### ISSUE TITLE
Logout issue

### ISSUE THREAD

**Issue by mguerrieri** [IdentityServer/IdentityServer4#10]
Was having an issue logging out from a javascript SPA client, so I tried the sample app with the javascript OIDC client sample and got the same error- from the VS Output window:

	Microsoft.AspNet.Hosting.Internal.HostingEngine: Information: Request finished in 0.0078ms 200 application/json
	Microsoft.AspNet.Hosting.Internal.HostingEngine: Information: Request starting HTTP/1.1 GET http://localhost:22530/connect/endsession?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A7017%2Findex.html&id_token_hint=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjIyNTMwIiwiYXVkIjoianNfb2lkYyIsImV4cCI6MTQ1MzA4NTA1MywibmJmIjoxNDUzMDg0NzUzLCJub25jZSI6IjY2NDA4MzI4MDQyNTgwNSIsImlhdCI6MTQ1MzA4NDc1MywiYXRfaGFzaCI6Im81RmpBbHp5MDNvU2NDczF5SUh0dkEiLCJzaWQiOiIxNzVhMzNmNTRmYmZiYWJjZjYyMGYzMzM4NjlhN2Y2YiIsInN1YiI6Ijg4NDIxMTEzIiwiYXV0aF90aW1lIjoxNDUzMDg0NzE0LCJpZHAiOiJpZHN2ciIsIm5hbWUiOiJCb2IgU21pdGgiLCJnaXZlbl9uYW1lIjoiQm9iIiwiZmFtaWx5X25hbWUiOiJTbWl0aCIsImVtYWlsIjoiQm9iU21pdGhAZW1haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIndlYnNpdGUiOiJodHRwOi8vYm9iLmNvbSJ9.e6tBWOM6A2kHP37Je78-kicslIdKv29TqHGxXgQLZwtZG6u0q8CkFfifksc4q0weXinWtXtVEMPISMOf9ZfHR5ALg4kxMlYyxQOQd3Yo-rqbqz4qLyylQ9FEWbxqfnOxt91uAlIyMjkIxDxIuTMKU	_K7VJtIr_jfM95DuFn7MwNI_yeRtDOsashIgXYwDFv4VDtl3-d7JNKy_Akmpz9mfh-xsiRrHNgffr229JZzXuPpm_pbkfhSKsxcRfoPWSNZn0KdWxUrVgixy7Noz5PtPyF8z95F7GClLKYACLqyYlRmj4yPJhGyn5QrRbbf3SgzXz19LuVhJhglZ0PKfAzYaA  
	Microsoft.AspNet.Authentication.Cookies.CookieAuthenticationMiddleware: Information: HttContext.User merged via AutomaticAuthentication from authenticationScheme: idsrv.
	Microsoft.AspNet.StaticFiles.StaticFileMiddleware: Verbose: The request path /connect/endsession does not match a supported file type
	Microsoft.AspNet.Routing.Template.TemplateRoute: Verbose: Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.
	Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler: Verbose: No actions matched the current request
	Microsoft.AspNet.Builder.RouterMiddleware: Verbose: Request did not match any routes.
	Microsoft.AspNet.Hosting.Internal.HostingEngine: Information: Request finished in 0ms 404 

Looks like a routing issue with the connect/endsession call?

**Comment by brockallen** [comment]
We don't have the end session endpoint implemented yet.
