### ISSUE TITLE
IUserService.AuthenticateExternalAsync

### ISSUE THREAD

**Issue by totht91** [IdentityServer/IdentityServer4#100]
While I'm investigating the current codebase of the IdentityServer4 to port my v3 application after RTM, I don't find the a new version of the old `IUserService` interface's `AuthenticateExternalAsync` approach. Is this now fully the controller's or the `ICustomGrantValidator`'s responsibility and not the IdentityServer's pipeline?

**Comment by brockallen** [comment]
Search the closed issues -- we discuss in there somewhere.
