### ISSUE TITLE
Add support for getting IdentityServer error details in ErrorMessage

### ISSUE THREAD

**Issue by akamud** [IdentityServer/IdentityServer4#1002]
### A little bit about our scenario:

We have many websites integrating via `code flow`, but, by far, the most common error is that they are using an invalid redirect URI. This generates a lot of work from our side, because AFAIK the only way to diagnose this is looking at the logs. We would like to detect this and provide a better error message so we don't have to look at the logs everytime.

### What we've tried

I'm getting the `ErrorMessage` similar to what is done [here](https://github.com/IdentityServer/IdentityServer4/blob/db1affb8a6574b90881c9a3da7a5ad1ec2e996b7/src/Host/Quickstart/Home/HomeController.cs#L29), but I just get the `unauthorized_client` that is set [here](https://github.com/IdentityServer/IdentityServer4/blob/544748cb918d378c4fe84320b9f362ebe7581330/src/IdentityServer4/Validation/TokenRequestValidator.cs#L249). I'm wondering if it would be possible to expose extra details about the error.

Is there a way to do this? Could this be supported?

**Comment by brockallen** [comment]
It sounds like you want a developer focused error message. As of now (other than the logging) we don't have that coded throughout IdentityServer so it's a bit of a task to do this. We'll assign this to 2.0.

What you might be able to do in the meantime is check the request id against what is persisted via the [event service](https://identityserver4.readthedocs.io/en/release/topics/events.html).

**Comment by brockallen** [comment]
The first step has been added: https://github.com/IdentityServer/IdentityServer4/issues/965
