### ISSUE TITLE
[Question/Support] Unable to get RedirectUri to Https

### ISSUE THREAD

**Issue by Franklin89** [IdentityServer/IdentityServer4#1009]
I am calling my IdentityServer from a ASP.NET Core application that is running behind a HAproxy for load balancing. I use HTTPS and SSL Termination at my HAProxy, so the internal communication (HAProxy to my web app is http). If I try to sign in everything works until I get redirected to my web app. There I get an error that the **message.State is null or empty**. If i check my logs I see tat the RedirectUri is still http? Is that the problem?

I followed this issue #213 to change the requests host header but that did not change anything.

My guess is that my IdentityServer is working correct, but not sure which part I am missing and would be happy if someone could point me into the right direction.

```json
{
  "ClientId": "web",
  "ClientName": "Web client",
  "RedirectUri": "http://xxx/signin-oidc",
  "AllowedRedirectUris": [
    "https://xxx/signin-oidc"
  ],
  "SubjectId": "anonymous",
  "RequestedScopes": "",
  "Raw": {
    "client_id": "web",
    "redirect_uri": "http://xxx/signin-oidc",
    "response_type": "code id_token",
    "scope": "openid profile offline_access guests hotels",
    "response_mode": "form_post",
    "nonce": "636266586037110270.NDcyZGZiNTEtZTI5My00NWQ3LTgyZWMtNzQ4YWRlY2U1NTc3NTBiMTE5OWUtYWE5ZC00MWMyLTg2NjYtYWU1YjgwZTMwNGU2",
    "state": "CfDJ8KhdnWmV5gRGhjtNaLv5hm9wVj9ZERFvhzxe5dFG8QQef_7CJns1YPiXeu5I2p_OgIjxGK-9tMEWRB_ppgqcdKgOuePfQoRBLrnzapgeZI7J5eCvcNW0aVlhNpRFf9nJw32XwBzHoTQggUDR0SOgzLv9SlxxTQeLIqXQrxWKIwEGhjtSi9fy8ZCDmlf6UMVlbiZJ5uRrCI_Ezc3keCFNxNPf7ozVP-5l4Xb6CHIsbnK0XwAhMpXYpQZo9d8wGmXyEwSzYFqjx1ZtR39Ikb0nFYEhJPyjkWu78-9WP-zf8cLltHLogcBeTCRSZc_29QYUzG2LXFIzOTwPrdikg8XXxxTbnZEKDAev5VKr142i0sVnysCkgaQsvHR1ttxgiyH7aQ",
    "x-client-SKU": "ID_NET",
    "x-client-ver": "2.1.3.0"
  }
}
```

**Comment by brockallen** [comment]
I guess you found the solution?

**Comment by Franklin89** [comment]
@brockallen Yes i got it fixed :-) thank you

The problem were the headers forwarded from the proxy to get the https working. But also had to some networking issues with docker and the windows firewall on my local machine.
