### ISSUE TITLE
Documentation doesn't expand how Federation Gateway can be implemented

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [IdentityServer/IdentityServer4#1011]
https://identityserver.io/ has section 
**Federation Gateway**
Support for external identity providers like (Azure) Active Directory, Google, Facebook etc. This shields your applications from the details of how to connect to these external providers.

However it is not a link and documentation search for "Federation Gateway" https://identityserver4.readthedocs.io/en/release/search.html?q=Federation+gateway&check_keywords=yes&area=default  doesn't give any more details.

I would appreciate any links giving more details, in particular  how to use Azure Active Directory as authentication provider with own implementation of authorization provider.

**Comment by TomCJones** [comment]
You can do all that with the app available on visual studio. Just create a web app with .Net core and select individual authentication. Links will be added to the code to tell you what to do next.

thx ..Tom (mobile)

On Apr 2, 2017 8:46 PM, michael-freidgeim-webjet <notifications@github.com> wrote:

https://identityserver.io/ has section
Federation Gateway
Support for external identity providers like (Azure) Active Directory, Google, Facebook etc. This shields your applications from the details of how to connect to these external providers.

However it is not a link and documentation search for "Federation Gateway" https://identityserver4.readthedocs.io/en/release/search.html?q=Federation+gateway&check_keywords=yes&area=default doesn't give any more details.

I would appreciate any links giving more details, in particular how to use Azure Active Directory as authentication provider with own implementation of authorization provider.
