### ISSUE TITLE
Initial Login Hangs with IdentityServer4

### ISSUE THREAD

**Issue by jobrien721** [IdentityServer/IdentityServer4#1015]
### Issue / Steps to reproduce the problem

- First I will go to the Sandbox site which then will re-direct me to the Identity Server
- Next I will sign in with credentials
- Then On the Way back to the Sandbox Site after Authenticating it gets hung up and I receive the following error:
**_Refused to load https://identityServerURL.com because it does not appear in the form-action directive of the Content Security Policy._**
 _Also the Site it is redirecting to is an https:// as well_

We are using Grant Type of Hybrid within the configuration of the IdentityServer4 

_Please note that if I go back to the site it then logs me in and authenticates just fine and sends the token like its suppose to and the whole site functions as it should, going to the API etc . . its just that initial login and redirect to the site that is causing the issue._

Thank you in advance for your time and all of your help!

_This issue is not an issue when running in Dev Mode on my Local machine it only happens when on the Live Sandbox Site_

**Comment by brockallen** [comment]
got it sorted?

**Comment by jobrien721** [comment]
Sorry for the delay yes I did get it sorted thank you for asking! For any future developers looks for this solution the issue was that I was using Grant Type of Hybrid and needed to use a Grant Type of Implicit.
