### ISSUE TITLE
Extracting Username from Token

### ISSUE THREAD

**Issue by vmalhar** [IdentityServer/IdentityServer4#1017]
I have an ASP.NET Core web api and a mvc client application secured by IdentityServer4.
When an web API request is made by the client, i need to do additional filtering on the data returned based on the username of the logged in user. Hence would like to extract the username of the logged in user in the web api controlled action. Is there a way to do this?

**Comment by brockallen** [comment]
Add that claim to the UserClaims collection on the configured ApiResource: https://identityserver4.readthedocs.io/en/release/reference/api_resource.html

**Comment by vmalhar** [comment]
Thanks Brock. That worked!!!

**Comment by zaibimed** [comment]
> Add that claim to the UserClaims collection on the configured ApiResource: https://identityserver4.readthedocs.io/en/release/reference/api_resource.html

can you please share the answer again, the page is not accessible :(

**Comment by jddonovan** [comment]
Just look for the same topic in the latest docs:
[](https://identityserver4.readthedocs.io/en/latest/reference/api_resource.html)

**Comment by marcsstevenson** [comment]
For clarity, this refers to the GetApis method within the example Config.cs. Below is an example which adds claim types to the API Resource:

        public static IEnumerable<ApiResource> GetApis()
        {
            return new ApiResource[]
            {
                new ApiResource("api1", "My API", claimTypes: new string[] { JwtClaimTypes.GivenName, JwtClaimTypes.FamilyName, JwtClaimTypes.Email, JwtClaimTypes.Role, "office" })
            };
        }
