### ISSUE TITLE
Basic QuickStart - Not Working

### ISSUE THREAD

**Issue by grahamehorner** [IdentityServer/IdentityServer4#1018]
I've read and followed the basic quick start instructions on how to configure IdentityServer4;
I'm using Windows 10 Enterprise Edition with VisualStudio 2017 the quick start fails to build
as according to VisualStudio the IServiceCollection extension methods aren't found as is the IdentityServer4 namespace however the nuget package has installed correctly 

### Issue / Steps to reproduce the problem
create a ASP.NET core empty web application
add IdentityServer4 via nuget package manager 
open the startup.cs

in the ConfigureServices method
add the line services.AddIdentityServer()

note red squiggle showing error ?
and failure to build

**Comment by leastprivilege** [comment]
restart visual studio?

**Comment by grahamehorner** [comment]
@leastprivilege I have done; same issue, don't think its VisualStudio 2017 cause the problem ?

**Comment by grahamehorner** [comment]
@leastprivilege interesting after a complete restart/reboot the project now builds/resolves the IdentityServer namespace, why interesting/odd well other projects seemed to have been work ok with other nuget packages, I wonder if this a roslyn issue given it builds in the projects background?

**Comment by grahamehorner** [comment]
@leastprivilege more infor as this is totally wired, after a complete restart creating a new asp.net core web application (empty) adding IdentityServer4 VS2017 doesn't recognise the namespace or extension methods; a restart of VS2017 doesn't help; however a reboot of the machine re-opening the project all is resolved ?

**Comment by grahamehorner** [comment]
@leastprivilege happy to record a video showing the issue if you'd like; I've been able to reproduce this one 3 machines now with a 100% :'( I'll try a VS2017 RC system to see if that is broken also

**Comment by leastprivilege** [comment]
Is that resolved?

I tried it today and it was working for me straight away.

**Comment by grahamehorner** [comment]
We are still have the issue; but we are looking to why this is happening and reporting it as a possible VS 2017 issue; We are going to link the tickets, but collecting more details, happy to post a video showing issue or allow you a remote desktop session so you can experience this firsthand ;)

**Comment by leastprivilege** [comment]
I see enough VS2017 firsthand every day - I have enough ;)

Closing - feel free to re-open if you have new info.

**Comment by grahamehorner** [comment]
@leastprivilege FYI this issue was created by a 401 error from a secure nuget repository which triggered something to make intellisense stop working; work around is to remove/disable protected nuget repository from solution and reference package on local disk; and nothing to do with identityserver nuget packages or nuget. thanks again from your help, hope/trust this will assist someone else should they come across the issues.

**Comment by BjarkeMeier** [comment]
I also experience the red line under the extension method. It however doesn't prevent the code from compiling. So it's apparantly "just" a UI bug.
