### ISSUE TITLE
External Provider Claims Transformation

### ISSUE THREAD

**Issue by grahamehorner** [IdentityServer/IdentityServer4#1019]
I'm attempting to capture the ProviderSubjectId from an external provider (Google,Facebook,Twitter) as a claim to the IdentityServer client, although the user contains both ProviderName ='Facebook' & ProviderSubjectId ='....' and these are added to the additionalClaims the client application (Web MVC) doesn't receive any claim/value key pairs holding the ProviderSubjectName/ProviderSubjectID.

These values will be user to access avatar/profile images provided by the oauth/identity provider, is this possible? what could I be doing wrong? or is there an example of transforming claims from an external provider into a superset of claims ?

**Comment by leastprivilege** [comment]
So - do you put the into the token in your profile service?

**Comment by grahamehorner** [comment]
Profile service? I'm using in memory store as this is in development and have modified the example account controller to add the ProviderSubjectId to the additional claims collection? I was hoping this would pass this across to the client? is my assumption incorrect? what would be the best way to achieve passing additional information to the client via the user claim?

**Comment by leastprivilege** [comment]
Whatever you pass as additional claims gets written into the signin cookie.

The profile service is who determines what gets put into the tokens (based on the requested scopes). 

Implement IProfileService and register it (or copy our default).

**Comment by grahamehorner** [comment]
@leastprivilege so would you expect the user claims on the client to include the items placed in the additionalClaims collection by IdentityServer ? or do you access the additional claims on the client by someother mean?

**Comment by leastprivilege** [comment]
the client will only receive what the profile service puts in the tokens. As easy as that.

Implement the interface, put a breakpoint into the 2 methods - it will be self-explaining.

**Comment by grahamehorner** [comment]
@leastprivilege thanks for your help; I'll look at the profile service;  it's my understanding around where additional claims are held which seems incorrect; which I assumed would be in the User.Claims on the client.

I do see the claims coming into the IdentityServer from the 3rd party, in the AccountController method ExternalLoginCallback but the token which is passed to the client doesn't hold all of the claims returned by the 3rd party service; it is also replacing the 3rd party's SubjectID with it's own? the scopes used for the 3rd party and clients match; ie: openid, profile, email 

Also are you able to point me in the direction of the IProfileService sample for ASP.NET Core ?

Thanks for your help and great work with IdentityServer4; would also love to more about the IdentityServer4 as a Service offering coming soon ;)

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/Interfaces/IProfileService.cs

What else do you need? Implement and debug it ;) have fun.

**Comment by grahamehorner** [comment]
@leastprivilege sorry but I don't understand why the client token isn't getting the claims; everything that the IdentityServer end ie. in the IProfileService events shows the claims #puzzled thanks again

**Comment by grahamehorner** [comment]
@leastprivilege starting to think this an issue with the client which is using the Microsoft OpenIdConnect provider? :'(

**Comment by leastprivilege** [comment]
The `GetProfileDataAsync` method passes in a context - the context has an `IssuedClaims` collection. Only what you put on that collection goes into a token.

Things don't happen auto-magically. sorry ;)

**Comment by grahamehorner** [comment]
@leastprivilege I must be begin a #noob here; as I can see some of the 3rd party claims in client; but not the others; I've added a test claim via the IProfileService and I can see this; but not all of the Subject.Claims make it over to the client? #noob #confused and sorry again for beginning a #noob

**Comment by leastprivilege** [comment]
None of the Subject.Claims make it over by default. You need to add them to the IssuedClaims collection.

**Comment by grahamehorner** [comment]
@leastprivilege that's not want I'm seeing if I sign in with google/facebook **some** of the claim provided by the 3rd party make it over these are shown in the Subject.Claim when the IProfileService event fires.? I'm able to copy the claims from the Subject.Claims into the IssuedClaims in the IProfileService prefixing them the claim type with "provider:" and these come over,  so I guess this must be a issue with my understanding; I'm going to have a lot of reading/hacking to obtain your level of knowledge around IdentityServer ;) thanks again for your help and very prompt replies.

**Comment by grahamehorner** [comment]
@leastprivilege after some digging around and having reviewed the source of the TestUserStore AutoProvisionUser method this is where the 3rd party claims are getting replaced with IdentityServer claims and mapped to the using the JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap which is why only some of the 3rd party claims are appearing in the client application and I was confused to how/where the mapping occurred as this is not immediately apparent in the quick start examples as it is hidden in the IdentityServer4.Test.TestUserStore source.  Now with better understanding of this and the concept I have created my own UserStore which uses the Microsoft DistributedCache to hold 3rd party claims performs mappings according to my requirements.

Thanks again for your help and pointing me the correct direction; and giving me a better understanding of the IdentityServer4 implementation; keep up the great work & great support.

**Comment by ferryferry** [comment]
@grahamehorner Do you have an example for me i'm facing the same problem, my userclaims are not mapped to the user in the client MVC..
