### ISSUE TITLE
Sign out from Identity Server 4 using Client (.net framework)

### ISSUE THREAD

**Issue by ShashikantMaurya** [IdentityServer/IdentityServer4#1023]
Hi,

I have used Identity Server 4,I have client(.net framework),As we can not use

HttpContext.Authentication.SignOutAsync("Cookies");
HttpContext.Authentication.SignOutAsync("oidc");

Please help me

**Comment by brockallen** [comment]
Not enough info.

**Comment by ShashikantMaurya** [comment]
Hi,

If we create client using Asp.Net Core then we can sign out using below code

HttpContext.Authentication.SignOutAsync("Cookies");
HttpContext.Authentication.SignOutAsync("oidc");

but i have created Client using .Net Framework so we can not use packages of Asp.Net Core,i need to sign out.

Please help me

**Comment by leastprivilege** [comment]
You need to do a redirect to the end session endpoint manually.

Check the spec:
https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

**Comment by brockallen** [comment]
Moar docs: https://identityserver4.readthedocs.io/en/release/endpoints/endsession.html

**Comment by prflores** [comment]
Hi, sorry for writing on a closed issue, but I am trying to do the same. I posted in SO about my problem -
[https://stackoverflow.com/questions/48365146/sign-out-identityserver4-with-identityserver3-library-in-mvc-client]
Thank you.

**Comment by prflores** [comment]
@leastprivilege i tried doing a manual redirect call but i'm still being signed-in automatically. When after redirecting to the homecontroller index page and clicking to a page where there's [Authorize] attribute.

```
        [HttpGet]
        [Authorize]
        public ActionResult SignOut()
        {
            //Request.GetOwinContext().Authentication.SignOut();
            var identity = (ClaimsIdentity)User.Identity;
            IEnumerable<Claim> claims = identity.Claims;
            var idToken = claims.FirstOrDefault(c => c.Type == "id_token").Value;
            return Redirect(AppConstants.AuthServer() + "/connect/endsession?id_token_hint=" + idToken + "&post_logout_redirect_uri=" + AppConstants.ClientServer() + "/signout-callback-oidc");
        }

        //signout-oidc redirect
        [AllowAnonymous]
        public ActionResult LogoutCallback()
        {
            Request.GetOwinContext().Authentication.SignOut("Cookies");
            //Request.GetOwinContext().Authentication.SignOut("oidc");
            return RedirectToAction("Index", "Home");
        }
```
