### ISSUE TITLE
[Question] IdentityServer Flow

### ISSUE THREAD

**Issue by odysseus1973** [IdentityServer/IdentityServer4#1024]
Hello!

I have several customers (stores) who must have access to my API, each of them issued a unique identifier, login and password. These clients will modify their own software to connect to my API. My API and Identity Server 4 are located on different servers, if this is important. Each client software must, using an identifier (login) and password, be able to access the API, and in the API I must receive the client ID and its access rights to the API. What kind of flow should I use? I read all IdentityServer4 docs, but can't find right flow in my case...

Thanks!

**Comment by leastprivilege** [comment]
Sounds like client credentials flow to me. Password become client secrets.


-------
Dominick Baier

**Comment by odysseus1973** [comment]
Hello!

Thanks for answer. As far as I understand, I have to create an IdentityServer client for my API with ClientCredential Flow and clients for each store with ClientCredential Flow. Each store must requests a token on the IdentityServer with clientId and secret and then access my API with this token. Right?

**Comment by leastprivilege** [comment]
yes
