### ISSUE TITLE
DefaultGrantStore checking expiration, logging expired grants as not found

### ISSUE THREAD

**Issue by chrisowhite** [IdentityServer/IdentityServer4#1025]
### Issue
The DefaultGrantStore is checking grant expiration in GetItemAsync() and then returning null if the grant is expired. This causes callers to log expired grants as not found, when they were in fact found but just expired. The validators that ultimately call into DefaultGrantStore never hit their own expiration checks that would more accurately log the situation.

We're not currently requiring consent for any of our clients, so I'm not as clear on how that is affected.

For example, this bit in DefaultGrantStore
```
protected async Task<T> GetItemAsync(string key)
{
    key = GetHashedKey(key);

    var grant = await _store.GetAsync(key);
    if (grant != null && grant.Type == _grantType && !grant.Expiration.HasExpired())
    {
        try
        {
            return _serializer.Deserialize<T>(grant.Data);
        }
        catch(Exception ex)
        {
            _logger.LogError("Failed to deserailize JSON from grant store. Exception: {0}", ex.Message);
        }
    }

    return default(T);
}
```

Which ultimately means this in TokenValidator.ValidateReferenceAccessToken() never logs an expired reference token and the token is not removed.
```
if (IdentityServerDateTime.UtcNow >= token.CreationTime.AddSeconds(token.Lifetime))
{
    LogError("Token expired.");

    await _referenceTokenStore.RemoveReferenceTokenAsync(tokenHandle);
    return Invalid(OidcConstants.ProtectedResourceErrors.ExpiredToken);
}
```

### Steps to reproduce the problem
Introspect with an expired reference token.
Attempt to exchange an expired refresh token.
Request a token with an expired authorization code.

**Comment by chrisowhite** [comment]
Went and looked into the unit tests. It looks like it's passing the expired reference token test because of this in `DateTimeExtensions`.

```
public static bool HasExpired(this DateTime expirationTime)
{
    if (expirationTime < IdentityServerDateTime.UtcNow)
    {
        return true;
    }

    return false;
}
```

When the test runs `expirationTime` equals the value returned from `IdentityServerDateTime.UtcNow` so `HasExpired` returns call. `TokenValidator` is evaluating "less than or equal to" while this is only "evaluating less than."

**Comment by chrisowhite** [comment]
I can take a stab at fixing this. Making the expiration inequality evaluation consistent (I feel appropriately) breaks the expired reference token test fail. I just need to know how to proceed. I feel that if the current time equals the expiration time, the token is expired. Since callers down the call stack perform expiration checks, seems reasonable to remove that check from the DefaultGrantStore, since they exist, they're just expired.

**Comment by brockallen** [comment]
How's this situation different than the record having been cleaned up in the DB after its expiration?

**Comment by chrisowhite** [comment]
The problem is it doesn't appear that they're being cleaned up in the DB, since DefaultGrantStore returns null, which means the block that removes them from the store is never hit. Plus I've got tons of log messages for grants not being found that are still sitting in our persisted store.

**Comment by brockallen** [comment]
Is the main problem as you see it that an error appears in the log? Or the lack of a log message indicating that it's found but expired?

**Comment by brockallen** [comment]
Also, another question seeking feedback: would you expect our plumbing to then delete a loaded grant that was found to expire?

Finally, you are using our EF library? There's a helper to cleanup expired grants: https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/Host/Startup.cs#L83

**Comment by chrisowhite** [comment]
I see 2 issues. 

1. The not found error message had me trying to track down something that was never really a problem, since all I'm seeing is those messages and none that indicate they were just expired reference tokens (most of what I'm seeing) or authorization codes.

2. With the current implementation, I would expect them to be removed, but that doesn't appear to be happening.

As far as your request for feedback, I feel that grant validation should be as fast as possible. I don't feel that it's necessary to await a remove from what could potentially be backed by a persistent store in order to validate a grant, as long as there's some other mechanism to clean them up. We're using MongoDB store these, so I can just put a TTL index on the expiration time in our case, and that's totally fine with me since we have a way to manage it. It's nice to keep them around for a little bit in case we need to trouble shoot anything so it would be nice to be able to manage that in a way that we see fit.

**Comment by brockallen** [comment]
Ok, I just pushed changes to address 1.

**Comment by chrisowhite** [comment]
Just took a look at your commit. https://github.com/IdentityServer/IdentityServer4/commit/bc70197f1b57b542a5f8a2e3b9b0f161a9777fad

It looks like I would see a new expired grant message as well as the invalid grant message since a null value is still returned from `DefaultGrantStore`. In my mind I was thinking remove the expiration check from `DefaultGrantStore` and remove the call in `TokenValidator.ValidReferenceAccessTokenAsync()` that removes the grant from the store, it seemed everything that was calling into the store was doing their own expiration checks. That way you only get a single log message, invalid if not found, expired if it's expired.

**Comment by brockallen** [comment]
I'll let @leastprivilege decide

**Comment by chrisowhite** [comment]
Thanks @brockallen and @leastprivilege. Appreciate the attention to this!
