### ISSUE TITLE
An api written in PHP

### ISSUE THREAD

**Issue by eld1887** [IdentityServer/IdentityServer4#1029]
Hi,
i´m new to this theme, so maybe my question is stupid. 
I want use the IdentityServer4 with my Api (it should be a kind of a fileserver) written in php.
So my question is how can i "connect" my php api to the identityServer, so that he protect my php Api? is´t correct that i "only" need to use openid? Maybe someone have an example?

I would be grateful for any reference.
greetings

**Comment by leastprivilege** [comment]
IdentityServer issues access tokens - you send those access tokens to your PHP API. We use the standard JWT format.

I would concentrate my research on how to consume JWT tokens in PHP.
