### ISSUE TITLE
UserStore Interface & Dependancy Injection

### ISSUE THREAD

**Issue by grahamehorner** [IdentityServer/IdentityServer4#1031]
I'm wondering why there is no IUser or IUserStore interfaces; if IdentityServer had these the AddTestUsers extension method could then be changed to a generic implementation named AddUsers<TestUserStore,Test , >(IEnumerable<IUser> populateWith ) accepting the type/implementation to be used/registered with DI; these could also be optional and default to an internal implementation.

the idea would be to allow developers to swap in/out the implementation while conforming to the interface contracts.

extension method example :-
 
        public static IIdentityServerBuilder AddUsers<
            TUserStore,
            TUserProfileService,
            TUserResourceOwnePasswordValidator>
            (
                this IIdentityServerBuilder builder
            )
            where TUserStore : class, IUserStore , new()
            where TUserProfileService : class, IProfileService, new()
            where TUserResourceOwnePasswordValidator : class, IResourceOwnerPasswordValidator, new()

**Comment by leastprivilege** [comment]
We discussed that - but we don't see a huge benefit. 

Most user management libraries are either ASP.NET Identity or custom - no need to push them into somer other abstraction that's probably in the way at some point.

**Comment by grahamehorner** [comment]
would this not give opportunity to a developer to do custom user management for multi tenant services, I understand not wishing to add layers of abstract where not needed, however I see a need in my environment to have different user store, profile services and validation used at runtime based on the client endpoint. Don't know if that is possible? thinking aloud
