### ISSUE TITLE
Redirect ALREADY AUTHENTICATED users back to ID server to re-login and re-grabbing new token

### ISSUE THREAD

**Issue by agrebenyuk** [IdentityServer/IdentityServer4#1032]
My resource server has got IdServer4 client installed and everything was fine until I introduced Authorization attribute on Resource server which throws 401 if Principal does not contain all necessary claims.

Once I navigate to the controller decorated with this attribute I can catch in debug that in RedirectToIdentityProvider 
n.ProtocolMessage.RequestType == OpenIdConnectRequestType.AuthenticationRequest

And this is correct ,- I need to make user go to Id Serve login page and log in with different credentials and obtain new token with right Claims. The resource server redirects the request to https://idserver:5000/connect/authorize?......   instead

And I presume that IdServer responds that Resource server is already authenticated and redirects back to resource server and then I have infinite loop..

What technique do I need to use to have correct behavior when I need to Redirect AUTHENTICATED users ,which don't have right permissions, to IdServer to re-login and be reissued with new token ?

**Comment by leastprivilege** [comment]
So do you want them to go back to identityserver to re-login - or do you want to show an "access denied" page?

**Comment by agrebenyuk** [comment]
Ideally first one, if this is possible. If not, second option would be handy.

Or maybe controllable combination of those two behaviors. This would cover scenarios like using the token in between different web sites using the same idserver where some websites accept the token and some parts (controllers)of of other websites require additional claims etc

**Comment by leastprivilege** [comment]
You need to set the AutomaticChallenge to false on the MW - and rather make your decision on the access denied page - you can trigger the OIDC MW manually by calling Challenge and pass the prompt parameter to force the login page again.

This sounds like crazy talk - well - thank Microsoft for badly documenting their stuff.

**Comment by agrebenyuk** [comment]
` app.UseOpenIdConnectAuthentication(openIdConnectAuthenticationOptions );`
with `new OpenIdConnectAuthenticationOptions` object passed there . And this OpenIdConnectAuthenticationOptions does not seem to have AutomaticChallenge property.

I may be using wrong MW or Options , please let me know. I am using those just I 've seen they are used in on of the Clients samples you have though. Is there any "Client" samples that you would recommend looking at which would cover (or would be close to cover) case similar like this?

**Comment by leastprivilege** [comment]
Ah this is Katana, yes?

**Comment by agrebenyuk** [comment]
Yeah, that's right!

**Comment by leastprivilege** [comment]
OK - well - I would write a middleware that checks the response status code - and if it is 401 and the user is authenticated, I would challenge the OIDC middleware with the prompt=login parameter.

I don't have a sample for that, sorry.
