### ISSUE TITLE
reading the custom scope values from token

### ISSUE THREAD

**Issue by cllp** [IdentityServer/IdentityServer4#1033]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

Hi, I have configured a custom scope in IS4 in order to provide additional user info, like role and email. My question, I see the custom.scope claim in my WebApi (User.Identity.Claims), but how do I get the value from it?

![image](https://cloud.githubusercontent.com/assets/4180750/24788522/4b7183de-1b6e-11e7-85e2-debe29b69b3c.png)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
By configuring the api resource user claims - or by calling the userinfo endpoint.

**Comment by cllp** [comment]
Thanks very much for your answer Dominick. I meant in the API that I´m protecting. I configured the claims in IS4 and I get/see the claims fine in the client application. I just don´t know how I get the values from the token in the resource API. Could you refer to any examples where a token is sent and authorized in an API and where all claims (scope) values are revealed from the User Identity?

**Comment by leastprivilege** [comment]
You need to configure the claims with the API resource as well.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by cllp** [comment]
Hi again, do you have an examples for how to update the claims in the API resource? Did not eally understand if you meant "calling the userinfo endpoint" from the client or the resource API in your previous reply.

**Comment by leastprivilege** [comment]
new issue.
