### ISSUE TITLE
Why to use identity server while we have adfs ?

### ISSUE THREAD

**Issue by nourBerro** [IdentityServer/IdentityServer4#1035]
In my organisation im trying to apply sso and we have adfs server. 
So should i use adfs or implement identityserver ? Why?

**Comment by leastprivilege** [comment]
If ADFS has all the features you need - then you don't need IdentityServer.

**Comment by nourBerro** [comment]
I hope some one who knows more about adfs and identity server to answer the question

**Comment by kenneth-y** [comment]
you should at least have a list high-level requirements that your organization need for your SSO implementation. then you try to find out the features that are available from adfs and IdentityServer then assess which implementation suits your organization.

**Comment by TomCJones** [comment]
ADFS is not an identity provider, it is an identity translator.

If you have AD as your identity provider, ADFS is a good translator.

..tomj

________________________________

**Comment by nourBerro** [comment]
@tomCJones so the main advantage of identity server over adfs is idsrv able to authenticate from many providers like google aspnetIdentity. But adfs os only authenticate using AD 
Is there any other differences?

**Comment by TomCJones** [comment]
actually, that is not what I was trying to say.

ADFS allows authentication from a wide variety of RPs, far wider than Identity Server which is limited to OIDC.

ADFS does not act as an identity provider, which Identity Server can do.

ADFS typically uses AD as an identity provider.

..tomj

________________________________
