### ISSUE TITLE
ids4 configured to use external Login page and hosted in an application within iis produces duplicated path in the returnUrl

### ISSUE THREAD

**Issue by rurdea** [IdentityServer/IdentityServer4#1036]
When using a custom external Login url (options.UserInteraction.LoginUrl) the returnUrl querystring parameter that is passed by identityserver to the Login page contains duplicated base path if identityserver runs in an application within IIS (eg: DefaultWebsite\App).

Looking at the source code, it appears that the duplication comes from setting the HttpContext.Request.PathBase to both, IdentityServerBaseUrl and returnUrl:

(snippet from IdentityServer4.Endpoints.Results.LoginPageResult)
```
        public Task ExecuteAsync(HttpContext context)
        {
            Init(context);

            var returnUrl = context.Request.PathBase.ToString().EnsureTrailingSlash() + Constants.ProtocolRoutePaths.AuthorizeAfterLogin;
            returnUrl = returnUrl.AddQueryString(_request.Raw.ToQueryString());

            var loginUrl = _options.UserInteraction.LoginUrl;
            if (!loginUrl.IsLocalUrl())
            {
                // this converts the relative redirect path to an absolute one if we're 
                // redirecting to a different server
                returnUrl = context.GetIdentityServerBaseUrl().EnsureTrailingSlash() + returnUrl.RemoveLeadingSlash();
            }

            var url = loginUrl.AddQueryString(_options.UserInteraction.LoginReturnUrlParameter, returnUrl);
            context.Response.RedirectToAbsoluteUrl(url);

            return Task.FromResult(0);
        }
```

Notice in the above snippet that, when initialised, the returnUrl is prepended with the PathBase, and then, after the IsLocalUrl check is made (which is false in my case), it is again prepended with the GetIdentityServerBaseUrl which contains the PathBase and results in the duplication.

I think the GetIdentityServerBaseUrl call should be replaced with GetIdentityServerOrigin.

Thanks,
Radu

**Comment by brockallen** [comment]
fixed, thanks for the report.

**Comment by iwollmann** [comment]
I have a similar issue here and my doubt is why the OidcReturnUrlParser accepts only local urls in the verification? Is something related to the oidc specification? Today I'm registering my custom parser to bypass this issue.

**Comment by leastprivilege** [comment]
@brockallen ?

**Comment by brockallen** [comment]
Correct, as of now it looks like it only allows local URLs: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/OidcReturnUrlParser.cs#L51

Originally we deliberately only allowed local, as we planned on providing more formal support for external login pages. Perhaps we don't need formal support, and just want to remove the local restriction for now? I think we need a new issue to explore this.
