### ISSUE TITLE
How to remove scopes from an MVC client request?

### ISSUE THREAD

**Issue by EPinci** [IdentityServer/IdentityServer4#1038]
Per [Identityserver4 Default Scopes](https://leastprivilege.com/2016/09/14/new-in-identityserver4-default-scopes/) if no scope is sent on an authentication request, all the AllowedScopes claims for the client are sent. Do I read it correctly?

Is there a way to have the .UseOpenIdConnectAuthentication from an MVC application *not* to send out the scope in order to leverage this? The Scope property is readonly and if I do this:
```
   app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
   {
      [...]
      Scope = { "" },
      [...]
   }
```
The authentication request is still sent out with a scope set to "opened profile".
Any hint?

Thank you!

**Comment by leastprivilege** [comment]
It says

> At the token endpoint, scope is now optional (IOW for client credentials, resource owner and extension grants requests).

the OIDC MW uses the authorize endpoint - not the token endpoint.

**Comment by EPinci** [comment]
I see, thank you for the clarification!

If anybody else bump into this, specs are [here](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)

**Comment by merijndejonge** [comment]
I think I follow the spec by specifying _only_ `openid` as scope. Still I the generated request contains both `openid` and `profile`. Why? See my `OpenIdConnectOptions` below:

```csharp
   new OpenIdConnectOptions
   {
      SignInScheme = "cookie",
      ClientId = "openIdConnectClient",
      Authority = "https://localhost:44375/",
      ResponseType="code",
      Scope = {"openid" },
   };
```
This results in the following request to IdentityServer4:
```
   GET /connect/authorize?
      client_id=openIdConnectClient&
      redirect_uri=https%3A%2F%2Flocalhost%3A44321%2Fsigninoidc&
      response_type=code&
      scope=openid%20profile&
      response_mode=form_post&
      nonce...
```
Observe the `scope` parameter in the request which contains `openid` _and_ `profile`.

Any suggestions about how to get rid of the profile scope in the request?

Thanks in advance!

**Comment by leastprivilege** [comment]
you need to manually clear the scope collection. Thank Microsoft for that. @tratcher

**Comment by merijndejonge** [comment]
Thanks for the answer.
I'm so much of an expert (yet), Could you be so kind and explain how I can manually clear that scope collection?

Thanks again!

**Comment by leastprivilege** [comment]
```csharp
var options = new OpenIdConnectOptions();
options.Scope.Clear();
options.Sope.Add("openid");
```

**Comment by merijndejonge** [comment]
Thanks that helped!
