### ISSUE TITLE
[Question] Opening solution in Visual Studio for mac requires inclusion of <TargetFramework>

### ISSUE THREAD

**Issue by jorgecotillo** [IdentityServer/IdentityServer4#1039]
There is a question I have and maybe someone can give me some additional information.

### Scenario:

I just cloned IdentityServer4 repo and tried to open it up in Visual Studio for Mac (Preview 6 - 7.0 build 2715) and wasn't able to compile the solution unless I make some updates to IdentityServer4 project:

1. Update netstandard1.4 to netstandard1.7 in ``<TargetFrameworks> ``
2. Update `` <PropertyGroup> `` conditions from netstandard1.4 to netstandard1.7

After doing this, I was able to restore the nuget packages successfully but then got around 520+ errors related to missing references - which is misleading because the restore worked successfully.

In order to properly load the solution, here is the update required:

1. Remove ``<TargetFrameworks>``
2. Add ``<TargetFramework>netstandard1.7</TargetFramework>``

Now I am able to compile and run the solution.

The question I have is, Why I need to remove TargetFrameworks and add TargetFramework? Even if I updated the previous TargetFrameworks netstandard1.4 reference to netstandard1.7 it did not work.

Thanks in advance for the help.

### Environment info

```
.NET Command Line Tools (1.0.1)

Product Information:
 Version:            1.0.1
 Commit SHA-1 hash:  005db40cd1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.1
```

**Comment by leastprivilege** [comment]
Please open a bug at Microsoft.
