### ISSUE TITLE
When using Asp.Net Core Application(.Net framework) + .net 4.6.2

### ISSUE THREAD

**Issue by oferAshkenazy** [IdentityServer/IdentityServer4#104]
Hi,
I keep getting the following error "Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

The code which triggers the error ==> app.UseIdentityServer();

Thanks

**Comment by bburman** [comment]
@oferAshkenazy I had the same issue and tagged it here:

#95 

I had to manually copy that one and a couple of other DLLs to my output directory after compile. I can't tell where the bug lies. I wonder if it is a problem with IdentityServer4, NuGet, or the .NET Framework installer...

**Comment by brockallen** [comment]
Yes, we've also seen some of these odd errors. I think we found that including a reference in project.json addresses the problem. Still unknown why (we think it's some transitive dependency where the nuget package is not listed).

**Comment by YannisMarios** [comment]
Could you please indicate which package you have added in your project.json?

**Comment by brockallen** [comment]
The ones it complains about.

**Comment by YannisMarios** [comment]
I have added     "System.Runtime": "4.1.0-rc2-24027"

But I still get the same error:

System.IO.FileNotFoundException
Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by brockallen** [comment]
Sorry then -- not sure what that issue is.

**Comment by YannisMarios** [comment]
My project.json is:

{
  "dependencies": {
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "IdentityServer4": "1.0.0-beta2",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0-rc2-final",
    "System.Runtime": "4.1.0-rc2-24027"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "net462": { }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

**Comment by YannisMarios** [comment]
Whatever I do I can't install "System.Runtime": "4.1.0-rc2-24027" ...

I always end up with version 4.0.20

![image](https://cloud.githubusercontent.com/assets/11289298/15589162/5434a8b0-239a-11e6-8d1c-5e76ee307d1e.png)

**Comment by brockallen** [comment]
Sorry -- that's one I've not run into. Without IdSvr do you still have the problem? IOW, try to minimize the code until you find what triggers it.

**Comment by YannisMarios** [comment]
I suspect the problem is with .net4.6.2 PREVIEW. Some dlls are missing from the framework among them...System.Runtime.

I dont know what to do. I already have class libraries .net4.6.2 and i cant use them with asp.net core rc2 and your idsrv4.

**Comment by oferAshkenazy** [comment]
solved
as bburman mentioned manual copy is the answer

Here are the steps to overcome the problem:
1. I created 4.6.2 Web api core project (.net framework) 
2. Used nuget to add identityserver4
3. Packaged my 4.6.1 class library into package and added it to my Web api project
** using nuget to add System.runtime to the Web api project does not help
4. I created a small class library project (4.6.2) using nuget added system.runtime dll
5. copied System.runtime from my class library to my Web api project bin folder

Thanks for all the help

**Comment by YannisMarios** [comment]
@oferAshkenazy Nice! Thank you for sharing.

I think I will go on with IdentityServer3 and wait for the team to fix issues of v4.

**Comment by leastprivilege** [comment]
i updated all the packages - give it a go and see if that works better for you (and open a new issue if you encounter problems)

**Comment by paulczy** [comment]
I can confirm it is fixed in my project. Thanks Dominick.
