### ISSUE TITLE
SecurityHeaderAttribute as part of IdentityServer4

### ISSUE THREAD

**Issue by siberianguy** [IdentityServer/IdentityServer4#1043]
I'm building my web site authentication around IdentityServer4 and Samples project is extremely useful (thanks a lot for that!).  But there's one thing I noticed: most quickstart projects use **SecurityHeadersAttribute**. To be honest I have no idea about the story behind SecurityHeadersAttribute code. One part of me guesses authentication is vulnerable to some kind of attacks without it, the other part treats all the code in Samples project as optional. So wouldn't it be better to have SecurityHeadersAttribute as part of IdentityServer4 to stress its improtance?

**Comment by brockallen** [comment]
That's from the quickstart UI, not part of IdentityServer itself. It implements [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) in the UI.
