### ISSUE TITLE
Consider setting a default for CORS PreflightCacheDuration.

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1047]
https://github.com/IdentityServer/IdentityServer4/issues/579#issuecomment-293063364

**Comment by brockallen** [comment]
I'm now torn on this -- this is really a prod-only setting and should be part of the deployment checklist that any normal app should go through. If we set it by default (or even in release only builds) then it's not obvious and changes behavior depending on that scenario. 

I'm inclined to not add this.

**Comment by leastprivilege** [comment]
The default should be no-cache - same as for the discovery doc (and for the same reasons).

**Comment by brockallen** [comment]
So then this is a no-fix.
