### ISSUE TITLE
Allow for a separate "RedirectAuthority" url

### ISSUE THREAD

**Issue by JoshYaxley** [IdentityServer/IdentityServer4#1051]
I think it would be useful to be able to have separate authorities defined for internal HTTP communication and browser redirects.

## My scenario

I'm setting up a dockerised Identity Server with example APIs and clients, for me to get to grips with the technology and provide a base for future projects.

For example, my MVC client middleware can be set up like this:

``` csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
    AuthenticationScheme = "oidc",
    SignInScheme = "Cookies",

    Authority = "http://identityserver:5000",
    RequireHttpsMetadata = false,

    ClientId = "example-mvc-client",
    SaveTokens = true
});
```

Because both my client and identity server are within the docker network, they can communicate using their aliases. Setting the authority like this allows my client to communicate to my identity server. However, the authority is also used for browser redirects (when a user accesses a secured part of the client, they are redirected to the identity server to sign in). Because the user has no concept of the "identityserver" container, this redirection obviously fails.

Alternatively, I can set:

``` csharp
Authority = "http://localhost:5000"
```

Where `identityserver:5000` is port-forwarded to `localhost:5000` in my `docker-compose.yml`.

This allows the redirects to work, but the internal HTTP communication will now fail because my client container will try to talk to its own localhost, rather than the identityserver container.

There is a workaround for this by setting the `identityserver:localhost` in the docker-compose links or network alias sections. However, this doesn't strike me as a good solution for production (and I can't actually get it to work in development - though I do know the [docker sample](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Docker) has it working).

## Suggestion

I think, ideally, you would be able to set-up your middleware like this:

``` csharp
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
{
    AuthenticationScheme = "oidc",
    SignInScheme = "Cookies",

    Authority = "http://identityserver:5000",
    RedirectAuthority = "http://localhost:5000",
    RequireHttpsMetadata = false,

    ClientId = "example-mvc-client",
    SaveTokens = true
});
```

The `Authority` property would be used for internal HTTP communication (container to container), and the `RedirectAuthority` property would be used for redirecting the user to the identity server's login UI.

The `RedirectAuthority` property could be optional, and, if not set, the `Authority` property would be used for redirects, thus not breaking anyone's existing code and not adding extra configuration for people that don't need it.

-----------------------------------------------

This would be useful in any situation where the user's machine and the client cannot both refer to the identity server via the same URL. Is there a need for this? Is it low priority? Have I misunderstood the problem?

**Comment by brockallen** [comment]
`UseOpenIdConnectAuthentication` is Microsoft's library, not ours. You should bring this suggestion to them: https://github.com/aspnet/security/issues

**Comment by JoshYaxley** [comment]
Apologies! Thank you for pointing me in the right direction.
