### ISSUE TITLE
is EnablePostSignOutAutoRedirect option available in Idsvr4

### ISSUE THREAD

**Issue by naveenkumarreddy** [IdentityServer/IdentityServer4#1054]
I am using IdentityServer4 but unable to point out EnablePostSignOutAutoRedirect option in this version.

**Comment by naveenkumarreddy** [comment]
Sorry found it

**Comment by DureSameen** [comment]
where it is?

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/release/Quickstart/Account/AccountOptions.cs#L16
