### ISSUE TITLE
Consider implicit refresh tokens

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1056]

**Comment by brockallen** [comment]
Umm, what did I mean here?

**Comment by leastprivilege** [comment]
Getting a refresh token without explicitly asking for offline_access - the spec distinguishes between the two use cases.

Not sure we want to go down that rabbit hole.

**Comment by brockallen** [comment]
Ah, ok -- I confused myself by using the word implicit.

**Comment by brockallen** [comment]
Hmm, maybe this could easily be done just by adding a new "refresh_token" grant type. So if you have this, you automatically get a refresh token in the code exchange token response. For clients that need user-consented offline access, then that as an explicit flag remains the same as it is today.

**Comment by leastprivilege** [comment]
Why not always give a refresh token if `AllowOfflineAccess` is set. Then record somewhere the fact if the client asked for the token explicitly or not..
