### ISSUE TITLE
Data type for scope in access token

### ISSUE THREAD

**Issue by akshetty9** [IdentityServer/IdentityServer4#1061]
Scope in access token of IDS 4 is always a array of strings.

> {
>   "nbf": 1492094223,
>   "exp": 1492097823,
>   "iss": "http://server/core",
>   "aud": [
>     "http://server/core/resources",
>     "ApiResource1"
>   ],
>   "client_id": "TestClient",
>   "scope": [
>     "Api1",
>     "Api2"
>   ]
> }

But the result of introspection shows scope as space separated string

> {
>   "iss": "http://server/core",
>   "nbf": 1492096836,
>   "exp": 1492100436,
>   "aud": [
>     "http://server/core/resources",
>     "ApiResource1"
>   ],
>   "client_id": "TestClient",
>   "scope": "Api1 Api2",
>   "active": true
> }

As per the [specification](https://tools.ietf.org/html/rfc6749#section-3.3) it should be list of space limited string.
Any reason for making this as array?

**Comment by leastprivilege** [comment]
You are right on they way in - but in the token they become claims.
The introspection spec mandates the string format. 

So there is not really a spec that describes how scopes should be formatted in an access token (not even the name of the scope claim is defined).

Splitting it up into a JSON array works best for most platforms.

**Comment by akshetty9** [comment]
Ok. What I found in this [spec](https://tools.ietf.org/html/rfc6749#section-3.3) is that, it specifies the format to be list of space- delimited, case-sensitive strings. In section [4.2.2](https://tools.ietf.org/html/rfc6749#section-4.2.2) it refers to section 3.3 for the scope parameter

**Comment by leastprivilege** [comment]
Yes. We do return the scope parameter as per spec.

**Comment by akshetty9** [comment]
Then it should be space separated list of strings ☺️

**Comment by leastprivilege** [comment]
No. Read the spec again :)

**Comment by akshetty9** [comment]
https://tools.ietf.org/html/rfc6749#section-4.2.2
Okay. This is what i read. Not sure If this the right place to look at. Thanks for you time.

4.2.2.  Access Token Response
scope
         OPTIONAL, if identical to the scope requested by the client;
         otherwise, REQUIRED.  The scope of the access token as
         described by Section 3.3.

3.3.  Access Token Scope

   The authorization and token endpoints allow the client to specify the
   scope of the access request using the "scope" request parameter.  In
   turn, the authorization server uses the "scope" response parameter to
   inform the client of the scope of the access token issued.

   The value of the scope parameter is expressed as a list of space-
   delimited, case-sensitive strings.  The strings are defined by the
   authorization server.  If the value contains multiple space-delimited
   strings, their order does not matter, and each string adds an
   additional access range to the requested scope.

**Comment by leastprivilege** [comment]
The scope response parameter is specified. That's what we return. 

You are referring to the content of the access token. Which is not specified.

**Comment by akshetty9** [comment]
Ah. Ok I get it. Don't see anything specified for the scope inside the access token. Thanks.

**Comment by UbhiTS** [comment]
So, ID4 always outputs the scope as an array of strings ?

**Comment by leastprivilege** [comment]
IIRC - the IClaimsService
