### ISSUE TITLE
set_AbsoluteExpiration does not have an implementation.

### ISSUE THREAD

**Issue by ayayalar** [IdentityServer/IdentityServer4#1062]
### Issue / Steps to reproduce the problem
1. Run command dotnet new is4inmem
2. Start 
3. Unhandled exception thrown.
4. See attached log file

### Relevant parts of the log file
[identityserver4_log.txt](https://github.com/IdentityServer/IdentityServer4/files/920685/identityserver4_log.txt)

```
<log goes here>
```

**Comment by leastprivilege** [comment]
did you do a restore?

**Comment by ayayalar** [comment]
Yeah, no difference

**Comment by leastprivilege** [comment]
can't repro.

**Comment by ayayalar** [comment]
Looks like I ran into a dotnet core version hell. I did reinstall dotnet sdk. I can no longer pro either. Sorry for the trouble.
