### ISSUE TITLE
IdentityServer DI differences with StructureMap 

### ISSUE THREAD

**Issue by no1melman** [IdentityServer/IdentityServer4#1064]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

Here's my `startup.cs`

```
using System;
using StructureMap;

namespace Custom.Website
{
    using System.Collections.Generic;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Logging;
    using IdentityServer4.Models;
    using Microsoft.AspNetCore.Http;

    public class Startup
    {
        public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            Configuration = builder.Build();
        }

        public IConfigurationRoot Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            // Add framework services.
            services.AddMvc();
            services.AddIdentityServer()
                .AddTemporarySigningCredential()
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddInMemoryClients(Config.GetClients());

            var container = new Container(cfg =>
            {
                cfg.Scan(s =>
                {
                    s.TheCallingAssembly();
                    s.WithDefaultConventions();
                });

                cfg.Populate(services);
            });

            return container.GetInstance<IServiceProvider>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseIdentityServer();
            app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:5000",
                RequireHttpsMetadata = false,

                ApiName = "all",

            });
            app.UseStaticFiles(new StaticFileOptions
            {
                OnPrepareResponse = ctx =>
                {
                    ctx.Context.Response.Headers.Append("Cache-Control", "no-cache");
                }
            });
        }
    }

    public class Config
    {
        // scopes define the API resources in your system
        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource("all", "All APIs")
            };
        }

        // client want to access resources (aka scopes)
        public static IEnumerable<Client> GetClients()
        {
            return new List<Client>
            {
                new Client
                {
                    ClientId = "another",
                    AllowedGrantTypes = GrantTypes.ClientCredentials,

                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowedScopes = { "all" }
                },
                new Client
                {
                    ClientName = "idserver",
                    ClientId = "idserver",
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
                    Enabled = true,

                    AllowedScopes = { "all" },

                    ClientSecrets =
                    {
                        new Secret("idserversecret".Sha256())
                    },

                    AccessTokenType = AccessTokenType.Jwt
                }
            };
        }
    }
}

```

Here is my client config:

```
namespace Custom.TestClient
{
    using System;
    using IdentityModel.Client;

    public class Program
    {
        public static void Main(string[] args)
        {
            var tokenClient = new TokenClient(
                "http://localhost:5000/connect/token", 
                "idserver", 
                "idserversecret",
                AuthenticationStyle.BasicAuthentication);

            var tokenResponse = tokenClient.RequestResourceOwnerPasswordAsync("who", "cares", "all").Result;

            Console.WriteLine($"Code: {tokenResponse.HttpStatusCode}");
            Console.WriteLine($"Error: {tokenResponse.Error}");
            Console.WriteLine($"Desc: {tokenResponse.ErrorDescription}");

            Console.ReadKey();
        }
    }
}
```

### Relevant parts of the log file

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/connect/token application/x-www-form-urlencoded 57
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /connect/token matched to endpoint type Token
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Mapping found for endpoint: Token, creating handler: IdentityServer4.Endpoints.TokenEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
dbug: IdentityServer4.Endpoints.TokenEndpoint[0]
      Start token request.
dbug: IdentityServer4.Validation.ClientSecretValidator[0]
      Start client validation
dbug: IdentityServer4.Validation.BasicAuthenticationSecretParser[0]
      Start parsing Basic Authentication secret
dbug: IdentityServer4.Validation.SecretParser[0]
      Parser found secret: BasicAuthenticationSecretParser
dbug: IdentityServer4.Validation.SecretParser[0]
      Secret id found: idserver
fail: IdentityServer4.Validation.ClientSecretValidator[0]
      No client with id 'idserver' found. aborting
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 529.4233ms 400 application/json
```

**Comment by leastprivilege** [comment]
We have more people that have problems with StructureMap - we use the built-in DI API . Maybe @jeremydmiller can have a look.

**Comment by no1melman** [comment]
Why would it be a problem with structure map? it appears to be calling the correct validators doesnt it?

**Comment by no1melman** [comment]
I'll pull the repo down tomoz and create a structuremap test proj

**Comment by leastprivilege** [comment]
Because for some reason the client cannot be found (which comes from DI)

**Comment by jeremydmiller** [comment]
@leastprivilege Going to say that I very seriously doubt that this is a "StructureMap problem," but very possibly part of whatever ASP.Net Core DI abstraction assumptions you're counting on. Are you guys depending on the lifecycle per request behavior in your middleware, or do you do that yourself? Could it be a scoping problem that you're expecting something to have the HttpContext information when that does not yet exist?

@no1melman Before you do too much, use SM's `WhatDoIHave()` to see if the services you expect to be in there are really there. Beyond that, maybe do a DescribePlan() on whatever the validator is that doesn't have any information? See if you can spot whatever dependency connects to identity server that might be in the wrong place?

**Comment by no1melman** [comment]
@jeremydmiller I would do, but if you look in Id servers extensions for the service collection there are a tonne of services it registers, I just thought it would be easier to follow the path through... I don't reckon that doing spot checks would be suitable. I do agree that it would be strange if it were a Structuremap issue - mainly because it seems to be getting to the the right places?!

**Comment by no1melman** [comment]
Okay, so I've created a server and client. Using internal DI it works, adding StructureMap it fails. So clearly things aren't being wired up properly

**Comment by no1melman** [comment]
For the client:

```
PluginType     Namespace                    Lifecycle                     Description
==================================================================
IClientStore    IdentityServer4.Stores    UniquePerRequest     IdentityServer4.Stores.InMemoryClientStore 
```

**Comment by leastprivilege** [comment]
That's the relevant code if that help

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/InMemory.cs#L66

**Comment by no1melman** [comment]
Yeah I've been scouring that code... I can't see anything out of the ordinary apart from `AddSingleton(clients)` where `clients` is an `IEnumerable<Client>` I'm not sure how structuremap handles that

**Comment by no1melman** [comment]
It isn't the clients - I think it's the validators...

**Comment by no1melman** [comment]
Yeah, confirmed. Structuremap isn't handling the `IEnumerable<Client>` or other type registrations. I created my own in memory client store and the it worked fine (bar the scopes, but that is the same problem).

**Comment by jeremydmiller** [comment]
@leastprivilege What lifecycle **should** those services be? If they're meant to be stateful between requests or even by requesting them multiple times in the same http request, "UniquePerRequest" is absolutely useless. Have you guys bothered to test any of your stuff with anything besides the built in container?

@no1melman SM's behavior for how it handles enumerable types are documented here: http://structuremap.github.io/the-container/working-with-enumerable-types/. It's perfectly possible that IdentityServer is depending on some kind of undocumented assumption about the built in IoC container, but right now, the StructureMap aspnetcore adapter passes all of their compliance tests.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/InMemory.cs#L66

@jeremydmiller for the in-mem (test) one we are adding the clients as a singleton.

We never tested against any other DI container.

**Comment by brockallen** [comment]
> Specifically, if you request one of these types either directly with GetInstance<IList<IWidget>>() or as a declared dependency in a constructor or setter (new WidgetUser(IList<IWidgets> widgets) for example) and you have no specific registration for the enumerable types, StructureMap has a built in policy to return all the registered instances of IWidget in the exact order that the registrations were made to StructureMap

As I read this, I see *you have no specific registration for the enumerable types* -- but we do have a specific registration of `IEnumberable<Client>`. So am I misreading or misinterpreting those docs?

**Comment by jeremydmiller** [comment]
@no1melman Can you just list out the entire WhatDoIHave() output? @brockallen & @leastprivilege Are you expecting this code:

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/InMemory.cs#L68

To add the client collection as an aggregate as a singleton? 

@leastprivilege What you're doing isn't idiomatic StructureMap (we'd generally just add each one independently and let the default behavior just work), but it should still work without any trouble. Again, get the SM WhatDoIHave diagnostics here and I might be able to tell you more.

Hate to tell you guys, but by no means would I assume that your code will magically work against any other IoC tool until you test it. There's an insane amount of assumptions in the ASP.Net Core IoC abstractions that does not really match any container except for the built in one.

**Comment by brockallen** [comment]
It sounds like if this isn't something designed into the ASP.NET Core DI spec (I'm assuming something like this exists), then the semantics should prohibit it I'd think. If it's allowed by the default, then that behavior should be defined by the spec.

**Comment by leastprivilege** [comment]
IOW - if it helps we have no issue adding a wrapper class e.g. `Clients` which holds the IEnumerable.

I guess we just want to understand the real issue.

**Comment by no1melman** [comment]
I'm finding that I can't just use `cfg.Scan` in StructureMap because the core service registration that IdentityServer does creates a bunch of defaults that remain the defaults even after the scan does its thing.

This means for something like `IResourceOwnerPasswordValidator` I have to make sure I call `Populate(services)` before I do `cfg.For<IResourceOwnerPasswordValidator>().Use<ResourceOwnerPasswordValidator>()` so that I make my implementation the default.

This behaviour basically makes using StructureMap redundant as I now have to specify all my IdentityServer configurations up front.

**Comment by jeremydmiller** [comment]
@leastprivilege I'm not ruling out that it's a StructureMap issue (but I think it's more likely in the ASP.Net Core adapter code for SM), but I haven't heard anything conclusive either way.

**Comment by jeremydmiller** [comment]
@no1melman There's a StructureMap bug fix release up (4.4.5) today that had a change to the way SM handles enumerables that might help you out with the clients registration.

**Comment by no1melman** [comment]
Oh sweet, thanks @jeremydmiller

**Comment by brockallen** [comment]
Once your issue is resolved let us know so we can close the issue. Thanks.

**Comment by no1melman** [comment]
I resolved the issue by implementing my own in memory classes. I'm not going to take the approach of registering an `IEnumerable<T>` because that isn't fit for purpose.

**Comment by leastprivilege** [comment]
You know what the right thing to do would be, don't you?

Propose a solution, start a PR - give back. just sayin'.

**Comment by no1melman** [comment]
I don't think there is anything wrong with your current implementation. I assume the `InMemory...` stuff is just for testing with - in the real world implementations you would just implement everything yourself. So I was just saying that because I'm using this for a production site `InMemory...` isn't fit for purpose - which is fine.
