### ISSUE TITLE
Deal with Azure AD federation gateway problem

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1066]
https://github.com/mclark1129/IdentityServer4.Samples/tree/master/AzureAd_CustomStateDataFormat

**Comment by brockallen** [comment]
Done, but needs review/cleanup.

**Comment by phrazed** [comment]
Any idea how to use these extension methods in Core 2? app.UseOpenIdConnectAuthentication is depreciated...
