### ISSUE TITLE
"Token request validation success" event logs client secret

### ISSUE THREAD

**Issue by akshetty9** [IdentityServer/IdentityServer4#1068]
Token request validation should redact the client secret in Raw

> details
> {
>   "ClientId": "bb95775d69234",
>   "ClientName": "client003",
>   "GrantType": "client_credentials",
>   "Scopes": "Api1",
>   "Raw": {
>     "client_id": "bb95775d69",
>     "client_secret": "m[J*$&69Pyorj&PX^FyT7#]Iw~qsUCAkTMevkCINq$hh9",
>     "grant_type": "client_credentials",
>     "scope": "Api1"
>   }
> }

Adding it to the SensitiveFilterList [here](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Logging/Models/TokenRequestValidationLog.cs#L30) should do it. I can send a PR if it is correct thing to do

**Comment by leastprivilege** [comment]
good catch - PR please. thanks

**Comment by leastprivilege** [comment]
merged
