### ISSUE TITLE
Revocation Endpoint Status?

### ISSUE THREAD

**Issue by jkavanaghrdm** [IdentityServer/IdentityServer4#107]
The Revocation endpoint (connect/revocation) is 404 Not found. I don't see it in the Source. Is it coming in a future update? Or has it been replaced?

**Comment by leastprivilege** [comment]
it is coming in a future version

**Comment by jkavanaghrdm** [comment]
Hi Dominick. Do you have an expected timeline for this update?

**Comment by leastprivilege** [comment]
no. Probably not for 1.0 - but we'll try.

**Comment by jkavanaghrdm** [comment]
Thanks for trying; it's very much appreciated. Now that this Issue is closed, Is there another Issue # I can use to track the status of the Revocation endpoint implementation? Also, what's the expected timeline for 1.0?

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/111
