### ISSUE TITLE
HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).

### ISSUE THREAD

**Issue by ShashikantMaurya** [IdentityServer/IdentityServer4#1071]
Hi,

I have configured client using Identity Server 4 like below

new ClientModel
                {
                    ClientId = "client",
                    ClientName = "client",
                     AllowedGrantTypes = GrantTypes.List(
                                                        GrantType.Hybrid,
                                                        GrantType.ClientCredentials
                                                       ),
                    ClientSecrets =
                    {
                        new Secret("Secret".Sha256())
                    },
                    AllowAccessTokensViaBrowser = true,
                    RedirectUris = { "http://localhost:20303/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:20303/" },
                    AllowedCorsOrigins = { "http://localhost:20303/" },
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1"
                    },
                    AllowOfflineAccess = true,                   
                },         

and I have created API using .net framework 4.5 and configured like below 

 app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44358",
                RequiredScopes = new[] { "api1" },
                DelayLoadMetadata = true
            });
and when i try to call api with client application  i am getting  error 500
public async Task<IActionResult> CallApiUsingClientCredentials()
        {
            var tokenClient = new TokenClient("https://localhost:44358/", "client", "Secret");
            var tokenResponse = await tokenClient.RequestClientCredentialsAsync("api1");                     
            var client = new HttpClient();
            client.SetBearerToken(tokenResponse.AccessToken);
            var content = await client.GetStringAsync("http://localhost:8182/api/Questions");

            ViewBag.Json = JArray.Parse(content).ToString();
            return View("json");
        }

        public async Task<IActionResult> CallApiUsingUserAccessToken()
        {
            var accessToken = await HttpContext.Authentication.GetTokenAsync("access_token");
            var client = new HttpClient();
            client.SetBearerToken(accessToken);
            var content = await client.GetStringAsync("http://localhost:8182/api/Questions");

            ViewBag.Json = JArray.Parse(content).ToString();
            return View("json");
        }

Please help me

**Comment by leastprivilege** [comment]
check the logs.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
