### ISSUE TITLE
Expose IdentityServer actions from my own custom controller

### ISSUE THREAD

**Issue by xplatsolutions** [IdentityServer/IdentityServer4#1074]
Can I expose IdentityServer4 actions via my own controller; - any samples?

I want to use my Auth service layer as REST service and not the IdentityModel nuget package. Another reason if I want special business logic when creating tokens for the clients.

**Comment by brockallen** [comment]
> Can I expose IdentityServer4 actions via my own controller; - any samples?

Can you be more specific? We provide many extensibility points for our endpoints.

> I want to use my Auth service layer as REST service and not the IdentityModel nuget package.

This does not compute.

**Comment by xplatsolutions** [comment]
Having the below configuration in ASP.NET Core Web API.

```
// Startup.cs
// in ConfigureServices method - identity server with in-memory stores, keys, clients and scopes
            var idsrvBuilder = services.AddIdentityServer()
                .AddTemporarySigningCredential()          
         .AddInMemoryApiResources(Config.GetApiResources(Configuration["AppSettings:ApiName"]))
                .AddInMemoryClients(Config.GetClients(Configuration["AppSettings:ClientId"], Configuration["AppSettings:ApiName"]));

idsrvBuilder.AddResourceOwnerValidator<ResourceOwnerPasswordValidator>();
idsrvBuilder.AddProfileService<ProfileService>();

// in Configure method
app.UseIdentityServer();
```
At this point I can just start my web service and it will listen for requests. And I have no `Controller`, it all works out of the box in the IdentityServer (or I can't find the right documentation page).
Then in a client I can do something like the below to request a token.
```
private async static Task RequestAccessTokenWithCredentials()
        {
            var disco = await DiscoveryClient.GetAsync("http://localhost:5000");

            string clientId = "client";
            string secret = "secret";
            string apiName = "api";
            string username = "viko";
            string password = "test";

            // request token
            var tokenClient = new TokenClient(disco.TokenEndpoint, clientId, secret);
            var tokenResponse = await tokenClient.RequestResourceOwnerPasswordAsync(username, password, apiName);

            if (tokenResponse.IsError)
            {
                Console.WriteLine(tokenResponse.Error);
                return;
            }

            Console.WriteLine(tokenResponse.Json);
            Console.WriteLine("\n\n");
        }
```

`DiscoveryClient` is part of the IdentityModel nuget package, but I want to create my own API `Controller` and invoke a GET operation to retrieve the token. So if I had a controller named "AuthController" with an action GET and route "tokenwithcredentials" I can point the clients to http://domain/auth/tokenwithcredentials pasing the parameters needed and retrieve the token.

What I'm looking for is where to start to expose a custom API endpoint instead of using `DiscoveryClient`. Is it possible?

**Comment by leastprivilege** [comment]
Have a look at `IdentityServerTools` - this has an easy token creation API.
