### ISSUE TITLE
server to server communication 

### ISSUE THREAD

**Issue by fdewannemaeker** [IdentityServer/IdentityServer4#1077]
Say i have the following:
A js spa client that is authenticated using idsrv4 using Implicit Flow.
Api1 and api2 are protected by the same idsrv4. 
The js spa client has access only to api1 (Implicit Flow). Api1 has access to api2 (Authorization Code Flow).  
Js Spa client and api1 are not mine (not trusted), idsrv4 and api2 are mine.
Question: how do I know which user is logged in in api2? As the call is made by api1 using client credentials, is it possible?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
