### ISSUE TITLE
How to handle 3rd party (non-ui) authentication

### ISSUE THREAD

**Issue by XplMarcel** [IdentityServer/IdentityServer4#1078]
I have the following situation:
1.  An Authentication server (identityserver 4)
2.  An API application.
3.  3rd parties (non-ui) using the API application.

3rd parties can register an account after which they retrieve a generated client_id and client_secret so they can authenticate from their API application (machine to machine) to be able to use our API application.
The problem is that i want to add the tenantId's of tenants they can use (which can be maintained by the 3rd party) to the generated access_token, so the 3rd party knows which tenants can be used and on our API side if the 3rd party is authorized to use a certain tenant. I can't add claims, since an access_token generated with this flow doesn't represent a User.

So how do i handle authentication like that ?
Is the client_credentials flow the right one ?

**Comment by leastprivilege** [comment]
Client can have claims as well. Check `Client`.

**Comment by XplMarcel** [comment]
Solved.. thanks
