### ISSUE TITLE
Where/how to store refresh token?

### ISSUE THREAD

**Issue by moritzgloeckl** [IdentityServer/IdentityServer4#1082]
Hi,

we were wondering what's the best practice to store refresh_tokens? Our main application is using Google Login/Authentication. Now we want to add IDS4 to allow others to use our API - we act as a provider just like Google. But because of that we need to authenticate our users with Google. Would you do this just the first time and forget about it or authenticate them with every request of the client application? And what happens when the client application wants to refresh their token, we need to refresh the Google token right? 

It looks like this:

Client -Authenticate-> IdentityServer -Authenticate-> Google

So we do not have a user database, but just use Google as an authentication method. 

Thanks a lot.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
