### ISSUE TITLE
Question: What does client.AllowAccessTokensViaBrowser exactly do?

### ISSUE THREAD

**Issue by deastr** [IdentityServer/IdentityServer4#1083]
I've red the documentation and I also checked the source code but I couldn't figure out what it exactly is for. In samples it's used in conjunction with Implicit flow but setting it true or false in my Hybrid client didn't seem to change anything?

**Comment by leastprivilege** [comment]
it is prohibiting that an access token is delivered via the browser channel - unless explicitly allowed.

**Comment by deastr** [comment]
Yes I've seen the check in AuthorizeRequestValidator but what exactly is the "browser channel"? How is it determined that the current token request is made by a browser/javascript client so IdSrv can decide if it should send a token or not?

**Comment by leastprivilege** [comment]
IOW - via the authorize endpoint
