### ISSUE TITLE
How to restrict users to get an access_token depending on scope

### ISSUE THREAD

**Issue by XplMarcel** [IdentityServer/IdentityServer4#1088]
I have an IS4 server which is being used for multiple API's (using ApiResource).
Lets say "Api1" and "Api2" and users "User1", "User2" and "User3".
I want "User1" to be able to only retrieve an access_token for "Api1", "User2" only for "Api2" and "User3" for "Api1" and "Api2".

I already tried to implement this using soo many code samples as a reference, but i can't seem to figure out how i would model my ApiResources, Clients and Users to accomplish this.

Any suggestions and or documentation/code sample references i could be pointed too ?

**Comment by brockallen** [comment]
That's not typically done in IdentityServer. Scope validation is about clients, not users. Do your user authorization in the resource server.
