### ISSUE TITLE
Implicit Flow + Apache Cordova

### ISSUE THREAD

**Issue by darkcircuituk** [IdentityServer/IdentityServer4#1089]
Working on a sample of getting IS4 working with Angular2 on the Apache Cordova platform, and although I have successfully got the redirect to IS4 working fine, I am unable to get the post-login redirect back to Cordova working.

From my limited knowledge on the subject it appears that Cordova is taking exception to the way IS4 performs it's redirect back to the app as it throws a 'Not allowed to load local resource: file:///android_asset/www/index.html#id_token=blah' error when using the redirect_uri 'file:///android_asset/www/index.html' (the result of window.location.href prior to initial redirect).

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. But here's a place to get started with Cordova: https://github.com/IdentityModel/oidc-client-js/issues/34#issuecomment-227098369

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by GFoley83** [comment]
@darkcircuituk Did you find a solution for this? Currently have the same problem for an Ionic project.
