### ISSUE TITLE
Reacting to Identity 2.0 changes

### ISSUE THREAD

**Issue by harisbotic** [IdentityServer/IdentityServer4#1090]
Are you planning to react to the changes happened in Identity 2.0 any soon?
https://github.com/aspnet/Identity/commit/14b4bea964875b605cef5a0fef7ed21ceb51aa6f

**Comment by brockallen** [comment]
Our 2.0 will be after their 2.0 and we'll most likely change to the new authN system.

**Comment by harisbotic** [comment]
For some reasons, sadly I am forced to use latest 2.0 version but when I switch I have following error

<img width="592" alt="screen shot 2017-04-21 at 23 48 44" src="https://cloud.githubusercontent.com/assets/6454831/25297342/6ca51554-26ed-11e7-99c9-ab06145a79b0.png">



Can I do any workaround to make this work for now?

**Comment by harisbotic** [comment]
@leastprivilege @brockallen

**Comment by brockallen** [comment]
> For some reasons, sadly I am forced to use latest 2.0 version but when I switch I have following error

Sorry. I can't imagine they're compatible.
