### ISSUE TITLE
Question: How could I map sessions to access tokens?

### ISSUE THREAD

**Issue by infinnie** [IdentityServer/IdentityServer4#1091]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)
> Ah help me 
>
> Assume that I have a system S with some users, and users are authenticated on the S system using their S accounts. Now I have another system T that uses IdentityServer4 which does not own or know about the S users’ accounts. However, if the system S needs T to generate a unique access token for each user and each of his/her sessions, what should I do?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by infinnie** [comment]
I was so sorry about that.
