### ISSUE TITLE
Getting addtional Information from IdentityServer4 using asp.net core

### ISSUE THREAD

**Issue by anitchanana** [IdentityServer/IdentityServer4#1093]
I have created an IdentityServer4 website which has number of clients, one of them is JS client.
I am using JS client to get access_token. The detail returned is in snapshot.
What i want to add couple more column to that like
PersonId : 11,
Address : ABC 
along with Access_token,id_token etc.

How can i get that from IdentityServer4 ?
![info](https://cloud.githubusercontent.com/assets/6780356/25274565/36f2a078-26ae-11e7-8aff-18737c16ed79.png)

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
