### ISSUE TITLE
Problem logging out from two identityservers 4 

### ISSUE THREAD

**Issue by lghinet** [IdentityServer/IdentityServer4#1094]
hello, 
i have two linked identityserver4, using .net core, 
first : https://localhost:44398/ lets call this one idsrv1
second : https://localhost:44362/ lets call this one idsrv2

idsrv1 has idsrv2 as an external provider
idsrv1 has this configuration on StartUp

`services.AddIdentityServer(options =>
                {
                    options.Authentication.FederatedSignOutPaths.Add("/signout-callback-aad");
                    options.Authentication.FederatedSignOutPaths.Add("/signout-callback-idsrv");
                    options.Authentication.FederatedSignOutPaths.Add("/signout-callback-adfs");
                })`

...

` var cookies = app.ApplicationServices.GetRequiredService<IOptions<IdentityOptions>>().Value.Cookies;

            app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "CharismaCoreIdentity",
                SignInScheme = cookies.ExternalCookieAuthenticationScheme,//IdentityServerConstants.ExternalCookieAuthenticationScheme,
                SignOutScheme = cookies.ApplicationCookieAuthenticationScheme,//IdentityServerConstants.SignoutScheme,
                AutomaticChallenge = false,
                DisplayName = "CharismaCore Identity",
                Authority = "https://localhost:44362/",
                ClientId = "charismaidsrv",
                ClientSecret = "charismaidsrvSecret",
                ResponseType = OpenIdConnectResponseType.IdToken,
                Scope = {"openid email"},
                SaveTokens = true,
                GetClaimsFromUserInfoEndpoint = false,
                CallbackPath = new PathString("/signin-idsrv"),
                SignedOutCallbackPath = new PathString("/signout-callback-idsrv"),
                RemoteSignOutPath = new PathString("/signout-idsrv"),
                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    RoleClaimType = "role"
                },
                Events = new OpenIdConnectEvents
                {
                    OnTokenValidated = n =>
                    {
                        ((ClaimsIdentity)n.HttpContext.User.Identity).AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));

                        //id.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
                        //n.AuthenticationTicket = new AuthenticationTicket(id,n.AuthenticationTicket.Properties);
                        return Task.FromResult(0);
                    },
                    OnRedirectToIdentityProviderForSignOut = context =>
                    {
                        var idTokenHint = context.HttpContext.User.FindFirst("id_token");
                        //if (idTokenHint != null)
                          //  n.ProtocolMessage.IdTokenHint = idTokenHint.Value;

                        return Task.FromResult(0);
                    }
                }
            });`

I configured the idsrv1 as a client for  idsrv2 as follows : 
`LogoutSessionRequired = true`
`LogoutUri = https://localhost:44398/signout-callback-idsrv`
`PostLogoutRedirectUri = https://localhost:44398/signout-callback-idsrv`

**Problem1** 
If I logout from idsrv2, it opens an iframe and calls idsrv1/signout-callback-idsrv but in FederatedSignOutMiddleware class 
`var upstreamSid = user.FindFirst(OidcConstants.EndSessionRequest.Sid)?.Value;`
but upstreamSid is null  - "no sid param passed"

I tried with 
`LogoutUri = https://localhost:44398/signout-idsrv`
this works ok, but i want a federate logout, so that all clients of idsrv1 get logout

**Problem2** 
If i logout from idsrv1, its redirected to idsrv2 ,then logout, ok so far,  LogoutUri is called but PostLogoutRedirectUri is never called, 
I know this is related to IdTokenHint, which i did try to set as you see in my code above, but no luck.

**Problem3** 
this is related to an angular client, using oidc-client
After i logout from an angular client and the user belongs to idsrv2, i am redirected to idsrv1 and then to idsrv2 and then logged out, but there is no LINK to come back to my angular site.

thanks you,
help is very much appreciated

**Comment by brockallen** [comment]
> Problem1

Did idsrv2 issue a sid at login time? You need to capture it and issue it as a claim in the auth session cookie.

> Problem2

Check the logs -- it should point you at why it's not honoring the post logout redirect uri.

> Problem3

Same as Problem2, I think. And if it did work the workflow would be idsrv2 links you back to idsrv1, which then links you back to your JS app.

**Comment by lghinet** [comment]
> Problem1
Did idsrv2 issue a sid at login time? You need to capture it and issue it as a claim in the auth session cookie.

both idsrv have a session cookie, how can i add it as a claim ?

**Comment by lghinet** [comment]
> Problem2
Check the logs -- it should point you at why it's not honoring the post logout redirect uri.

the idtokenhint is not present
i couldnt attach it through OpenIdConnectEvents

**Comment by lghinet** [comment]
solve the problems by adding 
`  var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToAction(nameof(Login));
            }

            var additionalClaims = new List<Claim>();
            // if the external system sent a session id claim, copy it over
            var sid = info.Principal.FindFirst(JwtClaimTypes.SessionId);
            if (sid != null)
            {
                additionalClaims.Add(new Claim(JwtClaimTypes.SessionId, sid.Value));
            }

            // if the external provider issued an id_token, we'll keep it for signout
            var id_token = info.AuthenticationTokens.FirstOrDefault(x => x.Name == "id_token")?.Value;
            
            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, false, additionalClaims.ToArray(), id_token);`

in the ExternalLoginCallback;
kind of tricky when using AspNetIdentity in idsrv1, i had to rewrite some mothods in the SingInManager.
I suppose this will have worked out of the box if using the default user implementation
thanks
