### ISSUE TITLE
AuthorizeResponse

### ISSUE THREAD

**Issue by 546456** [IdentityServer/IdentityServer4#1097]
Null idToken when using AuthorizeResponse after the user is authenticated.

Replace the Secure() action in MVCManual sample with the following code.  After you are authenticated response.AccessToken is null.

       `public async Task<IActionResult> Secure()
        {
            if (User.Identity.IsAuthenticated)
            {
                var disco = await DiscoveryClient.GetAsync(Constants.Authority);

                var authorizeUrl = new AuthorizeRequest(disco.AuthorizeEndpoint).CreateAuthorizeUrl(
                    clientId: "mvc.manual",
                    responseType: "id_token",
                    scope: "openid",
                    redirectUri: "http://localhost:44077/home/callback",
                    state: "random_state",
                    nonce: "random_nonce",
                    responseMode: "form_post");

                var response = new AuthorizeResponse(authorizeUrl);

                var accessToken = response.AccessToken;
                var idToken = response.IdentityToken;
                var state = response.State;

                return View();
            }

            return await StartAuthentication();
        }`

**Comment by leastprivilege** [comment]
Because that's not how it works. You need to do a redirect to the token service.

https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/MvcManual/Controllers/HomeController.cs#L57

**Comment by 546456** [comment]
Thanks for the response.  I was going off the documentation at the bottom of the page here: http://docs.identityserver.io/en/release/endpoints/authorize.html?highlight=authorize%20endpoint.

I should never be using AuthorizeReponse?  I'm trying to see if a user is already authenticated without doing the redirect.

**Comment by leastprivilege** [comment]
All the request class is doing is to create a URL string.

**Comment by 546456** [comment]
My question is over Authorize**Response** not AuthorizeRequest.

**Comment by leastprivilege** [comment]
AuthorizeResponse is a class that parses a response from an authorization server.

**Comment by leastprivilege** [comment]
I see - well - the URL in the 2nd sample is not the one created - it is the callback URL from the server. You need to do a round-trip in between.

The MVC Manual sample has the right usage.

**Comment by 546456** [comment]
Thanks
