### ISSUE TITLE
Question over API

### ISSUE THREAD

**Issue by henriqueleandro** [IdentityServer/IdentityServer4#1098]
Good afternoon to all a quick question,
How could I use the IDV4 with angular,?
Could you simply use the controller account business rules in an api?
Or would you have any security patches that would prevent webApi from being used?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
