### ISSUE TITLE
Duplicate scopes in QS UI?

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1099]
https://stackoverflow.com/questions/43419140/why-am-i-seeing-duplicate-scopes-on-identityserver4s-consent-screen/43520548?noredirect=1#comment74105237_43520548

**Comment by asfyra** [comment]
If you are using InMemoryResourcesStore then this [fix](https://github.com/IdentityServer/IdentityServer4/pull/1217/commits/16d11bdfc5cc2d81d454f637a2deee6b30298870) might solve your issue

**Comment by brockallen** [comment]
Fixed. Thanks.
