### ISSUE TITLE
Custom Policy with Claims

### ISSUE THREAD

**Issue by joaomello** [IdentityServer/IdentityServer4#110]
Hi, there is a way to use custom policy with identityserver4 on a client using openidconnect middleware?

I found it to identityserver3, I don't know if it is the same...
https://leastprivilege.com/2014/06/24/resourceaction-based-authorization-for-owin-and-mvc-and-web-api/

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
