### ISSUE TITLE
Login a native mobile app with IdentityServer4

### ISSUE THREAD

**Issue by OscarCanek** [IdentityServer/IdentityServer4#1102]
1. Is there a library to login a native mobile app (ios swift) similar to IdentityModel in .Net?
2. What the process to authenticate a native mobile app (ios swift) using an existing IdentityServer4?

**Comment by leastprivilege** [comment]
That's the recommended one

https://github.com/openid/AppAuth-iOS/blob/master/Examples/README-IdentityServer.md
