### ISSUE TITLE
Question: Getting Authenticated User's Roles/Groups from Windows AD

### ISSUE THREAD

**Issue by kenneth-y** [IdentityServer/IdentityServer4#1103]
Hi,

I'm using IdentityServer4 in my application using Windows Integrated authentication (Active Directory). 

Quite new to using IdentityServer4. :) Does IdentityServer4 by default returns the authenticated user's AD Groups? Or, do I need to explicitly request that info?

Appreciate your inputs. 

Thanks!

**Comment by leastprivilege** [comment]
You would need to capture the Windows groups at login time - like here

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/release/Quickstart/Account/AccountController.cs#L138

This would make them available to your profile service - which in turn can then put them into a token.

**Comment by kenneth-y** [comment]
thanks for the response @leastprivilege. i do see the claims being added from the LoginController when I placed a breakpoint on code block below.

![image](https://cloud.githubusercontent.com/assets/20555356/25465451/ea2177d4-2b34-11e7-8040-dbdbc733294c.png)

Tried enumerating the claims of the authenticated user from my MVC Web App (client) but i could see the roles. So I guess i need to extend the IProfileService interface, is that right? Inspected the claims inside GetProfileDataAsync() method i only see 5 claims.

![image](https://cloud.githubusercontent.com/assets/20555356/25467476/0021c24e-2b41-11e7-8e4a-ac57cacbb3c5.png)

Thanks in advance for your inputs :)

**Comment by kenneth-y** [comment]
@leastprivilege i managed to retrieve the claims in my custom IProfileService. I added the role claims inside ExternalLoginCallback() action of the AccountController.

![image](https://cloud.githubusercontent.com/assets/20555356/25516827/32109fd0-2c1f-11e7-8f49-53ab749e5b24.png)

pls let me know your thoughts if its the correct way.

**Comment by leastprivilege** [comment]
looks good.
