### ISSUE TITLE
[Question] Host protected UI from/within Identity Server itself

### ISSUE THREAD

**Issue by raffaeu** [IdentityServer/IdentityServer4#1104]
We have implemented the following architecture at the moment:
 - Identity Server 4 on Azure with SQL Azure
 - Web Client on ASP.NET Core
 - API on ASP.NET Core
 - Client on Windows Client
 - Zapier (integration service)

For *Web Client* we use the **HybridAndClientCredentials** 
For *Windows Client* we use the **ClientCredentials**
For *Zapier* we use the **ClientCredentials** + authroization endpoint

Now, we came up with the requirement of implementing some UI for Identity Server which we want to add to the Identity Server project.
So, first thing I configured identity server to also have an authentication cookie as following:

```csharp
/* this cookie is used to authenticate into Identity Server itself */
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
     AuthenticationScheme = IdentityServerConstants.LocalIdentityProvider,
     AutomaticChallenge = true,
     LoginPath = "/Account/Login"
});
```

So if the User point directly to **Identity Server URL** it will be redirect into Identity Server Home after login. So far so good.
The problems I am facing are about the **Identity Server Client**. With **Web Client** we have a dedicated client which inform us about *Redirect*, *Client Claims*, *Scopes*, *OfflineAccess* and more while with this scenario of authenticating into Identity Server itself, we don't have a Client so after authentication I have these problems:

```csharp
/* it always returns NO */
interactionService.IsValidReturnUrl(model.ReturnUrl)
```

```csharp
/* context is always null because in this case 
Identity Server doesn't have a Client for "itself" */
var context = await _interaction.GetAuthorizationContextAsync(returnUrl);
```

My question is, what am I supposed to do? Should I create and configure a Client for Identity Server **also**, should I have another website which is the **UI for Identity Server** or is there any example that I should follow?

**Comment by leastprivilege** [comment]
This would be similar to 

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/release/Quickstart/Grants/GrantsController.cs#L19

and 

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/release/Quickstart/Account/AccountController.cs#L98

**Comment by raffaeu** [comment]
@leastprivilege I was actually reading that code
So I'll move forward from there.

I miss this piece which was causing the problem to me:
```
(_interaction.IsValidReturnUrl(model.ReturnUrl) || Url.IsLocalUrl(model.ReturnUrl))
```
