### ISSUE TITLE
Question: Adding custom values on client to be added to access token

### ISSUE THREAD

**Issue by deastr** [IdentityServer/IdentityServer4#1105]
Is it possible to add custom dynamic values (key+value pair) to authorization request to IdSrv so it can add it to the access token as claim? Like AcrValues or client claims but value is dynamic per user.

**Comment by leastprivilege** [comment]
You think that is a good idea - so anybody could change those values on the URL and we would blindly sign it?

**Comment by deastr** [comment]
I totally agree with you. The only reason I'm looking for this is backwards compatibility. Our current in-house clients use access token to send additional values within calls to an internal api. I'm not optimistic about such a feature and honestly don't want to but what can you do. I feel like it can be only done doing custom `IExtensionGrantValidator `implementation am I correct?

**Comment by leastprivilege** [comment]
I am confused now - do you want to send custom parameters to the token endpoint of authorize endpoint??

**Comment by deastr** [comment]
I want the client to be able to send additonal values/parameters to the IdP during authorization so IdP can add them as claims to the access token.

**Comment by leastprivilege** [comment]
to which endpoint?

**Comment by deastr** [comment]
Well I was hoping if it could be done during passive authentication process using OIDC but I guess maybe I have to settle with manuel call for the token endpoint?

**Comment by leastprivilege** [comment]
You can send additional parameters to the authorize endpoint. They are available via the interaction service from the login page e.g. From there you can put them into the signin cookie which is available in the profile service.

..but - you've been warned ;)
