### ISSUE TITLE
InvalidSignInRedirectUrl in Idsrv4 to prevent back button issues after sign in

### ISSUE THREAD

**Issue by SebJones** [IdentityServer/IdentityServer4#1106]
Hi,

I'm currently having issues when users are pressing the back button after sign in, such that even though they are authenticated they are placed back on the log in screen, and obviously with no sign-in cookie present in order to re-authenticate and redirect back to the app landing page.

I know this was solved using an InvalidSignInRedirectUrl property in the AuthenticationOptions object in Idsrv3 to redirect users to the specified url when arriving at the login page with no sign in message - is there an equivalent available for this or a reason why this can't also be implemented in Idsrv4?

Cheers,
Seb

**Comment by leastprivilege** [comment]
Signin cookies do not exist anymore in 4.

**Comment by SebJones** [comment]
Ah OK my bad. The issue remains though - pressing the back button returns to the login screen even if the user is authenticated when a redirect would be preferable, is this possible?

**Comment by leastprivilege** [comment]
You can check on the login page if the user is already authenticated and do the redirect yourself.
