### ISSUE TITLE
Error 'X-Frame-Options' to 'sameorigin' when using federate signout

### ISSUE THREAD

**Issue by lghinet** [IdentityServer/IdentityServer4#1107]
Hello, 
i am using two identityservers: idsrv1 and idsrv2 as an external provider for idsrv1;
i get in the following error when i try to signout, from idsrv2 as shown below

![image](https://cloud.githubusercontent.com/assets/12889810/25446059/f1478570-2ab8-11e7-8766-3345f007e885.png)

the error comes from here 
`var logoutPageUrl = _options.UserInteraction.LogoutUrl;
                if (logoutPageUrl.IsLocalUrl())
                {
                    context.Response.Headers.Add("X-Frame-Options", "SAMEORIGIN");
                }
                else
                {
                    context.Response.Headers.Add("X-Frame-Options", $"ALLOW-FROM {logoutPageUrl.GetOrigin()}");
                }`

_options.UserInteraction.LogoutUrl = "account/logout" which is ok in the case where i logout from idsrv1, but if i logout from idsrv2, and federate logout kicks in, _options.UserInteraction.LogoutUrl should be external 

if I logout from idsrv1, works ok
i think its related to  this issue  https://github.com/IdentityServer/IdentityServer3/issues/2654

any ideas 
thanks

**Comment by brockallen** [comment]
I think this a non-issue now given this change: https://github.com/IdentityServer/IdentityServer4/issues/1224. I'll close, and if it's still an issue after 2.0 is released, feel free to reopen.
