### ISSUE TITLE
Implement token revocation endpoint

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#111]

**Comment by leastprivilege** [comment]
dup

**Comment by vanthome** [comment]
Both issues regarding this are closed, does it mean it's done?
For me the revocation endpoint does respond properly but the token is still usable, so it's not working correctly.

**Comment by leastprivilege** [comment]
Revocation only works if you are using reference tokens. 

Is that what you are doing?

**Comment by vanthome** [comment]
Yea that was the issue. Many thanks for the hint!
What I find strange is that I had to use `ScopeSecrets` on the scope and `ScopeSecret` on the client respectively which does not seem to be the case in the samples in _IdentityServer4.Samples_. Without this I always got an error `Secret validators could not validate secret` when the RS tried to introspect the token.
