### ISSUE TITLE
login/signup form where to implement?

### ISSUE THREAD

**Issue by eld1887** [IdentityServer/IdentityServer4#1110]
hi guys, i hope this is the right place to ask my question.
I´m not sure if i understand the operations correct.

What i want: I want an Angular2 Client for example for Login/sign up, identityserver4 for authetification and a protected api written in php. So i read that implict flow as grantype, openid and jwt would be the best.

Nnow i try to understand where i should creat the login form. Normally i would do that in the angular client and send only the data from the login/signup form to the identityserver (what would be the next question, how it works). But at each tutorial for identityServer4 the login form/ui is at the serverside. (ui is implemented at identityserver) 

Could someone describe me the right way to implement it?
 
Thanks in advance

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
