### ISSUE TITLE
Microsoft authentication with IdentityServer4 in asp.net core

### ISSUE THREAD

**Issue by anitchanana** [IdentityServer/IdentityServer4#1111]
Hi
I am trying to integrate microsoft authentication with Identityserver4 in asp.net core application.
When i try to log in with microsoft, it displays the following screen.

Is there support for Microsoft authentication with IdentityServer ?

![microsoft](https://cloud.githubusercontent.com/assets/6780356/25524131/e39fa4ba-2c26-11e7-84ec-c28a298899d3.png)

**Comment by leastprivilege** [comment]
Sure. Try it first in a standalone app to reduce the number of moving parts.

**Comment by anitchanana** [comment]
Hi
I have tried it with standalone app and it worked . But with identity server , it gave me the error above.
Is there is anything that i should share so that we are on the same page ?

**Comment by brockallen** [comment]
The error appears to be on the Microsoft side -- check their error logs.

**Comment by anitchanana** [comment]
ok
I will check that
Thanks

**Comment by leastprivilege** [comment]
any update?

**Comment by anitchanana** [comment]
I have been working on other related stuff .
Once i get over that, will work on this and let you know what i am upto in a day or two
Thanks

**Comment by jimbo74** [comment]
see this issue:
https://github.com/IdentityServer/IdentityServer4.Samples/issues/98

**Comment by brockallen** [comment]
Closing for now -- reopen if needed.
