### ISSUE TITLE
Investigate what else is needed to support external pages (login, etc)

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1112]
https://github.com/IdentityServer/IdentityServer4/issues/1036#issuecomment-298025813

**Comment by brockallen** [comment]
@leastprivilege so you don't think we need anything else here?

**Comment by brockallen** [comment]
@leastprivilege ping

**Comment by leastprivilege** [comment]
I think there is nothing we need to do right now.
