### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by szahn** [IdentityServer/IdentityServer4#1114]
info: IdentityServer4.Startup[0]
      You are using the in-memory version of the persisted grant store. This wil
l store consent decisions, authorization codes, refresh and reference tokens in
memory only. If you are using any of those features in production, you want to s
witch to a different store implementation.
dbug: IdentityServer4.Hosting.CookieMiddlewareExtensions[0]
      Using built-in CookieAuthentication middleware with scheme: idsrv
dbug: IdentityServer4.Hosting.CookieMiddlewareExtensions[0]
      Adding CookieAuthentication middleware for external authentication with sc
heme: idsrv.external
info: Microsoft.Extensions.DependencyInjection.DataProtectionServices[0]
      User profile is available. Using 'C:\Users\\AppData\Local\ASP.N
ET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at r
est.
Hosting environment: Development
Content root path: C:\Host
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/.well-known/openid-con
figuration
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/.well-known/openid-con
figuration
dbug: IdentityServer4.CorsPolicyProvider[0]
      CORS request made for path: /.well-known/openid-configuration from origin:
 http://localhost:60720
dbug: IdentityServer4.CorsPolicyProvider[0]
      CORS request made for path: /.well-known/openid-configuration from origin:
 http://localhost:60720
dbug: IdentityServer4.Services.InMemoryCorsPolicyService[0]
      Client list checked and origin: http://localhost:60720 is allowed
dbug: IdentityServer4.Services.InMemoryCorsPolicyService[0]
      Client list checked and origin: http://localhost:60720 is allowed
dbug: IdentityServer4.CorsPolicyProvider[0]
      CorsPolicyService allowed origin: http://localhost:60720
dbug: IdentityServer4.CorsPolicyProvider[0]
      CorsPolicyService allowed origin: http://localhost:60720
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /.well-known/openid-configuration matched to endpoint type Di
scovery
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Mapping found for endpoint: Discovery, creating handler: IdentityServer4.E
ndpoints.DiscoveryEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpo
int for /.well-known/openid-configuration
dbug: IdentityServer4.Endpoints.DiscoveryEndpoint[0]
      Start discovery request
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.ArgumentException: An item with the same key has already been added. Key:
 IdentityServer4.Hosting.AuthenticationHandler
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key
)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boo
lean add)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAcce
ssor(Type serviceType, ServiceProvider serviceProvider)
   at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey
,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory,
TArg arg)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type s
erviceType)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.GetService(IServicePr
ovider sp, Type type, Type middleware)
   at lambda_method(Closure , Object , HttpContext , IServiceProvider )
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__
18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__
18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__
18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__
18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveN
ext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext() in C:\Re
po\JustEnough.Web.Identity\Dependencies\IdentityServer4\src\IdentityServer4\Host
ing\BaseUrlMiddleware.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>
d__7.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 406.4386ms 200 application/json
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/connect/checksession

dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /connect/checksession matched to endpoint type CheckSession
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Mapping found for endpoint: CheckSession, creating handler: IdentityServer
4.Endpoints.CheckSessionEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.CheckSessionEn
dpoint for /connect/checksession
dbug: IdentityServer4.Endpoints.CheckSessionEndpoint[0]
      Rendering check session result
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 28.5419ms 200 text/html; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/.well-known/openid-con
figuration
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /.well-known/openid-configuration matched to endpoint type Di
scovery
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Mapping found for endpoint: Discovery, creating handler: IdentityServer4.E
ndpoints.DiscoveryEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpo
int for /.well-known/openid-configuration
dbug: IdentityServer4.Endpoints.DiscoveryEndpoint[0]
      Start discovery request
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 12.469ms 200 application/json
info: Microsoft.AspNetCore.Server.Kestrel[14]
      Connection id "0HL4EB50Q4ENE" communication error.
Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4081
 ECANCELED operation canceled
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 581.8279ms 500 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/.well-known/openid-con
figuration/jwks
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /.well-known/openid-configuration/jwks matched to endpoint ty
pe Discovery
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Mapping found for endpoint: Discovery, creating handler: IdentityServer4.E
ndpoints.DiscoveryEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpo
int for /.well-known/openid-configuration/jwks
dbug: IdentityServer4.Endpoints.DiscoveryEndpoint[0]
      Start key discovery request
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 38.5321ms 200 application/json

**Comment by leastprivilege** [comment]
Sorry - what do you expect here? You paste us some logs and we figure out the rest? 

You need to put a little bit more effort into a bug report/issue.
