### ISSUE TITLE
IServiceCollection' does not contain a definition for 'AddIdentityServer'

### ISSUE THREAD

**Issue by nssidhu** [IdentityServer/IdentityServer4#1117]
- [X ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I am following this video https://channel9.msdn.com/Shows/MVP-Show/Episode-2-Germany-Part-III-IdentityServer4-in-Action
I am using VS 2017 and created ASP.NET Core 1.1 Web App. 
I added Nuget Package for Identity server and
I can see the package reference was added in .csproj file
     <PackageReference Include="IdentityServer4" Version="1.5.0" />

I am getting the following Error @ services.AddIdentityServer(); in ConfigureServices of startup.cs.

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'IServiceCollection' does not contain a definition for 'AddIdentityServer' and no extension method 'AddIdentityServer' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	IndentityServer	XXXX\IndentityServer\Startup.cs	60	Active

What am i missing or done wrong here?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by harisbotic** [comment]
This is the package that you need

```  
<PackageReference Include="IdentityServer4" Version="1.5.0" />
```

Don't forget to `dotnet restore` and add this `using Microsoft.Extensions.DependencyInjection;` which you probably all did xD

If the information you provided above are all correct, this should be enough.
Try creating a separate new project and see if it works

**Comment by nssidhu** [comment]
I created a new project and verified that it is using 1.5 and has reference to DependencyInjection. Still same problem. 

I have attached the sample project.
[WebApplication2.zip](https://github.com/IdentityServer/IdentityServer4/files/966791/WebApplication2.zip)

**Comment by harisbotic** [comment]
you wrote `services.AddIdentitServer();`
and it should be `services.AddIdentityServer();`

Intellisense told me that...

**Comment by nssidhu** [comment]
Here is the screenshot
![screenshot identitiyserver 2 2017-04-30_11-06-24](https://cloud.githubusercontent.com/assets/3267605/25565877/a128fa44-2d95-11e7-890c-216349ac517d.jpg)
![screenshot identityserver 2017-04-30_11-08-39](https://cloud.githubusercontent.com/assets/3267605/25565878/a1312b92-2d95-11e7-9210-873f9ec3a4f4.jpg)

**Comment by harisbotic** [comment]
In the project that you sent me everything is working fine for me

**Comment by nenadsavicic** [comment]
Same thing happened to me, try to unload the project and then reload it again, it should work, really weird...

**Comment by nssidhu** [comment]
Yes unloading and reloading the project worked

**Comment by estevban** [comment]
Thanks guys. Unload and load the project also work ok

**Comment by SathishNadarajan** [comment]
Unload and ReLoad the project worked for me
