### ISSUE TITLE
Options for IProfileService?

### ISSUE THREAD

**Issue by PivotalAnimal** [IdentityServer/IdentityServer4#112]
I have code that will save Clients / Scopes to a database similar to the IS4 Host Example. However, I need to think about how to handle IProfileService. (builder.AddInMemoryUsers(Users.Get())). What comes to mind is something along the lines of ASP.NET Identity. Salt / Hash, etc. Perhaps I could grab the latest code on github and copy it for my own. Do you have any advice or know of any good projects that store user names / passwords securely and / or that are built for IS3 / 4?

**Comment by leastprivilege** [comment]
Use the aspnet core web app template with individual auth. This has all the aspnet identity pieces in it. Learn it and understand it. Then apply to idsrv's login pages.

**Comment by PivotalAnimal** [comment]
I can see now how a 'UserStore' could be quite varied across use-cases. I am trying to take a simple approach and have one place users log into for many sites. Basically a user interface with my logo that extends the IS4 Host project somehow. User management screens would be nice as well. Maybe this is the wrong approach and i should instead use two sites for this, one using asp.net identity pretty much out of the box. Maybe I am confused. That being said, I also want to ensure the passwords are stored encrypted. I can build code to do this. The headache of forced lockout, etc is another concern of mine. Anyhow, my followup question is, if I created a User mimicking the example and a simple IProfileService would one User be associated with many Client / ClientClaims or should it be a strictly one to one. (one user name / password) = one IdentityServer4.Core.Models.Client or should it be one to many? Also, more interfaces for IS4 models might be handy for extensibility purposes.
