### ISSUE TITLE
Sending custom params from client on silent renew / refresh in implicit flow

### ISSUE THREAD

**Issue by Krishna-teja** [IdentityServer/IdentityServer4#1121]
Is there any way we could pass extra parameters to the signinsilent / silent refresh call from oidc-client that we could tap on in the profile service so that I could add extra claims to the access token?

**Comment by brockallen** [comment]
The resource definitions have user claims -- does that not work for your scenario?

**Comment by Krishna-teja** [comment]
@brockallen 
Recently we've started implementing IdentityServer4 in our company. 

Our setup is something like this:
We have an SIS (Student information system) developed in house which has 9 different products. We are integrating all the products so that we can have seamless SSO solution between different products. All the products are purely Angular apps and they call APIs using access tokens and we are using oidc-client on client side. We use silent renew to renew the token on all client side js apps.

All the students and staff have single identity but can have access to multiple schools. 

We have a lot of claims that we generate where most of them go as part of token so that API can use those claims. But for every product users(staff/students) can change schools. When they change new claims are being generated for that school and everything works fine. The problem that I am running into is that we needed to provide ability for users to be on different schools in multiple tabs of the same client. So Client1Tab1 and Client1Tab2 can be from different schools which could have different claims all together. In order to support that, there are two ways to maybe solve this, 
1. On every silent renew, send school codes to Profile service to add separate claims into access token for the same client or
2. Remove the school related claims all together from Token and maybe on every API call include a separate header like SchoolCode info so that API could query for necessary info. 

So wanted to know if the first method could work so that an extra query would be eliminated for every API call.

**Comment by brockallen** [comment]
The fact that the user has different data in the context of different schools sounds like business data, not identity data. IOW, you might be asking the identity system to be doing things your business APIs should be. The identity system has done its job -- provide a single identity across all your apps (products). Of course, it's hard to help design a system via github issues, and that's not the purpose of the issue tracker.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
