### ISSUE TITLE
IdentityServer4.AspNetIdentity usage sample

### ISSUE THREAD

**Issue by adimitri64** [IdentityServer/IdentityServer4#1122]
Hi guys I've followed the IdentityServer4 guide and everything was fine with the QuickStarts until I've tried the 6th sample (AspNetIdentity). This sample uses IdentityServer4.AspNetIdentity assembly. As you know, the standard implementation is using EF. Now, I've already removed EF from a AspNet identity application but not in AspNetCore.
The underlying models have changed a lot from AspNet to AspNet core so I'm asking if someone can point me to some resource that shows how to remove EF from an AspNetCore implementation.
Many thanks all

adimitri64

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
