### ISSUE TITLE
Search  subject in ClaimsIdentity with ClaimTypes.NameIdentifier too.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4#1124]
I not sure this is my mistake or a bug. 
I have a MVC implicit client with following configuration. 

```
 var configs = new OpenIdConnectOptions
            {
                AuthenticationScheme = "Oidc",
                SignInScheme = "idsrv",
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                PostLogoutRedirectUri = "xyz",
                Authority = "abc",
                RequireHttpsMetadata = false,
                ClientId = "myclient",
                ResponseType = "id_token",
                Scope = { "openid", "profile", "email" },
                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = JwtClaimTypes.Name,
                    RoleClaimType = JwtClaimTypes.Role,
                }
           };
```
1.  When sign in from my identity server (size of the cookie is 617 bye) and then sign in to the client `User.Identity.Name` is correct and.

2.   When sign in from my the client (size of the cookie is 2366 bye) `User.Identity.Name` is NULL  ,and then I visit a secure MVC controller on the IsentityServer , the `User.GetSubjectId() `throw "sub claim is missing" exception. 
I change the method as bellow  and all thing work fine:

```
 public static string GetSubjectId(this IIdentity identity)
        {
            var id = identity as ClaimsIdentity;
            var claim = id.FindFirst(JwtClaimTypes.Subject);

            if (claim == null)
            {
                claim = id.FindFirst(ClaimTypes.NameIdentifier);
            }

            if (claim == null)
            {
                throw new InvalidOperationException("sub claim is missing");
            }
            return claim.Value;
        }

```

Thanks a lot for your time .

**Comment by mule** [comment]
I know this is old and closed  but ts this a bug or is it caused by some config issue etc?
Because the code in PrincipalExtensions.cs is still the same. Just asking because I have the exact same problem and AFAIK there is no PR to fix this.
Anyways, going to use the fix provided by @mikeandersun for now at least.
