### ISSUE TITLE
Claims do not contain "token" - how do I enable?

### ISSUE THREAD

**Issue by opinionmachine** [IdentityServer/IdentityServer4#1127]
- [ x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Use any api sample, set a breakpoint after api has been called. Look at Claims enumeration. See that a claim "token" does not exist.
Google for 36 hours
Look through the source for another 5
Notice that a thread about the v4 equivalent of preserveAccessToken was summarily dismissed without even a link to the supposed thing that was replacing it.

### Relevant parts of the log file

N/A
```
<log goes here>
```

**Comment by leastprivilege** [comment]
Use intellisense on options. Find `SaveToken` ??

**Comment by opinionmachine** [comment]
Sorry, I omitted that step from my list. That went in at step 1 actually, apologies for being unclear. 

I could parse the Authorization header for my delegation purposes (to the incoming access token back to the Token endpoint to get a new delegated access token like the docs say) but I want the code to look pretty.

**Comment by leastprivilege** [comment]
Use SaveToken and use the extensions for AuthenticationManager to retrieve it in your code.

**Comment by brockallen** [comment]
All set on this? Can we close?

**Comment by opinionmachine** [comment]
It doesn't work like in IdentityServer3 with claims o  the principal. But there is an undocumented way to get the token from the context, so I'm happy. Thanks guys!

**Comment by rosdi** [comment]
For those who are migrating from IdentityServer3 and arrived at this page from Google, you can get the access token like so:

`var accessToken = await httpContextAccessor.HttpContext.GetTokenAsync("access_token");`

Took me a while to figure this out... duh!
