### ISSUE TITLE
Disable default caching for discovery

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1132]

**Comment by brockallen** [comment]
fixed

**Comment by laurynasr** [comment]
Why was this change done?
At least the doc comments still say that it defaults to one hour:
https://github.com/IdentityServer/IdentityServer4/blob/e130df9abd0b915cf70603442c6b32f9528d350a/src/IdentityServer4/Configuration/DependencyInjection/Options/DiscoveryOptions.cs#L70

**Comment by brockallen** [comment]
The change was done because once you go to production you are expected to choose these values (not us). Also, if you don't know about the value and it's set by default then you might have unexpected behavior in prod.
