### ISSUE TITLE
Call between APIs with different scopes with shared access token

### ISSUE THREAD

**Issue by Bemjamin** [IdentityServer/IdentityServer4#1133]
It is possible to have something like this? How to share the access token between two APIs with different scopes? 

![image](https://cloud.githubusercontent.com/assets/1276294/25730285/531f72c0-3109-11e7-9bb9-90f4a95e6d7f.png)

**Comment by leastprivilege** [comment]
docs: https://identityserver4.readthedocs.io/en/release/topics/extension_grants.html
