### ISSUE TITLE
Which in-app browser in UWP and Xamarin.Droid?

### ISSUE THREAD

**Issue by Ponant** [IdentityServer/IdentityServer4#1136]
Hi @leastprivilege , @brockallen ,
I have been following your videos in trying to get acquainted with IS4 and stumbled upon Dominik's recommendation not to use WebView and Web Authentication Broker (WAB), but rather an in-app browser, here https://vimeo.com/205451987. He showed the example with a Xamarin.IOS where the in-app browser is basically Safari. I know of only WebView in a UWP and the sample here https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/Uwp seems to use a WAB. Is there any equivalent to the Safari example for UWP and Xamarin.Droid?

**Comment by leastprivilege** [comment]
On UWP you can use the system browser just like our console sample. On Android it is recommended to use Chrome custom tabs.

**Comment by Ponant** [comment]
Thanks @leastprivilege for your time. I will try this out, I am unsure on how to handle a redirect to the app if I use the system browser (on a phone in particular), because if I remember the browser in the console app sample will just tell you that you can now return to your app, whereas a user would expect to be returned back to the app ui after authentication is done. It might not be optimal but I have to try it out.

**Comment by leastprivilege** [comment]
Check their docs and read the OAuth for native apps spec. This is all possible.
