### ISSUE TITLE
Introspect rfc7662

### ISSUE THREAD

**Issue by madsj** [IdentityServer/IdentityServer4#114]
I have been looking at the source code of introspect. Is is correct that it is not possible to validate refresh_tokens?

If I remember the RFC7662 spec correct then "token" can be either a refresh or a access token. And the "token_type_hint" can also be of value "acces_token" and "refresh_token".

The reason why I am asking is because as a client I want to validate a refresh token that I have obtained from the IdentityServer.

**Comment by leastprivilege** [comment]
thats not implemented. and pretty unusual as well. To validate a refresh token - try to use it.

**Comment by madsj** [comment]
Thanks for fast reply
