### ISSUE TITLE
how to prevent rogue users from bypassing login=prompt 

### ISSUE THREAD

**Issue by architau** [IdentityServer/IdentityServer4#1141]
When a client wants to force a user to login again, this can be done by passing the login=prompt in the authorizerequest. But what is preventing a rogue user from manually opening the url and omitting the login=prompt and by this: bypassing a security measure that the client is trusting upon? 

At this moment, the user will get the requested tokens without IdentityServer prompting the user as far as I can tell? I tried to add code to force a prompt in the CustomAuthorizeRequestValidator, but found it impossible to detect whether the ValidateAsync is triggered by the initial request of the client or by the roundtrip to identityserver after the validation process. Simply adding promp=login to the request is therefor not an option as this immediately results in an infinite loop..

A simple context on the calling function would help in fixing this problem, but perhaps this is something that also could be included in the client configuration model? IdentityServer could then force a login prompt when a client config specifies it expects one? The client itself can set a prompt=login parameter on the authorize request but can never truly trust the parameter being there when it reaches IdentityServer?

Am I missing something trivial here?

**Comment by leastprivilege** [comment]
You can check the iat claim - that tells you when authentication has happened. It should be recent in that case.

**Comment by architau** [comment]
thanks for the quick response. In my case iat doesn't solve the problem at hand, the auth_time does as this gives the time the user originally logged in. So thanks for that! 

this leaves the problem of enforcing prompt at the different clients though. I would be fantastic if identityserver could enforce this by design. To reduce possible identity theft as a result of insufficiently or poorly secured clients that simply trust the promp=login to be present even if they should not. 

could identityserver assist in reducing this problem by adding an extra property in the client config object enforcing login=prompt? Or another option, by enhancing the CustomAuthorizeRequestValidator such that it can force prompt without running in an infinite loop?

**Comment by brockallen** [comment]
> thanks for the quick response. In my case iat doesn't solve the problem at hand, the auth_time does as this gives the time the user originally logged in. So thanks for that!

Are you saying that when the user re-enters credentials the auth_time is not getting updated? If so, this is a problem/bug.

**Comment by brockallen** [comment]
> this leaves the problem of enforcing prompt at the different clients though. I would be fantastic if identityserver could enforce this by design. 

Also, this is not something you can blindly trust of the token server -- you need to validate the response in some way to ensure your requirement has been met, thus the suggestion of the auth_time.

**Comment by architau** [comment]
auth_time gave me the correct information as far as I can tell.  So no bug at this point.  Regarding the other response: I understand your point of view. Thanks for the insight!

**Comment by Mardoxx** [comment]
leastprivilege, said `iat`, not `auth_time` perhaps this is where the confusion lies!

I would asusme `auth_time` returns the time at last authentication, not the time the token was, effectually, created. If this does, indeed, update correctly then just verify that the time they last authed in your sensitive api falls within a reasonable time period - as brockallen, and, I presume, leastprivilege suggested - if it doesn't just send back an unauth response that client will pick up on to relog user.

**Comment by architau** [comment]
thanks for your help and for pointing me in the right direction! Issue can be closed as far as I am concerned...
