### ISSUE TITLE
Authorization Code Flow, Redirect URI HTTP method

### ISSUE THREAD

**Issue by Neku** [IdentityServer/IdentityServer4#1142]
I'm trying to use a code flow in a native iOS app through the custom URL schemes as redirect_uri (i.e. myapp://success). The issue is that IdentityServer is using a 302 POST instead of GET and that doesn't sit well with Safari on iOS.
Is there any way to configure the http method used for the redirect?

**Comment by leastprivilege** [comment]
Is it native iOS - see here:
https://github.com/openid/AppAuth-iOS

or C#
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/iOSClient

**Comment by Neku** [comment]
My question is how IdentityServer chooses the HTTP method to use for a redirect, because when Safari (at lease in iOS 10) doesn't allow a POST on a custom url scheme.

**Comment by leastprivilege** [comment]
it's controlled by the `response_mode` parameter.  Different grant types allows for different response modes.

What's your grant type?

**Comment by Neku** [comment]
*facepalm* I completely missed it
`response_mode=form_post`, thank you for the support!
