### ISSUE TITLE
ASP.NET Core, IdentityServer4, custom registration mechanism

### ISSUE THREAD

**Issue by alexwilsh** [IdentityServer/IdentityServer4#1147]
Hi,
First of all let me to describe the flow I implemented in my project.
I have ASP.NET Core MVC project (MVC client) and IdentityServer4 (Identity server).
An user can access almost all pages on the website, but there are few which are protected by authentication. 

Login and Registration forms are on the Identity server side. MVC client passes an additional parameter to Identity Server with the url for redirecting after authentication. This is configured by the 'ReturnUrlParameter' property of CookieAuthenticationOptions (I set it as 'requestedUrl'). 

I have Login action on the MVC client side which is protected by Authorize attribute and has 'requestedUrl' argument. That means that whenever I need to authenticate an user, I just redirect him to my internal action and pass there 'requestedUrl'. Once Identity Server authenticated an user, I have the redirect to my internal Login action where I can grab 'requestedUrl' parameter and do local redirect to the page where an user requested an authentication.

This works well with the login flow. But the issue is with the registration.

User can request the registration from the login page. The registration consists of few steps: 
* user enters some basic data + his email
* system sends an email with the link to user and generated pin code
* user clicks that link which redirects him to activation page, enters pin code
* after activation, user is redirected to login page 
* and now after the login page I need to redirect this user back to that page in MVC client where he requested the authentication.

If I have the access to 'requestedUrl' parameter on Identity server side, I could save this value to the database and use it after successful registration to redirect to appropriate page. But I don't see this neither in Request, nor in authentication context on Identity server side.

Could you help me to resolve this task? Or point me to the correct way of implementing this.

Thanks in advance.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
