### ISSUE TITLE
Identity server with implicit flow trying to load unnecessary scripts from an unknown port number at login and checksession call after login

### ISSUE THREAD

**Issue by pmaheshgupta** [IdentityServer/IdentityServer4#1148]
I am working with Identityserver4 and SPA app using Implicit flow.

When attempting to login Identity server is trying to load unnecessary scripts from an unknown port number at **login** and **checksession call** after login

But these scripts are blocked from being loaded due to CSP. Why is Idsvr trying to load the scripts and I don't see any references to these files in the code as I searched complete solution with the endpoint it is trying to load.

It will be a big issue if the Idsvr behaves like this in the production. Can any one help me understand and solve this issue?

I uploaded the complete project to github to replicate.
[https://github.com/pmaheshgupta/Identityserver4samplescenarios](https://github.com/pmaheshgupta/Identityserver4samplescenarios)

Attaching the images from the chrome console.

![unwantedcallsissue1](https://cloud.githubusercontent.com/assets/4446188/25887193/a878b104-357e-11e7-9ae2-c22f1f01c9a9.png)
![unwantedcallsissue2](https://cloud.githubusercontent.com/assets/4446188/25887194/a87dd904-357e-11e7-9c40-acb65fc1d02e.png)
![unwantedcallsissue3](https://cloud.githubusercontent.com/assets/4446188/25887195/a87f5eb4-357e-11e7-9d59-ff91017f859c.png)

**Comment by leastprivilege** [comment]
That looks like browserlink - which is some weird MS debugging thing you have enabled in your VS.

Unrelated to IdentityServer.
