### ISSUE TITLE
Library conflict using RC2 with framework net452

### ISSUE THREAD

**Issue by marspd** [IdentityServer/IdentityServer4#115]
HI there
I am using the IdentityServer4 1.0.0-beta2 for RC2 and have my IdSrv running fine with the framework  netcoreapp1 defined in project.json as per the samples.

However, due to other project requirements I need to target the net452 framework and I have changed the project.json accordingly.

The problem is when I compile I get the following error
JPC.IdSrv\UI\Login\LoginService.cs(42,84): error CS0433: The type 'Claim' exists in both 'System.Security.Claims, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

I've tried all sorts but to be honest I am not sure how to track down and resolve this issue.

Any pointers at all would be most welcome.

Regards
Paul

**Comment by leastprivilege** [comment]
use the latest version - it should work there.

**Comment by marspd** [comment]
Indeed it does work with the latest version, I didn't realise there had been another update. Apologies for bothering you. I should have checked that first.
Regards
Paul
