### ISSUE TITLE
Customize Validation Messages for Token Endpoint

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1153]
Is it possible to customize validation messages sent by the token end point /connect/token

**Comment by leastprivilege** [comment]
What is a validation message?

**Comment by satyajit-behera** [comment]
BadRequest messages

**Comment by leastprivilege** [comment]
No - the core error messages are according to the spec.

**Comment by satyajit-behera** [comment]
Thanks.
