### ISSUE TITLE
revocation of token does not revoke the token and works with api resource end point

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1154]
I have a server: Server1 (configured with identity server)

I have a web api (configured with identity server AccessTokenValidation.

Token generated from the server using /connect/token works well.
Accessing the API using the token also works well.

When I revoke the generated token using /connect/revocation, I get a 200 OK BUT I am still able to access the API using the token.

Revocation of token does not work.

**Comment by brockallen** [comment]
> Revocation of token does not work.

Only possible for reference tokens and refresh tokens.

**Comment by satyajit-behera** [comment]
Thanks, whats the best practices to safeguard the token when we want to log out someone. Should we keep the token lifetime very short and rely on refresh tokens.

**Comment by TomCJones** [comment]
right - you are at the core of the problem.

Once a right has been granted, it is always a challenge to take that right away.

You have to balance the user experience with security to get the best of both.

That is always a trade-off.   ..tom
________________________________

**Comment by Blastnsmash** [comment]
This isn't a problem at all. You handle this by setting timeouts on cookies and tokens themselves - two different data stores of cache. Remember, there is a trade-off in performance. The more frequent you re-check and reinitialize the tokens/cookies - the less performant the system. 

Here is an example of refreshing a cookie in an mvc app: 
https://stackoverflow.com/questions/42987741/refresh-claimsprincipal-with-openidconnect-middleware-mvc-client-cookies

In the link above, what Dominic said is in response to the authorization part. You don't want to put application specific data into your identity and access tokens. Rather, minimize the information in these data-stores as much as possible but have enough information there to query an application specific data-store that can verbosely describe your authorization rules for your application.

**Comment by khennny** [comment]
I think using reference token might be a better approach than reducing the lifetime of access token.
It provides immediate token revocation .
