### ISSUE TITLE
Identity Server 4 Running Behind a load Balancer

### ISSUE THREAD

**Issue by adussarpsbcg** [IdentityServer/IdentityServer4#1157]
I have setup Identity Server 4 for my project using Entity Framework. I already configured the service to use a persisted grant Store and a Signed Certificate.
```

services.AddIdentityServer()
        .AddSigningCredential(Config.GetSigningCertificate())
        .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>()
        .AddProfileService<ProfileService>()
        .AddConfigurationStore(builder =>
                    builder.UseSqlServer(connectionString, options =>
                        options.MigrationsAssembly(migrationsAssembly)))
        .AddOperationalStore(builder =>
                    builder.UseSqlServer(connectionString, options =>
                        options.MigrationsAssembly(migrationsAssembly)));
```

Here is the configuration of the service.

The problem is when I run my server behind a load balancer with for exemple 2 identic instances handling all the request, the server where the user did not logged in fail to decode the JWT token, leading to 401 unauthorized errors.

I'm assuming the sigining method of the tokens or their encription is the problem but I cannot find a way to solve this.

Here is the rest of my configuration.

The Configure:
```
 app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
{
      Authority = url,
      // Authority = "http://localhost:5000",
      AllowedScopes = { "WebAPI" },
      RequireHttpsMetadata = false,
      AutomaticAuthenticate = true,
      AutomaticChallenge = true,
})
```

the Client:
```
 new Client
{     ClientId = "Angular2SPA",
     AllowedGrantTypes = GrantTypes.ResourceOwnerPassword, // Resource Owner Password Credential grant.
     AllowAccessTokensViaBrowser = true,
     RequireClientSecret = false, // This client does not need a secret to request tokens from the token endpoint.
     AccessTokenLifetime = 7200, // Lifetime of access token in seconds.
     AllowedScopes = {
                       IdentityServerConstants.StandardScopes.OpenId, // For UserInfo endpoint.
                       IdentityServerConstants.StandardScopes.Profile,
                       "roles",
                       "WebAPI"
                      },
     AllowOfflineAccess = true, // For refresh token.
     AccessTokenType = AccessTokenType.Jwt
} 

```
I also implemented my own IResourceOwnerPasswordValidator and IProfileService based on EF validations.

Any idea why is this happening?

**Comment by leastprivilege** [comment]
> fail to decode the JWT token

Who fails to decode token? did you turn on logging where this happens?

**Comment by adussarpsbcg** [comment]
There is 2 servers working in parallel and the one that did not provided the token fail to validate it and returns 401 unauthorized on the apis routes.

**Comment by leastprivilege** [comment]
Then turn on logging in the API to see what exactly is going wrong...

**Comment by adussarpsbcg** [comment]
Hey, I found the error, the Elastic Beanstalk env was not the same on the 2 servers, leading to an authority error.You can close the issue.
