### ISSUE TITLE
Consider adding interfaces to object to allow consumers to more easily test

### ISSUE THREAD

**Issue by kiyote** [IdentityServer/IdentityServer4#1158]
When creating unit tests for code that consumes things like IntrospectionClient, etc, creating a mock is impossible because it has neither an interface or virtual methods.  By simply adding interfaces with an API declaration that matches the object the usage of the client and responses, etc, could be easily mocked out.

**Comment by brockallen** [comment]
I think you meant to open this issue in this repo: https://github.com/IdentityModel/IdentityModel2
