### ISSUE TITLE
Azure Key Vault

### ISSUE THREAD

**Issue by MatthewGabriel** [IdentityServer/IdentityServer4#1159]
Hi,

Does anyone have any advice about using Azure Key Vault for storing asymmetric keys for use in IdentityServer?  I can only find limited information about using certificates, but I'd rather use an RsaSecurityKey.

Thanks,

**Comment by Mardoxx** [comment]
You can store certs in keyvault as secrets (they are stored as Base64 encoded strings) then in your startup you can pull them down using keyvault rest api and read into `X509Certificate2`.

**Comment by TomCJones** [comment]
certs aren't secrets, they are public.  I think you mean keys.   ..tom


________________________________

**Comment by Mardoxx** [comment]
Yes

**Comment by MatthewGabriel** [comment]
I was specifically thinking keys, rather than certificates.  Keys are stored in the keys section and certs in the secrets section and the private key never comes out of the vault (as I understand it).  Furthermore, I want to take advantage of key rolling (versions) within the key vault, so the application needs to be able to see the new key when it changes.  I'm going to be looking into it properly soon, so I will post any findings here when that happens, but just wondered if anyone had already done it.

**Comment by leastprivilege** [comment]
You can replace (or derive) from your default token creation service -

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultTokenCreationService.cs

and then use the KeyVault API to obtain a signature.

**Comment by MatthewGabriel** [comment]
Thank you @leastprivilege for pointing me in the right direction.  I should get to look into this over the next week.  And also thank you and @brockallen for IdentityServer4, amazing piece of work.

**Comment by TomCJones** [comment]
be careful to mark the key as non-exportable if that's what you want
