### ISSUE TITLE
Auth0 Type Lock Widget

### ISSUE THREAD

**Issue by maganuk** [IdentityServer/IdentityServer4#1160]
@brockallen This is not really an issue, but more of a general question. How does the Auth0 Lock widget work? I want to implement something similar in my SPA. As I understand, in an implicit flow for a SPA, its best practice to redirect to the Identity Server which means we cant use a modal window. How does Auth0 do it? Are they really using a resource owner flow in a SPA, and is it safe to do so? What about if we're on https?

**Comment by brockallen** [comment]
> How does the Auth0 Lock widget work

with a custom handshake to the STS login page (either with ajax or an iframe -- i forget which). it's very clever, but not anything you'd see in the OIDC spec.

**Comment by maganuk** [comment]
Got it. Presume nothing like this is planned for Identity Server since we follow the OIDC spec very stringently?

**Comment by brockallen** [comment]
correct
