### ISSUE TITLE
JavaScript Client flow with ResourceOwnerPasswordValidator IdentityServer4

### ISSUE THREAD

**Issue by zorro-lp** [IdentityServer/IdentityServer4#1166]
Hi,

I added custom ResourceOwnerPasswordValidator to my Identity Server. I have a SPA client, in that user enter their username and password, then access the API which is protected by IdentityServer4. 

The quickstarts samples [7_JavaScriptClient] uses oidc-client.js, so when you click Login, it will redirect to Identity Server site. I would like the user to log in from my client app.

I think of calling identity server http://localhost:5000/connect/token from my client app with hard coded client secret. Is it safe to do that? If it is not safe, which ways do you recommend?

Thanks,
Nga

**Comment by brockallen** [comment]
The oidc-client library is designed for the implicit flow, not resource owner password flow. JS clients can't keep secrets, so don't use one.

**Comment by zorro-lp** [comment]
Hi, My JS client is a React app on ASP.NET Core. Is it a good way if I create an api controller that get token from new TokenClient(endpoint, client, secret).RequestResourceOwnerPasswordAsync, then call the api from my custom login page?

**Comment by brockallen** [comment]
You can, sure.

**Comment by zorro-lp** [comment]
Thanks.
