### ISSUE TITLE
API with identity Server

### ISSUE THREAD

**Issue by walid1001** [IdentityServer/IdentityServer4#117]
Hi, I'm new with Identity server and I spent a while with the samples. 

I'm trying to use Identity Server with an API I'm building. the users will be from Identity server database and from openid source (facebook or google).

the idea is have all the users (local + openid) registered into identity server as local + linked accounts.

at the end, with a token from openid, making a call to the library securely.

is this a correct scenario ? am I missing something ?

Thank you for your help.

regards,

walid

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
