### ISSUE TITLE
"Message contains error: 'invalid_grant', error_description: 'error_description is null', error_uri: 'error_uri is null'."

### ISSUE THREAD

**Issue by adolya** [IdentityServer/IdentityServer4#1170]
Hi

I'm experiencing an issue hosting my Identity server behind load balancer.
I have 2 instances. And in 50% of them I receive and an exception on client after successful login.
`"Message contains error: 'invalid_grant', error_description: 'error_description is null', error_uri: 'error_uri is null'."`

Logs from server 
`IdentityServer4.Validation.TokenRequestValidator[0]
      Invalid authorization code: aa860c2e4b5383591dff5ade8b7fb0e73495082ea822ec45258ccff6a0946d8f`

Steps to reproduce: 
1. Open Mvc client in Chrome, that is configured to work in hybrid mode and press login (this will redirect to Identity Server).
2. Enter credentials and press login. This will authenticate and redirect. Everything works as expected.

Open Chrome in "Incognito mode" and repeat the steps 1-2.
After successful redirect I receive the exception on client described above.

Server:
```csharp
var identityBuilder = services
			.AddIdentityServer()
			.AddSigningCredential(new X509Certificate2("IdentityServerAuth.pfx"))
			.AddInMemoryIdentityResources(InMemoryConfig.GetIdentityResources())
			.AddInMemoryApiResources(InMemoryConfig.GetApiResources())
			.AddInMemoryPersistedGrants();
```

Client:
```csharp
app.UseCookieAuthentication(new CookieAuthenticationOptions
		{
			AuthenticationScheme = "Cookies",
			AutomaticAuthenticate = true,
			ExpireTimeSpan = TimeSpan.FromMinutes(60),
			AccessDeniedPath = "/Error/AccessDenied"
		});
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
		{
			AuthenticationScheme = "oidc",
			SignInScheme = "Cookies",
			Authority = "http://identity.server",
			RequireHttpsMetadata = false,
			ClientId = "ClientId",
			ClientSecret = "ClientSecret",
			ResponseType = "code id_token",
			Scope = {"openid", "profile", "email", "myclient", "offline_access"},
			GetClaimsFromUserInfoEndpoint = true,
			SaveTokens = true,
			TokenValidationParameters = new
				Microsoft.IdentityModel.Tokens.TokenValidationParameters
					{
						NameClaimType = JwtClaimTypes.Name,
						RoleClaimType = JwtClaimTypes.Role,
					},
					Events = new OpenIdConnectEvents()
					{
						OnRemoteFailure = context =>
						{
							context.Response.Redirect("/error");
							context.HandleResponse();
							return Task.FromResult(0);
						}
					}
		});
```
P.S. I checked the direct connection, around the balancer. Everything works as expected

**Comment by brockallen** [comment]
`AddInMemoryPersistedGrants` is the issue. you need a database, as we describe in the docs: https://identityserver4.readthedocs.io/en/release/topics/deployment.html

**Comment by hnviradiya** [comment]
Hey, I have same issue. Why do I need database, as in my case, I don't have load balancer. I am using normal chrome window.

**Comment by Saldash** [comment]
> `AddInMemoryPersistedGrants` is the issue. you need a database, as we describe in the docs: https://identityserver4.readthedocs.io/en/release/topics/deployment.html

Resource link is no longer valid

**Comment by Ran-snow** [comment]
http://docs.identityserver.io/en/latest/topics/deployment.html#operational-data

**Comment by YashwanthRoy** [comment]
Hi, 

Im experiencing the same issue with identityserver4, .net core 2.2 where my config is as

Client Configuration is as --

          new Client
                {
                    ClientId = "dummy",
                    ClientName = "Dummy",

                    ClientSecrets =
                    {
                        new Secret("secret".Sha512())
                    },

                    AllowedGrantTypes =
                    {
                        GrantType.Hybrid
                    },

                    RequireConsent = false,

                    RedirectUris = { "https://localhost:44321/signin-oidc" },
                    FrontChannelLogoutUri = "https://localhost:44321/signout-oidc",
                    PostLogoutRedirectUris = { "https://localhost:44321/signout-callback-oidc" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.OfflineAccess,
                        "api"
                    },

                    AllowOfflineAccess = true,

                    UserSsoLifetime = 7 * 24 * 60 * 60,
                    AccessTokenLifetime = 4 * 60 * 60, 
                    AbsoluteRefreshTokenLifetime = 3 * 24 * 60 * 60,
                    SlidingRefreshTokenLifetime = 1 * 24 * 60 * 60,
                    RefreshTokenUsage = TokenUsage.ReUse,
                    RefreshTokenExpiration = TokenExpiration.Sliding
                }


And MVC client as


           services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            })
            .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
            {
                options.LoginPath = new PathString("/Account/Login");
                options.SlidingExpiration = true;
                options.ExpireTimeSpan = TimeSpan.FromDays(7);
            })
            .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
            {
                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

                options.Authority = Configuration["IdaAuthority"];
                options.ClientId = Configuration["ClientId"];
                options.ClientSecret = Configuration["ClientSecret"];

                options.ResponseType = OpenIdConnectResponseType.CodeIdToken;
                options.ResponseMode = OpenIdConnectResponseMode.FormPost;

                options.Scope.Clear();
                options.Scope.Add(IdentityServerConstants.StandardScopes.OpenId);
                options.Scope.Add(IdentityServerConstants.StandardScopes.OfflineAccess);
                options.Scope.Add("api");

                options.SaveTokens = false;

                options.GetClaimsFromUserInfoEndpoint = true;

                options.TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = JwtClaimTypes.Name,
                    RoleClaimType = JwtClaimTypes.Role,
                };

                options.ClaimActions.MapAllExcept("iss", "nbf", "exp", "aud", "nonce", "iat", "c_hash");

                var existingOnAuthorizationCodeReceivedHandler = options.Events.OnAuthorizationCodeReceived;
                options.Events.OnAuthorizationCodeReceived = async context =>
                {
                    await existingOnAuthorizationCodeReceivedHandler(context);

                    var idaAuthority = Configuration["IdaAuthority"];
                    var client = new HttpClient();
                    var tokenRequest = new AuthorizationCodeTokenRequest
                    {
                        Address = $"{idaAuthority}/connect/token",
                        ClientId = context.TokenEndpointRequest.ClientId,
                        ClientSecret = context.TokenEndpointRequest.ClientSecret,
                        Code = context.TokenEndpointRequest.Code,
                        RedirectUri = context.TokenEndpointRequest.RedirectUri
                    };

                    var tokenResponse = await client.RequestAuthorizationCodeTokenAsync(tokenRequest);
                    if (tokenResponse.IsError)
                    {
                        throw new Exception(tokenResponse.Error);
                    }

                    var userInfoRequest = new UserInfoRequest
                    {
                        Address = $"{idaAuthority}/connect/userinfo",
                        Token = tokenResponse.AccessToken
                    };

                    var userInfoResponse = await client.GetUserInfoAsync(userInfoRequest);
                    if (userInfoResponse.IsError)
                    {
                        throw new Exception(userInfoResponse.Error);
                    }

                    var identity = new ClaimsIdentity(context.Principal.Identity.AuthenticationType);
                    identity.AddClaims(userInfoResponse.Claims);
                    identity.AddClaim(new Claim("access_token", tokenResponse.AccessToken));
                    identity.AddClaim(new Claim("expires_at", DateTime.UtcNow.AddSeconds(tokenResponse.ExpiresIn).ToLocalTime().ToString()));
                    identity.AddClaim(new Claim("refresh_token", tokenResponse.RefreshToken));
                    context.Principal.AddIdentity(identity);
                };

`


using SaveTokens = true, is creating a cookies of very large size, so i want it to fetch tokens manually and put required in the cookie.

everything seems to be fine, but just after sucessfull signin the OnAuthorizationCodeEvent triggers and the call to token end point is made and the tokens are saved in cookie. then the oidc middleware redirects the app to redirect uri /signin-oidc where a second call is made to token end point and there it throws error

An unhandled exception occurred while processing the request.
OpenIdConnectProtocolException: Message contains error: 'invalid_grant', error_description: 'error_description is null', error_uri: 'error_uri is null'.
Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

Logs --

![Screenshot (263)_LI](https://user-images.githubusercontent.com/36771763/63848361-52f7af80-c9ad-11e9-9e11-89d8855b9565.jpg)


any help?
