### ISSUE TITLE
External Login JwtClaimTypes.Email

### ISSUE THREAD

**Issue by Kieken72** [IdentityServer/IdentityServer4#1171]
Starting from the quickstart using google authorisation only. I failed to retrieve the emailadress in the claims by using JwtClaimTypes.Email:
`var email = claims.FirstOrDefault(x => x.Type == JwtClaimTypes.Email);
            if (email != null)
                additionalClaims.Add(new Claim(JwtClaimTypes.Email, email.Value));`

Instead I had to use the following to retrieve the email adress from google.
`var email = claims.FirstOrDefault(x => x.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress");;`

Shouldn't be needed?

**Comment by mackie1001** [comment]
I've noticed the same thing. My guess is that the default mapping logic in the TokenValidator is kicking in when it probably shouldn't in this case. I just look for both claim types to work around it, not a massive deal.

**Comment by brockallen** [comment]
It's because Microsoft's Google auth MW uses strange XML-based claim types for the email.
