### ISSUE TITLE
Customization of logic for connect/token endpoint

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1176]
Is it possible to customize the logic for connect/token end point to add more parameters and write our own logic to validate a user and grant access token?

**Comment by leastprivilege** [comment]
yes - try this one

https://identityserver4.readthedocs.io/en/release/topics/resource_owner.html

**Comment by satyajit-behera** [comment]
@leastprivilege Thanks

**Comment by alexsandro-xpt** [comment]
@leastprivilege the link is breaked.

**Comment by markmcgookin** [comment]
Here's the updated docs. There really needs to be a redirect for the old docs. 

http://docs.identityserver.io/en/latest/topics/resource_owner.html
