### ISSUE TITLE
Documentation : Left menu does not display all topics all the time. It depends on the details section.

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1177]
Was going through the documentation.
The left menu shows up the topic only to an extent to which the details section shows up in length.

If the details section is small, the menu content to the left does not scroll to the the last topic.
Only if the details content is very long, all the menu items shows up.

This link:
https://identityserver4.readthedocs.io/en/release/topics/resource_owner.html

shows upto "Adding a JavaScriptClient" and then cannot scroll.

And the link:
https://identityserver4.readthedocs.io/en/release/topics/extension_grants.html

shows the full menu content in the left because the content is long and scrollable.

**Comment by Mardoxx** [comment]
What browser are you using, works fine here! The LHS menu is in its own scrollable container -- mouse over it to scroll.

**Comment by satyajit-behera** [comment]
Using Edge and Chrome. Oh! Ok! Not so smooth with laptop touchpad.  I don't use mouse. Thanks.
