### ISSUE TITLE
Can't install "IdentityServer4": "1.0.0-beta3" on ASP.NET Core 1.0 (.NET Framework)

### ISSUE THREAD

**Issue by YannisMarios** [IdentityServer/IdentityServer4#118]
Hi, 

I tried to install 1.0.0-beta3 on ASP.NET Core 1.0 (.NET Framework) and I get the message:

![image](https://cloud.githubusercontent.com/assets/11289298/15814078/c30b01be-2bcc-11e6-99ff-0f44db256e22.png)

Can you please help? Am I doing something wrong?

**Comment by leastprivilege** [comment]
have you tried turning it off and on again?

(aka restart VS)

**Comment by YannisMarios** [comment]
Yes I did, restarted VS 2015, deleted project and created new one but no luck.

I still get the same message. It seems the Nuget won't let me install 1.0.0-beta3.

My PC runs on Win 10 Enterprise (Fully updated) and VS 2015 community (All updates done)

**Comment by xyting** [comment]
first I have the same error, but I go to the dir and run dotnet restore, anything OK

**Comment by YannisMarios** [comment]
@xyting Thanks for the reply,

It did not work for me,

![image](https://cloud.githubusercontent.com/assets/11289298/15814991/b903f99a-2bd2-11e6-824c-dce048fb02d4.png)

**Comment by tonyqq** [comment]
I ran "dotnet restore" from command line and it worked for me.

**Comment by Codelnw** [comment]
@YannisMarios Try this:-

(1) Delete that line.
(2) Save.
(3) Wait for Package Restoration to finish.
(4) Put back that line.
(5) Save.

**Comment by YannisMarios** [comment]
@Codelnw Thanks for the reply,

I have already tried that several times but no luck.

**Comment by YannisMarios** [comment]
Any Ideas?

![image](https://cloud.githubusercontent.com/assets/11289298/15823027/97651876-2c01-11e6-9b27-c9109af51a38.png)

**Comment by Codelnw** [comment]
@YannisMarios I think the cause of this problem is: you named the project as: IdentityServer4 which is the same as package's name of this repo. Try to change the project name to something else.

**Comment by YannisMarios** [comment]
Damn! You must be right! I will try it tommorow. Thanks!

**Comment by YannisMarios** [comment]
@Codelnw  Yes it was my mistake naming the project IdentityServer4....I changed name and it worked.

Thank you.

**Comment by pitthehan** [comment]
@Codelnw You are right, the problem was caused by naming the project IdentiServer4, after I changed the name, it worked.
