### ISSUE TITLE
IdentityServer4 Password Grant Type

### ISSUE THREAD

**Issue by DylanNicolini** [IdentityServer/IdentityServer4#1181]
I am looking to implement Identity server to centralize identity and user authentication as a single micro-service. However, we are supporting multiple web sites / web applications that are single-tenant applications. Ultimately, we want to move towards an oauth 2.0 / open id connect centralized model. However, some of our clients will be bringing their own identity provider and others would be using our IdentityServer4 service as that Identity provider. We are currently looking to implement the password grant type as we do not want to redirect users from their native login page to the identity server's login page. Has anyone ever done anything like this before? Or should we abandon identity server and go for an Asp.Net Identity / custom solution?

**Comment by MrJerB** [comment]
Here are my thoughts:

- If you want to restrict a client to be accessible by a single the tenant, you could have OP return a claim about the tenant this user is meant to belong to and accept/reject the identity at the client side. An other option would be to pass the tenant as an acr_value and set up some validation rules checking the client_id during the auth process.

- Regards your clients bringing their own identity provider, I think this would be once again your client app's responsibility as I cannot understand password grant type being used to obtain an identity from a third party.

I am not speaking from a point expertise so some input on the above would be appreciated for the purposes of my own learning.

**Comment by DylanNicolini** [comment]
I think that passing the tenant during the auth process would be a good step, but I also think each api / micro-service will be responsible for handling it's own rules and permissions for each user / tenant.

With regards to the clients bringing their own identity provider, My thoughts were along the line of a client wanting to using our application, but needing to use Azure AD services / SAML as their identity provider. I do agree that most of this would rely on the client application, but I was curious if we could centralize this to redirect to an identity / authorization to house most of the identity management code within a single service. To then hide the implementation details of Oauth 2.0 / SAML 2.0 / Open ID Connect to a single place. Maybe this can't be done.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
