### ISSUE TITLE
when scope set access_offline access_token is unauthorized

### ISSUE THREAD

**Issue by xubair81** [IdentityServer/IdentityServer4#1184]
step 1:
var mode={
            client_id: "js",
            client_secret: "secret",
             scope: "offline_access",
            grant_type: "password"
        };

i use this model to send requent to identityserver for access token this request return token but when i call api function which have [Authorize] attribute its response is bad [unauthorized]

Step 2
var mode={
            client_id: "js",
            client_secret: "secret",
             scope: "apiName",
            grant_type: "password"
        };
when i use this model in response i do not receive any refresh token but access token is working fine i don't know what to do with this 

expected result     refresh token when access token is expired

here is my client class
public class Clients
    {
        public static IEnumerable<Client> GetClients()
        {
            var clients = new List<Client>();

          
            var websiteGrants = new List<string> { GrantType.ResourceOwnerPassword };
            var secret = new Secret("secret".Sha256());

            var websiteClient = new Client()
            {
                // we will be using Angular JS to access the API - so naming it js
                ClientId = "js",

             
                Enabled = true,

                // just a human friendly name
                ClientName = "JavaScript Client",

               
                AllowedGrantTypes = websiteGrants,

                // secret for authentication
                //TODO: Change the secret to something hard to guess
                ClientSecrets = { secret },

              
                AllowOfflineAccess = true, //Enable refresh token

                // we need to access the fhApi from Angular JS front-end 
                // fhApi is defined in Resources file as an API Resource
                // for refresh tokens we have to add this scope: IdentityServerConstants.StandardScopes.OfflineAccess
                //http://stackoverflow.com/a/31413133/1910735
               
                AllowedScopes = {
                    "obapi",
                    IdentityServerConstants.StandardScopes.OfflineAccess  },

                AccessTokenLifetime = 10 // in seconds - default is 3600 = 1 hour - for testing I have set to 2 mins
            };

            clients.Add(websiteClient);

            return clients;
        }

**Comment by brockallen** [comment]
1: you need to request more scopes than just offline_access -- what API do you need offline access to?
2: offline_access is not compatible with JS implicit clients -- they are not allowed to obtain refresh tokens.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
