### ISSUE TITLE
Question: Running Identity Server 4 in .Net 4.5.2

### ISSUE THREAD

**Issue by AdamRiddick** [IdentityServer/IdentityServer4#1185]
I'm looking to run Identity Server 4 in .Net 4,5,2, as its suggested here; [Identity Server 4 Platforms](https://leastprivilege.com/2017/01/15/platforms-where-you-can-run-identityserver4/).

Is there a sample created that shows Identity Server 4 running in this context?

**Comment by Mardoxx** [comment]
Just change set your target framework to use net452 moniker.

**Comment by AdamRiddick** [comment]
@Mardoxx Thanks for the reply.

To this point I have created a .Net Framework 4.5.2 Library and imported the required Identity Server packages. 

The problem I am facing is trying to get Identity Server 4 running targetting .Net 4.5.2 as a virtual app within IIS without the .Net Code Runtime installed. I can see from the Identity Server 4 codebase that the configuration is done against the `IApplicationBuilder` interface, which is injected into the `WebHostBuilder` startup methods. Is there an alternative method to configure Identity Server 4, or is it bound to the `IApplicationBuilder`, and thus requiring the AspNetCoreModule to run within IIS ?

The reason I'm looking for samples is to discover if it can be used in this context

**Comment by Mardoxx** [comment]
Good question. I was under the impression that ASP.NET Core libraries run under net core and net framework and that `AspNetCoreModule` is only required for net core apps?

**Comment by AdamRiddick** [comment]
That was also my understanding.

I'm struggling with the configuration, which is what spurred me to try and locate a sample of something similar. 

In order to get the `IApplicationBuilder` implementation needed to configure Identity Server 4, i'm using the Startup against the `WebHostBuilder`, which I am configuring using Kestrel. In order to get the startup to fire the .Net Framework 4.5.2 library has an output type of exe, and this is where it is falling over, as without the `AspNetCoreModule` IIS won't manage the process.

I may be going about this in the wrong way, so any assistance is appreciated.

**Comment by leastprivilege** [comment]
https://docs.microsoft.com/en-us/aspnet/core/publishing/iis

**Comment by Mardoxx** [comment]
Is this necessary even if you are targeting net framework?

**Comment by leastprivilege** [comment]
What is necessary?

The deployment model of asp.net core is slightly different compared to asp.net.old. It always uses Kestrel and the aspnet core module for IIS - regardless which target runtime is used.

**Comment by Mardoxx** [comment]
Ahh thanks, that answers my question then!

**Comment by joehoeller** [comment]
Can I use IDServer4 + .NET 4.5 to connect to ADFS?

**Comment by leastprivilege** [comment]
IS4 requires .NET 4.6.1 or .NET Core 2.0
