### ISSUE TITLE
How to reject Registration and Logins if request is not made from a client

### ISSUE THREAD

**Issue by Ponant** [IdentityServer/IdentityServer4#1189]
In the scenario where IS4 is on myidentityserver.com and an MVC client on mvcclient.com, the current quickstart allows anyone to go **directly**  to myidentityserver.com and register as a user, without coming from the MVC client. Is there a way to forbid registration/authentication if the user does not access IS4 from the MVC client?

**Comment by leastprivilege** [comment]
It's a normal MVC app at this point. 

If the request comes via the OIDC endpoint - there must be a valid authorize URL on the returnUrl parameter - you could check for that.
