### ISSUE TITLE
Remove reference token from existing Cache

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1190]
We can set the duration cache for a reference token.
When we revoke the reference token, is it possible to remove the token from the cache also?

Otherwise, it will be available even after revoking the token till the cache duration ends.

**Comment by brockallen** [comment]
IIRC we don't cache the grants. What cache are you using?

**Comment by satyajit-behera** [comment]
Thanks. I noticed this in the Resource project (API). The API retain the reference token for 10 mins by default, even after its revoked. Hence the reference token works for that time span.

**Comment by brockallen** [comment]
Yea, that's the trade off for caching vs. hitting introspection on each use of the access token. Not much I can do to help you there. You will have to decide for your scenario which works better.

**Comment by satyajit-behera** [comment]
Thanks. But is there any method that can help me remove a cache by its key?

**Comment by brockallen** [comment]
We use the built-in cache: https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/dev/src/IdentityModel.AspNetCore.OAuth2Introspection/OAuth2IntrospectionHandler.cs#L22

So you could use this and remove the token manually -- the token itself is the key.

**Comment by satyajit-behera** [comment]
Thanks a lot
