### ISSUE TITLE
Identity.Application.session cookie

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4#1193]
Hi,

Is "Identity.Application.session" a cookie created by IdentityServer4? If so is there an option to set it to httponly?

**Comment by leastprivilege** [comment]
It needs to be accessible by JavaScript.

https://openid.net/specs/openid-connect-session-1_0.html#ChangeNotification

**Comment by pzelnip** [comment]
How does one protect against CSRF then?  If my SPA gets a non-httponly cookie with the JWT, wouldn't it then be vulnerable to a CSRF attack?
