### ISSUE TITLE
Setting token lifetime for different grant types in identityserver4

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1195]
Is it possible to set the token lifetime for different grant types in identityserver4.

Example: Can I can set lifetime with **password** grant to 20 mins and set lifetime with **my extension** grant to 10 mins?

**Comment by brockallen** [comment]
Yes, you can dynamically change the `AccessTokenLifetime` on the `ValidatedRequest` during your custom request processing logic.
