### ISSUE TITLE
Error Handling per the spec?

### ISSUE THREAD

**Issue by agilenut** [IdentityServer/IdentityServer4#1196]
We are implementing Identity Server 4 and I'm wondering if the way Identity Server 4 handles errors is correct per the Open ID Connect / Oauth 2.0 specification. 

Section [3.2.2.6](https://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthError) of the Core spec states that errors for the Authorize endpoint should be handled in the following manner:

>When using the Implicit Flow, Authorization Error Responses are made in the same manner as for the Authorization Code Flow, as defined in Section 3.1.2.6, with the exception of the differences specified in this section.

The referenced section, [3.1.2.6](https://openid.net/specs/openid-connect-core-1_0.html#AuthError), states: 

>If the End-User denies the request or the End-User authentication fails, the OP (Authorization Server) informs the RP (Client) by using the Error Response parameters defined in Section 4.1.2.1 of OAuth 2.0 [RFC6749]. (HTTP errors unrelated to RFC 6749 are returned to the User Agent using the appropriate HTTP status code.)

>Unless the Redirection URI is invalid, the Authorization Server returns the Client to the Redirection URI specified in the Authorization Request with the appropriate error and state parameters. Other parameters SHOULD NOT be returned.

Section [4.1.2.1](https://tools.ietf.org/html/rfc6749#section-4.2.1) of the OAuth 2.0 spec states:
>If the request fails due to a missing, invalid, or mismatching
   redirection URI, or if the client identifier is missing or invalid,
   the authorization server SHOULD inform the resource owner of the
   error and MUST NOT automatically redirect the user-agent to the
   invalid redirection URI.

>If the resource owner denies the access request or if the request
   fails for reasons other than a missing or invalid redirection URI,
   the authorization server informs the client by adding the following
   parameters to the fragment component of the redirection URI using the
   "application/x-www-form-urlencoded" format.

It goes on to say that the error parameter to be sent to the client includes things such as missing required parameters, invalid scopes, etc. 

Identity Server seems to take the approach of issuing a 302 redirect to an error endpoint with an errorId parameter. It seems to do this for any type of error regardless of whether it is an invalid redirection URI or invalid scope. But the spec seems to imply that these should be handled differently. 

As an example, both of these calls result in a 302 redirect to the error page:

```
GET /connect/authorize?client_id=validclient&scope=validscope&redirect_uri=http%3A%2F%2FINVALIDREDIRECTURI&response_type=token&state=abc&nonce=xyz

GET /connect/authorize?client_id=validclient&scope=INVALIDSCOPE&redirect_uri=http%3A%2F%2Fvalidredirecturi&response_type=token&state=abc&nonce=xyz
```
Based on my understanding of the specs, the 302 redirect for the invalid redirect URI (first example) is a valid implementation to inform the user (not the client). 

But the second example which includes an invalid scope should redirect to the redirect URI instead of the error page so that the client is informed (not the user). 

I don't consider myself to be an expert with regard to these specs. So, I'm sure I'm missing something. Could you please enlighten me if and how the current error handling mechanism is compliant with the Open ID Connect specification?

Thanks in advance!

**Comment by brockallen** [comment]
There are attacks on the original spec redirect guidelines, so we implement the additional protection features described here: https://tools.ietf.org/html/draft-ietf-oauth-closing-redirectors-00

**Comment by agilenut** [comment]
Thanks for the response. I figured it was something like that.
