### ISSUE TITLE
Chome Plugin and Implicit Grant Flow

### ISSUE THREAD

**Issue by antonfelich** [IdentityServer/IdentityServer4#1197]
We are looking at an edge case where we want to publish a Chrome Plugin that uses our IdentityServer4 implementation for authentication.

As the code will reside on the end users machine a client secret needs to be protected (or in this case not used at all) so I believe the correct flow is the implicit grant flow. 

To avoid an access token being out in the wild for too long we want short lived 5 minute tokens. But to ensure a smooth user experience will would like to issue a 30 day session (and a 30 day cookie with the identity token in it) so they can return for more access tokens when needed without having to login again. Obviously for security, should for some reason we cancel their account then the session will be terminated in the DB and no more access tokens can be requested.

ISessionIdService has been extended to allow us to store the session details in the DB and provide a mechanism for terminating them when required. Probably also worth a mention that the session slides with each request to keep it at 30 days. 

Now as I said this is an edge case. Our client base is already unhappy with us having a session length of 2 hours, so extending it to 30 days would cause mayhem. What we ideally need to do is vary our session length based on the incoming client_id to connect/authorize/ Chrome plugins have their own sandbox for sessions/cookies so it would be isolated from our normal site access. But doing that "feels" wrong, should a session on the IdentityServer really be tied to a specific client? I wouldn't think so... 

Has anybody else come across this sort of scenario? How have you handled it? Any suggestions would be extremely appreciated.

**Comment by brockallen** [comment]
I'd say that a browser plugin in falls into the native client category, so you should use hybrid+PKCE. This sample from Google shows how to do that with a JS-based native app: https://github.com/openid/AppAuth-JS

**Comment by antonfelich** [comment]
That was exactly what I wanted, thanks Brock much appreciated. I'm also in the process of putting together a blog post on how the Hybrid+PCKE flow works in case anybody else gets stuck.

**Comment by ghanashyaml** [comment]
@antonfelich , can you please add your blog post URL here for benefit of others? Thanks!
