### ISSUE TITLE
Error relating AuthenticationOptions class when using from netcore 2

### ISSUE THREAD

**Issue by eiximenis** [IdentityServer/IdentityServer4#1198]
Hi,
I started testing the use of IdSvr4 under a netcore 2.0.

I had a netcoreapp1.0 using IdentityServer4.AccessTokenValidation@1.2.0
Everything was OK.

To test I updated my csproj to target netcoreapp2,0 and reference the new meta-package "Microsoft.AspNetCore.All@2.0.0-preview1-final". Of course package "IdentityServer4.AccessTokenValidation@1.2.0" is still references"

No source code changes are made.

1. A dotnet restore works OK
2. A dotnet build fails with  error CS7069: Reference to type 'AuthenticationOptions' claims it is defined in 'Microsoft.AspNetCore.Authentication', but it could not be found 

The problem is due that in Microsoft.AspNetCore.Authentication@2.x the class "AuthenticationOptions" no longer exists.

**Comment by brockallen** [comment]
We don't support ASP.NET Core 2 yet. We will tho: https://github.com/IdentityServer/IdentityServer4/issues/1055

**Comment by Charleslekgoathi** [comment]
Has this been added to  ASP.NET Core 2 yet?

**Comment by Andree643** [comment]
Do you support the ASP.NET Core 2 now? I'm still getting this message.

**Comment by brockallen** [comment]
What makes you say that?
