### ISSUE TITLE
Consent is not saved to IPersistedGrantStore

### ISSUE THREAD

**Issue by hikalkan** [IdentityServer/IdentityServer4#1199]
I'm using ``AddInMemoryPersistedGrants`` as in the samples. Remembering Consent is not working. It's asking consent every time. As I understand, InMemory persistent grant should remember consents until application shutdown (since it's singleton). 

It can be reproduced with Quickstart6_AspNetIdentity sample (https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/6_AspNetIdentity).

I have investigated IdentityServer4 source code but could not find where it uses ``IPersistedGrantStore`` when we call ``IIdentityServerInteractionService.GrantConsentAsync`` method.

**Comment by brockallen** [comment]
If you ask for offline_access, the spec says to prompt each time, so we do.

https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

**Comment by hikalkan** [comment]
It was like that. I will try without offline access too. Thank you for the information. I will close issue if removing offline access makes it work.

**Comment by hikalkan** [comment]
It works as expected. Thanks a lot.
