### ISSUE TITLE
Checksession resource not available in IdentityServer4.Sample IdSvrHost

### ISSUE THREAD

**Issue by realavaloro** [IdentityServer/IdentityServer4#12]
I am playing witht he samples and I see that in one of the clients from IdentityServer3, the oidc in javascript, there is something sending GET requests to:
```http://localhost:22530/connect/checksession``` (the IdSvrHost)
but in the IdSvrHost from IdentityServer4.Samples there is nothing with this endpoint.

Is that something required? I apologize if this is not an issue, but I haven't been able to find any documentation about IdentityServer4 with implicit flows and I still don't fully understand what's necessary to store tokens in client side.

**Comment by leastprivilege** [comment]
session management is not implemented yet.

**Comment by realavaloro** [comment]
Thank you.
It'd be great if you could include some tips on good practices in client side when retrieving/storing tokens.
As far as I understood it's better to treat the access token (JWT) as a password, hence if stored in client side better to do so in a cookie rather than in local storage.

But is it a better practice to retrieve silently the token from the IdSvrHost? I guess that would require storing username/password for the browser session in client-side and/or allowing the user to remember it in case the user closes the browser.

In that case would a refresh-token be necessary at all? If sending username/password silently before the current token expires (assuming the token is stored in an app variable, not persisted) then there wouldn't be any need to refresh the token, would it?

These are the kind of questions I have at the moment. I'd appreciate any link or advice on what's best. Thank you!

**Comment by leastprivilege** [comment]
This is an issue tracker - can we please focus on the issue in the title ;)

SO is a great place to ask general purpose questions that are not directly related to idsrv.
