### ISSUE TITLE
login from the database Identityserver4

### ISSUE THREAD

**Issue by andreslon** [IdentityServer/IdentityServer4#120]
How can I login from the database Identityserver4 earlier in identityserver3 with the customer IUserService reached the breakpoint, but with the version v4 never reaches the GetProfileDataAsync method , the client always returns "Internal Server Error"

![image](https://cloud.githubusercontent.com/assets/2242679/15845888/0b0949ec-2c3d-11e6-8b14-d6e5d9bcc1d8.png)

**Comment by leastprivilege** [comment]
We'd need more details - check the logs.

**Comment by andreslon** [comment]
I have not any .log error, because it is not an exception.
I need to authenticate with the database.

Adding users in memory works:
![image](https://cloud.githubusercontent.com/assets/2242679/15993958/8edec6a2-30bb-11e6-865b-182bc44e69f2.png)

But I can not have static users, as they can change their data.
And it does not work:
![image](https://cloud.githubusercontent.com/assets/2242679/15993960/9c73a634-30bb-11e6-9fca-dea77105b35d.png)

I need my client's call enters the method GetProfileDataAsync:
![image](https://cloud.githubusercontent.com/assets/2242679/15993968/dd240eb2-30bb-11e6-90c0-c1db65e986b7.png)

**Comment by brockallen** [comment]
You need to understand the sampe host and how it related to IdSvr4. Here's a sample that has taken the sample host and applied ASP.NET Identity 3 to it: https://github.com/tibold/IdentityServer4.Contrib.AspNetIdentity
