### ISSUE TITLE
HTTP Error 400. The size of the request headers is too long.

### ISSUE THREAD

**Issue by senafees** [IdentityServer/IdentityServer4#1201]
I am using IdentityServer4 for SSO purpose. When a user logged in from a browser successfully and then tries to login from other browser then it throws error (Bad Request - Request Too Long). Strange behavior.
Anybody guide me where am I doing wrong.

**Comment by Mardoxx** [comment]
Are you running behind a proxy (nginx e.g.)

**Comment by sr-h** [comment]
I'm having the same issue. I notice that the number of idsrv session cookies grows on each login. So If all I do is login and logout multiple times, this will end up in me hitting that 400 Error with request header too long. Is this a possible booboo on my end or is this a known issue of some sort? Increasing acceptable header length is not a "fix", that is just moving the problem further down the road. :)

**Comment by sr-h** [comment]
This maybe is a Chrome issue for me. I just found out that Firefox doesn't store these cookies on each login/logout but Chrome does. I changed the setting in chrome where it says "Continue where you left off" when relaunching Chrome to "Open the new tab page" and on next browser close the cookies are all cleared. Before, having already logged out and closed the tab using the service that talks to IDsrv, made no difference - Having "continue where you left off" set is what causes this no matter what.

Welp, that sucks.

**Comment by Mardoxx** [comment]
>I notice that the number of idsrv session cookies grows on each login

Might be worth looking in to

**Comment by brockallen** [comment]
If a user does things in Chrome to affect cookies as set by the server, then there's not much I can do to help. I've heard of this setting in chrome -- it also stores cookies on disk even tho the cookie is set as a session cookie (for example if you hibernate/shutdown the OS).

Other than that, it's possible that you're getting not authentication cookies, but OIDC middleware cookies piling up from the client app. If the signin handshake is not completed, then it's possible that nonce cookies are not cleaned up.

**Comment by sr-h** [comment]
Yeah I'm aware theres not much you can do about this being a Chrome issue :D My problem is most people I know use the 'Continue where you left off' setting :(
All I know right now is the cookies are called idsrv.ClientSessions.XXXX... but we'll continue looking into it.
Should IdentityServer destroy these cookies (right now, by design) when the user logs out or is it relying on the browser to do its normal cleanup? Just wondering where to focus my attention on this.

**Comment by brockallen** [comment]
> idsrv.ClientSessions.XXXX

Those don't look like authentication cookies -- those look like cookies that are issued to do single signout. Are you letting the "logged out" page render, or are you navigating away from it immediately?

**Comment by sr-h** [comment]
We redirect away from it, maybe it doesn't fully render before redirecting. Is that the problem?

**Comment by brockallen** [comment]
Yes. You need to let it render so all the iframes can complete.

**Comment by brockallen** [comment]
> You beautiful specimen

Uhh, thanks?

**Comment by tomek14** [comment]
@siggirh can you give more brief background on this? How you solve it ? Becouse I'am facing the same problem

**Comment by siggirh** [comment]
Our problem was when the user logged out we had a javascript redirect in the logout page where we redirected to our official landing page as soon as the redirect page started loading. We just needed to let the logout page finish rendering (so the iframes load properly and do their thing) and then redirect on a delayed timer.
