### ISSUE TITLE
Question: Long Term Support (LTS) for Identity Server

### ISSUE THREAD

**Issue by scottblasingame** [IdentityServer/IdentityServer4#1205]
My company has operational guidelines to only allow LTS (i.e. 1.0.x) versions of software on our servers. With .NET Core that brings up an issue with IdentityServer4, as it appears it is using the the current branch versions (i.e. 1.1.x) of .NET Core assemblies.

I'm not expecting you to change anything in your project, but I am wondering if you have any thoughts or suggestions for us (aside from convincing Ops to relax the standard in this case, which I am currently trying to do).

**Comment by leastprivilege** [comment]
Well - then they probably need to wait for 2.x

**Comment by scottblasingame** [comment]
So you're saying that 2.x of IdentityServer will target a LTS version of Core (like 2.0.x)? Here's a good read from another maintainer on this subject: https://andrewlock.net/supporting-both-lts-and-current-releases-for-asp-net-core/

**Comment by brockallen** [comment]
The reason we don't currently support LTS of .NET Core is because Microsoft added breaking changes in 1.1.x, and it made it impossible for us to have one version that worked in both versions.

**Comment by leastprivilege** [comment]
We will have IdentityServer4 v2 target aspnet core v2 (until MS breaks stuff again in 2.1 - but that's another story).
