### ISSUE TITLE
ExtensionGrants : Use custom logic to return same output token (jwt/reference) as connect/token

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1208]
I am using Extension Grants to extend my authentication logic. The example code works fine.

I want to customize the authentication logic with some additional parameters But want to use the same logic to return token as in the case of connect/token with all the logic for jwt/reference/refresh token as it is.

Please indicate the methods available and needed to do the same assuming user authentication is done and I have a user object available with me.

**Comment by leastprivilege** [comment]
There is no easy way to do this right now - the token response generator re-design we did for 2.0 might help here. Fee free to have a look and open a more specific issue.
