### ISSUE TITLE
identity server 4 and facebook authorization

### ISSUE THREAD

**Issue by lmaraneli** [IdentityServer/IdentityServer4#1209]
Hello,

I need to make backend API with multiple device support and built in identity server for authentication.

I have used local users with passwords and it works fine.
but when mobile clients submit facebook access token to api, I can't generate local access token,
because I don't have passwords for extenran users and can't use 'RequestResourceOwnerPasswordAsync'
method.

can you suggest me any valid solution? is it possible without cookies and how to do it?

thank you

**Comment by leastprivilege** [comment]
You need to switch to an interactive flow.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
