### ISSUE TITLE
Question on how to restric api resource access on User level

### ISSUE THREAD

**Issue by YannisMarios** [IdentityServer/IdentityServer4#121]
Hello,

How can I restrict different access levels to resources for different users that use the same client.

For example we are building a channel manager for hotel owners/administrators.

Here in Greece there are companies that manage several hotels each.

Suppose you are the manager of the company that manages 10 hotels.

You want to use a web application to view and manage your hotels. As a manager you want to have access to all of the 10 hotels settings (e.g add remove rooms, prices, offers etc).

Then you decide that one of your employees will manage only 3 of the 10 hotels and another one the remaining 7.

so employee 1 has access to api/hotels/1, api/hotels/2, api/hotels/3
and the other one to the other 7...

How do I accomplish this?

Will Roles do the job?...I don't see how.

**Comment by Junicus** [comment]
I have a similar issue.  Here is my version of this: 

I have multiple restaurants, each restaurant belongs to a stablished region.
I have region managers that manage those restaurants.

I solved it by giving a claim to the region managers that goes in the scope for the api.  In the api I setup a custom authorization handler that looks at that receives the resource (in my case a restaurant) and the claim, and it checks if the restaurant is in that region.

I watched https://blogs.msdn.microsoft.com/webdev/2016/03/15/get-started-with-asp-net-core-authorization-part-1-of-2/ and https://blogs.msdn.microsoft.com/webdev/2016/03/23/get-started-with-asp-net-core-authorization-part-2-of-2/

In the video they talk about a repo with samples for that https://github.com/blowdart/AspNetAuthorizationWorkshop/tree/master/src/Step_7_Resource_Based_Requirements

Hope it helps

**Comment by YannisMarios** [comment]
Thank you,

I will look at them and I also hope I will find a solution to this problem.

**Comment by YannisMarios** [comment]
Actually could you be more specific and provide a more concrete example with classes and startup?

Thank you

**Comment by brockallen** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.

**Comment by Junicus** [comment]
Maybe this could help [hotel authorization gist](https://gist.github.com/Junicus/ec1312ec4ea89047081146541d2be964) it's very basic but it should help you get in the right direction

**Comment by YannisMarios** [comment]
Thank you.

I may be wrong but in your solution you are relating the Hotel to the User
correct?

I mean that your Hotel has some sort of list of "alllowed" users?

if(resource.ManagerId == context.User.FindFirst("SomeID").Value)
