### ISSUE TITLE
Normal quickstart of HybridFlowAuthenticationWithApiAccess

### ISSUE THREAD

**Issue by RepositoryNY** [IdentityServer/IdentityServer4#1210]
Could you please provide an example of HybridFlowAuthenticationWithApiAccess? Because, it seems that [HybridFlowAuthenticationWithApiAccess](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/5_HybridFlowAuthenticationWithApiAccess) is corrupted, it is absolutely the same as the previous [ImplicitFlowAuthenticationWithExternal](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/4_ImplicitFlowAuthenticationWithExternal)

**Comment by leastprivilege** [comment]
The quickstart is fine - it i using hybrid:

https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/5_HybridFlowAuthenticationWithApiAccess/src/MvcClient/Startup.cs#L62

**Comment by RepositoryNY** [comment]
In client, but how about server configuration example like in [this tutorial]? (https://identityserver4.readthedocs.io/en/release/quickstarts/5_hybrid_and_api_access.html) It has too much questions, when using internal IdentityServer client, instead of examples with sending pure requests, e.g. in Postman, whatever.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
