### ISSUE TITLE
Authorize Resource APIs written in PHP, Node.js and Ruby On Rails (with Reference Token)

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1211]
I have a situation where I have some Resource APIs written in PHP, Node.js and Ruby On Rails.

Then came across this reference:
https://github.com/IdentityServer/IdentityServer4/issues/1029

Adding to the answer in the question mentioned above, if I choose reference token for a Client, is it possible to write authorizing a php, node.js or ruby on rails Resource using the REFERENCE TOKEN.

If possible, any reference available?

Thanks

**Comment by leastprivilege** [comment]
You can validate reference tokens using introspection

https://tools.ietf.org/html/rfc7662

Don't know if any libraries exist for your platform though (but is easy to implement).
