### ISSUE TITLE
Extend Client information

### ISSUE THREAD

**Issue by rajarameshvarma** [IdentityServer/IdentityServer4#1214]
I would like to add additional metadata information about the "Client". Is there a way to extend Client class or do I need to write my own service for this metadata separately and DI into the identityserver host?

**Comment by leastprivilege** [comment]
You can derive from Client and downcast in your own code.

**Comment by rajarameshvarma** [comment]
I am using IdentitServer4.EntityFramework to persist the data in SQL Server. I have to persist the metadata too.  how can I extent ClientStore to get this metadata? FindClientByIdAsync returns a "Client".

**Comment by leastprivilege** [comment]
You need to extend the EF layer to return a derived client type.

**Comment by brockallen** [comment]
Either extend, or define a new custom repo for this metadata that knows how to load from your custom tables and inject it into the places you need it.

**Comment by rajarameshvarma** [comment]
Thank you
