### ISSUE TITLE
connect/checksession API not returning changed event in iframe 

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#1215]
I'm testing the connect/checksession API as described here:

http://openid.net/specs/openid-connect-session-1_0.html

Even though my id_token and access_token have expired, the check_session iframe API always returns an unchanged event. 

MessageEvent {isTrusted: true, data: "unchanged", origin: "https://localhost:44318", lastEventId: "", ...

IdentityServer4 : 1.5.1

**Comment by leastprivilege** [comment]
token lifetimes are unrelated. 

This checks the authentication session - IOW if the user has a valid cookie with idsrv

**Comment by damienbod** [comment]
So I need to configure IdentityServer4 to create a cookie when the user logins in using the OpenID Implicit Flow and set the lifetime of this cookie to a value smaller than the lifespan of the id_token

**Comment by leastprivilege** [comment]
The cookie always gets created - that's the "SSO session" with identityserver.

id_token lifetime is not important - id tokens are just the signed protocol response (only used to validate the authentication event and for a hint at logout time).

**Comment by damienbod** [comment]
Any examples how I can configure the SSO session with identityserver4?

**Comment by leastprivilege** [comment]
Basic settings like lifetime and sliding vs absolute can be configured on the options in ConfigureServices.

If you need more control, provide your own cookie middleware and tell us the name of it (also on the options)
