### ISSUE TITLE
Question: is it possible to get issuer details from claims

### ISSUE THREAD

**Issue by AndreSteenbergen** [IdentityServer/IdentityServer4#1218]
I have a working setup, with multiple social logins provided. I can successfully link these logins to my account, but because most providers provide with name and surname and other claims I end up with claims provided by multiple issuers.

Is it possible to get claims including the issuer? Or is there another endpoint to get userinfo including issuers for the claims?

for example I have this response from the userinfo endpoint
```
{
  "sid": "11968265d1b341716d268c06acc9f4d9",
  "sub": "b7c78b67-fe45-4793-82b7-93b9544df379",
  "auth_time": 1496234621,
  "idp": "Google",
  "amr": [
    "external"
  ],
  "ProfileImage": [
    "https://lh5.googleusercontent.com/-iPLOMpfomRs/AAAAAAAAAAI/AAAAAAAACoE/s9h7_mdxHyc/photo.jpg?sz=400",
    "http://pbs.twimg.com/profile_images/827132969550770176/ApBjFIQx_400x400.jpg"
  ],
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": "André",
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": [
    "André Steenbergen",
    "CalqoDev"
  ],
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname": "Steenbergen"
}
```

**Comment by leastprivilege** [comment]
And do you really want the multiple claims from multiple issuers in your client applications?

**Comment by AndreSteenbergen** [comment]
You are correct I don't need all claims in my client.

At this moment for now I am designing an accounts page with this data,
managing (standard route in the identityserver4 example (/manage)) user social logins, I show the social login, including the name, and profileImage from that provider. Using the claims with issuer, that's the reason why I store the claims. But I don't need them all in userinfo.

I would love to see a way to filter the claim, getting only the claims from the api resource, and the claims where the identityresource claims are equal to that of the idp. If that's not possible out of the box, not a problem. I can write my own endpoint.

**Comment by AndreSteenbergen** [comment]
Line 185 (/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/Core.cs)
`builder.Services.TryAddTransient<IUserInfoResponseGenerator, UserInfoResponseGenerator>();`

I guess I will make my own implementation of `IUserInfoResponseGenerator` (based on UserInfoResponseGenerator). That would work right?

**Comment by leastprivilege** [comment]
You can control which claims are returned in the token by implementing `IProfileService` - and yes you can override our userinfo response generator as well.

**Comment by AndreSteenbergen** [comment]
Thanks for the update about IProfileService. I already have one added to DI, because of `.AddAspNetIdentity<ApplicationUser>();` I think the implementing IprofileService is more elegant then the responsegenerator, do I call builder.AddProfileService after AddAspNetIdentity?
