### ISSUE TITLE
Add Clients in Identity Server 4 at runtime or dynamically

### ISSUE THREAD

**Issue by ypatil25489** [IdentityServer/IdentityServer4#1219]
I am using IdentityServer4.EntityFramework. I want to add clients at run time I mean after deployment user should able to add client to DB and those clients should be functional after adding into the database.

Any option availble so that I can dynamically add clients in IdentityServer4.

**Comment by brockallen** [comment]
The EF library loads from the database. Is that not what you want?

**Comment by AndreSteenbergen** [comment]
IdentityServer4 interfaces only tell the developer to build getters (see `IClientStore`, `IResourceStore`). If you want to create your own GUI, you would have to create your own interfaces. That way you can create clients, resources etc yourself. Or find a nuget package providing an administration module for IdentityServer. Have a look at PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore they add possibility to do CRUD ... there is a warning in the readme though ....
