### ISSUE TITLE
Defining API Resource at controller level

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1221]
The documentation shows how to configure the API Resource at an application as scope at startup.

![image](https://cloud.githubusercontent.com/assets/10031739/26639785/63751586-4643-11e7-8552-14306f899029.png)

Can we define the resources at controller or action as scope.

I have a situation where an web api application contains many controllers.
And I want to restrict the scope to specific controllers and actions instead of defining the resource once per application startup.

Is it possible? Are there any other solution for this type of scenarios.

**Comment by leastprivilege** [comment]
You can check the scope claims at the controller/action level. Either manually or using the new authZ policy feature in asp.net core.

**Comment by satyajit-behera** [comment]
@leastprivilege Thanks.

**Comment by JanBN** [comment]
Could you please show piece of code how ? Thank you
