### ISSUE TITLE
Additional parameters for external logins

### ISSUE THREAD

**Issue by uringeller** [IdentityServer/IdentityServer4#1222]
Hi @leastprivilege ! 
I'm trying to pass an acr_values parameter to an external provider, but can't figure out how to affect the request. Got any pointers?

**Comment by leastprivilege** [comment]
Hey

not sure I follow. 

You want to set an acr_value for an external provider from within IS?

**Comment by uringeller** [comment]
Yes, actually a mapping from an incoming acr_value..

**Comment by leastprivilege** [comment]
Can't remember the best way right now -

try

* setting the value on `HttpContext.Items` - and read it from there in the `OnRedirectingToIdentityProvider` event on the middleware.
* putting it into the `AuthenticationProperties` and passing those into the call to `ChallengeAsync`

**Comment by uringeller** [comment]
Perfect, thanks!

**Comment by leastprivilege** [comment]
Which one worked for you?

**Comment by uringeller** [comment]
The most obvious one of course :) 
HttpContext and OnRedirectToIdentityProvider..

**Comment by uringeller** [comment]
`Events = new OpenIdConnectEvents()
                {
                    
                    OnRedirectToIdentityProvider = r =>
                    {
                        if (r.HttpContext.Items.ContainsKey(OidcConstants.AuthorizeRequest.AcrValues))
                        {
                            var acrValues = r.HttpContext.Items[OidcConstants.AuthorizeRequest.AcrValues].ToString();
                            r.ProtocolMessage.AcrValues = acrValues;
                        }
                        return Task.FromResult(0);
                    }
                }`
