### ISSUE TITLE
Question on Windows Authentication

### ISSUE THREAD

**Issue by RaviTejaKaruturi** [IdentityServer/IdentityServer4#1226]
Hi,
In the docs related to windows Authentication (http://docs.identityserver.io/en/release/topics/windows.html) its mentioned that
_Also the virtual directory in IIS (or IIS Express) must have Windows and anonymous authentication enabled_
Why do we need to turn on anonymous authentication as well?

**Comment by leastprivilege** [comment]
Because some requests are anonymous (or start anonymous) - e.g. discovery or authorize
