### ISSUE TITLE
Ramon

### ISSUE THREAD

**Issue by ramonTC** [IdentityServer/IdentityServer4#1227]
Hello,

We are having problems when starting identity server 4 on asp.net core.

We have the configuration set to persist  store in entity framework but logs says that we still are using In-memory persistent grant:

2017-06-02T14:56:39.844714300Z info: IdentityServer4.Startup[0]
2017-06-02T14:56:39.844755400Z       You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.

Here's the config we actually have set in startup.cs:

In ConfigureServices method:
public void ConfigureServices(IServiceCollection services)
        {            
            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

// Adds IdentityServer
            services.AddIdentityServer(x => x.IssuerUri = "null")
                .AddSigningCredential(Certificate.Get())
                .AddInMemoryApiResources(Config.GetApis())
                .AddInMemoryIdentityResources(Config.GetResources())
                .AddInMemoryClients(Config.GetClients(clientUrls))
                .AddAspNetIdentity<ApplicationUser>()
                .Services.AddTransient<IProfileService, ProfileService>(); 
...

In Configure method:

 public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseIdentity();
            app.UseIdentityServer();
...

Is there some configuration missing?

Thanks.

**Comment by Mardoxx** [comment]
>We have the configuration set to persist store in entity framework

I can't see where you are registering `IPersistedGrantStore`

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
