### ISSUE TITLE
Allow PKCE on demand (without explicit configuration)

### ISSUE THREAD

**Issue by bungle** [IdentityServer/IdentityServer4#1228]
I would like to know if there is a specific reason that PKCE causes `400` error on token endpoint with  [demo.identityserver.io](https://demo.identityserver.io/) when using `grant_type`: `authorization_code` and `client_id`: `server.code`. and `client_secret`: `secret` with PKCE codes supplied.

I know that this page: [demo.identityserver.io](https://demo.identityserver.io/) says no particular thing about PKCE on `server.code`, but does it hurt to have PKCE enabled if the client specifically requests it? For example with `Okta` and `Google` it just works.

Is this a possible limitation in IdentityServer4 (or with demo environment, e.g. is this configurable)? Or just something that I don't understand (e.g. `beginner`).

What I mean that it is easier to build a secure client when the client can lookup for `code_challenge_methods_supported` and if it is supported, then also add PKCE.

**Comment by bungle** [comment]
Ok, it looks like the `limitation` is here:
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/TokenRequestValidator.cs#L286-L290

I think it would be better if you enable it dynamically based on client request.

**Comment by leastprivilege** [comment]
If the client thinks it is doing pkce, but the server ignores it, the client should know about it.

**Comment by bungle** [comment]
Of course, but why doesn't the server enable PKCE when client requests it is the main question. I see no reason for server to ignore it if the server specifically announces that it supports it in `code_challenge_methods_supported`.

**Comment by leastprivilege** [comment]
I can see your point - we will discuss this.

**Comment by leastprivilege** [comment]
done on dev.

**Comment by bungle** [comment]
@leastprivilege thanks, LGTM!
