### ISSUE TITLE
Localize errors 

### ISSUE THREAD

**Issue by sergeu90** [IdentityServer/IdentityServer4#1231]
Hi.I want to ask. How сan do I localize your errors?

**Comment by apacherose** [comment]
Maybe the easiest approach is to set the properties of the RequiredAttribute, which is used in the Quickstarts, for example part of the LoginInputModel type would look like:
`[Required(ErrorMessageResourceName = "ResourceKeyName", ErrorMessageResourceType = typeof(Resources))]
public string Username { get; set; }`

where the `Resources` type is just a *.resx resource class in your library.

**Comment by Robban1980** [comment]
The easiest way is to check how to do localization in AspNet Core MVC here  https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization

**Comment by saeidehv** [comment]
Hello
I need to localize the error messages from UserManger like : "email is already taken from _userManager.SetEmailAsync(user, Input.Email).
Does Identity Server 4 support localization?

**Comment by Robban1980** [comment]
@saeidehv it is not IdentityServer4 you want to localize, but what ever is presenting the error to a user. Check the link above on how localization works in .Net Core and you can use that as a starting point.
