### ISSUE TITLE
no .NET Framework support for ASP.NET Core 2.0

### ISSUE THREAD

**Issue by MNTLM** [IdentityServer/IdentityServer4#1232]
Hi,

we are thinking about the usage of IdentityServer4 for a .Net Framework 4.x 
web application (Front-End: AngularJS, Bootstrap; Back-End: C#/F#, WCF, Web API, NHibernate, MS SQL Server).

Will the "no .NET Framework support for ASP.NET Core 2.0" decision be a problem for our purpose?

Thanks 
Marco

**Comment by totht91** [comment]
.NET Framework will be supported in ASP.NET Core 2.0 RTM. It's just a temporary issue in the preview builds.
