### ISSUE TITLE
Change DefaultGrantStore.GetHashedKey to virtual

### ISSUE THREAD

**Issue by enemaerke** [IdentityServer/IdentityServer4#1235]
We are migrating an existing IdentityServer3 solution to IdentityServer4. During this migration, we've identified that the hashed keys for e.g. reference tokens, which are used for lookups, have changed from IdSrv3 to IdSrv4, namely that they are now postfixing the type before being hashed, thus breaking backwards compatibility. To ease the burden of porting this (i.e. not having to fully implement the IReferenceTokenStore), I propose to make the DefaultGrantStore.GetHashedKey virtual to allow for a simple derived class of DefaultReferenceToken to just override this method to assist in backwards compatibility. 

The line in question is [here](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Stores/Default/DefaultGrantStore.cs#L58)

Thoughts?

**Comment by brockallen** [comment]
Maybe it's be better if all the methods were virtual?

**Comment by enemaerke** [comment]
Hi @brockallen. Sure, that would perhaps be beneficial as well. For my specific issue, it was the GetHashedKey method that I needed to override for backwards compatibility purposes.

**Comment by brockallen** [comment]
Done. Have a look and let us know, please.

**Comment by enemaerke** [comment]
That looks perfect, thanks for taking the time @brockallen and for providing a cool framework to build on top off. Feel free to close this issue.
