### ISSUE TITLE
Preview release for Core 2.0?

### ISSUE THREAD

**Issue by spudcud** [IdentityServer/IdentityServer4#1236]
I have seen the 2.0 milestone (~50% complete) and know that right now 2.0 is not supported. We are porting to 2.0 as 1.1 doesn't have everything we need. Is there a timeframe on when a preview release may be available that would support 2.0? We will not be releasing core into production until end of year or next year (waiting for SignalR in Core) but we are trying to get as much hooked up as we can as soon as possible to see any problems or issues that are encountered.

Any information you have would be appreciated so we can plan out the work for supporting 2.0.
Thanks,
Steve

**Comment by llustosa** [comment]
The same for me.

I started a project last week that will depend on SignalR. Do you have any prevision to release IdentityServer for .netcore 2.0?

**Comment by MatthewGabriel** [comment]
> I started a project last week that will depend on SignalR

You can use SignalR with .netcore 1.1 although I'm unsure if all the features are available.  I have a basic SignalR .netcore 1.1 app.  I'm no expert on SignalR but just wanted to check you knew it can be used.

**Comment by llustosa** [comment]
@MatthewGabriel Thanks for replying. I believe that you are referencing the .Net Framework libraries on your app, right? So I guess that you loose portability. This is importante for me because my application will be deployed on a Linux enviroment. Please correct me if I'm wrong.

**Comment by MatthewGabriel** [comment]
This nuget package is the one I'm using: .Net Standard 1.6: https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Microsoft.AspNetCore.SignalR.Server

**Comment by llustosa** [comment]
Ok, I'll test this package. Thanks.

**Comment by spudcud** [comment]
This question was not about SignalR. I am looking for a preview of IdentityServer 4 to plug it in to a Core 2.0 app.

**Comment by MatthewGabriel** [comment]
Sorry, I realise the question was about IdentityServer4 for Core 2.0.  I can't answer that accurately, but I don't think it is available yet.  I was giving an alternative path for you to follow in the meantime until a preview of IdentityServer4 for Core 2.0 is available.  Your actual question is better answered by someone closer to the project.

**Comment by leastprivilege** [comment]
not yet - we are waiting for preview 2 of asp.net core 2. 

tracked here: https://github.com/IdentityServer/IdentityServer4/issues/1055
