### ISSUE TITLE
Storing and retrieving identity tokens and access tokens in the database using stored procedures

### ISSUE THREAD

**Issue by passionislyf14** [IdentityServer/IdentityServer4#1237]
Hi all,

This is a question not an issue. I want to store and retrieve identity tokens and access tokens from the sql server database. Please note that I cannot use EF and I will be creating tables and stored procedures. In IdentityServer3, looks like this was achieved by overriding TokenHandleStore. What is the best way of accomplishing this in IdentityServer 4 ? Any help is appreciated. Thank you.

**Comment by brockallen** [comment]
Operational data: https://identityserver4.readthedocs.io/en/release/topics/deployment.html

**Comment by passionislyf14** [comment]
@brockallen Thank you
