### ISSUE TITLE
Possible way to persist temporary data during authorization flow

### ISSUE THREAD

**Issue by apacherose** [IdentityServer/IdentityServer4#1238]
I would like to keep some operational data during the authorization flow.

The setting, described with few words, is the following: 
A javascript client is redirected to IdentityServer and a login screen is displayed.
Based on some specific criteria (business case), I'd like to store some data somewhere so it can be accessed 
later in my custom implementation of `IProfileService`, more specifically in `GetProfileDataAsync(context)`.
So the `AuthorizeEndpoint` can get needed claims and then return back to the originating client. 

I don't want to keep it in database, I'd prefer some in-memory solution.
I cannot use http features like query string, session or cookies, because `IProfileService` is out of this scope.
The `GetProfileDataAsync(context)` method receives just a `ProfileDataRequestContext `object.

I will think of other ways to achieve the desired goal (and maybe end up using a database-like storage), 
but I'd like to hear some ideas if someone has already faced this case.

Thank you.

**Comment by benjaminadrom** [comment]
I have nearly the same situation, i want to pass additional data to the custom "GetProfileDataAsync()" but i am not able to achieve this...

**Comment by leastprivilege** [comment]
Either put that data into the signin cookie - or use a cache like Redis.

**Comment by apacherose** [comment]
Yes, the solution with a cookie indeed came into an idea lately.
So we'll end up with the following solution:
- at the beginning of the login process we add the needed data into claims collection
HttpContext.Authentication.SignInAsync(subjectid, username, props, claims);

- and then later, in the above mentioned IProfileService ,we access this data through `ProfileDataRequestContext.Subject` principal, which contains the claims.

Thank you for confirming the validity of the approach.
