### ISSUE TITLE
Replace token generation and validation

### ISSUE THREAD

**Issue by adaneam** [IdentityServer/IdentityServer4#1239]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I have a separate service for generating and validating tokens. How do I get hold of token generation and validation logic in IdentityServer4?

I want to replace access_token value with one returned by my existing service.

**Comment by arzzzae** [comment]
You can create your own implementation of ITokenService and ITokenRequestValidator.

**Comment by brockallen** [comment]
@adaneam  all set?
