### ISSUE TITLE
Ability to filter claims returned from UserInfoEndpoint via scope

### ISSUE THREAD

**Issue by patnolan** [IdentityServer/IdentityServer4#1241]
Hi,

Can we add a request to allow extra parameters to be passed to the UserInfoEndpoint service similarly to the TokenEndpoint? I've noticed a number of people have raised a need for this feature throughout the various forums.

I'm trying to retrofit IdentityServer4 into a legacy environment so I cannot change the system in any significant way. Without going into great detail about the domain, I need to retrieve the Claims from IdentityServer from within an API AuthorizationHandler. In our case, the claims cannot be passed around with the token.

From our AuthorizationHandler we access the "site" route which determines which part of the system the user is accessing (see sample below). I'm planning to align the "site" with an IdentityServer API scope. I then want to only retrieve the claims which are relevant to the scope "site".

The problem is that we only no the scope they're targeting at the point they call an API operation. They could potentially access multiple scopes via multiple calls to the API using the same access token. We do not want to return the claims for every scope on login or API authorisation as in our case it's extremely large and there's a noticeable performance hit. 

Could you please include the ability to filter the claims returned from UserInfoEndpoint via something such as scope (or allow extra parameters like the TokenEndpoint)?

Sample implementation may be something like this

```
var userInfoClient = new UserInfoClient(disco.UserInfoEndpoint);
var response = await userInfoClient.GetAsync(tokenResponse.AccessToken, "scope1 scope2");
```

SAMPLE AuthorizationHandler
```
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, ClaimAuthorizationRequirement requirement)
{
    try
    {
        var filterContext = context.Resource as AuthorizationFilterContext;
        if (filterContext != null)
        {
            if (filterContext.RouteData.Values.Keys.Any(k => k == "site"))
            {
                var value = filterContext.RouteData.Values["site"] as string;
                if (!string.IsNullOrEmpty(value))
                {
```

**Comment by joshpearce** [comment]
I'm no expert but I'm curious to know why you want to pass this information around as claims? Does each site not have an independent (of Identity Server) way to get this information about the user?

**Comment by patnolan** [comment]
Hi,

I'm actually not passing the claims around with the token. My API is retrieving the claims from IdentityServer via an AuthorizationHandler. 

The "site" route actually corresponds to a SharePoint subweb. I need to use the ProfileService behind IdentityServer to build some claims where the source for the claims is data retrieved from the SharePoint subweb.

However, I need to pass into the ProfileService some identifier for the subweb so I know which subweb the user is trying to target. The two options I have mentioned in my above post would be to update the UserInfoEndpoint to include optional parameters like the TokenEndpoint. I believe the ability to filter the claims returned via allowed scopes would be the most elegant solution. I could then define each subweb as an allowable scope. I don't want to return all claims for all scopes as this would be extremely inefficient.

From my extensive reading around various forums I know adding this ability to the ProfileService would help a lot of people.

**Comment by brockallen** [comment]
Out of curiosity, why so many identity claims associated with each API resource? Or are you using this as a permissions system (which is not what IdentityServer is designed to be)?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
