### ISSUE TITLE
Using acr_values=“idp:Google” with Xmarin's IdentityModel.OidcClient does not Skip login page on identityserver4

### ISSUE THREAD

**Issue by Merawza** [IdentityServer/IdentityServer4#1245]
I am using the sample code for xamarin oidcclient to authenticate users,
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/AndroidClientChromeCustomTabs/AndroidClientChromeCustomTabs/MainActivity.cs

I want to skip login page if user chooses an external provider, I was able to do that in sample code by adding extras parameter acr_values:

var result = await _oidcClient.LoginAsync(extraParameters: new { acr_values="idp:Google" });

and it worked, but not with my implementation of identityserer4, I have to choose the external idp again on idsrv's login page, my client config is:

new Client
                {
                    ClientId = "mvc",
                    ClientName = "MVC Client",
                    AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,
                    RequireConsent=false,
                    AccessTokenType=AccessTokenType.Jwt,
                    AllowAccessTokensViaBrowser=true,

                    ClientSecrets = {
                        new Secret("secret".Sha256())
                    },

                    // where to redirect to after login
                    RedirectUris = { "http://192.168.1.6.nip.io:13013/Home/", "io.identitymodel.native://TrainAppCallback" },

                    // where to redirect to after logout
                    PostLogoutRedirectUris = { "http://192.168.1.6.nip.io:13013/signout-callback-oidc" },

                    AllowedScopes = new List<string>
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1"
                    },

                    AllowOfflineAccess = true,

                    RequirePkce = true
                }
am I missing some configuration on idsrv? because the only difference in my client code is the authorization endpoint (instead of https://demo.identityserver.io I use my local implementation of idsrv).

**Comment by adkendall** [comment]
Is this because of issue https://github.com/IdentityServer/IdentityServer4/issues/1250 ?

I too am having difficulty using acr_values to have a client bypass the login page and go straight to my external OpenIdConnect IdP.

**Comment by Merawza** [comment]
Not sure, I tried it with google and facebook, same problem, redirection does not occur, although when I try my code gainst the https://demo.identityserver.io/ it works as expected for google.
I have downloaded the Identityserver4Demo source, and I'll deploy it locally and test if it'll work.

**Comment by leastprivilege** [comment]
Can't repro - check your logs for more hints. closing for now.

**Comment by Merawza** [comment]
The demo worked as expected, I was using an account controller that does not handle external providers.
