### ISSUE TITLE
Question regarding refresh_token in MVC Hybrid

### ISSUE THREAD

**Issue by robertdavey** [IdentityServer/IdentityServer4#1247]
Hi, I have a question regarding the authentication cookie. We're using a model similar to that of the [MvcHybrid](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients/src/MvcHybrid) example from the samples. One problem we're experiencing though is with the refresh token, and the authentication cookies.

In the example, the call to `app.UseCookieAuthentication(…)` sets the cookie expiration time at 60 minutes.

If the authentication cookie has expired (say after 60 minutes of inactivity) and we try to call the `RenewTokens()` action, the call to `GetTokenAsync("refresh_token")` returns `null` as the authentication cookies are expired.

Is there a setting, or change we can make, to prevent this from happening? We've tried using the `SlidingExpiration` setting on the `CookieAuthenticationOptions` but this only has an effect if requests were made inside the cookie lifetime.

If not we may have to increase the lifetime of the authentication cookie to reduce the risk of this happening. Are there any real security concerns with extending the lifetime of a cookie like this to say, 7 days?

**Comment by leastprivilege** [comment]
IMO - the cookie is not a good place to store refresh tokens. Store them in a database or similar.

The `SaveTokens` feature seems convenient - but cookies get very big and you run into the above mentioned problems.

**Comment by brockallen** [comment]
> IMO - the cookie is not a good place to store refresh tokens. Store them in a database or similar.

Or store them in the cookie (for convenience) and use the ICookieManager to store the actual payload in a DB or a distributed cache: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/ICookieManager.cs
