### ISSUE TITLE
Implementing RefreshTokenStore & token serialization.

### ISSUE THREAD

**Issue by cleftheris** [IdentityServer/IdentityServer4#125]
Currently I am trying to implement a RefreshTokenStore that persist to the database. I would like to use the `ToClaimsDictionary` extension method in order to serialize the claims of the refreshToken 

My model

```csharp
    public class IdentityRefreshToken
    {
        public string Key { get; set; }
        public string SubjectId { get; set; }
        public string ClientId { get; set; }
        public DateTime IssuedUtc { get; set; }
        public DateTime ExpiresUtc { get; set; }
        public string ProtectedTicket { get; set; }
    }
```

1. Is there a possibility to change [ClaimListExtensions](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Extensions/ClaimListExtensions.cs#L13) to be public?
2. is there any better way to serialize the contents of the refeshToken and have them deserialized latter on?
3. Should I filter out any expired tokens upon `GetAsync` or this is the responsibility of the caller.

Thanks

**Comment by leastprivilege** [comment]
have a look at the idsrv3 EF repo - it has helpers.
