### ISSUE TITLE
idp:Negotiate on acr_values does not work!

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1250]
fix it!

**Comment by brockallen** [comment]
It's because when the login page logs the user in with one of the windows-based MW schemes, it changes it to "Windows", but back in the authorize validator the current scheme doesn't match the acr_value so it re-triggers login.

**Comment by brockallen** [comment]
So we should decide if we want the QS UI to hide the different windows schemes or not. IOW, if we don't hide them, then the upstream plumbing will need to know what Negotiate and NTLM mean (and know the difference and/or the fact that they're both windows). If we do hide them, then we should not be supporting "Negotiate" in the QS login workflow as a scheme.

**Comment by brockallen** [comment]
For the time being, I added to the QS support for acr_values="idp:Windows".

**Comment by larsw** [comment]
Pardon my lack of internal IdentityServer jargon knowledge, but what's "QS" ?

**Comment by brockallen** [comment]
QS is just for "quick starts"

**Comment by leastprivilege** [comment]
Yeah - I like calling it Windows. Should this be merged into the QS repo as well?
