### ISSUE TITLE
Persisting access tokens and identity tokens in the database without EF, Override PersistedGrantStore ?

### ISSUE THREAD

**Issue by passionislyf14** [IdentityServer/IdentityServer4#1254]
Hi all,

This is a question not an issue. I need to persist access tokens and identity tokens in the database without using Entity Framework.  Is overriding the behavior of Persisted Grant Store the right way of doing it ? Can anyone please point me in the right direction ? Any help is appreciated. Thank you.

**Comment by chrisowhite** [comment]
You just need to create your own implementation of `IPersistedGrantStore` and register it in `Startup.ConfigureServices()`.

**Comment by passionislyf14** [comment]
@chrisowhite Thank you
