### ISSUE TITLE
SAML2.0 support

### ISSUE THREAD

**Issue by DominikPfeifer** [IdentityServer/IdentityServer4#1256]
For a new Application in our Company we need SAML2-SSO.

Are there any plans for IdentityServer4 SAML2.0 support?

**Comment by chrisowhite** [comment]
You can implement an extension grant for the SAML 2.0 Profile for OAuth 2.0. I've done this for the JWT Assertion Profile. 

https://tools.ietf.org/html/rfc7522

Your application would accept the SAML assertion, and then send it to the idsrv token endpoint with the SAML assertion grant type. Idsrv will resolve your extension grant validator where your code running in idsrv would validate the assertion, resulting in an access token being issued.

**Comment by brockallen** [comment]
> Are there any plans for IdentityServer4 SAML2.0 support?

Given how we have designed for external authentication, we don't inherently support protocols for external IdPs. This is something you'd need an authentication middleware for. Microsoft will never implement this, so you should consider hiring @andersabel to build it.

**Comment by DominikPfeifer** [comment]
Sorry, i didn't meant external authentication.

I want IdentityServer to have a SAML endpoint, like mentioned here it should already work with WS-Federation:
https://identityserver4.readthedocs.io/en/release/topics/add_protocols.html

In a blog entry from @leastprivilege it says 

> When we designed IdentityServer4, we wanted to make it easier to extend the core token service with custom protocol endpoints.
https://leastprivilege.com/2017/03/03/extending-identityserver4-with-ws-federation-support/

**Comment by brockallen** [comment]
Ah, so then you'd need to follow the pattern in our ws-fed example: https://github.com/IdentityServer/IdentityServer4.WsFederation. But you would still need a library or component to handle the SAML2-P protocol. Microsoft will never implement this, so you should consider hiring @AndersAbel to build it.

**Comment by leastprivilege** [comment]
We are considering building a commercial SAML2p plugin. Please contact us at identity@leastprivilege.com to discuss more details.

**Comment by clegendre** [comment]
Hello @leastprivilege,
Do you already have any idea about the price of this plugin and an estimated release date?

Thank you.

**Comment by brockallen** [comment]
Email us, @clegendre, and we can get you those details.

**Comment by andrewclymer** [comment]
The scheduled release date will be 1st September, the price of the component is $2500

**Comment by Newbe36524** [comment]
is that avaliable now ?  I sent email ,but no reply

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2017/10/13/saml2p-identity-provider-support-for-identityserver4/

**Comment by DebasishEuro** [comment]
Hello ,

Does Identity Server 4 support OAuth and SAML?.As we have an existing MVC application which needs to support the above two security protocols.This MVC application is using external Identity Providers like SSO..But our Identity Server is configured as OpenId and OAuth.If its possible please give a solution.

Thanks

**Comment by scottbrady91** [comment]
You would need to implement something like https://tools.ietf.org/html/rfc7522. This isn't currently supported by IdentityServer or the IdentityServer SAML component.

**Comment by pizzadev** [comment]
So, Is it possible to have SAML2 with .net core 2 and identityserver4?   Documentation says that it is possible, also there is a link to the sample, BUT!!! Sample Project was built with .net framework 4.6.1 (you can open properties of the project and see the version of .net). SamlPlugin is NOT COMPATIBLE with .net core 2....

@scottbrady91  When I'm installing nuget package with SAML plugin it says: "Package Rsk.IdentityServer4.Saml 2.0.2.3 was restored using .net framework 4.6.1 instead of target framework .netCoreApp 2. This package may be not fully compatible with your project"
How that can be solved?

**Comment by scottbrady91** [comment]
@pizzadev The IdentityServer 4 SAML component supports ASP.NET Core 2.0 targetting the full .NET Framework. We're looking at adding .NET Core support, using the new Microsoft libraries that came out a few weeks ago, in the next version of the library.

**Comment by tarunp** [comment]
Hi Scott, Any tentative timeline for new .Net core libraries support in Rsk.IdentityServer4.Saml and Rsk.IdentityServer4.WsFederation packages?

**Comment by ryanbuening** [comment]
@scottbrady91 any updates  on .NET Core support?

**Comment by scottbrady91** [comment]
We've made a start at porting them, but have been slowed down since none of the metadata libraries made it to .NET standard. Unless anyone knows otherwise?

**Comment by gary-b** [comment]
We're considering idsrv4 for auth in our saas app. We have multiple customers who will want their users to login with identities stored in their ad servers. One of these uses    saml 2. We control the client apps, currently a mobile app (ionic) and webforms app that will use user logins, either local to idsrv or via the id server of the customer and an api that will use client logins, likely local to idsrv but unsure.

1. Where does the oauth solution presented by @chrisowhite fit in?

2. The saml commercial offering had some limitations, no support for logout - will this be added /why is it not supported - is it something inherent to one of the parts? No api support - this shouldn't affect the mobile app should it? It communicates with us via an api, but users are displayed a login screen on the app. We will need offline mode too note.

3. If we get our customer to support ws fed, what is the timeline for the saml 2 offering to support .net core proper? The question is do we need to target .net 45 from the off to support a saml 2 customer 6 months from now, asuming a switchover might be tricky?

4. Idsrv 3 has a saml example. It's noted the example server used doesn't support much security. Does this mean there's much more work to make this the code fit for use against saml2 pointing to ad for production use?

I'm not asking for all the tech details, just ensuring idsrv is the way to go.

**Comment by gary-b** [comment]
The above is @scottbrady91 mostly for you, sorry for the spam. I don't think an edit sends a notification.

**Comment by chrisowhite** [comment]
@gary-b Take my idea with a grain of salt since it's basically a hack. The right way to do this would be to support SAML in idsrv either via the RSK solution of if you happen to already have a license with ComponentSpace as they have another option for integrating with IdentityServer4.

**Comment by scottbrady91** [comment]
Based on your scenario, it sounds like you want IdentityServer to act as a SAML SP (send SAML requests and receive SAML responses), as opposed to acting as an IdP (receive SAML requests and send SAML responses). Whilst our component does offer that side of the story, it is not IdentityServer specific.

But to answer your questions:
1. SAML doesn't have the concept of API security, so when you log in using SAML you don't get anything similar to an access token. A proposed solution to this is to use RFC7522 and swap SAML assertions for access tokens.
2. For acting as a SAML IdP, there is limited support for logout. Currently we just don't support logout responses. This was to keep things simple and maintain OpenID Connect single sign off. There are plans to build upon this in the future.
3. .NET Standard 2.0 support is scheduled for release in September. I'm still working through porting the old metadata libraries.
4. I'm not sure which sample you mean. Do you have a link?

**Comment by gary-b** [comment]
Thanks @scottbrady91 You are correct i think in that idsrv will be a saml2 sp

1. We will have a mobile app where the user signs in, and then it makes rest calls when online. These rest calls will be secured with a token presumably. Does the fact that the IDP idsrv will be redirecting them to uses SAML2 mean that we will have to deal with RFC7522? (Its confusing because there is such a thing as a SAML2 token too).

4. I was referring to https://coding.abel.nu/2015/01/saml2-for-thinktecture-identityserver-3-with-kentor-authservices/
