### ISSUE TITLE
Client secret stilling being logged in 1.5.1/1.5.2

### ISSUE THREAD

**Issue by joemcbride** [IdentityServer/IdentityServer4#1258]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

It doesn't look like https://github.com/IdentityServer/IdentityServer4/issues/1068 / https://github.com/IdentityServer/IdentityServer4/pull/1076 has made the cut for the last two versions.  Any chance to get a version pushed with that commit?  Thanks!

1) Download version 1.5.1 or 1.5.2
2) Request a token
3) Look at the log file

### Relevant parts of the log file

```
[2017-06-14T12:27:26.5487574-07:00 INF 0HL5JBDC64DU8] (5993a9fa) Token request validation success
"{
  \"ClientId\": \"some_id\",
  \"ClientName\": \"a name\",
  \"GrantType\": \"authorization_code\",
  \"AuthorizationCode\": \"...\",
  \"Raw\": {
    \"grant_type\": \"authorization_code\",
    \"code\": \"...\",
    \"redirect_uri\": \"http://localhost/signin-oidc\",
    \"code_verifier\": \"...\",
    \"client_id\": \"some_id\",
    \"client_secret\": \"secret\"
  }
}"
```

**Comment by leastprivilege** [comment]
This is for 2.0
