### ISSUE TITLE
Adding claims/data to already issued token without logging out?

### ISSUE THREAD

**Issue by apacherose** [IdentityServer/IdentityServer4#1259]
Hello,

I’d like to add additional claims to already issued access token of user.
More concrete, the case is the following:
A user is logged in, and tokens are issued. Later, at some time, the user may(or may not) access resource that requires client certificate(and data from it).
So I’d like to **reissue the token**, adding some of certificate public data as claims, without forcing the user to logout.

I see that the easiest way is achieve this, is to force the user to logout and then prompt for new login, this time with certificate.
Yet, I’d like to know if I can skip this inconvenience for the user by using the means of the IdentityServer.

The client of the IdentityServer is javascript application and implicit flow is used.

Thank you.

**Comment by brockallen** [comment]
Sounds like your client needs to make a new authorization requests that includes the new/additional scope.

**Comment by apacherose** [comment]
Found the solution too complicated, so we decided to prompt for client certificate at the login page and then within the login process and the token creation use the some date from the certificate.
If the user does not provide client cert, then later when cert data is required, we kindly request the user to re-login again, so we can get that certificate data.
