### ISSUE TITLE
Is there an equivalent of DelayLoadMetadata in IdentityServer4?

### ISSUE THREAD

**Issue by ciriarte** [IdentityServer/IdentityServer4#126]
Greetings Everyone,

Is there an equivalent of DelayLoadMetadata in IdentityServer4?

https://identityserver.github.io/Documentation/docsv2/consuming/options.html

Mostly, I am interested in adding `Issuer Name` and the `Signing Certificate` to statically validate tokens, but I don't see them yet on version 4.

**Comment by leastprivilege** [comment]
sure - in the access token validation MW for idsrv4

**Comment by nilavghosh** [comment]
Hi,

I still could not figure out where the DelayLoadMetadata option is in IdentitySever4 . Would be really helpful if someone could help. :)

Regards,
NIlav Ghosh

**Comment by leastprivilege** [comment]
it's the default behavior now.

**Comment by nilavghosh** [comment]
Yes Dominick,

I figured this out. Thanks so much.

Regards,
Nilav Ghosh
