### ISSUE TITLE
Sliding refresh tokens with unbounded absolute lifetime

### ISSUE THREAD

**Issue by chrisowhite** [IdentityServer/IdentityServer4#1261]
I've come across a need to have sliding lifetime refresh tokens, but I don't want them to hit an absolute limit if they continue to be exchanged within the sliding window. 

There a couple ways I can do this:

1. Set a really high `Client.AbsoluteRefreshTokenLifetime`
2. Create my own implentation of `IRefreshTokenStore` that interprets `Client.AbsoluteRefreshTokenLifetime = 0` as unlimited, ignores the absolute lifetime, and continues to increase the lifetime of the token (32-bit int is good for about 68 years worth of seconds).

Option 1 has bought me time in production until I can get option 2 out, but I was wondering is this was something to consider implementing in the `DefaultRefreshTokenService` and `TokenRequestValidator`.

**Comment by leastprivilege** [comment]
Well - given how our industry works - a lifetime of 5 years should be more than needed (make it 10 if you need to protect a mainframe-based API) ;)

IOW - yes in theory you are right - but not sure it is worth the efforts given you can set the lifetime to e.g. 100 years.

**Comment by leastprivilege** [comment]
If you want to do a PR for this - including tests etc - feel free.

We won't have the time in the foreseeable future.

**Comment by chrisowhite** [comment]
No problem. On it.

**Comment by brockallen** [comment]
Merged, thanks!
