### ISSUE TITLE
Revoke a Reference Token

### ISSUE THREAD

**Issue by AdamRiddick** [IdentityServer/IdentityServer4#1263]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

I'm looking to implement functionality to allow administrator users to log-out any user from all clients connected to an authentication server running Identity Server 4, using Entity Framework.

I have a client connecting with OIDC using reference tokens (Access Token Type = 1) and I call `RemoveAllGrantsAsync` on the `IPersistedGrantService` and it successfully removes all of the persisted grants for the Identity in question, however the next request to Identity Server results in the Persisted Grant being created again;

I can see it can't find the peristed grant;
`
 AoNroO0IZG3x6YfNpdEn62ZuSGA9cAxO0xmLnpmfWtc= not found in database
`

But then it's inserted again, whereas I would expect the validation to fail;
```
SET NOCOUNT ON;
INSERT INTO [idsrv].[PersistedGrants] ([Key], [ClientId], [CreationTime], [Data], [Expiration], [SubjectId], [Type])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6);
```

The client is configured as follows;
```
app.UseCookieAuthentication(new CookieAuthenticationOptions
                                            {
                                                AuthenticationType = "Cookies"
                                            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
                                                   {
                                                       ClientId = "silicon",
                                                       Authority = "http://localhost:64916/",
                                                       RedirectUri = "http://localhost:10315/",
                                                       PostLogoutRedirectUri = "http://localhost:10315/",
                                                       SignInAsAuthenticationType = "Cookies",
                                                       ResponseType = "code id_token",
                                                       Scope = "openid profile restapi offline_access"
            });
```

Am I missing something in the configuration to prevent the removed grant from authorizing?

**Comment by brockallen** [comment]
> I have a client connecting with OIDC using reference tokens (Access Token Type = 1) and I call RemoveAllGrantsAsync on the IPersistedGrantService and it successfully removes all of the persisted grants for the Identity in question, however the next request to Identity Server results in the Persisted Grant being created again;

Presumably because of SSO, right? IPersistedGrantService doesn't deal with active login sessions (IOW the user's cookie), so you'd need to devise a way to kill the cookie (typically via the cookie validate principal event): https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/Events/CookieAuthenticationEvents.cs#L20

**Comment by AdamRiddick** [comment]
Yeah because of SSO - Thanks for this I'll take a look at the validate principal event.

**Comment by egmfrs** [comment]
@brockallen your link is taking me to a 404 page.
