### ISSUE TITLE
Access ConfigurationDbContext outside startup

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1266]
How can we access the same instance of ConfigurationDbContext outside the startup class after we configure it in the Startup.cs ?

I want to create a repository with ConfigurationDbContext and want to use the same instance of ConfigurationDbContext as configured in startup.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by satyajit-behera** [comment]
Thanks
