### ISSUE TITLE
Integrate with custom authentication provider

### ISSUE THREAD

**Issue by sowsan** [IdentityServer/IdentityServer4#1267]
I have a API which will validate the user identiy and it will respond whether user is valid or not. I want to integratrate that API so that I can make it's part of the open ID identity server ? Documenttion talking about test user and external providers https://identityserver4.readthedocs.io/en/release/quickstarts/4_external_authentication.html , I'm not sure how can in integrate my custom API for authentication. Any pointers would be really helpful

**Comment by brockallen** [comment]
Call it from the login logic on the account controller.

**Comment by sowsan** [comment]
Thank you !, my scenario is we have to provide the service as - "Authentication As Service", other client can integrate it as an external authentication provider. In the quickstart UI e.g, it using the middleware as below. Is it a best practice to make the UI components also part of the same middlware ? Sorry for my ignorance...still learning :) 

 // middleware for external openid connect authentication
        app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
        {
            SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
            SignOutScheme = IdentityServerConstants.SignoutScheme,

            DisplayName = "OpenID Connect",
            Authority = "https://demo.identityserver.io/",
            ClientId = "implicit",
                
            TokenValidationParameters = new TokenValidationParameters
            {
                NameClaimType = "name",
                RoleClaimType = "role"
            }
        });

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
