### ISSUE TITLE
DB + Identity + IdentityServer4

### ISSUE THREAD

**Issue by jkvargas** [IdentityServer/IdentityServer4#1268]
Hello, 
I'm working to integrate identityserver4 with identity and mongodb,
Now, the login is working correctly and authenticating against the database, but its failing when it goes to authorize endpoint.

here precisely:

`
internal async Task<IEndpointResult> ProcessAuthorizeAfterLoginAsync(HttpContext context)
        {
            _logger.LogDebug("Start authorize request (after login)");

            var user = await context.GetIdentityServerUserAsync();
            if (user == null)
            {
                return await CreateErrorResultAsync("User is not authenticated");
            }

            var parameters = context.Request.Query.AsNameValueCollection();
            var result = await ProcessAuthorizeRequestAsync(parameters, user, null);

            _logger.LogTrace("End Authorize Request. Result type: {0}", result?.GetType().ToString() ?? "-none-");

            return result;
        }
`

my user is always returning null.
i feel thats something that i forgot to register.
in my Startup class i do have a AddSingleton for IUserRepository, IUserStore, IUserLoginStore, IUserClaimStore, IUserPasswordStore, IUserSecutiryStore, IUserPasswordStore, IUserSecurityStampStore, IUserTwoFactorStore, IUserEmailStore, IUserLockoutStore, IUserPhoneNumberStore, IUserRoleStore, IRoleStore.

also, i am setting 
        services.AddIdentity<User, Role>().AddDefaultTokenProviders();
and 
         app.UseIdentity();
         app.UseIdentityServer();

please, ask me if you need further info =)

**Comment by brockallen** [comment]
Sounds like the cookie is not present.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
