### ISSUE TITLE
Custom Grant Type Password with multi-tenant parameter

### ISSUE THREAD

**Issue by raffaeu** [IdentityServer/IdentityServer4#1269]
Following an article related to multi-tenancy, I have customized **Identity Server 4.0** to allow multi-tenancy. This is achieved by having an extra field in the user table, of type `Guid` which contains the *tenant (Organization) Id*.

All our applications are connecting and validating their connection by using the centralized Login User Interface provided by Identity Server 4.0 which is also asking now for an extra parameter in the query string (tenant_id). Everything works as expected and a tenant authenticated is not authenticated in another client but we need now to customize the `login` executed by the `grant_type=password` because that code is actually verifying only the combination of Username/Password and not Username/Password/Tenant.

My question is, what solution is better?

 - Provide a custom grant type and somehow *suppress* the default grant_type = password?
 - Customize the grant_type = password with custom logic?

In case of the second scenario, is this possible? Is there an example about it?

**Comment by leastprivilege** [comment]
The resource owner password validator has access to the raw request - e.g. an acr_values that contains tenant.

**Comment by raffaeu** [comment]
Perfect, I just to override that and pass extra parameters.

**Comment by vdecristofaro** [comment]
@raffaeu
Could you please share the article you followed please?
