### ISSUE TITLE
302 redirect on login to wrong URL

### ISSUE THREAD

**Issue by artstalker** [IdentityServer/IdentityServer4#1271]
Hi,

I have a strange issue on Azure with IDS after latest upgrade of all nuget packages.
Our IDS is hosted on Azure environment with URL:
http://xxxxx.azurewebsites.net
But when I try to login or logout, the workflow crashes because it always redirect to
htttp://xxxxx:80.
Note that there is no **azurewebsites.net** anymore
![image](https://user-images.githubusercontent.com/2846956/27421763-73565436-5734-11e7-9b57-09741e02202d.png)

Below are logs from IDS. It already uses wrong url there from the begining:

>  2017-06-22 07:05:15.514 +00:00 [Information] Request starting HTTP/1.1 GET http://xxxxx:80/connect/authorize?response_type=id_token%20token&client_id=js&redirect_uri=http://xxxxx.azurewebsites.net/&scope=api1%20openid%20profile&nonce=N0.61489864144180631498115112901&state=14981151129010.8108356828992858  
> 2017-06-22 07:05:15.514 +00:00 [Information] "idsrv" was not authenticated. Failure message: "Ticket expired"
> 2017-06-22 07:05:15.717 +00:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.AuthorizeEndpoint" for "/connect/authorize"
> 2017-06-22 07:05:16.076 +00:00 [Information] ValidatedAuthorizeRequest
> "{
>   \"ClientId\": \"js\",
>   \"ClientName\": \"JavaScript Client\",
>   \"RedirectUri\": \"http://xxxxx.azurewebsites.net/\",
>   \"AllowedRedirectUris\": [
>     \"http://localhost:5003/\",
>     \"http://localhost:5003/callback.html\",
>     \"http://localhost:5001/swagger/o2c.html\",
>     \"http://localhost:5002/swagger/o2c.html\",
>     \"http://xxxxx.azurewebsites.net/\",
>     \"http://xxxxx.azurewebsites.net/callback.html\",
>     \"http://xxxxx.azurewebsites.net/swagger/o2c.html\"
>   ],
>   \"SubjectId\": \"anonymous\",
>   \"ResponseType\": \"id_token token\",
>   \"ResponseMode\": \"fragment\",
>   \"GrantType\": \"implicit\",
>   \"RequestedScopes\": \"api1 openid profile\",
>   \"State\": \"14981151129010.8108356828992858\",
>   \"Nonce\": \"N0.61489864144180631498115112901\",
>   \"Raw\": {
>     \"response_type\": \"id_token token\",
>     \"client_id\": \"js\",
>     \"redirect_uri\": \"http://xxxxx.azurewebsites.net/\",
>     \"scope\": \"api1 openid profile\",
>     \"nonce\": \"N0.61489864144180631498115112901\",
>     \"state\": \"14981151129010.8108356828992858\"
>   }
> }"
> 2017-06-22 07:05:16.076 +00:00 [Information] Showing login: User is not authenticated
> 2017-06-22 07:05:16.076 +00:00 [Information] Request finished in 584.9474ms 302 

While trying to understand what's wrong, I've opened .well-known/openid-configuration to see endpoints on IDS and here what I've seen:
![image](https://user-images.githubusercontent.com/2846956/27422046-7a7c66b4-5735-11e7-8962-a08fed8ed588.png)

There is no **azurewebsites.net** part in endpoints. My main question is how this config is generated? How can I debug it to see what went wrong?

**Comment by artstalker** [comment]
I've found out that HttpContext.Host is set to xxxxx:80 (without azurewebsites.net). I think that's what causing the issue because later on BaseUrlMiddleware sets IdentityServerOrigin to this wrong value

**Comment by artstalker** [comment]
I just deployed IDS sample from https://github.com/IdentityServer/IdentityServer4.Samples/ and it does not work properly as well
Please, open this url to see configuration:
http://jfids3.azurewebsites.net/.well-known/openid-configuration

**Comment by artstalker** [comment]
Fixed by this code in IDS Startup.cs:
```
 var fordwardedHeaderOptions = new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            };
            fordwardedHeaderOptions.KnownNetworks.Clear();
            fordwardedHeaderOptions.KnownProxies.Clear();

            app.UseForwardedHeaders(fordwardedHeaderOptions);
```

Put it **before** `app.UseIdentityServer();`

**Comment by stt106** [comment]
Can you please confirm it's the same issue? https://github.com/IdentityServer/IdentityServer4/issues/1779

**Comment by artstalker** [comment]
It does not look the same for me. The issue is different
