### ISSUE TITLE
Upgrade IdentityServer4 issue

### ISSUE THREAD

**Issue by StevenZhou1985** [IdentityServer/IdentityServer4#1274]
Dear Guys,
We have a product which is created based on IdentityServer4. Currently the .net core project in the solution was still based on xproj, not the latest csproj. We have met an issue in the TFS build(VS2015) that "An item with the same key has already been added. Key: System.Net.Http Unspecified" after we upgraded IdentityServer4 libraries to latest version.
As you know, latest IdentityServer4 libraries was based on csproj now. I would like to confirm with you guys if that's the root cause for the issue. Thanks.
BTW: There is no issue in local build when we use VS2015 + .net core 1.0.

Reference:
https://github.com/dotnet/cli/issues/2925
https://github.com/dotnet/cli/issues/2796
https://github.com/dotnet/cli/issues/1860

**Comment by leastprivilege** [comment]
I don't know. I would recommend you upgrade to the RTM tooling ASAP.
