### ISSUE TITLE
different type of users restrict customer user to not login from admin side and vise versa

### ISSUE THREAD

**Issue by xubair81** [IdentityServer/IdentityServer4#1275]
in my project solution i have three types of users (admin,customer and staff) all types of user has different login page

the problem is user can login from all login pages i just to restrict to their own login page or project

i tried this and its work fine for me but security issue passing user_type from client side

{
                client_id: "js",
                client_secret: "secret",
                scope: "obapi offline_access",
                grant_type: "password",
                username: email,
                password: user.password,
               user_type:"Customer"
            }

is there any way to do same (every type of user login from their own login page)

i think this way i can solve my problem

for customer http://localhost:44337/connect/customertoken
for admin http://localhost:44337/connect/admin token
for staff http://localhost:44337/connect/stafftoken

but i am not sure it is possible or not if yes then tell me how to get this thing (security is most important)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
