### ISSUE TITLE
Edit Client

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1280]
The sample and seed data shows creating a new client in Startup.
This is fine in case of creating a client.

Are there any existing methods or provision for Updating a client. Update involves tracking the existing records from the collection fields within the clients too.
How are entities mapped from IdentityServer4.Models to IdentityServer4.EntityFramework.Entities during an update considering the records are already available in database?

Thanks

**Comment by brockallen** [comment]
We don't have any FOSS editing tools for config data. There is a commercial product called "AdminUI" https://www.identityserver.com/products/

**Comment by satyajit-behera** [comment]
Thanks. If we want to programmatically modify some of the properties of the Client model, are there any dos and donts that we should take care of. 
Just to confirm: We don't have any mapper for Edit or Retrieve client records?

**Comment by brockallen** [comment]
I'd suggest just keeping that data separate and even possibly a different repo/API/DbContext for it.

**Comment by satyajit-behera** [comment]
Thanks
