### ISSUE TITLE
Expose SessionStore option

### ISSUE THREAD

**Issue by Alxandr** [IdentityServer/IdentityServer4#1281]
Currently we can set CookieLifetime and CookieSlidingExpiration etc. on the AuthenticationOptions. Could you also provide an option to set `CookieLifetime` on the cookie middleware? Currently this is the only thing forcing me to create the middleware myself.

**Comment by brockallen** [comment]
You can register the cookie MW yourself and tell us about it via this: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/Options/AuthenticationOptions.cs#L28

**Comment by Alxandr** [comment]
On mobile, so apologies in advance for short and bad answer. Also noticed error in original post states CookieLifetime which should be SessionStore. My point was that:

1. This is the only cookie mw option I need not currently configurable, so I need to manually create mw for single option. 
2. Needing to not use cookies cause size requirement is likely not uncommon. I've only added 3 claims to my user and that was enough. 
3. Regardless there should really be docs on this. I used quite some time figuring out how to shrink my cookies.

**Comment by brockallen** [comment]
> This is the only cookie mw option I need not currently configurable, so I need to manually create mw for single option.

Understood, but at what point do decide there are too many and it makes sense for you to do the entire MW. I suppose we could expose the entire CookieOptions... I'll leave this open to consider.

> Needing to not use cookies cause size requirement is likely not uncommon. I've only added 3 claims to my user and that was enough.

Sure, and that's starting to be outside the realm of our OIDC component. 

> Regardless there should really be docs on this. I used quite some time figuring out how to shrink my cookies.

Did you check at docs.asp.net? I'd expect Microsoft to be the main target of this request (not IdentityServer).

**Comment by Alxandr** [comment]
@brockallen the problem was not the oidc cookie but the cookie used to sign in to identityserver itself.

**Comment by brockallen** [comment]
> @brockallen the problem was not the oidc cookie but the cookie used to sign in to identityserver itself.

Sure, and that's what I was talking about. As I said, we only provide the cookie MW in the pipeline as a convenience, and the more you need to control it then there's a point where we just need to let you do all of it.

> To clarify, the cookie created by the /connect/* endpoint was too big. The one created by the oidc middleware was not.

Right, and you said only a few claims causes this to get huge... makes me wonder why, but normally we don't see this behavior. Again, I'll leave this open to do some more investigation when there's time.

**Comment by brockallen** [comment]
Were you ever able to find out why you had so many claims in your primary authentication cookie (and thus the size)?

**Comment by Alxandr** [comment]
Ah. Sorry, I haven't been working on it for a while (vaccation). And I have an exam in a week so I'm not working currently. That being said I'm not entirely sure how I would go about figuring it out? I currently employ a cache (SessionMemoryStore or somesuch) instead of putting the token in cookies, would looking at the data stored in the cache give you some information?

**Comment by brockallen** [comment]
Oh, so you're talking about the client, not the cookie in IdentityServer? Sorry if we're talking past one another...

**Comment by Alxandr** [comment]
No. I'm talking about the cookie in identityserver. It grew too large, so I had to convert it to "session". I had to do this for *both* the client and identityserver itself.

**Comment by brockallen** [comment]
So then I'd suggest finding out why... It should not generally need to be that large at IdSvr itself.

**Comment by Alxandr** [comment]
Yep. Will look at it next week.

**Comment by brockallen** [comment]
Any update?

**Comment by Alxandr** [comment]
Sorry. No. I'm afraid I'll have to say that I will likely not be able to look at this for a while. I started a new job today (been moving all of last week). We put authn on hold on my previous project untill everything is supported on ASP.NET 2.0. I would like to look at it, but I can't say when I will be working on the project where we used it again.

**Comment by brockallen** [comment]
Given the changes in 2.0, I'll close this. Feel free to open a new issue if something's not to your liking.

**Comment by Alxandr** [comment]
Will do. Hopefully I'll get the option to pick this up again later :)
