### ISSUE TITLE
Deployment Question

### ISSUE THREAD

**Issue by TDK1964** [IdentityServer/IdentityServer4#1282]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

I am deploying IdentityServer4 to my server where it's my intention to use it to authenticate multiple applications and/or client installations. I am also using the ASPNet Identity / EntityFramework configuration.

My question is - when deployed, the ASPNETxxx tables and IDS4 tables are location in the same database. Is this the best approach for my scenario or should the ASPNETxxx tables be located in the individual applications/client installations databases?

**Comment by brockallen** [comment]
That's up to you. We don't have an opinion on it.

**Comment by TDK1964** [comment]
@brockallen I was mainly looking for your expert guidance. If it were you deploying my example deployment what would you do?

**Comment by brockallen** [comment]
I'd keep them separate (either by db or by schema)
