### ISSUE TITLE
Issue with Private Key processing on Azure ARM Provisioned VMSS VM's

### ISSUE THREAD

**Issue by Iain-Stevenson** [IdentityServer/IdentityServer4#1286]
### Issue with Private Key on Azure VMSS VM's with certificate private keys provisioned by Azure KeyVault.

This is NOT a fault with IndentityServer4. 

This is a significant operational issue using IdentityServer4 under Azure and Service Fabric. 

Even though our provided workaround is a one-time per VM it is unsatisfactory, as scaling out additional VM's requires manual intervention.

We are contacting Microsoft on this issue but are posting here for three reasons;

- Alert the community to record the issue details and workaround
- Raise awareness with the IdentityServer team
- Elicit any alternative workarounds from anyone

If we get a solution from Microsoft we will update this post.

### Context

We have an Azure VMSS VM auto provisioned via ARM scripting / PowerShell for several Microservices running under Service Fabric on a secured cluster. 

A vital service in the product is IdentitySever4 securing access to a pubic WebAPI scope, which otherwise works correctly, and all services are publicly secured using the company domain wildcard certificate; 

We have three discrete environments;

- WORKING: Local development (Workstation) cluster secured using self signed IISExpress generated localhost certificate
- FAILED: Cloud Test cluster secured using domain wildcard certificate
- PENDING: Cloud production cluster secured using domain wildcard certificate

Our SDK client logs the user in via the IdentityModel.OidcClient for a client configured to request Access tokens for our WebAPI. 

### Problem

On publishing to Cloud Test cluster and running test client it fails. 

The failing workflow is; Client -> IDSRV -> Federated Identity -> Consent Screen -> JWT Token Creation -> Fatal

The Log showed the error;
```
2017-06-27 11:55:05.532 +00:00 [Verbose] Creating JWT identity token
2017-06-27 11:55:05.550 +00:00 [Fatal] Unhandled exception: "System.Security.Cryptography.CryptographicException: Keyset does not exist

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PrivateKey()
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_HasPrivateKey()
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
   at IdentityServer4.Services.DefaultTokenCreationService.CreateJwtAsync(JwtSecurityToken jwt)
   at IdentityServer4.Services.DefaultTokenCreationService.<CreateTokenAsync>d__3.MoveNext()
... more removed for brevity
```
This is the method in the DefaultTokenCreationService   

```
	/// <summary>
	///     Applies the signature to the JWT
	/// </summary>
	/// <param name="jwt">The JWT object.</param>
	/// <returns>The signed JWT</returns>
	protected virtual Task<string> CreateJwtAsync(JwtSecurityToken jwt)
	{
		var handler = new JwtSecurityTokenHandler();
		return Task.FromResult(handler.WriteToken(jwt));
	}

```

### Investigation

Googling the exception suggested this was a permissions issue accessing the declared private key as specified in the Startup.cs of the service;

`	identityServerBuilder.AddSigningCredential(_appSettings.Certificates.Thumbprint, StoreLocation.LocalMachine, NameType.Thumbprint);
`
The Thumbprint is configured to be that of the company wildcard domain certificate that is (Correctly) auto provisioned via Azure Key Vault. 

The certificate works/worked fine with the web services in all other ways on all clients.

As the workaround fixed the issue and there were no log entries suggesting key configuration we can assume it was not an issue with configuring the private key via startup.

In other words IdentityServer found the private key but as you will see it just was not allowed to use it.

### Cause

The provisioned certificate private key is not readable by the run time account of the IdentityServer service fabric Microservice.

The Microservice is by default running as "NT AUTHORITY\NETWORK SERVICE" and this has no permissions for the private key.

We are still establishing why it worked in local dev and not in the cloud.

### Workaround

Grant Read permissions for Service Fabric run time account "NETWORK SERVICE" for the private key.

In order to do this you MUST first change the Ownership of the private key to an administrator account.

Remote onto the affected Azure VM instances (ones which run the IdentityServer4 service) 

Find these using the Azure portal or PowerShell
```
As Administator account
Run the MMC then add the Certificates Snap-in for the LocalMachine
Locate the Personal store and select the certificate in question
Action -> All Tasks -> Manage Private Keys
Advanced -> Owner System - > Change
Change to Current Administrator Account -> OK
Add "NETWORK SERVICE" with Read Permission -> OK
Advanced -> Owner [Admin Account] - > Change
Change to System  -> OK
Done.
```
This worked and the system now operates as desired.

**Comment by brockallen** [comment]
Just so I'm clear: The cert is in the windows certificate store on the local machine?

**Comment by Iain-Stevenson** [comment]
Sorry for the confusion, and please forgive me if this is not the best place to raise awareness of this.

The self signed cert  in question (localhost) is in the  My store of the LocalMachine on my workstation and works fine.

The commercially provided real certificate is in the My store of the LocalMachine  on the VM. 

The environment settings switches correctly to look for (and find) the the required cert on both environments via the environment settings when publishing of the SF application and the service finds it ok on startup.

Basically IDSRV is told to look in the correct place for the correct certificate but the permissions associated with the Azure provisioning of that certificate to the VM make it unavailable for IDSRV to use it to sign JWT tokens. 

However the certificate is available to sign the browser sessions on that VM.

When the permissions are corrected as per my OP on the VM, IDSRV works like a dream.

I have located an SF based potential workaround for this but it will take me a while to test it.

Its the 2nd answer to this SO post [here](https://stackoverflow.com/questions/39188300/load-ssl-certificate-in-azure-service-fabric-for-custom-tcp-service/39209243#39209243
). This answer seems to be a (useful) hack to automate what I did manually via the SF application configuration XML files, a batch file and a PowerShell script to force the SYSTEM account to do the job on publication to the VM.

**Comment by brockallen** [comment]
> The self signed cert in question (localhost) is in the My store of the LocalMachine on my workstation and works fine.
> The commercially provided real certificate is in the My store of the LocalMachine on the VM.

I'm still a bit confused, so apologies. If the cert is in the windows certificate store, then yes, you always need to configure the worker process identity to access the private key. As for all the AWS stuff, I don't know any of that so perhaps that ignorance is clouding my ability to help here.

> However the certificate is available to sign the browser sessions on that VM.

Does this mean you're using the HTTPS cert also for signing tokens? If so, don't do that. Use a separate cert for tokens (and it doesn't have to be from a CA -- use just a self-signed cert).

**Comment by Iain-Stevenson** [comment]
First of your points. As I have 'solved' the issue I just really wanted to log this somewhere that people coming along behind in this scenario have a chance of finding a solution quickly. To be sure, this is definitely a Windows/Service Fabric environmental problem. Rest assured I don't really need you to guys to work on this, just intending to make others aware its a headache for folks using IDRSV on Service Fabric. At the moment there just is not enough info out there on the net on this particular edge case problem.

The thing that caught me out was that the two environments behave differently wrt to private key permissions in windows and is a bit of a gotcha.  I wanted to make it obvious and public that its not an IDSRV issue even though it shows up when you place IDSRV in that environment.

Point two: I wondered about that (self signed cert for token signing) I can do that easily as I'm already doing that for intra-node security on the cluster anyway. I will just generate another one just for token signing 

Thanks for the advice.

**Comment by brockallen** [comment]
No problem -- opening an issue is about the best way we have now for raising concerns like this.

**Comment by Mardoxx** [comment]
ACL for private key read on NETWORK SERVICE account should be done automatically when using VMSS ARM template to provision cert.

Although saying that, it is pretty flaky some times. Open an issue here https://github.com/Azure/service-fabric-issues/issues

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by Iain-Stevenson** [comment]
Yep close it off, not a bug with IDSRV. 

Here its on the work schedule. We will update when we have a concrete and working solution. Current work revolves around dynamically pulling the certificate out of KeyVault at service startup and injecting it into the .net services collection to avoid relying on Azure hosting to deliver certificate to m/c.
