### ISSUE TITLE
Authentication flow won't return to client app after two-factor authentication

### ISSUE THREAD

**Issue by johnxjcheng** [IdentityServer/IdentityServer4#1289]
After I enabled the two-factor authentication I saw an issue: that is if I tried to login from the client web app (5002), the flow does not come back. The consent step is not presented. The flow stops at home page of identity server (5000) after successfully phone code verification. See the attached Fiddler trace, line 163~164. In the trace, the first part was without enabling 2FA. It successfully ends at a client page (line 48). But with the extra steps of 2FA, (in the orange box), the second connect/authorization/ request is missing. 

### Issue / Steps to reproduce the problem
1. Follow the example: https://identityserver4.readthedocs.io/en/release/quickstarts/6_aspnet_identity.html, and create the Idp server and client web apps. 
2. Enable 2FA authentication that's provided by the ASP.NET Core template.
3. Setup user data, such as phone number and preference for 2FA.
4. Try to login from the Client web app. 

### Relevant parts of the log file
The Fiddler trace is attached. 
![identityserver4-2fa](https://user-images.githubusercontent.com/194134/27745124-c9b01b2e-5d87-11e7-8d1d-ddc32e09fb8a.png)

**Comment by brockallen** [comment]
Sure, because the ASP.NET Core templates don't know about hosting a token server. Feel free to submit a PR to update the templates in our sample for it.

**Comment by johnxjcheng** [comment]
I see your point and looked into the Core template. I changed one line of code in VerifyCode.cshtml. It fixed the issue. Here is the code: 
original: 
`<form asp-controller="Account" asp-action="VerifyCode" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal">`
new: 
`<form asp-controller="Account" asp-action="VerifyCode" asp-route-returnurl="@Model.ReturnUrl" method="post" class="form-horizontal">`

**Comment by damienbod** [comment]
just saw this ticket now.

I made a PR
https://github.com/IdentityServer/IdentityServer4.Samples/pull/182
