### ISSUE TITLE
Is there functionality for Idsvr3's EnablePostSignOutAutoRedirect implemented in Idsvr4?

### ISSUE THREAD

**Issue by ericgreenmix** [IdentityServer/IdentityServer4#129]
I am not seeing anything similar to this in Idsvr4 currently. Is this implemented or planned to be implemented?

**Comment by leastprivilege** [comment]
not yet - but planned

**Comment by kwarnke** [comment]
Was this ever addressed?

**Comment by brockallen** [comment]
> Was this ever addressed?

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Host/Quickstart/Account/AccountOptions.cs#L16

**Comment by fernandoespinosa** [comment]
WOW... indeed it was... **but in the MOST OBSCURE AND UNDOCUMENTED WAY POSSIBLE!**

Basically I had to follow up where is `AutomaticRedirectAfterSignOut` ever used, and that lead me to `BuildLoggedOutViewModelAsync(string logoutId)` where basically a `PostLogoutRedirectUri` is being fetched out of a magical object that comes out of `_interaction.GetLogoutContextAsync(logoutId)` where `_interaction` is an injected instance of one such `IIdentityServerInteractionService`.

THEEEEEEEEEEEN, look where on earth do I get one such `IIdentityServerInteractionService`, to find that the `DefaultIdentityServerInteractionService` is internal and can pretty much only be injected via the absolutely never talked about `AddPluggableServices()` builder extension...

# OMG

**Comment by leastprivilege** [comment]
Glad you figured it out ;)
