### ISSUE TITLE
How, when using ASP.NET Identity, can I add custom claims to access tokens obtained via extension grants?

### ISSUE THREAD

**Issue by infinnie** [IdentityServer/IdentityServer4#1290]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I have been using ASP.NET identity in my IdentityServer4 project like
```cs
builder.AddAspNetIdentity<ApplicationUser>()
```
in order to facilitate the Authorization Code/Implicit/Hybrid authentication flows. However, when I wanted to add an extension grant flow, I found that I could not include extra claims within the access token:

```cs
context.Result = new GrantValidationResult("alice", "some", new Claim[] { new Claim("a", "b" )});
// HTTP 500
```

### Relevant parts of the log file

```
crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: System.ArgumentNullException...
```

**Comment by brockallen** [comment]
Extra claims in the access token should be obtained in the profile service.

**Comment by infinnie** [comment]
Thanks.

**Comment by infinnie** [comment]
May I use multiple profile services within the same application?

**Comment by brockallen** [comment]
> May I use multiple profile services within the same application?

No, we only take a dependency one a single one. If you have multiple DBs, then multiplex from within the one.

**Comment by infinnie** [comment]
@brockallen that would be too bad.

**Comment by infinnie** [comment]
So, how could I mix up all those different profile services and inject all of them into a single one?

**Comment by infinnie** [comment]
And since I would have no access to previously injected instances of the same type, this problem feels more severe to me:

https://github.com/aspnet/DependencyInjection/issues/540 and https://github.com/aspnet/DependencyInjection/issues/340

**Comment by infinnie** [comment]
```cs
public static IIdentityServerBuilder ReplaceProfileService<T>(this IIdentityServerBuilder builder) where T : IProfileService
{
    var type = typeof(T);
    var service = builder.Services.First(s => s.ImplementationType == type);
    builder.Services.Remove(service);
    builder.Services.Add(new ServiceDescriptor(typeof(IProfileService), typeof(MyProfileService<T>), ServiceLifetime.Transient));
    builder.Services.Add(new ServiceDescriptor(type, type, ServiceLifetime.Transient));
    return builder;
}
```

Seems good.

**Comment by infinnie** [comment]
Finally a question: why are custom claim fields not included in the access token? How could I include them?

**Comment by brockallen** [comment]
Look at the UserClaims on the ApiResource and Scope models.
