### ISSUE TITLE
Sub claim from external provider appears encrypted/encoded

### ISSUE THREAD

**Issue by bharaba** [IdentityServer/IdentityServer4#1292]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

Enable google/linked in auth in QuickStart server. The Mvc client sample app will list first name and last name fine but sub is not the unique id from the provider. It also seems to change based on the signing certificate used. Aka dev/temp cert or even after app recycle with a temp cert will change the sub value for the same user.  Auth works marvelously otherwise. Just need the provider id. I'm probably doing something silly.

Thanks in advance

**Comment by bharaba** [comment]
By the way, auth works marvelously otherwise. Just need the provider id. I'm probably doing something silly

**Comment by leastprivilege** [comment]
Our sample UI auto provisions the user and creates a random in-mem subject id. That's what you are probably seeing. If you want to propagate the external subject id - you need to change the sample code - check the account controller `ExternalLoginCallback` method.

**Comment by bharaba** [comment]
Ah of course. Thanks @leastprivilege All set
