### ISSUE TITLE
How to use IdentityServer parameters validation code

### ISSUE THREAD

**Issue by Neku** [IdentityServer/IdentityServer4#1293]
Hi, 
before the actual login page, I have another page where the user make a selection and then all the oauth parameters are forwarded to the authorize.
How do I reuse the code to validate the oauth parameters given that is an internal class in IdenitityServer?
Alternatively how do I put an extra step to be taken on the /authorize endpoint before the login?

**Comment by leastprivilege** [comment]
The login page is the first possible point to inject extra UI. It is then up to you if you really want to show the login page or go back to IdentityServer straight away (by redirecting to the returnUrl).
