### ISSUE TITLE
/connect/userinfo only showing 'sub' profile field for Google Auth

### ISSUE THREAD

**Issue by NickBrooks** [IdentityServer/IdentityServer4#1295]
Hi - I'm trying to follow the Quickstart tutorial and building an IdentityServer that only accepts External Providers (Google for now until I get it working), no built in user store.

The Quickstart tutorial works for me and hitting the `/connect/userinfo` endpoint, I receive `sub`, `family_name` and `given_name`

Creating my own project (using copied code from the Quickstart) I can successfully create the flow and grant access to my API using IdentityServer, however I can't seem to access any of the profile data in either the `/connect/userinfo` endpoint or creating a TestController that returns `User.Claims`, I simply get the `sub`.

My `Startup.cs` code looks like this, is anyone able to point me in the right direction?

```C#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddMvc();

        var connectionString = "connstring";
        var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

        // create RsaSecurityKey
        RSA rsa = RSA.Create();
        rsa.Encrypt(Encoding.UTF8.GetBytes("authkey"), RSAEncryptionPadding.Pkcs1);

        services.AddIdentityServer()
            .AddSigningCredential(new RsaSecurityKey(rsa))
            .AddConfigurationStore(builder =>
                builder.UseSqlServer(connectionString, options =>
                    options.MigrationsAssembly(migrationsAssembly)))
            .AddOperationalStore(builder =>
                builder.UseSqlServer(connectionString, options =>
                    options.MigrationsAssembly(migrationsAssembly)));
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        // this will do the initial DB population
        InitializeDatabase(app);

        loggerFactory.AddConsole(LogLevel.Debug);
        app.UseDeveloperExceptionPage();

        app.UseIdentityServer();

        app.UseGoogleAuthentication(new GoogleOptions
        {
            AuthenticationScheme = "Google",
            DisplayName = "Google",
            SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
            ClientId = "clientId",
            ClientSecret = "clientSecret"
        });

        app.UseStaticFiles();
        app.UseMvcWithDefaultRoute();
    }

    private void InitializeDatabase(IApplicationBuilder app)
    {
        using (var scope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
        {
            scope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>().Database.Migrate();

            var context = scope.ServiceProvider.GetRequiredService<ConfigurationDbContext>();
            context.Database.Migrate();
            if (!context.Clients.Any())
            {
                foreach (var client in Config.GetClients())
                {
                    context.Clients.Add(client.ToEntity());
                }
                context.SaveChanges();
            }

            if (!context.IdentityResources.Any())
            {
                foreach (var resource in Config.GetIdentityResources())
                {
                    context.IdentityResources.Add(resource.ToEntity());
                }
                context.SaveChanges();
            }

            if (!context.ApiResources.Any())
            {
                foreach (var resource in Config.GetApiResources())
                {
                    context.ApiResources.Add(resource.ToEntity());
                }
                context.SaveChanges();
            }
        }
    }
}
```

**Comment by astegmaier** [comment]
Not sure if this is the same thing, but you might have a look at #1285 - adding an implementation of  UserPrincipalClaimsFactory. If it solves your issue, let me know - I'm trying to figure out if it would be useful to add to the docs or not.

**Comment by NickBrooks** [comment]
@astegmaier The blog post you reference is actually something similar to what I had before I embarked on IdentityServer. Just a simple ASP.NET Identity implementation with its own JWT token auth service.

What you have is definitely along the right track, but I'm doing my best to avoid storing my users (credentials at least) at all... I want them to login with an external provider, the provider returns profile details (name, email, avatar/profile photo etc)... the profile details will be stored in the database and updateable through an AccountController but logins will be done through external provider. Just need to somehow get thosse profile details!!

What you have expands on the `ApplicationUser` class which I'm trying to avoid implementing...  See how we go!

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
