### ISSUE TITLE
How can i extend login with additional informations?

### ISSUE THREAD

**Issue by henriqueprj** [IdentityServer/IdentityServer4#13]
My user need to feed some additional informations (his location) after login has already be done with success. But, in idsrv4 i dont found a point to make this extensions. 

There is a way where i can made such thing? In idsrv3 we have partial login do such things.

Any thoughts?

**Comment by brockallen** [comment]
Partial logins are gone because now you are 100% responsible for the UI. You use the various Interaction classes or the action result classes to redirect back into IdentityServer. See the sample host project to get started. Also, details are subject to change :)

**Comment by henriqueprj** [comment]
Ok. Thank you.

**Comment by akamud** [comment]
Is [this](https://github.com/IdentityServer/IdentityServer4/tree/dev/src/Host) the sample you mentioned @brockallen?

**Comment by rh78** [comment]
Is there any more sample code on this? I am planning to port to IdSrv4 but the partial login is gone and I need some hint how to now securely implement that functionality.

**Comment by leastprivilege** [comment]
Just look at our sample UI - and it will be obvious

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI

**Comment by pierslawson** [comment]
@leastprivilege would you say this approach suggested on stackoverflow is suitable?

http://stackoverflow.com/questions/40609585/how-to-do-multiple-step-login-in-identityserver4

He is using a cookie to pass information between steps... I'm just not sure if using the SignInAsync and AuthenticateAsync is appropriate.

**Comment by leastprivilege** [comment]
Looks reasonable


-------
Dominick Baier

**Comment by rh78** [comment]
As a result, I did it the same. Actually it is partial login coded by yourself as the partial login Cookie was no different. If you want I can provide sample code that you can reuse.

**Comment by pierslawson** [comment]
@rh78 That would be good to see. Thank you.

**Comment by c-luu** [comment]
@rh78 @pierslawson share the sample code perchance?

**Comment by rh78** [comment]
@rh78 sorry I have no access to that code anymore. But afairemember you just authorize not using the "full auth cookie" but define a second one which just grants access to a part of your application, not every location. Once all information is present (the information entry will be protected by the partial cookie) you sign in the user using the "full auth cookie".

Also you can check out my framework projects here, maybe you can use some code (it also contains full implementation of UI, controllers, setup etc. but it's part of a larger, very opinionated project (HCore) that I use for my own software as a base foundation):

https://github.com/rh78/HCore/tree/master/HCore-Identity
https://github.com/rh78/HCore/tree/master/HCore-Identity-PagesUI-Classes
https://github.com/rh78/HCore/tree/master/HCore-Identity-PagesUI-Views
