### ISSUE TITLE
Authorization Code Flow

### ISSUE THREAD

**Issue by jkates1** [IdentityServer/IdentityServer4#130]
Is PKCE utilized in the Auth Code grant flow? I tried the other grant types that mention proof key in them explicity, but the only one that round tripped for me was the simplest auth code flow. I had the code challenge and challenge method parameters included in the request.

**Comment by leastprivilege** [comment]
PKCE is not implemented yet.

**Comment by jkates1** [comment]
Any ballpark on an ETA? Thanks.

**Comment by leastprivilege** [comment]
In the next months.
