### ISSUE TITLE
why IPersistedGrantStore does not work with SQL storage ???

### ISSUE THREAD

**Issue by aaguerra** [IdentityServer/IdentityServer4#1300]
I was following the documentation tutorial and the topic "Using EntityFramework Core for configuration data" indicates that the configurations can be stored in the base, but the problem is that following the documentation the only thing that works for me are the configurations of client, scope, user.

the Storage of the PersistedGrant when the application is deployed, is still handled in memory

How do I make the IPersistedGrantStore not to be handled in memory??

If someone owns in a git repository an implementation of the IPersistedGrantStore that can facilitate me would be very helpful.

**Comment by scottbrady91** [comment]
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/Startup.cs#L34

**Comment by aaguerra** [comment]
Using the QuickStarts example, the DB table PersistensGrand always passes empty even though users log in and ask for a token in the application
![image](https://user-images.githubusercontent.com/3911350/27987193-2883ce32-63cf-11e7-8109-fd7c22d17874.png)

How is the acces_token stored in the SQL database?

**Comment by scottbrady91** [comment]
Only reference tokens, user consent, authorisation codes, and refresh tokens are stored in this table. If you're sending out the full JWT then you won't see the access token in this table.

**Comment by aaguerra** [comment]
If I want to do load balancing
How do you configure two IDENTITYSERVER4 servers to serve the tokens in either?

**Comment by leastprivilege** [comment]
open a new issue if the docs are missing what you need.
