### ISSUE TITLE
How can to validate token both header and Url

### ISSUE THREAD

**Issue by jackyphuong** [IdentityServer/IdentityServer4#1302]
Hello, currently, I am using ID4 with .net core and Angular 4. I need to configure API to get image to property "src" of img component. It works well if that API allows anonymous. However, if we want to protect that API, we cannot send token to server (in header). So, can we send on header? or have any approach for this situation?

Thanks

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
