### ISSUE TITLE
No matching state found in storage

### ISSUE THREAD

**Issue by jackyphuong** [IdentityServer/IdentityServer4#1303]
Hello,

After sign in successfully, sometime, I meet this issue "No matching state found in storage". It happen when we call "SignInRedicrectCallback". Could you please let me know what I am wrong? I am using asp.net core, angular 4 and based on OIDC client sample.

Cheers,

**Comment by brockallen** [comment]
I'd search the archives in the oidc-client issue tracker.

**Comment by borisGong** [comment]
hi ，how to fix this issue , i also meet this issue
