### ISSUE TITLE
[Question] - OpenId Url

### ISSUE THREAD

**Issue by deinok** [IdentityServer/IdentityServer4#1304]
I have been searching for the OpenId Url of a server running IdentityServer4
I have also search it in the docs.

So, is IdentityServer4 implementing this part of OpenId?

**Comment by TomCJones** [comment]
Not sure what you are looking for.  Identity Server 3 & 4 are certified here:
http://openid.net/certification/
Perhaps you mean that they are not an identity server?
That is your job.

**Comment by deinok** [comment]
Im asking for something like the habiltity to login to [MyGet](https://www.myget.org/Sts/OpenId/Login/?wa=wsignin1.0&wtrealm=https:%2f%2fmyget-prod.accesscontrol.windows.net%2f&wreply=https:%2f%2fmyget-prod.accesscontrol.windows.net%2fv2%2fwsfederation&wctx=cHI9d3NmZWRlcmF0aW9uJnJtPWh0dHBzJTNhJTJmJTJmd3d3Lm15Z2V0Lm9yZyUyZiZyeT1odHRwcyUzYSUyZiUyZnd3dy5teWdldC5vcmclMmZBY2NvdW50JTJmTG9naW41) putting the following URL http://steamcommunity.com/openid

**Comment by brockallen** [comment]
OpenID != OpenID Connect
