### ISSUE TITLE
Consider API resource user claims to be accessible via user info

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1306]
IOW, allow user claims to be obtained via user info for an API rather than putting the claims in the AT itself.

This would encourage an API to define their own user claims and associate them with the API scope, but still obtain them dynamically. It will also help discourage APIs from using the user info endpoint for the identity data based on identity scopes that the client is requesting.

**Comment by MatthewGabriel** [comment]
This would seem to make a lot of sense.  I'm building a system at the moment that will have multiple services each with an API.  Services will be developed and added over time.  Each service will define claims that will only make sense to itself, as well as using the generic claims.  I'm intending to make my Identity Server act as a repository for other services to store their own claim types, which will be served to them as and when needed.

Doing this via user info would seem to fit that very well.

**Comment by TomCJones** [comment]
I have been working on the same idea for that is call a attribute provider using the user info end point.

Here is a description I have written. I will be working on demo code in the coming months.
https://wiki.idesg.org/wiki/index.php?title=Identity_Model_Overview#Problem_to_be_Solved

**Comment by brockallen** [comment]
After discussion, reference tokens already solve this. We don't currently update the user claims from the profile service, though, so perhaps that's what this issue should morph into -- a flag on the ApiResuorce, for example, to dynamically fetch the user claims on each call to introspection.

**Comment by jaanclaeys** [comment]
I also thought about this, and indeed user info endpoint seems the wrong place. It is ment for client, and according to OpenID specification it can be an encrypted token for the specific client itself. So in that case the API will not get far with the answer.

Extending the introspection endpoint with configured claims attributes per scope and/or per resource seems the right approach. Maybe even constructing a JWT ID token to put in the response (optionally signed and encrypted).
