### ISSUE TITLE
IdentityServer4 benchmark

### ISSUE THREAD

**Issue by ronkajitsu** [IdentityServer/IdentityServer4#1309]
Would it be possible to see some benchmarks results for IdentityServer4? Has anyone tested it? I I have tried console client with server on localhost and have got around 500 rps on i5-2300 CPU with 12 GB RAM on Linux (and Windows). Is it normal result?

**Comment by leastprivilege** [comment]
We never did benchmarks since most time you spend in extensibility code like database access.

**Comment by ronkajitsu** [comment]
It's ok with Apache Bench (something like that):

> Concurrency Level:      200
> Time taken for tests:   5.848 seconds
> Complete requests:      10000
> Failed requests:        0
> Non-2xx responses:      10000
> Keep-Alive requests:    0
> Total transferred:      2230000 bytes
> Total body sent:        3400000
> HTML transferred:       260000 bytes
> Requests per second:    1710.06 [#/sec] (mean)
> Time per request:       116.955 [ms] (mean)
> Time per request:       0.585 [ms] (mean, across all concurrent requests)
> Transfer rate:          372.41 [Kbytes/sec] received
>                         567.79 kb/s sent
>                         940.20 kb/s total
> 
> Connection Times (ms)
>               min  mean[+/-sd] median   max
> Connect:        0    0   0.9      0       9
> Processing:     6  116  11.6    114     180
> Waiting:        6  115  11.7    114     180
> Total:         15  116  11.4    115     183
> 
> Percentage of the requests served within a certain time (ms)
>   50%    115
>   66%    118
>   75%    120
>   80%    122
>   90%    126
>   95%    130
>   98%    137
>   99%    162
>  100%    183 (longest request)
