### ISSUE TITLE
Username is assigned as subjectId; want to change value server-side

### ISSUE THREAD

**Issue by scionwest** [IdentityServer/IdentityServer4#1310]
I've currently got Identity Server wired up so that when I Post the following, I get back my authentication token containing my claims.

![image](https://user-images.githubusercontent.com/1865693/28001530-1711dd24-64e2-11e7-9d8b-b29ca96b3183.png)

I'm using a grant_type of password for our mobile application (since we own both the app and the back-end). What I noticed though is that the SubjectId is equal to the Username I post with. I've spent the day looking through the IdentityServer4 repo and the IdentityServer4.EntityFramework repositories to see how you are setting that, but haven't been able to find it.

Is there a Store, or a configuration, that I can implement that allows me to take the username given and query the database for the records Id, assigning that Id as the SubjectId? The flow I'm currently using is that the mobile app posts an account registration form to our server and we create the account, inserting it into our database. The app, knowing what the username is at this point, posts to `/connect/token` to get the token that it needs. I could send the AccountId down to the mobile app in the account registration response, but I was hoping that I could just do that translation on the token generation side, similar to my claims and scopes look-ups via the ResourceStore.

Would the recommended approach be to inherit from `DefaultTokenService` and override the `CreateIdentityTokenAsync` method, or is there a different route that is preferred to achieve this?

**Comment by leastprivilege** [comment]
The subject ID is whatever you set in your resource owner password validator.

**Comment by scionwest** [comment]
Ah ok - I didn't realize that. Got my change made, thanks!

**Comment by carlospence** [comment]
The custom resource Owner password validator is only called when using password GrantType, if I use implicit GrantType the IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator is called, thus using the default SubjectId. I want the SubjectId to be the UserGuid instead of the UserId but it is using the UserId by default. I implemented a CustomUserStore.
