### ISSUE TITLE
Support for .NET Core 2 ?

### ISSUE THREAD

**Issue by CESARDELATORRE** [IdentityServer/IdentityServer4#1312]
- [X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Afaik, IdentityServer4 still does not support .NET Core 2.

This is a blocking issue for us (.NET team at Microsoft Corp.) in a project we're working on (microservice reference app) which is currently being migrated from .NET Core 1.1 to .NET Core 2.
https://github.com/dotnet-architecture/eShopOnContainers 

Any update on when IdentityServer4 will support .NET Core 2?
Thanks,

**Comment by TomCJones** [comment]
wow, this is really funny. Microsoft is blocked on the availability of free software!
I guess they could sign up to contribute?

**Comment by brockallen** [comment]
Dup: https://github.com/IdentityServer/IdentityServer4/issues/1055
