### ISSUE TITLE
Is there any an end to end working example for doing windows authentication using identityserver4?

### ISSUE THREAD

**Issue by brikesh987** [IdentityServer/IdentityServer4#1314]
Most of the places refers  to the following links:
http://docs.identityserver.io/en/release/topics/windows.html
https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/tree/release/Quickstart

But these examples doesn't seem to work as is. Can you please point to a better documentation?

**Comment by leastprivilege** [comment]
That's the best docs we have.
