### ISSUE TITLE
Client credentials flow - adding claims adds extra 'client_' prefix

### ISSUE THREAD

**Issue by justinteaw** [IdentityServer/IdentityServer4#1318]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Create client credential client with _claims_ on IdSvr
Claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, "sites.read")
                    }

When I try to do claims authorization in my Resource server
Eval(context.Principal.HasClaim(ClaimTypes.Name, "sites.read"));
It won't work.

Preview the claims of access token on jwt.io
**Expected**: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "read"
**Result**: ""client_http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": "read"

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
https://identityserver4.readthedocs.io/en/release/reference/client.html

search for `prefix`

**Comment by BobBoba** [comment]
Spend a day trying to figure it out. When I had IdSrv4 migration applied `1.5.2` -> `2.3.0` column `ClientClaimsPrefix` successfully created with default value of null which will be used by IdSrv to prefix claims.
So, IdSrv clients expected to get prefixed claims but got raw ones.
Dear @leastprivilege , can you please modify migration which will fill `ClientClaimsPrefix` field with `client_`  value by default? It might help people in future.

**Comment by leastprivilege** [comment]
If you think this is a bug, please open a new issue.

**Comment by BobBoba** [comment]
No, no, I'm not sure this is a bug. Just posted my 5 cents for users who'd face this problem in future.

**Comment by babin93** [comment]
> https://identityserver4.readthedocs.io/en/release/reference/client.html
> 
> search for `prefix`
This page does not exist.
