### ISSUE TITLE
"Parameter count mismatch." exception, Even passing full parameter in RequestResourceOwnerPasswordAsync

### ISSUE THREAD

**Issue by llmsjraj** [IdentityServer/IdentityServer4#1319]
var tokenResponse = await tokenClient.RequestResourceOwnerPasswordAsync(model.Username, model.Password, null, model.Code, default(System.Threading.CancellationToken));

i am getting "Parameter count mismatch. Exception". please tell me how can i call this method.

I have to pass extra: parameter in this method which is of object type.

**Comment by llmsjraj** [comment]
![err](https://user-images.githubusercontent.com/22942645/28084637-db029fd8-6696-11e7-8fc4-5fc4b41a87a3.png)

please error details.

**Comment by leastprivilege** [comment]
still an issue?

**Comment by llmsjraj** [comment]
No, it has been resolved. Actually it's confusing to understand what is expected type to pass in extra parameter. Because it's an object type and i was passing the string. But expected type is Dictionary.

var extra = new Dictionary<string, string> { { "Key", "Value" } };

this is how i got success. 

But, I want to ask another question  leastprivilege . Currently i have implemented "ResourceOwnerPassword" grant type  to issue the token . I just have one method "GetToken" in my IdentityServer project. and i protected all my api's  which reside in others visual studio solution( i mean hosted on other server). it work perfect.

But now, i have to implement third party login too like "Google, facebbok etc...".  So How can i implement this . as i have used  "ResourceOwnerPassword" grant type.

please help ...
