### ISSUE TITLE
Can't verify JWT token in node js and online JWT validator

### ISSUE THREAD

**Issue by dmigo** [IdentityServer/IdentityServer4#132]
There is a token:
`eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMDEvcmVzb3VyY2VzIiwiZXhwIjoxNDY2MTc1MDI1LCJuYmYiOjE0NjYxNzE0MjUsImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjoic29tZS1zY29wZSIsInN1YiI6ImZpcnN0LW9uZSIsImF1dGhfdGltZSI6MTQ2NjE3MTQyNCwiaWRwIjoiaWRzcnYiLCJhbXIiOlsicGFzc3dvcmQiXX0.CWwpcmY6UUm-vGs9668BOaYuWTaZYvhh3N-yTXYcC7B0J25cnJcYDKJeLKMc06mcVC_1UpyzB4cLbKnlxbmU0dlnA20p88OImKrA9P28aPwITeMub2g5Gu9eTwGoJmyzsdMEAfakKzo7awd0XbLviakKb8NpF9mgkquipnmibdiLiLYnz91lSVt7xD2q4snK_QW4sbEa5Ujwv_Q2o1Y6aY5RDx3G5RHPI40jbAF8I5AaHXZIDlviFVCCqoTCHSUD4rixTnZG9zEc7OgGI5cjXY2E0_XEhw2JDN-7JJcCBMPdm6fj64OCDbXlrnkFhtH0TtcC82_lg0Z60j4xQF9P5w`  
The secret that was used is `some-scope`.

It can be easily verified in .net code, but not in nodejs (I use express-jwt). 
[https://kjur.github.io/jsrsasign/tool_jwtveri.html](Online Verifier) says it is invalid as well.

What am I doing wrong, where might be the problem?

I can add some code or data from my DB if it'll make things clearer.

**Comment by leastprivilege** [comment]
Not an IdSrv question.

**Comment by dmigo** [comment]
@leastprivilege I forgot to mention that the token is produced by IdentityServer4. Does this change anything?

**Comment by leastprivilege** [comment]
no ;)

According to jwt.io, this toke looks good. You need to learn the node.js side.

**Comment by dmigo** [comment]
@leastprivilege but it says:

> Invalid Signature

**Comment by leastprivilege** [comment]
did you insert your keys?

**Comment by dmigo** [comment]
@leastprivilege  I've tried to use `some-secret` which is the secret in my case

**Comment by leastprivilege** [comment]
no. For jwt.io to validate it you need to paste in the signing key.

I wouldn't worry about that - I can guarantee the token is valid ;) Learn how to use the validation library instead.

**Comment by dmigo** [comment]
@leastprivilege  Ok, I'll try to figure this out. Thank you for your time!
