### ISSUE TITLE
Custom grant page

### ISSUE THREAD

**Issue by joaomello** [IdentityServer/IdentityServer4#1320]
Hi! I was reading this issue https://github.com/IdentityServer/IdentityServer4/issues/166
And found a case when the users login, I verify he can has access to more then one "directory/tenant/global permission" and need the user to specify which. To not implement this verification on ever client, I would create custom grant page for this situation, where he can select in which to use. Is this viable/right?

**Comment by TomCJones** [comment]
normally in OpenID Connect it is the consent page from the OP that allows the user to select the claims to present.


________________________________

**Comment by joaomello** [comment]
But in this case, he will have to choose the "value of claim". Based on his configuration.

**Comment by joaomello** [comment]
It's like to let user choose what scope he wants to access, and them add this claim to the token (like a sub-group of the tenant)

**Comment by brockallen** [comment]
> I verify he can has access to more then one "directory/tenant/global permission" and need the user to specify which

I don't follow what this means.

**Comment by leastprivilege** [comment]
Since you are in control of the UI workflow, you can present whatever screen you want. If you want to preserve data from there (e.g. a tenant ID), put that into the signin cookie. From there you can retrieve it in your profile service.
