### ISSUE TITLE
Token in Reverse Proxy

### ISSUE THREAD

**Issue by TiffFreedomLin** [IdentityServer/IdentityServer4#1321]
With Kestrel, when we pass the ClientID and the secret, we get the token. And with that token we are able to call our webapi to get the response. But when set up with reverse proxy using IIS,  we can get the token and it works for the first about 10 seconds to any call with that token. After that, the token is no longer available and we get the 401 unauthorized on the calls. Are there any configurations or parameters that we need to set differently for reverse proxy?

Any help is greatly appreciated!

**Comment by leastprivilege** [comment]
still an issue?

**Comment by brockallen** [comment]
Closing for now. Reopen if you have any updates.
