### ISSUE TITLE
Using mutitenancy with identity server 4

### ISSUE THREAD

**Issue by rpundlik** [IdentityServer/IdentityServer4#1322]
We are trying to use saaskit(multitenancy project) with Identity Server 4 to make multi-tenant application using Identity Server.

Our requirement is as follows.

We have common login page for all clients. However, once client user will get logged in, we are showing the client list to which user has access and on click of client name user will be redirected to respective clients dashboard.

To achieve this we have used below kind of approach.

1. Login, client list page added in Identity Server project.
2. When user clicks desired client, it will be redirected to client project(Here we have already set the dashboard url to client).
3. In client project based on url(For e.g. clientname/home/dashboard) we are resolving the client using saaskit.
4. We have 2 DBContexts, one is to get the tenat info from Management DB and second is TenantContext which will work on Client DB.
5. All clients and there users are stored in Management DB.

### Issue / Steps to reproduce the problem
4. So now it is supposed to show the dashboard page, however we have added `**[Authorize]**` attribute to the dashboard method because of this it is trying to call `account/login` method. 
But here, the method is not called from server project instead it is searching in client project(which is NOT available, it is written in server project) and resulting into error. Also, it is trying to append ReturnUrl of dashboard to it.

Thanks for the help !

**Comment by leastprivilege** [comment]
> once client user will get logged in, we are showing the client list to which user has access and on click of client name user will be redirected to respective clients dashboard.

This is not how it works - the redirect_uri is fixed - do the redirect and "has access to" logic in the client.

**Comment by brockallen** [comment]
Closing for now. Reopen if you have any updates.
