### ISSUE TITLE
Have a claim in identity resource and not in api resource

### ISSUE THREAD

**Issue by merijndejonge** [IdentityServer/IdentityServer4#1323]
Hi,
I want to achieve the following:

I have an web application that accesses a remote web api that requires authentication. I've setup identityserver4 with ResourceOwnerPasswordAndClientCredentials  grant types Authentication works and accessing the web api also works.

Now I need some user information (e.g., the user's email address) _only_ in the web application. This information must not be exposed to the web api. It should therefore _not_ be present in the claims of the authenticated user at the remote web api.

I've created an ApiResource with a scope that contains the claims that are needed at the remote web api. I've _not_ included this "email" claim there, again, because it shouldn't be exposed to the web api. I've also created an IdentityResource which _does_ have the "email" claim defined (in the list of UserClaims).

Unfortunately, the email claim does not arrive at my web application. It seems that only if I also add  the claim to the claims of scope of the ApiResource the claim is available in the web application. The problem now is that it also becomes available at the remote web api.

In [#678] and [#683] seem related. E.g., I've implemented profile service, but in the GetProfileDataAsync how can I make sure that the claim is included in an id_token and not in an access_token?

Is what  want at all possible?
Any suggestions about what I'm otherwise doing wrong?

Thanks in advance.

**Comment by leastprivilege** [comment]
You are looking for an identity token, but your are using the wrong flow - resource owner does not give you an id_token.

**Comment by brockallen** [comment]
Closing for now. Reopen if you have any updates.
