### ISSUE TITLE
Access token after logged in

### ISSUE THREAD

**Issue by a513091a** [IdentityServer/IdentityServer4#1324]
I am trying to build a Facebook login function with native Facebook sdk.
I call the api with Facebook token and user id to verify and login identity server account but I cannot get the token after logged in.

Here is my step for verification:
1. Get Facebook email using Facebook access token and user id;

2. Verify email with Database;

3. Sign in Identity server;

Here is my code for verification

        [HttpPost]
        [AllowAnonymous]
        public async Task<string> GetTokenForIOS(FacebookUserModel model)
        {
            model.email = await GetEmail(model);
            var user = await _userManager.FindByNameAsync(model.email);
            if (user != null)
            {
                // sign in identityServer
                await _signInManager.SignInAsync(user, isPersistent: false);

                var externalAccessToken = await _userManager.GetAuthenticationTokenAsync(user, "IDV4", "access_token");
               
                string token = await GetAccessToken();
                return token;
            } else {
                FacebookUserInfoModel infoModel = await GetFacebookUserInfo(model);
                ...
                // sign in Identity Account after registration

                // return token;
            }
            return "";
        }

Here is my code for getting token

        public async Task<string> GetAccessToken()
        {

            // discover endpoints from metadata
            var disco = await DiscoveryClient.GetAsync("https://localhost:44355");

            // request token
            var tokenClient = new TokenClient(disco.TokenEndpoint, "client.ios");
            var tokenResponse = await tokenClient.RequestClientCredentialsAsync("api");

            if (tokenResponse.IsError)
            {
                Console.WriteLine(tokenResponse.Error);
                return "";
            }
            else
            {
                Console.WriteLine(tokenResponse.Json);
                JToken jObject = tokenResponse.Json;
                return tokenResponse.Json.ToString();
            }
        }

Here is my client config:

        new Client
               {
                   ClientId = "client.ios",
                   RequireClientSecret = false,
                   ClientName = "iOS app client",
                   AllowedGrantTypes = GrantTypes.Code,
                   RequirePkce = true,
                   //AllowAccessTokensViaBrowser = true,
                   RequireConsent = false,

                   RedirectUris = { "net.openid.appauthdemo:/oauth2redirect" },
                   PostLogoutRedirectUris = { "net.openid.appauthdemo:/oauth2redirect" },
                  
                   AllowedScopes =
                   {
                       IdentityServerConstants.StandardScopes.OpenId,
                       IdentityServerConstants.StandardScopes.Profile,
                       IdentityServerConstants.StandardScopes.Email,
                       IdentityServerConstants.StandardScopes.Phone,
                       "api"
                   },
                   AllowOfflineAccess = true
               }

**[2017-07-14 UPDATED]**
Here is my code for calling Facebook API:

         public async Task<FacebookUserInfoModel> GetFacebookUserInfoAsync(FacebookUserModel model)
        {
            TaskCompletionSource<IRestResponse> taskCompletationSource = new TaskCompletionSource<IRestResponse>();

            RestClient client = new RestClient("https://graph.facebook.com/v2.4/me?access_token="
                + model.access_token + "&fields=email,name,first_name,last_name,gender,timezone,age_range,link,locale");

            var request = new RestRequest(Method.GET);
            request.AddHeader("Accept", "application/json");

            client.ExecuteAsync(request, r => taskCompletationSource.SetResult(r));

            RestResponse response = (RestResponse)(await taskCompletationSource.Task);

            if (response.StatusCode == HttpStatusCode.OK && response.ContentType.Contains("application/json"))
            {
                if (response.Content != null)
                {
                    var info = JsonConvert.DeserializeObject<FacebookUserInfoModel>(response.Content);

                    return info;
                }
            }

            return null;
        }

The token response for access_token always is null. How can I get or generate the user access token with the user information for response or it's impossible to get token here?

**Comment by brockallen** [comment]
I'm confused -- how does the FaceBook API have anything to do with IdentityServer?

**Comment by a513091a** [comment]
I use the token to get the FaceBook user information such email to verify the email with email in DB.
If the email is existed then use the userManager sign in method. If not then to use the FaceBook user information to register a new account via userManager sign up method.

The major reason is I want to use native FB sdk to do FB login and then sign in IdentityServer to get tokenResponse to login my back-end service account through AppAuth. In your view, is it possible?

**Comment by TomCJones** [comment]
did you put "email" in the "scope"?
I know on Google you need to add to registration to get email.

**Comment by a513091a** [comment]
I passed the FB access_token and userId as model to be parameter.
I can call the in FB api https://.../me?fields=email&access_token the GetMail method to get the user email for verification.
In this case, I want to get the user token response after logged in IdentityServer .

**Comment by a513091a** [comment]
The below steps are my Facebook Login flow:

In Mobile:
1. iOS native Facebook login;

2. retrieve Facebook response then call api with Facebook access_token and userID

In IdentityServer:
3. retrieve Facebook access_token and userID then call Facebook user email via Facebook API with access_token;

4. retrieve Facebook user email then verify the email.

5. if email is existed, sign in the email's owner account of IdentityServer;

6. get token response then return to mobile app;

In Mobile:
7. retrieve the IdentityServer token response and then save to stateAuth of AppAuth;

8. use AppAuth login back-end server;

This flow only shows the normal Facebook login successfully. Some checking such as local login/Facebook login, login/registration and get Facebook information is success or not are not considering.

**Comment by brockallen** [comment]
All set on this issue? Can we close?
