### ISSUE TITLE
Consider adding extensions methods for adding ext providers with display names

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1327]
...so users don't need to use "workarounds" like 

`services.Configure<AuthenticationOptions>(o => o.SchemeMap["OIDC"].DisplayName = whatever`

..after all that display name is used to dynamically populate the login UI (as it was supposed to be used)...

**Comment by TomCJones** [comment]
I am running into that problem on aspnetcore 1.x.
There seems to be no display name for the IDP in the client.
Have you seen this problem?  (only happens on dynamic registration.)
..tom

**Comment by leastprivilege** [comment]
OK - MS added the feature back due to popular demand ;)

https://github.com/aspnet/Security/pull/1320
