### ISSUE TITLE
AspNet Identity and Identity Server 4

### ISSUE THREAD

**Issue by DoubleExposure** [IdentityServer/IdentityServer4#1328]
I am a little confused. In ID3, the client would route you to the ID Server's login page. e.g Quickstart login.
With AspNet Identity4 does it still route you to the ID4 Server's Login page?
Right now, if I try to call a page protected by the [Authorize] it routes me to a page with the error message  **unauthorized_client**.
Shouldn't it route me to the ID server 4's login page (Quick Start GUI)?
I need to have this routing to ID4's login page in order to authenticate the user ID and password using MultiTenant approach.
I need to be able to get the domain name, which I have, and then determine based on the domain name which ASPNETUSER table to log into. 
how is ID4 doing this authentication after the client portal routes you back to the the ID4 server?

**Comment by brockallen** [comment]
Do the samples not work for you? We no longer have a UI in IdSvr4 -- perhaps watch our NDC video on what's new in IdSvr4?

**Comment by brockallen** [comment]
So after I just wrote my reply, I actually have no idea what you're asking. What's ID3 and ID4? ASP.NET Identity, or IdentityServer?

**Comment by DoubleExposure** [comment]
ID3 and ID4 Identity Server3 versus Identity Server 4.
I added the Quickstart GUI to the IdentityServer 4 server but it appears that this routing is no longer the same.  Should the AspNet Identity web portal route to it's own login form now instead of to the Quickstart version that was found in Identity Server 3?

**Comment by DoubleExposure** [comment]
I want the user to login to his portal, and based on the domain name, I will use ResourceOwnerPasswordAuthentication, formerly UserService to connect to the proper portal's ASPNETUSER account in the database to authenticate the user and then return a token.

**Comment by DoubleExposure** [comment]
I guess that the RedirectURI can point to the ID4 GUI page but is this the proper approach?
The idea is that I can have many portals but authentication is managed by one single ID4 server.

**Comment by DoubleExposure** [comment]
Ok, I cam across the following:

http://docs.identityserver.io/en/release/quickstarts/6_aspnet_identity.html#refaspnetidentityquickstart
