### ISSUE TITLE
Manually trigger full signout from federated (saml2) authentication middleware

### ISSUE THREAD

**Issue by david-ernstsson-stratsys** [IdentityServer/IdentityServer4#1329]
### Case
- We have a middleware for external idp authentication using saml2.
- Signout triggered by our idsrv/client works fine
- Signout triggered by external saml2 idp not quite sure best approach

Basically we have a saml2 authenticationhandler where we get an incoming valid slorequest from user's external idp. We would then of course want to make sure that we do everything we can (working federated signout can truly be tricky in all browsers, especially using a protocol such as saml2) to make sure user is signed out from both our idp as well as any clients. What to do?

### Attempts
1. `await Context.Authentication.SignOutAsync() ` - Does not signout user from clients, seems to do quite abit of cleanup though which is nice
2.            

```
var logoutId = await _interactionService.CreateLogoutContextAsync();
            var userInteractionOptions = _identityServerOptions.UserInteraction;
            var logoutUrl = Context.GetIdentityServerRelativeUrl(_identityServerOptions.UserInteraction.LogoutUrl);

Response.Redirect(logoutUrl);
```

This might be working nice if not for the fact that we then later get stuck on 'ShowLogoutPrompt' because we do not have a client. Since we have already validated that the slosignout request is valid there should be no need for this check (not to mention the whole request might be hidden inside an iframe), how can we avoid this?

### Question
How to trigger a full signout from middleware/authentication handler where we have already validated signoutrequest?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
