### ISSUE TITLE
Want to grant 'profile' but not include in JWT

### ISSUE THREAD

**Issue by spragchris** [IdentityServer/IdentityServer4#1330]
(TL;DR is it possible to have a profile service but not include profile data in the JWT?)

Hello, I'm implementing Oidc using ID4 and would like to keep my JWT small by only including base information, but would like to offer enhanced data for authorisation purposes for downstream clients to use. So my authorization code flow looks similar to this:

1) ask for token granting openid and profile
2) receive id token and exchange for access token
3) store token in server state for logged in user to use in down-stream services
4) retrieve profile information and store in server state for client application authorisation decisions

Firstly, I can't seem to separate the profile data from the JWT at the 3rd point. I can either get the profile data in the JWT or disable profile data entirely at ID4. Is it possible to do what I'm trying to do?

Secondly, is this an appropriate way to retrieve application level authorisation data? Is there a supported channel for this in ID4, or should I implement my own service to suit this need?

**Comment by leastprivilege** [comment]
read this first 

https://leastprivilege.com/2017/07/10/authorization-is-hard-slides-and-video-from-ndc-oslo-2017/

**Comment by spragchris** [comment]
Thanks but a cursory glance indicates it's not exactly direct to the point I'm asking. Can you give me some context regarding your recommendation that I read this? Are you suggesting I watch a video on authorisation in general?

**Comment by spragchris** [comment]
I think I regret mentioning authorisation in my question, as that's not really what I'm interested in. Specifically, I really just want to know if I can have profile data come back on userinfo endpoint, but not be in the JWT from the token endpoint.

**Comment by spragchris** [comment]
For posterity:

I believe the correct use of the Profile Service is intended to be as a means of extending the access_token, and not a framework for designing a profile service as a resource, which could be done in business level APIs.
