### ISSUE TITLE
Getting error if removed TestUserStore _users

### ISSUE THREAD

**Issue by Iamguy84** [IdentityServer/IdentityServer4#1336]
Hi folks,
I was following the docs https://github.com/IdentityServer/IdentityServer4.Quickstart.UI and only windows authentication (Not another provider such as google )
In AccountController:
```
//private readonly TestUserStore _users;
.......
.......
var user = _users.FindByExternalProvider(provider, userId);  // Error: The name '_users' does not exist in the current context
.......
.......
await _events.RaiseAsync(new UserLoginSuccessEvent(provider, userId, user.SubjectId, user.Username));
await HttpContext.Authentication.SignInAsync(user.SubjectId, user.Username, provider, props, additionalClaims.ToArray());
.......
.......
```
if I do not want TestUserStore then how to **var user = ????**

Or may be **private readonly ???? _users;**

I am waiting for your response 
Thanks in Advance :)

**Comment by leastprivilege** [comment]
You need to replace that code with your own user management library.
