### ISSUE TITLE
Introspection, custom token validation

### ISSUE THREAD

**Issue by mangelarilla** [IdentityServer/IdentityServer4#1337]
Is there any way to customize/extend the introspection endpoint token validation?

In order to consider external data like this user is already logged in on another device so I want to revoke that token on behalf of the new session.

**Comment by leastprivilege** [comment]
Try overriding the introspection response generator. This will be easier though in 2.0

**Comment by mangelarilla** [comment]
Is there a way to access the request from the IIntrospectionResponseGenerator?

**Comment by leastprivilege** [comment]
you could inject the `IHttpContextAccessor`

**Comment by mangelarilla** [comment]
Thank you, I realized late. Overriding the response generator and adding it to the services worked.

I close the issue.
