### ISSUE TITLE
Throws 401 error before expiration time

### ISSUE THREAD

**Issue by zorro-lp** [IdentityServer/IdentityServer4#1340]
Hi, I have a SPA on ASP.NET Core with React+Redux. I'd like user to log in from my site, so I am using resource owner password flow.

People said that: A Single Page Application should not under any circumstances get a refresh token, so I set AccessTokenLifetime as long as possible = 50400 (14 hours).

`new Client {
                    ClientId = "ro.client",
                    AccessTokenLifetime = 50400,
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
                    ClientSecrets = new List<Secret> {
                        new Secret("secret".Sha256())},
                    AllowedScopes = new List<string> {
                        StandardScopes.OpenId,
                        StandardScopes.Profile,
                        "myapi"
                    }
                }`

I am in dev server, so I put DiscoveryClient.Policy.RequireHttps = false; I checked the auth_time and exp claims' value from token response and the difference between auth_time and exp is correct (50400). 
But only after maximum few hours (I don't remember exactly), the fetch call returns 401 error. Do you have any idea why the error happens before expiration time?

Thanks.

**Comment by leastprivilege** [comment]
Check the logs of the API to find out more about why the 401 is returned.

**Comment by zorro-lp** [comment]
I checked Diagnostics logs and it said:
  <Data Name="ModuleName">AspNetCoreModule</Data>
  <Data Name="Notification">128</Data>
  <Data Name="HttpStatus">401</Data>
  <Data Name="HttpReason">Unauthorized</Data>
  <Data Name="HttpSubStatus">0</Data>
  <Data Name="ErrorCode">0</Data>
  <Data Name="ConfigExceptionInfo"></Data>

**Comment by leastprivilege** [comment]
you need the log output from aspnet core - especially the JWT middleware.

**Comment by zorro-lp** [comment]
Hi, I have some more information on the error:
`Bearer error= invalid_token, error_description=The signature key was not found`

`"Bearer" was not authenticated. Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match 'kid': ...`

Does it happen because I call .AddTemporarySigningCredential(); in IdentityServer?

`services.AddIdentityServer()
                .AddInMemoryClients(MyClients.Get())
                .AddInMemoryIdentityResources(MyResources.GetIdentityResources())
                .AddInMemoryApiResources(MyResources.GetApiResources())
                .AddTemporarySigningCredential();`

**Comment by leastprivilege** [comment]
That might be the case yes - either switch to `AddDeveloperSiginingCredential` for dev time - or a proper cert for prod.

**Comment by zorro-lp** [comment]
Thanks, it works.
