### ISSUE TITLE
Signing certificate disappears periodically 

### ISSUE THREAD

**Issue by apacherose** [IdentityServer/IdentityServer4#1348]
The signing certificate that is used for token singing by the IdentityServer, disappears from Computer Store of the machine periodically.

We have configured the server this way:
```
 services.AddIdentityServer()
 .AddSigningCredential(signingCertThumbprint, StoreLocation.LocalMachine, NameType.Thumbprint);
```

Strangely, at some periodic amount of time, that certificate just disappears from the store, where it is installed! So the server cannot access that key and throws exception.

Has someone come across this weird behavior?
It is really annoying because we have to install the certificate every time and give access to the key to app pools, users, etc.

Thank you!

**Comment by leastprivilege** [comment]
Never seen that before.

**Comment by brockallen** [comment]
Closing for now. Reopen if you have any updates.
