### ISSUE TITLE
Not worked refresh token after reboot server

### ISSUE THREAD

**Issue by gromanev** [IdentityServer/IdentityServer4#1349]
Good day. At me such problem, I use authorization on JWT and at me after each server reboot the current refresh of a token does not work.

```
services.AddIdentityServer ()
                 .AddProfileService <LynxProfileService> ()
                 .AddResourceOwnerValidator <LynxResourceOwnerPasswordValidator> ()
                 .AddSigningCredential (IdentityServerConfiguration.GetSigningCertificate ())
                 .AddInMemoryPersistedGrants()
.AddInMemoryApiResources (IdentityServerConfiguration.GetApiResources (AuthConstants.ApiSecret))
                 .AddInMemoryClients (IdentityServerConfiguration.GetClients ());
```

**Comment by leastprivilege** [comment]
`.AddInMemoryPersistedGrants()` means you are storing runtime state like refresh tokens in-memory only. You need to persist them, e.g. 

https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html

**Comment by gromanev** [comment]
And for which you need services.AddScoped <IPersistedGrantStore, LynxPersistedGrantStore> () ?

**Comment by leastprivilege** [comment]
I don't know what Lynx is - we have support for Entity Framework. Or you implement it yourself.

**Comment by gromanev** [comment]
Sorry, 
`services.AddScoped<IPersistedGrantStore, PersistedGrantStore>()`
