### ISSUE TITLE
Make it easier to return errors back to client from login pages

### ISSUE THREAD

**Issue by szubajak** [IdentityServer/IdentityServer4#1352]
Hi,

I have a problem with proper handling external authentication errors.

Our solution works like that:

1) If request comes to our idp with special value (securityLevel) in acr_values, user needs to authenticate using external idp provider.

2) We handle such situation in AuthorizationResponseGenerator by overriding ProcessInteractionAsync. Acr values is readed there from request.AuthenticationContextReferenceClasses. If user is not signed in external IDP, we process it using OpenIdConnectOptions.

if (!currentSecurityLevels.Contains(requestedSecurityLevel.ToString()))
{
	return new InteractionResponse { IsLogin = true };
}

3) Happy path works fine. The problem is, when an error occurs during external IDP round trip. Such situation is handled by OpenIdConnectEvents (OnRemoteFailure or OnAuthenticationFailed).
I can redirect there to error page like:
context.Response.Redirect("/error");
context.HandleResponse();

We don't want to display error page, but process such request once again and return error to our client.

I don't know how to pass info that error has occurred from OpenIdConnectEvents (OnRemoteFailure or OnAuthenticationFailed) to AuthorizationResponseGenerator and return OidcConstants.AuthorizeErrors.LoginRequired to our client.
I'm thinking about passing it in temporary cookie, but I guess it's not proper.
Can you help me with this flow? How should I do it the right way?

Thanks in advance,
Jakub

**Comment by brockallen** [comment]
As of now, yes, this is tricky. I'll leave this open as an enhancement to make it easier.

**Comment by szubajak** [comment]
Thank you
