### ISSUE TITLE
Documentation on IdentityServer4 UserInteraction options

### ISSUE THREAD

**Issue by MovGP0** [IdentityServer/IdentityServer4#1355]
Refers to [Documentation on UserInteraction](https://identityserver4.readthedocs.io/en/release/reference/options.html#userinteraction)

The `UserInteraction` options should be better documented. 

Example: 
```csharp
    options.UserInteraction.LoginUrl = "login";
```

Sets the route to `scheme://hostname:port/connect/login`, while 

```csharp
    options.UserInteraction.LoginUrl = "/login";
```

sets the route to `scheme://hostname:port/login`. Also it is not possible to write ErrorUrl as a clean route. Ie. 

```csharp
.AddIdentityServer(options =>
{
    options.UserInteraction.ErrorUrl = "/error";
    options.UserInteraction.ErrorIdParameter = "/errorId";
})
```
will create the route `scheme://hostname:port/error?errorId={errorid}`, while a route like `scheme://hostname:port/error/{errorid}` is apparently not possible.

**Comment by MovGP0** [comment]
I am also wondering how to reconfigure those routes since I found no suitable documentation: 
```
Account/ExternalLogin
Account/ExternalLogin (callback)
Account/AccessDenied
Home
```

**Comment by leastprivilege** [comment]
For the above suggestions - good catch. Please PR.

All UI routes are under your control and are not an IS concern.

**Comment by MovGP0** [comment]
i think the error route could be implemented in `IdentityServer4.Endpoints.Results.AuthorizeResult.RedirectToErrorPageAsync()` like the following: 

```csharp 
var errorIdParameter = _options.UserInteraction.ErrorIdParameter;
var url = errorIdParameter.StartsWith("/")
                ? (errorIdParameter.EndsWith("/") ? errorUrl + id : errorUrl + "/" + id)
                : errorUrl.AddQueryString(_options.UserInteraction.ErrorIdParameter, id);
```

**Comment by Lutando** [comment]
I ran into this [as well](https://github.com/IdentityServer/IdentityServer4/issues/228)  @MovGP0. If EnsureLeadingSlash() still exists then it would be  cleaner to use that method else you're duplicating that logic

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
