### ISSUE TITLE
Option for adding user claims in the access token missing

### ISSUE THREAD

**Issue by MovGP0** [IdentityServer/IdentityServer4#1356]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I want to send custom user claims with the access token. It should be possible to do so based on the Scope.UserClaims configuration. 

Example: 

**Config.cs**
```csharp
        public static IEnumerable<Scope> GetScopes()
        {
            // other scopes

            yield return new Scope
            {
                Name = "roles", 
                DisplayName = "Roles", 
                Description = "", 
                UserClaims = new[] {
                    @"http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
                },
                ShowInDiscoveryDocument = true,
                Required = false,
                Emphasize = true
            };
        }

        public static IEnumerable<Client> GetClients()
        {
            yield return new Client
            {
                AllowedGrantTypes = GrantTypes.Implicit,
                AllowedScopes = { "roles" },
                AccessTokenType = AccessTokenType.Jwt,
                AlwaysSendClientClaims = true,
                AlwaysIncludeUserClaimsInIdToken = true, 
                AlwaysIncludeUserClaimsInAccessToken = true, 
                // ....
            };
```
What I am expecting here is the `Client.AlwaysIncludeUserClaimsInAccessToken` option, which should enrich the access token with the user claims that are specified in the `Scope` object. This is currently possible by implementing a custom `ITokenService`, but I guess it may work without that.

**Comment by MovGP0** [comment]
Another way would be to use the Access Token in order to get additional user information via the user information endpoint: 

```csharp
    [Authorize("ApiUser")]
    [Route("topsecret")]
    public sealed class TopSecretController : Controller
    {
        private IConfiguration Configuration { get; }

        public TopSecretController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        [HttpGet]
        public async Task Get()
        {
            var accessToken = GetAccessToken(HttpContext);
            if (accessToken == null)
            {
                await WriteResponseAsync("Could not find access token", HttpStatusCode.Unauthorized);
                return;
            }

            var discoveryClient = new DiscoveryClient(Configuration["IdentityServerUrl"]);
            var discoveryResponse = await discoveryClient.GetAsync();

            if (discoveryResponse.IsError)
            {
                await WriteResponseAsync("Could not load discovery document", HttpStatusCode.InternalServerError);
                return;
            }

            var userInfoClient = new UserInfoClient(discoveryResponse.UserInfoEndpoint);
            var response = await userInfoClient.GetAsync(accessToken);

            if (response.IsError)
            {
                await WriteResponseAsync($"Could not access user info ({response.Error})", HttpStatusCode.InternalServerError);
                return;
            }

            var claims = response.Claims;
            if (claims.Any(c => c.Type == "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" &&
                                c.Value == "Admin"))
            {
                await WriteResponseAsync("top secret");
                return;
            }

            await WriteResponseAsync("access denied", HttpStatusCode.Forbidden);
        }

        private async Task WriteResponseAsync(string result, HttpStatusCode statusCode = HttpStatusCode.OK)
        {
            var data = System.Text.Encoding.UTF8.GetBytes(result);
            Response.StatusCode = (int)statusCode;
            Response.ContentType = "text/strings";
            await Response.Body.WriteAsync(data, 0, data.Length);
        }

        private static string GetAccessToken(HttpContext httpContext)
        {
            var accessToken = (httpContext.Request.Headers as FrameRequestHeaders).HeaderAuthorization;
            var token = accessToken.First().Remove(0, "Bearer ".Length);
            return token;
        }
    }
```

However, I can't find the setting that is required to include the user claims. I only then the `sub` claim so far.

**Comment by leastprivilege** [comment]
> public static IEnumerable<Scope> GetScopes()

You are either on IdentityServer3 or a really old version of IdentityServer4

**Comment by MovGP0** [comment]
IdentityServer4 v1.5.2. The latest NuGet package. 

But yes, a newer NuGet package would be welcome. 

The `IEnumerable GetScopes()` is taken from the manual. In practice, I use it to populate the `ApiResource.Scopes`: 

```csharp
        public static IEnumerable<ApiResource> GetApiResources()
        {
            var resource = new ApiResource("api.mydomain.com", "API Server");
            resource.Scopes.AddRange(GetApiServerScopes()); // AddRange is a custom extension method
            yield return resource;

           // other API resources
        }
```

**Comment by leastprivilege** [comment]
OK - so on the scopes you define the claim types you would like to include in the respective token when the scope gets requested.

Those claim types will get passed into the profile service - and the profile service may then return the corresponding values. Is that also your understanding?

**Comment by MovGP0** [comment]
yes. that is the intention.

**Comment by leastprivilege** [comment]
OK - so then it works as expected?

**Comment by MovGP0** [comment]
the intention of the issue is to optionally include the user claim type/value-pairs in the access token, such that the API Resource doesn't need an additional roundtrip to the identity server.

**Comment by leastprivilege** [comment]
I don't follow - this is all done in the profile service. What's your issue?

**Comment by MovGP0** [comment]
I want to save the round trip to the UserInfo endpoint on every request to the API Resource for performance considerations.

**Comment by leastprivilege** [comment]
I understand that - then put those claims into the access token.

**Comment by MovGP0** [comment]
I guess I figured it out: Reference Tokens :-) 
http://docs.identityserver.io/en/release/topics/reference_tokens.html

**Comment by stalek71** [comment]
@MovGP0,
where you able to make custom user claims working at all?
I added JwtClaimTypes.Role to resource scope and I see (in profile service) it sends back role claim,
but I don't see it on MVC (client) side.

Resource config on server side (identityserver4) is like below:  

`new ApiResource("reporting", "Reporting") {  UserClaims = { JwtClaimTypes.Role } }`

The client definition for client on identityserver is below:    
    `    new Client
            {
                AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,

                ClientId = wrc_mvc_ConfigInfo.ClientId,
                ClientName = wrc_mvc_ConfigInfo.ClientName,
                RequireConsent = wrc_mvc_ConfigInfo.RequireConsent,

                AlwaysSendClientClaims = true,
                AlwaysIncludeUserClaimsInIdToken = true,

                ClientSecrets =
                {
                    new Secret("secret".Sha256())
                },

                RedirectUris = wrc_Urls.RedirectUris,
                PostLogoutRedirectUris = wrc_Urls.PostLogoutRedirectUris,
                AllowedCorsOrigins = wrc_Urls.AllowedCorsOrigins,

                AllowedScopes =
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    "reporting"
                },
                AllowOfflineAccess = true
            });
`

The client definition for mvc (on client side) is below:
`JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",

                Authority = _securityModel.Authority,
                RequireHttpsMetadata = false,

                ClientId = "webReportingClient.mvc",
                ClientSecret = "secret",

                ResponseType = "code id_token",
                Scope = { "openid", "profile", "reporting", "offline_access" },
                GetClaimsFromUserInfoEndpoint = true,

                SaveTokens = true,

                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = JwtClaimTypes.Name,
                    RoleClaimType = JwtClaimTypes.Role
                    //NameClaimType = ClaimTypes.Name,
                    //RoleClaimType = ClaimTypes.Role
                }
            });`

I thought also setting **AlwaysIncludeUserClaimsInIdToken** to true makes all custom claims available out of the box in ClaimsPrincipal (in Claims property), but it looks it's not as simple. I added some small factory(provider) to have IPrincipal injected in service classes, but it has 14 default claims only out of the box.

`            // Registration for IPrincipal injections`
`services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();`
`services.AddTransient<IPrincipal>(provider =>`
                                                       `provider.GetService<IHttpContextAccessor>().HttpContext.User);
`


Do you have any working idea for such case? :)

**Comment by MovGP0** [comment]
@stalek71 I did. The trick was to implement a custom `IProfileService`. Unfortunately this is currently not documented. I figured it out by reading the source code. 

This is mostly infrastructure: 
```csharp
    public sealed class UserProfileService : IProfileService
    {
        private ILogger Log { get; }
        private IUserStore Users { get; }
        private IClaimManager ClaimManager { get; }
        private IHttpContextAccessor HttpContextAccessor { get; }

        public UserProfileService(IUserStore users, IClaimManager claimManager, IHttpContextAccessor httpContextAccessor, ILogger<UserProfileService> log)
        {
            HttpContextAccessor = httpContextAccessor;
            Users = users ?? throw new ArgumentNullException(nameof(users));
            ClaimManager = claimManager ?? throw new ArgumentNullException(nameof(claimManager));
            HttpContextAccessor = httpContextAccessor ?? throw new ArgumentNullException(nameof(httpContextAccessor));
            Log = log ?? throw new ArgumentNullException(nameof(log));
        }

        private CancellationToken CancellationToken => HttpContextAccessor.HttpContext.RequestAborted;
```
This is the interesting part: 
```csharp
        public async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            context.LogProfileRequest(Log);

            if (context.RequestedClaimTypes.Any())
            {
                // get the user
                var users = await Users.FindBySubjectIdAsync(context.Subject.GetSubjectId(), CancellationToken.None);

                // get the user claims from Microsoft.Identity (using my custom manager)
                var additionalClaims = ClaimManager.GetAdditionalClaimsAsync(users, CancellationToken);

                // filter the claims 
                // you could do that in the ClaimManager and not return them in the first place
                // but I wanted it to be more obvious what is happening
                var newClaims = additionalClaims.Where(claim => !context.IssuedClaims.Contains(claim));

                // add the caims to the context
                context.AddRequestedClaims(newClaims);
            }

            context.LogIssuedClaims(Log);
        }
```
This is the other method you need to implement
```
        public async Task IsActiveAsync(IsActiveContext context)
        {
            var user = await Users.FindBySubjectIdAsync(context.Subject.GetSubjectId(), CancellationToken);
            context.IsActive = user != null && user.LockoutEnabled == false;
        }
    }
```

**Comment by MovGP0** [comment]
btw: there are at least two schemes for roles: `IdentityModel.JwtClaimTypes.Role` (value: `role`) and `System.Security.Claims.ClaimTypes.Role` (value: `http://schemas.microsoft.com/ws/2008/06/identity/claims/role`). You might want to support both.

**Comment by stalek71** [comment]
Thanks @MovGP0 !
Unfortunately this is what I had implemented already. I see role claim prepared on identityserver4 side, but (somehow?) I don't receive this claim on client side (mvc application). I try to use HttpContext.User casted to ClaimsPrincipal, but scope of claims I see there is just generic and I don't know where to look for the source of the problem :( 
Could you paste the client definition on your side also :) ? Maybe I just use wrong token processor (or something similar)? I provided my client definition above, but I don't see what it could screw up there.
Btw: how do you format your source code to paste here? Do you use some website creating it with proper markdown already :) ?

**Comment by MovGP0** [comment]
@stalek71 this here should make it work: 

**JavaScript Client**
```csharp
yield return new Client
{
    ClientId = "frontend",
    ClientName = "Frontend Server",
    Enabled = true,
    AllowedGrantTypes = GrantTypes.Implicit, // required for JS Clients
    AllowedScopes = { "email", "openid", "roles", "api.mydomain.com" },
    AccessTokenType = AccessTokenType.Jwt,
    RedirectUris = new[]
    {
        "https://client.mydomain.com/"
    },
    AllowedCorsOrigins = new[] 
    {
        "https://client.mydomain.com/"
    },
    AllowOfflineAccess = true,
    AllowAccessTokensViaBrowser = true,
    AlwaysSendClientClaims = true,
    // you might want this to enable and disable functionality in the JavaScript frontend
    AlwaysIncludeUserClaimsInIdToken = true 
};
```

**Resource Server**
```csharp
var resource = new ApiResource("api.mydomain.com", "API Server");
resource.Scopes.AddRange(GetResourceServerScopes());
resource.UserClaims.AddRange(new[] { JwtClaimTypes.Role, ClaimTypes.Role });
```

```csharp
private static IEnumerable<Scope> GetResourceServerScopes()
{
    yield return new Scope
    {
        Name = "roles_api", 
        DisplayName = "Roles", 
        Description = "Allow the service access to your user roles.", 
        UserClaims = new[] { JwtClaimTypes.Role, ClaimTypes.Role },
        ShowInDiscoveryDocument = true,
        Required = true,
        Emphasize = true
    };
}
```

```csharp
yield return new Client
{
    ClientId = "api.mydomain.com",
    ClientName = "API Server",
    Enabled = true,
    AllowedGrantTypes = GrantTypes.Code, // uses the ClientID + Secret to get tokens
    ClientSecrets =
    {
        // use some really long random value here (>16 characters)
        new Secret("l2EwArBmEw1kyjT8RaH1fjxvToz5GWrihxDuE7i6H5bvUFuG9r8sVbo54WftV4cG".Sha256())
    },
    AccessTokenType = AccessTokenType.Jwt,
    RedirectUris = new [] { "https://api.mydomain.com/" },
    AllowedCorsOrigins = new[] { "https://api.mydomain.com/" },
    AllowOfflineAccess = false,
    AllowAccessTokensViaBrowser = false,
    AlwaysSendClientClaims = true,
    AlwaysIncludeUserClaimsInIdToken = true,
    AllowedScopes = new [] { "email", "openid", "roles", "api.mydomain.com" }
};
```

**Comment by MovGP0** [comment]
btw: if you use Angular in the Frontend, you might find this helpful: 


Install [jwt-decode](https://github.com/auth0/jwt-decode): 
```powershell
npm install jwt-decode --save
npm install @types/jwt-decode --save-dev
```

**pipes/jwtdecode.pipe.ts**
```typescript
import { Pipe, PipeTransform } from "@angular/core";
import * as jwtDecode from "jwt-decode";

@Pipe({ name: "jwtdecode" })
export class JwtDecode implements PipeTransform {
  transform(token: string): any {
    if (!token) return token;
    return jwtDecode(token);
  }
}
```

**app.module**
```typescript
import { JwtDecode } from './pipes/jwtdecode.pipe';

@NgModule({
  declarations: [ JwtDecode, /* ... */ ]
  // ...
})
export class AppModule {
  // ...
}
```

**usage**
```html
<pre>{{IdToken | jwtdecode | json}}</pre>
<pre>{{accessToken | jwtdecode | json}}</pre>
```

This way you can easily inspect the tokens.

**Comment by stalek71** [comment]
Thanks @MovGP0,
it looks I have the same settings for server side. The difference is I use GrantTypes.**HybridAndClientCredentials** and don't use oidc-client.js or similar stuff to consume tokens directly on Angular4 level. Instead of this I use provider for app initialization where I prepare config info for Angular app (provide: APP_INITIALIZER). Configuration service uses ClaimsPrincipal to access received token data and OpenIdConnect authentication from asp.net core. I will let you know if I know the way to resolve this problem...

**Comment by stalek71** [comment]
It looks the issue can be on identityserver level yet :(
I don't know why requested claim types doesn't contain claims from **reporting** scope ("role" and "EMDClaim"). Maybe you have seen something like this already?
Do you know what drives the list of requested tokens on the stage shown below? :)

dbug: IdentityServer4.Validation.TokenValidator[0]
      Token validation success
{
        "ValidateLifetime": true,
        "AccessTokenType": "Jwt",
        "ExpectedScope": "openid",
        "Claims": {
          "nbf": 1501669796,
          "exp": 1501673396,
          "iss": "http://localhost:5000",
          "aud": [
            "http://localhost:5000/resources",
            "reporting"
          ],
          "client_id": "webReportingClient.mvc",
          "sub": "f2680725-dbdd-4d88-9b65-fd208570c809",
          "auth_time": 1501669794,
          "idp": "local",
          **"role": "EMDAdmin",**
          **"EMDClaim": "ASClaim",**
          "scope": [
            "openid",
            "profile",
            "reporting",
            "offline_access"
          ],
          "amr": "pwd"
        }
      }
dbug: IdentityServer4.ResponseHandling.UserInfoResponseGenerator[0]
      Scopes in access token: openid profile **reporting** offline_access
dbug: IdentityServer4.ResponseHandling.UserInfoResponseGenerator[0]
      **`Requested claim types`**: **sub name family_name given_name middle_name nickname preferred_username profile picture website gender birthdate zoneinfo locale updated_at**
info: IdentityServer4.ResponseHandling.UserInfoResponseGenerator[0]
      Profile service returned to the following claim types: **name given_name family_name**
dbug: IdentityServer4.Endpoints.UserInfoEndpoint[0]
      End userinfo request
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL6PI3KHU68O" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 134.3073ms 200 application/json

**Comment by stalek71** [comment]
When I commented out filtering of claims in profile service it sent me custom claims to mvc client.
I changed the code like below:
```
// Set issued claims to return
//context.IssuedClaims = claims.Where(x => context.RequestedClaimTypes.Contains(x.Type)).ToList();
context.IssuedClaims = claims.ToList();
```
Set one question still remains open: how to drive requested claims it takes into account user/custom claims also??? 
Maybe @leastprivilege or @brockallen could help us on this explaining how to achieve such goal...

**Comment by MovGP0** [comment]
The filtering is that Identity Server only returns the claims that are requested by the client. 

So I guess that your client does not ask for the all required claims, or the claims are missing in the client configuration (or both).

**Comment by stalek71** [comment]
The client configuration is simple by me:
```
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",

                Authority = _securityModel.Authority,
                RequireHttpsMetadata = false,

                ClientId = "webReportingClient.mvc",
                ClientSecret = "secret",

                ResponseType = "code id_token",
                Scope = { "openid", "profile", "reporting", "offline_access" },
                GetClaimsFromUserInfoEndpoint = true,

                SaveTokens = true,

                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = JwtClaimTypes.Name,
                    RoleClaimType = JwtClaimTypes.Role
                    //NameClaimType = ClaimTypes.Name,
                    //RoleClaimType = ClaimTypes.Role
                }
            });
```
In the Scope config elem I provided "reporting" value that should lead to two custom claims on identityserver. Maybe they are no appended to list of requested claims (somehow?)
Maybe I should provide explicit list of claims related to this client config? You js client has list of scopes only also. It's strange ...

**Comment by MovGP0** [comment]
you probably want to change that to 

```csharp
Scope = { "openid", "profile", "reporting", "offline_access", JwtClaimTypes.Role, "EMDClaim"},
```

except you include `JwtClaimTypes.Role` and `"EMDClaim"` in the `profile` scope: 

```csharp
yield return new Scope
    {
        Name = "profile", 
        DisplayName = "Profile", 
        Description = "Allow access to your user profile.", 
        UserClaims = new[] { JwtClaimTypes.Role, ClaimTypes.Role, "EMDClaim" },
        ShowInDiscoveryDocument = true,
        Required = true,
        Emphasize = true
    };
```

**Comment by stalek71** [comment]
@MovGP0,
I think I found potential source of the problem (I had to look into source code finally). The method shown below (from DefaultClaimsService.cs) doesn't correlate Claims defined in ApiResources with scopes requested by the client. All the info client requested is available in request param, but this code doesn't inspect requested scopes/resources to extract user defined claims from resource definitions...
To be honest I don't know if such logic should be there, but in the case **request.Client.AlwaysIncludeUserClaimsInIdToken** has **true** such inspection (and extraction of the claims) should be there by me...

```
        public virtual async Task<IEnumerable<Claim>> GetIdentityTokenClaimsAsync(ClaimsPrincipal subject, Resources resources, bool includeAllIdentityClaims, ValidatedRequest request)
        {
            Logger.LogDebug("Getting claims for identity token for subject: {subject} and client: {clientId}",
                subject.GetSubjectId(),
                request.Client.ClientId);

            var outputClaims = new List<Claim>(GetStandardSubjectClaims(subject));
            outputClaims.AddRange(GetOptionalClaims(subject));

            // fetch all identity claims that need to go into the id token
            if (includeAllIdentityClaims || request.Client.AlwaysIncludeUserClaimsInIdToken)
            {
                var additionalClaimTypes = new List<string>();

                foreach (var identityResource in resources.IdentityResources)
                {
                    foreach (var userClaim in identityResource.UserClaims)
                    {
                        additionalClaimTypes.Add(userClaim);
                    }
                }

                // filter so we don't ask for claim types that we will eventually filter out
                additionalClaimTypes = FilterRequestedClaimTypes(additionalClaimTypes).ToList();

                var context = new ProfileDataRequestContext(
                    subject,
                    request.Client,
                    IdentityServerConstants.ProfileDataCallers.ClaimsProviderIdentityToken,
                    additionalClaimTypes);

                await Profile.GetProfileDataAsync(context);

                var claims = FilterProtocolClaims(context.IssuedClaims);
                if (claims != null)
                {
                    outputClaims.AddRange(claims);
                }
            }
            else
            {
                Logger.LogDebug("In addition to an id_token, an access_token was requested. No claims other than sub are included in the id_token. To obtain more user claims, either use the user info endpoint or set AlwaysIncludeUserClaimsInIdToken on the client configuration.");
            }

            return outputClaims;
        }
```

**Comment by stalek71** [comment]
I meant such small code modification like below:

```
       public virtual async Task<IEnumerable<Claim>> GetIdentityTokenClaimsAsync(ClaimsPrincipal subject, Resources resources, bool includeAllIdentityClaims, ValidatedRequest request)
        {
            Logger.LogDebug("Getting claims for identity token for subject: {subject} and client: {clientId}",
                subject.GetSubjectId(),
                request.Client.ClientId);

            var outputClaims = new List<Claim>(GetStandardSubjectClaims(subject));
            outputClaims.AddRange(GetOptionalClaims(subject));

            // fetch all identity claims that need to go into the id token
            if (includeAllIdentityClaims || request.Client.AlwaysIncludeUserClaimsInIdToken)
            {
                var additionalClaimTypes = new List<string>();

                foreach (var identityResource in resources.IdentityResources)
                {
                    foreach (var userClaim in identityResource.UserClaims)
                    {
                        additionalClaimTypes.Add(userClaim);
                    }
                }

                // Beginning of modification
                if(request.Client.AlwaysIncludeUserClaimsInIdToken)
                {
                    var claimsToAdd = resources.ApiResources
                        .Where(x => request.Client.AllowedScopes.Contains(x.Name))
                        .Select(x => x.UserClaims)
                        .SelectMany(x=>x)
                        .Distinct();

                    additionalClaimTypes.AddRange(claimsToAdd);
                }
                // End of modification

                // filter so we don't ask for claim types that we will eventually filter out
                additionalClaimTypes = FilterRequestedClaimTypes(additionalClaimTypes).ToList();

```
