### ISSUE TITLE
service interfaces lack cancellation support

### ISSUE THREAD

**Issue by MovGP0** [IdentityServer/IdentityServer4#1358]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
the interface `IdentityServer4.Services.IProfileService` requires async methods, but lacks the `CancellationToken` parameter. This makes it impossible to implement cancellation support. Other interfaces might have the same issue.

**Comment by leastprivilege** [comment]
What would be a real world scenario for cancellation in the profile service? IOW - how would you use  it if we would add it?

**Comment by MovGP0** [comment]
In my case, the custom profile service needs to access a database over the network and there is also a retry policy (with Polly) in place, so the data access can bind the task for a long time. 

However, the Task in the DAL will not get canceled when the cancellation token from the HTTP session is not passed. 

What I want is to cancel the data access/retry policy, when the REST client canceled the session.

**Comment by Mardoxx** [comment]
Interesting, however, does that really matter? Or are you wanting to satisfy a "what if" scenario?

Forgive me if I misunderstand -- For retry cancellation this makes sense -- but only in the very unlikely scenario that: 1. your user logs when your DB is down  2. your retry policy several failures until it gives up (which could last minutes in total until absolute failure) 3. user cancels navigation request within this time.

As for contacting a database -- probably not. As soon as the request to your db has been sent off, it will do the work regardless of whether its calling task has been requested to be cancelled or not. Unless you do, say, several queries and check the cancellation token between them.

To me... The sorts of information that should go in the profile should be very simple. E.g. name, surname, email. Something that is very inexpensive (temporally) to retrieve. If the request for this information fails, I think you'd have bigger issues than worrying about some hanging tasks!

For completeness I suppose it should be added, but I see little value. Perhaps I've misunderstood.

**Comment by MovGP0** [comment]
I had issues with an unreliable connection to the database in development, so even small requests kept failing. Also, it's always a good idea to saveguard all requests to external resources. 

(see also: [Release It! by Michael T. Nygard](https://www.amazon.com/dp/0978739213))

**Comment by brockallen** [comment]
Would it be possible for you to just use the one from the IHttpContextaccessor?

**Comment by MovGP0** [comment]
yes, you can. I personally think it is still a good idea to give the user the control over it and expose the `CancellationToken` on every async method as an optional parameter. 

However, `Microsoft.Identity` also uses the token from the HttpContext per default and there is the possibility to provide your own `CancellationToken`, but it is not obvious to the developer using it. Personally, I think this hidden functionality is a bad thing. 

----

This is how it works in Microsoft.Identity: 

*implicit cancellation token (from HttpRequest)*
```csharp
// not obvious that you can provide the cancellation token = very bad
userManager.DoSomethingAsync(param); 
```

*explicit cancellation token*
```csharp
// definitely not a standard pattern, so most users won't know that it exist 
userManager.CancellationToken = cancellationToken; 
userManager.DoSomethingAsync(param);
```

----

In the TPL library, it was originally designed to provide the `CancellationToken` explicitly. There can still be a fallback to the cancellation token from the `HttpContext`. This way the user can clearly see that she can provide a cancellation token: 

```csharp
// injected from constructor
private IHttpContextAccessor HttpContextAccessor { get; }

private CancellationToken HttpCancellationToken =>
    HttpContextAccessor.HttpContext.RequestAborted ?? CancellationToken.None;

public await Task DoSomethingAsync(CancellationToken cancellationToken = default(CancellationToken))
{
    var cancellationToken = cancellationToken ?? HttpCancellationToken;
    // ...
}
```

**Comment by leastprivilege** [comment]
Not going to happen for 2.0. Maybe in a later version.
