### ISSUE TITLE
Asp.net Core and IdentityServer4 quick start doesn't work

### ISSUE THREAD

**Issue by benaichouchem** [IdentityServer/IdentityServer4#1359]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Following the step by step to create the ID server (https://identityserver4.readthedocs.io/en/dev/quickstarts/0_overview.html#how-to-run-the-quickstart), I get the follow error:

> No storage mechanism for clients specified. Use the 'AddInMemoryClients' extension method to register a development version

Does the documentation need an update or do I have a setup issue?
### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
That page says:

> IdentityServer is not yet ready to be launched. In fact, when you try it, you should see an exception at startup time stating that services are missing. We will add those services in the following quickstarts.

**Comment by leastprivilege** [comment]
continue here:

https://identityserver4.readthedocs.io/en/dev/quickstarts/1_client_credentials.html

**Comment by benaichouchem** [comment]
That explains it, thanks

**Comment by D252874** [comment]
love it when you get old answers to an problem i have and it doesn't work because the page the link is for doesn't exist anymore

**Comment by scottbrady91** [comment]
https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html
