### ISSUE TITLE
Request new Token with specific id, when already authenticated

### ISSUE THREAD

**Issue by Karnich** [IdentityServer/IdentityServer4#1360]
Hi. Question:

I am trying to figure out how i can generate a new token with a different payload based on a user input. I have a working IProfileService which requests a Claims endpoint i created and adds them to the token. Now since we have hundreds of claims and bound to different portfolios which needs to be accessible from different clients. Users can have access to a lot different portfolios where user have different claims. We thought about putting all of it in 1 basket but it would literally mean hundreds of claims in the token. 

So we wish to generate a new token when you switch portfolio. That new token will now contain the claims that are specific to that user, in that portfolio.

Can anyone point me in the right direction?

**Comment by leastprivilege** [comment]
I think you are mis-using the token concept. That sounds to me like application specific data. IOW use IdentityServer for identity and create an API for your app specific data.

https://www.youtube.com/watch?v=EJeZ3YNnqz8&index=5&list=WL

**Comment by Karnich** [comment]
@leastprivilege Nice video. It definitely gave more insight into the second option we considered. The "Api must call external service to figure out if the user can do xx". We really want to avoid that.

So what im working on implementing right now is an endpoint where i can swap my token out if im authorized. The token will contain new claims that are specific to what im working on right now. It might be misuse, you would know better than me :)

But so far it seems like a nice way to solve our problem.
We avoid huge tokens with 100+ claims
We avoid the need for APIs to call external APIs about permissions
We avoid logging the user out
The IdentityServer does basically not know anything about the application specific claims, it just calls an endpoint to retrieve them during token creation.
It enables external partners to control and create their own claims for their system

Im using the IdentityServerTools to create new token. I think im gonna continue down this route and see where it takes me :)  You can close this .. feel free to comment on my solution, even if you dont like it ;)

**Comment by leastprivilege** [comment]
It's fine - have fun ;)
