### ISSUE TITLE
authorize attribute

### ISSUE THREAD

**Issue by asoet** [IdentityServer/IdentityServer4#1361]
I've followed https://identityserver4.readthedocs.io/en/dev/quickstarts/6_aspnet_identity.html and it works with my client. But now I want to add a user via my client via a httpclient.

I have succesfully found the access-token and added it to the header.
But when I have the Authorize attribute it gives me the login page.

I think it doesn't check the bearer token. Is this possible?

**Comment by leastprivilege** [comment]
Not enough data.

**Comment by Mardoxx** [comment]
>succesfully found the access-token and added it to the header
Post code plz.

**Comment by asoet** [comment]
```
 var info = 
_contextAccessor.HttpContext.User.FindFirstValue("AccessToken");
 using (var client = new HttpClient())
{
       client.SetBearerToken(info);
       client.BaseAddress = new Uri($"{_settings.IdentityServerUrl}");
       var response = await client.PostAsync("api/users" + uri, new StringContent(JsonConvert.SerializeObject(req).ToString(), Encoding.UTF8, "application/json"));             
```

This is the code I use on the client side.
The format is `Bearer token_goes_here`

Do you need the code I use for the identityserver side? please specify.

**Comment by MovGP0** [comment]
*"I want to add a user via my client via a httpclient."*

There is no way of doing that with Identity Server. Identity server handles OAuth/OpenID tokens that describe user attributes, but does no user management. 

When you want to create a new user, you need to use another library like [ASP.NET Identity](https://www.asp.net/identity) and write a custom REST service around it for user management. I recommend to implement it as a **separate API Resource** and use Identity Server to issue the access tokens for accessing that API.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
