### ISSUE TITLE
Access Acr values (specifically tenant) in IProfileService and IResourceOwnerPasswordValidator

### ISSUE THREAD

**Issue by davebown** [IdentityServer/IdentityServer4#1363]
Is there any way to access the acr values in an implementation of IProfileService and IResourceOwnerPasswordValidator? If so how? I'm struggling to find any documentation on this.

**Comment by davebown** [comment]
I see that IProfileService can't access the request so i need to generate a claim in the ExternalLoginCallback method of the AccountController. I presume I can get the acr_values from the result of GetAuthenticateInfoAsync method?

In terms of the IResourceOwnerPasswordValidator I assume I can find acr_values using context.Request.Raw.Get("acr_values") ?

**Comment by leastprivilege** [comment]
sounds both good to me ;)
