### ISSUE TITLE
Cannot add new routes to the endpoint router

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4#1364]
Cannot use the `AddEndpoint` in the `BuilderExtensions` due to the use of the `EndpointName` enum.

Endpoints registered by:
```
public static IIdentityServerBuilder AddEndpoint<T>(this IIdentityServerBuilder builder, EndpointName endpoint) where T : class, IEndpoint {
  builder.Services.AddTransient<T>();
  builder.Services.AddSingleton(new EndpointMapping { Endpoint = endpoint, Handler = typeof(T) });

  return builder;
}
```

`EndpointName` is then registered using `Constants.EndpointPathToNameMap`:
```
public static readonly Dictionary<string, EndpointName> EndpointPathToNameMap
```

These are then used in the `EndpointRouter` to figure out the `EndpointName` from the path, and be matched back to the registered endpoint.

But you can't extend an enum, so endpoints outside of the OIDC spec cannot currently be registered.

**Comment by leastprivilege** [comment]
@brockallen e.g. to add saml2p (or ws-fed) endpoints...we should discuss this for 2.0

**Comment by scottbrady91** [comment]
Will this apply to ASP.NET Core 1.x too? Or do you want people to go the controller route for that?

**Comment by brockallen** [comment]
We can do this for 2.0, but 1.x might be too much work... and it might technically be a breaking change.

**Comment by scottbrady91** [comment]
Could we get some extra enum values for 1.x?

**Comment by brockallen** [comment]
You have several: `(EndpointName)(EndpointName.UserInfo+1)` :)

**Comment by brockallen** [comment]
Do we want to allow our endpoints to be replaced? e.g. /authorize, etc?

**Comment by brockallen** [comment]
I think the outcome of our conversation was "no" that's not something we're trying to design for.
