### ISSUE TITLE
unsafe-inline for edge in 

### ISSUE THREAD

**Issue by armitagemderivitec** [IdentityServer/IdentityServer4#1369]
Hi,

I recently ran a Veracode dynamic scan for security validation purposes of our code base. A flaw was picked up of using the 'unsafe-inline' element in a CSP header for the /connect/authorize endpoint which I have traced to the following location:

File: https://github.com/IdentityServer/IdentityServer4/blob/75ac815e744051d8150274743cdd8588eb68abb0/src/IdentityServer4/Endpoints/Results/AuthorizeResult.cs
Line: 126

A comment has been added: 
// 'unsafe-inline' for edge

Could someone explain why this security hole is there for edge and if there any way it can be removed. If it cannot how can I justify it's existence in my security report? 

Many thanks 

Mike

**Comment by Mardoxx** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/475#issuecomment-260225024

I presume

**Comment by armitagemderivitec** [comment]
Thank you Mardoxx, just to be clear does this leave an cross-site scripting vulnerability in older browsers and Edge? Presumably any modern browser using CSP2 uses the hash and is therefore secure?

**Comment by leastprivilege** [comment]
It doesn't mean that there is a XSS vulnerability - it just means that the additional layer of protection via CSP is not supported in certain browsers.
