### ISSUE TITLE
"idsvr" or "idsrv"?

### ISSUE THREAD

**Issue by inongogo** [IdentityServer/IdentityServer4#137]
I was going through the Constants.cs file and found that some of the strings and variables are called "idsvr" and some are called "idsrv". I then searched through the entire repo and found some other places. It seems that "idsrv" is more used than "idsvr"

Is this a typo or is there a reason for it?

**Comment by leastprivilege** [comment]
that's a typo. we'll fix it.

**Comment by brockallen** [comment]
"idsvr" is the right one.

**Comment by leastprivilege** [comment]
maybe we should rename that to local?

**Comment by leastprivilege** [comment]
for the idp i mean

**Comment by brockallen** [comment]
I'm ok with that.

**Comment by leastprivilege** [comment]
done on dev
