### ISSUE TITLE
dotnet core 2.0 cookie authentication uses samesite = lax as default

### ISSUE THREAD

**Issue by pksorensen** [IdentityServer/IdentityServer4#1370]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Set up a client on domain1 and identity server on domain2 and use oidc-client silent sign in.

when the authorize endpoint processes the request the identity is null due to no cookies are present in the request.
https://github.com/IdentityServer/IdentityServer4/blob/aspnetcore2/src/IdentityServer4/Endpoints/AuthorizeEndpoint.cs#L104

Upon investigating a 1.x version of the app running live I found
![image](https://user-images.githubusercontent.com/2718591/28744870-07d47da6-746b-11e7-9204-b8e0d43f71f4.png)
idsrv cookies having none in samesite settings.

Upon investigating a 2.x version of the app running i found that these was changed to lax.

Changing to none for 2.x made the application behave as before.

https://github.com/pksorensen/IdentityServer4/blob/aspnetcore/netstandard/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/Core.cs#L55

**Comment by brockallen** [comment]
We will have to remove the use of same site cookies for 2.0.

**Comment by leastprivilege** [comment]
I set SameSite to none for the main authentication cookie and the session cookie. @brockallen review

**Comment by brockallen** [comment]
Yep, looks good.
