### ISSUE TITLE
invalid redirect URLs

### ISSUE THREAD

**Issue by MovGP0** [IdentityServer/IdentityServer4#1373]
- [X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
* Identity Server 4 (NuGet v1.5.2)
* Log-in via implicit flow: 

```
GET /connect/authorize?response_type=id_token%20token&client_id=frontend&redirect_uri=https://localhost:6001/&scope=openid%20email%20roles&nonce= ... 2&state=... HTTP/1.1
```

* When the login is successful, I get an redirect to an url that looks like

```
https://localhost:6001/id_token= ... &access_token= ... 
```
instead of 

```
https://localhost:6001/?id_token= ... &access_token= ... 
```

### Relevant parts of the log file
no logged error

**Comment by MovGP0** [comment]
the issue seems to be in `IdentityServer4.Endpoints.Results.AuthorizeResult.BuildRedirectUri()`

```csharp 
if (Response.Request.ResponseMode == OidcConstants.ResponseModes.Query)
{
    uri = uri.AddQueryString(query);
}
else
{
    uri = uri.AddHashFragment(query);
}
```

The `AddHashFragment` does not add the missing `?` after the hash.

**Comment by leastprivilege** [comment]
Are you saying that

`redirect_uri=https://localhost:6001/&scope=openid%20email%20roles&nonce= ... 2&state=...`

is your pre-configured redirect URI? and if yes - why?

**Comment by MovGP0** [comment]
the preconfigured redirect url is `https://localhost:6001/`. it is the main route because it is a single page application (SPA). Have the same issue with angular hash routing.

**Comment by MovGP0** [comment]
btw. I solved the above issue by changing the above code to: 
```csharp
if (Response.Request.ResponseMode == OidcConstants.ResponseModes.Query)
{
    uri = uri.AddQueryString(query);
}
else
{
    uri = uri.AddQueryString(query);
    uri = uri.AddHashFragment(query);
}
```
This might not be a proper solution however, because there might be cases where it is wrong and I currently lack the insight about its implications.

**Comment by leastprivilege** [comment]
This is pretty security sensitive code you are changing here.

The page where the redirect URI points to should not be part of your Angular route. Just use a plain html page and from there redirect back to the main app.

**Comment by MovGP0** [comment]
ok. so something like `https://localhost:6001/return.html` and transmitting `https://localhost:6001/return.html?return=https://localhost:6001/#/my/route/back` as the `returnUrl` then? 

```http
GET /connect/authorize
?response_type=id_token%20token
&client_id=frontend
&redirect_uri=https%3A%2F%2Flocalhost%3A6001%2Freturn.html%3Freturn%3Dhttps%3A%2F%2Flocalhost%3A6001%2F%23%2Fmy%2Froute%2Fback
&scope=openid%20email%20roles
&nonce= ... 2
&state=... 
```
Or do I need to use the `state` parameter for that?

**Comment by leastprivilege** [comment]
yep store the "deep link" before doing the redirect to IS - then use a static redirect URI (e.g. "callback.html"). Process the response and then do the final redirect back to the routing system.

**Comment by MovGP0** [comment]
still doesn't solve the issue with the missing question mark before the URL query

**Comment by leastprivilege** [comment]
ah you can't. It's not allowed for JS clients. It mush be a hash fragment. Check the spec.

**Comment by MovGP0** [comment]
Oh. I see. [Section 4.2](https://tools.ietf.org/html/rfc6749#section-4.2) requires the use of the hash fragment. So I need to use `location.hash` to get the parameters and not use Angular Hash Routing.
