### ISSUE TITLE
Windows Authentication Custom page?

### ISSUE THREAD

**Issue by Iamguy84** [IdentityServer/IdentityServer4#1374]
Hi,

Is it possible to custom login page for windows authentication (Intranet application)?

Thanks

**Comment by leastprivilege** [comment]
need more context

**Comment by mackie1001** [comment]
This would suggests yes:

[https://blogs.msdn.microsoft.com/wushuai/2017/06/26/how-to-support-windows-authentication-for-asp-net-core-in-iis/](url)

If you wanted to mix this with some of form of authentication you'd probably need to experiment.

Another option is to use ADFS on Server 2016 as it supports OpenID Connect and works fine with the standard middleware.

**Comment by leastprivilege** [comment]
Sure - we support Windows authN - our quickstart UI has that implemented.

I just don't understand what "custom login page" means in this context.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by takato1314** [comment]
Maybe this is different from what the original author asks for, but for me i am wondering if it is possible to do the following:

1.  Create custom html form page with a username field and password field.
2.  User keys in his/her windows domain account and password into those field and click submit button.
3.  In the backend, somehow use those inputs from user and do windows authentication to verify the login.
4.  Return access token if successfully authenticated.
