### ISSUE TITLE
Add docs for IProfileService

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1376]
We don't seem to have any as of now.

**Comment by MovGP0** [comment]
#1356

**Comment by brockallen** [comment]
Yes, that's what caused me to open this issue.

**Comment by naveddeshmukh** [comment]
Since now the doc is available [here](http://docs.identityserver.io/en/release/reference/profileservice.html), time to close the issue?

**Comment by brockallen** [comment]
Oh yea, thanks!
