### ISSUE TITLE
Correct use of custom SignInManager?

### ISSUE THREAD

**Issue by luis-cortina** [IdentityServer/IdentityServer4#1378]
I'm using IdentityServer 4 with AspNet Core Identity Implementation based on the QuickSamples. I have added a new field to the AspNetUsers Table that acts as a flag that locks out an user based on a Admin decision (I didn't want to use the Lockout field since I want a way to lock out a user regardless of whether he recover his password or not, and is more like a human task to enable this flag)

I created a custom SignInManager so after the user gets signed in, I would check the flag to determine whether to lock the user out or not. 
The issue is:
- If I use the base method to call the signin, and I'm authenticating a MVC Client, the NotAllowed result get's ignored and the MVC client gets authenticated anyway. (I can see in the logs the auth failure)

```
public override async Task<SignInResult> PasswordSignInAsync
(TUser user, string password, bool isPersistent, bool lockoutOnFailure)
    {
        var result = await base.PasswordSignInAsync(user, password, isPersistent, lockoutOnFailure);
         var appUser = user as IdentityUser;
         if (appUser.ManualLockout) 
        {
            return SignInResult.NotAllowed;
        }
         return result;
    }
```

- If I do my own authentication, I mean to check the user and password myself, the user gets properly locked out:

```        public override async Task<SignInResult> PasswordSignInAsync(
            TUser user, string password, bool isPersistent, bool lockoutOnFailure)
        {
            var appUser = user as ApplicationUser;
            var result = await _db.Users
                .Where(
                    u => u.UserName == appUser.UserName && u.PasswordHash == appUser.PasswordHash)
                    .FirstOrDefaultAsync();
           
            if (result == null)
                return SignInResult.Failed;
            
            if (!result.IsBusinessValidated)
                return SignInResult.NotAllowed;
            return SignInResult.Success;
        }
```

This behaviour smells like I'm doing something wrong or using stuff improperly. 
Can you please give me an idea if there's a better way to do this?

Thanks in advance,

Luis

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
