### ISSUE TITLE
Response type not supported: id_token%20token

### ISSUE THREAD

**Issue by chinkan** [IdentityServer/IdentityServer4#1379]
### Issue / Steps to reproduce the problem

I have setup a identityserver4 behind apache proxypass, and I set a client to connect to identityserver to login, and when I want to login and redirect to identityserver, it return `Sorry, there was an error : unsupported_response_type` and I check the log from identityserver it said `Response type not supported: id_token%20token`. How can I solve this problem? Thanks

(Apache has setup let's encrypt ssl cert to support ssl)
(Sorry for my English :) )

### Relevant parts of the log file

```
fail: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Response type not supported: id_token%20token
      {
        "ClientId": "ancs",
        "ClientName": "Asp.net core starter",
        "RedirectUri": "http://localhost:5002",
        "AllowedRedirectUris": [
          "http://localhost:5002"
        ],
        "SubjectId": "anonymous",
        "RequestedScopes": "",
        "State": "15016528580190.5511211529588498",
        "Raw": {
          "response_type": "id_token%20token",
          "client_id": "ancs",
          "redirect_uri": "http://localhost:5002",
          "scope": "openid%20profile%20avatar%20aspnetcorestarterscope%20glsapi",
          "nonce": "N0.446335987731079741501652858019",
          "state": "15016528580190.5511211529588498"
        }
      }
fail: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
      Request validation failed
```

**Comment by leastprivilege** [comment]
The %20 shouldn't be there - maybe you have a double encoding issue on the URL.

**Comment by chinkan** [comment]
Hi @leastprivilege ,

Thanks for your help!

However I have updated my apache config with:
```
AllowEncodedSlashes NoDecode
ProxyPreserveHost On
ProxyPass / http://10.0.0.9:5000/ nocanon
ProxyPassReverse / http://10.0.0.9:5000/
```

but still return this error. And the log still the same.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by chinkan** [comment]
Sorry for late response, it is my fault. That apache setting is work. Thanks for your help!

**Comment by erwin123** [comment]
Hi everyone, I got same error, can anybody explain hows the solution are there?
