### ISSUE TITLE
CSP frame-src issue when set iframe src SignOutIframeUrl in the view.

### ISSUE THREAD

**Issue by singlewind** [IdentityServer/IdentityServer4#1380]
Chrome won't load iframe because the endsession endpoint contains html try to load a client page inside a frame which is different url

**Comment by brockallen** [comment]
This is true if they're mixed schemes (http/https). Might that be the issue?

**Comment by singlewind** [comment]
@brockallen I was thinking it is possible to add a content-security-policy header for endsession endpoint which just specify the frame-src <url>, which is the embedded url.  Do you think whether there is any security concern?

**Comment by brockallen** [comment]
Actually, we'll be making a change related to this: https://github.com/IdentityServer/IdentityServer4/issues/1224

**Comment by brockallen** [comment]
Closing this as dup of #1224
