### ISSUE TITLE
Retrieving Access Token from External Provider

### ISSUE THREAD

**Issue by kenneth-y** [IdentityServer/IdentityServer4#1381]
Hi,
I have configure Microsoft authentication in IS4. Would like to ask if it's possible to retrieve access token for Graph API.

Thanks.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by kenneth-y** [comment]
thanks @brockallen. yep, posted a question in StackOverflow. 
would like to shoot one more question. :) is there some kind of a temporary store for the access token received from Microsoft in IS4? Looked into the OAuthEvents "OnCreatingTicket" in the MicrosoftAccountAuthentication MW. Saw that there is an access token returned and was wondering is it saved by IS4 and will need to retrieve it by accessing thru extension points.
