### ISSUE TITLE
Question:  What is the best approach to use grant type ResourceOwnerPassword , when using from javascript client ?

### ISSUE THREAD

**Issue by sherry-ummen** [IdentityServer/IdentityServer4#1382]
I am not sure if I can ask a question here. If not then please close the issue and I am sorry.

So I have a UI layer which communicates to the Web API . I have a requirement for having username and password for authentication. Now I think identitiyserver javascript lib I cannot use it for this purpose, so I would have to do something custom. But I am not sure what is the best approach in terms of security.

Could you please suggest or point me to right direction. please

Thanks

**Comment by brockallen** [comment]
Resource owner password flow, but there are many downsides (no SSO, no federation, etc).

**Comment by sherry-ummen** [comment]
what is Resource owner password flow ?

Is it what I understood that
1) we POST with username and password to auth server
2) auth server returns the token
3) use this token further for communication

And I assume that this I have to implement it since there is not javascript library by identityserver ?

But now you say that there are many downsides to it, so could you suggest a solution which would satisfy all aspects ?

**Comment by brockallen** [comment]
> what is Resource owner password flow ?

You need to read the OAuth2 and OIDC specs.

**Comment by sherry-ummen** [comment]
ok then you say my understanding is wrong :)

but do you suggest some good practice when designing a system with the requirements i have using identityserver4 ?

**Comment by brockallen** [comment]
Resource owner password flow, but the oidc-client library doesn't implement that flow (since it's not recommended).

**Comment by sherry-ummen** [comment]
ok I think your one liners just say that I should do some more research and ask more specific question :)  I will do that then and get back to you with more specific questions. Thanks for the pointer thou.

**Comment by waqaskhan540** [comment]
@sherry-ummen  I had the exact same problem , If you are using ResourceOwnerPassword flow then one thing is sure that you can't use it directly from the client application (javascript client) coz that will expose your credentials. What I did was , I sent credentials to my API (username,password) and then from the API send request to IdentityServer with additional credentials (client_id,client_secrets and scopes) and get the access_token. hope it will help you. 

you can refer to the sample here : https://github.com/waqaskhan540/IdentityServerExternalAuth/tree/master/Sample
