### ISSUE TITLE
Show login/register inside website. 

### ISSUE THREAD

**Issue by masoud-bahrami** [IdentityServer/IdentityServer4#1383]
I have 4 micro-service front end web site, all of them, use the **IdentityServer4** for Auth management. But I dot't want to **redirect** users to the new URL, for login or register, and then go back to the current web site.
 I want to if one user invoke any action at page x, that he/she has not access to it, **IdentityServer** login page, open in a modal inside page x.

**Comment by GDehnke-Turpin** [comment]
That is a perfect user experience... tick tick...

**Comment by brockallen** [comment]
By default we use XFO to prevent this. You can do a popup.

**Comment by masoud-bahrami** [comment]
Thanks @brockallen Is there an example?

**Comment by brockallen** [comment]
No

**Comment by Mardoxx** [comment]
https://github.com/IdentityModel/oidc-client-js handles login via popup, may point you in the right direction. Can always dissect it to figure out how it does it.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
