### ISSUE TITLE
Implicit flow custom user store

### ISSUE THREAD

**Issue by leo9223** [IdentityServer/IdentityServer4#1386]
I have successfully implemented an authorization server using ResourceOwner flow having custom user store.

But this time I have to implement an authorization server using Implicit flow and I have to have custom user store. I have searched a lot, but I have not found which Interface I have to implement for validating users in Implicit flow?

**Comment by brockallen** [comment]
You do this in the login page that you build.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
