### ISSUE TITLE
Using IdentityServer to protect API only

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [IdentityServer/IdentityServer4#1388]
I'm currently building a website with ASP.NET Core which supports your run of the mill user actions, like profile, a small chat, etc. Doing this with the standard template was easy enough.

Now I want to add an API to it to the page to support a desktop application (since the websites publishes data that can be consumed locally). This API contains user information, that should only be visible to the user, thus it needs to be secured (obviously).

The workflow is as follows:
* The user starts the application and has to login, even if the user is already logged in on the website
* The application send username/password via a HTTPS connection to the website
* The website returns a token to the application with a certain(extendable) lifetime and is stored locally
* Whenever the user requests data, the application sends the token to the server and gets the data if allowed.

Obviously this sounds like a job for JWT and IdentityServer4. However from glancing over the Documentation I'd have to rewrite my website auth flow to support IdentityServer and in turn only JWT are used. Yet I'm totally fine with the cookie based authentication ASP.NET Identity gives me.

Can I use my existing auth flow and use IdentityServer only to secure the api, forcing the user to login even if he is logged in on the website already and ignore potential local cookies on the machine?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
