### ISSUE TITLE
IdentityServer recursive API access

### ISSUE THREAD

**Issue by rbaryolo** [IdentityServer/IdentityServer4#1390]
I have an IdentityServer4 authentication/authorization server for protecting some APIs. From within my IdentityServer4 implementation I need to access at least one of those protected APIs, lets say A. The problem is that I must ask for a Bearer Token inside my IdentityServer4 implementation (ask for a bearer token to myself) to set it in the authorization header for making a request to the API A. Some times in Development environment I need to access the API A in the last part of the startup of my IdentityServer4 implementation, but I can not ask for a token in that situation because IdentityServer4 who is the token provider is not up. I want the API A to be protected because it can be accessed from other clients too. I wonder if there is a workaround in IdentityServer4 for managing these kind of situations. How to handle a situation where IdentityServer4 is a client of itself?

**Comment by brockallen** [comment]
use the tools API: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/IdentityServerTools.cs#L45
