### ISSUE TITLE
IdentityServer4 RC2 - invalid_request

### ISSUE THREAD

**Issue by hmheng** [IdentityServer/IdentityServer4#140]
I'm trying xamarin.forms with identityserver4 rc2. However, no matter how I change the granttype, it still throws me "Invalid_Request" error. It was fine with RC1 IDS4. anyone can help?
my IDS is fine in hybrid granttype with ASP.NET Core RC2 MVC app, but not mobile app.

**Comment by leastprivilege** [comment]
check the logs

**Comment by hmheng** [comment]
i'm sorry, but I couldn't retrieve the log as it is published on azure webapp. is there anyway that I can get the detailed error message?

**Comment by leastprivilege** [comment]
You need to enable logging - not sure how that works for aspnetcore and Azure (we use the standard aspnet core logging facilities) - maybe a question for MS

**Comment by hmheng** [comment]
actually when i set the granttype hybrid for my web client, it works perfectly. But when it comes to my mobile client with implicit, then it just throws me invalid request on ids error page. :(

**Comment by leastprivilege** [comment]
Well - i am not surprised by that. There might be some configuration/request mismatch. Logging will tell you.

**Comment by leastprivilege** [comment]
Configure logging to write to a file or maybe this approach

http://benfoster.io/blog/how-to-use-tracesource-with-azure-diagnostics

or

https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.TraceSource
or
https://github.com/aspnet/Logging/tree/dev/src/Microsoft.Extensions.Logging.EventLog

should be doable

**Comment by hmheng** [comment]
Thanks, I'm trying to set it up. 
Btw, I found an issue when I put responsetype "id_token token" in my implicit client configuration for getting access_token and identity token, iIt shows me that invalid_request error. When I set only "id_token", it is able to capture the identity token.

**Comment by leastprivilege** [comment]
Sure - but you won't solve that problem by just trying out some combinations.

there's another flag `AllowAccessTokensViaBrowser` which must be set to true if you want to deliver access tokens via the front channel.

**Comment by hmheng** [comment]
Thanks bro, you save my day. AllowAccessTokenViaBrowser settings solved the issue.
Is this the new property in Client?

**Comment by leastprivilege** [comment]
yes. 

Now go learn how logging works on Azure and let us all know.

**Comment by hmheng** [comment]
yea, trying.. haha.

**Comment by zngreg** [comment]
where to put AllowAccessTokensViaBrowser on the server or client?

**Comment by leastprivilege** [comment]
It's a client setting

**Comment by zngreg** [comment]
Thanks, i got it.

**Comment by galgodage** [comment]
How can i use identityserver4 with asp.net MVC,  not core. Can i have sample
