### ISSUE TITLE
[Question] How to get the ScopesRequested (List of scopes that were originally requested) in the Custom implementation of IProfileService.GetProfileDataAsync method ?

### ISSUE THREAD

**Issue by manishandankar** [IdentityServer/IdentityServer4#1400]
[Question] How to get the ScopesRequested (List of scopes that were originally requested) in the Custom implementation of IProfileService.GetProfileDataAsync method ?
ProfileDataRequestContext does not have this property.

I need to process some user information based on the requested scopes before returning the additional claims from GetProfileDataAsync Method.

Can you please help on this ?

**Comment by brockallen** [comment]
Our profile service is an abstraction over scopes, so it's not in there (by design).

**Comment by manishandankar** [comment]
Thank you so much. I think I would be able to rely on the RequestedClaimTypes from the context.
