### ISSUE TITLE
Enable Tests for both netcoreapp2.0 and net461

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1401]
* and find full .net framework API for platform abstractions

**Comment by leastprivilege** [comment]
https://github.com/aspnet/Announcements/issues/237#issuecomment-323786938

**Comment by leastprivilege** [comment]
Multi-targets enabled on branch - seems the RSA bug still exists

https://github.com/dotnet/corefx/issues/8688#issuecomment-323927390

**Comment by leastprivilege** [comment]
done
