### ISSUE TITLE
consider using default authN scheme 

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1402]
instead of having our own scheme property on the auth options. might be easier for consuming devs to not have 3 places to change the default.

**Comment by leastprivilege** [comment]
done 

https://github.com/IdentityServer/IdentityServer4/pull/1446

plz review @brockallen

**Comment by brockallen** [comment]
Yep, reviewed it all. I made some tweaks here & there, but all in all looks good. There are more TODOs in the comments for us to go over together before release.
