### ISSUE TITLE
Microsoft.IdentityModel.Tokens problem in beta4

### ISSUE THREAD

**Issue by Tazer** [IdentityServer/IdentityServer4#141]
Hey , 

Just tried out beta4. But getting this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1705	Assembly 'IdentityServer4' with identity 'IdentityServer4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.IdentityModel.Tokens, Version=5.0.0.699, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.IdentityModel.Tokens' with identity 'Microsoft.IdentityModel.Tokens, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	twee.cloud.auth..NETCoreApp,Version=v1.0	C:\@Project\twee.cloud\twee.cloud.auth\src\Startup.cs	51	Active
````

my project.json looks like this:

```
{
  "dependencies": {
    "Dapper": "1.50.0-rc2b",
    "CryptoHelper": "1.0.0-rc2-final",
    "Swashbuckle": "6.0.0-beta9",
    "IdentityServer4": "1.0.0-beta4",
    "StackExchange.Redis": "1.1.604-alpha",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Configuration": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.NETCore.App": {
      "version": "1.0.0",
      "type": "platform"
    },
    "Npgsql": "3.1.4",
    "System.Linq": "4.1.0"
  },

  "tools": {
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

so not sure why I'm getting that error.

**Comment by Tazer** [comment]
Noticed it was the same problem in Samples when I opened them. So to reproduces , just open `MVC and API.sln` and check startup / or try to build:

![image](https://cloud.githubusercontent.com/assets/132698/16392331/ad93f59e-3cab-11e6-8fc3-b3332cf1a5b9.png)

@leastprivilege

**Comment by leastprivilege** [comment]
Open our MVC and API sample and compare.

let me know

**Comment by Tazer** [comment]
@leastprivilege yes I did and got the same problem :)

**Comment by kmaragon** [comment]
The Credential verb changed. But that is trivial. This is less so:

error CS1705: Assembly 'IdentityServer4' with identity 'IdentityServer4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.IdentityModel.Tokens, Version=5.0.0.699, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.IdentityModel.Tokens' with identity 'Microsoft.IdentityModel.Tokens, Version=5.0.0.127, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

Is it possible that the beta4 package was built against that one "preview versions" nuget server that Microsoft has set up so it either directly or indirectly uses a Microsoft.IdentityModel.Tokens that is newer than the newly release 5.0.0 version?

**Comment by leastprivilege** [comment]
having a look

**Comment by leastprivilege** [comment]
https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/

not sure where you have that nuget from - it is def not from us.

Maybe delete your .vs folder and nuget cache

**Comment by Tazer** [comment]
Tried that also. The nuget comes from https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/ cause it has an dependency on it.

![image](https://cloud.githubusercontent.com/assets/132698/16394140/0251171c-3cb4-11e6-9876-16f79ebc80e9.png)

**Comment by kmaragon** [comment]
FWIW that error is not a nuget error. It's a dll reference error. So it could be that System.IdentityModel.Tokens.Jwt has a package dependency on the correct package but a dll dependency on the wrong dll.

**Comment by MasterSkwerl** [comment]
I'm getting the same thing. I just installed 2015 Fresh w/ Update 3 & The 1.0.0 Preview 2 SDK. I created an empty Core WebApp and when I started to pull from the example...got the same error.

**Comment by ericvan76** [comment]
Same problem here.

**Comment by etrafiee** [comment]
same here

**Comment by avoxm** [comment]
Got the same problem as well. This looks like a bug.

**Comment by leastprivilege** [comment]
OK - after deleting my package cache I can repro the problem.

Not sure yet what the problem is. working on it.

**Comment by leastprivilege** [comment]
I published beta4-update1 - give it a try

**Comment by chrisvfabio** [comment]
It works, thanks!

**Comment by etrafiee** [comment]
thanks :)

**Comment by ericvan76** [comment]
What a quick fix! Thanks.
