### ISSUE TITLE
2.0 is targeting netcoreapp instead of netstandard

### ISSUE THREAD

**Issue by galvesribeiro** [IdentityServer/IdentityServer4#1410]
Hey guys, 

I don't if it is intentional but, https://www.nuget.org/packages/IdentityServer4/2.0.0-preview2 is targeting `netcoreapp2.0` instead of `netstandard2.0`. 

Is that correct?

Thanks

**Comment by leastprivilege** [comment]
That is correct - and will be fixed soon.
