### ISSUE TITLE
IRefreshTokenStore requires more context regarding reference type AccessTokens

### ISSUE THREAD

**Issue by null-d3v** [IdentityServer/IdentityServer4#1411]
- ☑ I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

I am writing my own store implementations with a backing service which stores the relevant information in a normalized relational database.

I am encountering great difficulty with IRefreshTokenStore and reference type AccessTokens:
* [ITokenResponseGenerator.CreateAccessToken() will create the reference AccessToken and store it using the ITokenService's CreateAccessToken() and CreateSecurityToken()](https://github.com/IdentityServer/IdentityServer4/blob/release/src/IdentityServer4/ResponseHandling/TokenResponseGenerator.cs#L228).
* [The IRefreshTokenService is only provided the AccessToken from ITokenService.CreateAccessToken(), which has no distinguishing information, i.e. the reference token handle.](https://github.com/IdentityServer/IdentityServer4/blob/release/src/IdentityServer4/Services/DefaultRefreshTokenService.cs#L49)

In the IRefreshTokenStore implementation I have no feasible way of discerning which previously stored reference type AccessToken the RefreshToken is intended to reference.

**Comment by leastprivilege** [comment]
> stores the relevant information in a normalized relational database.

Why?

**Comment by null-d3v** [comment]
I would think that referential integrity would be my own prerogative as an implementation detail.

Operating at scale, an n-tier service is an approachable solution. Full referential integrity within that service affords an extensive set of benefits.

Currently the store interfaces are prohibitive to that, and I cannot see an express reason why they are.

**Comment by brockallen** [comment]
At this point, I don't see us changing this anytime soon as it would be a large breaking change.
