### ISSUE TITLE
Question: Is there any possibility return the access_token with only user object?

### ISSUE THREAD

**Issue by eduardobarbiero** [IdentityServer/IdentityServer4#1412]
I am implementing a functionality, where access_token will be sent via email, in this case I need to generate this token with a logic to authenticate the user when accessing the link passed via email.

```c#
public async Task<IActionResult> GetLink () 
{
  var user = await userManager.FindByEmailAsync("eduardo@test.com.br"); // is active user created
  if (user != null)
  {
    var ident = await userManager.GetAuthenticationTokenAsync(user, "Test", "access_token");
    return Ok(ident);
  }
  return NoContent();
}
```

Based on the research expected would be something like this, but this is not done with persisted data and my model is not allowing this, anyone have any idea how to persist? Or even just return the token?

**Comment by duyvan82** [comment]
i don't think publicly sharing the access_token is a good idea, also the access token is supposed to be short-lived, what if the user reads the email after the access token has expired?

**Comment by eduardobarbiero** [comment]
@duyvan82 thanks for aswering!

It would basically be redirected to re-login. You say that way, I think it makes a great sense to share another form of link, but to actually create an "authenticated session" it is necessary to return from the access_token server... then somehow, even though I share a different token in the email , It will need access_token for all other requests to be made.

**Comment by duyvan82** [comment]
@eduardobarbiero I may not fully understand your requirements and what you're trying to do, but it does sound to me as though you don't need to share the access token at all.
i would just provide them with the link to the secured resource in the email, clicking on the link would either take them to the resource if they've been authenticated or to the login page if they haven't.

upon successfully authenticate themselves, they would get the access token (depending on the oidc flow in use) and they can just use it for subsequent requests.

again, maybe i completely misunderstood your requirements..

**Comment by eduardobarbiero** [comment]
@duyvan82 i think it is a bad behavior not is not acceptable, but, my user dont have a password for access in this case, maybe is necessary using the token or another mode to login. 
It is a very simple flow, this link would be one for a granted action (it will only have read access, basically), and this link will be sent only to a user via email.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
