### ISSUE TITLE
id_token doesn't contain custom claims like user roles when grant type is Hybrid

### ISSUE THREAD

**Issue by zonef** [IdentityServer/IdentityServer4#1415]
I'm using Hybrid grant type and request with response_type = "id_token code"
After getting result i then request for access_token. In my Client application I need end user roles defined in Identity Server, unfortunately id_token contains only predefined claims. However when I remove code from response type i get id_token with all the necessary claims.
what is the preferable way to have id_token with all claims and refresh_token,access_token (I don't need roles here).

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2016/12/14/optimizing-identity-tokens-for-size/
