### ISSUE TITLE
"no client identifier found"

### ISSUE THREAD

**Issue by oferAshkenazy** [IdentityServer/IdentityServer4#1417]
I have been using identity server 4 in our production environment
from time to time I get the following error "no client identifier found" (in windows event log)
I know it is related to how the call to identity server is formed..
I would like to catch that error and log the request with all headers and parameters, it ? is it possible ?

**Comment by leastprivilege** [comment]
not enough info.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
