### ISSUE TITLE
Role based Authorization IS4 JavaScript Client

### ISSUE THREAD

**Issue by radjaxx** [IdentityServer/IdentityServer4#1418]
Hi,
Role Based Authorization with JS client is not working for me :(
Getting 403 error. I cannot google relevant info what to do :(. I assume claims are missing in AccessToken but not sure how to add them there or how to handle them :( . There is plenty of info for MVCClient but JS is missing.

Please would you advise? 
 
    public class Config
    {
        // scopes define the resources in your system
        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Address(),
                new IdentityResource("roles","your roles",new List<string>(){ "role"})
            };
        }

        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource("api1", "My API")
            };
        }

        // clients want to access resources (aka scopes)
        public static IEnumerable<Client> GetClients()
        {
            // client credentials client
            return new List<Client>
            {   
                // JavaScript Client
                new Client
                {
                    ClientId = "js",
                    ClientName = "JavaScript Client",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,
                    Enabled = true,
                    RedirectUris = { "http://localhost:5003/callback.html" },
                    PostLogoutRedirectUris = { "http://localhost:5003/index.html" },
                    AllowedCorsOrigins = { "http://localhost:5003" },
                    AlwaysIncludeUserClaimsInIdToken = true,
                     AlwaysSendClientClaims = true,
                    AccessTokenType = AccessTokenType.Jwt,
                    RequireConsent = false,
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Address,
                        "api1",
                        "roles"
                    },
                }
            };
        }

        public static List<TestUser> GetUsers()
        {
            return new List<TestUser>
            {
                new TestUser
                {
                    SubjectId = "1",
                    Username = "alice",
                    Password = "password",

                    Claims = new List<Claim>
                    {
                        new Claim("name", "Alice"),
                        new Claim("website", "https://alice.com"),
                        new Claim("address","2, big street"),
                        new Claim("role","free")
                    }
                },
                new TestUser
                {
                    SubjectId = "2",
                    Username = "bob",
                    Password = "password",

                    Claims = new List<Claim>
                    {
                        new Claim("name", "Bob"),
                        new Claim("website", "https://bob.com"),
                         new Claim("role","paying")
                    }
                }
            };
        }
    }
}

Javascript Client:
var config = {
    authority: "http://localhost:5000",
    client_id: "js",
    redirect_uri: "http://localhost:5003/callback.html",
    response_type: "id_token token",
    scope: "openid profile api1 address roles",
    post_logout_redirect_uri: "http://localhost:5003/index.html",
};
var mgr = new Oidc.UserManager(config);

And finally Api Controller:

  [Route("[controller]")] 
    public class IdentityController : ControllerBase
    {
        [HttpGet]
        [Authorize(Roles = "free")]
        public IActionResult Get()
        {
            return new JsonResult(from c in User.Claims select new { c.Type, c.Value });
        } 
    }

### Relevant parts of the log file

```
<log goes here>
```

**Comment by radjaxx** [comment]
Please would you include some snippet how to add claims into AccessToken? How to call UserInfo Endpoint and where from? Many thanks

**Comment by radjaxx** [comment]
Trying to set up api resource but unsuccesfully.

 new ApiResource
                {
                    Name = "api1",
                    DisplayName = "MY API 1" ,
                    UserClaims = { JwtClaimTypes.Role  }, 
                    Scopes =
                    {
                        new Scope()
                        {
                            Name = "roles",
                            // UserClaims = { "role" }
                        }
                    }

 Getting error below :(

Sorry, there was an error : invalid_scope
Request Id: 0HL743OV9UH9M

**Comment by leastprivilege** [comment]
Not enough info. check the logs.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by koo9** [comment]
think in implicit flow, the client does not have any roles define. only user has roles, correct?
