### ISSUE TITLE
How does deployment work?

### ISSUE THREAD

**Issue by gitn00b1337** [IdentityServer/IdentityServer4#1419]
Hi,

I'd like to quickly confirm how to deploy Identity Server (IS) on a separate server from the web applications. Do I need just one self-signed cert for the IS server or do I also need one for each web app that authorizes with it (with SSL certs as a seperate thing from this)?

From what I have gathered it's just one per Identity Server? I have not located a blog/tutorial explaining exactly how this all works with regarding certificates - only simple how-to's for one machine 

Thanks

**Comment by leastprivilege** [comment]
If you think there's information missing here
