### ISSUE TITLE
1.0 Upgrade / Restore Issue

### ISSUE THREAD

**Issue by PivotalAnimal** [IdentityServer/IdentityServer4#142]
It is probably just me, but after trying to update to 1.0 RTM, I am getting the following:

Microsoft.CodeAnalysis.Common 1.3.0 does not support framework .NETCoreApp,Version=v1.0
Microsoft.CodeAnalysis.CSharp 1.3.0 does not support framework .NETCoreApp,Version=v1.0
Microsoft.CodeAnalysis.VisualBasic 1.3.0 does not support framework .NETCoreApp,Version=v1.0
Microsoft.CSharp 4.0.1 does not support framework .NETStandard,Version=v1.4
Microsoft.Win32.Primitives 4.0.1 does not support framework .NETCoreApp,Version=v1.0
Microsoft.Win32.Registry 4.0.0 does not support framework .NETCoreApp,Version=v1.0

Etc.

**Comment by MasterSkwerl** [comment]
I had updated my packages to 1.0.0 without first having updated my SDK to the newest version. Not sure if it is the same story for you...but hopefully it helps. 

I'm having a separate issue where the most recent IdSrv4 build seems to be targeting a newer subversion of Microsoft.IdentityModel.Tokens. We may just need to give em a chance to catch up.

**Comment by PivotalAnimal** [comment]
I installed VS2015.3, The latest SDK, The Visual Studio Tooling Update, etc. Not sure what is up. Funny thing is, I tried to uninstall RC2 tooling but those solutions are still building correctly.
