### ISSUE TITLE
How to get Module and exponent from identity server 4?

### ISSUE THREAD

**Issue by cdamose** [IdentityServer/IdentityServer4#1422]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Visit the discovery document.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/MvcManual/Controllers/HomeController.cs#L78
