### ISSUE TITLE
Javascript CORS question

### ISSUE THREAD

**Issue by waynevdm** [IdentityServer/IdentityServer4#1423]
Hi

I have got a javascript client solution for CORS working by using the ASP.NET/MVC. The identity server startup is as follows. 

The ConfigureServices method has
    services.AddCors();
    services.AddMvc(

The Configure method loads the origins from the config file and sets up the policy
    var appConf = new ApplicationConfiguration();
    Configuration.GetSection(nameof(ApplicationConfiguration)).Bind(appConf);
    string[] clientOrigins = appConf.ClientOrigins.Split(',');

    app.UseCors(policy =>
    {
        policy.WithOrigins(clientOrigins);
        policy.AllowAnyHeader();
        policy.AllowAnyMethod();
        policy.WithExposedHeaders("WWW-Authenticate");
    });

The config entry is as follows
    "ClientOrigins": "http://localhost:55950"

The javascript client is also setup in an ASP.NET/MVC website with CORS enabled as follows
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddCors();
        services.AddMvc();
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        app.UseCors(policy =>
        {
            policy.WithOrigins(
                "http://localhost:5000"); // Identity Server origin
            policy.AllowAnyHeader();
            policy.AllowAnyMethod();
            policy.WithExposedHeaders("WWW-Authenticate");
        });
    }

However our client will be an angular application and will not have the ASP.NET/MVC CORS solution available to it. I have read the the documentation on identity server 4 CORS http://docs.identityserver.io/en/release/topics/cors.html and would like to use the AllowedCorsOrigins.
We have implemented or own ClientStore so I have implemented a Custom CORS Policy Service as follows

    public class CorsPolicyService : ICorsPolicyService
    {
        private readonly ILynxTransitClient _lynxClient;
        private readonly ILogger<CorsPolicyService> _logger;

        public CorsPolicyService(ILynxTransitClient lynxClient, ILogger<CorsPolicyService> logger)
        {
            _lynxClient = lynxClient;
            _logger = logger;
        }

        public async Task<bool> IsOriginAllowedAsync(string origin)
        {
            var query = new ListClientAllowedCorsOrigins();
            var allowedOriginsResp = await _lynxClient.RequestAsync<ListClientAllowedCorsOrigins, ListClientAllowedCorsOriginsResponse>(query);

            var isAllowed = allowedOriginsResp.Origins.Contains(origin, StringComparer.OrdinalIgnoreCase);
            _logger.LogDebug("Origin {origin} is allowed: {originAllowed}", origin, isAllowed);
            return isAllowed;
        }
    }

The query returns all the AllowedCorsOrigins from all the clients that are stored.

The identity server configuration is as follows for the policy

    public static void AddThresholdIdentity(this IServiceCollection services, ScopedService scopedService)
    {
        services.AddTransient<IUserStore, UserStore>();
        services.AddTransient<IRedirectUriValidator, CustomRedirectValidator>();

        var key = CreateRsaSecurityKey();
        services.AddIdentityServer()
            .AddSigningCredential(new SigningCredentials(key, "RS256"))
            .AddCorsPolicyService<CorsPolicyService>()
            .AddClientStore<ClientStore>()
            .AddResourceStore<ResourceStore>()
            .AddProfileService<ProfileService>();
        services.AddScoped(sp => scopedService);
    }

When I remove the javascript client ASP.NET/MVC CORS configuration I get the CORS HTTP request error and the breapoint I have in the Custom CORS Policy Service is never reached so I don't think it is being used. 

Have I not configured the Custom CORS Policy Service correctly or is ther something I am not understanding?

**Comment by brockallen** [comment]
To handle CORS all you need to do is add the client's origin to the Client configuration's AllowedCorsOrigins configuration property.
