### ISSUE TITLE
Question:  Why is the IdentityTokenLifetime default to 300 sec?

### ISSUE THREAD

**Issue by kevinlo** [IdentityServer/IdentityServer4#1428]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

Maybe I should ask what it the intended use of the Identity token.   I thought it is used to identify the user and it can be passed to other services (e.g. backend services) and the that services use the id_token to validate it is a valid user?   But I don't see any endpoint to validate the id_token.  If not, what should be passed from one service to another service to validate the user?

The only end point that takes the id_token parameter is the End Session Endpoint where it is passed as the id_token_hint.   But in that case, why is the IdentityTokenLifetime  default to 300 sec only?   I don't expect the user end the session in 300 sec.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io

**Comment by michael-freidgeim-webjet** [comment]
The question answered on SO  https://stackoverflow.com/questions/45746403/why-is-the-identitytokenlifetime-default-to-300-sec
