### ISSUE TITLE
A way of adding signing cert cause EF update/migrate failure

### ISSUE THREAD

**Issue by johnxjcheng** [IdentityServer/IdentityServer4#1429]
### Issue / Steps to reproduce the problem
With the following ways of AddSigningCredential, 
`            services.AddIdentityServer()
	            .AddSigningCredential(new X509Certificate2(Path.Combine(".", "Certificates", "mycert.pfx"), "password"))  // THIS LINE PREVENTS EF Migrate/Update, COMMENT IT OUT WHEN DOING THAT!!
				.AddAspNetIdentity<ApplicationUser>()
				.AddProfileService<LdsProfileService>()
				.AddConfigurationStore(builder =>
                    builder.UseSqlServer(configurationConnection, options =>
                        options.MigrationsAssembly(migrationsAssembly)))
                .AddOperationalStore(builder =>
                    builder.UseSqlServer(configurationConnection, options =>
                        options.MigrationsAssembly(migrationsAssembly)));`

Run: dotnet ef database update --context ConfigurationDbContext

### Relevant parts of the log file

```
`An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory
to override the initialization of the DbContext at design-time. Error: The system cannot find the path specified
No parameterless constructor was found on 'ConfigurationDbContext'. Either add a parameterless constructor to 'Configura
tionDbContext' or add an implementation of 'IDbContextFactory<ConfigurationDbContext>' in the same assembly as 'Configur
ationDbContext'.`
```
### Workaround
Comment out the line of .AddSigningCredential, then ef database task should work.

**Comment by leastprivilege** [comment]
Well - I guess the path-base is different then. It is not recommended to load certs from the file system anyways.
