### ISSUE TITLE
Cannot use ConfigurationBinder to bind Client from config file

### ISSUE THREAD

**Issue by kevinlo** [IdentityServer/IdentityServer4#1430]
I have this Clients settings in the AppSettings.json

```
  "Clients": {
    "Client1": {
      "ClientId": "App1",
      "ClientName": "App1",
      "ClientSecrets": [ "secret" ],
      "AllowedGrantTypes": [ "hybrid" ],
      "AllowedScopes": [ "openid", "WebApi" ],
      "RedirectUris": [ "http://myserver/api/" ],
      "AllowOfflineAccess": true,
      "RequireHttps": false,
      "RequireConsent": false,
      "AllowAccessTokensViaBrowser": false
    },
    "Client2": {
      "ClientId": "App2",
      "ClientName": "App2",
      "ClientSecrets": [ "secret" ],
      "AllowedGrantTypes": [ "hybrid" ],
      "AllowedScopes": [ "openid", "profile", "offline_access" ],
      "RedirectUris": [ "http://myserver/app2/signin-oidc" ],
      "PostLogoutRedirectUris": [ "http://myserver/app2/Home/Index" ],
      "AllowOfflineAccess": true,
      "RequireHttps": false,
      "RequireConsent": false,
      "AllowAccessTokensViaBrowser": false,
      "AlwaysIncludeUserClaimsInIdToken": true
    }
  }

```
I have the following to use ConfigurationBinder to bind it to Client

```
            IList<Client> clients = new List<Client>();
            IConfigurationSection cs = Configuration.GetSection("Clients");
            cs.Bind(clients);
```

For version 1.5.2 or older, the Client _allowedGrantTypes is IEnumerable and the binding does not work because [Binding to non-null IEnumerable doesn't work](https://github.com/aspnet/Configuration/issues/611)

`private IEnumerable<string> _allowedGrantTypes = GrantTypes.Implicit;
`
     
In the 2.0 preview, the Client _allowedGrantTypes  is changed to [ICollection ](https://github.com/IdentityServer/IdentityServer4/commit/35184dd52f65672e9684ebefb14e2372c63cf887)

The binding will try to add the "Hybrid" to the existing _allowedGrantTypes.   Because the default _allowedGrantTypes has the "Implicit", the ValidateGrantTypes will throw InvalidOperationException because of this

`            DisallowGrantTypeCombination(GrantType.Implicit, GrantType.Hybrid, grantTypes);`

Can the default GrantTypes.Implicit be removed from the _allowedGrantTypes and let the user of Client to set it?  I don't think Implicit is the most used grant type and the Grant type need to be set in many cases.   

If not, can you provide a way to easily bind the Client from config file?    

I don't want to create a duplicated ClientDummyModel just for the binding and then manually set the properties to the real Client.

**Comment by kevinlo** [comment]
I forgot to mention I have this ClientScretConverter to convert string to Secret to make the binding work
```
            TypeDescriptor.AddAttributes(typeof(Secret), new TypeConverterAttribute(
                typeof(ClientScretConverter)));

    public class ClientScretConverter : StringConverter
    {
        public override bool CanConvertTo(ITypeDescriptorContext context, Type destinationType)
        {
            return destinationType == typeof(Secret) || base.CanConvertTo(context, destinationType);
        }
        public override object ConvertFrom(ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value)
        {
            if (value != null && value is string)
            {
                return new Secret (((string)value).Sha256());
            }
            return base.ConvertFrom(context, culture, value);
        }
    }
```

**Comment by brockallen** [comment]
I'm happy to remove that as the default.

**Comment by leastprivilege** [comment]
@brockallen I think we should consider including all the necessary plumbing to read from config

**Comment by brockallen** [comment]
IIRC, I think we did that by the change to ICollection from IEnumberable. But we could possibly add some more sugar (a la Hao).

**Comment by kevinlo** [comment]
Does it make sense you can provide a DefaultClientScretConverter  too?

**Comment by brockallen** [comment]
Yea, I'm sure we could provide IConfigSection support. We'd have to look into it.

**Comment by cheesemacfly** [comment]
Just ran into this issue today, that'd be super helpful.

**Comment by brockallen** [comment]
Does this look like it does what you want? 

https://github.com/IdentityServer/IdentityServer4/pull/1473

**Comment by kevinlo** [comment]
@brockallen  It looks good. 

Why don't you change the following calls in ConfigServices to use config section too.  You already add those functions:

.AddInMemoryIdentityResources(_config.GetSection("IdentityResources"))
.AddInMemoryApiResources(_config.GetSection("ApiResources"))

Then, both Clients.cs and Resources.cs OR the whole Configuration folder can be removed.

**Comment by brockallen** [comment]
I just added the one to show how it worked. 

As for the demo code, I think we'll stick with the in-memory based approach since it's for dev purposes only and intellisense is better than the config approach.

**Comment by brockallen** [comment]
Also, I wanted to point out that I specifically did not provide a secret converter -- we don't want to encourage secrets stored in plain text. You'll have to hash them prior to putting them in the config files, especially since I could see people using this for production scenarios.

**Comment by kevinlo** [comment]
Ok.  It makes sense.  You can close this issue.  Thanks.

**Comment by cheesemacfly** [comment]
Could we have this implementation for the [AddTestUsers](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Test/IdentityServerBuilderExtensions.cs) too? I can send a PR if that helps.

**Comment by brockallen** [comment]
Not a bad idea -- @leastprivilege thoughts?

**Comment by brockallen** [comment]
And of course, @cheesemacfly, you could easily add your own in the meantime.

**Comment by cheesemacfly** [comment]
Yes, very much inspired by what is already there:

```csharp
public static class IdentityServerBuilderExtensions
{
    public static IIdentityServerBuilder AddTestUsers(this IIdentityServerBuilder builder, IConfigurationSection section)
    {
        var users = new List<TestUser>();
        section.Bind(users);

        return builder.AddTestUsers(users);
    }
}
```

**Comment by kevinlo** [comment]
@brockallen  Regarding to your [comment](https://github.com/IdentityServer/IdentityServer4/issues/1430#issuecomment-326427943) about putting the SHA256 text in the config file.   I try to do it today.  But then I find out that the [OpenIdConnectHandler](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs) just send the plain text to the IS4.   At IS4, the [HashedSharedSecretValidator](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/HashedSharedSecretValidator.cs) convert the passed in plain text to SHA256 and SHA512 to compare
```
            var secretSha256 = sharedSecret.Sha256();
            var secretSha512 = sharedSecret.Sha512();
```

In other words, on the IS4, it is configured in SH256, but on the resource server using the OpenIdConnectMiddleware, it needs to config as plain text secret.   Isn't it inconvenient or hard to compare if both sides of the secrets are set up properly?   I expect they both either using SHD256 or plain text. 

In fact, the IdentityServer document [example ](http://docs.identityserver.io/en/release/quickstarts/1_client_credentials.html) shows it convert to SHA256 only when it is converted to Secret.  It is easier to compare the plain text.

```
            ClientSecrets =
            {
                new Secret("**secret**".Sha256())
            },

// request token
var tokenClient = new TokenClient(disco.TokenEndpoint, "client", "**secret**");
```

That's why I still need to keep the secret converter and cannot put the secret in SHA256 in the config file.

What is your comment about it?

**Comment by leastprivilege** [comment]
The config file in IS4 is a data store. You should never store secrets in plain text in your data store.

**Comment by kevinlo** [comment]
@leastprivilege  But then why it expect the incoming secret in plain text and default to use the HashedSharedSecretValidator to convert it to the SHA256 to compare.  Can it use a validator to compare the incoming SHA256 directly?

**Comment by leastprivilege** [comment]
Because that's the way it works ;)

IS stores the hash so that the real secret does not get compromised in case of a data breach. The client is supposed to store that secret securely as well - but not hashed of course otherwise the hash would become the secret.

**Comment by kevinlo** [comment]
@leastprivilege  Obviously, I am new to the authentication and authorization.   I think I understand why it does now.   Thanks for your explanation.  Is there any good documents explaining the best practices in handling authentication and authorization?

**Comment by andriysavin** [comment]
`Client.Claims` doesn't work with configuration. I tried this json:
```
"Claims": [
          {
            "Type": "MyClaimType",
            "Value": "MyValue"
          }
```
Apparently, `Claim` type is immutable, so cant be deserialized from config. But I think nobody expects that, I spent a while trying to understand why I wasn't getting client claims in tokens.

**Comment by brockallen** [comment]
I think it's important to understand that Microsoft's JSON-backed config system in ASP.NET Core is not really a real persistence mechanism (and it does not use JSON.NET). In short, it's pretty limited, so you might need to lower your expectations.

**Comment by andriysavin** [comment]
@brockallen Yeah, I understand that. I mean maybe, for loading configs a parallel DTO hierarchy should be created (though it requires some work and later support). Meanwhile, here's my workaround for this:

 ```
public static IIdentityServerBuilder AddInMemoryClientsWithClamis(
            this IIdentityServerBuilder builder,
            IConfigurationSection section)
        {
            Check.NotNull(builder, nameof(builder));
            Check.NotNull(section, nameof(section));

            var clients = section.Get<Client[]>();

            if (clients == null)
            {
                return builder;
            }

            for (int i = 0; i < clients.Length; i++)
            {
                var claimDtos = section.GetSection(
                    FormattableString.Invariant($"{i}:Claims")).Get<ClaimDto[]>();

                if (claimDtos == null)
                {
                    // No Claims section.
                    continue;
                }

                var claims = claimDtos.Select(dto => new Claim(
                    dto.Type,
                    dto.Value,
                    dto.ValueType,
                    dto.Issuer,
                    dto.OriginalIssuer));

                clients[i].Claims.Add(claims); // "Add" is my extension method for multiple items adding.
            }

            builder.AddInMemoryClients(clients);

            return builder;
        }
```
