### ISSUE TITLE
Make InputLengthRestrictions.TokenHandle configurable

### ISSUE THREAD

**Issue by ssarj** [IdentityServer/IdentityServer4#1431]
I see that `InputLengthRestrictions.TokenHandle` does not have a public setter, which I ran into when playing with a token generation scheme that was generating strings of length > 100.

Before making a PR, is there any desire:

- to have this value configurable?
- have reference token handles validated as they're generated (.. and so have an incorrect implementation detected earlier)?

**Comment by brockallen** [comment]
> which I ran into when playing with a token generation scheme that was generating strings of length > 100.

How? IIRC we gen a 128 bit random number and put that into a base64url encoded string.

**Comment by ssarj** [comment]
Sorry, I really should have said "playing with a token handle generation scheme".

I've got my own implementation of `IReferenceTokenStore` that fully encapsulates reference token storage, and so does not depend on `IHandleGenerationService` / `DefaultHandleGenerationService` in anyway.

**Comment by brockallen** [comment]
Hmm... well, we have to have some limits. We'll take a look.

**Comment by ssarj** [comment]
Absolutely agree that there needs to be a limit -- only question is could it be configurable by users of IdentityServer4.

**Comment by brockallen** [comment]
Done.
