### ISSUE TITLE
Windows Authentication with Kestrel + IISIntegration

### ISSUE THREAD

**Issue by balaji-rajan** [IdentityServer/IdentityServer4#1434]
### Issue / Steps to reproduce the problem
Configured identity server to run on kestrel with IISIntegration and enabled WindowAuthentication in IISExpress with VS its perfectly working. Later moved it to Windows server and local IIS then its stopped working

***UnauthorizedAccessException: Attempted to perform an unauthorized operation.**

for windows server i've installed **DotNetCore.1.0.5_1.1.2-WindowsHosting**

**Comment by brockallen** [comment]
I'd search the Microsoft repos for this -- it's some bug in their components.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
