### ISSUE TITLE
How to get clientId in a ICorsPolicyService?

### ISSUE THREAD

**Issue by galvesribeiro** [IdentityServer/IdentityServer4#1435]
I need to get the `clientId` inside a custom implementation of `ICorsPolicyService` at the `IsOriginAllowedAsync(string origin)` method in IdentityServer4.

Can you anyone point me how to do it?

Thanks! I appreciate any input.

**Comment by galvesribeiro** [comment]
Someone?

**Comment by brockallen** [comment]
No, we don't have that since we don't know which client it is.

**Comment by galvesribeiro** [comment]
That make things VERY complicated and limited @brockallen.

Imagine that you have 2 clients and you want 1 to allow a particular origin, and other not. The way it is today, without filtering by clientId as I can see from the entity framework store implementation for this service, its all or nothing. You add one origin and everyone will be able to use it... That breaks any kind of multitenant scenario...

Is there a way to workaround it?

Thank you.

**Comment by brockallen** [comment]
How would you know what client is requesting the discovery document?

**Comment by galvesribeiro** [comment]
That is only used for the discovey document @brockallen? I thought that was used on every request to validade if the origin was allowed or not...

In all cases, every time that method was invoked it will seek the whole database.

I'm trying to find a way to narrow down to only origins scoped to a given clientId. Hence why the allowed origins are registered to the Client object.

**Comment by leastprivilege** [comment]
Use caching.

**Comment by galvesribeiro** [comment]
@leastprivilege cache is the bad "solution" to all performance problems instead of proper fixing the problem which in this case, is to proper index. Cache may work to a simple website but not to a distributed system.

**Comment by brockallen** [comment]
My point was that there are many requests into IdentityServer where no client id is passed, yet we still need to allow CORS. Thus the design.

**Comment by galvesribeiro** [comment]
@brockallen ok, as far as I understood the code, the only case that it is required is the discovery doc. Is there anything else?

Also, for other requests which we do have the clientId and which looks like are the most frequent ones, can we have another method that takes the clientId and origin? For example Authorize and Token endpoint are way more frequent than the discovery document and they have the clientId somewhere for sure. They could leverage a considerable bump in performance if we have this extra method.

**Comment by leastprivilege** [comment]
Then you are misunderstanding how CORS actually works. It is a transport level protocol and its evaluation happens much earlier than the oidc protocol endpoints. 

I'd use caching ;)

**Comment by galvesribeiro** [comment]
Ok, then I'm not understanding. So may I ask why the list of Allowed Origins are attached to the Client object and are not a global list of Origins on its own? :)

**Comment by brockallen** [comment]
You could implement your custom cors policy service that way if you wanted to.

**Comment by galvesribeiro** [comment]
@brockallen that is what I was trying to do, but I hit on the missing clientId thing.

**Comment by brockallen** [comment]
Have you seen how our EF implementation does it?

**Comment by galvesribeiro** [comment]
Yup, I did. It does a huge scan on all clientIds and all origins.

https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Services/CorsPolicyService.cs#L34-L38

I'm trying to integrate IdSrv with Orleans but there we don't scans since it doesn't scale.

**Comment by brockallen** [comment]
I don't know what Orleans is, but in EF we should have indexes on the origins table.

**Comment by leastprivilege** [comment]
> So may I ask why the list of Allowed Origins are attached to the Client object and are not a global list of Origins on its own? :)

Becuase it is a client specific setting. That all said - you don't have to use that mechanism and can maintain your own flat list of allowed origins. Just make sure you update all the necessary places when you add a new client.

**Comment by galvesribeiro** [comment]
Orleans -> dotnet.github.io/orleans

Ok, I got it... Will remove that collection and make it something else.

Thanks
