### ISSUE TITLE
System.MissingMethodException Error after migrating from asp.net core 1.1 to asp.net core 2.0

### ISSUE THREAD

**Issue by noufionline** [IdentityServer/IdentityServer4#1436]
Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Microsoft.Extensions.DependencyInjection.AuthenticationServiceCollectionExtensions.AddAuthentication(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.

Can anyone Help?

**Comment by alexdresko** [comment]
Confirmed. Was basically just following along [here](https://identityserver4.readthedocs.io/en/release/quickstarts/6_aspnet_identity.html) and ran into that exception.

**Comment by ifflanb** [comment]
Sorry what was the fix for this?

**Comment by mravko** [comment]
Anyone? Closed but no explanation, what is the fix?

**Comment by mravko** [comment]
Ok so you should instal the preview version of the package. The documentation doesn't specify that if you use the .net core 2. (2.0.0-preview3)

**Comment by needcash** [comment]
Thank you, 2.0.0-preview3 version of the package fixed the problem.
