### ISSUE TITLE
There is no any option available to handle smart card authentication in Identity Server 4

### ISSUE THREAD

**Issue by malitushar27** [IdentityServer/IdentityServer4#1437]
- [ ] I read and understood how to do Resource Owner Password Validation [Resource Owner]

### Issue / Steps to reproduce the problem
I have client web application, when it gets loaded, for authentication, I have redirected it to Identity Server 4 URL, I have modified login page to accept two kinds of authentication, first is username and password (Resource owner) and second is Smart card authentication. What I want to implement as, when I click on smart card authentication, my app should read the smart card and validate it against the PIN and return me the result of Digital Signature.
I found one implementation of Identity Server 4 - IExtensionGrantValidator, but it doesn't really support smart card authentication

### Relevant parts of the log file

```
no logs here
```

**Comment by leastprivilege** [comment]
If your environment is configured correctly for client certificate authentication - you can just read the X509 details from the HttpContext. This is not really IdentityServer specific.

**Comment by malitushar27** [comment]
In identity Server V3, we have options in IdentityServerOptions like RequireSsl, SigningCertificate, PublicOrigin through which we were telling to use certificate, I am unable to find these options in Identity server V4, please guide me if I am missing.

**Comment by leastprivilege** [comment]
Start with documentation maybe.

https://identityserver4.readthedocs.io/en/release/

**Comment by malitushar27** [comment]
I am sorry to say this that documentation doesn't provide the information which I am looking for.

**Comment by leastprivilege** [comment]
Have you tried the quickstarts e.g.? looked under deployment etc?

**Comment by malitushar27** [comment]
Yeah, I tried with quick-start, it has Resource Owner implementation, custom grant validater but nothing related to these options available in IdSrv3.

**Comment by leastprivilege** [comment]
And how do they set the certificate?
