### ISSUE TITLE
Encrypted Token Support

### ISSUE THREAD

**Issue by alpersogukpinar** [IdentityServer/IdentityServer4#1439]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
As far as I know, System.IdentityModel.Tokens.Jwt 1.5.3 and later versions supports encrypted tokens.
Do you plan to support encrypted tokens at identity server or do you have any suggestions to encrypt identityserver generated tokens?
Thanks,
Alper
### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
We currently don't have built-in support for that. But you can easily add it yourself by implementing (or deriving from our default) `ITokenCreationService'.

If you want that feature, please open a feature request and describe your scenario.

**Comment by alpersogukpinar** [comment]
Hi @leastprivilege ,
I've created an issue #1440  for feature request, as you suggested. 
I also forked the project and started to  develop that feature. I haven't finished the development yet, but it would be nice if you could comment on the code before I am going too far...

**Comment by leastprivilege** [comment]
Don't worry - if we decide to add that we would do that ourselves.
