### ISSUE TITLE
Federated Signout

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#144]

**Comment by Lutando** [comment]
Is this related to the endsession endpoint?

**Comment by brockallen** [comment]
@Lutando it's something like this: https://brockallen.com/2016/02/09/federated-sign-out-and-identityserver3/

**Comment by brockallen** [comment]
Notes from some research: federated signout will be the responsibility of the logout UI page. once they deliver the user to the SLO location, and that has returned the user back, the signed out page can invoke the same APIs on the `IUserInteractionService` that it calls without federated signout to render the iframe to IdSvr's end session cleanup endpoint. 

In short, I don't think there's anything to do for this as a feature, unless I'm forgetting something. Am I @leastprivilege?

**Comment by brockallen** [comment]
The only other thing we could do is possibly provide an API or a taghelper to automatically render the iframe. This might be something in the UI library.

**Comment by brockallen** [comment]
The more I think about it, I almost prefer middleware in front checking for the oidc-signout to emit the hidden iframes.

**Comment by brockallen** [comment]
we will build a middleware that we can put in front of the signout to emit the iframes.

**Comment by brockallen** [comment]
done. we should review the API "feel" @leastprivilege
