### ISSUE TITLE
How to Sync Users with Api Resources

### ISSUE THREAD

**Issue by DavidNorena** [IdentityServer/IdentityServer4#1442]
Maybe this creates coupling but, what if we need to relate tables or information to userid, what is the best aproach to do that. (I know there is a endpoint exposing user info).

But what if we need to show information about a list of users, as far as i understand all user information is stored at the identity server side, so if i need to relate information to those users i would need to authenticate them each one and then call userinfo ?

Example:

I have a posts table and I need to relate them to user id, because i need to do searches and stuff like that related to user information on the client app..

Hope you understand me !

**Comment by leastprivilege** [comment]
I don't understand you - but - that is beyond IdentityServer. We just implement the OpenID Connect/OAuth2 protocol. You are asking for some custom functionality.

IOW - build it yourself.

**Comment by DavidNorena** [comment]
Ok, then I ask this, what if you need user info stored at the client app, because you need to relate tables and data to users, could you please at least give me some guidance or how you will implement it, or do it ... 

Sorry if my english isn't good !

**Comment by pekkah** [comment]
Build an api which reads the information from those same tables you have configured identity server to use.

**Comment by DavidNorena** [comment]
This is my aproach, I'm using javascript client to login, as soon as IdentityServer gives me a token, it calls a return url in the javascript client, so the login or register flow, would be made once, when its done, I call another endpoint in my api with the fresh token to "create" or "update" the user info !
