### ISSUE TITLE
identityserver4 login page not display

### ISSUE THREAD

**Issue by xubair81** [IdentityServer/IdentityServer4#1445]
when i request 
` basePath: 'http://localhost:26201',
                authorizationEndpoint: 'connect/authorize',
                clientId: 'Partner',
                redirectUri: 'http://localhost:13079/index.html',
                endSessionEndpoint: '/account/login.html',
                scope: 'openid profile',
                response_type: "id_token",
                nonce: "asdasd",
                state: "asdsssd"`

its just return blank page and page url is
["http://localhost:26201/account/login?returnUrl=%2Fconnect%2Fauthorize%2Flogin%3Fresponse_type%3Did_token%26client_id%3DPartner%26state%3Dasdsssd%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A13079%252Findex.html%26scope%3Dopenid%2520profile%26nonce%3Ddummynonce"](url)

**Comment by lasrol** [comment]
> IdentityServer does not provide any user-interface or user database for authentication. These are things you are expected to provide or develop yourself.

So have you created a controller and view for your login page?

**Comment by leastprivilege** [comment]
Yep. See here:

https://identityserver4.readthedocs.io/en/release/quickstarts/3_interactive_login.html
