### ISSUE TITLE
Question: ClientSecretValidator not public anymore

### ISSUE THREAD

**Issue by beauceant** [IdentityServer/IdentityServer4#1448]
`ClientSecretValidator` was a useful piece of code in v1.5.2 for requests' validation (e.g. in a custom endpoint).
Is there a convenient way to replace it?

**Comment by leastprivilege** [comment]
Did we make it internal? I need to check

**Comment by brockallen** [comment]
Alas, it is `internal`.

**Comment by leastprivilege** [comment]
It's public now.

**Comment by beauceant** [comment]
That is great! Thank you.
