### ISSUE TITLE
JavaScript application refresh token question

### ISSUE THREAD

**Issue by alvachien** [IdentityServer/IdentityServer4#1451]
Based on the [documentation of Grant Type](http://docs.identityserver.io/en/release/topics/grant_types.html), the refresh token only supported in hybrid, authorization code and resource owner password flows. 

My javascript application using Oidc-client, it always use implicit as the Grant Type. Is there any way to enable refresh token in javascript application? If it is not possible, how to enlarge the default expiration time then? 

Thanks very much in advance, Alva

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
