### ISSUE TITLE
Requesting tokens with invalid scopes

### ISSUE THREAD

**Issue by jwholme2** [IdentityServer/IdentityServer4#1456]
HI!

Just a quick note - this is a follow-up from when Brock was on-site. I am on IdentityServer4 1.5.2

I have an API Resource that has 3 scopes: scopeA, scopeB, and scopeC.

I have an API client that has allowedScopes set to scopeA and scopeB. The allowedGrantTypes is set to client_credentials, and there is 1 clientSecret. 

If I try to hit the token endpoint with an invalid scope, as so:

grant_type=client_credentials&client_id=redacted&client_secret=redacted&scope=SCOPE_DOES_NOT_EXIST

I receive the following

{"error":"invalid_scope"}

If I try to pass an invalid scope in an array to the token endpoint, as so:
grant_type=client_credentials&client_id=redacted&client_secret=redacted&scope%5B0%5D=SCOPE_DOES_NOT_EXIST

 I get the following:

{"access_token":"redacted","expires_in":3600,"token_type":"Bearer"}

Calling introspection on this token shows that it has scopeA and scopeB, which are the original allowedScopes for the client. 

This is odd behavior as it does increase the scope of the token. 

Thanks!

**Comment by brockallen** [comment]
Thanks for logging this. We'll have a look.

**Comment by brockallen** [comment]
@jwholme2 Can you clarify this part:

>If I try to pass an invalid scope in an array to the token endpoint, as so:
grant_type=client_credentials&client_id=redacted&client_secret=redacted&scope%5B0%5D=SCOPE_DOES_NOT_EXIST

I guess I'm not sure what you mean by "in an array" and what's the "%5B0%5D" encoding above. Thanks

**Comment by brockallen** [comment]
I think what's happening is that when you pass `scope[0]` then IdSvr is missing the expected `scope` apram and falling back to its behavior of allowing `scope` to be optional and thus granting all configured scopes for the client.

**Comment by brockallen** [comment]
Any thoughts on my question @jwholme2?

**Comment by leastprivilege** [comment]
??

**Comment by brockallen** [comment]
@leastprivilege well, we should add a test for this anyway to ensure it's working.

**Comment by brockallen** [comment]
Hey @jwholme2 -- I can't reproduce this, so we will have to close if we don't hear back. Let us know, please. Thanks!

**Comment by jwholme2** [comment]
@brockallen So sorry for the very long delay! Yes, we can close. I think you are correct - the encoding shows scope[0] and thus IdSvr is defaulting to a missing scope.
