### ISSUE TITLE
Alternate signing algorithm support

### ISSUE THREAD

**Issue by chrisdrobison** [IdentityServer/IdentityServer4#1460]
Right now it looks like identity server only supports one signing algorithm. Is it possible to add others?

**Comment by leastprivilege** [comment]
Right now we only support RSA with SHA256.

.NET / .NET Core had some problems with supporting other algorithms x-plat without multi-targeting. This might be resolved now with .NET Core 2. We'll have to look into it post IS4 2.0.

**Comment by Krempelj** [comment]
That's great to see that you've added this to the milestone. Will PS256 algorithm also be supported?

**Comment by leastprivilege** [comment]
tbh - I didn't have yet to research yet. If you want to have a look - feel free.

**Comment by Krempelj** [comment]
[Jose-Jwt](https://github.com/dvsekhvalnov/jose-jwt) (for .Net & .Net Core) supports a lot of alternative algorithms, also PS256. Would including this lib to IdentityServer be an option?

**Comment by leastprivilege** [comment]
So does the Microsoft JWT handler - which is what we currently use.

That being said - you can use whatever JWT library you want by implementing the `ITokenCreationService`.

**Comment by Jehoel** [comment]
@leastprivilege I'm looking at `ITokenCreationService` and it's unclear how I can implement it to provide `ES256` signatures.

As far as I can tell, the `DefaultTokenCreationService` can be used as-is, instead we just need to supply an ES256 `SecurityKey` via the `IKeyMaterialService` (as it's passed into the `System.IdentityModel.Tokens.Jwt.JwtHeader` constructor which takes care of the rest... I think?)

...so how do we supply an ES256 key?

**Comment by leastprivilege** [comment]
Will be fixed in 3.0
