### ISSUE TITLE
Discovery doc also not https

### ISSUE THREAD

**Issue by imalexi** [IdentityServer/IdentityServer4#1462]
not HTTPS in .well-known/openid-configuration 
my startup.cs[.net core 1.1] add

app.UseForwardedHeaders(new ForwardedHeadersOptions
{
 ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

but the Discovery doc also not https:

"issuer": "http://api.intime.com",
  "jwks_uri": "http://api.intime.com/.well-known/openid-configuration/jwks",

how to set

**Comment by NoMoreLoad** [comment]
I've use this code inside `Configure` method of `Startup` class
```
public void Configure(
    ...
    IOptions<ForwardedHeadersOptions> baseForwardOptions)
{
    ...
    if (baseForwardOptions.Value.ForwardedHeaders == ForwardedHeaders.None)
    {
        var options = new ForwardedHeadersOptions
        {
            ForwardedHeaders = ForwardedHeaders.All,
            RequireHeaderSymmetry = false
        };
        app.UseForwardedHeaders(options);
    }
    ...
}
```
If no forwarded options is specified, that means we works behind IIS, and forwarding was not configured yet, so we override it. This is not the IdentityServer issue, but ASP.NET Core. You can read more about this in [IdentityServer docs](https://identityserver4.readthedocs.io/en/release/topics/deployment.html) and in [ASP NET Core repository issues](https://github.com/aspnet/Docs/issues/2384).

**Comment by brockallen** [comment]
Thanks for the tip.

**Comment by RainingNight** [comment]
I'm added UseForwardedHeaders, but still not https!

**Comment by NoMoreLoad** [comment]
@RainingNight .NET Core 1.0/1.1/2.0? Dev/Prod env?

**Comment by RainingNight** [comment]
@NoMoreLoad ASP.NET Core 2.0 & .NET Core 2.0 and IdentityServer4 2.0, in Prod env, use nginx proxy.

Source: [https://github.com/RainingNight/AspNetCoreSample/blob/master/src/IdentityServerSample/Startup.cs](https://github.com/RainingNight/AspNetCoreSample/blob/master/src/IdentityServerSample/Startup.cs)

Demo: [https://oidc.faasx.com/.well-known/openid-configuration](https://oidc.faasx.com/.well-known/openid-configuration)

**Comment by NoMoreLoad** [comment]
@RainingNight Try to read this [thread](https://github.com/aspnet/Docs/issues/2384). Maybe it will be helpful. And try to sniff traffic between nginx and kestrel to watch what headers are passed to kestrel. Maybe some headers that passed shema are not defined and didn't passed from nginx to kestrel. I've deploy this on Apache 2.4 and my apache config looks like this 
```xml
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerName asystem-web-api.ru
	ServerAlias www.asystem-web-api.ru
	ServerAdmin admin@asystem-web-api.ru
	ProxyPreserveHost On
	ProxyPass / http://127.0.0.1:50001/
	ProxyPassReverse / http://127.0.0.1:50001/
	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined
	RequestHeader set X-Forwarded-Proto "https"
	Header always set Strict-Transport-Security "max-age=15768000"
	SSLCertificateFile /etc/letsencrypt/live/asystem-web-api.ru/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/asystem-web-api.ru/privkey.pem
	Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```
my forwarded headers config described [here](https://github.com/IdentityServer/IdentityServer4/issues/1462#issuecomment-325320746).

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2017/10/09/new-in-identityserver4-v2-simplified-configuration-behind-load-balancers-or-reverse-proxies/

**Comment by NoMoreLoad** [comment]
@leastprivilege Useful, but looks like a hack)
I think it should solved using web-server configuration and middleware. It's pretty clean and could be reused in different parts of your app, not only inside of identity server's "scope".
@RainingNight If your deadlines are burning - it could be a solution, if you can't solve this trouble using "clear" way.

**Comment by leastprivilege** [comment]
It is actually wiring up middleware - and you can use it for the reasons I've given in the post.

**Comment by RainingNight** [comment]
It's ok. Thanks!
