### ISSUE TITLE
RFC7523 grant type support

### ISSUE THREAD

**Issue by ycrumeyrolle** [IdentityServer/IdentityServer4#1463]
I would like to implement the [RFC 7253](https://tools.ietf.org/html/rfc7523) grant type `urn:ietf:params:oauth:grant-type:jwt-bearer`. 
The goal is to allow federation from another IdP to IdentityServer :
1/ The user is authenticated on external IdP. The user is not authenticated on the IdentityServer
2/ The browser make an authorization grant request on the IdentityServer with the end-user subject within the assertion
3/ The IdentityServer authenticate the user with the assertion and process the grant

I suppose we have to implement an [extension grant](https://identityserver4.readthedocs.io/en/release/topics/extension_grants.html).
And to implement a custom authentication handler. 
Is it a good approach? 

I take a look at the source code, and I do not understand the current usage of the [`urn:ietf:params:oauth:grant-type:jwt-bearer`](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/IdentityServerConstants.cs#L39). Is it just used internally?

**Comment by chrisowhite** [comment]
@brockallen, I've implemented the authorization grant portion of RFC7253 as an extension grant in our IdentityServer4 implementaton. The way I retrieve the signing credentials is a bit specific to our environment but wouldn't be difficult to adjust it to use the `Client.ClientSecrets` property (or something else) instead. 

Looks like the client authentication portion is already implemented in IdentityServer4 (@ycrumeyrolle I believe this is where you're seeing that constant used).

**Comment by leastprivilege** [comment]
Either you or I am missing something here ;)

The above RFC defines an extension grant for the **token** endpoint - not the **authorize** endpoint.

> 2/ The browser make an authorization grant request on the IdentityServer with the end-user subject within the assertion

Whoch endpoint are you trying to extend?

**Comment by ycrumeyrolle** [comment]
I think I am the one that is missing something!
Indeed I thought the assertion should be passed in the authorization request...

I am willing to federate a source IdP to a target IdP. 
The source IdP is capable to generate an end-user assertion (SAML or JWT) and to pass it to the target IdP, capable to convert the end-user assertion into end-user authentication. By doing so, the IdP is capable to provide authorization based on an external IdP.
As the target IdP persist the authentication with a cookie, I have to initiate the federation flow with a browser request. 


RFC7523 looks good to me, but as you noticed, can not apply as-is to my use case. 

I see three other options : 
 - [Sign-in with external provider](http://docs.identityserver.io/en/release/topics/signin_external_providers.html)
 - [Client initiated Backchannel Authentication](http://openid.net/specs/openid-connect-modrna-client-initiated-backchannel-authentication-1_0.html)
 - Custom authentication flow (based on CIBA without the need of pooling?)

**Comment by leastprivilege** [comment]
Yep - you federate using an external provider.

**Comment by asgeiroa** [comment]
@ycrumeyrolle how did you solve this eventually? I'm trying to solve the same problem and wondering about the same options

**Comment by ycrumeyrolle** [comment]
@asgeiroa we have followed the documentation on http://docs.identityserver.io/en/latest/topics/federation_gateway.html
