### ISSUE TITLE
[Question]  How can I retrieve the Parameter prompt=login passed in the authorize request in the Login Action since it does not get added to returnUrl / Cannot be retrieved as PromptMode by calling GetAuthorizationContextAsync

### ISSUE THREAD

**Issue by manishandankar** [IdentityServer/IdentityServer4#1467]
How can I retrieve the Parameter prompt=login passed in the authorize request in the Login Action since it does not get added to returnUrl / Cannot be retrieved as PromptMode by calling GetAuthorizationContextAsync

I see that the authorize request has prompt=login, while the returnUrl does not and I am not able to retrieve the same by calling GetAuthorizationContextAsync of interaction service.

**Comment by brockallen** [comment]
That's a good point. We remove prompt=login from the URL when we redirect to login, because then we'd end up redirecting back to login if it were passed again. Why do you need to know? If you're on the login page, then idSvr thinks the user needs to login :)

**Comment by manishandankar** [comment]
Thanks :) There is some business logic that needs to be executed in the Login Action if prompt was login. The user would be redirected to Login page when.
1. The user was not logged in and hence the redirect to login.
2. Client sends prompt=login to force the login for the user.
There is no way I can differentiate if prompt was login or the user was not logged in.

Maybe I can handle this by expecting an extra parameter in acr_values from client in case of prompt=login to execute the business logic based on forced login. Please let me know if this approach is fine ?

Thank you for your reply :)

**Comment by brockallen** [comment]
Can you explain what's different about prompt=login? Normally login pages show the login page regardless if the user is already authenticated.

**Comment by manishandankar** [comment]
We have a client that sends request to authorize endpoint, which would redirect to login page if user is not authenticated already /  the authorize request has prompt=login in the query string (so that client can force the login). In the login action of account controller, we need to execute specific business logic if prompt was login. Apologies for keeping it more generic, but I hope this provides the desired context.

**Comment by brockallen** [comment]
Our design is that if you show up on the login page, then login (and prompt) is necessary. If your client needs different semantics, then I'd suggest passing a custom `acr_value`.

**Comment by mackie1001** [comment]
We had the same requirement and thus needed to preserve that prompt value (for login but also select_account). We have some custom client-config specific logic and UI flow that needs to know what was originally requested. I ended up overriding `AuthorizeInteractionResponseGenerator.ProcessLoginAsync()` and copied the prompt value to a parameter of a different name. 

The amount of code that's changed is minimal:

```csharp
protected override async Task<InteractionResponse> ProcessLoginAsync(ValidatedAuthorizeRequest request)
{
    if (request.PromptMode == OidcConstants.PromptModes.Login ||
            request.PromptMode == OidcConstants.PromptModes.SelectAccount)
    {
        request.Raw["prompt_original"] = request.PromptMode;

        // remove prompt so when we redirect back in from login page
        // we won't think we need to force a prompt again
        request.RemovePrompt();

        _logger.LogInformation("Showing login: request contains prompt={0}", request.PromptMode);

        return new InteractionResponse() { IsLogin = true };
    }
            
    return await base.ProcessLoginAsync(request);   
}
```

**Comment by brockallen** [comment]
@manishandankar I hope @mackie1001's suggestion is sufficient for you. I'll close for now, since that does sound like a suitable workaround.

**Comment by gatimus** [comment]
I have a similar requirement to distinguish the `prompt` value. I have the requirement to popup a signin if the browser was asleep (token didn't renew and expired and silent signin failed) or if the user was signed out from an other tab (session monitoring) to allow the user to re-sign in with out losing work. This login view needs to only allow login into the use authenticating not any user. I was turned to [openid core AuthRequest](http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) `prompt=login` where 
> The Authorization Server SHOULD prompt the End-User for *reauthentication*.
