### ISSUE TITLE
Question: Using IdentityServer4 UI/login and ClaimsPrincipal

### ISSUE THREAD

**Issue by Kouloukos** [IdentityServer/IdentityServer4#147]
Hello,

Actually I have 2 questions:

1)
I am using IdentityServer4 Core (.NET Framework 4.6.2) and I have implemented User, Client and Scope persistence in MongoDB. I can successfully issue tokens for my API (Core.NET Framework 4.6.2) and everything works as expected. I put a breakpoint in my API HotelController and I can see in Locals under this, HttpContext, User, Claims my Claims and also the client, scope etc (see image below) 

![image](https://cloud.githubusercontent.com/assets/6676907/16502632/0e7b701c-3f18-11e6-88ca-12f58d1c6222.png)

When I look ClaimsPrincipal.Current (same level as this above) in locals I don't see my claims...
![image](https://cloud.githubusercontent.com/assets/6676907/16502905/4e6c2382-3f19-11e6-9d6d-7dcbfcd5df6b.png)

Is this how it is supposed to be?

2)
When I use the same credentials at the the UI/login page to login to the IdentityServer:
![image](https://cloud.githubusercontent.com/assets/6676907/16502969/9cd93bc2-3f19-11e6-9a6f-d1aab76bc30e.png)

I put a breakpoint at my login controller and I can see in locals that user and claims have my claims:
![image](https://cloud.githubusercontent.com/assets/6676907/16503539/2cf7785c-3f1c-11e6-8d23-f04a5d432c09.png)

but when I put a trace in LoginController's Index and look at Autos I see that CurrentPrincipal's claims are empty
 
![image](https://cloud.githubusercontent.com/assets/6676907/16503603/7a7978c8-3f1c-11e6-8f81-a1b4cbe8e39d.png)

Is this it is supposed to be this way?

Here is my LoginController Index action:

        [HttpPost(Constants.RoutePaths.Login)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(LoginInputModel model)
        {
            if (ModelState.IsValid)
            {
                if (_loginService.ValidateCredentials(model.Username, model.Password))
                {
                    var user = _loginService.FindByUsername(model.Username);

                    var claims = new Claim[] {
                        new Claim(JwtClaimTypes.Subject, user.Id.ToString()),
                        new Claim(JwtClaimTypes.Name, user.Username.Value),
                        new Claim(JwtClaimTypes.IdentityProvider, "AuthServer"),
                        new Claim(JwtClaimTypes.AuthenticationTime, DateTime.UtcNow.ToEpochTime().ToString()),
                        new Claim(JwtClaimTypes.Role, Enum.GetName(typeof(Role), user.Role))
                    };
                    var ci = new ClaimsIdentity(claims, "password", JwtClaimTypes.Name, JwtClaimTypes.Role);
                    var cp = new ClaimsPrincipal(ci);

                    await HttpContext.Authentication.SignInAsync(Constants.PrimaryAuthenticationType, cp);

                    if (model.SignInId != null)
                    {
                        return new SignInResult(model.SignInId);
                    }
                    System.Diagnostics.Trace.Write(ClaimsPrincipal.Current);
                    return Redirect("~/");
                }

                ModelState.AddModelError("", "Invalid username or password.");
            }

            var vm = new LoginViewModel(model);
            return View(vm);
        }

I want to use the IdentityServer UI to add CRUD functionality for Users, Clients and scopes. 
I am using a DDD onion structure (all Projects may reference the Domain project but not the other way around) in my Solution and I have Domain, Application, Infrastructure and API layers (IdentityServer is in the Infrastructure layer). 

![image](https://cloud.githubusercontent.com/assets/6676907/16503845/994de88c-3f1d-11e6-9f14-6e5adb7cffe3.png)
![image](https://cloud.githubusercontent.com/assets/6676907/16504002/6665abfc-3f1e-11e6-80b5-1ddf2948d2d2.png)
![image](https://cloud.githubusercontent.com/assets/6676907/16503920/f238cd22-3f1d-11e6-9293-f14c5a735379.png)

User in my solution is a Domain object while Clients and Scopes are the ones from IdentityServer.
All of them persisted to MongoDB. 

Here is how I assign my User domain object properties to the corresponding claims in ProfileService (UserService is in my Application layer):
![image](https://cloud.githubusercontent.com/assets/6676907/16504289/edd68916-3f1f-11e6-8c1c-56e7025137b1.png)

and here is my AuthServer's (IdentityServer4) Startup.cs:

using System.IO;
using System.Security.Cryptography.X509Certificates;
using AuthServer.Initializations;
using AuthServer.Repositories.Implementations;
using AuthServer.Repositories.Interfaces;
using AuthServer.Services;
using AuthServer.Services.Implementations;
using IdentityServer4.Models;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using IdentityServer4.Services;
using IdentityServer4.Validation;
using MongoDB.Bson.Serialization;
using Services.Implementations.Users;
using Services.Interfaces.Users;
using CustomGrantValidator = AuthServer.Extensions.CustomGrantValidator;

namespace AuthServer
{
    public class Startup
    {
        private readonly IHostingEnvironment _environment;

        public Startup(IHostingEnvironment env)
        {
            BsonClassMapper.BsonClassMaps();
            //Initializations.Initializations.CreateClients();
            //Initializations.Initializations.CreateScopes();
            _environment = env;
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            var cert = new X509Certificate2(Path.Combine(_environment.ContentRootPath, "Files\\identityserver.pfx"), "******************");

            var builder = services.AddIdentityServer()
                .SetSigningCredentials(cert);

            builder.Services.AddTransient<IUserService, UserService>();
            builder.Services.AddTransient<IClientRepository, ClientRepository>();
            builder.Services.AddTransient<IScopeRepository, ScopeRepository>();
            builder.Services.AddTransient<IClientStore, ClientStore>();
            builder.Services.AddTransient<IScopeStore, ScopeStore>();
            builder.Services.AddTransient<IProfileService, ProfileService>();
            builder.Services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();
            builder.AddCustomGrantValidator<CustomGrantValidator>();

            // for the UI
            services
                .AddMvc()
                .AddRazorOptions(razor =>
                {
                    razor.ViewLocationExpanders.Add(new UI.CustomViewLocationExpander());
                });
            services.AddTransient<UI.Login.LoginService>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(LogLevel.Trace);
            loggerFactory.AddDebug(LogLevel.Trace);

            app.UseDeveloperExceptionPage();

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = "Temp",
                AutomaticAuthenticate = false,
                AutomaticChallenge = false
            });

            //app.UseGoogleAuthentication(new GoogleOptions
            //{
            //    AuthenticationScheme = "Google",
            //    SignInScheme = "Temp",
            //    ClientId = "434483408261-55tc8n0cs4ff1fe21ea8df2o443v2iuc.apps.googleusercontent.com",
            //    ClientSecret = "3gcoTrEDPPJ0ukn_aYYT6PWo"
            //});

            app.UseIdentityServer();

            app.UseStaticFiles();
            app.UseMvcWithDefaultRoute();
        }
    }
}

I watched Dominick's courses in Pluralsight (Introduction to Identity and Access Control in .NET 4.5  and Identity and Access Control in ASP.NET 4.5) although my projects are in 4.6.2.

Can someone please help me clear things out regarding ClaimsPrincipal in both questions above?
Should I explicitly set the ClaimsPrincipal.Current Claims equal to my User's claims?

Thank you.

**Comment by leastprivilege** [comment]
I wouldn't use claimsprincipal.current anymore.

**Comment by Kouloukos** [comment]
Thank you Dominick for the quick reply...

What do you think about my setup? Is everything correct regarding my IdentityServer's settings?

(Hahaha I am also watching Euro 2016 POLAND-PORTUGAL,  penalties)

**Comment by leastprivilege** [comment]
these are all not issues with idsrv - please use SO for general questions. thanks!

**Comment by waqaskhan540** [comment]
@leastprivilege hi can you share with me how you have provided clients, users and scopes through the database because I am struggling with that, Your help in this regard would be much appreciated.

thank you
