### ISSUE TITLE
Scope duplication still unfixed in 1.5.2

### ISSUE THREAD

**Issue by Falco20019** [IdentityServer/IdentityServer4#1470]
The problem described [here](https://stackoverflow.com/questions/43419140/why-am-i-seeing-duplicate-scopes-on-identityserver4s-consent-screen) was not fixed in 1.5.2 which is the latest version for .NET Standard 1.4 released. It was addressed in [this](https://github.com/IdentityServer/IdentityServer4/commit/239afad00b0bebce1b4fbadfad9b1d09858b69f4) commit, but never found it's way on to NuGet.

Please release a patch since as of now, Scopes are not really usable with .NET Core 1.1 without adding a manual workaround in `ConsentService.BuildViewModelAsync` to remove the duplicates again.

**Comment by leastprivilege** [comment]
This will be fixed in 2.0 IIRC

**Comment by Falco20019** [comment]
But 2.0 targets .Net Standard 2.0, right? So not usable for an asp.net core 1.1 project. And migrating middleware stuff needs some time. So a NuGet Package with a fix would be great.

**Comment by leastprivilege** [comment]
We have limited resources - right now we work on 2.0 - if you want to do a patch for 1.x feel free to PR.

Also - why do you have duplicate scopes in the first place?

**Comment by Falco20019** [comment]
It already IS fixed in 1.x due to the commit I linked in my first post. There was just no 1.5.3 which included it. That was my point :)

If you make a 1.5.3 based on https://github.com/IdentityServer/IdentityServer4/tree/239afad00b0bebce1b4fbadfad9b1d09858b69f4 it still targets .netstandard1.4 and has the bug fixed. Maybe take the latest working version that targets 1.4

And I don't have duplicate scopes, it's just due to a bug in InMemoryStore. So I think it only affects the tutorials and people testing it before making it production-ready

**Comment by leastprivilege** [comment]
> Maybe take the latest working version that targets 1.4

We can't do that because we introduced breaking changes in the meantime (before we moved to v2).

**Comment by Falco20019** [comment]
OK, than it is like it is. I assume it only appears when using the InMemoryStore anyway which should not be relevant for production. Maybe add a note [here](http://docs.identityserver.io/en/release/topics/apis.html?highlight=Scopes) that scopes do not work as expected when using InMemoryStore but as they should when using real stores?
