### ISSUE TITLE
Test windows authentication with iis Integration 2.0 and http.sys

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1472]

**Comment by brockallen** [comment]
yea, yea... go back to your terrine and bordeaux! :P

**Comment by brockallen** [comment]
IIS needed some minor tweaks given that they only have one scheme now, but other than that it looks ok.

HttpListener is next.

**Comment by brockallen** [comment]
HttpSys is missing some parity with IIS: https://github.com/aspnet/HttpSysServer/issues/392

**Comment by brockallen** [comment]
Another non-parity issue: https://github.com/aspnet/HttpSysServer/issues/393

**Comment by brockallen** [comment]
I'm of the opinion that HttpSys support is really 2nd class at this point, so it's really not worth our effort to bend over backwards to hide the discrepancies between the two from unsophisticated users. If someone understands the difference and wants/needs HttpSys then they can do the tweaks on the UI later to accommodate how it works differently than IIS.

**Comment by brockallen** [comment]
reopening to track future work
