### ISSUE TITLE
Incorrect Override Scopes When Using ClientCredentials

### ISSUE THREAD

**Issue by Silvenga** [IdentityServer/IdentityServer4#1474]
- [X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

#### Setup

I would dare say a very standard setup, the relevant client config is below.

```csharp
new Client
{
    ClientId = "test-service-user-client",
    AllowedGrantTypes = GrantTypes.ResourceOwnerPasswordAndClientCredentials,
    AllowedScopes =
    {
        IdentityServerConstants.StandardScopes.OpenId
    },
    ClientSecrets = new List<Secret>
    {
        new Secret("test-service-user-client-secret".Sha256())
    }
}
```

#### Request

```http
POST /connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=test-service-user-client&client_secret=test-service-user-client-secret&grant_type=client_credentials
```

Easier to read:
```
client_id: test-service-user-client
client_secret: test-service-user-client-secret
grant_type: client_credentials
```

#### Response

```
HTTP/1.1 400 Bad Request

{
  "error": "invalid_scope"
}
```

### Relevant parts of the log file

```
Debug: Start token request validation
Debug: Start client credentials token request validation
Trace: Client provided no scopes - checking allowed scopes list
Trace: Defaulting to: openid
Error: test-service-user-client cannot request OpenID scopes in client credentials flow
Error: {
  "ClientId": "test-service-user-client",
  "GrantType": "client_credentials",
  "Scopes": "openid",
  "Raw": {
    "client_id": "test-service-user-client",
    "client_secret": "test-service-user-client-secret",
    "grant_type": "client_credentials"
  }
}
```

### Rationale

I understand that identity scopes just don't make any sense while using `client_credentials` flow. However, `password` flow would make use of identity scopes. I'm wondering if `Defaulting to:` should be occurring when using the `client_credentials` flow.

**Comment by brockallen** [comment]
Obviously if the client passed the scopes then you'd not have this issue. Having said that, I'm hesitant to change our defaulting logic to start to be too clever -- the more logic that does magic the more chance for bugs.

**Comment by Silvenga** [comment]
Oops, I think I misunderstood the usage of scopes.

I was considering to use `client_credentials` to verify that the client is who they say they are, not if they are allowed to access protected resources. This would be incorrect as I should not be using the grant_type to verify the client, rather I should use a scope.

Also per spec:

> If the client omits the scope parameter when requesting
>   authorization, the authorization server MUST either process the
>   request using a pre-defined default value or fail the request
>   indicating an invalid scope.  The authorization server SHOULD
>   document its scope requirements and default value (if defined).

So there isn't a bug here.
