### ISSUE TITLE
Don't use default signin scheme -- be explicit and use auth scheme

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1477]
ASP.NET Identity sets the default signin scheme to be external cookies, so we can't assume the default signin scheme is the main cookie. 🙄

**Comment by brockallen** [comment]
FWIW: https://github.com/aspnet/Identity/issues/1409

**Comment by brockallen** [comment]
Also, we should consider how this gets done in our host -- do we set the default, or do we set each external MW individually.

**Comment by brockallen** [comment]
Done

**Comment by leastprivilege** [comment]
that's very sad...
