### ISSUE TITLE
multi-tenant User Accounts

### ISSUE THREAD

**Issue by jgilbert1** [IdentityServer/IdentityServer4#148]
I am attempting to implement multi-tenancy with identityserver4 beta 4.  I am passing the tenant via acr_values.  I can see it in the signinrequest in AuthorizeEndpointResultFactory.  How do I get access to this value in the LoginService ValidateCredentials method?  Or should it be done somewhere else?

**Comment by brockallen** [comment]
You will have access to the tenant in the UI code. Right now that's on the SignInMessage, but that's being reworked as we speak.

**Comment by rodrigocezar** [comment]
@brockallen It is safe and right to use claim to save TenantID?

**Comment by brockallen** [comment]
sure

**Comment by iberodev** [comment]
are the `acr_values` accessible through the [ProfileDataRequestContext ](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Models/Contexts/ProfileDataRequestContext.cs)?

I would need to check the tentant before building the claims as these would depend on what tenant is making the authorization request. My implementation of the `IProfileService` would be an ideal place to access this but I don't think it's avaulable there.

You mention this area was being reworked. in IdentityServer4 RC1 where did this end up being available inf the back end?

**Comment by iberodev** [comment]
I just found tenant would be available in the `AuthorizationRequest` by using the [IIdentityServerInteractionService ](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/IIdentityServerInteractionService.cs)
