### ISSUE TITLE
Consider including ui_locales as query parameter to ErrorUrl and LogoutUrl

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1480]

**Comment by brockallen** [comment]
As per discussion -- maybe only pass to error page, not the logout url. For logout, the recommendation is to set the ui_locale as part of the auth cookie to it can be used at signout time. 

Perhaps this issue can encapsulate such a change in the QS UI.

**Comment by brockallen** [comment]
Done for error page only. We won't support this on end session since the spec doesn't include it, and there are other ways to track that for the logout page.

**Comment by damienbod** [comment]
@brockallen @leastprivilege  What other ways? If you cannot send the current culture in the URL of the end session, it is not possible to set the correct culture for the logout view to match the clients culture.

Greetings Damien

**Comment by leastprivilege** [comment]
You can set a cookie at authorize time.

**Comment by damienbod** [comment]
But if I switch the client language after this, the logout view will be displayed in the culture set from the cookie, so this does not work.

**Comment by leastprivilege** [comment]
true. Is that a very common scenario?

**Comment by leastprivilege** [comment]
you need to start a conversation with the openid foundation for that.

**Comment by damienbod** [comment]
I live in Switzerland ...

**Comment by TomCJones** [comment]
i am a member of the OpenID Foundation. Can you write up a clear suggested addition?

**Comment by damienbod** [comment]
@TomCJones 

Here is the issue:

https://bitbucket.org/openid/connect/issues/1017/session-management-rp-init-logout-proposal

thanks

**Comment by TomCJones** [comment]
It doesn't seem that this changes much. ui_locals could always have been added as it was always in the core spec. Now it will be explicitly listed as OPTIONAL for the logout instead of implicitly optional as it is today.  @leastprivilege asked if it were a common scenario. @brockallen said "there are other ways to track that for the logout page." It was also suggested to be added to one of the quick starts. I guess you need to make the case to them that it belongs in the response, or create a pull request yourself that adds it. Or make that case that it would not work to add it to the cookie.

**Comment by TomCJones** [comment]
By the way, where would the value be stored? in the application user object?

**Comment by JakeGarrison** [comment]
I currently have a use case where the RP logs out due to inactivity. I would like to pass this as a param to endsession so I can consume it in the logout method to indicate to the end user why they have been logged out. 

We use the oidc js client on the RP and it is not currently possible to pass additional parameters to the endpoint executed by the silentLogout method. (which I might make a feature request for in that repo)

What is the recommended approach today for implementing this feature?

**Comment by ace90210** [comment]
Sorry to bump an old thread but this is an issue for ourselves too, our use case is a mobile app controls the culture and we want to get that culture via the URL parameters, as mentioned before the user could have changed the culture on the mobile without our knowledge so the cookie option isnt suitable. I see no downside to allowing a method of passes parameters from the end session (or any of the built in endpoints) to allow us more control over our applications.

**Comment by brockallen** [comment]
Galvanize the spec committee for this issue.

**Comment by ace90210** [comment]
OK for future reference i have found a workaround in .NET Core 2.2, albeit a terribly hacky one (imo at least).

For those with this issue that like myself **need** this feature and can't wait for a update to Identity Server. I have included out workaround below.


    /// <summary>
    /// Resolves culture/ui_locale parameters not supported by Identity Server 4
    /// Note: is a workaround solution to issue raised here: "https://github.com/IdentityServer/IdentityServer4/issues/1480"
    /// No suitable alternative solution being offered by Identity Server Team at present
    /// </summary>
    public class IdentityServerCultureRequestHandler
    {

        private const string ParameterName = "ui_locales";
        private readonly RequestDelegate _next;

        /// <summary>
        /// Standard middleware constructor
        /// </summary>
        /// <param name="next">The <see cref="RequestDelegate"/> for the middleware</param>
        public IdentityServerCultureRequestHandler(RequestDelegate next)
        {
            _next = next;
        }

        /// <summary>
        /// Invokes the middleware behaviour
        /// </summary>
        /// <param name="context">The <see cref="HttpContext"/> for the request</param>
        /// <returns>The <see cref="RequestDelegate"/></returns>
        public async Task InvokeAsync(HttpContext context)
        {
            bool isEndSessionRequest = context.Request.Path.StartsWithSegments(new PathString("/connect/endsession"), StringComparison.CurrentCultureIgnoreCase);

            if (!isEndSessionRequest)
            {
                await _next(context);
            }
            else
            {
                var cultureQuery = context.Request.Query[ParameterName];

                await _next(context);

                try
                {
                    if (context.Response.StatusCode == StatusCodes.Status302Found)
                    {
                        string headerLocation = context.Response.Headers["Location"];

                        var uriBuilder = new UriBuilder(headerLocation);
                        var query = HttpUtility.ParseQueryString(uriBuilder.Query);
                        query[ParameterName] = cultureQuery;
                        uriBuilder.Query = query.ToString();

                        context.Response.Headers["Location"] = new StringValues(uriBuilder.Uri.OriginalString);
                    }
                }
                catch
                {
                    // handle exception if needed or ignore
                }
            }
        }
    }

Then add it to the middleware pipeline before IdentityServer
`app.UseMiddleware<IdentityServerCultureRequestHandler>();`
`app.UseIdentityServer();`


The above code is how we are getting around the issue and may require slight tweaking. Its longer than probably needed as this middleware in invoked on all request we put in extra precautions to ensure it doesnt break anything else.

@brockallen as @TomCJones stated this is an optional feature so implementing it doesnt break compliance. I don't see why we need to pressure them further? does it need to be mandatory before its addressed here? and why not suggest a suitable workaround for the problem (the cookies suggestion has known flaws that make it unsuitable for use so isnt really an option for many of us)
