### ISSUE TITLE
Consider adding cancellation support to relevant interfaces

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1481]

**Comment by brockallen** [comment]
Why can't our implementations just grab the cancellation token from the http context? This would mean we're not accepting it as a formal param, but it's really the one we'll be using anyway.

**Comment by leastprivilege** [comment]
I agree.

**Comment by brockallen** [comment]
Okies, so maybe this is how to approach this as a feature. Personally, I always hate how CTS pollutes an API.

**Comment by brockallen** [comment]
We might need to leave this open... what if our EF is used outside of asp.net, for example? We still might need the params... let me look into it.

**Comment by railarmenien** [comment]
Considering the Task / Task<T> already pollutes API it makes sense to also accept the CancellationToken.

**Comment by damianh** [comment]
Yes you'll need to add the cancellation token parameter to all async methods on the various interfaces. Yes it is viral but that us what it is. Can be added in a non-breaking way by making the parameter optional.

**Comment by leastprivilege** [comment]
> Can be added in a non-breaking way by making the parameter optional.

Are you sure? IIRC default params are added by the caller and not the callee.

**Comment by leastprivilege** [comment]
But generally agreed.

`CancellationToken cancellationToken = default`

**Comment by brockallen** [comment]
Non breaking, assuming a re-compile :)

**Comment by damianh** [comment]
Yes a re-compile, but I think semver wise it's still considered non-breaking? I've not heard anyone dropping a replacement dll into a deployed application in many years.

**Comment by brockallen** [comment]
>  I've not heard anyone dropping a replacement dll into a deployed application in many years.

Not old-skool enough :)

**Comment by damianh** [comment]
Actually I think anyone inheriting from any of default services (i.e. `DefaultProfileService`) and overriding a method (`GetProfileDataAsync`) would experience a 'breaking' change. 🤔
