### ISSUE TITLE
Investigate SourceLink

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1483]

**Comment by brockallen** [comment]
Added something.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/1508

**Comment by leastprivilege** [comment]
OK - seems to become mainstream now in 2.1

https://github.com/dotnet/sourcelink

**Comment by leastprivilege** [comment]
We will add the MS SourceLink starting with 2.3. no need to document it I think.
