### ISSUE TITLE
Customize Introspection response

### ISSUE THREAD

**Issue by RiskXs** [IdentityServer/IdentityServer4#1484]
I'm using IdentityServer 4 and I want to customize the Introspection response to include the user's claims whenever the user send it's reference token for validation. I couldn't find any documentation about customizing the Introspection response. Is it possible? Is there a better way for the user to get it's claims?

Thanks!

**Comment by brockallen** [comment]
Is the profile service not sufficient for you needs?

**Comment by RiskXs** [comment]
Hi brockallen,

I'm not sure what is this profile service your talking about, I'll love if you could redirect me to documentation

Any way I would like to know if I can customize Introspection response and what should I do to implement that.

**Comment by leastprivilege** [comment]
You can implement your own `IIntrospectionResponseGenerator` - this will be even cleaner in the upcoming 2.0 version.
