### ISSUE TITLE
Unauthorized -  publish in IIS

### ISSUE THREAD

**Issue by andreslon** [IdentityServer/IdentityServer4#149]
Regards, I'm using IdentityServer4  and I have a problem when I published my web site Asp.Net Core RC2 in IIS, in mode debug (from Visual studio) I don't have problems. 

My client Application shows "Unauthorized".

I have this: 

` app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:62/SampleApi/",
                ScopeName = "webapi",
                ScopeSecret = "webapiSecret",
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                RequireHttpsMetadata = false,
                
            });`

![image](https://cloud.githubusercontent.com/assets/2242679/16542757/99ca3356-407b-11e6-8144-061c1a1b5eb3.png)

Help ,please.

**Comment by PivotalAnimal** [comment]
You should remove RC2 or at least try to and upgrade to RTM. Also, one of my machines was totally hosed and I had to rebuild it for RTM. Hopefully that isn't the case for you. Best of luck!

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
