### ISSUE TITLE
Consider inferring allowed CORS origins from redirect URIs?

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1490]
If `AllowedCorsOrigin` list is empty and grant type is implicit?

**Comment by brockallen** [comment]
Does google do it that way? :P

**Comment by brockallen** [comment]
And does AllowAccessTokensInBrowser is true.

**Comment by brockallen** [comment]
Assigning to 3.0 since it's enough of a behavior change that I'd call it sort of breaking. I don't want people on 2.x to be surprised by this as a new behavior.

**Comment by brockallen** [comment]
Implicit is dead.
