### ISSUE TITLE
Enable Active Directory On Premise

### ISSUE THREAD

**Issue by eflorespalma** [IdentityServer/IdentityServer4#1491]
I hope somebody can help with this....Our client have many applications and they want to integrate it to just log in once (single sign on), but they want that using active directory on premise (**NOT AZURE AD AND NOT WS-FEDERATION**) they have their own server.They want something like this image https://ibb.co/nyHOia .... we decide to evaluate identityserver so we found this https://identityserver4.readthedocs.io/en/release/topics/windows.html and in that link says that identitserver 4 support active directory but here we dont see where we are going to put the LPAD//... route to connect to the active directory... so we are with doubts if identityserver supports or not Active directory or Maybe we cant undertand it very well. Thank you.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
