### ISSUE TITLE
Consider ConfigureAwait

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1492]

**Comment by railarmenien** [comment]
I don't think that's required because IS4 is not running on `System.Web` please have a look at https://twitter.com/davidfowl/status/898672274080911360

**Comment by Mardoxx** [comment]
Not required for net core https://stackoverflow.com/a/13494570/3515174 but for net full.. not sure.

I look this up from time to time - I have yet to convince myself I am doing async properly - to try and gain a better understanding. All that happens is I get a solution but no intuition.

Basically all I learn is "don't use it unless you are writing a library which could possibly be used in an application with a UI (or an application with one main thread)." Which is fine.. I can do that.. but it would be good to understand _why_. Seems a rather large concept and details are left out of less complex blogs out of brevity or ignorance. A lot just seem to parrot "if you don't configure await false a UI app you will get a deadlock" without explaining the technicalities - either that or I'm a bit slow :)

**Comment by brockallen** [comment]
Given that I've not yet done the research, if/when you find out let us know here :)

**Comment by MV10** [comment]
@Mardoxx You may find this article useful.

https://blogs.msdn.microsoft.com/benwilli/2015/09/10/tasks-are-still-not-threads-and-async-is-not-parallel/

**Comment by brockallen** [comment]
Not anymore.

**Comment by leastprivilege** [comment]
Decide after reading

https://devblogs.microsoft.com/dotnet/configureawait-faq/

**Comment by brockallen** [comment]
> Decide after reading

So it boils down to: do we care about the "small perf overhead", according to his article. Well, do we?
