### ISSUE TITLE
Access Token Save in DB

### ISSUE THREAD

**Issue by AlexGnatuyk** [IdentityServer/IdentityServer4#1496]
Hi,
I am using  identityserver4. My question is very simple that how can i save my access token in my DB because I have a scenario in which i want to save my access token in DB. Can anyone please guide me how can i do this?
Thanks in advance.

Regards,
Alex

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
