### ISSUE TITLE
ArgumentException: Invalid cookie value when login with more than one client

### ISSUE THREAD

**Issue by ircnelson** [IdentityServer/IdentityServer4#15]
When I try login with more than one client, the idsrv4 throws an ArgumentException (Invalid cookie value).

[stacktrace](https://gist.github.com/ircnelson/dffb860782e7cd0825a4)

**Comment by brockallen** [comment]
This seems to be a problem in ASP.NET Core: https://github.com/aspnet/HttpAbstractions/issues/535

**Comment by ircnelson** [comment]
[This commit](https://github.com/IdentityServer/IdentityServer4/commit/359c5d4b86e8b2d302a3389dd5a46b462810aa79) solved the problem with SSO. Thks @brockallen to fix it.
