### ISSUE TITLE
Could not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127

### ISSUE THREAD

**Issue by MaorWithM** [IdentityServer/IdentityServer4#150]
I've been doing the "Getting Started: JS Authentication & Web APIs" guide,
At part 2 when running the web api i get the following exception :
 "Could not load type 'System.IdentityModel.Tokens.TokenValidationParameters' from assembly 'System.IdentityModel.Tokens.Jwt, Version=5.0.0.127, Culture=neutral"

The configuration used in the Startup : 

            app.UseCors(CorsOptions.AllowAll);

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44300",

            
                ClientId = "api",
                ClientSecret = "api-secret",

                RequiredScopes = new[] { "api" }
            });

       
            var httpConfiguration = new HttpConfiguration();
            httpConfiguration.MapHttpAttributeRoutes();
            httpConfiguration.Filters.Add(new AuthorizeAttribute());

            app.UseWebApi(httpConfiguration);

Any ideas to what can be done?

**Comment by leastprivilege** [comment]
I am confused. The walkthrough is for identityserver3 - but this is the identityserver4 repo.

**Comment by MaorWithM** [comment]
You right, excuse me for the mistake.
I should have posted the issue on "IdentityServer3.AccessTokenValidation"

**Comment by leastprivilege** [comment]
access token validation in OWIN is not compatible with system.identitymodel v5 - you need to downgrade to v4.

**Comment by brentschmaltz** [comment]
OWIN (Katana) has been upgraded to work with IdentityModel v5.
see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/Migrating-from-Katana-(OWIN)-3.x-to-4.x
