### ISSUE TITLE
Federation Gateway 

### ISSUE THREAD

**Issue by ikeamster** [IdentityServer/IdentityServer4#1500]
I understand the OAUTH2 flow with IDSRV4 and we're currently implementing token access and user authentication with open ID connect. I've done the external authentication quick-start and read the docs about external providers. 

Aside from listed concepts, nothing solid is telling me how do you set up IDSRV4 to be a federation gateway? I'm still not clear on how to configure the server and a user client. 

Much help would be appreciated.

**Comment by TomCJones** [comment]
http://docs.identityserver.io/en/release/topics/federation_gateway.html

**Comment by kibagami-jubei** [comment]
@TomCJones Thanks for the reply. 

Yeah, I read that Tom, I mention that in my post but not as clearly, but I also read this article too. https://www.identityserver.com/articles/identityserver4-ws-federation-and-sharepoint/

I'm just wondering if above link is the way to go - which it sounds like to me.

**Comment by ikeamster** [comment]
@TomCJones 

Thanks for the reply;   read that article but it's still not clear to me. I'm also reading about this: https://www.identityserver.com/articles/identityserver4-ws-federation-and-sharepoint/ 

Is this, the above link, the way to go or the complete or the complete opposite direction?

**Comment by leastprivilege** [comment]
A federation gateway is a IS4 with support for external providers. That's it.

**Comment by leastprivilege** [comment]
Think of a "federation gateway" as a pattern - not a specific configuration.

**Comment by ikeamster** [comment]
@leastprivilege Thanks for the reply. I really, really appreciate it. 

I'm coming to find out this is bit of misnomer. Sounds like it can mimic the architecture, more so, and that's it? But if I wanted to go the extra mile then I would need to implement my own ws-federation endpoint, like (how Scott Brady did) in that link I posted, or wait until the team releases an official NUGET plugin (like how they did for IDSRV3). Am I right? Does that sound about right?

**Comment by leastprivilege** [comment]
The ws-fed endpoint means that IS supports more than one protocol as an IdP - 

the fed gateway means that IS itself is a **client** to more than one IdP.

I know it is confusing ;)

**Comment by mudasseriqbal** [comment]
> I understand the OAUTH2 flow with IDSRV4 and we're currently implementing token access and user authentication with open ID connect. I've done the external authentication quick-start and read the docs about external providers.
> 
> Aside from listed concepts, nothing solid is telling me how do you set up IDSRV4 to be a federation gateway? I'm still not clear on how to configure the server and a user client.
> 
> Much help would be appreciated.

were you able to solve the issue ?
