### ISSUE TITLE
Getting null AccessToken when using ResourceOwnerPasswordValidator in Integration Test.

### ISSUE THREAD

**Issue by masaab** [IdentityServer/IdentityServer4#1502]
I am successfully getting a accessToken if I dont use custom  implementation of IResourceOwnerPasswordValidator. But If I use a custom implementation like below.
It is showing **invalid_grant**.

**IdentityServerSetup.cs**

```
    public async Task<string> GetAccessTokenForUser(string userName, string password, string clientId = "client", string clientSecret = "secret")
        {
            var client = new TokenClient(TokenEndpoint, clientId,clientSecret, innerHttpMessageHandler:_handler);
            var response = await client.RequestResourceOwnerPasswordAsync(userName, password, _apiName);
            return response.AccessToken;
        }
```

```
**Startup.cs**
`  services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();`


**ResourceOwnerPasswordValidator.cs**

 public class ResourceOwnerPasswordValidator : IResourceOwnerPasswordValidator
    {
        public ResourceOwnerPasswordValidator()
        {
        }
        public Task ValidateAsync(ResourceOwnerPasswordValidationContext context)
        {
            context.Result = new GrantValidationResult(context.UserName, "password");
        }
    }
```

**Comment by leastprivilege** [comment]
Check the log differences between the two implementations.

**Comment by masaab** [comment]
I am getting this error in the Logs.

User has been disabled: user
IdentityServer4.Validation.TokenRequestValidator:Error: {
  "ClientId": "client",
  "GrantType": "password",
  "Scopes": "api.public",
  "UserName": "user",
  "Raw": {
    "grant_type": "password",
    "username": "user",
    "password": "***REDACTED***",
    "scope": ".api.public"
  }
}

**Comment by masaab** [comment]
The solution is to use IProfileServices.
