### ISSUE TITLE
Flow Suggestion

### ISSUE THREAD

**Issue by imperugo** [IdentityServer/IdentityServer4#151]
Hi, 
I'm migrating an "old" application based on Idsrv3 (1.6.3) to Idsrv4 but I'm going to refactor some part of the code and I need an advice by you about the right flow.

Basically my application is build with several actors:

- **idsrv**(only authentication)
- **webapp** (MVC app)
- **backoffice** (Admin area SPA)
- **jobs** (async scheduled operations)
- **bus worker role** (NServiceBus dispatcher)
- **API** (all the endpoint called by the WebApp, Backoffice and Jobs)

The web app (is the app with the highest traffic) must be compatible with old browser, so IE8 (I know, but is a customer constrain), it means I can't use CORS to call the APIs and I've to wrap all the XHR calls into the MVC application who will forward them to the APIs.

So the APIs must be called directly (via the **Backoffice** SPA who doesn't have the CORS problem),  using a proxy in case on MVC application (CORS problems) of via code in case of Jobs (it's c#).

For the first two cases, into the APIs I need to know some info about the logged users (roles/claims).

What is the best way to do that?

Thanks

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
