### ISSUE TITLE
RequestResourceOwnerPasswordAsync internal server error

### ISSUE THREAD

**Issue by sergeu90** [IdentityServer/IdentityServer4#1511]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

 var tokenClient = new TokenClient(discoveryResponse.TokenEndpoint, AppConstants.ClientId,
                    AppConstants.Secret);

                tokenResponse = await tokenClient.RequestResourceOwnerPasswordAsync(email, password,
                    IdentityServerConstants.StandardScopes.OfflineAccess);
I have error 
![image](https://user-images.githubusercontent.com/7217517/30297459-830433e2-9750-11e7-8603-221714cc8517.png)

I have 2.0.0-rc1 version.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by sergeu90** [comment]
My issue was in the migrations.

**Comment by DmytroMyslyvets** [comment]
sergeu90,  у вас получилось решить эту проблему?

**Comment by sundarkurs** [comment]
I'm also facing the same issue, what was the migration error you had. Seems recently I update the migration to remove one of the field added in AspNetUsers table. And how did you fix the issue?
Thanks
