### ISSUE TITLE
With latest identity server I get 404 on authorize endpoint

### ISSUE THREAD

**Issue by ashtonkj** [IdentityServer/IdentityServer4#1512]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

I am not sure what I am doing wrong (but obviously I am missing something). Everything works (in the Identity Server host and connected API), except for the authorize endpoint. Any assistance would be appreciated. 

### Issue / Steps to reproduce the problem

Startup.cs contains the following 

services.AddIdentityServer(options =>
            {
                options.Events.RaiseSuccessEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseErrorEvents = true;
                options.Endpoints.EnableAuthorizeEndpoint = true;
            })
                .AddDefaultEndpoints()
                .AddRequiredPlatformServices()
                .AddResourceStore<ApiResourceStore>()
                .AddDeveloperSigningCredential()
                .AddPersistedGrants()
                .AddClientStore<ClientStore>()
                .AddAspNetIdentity<ApplicationUser>();

### Relevant parts of the log file

[06:55:28 Information] IdentityServer4.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.AuthorizeEndpoint" for "/connect/authorize/login"

[06:55:28 Information] Microsoft.AspNetCore.Hosting.Internal.WebHost
Request finished in 27.7207ms 404

**Comment by ashtonkj** [comment]
Just to make this 100% clear - this is using IdSrv 4 prerelease for .net core 2.

**Comment by brockallen** [comment]
Not enough info.

**Comment by ashtonkj** [comment]
Closing this issue. Bug was on my side. Once I had the Id Server code running on my machine where I could step through it, the issue was easy to spot and resolve.

**Comment by rbeauchamp** [comment]
hi @ashtonkj , what was the root cause? thanks!
