### ISSUE TITLE
Unhandled exception when IsActive = false

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1513]
that's unexpected! 

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at IdentityServer4.Services.DefaultUserSession.<CreateSessionIdAsync>d__16.MoveNext()

**Comment by devoution013** [comment]
thx i am having this issue as well,

do you have a workaround we can use ?

**Comment by brockallen** [comment]
Moar infoz, plz. 

I tried to repro via authorize flow, but I can't repro. I set a test user to active = false (I added an IsActive flag to our TestUser and check it from the TestuserProfileService ), and I just get sent back to the login page.

**Comment by brockallen** [comment]
Ah, nevermind -- I found it. This is a dup of this, and as such has already been fixed (that's why I couldn't repro): https://github.com/IdentityServer/IdentityServer4/pull/1488
