### ISSUE TITLE
Make Endpoint class public to allow custom routing

### ISSUE THREAD

**Issue by tillig** [IdentityServer/IdentityServer4#1514]
I'm attempting to replace the discovery endpoint and possibly the endpoint router in an effort to provide a solution [similar to his Azure AD solution](http://www.cloudidentity.com/blog/2014/08/26/the-common-endpoint-walks-like-a-tenant-talks-like-a-tenant-but-is-not-a-tenant/) where tenant is a URL parameter.

I'm running into a challenge, though, with the fact the `IdentityServer4.Hosting.Endpoint` class is internal - in order to replace the "Discovery" endpoint, I have to either do some interesting reflection (so I can look in the `IServiceCollection` and find the `Endpoint` singleton that's already been registered) or craft my own `IIdentityServerBuilder` _before_ calling `services.AddIdentityServer()`. This is because registration _order_ of the endpoints appears to matter - the first one found in the service collection that matches the path is used, and that is always the default one rather than mine.

I also want to try introducing some route template support into a custom `IEndpointRouter` but, again, I can't get to the list of registered `Endpoint` objects very easily because `Endpoint` is internal.

**Any way `Endpoint` can be made public before the final 2.0 release?**

**Comment by tillig** [comment]
Somewhat related, though I can open a different issue if desired: The `EndpointRouter` specifically has [a test to ensure the first registered route mapping is used](https://github.com/IdentityServer/IdentityServer4/blob/dev/test/IdentityServer.UnitTests/Hosting/EndpointRouterTests.cs#L85), which effectively _also_ ensures no one can override any of the default routes since the conforming DI container behavior is to return the `IEnumerable<T>` in the order of registration. I think in .NET Core this should be _finds the last registered mapping_ so overrides are possible.

**Comment by tillig** [comment]
Looks like @brockallen had [an unanswered comment on 1364](https://github.com/IdentityServer/IdentityServer4/issues/1364#issuecomment-320474162) wondering if routes should be replaceable. I think so, and it'd be easy enough to do that.

Technically a custom `IEndpointRouter` could bypass use of any existing registered `Endpoint` objects and re-register everything in a custom way to do it, but it'd be nice to be able to get the same effect with less work.

**Comment by tillig** [comment]
It occurred to me this morning that depending on the _order_ of the `IEnumerable<Endpoint>` is actually a subtle gotcha. The Microsoft conforming container has a specific behavior, other containers have tried to adapt to that behavior, but it's not really guaranteed. There's a big `Microsoft.Extensions.DependencyInjection` issue about that I can dredge up if you want to read one of the longest issues EVAR.

Point being, it would be good to have the ability to specify an `Order` for each endpoint if there's the ability to add endpoints. The ASP.NET Core stuff was too far along to do that in some cases, but they agreed that's the more accurate way to go. That would also stop folks from having to `Insert` into the `IServiceCollection` or whatever - just add a new `Endpoint` with a lower `Order`.

It makes me wonder if `Endpoint` should actually be more like this:

```csharp
public abstract class Endpoint
{
  public string Id { get; set; }
  public int Order { get; set; }
  public Type Handler { get; set; }
  public abstract bool Match(HttpContext context);
}

public class PathEndpoint
{
  public PathString Path { get; set; }
  public override bool Match(HttpContext context)
  {
     return context.Request.Path.StartsWithSegments(this.Path);
  }
}
```

With something like that, not only could one handle ordering correctly, you could also change the logic for path matching from _outside the `EndpointRouter`_ so extensions wouldn't necessarily need a whole custom router.

BUT! This drifts a bit from the original request. I can live with a simple public `Endpoint` and still work around everything else.

**Comment by brockallen** [comment]
Done, thanks

**Comment by joeaudette** [comment]
@tillig I've been using a fork in order to be able to use an extra url segment in all of the endpoint urls. This issue makes me think maybe it is now possible to do that without forking. I wonder if you could elaborate on how to do it to help me out?

pretty much just like that article you linked, I want to be able to use urls like

    domain/tenantsegment/therestoftheidserverendpointpath

where the tenantsegment is how I resolve the tenant. Are you doing something like that? and if so any pointers on how to achieve it would be greatly appreciated

**Comment by tillig** [comment]
@joeaudette Read through PR #1576 for a walkthrough with code of what I'm doing.

**Comment by joeaudette** [comment]
@tillig many thanks! that looks promising for my needs, I will give it a try in my solution.

**Comment by natelaff** [comment]
@tillig do you happen to have a full example in one of your repos? Possibly updated for current versions of IS4? :) trying to wrap my head around some of what you have happening, but there are missing pieces that I'm not quite sure what's going on there. thank you!

**Comment by tillig** [comment]
I don't have anything I can make public other than what I've provided, sorry.

**Comment by natelaff** [comment]
@tillig no worries. Maybe you can just clarify a few things?

- What is TransparentObject in AddMultitenantRouting()?
- With the changes made do you still require PathEndpoint?
- IdentityServerEndpointType. Was this yours, or did IS4 change something?

Thanks for any clarification :)

**Comment by tillig** [comment]
Sorry, it's been two years since this code, I'm not on that project anymore, and I'm on vacation for the next two weeks. I hate to say it, but what's here in this thread is all I can do for you.
