### ISSUE TITLE
Assistance Building Project

### ISSUE THREAD

**Issue by jonathaneckman** [IdentityServer/IdentityServer4#1517]
- [x ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
1. Download source code from 2.0.0-rc1.
2. Run build.ps1.
3. Errors.

![image](https://user-images.githubusercontent.com/11893200/30352475-0b18b2c4-97ee-11e7-9468-1a0d2605db2a.png)

and errors on build still:

![image](https://user-images.githubusercontent.com/11893200/30352488-1c07f23e-97ee-11e7-9544-e94a97160416.png)

**Comment by brockallen** [comment]
Can you create any new ASP.NET Core 2 projects on your machine?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
