### ISSUE TITLE
Consider making the requested scopes/resources available in ProfileService

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1519]
in addition to claim types.

**Comment by eddietisma** [comment]
I have encountered the need for this in a situation at my work. Where some clients are requesting scopes for information which is specific to a certain login provider. At the same time we're trying to transition all users/clients to a new provider (which involves a breaking change of user information and claims). During this transition period i need to provide backwards compatibility to old clients with information/claims that they are requesting, hence we're always fetching user information from the older provider (currently stored in a db). 

With this we would be able to only issue db calls when needed and thereby reducing unnecessary login time.

**Comment by leastprivilege** [comment]
You can always get to the information by deriving from our `DefaultClaimsService` - but yeah - considering putting the requested resources on the profile request context.

**Comment by brockallen** [comment]
Done
