### ISSUE TITLE
Question: asp.net 4.5 obtain token and call asp.net core API

### ISSUE THREAD

**Issue by nigel-dewar** [IdentityServer/IdentityServer4#1520]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

Hi There, I have read through the docs but I cannot find an answer Im looking for sorry.

Here is what I would like to know.

I have 4 peices to the puzzle

- asp.net core running IdentityServer4
- asp.net core API
- asp.net 4.5 API (using OWIN middleware and IdenityServerValidation3)
- an html client which authenticates using OIDC client

I wish to have the client call the asp.net 4.5 API, which validates the token (I know how to do that), but then I want to call the asp.net core API from the asp.net 4.5 API - to do some additional work which I couldnt do in my asp.net 4.5 (Its a long story). 

I believe what I am seeking to do in my asp.net 4.5 is use to same token passed from the html client, and re-use this passing it again to the second (asp.net core) API.

Is this all legit?   possible?

Cheers

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
