### ISSUE TITLE
Bad Request - Request Too Long - Http Error 400

### ISSUE THREAD

**Issue by callranjithkani** [IdentityServer/IdentityServer4#1521]
Hi,

Bad Request - Request Too Long - Http Error 400

Have you got answer, me too face this same issue, my sso proxy developed by asp.net core 1.1 and few client applications also developed by core 1.1 it's working fine, if i try to implement 4.5.2 developed client app i faced Bad Request - Request Too Long Error, have any idea please let me know

My Response URI:

http://localhost:4000/connect/authorize?client_id=devtest&redirect_uri=http%3a%2f%2flocalhost%3a4002%2fsignin-oidc&response_mode=form_post&response_type=id_token+code&scope=openid+profile&state=OpenIdConnect.AuthenticationProperties%3dO3LnGgSMQdDkOZI9AxWTqT9183vBYw7YcEPAoRENX5Kg0zp6Qr4MBOI96fJ2rOFX64ka4S7zPwjezWfTZz6J7OQ_D-_eHbYSOamRdV8_BoRghBopcmwGXdGTKRuPTxilO9p3exS5NL6AjeydBZD-5o9eJxR_x46r43jAwvnN0TwjwUq-i9KJ2HpxbM-lTEloQ6pXo-FVhQoBTEdJJTHgmqeuH80l5E_0hlLGFb0wg5E&nonce=636409049642654741.MzE5YWJkOWQtMTAyMy00YTcxLWExMjYtNTI2YjA2NWI0ZmFmYmY4Njc2MDEtNWY3Ni00NjdiLWI5ZjctMTE1MTQ1YTRiOGQ5

**Comment by rizamarhaban** [comment]
Can share the config file? Make sure the ```RedirectUris``` (Client config) and ```RedirectUrl``` (OpenIdConnectAuthentication options) ends with '/' in the configuration.

``` csharp
RedirectUris = { 'http://localhost:4002/' },
```

Try that first.

**Comment by callranjithkani** [comment]
@ rizamarhaban : Thanks lot it's working :)

**Comment by brockallen** [comment]
So we can close this now?

**Comment by callranjithkani** [comment]
Please close this issue :)

**Comment by callranjithkani** [comment]
@brockallen Please close this issue :)

**Comment by fatihapaydin** [comment]
@rizamarhaban 
while(true){
Console.WriteLine("Thank you very much :)");
}

**Comment by santhudr** [comment]
Hi,
 I've the same issue, but my redirect url already has got '/' at the end of redirecturl:
http://localhost/AuthServer/identity/wsfed/?wa=wsignin1.0&wtrealm=http%3a%2f%2flocalhost%2fmvcclient%2f&wctx=rm%3d0%26id%3dpassive%26ru%3d%252fMVCClient%252f&wct=2018-08-29T12%3a47%3a59Z

Any idea?

**Comment by peterkarman1** [comment]
@santhudr probably figured this out already but delete your cookies after the above fix
