### ISSUE TITLE
[Question] Enable response_type extension

### ISSUE THREAD

**Issue by ycrumeyrolle** [IdentityServer/IdentityServer4#1527]
As defined per (RFC6749)[https://tools.ietf.org/html/rfc6749#section-8.4], the response_type should be extensible. 
I did not see a way to extend this part, as the Constants.SupportedResponseType is internal.

The goal is to support the `none`  value and/or other values (like a `federation` value)

**Comment by leastprivilege** [comment]
We don't support extending the response types.

If you think that feature is needed please open a feature request and explain the scenarios in detail.
