### ISSUE TITLE
User.Identity.Name Returns null

### ISSUE THREAD

**Issue by callranjithkani** [IdentityServer/IdentityServer4#1528]
Hi,
**User.Identity.Name Returns null**
Have you got answer, me too face this same issue, my SSO proxy developed by asp.net core 1.1 and few client applications also developed by core  1.1 it working fine , if i try to implement 4.5.2 developed client app it authenticated successful , but try to retrieve user name i faced this issue.
 , have any idea please let me know

My Code:

        [Authorize]
        public ActionResult Index()
        {
           ClaimsPrincipal icp = Thread.CurrentPrincipal as ClaimsPrincipal;
            // Access IClaimsIdentity which contains claims
            ClaimsIdentity claimsIdentity = (ClaimsIdentity)icp.Identity;
            Response.Write("User Name:"+ User.Identity.Name + "<br>");
            // Access claims
            foreach (Claim claim in claimsIdentity.Claims)
             {
                Response.Write(claim.Type+"<br>");
                Response.Write(claim.Value + "<br>");
                Response.Write(claim.ValueType + "<br>");
            }
            return View();
        }

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
