### ISSUE TITLE
[Question] How to return code via windows authentication?

### ISSUE THREAD

**Issue by XaveScor** [IdentityServer/IdentityServer4#1529]
User can authenticate via form or windows auth. I need to get code in both scenarios. How to do that?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
