### ISSUE TITLE
No IAuthenticationSignOutHandler is configured to handle sign out for the scheme: oidc in .net core with identity server 4

### ISSUE THREAD

**Issue by rahulmistry25425** [IdentityServer/IdentityServer4#1531]
Hello,

I am migrating my identity server based project from .net core 1 to 2, i am facing this issue while i am trying to logout

Here is screen shot of error.
![image](https://user-images.githubusercontent.com/15902578/30479439-d9e6cf28-9a32-11e7-8fa1-fb1d3f6214cb.png)

In ConfigureService in **client**

```
services.AddAuthentication(options =>
                    {
                        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                    })
                    .AddCookie(options =>
                    {
                        options.LoginPath = "/account/login";
                        options.AccessDeniedPath = "/account/denied";
                    })
                    .AddOpenIdConnect(options =>
                    {
                        options.Authority = Configuration["ASAP-IdentityServer-Url"];
                        options.ClientId = "#########";
                        options.ClientSecret = "########";
                        options.GetClaimsFromUserInfoEndpoint = true;
                        options.SignedOutRedirectUri = "http://localhost:5002";
                        options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        options.ResponseType = "code id_token";
                        options.RequireHttpsMetadata = false;
                        options.SaveTokens = true;
                        options.Scope.Add("openid");
                        options.Scope.Add("profile");
                        options.Scope.Add("offline_access");
                        options.TokenValidationParameters = new TokenValidationParameters
                        {
                            NameClaimType = "name",
                            RoleClaimType = "role"
                        };
                    });

```

also used 
`app.UseAuthentication();`
 in configure method.

Here is my logout action method

```
public IActionResult Logout()
        {
            return SignOut("Cookies", "oidc");
        }
```

Please let me know if any further information needed or not

**Comment by brockallen** [comment]
Set the OIDC SignOutScheme to be "Cookies"

**Comment by rahulmistry25425** [comment]
```
services.AddAuthentication(options =>
                    {
                        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                        options.DefaultSignOutScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    })
```
still not working

**Comment by brockallen** [comment]
So you realize this problem is unrelated to IdentityServer, since this code is all in your client. Microsoft should be the ones to support their framework.

**Comment by rahulmistry25425** [comment]
So as per my understanding still identify server 4 is not stable with .net core 2?

**Comment by rahulmistry25425** [comment]
Because its seems like there are many changes held in .net core 2 version...so do you know when should be we able to get identify server 4 examples with .net core ?

**Comment by rmja** [comment]
I had a very similar issue when using idsrv.AspNetIdentity. For me the culprit was [this assignment](https://github.com/aspnet/Identity/blob/74c1e19e6c14359d428ffe803a93d846b2123a63/src/Microsoft.AspNetCore.Identity/IdentityServiceCollectionExtensions.cs#L70), and the default fallback for DefaultSignOutScheme is DefaultSignInScheme.
But the cookie (in my case) was issued with the scheme `IdentityConstants.ApplicationScheme`
So instead of `HttpContext.SignOutAsync()` I did this instead:

```
await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
```

**Comment by rahulmistry25425** [comment]
@rmja Thanks for your suggetions.it works for me

**Comment by shobhitkasliwal** [comment]
I am facing the same issue. 
services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;

            })
            .AddCookie()
            .AddOpenIdConnect(options =>
            {....}

Can you please let me know how to make logout working with Identity Server 4

**Comment by rahulmistry25425** [comment]
@shobhitkasliwal 

 ```
services.AddAuthentication(options =>
                    {
                        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        options.DefaultSignOutScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                        options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                    })
```

In Logout Action Method

`            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);`

**Comment by roblapp** [comment]
I am having this issue when using the Quickstart UI. I have the following:

```
services.AddAuthentication()
            .AddGoogle("Google", options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;

                options.ClientId = "708996912208-9m4dkjb5hscn7cjrn5u0r4tbgkbj1fko.apps.googleusercontent.com";
                options.ClientSecret = "wdfPY6t8H8cecgjlxud__4Gh";
            })
```

and my Logout endpoint looks like this:

```
public async Task<IActionResult> Logout(LogoutInputModel model)
        {
            var vm = await this.accountViewService.BuildLoggedOutViewModelAsync(model.LogoutId);

            var user = this.HttpContext.User;
            if (user?.Identity.IsAuthenticated == true)
            {
                await this.HttpContext.SignOutAsync();

                // raise the logout event
                await this.eventsService.RaiseAsync(new UserLogoutSuccessEvent(user.GetSubjectId(), user.GetDisplayName()));
            }

            if (!vm.TriggerExternalSignout)
            {
                return this.View("LoggedOut", vm);
            }

            return this.SignOut(
                new AuthenticationProperties
                {
                    RedirectUri = this.Url.Action("Logout", new { logoutId = vm.LogoutId })
                },
                vm.ExternalAuthenticationScheme);
        }
```

I don't understand why this doesn't work. I registered the Google middleware as 'Google' scheme and that is what `vm.ExternalAuthenticationScheme` is passing to the SignOut method. Am I missing something obvious?

**Comment by brockallen** [comment]
Google doesn't support signout.

**Comment by roblapp** [comment]
Thanks for clarifying

**Comment by RandyCh** [comment]
I have a similar issue
` .AddMicrosoftAccount("aad", "Azure AD", options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.ClientId = "#######";
                options.ClientSecret = "######";
            });`
Does Azure not support signout,either?
I get providerSupportsSignout equal false.
' var providerSupportsSignout = await _httpContextAccessor.HttpContext.GetSchemeSupportsSignOutAsync(idp);`
Am I Missing settings?
Any suggestions would be appreciated.
