### ISSUE TITLE
Mixed cookie authentication and IdentityServerAuthenticationService

### ISSUE THREAD

**Issue by mpetito** [IdentityServer/IdentityServer4#1533]
I have an ASP.NET Core 2.0 project using ASP.NET Identity with a mix of Cookie Authentication and Identity Server Authentication.  Identity Server 2.0.0-rc1 is also hosted within the same project.

After configuring IdentityServer, `PasswordSignInAsync` fails when using the ASP.NET Identity `SignInManager` to perform typical form / cookie based login.

The default `AddIdentityServer` extension method for `IServiceCollection` [adds a decorator](https://github.com/IdentityServer/IdentityServer4/blob/53f20267d9d1858869c7cce1810f8062c2b06c6f/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/Core.cs#L58) around `IAuthenticationService` via the internal extension `AddCookieAuthentication`.  This decorator asserts that the authenticated principal contains a `sub` claim, which the default identity `ClaimsPrincipalFactory` does not provide.

I can see how this claim makes sense for JWT.  But when hosting IdentityServer within a project which also uses Cookie Authentication, this assertion fails (because the ClaimType used in this case is `NameIdentifier`).

I'm not clear on the purpose of the `IdentityServerAuthenticationService` and the internal `AddCookieAuthentication`.  Should this be opt-in, or is there a better way to configure this hybrid authentication scenario?

**Comment by mpetito** [comment]
My workaround for now is to register IdentityServer the same way as the extension method, but explicitly without `AddCookieAuthentication`:

```
services.AddIdentityServerBuilder()
        .AddRequiredPlatformServices()
        //.AddCookieAuthentication()
        .AddCoreServices()
        .AddDefaultEndpoints()
        .AddPluggableServices()
        .AddValidators()
        .AddResponseGenerators()
        .AddDefaultSecretParsers()
        .AddDefaultSecretValidators()
```

**Comment by leastprivilege** [comment]
`sub` is a required claim for OpenID Connect, OAuth and hence IdentityServer. Use it instead of name identifier.

**Comment by mpetito** [comment]
@leastprivilege Do you mean that the ASP.NET Identity `UserClaimsPrincipalFactory` should be overridden to provide the `sub` claim? By default it provides the `NameIdentifier` claim instead.

I'm not sure why Identity Server should be involved in `PasswordSignInAsync` in the first place.  If I'm only using it for JWT Bearer authentication, why would it care about cookies at all?

**Comment by leastprivilege** [comment]
IdentityServer needs to keep track of a couple of things to fulfil the protocol requirements. These things are stored in the cookie.

have a look here:
https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/tree/dev/src/Host

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by mpetito** [comment]
@leastprivilege I still believe this is a regression. I understand that authentication has changed from aspnet core 1.1 to 2.0, but the oauth2 protocols have not.

In the prior version with aspnet core 1.1, I could use aspnet identity with cookie authentication in the same project as identity server with bearer authentication.  Now, I can only do so if I change aspnet identity to use the `sub` claim (which I have not yet tested, nor am I sure of the implications).

Instead, my workaround is to skip identity server's internal call to `AddCookieAuthentication()`.  This appears to have no impact on oauth2 *bearer* authentication via identity server.  In fact, the API clients which are using bearer authentication do not even support cookies.

It looks like `AddCookieAuthentication` is used to support the OpenID Connect Session protocol.  I'm not using this at all as I'm just using identity server's token endpoint.  It looks like IUserSession didn't even exist in 1.5.2 - and the support of this protocol introduced in 2.0.0 has broken a previously working integration.

**Comment by brockallen** [comment]
@mpetito did you see this sample? it shows co-hosting IS and an API in the same ASP.NET Core 2 host.

https://github.com/brockallen/IdentityServerAndApi

**Comment by mpetito** [comment]
@brockallen Yes but notably, this example omits any usage of `SignInManager.PasswordSignInAsync`. 
 Instead, it uses `HttpContext.SignInAsync` which is part of ASP.NET Core Authentication.

So this is not an example of co-hosting IS, an API and ASP.NET Identity in the same project.

**Comment by brockallen** [comment]
`SignInManager` is an API from ASP.NET Identity. It uses its own cookies. See the ASP.NET Identity repo for that usage: https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/

**Comment by mpetito** [comment]
@brockallen I think I see the line that I'm missing in my Startup.cs.  It seems there's an `AddIdentityServer` extension method on `IdentityBuilder`.  This reconfigures the ASP.NET Identity claims.

https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/eccf0ae2f9ef1130e317e582d47a5c48bbfadcc5/src/Host/Startup.cs#L36

It would be helpful if the IS ASP.NET Identity docs included that config (the readme only points out `AddAspNetIdentity`).

I may run into another issue, because my project already provides an implementation of `IUserClaimsPrincipalFactory<TUser>`, but I will try this.  Thank you!

**Comment by brockallen** [comment]
Yep, we're still in rc and have not yet gotten to updating the docs for ASP.NET Core 2.0.

you might be able to derive from our `IUserClaimsPrincipalFactory` implementation. if not, then we can consider using a decorator pattern to better work with yours and others' who need their own.

or you can just ignore ours and register yours after ours in DI.
