### ISSUE TITLE
Exchange Facebook, Google ,Twitter access token for IdentityServer access token

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4#1536]
Hi,

Is it possible for you guys to have a new endpoint (or use the existing ones) to provide a feature where applications using ResourceOwner flow or Client credential flow could exchange access token for an access token from external providers from facebook, gmail or twitter. I have already done that for my personal project but would be great if you guys can provide it too.

**Comment by leastprivilege** [comment]
This is called an extension grant. We won't include that in our core library - but it is easy to add yourself. Feel free to publish a contrib library or blog post - and we will to it from out docs.

**Comment by waqaskhan540** [comment]
@leastprivilege thanks.. I will share the code and will let you know..

**Comment by waqaskhan540** [comment]
@leastprivilege  here is the link to my repo for exchanging external (facebook, google , twitter) access token for Identity server access token... Looking forward to your feedback.

https://github.com/waqaskhan540/IdentityServerExternalAuth

**Comment by leastprivilege** [comment]
I opened an issue and updated the readme.

**Comment by waqaskhan540** [comment]
@leastprivilege  thanks.. will be updating soon..

**Comment by rasmuschristensen** [comment]
Hi @waqaskhan540 
It looks really great, just what I need for my own project. Does it also support refreshtokens?

**Comment by rasmuschristensen** [comment]
One question, why do you make the possible extra request if user is not registered. Couldn't you just get the email from the provider and then use that one?

**Comment by waqaskhan540** [comment]
@rasmuschristensen  for now it doesn't support refresh tokens but it can be added.. I will update you If I see its possible..

**Comment by waqaskhan540** [comment]
@rasmuschristensen I have added support for refresh tokens... I had to set AllowOfflineAccess set to true on client.. include an extra scope of 'offline_access' in your token request, you will then get the refresh token as well..thanks.

**Comment by rasmuschristensen** [comment]
Whats the reason for adding the "external" table when you have a similar with AspNetUserLogins from ASPNET Identity?

**Comment by waqaskhan540** [comment]
@rasmuschristensen there is no special reason for that, other than leaving the .NET Identity's table intact..
i'll appreciate a PR..

**Comment by AlexanderButs** [comment]
@waqaskhan540 Thanks for Your work a lot, this is what i needed :-)

**Comment by waqaskhan540** [comment]
@AlexanderButs thanks

**Comment by tknuts** [comment]
Hi. I get an error: "Invalid_client", back from the IdentityServer. I don't seem to have the "external" grant type related to my client. Should I  add this manually? Also i did not add my FacebookProvider via the ExternalProvider in the IdentityServer, but like this:

`             services.AddAuthentication()
                 .AddFacebook("Facebook", options =>
                 {
                     options.AppId = "1320695524728304";
                     options.AppSecret = "a47c53debe9fefcba5e89ecbfa269a88";
                     options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                 })`

How do I get the client and Grat type right ?

Regards, Thomas Kristiansen

**Comment by tknuts** [comment]
If I use grant_type: external, i get: **unsupported_grant_type** back....

**Comment by waqaskhan540** [comment]
@tknuts  can you please share your full Authentication configuration in the Startup

**Comment by tknuts** [comment]
I got it working now, thanks though...

**Comment by waqaskhan540** [comment]
@tknuts cheers

**Comment by sjdkln** [comment]
hi @waqaskhan540 
its great, is there something like this for identity server 3?

**Comment by waqaskhan540** [comment]
@sjdkln 
I wrote this specifically in .net core .. its not available for identityserver 3.. but you can follow the code and write one for yourself..
