### ISSUE TITLE
Is it possible to load different brand templates based on client Id received via authorise url?

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer4#1538]
I have two different clients registered. Is it possible to load different path for templates based on what clientId is received through authorise url?

If I have Microsoft client accessing SSO I want to show Microsoft logo and if I have apple client accessing I want to show Apple logo. How can I do that?

**Comment by leastprivilege** [comment]
You can call the interaction service to find out the client details and then render a different view accordingly 

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/release/Quickstart/Account/AccountService.cs#L33

**Comment by nukec** [comment]
@leastprivilege thanks, we also have sso in Idserv3, is it possible to do it there as well? We don't have controllers there, only config files, or do we have to override controllers?

**Comment by leastprivilege** [comment]
Sure - but it is hard than in IS4. IIRC you need to implement a view service. The docs have more info.

**Comment by Janidbest** [comment]
Perhaps, leaving this luxury of styling to client by providing css to override the defaults would be the easiest way. May be having one more field on the client table to persist styling specific url.
