### ISSUE TITLE
Urls generated with identity server behind LB

### ISSUE THREAD

**Issue by Exocomp** [IdentityServer/IdentityServer4#1539]
I have a case where SSL is handled prior to getting to the box that hosts identity server, so the setup is Client/https -> SSL Box/http -> Identity Server.  

In this scenario the urls (issuer, jwks_uri, authorization_endpoint, etc) generated in the discovery document (.well-known/openid-configuration) use http, how can I tell identity server to use https when generating these endpoints in the discovery document based on the above scenario?

**Comment by leastprivilege** [comment]
This has been asked many times already - and is not really an IdentityServer topic. It's an ASP.NET Core deployment topic.

https://identityserver4.readthedocs.io/en/release/topics/deployment.html

**Comment by rizamarhaban** [comment]
@Exocomp see PublicOrigin and IssuerUrl property.

**Comment by Exocomp** [comment]
@leastprivilege Thanks for the quick response.  Adding both 'X-Forwarded-For' and 'X-Forwarded-Proto' resolved the issue.
