### ISSUE TITLE
IdentityServer4 on docker

### ISSUE THREAD

**Issue by VenkateshSrini** [IdentityServer/IdentityServer4#1541]
Hi,
My application is in .NET core 2.0. I want to create a centralized A&A server that can connect to an Azure LDAP and perform Authentication and also Authorization. I would want this microService to be in .NET core 2.0 in a _Docker container_

So the ask is 
1) Is there an official docker image provided by the creators for identityServer 4
2) Do you have an .NET 2.0 standard compliant IdentityServer4
3) If there are no docker images then can you please provide some guidance for creating the same.

Thanks

**Comment by leastprivilege** [comment]
Given the nature of IdentityServer, a base image would not make sense. Your base image would be the ASP.NET Core 2.0 image where you "deploy" IdentityServer to.

**Comment by VenkateshSrini** [comment]
@leastprivilege,
I'm still not able to understand what you are saying. Could you please clarify what you mean by saying "Given the nature of IdentityServer, a base image would not make sense". My requirement is I need the Identity server to be able to authenticate application that are running out of docker. The identity server should also run as a docker container. So having said this it would be great if you can guide me to sample which does this end to end or some links that will help me do this

**Comment by leastprivilege** [comment]
I think you need to learn Docker first.

https://docs.microsoft.com/en-us/aspnet/core/publishing/docker

**Comment by VenkateshSrini** [comment]
@leastprivilege,
Thanks for the link. In fact I have attend docker training in Weighbee and have deployed an API app and Postgress in two different container and have linked them using compose and put in on swarm. By point is I want to understand that what is that nature of identity server that prevenst it from putting it in docker

**Comment by leastprivilege** [comment]
Nothing. It is just a library inside a normal ASP.NET Core application.

**Comment by VenkateshSrini** [comment]
@leastprivilege,
So that means we need some host process like ASP.NET core to use this library and host that app in container is it? If that is case do we need any special consideration like subnet mask that we need to take care? DO we have some guidance on how to get this working on docker
