### ISSUE TITLE
2.0.0rc1 - InvalidOperationException: sub claim is missing

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer4#1545]
After upgrading to 2.0.0rc1 I get this while trying to log in:

> InvalidOperationException: sub claim is missing

Code is not changed just settings.

All I did was to remove app.UseIdentity() and replaced with app.AddAuthentication();
Same thing in Configure method in Startup.cs.

> Application version: 1.0.0.0
> AspNetCoreEnvironment: Development
> Client IP address: 127.0.0.1
> DeveloperMode: true
> Event time: 20/09/2017 18:59:30
> Exception type: System.InvalidOperationException
> handledAt: Platform
> Message: sub claim is missing
> Node name: DESKTOP-NOBHIJ3
> Operation ID: e48aaa36-41282e80d87e671d
> Operation name: POST Account/Login
> Operation parent ID: |e48aaa36-41282e80d87e671d.
> Problem ID: System.InvalidOperationException at IdentityServer4.IdentityServerPrincipal.AssertRequiredClaims
> Role instance: DESKTOP-NOBHIJ3
> SDK version: aspnet5c:2.1.1
> Session ID: vG4WH
> User ID: UJE4K
> 
> Stack Trace
> System.InvalidOperationException: sub claim is missing
>     at  IdentityServer4.IdentityServerPrincipal.AssertRequiredClaims
>     at  IdentityServer4.Hosting.IdentityServerAuthenticationService.AugmentPrincipal
>     at  IdentityServer4.Hosting.IdentityServerAuthenticationService+<SignInAsync>d__7.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Identity.SignInManager`1+<SignInAsync>d__30.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Identity.SignInManager`1+<SignInOrTwoFactorAsync>d__52.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  System.Runtime.CompilerServices.TaskAwaiter`1.GetResult
>     at  Microsoft.AspNetCore.Identity.SignInManager`1+<PasswordSignInAsync>d__33.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  System.Runtime.CompilerServices.TaskAwaiter`1.GetResult
>     at  Microsoft.AspNetCore.Identity.SignInManager`1+<PasswordSignInAsync>d__34.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  System.Runtime.CompilerServices.TaskAwaiter`1.GetResult
>     at  IdentityServerWithAspNetIdentity.Controllers.AccountController+<Login>d__10.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  System.Runtime.CompilerServices.TaskAwaiter`1.GetResult
>     at  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow
>     at  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next
>     at  Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow
>     at  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next
>     at  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  IdentityServer4.Hosting.IdentityServerMiddleware+<Invoke>d__4.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__7.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  IdentityServer4.Hosting.BaseUrlMiddleware+<Invoke>d__3.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware+<Invoke>d__7.MoveNext
>     at  System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
>     at  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
>     at  Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext
> 
>

**Comment by laorient** [comment]
If it is an existing account in your AspNetIdentities tables, then add "sub" and "name" claims into the AspNetClaims table and you should be good.

**Comment by mrf460** [comment]
Find this line in Startup.cs confgiureservices

services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                **.AddIdentityServer()**
                .AddDefaultTokenProviders();

make sure .AddIdentityServer() is there.  That's what solved it for  me

**Comment by nukec** [comment]
@mrf460 that was the thing. I forgot to add **AddIdentityServer().**
