### ISSUE TITLE
Getting a 400 error on /Account/Login upon signing in IE 11- looks like antiforgery token issue

### ISSUE THREAD

**Issue by MVC2013** [IdentityServer/IdentityServer4#1548]
- [X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

1. I am navigating to /connect/authorize in IE 11 with the following query string values: client_id, response_type, scope, redirect_uri, state, nonce. I get successfully redirected to /account/login, and I am able to successfully sign in.

2. After submitting the form, my session begins as expected, but my address bar still shows /account/login and a 400 error is returned- the page does not load successfully.

### Relevant parts of the log file

```
**Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter**
Antiforgery token validation failed. The provided antiforgery token was meant for a different claims-based user than the current user.
```

**Comment by leastprivilege** [comment]
Seems to be an MVC / ASP.NET Core problem. Please open an issue with Microsoft as well.

**Comment by MVC2013** [comment]
Looking into that- thank you for the fast response!

**Comment by brockallen** [comment]
All set on this issue -- can we close?
