### ISSUE TITLE
ICorsPolicyProvider url restriction

### ISSUE THREAD

**Issue by mtwarowski** [IdentityServer/IdentityServer4#155]
HI Guys!

Sorry to bother byt i've run into an issue trying to use your IdentityServer in my project. To give you a better overview of my current problem my setup is:

- i have a asp core RTM (but that problemy doesn't mater) user restricted Web API with you IdentityServer4 setup as in the sample for SPA. 
- Asp Core ui project with is hosted on different domain the the server. This one is just serving a static files with Angular2 website that is using your js client to authenticate users and request the api with the access token.

So the issue is that in the base implementation of your ICorsPolicyProvider you are allowing only specific paths to be used with CORS. Those paths live in Constants.RoutePaths.CorsPaths read only array. 
All that will cause all other request to the api to be Unauthorized.

So the question what is the best work around this issue? 
Shell i make my own custom implementation of a ICorsPolicyProvider and register it into a a standard Asp Core IoC container?
Or is there a way of specifying that other urls are valid?
Or maybe i'm just and ideat and that's not how we want to interact with the restricted web API?

Hope my description is precised enough.

**Comment by leastprivilege** [comment]
the CORS design is not done yet - we know there are issues.

**Comment by leastprivilege** [comment]
give input if you like #167
