### ISSUE TITLE
Go to login page when token expired

### ISSUE THREAD

**Issue by santiagomolinadecastro** [IdentityServer/IdentityServer4#1552]
- [X ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

Hi all!!

I have a problem. 

Im with token expiration problem. When token is expired, my application go to logout endpoint, but i cant do it (single sign-out by logut page). I wanna to reditect to users to login page.

The steps:

1. User is working
2. Token is expired
3. Redirect to users to Login page.

Now, i could do this:

1. User is working
2. Token is expired
3. Redirect to users to Log out page.

Can you help me?

Thanks!

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
> When token is expired, my application go to logout endpoint, but i cant do it (single sign-out by logut page). I wanna to reditect to users to login page.

This sounds like you need to take more control in your client app.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
