### ISSUE TITLE
Token Access Request Confirmation

### ISSUE THREAD

**Issue by Alchemy86** [IdentityServer/IdentityServer4#1553]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

Im looking to confirm I am using this right. I've checked the examples and docs but cannot find a complete example of what Im trying to do.
Using the quick start 5 project as an example, I have added extra ApiResources, I've then added 2 scopes to the Api Resource.

The user request has been set to this resrouce name, api2. I want the API to confirm the user has read access from API2. So the client is set to be allowed api2, read scopes. api2 is requested buy i dont seem to be able to confirm they have read? If I requested api read for example it would confirm, but if someone doesnt have read access it would give invalid scope.. Is there no setup that can be configured where a client is given read access scoped to a certain API resource, it confirms what the client can and cant do as part of that API??

Im either having to reqest just the API2, then add claims to a user that states what claims they have but then all claims come through on the user.. their access to api1 etc. I simply want to request a key for an API, then have details of what that user can do with reagards to that resource. Is this possible?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
AllowedScopes are what a client has access to, not a user. You do the authorization check in the API for the user. IdentityServer does not have a way to determine if a user is allowed, and that's not its job (by design).
