### ISSUE TITLE
Poor null handling EndSessionResult

### ISSUE THREAD

**Issue by Pastafarian** [IdentityServer/IdentityServer4#1555]
### Issue / Steps to reproduce the problem
Fail to set the LogoutUrl in the user interaction service or set it to a null value. 

`services.AddIdentityServer(x => x.UserInteraction.LogoutUrl = null);`

EndSessionResult blows up on the following line with an unhelpful exception. 

```
if (id != null)
{
      redirect = redirect.AddQueryString(_options.UserInteraction.LogoutIdParameter, id);
}
```

The fix this a null check could be added, something along the following lines.
```

 var redirect = _options.UserInteraction.LogoutUrl;

            if (string.IsNullOrWhiteSpace(redirect))
            {
                throw new ArgumentException("LogoutUrl is null or empty.");
            }
```

Was caught out with this one and had to dig into the source code to figure out what was going wrong. Totally my fault but I'm sure others will be thrown by this issue when implementing logout logic.

**Comment by brockallen** [comment]
I submitted a PR to address this. We do have some cleanup that's related to this, so we'll track it there. Thanks.
