### ISSUE TITLE
Google logout cookie cleanup problem/question

### ISSUE THREAD

**Issue by nixa333** [IdentityServer/IdentityServer4#1556]
I have implemented IS4 server with Google login option. I have a MVC app in .NET Framework 4.7 that authenticates with the mentioned IS4 server.

This are the OpenidConnect settings in MVC app:
```C#
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                CookieHttpOnly = true
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions {
                Authority = ConfigurationManager.AppSettings["Authority"],
                ClientId = ConfigurationManager.AppSettings["ClientId"],
                ClientSecret = ConfigurationManager.AppSettings["ClientSecret"],
                SignInAsAuthenticationType = "Cookies",
                RedirectUri = ConfigurationManager.AppSettings["RedirectUri"],
                ResponseType = "code id_token",
                Scope = "openid profile api.user"
            });
...
        // AccountController in MVC app
        public void LogOut()
        {
            Request.GetOwinContext().Authentication.SignOut();
        }

```
The problem I'm having is when logging in with Google account, and I have several accounts, I choose to login with one of them and everything works fine. When l logout and try to login with any other Google account, I'm again logged in with the first one. I guess this is some kind of cookie cleanup problem, but I don't know how to fix it.

Also, my LogoutUri never gets called by IS.

**Comment by brockallen** [comment]
I'm not quite following, but google doesn't support signout.

**Comment by nixa333** [comment]
I'll try to clarify this so we're sure then whats the problem. So, as you probably know, you can have multiple Google accounts logged in on one machine at the same time. Then,  when you want to log in into an application that supports Google login, Google will display a list of all your accounts and you would choose with which one you'll login with. To get back to my isuse, when I go to my application and want to login with google, I would login with first account from the list (lets call it acc1@gmail.com) and everything works fine. I would then logout from that account using the code mentioned in original question, again go to login with Google and choose the second account from the list(acc2@gmail.com), but again I would be logged in with the acc1@gmail.com. After all that if I open incognito tab and try to login again with acc2@gmail.com, it actually logs me in with that account. That made me think it's a cookie problem. So if this is the issue of Google not supporting sign out, how would I solve it?

**Comment by nixa333** [comment]
I guess this answers my question:
https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/create-an-aspnet-mvc-5-app-with-facebook-and-google-oauth2-and-openid-sign-on#off 

> If you log on to your app with Facebook,, and then log out and try to log in again with a different Facebook account (using the same browser), you will be immediately logged in to the previous Facebook account you used. In order to use another account, you need to navigate to Facebook and log out at Facebook. The same rule applies to any other 3rd party authentication provider. Alternatively, you can log in with another account by using a different browser.

Which pretty much sucks.
I believe there isn't much we can do about it, right @brockallen ?

**Comment by brockallen** [comment]
Yea, that's an implementation detail of those providers.

**Comment by krzyhan** [comment]
I changed default Logout action (from "Quickstart" AccountController)
add this line:
`HttpContext.SignOutAsync(IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme);`

And it's works for me
