### ISSUE TITLE
Identity server using Client Credential flow with existing application and Web API (Core)

### ISSUE THREAD

**Issue by john1452** [IdentityServer/IdentityServer4#1559]
**Problem**

We have an existing aspnet mvc 3 web application that our client use. This web application uses the simple membership provider based authentication (yes it’s old now). Note we cannot change this to use identity server. 

Now we are developing a new application using .net core web api with JavaScript front end. But the problem is that our new application must use the authentication from the old aspnet mvc 3 application.

**Example**

To make this more clear here is an example. User “John” signs into my OLDAPP using username password and navigates to our new application by click on navigation button.

**High level Design - ResourceOwnerPassword grant.**

Following is the design/flow that I am thinking about implementing for above problem.

1. When John signs into old OLDAPP. I will call the identity server and obtain an access token by passing the username and password to identity server using ResourceOwnerPassword grant. The token will be cached on server side.

1. When John clicks on navigation bar in order to go to the new application. I will re-direct him to the NEWAPP with the access token.

1. The redirect request will be intercepted by JavaScript and the access token will be saved to local browser storage for subsequent requests.

**Process of singing in from NEWAPP**

John will be redirect to the OLDAPP to sign in if he tries to navigate to the NEWAPP without signing in.

**Process of signing out**

If john wants to sign out of the NEWAPP. I will simply delete his access token and redirect him back to the OLDAPP to sign out from that as well.

What do you guys think, is this the right way to tackle the problem I described? 
Is there another way? For Example, is it possible to mix the ResourceOwnerPassword grant with JavaScript client (implicit grant) together? handling sign out with the javascript open id connect npm package?

I will eventually push my company to use identity server for the old application so that we can utilizes the single sign on. But this cannot happen right now.

Thank you.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
