### ISSUE TITLE
How to read external identity from the temporary cookie in .net core 2

### ISSUE THREAD

**Issue by llmsjraj** [IdentityServer/IdentityServer4#1561]
```
[[HttpGet("ExternalLoginCallback")]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl)
        {
            // read external identity from the temporary cookie
            var info = await HttpContext.Authentication.GetAuthenticateInfoAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
            var tempUser = info?.Principal;
            if (tempUser == null)
            {
                throw new Exception("External authentication error");
            }

            // retrieve claims of the external user
            var claims = tempUser.Claims.ToList();](url)


```

This is the snippet of external login callback using IdentityServer4. I have migrated to .net core 1 to 2 and i am getting warning  HttpContext.Authentication' is obsolete: 'This is obsolete and will be removed in a future version. So, which method is introduce in .net core 2 to get the identity? @leastprivilege @brockallen  Please help?

Thanks

**Comment by llmsjraj** [comment]
I am getting this error when executing this line 
`var info = await HttpContext.Authentication.GetAuthenticateInfoAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);`

![image](https://user-images.githubusercontent.com/22942645/30825203-bf4d5bee-a24f-11e7-9f0f-cdeb758a0f4d.png)


![image](https://user-images.githubusercontent.com/22942645/30825091-6903fbe4-a24f-11e7-939d-8974f6ba1cc2.png)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
