### ISSUE TITLE
Session Timeout after 30minutes - SecurityStampValidationInterval 

### ISSUE THREAD

**Issue by rezareAW** [IdentityServer/IdentityServer4#1562]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

After I login using any of the flows of Implicity or Hybrid and leaving the browser window open I am logged out after 30mins.  The logs seem to indicate a session timeout.

I have read up on this and it appears it could potentially be related to the SecurityStamp of Identity becoming invalid, however everything I read indicates this should only occur when the user changes security details i.e. password.  In my case this is not happening.

I have tried lots of things but can't seem to get past this issue in IdentityServer other than changing the SecurityStampValidationInterval to a high number.

Parts of my setup code include:

  services.AddIdentity<IdentityUser, IdentityRole>(
                        options =>
                        {
                            options.Cookies.ApplicationCookie.AuthenticationScheme = cookieAuth.AuthenticationScheme;

                            // https://github.com/aspnet/Identity/issues/999
                            // https://github.com/aspnet/Identity/issues/1389
                            // https://stackoverflow.com/questions/45825684/asp-net-core2-0-user-auto-logoff-after-20-30-min
                            // https://github.com/aspnet/Identity/issues/958
                            options.SecurityStampValidationInterval = TimeSpan.FromMinutes(10); //TimeSpan.FromHours(12);

                            // Password requirements as per Gemini item - ATX-239349  Sys2 - Identity server
                            options.Password.RequiredLength = 8;
                            options.Password.RequireUppercase = true;
                            options.Password.RequireLowercase = true;
                            options.Password.RequireNonAlphanumeric = true; 
                            options.Password.RequireDigit = true;
                        })
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddPasswordValidator<Features.Account.PasswordValidator<IdentityUser>>();

            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            services.AddIdentityServer(
                        options => { options.Authentication.AuthenticationScheme = cookieAuth.AuthenticationScheme; })
                    .AddOperationalStore(
                        builder => builder.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationsAssembly)))
                    .AddConfigurationStore(
                        builder => builder.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationsAssembly)))
                    .AddAspNetIdentity<IdentityUser>()
                    .AddTemporarySigningCredential();
            
            // please note that ideally if we want to persist the memory cache and the data protection information across multple instances
            // of the application we need to consider storing these in the database.  However at the moment we are a single instance so this approach is acceptable
            services.AddDistributedMemoryCache();
            services.AddSession(options =>
            {
                options.CookieHttpOnly = true;
                options.IdleTimeout = TimeSpan.FromMinutes(120);
            });

            services.AddDataProtection()
                    .PersistKeysToFileSystem(new DirectoryInfo(appSettings.PersistedCacheDirectory))
                    .SetDefaultKeyLifetime(TimeSpan.FromDays(appSettings.PersistedCacheDuration));

### Relevant parts of the log file

2017-09-26 07:09:16.327 +13:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.AuthorizeEndpoint" for "/connect/authorize"
2017-09-26 07:09:16.329 +13:00 [Debug] Start authorize request
2017-09-26 07:09:16.331 +13:00 [Debug] AuthenticationScheme: "Identity.Application" was not authenticated.
2017-09-26 07:09:16.333 +13:00 [Debug] No user present in authorize request
2017-09-26 07:09:16.334 +13:00 [Debug] Start authorize request protocol validation

**Comment by brockallen** [comment]
My guess is that somehow the `sid` is getting reset at IdentityServer, but IIRC that was a bug we fixed in the 1.0 beta timeframe.

**Comment by brockallen** [comment]
Also, this is an issue that's best discussed here: https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/

**Comment by alexsandro-xpt** [comment]
@rezareAW Did you found any solution for this case?
