### ISSUE TITLE
Authorization code grant type is limited to 100 characters on the token endpoint validation

### ISSUE THREAD

**Issue by MarkVinceSmit** [IdentityServer/IdentityServer4#1563]
- [x ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
1: get a 'password reset' token from the userManager. (in my trials the code has a length of 256.)
2: Try to call the connect/token endpoint with a grant_type of "authorization_code" passing in the code from step 1.

Result: Always a "Authentication code it too long" error.

Suggest: Allow the length to be set during initialization and configuration of the identity server. 

### Relevant parts of the log file
: IdentityServer4.Validation.TokenRequestValidator[0]
Mp.Sh.Core.License>       Start token request validation
Mp.Sh.Core.License> dbug: IdentityServer4.Validation.TokenRequestValidator[0]
Mp.Sh.Core.License>       Start validation of authorization code token request
Mp.Sh.Core.License> fail: IdentityServer4.Validation.TokenRequestValidator[0]
Mp.Sh.Core.License>       Authorization code is too long
Mp.Sh.Core.License> fail: IdentityServer4.Validation.TokenRequestValidator[0]
Mp.Sh.Core.License>       {
Mp.Sh.Core.License>         "ClientId": "mvc_client",
Mp.Sh.Core.License>         "ClientName": "Service Hub Core",
Mp.Sh.Core.License>         "GrantType": "authorization_code",
Mp.Sh.Core.License>         "Raw": {
Mp.Sh.Core.License>           "grant_type": "authorization_code",
Mp.Sh.Core.License>           "code": "CfDJ8KEeZNZ3bi1KucTXYnAlPMDVODlDH2m7RMgDVnbjwJdF2Emsyzs/81eTulPE757ofD0f+l/uZt7I3+7TLu1tZkIgi/JOByBEEGhDmMNH7vFWgk0p1dcpk5BkvQEuysqJu81k6392PnFBGQA/EfQGIgTopf2nzQ/THWwfCtf3ZhlZ4EGf/Jrg0LCG1Wr1r4zo1FGxXfLDCy3YLURupn5mapjLBUIoiTiy09lHML1YNXfdbMF+h0L42WVA9y3+tKBXRw==",
Mp.Sh.Core.License>           "client_id": "mvc_client"
Mp.Sh.Core.License>         }
Mp.Sh.Core.License>       }
Mp.Sh.Core.License> trce: IdentityServer4.Hosting.IdentityServerMiddleware[0]
Mp.Sh.Core.License>       Invoking result: IdentityServer4.Endpoints.Results.TokenErrorResult

The validation code running is using the (internal class, not interfaced) "InputLengthRestrictions", property .AuthorizationCode" which has a "private set" and is fixed on the value 100 (= constant: Default).

**Comment by brockallen** [comment]
These input length restrictions are configurable: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/Options/InputLengthRestrictions.cs#L87

**Comment by MarkVinceSmit** [comment]
True for 2.0++. The problem remains in the 'current' 1.5.2 (highest usable with core 1.1).

**Comment by leastprivilege** [comment]
Why is the code longer? It is normally generated by IS itself...

**Comment by MarkVinceSmit** [comment]
Because i was assuming the token received from the user managers "generate reset password" functionality would return me a OWIN auth code.

**Comment by MarkVinceSmit** [comment]
Since the original statement of 100 char limit has been made configurable in 2.0++ package, i suggest we close this topic.

**Comment by leastprivilege** [comment]
Well - i'd still be interested why your authorization codes are longer than that...

**Comment by brockallen** [comment]
Marvin and I sorted this out.
