### ISSUE TITLE
Full Tutorial for asp.net core 2.0 with IdentityServer4

### ISSUE THREAD

**Issue by createroftheearth** [IdentityServer/IdentityServer4#1565]
I have been trying to use IdentityServer 4 to asp.net core 2.0, I used several tutorials and several websites but I was unable to use it.I want a full tutorial program to use Identity Server4. I am a new bee in using identity server, I haven't used IdentityServer before.

**Comment by brockallen** [comment]
The quickstarts on dev were just updated for ASP.NET Core 2.0: http://docs.identityserver.io/en/dev/quickstarts/0_overview.html

**Comment by mneshasteh** [comment]
IdentityServer4
