### ISSUE TITLE
Lowercase the issuer URI if not specified explicitly

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#157]

**Comment by PivotalAnimal** [comment]
Great work, guys! I added a post in the Async issue that was probably off topic. Not trying to spam. I know you all are busy. So here it is:

Is using default collation inside a database when searching based on IS4 interfaces acceptable? There is no hint passed in from the implemented interfaces as to how to do string comparisons. Maybe this isn't a big deal, but I have been passing in StringComparison comparison = StringComparison.OrdinalIgnoreCase into other methods I have created. That allows different cultures to change how Entity Framework, for example, should test for equality. I am also not sure if it makes sense to pass in a Context object to these interfaces. AutoMapper, for instance, has re-written some of their methods to pass in a context providing more information.

**Comment by brockallen** [comment]
For questions or comments that are new or unrelated, open new issues please.

**Comment by PivotalAnimal** [comment]
I'll review the rfcs some more. I remember reading something about token comparisons.

**Comment by leastprivilege** [comment]
done on dev
