### ISSUE TITLE
Unauthorized client when calling token endpoint with authorization code using hybrid workflow on demo.identityserver.io

### ISSUE THREAD

**Issue by AdamRiddick** [IdentityServer/IdentityServer4#1570]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

Hi,

I'm using https://demo.identityserver.io/ to test my configuration against the different flows and response types. As this is using the demo, i'm unable to view the logs to find out whats going on.

I've been able to use the Authorization Code and Implicit flows without problem, however when using the hybrid flow, with the `code id_token` response type, everything works great until I request an access token from the token endpoint, using the code provided.

The configuration being used is;
```
app.UseOpenIdConnectAuthentication(
    new OpenIdConnectOptions
    {
        AuthenticationScheme = "demoidsrv",
        Authority = "https://demo.identityserver.io/",
        AutomaticChallenge = false,
        CallbackPath = new PathString($"/signin-demoidsrv"),
        ClientId = "server.hybrid",
        ClientSecret = "secret",
        DisplayName = "Demo idsrv code id_token",
        Events = new OpenIdConnectEvents
        {
            OnTokenValidated = OnTokenValidated
        },
       RemoteSignOutPath = new PathString($"/signout-demoidsrv"),
       ResponseType = "code id_token",
       SaveTokens = true,
       Scope =
           {
               IdentityServer4.IdentityServerConstants.StandardScopes.OpenId,
               IdentityServer4.IdentityServerConstants.StandardScopes.Email,
               IdentityServer4.IdentityServerConstants.StandardScopes.OfflineAccess
           },
        SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
        SignOutScheme = IdentityServerConstants.SignoutScheme,
        SignedOutCallbackPath = new PathString($"/signout-callback-demoidsrv"),
        TokenValidationParameters = new TokenValidationParameters
            {
                NameClaimType = "name",
                RoleClaimType = "role"
            }
    });

```

This works great, when arriving at my local authentication server, I get the option to use the external provider. Upon selecting it, I am redirected, login successfully and am returned to the client and i have access to the authorization code and id token.

So far so good. However, when I attempt to use the authorization code, in order to gain an access token to use against the user info endpoint, using the following code;

```
private static async Task OnTokenValidated(TokenValidatedContext context)
{
    // Omitted section initialising context.Options.Configuration
    var tokenClient = new TokenClient(context.Options.Configuration.TokenEndpoint, context.Options.ClientId, context.Options.ClientSecret);

    var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(                                        context.ProtocolMessage.Code, null, cancellationToken: cancellationTokenSource.Token);
}
```

I receive an error which states `unauthorized_client`. I did try setting the redirect uri to `https://notused` as per the config (https://github.com/IdentityServer/IdentityServer4.Demo/blob/master/src/IdentityServer4Demo/Config.cs), to the same result.

My question is: Am I missing a step ?

Also; if I change the response type to `code token` or `code id_token token` I get the response `Sorry, there was an error : invalid_request; Request Id: 0HL80KH982QM5`

**Comment by leastprivilege** [comment]
Here's the source code, so you can host yourself.

https://github.com/IdentityServer/IdentityServer4.Demo

**Comment by AdamRiddick** [comment]
This was a config mismatch, Thanks.
