### ISSUE TITLE
Route matching not separate from endpoint route handling

### ISSUE THREAD

**Issue by tillig** [IdentityServer/IdentityServer4#1572]
I've been working on a multitenant version of Identity Server where routing matches a template like `/{tenantid}/connect/token` or whatever - the tenant ID is a route parameter, similar to the way Azure AD does things. This wasn't hard to do with my own `IEndpointRouter`. Really nice flexibility around that.

A challenge I've hit is that even with the routing, the _endpoint handlers themselves_ are checking paths to see how to process certain requests:

- `AuthorizeEndpoint` looks at the request path [and tests for equality](https://github.com/IdentityServer/IdentityServer4/blob/74827bc4df39c2234d9490ba5ce032ce806ab475/src/IdentityServer4/Endpoints/AuthorizeEndpoint.cs#L56) to see if it's `/connect/authorize` or `/connect/authorize/callback`.
- `EndSessionEndpoint` also [tests the request path for equality](https://github.com/IdentityServer/IdentityServer4/blob/74827bc4df39c2234d9490ba5ce032ce806ab475/src/IdentityServer4/Endpoints/EndSessionEndpoint.cs#L36) to see if it's `/connect/endsession` or `/connect/endsession/callback`.

The path checking in the endpoint handler breaks the separation between routing and endpoint handling. Given the endpoint handlers are internal, you can't derive-and-override, either; it's a full fork/copy/paste situation.

I can think of a couple of solutions (not counting "fork/copy/paste"):

1. **Map one endpoint handler to each endpoint.** For handlers like `AuthorizeEndpoint` or `EndSessionEndpoint`, have a base class for common logic and individual derived classes for each matching route. This would avoid the need for the equality check.
2. **Make the endpoint handlers public so folks can derive/override the logic.** I can see why that may not be the best option, I'm just trying to avoid copy/pasting a bunch.

If you're open to option 1 I could PR that.

**Comment by tillig** [comment]
Note the fork/copy/paste route is a bit painful due to so many things being internal. For example, `AuthorizeEndpoint`...

- Returns an `AuthorizeResult`, which is internal.
- Logs with `AuthorizeRequestValidationLog` and `AuthorizeResponseLog`, both of which are internal (and uses `LogSerializer`, which is also internal).
- Uses a lot of internal extension methods along the way (conversions from objects to `NameValueCollection`, etc.).

**Comment by brockallen** [comment]
We'll discuss.

**Comment by tillig** [comment]
I submitted a PR to show what it'd take if you choose to go forward with something like that. I thought it might help facilitate the research and discussion.
