### ISSUE TITLE
"idp claim is missing" with AspNetIdentity 2.0.0-rc1

### ISSUE THREAD

**Issue by antonioromano** [IdentityServer/IdentityServer4#1573]
I know this is a duplicate of the issue https://github.com/IdentityServer/IdentityServer4/issues/277, but it has been closed and now the bug come back with the version 2.0.0-rc1

I noticed that some users are experiencing it. Sometimes the identityserver throw the error:
```Unhandled exception: System.InvalidOperationException: idp claim is missing```
or 
```IdentityServer4 message: idp claim is missing stack: at IdentityServer4.Extensions.PrincipalExtensions.GetIdentityProvider(IIdentity identity)```

It seems that the server tries to load some data from the cache getting an error, and what happens is an error response to the user who is trying to log in.

Any idea on what I can do to fix it? Is this issue under control?

**Comment by brockallen** [comment]
Open an issue in the ASP.NET Identity Repo: https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/

**Comment by gartak** [comment]
Sorry to write in a closed task, but I can't find any info about the "idp claim is missing" that's still there with IdentityServer4 v2.1.1 
Any suggestion is appreciated.
Thanks

**Comment by GithubCSL** [comment]
has this been fixed ?

**Comment by SolarMaximus** [comment]
We faced this issue too.

**Comment by JohnGalt1717** [comment]
Same here and that repro listed by @brockallen says to come here to report.
