### ISSUE TITLE
ApplicationDbContext with Custom API？

### ISSUE THREAD

**Issue by springe2004** [IdentityServer/IdentityServer4#1582]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

I have been upgraded to ids4  core 2.0,and i want Using custom ApplicationDbContext, Is there a good idea?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Can you elaborate?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
