### ISSUE TITLE
Same key across microservices in Core 2.0

### ISSUE THREAD

**Issue by AustinFelipe** [IdentityServer/IdentityServer4#1584]
Guys, let me see if I get it right. I have a service who needs authentication and I'd like to use IdentityServer 4 as Auth provider. How should I configure my service to use same credentials as IdentityServer?

I'm using Asp Net Core 2.0, so my ConfigureServices inside my service looks as follows:

``` csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(o =>
            {
                o.Authority = "http://localhost:5000";
                o.Audience = "mktplace";
                o.RequireHttpsMetadata = false;
            });
        }
```

Here is how I'm configuring the IdentityServer
``` csharp
      services.AddIdentityServer()
                .AddDeveloperSigningCredential(filename: "tempkey.rsa")
                .AddInMemoryApiResources(AuthConfig.ServerConfigQS.GetApiResources())
                .AddInMemoryClients(AuthConfig.ServerConfigQS.GetClients())
                .AddAspNetIdentity<ApplicationUser>();
```

I can get a valid token using my IdentityServer, it works ok. But calling my service it doesn't accept as a valid token. My guess is I'm not using the same credentials.

Any help on that? 

Thanks

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
