### ISSUE TITLE
Specify No External Logins Allowed

### ISSUE THREAD

**Issue by cdasilva** [IdentityServer/IdentityServer4#1585]
As far as I can tell it's currently impossible to declare that NO external IdPs can be used with a client. If you specify an empty IdentityProviderRestrictions, that means ALL external IdPs are allowed. 

The easiest way to solve this in a non-breaking fashion is to create a new Client property called EnableExternalLogin which is set to true by default. 
- AuthorizeRequestValidator, and AuthorizeInteractionResponseGenerator would need to be updated to enforce this new property. 
- The QuickStart UIs would need to update AccountService. 
- This also affects some of the unit and integration tests. 
- End-users can choose to update their UI code to take full advantage of the new property or ignore it.

**Comment by brockallen** [comment]
A workaround exists: Add a string to the allowed IdPs that contains an invalid idp name. Ugly, but it does work.

**Comment by cdasilva** [comment]
Good call. That should work fine on my end too. Thanks for everything you do Brock (and Dominick)
