### ISSUE TITLE
Access token not expire when invoke end session

### ISSUE THREAD

**Issue by gustavo84** [IdentityServer/IdentityServer4#1588]
I have a dubt, becouse i invoke end session identity server, but i don't know if access token will be valid.

Regards, Gustavo

- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Those two items are unrelated. Check SO for more insight into revoking access tokens at logout time.
