### ISSUE TITLE
Windows Active Directory Authentication with ASP.NET Identity 

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1589]
Can we configure Identity Server to use windows active directory authentication provided with asp.net identity.

Is it possible to use both Individual user and windows active directory in identity server (user will choose the option at runtime)

Thanks

**Comment by leastprivilege** [comment]
IdentityServer (as every other ASP.NET Core application) supports Windows authentication if configured correctly.

Check the docs.
