### ISSUE TITLE
Consider handling OpenID Connect request parameters as JWTs

### ISSUE THREAD

**Issue by adamdotdev** [IdentityServer/IdentityServer4#1590]
Are there plans for IdentityServer4 to support handling request parameters as JWTs according to [section 6 of the OpenID Connect Core spec](http://openid.net/specs/openid-connect-core-1_0.html#JWTRequests)?

We would like to enable Authentication Request signing using this method.

**Comment by leastprivilege** [comment]
This is a feature waiting for a sponsor.

**Comment by leastprivilege** [comment]
actually a dup of 

https://github.com/IdentityServer/IdentityServer4/issues/594
