### ISSUE TITLE
Ability to register users programmatically

### ISSUE THREAD

**Issue by ADringer** [IdentityServer/IdentityServer4#1594]
Hi,

I have a system where a user uploads a list of users that need to be registered on the system. My plan was to use an Azure Logic App to then call the `Register` method on IdentityServer. I added Swagger to aid in this.

However, the antiforgerytoken doesn't allow me to just directly POST to `Register` (as designed). Is there a way to call the API without user interaction to register a user? 

Thanks
Alex

**Comment by leastprivilege** [comment]
IdentityServer does not have a `Register` method. You need to build your own user management APIs.

**Comment by ADringer** [comment]
Ah, I'm using one of the quickstarts but forgot as I cloned it quite a while ago. I'll add my own method to the controller. 

Thanks
