### ISSUE TITLE
IdentityServerPrincipal.Create requires name to be not empty

### ISSUE THREAD

**Issue by Mardoxx** [IdentityServer/IdentityServer4#1597]
I was trying to create a user with a name set to `string.Empty` via `AuthenticationManager.SignInAsync` and was returned with a `ArgumentNullException` for `name`. This is where it threw:
https://github.com/IdentityServer/IdentityServer4/blob/388c4c50a20a6505c91c26f70c62811a99a9e8f5/src/IdentityServer4/IdentityServerPrincipal.cs#L117

Is it invalid to create a UserPrincipal with an empty name? If not, would you be able to allow it? If so, I think a different exception, perhaps a new `ArgumentNullOrEmptyException` would be better here as `IsMissing()` checks `string.IsNullOrWhiteSpace()`?

Thanks!

**Comment by leastprivilege** [comment]
Yes - we require a display name - if you don't have that concept, use the sub claim as the value.

**Comment by Mardoxx** [comment]
What's it used for? A quick search for `JwtClaimTypes.Name` and `GetName` just appear in code that dictates it is required. The only place I can see it being used is in `ClaimsPrincipalConverter`?

**Comment by leastprivilege** [comment]
It is used in the standard UI. As I said - if you don't have the concept. Just set the sub instead.

**Comment by Mardoxx** [comment]
So you only require name to be set just for your UI -- it has always seemed to me you left it up to the user (me) to implement UI and yours was just a very basic example. 

I basically wanted it for this: Users can request a token for my API, and optionally have a "profile" assigned to them (which can be resolved (lookedup) to their name). If they have a profile, set `name` as their profileId, otherwise null/empty string.

I suppose I could just set it to a different claim (e.g. "profile_id") and have this as a user claim for that api resource?

**Comment by leastprivilege** [comment]
You can set whatever value you want - or come up with a different claim type. 

For historical reasons we require a claim of type name. Thats all.

**Comment by Mardoxx** [comment]
Sweet, thanks 😄

**Comment by TomCJones** [comment]
In the OpenID protocol sub (subject) is the only required ID between the client and the OP. The user email or other attributes are not passed to the client unless the user explicitly consents to that happening. The user principal is external (and unknown) to the protocol.

**Comment by Mardoxx** [comment]
This is still the case with IdSrv, not sure what you mean?
