### ISSUE TITLE
Extensibility point in AuthorizeEndpoint

### ISSUE THREAD

**Issue by dbrink** [IdentityServer/IdentityServer4#16]
As part of researching tenant based authentication I found I can vary the tenant without affecting the user's authentication within IdSrv4.  This seems reasonable, yet there doesn't appear to be an extensibility point within the AuthorizeEndpoint's ProcessAuthorizeRequestAsync that would allow additional validation or customizing the interaction to change the prompt mode.  It looks like in IdSrv I might be have been able to do this in PreAuthenticateAsync.  

I'm testing this within the Mvc test project by including the "alice" tenant in the acr

                options.Events = new OpenIdConnectEvents
                {
                    OnRedirectToAuthenticationEndpoint = ctx =>
                    {
                        ctx.ProtocolMessage.AcrValues = "tenant:alice";
                        return Task.FromResult(0);
                    }
                };

I then kill the Mvc authentication cookie and use the "bob" tenant.  I'd like to detect the tenant change via a claim set on the initial sign-in and force them to authenticate again.

                options.Events = new OpenIdConnectEvents
                {
                    OnRedirectToAuthenticationEndpoint = ctx =>
                    {
                        ctx.ProtocolMessage.AcrValues = "tenant:bob";
                        return Task.FromResult(0);
                    }
                };

**Comment by brockallen** [comment]
So in short, you're saying that if the `acr_value=tenant:foo` request param is passed, that it's not being honored if the user is already logged in with a idp other than "foo"?

**Comment by dbrink** [comment]
Yes, though I'm not sure this should be handled differently in the default case.  My concern is more that there doesn't seem to be a way to reject the current IdentityServer identity during authorize.

**Comment by brockallen** [comment]
Well, IIRC, in IdSvr3 if the tenant in the acr_values didn't match the user's idp, then we triggered a login. So if IdSvr4 doesn't do that, then it sounds like a regression bug.

**Comment by leastprivilege** [comment]
Tenant and Idp are different unrelated things.

**Comment by brockallen** [comment]
Oh yea, of course. Forget what I said then :/

**Comment by dbrink** [comment]
Then I'm back to my original question.  Is there any way in IdSrv4 to force re-authentication based on authorize parameters or does this need to wait until some of the UserService bits are flushed out?

**Comment by brockallen** [comment]
Yep -- so you can take a look at this (it might be an approach that works for you): https://github.com/IdentityServer/IdentityServer3/issues/2388#issuecomment-172640121
