### ISSUE TITLE
Minor typos in documentation

### ISSUE THREAD

**Issue by gabrielweyer** [IdentityServer/IdentityServer4#1600]
I found two small typos in the documentation.

`docs/intro/support.rst`

![image](https://user-images.githubusercontent.com/2101647/31304956-29b9bf1c-ab7a-11e7-9fd0-c3f296851597.png)

`CONTRIBUTING.md`

`CONTRIBUTING` is still mentioning `ASP.NET Core 1.1` while the main `README` is mentioning `ASP.NET Core 2.0`

![image](https://user-images.githubusercontent.com/2101647/31304958-38f43e30-ab7a-11e7-8380-9867a4841f11.png)

**Comment by leastprivilege** [comment]
thanks. merged.
