### ISSUE TITLE
Parameterize the LoginUrl in IdentityServer? 

### ISSUE THREAD

**Issue by aneequrrehman** [IdentityServer/IdentityServer4#1603]
I have been trying to add a parameter in the Login URL. E.g.

```
services.AddIdentityServer(options =>
                {
                    options.UserInteraction.LoginUrl = "/{culture}/account/login";
                });
```

Is it possible to have such types of parameterized URLs? Also, how would I pass this culture from my (JavaScript) client application?
Thanks

**Comment by brockallen** [comment]
No, we don't have a way to support that. But culture as part of the request is already supported: Check the ui_locales param: https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

And then in your login you can get those: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Models/Messages/AuthorizationRequest.cs#L46 when you query the interaction service.

**Comment by ivanstamenic** [comment]
I'm sorry for reopening this! 

Getting culture by querying interaction service works like a charm, but my question is how to set ui_locales query string in Authentication Request request from MVC Client?

**Comment by leastprivilege** [comment]
You can use the events/notifications of the OIDC handler/middleware.
