### ISSUE TITLE
Http.Sys implementation with Windows Integrated Authentication

### ISSUE THREAD

**Issue by dviry** [IdentityServer/IdentityServer4#1607]
*opened new Issue [as requested](https://github.com/IdentityServer/IdentityServer4/issues/1057#issuecomment-335041550) by @brockallen*
 
While migrating to Http.Sys (from WebListener), looking at the [updated docs](http://docs.identityserver.io/en/dev/topics/windows.html) there is only a single comment about Http.Sys.
At the end of the article, the "DisplayName" warning with the solution with IISOptions really only applies to Kestrel, since for Http.Sys there is [no such equivalent](https://github.com/aspnet/HttpSysServer/issues/392), I had to change this [code](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/60b96229ad844b686bf0fcaca9474980fcda6240/Quickstart/Account/AccountService.cs#L52-L58).

I saw your [comment](https://github.com/IdentityServer/IdentityServer4/issues/1472#issuecomment-326483035) about Http.Sys, but please consider adding some hints in the Docs as that would probably help those trying to implement Http.Sys on their own.

PS: I changed the [code](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/60b96229ad844b686bf0fcaca9474980fcda6240/Quickstart/Account/AccountService.cs#L52-L58) to the following (which I think would work in any case - so maybe worth integrating it in the sample or at least in the [Quickstart docs](http://docs.identityserver.io/en/dev/topics/windows.html)?)
```javascript
var providers = schemes
    .Where(x => x.DisplayName != null 
                         || (AccountOptions.WindowsAuthenticationEnabled 
                             && x.Name.Equals(AccountOptions.WindowsAuthenticationSchemeName)))
    .Select(x => new ExternalProvider
    {
      DisplayName = x.DisplayName ?? x.Name,
      AuthenticationScheme = x.Name
    }).ToList();
```
PS2: I've been running v2 now on Production (with above code change) and so far so good! Thanks for a great release!!

Thanks

**Comment by brockallen** [comment]
Ok, I have added the additional check as you suggested.
