### ISSUE TITLE
2.0 version  custom endpoint  invalid

### ISSUE THREAD

**Issue by findtolive** [IdentityServer/IdentityServer4#1610]
I would like to rewrite the authorize endpoint, but according to the existing AddEndpoint method added after the invalid, before the nuget 1.52 version is no problem, but because some of the internal methods before the opening must be upgraded to version 2.0. So I modified the AddIdentityServer method source code, in the use of the first to add custom authorize endpoint and then manually add DefaultEndpoint all normal

public static IIdentityServerBuilder AddIdentityServer (this IServiceCollection services)
        {
            var builder = services.AddIdentityServerBuilder ();

            builder
                .AddRequiredPlatformServices ()
                .AddCookieAuthentication ()
                .AddCoreServices ()
                // AddDefaultEndpoints ()
                .AddPluggableServices ()
                .AddValidators ()
                .AddResponseGenerators ()
                .AddDefaultSecretParsers ()
                .AddDefaultSecretValidators ();

            // provide default in-memory implementation, not suitable for most production scenarios
            builder.AddInMemoryPersistedGrants ();

            return new IdentityServerBuilder (services);
        }

Comment the AddDefaultEndpoints () method and then use the following:

services.AddIdentityServer (options =>
            {
                options.Events.RaiseSuccessEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseErrorEvents = true;
                //options.Endpoints.EnableAuthorizeEndpoint = false;
            })
               // AddClientStore ()
               .AddInMemoryClients (Clients.Get ())
               //.AddInMemoryClients(_config.GetSection("Clients "))
               .AddInMemoryIdentityResources (Resources.GetIdentityResources ())
               .AddInMemoryApiResources (Resources.GetApiResources ())
               .AddDeveloperSigningCredential ()
               .AddExtensionGrantValidator <Extensions.ExtensionGrantValidator> ()
                .AddExtensionGrantValidator <Extensions.NoSubjectExtensionGrantValidator> ()
                .AddJwtBearerClientAuthentication ()
                .AddAppAuthRedirectUriValidator ()
               .AddAspNetIdentity <ApplicationUser> ()
               .AddEndpoint <AuthorizeEndpoint> ("Authorize", "/ connect / authorize")
               .AddDefaultEndpoints ()
               ;

Is this a Bug?

**Comment by brockallen** [comment]
What's not working? It's not clear to me from your text.

**Comment by findtolive** [comment]
.AddEndpoint ("Authorize", "/ connect / authorize")
custom endpoint does not workking

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
