### ISSUE TITLE
Don't require credentials for resource owner password clients on revocation endpoint

### ISSUE THREAD

**Issue by OllieDay** [IdentityServer/IdentityServer4#1611]
As with #526, could we do the same for the resource owner password grant type?

**Comment by brockallen** [comment]
Why?

**Comment by OllieDay** [comment]
We're using this grant type for a non-confidential client (`RequireClientSecret = false`) together with reference tokens and would like the client to be able to call the revocation endpoint.

Client credentials aren't required for generating tokens so I'm not seeing the benefit of requiring them for revocation. Am I missing something? The OAuth 2.0 spec mentions verifying credentials only in the case of confidential clients.

**Comment by leastprivilege** [comment]
The introspection endpoint uses the normal client secret validator - if no client credential is required, this should work the way you want it...

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
