### ISSUE TITLE
Any way to configure Clients, ApiResources and IdentityResources from IConfiguration?

### ISSUE THREAD

**Issue by NoMoreLoad** [IdentityServer/IdentityServer4#1614]
Does IdentityServer provides any extension methods to retrieve this from IConfiguration? 
I can't found something about it. Maybe I missed something?
It would be nice to "bootstrap" database configuration from IConfiguration when we started our application with empty database.

**Comment by leastprivilege** [comment]
yes - see here

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Host/Startup.cs#L43

**Comment by NoMoreLoad** [comment]
@leastprivilege Thanks! But what about secrets? It looks like I should store "pre-computed" Sha256 in my config. Am I right?

**Comment by leastprivilege** [comment]
yes

**Comment by NoMoreLoad** [comment]
@leastprivilege Thank you again!
