### ISSUE TITLE
PostLogoutRedirectUri sometimes not returned by GetLogoutContextAsync

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4#1616]
This sounds like a similar problem to https://github.com/IdentityServer/IdentityServer4/issues/1204 but I don't see a resolution there.

My Logout method is shown below. I have some JS on my client webpage which signs the user out after 30 mins if there is no browser interaction. When this happens context.PostLogoutRedirectUri is null. If I logout normally (link) or set the timeout to 5 mins then context.PostLogoutRedirectUri returns the correct value. Any idea why?

```
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Logout(string logoutId)
        {
            // ensure it is a valid logout
            var context = await _interaction.GetLogoutContextAsync(logoutId);

            if (context != null)
            {
                await _signInManager.SignOutAsync();
                return Redirect(context.PostLogoutRedirectUri);
            }

            return BadRequest();
        }
```

**Comment by leastprivilege** [comment]
Compare the network traffic between working/non-working version - maybe that gives you a clue.

**Comment by daver77** [comment]
My Client project is ASP.NET Forms so in Startup.cs I have the following. It seems that the token is null so it's not setting the 'notification.ProtocolMessage.IdTokenHint'

```
            app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                {
                    ....
                    
                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        ....

                        // Attach the id_token stored in the authentication cookie to the logout request.
                        RedirectToIdentityProvider = notification =>
                        {
                            if (notification.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                            {
                                var token = notification.OwinContext.Authentication.User?.FindFirst(OpenIdConnectParameterNames.IdToken);
                                if (token != null)
                                {
                                    notification.ProtocolMessage.IdTokenHint = token.Value;
                                }
                            }

                            return Task.FromResult<object>(null);
                        }
                    }
                }
            );
```

**Comment by leastprivilege** [comment]
Maybe the cookie has expired at this point...

**Comment by daver77** [comment]
It certainly looks that way, any more than a few minutes and token is null. Where is the timeout set for this cookie?

**Comment by daver77** [comment]
This worked for me

https://github.com/IdentityServer/IdentityServer3/issues/2687#issuecomment-194739035

**Comment by yosbeleg89** [comment]
@daver77 solution also worked for me, but I would like to know why if the IdTokenHint is not present then the GetLogoutContextAsync does not return it even when `post_logout_redirect_uri` is present in the `/endsession` request.

**Comment by yosbeleg89** [comment]
@leastprivilege as I can see in the [specs](https://openid.net/specs/openid-connect-session-1_0.html#RPLogout): If supplied, the OP SHOULD honor this request following the logout. Why if the `id_token_hint` is not provided then the `post_logout_redirect_uri` is not available?

**Comment by brockallen** [comment]
> Why if the id_token_hint is not provided then the post_logout_redirect_uri is not available

because you don't which which client it's for. requiring the id_token, in essence, authenticates the request to signout, which allows us to lookup the right client to then validate the `post_logout_redirect_uri`

**Comment by yosbeleg89** [comment]
Hmm, that makes sense to me, so we need to use the "[IdentityServer/IdentityServer3#2687 (comment)](https://github.com/IdentityServer/IdentityServer3/issues/2687#issuecomment-194739035)" workaround to make it always available?

**Comment by oakdemirci** [comment]
@yosbeleg89 did you find a better way other than the cookie?

**Comment by yosbeleg89** [comment]
I'm afraid not @oakdemirci, I still have the workaround in my AspNet project.

**Comment by oakdemirci** [comment]
@yosbeleg89 then you save it to a cookie in AuthorizationCodeReceived and retrieve the cookie in RedirectToIdentityProvider (OpenIdConnectRequestType.LogoutRequest). Right? 
Thanks ;)

**Comment by poveilleux** [comment]
I know I am a bit late to the party, but I think the `IdTokenHint` was not sent on the end session request because the `SaveTokens` property of the `OpenIdConnectAuthentication` was not set to `true`.
