### ISSUE TITLE
IdentityServer 4 1.5.2 HttpsContext.Identity not set in IE11 when using HttpContext.Authentication.SignInAsync() extension method

### ISSUE THREAD

**Issue by Robban1980** [IdentityServer/IdentityServer4#1619]
This is a very weird case only affect IE11 and Edge from what i have seen so far.

2 servers with an Identity Server 1.5.2 using AspNet Identity 3. They servers have no connection with each other. As long as only 1 server is opened at a time there are no issues signing in.

0. use IE 11.
1.Open server 1 in Tab 1, login page shows.
2. open server 2 in Tab 2, login page shows.
3. Go to Tab 1 and login. Error page is shown.
4. Go to tab 2 and login, Error page is shown.

Looking in the logs they both fail calling the authorization endpoint after successful authentication.
The error is "User is not authenticated" in the Authorization endpoint, followed by a Token Issuing fails. After a lot of investigation i found that for some reason in IE11 the HttpContext.Identity/User i not set in when using the HttpContext.Authentication.SignInAsync(sub, name, prop) extension method. Doing the same steps in Chrome and Firefox, does not generate the error.

After trying to change schema names and cookie names from default the issue persisted. However i switched from using SignInAsync() extension method to use the native one on the taking a schema and a principle. basically i manually do the same thing done in the extension method. And now it works in all browsers again. So I wonder if there might be some issue with the extension methods? 

Maybe this is not an issue in 2.0 using the extension methods. It might not be a normal use case to have to Identity Server instances on different servers for different applications open at the same time in Internet Explorer.

**Comment by leastprivilege** [comment]
Those extension methods simply use the standard ASP.NET Core methods on AuthenticationManager. Try to repro the same without IdentityServer and if you still see a problem . tell Microsoft.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
