### ISSUE TITLE
IdentityServer4 EnableSignOutPrompt

### ISSUE THREAD

**Issue by BlackMoon** [IdentityServer/IdentityServer4#162]
Hi All!

Does **IdentityServer4 Host** implement 
`AuthenticationOptions.EnableSignOutPrompt = false` behaviour?

Thanks

**Comment by leastprivilege** [comment]
Since the UI is not controller by IS anymore - this feature does not exist anymore as well

**Comment by BlackMoon** [comment]
> Since the UI is not controller by IS anymore

And what about **PostLogoutRedirectUris** ? Redirect after logout also not implemented?

**Comment by leastprivilege** [comment]
As I said - in IS4 we don't implement any UI. We will provide a default implementation - but nothing will be built into our core library.

We release beta5 yesterday - look at our reference host to see how this is implemented now

https://github.com/IdentityServer/IdentityServer4/tree/dev/src/Host

**Comment by BlackMoon** [comment]
> We released beta5 yesterday - look at our reference host to see how this is implemented now
Now I see

```
public class LogoutController : Controller
{
        [HttpGet("ui/logout", Name = "Logout")]
        public IActionResult Index(string logoutId)
        {
            ViewData["logoutId"] = logoutId;
            return View();
        }

        [HttpPost("ui/logout")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Submit(string logoutId)
        {
            await HttpContext.Authentication.SignOutAsync(Constants.DefaultCookieAuthenticationScheme);

            // set this so UI rendering sees an anonymous user
            HttpContext.User = new ClaimsPrincipal(new ClaimsIdentity());

            var logout = await _interaction.GetLogoutContextAsync(logoutId);

            var vm = new LoggedOutViewModel()
            {
                PostLogoutRedirectUri = logout.PostLogoutRedirectUri,
                ClientName = logout.ClientId,
                SignOutIframeUrl = logout.SignOutIFrameUrl
            };
            return View("LoggedOut", vm);
        }
......
}
```

**logoutId** url param always null in **Index** and also in **Submit** methods.
What value it must contains?

**Comment by leastprivilege** [comment]
did you try it with one of our sample clients from the samples repo?

**Comment by BlackMoon** [comment]
My client - WebForm ASPX site with OWIN Environment.

It use owin - 

```
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:1941",
                RequireHttpsMetadata = false,

                EnableCaching = true,

                ScopeName = "api1",
                ScopeSecret = "secret",
                AutomaticAuthenticate = true
            });
```

instead of aspnet core (in example) - 

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = config.AuthenticationType,
                SignInAsAuthenticationType = config.SignInAsAuthenticationType,
                Authority = config.Authority,
                ClientId = config.ClientId,
                RedirectUri = config.RedirectUri,
                ResponseType = config.ResponceType,
                Scope = config.Scope,
                UseTokenLifetime = config.UseTokenLifetime
```,

Maybe here's dismiss?

**Comment by leastprivilege** [comment]
i don't follow. UseIdentityServerAuthentication is for APIs

the Katana MW does not add the necessary parameters automatically - check our IdentityServer3 samples repo - e.g. 

https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client%20(Hybrid)/Startup.cs#L87

**Comment by BlackMoon** [comment]
> the Katana MW does not add the necessary parameters automatically

Thanks. 
Here's the reason.
