### ISSUE TITLE
Claims are not getting refresh

### ISSUE THREAD

**Issue by amruta455** [IdentityServer/IdentityServer4#1622]
I am using identity server 4 for authenticating and authorizing.In that, I am refreshing claims using access token. so claims are getting refresh sometimes and sometimes it is not.So I have to logout and login again to see updated claims.

Here the code i am using for refreshing claims -
List<Claim> claims = new List<Claim>();
            var accessToken = id.FindFirst("access_token");

            var userInfoClient = new UserInfoClient(new Uri(ConfigHelper.GetConfigValue("IdentityServerUrl") + "/connect/userinfo"), accessToken.Value);
            var userInfo = userInfoClient.GetAsync().Result;
            userInfo.Claims.ToList().ForEach(ui => claims.Add(new Claim(ui.Item1, ui.Item2)));

            claims.Add(new Claim("sub", id.FindFirst("sub").Value));
            claims.Add(new Claim("expires_at", id.FindFirst("expires_at").Value));
            claims.Add(new Claim("access_token", accessToken.Value));
            claims.Add(new Claim("refresh_token", id.FindFirst("refresh_token").Value));
            claims.Add(new Claim("id_token", id.FindFirst("id_token").Value));

            ClaimsIdentity newIdentity = new ClaimsIdentity(claims, "Cookies");
            var wrapper = new HttpRequestWrapper(HttpContext.Current.Request);
            wrapper.GetOwinContext().Authentication.SignIn(newIdentity);

**Comment by leastprivilege** [comment]
I don't understand the problem.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
