### ISSUE TITLE
Invalid scope raise http 403 forbidden

### ISSUE THREAD

**Issue by vdecristofaro** [IdentityServer/IdentityServer4#1624]
- [X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

I have successfully setup an IdentityServer instance. Also, I have setup an API with two controllers and I have created two different policies as described [here](http://docs.identityserver.io/en/release/topics/apis.html) (section validating scopes).

I have then created two clients, one for each api resource.

```
Client A —> Scope A —> Api A
Client B —> Scope B —> Api B
```

Everything is working, however I would expect to get a `401 Unauthorized` if calling Api B from Client A. Instead I am getting `403 Forbidden`.

Is this correct? Please excuse if it is a dumb question.

**Comment by brockallen** [comment]
https://tools.ietf.org/html/rfc6750#section-3
