### ISSUE TITLE
Inconsistent User Claims between doc image and sample app

### ISSUE THREAD

**Issue by SIkebe** [IdentityServer/IdentityServer4#1626]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

In the quickstarts 3 doc there is a screen shot of secure page that shows user claims.
https://github.com/IdentityServer/IdentityServer4/blob/release/docs/quickstarts/3_interactive_login.rst#testing-the-client

![](https://github.com/IdentityServer/IdentityServer4/blob/release/docs/quickstarts/images/3_claims.png?raw=true)

But, when you create a sample MVC app following the doc or using [this sample](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/3_ImplicitFlowAuthentication), you see only limited claims as below.

![use-claims](https://user-images.githubusercontent.com/17608272/31586469-71229822-b20c-11e7-975c-679a6dc573c1.png)

Which is the expected behavior?

**Comment by brockallen** [comment]
Can you send a PR updating the pic from the docs?

**Comment by SIkebe** [comment]
Sure! I'll do it.

**Comment by egmfrs** [comment]
What is missing in the sample code in order to bring back the bigger list of claims? I have another sample proj from pluralsight which brings back nonce, authtime etc. and can't for the life of me see the difference in the code between samples which causes one to have so many more claims included.

**Comment by leastprivilege** [comment]
set 

`options.ClaimsActions.Clear()` on the OpenID connect handler.

..and thank Microsoft for the intuitive API ;)

**Comment by egmfrs** [comment]
@leastprivilege Thank you - it was actually ClaimActions (not claims)

**Comment by SIkebe** [comment]
@leastprivilege Was that an intended change? Should I send another PR to bring it back?
