### ISSUE TITLE
Identity Server Hosted as Resource

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1628]
Is it possible to host IdentityServer itself as a resource also, so that the token received from the server can be used to access some custom resources (APIs) hosted within the identity server.

I tried to configure it as a resource as done in the sample API, but it does not authorize. Accessing this with a client with scope "serverapi"

```
services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = Constants.Authority;
                    options.RequireHttpsMetadata = false;

                    options.ApiName = "serverapi";
                    options.ApiSecret = "secret";
                });
```

**Comment by leastprivilege** [comment]
yes - see here

https://github.com/brockallen/IdentityServerAndApi

**Comment by satyajit-behera** [comment]
@leastprivilege Thanks a lot. Sample resolved my issue.
