### ISSUE TITLE
Include client ip address as structured logging field when logging token request infos / errors

### ISSUE THREAD

**Issue by osudude** [IdentityServer/IdentityServer4#1632]
It would be very helpful if identity server included the client ip address as a structured logging field when logging token request related errors / information.  This helps when looking through the logs for errors related to a given client ip.  Note client ip may be  a non-standard http header when behind a CDN so probably need to be able to register a custom IP address resolver that overrides default IP address resolution.    Tried to figure out how to do this with serilog / my own custom code without modifying identity server but couldn't figure it out.

Note, it might be cool if the identity server consumer could control what additional data gets logged on token request infos/errors.

**Comment by leastprivilege** [comment]
IMO - this has two parts to it.

* emitting IP addresses in log output is probably better done at the LoggerFactory level than at the app level (or use something like enrichers in Serilog).
* setting the right client IP address should be done at the pipeline level (e.g. using the forwarded header MW)

**Comment by osudude** [comment]
Serilog enricher is difficult due to lack of ioc support (no httpcontextfactory)

**Comment by brockallen** [comment]
Just be careful about logging IP address -- depending on your regional laws, that might be considered PII. Check with your legal department.
