### ISSUE TITLE
Disable any existing grant_type

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1639]
Is it possible to **disable** any **specific grant_type** for an installation and instead use custom grant type only?

Example: "password" grant_type can be disabled and a custom grant type only works for token end point.

**Comment by leastprivilege** [comment]
No.

You can *disable* password by not providing an implementation of the resource owner validator.

**Comment by satyajit-behera** [comment]
Thanks. I have a scenario where the user needs to pass more parameter in addition to user name and password for generating token. I can easily create this using "IExtensionGrantValidator".

But the user can also login using only the username and password without providing the additional parameters if I don't disable the default resource owner validator.

Is this scenario possible?

**Comment by leastprivilege** [comment]
You can disable the password grant - as I said above already.

**Comment by satyajit-behera** [comment]
Thanks
