### ISSUE TITLE
SetNoCache interference

### ISSUE THREAD

**Issue by Zinshis** [IdentityServer/IdentityServer4#164]
I am implementing Asp.NET Identity alongside IdentityServer with ResourceOwner grant type. Inside my custom IResourceOwnerPasswordValidator I use the standard Asp.NET Identity's SignInManager PasswordSignInAsync function to validate the user. This function however sets the "Cache-Control" header to "no-cache". This conflicts with the TokenResult's ExecuteAsync function at the end of the pipeline which also tries to set this header, resulting in a duplicate key error.
Is there a workaround to this I might have missed, or should I just inject the context in my IResourceOwnerPasswordValidator and remove the header again?

**Comment by leastprivilege** [comment]
IIRC this method in aspnet id sets a cookie? you don't want to sign in the user - just validate the password. 

@brockallen we need to add an implementation of that interface to the aspnetid sample

**Comment by PivotalAnimal** [comment]
Hi @Zinshis - I just looked over Identity code and didn't find anywhere that set cookies. I might be mistaken, but PasswordSignInAsync is probably what you need if you are trying to integrate user authentication from it with IS4. I have an example of how this is done on my repo. Contributions are welcome.

**Comment by leastprivilege** [comment]
It does set a cookie

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L185

you rather want to call `CheckPasswordAsync`

https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L253

**Comment by PivotalAnimal** [comment]
_PasswordSignInAsync_ calls _CheckPasswordAsync_ internally but also performs other housekeeping tasks. I think then that it is a viable option to call either depending upon the use case.
[https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L236](https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L236)

**Comment by leastprivilege** [comment]
You don't want to set a cookie for a resource owner password credential request. That does not make sense - you only want to validate the password.

**Comment by PivotalAnimal** [comment]
I am trying to find where in _PasswordSignInAsync_ is the actual cookie set. There is also the _SignInAsync_ method that calls Context.Authentication.SignInAsync. And I think that is what sets the cookies.

**Comment by leastprivilege** [comment]
Context.Authentication.SignInAsync does.

**Comment by PivotalAnimal** [comment]
So it makes sense that if one avoids using _SignInAsync_ but instead calls either _PasswordSignInAsync_ or _CheckPasswordAsync_, no cookies will be set.

**Comment by PivotalAnimal** [comment]
Looking at IS4 Host UI, how is the flow supposed to go for resource owner password credential request? How about the others? That would be useful documentation. Particularly the semantics and usage of _LoginController.cs_ and any other integration point. I know for sure that _HttpContext.Authentication.SignInAsync_ is being called during the _MVC and API Sample_. How about the other workflows? Client Credentials Grant? Extension Grants? Federated Auth / Google? I know there is more. I am just getting started. Thanks!

**Comment by leastprivilege** [comment]
Sure - once the code is done we will work on docs.

Here's a starting point:

https://github.com/IdentityServer/IdentityServer4/tree/dev/docs

**Comment by Zinshis** [comment]
Thank you both for the extensive feedback. I'll use the CheckPasswordAsync method as suggested.
