### ISSUE TITLE
Redesign scope validator

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1640]
Cuz it needs it

**Comment by leastprivilege** [comment]
wordz!

**Comment by granatoidas** [comment]
Are there perhaps plans to refactor ScopeValidator in such way that IdentityServer supports incremental authorization?

**Comment by leastprivilege** [comment]
Yes - it is planned for 3.0 because it is a breaking change. 

The incremental authZ spec is also far from being final..

**Comment by brockallen** [comment]
For reference: #3302

**Comment by leastprivilege** [comment]
tracked here: https://github.com/IdentityServer/IdentityServer4/issues/3520
