### ISSUE TITLE
Prefix default endpoints

### ISSUE THREAD

**Issue by mangelarilla** [IdentityServer/IdentityServer4#1641]
I´ve been looking around the `AddDefaultEndpoints` method trying to add a prefix to the default endpoint routes but they are all internal and I can't find a way to configure its routes.

Am I missing something which makes adding a route prefix more trivial?

EDIT:
I did this global workaround, but I'm not certain that it will not cause troubles with the endpoint routers.

`app.Map("/auth", appBuilder => appBuilder.UseIdentityServer());`

**Comment by leastprivilege** [comment]
They are fixed. Why?

**Comment by mangelarilla** [comment]
It is needed in my situation because of the internal server routing, but it seems that wrapping the appbuilder inside that route map works, need further testing though.
