### ISSUE TITLE
Allow Custom Client Secret Validation

### ISSUE THREAD

**Issue by szahn** [IdentityServer/IdentityServer4#1642]
It would be great if ClientSecretValidator was an interface or sub-classable such that I can add implement my own client secret validation. The current Identity Server services do not provide a plugin-architecture to do the following:

1.) If Client.RequireClientSecret is false or no client secret is provided during client credential grant, check the presence of a client certificate using _httpContextAccessor.HttpContext.Connection.GetClientCertificateAsync() and use certificate pinning to validate the client id with that cert.

2.) Instead of returning the all client details from the store upon validating the client secret, delegate secret validation to a sql proc by passing in the client id, secret. This prevents persisting the raw client(s) secret in memory.

To do this right now, I have to fully implement ITokenRequestValidator which means duplicating validation logic for all grant types which isn't something I want to do. Sometimes implementing ICustomTokenRequestValidator isn't sufficient to override pre-custom and post-custom validation logic.

**Comment by leastprivilege** [comment]
I will look into it - but some comments: 

You can implement 1) with the current bits - just plug in your own ISecretValidator.

for 2) the client secret is hashed - what's wrong with that having it in memory?

**Comment by leastprivilege** [comment]
Is that what you have in mind? https://github.com/IdentityServer/IdentityServer4/pull/1644

**Comment by leastprivilege** [comment]
No response. I merged it.
