### ISSUE TITLE
How to access IProfileService from within IdentityServer

### ISSUE THREAD

**Issue by germansak** [IdentityServer/IdentityServer4#1643]
- [X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
First of all I'm quite new to IS, but I have developed an IdentityServer with this functionality working.
Now I'm migrating it to the new version and I'm having this issue.
I'm trying to access my CustomClaimsService (:IProfileService) from within IdentityServer but it never gets executed. I'm taking as a base the Combined_AspNetIdentity_and_EntityFrameworkStorage sample on IdentityServer4.Samples
If I access from, let's say, MVC Client, the CustomClaimsService gets called and the token gets filled with my custom claims.

My ConfigureServices()

           

``` csharp
public void ConfigureServices(IServiceCollection services)
        {
            services.AddTransient<IEmailSender, EmailSender>();

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            string connectionString = Configuration.GetConnectionString("DefaultConnection");
            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                    //options.EnableTokenCleanup = true;
                    //options.TokenCleanupInterval = 30;
                })
                .AddAspNetIdentity<ApplicationUser>()
                .AddProfileService<CustomClaimsService>();

            services.AddMvc();

        }
```

and my Configure()

```csharp
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // this will do the initial DB population, but we only need to do it once
            // this is just in here as a easy, yet hacky, way to get our DB created/populated
            InitializeDatabase(app);

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseStaticFiles();

            // app.UseIdentity(); // not needed, since UseIdentityServer adds the authentication middleware
            app.UseIdentityServer();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
```

**Comment by brockallen** [comment]
I can't repro your issue. I did the minimal steps to add a custom profile service to that sample and it's working fine.

**Comment by germansak** [comment]
Hi, Brock. Thank you for your help. 
I guess I'm doing something wrong then

These are the steps I do

* Dotnet new with is4inmem
* Add Class Library "CustomClaimService" that derives from IProfileService and implement the interface (I touch nothing inside - I leave the exceptions)
* Add `.AddProfileService<CustomClaimService>();` to the IdentityServer Builder
* Add `services.AddTransient<IProfileService, CustomClaimService>();` to ConfigureServices
* Add a breakpoint inside of GetProfileDataAsync
* Start debugging
* Login with one of the in-memory user
* The breakpoint never gets hit

On the other example that I was working I've added a MVC Client and when I logged in the breakpoint got hit.
I uploaded the test to a repo. It's https://github.com/germansak/istestprofile

There must be something I'm missing :-(

**Comment by naveddeshmukh** [comment]
[https://github.com/IdentityServer/IdentityServer4/issues/458 ](ISSUE 458) 

> It's (GetProfileDataAsync Method on IProfileService) only called if you ask for scopes that have additional claims. 
@brockallen 

When you login into IdentityServer directly (by that I mean, You're **not redirected** to Identity Server by a client when using Implicit or Hybrid Flow). The GetProfileDataAsync Method on IProfileService never gets called. 

The GetProfileDataAsync Method on IProfileService  is Invoked when the client request additional claims for the user.

**Comment by brockallen** [comment]
Also:

> Add a breakpoint inside of GetProfileDataAsync

This isn't always called depending on the scopes requested. Put a break point in the ctor instead.

Also, yes, this:

> .AddTestUsers(TestUsers.Users) adds TestUserProfileService to IServiceCollection.

registers its own profile service. Choose one.

**Comment by germansak** [comment]
Actually I used test users to make the demo only. The actual app gets users from a database.
So what should I do? I need to get domain information from the user logged in from within IdentityServer since I run an admin panel to do users and roles administration, so I need to make policy based auth using the user information (I.E. Is he/she on IT?). Should I access the users database directly and make my own "ProfileService"? Is there any other way to reuse CustomClaimService so I don't have to write auth twice?

Thank you all for your help
German

**Comment by naveddeshmukh** [comment]
I guess SO will be a better place to discuss this? @brockallen

**Comment by brockallen** [comment]
Yes, SO please.

**Comment by Janidbest** [comment]
Just want to add my 2cents..

Compared to prev version (core1.2, old idmsrv4), ProfileService is being called on every token request and includes the claims, but now the claims are linked to scope, means if your request includes that scope that has required claims ( application special), then the service is being invoked.

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/release/topics/resources.html#defining-custom-identity-resources

and

http://docs.identityserver.io/en/release/reference/profileservice.html

**Comment by David-Harvey** [comment]
Hi guys,

I understand @germansak question and I understand why the IProfileService is not firing. 

_The GetProfileDataAsync Method on IProfileService is Invoked when the client request additional claims for the user._ 

My client(s) make an additional claim and as such fires the IProfileService GetProfileDataAsync when needed.

**However** I'm little lost on how to do something similar when you login directly to Identity Server. As you're not acting as client, so you're not requesting additional claims. So how would you inject a tenant header to be verified? (why I'm trying to do it).

I appreciate this isn't a bug, but would even appreciate if you drop me a link to a relevant issue/guidance.

@brockallen
