### ISSUE TITLE
Extending ability to set CSP frame-src on EndSessionCallback

### ISSUE THREAD

**Issue by null-d3v** [IdentityServer/IdentityServer4#1647]
- ☑ I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I have a Client which itself is a WS-Federation IdP. During the logout process, the CSP headers on the endsession callback are too strict and do not allow the Client to cycle through its realms. I'd like a way to specify or alter the CSP header on the endsession callback.

The two approaches I can think of, and possibly submit a PR for, are to:
- Add a URI collection to EndSessionCallbackValidationResult for CSP frame-src
- Use the new URI collection to populate the CSP frame-src header in EndSessionCallbackResult instead of the FrontChannelLogoutUris

Population of this collection could either be:
- Accomplished manually by those implementing an IEndSessionRequestValidator
or
- A facet of Client configuration, adding a collection of CSP frame-src URIs alongside the FrontChannel URIs.

**Comment by brockallen** [comment]
Given that I don't think you'd want IdSvr to have to know all the upstream WS-Fed hostnames (that would be a very leaky abstraction), then I could simple imagine a flag to disable frame-src altogether... perhaps this could be per-client even?

**Comment by null-d3v** [comment]
Disabling definitely an option; however the EndSessionCallbackResult does allow this in a way in that if the headers are already set it will not override them. So basic middleware on the /connect/endsession/callback endpoint which sets both CSP headers to empty strings achieves this. Currently this is what we are doing until we are able to kill the undesirable Client.

I think it's an alright approach for a solution given the context of the requirements. Could add this as an official option or even just update documentation for the behavior?

**Comment by brockallen** [comment]
I was thinking about this... us adding frame-src is overly cautious, so I think a simple global flag to disable is sufficient. Any objections?

**Comment by brockallen** [comment]
PR submitted -- have a look

**Comment by brockallen** [comment]
Done

**Comment by TheJayMann** [comment]
I was having the same problem, where I had a client that acts as a small wrapper for a website which exists on a separate domain.  By default, attempting to sign out would properly load the client, but the redirect would fail as it would have an origin not listed in the frame-src. The result is the client remains signed in.  I tried to use the `RequireCspFrameSrcForSignout = false`, and now I have a different problem.  It appears, due to the default-src 'none', none of the iframes will load at all.  The result is that all clients remain signed in on a signout.

**Comment by brockallen** [comment]
@TheJayMann  Can you open a new issue for that? We'll track it as a separate bug. Thanks.
