### ISSUE TITLE
IdentityServer4 assembly is not strongly named

### ISSUE THREAD

**Issue by DavidUrting** [IdentityServer/IdentityServer4#1653]
When adding the IdentityServer4 2.0.1 NuGet to an ASP.NET Core 2 application that is strongly named (signed) I get a `System.IO.FileLoadException: Could not load file or assembly 'IdentityServer4, Version=2.0.1.0, Culture=neutral, PublicKeyToken=9aed67b161f7db78' or one of its dependencies. A strongly-named assembly is required.` when running the application. 

Is it possible to provide a strong name in future releases?

**Comment by leastprivilege** [comment]
We don't provide strong named versions of our assemblies.

Maybe this will help you:
https://github.com/dsplaisted/strongnamer

**Comment by leastprivilege** [comment]
..and why would you strong name an ASP.NET Core application in the first place?

**Comment by DavidUrting** [comment]
The situation is that the ASP.NET Core application uses an (strongly named) framework library that is used company-wide. In that library there are some `internal` members that should be made visible to the ASP.NET Core application. For this we use `InternalsVisibleTo()`. But to make internals visible from a signed library to another assembly, that assembly has to be signed too. And a signed assembly cannot load unsigned assemblies. So it is a _domino-effect_...

The pragmatic solution here would be to make those `internal `members `public` and put some documentation on those members that they should not be used in other applications. So it is not a blocking issue, but rather an annoying issue.

Currently, we are evaluating **OpenIddict** and **IdentityServer4**. OpenIddict has the same issue but they will probably provide a strong key. I was using StrongNamer to work around the OpenIddict issue, but StrongNamer crashes on IdentityServer4. There is soms assembly that Mono.Cecil cannot load (BadImageException). 

So I removed StrongNamer for now, removed the strong name from the ASP.NET core application and made those members public in that library. So I can continue the evaluation for now...

**Comment by leastprivilege** [comment]
The pragmatic solution would be to remove the strong names everywhere ;)

**Comment by DavidUrting** [comment]
I know, but the problem is that the _framework library_ exists since 2004 and is used by 100+ company applications. Also, the library has to be present in the GAC and redirects are used quite heavily. So it is better that I do not touch the signing part of the assembly if I want to keep my job :)

**Comment by leastprivilege** [comment]
:) OK - in that case you could clone our repo and sign it yourself.

I am wondering what the Cecil problem is....

**Comment by DavidUrting** [comment]
I had to build a custom StrongNamer version to find the error: Mono.Cecil.ModuleDefinition.ReadModule() fails on the IdentityServer4.dll: **Format of the executable (.exe) or library (.dll) is invalid**. I will contact the maintainers of StrongNamger to report this issue since it steems to be an issue with the used Mono.Cecil version.

**Comment by leastprivilege** [comment]
OK - keep us posted. I will close this for now.
