### ISSUE TITLE
DefaultGrantStore RemoveAsync hides grants possibly leaking out of defined policies

### ISSUE THREAD

**Issue by janpieterz** [IdentityServer/IdentityServer4#1655]
As discussed in #1634 the DefaultGrantStore's delete method `RemoveItemAsync(string key)` calls the underlying store `Store.RemoveAsync(string key)` and suggests it always goes well (no exceptions nor validation checks it exists). Looking at the EntityFramework implementation (one others will use as a reference implementation) this is very much the case, as seen in the method here: https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Stores/PersistedGrantStore.cs#L106

It could be interesting to create this contract stronger. For example, there could be an extra method `VerifyExistsAndRemove` that follows most of the same logic, except it does not capture any exceptions and throws if it doesn't exist.

Another method could be to create `Task<bool> TryRemoveAsync(string key)` and not have any other Remove method, making it obvious that the action can fail and forcing the logic for how to handle this at a higher level.

The current way exposes failures everywhere a specific PersistedGrant would be deleted as any DbUpdateConcurrencyException error is swallowed and (for example) `null` values (as with #1634) and other bugs higher up can cause the PersistedGrant's behavior to fall outside of defined policies.

**Comment by brockallen** [comment]
I guess I'm missing something -- what would the calling code do if this new `TryRemove` API returned `false`?

**Comment by janpieterz** [comment]
So this originated from the the #1634 bug where something should have been deleted but wasn't, and it did not notify callers of the Remove method. This caused refresh tokens to stay valid because the code deleting them never had any clue it failed.

Making this an explicit contract (a remove can fail or succeed) makes it something exceptions can be thrown for (Your one time use refresh token could not be deleted). There are other places the Remove method is used and certainly for PersistedGrants it seems applicable to be very careful with this.

So it'd make it an explicit decision to ignore or handle a false return, not an implicit ignore of a failed remove.

**Comment by brockallen** [comment]
Reassigning to be part of the RT rework.

**Comment by brockallen** [comment]
Reviewed and given that the original issue was solved, it's unclear if this is still needed.
