### ISSUE TITLE
Session failure in "multithreading" scenario.

### ISSUE THREAD

**Issue by dfrunet** [IdentityServer/IdentityServer4#1656]
As it was recommended, I first asked this on Stackoverflow, but probably that's too special for the community.
https://stackoverflow.com/questions/46810139/identity-server-4-defaultusersession-how-to-override-get-setclientlistasync
Briefly: a "dashboard" web app (RP1), authorized by idsrv displays several iframes with separate web apps (RPs), using the same OP. Requests from RP2 .. RPN comes simulteniosly and contain only RP1 in the clients list in the user's session. Then the last handled request overrides the cookie and we have RP1 and RPN ids only, when it's time to log out. The simplest solution seems to be caching the lists in IdSrv, compare and summ the instance from cache with the one from cookie when adding new item, but how to implement it the best way? In the current state the behavior looks like a bug.

**Comment by brockallen** [comment]
> In the current state the behavior looks like a bug.

Possibly, but also what you suggest is very hard to do without imposing server-side state.

**Comment by dfrunet** [comment]
I see, but I have to solve this in my environment anyway... So any suggestion how to override the client list handling without mass coding or copy-pasting would be much appreciated. Wish there were some virtual methods in DefaultUserSession and a possibility to inject my custom inherritor...

**Comment by brockallen** [comment]
Well, consider a decorator for it then, and pass thru the methods you don't need to tweak. We can consider making those virtual on the default.

**Comment by dfrunet** [comment]
I've generally solved this by explicit implementing IUserSession.AddClientIdAsync() and IUserSession.GetClientListAsync(), but still need DefaultUserSession to be public to make possible any enheritance. For now just copied and pasted. When could we expect the change to be published?

**Comment by brockallen** [comment]
> When could we expect the change to be published

What change?

**Comment by brockallen** [comment]
We'll add it for 2.1: https://github.com/IdentityServer/IdentityServer4/issues/1791. We can track it here.
