### ISSUE TITLE
Repository does not contain a config.cs file referenced in docs.

### ISSUE THREAD

**Issue by lenj962** [IdentityServer/IdentityServer4#1660]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
not enough info.

**Comment by lenj962** [comment]
I'm working through the "IdentityServer 4 - Protecting an API using Passwords" sample I cannot find the files in the GitHub repository that are reference in the docs.  For example, which file in the repos has the code referenced here:

> Adding a client for the resource owner password grant
> You could simply add support for the grant type to our existing client by changing the AllowedGrantTypes property. If you need your client to be able to use both grant types that is absolutely supported.
> Typically you want to create a separate client for the resource owner use case, add the following to your clients configuration:
> public static IEnumerable<Client> GetClients()
> {
>     return new List<Client>
>     {
>         // other clients omitted...
> 
>         // resource owner password grant client
>         new Client
>         {
>             ClientId = "ro.client",
>             AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
> 
>             ClientSecrets =
>             {
>                 new Secret("secret".Sha256())
>             },
>             AllowedScopes = { "api1" }
>         }
>     };
> }

**Comment by brockallen** [comment]
Here: https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/2_ResourceOwnerPasswords/src/QuickstartIdentityServer/Config.cs#L40

**Comment by lenj962** [comment]
Got it!  Thanks.  It's a lot easier to follow things when the narrative and the repos are consistent.  Getting on a roll!
