### ISSUE TITLE
Using IS4 with "old" MVC 5

### ISSUE THREAD

**Issue by nixa333** [IdentityServer/IdentityServer4#1663]
Hi there, as the title suggests I'm using IS4 with MVC5. IS4 is great, but I think I'm having problems with MVC5 implementation of Authentication. 
For MVC5 I followed IS3 tutorials and set it up like this:

```C#
AntiForgeryConfig.UniqueClaimTypeIdentifier = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier";

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                CookieHttpOnly = true
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions {
                Authority = ConfigurationManager.AppSettings["Authority"],
                ClientId = ConfigurationManager.AppSettings["ClientId"],
                ClientSecret = ConfigurationManager.AppSettings["ClientSecret"],
                RedirectUri = ConfigurationManager.AppSettings["RedirectUri"],
                ResponseType = "code id_token",
                Scope = "openid profile api.user",

                SignInAsAuthenticationType = "Cookies"
            });
```

IS4 is set up by IS4 tutorials and I believe there are no problems with it.

Logout with MVC is done with:

```C#
[HttpGet]
        public void Logout()
        {
            Request.GetOwinContext().Authentication.SignOut();
        }

        [AllowAnonymous]
        public void OidcSignout(string sid)
        {
            var cp = (ClaimsPrincipal)User;
            var sidClaim = cp.FindFirst("sid");
            if (sidClaim != null && sidClaim.Value == sid)
            {
                Request.GetOwinContext().Authentication.SignOut("Cookies");
            }
        }
```

Although I believe the OidcSignout method is never actually called, and that was something IS3 did.
My problem is the same as I had with external auths like Google or Facebook, in that when I  - login with account1 => logout => login with account2/3... I'm again logged in with the account1, or the first account I ever logged in with. This is the same situation I asked about [here](https://github.com/IdentityServer/IdentityServer4/issues/1556), and figured that's just the way those providers work, only now it's happening with my own auth provider.

These are MVC Client settings from DB:

AbsoluteRefreshTokenLifetime 	2592000
AccessTokenLifetime 	3600
AccessTokenType 	1
AllowAccessTokensViaBrowser 	0
AllowOfflineAccess 	0
AllowPlainTextPkce 	0
AllowRememberConsent 	1
AlwaysIncludeUserClaimsInIdToken 	0
AlwaysSendClientClaims 	0
AuthorizationCodeLifetime 	3600
EnableLocalLogin 	1
Enabled 	1
IdentityTokenLifetime 	3600
IncludeJwtId 	0
LogoutSessionRequired 	1
PrefixClientClaims 	1
ProtocolType 	N'oidc'
RefreshTokenExpiration 	1
RefreshTokenUsage 	1
RequireClientSecret 	1
RequireConsent 	0
RequirePkce 	0
SlidingRefreshTokenLifetime 	1296000
UpdateAccessTokenClaimsOnRefresh	0

**Comment by brockallen** [comment]
> Although I believe the OidcSignout method is never actually called, and that was something IS3 did.

I assume the MVC client has the FrontChannelLogoutUri configured?

> My problem is the same as I had with external auths like Google or Facebook, in that when I - login with account1 => logout => login with account2/3... I'm again logged in with the account1, or the first account I ever logged in with

I didn't really follow that, but we keep track of the clients you have logged into by adding those to the authentication cookie within IdSvr. If you change the identity of the user at IdSvr (which means getting a new cookie), then you lose the list of client and they won't get notified at signout (because it's a different user at that point).

**Comment by nixa333** [comment]
Hmm, seems that somehow my DB didn't update correctly on last IS4 update with migrations, so I was missing Back/Front channel fields in my Clients table. Is it enough to set FrontChannelLogoutUri to OidcSignout method to configure everything? If not, could you please explain [this help article](http://docs.identityserver.io/en/release/topics/signout.html?highlight=FrontChannelLogoutUri%20) to me since I don't understand how, for example, would that work if I don't have LoggedOut page, but rather redirect my users back to home page after the Logout.

**Comment by brockallen** [comment]
> If not, could you please explain this help article to me since I don't understand how

It's your responsibility to understand the specs. Here's the one in question: https://openid.net/specs/openid-connect-frontchannel-1_0.html

> PS. It would also be nice if you added tutorials for this.

It would, but this is a project that's paid for by our free time. It's FOSS, so you can contribute.
