### ISSUE TITLE
No refresh token returned with TokenUsage.ReUse 

### ISSUE THREAD

**Issue by odinnou** [IdentityServer/IdentityServer4#1665]
Hello, 
Is it possible to return the refreshToken (no updated) in the result of refreshToken request ?
It seems to be returned only if we configure RefreshTokenUsage to TokenUsage.OnTimeOnly

Thanks!

Kind Regards

Rémi

**Comment by odinnou** [comment]
I think, this refreshToken was returned in the 1.5.2 version of IS4

**Comment by odinnou** [comment]
The client :


> new Client
>                 {
>                     ClientName = "Common users",
>                     Enabled = true,
>                     ClientId = IdentityConstants.CLIENT_USERS,
>                     ClientSecrets = new List<Secret>
>                     {
>                         new Secret("secret".Sha256())
>                     },
> 
>                      AllowedCorsOrigins=new List<string>
>                     {
>                         "https://.....net",...
>                     },
>                     AllowedGrantTypes = {    IdentityConstants.GRANT_TYPE_FACEBOOK },
> 
>                     AbsoluteRefreshTokenLifetime = 2000,
>                     SlidingRefreshTokenLifetime = 600,
>                     RefreshTokenUsage = TokenUsage.ReUse,
>                     RefreshTokenExpiration = TokenExpiration.Sliding,
> 
> 
>                    AllowedScopes = new List<string>
>                        {
>                          StandardScopes.OfflineAccess,
>                        IdentityConstants.SCOPE_BASIC,
>                           IdentityConstants.SCOPE_LOGGED
>                        },
> 
>                    AllowOfflineAccess=true,
>                    AccessTokenLifetime=60,
>                     AccessTokenType=AccessTokenType.Reference
>                 }

**Comment by odinnou** [comment]
Ok, 
I think i found an issue with **TokenUsage.ReUse** : this mode don't care about **TokenExpiration.Sliding** and **SlidingRefreshTokenLifetime**
I tried with **TokenUsage.OneTimeOnly** mode and it works

**Comment by leastprivilege** [comment]
Thanks - we'll have a look.

**Comment by leastprivilege** [comment]
fixed. thanks!

We publish a new package soon.

**Comment by odinnou** [comment]
np! I am happy to contribute to this project
You help me so much ^^

Thanks

**Comment by odinnou** [comment]
I check this morning and it works like a charm! Thank you
