### ISSUE TITLE
Windows auth and Safari not working

### ISSUE THREAD

**Issue by helzgate** [IdentityServer/IdentityServer4#1666]
- [ x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
When using the latest example app, when I use windows authentication line 161 result?.Principal is always null from AccountController found [HERE](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/Quickstart/Account/AccountController.cs) 
This causes the authentication prompt to constantly loop indefinately.

This same setup works fine when using Chrome btw.

`result` is **not** null but `Principal` is.  This looks like a Safari + Windows Authentication issue that effects everything from trying to browse a IndentityServer4 authenticated website from a MAC to using an iOS app.  I'm not sure if it's a Negotiate/NTLM/Kerberos issue or what.  There are so many articles on the web with people complaining about Safari not working well with Windows Authentication but this would make the IdentityServer4 useless when using windows authentication in Xamarin/Native/React Native/Native Script apps, this is really bad if it's true.

If someone knows the IdentityServer4 + Windows auth won't work with Safari please say so, so that I don't look like a complete idiot in front of my boss.  I've been struggling with this for days.  Thanks!

**Comment by brockallen** [comment]
> There are so many articles on the web with people complaining about Safari not working well with Windows Authentication but this would make the IdentityServer4 useless when using windows authentication in Xamarin/Native/React Native/Native Script apps, this is really bad if it's true.

You mean make ASP.NET Core useless. I'd suggest opening an issue with Microsoft, as they are the ones that provide that feature.

**Comment by helzgate** [comment]
@brockallen Ah, good point.  Thanks for the response sir!

**Comment by helzgate** [comment]
By the way, there is ZERO support for challenge response in safari.  So windows authentication will never work in safari or within a Xamarin app out of the box.
