### ISSUE TITLE
User Access Token is granted on WebAPI even when Scope is defined and user does not have scope

### ISSUE THREAD

**Issue by murphycrosby** [IdentityServer/IdentityServer4#1672]
When I try to access the WebAPI with a different Bearer Token that specifically has a different Scope, I get 403 Forbidden, which is correct.  However, when I use a user access token from a login from the Interactive Identity server login page, the call to the WebAPI (in PostMan) succeeds when it should fail.

```
var scopePolicy = new AuthorizationPolicyBuilder()
	.RequireClaim("scope", "CoreAPI.Admin")
	.Build();

services.AddMvc(options =>
{
	options.Filters.Add(new AuthorizeFilter(scopePolicy));
})
.AddJsonOptions(options => options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver());

services.AddAuthentication(options =>
{
	options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
	options.Authority = "https://myidentity001.azurewebsites.net/";
	options.Audience = "CoreAPI";
	options.RequireHttpsMetadata = false;
});
```

**Comment by leastprivilege** [comment]
All code you are showing here is from Microsoft...how is that an IdentityServer problem?

**Comment by murphycrosby** [comment]
Apologies.  I followed the code setup like here for validating scopes.  Just not sure the issue for when passing a users access_token.
 http://docs.identityserver.io/en/release/topics/apis.html

**Comment by leastprivilege** [comment]
you can use https://jwt.io to have a look inside the token

**Comment by murphycrosby** [comment]
For some reason the User has the scope, but the do not anywhere in the database.  Does it get tacked on because that is the site that they are logging in to?

`{
  "nbf": 1508965287,
  "exp": 1508968887,
  "iss": "https://myidentity001.azurewebsites.net",
  "aud": [
    "https://myidentity001.azurewebsites.net/resources",
    "CoreAPI"
  ],
  "client_id": "91d54606-9875-94fa-c5b3-6160286de4f4",
  "sub": "bd60f258-6ce4-4781-86bb-3adfc96469f1",
  "auth_time": 1508965282,
  "idp": "local",
  "firstName": "Jim",
  "lastName": "Bob",
  "email": "jim.bob.crosby@gmail.com",
  "fullName": "Jim Bob",
  "userId": "bd60f258-6ce4-4781-86bb-3adfc96469f1",
  "scope": [
    "openid",
    "profile",
    "CoreAPI.Admin",
    "offline_access"
  ],
  "amr": [
    "pwd"
  ]
}`

**Comment by leastprivilege** [comment]
Users don't have scopes. Clients do.

**Comment by murphycrosby** [comment]
Thanks...since I know who the user is now, then in my app I need to look up to see if they can access the app?

**Comment by leastprivilege** [comment]
yes
