### ISSUE TITLE
Revoking access token is not working

### ISSUE THREAD

**Issue by UdayaBhandaru** [IdentityServer/IdentityServer4#1674]
Hi Team,

I am revoking access token as shown in the below code
var accessToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken);
            var refreshToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.RefreshToken);
            if (!string.IsNullOrEmpty(accessToken))
            {
                var tokenrevocationClient = await _httpClientProvider.GetTokenRevocationClient();
                var refreshAccessTokenResponse = await tokenrevocationClient.RevokeAccessTokenAsync(accessToken);
                
            }
            if (!string.IsNullOrEmpty(refreshToken))
            {
                var tokenrevocationClient = await _httpClientProvider.GetTokenRevocationClient();
                var refreshRefreshTokenResponse = await tokenrevocationClient.RevokeRefreshTokenAsync(refreshToken);
            }

But still the access token is not revoked . it is still active

**Comment by leastprivilege** [comment]
What kind of access token are you using? You can only revoke reference tokens (and refresh tokens).

**Comment by UdayaBhandaru** [comment]
We are using JWT Token. What does RevokeAccessTokenAsync in token revocation client do . Name suggests that we are revoking Access Token

**Comment by leastprivilege** [comment]
JWT tokens cannot be revoked. You'd need to switch to reference access tokens.

**Comment by UdayaBhandaru** [comment]
Is there any sample for the sample with the implementation

**Comment by leastprivilege** [comment]
Set the `AccessTokenType` on the `Client` to `Reference`.

**Comment by UdayaBhandaru** [comment]
Thanks

**Comment by OmidRafiee** [comment]
I'm having a problem as well.
After logging on to two different browsers, one of the browsers has valid login after leaving.

![Untitled](https://user-images.githubusercontent.com/25098596/55679485-8dd74900-5921-11e9-99ba-7e6f8362413b.png)



"clientType": 0,
  "absoluteRefreshTokenLifetime": 2592000,
  "accessTokenLifetime": 3600,
  "consentLifetime": null,
  "accessTokenType":Refrence,
    "allowAccessTokensViaBrowser": false,
  "allowOfflineAccess": true,
  "allowPlainTextPkce": false,
  "allowRememberConsent": true,
  "alwaysIncludeUserClaimsInIdToken": true,
  "alwaysSendClientClaims": false,
  "authorizationCodeLifetime": 300,
  "frontChannelLogoutUri": null,
  "frontChannelLogoutSessionRequired": true,
  "backChannelLogoutUri": null,
  "backChannelLogoutSessionRequired": true,
  "clientId": "mvc",
  "clientName":"Test",
  "clientUri": null,
  "description": null,
  "enabled": true,
  "enableLocalLogin": true,
  "id": 3,
  "identityTokenLifetime": 300,
  "includeJwtId": false,
  "logoUri": null,
  "clientClaimsPrefix": "client_",
  "pairWiseSubjectSalt": null,
  "protocolType": "oidc",
   "refreshTokenExpiration": 1,
   "refreshTokenUsage": OneTimeOnly ,
  "slidingRefreshTokenLifetime": 1296000,
  "requireClientSecret": true,
  "requireConsent": false,
  "requirePkce": false,
  "updateAccessTokenClaimsOnRefresh": true,
  "postLogoutRedirectUris": [
    "http://localhost:5002/",
    "http://localhost:5002/signout-callback-oidc"
  ],
  "postLogoutRedirectUrisItems": null,
  "identityProviderRestrictions": [
    
  ],
  "identityProviderRestrictionsItems": null,
  "redirectUris": [
    "http://localhost:5002/signin-oidc",
    "http://localhost:37295/signin-oidc",
    "http://localhost:5002",
    "http://localhost:37295/"
  ],
  "redirectUrisItems": null,
  "allowedCorsOrigins": [
    
  ],
  "allowedCorsOriginsItems": null,
  "allowedGrantTypes": [
    "hybrid"
  ],
  "allowedGrantTypesItems": null,
  "allowedScopes": [
      "account",
    "offline_access",
    "profile",
    "openid"
  ],
  "allowedScopesItems": null,
