### ISSUE TITLE
On the OpenIdConnect authentication enabled HTTPS callback RedirectUri does not take effect, the default is HTTP

### ISSUE THREAD

**Issue by snwxd** [IdentityServer/IdentityServer4#1677]
IdentityServer4 + asp.net Core 2.0，
Deployed to the production environment, the use of OpenIdConnect authentication, enabled HTTPS, callback RedirectUri default HTTP, how to solve? Server:https://uc.xxx.com, OpenIdClient:https://mvc.xxx.com.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
