### ISSUE TITLE
Could I use IdentityServer for my setup

### ISSUE THREAD

**Issue by thelastnovemberrain** [IdentityServer/IdentityServer4#1680]
Hi, I am trying to understand if I can use IdentityServer for  my setup.

I need to create a system with an authentication service, where other products can login. The idea is to use SSO which would allow me to login with one product, and then use another product without signing in. 
The problem is that I need to have a separate session for every login and if, for instance, I login to a ProductA and there is a session created(in my auth service), when I then open ProductB, a request is made to the authntication service with a session id from productA, the auth service checks this session id and creates a separate session id for productb, so it is not a classic SSO. Would it be possible to achieve with IdentityServer?
Thank you.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
