### ISSUE TITLE
QUESTION: external providers and provisional users?

### ISSUE THREAD

**Issue by kibagami-jubei** [IdentityServer/IdentityServer4#1682]
Hi, I'm looking at the code for your guys' ws-federation implementation (this link: https://github.com/IdentityServer/IdentityServer4.WsFederation) and noticed something on the account controller, specifically, with the external-login-callback action. There's a piece of code using the test store and it's looking for a provisional user by ID and identity provider. If none is found, one is created, "provisionally," after that, the aforementioned is signed in along with its claims. So I'm wondering why that's needed and have a whole bunch of questions:

- I'm undestanding that this is all test data for demo and what not, but, what are we supposed to do in a production setting? 
- And how shall I proceed when using ASP.NET identity? 
- Should we do our own implementation of a IUserStore (which I read about on this bug report), if so, are we to maintain users and its external providers through some database?

**Comment by brockallen** [comment]
> what are we supposed to do in a production setting?

Do what your requirements tell you do do.

> And how shall I proceed when using ASP.NET identity

You will have to learn how it works and add it yourself to the IdentityServer host. We do have some samples to help you get started, but they're just for that purpose only.

> Should we do our own implementation of a IUserStore (which I read about on this bug report), if so, are we to maintain users and its external providers through some database?

I don't know what `IUserStore` is. For the user database, you'd use whatever you want. You mentioned ASP.NET Identity, so that's an option.

**Comment by kibagami-jubei** [comment]
> You will have to learn how it works and add it yourself to the IdentityServer host. We do have some samples to help you get started, but they're just for that purpose only.

What I'm asking is ASP.NET identity what you're supposed to use, instead of that quick-and-dirty-intended-for-demo test user store?

**Comment by leastprivilege** [comment]
yes - you would use some persistent user store - e.g. ASP.NET Identity.
