### ISSUE TITLE
Allow IdentityServerTools to not depend on HttpContext

### ISSUE THREAD

**Issue by ozonni** [IdentityServer/IdentityServer4#1684]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

IdentityServerTools is a great way to generate tokens in identity server, but it's bound to HttpContext. I use IHostedService to run background job, and there i need to call api protected by identity. But at this point there is no HttpContext. Is there an easy way to issue token without http context?

**Comment by leastprivilege** [comment]
For an "easy" way - you need access to the DI container. Do you have that in your IHostedService?

**Comment by ozonni** [comment]
yes, i do have DI there

**Comment by leastprivilege** [comment]
It's not ideal - but I think you can re-create that then:

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/IdentityServerTools.cs#L45

**Comment by brockallen** [comment]
Or perhaps we add another API where those values (time and issuer) are passed as params?

**Comment by ozonni** [comment]
In the end HttpContext used only for getting `IssuerUri` which is possible to get from `IdentityServerOptions` if it's configured. I solved this by creating custom `JwtTokenTools` and injecting `IdentityServerOptions`. In this case there is no HttpContext involved

**Comment by brockallen** [comment]
I added a new API with issuer as a param for this.
