### ISSUE TITLE
User Authentication with OpenID Connect

### ISSUE THREAD

**Issue by dicksonkimeu** [IdentityServer/IdentityServer4#1687]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
See attached/ 

1. My MVC app authenticates well and redirects back very when i log in with TestUsers. But when i used a user on Asp Identity error/ Wrong username or  password/

### Relevant parts of the log file

```
<log goes here>
```
![aspnet identity](https://user-images.githubusercontent.com/4476822/32254738-dc058812-beb3-11e7-9cfb-15fe88625dae.PNG)

**Comment by dicksonkimeu** [comment]
This is the DB/ I have a user in the AspNetUsers table and when i use a normal MVC app which i use for user to register it can authenticate very well.

![aspnet identity db - copy](https://user-images.githubusercontent.com/4476822/32254896-06d9f9a0-beb5-11e7-97a0-33e07c205114.PNG)

**Comment by janpieterz** [comment]
Try removing the `AddTestUsers` call you have in there.

The `AddAspNetIdentity` and `AddTestUsers` both register similar services, which makes sense since they're both 'user stores'.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
