### ISSUE TITLE
Resource owner password credential grant does not appear to include name claim in generated token

### ISSUE THREAD

**Issue by osudude** [IdentityServer/IdentityServer4#1692]
The browser based auth flows (implicit and authcode) seem to include the user name in the generated token but the Resource owner password credential flow does not seem to include the user name claim. IProfileService impl does not include name as a requested claim so it appears to get filtered out.  How do you get the Resource owner password credential flow to include the user name in the generated token?    Is this a client configuration issue?

```
new Client
                {
                    ClientId = "ro.client",
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,

                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowedScopes = { "TestApi", "openid", "profile", "email" },
                }
```

**Comment by TomCJones** [comment]
In OpenID Connect the only required claim is sub. The release of another claim requires the consent of the user. The client can ask for anything it wants. It may not get it.
