### ISSUE TITLE
Question: Permission vs Scope

### ISSUE THREAD

**Issue by ondrejtomcik** [IdentityServer/IdentityServer4#1693]
Hello,

It's clear that using scopes as authorization rules is bad idea and that's what I what my question will be about. In your video from [NDC Oslo](https://www.youtube.com/watch?v=EJeZ3YNnqz8&t=921s) you are presenting that

- Let's have Authorization Server
- It hosts applications and permissions information
- Resource server received token issued by Identity Server
- Resource server additionally contact Authorization Server
  - get permissions for current user
  - store them to current Users claims

Good approach, but I miss few points and I would like to ask you for details.
On IdentityServer, you're modelling claims and scopes. Scope define group of functionalities on top of resources client can do - higher abstraction of claims and preventing client to access some apiResource at all.

If you want to model permissions, you should link them to this scopes. If I understand it correctly, it's hierarchy between scopes and permissions. 

Another question is, permissions belongs to resource server, what is in identity server model - ApiResource. You should be able to link them somehow with that API resource, what means your two components - Identity Provider and Authorization Provider just use one extended database.

Thanks for your hints.

Btw, don't you have code from this presentation available please?

BR
Ondrej

**Comment by brockallen** [comment]
scopes, as per the OAUTh2 RFC, are permissions the user has granted the client. permissions in our NDC talk were about user permissions. those are two different sets of permissions.
