### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by ondrejtomcik** [IdentityServer/IdentityServer4#1694]
Hello,

am I able to exclude api resource claims from access token?
Access token requested by the client should not contain claims which belong to the api resource, to which it requires access to.
Something like AlwaysIncludeUserClaimsInIdToken but for Access Token.

Thanks

**Comment by brockallen** [comment]
> Access token requested by the client should not contain claims which belong to the api resource, to which it requires access to.

access tokens are supposed to be opaque to the client -- IOW they should not be looking at or parsing them. if they are, then use a reference token.

**Comment by ondrejtomcik** [comment]
Probably I didn't explain myself correctly.

Api Resource entity represents some API in the system. You can define scope - at least one, by which you can divide functionality of an API, and give different clients access to those parts. 

Then we have user claim types associated with that scope, that should be included in the access token. The claims specified here will be added to the list of claims specified for the API.

So if client is asking for access token, with that scope, returned access token contains user claims (assuming user has these claims). This access token is used for accessing those APIs.

So, back to my question:
Can be those claims excluded from access token?

Based on my previous question: https://github.com/IdentityServer/IdentityServer4/issues/1693
Using user claims for user permissions is wrong pattern. 
So I assume that permission should as well belong to users but should be linked with api resource, because usually permisions are defined per APIs.
So to your answer to my second questions, yes, those are different sets of permisions (scope, user perm.), but as I explain above, coupled with API resource they belongs to. Right?

**Comment by brockallen** [comment]
>  Can be those claims excluded from access token?

Well, by not configuring them in the first place :)

As for the rest of the question, I'm still a bit confused. Scopes, as defined in OAuth2, are meant for client permission granted by the end user, when the client is 3rd party to the API.
