### ISSUE TITLE
Missing code_verifier

### ISSUE THREAD

**Issue by hadiidbouk** [IdentityServer/IdentityServer4#1695]
After updating the IS4 and working with .Net core 2, 
the IS4 isn't working anymore for the mobile client.

```
fail: IdentityServer4.Validation.TokenRequestValidator[0]
      Missing code_verifier
```

After reading the source code , this error will appear only when ```RequirePkce ``` is set to true and the mobile client isn't sending the PKCE.

In my case, i keep getting this error even when i set ```RequirePkce``` to false ( it's set by default)

How can i fix this error ?

**Comment by leastprivilege** [comment]
This also happens when the mobile client is sending the code challenge on the authorize request - but not the code verifier at the token endpoint.

Might that be the case?

**Comment by hadiidbouk** [comment]
Yes, 

I am using  `AppAuth `, and the default of this library isn't sending any code verifier at the token endpoint.

If i want to send it by my self  then it should be as a PlainText and this it's not recommanded.

In fact the code was working without any problem before

**Comment by leastprivilege** [comment]
AppAuth is using PKCE - i am pretty sure they send a code challenge to begin with.

**Comment by hadiidbouk** [comment]
AppAuth is sending the codeVerifierin the AuthorizationRequest only

```
        /**
         * Creates an authorization request builder with the specified mandatory properties.
         */
        public Builder(
                @NonNull AuthorizationServiceConfiguration configuration,
                @NonNull String clientId,
                @NonNull String responseType,
                @NonNull Uri redirectUri) {
            setAuthorizationServiceConfiguration(configuration);
            setClientId(clientId);
            setResponseType(responseType);
            setRedirectUri(redirectUri);
            setState(AuthorizationRequest.generateRandomState());
            setCodeVerifier(CodeVerifierUtil.generateRandomCodeVerifier());
        }
```

This request is created after the performing the TokenRequest , and in the TokenRequest there is no codeVerifier by default.

**Comment by leastprivilege** [comment]
Are you using an old version of AppAuth? - what's the point of sending a challenge without the verifier??

The reason the behavior has changed is - in 1.x when `RequirePkce` was turned off - we simply ignored all PKCE parameters. 

In 2.x it is "on demand". IOW **if** the authorize request sends the challenge - we also require a verifier.

**Comment by hadiidbouk** [comment]
Thank you @leastprivilege  , now it makes sense .

**Comment by hadiidbouk** [comment]
I fixed this error by setting in the AppAuth library the same generated code in the auth request and in the token request.

I Use to generate the code  ```CodeVerifierUtil.generateRandomCodeVerifier()```
