### ISSUE TITLE
Custom claims for access token

### ISSUE THREAD

**Issue by vbenavidesa** [IdentityServer/IdentityServer4#1696]
So I have been learning and working with identity server 4 for a month now, and I want to add some custom claims to my **access_token**. I implemented a custom **IProfileService** and added to my **startup.cs** and it kind of works, let me explain:

```
public class MyProfileService : IProfileService
    {
        public Task GetProfileDataAsync(ProfileDataRequestContext context)
        {            
            var claims = new List<Claim>();            
            claims.Add(new Claim("FullName", "Joe"));
            claims.Add(new Claim("FullName", "Tester"));
            context.IssuedClaims = claims;
            return Task.FromResult(0);
        }

        public Task IsActiveAsync(IsActiveContext context)
        {
            context.IsActive = true;
            return Task.FromResult(0);
        }
    }
```
That is my custom test implementation of the **IProfileService**. Then I add it to my **startup.cs** like this:

`services.AddTransient<IProfileService, MyProfileService>();
`
So in my **access_token** I get the custom claims, that part is great, but I want to get the roles for my users, how can I get the user who is signing up to get his roles from my database, that is the part where I am struggling. Any advice would be great, I can inject the DbContexts for the users and roles from the ASP.net Identity but how can I get the actual user who is signing up so I can get the claims I want from the database.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
