### ISSUE TITLE
Authorization story

### ISSUE THREAD

**Issue by janpieterz** [IdentityServer/IdentityServer4#1701]
In the much linked post https://leastprivilege.com/2016/12/16/identity-vs-permissions/ it's mentioned that there is the feeling that in 2017 the authorization story might be tackled.

It's one of those things that comes up here often, with a lot of questions/confusion around the difference between `Identity` and `Permissions`. 

Took me a while to get a grip on this too, as claims are such an easy way to store a lot of this, but then you run into issues like refreshing the claims (when for example creating an account and assigning an account claim etc).

Is there any progress on this? Are there any open source frameworks that handle permissions well in the ecosystem asp.net/identity server? Is it something that's currently advised to write custom for each app (did this for us and doesn't require that much)? 

Either way, it might be worth creating a part in the docs explaining this difference, where Identity Server focuses and the suggestions? More than happy to kick off an article in the docs if this would be the direction.

**Comment by leastprivilege** [comment]
We'll have an announcement at NDC in January.

**Comment by janpieterz** [comment]
I'll be looking forward to that! Cheers
