### ISSUE TITLE
Make it possible to set the localization from the /connect/authorize request

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#1703]
Adding culture=it-CH&ui-culture=it-CH parameters to the URL of the /connect/authorize request and setting the localization using QueryStringRequestCultureProvider is ignored from IdentityServer4

It would be nice if IdentityServer4 supported optional parameters to set the localization from the /connect/authorize request.

**Comment by leastprivilege** [comment]
There's a standard OIDC parameter for that `ui_locale`.

**Comment by damienbod** [comment]
Using the ui_locales in the /connect/authorize request does not set the culture either

**Comment by leastprivilege** [comment]
of course not - this is your job.

**Comment by damienbod** [comment]
CultureInfo.CurrentCulture = new CultureInfo(culture);
CultureInfo.CurrentUICulture = new CultureInfo(culture);

Gets ignored, because the IdentityServer4 middleware is doing something

**Comment by damienbod** [comment]
Also this is not a question but a feature request, because I don't see how IdentityServer4 supports culture switches from the /connect/authorize request

**Comment by leastprivilege** [comment]
I don't follow - the authorize endpoint is a protocol endpoint.

We redirect to your UI and there you can read the standard `ui_locales` parameter from there - and do whatever **you** need to do for localization.

**Comment by damienbod** [comment]
No matter how I set the localization from this method, the culture is being used, set from somewhere else. It is not possible to set the culture using the /connect/authorize  which redirects to my login in the AccountController login. Identityserver4 redirects with a returnUrl parameter and the culture is incorrect.

**Comment by leastprivilege** [comment]
> No matter how I set the localization from this method

From which method?

**Comment by damienbod** [comment]
Calling /connect/authorize from an Implicit flow client.

Using localization middlerware, it is not possible to set the IdentityServer4 host localization using query parameters or filters. It is only possible using a cookie.

I'll document this with an example.

Greetings Damien

**Comment by leastprivilege** [comment]
I guess I don't know enough about how localization works - but we are not doing anything special for it.

**Comment by leastprivilege** [comment]
I will close this - because I think this is the job of the UI - not the protocol endpoint.

Please open a new issue - maybe someone else knows more about the localization middleware.

**Comment by damienbod** [comment]
OK, When I find the reason why, I'll let you know. Reason I opened the issue here, is because I suspect it's something to do with the IdentityServer4 middleware redirects. 

I still think it is not possible to use the ui_locales parameter to set the localization in as ASP.NET Core application using IdentityServer4.

If I open a view/controller in the same host (ASP.NET Core) which does not use the Identityserver4 middleware, the query string localization works.

Greetings Damien

**Comment by leastprivilege** [comment]
QS is the wrong approach for this type of application. I thought we agree on that.

Dropping a cookie from the account controller is the much better way.

**Comment by damienbod** [comment]
@leastprivilege I found a solution. The problem is that IdentityServer4 redirects the oidc endpoint and packs the query in a returnUrl and the culture is no longer set. I created a custom provider which checks for this redirect and the culture is set correctly for the host.

I'll document how to do this

**Comment by damienbod** [comment]
Why is the QS the wrong solution for this?

**Comment by pawepaw** [comment]
> I found a solution. The problem is that IdentityServer4 redirects the oidc endpoint and packs the query in a returnUrl and the culture is no longer set. I created a custom provider which checks for this redirect and the culture is set correctly for the host.

I'll document how to do this

@damienbod what is the need to parse returnUrl for ui_locales? can't you simple create a cookie with culture from ui_locales ?
