### ISSUE TITLE
Make it possible to configure the cookie.domain value for identity server cookies

### ISSUE THREAD

**Issue by osudude** [IdentityServer/IdentityServer4#1704]
It would be helpful if Identity Server provided a way to configure the domain for identity server cookies (possibly via IdentityServerOptions?).  This is important for load balanced environments.

**Comment by leastprivilege** [comment]
Why? Simply register your own cookie handler with the settings you want and set the default schemes.

**Comment by osudude** [comment]
OIC,  is this the correct way to do that?  


```
services.AddIdentityServer()
.
.
.
services.AddAuthentication(IdentityServerConstants.DefaultCookieAuthenticationScheme)
                .AddCookie(IdentityServerConstants.DefaultCookieAuthenticationScheme, options =>
                {
                    options.CookieDomain = ".foo.com";
                });
```

Can I just override the domain or do i need to specify all the cookie options?

**Comment by leastprivilege** [comment]
I can't remember how MS deals with multiple registrations of the same scheme name - this might work - or not. Give it a try and let us know..

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by AshleyPoole** [comment]
The example above doesn't work as when app.AddIdentityServer() is called after the services have been registered, it throws as the IDS schema has already been configured. Any suggestion as I'm struggling to find examples online for ASPNET Core 2.0 and IDS 4? @leastprivilege

**Comment by brockallen** [comment]
If you want your own cookie scheme, register it after IdentityServer and set it as the default scheme.
