### ISSUE TITLE
Consider support for cnf claim

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1708]
https://tools.ietf.org/html/rfc7800

**Comment by Jenan** [comment]
Is it pop token primarily used for native clients?

**Comment by leastprivilege** [comment]
It's for situation where you want to embed possession information into a token. The cnf claim.

**Comment by Jenan** [comment]
OK, if I want to use the PoP token with request signature to the API. Is it possible probable only in native clients or am I able to do it on web as well?

**Comment by leastprivilege** [comment]
Any client that has sufficient crypto library support could use signatures.

**Comment by leastprivilege** [comment]
done
