### ISSUE TITLE
Do not show claims_supported items for 'hidden' resource / scope in Discovery Document

### ISSUE THREAD

**Issue by Ruard** [IdentityServer/IdentityServer4#1709]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue

Why do I see claims under _claims_supported_ that are associated only to an IdentityResource / ApiScope where ShowInDiscoveryDocument is false? The claims are supported, but I would expect not to see those because the 'parent' (IdentityResource / ApiScope) is hidden. Why would I hide the supported scope as the related claim(s) remain visible?

Since it is not possible to hide claims, I think it would be nice if the list of _claims_supported_ can be reduced by not showing claims that are associated to hidden IdentityResources / ApiScopes only. Like already is the case for disabled resources / scopes.

### Steps to reproduce the problem

Start IdentityServer4 and go to the discovery document: http://localhost:5000/.well-known/openid-configuration There are _scopes_supported_ and _claims_supported_.

Disable 'My API' in ApiResources. Claims are removed from list.
Enable 'My API' again and set ShowInDiscoveryDocument = false for ApiScope 'My API'.
Claims remain visible on the list, while the scope is removed. Expected: claims are removed from the list.

**Comment by leastprivilege** [comment]
Thanks - that sounds like a bug.

In the meantime you can completely disable the claims_supported section in the discovery document via the discovery options.

**Comment by leastprivilege** [comment]
fixed.
