### ISSUE TITLE
internal static class StringExtensions

### ISSUE THREAD

**Issue by PivotalAnimal** [IdentityServer/IdentityServer4#171]
Could this be made public? Other _Extensions_ might be useful public as well. My specific use case is in implementing _ICorsPoicyService_. Another option might be to change the signature from 
`Task<bool> IsOriginAllowedAsync(string origin) to Task<bool> IsOriginAllowedAsync(string origin, Func<string, string> getOrigin)` removing the need for parsing origin url by calling code. 
A third option might be to move some of the _Extension_ code to IdentityModel.

**Comment by brockallen** [comment]
I think for now we're not going to do anything on this. As with many of Microsoft's internal helpers, for now just copy the code.
