### ISSUE TITLE
How is the relative part of RedirectUrl controlled

### ISSUE THREAD

**Issue by agrebenyuk** [IdentityServer/IdentityServer4#1711]
Hi guys ,

Having 2 issues at the moment:

1) This one actually a question - being not authenticated when I hit my resource (client) application by the https://myresource.com/somePageWhichRequiresAuthentication.aspx it certainly redirects me to ID server. The redirect URL in IDServer settings is https://myresource.com . Upon successful login I am redirected back to https://myresource.com/somePageWhichRequiresAuthentication.aspx and NOT the https://myresource.com/default.aspx  This is kind of what I need , but I don't understand how this happens as everywhere while in debug I can see no notion about somePageWhichRequiresAuthentication.aspx   including url to authorize endpoint.

2) When my resource app session is expired - I want to have the authentication round-trip to IDServer done in a popup window so that the original page is not reloaded. And I kind of do this by opening the same page in popup and I can login in popup. And than I am redirected back to original page in popup .All good, but not sure how to close that popup window upon successful login. I am trying to set value to request.State on the ID Server side and it comes to resource app first but then it gets lost after it is redirected to authorization endpoint and subsequent request to resource app contains 
OpenIdConnect.AuthenticationProperties=arZucu9g7cv39Twn9i5iYyWiShn9h...
in it's state param.

what would you suggest me to do to close that popup window after successful login?

**Comment by agrebenyuk** [comment]
In other words - I know how to communicate from ResourceApplication=> IdentityServer (via acr_values). I haven't just found the right way to pass my custom params from IdentityServer => Resource application upon successful login. And I presume when I find out I will be able to close my popup window on resource application side by getting needed parameter

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
