### ISSUE TITLE
Edit on GitHub link leads to 404

### ISSUE THREAD

**Issue by SIkebe** [IdentityServer/IdentityServer4#1714]
Hi! I realized any **Edit on GitHub** link in docs redirects to 404.
Any path changed or a sphinx issue like [this](https://github.com/sphinx-doc/sphinx/issues/2278)?

For now IdentityServer4 docs is using sphinx  1.0.
https://github.com/IdentityServer/IdentityServer4/blob/e130df9abd0b915cf70603442c6b32f9528d350a/docs/conf.py#L28

**Comment by leastprivilege** [comment]
I noticed that as well - the "origin" is not right in the generated link.

Do you have experience with Sphinx? If yes - you can do a PR on the conf.py.

**Comment by SIkebe** [comment]
@leastprivilege Unfortunately no.
I ran `make.bat html` locally but generated html shows "View page source" not "Edit on GitHub".

**Comment by leastprivilege** [comment]
seems to be a known issue

https://github.com/rtfd/readthedocs.org/issues/3203

**Comment by brockallen** [comment]
Update: There's a PR pending to fix this.

**Comment by leastprivilege** [comment]
it's fixed
