### ISSUE TITLE
poor docs

### ISSUE THREAD

**Issue by sergot** [IdentityServer/IdentityServer4#172]
The documentation is quite poor :( , is it going to change anytime soon?

The two *getting started* articles looked very promising, so I wonder if there's anything more, any tutorial how to make IS4 working step by step?

Thanks in advance for any response. :)

**Comment by PivotalAnimal** [comment]
Much of understanding IS4 is understanding the RFCs of which there are quite a few. Here is another good resource: [https://identityserver4.readthedocs.io/en/dev/#](https://identityserver4.readthedocs.io/en/dev/#)

**Comment by leastprivilege** [comment]
@sergot I am really sorry that we cannot work 24/7 to provide you the optimal experience. You may have figured out that all of the work is done by 2 people in their spare time.

If you want to speed up coding and/or docs - you or your company are welcome to fund us.

**Comment by sergot** [comment]
@PivotalAnimal @leastprivilege thank you very much for your answers.

@PivotalAnimal I read this doc, also, I should read the RFCs then.

@leastprivilege I'm not complaining at all. I would be happy to help, I must understand the whole thing first, that's why I'm asking about documentation and stuff.

Thanks for the replies. Have fun
