### ISSUE TITLE
Question: Refreshing a reference token

### ISSUE THREAD

**Issue by ruskindantra** [IdentityServer/IdentityServer4#1720]
I have successfully been able to create a reference token although as mentioned on the Gitter channel I can't seem to set the "SubjectId" of it, I want to know if:

1. How do I set the subjectid?
1. Is the subjectid absolutely necessary?
    1. When I use the `IPersistedGrantStore` it requires a subject id and so I thought it should be necessary
1. Now that I have a reference token, it expires within the initial timeframe, can I refresh/reset that time to make it last longer? Can I use the `IPersistedGrantStore`/`IPersistedGrantService`?

**Comment by brockallen** [comment]
If a user is using the client, your tokens should have `sub` (reference tokens or otherwise).

**Comment by ruskindantra** [comment]
Thanks for the comment @brockallen although I am used client credentials flow and there is no user. I have issued a reference token and using EF to store it in the database. Upon inspecting the database there is no SubjectId populated, how can I populate that?

**Comment by brockallen** [comment]
You need a human to use the client and authenticate :)

**Comment by ruskindantra** [comment]
@brockallen my authentication is simply used for API->API communication, so no human involved, are you implying there is no `subjectid` I can use in that scenario?

**Comment by brockallen** [comment]
Yes.

**Comment by ruskindantra** [comment]
Okay, thank you and does that automatically mean that therefore you cannot *refresh* a reference token?

**Comment by brockallen** [comment]
You don't need refresh for client credentials workflows -- you have the original client id and secret.

**Comment by ruskindantra** [comment]
For workflows where a 3rd party who is authorised to use your API has a reference token, this reference token will expire, when this expires, I prefer to refresh the token on the server end rather than revoke it and issue a new token.  Sounds like a fairly common scenario so was just wondering what the best way to accomplish it

**Comment by brockallen** [comment]
Why are you using a reference token? Do you need revocability or are you going for obfuscation?

**Comment by ruskindantra** [comment]
Because it's recommended it the token is leaving the confines of an environment you are in control with then a reference token is preferred rather than a JWT. And yes, I need to revoke it if required or lost.

**Comment by brockallen** [comment]
Just keep in mind you're using client credentials flow. If for some reason the client needs to be deactivated you need to disable the client itself, and not just the token that was previously issued to it.

As for "because it's recommended"... well, yes, that's a good starting point but you always have to understand why you're following any advice and think if it's really appropriate for your scenario. That recommendation is more typical for scenarios where a user is involved.

**Comment by ruskindantra** [comment]
Agreed @brockallen and yes, we'll be deactivating the client as well if the 3rd party integration is turned off so I am simply covering all my bases..so back to the question, what's the recommended approach to refresh a reference token? If any...

**Comment by brockallen** [comment]
I already told you :)

> You don't need refresh for client credentials workflows -- you have the original client id and secret.

This means you use the token until it's expired, then you use the client id and secret to get a new one. That's how client credentials flow works.

**Comment by ruskindantra** [comment]
Righto! Thank you, good to understand the details.  I was just considering if from a 3rd party perspective where they might place this token in their authorisation headers and when it expires they will have to redo it rather than us simply "extending the expiry".  But I guess it all makes sense :)

**Comment by ruskindantra** [comment]
@brockallen just one more question around revoke/refresh, if am going with that feature, which service can I use to regenerate a new reference token on the server side?  For e.g. on the client side I can use `TokenClient` but on the server side is there a particular service you recommend?

**Comment by brockallen** [comment]
Yes, TokenClient from IdentityModel helps with accessing the token endpoint regardless of the grant type being used.
