### ISSUE TITLE
Question/Feature Request for select_account

### ISSUE THREAD

**Issue by jahead** [IdentityServer/IdentityServer4#1721]
Hey , 
I've been trying to implement a way for the you change the returned token based on acr_values without having to re-login. 

I need this because I need to give context to the roles of the identity. This isn't a full tenancy but a role based on a grouping within a single-tenancy. 

The solution I came up with is to use a `groupId` in `acr_values` and the `prompt=select_account`, if those two values are supplied, I'd check to see if the user is already authenticated and reissue the principle with the new groupId. (If they are apart of that group of course). Group modification is rare. 

The issue is that Idsvr strips the prompt from the url. This makes sense for login. So you don't have the issue of redirecting back all the time, but because idsvr redirect select_account and login back to the same page we have no distinction of whether the user is trying to force a login, or just change the select_account. 

I realise adding the prompt back would cause issues, but perhaps having the select_account route to a  different url would be an idea, that or pass extra perms to the login page so we can figure out if it's a forced login, select_account or both?

I also tried using the `GetProfileDataAsync` as a way to modify the claims being returned but idsvr does not supply the `acr_values` to it, and only supplies the information from the cookie/principle. Ideally I would want it there, as I can compare the principle with the acr_values at the authorize endpoint.  But I've noticed there has been some unwilling to change the `GetProfileDataAsync` interface in issues relating to it.

If there is anything I do with a PR or what not, I would be more then willing to help. 

For now I'm going to have to put extra information in the acr_values, which seems like a bit of a hack. And re-implementing the interfaces would be less then ideal because I want to leverage as much of upstream as I can.

**Comment by leastprivilege** [comment]
We will discuss this - but we are both very busy right now.

**Comment by jahead** [comment]
@leastprivilege awesome,. I solved it for now by using two acr_values and using a select_account prompt. 

Let me know if you need any help.

**Comment by brockallen** [comment]
We don't have plans for this anytime soon. If your company wants to sponsor the feature, then please contact us [directly](https://identityserver4.readthedocs.io/en/release/intro/support.html).

**Comment by jahead** [comment]
I don't think our small company will be able to sponsor this. But I'd like to give some of my time in helping this project, as I see it as an important package for the greater open source .net community. 

So if not this issue, is there anywhere else you would like work done?

**Comment by jahead** [comment]
Just bumping this, and seeing if it has been resolved yet?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jahead** [comment]
@leastprivilege I know you have limited resources, just confirming that this won't be done anytime soon?

**Comment by leastprivilege** [comment]
I added it to backlog. We don't have the time to do that anytime soon.
