### ISSUE TITLE
Add s_hash

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1722]
spec?

**Comment by leastprivilege** [comment]
https://openid.net/specs/openid-financial-api-part-2.html#introduction

**Comment by Tim391** [comment]
So we have temporarily 'solved' this by using the following code in our ProfileService:

`        private List<Claim> AddSHash(ProfileDataRequestContext context, List<Claim> claims)
        {
            var state = context.ValidatedRequest.Raw["state"];
            if (!string.IsNullOrEmpty(state))
            {
                claims.Add(new Claim("s_hash", HashAdditionalData(state)));
            }

            return claims;
        }

        protected virtual string HashAdditionalData(string tokenToHash)
        {
            using (var sha = SHA256.Create())
            {
                var hash = sha.ComputeHash(Encoding.ASCII.GetBytes(tokenToHash));

                var leftPart = new byte[16];
                Array.Copy(hash, leftPart, 16);

                return Base64Url.Encode(leftPart);
            }
        }`

Which is pretty much just a copy of what is being done in the DefaultTokenService to create the c_hash.

**Comment by leastprivilege** [comment]
Will be added to 3.0 - 

https://github.com/IdentityServer/IdentityServer4/pull/3511
