### ISSUE TITLE
Multiple domains SSO

### ISSUE THREAD

**Issue by fatbooy** [IdentityServer/IdentityServer4#1724]
Hi guys, 

I have question about how to setup IdentityServer to work on multiple domains. I have one web app domain www.abc.com for logging in and second domain with WebAPI at www.xyz.com. Could you recommend me some code samples or tutorials how to setup identity to login at www.abc.com and then send request to www.xyz.com/api/values and be automatically authenticated at th backgroud?

I will happy for any tips.

Thank you

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
