### ISSUE TITLE
Role claims returned by UserInfo endpoint are not in User.Claims

### ISSUE THREAD

**Issue by nicbavetta** [IdentityServer/IdentityServer4#1727]
Hello,

I have a persisted data store which maps roles to Windows users within my company's domain. These roles correspond to the access rights these users have within an MVC app. I am expecting that these roles will be available in User.Claims within the context of MVC pages so I can then evaluate whether the current user has access to the current page.

After much trial and error, I am beginning to think my understanding of how authentication/authorization _should_ work in my IdentityServer implementation is flawed. I will walk through my implementation and am requesting any feedback as to why this is not working as expected (please tell me if I am thinking about the approach incorrectly).

## **Identity Server Configurations**

**Identity Server.Startup.ConfigureServices**

![image](https://user-images.githubusercontent.com/8139425/32612920-1b44d8ee-c52f-11e7-9715-b6847878f6f7.png)

Here, I am adding IdentityServer, the developer signing cert, a custom user store implementation (see below), and resources/clients from a config (also below). Furthermore, since I am targeting Windows authentication, I have configured IIS options per [IdentityServer documentation](https://identityserver4.readthedocs.io/en/release/topics/windows.html).

**AddUserStore() and UserProfileService**

In the above chain, I am adding a custom user store and IProfileService implementation. Roles are retrieved from the user store and added to IssuedClaims on the ProfileDataRequestContext object.

![image](https://user-images.githubusercontent.com/8139425/32613211-e3ba7cf2-c52f-11e7-8d49-5ae0e1da1494.png)

![image](https://user-images.githubusercontent.com/8139425/32613237-f487aeb0-c52f-11e7-86a5-9001f1dd33e1.png)

**Resource configuration**

In my configuration file, I am defining the following resources and client. I am adding a resource that will contain user roles and permissions (RoleKey == "roles"). In this resource, I am adding a single claim type - JwtClaimTypes.Role ("role"). 

**I would expect that roles should be placed in User.Claims within the context of an MVC page. Is this correct?**

![image](https://user-images.githubusercontent.com/8139425/32613458-8fd6f6d2-c530-11e7-9ad5-2dd340253445.png)

![image](https://user-images.githubusercontent.com/8139425/32613415-7a1645c8-c530-11e7-9fa7-2e6f2063717f.png)

## **MVC Client Configuration**

As you can see below, I am adding the RoleKey ("roles") scope to options.Scope.  It is important to note that I am also setting GetClaimsFromUserEndpoint to 'true'.

![image](https://user-images.githubusercontent.com/8139425/32614758-93fe095a-c533-11e7-86d3-c41662fd8a62.png)

## Workflow

1. Start IdentityServer and MVC client. IdentyServer loads:

![image](https://user-images.githubusercontent.com/8139425/32614105-1d44b44a-c532-11e7-9e6c-7ea076dec692.png)

2. Click "Windows". Uncheck "Remember My Decision" and click "Yes, Allow".

![image](https://user-images.githubusercontent.com/8139425/32614187-55ffe58e-c532-11e7-8371-60b4cb45d31c.png)

3. Breakpoint hit on "OnTokenValidated". I can validate that claims exist in the context token, but the role claims do not. This **IS** expected as this token is the ID token and NOT the access token. Correct?

4. Breakpoint hit on "OnUserInformationReceived". Roles WERE retrieved from the UserInfo endpoint. This is good!

![image](https://user-images.githubusercontent.com/8139425/32614463-f16fb378-c532-11e7-9cbf-c8734869cefe.png)

5. MVC Client page loads (yes, it is marked with "Authorize")

![image](https://user-images.githubusercontent.com/8139425/32615110-7789b2dc-c534-11e7-8e59-6619d41acbdc.png)

Role claims are not there! Here is the code:

![image](https://user-images.githubusercontent.com/8139425/32614938-faebe952-c533-11e7-8655-ccbc61482510.png)

## What am I missing?

**Comment by brockallen** [comment]
You have too many questions in this issue, and this issue tracker is not meant to be a general purpose help forum. I don't quite know where to start, but perhaps you should watch this for more high level info on how all this is supposed to work: https://mva.microsoft.com/en-US/training-courses/introduction-to-identityserver-for-aspnet-core-17945

**Comment by nicbavetta** [comment]
@brockallen I have watched that. All of my questions are driving the primary question: Why are the roles not being injected into the User.Claims object?

**Comment by brockallen** [comment]
> @brockallen I have watched that. All of my questions are driving the primary question: Why are the roles not being injected into the User.Claims object?

Unfortunately I don't know and this is the wrong channel for those questions. Sorry. I'd suggest stackoverflow, or our commercial support offerings.

**Comment by Jenan** [comment]
Take a look here: https://github.com/aspnet/Security/issues/1449 - You probable need to map the claims yourself. (Role mapping: https://github.com/aspnet/Security/issues/1449#issuecomment-332767846)

**Comment by nicbavetta** [comment]
@Jenan 

Thanks so much. I am now able to access my role claims in User.Claims.

@brockallen / @leastprivilege - This recent [change](https://github.com/aspnet/Security/issues/1449#issuecomment-332359065) has caused this unexpected behavior in IdentityServer4. Perhaps this should be documented in the quick starts?

Anyway, I believe the change also leaves claims mapped with options.ClaimActions as unprotected. For example, consider the scenario I have just tested:

1. In IdentityServer configuration, remove the corresponding resource that corresponds to the claim now being mapped with options.ClaimActions. For me, this was removing an IdentityResource (see commented code):

```
public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                //new IdentityResource(RolesResourceName, "Your roles", new [] { JwtClaimTypes.Role }) <---- REMOVED
            };
        }
```

2.  Remove the corresponding scope from the client config (see commented 'RolesResourceName'):

return new List<Client>
            {
                // This client represents an internal client with access to the System API
                new Client
                {
                    ClientId = SystemApiName,

                    // no interactive user, use the clientid/secret for authentication
                    AllowedGrantTypes = GrantTypes.ClientCredentials,

                    // secret for authentication
                    ClientSecrets = { new Secret(IdentitySecret.Sha256()) },

                    // scopes that client has access to
                    AllowedScopes = { SystemApiName },
                },

```
                new Client
                {
                    ClientId = ModuleType.Administration.ToString(),
                    ClientName = "Administration Module Client",
                    AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,
                    ClientSecrets = { new Secret(IdentitySecret.Sha256()) },

                    // where to redirect to after login
                    RedirectUris = { "https://localhost:44310/signin-oidc" },

                    // where to redirect to after logout
                    PostLogoutRedirectUris = { "https://localhost:44310/signout-callback-oidc" },

                    AllowedScopes = new List<string>
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        SystemApiName,
                        //RolesResourceName <-------------------------- REMOVED
                    },

                    AllowOfflineAccess = true
                }
```

3. Remove the corresponding scope from the client's Startup configuration:

.AddOpenIdConnect("oidc", options =>
            {
                options.SignInScheme = "Cookies";

                options.Authority = IdentityConfiguration.AuthorityUrl;
                options.RequireHttpsMetadata = true;

                options.ClientId = ModuleType.Administration.ToString();
                options.ClientSecret = IdentityConfiguration.IdentitySecret;
                options.ResponseType = "code id_token";

                options.SaveTokens = true;
                options.GetClaimsFromUserInfoEndpoint = true;

                options.Scope.Add(IdentityConfiguration.SystemApiName);
                options.Scope.Add("offline_access");
                //options.Scope.Add(IdentityConfiguration.RolesResourceName); <------- REMOVED

                options.ClaimActions.Add(new JsonKeyArrayClaimAction(JwtClaimTypes.Role, JwtClaimTypes.Role, JwtClaimTypes.Role)); // <----- KEEP
            });

4. Complete login process

With these changes, the claims are still populated in User.Claims. They are no longer protected. Is this an issue?

**Comment by Jenan** [comment]
I've tested your scenario as you mentioned and I don't have a role claim in my user claims in MVC. It was returned only what I am able to get. It seems work fine.

**Comment by nicbavetta** [comment]
@jenan Are you able to share your implementation? On the consent screen, if I uncheck "Profile", even profile claims still appear in User.Claims. Perhaps it is a configuration issue on my end.

**Comment by Jenan** [comment]
@nicbavetta I have used the Quickstart 5 - here is repo: https://github.com/Jenan/IdentityServer4.ClaimActions

**Comment by brockallen** [comment]
Yea, I just commened on a similar issue here: https://github.com/IdentityServer/IdentityServer4/issues/1657#issuecomment-343610578

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by nicbavetta** [comment]
@brockallen Yes, we are all good. Closing now.

**Comment by Anexsoft** [comment]
Thx a lot, It's working for me :)

**Comment by ahedreville** [comment]
I had found IMO a better solution here [](https://github.com/aspnet/Security/issues/1383) using OnUserInformationReceived event

**Comment by jayeshdshah** [comment]
@ahedreville 
Perfect.. Short and sweet.. 

Thanks..

**Comment by sguryev** [comment]
`JsonKeyClaimAction` is in the Microsoft.AspNetCore.Authentication.OAuth v2.1.1 out pf the box
Usage: `options.ClaimActions.Add(new JsonKeyClaimAction(JwtClaimTypes.Role, null, JwtClaimTypes.Role));`

I just can't understand why they pass `"role"` value to the `valueType` parameter. Like here: https://github.com/aspnet/Security/issues/1449#issuecomment-332767846
I expected something like "String".

Actually I have dig to the sources and this value is used for the `Claim` object creation.
`/// <param name="valueType">The claim value type. If this parameter is null, then <see cref="F:System.Security.Claims.ClaimValueTypes.String"></see> is used.</param>`

So it should be rather `null` than `"role"`
And `"role"` value passed to the `valueType` parameter obviously leads to the following:
![image](https://user-images.githubusercontent.com/6978458/44301390-6eea5f00-a31e-11e8-8b6b-88ca947b3caf.png)

**Comment by VictorioBerra** [comment]
Thanks a lot for this guys `options.ClaimActions.Add(new JsonKeyClaimAction(JwtClaimTypes.Role, null, JwtClaimTypes.Role));` this is the simple solution i have been looking for.

If someone could link to some straight forward and simple documentation on what the ClaimActions are, why they are used, **when** they are using that would be awesome. There are so many events and theres no docs that I can find which show the lifecycle of each event and when these maps are used.

This is very confusing to new developers just trying to add some simple auth to their sites.
