### ISSUE TITLE
API always returns 401 when hosted in Azure

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer4#1737]
- [x ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

1. Take the HybridFlowAuthenticationWithApiAccess sample (or the EF sample) and deploy to Azure (this takes some URL tweaks in config to get it right, everything pointed to the right place)
2. Click on the "Secure" page, and it allows you to sign in
3. The page renders everything correctly (you are signed in, auth cookie present, etc)
4. Now click the link to make a call to the API
5. POOF, 401

Using all the latest bits as of this post (IdentityServer4.AccessTokenValidation 2.1.0, ASPNetCore.All (2.0.0)

### Relevant parts of the log file
```
Katana log simply shows that it rejected the request due to 401. Useless. 
```
Yes, I verified all the config settings are correct for this to function in the Azure enviro.  ApiName is correct, and entries in config match, Authority is the correct URL for Idsvr on Azure.  There really is not much to properly locking down an API, it is fantastically simple.  I'm not sure what is going wrong here.  The same project runs fine locally.

**Comment by dapug** [comment]
...and totally forgot that CORS is required even for server to server apps, not just JS clients.

**Comment by leastprivilege** [comment]
CORS only applies to JS clients.
