### ISSUE TITLE
Consider OAuth Mutual TLS spec

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1738]
https://tools.ietf.org/html/draft-ietf-oauth-mtls-04

**Comment by leastprivilege** [comment]
Needs client cert support - looking at @blowdart 

https://github.com/blowdart/idunno.Authentication/issues/11

**Comment by larsw** [comment]
This draft has recently been updated (https://datatracker.ietf.org/doc/draft-ietf-oauth-mtls/) to 0.11 and AFAIK is scheduled for RFC status (Proposed Standard).
Re. https://github.com/aspnet/Security/issues/1575 the client cert auth. dependency is on the ASP.NET Core 3.0 road map.

**Comment by jaanclaeys** [comment]
Are you looking into doing certificate-bound access tokens also, or are you considering only the client authentication?

**Comment by leastprivilege** [comment]
This shipped in 2.4
