### ISSUE TITLE
Branding of IS4

### ISSUE THREAD

**Issue by msclements2003** [IdentityServer/IdentityServer4#1741]
Good evening!  

We have several partners/applications that will be using IS4 in the future.  We are going to start out by routing them to IS4 login page and then route them back to application in question. One of our applications is multi-tenant. Can you provide some insight into how we might style/brand IS4 login UI based off Partner and/or Application?  This is a request from our product dept.  I have been attempting to use the Header in the REST call, but I'm not having much luck.

v/r

Sarah Clements

**Comment by TomCJones** [comment]
OpenID connect is designed so that you go to the client (application) which may already have a cookie and the to the IdP if cookie is not present. Does that work?
________________________________

**Comment by brockallen** [comment]
> Can you provide some insight into how we might style/brand IS4 login UI based off Partner and/or Application

While this is possible (as you have client id in the `AuthorizeRequest` available to you in the login page), I discourage it. You should change your thinking that users are logging into your company's authentication system, not a specific app's login system. You don't login to google calendar, you're logging into google... from which you can access your calendar, drive, videos, email, etc..

**Comment by msclements2003** [comment]
We don’t disagree technically, however our partners “customers” who are logging in do not know of our company. We are more of a third party to them. Some are afraid it would cause confusion. Each partner is able to brand their space accordingly based off vanity url. We would like to provide an option if there is one. It would have to be more granular than Client Id.

**Comment by TomCJones** [comment]
I agree with brock. But the client has complete control of the redirect url and can add any hints it want to send to the idp.

**Comment by leastprivilege** [comment]
> It would have to be more granular than Client Id.

You can send custom parameters to the authorize endpoint - and can access them in the account controller via the `IIdentityServerInteractionService`.

**Comment by brockallen** [comment]
Or also pass a tenant param in acr_values, as that sounds like it might match your scenario (if your partner is a tenant).
