### ISSUE TITLE
Tenant not being parsed from acr_values 

### ISSUE THREAD

**Issue by chispaK** [IdentityServer/IdentityServer4#1742]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

The tenant property is not being set on the AuthorizationRequest. see querystring below.

### Issue / Steps to reproduce the problem
{/connect/authorize/callback?client_id=spaClient&redirect_uri=https%3A%2F%2Flocalhost%3A44398%2Fnoauth%2Faccount%2Fauth-callback&response_type=id_token%20token&scope=openid%20profile%20administration&state=11a27d4fe33e47bead16a695abeec693&nonce=f9d14f9007134741a33b2caaea55558c&acr_values=tenant%3A%20localhost%3A44398}

The tenant propery is being set to empty string when i use the Task<AuthorizationRequest> GetAuthorizationContextAsync(string returnUrl) API on the IIdentityServerInteractionService.

I can see the value in the acr_values property.

Am i missing something here.

![acrvalues](https://user-images.githubusercontent.com/2429903/32708187-975bd332-c7f6-11e7-9462-b49881b41148.png)

```

**Comment by leastprivilege** [comment]
Is there a space after the colon?

**Comment by chispaK** [comment]
Yes there was a space after the colon. Removing the space resolved the issue. thank you.
