### ISSUE TITLE
Decrease log level for failed user login

### ISSUE THREAD

**Issue by RakhmatovR** [IdentityServer/IdentityServer4#1743]
### Issue
There was an [issue in Identity Server 3 ](https://github.com/IdentityServer/IdentityServer3/issues/3244) about log level in `TokenRequestValidator`. I have the same problem at Identity Server 4, and it would be nice to decrease log level about failed user login to **Warning** or lower. Or maybe someone can suggest how to do it from my side?

**Comment by leastprivilege** [comment]
Which exact message are we looking for?

**Comment by RakhmatovR** [comment]
@leastprivilege 
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/TokenRequestValidator.cs

420 line:
```
LogError("User authentication failed: {error}", errorDescription ?? resourceOwnerContext.Result.Error);
```

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/3d738e96263d3b2728bdde9474715d9c392b2875/src/IdentityServer4/Validation/TokenRequestValidator.cs#L413-L420

OK - we'll discuss this. @brockallen

**Comment by ssarj** [comment]
It would be neat to dial down some of the messages in the `TokenValidator` as well; I'd not have things like 'token expired' as errors.

Thanks!
