### ISSUE TITLE
use identityserver4 in php core

### ISSUE THREAD

**Issue by sinakhoshdel** [IdentityServer/IdentityServer4#1744]
Hi everyone,
I need to use latest news from fiba website and they provided an API which using identityserver4 as authorization system,
https://bbm-api.fiba.com/swagger
Our application is PHP and I tried to find something related to php and identityserver but I could not,
I would be grateful if help me how it is working with php and show me right way.I am really need to do this project asap

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
