### ISSUE TITLE
Allow flag to suppress idsvr.session cookie

### ISSUE THREAD

**Issue by AamirTamtec** [IdentityServer/IdentityServer4#1746]
@brockallen I want to remove idsvr.session on server side as i am unable to signout fron mvc application

**Comment by naveddeshmukh** [comment]
Session Cookie on Server Side?

Session Cookies are never stored on Server. They are always stored on client machine only.

**Comment by brockallen** [comment]
We emit that cookie as part of our support for the session management spec: https://openid.net/specs/openid-connect-session-1_0.html

Are you saying you would want a flag to disable it?

**Comment by AamirTamtec** [comment]
Yeah what if i want to clear that session..
I tried to edit idsvr.session value on client side but nothing changed

**Comment by brockallen** [comment]
Right, as if today that's something you won't be able to change. I'll leave this open as a feature request.

**Comment by brockallen** [comment]
It's possible that we rely upon the endpoint enabled/disabled to achieve this.

**Comment by AamirTamtec** [comment]
Great
Thankyou

**Comment by brockallen** [comment]
Done
