### ISSUE TITLE
UserInfo claims not available in access_token from cookie

### ISSUE THREAD

**Issue by nicbavetta** [IdentityServer/IdentityServer4#1750]
My understanding is that, when "GetClaimsFromUserInfoEndpoint" is enabled in the OpenIdConnect client configuration, any claims provided by an IProfileService implementation are added to the access_token, which is then stored in a cookie.

However, whenever I call HttpContext.GetTokenAsync("access_token"), the token only includes the claims that were presented in the access_token BEFORE receiving additional claims from the UserInfo endpoint via IProfileService implementation.

What confuses me is that the UserInfo claims **are** indeed accessible from the HttpContext.User.Claims object - just not in the access_token returned by HttpContext.GetTokenAsync("access_token").

I know GetTokenAsync retrieves the access_token from the cookie. Does IdentityServer4 store this cookie prior to any UserInfo endpoint calls?

**Comment by nicbavetta** [comment]
@brockallen Care to correct my misunderstanding?

**Comment by brockallen** [comment]
Well, we've answered this many times... poke around the archives.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
