### ISSUE TITLE
Including scope in Response

### ISSUE THREAD

**Issue by rukyoj** [IdentityServer/IdentityServer4#1751]
I make a request using **ResourceOwnerPassword** grant type. I get a response: 
```
{
    "access_token": "3ba6837b571c8f6a87af420f5d74155b0d50ffdf488d790c23944ed19b82c401",
    "expires_in": 86400,
    "token_type": "Bearer",
    "refresh_token": "3073a3058d385997cd558f15057ce0eec5cb3abe3b22259b69499d81c4197802"
}
```
How do I include **scope** in my response, so it looks like this ?
```
{
    "access_token": "3ba6837b571c8f6a87af420f5d74155b0d50ffdf488d790c23944ed19b82c401",
    "expires_in": 86400,
    "token_type": "Bearer",
    "refresh_token": "3073a3058d385997cd558f15057ce0eec5cb3abe3b22259b69499d81c4197802",
    "scope": "blah
}
```
Do I need to specify some additional properties in my _CllientStore_ or _ResourceOwnerPasswordValidator_ ?

**Comment by chrisdrobison** [comment]
It looks like you are using reference access tokens. I’m guessing you would
need to take that and call the introspection endpoint to get the
information you are looking for. Otherwise you could change the access
token type to JWT in the client settings and the scope with be included in
the token.

**Comment by brockallen** [comment]
Clients should not be parsing the token, nor should they use introspection (if that's what you're suggesting).

Scopes being returned in the response is more meant to allow a client know what the user consented to. In resource owner flow, there's no consent.

**Comment by leastprivilege** [comment]
You could add custom response fields by implementing `ICustomTokenRequestValidator`

**Comment by rukyoj** [comment]
Ah, yes. Implementing **ICustomTokenRequestValidator** helped
