### ISSUE TITLE
License copyright notice

### ISSUE THREAD

**Issue by ernonewman** [IdentityServer/IdentityServer4#1754]
I'm not sure how much of an issue this is but I just noticed that you have left in the boilerplate text for the copyright notice in a bunch of repositories.

The line in question is close to the bootom of the file and currently says:
**Copyright {yyyy} {name of copyright owner}**

This is in a few of the IdentityServer4 related repos, I haven't checked any of the 3 repos.

Nothing major just thought I would point it out.

**Comment by brockallen** [comment]
Do you have a link for as concrete example of what you mean?

**Comment by ernonewman** [comment]
Sure, here you go: [https://github.com/IdentityServer/IdentityServer4/blob/dev/LICENSE#L189](https://github.com/IdentityServer/IdentityServer4/blob/dev/LICENSE#L189)

Like I said, I don't know if it's big issue but I noticed it and thought I would mention it.

**Comment by brockallen** [comment]
Ah, ok, I see. Thanks!

**Comment by brockallen** [comment]
I've assigned legal council @leastprivilege (esquire) to the issue. Thanks again.

**Comment by ernonewman** [comment]
No probs, keep up the good work.

**Comment by leastprivilege** [comment]
Thanks!
