### ISSUE TITLE
Custom extension grant seems to work even if clientid / clientsecret are not included in POST data

### ISSUE THREAD

**Issue by osudude** [IdentityServer/IdentityServer4#1756]
Not sure if this is a IDS4 bug or just my misunderstanding of how custom extension grants work.  Wrote a custom grant extension and assigned the custom grant type to an identity server client instance.
Was able to call the custom grant validator via HTTP POST even though no clientid or client secret was included in the post data.  Is identity server supposed to enforce custom grant privileges by client or is that the custom grant validator's responsibility?

![ids4](https://user-images.githubusercontent.com/7307682/32865803-65f6c866-ca2a-11e7-92b8-a8697f92ea0d.PNG)

**Comment by naveddeshmukh** [comment]
Please share your logs and also if possible implementation of your custom grant extension.

**Comment by leastprivilege** [comment]
@osdude can't believe that. Will try to repro. Logs would be useful.

**Comment by osudude** [comment]
Here is the log file for running against my local workstation.  I will see if I can maybe reproduce the issue against the source code version of identity server (rather than nuget) to see why it works with no clientid.

[log-20171116.txt](https://github.com/IdentityServer/IdentityServer4/files/1480556/log-20171116.txt)

**Comment by brockallen** [comment]
If you can write an integration test to illustrate the problem (and send it as a PR), that'd be best. That way we can have it as part of our automated test suite.

**Comment by leastprivilege** [comment]
You seem to be sending the client credentials via basic authentication

2017-11-16 16:48:15.180 -06:00 [DBG] Start client validation
2017-11-16 16:48:15.184 -06:00 [DBG] Start parsing Basic Authentication secret
2017-11-16 16:48:15.184 -06:00 [DBG] Parser found secret: BasicAuthenticationSecretParser
2017-11-16 16:48:15.184 -06:00 [DBG] Secret id found: cid_uaa
2017-11-16 16:48:15.213 -06:00 [DBG] Secret validator success: HashedSharedSecretValidator
2017-11-16 16:48:15.213 -06:00 [DBG] Client validation success

**Comment by leastprivilege** [comment]
I guess we can close this.

**Comment by osudude** [comment]
That is strange. Not sure why the fiddler trace shows is showing no clientid or client secret.  

Serilog shows no client id as well:


```
public Task ValidateAsync(ExtensionGrantValidationContext context)
        {
            var accessToken = context.Request.Raw.Get("token");
            var clientid = context.Request.Raw.Get("client_id");

            _logger.LogDebug("UaaGrantValidator start. clientId = {clientId}, ipAddress = {ipAddress}", clientid, _ipResolver.GetAddress().ToString());
```

2017-11-16 16:48:16.469 -06:00 [DBG] UaaGrantValidator start. clientId = null, ipAddress = ::1

**Comment by leastprivilege** [comment]
Because they are not in the post body.

**Comment by osudude** [comment]
Oic, Think i was confused by the documentation :

```
POST /connect/token

grant_type=delegation&
scope=api2&
token=...&
client_id=api1.client
client_secret=secret
```

http://docs.identityserver.io/en/release/topics/extension_grants.html

**Comment by leastprivilege** [comment]
https://tools.ietf.org/html/rfc6749#section-2.3

**Comment by osudude** [comment]
Thanks for the rfc.  In reading does it show client_id in the body?

```
POST /token HTTP/1.1
     Host: server.example.com
     Content-Type: application/x-www-form-urlencoded

     grant_type=refresh_token&refresh_token=tGzv3JOkF0XG5Qx2TlKWIA
     &client_id=s6BhdRkqt3&client_secret=7Fjfp0ZBr1KtDRbnfVdmIw
```

**Comment by osudude** [comment]
Looks like the correct way to get the clientId in the request validator is  to pull from ExtensionGrantValidationContext.    I will change my code.

```
context.Request.Client.ClientId
```

thanks
