### ISSUE TITLE
Redirect from Registration Page

### ISSUE THREAD

**Issue by dapug** [IdentityServer/IdentityServer4#1757]
**Feature Request:**
Provided a way to go directly to the Registration page that will sign the user in and redirect to client.

**Scenario**:

- MVC client has Register | Login in nav menu
- User clicks "Register"
- User should go to Registration page

It's not good UX for user to go to the Login screen and then click "Register".   For Login, it is convenient (from the menu with unauthenticated user) to simply call `HttpContext.ChallengeAsync("name_of_oidc_scheme"); `, after which the user is automatically redirected to the MVC client after login - cool.  But for registration... what do we have to get similar behavior?

**Comment by TomCJones** [comment]
this question is about ui, not idsvr. The aspnetcore 2.0 code will do that out of the box.
you can look at my page if you want to see it  http://tomjones.us/Account/Register
you should close this issue

**Comment by naveddeshmukh** [comment]
Can't you just redirect the user to registration page on IdSvr from your application? 

>  Provided a way to go directly to the Registration page that will sign the user in and redirect to client.

IHMO, Registration of a user is not something IdentityServer4 handles, It is specific to your implementation. If you see this [method](https://github.com/IdentityServer/IdentityServer4.Samples/blob/c9b5b266997dc66ed4bf91f1950b28d690602f4c/Quickstarts/6_AspNetIdentity/src/IdentityServerWithAspNetIdentity/Controllers/AccountController.cs#L233), It does what you want and IdentityServer doesn't even care how it happens.

**Comment by dapug** [comment]
> "this question is about ui" 

How?  

It's completely a functionality issue.  Just as with login, if using oidc, specific instructions (redirects) allow the idsvr to know that to do with the request after a successful login.  This has nothing to do with UI.

> "Registration of a user is not something IdentityServer4 handles"

If not Idsvr, then who?  Every identity server I know handles registration, user sign-in, account management.  Take for example external login such as Google used in my MVC app.  You register at Google, not my MVC app, not at /Account/Register of my MVC, but of Google!  What am I missing?

Furthermore, one key goal is to make sure ONLY the Idsvr has access to the identity database.  If I manually tap into that database from my MVC client, then said client must ALSO have access to that database, which seems counterintuitive and has security implications.  Separation of concerns and domains, literally.  Identity should be handled in one place, and the MVC app is nothing more than a "dumb" client. The relationship between my IdSvr and MVC and Google and MVC app should be the same - not entangled.  

And lastly, even the samples (IdentityServer4.Samples), Idsvr handles registration, login, account management, quite obviously. Not the MVC client.

Please educate me if wrong on any of this.

**Comment by dapug** [comment]
I tried `/Account/Register?returnUrl=[my MVC client path] `as a link from my MVC client to the idsvr and after registration it took me to the root/index page of the identity server instead.  Definitely not the solution.

**Comment by naveddeshmukh** [comment]
>  Every identity server I know handles registration, user sign-in, account management. Take for example external login such as Google used in my MVC app. 

Yes, all those things happens but that's not something IdentityServer handles solely. A web application (mostly mvc) that contains IdentityServer at its core along with bunch of logic and UI to handle basic interaction with the IdentityServer (such as Login Page, Consent Page).

**Comment by brockallen** [comment]
> If not Idsvr, then who?

Your UI code would. Please check the docs on the workflow: http://docs.identityserver.io/en/release/topics/signin.html#login-workflow
