### ISSUE TITLE
sub claim missing when logging in with SignInManager

### ISSUE THREAD

**Issue by MovGP0** [IdentityServer/IdentityServer4#1758]
- [X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

After migrating to .NET Core 2, I get an `InvalidOperationException` with the message `sub claim is missing` when trying to login the user with an password recovery token and log in using `Microsoft.AspNetCore.Identity.SignInManager.SignInAsync(...)`. 

### Issue / Steps to reproduce the problem

Call to the following method: 
```csharp 
var user = await UserManager.FindByIdAsync(userId).ConfigureAwait(false);
var isVerified = await UserManager.VerifyChangePasswordTokenAsync(user, decodedToken).ConfigureAwait(false);
if (!isVerified)
{
    // ....
}

await SignInManager.SignInAsync(user, true)
``` 

### Relevant parts of the log file
**Logfile**
```
[11:49:31 Debug] IdentityServer4.Hosting.IdentityServerAuthenticationService
Augmenting SignInContext

[11:49:32 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request
System.InvalidOperationException: sub claim is missing
   at IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal)
   at IdentityServer4.Hosting.IdentityServerAuthenticationService.AugmentPrincipal(ClaimsPrincipal principal)
   at IdentityServer4.Hosting.IdentityServerAuthenticationService.<SignInAsync>d__7.MoveNext()
```

**Stacktrace** 
```
IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal)
IdentityServer4.Hosting.IdentityServerAuthenticationService.AugmentPrincipal(ClaimsPrincipal principal)
IdentityServer4.Hosting.IdentityServerAuthenticationService+<SignInAsync>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Identity.SignInManager+<SignInAsync>d__30.MoveNext()
```

**Comment by MovGP0** [comment]
The problem is apparently, that `IdentityModel.JwtClaimTypes.Subject` is requested, but the `ClaimsPrincipal` only provides the `System.IdentityModel.Claims.ClaimTypes.NameIdentifier` claim, which should be technically the same.

**Comment by brockallen** [comment]
Are you not using our ASP.NET Identity implementation's ClaimsPrincipalFactory, where we add the proper sub claim?

https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/UserClaimsFactory.cs#L34

Compare what your app to our ASP.NET Identity quickstart to see what's different.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by MovGP0** [comment]
Actually I do use the implementation from `Microsoft.AspNetCore.Identity`: 
```csharp
using Microsoft.AspNetCore.Identity;

public sealed class ClaimsPrincipalFactory : UserClaimsPrincipalFactory<Entities.User, Entities.Role>
{
    public ClaimsPrincipalFactory(UserManager<Entities.User> userManager, RoleManager<Entities.Role> roleManager, IOptions<IdentityOptions> optionsAccessor)
            : base(userManager, roleManager, optionsAccessor)
    {
    }
}

```
and in DI: 
```csharp
var identity = services.AddIdentity<User, Role>(options =>
{
    options.Password.RequiredLength = 12;
    options.User.RequireUniqueEmail = true;
    options.SignIn.RequireConfirmedEmail = true;
});

identity.AddClaimsPrincipalFactory<ClaimsPrincipalFactory>();
```

apparently the wrapper `IdentityServer4.AspNetIdentity.UserClaimsFactory<User>` is not called. Also, I'd like to use the Subject ID in the claims, rather than the UserID, but the code in the example calls 
```csharp
var sub = await _userManager.GetUserIdAsync(user);
identity.AddClaim(new Claim(JwtClaimTypes.Subject, sub));
```
so I might need to provide my own implementation.

**Comment by MovGP0** [comment]
Solution: overwrite the `ClaimsPrincipalFactory<TUser, TRole>.GenerateClaimsAsync(TUser user)` method to provide the additional claims: 
```csharp
protected override async Task<ClaimsIdentity> GenerateClaimsAsync(Entities.User user)
{
    var identity = await base.GenerateClaimsAsync(user).ConfigureAwait(false);

    if (!identity.HasClaim(x => x.Type == JwtClaimTypes.Subject))
    {
        var sub = user.SubjectId;
        identity.AddClaim(new Claim(JwtClaimTypes.Subject, sub));
    }
}
```

**Comment by DSpade-r** [comment]
I have the same problem. Appears when using EntityFramework in ASP.NET Core 2.1 + IdentityServer4

**Comment by innercitypressure** [comment]
Any luck DSpade?  I'm having the exact same issue, also .NET Core 2.1

**Comment by DSpade-r** [comment]
> @DSpade-r I was having the same exact issue and resolved it by adding:
> 
> `.AddAspNetIdentity<ApplicationUser>();`
> 
> to
> 
> `services.AddIdentityServer()`
> 
> in Startup.cs

Yes i forgot to add .AddAspNetIdentity<IdentityUser>(); Thanks.
