### ISSUE TITLE
Long running application

### ISSUE THREAD

**Issue by rolatilu** [IdentityServer/IdentityServer4#1760]
- I am working on a long running application. It could be up and running 4 days straight. 

This is my in memory client configuration for IdentityServer4:

                    Enabled=true,
                    RequireConsent = false,
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,
                    RequireClientSecret = false,
                    AccessTokenType = AccessTokenType.Reference,,                   
                    RedirectUris =[path],
                    PostLogoutRedirectUris =  [path],
                    AllowedCorsOrigins =[path]
                   AccessTokenLifetime = 600,
                   AllowOfflineAccess = true,
                   UpdateAccessTokenClaimsOnRefresh = true,

This is my oidc-client configuration used in a SPA js file:
    authority: [path],
    redirect_uri: "[path]/callback.html",
    post_logout_redirect_uri:  "/index.html",
    response_type: "id_token token",
    scope: "openid profile email roles",
    loadUserInfo: true,
    silent_redirect_uri: "[path]/silent.html",
    automaticSilentRenew: true,
    revokeAccessTokenOnSignout: true,
    filterProtocolClaims: false,
    accessTokenExpiringNotificationTime: 300

My silent.html code:
    Oidc.Log.logger = console;
    new Oidc.UserManager().signinSilentCallback();

For some reason access token is always expiring. What configuraiton am I missing? Why is access token not renewing continously?

**Comment by naveddeshmukh** [comment]
Look at the docs [here](https://identityserver4.readthedocs.io/en/release/topics/grant_types.html#implicit), It says  **features like refresh tokens are thus not allowed** for implicit flow.

Consider using Hybrid Flow.

**Comment by rolatilu** [comment]
I switched it to Hybrid now I get  unauthorized.  Is it because I am using oidc-client.js. This is the error: 
" [Error] Invalid grant type for client: implicit{"
I found this https://github.com/IdentityModel/oidc-client-js/issues/266. Does this mean I cannot use SPA and hybrid flow?

**Comment by naveddeshmukh** [comment]
It seems like you're still using implicit flow on your SPA client. Did you update your oidc-client config?

**Comment by rolatilu** [comment]
Can you provide the configuration name and value to set for this? I have not come across this option.

**Comment by naveddeshmukh** [comment]
` response_type: "code id_token",`

**Comment by naveddeshmukh** [comment]
@rolatilu I'm sorry, but it seems like you were correct. Hybrid flow is not supported by the oidc client library, but the silent renewal feature does what you require. It refreshes the access token. 
Perhaps @brockallen  or @leastprivilege  can suggest a suitable option.

**Comment by brockallen** [comment]
If you have a hybrid flow client, use refresh tokens to do renewal. This assumes your code is server side. If you instead are using JS and it needs renewal, then it needs to be its own client using implicit flow.

**Comment by rolatilu** [comment]
Yes. I am using JS but the renewal works for a while but then in an hour or more the access token expires. Been trying to figure it out for the past 3 months. This forum is my last resort before I look for an alternative.

**Comment by brockallen** [comment]
IMO, it sounds like you need to learn how the mechanics of the protocol and the web app are working. Otherwise, how do you know how to control it, and/or even feel comfortable in its security? 

In short, access tokens expire (after 1h by default). In a browser-based client, the cookie lifetime is your ticket to obtain new tokens. We have lots of videos and other resources to learn more on our docs. Please consult those for learning.

**Comment by rolatilu** [comment]
I have gone through your trainings, i.e pluralsight, vimeo, youtube, documents  etc. I started with the templates for Identityserver and that of oidc-client. Anyways, I was looking for you guys to point me in the right direction. Will figure it out on my own.

**Comment by brockallen** [comment]
If you require commercial support, then contact us: http://docs.identityserver.io/en/release/intro/support.html#refsupport
