### ISSUE TITLE
.net core 2.0 migration -> HTTP Error 400. The size of the request headers is too long.

### ISSUE THREAD

**Issue by lvanderbijl** [IdentityServer/IdentityServer4#1764]
I'm migrating from a .net core 1.x working implementation to .net core 2.0.

I've successfully migrate all the libraries and namespaces correctly and am able to run the identity server and authenticate against local users.

We use openidconnect to authenticate external users against an azure active directory. When we log in, we get a Bad Request - Request Too Long error.

This occurs if I set the connect option: SaveTokens = true. If I set the option to false, the code runs, but I don't have immediate access to the tokens and the user doesn't not seem to be signed in despite using: 

`HttpContext.SignInAsync(user.UserName, user.UserName, provider, props, additionalClaims.ToArray())`

I have tried all the previous version (.net core 1.x) suggestions:
1. Add a cachedpropertiesdataformat (https://github.com/mclark1129/IdentityServer4.Samples/blob/master/AzureAd_CustomStateDataFormat/src/QuickstartIdentityServer/Startup.cs)
2. add max request length to webconfig/system.web

All to no avail. Has anyone else come across this? Has anyone got a work around?

**Comment by brockallen** [comment]
It's possible that cookies are getting too big. Consider adding this:

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Host/Startup.cs#L74

Which caches the cookies server-side, but you will need to setup the distributed cache.

We don't have docs on this now, but tracking here: https://github.com/IdentityServer/IdentityServer4/issues/1765

**Comment by lvanderbijl** [comment]
I've added this, but I'm still getting the error.

When I looked at the logs, I could see there was an error suggesting the access token wasn't supplied from azure ad. I updated the ResponseType in open id connect to  return both code and id_token. This cleared the error but has made the cookie even larger - and I still get the error.

The cookie is indeed very large, especially when including the code and id_token.

There are no other errors in the log. 

Any other suggestions?

**Comment by brockallen** [comment]
No sorry. And if this is an error produced by AzureAD, I'd suggest you take your question to them as they are the ones expected to support their software.

**Comment by lvanderbijl** [comment]
Ok. By removing the response type I was able to get everything working.

But that means I don't actually get the access tokens from azure ad. For my needs, that's fine.

If I try to include any tokens in the response, I get the error. I'll close this for now as I was able to get this working.

**Comment by ghanashyaml** [comment]
@Ivanderbijil, can you post this issue in Azure AD forums, so Microsoft can be informed and can check it out?

**Comment by javiermolinar** [comment]
@lvanderbijl any news about this issue? I have the same problem after migrating to 2.0

**Comment by lvanderbijl** [comment]
Unfortunately no - I haven't had time to follow this up properly with MS and have had to move on to other things. Sorry.

**Comment by uribahbut** [comment]
we have the same problem using the default asp.net identity with sql server .
