### ISSUE TITLE
WPF Active Directory Issue

### ISSUE THREAD

**Issue by alex9249** [IdentityServer/IdentityServer4#1767]
I am having an issue where if i use an MVC web application  to authenticate active directory uses it gives me a pop up window prompting the user to type in their windows username and password. However, if i simply use a basic web browser control in a WPF application to go to the identity server login page and hit the windows button, it will automatically login as the current user logged into windows. Is there any way to get the same user name and password popup that i get in a web application in a WPF application so that it does not automatically login you in?

**Comment by brockallen** [comment]
That's a browser issue. As such, this is not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
