### ISSUE TITLE
User Scope Claims are being Filtered

### ISSUE THREAD

**Issue by reeceengle** [IdentityServer/IdentityServer4#1768]
- [ x] I read and understood how to enable [logging]

I am attempting to add Scopes to the user object.  I have done this by adding user claims with the value scope and the corresponding Scope name, in this case it's my API.  I am able to add whatever else  I would like to the User Claims but it seems like anything I add with Scope as the ClaimType is 

When I look into the log file, I am encountering this line: 
```
<Claim types from profile service that were filtered: "scope">
```

Obviously I am doing something wrong but it seems like I'm missing something; do I need to create something similar to the IProfileService GetProfileDataAsync implementation?

**Comment by brockallen** [comment]
Why are you adding scopes to the user? What are you trying to achieve?

**Comment by reeceengle** [comment]
I was hoping to add a scope where it says [NEW_SCOPE_HERE], was hoping to have it grant access to my client scope.

```
{
  "nbf": 1510866006,
  "exp": 1510869606,
  "iss": "https://auth.pd.com",
  "aud": "https://auth.pd.com/resources",
  "client_id": "PD Android",
  "sub": "534cc4ee-f6db-4e28-bd4a-910cdb1c99a0",
  "auth_time": 1510866006,
  "idp": "auth.pd.com",
  "userType": "appUser",
  "pd_user_id": "1111111111",
  "test": "1",
  "scope": [
    "offline_access",
    [NEW_SCOPE_HERE]
  ],
  "amr": [
    "password"
  ]
}
```

**Comment by brockallen** [comment]
> I was hoping to add a scope where it says [NEW_SCOPE_HERE], was hoping to have it grant access to my client scope.

Yea, but why? I'm missing what you're trying to achieve.

**Comment by reeceengle** [comment]
I expect it to be part of my required_scopes on the client side... Am I misunderstanding this concept of scopes?

**Comment by brockallen** [comment]
> Am I misunderstanding this concept of scopes?

I suspect you are. Check the RFC.
