### ISSUE TITLE
Port client authentication using HTTPS certificates

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#177]

**Comment by leastprivilege** [comment]
Need to investigate front server (e.g. IIS) to Kestrel coordination first

**Comment by yilativ** [comment]
I can't seem to have a HTTPS client. The iOS app requires that the connection is done via SSL, but the endpoints get generated with HTTP. Has anyone gotten this to work an 2016 project (it's still on Kestrel, but running net4.6.2)

**Comment by eric-davis** [comment]
Is your ID server behind a reverse proxy or load balancer that is
terminating HTTPS? If so, you will have to make sure that your load
balancer is sending the X-Forwarded-Proto header and include some sort of
middleware in your IdentityServer pipeline that will allow the processing
of that header - I used MIcrosoft.AspNetCore.HttpOverrides. Then your
discovery doc should list HTTPS endpoints even if the request from the
proxy to the server is via HTTP.

**Comment by leastprivilege** [comment]
waiting for https://github.com/blowdart/idunno.Authentication/issues/11

**Comment by leastprivilege** [comment]
move to https://github.com/IdentityServer/IdentityServer4/issues/177
