### ISSUE TITLE
Signing Key Rollover

### ISSUE THREAD

**Issue by rexdefuror** [IdentityServer/IdentityServer4#1770]
Hey everyone,

First of, I have to say that you did a most amazing job of IDS4. It's a great tool!

The trouble I'm having at the moment is with my implementation of rolling certificates.
I've implemented 2 stores `SigningCredentialStore` and `ValidationKeysStore`. There I'm grabing the latest generated self signed certificate from a database where i store them.

```
public async Task<SigningCredentials> GetSigningCredentialsAsync()
{
    var certificate = new X509Certificate2(await _certificateStore.GetSigningCertificate());

    if (certificate == null) throw new ArgumentNullException(nameof(certificate));

    if (!certificate.HasPrivateKey)
    {
        throw new InvalidOperationException("X509 certificate does not have a private key.");
    }

    var credential = new SigningCredentials(new X509SecurityKey(certificate), "SHA256WithRSA");
    return await Task.FromResult(credential);
}
```

This is how I implemented the method in `SigningCredentialStore`.

### My issue
I can't seem to find any related info on how to make IDS4 retake the newly generated certificate for signing. Can you please just point me in a direction where can I find in code what determines how those Signing Certificates are resigned?

### Error I get

```
ArgumentException: IDX10634: Unable to create the SignatureProvider.
Algorithm: 'SHA256WithRSA', SecurityKey: 'Microsoft.IdentityModel.Tokens.X509SecurityKey'
is not supported.
Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, string algorithm, bool willCreateSignatures)
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
