### ISSUE TITLE
Is User.Identity.Name supposed to be null? 

### ISSUE THREAD

**Issue by tbasallo** [IdentityServer/IdentityServer4#1773]
I'm not sure if I missed this somewhere, and it's not a breaking issue, but I'm unsure if this is by design or something I didn't do.

I'm logged in, I have identities and claims and everything works great. I am just wondering, is this null by design? Should one not use it? Is it a deprecated property that we do not want to populate? Or is it anti-claims?

I reviewed the samples and documents and it _seems_ like it's by design....

**Comment by TomCJones** [comment]
the required claim in OpenID Connect is sub (subject ID). Everything else about the user is just an attribute.

**Comment by brockallen** [comment]
Perhaps relevant (but for name claims type, not role claim type): https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by brockallen** [comment]
All set on this issue -- can we close?
All set on this issue -- can we close?

**Comment by tbasallo** [comment]
Yes, that was a good reference.
