### ISSUE TITLE
IdentityServer4 - The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/user.read email is not valid

### ISSUE THREAD

**Issue by Mtaraby** [IdentityServer/IdentityServer4#1774]
I am trying to use Microsoft Account as an external login in IdentityServer4 , I created a new app under Microsoft Application portal and configured it as the following : 

 1. I added new web Platfrom  
 2. under Delegated Permissions I added the following permissions  
 * User.Read
 * email 
 * openId 
 * Profile

and here is the code that I am using in IdentityServer4 to access Microsoft Account with adding email as a scope : 

    services.AddAuthentication()
        .AddMicrosoftAccount("MicrosoftAccount", options =>
        {
            options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;

            options.ClientId = "ClientId";
            options.ClientSecret = "ClientSecret";
            options.Scope.Add("email");
            
    });

but when trying yo access Microsoft Account I am getting the following error 

***The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/user.read email is not valid***

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
