### ISSUE TITLE
Single sign out with hybrid flow

### ISSUE THREAD

**Issue by zonef** [IdentityServer/IdentityServer4#1775]
I'm trying to implement single sign out with hybrid flow, however can't figure out how to use sid which is passed via frontchannellogouturl

I have 2 Clients(Client A and Client B) with single sign on in my Identity Server.
In login callback i got id_token, code, reference_token, and session_state.
Now i want to logout Client B when ClientA is logged out.
I configured frontchannellogouturl for both clients and IdentityServer via iframe calls the configured urls.
However it passes session id which i can't connect with reference_token or id_token and identify the user to logout.
What is the correct way to approach single sign out ?

**Comment by brockallen** [comment]
> I'm trying to implement single sign out with hybrid flow, however can't figure out how to use sid which is passed via frontchannellogouturl

The `sid` is a claim you get back in the id_token that should be managed as a claim in the session in your client app. If you're in ASP.NET Core 2, then the microsoft OIDC handler already does the right thing for you and handles the front channel signout and validated the `sid` proerly.

**Comment by Debasish1014** [comment]
How to do Single signout in identity server

**Comment by Debasish1014** [comment]
Single signout not working for me.If i signout from IdentityServer then my MVC client doesn't signout.I have used OWIN middle ware to authenticate my MVC application.

**Comment by brockallen** [comment]
The OWIN/Katana middleware does not support sign-out. You have to implement that endpoint manually.

**Comment by Debasish1014** [comment]
I have gone through sample apps but have not seen any implementation.Can you please send some example

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/MVC%20OWIN%20Client%20(Hybrid)/Controllers/HomeController.cs#L58

**Comment by Debasish1014** [comment]
Have used the above but it never gets called if i logout from identity server

**Comment by Debasish1014** [comment]
How can i logout automatically from MVC client if i logout from identity server.Is it possible

**Comment by parkinsona** [comment]
@Debasish1014 , did you ever get the logout to be called from IdentityServer? I am having a similar issue.

**Comment by DebasishSahoo14** [comment]
Hi @parkinsona can you explain in details about the issue

**Comment by parkinsona** [comment]
@Debasish1014, it turns out, this was working all along, just not in my local environment. I moved it to the integration environment (where everything is on a different hostname) and it worked. 

I think there is something strange happening in my local environment, because even when I would login, some of my relying parties would end up on a different session in identity server.
