### ISSUE TITLE
Custom TokenEndPoint, extending the base implementation (v1.5.2 to v2.x.x)

### ISSUE THREAD

**Issue by tjuatja** [IdentityServer/IdentityServer4#1781]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Hi All,

We have a requirement to perform external authentication (i.e. Windows among others) via Console application. We have this working on IdentityServer v1.5.2 (with .NET Core 1.1.) before by:

1. Injecting Custom grant Type
2. Injecting custom TokenEndPoint which encapsulate the base TokenEndPoint 
   - Which will fallback to challenge window scheme (to get the current windows user into the context) when it detects the custom grant type above

**First Issue**
This is how we hook up the custom endpoint [v1.5.2]:
`services.AddIdentityServer()`
**`.AddEndpoint<CustomTokenEndpoint>(EndpointName.Token)`**

However, since v2.x, the AddEndpoint signature has changed and we are not sure the equivalent code in IdentityServe4 v2.x to inject this behaviour. We have tried: 
                **`.AddEndpoint<CustomTokenEndpoint>("Token", new PathString("/connect/token"))`**
but, our custom implementation didn't get hit.

**Second Issue**
Sample CustomTokenEndpoint (v1.5.2) is as follows:

`public class CustomTokenEndpoint : IEndpoint`
`{`
`	private readonly TokenEndpoint mDefaultEndpoint;`
`	public CustomTokenEndpoint(TokenEndpoint defaultEndpoint)`
`	{`
`		mDefaultEndpoint = defaultEndpoint;`
`	}`
`	public async Task<IEndpointResult> ProcessAsync(HttpContext context)`
`	{`
`		StringValues value;`
`		if (NotCustomGrant())`
`		{`
`			return await mDefaultEndpoint.ProcessAsync(context);`
`		}`
`		if (!(context.User is WindowsPrincipal))`
`		{`
`			// Perform windows Challenge here...`
`		}`
`		return await mDefaultEndpoint.ProcessAsync(context);`
`	}`
`}`

The issue above is **TokenEndPoint** is now an internal class in v2.x (it was public on v 1.5.2).
Has anyone uses/encountered this and can provide some ideas on how to extend the existing **TokenEndPoint** implementation?

Cheers,

### Relevant parts of the log file

```
<log goes here>
```

**Comment by tjuatja** [comment]
**Updates**
[Issue 1]
Figured out that overriding the actual token endpoint is not needed, so we will introduce a custom endpoint, i.e. /connect/customtoken.

[Issue 2]
However, we still need a way to delegate the authentication back to the real TokenEndpoint 
which was made internal since 2.x.

Are there some kind of API to get to that real/base Token auth pipeline on our CustomTokenEndPoint implementation above?

**Comment by leastprivilege** [comment]
I don't understand why you need a custom endpoint for that..Why not challenge for Windows in the pipeline when the request comes in?

**Comment by tjuatja** [comment]
We are using this custom end point on back end client app (i.e. Console App), i.e.
`
                
                var tokenClient = new TokenClient("<mainUrl>/connect/customtoken", "clientId", httpMessageHandler)
                {
                    // codes omitted as it's not relevant to the issue
                };
                var tokenResponse = await tokenClient.RequestCustomGrantAsync("customGrantType", Scopes).ConfigureAwait(false);
`
Hence, the request comes in straight to our CustomTokenEndPoint Implementation above, which we challenge during that process depending on the grant type (in this case, it's the **customGrantType**).

Do you have an example/guideline on where we can intercept those request (and challenge) earlier before we need to reach the real TokenEndPoint?

Many thanks in advance!

**Comment by leastprivilege** [comment]
Write some middleware that checks for the custom URL - challenge and re-write to the original token endpoint...that's what I would do.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
