### ISSUE TITLE
Refresh Token does not increment Expiration

### ISSUE THREAD

**Issue by diomedtmc** [IdentityServer/IdentityServer4#1785]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
1.  Create an access and refresh token using grant_type=password.
2.  Refresh the token from #1 using grant_type = refresh_token
3.  Note the expiration on the resulting persisted grant is still the original values from #1.

Am I just missing something here?  Is this working as expected?  Should I be incrementing the values myself?  Do I need Sliding Expiration here?

`
                new Client()
                {
                    Enabled = true,
                    RequireConsent = false,
                    ClientId = "9f597b0b-ba64-41b8-be6e-aeb7d2e796fc",
                    AllowedScopes = new List<string>()
                    {
                        Dynamo.Constants.ApiResources.Router,
                        Dynamo.Constants.ApiResourceScopes.RouterFullAccess,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Email,
                        JwtClaimTypes.Role
                    },
                    IncludeJwtId = true,
                    AccessTokenType = AccessTokenType.Jwt,
                    RequireClientSecret = false,
                    AllowOfflineAccess = true,
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPasswordAndClientCredentials,
                    RefreshTokenUsage = TokenUsage.OneTimeOnly,
                    RefreshTokenExpiration = TokenExpiration.Absolute,
                    AllowAccessTokensViaBrowser = false,
                    UpdateAccessTokenClaimsOnRefresh = true,
                    AbsoluteRefreshTokenLifetime = shortTokens,
                    AccessTokenLifetime = shortTokens,
                    IdentityTokenLifetime = shortTokens,
                    AlwaysSendClientClaims = true,
                    AlwaysIncludeUserClaimsInIdToken = true,
                    ClientSecrets = new List<Secret>()
                    {
                        new Secret() {Value=""}
                    },
                    AllowedCorsOrigins = { "*" }
                },`

**Comment by brockallen** [comment]
Did you change the `RefreshTokenExpiration` on the `Client`?

**Comment by diomedtmc** [comment]
If I understand correctly, Absolute always expires at the first expiration specified?  And Sliding moves the expiration?

**Comment by diomedtmc** [comment]
What is the proper client setup to what I describe?  (Issue a token of say 16 minutes, then each refresh, get another 16 minutes)

**Comment by diomedtmc** [comment]
Got this working after tinkering with it for a bit, here is what worked for me:

`                  AllowOfflineAccess = true,
                    RefreshTokenUsage = TokenUsage.OneTimeOnly,
                    RefreshTokenExpiration = TokenExpiration.Sliding,
                    UpdateAccessTokenClaimsOnRefresh = true,
                    AccessTokenLifetime = Convert.ToInt32(TimeSpan.FromMinutes(16).TotalSeconds),
`

Thanks for the help!
