### ISSUE TITLE
Cannot get identity token from HttpContext.GetTokenAsync("id_token")

### ISSUE THREAD

**Issue by AamirTamtec** [IdentityServer/IdentityServer4#1789]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)
Identity token issued and logout working but not getting id_token through =>
await HttpContext.GetTokenAsync("id_token")

even tried changing => await HttpContext.GetTokenAsync("identity_token")

AllowedGrantTypes = GrantTypes.HybridAndClientCredentials
                    
### Relevant parts of the log file

 Identity token issued for  / ca43497e-5e3f-451a-8e9b-4f5b4dbc4bf6: eyJhbGciOiJSUzI1NiIsImtpZCI6IjMxMGFiZjI3ZTg4NTc5N2U1MThkYWZhNGQyMDliZWQ2IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MTEzNjQ2NjgsImV4cCI6MTUxMTM2NDk2OCwiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo1MDAwIiwiYXVkIjoiVHJpdGl1bU5nIiwibm9uY2UiOiI2MzY0Njk2MTM3MTIxNjA0NjAuTURGaFpEbG1OamN0WmpsalpTMDBOalZsTFRnMll6WXRPV0kwT1dKaU1UZzBNbUV5TlRZellqaGpOR1F0TTJZM015MDBORGs0TFdFNFlqSXRaV1JqT0dKa1pEWTFOalZqIiwiaWF0IjoxNTExMzY0NjY3LCJjX2hhc2giOiJ0YkF5VWhSSEItaVpuTUFSVWZtRmlnIiwic2lkIjoiOThmMTlhNTVjM2YyODA0OWFmYjVhYzljMzdkMWJmNmUiLCJzdWIiOiJjYTQzNDk3ZS01ZTNmLTQ1MWEtOGU5Yi00ZjViNGRiYzRiZjYiLCJhdXRoX3RpbWUiOjE1MTEzNjQ2NjcsImlkcCI6ImxvY2FsIiwibmFtZSI6ImFtaXIubWFuc29vcmlAdGFtdGVjaC5vcmciLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IjYxNjE2NTBhLTk4N2EtNDlhYS1iYTJkLTY3MzQ5MzU0MzM2YyIsImFtciI6WyJwd2QiXX0.LISetgpUtGzy6ZulNEHLNNLvYtDk7SMNWdpTZdWfcxPEpeDVs0cyQ62IaL2aoeKYLdwU-Sxv17f2qjeJWZ397-YV72zigeY-Z1mLKQvHvYahD_V5qd5oaDmyv8c-n6NZQ4SaCb59DNCorGeCYbdoIvQUrMS7OPSfK5JMpP5622MUsrOBQtbifqU_VZwep2JDlfWpRPV7uKtlLfforVFGjsxgkZAucUQD3_BUBvMED7pbjyorDDZWQ9v8a5IfrIAI8lySsWHGAApMSpWIV9OSJTFF_Ebe2C9Wdb7ecH0UH0l_u9f9180Lx6nTNhC207jFheK9neUWeQUcKKBqp5-QoA

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
