### ISSUE TITLE
Factor out InMemory implementation

### ISSUE THREAD

**Issue by michael-x** [IdentityServer/IdentityServer4#179]
As it's main purpose is testing and there is probably not much point in carrying it all the way into a production system, would it make sense to move all the InMemory stuff into a separate NuGet package (Something like IdentityServer4.InMemory)? It would probably also help in understanding a little better the borders between core stuff (things that you would almost never want to customize), the default service implementations (things that you may or may not want to use out of the box) and the 'example' storage layer (the things for which you almost always would want to use some storage implementation or write your own code).

**Comment by leastprivilege** [comment]
we are indeed thinking about a split. It it will happen, it will be in the RC1 timeframe.

**Comment by leastprivilege** [comment]
Not quite factored out to a different assembly - but they are now under the "Quickstart" namespace and are better isolated.
