### ISSUE TITLE
The docs site should use independent scrolling for the nav pane and the content area

### ISSUE THREAD

**Issue by jolleekin** [IdentityServer/IdentityServer4#1793]
### Issue / Steps to reproduce the problem
1. Visit http://docs.identityserver.io/en/release/
2. Scroll the content area
### Expect
The nav pane should not scroll.
### Actual
The nav pane is scrolled.

**Comment by leastprivilege** [comment]
If you know how to "fix" this - let us know...

**Comment by jolleekin** [comment]
Do you mean it's not an issue or something out of control?

**Comment by brockallen** [comment]
No, he means we use "readthedocs" and we don't have that much control over their UI. Unless you know how to tweak their code to fix it.

**Comment by jolleekin** [comment]
It's possible to [add custom CSS or JS](http://docs.readthedocs.io/en/latest/guides/adding-custom-css.html). Anyway, I think I should move this issue to Read the Docs's repo.

**Comment by Mardoxx** [comment]
It may be on purpose? This way you can scroll anywhere on the page to move the navbar.. I think I might be "feature not a bug"ing this though...

**Comment by jolleekin** [comment]
@Mardoxx As a user, what do you think? To me, it's a bug. The nav pane tells me what article I'm reading and what previous/next articles are. With independent scrolling, I can easily jump to related articles without having to scroll everything. For example, while reading **Token Endpoint**, I may want to jump to **Authorize Endpoint** or **End Session Endpoint**.

**Comment by leastprivilege** [comment]
tbh - I don't care. We already agreed that this a more appropriate discussion for the RTD repo.
