### ISSUE TITLE
Question: TokenRequestValidationLog

### ISSUE THREAD

**Issue by neilwashere** [IdentityServer/IdentityServer4#1794]
The TokenRequestValidator uses a TokenRequestValidationLog directly to control the serialization of the log messages.

I'm interested in overriding this mechanism in order to supply an additional list of fields to be redacted before serialization.

So my question is, before I get into the nitty gritty, is there a way I can achieve using a custom list of field names to be redacted for logging within the the TokenRequestValidator/TokenRequestValidationLog?

On my first pass through the code it doesn't look like this is immediately supported. I'm guessing I'll need to recreate the TokenRequestValidator and pull in the supporting players where necessary and of course drop in my Log scrubber and register it via the dependency injection hooks. That seems like it might be a maintenance issue in the waiting when all I really want is to supply some field names to redact.

Of course a cleaner solution would be a light refactor to supply some interface for field names to be redacted. I'm happy to do that if this is something that would be useful elsewhere. I admit our use cases may not be very typical so maybe there is a likelihood such a feature would be ignored.

Or maybe there is another way?

Cheers,
Neil

**Comment by brockallen** [comment]
Not a bad idea as a feature request. We'll leave it open to discuss.

**Comment by leastprivilege** [comment]
This would require some cross-cutting re-work of all the logging - which is a good idea, but I don't see that happening very soon.

Would hooking into the ASP.NET Core logging system directly be a much more universal solution?

**Comment by neilwashere** [comment]
It would certainly introduce wider scope for customizations and disambiguate some of the logging concern. I can't speak to the level of effort that may incur. However, if the log entries already came in as well defined objects instead of serialized strings I would have been able to introduce a custom formatter already and leave you in peace :)

**Comment by leastprivilege** [comment]
Let's move that discussion to #1809

**Comment by leastprivilege** [comment]
Did you look into redacting at the logger factory level? If we would give every data a unique name - e.g. subjectId, clientId etc - then you could probably redact it that way.

**Comment by neilwashere** [comment]
I did look into it.
Manipulation is possible for objects of known types either as a culture specific formatter (decided this would be a hack approach as it violates the interface intention) or within a custom template if your logger library supports such a thing. We use Serilog that does support custom templates but the problem for us became the point at which serialization occurs (both as a structured k/v object and as a string within the message). As it stands we'd need to completely re-write our formatter.
I think a named value approach might work well in some situations but a well known, typed, object is a more sustainable solution avoiding naming collisions from other log events. We can certainly attack this at the logger level but right now it's just too much work for us. Deciding how things look vs what things (inside what things) should be displayed at all is a concept our current libraries do not handle and will take time to address correctly.
I then do have to wonder if this is a concern of the logger at all. Sure it's possible (with some work) but is it right? The concept of what is sensitive is pushed to the logger itself where it *feels* like it's something we want to keep close to IDS.
