### ISSUE TITLE
ASP.NET Identity 3 Support

### ISSUE THREAD

**Issue by ry8806** [IdentityServer/IdentityServer4#18]
I was wondering if there are any plans to implement AspNetIdentity for IdentityServer4?? For ASP.Net core 1.0?

**Comment by brockallen** [comment]
We will see. We're not yet sure what the `IUserService` will look like in IdSvr4.

In essence, though, there it won't be hard for you to do this yourself in IdSvr4 (and it wasn't all that hard in IdSvr3).

**Comment by ry8806** [comment]
yeh, that's cool

Once you do know how the interface might look, then I wouldn't mind getting involved and writing the AspNetIdentity "bridge"

**Comment by leastprivilege** [comment]
Cool. Thanks! I will leave this open then

**Comment by ry8806** [comment]
Once you think you've finalised the IUserService interface (I understand you've got lots of other things to do) - could you let me know and I will start having a look at it :)

**Comment by Cybrosys** [comment]
Also interrested in the IUserService interface, since I just found that it didn't exist in IdSvr4 yet :)

**Comment by Cybrosys** [comment]
Is there a way to work around the limitation of just using InMemoryUser? It is possible to read all the users from a DB into memory. The only problem with that solution is how to handle when user information changes in the DB.

Everywhere it's used it's injected as a List<InMemoryUser>, if it instead was injected as IList<InMemoryUser> then it would've been possible to create an implementation that read from an external source/DB.

**Comment by alzdrak** [comment]
@Cybrosys please see [#5](https://github.com/IdentityServer/IdentityServer4.Samples/issues/5#issuecomment-182176755)  and the stackoverflow example to implement IUserService. Please note that IUserService will be replaced with something similar in the next release of Identity Server 4.

**Comment by Cybrosys** [comment]
Thank you @alzdrak !

**Comment by Cybrosys** [comment]
@ry8806 Update1 has been released. The two interfaces you're interrested in are:
`IProfileService` and `IResourceOwnerPasswordValidator`.

**Comment by ry8806** [comment]
Thanks - do we have a separate Repo for this, like we do in [IdentitfyServer3](https://github.com/IdentityServer/IdentityServer3.EntityFramework) ??

**Comment by leastprivilege** [comment]
not before RC2

**Comment by Cybrosys** [comment]
@ry8806 I've written simple implementations (inspired by the ID3 implementation) of both for AspNetIdenity, but they're tied to *.Identity.EntityFramework, in case you're interested.

[AspNetIdentity ProfileService and ResourceOwnerPasswordValidator.zip](https://github.com/IdentityServer/IdentityServer4/files/172707/AspNetIdentity.ProfileService.and.ResourceOwnerPasswordValidator.zip)

**Comment by SimonTouchtech** [comment]
@Cybrosys FWIW, it is relatively simple to remove the dependency on Identity.EntityFramework by using UserManager instead of the model class directly to get its properties. This would mean e.g. replacing `user.Id` with `await _userManager.GetUserIdAsync(user)`

**Comment by totht91** [comment]
I think you need to prioritize this issue, because Identity Server is unuseable for many people without ASP.NET Identity support and samples.

**Comment by tibold** [comment]
I looked into integration IdentityServer4 with Asp.Net Core Identity.
Here is my idea:
https://github.com/tibold/IdentityServer4.Contrib.AspNetIdentity

I have copied some tests from the core project and made them work with AspNet Identity.
Also created a sample project showing how the code is used. It is based on the default Asp.Net Core Web application template in Visual Studio. I tried to implement it with the least amount of changes.

What do you think?

**Comment by totht91** [comment]
Next week I will investigate on your solution.

**Comment by brockallen** [comment]
I'll also take a look. Thx.

**Comment by PivotalAnimal** [comment]
I have made some progress on this. It is not as abstract as IS3 IdentityManager. For instance, Reflection is more limited in .NET Core. I created my solution however so that you can switch between the default InMemoryUser implementation and EF easily. SEE: https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore

**Comment by leastprivilege** [comment]
The SPA sample in the sample repo has asp.net id3 support.
