### ISSUE TITLE
Provide Serialization classes for tokens, claims etc.

### ISSUE THREAD

**Issue by PivotalAnimal** [IdentityServer/IdentityServer4#180]
The code for the project I work on originally came from something you guys created for IS3. It makes use of NewtonSoft.Json to convert Claim, ClaimPrincipal, Client and Scope to / from JSON. It would be nice to have extension methods in IS4 to serialize / deserialize common classes such as these that could be used by multiple implementations? I think it might also make sense to add the [serializable] attribute to the core Models (Client, Scope, etc.) That way a separate implementation could more easily convert to / from xml and what not.

**Comment by leastprivilege** [comment]
We are planning to move the serialization classes that we previously had in the EF repo to the main one...

**Comment by brockallen** [comment]
All done.
