### ISSUE TITLE
Unable to get ClientSecrets and ClientRedirectUris from database

### ISSUE THREAD

**Issue by itanev** [IdentityServer/IdentityServer4#1800]
Hi,

I have a code in a service that retrieves a client from db. The code for getting a client looks like this:

...
Client client = _configurationDbContext.Clients.FirstOrDefault(client => client.ClientId == clientId);
...

The client is here, but the ClientSecrets and ClientRedirectUris are not, but I see them in the db:

![redirecturis](https://user-images.githubusercontent.com/3280176/33214124-3bfce792-d133-11e7-9972-d014dfa96702.png)

![clientsecrets](https://user-images.githubusercontent.com/3280176/33214131-40929018-d133-11e7-88a7-2a216728dcd6.png)

It seems that they are mapped correctly, but for some reason are not mapped to the Client entity collections.

What am I missing?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
