### ISSUE TITLE
Single login for different browsers

### ISSUE THREAD

**Issue by masoud-bahrami** [IdentityServer/IdentityServer4#1801]
I use Identity Server 4 as the SSO Service.
But now i have a scenario:
When the user login and authenticated using Identity Server in any browsers, for example Google Chrome, then i don't want to have to log in again for the same application in the Fire Fox.
Actually I need one login for all browsers.
Is there any way

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
