### ISSUE TITLE
Question - SPA and Sliding Expiration?

### ISSUE THREAD

**Issue by pjmagee** [IdentityServer/IdentityServer4#1803]
I can see in the documentation that the approach used for SPA's/Javascript applications is the Implicit Flow. However I am having difficulty in understanding how to use the Oidc-Client so that it can re-issue a new access token if the user is active on the SPA. I'm not looking for a solution in this issue, just an answer of 'yes'/'no' that Identity Server can support sliding expiration. Then I can continue to look into how to implement this.

Example: a user has just logged in and is redirected to my SPA, the user is then idle for 50 minutes and should expire after an hour. 10 Minutes before the user session expires, the user performs an action. The user's current session should then again expire in 1 hour if they remain idle.

Is it possible to have a sliding expiration in a Javascript application that uses GrantTypes Implicit with the example above?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
