### ISSUE TITLE
Login not working with javascript disabled, form missing a submit button

### ISSUE THREAD

**Issue by krompaco** [IdentityServer/IdentityServer4#1806]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

`<form method='post' action='https://some-uri.com'>`
`<input type='hidden' name='id_token' value='eyJh...' />`
`<input type='hidden' name='scope' value='openid profile' />`
`<input type='hidden' name='state' value='ae0796bb7562423d9a6b58da40a5fd' />`
`<input type='hidden' name='session_state' value='XRGLXOY8I-VlEK8_NL9J0MhBdpTseWWfB2DvLmldeBo.644807dfe875645faa7c5e5bd1d5c8' />`
`</form><script>(function(){document.forms[0].submit();})();</script>`

Put a submit button in there and hide it using JS so that clients with disabled javascript can login.

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Endpoints/Results/AuthorizeResult.cs

IdentityServer4.Endpoints.Results.AuthorizeResult.FormPostHtml

**Comment by leastprivilege** [comment]
Added as a feature request. 

Another options for is to use authorization code flow instead. This does not use the form post.

**Comment by krompaco** [comment]
Thank you! I tried that and it's looking good.

For refererence and review:

Starting from Quickstarts\Combined_AspNetIdentity_and_EntityFrameworkStorage I allow GrantType authorization_code for the MVC Client in database/config.

In MVC app startup OpenIdConnectOptions change to:
`options.ResponseType = "code";`
`options.ResponseMode = "query";`

**Comment by krompaco** [comment]
For the original request `<input type="submit" />` would do. It would then pick up a default text from the browser such as "Submit Query" or equivalent user's browser language. But maybe it's desirable to have some translations for stuff like that to be able to show a more valid text and title for those HTML docs?

**Comment by leastprivilege** [comment]
tracked here #1880
