### ISSUE TITLE
Remove logging of token?

### ISSUE THREAD

**Issue by DanielDiligent** [IdentityServer/IdentityServer4#1808]
The [Authorize](https://github.com/IdentityServer/IdentityServer4/blob/ea1aaf89e13d23b842a10c3c149278ceeda67f58/src/IdentityServer4/Endpoints/AuthorizeEndpointBase.cs#L149) and [Token](https://github.com/IdentityServer/IdentityServer4/blob/ea1aaf89e13d23b842a10c3c149278ceeda67f58/src/IdentityServer4/Endpoints/TokenEndpoint.cs#L120) endpoints log the actual token that was issued.

This is a security concern for us. We have disabled IdentityServer trace logging as a work around, but this is not ideal.

Would it be possible to remove the logging of the token?

We also have a requirement to never log the subject, but realise that might be more unique to us.  Is there a possibility this could also be removed from logging?

**Comment by brockallen** [comment]
Someone else recently opened an issue asking for some callback to do log filtering, so we might be able to accommodate this sort of feature request.

**Comment by leastprivilege** [comment]
see https://github.com/IdentityServer/IdentityServer4/issues/1794

Maybe you should collaborate to find a solution at the LoggerFactory level.

**Comment by leastprivilege** [comment]
Let's move that discussion to #1809
