### ISSUE TITLE
Request authorization scope = openid, the response time to return the session_state parameter, may I ask what is the use of session_state?

### ISSUE THREAD

**Issue by aqa510415008** [IdentityServer/IdentityServer4#1810]
Request authorization scope = openid, the response time to return the session_state parameter, may I ask what is the use of session_state?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
