### ISSUE TITLE
AllowedGrantTypes summary still lists implicit as default

### ISSUE THREAD

**Issue by Jaternius** [IdentityServer/IdentityServer4#1812]
- [X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

Due to the change to allow configuration binding for ASP.NET Core 2.0, `Client.AllowedGrantTypes` is defaulting to an empty list. This is a breaking change that isn't documented in the release notes (as the configuration binding is an "enhancement" and the change was only discussed in that issue), and [the documentation for the property itself still calls implicit the default](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Models/Client.cs#L78).

### Relevant parts of the log file

n.a.

**Comment by leastprivilege** [comment]
PR please

**Comment by brockallen** [comment]
PR submitted

**Comment by brockallen** [comment]
merged
