### ISSUE TITLE
Extension grant http response code

### ISSUE THREAD

**Issue by stevehickey87** [IdentityServer/IdentityServer4#1819]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue
I am trying to implement an extension grant that will need to return a redirect (along with the access token and id cookie) as the response, however, GrantValidationResult does not seem to have access to more than the response body.

Is there a security reason that this is not in place? If not, is this a feature on the roadmap?

**Comment by brockallen** [comment]
Extension grants don't allow for doing things like setting the response to a redirect./
