### ISSUE TITLE
Sample JS client to test Front Channel Logout

### ISSUE THREAD

**Issue by nehaer** [IdentityServer/IdentityServer4#1820]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

Hello,
I'm looking for some samples that can test Front Channel Logout feature with Identity Server Demo: https://demo.identityserver.io
Can you please help?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
JS clients don't use front-channel logout. They use the JS notification mechanism.

Anyways - sample client can be found here:

https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients
