### ISSUE TITLE
Sample client app that uses Front Channel Logout mehanism

### ISSUE THREAD

**Issue by nehaer** [IdentityServer/IdentityServer4#1821]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Have gone thru the sample clients available for Identity Server4. Was specifically looking a code sample to use Front Channel logout mechanism for logging out from Client App. Any reference pls? I need to check how a client implementation should look like for logout_uri endpoint.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/MvcManual/Controllers/HomeController.cs#L40-L52

For more details read the spec please.
