### ISSUE TITLE
need updated claims in new access token getting thru refresh token

### ISSUE THREAD

**Issue by AliShd** [IdentityServer/IdentityServer4#1822]
Its a question:

I put some claims in the access token that comes from DB while login (e.g. `entity_id` and `role`). Now at some stage the `entity_id` claim gets changed and I need to get a new access token with the updated claims. I am doing this using the refresh token to get a new access token but it comes with the same old claims inside; may be because the class implementing `IResourceOwnerPasswordValidator` is not being called in case of refresh token. So how can I get the updated claims in access token? Because user has to logout and re-login otherwise to get the `entity_id` and `role` claims updated.

I know the other option is to make use of the `/userinfo` endpoint for claims but my question here is in this case how the `[Authorize(Roles = "Manager")]` attribute of ASP.NET Core will work and get to know about roles if they don't exist in the access token?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by AliShd** [comment]
@leastprivilege OK [here](https://stackoverflow.com/questions/47600074/need-updated-claims-in-new-access-token-getting-thru-refresh-token) I posted the same question on stackoverflow. Can you please have a look?
