### ISSUE TITLE
Client.Description property inconsistent between Models and Entities

### ISSUE THREAD

**Issue by sei-jmattson** [IdentityServer/IdentityServer4#1825]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Entities.Client has a Description property, but Models.Client does not.  So, the Description property doesn't get mapped using the ToEntity() and ToModel() extension methods.

Is Models.Client.Description omitted by design? Would you rather we ignore Entities.Client.Description and use the Client.Properties for that value?

### Relevant parts of the log file
n/a

**Comment by brockallen** [comment]
Ah yes, the description for humans and that's why we added it to the EF layer, but don't have a corresponding entry in the core config layer.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
