### ISSUE TITLE
External authentication cookie not saved in Identity.External

### ISSUE THREAD

**Issue by Silthus** [IdentityServer/IdentityServer4#1826]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue

AspCore.Identity uses the "Identity.External" scheme to retrieve the external login provider: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/SignInManager.cs#L557

However IdentityServer sets the external authentication cookie into the idsrv.external scheme, resulting in a null response.

![image](https://user-images.githubusercontent.com/755327/33516732-ff8c4dc0-d777-11e7-9c04-72db0a336669.png)

I did not find the part where IdentityServer sets the cookie into the idsrv.external namespace, or else I would have greated a pull request.

As a workaround I created a custom SignInManager that uses the IdentityServerConstants.ExternalScheme to retrieve the LoginInformation.

**Comment by brockallen** [comment]
If you're using ASP.NET Identity and its `SignInManager`, then you need to code your UI to use that (as opposed to our QuickStart UI which uses our external scheme). IOW, you need to make those consistent.

**Comment by Silthus** [comment]
What do you mean by that? I was using the Quickstart template and it uses
the SigninManager which does not work

**Comment by brockallen** [comment]
So then you see this behavior in the ASP.NET Identity quickstart?

**Comment by Silthus** [comment]
Yes, this is the behavior out of the box when using the Asp Identity, Ef, or combined quickstart.

**Comment by brockallen** [comment]
I just ran the ASP.NET Identity QS 6 in chrome and it worked fine.

**Comment by Silthus** [comment]
For me it does not work. I cloned the QS 6 and ran it. `var info = await _signInManager.GetExternalLoginInfoAsync();` is null.

![image](https://user-images.githubusercontent.com/755327/33519748-b3570c66-d7ad-11e7-9a44-f48217fcce90.png)

https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/6_AspNetIdentity/src/IdentityServerWithAspNetIdentity/Controllers/AccountController.cs#L327

**Comment by brockallen** [comment]
So I also just ran the other two you mention (QS 8 and the combined one) and they also work. 

It sounds environmental to me. I'd suggest debugging more into the external cookie and see which one you do have.

**Comment by Silthus** [comment]
You are right. When I open the page in incognito mode everything works. Seems to be some caching issue.

**Comment by max-buecker** [comment]
Ehm, so I ran into this issue as well, when setting the `options.SignInScheme` of the external authentication provider to `IdentityServerConstants.ExternalCookieScheme`. When left at default, it works fine, though I don't know about the pros and cons about which SignInScheme to use and how to pick the best one for the situation.

**Comment by saifalmaluk** [comment]
I agreed with max-buecker, it resolve my problem when `options.SignInScheme` as leaving default.

```
.AddOpenIdConnect("IS4", "OpenID Connect", options =>
             { 
                 **//**options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme; 
```
