### ISSUE TITLE
Matadata for Back-Channel Logout

### ISSUE THREAD

**Issue by nomoreload** [IdentityServer/IdentityServer4#1828]
I have a question not about Identity Server itself, but about OpenID Connect and its impementatoin. Especially about Back-Channel Logout.
Does back-channel logout that described in [specification](https://openid.net/specs/openid-connect-backchannel-1_0.html) begins from the front-channel logout request?
How I understand back-channel logout mechanics:
1) User clicks "Logout" button in a client application
2) Application performs front-channel request
3) User redirects to IdentityServer
4) Front-Channel logout performs
5) IdentityServer calls callback route that notifies client about user logout (that is back-channel logout)
6) If redirection uri is registered - user redirects back to specified uri.
Am I correct?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
