### ISSUE TITLE
Create integration tests for PKCE

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#183]
spanning authorize and token endpoints

**Comment by brockallen** [comment]
i ported the ones from idsv3 and pushed to dev. there are a few that have some issues we need to discuss.

**Comment by brockallen** [comment]
Perhaps we should discuss setting the default response_mode as soon as the response_type is determined. This will solve the chicken & egg problem we're seeing.

**Comment by brockallen** [comment]
Not the most elegant PR ever, but this encapsulates all the changes needed to make this work. The main things are:
- allow error_description into authorization responses
- move assignment of the default response_mode earlier (as soon as response_type is known)

https://github.com/IdentityServer/IdentityServer4/pull/207

**Comment by brockallen** [comment]
merged. 2 tests marked as skip pending updates to IdModel

**Comment by leastprivilege** [comment]
updated idm and tests
