### ISSUE TITLE
Embedded IdentityServer 4 with Aspnet Identity and resource owner

### ISSUE THREAD

**Issue by Dafriskymonkey** [IdentityServer/IdentityServer4#1830]
I am trying to use IdentityServer4 with resource owner flow + aspnet identity and embed the api in the same project, and its not working even when using the sample code.

You can see the code used in this SO post :

https://stackoverflow.com/questions/47638011/embedded-identityserver-4-with-aspnet-identity-and-resource-owner

**Comment by brockallen** [comment]
We have a sample close to that here: https://github.com/brockallen/IdentityServerAndApi

Having said that, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by Dafriskymonkey** [comment]
are we sure this combination works in identityserver ? IdentityServer + Api + AspNet Identity

**Comment by Dafriskymonkey** [comment]
indeed the issue was not related to identity server, the `AddIdentity` was the source of the problem.

Thank you @brockallen
