### ISSUE TITLE
Refresh token response does not contain custom fields from custom token request validator

### ISSUE THREAD

**Issue by rukyoj** [IdentityServer/IdentityServer4#1831]
I have an implementation of **ICustomTokenRequestValidator** in which I add additional data in the custom response. So, when I make  request for an access token (using _password_  grant), I'm able to get my custom data in the response. But when I use use the _refresh_token_ grant, I'm unable to get my custom response (even though the **ValidateAsync** method actually gets called. Is this a bug, or am I supposed to override something else?

**Comment by brockallen** [comment]
> I'm able to get my custom data in the response

What's an example of this custom data, and how in the custom token request validator are you setting this data to be included in the response?

**Comment by rukyoj** [comment]
```    
public class CustomTokenRequestValidator : ICustomTokenRequestValidator
{
        public Task ValidateAsync(CustomTokenRequestValidationContext context)
        {
            context.Result.CustomResponse = new Dictionary<string, object>
            {
                {"scope", "read" }
            };

            return Task.CompletedTask;
        }
}
```

**Comment by leastprivilege** [comment]
OK - I can repro the problem. Need to have a closer look.

**Comment by leastprivilege** [comment]
Thanks for reporting!
