### ISSUE TITLE
[Question] How can I add more custom endpoints to CorsPath

### ISSUE THREAD

**Issue by dudedev** [IdentityServer/IdentityServer4#1833]
Hi, 

I have hosted API and IdentityServer together. So, my IdentityServer offers few endpoints to manage users. I want to allow Cors for these endpoints as well. However, I do not understand how can I add more endpoints to CorsPath if they have placeholders like "/api/users/{userId} ".

Right now, I have written a custom policy provider and custom policy service and used Cors for the root endpoint i.e. /api. 

Is there a way that I can add my root path of api i.e. /api/ to CorsPath so that I do not have to write custom policy provider.

**Comment by brockallen** [comment]
Did the docs not explain it sufficiently? http://docs.identityserver.io/en/release/topics/cors.html#mixing-identityserver-s-cors-policy-with-asp-net-core-s-cors-policies

**Comment by dudedev** [comment]
Thank you @brockallen for the response and nice documentation. I have read the docs and after reading it I wrote my own CorsProvider. However, I wanted to confirm if I can add my custom endpoints  with placeholders to the CorsPath options, because by looking at the code (https://github.com/IdentityServer/IdentityServer4/blob/a28ac7ae6d86eb40d2865734fe85b06f0ab44f26/src/IdentityServer4/Hosting/CorsPolicyProvider.cs) to compare the paths, I think it is not possible.

If I could add endpoints to the CorsPath, then I need not write custom CorsProvider.

**Comment by brockallen** [comment]
So I don't think you needed to implement your own CorsProvider, unless you would have done that anyway outside of IdentityServer. Our internal CORS implementation, as you saw, only is triggered for specific paths, which are the ones internal to IdentityServer and only the ones where CORS should be allowed (based on your IdentityServer cors config). Again, all of that is really separate form your CORS policy that you'd want with normal ASP.NET Core.

**Comment by dudedev** [comment]
I could not use the ASP.NET Core CORS policy because allowed origin is not known at development time. I have a requirement to allow all clients. So, my CorsPolicyService is iterating over all clients and checking against AllowedCorsOrigins to allow a origin for the custom endpoint.

**Comment by brockallen** [comment]
Ok, that's fine. You just need to register yours prior to ours in ConfigureServices, and we will decorate it.

**Comment by dudedev** [comment]
Yes, I did that. Thanks to docs. It works as expected. 
I just wanted to ask if I could add to path with placeholders to CorsPaths. In that case, I did not need to write own provider. 

Thanks anyways for your responses.

**Comment by brockallen** [comment]
`CorsOptions.CorsPaths`: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/Options/CorsOptions.cs#L37
