### ISSUE TITLE
PublicOrigin should be used by UI code

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1834]
Any UI redirects don't take `PublicOrigin` into consideration. Perhaps we need to emulate the ForwardedHeadersMiddleware (https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNetCore.HttpOverrides/ForwardedHeadersMiddleware.cs) based on this setting?

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/issues/34

Original issue from @tessierp:

We are using the IdentityServer 4 behind a Load Balancer and in Docker and using Docker Flow Proxy to terminate the SSL. We followed the instructions we found here to solve the issues assosicated with this configuration :

https://leastprivilege.com/2017/10/09/new-in-identityserver4-v2-simplified-configuration-behind-load-balancers-or-reverse-proxies/comment-page-1/#comment-92277

Works perfectly except in one case. In the views that are graciously offered by your team, we have in the HomeController’s the following :

"Click here to manage your stored grants", where in the "HERE" in index.cshtm of the HomeController is generated with ~/grants. This causes a generation of the wrong URL, http://xxx.com/account/login?returnUrl=%2Fgrants, instead of https://xxx.com/account/login?returnUrl=%2Fgrants

I assume this is because in the configuration of Kestrel it knows it is set up for HTTP and thus generates the URL in http. Is there an option I can set where the IdentityServer overrides this and sets it to HTTPS?

**Comment by brockallen** [comment]
@tessierp

I don't see the full URL rendered into the HTML that you claim in your original issue. Can you confirm the rendered HTML actually contains the wrong hostname (or is it just your browser tooltip showing the host when you hover your mouse over it)?

**Comment by brockallen** [comment]
Also, we just pushed a 2.0.6-preview1 to NuGet with a potential fix. Have a look please.

**Comment by tessierp** [comment]
Hi Brock,

I removed the host address from the URL. It was generating the right hostname, the problem was that HTTP was used instead of HTTPS. We will be trying the preview soon and let you know if that fixes the issue.

**Comment by brockallen** [comment]
Let me know, ASAP, please. I'd like to get a patch out.

**Comment by tessierp** [comment]
Hi Brock, it worked for a local login but we ran into some issues with external logins using Google. We are still evaluating the problem, making sure it is not a config issue. Did you by any change try an external login with your fix and does it work?

**Comment by brockallen** [comment]
Keep me posted.

**Comment by brockallen** [comment]
I just tested, and yes google logins work.

**Comment by brockallen** [comment]
I'll close this now since it seems we've tested both side of it. I need to push the patch today.

**Comment by tessierp** [comment]
Hi Brock, we have tested this. Seems the problems we are having are swarm related (Docker). So all should be good. Thanks for your help.

**Comment by brockallen** [comment]
yep. 2.0.6 was released earlier today. thanks
