### ISSUE TITLE
3 tier architecture for AuthServer (more of a question)

### ISSUE THREAD

**Issue by Ravivishnubhotla** [IdentityServer/IdentityServer4#1836]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
Using the Quick Start samples I have setup Identity Server 4 with Entity Framework and ASP.NET Identity. However on deploying on QA environment, the QA environment is three tier architecture (Web/APP/DB). Web does not have access to DB only thru APP. Now Login page is setup in AuthServer. How will this work in the IdentityServer4 since the DB access needs to setup directly from web?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
