### ISSUE TITLE
Authentication issue with OIDC

### ISSUE THREAD

**Issue by jayslife** [IdentityServer/IdentityServer4#1837]
I recently upgraded a series of websites to .net core 2.0 from 1.1.2, which everything was working great. I have painstakingly had to fix a ton of issues due to all of the changes made to Identity in this version. I am currently stuck on a issue that is kind of perplexing. 

I have two websites which separate concerns (UI, Services).  The UI project is split into two site (backend, front end). My services implement Identity service and use migrations for everything.

What is intended is that a user be able to navigate to either UI site and be redirected to the services site for Authentication. Once authenticated the user will be redirect back to the site that they originated from, thus being authenticated. (This is working as intended). The subsequent calls use a HttpClient to make requests to the services to interact with service endpoints. This is authenticated by placing the Token in the autherization of the HTTPClient.

```
var httpContext = httpContextAccessor.HttpContext;
if (httpContext.IsNotNull() && httpContext.User.IsNotNull() && httpContext.User.Identity.IsNotNull() && httpContext.User.Identity.IsAuthenticated)
            {
                var oidcToken = httpContext.GetTokenAsync("access_token").Result;
                
                if (!string.IsNullOrEmpty(oidcToken))
                {
                    DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", oidcToken);
                }
            }
            _baseUrl = appSettings.Value.BaseUrl;
```

services startup:
![image](https://user-images.githubusercontent.com/9482630/33630017-e94495a0-d9d3-11e7-8c60-cafd0646128d.png)

I am able to Authenticate and process Get Requests; however POST request return a 401 unauthorized back to my HttpClient. Please let me know if i can provide additional code snipits for help troubleshooting this issue.

**Comment by leastprivilege** [comment]
You'd need logs from the API that returns 401.

**Comment by jayslife** [comment]
dbug:   IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[9]
AuthenticationScheme: Bearer was not authenticated.
dbug:   IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[9]
AuthenticationScheme: Bearer was not authenticated.
info:   Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
Authorization failed for user: (null).
info:   Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
Authorization failed for user: (null).
info:   Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
Authorization failed for the request at filter   'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info:   Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[3]
Authorization failed for the request at filter   'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info:   Microsoft.AspNetCore.Mvc.ChallengeResult[1]
Executing ChallengeResult with authentication schemes (Bearer,   Identity.Application).
info:   Microsoft.AspNetCore.Mvc.ChallengeResult[1]
Executing ChallengeResult with authentication schemes (Bearer,   Identity.Application).
info:   IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[12]
AuthenticationScheme: Bearer was challenged.
info:   IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler[12]
AuthenticationScheme: Bearer was challenged.
info:   Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
AuthenticationScheme: Identity.Application was challenged.
info:   Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[12]
AuthenticationScheme: Identity.Application was challenged.
info:   Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Executed action   Aura.Core.Services.Controllers.AuraOrderEntry.OrderController.Count   (Aura.Core.Services) in 348.4091ms
info:   Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Executed action   Aura.Core.Services.Controllers.AuraOrderEntry.OrderController.Count   (Aura.Core.Services) in 348.4091ms
info:   Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Request finished in 472.723ms 302
info:   Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
Request finished in 472.723ms 302
info:   Microsoft.AspNetCore.Hosting.Internal.WebHost[1]


AuthenticationScheme: Bearer was not   authenticated.
--


Is this what you are looking for?

**Comment by leastprivilege** [comment]
not sure - I don't see an error. So it's hard to tell.

**Comment by jayslife** [comment]
Hi @leastprivilege 

I am not getting any errors. 
When a post request is sent to my services, my Login page for Identity is returned to the HTMLClient. If a Get request is sent via my HTTPClient the correct json is returned.

**Comment by leastprivilege** [comment]
i suspect some configuration error in the asp.net core authN system.

**Comment by jayslife** [comment]
@leastprivilege I have reviewed this 100 times, I am not sure what else I can try. Do you have any pointers on how I can debug this issue.

I see some other have had issues with setting up Identity along side their services API. Has there been a sample project and/or do you have any pointers on what can commonly go wrong with this type of setup? I would like to keep them combined and this worked well in the previous version.

I am not able to get the plan [Authorize] attribute to work. As stated before I am able to successfully able to achieve Get type requests using [Authorize(AuthenticationSchemes = IdentityServerAuthenticationDefaults.AuthenticationScheme)] on my controllers. But Posts do not authenticate with bearer for some odd reason.

I am on 500th hour of trying to get this fix, all help would be greatly appreciated.

**Comment by brockallen** [comment]
Perhaps commercial support would be in order then?

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

**Comment by jayslife** [comment]
Follow up: This issue ended up being an issue with our implementation and use of an HttpClient.

**Comment by LindaLawton** [comment]
@jayslife  can you post some more info on your solution for this?
