### ISSUE TITLE
Identity Server 4 and HIPAA Compliance

### ISSUE THREAD

**Issue by IdahoSixString** [IdentityServer/IdentityServer4#1838]
Does anyone know if Identity Server 4 meets the guidelines set forth by HIPAA?

**Comment by brockallen** [comment]
What are the guidelines you're concerned about?

**Comment by brockallen** [comment]
Any follow-up to my question, @IdahoSixString?

**Comment by IdahoSixString** [comment]
@brockallen My apologies I did not get a notification of your first response.

HIPAA does not identify specific technologies when defining their guidelines. However, they do specify all patient information must be stored encrypted and must also be transmitted over an encrypted channel IE HTTPS. 

Really my primary concern is how is the account information for identity server stored? Is the data encrypted, salted, hashed?

**Comment by brockallen** [comment]
> HIPAA does not identify specific technologies when defining their guidelines. However, they do specify all patient information must be stored encrypted and must also be transmitted over an encrypted channel IE HTTPS.
> 
> Really my primary concern is how is the account information for identity server stored? Is the data encrypted, salted, hashed?

IdentityServer itself does not manage any of that type of data. Where do we require the storage of some data, we define extensibility points that you can implement for this storage. So if any of our data you want/need protected in some special way, you can do it.
