### ISSUE TITLE
Identity Server with Oracle

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#1840]
Is it possible to use Oracle as storage for Identity Server 4?

If yes, what is the best approach and way forward?

Thanks

**Comment by brockallen** [comment]
Short answer is yes, it's possible. Docs for you to do more research: 

http://docs.identityserver.io/en/release/topics/deployment.html#configuration-data

http://docs.identityserver.io/en/release/reference/ef.html

**Comment by satyajit-behera** [comment]
Thanks @brockallen . Will go through this.
