### ISSUE TITLE
Logout user from all active sessions

### ISSUE THREAD

**Issue by archil** [IdentityServer/IdentityServer4#1841]
This may be shamefully simple question to ask but I do not know where to start. 

Suppose I have MVC application and utilized Identityserver4. From some external, unrelated application authorized user is locked (maybe status changed in db)

The question is, how do I manage to immediately force user logout from all the browsers he may currently be logged in? 

In ideal solution, I suppose there should be a way I let IdentityServer know that user was locked out somewhere else and then server would push some kind of notification to all its clients, thus invalidating session. I could theoretically check user status with every request at identityserver but I think that would incur performance charges.

Any suggestion would be great.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by egmfrs** [comment]
Can you direct us to the appropriate part of the documentation perhaps? I've read the docs on sign out and this doesn't seem to be covered.

**Comment by barankaynak** [comment]
Link is broken and also signout title does not have any example code.
