### ISSUE TITLE
Removing unsafe-inline for Edge raises issues

### ISSUE THREAD

**Issue by pierslawson** [IdentityServer/IdentityServer4#1842]
The bug fix https://github.com/IdentityServer/IdentityServer4/issues/1748 seems sensible but does raise a couple of issues...

For me this broke the redirection from the authorize endpoint when I was using Edge. Somehow I still had a 2016 version of Edge installed, despite having run all available Windows Updates. I only managed to get it working by downloading the Windows Update Assistant from https://www.microsoft.com/en-gb/software-download/windows10 and forcing an install of the Windows 10 Fall Creators Update. So the first issue is... I wonder how many other "real" users might encounter the same problem.

Secondly, would it be sensible to include a submit button in the form rendered by the connect/authorize endpoint so that the form can be manually submitted if the user's browser doesn't support JavaScript (for whatever reason)? The button could be hidden by JavaScript (if it is allowed to execute) before the form is submitted. Or is there a security reason you didn't include a button on the page?

**Comment by brockallen** [comment]
There's an open issue (or PR?) already for your second part.

**Comment by brockallen** [comment]
Fixed the noscript part here: #1880.

**Comment by brockallen** [comment]
As for the first part of your question -- I don't know what to say. Edge, I thought, was under the same automatic release model that Chrome and FF use, so in theory it should always be up to date?

**Comment by brockallen** [comment]
@pierslawson any thoughts?

**Comment by pierslawson** [comment]
I don't think it auto updates in the same way Chrome does. It appears to update as part of significant OS updates e.g. Creators Fall Update. There is plenty of chatter about Microsoft potentially breaking this link (e.g. https://www.neowin.net/news/microsoft-will-unbundle-its-edge-browser-from-the-windows-10-os-with-redstone-3) but I can't see anything confirming it. So updates seem to be optional and in some cases (such as mine) the update mechanism seems to get stalled. 

Since Edge appears to have supported the headers correctly for quite a while, maybe it is time to move forward. My only real issue was that it took quite some time to realise what the problem was... then even longer to force an update of Edge. Perhaps a temporary note in the documentation might help the discoverability of the work around (i.e. check your version of Edge and ensure it is greater than X then force an update by using Windows Update or the Windows Update Wizard or Chrome / Firefox).

**Comment by brockallen** [comment]
> Perhaps a temporary note in the documentation might help the discoverability of the work around

I'm not sure where that would go. Any suggestions?

**Comment by pierslawson** [comment]
Mmmm not so easy as the connect/authorize/callback resource is not directly mentioned in the docs. So... perhaps it could go in the tutorial that first introduces OpenID Connect i.e. here:

http://docs.identityserver.io/en/release/quickstarts/3_interactive_login.html#testing-the-client

Or in the docs page that deals with interactive authentication, perhaps here:

http://docs.identityserver.io/en/release/topics/signin.html#login-workflow

**Comment by dlemstra** [comment]
@brockallen Sorry for hijacking this issues but we are also experiencing issues with the removal of the `'unsafe-inline'` part. We have some clients with very old browsers that can no longer use our services. Would it be an option to add a setting to allow CSP 1? I can send a PR for this if you would be open to adding this setting.

**Comment by brockallen** [comment]
We've had the discussion of CSP1, and we didn't want to go there. Mainly CSP1 didn't support script hash for inline script, IIRC, so we'd have to rework all JS to separate script sources, which is a bit of work and more moving parts.

**Comment by dlemstra** [comment]
I did some more testing and it turns out that the browsers that support the `sha256` hash will check it and ignore the `unsafe-inline` part. The patches in #1748 break backwards compatibility with older browsers. We now have some middle-ware in place that checks if the `Content-Security-Policy` response header is set and replaces `script-src` with `script-src 'unsafe-inline'` to fix the compatibility with older browsers. If you don't want to create an option to allow this backwards compatibility we would prefer it if we can inject something to override the behavior instead of having this middle-ware in place.

**Comment by brockallen** [comment]
The reason we were aggressive about removing this was because of a pen test from a customer complained about it. Yes, I understand that newer browsers know what to do, but it's a difficult trade off when a pen tester that doesn't trust the browser is telling a customer that there's a red flag (when in practice there's not).

**Comment by brockallen** [comment]
The other thought is a new config flag to change the behavior. Perhaps you could design a PR for something like this?

**Comment by dlemstra** [comment]
I will work on a PR for this 👍

**Comment by dlemstra** [comment]
The PR has been submitted @brockallen. Feel free to make changes or request me to make them :)

**Comment by timcodesdotnet** [comment]
@dlemstra would it be possible for you to post your middleware? I've tried to do something similar, but it does not get hit on the authorize endpoint. The only way I've thought to add the unsafe-inline on there is to build a custom IdentityServer package, which I really don't want to do. 

I am having issues with Safari <= 9 not liking the hash in the CSP.

**Comment by dlemstra** [comment]
@timcodesdotnet Still hoping this will get merged soon so we can get rid of the middleware. Will need to ask my manager if we can share this. But I can probably tell how we did it. Will get back to you on this tomorrow.

**Comment by dlemstra** [comment]
@timcodesdotnet  We use the `UseMiddleware` extension method of `IApplicationBuilder` to register the middleware.  And in your `Invoke` method you will need to do `context.Response.OnStarting(yourFuncThatChangesTheHeader, context)` to get access to the response.

**Comment by timcodesdotnet** [comment]
@dlemstra thank you. I have tried this method but it doesn't affect the authorize endpoint, unless I did something wrong? I guess I need to wait for this PR to be merged.

**Comment by dlemstra** [comment]
@timcodesdotnet Did you register the Middleware before you called `app.UseIdentityServer();`?

**Comment by timcodesdotnet** [comment]
@dlemstra :/ no...many thanks for the pointers, that's working now. Look forward to replacing it soon with your new option.

**Comment by dlemstra** [comment]
@timcodesdotnet Happy to hear you managed to resolve it. Also hope we can use this new option soon :)

**Comment by skoruba** [comment]
What about this feature? - I have same issue with Edge and removing unsafe-inline from csp.

**Comment by brockallen** [comment]
I've merged the PR so now there's an option you can configured if you want/need to support older browsers.

**Comment by brockallen** [comment]
I think this issue can be close now. Any objections?
