### ISSUE TITLE
Consider an intermediate page after login for native clients

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1843]
If/when a user logs in and a redirect goes back to a native client, the login page remains visible after response launches native client. It looks funny/odd.

**Comment by leastprivilege** [comment]
wat?

**Comment by brockallen** [comment]
This is for native apps that use the system browser and consent disabled.

**Comment by brockallen** [comment]
Perhaps we'll solve this by having a client setting to issue the redirect via meta tag, like this:

```
<meta http-equiv="refresh" content="0;url=x-github-client://oauth?code=e5370629d11219ce1234&amp;state=75d7f4c5-1cda-4649-a1a3-907b3400c354" data-url="x-github-client://oauth?code=e5370629d11219ce1234&amp;state=75d7f4c5-1cda-4649-a1a3-907b3400c354">
  <script crossorigin="anonymous" integrity="sha256-oRw7geHJNixCwmaaGrjOzjdIGcmGOW1x6ArbOL6S/bA=" src="https://assets-cdn.github.com/assets/redirect-a11c3b81e1c9362c42c2669a1ab8cece374819c986396d71e80adb38be92fdb0.js"></script>
 
```

**Comment by brockallen** [comment]
Done: https://github.com/IdentityServer/IdentityServer4/commit/5777bc12e67fd45bf3fb7ffad43d3d4017657c30
