### ISSUE TITLE
Access_Token iss and aud url is coming through HTTP

### ISSUE THREAD

**Issue by reeceengle** [IdentityServer/IdentityServer4#1846]
- [ X] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

I am deploying identity server 4 to AWS Elastic Beanstalk and for some reason my iss and aud variables within my token have started being returned as http:// instead of https:// as they have in previous deploys.  I was just curious if this issue has been encountered before and what I might be able to do to fix things?

Thanks.

### Relevant parts of the log file

```
  "iss": "http://stageauth.p.com",
  "aud": "http://stageauth.p.com/resources",

```

**Comment by brockallen** [comment]
Sounds like a load balancer issue.

**Comment by reeceengle** [comment]
My thoughts too.

Any recommendations on how to remedy or anything I can try to troubleshoot?

**Comment by brockallen** [comment]
Check the Microsoft docs -- they have middleware for that.

**Comment by reeceengle** [comment]
Any recommendations on where to start?

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/release/topics/deployment.html
