### ISSUE TITLE
Make TokenValidator extensible

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1847]
to support other JWT libs and e.g. JWE

**Comment by bashiransari** [comment]
@leastprivilege thanks for opening this issue. I might be able to put sometime on this and create a PR  in christmas period

**Comment by leastprivilege** [comment]
I need to know the use cases first. What's yours?

**Comment by bashiransari** [comment]
Sorry for the late reply,
We are implementing identity provider in an ecosystem with many legacy applications which we cannot have backchannel communication due to infrastructure limitations. We decided to go with implicit-flow with encrypted id token as we have some sensitive information in claims.

**Comment by leastprivilege** [comment]
OK - that's fine. You can do that with a custom token creation service. But why would you need a custom token validator?

**Comment by leastprivilege** [comment]
Oh I see - do you want to validate your encrypted id_tokens for signout?

**Comment by leastprivilege** [comment]
Is this your scenario?

If you don't give me more information, we can't put it into the next release..

**Comment by leastprivilege** [comment]
OK - since we didn't get a response. This will be postponed.

I think ultimately I want to split up the validators for id_token, access token and refresh token - and a shared JwtValidator that can be replaced independently.

**Comment by bashiransari** [comment]
Sorry for late reply.
No problem, I am using a work around for now, will wait for the 2.2 .

Thanks 🙏

**Comment by leastprivilege** [comment]
You still haven't answered my question...

**Comment by bashiransari** [comment]
Oh, Sorry :-(
Yes, I need to read the idtokenhint in signout flow

**Comment by leastprivilege** [comment]
What is your workaround today?

* How do you encrypt the token?
* How do you get the client id at validation time (before the token is decrypted)?

**Comment by bashiransari** [comment]
For encryption I am using custom token creation service to create encrypted token
For validation I have copied tokenvalidator source code and modified it to support decryption

**Comment by leastprivilege** [comment]
Would you make that source code available so I can have a look?

**Comment by bashiransari** [comment]
Yes, I will share the code tomorrow

**Comment by jaredrsowers** [comment]
I also need `TokenValidator` and `PrivateKeyJwtSecretValidator` to be extensible for the same reason. 

I need to use JWE instead of JWT. The token creation is already there, just the validation is missing. In both classes by just adding something similar to a "`protected virtual TokenValidationParameters GetTokenValidationParameters(trustedKeys,ValidIssuer,ValidAudience)`" would probably be sufficient, but it is needed in both classes...

**Comment by leastprivilege** [comment]
maybe @bashiransari can show us his code?

**Comment by jaredrsowers** [comment]
This is my WIP for generating the JWE by extending the `DefaultTokenCreationService`:

```
public interface IExtendedKeyMaterialService : IKeyMaterialService
{
    Task<EncryptingCredentials> GetEncryptingCredentialsAsync();
}

public class ExtendedKeyMaterialService : DefaultKeyMaterialService, IExtendedKeyMaterialService
{
    public ExtendedKeyMaterialService(IEnumerable<IValidationKeysStore> validationKeys, ISigningCredentialStore signingCredential = null)
    : base(validationKeys, signingCredential)
    {
    }

    public Task<EncryptingCredentials> GetEncryptingCredentialsAsync()
    {
        var key = Convert.FromBase64String("some static key");

        var jweSecurityKey = new SymmetricSecurityKey(key)
        {
            KeyId = "aes_key_id"
        };

        var encryptingCredentials = new EncryptingCredentials(jweSecurityKey, SecurityAlgorithms.Aes256KW, SecurityAlgorithms.Aes256CbcHmacSha512);

        return Task.FromResult(encryptingCredentials);
    }
}

public class ExtendedTokenCreationService : DefaultTokenCreationService
{
    private readonly IExtendedKeyMaterialService _keys;

    public ExtendedTokenCreationService(ISystemClock clock, IExtendedKeyMaterialService keys, ILogger<ExtendedTokenCreationService> logger)
    : base(clock, keys, logger)
    {
        _keys = keys;
    }

    protected override async Task<string> CreateJwtAsync(JwtSecurityToken jwt)
    {
        var encryptingCredentials = await _keys.GetEncryptingCredentialsAsync();

        var tokenDescriptor = new SecurityTokenDescriptor
        {
            EncryptingCredentials = encryptingCredentials,
            SigningCredentials = jwt.SigningCredentials,
            Subject = new ClaimsIdentity(jwt.Claims)
        };

        var handler = new JwtSecurityTokenHandler();

        var jwe = handler.CreateJwtSecurityToken(tokenDescriptor);

        return jwe.RawData ?? handler.WriteToken(jwe);
    }
}
```

Everything seem to be working properly in my testing.

**Comment by leastprivilege** [comment]
> the client will append the client id to the 5 part token as will send it as id_token_hint parameter.

I think there are better solution to this. Something we need to figure out first.

Given that this requires some more research, and we have other higher priority issues right now - we have no plans right now to support encryption built-in.

If your company needs that feature built-in, they can sponsor us and we can work out something.

**Comment by DureSameen** [comment]
please see my example implementations :  https://github.com/DureSameen/IdentityServer4.JWE
