### ISSUE TITLE
Using Request Resource Owner Password in MVC Web app

### ISSUE THREAD

**Issue by bathorize** [IdentityServer/IdentityServer4#1848]
Hi,

We are using IdentityServer 4 aspnetcore1 for multiple clients. We first used it in a WebAPI serving to an Android app- the user enters his username and password in the native app, sends them to the WebAPI, and there we acquire an access token via RequestResourceOwnerPasswordAsync. In following calls when the client sends us the authorization header with Bearer {AccessToken}, the user is authenticated and also the HttpContext.User.Claims contains all the identity claims, along with its Subject. This works great.

Now, we tried the same approach with an MVC web client, but after login, the user is missing all the claims. What we want is to use the our login page to get the user's credentials, and use them to RequestResourceOwnerPasswordAsync to get the AccessToken. Then we save the token in a cookie, and have an mvc filter that will add it as a Authorization Bearer header to the requests.
The Bearer token is set correctly in the requests, HttpContext.User.Identity.IsAuthenticated is true, but the User Claims is missing "sub" claim and all the rest of the user claims (same scenario in WebAPI had them). I tried to manually call the /connect/introspect endpoint with the access token and successfully got the user's Subject. In the WebAPI client this get's called automatically, and the claims are set- I want this to happen the same in my MVC web app. I do not want to manually use this endpoint to get the user Subject from the access token- this is an ugly hack.

Can this be done? Probably Am I missing some configuration?

I'v seen all the client samples for MVC, but all of them redirected the user to the IdentityServer login page and we want to use our own in app custom login page.

Also, we use AccessTokenType Reference. I tried to change it to Jwt, but it didn't matter.

Here is the client definition in the Identity Server:
                new Client
                {
                    ClientId="MvcClient",
                    ClientName="MvcClient",
                    AllowAccessTokensViaBrowser=true,
                    AllowedGrantTypes=GrantTypes.ResourceOwnerPasswordAndClientCredentials,
                    AccessTokenType= AccessTokenType.Reference,
                    ClientSecrets =
                    {
                        new Secret("SOME-SECRET".Sha256())
                    },
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile
                    }
                },

**Comment by leastprivilege** [comment]
Resource owner flow is not authentication - that's why you don't get the claims back into the client.

Either change to a proper flow or you must utillize hacks.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
