### ISSUE TITLE
Loader on a connect/authorize/callback

### ISSUE THREAD

**Issue by haukurmar** [IdentityServer/IdentityServer4#1849]
Hi,

I am wondering what would be the best way to add some kind of a loader when IdentityServer is verifying identity, such as on the /connect/authorize and /connect/authorize/callback routes. 

Basically just an animated gif or font-awesome spinner on the view so that the user knows that something is going on.

Any ideas?

**Comment by JonasDbt** [comment]
This would really be nice. Even the possibility to give a message (text) would be great. Maybe by setting a value in the options?

**Comment by brockallen** [comment]
Dup. This can be done in the same way as: #1843. Stay tuned for that issue to be closed.

**Comment by WesToleman** [comment]
Hi,

I'm trying to implement a spinner for `/connect/authorize` /`/connect/authorize/callback` for a hybrid flow in a browser using windows integrated auth. I have looked at the linked issue and its fix however I'm not sure how to apply it to my situation. Is there a sample implementation I could reference?

**Comment by stijnsta** [comment]
I'm trying the same thing, but can't figure out how to achieve this. An example would be great.
