### ISSUE TITLE
Figure out cross references in docs

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#185]
https://github.com/IdentityServer/IdentityServer4/pull/184

**Comment by mpoettgen** [comment]
Could it be that avoiding underscore (_) within the label/hyperlink target could do the trick? it looks like it has a special meaning, so could mean trouble.

http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#hyperlink-targets
