### ISSUE TITLE
Exposing IdentityServer4 api endpoint to MVC client under OpenIdConnect scheme

### ISSUE THREAD

**Issue by nicbavetta** [IdentityServer/IdentityServer4#1850]
I have implemented an IdentityServer4 host with a Hybrid/ClientCredentials MVC client. I have an API within the IdentityServer4 host that I wish to expose to this client. I simply added a new ApiResource to the resource store, added this resource to AllowedScopes on the client model (maintained by my IClientStore implementation) and also added the resource to the Scope collection in the OpenIdConnect options on client startup.

Lastly, I added the following code to the IdentityServer4 host startup:

```
services.AddAuthentication()
             .AddIdentityServerAuthentication(OpenIdConnectDefaults.AuthenticationScheme, isAuth =>
             {
                 isAuth.Authority = "https://localhost:44336/";
                 isAuth.ApiName = "coreapi";
             });
```

The above code was inserted after the call to services.AddIdentityServer().

All of this works fine. The client is able to access the endpoint with the access token retrieved from the IdentityServer4 host. My question, however, is - do I want to be using the OpenIdConnect scheme for protecting this resource? Or should it have its own scheme? If I should be using a new scheme, how can I go about doing this while still maintaining OpenIdConnect authentication?

**Comment by leastprivilege** [comment]
have a look here

https://identityserver4.readthedocs.io/en/release/topics/add_apis.html

but also:

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by nicbavetta** [comment]
I have already looked at that documentation. It does not answer my question.

**Comment by leastprivilege** [comment]
Then I don't understand your question tbh.
