### ISSUE TITLE
[Question] [Code-review] Get user id from reference token in API

### ISSUE THREAD

**Issue by WiL-dev** [IdentityServer/IdentityServer4#1851]
My setup, 

+ An IdentityServer using MVC Identity to store the Users, created with `dotnet new mvc -au Individual` and applying the http://docs.identityserver.io/en/release/quickstarts/0_overview.html tutorial, running in localhost 5000.
+ An Ionic App (basically Angular2), but now I'm using postman to do tests.
+ A WEB API, created with `dotnet new webapi`, running in localhost 5001.

The IdentityServer resources and clients configuration is the following, notice that I'm using reference tokens:

       public static IEnumerable<IdentityResource> GetIdentityResources() {
            return new List<IdentityResource>{ new IdentityResources.OpenId() };
        }

        public static IEnumerable<ApiResource> GetApiResources() {
            return new List<ApiResource>{
                new ApiResource("api_resource", "API Resource") {
                    Description= "API Resource Access",
                    ApiSecrets= new List<Secret> { new Secret("apiSecret".Sha256()) },
                }
            };
        }

        public static IEnumerable<Client> GetClients() {
            return new List<Client>{
                new Client {
                    ClientId= "angular-client",
                    ClientSecrets= { new Secret("secret".Sha256()) },
                    AllowedGrantTypes= GrantTypes.ResourceOwnerPassword,
                    AllowOfflineAccess= true,
                    AccessTokenType = AccessTokenType.Reference,
                    AlwaysIncludeUserClaimsInIdToken= true,
                    AllowedScopes= { "api_resource" }
                }`

The password and user is send with postman and the token received is send to the WEB API also with postman, something like call `localhost:5001/v1/test` with the option `bearer token` .

In the API Startup, in ConfigureServices I'm adding the lines below

       services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority= "http://localhost:5000";
                    options.ApiName= "api_resource";
                    options.ApiSecret = "apiSecret";
                });`

And I'm getting the Id of the user inside the controller as follows:

    public async Task<IActionResult> Get(int id) {
        var discoveryClient = new DiscoveryClient("http://localhost:5000");
            var doc = await discoveryClient.GetAsync();

            var introspectionClient = new IntrospectionClient(
                doc.IntrospectionEndpoint,
                "api_resource",
                "apiSecret");

            var token= await HttpContext.GetTokenAsync("access_token");

            var response = await introspectionClient.SendAsync(
                new IntrospectionRequest { Token = token });

            var userId = response.Claims.Single(c => c.Type == "sub").Value;
    }

The question itself is if I'm using the right path to get the Id from the reference token, because now It works but I don't want to miss anything, specially thinking that is a security concern.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by WiL-dev** [comment]
Sorry for pollute the issues board, @brockallen this is the [question in stackoverflow][1].

CC: @leastprivilege because I'm using [IdentityModel][2] and the IntrospectionClient, (to be precise the IntrospectionResponse) don't seems to have an extension method to get user Id specific claim, that's why I have the felling that I'm missing something, plus there is the [OAuth2Introspection repository][3] that make some noise to me.

Thanks guys, excellent work!

[1]: https://stackoverflow.com/questions/47774842/get-user-id-from-reference-token-in-api
[2]: https://github.com/IdentityModel/IdentityModel2
[3]: https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection
