### ISSUE TITLE
Custom Login Page Per Client - Recommended Approach

### ISSUE THREAD

**Issue by markgmarkg** [IdentityServer/IdentityServer4#1853]
I manage to use Social vendors to authenticate users per specific web client (MVC).

I'm wondering what should be a right approach to show users a customized UI for this specific client.
What options are available?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
