### ISSUE TITLE
Discovery Endpoint event for logging

### ISSUE THREAD

**Issue by lythronaxargestes** [IdentityServer/IdentityServer4#1857]
I'm wondering if it would be possible to add an event type that is emitted when a request is made to the Discovery Endpoint? I would like to use this event type for custom logging.

Thanks in advance.

**Comment by leastprivilege** [comment]
What's the use case?

**Comment by lythronaxargestes** [comment]
For the client, when the DiscoveryClient is making a request to the Discovery Endpoint, I would like to write a custom log message containing metadata about the request extracted from the HttpContext.

**Comment by leastprivilege** [comment]
OK - we'll consider it.

For now you can just derive from our discovery response generators and emit an even yourself.

**Comment by brockallen** [comment]
> For the client, when the DiscoveryClient is making a request to the Discovery Endpoint, I would like to write a custom log message containing metadata about the request extracted from the HttpContext.

Does this mean you're sending custom params to the discovery endpoint?

**Comment by lythronaxargestes** [comment]
No, I am getting the context from HttpContextAccessor. I just need to read the context _when_ the event is emitted.

**Comment by leastprivilege** [comment]
We have some time now to add this - what kind of information would you like to see on this event?

**Comment by lythronaxargestes** [comment]
In addition to the base event properties, it would be useful to have the name/ID of the API or client from which the request is originating (if it is possible to determine this information).

**Comment by leastprivilege** [comment]
It's not  it's an anonymous call.

That's why I am questioning the value of this event altogether.

**Comment by brockallen** [comment]
It is not. The discovery endpoint request is anonymous.

**Comment by lythronaxargestes** [comment]
I see. In that case, the base event properties would suffice. My primary motivation is just to be able to know _when_ a request is made to the discovery endpoint.

**Comment by leastprivilege** [comment]
> you can just derive from our discovery response generators and emit an even yourself.

did you try this?

**Comment by leastprivilege** [comment]
OK - I don't see a value in an even that simply states that the discovery endpoint has been requested. Events are for logging structured data.

There are multiple other ways to achieve your goal

* derive from the response generator
* put middleware in the pipeline that checks for the discovery endpoint and do your logging here.

closing.
