### ISSUE TITLE
how transfer my self parameter to the client?

### ISSUE THREAD

**Issue by liugt34** [IdentityServer/IdentityServer4#1859]
in examples Quickstarts\3_ImplicitFlowAuthentication,,i modify the Config.cs file, and change the method 
 public static List<TestUser> GetUsers()   to 

````
public static List<TestUser> GetUsers()
 {
return new List<TestUser>
            {
                new TestUser
                {
                    SubjectId = "1",
                    Username = "alice",
                    Password = "password",

                    Claims = new List<Claim>
                    {
                        new Claim(JwtClaimTypes.Name, "Alice Smith"),
                        new Claim(JwtClaimTypes.GivenName, "Alice"),
                        new Claim(JwtClaimTypes.FamilyName, "Smith"),
                        new Claim(JwtClaimTypes.Email, "AliceSmith@email.com"),
                        new Claim(JwtClaimTypes.EmailVerified, "true", ClaimValueTypes.Boolean),
                        new Claim(JwtClaimTypes.WebSite, "http://alice.com"),
                        new Claim(JwtClaimTypes.Address, @"{ 'street_address': 'One Hacker Way', 'locality': 'Heidelberg', 'postal_code': 69118, 'country': 'Germany' }", IdentityServer4.IdentityServerConstants.ClaimValueTypes.Json)
                    }
                },
                new TestUser
                {
                    SubjectId = "2",
                    Username = "bob",
                    Password = "password",

                    Claims = new List<Claim>
                    {
                        new Claim(JwtClaimTypes.Name, "Bob Smith"),
                        new Claim(JwtClaimTypes.GivenName, "Bob"),
                        new Claim(JwtClaimTypes.FamilyName, "Smith"),
                        new Claim(JwtClaimTypes.Email, "BobSmith@email.com"),
                        new Claim(JwtClaimTypes.EmailVerified, "true", ClaimValueTypes.Boolean),
                        new Claim(JwtClaimTypes.WebSite, "http://bob.com"),
                        new Claim(JwtClaimTypes.Address, @"{ 'street_address': 'One Hacker Way', 'locality': 'Heidelberg', 'postal_code': 69118, 'country': 'Germany' }", IdentityServer4.IdentityServerConstants.ClaimValueTypes.Json),
                        new Claim("location", "somewhere")
                    }
                }
            };
````

but in the client ,when it run , it only show the GivenName&FamilyName,,but the Email and Address did not show anywhere, so how can i show the email or the address or other parameters?
need help?thanks

=================The list of MvcClient=======================
# Secure
## User claims
**sid**
c3aa644f76b48fe7339361b8c1da0cce
**sub**
1
**idp**
local
**name**
Alice Smith
**given_name**
Alice
**family_name**
Smith
**website**
http://alice.com

**Comment by brockallen** [comment]
I'd suggest reading more of the docs:

http://docs.identityserver.io/en/release/topics/resources.html

Having said that, 
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by liugt34** [comment]
@brockallen 
i have add the IdentityResources email and address in methed GetIdentityResources
```
public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Email(),
                new IdentityResources.Address()
                //customResource
            };
        }
```

and then add AllowScopes in method GetClients()
```
// OpenID Connect implicit flow client (MVC)
                new Client
                {
                    ClientId = "mvc",
                    ClientName = "MVC Client",
                    AllowedGrantTypes = GrantTypes.Implicit,

                    RedirectUris = { "http://localhost:5002/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:5002/signout-callback-oidc" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        IdentityServerConstants.StandardScopes.Address,
                    }
                }
```

but i still can't get the email and address claims on client?  i'm so confused

**Comment by leastprivilege** [comment]
..and does your client ask for the scopes?

That's what Brock meant - we cannot teach you how the spec works...

**Comment by liugt34** [comment]
@leastprivilege 
i tracked the code ,i find in the file  **ConsentService.cs**  the line 101

`var resources = await _resourceStore.FindEnabledResourcesByScopeAsync(request.ScopesRequested);`

the request.ScopesRequested only have openid and profile,,, i think maybe the url is wrong
see the url the parameter bold 
http:// localhost:5000/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dmvc%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A5002%252Fsignin-oidc%26response_type%3Did_token%26_**scope%3Dopenid%2520profile**_%26response_mode%3Dform_post%26nonce%3D636488366292757625.YjE0ZjNmYWItYzUyMC00NmI4LThiNDMtNmQ...

**Comment by liugt34** [comment]
@leastprivilege 
you mean i must set the scopes in client?

**Comment by liugt34** [comment]
@leastprivilege 

thank you very much ,i find it
