### ISSUE TITLE
Disable resource owner password validation after adding identity

### ISSUE THREAD

**Issue by matasliorentas** [IdentityServer/IdentityServer4#1861]
Hi,

I'm updating project which uses IdentityServer4 and IdentityServer4.AspNetIdentity from .Net Core 1.1 to 2.0 and there is issue where password grant type is not disabled because extension method  AddAspNetIdentity<T>() adds resource owner validator. 
Before update the project was configured to set resource owner validator to NotSupportedResourceOwnerPasswordValidator after adding identity, however in IdentityServer4 version 2.0.5 class NotSupportedResourceOwnerPasswordValidator is internal and that is not possible. 
Also discovery response generator checks if registered resource owner password validator is of NotSupportedResourceOwnerPasswordValidator type to determine whether to add password grant type or not, so even if I implemented my own password validator, password grant type would still show up in discovery document.

Is there a way to disable resource owner password validation again?

### Issue / Steps to reproduce the problem
In ConfigureServices method call
`services.AddIdentityServer().AddAspNetIdentity<User>();`
and check discovery document to see that grant types contain 'password'.

**Comment by leastprivilege** [comment]
Made the `NotSupportedResourceOwnerPasswordValidator` public - you can register that to disable resource owner flow.
