### ISSUE TITLE
Accessing introspection endpoint with Asp.Net Web Api in IdentityServer4 

### ISSUE THREAD

**Issue by jdbmarx** [IdentityServer/IdentityServer4#1862]
Hi!

I am developping a new Identity Server in my client using IdentityServer4 (.net core is a request) and I need to protect all legacy api's (Asp.Net Web Api) so I used IdentityServer3.AccessTokenValidation in them. But I receive a 401 result when accessing introspection endpoint for token validation. After a long time of research I found a post explaining that introspection endpoint is now protected with Api secret but I can't set it with IdentityServer3.AccessTokenValidation. How can I do it to work? 

Thanks in advance.

Dalton

**Comment by brockallen** [comment]
Yes, you can. It's ClientId and ClientSecret (which are ApiName/ApiSecret in the ASP.NET Core versions).

**Comment by jdbmarx** [comment]
I am receiving the following log:

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 POST http://localhost:8263/connect/introspect application/x-www-form-urlencoded 70
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
 >      Request starting HTTP/1.1 POST http://localhost:8263/connect/introspect application/x-www-form-urlencoded 70
> dbug: IdentityServer4.Hosting.EndpointRouter[0]
>       Request path /connect/introspect matched to endpoint type Introspection
> dbug: IdentityServer4.Hosting.EndpointRouter[0]
>       Endpoint enabled: Introspection, successfully created handler: IdentityServer4.Endpoints.IntrospectionEndpoint
> info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
>       Invoking IdentityServer endpoint: IdentityServer4.Endpoints.IntrospectionEndpoint for /connect/introspect
> info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.IntrospectionEndpoint for /connect/introspect
dbug: IdentityServer4.Endpoints.IntrospectionEndpoint[0]
      Starting introspection request.
dbug: IdentityServer4.Validation.BasicAuthenticationSecretParser[0]
      Start parsing Basic Authentication secret
dbug: IdentityServer4.Validation.SecretParser[0]
      Parser found secret: BasicAuthenticationSecretParser
dbug: IdentityServer4.Validation.SecretParser[0]
      Secret id found: applications
fail: IdentityServer4.Validation.ApiSecretValidator[0]
      No API resource with that name found. aborting
fail: IdentityServer4.Validation.ApiSecretValidator[0]
      No API resource with that name found. aborting
fail: IdentityServer4.Endpoints.IntrospectionEndpoint[0]
      API unauthorized to call introspection endpoint. aborting.
fail: IdentityServer4.Endpoints.IntrospectionEndpoint[0]
      API unauthorized to call introspection endpoint. aborting.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 120.222ms 401
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 120.222ms 401

IdSvr4 configuration:
```c#
        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource("my-api", "My Api")
                {
                    ApiSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    Scopes =
                    {
                        new Scope("api")
                    }
                }
            };
        }

        public static IEnumerable<Client> GetClients()
        {

            return new List<Client>
        {
            new Client
            {
                ClientId = "applications",

                // no interactive user, use the clientid/secret for authentication
                AllowedGrantTypes = GrantTypes.ClientCredentials,

                AccessTokenType = AccessTokenType.Reference,
                // secret for authentication
                ClientSecrets =
                {
                    new Secret("secret".Sha256())
                },
                
                AllowOfflineAccess = false,
                AccessTokenLifetime = lifetime.GetValueOrDefault(3600),
                ConsentLifetime = lifetime,
                IdentityTokenLifetime = lifetime.GetValueOrDefault(300),
                // scopes that client has access to
                AllowedScopes = { "my-api", "api" }
            },
        };
```
Web Api configuration:

                app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = "http://localhost:8081",
                    ValidationMode = ValidationMode.ValidationEndpoint,
                    ClientId= "applications",
                    EnableValidationResultCache = false,
                    RequiredScopes = new[] { "my-api","api" },                    
                    ClientSecret = "secret"

                });

**Comment by leastprivilege** [comment]
Your client id is wrong, it needs to be the name of the api resource that has the associated secret - see sample here:

https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/SampleAspNetWebApi/Startup.cs#L17-L25

**Comment by barron9** [comment]
issue resolved.
```

   app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
                {
                    Authority = Constants.BaseAddress,
                    RequiredScopes = new[] { "write" },

                    // client credentials for the introspection endpoint
                    ClientId = "write",
                    ClientSecret = "secret"
                });
```
