### ISSUE TITLE
Can it have different secret to different scope?

### ISSUE THREAD

**Issue by kevinlo** [IdentityServer/IdentityServer4#1863]
I ask this question in [stackoverflow](https://stackoverflow.com/questions/47765339/can-it-have-different-client-secret-for-different-scope), but I don't get an answer.

If a client allows the following scopes, can it have different secret for different scopes (e.g. secret1 for the "opened" and "profile" and secret2 for the "api2")? 

  "AllowedScopes": [ "openid", "profile", "api2" ],

I mean can it limit the client with secret1 to access the opened" and "profile" scope only, but not the "api2" scope and client with secret2 access the "api2" scope only? If not, what is the right way to achieve it?

From what I have read, the client secret is used to authorize access to the token endpoint. Client with secret1 or secret2 can create token of any of the allowed scopes.

From the [IdentityServer doc](http://hts.readthedocs.io/en/latest/topics/secrets.html), it says 

`This secret can now be assigned to either a Client or a Scope. `

But I don't see the [Scope class](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Models/Scope.cs) has the Secret field.

From [IdentityServer3 doc](https://identityserver.github.io/Documentation/docsv2/configuration/secrets.html), it has the ScopeSecrets.  Is it gone in IdenityServer4?

Should I use different client id (for the same application) to allow different scopes?

**Comment by brockallen** [comment]
The docs had a bug -- it should be:

`This secret can now be assigned to either a Client or a Scope.`

I fixed it.

**Comment by kevinlo** [comment]
@brockallen You just type what the current doc has.  Do you mean it had bug and you had fixed it and the current one is correct?   In that case, how to assign secret to the Scope?

Can you also comment about if we can have the same client but different secrets for different scopes?

**Comment by brockallen** [comment]
Sorry, I fixed my typo above. It should be ApiResource.

**Comment by Mataru** [comment]
Do I understand correctly from this thread that it is **not** possible to give a single client access to different scopes or resources based on which client secret is used? Will I have to define a new client if I want to be able to access a different set scopes/resources?
