### ISSUE TITLE
Consider dropping VS ASP.NET Identity template from host and samples

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1864]

**Comment by Jenan** [comment]
Why - can you add more info please? Thx.

**Comment by brockallen** [comment]
> Why - can you add more info please? Thx.

Because it has so much junk and it adds to the noise of illustrating the little bit of code needed to get ASP.NET Identity working with IdentityServer. Plus, it's a pain to update our samples every time Microsoft changes their templates.

**Comment by justindrerup** [comment]
I recently setup Identity Server with ASP.NET Identity and I found the samples invaluable - I therefore am an advocate of keeping them.  Being able to download the working samples from Github really helped put the theory/documentation into practice.  That said, I didn't attempt to go through the process of getting Identity Server working (without the samples) and it may have been a trivial task to complete.

**Comment by naveddeshmukh** [comment]
I vote to **keep** the Aspnet Identity Samples, If IdentityServer has support for Aspnet Identity, then there is a need for Samples and Docs for it.

**Comment by brockallen** [comment]
The problem is that Microsoft's template isn't well suited for how a token server needs to operate. We won't drop a sample using ASP.NET Identity, it's just that it's a lot of work to keep it feature-parity with the Microsoft template. So for now, this issue will defer to #1950, as that will be our ASP.NET Identity starting point.
