### ISSUE TITLE
MySQL and PostgreSQL Database Provider Integration Tests

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1865]
AppVeyor offers MySQL and PostgreSQL for testing. Integration tests should target these when in this environment.

Moved from: https://github.com/IdentityServer/IdentityServer4.EntityFramework/issues/37

**Comment by brockallen** [comment]
@scottbrady91 you'll have some free time over the holidays, right?

**Comment by scottbrady91** [comment]
This has been done by the way
