### ISSUE TITLE
Adding a client at runtime

### ISSUE THREAD

**Issue by vcrobe** [IdentityServer/IdentityServer4#1868]
In the sample "IdentityServer.Samples\Quickstarts\8_EntityFrameworkStorage\" I'm able to add a new _client_ to the database using a custom controller/view.

When I restart the application that client is loaded into the IdentityServer but I need to load that _client_ into the IdentityServer without having to restart the aplication, I mean, at runtime. How can I do that?

Thank you

**Comment by brockallen** [comment]
I'm confused. When you're using the EF implementation of the client store, then the clients are being loaded dynamically from the DB.

**Comment by vcrobe** [comment]
> then the clients are being loaded dynamically from the DB

YES! That happen in the initialization of the application, but once the application is initialized, let say, two hours after it's running I want to add a new client to the database but at the same time I want the client be recognized by _IdentityServer_ without having to restart the application.

**Comment by brockallen** [comment]
Right, which means you'd want to use the EF library we provide. I'm still confused.

**Comment by leastprivilege** [comment]
Our EF implementation loads clients and resources dynamically from the DB.

**Comment by NaniFlorida** [comment]
I have the same problem that I want to post client at run time to database using views is that possible
