### ISSUE TITLE
Login view per Client

### ISSUE THREAD

**Issue by maganuk** [IdentityServer/IdentityServer4#187]
Hi,

I've got an Identity Server (v4) up and running and have defined all the clients, users, scopes etc. I have an Angular Data Administration app, another Angular customer facing app and an Web API which serves the two apps. Currently everything works fine on the api and angular side. However, we would like for only our internal users to be able to login to the Data Admin app and the other users (including our internal users) to login to our customer facing app. 

The customers should be able to login locally or using other OAuth providers (such as facebook) but the internal users should only be able to login locally or using an Internal azure ad. I have all of this setup.

How can I create different login views for each of the clients (apps)? Currently all the authentication requests go to the same login view and therefore I am unable to customize the OAuth providers for each of the apps. Also I'd like for the login views to look like our apps.

Any help would be really appreciated.

Thanks
Vishal

**Comment by brockallen** [comment]
You're asking for two things. The first part is a dup of https://github.com/IdentityServer/IdentityServer4/issues/166, I believe.

The second part is solved by the "allowed IdPs" options  on the Client config. Your login UI would need to query this and do the right thing.

The third is a matter of your UI accessing the client requesting the login and changing itself accordingly.

**Comment by maganuk** [comment]
Thanks a lot. Just one quick question: 

"The third is a matter of your UI accessing the client requesting the login and changing itself accordingly."

Could you please give me a hint on how I can ascertain the client requesting the login?

**Comment by maganuk** [comment]
Would it be from the querystring?

**Comment by brockallen** [comment]
Look at the sample host -- there's a service injected to get this info.

**Comment by maganuk** [comment]
Got it thanks a lot.

**Comment by brockallen** [comment]
Follow-up question for you: for your first requirement where the user can't use certain clients (external user can't use internal for example) what would you want to happen if they did make the request into IdSvr? Should IdSvr 1) show them an error, or 2) show them a login page to login as a user that is allowed to access the app?

**Comment by maganuk** [comment]
The way I have implemented it now, the user is redirected the correct login page based on where he is coming from. So for example, if he is an external user and tries to login to the internal web app, he gets a failed login (invalid login). At least for me, this is the correct response. I would imagine, most would expect the same.

**Comment by brockallen** [comment]
Thanks for that. Also feel free to add any input to this thread: https://github.com/IdentityServer/IdentityServer4/issues/166 with any pertinent suggestions/feedback you have.

**Comment by maganuk** [comment]
Ok. Will have a look. Thanks

**Comment by ddydeveloper** [comment]
Hi!

Thank you for ID4, it is awesome. Maybe it is not suitable d, but it looks like this. I have several questions about ID4. Unfortunately, I didn't fully understand your solution. Can I implement this case with ID4: 

1. I have more than 1 client
2. Each client should be authenticated separately, so even if I logged in in the first app I need to login in the second one. 

Can I use build-in mechanism to implement this or I need to implement different log in solutions and use ID4 just as a API protection service? 

Any help would be really appreciated.

**Comment by maganuk** [comment]
That's what identity server is built for. You can authenticate as many clients as you like. Think of how you can login to different sites using Facebook, all using a single set of credentials. To force the user to login you could use prompt=login.

Have a look at https://github.com/IdentityServer/IdentityServer3/issu

**Comment by maganuk** [comment]
have a look at this: http://docs.identityserver.io/en/release/topics/signout.html

hope you've configured the two clients separately in IDS...

**Comment by ddydeveloper** [comment]
@maganuk if I'm not mistaken, clients configured separately:

`internal static IEnumerable<Client> GetClients(IEnumerable<RegisteredClient> clients)
        {
            return new List<Client>
            {
                new Client
                {
                    ClientId = "1",
                    AllowedGrantTypes = GrantTypes.Hybrid,
                    RequireConsent = false,

                    RefreshTokenExpiration = TokenExpiration.Sliding,
                    RefreshTokenUsage = TokenUsage.ReUse,

                    ClientSecrets = {new Secret("secret-1".Sha256())},
                    RedirectUris = new[] {"http://localhost:5002/signin-oidc"},
                    PostLogoutRedirectUris = new[] {"http://localhost:5002/signout-callback-oidc"},

                    UpdateAccessTokenClaimsOnRefresh = true,

                    AllowAccessTokensViaBrowser = true,
                    AllowedScopes = new List<string>
                    {
                        "services",
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.OfflineAccess
                    },
                    AllowedCorsOrigins = {"http://localhost:5002"},
                    AllowOfflineAccess = true
                },
                new Client
                {
                    ClientId = "2",
                    AllowedGrantTypes = GrantTypes.Hybrid,
                    RequireConsent = false,

                    RefreshTokenExpiration = TokenExpiration.Sliding,
                    RefreshTokenUsage = TokenUsage.ReUse,

                    ClientSecrets = {new Secret("secret-2".Sha256())},
                    RedirectUris = new[] {"http://localhost:5003/signin-oidc"},
                    PostLogoutRedirectUris = new[] {"http://localhost:5003/signout-callback-oidc"},

                    UpdateAccessTokenClaimsOnRefresh = true,

                    AllowAccessTokensViaBrowser = true,
                    AllowedScopes = new List<string>
                    {
                        "services",
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.OfflineAccess
                    },
                    AllowedCorsOrigins = {"http://localhost:5003"},
                    AllowOfflineAccess = true
                }
            };
        }` 

I've checked Logout action on new client logged in, it was not called. Even if I log in under the different logins I automatically log out from another app. I can't understand why.

**Comment by maganuk** [comment]
Check what cookies are clearing out. If I'm not mistaken, ids should retain
the cookie after logging out of one of the applications. Unless you're
doing a single signout.

**Comment by ddydeveloper** [comment]
@maganuk If I log out all cookies are cleared. I can't understand, why log in to one app force log out from another one?

Right now I have followed behaviour:

1. I've set up promt=login for all client apps in OIDC middleware;
2. I'm not loggen in any app;
3. I do log in in the first app, it works as expected;
4. I do log in in the second app
5. I update the first app page, after this I am redirected to the log in page; 
6. If I log put from one of the apps - I'm logged out from all of them.

So, i can be logged in in several app at the same time.

if I remove promt=login it works as single sign in:
1. I'm not loggen in any app;
2. I do log in in the first app, it works as expected;
3. I'm logged in the second app automatically;
4. If I log put from one of the apps - I'm logged out from all of them.

I want to get this scenario:
1. I'm not loggen in any app;
2. I do log in in the first app;
3. I do log in in the second app;
4. I do log out from the first app;
5. I'm still logged in the second app;
6. I do log out from the second app.

So I consider ID4 as the single point to log in all client apps but it should provide log in per each client. Cause different user can be logged in in one app but can't be loggen in in others.

**Comment by span** [comment]
Sorry for bringing this back to life but I'm trying to build separate gui's for different clients and I can't figure out what this means and where to find it:

> Look at the sample host -- there's a service injected to get this info.
