### ISSUE TITLE
LoginViewModel in QuickStart.UI May Have an Issue

### ISSUE THREAD

**Issue by markgmarkg** [IdentityServer/IdentityServer4#1870]
`ExternalLoginScheme` will raise an exception when using more than one External Providers.

    public class LoginViewModel : LoginInputModel
    {
        //....
        public IEnumerable<ExternalProvider> ExternalProviders { get; set; }
        public bool IsExternalLoginOnly => EnableLocalLogin == false && ExternalProviders?.Count() == 1;

        public string ExternalLoginScheme 
            => ExternalProviders?.SingleOrDefault()?.AuthenticationScheme; // <-- SingleOrDefault will throw on multiple items
    }

Should it return the first scheme available?

**Comment by brockallen** [comment]
`ExternalLoginScheme ` should not be used unless `IsExternalLoginOnly ` is true.

**Comment by markgmarkg** [comment]
Probably, this part should be re-factored a bit...

    public class LoginViewModel : LoginInputModel
    {
        public bool HasSingleExternalLoginOnly 
            => EnableLocalLogin == false && ExternalProviders?.Count() == 1;
        public string UniqueExternalLoginScheme 
            => HasSingleExternalLoginOnly ? ExternalProviders.FirstOrDefault()?.AuthenticationScheme : null;
    }

**Comment by brockallen** [comment]
Feel free to send a PR -- you might be able to get to it before me.

**Comment by brockallen** [comment]
What about this change:

`public string ExternalLoginScheme => IsExternalLoginOnly ? ExternalProviders?.SingleOrDefault()?.AuthenticationScheme : null;`

**Comment by brockallen** [comment]
I made this change on the dev branch, so it'll get picked up in the next patch. I'll close this for now. If you feel another change is more appropriate, then let us know. Thanks.

**Comment by markgmarkg** [comment]
Cool. It looks pretty much defensive now :)
