### ISSUE TITLE
Single Sign ON while on multiple tab contains login screen

### ISSUE THREAD

**Issue by IncRev-Bala** [IdentityServer/IdentityServer4#1871]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

@brockallen  I opened Gmail in multiple tab and tried to logout, after that every screen redirects me to login screen which prompt me to enter password to login again. I gave password in one tab, rest of the tabs redirects to the Gmail instead of User Credential. How could I implement the same in Identity Server.

Login to any of the configured application, and duplicate the URL in multiple tabs and logout in one tab immediately rest of the tabs redirects to the login (I configured the application to go to the Login once logout happened). Now all the tabs seeking user credential to login.

If I logged-in one tab automatically rest of the tabs need to redirect to the appropriate application based on that logged-in user.

> Note: In the default login view we don't have any iFrame to get update of session status.

Kindly assist me.

**Comment by leastprivilege** [comment]
Check the OpenID Connect session management spec.

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by IncRev-Bala** [comment]
Thanks for your immediate reply. I tried your sample application, I go through-ed most of the sites. But I failed to find the solution. If we are in Login screen, all the tabs not logging in to site only the respective tab redirects after the successful login.
