### ISSUE TITLE
Login issue in multiple tab contains login screen

### ISSUE THREAD

**Issue by IncRev-Bala** [IdentityServer/IdentityServer4#1872]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem

@brockallen  I'm using React Redux UI (OIDC middleware) application and service side C# .Net along with Identity Server.

Login to any of the configured application, and duplicate the URL in multiple tabs and logout in one tab immediately rest of the tabs redirects to the login (I configured the application to go to the Login once logout happened). Now all the tabs seeking user credential to login.

Now I tried to login using appropriate user credential in each and every tab, all the tabs performing the successful login. Then it will redirect to the client callback URL which was already specified

Some of the tabs fails to get the User information from the OIDC-Redux store, I debugged the code it comes as undefined. (Only in some tabs not in all the tabs).

In the client side I'm using 

`import { createUserManager } from 'redux-oidc';`

**SuccessCallback**:

```
if (this.props.user && this.props.user.profile && this.props.user.profile.Username) {
   // Navigate to appropriate view
} else {
    // trigger to logout
}
```
I'm getting `this.props.user` as undefined so I tried to the User from the UserManager

```
userManager.getUser().then(function (user) {
   // User is coming as Undefined only on some tabs, even the Successful login
});
```
But this also fails. What we need to do even the Identity Server returns successful login but in client it fails only in some tab (Multiple tab gets login in the same browser)

Kindly assist me.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
