### ISSUE TITLE
Quickstarts and .NET targeting.

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#1876]
Hello, I noticed the [implicit flow quickstart for identity server 4](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/3_ImplicitFlowAuthentication/src/QuickstartIdentityServer) target's netcoreapp. When I right click the project in VS 2017 Pro and click NuGet I searched for ITfoxtec.Identity.Saml2 and clicked "Install" then I get this error:

`Package ITfoxtec.Identity.Saml2 2.0.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package ITfoxtec.Identity.Saml2 2.0.0 supports: net462 (.NETFramework,Version=v4.6.2)`

- Why does the quickstart target netcoreapp2.0?
- Why does NuGet show packages for this project that I am not even allowed to install? 
- What is the best way around this? Should I create my own library that targets stnadard or 461 and make an API that sort of wraps ITfoxtec so it can be consumed by projects that target netcoreapp? Or am I better off changing IdentityServer4 core app to target standard?

The new .NET stuff is very confusing and the tooling seems like it just isn't quite there yet.

**Comment by brockallen** [comment]
> ITfoxtec.Identity.Saml2

No idea what package that it. You should contact their author.

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
