### ISSUE TITLE
Allow programmatic access to APIs to users

### ISSUE THREAD

**Issue by hnafar** [IdentityServer/IdentityServer4#1877]
What is the correct way to provide users with programmatic access to APIs?

I have an application composed of many services (all trusted services, within the same domain, not external applications), and identity service in the same domain.
I would like to allow a user to user a set of credentials to gain access to any of the APIs I provide.

Is it reasonable to think of a user as a client in this case, and use clientCredentials flow to get a token that will be passed to the target API? specifically, is it a good idea automatically assign a clientId and a clientSecret to every user in my system, and allow all users to use clientCredentials flow to request an access token? the access token would then contain all user's claims. If this is a reasonable approach, is there any way to remove the "client_" prefix from the added claims? or is that a bad idea?

**Comment by TomCJones** [comment]
use Kerberos, that's what it is designed for

**Comment by hnafar** [comment]
@TomCJones I would rather not.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
