### ISSUE TITLE
IdentityServerBuilder unnecessarily created twice

### ISSUE THREAD

**Issue by DavidNorena** [IdentityServer/IdentityServer4#1882]
Hi I was looking the code and I wonder why you create IdentityServerBuilder twice ? 
Why don't return the first one ?

Thanks,

### Issue / Steps to reproduce the problem

[here](https://github.com/IdentityServer/IdentityServer4/blob/d23b5b31080588b02b43f69dcd782b3e9cd489fb/src/IdentityServer4/Configuration/DependencyInjection/IdentityServerServiceCollectionExtensions.cs#L36)
[here](https://github.com/IdentityServer/IdentityServer4/blob/d23b5b31080588b02b43f69dcd782b3e9cd489fb/src/IdentityServer4/Configuration/DependencyInjection/IdentityServerServiceCollectionExtensions.cs#L52)

### Relevant parts of the log file

```
No log
```

**Comment by leastprivilege** [comment]
You are right. Want to fix it? Thanks

**Comment by DavidNorena** [comment]
Cool, next time I'll help with PR Directly ! Thanks guys !

**Comment by brockallen** [comment]
Yea, no worries -- someone else go to it.
