### ISSUE TITLE
can this keep going be IdentityServer4.saas?

### ISSUE THREAD

**Issue by seven1986** [IdentityServer/IdentityServer4#1883]
I just make a simple design, can this keep going for mutitenancy?
![ids4saas](https://user-images.githubusercontent.com/20808494/34067511-c2438078-e262-11e7-9637-4776f6c29874.jpg)

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
