### ISSUE TITLE
Rewrite logging and events

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1884]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/loggermessage

...relates to redacting logs etc..

**Comment by brockallen** [comment]
Perhaps to replace events?

**Comment by leastprivilege** [comment]
see also 

https://github.com/IdentityServer/IdentityServer4/issues/1931

**Comment by brockallen** [comment]
Beef up runtime logging/events

**Comment by brockallen** [comment]
Include this: #1809

**Comment by mcintyre321** [comment]
I've managed to hack some custom redaction in via reflection, by adding a key to the static TokenRequestValidationLog.SensitiveValues field:

```
            var logType = typeof(IdentityServer4.IdentityServerTools).Assembly.GetType("IdentityServer4.Logging.Models.TokenRequestValidationLog");
            var fieldInfo = logType.GetField("SensitiveValuesFilter", BindingFlags.Static | BindingFlags.NonPublic);
            string[] sensitiveValues = (string[] )fieldInfo.GetValue(null);
            sensitiveValues = sensitiveValues.Concat(new []{"ticket"}).ToArray();
            fieldInfo.SetValue(null, sensitiveValues);
```

Could we perhaps have this exposed via a SensitiveValues object in the container, or similar?

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/3055

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/3356

**Comment by leastprivilege** [comment]
tracked here: https://github.com/IdentityServer/IdentityServer4/issues/3518
