### ISSUE TITLE
Identity Server 3 Cookie Truncation Issue

### ISSUE THREAD

**Issue by krotkiske** [IdentityServer/IdentityServer4#1887]
Sorry for posting here identity 3 repo would let me post there as it is archived. Our identity server 3 implementation reports an error periodically that the cookie we set in our MVC client has been truncated. Would anyone know why this occurs? What would I need to provide to you to help troubleshoot this issue?

Thanks

**Comment by brockallen** [comment]
That repo was closed because it is no longer maintained as FOSS. If you require commercial support, please see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

This repo is for IdentityServer4 only.
