### ISSUE TITLE
Best way to define Client to be used with localhost vs domain

### ISSUE THREAD

**Issue by AleksandrAlbert** [IdentityServer/IdentityServer4#1888]
Hey, so I got my Identity Server project up and running, and am setting up my project to publish. Now, when I define my client in the config for IS4, I suppose I will have to set my redirect urls to my publish domain, something like this:
```
new Client{
    ...
    RedirectUris = { "localhost:5002/signin-oidc", "myclient.com/signin-oidc" }
    ...
}
```
Is including the localhost and domain the right way to do this? I am thinking it would be ok since an attacker would have to have my client secret in order to login. Or is it better to set up two separate clients (eg. 'client' and 'client_local'), and request the appropriate client at startup?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
