### ISSUE TITLE
Removed unauthenticated user handling in AuthorizeCallback

### ISSUE THREAD

**Issue by dhjf** [IdentityServer/IdentityServer4#1890]
Hi

After updating IS4 from 1.5.1 to 2.0.5 we discovered that request to /authorize/callback without an authenticated user does not redirect to an error page anymore, but rather returns a 200 with { "Code" : null } as content. 
The code that handled the situation with an error page was removed earlier in this change:

https://github.com/IdentityServer/IdentityServer4/commit/bfae2858aa01174d938c84f0871bb7b15786bd63#diff-347b430cd7e23b15aac73273fe69e036

More specifically:
```
var user = await _userSession.GetIdentityServerUserAsync();		
if (user == null)		
{		
   return await CreateErrorResultAsync("User is not authenticated");		
}
```

Is returning a null code really the desired way to handle this?

**Comment by brockallen** [comment]
> request to /authorize/callback without an authenticated user does not redirect to an error page anymore, but rather returns a 200 with { "Code" : null } as content.

I don't see that behavior. I see the user is redirected back to the login page.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
