### ISSUE TITLE
Why does the QuickStart5_Hybrid example trigger a call to /userinfo without the need for a ProfileService? Why does asking for scope email stop triggering the call to /userinfo and start requiring a ProfileService?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#1891]
Launch the QuickStart5, login with alice/password and notice that a call went out to /userinfo.

Now add `options.Scope.Add("email");` to your client. also add a new IdentityResource (`IdentityResources.Email()`) to your Identity Server and allowed scopes. Notice a call does not go out to /userinfo. To fix this, add a profile service.

I did not see this in the docs. What exactly determines the automatic fetch over to /userinfo? How can userinfo work without an existing profile service?

**Comment by brockallen** [comment]
You should read the Microsoft code for the OpenID Connect authentication handler.

**Comment by VictorioBerra** [comment]
According to the [code in the OpenIdConnectHandler](https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L694) if you set GetClaimsFromUserInfoEndpoint to true, it will always make the call. It turns out the Application Insights log has been truncating data from my view `Too much data was sent during this period and being removed for debugger responsiveness.`. When I look in ASP.NET Core Web Server output I see the calls.

If anyone sees this, there is a hidden [TestUserProfileService inside IdentityServer](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Test/TestUserProfileService.cs) that is registered by the AddTestUsers IIdentityServerBuilder extension method.

**Comment by brockallen** [comment]
> According to the code in the OpenIdConnectHandler if you set GetClaimsFromUserInfoEndpoint to true, it will always make the call

Presumably only if you have an access token.

So sounds like you're all sorted and we can close this. If not, feel free to reopen.
