### ISSUE TITLE
ASP.Net Core User Is null

### ISSUE THREAD

**Issue by STRATZ-Ken** [IdentityServer/IdentityServer4#1892]
https://stackoverflow.com/questions/47860774/c-sharp-net-core-asp-net-api-user-is-null

I hate to create github issues to bring attention, but I have been stumped on this for about 4 days now and I can't seem to bring attention on StackOverflow.  I have never seen such a thing.  All logs are on the link.

Thanks,

**Comment by brockallen** [comment]
Sorry -- This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
