### ISSUE TITLE
Obsolete method being used in the quickstarts

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#1895]
in the POST Logout action method in the Account controller there is this call:
`
await _events.RaiseAsync(new UserLogoutSuccessEvent(user.GetSubjectId(), user.GetName()));`

Visual studio says `user.GetName()` is obsolete. What should I replace this with? Should I manually find the name in the claims?

**Comment by brockallen** [comment]
There's a replacement, but I can't recall it off the top of my head. @leastprivilege added it recently.

**Comment by leastprivilege** [comment]
There is an updated version of that

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/798b3b6ac869e3dd6dc2a497898828a24e0c5164/Quickstart/Account/AccountController.cs#L319

**Comment by VictorioBerra** [comment]
What is the difference between IdentityServer4.Quickstart.UI and using the UI in one of the samples at IdentityServer4.Samples? Is it just more consolidated?

**Comment by leastprivilege** [comment]
the samples don't contain a token service - so we don't use the QS.UI - or am I wrong?
