### ISSUE TITLE
Question: Does IdentityServer4 implement User caching by default

### ISSUE THREAD

**Issue by reeceengle** [IdentityServer/IdentityServer4#1896]
### Issue / Steps to reproduce the problem
So I am updating user passwords in the user table via SQL and the password is being updated fine.  However, I am seeing some weird functionality in my production load-balanced environment where it seems like one server will recognize the password change, and the other server will update the password hash and grant a token.  

Whenever I run things locally, I can see things working. 

However I'm just not sure what mechanisms are in the UserStore by default.

I am a little stumped and hesitant to move forward.  My main question is, is there any user caching that runs by default that I may be able to turn off?

**Comment by brockallen** [comment]
Anything related to users is in your code, not within IdentityServer.
