### ISSUE TITLE
Add more fields to InputLengthRestrictions

### ISSUE THREAD

**Issue by PivotalAnimal** [IdentityServer/IdentityServer4#190]
I am creating an _EF_ solution and plan to use _IdentityServerOptions.InputLengthRestricitons_ to limit the length of fields in _OnModelCreating_. Could properties be added to InputLengthRestrictions for Client.ClientName, Client.ClientUri, ClientClaim.Type, ClientClaim.Value, ClientCorsOrigin.Origin, etc. I think consistency across implementations would be ideal. Adding these options would also likely offer more security and stability. On the other hand, it seems there is not much mention in the rfc as to what the lengths of strings should be. It is somewhat arbitrary. But things like URL should have some kind of limit. [https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore/blob/master/BlueConcord.IdentityServer.EntityFrameworkCore/EfConstants.cs#L12](https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore/blob/master/BlueConcord.IdentityServer.EntityFrameworkCore/EfConstants.cs#L12)
[https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore/blob/master/BlueConcord.IdentityServer.EntityFrameworkCore/DbContexts/ClientConfigurationContext.cs#L43](https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore/blob/master/BlueConcord.IdentityServer.EntityFrameworkCore/DbContexts/ClientConfigurationContext.cs#L43)

**Comment by brockallen** [comment]
We can look into how this might work. No promises though.

**Comment by leastprivilege** [comment]
Not planning to do anything here for RTM - still an issue? or more thoughts?

closing for now - feel free to re-open

**Comment by PivotalAnimal** [comment]
No issue here. I will likely use the official EF package and create a new library that references it for any mgmt additions. Need to spend time on this. Thanks!
