### ISSUE TITLE
Proposal: Always Allow CORS on .well-known

### ISSUE THREAD

**Issue by glatzert** [IdentityServer/IdentityServer4#1901]
I propose, that IDServer has a configuration Switch, which makes it allow any origin for metadata-related requests.

I'd also happily provide some of my time, to implement that Change and provide it as PR.

**Comment by brockallen** [comment]
Why would you special case that endpoint only? Why does the current CORS config not work for your scenario?

**Comment by glatzert** [comment]
I might have had a small confusion this morning, about how you generate the list of allowed origins (with EF). There's the ClientCorsOrigins and I needed some time to wrap my head around how you would detect the Client, when I access the Metadata.

Meanwhile I realized - you don't.
While the CORS Origin list is associated with the client, the evaluation isn't.
That was making it hard to grasp.

Probably everything is cozy and nice, if I start by adding the client ...
I'll close this.

BTW: #1490 also seems to be a 👍 idea
