### ISSUE TITLE
Proposal: Revoking all tokens in revocation endpoint.

### ISSUE THREAD

**Issue by haquex19** [IdentityServer/IdentityServer4#1902]
I'll start out by trying to describe a scenario. User A wants to log into a web application. The user logs into this application using a desktop browser. A token and refresh token is generated for this login and is stored in the data store configured for idsvr4. The user then logs into this application using a mobile device. Another token and refresh token is generated for that login and is also stored in that data store. The application wants to provide the user to log out, or log out from all devices. (These tokens are reference tokens). When a log out occurs, the token is removed from the data store.

Idsvr4 doesn't allow us to accomplish this in an easy way. We can revoke an access token in the revocation endpoint which is visible here:

```csharp
if (token.ClientId == validationResult.Client.ClientId)
{
    Logger.LogDebug("Access token revoked");
    await ReferenceTokenStore.RemoveReferenceTokenAsync(validationResult.Token);
}
```
line 111, IdentityServer4.ResponseHandling.TokenRevocationResponseGenerator.cs

We are also able to revoke a refresh token the same way. However, it seems all the reference tokens are also intended to be removed:

```csharp
if (token.ClientId == validationResult.Client.ClientId)
{
    Logger.LogDebug("Refresh token revoked");
    await RefreshTokenStore.RemoveRefreshTokenAsync(validationResult.Token);
    await ReferenceTokenStore.RemoveReferenceTokensAsync(token.SubjectId, token.ClientId);
}
```
line 136, IdentityServer4.ResponseHandling.TokenRevocationResponseGenerator.cs

I'm confused why `await ReferenceTokenStore.RemoveReferenceTokensAsync(token.SubjectId, token.ClientId);` is being called. By the method name and description, it implies to me that only that refresh token is revoked and has nothing to do with reference tokens. Am I incorrect in thinking this?

Finally on to my proposal. Also have a way where we can revoke all refresh tokens and reference tokens, to mimic the behavior of "logout of all devices". Keep in mind I'm still relatively new to idsvr4 and there might already be a way of accomplishing this.

Any thoughts on the proposal and my confusion on the revoking of a refresh token?

**Comment by brockallen** [comment]
The `IIdentityServerInteractionService` has some APIs for some of these things: http://docs.identityserver.io/en/release/reference/interactionservice.html

If you want an admin style (meaning for other users), then you'd need to use the `IPersistedGrantService` directly.

**Comment by brockallen** [comment]
Our token revocation endpoint implements the RFC. If you want your own custom revocation endpoint, then you are free to do that: http://docs.identityserver.io/en/release/topics/add_apis.html
