### ISSUE TITLE
Is it okay to access the httpcontext inside the ProfileService?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#1907]
We are not going to use a userStore. We are using ComponentSpace SAML2 library as an external identity provider and we are going to include all attributes needed from our side (shibboleth) including some active directory roles which then get mapped to claims and saved to session cookie during SignInAsyc().

Right now we successfully have authentication working and implicit/hybrid clients working. I have created this service:

```
        public PROFILESERVICETEST(Microsoft.AspNetCore.Http.IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }

        public Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var claims = _httpContextAccessor.HttpContext.User.Claims;

            if (context.RequestedClaimTypes != null)
            {
                var requestedClaims = claims.Where(x => context.RequestedClaimTypes.Contains(x.Type)).ToList(); ;
                context.IssuedClaims = requestedClaims;
            }

            context.IssuedClaims.Add(new System.Security.Claims.Claim("email", claims.First(x => x.Type == IdentityModel.JwtClaimTypes.Email).Value));
            return Task.CompletedTask;
        }
```

As you can see, we dig into the currently logged in users claims to provide the requested data back to the caller. Is this faulty in any way? I know it is not extensible. We do not expect the claims payload to ever get too big. We may need to hit the Db to check `IsActiveAsync` however.

Thanks,
Tory

**Comment by leastprivilege** [comment]
Sure - but context.Subject has the same info.

that being said - 

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
