### ISSUE TITLE
Support external SAML2-P providers

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1909]
In `AccountController` carry over a property for SAML from temp cookie into main cookie.

**Comment by brockallen** [comment]
Also refactor the callback code.

**Comment by brockallen** [comment]
Stop rendering the `<html>` in `AuthenticationRequestHandlerWrapper` (IOW, merge our iframe into any rendered html)

**Comment by brockallen** [comment]
`html` and `body` tags are no longer being rendered around the `iframe` in the federated signout handling code.

**Comment by brockallen** [comment]
I've also done some consolidation and cleanup in the AccountController. HTH @AndersAbel

**Comment by leastprivilege** [comment]
@AndersAbel happy?
