### ISSUE TITLE
[AuthorizeAttribute (Roles="")] doesn't work

### ISSUE THREAD

**Issue by hequs** [IdentityServer/IdentityServer4#191]
I use IdentyServer4 (beta3) for handling an authorization process on my SPA. The solution contains 3 separate projects: Spa, Api and IdentityServer (IS). 

The flow is the following: the user enters SPA, then he is redirected to the IS login page; once authenticated he is redirected back to the SPA.

Api is configured to use Jwt Tokens, issued by an IdentityServer, the following way:
```cs
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
app.UseJwtBearerAuthentication(new JwtBearerOptions
{
    Authority = <IdentityServer url>,
    Audience = <IdentityServer url> + "/resources",
    AutomaticAuthenticate = true,
    AuthenticationScheme = "Bearer",
    RequireHttpsMetadata = false,
    AutomaticChallenge = true
});
```

AuthorizeAttribute itself (without role validation) works properly, but requests to API methods protected with (Roles="") always return 403, besides JWT token contains all the claims, provided by an Asp.Net Identity (I overrided UserClaimsPrincipalFactory and IProfileService), namely, "sub", "name", "AspNet.Identity.SecurityStamp", "role".

**Comment by ariesdane** [comment]
Try setting the RoleClaimType = "role", and if User.Identity.Name is also empty, then set NameClaimType = "name".

**Comment by brockallen** [comment]
@hequs did @ariesdane's suggestion work for you?

**Comment by Simply-Awesome** [comment]
I have a similar issue where claims of type role (and their values) are not being returned.

When I use Id4 beta 5, and the Resource Scope is configured as:

                new Scope
                {
                    Name = "api1",
                    DisplayName = "API 1",
                    Description = "API 1 features and data",
                    Type = ScopeType.Resource,
                    //IncludeAllClaimsForUser = true,
                    Claims = new List<ScopeClaim>
                    {
                        new ScopeClaim("role")
                    }
                }

The role claims ARE returned (or available) at my Resource "api1". 

When I use Id4, with the same scope configuration, on one of the later builds (after beta 5) on Git; role claims are NOT returned. So if I were to log in with "alice", I expect to see 2 role claims. One "Admin" and the other "Geek". However, all I see is a single role claim of type "some_role"

**Comment by leastprivilege** [comment]
@Simply-Awesome open a new issue - some behavior has changed in beta5

**Comment by leastprivilege** [comment]
I assume the OP problem is solved.
