### ISSUE TITLE
System.Net.Http.WinHttpException: A security error occurred

### ISSUE THREAD

**Issue by Exocomp** [IdentityServer/IdentityServer4#1911]
I'd appreciate if I can get some help with this issue, I'm getting error "System.Net.Http.WinHttpException: A security error occurred" on the first request to app that is using server identity 4.

The app is onboarded like the following:

```
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
{
	Authority = appSettings.Value.Authority,
	RequireHttpsMetadata = true,
	AllowedScopes =
	{
		"projectxyz.finance.api1.read_only",
		"projectxyz.finance.api1.full_access",
	}
});
```

When I make a request to the app I get the following error:

```
System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://www.server.com/identity/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'https://www.server.com/identity/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: A security error occurred
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

This error only occurs on the first request when the app starts, if I wait about 3 minutes after the first request or so and try again then it works just fine.  I enabled debug level but the above is the best message I get.

Doing some research on this error it appears it occurs whenever there is an SSL error but in my case since it only occurs on the first request it rules out most issues.  Any suggestions or ideas on how I can troubleshoot this issue ?

**Comment by TomCJones** [comment]
Sounds like a timing problem. Easy to check. Just put that address in a browser and make the first call from it.

**Comment by Exocomp** [comment]
I tried the following:

1) First open a browser and go to https://www.server.com/identity/.well-known/openid-configuration
    This works fine

2) Restart the app and make a request to it
    I still get the error

3) Wait a bit and try step 2 again
    This time it works    

I guess it only happens when the app does a server side call to identity server.  I'm not sure if it is a cipher issue or protocol issue (TLS 1.0, 1.1, 1.2, etc), like somehow it fails on the first request and then waiting and try again picks a different cipher/protocol ?? could something like that be happening ?

**Comment by TomCJones** [comment]
I meant for you to try it with out restarting the app. I would guess some process is on demand start or whatever your os calls that.

**Comment by Exocomp** [comment]
I removed the explicit TLS ciphers defined on the server and that resolved the issue so I think my hunch was right, although not sure if that ends up changing something else that then makes it work with .net core. hmm.

**Comment by Exocomp** [comment]
Resolved, it was the ciphers, the Get-TlsCipherSuite powershell cmdlet came in handy.  Merry Christmas!

**Comment by haquex19** [comment]
I apologize for commenting on this two month old issue, but I am also experiencing this issue. When working locally in debug, all works fine. We are using azure to host the identity server. After deploying to azure, the first call always fails with the security error exception. All subsequent calls work well. Is it possible you can explain in a little more detail what was done to the ciphers to make it work?
