### ISSUE TITLE
iFrame , Object Refused to display in a frame because an ancestor violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by callranjithkani** [IdentityServer/IdentityServer4#1915]
Please include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

### Issue / Steps to reproduce the problem

Hi,

 I have sso implemented solution

i have deployed my **SSO Proxy** : http://192.168.20.6:4001
**Cllient 1** : http://192.168.20.6:5003
**Client  2** : http://192.168.20.6:5004

I want to populate Client1 content to client2 page using iframe , i got an error

**Error:**
Refused to display 'http://192.168.20.6:4001/connect/authorize/consent?client_id=TPReportaldevnew&redirect_uri=http%3A%2F%2F192.168.20.6%3A5003%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile%20apiportal%20offline_access&response_mode=form_post&nonce=636499494174626408.MTEzZTNkOWItMDE2My00MjRmLWI0NzctMGI1MmEyMGQwYmZhMTkyMmUxZjItNTAwYS00ZjUwLTliYTgtNmZiMzgyM2JiZDZl&state=CfDJ8HGMDUK8EWFBjE_N445h-ym4H8l1nqYiAZcPVQk-g7xYRGtVxXChpeeV0aof0ObQ-oYKFHRthqXn2TnDQdroIJq2IcFidTlmMeB2qS5et3P1TWIKVWbffvllicduFqSxYqAW3VeBk-gep-5F9bmy5d-VrNh3VJwS4-AmKEQxA6IF17awwEDFiSeXgUiorAYR2BCJ7AGgeQubzbDe0pAjhjVFzJQPT1YJYJ5wym8JxjIBRbi_N687dA-xkNW_FaWOf4up3eCnjBVrakKBToGhns0jB9Fx1PwiZG_JpnOEhUTXBWqLZTkyDOwKW216rw1Lh0UwsEZKaBEGdpPZUx8pYR8fjED-B7An_XyKpnPh1lOj' in a frame because an ancestor violates the following **Content Security Policy directive: "frame-ancestors** http://192.168.20.6:5003".

but once i hit **client1** in another tab **"http://192.168.20.6:5003"** and refresh **client2** **"http://192.168.20.6:5004"** working fine. please let me know the perfect solution

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
So client1 wants to show an iframe to client2, and client2 starts the login workflow? Is that when this happens?

**Comment by callranjithkani** [comment]
Yes, client1 wants to show an iframe to client2. yes client2 already logged in via SSO Proxy : http://192.168.20.6:4001
,
Please refer screen shot:


![image](https://user-images.githubusercontent.com/29392902/34400852-8fd1bb34-ebbb-11e7-9813-2a607714c104.png)

**Comment by brockallen** [comment]
This requires discussion @leastprivilege

**Comment by brockallen** [comment]
Ok, we will track this issue here: #1955 and we will have a patch for you.

**Comment by tongfei-github** [comment]
I have the same problem.No one answered the question I issued，Can you help me to solve it！？

**Comment by IamTonyZHOU** [comment]
This is their policy, they do not allow launching the share window in a custom modal or an iframe
