### ISSUE TITLE
Add FailureReason to IntrospectionRequestValidationResult

### ISSUE THREAD

**Issue by gaborari** [IdentityServer/IdentityServer4#1916]
I'd like to use the FailureReason in IntrospectionRequestValidationResult as in the previous version - I don't see a property for it, but the IntrospectionRequestValidationFailureReason enum still exists.

**Comment by leastprivilege** [comment]
please elaborate

**Comment by gaborari** [comment]
In 1.5.2 version, the IntrospectionRequestValidationResult class had a property:

_public IntrospectionRequestValidationFailureReason FailureReason { get; set; }_

Which is set by IntrospectionRequestValidator ValidateAsync method when there were errors, like missing token, invalid token, etc.

Currently, in 2.0.5, there is no more FailureReason property in the mentioned response class. As I see, the result contains error message in one case, when the token is missing: "missing_token". In other cases there is no error message and no reason of the error.

Currently, the IntrospectionRequestValidationResult.cs contains an enumeration called IntrospectionRequestValidationFailureReason, which was the type of FailureReason property in 1.5.2.

**Comment by leastprivilege** [comment]
and how do you want to use that?

**Comment by leastprivilege** [comment]
OK - I am still missing the big picture. Care to explain?

**Comment by leastprivilege** [comment]
Sorry - can you explain what exactly you want to do? And which solution propose?

**Comment by brockallen** [comment]
Any further input, @gaborari? If not, we can't consider this request and we'll end up closing the issue.

**Comment by gaborari** [comment]
Sorry for the late response!
@leastprivilege Now if the token exists in the request but the validation not succeded, the result contains no error (IsError = false, IsActive = false).
 For testing purposes as well, relying on the IsError and FailureReason properties was clear and simple.
In my case, I've added extra validation according to the claims if there was no error (when custom validation resulted error, set the FailureReason to InvalidToken value).

So I'm suggesting that, in the first case, when the token is missing, set the FailureReason (or the Error) as follows:

```
// retrieve required token
var token = parameters.Get("token");
if (token == null)
{
    _logger.LogError("Token is missing");

    return new IntrospectionRequestValidationResult
    {
         IsError = true,
         Api = api,
         Error = "Missing token",
         FailureReason = IntrospectionRequestValidationFailureReason.MissingToken
      };
}
```

In the second case, when the token exists in the request, but not valid or other error:
Set the IsError prop to true, and fill the FailureReason property with MissingToken value (or the Error property with a "Missing token"):

```
            // validate token
            var tokenValidationResult = await _tokenValidator.ValidateAccessTokenAsync(token);

            // invalid or unknown token
            if (tokenValidationResult.IsError)
            {
                _logger.LogDebug("Token is invalid.");

                return new IntrospectionRequestValidationResult
                {
                    IsError = true,
                    Token = token,
                    Api = api,
                    FailureReason = IntrospectionRequestValidationFailureReason.InvalidToken,
                    Error = "Invalid token"
                };
            }

```

As I see now, I think filling the Error (string) property could be better, especially in my case, if the requirements are changing, the error message can easily changed and can be tested easily as well.

**Comment by leastprivilege** [comment]
OK - send a PR please.

**Comment by gaborari** [comment]
OK, I try to get it done as soon as possible.

**Comment by Nymdrood** [comment]
Hi i searched  other issues and i think that my issue was related to this topic.

When i forgot access token in Bearer Authentication using javascript im getting 
500 - Internal Server Error

Header:
Authentication: Bearer undefined   

If i create any request with that header im getting an Internal. 

You can also check this with Postman 
Select authentication as Bearer and write undefined to token area. I think there is something missing.

**Comment by brockallen** [comment]
@gaborari -- did you do a PR for this?
