### ISSUE TITLE
Get Clients and Resource from existing tables

### ISSUE THREAD

**Issue by elnurvl** [IdentityServer/IdentityServer4#1917]
I have Clients and Company tables. I need to load IdentityServer clients and resources from these tables: ClientId comes from Client table, secret and scope come from Company table; all resource infos come from Company table. What pattern should I follow?

Thanks.

**Comment by leastprivilege** [comment]
You can plugin your own persistence by implementing `IClientStore` and `IResourceStore`.

**Comment by elnurvl** [comment]
Thank you for an answer. I am new on this framework, so I need a bit more detailed answer. Is there any documentation/tutorial on this subject?

**Comment by leastprivilege** [comment]
start here

http://docs.identityserver.io/en/release/topics/clients.html?highlight=IClientStore
http://docs.identityserver.io/en/release/topics/startup.html?highlight=IClientStore

**Comment by elnurvl** [comment]
Sorry, I have read those documents again, but unfortunately could not find a section about other implementations of IClientStore. Only in-memory configurations are demonstrated.
