### ISSUE TITLE
(Question) IS4 with webforms & multi-tenanted environment

### ISSUE THREAD

**Issue by Workshop2** [IdentityServer/IdentityServer4#1918]
We are a new tech team that has inherited a webforms app. We are planning on building out an internal API and would like some guidance for implementing it with our existing app.

Ideally we would like an independent app hosting the identity server, and both internal APIs and webform app would call it. However, we host hundreds of websites on a single platform in a multi-tenanted setup.

Can we use IS4 with webforms? 
Can you give some guidance around multi-tenanted setups?
Have I missed anything obvious?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by Workshop2** [comment]
Sorry about that.
