### ISSUE TITLE
Add a public constructor or factory for AuthorizationRequest for testing

### ISSUE THREAD

**Issue by tillig** [IdentityServer/IdentityServer4#192]
I'm trying to test my host controllers - specifically my login controller - and ran into an issue with trying to mock `IUserInteractionService.GetLoginContextAsync()`. ([Here's where the sample host login controller calls it.](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Host/UI/Login/LoginController.cs#L34)) I can't mock the return value of `AuthorizationContext` [because there's no public constructor](https://github.com/IdentityServer/IdentityServer4/blob/20e9ef9d3834cbbcd093abf235ef278fb15a4ba9/src/IdentityServer4/Models/Messages/AuthorizationRequest.cs), so frameworks like Moq that use dynamic proxying can't instantiate it. There also doesn't seem to be a static factory or anything where I can somehow create one.

Can a public constructor be added or possibly a static factory method that could be called to (basically) "new up" one of these so testing can happen?

**Comment by brockallen** [comment]
Yep, I can look into it.

**Comment by brockallen** [comment]
Done.
