### ISSUE TITLE
Validation of identity token dosen't validates its expiration date

### ISSUE THREAD

**Issue by efilv** [IdentityServer/IdentityServer4#1920]
Hi,

I want to validate the identity token at client level.
So I used to following link:

https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/MvcManual/Controllers/HomeController.cs

I found out that it dosent validate the expiration date of the token.
I tried to add the TokenValidationParameters object some flags, but no one of them validated the expiration date of the token (such as ValidateLifetime).

Am I missing something?

Thanks,
Efi.

**Comment by brockallen** [comment]
> Am I missing something?

Perhaps the pre-configured 5-minute clock skew of the JwtSecurityTokenHandler.

**Comment by efilv** [comment]
Yes.
That's why.

I have another question and I hope you will help me.
I configured my client's TokenValidationParameters and set the ClockSkew to 0.
But still when I call the UserInfoEndpoint it still wait 5 minutes before it validates the expiration date.

This is how i configured it:
```
options.TokenValidationParameters = new TokenValidationParameters
{
    NameClaimType = "name",
    RoleClaimType = "role",
    ValidateIssuer = true,
    ValidateLifetime = true,
    ValidateIssuerSigningKey = true,
    ClockSkew = new TimeSpan(0, 0, 0)
};
```

Thank you,
Efi.

**Comment by brockallen** [comment]
We don't do general Q&A on the issue tracker -- only bug reports or issues.

Please use one of the our free or commercial support options for Q&A

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
