### ISSUE TITLE
Already has error "invalid_grant" on ResourceOwnerPasswordValidationContext result before authentication

### ISSUE THREAD

**Issue by stt106** [IdentityServer/IdentityServer4#1921]
### Issue / Steps to reproduce the problem
I am using ResourceOwnerPassword grant as I want users to log in directly from Angular SPA client rather having to redirect to another log in page. In my IResourceOwnerPasswordValidator implementation, not sure why ResourceOwnerPasswordValidationContext.Result already has errored with **"invalid_grant"** even before any credenticals check logic begins:
![is_error_invalid_grant](https://user-images.githubusercontent.com/10818648/34388818-e0344940-eb2d-11e7-9991-93e5d03f291e.png)

In the log, it just says "User authentication failed: Invalid username or password" which I don't think is the real error; invalid_grant is definitely a more serious error.

Below is the code that is relevant:

The client:
```
 private IEnumerable<Client> GetClients(ICollection<string> allowedCorsOrigins)
        {
            return new List<Client>
            {
                new Client
                {
                    ClientId = "web-badders-rank",
                    ClientName = "Badders Rank Web Client",
                    ClientSecrets = {new Secret("secret".Sha256())},
                    //AccessTokenType = AccessTokenType.Reference,
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
                    AllowAccessTokensViaBrowser = true,
                    AccessTokenLifetime = 3600 * 24 * 10, // 10 days
                    IdentityTokenLifetime = 3600 * 24 * 10, // 10 days
                    // AllowedCorsOrigins = allowedCorsOrigins,
                    //AlwaysIncludeUserClaimsInIdToken = true,
                    //RequireConsent = false,
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "badders-rank-api"
                    }
                }
            };
        }

  ```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();
            services.AddMemoryCache();
            services.Configure<BadderRankConfiguration>(Configuration.GetSection("DataBase"));

            services.AddMvcCore()
                    .AddJsonFormatters();
             services.AddScoped(typeof(IPlayerRepository), typeof(PlayerRepository));
            services.AddScoped(typeof(IGroupRepository), typeof(GroupRepository));

            services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();
            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                //.AddInMemoryPersistedGrants()
                .AddInMemoryApiResources(GetApiResources())
                //.AddInMemoryIdentityResources(GetIdentityResources())
                .AddInMemoryClients(GetClients(new[] { "http://localhost:4200" }))
                //.AddTestUsers(GetTestUsers())
                .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>();
             
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = _authority;
                    options.ApiName = "badders-rank-api";
                    options.RequireHttpsMetadata = false;
                    options.ApiSecret = "secret";
                    options.SupportedTokens = SupportedTokens.Both;
                });

            services.AddCors(option => option.AddPolicy("MyPolicy", builder =>
            {
                builder.AllowAnyOrigin();
            }));   
        }
```

```

### Relevant parts of the log file

```
2017-12-27 17:36:57.698 +00:00 [WRN] CorsPolicyService did not allow origin: http://evil.com/
2017-12-27 17:36:57.700 +00:00 [DBG] Request path /connect/token matched to endpoint type Token
2017-12-27 17:36:57.700 +00:00 [DBG] Endpoint enabled: Token, successfully created handler: IdentityServer4.Endpoints.TokenEndpoint
2017-12-27 17:36:57.701 +00:00 [INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
2017-12-27 17:36:57.702 +00:00 [VRB] Processing token request.
2017-12-27 17:36:57.702 +00:00 [DBG] Start token request.
2017-12-27 17:36:57.702 +00:00 [DBG] Start client validation
2017-12-27 17:36:57.702 +00:00 [DBG] Start parsing Basic Authentication secret
2017-12-27 17:36:57.702 +00:00 [DBG] Parser found secret: BasicAuthenticationSecretParser
2017-12-27 17:36:57.702 +00:00 [DBG] Secret id found: web-badders-rank
2017-12-27 17:36:57.702 +00:00 [DBG] Secret validator success: HashedSharedSecretValidator
2017-12-27 17:36:57.702 +00:00 [DBG] Client validation success
2017-12-27 17:36:57.702 +00:00 [VRB] Calling into token request validator: IdentityServer4.Validation.TokenRequestValidator
2017-12-27 17:36:57.702 +00:00 [DBG] Start token request validation
2017-12-27 17:36:57.702 +00:00 [DBG] Start resource owner password token request validation
2017-12-27 17:38:52.566 +00:00 [ERR] User authentication failed: Invalid username or password
2017-12-27 17:38:52.568 +00:00 [ERR] {
  "ClientId": "web-badders-rank",
  "ClientName": "Badders Rank Web Client",
  "GrantType": "password",
  "Scopes": "badders-rank-api",
  "UserName": "tonysun@gamil.com",
  "Raw": {
    "grant_type": "password",
    "username": "tonysun@gamil.com",
    "password": "***REDACTED***",
    "scope": "badders-rank-api"
  }
}
2017-12-27 17:38:52.569 +00:00 [VRB] Invoking result: IdentityServer4.Endpoints.Results.TokenErrorResult
```

I just checked IdentityServer4 source code and got even more confused why this has happened because in the soruce code below from  `private async Task<TokenRequestValidationResult> ValidateResourceOwnerCredentialRequestAsync(NameValueCollection parameters)` in the **/src/IdentityServer4/Validation/TokenRequestValidator.cs**, clearly `resourceOwnerContext ` is just created and should have no error before it gets passed into `ValidateAsync`, and still in my case `resourceOwnerContext `is already errored before any attempt of authentication.
           
```
            /////////////////////////////////////////////
            // authenticate user
            /////////////////////////////////////////////
            var resourceOwnerContext = new ResourceOwnerPasswordValidationContext
            {
                UserName = userName,
                Password = password,
                Request = _validatedRequest
            };
            await _resourceOwnerValidator.ValidateAsync(resourceOwnerContext);
          // more source code
```

**Comment by farhadbheekoo** [comment]
@stt106 How are you? Did you manage to fix this issue?
