### ISSUE TITLE
Proper Flow for Data Access Authorization

### ISSUE THREAD

**Issue by granthoff1107** [IdentityServer/IdentityServer4#1922]
I have an access token which provides me roles. 
After Validating the token I receive a role "BasicUser"
Based off of the role I want to validate what they are trying to access from my Database

I.E
If you're a basic user and you're trying to view messages sent to not your userId the token would revoke access.

If you are an Admin and you're trying to view messages sent to someone elses user Id, this would be allowed.

Is this a viable usage for Identity Server?
Or is the Identity Provider only to say what I have access to Api Wise
And is not intended for data access authorization?

If so, would there be any down sides to using the token to validate data access authorization?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by GrantHoffman** [comment]
@brockallen This question is not code related, it will not pass review on stackoverflow.  

 I saw in the past you've marked things as questions. Maybe in the older IDSV3.
I was just hoping for a quick yes or no whether this works with the spec?
