### ISSUE TITLE
Will calling AddValidationKey override the key added with AddSigningCredential?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#1923]
I noticed `AddSigningCredential()` calls this:

`builder.Services.AddSingleton<IValidationKeysStore>(new DefaultValidationKeysStore(new[] { credential.Key }));`

and I noticed `AddValidationKeys()` calls this:

`builder.Services.AddSingleton<IValidationKeysStore>(new DefaultValidationKeysStore(keys));`

Calling AddSingleton with the same type will override the provided instance. So does that mean that new credential.Key added with AddSigningCredential will be removed and now the discovery service will stop reporting that key?

**Comment by leastprivilege** [comment]
No the DI supports multiple implementations at the same time.
