### ISSUE TITLE
Question: IdentityServer is completely UserStore-agnostic?

### ISSUE THREAD

**Issue by MV10** [IdentityServer/IdentityServer4#1924]
Is it correct that IdentityServer itself has no dependencies on any user-store implementation? From what I can tell, that's strictly a concern of whatever our project requirements might be (apart from supporting certain minimum concepts; specifically, ensuring we're able to work with a SubjectId, I believe).

I'm working backwards from the QuickStart-UI example and the TestUserStore to build out our own UI and persistence libraries. Our data layers are async but TestUserStore is not, so I wanted to be sure I wouldn't run into problems later if my own user store is async.

**Comment by leastprivilege** [comment]
yes. that's right.
