### ISSUE TITLE
ASP.NET Core data protection re-using persistence stores?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#1926]
[This link](https://identityserver4.readthedocs.io/en/release/topics/deployment.html#asp-net-core-data-protection) says the following:

> You can either re-use one of the above persistence store or use something simple like a shared file if possible.

How can we re-use the configuration store or the operational data store to store data protection keys?

**Comment by leastprivilege** [comment]
Microsoft has some plugins for SQL Server, Blog storage, Redis etc...
