### ISSUE TITLE
Permanent Session - Remember my login - idsrv.session expiration 

### ISSUE THREAD

**Issue by ChristianRiedl** [IdentityServer/IdentityServer4#193]
While in idsrv3 **idrv.session** cookie has an expiration time of approx one month in idsrv4 the cookie expires at the end of the browser session. I guess this is the reason why I am not able to make a permanent session even when "Remember my login" is checked. Is there an intention to change it in future versions ?

**Comment by brockallen** [comment]
Those cookies do different (but related) things, so I'm a little confused by the question. We're still working on some of these parts, so I'm not yet sure what direction we will end up with. Do you have a specific use-case or feature request?

**Comment by ChristianRiedl** [comment]
Thank you for your answer.
My application is not very critical regarding security, and so I currently use an idsrv3 based solution using implicit flow and "Remember my Login" functionality. Now I started to port to idsrv4 and I am afraid my customers will be unhappy when they have to login whenever they start a browser session. 
So I started to analyze the difference between idsrv3 and idsrv4 login flow of http messages and detected that idsrv4.session cookie has only session lifetime. Than I compared idsrv3 and idsrv4 sources and found that this functionality is not available any more (or not until now) in idsrv4. "Remember me" checkbox is ignored. Can you tell me if it is planned to support it in future versions ? If not, can you give me a hint how I can add this functionality ?
Of course I can tinker some cookie storage logic, but I want to do it in an OIDC compliant way.       
I searched in the OpenID connect specs, but got no answer for my problem.

**Comment by brockallen** [comment]
In IdSvr4 the entire UI for login will be the responsibility of the developer (you) and not the framework (us). So you can issue your own persistent cookie if you want. If the current UI does not honor the "remember me", then that's a bug in the sample.

**Comment by ChristianRiedl** [comment]
I understand that "remember me" is not really part of the OIDC specs and therefore idsrv4 will not support this functionality (other then idsrv3). So I have the choice to continue using idsrv3 or add the missing functionality on my side. Ok, thanks, I have the info needed to decide.

**Comment by leastprivilege** [comment]
What Brock is saying is - that in idsrv4 we are separating the UI from the protocol bits.

Remember Me is a UI feature. Once we get closer to RTM we will have a standard UI implementation that will support remember me OOB.

**Comment by ChristianRiedl** [comment]
Great to hear, implementing it inside idsrv4 will be a much better solution than tinkering arround !!

**Comment by brockallen** [comment]
I've done some thinking on this... session ID cookie is, in a sense, derived from the authentication cookie, but it's hard to have the session cookie know the options used for the main authentication cookie. We do need 2 cookies, and it's unfortunate that these could get of of sync. I'm wondering if it makes sense to:

1) put the session ID into the properties of the main authentication cookie, and when we need to emit the session ID cookie we read the value from the main authN cookie. if it's absent in the main authN cookie we add it (and re-issue the main authN cookie).

2) have middleware in IdSvr that always emits the session cookie if it's absent on the incoming request. Sort of a self-healing session ID. this way if the main authN cookie changes, we won't get out of sync (or at least we'll correct ourselves the next time a request is made into IdSvr).

**Comment by brockallen** [comment]
Ok, I'll track this here: https://github.com/IdentityServer/IdentityServer4/issues/240
