### ISSUE TITLE
How can I Extend IdentityServer4.EntityFramework.Entities.ApiResource?

### ISSUE THREAD

**Issue by seven1986** [IdentityServer/IdentityServer4#1933]
Could we plus 'Properties' and 'Claims' (same as Client Entity) in IdentityServer4.EntityFramework.Entities.ApiResource？

I think ApiResource can have some properties such as 'swagger.json、server Ip'  or others.
Used for connect ApiManagement.

 Thanks

**Comment by brockallen** [comment]
Done.
