### ISSUE TITLE
Why do third-party claims show LOCAL AUTHORITY as issuer?

### ISSUE THREAD

**Issue by MV10** [IdentityServer/IdentityServer4#1935]
The image below is the claims data persisted after a Google sign-in using a completely clean browser profile (no other cookies etc) and a pretty simple setup with Quickstart UI. Why are most of them issued by LOCAL AUTHORITY? I would have expected all of these to show Google as the issuer.

![1](https://user-images.githubusercontent.com/794270/34487359-fee74d1a-efa1-11e7-9e72-abdec77ecc56.jpg)

**Comment by brockallen** [comment]
Because of how they get copied over. You can change this code if it suits you.

**Comment by MV10** [comment]
Got it. I was confused why just one showed Google, I overlooked the part in the QS auto-provision when the claim type isn't known. Thanks!

```csharp
// copy the claim as-is
else
{
    filtered.Add(claim);
}
```
