### ISSUE TITLE
PersitedGrantStore implemented but log file says I'm still using the in memory version

### ISSUE THREAD

**Issue by sdv-mini-dev-1** [IdentityServer/IdentityServer4#1937]
I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). 

### Issue / Steps to reproduce the problem

I'm new at IdentityServer4. 
I'm using authorization code as grant type and I need to store authorization code and refresh token in the database.
Reading [documentation](https://identityserver4.readthedocs.io/en/release/topics/deployment.html#operational-data) I implemented my custom `PersistedGrantStore` class and in **Startup.cs** in _ConfigureServices_ method I wrote

```
services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddInMemoryClients(Config.GetClients())
                .AddTestUsers(Config.GetUsers())
                .AddOperationalStore();

services.AddMvc();

```
So in **IdentityServerBuilderExtensions.cs**

```
public static IIdentityServerBuilder AddOperationalStore(this IIdentityServerBuilder builder)
{
    builder.Services.AddTransient<IPersistedGrantStore, PersistedGrantStore>();
}
```
But the first line of log file is

### Relevant parts of the log file

```
You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
```

**Comment by brockallen** [comment]
> So in IdentityServerBuilderExtensions.cs

Does this mean you have forked the code to use IdentityServer?

**Comment by sdv-mini-dev-1** [comment]
No, I don't.
**IdentityServerBuilderExtensions.cs** is an helper class I created.
It is an extension method I use in startup.cs like:

```
services.AddIdentityServer()                
    [...]
    .AddOperationalStore();

```

What do you think about it? Am I missing something?

**Comment by sdv-mini-dev-1** [comment]
@brockallen I simplified _ConfigureServices_ with the following code:
```
services.AddIdentityServer()
    .AddDeveloperSigningCredential()
    .AddInMemoryIdentityResources(Config.GetIdentityResources())
    .AddInMemoryApiResources(Config.GetApiResources())
    .AddInMemoryClients(Config.GetClients())
    .AddTestUsers(Config.GetUsers())
    .Services.AddTransient<IPersistedGrantStore, PersistedGrantStore>();
```
Is that correct? 
Services.AddTransient<IPersistedGrantStore, PersistedGrantStore>(); **seems to be ignored by IdenitityServer.**

[Documentation](http://docs.identityserver.io/en/release/topics/deployment.html#operational-data) indicates this:
`You can also implement support for your own custom storage mechanism by implementing IPersistedGrantStore` .

Inside logs i see: 
`You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.`

**Comment by brockallen** [comment]
I tried to repo this in our EF host sample and could not. Can you repo it there and let us know? 

https://github.com/IdentityServer/IdentityServer4.EntityFramework/

**Comment by sdv-mini-dev-1** [comment]
I found a my mistake: I had created an interface with same name of the IdentityServer one.
I fixed removing it and using the correct namespace `IdentityServer4.Stores` for `IPersistedGrantStore`
