### ISSUE TITLE
On the ConfigurationDbContext why did we split up the model builder code?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#1938]
https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/DbContexts/ConfigurationDbContext.cs#L101-L102

Why not combine `ConfigureClientContext` and `ConfigureResourcesContext`?

**Comment by brockallen** [comment]
This allows others to create their own DbContext with only clients or resources.
