### ISSUE TITLE
If we want to host in a web farm, do we have to do anything special to share cookies between applications?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#1942]
We read the docs [here](http://docs.identityserver.io/en/release/topics/deployment.html#asp-net-core-data-protection).

> ASP.NET Core itself needs shared key material for protecting sensitive data like cookies, state strings etc. See the official docs here.
> You can either re-use one of the above persistence store or use something simple like a shared file if possible.

So we wrote our own Sql persistence store because a shared file was not possible for us. Everything on that front is working great. 

I read this guide here https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/cookie-sharing

Does this mean I have to tell IdentityServer4 to use the DataProtectionProvider? I looked at the source code of `AddDataProtection()` in `Microsoft.Extensions.DependencyInjection` and noticed it uses `TryAddSingleton` to try and register a `IDataProtectionProvider`. I noticed IdentityServer4 requires the `IDataProtectionProvider` in a few places, but does it ever set the DataProtector on `CookieAuthenticationOptions`?

I noticed it can be called here but is not https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/ConfigureInternalCookieOptions.cs#L21
  
My current code:

```csharp
var dataProtectionBuilder = services
    .AddDataProtection()
    .PersistKeysToSql(options =>
    {
        options.ConfigureDbContext = builder =>
        {
            builder.UseSqlServer(Configuration.GetConnectionString(identityServerConnectionStringKey), sql =>
            {
                sql.MigrationsAssembly(migrationsAssembly);
            });
        };
    })
    .SetDefaultKeyLifetime(TimeSpan.FromDays(DataProtectionConfiguration.Value.KeyLifetimeDays))
    .SetApplicationName("MyCompanyIdentityServer4");

// Use DataProtection certs in prod.
if (!Env.IsDevelopment())
{
    dataProtectionBuilder
    .ProtectKeysWithCertificate(new X509Certificate2(DataProtectionConfiguration.Value.ProtectKeysWithCertificate.FileName, DataProtectionConfiguration.Value.ProtectKeysWithCertificate.FilePassword))
    .AddKeyManagementOptions(options =>
    {
        options.XmlRepository = dataProtectionBuilder.Services.BuildServiceProvider().GetService<Microsoft.AspNetCore.DataProtection.Repositories.IXmlRepository>();
    });
}
```

**Comment by leastprivilege** [comment]
The cookie handlers pick up the global data protection configuration automatically.
