### ISSUE TITLE
IdentityServer4 Multiple API access, single token

### ISSUE THREAD

**Issue by chrisrestall** [IdentityServer/IdentityServer4#1943]
We have several in-house API's that we'd like to grant access to a client via client credentials flow.  The flow would go something like this.

1.    Client gets a token from is4 based on some scope
2.    Client hits first API with token
3.    Client needs to hit second API with same token.

Authorization of the token at the API endpoint seems to only work when the APIResource matches the APIName in the authentication parameters.  We would basically like to use the same token in each of our APIs.

How do you set up APIResource/Scopes such that this scenario can be accommodated?
--

**Comment by leastprivilege** [comment]
Create 2 API resources, make the client ask for both.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by chrisrestall** [comment]
Thank you!  Sorry I didn't see the free support option.  How do you "make" the client ask for both?

**Comment by nicbavetta** [comment]
@chrisrestall Hope this helps: https://github.com/IdentityServer/IdentityServer4/issues/2044
