### ISSUE TITLE
Invalid_scope when no scope specified for client credentials flow

### ISSUE THREAD

**Issue by chrisrestall** [IdentityServer/IdentityServer4#1945]
According to:
https://leastprivilege.com/2016/09/14/new-in-identityserver4-default-scopes/

However, when I do not pass a scope, I get an invalid scope error?  My client config looks like this:

ClientId = apiClientMeta.ClientId,                   
                        // no interactive user, use the clientid/secret for authentication
                        AllowedGrantTypes = GrantTypes.ClientCredentials, 
                        // scopes that client has access to
                        AllowedScopes = { "consapi", "custapi" }, 
                        ClientSecrets = secretes,
                        AllowAccessTokensViaBrowser = true,
                        RedirectUris = someuri,
                        PostLogoutRedirectUris = someuri,
                        AllowedCorsOrigins = true,
                        RequireConsent = false,
                        AlwaysIncludeUserClaimsInIdToken = true, 
                        AccessTokenType = AccessTokenType.Jwt, //Always
                        AlwaysSendClientClaims = true                    

My APIResources:
 ApiResource apiResource = new ApiResource("consapi", "Consultant API");
            apiResources.Add(apiResource);
            ApiResource apiResource2 = new ApiResource("custapi", "Customer API");
            apiResources.Add(apiResource2);

 I need to be able to get all of the AllowedScopes back for multiple API access, unless there's another way to do it.

**Comment by leastprivilege** [comment]
see 

https://github.com/IdentityServer/IdentityServer4/blob/666d76d07a790f6c1e2f35a8a90def66f7b9268c/test/IdentityServer.IntegrationTests/Clients/ClientCredentialsClient.cs#L89

and

https://github.com/IdentityServer/IdentityServer4/blob/666d76d07a790f6c1e2f35a8a90def66f7b9268c/test/IdentityServer.IntegrationTests/Clients/ClientCredentialsClient.cs#L123

**Comment by brockallen** [comment]
All set on this issue -- can we close?
