### ISSUE TITLE
Error from CreatePrincipal: ToEpochTime method not found

### ISSUE THREAD

**Issue by MV10** [IdentityServer/IdentityServer4#1949]
While doing some testing via the Quickstart.UI, inside `ExternalLoginCallback` the call to `SignInAsync` began throwing `Method not found: Int64 IdentityModel.EpochTimeExtensions.ToEpochTime`. I traced it back to the spot where `IdentityServerUser.CreatePrincipal` calls `AuthenticationTime.Value.ToEpochTime()`.

I'm in the process of merging the IdentityServer4 app with a separate client app based on Razor Pages, but the config changes are pretty minimal, and the only new dependency I added (versus a Quickstart.UI-only IS4 project) is the client-side `IdentityServer4.AccessTokenValidation` package. I doubt that's relevant, and before I started merging the two, Google third-party auth was working fine.

In Object Browser I see that `EpochTimeExtensions` is there and does have the method, and the project was working earlier. I've cleaned and rebuilt, I've restarted VS. Kind of puzzled.

Any ideas about what might be going on here?

**Comment by leastprivilege** [comment]
Make sure you have the latest nuget packages.

IdentityModel 3.0.0
IdentityServer 2.1.0
AccessTokenValidation 2.3.0

**Comment by MV10** [comment]
Ah, good call, didn't notice I'd picked up a newer AccessTokenValidation. Moving to IdentityServer 2.1.0 fixed it. Thanks.
