### ISSUE TITLE
Can I use it with nginx?

### ISSUE THREAD

**Issue by fleed** [IdentityServer/IdentityServer4#195]
Is it possible to use IdentityServer with nginx?
I'm using nginx to serve some static content (documentation) and redirect other requests to an Asp.net Core MVC app.
I'd like to protect both static and dynamic parts with IdentityServer.

As advanced feature I'd also like to pass claims to the Asp.net application.

**Comment by brockallen** [comment]
Yes, but this is more of a question for ASP.NET Core, not specifically IdentityServer4.
