### ISSUE TITLE
Consider QS.UI repo for ASP.NET Identity

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#1950]
so we have it in one place for quickstarts, templates etc.

**Comment by brockallen** [comment]
Can you start that repo and I can populate it? Thx.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4.Quickstart.UI.AspNetIdentity

**Comment by brockallen** [comment]
Done, thanks
