### ISSUE TITLE
(Hopefully) simple question regarding OAuth2IntrospectionOptions

### ISSUE THREAD

**Issue by robbaman** [IdentityServer/IdentityServer4#1951]
Apologies if this question has been answered before (I did actually look before I posted), but when using the `AddIdentityServerAuthentication()` method from the _IdentityServer4.AccessTokenValidation_ package there is an option to pass in two configuration functions, one for the _JwtBearerOptions_ and one for the _OAuth2IntrospectionOptions_.

The _OAuth2IntrospectionOptions_ configuration object mandates (as far as I've been able to determine) that a `ClientId` and `ClientSecret` are passed in. It was only after a significant amount of time that I figured out that what is requested here is a (Resource) Scope name and it's corresponding Scope secret of a scope that is also required to be in the reference access token that requires the introspection endpoint in the first place.

My question is, **is there a particular reason that these properties are called ClientId and ClientSecret?** On the overload of the `AddIdentityServerAuthentication()` (with just one configuration function) these same properties are called _ApiName_ and _ApiSecret_, which is much more obvious with regard to what one is supposed to provide.

A second question if I may be so bold; **am I correct in assuming one must always use one Scope for validating all reference access tokens?** We have an endpoint that uses quite a few scopes to authorize acccess to the various routes. It seems to me that the way it is designed we'd need to supply each client that requests an access token (and uses reference tokens) with the one scope that is specified in the options, and configure this scope with _AllowUnrestrictedIntrospection_.

**Comment by TomCJones** [comment]
Granted that client is nonobviosds. It goes back to the roots in OAuth where the site was considered to be acting as a client of the user.

**Comment by leastprivilege** [comment]
question 1: the OAuth2Introspection handler is a generic protocol implementation. From their point of view, the API introspecting the token is a client. The IdentityServer authentication handler is made for IdentityServer, so we chose the same terminology. It uses the generic one under the covers.

question 2: we only allow introspection of a token if the "introspecter" is a valid audience of that token. Otherwise unrelated APIs could "see" the token contents. If you want to change that behavior, you can replace the `IIntrospectionResponseGenerator`.

**Comment by robbaman** [comment]
@leastprivilege Thanks for taking the time to answer my question. I get what you mean with regards to the terminology, but for the other overload of the `AddIdentityServerAuthentication()` the property names have changed to _ApiName_ and _ApiSecret_. I believe these names are also IdentityServer specific as I recall from the documentation that you've chosen to not use the generic _Scope_ terminology, but instead use _ApiResource_. I don't think anyone would've minded if the two properties I mentioned woul've also be called _ApiName_ and _ApiSecret_ :D But it's all clear now, so thank you again.


With regards to the second question, what I mean is that it seems to me that now you always have to use exactly 1 scope to authenticate with the Introspection endpoint. Let me clarify with an example:

Suppose my WebApi site has two Api's: _Api1_ and _Api2_ of which only one is used at a time. If we chose to use reference tokens, then I **must** introduce a third resource scope for the sole purpose of identifying with the introspection endpoint. Because there is no way to use the `AddIdentityServerAuthentication()` to configure both Api1 **and** Api2 to be allowed, depending on the one that is used by the..... ah wait, it just dawned on me... with a reference token we don't know what scopes are in the token, so there's no way to use the one that's in the token... doh.

Well, I'll go sit in the corner now. I'll leave this here in case anyone has the same question and finds this.

**Comment by leastprivilege** [comment]
You are not using a scope to authenticate - you are using an API name/secret.

**Comment by robbaman** [comment]
I'm using IdentityServer3 where I need to add a Scope and ScopeSecret for this to work. 

So what you're saying is that I'm using an **Api name/secret** to authenticate. For this I need to use the **ClientId and ClientSecret** properties on the OAuth2IntrospectionOptions configuration object that correspond to the values in the **Scope and ScopeSecret** objects in IdentityServer3... 

You do see why one gets confused right? :)

**Comment by leastprivilege** [comment]
Especially since this repo does not know anything about IdentityServer3 ;)

**Comment by robbaman** [comment]
Yeah, we're building a client that uses dotnet core so we have to use the IdentityServer4.AccessTokenValidation package, but there's no budget (or need tbh) to upgrade the IdentityServer3 installation we have running. So for now it's an interesting and educating journey to get everything working. It's much appreciated that you and Brock are always so willing to help.
