### ISSUE TITLE
Getting access token within Claims Transformer on client MVC application

### ISSUE THREAD

**Issue by domrin123** [IdentityServer/IdentityServer4#1953]
Hi, I've posted this on stackoverflow (https://stackoverflow.com/questions/47929027/getting-access-token-within-claims-transformer-in-asp-net-core) a few weeks ago but we're still a stuck.

I'm developing a set of applications including an Identity Server using IdentityServer4, a .NET Core MVC app, a .NET Core WebAPI. We used he samples for Hybrid Flow to get started. As part of a asp.net core mvc application I am using `AddOpenIdConnect ` to do authentication and doing `options.SaveTokens = true`. 

However, as part of Claims Transformation, in `TransformAsync` I would like to be able to have access to the access token provided by the identityserver. This is to be able to call a permissions endpoint on the api to populate the principal with claims that I can use to do authorization on my controllers etc. If I call `HttpContext.GetTokenAsync("access_token")` I get a stackoverflowexception due to the infinite loop created by authenticate being called, which then calls `TransformAsync` again. Is this a sound approach in the first place? 

Typically, `TransformAsync` is where I would populate application permissions. Is there any way of accessing the token without triggering the authenticate again? Would appreciate any help as we're a bit stumped! I've seen suggestions around doing transformations in the `OnTicketReceived ` event. It looks like I'd have access to the token through the properties in there. Is this a better place to do it?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
