### ISSUE TITLE
Authorization response prevented in some iframe scenarios

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#1955]
Currently client apps that each use their own cookie and that are composed of many sub-apps via iframes (e.g. portal style apps), our CSP frame-ancestor options blocks responses to those clients in the child iframes. 

To fix this bug we will relax the frame-ancestor setting for the authorization response.

#1915

**Comment by brockallen** [comment]
fixed

**Comment by v2Shridhar** [comment]
Is there a workaround available if we cant upgrade out IdentityServer to 2.x nuget packages? Right now we are in 1.5.2
