### ISSUE TITLE
After logout when validating access_token in Introspection endpoint is returning active

### ISSUE THREAD

**Issue by LeandroSantosSilva** [IdentityServer/IdentityServer4#1956]
I login in the application is generated access_token, refresh_token and etc.

Perform the application logoff by the endsession endpoint

When executing the instrospection endpoint passing the previously retrieved access_token the system returns that it is active

When leaving the application should not invalidate this access_token? It is only returning that is not active after the expiration time of access_token.

Thanks.

**Comment by brockallen** [comment]
Access token lifetime is unrelated to a user's session lifetime.

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
