### ISSUE TITLE
Request due to deprecation of IDSRV3

### ISSUE THREAD

**Issue by tbrettallen** [IdentityServer/IdentityServer4#1957]
Our implementation of IdentityServer3 relies heavily on some in-house libraries developed in .NET Framework 4.6.1.

We are avoiding switching to Core for numerous issues we've had with it.

For us to upgrade to IdentityServer4, is it possible to have a version compiled against the .NET Framework runtime, so that we can continue to use existing code during the upgrade process?

I've seen other packages allow targeting both .NET Core runtime and .NET Framework runtime. Assuming all your code is compliant with .NET Standard, this hopefully won't be a huge issue.

Thanks!

**Comment by leastprivilege** [comment]
IdentityServer4 runs on .NET Core 2.0+ and .NET Framework 4.6.1+
