### ISSUE TITLE
Add client_id to ErrorMessage when Authorization request failed

### ISSUE THREAD

**Issue by sdib** [IdentityServer/IdentityServer4#1958]
On the error page, I would like to have access to the client_id provided to the authorization endpoint.

With this information I would be able to display (or redirect to) a user friendly page telling that the application has been disabled for example.

Is it a good idea, or you see some issues with it or can suggest alternatives?
If you think, that it is ok, will it be useful for other users? Do you want me to create pull request?

Here is my code for this feature : https://github.com/sdib/IdentityServer4/pull/1/files

**Comment by TomCJones** [comment]
Your assumption here is that the authorization endpoint has access to the OP data base and so can interpret the meaning of the client id.  This is not true in general.

**Comment by brockallen** [comment]
> Your assumption here is that the authorization endpoint has access to the OP data base and so can interpret the meaning of the client id. This is not true in general.

How else would the OP validate and process requests to the authorize endpoint if it didn't have access to it's configuration data (in a DB or otherwise)?

> Is it a good idea, or you see some issues with it or can suggest alternatives?

The real issue is how far into the validation processing have we gotten by the time we encounter an error. If the client info has not yet been validated (client, id, redirect uri, etc.), then you won't get it on the error page.

**Comment by TomCJones** [comment]
If the OP is the sole source of all claims, then it is reasonable to assume that the client_id works across all instances of the authz endpoint. That may be the only case of interest for this list today. On a different thread there was a discussion about expanding the scope to other sources of claims. In any case the way that the client styles itself to the user may not be the way it is known to the OP.

**Comment by brockallen** [comment]
> In any case the way that the client styles itself to the user may not be the way it is known to the OP.

I think @sdib is talking about the error page within IdentityServer, not anything in the client.

**Comment by sdib** [comment]
Yes you're right @brockallen , I'm talking about the error page within IdentityServer.
@TomCJones , if you had a look to my code for this feature, I'm just adding the ClientId info to the ErrorMessage object you can retrieve when the error page is called via InteractionService.

> The real issue is how far into the validation processing have we gotten by the time we encounter an error. If the client info has not yet been validated (client, id, redirect uri, etc.), then you won't get it on the error page.

It's fair enough for me to provide the ClientId only when it's possible.

**Comment by brockallen** [comment]
Added
