### ISSUE TITLE
Quickstart 6 doesn't redirect as expected 

### ISSUE THREAD

**Issue by eggbeard** [IdentityServer/IdentityServer4#1959]
### Issue / Steps to reproduce the problem
Clone https://github.com/IdentityServer/IdentityServer4.Samples.git
Open in Visual Studio 2017
Modify hosting as described [here](https://identityserver4.readthedocs.io/en/release/quickstarts/0_overview.html#modify-hosting)
Run project and try to access "Secure" link
Login succeeds per log file, but no redirect happens

### Relevant parts of the log file
Login works successfully

AuthorizeCallbackEndPoint is hit and complains that no user is present.

Ultimately results in redirecting back to login again?

```
info: IdentityServerWithAspNetIdentity.Controllers.AccountController[0]
      User logged in.
info: Microsoft.AspNetCore.Mvc.Internal.RedirectResultExecutor[1]
      Executing RedirectResult, redirecting to /connect/authorize/callback?client_id=mvc&redirect_uri=http%3A%2F%2Flocalhost%3A5002%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile%20api1%20offline_access&response_mode=form_post&nonce=636510689461743834.YjhjZDU5ZTEtNGY5NC00OTI2LWE3OTMtOGExYzdjYzY5NDA5ZDQyYmM5MTktNzE0My00YzRmLWExODgtZTM1YTgwZDYzMDA3&state=CfDJ8OMuGnQBqapFpRUWHqEv-uIsgC43HAFkKHBtTeLQQre2FRmKQmXMmxhCQUDP-YNfyyVGZFmOP5X1iVUciNKw-kj0ezaM_ZO17z1DOqY-fFnAkHZC06Ju79UyXcijWPNGXJTwL__XV68E7oB8C6ppcuQ-LhezdpmxVt_TjxxIk9ZB7WD3tssIWxWXg7Xw0dVEHcOJCUos_4JnoWf4zRr6JllGjg-1yXXN4Se8eXQ8uV1JX-CY1p3TT11hFXTNa9d22vJgAVHLVccA6K_S0SSFC-nm3bs4KXoZQJ2bRXNhM8X2DYc1_OsnX4hJbFrXBZbvmceRLZ-Ymx67foxgFn1UTak&x-client-SKU=ID_NET&x-client-ver=2.1.4.0.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityServerWithAspNetIdentity.Controllers.AccountController.Login (IdentityServerWithAspNetIdentity) in 3663.0541ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3728.3785ms 302
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/connect/authorize/callback?client_id=mvc&redirect_uri=http%3A%2F%2Flocalhost%3A5002%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile%20api1%20offline_access&response_mode=form_post&nonce=636510689461743834.YjhjZDU5ZTEtNGY5NC00OTI2LWE3OTMtOGExYzdjYzY5NDA5ZDQyYmM5MTktNzE0My00YzRmLWExODgtZTM1YTgwZDYzMDA3&state=CfDJ8OMuGnQBqapFpRUWHqEv-uIsgC43HAFkKHBtTeLQQre2FRmKQmXMmxhCQUDP-YNfyyVGZFmOP5X1iVUciNKw-kj0ezaM_ZO17z1DOqY-fFnAkHZC06Ju79UyXcijWPNGXJTwL__XV68E7oB8C6ppcuQ-LhezdpmxVt_TjxxIk9ZB7WD3tssIWxWXg7Xw0dVEHcOJCUos_4JnoWf4zRr6JllGjg-1yXXN4Se8eXQ8uV1JX-CY1p3TT11hFXTNa9d22vJgAVHLVccA6K_S0SSFC-nm3bs4KXoZQJ2bRXNhM8X2DYc1_OsnX4hJbFrXBZbvmceRLZ-Ymx67foxgFn1UTak&x-client-SKU=ID_NET&x-client-ver=2.1.4.0
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /connect/authorize/callback matched to endpoint type Authorize
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Endpoint enabled: Authorize, successfully created handler: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint for /connect/authorize/callback
dbug: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint[0]
      Start authorize callback request
dbug: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint[0]
      No user present in authorize request
dbug: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Start authorize request protocol validation
dbug: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Checking for PKCE parameters
dbug: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      No PKCE used.
dbug: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator
info: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint[0]
      ValidatedAuthorizeRequest
      {
        "ClientId": "mvc",
        "ClientName": "MVC Client",
        "RedirectUri": "http://localhost:5002/signin-oidc",
        "AllowedRedirectUris": [
          "http://localhost:5002/signin-oidc"
        ],
        "SubjectId": "anonymous",
        "ResponseType": "code id_token",
        "ResponseMode": "form_post",
        "GrantType": "hybrid",
        "RequestedScopes": "openid profile api1 offline_access",
        "State": "CfDJ8OMuGnQBqapFpRUWHqEv-uIsgC43HAFkKHBtTeLQQre2FRmKQmXMmxhCQUDP-YNfyyVGZFmOP5X1iVUciNKw-kj0ezaM_ZO17z1DOqY-fFnAkHZC06Ju79UyXcijWPNGXJTwL__XV68E7oB8C6ppcuQ-LhezdpmxVt_TjxxIk9ZB7WD3tssIWxWXg7Xw0dVEHcOJCUos_4JnoWf4zRr6JllGjg-1yXXN4Se8eXQ8uV1JX-CY1p3TT11hFXTNa9d22vJgAVHLVccA6K_S0SSFC-nm3bs4KXoZQJ2bRXNhM8X2DYc1_OsnX4hJbFrXBZbvmceRLZ-Ymx67foxgFn1UTak",
        "Nonce": "636510689461743834.YjhjZDU5ZTEtNGY5NC00OTI2LWE3OTMtOGExYzdjYzY5NDA5ZDQyYmM5MTktNzE0My00YzRmLWExODgtZTM1YTgwZDYzMDA3",
        "Raw": {
          "client_id": "mvc",
          "redirect_uri": "http://localhost:5002/signin-oidc",
          "response_type": "code id_token",
          "scope": "openid profile api1 offline_access",
          "response_mode": "form_post",
          "nonce": "636510689461743834.YjhjZDU5ZTEtNGY5NC00OTI2LWE3OTMtOGExYzdjYzY5NDA5ZDQyYmM5MTktNzE0My00YzRmLWExODgtZTM1YTgwZDYzMDA3",
          "state": "CfDJ8OMuGnQBqapFpRUWHqEv-uIsgC43HAFkKHBtTeLQQre2FRmKQmXMmxhCQUDP-YNfyyVGZFmOP5X1iVUciNKw-kj0ezaM_ZO17z1DOqY-fFnAkHZC06Ju79UyXcijWPNGXJTwL__XV68E7oB8C6ppcuQ-LhezdpmxVt_TjxxIk9ZB7WD3tssIWxWXg7Xw0dVEHcOJCUos_4JnoWf4zRr6JllGjg-1yXXN4Se8eXQ8uV1JX-CY1p3TT11hFXTNa9d22vJgAVHLVccA6K_S0SSFC-nm3bs4KXoZQJ2bRXNhM8X2DYc1_OsnX4hJbFrXBZbvmceRLZ-Ymx67foxgFn1UTak",
          "x-client-SKU": "ID_NET",
          "x-client-ver": "2.1.4.0"
        }
      }
info: IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator[0]
      Showing login: User is not authenticated
```

[IdentityServer4_QS6.log](https://github.com/IdentityServer/IdentityServer4/files/1613886/IdentityServer4_QS6.log)

**Comment by codetian** [comment]
I have a same question in Quickstart3_ImplicitFlowAuthentication

**Comment by codetian** [comment]
I am learning about Adding User Authentication with OpenID Connect . I code by example ,but The page redirect the http://localhost:5002/signin-oidc( page appear not found) when I login success. I download the example ,it run as expected .

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by eggbeard** [comment]
Yep, looks good.  many thanks

**Comment by yfr7** [comment]
Hi,
I am using the example that mixes asp.net identity and entityframework and I have the same problem.

I made some changes to make it work with SQL Server, and changed the usernames of the default users. I am testing it with the mvc client that is part of the sample.

From the logs I can tell that asp.net identity is authenticating the users, and at this point the user should be sent to a consent page. But that is not happening, and for some reason the user information is not being added to the request.

Here is part of the logs of Identity Server

[00:45:37 Information] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: Identity.Application signed in.

[00:45:37 Information] IdentityServer4.Events.DefaultEventService
{
  "Name": "User Login Success",
  "Category": "Authentication",
  "EventType": "Success",
  "Id": 1000,
  "Username": "admin",
  "SubjectId": "c60e946d-4583-41af-a37e-29b0de233c85",
  "DisplayName": "admin",
  "Endpoint": "UI",
  "ActivityId": "0HLDB0Q5HQRQ2:00000004",
  "TimeStamp": "2018-04-25T23:45:37Z",
  "ProcessId": 21316,
  "LocalIpAddress": "::1:5000",
  "RemoteIpAddress": "::1"
}

[00:45:37 Debug] IdentityServer4.Hosting.EndpointRouter
Request path /connect/authorize/callback matched to endpoint type Authorize

[00:45:37 Debug] IdentityServer4.Hosting.EndpointRouter
Endpoint enabled: Authorize, successfully created handler: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint

[00:45:37 Information] IdentityServer4.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint for /connect/authorize/callback

[00:45:37 Debug] IdentityServer4.Endpoints.AuthorizeCallbackEndpoint
Start authorize callback request

[00:45:37 Debug] IdentityServer4.Endpoints.AuthorizeCallbackEndpoint
No user present in authorize request

[00:45:37 Debug] IdentityServer4.Validation.AuthorizeRequestValidator
Start authorize request protocol validation

**Comment by j-tee** [comment]
@yfr7 Got the same issue here, Have you been able to get past yours. If you have let me n=know how you did it.

**Comment by yfr7** [comment]
Hi @j-tee,

I was able to get past the problem. How are you running the application. To me I had to clean the solution, remove the application cookies from my browser, and then run with the debugger (F5).

For some reason, when I was trying to run without the debugger (Ctrl + F5) the authentication info wasn't being persisted I'm my request.

Let me know how it works for you. 

Best regards,

**Comment by codeonnn** [comment]
Hi @yfr7

Thank you very much, was trouble shooting same problem from last 2 days.
Changed the browser all together, and correct redirect started happening with consent page.
I think cookies are not getting cleared correctly.

**Comment by santosh2812** [comment]
Hi All, I am facing same problem , but unable to get any solution - I have changed the browser and port cleared the cookies but nothing happened. 
Any help...

**Comment by santosh2812** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/3685
