### ISSUE TITLE
PromptMode="select_account"

### ISSUE THREAD

**Issue by etrafiee** [IdentityServer/IdentityServer4#196]
I am trying to implement a way that my users can swap accounts without having to login. I read in OpenIdConnect specs that prompt=select_account should do something similar to what I want.
As far as I looked in the IdentityServer4 library I wasn't able to find any implementations addressing that section of oidc spec.
Have I missed something or you are still working on that bit?

**Comment by brockallen** [comment]
This is something we did not support in IdSvr3, but given the UI re-work it might be easier in IdSvr4. If we get something working, then the real work will be passed onto you as the UI/login page developer and the request for prompt=select_account would be something your login code would have to handle.

**Comment by Lutando** [comment]
This is absolutely fantastic.

**Comment by etrafiee** [comment]
I am getting closer to the day that I need this feature. Is there any chance that we could have it in near future?

**Comment by leastprivilege** [comment]
Ultimately this needs to be implemented at the UI layer.

What's currently missing is that we hand of control to the UI for this prompt mode. Will add an issue for that...

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/547
