### ISSUE TITLE
EF Core Implementation throws Error on reading Resources

### ISSUE THREAD

**Issue by KyeTech** [IdentityServer/IdentityServer4#1960]
Hi,

I am seeing an error being thrown in the FindResourcesByScopeAsync method of IResourceStoreExtensions regrading instance members not guaranteed to be thread safe.

The error message I am seeing is:
A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.

More specifically this error is thrown by the call to FindIdentityResourcesByScopeAsync within FindResourcesByScopeAsync.

Could this be an EF core issue with the multiple asynchronous reads from the db on the same context?

Any help would be greatly appreciated.

**Comment by brockallen** [comment]
> Could this be an EF core issue with the multiple asynchronous reads from the db on the same context?

Doesn't matter -- the DbContext should be in DI as scoped (or transient).

**Comment by KyeTech** [comment]
Hi Brock,

Thanks for the quick response.
The sql configuration is handled by the following code:

services.AddIdentityServer()
                .AddConfigurationStore(options => { options.ConfigureDbContext = this.ConfigureUseSql; })
                .AddOperationalStore(options => { options.ConfigureDbContext = this.ConfigureUseSql; })

Where this.ConfigureUseSql is:

void ConfigureUseSql(DbContextOptionsBuilder builder)
        {
            var connectionString ="dbconnectionstring";
            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            builder.UseSqlServer(connectionString, sql => sql.MigrationsAssembly(migrationsAssembly));
        }

This is based on the documentation at:
http://docs.identityserver.io/en/release/quickstarts/8_entity_framework.html

Previously I wasn't seeing these errors until I updated identityserver4 recently to 2.1.0

Is there something that is incorrect about how I am setting up the db context for this?

**Comment by brockallen** [comment]
> Is there something that is incorrect about how I am setting up the db context for this?

No, it seems correct. So then it's unclear why you're getting the error you mention above.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by KyeTech** [comment]
Yes thanks, issue seems to be resolved after updating to 2.1.1 and changing, what didn't seem related, service scopes.
