### ISSUE TITLE
Method not found: 'Int64 IdentityModel.EpochTimeExtensions.ToEpochTime(System.DateTime)'.

### ISSUE THREAD

**Issue by zyofeng** [IdentityServer/IdentityServer4#1962]
The method is now returning int instead of long, cause PasswordSignInAsync to fail.

public static int ToEpochTime(this DateTime dateTime)

https://github.com/IdentityModel/IdentityModel2/blob/17a26a4ec95d7067856462a5788d7dc0501043d0/src/IdentityModel/EpochTimeExtensions.cs

**Comment by zyofeng** [comment]
If I update IdentityServer4 manually to 2.1.0, login works. but the minimal required version for IdentityServer4.AspNetIdnetity is 2.0.3. Assume this just needs to be updated so the minimal version is bumped to 2.1.0

**Comment by leastprivilege** [comment]
we are going to release new packages soon - so this should work automatically then. thanks

**Comment by MeydanOzeri** [comment]
I have the same issue with identityserver4 that is higher then version 2.1.2
