### ISSUE TITLE
Recommendations for token certificates?

### ISSUE THREAD

**Issue by MV10** [IdentityServer/IdentityServer4#1968]
Are there any requirements or recommendations relating to the creation of token signing and token validation certificates?

Google hasn't been much help. I've been playing around with `New-SelfSignedCertificate` in Powershell generating various certs for token-signing and token-validation. IdentityServer seems happy to accept certificates with all sorts of settings. Certificates have so many options, it's almost hard to believe there is a standard lurking behind all of that!

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
