### ISSUE TITLE
EndSession and clientId

### ISSUE THREAD

**Issue by baluubas** [IdentityServer/IdentityServer4#197]
I'm testing out new and improved EndSession functionality in beta5. 

I want to use the PostLogoutRedirectUris of a Client configuration when ending the session. However the `TokenValidator` fails the validation since it can't find the client id. 

Looking at the code it seems a bit strange (although I'm a complete newbie to oidc) that audience property of the token is used as clientId. The relevant code:

```
  private string GetClientIdFromJwt(string token)
        {
            try
            {
                var jwt = new JwtSecurityToken(token);
                var clientId = jwt.Audiences.FirstOrDefault();

                return clientId;
            }
            catch (Exception ex)
            {
                _logger.LogError("Malformed JWT token: {exception}", ex.ToString());
                return null;
            }
        }
```

I'm I completely off or could this be an actual bug?

**Comment by brockallen** [comment]
> However the TokenValidator fails the validation since it can't find the client id. 

Can you elaborate? What do the logs say?

**Comment by baluubas** [comment]
Of course

Here is what the logs say:

```
trce: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.EndSessionEndpoint
info: IdentityServer4.Endpoints.EndSessionEndpoint[0]
      Processing singout request
dbug: IdentityServer4.Validation.EndSessionRequestValidator[0]
      Start end session request validation
dbug: IdentityServer4.Validation.TokenValidator[0]
      Start identity token validation
fail: IdentityServer4.Validation.TokenValidator[0]
      Unknown or diabled client: http://localhost:60211/resources.
warn: IdentityServer4.Validation.EndSessionRequestValidator[0]
      Error validating id token hint.
{
        "SubjectId": "unknown",
        "Raw": {
          "id_token_hint": <removed>
        }
      }
```

So it appears  that audience claim value (in my case http://localhost:60211/resources) is being used to check the existence of a client (using `IClientStore`.) 

I was expecting the client id to equal the value of the claim with type JwtClaimTypes.ClientId. (That said, I'm not quite sure what the audience claim is intended for).

**Comment by brockallen** [comment]
That tells me that the access token is being sent, not the id token.

**Comment by baluubas** [comment]
Yes, spot on. As you said, I was sending the access_token and not the id_token. Sending the correct token fixed my problem.

Thanks for for the help.

**Comment by santiagomolinadecastro** [comment]
Where can i find that token_id? I have the same problem. I'm sending Access token but i have to send token_id.
