### ISSUE TITLE
Documentation Has Broken Link

### ISSUE THREAD

**Issue by zeus82** [IdentityServer/IdentityServer4#1973]
A link in the documentation is dead.

This document:
https://github.com/IdentityServer/IdentityServer4/blob/release/docs/quickstarts/4_external_authentication.rst

Has this link (which does not work):
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Host/Quickstart/Account/AccountService.cs

**Comment by brockallen** [comment]
feel free to submit a PR :)

**Comment by tbasallo** [comment]
Hope no one minds, I went ahead and made the change and created PR https://github.com/IdentityServer/IdentityServer4/pull/1974 

I added two links, one the project and the other to what I think was the intended destination (for auto-provisioning). [updated page in fork](https://github.com/tbasallo/IdentityServer4/blob/dev/docs/quickstarts/4_external_authentication.rst)

**Comment by brockallen** [comment]
Merged, thanks.
