### ISSUE TITLE
SSO with Multiple App

### ISSUE THREAD

**Issue by Nisfan** [IdentityServer/IdentityServer4#1975]
idsrv.domain.com - IdentityServer4

crm.domain.com - Client1
health.domain.com - Client2

Both the apps are registered as client with single identity server (idsrv.domain.com)

Admin User (Tenant) 'A' has license for both apps (crm, health) -
Admin User (Tenant) 'B' has license only for crm

Scenario 1:
1. User 'A' try to login crm.domain.com, it will redirect to idsrv.domain.com for authentication.
2. User signed into the crm.domain.com by entering authentication

so from here, User 'A' able to access health.domain.com as well because single identityserver (idsrv.domain.com), that make sense

Scenario 2:
1. User 'B' try to login crm.domain.com, it will redirect to idsrv.domain.com for authentication.
2. User 'B' signed into the crm.domain.com by entering authentication

3. **User 'B' doesn't have permission to access health.domain.com (licensing) so how can i deny the access and show login page?**

You can only have one signed in user at a time on a single instance of idsrv so cannot remain signed in on two tenants at the same time, is this still true?

I tried following ways to solve this problem

`
While Login User
new Claim("AllowedApp", "1,2"),

public class Customresponsehandler : AuthorizeInteractionResponseGenerator {

        public Customresponsehandler(ISystemClock clock, ILogger<AuthorizeInteractionResponseGenerator> logger, IConsentService consent, IProfileService profile) : base(clock, logger, consent, profile) {

        }

        protected override Task<InteractionResponse> ProcessLoginAsync(ValidatedAuthorizeRequest request) {
            string allowedApp = request.Subject.FindFirstValue("AllowedApp");
            string currentApp = request.GetTenant();

            if (allowedApp != null && allowedApp.Length > 0) {
                string[] allowedList = allowedApp.Split(',');

                if (!allowedList.Contains(currentApp)) {
                    request.RedirectUri = "/login";                    
                }
            }

            return base.ProcessLoginAsync(request);
        }
    }`

Thanks in advance

**Comment by leastprivilege** [comment]
> User 'B' doesn't have permission to access health.domain.com (licensing)

That's an application concern. Show him an error page in the client.

That said

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by Nisfan** [comment]
Thanks for quick reply

> Show him an error page in the client

I want to show login page instead of error page how I can do that? The way I did in Customresponsehandler is correct to handle this situation? or could you please point out the way handle?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
