### ISSUE TITLE
Question: Affinity requirement for scaled RPs

### ISSUE THREAD

**Issue by max-buecker** [IdentityServer/IdentityServer4#1976]
Hey there. So I have the task to revamp the authentication/authorization pipeline of a large classic ASP.NET application, that includes both Web Forms and MVC.

This application should be the RP, while I am adding a new web service hosting the OP as IdentityServer 4.
The RP is a website, that requires some amount of horizontal scaling to accommodate for user load, but I can't currently ensure affinity to those services. So when I use Authorization flow the RP becomes stateful, as it's storing e.g. access tokens and refresh tokens on behalf of the users. When a node of RP breaks down, and the users go to a different instance of RP than the one used to sign into RP, then they would have an additional roundtrip to OP, correct?

What is the recommended way to keep RP stateless. Is there a way for me to specify how the refresh_tokens and access_tokens are stored and managed? Say like a memory cache that's synchronized with a redis?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
