### ISSUE TITLE
After deploy identityserver3 makes error for The client application is not known or is not authorized

### ISSUE THREAD

**Issue by mohsenRi** [IdentityServer/IdentityServer4#1977]
I'm new in identity server3.

I implementation identityserver3 on my localhost and every thing works well but after i deploy it on IIS and go to the autorize page it makes an error. The text of error is :The client application is not known or is not authorized. But clientid are same as each other.

Here is my client code:
` new Client
            {
                Enabled = true,
                ClientName = "sth",
                ClientId = "mfc",
                Flow = Flows.Implicit,
                RequireConsent = false,
                AllowRememberConsent = true,
                RedirectUris = new List<string>
                {
                    System.Configuration.ConfigurationManager.AppSettings["sth"]
                },
                 PostLogoutRedirectUris = new List<string>
                {
                    System.Configuration.ConfigurationManager.AppSettings["sth"]
                },
                IdentityTokenLifetime = 360,
                AccessTokenLifetime = 3600,
                AllowedScopes = new List<string>() { "openid", "profile" , "roles", "WebAPI" }
            }`
And my startup class of my another project is:
    public void Configuration(IAppBuilder app)
    {
        app.UseCookieAuthentication(new CookieAuthenticationOptions
        {
            AuthenticationType = "Cookies"
        });

        app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
        {
            Authority =ConfigurationManager.AppSettings["Authority"],
            ClientId = "mfc",

            //In the Scope we ask what to include
            Scope = "openid profile roles WebAPI",
            RedirectUri = ConfigurationManager.AppSettings["RedirectUri"],
            ResponseType = "id_token token",
            SignInAsAuthenticationType = "Cookies",
            UseTokenLifetime = false,
            Notifications = new OpenIdConnectAuthenticationNotifications
            {
                SecurityTokenValidated = n =>
                {
                    var id = n.AuthenticationTicket.Identity;
                    var sub = id.FindFirst(IdentityServer3.Core.Constants.ClaimTypes.Subject);
                    var roles = id.FindAll(IdentityServer3.Core.Constants.ClaimTypes.Role);

                    // create new identity and set name and role claim type
                    var nid = new ClaimsIdentity(id.AuthenticationType,
                            IdentityServer3.Core.Constants.ClaimTypes.Name, IdentityServer3.Core.Constants.ClaimTypes.Role);

                    nid.AddClaim(sub);
                    nid.AddClaims(roles);

                    // keep the id_token for logout
                    nid.AddClaim(new System.Security.Claims.Claim("id_token", n.ProtocolMessage.IdToken));

                    nid.AddClaim(new System.Security.Claims.Claim("access_token", n.ProtocolMessage.AccessToken));

                    n.AuthenticationTicket = new AuthenticationTicket(nid, n.AuthenticationTicket.Properties);

                    return Task.FromResult(0);
                },
                RedirectToIdentityProvider = n =>
                {
                    if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                    {
                        var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");

                        if (idTokenHint != null)
                        {
                            n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                        }
                    }

                    return Task.FromResult(0);
                }
            }
        });

        AntiForgeryConfig.UniqueClaimTypeIdentifier = IdentityServer3.Core.Constants.ClaimTypes.Subject;
        JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

        // ConfigureAuth(app);
    }
Please help me. Thanks.!

**Comment by leastprivilege** [comment]
This repo is about IdentityServer4 - not 3. IdentityServer3 is retired.

You can try StackOverflow - or if you need commercial support, have a look here:
https://identityserver4.readthedocs.io/en/release/intro/support.html
