### ISSUE TITLE
Hybrid flow + custom flow: change account (claims, access token) to another account. 

### ISSUE THREAD

**Issue by azhukov** [IdentityServer/IdentityServer4#1982]
Hello!
I need some suggestion on how to implement my custom flow.

ASP.NET MVC OWIN (Identityserver3) uses Hybrid Grant type to sign in with IdentityServer4.
This works fine.

But there is an additional flow. I need to re-login user (change user claims and access token ) to different account by providing some parameters like linkedAccountID.

I implemented custom grant type but it seems to be a wrong approach. I need some browser interaction there to manage cookies. Am I right?
I think I have to redirect to some IdentityServer4 URL, do SignOut and then SignIn and redirect back to MVC client.

 Please suggest.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
