### ISSUE TITLE
Can I have an example for what the ID4 configuration would look like for ConsoleHybridWithPkce?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#1985]
I can't seem to figure out the configuration to get the https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients/src/ConsolePrivateKeyJwtClient sample working. Whats the AllowedGrantType? Do I need a client secret? Currently my error is that the client id cant be found.

Looks like I am a step closer with something like this, http://docs.identityserver.io/en/release/topics/secrets.html#beyond-shared-secrets I still cant get the client ID to be found however.

**Comment by VictorioBerra** [comment]
I fixed my issue by adding the client ID to TokenClient and using the configuration shown in the docs above.

I am leaving this open as I think there is a "bug" in the sample, I think that for the sample to work with the docs, the `TokenClient` must specify the client ID which it currently does not.

**Comment by leastprivilege** [comment]
Check the corresponding configuration for the client_id in the main repo host.

**Comment by VictorioBerra** [comment]
Following up in case anyone else finds this:

`AddJwtBearerClientAuthentication()`

That is required as per the docs: http://docs.identityserver.io/en/release/topics/startup.html?highlight=AddJwtBearerClientAuthentication
