### ISSUE TITLE
invalid_grant when using refresh tokens

### ISSUE THREAD

**Issue by ryanhmaas** [IdentityServer/IdentityServer4#1986]
I'm getting `"error": "invalid_grant"` when using refresh tokens. The flow looks something like:

- User logs in, gets access token & refresh token
- If access token expires, attempt to get a new one by passing the refresh token to `RequestRefreshTokenAsync`

The client has `StandardScopes.OfflineAccess` in the `AllowedScopes` plus the following settings

- `AllowOfflineAccess = true`
- ` RefreshTokenExpiration = TokenExpiration.Sliding`
- `RefreshTokenUsage = TokenUsage.ReUse`

Is there something else I'm missing or is this use case invalid?

Thanks!

**Comment by brockallen** [comment]
> Is there something else I'm missing

Look in the logs?

**Comment by ryanhmaas** [comment]
```
2018-01-12 15:45:53.847 -05:00 [DBG] Start token request validation
2018-01-12 15:45:53.852 -05:00 [DBG] Start validation of refresh token request
2018-01-12 15:45:53.858 -05:00 [DBG] refresh_token grant with value: 2d2d40b1d6254c9597d633c077ad13c0290954e28f717592570d4937055d3172 not found in store.
```
Based on this it looks like I need to store the refresh token on the given user record (or DBContext), or something to that effect, Would that be the correct assumption? Reason I ask is I've connected Identity to an existing DB without the standard fields.

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/release/topics/deployment.html

**Comment by ryanhmaas** [comment]
Thanks, I took a look at that. I do have a `PersistentGrants` table that I created manually (with the needed fields using the provided SQL script) and have configured 

```
.AddOperationalStore(options =>
                {
                     options.ConfigureDbContext = builder =>
                         builder.UseSqlServer(Configuration.GetConnectionString("ConnectionString"));
                })
```

as well as

```
                              .AddTransient<IPersistedGrantStore, PersistedGrantStore>();
```

per all the docs I've read. I only want Operational data (refresh tokens, etc) to be stored using Entity and I know this is doable. However, I don't see any records being dropped into the table once I login/get an access token. Does any data need to be seeded? Otherwise I don't think I'm missing anything. I'm also testing locally, would that affect results? The store does get instantiated (I hit a breakpoint in the constructor) too so I verified it's being used.

Thanks again.

**Comment by brockallen** [comment]
No records sounds like you're simply not using any flows that use them.

**Comment by ryanhmaas** [comment]
I'm using Resource Owner flow - I was under the assumption that it was supported?

For instance, the used client is 

```
 new Client
{
    AccessTokenType = AccessTokenType.Reference, //unsure if this is needed
    ClientId = "ro.client",
    AllowOfflineAccess = true,
    RefreshTokenExpiration = TokenExpiration.Sliding, //when refreshing the token, the lifetime of the refresh token will be renewed (by the amount specified in SlidingRefreshTokenLifetime)
    RefreshTokenUsage = TokenUsage.ReUse,
    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
    ClientSecrets =
    {
        new Secret("secret".Sha256())
    },
    AllowedScopes = {"api1", StandardScopes.OfflineAccess}
}
```

and in my `AddIdentityServerAuthentication` call I am setting the `ApiSecret` property. I understand all I need to do is inject my implementation (as I did above) of the `PersistedGrantStore`. I can provide the remainder of my `Startup.cs` class if any of the above does not seem to be problematic.

**Comment by ryanhmaas** [comment]
I'm closing this - what you suggested work. I was using the deployed endpoint instead of the localhost one when testing...d'oh.

Sorry.
