### ISSUE TITLE
Convert Reference Tokens from IdentityServer3 to IdentityServer4?

### ISSUE THREAD

**Issue by akiander** [IdentityServer/IdentityServer4#1987]
We are upgrading our site from IdentityServer3 to IdentityServer4. We have thousands of people using our mobile app that consumes the reference tokens stored in IdentityServer3. We use the entity framework storage for those tokens. 

Is there any way to gain access to those reference tokens so we can store them in IdentityServer4 when we go live with the upgraded version? 

The schemas look different between 3 and 4, and I can't see how I can convert them over. 

I want to avoid forcing all of those users to login in again just because we upgraded. Any tips or ideas on how to do this?

**Comment by brockallen** [comment]
The devil's in the details, but in theory you could implement the store yourself and read from the old DB and map to the new structure. I've not tried myself, though :)

**Comment by akiander** [comment]
I'm already using the default entity framework implementation for storing reference tokens... [this one](https://github.com/IdentityServer/IdentityServer3.EntityFramework).

Identity Server 4 appears to require [this new version](https://github.com/IdentityServer/IdentityServer4.EntityFramework). 

I just want to convert my existing reference tokens from version 3 to version 4 so my existing mobile clients aren't forced to login again when I upgrade. 

Is that possible with the default implementation?

**Comment by brockallen** [comment]
We don't have anything built-in for this, sorry.

**Comment by akiander** [comment]
Okay, thanks for the reply. We'll ask our customers to log back in to get new reference tokens once we upgrade. It would be beneficial for future upgrades to provide a path for migrating the tokens.

**Comment by manojkgarg** [comment]
I have similar situation.
Is anything available now for migrating tokens from IDM3 to IDM4.

**Comment by wilson85** [comment]
I've been working on something which will migrate reference tokens from is3 to is4, it's here for anyone with this problem: https://gist.github.com/wilson85/b3963c000efbe00917a51c3cd27f0115
