### ISSUE TITLE
Request: Make DefaultRoutePaths public

### ISSUE THREAD

**Issue by MV10** [IdentityServer/IdentityServer4#1988]
Given that IdentityServer4 considers UI an external implementation concern, it would be helpful if the [`DefaultRoutePaths`](https://github.com/IdentityServer/IdentityServer4/blob/release/src/IdentityServer4/Constants.cs#L187) where Identity Server expects to find UI support was publicly available. I have a different folder and page system (Identity Server is just part of what this server does), so I define routes to match what Identity Server expects, but I would prefer to reference your constants rather than hard-coding a copy of those values.

```csharp
services.AddMvc(options =>
{
    options.SslPort = 5000;
    options.Filters.Add(new RequireHttpsAttribute());
})
.AddRazorPagesOptions( options =>
{
    options.Conventions.AddPageRoute("/OpenIdConnect/Login", "/account/login");
    options.Conventions.AddPageRoute("/OpenIdConnect/Logout", "/account/logout");
    options.Conventions.AddPageRoute("/OpenIdConnect/Consent", "/consent");
    options.Conventions.AddPageRoute("/OpenIdConnect/Error", "/home/error");
});
```

**Comment by MV10** [comment]
Forgot to follow up, but for this to be useful they'd have to be expressed as routes (versus fragments with a leading slash that could be used to build a URI, which is how I'd characterize the constants you have now). The correct code is shown below. I wanted to be sure to mention it, in case that's too implementation-specific for you to expose them that way.

```
.AddRazorPagesOptions( options =>
{
    options.Conventions.AddPageRoute("/OpenIdConnect/Login", "account/login");
    options.Conventions.AddPageRoute("/OpenIdConnect/Logout", "account/logout");
    options.Conventions.AddPageRoute("/OpenIdConnect/Consent", "consent");
    options.Conventions.AddPageRoute("/OpenIdConnect/Error", "home/error");
});
```

**Comment by brockallen** [comment]
We support the ability to tell IdentityServer the paths to redirect to for login, consent, error, etc. Is that not sufficient for what you need? This one, for example: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/Options/UserInteractionOptions.cs#L20

**Comment by MV10** [comment]
Interesting, I missed that one -- it does the job. Thanks!
