### ISSUE TITLE
Acquire token with C/C++ API?

### ISSUE THREAD

**Issue by ChristianRMKoerber** [IdentityServer/IdentityServer4#1989]
[Question only, could not find out how to mark this appropriately]

Is there any known way to acquire a token from Identity Server 4 with a C/C++ API?
I am specifically interested in something similar to Quickstart 2 (Resource Owner Passwords) where the client, a custom device, neither has a web browser, nor runs .NET Core and might not even run under Linux but some lower level OS.

**Comment by leastprivilege** [comment]
Sure - as long as you client can do HTTP requests.

https://tools.ietf.org/html/rfc6749

**Comment by ChristianRMKoerber** [comment]
Thanks for the pointer. And indeed this works really well.
