### ISSUE TITLE
 identityserver4  used in an existing project

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer4#1990]
hi 
  i have many client projects,that's is used Python|Php|Nodejs|asp.net(not .net core).
  i want use identityserver4 but the mvc middle is .net core,so how can i use in my exist asp.net(not .net core).
  i find the identityserver3 is not .net core,but i want use your best and new identityserver4.
  how can i do it
                                                                                    thanks very much

**Comment by leastprivilege** [comment]
IdentityServer4 itself must run in an ASP.NET Core v2 application (either on .NET Core or .NET Framework).

The client can run on any platform.
