### ISSUE TITLE
How to validate tokens in API if I have many issuers?

### ISSUE THREAD

**Issue by yahya99223** [IdentityServer/IdentityServer4#1991]
Hi, for some reason I have multiple issuers that provide access-tokens, how can I validate a specific token using its issuer? how can I set authority to have value of issuer?

Tried something like:

JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();
        app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
        {
            Authority = variable,
            DelayLoadMetadata = true,
        });

Where Authority is a variable, but it looks like the authority would be registered once at startup.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
