### ISSUE TITLE
Question: Check the auth server if the user is logged in via XHR or some other background method.

### ISSUE THREAD

**Issue by EssyTech** [IdentityServer/IdentityServer4#1992]
I see a way to check the server to see if the user is logged in via the browser method using the url with connect/authorize endpoint.  This works fine and give the right feed back via url string, however, I think there must be a better way to do this.  Here is my situation:

I have 3 applications all using identity server for SSO.  When the user switches between applications I want to be able to check to see if the user is authenticated and if they are, the site will go ahead and run the no prompt login scenario.  However, if they are not I want to do nothing.  

I can get this working via initial redirect checks via the connect/authroize end point to get the state, however, the browser jumping between redirects as soon as the user enters the site is not ideal.  Is there a way to do this via XHR or an Iframe solution like checksession end point?

Thank you for any help.

**Comment by brockallen** [comment]
You can make requests to the authorization endpoint in an iframe, yes. Having said that, 
this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
