### ISSUE TITLE
Internal web client + public mobile app = 2 IdentityServers?

### ISSUE THREAD

**Issue by nicbavetta** [IdentityServer/IdentityServer4#1993]
My team is currently building a system comprised of an internal facing web client and a public facing mobile application.

The web client is responsible for administering the mobile app and will only be used by employees within our organization. The mobile app can be used by anyone in the public.

I have previously configured an IdentityServer that handles authentication for applications internal to our organization. I would like to use this implementation for authentication of the admin web client as it sits on top of a UserStore specific to the organization. I assume I need to simply configure a new IdentityServer that can sit on top of a new public or application-specific user store but am struggling with integration design when considering the following requirement:

The internal web client and mobile app will both need to make use of a common, application-specific API. 

Can I configure the API to have two authorities (sounds odd to me)? Do I configure one of the IdentityServers to act as an IDP for the other IdentityServer? What is the suggested approach here?

Thanks!

**Comment by nicbavetta** [comment]
How can I maintain separation of user stores with only one IdentityServer? I do not want to combine internal users and public user schemes.

**Comment by leastprivilege** [comment]
You can connect to different user stores based on client_id or any other parameter you pass on the authentication request.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by nicbavetta** [comment]
Should be. Thanks guys!
