### ISSUE TITLE
2 x IS4 and nginx load balancing

### ISSUE THREAD

**Issue by Meldow** [IdentityServer/IdentityServer4#1994]
Hey guys,
first of all, awesome job with IS, have been developing my single sign-on system for my company and this has been fundamental

Now, I have the following scenario
**Server A**: 
A.IdentityServer
A.WebApp

**Server B**:
B.IdentityServer
B.WebApp

1 - user connects to WebApp, 
- nginx redirects him to A.WebApp
- then A.WebApp redirects him to IdentityServer(A)
- user signs in, everything is fine

2 - we **shut down Server A**
- nginx now redirects the user to B.WebApp
- B.WebApp has no session cookie, therefore redirects to IdentityServer(B)
- **B.IdentityServer has no session cookie** (or the cookie is not for this app), therefore prompts the sign in form 
:(

.NETCore session cookies are not valid for A.IdentityServer and B.IdentityServer, so we need to re-sign in

Any idea how to keep session across servers?
Sticky session is not useful here (since we kill the original server)
Reference tokens have the same issue

Could really use some pointer here, 
Thanks in advance
Alex

**Comment by leastprivilege** [comment]
You should be able to share the IdentityServer session between both instances. Sounds like an ASP.NET Core configuration issue. Have you set up data protection correctly?

**Comment by Meldow** [comment]
thank you for the response.
have an idea where to look at, will answer as soon as I have some new info
Cheers!

**Comment by brockallen** [comment]
Any update?

**Comment by Meldow** [comment]
Helloes, I'm still wrapping some API stuff and in the next week I must get this fixed, so will be resolving this very soon

Thanks for the concern

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
