### ISSUE TITLE
Auto login between projects

### ISSUE THREAD

**Issue by Ramon-Balaguer** [IdentityServer/IdentityServer4#1995]
Hello,

I need help, to find a solution to a problem.

In our company, we have 2 projects (Project A, Project B) Each project has its own users (and different types) but they share the same database:

**Project A**: this project does not have direct access to the final web browser (there is a system in between), this project returns an access link for Project B with the users of Project A.

**Project B**: this project has an IdentityServer4 server to login with the users of Project B.

We want to create a link from Project A to do auto login (on the IdentityServer4 server) on Project B with the user of Project B.

**Comment by leastprivilege** [comment]
The link has to go to Project B - which in turn triggers authentication. That being said...

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
