### ISSUE TITLE
How to validate refresh tokens against upstream IdP?

### ISSUE THREAD

**Issue by mhellsten** [IdentityServer/IdentityServer4#1996]
From what I understand, when using upstream IdPs in IdentityServer, after the user authenticates at the upstream IdP, IdentityServer issues its own tokens back to the client, and then the upstream IdP is out of the picture until the the user has to authenticate again user their credentials. I'm primarily thinking of the Authorization Code flow with long-lived refresh tokens.

The problem I'm having is that if the user is locked out (or otherwise deactivated) in the upstream IdP, IdentityServer will potentially continue to issue access tokens for a long time after, which could be a major security concern at certain organizations. 

Would it be reasonable and practical for me to implement my own IdentityProvider that maintains the upstream refresh token for the user, so that when the client tries to redeem its refresh token, the IdentityProvider would issue a new access token only if it can also redeem the upstream refresh token against the upstream IdP (with the assumption that the upstream IdP would check the user record before issuing a new access token)?

`[Client] <--downstream token validation--> [IdSrv] <--upstream token validation--> [AAD]`

Thanks!

**Comment by brockallen** [comment]
We support checking if the user is allowed to obtain new tokens via the profile service via the `IsActive` method: http://docs.identityserver.io/en/release/reference/profileservice.html#isactivecontext

If you can implement this to  contact your upstream IdP, then it would work.

**Comment by phoenixjun** [comment]
Is there a way in the profile service to access the scope and grant in the token request? in our scenario, there are multiple upstream IdP and we need to validate in different upstream IdP based on the request context.
