### ISSUE TITLE
Pull Samples: error - cannot stat - filename too long (Windows 10)

### ISSUE THREAD

**Issue by kosa-gyula-77** [IdentityServer/IdentityServer4#1997]
When checking out a68958d of IdentityServer4.Samples, the following error is got:

_Updating dcbcc10..a68958d
error: cannot stat 'Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/PersistedGrantDb/20180109200712_InitialIdentityServerPersistedGrantDbMigration.Designer.cs': Filename too long_

OS: Windows 10
Git client: Atlassian SourceTree

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by Nuschler** [comment]
I had same issue, enabling core.longpaths as git config option
git clone -c core.longpaths=true https://github.com/IdentityServer/IdentityServer4.Samples.git

This solution was found as some of the answers here...
https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows

**Comment by kosa-gyula-77** [comment]
@Nuschler , Your solution has resolved the issue! Thanks.
