### ISSUE TITLE
How to disable url redirect to LoginUrl while not logged in? And return 401 unauthorized status instead

### ISSUE THREAD

**Issue by mokeyish** [IdentityServer/IdentityServer4#1999]
I configured UserInteractionOptions`UserInteractionOptions.LoginUrl=null`,But it cause an validating error.

**Comment by leastprivilege** [comment]
Why do you want to do that?

**Comment by mokeyish** [comment]
@leastprivilege My API server and IdentityServer has runing together，The font-end  I have used Angular already,dosen't need to redirect LoginUrl

**Comment by leastprivilege** [comment]
so why would you then do a request to the authorize endoint?

**Comment by mokeyish** [comment]
@leastprivilege I have  solved it.
![image](https://user-images.githubusercontent.com/16131917/35075988-0ffc0adc-fc31-11e7-82cc-395c384b112c.png)
