### ISSUE TITLE
Log noise when using multiple secret validators

### ISSUE THREAD

**Issue by Lutando** [IdentityServer/IdentityServer4#200]
I use a combination of secret validators (ones provided out of the box by you guys)

As I understand it when trying to validate secrets, IdentityServer4 will enumerate through your validators to see if one matches a secret that is being validated.

However quite often even though the secret is valid for a given validator, a validator unsuitable for the secret would try and validate the secret causing these messages to come through the logs

`Secret: [[Secret Description]] uses invalid hashing algorithm.`

Also I get the following when trying to validate my implicit clients which have no secrets

`No client secret found`

Now these two messages are clogging up my logs and im wondering if this is intended behavior or how do I omit this besides adding some sort of filter to my log provider which I would prefer to not do.

Info:
Using identityserver beta4-update1
Adding my validators using the following on the IDS4 builder 

```
builder.AddSecretValidator<HashedSharedSecretValidator>();
builder.AddSecretValidator<PlainTextSharedSecretValidator>();
```

Maybe this is not a Error level log but a warning level log? since it does not particularly mean that your validation request has failed. We typically log Error level and above to e-mail.

**Comment by brockallen** [comment]
Sure, we can take a look.

**Comment by leastprivilege** [comment]
Why are you using both hashed and plain text at the same time?

**Comment by Lutando** [comment]
For legacy reasons to be honest.Some of our clients have thier secrets stored in plaintext while the others are hashed. The vast majority of them are stored as hashed secrets. We also have a sort of portal to manage clients and we would like to have some of these client_ids and client secrets in 'human' readable form for ease of remembering them. These are mostly for our internal prototype projects.

**Comment by leastprivilege** [comment]
OK - will have a look.

but I don't understand this part:

>Also I get the following when trying to validate my implicit clients which have no secrets

>`No client secret found`

under which circumstances does this happen?

**Comment by Lutando** [comment]
Ahh my apologies they are two separate issues. I was being an idiot :) the latter issue isnt part of this one at all, just my configuration silliness.

**Comment by leastprivilege** [comment]
done
