### ISSUE TITLE
IdentityServer setting idp in access token to external provider. Is this right?

### ISSUE THREAD

**Issue by domrin123** [IdentityServer/IdentityServer4#2001]
Hi,

When using an IdentityServer with both Local (username + password) and Windows (as an external provider) - If I log in using Local the `idp `in the access token is set to "Local" and if I use Windows auth it is set to "Windows". Obviously the `sub `is set to the same userid regardless of what I use.

In the scenario where I am passing the access token from a SPA to an API and the API wants to create an account for that user (using ASP.NET Identity) I would want to use the `idp `field to define the LoginProvider in UserLogins for that account. If later on they login using a different method, then the user won't be found as the `idp `will be different, even though the `sub `is the same.

Shouldn't (or is there a way for) IdentityServer define `idp `as the same thing across the board, regardless of what external auth was used? After all, the application is trusting the IdentityServer, not the external provider. 

If I'm mistaken, should I not use the `idp `in this case?

Thanks

**Comment by brockallen** [comment]
IdentityServer allows you to configure what claims go into the access token based on the API's scope. If the client is using the "user registration" API, then you could put the IdP used for login and the IdP's unique id for the user. That would give you the info to associate the sub with the external IdP, no?

**Comment by brockallen** [comment]
Also, you'd think you'd have already done that associate from within IdentityServer when the user logs in, no?

**Comment by domrin123** [comment]
Yep you're correct. When a new user hits the id server they either create an account using the registration form or an account is created with an associated windows logon using standard ASP.NET Identity.

My question was more related to if a separate application came along (such as a SPA with an API sitting behind it) and used the idsrv for auth (but potentially other external providers if it liked). The SPA would pass the access token along to the API, and the API could potentially use that sub + idp as a way to identify the user. 

However if that idp can change based on what they used to auth with idsrv, they might not be able to match the user to someone who has already used that api. Hope that's made it a bit clearer. Thanks

Hope that makes this a bit clearer.

**Comment by brockallen** [comment]
`sub` is all you should need to identify the user, and it's unrelated to how the authentication was performed.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by domrin123** [comment]
Apologies, thought I replied to this. Go ahead.
