### ISSUE TITLE
Xamarin + External Providers + Identity Server 4

### ISSUE THREAD

**Issue by hdsmachado** [IdentityServer/IdentityServer4#2004]
Hi guys,

I wanna know if anyone could help me to solve my "issue" using Xamarin + External Providers + Identity Server 4
My scenario is this:

1) I have an Identity Server configured to accept external providers, when people are using the "admin" web page they can register/sign in using their account created in our own system OR they can use their Facebook/Google/Microsoft account. This is my middleware configuration:

```
public void ConfigureServices(IServiceCollection services)
{
	// Add framework services.
	services.AddDbContext<ApplicationDbContext>(options => {
		options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
	});

	services.AddIdentity<ApplicationUser, IdentityRole>(o =>
						{
							// configure identity options
							o.Password.RequireDigit = false;
							o.Password.RequireLowercase = false;
							o.Password.RequireUppercase = false;
							o.Password.RequireNonAlphanumeric = false;
							o.Password.RequiredLength = 6;
							o.SignIn.RequireConfirmedEmail = true;
						})
			.AddEntityFrameworkStores<ApplicationDbContext>()
			.AddDefaultTokenProviders()
			.AddErrorDescriber<LocalizedIdentityErrorDescriber>();

	// Add application services.
	services.AddTransient<IEmailSender, SendGridEmailSender>();
	services.AddTransient<ISmsSender, AuthMessageSender>();


	var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
	var certificateFile    = Path.Combine(Directory.GetCurrentDirectory(), Configuration["Certificate:FileName"]);

	
	services.AddIdentityServer()
			.AddSigningCredential(new X509Certificate2(certificateFile, Configuration["Certificate:Password"]))
			.AddResourceOwnerValidator<ResourceOwnerPasswordValidator>()
			// this adds the config data from DB (clients, resources)
			.AddConfigurationStore(options =>
			{
				options.DefaultSchema      = "identityservice";
				options.ConfigureDbContext = builder =>
				  builder.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"),
									   db => db.MigrationsAssembly(migrationsAssembly));
			})
			// this adds the operational data from DB (codes, tokens, consents)
			.AddOperationalStore(options =>
			{
				options.DefaultSchema      = "identityservice";
				options.ConfigureDbContext = builder =>
				  builder.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"),
									   db => db.MigrationsAssembly(migrationsAssembly));
			})
			.AddAspNetIdentity<ApplicationUser>();
	
	// Third-party authentication GOES HERE
	services.AddAuthentication()
			.AddGoogle(googleOptions => {
				googleOptions.ClientId     = Configuration["Authentication:Google:ClientId"];
				googleOptions.ClientSecret = Configuration["Authentication:Google:ClientSecret"];
			})
			.AddFacebook(facebookOptions => {
				 facebookOptions.AppId     = Configuration["Authentication:Facebook:AppId"];
				 facebookOptions.AppSecret = Configuration["Authentication:Facebook:AppSecret"];
			 })
			.AddMicrosoftAccount(microsoftOptions => {
				microsoftOptions.ClientId     = Configuration["Authentication:Microsoft:ApplicationId"];
				microsoftOptions.ClientSecret = Configuration["Authentication:Microsoft:Password"];
			});

	// Configuration
	services.Configure<AuthMessageSenderOptions>(Configuration);

	services.AddLocalization(opts => { opts.ResourcesPath = "Resources"; });

	services.AddMvc()
			.AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
			.AddDataAnnotationsLocalization();
}
```

2) I also have a mobile app (Android/iOS), and just like the web page, the users can choose what kind of account they are going to use. In this case, facebook authentication;

     
```
 public void OnCompleted(GraphResponse response)
        {
            if (_facebookLoginResult is null)
                throw new Exception("Failed to login with facebook account. The response of the server was empty");

            var objMe = JsonConvert.DeserializeObject<Dictionary<string, string>>(response.RawResponse);

            ((IAuthenticationController<FacebookLoginResult>)Button)?.SendAuthenticationResult(new FacebookAuthenticationResult
            {
                Status = AuthenticationStatus.Success,
                Result = new FacebookLoginResult(_facebookLoginResult.AccessToken.UserId,
                    _facebookLoginResult.AccessToken.Token,
                    FromUnixTime(_facebookLoginResult.AccessToken.Expires.Time),
                    _facebookLoginResult.AccessToken.ApplicationId,
                    objMe["email"],
                    $"{objMe["first_name"]} {objMe["last_name"]}")
            });
        }
```

In the web page process, when the user sign in using an external (eg. Google) the Identity Server calls the "ExternalLoginCallback" method which gets the AutheticateResult and then calls the "AutoProvisionUserAsync" which inserts the user data into the "AspNetUser..." tables.

My problem: Since google deprecated the authentication using web-views, I'm building native Xamarin components to provide external authentication for the users. 

- So, how can I configure my Xamarin app to save the user information (eg. FacebookAuthenticationResult) into my Identity DB?

- Is there a way which I can call the "ExternalLoginCallback" method and let the Identity Server do it's job? Because I don't have a "HttpContext" in my mobile app and this method uses "HttpContext.AuthenticateAsync" to retrieve some information.

Thanks!

**Comment by leastprivilege** [comment]
Instead of building a native login dialog - you should use the system browser instead.

See here: https://tools.ietf.org/search/rfc8252
and
https://github.com/IdentityModel/IdentityModel.OidcClient2

**Comment by cesairekent** [comment]
Good evening to you ... I have almost the same problem mine comes from the fact that after authentication with google I can not use the RegisterExternal method of identity

**Comment by TomCJones** [comment]
That whole concept of users allowing a native app from who-knows-where the ability to log them in "AS THE USER'S CLIENT" to access user owned resources is absolutely nuts. I am not disputing the fact that it is done, just the shear idiocy of it. I talked to a guy from Google who was pitching that as a safe idea; after all they "check" that the apps are legit, meaning from the web site that they claim to be from. Not legit in the sense of being a reliable user agent.

Peace ..tom
________________________________

**Comment by mattmiley** [comment]
I'm a total noob and just started researching this, but doesn't the SHA-1 hash take care of that part? https://developers.google.com/android/guides/client-auth

**Comment by cesairekent** [comment]
I already managed to recover access token and some user info thanks to xamarin Auth my problem comes from the fact that I do not know how to use this token from google with identity

**Comment by cesairekent** [comment]
Bonjour,
Je viens de signer la pétition "ETAT DU CAMEROUN : RIZ CAMEROUNAIS : LE
SCANDALE DU SIECLE A YAGOUA & MAGA ! ARRÊTONS ÇA !" et je souhaitais savoir
si vous voudriez nous aider en ajoutant votre signature.

Notre objectif est d'atteindre 1 500 signatures et nous avons besoin de
plus de soutiens. Pour en savoir plus et pour signer, c'est ici:

http://chng.it/2fJ65TDr9r

Merci!
Emmanuel Cesaire
