### ISSUE TITLE
Deploy Identityserver in a docker Linux container

### ISSUE THREAD

**Issue by OscarCanek** [IdentityServer/IdentityServer4#2005]
### Issue / Steps to reproduce the problem

I'm trying to deploy Identityserver for high availability in a docker container with Linux but always have the following error when I try to login through mvc. I'm using a pfx certificate.

This is how I configure the DataProtection:

```
services.AddDataProtection()
                .PersistKeysToFileSystem(dirInfo)
                .ProtectKeysWithCertificate(new X509Certificate2(Configuration["server:pfxFilePath"], Configuration["server:pfxPassword"]))
                .SetApplicationName(!string.IsNullOrWhiteSpace(Configuration["appName"]) ? Configuration["appName"] : "XXXXXXXXX")
                .DisableAutomaticKeyGeneration();
```

### Relevant parts of the log file

```

An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.

InnerException: 
ClassName : "System.InvalidOperationException"
Message : "The key ring does not contain a valid default protection key. The data protection system cannot create a new key because auto-generation of keys is disabled."
Data : null
InnerException : null
HelpURL : null
StackTraceString : " at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded) at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow) at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)"
RemoteStackTraceString : null
RemoteStackIndex : 0
ExceptionMethod : null
HResult : -2146233079
Source : "Microsoft.AspNetCore.DataProtection"
WatsonBuckets : null
```
This is the complete message:

[Log message](https://github.com/IdentityServer/IdentityServer4/files/1640589/e.2.txt)

PD: use a json viewer to see it i.e. http://jsonviewer.stack.hu/

**Comment by markphillips100** [comment]
Does encryption and decrpytion work without disabling key generation?

If it doesn't, is your certificate in the local machine store as I think it has to be (for decryption to work)?

**Comment by leastprivilege** [comment]
This question is really for Microsoft - check their docs on data protection or open an issue in the data protection repo.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
