### ISSUE TITLE
Identity Server - Chceck DB on every request - Force User Logout/Revoke Token

### ISSUE THREAD

**Issue by BrandonScharf** [IdentityServer/IdentityServer4#2010]
Is it possible to force IdentityServer to check a database for a field on every single request?

My example is a user logs into our single sign on through Identity Server using JWT tokens. According to previous issues/docs, JWT tokens cant be revoked through the revocation API call, so that's out the window.

Lets say this user logs into our application and after 15 minutes, an admin goes into user profile management, adjusts their permissions to certain tools and then saves those changes. The user and their token (which has those permissions stored in it) are never informed of this change and can continue using the site without being forced to login again to get the correct permissions. We are essentially looking for a way to force Identity Server on every single relying party page request (which should make a trip to the identity server app each time) to go out to a database, check if this user has had their account updated, and if so, log them out and require them to log back in to get the new updated permissions.

Is this possible?

I couldn't mark it as a question, so if you need to, please do.

**Comment by TomCJones** [comment]
Under the assumption that you actually want to use OpenID Connect, the site could hold the authz code and make requests to the id end-point for an id token as described in the spec.

3.1.3.1.  Token Request
A Client makes a Token Request by presenting its Authorization Grant (in the form of an Authorization Code) to the Token Endpoint using the grant_type value authorization_code, as described in Section 4.1.3 of OAuth 2.0 [RFC6749]. If the Client is a Confidential Client, then it MUST authenticate to the Token Endpoint using the authentication method registered for its client_id, as described in Section 9. 
The Client sends the parameters to the Token Endpoint using the HTTP POST method and the Form Serialization, per Section 13.2, as described in Section 4.1.3 of OAuth 2.0 [RFC6749]. 
The following is a non-normative example of a Token Request (with line wraps within values for display purposes only): 
  POST /token HTTP/1.1
  Host: server.example.com
  Content-Type: application/x-www-form-urlencoded
  Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW grant_type=authorization_code&code=SplxlOBeZQQYbYS6WxSbIA
    &redirect_uri=https%3A%2F%2Fclient.example.org%2Fcb

**Comment by brockallen** [comment]
> Is it possible to force IdentityServer to check a database for a field on every single request?

Did you read the docs on the profile service? http://docs.identityserver.io/en/release/reference/profileservice.html

> The user and their token (which has those permissions stored in it) are never informed of this change and can continue using the site without being forced to login again to get the correct permissions.

This is the wrong design of how to use of a centralized identity provider: 

http://policyserver.io/

**Comment by brockallen** [comment]
All set on this issue -- can we close?
