### ISSUE TITLE
Seed Not Working QS 8 and Combined?

### ISSUE THREAD

**Issue by ChristoKolander** [IdentityServer/IdentityServer4#2013]
Hello. Have been following along the Quick Starts to learn. Worked fine until, EF got involved.  "Combined_AspNetIdentity_and_EntityFrameworkStorage" (and QS 8) are giving me the error message = unauthorized_client. 

Maybe I am missing something, some feedback would be appreciated!

### Issue / Steps to reproduce the problem

My Steps: 1. Downloaded project. Could not get the tables into Local DB by just running sample application, so for all of the contexts I ran update-database - context nameofcontext - which worked fine. Registration of new user also worked, AspNetUsers got populated. However, when starting MVC application, I get this:

### Relevant parts of the log file

[14:09:45 Debug] IdentityServer4.EntityFramework.Stores.ClientStore
mvc found in database: False

[14:09:45 Error] IdentityServer4.Validation.AuthorizeRequestValidator
Unknown client or not enabled: mvc

Note: Token clearance keeps running, but no sign of seeding messages initially. Am I missing something? 
Note: Redirection does not work.

No hairs left....

**Comment by brockallen** [comment]
Did you run `dotnet run /seed` on the command line from the IdentityServerWithAspIdAndEF project?

**Comment by ChristoKolander** [comment]
Hello. I did Not. Maybe I should have realized that just reading the code inside Program.cs - but I didn't. Lesson learned I hope. Thank's a lot, working perfectly.

/C.

________________________________
Från: Brock Allen <notifications@github.com>
Skickat: den 22 januari 2018 14:43
Till: IdentityServer/IdentityServer4
Kopia: Chris Kol; Author
Ämne: Re: [IdentityServer/IdentityServer4] Seed Not Working QS 8 and Combined? (#2013)


Did you run dotnet run /seed on the command line from the IdentityServerWithAspIdAndEF project?
