### ISSUE TITLE
PostLogoutRedirectUri not always available

### ISSUE THREAD

**Issue by jtheisen** [IdentityServer/IdentityServer4#2014]
### Issue / Steps to reproduce the problem

I'm basing this on Quickstart6.

On clicking logout on the client (MvcClient), you get to the logged-out page of the identity server - but there's no post-logout-redirect-uri.

In fact I've seen it once - but only the first time I tried. In all of my subsequent login-logoff maneuvers the uri is missing. In the debugger I can see that the result of `BuildLoggedOutViewModelAsync` doesn't contain any information about on behalf which client we logged out.

What binds the "logout id" to the client anyhow?

### Relevant parts of the log file

```
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method IdentityServerWithAspNetIdentity.Controllers.AccountController.Logout (IdentityServerWithAspNetIdentity) with arguments (IdentityServer4.Quickstart.UI.LogoutInputModel) - ModelState is Valid
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler:Information: AuthenticationScheme: Identity.Application signed out.
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler:Information: AuthenticationScheme: Identity.External signed out.
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler:Information: AuthenticationScheme: Identity.TwoFactorUserId signed out.
IdentityServerWithAspNetIdentity.Controllers.AccountController:Information: User logged out.
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor:Information: Executing ViewResult, running view at path /Views/Account/LoggedOut.cshtml.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action IdentityServerWithAspNetIdentity.Controllers.AccountController.Logout (IdentityServerWithAspNetIdentity) in 211.0553ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 235.3822ms 200 text/html; charset=utf-8
```

**Comment by brockallen** [comment]
You'd have to add that in your version of the account controller. The short of it is that is that certain aspects of the the ASP.NET Identity template doesn't lend itself to mixing well with being a token server. We're in the middle of reworking the template now, in fact: https://github.com/IdentityServer/IdentityServer4/pull/2008

**Comment by jtheisen** [comment]
But the sample already has support for that built-in:

    @if (Model.PostLogoutRedirectUri != null)
    {
        <div>
            Click <a class="PostLogoutRedirectUri" href="@Model.PostLogoutRedirectUri">here</a> to return to the
            <span>@Model.ClientName</span> application.
        </div>
    }

It just doesn't always work and I don't see what made it work once.

I'm also don't think I need ASP.NET Identity - I'm not doing anything in the IdentityServer app apart from what's in the samples.

**Comment by brockallen** [comment]
> It just doesn't always work and I don't see what made it work once.

Ah, ok. In that case it's usually because the client doesn't send the id_token_hint and/or post_logout_redirect_uri, or the user's session has changed from the one the client gets. All of these aspects are covered in the spec: https://openid.net/specs/openid-connect-session-1_0.html

**Comment by jtheisen** [comment]
It's working now in the sample (not sure what the issue was). I still can't get it to work in another client that's still Owin: `UseOpenIdConnectAuthentication` does indeed not send the id_token_hint and/or post_logout_redirect_uri. Can it be made to do that?

**Comment by brockallen** [comment]
> Can it be made to do that?

Correct, the Katana OIDC library was lacking. Look at the Microsoft docs and/or check our samples: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients
