### ISSUE TITLE
Google access token has no scope on refresh using refresh token

### ISSUE THREAD

**Issue by CoLang** [IdentityServer/IdentityServer4#2015]
Am currently developing an android app for writing some values google spreadsheet. Here am using google sign in for authorization, by using google sign in am able to get server auth code and  also getting access token from the following line
final String accessToken = GoogleAuthUtil.getToken(MainActivity.this, account, scope);

Next, am using GoogleAuthorizationCodeTokenRequest class to get refresh token using server auth code. Here am successfully retrieving refresh token and access token for the first time when the user signs in.

The problem where am facing the issue is in getting access token scope on its expiry using refresh token. 
final String accessToken = GoogleAuthUtil.getToken(MainActivity.this, account, scope);
In the above line am adding the required scope and getting the success access token and when I debug the access token I can able to see the scope which I have added.

But When I use the refresh token to get access token am missing the scope which I have added to the previous access token.

 For Sign in the process am using the Android SDK, whereas to refresh the access token am using REST API.

Please help me out to get the scope which I have added to the previous access token request. On Successful REST API am able to get access token but not the scope.

Thank you in advance.

**Comment by brockallen** [comment]
What does your question have to do with IdentityServer?
