### ISSUE TITLE
identity server doesnot Log out properly

### ISSUE THREAD

**Issue by ChaosCriminal** [IdentityServer/IdentityServer4#2017]
![idenityerror](https://user-images.githubusercontent.com/1835138/35242171-adbd1af6-ff6d-11e7-8c42-ba84d4773a3a.PNG)

I am trying to implement IdentityServer4 but when I try to log out, its redirect to empty page . I looked for logout view but there is no logout view. I also tried to find identityserver4 account controller but ı donot know how I can access account controller because I think there is no logout method. 

Logout method is exist in identityserver4.QuickStart project but not exist in IdentityServer4.AspNetIdentity so I tried to copy from identityserver4.QuickStart add to IdentityServer4.AspNetIdentity and it didnot work obviously because in IdentityServer4.AspNetIdentity uses identityServer4's account controller not aspnet default account controller. I wanted to use identityserver4.QuickStart however there is no register method in AccountController . I am stuck . Could you tell me what can I do to get over this problem or could you send me Register method's code to add identityserver4.QuickStart AccountController

**Comment by brockallen** [comment]
> I am trying to implement IdentityServer4 but when I try to log out, its redirect to empty page . I looked for logout view but there is no logout view. I also tried to find identityserver4 account controller but ı donot know how I can access account controller because I think there is no logout method.

See the quickstart UI or templates for this: https://github.com/IdentityServer/IdentityServer4.Quickstart.UI

> Logout method is exist in identityserver4.QuickStart project but not exist in IdentityServer4.AspNetIdentity so I tried to copy from identityserver4.QuickStart add to IdentityServer4.AspNetIdentity and it didnot work obviously because in IdentityServer4.AspNetIdentity uses identityServer4's account controller not aspnet default account controller. I wanted to use identityserver4.QuickStart however there is no register method in AccountController . I am stuck . Could you tell me what can I do to get over this problem or could you send me Register method's code to add identityserver4.QuickStart AccountController

You need to build your UI to work the way you want it to. Our quickstarts and samples are just that -- samples. You will need to build the UI to meet your own requirements.

**Comment by brockallen** [comment]
We also have docs on the topic: http://docs.identityserver.io/en/release/topics/signout.html

**Comment by ChaosCriminal** [comment]
thank you for your answer 
I checked these links but There is no Register method in AccountController thats the problem I am looking for an answer

**Comment by TomCJones** [comment]
just start an asp.net core Web mvc app project with msft visual studio and change authentication to  Individual User accounts, that will create a registration page
or if you want to see what it looks like see this demo http://idesg-rp.azurewebsites.net/

**Comment by ChaosCriminal** [comment]
http://docs.identityserver.io/en/release/quickstarts/6_aspnet_identity.html 

i followed this document and i made same project as well as there is register view however there is no logout view as i mention my first entry. 

also i want to skip this logout page because   when i logout from my project i want to redirect my main page , i need  to access logout method in identityserver accountcontroller to redirect to my mainpage

**Comment by ChaosCriminal** [comment]
I checked register page at this  http://idesg-rp.azurewebsites.net/ address but it isnot work

**Comment by brockallen** [comment]
As mentioned above - the UI in IdentityServer is your responsibility. Our templates show various pieces to how you might build it, but they're just templates. You need to understand the interaction between IdentityServer and those UI pages, and then you need to implement them according to your requirements. We can't write all of that code for you.

**Comment by TomCJones** [comment]
sorry about that - I had added a TODO comment on the lack of web page validation for user names, I took the comment out and this now seems to work http://idesg-rp.azurewebsites.net/
