### ISSUE TITLE
Setting PublicOrigin does not change the RedirectUrl passed to the external login provider through OpenIdConnect

### ISSUE THREAD

**Issue by schwarzie2478** [IdentityServer/IdentityServer4#2019]
IdentityServer is running on server behind a loadbalancer.
The Load balancer takes care of the https protocol.
Our application server doesn't know about it.

As shown in the article
[https://leastprivilege.com/2017/10/09/new-in-identityserver4-v2-simplified-configuration-behind-load-balancers-or-reverse-proxies/](url)
I set the PublicOrigin to the https url.

Now the well-known configuration reflects the url as you should call it from outside.

I configured Identityserver to be able to log into Azure with a configuration similar to this example I found in the ID4 repo:
`                .AddOpenIdConnect("aad", "Azure AD", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.SignOutScheme = IdentityServerConstants.SignoutScheme;

                    options.Authority = "https://login.windows.net/4ca9cb4c-5e5f-4be9-b700-c532992a3705";
                    options.ClientId = "96e3c53e-01cb-4244-b658-a42164cb67a9";
                    options.ResponseType = "id_token";
                    options.CallbackPath = "/signin-aad";
                    options.SignedOutCallbackPath = "/signout-callback-aad";
                    options.RemoteSignOutPath = "/signout-aad";
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role"
                    };
                })`

The login flow is initiated well but Azure complains that the redirect url is invalid --> namely
RedirectUrl  should be   https://ids.hosted.com
but instead                     http://ids.hosted.com    is passed to Azure, but the redirect doesn't work then!

How do I get the https url to be used in the redirectflow from Azure.

**Comment by brockallen** [comment]
This is an issue to ask Microsoft, since that's their plumbing.

**Comment by schwarzie2478** [comment]
Thanks for your resonse,  

I solved the problem by doing something different than PublicOrigin PublicOrigin didn't work for me, but this did work:
I added a OWin block ( as the first one!) that sets the scheme to https when the host is the url hosted as https.

`            app.Use(async (context, next) =>
            {
                var log = loggerFactory.CreateLogger<Startup>();
                if (context.Request.Host.Host.Contains("mycompany.com"))
                {
                    log.LogInformation("Setting scheme of request to https");
                    context.Request.Scheme = "https";
                    HostString httpsHostString = new HostString(context.Request.Host.Host, 443);
                    context.Request.Host = httpsHostString;
                }
                await next.Invoke();
            });`
