### ISSUE TITLE
AddInMemoryUsers inconsistent (List vs IEnumerable)

### ISSUE THREAD

**Issue by AndyPook** [IdentityServer/IdentityServer4#202]
AddInMemoryUsers takes a List whereas others take IEnumerable.
It's argued that input args should be of the least specific type.

CLA (thinktecture.IdentityServer) signed
PR to follow

**Comment by brockallen** [comment]
In IdSvr3 it was a list because it needed to be mutable. I don't know about IdSvr4 yet if we still need it that way.

**Comment by AndyPook** [comment]
Hmmm, ok... 
It looks like the LoginService (in Host) does need to add to the collection (shouldn't it be InMemoryLoginService?). But the services in IS4 do not (at the moment)

I bumped into this because I tried to use a different collection type. List can be a little constraining.
It looks like the direction is for IS4 to be "readonly" in relation to the "stores". It's another parts responsibility to maintain the stores.
It _could_ be argued that AddInMemoryUsers should take IEnumerable and LoginService should take ICollection. It's then up to the dev to pass the right instance into each to achieve the desired effect.

**Comment by PivotalAnimal** [comment]
I abstracted the methods from LoginController using interfaces. One for Cookie Handling and one for in memory / database operations. It uses IEnumerable. What I haven't figured out is the best way to implement AutoProvisionUser using AspIdentity as part of my solution. Any suggestions? [IUserService](https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore/blob/master/BlueConcord.IdentityServer.EntityFrameworkCore/Interfaces/IUserService.cs)

**Comment by AndyPook** [comment]
things always look simple when you first start. Then the detail devil sticks its head up.

Using the interfaces is "better" as it better expresses the needs of the dependent class. But, in this case, the same collection instance needs to be used by two dependents with different requirements. 

So you either
 1. Just use List (or ICollection) and accept that some classes (ie InMemoryProfileService) take a dependency that is over featured
 2. register the collection twice (IEnumerable and ICollection) but this may seem a little weird/awkward.

However, you could also argue that this shouldn't be a concern of IS4 at all. It only needs abstractions like IProfileService. This only seems like an issue because there are implementations like InMemoryXYZ within IS4.

Maybe the "solution" is to remove the InMemory implementations from IS4 and boil it down to its essentials. Would you ever use InMemory for any reason other than testing? Maybe they belong in the Host project which is a demo/sample/debugging construct. Maybe in a separate proj, "IndentiServer4.InMemory". Then it would sit as a peer with IndentityServer4.EF/TableStorage/DocumentDB/whatever.
(not sure what to think about the DefaultXYZ implementations)

So, from the library developers pov, you're just saying "here's what the library needs" (ie IProfileService and friends). Implementations of these services are a different concern (ie storage and admin).

Thoughts?

**Comment by mpoettgen** [comment]
See also #179.
I'm not sure, but InMemory may be a valid option for transient data (e.g. something like a RefreshToken), while for persistent data (Clients, Scopes, etc.) it would only be used for testing. So could be good to keep these apart (#208)

**Comment by brockallen** [comment]
Yea, just hold off on this for now, please. This month we're doing a lot of work on IdSvr, and for this particular issue we're not yet ready on a direction or what's needed. What you see now is just a snapshot in time of where we're going.

**Comment by leastprivilege** [comment]
closing for now. please open a new issue for the RC
