### ISSUE TITLE
Using IdentityServer server and client in same Asp.Net Core app without using a static Authority to work around DNS issues

### ISSUE THREAD

**Issue by joshmouch** [IdentityServer/IdentityServer4#2020]
I'd like to see if there's a way to tell `AddIdentityServerAuthentication()` to use the local Asp.Net Core app instead of passing in a static Authority URL.  I believe this would be done using the following properties.

```

options.IntrospectionBackChannelHandler = identityServerHttpMessageHandler;
options.IntrospectionDiscoveryHandler = identityServerHttpMessageHandler;
options.JwtBackChannelHandler = identityServerHttpMessageHandler;

```

But I'm not sure exactly how to create these message handlers to work with IdentityServer.

Here's the situation:

I have an Asp.Net Core app that is using IdentityServer and hosts both the idenityServer and the app consuming the IdentityServer.

The problem I have is that when you call AddIdentityServerAuthentication, you have to pass in an Authority. I configure this to point to the production URL of the web site (e.g. https://api.mysite.com).  However, I'm using Azure App Services with auto-scaling, and when a new instance is being created during an auto-scaling operation, DNS resolution is questionable.  This results in all sorts of 500 errors that I'm having a hard time fixing when the new instance is scaled out.  I think this is because the new instance is trying to access Azure's load balancer (at https://api.mysite.com), but can't.  Eventually, it starts working, but it's only after the whole "azure auto-scaling" process is complete.

So, I think the solution is to using the HttpMessageHandlers instead of passing in a statically configured Authority URL... I just don't know how.  Do you have any examples set up for this scenario?

**Comment by brockallen** [comment]
Those back channel handlers are mainly there for unit testing, so I've never tried to use them in a prod environment.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by joshmouch** [comment]
It's still an issue, as I have no way to host IdentityServer and the site using it in the same web app.  It mostly works, but certain scenarios (e.g. deployment testing, azure auto-scaling, etc.) faile when you can't point to an internal Authority rather than an external one.

**Comment by brockallen** [comment]
Two different authority URLs are two different token servers, at least that's how the specs work.
