### ISSUE TITLE
End Session Endpoint return 404 on "GET /account/logout"

### ISSUE THREAD

**Issue by Shadowman4205** [IdentityServer/IdentityServer4#2021]
Hello,

trying to logout using end session endpoin but getting 404. While login working well. Do i have to do something else in my identity server code for logout?

[LOG.txt](https://github.com/IdentityServer/IdentityServer4/files/1660696/LOG.txt)

**Comment by brockallen** [comment]
Those logs are very hard to read. Do you have a plain text version of them?

**Comment by Shadowman4205** [comment]
Any help?

**Comment by brockallen** [comment]
No -- I meant all the JSON wrapped around the actual log messages that app insights is adding. It's much easier to see the expanded log messages like from the console or file logger.

**Comment by Shadowman4205** [comment]
@brockallen sorry for inconvenience, i replaced the log with txt log file by copy-paste from visual studio console. The logs are not all object format so i do not know how make them fast to json.

**Comment by brockallen** [comment]
Any update on this?

**Comment by Shadowman4205** [comment]
@mackie1001 
At the moment i created this Action
```
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
```
what do you mean by 'You can customise the path via IDS4 config.'

**Comment by brockallen** [comment]
You might need one that supports GET. Check our quickstart host samples.
