### ISSUE TITLE
Best approach to transform and normalize claims from external authentication providers?

### ISSUE THREAD

**Issue by JohanPetersson** [IdentityServer/IdentityServer4#2022]
I couldn't find any information if it is OK to file an issue for questions, or if we should post them on SO instead. Sorry if this is not the right place for questions. Maybe you should update the readme with this information?

The backstory is that I have multiple external authentication providers configured, e.g. Facebook, MSA and so on. When the user has signed in through any of these I want to transform/normalize the claims and maybe add additional custom ones, e.g. roles, before the user is sent back to the client. This way my client doesn't have to care about which provider the user signed in through since all claims will be the same in the token. I.e. no need to transform the claims in the client.

I also want to do this based on which provider the user signed in with.

I've looked into using `UserClaimsPrincipalFactory<TUser>` (which supports DI) and then register my implementation with `AddClaimsPrincipalFactory`. Is this the preferred method?

I've also looked into replacing `SignInManager<TUser>` and then override the method `SignInAsync`, but if I change the claims here it's not reflected in the token sent to the client. Also the parameter `authenticationMethod` is null the first time a user signs in and has gone through the consent and email/username confirmation screen.

I also would like to stay away from replacing most of the code that's handled automatically in the `GetExternalLoginInfoAsync` and `ExternalLoginSignInAsync` methods that's called from the account controller.

I would assume that transforming claims from external providers would be a first-class citizen feature, but it's not so clear how and where to do it, so it's stored correctly in DB (given that ASP.NET Core Identity is used) and the token.

Thank you

**Comment by brockallen** [comment]
Yes, SO is a better place for these types of questions. I updated our issue template to reflect that. Thanks.

**Comment by ronnieoverby** [comment]
Nice to see the link to the SO post....

**Comment by JohanPetersson** [comment]
@ronnieoverby here's the link https://stackoverflow.com/questions/48410868/best-approach-to-transform-and-normalize-claims-from-external-authentication-pro. Unfortunately I don't think it's to any help.

**Comment by ronnieoverby** [comment]
@JohanPetersson Thanks anyway. 

@brockallen could you go answer that question on SO?
