### ISSUE TITLE
Using idsrv4 without nonce? Troubles with Katana.

### ISSUE THREAD

**Issue by jtheisen** [IdentityServer/IdentityServer4#2024]
I've disabled nonces in my Katana app like so:

    options.ProtocolValidator.RequireNonce = false;

Then idsrv4 isn't happy and tells me that my "nonce is not valid".

Is there a way to turn the nonce requirement off altogether?

I'm asking because

1. there are some unresolved issues in Katana regarding them, see [this](https://github.com/aspnet/Security/issues/390); I indeed see nonce cookies accumulating in my Katana test app that surely will at some point break the entire site due to the cookie information getting too large (it's amazing that they unleash this crap without warning).
2. Also the security degradation is not a regression from my current (non-federated, classic) login experience. (It is my understanding that nonces are only used to prevent replay attacks.)

**Comment by jtheisen** [comment]
In hindsight, I believe I tripped over this just yesterday when I couldn't log in to the Azure Portal because "the request headers are too large". Indeed the Azure Portal is also leaking such nonces.

**Comment by brockallen** [comment]
nonce is part of the sepc and it's required for implicit and hybrid flows, and that's what IdentityServer implements. I don't know why Microsoft has a flag to disable it.

**Comment by jtheisen** [comment]
I found more old conversation about this [here](https://github.com/IdentityServer/IdentityServer3/issues/1407) and [here](https://github.com/IdentityServer/IdentityServer3/issues/1124).

Ok, let's close this.
