### ISSUE TITLE
How do you get "acr_values" inside IProfileService implementation?

### ISSUE THREAD

**Issue by aneequrrehman** [IdentityServer/IdentityServer4#2025]
A lot of online documentation and help material suggest generating a claim inside `GetAuthenticateInfoAsync`. But `GetAuthenticateInfoAsync` isn't available either in IS4, or am I missing something?

**Comment by brockallen** [comment]
I don't follow how the subject of this issue relates to the comment part you wrote.

**Comment by aneequrrehman** [comment]
@brockallen My bad. I was trying to access `acr_values` specifically `tenant` inside `IProfileService` implementation. And I saw here at https://github.com/IdentityServer/IdentityServer4/issues/1363 something about `GetAuthenticateInfoAsync` to which you agreed, but I am unable to find this method.

**Comment by brockallen** [comment]
`GetAuthenticateInfoAsync` is unrelated to the authorize endpoint parameters.

**Comment by aneequrrehman** [comment]
Right. So how would you suggest accessing "acr_values" inside `IProfileService` implementation? I mean these are accessible using identity server interaction service, but that requires the `Request` which isn't available in `ProfileService`.

**Comment by brockallen** [comment]
What do you need them for? Seems like the wrong place.

**Comment by aneequrrehman** [comment]
Well, we have our roles dependent upon Tenant (one user can belong to multiple tenants) as well as the particular time of the year. So at first I am loading the default Tenant and the default Role under that tenant, but afterwards if the user switches their profile, I need to know which tenant they are switching to (or maybe to which role they are switching to) so I can load up relevant claims. That's why I am passing these from the client app to IS via acr_values.
Also the Admin can impersonate any user.
I am not sure if what I am doing is the right way to achieve this. But that's our scenario.

**Comment by brockallen** [comment]
Why not look at a tenant claim in the Subject?

**Comment by aneequrrehman** [comment]
@brockallen I am just trying to get my head around this. So `Tenant` is available in the middleware and in the Controllers using `_interactionService.GetAuthorizationContextAsync(context.Request.Query["returnUrl"])` but still I want to access this info inside ProfileService. 
So this way, let's say the user tried to switch to another tenant, that new tenant's name (or id) value will come as part of the request to the IS and then, using that Tenant value, I can load the appropriate claims e.g. StartRole, StartYearId etc. which are specific to our application. Or if the user tried to switch the role (under the same tenant), I can get that from acr_values (to which role they are trying to switch), and load appropriate claims.

Our requirement is actually working fine at the moment, but I believe it's a bit nasty. So what we are currently doing is loading everything up in the claims with the first ProfileService execution, and the claim values are actually JSON objects, and we make decisions from these JSON objects in the client application, which was fine until we have multiple client applications. So now we have to implement the same JSON object parsing etc in all the client applications, and we are trying to avoid that.

Any help is highly appreciated. Thanks

**Comment by brockallen** [comment]
>  but still I want to access this info inside ProfileService.

There's a context param with a Subject with claims. When the user logs in, issue a tenant claim.

**Comment by aneequrrehman** [comment]
But the user logs in once which means only the tenant for which user logged in will be in claims, when they try to switch the tenant, there is no login etc.

**Comment by brockallen** [comment]
> But the user logs in once which means only the tenant for which user logged in will be in claims, when they try to switch the tenant, there is no login etc.

There is an extensibility point for this called the interaction response generator -- look at overriding it to require the user to login if the conditions aren't right.

**Comment by aneequrrehman** [comment]
Thank you @brockallen. This worked like a charm. :)

**Comment by asharda1** [comment]
Hi Aneequrrehman, 
Can you please explain the complete implementation , as I have same issue

**Comment by HitDaCa** [comment]
In case anybody else gets stuck on this, following a possible approach to access all `acr_values` in your custom `IProfileService` class:

 ```
public class ... : IProfileService
{
    ...
    public virtual async Task GetProfileDataAsync(ProfileDataRequestContext context) {

        // Grab acr_values from Raw context
        var acr_values = new Dictionary<string, string>();
        
        var reqParamsDict = context.ValidatedRequest.Raw.ToDictionary();
        if (reqParamsDict.ContainsKey("acr_values"))
        {
            var raw = reqParamsDict["acr_values"].Split(' ', StringSplitOptions.RemoveEmptyEntries).ToList();
            acr_values = raw.Select(item => item.Split(':', 2, StringSplitOptions.RemoveEmptyEntries)).ToDictionary(s => s[0], s => s[1]); 
        }
        ...
    }
    ...
}
```

And the custom extension to easily turn the `NameValueCollection` returned by `context.ValidatedRequest.Raw` into a Dictionary.
```
 public static class SomeRandomExtensions
{
    public static IDictionary<string,string> ToDictionary(this NameValueCollection col)
    {
        return col.AllKeys.ToDictionary(x => x, x => col[x]);
    }
}
```

**Warning:** _The above code/approach is an example implementation approach which has not been tested and should therefore not be used in any production setup (IS4, version 2.3.2)_
