### ISSUE TITLE
Is the idserv.external cookie encrypted? Is it possible to spoof?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#2026]
It is my understanding that external providers set these with SignInAsync and that under the hood DataProtection is used to encrypt the cookie. Cookies are transmitted via SSL. Is this correct?

**Comment by brockallen** [comment]
Yes to all, and all of that has nothing to do with IdentityServer -- those are all features of ASP.NET Core.
