### ISSUE TITLE
MDM mobile app recommended flow/strategy

### ISSUE THREAD

**Issue by benoitbac** [IdentityServer/IdentityServer4#2029]
Hi and thanks for IS4 which is really nice product you offered us !
I'm sorry to ask for question here but it's quite difficult for me to try to find sort of answer about that :(
I would like to be able to authenticate via a mobile app MDM enrolled device , without user having to login as with a classical hybrid pkce flow,  on my IS4 openid IS , but I'm not able to find some advices or articles in order to be able to do that on a minimal safe way.
Is somebody maybe could give an advice or somewhere to look , I'm quite lost to be honest.
Thanks again guys, and long life for open source sharing nice guys !!!

**Comment by TomCJones** [comment]
there is no safe way.
The ROclients show a way.

**Comment by benoitbac** [comment]
Thanks Tomc , but what do toi mean n'y ROclients ?

**Comment by benoitbac** [comment]
Sorry for bad language on mobile, what do you mean by ROclients?

**Comment by TomCJones** [comment]
Quickstart #4 has one that I have used
lots here https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients/src

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
