### ISSUE TITLE
Defining a post login redirect url

### ISSUE THREAD

**Issue by monkeylumps** [IdentityServer/IdentityServer4#2030]
I have a requirement to redirect all users through a PostLoginRedirectController after they have successfully logged in.

This Controller can then, in turn, redirect the users elsewhere in the application based on its own rules, this means I can't use the RedirectUri to pass users to this controller as I can't guarantee they will ever hit the /signin-oidc endpoint.

Is there a way to force a redirect after the /signin-oidc endpint is hit - I have noticed that if you don't go to the root of an app a cookie is created that seems to store the url that the user was trying to go to and instead of redirecting to / the /signin-oidc redirects to the cookie url.

Workflow that i need would look something like this

App 1 - /mycontroller
Redirect to Identity server
Login ....
Redirect back to App 1 /signin-oidc
Redirect to App 2 /PostLoginRedirectController 
... run rules 
Redirect to its result or the return ulr of app 1 / mycontroller

Any help on this would be appreciated.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
