### ISSUE TITLE
How to set error_description, error_uri

### ISSUE THREAD

**Issue by benlinx1018** [IdentityServer/IdentityServer4#2031]
I want to add custon error_description, error_uri  when the user not allow access,
but  can not find any way to set up them 

how to do it  on IdentityServer4 using IdentityServer4.Samples.Quickstarts.7_JavaScriptClient?

**Comment by brockallen** [comment]
As of now, we don't have a way to pass error_description back from the authorize endpoint from your hosting code.

**Comment by gthvidsten** [comment]
+1 for this feature. As it is now my client can know that something went wrong with the authentication, but it can't know what went wrong. It would be very good to be able to differentiate between authentication errors and i.e. the user cancelling his authentication.

**Comment by Jestar342** [comment]
May I inquire as to what the purpose of the error description field/property is, if it isn't being passed back to the client? 

E.g. when I add the following validator:

    public async Task ValidateAsync(ExtensionGrantValidationContext context) 
        => new GrantValidationResult(TokenRequestErrors.InvalidRequest, "Bad juju");

where does that "Bad juju" go to, practically? Is there somewhere in some kind of logging I can include that description?

**Comment by brockallen** [comment]
> May I inquire as to what the purpose of the error description field/property is, if it isn't being passed back to the client?

For these changes, IIRC< they're used on the error page t show the end user (in dev mode, who is presumably a developer).
