### ISSUE TITLE
Improvement: Log output for "Invalid redirect_uri" error of TokenRequestValidator

### ISSUE THREAD

**Issue by cbfrank** [IdentityServer/IdentityServer4#2032]
TokenRequestValidator.cs will get ther error for redirect_url validation, but the error/log output is:
LogError("Invalid redirect_uri: {redirectUri}", redirectUri);
In my case, the requested redirect_url is ***/, while expected redirect_url is ***, and the log shoows:
"Invalid redirect_uri: ***", the reidrect_uri is missing "/" and the end, but is it not obviously to found what's missing or incorrect in this case. Finally I have to debug with the source code of ID4.
It would be greate to output the expected redirect_uri together with the current redirect_uri which will make it easyer to find what's going wrong.

Thanks

**Comment by brockallen** [comment]
`http://foo` is not the same URL as `http://foo/`. Sounds like you have a mismatch in your URL config for `Client`'s `RedirectUri`.

**Comment by leastprivilege** [comment]
PR?

**Comment by brockallen** [comment]
Any update?

**Comment by cbfrank** [comment]
I'm sorry that I'm a littly busy these days, and will creata a pull request after about two weeks.

**Comment by cbfrank** [comment]
Hi, The pull request has been submitted. #2081
