### ISSUE TITLE
Question: What benefits does IdentityServer4 offer over IdentityServer3?

### ISSUE THREAD

**Issue by tbrettallen** [IdentityServer/IdentityServer4#2033]
As the subject states, what benefits are offered? I could not find a comparison between the two.

Also, what level of effort would be required to convert from IdentityServer3 to IdentityServer4? We use a custom user service with custom identity providers, custom claims provider, and a custom sign in view/controller and a custom redirect URL validator.

Is there a guide for conversion?

Due to the level of customization we've implemented and time invested so far, we are cautious to try and convert to IdentityServer4.

**Comment by lgigrl** [comment]
+1

We are asking ourselves the exact same questions around here. Could anyone provide some guidance?

**Comment by Jackalex36** [comment]
We are wondering the same thing. From what we have seen, similar features are mostly possible in both cases but sometimes harder to achieve. Or at least it might be less straight forward to set up or less optimized.

The obvious difference is that the IS3 is archived, no longer in active development, beside major security patches. We can expect better community support, issue handling and documentation with IdentityServer4 in the future. 

The orientation taken with .Net Core 2 is also pretty good, which means that we could now set it up on low cost Linux systems! -> But, does it mean you can't fully use past customisations built over IS3 if they are in .Net 4.5 for example?

I'm also wondering if a migration path exists, but I kind of doubt it.

_PS. I'm not sure this is officially an issue, beside maybe some documentation/clarification on the subject._

Thanks!

**Comment by brockallen** [comment]
We did a video showing what's new. Check our video listing: http://docs.identityserver.io/en/release/misc/videos.html
