### ISSUE TITLE
Retrieving access token without client ID/secret

### ISSUE THREAD

**Issue by nicbavetta** [IdentityServer/IdentityServer4#2034]
I have defined a protected API within an IdentityServer Host which contains a few "startup" endpoints. These endpoints were added to support a streamlined configuration process when adding new API resources or clients. See the IdentityServer Host ConfigureServices() method below:

```
public void ConfigureServices(IServiceCollection services)
{
       services.AddMvc();
       services.AddAuthorization(options =>
       {
           options.AddPolicy("StartupApiPolicy", policy =>
           {
               policy.AuthenticationSchemes.Add(JwtBearerDefaults.AuthenticationScheme);
               policy.RequireAuthenticatedUser();
               policy.RequireScope(IdentityServerApiConfiguration.Scopes.Startup.ScopeName);
           });
       });

       // [Authorize(Policy = "StartupApiPolicy")] is added to the Startup API controller.

       services.AddIdentityServer()
                    .AddDeveloperSigningCredential()
                    .AddResourceStore<ResourceStore>()
                    .AddClientStore<ClientStore>()
                    .AddProfileService();
...

       services.AddAuthentication()
                    .AddIdentityServerAuthentication(isAuth =>
                    {
                        isAuth.Authority = identityServerUrl;
                        isAuth.ApiName = "identityserverstartupapi";
                    });
}
```

## Ideal Scenario
When a developer in my organization is writing a new API, they will add middleware that registers the application with the IdentityServer Host. Under the hood, this middleware will call the IdentityServer Host API endpoint that adds a new API resource to the resource data store. A developer will also be able to add similar middleware if they are writing a new client.

## Question
When a new client or API runs for the very first time, the respective IdentityServer data store  will not contain any configuration for it yet. Therefore, the middleware will call the IdentityServer Host API to add the configuration. Since the host API is protected, I will need a token to authenticate. I know you can retrieve tokens with the TokenClient but this requires a client ID/secret to instantiate - which does not exist yet.

What is the recommended approach for retrieving an access token in this scenario?

**Comment by leastprivilege** [comment]
well - that's a chicken/egg problem. There's no solution to that without introducing a special "registration" client or similar (check the dynamic client reg spec).

that being said

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
