### ISSUE TITLE
associated user claims for api request 

### ISSUE THREAD

**Issue by bufferz** [IdentityServer/IdentityServer4#2036]
_List of associated user claim types that should be included in the access token._

is it possible to change the behavior of the identity server if the claims required to be included on the token to apply an api request not enough ? is there any example out there ? 

thanks!

to clarify : i want to be able to customize the authorization failure . this is can be achieved using custom attributes . but how can i apply that attribute only in a specific scenario which is the **token require more claims**

**Comment by brockallen** [comment]
This is already a feature -- check the docs on ApiResources and UserClaims.
