### ISSUE TITLE
Following Identity server test server demo Logout Logoutid null

### ISSUE THREAD

**Issue by ciptoj** [IdentityServer/IdentityServer4#2038]
Please only use the issue tracker for bug reports and/or feature requests. For free or commercial support options, see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

### Issue / Steps to reproduce the problem
Aspnet identity is set to custom mode, with GUID ID
Change subjectID to my custom GUID 
Account LogOut , logoutID becomes null

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Not enough info. I'd suggest debugging into when you need a logoutId.

**Comment by ciptoj** [comment]
I already resolve this.
turns out in the angular need to configure redirect url,
http://xxxx/sign-inodc

On Tuesday, February 6, 2018, Brock Allen <notifications@github.com> wrote:
> Not enough info. I'd suggest debugging into when you need a logoutId.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/4-q5Jr4Prk6wVqAjRprDamBj6sMTh5UU45H7Kf1Q-WGL8eksBowSMcZUsXEOV9YIOuMe08Pr29d6MQo19RgpuEx9yNaMJCKAlYiYD-KDhJxWCXAOIMc7x5g_eywsyfE1MwbUS3qfEUJFplTTiLN2ezYhB_yFow=s0-d-e1-ft#https://github.com/notifications/beacon/AIckTAistdDYU_cDBE9uJaSPiLFcCWOcks5tSFRfgaJpZM4Rzux0.gif
>

-- 
Regards,


(Cipto)
Mobile: +6281808557858
