### ISSUE TITLE
HttpClient

### ISSUE THREAD

**Issue by ChristoKolander** [IdentityServer/IdentityServer4#2040]
Hello!
Setting up an Identity Server Protected Web API, consuming it from an MVC Client - using the HttpClient class provided from Microsoft. As far as attaching the headers to the request, I only got it to work when explicitly attaching an authorization header with token in each controller action. No other way? Gets kind of bloated, this manual approach, but using a class library builder pattern not applicable because of the token needs to get collected and injected for each request...as far as I understand it. 

Any suggestions, any one? Resources?

/C.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
