### ISSUE TITLE
ForbiddenResult from controller action leads to redirect

### ISSUE THREAD

**Issue by jtheisen** [IdentityServer/IdentityServer4#2043]
### Issue / Steps to reproduce the problem

Bootstrap a ASP.NET Core webapi app from the VS templates.

Hook up IdentityServer4 just like so:

```
services.AddIdentityServer()
```

Write a controller action that returns a `ForbiddenResult`.

Query the action.

You get redirected to `/Account/AccessDenied`.

It's probably not IdentityServer4 directly that causes this, but it definitely causes it indirectly.

I want to have a web api alongside the mvc stuff and the api should give you such a redirect (and even for mvc I would think that's a questionable behavior).

**Comment by jtheisen** [comment]
I had [posted this question](https://github.com/IdentityServer/IdentityServer4/issues/2043) earlier on SO.

**Comment by brockallen** [comment]
I suspect you need to set the scheme on the result to get the behavior you want.

**Comment by jtheisen** [comment]
What scheme? I want the ForbiddenResult to cause a 403 as it's supposed to.

**Comment by jtheisen** [comment]
Indeed there's some conceptual stuff I don't know about yet. Returning some scheme doesn't redirect but throws some exception.

Ok, feel free to close this then.

**Comment by jtheisen** [comment]
You don't happen to know what IdentityServer does that sets this up though, do you?

**Comment by brockallen** [comment]
Check our docs, or look at the code -- those are the best ways to learn it and understand how it works.
