### ISSUE TITLE
Feature Request RP-init logout optional ui_locales parameter

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#2045]
As a user I want to set the culture when doing a RP logout using the ui_locales parameter.

Note: This will be included in the next specification release or draft.

https://bitbucket.org/openid/connect/issues/1017/session-management-rp-init-logout-proposal

  RP-Initiated Logout Will be updated with the ui_locales.

http://openid.net/specs/openid-connect-session-1_0.html#RPLogout

**Comment by damienbod** [comment]
related : https://github.com/IdentityServer/IdentityServer4/issues/1480

**Comment by brockallen** [comment]
Not if the spec spec support it. But what I'd argue is that when the authorize request is initially processes with its ui_locales that the app track that in the user's session at IdentityServer. Then at logout time you use that to do your localization. That makes much more sense to me.

**Comment by igor-moskvitin** [comment]
@brockallen clear. i am using it as you say, but what if user on client change language after signin - thats strange if all on client side will be on new language, but logout screen confirmation - on previous. I agree that its a not frequently case, but its can be. and @brockallen set it to future - thats why i ask.

**Comment by damienbod** [comment]
The ui_locales  must be supported as defined in the Core section 15.1

http://openid.net/specs/openid-connect-core-1_0.html

As the OpenID Connect Session Management 1.0 is built on top of this, the RP-Initiated Logout must support this per specification.

Also your preferred solution will not work if I change the language after a login, which is a normal use case in most applications which we deploy. 

Greetings Damien

**Comment by brockallen** [comment]
> The ui_locales must be supported as defined in the Core section 15.1

That's authorize, not end session. 

> As the OpenID Connect Session Management 1.0 is built on top of this, the RP-Initiated Logout must support this per specification.

I don't see how that logic follows. Does that mean end session should accept all the same params as the authorize endpoint?

> Also your preferred solution will not work if I change the language after a login, which is a normal use case in most applications which we deploy.

Why would an end user change their language? What's an example of that use case?

**Comment by damienbod** [comment]
In section 15.1:

15.1.  Mandatory to Implement Features for All OpenID Providers

All OpenID Providers MUST implement the following features defined in this specification. 
This list augments the set of features that are already listed elsewhere as being "REQUIRED" or are described with a "MUST", and so is not, by itself, a comprehensive set of implementation requirements for OPs.

Preferred Locales

OPs MUST support requests for preferred languages and scripts for the user interface and for Claims via the ui_locales and claims_locales request parameters, as defined in Section 3.1.2. (Note that the minimum level of support required for these parameters is simply to have their use not result in errors.)

These definitions are for all OP requests...

In the session management section 1:

This specification <b>complements</b> the OpenID Connect Core 1.0 [OpenID.Core] specification by defining how to monitor the End-User's login status at the OpenID Provider on an ongoing basis so that the Relying Party can log out an End-User who has logged out of the OpenID Provider.

So the session management OP requests must support the Mandatory stuff in section 15.1 , not the params in the authorize requests.

2) auto Login then the user switches language.

**Comment by brockallen** [comment]
I'm pretty sure you realize that section 3.1.2 is the authorization endpoint section.

> These definitions are for all OP requests...

I don't see that statement in the spec, so this seems to be your interpretation. And all OP requests would mean token, discovery, etc. 

I appreciate the desire to have the locales on every page, but I don't intend to add custom non-spec compliant workarounds (like so many other implementations). Please don't try to "strong arm" this conversation by blurring the reading of the spec (as I don't see anyone from the spec committee agreeign with you on your comment https://bitbucket.org/openid/connect/issues/1017/session-management-rp-init-logout-proposal#comment-43313913). If the spec gets clarified on these points, then I'm fine with adding it.
