### ISSUE TITLE
EntityFramework LINQ expression cannot be translated

### ISSUE THREAD

**Issue by DominikPfeifer** [IdentityServer/IdentityServer4#2051]
### Issue / Steps to reproduce the problem

1. Use **Identityserver4.EntityFramework** package
2. Enable token cleanup

### Relevant parts of the log file

```
The LINQ expression 'where ([x].Expiration < Convert(DateTime.UtcNow, Nullable`1))' could not be translated and will be evaluated locally.
```

Line:
https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/1d7a862903b82c08f28d0787b1dafe1590e2f526/src/IdentityServer4.EntityFramework/TokenCleanup.cs#L113

### Fix
`.Where(x => x.Expiration.HasValue && x.Expiration.Value < DateTime.UtcNow)`

**Comment by brockallen** [comment]
Which DB are you using?

**Comment by DominikPfeifer** [comment]
I am currently using Sqlite for the Operational Store.

I only realized the Warning on our Seq Server ;)

I attached a RAW Log file from Seq
[event-826a571e6c7408d5e7a6b10200000000.txt](https://github.com/IdentityServer/IdentityServer4/files/1695531/event-826a571e6c7408d5e7a6b10200000000.txt)

**Comment by brockallen** [comment]
Ok... we'll have to determine is this is provider specific or not. Do you have other DBs you use?

**Comment by DominikPfeifer** [comment]
Currently we only have the SqliteDB.

I can test that tomorrow on a SqlServer too.

**Comment by brockallen** [comment]
Please do and let us know. Thanks.

**Comment by DominikPfeifer** [comment]
SqlServer works fine

aspnet/EntityFrameworkCore#10887

**Comment by brockallen** [comment]
Ok, so that tells me it's provider specific... so question is then -- what should be done (if anything)?

**Comment by DominikPfeifer** [comment]
It will be fixed in the next EfCore release, so nothing should be necessary to do.

Thanks for the investigation :)
