### ISSUE TITLE
Consider create datetime on ClientSecret

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#2055]
Client secrets are created and we can have more then one.     I was thinking that our developers may create several client secrets.      It would be nice to know when a secret was created.   My current solution is to add a time stamp to the description property which works but isn't ideal.

I am willing to submit a pull request on this if you agree its wroth adding.

**Comment by leastprivilege** [comment]
This would mean a schema change - and we try to avoid that..

I will put it in backlog.

**Comment by LindaLawton** [comment]
Do you have any idea how much hair pulling i have had from the schema changes in 1.x -> 2.0 upgrade?

I kind of thought you guys loved schema changes :)

**Comment by brockallen** [comment]
> Can we get migration steps in this time

Migrations are the concern of the hosting application. This is because fundamentally EF migrations don't support library style schemas.

**Comment by brockallen** [comment]
We'll add this on the 3.0 milestone, since that will be an expected big (schema) change.

@leastprivilege also is mentioning a "last access" time so people know which secrets are stale.

**Comment by LindaLawton** [comment]
Can we add a create datetime and a last access datetime for Clients as well

**Comment by brockallen** [comment]
Also, perhaps a LastAccessedDate

**Comment by LindaLawton** [comment]
I keep meaning to try to add this as a clientproperty to the client validate.    I just couldn't decide if lastaccessdate counted with failed login or just with successful logins.

we apparently need this for GDPR compliance.

**Comment by TomCJones** [comment]
I am planning to add this to the user db to list successful logins as I use that to establish termination date, which is what I need for consent receipt for GDPR.  BTW, I implemented consent receipt on a ASP.NET identity / idsvr4 OP. But I have not found any good way to have user consume the data as yet,

**Comment by LindaLawton** [comment]
But in the event of client credentials Grant type its not a user and you would need to store lastaccessdate of the client itself.

what about refresh token usage do you think it best to store that on the user or the client or the client access grant can't remember that table I am mobile right now.

**Comment by TomCJones** [comment]
GDPR should only apply to user? or am I missing something here?
If you are talking about impersonation, I just refuse to allow that as it is far beyond GDPR thinking.
I don't think that there is anything that requires tracking refresh usage, altho I never thought much about it.

**Comment by LindaLawton** [comment]
It is possible that this is a requirement from a customer I am not privileged to that information.

I was told anyone or anything accessing data must be logged.  In the event of a client its the developer who we must log who's data they accessing and when oauth2 clients.    If its an identity login then we log it as the user.

**Comment by brockallen** [comment]
> or am I missing something here

The values we're discussing here are client, not user related.

**Comment by LindaLawton** [comment]
@brockallen Sorry we apart to have side tracked your thread.   

I would be interested to hear how you plan on detecting last access?  Are we talking last valid use of it or last attempted use of it?

Also probably another issue but a method for resetting secret would be really nice.

**Comment by brockallen** [comment]
> I would be interested to hear how you plan on detecting last access? Are we talking last valid use of it or last attempted use of it?

Yea, we'd have to find out in the authN code which one is matched and then somehow trigger an update to the DB for it.

**Comment by LindaLawton** [comment]
Going to have to do some kind of load testing you dont want two updates running at the same time crashing into eachother.

**Comment by TomCJones** [comment]
wouldn't the easiest solution be to update the field on successful login (to the OP, not the client)?
That's all I had planned to do.

Peace ..tom
________________________________

**Comment by LindaLawton** [comment]
Ok I am going to play devils advocate here and ask will updating the database on all successful logins cause any load issues?   deadlocks can't happen on update iir but what happens if the row no longer exists for some reason or you can't access the database.    there will need to be some readable error handling with this.

**Comment by TomCJones** [comment]
This thread does seem to be wandering, but you should consider the purpose of the field. If the record doesn't exist there is no purpose served in updating it.

**Comment by TomCJones** [comment]
This thread does seem to be wandering, but you should consider the purpose of the field. If the record doesn't exist there is no purpose served in updating it.

**Comment by leastprivilege** [comment]
I don't see this for 2.3 - will be considered at some later point.

**Comment by leastprivilege** [comment]
I misspoke ;)

**Comment by brockallen** [comment]
![68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f4469634e6a694255454141347456512e6a7067](https://user-images.githubusercontent.com/649492/43520881-4c9f3cfa-9562-11e8-9ffb-4b9d67b7f177.jpeg)

**Comment by brockallen** [comment]
Created date time added to the secret EF class.
