### ISSUE TITLE
Question : Client Credentials to authorize a controller on Identity Server

### ISSUE THREAD

**Issue by NazmiAltun** [IdentityServer/IdentityServer4#2061]
Is it possible to authorize  an api controller , that is implemented on identity server app , to a particular client  by using client credentials grant type?

For example on identity server i have a controller such as;

```
[Route("/users")]
    public class UserController : ApiControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetAllUsers()
        {
            return Ok();
        }
    }
```
and i have a client  with following config;
```
  {
      "ClientId": "web.client",
      "ClientName": "web Client",
      "AllowedGrantTypes": [ "client_credentials" ],
      "ClientSecrets": [ { "Value": "CLIENT_SECRET_HERE" } ], 
      "AllowedScopes": [ "idvsrapi"]
    }
```

I want  GetAllUsers  method to be authorized only to the client above . Is this possible without user login?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
