### ISSUE TITLE
ClientSecretValidationResult.Error and ClientSecretValidationResult.ErrorDescription not used

### ISSUE THREAD

**Issue by SarapinIT** [IdentityServer/IdentityServer4#2063]
Hello, i'm try to add Custom realization of IClientSecretValidator with custom Error and ErrorDescription in returned ClientSecretValidationResult. But i find that Error and ErrorDescription fields not used in Endpoint result. 

IdentityServer4.Endpoints.TokenRevocationEndpoint
```
private async Task<IEndpointResult> ProcessRevocationRequestAsync(HttpContext context)
{
        _logger.LogDebug("Start revocation request.");

        // validate client
        var clientValidationResult = await _clientValidator.ValidateAsync(context);

        if (clientValidationResult.IsError)
        {
            return new TokenRevocationErrorResult(OidcConstants.TokenErrors.InvalidClient);
        }

        ...
}
```

IdentityServer4.Endpoints.TokenEndpoint
```
private async Task<IEndpointResult> ProcessTokenRequestAsync(HttpContext context)
 {
       _logger.LogDebug("Start token request.");

        // validate client
        var clientResult = await _clientValidator.ValidateAsync(context);

        if (clientResult.Client == null)
        {
            return Error(OidcConstants.TokenErrors.InvalidClient);
        }

        ...
}
```

Can we use Error and ErrorDescription in Error ctor and TokenRevocationErrorResult ctor?

### Issue / Steps to reproduce the problem
* Create custom realization of IClientSecretValidator with some custom Error and ErrorDescription text in ClientSecretValidationResult
* Replace default IdentityServer realization of IClientSecretValidator in Startup.ConfigureServices
```
services.Replace(new ServiceDescriptor(
        typeof(IClientSecretValidator),
        typeof(CustomClientSecretValidator),
        ServiceLifetime.Transient));
```
* Request token with wrong client_id
* Receive a response:
```
{
    "error": "invalid_client"
}
```
instead of custom Error and ErrorDescription

**Comment by chrisowhite** [comment]
The "invalid_client" error response is prescribed in the OAuth 2.0 spec.

https://tools.ietf.org/html/rfc6749#section-5.2

You should see your custom error and description in the logs. Generally you want to avoid sending back too much validation failure information to a potential attacker.

**Comment by leastprivilege** [comment]
> You should see your custom error and description in the logs. Generally you want to avoid sending back too much validation failure information to a potential attacker.

agreed.

**Comment by SarapinIT** [comment]
Ok, I understand, thanks
