### ISSUE TITLE
Loop on requests (HTTPS/HTTP cookies issue)

### ISSUE THREAD

**Issue by Astimus** [IdentityServer/IdentityServer4#2064]
I have similar problem as discribed in this [link](https://github.com/IdentityServer/IdentityServer3/issues/294).

I have IdSrv4 and Node.js with oidc-client-js. Both of them can work on http and https. I have option in settings. So if client authenticated throw http. And platform rebooted with https. Client trying to login again and have problem which described in link above. How to fix such behavior? Do I need somehow to clean client's browser cookies after rebooting platform?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
