### ISSUE TITLE
IdentityServer4 suggested architecture for n per m users per profiles

### ISSUE THREAD

**Issue by SaviCarlone** [IdentityServer/IdentityServer4#2065]
I am really new to IdentityServer but I really appreciate it.
The app I am going to build is a game G1 where a user U1 can logon with standard user/pwd and then has a default profile for G1 that we can call P1 (let's say team name, etc..). So U1 owns P1 profile, U2 owns P2 profile and so on, but at a certain time U1 can say: "I want to share my P1 profile with U2 (in readonly/in read-write)". From that moment, U2 at login time should choose if operating on P1 or P2 (and remember it for next time, and have the chance to change this decision). In G1 game both P1 and P2 are in the same context/DB, because they are partecipating to the same competition. 
After this, the G2 game has the same concepts, but each profile points to a different context/DB. In this second game, partecipating needs admin approval (because creating different DB for each profile can be expensive and needs specific startup scripts...).
Both games should work for all (web, mobile, maybe mobile app).

The idea is creating a global SSO IdentityServer that just authenticate user and is just the roof ot the building, but how ask specific game info, when during logon, where store them and how check them? Anyone can guidre me for the architecture definition? Is there any sample?
Thank you!

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
