### ISSUE TITLE
Signout for Google External Identity Provider isn't working

### ISSUE THREAD

**Issue by himalpatel81** [IdentityServer/IdentityServer4#2066]
I'm using the [Sample Project](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/4_ImplicitFlowAuthenticationWithExternal) which works against Google as External Authentication provider. 
During Signout, I also want to signout the user from Google. But that isn't happening. 
It only signout the user from the MVC App.

**Comment by brockallen** [comment]
Googles doesn't support that.
