### ISSUE TITLE
Discovery endpoint retrieval problem

### ISSUE THREAD

**Issue by vladbondarenko1** [IdentityServer/IdentityServer4#2069]
Hi. Have a problem with discovery document endpoint. 
**Steps:**

1. Stop the IdentityServer website.
2. Start application which use IdentityServer authentication
3. Make a request to application
4. Start the IdentityServer website.
5. Make the request again

**Expected result**

Step 3 fails with
`System.InvalidOperationException: Error parsing discovery document from http://localhost:9090/.well-known/openid-configuration: Error connecting to http://localhost:9090/.well-known/openid-configuration: An error occurred while sending the request.
   at IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions.<GetIntrospectionEndpointFromDiscoveryDocument>d__3.MoveNext()`

Step 5 succeeds, because IdentityServer is up and running again and metadata can be retrieved.

**Actual result:**

All subsequent requests fail with the same exception. There is no retry behavior for retrieving discovery endpoint metadata, only restart application can help.

**Screenshoot with error:**
![1](https://user-images.githubusercontent.com/26981150/36155099-1f7b3e6e-10dc-11e8-9370-8c2f9475e3af.png)
![3](https://user-images.githubusercontent.com/26981150/36156209-084630c0-10df-11e8-8179-21e9f17cdd6e.png)

**IdentityServer authentication settings:**
![2](https://user-images.githubusercontent.com/26981150/36155964-7569f732-10de-11e8-85fd-6a29ca0c050a.png)

**Comment by brockallen** [comment]
Do you know if this is an issue in the client libraries or something in IdentityServer itself?

**Comment by vladbondarenko1** [comment]
Looks like that issue is in `IdentityModel.AspNetCore.OAuth2Introspection` library 
in `PostConfigureOAuth2IntrospectionOptions` class `GetIntrospectionEndpointFromDiscoveryDocument ` method

**Comment by brockallen** [comment]
Open an issue on that repo then, please.

**Comment by vladbondarenko1** [comment]
Already opened https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/issues/26

**Comment by dudedev** [comment]
Is this issue really fixed. I am still getting this error.
```
System.InvalidOperationException: Error parsing discovery document from http://myidentityserver/.well-known/openid-configuration: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
at IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions.<GetIntrospectionEndpointFromDiscoveryDocument>d__3.MoveNext() in C:\local\identity\model\AspNetCore.OAuth2Introspection\src\IdentityModel.AspNetCore.OAuth2Introspection\PostConfigureOAuth2IntrospectionOptions.cs:line 62
```

Below is the service setup code.
```
                services
                    .AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                    .AddIdentityServerAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme, options =>
                    {
                        options.Authority = identityServerUri;
                        options.ApiName = apiName;
                        options.ApiSecret = apiSecret;
                        options.RequireHttpsMetadata = false;
                    });
```

 I am using version 2.5.0 of IdentityServer4.AccessTokenValidation which is using IdentityModel.AspNetCore.OAuth2Introspection v3.2.0

**Comment by brockallen** [comment]
Do you have a middleware in your pipeline such as `UseDeveloperExceptionPage`? That's why it's rending html, and not json.

**Comment by dudedev** [comment]
Yes, I am using the DeveloperExceptionPage, but only in the development mode. like this.. 
```
            if (devMode)
            {
                app
                    .UseDeveloperExceptionPage()
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseAuthentication();
```
But, I get the same error if I run it in Production mode. I get above error in the log output, when I send an API request with access_token.

**Comment by brockallen** [comment]
Doesn't this: `app.UseExceptionHandler("/Home/Error");` render html?

**Comment by dudedev** [comment]
I found out the issue. Actually, due to incorrect DNS entry the identity server was pointing to the application(dockerized) itself, which was returning HTML. Anyways, thanks for your support.
