### ISSUE TITLE
[BUG] Cant load one of the samples on windows do to path to long.

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#2071]
This issue is cross posted from [IdentityServer4.Samples](https://github.com/IdentityServer/IdentityServer4.Samples/)  

### Issue / Steps to reproduce the problem

On windows 10 VS17  try to open the solution file associated with [Combined_AspNetIdentity_and_EntityFrameworkStorage](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage)

Results in an error as the migration file leads to a path thats to long.

### Relevant parts of the log file

System.AggregateException: Project system data flow 'ProjectEvaluationProjectCapabilitiesProvider: 10600' closed because of an exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: The item metadata "%(FullPath)" cannot be applied to the path "Data\Migrations\IdentityServer\ConfigurationDb\20171005153917_InitialIdentityServerConfigurationDbMigration.cs". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

## Note

I have seen this before if memory services we just need to rename some of the files so they dont result in such a long path.   I may have a look at it when i am finished with the current fix i am working on.

**Comment by brockallen** [comment]
Didn't someone just recently update the docs or quickstarts with a note about avoiding this?
