### ISSUE TITLE
Feature Request: Consider checking  [AccessTokenLifetime] to something other than 0

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#2072]
### Issue / Steps to reproduce the problem

I recently manually inserted a client into the database in error i had forgotten to set the [AccessTokenLifetime] which lead to the following error 

### Relevant parts of the log file

>System.ArgumentException: IDX10401: Expires: '02/14/2018 13:08:38' must be after NotBefore: '02/14/2018 13:08:38'.

### Suggestion / question

When we validate the client as the user logs in would it be possible / a good idea to validate that the access-token life time is not set to 0.   I cant think of any reason where it would be valid to have an access token lifetime of 0 on most of the grant types if not all.   I am thinking somewhere in [here](https://github.com/IdentityServer/IdentityServer4/blob/b0d853ca51946ce99ac0ee3fff4401e25b07e52c/src/IdentityServer4/Validation/AuthorizeRequestValidator.cs#L147)   The question would be should it just be logged as a warning or should it be the cause to make a client invalid.

**Comment by brockallen** [comment]
So then if it is found to be zero, what do we do then? I lean towards this just being a configuration error and not something we can do much about, expect add defensive error logging anywhere an external configuration value is loaded. It's possible to write all that defensive code, but it's work.

**Comment by LindaLawton** [comment]
I agree it's a configuration error.    Even so the error return really isn't helpful in diagnosing the confirmation error.   

I think we should inform either the owner of the identity server and/or the developers using the client id that there is an issue.

If you are worried about the time it would take to add this don't be.  I would be happy to do it, I would just like some direction from you on how best to do it.    I use this daily I am happy to contribute.

**Comment by brockallen** [comment]
Ok, thanks. Let us discuss and then we'll get back to you.

**Comment by brockallen** [comment]
So you're suggesting a log entry to let the dev know? If that's all, then yes please send a PR for that.

**Comment by LindaLawton** [comment]
For now i cant think of a better option then logging that the client is not valid it was setup wrong.  You happy with adding it to AuthorizeRequestValidator?   or do you have a better place?

**Comment by leastprivilege** [comment]
I guess this should be part of a bigger effort - moving to https://github.com/IdentityServer/IdentityServer4/issues/2114
