### ISSUE TITLE
Feature Request: Standard .NET events for purposes other than logging

### ISSUE THREAD

**Issue by MV10** [IdentityServer/IdentityServer4#2073]
Any chance you'd consider raising events through the normal .NET event system? This should make it easy to respond to things like a successful login where OIDC Prompt is set to "none". 

My client app registers a non-default OIDC challenge with no UI to achieve persistent login (between sessions -- a silent challenge when a new anonymous user first arrives). We'd like to update the user data's "last visit" timestamp when this happens. As far as I can tell, right now we'd have to hijack `IEventSink` to do this -- and then we'd be responsible for implementing logging ourselves, or whatever else might eventually end up in the default implementation.

**Comment by brockallen** [comment]
> Any chance you'd consider raising events through the normal .NET event system

I'm not entirely sure what this means.

**Comment by MV10** [comment]
I was assuming events like `UserLoginSuccess` were generally raised (logged), but now I see it's only raised in the case of [`TokenRequestValidator`](https://github.com/IdentityServer/IdentityServer4/blob/c7eade457ec75a6ea99af307293776011a8d1717/src/IdentityServer4/Validation/TokenRequestValidator.cs#L732). I was referring to exposure of events internal to Identity Server (by which I mean, excluding any UI code -- I know the Quickstart raises some events, too).

I should have written "C# events" rather than .NET events... but otherwise I'm not sure how else to describe it. Declare events in Identity Server that we can wire up which are invoked at the appropriate places throughout the code. Given there are non-UI flows, it would give us hooks to add our own processing when certain interesting events occur. (Have I overlooked a way to do this now?)

Any real code would probably also deliver useful args with the events, but as a trivial example:

```
public event EventHandler UserLoginSuccess;
public event EventHandler UserLoginFailure;
```

**Comment by brockallen** [comment]
I don't foresee us moving in that direction: 1) it's a major breaking change, and 2) it's not DI friendly and counter to the ASP.NET Core style

**Comment by MV10** [comment]
Is there an existing way to add code that is guaranteed to run in response to a successful login?

**Comment by leastprivilege** [comment]
Logins only happen on the account controller. This is your code anyways.

**Comment by dtsmith94** [comment]
In my IS4 implementation, I audit user logins and I would find it useful to be able to detect somehow when a js client validates an auth token with IS4 - in the case of 'Remember Me' when I have no way of knowing a user has authenticated on a given day, only the day they physically typed in their username and password. I need to be able to log this in my own custom way - not looking through the logs to pick this up. Do you have a recommended way of doing this? I was hoping I could just handle an IS4 'ApiAuthenticationSuccessEvent' but as MV10 has already alluded to, these are not events which can be handled in C#.

**Comment by brockallen** [comment]
> In my IS4 implementation, I audit user logins and I would find it useful to be able to detect somehow when a js client validates an auth token with IS4

This can already be done in the authorize request validator:
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Endpoints/AuthorizeEndpointBase.cs#L67

and in the user interaction response generator:
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Endpoints/AuthorizeEndpointBase.cs#L81

So those are the places you can get involved with the request for authorization.

**Comment by dtsmith94** [comment]
Thanks for shining a light... I’ve extended the AuthorizeInteractionResponseGenerator class to achieve this.

**Comment by brockallen** [comment]
all set on this issue -- can we close?
