### ISSUE TITLE
XML API documentation

### ISSUE THREAD

**Issue by drjaydenm** [IdentityServer/IdentityServer4#2076]
Hi there, great work on IdentityServer4!

We are implementing this software and are using Swagger/Swashbuckle to document the API for the identity server. Our own endpoints are showing correctly in the docs, however the IdentityServer4 endpoints do not show (obviously because they are part of the middleware & not part of our application code).

Is it possible to include a way to get the XML documentation for IdentityServer4? This would be great as all API endpoints would then be visible in Swagger/Swashbuckle then.
Thanks

**Comment by brockallen** [comment]
This is not the first time I've seen this request. What's the use case... or who would the consumer of these APIs be? The reason this is somewhat of an odd request (to me) is that the specs defines these endpoints, so I'm confused as to why they need to be documented in something like swagger.

**Comment by drjaydenm** [comment]
We have 6 dev teams all looking to utilize this system for different applications, some of them aren't using the .NET stack so can't make use of all the IdentityServer* libraries. 
Arguably they should probably use some other sort of OAuth/OpenID framework to do the calls for them, but some are legacy systems. But having these endpoints all documented in one place makes it easy to visualize what the entire implementation of identity server is capable of.

Using a tool like Swagger also allows you to send requests right from the browser to quickly try it out, lowering the entry barrier for other teams.

It's not a deal-breaker, but would be a really nice feature.

**Comment by leastprivilege** [comment]
We discovery endpoint has a list of all protocol endpoints - and the corresponding specs document them. 

https://identityserver4.readthedocs.io/en/release/intro/specs.html

We have no other plans beyond that.
