### ISSUE TITLE
How to refresh that identity token in mobile?

### ISSUE THREAD

**Issue by Sathiyamm** [IdentityServer/IdentityServer4#2078]
I'm generating token in the login time

` var identityService = await DiscoveryClient.GetAsync("http://localhost:5000");
                        // request token
                        var tokenClient = new TokenClient(identityService.TokenEndpoint, "ro.client", "secret");
                        tokenResponse = await tokenClient.RequestResourceOwnerPasswordAsync(user.UserName, model.Password, "api1");`

and store the local storage. 

client-side access the API method add the headers

`headers.append('Authorization', 'Bearer  ' + token);
headers.append('Content-Type', 'application/json');
        headers.append('Accept', 'application/json');
        const options = {
            method: 'POST',
            headers,
            body: JSON.stringify(data)
        };`
Its working good in web. After expire controller return unauthorize. 
But I'not needed to expire in the token (refresh the token) in a mobile app.
So how to refresh that token in mobile?
any headers add for refresh the token?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
