### ISSUE TITLE
Feature Request: Code Example using TwoStepsAuthenticator

### ISSUE THREAD

**Issue by MovGP0** [IdentityServer/IdentityServer4#2079]
### Issue / Steps to reproduce the problem

There should be an example for 2-step authentication using the Time-Based One-Time Password Algorithm (TOTP). 

There is an open source project for this here: [TwoStepsAuthenticator](https://github.com/glacasa/TwoStepsAuthenticator) 

### Secondary goal

Implement an example using a QR Code (maybe [this library](https://github.com/codebude/QRCoder)?) on the screen, such that the user can easily connect the mobile phone by scanning the code from the screen.

**Comment by leastprivilege** [comment]
Good idea! Let us know where you put that sample so we can link to it.

**Comment by MovGP0** [comment]
I don't have a sample. Just wanted to keep track of the idea. 

Also currently too busy to implement a sample myself :-(

**Comment by codebude** [comment]
Hi together, 

I'm the creator of the QRCoder library linked above. If you need any help, let me know. By the way, the QRCoder lib brings an payload generator with it, which can create TOTP QR payloads. Documentation: https://github.com/codebude/QRCoder/wiki/Advanced-usage---Payload-generators#311-one-time-password Code: https://github.com/codebude/QRCoder/blob/master/QRCoder/PayloadGenerator.cs#L1689

**Comment by TomCJones** [comment]
Pull request #57 shows 2fa running.  https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/pull/57

**Comment by leastprivilege** [comment]
We cannot provide such samples. This would be a community/consulting effort

**Comment by MovGP0** [comment]
in case anybody wants to work on this

* [TOTP/HOTP library](https://github.com/kspearrin/Otp.NET) 
 *  [URL format for authenticator](https://github.com/google/google-authenticator/wiki/Key-Uri-Format)

**Comment by eaba** [comment]
@MovGP0 is this in any way different from aspnet.core identity two step authentication?

**Comment by MovGP0** [comment]
There are different methods of two step authentication. One way is to send an SMS with a one-time-password ([Twilio](https://www.twilio.com) is quite good). Another is to use a FIDO U2F Token, like a [Yubikey](https://en.wikipedia.org/wiki/YubiKey) or [Google Titan Key](https://cloud.google.com/titan-security-key/). 

TOTP and HOTP are another method(s), similar to those [RSA SecurID](https://en.wikipedia.org/wiki/RSA_SecurID) tokens, which some companies used before. The standard is supported by multiple smartphone apps, like Google Authenticator, Microsoft Authenticator, LastPass Authenticator, and others, as well as many large Websites like Google, Microsoft, Twitter, Facebook, GitHub, LastPass, and some others. So this is basically my daily driver for secure logins on the Internet.
