### ISSUE TITLE
Token verification fails caused by missing kid

### ISSUE THREAD

**Issue by hubertstrk** [IdentityServer/IdentityServer4#2082]
I am trying to use the external login functionality with Identity Server 4.2 where I get the following exception: `System.Exception: Correlation failed` ([correlation-failed.txt](https://github.com/IdentityServer/IdentityServer4/files/1736981/correlation-failed.txt))

Currently there are a few uncertainties for me. Therefore to get a better insight I used the [https://openidconnect.net](https://openidconnect.net) playground to run the flow. As a result I get an id token which I can read with the help of [https://jwt.io](https://jwt.io). So this is fine. However the last step says _There was an error verifying your token. Try again_. 

After digging a bit I noticed that the keys endpoint on the external idp lacks the _kid_ parameter. There is _kty_, _use_, _alg_, _n_ and _e_ but no _kid_.  The specification says that the kid is optional but I couldn't find any information telling under what circumstances the _kid_ is needed or when not. Finally it is the only thing I can see which might be wrong or missing.

If the error is related to the missing _kid_ then apparently you could create the kid out of _n_ and _e_ ([https://github.com/IdentityServer/IdentityServer4/issues/1537](https://github.com/IdentityServer/IdentityServer4/issues/1537)).
My question is does this also apply to the verification of id tokens or am I totally on the wrong track here?

_(unfortunately the external implementation of the idp cannot provide a kid, so this is not an option and since the kid is optional I would call  the external idp oidc conform)_

**Comment by brockallen** [comment]
I don't understand -- IdentityServer always provides a kid, so which token server are you talking about when you say the kid is missing?

Also, this error:

> Correlation failed

Is a client-side error typically due to cookie issues (which means it's unrelated to IdentityServer). Check with Microsoft support on this issue -- there are tons of issues related to it since many people run into it.

**Comment by ChristophBroeker** [comment]
We are using the external login functionality of the Identity Server 4.2. So the Identity Server ist the client and the idp is form an other company. So during the implicit flow we got the error 
`System.Exception: Correlation failed`. 

To get a better insight we run the flow with https://openidconnect.net. And there we got the error that the kid parameter is missing. But that should not be the problem. The idp is providing the n and e parameter, which should be sufficient to execute the implicit flow. With the n and e parameter it is possible to create the public key and therefore it is possible to validate the id token. 

But could it be possible that the Identity Server has the same error like the implementation of  https://openidconnect.net, which needs apparently a kid parameter.

**Comment by brockallen** [comment]
All of these are in your login page that is using OIDC and the Microsoft OIDC authentication handler, right? The fact that it's hosted along side of IdentityServer sounds unrelated, IMO. IOW, I'd suggest getting a stand alone ASP.NET Core app working with your OIDC IdP outside of IdentityServer. If/when you run into these errors, then contact Microsoft for help as I think you will find it's all related to their components.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
