### ISSUE TITLE
JWT client authentication only supports "self issued" assertions

### ISSUE THREAD

**Issue by NilsEngelbach** [IdentityServer/IdentityServer4#2083]
When looking into the code for client assertion i stumbled over this line:

`"Both 'sub' and 'iss' in the client assertion token must have a value of client_id."`

https://github.com/IdentityServer/IdentityServer4/blob/2fec5dbcf4f8eea735d3d616296caad9540ebdb9/src/IdentityServer4/Validation/PrivateKeyJwtSecretValidator.cs#L104

In the [Open ID Spec](http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) this is also required.
But in the [Assertion Framework for OAuth 2.0](https://tools.ietf.org/html/rfc7521) and [RFC 7523](https://tools.ietf.org/html/rfc7523#section-3) it is also mentioned that it is possible to create the assertion by a (external) "Token Service" where the issuer must contain a unique identifier for the entity that issued the JWT (!= ClientID).

So is it an intended behavior that only "self issued" assertions by the clients are possible?

**Comment by brockallen** [comment]
For a token issues by a separate STS, then you'd implement it as an extension grant: http://docs.identityserver.io/en/release/topics/extension_grants.html
