### ISSUE TITLE
Question: How to set different IdentityServerAuthenticationOptions for integration tests?

### ISSUE THREAD

**Issue by alesdvorakcz** [IdentityServer/IdentityServer4#2084]
Hello, in older version, it was possible to set IdentityServerAuthenticationOptions as a singleton to DI Container like this:
```
public void ConfigureServices(IServiceCollection services)
{
    services.TryAddSingleton(new IdentityServerAuthenticationOptions
    {
        Authority = Configuration.IdentityServerAuthority(),
        ScopeName = "api1",
        ScopeSecret = "secret",
        //...,
    });
}

public void Configure(IApplicationBuilder app)
{
    var options = app.ApplicationServices.GetService<IdentityServerAuthenticationOptions>()
    app.UseIdentityServerAuthentication(options);

    //...
}
```

but now I cant find any way ho to do it (I need different settings for production/development and different for integration testing (there identity server runs in memory trough TestServer).
I tried something like this
```
services.TryAddSingleton(new IdentityServerAuthenticationOptions
{
    Authority = identityServerConfig.Authority,
    RequireHttpsMetadata = false,
    ApiName = Constants.API_ID,
    RoleClaimType = CustomClaimTypes.Role,
    NameClaimType = CustomClaimTypes.Name,
});
services.AddAuthentication("Bearer")
    .AddIdentityServerAuthentication("Bearer");
```
but it looks I cant create from scratch my own instance of IdentityServerAuthenticationOptions. now I can only use .AddIdentityServerAuthentication(options => ...) to modify existing instance...

Is there any way how to achieve this? Thanks

**Comment by brockallen** [comment]
Here's how we do it: https://github.com/IdentityServer/IdentityServer4/blob/dev/test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs#L74

**Comment by alesdvorakcz** [comment]
so there is no way how to do it with .UseStartup<Startup>() ?

**Comment by brockallen** [comment]
We use the IOptions pattern in ASP.NET Core, so you can look into how to configure that.

**Comment by alesdvorakcz** [comment]
the solution for me was IStartup interface which is not well documented. More info for example here: (just in case anyone will have same problem)
https://www.strathweb.com/2017/06/resolving-asp-net-core-startup-class-from-the-di-container/
