### ISSUE TITLE
Plus character in client's secret causes failed secret validation

### ISSUE THREAD

**Issue by rshramko** [IdentityServer/IdentityServer4#2086]
We upgraded from IdentityServer4 from 2.1.1 to 2.1.2 and suddenly discovered that some of our clients cannot get tokens using client_credentials grant type anymore.

We quickly looked into the issue and found out that if a client has the plus character in its secret (+) and the client sends the secret using Basic authentication header, this leads to the auth failure. If the client sends the secret as a part of the POST body (as a form parameter), everything works as it should be.

### Issue / Steps to reproduce the problem

1. Define a client, which has the plus character in its secret.
2. Try requesting a token using the Token Endpoint using Basic Auth for sending credentials:

```
curl --request POST \
  --url http://identity.apaleo.local:49786/connect/token \
  --header 'Authorization: Basic bXljbGllbnQ6QWJjZCsxMjM0' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'client_id=myclient&grant_type=client_credentials'
```

You will see that the request fails.

3.Now try requesting the token this way:

```
curl --request POST \
  --url http://identity.apaleo.local:49786/connect/token \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data 'client_id=myclient&grant_type=client_credentials&client_secret=Abcd%2B1234'
```

This time the token you'll get the token.

### Relevant parts of the log file

```
2018-02-19 20:22:57.7118|IdentityServer4.Validation.ClientSecretValidator|ERROR|Client secret validation failed for client: myclient
```

**Comment by leastprivilege** [comment]
We recently fixed a bug with how credentials transmitted via the authorization header are decoded (https://tools.ietf.org/html/rfc6749#section-2.3.1).

My guess is you are also encoding them not 100% correctly. See this discussion:

https://github.com/IdentityServer/IdentityServer4/issues/2039

**Comment by rshramko** [comment]
@leastprivilege Thank you for the clarification, now it's clear why the plus character doesn't work anymore.

Well, I won't be arguing about the correctness, or incorrectness of the fix applied. As for me this smells like a problem with RFC6749 itself.

Responding to to your question: yes, we don't do URL-encoding of secret in our internal implementation, we need to adjust the code.

And so do our 3rd party clients, that use a variety of different languages and frameworks, and looks like we need to ask them to adjust their implementations as well.

And so do ubiquitous tools like curl and postman, as obviously they have no idea that for some strange reasons the Basic Auth header needs to be double-encoded.

The latter case is the most frustrating one, as I believe, the amount of people who remembers RCF6749 by heart is next to nothing, and attempt to get a token using curl during troubleshooting might be quite an interesting experience.

**Comment by ozonni** [comment]
this literally brakes all clients in the world, starting with `curl` and millions of nodejs/js libs for oatuh. @leastprivilege how am i suppose to ask all of them suddenly adjust the way they send credentials to us?

**Comment by leastprivilege** [comment]
I understand - and I also didn't know it. But we got error reports from people using spec-compliant client libraries where we decoded the secret using standard basic authN.

I guess the fact is that OAuth2 does NOT use basic authentication - but their own flavour of it. 

As an alternative you can always send client id and secret in the POST body instead.

**Comment by rshramko** [comment]
Thank you, @leastprivilege 

We will communicate to our API clients, asking either for the code adjustment, or the client_secret itself.

I'm closing the issue then, as there's nothing you can really do about it.

Thanks again for being responsive, really appreciate it!

**Comment by pgrm** [comment]
Maybe add a `+` character to one of the test-clients credentials?

**Comment by vmh32** [comment]
I was experiencing similar issue because the client secret contained this character: '#'
