### ISSUE TITLE
Notifying clients that the user has signed-out not working

### ISSUE THREAD

**Issue by eliasnawfal** [IdentityServer/IdentityServer4#2089]
Upgrading from 1x to IdentityServer4 2.1.2.
I have many MVC clients that I want to logout from when the user triggers logout on client 
`  await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignOutAsync("oidc");`
This action redirects to logout action method "logout" in IdentityServer that is like the sample
[IdentityServerSamples Account Controller AspNetIdentity ](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/6_AspNetIdentity/src/IdentityServerWithAspNetIdentity/Controllers/AccountController.cs)
I'm using same LogoutViewModelBuilder.

The problem is if I logout from one MVC client and the iFrame is rendered correctly (SignOutIFrameUrl has value) other mvc client are not signing out clearing cookie.

I read new documentation  [Signout IdentityServer release](https://identityserver4.readthedocs.io/en/release/topics/signout.html)

and tried to set value for BackChannelLogoutUri and FrontChannelLogoutUri  but still logout on all client didn't work.

**Comment by leastprivilege** [comment]
We simply call whatever logout URI is configured. You need to debug/network trace why this does not work for you.

Check our samples repo for working examples.

**Comment by eliasnawfal** [comment]
@leastprivilege Thank you for your response, I was able to solve the problem after reading OpenId documentation about FrontChannelLogout and BackChannelLogout, I set FrontChannelLogoutSessionRequired to false, and I pointed FrontChannelLogoutUri to my logout ActionMethod of each client.

**Comment by zyofeng** [comment]
Sorry for resurrecting an old ticket, I am still unclear on how this worked.
I have two RPs using IdV4, when I sign-out without specifying the logoutId, shall I expect both clients to be notified through multiple iframes?

If so how is this achieved? I am using the QuickStart sample code and I can only get it working with one client (since there is only 1 iframes on the LoggedOutView)

The OpenId documentation does not clarify on how frontchannel_logout_uri would work in a multi-RP scenarios rather it was talking about logging out downstream RPs which is irrelevant to my question.

**Comment by kloudja** [comment]
@zyofeng the identity server returns a signOutIframeUrl that will contact the identity server endpoint.
It will create mini iframes inside the big iframe and those mini iframes will point to each front channel logou uri you described for each client.
In simple terms is this

**Comment by phungdkh** [comment]
> We simply call whatever logout URI is configured. You need to debug/network trace why this does not work for you.
> 
> Check our samples repo for working examples.

Hi @leastprivilege
Could you help to provide the link of samples repo for working examples?

Many thanks,
Phung Dinh

**Comment by leastprivilege** [comment]
Check the "Manual MVC Client" in the samples folder.

**Comment by phungdkh** [comment]
@leastprivilege

I got it.

Thanks a lot,
Phung Dinh
