### ISSUE TITLE
/connect/endsession redirect post_logout_redirect_uri parameter not used

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#209]
If I set the post_logout_redirect_uri parmeter in the connect endsession api call,it is not used in IdentityServer4, only the URL defined in the Client configuration.

**Comment by brockallen** [comment]
The URL being passed -- is it in the client's list of allowed post logout redirect uris?

**Comment by damienbod** [comment]
Sorry, this is working, rechecked it and the URL didn't match one of the URLs in the PostLogoutRedirectUris
