### ISSUE TITLE
Use Exception overload of ILogger.LogCritical for unhandled exceptions

### ISSUE THREAD

**Issue by chrisowhite** [IdentityServer/IdentityServer4#2090]
Unhandled exceptions are caught in `IdentityServerMiddleware` this way:

`_logger.LogCritical("Unhandled exception: {exception}", ex.ToString());`

Since this is not using the overload of `LogCritical` that takes an exception object, registered loggers do not receive the full exception details, making it difficult to aggregate resulting log data based on just the exception message. When using Kestrel, the exception is caught again and an event is emitted with the exception object. 

Consider something like:

`_logger.LogCritical(ex, "Unhandled exception: {exception}", ex.Message);`

**Comment by brockallen** [comment]
Yep, good catch.

**Comment by chrisowhite** [comment]
Looks like there are 2 more spots in TokenValidator...

`_logger.LogError("JWT token validation error: {exception}", ex.ToString());`
`_logger.LogError("Malformed JWT token: {exception}", ex.ToString());`

**Comment by brockallen** [comment]
Just PR please. Thanks
