### ISSUE TITLE
Flow to update access token claims when coming through refresh token

### ISSUE THREAD

**Issue by phoenixjun** [IdentityServer/IdentityServer4#2093]
We are developing a Identity server in the company which has a few child company and the user information stores in the database within the child company. So currently the structure is the Identity server 4 will talk to individual IDP to get the access token and then forward back to the client (We implement IResourceOwnerPasswordValidator and control which IDP to talk to). Everything is working fine until we want to support the refresh token.

<code>

                                              <---------------> [Individual IDP 1]

[Client] <------------> [IdSrv (IDP4)] <---------------> [Individual IDP 2]
 
                                             <---------------> [Individual IDP 3]
</code>

In our scenario, the user information / claims stores in the sub system and not in the main IDP server, so when the user want to get a new access token, we need to talk back to the IDP server to do that (through API call, there is no direct access to the database).

There are similar discussion in the forum, and it seems like that IProfileService could do the job. I was thinking to implement that interface and call the individual IDP when renewing the access token. I would like to know

1. is there a way to identity the requested scope and grant type when implementing the GetProfileDataAsync? I only want to communicate to the sub system for the updated claim under the context of grant_type=refresh_token. and also, i need those information in order to define which subsystem to connect to
2. is there any recommended approach to communicate with the sub system for the updated claims in this scenario? at the moment, the main IDP talk to the other sub system through API call.
3. Or is there a better approach instead of implementing the IProfileService

**Comment by phoenixjun** [comment]
https://stackoverflow.com/questions/48905831/flow-to-update-access-token-claims-when-coming-through-refresh-token

I have posted a question in the stackoverflow as well. Any comments / suggestions are welcome.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
