### ISSUE TITLE
Any way to extend the issue token functionality?

### ISSUE THREAD

**Issue by iberodev** [IdentityServer/IdentityServer4#210]
I am trying to record each time a new identity token is issued (e.g: LastLoggedInOn field or similar).
Is there any way to extend or access the token endpoint (maybe by sending a callback action) so that I can do something with my Identity Server host whenever Identity Server 4 generates a token?

**Comment by brockallen** [comment]
We will have events like we did in IdSvr3 and that could be a place for you to record that a user had a token issued. We're just not there yet in the implementation.

**Comment by leastprivilege** [comment]
Events are already implemented.
