### ISSUE TITLE
IRedirectUriValidator

### ISSUE THREAD

**Issue by DiginessForever** [IdentityServer/IdentityServer4#2100]
I created a custom class to validate redirectUris, implementing IRedirectUriValidator on my IdentityServer4 implementation.

In the IdentityServer4 startup in ConfigureServices, I have:
```
services.AddIdentityServer()
   .AddRedirectUriValidator<AuthorizedRedirectValidator>()
```

(the .AddRedirectUriValidator line is just one of the many sub functions called after AddIdentityServer())

I've tried putting the above in different orders, but regardless, when I run a client through the authentication, the above class that implements IRedirectUriValidator isn't getting called (it still calls the standard one).

Do I need to do anything else?  I realize that implementing your own validator instead of doing an exact match can open you to covert redirects and have exacting safeguards in the validator.

**Comment by DiginessForever** [comment]
I've been playing with a client and its redirectUris and finally got the above to trigger.  It seems though that the standard redirect validator is still running beforehand and rejecting any uris that aren't explicitly mentioned in the server side client config.  Any way I can completely override it?

**Comment by DiginessForever** [comment]
It seems that without being explicitly in the allowed uris, it fails on the authorize endpoint and throws an error:  (the below being run with minimal validation in the interface, only for debugging)

> IdentityServer4.Endpoints.AuthorizeEndpoint:Information: {
>   "ClientId": "myClient",
>   "ClientName": "Custom Web Client",
>   "AllowedRedirectUris": [
>     "https://localhost:44001"
>   ],
>   "SubjectId": "anonymous",
>   "RequestedScopes": "",
>   "Raw": {
>     "client_id": "myClient",
>     "redirect_uri": "https://localhost:44001/home",
>     "response_mode": "form_post",
>     "response_type": "code id_token",
>     "scope": ...
>     "state": "OpenIdConnect.AuthenticationProperties=...
>     "nonce": ...
>   }
> }

**Comment by DiginessForever** [comment]
I created a StackOverflow question as well:  
https://stackoverflow.com/questions/48952192/identityserver4-redirect-validator-implementing-iredirecturi-interface

**Comment by leastprivilege** [comment]
> It seems though that the standard redirect validator is still running beforehand and rejecting any uris that aren't explicitly mentioned in the server side client config. Any way I can completely override it?

I don't think your observation is right - check our main repo, we use a custom validator there as well and it works as expected.

**Comment by Greeng0** [comment]
FWIW, I believe I found the cause of @DiginessForeve's issue.
If the Client.RedirectUris property is not set, or is set to an empty collection, then the IRedirectUriValidator will not be invoked. There needs to be a value in Client.RedirectUris. even if it's a garbage one. See the Config.cs here: https://github.com/IdentityServer/IdentityServer4.Demo/blob/master/src/IdentityServer4Demo/Config.cs, where we can see "https://notused" used everywhere as the RedirectUri.

**Comment by EddyPPP** [comment]
I've been trying to get this working too, and have found that `AddRedirectUriValidator<...>()` doesn't seem to work, but adding this line (like the demo project) was successful:
`services.AddTransient<IRedirectUriValidator, ...>();`
