### ISSUE TITLE
How to debug Identityserver4 source code

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer4#2103]
I want to debug Identityserver4 source code, so I can understand the underlying logic of the entire code, but I do not know how to do it. Does anyone know how to debug identityserver4 source code? Thank you

Please forgive me my English is not very good

**Comment by aneequrrehman** [comment]
@YINZHU2016 This isn't exactly an issue. 

Identity Server 4 is open source, so you can look into the code any way you want. But to run it in debug mode, you can project-reference it by cloning a copy.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
