### ISSUE TITLE
non .net core WebApi how to use identityserver4

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer4#2104]
I want to use Identityserver4 as a SSO product for prod. But I have 2 questions

1. Is this project already in release version? Because I didn't find the message that the stable version was published in the github document.but i see a release branch and some version tag in github.but i not sure.

2,  I want to use identityserver4 to do sso, but because the company before the API project is the use of non.Net core version of the webapi project, it is not possible to use identityserver4 to provide authentication middleware to do validation, how can I do to let the old API can use identityserver4 to do the certification? I don't want to use identityserver3, and I want to use the latest identityserver4
thanks
sorry abut my english is not good

**Comment by brockallen** [comment]
> Is this project already in release version? Because I didn't find the message that the stable version was published in the github document.but i see a release branch and some version tag in github.but i not sure.

Yes it is, and those are how we track formal releases. You can find the release binary on nuget.

>  I want to use identityserver4 to do sso, but because the company before the API project is the use of non.Net core version of the webapi project, it is not possible to use identityserver4 to provide authentication middleware to do validation, how can I do to let the old API can use identityserver4 to do the certification? I don't want to use identityserver3, and I want to use the latest identityserver4

We implement specifications of protocols, so any app that can communicate with those protocols then yes. It's all about interopability.

As for the details of using OIDC and OAuth2 in your apps and API, this issue tracker is not the place for that.

**Comment by YINZHU2016** [comment]
Is there any blog or document ask how to do it in non .net core ? because i don not how to do it.

**Comment by TomCJones** [comment]
If you want .net framework for the api just use I’d server3 to get the samples for that.

Then use id server4 for all the rest.
