### ISSUE TITLE
Is Old .net mvc or webapi can use idrv3 plug to connect idrv4 sso

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer4#2106]
I check a lot of information,like google,github,stackoverflow, many people have such a scene, is the use of isrv4 as the SSO server, then they have a lot of non.Net core.Net freamwork webapi , the old project to nedd token verification in idrv4 sso, so they can only use IdentityServer3.AccessTokenValidation. 

In theory, a client system like AccessTokenValidation doesn't need to pay attention to which version of SSO is, because it will do token verification if it follows oidc protocol. I also see the above GitHub a lot of issue, but also illustrates the problem, but I would like to ask, because this scene will be more, so you can determine whether we use IdentityServer3.AccessTokenValidation compatible with all idrv4 in.Net freamwork old webapi? Because it's very likely that these old API will almost never be altered and upgraded to.Net

The version of core is a very common scenario for IdentityServer3.AccessTokenValidation's robust docking with idrv4's SSO. Whether your project is going to write a sample. Let me talk about how to use IdentityServer3.AccessTokenValidation in old.Net webapi projects to do idrv4 SSO. I think there will be many people who want to upgrade idrv4 want to know this knowledge.

Even a lot of people want to know whether old.Net MVC project can use original identityserver3 plug-in to connect idrv4's AuthorizationCode or other modes.

thank you

Sorry about my English is not good

**Comment by brockallen** [comment]
https://github.com/IdentityServer/CrossVersionIntegrationTests

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
