### ISSUE TITLE
[Question] Startup.cs - throw new Exception("need to configure key material");

### ISSUE THREAD

**Issue by LaurentFromParis** [IdentityServer/IdentityServer4#2107]
Hi,

This is not a bug, just a question.
When I tryed to execute dotnet MyIdServer.dll /seed
I got : throw new Exception("need to configure key material");

I did this :
`
#if DEBUG
                var certPath = Path.Combine(Directory.GetCurrentDirectory(), "Cert", "MyIdServerLocalhost.pfx"); //IISExpressCertificate
                X509Certificate2 cert = new X509Certificate2(certPath, "MyLocalhostCertPassword");
#else
                    var certPath = Path.Combine(Directory.GetCurrentDirectory(), "Cert", "MyIdServer.pfx");
                    X509Certificate2 cert = new X509Certificate2(certPath,"MyProductionCertPassword");
#endif

builder.AddSigningCredential(cert);
`

My question is :
This means when you seed the database for production, you cannot use it in localhost test mode because some encryption is different ?

If yes, do I have to seed a first database for localhost with a first connectionstring and a second one for production ?

Thanks

**Comment by brockallen** [comment]
The docs have many of your answers:
http://docs.identityserver.io/en/release/quickstarts/0_overview.html
http://docs.identityserver.io/en/release/topics/crypto.html

**Comment by leastprivilege** [comment]
Also - learn about the hosting environment concept in ASP.NET Core - this is orthogonal to DEBUG.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by Alex2357** [comment]
> The docs have many of your answers:
> http://docs.identityserver.io/en/release/quickstarts/0_overview.html
> http://docs.identityserver.io/en/release/topics/crypto.html

The links are broken. Could you update them?

**Comment by jmb1304** [comment]
Here are the updated links:

[http://docs.identityserver.io/en/latest/quickstarts/0_overview.html](http://docs.identityserver.io/en/latest/quickstarts/0_overview.html)

[http://docs.identityserver.io/en/latest/topics/crypto.html](http://docs.identityserver.io/en/latest/topics/crypto.html)

**Comment by Alex2357** [comment]
> Here are the updated links:
> 
> http://docs.identityserver.io/en/latest/quickstarts/0_overview.html
> 
> http://docs.identityserver.io/en/latest/topics/crypto.html

Thanks for the update
