### ISSUE TITLE
[Bug] IdentityServerWithAspIdAndEF sample DBGeneration cluster index max lenght

### ISSUE THREAD

**Issue by LaurentFromParis** [IdentityServer/IdentityServer4#2108]
Hi,

I work on IdentityServerWithAspIdAndEF sample 
I replaced UseSqlite with UseSqlServer, I regenerated my migration and I created the database.
I used the script database task to create a second database with the same structure for my tests.
SSMS throw a warning : max length for a clustered index is 900 bytes and [PK_AspNetUserLogins, PK_AspNetUserRoles, PK_AspNetUserTokens] has a length of [1800, 1800, 2700].

PK length must be restraint to 900 bytes isn't it ? 

Thanks

**Comment by brockallen** [comment]
That's a Microsoft issue, not an IdentityServer issue.
