### ISSUE TITLE
[QUESTIOn] Azure Deploy fail redirect URI 

### ISSUE THREAD

**Issue by oottoohh** [IdentityServer/IdentityServer4#2111]
i have client app with razor MVC and identity server running on   **azure**
my problem is client always fail to call redirect uri with IP public

**this is my startup.cs**

`services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
                .AddCookie("Cookies")
                    .AddOpenIdConnect("oidc", options =>
                    {
                        options.SignInScheme = "Cookies";

                        options.Authority = "http://<this is my ip>:8080";   //IP PUBLIC HERE
                        options.RequireHttpsMetadata = false;

                        options.ClientId = "webapp2";
                        options.ClientSecret = "web123";
                        options.ResponseType = "code id_token";

                        options.SaveTokens = true;
                        options.GetClaimsFromUserInfoEndpoint = true;

                        options.Scope.Add("masterdataapi");
                        options.Scope.Add("offline_access");
                    });
        }
`

and this is my **Config.cs** on Identity
`ClientSecrets =
                    {
                        new Secret("web123".Sha256())
                    },

                    RedirectUris           = { "http://<this is my ip>/signin-oidc" },
                    PostLogoutRedirectUris = { "http://<this is my ip> /signout-callback-oidc" },`
Please help me! thanks

**Comment by brockallen** [comment]
Not enough info and really no idea -- sounds like an environmental issue you need to work out.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by oottoohh** [comment]
yea you can close this, thanks
