### ISSUE TITLE
Setting user specific access token lifetime

### ISSUE THREAD

**Issue by sharfanfq** [IdentityServer/IdentityServer4#2112]
I am having my identity server running with multiple clients and having different access-token lifetime per client.. which works perfectly, I would like to know how it is possible to have tokens generated on different lifetime span based on user preference

### I have added a sample client here

```
new Client
                {
                    ClientId = "Id",
                    ClientName = "Name",
                    Flow = Flows.ResourceOwner,
                    ClientSecrets = new List<Secret>()
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowAccessToAllScopes = true,
                    AccessTokenLifetime = 31536000,
                    AccessTokenType = AccessTokenType.Reference
                }
```
thanks

**Comment by brockallen** [comment]
You could have a custom authorize/token request validator that changes the `AccessTokenLifetime` on the `ValidatedRequest`.

**Comment by sharfanfq** [comment]
Okay thanks

**Comment by Mubeen07** [comment]
@sharfanfq can you help me out on this, how you figure this out. having same problem statement
