### ISSUE TITLE
ResourceId usage and implementaion

### ISSUE THREAD

**Issue by richardlawidjaja** [IdentityServer/IdentityServer4#2113]
so at the moment i am migrating from spring framework to IS4, however i am puzzled on how can we set the resource id,
so here is the scenario a Java based microservices called customer will make a call to my IS4 services to get the access token. everything went well we able to verify the token generated however since the client is a java based it throws a
{
    "error": "access_denied",
    "error_description": "Invalid token does not contain resource id (oauth2-resource)"
} 

in my implementation my IS is using custom client store that implement IClientDetailsService
![image](https://user-images.githubusercontent.com/29135672/36772271-810dc368-1c8f-11e8-8637-f66af8f7bfe2.png)

i did set the ResourceId There but when a request made to the Java application it throws error above,
so could you give an example on how can we set the resource id?

**Comment by leastprivilege** [comment]
I don't know what ClientDetails is - certainly not one of our classes. I also don't know what a "ResourceId" is - never heard the term before.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by richardlawidjaja** [comment]
I found what was the problem so basically in Spring framework implemntation they have a default value for a resource id, now the reason why IS4 does not work is because we dont really need the resource Id.
the quickest fix that i have done is by adding the java resouce id value to IS4 and it works well. so yes case is closed.
