### ISSUE TITLE
Add more configuration validation to token/authorize pipeline

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#2114]
initiated by https://github.com/IdentityServer/IdentityServer4/issues/2072

let's collect more config checks here and then implement them in one go.

* AccessTokenLifetime is 0

what else?

**Comment by LindaLawton** [comment]
1. Browser enabled with no redirect URI set?    
2. Using JavaScript without setting cors 
3. RequireClientSecret missing a secret?  

I don't think its worth invaliding the max tokenlifetime,  being that its an int the potential age of the access token is greater then the epoch time.   I think you and I discussed this on stack. [link](https://stackoverflow.com/a/48149679/1841839)

**Comment by brockallen** [comment]
Ideas:
 * maybe add a check to `IClientStoreExtensions.FindEnabledClientByIdAsync` since most (if not all) of our code should be funneling thru that API to load a client
* maybe add a new service in DI to do the validation. possibly devs could replace to add their own checks? On the values in `Properties` for example?

**Comment by LindaLawton** [comment]
On the values in Properties for example?  <---- Love that idea since i am using properties.

**Comment by chrisowhite** [comment]
Are you guys looking to implement specific default rules for 2.x or would that be a 3.0 thing (saw the comment from @leastprivilege in the above PR)?

**Comment by leastprivilege** [comment]
I will merge the base infrastructure today. But it will be no-op by default. Then we can "crowd source" validation rules to be used optionally. They will then become the default in 3.0

**Comment by leastprivilege** [comment]
OK - here's the new validator:

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/DefaultClientConfigurationValidator.cs

It's not enabled by default - but in the host it is:
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Host/Startup.cs#L52

I added a bunch of validation checks already. Feel free to PR to add new ones!

Each check should have a corresponding test here:
https://github.com/IdentityServer/IdentityServer4/blob/dev/test/IdentityServer.UnitTests/Validation/ClientConfigurationValidation.cs

**Comment by LindaLawton** [comment]
What happens if no context.Client.PostLogoutRedirectUris is supplied?

**Comment by leastprivilege** [comment]
Well - that's an optional setting.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/2317

**Comment by janpieterz** [comment]
When, for example, using an int.MaxValue (a valid configuration value) for SlidingRefreshTokenLifetime, the result of below line can mean the integer becomes a negative value. This is relevant for scenario's with, for example, the AbsoluteRefreshTokenLifetime set to 0 and a Sliding expiration, where people expect them to be valid forever (or at least significantly long enough to not matter).


https://github.com/IdentityServer/IdentityServer4/blob/325ea0e67b1de2c836f26eb38436ff07177028d4/src/IdentityServer4/Services/DefaultRefreshTokenService.cs#L120

There's a couple of options here:

1.  Ensure the configuration can never exceed int.MaxValue / 2 when configuring a client (but what about database changes?)
2. Change the processing code to ensure this won't happen (either on load of client settings limit it to int.MaxValue / 2 and log it, or when issuing a new lifetime ensure it doesn't pass it and go negative)
3. Change it to a uint and if exceeding set it to uint.MaxValue
4. Ignore 😄 

Happy to submit a PR once we know the option.
