### ISSUE TITLE
Wrong GrantValidationResult error value

### ISSUE THREAD

**Issue by HasanAJ** [IdentityServer/IdentityServer4#2116]
I get the wrong error value from GrantValidationResult inside my custom IResourceOwnerPasswordValidator.

Here is the code:

    if (roles.Contains(Constants.ROLES_CLIENT))
    {                
        if (!user.PhoneNumberConfirmed)
            {
                 context.Result = new GrantValidationResult(TokenRequestErrors.InvalidRequest, "Phone 
                 number not verified");
                 return;
            }
    }

When the token endpoint is called, I get the following:

    {
       "error": "invalid_grant",
       "error_description": "Phone number not verified"
    }

I try all types of TokenRequestErrors but I always get invalid_grant.

I also try to change this value using the following line but it also doesnt work: context.Result.Error = "whatever";

**Comment by user1336** [comment]
I think I found it, this line shouldn't use `OidcConstants.TokenErrors.InvalidGrant` but use the `resourceOwnerContext.Result.Error`
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/TokenRequestValidator.cs#L427 

Can I submit a PR?

**Comment by leastprivilege** [comment]
Yes. Thanks.
