### ISSUE TITLE
Is there any backport or library like IdentityServer4.AccessTokenValidation for non-core frameworks?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#2117]
We have a full framework Web API 2.2 app we want to add Identity Server Authentication to.

I know that I can use any easily available 3rd party JWT token to verify the JWT but what about reference tokens?

**Comment by VictorioBerra** [comment]
@brockallen Isn't that only for Katana? I don't have anywhere I can do `x.Use` or `x.Add`.

**Comment by brockallen** [comment]
That's all there is. You can always build your own. It's just the introspection spec: 
https://tools.ietf.org/html/rfc7662

As part of it you could use IdentityModel's IntrospectionClient library: 
https://github.com/IdentityModel/IdentityModel2
https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/IntrospectionClient.cs

**Comment by VictorioBerra** [comment]
I see in the middleware handler after you get the token you call AuthenticateAsync, how does it validate the tokens from there? I assume I will have to do that part too?

**Comment by VictorioBerra** [comment]
I think I see what's happening. You AddJwtBearer and then AuthenticateAsync invokes that handler. Does it hit the discovery endpoint for the pubic signature to verify the token and all that? How does it know how to do that

**Comment by brockallen** [comment]
Read the code. It's all up there.
