### ISSUE TITLE
Server generates token, client returns "Message contains error: <invalid_request>"

### ISSUE THREAD

**Issue by joaco-espinosa** [IdentityServer/IdentityServer4#2118]
Hello,

I'm experiencing an issue hosting my Identity server behind load balancer.
I have one instance (planning on adding more) and I always get an error message on the client even though the login is successful and the token is correctly generated on the server.

Could you please help me narrow down the problem? I'm not sure if this is a client side problem or a server side one.

Client message:
```Message contains error: 'invalid_request', error_description: 'error_description is null', error_uri: 'error_uri is null'.```

Logs from server:
```"Token Issued Success" (2000) Detailed Event Information: "{ RemoteIpAddress: XXXX, ClientId: IdProviderWebClient, ClientName: Test Web Client - Authorization Code Flow, RedirectUri: http://localhost:5002/signin-oidc, Endpoint: Authorize, SubjectId: <GUID>, GrantType: authorization_code, Tokens: [ { TokenType: code, TokenValue: ****8b07 }]}"```

Stack trace:
```
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<RedeemAuthorizationCodeAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__21.MoveNext()
```

Client startup:
```
public void ConfigureServices(IServiceCollection services)
{
	JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

	services.AddAuthentication(o =>
	{
		o.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
		o.DefaultChallengeScheme = "oidc";
	})
	.AddCookie(CookieAuthenticationDefaults.AuthenticationScheme)
	.AddOpenIdConnect("oidc", o =>
	{
		o.Authority = Configuration["Authority"];
		o.ClientId = Configuration["OpenIdConnectOptions:ClientId"];
		o.ClientSecret = Configuration["OpenIdConnectOptions:ClientSecret"];
		o.GetClaimsFromUserInfoEndpoint = Convert.ToBoolean(Configuration["OpenIdConnectOptions:GetClaimsFromUserInfoEndpoint"]);
		o.RequireHttpsMetadata = Convert.ToBoolean(Configuration["OpenIdConnectOptions:RequireHttpsMetadata"]);
		o.ResponseType = Configuration["OpenIdConnectOptions:ResponseType"];
		o.SaveTokens = Convert.ToBoolean(Configuration["OpenIdConnectOptions:SaveTokens"]);

		foreach (var item in Configuration.GetSection("OpenIdConnectOptions:Scope").GetChildren())
		{
			o.Scope.Add(item.Value);
		}
		o.SignInScheme = Configuration["OpenIdConnectOptions:SignInScheme"];
	});

	services.AddMvc();
}
```

**Comment by leastprivilege** [comment]
The stack trace you are showing comes from the OpenID Connect handler from Microsoft. Open an issue with them.

Feel free to link to this issue and update us.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by joaco-espinosa** [comment]
Following up on https://github.com/aspnet/Security/issues/1677

**Comment by lbatistag80** [comment]
hey , any update with this? I am experiencing same issue.
