### ISSUE TITLE
Question:Would like to have API instead of a login authentication screen

### ISSUE THREAD

**Issue by BrahmaReddyMadhira** [IdentityServer/IdentityServer4#2123]
As part of my work,  I required to have  WEBAPI instead of a Login screen. I know that we can do this.
However would like to know challenges and concerns around it?

I know I have a weird requirement.

**Comment by ReeceWilliams7** [comment]
What exactly do you mean by a Web API? If you are referring to an API that you can call to validate some credentials and return your token(s), then perhaps you want to look at the resource owner password credentials grant: http://docs.identityserver.io/en/release/topics/resource_owner.html

It's not recommended as stated on this page: http://docs.identityserver.io/en/release/topics/grant_types.html but it might be what works for your use case.

**Comment by BrahmaReddyMadhira** [comment]
Thank you!  I meant like I don't to have Login screen where user enter username and password but rather I would like to have an API that can Authenticate and authorize.    I got the answer what I am looking for.
Thank you
