### ISSUE TITLE
Unable to run Quickstarts/7_JavaScriptClient

### ISSUE THREAD

**Issue by sajrashid** [IdentityServer/IdentityServer4#2125]
### Issue / Steps to reproduce the problem
IdentityServer Project does not build in Quickstarts 7.

**3 errors in total all in _AccountController_**

Line 255   User.GetDisplayName

'ClaimsPrincipal' does not contain a definition for 'GetDisplayName' and no extension method... 

Line 369  logout?.ClientName
'LogoutRequest' does not contain a definition for 'ClientName' and no extension method...

**Comment by brockallen** [comment]
Can you try to update to the latest IdentityServer nuget?

**Comment by sajrashid** [comment]
Updated to 2.12 and it's now working, thank you.
