### ISSUE TITLE
Multi-Tenant with AspNetCore.Identity

### ISSUE THREAD

**Issue by ovidiaconescu** [IdentityServer/IdentityServer4#2128]
Is there a preferred way to enable multi-tenancy on IDS4 on aspnetcore 2.0 using `AspNetCore.Identity`?

The samples from #442 - https://github.com/schatekar/IdentityServer4.MultiTenant and https://github.com/khelben/IdsvrMultiTenantExample based on https://github.com/saaskit/saaskit no longer work due to the fact that the method `UseCookieAuthentication` in `CookieAppBuilderExtensions` is now obsolete.

I've attempted to work it out like https://stackoverflow.com/questions/48384484/multitentant-identity-server-4#comment85163360_48384484 and modify the AspNetUser and SignInManager as in https://www.scottbrady91.com/ASPNET-Identity/Quick-and-Easy-ASPNET-Identity-Multitenancy but the issue stands that signing-in a user on one tentant automatically considers it signed-in on all clients.

**Comment by ovidiaconescu** [comment]
Since the problem is with `builder.UseCookieAuthentication`, as it is now obsolete,  I've done a PR on saaskit to update it to netcoreapp2.0 and changed the way auth is set in the `AspNetMvcAuthDemo`

I'm using two transient services that set the configuration from the tenant every time it is needed.
This is something that @brockallen suggested way back in #19 

See PR here: https://github.com/saaskit/saaskit/pull/96

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by ovidiaconescu** [comment]
Not unless there is another suggested way to achieve multi-tenancy?

**Comment by leastprivilege** [comment]
ASP.NET Core itself is not multi-tenant. So regardless how much duct-tape you put around it - there are limits.

**Comment by maxisam** [comment]
@leastprivilege your statement might not be true after 2.1. 

https://github.com/aspnet/Security/issues/1718

https://stackoverflow.com/questions/49596938/openid-connect-identifying-tenant-during-login/49682427#49682427
