### ISSUE TITLE
Load Balancing not verifying tokens from other instance

### ISSUE THREAD

**Issue by scossgrove** [IdentityServer/IdentityServer4#2130]
Hi,

I have two identical site that are API end points. Both these are not the UI for the identity server but merely an api back-end (CRUD basically) for the users in the system. 

everything is working fine for the following when on the same server:
1. Generate an email confirmation token. [ userManager.GenerateEmailConfirmationTokenAsync(user) ]
2. verify email token. [ userManager.VerifyUserTokenAsync(user, tTokenProvider, tPurpose, request.Token) ]

However when in the load balancing situation is machine A is generating the email confirmation token and machine B goes to verify the token, then the token is always invalid.

Can you tell me what I am doing wrong here, Is this a bug?

             --- The following is the configuration for the AspIdentity stuff ----
            // NOTE: This is the database connection class to be used
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(connectionString));

            // NOTE: This needs to stay in line with the Startup of the Identity Server projects
            services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            // NOTE: This is the Identity User classes to be used
            services.AddTransient<ApplicationUserStore>();
            services.AddTransient<ApplicationUserManager>();
            services.AddTransient<ApplicationRoleManager>();

            // NOTE: this is to set the password requirements for the user.
            services.Configure<IdentityOptions>(io =>
            {
                // Password Properties
                io.Password.RequireDigit = false;
                io.Password.RequiredLength = 10;
                io.Password.RequireNonAlphanumeric = false;
                io.Password.RequireUppercase = false;
                io.Password.RequireLowercase = false;
                // Lockout Properties
                io.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                io.Lockout.MaxFailedAccessAttempts = 5;
                io.Lockout.AllowedForNewUsers = true;
                // Configuration
                io.SignIn.RequireConfirmedEmail = true;
            });

            // NOTE:

            // NOTE: this is the messaging classes to be used
            services.AddTransient<IEmailSender, AuthMessageSender>();
            services.AddTransient<ISmsSender, AuthMessageSender>();

**Comment by brockallen** [comment]
> GenerateEmailConfirmationTokenAsync

This issue tracker is for IdentityServer issues. That's a feature of ASP.NET Identity, not IdentityServer. Check with Microsoft support.
