### ISSUE TITLE
Quickstart1_clientcredentials Client project is not building

### ISSUE THREAD

**Issue by ninjaboy** [IdentityServer/IdentityServer4#2134]
### Issue / Steps to reproduce the problem

Opening quickstart1_clientcredentials solution and trying to build it it generates the following errors for Client project:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8104	An error occurred while writing the output file: System.IO.IOException: Incorrect function.	Client	C:\Code\IdentityServer\IdentityServer4.Samples\Quickstarts\1_ClientCredentials\src\Client\CSC	1	N/A
Error	CS0016	Could not write to output file 'C:\Code\IdentityServer\IdentityServer4.Samples\Quickstarts\1_ClientCredentials\src\Client\obj\Debug\netcoreapp2.0\Client.dll' -- 'Incorrect function.	Client	C:\Code\IdentityServer\IdentityServer4.Samples\Quickstarts\1_ClientCredentials\src\Client\CSC	1	N/A

I am using Visual Studio 2017. The studio is started as Administrator.
Has anyone faced this?

**Comment by brockallen** [comment]
Do you have the latest nugets for IdentityServer?

**Comment by brockallen** [comment]
Do you have the latest nugets for IdentityServer?

**Comment by ninjaboy** [comment]
I have simply cloned this repository today as it is, packages are restored by default.
I have just updated the packages manually within Visual Studio and I believe all the packages are the latest now.

The issue still reproduces.

**Comment by brockallen** [comment]
Ok, thanks. We'll see if we can repro it.

**Comment by brockallen** [comment]
I just built the latest from both dev & release. It requires ASP.NET Core 2 SDK, etc...

**Comment by ninjaboy** [comment]
@brockallen , latest SDK is installed indeed.
Can you try one more thing please? In my case when I right click the solution itself and Build - it's ok. However, there's no dll created in src\Client\bin\Debug\netcoreapp2.0\ folder.
The issue reproduces when I explicitly right-click on the Client project and try to build.

I have also manged to reproduce the same issue on my colleague's machine with the same steps.
![image](https://user-images.githubusercontent.com/275925/36988706-6a25561e-2097-11e8-94f2-3e382f390f31.png)

**Comment by ape-box** [comment]
I'm having the same issue

**Comment by TomCJones** [comment]
visual studio seems to have some really weird behaviors based on historical files left around. I have had to completely restart one project (ie delete and re-new) and rebuild from scratch. I hear that the new release is fixing some of these problems. It can sometimes be fixed by deleting the bin on obj folders and rebuilding, but not always.
