### ISSUE TITLE
after publish the identiy 4 getting issue, in local it is working fine..

### ISSUE THREAD

**Issue by avinash1422** [IdentityServer/IdentityServer4#2137]
![identity issue](https://user-images.githubusercontent.com/29281656/37073798-12b3cf2e-21ef-11e8-81a4-69626ebc2208.jpg)

i created identiy 4 solution. it is working fine my local. when i publish to azure ,i am getting above issue after deploying the identity 4.

**Comment by huytnd** [comment]
Can you provide more details, especially the log file content?

**Comment by avinash1422** [comment]
thanks for your quick reply.
i published using azure web service profile. i am unaware of the getting log file . could you please let me know where can i find it..

**Comment by huytnd** [comment]
set stdout to true in the webconfig file, and create a "logs" folder.

**Comment by leastprivilege** [comment]
OK good - not IdentityServer related. Can I close?

**Comment by avinash1422** [comment]
i found the issue only , any solution for that.
 my local is working fine that sql credentials
