### ISSUE TITLE
Prompt Mode handling does not support multiple values

### ISSUE THREAD

**Issue by gb056** [IdentityServer/IdentityServer4#2138]
### Issue / Steps to reproduce the problem
The OpenIdConnect spec says the following of the prompt parameter: 
> **Space delimited**, case sensitive **list** of ASCII string values that specifies whether the Authorization Server prompts the End-User for reauthentication and consent.

This states that you can, for example, add `prompt=login consent` to force both login and consent, this (and any of the other combinations) however is not supported by IdentityServer4.

Suggest splitting the prompt parameter with the space delimiter and treating it as a list of requested prompt modes instead of looking for an exact match to one of them.

[Here](https://github.com/IdentityServer/IdentityServer4/blob/ad945f4204f19ce7dca40e29e51eb2b7bee3b918/src/IdentityServer4/ResponseHandling/AuthorizeInteractionResponseGenerator.cs#L101) is one place that the code just checks for a single prompt mode instead of checking whether it is contained in the list.

**Comment by leastprivilege** [comment]
Thanks! We'll consider it.

**Comment by brockallen** [comment]
PR submitted. Please have a look.

**Comment by brockallen** [comment]
PR merged
