### ISSUE TITLE
Code flow problem with IdentityModel NuGet package > 3.0.0

### ISSUE THREAD

**Issue by guidoffm** [IdentityServer/IdentityServer4#2139]
Server is IdentityServer4 2.0.2

When using code flow with IdentityModel client package 3.0.0 everything is fine.
After upgrading to a version > 3.0.0 gives this error:

"Client secret validation failed for client"

**Comment by leastprivilege** [comment]
There was a bug in IdentityServer and IdentityModel - either upgrade to the latest IdentityServer4 - or there is a new flag on the TokenClient to use the legacy behavior: 

https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/TokenClient.cs#L123

**Comment by guidoffm** [comment]
Worked for me. 

:-)
