### ISSUE TITLE
on the topic of Identity Server 4 pages being hosted in an iframe. 

### ISSUE THREAD

**Issue by JudeAlquiza** [IdentityServer/IdentityServer4#2140]
Hi,
    In relation to this thread, https://github.com/IdentityServer/IdentityServer3/issues/2442 does this mean that its also not secure to host any other identity server pages in an iframe for that matter.

We currently have an angular client. which has a nav bar in it but we want that same nav bar to be in one of the identity server pages. Our problem is that with that we will be having code duplication, but if we don't want to have code duplication then we'll have to put identity server pages inside of an iframe which is then a security risk. 

Just want to know your suggestion so that we'll avoid both code duplication and putting anything inside of an iframe.

Thanks!
Jude Alquiza.

**Comment by brockallen** [comment]
We don't allow many UI pages in an iframe. We want to prevent click-jacking scenarios (https://en.wikipedia.org/wiki/Clickjacking). Google's login page is the same, so we used that as precedent. Of course, you control the UI in IdentityServer, so if you want to relax those protections that's up to you and your threat modeling.

**Comment by JudeAlquiza** [comment]
@brockallen Thanks for the response, we actually ended up white listing the domain that is allowed to host our server side pages in an iframe, only where the angular client app runs where we allowed it be hosted in an iframe and not anywhere else for security reasons.
