### ISSUE TITLE
OpenID Provider Authentication Policy Extension 1.0

### ISSUE THREAD

**Issue by terrasynq** [IdentityServer/IdentityServer4#2142]
Do you have any plans to implement this?
http://openid.net/specs/openid-provider-authentication-policy-extension-1_0.txt

We have a use-case in which we'd like the SP to request that the user is verified against higher trust providers such as multi-factor authentication. This would be achieved by the SP specifying the desired flows as acr_values, and the IdP responding with both the acr and amr claims.

**Comment by brockallen** [comment]
That looks like a spec from OpenID, not OpenID Connect.

**Comment by terrasynq** [comment]
The spec is from OpenID, but it's used in OpenID Connect under the id_token spec in the values of the acr claim http://openid.net/specs/openid-connect-core-1_0.html#IDToken 

The flow I want to achieve is:
The OP publishes a list of supported mfa options (OpenID.PAPE / spec above)
RP includes acr_values with the desired validation level (zero or more policies to apply)

Issued tokens contain:
acr - Authentication Context Class that the authentication performed satisfied, which is a number 0-4
amr - Policies satisfied by the authentication request

**Comment by brockallen** [comment]
That's not something IdentityServer internally would know how to do. That's something you'd do in your login page.
