### ISSUE TITLE
Column length too big(50000) for mysql

### ISSUE THREAD

**Issue by rocketRobin** [IdentityServer/IdentityServer4#2145]
When I succeeded made migrations for identity server 4,I try to do update datebase.
But an error occurred.

```An error occurred while calling method 'BuildWebHost' on class 'Program'. Contin
uing without the application service provider. Error: Column length too big for column 'Data' (max = 21845); use BLOB or TEXT instead
```

the sql is 

```
      CREATE TABLE `PersistedGrants` (
          `Key` varchar(200) NOT NULL,
          `ClientId` varchar(200) NOT NULL,
          `CreationTime` datetime NOT NULL,
          `Data` varchar(50000) NOT NULL,
          `Expiration` datetime NULL,
          `SubjectId` varchar(200) NULL,
          `Type` varchar(50) NOT NULL,
          PRIMARY KEY (`Key`)
      );
```

The filed Data's length is 50000 !!! 
That was too long for mysql.

**Comment by brockallen** [comment]
I'd try deriving from the DbContext and override the mapping.

**Comment by rocketRobin** [comment]
But is that a good idea, and how I integrat it into AddOperationalStore? can you show me the code?

**Comment by flyznex** [comment]
I tried to set my database character set from UTF-8 to latin1,
"alter database database_name character set=latin1;"  and ours update command run very well

**Comment by brockallen** [comment]
Do we have any suggestions on this issue? I'd like to not have to do anything custom for a specific provider in the EF code. And if you have a way outside of this to change the column, I think that will be the solution. Perhaps EF migrations isn't the right tool for the job, and if that's the case it's more of a Microsoft issue (and limitation/failing).

**Comment by brockallen** [comment]
Since I've had no suggestions, I'm closing.
