### ISSUE TITLE
error after login when clicking "No, i do not allow" button

### ISSUE THREAD

**Issue by BehnamAbdy** [IdentityServer/IdentityServer4#215]
i cloned the samples and opened this solution in vs 2015 IdentityServer4.Samples/MVC and API/MVC and API.sln, then when i login with mvc project all things work, but problem occures when after login in consent view i hit the button of "No, i do not allow" i get this error:

An unhandled exception occurred while processing the request.
OpenIdConnectProtocolException: Message contains error: 'access_denied', error_description: 'ErrorDecription null', error_uri: 'ErrorUri null'.
MoveNext

AggregateException: Unhandled remote failure. (Message contains error: 'access_denied', error_description: 'ErrorDecription null', error_uri: 'ErrorUri null'.)

also things work well if i hit the "yes, allow" button
any idea what is going on though i haven't modified the original code

**Comment by brockallen** [comment]
I can look into it... might just be something incomplete in the UI sample layer./

**Comment by brockallen** [comment]
Ok, just looked into this. This is how the Microsoft OIDC middleware handles errors. This is not an IdentityServer issue. You would be expected to handle the error on the `Events` property of the OIDC middleware and have this error however you saw fit. Here is a list of common errors  you'd expect to get from OIDC/OAuth2: https://tools.ietf.org/html/rfc6749#section-4.1.2.1

**Comment by BehnamAbdy** [comment]
thanks a lot

**Comment by rodrigogalhardo** [comment]
Hi, I have some troubles with identity server 4.

An unhandled exception occurred while processing the request.

OpenIdConnectProtocolException: Message contains error: '', error_description: 'error_description is null', error_uri: 'error_uri is null'.
MoveNext

AggregateException: Unhandled remote failure. (Message contains error: '', error_description: 'error_description is null', error_uri: 'error_uri is null'.)

Please anyone know how to fix it ?
