### ISSUE TITLE
Question regarding Identityserver 4 together with Microsoft.AspNetCore.Identity

### ISSUE THREAD

**Issue by Thor-Kristian-Valderhaug** [IdentityServer/IdentityServer4#2150]
Hi

We are looking at using Identityserver 4 together with Microsoft.AspNetCore.Identity.
I see from the [AspNetIdentity example](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity)  that you have chosen to store the roles as claims with the type `JwtClaimTypes.Role`.
Why have you gone for this approach and not used the role mechanism provided by Microsoft.AspNetCore.Identity via the `RoleManager` ?

**Comment by brockallen** [comment]
Roles are just claims. RoleManager treats them as something special. If you don't need the role manager, then don't use it. The samples didn't need it.

**Comment by Thor-Kristian-Valderhaug** [comment]
Ok, thanks for the clarification.
