### ISSUE TITLE
Creating JWTs on full framework with CNG certificates

### ISSUE THREAD

**Issue by daghelge** [IdentityServer/IdentityServer4#2151]
Hi,

we've retargeted our STS from core to full framework (4.6.2) as we want to support SAML and WS-Fed. Our signing certs are using a CNG Key Storage provider, and now we get the following exception when IS4 attempts to generate a JWT.

```
CryptographicException: Invalid provider type specified.

System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, bool randomKeyContainer)
System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, bool randomKeyContainer, int dwKeySize, ref SafeProvHandle safeProvHandle, ref SafeKeyHandle safeKeyHandle)
System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
System.Security.Cryptography.RSACryptoServiceProvider..ctor(int dwKeySize, CspParameters parameters, bool useDefaultKeySize)
System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PrivateKey()
Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PrivateKeyStatus()
Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider.FoundPrivateKey(SecurityKey key)
Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, string algorithm, bool willCreateSignatures)
Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, string algorithm, bool willCreateSignatures)
Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForSigning(SecurityKey key, string algorithm)
System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedSignature(string input, SigningCredentials signingCredentials)
System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.WriteToken(SecurityToken token)
IdentityServer4.Services.DefaultTokenCreationService.CreateJwtAsync(JwtSecurityToken jwt).

```
As far as I can gather Microsoft.IdentityModel.Tokens.X509SecurityKey has been rewritten to support CNG (using RSACertificateExtensions), but it looks like it only targets .net standard 1.4. 

(some issues: 
[https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/480](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/480)
and
[https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/667](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/667)

the relevant code:
[https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs#L92](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs#L92)
)

Anyhows, this isn't directly related to IS4 of course - but somebody else must experienced the same problem? Is the only solution right now to avoid using CNG with full framework?

/dag

**Comment by leastprivilege** [comment]
tbh - I don't know.

WS-Fed and SAML would also work on .NET Core though.

**Comment by leastprivilege** [comment]
Can you repro that outside of identityserver?

**Comment by daghelge** [comment]
I'll throw something together with test certificates for CSP and CNG.

**Comment by leastprivilege** [comment]
With an isolated sample it will be easier to talk to Microsoft I guess
