### ISSUE TITLE
Serilog output to Seq is not treating details as a Json object but as a raw string 

### ISSUE THREAD

**Issue by bronumski** [IdentityServer/IdentityServer4#2153]
### Issue / Steps to reproduce the problem

Configure IdentityServer logging as per:

http://docs.identityserver.io/en/release/topics/logging.html

Adding in a Sink to Seq

https://docs.getseq.net/docs/using-serilog

The rich Json output is there but it is not treated as a Json object but a string

![image](https://user-images.githubusercontent.com/3909845/37498185-163167f6-287a-11e8-85a8-590b21ffeef5.png)

If it where treated as an object it would look like this:

![image](https://user-images.githubusercontent.com/3909845/37498287-bce9705c-287a-11e8-8f83-3e28a11ef251.png)

This means that you cannot query the properties on the Json object as per:

https://nblumhardt.com/2014/03/seq-log-query-of-the-day-2-properties/

**Comment by leastprivilege** [comment]
The current logging is not really designed to be fully structured - that's a todo.

If you need structured data, look into events.

https://identityserver4.readthedocs.io/en/release/topics/events.html

**Comment by bronumski** [comment]
Ok, thanks
