### ISSUE TITLE
ASP.NET Core Identity has now Identity UI nuget, does IdentityServer want to follow?

### ISSUE THREAD

**Issue by LisaTatum** [IdentityServer/IdentityServer4#2158]
asp.net core identity =>

https://blogs.msdn.microsoft.com/webdev/2018/03/02/aspnetcore-2-1-identity-ui/

identityserver 4 => 

copy/paste and adapt the:  https://github.com/IdentityServer/IdentityServer4.Quickstart.UI

It would be cool to have the quickstart ui as nuget too where I could e.g. configure for inmemory or db persistance.

Its a feature request ;-)

**Comment by brockallen** [comment]
you can use the dotnet CLI: https://github.com/IdentityServer/IdentityServer4.Templates

**Comment by LisaTatum** [comment]
thx man, did not know that stuff, hoped for such an answer :-)
