### ISSUE TITLE
How To Exit directly instead of jumping to the SSO exit interface

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer4#2160]
http://docs.identityserver.io/en/release/topics/signout.html
i see many document about identityserver4,but i can not find how to do it .
the Front-channel,Back-channel , session management Very complicated, do not understand meaning

I was recently learning how to use identityserver4. I used the quickstart's page templates and features. I used hybird's mixed mode. Then my client is openid middleware. If I access my client's interface that requires authorization, Will automatically jump to the identityserver4 server login screen, and then I will automatically log back to my client interface. These are all well implemented and there is no problem, but when my client exits, I use the instance code of identityserver4.

Await HttpContext.SignOutAsync("Cookies");
Await HttpContext.SignOutAsync("oidc");

It actually jumps back to the sso interface to exit. This implementation I saw the documentation of identittyserver4, probably meant to jump back, delete identityserver4 on the login cookie status of this account, and notify other clients that the account has exited. But I don't want to have such a jump to the sso exit interface operation. I think that when my client clicks on the exit, it will simply exit. Of course, I still want to be able to delete the login status of identityserver4, and hope to inform other clients that this account has already exited. Landlord do you know how to achieve it? Of course, the accesstoken I use is jwt format. I don't want to use the format of refrence token.

sorry about my english

**Comment by brockallen** [comment]
> But I don't want to have such a jump to the sso exit interface operation.

This is how it works. Check the specs: https://openid.net/connect/

**Comment by YINZHU2016** [comment]
i have see the https://openid.net/connect/,but i still do not know how to do it.
please help thanks.
I want the client to log out of the local login state, and then can tell the SSO to exit the login state in the background, and can notify its client that the account is logged out, but instead of jumping to the SSO's loginout to use the iframe to notify other clients. I want to call a SSO interface directly in my client side code, through a tool like HttpClient. To clear the login status of SSO, and then you can notify other clients that I quit.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
