### ISSUE TITLE
loading CustomTokenRequestValidator after ProfileService

### ISSUE THREAD

**Issue by wonl** [IdentityServer/IdentityServer4#2161]
### Startup.cs ###
```java
.AddClientStore<CustomClient>()
.AddProfileService<CustomProfile>()
.AddCustomTokenRequestValidator<CustomTokenRequestValidator>()
```
In runtime, CustomTokenRequestValidator loads after CustomClient and before CustomProfile. Is this order intentional? 

Is there a way to change the order so CustomProfile loads before CustomTokenRequestValidator? I need to retrieve a few claims from CustomProfile in CustomTokenRequestValidator. When I view CustomTokenRequestValidationContext, I see claims inside Client.Claims but nothing inside Subject.Claims since CustomProfile hasn't run yet.

**Comment by brockallen** [comment]
> In runtime, CustomTokenRequestValidator loads after CustomClient and before CustomProfile. Is this order intentional?

I don't understand. You should look thru the code to understand the dependency graph.

**Comment by richardlawidjaja** [comment]
@brockallen so what he meant is the CustomTokenRequestValidator is triggered before we load data for Custom Profile in this case let say if we want to append additional response that has been loaded by the custom profile it will not be available when we trigger CustomTokenRequestValidator. as i have mention it above we can append some of the response in  IResourceOwnerPasswordValidator.

**Comment by brockallen** [comment]
I guess I'm not following exactly. The ordering is the way it is. If you need to pass context from one to another, then that's beyond our design. If it's all in the same HTTP request, the consider putting info in the HttpContext.Items collection.
