### ISSUE TITLE
[Question] Authority with both hostname and IP

### ISSUE THREAD

**Issue by mhasanunal** [IdentityServer/IdentityServer4#2165]
### 1. Explanation
I have a local DNS server thus I write all my configs with hostnames ( Both Identity Server and an MVC client ).
In local network it doesn't a problem and works like a charm. 
For ex: 
id_serv --> http://sso.mysite.com **Port (80)** _expects this hostname_
client --> http;//www.mysite.com/site1 **Port (80)** _expects this hostname_

### 2. Issue
My company uses **APN** service from a mobile operator. And they use their own DNS server. Thus, my sites can not be resolved (as expected). We contact with them and they setted our DNS server as default DNS. So, for now problem resolved.

### 3. Question
Is there a way to set authority with multiple types (Both ip and hostname) and allow access with both ip and hostname?

**Comment by brockallen** [comment]
No, not with IP. TLS and PKI are involved to establish trust, so IPs won't work.
