### ISSUE TITLE
QuickStart - Windows authentication

### ISSUE THREAD

**Issue by AndrePinto-NET** [IdentityServer/IdentityServer4#2166]
I've spent some time trying to set up windows authentication, and long story short, I think there is a mistake om the quick start samples. [Here](https://github.com/IdentityServer/IdentityServer4.Samples/blob/1264aacccfd532c8b4f1e181738c4943183afc3b/Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Quickstart/Account/AccountController.cs#L417), I think the correct is 

`await HttpContext.SignInAsync(
                    IdentityConstants.ExternalScheme,
                    new ClaimsPrincipal(id),
                    props);
`

instead of 

`await HttpContext.SignInAsync(
                    IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme,
                    new ClaimsPrincipal(id),
                    props);`

It was the only way to make windows authentication work.

**Comment by brockallen** [comment]
Yes, I think you're right. Want to send a PR to fix? Thanks.

**Comment by brockallen** [comment]
BTW, this is fixed on our dev branch already.
