### ISSUE TITLE
Secrets with `plus` symbol in secret aren't parsed well

### ISSUE THREAD

**Issue by Sebosek** [IdentityServer/IdentityServer4#2167]
Symbols `+` (plus) are replaced by space (or any whitespace) which is a bug or breaking change in API.
Here is [a link to a reproducible solution on GitHub](https://github.com/Sebosek/ids4-2.1.2-parse-bug).
A bug occurs between version >2.0.6 and <=2.1.2.

### Issue / Steps to reproduce the problem
Here is a sample CURL
```
curl -X POST \
  http://localhost:63744/connect/token \
  -H 'accept: application/json' \
  -H 'authorization: Basic Y2xpZW50OjErMQ==' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d 'grant_type=client_credentials&scope=api'
```

Which contains client `client` with secret `1+1`.
In the sample application, there is `CustomSecretValidator` which logs income parsed secret and as you can see it log parsed value contains `1 1` instead of `1+1`.

```
[Information] IdentityServer4.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token

[Debug] IdentityServer4.Endpoints.TokenEndpoint
Start token request.

[Debug] IdentityServer4.Validation.ClientSecretValidator
Start client validation

[Debug] IdentityServer4.Validation.BasicAuthenticationSecretParser
Start parsing Basic Authentication secret

[Debug] IdentityServer4.Validation.SecretParser
Parser found secret: BasicAuthenticationSecretParser

[Debug] IdentityServer4.Validation.SecretParser
Secret id found: client

[Debug] IdS4.CustomSecretValidator
Parsed secret: 1 1

[Debug] IdentityServer4.Validation.HashedSharedSecretValidator
No matching hashed secret found.

[Debug] IdentityServer4.Validation.SecretValidator
Secret validators could not validate secret

[Error] IdentityServer4.Validation.ClientSecretValidator
Client secret validation failed for client: client.
```

If you need more detail let me know.
Thank you and have a nice day.

Sebastian

**Comment by leastprivilege** [comment]
This has been discussed a couple of times - OAuth does not use HTTP Basic Authentication - but a variant of it (IOW curl does the wrong encoding)

https://tools.ietf.org/html/rfc6749#section-2.3.1

**Comment by Sebosek** [comment]
Oh, thanks for the reply. So, basically, it means that I should `client:1+1` encode by parts with form-encoding and than to base64. 
I guess this could be closed then...
