### ISSUE TITLE
External Authentication - AspNET Identity 

### ISSUE THREAD

**Issue by ChristianRiedl** [IdentityServer/IdentityServer4#217]
In the upcoming idsrv4 docs I have seen a chapter "External Identity Provider". So I am optimistic that this functionality is planned in future releases. I tried with beta5 and was able to successfully login my  SPA via idsrv4 and Azure AD but redirection back to  SPA did not work. 
The redirect url must be looped through and also the providers must be managed somehow.  

My _ProfileService_ and _LoginService_ is based on AspNet Identity (like idsrv3.AspNetIdentity).
Is AspNet Identity integration planned for idsrv4 ?  Is it a good idea to go in this direction ?

An OIDC provider requires some kind of user and right management AspNet Identity or MemberShipReboot deliveres this functionality more or less but does not fit 100 % to idsrv4.    
 
@leastprivilege , I admit that I misuse the "Issues" to get answer for some questions which are very important for me. But I see no other possibility to get such "roadmap" info. Probably other people who are porting from idsrv3 to idsrv4 are interested to.

**Comment by leastprivilege** [comment]
check our host and samples - it is all in there already. Just not documented yet.

**Comment by ChristianRiedl** [comment]
I of course tried host and MvcImplicit sample. The behavior is the same. Login successfully via Google, user created but not redirected to MvcImplicit. (LoginController.ExternalCallback).
LoginController.cs :
```
public async Task<IActionResult> ExternalCallback(string returnUrl)
{
    ...
    if (returnUrl != null)
    {
        // todo: signin
        //return new SignInResult(signInId);
    }
    return Redirect("~/");
}
```

**Comment by brockallen** [comment]
This has been fixed.

**Comment by cwharris** [comment]
I'm afraid I've been searching for a solution to this problem all evening, and this issue is as far as I've come to finding a solution. Could you be more specific about the fix, or reference a pull request?

**Comment by cwharris** [comment]
Opened https://github.com/IdentityServer/IdentityServer4.Samples/pull/49 to address this issue. Furter discussion should probably be directed to the `IdentityServer4.Samples` repository.
