### ISSUE TITLE
Client identity proof and automatic authorization request processing

### ISSUE THREAD

**Issue by tamas-kozma** [IdentityServer/IdentityServer4#2170]
A native (_public_) client uses the _code flow_ to authenticate the user and get consent, using a local loopback response URL. The user clicks remember me and remember consent check boxes. Next time the client makes an authorization request, it will be granted without user interaction. But what if next time it is a rogue app that uses the same client ID, and thus gets an _access_token_ for free.

[OAuth 2.0 for Native Apps](https://tools.ietf.org/html/draft-ietf-oauth-native-apps-12#section-8.6) says: 
> "[...] the authorization server SHOULD NOT process authorization requests automatically without user consent or interaction, except when the identity of the client can be assured. [...] Measures such as claimed HTTPS redirects MAY be accepted by authorization servers as identity proof [...]"

After testing, looking through the source code and googling, I haven't found that IdentityServer4 would support the notion of proven client identity in this context, and it seems to me that the above described vulnerability applies.

I'm a newbie when it comes to security, so it might very well be possible that I'm overlooking something obvious, in which case I'm sorry to have bothered you. Otherwise, maybe it should be possible to mark some response URLs as safe in the client configuration, and only when such a safe URL is used would the login and/or consent pages be skipped?

**Comment by leastprivilege** [comment]
Well - if you want that behavior - don't allow saving consent.

**Comment by tamas-kozma** [comment]
But that will force my legit app to always show the consent page as well.

**Comment by leastprivilege** [comment]
Sure - there is no way to distinguish between "legit" apps - and spoofed ones.

A native app would typically use refresh tokens to keep the "session" alive - so no need to go back to the authorize endpoint.

**Comment by TomCJones** [comment]
This is a severe problem with apps on a user's device. OpenID is trying to address the issue with FAPI http://openid.net/wg/fapi/
But I am afraid that even it does not go far enough. As the current Facebook imbroglio shows, it is hard for a user to understand which apps are trustworthy, let alone some random web site.

**Comment by TomCJones** [comment]
Proof of possession is another avenue you could explore https://datatracker.ietf.org/doc/rfc7800/

**Comment by brockallen** [comment]
All set on this issue -- can we close?
