### ISSUE TITLE
PublicOrigin with the value empty string results in invalid Issuer

### ISSUE THREAD

**Issue by jklawrence** [IdentityServer/IdentityServer4#2173]
### Issue / Steps to reproduce the problem
- Set `IdentityServerOptions.PublicOrigin` to `string.Empty`.
- `IdentityServerApplicationBuilderExtensions.ValidateOptions(...)` does not log the fact that the PublicOrigin has been overwritten, because the IsPresent() extension method checks for !string.IsNullOrEmpty
```
if (options.PublicOrigin.IsPresent()) logger.LogDebug("PublicOrigin explicitly set to {0}", options.PublicOrigin);
```
- The `BaseUrlMiddleware` uses the null-coalescing operator to set the IdentityServerOrigin value, so it does get set to the empty string:
```
var origin = _options.PublicOrigin ?? request.Scheme + "://" + request.Host.Value;
context.SetIdentityServerOrigin(origin);
```

Impact:
You end up with relative urls in your discovery document:
`"jwks_uri":"/.well-known/openid-configuration/jwks","authorization_endpoint":"/connect/authorize",...`

I'm not sure if more is impacted by this - I haven't taken a close look.

I would open a PR [changing the BaseUrlMiddleware to also check `PublicOrigin.IsPresent()`](https://github.com/jklawrence/IdentityServer4/commit/a8a7b38c12a8c13da1e4976810ad52b247a473b7), but that's potentially a breaking change if anyone is depending on relative urls in their discovery document. If that is valid, then I believe the logging should be changed to log the fact that the PublicOrigin is explicitly being set to the empty string.

**Comment by brockallen** [comment]
I pushed a fix to prevent empty config values for PublicOrigin. Have a look, please.
