### ISSUE TITLE
Two times localhost uri's as redirecturi gives errors

### ISSUE THREAD

**Issue by GeertVL** [IdentityServer/IdentityServer4#2174]
### Steps to reproduce

When you add a client as follow:

```json
  "Clients": [
    {
      "ClientId": "my.client",
      "ClientName": "my.client",
      "RedirectUris": [
        "http://localhost:4200", 
        "http://localhost:49155"
      ],
      "AllowedCorsOrigins": [
        "http://localhost:4200",
        "http://localhost:49155"
        ...
```

### Relevant parts of the log file

```
Bearer token not found
```

Is it allowed to have localhost twice in your client definition or do I have to do it differently.

It is needed to use with Angular once to run it locally and twice to run the end to end tests.
Both use a different port.

**Comment by brockallen** [comment]
There's not enough info here.

**Comment by GeertVL** [comment]
First question here. What more info do you need?

**Comment by brockallen** [comment]
For some reason on the user info endpoint, the access token being sent by the client is not being found by IdentityServer -- that's what it sounds like. Can you check the network trace on the call to useinfo to verify the presence of the access token?

**Comment by brockallen** [comment]
redirect uris are matched exactly, so if the port is configured then it needs to be in there.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
