### ISSUE TITLE
OpenId2 Provider

### ISSUE THREAD

**Issue by FreePhil** [IdentityServer/IdentityServer4#2175]
Fail to add existing **OpenId2** provider to IdentityServer 4.  Should I customize the authentication builder for **OpenId2**?

**Comment by leastprivilege** [comment]
You would need an ASP.NET Core OpenID authentication handler. This is independent of IdentityServer.

**Comment by FreePhil** [comment]
Wondering if there is any open source I can reference?

**Comment by brockallen** [comment]
Perhaps here: https://github.com/aspnet-contrib/.
