### ISSUE TITLE
Define the settings for multiple single sign on

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer4#2178]
hello  
I have 6 web app, namely A, B, C, D, E and F I have used idrv4 SSO for their login, I have deployed a idrv4 server, but I have a special scenario. I hope it is single sign on A, B, C. Then D, E,F are single sign on another. But the situation is that they are all connected to the one idrv4 SSO, so now they are just logged together. What are the objects I can set to client in idrv4 to implement the scene I said above? I have found a lot of information without a relevant introduction. Is the final solution is that I deploy 2 SSO sites S1, S2, and then let A, B, C connect S1, and D, E,F connect S2? Because in fact my logon code is the same as the logon database, I just want to separate into 2 single - point logon clusters.

thanks

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
