### ISSUE TITLE
After sign in i want take email address,

### ISSUE THREAD

**Issue by galgodage** [IdentityServer/IdentityServer4#2179]
Hi,
I have MVC application. i use identityserver4 for google and azure AD sign in. After sign in i want take login email address to my mvc application. How can i take it

lakmal

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
