### ISSUE TITLE
missing IClientStore sample

### ISSUE THREAD

**Issue by BehnamAbdy** [IdentityServer/IdentityServer4#218]
unfortunately the api missing a vivid sample for importing clients and users from thirdparty repositories like sqldb or..
i trying to implement the identityserver to work with my custom client and user repository instead of inmemory but i get this error when tying to enter the login page from client
Unable to obtain configuration from: 'http://localhost:5000/.well-known/openid-configuration

**Comment by leastprivilege** [comment]
very similar to 

https://github.com/IdentityServer/IdentityServer3.EntityFramework/blob/master/Source/Core.EntityFramework/Stores/ClientStore.cs
