### ISSUE TITLE
.net core 2 Sample

### ISSUE THREAD

**Issue by pizzadev** [IdentityServer/IdentityServer4#2181]
So, Is it possible to have SAML2 with .net core 2 and identityserver4? Documentation says that it is possible, also there is a link to the sample, BUT!!! Sample Project was built with .net framework 4.6.1 (you can open properties of the project and see the version of .net). SamlPlugin seems to be  NOT COMPATIBLE with .net core 2....

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
