### ISSUE TITLE
Use AD authentication at default Identity Server form

### ISSUE THREAD

**Issue by raphaeldiasrj** [IdentityServer/IdentityServer4#2183]
Hi!

I need to authenticate a user by Windows Authentication in **Asp.net Core**, but I don't want to open the default browser login window for aesthetic needs. So, I want to do the same thing of the default browser login window, but in Identity Server login form (Views / Account / Login.cshtml).

Does anyone have an idea?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
