### ISSUE TITLE
IdentityServer4.Samples won't build in VS2015.

### ISSUE THREAD

**Issue by jdege** [IdentityServer/IdentityServer4#2184]
I've been trying to build the sample projects from IdentityServer4.Samples, and the solutions won't load.

### Issue / Steps to reproduce the problem

- Clone [https://github.com/IdentityServer/IdentityServer4.Samples.git](https://github.com/IdentityServer/IdentityServer4.Samples.git)

- In Windows Explorer, navigate to \IdentityServer4.Samples\Quickstarts\3_ImplicitFlowAuthentication

- Double-click on Quickstart3_ImplicitFlowAuthentication.sln

Visual Studio loads, but all of the projects are flagged with (load failed).

- Right-click on one of the projects, and select "Reload project" from the context menu.

An error message appears:

> QuickstartIdentityServer.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format. 

- Edit the project file. Change '<Project Sdk="Microsoft.NET.Sdk.Web">' to "<Project Sdk="Microsoft.NET.Sdk.Web" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">", and save.

- Try to reload the project again.

A new error appears:

> QuickstartIdentityServer.csproj : error  : The attribute "Version" in element <PackageReference> is unrecognized.

I'm at a loss as to how to even start with this.

If this can't be compiled with VS2015, you should update MinimumVisualStudioVersion in the .sln.

**Comment by vdecristofaro** [comment]
https://stackoverflow.com/a/42337225/431537

**Comment by brockallen** [comment]
ASP.NET Core 2 is only supported by Microsoft in VS2017.

**Comment by jdege** [comment]
As I said, if the solution won't work in VS2015, it shouldn't load in VS2015.

MinimumVisualStudioVersion should be correct.
