### ISSUE TITLE
LicenseKey & Licensee

### ISSUE THREAD

**Issue by pizzadev** [IdentityServer/IdentityServer4#2185]
Hello, where can I get LicenseKey and Licensee ?
 .AddSamlPlugin(options =>
            {
                options.Licensee = "";
                options.LicenseKey = "";
            })

Is that a key from x.509 cert that I can generate (selfsigned cert)  ?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
