### ISSUE TITLE
IdentityServer4.Models as nuget package

### ISSUE THREAD

**Issue by anktsrkr** [IdentityServer/IdentityServer4#2189]
It would be great if we could have IdentityServer4.Models as a different nuget package.

#### Why?
It may possible that, you are implementing real project and want to separate repositories in different class library.
 #### You can do it still where is the problem? 

Well, Yes! we can do it , but the problem is either you need to reference whole IdentityServer4 or need to create whole set of  new models! 

Now to keep clean class library can we have  IdentityServer4.Models as a different nuget package?

**Comment by leastprivilege** [comment]
Thanks. We'll consider it for a future release.

**Comment by anktsrkr** [comment]
Okay. Thanks @leastprivilege. Please let me know if I can contribute also.

**Comment by leastprivilege** [comment]
current plan is to put that in 2.3

**Comment by anktsrkr** [comment]
@leastprivilege  perfect! 

Thank you.

**Comment by OculiViridi** [comment]
@leastprivilege Was it finally realeased the new `IdentityServer4.Models` package with the v2.3.0? I can't find it on NuGet.

**Comment by scottbrady91** [comment]
https://www.nuget.org/packages/IdentityServer4.Storage

**Comment by cdie** [comment]
@leastprivilege Why does 3.0.0-preview3.4 depends on netcoreapp3.0 instead of netstandard2.0 (or event netstandard 2.1) ?
I'my trying to create a shared data model for Mongo and IdentityServer4.Models are part of some collections, will I be stuck in 2.5 ?

**Comment by leastprivilege** [comment]
We fixed this - but it is not yet published on nuget.
