### ISSUE TITLE
Refactor config API

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#219]
* split in Core & optional services
* consider IOptions

**Comment by leastprivilege** [comment]
related: https://github.com/IdentityServer/IdentityServer4/issues/3

**Comment by leastprivilege** [comment]
* interfaces vs no interfaces
* Add vs TryAdd
* core validators vs pluggable validators
* InMemory -> quickstart?

**Comment by brockallen** [comment]
done
