### ISSUE TITLE
null value over CustomResponse -

### ISSUE THREAD

**Issue by richardlawidjaja** [IdentityServer/IdentityServer4#2190]
Hi Brock and Dominick.
Could you please let me know, is there any reason on why i can't really pass a null value over a custom response?

`context.Result.CustomResponse = new Dictionary<string, object>{
                        {"customerId", (user.ManagerId=="0"||user.CustomerId==null)?null:user.CustomerId},
                        {"managerId", (user.ManagerId=="0"||user.ManagerId==null)?null:user.ManagerId},
                        {"userId", string.IsNullOrEmpty(user.SubjectId)?null:user.SubjectId },
                        {"memberId",  string.IsNullOrEmpty(user.MemberId)?null:user.MemberId}
}`

This will throws object is not set to reference
I am in a middle of java to .net migration and the java microservices require null value to be passed as a custom response

is there any work around for this issue? it works well with a string values thou but the java microservices complain about "null" because its not null

**Comment by brockallen** [comment]
I'm missing the context of this question. Can you elaborate?

**Comment by richardlawidjaja** [comment]
when creating a custom response, you will require to assign a new Dictionary<string, object> as the custom response. in this dictionary can we add a null as a value?
in short something like this

context.Result.CustomResponse = new Dictionary<string, object>{ {"customerId", null}}

because when i try to do this, it will throw null reference exception, is there any workaround to handle this?

**Comment by brockallen** [comment]
> when creating a custom response

when? during the token request/response processing, i'm guessing?

**Comment by richardlawidjaja** [comment]
correct, it happen during the token response. my best guess for this issue probably it happen because of the Dictionary<string,object> did not accept null value.

**Comment by richardlawidjaja** [comment]
probably to solve this issue you might want to change the Dictionary to a nullable dictionary?

**Comment by leastprivilege** [comment]
Give it a try including test coverage. If it works, this can be the basis for a PR.

**Comment by leastprivilege** [comment]
did you try it?

**Comment by richardlawidjaja** [comment]
Hi Dom, Sorry I as busy over my project, I will try it over the week end i will let you know

**Comment by richardlawidjaja** [comment]
Hi Domminick and Brock I have tested my proposed solution however I dont think we can change it to nullable dictionary as it does not supported in C#, you can assign a null value on TValue but not the dictionary itself as for this moment for my project we have solved it internally by using string empty instead of null.

**Comment by leastprivilege** [comment]
OK - good.
