### ISSUE TITLE
Cache the most recurring sql query result at application level in IdentityServer  ??

### ISSUE THREAD

**Issue by agrebenyuk** [IdentityServer/IdentityServer4#2191]
Hi there ,

I was looking at the configuration  db insight and found that one of the most re-issued sql query from Identity server is as follows . 
`SELECT [i].[Id], [i].[IdentityResourceId], [i].[Type]
FROM [IdentityClaims] AS [i]
WHERE EXISTS (
    SELECT 1
    FROM [IdentityResources] AS [identityResource]
    WHERE [identityResource].[Name] IN (N'openid', N'profile', N'email', N'mycompanyRoles') AND ([i].[IdentityResourceId] = [identityResource].[Id]))
ORDER BY [i].[IdentityResourceId]`

And the output seems to be quite static as long as we don't add/remove/change items in those 2 tables. 

Is there a way to cache the output of that query at the application level ? Would it be appropriate ? or if my thinking is not quite right please let me know why.

Version used : 1.5.3

Cheers,
Andrey

P.S. I added code as bellow , hopefully it will do what I need , but not 100% sure as IdentityClaims is not seem to be part of those caches.
`AddInMemoryCaching()
                  .AddClientStoreCache<IdentityServer4.EntityFramework.Stores.ClientStore>()
                  .AddConfigurationStoreCache()
                  .AddResourceStoreCache<IdentityServer4.EntityFramework.Stores.ResourceStore>();`

**Comment by brockallen** [comment]
`AddClientStoreCache` and `AddResourceStoreCache` are the easy ways to add caching for those tables. And you can configure the cache itself: http://docs.identityserver.io/en/release/topics/startup.html?highlight=AddClientStoreCache#caching

**Comment by alexsandro-xpt** [comment]
@agrebenyuk Is this working for you?

**Comment by agrebenyuk** [comment]
hi @alexsandro-xpt  , `AddClientStoreCache` and `AddResourceStoreCache`  extensions helped

**Comment by alexsandro-xpt** [comment]
@agrebenyuk I just do it:

```
                .AddInMemoryCaching()
                .AddClientStoreCache<IdentityServer4.EntityFramework.Stores.ClientStore>()
                .AddConfigurationStoreCache()
                .AddResourceStoreCache<IdentityServer4.EntityFramework.Stores.ResourceStore>()
```

But don't work, same delay time, I don't know why.

**Comment by agrebenyuk** [comment]
First you need to watch sql queries in sql profiler before and after using those methods. Maybe delay is at some different place

**Comment by alexsandro-xpt** [comment]
I do it, I saw the delay occur when OIDC JS client calls `/connect/authorize` API

**Comment by agrebenyuk** [comment]
Try to monitor what sql queries are when this api method is called. Try twice , and then compare results. The second call should have less sql queries. I would also check how many rows are in the tokens table , in earlier versions of IdentityServer they were not auto delectable after tokens expire , And if all sql queries number is  at minimum level , check their execution plans, you might need to introduce an index, or maybe remove some index if one has Ben introduced mistakenly .Sorry, I’ve moved on to a different project since then and probably not the best person with details now. Cheers

**Comment by Workshop2** [comment]
Updated link for the broken readme post: http://docs.identityserver.io/en/latest/topics/startup.html?highlight=startup#caching
@brockallen
