### ISSUE TITLE
Add docs for UseIdentityServerEfTokenCleanup

### ISSUE THREAD

**Issue by agrebenyuk** [IdentityServer/IdentityServer4#2192]
Could not find any documentation on this extensions method. 

`public static IApplicationBuilder UseIdentityServerEfTokenCleanup(this IApplicationBuilder app, IApplicationLifetime applicationLifetime);`

What does it actually do if I add it as bellow 

`            app.UseIdentityServer();
            app.UseIdentityServerEfTokenCleanup(appLifetime);
`

Version used : 1.5.3

**Comment by brockallen** [comment]
I guess not. It would be here: http://docs.identityserver.io/en/release/reference/ef.html

I'll leave this open as a docs issue.

**Comment by Mardoxx** [comment]
>What does it actually do if I add it as bellow

Registers TokenCleanup.Start and .Stop to the respective starting and stopping callbacks of the given app lifetime. I.e. starts up the cleanup schedule on app startup and stops it when it's shutting down.
