### ISSUE TITLE
AddOpenIdConnect() Issue

### ISSUE THREAD

**Issue by nishani** [IdentityServer/IdentityServer4#2193]
Hi 
I have an identity server (version 4) hosted in a remote iis. I am trying to connect to it from locally hosted api (netcore 2).  Always it gives me invalid redirect_uri error.

Log
2018-04-03 10:06:16.375 +05:30 [ERR] Invalid redirect_uri: http://localhost:5002/signin-oidc
{
  "ClientId": "app",
  "ClientName": "app",
  "AllowedRedirectUris": [
    "https://app.com/"
  ],
  "SubjectId": "anonymous",
  "RequestedScopes": "",
  "Raw": {
    "client_id": "app",
    "redirect_uri": "http://localhost:5002/signin-oidc",
    "response_type": "id_token",
    "scope": "openid profile",
    "response_mode": "form_post",
    "nonce": "636583269955688023.YjFjZDFjZTAtYmRjNC00Y2ZiLWJlOGItN2E4Yzg0NjFkMzc3ZTBhZTZkMDItNGNiOC00M2M2LTgwZjgtZjNlYTg4NTJjNWFh",
    "state": "CfDJ8NDwe1C6S5tNmGt4vTCtYEGNnq3mqDk5W4OvI9WIZZMP6LF-5ePpQDSbq1BDlIPOY5zsw3g09b3x2SqcGz1OIVPxWcUPTX752GRJQcS2opcl1ijG87iCfzBZKPhrB7UnUNH-GGeuxtFx0EqqOQhwYo7gpEuPtC0HuigLvQbEXSv2pmG-O2uHnRg8CiraizcxPrgYFCQDSs9g8tTF_38gbeyweXfz_pkK5MKt-fj3qEUFhdERMdtstr-qG7IrMH87YAeaRM6w4kvjz5UvGA_LHaYIHS5HQSeov_V06wGi96C9RVdaplG33JsHe6t6XCcyxhxCdYD1kde4KRJOJqtVsdM",
    "x-client-SKU": "ID_NET",
    "x-client-ver": "2.1.4.0"
  }
}

Please help me out to identify why this redirect_uri is assigned to localhost.
Is there any way to define redirect_uri in servece.AddOpenIdConnect() ?

Thanks 
Nishani

**Comment by brockallen** [comment]
You need to configure your reverse proxy and ASP.NET Core hosting properly. As such, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
