### ISSUE TITLE
Can't Open Combined_AspNetIdentity_and_EntityFrameworkStorage Sample Project in Visual Studio

### ISSUE THREAD

**Issue by ZahFox** [IdentityServer/IdentityServer4#2196]
This issue is in reference to the IdentityServer4. Samples repository. As was expected, I originally had an issue cloning this repo, but that was an issue easily resolved due to the README stating that I would need to set a global config option for Git. However, there is an issue that I can't seem to find any way to resolve. When I actually open the Combined_AspNetIdentity_and_EntityFrameworkStorage solution, I receive  the following error.
<img width="207" alt="issue040318" src="https://user-images.githubusercontent.com/23032758/38280493-35735e3a-376b-11e8-8475-e97d7366f2e2.PNG">

Due to this error, (i.e. the file names being too long) Visual Studio fails to load the one project I wanted to use IdentityServerWithAspIdAndEF... Could you please show me a workaround for this using Visual Studio or give the files/folders causing this more concise names please. I find the documentation to be lacking in helping me understand how to actually link ASP Identity, its Roles, and its User Claims into the way Identity Server handles adding that information to the client tokens. I figured running this project and observing the behavior would be a lot more helpful than just reading the code.

### Issue / Steps to reproduce the problem
Clone the repo and try to open the Combined_AspNetIdentity_and_EntityFrameworkStorage solution

**Comment by brockallen** [comment]
If you clone into a directory not so deep in the windows hierarchy then you won't have this problem. It's a IS problem/limitation.

**Comment by ZahFox** [comment]
@brockallen OK, for now I guess that will have to do, but I hope you consider addressing this eventually.
