### ISSUE TITLE
Federated Signout and nested iframes not obeying SET Cookie calls

### ISSUE THREAD

**Issue by davdev82** [IdentityServer/IdentityServer4#2201]
Hello Guys

We are using IdServer4 with IdServer3 as its upstream IDP. I am trying to implement Single Sign Out across both IdServers. When the user who is logged into IdServer3 signs out, we get nested iframes rendered that ultimately call frontchannel logout URIs for clients logged into IdServer4 and IdServer3. 

However, the frontchannel logout URI for the deepest client does not clear its cookie because of the nested iframes within iframes. It executes the SignOut("Cookie") call and I can see in Fiddler that there is a SET Cookie call as below

```
Set-Cookie: .AspNetCore.TournamentCookies=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax
Set-Cookie: .AspNetCore.TournamentCookiesC1=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax
Set-Cookie: .AspNetCore.TournamentCookiesC2=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax
X-Content-Type-Options: nosniff
```
However browser seems to be ignoring these calls for Set Cookie and a subsequent request to an authenticated page goes through. Is there any setting or best practice that needs to be followed inorder to ensure that a Federated SignOut works with IdServer especially when the calls to SET COOKIE are executed in the context of Iframe within Iframe within Iframe within Iframe within IFrame. Precisely 5 nested IFrame calls.

The issue is true in IE 11, Chrome Version 65.0.3325.181

**Comment by brockallen** [comment]
I suspect it's the IE Zone issue. That's a browser "feature", which OIDC does not address since "IE Zones" are not something in the HTTP/HTML specs.

**Comment by davdev82** [comment]
Hi Brock

I can confirm that it is not working with Chrome, IE and Firefox. 

It does work in scenario where the level of nesting is not deep i.e. 
- when signing out from an IdServer4 client causing all the IdServer4 clients to be signed out as well as upstream IdServer3 clients as the flow in that scenario causes a redirect to IdServer4 which then issues front channel logout calls

However, when signing out from IdServer3 client does not sign out all downstream IdServer4 clients as the amount of iframe nesting is as follows

IdServer3 EndSession Callback ---> Renders IdServer4 Frontchannel Logout ---> Renders IdServer4 EndSessionCallback URL ---> Renders IdServer4 Clients Front Channel Logout

Any help will be great

**Comment by brockallen** [comment]
Then perhaps you have same-site cookies configured in your STS. Change them to none or lax instead: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/ConfigureInternalCookieOptions.cs#L28

**Comment by davdev82** [comment]
The only place it is configured as lax is on the Client Application. IdServer4 STS and the upstream IdServer3 STS do not output any same site attribute when doing Set Cookie

**Comment by brockallen** [comment]
Did you ever make any progress on this? I, myself, never found time to try to repro.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
