### ISSUE TITLE
PersistedGrants  Key column as clustered index

### ISSUE THREAD

**Issue by agrebenyuk** [IdentityServer/IdentityServer4#2202]
Hi guys ,

This is more a question in terms of data storage design approach that you chose.
IdentityServer 1.5.3

In the PersistedGrants table the Clustered index is on Key column (nvarchar(200)) with FillFactor 0 (100%) .
I guess the question is why that was your decision , given that the Keys(tokens) them-self are random strings , and it sounds like this kind of data can bring more page splits during inserts. And I can see the INSERT is very common operation to happen here. 

Or it was supposed to be that data pages will very often have enough space for new row due to that randomness of the keys .. 

Cheers,
Andrey

**Comment by brockallen** [comment]
I suppose we could have gone with an int PK, but then we'd need a unique index on the Key value, as that's almost the only thing ever used to query that record. Would that be a better approach?

**Comment by agrebenyuk** [comment]
Theoretically yes, that would be non-clustered index on the "Key" column  and  in that case during the page split (which would still happen on insert  but less frequently because of lesser size) only 'Key' data would be written to a new page with the pointer to int clustered key  and therefore rest of the row data (which is by it's nature a bit of read overhead but not significant given read operation returns 1 row only). 

Currently, with the clustered index page split, the full row's data together with Key column data is copied to newly created page. Given that during page split the half of all data is copied over to new page it seems to be higher I/O . And this happens  more frequently then it would with non-clustered index.

But this is theoretically , I haven't tried that.. and please correct me if I'm wrong here because I am not DBA actually , but given that this is "heavy inserted" table this is probably something to test.

Cheers,
Andrey

**Comment by agrebenyuk** [comment]
Oh, why I actually raised that, we have set up weekly index rebuild , and I noticed that after the index rebuild I have kind of high I/o . I presume that after rebuild the whole table data is perfectly ordered and pretty every INSERT after rebuild would be the cause of another page split until it is fragmented enough again

**Comment by scottbrady91** [comment]
On the implementation side of things, the EF APIs for clustered indexes are database provider specific which might make this kind of change a bit awkward.

**Comment by agrebenyuk** [comment]
Thanks @scottbrady91 , I thought this is something abstracted like this 
`modelBuilder.Entity<ClassOne>() 
            .Property(t => t.ColumnOne) 
            .HasColumnAnnotation( 
                     "Index",  
                     new IndexAnnotation(new IndexAttribute("IX_ColumnOneTwo") { IsClustered = true }));
`
Anyway, I guess at this stage I just wanted to see if it is actually seen as an issue for anyone else. With my current PersistedGrants table size ~2Gb I can feel it sometimes..

**Comment by brockallen** [comment]
@agrebenyuk are those all active tokens? there is an expiration column, IIRC, so you could cleanup expired records

**Comment by agrebenyuk** [comment]
Hi @brockallen , no they are not , and I have currently regular clean-up process already set-up, and I agree ,- with the number of active tokens only , the INSERT issue is not tangible enough. Still worth considering for huge amount of tokens (I hope your system is used for someone with >=0.5M users :) ) . I guess my question is solved . Thanks guys!
