### ISSUE TITLE
[Question] App password support

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#2203]
I have been digging around in the documentation looking for something like [App password ](https://support.google.com/accounts/answer/185833?hl=en) in Identity server 4.   

Is this supported?   If not are there any plans to support it?

**Comment by LindaLawton** [comment]
Actually its for use with logging in with a users login and password with two factor enabled.

I use Git command line and have 2fa enabled on my github account.   In order to commit to Github from my pc i have to install this password key.  You cant login with a password and the 2fa key via command line.

IMO API keys are mostly used for accessing [public data](http://www.daimto.com/google-developer-console-create-public-api-key/) there is no user associated with who is accessing the data.   I would love to get Oauth2[ service account delegation](http://www.daimto.com/google-developer-console-service-account/) working if you have a tutorial for that one as well.

**Comment by leastprivilege** [comment]
The OAuth approach would be a PAT (personal access token) - github does this, VSTS also.

IOW - you pre-generate an JWT access token with some lifetime. Could be easily done in IS

https://identityserver4.readthedocs.io/en/release/topics/tools.html

**Comment by LindaLawton** [comment]
you pre-generate an JWT access token with some lifetime.  <--- thats what we are doing now and i hate this option.

**Comment by leastprivilege** [comment]
> Is this a pre genreated jwt?

Not sure if it is a JWT - but yes - a pre-gen'd token

> I just need some verification that IDs4 does not support this 

I don't even know what that means. How would IS need to support that?

**Comment by brockallen** [comment]
All set on this issue?

**Comment by leastprivilege** [comment]
The account controller is YOUR code. You can do whatever you want.

**Comment by leastprivilege** [comment]
And no - we don't have a sample. Everything on the account controller is custom to your scenario. All you do is tell us the authentication outcome by setting the cookie.
