### ISSUE TITLE
Additional claims in GrantValidatonResult not being passed to the JWT token

### ISSUE THREAD

**Issue by rafaelvascc** [IdentityServer/IdentityServer4#2207]
### Issue / Steps to reproduce the problem

1. Created a custom grant validator adding custom Claim in the results
```
public class TestGrant : IExtensionGrantValidator
    {
        public string GrantType => "custom_grant";

        public async Task ValidateAsync(ExtensionGrantValidationContext context)
        {
            context.Result = new GrantValidationResult("1", "custom_grant", DateTime.UtcNow, 
                new List<Claim> { new Claim("custom", "value") });
            return;
        }
    }
```
2.  Registered on startup
```
services.AddIdentityServer()
                .AddExtensionGrantValidator<TestGrant.TestGrant>()
```
3. Created identity resource for testing

![image](https://user-images.githubusercontent.com/2701532/38384042-c661ce98-3916-11e8-9d9a-f5e0f849d914.png)

4. Created client with access to this resource and using the custom grant type

![image](https://user-images.githubusercontent.com/2701532/38384239-47b27c7c-3917-11e8-86d8-691e683bf670.png)

5. Requested access token

![image](https://user-images.githubusercontent.com/2701532/38384392-b670cd94-3917-11e8-90c5-ad52255e9421.png)

6. Custom claim added int the TestGrant validator not present in the JWT token
![image](https://user-images.githubusercontent.com/2701532/38384500-fb1c9c2a-3917-11e8-9e0c-6287a792a3b8.png)

### Possible Solution

Folowing lines of code added to the method _GetAccessTokenClaimsAsync_ of class DefaultClaimsService 

```
                await Profile.GetProfileDataAsync(context);

                var claims = FilterProtocolClaims(context.IssuedClaims);

                var customClaimsFromUser = subject.Claims.Where(c => !outputClaims.Select(oc => oc.Type).Contains(c.Type) &&
                (resources.IdentityResources.SelectMany(i => i.UserClaims).Contains(c.Type) || resources.ApiResources.SelectMany(i => i.UserClaims).Contains(c.Type)));

                outputClaims.AddRange(customClaimsFromUser);

                if (claims != null)
                {
                    outputClaims.AddRange(claims);
                }
```
JWT Token now contains the custom claim

![image](https://user-images.githubusercontent.com/2701532/38384786-b93e773c-3918-11e8-9989-cb35bead453d.png)

Is this really a bug?
If so, is my proposed solution correct?
Thanks!

**Comment by leastprivilege** [comment]
The claims you add in the extension grant don't go into the token automatically.

You need to pick them up in your profile service `GetProfileDataAsync` and add them to token.

**Comment by rafaelvascc** [comment]
Could you please point me to an example?
Thanks.

**Comment by rafaelvascc** [comment]
Also, does make sense to include an additional parameter in the GrantValidationResult that enables the claims to be auto added to the token?

**Comment by leastprivilege** [comment]
The `ProfileDataRequestContext` in the `GetProfileDataAsync` method has a subject property. This has all the claims from the extension grant validator.

**Comment by rafaelvascc** [comment]
Sorry, but i still don't understand what to do with this method.
The only thing i did was the creation of the custom grant validator, then i let the rest of the pipeline take care of the rest automatically.
Should i implement something else to be handled after the grant validator?
Thanks.

**Comment by leastprivilege** [comment]
Yes - you need a profile service.

http://docs.identityserver.io/en/release/reference/profileservice.html

**Comment by rafaelvascc** [comment]
Thanks for response and sorry for the delay. Do you have an example of the implementation  of the profile service?
I see that the implementation of the DefaultProfileService is actually quite simple, but i still dont understand how to make my implementation work with my grant validation.
Thanks.

**Comment by leastprivilege** [comment]
No I don't - derive from the default and register it. Set a breakpoint in the methods and inspect the context. That's what I would do.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by rafaelvascc** [comment]
Sorry for not giving any updates. I was moved to another project and could not work on this issue anymore. Maybe another developer will ask further questions in the future. Thank you.
