### ISSUE TITLE
Alternative form for client Credential in Token endpoint

### ISSUE THREAD

**Issue by MonDeveloper** [IdentityServer/IdentityServer4#2208]
A couple of weeks ago I was looking for a way to Instantiate the TokenClient passing a client JWT already issued instead of the classic pair client_id & client_secret.
This is the Issue I opened looking for any suggestion IdentityModel/IdentityModel2#101.

Today I was digging a bit more on the server side of the TokenEndpoint and I discovered everything about client verification is resolved within the `IClientSecretValidator` implementation so I cloned the actual one and I created mine just adding the logic I need looking for the Authorization Bearer header and trying to verify if it is bringing the client information I need (just a double check with the client_id parameter).

It works, anyway there are some noisy parts:
- the duplication of the existing code (because I didn't find any way to put something in the middle of the existing `ClientSecretValidator` class with the access to the `HttpContext context` passed
- the need to create a custom TokenClient object in order put the client JWT as Bearer Header during the Call to the Token Endpoint

Do you think it could worth adding this logic into the IdentitytServer / IdentityModel base libraries?

**Comment by brockallen** [comment]
I think this question was asked (and answered) elsewhere. Can we close it?

**Comment by MonDeveloper** [comment]
yes.
Sorry for the spam.

Il giorno ven 6 apr 2018 alle ore 14:32 Brock Allen <
notifications@github.com> ha scritto:
