### ISSUE TITLE
"identity server is requesting your permission..."

### ISSUE THREAD

**Issue by enemyofthedawn** [IdentityServer/IdentityServer4#2209]
Sorry for confusion.

I'm new to OpenID Connect and OAuth in general. I'm aware it is used when you want to give third party users access to your api, something like GraphAPI in FB. You get this message then: "identity server is requesting your permission..." 

Question is: can I use it for internal WebAPI that is not meant to be used by third party users but by my application? I found this: http://docs.identityserver.io/en/release/topics/consent.html I'm on the right path? What if I just want to implicitly authorize the user in m application. 

Or to put it simply: When shouldn't I use identity server?

I want to make a WebAPI that can be accessed by various clients(desktop, web,mobile). I'm not sure if ASP.NET Identity without using identity server is enough. I want to base my architecture on microservices (project per feature/module). I'm not sure how to handle auth in microservices.

**Comment by brockallen** [comment]
Yes, you can disable the consent screen based on the client and your requirements.
