### ISSUE TITLE
Can't access custom user claims from my MVC client

### ISSUE THREAD

**Issue by ZahFox** [IdentityServer/IdentityServer4#2213]
Ok, before I explain this issue in detail let me please first state that I've spent ALOT of time these last few weeks trying to make this framework work for my application(s). I've gone through every quick-start, read most of the docs, spent time watching videos on OAuth and OpenID, and even read through a lot of the example code projects here on GitHub. Everything is nearly in place except one very important part, claims.. 

My current projects are pretty much three of the applications from the quick-starts (for now): My Identity Server is one using EF Core to persist operational data and my users are persisted using ASP.Net Identity in a separate user database. The other two applications are the MVC client and the API resource. My main goal is to make the MVC client a GUI for accessing the API resource. This API resource should have a custom user claim associated with it that defines a user's role in the context of the API alone, but this is the one critical part I can't get just right. According to the docs, what I'm supposed to do is add custom IdentityResource on my IdentityServer. In my case this one is called "notus-role" (notus being the eventual name for my API)

<img width="618" alt="defining-identity-resources" src="https://user-images.githubusercontent.com/23032758/38477023-4760420c-3b76-11e8-8b44-3d4b3d82bb87.PNG">

Ok, next I added an ApiResource that includes the previously created IdentityResource as a UserClaim (this is one of the parts I'm not so sure about..)
<img width="489" alt="defining-api-resource" src="https://user-images.githubusercontent.com/23032758/38477088-817ccf32-3b76-11e8-902c-46fc1cbcb8e6.png">

After that, I added an MVC client that has access to both the ApiResource and the IdentityResource
<img width="454" alt="defining-mvc-client" src="https://user-images.githubusercontent.com/23032758/38477117-b10fadf0-3b76-11e8-8900-eb2f2fe89e00.PNG">

Just to be thorough, here is the relevant section of the Startup.cs file for both the MVC client and API (MVC is the top image, API is the bottom image)
<img width="355" alt="startup-for-mvc-client" src="https://user-images.githubusercontent.com/23032758/38477531-ba272c04-3b78-11e8-9545-3f144e292e4b.PNG">
<img width="336" alt="startup-for-api" src="https://user-images.githubusercontent.com/23032758/38477178-f5c33ae8-3b76-11e8-8855-9c4254fd54a7.PNG">

Now comes one of the most confusing parts about all of this, (mostly because I haven't seen anywhere in the docs that mentions how to do this) adding a custom claim to the users. Naturally, having worked the ASP Identity before, I would assume that it is just like adding a claim to the Identity User, which I've done as you can see below:
<img width="368" alt="seeding-admin-with-claims" src="https://user-images.githubusercontent.com/23032758/38477241-4056e8b6-3b77-11e8-8749-ffc72e421955.PNG">
<img width="222" alt="user-claims" src="https://user-images.githubusercontent.com/23032758/38477246-45a73244-3b77-11e8-8c33-26e3e66d6a41.PNG">

Ok, now at this point, I've tested all of the applications and they work just fine, but as I've mentioned, this custom claim is an issue. What is strange is that when I call my API from the MVC client using the access token, my API client is able to see this custom claim:
<img width="548" alt="user-identity-from-api" src="https://user-images.githubusercontent.com/23032758/38477792-47ad7596-3b7a-11e8-96ca-e36eff4dc33f.PNG">

The main issue is that, from my MVC client, I can't seem to get this claim to appear no matter what I do (and yes I added its scope to startup file if you look in the picture from earlier on). There are only four claims I can ever see from the MVC client:
<img width="562" alt="user-identity-from-mvc" src="https://user-images.githubusercontent.com/23032758/38477824-7c68a882-3b7a-11e8-87b7-1c9be5189099.PNG">

This is an issue because I would like to make it so that the MVC client can authorize certain users for admin-like parts of the application using the notus-role. If you made it this far I really appreciate you taking the time to look this over. If you could provide some guidance it would be very appreciated (I'd be more than willing to contribute all of my code when I'm finished with this project for maybe a sample in the docs or something). Perhaps this is just me overlooking information that is already there, but I feel as if there isn't enough information in the docs explaining how custom claims and scopes are implemented. Yes, I understand how to define them, but I really have no idea how or when I can actually add that data a response/request (like what if I wanted a claim to be a list of user permissions or some custom data type). Get back to me when you can, any guidance would be a blessing.

> **Source Code for this project**
URL: https://bitbucket.org/ZahFox/asp-dot-net-core
BRANCH: Test-IdentityServer4
Project Names: 
    * Server - TestIdentity
    * MVC Client - TestIdentityServer-MVC-Client
    * API - TestIdentityServer4-API

> **Related Questions**
* Could you please clearly define the relationship between an IdentityResource and its claimTypes (are the claimTypes a 1-to-1 mapping of values from the aspnetuserclaims table in the User Database?)
* In an API resource, are the UserClaims based on IdentityResources, or purely from the aspnetuserclaims table?
* How can a profile be added as a claim? I see no table or any explanation of the format or process for dealing with profiles.

**Comment by leastprivilege** [comment]
Did you read this here as well:

https://leastprivilege.com/2017/11/15/missing-claims-in-the-asp-net-core-2-openid-connect-handler/

**Comment by leastprivilege** [comment]
Microsoft docs? Yea - totally agree. Tell @tratcher

**Comment by Tratcher** [comment]
Yeah... https://github.com/aspnet/Docs/issues/5106#issuecomment-356402957

**Comment by snickler** [comment]
@ZahFox @leastprivilege  @Tratcher  - I happened to come across the **[MapAllClaimsAction](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.oauth.claims.mapallclaimsaction?view=aspnetcore-2.2)**. 

Using it seemed to do the trick for me. Other than having to explicitly map my role claims to a "role" type beforehand, every custom claim is coming through from the User Info endpoint. 


```
                    options.ClaimActions.Add(new MapAllClaimsAction());
                    options.ClaimActions.DeleteClaim(JwtClaimTypes.Role);
                    options.ClaimActions.MapJsonKey(JwtClaimTypes.Role, JwtClaimTypes.Role, JwtClaimTypes.Role);
```

I did it this way instead of `options.ClaimActions.MapAllExcept(JwtClaimTypes.Role);` in order to maintain the ClaimsActions defined in the OpenIdConnectOptions (since MapAllExcept will clear all ClaimsActions first). This also makes sure that the `role` JToken doesn't add as an extra string JSON array of the roles you have defined.

**Comment by mayankgaur** [comment]
> @leastprivilege No I didn't, but I followed along and this solved my issue! I really feel like this is something that should be more clearly explained how to handle in the documentation.

Hi I am also facing similar issue could you please elaborate what you have done I have tried all this method but still I am not having extra claims .
options.SignInScheme = "Cookies";
                    options.Authority = "http://localhost:5000";
                    options.RequireHttpsMetadata =  false;
                    options.ClientId = "ecp_spa"; 
                    options.ClientSecret = "secret";
                    options.ResponseType = "id_token code";
                    options.SaveTokens = true;
                    options.GetClaimsFromUserInfoEndpoint = true;
                    options.Scope.Clear();
                    options.Scope.Add("openid");
                    options.ClaimActions.Remove("amr");
                    options.ClaimActions.Add(new MapAllClaimsAction());
                    options.ClaimActions.DeleteClaim(JwtClaimTypes.Role);
                    options.ClaimActions.MapJsonKey(JwtClaimTypes.Role, JwtClaimTypes.Role, JwtClaimTypes.Role);
