### ISSUE TITLE
ExternalLoginCallback unable to find cookie in Quickstart6 sample when using windows auth

### ISSUE THREAD

**Issue by jzelos** [IdentityServer/IdentityServer4#2216]
### Issue / Steps to reproduce the problem
When attempting to read the external cookie, the Account controller uses a different constant to that set via Windows authentication to denote the scheme. (It fails as there is no match)

Line 159
`var result = await HttpContext.AuthenticateAsync(IdentityConstants.ExternalScheme);`

Line 416
`
await HttpContext.SignInAsync(
    IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme,
    new ClaimsPrincipal(id),
    props);
`

When checking with Google external auth it appears that two cookies are present, one for each scheme identifier so I'm not sure which is preferable.

### Relevant parts of the log file

NA

**Comment by SIkebe** [comment]
similar to https://github.com/IdentityServer/IdentityServer4/issues/2166

**Comment by brockallen** [comment]
Yes, I'd suggest fixing it in your local version. Thanks.

**Comment by jzelos** [comment]
Apologies, didn't check closed issues, only open ones. Will close as duplicate of #2166

**Comment by brockallen** [comment]
Yea, no worries. We've been slow to merge dev into release -- we have a release coming up soon where we'll do this. Thanks again
