### ISSUE TITLE
GetErrorContextAsync does not always return description. 

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#2218]
### Issue / Steps to reproduce the problem

Load a client that is invalid and it should be caught by an error control.

```
     public async Task<IActionResult> Error(string errorId)
    {
        var vm = new ErrorViewModel();
        var message = await _interaction.GetErrorContextAsync(errorId);
        if (message != null)
            vm.Error = message;
        return View("Error", vm);
    }
```

### Relevant parts of the log file

```
fail: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Unknown client or not enabled: 3CCF1B2D-D064-4A1B-BFD4-57E0451575C7.apps.biz
{
        "SubjectId": "anonymous",
        "RequestedScopes": "",
        "Raw": {
          "client_id": "3CCF1B2D-D064-4A1B-BFD4-57E0451575C7.test.apps.biz",
          "redirect_uri": "http://localhost:4200/signin-oidc",
          "response_type": "id_token",
          "scope": "openid profile",
          "response_mode": "form_post",
          "nonce": "636589548258549622.YzMwMzRkNjAtYWU2Ni00ODlmLTg3ZWQtNmRmOThhYjcyN2JlZWFkYjk2MjEtNDAxNC00ZTQ1LWEzZTAtNTZmMWIyNDhkZjg1",
          "state": "CfDJ8FDPGFWZWNNOmnYDxcFlnVDZgaOG1kNakiXQF48y_4gnSxuIVAVQmMJ_4j9SUZz1TXGJDt4-8EKmoxLXuw3SZgyc5fy1ODzdS0Njd68T1W9dGxt8rFNrUF0njKk3XrSRTeJ45geS_uOL4w89OVupVq4UtHVbKxj3UMZLCn4W-BAXpXfo43KIT8RvxICMjbNtvPM1toEmMSlfdic6T6EZoxXpwim919xMLeQCY0S7QZdbc9DFfUfJkVYsLrofiBvQtZLfQjRQNp_7MiYFz_C4IQ7BAupErvZpcNvpBhQJWIt8BKlACVfKLHbvO6M0FKqa9A",
          "x-client-SKU": "ID_NET",
          "x-client-ver": "2.1.4.0"
        }
      }
```

### Response from GetErrorContextAsync

```
{  
   "DisplayMode":null,
   "UiLocales":null,
   "Error":"unauthorized_client",
   "ErrorDescription":"",
   "RequestId":"0HLCUR010ILME:00000001",
   "RedirectUri":null,
   "ResponseMode":null
}
```
Does not contain any error description.

### Offending code.

[AuthorizeRequestValidator.cs](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/AuthorizeRequestValidator.cs#L151)

```
var client = await _clients.FindEnabledClientByIdAsync(request.ClientId);
            if (client == null)
            {
                LogError("Unknown client or not enabled", request.ClientId, request);
                return Invalid(request, OidcConstants.AuthorizeErrors.UnauthorizedClient);
            }
```

Some of the other validators return a description the one above does not.  The example below does.

```
 return Invalid(request, OidcConstants.AuthorizeErrors.UnauthorizedClient, "Invalid redirect_uri");
```

### Work around 

```
if (message.Error == "unauthorized_client")
            {
                message.ErrorDescription = $" {message.ErrorDescription ?? "Client rejected"}. Contact plugin developer.";
            }
```
[Links to](https://stackoverflow.com/q/49752059/1841839)

**Comment by brockallen** [comment]
IIRC, we don't always put the description into the payload sent to the error page. I didn't get a chance to look yet (or to try to repro this), but can you see a description being added for that scenario?

**Comment by LindaLawton** [comment]
I need as much information as I can to pass on to developers so they don't contact me and force me to check the logs.

Ideally I am thinking that we should return the same errors Google authorization server returns

**Comment by brockallen** [comment]
Basically anywhere `Invalid` is called in the `AuthorizeRequestValidator` you're looking for the error description to be filled in.

**Comment by brockallen** [comment]
submitted a PR for review for this

**Comment by brockallen** [comment]
merged.

**Comment by VictorioBerra** [comment]
@LindaLawton 

> Ideally I am thinking that we should return the same errors Google authorization server returns

Do you have a link to the errors they expose specifically. This might also be a question for you too @brockallen : Exactly how much of exposing these errors is a problem? Is it kind of like specifying "Your username was right, but you provided the wrong password."?

While I think some errors are very helpful to expose for developers like "Invalid scope for client" but the result of things like `_uriValidator.IsRedirectUriValidAsync(redirectUri, request.Client)` might be a little more dangerous to expose.

If you chain enough errors together you could follow the breadcrumbs to putting all the right parts of an Authorization request together.
