### ISSUE TITLE
Get rid of DateTimeOffset?

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#222]
e.g. in Secret class - but also everywhere else

**Comment by brockallen** [comment]
done

**Comment by automatonic** [comment]
Out of curiosity, what is the motivation for ditching DateTimeOffset? I would assume it was something like this: http://stackoverflow.com/a/264643/8668

**Comment by brockallen** [comment]
Because we are always storing UTC, so the use of it was not necessary. Oh yea, and we had lots of complaints about it.

**Comment by automatonic** [comment]
OK. Thanks!
