### ISSUE TITLE
Issuing JWT token myself versus using IdentityServer4

### ISSUE THREAD

**Issue by enemyofthedawn** [IdentityServer/IdentityServer4#2221]
I currently issue tokens myself in my web api with `JwtSecurityToken` and I use standard ASP.NET Core middleware calling `AddJwtBearer` to verify the tokens. It works fine.

What advantage will give me using OpenID Connect (through IdentityServer4) over the approach described above? How to answer myself question "Do I need OpenID Connect?"

From my basic understanding about OpenID Connect, it is used to allow third parties to access your API. But I make API for myself and not for third parties and I don't know why should I favor IdentityServer/OpenIddict over my simple approach. 

I read that if I want Single sign-on I should use this, but JWTs itself aren't bound to any specific domain and I can use single sign-on with just pure JWTs. 

I understand it implements some kind of standard for issuing tokens. (protocol). It might be good if I ever wish to expose some API to third parties. But for internal APIs? Is it worth using it?

**Comment by TomCJones** [comment]
If you aren’t interested in obtaining user consent or any of those other niceties that come with a well thought out approach to managing user security or privacy, then go ahead with whatever you can hack up.

**Comment by enemyofthedawn** [comment]
Yeah, I'm not interested in any user consent as I want the auth to happen in the background (transparently) in my native mobile/desktop app. But I saw you can disable the consent if you want to. Can you give me some example why would I want to use OIDC instead of my own authentication/authorization flow? What other niceties do you mean? Basically I want just login/logout feature but using tokens and possibly "remember me" feature too (refresh tokens?)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by TomCJones** [comment]
https://www.scottbrady91.com/Identity-Server/Getting-Started-with-IdentityServer-4
