### ISSUE TITLE
External Provider and Proxy

### ISSUE THREAD

**Issue by morten-hogseth** [IdentityServer/IdentityServer4#2223]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem
1. Setting up external provider with oidc.
2. external callback url = internal.is.address/signin-oidc in WSO2
3. It works.

---

1. Putting the solution behind a Proxy.
2. changing callback url to proxy.is.address/signin-oidc in WSO2
3. WSO2 responds with 
    * invalid_callback - Registered callback does not match with the provided url.
4. inspect https://external-provider/oauth2/authorize? query string parameters
    *  redirect_uri:  internal.is.address/signin-oidc 

So the redirect_uri is using the internal address even when the request was initiated from the proxy.
Maybe that makes sense. My url rewrite guy told me he could not change 302 in proxy.

So where can I change this.

What I have tried. In AccountController, make sure the redirect url is correct.
But it seems that the oidc middleware is changing it?

---

        /// <summary>
        /// initiate roundtrip to external authentication provider
        /// </summary>
        [HttpGet]
        public IActionResult ExternalLogin(string provider, string returnUrl)
        {
            //returnUrl = Url.Action("ExternalLoginCallback", new { returnUrl = returnUrl });
            returnUrl = "https://proxy.is.address/Account/ExternalLoginCallback";

            var props = new AuthenticationProperties
            {
                RedirectUri = returnUrl,
                Items = { { "scheme", provider } }
            };
            return new ChallengeResult(provider, props);
        }

Please point me in the rigth direction in IS 4 application where I can fully change the redirect url to avoid the error above.

**Comment by leastprivilege** [comment]
This is a hosting concern - please check the Microsoft docs for deploying behind proxies or load balancers.

**Comment by morten-hogseth** [comment]
Ok thanks
