### ISSUE TITLE
Pass token from Mvc to Javascript

### ISSUE THREAD

**Issue by bahadircivelek** [IdentityServer/IdentityServer4#2226]
Hi,
My registration and login part in MVC side. at user login, i am redirect to user to my angular part but i wonder how can i pass access_token from mvc to angular side, what is the best way to do that ?

**Comment by brockallen** [comment]
I'd suggest treating your JS like a separate client and use oidc-client-js. Having said that, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
