### ISSUE TITLE
First request to identityServer ExternalLoginCallback Error

### ISSUE THREAD

**Issue by xaviergxf** [IdentityServer/IdentityServer4#2228]
Hi,

  The MVC Client when requesting the first time authentication to IdentityServer makes it throw the exception "External authentication error" because result.Successed is false and there's no failure message.

 /// <summary>
        /// Post processing of external authentication
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> ExternalLoginCallback()
        {
            // read external identity from the temporary cookie
            var result = await HttpContext.AuthenticateAsync(IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme);
            if (result?.Succeeded != true)
            {
                throw new Exception($"External authentication error {result?.Failure?.ToString()}");
            }
...
}

The client is logging with windows authentication. Why this happens only the first time? How can i obtain more detailed information about this error on AuthenticateAsync?

Thanks,

**Comment by brockallen** [comment]
Not sure. The code on that login page is your code. We only provide samples/quickstarts to get you started. You need to debug, understand, and control that code for your requirements.

**Comment by xaviergxf** [comment]
My code is a copy paste from one of the quickstarts...

**Comment by brockallen** [comment]
On you using the release QS UI code, or the dev branch UI code?

**Comment by brockallen** [comment]
I did find a bug in our dev branch code for windows auth. If you were also using the dev branch, apply this change to your code: https://github.com/IdentityServer/IdentityServer4/commit/a90bd0f1340a02f8e03280c1cf44d2b880b018f5

**Comment by xaviergxf** [comment]
Yes @brockallen, you may close the issue
