### ISSUE TITLE
Identity server 4

### ISSUE THREAD

**Issue by Muraliapm** [IdentityServer/IdentityServer4#2231]
Hi, 

I have created Authorization server project using Identity Server 4. Then I have created a. Net core API and generating token from API controller method using identity server which I have created. 

I can able to get token from identity server without any issues but after generating token, I stopped Authorization server and trying to access a controller method(this method set with Authorize attribute) using the token. I can able to access the method without running Authorization server.

Please let me know how to fix this issue? 

Thanks, 
Murali

**Comment by leastprivilege** [comment]
This is the way this works with self contained tokens (JWTs) - they are valid as long as the configured lifetime. You can set the AccessTokenType property on the client to Reference to get the behavior you want. 

https://identityserver4.readthedocs.io/en/release/topics/reference_tokens.html

**Comment by Muraliapm** [comment]
Thanks @leastprivilege!!. 
I am implementing my own identity server and could you please help me how to get refresh token. I am using HybridAndClientCredentials gran type and not able to get refresh token. I am able to get only access token. Please see my sample code,
![image](https://user-images.githubusercontent.com/23413513/39075501-93714758-4513-11e8-9b82-4e43593a90c7.png)
![image](https://user-images.githubusercontent.com/23413513/39076082-ebec721a-4516-11e8-8c13-049b4d082bb4.png)
![image](https://user-images.githubusercontent.com/23413513/39076227-bcc6c89a-4517-11e8-9390-8aff6b386c26.png)
Please let me know how to get refresh token using hybrid flow?.

Thanks,
Murali
