### ISSUE TITLE
Adding User Authentication with OpenID Connect

### ISSUE THREAD

**Issue by hflorin** [IdentityServer/IdentityServer4#2233]
### Issue / Steps to reproduce the problem
I have been following the steps from the documentation for adding user authentication with OpenID Connect. This link: [https://identityserver4.readthedocs.io/en/release/quickstarts/3_interactive_login.html].

So the setup is, on one hand, the standard Asp.Net Core MVC Web App acting as the host for  IdentityServer4. The app is the standard template with Authentication type set to use Individual User Accounts which sets up the Asp.Net Identity for user management.
On the other hand there is another MVC web app,acting as a client, configured to use the implicit grant types.
All the configuration is just copied and pasted from the above link.

The problem I am encountering which I can't get passed is the following scenario:

start up both client app and IdentityServer4 host app.
The HomeController Index action on the client app is marked with the Authorize attribute, so on accessing the homepage the client redirects to IdentityServer4 app to authenticate the user and setup the login cookie. Up to this point everything works great, including the login of the user on the identity server instance. The problem is that after the user is logged on he is not redirected back to the client app, instead he is redirected to the the login page on identity server instance, with the following return URL:

http://localhost:5000/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dmvc%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A5002%252Fsignin-oidc%26response_type%3Did_token%26scope%3Dopenid%2520profile%26response_mode%3Dform_post%26nonce%3D636593250073027688.YTU1MGQ4N2QtYmE4Mi00ZGRhLWE2ZWMtMmZlMGI5YTFkMjVkNzU1NDJhMGQtNTI2Mi00MmQwLTg4NjMtMjA3M2E3YjkzZmEx%26state%3DCfDJ8Cji98DpbOVNgLHtSuu73e7zJapnDOV-07ayG5XosX1Btfjud2vJXCTULMCILjfStfvUG8TDOK7fJMSfN8hVQSG0XCpqtPlJPSxaKogj4tOnPQEpn4b41pSql4ZzNiu3iBfI3g6_nPa0ERgyhLQdcBuQipHsMndvPWS9Tn2-XUM7vRBtckuyhfAt2fRwrJYHwd6q1sVlGKnzT_PQuaYui_YE11W0yQTTwhVuF0GGxIk32SG8XmeptHqYwxDUG3mwxB--xfn_3m1NCV0gP2j6l9yQO4vwrcZxdBqiKtbfIsfQ7nn5cImowqogUC9gMmy4RA%26x-client-SKU%3DID_NET%26x-client-ver%3D2.1.4.0

Other changes I've made were to replace the login methods from the AccountController created by the Visual Studio template, with the login methods from the QuickstartUI AccountController, since I want to keep the Registration logic it provides.
Also marked the login methods with the AllowAnnonymous attribute, since this caused an infinite loop.

I can provide code sample if needed. If anyone can help me with this issue I would be very grateful.

Thank you

**Comment by VictorioBerra** [comment]
@hflorin How did you fix this?

**Comment by skbelalmd** [comment]
Facing same issue....
@hflorin  Please mention the fix.
