### ISSUE TITLE
BasicAuthenticationSecretParser `Decode` of Secrets that have `+` signs breaks

### ISSUE THREAD

**Issue by ericgreenmix** [IdentityServer/IdentityServer4#2236]
I just updated from 2.1.1 to 2.1.3. After the update I kept getting `invalid_client` on then `token` endpoint. With the reason of `Invalid client secret`.

I tracked this down to a change in 2.1.2 that added the `Decode` method to the `BasicAuthenticationSecretParser` on the secret. 
https://github.com/IdentityServer/IdentityServer4/blob/bfd7031bdc1b950db12859d0597fec1f05cede60/src/IdentityServer4/Validation/BasicAuthenticationSecretParser.cs#L109

While adding this decoding of the Uri value meets RFC6749, it breaks any existing client secrets that have a `+` sign in them. Which is what is happening in the case of the secret that I am using.

Is there a standard for generating secrets that I should be using, so there isn't a breaking change to my secrets getting parsed in the future?

**Comment by mpomery** [comment]
What happens if you encode your client secret before you send it?

The decode message replaces all unencoded plus signs with encoded spaces, changing the character it ends up as when the decode runs.

**Comment by ericgreenmix** [comment]
Right, so I saw that the `TokenClient` in the IdentityModel has been updated to have this encoding. So if I go update all the dependent applications to the latest version of IdentityModel, that adds this encoding, things start working again. 

I also just found https://github.com/IdentityServer/IdentityServer4/issues/2086, which describes this issue as well. Closing
