### ISSUE TITLE
Is there a way how you can show a progress screen after the login screen?

### ISSUE THREAD

**Issue by tomasfilipEC** [IdentityServer/IdentityServer4#2237]
Hi,

first of all, thank You for all the hard work that you put into Identity Server. 
And now my question:

Once the user clicks login on the login screen and the login is successful the user is redirected to connect/authorize. During that time the user is presented with a blank screen while the processing is handled.

Is there a way how I could show a custom HTML page during this step? It would be a simple page with a progress animation.

Thank you

Kind Regards 
Tomas Filip

**Comment by mpomery** [comment]
`connect/authorize` responds with a 302 redirect back to the client application. How long are you seeing this page for? What does the network performance tab in your browser show?

I just ran a test on my instance and my login took 500ms, while the authorize page was around 70ms
![Test Run](https://i.imgur.com/NixLu63.png)

- First call is the form submission, which redirects to `connect/authorize`. (497ms)
- `connect/authorize` redirects to my client applications callback point (67ms)
- That callback point redirects to my application. (12ms)

Note: This is running against my IdentityServer3 service, but the performance should be similar in an IdentityServer4 instance.

**Comment by leastprivilege** [comment]
The above interfaces were used in IdentityServer3 - this is the IdentityServer4 repo. We don't do free support anymore on the old versions. Here are some alternative options:

https://identityserver4.readthedocs.io/en/release/intro/support.html

**Comment by tomasfilipEC** [comment]
I understand,
thank you for your support anyway.

Kind Regards
Tomas Filip
