### ISSUE TITLE
missing steps to use `IdentityServer4.Quickstart.UI.AspNetIdentity` content of repo

### ISSUE THREAD

**Issue by ntregillus** [IdentityServer/IdentityServer4#2241]
https://github.com/IdentityServer/IdentityServer4.Quickstart.UI.AspNetIdentity

notes say there are directions on how to use this repo over an existing project, but never provides them

**Comment by ntregillus** [comment]
This is my third attempt at using IdentityServer4 on my existing Aspnet identity website. all have failed to build the entityframework migrations since i already have a context that is used for my project.

all the documentation I am finding is for greenfield new projects. tacking this on an existing aspnet identity solution just isn't working (aka migrations never get generated when attempting to build them.

**Comment by leastprivilege** [comment]
I am not sure if work was ever completed in this repo. Not enough resources I am afraid.

**Comment by Irfan434** [comment]
I think the directions mentioned in the first comment are here:
http://docs.identityserver.io/en/release/quickstarts/3_interactive_login.html

The above link is page 3 of the IdentityServer4 tutorial. The first page is here:
http://docs.identityserver.io/en/release/quickstarts/0_overview.html
