### ISSUE TITLE
Update clients in IdentityServer4 database

### ISSUE THREAD

**Issue by hubaozhang** [IdentityServer/IdentityServer4#2242]
I use Net core EF for MS SQL database access. I have the following code to seed and update my database.

     private static void EnsureSeedData(ConfigurationDbContext context)
        {
            if (!context.Clients.Any())
            {
                Console.WriteLine("Clients being populated");
                foreach (var client in Config.GetClients().ToList())
                {
                    context.Clients.Add(client.ToEntity());
                }
                context.SaveChanges();
            }
            else
            {
               Console.WriteLine("Clients already populated, update clients");
					foreach (var client in Config.GetClients().ToList())
					{
						var item = context.Clients.Where(c => c.ClientId == client.ClientId).FirstOrDefault();
					   if(item == null)
						{
							context.Clients.Add(client.ToEntity());
						} else {
							var model = client.ToEntity();
							model.Id = item.Id;
							context.Entry(item).CurrentValues.SetValues(model);
						}						
					}
					context.SaveChanges();
				}}
It seems there is a bug in the IdentityServer4 model definition. If there is no records in the database, every thing is populated correctly. If there are some records, some records are updated correctly while others are not updated.

**Comment by LindaLawton** [comment]
Which properties exactly are not being updated?

Any chance you can give me a client before and what you are trying to update it to?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by hmsca** [comment]
I'm actually having the same issue. I can't update the AllowedScopes property.
