### ISSUE TITLE
Invalidate client side cookie with token service

### ISSUE THREAD

**Issue by garymacpherson** [IdentityServer/IdentityServer4#2243]
Just wanted to clarify my knowledge and ensure there wasn't a configuration piece I was missing.

Upon successful sign-in the browser is issued idsrv.session and .AspNetCore.Cookies cookies which allowed repeated access to the /connect/authorize endpoint to be handled without having to login again (unless prompt=login param is found)

When the end user browses to /connect/endsession these 2 cookies are cleared up, however it appears as if these cookies are entirely self-contained with no server side representation of them to allow server side invalidation. Result is that if they were to be compromised that they could be used in a replay attack to reissue tokens.

Is there any kind of configuration that I am missing or risk mitigation I can implement to reduce this problem?

**Comment by brockallen** [comment]
You can configure the cookie handler in ASP.NET Core to store a server-side representation of them (via ITicketStore SessionStore on the cookie options). That's an ASP.NET Core feature, so check the Microsoft docs.

**Comment by garymacpherson** [comment]
Cheers for the direction.
