### ISSUE TITLE
Sign in: authorize specific users in concrete apps

### ISSUE THREAD

**Issue by ddydeveloper** [IdentityServer/IdentityServer4#2245]
Hi! 

Could you clarify can I use ID4 to authenticate specific user on specific apps. E.g. I have two apps, one app for limited part of the users and another - for all users. I want to provide followed flow:

1. I logged in as a first app user. When I open the second app I want to be redirected to the ID4 log in page (even if I was logged in in the first app)

2. And the same in the opposite case. I logged in as a second app user. When I open the first one I want to be redirected to the ID4 log in page;

I try to configure OIDC promt property:

`options.Events.OnRedirectToIdentityProvider = context =>
                    {
                        context.ProtocolMessage.Prompt = "login";
                        return Task.CompletedTask;
                    };`

But I got not suitable behaviour: now I can be logged in only in one app at the same browser. It is not think I expected.

I try to investigate this on SO and got this answer: 

https://stackoverflow.com/questions/49880489/identityserver4-authenticate-each-client-separately

I'm not completely sure, that it is true. If I'm not mistaken ID4 use cookie to check the user was logged in , but I suppose that we can at least create specific cookie acording to the client app?

Any help would be really appreciated.

**Comment by leastprivilege** [comment]
IdentityServer is a **single sign-on** system. If you need to restrict certain users to applications, you need to put that logic into the application itself.

**Comment by ddydeveloper** [comment]
I am right to reach expected behaviour I need to implement one of the followed solution:

1. Use separate IdentityServer Node for each context (group of the app with SSO);
2. Use Roles to manage access to the concrete apps according to the logged in user;
3. Implement own authentication logic for each app.

**Comment by leastprivilege** [comment]
None of the above.

IdentityServer is the central authentication system. App access is managed in the app.

**Comment by ddydeveloper** [comment]
@leastprivilege OK, I understand, but can I use [Authorize(Roles="myrole")] for client controllers actions returned view. We have central authentication point but check the access for each app separately. 

It is not against the idea of the IdentityServer, isn't it?

**Comment by leastprivilege** [comment]
You can do that.

**Comment by ddydeveloper** [comment]
Thank you for help, close this issue
