### ISSUE TITLE
Get client id in the Login action

### ISSUE THREAD

**Issue by ddydeveloper** [IdentityServer/IdentityServer4#2246]
Do ID4 provides opportunity to get client id in the login action? I can parse it from the returnUrl field but it seems not so good decision.

**Comment by leastprivilege** [comment]
Check our quickstart UI

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/release/Quickstart/Account/AccountController.cs#L80

**Comment by ddydeveloper** [comment]
Thank you!
