### ISSUE TITLE
SSO with multiple tenants

### ISSUE THREAD

**Issue by Meldow** [IdentityServer/IdentityServer4#2247]
I have several tenants that are defined by different URL using the same client

Client - c1

Tenants - t1, t2, t3

so, our users can access the client using different URL

http://t1.c1.com

http://t2.c1.com

http://t3.c1.com

Everything works wonderfull except when trying to single sign out.

[According to the docs](http://docs.identityserver.io/en/release/topics/signout.html), we will use the field **FrontChannelLogoutUri** from Client to open a IFrame to clear the cookies for that client.

If we set the FrontChannelLogoutUri for any of the domains above, the SSO works for that tenant, but not for the others

**Question**: How can we logout from any of the above tenants?
(single **FrontChannelLogoutUri** that will log out from all http://t1.c1.com, http://t2.c1.com, http://t3.c1.com and http://c1.com. (domain + subdomains)

My idea was to manually delete ALL the cookies from all subdomains, so, using FrontChannelLogoutUri as http://c1.com/logout-confirm, therefore it would clear all the cookies in that domain/subdomain

```
 [HttpGet("logout-confirm")]
 public async Task LogoutConfirm()
 {
    foreach (var cookie in Request.Cookies.Keys)
    {
       Response.Cookies.Delete(cookie);
    }
    HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
    HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
 }
```
This works if we open a new tab with that URL (defined in the client table), but for some reason the IdentityServer does not open the IFrame with that URL upon executing sign out.

Any ideas?
Thanks in advance

**Comment by brockallen** [comment]
Use the backchannel logout for that scenario.

**Comment by Meldow** [comment]
@brockallen  Thank you for the quick response

I've added the same URL to the back-channel and now it logs the following

13:31:05.159 D      7 32766 1000  [IdentityServer4.Validation.EndSessionRequestValidator] Client front-channel logout URLs: "https://c1.eu/oneloginconnector/logout-confirm?sid=8a9c807850c2b4050f57231e0d845b69&iss=https%3A%2F%2Fc1.eu%2Foneloginidentity" 
13:31:05.159 D      7 32766 1000  [IdentityServer4.Validation.EndSessionRequestValidator] Client back-channel logout URLs: "https://c1.eu/oneloginconnector/logout-confirm" 
13:31:05.159 I      7 32766 1000  [IdentityServer4.Endpoints.EndSessionCallbackEndpoint] Successful signout callback. 
13:31:05.159 D      7 32766 1000  [IdentityServer4.Endpoints.EndSessionCallbackEndpoint] Client front-channel iframe urls: ["https://c1.eu/oneloginconnector/logout-confirm?sid=8a9c807850c2b4050f57231e0d845b69&iss=https%3A%2F%2Fc1.eu%2Foneloginidentity"] 
13:31:05.159 D      7 32766 1000  [IdentityServer4.Endpoints.EndSessionCallbackEndpoint] Client back-channel iframe urls: ["https://c1.eu/oneloginconnector/logout-confirm"] 
13:31:05.617 D     11 32765 1000  [IdentityServer4.Infrastructure.BackChannelLogoutClient] Back channel logout for client id: "xx_client_id" to URI: "https://c1.eu/oneloginconnector/logout-confirm", result: 405 
13:31:05.617 V     11 32765 1000  [IdentityServer4.Hosting.IdentityServerMiddleware] Invoking result: "IdentityServer4.Endpoints.Results.EndSessionCallbackResult" 

**Question #1** What is the purpose of the back channel? In my understanding, would be clients using PasswordCredentials flow, where you have no browser, this should be the way to trigger the log out, but I think i'm missing concepts here

**Question #2**  Back channel logout for client id:  (...) result: 405
Any idea why I'm getting a 405 Method Not Allowed ?

**Comment by Meldow** [comment]
[Further investigation](https://openid.net/specs/openid-connect-backchannel-1_0.html#BCRequest) found out that it is a POST and not a GET, will be trying some ideas and will get back asap

**Comment by Meldow** [comment]
Following [this issue](https://github.com/IdentityServer/IdentityServer4/issues/2224) I am now able to redirect to the subdomain and successfully sign out of the clients!

Thanks for an awesome product!
