### ISSUE TITLE
Exception: Duplicate API scopes found

### ISSUE THREAD

**Issue by odinnou** [IdentityServer/IdentityServer4#2248]
Hello !

I have upgrade recently my Identity Server from v2.1.3 to 2.2.0 without changing anything else.
But, when I try to get a token, I got this exception : 

"Duplicate API scopes found. This is an invalid configuration. Use different names for API scopes. Scopes found: basic"

![scopes_fail](https://user-images.githubusercontent.com/3084655/38943501-dc33b2d4-4331-11e8-8d45-35290d12e1b5.PNG)

Indeed, i use the scope name "basic" in the API "internal" and the API "external" but this configuration works in v2.1.3 and during last year (IDsrv v3 & v4).

My configuration here  

 ```
 return new[]
{
        new ApiResource
        {
            Name = IdentityConstants.API_INTERNAL,
            ApiSecrets =
            {
                new Secret(config.APISecrets[IdentityConstants.API_INTERNAL].Sha256())
            },
            Scopes =
            {
                new Scope()
                {
                    Name = IdentityConstants.SCOPE_SUPER,
                    DisplayName = "Admin access"
                },
                new Scope()
                {
                    Name = IdentityConstants.SCOPE_BASIC,
                    DisplayName = "Basic access"
                }
            }
        },
        new ApiResource
        {
            Name = IdentityConstants.API_EXTERNAL,
            ApiSecrets =
            {
                new Secret(config.APISecrets[IdentityConstants.API_EXTERNAL].Sha256())
            },
            Scopes =
            {
                new Scope()
                {
                    Name = IdentityConstants.SCOPE_LOGGED,
                    DisplayName = "Logged access",
                },

                new Scope()
                {
                    Name = IdentityConstants.SCOPE_BASIC,
                    DisplayName = "Basic access"
                }
            }
        }
};
```

I hope, it's just a bug t_t

Thanks in advance!
Kind regards, Remi

**Comment by leastprivilege** [comment]
Scope names must be unique. Since this was a common configuration mistake, we added a check for it in the latest version.

**Comment by odinnou** [comment]
Hello
Ok ok, thank you, I was afraid of this answer xD

I will update this.

**Comment by odinnou** [comment]
Just out of curiosity the "offline_access" scope is an exception so ?
If I want to use refresh_token with 2 differents APIs, I will not have this error ?

**Comment by leastprivilege** [comment]
Yes. You wouldn't put offline_access into the scope list - rather set EnableOfflineAccess on the client.

**Comment by odinnou** [comment]
Yes, indeed.. sorry for my stupid question ^^

**Comment by Pete-PlaytimeSolutions** [comment]
Does this imply that if you were to have a micro services architecture with dozens of API's, and a single UI , I now need to request an access token from the UI with up to 20-30 individual scopes? One for each individual ApiResource?

**Comment by brockallen** [comment]
>  I now need to request an access token from the UI with up to 20-30 individual scopes? One for each individual ApiResource?

Depends how you design your scopes. But having 20-30 scopes sounds like a lot to me, as that becomes unmanagable.

**Comment by hugoqribeiro** [comment]
I am having trouble with this. How does this not break existing configuration that had this issue?
