### ISSUE TITLE
Consider Properties on ApiResource and IdentityResource EF models

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2249]
Please

**Comment by brockallen** [comment]
@leastprivilege let's discuss

**Comment by scottbrady91** [comment]
What, like client properties?

**Comment by LindaLawton** [comment]
Not apposed to it as i currently use client properties.    What is your use case?   and could it be expanded to other tables?

**Comment by TomCJones** [comment]
I have started a project to put properties on user private information. This effort is needed (IMHO) to become GDPR compliant.

**Comment by leastprivilege** [comment]
> I have started a project to put properties on user private information

And how is that in any way related to this issue?

**Comment by TomCJones** [comment]
how is that any different from Properties on IdentityResource EF models

**Comment by brockallen** [comment]
properties added to api and identity resources
