### ISSUE TITLE
IdentityServer might log tokens in case of error

### ISSUE THREAD

**Issue by mantasaudickas** [IdentityServer/IdentityServer4#2251]
Hello,

we are using IdentityServer4, v 2.1.3 with ASP.NET Core 2.0.6.
For logging we use Serilog structured logging.
Recently I noticed that in case of authorization errors tokens are also logged.

I don't think it is very safe behavior especially when distributed logging can be used  like ELK where anybody can accidentally see issued token.

One particular case we have when using Implicit flow with silent refresh. In case of misconfiguration of silent refresh url [AuthorizeRequestValidator ](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/AuthorizeRequestValidator.cs#L630) logs error with request details which also contains id_token_hint.

In general it might be also more of such places.
Any thoughts on this?

**Comment by leastprivilege** [comment]
id_tokens are not security sensitive (as opposed to access tokens). But I agree that this could leak personal data.

We'll look into it.

**Comment by mantasaudickas** [comment]
Yes, I agree it is not security sensitive, but having in mind that id_token by default is valid for 5 minutes (http://docs.identityserver.io/en/release/reference/client.html#token), it might be an issue.
Also maybe there are other places where such information might be logged even with access_token..

**Comment by LindaLawton** [comment]
We have currently been working on [GRDP](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation)  there was a question posed in a meeting yesterday about the data that is being logged by Ids4.   Unfortunately its hard for me to see what is standard logging and what was added by my predisor

>info: X.IdentityServer.Services.XClaimsService[0]
      Loading Installed App claims for user 21248582 with fiscal of 21880.

I think it would be nice to know what is exactly logged by default and how it may be effected by [GRDP](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation).   As well as some kind of guidelines of what not to log.    Not that i am saying [GRDP](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) is the responsibility or a concern of this project but well as a group we could come up with some best practices.

**Comment by leastprivilege** [comment]
Good idea - do some research and we can incorporate that in docs and future versions.

**Comment by leastprivilege** [comment]
> but having in mind that id_token by default is valid for 5 minutes  

Even in that time period it is not security sensitive. But anways - yes - re-working logging is on of our big todo features for 3.0

**Comment by LindaLawton** [comment]
I have a feeling I just inadvertently volunteered for this task.   Documentation is on git right?

**Comment by leastprivilege** [comment]
I think you did. Do your research first - then we can discuss.

**Comment by LindaLawton** [comment]
I have a question first.   Is it the responsibility of IDs4 to ensure GDPR compliance?   or is it up to the developer using IDs4 that what they are doing is GDPR compliant?   there is a difference in how we approach this.

I have no use in looking into this I need to anyway for work now that I have spotted it in the logs management knows there is a problem.

**Comment by TomCJones** [comment]
That's been a broiling topic for a very long time.  See this https://www.splunk.com/en_us/form/how-to-operate-your-siem-under-the-gdpr.html?ac=bing_amer_usa_en_search_generic_security&utm_campaign=bing_amer_usa_en_search_generic_security&utm_source=bing&utm_medium=paidsearch&utm_term=siem&utm_content=laymans_guide_SIEM_GDPR_WP_EN&_bt=71124728250246&msclkid=77c887379deb188cd381ddef48a56766

my own take is that when logs contain personal information (and authN does contain personal information), then the logs need to be strongly protected from disclosure. That means a separate authZ solution for the logs.  But to your question, it depends on whether IdSvr is concerned with demos, or with real-world implementations. Real-world implementations do need to consider security of the logs.

**Comment by LindaLawton** [comment]
I was more thinking could we / should we prevent some information from being logged?

Example: Google analytics will no longer accept logging of emails they drop the data.   

or should we recommend that logs be stored secure and what you choose to log is up to you.

**Comment by leastprivilege** [comment]
What I was thinking off is to analyze what we are currently logging and point out possible problems so we can address them in the future.

**Comment by LindaLawton** [comment]
sounds like a good a place to start as any.   I have a few hours tomorrow I will start there.

**Comment by leastprivilege** [comment]
I removed the potential id_token_hint from the authorize log.

https://github.com/IdentityServer/IdentityServer4/commit/82f130c7065240660cd5d2b3123478a515b12e8d

Anything else? For 2.3 we can't go through all possible logging scenarios - but now is the time to make some changes for the next minor release.
