### ISSUE TITLE
SAMLRequest IssueInstant too old to trust

### ISSUE THREAD

**Issue by FletcherNZ** [IdentityServer/IdentityServer4#2253]
Hi,

Currently having an issue with Identity Server 4.0 using Azure AD B2C as source of user registration and securing via MFA. 

As the registration time varies depending on the user logging into their MSA/Gmail account and then adding their MFA authentication methods and then validating these, by the time they hop back to Identity Server the following error appears:

Error
Sorry, there was an error : invalid SAML Request
SAMLRequest IssueInstant too old to trust

If we then click on the initial link again they successfully login, I'm unsure if this is a bug or a configuration setting update required but haven't found out where this stems from yet.

Thanks in advance for any pointers on this issue.

**Comment by leastprivilege** [comment]
This error message definitely doesn't come from us. Do you have a call stack?

**Comment by scottbrady91** [comment]
This is an error from our IdentityServer4.Saml component. Are you in contact with anyone from RSK? If not could you please email your issue to support@rocksolidknowledge.zendesk.com?

Off the top of my head, I'm unsure if we have a configuration option for this at the moment. If not we'll open a feature request for you.

**Comment by FletcherNZ** [comment]
Thanks for the update all, will log a support call against the plugin now.

**Comment by andreslon** [comment]
I have the same problem, only change the demo key in the startup file.
So, How I can implement SAML in my API ?

![image](https://user-images.githubusercontent.com/2242679/39222249-54c9e5aa-4801-11e8-9bd7-a4b0e843eedf.png)

![image](https://user-images.githubusercontent.com/2242679/39222225-29aa63fe-4801-11e8-88a2-0fec191924b5.png)

Thanks.

**Comment by scottbrady91** [comment]
@andreslon This is a different error. Also SAML in an API? There are no access tokens with SAML.

Best place for issues like these is support@rocksolidknowledge.com or your contact at RSK. Otherwise, if this is an issue with the sample repo, the issue tracker in the SAML2P sample repository.

Could you use one of these methods and let us know what service provider you are using (your client app) and maybe provide us with a sample SAMLRequest.
