### ISSUE TITLE
Separate "Abstract" models into POCO "Core" package

### ISSUE THREAD

**Issue by liamdawson** [IdentityServer/IdentityServer4#2254]
I have a scenario where I want to share some IdentityServer4 models between a couple of projects via a Class Library project, and this currently means that I need to add the full `IdentityServer4` nuget package to that shared project. It would be lovely if some of the configuration POCOs could be separated into a `IdentityServer4.Abstractions` or similar library, mainly for classes like `IdentityResource` and `ApiResource`, `Client`, etc.

**Comment by leastprivilege** [comment]
There's already a separate issue for that. We are considering it for the next major version.
