### ISSUE TITLE
Configurable reference access token size

### ISSUE THREAD

**Issue by Exocomp** [IdentityServer/IdentityServer4#2255]
I've searched and looked into the doc but I didn't find an answer, apologies if I overlooked it.  

For those who are paranoid is it possible to increase the length/size of the reference access token, is it configurable?  

Currently it is 64 characters, which I would like to increase.  With the underlying paranoia being that someone could attempt random tokens and get a positive hit.  

I ask the question with the understanding that other mechanisms could be used to throttle/mitigate an attack using random tokens.

**Comment by leastprivilege** [comment]
The entropy is 256 bit. Are you sure you need more? Do the math yourself.

That being said - you can replace the `IHandleGenerationService` .

**Comment by cqpaul** [comment]
Can the token be more Shorter? It's too long to use in the url.
