### ISSUE TITLE
Can you make a service accepting access token from multiple authority?

### ISSUE THREAD

**Issue by ThisNoName** [IdentityServer/IdentityServer4#2256]
I have internal app authenticating with AD/LDAP/IdSvr4, an external app using IdSvr4 and UserId/Password from database.  Both apps need to access the same WebApi.  What's the best way to make the service accepting all tokens and consider requests from both apps as Identity.IsAuthenticated? 
 I searched around but couldn't find any definitive answer.

I have a TypeFilterAttribute where I could probably hard-coded to handle both token?  Clearly not good.

I have a bunch of code implementing IAuthorizationProviderFactory and IAuthorizationProvider.  Haven't finished it yet.  But is that the right direction?

Or could it be as simple as adding two authority at startup?

.AddIdentityServerAuthentication(options =>  {
           options.Authority = "http://SsoInt; http://SsoExt"

I thought I saw something in that direction, but couldn't find it again.

Any suggestions?  Really appreciated.

**Comment by leastprivilege** [comment]
That's not really recommended - an API should only trust one authority. 

That said - you can add one authentication handler for each authority.

**Comment by ThisNoName** [comment]
Thanks for the follow up.  Both my "authority" are handcrafted IdSvr4 using bearer token.  But looks like you can't have two Jwt Bearer handler out of the box?

I'm just looking to pass Identity.IsAuthenticated without too much custom coding, but worst case scenario, I'll just have two of the same api off by one config line.
