### ISSUE TITLE
Question: Ability to get Authorization_Code via a direct api call.

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2258]
I probably committed heresy against the OIDC Spec, but whatever.

I modified IdentityServer4 directly to achieve the ability to get an authorization_code without going through a UI login/consent flow.

## Authorize2 API 
Note the access_token here works against the user_info api.
```
https://localhost:44312/connect/authorize2
Content-Type:application/x-www-form-urlencoded
Authorization:Bearer { access_token}

scope:offline_access
client_id:resource-owner-client
client_secret:secret
beneficiary_client_id:resource-owner-client_2
redirect_uri:https://blah
response_type:code
prompt:none

```
## Produces
```
{
    "code": "7073566239a4218154c4ecfc2be89e6ebd674028e6ca5a3a55b9792772b0b84d"
}
```

I then can make an ordinary token call with the code

## Retrieve the tokens
```
https://localhost:44312/connect/token
Content-Type:application/x-www-form-urlencoded  

grant_type:authorization_code
client_id:resource-owner-client
client_secret:secret
code:a4c3d55860266d204265f0661de4d34282726805060830bb1481720ca9900bef
redirect_uri:https://blah
```
## Produces
```
{
    "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijc4OGRhZjMxYmRjYWUwMzE1MWUwYzRkMWQ1MDNjOTU0IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MjQ0MzE2NjksImV4cCI6MTUyNDQzNTI2OSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMTIiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0NDMxMi9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJyZXNvdXJjZS1vd25lci1jbGllbnQiLCJzdWIiOiJyYXQiLCJhdXRoX3RpbWUiOjE1MjQ0MzEyNjQsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdfQ.iMHN-xTuaAm8PBLARYJpkpuu_oy1a5eVBP6xSZlIdFGFOfLkJ_HvGjywZcSagzrPgYeQSN_pPSzf2QwZLg6wFwoZkvsaW-qD9ebiqZZqSTGTYxGGafapYR8Vn_VIIfC48va1bkwlo5F04UAw6uBPKI5Bq3_NQuklBgWsUveHAfkOt0A8OvPrgvfS870n7CZ58u31EvdkHlF1cz2_u4UcdoT8MvwZUXVA5VhFUW3e2sZocVQqUuoua8W7u9p6muKufC5zJ00vzwg-LPYooIxEc0ouFVFfRguMCdLrDY_3lrDTe8B8iE48F5zvVqSkjmH6H-_5s8MV_8f39TVsTLuUYQ",
    "expires_in": 3600,
    "token_type": "Bearer",
    "refresh_token": "f4705f92e510659cdb777b70d8b806d982015119f8f18e7f4a718b27c3b4fb95"
}
```

So here is the questions:
I introduced a new custom/non-spec endpoint to IdentityServer4 which required access to a handful of internal classes.  
1.  Would there be a better way to do this than getting access to internal class you haven't opened up to be publicly consumed?  
2.  Would you be open to exploring opening up some of these classes so I can do this without forking IdentityServer4?  
3. Would you be open to letting endpoints to registered so they are part of your endpoint router?  

Stuff I need direct access to;
```
AuthorizeResult as I needed to typecast from IEndpointResult, so I could get the internal Response.
AuthorizeEndpointBase as my Endpoint leveraged some helpers in there to produce the authorization_code.
internal class Authorize2Endpoint : AuthorizeEndpointBase
{
}

```

**Comment by brockallen** [comment]
Why not use an extension grant? That's what it's designed for.

**Comment by ghstahl** [comment]
Ok then, I will get back to you with that implementation's result.

**Comment by ghstahl** [comment]
Extension Grants rock, and worked as expect.  I still have an ask to have a context object that is passed from IExtentionGrant all the way to IProfileService.  I have another issue about that, but we can close this.  Thanks.
