### ISSUE TITLE
Unable to Add Scopes/Claims to Interactive Sample Project

### ISSUE THREAD

**Issue by BM78** [IdentityServer/IdentityServer4#2259]
I'm currently forced to use ASP.NET Core 1.x so I'm working with the aspnetcore1 branch of your IdentityServer4.Samples repo.

I was able to run Quickstart3_ImplicitFlowAuthentication without issue, but when I attempt to add the Email scope and claim, it does not appear in the User.Claims collection.  I see that many others have had similar issues but I have not been able to solve the issue and fear I am missing something obvious.  The changes I have made are as follows:

In QuickstartIdentityServer project's Config.cs:

- added `Email` `IdentityResource` to `GetIdentityResources()`
```c#
        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Email(),
            };
        }
```
- added `Email` to the allowed scopes of the implicit flow client (MVC)
```c#
                // OpenID Connect implicit flow client (MVC)
                new Client
                {
                    ClientId = "mvc",
                    ClientName = "MVC Client",
                    AllowedGrantTypes = GrantTypes.Implicit,

                    RedirectUris = { "http://localhost:5002/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:5002/signout-callback-oidc" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                    }
                }
```

- added Email claims to the two test users
```c#
                new TestUser
                {
                    SubjectId = "1",
                    Username = "alice",
                    Password = "password",

                    Claims = new List<Claim>
                    {
                        new Claim("name", "Alice"),
                        new Claim("website", "https://alice.com"),
                        new Claim( IdentityServerConstants.StandardScopes.Email, "alice@xyz.com" ),
                    }
                },
                new TestUser
                {
                    SubjectId = "2",
                    Username = "bob",
                    Password = "password",

                    Claims = new List<Claim>
                    {
                        new Claim("name", "Bob"),
                        new Claim("website", "https://bob.com"),
                        new Claim( IdentityServerConstants.StandardScopes.Email, "bob@xyx.com" ),
                    }
                }
```

The discovery document then contains `email` in `scopes_supported` and `email` and `email_verified` in `claims_supported`.

```json
{
  "issuer": "http://localhost:5000",
  "jwks_uri": "http://localhost:5000/.well-known/openid-configuration/jwks",
  "authorization_endpoint": "http://localhost:5000/connect/authorize",
  "token_endpoint": "http://localhost:5000/connect/token",
  "userinfo_endpoint": "http://localhost:5000/connect/userinfo",
  "end_session_endpoint": "http://localhost:5000/connect/endsession",
  "check_session_iframe": "http://localhost:5000/connect/checksession",
  "revocation_endpoint": "http://localhost:5000/connect/revocation",
  "introspection_endpoint": "http://localhost:5000/connect/introspect",
  "frontchannel_logout_supported": true,
  "frontchannel_logout_session_supported": true,
  "scopes_supported": [ "openid", "profile", "email", "api1", "offline_access" ],
  "claims_supported": [ "sub", "name", "family_name", "given_name", "middle_name", "nickname", "preferred_username", "profile", "picture", "website", "gender", "birthdate", "zoneinfo", "locale", "updated_at", "email", "email_verified" ],
  "grant_types_supported": [ "authorization_code", "client_credentials", "refresh_token", "implicit", "password" ],
  "response_types_supported": [ "code", "token", "id_token", "id_token token", "code id_token", "code token", "code id_token token" ],
  "response_modes_supported": [ "form_post", "query", "fragment" ],
  "token_endpoint_auth_methods_supported": [ "client_secret_basic", "client_secret_post" ],
  "subject_types_supported": [ "public" ],
  "id_token_signing_alg_values_supported": [ "RS256" ],
  "code_challenge_methods_supported": [ "plain", "S256" ]
}
```
When I log in with one of the test users, however, I am not prompted for consent for the `Email` scope:

![image](https://user-images.githubusercontent.com/25416056/39123756-cc30410c-46c6-11e8-98e0-ca3ab411ea67.png)

And when I consent, the `email` claim is missing:

![image](https://user-images.githubusercontent.com/25416056/39123791-ea49366c-46c6-11e8-9833-4544761d2b9b.png)

When debugging `ConsentService.BuildViewModelAsync(string, ConsentInputModel)`, `request.ScopesRequested` only contains two scopes, `openid` and `profile`.  It is my understanding that including the `Email` scope in the interactive client should include `email` in the requested scopes.

Please let me know what I am doing wrong.  Thank you.

Update: I tried the same changes with the release version of the Quickstart3 sample and have the same issue; clearly, I am missing something important.

**Comment by brockallen** [comment]
I don't recall if ASP.NET Core 1 had the "GetClaimsFromUserInfo", but that's what it sounds like you need.

**Comment by BM78** [comment]
It does; I tried that and the client's `AlwaysIncludeUserClaimsInIdToken` property.  While these did include the Identity claims from the profile scope/resource (e.g. the nickname and website claims), the email claim is still not included.  

IdentityResources such as Email and Phone is not included in the requested scopes, thus the user is not shown the email and phone number scopes/resources on the consent page.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by bluebaroncanada** [comment]
I think this is what you're looking for:
https://github.com/aspnet/Security/issues/839
