### ISSUE TITLE
Configuration and Operation Stores Web API - Feature Request

### ISSUE THREAD

**Issue by langell** [IdentityServer/IdentityServer4#2261]
Is there a way to have the Config and Operation Stores accessible via a Web API.  We don't want to the database accessible from  the DMZ. So ideally, we could configure the Stores as follows....

.AddConfigurationStore("https://myserver.com/configEndpoint")
.AddOperationalStore("https://myserver.com/operationEndpoint")

The endpoints could implement some known Interface that Identity Server would know how to use.

Thanks

**Comment by brockallen** [comment]
It's possible. You'd need to build it.

**Comment by langell** [comment]
ok Thanks.

After looking at the Code, I guess I could just implement the IClientStore and IPersistantGrandStore and do the backend calls from there.

**Comment by brockallen** [comment]
Yep, that's what you'd need to do.

**Comment by leastprivilege** [comment]
..and an extension method.

Since this is a good idea - please open source it so other can benefit from it.

**Comment by langell** [comment]
Absolutely, I might ask for some guidance on that when I get to a point
where I can release the code.
