### ISSUE TITLE
ClientSecret exceeds the MaxLength value

### ISSUE THREAD

**Issue by adrianiftode** [IdentityServer/IdentityServer4#2264]
Hi,

We are using the Jwts for secret validation and we had an issue with seeding the Clients secrets with EntityFramework.

Some of the certificates have a greater value than 2000 chars so inserting in the database raised an exception.

We added a migration to temporarily fix this by increasing the column max length value.

Thanks,

Adrian

**Comment by LindaLawton** [comment]
[ModelBuilderExtensions.cs#L88](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Extensions/ModelBuilderExtensions.cs#L88)  I am happy to set this to 4000 if everyone agrees MicroSoft Sql Server NVarchar max is 4000 i bereave.   MySql is IIR varchar and can hold a bit more.   Not sure what other databases .Net core entity framework supports yet.

By setting it to 4000 shouldn't hurt anything that I can think of.   We could also consider setting the Description fields to max 4000 as well they seam to be set to 1000.

_Note I haven tested this no idea if there is any limitations in the length over in the Identity server side.  But at this time i cant think of any reason why there would be_

**Comment by brockallen** [comment]
would 4K work for you @adrianiftode ?

**Comment by adrianiftode** [comment]
We used 3K and seemed ok until now. However that code didn't reach the production yet. I think 4k is fine, it really has to be a really big certificate with lots of information to exceed this value.
Thanks. Will you close this?

**Comment by brockallen** [comment]
Ok, I'll make the change and will close this issue once it's done.

**Comment by brockallen** [comment]
ok, done.
