### ISSUE TITLE
ICustomTokenValidator  need ValidateRefreshTokenAsync

### ISSUE THREAD

**Issue by maliming** [IdentityServer/IdentityServer4#2265]
Why ICustomTokenValidator Doesn't Have ValidateRefreshTokenAsync?
If I want to customize the verification, how can I achieve this?

**Comment by brockallen** [comment]
What sort of validation checks are you looking to add?

@leastprivilege -- Would this be a reasonable feature request?

**Comment by leastprivilege** [comment]
Elaborate please.

**Comment by maliming** [comment]
I added SecurityStamp in RefreshToken Claims.
I want to revoke this RefreshToken when SecurityStamp changes.

**Comment by pawepaw** [comment]
any update on that? I understand that it can be also achieved with `ICustomTokenRequestValidator`. Where i can validate token request based on SecurityStamp saved in claims vs SecurityStamp saved in db. 

The other way is to revoke somehow all tokens for subjectId when changing SecurityStamp but according to https://github.com/IdentityServer/IdentityServer4/issues/2308 there is currenty no built in endpoint which does that and it would require creating it manually.

**Comment by leastprivilege** [comment]
no update.

**Comment by maliming** [comment]
The issue should be keep open.

**Comment by leastprivilege** [comment]
We consolidated all refresh token work into the new refresh token service.

**Comment by maliming** [comment]
Thanks @leastprivilege  : )
