### ISSUE TITLE
IdentityServer 3 All in One Authentication 

### ISSUE THREAD

**Issue by sapandeepprimecaretech** [IdentityServer/IdentityServer4#2266]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

I am trying to use Identityserver to authenticate locally , using Active Directory authentication and also with WS- Fedration from ADFS. I posted similar ticket i [#3689.](https://github.com/IdentityServer/IdentityServer3/issues/3689) under Identityserver3 and i was given few samples to look on. 
I tried implementation. But the problem is , either i can use AD or WS Federation authentication or Local Login. 

it shows me Login screen if i have EnableLocalLogin = true or else i have to set it to false to go to Ws Fedrated site for login..

 var authenticationOptions = new AuthenticationOptions()
                                            {
                                                RememberLastUsername = true, 
                                                CookieOptions = cookieOptions, 
                                                **EnableLocalLogin = true,** 
                                                EnableLoginHint = true, 
                                                EnablePostSignOutAutoRedirect = true, 
                                                EnableSignOutPrompt = true, 
                                                InvalidSignInRedirectUrl =
 
                                                IdentityProviders = ConfigureIdentityProviders
                                            };

Does it means IdentityServer doesn't supoort Mixed mode of authentication and either of the mode can work at  a time?

also if i try to create an extra button on Login page , LoginViewModel doesn't show me any property to let me know  that other identityproviders are setup. 

Please suggest some solution . Thanks.
### Relevant parts of the log file

```
<log goes here>
```

**Comment by sapandeepprimecaretech** [comment]
Also i am working on a multi tenant project where i have to access multiple WS Federations for different tenant to validate login along with local login. Please provide some insight to handle multiple identity providers.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
