### ISSUE TITLE
BasicAuthenticationSecretParser does not handle empty client_secret

### ISSUE THREAD

**Issue by TheBels** [IdentityServer/IdentityServer4#2267]
We are on ID4 2.1.2 on Net Core 2.x. We also use Swashbuckle.AspNetCore for swagger documentation. Our setup has only a client_id specified - we are not using client_secret. This all worked fine with Swashbuckle 1.x.

The issue is that I'm upgrading to Swashbuckle 2.4.0 and the client_id and client_secret are now being passed via Authorization Basic header of the form `client_id:client_secret`. This also is fine.. except we have an empty client_secret. Thus the encoded string given to ID4 to parse is `client_id:` And when going into `BasicAuthenticationSecretParser.ParseAsync` it fails when checking for non-empty and non-null client_id and secret fields: https://github.com/IdentityServer/IdentityServer4/blob/becb2206826b1039687b3ec895fad5e1b26ef0c5/src/IdentityServer4/Validation/BasicAuthenticationSecretParser.cs#L97

### Issue / Steps to reproduce the problem

To reproduce: via Postman or similar you may confirm logging in with only x-www-form-urlencoded works fine, e.g.:

![login-success-with-x-www](https://user-images.githubusercontent.com/12475792/39274029-a936469e-48ae-11e8-8b71-2b1453c39305.png)

Further you may confirm that authentication works fine with passing in a dummy secret:

![login-success-with-dummy-secret](https://user-images.githubusercontent.com/12475792/39274044-ba2fb192-48ae-11e8-920f-a7a4e7d17918.png)

However, when omitting the dummy secret, that is encoding the string `my_client_id:`, then a 400 is returned due to the above-mentioned behavior in BasicAuthenticationSecretParser:

![login-fail-with-empty-secret](https://user-images.githubusercontent.com/12475792/39274105-ec52ea2c-48ae-11e8-8773-bbb23c5c92f9.png)

Thus it appears `BasicAuthenticationSecretParser` has a bug with clients without secrets. I searched around and didn't find a SO post nor an Issue raised so perhaps I'm missing something. Anyone have any hints/ideas on what I'm missing here?

**Comment by leastprivilege** [comment]
Looks like it was by design. We can change that.

Do you want to do a PR including test?

**Comment by TheBels** [comment]
Hi @leastprivilege  - thanks for confirming the behavior.

I don't mind taking a look but I wouldn't be able to get to it immediately. But we can certainly keep the ticket open and I (or others if desired) can come back to this.

For now I plan to work around the issue by hiding the client_secret in the web page and providing a default value in the code.

**Comment by AliBazzi** [comment]
@leastprivilege Can I pick this up ?

**Comment by leastprivilege** [comment]
sure. thanks!

**Comment by leastprivilege** [comment]
done
