### ISSUE TITLE
Question: How do I add custom links on the Login page?

### ISSUE THREAD

**Issue by 82949712** [IdentityServer/IdentityServer4#2268]
For example if I would like to add a forgot password link to the login page for a particular client.

**Comment by DotNetPat** [comment]
You could do that by getting the clientid from the request, pass it on to the login view and do an if that contains your link. If im right...

**Comment by 82949712** [comment]
@DotNetPat  If I get you correctly, I can just check my client id and display information accordingly. But do I need to hard code all these custom links in the IdentityServer? Can these be passed to IS by the client or saved in the client configuration (I don't see any option in the client object though)

**Comment by 82949712** [comment]
@brockallen Yes, I am aware of that. I'm just wondering if there's any standard way of doing this. It would be nice if you could give a very simple example.

**Comment by DotNetPat** [comment]
@82949712 have you tryed extending it by inheritance to add needed properties? I would create a subclass of the client, add the needed properties and in the login view i would try to get this information and display the link if needed.

**Comment by DotNetPat** [comment]
@82949712 As far as i know is IdentityServer just a framework to do SSO using standardized procedures like openidconnect and oauth. it is not a out of the box user management system. so if you already have a system, that should be integrated, you can do that by adding a corresponding client using oauth or openidconnect. in this case the usermanagement you are integrating is responsible for resetting its password. (to keep everything clean). if you want implement a usermanagement system, you should first try the quickstart-sample and step through the login-procedure (http-get) of the account-controller and have a look at its view. This will show you where all the information comes from and the model, that is used by the view. ^^ all you have to do is inserting your corresponding code that fits to your usermanagement-processes. I have looked at the AccountControler class of the quickstart and there is no implementation of a reset process.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
