### ISSUE TITLE
Invalid_grant error with Hybridflow

### ISSUE THREAD

**Issue by FullyCSharped** [IdentityServer/IdentityServer4#2269]
I  have an ASP.NET core 2 MVC app using Identity server 3 with the below configuration 

services.AddAuthentication(sharedOptions =>
                {
                    sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    sharedOptions.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;

                })
                 .AddOpenIdConnect(options =>
                 {
                     options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                     options.Authority = authConfig.GetValue<string>("Authority");
                     options.RequireHttpsMetadata = false;
                     options.ClientId = authConfig.GetValue<string>("ClientId");
                     options.ClientSecret = authConfig.GetValue<string>("ClientSecret");
                     options.ResponseType = "code id_token token";
                     options.SaveTokens = true;
                     options.GetClaimsFromUserInfoEndpoint = false;
                     options.TokenValidationParameters = new
                     TokenValidationParameters
                     {
                         NameClaimType = ClaimTypes.Name,
                         RoleClaimType = ClaimTypes.Role
                     };
                     options.Events = new OpenIdConnectEvents
                     {
                         OnRemoteFailure = context =>
                         {
                             context.HttpContext.Response.Redirect($"/Error?RequestId=4000&errormessage={context.Failure?.Message }");
                             context.HandleResponse();
                             return Task.FromResult(0);
                         },
                         OnRedirectToIdentityProvider = context =>
                         {
                             //TODO: Get IdentityProvider value for Multiple subscribers and not from config
                             var idp = authConfig.GetValue<string>("IdentityProvider");
                             var acrValues = new List<string>();

                             if (!string.IsNullOrWhiteSpace(idp))
                                 acrValues.Add($"idp:{idp}");

                             if (acrValues.Count > 0)
                                 context.ProtocolMessage.AcrValues = string.Join(" ", acrValues);

                             //if (context.ProtocolMessage.RequestType != OpenIdConnectRequestType.Logout)
                             //{
                             //    if (!CurrentEnvironment.IsDevelopment() &&
                             //        context.ProtocolMessage.RequestType == OpenIdConnectRequestType.Authentication)
                             //    {
                             //        // in widget iframe skip prompt login screen
                             //        context.ProtocolMessage.Prompt = "none";
                             //    }
                             //    return Task.FromResult(0);
                             //}

                             var idTokenHint = context.HttpContext.User.FindFirst("id_token");
                             if (idTokenHint != null)
                                 context.ProtocolMessage.IdTokenHint = idTokenHint.Value;

                             return Task.FromResult(0);
                         }
 };
                 options.Scope.Clear();
                 options.Scope.Add("openid");
                 options.Scope.Add("profile");
                 options.Scope.Add("roles");

             })
             .AddCookie("Cookies", o =>
             {

                 o.Cookie.Expiration = TimeSpan.FromMinutes(10);
                 o.Cookie.HttpOnly = true;
                 o.Cookie.Name = "Sample";

             });

And the Client Configuration on Identity server side is as  follows 

   "ClientName": "SampleApp",
    "ClientId": "sample.app.mvc",
    "Flow": 2,
    "RedirectUris": ["https://localhost:44368/signin-oidc","https://sample.azurewebsites.net/signin-oidc"],
    "PostLogoutRedirectUris": ["https://localhost:44368/"],
        "PrefixClientClaims": true,
    "RequireConsent": false,
    "AllowedScopes": 
    [
        "openid",
        "profile",
        "roles",
        "CustomScope"
    ],
    "Claims": [{
        "Type": "subscriberId",
        "Value": "35621957-cb82-4ecc-bce5-836c707d163c"
    }],
"ClientSecrets": [{
        "Secret": "tudc73K2y7pnEjT2"
    }],

    "IdentityTokenLifetime": 300,
    "AccessTokenLifetime": 3600,
    "AuthorizationCodeLifetime": 300,
    "EnableLocalLogin": true
}

I am having an issue with the user login, after I enter the uname and pwd on the idsrv screen and it also posts back to the mvc app, but when using the the authorization code to fetch IdToken and AccesToken i get the error which says "Invalid Authorization code" in the logs 

01:58:30 [45] WARN  Microsoft.Owin.Security.OpenIdConnect.OpenIdConnectAuthenticationMiddleware - The state field is missing or invalid.
01:58:30 [45] INFO  IdentityServer3.Core.Endpoints.TokenEndpointController - Start token request
01:58:30 [45] DEBUG IdentityServer3.Core.Validation.ClientSecretValidator - Start client validation
01:58:30 [45] DEBUG IdentityServer3.Core.Validation.BasicAuthenticationSecretParser - Start parsing Basic Authentication secret
01:58:30 [45] DEBUG IdentityServer3.Core.Validation.PostBodySecretParser - Start parsing for secret in post body
01:58:30 [45] DEBUG IdentityServer3.Core.Validation.SecretParser - Parser found secret: PostBodySecretParser
01:58:30 [45] INFO  IdentityServer3.Core.Validation.SecretParser - Secret id found: 
01:58:30 [45] DEBUG Cache - Cache miss: 
01:58:30 [45] DEBUG IdentityServer3.Core.Validation.SecretValidator - Secret validator success: HashedSharedSecretValidator
01:58:30 [45] INFO  IdentityServer3.Core.Validation.ClientSecretValidator - Client validation success
01:58:30 [45] INFO  IdentityServer3.Core.Validation.TokenRequestValidator - Start token request validation
01:58:30 [45] INFO  IdentityServer3.Core.Validation.TokenRequestValidator - Start validation of authorization code token request
01:58:30 [45] ERROR IdentityServer3.Core.Validation.TokenRequestValidator - Invalid authorization code: 90611b4feec82c6b63b7b4a29ae4c2e6
 {
  "ClientId": "mvc.hybrid.client",
  "ClientName": "mvc",
  "GrantType": "authorization_code",
  "AuthorizationCode": "90611b4feec82c6b63b7b4a29ae4c2e6",
  "Raw": {
    "client_id": "mvc.hybrid.client",
    "client_secret": "******",
    "code": "90611b4feec82c6b63b7b4a29ae4c2e6",
    "grant_type": "authorization_code",
    "redirect_uri": "https://sameple.azurewebsites.net/signin-oidc"
  }
}
01:58:30 [45] INFO  IdentityServer3.Core.Endpoints.TokenEndpointController - End token request
01:58:30 [45] INFO  IdentityServer3.Core.Results.TokenErrorResult - Returning error: invalid_grant
01:58:46 [164] INFO  IdentityServer3.Core.Endpoints.EndSessionController - Start end session request
01:58:47 [164] INFO  IdentityServer3.Core.Validation.EndSessionRequestValidator - Start end session request validation

**Comment by leastprivilege** [comment]
This is really an IdentityServer3 question - this repo is for IS4 only.

>  Invalid authorization code: 90611b4feec82c6b63b7b4a29ae4c2e6

that being said - that implies the code cannot be found in your data store - often cause by using the in-mem stores combined with load balancing.

**Comment by FullyCSharped** [comment]
@leastprivilege, Thanks 
 
In memory is the problm I think...
Ids in my case is hosted on Azure and has two instances...


Also in the above code I have mentioned cookie expiration duration using cookieauthentication options to 10 mins l...however it isn't working at all.Can you give me some pointers on that please

**Comment by leastprivilege** [comment]
since this is not a bug, you are asking for consulting for the wrong version ;)

read the docs - or

https://identityserver4.readthedocs.io/en/release/intro/support.html
