### ISSUE TITLE
is there anonymous token?

### ISSUE THREAD

**Issue by topfunet** [IdentityServer/IdentityServer4#2270]
i separate my api to two scope "api.admin" and "api.web", and i have a angular app use "api.web" scope.
every controller in "api.web" has Authorize(Policy = "api.web"),so here is the problem:
when user logined in, because there has a access_token and scope, so they can get data.
but for anonymous user there's no access_token and scope, so they can't get data.
is there anonymous token i can use for anonymous user to get a access_token with scope?

**Comment by brockallen** [comment]
Why bother with authentication at all if you allow anonymous?

Anyway, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
