### ISSUE TITLE
AdminUI Custom Database Tables

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4#2271]
As requested, below are the extra properties AdminUI stores for IdentityServer configuration:

### Clients
- **NormalizedClientId**: Used to prevent duplicate ClientId's. Uses ILookupNormalizer from ASP.NET Core Identity implementation [UpperInvariantLookupNormalizer
](https://github.com/aspnet/Identity/blob/dev/src/Core/UpperInvariantLookupNormalizer.cs)
- **NormalizedClientName**
- **Description**
- **Reserved**: Used to prevent records being modified via AdminUI or API

### Resources
- **NormalizedName**
- **Reserved**

**Comment by mikeandersun** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/2274
The two issues request extra properties on Resources.

**Comment by brockallen** [comment]
@scottbrady91 what's the schedule for this work?

**Comment by brockallen** [comment]
ping

**Comment by scottbrady91** [comment]
I'll get a PR done early next week.

**Comment by brockallen** [comment]
BTW, I think we'd prefer these in for the preview1 if possible (meaning prior to any updates for device flow, since we decided that will be for preview2).

**Comment by scottbrady91** [comment]
I've just realized that most of these have got unique indexes.

The only way I can see to get around this is to bring the normalization stuff into IdentityServer/the EF repo, or to get rid of the indexes. Both will be awkward for both existing IdentityServer or AdminUI users.

Let me know what you think.

**Comment by brockallen** [comment]
Perhaps AdminUI should treat the ClientId and ResourceName as the normalized values?

**Comment by scottbrady91** [comment]
I'm not against that; the whole normalization thing was a non-starter as you saw. But unfortunately, I'm not going to be able to discuss it with anyone before preview1.

**Comment by scottbrady91** [comment]
Happy to wait or do you want the reserved & description stuff anyway?

**Comment by brockallen** [comment]
description should be in there already.

**Comment by brockallen** [comment]
i'm ok to wait on the rest

**Comment by brockallen** [comment]
Also, for reserved -- can't that go into the properties table? Seems like a good place without needing a schema change.

**Comment by scottbrady91** [comment]
https://github.com/IdentityServer/IdentityServer4.EntityFramework.Storage/pull/2

**Comment by brockallen** [comment]
Merged.
