### ISSUE TITLE
Add a PublicUrl to ApiResource .

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4#2274]
I need to give some public information about my API to developers. 
I think with having a property (e.g `PublicUrl`,...) I can do this.
Thanks

**Comment by brockallen** [comment]
Can you elaborate?

**Comment by mikeandersun** [comment]
Please look at google developer console. In there there are many APIs that we can add them to client . 
The Apis have many information when we click on one of them .
 With having some fields on ApiResource  I can link the developer to an internal or external page to get mode info about the api (e.g api price , api usage , ...) .
sorry for my bad english :)

**Comment by brockallen** [comment]
I think this issue would provide you what you need: #2249. If so, then I'd close this as a dup.

**Comment by mikeandersun** [comment]
This is duplicate of #2249 
I close this and follow that.
