### ISSUE TITLE
Identity server 4 Refresh token issue

### ISSUE THREAD

**Issue by Muraliapm** [IdentityServer/IdentityServer4#2276]
Hi,

I am implementing my own identity server and could you please help me how to get refresh token. I am using HybridAndClientCredentials gran type and not able to get refresh token. I am able to get only access token. Please see my sample code,
![image](https://user-images.githubusercontent.com/23413513/39361655-1217bd58-4a41-11e8-86fb-2c34a7cb1c3e.png)
![image](https://user-images.githubusercontent.com/23413513/39361661-15f413fe-4a41-11e8-8b5d-39b0cc69a629.png)
![image](https://user-images.githubusercontent.com/23413513/39361665-1a2ad7b4-4a41-11e8-9fa0-3cb85015056f.png)

Please let me know how to get refresh token using hybrid flow?.

Thanks,
Murali

**Comment by brockallen** [comment]
You didn't request offline_access, but that's moot anyway -- client_credentials clients don't need refresh tokens since you have the original client_id and client_secret.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by Muraliapm** [comment]
Thanks Brock!!

**Comment by kuldeepchopradotnet** [comment]
https://stackoverflow.com/questions/31385593/identity-server-not-returning-refresh-token/59190556#59190556
