### ISSUE TITLE
Identity server 4 issue

### ISSUE THREAD

**Issue by Muraliapm** [IdentityServer/IdentityServer4#2277]
I have implemented IS4 and using it for my Core 2.0 API and Angular Core web app. I set my AccessTokenLifetime as 2 mints, once access token is expired, I have to get another accesstoken from IS4 using refresh token. But I dont want to use Resource Owner Password Flow. I am using Hybrid flow to get refresh token. 

Also, I want to implement the below things using IS4. Could you please provide some working samples?
1. Single Sign On
2. Two Factor Authentication 

Thanks,
Murali.C

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
