### ISSUE TITLE
Can't implement single log out scenario with End Session Endpoint

### ISSUE THREAD

**Issue by ddydeveloper** [IdentityServer/IdentityServer4#2278]
I have followed sctructure:
1. IdentityServer
2. WebAPI
3. MVC manager app, call it MVC_1 to simplify
4. MVC admin app - MVC_2

I want to ensure all client apps should be logged out if at least one of them initiate log out action. According to documentation: http://docs.identityserver.io/en/release/endpoints/endsession.html#refendsession

I've implemented a log out action in a client controller with followed code: 

        `[AllowAnonymous]
        public async Task Logout()
        {
            var idToken = await HttpContext.GetTokenAsync("id_token");
            
            var discoveryClient = await (new DiscoveryClient(_identitySettings.Authority)).GetAsync();
            var endSessionUrl = $"{discoveryClient.EndSessionEndpoint}?{Constants.IdentityTokenName}_hint={idToken}&post_logout_redirect_uri={HttpContext.Request.Scheme}://{HttpContext.Request.Host}/signout-callback-oidc";

            Redirect(endSessionUrl);
        }`

After this I expected that all clients, and the especially the initiator one should be re-authenticated. But if fact it just cleaned IS cookies: 

![image](https://user-images.githubusercontent.com/28873881/39395366-84f7f266-4ae6-11e8-90d0-beafaaa83430.png)

My client apps cookies still active and can be used.  Maybe I have a wrong configuration, but it looks right. I could clear all cookies on the IS log out action but it would be workaround. The IS provides really useful features to do it. 

And one more think, for the client apps I used custom Cookies Scheme, like "MVC_1_Cookies" and "MVC_2_Cookies" to ensure the simultanious working with the tokens and renew mechanism. When I used default "cookie", the last active app overrided cookies .AspNetCore.Cookies and the second one couldn't get tokens.

Added configuration to help you be a little bit familiar with my implementation 

IS: 

        `internal static IEnumerable<Client> GetClients(IEnumerable<RegisteredClient> clients)
        {
            return clients.Select(x =>
            {
                var scopes = x.AllowedScopes.ToList();
                scopes.Add(IdentityServerConstants.StandardScopes.OpenId);
                scopes.Add(IdentityServerConstants.StandardScopes.Profile);
                scopes.Add("offline_access");
                scopes.Add("roles");

                var client = new Client
                {
                    ClientId = x.Id,
                    ClientName = x.Name,
                    AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,
                    RequireConsent = false,
                    ClientSecrets = { new Secret(x.Secret.Sha256())},

                    RedirectUris = {$"{x.Url}/signin-oidc"},
                    PostLogoutRedirectUris = {$"{x.Url}/signout-callback-oidc"},
                    BackChannelLogoutUri = $"{x.Url}/Account/forcelogout",

                    AllowedScopes = scopes,
                    AllowOfflineAccess = true,
                    AllowedCorsOrigins = {x.Url },
                    AlwaysIncludeUserClaimsInIdToken = true,
                    RefreshTokenUsage = TokenUsage.ReUse
                };

                return client;
            });
        }`

MVC_1:

        `public void ConfigureServices(IServiceCollection services)
        {
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            
            services.Configure<IdentitySettings>(Configuration.GetSection(nameof(IdentitySettings)));
            var identitySettings = services.BuildServiceProvider().GetService<IOptions<IdentitySettings>>().Value;
            
            services.AddAuthentication(options =>
                {
                    options.DefaultScheme = "MVC_1_Cookies";
                    options.DefaultChallengeScheme = Constants.OidcScheme;
                })
                .AddCookie("MVC_1_Cookies")
                .AddOpenIdConnect(Constants.OidcScheme, options =>
                {
                    options.SignInScheme = "MVC_1_Cookies";
                    options.Authority = identitySettings.Authority;

                    options.RequireHttpsMetadata = false;

                    options.ClientId = identitySettings.Id;
                    options.ClientSecret = identitySettings.Secret;
                    options.ResponseType = "code id_token";

                    options.SaveTokens = true;
                    options.GetClaimsFromUserInfoEndpoint = true;

                    options.TokenValidationParameters.NameClaimType = "name";
                    options.TokenValidationParameters.RoleClaimType = "role";

                    options.Scope.Add("roles");
                    options.Scope.Add("offline_access");
                    foreach (var scopeName in identitySettings.Scopes.Select(x => x.Name))
                    {
                        options.Scope.Add(scopeName);
                    }
                });
        }`

MVC_2:

`public void ConfigureServices(IServiceCollection services)
        {
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            services.Configure<IdentitySettings>(Configuration.GetSection(nameof(IdentitySettings)));
            var identitySettings = services.BuildServiceProvider().GetService<IOptions<IdentitySettings>>().Value;
            
            services.AddAuthentication(options =>
                {
                    options.DefaultScheme = "MVC_2_Cookies";
                    options.DefaultChallengeScheme = Constants.OidcScheme;
                })
                .AddCookie("MVC_2_Cookies")
                .AddOpenIdConnect(Constants.OidcScheme, options =>
                {
                    options.SignInScheme = "MVC_2_Cookies";
                    options.Authority = identitySettings.Authority;

                    options.RequireHttpsMetadata = false;

                    options.ClientId = identitySettings.Id;
                    options.ClientSecret = identitySettings.Secret;

                    options.ResponseType = "code id_token";

                    options.SaveTokens = true;
                    options.GetClaimsFromUserInfoEndpoint = true;

                    options.TokenValidationParameters.NameClaimType = "name";
                    options.TokenValidationParameters.RoleClaimType = "role";

                    options.Scope.Add("roles");
                    options.Scope.Add("offline_access");
                    foreach (var scopeName in identitySettings.Scopes.Select(x => x.Name))
                    {
                        options.Scope.Add(scopeName);
                    }
                });
        }`
  
Will be grateful for your help!

**Comment by brockallen** [comment]
Are you actually implementing this endpoint in your MVC apps?

`BackChannelLogoutUri = $"{x.Url}/Account/forcelogout",`

The Microsoft `AddOpenIdConnect` handler does not do it for you.

**Comment by ddydeveloper** [comment]
@brockallen yes, I've add the ForceLogout action to each client and add the option to the configuration:

       `[HttpGet("[action]")]
        public async Task ForceLogout()
        {
            await HttpContext.SignOutAsync(_identitySettings.CookiesScheme);
            await HttpContext.SignOutAsync(Constants.OidcScheme);
        }`

       `BackChannelLogoutUri = $"{x.Url}/Account/ForceLogout"`

**Comment by ddydeveloper** [comment]
I've solve the problem with the ForceLogout action after reading more documentation. especially about <iframe> on the logput page. But I've got another one. Maybe it us because of misunderstanding of the right logout flow.

Now I've implemented the followed:
1. Added <iframe> with SignOutIframeUrl:

    `
 <iframe width="0" height="0" class="signout" src="@Model.SignOutIframeUrl"></iframe>
    `

2. Added the ForceLogout action for the each client which must be notified about logout:

`
        [HttpPost("[action]")]
        public async Task ForceLogout()
        {
            await HttpContext.SignOutAsync(_identitySettings.CookiesScheme);
        }
`

3. Added an option BackChannelLogoutUri as a ForceLogout endpoint:

    `
BackChannelLogoutUri = $"{x.Url}/Account/ForceLogout"
    `

4. Implemented the Identoty Server Logout action:

    `
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Logout(string logoutId)
        {
            var logout = await _interaction.GetLogoutContextAsync(logoutId);
            var vm = new LoggedOutViewModel
            {
                AutomaticRedirectAfterSignOut = false,
                PostLogoutRedirectUri = logout?.PostLogoutRedirectUri,
                ClientName = logout?.ClientId,
                SignOutIframeUrl = logout?.SignOutIFrameUrl,
                LogoutId = logoutId
            };

            await _signInManager.SignOutAsync();
            _logger.LogInformation("User logged out.");

            return View("LoggedOut", vm);
        }
    `

But .AspNetCore_clientId_Cookies still was not cleared; I use custom cookies scheme for each client, e.g.
"Client1_Cookies", "Client2_Cookies" and use them in ForceLogout action. But it does not works, I still have app cookies:

![image](https://user-images.githubusercontent.com/28873881/39572610-87120b7c-4ed8-11e8-91cb-ccc05c58c7ea.png)

Maybe I shouldn't use SignOutAsync extension method and clear them in other way?

**Comment by ddydeveloper** [comment]
@brockallen Do you have an example of the Single Log Out implementation with BackChannelLogoutUri? 

I think it would be very useful, cause, unfortunately, I didn't find something in QuickStartExamples, SO or somewhere else.

**Comment by brockallen** [comment]
> @brockallen Do you have an example of the Single Log Out implementation with BackChannelLogoutUri?

https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients/src/MvcHybridBackChannel

**Comment by ddydeveloper** [comment]
@brockallen Thank you! I am going to investigate it in the nearest time!

**Comment by ddydeveloper** [comment]
@brockallen Thank you. I've implemented BackChannelLogoutUri, it works as expected. Close the issue.

**Comment by Tigro90** [comment]
Would be nice if possible to see how you solved it. Unfortunately the link from @brockallen doesn't work anymore and it seems it contained the solution to this problem. Is it possible to see this example of Single Sign Out with BackChannelLogoutUri ? Thanks in advance!

**Comment by Tigro90** [comment]
For helping to understand what's going on behind the scene: https://blog.tretainfotech.com/posts/2018/august/single-sign-out-in-identityserver4-with-back-channel-logout/
