### ISSUE TITLE
Weird interaction behaviour when signing in.

### ISSUE THREAD

**Issue by Lutando** [IdentityServer/IdentityServer4#228]
I have a project that is almost identical to the [Host](https://github.com/IdentityServer/IdentityServer4/tree/dev/src/Host) project in this repository

However In my sample when I try to initiate implicit flow I get a mis-constructed redirect from the middleware. that looks sort of like this 

`http://localhost:5000/connect/login?returnUrl=http%3A%2F%2Flocalhost%3A5000%2Fconnect%2Fauthorize%2Flogin%3Fclient_id%3Dim...`

for some reason its trying to route me to a controller/endpoint where the base route is `/connect`

There is hardly any noticeable difference in configuration between my project [here](https://github.com/Lutando/SignInInteraction) and the host project linked above

Repro steps
1) Get project as linked in this issue [here](https://github.com/Lutando/SignInInteraction).
2) Run an implicit client like [this one](https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient).
2.1) Change `app.js` settings to the following:

- `authority: "http://localhost:5000",`
- `client_id: "implicit_client",`
- `scope: "openid api1",`

3) Run both solutions and try and login from the implicit client, and you will receive an odd redirect as mentioned above.

**Comment by Lutando** [comment]
OK. well I found out the issue. The `UserInteractionOptions.*`  specified in the options builder has to have a leading slash or you will run into the issue as described above.

**Comment by Lutando** [comment]
I guess a bug fix would be to `EnsureLeadingSlash()` on `set;`

**Comment by brockallen** [comment]
Yea, we'll figure something out. thanks for the report.

**Comment by brockallen** [comment]
I think we will solve this via documentation. For now this was done in code comments, but when the proper documentation is written it will also be included in there. Thanks.
