### ISSUE TITLE
Client missing description while EF Client has it.

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#2280]
The model in Ids4 [Client.cs](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Models/Client.cs)   does not appear to contain a description property of the client.  However the entity framework model [Client.cs](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Entities/Client.cs) does contain a field called description.

>public string Description { get; set; }

I am a bit new to Entity framework so not really sure if this is a bug or if I am doing something wrong.   Shouldn't the client object in Ids4 contain all the properties available in the database from EF?  or am I missing something.

**Comment by LindaLawton** [comment]
I am on it only took me five minutes to add it.   Just trying to wrap my head around your test application in here so that i can force it to come with the consent screen with the added description on it.   

If i can get it tested i can submit a pull request and save you the time.

**Comment by brockallen** [comment]
Thanks for this -- I think we didn't understand where you had meant, which is mostly in the UI.

**Comment by brockallen** [comment]
I finally had a real look at the PR. Basically you're looking for the description to be used in IS somehow... the description in the EF layer is meant for any custom admin UI. not necessarily for IS. I guess the only interesting place would be on the consent screen. Is that the main driver for this issue request?

**Comment by brockallen** [comment]
done

**Comment by LindaLawton** [comment]
yup our third parties need description on the consent screen.

thanks

**Comment by brockallen** [comment]
ok, then perhaps we can try to re-apply the PR to the new structure. of you can always just do it in your UI.

**Comment by LindaLawton** [comment]
the problem is simple the field exists in ef it doesn't not exist in the ids datamodel.  why exactly would the datamodel not include all values available in ef.   if you don't want description why was it added in the ef? 

I can't just add it to the ui it doesn't exist.   I applied that pr three months ago because we needed it in production asap I told management it would be in the next release as I personally submitted a pr.   

are we talking about waiting another three months for you to review and reject another one of my prs?   I am on vacation for another two weeks and won't be able to submit anything anyway.

**Comment by brockallen** [comment]
We're actively working on 2.3 given that we have time now. 3 months ago we were't. If you're on holiday, I'd not bother and enjoy the time off instead.
