### ISSUE TITLE
ConsentDeniedEvent and GrantsRevokedEvent is missing in GrantsController

### ISSUE THREAD

**Issue by tishansoft** [IdentityServer/IdentityServer4#2281]
Hi 

I am trying to follow through this article to understand how identityserver4 works.  I am trying to add the mvc client. As per the instruction, I downloaded the assets and controllers.

ConsentDeniedEvent and GrantsRevokedEvent seems missing. Can some one suggest me where can I find them?

Thanks

**Comment by SIkebe** [comment]
Those events were added to Identityserver4 v2.2.
https://github.com/IdentityServer/IdentityServer4/pull/2199

**Comment by tishansoft** [comment]
Thank You, it worked. You saved lot of time.!!!!
