### ISSUE TITLE
Consider more metadata for clients and resources

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#2285]
resources: created, updated
clients: created, updated, last access

**Comment by leastprivilege** [comment]
This has of course implications - because to maintain those values (e.g. client last access) we would need write access to the config store.

**Comment by brockallen** [comment]
which of these do we want tin 2.3?

**Comment by leastprivilege** [comment]
all of them - some are useful for admin interfaces. 

client last access is something I heard a couple of times - we don't have to use it internally - but that timestamp could easily be set in an ext. point.

**Comment by brockallen** [comment]
ok, done. also added LastAccessed to APiResource if the desire is to track last client/api authentication (think introspection). 

do we also want a LastAccessed on the secret table?
