### ISSUE TITLE
Parameter `session_state` not being returned for failed auth requests

### ISSUE THREAD

**Issue by aryzing** [IdentityServer/IdentityServer4#2287]
We're currently using Identity Server with the [session management extension](http://openid.net/specs/openid-connect-session-1_0.html) enabled. When the user successfully logs in, `session_state` is present in the 302 redirection when using the `code` flow. However, if the auth fails, as per [spec](http://openid.net/specs/openid-connect-session-1_0.html#RPiframe),

> Session state SHOULD be returned upon an authentication failure.

but it is not being returned, 

This is causing unexpected behavior in the RP iframe since it can't send a session state value to the OP iframe for it to calculate any state changes.

Could this be a config issue on our side, or is ISv4 simply not returning `session_state` when the Auth fails (despite having the session extension enabled)?

**Comment by brockallen** [comment]
session_state is different than the state param. are you confusing those? also, if there's an error for most scenarios we don't redirect back to the client, due to guidance issued after the OAuth2/OIDC specs were finalized: https://tools.ietf.org/html/draft-ietf-oauth-closing-redirectors-00

**Comment by brockallen** [comment]
Ok, I went back and checked that section in the spec. To be honest it's not clear to me what that sentence means. If authentication fails, you'd not have a session, so how would you have a session state to return.

Also, oidc-client.js already implement this for you (https://github.com/IdentityModel/oidc-client-js/), so not sure you need to do all this work yourself.

**Comment by brockallen** [comment]
> Anyhow, I have looked into oidc-client.js, however, as far as I can tell, it only supports a getUser method that attempts to authenticate the user once when called.

There's a lot more to it than that, and it automatically handles check session for you, including creating the iframe, polling, and re-requesting authorization w/ prompt=none if the response is changed. Also, it provides an event to let you know if the user's session has changed at the OP. In short, if you didn't want to implement it yourself then it's already all done and packaged for you already.

**Comment by brockallen** [comment]
> Session state is just a function of the client id, origin, and perhaps the End-User's auth state.

We don't have a session state for anonymous users. That one-liner in the session mgmt spec certainly was not clear enough (for me at least) to consider returning one for anonymous users (especially given that it's in the RP Iframe section... *shrug*). 

Anyway, we can consider it. It'd not be too difficult. Again, though, the absence of one certainly tells your client that you need to re-auth the user, right?

**Comment by brockallen** [comment]
Ok, I see your point. So the anon session state will change once authenticated.

But if the client has no user, I guess I don't see the use case of polling check_session to then know that they're authenticated. What's what use case, or what kind of app are you building where that's needed?

**Comment by aryzing** [comment]
For example, it's not uncommon for, what is perceived as a single app, to be in fact powered by many "smaller" apps, each with their own codebase. However, all using a single Authorization Server.

Say that each app is under

```
app1.example.com
app2.example.com
...
```

if a user logs in from `app1.example.com`, it would be nice to have `app2` react accordingly (say, display that user's username or something).

In the case were a tab to `app2` was already open, I would expect that, because the RP iframe from app2 is polling the same `checksession` OP iframe, it would be informed that there has been a change, and react accordingly, fetching the user's credentials.

**Comment by brockallen** [comment]
I guess I'm still confused. Why wouldn't the app just trigger authorize and get the user logged in? Or is it more that app2 just wants to allow the user to stay anonymous until it detects they have logged in (presumably in another tab)?

**Comment by aryzing** [comment]
> app2 just wants to allow the user to stay anonymous until it detects they have logged in 

Correct. app2 may have public and private routes, but the public routes' UI may be decorated differently if they detect that the user has authenticated (eg. display "Sign In" vs "Hi Alice!" in a navbar for a FAQ page)

**Comment by brockallen** [comment]
Ok, got it.

**Comment by aryzing** [comment]
Closing down, feature request in #2289
