### ISSUE TITLE
Reference Token validation endpoint

### ISSUE THREAD

**Issue by valeriob** [IdentityServer/IdentityServer4#2288]
Hi,
i'm using IdentityServer3.AccessTokenValidation to connect to a ids4, because it should be backward compatible.
I configured a client with reference token, but i do not understand where the accesstokenvalidation endpoint is in ids4.
Looking at the code in ids3 it should be at "connect/accesstokenvalidation" but ids4 returns 404.

![image](https://user-images.githubusercontent.com/1522516/39537027-9d0db0c0-4e38-11e8-9b2c-df88ec2a18b7.png)

What is wrong ?

**Comment by brockallen** [comment]
We use introspection now. The access token validation endpoint was custom before the intospection spec was finalized.

**Comment by valeriob** [comment]
Thanks for clarifying that, i thought i read that it was compatible with v4.
So this just means i can only use JWT tokens until i upgrade to aspnetcore on the client, correct ?

**Comment by brockallen** [comment]
We deprecated the access token validation endpoint in v2 of IdentityServer3 IIRC.

**Comment by valeriob** [comment]
Ok, it will require some more learning 😄 
thanks for pointing me to the right direction.
