### ISSUE TITLE
Consider returning session_state response param from authorize even for anonymous users

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2289]
#2287

> We're currently using Identity Server with the [session management extension](http://openid.net/specs/openid-connect-session-1_0.html) enabled. When the user successfully logs in, `session_state` is present in the 302 redirection when using the `code` flow. However, if the auth fails, as per [spec](http://openid.net/specs/openid-connect-session-1_0.html#RPiframe),

> Session state SHOULD be returned upon an authentication failure.

**Comment by aryzing** [comment]
By any chance, do you have any idea of when this feature could be implemented or how hard it is to implement? I'm really looking forward to it! I'd even have a stab at it if I felt more confident with my C# skills...

**Comment by brockallen** [comment]
Also, allow session_id cookie name to be changed (prolly based on authN cookie name).

**Comment by brockallen** [comment]
merged
