### ISSUE TITLE
Add an object as input to FindClientByIdAsync method instead of just a string parameter.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4#2290]
I want to get client according to some extra field that I store in my clients table.
By changing signature of the method in `IClientStore `it be more flexible to implementation . 
`Task<Client> FindClientByIdAsync(string clientId);`
to 
`Task<Client> FindClientByIdAsync(Client client)`

**Comment by leastprivilege** [comment]
Why and where would you need that?

**Comment by brockallen** [comment]
>  Task<Client> FindClientByIdAsync(Client client)

Uhh, don't you see the problem with this design? I have to create a Client to get the right Client?

**Comment by mikeandersun** [comment]
@leastprivilege  I needs to query the store with more parameter (e.g `tenantId`,..). I want to have primary key on `clientId `and `tenantId `in the client table.
@brockallen  the parameter is an object to carry out parameter to query the table according the value of it's properties.

**Comment by brockallen** [comment]
What is tenant specific about your client?

**Comment by leastprivilege** [comment]
How would we know about your custom fields then?

You need a custom data access API for that.
