### ISSUE TITLE
Using MongoDB as User Store and Configuration Store

### ISSUE THREAD

**Issue by paulyipkh** [IdentityServer/IdentityServer4#2291]
I am converting my configuration store and user store from MSSQL to Mongo.

First of all, I converted the configuration store to MongoDB using IdentityServer4.Contrib.MongoDB
https://github.com/diogodamiani/IdentityServer4.Contrib.MongoDB
This step works and everything goes fine.

Then, I converted the user store and role store to MongoDB.
My first attempt is alextochetto/aspnetcore-identity-mongodb
https://github.com/alextochetto/aspnetcore-identity-mongodb
The data migration is done and the angular client can log on successfully but  the method of GetProfileDataAsync of my CustomProfileService is not called and I missed the role and custom claims.
The ServiceCollection was registered correctly IProfileService => CustomProfileService  and confirmed with unit test.

Then I start everything all over again using 
AspNetCore.Identity.MongoDbCore
https://www.nuget.org/packages/AspNetCore.Identity.MongoDbCore/

The same problem persists.
All three pieces IdentityServer, IdentityStore, ConfigurationStore worked separately with the only problem GetProfileDataAsync not being called.

My client is an angular client using oidc and implicit flow
client_id: 'spa',
scope: 'openid profile api',
response_type: 'id_token token',
filterProtocolClaims: true,
loadUserInfo: true,

Do you know any reference implementation that I can learn from ?
Thanks a lot.

**Comment by brockallen** [comment]
> Do you know any reference implementation that I can learn from ?

No, sorry.

**Comment by paulyipkh** [comment]
Thanks
