### ISSUE TITLE
Client credentials flow with no scopes breaks after implicit flow set up

### ISSUE THREAD

**Issue by maximpashuk** [IdentityServer/IdentityServer4#2295]
Using IdentityServer 2.1.3, but I think 2.2 also affected.

Imagine the situation:
1. Client set up client_credentials flow, client provide **no scopes** to get OAuth token for API access. By default it get all available scopes that set up in IdentityServer, and it is fine.
2. Additionaly client set up implicit flow for OpenIdConnect authentication with scopes "openid", "profile". Users of that client can successfully authenticate.

But BAM: first scenario with client_credentials starts failing with error **"cannot request OpenID scopes in client credentials flow"**.

If client specify scopes explicitly for first scenario, then all the things start work fine again.
But I think that **adding new grant type should not break previous grant types**.

Practically, I think then client specify no scope in token request, all available scopes for client should be filtered by grant_type.

P.S. I found issues like mine, for example in #632 and #1474, but only recommendation I found is to explicitly specify claims in client_credentials.

**Comment by LindaLawton** [comment]
IIR the client_credentials flow is not meant to be used for server to server communication.  In this scenario there is no end user to identify. The client_credentials grant type is undefined in OpenID Connect.  

There for the open id scopes will not work for it as its not a real user.

**Comment by leastprivilege** [comment]
IOW - in the client creds flow scenario with no scopes specified, we should filter out identity scopes... @brockallen

**Comment by LindaLawton** [comment]
Verified

     var disco = await DiscoveryClient.GetAsync("http://localhost:5000");
     var tokenClient = new TokenClient(disco.TokenEndpoint, "ef2e55b8-dab8-4a7b-9f7e-5ce4351803ca.xena.biz", "1f0ec2de-3e57-4f64-abca-4f1ff725ab10");
      var fields = new Dictionary<string, string>
            {
                { "grant_type", "client_credentials" }
            };

        //fields.Add("scope", "testapi");
        var tokenRespone = await tokenClient.RequestAsync(fields, CancellationToken.None);

Results in:

> fail: IdentityServer4.Validation.TokenRequestValidator[0]
>       ef2e55b8-dab8-4a7b-9f7e-5ce4351803ca.xena.biz cannot request OpenID scopes in client credentials flow
> fail: IdentityServer4.Validation.TokenRequestValidator[0]
>       {
>         "ClientId": "ef2e55b8-dab8-4a7b-9f7e-5ce4351803ca.xena.biz",
>         "ClientName": "Client Credentials",
>         "GrantType": "client_credentials",
>         "Scopes": "openid profile testapi",
>         "Raw": {
>           "grant_type": "client_credentials"
>         }
>       }

Clinet in question has the following scopes set up 

```
Id	ClientId	Scope
36	25	openid
37	25	profile
38	25	testapi

```

**Comment by leastprivilege** [comment]
yes I know ;)

**Comment by LindaLawton** [comment]
I know you know but you know i had to test it myself :)    Started a huge conversation about client_credentials flow between me and my coworkers was quite fun.

Are you going to fix i was going to do a bit of digging.    I love using my 20% time on this project

**Comment by brockallen** [comment]
If you want to suggest a PR to address the issue, then I'm happy to review it.

**Comment by leastprivilege** [comment]
will go into 2.3
