### ISSUE TITLE
Correlation error for MVC .net Core App while redirect to .net App 

### ISSUE THREAD

**Issue by EmilyGermanotta** [IdentityServer/IdentityServer4#2296]
I had the scenario here was like, for the MVC .net core project, i am using Azure Active Directory and openIdConnect, everything seems fine. So for my old project, written in .net, i had make a link for it to redirect user to MVC .net core project. After I was landed to the MVC .net core App then i press the back button, i can't return to my old .net app, instead, it came out the error regarding Correlation error. What is happening? It happens quite frequent, when i press the back button to return to old .net app. 
I can't figured out why? I had read some article, I assume this was caused by the cookies or token where issued to MVC .net App at the first place and there is something gone wrong in the middle, so when i press back button to the old .net App, the cookies or token was expired? Am i predicted correctly?

the error looks like this 
![image001](https://user-images.githubusercontent.com/29965379/39621741-59dbd3be-4fc2-11e8-8c5a-6bb6e9b4cd2a.png)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
