### ISSUE TITLE
Extract JWT payload creation to extension method

### ISSUE THREAD

**Issue by shaikatz** [IdentityServer/IdentityServer4#2299]
On IDSrv3 all JWT payload creation logic moved to extension method to ease the process of overriding TokenService. 
We need to override TokenService so we can sign the token with azure KeyVault.

This is the [relevant commit from IDSrv3](https://github.com/IdentityServer/IdentityServer3/commit/dd07bd88f64b437b2c261cc76c71917ec5a0eb03)

I can open a PR if needed.

Thanks
Shai

**Comment by brockallen** [comment]
>  We need to override TokenService so we can sign the token with azure KeyVault.

Is the plan to really send every token signing request to keyvault? What volume are you expecting?

**Comment by shaikatz** [comment]
Yes, and we have high load but we want to use HSM because those are highly sensitive keys - and this is why we are using key vault.

**Comment by leastprivilege** [comment]
That's a good idea. I will add that.
