### ISSUE TITLE
IS4 HttpContext.GetTokenAsync("refresh_token") always returns null

### ISSUE THREAD

**Issue by dresdor** [IdentityServer/IdentityServer4#2301]
### Issue / Steps to reproduce the problem
We are having an issue where we are unable to retrieve the refresh token to refresh our access token.  When we make the call:

     HttpContext.GetTokenAsync("refresh_token")

it always returns null.  We are currently retrieving our access token by the following code:

     var curToken = filterContext.HttpContext.AuthenticateAsync("oidc").Result;
     var tok = curToken.Properties.Items[".Token.id_token"];

which successfully retrieves the token.  There's nothing in the AuthenticateAsync response that resembles the refresh token (though the expiration times that are in there are much longer than what the access token should have, and indeed does have after being decode by jwt.io).

This is what the relevant client looks like:
![Client](https://i.stack.imgur.com/R1mxi.png)

I'm not sure if there's some configuration that has been missed, or if there's an issue with our call, but in either case we are not able to retrieve the token.  

EDIT: Reading further on the grant types (something I had not considered) it looks like renew is not allowed in implicit grant.  If I switch this to hybrid grant, is that the best way to resolve this issue for supporting an angular front-end backed by .NET security?

**Comment by brockallen** [comment]
Is the client requesting the offline_access scope?

**Comment by dresdor** [comment]
Issue largely resolved due to some massive reworking of scopes and other bits.  Problem I have now is that User Principal does not seem to have most of the custom claims we have established.

Identity Server:
![image](https://user-images.githubusercontent.com/33524074/39760670-92b0b3ea-529b-11e8-85e5-9e74aea4cfc8.png)

Client:
![image](https://user-images.githubusercontent.com/33524074/39760722-b8403644-529b-11e8-89a9-68b5754c7fa7.png)

When we use our token against the APIs, the only claims information that is pulled is:
nbf
exp
iss
aud
nonce
iat
at_hash
sid
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier
auth_time
http://schemas.microsoft.com/identity/claims/identityprovider
http://schemas.microsoft.com/claims/authnmethodsreferences


We are not getting any of our custom claims, like user's friendly name or userid which we use in several important calls.  They were working before switching from implicit to hybrid

**Comment by dresdor** [comment]
I've resolved this by implementing a custom IProfileService, and am now getting a similar set of claims back.  However, I'm still not sure how on earth it was working with Implicit and still sending those claims.  Not going to worry too much about it though.
