### ISSUE TITLE
Identity Server with asp.core 2.1 

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#2302]
Do you foresee any challenges or unforeseen issues using current version of identity server 4 with asp.core 2.1 ? 
Thanks

**Comment by leastprivilege** [comment]
I don't see any unforeseen issues right now ;)

**Comment by damienbod** [comment]
@satyajit-behera @leastprivilege 

I tried this, and have no issues with the IdentityServer4. The Identity part has changed a lot and the samples, Identity part needs a bit of work.

**Comment by satyajit-behera** [comment]
Thanks @leastprivilege

**Comment by satyajit-behera** [comment]
@damienbod I guess, you moved from IdentityServer4 v1 (for .net core 1) to use asp.net core 2.1
And hope, its not needed when we do it for v2 which already works with asp.net core 2.0
