### ISSUE TITLE
IOS 8.1 version support for Fragment

### ISSUE THREAD

**Issue by aqa510415008** [IdentityServer/IdentityServer4#2303]
IOS 8.1 version support for Fragment, after the success of the authorization can not jump, stay at https://auth.xxx.com/connect/authorize/callback?client_id=201802058888&redirect_uri=xxx

```
 private string BuildRedirectUri()
        {
            var uri = Response.RedirectUri;
            var query = Response.ToNameValueCollection().ToQueryString();

            if (Response.Request.ResponseMode == OidcConstants.ResponseModes.Query)
            {
                uri = uri.AddQueryString(query);
            }
            else
            {
                uri = uri.AddHashFragment(query);
            }
            if (Response.IsError && !uri.Contains("#"))
            {
                // https://tools.ietf.org/html/draft-bradley-oauth-open-redirector-00
                uri += "#_=_";
            }
            return uri;
        }
```

**Comment by brockallen** [comment]
Can you explain why it doesn't handle the redirect URI correctly?

**Comment by aqa510415008** [comment]
@brockallen Previous versions of IOS 8 .1 do not support this UIR jump
```
https://auth.xxx.com/#client_id=201802058888 
```
 He only supports
```
https://auth.xxx.com/?client_id=201802058888 
```

**Comment by brockallen** [comment]
So you're saying the request to the authorization endpoint is not working when you send params via the hash fragment?

**Comment by aqa510415008** [comment]
@brockallen  Invalid redirect URL after authorization is successful

**Comment by brockallen** [comment]
That sounds like an environmental issue as IdentityServer simply follows the specs. You need to do some more debugging on your side.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
