### ISSUE TITLE
Feature Request: Allow changing AbsoluteRefreshTokenLifetime for Extension Grants

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2305]
In the spirit of letting me do whatever the hell I want to do in Extension Grants, I would like the ability to mint a token where I have control over everything :)

In this case, I would like to be able to change the AbsoluteRefreshTokenLifetime the same way I can change AccessTokenLifetime in my ValidateAsync function;

i.e. similar to the way I am changing context.Request.AccessTokenLifetime below;  
```
// optional stuff;
var accessTokenLifetimeOverride = _validatedRequest.Raw.Get(Constants.AccessTokenLifetime);
if (!string.IsNullOrWhiteSpace(accessTokenLifetimeOverride))
{
    var accessTokenLifetime = Int32.Parse(accessTokenLifetimeOverride);
    if (accessTokenLifetime > 0 && accessTokenLifetime < context.Request.AccessTokenLifetime)
    {
        context.Request.AccessTokenLifetime = accessTokenLifetime;
    }
    else
    {
        var errorDescription =
            $"{Constants.AccessTokenLifetime} out of range.   Must be > 0 and less than configured AccessTokenLifetime.";
        LogError(errorDescription);
        context.Result = new GrantValidationResult(TokenRequestErrors.InvalidRequest, errorDescription);
        return;
    }
}
```

**Comment by brockallen** [comment]
Right now this is a client config setting, and it's a bit of work to change that. What's your concrete use case.

**Comment by ghstahl** [comment]
I created an extension grant that lets me mint tokens with arbitrary claims.
One of the features I could expose (because the framework let me ) is to pull in the access_token_lifetime from a configured upper limit.

[ref doc](https://p7identityserver4.azurewebsites.net/docs/arbitrary_resource_owner.md)  

I would like the ability to allow my clients to also pull in the AbsoluteRefreshTokenLifetime from an upper configured limit.

```
POST http://localhost:21354/connect/token

Headers:
    Content-Type:application/x-www-form-urlencoded

Body:
    grant_type:arbitrary_resource_owner
    client_id:arbitrary-resource-owner-client
    client_secret:secret
    scope:offline_access metal nitro aggregator_service.read_only
    arbitrary_claims:{ "role": ["application", "limited"],"query":["dashboard", "licensing"],"seatId":["1234abcd"]}
    subject:886bea3f-e025-4ab9-a811-e9b86f563668
    access_token_lifetime:3600
```

**Comment by brockallen** [comment]
so you want the refresh token expiration to be affected by something in the request? and thus the client config in the DB is ignored?

**Comment by ghstahl** [comment]
Kindof. In my case the rule is it cannot be greater than what is configured so not completely ignored.
