### ISSUE TITLE
IdentityServerAuthenticationOptions error

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer4#2307]
Hello, I used identityserver4 as the project's SSO, and I recently wanted to add the api side to the configuration file of appseting.json for IdentityServerAuthenticationOptions. Because I want to implement, I can modify the contents of the configuration file and then switch dynamically
**Authority**
**ApiName**
**ApiSecret**
Without restarting the application

My code is as follows:
`services.Configure<IdentityServerAuthenticationOptions>(Configuration);
  services.AddAuthentication(Bearer).AddIdentityServerAuthentication();`

appseting.json:
`"Authority": "https://xxxxx.com/sso",
  "ApiName": "xxxapi",
  "ApiSecret": "xxx-xxx-xx-xx"`

but the api return error
You must either set Authority or IntrospectionEndpoint

**Comment by brockallen** [comment]
Sorry, this is not supported and would be a massive reworking. It's not even clear if all the underlying components we use from ASP.NET Core support this.

**Comment by BennieCopeland** [comment]
So we can't use `appsettings` to set the `IdentityServerAuthenticationOptions`? How do we handle different environments?
