### ISSUE TITLE
RevokeRefreshTokenAsync doesn't clear out all refresh_tokens that have the same subject/client_id combination

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2308]
### Issue / Steps to reproduce the problem

I am able to mint 2 tokens via Extension Grants that have the same subject.  
Revoking the refresh_token removes the refresh_token, but then doesn't remove all the others that have the same subject.  Looking at the code, it tries to remove all the reference tokens by subjectId/ClientId.

i.e.
```
/// <summary>
/// Revoke refresh token only if it belongs to client doing the request
/// </summary>
protected virtual async Task<bool> RevokeRefreshTokenAsync(TokenRevocationRequestValidationResult validationResult)
{
    var token = await RefreshTokenStore.GetRefreshTokenAsync(validationResult.Token);

    if (token != null)
    {
        if (token.ClientId == validationResult.Client.ClientId)
        {
            Logger.LogDebug("Refresh token revoked");
            await RefreshTokenStore.RemoveRefreshTokenAsync(validationResult.Token);
            await ReferenceTokenStore.RemoveReferenceTokensAsync(token.SubjectId, token.ClientId);
        }
        else
        {
            Logger.LogWarning("Client {clientId} tried to revoke a refresh token belonging to a different client: {clientId}", validationResult.Client.ClientId, token.ClientId);
        }

        return true;
    }

    return false;
}
```

My Unit Test is located [Here..](https://github.com/ghstahl/IdentityServer4-Extension-Grants/blob/master/src/Tests_ExtensionGrants/ArbitraryResourceOwnerTests.cs)  
```
[TestMethod]
public async Task Mint_multi_arbitrary_resource_owner_and_refresh_and_revoke()
{
    ...
}
```

I assume that the call to RemoveReferenceTokensAsync is meant to account for multiples.  
I would think that the following;
```
 await RefreshTokenStore.RemoveRefreshTokenAsync(validationResult.Token);
```
needs to be replaced with a new remove;
```
await ReferenceTokenStore.RemoveRefreshTokensAsync(token.SubjectId, token.ClientId);
```

**Comment by ghstahl** [comment]
I have a workaround that shows how to deal with this until we get the new feature in.   
[workaround](https://github.com/ghstahl/IdentityServer4-Extension-Grants/blob/master/docs/refresh_token_revocation_workaround.md)

**Comment by ghstahl** [comment]
Also, revoking all refresh_tokens with 
```
await ReferenceTokenStore.RemoveRefreshTokensAsync(token.SubjectId, token.ClientId);
```
may not be enough.

I have a situation where I want all tokens removed based on only a subject.
```
await ReferenceTokenStore.RemoveRefreshTokensAsync(token.SubjectId);
```

My use case is as follows;
1. Client logins in and only gets back a token that is scoped to account_only information.  Pretty much all that I usually want from logging into google.
2. Client then using a custom extension_grant mints another token with custom scopes/claims with the login only access_token  being passed in as in the following grant_type;  
```
POST http://localhost:21354/connect/token

Headers:
   Content-Type:application/x-www-form-urlencoded

Body:
   grant_type:arbitrary_oidc_resource_owner
   client_id:arbitrary-resource-owner-client
   client_secret:secret
   scope:offline_access nitro metal
   arbitrary_claims:{"some-guid":"1234abcd","In":"Flames"}
   access_token_lifetime:3600
   access_token:{{token from a previous login}}  
```

I have many client_id(s) in play, all deriving their custom tokens from the original subject.  The subject is the only thing carried forward when clients mint custom tokens.

When a refresh_token gets revoked, all subjects from all clients have to go.

**Comment by jasonycw** [comment]
This is the opposite issue for https://github.com/IdentityServer/IdentityServer4/issues/1315
It changed the behavior of revoke all to only revoke 1 refresh token. 
But it seems that no extra endpoint is added back for the revoke all functionality.

**Comment by klioqc** [comment]
Yes, I think it would be useful to be able to delete all tokens for user
await ReferenceTokenStore.RemoveRefreshTokensAsync(token.SubjectId);

If, for example, refresh tokens are used in native applications and stored on user laptop or phone, and then he lost his device.

**Comment by pawepaw** [comment]
to clarify, currently there is no endpoint which will remove all refresh tokens for specified subjectId and clientId? I see that there is a method in IRefreshTokenStore but it's not used anywehere. 

Currently Token revocation endpoint removes only one specified token. To handle that it'd require us to create custom endpoint, am i right?

**Comment by brockallen** [comment]
> Currently Token revocation endpoint removes only one specified token. To handle that it'd require us to create custom endpoint, am i right?

Yes.
