### ISSUE TITLE
binding to ClientName from the Logout-View?

### ISSUE THREAD

**Issue by riankol** [IdentityServer/IdentityServer4#231]
Thanks a lot for the usefull examples you've provided! I've built an app with identityserver4, using your MVC Hybrid Client example as basis. But I encountered this:
In the LogoutController says the Submit-method:
```
            var logout = await _interaction.GetLogoutContextAsync(logoutId);
            var vm = new LoggedOutViewModel()
            {
                PostLogoutRedirectUri = logout.PostLogoutRedirectUri,
                ClientName = logout.ClientId,
                SignOutIframeUrl = logout.SignOutIFrameUrl
            };
            return View("LoggedOut", vm);
```
I want to bind ClientName to logout.ClientName, as I don't want the id to be displayed in the Logout-View. But logout does not have a ClientName attribute.
Did I miss something anywhere? Or is it impossible to bind to the ClientName from the Logout-view?

**Comment by brockallen** [comment]
I'd suggest that you inject the IClientStore into your controller, and then lookup the Client configuration (and thus the name) from the ClientId passed via the context.

**Comment by brockallen** [comment]
All set on this?
