### ISSUE TITLE
Multiple login scenarios

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer4#2313]
Hello, I'm using your identityserver4 as my sso, this is a very great project, but now there is a problem that has been bothering me. I have 3 ClientA, ClientB, ClientC, all using mixed mode.

Now there is a problem: If I log in to account A on client A, then when I access ClientB, ClientC, it will automatically log in and will not jump to the login screen of SSO because I have logged in to client A. I read your document saying this is the self-certification rule.

But the effect I want now is: When I use A account to log in to client A, and then go to visit ClientB or ClientC, I can still jump to the login interface of SSO normally, so that I can use other accounts to log in.

Because I am now the client A, ClientB, ClientC account of the three systems is actually not universal, I just put it in a table only. How can I solve this problem? These three systems I have docked SSO01, because I want to deploy only a set of SSO. I want multiple systems can share the login interface of sso.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by YINZHU2016** [comment]
i find some answer
https://stackoverflow.com/questions/48681426/identityserver4-force-user-to-re-enter-credentials?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

options.Events.OnRedirectToIdentityProvider = context =>
{
    context.ProtocolMessage.Prompt = "login";
    eturn Task.CompletedTask;
};
