### ISSUE TITLE
Login using popup, <iframe> for Hybrid flow

### ISSUE THREAD

**Issue by YINZHU2016** [IdentityServer/IdentityServer4#2314]
I am having difficulty dealing with an issue: is it possible to implement a login form using Identityserver4 in a popup or a <iframe> ?

Please give me some advice for this issue.
Thanks and Best Regards

**Comment by leastprivilege** [comment]
Our default UI prevents iframing - this is a common security best practice. You can inspect the code in the `SecurityHeaders.cs` file.

**Comment by YINZHU2016** [comment]
@leastprivilege Can you help look at this issue? Thanks and Best Regards
https://github.com/IdentityServer/IdentityServer4/issues/2313

**Comment by brockallen** [comment]
@YINZHU2016 This is up to your UI code. We provide the quickstart, but beyond that you will have to design it to work the way you want.
