### ISSUE TITLE
Authenticating an Outlook Add-in using IdentityServer4 (JWT)

### ISSUE THREAD

**Issue by sajihkiriwendala** [IdentityServer/IdentityServer4#2315]
I want to implement an Outlook Add-In for the user to login through the Outlook desktop application into a web application profile and do their necessary changes through the Outlook desktop application itself.
The authentication needs to be done with Identity Server 4.
Please give me some advice for this issue.
Thanks.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
