### ISSUE TITLE
Adapt SlidingRefreshTokenLifetime to prevent negative lifetimes

### ISSUE THREAD

**Issue by janpieterz** [IdentityServer/IdentityServer4#2317]
When, for example, using an int.MaxValue (a valid configuration value) for SlidingRefreshTokenLifetime, the result of below line can mean the integer becomes a negative value. This is relevant for scenario's with, for example, the AbsoluteRefreshTokenLifetime set to 0 and a Sliding expiration, where people expect them to be valid forever (or at least significantly long enough to not matter).

https://github.com/IdentityServer/IdentityServer4/blob/325ea0e67b1de2c836f26eb38436ff07177028d4/src/IdentityServer4/Services/DefaultRefreshTokenService.cs#L120
 
Example logs for this:
```
New lifetime: -2145103527
Current lifetime: 2380122 
```

```
New lifetime: -2146012154
Current lifetime: 1471495 
```

There's a couple of options here:

1.  Ensure the configuration can never exceed int.MaxValue / 2 when configuring a client (but what about database changes?)
2. Change the processing code to ensure this won't happen (either on load of client settings limit it to int.MaxValue / 2 and log it, or when issuing a new lifetime ensure it doesn't pass it and go negative)
3. Change it to a uint and if exceeding set it to uint.MaxValue
4. Ignore 😄

**Comment by leastprivilege** [comment]
Please contribute here 

https://github.com/IdentityServer/IdentityServer4/issues/2114#issuecomment-379185830

**Comment by janpieterz** [comment]
Super, cheers.
