### ISSUE TITLE
Question: Is there an MVCClient example that uses asp.net identity 

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2319]
I am trying to trigger a logout on IdentityServer4 the same way the MVCClient examples do;
```
MVC Client:
public async Task Logout()
{
    await HttpContext.SignOutAsync("Cookies");
    await HttpContext.SignOutAsync("oidc");
}
```

```
and Mine.
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Logout()
{
    await _signInManager.SignOutAsync();
    _logger.LogInformation("User logged out.");
    return RedirectToPage("/Index");
}
```
My registration with identity is pretty much out the box.
```
var authenticationBuilder = services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = IdentityConstants.ApplicationScheme;
    options.DefaultChallengeScheme = IdentityConstants.ApplicationScheme;
    options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
});


authenticationBuilder.AddOpenIdConnect("oidc", options =>
{
    options.Authority = "http://localhost:5000";
    options.RequireHttpsMetadata = false;

    options.ClientId = "mvc";
    options.SaveTokens = true;
    options.Events.OnRedirectToIdentityProvider = async n =>
    {
        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.Authentication)
        {
            n.ProtocolMessage.AcrValues = "idp=google";
        }
    };
});
```

**Comment by brockallen** [comment]
If your MVC client is using IdentityServer then there's little point in using ASP.NET Identity in the MVC app since your MVP app is not managing credentials.

**Comment by ghstahl** [comment]
@brockallen 
I was looking for how OIDC does a redirect to the provider to do the signout.  Since I am using out of the box asp.net identity on my end, I had to do it myself.
https://github.com/IdentityServer/IdentityServer4/issues/1023
[endsession](https://identityserver4.readthedocs.io/en/release/endpoints/endsession.html)

The following is my SignOut that cooks up an endsession url to sign everyone else out;  
```
public async Task<IActionResult> OnGetAsync()
{
    var clientSignoutCallback = $"{Request.Scheme}://{Request.Host}/Account/SignoutCallbackOidc";
    // Get id_token first to seed the iframe logout
    var user = await _signInManager.UserManager.GetUserAsync(User);
    IdToken = await _signInManager.UserManager.GetAuthenticationTokenAsync(user, "oidc", "id_token");

    var discoveryCache = await _discoverCacheContainer.DiscoveryCache.GetAsync();
    var endSession = discoveryCache.EndSessionEndpoint;
    EndSessionUrl = $"{endSession}?id_token_hint={IdToken}&post_logout_redirect_uri={clientSignoutCallback}";
    
    // no matter what, we are logging out our own app.
    // Do Not trust the provider to keep its end of the bargain to frontchannel sign us out.
    await _signInManager.SignOutAsync();
    _logger.LogInformation("User logged out.");

    // this redirect is to the provider to log everyone else out.  
    // We will get a double hit here, as our $"{Request.Scheme}://{Request.Host}/Account/SignoutFrontChannel";
    // will get hit as well.  
    return new RedirectResult(EndSessionUrl);
}
```

BTW: I get you point on federation_gateway, and am complying to that.  So why would I still be using ASP.NET Identity over on my client?  because I am lazy and its a perfectly good user database, where I only know that user as a GUID.  I don't use Identity here to its fullest.  I remove every type of login it does and only allow a single provider. 2FA, multi-provider linking, account locking is gone.  I rely on the federated gateway to do all that, Just like your MVC Client.  There is AutoProvisioning going on here.

Now unto doing this in a hidden iFrame where I was thinking of added a middleware on the provider to put security headers on everything but the endsession url.  Do you see any security issues with opening  up endsession to being iFramed?

**Comment by brockallen** [comment]
All that code is up to you to design and build. We don't normally provide support beyond the IdentityServer core feature set here on the issue tracker.
