### ISSUE TITLE
IdentityServer in a non-web scenario?

### ISSUE THREAD

**Issue by NKnusperer** [IdentityServer/IdentityServer4#232]
Is IdentityServer feasible for a non-web centric use case?
I have a TCP based service which clients connect to and this service may call an arbitrary number of internal microservices (using a service bus). 
To have an unified identity/authentication platform between all service I tough IdentityServer might be a good choice except that every sample I found is somehow web specific.

Will IdentityServer do the job under this environment?

**Comment by leastprivilege** [comment]
Idsrv is an implementation of OpenID Connect and OAuth 2 - which are both HTTP based.

That said - how you transfer access tokens between the client and the API is up to you. This can be done over arbitrary transports.
