### ISSUE TITLE
Support for Individual Migration History Table IdentityServer4.EntityFramework

### ISSUE THREAD

**Issue by tiwari-abhishek** [IdentityServer/IdentityServer4#2322]
### Issue / Steps to reproduce the problem
I am trying to set a custom MigrationHistoryTable name for the ConfigurationDbContext and PersistentGrantDbContext, but when I run 'dotnet ef database update' the Migration History table name always gets created prefixed with 'dbo_'.

However, this works for AspnetIdentity though and I am able to create a separate MigrationHistory table for that. So I think its a bug? Is there a workaround?

Code I am using for ConfigurationDbContext
```
public class ConfigurationDbContextFactory : IDesignTimeDbContextFactory<ConfigurationDbContext>
    {
        ConfigurationDbContext IDesignTimeDbContextFactory<ConfigurationDbContext>.CreateDbContext(string[] args)
        {
                var optionsBuilder = new DbContextOptionsBuilder<ConfigurationDbContext>();
                optionsBuilder.UseSqlServer(idsSettings.DatabaseSettings.ConnectionString,
                 x => x.MigrationsHistoryTable(Constants.MigrationsHistoryTable, 
                          idsSettings.DatabaseSettings.SchemaName));
                var configStoreOptions = new ConfigurationStoreOptions 
                {
                      DefaultSchema = idsSettings.DatabaseSettings.SchemaName};
                }
               return new ConfigurationDbContext(optionsBuilder.Options,configStoreOptions);         
        }
    }
```
I also tried the below instead, but same results

   ```
return new ConfigurationDbContext(optionsBuilder.Options, new ConfigurationStoreOptions
            {
                ResolveDbContextOptions = (provider, builder) =>
                {
                    optionsBuilder.UseSqlServer(idsSettings.DatabaseSettings.ConnectionString, x => x.MigrationsHistoryTable(Constants.MigrationsHistoryTable, idsSettings.DatabaseSettings.SchemaName));
                },
                DefaultSchema = idsSettings.DatabaseSettings.SchemaName
            });
```

**Code that works for AspnetIdentity**
```
public class UserProfileDbContextFactory : IDesignTimeDbContextFactory<UserProfileDbContext>
    {
        UserProfileDbContext IDesignTimeDbContextFactory<UserProfileDbContext>.CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<UserProfileDbContext>();
            optionsBuilder.UseSqlServer(aspnetIdentitySettings.DatabaseSettings.ConnectionString,
                x => x.MigrationsHistoryTable(Constants.MigrationsHistoryTableName,
                    aspnetIdentitySettings.DatabaseSettings.SchemaName));
            IOptions<AspnetIdentitySettings> options = Options.Create(aspnetIdentitySettings);
            return new UserProfileDbContext(options, optionsBuilder.Options);
        }
    }
```

**Comment by brockallen** [comment]
Not sure -- I never tried to do that. But our EF library is minimally involved -- it's more just a wrapper around the EF config system. You might need to grab the EF project and debug into to figure it out. If you make any progress and you think there's something missing from how we do wrap the EF layer, let us know.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by tiwari-abhishek** [comment]
Yes we can close. I haven't found time yet to debug but since I am at least able to separate out aspnet identity in its own history table, I can leave identity server migrations in dbo. 

The reason I wanted to separate database migrations into their own schemas was because EFCore removed the context key column from migration history table. So if I have schema name 'Init' for my multiple dbcontexts, their migration entries appear to be <timestamp>_Init. Its not easy without spending effort correlating migration files with table entries to figure out which <timestamp>_Init migration belongs to which dbcontext. 

By the way, I figured out a way to automate the schema name generation altogether so I am at peace now.

**Comment by ceemafour** [comment]
Just in case this is still needed, try this on your ConfigureServices Method:

`options.ConfigureDbContext = b =>
                    b.UseSqlServer(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly).MigrationsHistoryTable("ConfigMigrationTable", "MySchema")`

**Comment by tiwari-abhishek** [comment]
Thanks, I will give this a try
