### ISSUE TITLE
Windows Logout do not work as expected 

### ISSUE THREAD

**Issue by kessko** [IdentityServer/IdentityServer4#2328]
Hello, faced with SignOut issue.

I use IdentityServer4.Quickstart as core of my app. Case that i want to cover is Login/Logout through Windows authentication scheme. I turned ON Windows Authentication on IIS.
Login using Windows works perfect. I navigate to Account/Login then just click on button with name "Windows" and i am in. I see "idsrv" and "idsrv.session" cookie in browser.
So far so good.

When i try to Logout by clicking on "Logout" that located above my windows user name in header there is no error appears and looks like everything is ok, even i see message "You are now logged out" , but when i go to main page -> I am still authenticated.
I see the name of my windows user in header and if i try to logout one more times i will see
System.InvalidOperationException: 'sub claim is missing' 
in AccountController controller
Logout method 
206 row ->  await _events.RaiseAsync(new UserLogoutSuccessEvent(User.GetSubjectId(), User.GetDisplayName()));
It looks like user logged out but i don't know how to say, partially? There is no subject id in Claims but application still know my windows name and other stuff. When i try to inspect user claims i found all my claims valid and exists in HttpContext.User property. Additionally method User.IsAuthenticated() returned true.

I'm not familiar with windows authentication well but i expected that after logout application will no longer know about current User.
Maybe i miss something?

**Comment by brockallen** [comment]
>  Maybe i miss something?

When using integrated windows authentication the only way to really logout is to logout of your computer -- the same one you logged into with your windows credentials.

**Comment by kessko** [comment]
Wow, that means that it works as everyone expected.
Thank you for explanation.

**Comment by neu-anthony** [comment]
@brockallen @leastprivilege I have tested this and IdentityServer4 performs normally via FireFox, Edge.  But on Chrome, the windows user stays logged in when the local user logs out.  

**Do you have any ideas where to begin looking for a solution**?  it looks messy when the user logs out and then up in the menu bar their windows creds show them as still logged in?  for example: Anthony is logged in, then logs out and DOMAIN\Anthony is logged in.

Here are steps to reproduce:
1) setup IdentityServer4 site to be in "Intranet Zone"
2) create local user
3) map local user to windows user (AspNetUserLogins)
4) access login page from Chrome
5) use Windows login button on External Logins
6) user is redirected to grants page with local username as dropdown in menu bar
7) use username dropdown to log out
8) press yes to logout prompt
9) user is redirected back to login page, showing domain creds as logged in user (in menu bar as dropdown).

If you follow the same steps from FireFox, Edge the last step shows a normal login page with no logged in user dropdown.
