### ISSUE TITLE
Implicit flow access token validation

### ISSUE THREAD

**Issue by waynevdm** [IdentityServer/IdentityServer4#2333]
Hi

We have a scenario where a website built in Java is retrieving and access token from Identity Server 4 and calling their server with the access token. I told them they should be validating the token on the backend but I am having difficulty figuring out how you do that for an access token for a client setup with implicit flow. The C# sample code I have seen calls the introspection endpoint for an access token retrieved with the resource owner flow client. Any help would be appreciated.

Thanks,
Wayne

**Comment by brockallen** [comment]
>  I told them they should be validating the token on the backend but I am having difficulty figuring out how you do that for an access token for a client setup with implicit flow. 

I don't understand. How the client obtains the access token (e.g. the flow) is orthogonal to how the API validates the access token.

**Comment by nathanrhoda** [comment]
Hi 

Just for some more context the client receives the token via a connect/authorize call and then we were thinking about making a second call to token/introspect to verify the token after the authorization. The catch though is we are using implicit flow and we are struggling to find good examples where this is done. 

Regards
Nathan

**Comment by brockallen** [comment]
You're confusing the protocol flows, I think. Clients don't inspect access tokens. Clients validate identity tokens only. APIs receive and validate access tokens.

**Comment by nathanrhoda** [comment]
Apologies I may have caused some confusion by saying client i actually meant IdentityServer Client ie. Web Application.  Also We currently have it configured using the implicit flow with no secret. 
So flow is as follows 
1) A user logs in calls into connect/authorize receives the token 
2) After the api receives the access token we want to call into connect/introspect to verify that it is still active, valid and not tampered with.
This is all currently being attempted using c#  web application.
Let me know if that s a bit clearer

**Comment by waynevdm** [comment]
We have read the docs but if we have an client configured like below

  "OAuth2Configuration": {
    "ApiResources": [
      {
        "Name": "MyApi",
        "DisplayName": "My Api"
      },
    ],

    "Clients": [
      {
        "ClientId": MyPortal",
        "Name": "My Portal",
        "RedirectUris": [
          "http://localhost:4200",
          "http://localhost:4200/*",
          "http://localhost:6002",
          "http://localhost:6002/*"
        ],
        "AllowedCorsOrigins": [
          "http://localhost:4200",
          "http://localhost:5000",
          "http://localhost:6002"
        ],
        "AllowedGrantType": "Implicit",
        "AllowedScopes": [ "MyApi" ]
      }

and the startup of the Api is
            app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:5000",
                RequireHttpsMetadata = false,

                ApiName = "MyApi"
            });

What we are trying to understand is if the introspection endpoint is called then where does it get the scope secret from?

**Comment by brockallen** [comment]
> What we are trying to understand is if the introspection endpoint is called then where does it get the scope secret from?

Introspection is automatically called by UseIdentityServerAuthentication. You need to set an ApiName (as you have done) and an ApiSecret. The ApiSecret is configured in IdentityServer on the ApiResource's ApiSecrets collection.
