### ISSUE TITLE
Is it possible to store "Clients" on database using IDS4?

### ISSUE THREAD

**Issue by CeelMarten** [IdentityServer/IdentityServer4#2338]
I want to store Clients on database. Can I do that with IDS4?
Thanks in advance

**Comment by SIkebe** [comment]
http://docs.identityserver.io/en/release/quickstarts/8_entity_framework.html

**Comment by CeelMarten** [comment]
@SIkebe Thanks for the answer. I'm looking for another solution, without EF. Solutions for micro ORMs

**Comment by brockallen** [comment]
Read the docs: http://docs.identityserver.io/en/release/topics/clients.html

**Comment by CeelMarten** [comment]
Thank you, @brockallen . This page helped me to understand what I want and what can I do for that. And for those in future who will seek "autocreate" (DB table) functionality for micro ORMs. There is no way to do that.
You must...
1. Create DB Tables ( http://docs.identityserver.io/en/release/topics/clients.html)  Find required fields here.
2. Create "GetClientById" Stored Procedure 
3. Implement IClientStore
4. And finally in Startup.cs Use AddClientStore instead of AddInMemoryClients 

Am I right ?

**Comment by brockallen** [comment]
That could be one way to go about it.
