### ISSUE TITLE
Question: Is that possible to get email claim(or different) when i use integrated windows authentication?

### ISSUE THREAD

**Issue by kessko** [IdentityServer/IdentityServer4#2339]
Hello, my question is:
When i am use integrated windows authentication through press "Windows" button on Account/Login view at the back-end i see that we just call Challenge with "Windows" scheme as parameter.
I inspect WindowsIdentity Claims after success login and i cannot see email claim. 
I explored Active Directory and i see that the property "mail" present in my user profile.

Maybe exist an approach to identify what exactly claims i need inside Identity when i start Challange?
For example in my Identity claims i can see more than 100 windows groups. But  to be honest i dont need them at all.

**Comment by brockallen** [comment]
>  I inspect WindowsIdentity Claims after success login and i cannot see email claim.

Configure your AD to issue this claim, or write some directory services code to look it up.

**Comment by kessko** [comment]
Unfortunately i cannot configure AD, but anyway directory service sound like a solution.
Thanks for help.
