### ISSUE TITLE
Refactor Request: Only rely on IHttpContextAccessor and HttpContext on the edge

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2341]
I am implementing a background cron job that attempts to mint tokens directly as a means to know that my service is healthy.  My app relys on Azure KeyVault for signing and Redis for storing refresh_tokens.
So I am pushing a request through to probe the health of the entire system.

I am using;
```
IHostedService and IHttpContextAccessor is not in play here.. 
```  

To do that I thought I could use all these IService(s) that TokenEndpoint is using.  For the most part the abstractions are very good.

However, reliance on HttpContext deep in default services would have me replace more than I am comfortable replacing.  
i.e. 
```
public class DefaultTokenService : ITokenService
{
     public virtual async Task<Token> CreateIdentityTokenAsync(TokenCreationRequest request)
     {
...
           var issuer = Context.HttpContext.GetIdentityServerIssuerUri();
...
     }
} 
```
When you take up your next refactoring effort, can you give thought on pulling IHttpContextAccessor and HttpContext to the edge.  One way is to rely on it only at the edge(TokenEndpoint), by pulling everything you need and pass raw data downstream.

-H

**Comment by brockallen** [comment]
This would be a lot of changes. Are you interesting in submitting a PR? If so, it would have to wait for 3.0 where breaking changes are acceptable.

**Comment by ghstahl** [comment]
I can submit a PR for 3.0.
