### ISSUE TITLE
Support returning a refresh token without the `offline_access` scope

### ISSUE THREAD

**Issue by liamdawson** [IdentityServer/IdentityServer4#2342]
According to the OpenID Connect Core 1.0 specification section 11 (http://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess), the `offline_access` scope is a good way to define returning a refresh token, but it also notes "The use of Refresh Tokens is not exclusive to the offline_access use case. The Authorization Server MAY grant Refresh Tokens in other contexts that are beyond the scope of this specification."

https://github.com/IdentityServer/IdentityServer4/blob/release/src/IdentityServer4/ResponseHandling/TokenResponseGenerator.cs#L278   
and   
https://github.com/IdentityServer/IdentityServer4/blob/release/src/IdentityServer4/ResponseHandling/TokenResponseGenerator.cs#L302   
set the conditions for generating a refresh token as "the `offline_access` scope has been passed and validated".

It would be good if it were possible to configure a "return a refresh token anyway" configuration setting. In my case, I need it to emulate a different OIDC server I don't control, where it returns refresh tokens without that scope being specified (and indeed rejects the `authorize` request if you include that scope).

**Comment by brockallen** [comment]
Dup: #1056
