### ISSUE TITLE
HTTPS SSL certificate validation issue - Identity Server 4

### ISSUE THREAD

**Issue by Muraliapm** [IdentityServer/IdentityServer4#2343]
Hi,

I have created Authserver using Identity server 4 and deployed it in staging server by creating SSL. The URL is working fine. https://{my server host}/.well-known/openid-configuration. I am using this Authserver in my Angular 5 application using implicit flow. Everything is working fine but when i run the application at first time, getting below error.
![image](https://user-images.githubusercontent.com/23413513/40763698-5c33f27a-64c3-11e8-915c-c22ee0617511.png)
if we manually run this url https://{my server host}/.well-known/openid-configuration, it shows below warnings.
![image](https://user-images.githubusercontent.com/23413513/40763817-e092aef8-64c3-11e8-84e0-9b77803c8311.png)

Please let me know how to skip this SSL validation in Angular so that we dont need to manually run the openid-configuration url.?

Thanks,
Murali.C

**Comment by leastprivilege** [comment]
You need a working HTTPS setup. This is a requirement. This is also not an IdentityServer related issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
