### ISSUE TITLE
Replace Quick start MVC razor view with Angular or React application.

### ISSUE THREAD

**Issue by vejandla** [IdentityServer/IdentityServer4#2347]
First of all, Thank you for this awesome product, I have been using the [quick start UI](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI) for my identity server, Is there a way we can have a javascript application(angular, react, vue) as the UI for Identity server instead of using MVC.

**Comment by brockallen** [comment]
Yes, it's possible but not worth the effort IMO.

**Comment by vejandla** [comment]
Can you give me a pointer where to start?

**Comment by brockallen** [comment]
You need to replace what the AccountController from the quickstart is doing.

**Comment by vejandla** [comment]
@brockallen I have started using angular UI for idp login screen. I did this using UserInteractionOptions. Is this the right approach? am I in the right direction?

**Comment by collinbarrett** [comment]
@vejandla did ya'lll continue to pursue this approach? we're interested in finding an Angular boilerplate for IS4 if one exists to more easily match the styling of the client Angular applications.
