### ISSUE TITLE
Missing parameter in SAML assertion.

### ISSUE THREAD

**Issue by frjaffery** [IdentityServer/IdentityServer4#2351]
We have implemented the Identity Server 4 with SAML2p and noticed that SAML assertion does not contain these below parameters. This entire block is missing, are we missing anything to enable this? please help.

        <saml:Conditions NotBefore="2018-05-31T16:07:28.717Z"
                         NotOnOrAfter="2018-05-31T16:09:28.717Z"
                         >
            <saml:AudienceRestriction>

Anybody has nay idea?

**Comment by leastprivilege** [comment]
@scottbrady91

**Comment by brockallen** [comment]
Please contact support at Rock Solid Knowledge for this, as it's a feature of that product not IdentityServer itself. Thanks.

**Comment by scottbrady91** [comment]
@frjaffery Is this the same as the issue you have already reported? Or something new? If this is different, please contact support@rocksolidknowledge.com

**Comment by frjaffery** [comment]
Yes, this is the same as we have already reported.
