### ISSUE TITLE
Sign nuget packages

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#2353]
https://blog.nuget.org/20180522/Introducing-signed-package-submissions.html

**Comment by leastprivilege** [comment]
yes you are ;)

**Comment by LindaLawton** [comment]
I would offer to look into it on Friday but after reading though that i dont think thats something your going to want to give me access to.

**Comment by leastprivilege** [comment]
Don't worry . I am working on it.

**Comment by leastprivilege** [comment]
OK - details have been worked out. All releases to nuget will be signed in the future.

**Comment by LindaLawton** [comment]
can I ask where you got the certificate?   I need to do the same at some point on one of my projects

**Comment by brockallen** [comment]
From being in the .NET Foundation.

**Comment by leastprivilege** [comment]
You just need a code signing certificate from one of the public CAs.

**Comment by andrehamer** [comment]
When should we expect the signed dlls in nuget?

**Comment by leastprivilege** [comment]
The dlls are not signed. Only the nuget.
