### ISSUE TITLE
No DbContext named 'PersistedGrantDbContext' was found Exception

### ISSUE THREAD

**Issue by MostafaAbdlrazek** [IdentityServer/IdentityServer4#2356]
**Steps to reproduce the issue:**
1. have an existing ASP.NET Core 2 MVC app for the identity server
2. created a new .NET Core class library to have the DAL logic in it and installed the following packages in it:
`IdentityServer4.EntityFrameWork`
`IdentityServer4.AspNetIdentity`
`Microsoft.EntityFrameWorkCore`
`Microsoft.EntityFrameWorkCore.Tools`
3. Added the below snippet before the end </Project> element in the class library:

`<ItemGroup>
  <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
</ItemGroup>`

4. and then tried to run the following migration command 
`dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb` 

**Expected**
A migration folders created for the PresistedGrantDbContext

**Actual**
No DbContext named 'PersistedGrantDbContext' was found

I have tried to clean the solution and rebuild it and even creating another class library but the same issue happen.

**Comment by brockallen** [comment]
IIRC, migrations don't work for library projects. In any event, that's a microsoft feature, not an IdentityServer feature so I'd look to them for help with it.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
