### ISSUE TITLE
During the cleanup token process, add support for an event when token is expired. 

### ISSUE THREAD

**Issue by gsvitak** [IdentityServer/IdentityServer4#2359]
Hello

I have a third party system that uses the concept of sessions to maintain user state. I need the ability to automatically clean up the sessions in the third party system when the tokens are expired. I would love to have an event that is fired by the token cleanup process so I can implement my logic to clean up the sessions. 

I would be willing to help with the work for this feature request if needed.

Thanks,
G

**Comment by brockallen** [comment]
Not a bad idea.

**Comment by brockallen** [comment]
@LindaLawton this might be a nice project given that you mentioned your Friday plans :)

**Comment by LindaLawton** [comment]
Sounds like fun considering i have not played in the event system yet.    Assign me to it.   I know where to find you if i have any questions free to point me in the correct direction.   The last bug took me four hours to find and five minutes to fix :)

**Comment by gsvitak** [comment]
Awesome!! thanks. Let me know if can help.

**Comment by gsvitak** [comment]
@LindaLawton Thanks for the support. I am curious to see how things are going. Any updates?

Thanks,
G

**Comment by LindaLawton** [comment]
I didn't have long to look at it but was unavailable to figure out what even calls it.     its like the setting isn't used anywhere.

I should have some more time to look at it Friday.

**Comment by gsvitak** [comment]
@LindaLawton checking in.. how are things going?

**Comment by LindaLawton** [comment]
unfortunately we had some issues at work that have priority, and now we are into vacation season. I won't have to look at this until the end of August.

**Comment by brockallen** [comment]
How would this event look like?  Just a delegate? Or something from DI? DI is tricky since this token thing runs outside of http requests.

**Comment by gsvitak** [comment]
A delegate is fine. Understand the DI complexity.

**Comment by brockallen** [comment]
Ok so turns out i was already resolving stuff from DI in the token cleanup, so we can do a service in DI

**Comment by brockallen** [comment]
ok, done -- and with an interface in DI.

**Comment by gsvitak** [comment]
Thank you!! Do you have a unit test to show how it works?

**Comment by brockallen** [comment]
no, but the sample EF host does. if you'd like to add tests, we'd love them

**Comment by jjavierdguezas** [comment]
Hi, please can you show some piece of code?
I need to do some stuff when a token is expired, but I cant figure it out
thanks in advance

**Comment by jjavierdguezas** [comment]
@gsvitak @brockallen, can you please help me find the piece of code that do this feature? thanks in advance

**Comment by jjavierdguezas** [comment]
for future references you should implement `IOperationalStoreNotification`
