### ISSUE TITLE
RedirectURI not respected for authorize request to External OIDC Provider

### ISSUE THREAD

**Issue by ygeelen-tb** [IdentityServer/IdentityServer4#2361]
Hello,

I'm using the latest version of IdentityServer4 and I'm writing authentication for an Angular6 app towards a OIDC provider of the government. 

Even though I think I have configured the redirectURI correctly (ClientRedirectUris = https://localhost:44328/oidc/fas/auth):

new Client
                {
                    ClientId = "ng",
                    ClientName = "Angular Client",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,
                    RequireConsent = true,
                    RedirectUris = { configuration["ClientRedirectUris"] }, 
                    PostLogoutRedirectUris = { configuration["ClientPostLogoutRedirectUris"] },
                    AllowedCorsOrigins = { configuration["ClientUrl"], configuration["WebApiUrl"] },
                    AllowedScopes =
                    {
                      IdentityServerConstants.StandardScopes.OpenId,
                      IdentityServerConstants.StandardScopes.Profile,
                        "egovNRN",
                        "certficateInfo"
                    }
                }

[Route("oidc/fas/login")]
        public IActionResult Login()
        {
            string returnUrl = this.Request.Query.ContainsKey("returnUrl") ? this.Request.Query["returnUrl"].FirstOrDefault() : string.Empty;
            string provider = "fas-oidc";
            string callbackUrl = Configuration["ClientRedirectUris"];
AuthenticationProperties props = new AuthenticationProperties
            {
                RedirectUri = callbackUrl,
                Items =
                {
                    { "scheme", provider },
                    { "returnUrl", returnUrl }
                }
            };
            return Challenge(props, provider);
        }

It seems that the redirect_uri used for the authorize request to the external provider eventually is the default URL being https://localhost:44328/signin-oidc rather than https://localhost:44328/oidc/fas/auth ?
![redirecturi](https://user-images.githubusercontent.com/12393883/41053199-2983da00-69bb-11e8-9e2c-2d75e7f9e54b.png)

Am I missing some configuration?

**Comment by brockallen** [comment]
Sounds like a misconfiguration in your IdentityServer somewhere.

**Comment by ygeelen-tb** [comment]
@brockallen I fixed this by configuring the CallBackPath property of the AddOpenIdConnect options to the same RedirectUri I configured in the IDS OIDC Client allowed redirect uris.
