### ISSUE TITLE
Correlation failed 

### ISSUE THREAD

**Issue by dfrostpl** [IdentityServer/IdentityServer4#2365]
Hi. I'm trying to connect 2 .NET Core 2.1.0 MVC apps with Identity Server 4. 

Identity Server Configuration:
`public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(options => { options.UseSqlServer(Configuration.GetConnectionString(Constants.ConnectionStrings.Sql)); });
services.AddIdentity<User, IdentityRole<int>>(options =>
                {
                    options.Password.RequireNonAlphanumeric = false;
                })
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services.AddScoped<IClientStore, ClientStore>();
            services.AddScoped<IProfileService, UserProfileService>();
            services.AddScoped<IUserClaimsPrincipalFactory<User>, PrincipalFactory>();
            services.AddIdentityServer()
                //here should be certificate for prod
                .AddDeveloperSigningCredential()
                .AddInMemoryPersistedGrants()
                .AddInMemoryIdentityResources(IdentityServerConfiguration.GetIdentityResources())
                .AddClientStore<ClientStore>()
                .AddProfileService<UserProfileService>()
                .AddAspNetIdentity<User>();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            AccountOptions.ShowLogoutPrompt = false;
            AccountOptions.AutomaticRedirectAfterSignOut = true;
            app.UseHsts();
            app.UseStaticFiles();
            app.UseIdentityServer();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    "default",
                    "{controller=Home}/{action=Index}/{id?}");
            });
        }`

MVC Client Configuration
`public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(options =>
            {
                options.Filters.Add(new RequireHttpsAttribute());
            }).SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            //to remove default .net core mappings
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            
            services.AddAuthentication(options =>
                {
                    options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme; ;
                    options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                })
                .AddCookie()
                .AddOpenIdConnect(options =>
                {
                    options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    options.RequireHttpsMetadata = false;
                    options.Authority = "https://localhost:44310";
                    options.ClientId = "Zebra";
                    options.SaveTokens = true;
                    options.TokenValidationParameters.NameClaimType = "name";
                    options.RemoteAuthenticationTimeout = TimeSpan.FromSeconds(10);
                    options.ClientSecret = "secret";
                    options.ResponseType = "code id_token";
                    options.Scope.Add("offline_access");
                    options.GetClaimsFromUserInfoEndpoint = true;
                });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
               
            }
            app.UseHsts();
            app.UseStaticFiles();
            app.UseAuthentication();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    "default",
                    "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }`

Everything is OK but when identity server redirects back to client, it throws Correlation failed exception.

**Comment by LindaLawton** [comment]
Wild guess add this to your configure in start up.

    app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedProto
            });

**Comment by dfrostpl** [comment]
@LindaLawton ,
thank you for response.  But looks like it's not the case. 
[screenshot](http://joxi.ru/V2VBGdvuxgv802.jpg)
do you know exact reason why it happens? 
Actually  I downloaded samples with IdentityServer 4 v. 1.5.2 and it worked very fine. 
I'm using lates 2.2.0

**Comment by LindaLawton** [comment]
I had this last week.  For me it had something to do with the fact that we are running in docker where everything goes around as http but some stuff gets sent back by the load balancer https.   I am trying to remember exactly what i did to fix it.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by LindaLawton** [comment]
Leaving note here then:

If anyone ever gets a working version of identity server without this error  (**Correlation failed** ) please ping this.   I would love to see the solution after three months I have still not found the solution.

**Comment by ZOXEXIVO** [comment]
@LindaLawton yes, we are using identity without Correlation Failed error)
Implement custom DataProtection repository storage, that use one protection key for your nodes

**Comment by cculver** [comment]
@LindaLawton did you ever get this figured out? Running into the same exact situation. Thinking it's related to developer signing credentials running in production but nothing conclusive.
