### ISSUE TITLE
Using IdentityServer as external OAuth provider for .NET Framework based applications

### ISSUE THREAD

**Issue by zeroxster** [IdentityServer/IdentityServer4#2367]
Is it at all possible to use IdentityServer as external authentication for .NET Framework based applications? I've been trying to stich together a secure hybrid method that would allow signing into IdentityServer from an .NET Framework 461 based project, with little luck. 

I wonder if anyone has attempted something similar to this and had luck with it? And if there's any existing documentation that could contain hints as to how to achieve that.

**Comment by leastprivilege** [comment]
This certainly works - but 

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
