### ISSUE TITLE
Questions regarding Angular - Web API - IDS4 setup

### ISSUE THREAD

**Issue by ygeelen-tb** [IdentityServer/IdentityServer4#2369]
Hi,

I have set up the following so far:
- Angular project (JS): 
    - calls the IDS for authenticating a person
    - uses OIDC javascript client library to redirect to IdentityServer connect endpoint
    - adds the bearer token to all requests to the Web API

- .NET Core 2 Web API project:
    - manages person data in database
    - uses IdentityServerAuthentication (OAuth2)

- IdentityServer4 project:
    - 2 clients: Angular (implicit grant type) and API (grant type client credentials)
    - calls external OIDC Provider (OP)
    - user authenticates through eID for example
    - external OP does callback to Api Controller in IdentityServer4 project where calls are made to the token and userinfo endpoint of the external OP to get access_token, refresh_token, id_token and all claims

My questions:

- is it normal that I need to do the HTTP requests to the Token endpoint and UserInfo endpoint of the external OP manually? Or should IdentityServer do that for me, just like it does the authorize request for me?

 - would it make more sense to have the callback endpoint in de Web API directly? or should I just POST from the IdentityServer Api Controller callback action to a new user registration endpoint in the Web API?

- now I have those 3 tokens, how to return them to the Angular client? By using the SaveTokens option to return them in a cookie?

- what's the best place to store user data: in a new database behind the IdentityServer or in the database behind our Web API?

- [the example code for external OP's on your website](http://docs.identityserver.io/en/release/topics/signin_external_providers.html) starts with the following line:
"HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme)" this however throws an exception when executed in my callback action. Is the following configuration not enough to make sure external cookies are created?

services.AddAuthentication(options =>
                {
                    options.DefaultScheme = "Cookies";
                    options.DefaultChallengeScheme = "fas-oidc";
                })
                .AddOpenIdConnect("fas-oidc", "fas-oidc", options =>
                {
                       options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
