### ISSUE TITLE
IPersistedGrantStore for the production mode

### ISSUE THREAD

**Issue by doronkind** [IdentityServer/IdentityServer4#2370]
Can I ask you one questions, cause maybe I didn't clearly understand the documentation? We can configure PersistedGrantStore by implementation the IPersistedGrantStore interface. We can consider EF core and use suitable NugetPackage or we can implement own solution. 

By default we keep reference and refresh tokens in memory. It works until the IS4 app pool won't be unloaded, becuase of the Idle timeout e.g. and after pool loaded once again, actually we have no in-memory data. It is according to logic. 

Is it good idea if I use "Always on" option (disable Idle timeout) instead of the PersistedGrantStore implementation?
  
As a result my pool will never be unloaded and I always can use in memory data. We get some problems if app be crushed, but in general this way seems quite simple and working.

What is your recomendation about this, maybe I missed sothing important?

**Comment by leastprivilege** [comment]
Well - if you only have short-lived data - this might be an option.

Keep in mind that this will not work once you try to scale out to more than 1 server.

**Comment by doronkind** [comment]
Sure, we need to share data between servers in the scaling case. 

I just starts with IS and at the first stage want to implement the simpiest production environment, investigate potentially proplems and after try other approaches, such as persistent storage.

Thank you for the answer!
