### ISSUE TITLE
Identity Server & Identity Server Authentication with Http.Sys

### ISSUE THREAD

**Issue by yoelgh** [IdentityServer/IdentityServer4#2378]
Hi,

I'm implementing an organization management system that also serve as Authorization Server/ID Provider.

IdentityServer4 is used for implementing the Authorization Server/ID Provider.
IdentityServer4.AccessTokenValidation is used for implementing the authorization of the organization management api.

They are both running on the same web host. 
HttpSys is specified as the server to be used by the web host as a Windows Authentication Logins must be supported.

The HttpSys is configured like this:
```
options.Authentication.Schemes = AuthenticationSchemes.Negotiate;
options.Authentication.AllowAnonymous = true; 
```

The problem is:
Whenever a 401 status code is return, a 'WWW-Authenticate: Negotiate' header is added to the response, causing the browser to pops up the built in sign in popup. 

For example:
When trying to access the protected organization management api without an access token the 'Identity Server Authentication' sets the status code to 401 and added the 'WWW-Authenticate: Bearer' header, which is fine, but a 'WWW-Authenticate: Negotiate' is also added by the HttpSys, causing the browser to pops up the built in sign in popup.

Thanks,
Yoel

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. I think you should ask around on the ASP.NET Core forms for that.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
