### ISSUE TITLE
IdentityServer4.AccessTokenValidation not supported in .Netframework

### ISSUE THREAD

**Issue by Sivasekare** [IdentityServer/IdentityServer4#2381]
Guys,  I have created IdentityServer using the latest version 4.  But my Services (api) are running in .NetFramework.  I couldnt see any ways to use IdentityServer4.AccessTokenValidation in the api running under .NetFramework.  Does IdentityServer4.AccessTokenValidation support .Netframework.  I have tried IdentityServer3.AccessTokenValidation, but it looks to be returning 'UnAuthorized' since the token issued by IdentityServer4 is validated by using IdentityServer3.AccessTokenValidation.  Does that make any diff?
Appreciate your support

**Comment by kevinlo** [comment]
IdentityServer4.AccessTokenValidation has net461

You can see 

>     <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>

in [IdentityServer4.AccessTokenValidation.csproj](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/blob/dev/src/IdentityServer4.AccessTokenValidation/IdentityServer4.AccessTokenValidation.csproj)

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by Sivasekare** [comment]
Yes please
