### ISSUE TITLE
Not seeing profile data on: user info endpoint.

### ISSUE THREAD

**Issue by nduijvelshoff** [IdentityServer/IdentityServer4#2385]
### Issue / Steps to reproduce the problem

When I send a `GET` to `/connect/userinfo` I receive the following response:
```
{
    "sub": "c4180a3f-7d36-4a34-a41a-f5696df9ffcf",
    "preferred_username": "demo@ domain.tld",
    "name": "demo@tada.red"
}
```
While I expected to see:
```
{
    "sub": "c4180a3f-7d36-4a34-a41a-f5696df9ffcf",
    "preferred_username": "demo@domain.tld",
    "name": "Demo Demo",
    "given_name": "Demo",
    "family_name": "Demo",
}
```
I created the following table column's:
- DisplayName
- GivenName
- FamilyName

Did I do sorting wrong? By the way, I'm using the ASP.NET Core Identity.

**Comment by brockallen** [comment]
> I created the following table column's:

And then how are you mapping those back to claims in IdentityServer?

**Comment by vverrastro** [comment]
What do you mean when you wrote _"I created the following table column's"_?

You can see correct result if you add claims to your user (into table UserClaims). Like:

- Type: give_name
- Value: myName

**Comment by nduijvelshoff** [comment]
@vverrastro that was indeed the solution, thanks!
