### ISSUE TITLE
RefreshToken Expiration causing Undesired User Logout

### ISSUE THREAD

**Issue by reeceengle** [IdentityServer/IdentityServer4#2386]
### Issue / Steps to reproduce the problem
Currently we have our IdentityServer client set to use defaults for
AbsoluteRefreshTokenLifetime & SlidingRefreshTokenLifetime. This is causing a lot of our users to re-enter their credentials which we want to increase.

We are going to increase these times to better support our desired functionality.

However, for PersistedGrants that have already been created, is it possible to increase their Expiration by modifying that column in the PersistedGrants table? Or would we also need to modify the data column to truly extend the expiration of a given PersistedGrant?

### Relevant parts of the log file
```
<no relevant logs>
```

**Comment by brockallen** [comment]
You'd have to change the data in the json itself.
