### ISSUE TITLE
Handling custom parameters in IntrospectionEndpoint

### ISSUE THREAD

**Issue by opoutere** [IdentityServer/IdentityServer4#2388]
Hello,
I'd like to handle custom input parameters in introspection endpoint. I'd like to modify introspection behavior in an inherited IntrospectionResponseGenerator class based on the input parameter.
There is a property named Parameters In IntrospectionRequestValidationResult, I think this would be a great candidate to pass my custom parameters in IntrospectionResponseGenerator.ProcessAsync(). However Parameters property never gets a value in the introspection pipeline.
It would be nice to make the Parameters property value assignment in IntrospectionRequestValidator.ValidateAsync() like this:

```
            return new IntrospectionRequestValidationResult
            {
                IsActive = true,
                IsError = false,
                Token = token,
                Claims = tokenValidationResult.Claims,
                Api = api,
                Parameters = parameters
            };
```

**Comment by brockallen** [comment]
This is something we'd consider if you submit a PR.

**Comment by brockallen** [comment]
merged, thanks!

**Comment by VictorioBerra** [comment]
@opoutere I hope this is not too off topic but I am curious to what you are doing with the extra params in the introspection endpoint?

**Comment by opoutere** [comment]
@Kahbazi thanks for the PR!

**Comment by opoutere** [comment]
@VictorioBerra In our Identity solution each user can belong to multiple tenants. When making introspection without input parameters, user will get the claims related to his/her current tenant context. Current tenant context is specified by a tenant ID originally requested via IS Authorize endpoint. We need a way for users to get back claims related to a tenant other than the current tenant via introspection. This way no need to request for a new token via implicit flow via Authorize endpoint. So I pass an extra tenant ID parameter in introspection request when I need the claims related to the other tenant.

**Comment by VictorioBerra** [comment]
@opoutere

That makes sense, thanks. Just curious though why not make sure those extra claims are inserted into the id_token and acess_token at the time they are issud? Or make them available via the user info endpoint?
