### ISSUE TITLE
How to customer IdentityUser  

### ISSUE THREAD

**Issue by borisGong** [IdentityServer/IdentityServer4#2394]
when I custom my user , I need  Inherit IdentityUser class , but IdentityUser class  defines  many properties that I don`t  need  , example for  PhoneNumber , Email  .  how to  remove the properties

**Comment by leastprivilege** [comment]
This is an ASP.NET Identity question - and unrelated to IdentityServer

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
