### ISSUE TITLE
Identityserver4 controller action is not getting called

### ISSUE THREAD

**Issue by sreekanthmg** [IdentityServer/IdentityServer4#2397]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

I have a AdminController in IndentityServer4 project witch has an action
[Authorize]
[HttpPost("user/{userName}/assignclaims")]
public async Task<IActionResult> AssignClaimsToUser(string userName, [FromBody]
List<ClaimBindingModel> claimsToAssign)
{
}
So I would like in my ApiController to manage claims
var httpClient = await _identyServerHttpClient.GetClient();
var response = await httpClient.PostAsync("api/admin/user/khasaar@gmail.com/assignclaims", new Htt );
if (response.IsSuccessStatusCode)
{
}
public async Task<HttpClient> GetClient()
{
          var currentContext = _httpContextAccessor.HttpContext;
          string accessToken = await currentContext.GetTokenAsync("access_token");
        _httpClient.BaseAddress = new Uri("http://MyIdentityServerUrl");
        _httpClient.DefaultRequestHeaders.Accept.Clear();
        _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        if (!string.IsNullOrWhiteSpace(accessToken))
        {
            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
        }

        return _httpClient;
    }

It return 200 but does not fire AdminController .AssignClaimsToUser

Why this is not working when I have authorize attribute decorated in some controller in id server ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
