### ISSUE TITLE
Identityserver4 not working in AWS ALB

### ISSUE THREAD

**Issue by sreekanthmg** [IdentityServer/IdentityServer4#2398]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

I am facing a serious issue related to identityserver4 when I host my application in AWS. It is created in asp.net core 1.x.
My application is having following components
1. identityserver4 which is an MVC app
2. AngularJS
3. Micro services

Here, once user authenticated against identityserver4 using implicit flow, we get the token in angularjs app by using oidc-client. And this token will get passed in the header while calling different micro services and micro service internally validates it against identityserver4 by UseIdentityServerAuthentication.

This works fine if we use system ip for configuration. But when we created ALB for identityserver in AWS, all micro services started failing saying 401 unauthorized exception. Our micro services does not have an ALB as it is not exposed to external world. 

Can you suggest what could be the issue ?

Also is there any way, I can manually check the bearer token against identityserver4 in my micro services, rather than using UseIdentityServerAuthentication ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Sounds like you need to configure the Issuer.

**Comment by sreekanthmg** [comment]
Where should I mention the issuer? Is it in identityserver configuration or in my micro service ?

Identity Server config:
 services.AddDeveloperIdentityServer()
                .AddInMemoryScopes(clientConfig.GetScopes())
                .AddInMemoryClients(clientConfig.GetClients());

app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                ExpireTimeSpan = TimeSpan.FromMinutes(20),
                SlidingExpiration = true
            });

Micro service config:
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = Configuration["AuthorityUrl"],
                ScopeName = Configuration["ScopeName"], 
                RequireHttpsMetadata = false,
                AutomaticChallenge = true
            });

**Comment by brockallen** [comment]
There are similar posts here in the issue tracker. I didn't spend too much time looking at yours, but it sounds similar. IOW, you're using an IP and a hostname. Using IP is problematic behind load balancer, so you might need to set the PublicOrigin: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/Options/IdentityServerOptions.cs#L29

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by sreekanthmg** [comment]
Yes.  You can close

On Jun 23, 2018 6:43 PM, "Brock Allen" <notifications@github.com> wrote:

All set on this issue -- can we close?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/IdentityServer/IdentityServer4/issues/2398#issuecomment-399677674>,
or mute the thread
