### ISSUE TITLE
How to create user identity from identityserver4 bearer token 

### ISSUE THREAD

**Issue by sreekanthmg** [IdentityServer/IdentityServer4#2399]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

I am having identity server4 bearer token. 
Can I create any deserialization/other techniques to generate user identity without calling useidentityauthe.. ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
The identity of the user in the bearer token is held in the "sub" claim type.
