### ISSUE TITLE
System.Security.Authentication.AuthenticationException: Unable to obtain configuration

### ISSUE THREAD

**Issue by fshin123** [IdentityServer/IdentityServer4#2401]
Hello,
I recognize that different flavors of this issue have been posted in the issues list for IdentityServer, but of course, I think this is distinct. ;-)

We have an API that is configured to work with IdentityServer 4 that is randomly throwing an exception when it is trying to access the configuration at //oursite/.well-known/openid-configuration. When I say "randomly," I mean that it occurs once every 12-24 hours. Once it happens, it gets "stuck" with that behavior until the app services are restarted (this is in Azure). 

Here is the exception message:
Unable to obtain configuration from: 'https://oursite/.well-known/openid-configuration'. IDX10804: Unable to retrieve document from: 'https://oursite/.well-known/openid-configuration'. An error occurred while sending the request. The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. The remote certificate is invalid according to the validation procedure.

Steps that we have taken to date:
1. Update the TLS on the SSL certs to 1.2 (it was previously set at 1.0).
2. We realized that the IdentityServer service setup at startup was using the Temporary Signing Credential (.AddTemporarySigningCredential()). Here is where things get interesting. In our QA environment, we deployed a change to use a proper signing credential and since that time, we have not experienced the problem in that environment. That was 4 days ago.
3. Ran a load test on the QA environment with the fix in #2 to see if we could generate the issue. We could not.

RE: #2 above, it's worth noting that the environment is not set up for autoscaling and there is only 1 instance for the app service. 

We would like to believe that no longer using the temporary signing credential is the fix, but we currently do not have the means of confirming this with a test, documentation, etc. Also, the fact that this is an intermittent issue confuses things as well.

Any thoughts?

**Comment by brockallen** [comment]
Our signing cert has noting to do with the cert for TLS. So no, not really any thoughts. It sounds more like a bug in the consumer side (meaning Microsoft's code) if they choke on a TLS issue and can't re-request the discovery document (if that's really how it's failing).

**Comment by fshin123** [comment]
Brock,
Thanks for the reply. It seems like there have been several occurrences of issues that _smell_ like this one. But from what I have gathered, most/all of these are in the realm of "it's not working at all." Our issue is particularly perplexing given the erratic/unpredictable nature of it.

Hoping someone out there has experienced something similar or have any thoughts in this regard?

**Comment by brockallen** [comment]
Can you hit the discovery document in your browser without TLS errors?

**Comment by fshin123** [comment]
Yes.  I am able to access it through the browser with no TLS errors event when the error is manifesting in the back end.

**Comment by brockallen** [comment]
So then I'm at a loss. Are there logs somewhere in your servers for the error?

**Comment by fshin123** [comment]
@brockallen , right now most of our available logging for this issue is via Application Insights. I've seen other issues posted here (like this one: https://github.com/IdentityServer/IdentityServer4/issues/727) where users expressed that a similar issue is "fixed" when the temporary signing credential (.AddTemporarySigningCredential) is replaced with a fixed signing cert (.AddSigningCredential).  I am assuming in those cases, the requests were ALWAYS failing which is different from my case, where it is intermittent. However, has any connection been found between the .AddTemporarySigningCredential approach and the request for the configuration endpoint in IdentityServer?

**Comment by brockallen** [comment]
That's odd, because as I said the signing credentials is unrelated to the TLS certificate.

**Comment by fshin123** [comment]
Yes, I understand that. But there seems to be enough anecdotal evidence that smells like there is some relation for some reason-- given that several people have had the problem, made that change, and no longer had the problem...

**Comment by brockallen** [comment]
Ok, well keep investigating please. If you discover anything, let us know.

**Comment by brockallen** [comment]
Any update?

**Comment by fshin123** [comment]
Nothing solid.

The only interesting thing is that our production environment was getting the same issue (albeit less frequently than our QA environment was), when we deployed the change to production (no longer using the temporary signing cert), we stopped getting the exceptions in that environment as well. It has been almost a week now. It is intellectually tough to draw the conclusion that the issue is now fixed since there is neither firm logic or a good test to prove this out. However, the passage of time and the anecdotal evidence seen in other issue posts lends some weight...

**Comment by fshin123** [comment]
FYI-- the issue crept up again in both environments. Looks like the temporary signing cert change was not the fix. Interesting that it seemed to "fix" the issue for a relatively long period of time. However, still no good...

**Comment by leastprivilege** [comment]
any update?

**Comment by fshin123** [comment]
@leastprivilege -- unfortunately no. I found this issue: https://github.com/IdentityServer/IdentityServer4/issues/2195

It smells similar but I am unclear what the problem/solution was.

**Comment by RWillup** [comment]
Hi,

I was getting the same error message:
"Unable to obtain configuration from: 'https://.../.well-known/openid-configuration"

In my case I was using Visual Studio and noticed that I could browse the URL from Postman or other browsers.
What happens is that Postman and browsers use the system proxy, but .NET does not. 
So to fix the issue I have to provide the proxy, like so:

```
            public void Configure(string name, JwtBearerOptions options)
            {
                options.BackchannelHttpHandler = new HttpClientHandler() { Proxy = new WebProxy(_config["System:Proxy"]) };
                options.Authority = $"{_azureOptions.Instance}{_azureOptions.TenantId}";
                ...                
            }
```

**Comment by fshin123** [comment]
Robson,
Were you getting the error message intermittently or all the time? If intermittently, do you know the root cause for this?

Frank

**Comment by brockallen** [comment]
Any update?

**Comment by RWillup** [comment]
I was getting it all the time.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by debchy** [comment]
I have solved the problem. This problem is happening for proxy address which is not resolving with OIDC connection.
So, Instead of 
`options.Authority = "http://app.mycompany:5959/";`
I am now using IP address.
`options.Authority = "http://41.4.40.41:5959/";`

**Comment by weitzhandler** [comment]
@debchy that didn't help.
I have spent hours trying to solve this issue, no solution yet.
