### ISSUE TITLE
IdentityServer4.AspNetIdentity's ProfileService readonly filelds should be protected

### ISSUE THREAD

**Issue by TsengSR** [IdentityServer/IdentityServer4#2402]
The `IdentityServer4.AspNetIdentity`'s `ProfileService` readonly fields should be changed to protected, to make them accessible within the derived classes without declaring your own fields.

Right now its hard to override 

```
        public virtual async Task IsActiveAsync(IsActiveContext context)
        {
            var sub = context.Subject.GetSubjectId();
            var user = await _userManager.FindByIdAsync(sub);
            context.IsActive = user != null;
        }
```

without having to declare a new constructor in the derived class just to hold the passed instances of `IUserClaimsPrincipalFactory<TUser>` and `UserManager<TUser>`.

**Comment by brockallen** [comment]
done on dev.
