### ISSUE TITLE
How to identify Azure B2C Application Unique Id?

### ISSUE THREAD

**Issue by vetrivelmp** [IdentityServer/IdentityServer4#2405]
Hello All,
I have created two applications inside B2C. Say App1 and App2.
I have created one identity provider(IDPDemo) for pointing my identity server 4 instance.
But inside B2C, i linked same IDPDemo to both App1 and App2.

My Concern is how to identify inside my identity4 server which Azure B2C App(App1 or App2) has called to Identity server?

Any help on this would be appreciated.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
