### ISSUE TITLE
Sample for dotnet core REST api(acting as a Authenticationa and Autharization service) with identityserver4(NO UI) framework ?

### ISSUE THREAD

**Issue by saurabhdeshpande49** [IdentityServer/IdentityServer4#2407]
Hi,

As I see most of the sample provided for identityserver comes with the UI, I am trying to build a dotnet core 2.0/2.1 end point based REST api which then uses the idnetityserver for authentication and autharization.
I just dont wat to use the identityserver UI and would like to test the standalone REST api with json inputs for creating users and roles etc which then will be the identy management service for my application.

Are there any samples available where in identity framework integrated with dotnet core rest api without any UI from identity server?

**Comment by brockallen** [comment]
IdentityServer does not do identity management. That's up to your architecture to provide one. 

There are samples for using IdentityServer all programmatically: http://docs.identityserver.io/en/release/quickstarts/2_resource_owner_passwords.html
