### ISSUE TITLE
Unable to get email address claim from Yahoo API in IdentityServer4

### ISSUE THREAD

**Issue by thanatosphere** [IdentityServer/IdentityServer4#2408]
I need to get profile and email claims from external providers and I am able to do so with Google, Facebook and MS Live ID. However, I am unable to get the email claims in Yahoo.

In my Yahoo API app I specify **API Permissions** to **Profiles (Social Directory)** and selected ***Read/Write Public and Private***

In IdentityServer4 app I have specified the scope to include **sdpp-w** which supposedly should include the email address as an additional claim as stated in this [documentation][1].

Here's the snippet of my code:

**Startup.cs**

    services.AddAuthentication()
              .AddGoogle(options =>
              {
                  options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                  options.ClientId = Configuration.GetValue<string>("ExternalProviders:GoogleClientId");
                  options.ClientSecret = Configuration.GetValue<string>("ExternalProviders:GoogleSecretKey");
              })
              .AddFacebook(options =>
              {
                  options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                  options.AppId = Configuration.GetValue<string>("ExternalProviders:FacebookAppId");
                  options.AppSecret = Configuration.GetValue<string>("ExternalProviders:FacebookSecretKey");
                  options.CallbackPath = Configuration.GetValue<string>("ExternalProviders:FacebookCallbackPath");
              })
              .AddMicrosoftAccount("Microsoft", "Windows Live ID", options =>
              {
                  options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                  options.ClientId = Configuration.GetValue<string>("ExternalProviders:WindowsClientId");
                  options.ClientSecret = Configuration.GetValue<string>("ExternalProviders:WindowsSecretKey");
                  options.CallbackPath = Configuration.GetValue<string>("ExternalProviders:WindowsCallbackPath");
              })
              .AddYahoo(options =>
              {
                  options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                  options.Scope.Add("openid,sdpp-w");
                  options.ClientId = Configuration.GetValue<string>("ExternalProviders:YahooClientId");
                  options.ClientSecret = Configuration.GetValue<string>("ExternalProviders:YahooSecretKey");
                  options.CallbackPath = Configuration.GetValue<string>("ExternalProviders:YahooCallbackPath");
              });

**Config.cs**

    // scopes define the resources in your system
        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Email()
            };
        }

    // clients want to access resources (aka scopes)
        public static IEnumerable<Client> GetClients()
        {
            // client credentials client
            return new List<Client>
            {
                new Client
                {
                    ClientId = "mvc.manual",
                    ClientName = "MVC Manual Client",
                    AllowedGrantTypes = GrantTypes.Hybrid,
                    AllowAccessTokensViaBrowser = true,
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },

                    RedirectUris = { "https://mywebsite/account/signin-callback" },
                    PostLogoutRedirectUris = { "https://mywebsite/signout-callback" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        "api2"
                    },
                    AllowOfflineAccess = true
                }
            };
        }

  [1]: https://developer.yahoo.com/oauth2/guide/openid_connect/decode_id_token.html#additional-claims=

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
