### ISSUE TITLE
Idp claim is missing

### ISSUE THREAD

**Issue by s-amani** [IdentityServer/IdentityServer4#2409]
Hi, I read all the problem and comments related to this issue, I got following code from [https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/), It seems problem with idp claim is solved, but now, I have another problem, app frequently hit the following code after authentication and app falls into deadlock.
```
 public static Task UpdatePrincipal(SecurityStampRefreshingPrincipalContext context)
        {
            var newClaimTypes = context.NewPrincipal.Claims.Select(x=>x.Type).ToArray();
            var currentClaimsToKeep = context.CurrentPrincipal.Claims.Where(x => !newClaimTypes.Contains(x.Type)).ToArray();

            var id = context.NewPrincipal.Identities.First();
            id.AddClaims(currentClaimsToKeep);

            return Task.FromResult(0);
        }

```
Any advice will be helpful.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
