### ISSUE TITLE
Authorization to API endpoint with access token that differs from that which was issued

### ISSUE THREAD

**Issue by testlump** [IdentityServer/IdentityServer4#2412]
## Description

The `access_token` that is produced by Identity server can be altered and an API endpoint will still authorize a client that presents it. 

## Steps to reproduce 

The set up is that of the Client Credentials example cited here: https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/1_ClientCredentials and here http://docs.identityserver.io/en/release/topics/startup.html - three applications; IdentityServer, An API (MVC App with a single default route protected with [Authorize] attribute) and a test client that uses the IdentityModel client library. 

The Identity server issues an access token for `api1` to the requesting client (`client`) with the value: `eyJhbGciOiJSUzI1NiIsImtpZCI6IjhmNjUxNmQzMGJhOWJhZTM3NTU1MjZjZTNjMTM2MTkxIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MzAwMjMyNDIsImV4cCI6MTUzMDAyNjg0MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjpbImFwaTEiXX0.MVOKwu5gM3oi_mspin142X5k7Bsz1nub5C2Yj6d3C93rPX2V1rF0HnP9N4tHmoEfeIHOjj9w2hYJijS7wIgyMpyD00z7gl3hDxjdcHcCdjIzYgSHQQ3NAPRamBs_KUZ4esQO9_aXVzHsRs_xoXhbUUXXheSIZtNRrCBa3oqp4gZWkSXuMieYvWLVgjE8cjDTXvxFgU5P3Ho_V0bMEgcPLXqLzFajEhhF7mJD5MrloxRVnQqkPrt6U3rAhTuMbL1fsVj2G_dwUcrisy4-ad0HQ2g1sX8HWtkHWQpfV5Yt3bB1wiynT7meWk3d5ZbzEMXSPohr3es01sIKI9lwFvvqYA`

A curl request with the token to the API returns `Authorized (200 - OK)` as expected: 

```
* TCP_NODELAY set
* Connected to 10.64.112.111 (10.64.112.111) port 5001 (#0)
GET / HTTP/1.1
Host: 10.64.112.111:5001
User-Agent: curl/7.60.0
Accept: */*
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhmNjUxNmQzMGJhOWJhZTM3NTU1
MjZjZTNjMTM2MTkxIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MzAwMjMyNDIsImV4cCI6MTUzMDAyNjg0
MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAw
MC9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjpbImFwaTEiXX0.
MVOKwu5gM3oi_mspin142X5k7Bsz1nub5C2Yj6d3C93rPX2V1rF0HnP9N4tHmoEfeIHOjj9w2hYJijS7
wIgyMpyD00z7gl3hDxjdcHcCdjIzYgSHQQ3NAPRamBs_KUZ4esQO9_aXVzHsRs_xoXhbUUXXheSIZtNR
rCBa3oqp4gZWkSXuMieYvWLVgjE8cjDTXvxFgU5P3Ho_V0bMEgcPLXqLzFajEhhF7mJD5MrloxRVnQqk
Prt6U3rAhTuMbL1fsVj2G_dwUcrisy4-ad0HQ2g1sX8HWtkHWQpfV5Yt3bB1wiynT7meWk3d5ZbzEMXS
Pohr3es01sIKI9lwFvvqYA

HTTP/1.1 200 OK
Date: Tue, 26 Jun 2018 14:39:16 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked
{"hello":"world"}* Connection #0 to host 10.64.112.111 left intact
```

but if I change the last character of the token from `A` to `B`, the connection is also authorized:

```
* Connected to 10.64.112.111 (10.64.112.111) port 5001 (#0)
GET / HTTP/1.1
Host: 10.64.112.111:5001
User-Agent: curl/7.60.0
Accept: */*
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhmNjUxNmQzMGJhOWJhZTM3NTU1
MjZjZTNjMTM2MTkxIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MzAwMjMyNDIsImV4cCI6MTUzMDAyNjg0
MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAw
MC9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjpbImFwaTEiXX0.
MVOKwu5gM3oi_mspin142X5k7Bsz1nub5C2Yj6d3C93rPX2V1rF0HnP9N4tHmoEfeIHOjj9w2hYJijS7
wIgyMpyD00z7gl3hDxjdcHcCdjIzYgSHQQ3NAPRamBs_KUZ4esQO9_aXVzHsRs_xoXhbUUXXheSIZtNR
rCBa3oqp4gZWkSXuMieYvWLVgjE8cjDTXvxFgU5P3Ho_V0bMEgcPLXqLzFajEhhF7mJD5MrloxRVnQqk
Prt6U3rAhTuMbL1fsVj2G_dwUcrisy4-ad0HQ2g1sX8HWtkHWQpfV5Yt3bB1wiynT7meWk3d5ZbzEMXS
Pohr3es01sIKI9lwFvvqYB

HTTP/1.1 200 OK
Date: Tue, 26 Jun 2018 14:41:56 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Transfer-Encoding: chunked

{"hello":"world"}* Connection #0 to host 10.64.112.111 left intact
```

However, if I manipulate the last character in the token above to an `R`, the api endpoint rejects the authorization request:

```
* Connected to 10.64.112.111 (10.64.112.111) port 5001 (#0)
GET / HTTP/1.1
Host: 10.64.112.111:5001
User-Agent: curl/7.60.0
Accept: */*
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjhmNjUxNmQzMGJhOWJhZTM3NTU1
MjZjZTNjMTM2MTkxIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MzAwMjMyNDIsImV4cCI6MTUzMDAyNjg0
MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAw
MC9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjpbImFwaTEiXX0.
MVOKwu5gM3oi_mspin142X5k7Bsz1nub5C2Yj6d3C93rPX2V1rF0HnP9N4tHmoEfeIHOjj9w2hYJijS7
wIgyMpyD00z7gl3hDxjdcHcCdjIzYgSHQQ3NAPRamBs_KUZ4esQO9_aXVzHsRs_xoXhbUUXXheSIZtNR
rCBa3oqp4gZWkSXuMieYvWLVgjE8cjDTXvxFgU5P3Ho_V0bMEgcPLXqLzFajEhhF7mJD5MrloxRVnQqk
Prt6U3rAhTuMbL1fsVj2G_dwUcrisy4-ad0HQ2g1sX8HWtkHWQpfV5Yt3bB1wiynT7meWk3d5ZbzEMXS
Pohr3es01sIKI9lwFvvqYR

HTTP/1.1 401 Unauthorized
Date: Tue, 26 Jun 2018 14:52:23 GMT
Server: Kestrel
Content-Length: 0
WWW-Authenticate: Bearer error="invalid_token", error_description="The signatu
re is invalid"

* Connection #0 to host 10.64.112.111 left intact
```
I've tried a number of different characters with different access tokens and not all yield a token that differs from that which was issued but which is also authorized by the endpoint, but many do. 

Is this behaviour intentional / correct?

**Comment by brockallen** [comment]
That would be more a question for Microsoft since you're using a JWT and it's the Microsoft JWT authentication handler that's doing that validation.

**Comment by TomCJones** [comment]
not really - that is caused by padding.  MSFT converts it to binary before it is checked and not all of the bits are included in the conversion.

**Comment by leastprivilege** [comment]
This has been asked in several places before - it is due to the base64 encoding and padding. All is good ;)
