### ISSUE TITLE
Identityserver4 not working on AWS ALB Loab Balancer

### ISSUE THREAD

**Issue by sreekanthmg** [IdentityServer/IdentityServer4#2415]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

We are facing an issue deploying our application in AWS. 
We have multiple identity-service instances are running in 2 servers and we are load balancing it behind ALB. The issue is the 1st request goes to Identity server1 and if the second goes server2, it fails saying 401-unauthorized because the server 1 could not able to share the token with server2.

Following are our configuration in identity service.
We are using implicit flow and get the token using oidc_client in angular.
services.AddDeveloperIdentityServer((option) =>
            {
                option.IssuerUri = Configuration["IdentityServerOptions"]; **//http://server1_ip:61307**
            })
                .AddInMemoryScopes(clientConfig.GetScopes())
                .AddInMemoryClients(clientConfig.GetClients());

To connect to identity server in other micro services, I am using
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = Configuration["AuthorityUrl"], **//http://server1_ip:61307**
                ScopeName = Configuration["ScopeName"],       
                RequireHttpsMetadata = false,
                AutomaticChallenge = true
            });

What I have to do to make load balancing working here ?
I dont find property PublicOrigin in identityserveroptions.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
First of all - `services.AddDeveloperIdentityServer` is not a method from IdentityServer. So we can't support that.

and

> it fails saying 401-unauthorized because the server 1 could not able to share the token with server2.

I don't know what that means.

finally

IdentityServer is just a plugin to a standard ASP.NET Core application. Check the Microsoft  documentation to get that up and running behind load balancers.

https://identityserver4.readthedocs.io/en/release/topics/deployment.html
