### ISSUE TITLE
The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1

### ISSUE THREAD

**Issue by narsingraomanda** [IdentityServer/IdentityServer4#2417]
I have downloaded the source code from git hub. when i tried to run that solution i got this error. 

Severity	Code	Description	Project	File	Line	Suppression State
Error. The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.	IdentityServer.UnitTests	C:\Program Files\dotnet\sdk\2.1.2\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	135

**Comment by cguldogan** [comment]
Did you install .NET Core 2.1 SDK [.NET Core 2.1 SDK](url) ?

**Comment by leastprivilege** [comment]
I think the error message is pretty good.
