### ISSUE TITLE
EntityFramework migration to PostGreSql does not create auto-incrementing ids

### ISSUE THREAD

**Issue by MontyGvMC** [IdentityServer/IdentityServer4#2420]
I switched from MSSql to PostGreSql and let Entity Framework Core create the database using the migrations with /seed argument from the Sample Quickstart 8_EntityFrameworkStorage.

Under MSsql it worked fine but using a PostGreSql Db it has issues with the auto-incrementing ids (e.g. table Clients).

Inspecting the generated PostGreSql DB with pgadmin it shows that the default value is not set.

**Comment by brockallen** [comment]
Do you have a suggestion for how to fix the problem?

**Comment by brockallen** [comment]
Is there a way to do this in your migration creation, so we don't have to add code inside the core ef module for DB specifics?

**Comment by Mardoxx** [comment]
First link you posted told you how to do this.

In your DbContext impl:
```cs
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    //...

    // Do this for all IdSrv entitites which should auto increment
    modelBuilder.Entity<Client>()
        .Property(e => e.Id)
        .ValueGeneratedOnAdd();
}
```

**Comment by MontyGvMC** [comment]
Yeah, already forgot about that post. Thank you for your hints. For myself I fixed it by writing a create script for PostGre SQL and scaffolding the db context from that database. Within the Identity Server I still use the default provided EF db context for reading from the db.

This issue was more pointing out (for you or other users) that the provided entiy framework core db context **only** works with MS SQL databases. It supports at least reading from a PostGre SQL database (since the missing sequences do not influence reading). With the links given I wanted to provide some hints (for other users targeting PostGre SQL) how to get it done.

But this also means using migrations for creating the database with the given db context against other databases than MS SQL won't work out of the box.

Next week (and the week after) I have some days off where I plan to give myself some learning time. One thing I want to learn is how to support multiple databases with one EF Core database context. If I find the time I will learn that by experimenting with the EF core db context of the Identity Server. I hope I get it to work to support MS SQL, PostGre SQL and MySQL.

If you are interested in the results I could share my experiences.

**Comment by brockallen** [comment]
@MontyGvMC one thing we've started using to manage multiple database (instead of EF migrations) is DbUp: https://dbup.readthedocs.io/. I use migrations to get my starter SQL, then hand work it as needed. DbUp then helps apply is to the DB and deal with versioning over time.

**Comment by MontyGvMC** [comment]
If this question is into my direction: I am sorry I don't understand.

**Comment by brockallen** [comment]
@MontyGvMC I was looking for help in solving this within the core EF code we provide without making it provider specific. Otherwise, your fix is to do something in your migrations code, which is beyond this repo thus I can close the issue.
