### ISSUE TITLE
EventSource token validation

### ISSUE THREAD

**Issue by RomainWilbert** [IdentityServer/IdentityServer4#2421]
Hi,

It seems that EventSource API does not provide header support. What would be the best approach to validate tokens in that case ?

Does the IdentityServer4 AccessTokenValidation API handles query params or cookies for validating access tokens ?

Thanks

**Comment by RomainWilbert** [comment]
So best practice would to implement a CookieTokenRetriever and use it in the gateway when configuring token validation ?

**Comment by brockallen** [comment]
I don't know what your approach really entails. 

In the past I have used an access token to call an API that issues a cookie on the response. Then with the cookie you make the websocket connection.

**Comment by RomainWilbert** [comment]
I have a simple ReactJs app which authenticates on IS4 via oidc, and then i
create the eventsource which calls an Api which validates the access token
on IS4

Le jeu. 28 juin 2018 à 18:49, Brock Allen <notifications@github.com> a
écrit :

**Comment by leastprivilege** [comment]
You can use the token retriever to get tokens from any place in the incoming request - e.g. a cookie or query string param.
