### ISSUE TITLE
Logout issue in Microsoft Edge browser

### ISSUE THREAD

**Issue by smsaxena5** [IdentityServer/IdentityServer4#2425]
I am having the logout problems in the Microsoft Edge browser. I am able to log out of my Asp.Net core MVC application and I am also automatically being redirected to the IdentityServer login page. I see the following message on the console: [Information] Showing login: User is not authenticated.
If I then try to go to a url of my MVC app from which I logged out I am being redirected to the IdentityServer login page on the first try. However on the second try I am able to open it as an authenticated user.

Here is something else I noticed: The first time when I am not allowed to open the url, the OpenIdConnect OnRedirectToIdentityProvider event handler in my mvc app is being called. The second time around it is not being called.

I also put my comment on a similar issue which is now closed: https://github.com/IdentityServer/IdentityServer4/issues/2133

Update: Please disregard my comments about OnRedirectToIdentityProvider. Its wierd but today the OnRedirectToIdentityProvider event handler in my mvc app is being called every time. 
However, I noticed that on my colleagues edge broswer, the logout does not redirect to the identity server login page but redirect to the landing page of the mvc app as if the user had not logged out.

**Comment by smsaxena5** [comment]
The problem is experienced when I have signed into two mvc applications using sso. When I log out of the first app, and try to open the app again  using a link provided in the other app, it opens it on the second try. However, if I close the tabs, or try to open via the address bar I need to authenticate again.

It's the same behavior whether I log out from the client or from identity server. When logging out directly from Identity Server, the front channel logout uri is successfully being called for the first app but not for the second (it does get called if its  the only app I signed into). 

Do you have any suggestions on what else I should be checking?

**Comment by smsaxena5** [comment]
I changed the auth cookie name (Cookie.Name) in the AddCookie extension methods of both apps to be different. No difference.

Yes, they are on localhost.

**Comment by brockallen** [comment]
Any update?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
