### ISSUE TITLE
Loop in redirection between OIDC and login method.

### ISSUE THREAD

**Issue by masoud-bahrami** [IdentityServer/IdentityServer4#2430]
I have two mvc web application. The first is used to configure IdentityServer Configuration for example managing clients, secrets, apis and .. . And the Second is only used as a Identity Provider Server.

I use IdentityServer4 with asp net core 2 and Authentication 2.

The Startup Code

`

    public class Startup
    {
        public IConfiguration Configuration { get; }
        public IHostingEnvironment Environment { get; }
        public Startup(IConfiguration config, IHostingEnvironment env)
        {
            Configuration = config;
            Environment = env;
        }
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(options =>
               options.UseSqlServer(Configuration.GetConnectionString("Users")));
                            services.AddIdentity<ApplicationUser<Guid>, ApplicationRole<Guid>>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
            services.AddMvc();
            services.Configure<IISOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });
            var connectionString = Configuration.GetConnectionString("Configuration");
            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
            var builder = services.AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;
            })
                .AddAspNetIdentity<ApplicationUser<Guid>>()
                // this adds the config data from DB (clients, resources, CORS)
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = db =>
                        db.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = db =>
                        db.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    // options.TokenCleanupInterval = 15; // interval in seconds. 15 seconds useful for 
               debugging
                });
            services.AddDbContext<ConfigurationDbContext>(options =>
                options.UseSqlServer(connectionString));
            
            if (Environment.IsDevelopment())
            {
                builder.AddDeveloperSigningCredential();
            }
            else
            {
                throw new Exception("need to configure key material");
            }
            services.AddAuthentication("Cookies")
                .AddCookie("Cookies")
                .AddOpenIdConnect("openid_connect", "AAA.SSO.Configuration", a =>
              {
                  a.SignInScheme = "Cookies";
                  a.Authority = "http://localhost:5000";
                  a.ClientId = "mvc";
                  a.ClientSecret = "49C1A7E1-0C79-4A89-A3D6-A37998FB86B0";
                  a.ResponseType = "code id_token";
                  a.SaveTokens = true;
                  a.CallbackPath = new Microsoft.AspNetCore.Http.PathString("/signin-oidc");
                  a.TokenValidationParameters = new 
                         Microsoft.IdentityModel.Tokens.TokenValidationParameters
                  {
                      NameClaimType = JwtClaimTypes.Name,
                      RoleClaimType = JwtClaimTypes.Role
                  };
                  a.RequireHttpsMetadata = false;
              });
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (Environment.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }
            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseIdentityServer();
            app.UseMvcWithDefaultRoute();
        }
        }
`

and Login Method is:

`
                    [HttpGet]
                    [AllowAnonymous]
                     public async Task<IActionResult> Login(string returnUrl)
                  {
            return Challenge(new AuthenticationProperties { RedirectUri = returnUrl }, "openid_connect");
        }   
`
The client config is :

`
             yield return new Client
            {
                ClientId = "mvc",
                ClientName = "MVC Client",
                AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,
                ClientSecrets = { new Secret("49C1A7E1-0C79-4A89-A3D6-A37998FB86B0".Sha256()) },
                RedirectUris = { "http://localhost:5001/signin-oidc" },
                FrontChannelLogoutUri = "http://localhost:5001/signout-oidc",
                PostLogoutRedirectUris = { "http://localhost:5001/signout-callback-oidc" },
                AllowOfflineAccess = true,
                AllowedScopes = { "openid", "profile", "api1" }
            };
`
When i go to an authorized action, it redirect me to http://localhost:5000
and after i redirected to login and again redirect to http://localhost:5000 and ... :)

**Comment by WisdomCorp** [comment]
I also faced the same issue, it some sort of memory issue, in my case I restarted the pc and it worked. In your case just close all instance(s) of the app(s) and check or try restarting Visual studio (assuming you are using it).
hope it helps.
