### ISSUE TITLE
IdentityServer via corporate proxy

### ISSUE THREAD

**Issue by GoestaBergfeld** [IdentityServer/IdentityServer4#2433]
Hi there,

we are currently trying to implment IdentityServer4 but having problems communicating through our proxy.
Our proxy is initialized like this:

proxy = new WebProxy("http://ourproxy:xxxx",true);

and we configure our OpenIdConnect this way:

.AddOpenIdConnect("aad", "Azure AD", options =>
	{
		options.BackchannelHttpHandler = new HttpClientHandler {Proxy = proxy};
		options.ClientId = ourClientId;
		options.ClientSecret = outClientSecret;
		options.Authority = "https://login.windows.net/common/oauth2/authorize";
		options.UseTokenLifetime = true;
		options.CallbackPath = "/signin-oidc";
		options.RequireHttpsMetadata = false;
		options.GetClaimsFromUserInfoEndpoint = true;
	})
	
BUT: nothing comes to our proxy.

Are we still missing something or is there a bug in IdentityServer4?

Thanks for any advice.

Best regards,
Gösta

**Comment by leastprivilege** [comment]
All the code you are showing is from Microsoft - IdentityServer is not involve in that part.

**Comment by GoestaBergfeld** [comment]
You are absolutely right. Thought it was part of IdentityServer. Fixed the issue already.

Thanks for answering!
