### ISSUE TITLE
Redirecting to wrong uri after authorization

### ISSUE THREAD

**Issue by dnyanp** [IdentityServer/IdentityServer4#2435]
I am using Identity server 4 and client is angular application.
After authorization, user is redirecting to some other uri.

Identity Server: http://devhost/
Client Uri : http://devhost:4200

My authorize URI is:
http://devhost/connect/authorize/callback?client_id=user.management&redirect_uri=http%3A%2F%2Fdevhost%3A4200%2Fcallback1&response_type=id_token%20token&scope=openid%20profile&state=aa817b20be124695b89d2d90b715b678&nonce=368d07a84e7245c3b158f643225260b1

Redirect_uri in above authorize callback uri is= http://devhost:4200/callback1

But it is redirecting to http://devhost/callback1#id_token=.......
So, getting 404 error.
When I manually change it to  http://devhost:4200/callback1#id_token=.......
it works fine.
Anyone has any idea why the host of the redirect uri (http://devhost:4200/) is changing to host of Identity server (http://devhost/)?

**Comment by brockallen** [comment]
it's hard to say. sounds like some misconfiguration somewhere.

**Comment by dnyanp** [comment]
It was due to misconfiguration in iis url rewrite
