### ISSUE TITLE
IdentityServer + ASP.NET Core Identity: IDP using the test users instead of aspnetidentity database users

### ISSUE THREAD

**Issue by GzimH** [IdentityServer/IdentityServer4#2438]
I have this really weird issue. I changed the AddTestUsers extension method with the AddAspNetIdentity method. Somehow, ID4 server stores the test users, and ignores the users from the database.

So, I can log in with the test users even though I removed them from the configuration. When I sign out I manually redirect to "/" of identity server (main page) and I can see that as Im still logged in as Bob (test user from Config.GetUsers())

**Note**: this issue happens only if I call  "services.AddIdentity<ApplicationUser, IdentityRole>()"

### configuration
services.AddIdentityServer()
              .AddDeveloperSigningCredential()
              .AddInMemoryPersistedGrants()
              .AddInMemoryIdentityResources(Config.GetIdentityResources())
              .AddInMemoryApiResources(Config.GetApiResources())
              .AddInMemoryClients(Config.GetClients())
              .AddAspNetIdentity<ApplicationUser>();

### Issue / Steps to reproduce the problem
1. Start fresh with a simple QuickStart template of ID4 (not the one with the Asp.Net Identity Core included)
2. Follow each step of this doc http://docs.identityserver.io/en/release/quickstarts/6_aspnet_identity.html

### Relevant parts of the log file
Request starting HTTP/1.1 POST https://localhost:5001/Account/Logout application/x-www-form-urlencoded 235
dbug: IdentityServer4.Hosting.CorsPolicyProvider[0]
      CORS request made for path: /Account/Logout from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint

**Comment by brockallen** [comment]
> I have this really weird issue. I changed the AddTestUsers extension method with the AddAspNetIdentity method. Somehow, ID4 server stores the test users, and ignores the users from the database.

did you change the account controller to use ASP.NET Identity?

**Comment by GzimH** [comment]
No, I didn't see any section of the doc mentioning that. What am I supposed to change exactly?

**Comment by brockallen** [comment]
> What am I supposed to change exactly?

The logic to use ASP.NET Identity. In short, the code int eh quickstart is *your* code, not ours. Make it login the users from wherever you're managing their identities.

**Comment by GzimH** [comment]
I have an Angular App as a client, and I managed to set everything up, so "my" code at the AccountController was doing a pretty good job. Is only when I add Identity where things get nasty.

**Comment by GzimH** [comment]
What I am most curious here is how is the Id4 still using the test users and not the asp.net identity ones from the db?

**Comment by brockallen** [comment]
You should look at the ASP.NET Identity quickstart (it's slightly different): https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/tree/dev/src/Host

**Comment by GzimH** [comment]
Thanks man, I appreciate your help. You can close this issue now
