### ISSUE TITLE
CloneWithScopes in ApiResource does not clone DisplayName

### ISSUE THREAD

**Issue by klioqc** [IdentityServer/IdentityServer4#2441]
IdentityServer4/src/IdentityServer4/Models/ApiResource.cs contains method CloneWithScopes that is used when Grants for current users are shown.
For some reason this method does not clone DisplayName and because of it Grants list contains only names, not descriptive DisplayNames

**Comment by brockallen** [comment]
I can fix that. Was it causing you a problem?

**Comment by brockallen** [comment]
fixed.
