### ISSUE TITLE
Ask the name of the plug-in

### ISSUE THREAD

**Issue by Dudeping** [IdentityServer/IdentityServer4#2442]
## Does anyone know the name of the Json format plug-in used by the document?

![文档](http://docs.identityserver.io/en/release/_images/1_discovery.png)

**Comment by leastprivilege** [comment]
One of those

https://chrome.google.com/webstore/search/JSON

**Comment by veikkoeeva** [comment]
Additional note, either Firefox does a similar thing by default or I have some plugin installed.
