### ISSUE TITLE
Can't use Combined_AspNetIdentity_and_EntityFrameworkStorage sample

### ISSUE THREAD

**Issue by CeelMarten** [IdentityServer/IdentityServer4#2444]
From sample **Combined_AspNetIdentity_and_EntityFrameworkStorage**  in **SeedData.cs**  code 

```
ApplicationDbContext contextt = scope.ServiceProvider.GetService<ApplicationDbContext>();
contextt.Database.Migrate();
```
doesn't work. Intellisense says that **Database' does not contain a definition for 'Migrate'**

**Comment by Shyroby** [comment]
Are you trying to use SqlServer instead of Sqlite?
