### ISSUE TITLE
multi-tenancy openidConnect

### ISSUE THREAD

**Issue by tqduy** [IdentityServer/IdentityServer4#2445]
**I am working on the identity server 4 with multi-tenancy on Microsoft Azure AD
I meet the case that when I create a new AD, I add the AD list as array into the identity server 4**

in Appsetting.json: 
`"AzureAds": [
    {
      "AzureAdClientId": "xxxxx-xxxxx-x-x-xxxxxxxx"
      "AzureAdTenantId": "a.onmicrosoft.com"
    },
    {
      "AzureAdClientId": "yyyy-y-yy-y-y-y-yyyyyyy",
      "AzureAdTenantId": "b.onmicrosoft.com"
    }
  ],`

**I have to use the loop to add multiple the openIDConnection corresponding to the tenants like this:**
[https://imgur.com/a/uqgPza3](url)

With this approach, I have to manually select the tenant right before I login by username/password of that Azure AD:
[https://imgur.com/bPMfsw6](url)
Is there any way for me to skip the selecting AD manually, just input the user email and the identity server will choose the correct tenant for me?
thank you
@leastprivilege

**Comment by leastprivilege** [comment]
You can use the common endpoint in Azure AD

http://www.cloudidentity.com/blog/2014/08/26/the-common-endpoint-walks-like-a-tenant-talks-like-a-tenant-but-is-not-a-tenant/

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
