### ISSUE TITLE
Using Windows auth as the only IdentityProvider results in infinite loop

### ISSUE THREAD

**Issue by fablacky** [IdentityServer/IdentityServer4#2448]
Hi,
I've been learning for quite some time how to use IdSrv4 and I managed to build a small webapp acceptiong both local and windows authentication.
Lately I wanted to only offer windows as an IdentityProvider and I've been following the (excellent) quickstart code. Problem is, my requests keep looping during login and by comparing the various requests it looks like I get to the authorize endpoint without the  .AspNetCore.Antiforgery cookie embedded into the request. That's the only difference I could find between using windows auth as a secondary idp or using it as the only one. 
This is what I see when I track the various requests: 
![image](https://user-images.githubusercontent.com/17791461/42505029-d43432be-843d-11e8-9920-5457656efe67.png)
supposedly the call to the 'authorize' callback should send me to the signin-oidc endpoint..
I'm not sure what else would be useful in solving this but in the meantime I'd like to know if I'm skipping some important parts

**Comment by brockallen** [comment]
I think your ExternalLoginCallback is not properly setting the cookie at IdenittyServer. Compare our samples to what you're doing?

**Comment by fablacky** [comment]
My ExternalLoginCallback is basically the same as the commented code in your samples (aside from the check on the user). 
Like I said, I allow windows authentication as an additional button on my main login window and I'm trying to skip the login view.
I've checked every single request made in both these scenarios and the only sensible difference is in the login method:

![image](https://user-images.githubusercontent.com/17791461/42521008-0c54e4ac-8468-11e8-99d6-24be9c2efde4.png)

The working scenario - return View(wm) -  returns the login view along with a AspNetCore.Antiforgery cookie. The other one calls the externalLogin procedure, I just don't understand how obtain the antiforgery cookie since it's not referred anywhere in both the code behind or the views

**Comment by fablacky** [comment]
I've managed to include an AntiForgeryToken in my final request to the Authorize endpoint but it would still reject it and send me back to the Login action in my controller. The only way for me to go through with this scenario is customize the returnUrl and avoid using idp as an acr_value. I'm probably misusing this property but I can't figure out why. Is there any sampling showing how to skip UI login?

**Comment by leastprivilege** [comment]
if you set the idp on the incoming request - we make sure that the value of idp claim going back matches that.

Setting the idp on acr_values if for scenarios where the client wants to tell the STS to use a specific external provider.

**Comment by fablacky** [comment]
I'm not sure I understood correctly, do you mean I have to set a custom claim on my response matching the idp value on my login request?

**Comment by leastprivilege** [comment]
First of all - why are you using the acr_values at all?

**Comment by fablacky** [comment]
Because I'd like to bypass the login screen if my application has been set to use an external identity provider as a default and, if I interpreted the documentation correctly, I'm supposed to use that particular field.

**Comment by leastprivilege** [comment]
OK - so you have two types of logins? username/password and Windows.

In this case the acr_values is a way to achieve bypassing the login screen - the idp claim must then match the acr_values idp name.

**Comment by fablacky** [comment]
I wasn't even aware I had a idp claim on my responses. Anyway I checked and turns out the value on the claim was 'Windows' while the value on my acr_values field was 'windows'. Works flawlessly now. Thank you both so much!
