### ISSUE TITLE
return to login with return url = logout page after clearing the cache

### ISSUE THREAD

**Issue by mostafahedawa** [IdentityServer/IdentityServer4#2451]
#Question : i have identity server 4 with angular client using oidc client
i logged in successfully but after i clear my browser cache i logged out and redirect to login page with return url logout page : **http://localhost:55110/account/login?returnUrl=%2Faccount%2Flogout**
if there is any investigation about this case

**Comment by brockallen** [comment]
can you explain more?

**Comment by mostafahedawa** [comment]
@brockallen  after successfully logged in i try to clear the browser cache and after the browser clear it it logged me out and return to identity server login page but it carry this return url /login?returnUrl=**/account/logout** and due ton this url i return back to login after every login because of this return url if there is any explanation for it

**Comment by brockallen** [comment]
sounds like your logout page doesn't allow anonymous requests?

**Comment by mostafahedawa** [comment]
> sounds like your logout page doesn't allow anonymous requests?
> 
@brockallen  why to allow anonymous in logout ? it shouldn't allow any anonymous request in logout .

> why are you triggering this from the logout page
> what you mean here can you explain ?

**Comment by brockallen** [comment]
I can't help you with that. You've decided to code up your logout page that way. So if it's not working the want you want, then change it.
