### ISSUE TITLE
How to post data for authentication from ASP.Net MVC to IdentityServer4 login controller.

### ISSUE THREAD

**Issue by parthyee** [IdentityServer/IdentityServer4#2452]
I Have an ASP.Net MVC application with Owin configuration and IdentityServer4.
How to post data for authentication from ASP.Net MVC application to IdentityServer4 login controller.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
