### ISSUE TITLE
Operations that change non-concurrent collections must have exclusive access

### ISSUE THREAD

**Issue by jwcao** [IdentityServer/IdentityServer4#2453]
### Issue / Steps to reproduce the problem
We have had this issue happen twice in our production environment, where shortly after an app pool recycle the below exception starts throwing for every request for a refresh token or access token, the result then being that no users can log in. To fix the issue, we have to recycle the app pool.

We have never seen the issue in our testing environments, and we don't know what specifically causes it. We've since enabled more robust logging on the production servers, but at this time all we have to go on is the below exception. We are using the latest release versions of the IdentityServer4 and .Net Core packages. We are running on Windows Server 2016 with IIS set up to reverse proxy requests to kestrel. When the app pool is recycled, kestrel is restarted.

Thank you

### Relevant parts of the log file

```
Unhandled exception: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct. System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)   at Remotion.Linq.Parsing.Structure.NodeTypeProviders.MethodInfoBasedNodeTypeRegistry.GetNodeType(MethodInfo method)   at Remotion.Linq.Parsing.Structure.NodeTypeProviders.MethodInfoBasedNodeTypeRegistry.IsRegistered(MethodInfo method)   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.GetQueryOperatorExpression(Expression expression)   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToArray()   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToArray()   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)   at System.Linq.Enumerable.SelectListPartitionIterator`2.ToArray()   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)   at Remotion.Linq.QueryableBase`1.GetEnumerator()   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)   at IdentityServer4.EntityFramework.Stores.ResourceStore.FindApiResourcesByScopeAsync(IEnumerable`1 scopeNames)   at IdentityServer4.Stores.IResourceStoreExtensions.FindResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames)   at IdentityServer4.Stores.IResourceStoreExtensions.FindEnabledResourcesByScopeAsync(IResourceStore store, IEnumerable`1 scopeNames)   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessRefreshTokenRequestAsync(TokenRequestValidationResult request)   at IdentityServer4.ResponseHandling.TokenResponseGenerator.ProcessAsync(TokenRequestValidationResult request)   at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)   at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
```

**Comment by brockallen** [comment]
Do you have a larger call stack so we can know where this is happening?

**Comment by jwcao** [comment]
Thanks for your response. Unfortunately, that is the full call stack that is getting logged. It came from an ILoggerFactory provider.

**Comment by brockallen** [comment]
Oh, that line is massively long -- I missed that. I bet there's enough context in there to get started.

**Comment by sazarghani** [comment]
I got exactly that same error:

InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
System.Collections.Generic.Dictionary<TKey, TValue>.FindEntry(TKey key)
System.Collections.Generic.Dictionary<TKey, TValue>.TryGetValue(TKey key, out TValue value)
Microsoft.EntityFrameworkCore.Metadata.Internal.Model.GetDisplayName(Type type)
Microsoft.EntityFrameworkCore.Metadata.Internal.Model.FindEntityType(Type type)
Microsoft.EntityFrameworkCore.ModelExtensions.FindEntityType(IModel model, Type type)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler+IncludeLoadTreeNodeBase.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, bool trackingQuery, bool asyncQuery, ref int collectionIncludeId, QuerySourceReferenceExpression targetQuerySourceReferenceExpression)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler+IncludeLoadTreeNode.CompileCollectionInclude(QueryCompilationContext queryCompilationContext, Expression targetExpression, Expression entityParameter, bool trackingQuery, bool asyncQuery, ref int collectionIncludeId)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler+IncludeLoadTreeNodeBase.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, bool trackingQuery, bool asyncQuery, ref int collectionIncludeId, QuerySourceReferenceExpression targetQuerySourceReferenceExpression)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler+IncludeLoadTree.Compile(QueryCompilationContext queryCompilationContext, QueryModel queryModel, bool trackingQuery, bool asyncQuery, ref int collectionIncludeId)
Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CompileIncludes(QueryModel queryModel, bool trackingQuery, bool asyncQuery)
Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, bool asyncQuery)
Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, bool asyncQuery)
Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor<TResult>(QueryModel queryModel)
Microsoft.EntityFrameworkCore.Storage.Database.CompileAsyncQuery<TResult>(QueryModel queryModel)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQueryCore<TResult>(Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler+<>c__DisplayClass22_0<TResult>.<CompileAsyncQuery>b__0()
Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore<TFunc>(object cacheKey, Func<Func<QueryContext, TFunc>> compiler)
Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery<TResult>(object cacheKey, Func<Func<QueryContext, IAsyncEnumerable<TResult>>> compiler)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery<TResult>(Expression query)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync<TResult>(Expression query)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync<TResult>(Expression expression)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable<TResult>.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
System.Linq.AsyncEnumerable.Aggregate_<TSource, TAccumulate, TResult>(IAsyncEnumerable<TSource> source, TAccumulate seed, Func<TAccumulate, TSource, TAccumulate> accumulator, Func<TAccumulate, TResult> resultSelector, CancellationToken cancellationToken)
TaxMonitor.Infrastructure.UserManagement.AccountManager.GetRolesLoadRelatedAsync(int page, int pageSize) in AccountManager.cs
-
            if (page != -1)
                rolesQuery = rolesQuery.Skip((page - 1) * pageSize);
            if (pageSize != -1)
                rolesQuery = rolesQuery.Take(pageSize);
            var roles = await rolesQuery.ToListAsync();
            return roles;
        }
        public async Task<Tuple<bool, string[]>> CreateRoleAsync(ApplicationRole role, IEnumerable<string> claims)
        {
TaxMonitor.WebUi.Controllers.AccountController.GetRoles(int pageNumber, int pageSize) in AccountController.cs
-
        [HttpGet("roles/{pageNumber:int}/{pageSize:int}")]
        [Authorize(Authorization.Policies.ViewAllRolesPolicy)]
        [ProducesResponseType(200, Type = typeof(List<RoleViewModel>))]
        public async Task<IActionResult> GetRoles(int pageNumber, int pageSize)
        {
            var roles = await _accountManager.GetRolesLoadRelatedAsync(pageNumber, pageSize);
            List<RoleViewModel> list = Mapper.Map<List<RoleViewModel>>(roles);
            return Ok(list);
        }
        [HttpPut("roles/{id}")]
TaxMonitor.WebUi.Controllers.AccountController.GetRoles() in AccountController.cs
-
        [HttpGet("roles")]
        [Authorize(Authorization.Policies.ViewAllRolesPolicy)]
        [ProducesResponseType(200, Type = typeof(List<RoleViewModel>))]
        public async Task<IActionResult> GetRoles()
        {
            return await GetRoles(-1, -1);
        }
        [HttpGet("roles/{pageNumber:int}/{pageSize:int}")]
        [Authorize(Authorization.Policies.ViewAllRolesPolicy)]
        [ProducesResponseType(200, Type = typeof(List<RoleViewModel>))]
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by sazarghani** [comment]
I have a little more information: I got the error during my local tests of a asp.net core 2.1 web app + angular 6. I don't know if it is a coincidence or not, but whenever i connect to the date base on the local sql server (localdb) and then try to load the list of user roles in the web ui, I got this error. I do not any queries, just connect to the db using ssms. This is the only clue i can provide, hope it helps.

**Comment by brockallen** [comment]
@sazarghani any more info as to when this happens for you?

**Comment by sazarghani** [comment]
Unfortunately, no. I tried to reproduce it, but it seems to me that it happens quite randomly. The setup is simple: I have an asp net core 2.1 web app with a angular 6 web ui. The sql server db is used for storing users and roles. As written before, i am testing it an my computer, so there no simultaneous access to the web app. 

If find any thing new i let you know.

Thank you very much for your attention.

**Comment by Ro3A** [comment]
I just updated my app to use .net core 2.1.2 and this began happening immediately. I reverted back to 2.1.1 and the issue went away. The code production this error, in my case, is the following:

 var result = await _someDbContext.SomeTable
                .Where(x => x.Active.HasValue && x.Active.Value == true)
                .Select(x => new SomeModel
                {
                    Name = x.Name,
                    Id = x.Id
                }).ToListAsync();

**Comment by Ro3A** [comment]
I've reported the issue in .net core EntityFrameworkCore github as well.

https://github.com/aspnet/EntityFrameworkCore/issues/12713

**Comment by benaadams** [comment]
This is an intentional exception that is being thrown by the Dictionary in newer .NET Core https://github.com/dotnet/corefx/issues/28123 which indicates the dictionary is being incorrectly modified concurrently by multiple threads (it wouldn't have been detected previously and could lead to infinite loops)

**Comment by sazarghani** [comment]
I am using 2.1.1, and still see the exception, but it happens not quite often...

**Comment by benaadams** [comment]
Looks to be the issue in EntityFrameworkCore https://github.com/aspnet/EntityFrameworkCore/issues/12713

**Comment by brockallen** [comment]
Thanks for the insight, @benaadams. 

I guess we can close this @jwcao?

**Comment by jwcao** [comment]
@brockallen Looks like it. Thanks for your help.

**Comment by benaadams** [comment]
Added an issue to corefx so its easier to find in search https://github.com/dotnet/corefx/issues/31186
