### ISSUE TITLE
No Client with ID when using in memory client

### ISSUE THREAD

**Issue by harrisonengel** [IdentityServer/IdentityServer4#2455]
### Issue / Steps to reproduce the problem
I'm getting "No client with ID _" when using in-memory clients even though I have added a Client with the ID using AddInMemoryClients

		public Startup(IHostingEnvironment env)
		{
			this.hostingEnvironment = env;

			var configBuilder = new ConfigurationBuilder()
				.SetBasePath(env.ContentRootPath)
				.AddJsonFile("appsettings.json", true, true)
				.AddJsonFile($"appsettings.{env.EnvironmentName}.json", true);

			Configuration = configBuilder.Build();
		}

		public IConfiguration Configuration { get; }

		public IServiceProvider ConfigureServices(IServiceCollection services)
		{
			services.AddIdentityServer()
					.AddDeveloperSigningCredential()
			        .AddInMemoryApiResources(GetStaticResources())
					.AddInMemoryClients(GetStaticClients());
			
			services.AddMvc();

			return services.BuildServiceProvider();
		}

		public void Configure(IApplicationBuilder app, IHostingEnvironment env)
		{
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();

			}

			app.UseIdentityServer();

			app.UseMvc();   
		}
        
		private static IList<Client> GetStaticClients(){
			return new List<Client>() {
				new Client(){
                    ClientId = "myclient",
					ClientSecrets = { new Secret("myclientsecret") },
					AllowedGrantTypes = GrantTypes.ClientCredentials,
					AllowedScopes = { "clientscope" },
                    Enabled = true
				}
			};
		}

		private static IList<ApiResource> GetStaticResources(){
			return new List<ApiResource>()
			{
                new ApiResource("ApiResource", "My Api Resource")
			};
		}

	}

I would expect FindEnabledClientByIdAsync to not fail to find the client by id "myclient".

I'm using the following PS script to send the request:

```
$unencoded = "myclient:myclientsecret"
$bytes = [System.Text.Encoding]::Unicode.GetBytes($unencoded)
$token = [Convert]::ToBase64String($bytes)
$body = '{"grant_type":"client_credentials","scope":"clientscope"}'

Invoke-WebRequest -Uri $uri -Headers @{"Content-Type"="application/x-www-form-urlencoded";"Authorization"="Basic $token" } -Body $body -Method POST
```

This fails with "invalid_client". Looking at the code this means that the issue is that the in memory client store can't resolve the client by "myclient".

### Relevant parts of the log file

```
[21:25:20 Debug] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: idsrv was not authenticated.

[21:25:20 Debug] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: idsrv was not authenticated.

[21:25:20 Debug] IdentityServer4.Hosting.EndpointRouter
Request path /connect/token matched to endpoint type Token

[21:25:20 Debug] IdentityServer4.Hosting.EndpointRouter
Endpoint enabled: Token, successfully created handler: IdentityServer4.Endpoints.TokenEndpoint

[21:25:20 Information] IdentityServer4.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token

[21:25:20 Verbose] IdentityServer4.Endpoints.TokenEndpoint
Processing token request.

[21:25:20 Debug] IdentityServer4.Endpoints.TokenEndpoint
Start token request.

[21:25:20 Debug] IdentityServer4.Validation.ClientSecretValidator
Start client validation

[21:25:20 Debug] IdentityServer4.Validation.BasicAuthenticationSecretParser
Start parsing Basic Authentication secret

[21:25:20 Debug] IdentityServer4.Validation.SecretParser
Parser found secret: BasicAuthenticationSecretParser

[21:25:20 Debug] IdentityServer4.Validation.SecretParser
Secret id found: myclient

[21:25:20 Error] IdentityServer4.Validation.ClientSecretValidator
No client with id 'myclient' found. aborting

[21:25:20 Verbose] IdentityServer4.Hosting.IdentityServerMiddleware
Invoking result: IdentityServer4.Endpoints.Results.TokenErrorResult
```

I don't see anything wrong with the client ID, why would it be unable to resolve it in the ClientStore?

**Comment by brockallen** [comment]
Hmm, the above looks ok to me. So it's hard to tell from here.

**Comment by harrisonengel** [comment]
There were a couple of issues, one being the use of Unicode and another being trying to pass the parameters as Jason instead of the x-www-form-urlencoded scheme.
