### ISSUE TITLE
SqlException: Cannot insert the value NULL into column 'IsBlocked', table 'mpoint-admin-ui-api-acceptance.dbo.AspNetUsers'

### ISSUE THREAD

**Issue by SonalJadhav24** [IdentityServer/IdentityServer4#2456]
I am creating Identity server to use with AdminUI , followed tutorial to establish Identity server with AspNetIdentity. Steps followed.
1. Run AdminUI API locally .-> Migrations done -> created records of AdminUI in database

2. Run  identity server locally to create user by registration process on web page.
3. Fail to create user Error shown as 

Can anybody help on this ?  

```
A database operation failed while processing the request.

DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
SqlException: Cannot insert the value NULL into column 'IsBlocked', table 'mpoint-admin-ui-api-acceptance.dbo.AspNetUsers'; column does not allow nulls. INSERT fails. The statement has been terminated.
Applying existing migrations for ApplicationDbContext may resolve this issue

There are migrations for ApplicationDbContext that have not been applied to the database

    00000000000000_CreateIdentitySchema

An error occurred applying migrations, try applying them from the command line

In Visual Studio, you can use the Package Manager Console to apply pending migrations to the database:
```

**Comment by brockallen** [comment]
You need to have your ASP.NET Identity User class inherit from the AdminUI's IdentityExpress base class from their IdentityExpress nuget: https://www.nuget.org/packages/IdentityExpress.Identity/

**Comment by brockallen** [comment]
> If you are extending IdentityUser, I would recommend switching that dependency to IdentityExpressUser. We're releasing a blog post on the best way to do this near the end of the month.

FWIW, I have done this for some of my customers and it works well.

**Comment by SonalJadhav24** [comment]
Thanks A lot for suggestion. It solved my problem
