### ISSUE TITLE
InMemoryUser : IUser abstraction 

### ISSUE THREAD

**Issue by ChristianRiedl** [IdentityServer/IdentityServer4#246]
**InMemoryUser** is an object now living in the Quickstart namespace. When  you implement an EF based or ASPNet Identity based user store than there will be no **InMemoryUser**. I think it would be good to have an abstraction of the user object because InMemoryXxx is an implementation term and misleading for classes like **InMemoryUserProfileService** who are not bound to an in-memory implementation. 

I think now  is a good chance to change it.

I propose to define something like an **IUser** Interface and use it in 
IdentityServer4.QuickStart.InMemoryUsere
IdentityServer4.QuickStart.InMemoryUserProfileService
IdentityServer4.QuickStart.InMemoryUserResourceOwnerPasswordValidator
Host.Ui.Login.InMemoryUserLoginService

I know it is a luxury problem and I can implement my own stuff instead of using QuickStart and Host.UI but I think it would be an architectural advantage do use an interface to decouple user aspect from the InMemory implementation.

**Comment by brockallen** [comment]
So are you saying you want to mix some of these services with a real DB-backed implementation, but then use some of the other in-memory service implementations?

**Comment by ChristianRiedl** [comment]
Yes, why not. I use AspNet.Identity as persistence and with a IUser interface integration would be very nice.  I know, in real use cases it will be probably better to use own implementations for the complete Quickstart stuff.

But anyhow, this classes are not dependent  how user storage is implemented. When they use simply IEnumerable of IUser  they can be used regardless how the users are stored. 
I always tend to more generic solutions, but I know that it sometimes leads to misuse.
Where to use interfaces and where not is not easy to decide. 

I only wanted to to say that in my opinion InMemoryUser is a candidate for an interface and I see that there are a lot of changes on the way to RC1 and it would be a good chance now to introduce IUser. 

Anyway you and Dominik did a great Job !!

**Comment by brockallen** [comment]
So the IUser would have a list of claims and an is enabled flag? Or also subject id and maybe  name properties?

**Comment by ChristianRiedl** [comment]
Exactly and when you add an IUserStore interface with the methods 
```
Task <IUserStore> FindByUserAsync (string userName)
Task <IUserStore> FindByExternalProvider (string provider, string userId)
```
and an InMemoryUserStore implementation than you get an orthagonal architecture providing the same infrastructure for all types of entities. I and surely other users will be happy because, they have to write less code.

**Comment by brockallen** [comment]
I think we understand... we'll consider it.

**Comment by brockallen** [comment]
We came to a compromise by adding some helper extension methods. Thanks
