### ISSUE TITLE
Challenge creates wrong url social login

### ISSUE THREAD

**Issue by elgerm** [IdentityServer/IdentityServer4#2461]
Been pulling my hair out over this one:

When identityserver is configured to run on a relative url (say: http://example.com/identity) the challenge that's being called in externallogin replaces all the host names to 'http://example.com'. Identityserver is running in folder /identity via a reverse proxy.

For example the url to google should be:

https://accounts.google.com/o/oauth2/v2/auth?response_type=c ... etc

but the challenge calls:

http://example.com/o/oauth2/v2/auth?response_type=c ...

Only when I'm using a hostname without '/identity' like http://example.com the challenge calls the correct urls.

Setting the options.AuthorizationEndpoint hardcoded to 'accounts.google.com' also doesn't work when using a relative url for identityserver. It just always adds 'http://example.com'

**Comment by leastprivilege** [comment]
Challenge is a Microsoft API. I can't see how IdentityServer would interfere there.
