### ISSUE TITLE
AdminUI API : CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)

### ISSUE THREAD

**Issue by SonalJadhav24** [IdentityServer/IdentityServer4#2462]
Hi All,

I am working on AdminUI , Idenityserver and AdminUIAPI. I have set up my Identity server with AspNe Identity migrations , I m facing problem in accessing AdminUI API from AdminUI web.

It gives me error of CORS domain  as follows.

1. Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8082/ClaimTypes. (Reason: CORS request did not succeed).

2. Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8082/system/nop. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘(null)’).

Http://localhost:8082 - Is the AdminUI API running.

http://localhost:8083 - Is the IIS configured for AdminUI 

 Can anyone help me , how I can set up CORS headers for this AdminUI API.

Thanks
Sonal

**Comment by leastprivilege** [comment]
The best way to get support for Admin UI is by contacting RSK directly - please use

support@identityserver.com

thanks!
