### ISSUE TITLE
AdminUI API :: http://localhost:.../system/nop returns NULL

### ISSUE THREAD

**Issue by SonalJadhav24** [IdentityServer/IdentityServer4#2463]
Hi All,

I am configuring Admin UI API and Admin UI locally on IIS. When I try to access AdminUI API from UI, I get error in console as follows.
I can run independently AdminUI API. However, my UI application cannot receive any data from AdminUI API.

> 
> `XML Parsing Error: no root element found` 
Location: http://localhost:8082/system/nop

Can anybody help me on this ?

Thanks
Sonal

**Comment by leastprivilege** [comment]
The best way to get support for Admin UI is by contacting RSK directly - please use

support@identityserver.com

thanks!
