### ISSUE TITLE
Use multiple authorities in an ASP.NET API

### ISSUE THREAD

**Issue by Marcel-Lambacher** [IdentityServer/IdentityServer4#2465]
I'm working in a project with a backend component.
This backend component can (but doesn't have to be) have access to the internet.

For accessing the backend, the client musst be authenticated using OAuth and OpenId (IdentityServer4).
If the backend has a connection to the internet, the OAauth authority should be an IdentityServer4 in the internet. Otherwise, the OAuth authority should be an IdentityServer4 within the same network as the backend itself.

For integrating OAuth into the backend component, I'm using IdentityServer4.AccessTokenValidation.
Is it somehow possible, to define two Authorities at the same time?

I want to achive, that no matter which of those IdentityServers I use, the authentication is successfully on the backend.

**Comment by leastprivilege** [comment]
No - it is not designed for that.

You could register two authentication handlers - each with their own scheme name.

**Comment by Marcel-Lambacher** [comment]
Many thanks for your answer. I didn't was thinking about that solution.
In my case we can close this issue.


Best regards

Marcel Lambacher
