### ISSUE TITLE
Identityserver4 not working with https (Very Urgent)

### ISSUE THREAD

**Issue by sreekanthmg** [IdentityServer/IdentityServer4#2466]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

In my application, which is hosted in AWS, we are using identityserver 4 and it works fine with http scheme. But when DNS configured with SSL, identity server 4 started giving error. It could not able to connect to http as all identityserver4 endpoints are still referring to http. For example, when I try **https://server.identity.com/.well-known/openid-configuration**, it displays all endpoints, but with **http**, **not https**. I have tried below line of code, but still not working

app.UseForwardedHeaders(new ForwardedHeadersOptions
{
ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

Any help would be greatly appreciated

### Relevant parts of the log file

In ConfigureServices method
------------------------------------
services.AddDeveloperIdentityServer((option) =>
            {
                option.IssuerUri = Configuration["IdentityServerOptions"];
            })
                .AddInMemoryScopes(clientConfig.GetScopes())
                .AddInMemoryClients(clientConfig.GetClients());

In Configure method
-------------------------
app.UseIdentityServer();
app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                ExpireTimeSpan = TimeSpan.FromMinutes(20),
                SlidingExpiration = true
            });

```
<log goes here>
```

**Comment by sachokFoX** [comment]
@sreekanthmg I had the same issue. Fixed with adding:

```
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<ForwardedHeadersOptions>(options =>
    {
        options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
        options.RequireHeaderSymmetry = false;
        options.KnownNetworks.Clear();
        options.KnownProxies.Clear();
    });
    ...
}
```

and enabling:
```
public void Configure(IApplicationBuilder app)
{
    app.UseForwardedHeaders();
    ...
}
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
