### ISSUE TITLE
Is there a way to enforce an array even when the claim is only one?

### ISSUE THREAD

**Issue by UbhiTS** [IdentityServer/IdentityServer4#2468]
I saw a similar request for IdentityServer3 (https://github.com/IdentityServer/IdentityServer3/issues/607) and don't know if any mods have been done in ID4 to accommodate this, but it would be very nice to be able to enforce an array even if you have one element for a certain claim ... 

for example
{
"FirstName":"John",
"LastName":"Doe",
`"Role":["Admin"]`
}

In the above, the Role claim could have one or multiple values. And the problem is that the schema changes depending on if you have one role or multiple roles. 
If you have one role, you get a string value - `"Role":"Admin"`
and if you have multiple roles, you get an array of values - `"Role":["Admin","PowerUser","ReadOnlyUser"]`

This causes deserialization complexities as the client will now have to maintain multiple models.
Is there a workaround for this already somewhere ?

**Comment by leastprivilege** [comment]
I guess you could generate the JSON array yourself and set the claim using a ClaimValueType of Json.

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/IdentityServerConstants.cs#L31

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by babin93** [comment]
> I guess you could generate the JSON array yourself and set the claim using a ClaimValueType of Json.
> 
> https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/IdentityServerConstants.cs#L31

This url no longer work

Does the Json ClaimValueType still exist ? I can't find it in 2.3.2
