### ISSUE TITLE
EndSession class should be public? 

### ISSUE THREAD

**Issue by simoncowie** [IdentityServer/IdentityServer4#2469]
I am writing a custom `IEndSessionRequestValidator` so I can validates a custom `id_token_hint` (accepting a session Id from our old login system). However, I am not able to re-implement the functionality of the `ValidateCallbackAsync` method, which I don't want to alter, because I can't inject an `IMessageStore<EndSession>` type as EndSession is internal. 

Given that I shouldbe able to override the validator, and that `IMessageStore<EndSession>` seems to be [a pluggable service](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/Core.cs#L158), should `EndSession` not be public?

**Comment by brockallen** [comment]
I'll have a look (tomorrow). If we don't move very fast on this, ping me OOB, please.

**Comment by brockallen** [comment]
fixed
