### ISSUE TITLE
Limit resource actions by scope

### ISSUE THREAD

**Issue by vhe1** [IdentityServer/IdentityServer4#247]
Hi!
Is there any way I can specify that, for instance, a

- GET http:/myserver/mypath requires scope X and
- GET http:/myserver/myOtherpath requires scope Y
?
Is there some scope attribute or can I access that stuff from within the controller?

**Comment by brockallen** [comment]
You'd have to build that yourself. You might be able to use the new policy based authorization: https://docs.asp.net/en/latest/security/authorization/claims.html

**Comment by vhe1** [comment]
Thanks a lot!
That's it.

**Comment by needo2** [comment]
What is the point of AllowedScopes if you can't limit controllers to scopes without writing another framework? Please someone tell me.

**Comment by maxswann** [comment]
Take a look at this as it might help, https://github.com/IdentityServer/IdentityServer4/issues/1786
