### ISSUE TITLE
Angular 5 using Identity Server 4

### ISSUE THREAD

**Issue by FodJar** [IdentityServer/IdentityServer4#2471]
Is there any way to change access token data during refresh token call? I cant find the refresh token function inside my identity server 4 to debug, but refresh token works, the token changes on client.

btw im using oidc-client library on angular to trigger the resfresh token function

**Comment by brockallen** [comment]
The only thing we have is a flag to update access token on renewal but only with refresh tokens. If you're doing a SPA, then you're not using refresh tokens to obtain new access tokens.
