### ISSUE TITLE
Identity 4 Server with Angular

### ISSUE THREAD

**Issue by FodJar** [IdentityServer/IdentityServer4#2472]
Im using angular 5, library oidc client, to call identity server 4. my identity are inside .net core, mvc project. I dont understand how from angular, when i trigger the login function, which i suppose its call this url/connect/authorize, but in identity server it goes to account controller login get method. Anyone please help.. Tq in advance

**Comment by brockallen** [comment]
I think you need to read the specs to learn more about this.

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
