### ISSUE TITLE
Signing Certificate EKU

### ISSUE THREAD

**Issue by maganuk** [IdentityServer/IdentityServer4#2475]
This is more of a general question. I'm trying to generate a digital signing certificate on Azure Key Vault to use with Identity Server. I know the code signing EKU is 1.3.6.1.5.5.7.3.3. But say if the EKU was set to 1.3.6.1.5.5.7.3.2, 1.3.6.1.5.5.7.3.1. Will it matter?

**Comment by leastprivilege** [comment]
IIRC we can work with any cert that is allowed to sign.

**Comment by maganuk** [comment]
Thanks for the info
