### ISSUE TITLE
IdentityServer4 with ASP .NET Core 2.1- End point configurations

### ISSUE THREAD

**Issue by bijukrishnanbs** [IdentityServer/IdentityServer4#2476]
Hi All,

I am using Identity Server 4 version 2.2.0 with ASP.Net core 2.1.
I am facing some end point configuration in my Asp .net core 2.1 API.

I am pasting the configuration here,

   services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
            .AddIdentityServerAuthentication(options =>
            {
            options.Authority = "http://localhost:5000";
              options.ApiName = "Api1";
             options.ApiSecret = "secret";
            options.RequireHttpsMetadata=false;
                  
            }); 

Regards
krrish

**Comment by leastprivilege** [comment]
not enough context.
