### ISSUE TITLE
Identityserver4 redirection is not working after log in 

### ISSUE THREAD

**Issue by Manojmadhav** [IdentityServer/IdentityServer4#2477]
Version
Identiotyserver4 2.2.0
ASP.NETCore 2.0.5

Client-Authcode

 new Client {
                    ClientId = "authorizationCodeClient2",
                    ClientName = "Authorization Code Client",
                    ClientSecrets = new List<Secret> { new Secret { Value = "mysecret".Sha512() } },
                    Enabled = true,
                    AllowedGrantTypes = new List<string> { "authorization_code" }, //DELTA //IdentityServer3 wanted Flow = Flows.AuthorizationCode,
                    RequireConsent = true,
                    AllowRememberConsent = false,
                    RedirectUris =
                      new List<string> {
                           "http://localhost:5436/account/oAuth2/",
                      },
                    PostLogoutRedirectUris =
                      new List<string> {"http://localhost:5436/",},
                    AllowedScopes = new List<string> {
                        "api1"
                    },
                    AccessTokenType = AccessTokenType.Jwt
                }

Client -Implicit

                new Client
                {
                    ClientId = "js",
                    ClientName = "JavaScript Client",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowAccessTokensViaBrowser = true,
                     ClientUri = "https://localhost:5003",
                    Properties = new Dictionary<string, string>
                    {
                        { "StartLoginFragment", "/callback.html" }
                    },
                    RedirectUris =           { "http://localhost:5003/callback.html" },
                    PostLogoutRedirectUris = { "http://localhost:5003/index.html" },
                    AllowedCorsOrigins =     { "http://localhost:5003" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1"
                    }
                }

We are able to login with credentials but after redirection is not happening. ITs returning to server log in page

![image](https://user-images.githubusercontent.com/40380817/43128361-75acaa42-8f4f-11e8-8976-586f320260b2.png)

**Comment by leastprivilege** [comment]
not enough context.

**Comment by Manojmadhav** [comment]
I am trying  Auth code flow and implicit, The login with custom credentials are happening. After login server has to redirect to client URL which is mentioned in the Client config

here the urls are mentioned below

"http://localhost:5436/account/oAuth2/",

or 
 RedirectUris =           { "http://localhost:5003/callback.html" },
                PostLogoutRedirectUris = { "http://localhost:5003/index.html" },
                AllowedCorsOrigins =     { "http://localhost:5003" },

**Comment by brockallen** [comment]
Check the logs.

**Comment by Manojmadhav** [comment]
Rectified the issue, The subject property is mandatory in User object even if we don't use the same.

**Comment by jnabizada** [comment]
> Rectified the issue, The subject property is mandatory in User object even if we don't use the same.

@Manojmadhav could you please specify the type of User you are using. If you mean by User IdentityServer4.Test.TestUser or Microsoft.AspNetCore.Identity.IdentityUser?

Also can you share the code please, you used that subject property in User object?

Thanks,

**Comment by fanc-mso** [comment]
I'm having the same issue with the IdentityServer4.Test.TestUser as demo'ed in the Quickstart UI. I get to the login screen, I enter the credentials for one of the test users, credentials pass, but redirection is not working. Getting back to login page.
