### ISSUE TITLE
Redirect back to JsOidc Client fails when Identityserver4 behind IIS Reverse proxy

### ISSUE THREAD

**Issue by nigelhoward** [IdentityServer/IdentityServer4#2478]
## Description

Identityserver4 fails to re-direct back to JsOidc client redirect_uri when IdentityServer behind IIS Reverse proxy but all other clients function as expected.

### GitHub repo
For full code and more information please see the GitHub repo :- 

https://github.com/nigelhoward/IDS4_QuickStart6_DebugJsOidc

Above Repo is modified clone of the Quickstart 6_AspNetIdentity from here:-

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI

## Test setup

- Using OSX with Parallels VMs
- VS2017 project with a clone of the QuickStart 6
- Added the JsOidc client to project
- Modified QuickStart projects to use IIS Reverse proxy server domain
- IIS installed locally using a 'hijacked' domain and valid SSL
- Modified hosts files to point dns at local hijacked domain on server on 192.168.1.11

## Verified 

- Diso doc conatins correct urls
- IIS Setting server variables correctly - HTTP_X_FORWARDED_HOST etc
- Identityserver using ForwardedHeaders
- app.UseForwardedHeaders()  before app.UseIdentityServer() in config class
- Firewalls off and pings ping correct host name
- Identity server home page and links set correctly by rev proxy
- API functions correctly on htt<I></I>p://localhost:5001

## Test results

**Using htt<i></i>p://localhost:5000 for STS server** 

- Tested the MvcClient on localhost:5002 - Everything ok
- Tested the ResourceOwnerClient - Everything ok
- Tested the Client client - Everything ok
- Tested the JsOidc client on localhost:5002 - Everything ok

**Using htt<i></i>ps://www.wholesalesolar.co.uk for STS server**

- Tested the MvcClient on localhost: 7017 - Everything ok
- Tested the ResourceOwnerClient - Everything ok
- Tested the Client client - Everything ok
- Tested the JsOidc client on localhost: 7017 - Not redirecting back to client after login

**Redirect Url contains correct page (callback.html) but the host is wrong:-**

htt<i></i>ps://www.wholesalesolar.co.uk/callback.html#id_token=eyJhbGciOiJSUzI1NiIsImtpZCIetc...

**The redirect url should be like this:-**

htt<i></i>p://localhost:7017/callback.html#id_token=eyJhbGciOiJSUzI1NiIsImtpZCIetc.....

We also have an angular 6 client that uses https://github.com/damienbod/angular-auth-oidc-client library that exhibits the same behaviour

We only changed IdentityServer4.Samples-release project code where absolutley necessary so we could run these tests

## IIS Config & Rewrite rules

```xml
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="ReverseProxyInboundRule1" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="http://localhost:5000/{R:1}" />
                    <serverVariables>
                        <set name="HTTP_X_FORWARDED_HOST" value="{HTTP_HOST}" />
                    </serverVariables>
                </rule>
            </rules>
            <outboundRules>
                <rule name="ReverseProxyOutboundRule1" preCondition="ResponseIsHtml1">
                    <match filterByTags="A, Form, Img" pattern="^http(s)?://localhost:5000/(.*)" />
                    <action type="Rewrite" value="http{R:1}://www.wholesalesolar.co.uk/{R:2}" />
                </rule>
                <preConditions>
                    <preCondition name="ResponseIsHtml1">
                        <add input="{RESPONSE_CONTENT_TYPE}" pattern="^text/html" />
                    </preCondition>
                </preConditions>
            </outboundRules>
        </rewrite>
        <urlCompression doDynamicCompression="false" />
    </system.webServer>
</configuration>
```

### FYI - Hijacked domain
I had full permission to use the hijacked domain - It's my wife's shop and I did ask her :-)

**Comment by nigelhoward** [comment]
There is a also stackoverflow question about this here:

https://stackoverflow.com/questions/51477539/no-redirect-back-to-jsoidc-client-when-identityserver4-behind-iis-reverse-proxy

**Comment by nigelhoward** [comment]
Update : Some more info which makes it a little more confusing.

When IdentityServer is running as an MVC App (application pool with no managed code) the JsOidc client functions correctly. I will try and test it with Nginx as rev proxy at some point.

**Comment by brockallen** [comment]
Really hard to say. DNS issues are difficult to debug on the issue tracker.

**Comment by nigelhoward** [comment]
Hi Brock - Thank you for your reply - What makes you think it's a DNS issue?

**Comment by brockallen** [comment]
I guess I misspoke. I meant config issue (which I guess if affecting your host names, not DNS of course).

**Comment by leastprivilege** [comment]
![](https://pbs.twimg.com/media/DicNjiBUEAA4tVQ.jpg)

**Comment by nigelhoward** [comment]
Hi Brock,

It has got to be something to do with IIS because behind Nginx reverse proxy JsOidc works correctly. I can't see anything wrong with my IIS Config. After all it works for all the other clients without any issues.

## Tests to date

**No reverse proxy**

- Tested the MvcClient on localhost: 7017 - Everything ok
- Tested the ResourceOwnerClient - Everything ok
- Tested the Client client - Everything ok
- Tested the JsOidc client on localhost: 7017 - Everything ok

**Behind IIS Reverse proxy**

- Tested the MvcClient on localhost: 7017 - Everything ok
- Tested the ResourceOwnerClient - Everything ok
- Tested the Client client - Everything ok
- Tested the JsOidc client on localhost: 7017 - Not redirecting back to client after login

**Behind Nginx Reverse proxy**

- Tested the MvcClient on localhost: 7017 - Everything ok
- Tested the ResourceOwnerClient - Everything ok
- Tested the Client client - Everything ok
- Tested the JsOidc client on localhost: 7017 - Everything ok

Using Fiddler I've examined the requests between IIS and the clients and I can't see any difference between the two authorise requests for the JsOidc client when behind and then NOT behind IIS Rev proxy.

I may be getting config blind but I really can't see any issues with my IIS Config.

**Comment by brockallen** [comment]
Any update on this?

**Comment by nigelhoward** [comment]
No update I'm afraid - I can however consistently repeat above
We have implemented IDS4 and clients behind Nginx for an easier life!
But thanks for you help so far Brock Vader :-)
