### ISSUE TITLE
Preserve query string

### ISSUE THREAD

**Issue by rizksobhi** [IdentityServer/IdentityServer4#2480]
Hi,
I am using Identity server 4 with a sitefinity client. I am constructing a url to a secured api with a custom value passed in the query string. (ex: http://localhost:60876/Sitefinity?code=CfDJ8GIUky). I am trying to catch the code's value before redirecting to ID4 however the value disappears. Below is my Notification setup:

Notifications = new OpenIdConnectAuthenticationNotifications()
                    {
                        RedirectToIdentityProvider = n =>
                        {
                            // I am trying to intercept the request here to catch the query string value!
                            return Task.FromResult(0);
                        }
                    }

Any help will be appreciated.
Thank you

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
