### ISSUE TITLE
Unity Container Extension brokes discovery document endpoint

### ISSUE THREAD

**Issue by piotrekbigu** [IdentityServer/IdentityServer4#2485]
Hi,
I tried to use in my project .NET Core App with IdentityServer4 and with extension which uses Unity Container as DI instead of built in mechanism. Everything works correctly except fact that discovery endpoint stop working - it gives 404 response. I followed below link during implementation:

https://github.com/unitycontainer/microsoft-dependency-injection

Used _Identity Server 4_ version: **2.20**
Used _Unity Container Extension_ version: **2.0.10**

**Comment by brockallen** [comment]
Any update? I don't know ~~much~~ anything about the Unity Container.

**Comment by leastprivilege** [comment]
We are using the standard ASP.NET Core DI system. Especially with discovery I can't see anything complicated. 

If you have further information (exact exception message, stack trace etc) - feel free to re-open the issue.
