### ISSUE TITLE
"Id" field missing in IdentityServer4.Models.Client compared to IdentityServer4.EntityFrameworkcore.Entities.Client

### ISSUE THREAD

**Issue by rlanga** [IdentityServer/IdentityServer4#2486]
When I start up my IdentityServer application, I get a DB error in SeedData.EnsureSeedData.cs. When adding new clients to context (context.Clients.Add) , it says 'null value in column "Id" violates not-null constraint'. After comparing the Client classes from IdentityServer4.Models which is used in Config.cs; and IdentityServer4.EntityFrameworkCore.Entities which is used in SeedData.cs, I realized the first client class is lacking the Id field. Is the Id field missing in IdentityServer.models.Client on purpose? and if so, how do I program my database seeding code?

**Comment by rlanga** [comment]
I tested it with a MySQL driver and it seemed to work just fine but when I switched to npgsql (Postgres), it gave me the error.

**Comment by brockallen** [comment]
Is `Id` a nullable int? I guess I still cant' tell where/why this is happening. You will have to do some deeper research to find out.

**Comment by rlanga** [comment]
Hi, I figured it out. I was using migrations created whilst using a MySQL driver. I deleted the migrations and made fresh ones with npgsql.
Sorry for all the hassle!
