### ISSUE TITLE
Signature validation failed - unable to match keys

### ISSUE THREAD

**Issue by EPinci** [IdentityServer/IdentityServer4#2490]
### Issue / Steps to reproduce the problem

I have a aspnetcore v2.1 pair of applications:
- 1 IdentityServer4 app
- 1 Client web app using JWT middleware to consume tokens

This is the relevant code I'm using on client side:
```
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            services.AddAuthentication(options => {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                })
                .AddCookie(options => {
                    // [bunch of cookie options in here]
                })
                .AddOpenIdConnect(options => {
                    options.Authority = Configuration.GetValue<string>("Authority");
                    options.RequireHttpsMetadata = Environment.IsProduction();
                    options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                    {
                        NameClaimType = "sub",
                        RoleClaimType = "role",
                    };

                    options.ClientId = "clientId";
                });
```

**Code/setup is working on Windows.**
I'm now moving it on Linux and the same code is throwing the exception below.

### Relevant parts of the log file

```
[13:40:59 ERR] Connection id "0HLFJOFTD343U", Request id "0HLFJOFTD343U:00000001": An unhandled exception was thrown by the application.
System.Exception: An error was encountered while handling the remote login. ---> Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match keys: 'E0A8C5DDFA740788D3ECEE10E3EFC398EA703D53'
```

**Comment by EPinci** [comment]
Not really, I'm still fighting with this.
I changed the OpenID part of the code like this:
```
                    options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                    {
                        NameClaimType = "sub",
                        RoleClaimType = "role",
                    };

                    string stsDiscoveryEndpoint = string.Format("{0}/.well-known/openid-configuration", options.Authority);
                    ConfigurationManager<OpenIdConnectConfiguration> configManager = new ConfigurationManager<OpenIdConnectConfiguration>(stsDiscoveryEndpoint, new OpenIdConnectConfigurationRetriever());
                    OpenIdConnectConfiguration config = configManager.GetConfigurationAsync().Result;
                    options.TokenValidationParameters.IssuerSigningKeys = config.SigningKeys;
```
because some related articles mentioned having to manually pull the keys but nothing changed.
I still do not understand why it works on Windows and not on Linux or how to properly troubleshoot this.

**Comment by brockallen** [comment]
These are all client side issues, and not really related to IdentityServer working or not. I think you will have to reach out elsewhere (perhaps Microsoft) to get help. Sorry.

**Comment by EPinci** [comment]
I understand - can I just ask you to confirm me one thing?
I can see from the debug spew that the new code just added is actually pulling two keys from the IS4 manifest, they both have same ID and this ID does effectively not match the kid in the token from the same IS4. Is this to be expected?

**Comment by EPinci** [comment]
Actually, turns out you were right the very first time on the "sounds environmental": one DNS entry was misfiled and the client app was pulling the manifest from the wrong IS4 app.

@brockallen Sorry for your time chasing down this. :(

At least, if anyone runs into something like this, the code I added later on to pull the keys from the manifest can be used to get started in troubleshooting.
