### ISSUE TITLE
Refresh token is not redacted

### ISSUE THREAD

**Issue by yaron-idan** [IdentityServer/IdentityServer4#2492]
### Issue / Steps to reproduce the problem
When logging IdentityServer4 requests the refresh token is not redacted, even though this token is expected to be redacted. 
Attached is an example of a log file, I've manually redacted specific info not relevant to the issue (marked by <MANUAL REDACT>) and specified the refresh_token by <SHOULD_HAVE_BEEN_REDACTED>. 
Do you have any idea why is the token not redacted? It seems like sensitive information IMHO.

### Relevant parts of the log file
```
details: "{
    "ClientId": "<MANUAL REDACT>",
    "ClientName": "<MANUAL REDACT>",
    "GrantType": "refresh_token",
    "Raw": {
      "refresh_token": "<SHOULD HAVE BEEN REDACTED>",
      "grant_type": "refresh_token",
      "scope": "<MANUAL REDACT>",
      "redirect_uri": "<MANUAL REDACT>",
      "client_secret": "***REDACTED***"
    }
  }"
SourceContext: "IdentityServer4.Validation.TokenRequestValidator"
RequestId: "<MANUAL REDACT>"
RequestPath: "<MANUAL REDACT>"
Application: "<MANUAL REDACT>"
RenderedLogMessage: ""{
    \"ClientId\": \"<MANUAL REDACT>\",
    \"ClientName\": \"<MANUAL REDACT>\",
    \"GrantType\": \"refresh_token\",
    \"Raw\": {
      \"refresh_token\": \"<SHOULD HAVE BEEN REDACTED>",
      \"grant_type\": \"refresh_token\",
      \"scope\": \"<MANUAL REDACT>\",
      \"redirect_uri\": \"<MANUAL REDACT>",
      \"client_secret\": \"***REDACTED***\"
    }
  }""
LogMessageTemplate: "{details}"
```

**Comment by leastprivilege** [comment]
Might be a bug - wanna have a look yourself?

**Comment by leastprivilege** [comment]
I added `refresh_token` to the list of values to redact.

https://github.com/IdentityServer/IdentityServer4/commit/6003f606458255666dc33db00714ef0d15969061

**Comment by yaron-idan** [comment]
Thanks! I completely missed out on this issue being resolved. I'll try to patch the next one I find myself.
