### ISSUE TITLE
Identity Server 4 with ASPNET Identity on ASPNET CORE 2.1

### ISSUE THREAD

**Issue by binbsr** [IdentityServer/IdentityServer4#2494]
As AspNet Core team changes identity management from regular mvc to razor pages AND inside an area, is there a way to configure IDS4 endpoint URLs to adapt these changes while using AspNet Identity with IDS4. For example: _http://localhost:5000/account/login?returnUrl=_ need to be changed _http://localhost:5000/identity/account/login?returnUrl=_ and so on.

Or am I missing any easy way out guys.

**Comment by brockallen** [comment]
The paths to the UI pages has always been configurable: http://docs.identityserver.io/en/release/reference/options.html#userinteraction

**Comment by ScarlettCode** [comment]
I think this [doc](http://docs.identityserver.io/en/release/quickstarts/6_aspnet_identity.html) should be updated noting this

**Comment by brockallen** [comment]
This is an community driven OSS project. PRs for docs are welcome.

**Comment by alexsandro-xpt** [comment]
It's real, the docs is out of date. A some days I had to do a lot of search on the web to learn some question about ASP Net Identity and Identity Server integration and customization.

**Comment by ScarlettCode** [comment]
Can we merge [this](https://github.com/IdentityServer/IdentityServer4/pull/2008) and then we can update based off that, or should we create a new PR with changes based on what it is currently?

**Comment by brockallen** [comment]
Yes @ScarlettCode we should merge that. I do need to update it for 2.1 though.
