### ISSUE TITLE
Sample for Asp.Net Core project that hosts both API and IdentityServer

### ISSUE THREAD

**Issue by joshmouch** [IdentityServer/IdentityServer4#2495]
In all the samples I can find, the IdentityServer and the API using the IdentityServer are broken up into two projects.  Do you have a sample solution or else a set of suggested configuration for a solution that hosts both together?

There seem to be several odd things that happen in this case.  For example, when tokens are being validated, it's actually hitting a URL endpoint rather than validating locally.  There use to be a setting to change this back in IdentityServer3, but this appears to have been removed in IdentityServer4.  Another oddity is that you have to configure the Authority to whatever the API URL currently is, even though it's self-hosted.  There are a few more oddities here and there.

**Comment by HansMusterWhatElse** [comment]
you're the best Allen - thank you very much! 👍

**Comment by Greeng0** [comment]
The documentation link provided by @brockallen seems to be broken, is there a more up-to-date reference on this topic?

**Comment by yarrgh** [comment]
http://docs.identityserver.io/en/latest/topics/add_apis.html
