### ISSUE TITLE
Ability to override default authentication scheme for HttpContext.SignInAsync(...)

### ISSUE THREAD

**Issue by Mardoxx** [IdentityServer/IdentityServer4#2497]
Currently it just gets the value from `DefaultAuthenticationScheme` 

https://github.com/IdentityServer/IdentityServer4/blob/413daee4b7d0b07728ab77b08c3945e44ea97c96/src/IdentityServer4/Extensions/HttpContextAuthenticationExtensions.cs#L264-L267
https://github.com/IdentityServer/IdentityServer4/blob/413daee4b7d0b07728ab77b08c3945e44ea97c96/src/IdentityServer4/Extensions/HttpContextAuthenticationExtensions.cs#L286-L295

I'd would guess there's good reason why it's like this?

Not really sure if my use case is appropriate for such a change, but basically I was modifying an existing project to have idsrv built in, and someone had set

```cs
services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = "Bearer";
    options.DefaultChallengeScheme = "Bearer";
}).AddJwtBearer("Bearer",  opts => { /* ... */});
```

Which caused an exception when calling `HttpContext.SignInAsync(...)` because JwtBearer's handler can't be used for sign in...

One idea I had for this is to create `IdSrvCookieAuthentication` from `CookieAuthentication` something like and create associated handler. Then for idsrv sign-in we can get the scheme where handler type is `IdSrvCookieHandler` and use it.
Then for overwriting the cookie handling instead of 
```cs
services.AddAuthentication("MyCookie")
    .AddCookie("MyCookie", options =>
    {
        options.ExpireTimeSpan = ...;
    });
```

can do
```cs
services.Configure<IdSrvCookieAuthenticationOptions>(options => {
        // configure....
    });
```

Not even sure this is necessary, but I can sketch something together if you like... 🤷

Or in fact, why not have methods on idsrv builder to configure cookie auth settings, then you could always use idsrvcookieauth scheme.

**Comment by brockallen** [comment]
You can always call SignIn and pass the explicit scheme. But our design is that the DefaultSignInScheme and DefaultAuthenticationScheme are useed to know what cookie scheme you're using for your IdentityServer users.

**Comment by brockallen** [comment]
Well, then I'd question why you're trying to crap so much into the single host.

**Comment by Mardoxx** [comment]
Which, of course, would be a valid observation!

Is using the default auth scheme not assuming too much? I can create a PR with my idea if you like.

Are you able to elaborate more on https://github.com/IdentityServer/IdentityServer4/issues/2489 because it sounds like my proposal may help?
