### ISSUE TITLE
IdentityServer4 /connect/token is returning unauthorized client

### ISSUE THREAD

**Issue by vaarenyam** [IdentityServer/IdentityServer4#2498]
I have the following configuration:
![image](https://user-images.githubusercontent.com/17843577/43420227-c9f69ad4-9460-11e8-9095-e7f652042b45.png)

When I hit the /connect/token endpoint, I get the following error:

![image](https://user-images.githubusercontent.com/17843577/43420283-e2b6dfde-9460-11e8-99c2-78285a0bcd16.png)

When I change the grant type to password, I get "unauthorized_client" error:

![image](https://user-images.githubusercontent.com/17843577/43420385-20fd8022-9461-11e8-9d52-9f2a3bd6e6b8.png)

**Please help!**

**Comment by brockallen** [comment]
please check the spec: implicit clients don't use the token endpoint.

**Comment by vaarenyam** [comment]
I changed the Grant Type to one that is supported as per the documentation. However, I still get the same "unauthorized_client" error!

**Comment by leastprivilege** [comment]
You need to check the logs. Otherwise we can't help you.
