### ISSUE TITLE
Extensibility point for OAuth/OIDC with a non-JWT token

### ISSUE THREAD

**Issue by makerofthings7** [IdentityServer/IdentityServer4#250]
I'm trying to integrate a custom authentication scheme into Identity Server, using custom cryptography. What are the correct extensibility points? 

Functionally, this is similar to OIDC with the code authorization flow, however the backend-server2server communication isn't required since I'm using a certificate variant that prevents transfer of the auth-code to other parties. 

I sent an email to someone at @leastprivilege.com but got no reply on the custom work request. 

Key take aways: 
* Validation of the auth token will be with custom C# code. It's not X509 based, but is like a certificate.
* The format is JSON, but isn't a JWT.  
* A new discovery endpoint is needed (/well-known/customToken)

How to I properly engage you into this discussion?

**Comment by leastprivilege** [comment]
IdentityServer provides a number of extensibility points to customize the workflow around OpenID Connect and OAuth. 

We are not designing for extending it for custom (not in the spec) flows.

**Comment by leastprivilege** [comment]
That said - you can customize the token format using `ITokenCreationService` and nothing stops you from adding your own discovery endpoint
