### ISSUE TITLE
how to request without "https"???( await DiscoveryClient.GetAsync)

### ISSUE THREAD

**Issue by pangtuzi** [IdentityServer/IdentityServer4#2501]
run:
var disco = await DiscoveryClient.GetAsync("http://192.168.1.4:5000");
error:
 "Error connecting to http://192.168.1.4:5000/.well-known/openid-configuration: HTTPS required"

how to request without "https"
"var disco = await DiscoveryClient.GetAsync("http://192.168.1.4:5000");"//how to request without "https"

**Comment by brockallen** [comment]
There's an option on the DiscoveryClient to allow http.

**Comment by alexambrogi** [comment]
I have a similar problem
run:
var disco = await DiscoveryClient.GetAsync("http://localhost:5000");
error:
Error connecting to http://localhost:5000/.well-known/openid-configuration: An error occurred while sending the request.

**Comment by artstalker** [comment]
Hi brockallen. Where is an option? I couldn't find it on the DiscoveryClient

**Comment by brockallen** [comment]
It's the policy property, IIRC.
