### ISSUE TITLE
Passing subject to GrantConsentAsync results in redirect back to consent screen

### ISSUE THREAD

**Issue by senseibaka** [IdentityServer/IdentityServer4#2502]
`IIdentityServerInteractionService.GrantConsentAsync(AuthorizationRequest request, ConsentResponse consent, string subject = null)` optionally allows you to specify a `subject`.

I'd like to use this to specify a `subject` which acts as an 'alias' to the real user. Aliases are per-authorization-request (and become associated with the user at the consent screen).

However, if I pass this alias to `GrantConsentAsync`, and redirect the user agent to the `ReturnUrl`,
The user agent is redirected back to the consent screen.

I'd expect that the client should receive an authorization code, and be able to exchange this for an access token where the `sub` field is populated with the alias.

Have I missed something?

Thanks

**Comment by brockallen** [comment]
The subject is up to you to assign semantics to. It's the required claim issued in the authentication cookie from login and it's the value passed back to the profile service. If your code across all of those things can keep the alias version of that straight, then I can't think of anything off the top of my head that would prevent you from doing that.

**Comment by senseibaka** [comment]
Yes, I was thinking that might be the case (controlled with a call to `HttpContext.SignInAsync`, right?). 
However at the same time I'd be wanting the actual user's session to be remembered....

The alias is controlled by the client, and acts sort of like a grant session (so each time the client wants to do an auth request, they'd first need to create a new alias and supply its details). I agree, it's a bit gross, but that's the spec I have to implement 😜 

That being said, I've figured out that I can work around this by supplying my own implementation of `IAuthorizeResponseGenerator` to DI, and then modify the `ValidatedAuthorizeRequest.Subject` before it is written to the grant store. That seems to work, and the resulting access_token contains the alias subject, rather than the real subject.

It'd then be left as an exercise for the api to convert the alias back to an actual subject.

As an aside -- do you have any near-future plans to support a signed JWT being sent in an auth request? (in the `request` parameter)?

**Comment by brockallen** [comment]
>  However at the same time I'd be wanting the actual user's session to be remembered....

When you issue the claims in the login cookie you can put more claims, such as the real sub as some custom claim. Maybe that'd help?

> As an aside -- do you have any near-future plans to support a signed JWT being sent in an auth request? (in the request parameter)?

No pressing plans (there is an open issue somewhere). We do accept sponsorship to prioritize such things.

**Comment by senseibaka** [comment]
> When you issue the claims in the login cookie you can put more claims, such as the real sub as some custom claim. Maybe that'd help?

That might be an option, using the extra claims parameter on HttpContext.SignInAsync, I assume?

> No pressing plans (there is an open issue somewhere). We do accept sponsorship to prioritize such things.

Hmm, or something I could try my hand at (if I could find the time, that is...)

Thanks

**Comment by brockallen** [comment]
> That might be an option, using the extra claims parameter on HttpContext.SignInAsync, I assume?

Yes. 

So given that you have what I think you need for now, I'll close. If you run into problems reopen or open a new issue.
