### ISSUE TITLE
 all the scope and response type joined together

### ISSUE THREAD

**Issue by liugt34** [IdentityServer/IdentityServer4#2503]
centos 7.2,  docker 18.03.1-ce , nginx 1.12.2
this is the right request in my product server 
![qfbb29 v z_ cl _ vjg8](https://user-images.githubusercontent.com/8056013/43562486-6cb611e2-964f-11e8-81fb-76b9df858e52.png)

this is my request  in my test server
![rb 0 asi0k 91 o1ql6 lm](https://user-images.githubusercontent.com/8056013/43562487-6d09ec5e-964f-11e8-9f29-e48ea36b6061.png)
![s 0i4bflsml 17v 0 02uot](https://user-images.githubusercontent.com/8056013/43562488-6e2721ec-964f-11e8-82d3-2e7392461644.png)

i dont't know what happend!  anyone help?

**Comment by brockallen** [comment]
Any update?

**Comment by liugt34** [comment]
i think this problem is maked by nginx ,but i don't know how to resolve it ? i use another windows server,and use iis, and it worked well

**Comment by brockallen** [comment]
Supporting nginx is beyond what we can help you with here.
