### ISSUE TITLE
UserInfoRequestValidator should send all claims to IsActiveAsync

### ISSUE THREAD

**Issue by Lampjaw** [IdentityServer/IdentityServer4#2505]
### Issue / Steps to reproduce the problem

We just upgraded from 2.0.1 to 2.2 and ran into this change from issue #1662.
Currently UserInfoRequestValidator is sending a filtered set of claims to ProfileService.IsActiveAsync. We use the SessionId claim to verify our users in ProfileService but the claim is being removed. I think it makes sense to send all available claims when checking IsActive and to apply the filter after.

**Comment by leastprivilege** [comment]
You are correct that we are filtering claims in the userinfo endpoint.

But the real issue you are seeing is, that the access token that is used to access userinfo does not contain the session ID claim. Thus it is missing in IsActiveAsync.

OAuth access tokens don't have the concept of a session - if the sid claim is missing, you should probably ignore it in IsActive.

**Comment by leastprivilege** [comment]
Will close this - feel free to re-open if you have further questions.
