### ISSUE TITLE
Update all projects

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#2509]
* SourceLink support
* ASP.NET Core 2.1
* flatten src and test folder
* use unified .cake file

**Comment by leastprivilege** [comment]
Done for 

* IdentityServer4
* IdentityServer4.Storage
* EntityFramework.Storage

**Comment by brockallen** [comment]
EF is now updated and the QS UI has also been sync'd

**Comment by brockallen** [comment]
ASP.NET Identity now as well
