### ISSUE TITLE
IAuthenticationHandlerProvider not working as expected

### ISSUE THREAD

**Issue by Mardoxx** [IdentityServer/IdentityServer4#2519]
I can't resolve an authentication provider by its name from `IAuthenticationHandlerProvider` when using IDSrv because it's got a completely different [implementation](https://github.com/IdentityServer/IdentityServer4/blob/8aa7b020ebb52e5e721953bd3ecd4483f22b5d86/src/Hosting/FederatedSignOut/FederatedSignoutAuthenticationHandlerProvider.cs), and changed what it returns compared to the [default](https://github.com/aspnet/HttpAbstractions/blob/23783e4dba7c3ad8b7bf4ca60eb02f1c151e50a2/src/Microsoft.AspNetCore.Authentication.Core/AuthenticationHandlerProvider.cs) 😢 

I'm now wondering if I'm meant to be using this class the way I am doing... I guess it's no biggie, as I can just copy the 2LoC from the original.

**Comment by Mardoxx** [comment]
I was thinking about perhaps using `Castle.DynamicProxy`, but it's bound to break something or somewhere... it involves too many (i.e. more than 0) assumptions about how the return value is gonna be used..

**Comment by brockallen** [comment]
Sorry, I'm not following.

**Comment by Mardoxx** [comment]
`await _handlerProvider.GetHandlerAsync(_context, "name")` will return a `AuthenticationRequestHandlerWrapper` instead of the actual handler type

**Comment by Mardoxx** [comment]
It's okay I've solved what I needed to now.
