### ISSUE TITLE
Is it possible to have custom subdomain login pages?

### ISSUE THREAD

**Issue by h2chch** [IdentityServer/IdentityServer4#2521]
My objective is to have:

first.domain.com/identity/login?
second.domain.com/identity/login?
.
n.domain.com/identity/login?
Depending from which subdomain user is coming from, he will be redirected to one of the login page above. Is it possible to achieve this on IdentityServer?

**Comment by leastprivilege** [comment]
There is only one login "route" - but from there you have full control where you want to redirect the user to. Just preserve the original returnUrl and come back to that when you are done.
