### ISSUE TITLE
Windows Authentication in Identity Server 4 using API in HTML / JS Client via Ocelot

### ISSUE THREAD

**Issue by vighneshtrivedi2004** [IdentityServer/IdentityServer4#2522]
I want to use Windows Authentication in Identity Server 4 using API in HTML / JS Client, via Ocelot - API Gateway. 

I tried the knowledge base link as mentioned below:

http://docs.identityserver.io/en/release/topics/windows.html

This turns on the Windows Authentication in Identity Server using Kestrel and IIS Express.

However, on calling ExternalLogin method on AccountController gives 401 - unauthorized error. (http://localhost:5000/Account/ExternalLogin?provider=Windows&Return url=/)

I get a similar error when invoking connect/token endpoint using grant type = password and providing windows credentials in username and password fields.

The workflow I want to achieve is :

1. The user enters Windows Credentials on HTML page
2. Client sends credentials to Identity Server API via Ocelot.
3. Identity server authenticates the windows user and returns token to HTML Client.
4. HTML Client uses the token to call Microservices API.

Here, would you let us what endpoint we need to invoke and the workflow that we should follow to achieve windows authentication in Identity Server 4. We have looked at quickstart UI sample already and not able to understand the required steps for this requirement.

**Comment by brockallen** [comment]
Then build your login page to work the way you want.

**Comment by vighneshtrivedi2004** [comment]
Thank you for your response. We already have login page implemented. We want to find exact API endpoint within identity server to perform windows authentication.

Should we use connect/token endpoint or call ExternalLogin method within AccountController? Or perhaps this involves calling different endpoint?

**Comment by brockallen** [comment]
One of us is not understanding. 

> We want to find exact API endpoint within identity server to perform windows authentication.

That question doesn't make any sense to me. 

> The user enters Windows Credentials on HTML page

Which HTML page? In the client or in IdentityServer?

> Client sends credentials to Identity Server API via Ocelot.

I don't know what Ocelot is.

**Comment by vighneshtrivedi2004** [comment]
We have a HTML page for Login on the our client side where we want to achieve same functionality as the "Windows" button in the Quick Start UI sample. In other words, let us say that user enters windows credentials on this HTML page on the client side and clicks Login button, after that, how do we initiate windows authentication driven by Identity Server?

We are also struggling to use windows authentication using Identity Server for login action triggered from our HTML client page and generate token only after windows authentication is successful.

**Comment by brockallen** [comment]
Why don't you make that button trigger authorization and send an acr_value to IdentityServer with idp:windows? That way it just works with how our quickstart works and you'd get SSO from that. Other than that, I don't have any suggestions for doing it programmatically. I'm sure there are ten other ways you could get it hacked together, but the protocols all point you at doing the authentication at the token server in the browser.

**Comment by vighneshtrivedi2004** [comment]
I tried calling authorize end point using below URL but still there is no success. I am assuming you suggested to call identity server authorize endpoint for performing windows authentication:

http://localhost:5000/Authorize?scope=api1&client_id=client&response_type=id_token token&acr_values=idp:Windows&state=abc&nonce=xyz&redirect_uri=" + encodeURIComponent("http://localhost:5000")

**Comment by brockallen** [comment]
Just to be clear, I was suggesting the normal authorization request by redirecting the user's browser (not an ajax call).

**Comment by brockallen** [comment]
Any update?

**Comment by vighneshtrivedi2004** [comment]
Hi Brock,

Thank you for providing extended support. My issue here is that I am not sure on what should be ideal workflow to implement windows authentication from a HTML client which is targeting to use Identity Server for authentication and token generation.

I have read the documentation on windows authentication. It suggests to use Kestrel and IIS Express from Visual Studio with windows authentication setting as true. However, this is not enough it seems and there would be additional work-flow or tasks required to implement windows authentication.

**Comment by brockallen** [comment]
Our samples show an approach for windows authentication, and that's the most common approach. At this point, it seems that this issue does not reflect a bug or feature request within IdentityServer, so I'll close this issue. If you need commercial support to try to help you with your project, then see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

**Comment by shridhara136** [comment]
how to add window users
