### ISSUE TITLE
Check to see if we handle access denied from external IdPs in our templates

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2526]

**Comment by brockallen** [comment]
ok, no fix here. for some reason i thought the built in plumbing sent the error to the callback page. it doesn't :/

**Comment by leastprivilege** [comment]
but the QS UI should probably show how to handle external errors, no?

**Comment by brockallen** [comment]
Isn't that MS docs? You have to do it in each external handler's callback.
