### ISSUE TITLE
Reference token authorization failing with JS client and API

### ISSUE THREAD

**Issue by nloding** [IdentityServer/IdentityServer4#2528]
### Issue / Steps to reproduce the problem

In troubleshooting #2511 I decided to give reference tokens a try, as you can revoke those. I set up my API like so:

```csharp
var api = new ApiResource("my-api", "My API");
api.ApiSecrets = new List<Secret>()
{
     new Secret("abcdefghijklmnopqrstuvwxyz".Sha256())
};
```

And updated my API to use this configuration:

```csharp
            services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = Configuration["OAuthServer:Url"];
                    options.ApiName = "my-api";
                    options.ApiSecret = "abcdefghijklmnopqrstuvwxyz";
                });
                // .AddJwtBearer(options => {
                //     options.Authority = Configuration["OAuthServer:Url"];
                //     options.Audience = $"{Configuration["OAuthServer:Url"]}/resources";
                //     options.RequireHttpsMetadata = false;
                // });
```

You can see my previous config there, just for reference. I see the following in the output:

```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed for user: (null).
```

I've confirmed that my JS client is passing the access_token I received when logging in. I've confirmed this is set as the Bearer token in the request.

**Comment by brockallen** [comment]
AddIdentityServerAuthentication uses Bearer as the scheme. Is IdentityServerAuthenticationDefaults.AuthenticationScheme the same? 

Also, do you have a UseAuthentication in your MW pipeline?

Any logs in the API?

**Comment by nloding** [comment]
@brockallen I copied that code snippet directly from the docs. Not sure what you mean if `IdentityServerAuthenticationDefaults.AuthenticationScheme` is the same? I do have `app.UseAuthentication()`, and it does work perfectly (except for my subdomain logout issue #2511) with JWT tokens. It's the switch to reference tokens that is wonky.

Nothing obvious in the API logs. I'll turn up the logging tomorrow on everything and see what I get.

**Comment by nloding** [comment]
@brockallen here is the full debug output when I make a request (actually a few requests) after authenticating: https://gist.github.com/nloding/863f458f441fd14505daa36bc3ccc849

I removed the `IdentityServerAuthenticationDefaults.AuthenticationScheme` setting, so it's just `services.AddAuthentication()` - the log was identical.

I also forgot to include versions:
IdentityServer4.AspNetIdentity: 2.1.0
IdentityServer4: 2.1.3
IdentityModel: 3.5.0
IdentityServer4.AccessTokenValidation: 2.5.0
all running in AspNetCore 2.0.0

**Comment by nloding** [comment]
Also, here is a longer debug log, that starts from when I click "Login" and authenticate, through to the failed requests when the login callback completes: https://gist.github.com/nloding/dd363fc035a9cf54bdf624560d31e717

**Comment by leastprivilege** [comment]
I don't see a call to the introspection endpoint..

**Comment by nloding** [comment]
@leastprivilege I don't either - I was curious about that, but didn't know if it should hit checksession first. Using `AddIdentityServerAuthentication` should call the introspection endpoint, shouldn't it? I'm not sure at this point how I can determine if there's a bug with IdentityServer or an issue with my configuration.

**Comment by leastprivilege** [comment]
Also check the logs in the API.

**Comment by nloding** [comment]
@leastprivilege there is no call made to the introspection endpoint, just checksession. Here is the full log with all log levels set to `Debug` on the API. https://gist.github.com/nloding/6733f8562302dd5351be49d89bc0444a

This seems to be a bug. Per the docs, just using `AddIdentityServerAuthentication` should call the introspection endpoint automatically. And it's not.

Some additional details: I'm using the `oidc-client-js` for managing my SPA, and using the `access_token` off the user object returned from that, setting that as the Bearer token in my requests. I've confirmed that the token is present in the HTTP requests. If I switch my configuration back to use JWTs (per the commented code above), it works just fine.

If I change the access token type on the client configuration to JWT, and I remove the API secret, and set it up like described here https://identityserver4.readthedocs.io/en/release/topics/apis.html#the-identityserver-authentication-handler - it fails with JWTs also, with nearly identical logs.

**Comment by leastprivilege** [comment]
I'd want to see the logs of the API **only**

**Comment by nloding** [comment]
Aha, some success! I added the following options:

```csharp
.AddAuthentication(options => { 
     options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme; 
     options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme; 
})
```

... and now the introspection endpoint is called. Here are the logs: https://gist.github.com/nloding/644685325a7bb3d761ebd2a088fac76f

Doesn't look like `AddIdentityServerAuthentication` uses the Bearer scheme by default, perhaps?

Unfortunately, the Identity UserManager isn't able to find the user (`_userManager.GetUserAsync(HttpContext.Principal)`). That may be a separate issue? Not sure at this point, it is able to pull the user when using the JWT tokens and `AddJwtBearer`.

**Comment by leastprivilege** [comment]
You should always set the default scheme.

see here

https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Clients/src/SampleApi/Startup.cs#L29-L64

**Comment by nloding** [comment]
I had it set per the docs here: https://identityserver4.readthedocs.io/en/release/topics/apis.html#the-identityserver-authentication-handler

`services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)` but that isn't the same scheme, it seems.

Now I just need to figure out why my user is null, even though it shows the right ID in the logs ("Authorization was successful for user: 120764.") I have not set up any custom claims - are the default claims different for a reference token vs. a JWT?

**Comment by leastprivilege** [comment]
no - they are the same.

you can choose whatever scheme names you want - as long as they match.

**Comment by nloding** [comment]
Shouldn't it have worked with that previous set up, then? The only change I made was from:

`.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)`

to

```csharp
.AddAuthentication(options => { 
     options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme; 
     options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme; 
})
```

**Comment by leastprivilege** [comment]
look at the snippet I sent you.

**Comment by nloding** [comment]
I'll submit an update to the docs - that first parameter in `AddIdentityServerAuthentication` is not in the docs.

I also figured out the null user issue - I had to add this line to `AddIdentity`: `config.ClaimsIdentity.UserIdClaimType = "sub";`

Thanks for all your hard work on this library!

**Comment by brockallen** [comment]
> I also figured out the null user issue - I had to add this line to AddIdentity: 
> config.ClaimsIdentity.UserIdClaimType = "sub";

We have an extension method to add ASP.NET Identity into IdentityServer.

**Comment by nloding** [comment]
@brockallen I am using that. And everything works great with JWTs, but when I switched to reference tokens I had to add this line for `UserManager.GetUserAsync` to find the user.

**Comment by brockallen** [comment]
Right, and why in your API project would you be referencing ASP.NET Identity? That's somewhat counter intuitive. The identity of the user should be delivered to your API via the access token.
