### ISSUE TITLE
IdentityServerAuthenticationOptions cannot be provided per tenant

### ISSUE THREAD

**Issue by himalpatel81** [IdentityServer/IdentityServer4#2529]
Implement a class that inherit from "IOptionsMonitor<IdentityServerAuthenticationOptions>" and override the "Create" method. Create method in my case identity the tenant based on the host name and set the related "Authority: & "APIName". 

In the Startup.cs, register the Singleton using following code. 
`ervices.AddSingleton<IOptionsMonitor<IdentityServerAuthenticationOptions>, IdentityServerTenantProvider>();`

For the first tenant call, it works fine. But when the second tenant makes the request, it still uses the APIName and Authority of the first tenant.  Create method is getting called for the second tenant and trying to set the proper "Authority" & APIName but it is not being set.

**Comment by brockallen** [comment]
We don't support that, sorry.

**Comment by rhtnr** [comment]
@himalpatel81 Were you able to get the options to work dynamically per request or tenant?
