### ISSUE TITLE
Add caching for introspection

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#253]

**Comment by brockallen** [comment]
Looks like it might be best for this on the `IPersistedGrantService` for the `GetReferenceTokenAsync`.

**Comment by brockallen** [comment]
Also, caching on IsActive?

**Comment by brockallen** [comment]
>  Also, caching on IsActive?

I decided that I'd not want a built in IsActive cache -- it's simple enough for a customer to do that themselves.

**Comment by brockallen** [comment]
The other place we could do caching is on the `TokenValidator.ValidateAccessToken` which is called from both introspection and userinfo endpoints. It's an easy cache key (the token itself).

**Comment by brockallen** [comment]
Postpone -- we need something more clever and into the token validator itself.

**Comment by brockallen** [comment]
Too scenario specific to provide a default implementation that will work for most scenarios. Can be done manually with a custom IReferenceToken store that does caching.
