### ISSUE TITLE
Issue with Implicit flow quickstart and default authentication cookie lifetime

### ISSUE THREAD

**Issue by shaikatz** [IdentityServer/IdentityServer4#2530]
### Issue / Steps to reproduce the problem
Set up a an external TicketStore, and use the Implicit flow quickstart, identityserver will start to generate exceptions.

The problem is that the default cookie expire timespan is 10 hours, but the quickstart does not set `AuthenticationOptions` `IsPersistent` field to true.

The flow is that user is login, getting a session cookie, and doesn't close the browser, after 10 hours, the cookie is still alive (because it's session cookie without expiration) the identity server will try to retrieve the ticket from the external database and will get a null value.

Looking at https://docs.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-2.1&tabs=aspnetcore2x It's written that 
```
   IsPersistent = true,
    // Whether the authentication session is persisted across 
    // multiple requests. Required when setting the 
    // ExpireTimeSpan option of CookieAuthenticationOptions 
    // set with AddCookie. Also required when setting 
    // ExpiresUtc.
```

**Comment by brockallen** [comment]
> The problem is that the default cookie expire timespan is 10 hours, but the quickstart does not set AuthenticationOptions IsPersistent field to true.

I don't follow. These values are legal, as they are saying the cookie should expire in 10 hours but not be persistent. Setting a 10 hour cookie does not require it to be persistent.

**Comment by shaikatz** [comment]
The exception was thrown by my own implementation of TicketStore,
The issue that I see here is that I couldn't anticipate requests that their token was expired since the cookie has a life time of 10hours, and my redis cache expiry set to 10 hours.

But, because we don't set the cookie to be persisted, it doesn't have 10 hours expiry in the client side (because it's a session), and he send a request with expired cookie. 

So as I quoted from .NET documentation, when setting an expiry to the token, we should make the cookie persistent, to enforce the expiry that we set.

It might no be a bug, but maybe a confusion or me misunderstand the design.
let me know what you think about that.

**Comment by brockallen** [comment]
I think your token store just returns null if you can't find a matching item.

**Comment by shaikatz** [comment]
I know how to fix my store implementation to prevent the exception.
I just think that the behaviour of the cookie (session and not 10 hours expiry because of the persistent false) is counter intuitive.

**Comment by brockallen** [comment]
Well, to me it makes perfect sense. I do agree with you that the docs on the IsPersistent flag are confusing. I read the comment you pasted several times and it still doesn't make much sense to me, and if you take it at face value the comment is wrong (if not misleading). I'd suggest opening an issue with Microsoft.
