### ISSUE TITLE
More than twenty 'IServiceProvider' instances warning.

### ISSUE THREAD

**Issue by kieronlanning** [IdentityServer/IdentityServer4#2531]
I've also posted this in the Entity Framework Core issues repro, but I think it maybe related to IdSrv4's use of EF...

[Issue: 12927](https://github.com/aspnet/EntityFrameworkCore/issues/12927)

This is the issue as it stands, but I'll add a little more detail after:

When using EF Core 2.1.1 after a number of calls into my service I start seeing the following warning:

> More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework. This is commonly caused by injection of a new singleton service instance into every DbContext instance. For example, calling UseLoggerFactory passing in a new instance each time--see https://go.microsoft.com/fwlink/?linkid=869049 for more details. Consider reviewing calls on 'DbContextOptionsBuilder' that may require new service providers to be built.

I've followed the instructions details in the link in the warning, and from Issue #10235 but still the warning occurs.

The contexts all use the same `ILoggerFactory` by using the `UseLoggerFactory` extension:

```
services.AddDbContext<ApplicationDbContext>(
    builder =>
        {
            builder
                .UseLoggerFactory(LoggerFactory)  // <-- Passed in during App class start-up in the constructor.
                .UseSqlServer(defaultSqlConnectionString, options => options.MigrationsAssembly(migrationsAssembly));
        });
```

EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

-------------------------------------------------------------------------

I have two services which make use of EF Core, one runs absolutely fine and never spits out that warning, despite trying to force it to happen - lots of SQL heavy calls.

However, the other one is my Identity Server 4 service. 

With the use of the `ConfigurationDbContext` and the `PersistedGrantDbContext` I can't see anywhere I can easy add the call to `.UseLoggerFactory`, as per the explanation in the link from the warning.

Out of all my research, I can't see or think of anywhere else it could be - I'm ensuring every `DbContext` I manually register uses that single instance of the `LoggerFactory`.

**Comment by brockallen** [comment]
Can you reproduce this with our EF host sample?

**Comment by kieronlanning** [comment]
@brockallen I’ll give it a go over the next few days and report back.

**Comment by brockallen** [comment]
Please use the dev branch, as we've made several update recently. Thanks.

**Comment by kieronlanning** [comment]
@brockallen Does that include the use of the `.UseLoggerFactory`?

**Comment by brockallen** [comment]
I don't think so.

**Comment by Mardoxx** [comment]
Post impl of `LoggerFactory`

**Comment by kieronlanning** [comment]
@brockallen I think it's safe to close this report now.

On the linked issue in the EF Core repro, it seems lots of people have this issue, and it does seem like it's related to the way Autofac is handling some of the `DbContext` related registration, so unrelated to IdentityServer 4 I'd say.

Thanks for your support!
