### ISSUE TITLE
add identity method and return 404

### ISSUE THREAD

**Issue by liugt34** [IdentityServer/IdentityServer4#2535]
i have write a user account webapi , so i useed the identity in the code
in the Startup.cs ,,i add this method
`services.AddIdentity<ApplicationUser, ApplicationRole>().AddEntityFrameworkStores<ApplicationDbContext>().AddDefaultTokenProviders();`

but it return 404 error

![tim 20180809114123](https://user-images.githubusercontent.com/8056013/43876807-345fe352-9bc9-11e8-8a9d-656ee86c97d8.png)

when i comment it ,and it return 401,and the authorize worked.

and so ,how can i use the addidentity and at the same time make the authorize worked!

**Comment by leastprivilege** [comment]
I can't see how this is an issue with IdentityServer. Please use one of the support options here:

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
