### ISSUE TITLE
No migrations were applied. The database is already up to date for ConfigurationDbContext - Ref Example Client :Combined_AspNetIdentity_and_EntityFrameworkStorage

### ISSUE THREAD

**Issue by kotikavoori** [IdentityServer/IdentityServer4#2538]
im trying to use this example from git repo : Combined_AspNetIdentity_and_EntityFrameworkStorage , For some reason im able to use only IdentityDB in Sqlite DB.Not able to migrate or update  ConfigurationDbContext

### Issue / Steps to reproduce the problem
Checkout the repo
do update database - context ConfigurationDbContext , the sqlite.db[ASpidUsers.db] wont get updated..the message in console is No migrations were applied. The database is already up to date.

Am i missing something ?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by kotikavoori** [comment]
@brockallen please check this one

**Comment by brockallen** [comment]
I just ran the "ef database update" for both DbContexts for that QS sample and it worked fine. I don't know why you have that error. But if it says the DB is there, then it should be fine.
