### ISSUE TITLE
Consider Add or Replace Endpoint extension method

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2539]

**Comment by brockallen** [comment]
For this, we already have a AddEndpoint -- perhaps this impl shoul[d just change to put the item in front?

**Comment by brockallen** [comment]
I suspect we'll be reworking in terms of endpoint routing at some point, and AddEndpoint already works, I'm closing this.

**Comment by VictorioBerra** [comment]
Did this show up in the release notes as an enhancement because it was attached to a milestone even though this issue resulted in no changes?

**Comment by brockallen** [comment]
I think you're right -- there was no action here in 2.5 IIRC.
