### ISSUE TITLE
Discuss throttling

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#254]
* entire server?
* particular endpoint?
* status codes?

**Comment by Lutando** [comment]
Should this be part of IdentityServer4? seems like something that would be best tackled by just using another [middleware](https://github.com/stefanprodan/AspNetCoreRateLimit) which has the configurability to throttle endpoint(s)

**Comment by leastprivilege** [comment]
I agree - that's why this issue is called "discuss" ;)

**Comment by brockallen** [comment]
I only think there are 2 places that might need this -- userinfo and introspection, and I think these possible caching considered here: https://github.com/IdentityServer/IdentityServer4/issues/253#issuecomment-252445187 will be sufficient in addressing any flooding issues.

**Comment by brockallen** [comment]
The kind of throttling we were discussing would need to be done more inside IdSvr with more intelligence, so this issue will be the main one to satisfy this: https://github.com/IdentityServer/IdentityServer4/issues/253
