### ISSUE TITLE
Use Service Fabric Reliable Collection for Identity server

### ISSUE THREAD

**Issue by PrabhujiMudragalla** [IdentityServer/IdentityServer4#2542]
Hi Team, 

We are using Service Fabric(.Net Framework) for our application, so we are in a plan to migrate Identity Server Web application to Service Fabric Stateful service with Reliable collections. Can you provide necessary steps to migrate the database tables to Reliable collections and necessary steps to migrate the web application.

**Comment by brockallen** [comment]
No, sorry. We don't have any information on that.
