### ISSUE TITLE
Migrate Identity Server 3 to Service Fabric 4

### ISSUE THREAD

**Issue by PrabhujiMudragalla** [IdentityServer/IdentityServer4#2543]
Do we have any steps to migrate ASP.NET Identity server 3 to the ASP.NET Identity server 4 for DotNet Framework >4.6 application?

**Comment by brockallen** [comment]
We don't have any thing specific. I'd suggest starting with our quickstarts, then from that knowledge you'd have to take what you have for IS3 and plan for yourself moving to IS4.

**Comment by PrabhujiMudragalla** [comment]
Thanks for the update Allen. 
Do we have any quick start for Identity Server 4 with .Net Framework

**Comment by brockallen** [comment]
Yes, consult the docs.

**Comment by PrabhujiMudragalla** [comment]
Hi Allen, 
There are only blogs that says it supports in .Net Framework but there are no samples or reference to implementation in .Net Framework 4.6

We can't introduce .Net Core to our existing environment as there are some Nugets dependent on .Net Framework. So can you guide me how to implement Identity Server 4 in .Net Framework

**Comment by brockallen** [comment]
> So can you guide me how to implement Identity Server 4 in .Net Framework

IdentityServer is just a library that targets netstandard. Just build your ASP.NET Core app targeting .NET framework. Consult Microsoft with how to do that.
