### ISSUE TITLE
IdentityServer4 Asp.Net Core Identity does not redirect back to client

### ISSUE THREAD

**Issue by MichalJana** [IdentityServer/IdentityServer4#2544]
I have basic IdentityServer4 with Asp.Net Core Identity. After redirecting to the login page and signing in, IdentityServer does not redirect me back to the client. I have already tried to post here [https://stackoverflow.com/questions/51683801/identityserver4-asp-net-core-identity-does-not-redirect-back-to-client](url) without success. 

Here is repository with the solution:
[https://github.com/MichalJana/IdentityServerExample](url)

**Comment by brockallen** [comment]
Do the samples work for you? If so, then this doesn't seem to be a bug or problem with IdentityServer itself.
