### ISSUE TITLE
Signout prompt is not showing when ClientId is available

### ISSUE THREAD

**Issue by ltduy** [IdentityServer/IdentityServer4#2546]
I'm getting issue with QuickStart.UI when Signout prompt is not show up when try to signout from client because ``ShowSignoutPrompt`` is always ``false`` when client is available

https://github.com/IdentityServer/IdentityServer4/blob/706b3d1618547d7bc264693f7b2cd0333ad8faef/src/Models/Messages/LogoutRequest.cs#L177

Should it be something like this?
````csharp
public bool ShowSignoutPrompt => ClientId.IsPresent(); 
````

**Comment by brockallen** [comment]
ClientId is present when the client has authenticated the signout request with the id_token_hint, therefore we don't need to prompt for signout. So the current logic is correct. If you always want to prompt then feel free to change the UI logic.

**Comment by ltduy** [comment]
Thank you! I'm closing this issue now
