### ISSUE TITLE
Client Credentials developer portal

### ISSUE THREAD

**Issue by danutzplusplus** [IdentityServer/IdentityServer4#2547]
Hi,

This is a feature request or a question with regards to how safe this would be.
How doable, in a secure manner of course, would a developer portal be on the identity server, where 3rd party users of your identity server could access an admin page where they can set their own client secret. Thus eliminating this management issue, and having the client owner handle this. 

I realize this would introduce the need to handle a new set of user credentials that they can use to authenticate. So, maybe this is not worth it? Looking at other platforms, this is how they seem to do it, but they already have user accounts that they can use to authenticate requests that try manage the client credentials.

I searched for something similar on the items, and couldn't find anything. So I hope I didn't miss anything.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
