### ISSUE TITLE
What will be ExternalLoginConfirmation work with Azure AD external login with ASP.NET Idenity in Identity Server4

### ISSUE THREAD

**Issue by newlearner88** [IdentityServer/IdentityServer4#2548]
I am using ASP.NET Core 2.0 , follow below article to get work with asp.net identity in IdenityServer4:

http://docs.identityserver.io/en/release/quickstarts/6_aspnet_identity.html

After add Azure AD login , i modify the ExternalLoginCallback as document show 
`       

       // read external identity from the temporary cookie
        var result = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
        if (result?.Succeeded != true)
        {
            throw new Exception("External authentication error");
        }

        // retrieve claims of the external user
        var externalUser = result.Principal;
        if (externalUser == null)
        {
            throw new Exception("External authentication error");
        }

        // retrieve claims of the external user
        var claims = externalUser.Claims.ToList();

        // try to determine the unique id of the external user - the most common claim type for that are the sub claim and the NameIdentifier
        // depending on the external provider, some other claim type might be used
        var userIdClaim = claims.FirstOrDefault(x => x.Type == JwtClaimTypes.Subject);
        if (userIdClaim == null)
        {
            userIdClaim = claims.FirstOrDefault(x => x.Type == ClaimTypes.Upn);
        }
        if (userIdClaim == null)
        {
            throw new Exception("Unknown userid");
        }

        var externalUserId = userIdClaim.Value;
        var externalProvider = userIdClaim.Issuer;
        return View("ExternalLogin", new ExternalLoginViewModel { Email = externalUserId });`

The next page identity server will show whether create a new user with AAD user's upn , when clicking confirm , it turns out to ExternalLoginConfirmation function , now i am confused about how to modify this part of codes :
`        

        if (ModelState.IsValid)
        {
            // Get the information about the user from the external login provider
            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                throw new ApplicationException("Error loading external login information during confirmation.");
            }
            var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
            var result = await _userManager.CreateAsync(user);
            if (result.Succeeded)
            {
                result = await _userManager.AddLoginAsync(user, info);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    _logger.LogInformation("User created an account using {Name} provider.", info.LoginProvider);
                    return RedirectToLocal(returnUrl);
                }
            }
            AddErrors(result);
` 

If i use : var info = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);

It will threw error .

**Comment by brockallen** [comment]
You might need to use the ASP.NET Identity API on the SignInManager to get the external user. It all depends how you setup your external authentication.

**Comment by newlearner88** [comment]
Could you help please tell me how to sue SignInManager to get the external user , it always return null . I set as

 services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            // Add application services.
            services.AddTransient<IEmailSender, EmailSender>();

            services.AddMvc();

            // configure identity server with in-memory stores, keys, clients and scopes
            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddInMemoryPersistedGrants()
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddInMemoryClients(Config.GetClients())
                .AddAspNetIdentity<ApplicationUser>();


            services.AddAuthentication(auth =>
            {
                auth.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                auth.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
                auth.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }).AddCookie()
          .AddOpenIdConnect("AAD", "Azure Active Directory", options =>
          {
              options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
              options.SignOutScheme = IdentityServerConstants.SignoutScheme;
              options.Authority = "https://login.microsoftonline.com/xxxx.onmicrosoft.com";
              options.ClientId = "xxxxxxxxxxxxxxxxxxxxxx";
              options.Scope.Add("openid");
              options.Scope.Add("profile");
              options.TokenValidationParameters = new TokenValidationParameters
              {
                  ValidateIssuer = false
              };
              options.GetClaimsFromUserInfoEndpoint = true;
          });

**Comment by newlearner88** [comment]
After some research , i modify codes in ExternalLoginCallback : 

            var result1 = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
            if (result1?.Succeeded != true)
            {
                throw new Exception("External authentication error");
            }

            // retrieve claims of the external user
            var externalUser = result1.Principal;
            if (externalUser == null)
            {
                throw new Exception("External authentication error");
            }

            // retrieve claims of the external user
            var claims = externalUser.Claims.ToList();

            // try to determine the unique id of the external user - the most common claim type for that are the sub claim and the NameIdentifier
            // depending on the external provider, some other claim type might be used
            var userIdClaim = claims.FirstOrDefault(x => x.Type == JwtClaimTypes.Subject);
            if (userIdClaim == null)
            {
                userIdClaim = claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
            }
            if (userIdClaim == null)
            {
                throw new Exception("Unknown userid");
            }

            var externalUserId = userIdClaim.Value;
            var externalProvider = userIdClaim.Issuer;


            // Sign in the user with this external login provider if the user already has a login.
            var result = await _signInManager.ExternalLoginSignInAsync("AAD", userIdClaim.Value, isPersistent: false, bypassTwoFactor: true);
            if (result.Succeeded)
            {
                _logger.LogInformation("User logged in with {Name} provider.", "AAD");
                return RedirectToLocal(returnUrl);
            }
            if (result.IsLockedOut)
            {
                return RedirectToAction(nameof(Lockout));
            }
            else
            {
                // If the user does not have an account, then ask the user to create an account.
                ViewData["ReturnUrl"] = returnUrl;
                ViewData["LoginProvider"] = "AAD";
                var email = claims.FirstOrDefault(x => x.Type == ClaimTypes.Upn).Value;
                return View("ExternalLogin", new ExternalLoginViewModel { Email = email });
            }

And in ExternalLoginConfirmation : 

            if (ModelState.IsValid)
            {
                var result1 = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
                // Get the information about the user from the external login provider
                // var info = await _signInManager.GetExternalLoginInfoAsync();
                if (result1 == null)
                {
                    throw new ApplicationException("Error loading external login information during confirmation.");
                }
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await _userManager.CreateAsync(user);
                if (result.Succeeded)
                {
                    // retrieve claims of the external user
                    var externalUser = result1.Principal;
                    if (externalUser == null)
                    {
                        throw new Exception("External authentication error");
                    }

                    // retrieve claims of the external user
                    var claims = externalUser.Claims.ToList();

                    result = await _userManager.AddLoginAsync(user, new UserLoginInfo("AAD",claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value, claims.FirstOrDefault(x => x.Type == ClaimTypes.Upn).Value));
                    if (result.Succeeded)
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        _logger.LogInformation("User created an account using {Name} provider.", "AAD");
                        return RedirectToLocal(returnUrl);
                    }
                }
                AddErrors(result);
            }

            ViewData["ReturnUrl"] = returnUrl;
            return View(nameof(ExternalLogin), model);

The user create and validate whether in database  , but the problem is why client is not returned ? It fires 

    return RedirectToLocal(returnUrl);

But not return to the client .  the redirect url is /connect/authorize/callback?client_id=mvc2&redirect_uri=http%3A%2F%2Flocalhost%3A49459%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile%20api1%20offline_access&response_mode=form_post&nonce=xxxxxx&state=xxxxxxxx&x-client-SKU=ID_NET&x-client-ver=2.1.4.0

Please any suggestion ?

**Comment by brockallen** [comment]
> Could you help please tell me how to sue SignInManager to get the external user 

Sorry, that's beyond the support we can offer here, since it's not an IdentityServer issue.

**Comment by newlearner88** [comment]
@brockallen  I have got the external user and save into the database , see my above reply . The problem is identity server will not redirect to my client after sign-in .

**Comment by scottbrady91** [comment]
` /connect/authorize/callback` is the correct URL after user auth. You need to first go back to IdentityServer to continue the authorization request, before you can go back to the client app.

IdentityServer should then create tokens, etc. and then redirect you to http://localhost:49459/signin-oidc

**Comment by newlearner88** [comment]
@scottbrady91  , your process is actually the same as you said , i use asp.net identity in identity server , and config the external login in identity server , after external login , i use identity to save local user and sign-in ,but after that , identity server wouldn't redirect to my client MVC.

**Comment by opinionmachine** [comment]
Yeah, external stuff works with Google and LinkedIn, but Azure AD is weird. I tried at first to just use the plain old AzureAD cookie auth if External callback failed as fallback - like this:

```csharp
            // read external identity from the temporary cookie
            var result = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
            if (result?.Succeeded != true)
            {
                result = await HttpContext.AuthenticateAsync(AzureADDefaults.AuthenticationScheme);
                if (result?.Succeeded != true)
                {
                    throw new Exception("External authentication error");
                }
            }
``` 
This "works" for a while, I had a site use external AAD login for a while. However - I tried hooking code flow auth into an app, and then it failed horribly with an exception when processing the redirect back to the app. Going to use a Google external account (which uses he proper External Auth cookie) just worked. So there is something weird here. I think I have to actually solve the ExternalCookieAuthenticationScheme stuff with AAD to be able to use it.
