### ISSUE TITLE
How to change client secret from code?

### ISSUE THREAD

**Issue by odysseus1973** [IdentityServer/IdentityServer4#2549]
Hi!

I want to change clients secrets from my code. I read the documentation and did not understand how to do it. When I add new List<ClientSecret> to client ClientSecret property, old secret is not deleted. 
So to change the secret, I have to delete the client and recreate it. Is there another way to do this?

Thanks!

**Comment by brockallen** [comment]
We don't have a convenience for that, so you will have to manage those values yourself. We don't provide something for this because different projects manage that data differently.
