### ISSUE TITLE
When external OIDC provider returns an error, IDSrv generate 500 to the user 

### ISSUE THREAD

**Issue by shaikatz** [IdentityServer/IdentityServer4#2553]
### Issue / Steps to reproduce the problem
Set external odic provider and let him return error.
This makes the identity server throw an exception and result the client receive 500 instead of seeing the actual error from the oidc provider.
I except the user to see the description of the error as I see it in the log in the ErrorDescription field.

### Relevant parts of the log file
```
"Timestamp":"2018-08-16T06:05:16.5728564+00:00","Level":"Error","MessageTemplate":"Message contains error: '{Error}', error_description: '{ErrorDescription}', error_uri: '{ErrorUri}'.","Properties":{"Error":"access_denied","ErrorDescription":"XXXXX some reason.","ErrorUri":"error_uri is null","EventId":{"Id":12},"SourceContext":"Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler","RequestId":"0HLG2JTHQSKQ7:00000001","RequestPath":"/signin-pingidentity","Application":"identityserver_new"}}
```

**Comment by brockallen** [comment]
Handling the error from an external IdP is up to you in your external handler configuration.
