### ISSUE TITLE
Should SessionId Cookies be considered "Essential"

### ISSUE THREAD

**Issue by cdwaddell** [IdentityServer/IdentityServer4#2554]
Cross linked from oidc-js issue: https://github.com/IdentityModel/oidc-client-js/issues/612

It looks like Session cookies are not considered essential for GDPR compliance. It looks like webservers may not send cookies that are not flagged `IsEssential`.

https://docs.microsoft.com/en-us/aspnet/core/security/gdpr?view=aspnetcore-2.1#essential-cookies

Message cookies may need this treatment as well:

https://github.com/cdwaddell/IdentityServer4/commit/cb667c4414e196fe0bfb951808968e96e3ab8c20

**Comment by cdwaddell** [comment]
FYI, the default value of `CheckConsentNeeded` is false, so this will only affect users that turn this setting on as a way to comply with GDPR.

**Comment by brockallen** [comment]
Yes, we will be reviewing them and making the necessary changes for the next release.

**Comment by markphillips100** [comment]
Great. Thanks Brock

**Comment by brockallen** [comment]
Ok, so I just got some non-official guidance and some folks say that this is not set by default in the Microsoft stuff because they claim "it depends", meaning a site might work without authN. But for IdentityServer, it's sort of all about this, so of course they're considered essential. 

Thoughts? I lean to enabling them, but I'm just looking for some discussion.

**Comment by markphillips100** [comment]
I lean towards them being essential in this use case. They are fundamental
to the normal operation of the identity application.

**Comment by brockallen** [comment]
Ok, yea, that didn't take much convincing :)

@cdwaddell -- did you also have to set that for your primary authN cookie? I would have expected that you did.

**Comment by brockallen** [comment]
Done (as well as in the ASP.NET Identity repo).

**Comment by cdwaddell** [comment]
@brockallen , this issue didn't affect me because I don't use the `CheckConsentNeeded` flag. I looked into it for a user having the session issue that affected us in oidc.js. That being said, I use ASP.Net Identity and they made this change in December:

https://github.com/aspnet/Security/issues/1561
