### ISSUE TITLE
SSO doesn't work with asp.net mvc 5 client when deployed to IIS, Locally works great

### ISSUE THREAD

**Issue by furqan56** [IdentityServer/IdentityServer4#2555]
**Identity Server Setup:**

public void ConfigureServices(IServiceCollection services)
        {
            services.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(Configuration.GetValue<string>("ProtectionKeyLocation")))
                .SetDefaultKeyLifetime(TimeSpan.FromDays(14));

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            var clientsConfig = new List<ClientConfig>();
            Configuration.GetSection("Clients").Bind(clientsConfig);
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
            
            services.AddIdentityServer(options =>
                {
                    options.Authentication.CookieLifetime = TimeSpan.FromMinutes(30);
                    options.Authentication.CookieSlidingExpiration = true;
                })
                .AddDeveloperSigningCredential()
                .AddInMemoryApiResources(IdentityConfig.GetApiResources())
                .AddInMemoryClients(IdentityConfig.GetClients(clientsConfig))
                .AddInMemoryIdentityResources(IdentityConfig.GetIdentityResources())
                .AddProfileService<UserProfileService>();

            services.AddSingleton<UserService>(new UserService(Configuration.GetConnectionString("BridgeSuiteConnection")));
            services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();
            services.AddTransient<IProfileService, UserProfileService>();

            var cors = new DefaultCorsPolicyService(LoggerFactory.CreateLogger<DefaultCorsPolicyService>())
            {
                AllowAll = true,
            };

            services.AddSingleton<ICorsPolicyService>(cors);
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }).AddCookie();
        }

**Asp.net Client Setup:**

app.UseOpenIdConnectAuthentication(openIdConnectOptions: new OpenIdConnectAuthenticationOptions
            {
                
                AuthenticationType = OpenIdConnectAuthenticationDefaults.AuthenticationType,
                SignInAsAuthenticationType = CookieAuthenticationDefaults.AuthenticationType,
                RedirectUri = $"{options.ApplicationUrl.Trim('/')}",
                PostLogoutRedirectUri = $"{options.ApplicationUrl.Trim('/')}",
                Authority = options.IdentityUrl,
                ClientId = options.ClientId,
                ClientSecret = options.ClientSecret,
                ResponseType = "id_token token",
                Scope = string.Join(" ", options.Scopes),
                UseTokenLifetime= true,

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = async n =>
                    {
                        var userId = n.AuthenticationTicket.Identity.FindFirst(ClaimTypes.NameIdentifier);
                        BridgeSuiteCache.Instance.Add($"{userId.Value}:IdToken", n.ProtocolMessage.IdToken);
                        await Task.FromResult(0);
                    },
                    RedirectToIdentityProvider = async n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)
                        {
                            var key = $"{n.OwinContext.Authentication.User.FindFirst(ClaimTypes.NameIdentifier).Value}:IdToken";
                            var idTokenHint = BridgeSuiteCache.Instance.Get<string>(key);
                            if (idTokenHint != null)
                            {
                                BridgeSuiteCache.Instance.Remove(key);
                                n.ProtocolMessage.IdTokenHint = idTokenHint;
                            }
                        }
                        await Task.FromResult(0);
                    }
                }
            });

3rd Application is the Angular App which is working great.

scenario:
IDS4 -----> Asp.net Mvc 5 App
|_________>Angular6 App with .net core api which relay on access token

1) When user Login from Angular app it creates a user session on both Angular app and IDS4. SSO works great between Angular app and IDS4 it logins the user in both apps when user login either of the app.

**Problem**
2) Asp.net app redirect user to identity server and establish local user session but doesn't create a user session on IDS4 app. when you browse IdentityServer it doesn't show the user logged in but when user initiates the logout process it redirects to identity server where you can observe that the user logged in and signing out.

3) Signout is working perfectly it validate the id_token and automatically redirect the user back to the postlogoutURL

Goal: when user login in any app it must be authorize for other app without re login

**Comment by brockallen** [comment]
Sorry, but this sounds environmental. 

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
