### ISSUE TITLE
about both use same account login mvc client and js client sometime return 401

### ISSUE THREAD

**Issue by pigwing** [IdentityServer/IdentityServer4#2557]
i have create two client, one is mvc client (use in C#) and other is js client (use in spa use the oidc javascript client.js) i found that when i use the same account login mvc web and spa web some time mvc will return 401 statuscode and the spa will cros error 
identityserver4 use https
that i found the identityserver4 logging  my identityserver4 server use https and some logging display
Request starting HTTP/1.1 GET http://xxxx/.well-known/openid-configuration
Request starting HTTP/1.1 POST http://xxx/account/login?returnUrl.....
Policy execution failed.
that requests not use https scheme

**Comment by pigwing** [comment]
mvc client visit pc browser
js client visit mobile browser
use same account login access in the same time
some time mvc client will return 401 statuscode and the js client will return cross error

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
