### ISSUE TITLE
Use service discovery for Authority

### ISSUE THREAD

**Issue by Heurazio** [IdentityServer/IdentityServer4#2563]
Let's assume I have a bunch of APIs running in Docker (with replicas) and I like to protect the APIs with IdentityServer. I'm also using service discovery (e.g. `Consul`) to get services, check their health, and do load-balancing. What is the best way to add the "Authority" of the IdentityService (or it's replicas) to the protected APIs using service discovery?

```
services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = "http://localhost:5000";
                    options.RequireHttpsMetadata = false;

                    options.ApiName = "api1";
                });
```

When I add the basic setup for API protection the `Authority` is hardwired to this particular URL. What happens, when this service degrades or shuts down shortly after but other services are available and healthy? Or when there is a heavy load on the particular authority service and there are others with only few or zero load?

Is it possible or are there workarounds to supply IdentityServer with a service discovery in such cases? And if yes, how?

**Comment by brockallen** [comment]
The short answer is to use DNS. Having said that, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
