### ISSUE TITLE
Implicit Flow / Secured Downloads with Url Token

### ISSUE THREAD

**Issue by marcels2204** [IdentityServer/IdentityServer4#2566]
Implemented Implicit Flow with IdentityServer4. 
Now i want to secure downloads with Url Access Tokens. 
Can this be mixed? (Header or Url token validation) How to configure this?

Whould like to make POST Request for getting access token.
Then i would make an GET Request for the downloadable file (/api/docs/ey329362....)

Client is an Angular 6 SPA.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
