### ISSUE TITLE
Using POST ../connect/introspect returns statuscode 415.

### ISSUE THREAD

**Issue by PresidentCamacho** [IdentityServer/IdentityServer4#2567]
Hi,

I'm trying to use the connect/introspect endpoint to validate my access_token created by the same STS that I'm trying to call its introspect endpoint. Now when calling this endpoint I get the error "415 Unsupported Media Type". I've not added anything in the header nor body.

Sending the Basic auth in the header gives the same error.
Also when sending the access_token as <token> in token=<token> in the request body.

**Comment by brockallen** [comment]
I bet you're sending it as json and not x-www-form-url-encoded.

**Comment by PresidentCamacho** [comment]
You're correct, my body was empty but its defaulting to form-data. Changing it to x-www-form-url-encoded gave me 400 Bad Request which is a better statuscode :)

**Comment by PresidentCamacho** [comment]
One more thing I don't know if I should create a new thread for it or not, but its a direct followup to this question.

When adding Token to the body I used an access token issued by this STS to see if the endpoint works and sure enough it gave me statuscode 200. But to be sure I also edited the access token and it still gives me statuscode 200. 

Should it be like this?

**Comment by PresidentCamacho** [comment]
Never mind, the body of the return said it all. Thanks!
