### ISSUE TITLE
.Net Core 2 Cookie Consent and IsEssential?

### ISSUE THREAD

**Issue by Eneuman** [IdentityServer/IdentityServer4#2568]
Hi

It looks like the IdCookie will not be set If using .Net Core 2.1 with the new Cookie Consent option, if the user opts out of cookies. The IdCookie must be considered essential to the functionallity of IdServer, so perhaps the IsEssential = true should be set here ?

https://github.com/IdentityServer/IdentityServer4/blob/e14a1e9b2dfd4173bedb3e570ac5c888927ccb22/src/Services/Default/DefaultUserSession.cs#L374

**Comment by brockallen** [comment]
dup #2554

**Comment by Eneuman** [comment]
Correct, closing
