### ISSUE TITLE
Consider using new endpoint routing features in ASP.NET Core 3.0

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2569]

**Comment by JoeyHerrington** [comment]
Meanwhile, do you happen to have a list of settings on-hand that we can use?
```csharp
services.AddIdentityServer(options => {
    options.UserInteraction.LoginUrl = "/Identity/Account/Login";
    // etc...
})
```
right now, it's just trial and error with more of the latter!

**Comment by brockallen** [comment]
You mean like docs? 

http://docs.identityserver.io/en/release/topics/startup.html
docs.identityserver.io/en/release/reference/options.html

**Comment by JoeyHerrington** [comment]
Sorry, I found exactly what I was looking for right after posting my comment and forgot to delete my question!  Thanks!

**Comment by Blizzard1978** [comment]
I used new "AddControllersWithViews();"  and it crashed in apsnetcore 3.0 pr9 on the autorization attribute in consent controller fixed it by adding "app.UseAutorization();" after the "app.UseIdentityServer();" in the pipeline, this is because use authentication and use autorization has been pulled appart.

**Comment by the--dud** [comment]
Thanks for the quick reply. This is related to our previous issue https://github.com/IdentityServer/IdentityServer4/issues/4047 , which relates to our efforts to support encrypted responses (encrypted ID token + encrypted userinfo response).

**Comment by brockallen** [comment]
IIRC there is a way to override our existing endpoints -- it's just a matter of being configured in DI in the right order.
