### ISSUE TITLE
How To get Google token from External provider

### ISSUE THREAD

**Issue by senzacionale** [IdentityServer/IdentityServer4#257]
I am checking this temUser from external cookie

`var tempUser = await HttpContext.Authentication.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);`

but I can not see any Google token inside. Is it possible to get it? It would be fine to receive token from external provider because with this token extra call is then possible

**Comment by brockallen** [comment]
Your question is about how the google middleware works. Perhaps you should ask on a Microsoft forums for that.
