### ISSUE TITLE
Refresh Token revocation - all tokens for the associated subject are deleted instead the only one that was requested to revoke

### ISSUE THREAD

**Issue by pmehta1682** [IdentityServer/IdentityServer4#2571]
Currently there is a bug with the way the token revocation works that was reported [here ](https://github.com/IdentityServer/IdentityServer4/issues/1315) The issue is currently the token is revoked by ClientId and SubjectId instead of the Key(handler) so if the same user is logged in on multiple devices, if he logs out from one device it logs him out from all devices.
I know this has been fixed in the latest version and might be released sometime soon. But is it also possible to fix this in 1.5.3 since that is the version we are using and might not be able to upgrade soon?

It should be a one line change in the RevocationEndPoint.cs file. 
https://github.com/IdentityServer/IdentityServer4/blob/1.5.3/src/IdentityServer4/Endpoints/RevocationEndpoint.cs#L183

In line 183
Instead of  `await _refreshTokenStore.RemoveRefreshTokensAsync(token.SubjectId, token.ClientId);`
Update to `await m_refreshTokenStore.RemoveRefreshTokenAsync(handle);`

**Comment by brockallen** [comment]
We're following this model for support for old versions:

https://hueniverse.com/the-backwards-commercial-license-647290f7e38b

If your company wants this, then contact us directly for commercial support. Thanks.

**Comment by pmehta1682** [comment]
Thanks. Can you tell me when the latest version of IdentityServer will be released which has this fix?

**Comment by brockallen** [comment]
Check the milestones.
