### ISSUE TITLE
Brand error page

### ISSUE THREAD

**Issue by devdigital** [IdentityServer/IdentityServer4#2572]
Hi, if you wish to brand Identity Server based on the client id, or tenant ACR value, then we have access to the `returnUrl` within the query string, and we can derive the client id and ACR values from that.

However, is there any recommended way to brand the Identity Server error page, as it isn't forwarded the `returnUrl`, where the client id or ACR values can be accessed, only an `errorId`, which only gives access to error information, redirect URI, and response mode.

**Comment by brockallen** [comment]
> Hi, if you wish to brand Identity Server based on the client id, or tenant ACR value, then we have access to the returnUrl within the query string, and we can derive the client id and ACR values from that.

Use our interaction service, as our samples show.

**Comment by brockallen** [comment]
> However, is there any recommended way to brand the Identity Server error page, as it isn't forwarded the returnUrl, where the client id or ACR values can be accessed, only an errorId, which only gives access to error information, redirect URI, and response mode.

This is somewhat difficult, because you might be on the error page because the returnUrl (meaning the original authorize request params) is itself invalid in some way.

**Comment by devdigital** [comment]
Could the `ErrorMessage` model be updated to include the client id and acr values if they are present and valid? Happy to create a PR if the idea is sound.

**Comment by brockallen** [comment]
There might already be an open issue related to these ideas... try to find it and see where we stand on this, since you're not the first to ask.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by devdigital** [comment]
I've searched the open issues, but can't see another that covers the branding of the error page, and this is still an issue for us.

**Comment by brockallen** [comment]
As I said this might be hard if you want to brand it base don client id. Client id might not be available. You will have to either use something else to indicate branding, or make your error page more general.
