### ISSUE TITLE
Unable to read clients from configuration when a client has one or more claims.

### ISSUE THREAD

**Issue by frabe1579** [IdentityServer/IdentityServer4#2573]
If I load clients from asp.net core configuration file, and the client has one or more claims, the configuration binder throws an exception because it cannot create instances of type Claim. This is not the expected behavior, but anyway is a Configuration Binder limitation, which cannot create instances of classes which does not have a public parameterless constructor.
At the moment we cannot expand Configuration Binder because it does not support custom deserializers.
Maybe the property Claims of class Client can be replaced with a collection of a custom class type as item, with parameterless constructor. Alternatively we can use a bridge class to load from configuration, or we can add a phantom (code editor hidden) property used to load configuration from its setter to the real property.

To reporoduce the exception:

1. Add this snippet to appsettings.json:
```
  "identityServer": {
    "clients": [
      {
        "clientId": "client1",
        "clientName": "Client 1",
        "allowedScopes": [ "openid", "offline_access" ],
        "claims": [
          {
            "type": "role",
            "value": "somerole"
          }
        ]
      }
    ]
  }
```

2. Configure the indentity server to load clients in memory from configuration:
`services.AddIdentityServer().AddInMemoryClients(_configuration.GetSection("identityServer:clients")`

3. Try to use the clients from a mvc controller (obtain them from constructor, invoking DI/Configuration logic):
```
public class HomeController : Controller {
  IEnumerable<Client> _clients;
  public HomeController(IEnumerable<Client> clients) {
    _clients = clients;
  }

  public IActionResult Index() {
    return View();
  }
}
```
No logs for this bug because the project crashes at startup.

**Comment by leastprivilege** [comment]
I had a brief look - I cannot re-produce the crash. But the claims are not getting properly bound. IOW the claims list is empty.

This seems to indicate that you can use a type descriptor
https://stackoverflow.com/questions/42007114/custom-configuration-binder-for-property

But I didn't get it to work in the limited time I had.

Do you want to give that a try? Or suggest a different non-breaking solution (maybe as a PR as a basis for discussion).

**Comment by leastprivilege** [comment]
any update? @totalprogrammi

**Comment by totalprogrammi** [comment]
Sorry, for now i have no time, maybe at January.

**Comment by xmichaelx** [comment]
Try adding new converter for claims:

```csharp
class ClaimConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType)
        {
            return objectType == typeof(Claim);
        }

        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            JObject jo = JObject.Load(reader);
            string type = jo.GetValue("type", StringComparison.OrdinalIgnoreCase)?.Value<string>();
            string value = jo.GetValue("value", StringComparison.OrdinalIgnoreCase)?.Value<string>();
            string valueType = jo.GetValue("valueType", StringComparison.OrdinalIgnoreCase)?.Value<string>();
            string issuer = jo.GetValue("issuer", StringComparison.OrdinalIgnoreCase)?.Value<string>();
            string originalIssuer = jo.GetValue("originalIssuer", StringComparison.OrdinalIgnoreCase)?.Value<string>();
            return new Claim(type, value, valueType, issuer, originalIssuer);
        }

        public override bool CanWrite
        {
            get { return false; }
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }
    }
```
you can either use it directly or put it default settings:

```csharp
JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                Converters = new List<JsonConverter> { new ClaimConverter() }
            };
```

**Comment by leastprivilege** [comment]
Have you actually tried that? It needs to plug into the asp.net core config system...

**Comment by frabe1579** [comment]
I've tried your solution, but without success.
I think it cannot work because the configuration mechanism of Microsoft.Extensions.Configuration does not use json to map configuration. In other words, Newtonsoft.Json is used by Microsoft.Extensions.Configuration only to read data into key-value pairs, but not for binding data to objects.

I'm trying TypeConverter..

P.S. my nickname is changed from totalprogrammi to frabe1579

**Comment by frabe1579** [comment]
I've downloaded the source code of Microsoft.Extensions.Configuration.Binder, added a unit test to debug Claim serialization, and I came to the conclusion than the binder does not support any mechanism than public parameterless constructor for custom types. TypeConverter is used only for single values, so it cannot be used for complex types. There is a silent exception catch in the method that tries to construct the custom object (the Claim), and this is the reason that no exception is raised (the error is ignored and the item is not added to the collection).

At this point, i think that the only solution is to rewrite the configuration loading using POCO classes mapped to model classes (maybe using Automapper), but this require doubling the code for the model.

There is an open issue for Immutable types, that maybe will resolve our problem with .net core 3.0:
#https://github.com/aspnet/Extensions/issues/608, but for now seems no code change is present for that.

Personally, i've resolved using Entity Framework, so for me this is no more a direct problem.

[This is the line where the exception is catched and ignored](https://github.com/aspnet/Extensions/blob/e2f51bb31a313fd329765b6fcff1b6923f6d0fc3/src/Configuration/Config.Binder/src/ConfigurationBinder.cs#L446), and [this is the method that throws that instance](https://github.com/aspnet/Extensions/blob/e2f51bb31a313fd329765b6fcff1b6923f6d0fc3/src/Configuration/Config.Binder/src/ConfigurationBinder.cs#L350)

This is the simple test used:

    public class ClaimBindingTest
    {
        [Fact]
        public void ReadClaim()
        {
            var configuration = new ConfigurationBuilder()
                .AddJsonFile("appsettings.json")
                .Build();
            var cc = new ConfigClass();
            configuration.GetSection("config").Bind(cc);

            Assert.NotNull(cc.Claims);
            Assert.NotEmpty(cc.Claims);
            Assert.Equal(2, cc.Claims.Count);
        }

        class ConfigClass
        {
            public IList<Claim> Claims { get; set; }
        }
    }

And this is the appsettings.json file

`
{
  "config": {
    "claims": [
      {
        "type": "sub",
        "value": "abcd"
      },
      {
        "type": "iss",
        "value": "1234"
      }
    ]
  }
}
`

**Comment by leastprivilege** [comment]
That's what I thought. We cannot easily do that right now because it would be a breaking change.

Did you open an issue with Microsoft?

**Comment by frabe1579** [comment]
I've added a comment #https://github.com/aspnet/Extensions/issues/608#issuecomment-487143413, with a back-reference, on an already open issue.

There are some references to IdentityServer4 by Microsoft, like [this](https://docs.microsoft.com/it-it/dotnet/standard/microservices-architecture/secure-net-microservices-web-applications/) so maybe there are other people potentially involved in this issue, but i don't know how to contact them (and if they can help us).

**Comment by conterio** [comment]
Any update on this?

**Comment by leastprivilege** [comment]
No. We need to move away from the Claims type for config - it's very serialization unfriendly.

**Comment by leastprivilege** [comment]
Will introduce a ClientClaim class with a type/value property

**Comment by brockallen** [comment]
PR merged and thus done.
