### ISSUE TITLE
Consider making docs URLs use HTTPS

### ISSUE THREAD

**Issue by jeroenheijmans** [IdentityServer/IdentityServer4#2574]
It seems that the documentation URL at the `docs.identityserver.io` domain only supports [HTTP](http://docs.identityserver.io), but not [HTTPS](https://docs.identityserver.io). Even though I have no experience with *.github.io pages on *custom* domains, it does seem there is support for HTTPS on those too (based on [this announcement](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)).

![https error on docs](https://user-images.githubusercontent.com/1590536/44629443-b640a300-a94f-11e8-82be-5b6b98a4de54.png)

PS. I've [searched but found no issue about this yet](https://github.com/IdentityServer/IdentityServer4/issues?q=is%3Aissue+is%3Aopen+label%3Adocs).

**Comment by jeroenheijmans** [comment]
Thanks for the prompt response.

I'm a bit confused though, who is "*their*" in your reply? Don't both `identityserver4.readthedocs.io` and `docs.identityserver.io` belong to IdentityServer4, hosting the same content? Put differently, regardless of what the `readthedocs.io` link does, wouldn't it make sense to enable HTTPS for `identityserver.io` too?

The reason I ask might be relevant here too. If I [search on Google for "IdentityServer"](https://www.google.nl/search?q=identityserver&oq=identityserver) the top hits are links to the `identityserver.io` domain, which is HTTP:

![google result](https://user-images.githubusercontent.com/1590536/44630274-0bce7d00-a95b-11e8-9649-7b715efaa95f.png)

(I _now_ see that the [http://identityserver.io/](http://identityserver.io/) site links to the docs on the other (https) domain. But usually I find docs via Google, not a link on a home page.)

**Comment by brockallen** [comment]
We use `readthedocs.io` to host our docs, and they do it for free for OSS projects. That's the "they". If we wanted our docs domain hosted by them we'd have to share our cert. I'm sure we could do that, but then I'm also pretty sure it would no longer be free then.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by jeroenheijmans** [comment]
Thanks for asking!

I guess you could close this as "wontfix", but I would not call the issue resolved. Although I understand you rely on the courtesy of a free hosting package, it still seems silly to me that the docs for a security-related piece of software are hosted over http. On one hand it's not the URL you publish on the identityserver.io website, but on the other it _is_ the way folks will practically find you (via Google).

I didn't know about readthedocs by the way, but always admired the clean structure of IDS4's documentation. Out of curiosity I digged a bit through their docs, as well as [the bit on SSL for custom domains](https://docs.readthedocs.io/en/latest/alternate_domains.html#custom-domain-ssl) which might or might not be helpful in resolving this issue. (Forgive me if my lack of knowledge of your setup makes that link irrelevant.)

Anyways, I also appreciate that any OSS maintainer has only limited time and other resources, and would totally understand if you close the issue and move on. Up to you!

And thanks again for taking the time to respond to my inquiries.

**Comment by brockallen** [comment]
Thanks.
