### ISSUE TITLE
protecting an API written in asp.net 5 / web api 2

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#2576]
All the samples explain how to protect an API written in asp.net core.
 ```
services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = "http://localhost:5000";
                    options.RequireHttpsMetadata = false;

                    options.ApiName = "api1";
                });

```
Is it possible to protect APIs written in asp.net 5 / web api2 with full .net framework using Identity Server 4. How?

Thanks

**Comment by satyajit-behera** [comment]
Thanks @leastprivilege 

So, is it right practice if I can use the code below in a custom authorize attribute to validate the token:

POST /connect/introspect
Authorization: Basic xxxyyy

token=<token>
A successful response will return a status code of 200 and either an active or inactive token:
{
    "active": true,
    "sub": "123"
}
Unknown or expired tokens will be marked as inactive:
{
    "active": false,
}
An invalid request will return a 400, an unauthorized request 401.

**Comment by satyajit-behera** [comment]
Yes, in case of Reference token, that will be the only choice, I guess. Thanks.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by satyajit-behera** [comment]
Yes @brockallen . Thanks a lot.
