### ISSUE TITLE
Unable to validate jwt token with self signed certificate

### ISSUE THREAD

**Issue by Murtuzakabul** [IdentityServer/IdentityServer4#2579]
I am using .Net Core on linux server. I have two services running, one is identity server and another is my web application. I successfully get the token from identity server but my application is not able to validate the token. Here is the error I am getting.

> 
> New message was received
> fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
>       Exception occurred while processing message.
> System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:5010/.well-known/openid-configuration'.
>    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
>    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
> fail: Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HLGDLDR5IEOL", Request id "0HLGDLDR5IEOL:00000001": An unhandled exception was thrown by the application.
> System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:5010/.well-known/openid-configuration'.
>    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
>    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
>    at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
>    at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
>    at Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

To further clarify, I am using a self signed certificate. When I request the same page i.e. 'https://localhost:5010/.well-known/openid-configuration',  with wget with ignoring the certificate error, I am getting 200 - ok response. I guess it has something to do with IdentityServerClient package. It is not ignoring the certificate error. Any ideas on it ?

**Comment by kieronlanning** [comment]
I've this same problem.

Id4Svr is running in a Linux container in Azure App Services. 

Everything is setup to be HTTPS. However, the client always fails with that same error.

However, if I got to the .well-known url myself, all the endpoints are showing non-HTTPS.

If I run Id4Svr in Azure App Services for Windows (which is IIS) with the same configuration, it's all fine.

**Comment by kieronlanning** [comment]
@leastprivilege That's perfect! Exactly what I was missing.

Thanks!

**Comment by li0nsar3c00l** [comment]
I got a similar setup (linux docker containers with self signed dev certificates) and the same problem with the following error messages:

> An unhandled exception occurred while processing the request.
SocketException: Cannot assign requested address
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)
HttpRequestException: Cannot assign requested address
System.Net.Http.ConnectHelper.ConnectAsync(string host, int port, CancellationToken cancellationToken)
IOException: IDX20804: Unable to retrieve document from: 'https://localhost:44100/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(string address, CancellationToken cancel)
InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:44100/.well-known/openid-configuration'.
Microsoft.IdentityModel.Protocols.ConfigurationManager<T>.GetConfigurationAsync(CancellationToken cancel)

When i navigate to https://localhost:44100/.well-known/openid-configuration in my browser, i can see the config without any problems at all. Using sdk 2.1.402 and identityserver 2.3.0 preview.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
