### ISSUE TITLE
IdentityServer4 + AWS Cloud directory ?

### ISSUE THREAD

**Issue by saurabhlogward** [IdentityServer/IdentityServer4#2587]
This more of information I am requesting on how to integrate the IdentityServer4 to work with AWS Cloud Directory.
Use Case:
AWS Cloud directory helps to manage the hierarchical data where as IdentityServer can be used for authenticating the users from the cloud directory.
Question:
Is this possible with IdentityServer current API's ?

**Comment by leastprivilege** [comment]
Yes - you are writing that code yourself. So you can use whatever data store you like.

**Comment by saurabhlogward** [comment]
Any references/example for such customization of having AWS Cloud directory as underlying data source for authenticating the user ?

**Comment by brockallen** [comment]
Not for AWS, sorry.
