### ISSUE TITLE
Reference token validation issue with localhost

### ISSUE THREAD

**Issue by devdigital** [IdentityServer/IdentityServer4#2591]
I'm using Identity Server 4 to generate reference tokens, and forwarding that (via a delegation custom extension grant) to an OWIN/.NET 4.x based service which uses the Identity Server 3 access token validation middleware to validate the token.

However, running this locally (IS4 at http://localhost:5000), I'm getting the following output from the token validation middleware when it attempts to use the introspection endpoint to validate the token:

```
Error returned from introspection endpoint: An error occurred while sending the request. 
invalid bearer token received
```

and

```
System.Net.Http.HttpRequestException: 'An error occurred while sending the request.' 
WebException: The server committed a protocol violation. Section=ResponseStatusLine
```

I can call `POST http://localhost:5000/connect/introspect` directly in Postman, and get back the expected response (including `active: true`).

Is this a case of needing to run HTTPS for local development? Can this requirement be disabled?

One solution would be to use a JWT (self contained) token for the backend service. Then I could use the `Local` validation mode, and presumably avoid this issue.

Are there any examples of a custom extension grant which switches a reference token for a JWT with Identity Server 4?

**Comment by devdigital** [comment]
As an update, adding `ServicePointManager.Expect100Continue = false;` to the OWIN/.NET 4.x backend service fixes the issue. It only occurs locally, so I haven't delved into debugging what IS4 returns from the `/connect/introspect` endpoint.

In terms of the other question though, I've found an [example](https://github.com/IdentityServer/IdentityServer3/issues/1725#issuecomment-190290329) of writing a custom extension grant for IS3 to exchange a reference token for a JWT. I see this [open issue](https://github.com/IdentityServer/IdentityServer4/issues/2310) for IS4. Is there an equivalent process for IS4 that I can use in the short term?

**Comment by devdigital** [comment]
Thanks, we're already using a custom extension grant for simple delegation, exactly from the docs - how can this be extended to change the reference token type to a JWT?

**Comment by leastprivilege** [comment]
You can change the token type on the request object that gets passed into the validator

**Comment by devdigital** [comment]
Thanks, `context.Request.AccessTokenType = AccessTokenType.Jwt;` is working as expected. This issue can be closed.
