### ISSUE TITLE
Custom scope missing from external identity provider.

### ISSUE THREAD

**Issue by PresidentCamacho** [IdentityServer/IdentityServer4#2592]
Hi, 

I've setup an IdentityServer4 with only an external identity provider as the way to login. Now this external identity provider have a custom scope `x_scope`.

**My external identity provider**

```
            services.AddAuthentication()
                .AddOpenIdConnect("externalidentityprovider", "externalidentityprovider", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.SignOutScheme = IdentityServerConstants.SignoutScheme;

                    options.Authority = "_externalidentityprovider-adress_";

                    options.ClientId = "client";
                    options.ClientSecret = "secret";

                    options.ResponseType = "code";
                    options.RequireHttpsMetadata = true;
                    options.SaveTokens = true;

                });
```

**How my resources are set up:**

```
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResource()
                {
                    Name = "x_scope",
                    DisplayName = "x_scope",
                    Description = "A Custom Scope",
                    UserClaims = new[]
                    {
                        "x_scope"
                    }
                }
            };
```

**The Client that is using my identityserver:**

```
                new Client
                {
                    ClientId = "mvc",
                    ClientName = "MVC Client",
                    AllowedGrantTypes = GrantTypes.Hybrid,

                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },

                    RedirectUris = {"http://localhost:5002/signin-oidc"},
                    PostLogoutRedirectUris = {"http://localhost:5002/signout-callback-oidc"},

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "x_scope"
                    },
                    AllowOfflineAccess = true,
                    EnableLocalLogin = false
                }
```

**The client setting up authentication:**

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "externalidentityprovider";
            })
                .AddCookie("Cookies")
                .AddOpenIdConnect("externalidentityprovider", options =>
            {
                options.SignInScheme = "Cookies";

                options.Authority = "_adresstomyidentityserver_";

                options.ClientId = "mvc";
                options.ClientSecret = "secret";
                options.ResponseType = "id_token code";

                options.SaveTokens = true;
                options.GetClaimsFromUserInfoEndpoint = true;

                options.Scope.Add("x_scope");
                options.Scope.Add("offline_access");
            });

I get the x_scope in my consent screen when I've logged in but it doesn't seem to be appear in my claims. Querying the userendpoint with the access_token I got doesn't contain it either.

What am I missing?

**Comment by Olek-HZQ** [comment]
It only can map standard OIDC claims, but unfortunately not mapped by Microsoft.So you should map it yourself.
options.ClaimActions.MapUniqueJsonKey("nnin_altsub", "nnin_altsub");
see this:[https://leastprivilege.com/2017/11/15/missing-claims-in-the-asp-net-core-2-openid-connect-handler/](url)

**Comment by PresidentCamacho** [comment]
@Olek-HZQ Thanks! I will try that.

Your link is broken.

**Comment by Olek-HZQ** [comment]
@PresidentCamacho try again.

**Comment by PresidentCamacho** [comment]
@Olek-HZQ you said that I should add it to the client, but I don't think its the clients fault. When using the access_token I got for IdentityServer to query the userinfo endpoint I still do not get that scope.

**Comment by Olek-HZQ** [comment]
@PresidentCamacho 
I get it  by using the access_token.
my user info endpoint: http://localhost:17366/connect/userinfo
response info: 

`{
    "name": "Olek",
    "email": "875755898@qq.com",
    "role": "Admin",
    "x_scope": "x_scope_name",
    "sub": "1"
}`
Code:
Test User:
`new TestUser
                {
                    SubjectId = "1",
                    Username = "olek",
                    Password = "password",

                    Claims = new List<Claim>
                    {
                        new Claim(JwtClaimTypes.Name, "Olek"),
                        new Claim(JwtClaimTypes.Email, "875755898@qq.com"),
                        new Claim(JwtClaimTypes.Role, "Admin"),
                        new Claim("x_scope", "x_scope_name")
                    }
                },`

client side:
add this code `options.ClaimActions.MapUniqueJsonKey("x_scope", "x_scope");`

The other configs is the same as your code.

See if this can help you.

**Comment by PresidentCamacho** [comment]
@Olek-HZQ Thanks, I'll check with my identity provider and see if something is missing from them.
