### ISSUE TITLE
redirect_uri always use http not https

### ISSUE THREAD

**Issue by heavenwing** [IdentityServer/IdentityServer4#2598]
### Issue / Steps to reproduce the problem
host identityserver4 server and asp.net core client behind IIS ARR with SSL-offloading
add https address into redirecturi for client
when login with client , idsvr says unauthorized_client 
and after add http address into redirecturi, idsvr postback to http not https

I have already add below code into Configure of Startup for idsvr4 and client
`
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });
`

**Comment by leastprivilege** [comment]
Yeah it's tricky.

https://leastprivilege.com/2017/10/09/new-in-identityserver4-v2-simplified-configuration-behind-load-balancers-or-reverse-proxies/

**Comment by heavenwing** [comment]
@leastprivilege 
The PublicOrigin works for fixing the links for well-known configuration, but the redirect url coming back to Identityserver stays http:// instead of https://

**Comment by leastprivilege** [comment]
Which redirect URI ?

**Comment by cloudybrain** [comment]
I'm having the same problem.. I enter in my url in the following format in production:

   https://www.abc.com

but it redirects to the identityserver4 with the following message: 

   unauthorized client

With the following error message:

fail: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Invalid redirect_uri: http://www.abc.com/connect{
        "ClientId": "client_stuff",
        "ClientName": "client name",
        "AllowedRedirectUris": [
          "https://www.abc.com/connect"
        ],

If I was to change my ClientRedirectUrl to show as http instead of https, it works. I'm trying to figure this out using fiddler, but it shows all responses as the original request coming as https. So I'm really not sure why identityserver thinks the incoming request from the client is http.

**Comment by Vithozor** [comment]
That didn't work for me, but I was able to make it work by httpd configuration, Following the instructions [here](https://docs.microsoft.com/en-Us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.1#ssl-configuration), you will end up with some .conf files for your applications. It's mandatory that you add this to the 443 port VirtualHost:

```
    ProxyPass / https://127.0.0.1:5001/
    ProxyPassReverse / https://127.0.0.1:5001/
    ServerName [YOUR DOMAIN NAME]:443

    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
```
Also, your application must be listening through the port after the localhost IP (5001 in the example). You can do this on Program.cs:

  ```
  public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
        .UseUrls("https://localhost:5001", "http://localhost:5010")
            .UseStartup<Startup>();
```

**Comment by morrisond91** [comment]
@heavenwing  did you ever get to the bottom of your issue? i am experiencing same issues with IIS.

**Comment by heavenwing** [comment]
I searched a article with workaround: https://www.linuxidc.com/Linux/2017-06/145177.htm?utm_medium=referral

**Comment by heavenwing** [comment]
I explain my problem clearly now . Please re-open this issue. @brockallen

I create a microservice application which include a STS service and mangement console (MC) web.
STS service port is 10103 (in my applicaiton), and MC web port is 10102.

My microservice app hosted in service fabric cluster, and use IIS ARR as load balancer for this SF cluster.
Assigned a domain (sso-login.mydomain.com) to load balancer, route to SF cluster's port 10103.
Assigned a domain (sso-mc.mydomain.com) to load balancer , route to SF cluster's port 10102.
Binding a SSL certificate into load balancer, but enabled SSL offloading for sso-login.mydomain.com and sso-mc.mydomain.com.

Create a IdentityServer4 client configuration for MC web ( a MVC web application).
First, I set "https://sso-mc.mydomain.com" as RedirectUri. 
When I access MC web with url "https://sso-mc.mydomain.com", once do login action, I will get a error "unauthorized_client".
Second, I add "http://sso-mc.mydomain.com" as RedirectUri, "https://sso-mc.mydomain.com" still be kept.
When I login at "https://sso-mc.mydomain.com" again, I can see login form from STS service.
But after I login successfully , STS service redirect to "http://sso-mc.mydomain.com" instead of "https://sso-mc.mydomain.com".

https://github.com/appsonsf/FabricSSO is my application's source code.

**Comment by heavenwing** [comment]
According to this [description](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#forward-the-scheme-for-linux-and-non-iis-reverse-proxies), I missed these lines:
`
 options.KnownNetworks.Clear();
 options.KnownProxies.Clear();
` 

If you don't add it into options, X-Forwarded-Proto would not be forwarded
