### ISSUE TITLE
custom stores

### ISSUE THREAD

**Issue by mbeckenbach** [IdentityServer/IdentityServer4#26]
Hi, 

I just want to give you some feedback

I've implementing almost all stores as a custom implementation using ef 7 now.

It was pretty easy thanks to the simplicity of the in memory store interfaces and models, that I could use as a boilerplate for finding out relationships.

One part is a bit confusing: Why does the user have a subject property? In a classic db I would expect a user id. 

Is this only because of the open id standard? Or are there cases when this could be something else than a user id?

I've seen it is used to map the consent to a user for example.

**Comment by leastprivilege** [comment]
Yes - the openid connect protocol demands a subject id - you can map that to whatever is unique, immutable user identifier in your domain.

**Comment by mbeckenbach** [comment]
Ok this is what I do at the moment. My User entity has a UserID which maps to the subject in identity server models.
