### ISSUE TITLE
Documentation for Secrets still mention old ClientAssertionSecretParser

### ISSUE THREAD

**Issue by klioqc** [IdentityServer/IdentityServer4#2601]
This topic 
https://github.com/IdentityServer/IdentityServer4/blob/release/docs/topics/secrets.rst
contains line 
builder.AddSecretParser<ClientAssertionSecretParser>()
I think it should be 
AddSecretParser<JwtBearerClientAssertionSecretParser>()

**Comment by leastprivilege** [comment]
I don't follow - feel free to PR to get a better diff.

**Comment by klioqc** [comment]
sorry, text in angle brackets is lost here. I suggested to update old ClientAssertionSecretParser with new JwtBearerClientAssertionSecretParser for the builder.AddSecretParser. i'll create PR...

**Comment by klioqc** [comment]
yes, doc is updated - https://github.com/IdentityServer/IdentityServer4/pull/2611
