### ISSUE TITLE
Question: validate access token in Node API.

### ISSUE THREAD

**Issue by vejandla** [IdentityServer/IdentityServer4#2602]
First of all thanks for the awesome framework and appreciate all the hard work you guys put in into this.

We have implemented the identity provider server in asp.net core 
and we have the api's in asp.net, node (hapi-js)
we have SPA as front end and we used implicit flow and followed recommended guidelines. 
Followed the examples to include identity server middleware in asp.net. 

Are there any packages or middle-ware plugins you  suggest to validate to access token sent by SPA requests to node API's?

**Comment by leastprivilege** [comment]
any JWT validation library would do - also check

https://openid.net/certification/

**Comment by MuhammadBilalYar** [comment]
@vejandla, are able to resolve this app? can you share any sample?
