### ISSUE TITLE
couldn't find the .pfx sample certificate in the sample project repository

### ISSUE THREAD

**Issue by shibutamang** [IdentityServer/IdentityServer4#2603]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
not enough info
