### ISSUE TITLE
/admin endpoint available when i removed all AdminUI related stuff out of my startup?

### ISSUE THREAD

**Issue by rikka94** [IdentityServer/IdentityServer4#2608]
As title, i already removed all the AdminUI related middleware.
Yet the "/admin" still being hijacked and redirected non-functional admin ui page.

I only had
IdentityServer4 (2.2.0), 
IdentityServer4.AspNetIdentity (2.1.0), 
IdentityServer4.EntityFramework (2.1.1) in my nuget packages.

Am i missing something or is it a way to disable/remove the endpoint?

Thanks.

**Comment by brockallen** [comment]
Something is amiss. @scottbrady91?

**Comment by scottbrady91** [comment]
It sounds like your browser has cached the AdminUI app.

If you've removed calls to `UseAdminUI` and reran your application, then there's no way that AdminUI can route. We're not doing anything special.

If you dig in a little further, I bet the API side isn't available (meaning users won't list, etc.).

**Comment by rikka94** [comment]
Turn out my chrome somehow cached the page.
Open the same page in other incognito mode and finally my route working.

Sorry for the fuss and thanks for the hint.
