### ISSUE TITLE
IdentityServer4.Samples ImplicitFlowAuthentication won't build

### ISSUE THREAD

**Issue by GuruRAM** [IdentityServer/IdentityServer4#2614]
Quickstart3_ImplicitFlowAuthentication has compile errors.

### Issue / Steps to reproduce the problem
Execute IdentityServer4.Samples\Quickstarts\3_ImplicitFlowAuthentication\src\QuickstartIdentityServer\updateUI.ps1

Build IdentityServer\IdentityServer4.Samples\Quickstarts\3_ImplicitFlowAuthentication\Quickstart3_ImplicitFlowAuthentication.sln

The solution has build errors since IdentityServer4 2.1.0 version is referenced in [QuickstartIdentityServer.csproj](https://github.com/IdentityServer/IdentityServer4.Samples/blob/004937b68c8c70b2cf65b58f4ebec59fb056be61/Quickstarts/3_ImplicitFlowAuthentication/src/QuickstartIdentityServer/QuickstartIdentityServer.csproj#L8) and respective events are not presented there.

Possible fix would be to update the reference of IdentityServer4  to 2.2.0

### Relevant parts of the log file

```
Error	CS0246	The type or namespace name 'GrantsRevokedEvent' could not be found (are you missing a using directive or an assembly reference?)	QuickstartIdentityServer	*\IdentityServer4.Samples\Quickstarts\3_ImplicitFlowAuthentication\src\QuickstartIdentityServer\Quickstart\Grants\GrantsController.cs	57	N/A
Error	CS0246	The type or namespace name 'ConsentDeniedEvent' could not be found (are you missing a using directive or an assembly reference?)	QuickstartIdentityServer	*\IdentityServer4.Samples\Quickstarts\3_ImplicitFlowAuthentication\src\QuickstartIdentityServer\Quickstart\Consent\ConsentController.cs	115	N/A
Error	CS0246	The type or namespace name 'ConsentGrantedEvent' could not be found (are you missing a using directive or an assembly reference?)	QuickstartIdentityServer	*\IdentityServer4.Samples\Quickstarts\3_ImplicitFlowAuthentication\src\QuickstartIdentityServer\Quickstart\Consent\ConsentController.cs	136	N/A
```

**Comment by brockallen** [comment]
The .ps1 is meant for us to update the sames when the code's all in sync. It's not really meant for you to grab the latest of the QS UI.
