### ISSUE TITLE
Does clientsecret  has a length limit?

### ISSUE THREAD

**Issue by jonechenug** [IdentityServer/IdentityServer4#2616]
If I have a clientsecret   just like "y5nWxf5uQ7kVdEVG7fvOkHzNHZuux1HYUKbohHjHVxpcpMq1OOnANehfzYCQmSDgviNCwXYDN6Bpfsq05WsW9zcKa7MrRMoq5pUwR4CaE16po0NiGEdVoMYhJS8HSy71".
As you see, It has **128** length. When I use the tokenClient to test and verify,it give me a **invalid_client** error.
Also it has  **not call** `IClientConfigurationValidator`!

**Comment by brockallen** [comment]
There is config you can change to allow longer input values:

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Configuration/DependencyInjection/Options/InputLengthRestrictions.cs#L22
