### ISSUE TITLE
Create a method to wait until the user is logged out from all clients

### ISSUE THREAD

**Issue by kloudja** [IdentityServer/IdentityServer4#2619]
I'm using Front-channel signout in my implementation and I redirect the user to the current client after 3 seconds to allow the iframe to render all miniIframes to logout from all clients.
However in slow networks, sign out does not work since some iframes (inside the big iFrame) do not load completely before i redirect them...
The first approach I though to solve the problem was to send a request to the identityServer to check if the user is alrady logged out from all clients, and only then redirect the user. 
However it is not possible to retrieve a list of all clients that the user is signed in...

The second approach i tried was to do onload of the mini-iframes but no success since it throws a cross origin error while trying to edit the mini iframes.

I would like to have a method that allow me to wait until the user is successfully logged out from all clients and only then redirect the user

**Comment by brockallen** [comment]
Did you see the `AutomaticRedirectAfterSignOut` setting? 

https://github.com/IdentityServer/IdentityServer4/blob/dev/host/Quickstart/Account/AccountOptions.cs#L16

**Comment by kloudja** [comment]
Thanks for the reply. =) 
Where can i read about that setting? Did not found that info on idsrv4 doc...
Would like to know what it does, where and how to use it.
I just want to be sure that my user is only redirected when signout is successfully performed in all clients... (front-channel signout).
I receive that boolean in my front end and then what?
`if (response.automaticRedirectAfterSignOut) {
               //well is just a bollean, means nothing...
}`

Sorry my ignorance =/

**Comment by brockallen** [comment]
> Where can i read about that setting

In the code -- look at the account controller.

**Comment by kloudja** [comment]
Thanks for the reply.
I was already reading the code. I downloaded the IdentityServer4-demo.
The thing is, it is just a boolean. Probably I was not clear, or I am not understanding something, sorry.
I'm actually, in my code doing the same as you guys.

Demo-code:
`section scripts
{
    @if (Model.AutomaticRedirectAfterSignOut)
    {
        <script src="~/js/signout-redirect.js"></script>
    }
}`

My code:
SERVER-SIDE
            
            var logout = await _interaction.GetLogoutContextAsync(logoutId);

            var vm = new LoggedOutViewModel
            {
                AutomaticRedirectAfterSignOut = true,
                PostLogoutRedirectUri = logout?.PostLogoutRedirectUri,
                ClientName = string.IsNullOrEmpty(logout?.ClientName) ? logout?.ClientId : logout?.ClientName,
                SignOutIframeUrl = logout?.SignOutIFrameUrl,
                LogoutId = logoutId,
                Authenticated = (User != null ? User.Identity.IsAuthenticated : false)
            };

FRONT-END

               this.SigninService.signOut(this.logoutId).subscribe(
                      response => {
                             (...)
                            if (response.automaticRedirectAfterSignOut) { 
                                 this.goToLogoutRedirectUri();
                            }
                      });

My logout flow is correct:
1 - Front-End asks back-end to logout
2 - Back-end clears his cookies, and sends the signoutIframe and postLogoutRedirectUri
3 - Renders iframe and goes to PostLogoutRedirectUri

The problem is on slow-networks... The iframes inside the main iframe do not have time to complete its operations contacting the respective clients...
I even set a counter of 3 seconds to give time to the iframe to load the mini iframes but on slow networks it still does not work

**Comment by kloudja** [comment]
Any clue how can i implement this?

**Comment by kloudja** [comment]
Still nothing?

**Comment by brockallen** [comment]
Sign-out is a hard problem. The specs cover what they cover (which is what we implement), and for single sign-out it's best effort.
