### ISSUE TITLE
Consider adding description to grants table

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2621]
So end user can name the device/client to which they are granting consent. 

At least for now we can add the column in the DB.

**Comment by brockallen** [comment]
moving this to 3.0 -- @leastprivilege  we can discuss, as it entails the whole stack from UI to DB.

**Comment by friendly-tech** [comment]
Any update on this, we are adding a UI so users can revoke refresh_tokens and we would like to show the device name to which it belongs...

Before i embark on tryin to do this, is there anything built in i can use or any suggestions on the best approach.. >?

**Comment by brockallen** [comment]
This is slated for 4.0, so nothing's been done yet.

**Comment by brockallen** [comment]
PR submitted

**Comment by friendly-tech** [comment]
Great, just had a look.

Will there be a way to assign device description when not requiring consent..?

**Comment by brockallen** [comment]
> Will there be a way to assign device description when not requiring consent..?

Well, you can augment the UI anyway you want. But if you don't have some UI, then I'm not sure where/when you'd let the user do that. Thoughts?

**Comment by friendly-tech** [comment]
maybe something like a ‘IDeviceDescriptionProvider’ With a default implementation that provides it from userAgent from the http request.

**Comment by friendly-tech** [comment]
Or pass in via querystring to authorize endpoint - I’m not really sure but things like Facebook/google show device description without you typing it in.

**Comment by brockallen** [comment]
PR merged
