### ISSUE TITLE
Issue using custom Identity with Identity Server

### ISSUE THREAD

**Issue by axufuris** [IdentityServer/IdentityServer4#2622]
Hi there, I created a front end to my Identity Server.  In order to login to the front end I setup our SSO Authentication for the user to login.  I made sure to put the services.AddIdentity before my services.AddIdentityServer, but I am still running into an error when doing it. I know I have everything configured correctly for SSO, because it is working just fine in my other project.  It looks like the AddIdentityServer is still overriding everything.

```
services.AddIdentity<ApplicationUser, ApplicationRole>().Services.ConfigureApplicationCookie(options =>
            {
                options.LoginPath = "/Saml/SingleSignOn";
                options.SlidingExpiration = true;
                options.LogoutPath = "/Saml/SingleSignOn";
                options.Cookie.Expiration = new TimeSpan(1, 0, 0);
                options.Cookie.IsEssential = true;
            });

            services.AddTransient<IUserStore<ApplicationUser>, CustomUserStore>();
            services.AddTransient<IRoleStore<ApplicationRole>, CustomRoleStore>();
            services.AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>, MyUserClaimsPrincipalFactory>();

            services.AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;
            })
            // this adds the config data from DB (clients, resources)
            .AddConfigurationStore(options =>
            {
                options.ConfigureDbContext = b =>
                    b.UseSqlServer(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly));
            })
            // this adds the operational data from DB (codes, tokens, consents)
            .AddOperationalStore(options =>
            {
                options.ConfigureDbContext = b =>
                    b.UseSqlServer(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly));

                // this enables automatic token cleanup. this is optional.
                options.EnableTokenCleanup = true;
                // frequency in seconds to cleanup stale grants. 15 is useful during debugging
                options.TokenCleanupInterval = int.Parse(Configuration.GetSection("TokenCleanup").Value);
            })
            .AddDeveloperSigningCredential();
```

The error that is now coming up is:

InvalidOperationException: sub claim is missing
IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal) in IdentityServerAuthenticationService.cs
IdentityServer4.Hosting.IdentityServerAuthenticationService.AugmentPrincipal(ClaimsPrincipal principal) in IdentityServerAuthenticationService.cs
IdentityServer4.Hosting.IdentityServerAuthenticationService.SignInAsync(HttpContext context, string scheme, ClaimsPrincipal principal, AuthenticationProperties properties) in IdentityServerAuthenticationService.cs
Microsoft.AspNetCore.Identity.SignInManager<TUser>.SignInAsync(TUser user, AuthenticationProperties authenticationProperties, string authenticationMethod)
GUIdentityServer4.Controllers.SamlController.AssertionConsumerService() in SamlController.cs
+
                await signInManager.SignInAsync(user, false);
```

**Comment by brockallen** [comment]
This usually happens when you don't have the default authentication scheme set to the same scheme you use on your login page.

**Comment by axufuris** [comment]
My login page is a SSO page outside my application.  And i'm sorry, but I can tell you that probably isn't the problem.  I have this exact same code for single sign on in other applications and it works. It is only when I add the Identity Server to it that it breaks.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
