### ISSUE TITLE
Type error on dotnet core 2.2 preview 2: missing IIdentityServerBuilder

### ISSUE THREAD

**Issue by kooshan** [IdentityServer/IdentityServer4#2624]
Hi,
using dotnet core 2.2 preview 2, I get this error

`error CS0012: The type 'IIdentityServerBuilder' is defined in an assembly that is not referenced. You must add a reference to assembly 'IdentityServer4, Version=2.0.4.0, Culture=neutral, PublicKeyToken=null'
`

on a pretty much conventional sample:

`
services.AddIdentityServer(options =>
            {
                // configurations
            })
`

I'm using IdentityServer package version 2.3.0-preview1-update2. This code used to compile and work well under dotnet core 2.2 preview 1.

**Comment by shauntir** [comment]
I have the same issue using dotnet core 2 with version 2.3.0-preview1-update2 of IdentityServer.

**Comment by brockallen** [comment]
Any update on this? Can you repo this with our samples?

**Comment by kooshan** [comment]
No. I couldn't. H though preview 3 would somehow resolve this issue, but it persists.  I can't guess what may have caused this. Since it is literally the same setup which used to compile and run.
