### ISSUE TITLE
Responsible Disclosure Policy?

### ISSUE THREAD

**Issue by omerlh** [IdentityServer/IdentityServer4#2625]
I just encountered this [question](https://stackoverflow.com/questions/52372862/identityserver4-and-owasp) on SO - which report a potential security issue. I've commented that this is not the way to report such issues - but then noticed the lack of responsible disclosure policy on GitHub (probably me missing it). Maybe consider adding `Security.md` page? See [Ghost's](https://github.com/TryGhost/Ghost/blob/master/SECURITY.md) file for example.

**Comment by brockallen** [comment]
If you think there is a security concern, please send mail to contact@identityserver.io

**Comment by omerlh** [comment]
I'm not sure - but this is not why I've opened this issue. this issue is about making it easier to find the responsible disclosure policy of this project. This is why I suggested using `security.md`...

**Comment by leastprivilege** [comment]
This is a good idea. We will add such a file. Thanks!

**Comment by leastprivilege** [comment]
done
