### ISSUE TITLE
Token cleanup job is running twice for multiple instances 

### ISSUE THREAD

**Issue by deepakgupta03** [IdentityServer/IdentityServer4#2628]
Hi,
 
We have deployed our identity server on azure ARM and we have two instances of identity server. The cleanup activity of tokens is being performed by both the instances but we need to restrict it to one instance only.

**Comment by brockallen** [comment]
You can disable the cleanup flag on the one you want to disable.

**Comment by deepakgupta03** [comment]
Hi brockallen,
      Thanks for the quick response. We have multiple instances of same web application(web-farm) which shares same configurations. Please let me know how we will disable it and which setting in the configurations you are talking about. We have created Instance of TokenCleanup and start it in the application code.

Thanks in Advance !!!

**Comment by brockallen** [comment]
`EnableTokenCleanup` on http://docs.identityserver.io/en/release/reference/ef.html#operationalstoreoptions

**Comment by deepakgupta03** [comment]
Hi brockllen,
Multiple instances of same web application(web-farm) shares the same code so how we can achieve this by 
EnableTokenCleanup property.
Also, we have used identity server3, is there any way in IdentityServer3.

**Comment by brockallen** [comment]
IIRC, there's a similar flag for IdentityServer3.

**Comment by deepakgupta03** [comment]
Thanks Brockallen,
I'm not sure how I would update this property(EnableTokenCleanup) in one instance if both the instances are running on same web application(web-farm) and share same code. Please suggest.

**Comment by brockallen** [comment]
I don't know your hosting or deployment infrastructure. You'd have to figure that out yourself.
