### ISSUE TITLE
Use SecureString

### ISSUE THREAD

**Issue by krema** [IdentityServer/IdentityServer4#2629]
Wouldn't it be better to use SecureString instead of regular strings? 
I.e. in ResourceOwnerPasswordValidationContext the member Password

Is there a reason for not using SecureString?

Cheers

**Comment by leastprivilege** [comment]
What's your threat model?

**Comment by leastprivilege** [comment]
Or IOW - what do you want to protect against?

**Comment by krema** [comment]
From [Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netcore-2.1)

> SecureString is a string type that provides a measure of security. It tries to avoid storing potentially sensitive strings in process memory as plain text. (For limitations, however, see the How secure is SecureString? section.) The value of an instance of SecureString is automatically protected using a mechanism supported by the underlying platform when the instance is initialized or when the value is modified. Your application can render the instance immutable and prevent further modification by invoking the MakeReadOnly method.

**Comment by brockallen** [comment]
@krema that didn't answer the question. What are you trying to protect against by using SecureString?

**Comment by krema** [comment]
Elevation of Privilege by reading the credentials out of the memory. A lower/none privilege user or application can access functions or content reserved for higher privilege users or applications.

**Comment by leastprivilege** [comment]
SecureString has proven to be inefficient. Before we can turn something into a SecureString, it's first an "in-secure string". And you can most likely find that in memory as well.

Also - if someone has access to your memory - I think you have bigger issues.

Did you also read: https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netcore-2.1#HowSecure
