### ISSUE TITLE
Integrating Discourse with IdentityServer4 SSO

### ISSUE THREAD

**Issue by wleev** [IdentityServer/IdentityServer4#2631]
How would one go about integrating Discourse with IdentityServer4 as SSO provider? Their method is not completely OAuth2 compatible ( as specified in: https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045 ).

Are there any examples of manually doing a login and token generation?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
