### ISSUE TITLE
Persisted Grants - Refresh tokens not updated in DB

### ISSUE THREAD

**Issue by markarmitage** [IdentityServer/IdentityServer4#2632]
Hi,

I'm using Persisted Grants to store the tokens in the DB and they have an expiration. We're refreshing the tokens and when stepping through the code I can see the expiration date being updated but this is not reflected in the DB record. Should it be? The reason this causes problems is that the record is removed from the DB as it has passed it's expiration so the next time I refresh the token I get an 'invalid_grant' error as the token no longer exists in the DB.
I suspect even if the record did exist I would still get an error as the expiration date has passed. Can you advise on this please?

Thanks in advance,
Mark

**Comment by brockallen** [comment]
Do you have a concrete repo for this? Perhaps in one of our samples?

**Comment by markarmitage** [comment]
No I don't have a repo for this. The scenario is Identity Server 4 .Net Core project, a .Net 4.5 API project and a MVC 4.5 web project. I'm trying to refresh the token so that I can still authenticate the API project from the web project. Do you have a sample that covers this scenario and that updates the expiry of the token in the DB? Or is there a different approach that I should take?

**Comment by brockallen** [comment]
So is there a bug that you can repo for us to investigate?
