### ISSUE TITLE
CURL requests in documentation

### ISSUE THREAD

**Issue by DjangoFR** [IdentityServer/IdentityServer4#2633]
The examples in the documentation are certainly great for C# people, but if you come from another world, they are quite complicated to understand/reproduce. It would be great to have CURL requests in the documentation - then anyone could execute the requests on the command line.

Something like this:
https://stackoverflow.com/a/52429221/2095846

**Comment by leastprivilege** [comment]
Good idea! Feel free to add them.

**Comment by LindaLawton** [comment]
I might also have some gists floating around for this

**Comment by manishkungwani** [comment]
Hi,
I would like to contribute with the sample curl requests.
Which pages do you think I should start with?
I was thinking of starting with https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html
OR the endpoint pages, starting from - https://identityserver4.readthedocs.io/en/latest/endpoints/authorize.html

Please let me know.

**Comment by mrPsycho** [comment]
would be really cool to have such examples, cause they something like standard.
