### ISSUE TITLE
Allowing GET at introspection.

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#2634]
https://tools.ietf.org/html/rfc7662#section-4 

>   To prevent the values of access tokens from leaking into server-side
   logs via query parameters, an authorization server offering token
   introspection MAY disallow the use of HTTP GET on the introspection
   endpoint and instead require the HTTP POST method to be used at the
   introspection endpoint.

We have a vendor who can only currently send GET requests. Id like to be able to easily toggle allowing a GET.

Is there currently an easy workaround for us?

**Comment by leastprivilege** [comment]
Not without changing the source code.

**Comment by VictorioBerra** [comment]
I could implement my own endpoint essentially copy and pasting 90% of the current endpoint right? Im considering doing a PR with a flag allowing GETs but the other issue is our vendor wants to send the tokens in the QueryString too. So it's looking like the changes needed will be more than just allowing GETs.

**Comment by brockallen** [comment]
The spec discourages GET because the tokens are passed in the query string, which might end up in a log file. This is not ideal and this is why we never did this. 

We're open for a PR after our 2.3 release.

**Comment by VictorioBerra** [comment]
I assumed as much. We're waiting to see if this change would fix the issue with our vendor. If it does I'll PR the changes which I'm pretty much done with.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
