### ISSUE TITLE
Master and child token

### ISSUE THREAD

**Issue by m-demydiuk** [IdentityServer/IdentityServer4#2635]
**Is your feature request related to a problem? Please describe.**
We have partners in our system which have users registered in our db. The partner can receive partner token using grant type `client_credentials` and `client_id`/`client_secret` pair. After the partner got partner token, he should be able to provide a token for a user using grant_type `password` and `email/password` 
 pair. Only authenticated/authorized partners can get user toke.

**Describe the solution you'd like**
After the partner got partner token, he makes another request to the identity server. Partner specifies:
- Partner token
- User email
- User Password

Is it possible at all, or we should create some custom logic? If custom logic, can you send some links for solutions?

Thanks in advance.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
