### ISSUE TITLE
OIDC - HTTP 404 after redirect to client app 

### ISSUE THREAD

**Issue by ngruson** [IdentityServer/IdentityServer4#2640]
I made a sample IdentityServer host + MVC client application that use OIDC based on https://identityserver4.readthedocs.io/en/release/quickstarts/3_interactive_login.html.
That works ok.

When I copy the relevant startup code to my actual MVC app, things don't work as well anymore. First, a controller is hit that is decorated with the Authorize attribute and is redirected to the IdentityServer login page. After the user logs in and is redirected to my app again, a HTTP 404 error occurs.
The post to signin-oidc of my MVC client seems to be going well. After that the 404 happens.
How can I debug this further?

Relevant code of the IdentityServer host:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddTestUsers(TestUsers.Users)
                .AddInMemoryClients(Config.GetClients())
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApiResources());

            services.AddMvc();
        }

```
Relevant code of the MVC client:
```
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
                .AddCookie("Cookies")
                .AddOpenIdConnect("oidc", options =>
                {
                    options.SignInScheme = "Cookies";

                    options.Authority = "http://localhost/Webshop.IdentityServer";
                    options.RequireHttpsMetadata = false;

                    options.ClientId = "webshop";
                    options.SaveTokens = true;
                });
        }

```

### Relevant parts of the log file

```
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2018-09-22T19:20:19.2813334Z","tags":{"ai.internal.nodeName":"CLT-NGRUSON","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.operation.parentId":"|ef582de1-4b89990c129dc875.","ai.location.ip":"127.0.0.1","ai.cloud.roleInstance":"CLT-NGRUSON","ai.operation.name":"POST /Webshop.Web/signin-oidc","ai.operation.id":"ef582de1-4b89990c129dc875","ai.application.ver":"1.0.0.0"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"Request finished in 56.0594ms 302","severityLevel":"Information","properties":{"ElapsedMilliseconds":"56,0594","CategoryName":"Microsoft.AspNetCore.Hosting.Internal.WebHost","AspNetCoreEnvironment":"Development","DeveloperMode":"true","StatusCode":"302"}}}}
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2018-09-22T19:20:19.2212392Z","tags":{"ai.internal.nodeName":"CLT-NGRUSON","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.location.ip":"127.0.0.1","ai.cloud.roleInstance":"CLT-NGRUSON","ai.operation.name":"POST /Webshop.Web/signin-oidc","ai.operation.id":"ef582de1-4b89990c129dc875","ai.application.ver":"1.0.0.0"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|ef582de1-4b89990c129dc875.","name":"**POST /Webshop.Web/signin-oidc","duration":"00:00:00.0636929","success":true,"responseCode":"302","url":"http://localhost/Webshop.Web/signin-oidc"**,"properties":{"AspNetCoreEnvironment":"Development","httpMethod":"POST","DeveloperMode":"true"}}}}
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost/Webshop.Web/Basket/AddToBasket  
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2018-09-22T19:20:19.3147304Z","tags":{"ai.internal.nodeName":"CLT-NGRUSON","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.operation.parentId":"|ef582de2-4b89990c129dc875.","ai.location.ip":"127.0.0.1","ai.cloud.roleInstance":"CLT-NGRUSON","ai.operation.name":"GET /Webshop.Web/Basket/AddToBasket","ai.operation.id":"ef582de2-4b89990c129dc875","ai.application.ver":"1.0.0.0"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"Request starting HTTP/1.1 GET http://localhost/Webshop.Web/Basket/AddToBasket","severityLevel":"Information","properties":{"CategoryName":"Microsoft.AspNetCore.Hosting.Internal.WebHost","AspNetCoreEnvironment":"Development","Protocol":"HTTP/1.1","DeveloperMode":"true","Scheme":"http","Method":"GET","Host":"localhost","Path":"/Webshop.Web/Basket/AddToBasket"}}}}
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 32.8847ms 404 
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Message","time":"2018-09-22T19:20:19.3231198Z","tags":{"ai.internal.nodeName":"CLT-NGRUSON","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.operation.parentId":"|ef582de2-4b89990c129dc875.","ai.location.ip":"127.0.0.1","ai.cloud.roleInstance":"CLT-NGRUSON","ai.operation.name":"GET /Webshop.Web/Basket/AddToBasket","ai.operation.id":"ef582de2-4b89990c129dc875","ai.application.ver":"1.0.0.0"},"data":{"baseType":"MessageData","baseData":{"ver":2,"message":"**Request finished in 32.8847ms 404**","severityLevel":"Information","properties":{"ElapsedMilliseconds":"32,8847","CategoryName":"Microsoft.AspNetCore.Hosting.Internal.WebHost","AspNetCoreEnvironment":"Development","DeveloperMode":"true","StatusCode":"404"}}}}
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2018-09-22T19:20:19.2865317Z","tags":{"ai.internal.nodeName":"CLT-NGRUSON","ai.internal.sdkVersion":"aspnet5c:2.1.1","ai.location.ip":"127.0.0.1","ai.cloud.roleInstance":"CLT-NGRUSON","ai.operation.name":"GET /Webshop.Web/Basket/AddToBasket","ai.operation.id":"ef582de2-4b89990c129dc875","ai.application.ver":"1.0.0.0"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"|ef582de2-4b89990c129dc875.","name":"GET /Webshop.Web/Basket/AddToBasket","duration":"00:00:00.0399890","success":false,"responseCode":"404","url":"http://localhost/Webshop.Web/Basket/AddToBasket","properties":{"AspNetCoreEnvironment":"Development","httpMethod":"GET","DeveloperMode":"true"}}}}
The program '[16388] dotnet.exe: Program Trace' has exited with code 0 (0x0).

```
IIS logs:

2018-09-22 21:11:04 ::1 POST /Webshop.Web/signin-oidc - 80 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/64.0.3282.140+Safari/537.36+Edge/17.17134 http://localhost:81/Webshop.IdentityServer/connect/authorize?client_id=webshop&redirect_uri=http%3A%2F%2Flocalhost%2FWebshop.Web%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=636732474645581393.MjFmY2I3ODAtOGQ4OC00NTAxLWE5MzgtNWVjMzg2NDZjZmRiYWRmMTE3ZmYtOWE5Ni00ZDBiLWFmM2EtN2VkNDRjNTQxZTI4&state=CfDJ8AhcSnwTTTBBgtPSuVfCJdvRQ_yasFBwSUi4WWA55Inhdj7g3DbQANa_EC6f3Xp8P2IT8bA5arHpFB1gCe6wdIFfCynr1nX_IFwkjx0UGb3gKXjGHlRR6ZjHCnkWA3hw_B07ZyjuWVjN7rQmbcbIjMjvBBxg4pxPTJEpW23UpwSnkf5gS2BEtotqx41rL1UBmtEkGtqk7goj23m8B0yhPOM2rPAUrPpa-LI5mYjah9KqA6axeEEckq6Jo4J0gkML_1dajVB1heOT6a0ekcK0_g1PYP2P4nNsP5QV7evzqJ4U0N1EOHTf2GS10N1lE2O_6hl3d4T4IknroYhdEDJAWKQNS4egY__bZ1Kvz_OgMEEl&x-client-SKU=ID_NET&x-client-ver=2.1.4.0 302 0 0 24
2018-09-22 21:11:04 ::1 GET /Webshop.Web/Basket/AddToBasket - 80 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/64.0.3282.140+Safari/537.36+Edge/17.17134 http://localhost:81/Webshop.IdentityServer/connect/authorize?client_id=webshop&redirect_uri=http%3A%2F%2Flocalhost%2FWebshop.Web%2Fsignin-oidc&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=636732474645581393.MjFmY2I3ODAtOGQ4OC00NTAxLWE5MzgtNWVjMzg2NDZjZmRiYWRmMTE3ZmYtOWE5Ni00ZDBiLWFmM2EtN2VkNDRjNTQxZTI4&state=CfDJ8AhcSnwTTTBBgtPSuVfCJdvRQ_yasFBwSUi4WWA55Inhdj7g3DbQANa_EC6f3Xp8P2IT8bA5arHpFB1gCe6wdIFfCynr1nX_IFwkjx0UGb3gKXjGHlRR6ZjHCnkWA3hw_B07ZyjuWVjN7rQmbcbIjMjvBBxg4pxPTJEpW23UpwSnkf5gS2BEtotqx41rL1UBmtEkGtqk7goj23m8B0yhPOM2rPAUrPpa-LI5mYjah9KqA6axeEEckq6Jo4J0gkML_1dajVB1heOT6a0ekcK0_g1PYP2P4nNsP5QV7evzqJ4U0N1EOHTf2GS10N1lE2O_6hl3d4T4IknroYhdEDJAWKQNS4egY__bZ1Kvz_OgMEEl&x-client-SKU=ID_NET&x-client-ver=2.1.4.0 404 0 0 29

**Comment by brockallen** [comment]
Any update?

**Comment by ngruson** [comment]
I didn't have a HttpGet controller method matching the URL that IdSrv redirects to after logging the user in. I just added that to my code, that prevents the 404 from happening, but the user experience gets a little bit weird. Because I have an Authorize attribute on a HttpPost action, the user gets redirected to IdSrv to log in, but that's when I lose the state of the original Post request. Any way that you know of to extend the functionality of the signin-oidc method of ASP.NET Core in my client app? Maybe somewhere in the OIDC middleware? I need to add some code after the user has logged in, but in this scenario the SignIn method of my AccountController doesn't get hit.

**Comment by brockallen** [comment]
Yea, the MSFT OIDC plumbing has some events you'd need to handle to take control. Since we've established that this is a client issue and not an IdentityServer issue, I'll close.
