### ISSUE TITLE
ClaimValueTypes.DateTime not working

### ISSUE THREAD

**Issue by RomainWilbert** [IdentityServer/IdentityServer4#2642]
I create a new custom claim with ClaimValueTypes.DateTime type in my IProfileService implementation:

```
        public async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var user = await userStore.FindByUserId(context.Subject.GetSubjectId());

            var claims = new List<Claim>
            {
                new Claim(JwtClaimTypes.GivenName, user.Firstname),
                new Claim(JwtClaimTypes.FamilyName, user.Lastname),
                new Claim(JwtClaimTypes.Email, user.Email),
                new Claim(JwtClaimTypes.Name, user.Firstname + " " + user.Lastname)
            };
            
            if (user.ExpirationDate.HasValue)
            {
                claims.Add(new Claim(ExpirationDateClaim, user.ExpirationDate.Value.ToString("o"), ClaimValueTypes.DateTime));
            }

            context.IssuedClaims.AddRange(claims.Where(x => context.RequestedClaimTypes.Contains(x.Type)).ToList());
        }
```

On the client side, when I look at User.Claims, valueType is "http://www.w3.org/2001/XMLSchema#string" for my custom claim.

What is the best practice to manipulate DateTime claims and the best way to deserialize it on the client side ?

Thanks

**Comment by leastprivilege** [comment]
ClaimValueTypes are a .NET only concept - they are not round-tripped.

**Comment by RomainWilbert** [comment]
Thanks for answering. If this is only concept, can anyone explain why on the client side the iso date claim is deserialized as a culture specific formatted date ?

**Comment by leastprivilege** [comment]
This would be more a question for MS - since the provide the JWT handler (if you are using that).

**Comment by RomainWilbert** [comment]
I am quite new to .Net. I use .Net core 2.1.2 so I don't have a clue if this is the JWT handler which is used. I thought the mapping would be done by the AccessTokenValidation package.

Can you recommend a best practice for passing through datetime typed claims ? For now I use a hack which serialize the date in json on server side, so it escapes the iso string value and avoids format corruption on the client side

**Comment by leastprivilege** [comment]
Yes - this is the MS JWT handler in use.

For now this sounds like a feasible approach. But feel free to open an issue here:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
