### ISSUE TITLE
IdentityServer is not returning "Email" as part of id_token.

### ISSUE THREAD

**Issue by NavpreetHallen** [IdentityServer/IdentityServer4#2645]
I have added Email as part of GetIdentityResources() in Config.cs as well as AllowedScopes  but id_token doesn't contain user email at all.
decoded id_token : it only contains id not email 
{
  "nbf": 1537847177,
  "exp": 1537847477,
  "iss": "https://********com",
  "aud": "**",
  "nonce": "*******-574a-477c-af85-510b5e5f7fd",
  "iat": **7847177,
  "c_hash": "****WgKjTnCqOwf4TQ",
  "sid": "***be84668c81e19a21ae56824c6",
  "sub": "a0e5850c-8c9a-43e4-9b39-da6293291f77",
  "auth_time": 1537846394,
  "idp": "local",
  "amr": [
    "pwd"
  ]
}

How can I make it return Email in id_token

**Comment by opoutere** [comment]
For some reason Identity Server doesn't return user details in id token when both id token and access token are requested in the same implicit flow request. If you just request id token, then user detail claims will be issued. If you request both tokens, then afterwards you need to call userinfo endpoint to get user details.

**Comment by brockallen** [comment]
> For some reason Identity Server doesn't return user details in id token when both id token and access token are requested in the same implicit flow request. If you just request id token, then user detail claims will be issued. If you request both tokens, then afterwards you need to call userinfo endpoint to get user details.

That's per-spec.

**Comment by brockallen** [comment]
> I have added Email as part of GetIdentityResources() in Config.cs as well as AllowedScopes but id_token doesn't contain user email at all.

You need to configure the user claims you want in the corresponding tokens via the IdentityResource or ApiResources. That's covered in our docs.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
