### ISSUE TITLE
Two different clients , two user logins, second user is directly getting logged in instead prompting log in 

### ISSUE THREAD

**Issue by Manojmadhav** [IdentityServer/IdentityServer4#2647]
Hi ,

We have configured two clients, the first user logged in with the first client in the first tab of the browser, while we are trying to log in with the second user for the second client in the second tab of the same browser is not prompting log in page .

identityserver4 ASP.Net Core + OIDC client +Implicit

Can you please help me

**Comment by brockallen** [comment]
That's how SSO works.
