### ISSUE TITLE
Asp.Net Core 2.1 with IdentityServer4 throw error "InvalidOperationException: idp claim is missing"

### ISSUE THREAD

**Issue by Edward-Zhou** [IdentityServer/IdentityServer4#2649]
I follow [Using ASP.NET Core Identity](http://docs.identityserver.io/en/release/quickstarts/6_aspnet_identity.html) with `Asp.Net Core 2.1` and `IdentityServer4.AspNetIdentity`.         

Here is reproduceable project:      
[IdentityServerWithAspNetCoreIdentity](https://github.com/Edward-Zhou/AspNetCore/tree/master/IdentityServerWithAspNetCoreIdentity)     

[IdentityServerMVCClient](https://github.com/Edward-Zhou/AspNetCore/tree/master/IdentityServerMVCClient)

After launching both project, I could login the IdentityServerWithAspNetCoreIdentity after registering. But for `IdentityServerMVCClient`, I will got below error when I click `About`.     

> InvalidOperationException: idp claim is missing

**Comment by brockallen** [comment]
This usually happens when you don't have the proper default authentication scheme set in your app to be the IdentityServer cookie.

**Comment by Edward-Zhou** [comment]
How should I set `proper default authentication scheme`?

**Comment by brockallen** [comment]
You can do it in the AddAuthentication(options=>{...})

**Comment by Edward-Zhou** [comment]
I have configured `services.AddAuthentication(options =>
                    {
                        options.DefaultScheme = "Cookies";
                        options.DefaultChallengeScheme = "oidc";
                    })` at client side, what should I configure at IdentityServer side?

**Comment by JohnGalt1717** [comment]
@Edward-Zhou did you ever get this working? I'm still getting this routinely if the cookie is still valid.
