### ISSUE TITLE
Requesting introspection endpoint without api secret

### ISSUE THREAD

**Issue by victorjonsson** [IdentityServer/IdentityServer4#2651]
Hi there!

We have an API resource without secret. How is it that we can use `services.AddIdentityServerAuthentication` in our third party application but we're not able to request the retrospection endpoint, it responds with http status 401. My assumption is that `AddIdentityServerAuthentication` will request the retrospection endpoint to verify the jwt token, or am I wrong?

**Comment by victorjonsson** [comment]
But my question is then how the signature of the jwt token gets verified in the third party application?

**Comment by brockallen** [comment]
If it's a JWT, introspection is not needed. The signature is validated by the API downloading the signing keys via discovery.

**Comment by victorjonsson** [comment]
Ah, okey! That was the missing piece of the puzzle.

/ thanks

**Comment by victorjonsson** [comment]
Does the signing keys get cached? Or will every request to the third party application end up in a request to the discovery endpoint as well?

**Comment by brockallen** [comment]
Yes, cached.
