### ISSUE TITLE
Windows authentication without hosting platform dependency

### ISSUE THREAD

**Issue by igor-moskvitin** [IdentityServer/IdentityServer4#2653]
[Docs](https://identityserver4.readthedocs.io/en/release/topics/windows.html) says that windows auth can work only with windows/iis, but will be nice to remove this limitation.
May be possible to use tools like [this](https://github.com/SteveSyfuhs/Kerberos.NET)?

Or may be already exist some sort of integrations?

**Comment by brockallen** [comment]
All authentication is a host concern with IdentityServer. Do if you want to use that, then go for it.

**Comment by igor-moskvitin** [comment]
Ok. Thanks i will try.
