### ISSUE TITLE
Client Description  isn't available at IdentityServer4.Models.Client

### ISSUE THREAD

**Issue by brunohbrito** [IdentityServer/IdentityServer4#2654]
### Issue / Steps to reproduce the problem
I'm trying to get/set Client Description at `IdentityServer4.Models.Client` to Store it at Db through ToEntity(). 
The property isn't available, but it exists at `IdentityServer4.EntityFramework.Entities.Client`

![image](https://user-images.githubusercontent.com/7241156/46186544-9c2f1300-c2b5-11e8-9da2-171ecbbe38cc.png)

I made an workaround, just for you guys know about it!

**Comment by brockallen** [comment]
It is in 2.2: https://github.com/IdentityServer/IdentityServer4.Storage/blob/dev/src/Models/Client.cs#L60

**Comment by brunohbrito** [comment]
Great! 

But I think that we need to wait the next version of IdentityServer4.EntityFramework. Because it depends of version IdentityServer4 2.1.1 ?

Or there is a way, that I cannot see, to update version 2.2 with this version of EF?

**Comment by brockallen** [comment]
Correct -- it won't be there until 2.2. If you want to update it now, then you will have to use the EF entities directly.

**Comment by brunohbrito** [comment]
Thx!
