### ISSUE TITLE
Identity server is not retrying for failed db calls

### ISSUE THREAD

**Issue by deepakgupta03** [IdentityServer/IdentityServer4#2655]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Relevant parts of the log file

```
<log goes here>
```

**Comment by deepakgupta03** [comment]
Hi,
I am using IdentityServer3.EntityFramework. Identity server is not retrying for failed database calls. It should retry again if  database call fails.

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer3#note-this-repository-is-no-longer-in-active-development-or-maintenance-other-than-reported-security-vulnerabilities

**Comment by deepakgupta03** [comment]
Hi  brockallen

Thanks for quick response.
Is retry possible for failed identity database  calls in IdentityServer4.EntityFramework?

**Comment by brockallen** [comment]
It's possible, but we don't currently do that. What's the use-case or scenario you're trying to address?

**Comment by deepakgupta03** [comment]
For cases when database is down for a particular instance of time, some transient issues occur due to connection establishment failure. By implementing retry logic, we want to avoid such transient issues.

**Comment by brockallen** [comment]
Well, we don't have anything like that built-in, but if you need that you can implement any of the store interfaces and add that logic.
