### ISSUE TITLE
Will IdentityServer4 2.3 support .NET Core 2.2?

### ISSUE THREAD

**Issue by MontyGvMC** [IdentityServer/IdentityServer4#2656]
**Is your feature request related to a problem? Please describe.**
Using X509Certificate2 on non windows platforms have a (.NET Core) bug when decrypting data.

Short explanation:
A bug deep in .NET Core prevents decrypting on non windows platforms (e.g. Docker) due to the missing certificate store. This happens on decrypting data .NET Core always looks up the certificate store and fails if it is not present.

See [that data protection issue](https://github.com/aspnet/DataProtection/issues/286) and the referenced issues for a more detailed explanation.

In an Identity Server 4 scenario X509Certificate2 can be used for the SigningCredentials (and optionaly for data protection e.g. on protected resources/API side).

I found out that with IdentityServer 2.3 preview 1 you moved all repositories to .NET Core 2.1. The bug described above will be/is fixed in .NET Core 2.2 (as far as I understood the linked issues).

Maybe it is only me but I haven't got SigningCredentials working on docker nor the data protection for my IdentityServer4 nor the protected resources. Anyone else having issues?

If at least 2.3 (more preferably 2.1 or 2.2) would support .NET Core 2.2 IdentityServer4 could be run in docker????

**Describe the solution you'd like**
If IdentityServer 2.3 would support .NET Core 2.2 SigningCredentials as X509Certifcate2 could be used on docker too.

**Describe alternatives you've considered**
X509certifcate not working on non windows platforms (or maybe it is just me messing up)
So far for testing I use the developer signing credentials.
I haven't figured out a  (working) 3rd option on docker so far.

**Comment by brockallen** [comment]
We have many customers running on linux containers using certs for their signing credentials. I don't know of anything that has changed in .NET Core or ASP.NET Core that's already released with what's planned for 2.2 that should cause those working solutions to break. I did not yet read the link you provided above. Are you saying something is changing in 2.2 whereby those existing solution will no longer work?

**Comment by MontyGvMC** [comment]
Are you saying something is changing in 2.2 whereby those existing solution will no longer work?

No. If there are already people got it working than its just me. And if it works now it will still work in 2.2.

When I experienced problems my research brought me to the link above and I thought that would be the solution. But with the given information I will habe to recheck.

Well, from my side it could be closed...

Thanks
