### ISSUE TITLE
Using both asp.net identity and entity framework together gives No DbContext named 'PersistedGrantDbContext' was found

### ISSUE THREAD

**Issue by satyajit-behera** [IdentityServer/IdentityServer4#2657]
When I use both asp.net Identity combined with Entity Framework configuration operational data storage, it does not create the migrations.

Configurations:
```
services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddAspNetIdentity<ApplicationUser>()
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 30;
                });

```
Running the following command:

> dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb

gives error:

> No DbContext named 'PersistedGrantDbContext' was found.

But if I remove the .AddAspNetIdentity<ApplicationUser>()  from the above configuration, it works fine. 

Am I missing something?

This happens when its with asp.net core 2.1

Thanks

**Comment by brockallen** [comment]
I just tested this and it's working fine. Check the latest commit to the samples no the dev branch: 

https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev

I added a batch file to create your database and it uses all 3 DbCOntexts.

**Comment by satyajit-behera** [comment]
Thanks. Will check.

**Comment by satyajit-behera** [comment]
The sample works with netcoreapp2.0
I get the error when I work with netcoreapp2.1
Thanks

**Comment by brockallen** [comment]
We will update our samples when we ship 2.3 (which will be soon).

**Comment by sprengo** [comment]
Any update on that one? I get the same error that was stated in the OP.
