### ISSUE TITLE
Exception using AddAspNetIdentity()

### ISSUE THREAD

**Issue by dknaack** [IdentityServer/IdentityServer4#266]
I get the following Exception

```
An exception of type 'System.TypeLoadException' occurred in 
MyProject.Api.dll but was not handled in user code

Additional information: Method 'ValidateAsync' in type
'IdentityServer4.AspNetIdentity.ResourceOwnerPasswordValidator`1' from assembly
'IdentityServer4.AspNetIdentity, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
does not have an implementation.
```

Stacktrace:

```
at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensions.AddAspNetIdentity[TUser](IIdentityServerBuilder builder, String authenticationScheme)
   at MyProject.Api.Startup.ConfigureServices(IServiceCollection services) in Z:\Users\dknaack\Development\MyProject\MyProject.Api\src\MyProject.Api\Startup.cs:line 104
```

on

```
var builder = services.AddIdentityServer()
      .SetSigningCredential(cert)
      .AddInMemoryClients(Clients.Get())
      .AddInMemoryScopes(Scopes.Get())
      .AddAspNetIdentity<ApplicationUser>();
```

Any ideas?

Thanks in advance

**Comment by brockallen** [comment]
We just tried to reproduce your situation on the ASP.NET Identity Quickstart and could not reproduce it. Are you using RC1 (I'm assuming yes)? Does the ASP.NET Identity Quickstart work for you?

**Comment by brockallen** [comment]
Also, if you're not using `AddIdentityServerQuickstart` then you'll also need to register `AddInMemoryStores` (in addition to your signing cert).

**Comment by dknaack** [comment]
I thought i was on rc1 but for some reason dotnet restore used beta5. After removing the packages from project.json and re-adding it + using AddIdentityServerQuickstart and AddInMemoryStores()  the problem is gone.

Thank you very much!
