### ISSUE TITLE
User token vs application/client token

### ISSUE THREAD

**Issue by danutzplusplus** [IdentityServer/IdentityServer4#2662]
Hello,

This isn't an issue, just a question regarding some vocabulary in the OAuth2 knowledge space. But I believe this is the most knowledgeable place where my question could be answered. At least I hope someone can clarify this for me.

As we all know the OAuth2 framework specifies the issuance of JWT tokens either using the client credentials flow, which places client/application claims on the token, and the other flows which do place user claims on the token. This distinction is enforced by the spec of JWT: https://tools.ietf.org/html/rfc7523#section-3

> The JWT MUST contain a "sub" (subject) claim identifying the
        principal that is the subject of the JWT.  Two cases need to be
        differentiated:

        A.  For the authorization grant, the subject typically
            identifies an authorized accessor for which the access token
            is being requested (i.e., the resource owner or an
            authorized delegate), but in some cases, may be a
            pseudonymous identifier or other value denoting an anonymous
            user.

        B.  For client authentication, the subject MUST be the
            "client_id" of the OAuth client.

But there doesn't seem to be the same enforcement of distinction between types of identity claims on the token with regards to when the resource-server will receive that token. In certain situations you can, at the resource-server level, distinguish whether the token was issued for a user or a non-user client (for ex. identityserver fills the subject with the guid of the user vs the client_id, as the spec says), but there doesn't seem to be a clear distinction between the two.

Would it be wrong or introduce confusion, or any other negative effect that you see, to make a distinction between the two token types? Calling one a so-called user token and the other an application/client token? It makes sense to me to name them differently, since in some circumstances you will likely want to distinguish between the two. The most likely scenario that comes to mind is an audit scenario, where you want to know if the request token was made on behalf of a particular user or just a generic client.

I would really appreciate some feedback from you knowledgeable ladies and gentlemen. Thank you and have a good one.

**Comment by leastprivilege** [comment]
Well - the spec you are citing above is confusing. It is about using JWTs as client secrets.

In IS we made the decision for the JWTs we issue that `sub` always refers to a human. We use `client_id` to identify a client. This way we minimize chances they are parsed incorrectly.

**Comment by danutzplusplus** [comment]
> 
> 
> Well - the spec you are citing above is confusing. It is about using JWTs as client secrets.
> 
> In IS we made the decision for the JWTs we issue that `sub` always refers to a human. We use `client_id` to identify a client. This way we minimize chances they are parsed incorrectly (or mixed up).

So, you made the explicit choice to not overload the subject field with either human identifier or a client identifier? And instead use one, the subject, for human identifier and the client_id as a client identifier.

So, I guess you would agree that you see no issue in distinguishing between the two types of tokens? One a "user token" and the other an "application/client token"?

**Comment by leastprivilege** [comment]
our access tokens always have a `client_id` claim to identify the client. In addition - IF a user is present - there is also a `sub` claim.

**Comment by danutzplusplus** [comment]
Thank you for the information. This helped a lot.
