### ISSUE TITLE
Add example for using X509Certificate2 to the docs on the website

### ISSUE THREAD

**Issue by MontyGvMC** [IdentityServer/IdentityServer4#2663]
**Is your feature request related to a problem? Please describe.**
Using X509Certificate2 for signing credentials seems pretty straight forward but actually needs more configuration than expected.

The docs on the [website](http://docs.identityserver.io) just show developer signing credentials.
If one googles **WindowsCryptographicException: Keyset does not exist** the first result is [this IdSrv4 issue](https://github.com/IdentityServer/IdentityServer4/issues/1575) where it is just mentioned that it was ask many times before.

[This issue](https://github.com/IdentityServer/IdentityServer3/issues/269) states it works out of the box since the certifciate is included (though it was IdSrv3). Adding a custom pfx and using it doesn't work.

Unfortunatly that lacks an explanation. Mind adding a short code snippet to the website showing how to set that up?  Which flags to use?

**Describe the solution you'd like**
A small code snippet and instructions for configuration would be great if people asking many times for that.

**Comment by 4356Surf** [comment]
Not sure if this will help, but I am using this between local and dev machines. 
For local development look for personal -> certificates, for development server ask your server admin if you don't have creds as I had to do. Also, make sure the ISS AppPool\AppPoolName has read access to the cert.

Here's a startup snip below with some refs:

            // Cert thumbprint
            string certTP = string.Empty; 
            if (Environment.IsDevelopment())
            {
                certTP = "4734d9d4ce2c07d78e23d9fffdc6be78c6e534a5";
            }
            else
            {
            certTP = "33b414efbc6c08664fe3526627e0f7ef1422f55a";
            }

            //REF: https://cuteprogramming.wordpress.com/2018/03/04/kosd-series-certificate-for-signing-jwt-on-identityserver/
            // Ref: https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-retrieve-the-thumbprint-of-a-certificate
            X509Certificate2 cert = null;
            using (X509Store certStore = new X509Store(StoreName.My, StoreLocation.LocalMachine))
            {
                certStore.Open(OpenFlags.ReadOnly);
                var certCollection = certStore.Certificates.Find(
                    X509FindType.FindByThumbprint,
                    certTP,
                    false);

                // Get the first cert with the thumbprint
                if (certCollection.Count > 0)
                {
                    cert = certCollection[0];
                }
            }
            services.AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;
                options.UserInteraction.LoginUrl = "/Account/Login";
                options.UserInteraction.LogoutUrl = "/Account/Logout";
            })
            .AddSigningCredential(cert)

**Comment by jrob5756** [comment]
I found this article helpful by Scott Brady.

https://www.scottbrady91.com/OAuth/Removing-Shared-Secrets-for-OAuth-Client-Authentication

**Comment by MontyGvMC** [comment]
A missing piece of information (at least for a beginner like me): certificates can be broken/unusable.

So check if .NET Core can handle your certificate private keys when running into all flavors of cryptographic exception. No exception will tell you that "simply" your certificate can't be used.

For further information: [.NET Core X509Certificate2 usage (under Windows/IIS, Docker, Linux)](https://stackoverflow.com/questions/53334142/net-core-x509certificate2-usage-under-windows-iis-docker-linuxl)
