### ISSUE TITLE
Updating docs and quick start samples to ASP.NET Core 2.1 / 2.2 

### ISSUE THREAD

**Issue by markpritchett** [IdentityServer/IdentityServer4#2664]
All the docs and quick start samples are for ASP.NET Core 2.0.

Given the number of docs and quick start samples, it's a fairly big task to update them all and so I was wondering what work was in progress / planned in this area and what would be the best way of planning the remaining work?

I suppose another consideration is that ASP.NET Core 2.2 is scheduled for release by the end of the year.  So would it make sense to skip over version 2.1 and just update the docs and quick start samples to version 2.2?

Whilst some of the work will be simply changing the version from 2.0 to 2.1 / 2.2, other parts will require more work.  A couple of things that I can think of are:

- Using ASP.NET Core Identity / Entity Framework Core 2.1 / 2.2
- Taking control of URLs in the quick start samples

**Comment by brockallen** [comment]
Our plans for the docs are:
1) release IdentityServer 2.3
2) rework our quickstarts to use our templates (and not the VS File->New Project templates)
3) see what happens in ASP.NET Core 2.2 and their use of IdentityServer

The main reason the docs have become somewhat stale is that Microsoft up-ended the ASP.NET Identity templates and somewhat broke our quickstart for it. That's a lot of work to keep chasing their template changes.

**Comment by leastprivilege** [comment]
Work has started on the new quickstarts. They will be done in a way that it doesn't matter too much anymore which version of ASP.NET is used (at least that's my dream).

We don't plans to do RPs.

**Comment by Ponant** [comment]
@leastprivilege , this issue has the tag "help wanted". Feel free to tell me if you need an input for testing or whatever.

**Comment by leastprivilege** [comment]
You can go to our docs and choose the UpdatedQs branch. QuickStart 1-4 are updated. A review would be nice. Thanks

**Comment by Ponant** [comment]
I am on it and have some proposals, mainly on the pedagogy side. I also found out that the discovery endpoint display
```
"scopes_supported": 
[
"openid",
"api1",
"offline_access"
],
```
which is more detailed than the image snapshot you show. Is that expected or should be mentioned.
I am on .Net core 2.2 preview3

**Comment by leastprivilege** [comment]
image is fixed

**Comment by leastprivilege** [comment]
any other feedback

**Comment by leastprivilege** [comment]
tracking in #2536

**Comment by leastprivilege** [comment]
Everything is here
http://docs.identityserver.io/en/updatedqs/quickstarts/0_overview.html

this will replace latest - once @brockallen is done
