### ISSUE TITLE
Two local clients (different ports) with local identity server keep asking login page

### ISSUE THREAD

**Issue by brijesh-1111** [IdentityServer/IdentityServer4#2665]
I have an issue with single sign-on with Identity server 4.

While I was following Identity server 4 (with aspnet core 2) videos and articles, I have developed a sample applications + identity server local. I have:

- Identity Server: https://locahost:5001
- Application 1: https://localhost:44373
- Application 2: https://localhost:44317

Both applications are the same Asp.net core 2 (MVC) except the client id. They have the same Authority https://localhost:5001

Now, When I tried to authenticate Application 1 against Identity server it's giving me the login page, authenticating the user (against aspnet identity) and giving me the home page back. I can see the claims are also coming as expected.

Same thing for Application 2 as well as Identity server.

But now the problem is: If I complete the authentication for application 1 and try to refresh the page on Application 2 or Identity server nothing is authenticating. If I tries to access the secure page, it gives me the login screen from Identity server 4 as like there is no authentication has done. Same I tried to check by authenticating directly on Identity Server 4 and refreshing both the application (1 and 2) but no luck.

Seems like I am missing something. Here is my configuration:

Application side I have:
`options.Authority = authenticationSettings.IdentityServer.Authority;
        options.RequireHttpsMetadata = bool.Parse(authenticationSettings.IdentityServer.RequireHttpsMetadata);
        options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;

        options.ClientId = authenticationSettings.IdentityServer.ClientId;
        options.GetClaimsFromUserInfoEndpoint = true;
        options.ResponseType = "code id_token";
        options.SaveTokens = true;
        options.ClientSecret = "secret";

        options.Scope.Add("openid");
        options.Scope.Add("profile");
        options.Scope.Add("email");`

Identity server side I have following client (same for application 1 and 2 except client id):

`new Client
            {
                ClientId = "mvc01",
                ClientName = "MVC 01 Demo",
                AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,
                ClientSecrets = { new Secret("secret".Sha256()) },
                AllowAccessTokensViaBrowser = true,
                RequireConsent = false,
                RedirectUris =           { "https://localhost:44317/signin-oidc"},
                PostLogoutRedirectUris = { "https://localhost:44317/signout-callback-oidc" },
                BackChannelLogoutUri = "https://localhost:44317/signout-callback-oidc",
                FrontChannelLogoutUri  = "https://localhost:44317/signout-callback-oidc",
                AllowedCorsOrigins =     { "https://localhost:44317" },
                AllowedScopes =
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    IdentityServerConstants.StandardScopes.Email,
                    "office"
                }
            }
'
I also have tried to check the application info under chrome developer toolbar and found that they individually storing the cookies (.AspnetCore.Cookies, .AspnetCore.Cookies1, .AspnetCore.Cookies2) but that is for only that site) If I go to other application (where I haven't did sign-in) I am getting blank there.

Any suggestion?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
