### ISSUE TITLE
EF QuickStart Documentation SQL Script link is broken, 404.

### ISSUE THREAD

**Issue by nezoic** [IdentityServer/IdentityServer4#2666]
In the EF Quick Start Docs, the link to the SQL Scripts is throwing a 404.

http://docs.identityserver.io/en/release/quickstarts/8_entity_framework.html#refentityframeworkquickstart

![image](https://user-images.githubusercontent.com/5908638/46298252-34eaba80-c564-11e8-8455-50ca28f9de34.png)

**Comment by brockallen** [comment]
Thanks for the heads up. You can submit a PR to get this fixed!

**Comment by brockallen** [comment]
I just clicked the link and it was the right page.

**Comment by Chris-ZA** [comment]
I just submitted PR #2688 for this.  

The link was pointing to the dev branch.  I changed it to use the release branch [link](https://github.com/IdentityServer/IdentityServer4.EntityFramework/tree/release/src/Host/Migrations/IdentityServer)

**Comment by brockallen** [comment]
merged, thanks
