### ISSUE TITLE
JWKS endpoint content type

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#2669]
should be "application/jwk-set+json"

https://tools.ietf.org/html/rfc7517 section 8.5.1

**Comment by leastprivilege** [comment]
done on patch branch and merged to dev

**Comment by mantasaudickas** [comment]
Sorry, but these changes should not be made with patch version change as it breaks clients:

```
ERROR Error: Uncaught (in promise): Error: Invalid response Content-Type: application/jwk-set+json; charset=UTF-8, from URL: https://***.com/.well-known/openid-configuration/jwks
Error: Invalid response Content-Type: application/jwk-set+json; charset=UTF-8, from URL: https://***.com/.well-known/openid-configuration/jwks
```

Using "oidc-client": "1.5.0".

**Comment by leastprivilege** [comment]
please open a new issue.

**Comment by mantasaudickas** [comment]
I guess there is no need for a new issue, as change had to be done here, and oidc client also has already a fix for this.. just I wanted to complain about semantic versioning.. :)
For us such change means that we have to communicate across all departments to upgrade their clients and only then update IdentityServer packages.
I was not expecting breaking change with patch (2.3.X) version increment..

**Comment by leastprivilege** [comment]
> I was not expecting breaking change with patch (2.3.X) version increment..

me neither

**Comment by shaikatz** [comment]
@leastprivilege There are any updates on that issue? we almost fall on that trap as well, this patch broke behaviour for all clients.
