### ISSUE TITLE
CorsPolicyProvider class is no more public

### ISSUE THREAD

**Issue by senzacionale** [IdentityServer/IdentityServer4#267]
Why is `CorsPolicyProvider `no more `public` class. We used it before (`PolicyProvider`) just for allow more route paths.

How can we achieve same functionality now?

**Comment by brockallen** [comment]
The design was changed to have the `CorsPolicyProvider` decorate any custom `ICorsPolicyProvider` registered in DI prior to registering IdentityServer.

**Comment by senzacionale** [comment]
I used it so:

```
var paths = new List<string>(Constants.ProtocolRoutePaths.CorsPaths);
            paths.AddRange(CorsOptions.RoutePaths);

            // just for allow more route paths
            services.AddTransient<ICorsPolicyProvider>(provider =>
            {
                return new PolicyProvider(
                   provider.GetRequiredService<ILogger<PolicyProvider>>(),
                   paths,
                   provider.GetRequiredService<ICorsPolicyService>());
            });
            services.AddCors();
```

**Comment by senzacionale** [comment]
Do you have any idea how to solve this problem?

**Comment by brockallen** [comment]
That's opening this up beyond our intended design. Why do you need CORS on other paths?

**Comment by senzacionale** [comment]
Because I am using some AccountApi framework and I need CORS. Is it possible to make this class public?

**Comment by brockallen** [comment]
I guess what I'm not clear on it why aren't you just using the normal ASP.NET CORS support for those other paths in your app?

**Comment by senzacionale** [comment]
> Or are you saying that you want to use the Client configuration for the AllowCorsOrigins for the rest of your APIs?

Exactly that I need

**Comment by brockallen** [comment]
If that's all you need, then inject the `ICorsPolicyService` into your constructor and then use `IsOriginAllowedAsync` from your custom CORS policy provider.

**Comment by senzacionale** [comment]
but with `IsOriginAllowedAsync  `I can not achieve this logic

```
services.AddTransient<ICorsPolicyProvider>(provider =>
            {
                return new PolicyProvider(
                   provider.GetRequiredService<ILogger<PolicyProvider>>(),
                   paths,
                   provider.GetRequiredService<ICorsPolicyService>());
            });
```

**Comment by brockallen** [comment]
I moved the logic into an extension method so you can use it from your code.
