### ISSUE TITLE
 CORS request made for path: "/connect/authorize" from origin: but rejected because invalid CORS path

### ISSUE THREAD

**Issue by DFullbrook** [IdentityServer/IdentityServer4#2670]
I raised this issue back in Aug 2017 against Identity Server 3 (see #3829 [IdentityServer/IdentityServer3/issues/3829]). I noticed recently that **CorsPolicyService implementation not being picked up**  (see #1101) was fixed in Identity Server 4 - it looks like the same issue. In the comments, Brock, you mention that a workaround is to register "yours after you register IdentityServer in DI". Is there a similar workaround in Identity Server 3? If so, could you provide a code snippet?

Thanks.

**Comment by DFullbrook** [comment]
Hi Brock,

I provided my own Cors Policy Service

    public class MyCorsPolicyService : ICorsPolicyService
    {
        public Task<bool> IsOriginAllowedAsync(string origin)
        {
            return Task.FromResult(true);
        }
    }

And register it as follows:

factory.CorsPolicyService = new Registration<ICorsPolicyService, MyCorsPolicyService>();

The policy is never called.

Best regards,

David Fullbrook.

**Comment by brockallen** [comment]
I see, you're referring to IS3 not IS4. As we've mentioned elsewhere, IS3 is no longer supported. I'll follow up with you on your email for a commercial option.
