### ISSUE TITLE
Question: Why DefaultCookieTimeSpan is set by default to 10 hours?

### ISSUE THREAD

**Issue by igor-moskvitin** [IdentityServer/IdentityServer4#2674]
I see that by [default in AspNetCore](https://github.com/aspnet/Security/blob/release/2.1/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationOptions.cs#L32) timespan is set to 14 days, but for [IdentityServer defaults](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Constants.cs#L19) it sets to 10 hours. Can you provide reasons for reduce this time?
Now i have an issue when use renew access_token after 10 hours and set CookieLifetime to 24 hours, but what possible risks it intoduced?

**Comment by brockallen** [comment]
To be more precise: 10 hour, no sliding. It was chosen because it's a reasonable and safe default. You can change it to anything you want.

**Comment by igor-moskvitin** [comment]
And why it is more safe? What kind of attacks can use an extended lifetime for this cookie? I know that i can extend this, but want to know about reason to reduce it for default in IdSrv4.

**Comment by brockallen** [comment]
In our experience, most uses of IdentityServer expect a 10 hour fixed SSO session. It's a reasonable and safe default. I think the context is important too -- a user's lifetime in the SSO server is different than a user's lifetime in a general purpose ASP.NET Core MVC app.

Perhaps you should be asking why Microsoft chose 14 days by default for their cookie.

**Comment by brockallen** [comment]
Yes, and @TomCJones's source is what we basically modeled our choice on.

**Comment by igor-moskvitin** [comment]
Ok. Thanks.
