### ISSUE TITLE
How can i authenticate an MVC 5 application with IdentityServer4

### ISSUE THREAD

**Issue by debchy** [IdentityServer/IdentityServer4#2675]
**How can i authenticate an MVC 5 application with IdentityServer4**
My API Resource is an MVC 5 application. 
In the Quickstart I got how to authenticate a .net core API Resource  with Identityserver4 by adding dependency injection

> services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
              .AddIdentityServerAuthentication(options =>
              {
                  options.Authority = "http://localhost:59392/";
                  options.ApiName = "dataEventRecords";
                  options.ApiSecret = "dataEventRecordsSecret";
                  options.RequireHttpsMetadata = false;
              });

I need to know how can i authenticate my MVC application/Api same way like we did in .net core.

**Comment by SIkebe** [comment]
@debchy This might help you.
https://github.com/IdentityServer/CrossVersionIntegrationTests/tree/master/src/KatanaApiIdSrv4withRSA

**Comment by debchy** [comment]
Hi @SIkebe ,
Thanks for your reply. But the example in in IndentityServer3. I am not getting access to app.UseIdentityServerBearerTokenAuthentication using package IdentityServer4.AccessTokenValidation in MVC

**Comment by SIkebe** [comment]
Above example uses IdentityServer4, not IdentityServer3.
Am I missing something?

**Comment by debchy** [comment]
This method is using IdentityServer3.AccessTokenValidation;
https://github.com/IdentityServer/CrossVersionIntegrationTests/blob/master/src/KatanaApiIdSrv4withRSA/Program.cs

Also this example is setting configuration for client. But i need to make my MVC application as resourceAPI.

**Comment by SIkebe** [comment]
IdentityServer4.AccessTokenValidation is for ASP.NET Core 2 app.

> i need to make my MVC application as resourceAPI.

How about this?
https://github.com/IdentityServer/CrossVersionIntegrationTests/tree/master/src/KatanaApiIdSrv4withRSA

**Comment by brockallen** [comment]
Katana-based samples here: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients

**Comment by debchy** [comment]
I guess [this article](https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html) better explain what I want. But unfortunately it is with IDserver3

**Comment by debchy** [comment]
Only Hybrid flow works for MVC oidc connect with IDS4.
I found the **solution**
My Client in IDS4:
`
               new Client
                {
                    ClientId = "mvc",
                    ClientName = "MVC Client",
                    AllowedGrantTypes = GrantTypes.Hybrid,// GrantTypes.HybridAndClientCredentials,

                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },

                    RedirectUris = { "http://localhost:57346/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:57346/signout-callback-oidc" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        "api1"
                    },

                    AccessTokenType = AccessTokenType.Jwt,
                    AccessTokenLifetime = 3600,
                    IdentityTokenLifetime = 3600,
                    UpdateAccessTokenClaimsOnRefresh = true,
                    SlidingRefreshTokenLifetime = 30,
                    RefreshTokenExpiration = TokenExpiration.Absolute,
                    RefreshTokenUsage = TokenUsage.OneTimeOnly,
                    AlwaysSendClientClaims = true,

                    AllowOfflineAccess = true
                }`

In my MVC Owin Startup:
`
            
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            var testConfig = new OIDC_Configuration
            {
                ClientId = "mvc",
                ClientSecret = "secret",
                Authority = "http://localhost:57468/",
                RedirectUri = "http://localhost:57346/signin-oidc",
                PostLogoutRedirectUri = "http://localhost:57346/signout-callback-oidc",
                ResponseType = OpenIdConnectResponseType.CodeIdToken,
                Scope = "openid profile api1 offline_access",
                Resource = "api1",
            };
            
            var config = testConfig;// connect to test IDserver4
            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = config.ClientId,
                ClientSecret = config.ClientId,
                Authority = config.Authority,
                RedirectUri = config.RedirectUri,// "http://localhost:57346/signin-oidc",
                PostLogoutRedirectUri = config.PostLogoutRedirectUri,// "http://localhost:57346/signout-callback-oidc",
                ResponseType =config.ResponseType,
                Scope =config.Scope,
                Resource = config.Resource,

                RequireHttpsMetadata = false,
                UseTokenLifetime = false,    
                SignInAsAuthenticationType = "Cookies",

                
                //As per https://github.com/IdentityServer/IdentityServer4/issues/1225
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    AuthorizationCodeReceived = async n =>
                    {
                        var tokenClient = new TokenClient(
                            n.Options.Authority + "connect/token",
                            config.ClientId,
                            config.ClientSecret
                        );

                        var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(n.Code, n.RedirectUri);

                        if (tokenResponse.IsError)
                        {
                            throw new AuthenticationException(tokenResponse.Error);
                        }

                        var userInfoClient = new UserInfoClient(config.Authority + "connect/userinfo");

                        var userInfoResponse = await userInfoClient.GetAsync(tokenResponse.AccessToken);

                        var id = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType);
                        id.AddClaims(userInfoResponse.Claims);

                        var Name = userInfoResponse.Claims.FirstOrDefault(c => c.Type.Equals("Name", StringComparison.CurrentCultureIgnoreCase)).Value;
                        id.AddClaim(new Claim("access_token", tokenResponse.AccessToken));
                        id.AddClaim(new Claim("expires_at", DateTime.Now.AddSeconds(tokenResponse.ExpiresIn).ToLocalTime().ToString(CultureInfo.InvariantCulture)));
                        id.AddClaim(new Claim("refresh_token", tokenResponse.RefreshToken));
                        id.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
                        id.AddClaim(new Claim("sid", n.AuthenticationTicket.Identity.FindFirst("sid").Value));

                        n.AuthenticationTicket = new AuthenticationTicket(
                            new ClaimsIdentity(id.Claims, n.AuthenticationTicket.Identity.AuthenticationType, JwtClaimTypes.Name, JwtClaimTypes.Role),
                            n.AuthenticationTicket.Properties
                        );

                        List<Claim> _claims = new List<Claim>();
                        _claims.AddRange(new List<Claim>
                            {
                                new Claim("http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier", Name),
                                new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider",Name)
                            });

                    },

                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.RequestType != OpenIdConnectRequestType.Logout)
                        {
                            return Task.FromResult(0);
                        }

                        var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");

                        if (idTokenHint != null)
                        {
                            n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                        }

                        return Task.FromResult(0);
                    }
                }
            });`

Now the **problem** is with AntiForgeryToken. It is not getting claims coming from IDS4.

> A claim of type 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier' or 'http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider' was not present on the provided ClaimsIdentity.

What is the solution?

**Comment by nixa333** [comment]
Hi @debchy 

I have MVC5 app connecting to IS4 server, this is the code I use. I don't know if it's the best version/option but it works for me:

```csharp
public void ConfigureAuth(IAppBuilder app)
{
    AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub";

    app.UseCookieAuthentication(new CookieAuthenticationOptions
    {
        AuthenticationType = "Cookies",
         CookieHttpOnly = true
    });

    app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
    {
        Authority = ConfigurationManager.AppSettings["Authority"],
        ClientId = ConfigurationManager.AppSettings["ClientId"],
        ClientSecret = ConfigurationManager.AppSettings["ClientSecret"],
        RedirectUri = ConfigurationManager.AppSettings["RedirectUri"],
        ResponseType = "code id_token",
        Scope = "offline_access openid profile customscope",
        RequireHttpsMetadata = bool.Parse(ConfigurationManager.AppSettings["IsProduction"]),

        SignInAsAuthenticationType = "Cookies",
        Notifications = new OpenIdConnectAuthenticationNotifications
        {
            AuthorizationCodeReceived = async n =>
            {
                var disco = await DiscoveryClient.GetAsync(ConfigurationManager.AppSettings["Authority"]);
                // use the code to get the access and refresh token
                var tokenClient = new TokenClient(
                            disco.TokenEndpoint,
                            ConfigurationManager.AppSettings["ClientId"],
                            ConfigurationManager.AppSettings["ClientSecret"]);

                var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(n.Code, n.RedirectUri);

                if (tokenResponse.IsError)
                {
                    throw new Exception(tokenResponse.Error);
                }

                // use the access token to retrieve claims from userinfo
                var userInfoClient = new UserInfoClient(disco.UserInfoEndpoint);

                var userInfoResponse = await userInfoClient.GetAsync(tokenResponse.AccessToken);

                // create new identity
                var id = new ClaimsIdentity(n.AuthenticationTicket.Identity.AuthenticationType);
                id.AddClaims(userInfoResponse.Claims);

                id.AddClaim(new Claim("access_token", tokenResponse.AccessToken));
                id.AddClaim(new Claim("expires_at", DateTime.UtcNow.AddSeconds(tokenResponse.ExpiresIn).ToString()));
                id.AddClaim(new Claim("refresh_token", tokenResponse.RefreshToken));
                id.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
                id.AddClaim(new Claim("sid", n.AuthenticationTicket.Identity.FindFirst("sid").Value));

                n.AuthenticationTicket = new AuthenticationTicket(
                            new ClaimsIdentity(id.Claims, n.AuthenticationTicket.Identity.AuthenticationType, "name", "role"),
                            n.AuthenticationTicket.Properties);
                    }
                }
            });
        }
```

This is being called from Startup class

```csharp
public partial class Startup
{
    public void Configuration(IAppBuilder app)
    {
        ConfigureAuth(app);
    }
}
```

**Comment by debchy** [comment]
@nixa333, thanks. This code is same as what i used. My only missing part is AntiforgeryConfig

> AntiForgeryConfig.UniqueClaimTypeIdentifier = "sub";

Now @Html.AntiForgeryToken() is also not throwing any error. Awesome. But the question is how to logout!!

**Comment by nixa333** [comment]
Use this

```csharp
public void LogOff()
{
    System.Web.HttpContext.Current.GetOwinContext().Authentication.SignOut();
}
```

**Comment by debchy** [comment]
@nixa333, Thanks it works properly.
I can get the user email, phone, birthday, role etc as claims.
Now the next issue is how can I match the role in [Authorize(Roles="members")] attribute and that coming from claims.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by debchy** [comment]
Hi @brockallen ,
I have a related question.
If my resource is secured like bellow way, I can't get access to the client and always showing unauthorized_client. This time my client and resoruceAPI are stored in DB. the only difference between my inMemory Client, resource and User and EntityFrameworkClient,resource/User is in DB, I have added resource secret and resource scope. Check the bellow code-

`
new ApiResource("dukkan")
                {
                    ApiSecrets =
                    {
                        new Secret("dukkanSecret".Sha256())
                    },
                    Scopes =
                    {
                        new Scope
                        {
                            Name = "dukkanscope",
                            DisplayName = "Scope for the dukkan ApiResource"
                        }
                    },
                    UserClaims = { "role", "admin", "sa", "dukkan", "dukkan.admin", "dukkan.sa" }
                },
`
For more information, I am using the code that have mentioned earlier in the thread to access the IDS4
