### ISSUE TITLE
ASPNetIdentity and IdentityServer4

### ISSUE THREAD

**Issue by asharda1** [IdentityServer/IdentityServer4#2677]
HI ,
I followed all the Documentation from Identityserver.io.
My issue is 0 I have fresh server, where I want to use safe and secure ldentityServer so we choose Identityserver4 and as the documentation says we need to have our own User management I have used ASPNET Identity.
I have 3 DBCOntext and all are pointing to same Database, here when a user is created and the code given in Sample6 od quickstart works, from where it is log me in from Identity server or fromASPNetIdentity
1. I do not understand the relationship of these two framework although I have used .AddAspNetIdentity<ApplicationUser>() when defining the IdentityServer for User Base.
2. How I will add Claims or scopes to the user created from ASPNEtIDentity UI register page as it has only name and password field?
3. How to defined a user for some of the clients but not for the other type of clients?
Its urgent please response ASAP.

**Comment by saadishahin** [comment]
1. You can have a look at https://github.com/IdentityServer/IdentityServer4.AspNetIdentity to figure out what's happening exactly, it's really simple and straight forward.

2. You can copy the user UserClaimsFactory from there if you want to add additional logic, I don't know if there's another way to do.

3. I think you need to customize the User store to handle this, and you need to override the ResourceOwnerPasswordValidator to include the client in the check.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
