### ISSUE TITLE
Multiple external active directory providers 

### ISSUE THREAD

**Issue by nixa333** [IdentityServer/IdentityServer4#2678]
Hi,

this is a question, not an issue, and I also plan on posting it to SO, but don't even know where to start.
So basically I have a working IS4 auth server which has been serving my app and api for some time and it works great. Our solution supports regular user registration/login and also google and facebook logins.
Now we're presented with a challenge from one of our clients to enable their employees to log into our app with their existing AD user accounts.
Naturally I don't want to do this just for them, but would like to make it an option for all other enterprise users that have existing ADs.
I've been reading about federated gateways and windows login, but will definitely need to do some more reading. The major unknown for me, is how to allow anyone to connect their AD with my app, and then execute login process. Ideally I would like to do this by having a DB table of providers and loading them on app start, but if I'll have to manually add code block to my startup for each of them, I'll live with it.
Second unknow is the login process itself, do I have to have a separate login page for that, or check if I have a provider registered for that email domain user is signing in with, whenever anybody logs in?
Please help, I'm lost :)

**Comment by brockallen** [comment]
Feel free to add the link to the SO article. Folks can then follow it and reply there.

**Comment by nixa333** [comment]
Here's the SO link https://stackoverflow.com/questions/52648311/identityserver-4-multiple-external-active-directory-providers
