### ISSUE TITLE
Two-Factor authentication

### ISSUE THREAD

**Issue by saadishahin** [IdentityServer/IdentityServer4#2679]
Hello,

İ have a standalone identityserver that will be used to authenticate an Api and an angular6 client, is here anyway to use the AspNetİdentity 2fa? I'm thinking in a work around but I don't think it's a good idea to do so, I'm thinking of letting the user to sign-in, and if the identity result returned RequiresTwoFactor, I'll return custom error to the UI it asks for the 2facode and it will be sent to the server along with the username to identify the user, and if it's verified I'll send the token back.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
