### ISSUE TITLE
Resource Owner Flow in ASP.NET Core

### ISSUE THREAD

**Issue by avoxm** [IdentityServer/IdentityServer4#268]
I am using IdentityServer4 to authenticate/authorize users of my web application. 
Here is how it works : I have 3 nodes, Web API, Web Application and IdentityServer. Web API is secured by   IdentityServer and in order to send requests to API web application needs to provide a valid access token. Since I did not wanted to redirect user to identity server and I have control over all nodes I've concluded that Resource Owner flow is the way to go. 
So to login user provides his/her username and password,  Web App uses TokenClient to request access_token and refresh_token from Identity Server and stores them into claims so it can use it to send requests to Web API.

So the problem I have is to get the user id (sub). Currently I am decoding the access_token received from identity server to get the user id and storing it in claims again, but it feels more like a hack than a proper solution. 

And if this is the proper way of doing it, how can I validate the token using the secret key. 
At the moment I am just decoding the token from Base64 and converting the Json object.

Could you please advice.
Thanks

**Comment by leastprivilege** [comment]
IOW - you want the sub "outside" the access token so that the client can read it? That's exactly why resource owner flow is not recommended ;))

Anyways - starting with RC1 you can set custom response fields. Chech the new `GrantValidationResult` in the resource owner validator.

**Comment by avoxm** [comment]
@leastprivilege not exactly I want to have it inside access/identity token, I just want to populate claims out of access token. As I have noted I am still doing it by decoding bas64 string and etc, I was just thinking if there are better ways to do it.

**Comment by leastprivilege** [comment]
sorry - then I don't understand.

**Comment by avoxm** [comment]
@leastprivilege sorry probably I am not describing my case clear. 
Here's how login flow looks like : User provides username/pass in a web app, web app uses  TokenClient to request a token that contains sub. So the question is how to decrypt that token in web app properly so to get the sub. At the moment I am decoding the access token "manually" and populating claims accordingly, but it makes me think that there must be a better way of doing this.

**Comment by leastprivilege** [comment]
You need to properly validate the token. Use the MS JwtSecurityTokenHandle for this.

**Comment by avoxm** [comment]
Thanks @leastprivilege, will look into it.
