### ISSUE TITLE
Implementing Identity Server In a WCF Service Application

### ISSUE THREAD

**Issue by omoprodigi** [IdentityServer/IdentityServer4#2685]
Hi Guys, I've been scouring Google and other related resources for a tutorial or Guide to Implement Identity Server 4 in a WCF Service Application.

Most of the tutorials explore implementing it in a Web Api/MVC or Console App. 

Is it impossible to implement in a WCF Service ?

Please a link or guide to do this will be well appreciated.

**Comment by brockallen** [comment]
We have a sample: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/WcfService

having said that, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
