### ISSUE TITLE
Recommendation for grant type choice 

### ISSUE THREAD

**Issue by apacherose** [IdentityServer/IdentityServer4#2686]
Hello,
I'd like to be advised which grant type/authentication flow to use for the following case:

I have an API(api1) which is secured and authenticates from incoming tokens users or other API clients.
One functionality of this API(api1) requires to identify user from the token. We have another API(api2) that calls that functionality. I thought that I could issue resource owner access token for **some system user** for api2 and then make that call to api1.
But then I read your advise [here](http://docs.identityserver.io/en/release/topics/grant_types.html#resource-owner-password) that says it's not recommended.

I cannot issue delegation token because I don't have authenticated user and access token in api2.
I cannot issue client credentials token, because I won't have **sub** claim.

So, what is you recommendation for my case?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
