### ISSUE TITLE
In Memory Storage

### ISSUE THREAD

**Issue by arnaldo-infinite** [IdentityServer/IdentityServer4#2687]
Hi,

It is not regarding a bug or a feature, but just a verification. The identity server is storing the ID/Access Tokens in memory while it provides extensions to store refresh token and reference token in DB. Can the Identity Server store large amount of Access Token at the same time in memory without utilizing a DB for bulk storage of access tokens?

**Comment by brockallen** [comment]
id_tokens and access_tokens are sent back to the client, not kept in memory in IdentityServer (unless the access token is a reference token, which it is then stored in a similar way to refresh tokens).

**Comment by arnaldo-infinite** [comment]
Thank you so much for clearing my doubt, that made me go further into OAuth & Open ID specs.
