### ISSUE TITLE
[Question] In which place in the pipeline set user as logged in in DB

### ISSUE THREAD

**Issue by QuantumDeveloper** [IdentityServer/IdentityServer4#2689]
Hi, I am using scheme with authentication using my DB and ASP Core identity Server. I also implemented `IResourceOwnerPasswordValidator` and `IProfileService`.
I am connecting to server through `tokenClient.RequestResourceOwnerPasswordAsync` method and dont use MVC

Everything seems working as expected, but I want to set `IsLoggedIn` property to user and save it in DB and when session will be over, set it to false.

What is the best place to do it? Didn't find answer anywhere.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
