### ISSUE TITLE
NullReferenceException in DiscoveryEndpoint using NET452

### ISSUE THREAD

**Issue by BrettJaner** [IdentityServer/IdentityServer4#269]
When using the SetTemporarySigningCredential() method running NET452, the RsaSecurityKey is initialized using RsaParameters.  This leaves the Rsa property on the RsaSecurityKey as null.  In the DiscoveryEndpoint.ExecuteJwksAsync method, we are looking at the Rsa property to retrieve back the parameters.  This is where the NullReferenceException happens.

Here is code snippet from SetTemporarySigningCredential():

```
RsaSecurityKey key = null;
#if NET452
   if (rsa is RSACryptoServiceProvider) 
   {
       var parameters = rsa.ExportParameters(includePrivateParameters: true);
       key = new RsaSecurityKey(parameters);
                        
       rsa.Dispose();
   }   
#endif
   if (key == null)
   {
       key = new RsaSecurityKey(rsa);
   }
```

And a code snippet from ExecuteJwksAsync():

```
var rsaKey = key as RsaSecurityKey;
if (rsaKey != null)
{
    var parameters = rsaKey.Rsa.ExportParameters(false);

    var exponent = Base64Url.Encode(parameters.Exponent);
    var modulus = Base64Url.Encode(parameters.Modulus);
```

A solution could be null checking the Rsa property, and if null using the Parameters property instead.  Seems to work on my machine.

```
var parameters = rsaKey.Rsa != null
    ? rsaKey.Rsa.ExportParameters(false)
    : rsaKey.Parameters;
```

**Comment by leastprivilege** [comment]
thanks - will look into it.

**Comment by Lutando** [comment]
I also just ran into this. 

It specifically occurs in `DiscoveryEndpoint.cs` : `line 265`

quick repro step is to just change the target framework of any of the quickstart frameworks to net451-ne461.

**Comment by leastprivilege** [comment]
@BrettJaner wanna send a PR? against dev.

**Comment by leastprivilege** [comment]
@BrettJaner nm - I did it myself - also wrote a test for it.

Update on the dev nuget feed.

**Comment by leastprivilege** [comment]
I published a 1.0.0-rc1-update1 to nuget with a fix.

**Comment by RolandGuijt** [comment]
Thanks!

**Comment by BrettJaner** [comment]
Thanks all!
