### ISSUE TITLE
sub claim is missing with Azure AD. while Google and Facebook is working

### ISSUE THREAD

**Issue by brijesh-1111** [IdentityServer/IdentityServer4#2690]
I am getting an error while I have External Authentication as Azure AD. However,  with Google and Facebook everything is working well (alongside of Entity Framework Local Authentication).

I have following piece of code in Startup.

public void ConfigureServices(IServiceCollection services)
{
	AuthenticationSettings authenticationSettings = services.RegisterAuthenticationSettings(configuration: Configuration);

	services.AddDbContext<ApplicationDbContext>(options =>
		options.UseSqlServer(
			Configuration.GetConnectionString("DefaultConnection")));

	services.AddIdentity<ApplicationUser, IdentityRole>()
		.AddEntityFrameworkStores<ApplicationDbContext>()
		.AddDefaultTokenProviders();

	services.AddAuthentication()
	 .AddGoogle(GoogleDefaults.AuthenticationScheme, options =>
	 {
		 options.SignInScheme = IdentityConstants.ExternalScheme

		 options.ClientId = "GoogleClientId";
		 options.ClientSecret = "GoogleSecret";
		 options.CallbackPath = "/signin-google";
	 })
	 .AddFacebook(FacebookDefaults.AuthenticationScheme, options => 
	 {
		 options.SignInScheme = IdentityConstants.ExternalScheme;

		 options.ClientId = "FacebookClientId";
		 options.ClientSecret = "FacebookClientSecret";
		 options.CallbackPath = "/signin-facebook";
	 })
	 .AddMicrosoftAccount(MicrosoftAccountDefaults.AuthenticationScheme, options => 
	 {
		 options.SignInScheme = IdentityConstants.ApplicationScheme;

		 //options.ClientId = "AzureADClientId";
		 //options.ClientSecret = "AzureADClientSecret";
		 options.CallbackPath = "/signin-microsoft";

	 });

	var builder = services.AddIdentityServer(options =>
	{
		options.Events.RaiseErrorEvents = true;
		options.Events.RaiseInformationEvents = true;
		options.Events.RaiseFailureEvents = true;
		options.Events.RaiseSuccessEvents = true;
	})
	.AddInMemoryPersistedGrants()
	.AddInMemoryIdentityResources(Config.GetIdentityResources())
	.AddInMemoryApiResources(Config.GetApiResources())
	.AddInMemoryClients(Config.GetClients())
	.AddAspNetIdentity<ApplicationUser>();

	if (Environment.IsDevelopment())
	{
		builder.AddDeveloperSigningCredential();
	}
	else
	{
		builder.AddSigningCredential(authenticationSettings.IdentityServer.SigningCredentialCertificateName);
	}
}

while configure method has:

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            //app.UseAuthentication();
            app.UseIdentityServer();

            app.UseMvcWithDefaultRoute();
        }

The Error message I am getting is:

**An unhandled exception occurred while processing the request.
InvalidOperationException: sub claim is missing
IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal) in IdentityServerAuthenticationService.cs, line 119
IdentityServer4.Hosting.IdentityServerAuthenticationService.AssertRequiredClaims(ClaimsPrincipal principal) in IdentityServerAuthenticationService.cs**

Not sure, why many of the articles (with in this context) suggest that we are missing .AddIdentity solves the problem. But for my case, its already there and it's working with Google and Facebook. Not with Azure AD.

Any quick suggestion? I haven't change any code for Identity Server 4 Quick Start.

**Comment by brockallen** [comment]
```
.AddMicrosoftAccount(MicrosoftAccountDefaults.AuthenticationScheme, options => 
 {
	 options.SignInScheme = IdentityConstants.ApplicationScheme;
```

That config looks different than the other external providers that are working.

**Comment by brijesh-1111** [comment]
Looks very embarrassed when we do such silly mistake. Thanks for quick reply.
