### ISSUE TITLE
Identity created in extension grants

### ISSUE THREAD

**Issue by federicobarera** [IdentityServer/IdentityServer4#2693]
Hi,

when using the extension grant, in the `IExtensionGrantValidator` implementation is it possible to return a `GrantValidationResult` with a `ClaimsPrincipal -> ClaimsIdentity`
Since idtoken is not returned from custom grants, but an identity is indeed created during the grant, how can you access the details?

EDIT:
After few attempts (mainly didn't understand that openid has to be registered as resource), I've managed to get the openid scope in the access_token an call the userinfo. I did not find tho the initial 14 (custom) claims created in the `IExtensionGrantValidator` implementation.
Even overwriting the `IProfileService` to intercept the `if (context.Caller == "UserInfoEndpoint")` the `context.Subject.Claims` does not contain the initial claims returned by the `IExtensionGrantValidator`.

Should I persist those claims somewhere myself, or am I missing something?

Thanks,

Federico

**Comment by leastprivilege** [comment]
All claims you return from an extension grant are available in the profile service. From there you need to return them in GetProfileDataAsync so they get put into an access token.

**Comment by federicobarera** [comment]
Hi @leastprivilege 

the claims are indeed available in the `GetProfileDataAsync` when the access token is created. Not all claims tho are necessary in the access token, that's why I hoped I could return a subset while leaving the others in the user-info.

Based on this question: https://github.com/IdentityServer/IdentityServer3/issues/1521 I hope there was a way to do it oob

**Comment by federicobarera** [comment]
I also had a look at this linked project https://github.com/waqaskhan540/IdentityServerExternalAuth which performs token exchange. 
He is actually persisting an identity after token-exchange, but when calling the userinfo endpoint, only the subject is returned

```
var result = await tokenClient.RequestCustomGrantAsync("external", "Test.WebApi openid email profile", payload);
var client = new HttpClient();
client.SetBearerToken(result.AccessToken);
var r = await client.GetAsync(disco.UserInfoEndpoint);
var c = await r.Content.ReadAsStringAsync();
```

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by leastprivilege** [comment]
You define the behavior of userinfo by implementing IProfileService.

**Comment by federicobarera** [comment]
I see. Thanks for the reply, can be closed
