### ISSUE TITLE
MVC Client and Api working together

### ISSUE THREAD

**Issue by pfuentes1402** [IdentityServer/IdentityServer4#2698]
I am using IdentityServer4 to create the Identity server, and I have a MVC project that uses identity server security but I also expose an API in this same MVC project and not separated, I have read and followed the indications of the Switching to Hybrid Flow and adding API Access back but I have not got it.
What I need is to have a MVC client and an Api working together on the same project both protected with the security of the identity project. Is this possible?.

**Comment by ngruson** [comment]
Have you checked out this sample? https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/5_HybridFlowAuthenticationWithApiAccess

Only difference is that your client app and API would co-exist in the same project, but that should be no problem as long as you setup the middleware correctly.

**Comment by pfuentes1402** [comment]
Thanks for your attention, but I well need correct configuration  to middleware to allow MVC project and Api working together. In 5_HybridFlowAuthenticationWithApiAccess the configurations wonking separated and when join two configuration (Api + MVC client) into same project, it not work. Exist any example with the correct configuration to  middleware ?

**Comment by ngruson** [comment]
Cooked up a working sample. 
Trick is to add authentication handler for JwtBearer and using that same scheme in the API controller.

Startup.cs:
`services.AddAuthentication()
                .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
                {
                    options.Authority = "http://localhost:5000";
                    options.RequireHttpsMetadata = false;
                    options.Audience = "api1";
                    options.SaveToken = true;
                });`

API controller:
`[Route("[controller]")]
    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class IdentityController : ControllerBase
    {`

**Comment by pfuentes1402** [comment]
Thanks, this solutions is very good, I configured my MVC client and work OK. Thanks soo much
