### ISSUE TITLE
Port JWT client authentication

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#27]
...needs new Microsoft.IdentityModel (RC2)

**Comment by uncleyo** [comment]
should I help with this one?

**Comment by leastprivilege** [comment]
Yes - but we have to wait until RC2 - and there is currently no ETA for this.

**Comment by leastprivilege** [comment]
Hey, wanna investigate how that would work with the new bits?

**Comment by uncleyo** [comment]
Sure, I'll take a look!

**Comment by leastprivilege** [comment]
progress?

**Comment by uncleyo** [comment]
The bits are there https://github.com/uncleyo/IdentityServer4/tree/private_key_jwt, but I wanted to add some integration tests and got stuck there. I'll try to finish it this week
