### ISSUE TITLE
What has happened with IRefreshTokenStore, IConsentStore, ITokenHandleStore and IAuthorizationCodeStore

### ISSUE THREAD

**Issue by ansaj777** [IdentityServer/IdentityServer4#270]
Hi,

i would like to know what has happened with
`RefreshTokenStore, IConsentStore, ITokenHandleStore and IAuthorizationCodeStore`

They not exist any more. How to implement different scopes now?

regards,
Mitja

**Comment by leastprivilege** [comment]
They have all been replaced by `IPersistedGrantStore`
