### ISSUE TITLE
how to logout  via post method

### ISSUE THREAD

**Issue by wlnh420** [IdentityServer/IdentityServer4#2701]
await HttpContext.SignOutAsync("oidc");  this method  as  httpget and there is an error:' length of id_token_hint is too long'
----------------------------------------------------
I want to logout  as httpPost method?
or
How I get id_token and i can logout via <input name="id_token_hint" value="???????">

**Comment by ngruson** [comment]
Please look at https://github.com/IdentityServer/IdentityServer3/issues/1845

**Comment by rasitha1** [comment]
FYI - there's a suggestion to support POST for logout: https://bitbucket.org/openid/connect/issues/1056/use-of-id_token-in-rp-initiated-logout-as
