### ISSUE TITLE
How to use my own authority?

### ISSUE THREAD

**Issue by fagnercarvalho** [IdentityServer/IdentityServer4#2702]
I was playing with the [5_HybridFlowAuthenticationWithApiAccess](https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/5_HybridFlowAuthenticationWithApiAccess) sample from the [IdentityServer/IdentityServer4.Samples](https://github.com/IdentityServer/IdentityServer4.Samples/) repository and I noticed that the QuickstartIdentityServer project is referencing https://demo.identityserver.io as the OpenID Connect authority. How to use my own authority in this case? I want to use this code as a reference for my own code but I didn't want to use this URL.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
