### ISSUE TITLE
    services.AddOidcStateDataFormatterCache(); doesn't stop from sending out huge state parameter

### ISSUE THREAD

**Issue by tiwari-abhishek** [IdentityServer/IdentityServer4#2704]
### Issue / Steps to reproduce the problem
I use an external IdP hosted in Azure, as oidc provider for my IdentityServer. For whatever reason, the **AddOpenIdConnect** middleware is adding a gigantic 'state' parameter which kills the logout request and there is no redirection back to my IdentityServer on signout. The external idp shows this message: `"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable"`

I tried to use the **AddOidcStateDataFormatterCache** middleware, but it still doesnt make a difference. I tried to disable Telemetry to reduce the URL size but it didnt help as well. Below is my configuration, pretty simple and standard. 

```
    public void ConfigureServices(IServiceCollection services)
        {
            services.AddOidcStateDataFormatterCache();
            services.AddAuthentication(options =>
            {
                options.DefaultChallengeScheme = "external-idp";
            })
            .AddOpenIdConnect("external-idp", "OpenID Connect", options =>
            {
                options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                options.Authority = "https://external-idp.com/";
                options.ClientId = "client1";
                options.ClientSecret = "secret";
                options.ResponseType = "code";
                options.SaveTokens = true;
                options.CallbackPath = "/login";
                options.SignedOutCallbackPath = "/logout";
                options.RemoteSignOutPath = "/logout";
                options.DisableTelemetry = true;                
            });
       }
```
If I remove or alter the "state" parameter, redirect back to my IdentityServer works but redirect back to application fails, and then if I re-trigger a logout, I finally land on my client application.

I also tried to override the state parameter by adding my own as below, but it didnt make any difference, state was still huge:
```			options.Events.OnRedirectToIdentityProviderForSignOut = (ctx) =>
                {
                    ctx.ProtocolMessage.Parameters.Add("state", "blah");
                    return Task.FromResult(0);
                };```

Is anyone struggling with this?

**Comment by leastprivilege** [comment]
`services.AddOidcStateDataFormatterCache();` is wrong - you need to pass in the name(s) of the handlers you want to apply this behavior:

https://github.com/IdentityServer/IdentityServer4/blob/3769bc41d625439f4ff94d2d8a4a247053c28037/host/Startup.cs#L77
