### ISSUE TITLE
How to secure .net MVC 5 API with IdentityServer?

### ISSUE THREAD

**Issue by debchy** [IdentityServer/IdentityServer4#2708]
All the example to secure MVC API is with IdentityServer3. they are using IdentityServer3.AccessTokenValidation
` app.UseOAuthBearerAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "https://localhost:44319/identity",
                RequiredScopes = new[] { "sampleApi" }
            });`
In QuickStart, .net core 2 has package for IdentityServer4.AccessTokenValidation. but for MVC5 there's no such package.

Please help I need to secure my API. Please don't provide example of IdentityServer3. Microsoft's IdentityModel version is not compatible with it. IdentityServer3.AccessTokenValidation need IdentityModel version less than 2.0.0 but my IdentityModel Verison is 3.4.0

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
