### ISSUE TITLE
Identity Server 4 update from 1.0.0 beta 5 to 1.0.0 rc1 error

### ISSUE THREAD

**Issue by oferAshkenazy** [IdentityServer/IdentityServer4#271]
Hi ,
Upgraded my project ,
when calling the "http://MyServer/connect/token"
I get the following error : 
Unable to resolve service for type 'IdentityServer4.Stores.IPersistedGrantStore' while attempting to activate 'IdentityServer4.Services.Default.DefaultPersistedGrantService'.
"

Thanks for the help

**Comment by leastprivilege** [comment]
Add `AddInMemoryStores()`

**Comment by oferAshkenazy** [comment]
Thanks it worked!!!
