### ISSUE TITLE
Different token key in database and cache

### ISSUE THREAD

**Issue by Arsmn1996** [IdentityServer/IdentityServer4#2711]
I enabled cache for access token in my api and use Redis for caching.
Token key that stored in Redis is different from token key in permament database.
Why they are not same?
I want to remove key in Redis when an access token revoke by user but i cant access to that.

**Comment by brockallen** [comment]
we hash the key in our DB in case the IS DB is compromised.

**Comment by Arsmn1996** [comment]
Thanks @brockallen 
so I don't have access from IdentityServer to delete token from cache?
Which hash algorithm IS use?

**Comment by brockallen** [comment]
>  so I don't have access from IdentityServer to delete token from cache?

I don't follow.

>  Which hash algorithm IS use?

SHA256

**Comment by Arsmn1996** [comment]
Thank you @brockallen
