### ISSUE TITLE
Requesting Claims using the "claims" Request Parameter

### ISSUE THREAD

**Issue by thelegendofando** [IdentityServer/IdentityServer4#2712]
Hello,

I require a [feature](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter) which is in the OpenID Connect spec, I believe it's optional and I can't see any support for it in the source code and the disco omits the `claims_parameter_supported` value.

Questions:
Is there support for this feature and I'm just missing it?
Are there any plans to support it?
Could I implement this functionality and open a PR?

Thanks in advance.

**Comment by leastprivilege** [comment]
We currently don't support this, and have no plans right now to support it.

That being said - I just skimmed the spec, it seems you simply add a `claims` query string param to the authz request. You can do that today and get access to it from within your code. 

Maybe that's a starting point that could lead to a formal feature.

**Comment by thelegendofando** [comment]
Cool. Thanks for getting back to me so quickly!
