### ISSUE TITLE
Allow custom PersistentGrantSerializer claim converters

### ISSUE THREAD

**Issue by acarlonvs** [IdentityServer/IdentityServer4#2713]
**Is your feature request related to a problem? Please describe.**
I am currently inheriting from DefaultUserSession to implement custom bearer JWT based authentication. The resulting ClaimsPrincipal is a type that is derived from ClaimsPrincipal. 
Problem occurs in PersistentGrantSerializer when storing the auth code. Specifically, the serialization fails with PlatformNotSupported exception. This is because ClaimsPrincipal claims cannot be serialized. There is already code in PersistentGrantSerializer.cs to accommodate this by way of the ClaimConverter and ClaimsPrincipalConverter 

        public PersistentGrantSerializer()
        {
            _settings = new JsonSerializerSettings();
            _settings.ContractResolver = new CustomContractResolver();
            _settings.Converters.Add(new ClaimConverter());
            _settings.Converters.Add(new ClaimsPrincipalConverter());
        }

The problem is that the `ClaimsPrincipalConverter` check does not include derived types: 

        public override bool CanConvert(Type objectType)
        {
            return typeof(ClaimsPrincipal) == objectType;
        }

**Describe the solution you'd like**
It is possible to implement custom serialization by implementing IPersistentGrantSerializer. However, it would be ideal to simply wrap / inherit from the existing PersistentGrantSerializer and benefit from any future improvements. The problem is that _settings is private. This means that it is not possible to add a custom claims converter, e.g. CustomerPrincipalClaimsConverter. 

**_Therefore, it seems best to add a protected Settings property to PersistentGrantSerializer._**

This allows wrapping or inheriting PersistentGrantSerializer, with the only additional logic being the addition of the custom claim converters.

**Describe alternatives you've considered**
* Using Clone on the ClaimsPrincipal, but this means that the derived information is lost. 
* Implementing IPersistentGrantSerializer, but this means missing out on future improvements. 
* Change ClaimsPrincipalConverter to include derived types in CanConvert, but it seems better to explicitly add a separate converter to avoid unexpected side effects.

**Comment by brockallen** [comment]
I think in the future we will be moving away from using the non-serializable Claim class internally. So I think this feature request will become moot. I know it was opened a long time ago, so I imagine in the meantime you have some workaround. Thanks
