### ISSUE TITLE
Token expired error level too high

### ISSUE THREAD

**Issue by EvgenyKhaliper** [IdentityServer/IdentityServer4#2714]
Is this necessary to have error for that ? I mean if client makes constant requests should it be enough just to 401 ?
Can we check whether the reference token expired before accessing with it ?

thanks

IdentityServer4.Validation.TokenValidator

```
if (token.CreationTime.HasExceeded(token.Lifetime, _clock.UtcNow.UtcDateTime))
{
    **LogError("Token expired.");**

    await _referenceTokenStore.RemoveReferenceTokenAsync(tokenHandle);
    return Invalid(OidcConstants.ProtectedResourceErrors.ExpiredToken);
}
```

**Comment by TCDooM** [comment]
yes, we really need this change.
it is annoying to get this error when it is just fine actually.

**Comment by leastprivilege** [comment]
tracking here

https://github.com/IdentityServer/IdentityServer4/issues/3518
