### ISSUE TITLE
Client getting Invalid Scope error while client is registered with IdentityServer4

### ISSUE THREAD

**Issue by omkarchoudhari** [IdentityServer/IdentityServer4#2715]
Right now i am using IdentityServer4 and implementing in .NetCore 2.1. I configured the server as per documentation and i had tested client authentication and authorization also. it works fine.

But somehow, means its really weird to said that after few days it stops working, means i can login to the server, i have successfully create users, and clients also but when i hit Client URL it gives me error like below…

Sorry there was an error: Invalid Scope.

and redirect to home/error page.

but few days before i have tested same scenario and that time works fine.

Here are the details
1) Using ASPNET IDENTITY.
2) USING CONFIGURATIONDBCONTEXT and PERSISTANTDBCONTEXT.

so i all values are coming from database.

this is client authetication code in STARTUP.CS

services.AddAuthentication(options =>
{
options.DefaultScheme = “Cookies”;
options.DefaultChallengeScheme = “oidc”;
}).AddCookie(“Cookies”,
(options) =>
{
options.AccessDeniedPath = “/Authorization/AccessDenied”;
})
.AddOpenIdConnect(“oidc”, options =>
{
options.SignInScheme = “Cookies”;
options.Authority = “https://localhost:44388”;
options.ClientId = “OnCallClient”;
options.ResponseType = “code id_token”;
options.Scope.Add(“openid”);
options.Scope.Add(“profile”);
options.Scope.Add(“address”);
options.Scope.Add(“roles”);
options.SaveTokens = true;
options.ClientSecret = “secret”;
options.GetClaimsFromUserInfoEndpoint = true;
options.ClaimActions.Remove(“amr”);
options.ClaimActions.DeleteClaim(“sid”);
options.ClaimActions.DeleteClaim(“idp”);
options.ClaimActions.Add(new JsonKeyClaimAction(“role”, “role”, “role”));

});

and i registered above client like this

var clients = new Client
{
ClientName = Model.ClientName,
ClientUri = Model.ClientUri,
ClientId = Model.ClientId,
AllowedGrantTypes = IdentityServer4.Models.GrantTypes.Hybrid,
//AccessTokenLifetime= 60,
RedirectUris = new List()
{
Model.ClientUri.EnsureEndsWith(‘/’)+”signin-oidc”
},
PostLogoutRedirectUris = new List()
{
Model.ClientUri.EnsureEndsWith(‘/’)+”signout-callback-oidc”
},
AllowedScopes =
{
IdentityServerConstants.StandardScopes.OpenId,
IdentityServerConstants.StandardScopes.Profile,
IdentityServerConstants.StandardScopes.Address,
“roles”
},
ClientSecrets =
{
new Secret(“secret”.Sha256())
}
};

I have spend lots of time in resolving this issue, Please Help me to solve this issue.

**Comment by brockallen** [comment]
Not sure. You will have to investigate more.

**Comment by omkarchoudhari** [comment]
This issue appeared in another environment as well. you have marked it as a question. does that mean that it wont be flagged as Issue anymore ?

**Comment by leastprivilege** [comment]
Not unless you have log files that give more information.

**Comment by brockallen** [comment]
Any update?

**Comment by myc0l** [comment]
I am having the same issue Idsvr just stops working and gives error status code 302 on authorization endpoint. It was working fine before
