### ISSUE TITLE
ICustomTokenRequestValidator Transient service not working on first request

### ISSUE THREAD

**Issue by egulbrand** [IdentityServer/IdentityServer4#2716]
Hello,

I am attempting to add a client claim when a request comes through from a client using the client_credentials flow.  I created a class that implements ICustomTokenRequestValidator:
`    public class CustomTokenRequestValidator : ICustomTokenRequestValidator
    {

        public Task ValidateAsync(CustomTokenRequestValidationContext context)
        {
            var result = context.Result;
            
            if(result.IsError == false)
            {
                if(result.ValidatedRequest.Client.ClientId == "clientid")
                {
                    string[] strpassedids = result.ValidatedRequest.Raw.GetValues("passed_through_id");
                    string strPassedID = strpassedids[0];

                    var client = context.Result.ValidatedRequest.Client;
                    client.Claims.Add(new Claim("passed_id", strPassedID));
                    return Task.CompletedTask;
                }
                else
                {
                    throw new Exception("Error Validation Token: " + result.ErrorDescription);
                }
            }
            else
            {
                throw new Exception("Error Validation Token: " + result.ErrorDescription);
            }
        }
    }`

I then added this class as a transient service in DI:
`            builder.Services.AddTransient<ICustomTokenRequestValidator, CustomTokenRequestValidator>();
`
Once I start IdentityServer4, the first time I submit a request to the token endpoint, the added claim is not there.  But after the first time, the added claim is there everytime.  If I put a breakpoint in the code, the claim is there the first time. This indicates to me that the ICustomTokenRequestValidator is not done by the time the access token is created and returned to the client. Is there something more I need to do to insure the claim will be added?

Any suggestions would be appreciated.

Thanks.

**Comment by leastprivilege** [comment]
Adding claims like

```
var client = context.Result.ValidatedRequest.
client.Claims.Add(new Claim("passed_id", strPassedID));
```

can have side effects - especially with the in-memory config store. There is a client claims collection directly on the `ValidatedRequest` object - use this one instead.

**Comment by egulbrand** [comment]
I updated my claims to be added directly to the ValidatedRequest.ClientClaims collection and it worked the first time and all subsequent times. Thanks for the assistance.
