### ISSUE TITLE
Lowercase URLs for login/logout are broken

### ISSUE THREAD

**Issue by u-abramchuk** [IdentityServer/IdentityServer4#2721]
Hello!

My application uses lowercase routes. This is configured via
```cs
services.Configure<RouteOptions>(options => options.LowercaseUrls = true);
services.AddMvc();
```

It worked as expected with IdentityServer4 version 2.2.0. But after I've updated to 2.3.0-preview1-update2 login and logout URLs are generated in pascal case like `http://localhost:5000/Account/Login?...`. 

Other routes work as expected.

Thank you in advance.

**Comment by brockallen** [comment]
Could this be because the default LoginPath is coming from the cookie options which is hard coded like:

```
public static readonly PathString LoginPath = new PathString("/Account/Login");
```

**Comment by u-abramchuk** [comment]
I've checked this in the first place, I don't specify LoginPath in cookie options.

**Comment by u-abramchuk** [comment]
I've debugged it a bit. It turns out "/Account/Login" value comes from [Asp.Net Identity](https://github.com/aspnet/Identity/blob/master/src/Identity/IdentityServiceCollectionExtensions.cs#L53)
