### ISSUE TITLE
Field not found exception with IdentityServer4.EntityFrameWork.DbContext

### ISSUE THREAD

**Issue by sameerlm** [IdentityServer/IdentityServer4#2722]
Using MySQL DB with entityframework,

Migrations running successfully, when it attempts to see if any records in Clients(in below code snippet) it gives below exception
"System.MissingFieldException: 'Field not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueExceptionMethod'.' "

private void InitializeDatabase(IApplicationBuilder app)
        {
            using (var serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
            {
                serviceScope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>().Database.Migrate();

                    var context = serviceScope.ServiceProvider.GetRequiredService<ConfigurationDbContext>();
                    context.Database.Migrate();
                    if (**!context.Clients.Any()**)
                    {
                        foreach (var client in InMemoryConfiguration.Clients())
                        {
                            context.Clients.Add(ClientMappers.ToEntity(client));
                        }
                        context.SaveChanges();
                    }
               
            }
        }

**Comment by brockallen** [comment]
There's not enough info from your error to tell which field is missing. Can you debug more please?

**Comment by sameerlm** [comment]
Program.cs Code
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateWebHostBuilder(args).Build().Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
            .UseKestrel()
            .UseUrls("http://localhost:56940")
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseIISIntegration()
            .UseStartup<Startup>();
        
    }


Startup Code

public class Startup
    {
        //const string connectionString = @"Data Source=(LocalDb)\MSSQLLocalDB;database=IdentityServer4.Quickstart.EntityFramework-2.0.0;trusted_connection=yes;";
        

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            string migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name; 
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1); ;

            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddTestUsers(InMemoryConfiguration.Users().ToList())
                // this adds the config data from DB (clients, resources)
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseMySql(Configuration.GetConnectionString("DataAccessMySqlProvider"),
                            mysql => mysql.MigrationsAssembly(migrationsAssembly));
                   
                })
                // this adds the operational data from DB (codes, tokens, consents)

                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseMySql(Configuration.GetConnectionString("DataAccessMySqlProvider"),
                            mysql => mysql.MigrationsAssembly(migrationsAssembly));

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 30;
                });


        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env,ILoggerFactory loggerFactory)
        {
            //InitializeDatabase(app);
            loggerFactory.AddConsole();
            app.UseIdentityServer();
            app.UseDeveloperExceptionPage();
            app.UseStaticFiles();
            app.UseMvcWithDefaultRoute();
        }

        //private void InitializeDatabase(IApplicationBuilder app)
        //{
        //    using (var serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
        //    {
        //        serviceScope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>().Database.Migrate();

        //            var context = serviceScope.ServiceProvider.GetRequiredService<ConfigurationDbContext>();
        //            context.Database.Migrate();
        //            if (!context.Clients.Any())
        //            {
        //                foreach (var client in InMemoryConfiguration.Clients())
        //                {
        //                    //context.Clients.Add(ClientMappers.ToEntity(client));
        //                    context.Clients.Add(IdentityServer4.EntityFramework.MySql.Mappers.ClientMappers.ToEntity(client));
        //                }
        //                context.SaveChanges();
        //            }
               

        //        //if (!context.IdentityResources.Any())
        //        //{

        //        //    foreach (var resource in InMemoryConfiguration.IdentityResources())
        //        //    {
        //        //        context.IdentityResources.Add(resource.ToEntity());
        //        //    }
        //        //    context.SaveChanges();
        //        //}

        //        //if (!context.ApiResources.Any())
        //        //{
        //        //    foreach (var resource in InMemoryConfiguration.ApiResources())
        //        //    {
        //        //        context.ApiResources.Add(resource.ToEntity());
        //        //    }
        //        //    context.SaveChanges();
        //        //}
        //    }
        //}
    }

**Comment by brockallen** [comment]
Sorry, I don't plan on debugging your code. I need you to debug it to help your issue. Does your call stack have the field name? If not, please debug it more in your environment and provide me which one is missing.

**Comment by sameerlm** [comment]
Hi Brock,

Managed to resolve the issue, updated Microsoft.EntityFrameworkCore nuget pagckage to latest version.
