### ISSUE TITLE
offline_access is reported in discovery document but not allowed

### ISSUE THREAD

**Issue by uhfath** [IdentityServer/IdentityServer4#2723]
I believe it's set here:
https://github.com/IdentityServer/IdentityServer4/blob/master/src/ResponseHandling/Default/DiscoveryResponseGenerator.cs#L181

It reports that we have allowed "offline_access", whereas we haven't defined it anywhere.
Also, if a client requests this scope (and we haven't allowed it) the identity server reports, that it's incorrect, as it should.
However, the discovery document shows that it's allowed.

Is there a reason for this?

**Comment by brockallen** [comment]
Did you enable it on the client config?

**Comment by uhfath** [comment]
Nope.
Unless it's enabled by some other property.
Here is the config:

`new Client
{
    ClientId = "invoices.ui",
    RequireConsent = false,
    AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,
    AccessTokenType = AccessTokenType.Reference,

    AllowedCorsOrigins = configuration.GetSection("Redirect").Get<RedirectOptions>().AllowedCorsOrigins.ToList(),
    RedirectUris = configuration.GetSection("Redirect").Get<RedirectOptions>().RedirectUris.ToList(),
    PostLogoutRedirectUris = configuration.GetSection("Redirect").Get<RedirectOptions>().PostLogoutRedirectUris.ToList(),

    ClientSecrets =
    {
        new Secret("invoices.ui.secret".Sha256())
    },

    AllowedScopes =
    {
        IdentityServerConstants.StandardScopes.OpenId,
        "invoices.api.scope",
    },
}
`

**Comment by brockallen** [comment]
Enable "AllowOfflineAccess"

**Comment by uhfath** [comment]
Sorry, but i think you missunderstood me.
What i meant was, even if i don't enable "offline access" (and i don't need it right now) it's still reported as allowed in discovery document, whereas it's not.
It's in the list of allowed scopes.

**Comment by brockallen** [comment]
Ah, I see. So yes, the token server supports it. That doesn't imply that all clients are allowed access to it. That's the case for any scope.

**Comment by uhfath** [comment]
Oh. Got it.
Thanks!
