### ISSUE TITLE
'Audience validation failed' in case ResourceName != ScopeName + unable to use multiple scopes for a single resource

### ISSUE THREAD

**Issue by Ruard** [IdentityServer/IdentityServer4#2724]
The validation should be based on the child scopes of the resource and not on the name of the resource.

### Issue / Steps to reproduce the problem

Take the sample project: 5_HybridFlowAuthenticationWithApiAccess

In the QuickstartIdentityServer project in config.cs change GetApiResources to:

```
        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                //new ApiResource("api1", "My API")
                new ApiResource
                {
                    Enabled = true,
                    Name = "api",
                    Scopes = new List<Scope> { new Scope { Name = "api1" }, new Scope { Name = "api2" } }
                }
            };
        }
```

Please note that the name of the resource is changed to 'api' and there are multiple scopes: 'api1' and 'api2', though the issue is the same when the 'api2' scope is omitted.

Start IdentityServer, Mvc Client and Api and go to http://localhost:5002/Home/CallApiUsingUserAccessToken

After login the Api is called which results in an error:

> Bearer was not authenticated. Failure message: IDX10214: Audience validati
> on failed. Audiences: 'http://localhost:5000/resources, api'. Did not match: val
> idationParameters.ValidAudience: 'api1' or validationParameters.ValidAudiences:
> 'null'.

The problem is that Audiences should not be 'api', the name of the resource, but the child scopes of api: 'api1' and 'api2'.

For a simple 1:1 configuration there is no problem as long as resource name == scope name, but I think it should be possible to configure multiple scopes per resource and use any name for the resource as the scope name is used by the resource and the scope is linked by resourceid.

**Comment by Ruard** [comment]
In addition, when Scopes are omitted and "api1" is requested:

        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource { Enabled = true, Name = "api1", DisplayName = "api" }
            };
        }

In http://localhost:5000/.well-known/openid-configuration:

> Scopes_supported: "openid", "profile", "offline_access"

And the expected result:

> Result: Sorry, there was an error : invalid_scope

But when a scope exists with another name the name of the resource is used.


And with multiple scopes:

        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource
                {
                    Enabled = true,
                    Name = "api1",
                    DisplayName = "api",
                    Scopes = new List<Scope> { new Scope { Name = "api1", DisplayName = "api1" }, new Scope { Name = "api2", DisplayName = "api2" } }
                }
            };
        }

In http://localhost:5000/.well-known/openid-configuration:

> Scopes_supported:  "openid", "profile", "api1", "api2", "offline_access"

Client is configured: 

                    AllowedScopes = 
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1",
                        "api2"
                    },

But request.ScopesRequested doesn't contain api2 and in the Consent screen only api1 (the resource) is shown.

**Comment by Ruard** [comment]
From the [docs](http://docs.identityserver.io/en/release/reference/api_resource.html#scopes):

> In the simple case an API has exactly one scope. But there are cases where you might want to sub-divide the functionality of an API, and give different clients access to different parts.

I assume resource == API in that case. Within one API I can use policies to filter the scope.

But when I want to split the resource in multiple API's then it becomes a 'logical' name to group the resources. Where each resource contains:

                .AddIdentityServerAuthentication(options =>
                {
                    options.ApiName = "api1";

In that case ApiName != ScopeName but ResourceName.

Perhaps the issue can be solved by adding an additional setting to define the implemented scopes and use that to validate the requested scope:

                .AddIdentityServerAuthentication(options =>
                {
                    options.ApiName = "api1"; // or ResourceName
                    options.AllowedScopes = "read write";

Where scopes no longer need to be globally unique, but only within the resource.

**Comment by leastprivilege** [comment]
ApiName = audience in token - this is used to validate the token at the pipeline level (or you turn it off)

Scopes would be validated at the controller/action level

**Comment by Ruard** [comment]
But is it right to compare `Audiences: 'http://localhost:5000/resources, api'`, the ApiName with `validationParameters.ValidAudience: 'api1'`, the scope name?

Is turning of the validation the only way to get past the error when using multiple scopes for one resource?

**Comment by leastprivilege** [comment]
You can have as many scopes as you like for one resource. Audience is for coarse grained checking, scopes for fine grained.

**Comment by Ruard** [comment]
Your comment made me realize my mistake. I am mixing the ApiName with the scope name.

When changing the api name (in the Api project) to the resource name then of course it works:

            services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    options.ApiName = "api";
                });

And then I can use policies to limit access using the scopes.
