### ISSUE TITLE
Logging out of hybrid flow via back-channel?

### ISSUE THREAD

**Issue by dpotoole** [IdentityServer/IdentityServer4#2726]
I'm using IdentityServer4 with an Ionic hybrid app. Logging in, I use the hybrid flow by opening an InAppBrowser (not a system browser) and redirecting the user to IdentityServer. We use LDS or Azure AD externally to authenticate. After getting the code back, I cash that in via the token endpoint to get my tokens and everything works great. Initially, I had the logout just clear my tokens from local storage which would then prompt the user to log in.

I'm testing some functionality around resource actions to limit what the user can do on the front end and I'm noticing if I sign out using the method above (or cash in a refresh token) and add the resource action, it doesn't show up in the bearer token on my next log-in or when I cash in the refresh token. If I actually sign out of IdentityServer via the browser and add the action, it does show up the next time I log in.

Since the InAppBrowser isn't using the system browser and it's a new instance every time, how exactly can I log out via the browser if it has no clue about the previous session used to log in? Is there just a way to do a back-channel log out via an endpoint similar to the token endpoint or do I have to use the endsession endpoint in the InAppBrowser?

**Comment by brockallen** [comment]
> I'm testing some functionality around resource actions to limit what the user can do on the front end and I'm noticing if I sign out using the method above (or cash in a refresh token) and add the resource action, it doesn't show up in the bearer token on my next log-in or when I cash in the refresh token. If I actually sign out of IdentityServer via the browser and add the action, it does show up the next time I log in.

Can you clarify this paragraph? I'm getting lost in what you're asking.

As for signout -- if you use an embedded browser, then there is no real notion of signout in the browser. As for your tokens, use the revocation endpoint.

**Comment by dpotoole** [comment]
Thanks for the response, Brock. 

We have some resource actions that dictate what users can do within the app (i.e. this user can submit an order while this one cannot, etc). These come back in the access token so I'm parsing the access token to determine what users can and can't do. I'm running into two scenarios that are giving me trouble:

ON TOKEN REFRESH
*User is logged into native app without a certain resource action. It's not in the list of actions parsed out of the bearer token so they can't do that certain thing. No problem.
*I'll go in and add that resource action for that user. What I would expect to happen is when my access token expires and I get a new one via a refresh token, I'd expect to see that new resource action in my list of actions in the bearer token. It is not.

ON SIGN-OUT
*Similarly, if I signed out and signed back in, I'd expect to see the new action in the list but it isn't. 

This is an Ionic app so I can run it in my browser without sideloading it onto a device. To be able to do this, I open a tab on my desktop with the Identity Server URL the embedded browser is pointed to and sign in that way. That gives me the authorization code which I can paste into the app and then the app makes the POST call to the token endpoint to get the tokens and I'm off and running. If I actually sign out in my desktop browser where I originally logged in and then sign in again, the action list is updated properly.  As far as signing out of the actual native app, I was just clearing the tokens to force a new launch of an embedded browser to sign in to IdentityServer.

**Comment by brockallen** [comment]
Unfortunately your questions border on consulting guidance, which we are happy to provide (for a fee, of course). I also think you're a bit confused about what the access token really is for -- it's not for user authorization.

In any event, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
