### ISSUE TITLE
Set a different Refresh Token Expiration for a specific user

### ISSUE THREAD

**Issue by sk3xn3t** [IdentityServer/IdentityServer4#2728]
Hello,

I have the following setup:

Client: AngularJS Web App

Server: ASP.NET Web API

In the server I use the IdentityFramework3 to authenticate users on my AngularJS Client that has the (oidc-token-manager) configured.

Currently I'm setting the AbsoluteRefreshTokenLifetime to 48 hours for my Client MyAngularJsApp like so:

```
new Client
{
	Enabled = true,
	ClientId = MyAngularJsApp.Id,
	ClientUri = MyAngularJsApp.Uri,
	ClientName = MyAngularJsApp.Name,
	Flow = Flows.Implicit,
	AllowAccessToAllScopes = true,
	IdentityTokenLifetime = 300,
	AccessTokenLifetime = 3600,
	RefreshTokenExpiration = TokenExpiration.Absolute,
	RefreshTokenUsage = TokenUsage.ReUse,
	AbsoluteRefreshTokenLifetime = TimeSpan.FromDays(2).Seconds,
	RequireConsent = false,
	RedirectUris = new List<string>
	{
		MyAngularJsApp.Uri + "/assets/idSrv/callback.html",
		MyAngularJsApp.Uri + "/assets/idSrv/silentrefreshframe.html"
	},
	PostLogoutRedirectUris = new List<string>
	{
		MyAngularJsApp.Uri + "/index.html"
	}
},
```

There is one specific user that will log into my client that I want to set his Refresh Token to last 100 days so that the user does not have to Authenticate in 100 days, the reason I need this specific user to have 100 days without needing to log in is because this user will be used to display a specific part of the app on a big monitor, it'll remain static for 100 days

`AbsoluteRefreshTokenLifetime = TimeSpan.FromDays(100).Seconds,`

  How do I make it so that only this user has this refresh token lifetime?

**Comment by brockallen** [comment]
IdentityServer does not implement the dynamic client registration spec -- there's an long discuss on an issue from a while ago about this topic.
