### ISSUE TITLE
How to capture the access token from an external provider, for subsequent use with that provider's API

### ISSUE THREAD

**Issue by solirobi** [IdentityServer/IdentityServer4#2732]
We are integrating with a number of external providers, such as Twitter, Facebook, & Google.   Beyond simply using those providers to authenticate, we need to be able to access the providers' APIs to do things on the authenticated user's behalf.  In order to do this, we need to capture the access token issued by these providers during the authentication sequence.   How is this done?

**Comment by brockallen** [comment]
> How is this done?

No differently than if you were not using identityServer.

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
