### ISSUE TITLE
Updates samples PR

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#2734]
I have created an ASP.NET Core 2.2 example, ASP.NET Core OpenID Connect Back-Channel Logout for Hybrid Clients from the IdentityServer4.Samples.

https://github.com/damienbod/AspNetCoreBackChannelLogout

If you want, I could create a PR to update the client samples with the following:

- ASP.NET Core 2.2
- Bootstrap 4
- HTTPS

https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Clients

If you are interested, I will do a PR

Greetings Damien

**Comment by brockallen** [comment]
Not at this point. We'll update our samples after we release 2.3. And the official templates will most likely be from Microsoft.
