### ISSUE TITLE
IdentityServerAuthenticationService.AugmentMissingClaims variation

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2736]
[source](https://github.com/IdentityServer/IdentityServer4/blob/e14a1e9b2dfd4173bedb3e570ac5c888927ccb22/src/Hosting/IdentityServerAuthenticationService.cs)  

change
```
 var amr = identity.FindFirst(ClaimTypes.AuthenticationMethod);
if (amr != null &&
    identity.FindFirst(JwtClaimTypes.IdentityProvider) == null &&
    identity.FindFirst(JwtClaimTypes.AuthenticationMethod) == null)
{
    _logger.LogDebug("Removing amr claim with value: {value}", amr.Value);
    identity.RemoveClaim(amr);

    _logger.LogDebug("Adding idp claim with value: {value}", amr.Value);
    identity.AddClaim(new Claim(JwtClaimTypes.IdentityProvider, amr.Value));

    _logger.LogDebug("Adding amr claim with value: {value}", Constants.ExternalAuthenticationMethod);
    identity.AddClaim(new Claim(JwtClaimTypes.AuthenticationMethod, Constants.ExternalAuthenticationMethod));
}
```
to
```
 var amr = identity.FindFirst(ClaimTypes.AuthenticationMethod);
if (amr != null &&
    identity.FindFirst(JwtClaimTypes.IdentityProvider) == null )
{
    _logger.LogDebug("Removing amr claim with value: {value}", amr.Value);
    identity.RemoveClaim(amr);

    _logger.LogDebug("Adding idp claim with value: {value}", amr.Value);
    identity.AddClaim(new Claim(JwtClaimTypes.IdentityProvider, amr.Value));

    _logger.LogDebug("Adding amr claim with value: {value}", Constants.ExternalAuthenticationMethod);
    identity.AddClaim(new Claim(JwtClaimTypes.AuthenticationMethod, Constants.ExternalAuthenticationMethod));
}
```
I created an IDP that does the following;
1. Requires an initial login by a support agent.  This basically drops a cookie so I can track the agent
2. The real login is a screen that asks for the user's email, and a bunch of challenge questions.  This is all done over the phone.

My first cut of the final id_token looks something like this [id_token](https://jwt.io/#debugger-io?token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjAzM2ZkZjQ2YjZkODdkOThmNzIzY2U4YTE0MzBiMjBhIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MzkyOTI0NTIsImV4cCI6MTUzOTI5Mjc1MiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMTgiLCJhdWQiOiJmZWRlcmF0ZWQtaWRwIiwibm9uY2UiOiI2MzY3NDg4OTIzNTE2MTQ1MjguTkRaaFpUVXdNbU10WWpObFpDMDBNekkyTFdKaU1qUXRaVGd4TWpNNE1UVmlPV1F3WXpZeE5XVm1ObUV0TUdKall5MDBOalZsTFRsaVpHSXRaRFV3TmpNeFpEUmlORFk1IiwiaWF0IjoxNTM5MjkyNDUyLCJzaWQiOiJjZDEyODI3Y2I2NjUxN2IwZmExMjI0MzkwY2U2M2VkZiIsInN1YiI6IjE1MDUxZGFmLTE2NTQtNDJmOS1hODNkLWUyY2ZjZjE1MjY3NyIsImF1dGhfdGltZSI6MTUzOTI5MjQ1MiwiaWRwIjoiSWRlbnRpdHkuQXBwbGljYXRpb24iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0ZWRAdGVkLmNvbSIsIm5hbWUiOiJ0ZWRAdGVkLmNvbSIsImFnZW50OnVzZXJuYW1lIjoiYWdlbnQwQHN1cHBvcnR0ZWNoLmNvbSIsImFnZW50OmNoYWxsZW5nZVF1ZXN0aW9uIjpbIkZpcnN0IENhciIsIkZpcnN0IEhvdXNlIiwiRmlyc3QgUGV0Il0sInJvbGUiOiJhZ2VudF9wcm94eSIsImFtciI6WyJleHRlcm5hbCJdfQ.Q786finANflngn1SM9d_Pzaa23vqqgNGCKXlY_Ac1Um-p1IYDUL_71OpUBDbsiR0rTp8wCzhuhHiNeMzc-X86Q3Isn0GUHroTSI2T_-uwT6nVGlgzGO_JpfCV7qrd-ra4YED5rO9PeNFk_s7XAD0ipZyHlNrs2_JX4rwtd-qggcR0OmbppBEF2GJrWWR-iCF5lcdixgdnF4q6PRFLOJZ8wjvKRehe3qeI75iFv0jsQ0tKSv-3-D0Csv9zDW5llNQ_bsYxVj4JbWh7JqrlCeoQVlnMeqrIjSI864NK737rbZw3qk7KHtSuPzq5ygZd7eeNic7QmE4MBHM12YbHOCFqQ)  where I put in how the user got authenticated as claims.   

Those claims really belong as amr values as it tells the final consumer of the id_token the "How" this user got authenticated.

My second cut was to add all that as "amr"
```
"agent:username": "agent0@supporttech.com",
  "agent:challengeQuestion": [
    "First Car",
    "First House",
    "First Pet"
  ],
```
vs.
```
  "amr": [
    "agent:userName:agent0@supporttech.com",
    "challenge:fullSSN"
    "challenge:firstHouse",
    "challeng:firstPet"
  ],
```
I did this before your AugmentClaims was called.

From the looks of that statement in AugmentClaims its primary goal is to turn 
ClaimTypes.AuthenticationMethod into JwtClaimTypes.IdentityProvider

The existance of  JwtClaimTypes.AuthenticationMethod should not stop that from happening.

**Comment by brockallen** [comment]
I guess I'm not following. That code block is something specific for the vanilla ASP.NET Identity claims issuance code. If you need to tinker around at that level, I'd encourage you to change/control what claims are being issued in the cookie at IdentityServer. If you're using ASP.NET Identity, then I'd suggest overriding the user claims principal factory: https://github.com/aspnet/Identity/blob/master/src/Core/IUserClaimsPrincipalFactory.cs#L13

**Comment by ghstahl** [comment]
its been a while since I changed that code in my copy of IdentityServer4.  Let me put it back and refamiliarize myself with the problem.  My recollection is that identity.FindFirst(JwtClaimTypes.AuthenticationMethod) == null broke what I was trying to do and then further investigation pointed out that that particular check wasn't necessary. 

I will write a better issue statement.

**Comment by ghstahl** [comment]
Apparently, I can't reproduce the problem.  Just went away, everything works just fine with 2.3.0. I am just going to go ahead and close this, and we can all pretend this never happened.  Happy Thanksgiving!
