### ISSUE TITLE
How to return 401 instead 302 in a api project?

### ISSUE THREAD

**Issue by rocketRobin** [IdentityServer/IdentityServer4#2738]
the code is:
```
  .AddIdentityServerAuthentication(options =>
            {
                options.Authority = Configuration["SsoServerUrl"];
                options.RequireHttpsMetadata = false;
                options.ApiName = "gosg-sso-admin-api";
               
            });
```

when  authentication failed ，it's return 302 ,but this is an ajax call, I need to return a 401 result ,I can,t find out any way to implement it .

#505 is out of date ,its not work, I use dot net core 2.1.5 and ID4 .

please help me ,  thanks very very very much!

**Comment by Goxiaoy** [comment]
`//Configure this after identityServer 
            services.ConfigureApplicationCookie(options =>
            {
                options.Events.OnRedirectToAccessDenied =
                    options.Events.OnRedirectToLogin = c =>
                    {
                        if (c.Request.Path.StartsWithSegments("/api")
                            && c.Response.StatusCode == StatusCodes.Status200OK)
                        {
                            c.Response.Headers["Location"] = c.RedirectUri;
                            c.Response.StatusCode = StatusCodes.Status401Unauthorized;
                            return Task.FromResult<object>(null);
                        }
                        c.Response.Redirect(c.RedirectUri);
                        return Task.FromResult<object>(null);
                    };
            });`

**Comment by Goxiaoy** [comment]
~~~
//Configure this after identityServer 
            services.ConfigureApplicationCookie(options =>
            {
                options.Events.OnRedirectToAccessDenied =
                    options.Events.OnRedirectToLogin = c =>
                    {
                        if (c.Request.Path.StartsWithSegments("/api")
                            && c.Response.StatusCode == StatusCodes.Status200OK)
                        {
                            c.Response.Headers["Location"] = c.RedirectUri;
                            c.Response.StatusCode = StatusCodes.Status401Unauthorized;
                            return Task.FromResult<object>(null);
                        }
                        c.Response.Redirect(c.RedirectUri);
                        return Task.FromResult<object>(null);
                    };
            });
~~~
