### ISSUE TITLE
Constants no longer public accessible

### ISSUE THREAD

**Issue by ravetroll** [IdentityServer/IdentityServer4#274]
I was using Constants to get Reflection of SecretTypes and GrantTypes. Why is it now internal?

**Comment by leastprivilege** [comment]
Ah - that's an oversight - we'll add it back

**Comment by RolandGuijt** [comment]
You can use IdentityServerConstants instead.

**Comment by ravetroll** [comment]
They are not all in IdentityServerConstants.

**Comment by leastprivilege** [comment]
fixed in RC2 pre-release on the dev feed.
