### ISSUE TITLE
Querystring in IdentityServer4

### ISSUE THREAD

**Issue by hgmauri** [IdentityServer/IdentityServer4#2740]
I am using .NET Core 2.1 and i have the following situation:

- The user enters the page with a querystring, for example: **https://app.test.com/index.html?name=jhon&age=20&city=vitoria**

- The user is not logged in, then is redirected to the user login screen

- Once logged in, the user is redirected to the main page of the "app.test" application configured on the IdentityServer which is https://app.test.com/index.html

My question is, how do I in IdentityServer4 so that after the user is logged in, he is redirected to the main page with the **querystring**? It is possible?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
