### ISSUE TITLE
Event fires twice.

### ISSUE THREAD

**Issue by VereshchaginKonstantin** [IdentityServer/IdentityServer4#2743]
### Issue / Steps to reproduce the problem

Create IEventSink implementation with logging serialized Event object in PersistAsync method. 
When the token is received, the event fires twice. There is only one difference - "DisplayName" field. In one case it is null, in other is login.

### Relevant parts of the log file

```
[14:32:54.3254 INF] Credentials validated for username: "administration" Properties {SourceContext: "IdentityServer4.AspNetIdentity.ResourceOwnerPasswordValidator", RequestId: "0HLHORCVRSVVE:00000001", RequestPath: "/connect/token", Application: "IdentityServer"}
**[14:32:54.3254 INF]** {"Name":"User Login Success","Category":"Authentication","EventType":1,"Id":1000,"Username":"administration","Provider":null,"ProviderUserId":null,"SubjectId":"442aecfa-89c9-4be6-b5e8-e855008f906f","DisplayName":"administration","Endpoint":"Token","Message":null,"ActivityId":"0HLHORCVRSVVE:00000001","TimeStamp":"2018-10-23T11:32:54Z","ProcessId":16188,"LocalIpAddress":"127.0.0.1:7000","RemoteIpAddress":"127.0.0.1"} Properties {RequestId: "0HLHORCVRSVVE:00000001", RequestPath: "/connect/token", Application: "IdentityServer"}
**[14:32:54.3254 INF]** {"Name":"User Login Success","Category":"Authentication","EventType":1,"Id":1000,"Username":"administration","Provider":null,"ProviderUserId":null,"SubjectId":"442aecfa-89c9-4be6-b5e8-e855008f906f","DisplayName":null,"Endpoint":"Token","Message":null,"ActivityId":"0HLHORCVRSVVE:00000001","TimeStamp":"2018-10-23T11:32:54Z","ProcessId":16188,"LocalIpAddress":"127.0.0.1:7000","RemoteIpAddress":"127.0.0.1"} Properties {RequestId: "0HLHORCVRSVVE:00000001", RequestPath: "/connect/token", Application: "IdentityServer"}
[14:32:54.3254 INF] Token request validation success
```

**Comment by ActualAl** [comment]
This may or may not be related to an issue I'm seeing on our implementation of ID4. It happens when we issue a POST request to connect/token

Two methods in the ResourceStore get called twice which results in us calling our DB twice with duplicated queries.

Could this be a related issue or could be we doing something fundamentally wrong with our configuration of the server ?

In IoC we wire up our own ResourceStore.
 services
                .AddTransient<IdentityServer4.Stores.IResourceStore, Application.IdentityServer.Stores.ResourceStore>();

**Comment by fillipetardelli** [comment]
I faced this problem too while implementing a last login date log.

I did a work-around by validating the `DisplayName` like @VereshchaginKonstantin said. So let me know when you guys push some update about this in order that I can adjust my code.

Thanks

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by fcavaco** [comment]
hello, I am still facing this issue, this event does fire twice in my event sink implementation ... will try to apply the displayname constrain as suggested above...
