### ISSUE TITLE
OpenId UI authentication problems netcore 2.1

### ISSUE THREAD

**Issue by fspcons** [IdentityServer/IdentityServer4#2744]
Hey guys!

I recently started to update my identity micro-service to netcore 2.1 and I had some problems doing so. The MS runs authentication both by JWT and Cookies. The JWT part seems to be working just fine, the Cookie part however seems to have a small bug. Here's the scenario, i have a main API that contains the identityserver and a UI with an admin portal. When i attempt to login the UI i get redirected to the login page. From what i could understand during the extensive debugging is that the login process consists in two requests:

- First my UI calls my custom /Login endpoint, in wich i call the HttpContext Singin method and the idserver outputs on the console that the authentication was successful. 

- Right after that, from the return url, the authorize/callback endpoint is called (i think the issue is here) and it seems that in this step the identity server fails to find the recently created session and assumes the is no logged in user and then redirects to the login page.

I hope someone can help me understand where i'm failing or, if it is indeed an issue, that it could be fixed in the next release.

**Edit: I'm currently using the latest nuget version for IdentitySrver4 2.2.0 and also the latest nuget version for IdentityServer4.AcessTokenValidation 2.6.0**

### Issue / Steps to reproduce the problem

Here's my configuration:

**Identity API**

ConfigureServices       

               services.AddResponseCaching(); 
               services.AddMvcCore()                
                .AddVersionedApiExplorer(options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                });

                services.AddMvc(options =>
                {
                    options.Filters.Add(typeof(LogActionFilter));
                    options.Filters.Add(typeof(LogAuthorizationFilter));
                    options.Filters.Add(typeof(ValidateModelSerializationFilter));
                })                
                .AddJsonOptions(options =>
                {
                    options.SerializerSettings.Formatting = Formatting.None;
                    options.SerializerSettings.ContractResolver = hashResolver;
                });

                services.AddApiVersioning(o =>
                {
                    o.AssumeDefaultVersionWhenUnspecified = true;
                    o.DefaultApiVersion = new ApiVersion(1, 0);
                });
            services.AddCors();
            services.AddHttpContextAccessor();
              services.AddScoped(provider =>
                    {
                        var context = provider.GetService<IHttpContextAccessor>();

                        return context?.HttpContext != null ? new AuthInfo(context.HttpContext.User) : new AuthInfo(new ClaimsPrincipal());
                    });
            services.AddMappers();
            services.AddBaseServices();
            var config = IDSHelper.GetIDSOptions();

            services.AddIdentityServer(options =>
            {
                options.IssuerUri = config.Authority;
                options.PublicOrigin = config.Authority;
            })
            .AddSecretParser<JwtBearerClientAssertionSecretParser>()
            .AddSecretValidator<PrivateKeyJwtSecretValidator>()
            .AddConfigurationStore(isProduction)
            .AddOperationalStore();

            services.AddAuthentication()
            .AddIdentityServerAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme,  options =>
            {
                options.Authority = config.Authority;
                options.RequireHttpsMetadata = isProduction;
                options.ApiName = config.ApiName;
                options.ApiSecret = config.ApiSecret;
                options.SaveToken = true;
            });

ApplicationBuilder

             app.UseMiddleware<LogRequestResponseMiddleware>();
             var pathBase = GetPathBase();
                if (!string.IsNullOrWhiteSpace(pathBase))
                {
                    app.UsePathBase(pathBase);
                }
             app.UseCors(options =>
            {
                options.AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials();
            });
            app.UseMiddleware<HttpsMiddleware>()
                .UseMiddleware<HstsMiddleware>()
                .UseMiddleware<HttpExceptionMiddleware>()
                .UseStaticFiles()
                .UseMvcWithDefaultRoute();

            app.UseMiddleware<ConnectTokenErrorMiddleware>();

            if (env.IsDevelopment())
            {
                app.UseIdentityServer();
            }
            else
            {
                var config = IDSHelper.GetIDSOptions();

                var newUri = new Uri(config.Authority);

                var baseUrl = string.Format("{0}://{1}", "https", newUri.Host);

                app.UseMiddleware<PublicFacingUrlMiddleware>(baseUrl);
                app.ConfigureCors();
                app.UseMiddleware<IdentityServerMiddleware>();
            }

**UI**

ConfigureServices

               services.AddResponseCaching(); 
               services.AddMvcCore()                
                .AddVersionedApiExplorer(options =>
                {
                    options.GroupNameFormat = "'v'VVV";
                    options.SubstituteApiVersionInUrl = true;
                });

                services.AddMvc(options =>
                {
                    options.Filters.Add(typeof(LogActionFilter));
                    options.Filters.Add(typeof(LogAuthorizationFilter));
                    options.Filters.Add(typeof(ValidateModelSerializationFilter));
                })                
                .AddJsonOptions(options =>
                {
                    options.SerializerSettings.Formatting = Formatting.None;
                    options.SerializerSettings.ContractResolver = hashResolver;
                });

                services.AddApiVersioning(o =>
                {
                    o.AssumeDefaultVersionWhenUnspecified = true;
                    o.DefaultApiVersion = new ApiVersion(1, 0);
                });
            services.AddCors();
            
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
            .AddCookie(options =>
            {
                options.Cookie.Name = "access_token";
            })
            .AddOpenIdConnect(options =>
            {
                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.Authority = jwtPath;
                options.RequireHttpsMetadata = isProduction;
                options.ClientId = GetEnvironmentVariable("client");
                options.ClientSecret =  GetEnvironmentVariable("secrets");
                options.ResponseType = "code id_token";

                var scopesText = GetEnvironmentVariable("scopes");

                var scopes = scopesText != null ? scopesText.Split(";") : new string[0];

                foreach (var item in scopes)
                {
                    options.Scope.Add(item);
                }

                options.GetClaimsFromUserInfoEndpoint = true;
                options.SaveTokens = true;

                options.TokenValidationParameters = new TokenValidationParameters()
                {
                    IssuerSigningKey = signingConfigurations.Key,
                    ValidAudiences = tokenConfigurations.Audience,
                    ValidIssuer = tokenConfigurations.Issuer,
                    ValidateIssuerSigningKey = true,
                    ValidateLifetime = true,
                    ValidateAudience = true,
                    NameClaimType = "name",
                    RoleClaimType = "role",
                    ClockSkew = TimeSpan.Zero
                };

                if (isProduction)
                {
                    options.Events.OnRedirectToIdentityProvider = context =>
                    {
                        var builder = new UriBuilder(context.ProtocolMessage.RedirectUri)
                        {
                            Scheme = "https"
                        };

                        context.ProtocolMessage.RedirectUri = builder.ToString();
                        context.ProtocolMessage.RedirectUri = context.ProtocolMessage.RedirectUri.Replace(":80", "");
                        return Task.FromResult(0);
                    };
                    options.Events.OnRemoteFailure = context =>
                    {
                        Console.WriteLine("Test Error: " + context.Failure.Message + "|" +
                                            context.Failure.Source + "|" + context.Failure.StackTrace);

                        return Task.FromResult(0);

                    };
                }
            });

            services.AddHttpContextAccessor();
              services.AddScoped(provider =>
                    {
                        var context = provider.GetService<IHttpContextAccessor>();

                        return context?.HttpContext != null ? new AuthInfo(context.HttpContext.User) : new AuthInfo(new ClaimsPrincipal());
                    });
            services.AddMappers();
            services.AddBaseServices();

ApplicationBuilder

             app.UseMiddleware<LogRequestResponseMiddleware>();
             var pathBase = GetPathBase();
                if (!string.IsNullOrWhiteSpace(pathBase))
                {
                    app.UsePathBase(pathBase);
                }
            app.UseAuthentication();           

            app.UseCors(options =>
            {
                options.AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader()
                .AllowCredentials();
            });     
            app.UseMiddleware<HttpsMiddleware>()
                .UseMiddleware<HstsMiddleware>()
                .UseMiddleware<HttpExceptionMiddleware>()
                .UseStaticFiles()
                .UseMvcWithDefaultRoute();       

### Relevant parts of the log file

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:6001/accounts/v1/Account/Login? ...
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Login", controller = "Account"}. Executing action Accounts.API.Default.Controllers.Web.AccountController.Login (Accounts.API.Default)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Accounts.API.Default.Controllers.Web.AccountController.Login (Accounts.API.Default) with arguments (Accounts.Application.Views.Models.Default.LoginViewModel) - Validation state: Valid
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[10]
      >>>>> AuthenticationScheme: idsrv signed in. <<<<<
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Accounts.API.Default.Controllers.Web.AccountController.Login (Accounts.API.Default), returned result Microsoft.AspNetCore.Mvc.JsonResult in 1382.65ms.
info: Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor[1]
      Executing JsonResult, writing value of type '<>f__AnonymousType1`4[[System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Accounts.Application.Contracts.PostPasswordVirtualKeyboardAsyncResponse, Accounts.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Accounts.API.Default.Controllers.Web.AccountController.Login (Accounts.API.Default) in 1397.9593ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1411.9026ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:6001/connect/authorize/callback?...&x-client-SKU=ID_NETSTANDARD1_4&x-client-ver=5.2.0.0
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint for /connect/authorize/callback
info: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint[0]
      ValidatedAuthorizeRequest
      {
        "ClientId": "XXXXXX",
        "ClientName": "XXXXXXX",
        "RedirectUri": "http://localhost:5000/signin-oidc",
        "AllowedRedirectUris": [          
          "http://localhost:6002/signin-oidc",
          "http://localhost:6002/portal/v1/signin-oidc",
          "http://localhost:5000/signin-oidc",
          "http://localhost:5000/portal/v1/signin-oidc"
        ],
        "SubjectId": "anonymous",
        "ResponseType": "code id_token",
        "ResponseMode": "form_post",
        "GrantType": "hybrid",
        "RequestedScopes": "xxxxxxxxx",
        "State": "CfDJ8DzqeEYLLHFDvoLvFEkLRtrjMuwy4OON_0tVlhwYihj3leO_R038lsgEl3Hz_KdEqP2GurI9WTmx0R0CcaO3k6Txszp05gfuoXDm7kk_i6ecPUob6nNygr-F5O8R6fHY4nhg4nXc0X3VQJB2pR4sYxSZ0U520ABNGFBQnlFicIDwDYrnVIfwASacHcpcImJPC-dAgAxw0edLGjm-YhKt-6W1EV8pWdtusuCPA96M2RcoAwshVqeWIAjtDeYFavMEbeklsVFdFZn1M8MxMzHnbZK18Zz4IiyQd1kFuv6iOGjHZVQ7auHhQB54iCEXAnibgmDPG5JVYgl-i466EpmEGF8",
        "Nonce": "636759086523404179.Nzk0ZjQ0NzQtYzYxMy00ODI5LWJiNmEtMzhlNWI5ZThiYzBmZGIxMzdkNzctNWVkYS00MzM1LWEyMzEtNWU2NWJjZjhmZGQy",
        "Raw": {
          "client_id": "XXXX",
          "redirect_uri": "http://localhost:5000/signin-oidc",
          "response_type": "code id_token",
          "scope": "xxxxxxxxxxxx",
          "response_mode": "form_post",
          "nonce": "636759086523404179.Nzk0ZjQ0NzQtYzYxMy00ODI5LWJiNmEtMzhlNWI5ZThiYzBmZGIxMzdkNzctNWVkYS00MzM1LWEyMzEtNWU2NWJjZjhmZGQy",
          "state": "CfDJ8DzqeEYLLHFDvoLvFEkLRtrjMuwy4OON_0tVlhwYihj3leO_R038lsgEl3Hz_KdEqP2GurI9WTmx0R0CcaO3k6Txszp05gfuoXDm7kk_i6ecPUob6nNygr-F5O8R6fHY4nhg4nXc0X3VQJB2pR4sYxSZ0U520ABNGFBQnlFicIDwDYrnVIfwASacHcpcImJPC-dAgAxw0edLGjm-YhKt-6W1EV8pWdtusuCPA96M2RcoAwshVqeWIAjtDeYFavMEbeklsVFdFZn1M8MxMzHnbZK18Zz4IiyQd1kFuv6iOGjHZVQ7auHhQB54iCEXAnibgmDPG5JVYgl-i466EpmEGF8",
          "x-client-SKU": "ID_NETSTANDARD1_4",
          "x-client-ver": "5.2.0.0"
        }
      }
info: IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator[0]
      >>>>>> Showing login: User is not authenticated <<<<<<
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 944.3028ms 302
```

**Comment by jamieide** [comment]
I'm new to Identity Server and you obviously know it well, but you don't show you call to SignInAsync. This works for me in .NET Core:

            var scheme = await _authenticationSchemeProvider.GetDefaultAuthenticateSchemeAsync();
            await _httpContextAccessor.HttpContext.SignInAsync(scheme.Name, principal);

where _authenticationSchemeProvider is IAuthenticationSchemeProvider injected into a service.

**Comment by fspcons** [comment]
Sorry, that is a part of my /Login endpoint:
                    
                  ... login logic ...
                   await HttpContext.SignInAsync(validResult.UserId, validResult.Name, props);

                    return Json(new
            {
                ReturnUrl = model.ReturnUrl,
                Success = validResult.Success,
                Result = validResult
            });

**Comment by fspcons** [comment]
After some tests with my old 2.0 service i noticed the problem is the UI. Still can't figure out exactly why, but using my new 2.1 API with my old 2.0 UI the authentication proceeds just fine. The other way around i get the same result i described initially. So it must be in my new 2.1 UI ... Any help is deeply appreciated :)

**Comment by fspcons** [comment]
Finally figured it out, it was a problem in my authority configuration. Thanks anyway!
