### ISSUE TITLE
identityuser docker ioexception: idx20804: unable to retrieve document from: 'http://localhost:8080/.well-known/openid-configuration'.

### ISSUE THREAD

**Issue by doorwaaar** [IdentityServer/IdentityServer4#2746]
Hi, I have this error when using docker and identityserver4 (asp.net core 2.1)

 ioexception: idx20804: unable to retrieve document from: 'http://localhost:8080/.well-known/openid-configuration'.

But if I hit  http://localhost:8080/.well-known/openid-configuration   from the browser it works fine.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
