### ISSUE TITLE
Question - Is it possible to migrate the data in PersistedGrants table to keep the existing user session active?

### ISSUE THREAD

**Issue by pmehta1682** [IdentityServer/IdentityServer4#2747]
We are in the middle of an infrastructure change where we are upgrading to IdentityServer4 and moving to a CICD pipeline with a new database. With this change, we would like to migrate the data in PersistedGrants table from the old environment to the new environment so that users do not get logged out and keep their existing session. So my question is 

1. Is it possible to do what we are trying to migrate the data in PersistedGrants table?  
2. If yes, what is the best way to do that? We already tested this in our test env and we were not able to keep the existing user sessions by just migrating the data over
3.  If no, is there a way to keep the user sessions active in a situation like ours?

**Comment by brockallen** [comment]
We don't provide anything built in for that in the OSS. You could possibly contact us for consulting to provide it as a paid project.
