### ISSUE TITLE
Support for Azure AD V 2.0

### ISSUE THREAD

**Issue by skvsree** [IdentityServer/IdentityServer4#2748]
Is the support for Azure AD version 2.0 in place.  Refer link below .
[https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-protocols-oidc)

The sample from below link does not seem to work for multi-tenant, personal emails
[https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow](https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by brockallen** [comment]
Fixed, thanks.
