### ISSUE TITLE
Refresh token throw invalid grant error in production environment while it's working fine locally

### ISSUE THREAD

**Issue by arunkr1492** [IdentityServer/IdentityServer4#2753]
I am using resource owner password flow and i got successfully access token and refresh token and i did not persist any token in database and everything works fine locally.
But when i deploy identity server in production refresh token is not working as expected.
i have set access token expiry time 20 minutes and refresh token expiry time 7 days.

if i refresh access token within 20 minutes or before expiry of access token then refresh token refresh access token and work as expected but after expiry of access token refresh token does not refresh access token and throw invalid_grant error.

As i did not save refresh token in database and i searched on google but answers are confusion. 
As identity document stated we can persist refresh token, authorization code if we want.

So can anyone tell me :

Do i need to store refresh token? 
while it is working fine locally without storing .

or something else i need to look.

Thank you.
 
Your response is valuable for me.

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/release/topics/deployment.html

**Comment by arunkr1492** [comment]
Thank you .

May I know is it mendatory to implement operational DB or is there any another option as I don't want to persist refresh token or access token ?

**Comment by brockallen** [comment]
Then don't use them.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
