### ISSUE TITLE
understanding DB hash password 

### ISSUE THREAD

**Issue by arimaze** [IdentityServer/IdentityServer4#2755]
Hi all,

Is it possible to know how createsync() method works to insert a hash password into database.
Does it hash only password or concatenate with other fields.

I would like to insert directly a password using sql update query but i dont know how to create it.

For exemple if i generate a password hash with this tool it doesn't work.
https://passwordsgenerator.net/sha256-hash-generator/

Thank you,

Best regards

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
