### ISSUE TITLE
The Samples don't work in Firefox 63

### ISSUE THREAD

**Issue by theCuriousOne** [IdentityServer/IdentityServer4#2759]
After login the to one of the IdentityServer4 implementations, after the login it does not redirect to the redirectUrl (probably because https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302 )

**Comment by theCuriousOne** [comment]
Ways to reproduce:

1. Downloading the IdentityServer4.Samples (version 2.0)
2. Open some of the QuickStart solutions (for example 7_JavascriptClient) (using VS 2018 18.7 Community edition)
3. Set start multiple projects (the QuickstartIdentityServer have to be one of them and let say the MvcClient)
4. Start the debug process using Firefox (version 63 (64-bit) ) and try to log in MVCClient with some of the predefined users (ex. bob/password)
5. Firefox won't redirect after the login - it stays at this url: http://localhost:5000/account/login?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dmvc%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A5002%252Fsignin-oidc%26response_type%3Dcode%2520id_token%26scope%3Dopenid%2520profile%2520api1%2520offline_access%26response_mode%3Dform_post%26nonce%3D636770137735334069.MGVjM2VlZTYtZDc2MC00N2MxLThiMGEtNjQzOWVmOTNiNjcwYTE3OGFmY2YtMGYzMC00ZTlhLWJlMjEtMDY0NGQ1YzhkZjJm%26state%3DCfDJ8J65O7MO3GJFjzruowJX0NtlJ1xYaKMdTUYkOJLSW8XYkelfcosD80-snehck5zwmWIlHUh8jhzp-cMb__aPV_JHKu9gjB6qIXEAQcOue9tl78nEYFBl67CjUI1e_gn2Tffo6jEkao_1GHCRMTG92k6a7q-NWSPVkUVcWhdY9a8fe_sUSRMoC_dQGGbvP-Xm_W0CVLUaHwD5p1cD0fPeJzY9feUrMGrnteqy9nGbiPXizeQl4x5zgb-T2WfhFybL0vtivNyOdNosURxqA2zadSddGPSlzlLdETP5d08haaVOP8IfvJFKLLxiFelwKQn3AYPOBhZqxLJxaCD-dPRkurc%26x-client-SKU%3DID_NET%26x-client-ver%3D2.1.4.0


The network monitor in the debugger shows two 302  requests, one 302 POST (http://localhost:5000/account/login?***) and the second one 302 GET (http://localhost:5000/connect/authorize/callback?***).
And Firefox does not recommend 302 status for POST methods (the link in the first comment)

**Comment by brockallen** [comment]
Sounds like FF's new CORS issue.

**Comment by theCuriousOne** [comment]
@brockallen No. The target Framowork is set to .Net Core 2.1 and the nuget packages are all the latest (at the moment of writing this) - 
`IdenityServer4 v2.2.0   |  
MicrosoftAspNetCore.All v2.1.5  |  
Microsoft.NetCore.App v2.1.0`

**Comment by brockallen** [comment]
Ok, I'll try to repo.

**Comment by brockallen** [comment]
I just tested out latest IdentityServer (netcoreapp2.1), and the latest Client (JsOidc calling the API) - both from the dev branch. I used Firefox 63.0.1 (64-bit) on Windows and it's working for me. 

I think I will need more info to reproduce before I can try to fix anything.

**Comment by theCuriousOne** [comment]
@brockallen  Sorry for wasting your time (but maybe useful for someone else). I should have written sooner. It turns out the issue was with old cookies. I was playing around with the the app and turned off debugging on some (probably crucial) breakpoints. And since the app did not finish the flow in right order I had a lot of cookies (since the samples and my code were on the same url and port). Once I delete all from storage it was ok. I will try to reproduce it just (when I have some time) just in case maybe shows a hidden error.

Thank you for you time and your code :)
