### ISSUE TITLE
Manual validation at the time of refreshing a token

### ISSUE THREAD

**Issue by maganuk** [IdentityServer/IdentityServer4#276]
Hi,

So... my user is signed in and has a valid token. Now, at the time when he comes in to refresh the token I'd like to manually do some checks and then decide if I'd like to allow the refresh or not.

How can I implement this in IdentityServer4?

Thanks
Best Regards

Vishal

**Comment by leastprivilege** [comment]
Try implementing `ICustomTokenRequestValidator`

**Comment by maganuk** [comment]
Thanks for the lead. I've implemented the Validator. How can I get identityserver4 to use it? I cant find any samples or issues around it.

Thanks

**Comment by leastprivilege** [comment]
Register it with the aspnet DI system.

**Comment by maganuk** [comment]
Already tried that:
services.AddTransient<ICustomTokenRequestValidator, CustomTokenRequestValidator>();

still doesn't get called.

**Comment by maganuk** [comment]
BTW I'm using the implicit flow and I'm hoping this breakpoint should be hit every time the app does a silent refresh and gets a new token.

Is this correct?

**Comment by leastprivilege** [comment]
You said refresh token - that's a feature of OAuth's token endpoint.

"Silent renews" works completely different and is using the authorization endpoint. We are not done yet with the redesign of the authorization pipeline.

There is something similar (IIRC `ICustomAuthorizationRequestValidator`) which might work for you  - or not.

Please describe your scenario so we can get a better understanding.

**Comment by maganuk** [comment]
My bad, It indeed is a silent renewal and not a refresh token. Here's describing my exact issue:

I have two apps (an administration spa and a customer facing MVC app) which are both using a common user database. I have managed to implement two separate login pages for each of the apps based on the client Id from the IdentityServerInteraction service. So, users are allowed to login Into either of the apps based on the their role, which is working fine. Both the apps use a common web api as their data source. The problem is that since the user may be perpetually logged into the spa and the token to access the api is continuously silently renewed , at some point the administrator may decide to kick off the user from the required role so that he is unable to access the administration app. At this point I would like for the user to be logged out from the administration app and the silent renewal should fail.

So I would like to do a role check every time their is a silent renewal. 

Now you mentioned that you are still not done redesigning the auth pipeline. Do you expect something will be made available where I can do these checks in the final version of identity server 4 or my only option is to use the iCustomAuthorizationRequestValidator to do this check?

Thanks
Best Regards

Vishal

**Comment by leastprivilege** [comment]
Try the `ICustomAuthorizationRequestValidator` and see if it works for you. If not tell use what's missing.

**Comment by maganuk** [comment]
It works fine... There's nothing missing. Though it would be nice if there was something which tells me if it is an initial authorization request or a silent renew request.

**Comment by leastprivilege** [comment]
You can tell by the prompt=none parameter.

**Comment by maganuk** [comment]
do you mean request.promptmode? that is always null for me.

**Comment by leastprivilege** [comment]
hm - that might be a bug @brockallen 

But as I said - this is still an open issue - see https://github.com/IdentityServer/IdentityServer4/issues/166

**Comment by brockallen** [comment]
Just tested and we are getting prompt in the custom authorize request validator.

**Comment by maganuk** [comment]
Don't know what causes mine to be null always. Anyways, I think I'm okay to close the issue.

Thanks for all your help and thank you for the wonderful library. It's magic.
