### ISSUE TITLE
 identityServer is an API Project?

### ISSUE THREAD

**Issue by AdwardNguyen** [IdentityServer/IdentityServer4#2762]
Hi 
In my example, i build identityServer is an API Project

MVC Core: Login (call API authentication - MVC Client - Port: 5001)
API Authentication (IdentityServer - Port: 5000)
API Core (Secured API - other feature - Port: 5002)

When I start MVC Client (with authorize attribute) it's always call redirecturi (https://localhost:5001/signin-oidc, if I change this value to another url, it's showing error: invalid redirect_uri) from configuration and then call the next url: https://localhost:5000/account/login... but I want redirect to login screen from MVC Core (https://localhost:5001/User/Login)

Please help me!

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
