### ISSUE TITLE
Support for custom scope values

### ISSUE THREAD

**Issue by mladjanm** [IdentityServer/IdentityServer4#2763]
### **Problem description**
Organisation that I am working in is currently working on developing PSD2 Enabler solution. Recently we encountered a problem. According to Berlin Group PSD2 specification our solution should support payment authorization using OAuth2 protocol. Our idea was to use authorization code flow for payment authorization. In specification is stated that the scope attribute of OAuth2 Authorization request needs to be linked to the created payment resource. The value of the scope attribute should be in format 
**PIS:\<paymentId\>** where PIS: is fixed value for every request and paymentId represents identification of the created payment resource. 

### **Possible solutions**
Is it possible to send values that are not predefined in database or in-memory configuration through the scope attribute ? If not, can we somehow define template for values that we want to send through the scope attribute? For example, I want to define template PIS:\<paymentId\> which will allow to send paymentId through scope without modifying scopes in Identity Server configuration.

For more details about NextGenPSD2 Berlin Group specification read chapters
_4.3 Optional Usage of OAuth2 for PSU Authentication or Authorisation
5.1.3 OAuth2 SCA Approach: Implicit Start of the Authorisation Proces_ 
in this document https://docs.wixstatic.com/ugd/c2914b_bec5f9d0d3c94cfca2ad1b9da36dc752.pdf

and chapter _5.5.2 SCA using the OAuth2 approach_  
in this document https://docs.wixstatic.com/ugd/c2914b_39d88d82249d482ebcb9a92ebf03d159.pdf .

**Comment by brockallen** [comment]
There might be things you could do to get it to work, but we're not specifically designed for dynamic scopes. 

If you're interested in consulting to support your effort, let us know.

**Comment by hillin** [comment]
I'm interested in using identityServer in payment authorization scenarios. I also found [this blog post](https://leastprivilege.com/2017/05/02/financial-apis-and-identityserver/) prospecting the support of PSD2 in identityServer.  Do we have any progress?

**Comment by leastprivilege** [comment]
Tracking here

https://github.com/IdentityServer/IdentityServer4/issues/3520
