### ISSUE TITLE
Can i customise Identity server 4 in web API solution for user registration,change password,claims customisation?

### ISSUE THREAD

**Issue by UMANGAWASTHY** [IdentityServer/IdentityServer4#2765]
I want to use identity server 4 registration,change password,claims customisation as a seperate core Web API solution instead of single IdentityServer4 solution. I want to seperate login in different solution and other actions which i mentioned above in another solution with access token validation using IdentityServer4.AccessTokenvalidation. Can that be possible?

**Comment by AdwardNguyen** [comment]
I have same problem, when I add new Web API Project (IdentityServer), almost everything is working fine, but... have a problem when you config RedirectUris, it't always redirect to https://localhost:5000/Account/Login... while you want to switch to another url from another application

**Comment by wgutierrezr** [comment]
I have the same idea as @UMANGAWASTHY and I'm stuck at validating tokens created manually. This line returns null:
`var context = await _interaction.GetAuthorizationContextAsync(token);`

Regards

**Comment by brockallen** [comment]
That's up to your hosting app.

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
