### ISSUE TITLE
How to add more info to Claims before issuer access token for Client_Credentials flow

### ISSUE THREAD

**Issue by theblue8488** [IdentityServer/IdentityServer4#2768]
Hi everyone,

I have an issue about authentication and authorization in IdentitySever4. I need your advice with my issue as in follow:
I use Client_Credentials flow to protecting APIs.
I created an Client have many client secret, with each client secret is a user in my system (it means that user id or user name or user's email). My problem is how can i add more user id which stored in client secret to Claims before IdentityServer4 issuer to access token.

I will try to add more user id in client secret to Claims at method FindClientByIdAsync(string clientId) in IClientStore interface. It works fine with a client have only one client secret but if a client have many client secret then i can't identify expected client secret because in this method have only param clientId.

Is there any ways to add more Claims for Client_Credentials flow before Idp issuer to access token.?

Thank you so much, hope to hear form you soon,

**Comment by aaabdul** [comment]
I don't think this is the right approach. If you want the client to behave differently depending on the caller then I would suggest using multiple clients as you get more granular control.

Not sure what you mean by user id here as client credentials are meant for system to system access.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
