### ISSUE TITLE
JSON response formatting is different from ASP.NET Core

### ISSUE THREAD

**Issue by MartinZikmund** [IdentityServer/IdentityServer4#2769]
### Issue / Steps to reproduce the problem
The `HttpResponseExtensions` class writes JSON responses in `PascalCase` format instead of `camelCase` which is the ASP.NET Core default. It would be great if it was possible to at least configure this, or set the default to match ASP.NET Core.

**Comment by leastprivilege** [comment]
Why? What's the scenario?

**Comment by leastprivilege** [comment]
Can you give me an example?

I would say most things we write to the response have the exact casing per specification.

**Comment by brockallen** [comment]
Anything else to add to this?

**Comment by MartinZikmund** [comment]
Sorry, it was on our side :-) . We were using the `HttpResponseExtensions` class to output JSON to the response. However, it is surprising this class is marked as `public` as it seems as an internal utility class.
