### ISSUE TITLE
get current client Id in controller (web api ) .NetCore 2.1

### ISSUE THREAD

**Issue by inferiore** [IdentityServer/IdentityServer4#2771]
I working in .netcore 2.1 and identityserver4 , i use Resource owner password (password) for authenticate.
are they can tell me how i can get current client_id in the controller if only i have a bearer token?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
