### ISSUE TITLE
IOException: IDX20804: Unable to retrieve document from: 'http://localhost:32772/.well-known/openid-configuration'.

### ISSUE THREAD

**Issue by doorwaaar** [IdentityServer/IdentityServer4#2772]
Hi, I trie to set up a projects using asp.net mvc but i have this error when running docker-compose : IOException: IDX20804: Unable to retrieve document from: 'http://localhost:32772/.well-known/openid-configuration'.

can you help me to fix it ?
My sample is here :
https://github.com/doorwaaar/identity-server4-asp.net-core-docker

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
