### ISSUE TITLE
NodeJS authentication examples - please?

### ISSUE THREAD

**Issue by OndeVai** [IdentityServer/IdentityServer4#2773]
With the following setup:

1. An openid connect IDP using IdentityServer4
2. A NodeJs express website that needs to authenticate with IdentityServer4 using the "hybrid" flow. So, that means server to server communication and storing the token (identity and access) in a secure cookie.
3. A NodeJs express REST API that receives requests from the NodeJS website in 2 above. The website will pass the access token as the authorization bearer header in the request. The api will validate the access token and go from there.

All of the documented examples for 2) & 3) above are for Asp.Net Core and mostly wrapped up as middleware. I've searched with web to no avail. How can 2) and 3) be accomplished?

Working samples greatly appreciated!

**Comment by brockallen** [comment]
Sorry, we don't have any nodejs samples nor do we have plans to build any.
