### ISSUE TITLE
Namespaced claims 

### ISSUE THREAD

**Issue by aurokk** [IdentityServer/IdentityServer4#2774]
Hello!

I want to use hasura (https://hasura.io/) and it's jwt based authorization requires some claims in a custom namespace (https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html) like this:
```
{
  "sub": "1234567890",
  "name": "John Doe",
  "admin": true,
  "iat": 1516239022,
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": ["editor","user", "mod"],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "1234567890",
    "x-hasura-org-id": "123",
    "x-hasura-custom": "custom-value"
  }
}
```

As i understand it, i can't create custom claim with complex value type
(https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claim?view=netcore-2.1):
> The Value property contains the value of the claim. In order to reduce dependencies and simplify administration, in WIF the value of a claim is represented only as a string. For more complex value types, it is recommended that you use standard XML schema types to indicate how the value is meant to be serialized into and deserialized from a string.

But maybe...
Can i create a custom claims namespace with IdentityServer?

If it isn't possible please tell me why.

Issue at hasura's github https://github.com/hasura/graphql-engine/issues/978

**Comment by TomCJones** [comment]
json is just a string

**Comment by aurokk** [comment]
Yes, but IdS return it as a string: 
```
{
  "nbf": 1541262390,
  "exp": 1541265990,
  "iss": "http://localhost:5000",
  "aud": [
    "http://localhost:5000/resources",
    "rulebook-api"
  ],
  "client_id": "ios.client",
  "sub": "ebc42b59-d9a7-49ae-adab-2c0d19c3cfb0",
  "auth_time": 1541262386,
  "idp": "google",
  "rulebook_claims": "{\"x-hasura-allowed-roles\":[\"user\"],\"x-hasura-default-role\":\"user\",\"x-hasura-user-id\":\"ebc42b59-d9a7-49ae-adab-2c0d19c3cfb0\"}",
  "scope": [
    "openid",
    "rulebook-api",
    "offline_access"
  ],
  "amr": [
    "external"
  ]
}
```

And it's a problem, i need it deserialized :)

**Comment by leastprivilege** [comment]
Set the value type to JSON.


-------
Dominick Baier

**Comment by brockallen** [comment]
We tested it and this is what we get:

![image](https://user-images.githubusercontent.com/649492/47966347-58030100-e01f-11e8-94fb-c59c37146e2e.png)

**Comment by brockallen** [comment]
This: 

```
var rulebookClaim = new Claim("rulebook_claims",
```

is what gives you this in the result:

```
{
     ...
    "rulebook_claims": {
```

**Comment by aurokk** [comment]
I talk about... 

When I’m save my custom claim to DB, using user manager then I get serialized json in token.

But when I add claim to issued claim with custom profile service, then I get deserialed json in token.

And I don’t understand this is by design or not.

**Comment by leastprivilege** [comment]
There might be a bug involved here that we fixed yesterday. Try 2.3.0-preview2 and see if this changes the behavior.

**Comment by brockallen** [comment]
Any update?

**Comment by aurokk** [comment]
Colleagues, i'm sorry, everything works well, I'm not clearly described the problem. 
I just little confused. When i add claims in token with a custom profile service:
```
public Task GetProfileDataAsync(ProfileDataRequestContext context)
{
      ...
       var rulebookClaim = new Claim(
           "rulebook_claims",
           JsonConvert.SerializeObject(rulebookClaimData),
           IdentityServerConstants.ClaimValueTypes.Json
       );
       context.IssuedClaims.Add(rulebookClaim);
       ...
}
```

But when i create a new user, like this:
```
public async Task RegisterUser()
{
    // Create user
    var user = new ApplicationUser
    {
        UserName = Guid.NewGuid().ToString(),
    };
    var createResult = await _userManager.CreateAsync(user);

    // Add claims 
    var claims = new List<Claim>
    {
        new Claim("test", "{\"foo\":\"bar\"}", IdentityServerConstants.ClaimValueTypes.Json),
    };
    var addClaimsResult = await _userManager.AddClaimsAsync(user, claims);
}
```

I expected there should be a field ```valueType``` in database like "json" :)
![image](https://user-images.githubusercontent.com/7325744/48356280-f853c800-e6a6-11e8-96e4-51f863c1d1ca.png)
