### ISSUE TITLE
Errors on Auth when creating JavaScript client

### ISSUE THREAD

**Issue by JSweetland95** [IdentityServer/IdentityServer4#2776]
### Issue / Steps to reproduce the problem

Was following the quickstart docs. Followed it all through and finished the javascript client and found a couple of problems. I am not sure if I have missed something or if the quickstart implies something. 

It seems that the JavaScript Oidc user manager tries to call the logout(logoutId) overload which following the quickstarts the ASP.NET Core identity quickstart does not implement this method. 

Similarly, the client added to the identity server for the js client requires consent which again following the ASP.NET Core identity quickstart is not implemented. 

Is it assumed that we should copy the quickstart UI with these methods to the ASP.NET Core identity quickstart project or use the older quickstart project which uses the UI but not the identity. 

I just wanted to make people aware of this in the quickstarts but not sure which is the better solution. 

### Relevant parts of the log file

![image](https://user-images.githubusercontent.com/30146202/47964247-d1eeb680-e02e-11e8-99c5-db2d8b765e7e.png)

![image](https://user-images.githubusercontent.com/30146202/47964265-27c35e80-e02f-11e8-97e3-b22ab3bf87f0.png)

**Comment by brockallen** [comment]
You probably took the prior quickstart (the one using ASP.NET Identity) as the starting point for this one?

**Comment by JSweetland95** [comment]
Ahh yes, that would be it. Thank you for the quick reply. Where should it follow on from as a minimum? Would it be possible to just add a sentence saying that at the beginning just to prevent other peoples future confusion?

**Comment by brockallen** [comment]
At the end of the ASP.NET Identity QS it says: http://docs.identityserver.io/en/release/quickstarts/6_aspnet_identity.html#what-s-next

It basically means that yea, the ASP.NET Identity UI is really missing abunch of stuff to really make your host a full OIDC server implementation. Basically their template mindset is just for local stuff, whereas IdentityServer/OIDC needs more. 

HTH
