### ISSUE TITLE
2FA support?

### ISSUE THREAD

**Issue by norcis** [IdentityServer/IdentityServer4#278]
Hello,

I'm creating rest api and first party native mobile app which will consume it. To authorise API access and authenticate users I want to implement OpenId Connect with 2FA.

It would look like this:

1) in the app, user enters his username/password or use Facebook/Google etc.
2) if it's validated, server send SMS with shared secret to customer associated phone number.
3) clients enters PIN code received by SMS in the app. This pin could be passed to server to get token or maybe it should be stored in app and used for signing future requests. I'm not sure which flow should be used in such case.

Any recommendations how to do that?

**Comment by liamdawson** [comment]
https://docs.asp.net/en/latest/security/authentication/identity.html
https://docs.asp.net/en/latest/security/authentication/2fa.html

https://github.com/IdentityServer/IdentityServer4.AspNetIdentity

Use asp.net core Identity to handle the login and 2FA, integrate it with IS4 for the token generation etc.

**Comment by norcis** [comment]
Thank you for reference. I reviewed sample, but I'm not sure which option is suited for my case. 
I don't wan't to open web browser for user inside app, but I also don't want to store user password inside app (but secret sent by SMS could be) . User should put credentials in app's login screen (ResourceOwner flow?), but followed with 2FA.

**Comment by leastprivilege** [comment]
Resource owner is an anti-pattern. You are just deviating from all proven paths and make your life harder.

https://tools.ietf.org/html/draft-ietf-oauth-native-apps-03

**Comment by diegoabrantesalves** [comment]
I'm having a loop problem that happens sometimes, when I reboot the pool does not happen anymore and after a while happens anyone can help me?
