### ISSUE TITLE
refresh token expiration discovery

### ISSUE THREAD

**Issue by neilwashere** [IdentityServer/IdentityServer4#2781]
**Problem**
There is no standard way to discover expiration data for refresh tokens. This means holders of 
the refresh token simply do not know how long it will last for and therefore what refresh timing
strategy to use. It would be far nicer to know before hand if a refresh token is likely to work or
not.

**Possible Solution - within spec**
Make the refresh_token a JWT encoded with expiration info.

**Alternatives Considered - not quite within spec?**
- Implementing a discovery endpoint to return expiration data about a given refresh token
- overriding the token response to include refresh token expiration
 
**Additional context**
Our implementation does not have a one-size-fits-all pattern for access token and refresh token expirations. In many cases we simply can't tell our clients ahead of time just how long their access will last. Having expiration dates in the refresh token or on the token response would solve this.

**Comment by brockallen** [comment]
> There is no standard way to discover expiration data for refresh tokens. This means holders of
the refresh token simply do not know how long it will last for and therefore what refresh timing
strategy to use. It would be far nicer to know before hand if a refresh token is likely to work or
not.

This will never be 100% perfect as the end user can always revoke them. So you have to code for that.

>  Make the refresh_token a JWT encoded with expiration info.

No, the refresh token is not meant for clients to parse. Same goes for access tokens.

**Comment by neilwashere** [comment]
I would settle for 90% perfect. As it stands today access tokens can also be rendered useless via consent revocation. That the JWT is not meant to be parsed by the client is of course correct but pragmatism rules the day. Using values in the JWT is a practical way for our clients to perform account reconciliation amongst other things.
I am still curious as to why the refresh token expiration is omitted on a Token response (should there be a refresh token of course). I know it's not in the spec but do you know the reasoning behind this? One approach I am considering is simply changing the response to have this data. I can only guess there must be a really good reason not to.

**Comment by leastprivilege** [comment]
The spec does not cover this sort of response information back to the client. Thus I don't see why IS core needs to have it.

You can add custom response parameters yourself by implementing the custom token request validator.

**Comment by neilwashere** [comment]
Fair enough. Thanks :)
