### ISSUE TITLE
Allow 'IsActive' check on IdentityServer4.AspNetIdentity.ProfileService<TUser> for users not in ASP.NET Identity store of identity server

### ISSUE THREAD

**Issue by Meertman** [IdentityServer/IdentityServer4#2784]
Hi,

I've used the "feature request" issue template, but I rather think this is a question instead of a bug, or a feature request. 

Currently we have a setup using Identity Server 4 and ASP.NET Identity Core. In our scenario we have both internal users (defined in Active Directory), as well as external users (which we want to define in the ASP.NET Core Identity database used by identity server). 

One of the requirements we currently have is that we do not want to persist the users specified in Active Directory also in the (ASP.NET Core Identity) database used by identity server, as this would require a sync between the two (users that are locked / disabled / removed in AD would also need to be locked / disabled / removed in the database of identity server.

Our solution currently looks as follows:
We have configured 2 identity servers. One which uses the ASP.NET Core Identity database and is deployed in our DMZ and another one which uses a custom implementation of the ASP.NET Core Identity interface for retrieving information from Active Directory.

The identity server that uses AD as its underlying store is setup as an external identity provider for the identity server that uses an ASP.NET Core Identity database.

By overriding the ExternalLoginSignInAsync method of the SignInManager we allow (through configuration per external identity provider) the option to not lookup the claims of the user in the underlying store, but rather "pass-through" the claims of the external identity provider. (As such effectively not requiring the users stored in Active Directory to also be stored in the database of the identity server using the database)

When implementing this scenario, we have run into the ProfileService (IdentityServer4.AspNetIdentity.ProfileService<TUser>), which also checks the user in the underlying store (when using ASP.NET Core Identity with identity server), and effectively stating that users are not-active when the claims have been "passed through" from an external identity provider. (This check happens when calling the AuthorizeCallbackEndpoint)

It seems that this check is mostly done as a sort of revocation for a specific user?

Currently, we have considered the following solutions:
- Specify an additional claim (containing the name of the scheme used in case of an external identity provider login) on the user authenticated in the identity provider, and as such checking if the external identity provider is configured as "pass-through", and then foregoing on the IsActive check.
-> Pro's: We only change the flow in case of our "custom pass-through" solution.
-> Contra's: we have to add a custom claim, just to pass information from one call to another.

- Implement an additional property on the user persisted in the database which tells us if that user has been revoked. If a user cannot be found in the database, or this property is not set, then the user is considered 'Active'
-> Pro's: This allows us to revoke tokens for users coming from an external identity provider (we just need a record in the database with a random generated password), as well as users coming from our own identity provider.
-> Contra's: if the user is removed from the database, the user will just be considered 'Active'.

Are we missing alternatives here? Or are we misinterpreting the use of the IsActive call on the ProfileService? 

I'm happy to respond with additional information in case our scenario is not clear.

Thanks in advance for any advice or guidance you could provide us with!

Kind regards!

**Comment by TomCJones** [comment]
If you are already running AD, you can use ADFS as your external site rather than try to duplicate its functionality with IdSvr4.

**Comment by Meertman** [comment]
Hi @TomCJones,

Thanks for the quick reply! I completely agree with you that ADFS would solve Some problems, but not everything. (The external users are not in AD)

However, due to organisational reasons, ADFS is not an option. 

Kind regards

**Comment by TomCJones** [comment]
Then you need to learn if idsvr4 can read/write ad. If not you will need some sort of shadow user db if you want some of that functionality you describe above.

**Comment by brockallen** [comment]
You'd need to implement IsActive to match your identity design and semantics.

**Comment by Meertman** [comment]
Hi @brockallen, @TomCJones,

Thank you both for replying to this thread. For future reference, we've decided that we're going to create a temporary copy (with an "unknown" password) of the Active Directory information in the underlying store for identity server. (Upon login, the information coming from Active Directory will always be copied into the database again, for the maximum duration of the login session)

We feel that this most closely resembles the current architecture principles and will cause the least impact in future scenario's. 

Kind regards.
