### ISSUE TITLE
Custom app login screen with identityserver4

### ISSUE THREAD

**Issue by amiteshs** [IdentityServer/IdentityServer4#2786]
I am new to IdentityServer4. We have an existing Web app and now we are planning to write an API for 3rd party apps to connect. We want to use IdentityServer4 for the authentication. I have the IdentityServer server running but I want the user to be directed to our Web login page to login rather than the IdentityServer login. I can achieve this by setting the UserInteractionOptions.LoginUrl. After the login I redirect the user to the return Url that was passed in but the identity server redirects back to our web app and the keeps cycling. How can I tell the IdentityServer that the user has been authenticated? So that the IdentityServer shows the consent screen

**Comment by brockallen** [comment]
have you read the docs?

http://docs.identityserver.io/en/release/topics/signin.html#login-workflow

**Comment by amiteshs** [comment]
Yes I have and that link does not explain how to achieve my scenario.

**Comment by brockallen** [comment]
Well, your external app would somehow need to issue a cookie at your IdentityServer. How that's done is up to you. We do have customers doing that successfully.

**Comment by karpikpl** [comment]
Hey @amiteshs - have you solved your problem?
