### ISSUE TITLE
Backend management API for IS4

### ISSUE THREAD

**Issue by OculiViridi** [IdentityServer/IdentityServer4#2787]
Hi!
I'm using IS4 to manage authentication with `OAuth` and Users/Roles/Permissions with ASP.NET Core Identity.

I'd like to be able to create/edit/delete users/roles/clients/resources/etc. through some kind of backend management **REST Web API** exposed by the IS4 app, so that my application can call the needed methods.

I created a new IS4 .NET Core project using the "_IdentityServer4 with ASP.NET Core Identity_" (`is4aspid`) template, but I've not found any API Controller inside. Are those kind of controllers available somewhere, maybe starting from a different IS4 template?

May this management API feature be already available in your **AdminUI** commercial project or the management can be done only through the UI?

**Comment by scottbrady91** [comment]
Good question. Yes, this functionality is available in our AdminUI product. This product gives you both a UI to handle these functions and full access to the backing API. Access to this API is protected by your own IdentityServer.

To get a free trail please visit https://www.identityserver.com/products or feel free to email sales@identityserver.com directly.
