### ISSUE TITLE
 Web API written in IdentityServer3.AccessTokenValidation does not redirect to identityserver4 api for authenticate

### ISSUE THREAD

**Issue by samanevrc** [IdentityServer/IdentityServer4#2789]
hi
my web api sample that configed by IdentityServer3.AccessTokenValidation in StartUp.cs
doest not even redirect to IdentityServer4 api

in my api i wrote this:

var config = new HttpConfiguration();
config.MapHttpAttributeRoutes();

        app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
        {
            Authority = "http://localhost:6001",
            RequiredScopes = new[] { "api" },

            DelayLoadMetadata = true
        });

        app.UseWebApi(config);
and i configed my identityserver4 to port 6001,
but when i start both of them, my api/test does not redirect to identityserver4 for authenticate
please help me

**Comment by brockallen** [comment]
When authentication fails for a web api, a 401 is returned not a 302.

**Comment by samanevrc** [comment]
yes i exactly get 401 status code with this message 'Authorization has been denied for this request'
i think it means web api doest not recognize identity server to Authorize
despite my identity server app is running and when i connect to it by web api that use of IdentityServer4.AccessTokenValidation it works, but with Web API written in IdentityServer3.AccessTokenValidation  i get that message

**Comment by samanevrc** [comment]
i exactly implement like CrossVersionIntegrationTests-master sample

**Comment by leastprivilege** [comment]
Turn on logging in Katana to get more information.

**Comment by brockallen** [comment]
Any update?

**Comment by samanevrc** [comment]
@leastprivilege I 'll try it
