### ISSUE TITLE
Implicit flow with vue.js with API configuration

### ISSUE THREAD

**Issue by santosh2812** [IdentityServer/IdentityServer4#2790]
Hi All, I am trying to implement ID4 with vue.js Now I have few question as below 
1. I have more than 100 of API which will be used by my vue.js client so Do i need to add all the api Name in config of vue,js as below 
`import { UserManager } from "oidc-client";
class ApplicationUserManager extends UserManager{
    constructor(){
        super({
            authority: 'http://localhost:5000',
            client_id: 'gpsvueappjs',
            redirect_uri: 'http://localhost:8080/#/callback/#',
            response_type: 'id_token token',
            scope: 'openid profile schoolsysytemapi.Admin',
            post_logout_redirect_uri: 'http://localhost:8080/index.html'
          })
    }

    async login () {
        await this.signinRedirect()
        return this.getUser()
      }
    
      async logout () {
        return this.signoutRedirect()
      }
}
`
currently I have added one 
 scope: 'openid profile **schoolsysytemapi.Admin**' if yes then is it possible to make it dynamic as we are also make such configuration in ID4 DB. 
2. I need to manage the permission by using Claim of the User - as I have different type of User and I want to give different permission to different user - for example Admin user can create some data but office staff can only view the things like that, SO How can I make the role associated the with API and the User. 
3. Do I need to store the token on client side. 
4. In the API application side do I need to write custom Authorization module to handle the permission . 
please , i Have tried to follow the document but its not clear and I am new to IdentityServer4 that's might be not able to get it work. 
Thanks
Santosh Jha

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
