### ISSUE TITLE
Updating Claims Provided By An External Provider

### ISSUE THREAD

**Issue by leninator** [IdentityServer/IdentityServer4#2792]
Not sure if i'm missing something here or if its something that needs to be done in a custom way (Or even if what I'm trying is bad practice). Consider the following Scenario.

- A User chooses to log in via a external provider to my IDS4 server.
- IDS4 automatically provisions a local user and completes the sign-in of the user. My application is interested in a 'phone_number' claim and so copies this value to its local store.
- Later on the User updates their 'phone_number' in the external provider. So now the claim in my local IDS4 store is out of date.

What is the best way to update my local 'phone_number' claim. If i'm using a sliding refresh token there's a chance that it could be a very long time before a user has to re-authenticate against the original external provider and realize this claim has been updated.

In this particular case I have access to both the IDS4 instance and the External provider.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
