### ISSUE TITLE
Year 2038 problem in nbf and exp

### ISSUE THREAD

**Issue by vanbukin** [IdentityServer/IdentityServer4#2793]
### Issue / Steps to reproduce the problem
If we look into that lines https://github.com/IdentityServer/IdentityServer4/blob/nuget_2.3.0-preview2/src/Validation/Default/TokenValidator.cs#L452-L453 we will see, that reference token `nbf` and `exp` claims values comes from calling `.ToEpochTime` extension method from `IdentityModel` https://github.com/IdentityModel/IdentityModel2/blob/3.10.1/src/EpochTimeExtensions.cs#L16, which returns Int32, instead of Int64.
I think it should return Int64, or have additional extension method, that returns Int64.

**Comment by leastprivilege** [comment]
Will switch to the .NET built-in ones in v3

https://identitymodel.readthedocs.io/en/latest/misc/epoch_time.html

**Comment by brockallen** [comment]
Looks like a lot has been updated to use `long`, but where we emit claims we need to change to use `ClaimValueTypes.Integer64`.

**Comment by leastprivilege** [comment]
done on branch. Will be merged into 3.0
