### ISSUE TITLE
IdentityServer4 nginx proxy_pass

### ISSUE THREAD

**Issue by valeravorobjev** [IdentityServer/IdentityServer4#2795]
Hi! 
Guys help solve the problem! I am trying to work with identity Server 4 via nginx proxy_pass.

I've got some services: auth.service (identityServer), service.backend, service.site(asp.net mvc client).
auth.service host on localhost:5000, service.backend on localhost:6000, service.site on localhost:6001.

I want proxy to 80 port. The result should be as follows: http://localhost/auth , http://localhost/backend, http://localhost/ (site)

This is my nginx.conf

```events {
}

http {
       server { # simple reverse-proxy
         listen       80;
         server_name  droplet;
     
         location /backend/ {
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_pass http://droplet:6000/;
         }

         location /auth/ {
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_pass http://droplet:5000;
         }

         location /signin-oidc/ {
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_pass http://droplet:6001/signin-oidc;
         }

         location / {
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection keep-alive;
            proxy_set_header   Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_pass http://droplet:6001;
         }

     }
}
```
Then I try to switch to a protected resource. I am redirected to the login page. It's OK. I enter my username and password, click login. It's OK.

The authorization server then redirects me to http://myhost/signin-oidc. And here I get the error! 

> Correlation failed

I started watching what was happening!
It turns out that the request POST http://myhost/signin-oidc return http code 301 and immediately GET request to the same path.

What am I doing wrong?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by Vandersteen** [comment]
Did you ever manage to resolve this issue ?
We are hitting the same issue with http2 / nginx / ID4

**Comment by Vandersteen** [comment]
For future reference, our issue was that the default settings for header sizes in nginx were too small.

This worked for us:

```
    proxy-buffer-size: "128k"
    proxy-buffers: "4 256k"
    proxy-busy-buffers-size: "256k"
    large-client-header-buffers: "4 16k"
    client-header-buffer-size: 64k
    http2-max-field-size: 16k
    http2-max-header-size: 128k
    large-client-header-buffers: 8 64k
```

**Comment by eaba** [comment]
@Vandersteen how did you apply those settings? Annotation? ConfigMap? Please provide sample...thanks

**Comment by Vandersteen** [comment]
nginx-ingress terminates ssl
services / deployments / pods use http

I apply'd these configurations in the configmap

**Comment by lenardchristopher** [comment]
> I apply'd these configurations in the configmap

Further supporting this statement, some of the configuration options aren't accessible via annotations. It has to be done with a ConfigMap.

**Comment by eaba** [comment]
@lenardchristopher  and @Vandersteen  please can you show how you were able to apply the configuration in the configmap?
I tried same but nginx conf is not being updated

**Comment by lenardchristopher** [comment]
@eaba I updated the ConfigMap yaml and applied the changes, then I deleted the ingress controller pods to force them to reload with the new config. To verify my changes took effect, I tunneled into one of the ingress pods and looked at nginx.conf.
