### ISSUE TITLE
Question: idp session cookie is not sliding along with silent renewals

### ISSUE THREAD

**Issue by vejandla** [IdentityServer/IdentityServer4#2796]
I am runnig through a weird problem. I am able to do the silent renew, but my idp cookie is getting sliding.
More into the problem...

I have idp session cookie (idsrv) life time set to expire in 15 min and i kept the same time for Access and id token life time too.

On my JS client, i check user activity for every 2 min and if there is an activity in the last 2 min, i will renew the token.

I am able to get access and id token with renewed expiration times, but after 15 minuitues(idp cookie life time) silent renew calls are failing and idp is logging out. And i checked response of silent remew call, i see no cookies being set(with new slidingexpiration time) in the response headers.

Are there any settings i am supposed to enable at the server side? Appreciate your help.

**Comment by brockallen** [comment]
> I am able to get access and id token with renewed expiration times, but after 15 minuitues(idp cookie life time) silent renew calls are failing and idp is logging out.

Sounds like your cookie at IdentityServer is set to fixed 15m, no sliding.

Having said that, this seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by vejandla** [comment]
Thanks for the reply @brockallen We enabled the sliding option while configuring the identity server.
