### ISSUE TITLE
Guidance and samples for Multi-Region deployments

### ISSUE THREAD

**Issue by PaulMcManus23** [IdentityServer/IdentityServer4#2799]
In the age of GDPR can I ask what the official approach/plan is for global IdentityServer4 deployments that maintain PII in the users home region.

Is it along the lines of the below articles?

https://wso2.com/library/articles/2018/04/multi-region-deployment-for-wso2-identity-server-part-1/
https://wso2.com/library/articles/2018/04/multi-region-deployment-for-wso2-identity-server-part-2/

If so... is there guidance or a sample of how to handle these additional federation requests to alternate regional sibling identity server deployments? 

Does it rely on encryption and data replication between zones? If so, how do we handle multiple database connection strings (i.e. read only and read/write database instances)?

Can someone point me in the direction of some documentation or samples for dealing with the scenario?

**Comment by TomCJones** [comment]
That's really hard if you have a single domain name system like me@foo.com.
Then the locality is an attribute, which needs lookup to enable.
The easier way is to put users in local domains.
user1@na.foo.com
user2@eu.foo.com
user3@asia.foo.com
you can still have a disambiguation server if you want for email (which is a version of the lookup above.)
switching domains is hard, but so is life.

**Comment by brockallen** [comment]
> In the age of GDPR can I ask what the official approach/plan is for global IdentityServer4 deployments that maintain PII in the users home region.

Sorry, but this is beyond what we can help you with here on the issue tracker.
