### ISSUE TITLE
WS-Federation and external IdPs

### ISSUE THREAD

**Issue by Caleb1424** [IdentityServer/IdentityServer4#28]
Hello,

can you give me some info about your plans to support WS-Federation, External IdPs and WindowsAuthentication with IdSrv4.

Thanks a lot

**Comment by leastprivilege** [comment]
WS-Federation is not support in ASP.NET core 1.0 (there are plans to do that later - and we depend on that).

Windows Authentication - I don't know yet. All those low level details are moving targets right now. If it is possible we will certainly do it.

**Comment by uncleyo** [comment]
Do you think it could be possible to reuse the existing katana ws-federation implementation when targeting full framework?

**Comment by brockallen** [comment]
You could probably use parts of it to get the ws-fed protocol features, but then hook the various notifications to then bridge the gap to the new ASP.NET Core approach.
