### ISSUE TITLE
Primary key violation on Persisted Grants after deleting cookies

### ISSUE THREAD

**Issue by Petteroe** [IdentityServer/IdentityServer4#280]
I have followed your quickstarts up until adding more scopes. So I have a javascript test client and an MVC test client, and everything is in SQL server (ASP.Net Identity for users and your EF stuff for config and operational data).

After I manually delete cookies in order to start from scratch with a user story, I get a primary key violation: Violation of PRIMARY KEY constraint 'PK_PersistedGrants'. Cannot insert duplicate key in object 'dbo.PersistedGrants'. The duplicate key value is (Kmku4vRK/LNcnhv2tPtM2PcRvZQkvxipzP8w4e/jt8o=, user_consent)

Steps to reproduce:

- Open the action on the MVC test client with the Authorize attribute. 
- Log in using IdentityServer
- Open the javascript test client and click the Login button
- Clear cookies
- Refresh the javascript test client and click the Login button again
- Log in using IdentityServer
- Give the consent
- Go back to the action on the MVC test client with the Authorize attribute and refresh
- Give the consent -> Here you will get the crash.

![image](https://cloud.githubusercontent.com/assets/5712277/18417169/b49c961c-7828-11e6-89b5-6549aa648357.png)

Best regards, 
Morten

**Comment by brockallen** [comment]
Tracking here: https://github.com/IdentityServer/IdentityServer4.EntityFramework/issues/7

Thanks for the report.

**Comment by brockallen** [comment]
IdentityServer4.EntityFramework-rc1-update1 is now on nuget.

**Comment by Petteroe** [comment]
That was quick ☺

Thank you.

Morten
