### ISSUE TITLE
CorsPolicyService did not allow origin: file://

### ISSUE THREAD

**Issue by littleowlnest** [IdentityServer/IdentityServer4#2801]
Trying to make an AJAX call from a PhoneGap application and CORS is rejecting the call to my IS4 secured API.

### Issue / Steps to reproduce the problem
Using a jQuery AJAX call from PhoneGap, note that the call works inside the browser hosted version of PhoneGap e.g. http://192.168.0.133:3000/

However, if it makes the call from within PhoneGap on a device, it will fail.  The origin will be something like:
file:///var/mobile/Containers/Data/Application/{Guid}/..../www/index.html

I've tried adding file:// as a CORS origin and it still gets rejected by CORS.

### Relevant parts of the log file
```
2018-11-14 15:22:31.287 +00:00 [WRN] CorsPolicyService did not allow origin: file://
```

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
