### ISSUE TITLE
Code sample update request

### ISSUE THREAD

**Issue by ZoricaL** [IdentityServer/IdentityServer4#2802]
At link:
http://docs.identityserver.io/en/release/quickstarts/1_client_credentials.html

... the code needs this line to work: using IdentityServer4.Models;
Otherwise, adding ApiResource and Client reference is not recognized.

**Comment by brockallen** [comment]
PR on the docs is welcome.

**Comment by leastprivilege** [comment]
docs are being re-worked right now. And yes - PRs are welcome.
