### ISSUE TITLE
Need to propagate error description when a client fails validation.  

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2804]
**Is your feature request related to a problem? Please describe.**

I wish to fail client validation for any reason.  My current use case is to rate limit the client.
I plan to do this by implementing my own IClientSecretValidator and returning a clientResult that has a rich error description.

**Describe the solution you'd like**
The current implementation in TokenEndpoint only knows there is an error but doesn't propagate the error.
```
 internal class TokenEndpoint : IEndpointHandler
 {
        private async Task<IEndpointResult> ProcessTokenRequestAsync(HttpContext context)
        {
            _logger.LogDebug("Start token request.");

            // validate client
            var clientResult = await _clientValidator.ValidateAsync(context);

            if (clientResult.Client == null)
            {
                return Error(OidcConstants.TokenErrors.InvalidClient);
            }
            .......
     }
}
```
Proposed fix
```
 internal class TokenEndpoint : IEndpointHandler
 {
        private async Task<IEndpointResult> ProcessTokenRequestAsync(HttpContext context)
        {
            _logger.LogDebug("Start token request.");

            // validate client
            var clientResult = await _clientValidator.ValidateAsync(context);

            if (clientResult.IsError || clientResult.Client == null)
            {
                // I wish the client result actually had something close to a full TokenErrorResponse
                // i.e. ErrorModel that has everything that the TokenErrorResponse needs
                var error = clientResult.Error ?? OidcConstants.TokenErrors.InvalidClient;
                var errorDescription = clientResult.ErrorDescription;
               // wish I had a custom object to pass
               // wish I had control over the status_code that goes out as well
                return Error(error, errorDescription);
            }
            .......
     }
}
```

**Describe alternatives you've considered**
I could validate earlier in the pipeline, but then there is double validation for all calls.  The rate-limit is a rare hit.  This is probably cleaner as I can get in front of the entire IdentityServer pipeline and leave the codebase alone.  However, it punishes the good calls by introducing inefficiencies.

Have you run into another situation where someone wanted to rate-limit a client and is there a better place to do this?

The proposed change is backwards compatible and non-breaking.

I will write another issue(#2805),  about have a TokenErrorResult that lets me specify the status_code.

**Comment by brockallen** [comment]
Why not a custom token request or authorize request validator?

**Comment by ghstahl** [comment]
I got it working using a middleware earlier in the pipeline.  
I will research the authorize request validator as an option as well.
Saying that, is it still fair to say we should propagate the errors from the clientresult?

**Comment by brockallen** [comment]
I suggested the custom validators since they expose ways to indicate the error.
