### ISSUE TITLE
TokenErrorResult should allow me to specify the status_code

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2805]
**Is your feature request related to a problem? Please describe.**
related to #2804
TokenErrorResult hard codes the error status code as 400.

I would like to have control of this and have a status code of [451](https://en.wikipedia.org/wiki/HTTP_451) sometimes.

**Comment by brockallen** [comment]
400 is what the spec says for errors: https://tools.ietf.org/html/rfc6749#section-5.2

**Comment by ghstahl** [comment]
Touche!
