### ISSUE TITLE
Infinite requests to the /connect/userinfo endpoint

### ISSUE THREAD

**Issue by ydekova** [IdentityServer/IdentityServer4#2806]
### Issue / Steps to reproduce the problem
We have identityserver4 in out authorization server and oidc-client.js on the web client. We use the implicit flow, we have enabled a silent refresh on the client. We have this configuration for quite some time.

For some time we have been observing a strange issue on production. For some users, we have about 70 requests to /connect/userinfo within a second in our access logs.

All requests return 200, with payload about 550B
most of the problematic clients are using Chrome

We checked the configuration for the tokens expiration time and when to renew. Everything seems to be as expected. 

Here are our relevant configs:
the client configuration on the server:
    IdentityTokenLifetime = 300,
    AccessTokenLifetime = 3600,
    UpdateAccessTokenClaimsOnRefresh = true,

the oidcManager configuration on the client:
    automaticSilentRenew: true,
    accessTokenExpiringNotificationTime: 60,
    silentRequestTimeout: 50000,

We can't reproduce this on a local dev machine. What might be the reason for such behavior? Any help about where to look for clues will be highly appreciated.

Thanks

**Comment by brockallen** [comment]
Check your logs to identify which client and look into why it's doing that. That is a legal type of request, so the fact that it's calling many many times seems like a client coding problem.

**Comment by ydekova** [comment]
Thanks a lot for taking the time to respond. Just to let you know that I have found a possible cause and it doesn't seem to be directly related to the oidc-client library but I have to dig a little bit more. 
I'll let you know if I come across something related to your lib. Thanks.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
