### ISSUE TITLE
I m geeting automatically logged out before identity and access token expiration

### ISSUE THREAD

**Issue by developerTN** [IdentityServer/IdentityServer4#2807]
Hi all,

I use identity server 4 (default configuration) with core identity and angular 6.

Currently, after around 10 min of inactivity or less i m getting redirected to identity servee and logged out automatically.

I want this behaviour to be done after let s say 10h.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
