### ISSUE TITLE
How can I configure TwoFactorUserIdCookie ?

### ISSUE THREAD

**Issue by binhphanduc** [IdentityServer/IdentityServer4#2809]
**Can overwrite TwoFactorUserIdCookie when using default authentication schema.**
I cannot find anyway to configure TwoFactorUserIdCookie. It used to be there in Identity Server 1.0.
https://forums.asp.net/t/2128896.aspx?Two+factor+cookie+options+in+ASP+Core+2+0

I have done some investigates, but cannot find a good solution.

Thanks for your help or suggestion.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
