### ISSUE TITLE
Passing Additional Values to Token Endpoint

### ISSUE THREAD

**Issue by vaarenyam** [IdentityServer/IdentityServer4#2811]
Hello,

Does anyone know how one can pass additional parameters to the Token Endpoint in IdentityServer.

I have a need where some additional values need to be used before a Token is generated and sent back to the calling client post successful authorization.

Scenario: Token endpoint gets invoked from a Mobile App with Username, Password and Scope values (which are the three mandatory values). I need to pass the IMEI number too so that some more validations can be done. However, the token endpoint does not have the provision for any additional values. 

How can one perform some authentication based on additional parameters like Mobile No, IMEI etc.

Regards,
Jay

**Comment by leastprivilege** [comment]
Implement a `ICustomTokenRequestValidator`

**Comment by vaarenyam** [comment]
Can you please share some sample for the same.

The link
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/Interfaces/ICustomTokenRequestValidator.cs
is
dead!

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/master/src/Validation/ICustomTokenRequestValidator.cs

I don't have a sample. Implement the interface, register it, put a breakpoint in there. See if you get all the necessary data.

**Comment by vaarenyam** [comment]
I did the following just to check if the code gets hit in debug mode,

public class CustomClaimInjection : ICustomTokenRequestValidator
    {
        private readonly HttpContext _httpContext;

        public CustomClaimInjection(IHttpContextAccessor contextAccessor)
        {
            _httpContext = contextAccessor.HttpContext;
        }

        public Task ValidateAsync(CustomTokenRequestValidationContext context)
        {
            // THIS ONE. HOW TO GET THE SUB. THIS ALWAYS NULL.
            var sub =
_httpContext.User.FindFirst(JwtRegisteredClaimNames.Sub)?.Value;

            var client = context.Result.ValidatedRequest.Client;
            client.Claims.Add(new Claim("sub", sub));  // this will be
[client_sub]

            return Task.FromResult(0);
        }
    }


However, it does not get hit and I get the following exception in Logs,

crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: System.ArgumentNullException: Value cannot be
null.
      Parameter name: value
         at System.Security.Claims.Claim..ctor(String type, String value,
String valueType, String issuer, String originalIssuer, ClaimsIdentity
subject, String propertyKey, String propertyValue)
         at System.Security.Claims.Claim..ctor(String type, String value)
         at
Peso.Identity.Server.Extensions.CustomClaimInjection.ValidateAsync(CustomTokenRequestValidationContext
context) in
C:\JAYDEEP\PROJECTS\PESO\PesoWeb\SETT\src\Peso.Identity.Server\Extensions\CustomClaimInjection.cs:line
27
         at
IdentityServer4.Validation.TokenRequestValidator.<RunValidationAsync>d__14.MoveNext()
      --- End of stack trace from previous location where exception was
thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
         at
IdentityServer4.Validation.TokenRequestValidator.<ValidateRequestAsync>d__13.MoveNext()
      --- End of stack trace from previous location where exception was
thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
         at
IdentityServer4.Endpoints.TokenEndpoint.<ProcessTokenRequestAsync>d__7.MoveNext()
      --- End of stack trace from previous location where exception was
thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
         at
IdentityServer4.Endpoints.TokenEndpoint.<ProcessAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was
thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
         at
IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Value cannot be null.
      Parameter name: value
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Security.Claims.Claim..ctor(String type, String value, String
valueType, String issuer, String originalIssuer, ClaimsIdentity subject,
String propertyKey, String propertyValue)
   at System.Security.Claims.Claim..ctor(String type, String value)
   at
Peso.Identity.Server.Extensions.CustomClaimInjection.ValidateAsync(CustomTokenRequestValidationContext
context) in
C:\JAYDEEP\PROJECTS\PESO\PesoWeb\SETT\src\Peso.Identity.Server\Extensions\CustomClaimInjection.cs:line
27
   at
IdentityServer4.Validation.TokenRequestValidator.<RunValidationAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
IdentityServer4.Validation.TokenRequestValidator.<ValidateRequestAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
IdentityServer4.Endpoints.TokenEndpoint.<ProcessTokenRequestAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at IdentityServer4.Endpoints.TokenEndpoint.<ProcessAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()


I have registered the class in SartUp.cs as below,

services.AddScoped<ICustomTokenRequestValidator, CustomClaimInjection>();

Kindly advise.

Regards,
Jay

**Comment by vaarenyam** [comment]
I added the following and the breakpoint gets hit:

public class CustomClaimInjection : ICustomTokenRequestValidator
    {
        private readonly HttpContext _httpContext;

        public CustomClaimInjection(IHttpContextAccessor contextAccessor)
        {
            _httpContext = contextAccessor.HttpContext;
        }

        public Task ValidateAsync(CustomTokenRequestValidationContext context)
        {
            // THIS ONE. HOW TO GET THE SUB. THIS ALWAYS NULL.
            //var sub = _httpContext.User.FindFirst(JwtRegisteredClaimNames.Sub)?.Value;

            //var client = context.Result.ValidatedRequest.Client;
            //client.Claims.Add(new Claim("sub", sub));  // this will be [client_sub]

            context.Result.CustomResponse = new Dictionary<string, object>
            {
                {"scope", "read" }
            };

            return Task.CompletedTask;

            //return Task.FromResult(0);
        }
    }

However, I am still not sure about the following:

**_1. How can I pass additional values from the client into the call_**

**Comment by leastprivilege** [comment]
Well - you can get any input data e.g. liek `context.Result.Raw.Get("IMEI");`

Then you can put it on `HttpContext.Items?` so you can retrieve it later.

**Comment by vaarenyam** [comment]
@leastprivilege  Thanks a lot for your guidance.

I was able to pass the values as a Dictionary usingg the object parameter of the RequestResourceOwnerPasswordAsync method of the TokenClient and then retrieve it in the ValidateAsync method by using what you mentioned above.

Hope this thread helps others who may have a similar requirement!
