### ISSUE TITLE
Federated Signout and "continue" browser session

### ISSUE THREAD

**Issue by neiljthomson** [IdentityServer/IdentityServer4#2813]
We have a Java based client which works with an Identity Server 4 V2.0 server vi Hybrid workflow. We are using a reference access_token and have implemented Front Channel Logout and are working through RP and OP logout and are not seeing the OP Logout Page inserting the front_channel_logout_uri's into the page for clients if the RP did not Authenticate or interact with the OP in the current browser session.

Scenario:
1) fresh browser session. User is authenticated with OP and RP authenticates for Client A. Go to OP Logout page and do logout - page has front_channel_logout_uri's inserted and RP receives Front Channel Logout request. 

 2) Do (1), but don't do OP Logout. close browser and re-open (continue session) - access_token (reference token) still valid based on expiry time test (access_token expiration time returned by Authentication interaction in (1)). RP authenticates the user into the RP's client app without interaction with OP as token valid. Go to OP Logout page and do logout - page does NOT insert front_channel_logout_uri's.

I'm guessing the RP needs to at least validate the ref access_token in each browser session with the OP via the introspection endpoint, but I'd rather understand what are the options/actions. The spec for the logout page insertion says nothing about actions required by the RP for this scenario.

**Comment by neiljthomson** [comment]
The culprit is the IdP/OP cookie timeout (which I presume contains the user id/auth status and which RP's have logged in) has the default cookie handling, which has a browser session lifetime in the IdSvr4 code.

So of course, on close/open of the browser, the IdP/OP has forgotten the user and RP's which are logged in and therefore the 'front channel_logout_uri's are not generated.

A case of too many tokens/cookies where their lifetime/expiry are interdependent without that being highlighted in some of the specs (e.g. Front Channel Logout)

**Comment by brockallen** [comment]
All set then? We can close this?

**Comment by neiljthomson** [comment]
Yes, in future I'll indicate that in my comment.... 
Thank you,
