### ISSUE TITLE
Possible stability issue with HttpClient

### ISSUE THREAD

**Issue by doxakis** [IdentityServer/IdentityServer4#2814]
### Issue / Steps to reproduce the problem
Creating a new BackChannelHttpClient for every request could bring instability (BackChannelHttpClient 
inherits of HttpClient)

Source:
https://github.com/IdentityServer/IdentityServer4/blob/63a50d7838af25896fbf836ea4e4f37b5e179cd8/src/Configuration/DependencyInjection/BuilderExtensions/Core.cs#L127

Transient lifetime services are created each time they're requested. In order word, a new instance is created for each request and according to https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/, it is recommended to reuse one instance shared for the entire application.

Possible fix:
`AddTransient` could be changed to `AddSingleton`.

**Comment by leastprivilege** [comment]
Now that we are on 2.1 - we should use the HttpClientFactory wherever we need an HttpClient...

**Comment by leastprivilege** [comment]
How about we expose a `BackChannelHttpClient` name property on our options - if set we resolve a named HTTP client from the factory (if not - just a plain one). This would allow custom config on the client (like proxy settings etc..).

**Comment by doxakis** [comment]
It could be an idea.

If there is nothing set then, you could cache the instance if you have to create one.

I don't know what is best way to address the issue.

I just wanted to let you know. Feel free to fix it how you prefer. :)

**Comment by brockallen** [comment]
If we add a ctor to `BackChannelHttpClient` that accepts a `HttpClient` then you can use the factory approach. If not, then it falls back to current behavior. In 3.0 we'd rework to be all factory driven. Thoughts?

**Comment by leastprivilege** [comment]
Singleton instances are not recommended because of the DNS caching issue.

**Comment by cornem** [comment]
Certainly. That's why I seconded Brock's suggestion to implement `HttpClientFactory`, which has been designed to solve that issue.

However, using transient `HttpClient` instances isn't recommended either, so I'm definitely looking forward to a version which allows the use of the factory.

**Comment by brockallen** [comment]
> being able to inject a client would help for now.

You can now -- change the lifetime of the `BackChannelHttpClient` in DI to be singleton.

**Comment by brockallen** [comment]
Tracking here: #2859
