### ISSUE TITLE
Identity server creating Implicit Flow response for hybrid client.

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#2815]
### Issue / Steps to reproduce the problem

I have an Identity server 4 application.  Which is called by a Asp .net MVC application using a hybrid client.   I just spotted something strange in my logs and it has me curious.

Why would it create a `Creating Hybrid Flow` response and then change its mind and create an `Creating Implicit Flow` response?   We have had a few issues with login on this application and i am wonder if this has something to do with it.

### Relevant parts of the log file

    dbug: MYIds.IdentityServer.Services.ProfileService[3210]
          User IsActive [User: sub: 21248582] [Active: True]
    dbug: IdentityServer4.Services.DefaultConsentService[0]
          Client is configured to not require consent, no consent is required
    dbug: IdentityServer4.ResponseHandling.AuthorizeResponseGenerator[0]
          Creating Hybrid Flow response.
    dbug: IdentityServer4.EntityFramework.Stores.PersistedGrantStore[0]
          J4nh7ZtWP0/FJd6q5vzD/C1uHcMXhJal2FGQ2JFDjeA= not found in database
    dbug: IdentityServer4.ResponseHandling.AuthorizeResponseGenerator[0]
          Creating Implicit Flow response.

I can verify that `J4nh7ZtWP0/FJd6q5vzD/C1uHcMXhJal2FGQ2JFDjeA=` is actually in the database and was not expired at the time of the call.

**Comment by leastprivilege** [comment]
Describe "few issues".

**Comment by leastprivilege** [comment]
Looking at the source code - this logging is totally fine. Hybrid is a combination of code and implicit. Hence the log entries.

**Comment by leastprivilege** [comment]
In that case - don't describe the issues to me :p

**Comment by LindaLawton** [comment]
"Fiew issues " => Every five minutes users are being redirected to the identity server then back to the MVC application. (As they are still logged in)

Now and then it fails and we get the giant nonce cookie.

**Comment by leastprivilege** [comment]
Well - this sounds unrelated to IdentityServer.

**Comment by leastprivilege** [comment]
I will close this because I don't see an issue (besides slightly confusing debug logging).

**Comment by LindaLawton** [comment]
The question was just about the (slightly confusing debug logging).   Not related to the weird issues with our legacy MVC application acting like a drunken idiot.

Thanks for explaining the logging :)
