### ISSUE TITLE
Need to know what Type of IEndpointResult the service is returning

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#2818]
**Is your feature request related to a problem? Please describe.**
I am trying to track client requests for the purposes of rate-limit denial and usage billing.  To do this I replaced the IdentityServerMiddleware with a custom one that does;

1. preprocessing for rate-limit denials - Works fine
2. Let IdentityServer do its thing
3. Evaluate the result, prior to letting it execute and start the response.  This is for billing where I only track successful calls.

BTW:  I am happy that the IdentityServerMiddleware I replaced has very little code in it.  I don't like swapping out something this significant, but its small enough to keep it up to date.

If I let the IdentityServer middleware start executing, it starts the response, which denies writes to the response header.   Its a chicken and egg thing.  I need to know the StatusCode you plan to write for me to do stuff and write my own data in the response header.

**Describe the solution you'd like**
At the moment all your results implement IEndpointResult, which gives me no clue as to what its actually going to do.  I loves my abstractions, but this is too much ;)

A non-breaking change is to make a bunch of these;
```
public interface ITokenErrorResult: IEndpointResult{};
public interface IBadRequestResult: IEndpointResult{};
etc.

where TokenResult would look like this;
    public interface ITokenEndpointResult : IEndpointResult
    {
    }

    internal class TokenResult : ITokenEndpointResult{}

And my Check,
    var tokenResult = result as ITokenEndpointResult;
    var error = tokenResult == null;
```

**Describe alternatives you've considered**
One could add a Type to IEndpointResult where each implemenatation would set it in its constructor.
This might not be a breaking change either as we would be adding to the interface vs taking away something.  

**Additional context**

**Comment by leastprivilege** [comment]
Maybe this is the point where you should just fork IdentityServer and do your own ;)

**Comment by ghstahl** [comment]
Are you trying to ruin my Thanksgiving holiday!
So I had to make 2 changes to identityserver4 2.3.0 to make it work with my custom extension grants.
Both are non-breaking changes.
1. This Thing with all the IEndpointResult(s)  Same change just a lot of them
2. Add virtual to the ScopeValidator class methods so that I can inherit and override.
     AreScopesValidAsync
     AreScopesAllowedAsync
     In particular.

Please throw me a bone here, a turkey bone that is :)

**Comment by brockallen** [comment]
Given that we will soon re-implement using endpoint routing, I will close this since I think it will become moot. Sorry. :/
