### ISSUE TITLE
Update to Bootstrap 4

### ISSUE THREAD

**Issue by vanillajonathan** [IdentityServer/IdentityServer4#2819]
Update templates from Bootstrap 3 to use Bootstrap 4.

**Comment by leastprivilege** [comment]
Great idea - do you want to work on it?

**Comment by vanillajonathan** [comment]
No, but here is some migration documentation:
https://getbootstrap.com/docs/4.1/migration/

Any work would be done in the IdentityServer4.Quickstart.UI project or the IdentityServer4.Templates or both?

**Comment by leastprivilege** [comment]
I think you misunderstood the OSS thing then.

**Comment by brinehart** [comment]
I would be happy to contribute. Should I open a new issue and then send in a PR once it's complete or how does this team prefer to do it?

**Comment by brockallen** [comment]
yea, PR is fine. you will have to update the main css, but IIRC it's in less, so that's the preferred styling language for the host. if you plan to make it too different looking, then maybe show us a screen shot first.

**Comment by brinehart** [comment]
Ok. I'll try to keep to the accepted styling. How far back are we wanting to support Browserwise? 

If >= IE10 we could implement the new Bootstrap 4 flex options that would make it super responsive and bring it up to date with modern CSS3 practices.

Also, is there a reason to stick with LESS? SASS has replaced LESS in Bootstrap4 as the preferred precompiler and from what I can see so far there wouldn't be much in way of syntax that would need to change if we stuck with a `.scss` format.

**Comment by brockallen** [comment]
I'm fine with IE11. Also, please send the PR to the host folder -- we take that and then merge it into the QS repo. IOW, don't do the PR there, please. Thx
