### ISSUE TITLE
Client Credentials Flow complains "No redirect URI configured" when also allowing Authorization Code Flow

### ISSUE THREAD

**Issue by tedchirvasiu** [IdentityServer/IdentityServer4#2820]
1) I create a client and allow it both Client Credentials and Authorization Code flows.
2) I try to get a token issued from the token endpoint using grant_type=client_credentials.
3) I receive the error "invalid_client" with Identity Server complaining that "No redirect URI configured", even though it should not be required for Client Credentials Flow.
Removing Authorization Code will make it work again.

I have tried both using IdentityModel and making a raw POST request, with the same result.

I have made a minimal repo to reproduce the problem:
https://github.com/tedchirvasiu/identity-server-4-client-credentials-issue

![clientcredentialsvsauthorizationcode](https://user-images.githubusercontent.com/13540243/48869350-918c8800-ede5-11e8-9c98-f238cf02b527.PNG)

I am using .Net Core 2.1, IdentityServer4 2.3.0, IdentityModel 3.10.1.

Thank you!

**Comment by leastprivilege** [comment]
Yes - we turned on config validation in 2.3.

Your client is configured for using code flow - but you have not configured a redirect URI - this is required. Any reason you haven't configured one?

**Comment by TedProsoft** [comment]
Hold on a minute,
My client is configured for using either code flow or client credentials.

![ss1](https://user-images.githubusercontent.com/33120043/48889622-22438200-ee3f-11e8-8b26-db94c7debea7.PNG)

However, the request i'm making is client credentials:

![ss2](https://user-images.githubusercontent.com/33120043/48889648-39826f80-ee3f-11e8-81ea-33f29953d8e1.PNG)

Why is a redirect URI required when trying to use client credentials flow explicitly? Shouldn't a client be able to use both client credentials and code? Maybe I'm missing something?
Thanks.

**Comment by leastprivilege** [comment]
It is not about which flow you are using - when the client gets loaded, the configuration gets validated. And according to our default validator, the config is invalid.

So my question again - why do you have code flow configured without a redirect URI?

**Comment by TedProsoft** [comment]
Oh, alright, I see now... Then it's my bad. I was just setting it up, added all the future supported grant types, but I was implementing them one by one. I started with client credentials so I haven't fully configured the rest, I wasn't expecting it to validate code flow when only requesting client credentials.
