### ISSUE TITLE
Revoke TLS settings changes

### ISSUE THREAD

**Issue by nandhu** [IdentityServer/IdentityServer4#2821]
**Is your feature request related to a problem? Please describe.**
Build.ps1 script has changed the TLS settings and some the applications(outlook) are not working. 

**Describe the solution you'd like**
should have option to revoke those changes.

**Describe alternatives you've considered**
you can provide the another script to revoke those changes.

**Comment by nandhu** [comment]
I believe the powershell script will change it in system level. After executed the script my outlook was stopped working.

**Comment by leastprivilege** [comment]
I don't believe that. Have a look if you find some docs that support this statement.

**Comment by leastprivilege** [comment]
any update?
