### ISSUE TITLE
Not able to connect to userinfo endpoint to read claims

### ISSUE THREAD

**Issue by nidhilogic** [IdentityServer/IdentityServer4#2825]
This is how my config.cs file looks on IS4

Part 1 https://puu.sh/C7zhg/5bf6017551.png

Part 2 https://puu.sh/C7zh0/a65723cdbb.png

This is my client and this is how I call IS4 userInfo endpoint https://puu.sh/C7zhM/772febf446.png

Here is the error: https://puu.sh/C7zka/3c5b7a55d7.png

Can someone please help?

**Comment by leastprivilege** [comment]
You are using the client credentials grant type. In this grant type there is no user, and thus you can't call userinfo.
