### ISSUE TITLE
Consider PersistentGrantSerializer to be singleton

### ISSUE THREAD

**Issue by oslava** [IdentityServer/IdentityServer4#2826]
**DefaultGrantStore<T> has bad performance because of PersistentGrantSerializer**
Working with presistent grants (authorization code or tokens) is very slow. It takes at least 5 mileseconds for serialization/deserialization of grants. My storage is even faster than serialization, so this latency is too expensive for me.

**PersistentGrantSerializer should be a singleton**
PersistentGrantSerializer uses custom ContractResolver and Converters. I guess some metadata is cached inside instances so when PersistentGrantSerializer is singleton it works much faster.

I wrote some [benchmarks](https://github.com/oslava/IdentityServerBenchmarks) to test this: 
![bm](https://user-images.githubusercontent.com/6390765/48983941-01b54980-f117-11e8-8ad6-cfd73437dc5f.jpg)

**5ms** with new PersistentGrantSerializer against **0.02ms** with the same instance of PersistentGrantSerializer

**Comment by leastprivilege** [comment]
We'll look into it. thanks!

**Comment by brockallen** [comment]
Good find -- we changed it to static. Thanks!
