### ISSUE TITLE
DeviceCodeLifetime not null

### ISSUE THREAD

**Issue by randyjeppesen** [IdentityServer/IdentityServer4#2827]
Clients table, DeviceCodeLifetime is not null.  Documentation says: Lifetime to device code in seconds (defaults to 300 seconds / 5 minutes).  Should DeviceCodeLifetime be nullable since the default is 300?

**Comment by scottbrady91** [comment]
Yep, in the same style as the other token lifetimes (e.g., IdentityTokenLifetime)
