### ISSUE TITLE
Events for skipping consent screen when already consented

### ISSUE THREAD

**Issue by MJMortimer** [IdentityServer/IdentityServer4#2829]
I can see there have been events added for when consent is granted or denied but I can't see anything regarding events when not requiring consent because it's been previously granted and set to be remembered. 
I'd like to gather metrics for when a user logs into a client that they've already granted consent to.

Is there a way that I can surface events for this case?

**Comment by brockallen** [comment]
@leastprivilege -- you assigned this, so that means you think it's a worthwhile feature? if so, what milestone?
