### ISSUE TITLE
Q: PKCE Hybrid Flow, RedirectUri

### ISSUE THREAD

**Issue by ajtowf** [IdentityServer/IdentityServer4#283]
When using pkce hybrid flow for windows universal native apps, is it sane to need to add client redirect uri:s? The one we get by calling: 
    
    WebAuthenticationBroker.GetCurrentApplicationCallbackUri().AbsoluteUri => ms-app://s-1-15-2...

I get unauthorized client if I don't add it but it feels wierd, won't that be unique per client?

Or am I misunderstanding something fundamental here, we've authenticated ourselves with user/pass AND we've provided a clientid/secret from the app. Why do we need the redirectUri for the native client?

**Comment by brockallen** [comment]
Dom would know better, but my understanding is that those App IDs/GUIDs are unique to the app. So, yes, it's unique per client (but not per install of the client).

**Comment by ajtowf** [comment]
That really doesn't sound ideal for a native app flow, you'd need to provision each client, not optimal if you plan to distribute the app through app store, right?

My understanding was that hybrid with proof key/hybrid with pkce is the best choice for native apps so this doesn't sound right. Is user/pass more what I'm looking for?

**Comment by leastprivilege** [comment]
That ms-app id is the unique identifier for the app in the store. Iow all downloads of your app will use the same id.

**Comment by ajtowf** [comment]
Cool, thanks, it makes a lot more sense in that case!
