### ISSUE TITLE
ClientCredentialsHelper should check if ClientId or ClientSecret are not yet added to request

### ISSUE THREAD

**Issue by mantasaudickas** [IdentityServer/IdentityServer4#2832]
Hello,

I am using HttpClientTokenRequestExtensions from IdentityServer4 v2.3.0.
For method RequestTokenAsync I am passing clientId and clientSecret by my self like:
```
var parameters = new Dictionary<string, string>
{
    {"grant_type", "delegation"},
    {"client_id", clientId},
    {"client_secret", clientSecret},
    {"token_hint", userAccessToken},
};

var tokenResponse = await _client
    .RequestTokenAsync(new TokenRequest
    {
        Address = tokensEndpoint,
        ClientId = clientId,
        ClientSecret = clientSecret,
        GrantType = "delegation",
        Parameters = parameters
    }, cancellationToken)
    .ConfigureAwait(false);
```

I am aware that I am duplicating stuff.. however having the code like above will throw exception:
```
An item with the same key has already been added. Key: client_id
```

Short investigation showed that ClientCredentialsHelper does not check if parameters are already added which causes this exception.

However its fine with GranType, which is checked and added in RequestTokenAsync method:
```
if (!request.Parameters.ContainsKey(OidcConstants.TokenRequest.GrantType))
{
    request.Parameters.AddRequired(OidcConstants.TokenRequest.GrantType, request.GrantType);
}
```

I guess should be the same also with other arguments.

**Comment by leastprivilege** [comment]
Wrong repo - could you please open here:
https://github.com/IdentityModel/IdentityModel2
