### ISSUE TITLE
broken URL link in Docs "Creating the client"

### ISSUE THREAD

**Issue by hanslai** [IdentityServer/IdentityServer4#2834]
### Issue / Steps to reproduce the problem
In http://docs.identityserver.io/en/latest/quickstarts/1_client_credentials.html#creating-the-client  The text reads:

"**Creating the client**

The last step is to write a client that requests an access token, and then uses this token to access the API. For that, add a console project to your solution (see full code [here](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/1_ClientCredentials/src/Client/Program.cs))."

The link "https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/1_ClientCredentials/src/Client/Program.cs" is broken. It should be in the master branch I believe.

The correct URL should be: 
https://github.com/IdentityServer/IdentityServer4.Samples/blob/master/Quickstarts/1_ClientCredentials/src/Client/Program.cs  

I can do a PR if needed.

Thanks

**Comment by leastprivilege** [comment]
yes please. Could you also check all the other links - in essence the release branch is going aways - and master should be used. thanks!

**Comment by hanslai** [comment]
Sure, I am following the quickstarts now, submit PRs once I found them.
