### ISSUE TITLE
Custom ResetPassword page not working in IdentityServer3

### ISSUE THREAD

**Issue by YousafKhan0800** [IdentityServer/IdentityServer4#2841]
I am using CustomViewService in identity server 3 and I needed to add reset password page. I followed the solution provided here: https://stackoverflow.com/questions/31046208/identity-server-v3-custom-page-reset-password . But, Identity Server is not able to find resetPassword.html page even though I provided it in "templates" folder and it keeps returning 404 error "No webpage was found for the web address: http://localhost:44333/core/resetPassword?signin=b3253f1ef659cffe9165c7c6b134715a". Any help will be appreciated.

**Comment by leastprivilege** [comment]
This repo is about IdentityServer4.

**Comment by YousafKhan0800** [comment]
@leastprivilege I tried to post the issue in identityServer3's repository but it is closed. That is why I posted it here
