### ISSUE TITLE
This repo is about IdentityServer4.

### ISSUE THREAD

**Issue by YousafKhan0800** [IdentityServer/IdentityServer4#2842]
_Originally posted by @leastprivilege in https://github.com/IdentityServer/IdentityServer4/issues/2841#issuecomment-442335765_

Rep: I tried to post the issue in identityServer3's repository but it is closed. That is why I posted it here

**Comment by leastprivilege** [comment]
We don't support IdentityServer3 anymore. You can try StackOverflow. Or upgrade to v4.
