### ISSUE TITLE
AddIdentityServerAuthentication ApiSecret not work

### ISSUE THREAD

**Issue by jsoncc** [IdentityServer/IdentityServer4#2844]
Hi，There!
    I use the following code,but [ApiSecret] was not worked,whether I set the parameter，the token also can be passed validation。Why？

services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
    .AddIdentityServerAuthentication(options =>
    {
        options.Authority = "https://demo.identityserver.io";
        options.ApiName = "api1";
        options.ApiSecret = "secret";
    });

**Comment by leastprivilege** [comment]
not enough info. check the logs.
