### ISSUE TITLE
Breaking Changes from 2.2.0 to 2.3.0?

### ISSUE THREAD

**Issue by fabich** [IdentityServer/IdentityServer4#2845]
hi

After updating to 2.3.0 from 2.2.0 our application breaks:
``` 
System.Data.SqlClient.SqlException:
Invalid column name 'Created'.
Invalid column name 'DeviceCodeLifetime'.
Invalid column name 'LastAccessed'.
Invalid column name 'NonEditable'.
Invalid column name 'Updated'.
Invalid column name 'UserCodeType'.
Invalid column name 'UserSsoLifetime'.
```

do you have any information on this?

thank you for your help

**Comment by milosloub** [comment]
Same problem here

**Comment by scottbrady91** [comment]
More properties were added to the EF models. Some of these make their way up to IdentityServer, some don't.

You'll need to create a new migration.

**Comment by milosloub** [comment]
Ah, sure, just new migrations. Now it's working again, thanks!

**Comment by StevenLiekens** [comment]
This just bit me too. Please don't publish minor versions that require manual intervention when updating. @scottbrady91

**Comment by fabich** [comment]
@StevenLiekens my point exactly.

**Comment by leastprivilege** [comment]
That's how EF works. We won't do a new major release just because we are adding a field or table.

**Comment by leastprivilege** [comment]
But what we will do in the future is to add a remark to the release notes if EF requires a new migration.

**Comment by StevenLiekens** [comment]
Then also make it clear you don't follow semver all the way. Sorry for being brutal but you're breaking people's expectations by following your own versioning scheme.

**Comment by leastprivilege** [comment]
The we need to agree to disagree.

**Comment by ravero** [comment]
It took me a long time to realize the new version issue.
How do you create a migration for a third party library?

**Comment by brockallen** [comment]
> How do you create a migration for a third party library?

http://docs.identityserver.io/en/latest/reference/ef.html#database-creation-and-schema-changes-across-different-versions-of-identityserver

**Comment by fabich** [comment]
> http://docs.identityserver.io/en/latest/reference/ef.html#database-creation-and-schema-changes-across-different-versions-of-identityserver

> We also publish sample SQL scripts for the current version of the database schema.

[IdentityServer4.EntityFramework.Storage](https://github.com/IdentityServer/IdentityServer4.EntityFramework.Storage/tree/dev/migrations/SqlServer/Migrations) is archived and hasn't been updated for over five months

**Comment by brockallen** [comment]
@fabich the docs have an easy to use "Edit on Github" button to submit PRs
