### ISSUE TITLE
Adjust "Authentication scheme Bearer is configured for IdentityServer, but it is not a scheme that supports signin (like cookies)"

### ISSUE THREAD

**Issue by quanterion** [IdentityServer/IdentityServer4#2846]
I got IdentityServer validation error on startup "Authentication scheme Bearer is configured for IdentityServer, but it is not a scheme that supports signin (like cookies). Either configure the default authentication scheme with cookies or set the CookieAuthenticationScheme on the IdentityServerOptions." from https://github.com/IdentityServer/IdentityServer4/blob/63a50d7838af25896fbf836ea4e4f37b5e179cd8/src/Configuration/IdentityServerApplicationBuilderExtensions.cs#L105

However I don't need signin since I use ROPC flow. Is it possible to disable this validation error?

PS: I'm using IdSrv 2.3, everything works ok despite this error but it pollutes log and error tracking software

**Comment by alighanem** [comment]
I did not have this message with version 2.2.0

**Comment by brockallen** [comment]
Not right now, no. It's just a startup message, as well.

**Comment by brockallen** [comment]
Also, you could set the CookieAuthOptions on our options class and put in a dummy cookie handler.

**Comment by alighanem** [comment]
Maybe I do not understand but why do we have to set this option? Why do we have this error? Can you explain more?
Thank you in advance,

**Comment by quanterion** [comment]
> Also, you could set the CookieAuthOptions on our options class and put in a dummy cookie handler.
Can you explain where should I set it?

**Comment by brockallen** [comment]
services.AddAuthentication().AddCookie("dummy")
services.AddIdentityServer(options=>options.Authentication.CookieAuthenticationScheme="dummy"})

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by seanmars** [comment]
Same question. If this is not necessary, why show this message even with `fail` level?

**Comment by artchess** [comment]
This Fail is very confusing.

**Comment by leastprivilege** [comment]
It is a fail because for 99% of all IS use-cases, this is an invalid configuration.

**Comment by brockallen** [comment]
>> It is a fail because for 99% of all IS use-cases, this is an invalid configuration.
> Is there means IIS?

He means co-hosting IdentityServer and your API that's protected by IdentityServer.

**Comment by leastprivilege** [comment]
IS = IdentityServer

**Comment by MrGroovy** [comment]
> It is a fail because for 99% of all IS use-cases, this is an invalid configuration.

Why?

**Comment by MrGroovy** [comment]
I still dont understand what the error is? Please explain.

**Comment by artchess** [comment]
> I also just experienced this error when updating to 2.3. I agree that the fact that this now indicates an error at startup which signals log monitoring alerts every time the application runs is quite jarring especially since this is just a minor version update. I would not expect to encounter this nor the need to set a dummy cookie value when using a supported use case.

think the same.

**Comment by cremor** [comment]
I get the same error message. I don't need signin since my API only supports the OAuth 2.0 client credentials flow. How do I get rid of that error message?

@leastprivilege Please reopen this issue.

**Comment by SidShetye** [comment]
@leastprivilege @brockallen : This user report is legitimate and points to an incorrect assumption by IS. 

Having folks ignore security warnings isn't good and adding unnecessary auth related code adds to confusion, so seems like should be reopened, right? Any reason it's still closed despite multiple confirmations/requests by folks above? Original report even points to the offending line. 

Am I missing something?

**Comment by leastprivilege** [comment]
We can change the wording - but since for 90% of the time this is an invalid configuration. Some message will be shown.

**Comment by brockallen** [comment]
Changed to Informational.

**Comment by SidShetye** [comment]
I agree that the most users won't/shouldn't be in this configuration, switching to info or warning seems like a good balance. Thanks

________________________________
