### ISSUE TITLE
Trying to setup Windows Authentication for Identity server. 

### ISSUE THREAD

**Issue by pranavdhundhia** [IdentityServer/IdentityServer4#2847]
Returns following issue after setting up identity server with Windows Authentication.
Steps I followed as per Identity server  docs defined in following link : http://docs.identityserver.io/en/latest/topics/windows.html

and added  following configuration in web config
<system.webServer>
	<security>
                <authentication>
                    <anonymousAuthentication enabled="true" />
                    <windowsAuthentication enabled="true" />
                </authentication>
            </security>
</system.webServer>

I get following error trying to access server
![image](https://user-images.githubusercontent.com/3126366/49207632-7fa97700-f3db-11e8-9215-b5d7d4119f5d.png)

Please correct me with steps to make windows authentication available on identity server.

**Comment by leastprivilege** [comment]
Something is wrong with your web.config - at least that's what the error indicates.
