### ISSUE TITLE
Getting a 400 error on ajax requests. Antiforgery token for a different claims-based user than the current user

### ISSUE THREAD

**Issue by alexssandr1992** [IdentityServer/IdentityServer4#2849]
Hi,

I use ASP.NET CORE 2.1

Configuration:

      public void ConfigureServices(IServiceCollection services)
      {
            services.AddIdentity<User, Role>(options =>
            {
            })
            .AddEntityFrameworkStores<WebSiteDataContext>()
            .AddClaimsPrincipalFactory<CustomClaimsPrincipalFactory>()
            .AddDefaultTokenProviders();

           services.AddIdentityServer()
                .AddDeveloperSigningCredential() 
                .AddInMemoryPersistedGrants()
                .AddInMemoryIdentityResources(
                    new List<IdentityResource>
                    {
                           new IdentityResources.OpenId(),
                           new IdentityResources.Profile()
                    })
                .AddInMemoryApiResources(new List<ApiResource> { new ApiResource(systemApiName) })
                .AddInMemoryClients(
                    new List<Client>
                    {
                           new Client
                           {
                               ClientId = clientId,                                           
                               ClientName = clientName,                                     
                               AllowedGrantTypes = GrantTypes.HybridAndClientCredentials
                                   .Concat(GrantTypes.ResourceOwnerPassword).ToList(), 
                               ClientSecrets = { new Secret(secretKey.Sha256()) },                       
                               AllowedScopes =
                               {
                                   IdentityServerConstants.StandardScopes.OpenId,
                                   IdentityServerConstants.StandardScopes.Profile,
                                   systemApiName
                               },
                               AllowAccessTokensViaBrowser = true,
                               AlwaysSendClientClaims = true,
                               AlwaysIncludeUserClaimsInIdToken = true,
                               AccessTokenLifetime = 3600 * 24          
                           }
                    }
                )
                .AddAspNetIdentity<User>()            
                .AddProfileService<ProfileService>();

            services.AddAuthentication(options => options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = authorityEndPoint;
                    options.ApiName = systemApiName;
                    options.RequireHttpsMetadata = false;
                    options.NameClaimType = "name";
                    options.RoleClaimType = "role";
                });
       }

       public void Configure(IApplicationBuilder app, IHostingEnvironment env, IAntiforgery antiforgery)
       {
            app.UseIdentityServer();
            app.Use(next => ctx =>
            {
                var tokens = antiforgery.GetAndStoreTokens(ctx);
                ctx.Response.Cookies.Append("XSRF-TOKEN", tokens.RequestToken,
                    new CookieOptions() { HttpOnly = false });
                return next(ctx);
            });
        }

And use Antiforgery token validation same as in https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-2.1

But when I send header  'Authorization' with token in ajax request, than I have error

AntiforgeryValidationException: The provided anti forgery token was meant for a different claims-based user than the current user

If I remove header  'Authorization'  or attribute [ValidateAntiForgeryToken], than no errors.

**Comment by brockallen** [comment]
>         services.AddAuthentication(options => options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme)

This line is going to cause you problems.

**Comment by alexssandr1992** [comment]
If I remove this string 
options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme
than I can't pass User in HttpContext.
I use SPA application, so in Header 'Authorize' I pass access token

**Comment by alexssandr1992** [comment]
But it seems you are right. if I temporarily remove the string, the request will pass.
What can be solution for my problem?

**Comment by alexssandr1992** [comment]
it's can help me?

In a fiew forums I find advice to use services.AddCors

https://forums.asp.net/t/2134547.aspx?What+is+the+correct+implementation+of+middleware+that+validates+a+custom+XSRF+TOKEN+

but I don't understand how it must be work

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
