### ISSUE TITLE
Support versioning for the token endpoint

### ISSUE THREAD

**Issue by alaeddineG** [IdentityServer/IdentityServer4#2850]
We are moving from the Owin implementation of oAuth to use IdentitySergver4 instead (Thank you by the way  for the good work 👍  )
In Microsoft.Owin.Security we can setup different token endpoint. for  each one it's own provider (for the different Grant ) where you can setup different logic (in case there is breaking changes for example let say). So basically you can add as match token endpoint for each one it's version and logic like so :

```
app.UseOAuthAuthorizationServer(new OAuthAuthorizationServerOptions
	{
		TokenEndpointPath = new PathString(Paths.V1.TokenPath),
		Provider = new Providers.V1.OAuthProvider(),
		RefreshTokenProvider = new Providers.V1.RefreshTokenProvider(),
	});
	
app.UseOAuthAuthorizationServer(new OAuthAuthorizationServerOptions
	{
		TokenEndpointPath = new PathString(Paths.V2.TokenPath),
		Provider = new Providers.V2.OAuthProvider(),
		RefreshTokenProvider = new Providers.V2.RefreshTokenProvider(),
	});
```

Is there a way to to that with IdentityServer4 ? if not is it anyhow planned or probable ?
I've been searching the docs and some other threads and the only thing i found that can help me nearly achieve that is :

https://stackoverflow.com/questions/39186533/change-default-endpoint-in-identityserver-4

```
var builder = services.AddIdentityServer()
	.AddDeveloperSigningCredential()
	.AddInMemoryClients(InMemoryOAuthConfig.GetClients())
	.AddInMemoryApiResources(InMemoryOAuthConfig.GetApiResources());

builder.Services
	.Where(service => service.ServiceType == typeof(IdentityServer4.Hosting.Endpoint))
	.Select(item => (IdentityServer4.Hosting.Endpoint)item.ImplementationInstance)
	.ToList()
	.ForEach(item =>
	{
		item.Path = item.Path.Value.Replace("/connect", "/v1");
	});
```

Im not 100% convinced of the fix and again I cannot add another token endpoint, only a custom one (Since IdentityServer4.Endpoints.TokenEndpoint is internal ) and there I will have to code all the validation by myself (duplicate the code in IdentityServer4.Endpoints.TokenEndpoint ? )

The comment on the same thread says that is not possible right now (August 2016)
> Right now you cannot change the endpoint URLs of the protocol endpoints. If you think this is needed, please open an issue on github.

Is it possible now ?

**Comment by brockallen** [comment]
This is not possible, mainly because the DI system is shared (by default) across all middleware. Microsoft says at some point they will support a "multi-tenancy" feature, but i'm not holding my breath. I know there are some OSS projects that provide workarounds, but you'd have to look into it yourself.

**Comment by alaeddineG** [comment]
Thank you @brockallen  for your quick response.

The solution I was talking about to loop over the Endpoints and override the Path does it contain any potential risk ? Any problem that you can foresee ?

> I know there are some OSS projects that provide workarounds, but you'd have to look into it yourself.

Any example that you can throw to me ? :)

**Comment by brockallen** [comment]
>> I know there are some OSS projects that provide workarounds, but you'd have to look into it yourself.
> 
> Any example that you can throw to me ? :)

I think @PinpointTownes has one.

**Comment by alaeddineG** [comment]
I believe you where talking about https://github.com/aspnet-contrib/AspNet.Hosting.Extensions  
Thank you @brockallen
