### ISSUE TITLE
Listing registered users from IdentityServer in another application

### ISSUE THREAD

**Issue by zinov** [IdentityServer/IdentityServer4#2851]
I have a requirement to create an admin UI where I need to list all users registered on IdentityServer to start assigning permissions and roles. This application internally uses PolicyServer, but as a superadmin user, I would need to see all users registered on IdentityServer. Here IdentityServer is responsible for authentication and the other application that uses PolicyServer is responsible for the authorization.

Which is the correct way to proceed:
1- This admin UI application should be connected to the same database that IdentityServer uses to get all the users?
2 Or should I need to extend IdentityServer on this way?: 
http://docs.identityserver.io/en/latest/topics/add_apis.html

I followed this issue here: 
https://github.com/IdentityServer/IdentityServer3/issues/2607
 but still, it is not clear for me how to proceed on the question above.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by remi0411** [comment]
> I have a requirement to create an admin UI where I need to list all users registered on IdentityServer to start assigning permissions and roles. This application internally uses PolicyServer, but as a superadmin user, I would need to see all users registered on IdentityServer. Here IdentityServer is responsible for authentication and the other application that uses PolicyServer is responsible for the authorization.
> 
> Which is the correct way to proceed:
> 1- This admin UI application should be connected to the same database that IdentityServer uses to get all the users?
> 2 Or should I need to extend IdentityServer on this way?:
> http://docs.identityserver.io/en/latest/topics/add_apis.html
> 
> I followed this issue here:
> [IdentityServer/IdentityServer3#2607](https://github.com/IdentityServer/IdentityServer3/issues/2607)
> but still, it is not clear for me how to proceed on the question above.

Hello @zinov , I've the same problem, can you contact me ? You'll find my email on my github profile page, thank you
