### ISSUE TITLE
Broken link in Docs "Scopes and Clients Configuration"

### ISSUE THREAD

**Issue by hanslai** [IdentityServer/IdentityServer4#2853]
### Issue / Steps to reproduce the problem
The [Config.cs](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/5_HybridFlowAuthenticationWithApiAccess/src/QuickstartIdentityServer/Config.cs) link is broken in[ Scopes and Clients Configuration
](http://docs.identityserver.io/en/latest/quickstarts/6_aspnet_identity.html#scopes-and-clients-configuration)

**Comment by leastprivilege** [comment]
merged
