### ISSUE TITLE
IdentityServer4 using .NET Framework 4.5.2 Token Validation

### ISSUE THREAD

**Issue by UMANGAWASTHY** [IdentityServer/IdentityServer4#2855]
How to use IdentityServer4 using .NET Framework 4.5.2 in ASP.NET MVC 5 (not ASP.NET Core). Any example or tutorial will be helpful. I follow the IdentityServer3 but lots of missing components.

I ask this question because I cannot find some example. Actually, I already build the entire application based on .NET 4.6.1, and i m using Identity Server 4. 

Getting Unauthorized on AccessToken Validation in API calls

**Comment by leastprivilege** [comment]
IdentityServer4 itself requires ASP.NET Core which requires either .NET Core 2.x or .NET 4.6.1 or higher.

If you question is about clients - well - you need an OpenID Connect client library. For MVC 5 that would be Katana and its OIDC middleware.

**Comment by gilm0079** [comment]
@leastprivilege - from  your statement about about dependencies. Does that mean the IdentityServer4.AccessTokenValidation nuget only needs Framework 4.6.1 or higher?  When I try to install that package in my 4.6.1 project it wants to put around 20 aspnetcore related dependencies in as well.  Not sure if that is how it is supposed to work.  I'm not too clear on how the mixing of Framework and Core is supposed to work.

Or do I need to stick with IdentityServer3.AccessTokenValidation in my Framework 4.6.1 project?  Thanks in advance!

**Comment by leastprivilege** [comment]
IdentityServer4.AccessTokenValidation is middleware for ASP.NET Core - are you using that?

**Comment by gilm0079** [comment]
No. My project is .NET Framework 4.6.1 not AspNetCore.  I was confused by your statement above that IdentityServer4 could target AspNetCore 2.x or Framework 4.6.1.

We use IdentityServer4 as a separate site to run the IDP.  This client app is Framework 4.6.1 (not core) and we have been using IdentityServer3.AccessTokenValidation in it.  I was just hoping there was a newer package we could use in a non-core project as the IdentityServer3.AccessTokenValidation has max version dependencies that make it hard to keep other nuget packages up-to-date.  My workaround for nuget upgrades has been to remove the IdentityServer3.AccessTokenValidation nuget package from my project, upgrade the other packages, then install IdentityServer3.AccessTokenValidation again with the IgnoreDependencies flag.

Maybe I'm doing something wrong. What is the proper way to continue to use a nuget for AccessTokenValidation in a non-core application?  I thought I had to continue to use the IdentityServer3 version.

**Comment by leastprivilege** [comment]
I know it is confusing - but

* IdentityServer4 (and all the satellite packages) require ASP.NET Core 2.1.
* ASP.NET Core 2.1 runs on both .NET Core 2.1 and .NET Framework 4.6.1 and higher

**Comment by gilm0079** [comment]
ok. I understand what you were saying.  We are running ASP.NET (not core) with Framework 4.6.1 so it is not compatible with IdentityServer4 packages.

Is IdentityServer3.AccessTokenValidation still the nuget package to use in a ASP.NET (not core) application?  

Would it be possible to get a new nuget version published that is allowed to reference higher dependent versions?  I think this package references IdentityModel which also has max dependency versions on some core packages.

**Comment by leastprivilege** [comment]
IdentityServer3.AccessTokenValidation is targeting Katana 3.x - so this is still the right package.

We also stopped supporting all IdentityServer3 packages - if you want us to do any work on that, that would be part of a support contract. If you want to maintain it yourself, feel free to clone the repo.
