### ISSUE TITLE
How to populate LastAccessed property for Client and Resources

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer4#2860]
Could you please recommend some right place - where is it possible to populate `LastAccessed` property for Client and Resources?
I can't find any internal implementation.
Thanks!

**Comment by brockallen** [comment]
We don't set that ourselves, but your implementation could decide to use those from anywhere you deem appropriate.

**Comment by brockallen** [comment]
We deliberately did not add that. We designed IdentityServer (by default) to have read-only access to the configuration store. Someone else on the issue tracker asked for the LastAccessed properties so they could do it themselves. So it's there for you to do with however you want.
