### ISSUE TITLE
Integration test for micro service is not support

### ISSUE THREAD

**Issue by jingliancui** [IdentityServer/IdentityServer4#2861]
sample code:
[IdSample.zip](https://github.com/IdentityServer/IdentityServer4/files/2637031/IdSample.zip)

Hi , I am now try use the new asp.net core [Integration test](https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-2.1) feature with identity server 4.

two server test together simulated 2 micro service,one is mvc client,one is identity server:
```
public class AccountTest: 
        IClassFixture<IdentityApiApplicationFactory<Startup>>,
        IClassFixture<WebApplicationFactory<IdSampleMVC.Startup>>
```

and if you run or debug the test
you will found that  `mvcClient.GetAsync("/home/test");` can not connect to the url of `idApiFactory.Server.BaseAddress = new Uri("https://idserverlocalhost");`'

so ,I still didn't know how to do these for 2 Microsoft service use the asp.net nore new integration test feature .

**Comment by fuzzzerd** [comment]
I also have a sample that reproduces this issue when Identity Server is hosted in the same project as the Web API: https://github.com/IdentityServer/IdentityServer4/issues/685#issuecomment-432389815

**Comment by fuzzzerd** [comment]
@leastprivilege I was not aware of that; however, I'm not sure if the issue I'm having is the same as this one and/or the one solved by https://github.com/devdigital/IdentityServer4TestServer. 

I can't tell if I'm doing something incorrectly with my IdentityServer4 setup/config or if what I'm trying to do simply isn't possible with IdentityServer4 as it is today. I will try to produce a sample that demonstrates the problem I'm having that is separate from my project and post a new issue.

**Comment by jingliancui** [comment]
@leastprivilege 
Hi ,The IdentityServer with the asp.net identity feature, so it's contain the customer code for oidc login、register atc.Then I want test the Login、register atc.

**Comment by leastprivilege** [comment]
Checkout our integration tests - they do things like that. I believe the above mentioned test framework might streamline those things, but I never tried it.
