### ISSUE TITLE
post_logout_redirect_uri not set in /Account/Logout action

### ISSUE THREAD

**Issue by developermj** [IdentityServer/IdentityServer4#2863]
### Issue / Steps to reproduce the problem
Using reference token. Trying to set a post_logout_redirect_uri for a client supplied redirect after signing out. The client settings object does have the uri set on the identity server correctly. The logout uri is not being received on the identity server side when using the interaction service .GetLogoutContextAsync(logoutId) method. When using a standard JWT token the post logout redirect uri works as expected. Is this a bug or the expected result. Thank you.

Log from logout request for reference token:
      End session request validation success
      {
        "SubjectId": "42c566cc-5022-4463-8783-dd6fe63dc4a2",
        "Raw": {
          "post_logout_redirect_uri": "http://localhost:9000/assets/loggedout.html"
        }
      }

**Comment by leastprivilege** [comment]
I am not following. At logout time you have to present the id_token - id_tokens are always JWTs.

You might be confusing that with access tokens - which could be JWTs or reference tokens.

**Comment by developermj** [comment]
To state it as a question: How do I get the post_logout_redirect_uri when doing a logout and using a reference token? I've walked through the quickstarts and stackoverflow questions. The stated method for getting the post_logout_redirect_uri while using JWT tokens does not appear to work with reference tokens.

**Comment by leastprivilege** [comment]
Again - reference tokens is a red herring here. They are not used for logout. Check the spec.

**Comment by developermj** [comment]
For a client side application, how does one get the id_token to initiate the logout when using a reference token? Is there a sample or some guidance on how to initiate a client side logout with the post_logout_redirect_uri for a reference token? To be more clear: The logout works fine even when using a reference token. The problem is that the id_token_hint is null because there isn't an id_token on the client side. My assumption is that LogoutRequest.PostLogoutRedirectUri is always null in my case because I don't have an id_token.

**Comment by leastprivilege** [comment]
use a `response_type` of `id_token token`

**Comment by developermj** [comment]
I forked the IdentityServer4.Samples repo and tried what you indicated. It does work as expected. Issue must be on my implementation of identity server 4. I'm closing the issue. Thanks for you help :)
