### ISSUE TITLE
Invalid redirect_uri but all client and server are config

### ISSUE THREAD

**Issue by liugt34** [IdentityServer/IdentityServer4#2865]
i have met an error,  in the developement ,i used ip and port line http://172.16.4.36:4201

the client send the request is 
![image](https://user-images.githubusercontent.com/8056013/49513685-c8c26500-f8cc-11e8-9066-abd245922541.png)

and the server has the logs 
![image](https://user-images.githubusercontent.com/8056013/49513731-e8598d80-f8cc-11e8-8c33-65b2d58bbb7e.png)

![image](https://user-images.githubusercontent.com/8056013/49513947-85b4c180-f8cd-11e8-8131-df378f0ee2f5.png)

and in my database
![image](https://user-images.githubusercontent.com/8056013/49513747-f3142280-f8cc-11e8-8e98-8f2e33dac133.png)

and so ,i dont know how to resolve it ? any one help?

**Comment by leastprivilege** [comment]
That's not a bug - you have a typo..

silent vs slient

**Comment by liugt34** [comment]
thank u very much ,it's a very stupid mistake.
