### ISSUE TITLE
License URL in IdentityServer4-1.0.0-rc1-update1 package is incorrect.

### ISSUE THREAD

**Issue by tkoestler** [IdentityServer/IdentityServer4#287]
Probably not the highest priority :) but I noticed that the license URL in the NuGet package is incorrect. 

The URL is https://github.com/IdentityServer/IdentityServer4/LICENSE which does not exist.  I believe it was intended to be https://github.com/IdentityServer/IdentityServer4/blob/master/LICENSE.

**Comment by leastprivilege** [comment]
thanks! fixed!
