### ISSUE TITLE
Device flow does not work in web farm deployment with PersistentGrantStore

### ISSUE THREAD

**Issue by marufbd** [IdentityServer/IdentityServer4#2870]
Identity Server4 version: 2.3.0

I am using persisted grant store with database backend and common signing credentials in my identity server application. Its running in kubernetes with two container load balanced. Oauth flow with browser app works even if token issued by one and refreshed by other.

Now with device flow, after getting the /deviceauthorize on first container, it fails when the repeated /connect/token request moves to another one.

### Issue / Steps to reproduce the problem
Deploy identity server with persisted grant store and common key signing credentials into two kubernetes pod and access with one url.
Now run the device flow client with the authorize server url, client gets device code, usercode and url with /deviceauthorize request, then when repeatedly calling /connect/token for access token after one/two calls it returns with error invalid_grant

### Relevant parts of the log file

Sorry, i coudn't get the timings along with the logs, but can be assumed container 1 logs before container 2 /connect/token is the last log. 
The sequence is:
- GET http://example.com/.well-known/openid-configuration on container 2
- GET http://example.com/.well-known/openid-configuration/jwks on Container 1
- POST http://example.com/connect/deviceauthorization on Container 1
- POST http://example.com/connect/token on Container 1
- POST http://example.com/connect/token on Container 2 : fails with Invalid device code

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://example.com/.well-known/openid-configuration/jwks
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 24.8976ms 200 application/json; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://example.com/connect/deviceauthorization application/x-www-form-urlencoded 30
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DeviceAuthorizationEndpoint for /connect/deviceauthorization
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 53.0379ms 200 application/json; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://example.com/connect/token application/x-www-form-urlencoded 173
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 42.2071ms 400 application/json; charset=UTF-8
```

Container 2 logs
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://example.com/.well-known/openid-configuration
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.1191ms 200 application/json; charset=UTF-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://example.com/connect/token application/x-www-form-urlencoded 173
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
fail: IdentityServer4.Validation.DeviceCodeValidator[0]
      Invalid device code
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.2846ms 400 application/json; charset=UTF-8
```

**Comment by scottbrady91** [comment]
Do you know what your registration of `IDeviceFlowStore` is?

**Comment by scottbrady91** [comment]
Could you check what `IDeviceFlowStore` is resolving to in your implementation?

Calling `AddOperationalStore` should register an EF version of `IDeviceFlowStore`; however, I think this registration was missing from the 2.3.0 release of the IdentityServer4.EntityFramework library. What version of the EF library are you using?

**Comment by leastprivilege** [comment]
I think we need an `AddDeviceStore` extensions method - like we have for client and resource stores as well?!

**Comment by scottbrady91** [comment]
Added in #2880.

@marufbd any update on EF version and what your `IDeviceFlowStore` dependency is currently resolving as?

**Comment by marufbd** [comment]
@scottbrady91 `IDeviceFlowStore` resolves to `Identityserver4.Stores.InMemoryDeviceFlowStore`.
And I am not using EF or aspnet identity in my project.
I implemented the following stores backed with mongodb:
`IXmlRepository`
`IPersistedGrantStore`

I am now implementing IDeviceFlowStore quickly. 
Will let you know if it works in my load-balanced container deployment.

**Comment by marufbd** [comment]
Ok, implementing IDeviceflowStore with a persistent backend and registering it in services made device flow work for web farm scenario.thanks @scottbrady91

**Comment by marufbd** [comment]
Now this one is broken in v 2.3.2

Multiple container instance requires a custom implementation for IDeviceFlowStore.

But when storing `DeviceCode`, cannot serialize the newly indroduced property:
`public ClaimsPrincipal Subject { get; set; }`

I believe, CLaimsPrincipal is not supposed to be serialized in general, rather created from some form of token.

So cannot retrieve that either on `FindByDeviceCodeAsync(string deviceCode)`.

**Comment by scottbrady91** [comment]
https://github.com/IdentityServer/IdentityServer4.Storage/blob/dev/src/Stores/Serialization/ClaimsPrincipalConverter.cs

**Comment by marufbd** [comment]
@scottbrady91 
Thanks for that, will check and update here.

**Comment by marufbd** [comment]
Serializing `ClaimsPrincipalLite` works against my mongo store.
