### ISSUE TITLE
PersistedGrant's Key makes it hard to create foreign key in EF

### ISSUE THREAD

**Issue by PresidentCamacho** [IdentityServer/IdentityServer4#2872]
Hi,

 I'm trying to add my own EF migration that creates a new table with a FK to the `PersistedGrant` table. But since `PersistedGrant` is using a non code-first convention primary key my EF migration doesn't seem to understand what in the `PersistedGrant` is the primary key. 

`The entity type 'PersistedGrant' requires a primary key to be defined.`

Is there a reason why Key is used instead of: `Id`, `ID `or `PersistedGrantId`?

**Comment by brockallen** [comment]
The records in the persisted grant table are identified by the key. I'd not say that's unconventional; it's the appropriate design. Perhaps they could have had an `int Id` identity column, and then the `Key` could be a unique index, but the `Id` would never be used in any of our usage patterns.
