### ISSUE TITLE
Firefox back navigation error after authorize

### ISSUE THREAD

**Issue by u-foka** [IdentityServer/IdentityServer4#2873]
### Issue / Steps to reproduce the problem

- Start with the sample 6_AspNetIdentity
- Set RequireConsent to false in Config.cs:69 of IdentityServerWithAppNetIdentity project
- Start identity and mvc client
- Navigate to localhost:5002
- Navigate to the "Secure" link
- Log in as alice or bob
- After the secure page is displayed hit back in the browser

An 500 error page is returned with title "An unhandled exception occurred while processing the request."

What is happening is that Firefox does not skip the "Callback" page from the history which re-posts the signin-oidc call that returns the error.

After some research it is turned out that Firefox requires to post the form from within a page OnLoad event to properly skip the Callback page from the history.

### Relevant parts of the log file

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5002/signin-oidc application/x-www-form-urlencoded 1522
warn: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[15]
      '.AspNetCore.Correlation.oidc.z5gXb6vlqSC_w9j9ZedpMNP997CwuPG4huXCUfhHmZA' cookie not found.
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[4]
      Error from RemoteAuthentication: Correlation failed..
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.Exception: Correlation failed.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.9731ms 500 text/html; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5002/favicon.ico
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[8]
      AuthenticationScheme: Cookies was successfully authenticated.
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/favicon.ico'. Physical path: '/Users/u-foka/Desktop/IdentityServer4.Samples-master/Quickstarts/6_AspNetIdentity/src/MvcClient/wwwroot/favicon.ico'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1.7623ms 200 image/x-icon
```

**Comment by u-foka** [comment]
Additional information: https://pomcor.com/2018/05/16/a-bypass-of-the-firefox-post-redirection-bug/

**Comment by brockallen** [comment]
That's in your client app, and not in IdentityServer. Just handle the error event in the OIDC handler. Having said that: 

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by u-foka** [comment]
Hy there, first of all thanks for the quick reply :)

You're right that the exception is happening in the client application, but please also consider that the /connect/authorize/callback "page" showing up in the browser's history is IMO not the intended behavior as it's just a special redirect. For example in chrome it works perfect and goes back directly to the login page that the user expects.

To make firefox able to detect the redirecting page properly the form post has to be called from a window.onload event handler. My problem is that this whole page is hardcoded in the IdentityServer package and I have no way to modify this behavior.

And yes I could handle the exception in the client code, but at that point I don't know the original intention of the user, if the exception occurred because of an expired correlation cookie or by a back navigation.

So I could live with a solution where I could adjust this behavior myself or if you would change it in a way that it support firefox better.
For the latter please check my PR #2881

Thanks!

**Comment by brockallen** [comment]
Ok, interesting -- I'll have a look. Thanks.

**Comment by u-foka** [comment]
Hy, any news on this? :)
