### ISSUE TITLE
IdentityServer4.AspnetIdentity 2.3 not compatible with ASP.NET Core 2.2 project

### ISSUE THREAD

**Issue by zoinkydoink** [IdentityServer/IdentityServer4#2876]
### Issue / Steps to reproduce the problem
1. Create an ASP.NET Core 2.2 MVC app, select individual account for security (https checkbox is checked and cannot be changed)

2. Add nuget package IdentityServer4.AspnetIdentity 2.3 to the project

3. get the following error

Severity	Code	Description	Project	File	Line	Suppression State
Error		This version of Microsoft.AspNetCore.App is only compatible with the netcoreapp2.1 target framework. Please target netcoreapp2.1 or choose a version of Microsoft.AspNetCore.App compatible with netcoreapp2.2.	Identity	C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.app\2.1.1\build\netcoreapp2.1\Microsoft.AspNetCore.App.targets	14	

Also previously with 2.1 I had issues with IdentityServer4 for a asp.net core 2.1 project when https was enabled.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
We did update our host to 2,2 and it's working. I'll see if I can find time to follow your steps.

**Comment by brockallen** [comment]
>Create an ASP.NET Core 2.2 MVC app, select individual account for security (https checkbox is checked and cannot be changed)
>Add nuget package IdentityServer4.AspnetIdentity 2.3 to the project
>get the following error

I just did these exact steps and it's working -- the nuget installs fine.

**Comment by brockallen** [comment]
No updates, so I'll close.
