### ISSUE TITLE
Compatibility with Microsoft.AspNetCore.TestHost

### ISSUE THREAD

**Issue by fuzzzerd** [IdentityServer/IdentityServer4#2877]
**Is your feature request related to a problem? Please describe.**
When integration testing an IdentityServer+API project, with Client Credentials an error occurs. I have published a sample here on Github: https://github.com/fuzzzerd/IdentityServerAndApi/blob/master/IntegrationTest/UnitTest1.cs

Following the stack trace below, it seems to fail at JwtBearerHandler, I think this is because its newing up its own HttpClient, instead of using the one generated by TestServer, to talk back to IdSvr -- though I am not an expert.

I believe this is separate to this previously closed issue: https://github.com/IdentityServer/IdentityServer4/issues/766, and is basically a non-issue today as the newer IdentityModel nifty extension methods on HttpClient. 

**Describe the solution you'd like**
Ability to utilize the HttpClient generated by an instance TestServer. 

**Describe alternatives you've considered**
Would be open to a work around.

**Additional context**
Full log from the unit test run;

> Starting test execution, please wait...
> info: IdentityServer4.Startup[0]
>       Starting IdentityServer4 version 2.3.2.0
> info: IdentityServer4.Startup[0]
>       You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
> info: IdentityServer4.Startup[0]
>       Using the default authentication scheme idsrv for IdentityServer
> dbug: IdentityServer4.Startup[0]
>       Using idsrv as default ASP.NET Core scheme for authentication
> dbug: IdentityServer4.Startup[0]
>       Using idsrv as default ASP.NET Core scheme for sign-in
> dbug: IdentityServer4.Startup[0]
>       Using idsrv as default ASP.NET Core scheme for sign-out
> dbug: IdentityServer4.Startup[0]
>       Using idsrv as default ASP.NET Core scheme for challenge
> dbug: IdentityServer4.Startup[0]
>       Using idsrv as default ASP.NET Core scheme for forbid
> dbug: IdentityServer4.Startup[0]
>       Login Url: /Account/Login
> dbug: IdentityServer4.Startup[0]
>       Login Return Url Parameter: ReturnUrl
> dbug: IdentityServer4.Startup[0]
>       Logout Url: /Account/Logout
> dbug: IdentityServer4.Startup[0]
>       ConsentUrl Url: /consent
> dbug: IdentityServer4.Startup[0]
>       Consent Return Url Parameter: returnUrl
> dbug: IdentityServer4.Startup[0]
>       Error Url: /home/error
> dbug: IdentityServer4.Startup[0]
>       Error Id Parameter: errorId
> dbug: IdentityServer4.Hosting.EndpointRouter[0]
>       Request path /.well-known/openid-configuration matched to endpoint type Discovery
> dbug: IdentityServer4.Hosting.EndpointRouter[0]
>       Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryEndpoint
> info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
>       Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
> dbug: IdentityServer4.Endpoints.DiscoveryEndpoint[0]
>       Start discovery request
> dbug: IdentityServer4.Hosting.EndpointRouter[0]
>       Request path /.well-known/openid-configuration/jwks matched to endpoint type Discovery
> dbug: IdentityServer4.Hosting.EndpointRouter[0]
>       Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryKeyEndpoint
> info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
>       Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks
> dbug: IdentityServer4.Endpoints.DiscoveryKeyEndpoint[0]
>       Start key discovery request
> dbug: IdentityServer4.Hosting.EndpointRouter[0]
>       Request path /connect/token matched to endpoint type Token
> dbug: IdentityServer4.Hosting.EndpointRouter[0]
>       Endpoint enabled: Token, successfully created handler: IdentityServer4.Endpoints.TokenEndpoint
> info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
>       Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
> dbug: IdentityServer4.Endpoints.TokenEndpoint[0]
>       Start token request.
> dbug: IdentityServer4.Validation.ClientSecretValidator[0]
>       Start client validation
> dbug: IdentityServer4.Validation.BasicAuthenticationSecretParser[0]
>       Start parsing Basic Authentication secret
> dbug: IdentityServer4.Validation.PostBodySecretParser[0]
>       Start parsing for secret in post body
> dbug: IdentityServer4.Validation.SecretParser[0]
>       Parser found secret: PostBodySecretParser
> dbug: IdentityServer4.Validation.SecretParser[0]
>       Secret id found: spa
> dbug: IdentityServer4.Stores.ValidatingClientStore[0]
>       client configuration validation for client spa succeeded.
> dbug: IdentityServer4.Validation.SecretValidator[0]
>       Secret validator success: HashedSharedSecretValidator
> dbug: IdentityServer4.Validation.ClientSecretValidator[0]
>       Client validation success
> dbug: IdentityServer4.Validation.TokenRequestValidator[0]
>       Start token request validation
> dbug: IdentityServer4.Validation.TokenRequestValidator[0]
>       Start client credentials token request validation
> dbug: IdentityServer4.Validation.TokenRequestValidator[0]
>       spa credentials token request validation success
> info: IdentityServer4.Validation.TokenRequestValidator[0]
>       Token request validation success
> {
>         "ClientId": "spa",
>         "GrantType": "client_credentials",
>         "Scopes": "api1",
>         "Raw": {
>           "grant_type": "client_credentials",
>           "scope": "api1",
>           "client_id": "spa",
>           "client_secret": "***REDACTED***"
>         }
>       }
> dbug: IdentityServer4.Services.DefaultClaimsService[0]
>       Getting claims for access token for client: spa
> dbug: IdentityServer4.Endpoints.TokenEndpoint[0]
>       Token request success.
> fail: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[3]
>       Exception occurred while processing message.
> System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
>    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
>    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
>    --- End of inner exception stack trace ---
>    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
>    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
>    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
>    --- End of inner exception stack trace ---
>    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
>    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
> fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
>       An unhandled exception has occurred while executing the request.
> System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: '[PII is hidden]'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
>    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
>    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
>    --- End of inner exception stack trace ---
>    at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.GetDocumentAsync(String address, CancellationToken cancel)
>    at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
>    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
>    --- End of inner exception stack trace ---
>    at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
>    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
>    at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
>    at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
>    at Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
>    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
>    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
>    at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events) in C:\local\identity\server4\IdentityServer4\src\Hosting\IdentityServerMiddleware.cs:line 72
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
>    at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in C:\local\identity\server4\IdentityServer4\src\Hosting\BaseUrlMiddleware.cs:line 36
>    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

**Comment by leastprivilege** [comment]
>  it seems to fail at JwtBearerHandler, I think this is because its newing up its own HttpClient

JwtBearer has a BackChannelHandler property. Set this to the handler that you get from the test host.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by fuzzzerd** [comment]
I have solved my issue yes. It would be great for some confirmation that this is an accepted approach for such testing scenarios and perhaps a documentation update or note at least mentioning it.

**Comment by Jehoel** [comment]
I don't think it's a good idea to use a static field in your `Startup` class because it will break when using `WebApplicationFactory<TStartup>` in parallel - such as when xUnit creates multiple instances by default.

I understand the correct way is to set `BackchannelHttpHandler` inside your `WebApplicationFactory` subclass's `ConfigureServices` call, like so:

```
public sealed class MyTestWebApplicationFactory : WebApplicationFactory<MyStartup>
{
    protected override void ConfigureWebHost( IWebHostBuilder builder )
    {
        base.ConfigureWebHost( builder );
        builder 
            .UseEnvironment( "Development" )
            .ConfigureAppConfiguration( this.OverrideConfiguration )
            .ConfigureServices( this.ConfigureServerForWebTests )
            .ConfigureTestServices( this.ConfigureTestServices );
    }

    private void ConfigureServerForWebTests( WebHostBuilderContext whbc, IServiceCollection services )
    {
        services.Configure<JwtBearerOptions>( RssIdentityAuthenticationSchemes.Bearer, jwtOpts => {
            // This runs before the `AddJwtBearer` call in Startup.cs:
            jwtOpts.BackchannelHttpHandler = this.Server.CreateHandler();
        } );
    }
}

```

**Comment by fuzzzerd** [comment]
@Jehoel That's a good idea. I'm not familiar with `WebApplicationFactory` how would [you adapt this test](https://github.com/fuzzzerd/IdentityServerAndApi/blob/b306799eb16aa77ad04b848c86ab6e8f2f2014d0/IntegrationTest/TestIntegrationTest.cs) to use it?

**Comment by Jehoel** [comment]
@fuzzzerd

I see that test is using a local `WebHostBuilder` - which is fine, just add it on to there, like so:

From this:

```
var server = new TestServer(Program.CreateWebHostBuilder(new string[] { }));
```

to this:

```
TestServer server;
{
    TestServer thisServer = null;
    IWebHostBuilder whb = Program.CreateWebHostBuilder( Array.Empty<String>() );
    whb.ConfigureServices( (whbc, services ) => {
        services.Configure<JwtBearerOptions>( "Bearer", jwtOpts => {
            jwtOpts.BackchannelHttpHandler = thisServer.CreateHandler();
        } ); 
    } );
   server = thisServer = new TestServer( whb );
}
```

The bit with `TestServer thisServer = null;` is a bit of a hack, but should be safe because the `Configure` callback won't be invoked until after `TestServer` is initialized, so the `thisServer` reference will not be `null` by the time it calls `.CreateHandler()`.
