### ISSUE TITLE
how to get id_token(SSO) ?

### ISSUE THREAD

**Issue by wlnh420** [IdentityServer/IdentityServer4#2878]
I create a mvc project(.net core mvc)  and connect to id3(.net framework)
1.  I want to get id_token in mvc project,how i get it?
2.  how to logout via post method?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
