### ISSUE TITLE
Breaking change in IdentityServer4.EntityFramework?

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4#2879]
I've just updated

    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="2.1.0" />
    <PackageReference Include="IdentityServer4.EntityFramework" Version="2.1.1" />

to

    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="2.3.0" />
    <PackageReference Include="IdentityServer4.EntityFramework" Version="2.3.2" />

and I now get an error accessing .well-known/openid-configuration. Is a db change needed for this update?

![capture](https://user-images.githubusercontent.com/2369739/49638596-88fc9a00-fa00-11e8-9d8f-f3ce6be49a4b.JPG)

**Comment by leastprivilege** [comment]
You have to run EF migrations.

**Comment by daver77** [comment]
Like this? It says my db is up to date

![image](https://user-images.githubusercontent.com/2369739/49644844-a8e88980-fa11-11e8-9913-a1b7faa2691c.png)

**Comment by daver77** [comment]
That just creates CreateTable methods. Is there a sql script somewhere that I can just run to update my db to the 2.3 version

![capture](https://user-images.githubusercontent.com/2369739/49721403-08d17100-fc5a-11e8-9b92-dcd8f9145734.JPG)

**Comment by nepeta70** [comment]
I also need a SQL script, because the project I'm working in is DB first and I have to send the script to the DBA.

**Comment by brockallen** [comment]
> Is there a sql script somewhere that I can just run to update my db to the 2.3 version?

We don't have that because we don't know what version you're coming from and we don't maintain a matrix of upgrade scripts for all databases.

**Comment by leastprivilege** [comment]
Do we have instructions somewhere - preferably in our docs that show how to create sql scripts and diff scripts?

**Comment by nepeta70** [comment]
I generated the db using the add-migration and then generated the scripts for creating the db using SQL tools. But because this project I'm working in is a project where the database is created and maintained by a DBA I think I'll define my clients using the custom client store or import them from a json file.

**Comment by daver77** [comment]
> 
> 
> > Is there a sql script somewhere that I can just run to update my db to the 2.3 version?
> 
> We don't have that because we don't know what version you're coming from and we don't maintain a matrix of upgrade scripts for all databases.

How are we supposed to upgrade then if EF Migrations does not work and you don't provide upgrade scripts. Surely you've documented the changes somewhere so we can manually add them?

**Comment by leastprivilege** [comment]
EF can generate diff scripts for your specific database back-end.
