### ISSUE TITLE
there is an bug:ERROR [35]: Invalid post logout URI

### ISSUE THREAD

**Issue by wlnh420** [IdentityServer/IdentityServer4#2882]
the id4 is not redirect http://localhost:5000/signout-callback-oidc.

auth:idsrv:admin 2018-12-08 21:18:27.6169 - ERROR [35]: Invalid post logout URI
{
  "ClientId": "NetCoreMvcWeb",
  "ClientName": "NetCoreMvcWeb",
  "SubjectId": "10000",
  "PostLogOutUri": "http://localhost:5000/signout-callback-oidc",
  "Raw": {
    "post_logout_redirect_uri": "http://localhost:5000/signout-callback-oidc",
    "id_token_hint": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2lhbS53ZWIvaWRlbnRpdHkiLCJhdWQiOiJOZXRDb3JlTXZjV2ViIiwiZXhwIjoxNTQ0Mjc1NDAyLCJuYmYiOjE1NDQyNzUxMDIsIm5vbmNlIjoiNjM2Nzk4NzE4ODY5MjY0Mjk1Lk4ySmpaREV4TURBdFl6UmtOUzAwWmpsakxXSTFNelV0TXpjeE4yUTVNamhsTnpGbE16QXpaRFJqWWpjdFl6aGtOUzAwT1RNd0xXRmpaall0WXpReU1qZGlNVFZsWmpFdyIsImlhdCI6MTU0NDI3NTEwMiwiYXRfaGFzaCI6IjZ6MXpuTTRFNnRxcXIwUzFQUmlTa1EiLCJzaWQiOiJkYTAwMmNiYWQxYjI1NGNhNDZmYTc5MjFhNTIyYWU0ZiIsInN1YiI6IjEwMDAwIiwiYXV0aF90aW1lIjoxNTQ0Mjc1MTAxLCJpZHAiOiJpZHNydiIsInRsd1VzZXIiOiJ7XCJBY2NvdW50SWRcIjpcIjEwMDAwXCIsXCJBY2NvdW50TmFtZVwiOlwi57O757uf566h55CG5ZGYXCIsXCJMb2dpbklkXCI6XCJhZG1pblwiLFwiVXNlcklkXCI6XCIxMDAwMFwiLFwiVXNlckNvZGVcIjpudWxsLFwiVXNlck5hbWVcIjpcIuezu-e7n-euoeeQhuWRmFwiLFwiVXNlck1lbWJlcnNoaXBJZFwiOlwiMTAwMDBcIixcIlVzZXJNZW1iZXJzaGlwSWRzXCI6XCJTeXN0ZW0uU3RyaW5nW11cIixcIlJlZ2lvbkNvZGVcIjpcIjE0MDAwMFwiLFwiUmVnaW9uTmFtZVwiOlwi5bGx6KW_55yBXCIsXCJPcmdhbml6YXRpb25JZFwiOlwiMTAwMDBcIixcIk9yZ2FuaXphdGlvbk5hbWVcIjpcIuWxseilv-ecgeiHqueEtui1hOa6kOWOhVwiLFwiT3JnYW5pemF0aW9uQWJiclwiOlwi5bGx6KW_55yB6Ieq54S26LWE5rqQ5Y6FXCIsXCJPcmdhbml6YXRpb25HcmFkZVwiOlwi55yB57qnXCIsXCJPcmdhbml6YXRpb25Db2RlXCI6XCJzeGd0dFwiLFwiRGVwYXJ0bWVudElkXCI6XCIxMzYxMDAwMFwiLFwiRGVwYXJ0bWVudE5hbWVcIjpcIuezu-e7n-euoeeQhlwiLFwiRGVwYXJ0bWVudEFiYnJcIjpcIuezu-e7n-euoeeQhlwiLFwiRHV0eVwiOm51bGwsXCJEdXR5T3JkZXJOb1wiOjk5LFwiSXNEZWZhdWx0RHV0eVwiOnRydWUsXCJUaXRsZVwiOlwi57O757uf566h55CG5ZGYXCIsXCJPcmRlck5vXCI6OTksXCJTZXhcIjpudWxsLFwiSWRjZFwiOm51bGwsXCJUZWxcIjpudWxsLFwiUm9vbVwiOm51bGwsXCJBZGRyXCI6bnVsbCxcIlBvc3RDb2RlXCI6bnVsbCxcIkVtYWlsXCI6bnVsbCxcIlN1cGVySWRcIjpudWxsLFwiTW9iaWxlXCI6bnVsbCxcIkhvdXNlVGVsXCI6bnVsbCxcIlFxXCI6bnVsbCxcIkR1dHlSYW5rXCI6XCJcIixcIkhlYWRJbWdcIjpcIlwiLFwiTW9yZVwiOnt9fSIsInRsd1VzZXJJZCI6IjEwMDAwIiwiYW1yIjpbInBhc3N3b3JkIl19.aqvVi01t6bbZB3gMH_AWKfBjiOmVr2ovLIXWCzAcYrnc1XOPk0qgbgs6Gk09nMF8yqfTwYXjm17npkuHCmq6lPY3E-KphDetxUuBSOcGCxU4UQ1aoFmEf7Q-x5UcpZqw8AV5xZ0PjKiFeDFxVthgTg1Rl0ggcla8OJEiI1QOtDmF45jwXWpl_npKCCaUrOlin9u7ifZ-OVcFSUjegD2uD0hiACcjWVKkaqGMgcpna4wpsj59JGmhcWpJcTs8lqJqlXboFcLbOTyjOZKvTY1NP3sSJBUUb4NLT3ZaEzzi78oIVV6bxwyUTAuMYvMI-LaNv7-FR7prFmUbKnJCwSpXrA"
  }
}

**Comment by brockallen** [comment]
Not enough info
