### ISSUE TITLE
Generate a token with claims from IdentityServerTools

### ISSUE THREAD

**Issue by granthoff1107** [IdentityServer/IdentityServer4#2884]
I'm generating a tokens so IdentityServer has Access to my API

    private async Task<string> CreatePaymentsTokenAsync()
    {
        var tokenLifeTime = 3600;
        var scopes = new[] { CoinbaseAuthConsts.PaymentScope };
        // Use in-built Identity Server tools to issue JWT
        var token = await _identityServerTools.IssueClientJwtAsync(CoinbaseAuthConsts.AuthorityClientId, 
                tokenLifeTime, scopes, new[] { "AstootApi" });
        return token;
    }

I'd like to add claims to this token, I'm not really sure of how to do this, I don't see an overload to pass claims in when generating a token.   

As a small feature request I would like to just be able to pass the claims to the IdentityServerTools

If there is a way to add a claim currently, I'd really appreciate it if you could point me in the right direction

**Comment by granthoff1107** [comment]
I see you can do this by using IssueJwtAsync instead thanks

**Comment by granthoff1107** [comment]
Thanks, the issue is getting GetIdentityServerIssuerUriSince the context is internal
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Dominick Baier <notifications@github.com> Date: 12/9/18  6:29 AM  (GMT-05:00) To: IdentityServer/IdentityServer4 <IdentityServer4@noreply.github.com> Cc: granthoff1107 <granthoff1107@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [IdentityServer/IdentityServer4] Generate a token with claims from IdentityServerTools (#2884) 
Audience is a claim of type aud.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/IdentityServer/IdentityServer4","title":"IdentityServer/IdentityServer4","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/IdentityServer/IdentityServer4"}},"updates":{"snippets":[{"icon":"PERSON","message":"@leastprivilege in #2884: Audience is a claim of type `aud`."}],"action":{"name":"View Issue","url":"https://github.com/IdentityServer/IdentityServer4/issues/2884#issuecomment-445529535"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/IdentityServer/IdentityServer4/issues/2884#issuecomment-445529535",
"url": "https://github.com/IdentityServer/IdentityServer4/issues/2884#issuecomment-445529535",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [IdentityServer/IdentityServer4] Generate a token with claims from IdentityServerTools (#2884)",
"sections": [
{
"text": "",
"activityTitle": "**Dominick Baier**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@leastprivilege",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"IdentityServer/IdentityServer4\",\n\"issueId\": 2884,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"IdentityServer/IdentityServer4\",\n\"issueId\": 2884\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/IdentityServer/IdentityServer4/issues/2884#issuecomment-445529535"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 422024905\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by brockallen** [comment]
@leastprivilege did this get into 2.4? we need to close, or move milestone.

**Comment by leastprivilege** [comment]
moved

**Comment by leastprivilege** [comment]
done. sorry this took ages.

**Comment by aagonzalez85** [comment]
When will this option be available?
