### ISSUE TITLE
TokenClient Obsolete, Documentation Wrong

### ISSUE THREAD

**Issue by iamwyza** [IdentityServer/IdentityServer4#2885]
### Issue / Steps to reproduce the problem
In a more recent release, TokenClient was marked as obsolete.  However the documentation still instructs you to use it: http://docs.identityserver.io/en/latest/quickstarts/1_client_credentials.html?highlight=HttpClient#creating-the-client.

The documentation should be updated to reflect whatever it is you're supposed to do now.  I'd do a PR for that, except the lack of documentation means I have no idea what I'm supposed to do in it's place.

**Comment by brockallen** [comment]
We're in the middle of updating our docs, so this will be changed.updated.

**Comment by leastprivilege** [comment]
a) the obsolete message has a link to updated IdentityModel docs
b) you can see a beta version of the new Quickstarts here: http://docs.identityserver.io/en/updatedqs/quickstarts/0_overview.html

**Comment by iamwyza** [comment]
a) The link just points you at http://docs.identityserver.io.  I'd hardly say that's a useful link.  It's just 1 step above a link to google.com.  
b) This helps, thanks.

**Comment by leastprivilege** [comment]
No - obsolete link points to the IdentityModel docs

**Comment by iamwyza** [comment]
Apologies, I did not realize the 2 were separate projects.
