### ISSUE TITLE
everytime i signin ,it'will  send   redirect_uri=http://****/signin-oidc,but i want send   redirect_uri=http://****/otherpage

### ISSUE THREAD

**Issue by wlnh420** [IdentityServer/IdentityServer4#2887]
everytime i signin ,it'will  send   redirect_uri=http://****/signin-oidc,
but i want send   redirect_uri=http://****/otherpage

how i setting???????

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
