### ISSUE TITLE
Possible issue with Access Tokens

### ISSUE THREAD

**Issue by sophisma** [IdentityServer/IdentityServer4#2888]
Hi, I'm relatively new to Identity Server 4 but I've noticed something odd when going through the quickstart tutorials.
I've created a service with IdentityServer4, an API and an MVC client that accesses that API.
The client was configured the following way:

    
```
new Client
    {
        ClientId = "mvc",
        ClientName = "MVC Client",
        AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,

        ClientSecrets =
        {
            new Secret("secret".Sha256())
        },

        // where to redirect to after login
        RedirectUris = { "https://localhost:44313/signin-oidc" },

        // where to redirect to after logout
        PostLogoutRedirectUris = { "https://localhost:44313/signout-callback-oidc" },

        AllowedScopes = new List<string>
        {
            IdentityServerConstants.StandardScopes.OpenId,
            IdentityServerConstants.StandardScopes.Profile,
            "api1"
         },

         AllowOfflineAccess = true
    }
```

In my MVC Client I have a controller with two actions, one that accesses the API using the TokenClient class and another one that uses HttpContex to retrieve the access token.
Both methods can be seen bellow:

   
```
 public IActionResult APICallWithHttpContext()
    {
        var accessToken = HttpContext.GetTokenAsync("access_token").Result;
        var client = new HttpClient();
        client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
        var content = client.GetStringAsync("https://localhost:5001/identity").Result;
        ViewBag.Json = JArray.Parse(content).ToString();
        return View("APICall");
    }

    public IActionResult APICallWithTokenClient()
    {
        // discover endpoints from metadata
        var disco = DiscoveryClient.GetAsync("https://localhost:5000").Result;
        if (disco.IsError)
        {
            Console.WriteLine(disco.Error);
            throw new Exception(disco.Error);
        }

        // request token for clientcredentials client
        var tokenClient = new TokenClient(disco.TokenEndpoint, "mvc", "secret");
        var tokenResponse = tokenClient.RequestClientCredentialsAsync("api1").Result;

        if (tokenResponse.IsError)
        {
            throw new Exception(tokenResponse.Error);
        }

        // call api
        var client = new HttpClient();
        client.SetBearerToken(tokenResponse.AccessToken);
        var response = client.GetAsync("https://localhost:5001/identity").Result;

        if (!response.IsSuccessStatusCode)
        {
            throw new Exception(response.StatusCode.ToString());
        }
        else
        {
            var content = response.Content.ReadAsStringAsync().Result;
            ViewBag.Json = JArray.Parse(content);
        }
        return View("APICall");
    }

```

In the API all methods can be accessed (no Authorized attribute).
I was just testing if I could access the API from the MVC 
 client.
Everything seemed to be working until I decided to do another test.
On the IdentityServer application I decided to comment the "api" scope on the client configuration:

```
AllowedScopes = new List<string>
        {
            IdentityServerConstants.StandardScopes.OpenId,
            IdentityServerConstants.StandardScopes.Profile,
            //"api1"
         },

```
At this point I noticed something, when using the TokenClient class I got an unauthorized response, as it should be. But, when using the HttpContext, I could still access the API from the MVC client, even though the application didn't have access to that scope.
Shouldn't I have a unauthorized response too?
This seems like a bug, It shouldn't be possible to access the API without access to that scope.
You can check the entire code here:

https://github.com/sophisma/IdentityServerTutorial

The IdentityServer application is inside the IdentityServerTutorial folder, te API is in IdentityServerTutorialAPI and the MVC client is in IdentityServerTutorialMVCClient.
The actions that access the API are inside the HomeController in the MVC client.

**Comment by leastprivilege** [comment]
Is this intended?
https://github.com/sophisma/IdentityServerTutorial/blob/master/IdentityServerTutorialAPI/Controllers/IdentityController.cs#L11

**Comment by sophisma** [comment]
Thank you for answering.
Yes, I commented the Authorized attribute because I wanted to check only the client access part, independently of the user being logged in or not.
Of course the result will be empty as there is no User.
With TokenClient it validates the "api" scope with HttpContext it doesn't.
Sorry if I'm making very basic questions but this is new to me.

**Comment by leastprivilege** [comment]
I can't follow - sorry. I would recommend you have a look at the tokens you are getting with e.g. https://jwt.io

If it contains an audience of api1 - you will get access to the API - if not - not. Of course this is only enforced when the Authorize attribute is present.

That said 

This seems to be a general question about IdentityServer - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by sophisma** [comment]
Sorry, I got this wrong.
Somehow I thought that the IdentityServer middleware was responsible for allowing/dening access to the clients and the Authorize attribute just authorized the Users.
