### ISSUE TITLE
Get client details when showing consent screen

### ISSUE THREAD

**Issue by amiteshs** [IdentityServer/IdentityServer4#2889]
Hi
We redirect users to our web application for login and consent. I have this part working but I need to show the client details who is requesting permission. How can I pass to our web app the clientId or some other detail that I can use to retrieve the client name to show to the user.

Code below shows the config I have which works fine:
`.AddIdentityServer(options =>
                {
                    options.UserInteraction = new UserInteractionOptions()
                    {
                        LoginUrl = "OUR WEB APP URL",
                        LoginReturnUrlParameter = "returnUrl",
                        ConsentUrl = "OUR WEB APP URL",
                        LogoutUrl = "..."
                    };
                })`

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by amiteshs** [comment]
Hi
No I am still trying to get an answer as to how to solve this issue. Is there a way IDS can pass over data to the web app telling it about the client asking for permission? I need to display something like, Company XYZ is asking for permission to use your data..... My issue is I cannot tell the web app about the client info.

**Comment by brockallen** [comment]
That's the client_id. You can always add extra claims via the `Client` setting called `ClientClaims`.

**Comment by amiteshs** [comment]
I just rechecked the passed in return url parameter and it does have a client_id in it. I will need to parse the return url and extract the client_id. This should not be a problem, It would however have been better if this was passed as an extra parameter together with the return url parameter.
Thanks for pointing this out.
