### ISSUE TITLE
Make ProtectedDataMessageStore public

### ISSUE THREAD

**Issue by tungsnguyen** [IdentityServer/IdentityServer4#2893]
**Is your feature request related to a problem? Please describe.**
I am implementing federated single logout with SAML and IdentityServer4. When triggering logout on SAML Idp, IS4 loses information about logged in clients (SignOutIframeUrls is cleared) when SAML Idp redirects to IS4 Idp. I checked and found out that SAML creates a new logout message which replaces old one.

**Describe the solution you'd like**
I need to use a data message store to keep message between SAML and IS4 and I found ProtectedDataMessageStore. However, it was internal.

**Describe alternatives you've considered**
I tried but did not find any other good solution. If there are any other ways to keep information between requests, please suggest.

**Comment by scottbrady91** [comment]
Can you confirm what version of the SAML component you are using? I think I may have fixed this in a recent release.

**Comment by tungsnguyen** [comment]
I am using version 2.2.0

**Comment by scottbrady91** [comment]
Okay. Some of the logout functionality was updated in 2.2.0-preview3. Let me know how it goes.

**Comment by tungsnguyen** [comment]
Hello Scott. Sorry I forgot to mention that I did not use the integrated SAML component, but Component Space SAML, because it supports .NET Core

**Comment by scottbrady91** [comment]
So do we: https://www.identityserver.com/articles/announcing-net-core-support-for-the-identityserver4-saml-component/

**Comment by brockallen** [comment]
Are you still looking for this class to be made public?

**Comment by tungsnguyen** [comment]
Hello. Yes I am, because unfortunately I could not replace Component Space SAML with integrated SAML component.

**Comment by brockallen** [comment]
Done.
