### ISSUE TITLE
Add more control over Response.

### ISSUE THREAD

**Issue by andrx** [IdentityServer/IdentityServer4#2894]
**Is your feature request related to a problem? Please describe.**
Recently i had to add support for [Google assistant's "OAuth and Google Sign-In + Authorization code" account linking](https://developers.google.com/actions/identity/google-sign-in-oauth?creation=yes&oauth=code). Adding `IExtensionGrantValidator` that supports `"urn:ietf:params:oauth:grant-type:jwt-bearer"` grant was easy but going through the logs of IdentityServer I noticed that it always returns 400 and the same message, no matter what 
 `customResponse` dictionary I supply.

So, in order to fix this behavior and comply with expectations on google side i had to copy-paste three classes (TokenEndpoint, TokenErrorResult, TokenResult) just because they are `internal`, register new endpoint and make one adjustment in `TokenErrorResult`:

        ...
        public async Task ExecuteAsync(HttpContext context)
        {
            context.Response.StatusCode = 400;
            context.Response.SetNoCache();

            var dto = new ResultDto
            {
                error = Response.Error,
                error_description = Response.ErrorDescription
            };

            if (Response.Custom.IsNullOrEmpty())
            {
                await context.Response.WriteJsonAsync(dto);
            }
            else
            {
                // changes here:
                if (Response.Custom.ContainsKey("httpCode"))
                {
                    context.Response.StatusCode = (int) Response.Custom["httpCode"];
                }
                var jobject = ObjectSerializer.ToJObject(dto);
                jobject.AddDictionary(Response.Custom);
                if (Response.Custom.ContainsKey("httpError"))
                {
                    jobject["error"] = (string)Response.Custom["httpError"];
                }
                await context.Response.WriteJsonAsync(jobject);
            }
        }
        ...
Then these two are replaced by values in `customResponse` dictionary and the flow works fine.
It looks hackish and may very well be wrong in terms of how i used it.  Is there simpler way at the moment?

**Describe the solution you'd like**
Passing in `TokenErrorResult` ctor some class or handler(s) that then could be called before `await context.Response.WriteJsonAsync(obj);` might help. Its responsibility would be to adjust `HttpContext.Response` according to `TokenErrorResponse`. If instance of the class is injected (may be a collection of those) then call it otherwise fallback to current implementation. Injection should happen on `IEndpointHandler` level I guess.

**Comment by brockallen** [comment]
IIRC, the spec mandates the status code and error codes sent back on failures. Are you asking to allow the response to override what the spec mandates, or are you asking for something else?

**Comment by andrx** [comment]
hi @brockallen, I guess we are talking about [this one](https://tools.ietf.org/html/rfc6749#section-5.2). 
Indeed, I don't see `user_not_found` as an option for `error` property. And `401` could only be sent when it's `invalid_client` otherwise it's `400`.
In this case Google wants specific response:

	HTTP/1.1 401 Unauthorized
	Content-Type: application/json;charset=UTF-8

	{
	  "error":"user_not_found",
	}

which is outside of spec. probably what i have is fine then..... the library can't cover all customized use cases.
Didn't intent to ask about overriding spec but now it looks exactly like it.

**Comment by 812169562** [comment]
now，
（context.Result = new GrantValidationResult(TokenRequestErrors.InvalidRequest, ex.InnerException.Message);）
。I want  set Response.StatusCode=200，What shall I do?

**Comment by brockallen** [comment]
So @andrx, you seem to be in agreement that we don't want to change the status codes so that we stay spec compliant? If so, we can close this?

**Comment by andrx** [comment]
@812169562 you probably need to do something similar to what I implemented, pass `customResponse` with the code and then add logic to handle this on `TokenErrorResult` side.

**Comment by andrx** [comment]
@brockallen I agree with you.
