### ISSUE TITLE
User Claims, where stored and must be fields in dbo.AspNetUsers?

### ISSUE THREAD

**Issue by toddtsic** [IdentityServer/IdentityServer4#2895]
Trying to come up to speed with IS4.

Using Asp.Net Core Identity

Trying to add custom claim (happens to be a property that is NOT a member of ApplicationUser).

By behavior I'm inferring that a custom claim can only be an existing property of the ApplicationUser, is this correct?

Also I can't seem to find where claims are stored (coming from OpenIdDict where were stored in dbo.AspNetUserClaims.  Nothing there.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
