### ISSUE TITLE
Consider azp instead of client_id

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#2897]

**Comment by TomCJones** [comment]
this intrigues me.  In Kantara we are considering a identifier to be a url that points to an identity statement. If you are thinking of using the azp to point to an identity we would like to see if what it points to is an identity statement.  see https://tcwiki.azurewebsites.net/index.php?title=Trusted_Identifier

**Comment by brockallen** [comment]
No, we're simply considering using the azp to hold the client's identifier in the same way we use client_id today. So it's just a name change, mainly since it's described in the OIDC spec for that purpose (at least in id_token validation).

**Comment by TomCJones** [comment]
there was a great thread on this in the fapi branch - but I can't find it now. As I recall the purpose of the azp is security assurance. But there is no prohibition concerning your use.

**Comment by TomCJones** [comment]
You might want to look at this thread. Seems like everyone is headed in a different direction https://bitbucket.org/openid/fapi/issues/190/aud-iss-should-be-mandatory-in-requests

**Comment by brockallen** [comment]
Not on the roadmap as of now.
