### ISSUE TITLE
EndpointRouter doesn't handle scoped services properly

### ISSUE THREAD

**Issue by pvasek** [IdentityServer/IdentityServer4#29]
If you have a store implementation registered with Scope life time:
```
services.AddScoped<IScopeStore, MyScopeStore>();
```
the store is instantiated only once for whole application lifetime.

If you register it with Transient life time 
```
services.AddTransient<IScopeStore, MyScopeStore>();
```
everything works as expected.

The problem is that the request scope is not initialized correctly. The fix which is working for me is to replace inside the `Find` method
```
endpoint = context.ApplicationServices.GetService(type) as IEndpoint;
```
with 
```
endpoint = context.RequestServices.GetService(type) as IEndpoint;
```
because the RequestService creates the request scope everything start to work then.

I am not sure if there is better way to accomplish that but I can create the PR with this one line change if you are interested.

**Comment by brockallen** [comment]
> The problem is that the request scope is not initialized correctly. The fix which is working for me is to replace inside the Find method
```
endpoint = context.RequestServices.GetService(type) as IEndpoint;
```
with
```
endpoint = context.RequestServices.GetService(type) as IEndpoint;
```

aren't those two lines of code the same?

**Comment by pvasek** [comment]
My apologies. The original code was
```
endpoint = context.ApplicationServices.GetService(type) as IEndpoint;
```

**Comment by brockallen** [comment]
Ah, ok. Yes, we should be using RequestServices. Send the PR if you'd like.

**Comment by huysentruitw** [comment]
don't forget to close :)
