### ISSUE TITLE
logoutId always null (user marked as not active)

### ISSUE THREAD

**Issue by eestein** [IdentityServer/IdentityServer4#2900]
I've posted this as a SO question (https://stackoverflow.com/questions/53780000/identityserver-logoutid-is-null), but I'm also posting it here, in case it is a bug, or the docs need updating to refer to `User not marked as active`. If there's such info, I'm sorry, I couldn't find it.

### Issue / Steps to reproduce the problem

I can't get the PostLogoutRedirectUri from IdentityServer4 because logoutId on my Logout action is always null. I checked and the PostLogoutRedirectUris property has the same exact url I'm sending and it still won't work, logoutId is always null.

After researching a little bit deeper I found out one of the errors being thrown are due to `IsActiveContext` not being active:

- source: https://github.com/IdentityServer/IdentityServer4/blob/master/src/Validation/Default/TokenValidator.cs#L123

I just couldn't find the process to fix it and confirm if this is the only problem.

Code:

[![enter image description here][2]][2]

Request:

[![enter image description here][3]][3]

### Relevant parts of the log file

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/i9n7k.jpg
  [2]: https://i.stack.imgur.com/DjCxK.jpg
  [3]: https://i.stack.imgur.com/AZrPc.jpg

**Comment by brockallen** [comment]
Any update?

**Comment by eestein** [comment]
@brockallen what update? I'm not following.

**Comment by brockallen** [comment]
I asked if you had any updates. Since I heard nothing I closed this.

**Comment by brockallen** [comment]
So to answer your original question - if the user is not active, then we can't validate a token for them. So at signout that sounds like what's happening, and thus your logoutId is null.

**Comment by eestein** [comment]
I'm sorry, but I still don't follow. I was asking a question/reporting a bug. I though you might be chiming leastprivilege who added the question tag. The situation hasn't changed and no answer was provided on SO.

**Comment by brockallen** [comment]
Well, that's how our token validator works. It checks to see if the user is "active". So since that is failing, the end session request validation fails, which means you don't get a logoutId in the logout action method.
