### ISSUE TITLE
Invalid request body keywords accepted and token issued

### ISSUE THREAD

**Issue by aristosamar** [IdentityServer/IdentityServer4#2906]
Hi,

I am using .NET Core 2.1 with Identity Server 4.
/connect/token end-point requires request body in format:

"scope=" + scopes + "&grant_type=client_credentials"

While testing I replaced keyword "scope=" with "blah blah blah=" and IDS issued valid token.

i.e.

"blah blah blah=" + scopes + "&grant_type=client_credentials"

Not a security problem but feels weird.

Regards
Mariusz

**Comment by leastprivilege** [comment]
Spec says the sts should ignore unknown parameters.
