### ISSUE TITLE
Consider adding Client.Id to Client Model

### ISSUE THREAD

**Issue by randyjeppesen** [IdentityServer/IdentityServer4#2910]
Please consider adding: 

     public int Id { get; }

 to Client in IdentityServer4.Models.

I  use the Client.Id as a foreign key in other tables.  Having the Id in the Client model saves a trip to the DB.

**Comment by brockallen** [comment]
That's a DB level concern, and thus why it's not in the domain model.

**Comment by Mortana89** [comment]
Can this be changed to a string property to support Guids?
CosmosDB does not support autoincrementing integers ootb upon inserts, so would really save some hacking away if this can be a string so that CosmosDB can generate guids ....

**Comment by brockallen** [comment]
I've spent many years trying to solve the one object model to abstract the different DB architectures, and it's not trivial. That's why the entity layer is deliberately separate from the model layer in IdentityServer.
