### ISSUE TITLE
ScopeValidator does not work properly with a custom cache in Redis

### ISSUE THREAD

**Issue by lttrung11** [IdentityServer/IdentityServer4#2918]
I tried to implement a custom cache for IS4:

```
    public class Is4DistributedCache<T> : ICache<T> where T : class
    {
        private readonly IDistributedCache _distributedCache;

        public Is4DistributedCache(IDistributedCache distributedCache)
        {
            _distributedCache = distributedCache;
        }

        public async Task<T> GetAsync(string key)
        {
            var content = await _distributedCache.GetAsync(key);
            if (content == null) return null;
            return JsonConvert.DeserializeObject<T>(Encoding.UTF8.GetString(content));
        }

        public async Task SetAsync(string key, T item, TimeSpan expiration)
        {
            if (item == null) return;

            var content = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(item));
            await _distributedCache.SetAsync(key, content, new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = expiration
            });
        }
    }
```
IDistributedCache is implemented by RedisCache of Microsoft.Extensions.Caching.Redis.

### Issue / Steps to reproduce the problem
1. When I tried to request an access token (/connect/token), I got the following error:
Requested scope not allowed: "..."

2. If I change GetAsync to this, then it works:
```
        public async Task<T> GetAsync(string key)
        {
            var content = await _distributedCache.GetAsync(key);
            if (content == null) return null;

            var item = JsonConvert.DeserializeObject<T>(Encoding.UTF8.GetString(content));
            if (item != null && item is IEnumerable enumerable && !enumerable.GetEnumerator().MoveNext())
            {
                return null;
            }

            return item;
        }
```
It's possible that when a blank array is returned from ICache<T>, ScopeValidator does not handle it properly.

### Relevant parts of the log file

When it failed:
```
2019-01-03T16:25:10.3426446+07:00 [DBG] [10] [Microservice.Security.Services.Is4DistributedCache] GetAsync, Key = "..."
2019-01-03T16:25:13.9791962+07:00 [DBG] [8] [Microservice.Security.Services.Is4DistributedCache] SetAsync, Key = "...", expiration = 900 seconds
2019-01-03T16:25:18.4943945+07:00 [DBG] [8] [Microservice.Security.Services.Is4DistributedCache] GetAsync, Key = "..."
2019-01-03T16:25:29.4133065+07:00 [DBG] [8] [Microservice.Security.Services.Is4DistributedCache] SetAsync, Key = "...", expiration = 900 seconds
2019-01-03T16:25:42.2479856+07:00 [DBG] [8] [Microservice.Security.Services.Is4DistributedCache] GetAsync, Key = "..."
2019-01-03T16:26:07.6118122+07:00 [ERR] [8] [IdentityServer4.Validation.ScopeValidator] Requested scope not allowed: "..."
2019-01-03T16:26:07.6271196+07:00 [ERR] [8] [IdentityServer4.Validation.TokenRequestValidator] TokenRequestValidationLog { ClientId: "...", ClientName: "Security Admin UI", GrantType: "password", Scopes: null, AuthorizationCode: null, RefreshToken: null, UserName: null, AuthenticationContextReferenceClasses: null, Tenant: null, IdP: null, Raw: [("client_id": "..."), ("client_secret": "***REDACTED***"), ("grant_type": "password"), ("username": "admin"), ("password": "***REDACTED***"), ("scope": "...")] }
```

And when it succeeded
```
2019-01-03T16:53:55.7964454+07:00 [DBG] [10] [Microservice.Security.Services.Is4DistributedCache] GetAsync, Key = "..."
2019-01-03T16:53:56.9240044+07:00 [DBG] [5] [Microservice.Security.Services.Is4DistributedCache] SetAsync, Key = "...", expiration = 900 seconds
2019-01-03T16:53:57.0412586+07:00 [DBG] [6] [Microservice.Security.Services.Is4DistributedCache] GetAsync, Key = "..."
2019-01-03T16:53:57.1109947+07:00 [DBG] [5] [Microservice.Security.Services.Is4DistributedCache] SetAsync, Key = "...", expiration = 900 seconds
2019-01-03T16:53:57.1600569+07:00 [DBG] [10] [Microservice.Security.Services.Is4DistributedCache] GetAsync, Key = "..."
2019-01-03T16:53:57.3543742+07:00 [DBG] [6] [Microservice.Security.Services.Is4DistributedCache] SetAsync, Key = "...", expiration = 900 seconds
2019-01-03T16:53:57.4117021+07:00 [DBG] [8] [Microservice.Security.Services.Is4DistributedCache] GetAsync, Key = "..."
2019-01-03T16:53:57.4621209+07:00 [DBG] [6] [Microservice.Security.Services.Is4DistributedCache] GetAsync, Key = "..."
```

**Comment by brockallen** [comment]
I just tried to repro your issue by creating an in-memory cache (I don't have redis), and I tried to make it as close to yours as possible. Here's mine:

```
public class MyCache<T> : ICache<T> where T : class
    {
        Dictionary<string, byte[]> _cache = new Dictionary<string, byte[]>();
        private string _name;

        public MyCache()
        {
            _name = typeof(T).FullName;
        }

        public Task<T> GetAsync(string key)
        {
            T result = default(T);
            if (_cache.ContainsKey(key))
            {
                var content = _cache[key];
                result = JsonConvert.DeserializeObject<T>(Encoding.UTF8.GetString(content));

            }
            return Task.FromResult(result);
        }

        public Task SetAsync(string key, T item, TimeSpan expiration)
        {
            if (item != null)
            {
                var content = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(item));
                _cache[key] = content;
            }
            else if (_cache.ContainsKey(key))
            {
                _cache.Remove(key);
            }

            return Task.CompletedTask;
        }
    }
```

And it's in DI like this:

```
services.AddSingleton(typeof(ICache<>), typeof(MyCache<>));

services.AddIdentityServer()
                .AddInMemoryClients(Clients.Get())
                .AddInMemoryIdentityResources(Resources.GetIdentityResources())
                .AddInMemoryApiResources(Resources.GetApiResources())
                .AddTestUsers(TestUsers.Users)
                .AddClientStoreCache<InMemoryClientStore>()
                .AddResourceStoreCache<InMemoryResourcesStore>();
```

And my clients seem to be working for me. So can you help me adjust my sample to have the same issue your redis cache is having so I can repro the issue?

**Comment by brockallen** [comment]
Any update?

**Comment by lttrung11** [comment]
Hi @brockallen,

I am sorry for not replying earlier.
We don't have this issue with in memory cache, only with Redis.

Here is how I register it in DI:
`
            services.AddSingleton<ICacheManager, RedisCacheManager>();
            services.AddTransient(typeof(ICache<>), typeof(IdentityServers4Cache<>));
`

ICacheManager is injected to IdentityServer4Cache in its constructor:
`
        public IdentityServers4Cache(ILogger<IdentityServers4Cache<T>> logger, ICacheManager cacheManager)
        {
            _cacheManager = cacheManager;
            _logger = logger;
        }
`

And here is the RedisCacheManager:
`
    public class RedisCacheManager : BaseCacheManager
    {
        private readonly ILogger<RedisCacheManager> _logger;
        private readonly RedisCacheOptions _redisCacheOptions;
        private readonly IDistributedCache _distributedCache;

        private ConnectionMultiplexer _connection;
        private ConnectionMultiplexer Connection => _connection ?? (_connection = ConnectionMultiplexer.Connect(_redisCacheOptions.Configuration));
        private IDatabase Cache => Connection.GetDatabase();

        public RedisCacheManager(ILogger<RedisCacheManager> logger, IOptions<RedisCacheOptions> redisCacheOptions, IDistributedCache distributedCache)
        {
            _logger = logger;
            _redisCacheOptions = redisCacheOptions.Value;
            _distributedCache = distributedCache;
        }

        protected override async Task SetInternalAsync(string key, byte[] content, TimeSpan expiration)
        {
            await _distributedCache.SetAsync(key, content, new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = expiration
            });
        }

        public override async Task<byte[]> GetAsync(string key)
        {
            var value = await _distributedCache.GetAsync(key);
            return value;
        }

        public override async Task FlushInternalAsync(string[] keys)
        {
            keys = keys.Select(k => $"{_redisCacheOptions.InstanceName}{k}").ToArray();

            var redisKeys = Connection.GetEndPoints().Select(ep => Connection.GetServer(ep))
                .SelectMany(s => s.Keys(pattern: $"{_redisCacheOptions.InstanceName}*"))
                .Where(rk => keys.Contains(rk.ToString()))
                .ToArray();
            if (redisKeys.Any())
            {
                var count = await Cache.KeyDeleteAsync(redisKeys);
                _logger.LogDebug($"{count} keys deleted, keys = {keys.Select(k => k.ToString()).Aggregate((x, y) => $"{x}, {y}")}");
            }
        }
    }
`

When I tried to debug Is4DistributedCache<T>.GetAsync(string key), this line will set item to a blank array:
`
var item = JsonConvert.DeserializeObject<T>(Encoding.UTF8.GetString(content));
`

And returning a blank array (instead of a null) will cause the issue to happen.

**Comment by brockallen** [comment]
>  We don't have this issue with in memory cache, only with Redis.

Then I can't help you. Sorry.

**Comment by lttrung11** [comment]
Thank you very much for your help, @brockallen
