### ISSUE TITLE
can't reach discovery endpoint after deploying IS4 to a subroute

### ISSUE THREAD

**Issue by przemekwojcik** [IdentityServer/IdentityServer4#2920]
I need to change the url of a discovery endpoint from this:

> /.well-known/openid-configuration

to this:

> /identity/.well-known/openid-configuration

i'm trying to deploy IS4 to Azure Kubernetes Service. It all works out great when i deploy IS4 to the root address (like http://xxxx.europe.cloudapp.azure.com) - I see the welcome page and i can access my discovery endpoint.

However, when i deploy IS4 to a subroute (http://xxxx.europe.cloudapp.azure.com/identity) i can't access oidc-configuration. I'm using URL rewriting so when i click the link to access discovery document (http://xxxx.europe.cloudapp.azure.com/identity/.well-known/openid-configuration) i get HTTP404.

The approach with mapping to a subroute didn't help:

```
            app.Map("/identity", authApp =>
            {
                authApp.UseIdentityServer();
            });
```

**Comment by brockallen** [comment]
Don't know, sorry. Sounds environmental. I'd try to reproduce it with a stand-alone ASP.NET Core app and get that working to better understand why it might not be working with IdentityServer.

**Comment by dviry** [comment]
here [another link](http://amilspage.com/set-identityserver4-url-behind-loadbalancer/) that might help.

**Comment by brockallen** [comment]
Any update?

**Comment by przemekwojcik** [comment]
We can close this one. What worked for me was:

```
            app.Map("/identity", authApp =>
            {
                authApp.UseIdentityServer();
                authApp.UseMvcWithDefaultRoute();
            });
```
