### ISSUE TITLE
Out of date property name in quickstarts

### ISSUE THREAD

**Issue by MikeBeaton** [IdentityServer/IdentityServer4#2921]
The quickstarts page [Protecting an API using Client Credentials/Adding an API/Configuration](http://docs.identityserver.io/en/latest/quickstarts/1_client_credentials.html#configuration) uses `JwtBearerOptions.ApiName` in the code, but the property is now called `JwtBearerOptions.Audience`.

**Comment by brockallen** [comment]
Merged, thanks.
