### ISSUE TITLE
Incorrect method name GetApiResources in quckstarts text

### ISSUE THREAD

**Issue by MikeBeaton** [IdentityServer/IdentityServer4#2922]
The quickstarts page [Protecting an API using Client Credentials/Defining an API Resource](http://docs.identityserver.io/en/latest/quickstarts/1_client_credentials.html#defining-an-api-resource) specifies the incorrect method name `GetApiResources` in the text, but uses the correct method name `GetApis` in the matching code.

**Comment by brockallen** [comment]
Merged, thanks

**Comment by cb577** [comment]
It appears the code sample on the second quickstart page, [Protecting an API using Passwords](http://docs.identityserver.io/en/latest/quickstarts/2_resource_owner_passwords.html), contains the same error in a code snippet, `.AddInMemoryApiResources(Config.GetApiResources())`
