### ISSUE TITLE
integration test 's open id connect throw "System.Net.CookieException : The 'Path'='/signin-oidc' part of the cookie is invalid " 

### ISSUE THREAD

**Issue by jingliancui** [IdentityServer/IdentityServer4#2925]
I have a mvc client use the oidc feature with asp.net identity.Config in startup is that:

```
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
            .AddCookie("Cookies")
            .AddOpenIdConnect("oidc", options =>
            {
                options.SignInScheme = "Cookies";

                //44341 is the port of Identity.API project
                options.Authority = "https://localhost:44341";

                options.RequireHttpsMetadata = false;
                
                options.ClientId = "mvc";
                
                options.ClientSecret = "secret";
                
                options.ResponseType = "code id_token";
                
                options.SaveTokens = true;
                
                options.GetClaimsFromUserInfoEndpoint = true;
                
                options.Scope.Add("api1");
                
                options.Scope.Add("offline_access");
                                
            });

```

Integration test code use this httpclient:

```
             var client = mvcFactory.CreateClient(new  
             Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactoryClientOptions()
            {
                HandleCookies=true,
                AllowAutoRedirect=false,
                BaseAddress=new Uri ("https://localhost:44332/")
            })
```

or this from the [identity model's code](https://github.com/IdentityModel/IdentityModel.Owin.PopAuthentication/blob/dev/src/IdentityModel.Owin.PopAuthentication.Tests/IntegrationTests/IdSvr_Client_And_WebApi_Integration/BrowserClient.cs):
```
            var client = new BrowserClient(new BrowserHandler(mvcHandler))
            {
                AllowCookies=true,
                BaseAddress=new Uri("https://localhost:44332/"),
                AllowAutoRedirect=false
            };
```

Then run the test show this error:
```
Message: System.Net.CookieException : An error occurred when parsing the Cookie header for Uri 'https://localhost:44332/Home/Login'.
---- System.Net.CookieException : The 'Path'='/signin-oidc' part of the cookie is invalid.
```

Do that because I want get the access_token from 
`HttpContext.GetTokenAsync("access_token");`

Because I do the oidc with the authorize feature, so I can get access token by used the id and secure,but this token didn't had the correct role for access the protected api.
So I do above code to simulator the login round trip to get the logined access_token.

**Comment by jingliancui** [comment]
Then today I check the source code of the .net core 's CookieContainerHandler  [here](https://github.com/aspnet/AspNetCore/blob/321327f84b2b22dcff2e9beb06a9a64236c5cced/src/Mvc/src/Microsoft.AspNetCore.Mvc.Testing/Handlers/CookieContainerHandler.cs#L43)

and the handler of the identity sample code [here](https://github.com/IdentityModel/IdentityModel.Owin.PopAuthentication/blob/dev/src/IdentityModel.Owin.PopAuthentication.Tests/IntegrationTests/IdSvr_Client_And_WebApi_Integration/BrowserHandler.cs#L60)

exception throw in the SetCookies method of the class CookieContainer.

That all info now  I can provide.

**Comment by AutismPatient** [comment]
**Please show the configuration information code of your identity server for more information**

**Comment by jingliancui** [comment]
Hi @AutismPatient 
Here is the config of the identity server:

```
        public List<Client> GetClients()
        {
            var result = new List<Client>
            {
                new Client
                {
                    ClientId = "mvc",
                    ClientName = "MVC Client",
                    AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,

                    RequireConsent = false,

                    AlwaysIncludeUserClaimsInIdToken = true,
                    AlwaysSendClientClaims = true,
                    //Claims=
                    UpdateAccessTokenClaimsOnRefresh = true,
                    RefreshTokenUsage = TokenUsage.OneTimeOnly,
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    //44332 is the port of mvc porject
                    RedirectUris = { "https://localhost:44332/signin-oidc" },
                    PostLogoutRedirectUris = { "https://localhost:44332/signout-callback-oidc" },
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1"
                    },
                    AllowOfflineAccess = true
            }
            };
            return result;
        }
```

and config in startup.cs :

```
            services.AddIdentityServer(options =>
            {
                options.Events.RaiseSuccessEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseErrorEvents = true;
            })
            .AddDeveloperSigningCredential()
            .AddConfigurationStore(options =>
            {
                options.ConfigureDbContext = builder =>
                builder.UseMySql(connStr,
                sql => sql.MigrationsAssembly(migrationsAssembly));
            })
            .AddOperationalStore(options =>
            {
                options.ConfigureDbContext = builder =>
                builder.UseMySql(connStr,
                sql => sql.MigrationsAssembly(migrationsAssembly));
                options.EnableTokenCleanup = true;
                options.TokenCleanupInterval = 30;
            })
            .AddAspNetIdentity<IdApiUser>();
```

**Comment by jingliancui** [comment]
`app.UseIdentityServer();`
had been in the Configure method.
Is it the initializes method you said ?

**Comment by AutismPatient** [comment]
`app.UseAuthentication();`

**Comment by jingliancui** [comment]
The mvc client's Configure method of startup.cs had been use the 
`app.UseAuthentication();`

**Comment by AutismPatient** [comment]
The url in your header is incorrect because it does not point to your identity server address

**Comment by AutismPatient** [comment]
**This may be because the callback address specified by the identity server is not the same as the address you used in the integration test, typically `/sigin-oidc` instead of `/login`**

**Comment by AutismPatient** [comment]
999999

**Comment by jingliancui** [comment]
@tamimehsas EF' s Sample Just check here:
http://docs.identityserver.io/en/latest/reference/ef.html

and here:
https://github.com/IdentityServer/IdentityServer4.Samples

**Comment by AutismPatient** [comment]
You try to put a `[Authorize]` method outside `Login` to see the effect

**Comment by jingliancui** [comment]
I don't understand what you said.
Can you tell me more detail?please

**Comment by AutismPatient** [comment]
**It also doesn't get to the root of the problem**

**Comment by brockallen** [comment]
So did you all sort out if there's a problem or not? I don't think anyone here has had time to look into this.

**Comment by twogood** [comment]
I just ran into a very similar problem today when trying to get an integration test working. I managed to solve it by setting the cookie paths like this:
```
.AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
				{
					options.CorrelationCookie.Path = "/";
					options.NonceCookie.Path = "/";
```
It seems like the cookie paths defaults to the same value as that of options.CallbackPath. I think that "/" would be a better default for the cookie paths. (Some more security minded person might disagree...)

**Comment by twogood** [comment]
After devising my own solution I also found this:

https://github.com/aspnet/AspNetCore/blob/d8381656429addead2e5eb22ba1356abfb419d86/src/Azure/AzureAD/test/FunctionalTests/WebAuthenticationTests.cs#L192

**Comment by jingliancui** [comment]
@twogood Thanks so much , I'll test your solution later  : )
So I want keep this issue still open status.
@brockallen 
@AutismPatient

**Comment by jingliancui** [comment]
@twogood It's work!!!Thanks so much.It's really useful to use the cookie,or I have do much code work in the project code to do simulated.
And with your help , I have reach the last step of the process of the integration test.And the last problem here https://github.com/IdentityServer/IdentityServer4/issues/3067
It's seem like that is an issue,we can discuss in the new thread 😀

**Comment by westonpace** [comment]
FYI, there is more information about the unerlying but on https://github.com/dotnet/corefx/issues/27520 and here https://github.com/dotnet/corefx/issues/29651

Once that last issues is addressed this workaround should no longer be necessary.
