### ISSUE TITLE
How to get Refresh token by calling Authorization endpoint on Identity server 4

### ISSUE THREAD

**Issue by nidhilogic** [IdentityServer/IdentityServer4#2929]
I have ASP.Net MVC client application, API.Net Web API 2 Project and Identity server 4. I want to protect my API's from unauthorized access and hence I get a JWT token from IS4 and then pass in the header as Bearer token while making a call to API. All this works fine(Login to the application, getting the JWT token and then passing to API so that it gets called after authorizing the token). I am using IdentityModel 3.9.0 version to interact with Identity server 4 endpoints.

I am trying to get Refresh Token from identity Server 4 and which is where the problem is. I am not able to get it by calling an Authorization endpoint. I am confused there. Below is my file IS4 GetClients method in a config file

I was using HybridAndClientCredentials and then found out that Refresh token flow is not supported using Client Credentials.

public static IEnumerable<Client> GetClients()
{
   return new List<Client>
    {
    new Client
        {
        ClientId = "client",
        AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,

        AccessTokenLifetime = 1800,

        AllowOfflineAccess  = true,

        // secret for authentication
        ClientSecrets =
        {
            new Secret("secret".Sha256())
        },
        // scopes that client has access to
        AllowedScopes = { "nidhiapi", "offline_access" }            
    }
};

I just created a Basic console application to test my auth server and below is the code in the main method

   var discoveryClient = await DiscoveryClient.GetAsync("http://localhost:5000/");
        if (discoveryClient.IsError)
        {
            Console.WriteLine(discoveryClient.Error);
            return;
        }

        // request the token from the Auth server
    var tokenClient = new TokenClient(discoveryClient.TokenEndpoint, "client", "secret");

    var tokenResponse = await tokenClient.RequestClientCredentialsAsync("nidhiapi"); 
I am able to get AccessToken in tokenResponse variable with the defined client and HybridClientCredentials flow

As I would like to get RefreshToken from Authorize endpoint. I tried following change in my client code with same GetClients method

 var tokenResponse = await tokenClient.RequestClientCredentialsAsync("offline_access");

using the above code line I get an error as "Invalid_Scope". I read about it and found that we need to use offline_access to get a refresh token

Also, I have one more question. As I was trying to figure out a solution for this, I thought of creating a tokenClient using AuthorizeEndPoint but unless I validate my client credentials, the below statement is of no use.

one more thing: what should I be passing in RequestRefreshToken method as it expects a token

 var authTokenClient = new TokenClient(discoveryClient.AuthorizeEndpoint, "client", "secret");

 var refreshTokenResponse = await tokenClient.RequestRefreshTokenAsync("offline_access");
I then tried changing my GetClients method to use Hybrid flow only and not HybridClientCredentials as I also read that RefreshToken flow is not available for ClientCredentials.

Actually, I am confused now. My requirement is to get a token from IS4 and then refresh it using refresh token so that MVC client application does not have to log in on expiration

Suggestion/Solution, please?

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
