### ISSUE TITLE
Readability of Quickstart

### ISSUE THREAD

**Issue by kbaley** [IdentityServer/IdentityServer4#2930]
Just went through the first quickstart. I see [one issue](#2921) has been addressed but I noticed a couple of others:

- https://github.com/kbaley/IdentityServer4/blame/master/docs/quickstarts/1_client_credentials.rst#L216 => `response` should be `tokenResponse`

- https://github.com/kbaley/IdentityServer4/blame/master/docs/quickstarts/1_client_credentials.rst#L242-L245 => `client` should be `apiClient`.

I have these corrected on a fork if there isn't too much bureaucracy involved in submitting a PR.

**Comment by leastprivilege** [comment]
I think those are all fixed. Please double check.

**Comment by leastprivilege** [comment]
Then PR please on master
