### ISSUE TITLE
Google+ Platform

### ISSUE THREAD

**Issue by smlyttle** [IdentityServer/IdentityServer4#2931]
The Google+ Sign-In Feature is being shutdown on 3/7/19 (https://developers.google.com/+/web/signin/).  Do IdentityServer users need to be on a certain version to not be affected by the Google+ Sign-In shutting down?

Thank you.

**Comment by brockallen** [comment]
https://github.com/aspnet/AspNetCore/issues/6069

**Comment by gilm0079** [comment]
@brockallen or @leastprivilege , will a new build of IdentityServer4 need to be released after the Google API fix in https://github.com/aspnet/AspNetCore/pull/6338 is released or can we upgrade the asp.net core library with the current build?  Thanks!!

**Comment by brockallen** [comment]
No -- you will need to update your nuget package from Microsoft. We don't include/use google -- your host does.

**Comment by rbanks54** [comment]
@brockallen As a note the docs and quickstart samples will need to be updated, though it might be worth waiting until the various patches are released (as per https://github.com/aspnet/AspNetCore/issues/6486).

Given this comment on the aspnet core announcement in the 3.0 section:
"...considering removing the Microsoft.AspNetCore.Authentication.Google package and directing users to Microsoft.AspNetCore.Authentication.OpenIdConnect instead."
I'm not sure if we should just switch over to the oidc approach instead.

If you create a "help wanted" issue with the approach you'd prefer we can jump in and make the changes for you.

**Comment by brockallen** [comment]
Yea, good idea.

**Comment by M0ns1gn0r** [comment]
@rbanks54 will you do the changes to docs?

**Comment by rbanks54** [comment]
I haven't had time as yet (life has been getting in the way). Given this is an open source project, anyone can jump on in.

**Comment by TomCJones** [comment]
has anyone tried using oidc for google auth yet?

**Comment by brockallen** [comment]
> has anyone tried using oidc for google auth yet?

Yes, it works fine. Just configure it for implicit flow.
