### ISSUE TITLE
IdentityServer integration with ASP.NET Core 2.1+ "Default Identity"

### ISSUE THREAD

**Issue by ulrichb** [IdentityServer/IdentityServer4#2934]
The current [ASP.NET Core Identity integration guide](http://docs.identityserver.io/en/latest/quickstarts/8_aspnet_identity.html), resp. the `IdentityServerAspNetIdentity` template uses/creates a lot of (_security relevant_) code in the project (especially [AccountController](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/78d1da20c8107a86110bdeb64595ebb15f2d2e4e/host/Quickstart/Account/AccountController.cs) and [ExternalController](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/78d1da20c8107a86110bdeb64595ebb15f2d2e4e/host/Quickstart/Account/ExternalController.cs)) next to the Razor views.

Is it possible to use the [ASP.NET Core 2.1+ "Default Identity"](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio#adddefaultidentity-and-addidentity) scaffolding (and [overwriting only specific scaffolded parts](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio) if necessary)? Also it would enable all the additional features implemented in ASP.NET Core Identity like 2FA, account confirmation, password reset, ... "by free".

If it's possible, it would be nice to update the docs and the template to guide the users (+ document possible drawbacks of this approach).

**Comment by brockallen** [comment]
Our documentation is for getting you started with IdentityServer. ASP.NET Identity is sufficiently complex and can be used in so many different ways that it's not our place to document that. You should check the ASP.NET Core docs instead for that.
