### ISSUE TITLE
Default length in the IHandleGenerationService

### ISSUE THREAD

**Issue by enemaerke** [IdentityServer/IdentityServer4#2936]
**Is your feature request related to a problem? Please describe.**
We are using IdentityServer4 (and are loving it) but recently received a security review that highlighted that the access token we generate are 32bit which was not deemed large/random enough. We see that the out-of-the-box setup does use 32bit (the DefaultGrantStore relies on the default value of 32 when calling into IHandleGenerationService that use the CryptoRandom/RandomNumberGenerator). We can (and have done) inject our own full implementation to adjust this behavior but since this got highlighted in a security review perhaps this will come up for other users of this library and it should either be changed to a higher default or perhaps be easier to change to a higher default value (perhaps using some options)?

**Describe the solution you'd like**
For the least amount of work for the consumers of IdentityServer, an option that specified the desired length of the handles being generated (which could default to 32 for backwards compatibility). Not sure if such an option would fit into the existing Options classes or require a new Options class. Furthermore, incrementing the length may interfer with some of the defaults of the InputLengthRestrictions (RefreshToken/TokenHandle) so that may also need to be considered?

**Describe alternatives you've considered**
The extension points for customizing this is already in place so this feature request is mostly for making it easier to change this internal detail.

**Additional context**
We are definitely not security experts and are in some ways "blindly" accepting the security review as valid criticism. If the criticism of the 32 bits length is unfair we'd be happy to learn. From the googling we've done it seems that 32bit of randomness was considered enough for secrets as of 2015 but as machine power grows perhaps that should be reconsidered?

**Comment by leastprivilege** [comment]
32 bytes is 256 bits..that’s a lot of entropy. 

https://m.youtube.com/watch?v=S9JGmA5_unY

**Comment by enemaerke** [comment]
@leastprivilege Thanks for the quick reply. I do see that this is indeed 32 bytes and not 32 bit that is the default. I think I was a bit confused since the default parameter seemed to align with the number 32. We did run an entropy test on the generated access token ourselves and got an "excellent" rating, so it seems the security review is not evaluating the token we think they should be evaluating.

Apologize for the confusion, I'll close the issue.
