### ISSUE TITLE
Connection leak in Identity 4 Server

### ISSUE THREAD

**Issue by briankitt** [IdentityServer/IdentityServer4#2940]
I've discovered that there is a SQL connection leak in Identity4.   It is so bad, that it can't possibly run a production server.  So that means I must have something set up wrong.
I use the Dapper connector for database management.
To find the leak, I downloaded the Dapper Identity source, and debugged it.
What I am finding, is the UserManager is never disposed by IdentityServer4.  Since it is never disposed, the cleanup is never done on connections, so connections stay open forever.

I'm almost tempted to dispose the usermanager inside of my controller, but since it's inserted via DI, that seems a bit hoaky.

Here is my configuration:
#region Identity
services.ConfigureDapperConnectionProvider<SqlServerConnectionProvider>(_configuration.GetSection("DapperIdentity"))
ConfigureDapperIdentityCryptography(_configuration.GetSection("DapperIdentityCryptography"))
.ConfigureDapperIdentityOptions(new DapperIdentityOptions { UseTransactionalBehavior = false }); //Change to True to use Transactions in all operations
services.AddIdentity<Model_CustomUser, Model_CustomRole>(x =>
{
x.Password.RequireDigit = false;
x.Password.RequiredLength = 4;
x.Password.RequireLowercase = false;
x.Password.RequireNonAlphanumeric = false;
x.Password.RequireUppercase = false;

x.User.RequireUniqueEmail = false;
x.User.AllowedUserNameCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 #`~!%^*()+-={}|[]:;<>?s,.'_@&";
})
.AddDapperIdentityFor<SqlServerConfiguration>()
.AddDefaultTokenProviders();
#endregion

**Comment by scottbrady91** [comment]
Seeing as `UserManager` is part of ASP.NET Core Identity, and all integration with it is code that belongs to implementors, then I don't see how this is an IdentityServer issue.

**Comment by brockallen** [comment]
Have you identified which UserManager or at least where it's being used from? The AccountController, or elsewhere, or all instances?

**Comment by briankitt** [comment]
Primarily in calls to roll manager.  The trace I am showing, I can see that
roll manager is getting allocated, but never disposed.  As such, within
minutes I have dozens of hanging threads who's last command was to get all
roles for a user.

**Comment by briankitt** [comment]
Perhaps I am just setting it up wrong?  If this were a common problem, it'd
be a huge issue.  I'm convinced it's very isolated and perhaps I'm the only
one, which tells me I probably just set it up wrong.

**Comment by briankitt** [comment]
Anyone have any pointers?  I am positive I have a setup issue.  This is so problematic, that it's not production capable.

**Comment by brockallen** [comment]
Did you ask in the MSFT forums/issue tracker?

**Comment by brockallen** [comment]
You will have to find out where/why it's happening. If that's something from Microsoft, then they wil fix it. If it's something in our integration layer, then we'll fix it. But without something more concrete, then I'm not sure anyone can do anything about it.

**Comment by brockallen** [comment]
Any update?

**Comment by briankitt** [comment]
Sorry, I've been too tied up on other projects, I've not had time to debug
this.  Hoping to get time to debug this by Monday.
