### ISSUE TITLE
Support for Google Flutter?

### ISSUE THREAD

**Issue by BenHayat** [IdentityServer/IdentityServer4#2942]
Hello IS4 Team;

We are planning to build a .Net Web API server (as our backend REST server) using IdentityServer4 (IS4) as our back server and authentication server.
For client, we plan to use Google Flutter to build our native apps to use IS4 for authentication server.
Is there currently SDK support from IS4 for flutter so we can call IS4 to get tokens to pass to our REST Server?
If not, will there be support with the upcoming update to .Net Core 2.2 when security upgrade is released?
If not, how can we successfully use IS4 with Flutter client?

Thanks in advance!

**Comment by brockallen** [comment]
> For client, we plan to use Google Flutter to build our native apps to use IS4 for authentication server.
Is there currently SDK support from IS4 for flutter so we can call IS4 to get tokens to pass to our REST Server?

It looks like Flutter is written in dart. I don't know of any reference implementation in dart for native apps to use code+pkce flow with the system browser, but the two reference implementations for android and iOS are here:

https://github.com/openid/AppAuth-Android
https://github.com/openid/AppAuth-iOS

**Comment by BenHayat** [comment]
Hi Brock;

Yes. Flutter is written in Dart.
>> I don't know of any reference implementation in dart for native apps to use code+pkce flow with the system browser<<

Excellent point. I will contact Flutter team and raise this question. I hope your team can create support Dart natively, as Flutter can really use .Net Core backend and IS4.

As soon as I find something, I'll post it here.
Thanks for the reply.

**Comment by BenHayat** [comment]
Brock, FYI, I went ahead and created a thread in the Flutter forum and asked you question.
Here is a link in case you want to follow it directly.

https://github.com/flutter/flutter/issues/26473

Thanks!

**Comment by brockallen** [comment]
> I hope your team can create support Dart natively, as Flutter can really use .Net Core backend and IS4.

Sorry, I don't expect us to create a dart sample. But the tech stack of the client app doesn't matter -- a client would just be using protocol. 

I'll close this now, as there's nothing really specific here for us to do.

**Comment by Lords08** [comment]
Yeah I think I need this feature too. Because in my organization, for authentication and authorization always using Identity Server 4. Please consider to make this package for Flutter too.
Thanks :D

**Comment by CesarD** [comment]
I'm just starting with Flutter as well and obviously found this issue while searching for the same topic.
Like someone pointed in the Flutter project issue, I think the solution should be to use AppAuth and not asking the IdS4 team as this is not their responsibility.

This is the Flutter package that helps to implement it and they are also using an IdentityServer4 instance for doing the demo: https://pub.dev/packages/flutter_appauth

Hope it helps. I'll be testing it at some point during the next few weeks.
