### ISSUE TITLE
Unused method in Docs "Adding User Authentication with OpenID Connect"

### ISSUE THREAD

**Issue by PavelGMK** [IdentityServer/IdentityServer4#2944]
Method `GetIdentityResources` in `Config.cs` of `IdentityServer` project is newer used.
Trying to run MVC client as described in [quickstart ](http://docs.identityserver.io/en/latest/quickstarts/3_interactive_login.html) results in `Invalid scope` error.

Calling `AddInMemoryIdentityResources(Config.GetIdentityResources())` method in `ConfigureServices` method in `Startup.cs` of `IdentityServer` project resolves the problem.

```C#
var builder = services.AddIdentityServer()
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddInMemoryClients(Config.GetClients())
                .AddTestUsers(Config.GetUsers())
                .AddInMemoryIdentityResources(Config.GetIdentityResources());
```

**Comment by leastprivilege** [comment]
OK - thanks. Please PR.

**Comment by brockallen** [comment]
> Method GetIdentityResources in Config.cs of IdentityServer project is newer used.
> Trying to run MVC client as described in quickstart results in Invalid scope error.

Can you elaborate? I ran the code in our templates, our host, and in quickstart3 and the call to `GetIdentityResources` is working in all three.

**Comment by leastprivilege** [comment]
@LindaLawton could you have a look
