### ISSUE TITLE
Upgrading from 2.2 to 2.3 breaks sessionId

### ISSUE THREAD

**Issue by dviry** [IdentityServer/IdentityServer4#2945]
Only using IdentityServer4 - based on the QuickStarts.UI, no API or anything else running, no custom authentication nor any other ASP.NetCore stuff. I am using a custom ClientStore (by running services.AddIdentityCore), not sure if related.

IdentityServer4 2.2.0,
IdentityServer4.AspNetIdentity 2.1.0
Microsoft.AspNetCore 2.2.0

Simple NuGet upgrade of both IdentityServer4.* to 2.3.0 causes this error on startup:

```
InvalidOperationException: No DefaultAuthenticateScheme found.
IdentityServer4.Services.DefaultUserSession.GetCookieSchemeAsync()
```

So after some research I've managed to get "over it" (not sure though if correct) by adding the following to the .AddIdentityServer(options):
```
options.Authentication.CookieAuthenticationScheme = IdentityServerConstants.DefaultCookieAuthenticationScheme;
```

Only to (later) discover that althought sessionIds are assigned (and log is error free), the cookie idsrv.session never gets created causing stuff like Backchannel signout to stop working (since the iframeUrl never gets set since there is no sessionId).

I tried searching through the changes but 2.3.0 includes (IMO) a lot of changes and I am not able to track down what am I doing wrong / missing.

Any ideas?

Vielen Dank im Voraus,
Leon

**Comment by dviry** [comment]
After further investigations I got the cookie back (for whatever reason the CookieLifeTime was set to Zero).

Question still remains whether the .CookieAuthenticationScheme I manually added to the IdentityOptions is correct.

Thanks in advance

**Comment by dviry** [comment]
That is also incorrect -  even though I am not really using AspNetCore Authentication, I had to add this above:

```c#
services.AddAuthenticationCore(o =>
            {
                o.DefaultAuthenticateScheme = IdentityServerConstants.DefaultCookieAuthenticationScheme;
                o.DefaultSignOutScheme = IdentityServerConstants.SignoutScheme;
            });
```

Now it seems to be working as expected - not sure where this breaking change stems from (AspNetCore 2.2 or IdentityServer 2.3).

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by dviry** [comment]
Sure, if you think my solution above is the right setting then I'm set.

Thanks

**Comment by brockallen** [comment]
> Sure, if you think my solution above is the right setting then I'm set.

As Dom recently stated, this is not a forum. It's an issue tracker for IdentityServer bugs and feature requests.
