### ISSUE TITLE
AccessTokenType.Reference does not work! Still returns JWT

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer4#2946]
I have added the following to the definition of my client as per the documentations instructions:
`AccessTokenType =  AccessTokenType.Reference,`

But still when I hit the ../connect/token endpoint with proper username and password, I will get a JWT access token (and not a reference token). I am using the Resource Owner flow. Is there anything extra that has to be done and is not mentioned in the docs?

**Comment by AutismPatient** [comment]
You must understand what this configuration parameter does

**Comment by leastprivilege** [comment]
That's all thats necessary. Check the samples in our samples repo.

**Comment by behrooz66** [comment]
Thanks for the mean language you guys use every time there is a question in this forum that seems too low level for you. I have read the document on the reference tokens here:
[](http://docs.identityserver.io/en/latest/topics/reference_tokens.html)

and maybe the reason I didn't "understand" is because documentation is terrible. Thanks anyway, close the thread.
