### ISSUE TITLE
Should I merge identity server database with application database

### ISSUE THREAD

**Issue by raminassar** [IdentityServer/IdentityServer4#2950]
Hello,

I recently started from scratch to implement a new application, so I have created a new application with its own database and I used Identity Server 4 with ASP.NET Identity which has a separate persistence database and I named it Identity_Server. 

The plan is that in near future I will start developing another applications which will be clients in the central Identity service provider (Identity Server 4).

The problem which I'm facing right now, in the application I'm developing I have auditing columns like CreatedById & LastUpdatedById which will capture the user id. As will as I will have a logs table where I will store the user id as a foreign key.
Storing user ids is not a problem because I can capture it once user logged into the application but the problem that in UI I wanted to present more meaningful claim like username or full name.

how I can make the relation between application entities and identity server user entity where both are in separate db context and separate physical databases. 

Shall I change the architecture and keep all my applications entities in same database with identity server?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
