### ISSUE TITLE
SQL Scripts for current MS SQL database schema

### ISSUE THREAD

**Issue by rmbrunet** [IdentityServer/IdentityServer4#2951]
The link to the SQL Scripts in the documentation still broken.

https://github.com/IdentityServer/IdentityServer4.EntityFramework/tree/release/src/Host/Migrations/IdentityServer

**Comment by brockallen** [comment]
Which link in the docs?

**Comment by rmbrunet** [comment]
In this page

http://docs.identityserver.io/en/release/quickstarts/8_entity_framework.html

there is a note with a link to where the SQL Scripts are for the database are located. Its returning 404.

**Comment by brockallen** [comment]
The release branch is no more -- it's master and dev, IIRC.
