### ISSUE TITLE
Best work flow for react native mobile app

### ISSUE THREAD

**Issue by AkhilRajMR** [IdentityServer/IdentityServer4#2952]
Hi @brockallen and   @MikeBeaton ,
I am created a identity-server with grant type "password" for my react native mobile app.  I got its work flow and i implemented that. but now i need a facebook login in that app. i also like to change that to authorization code flow. which is the best method to implement both(facebook with Authorization code) login.? 
I think hybrid is safe for both login. but i didn't get any sample implementation of that type. Is it possible using identityserver ? 
can you share any link regarding that.?

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by AkhilRajMR** [comment]
@leastprivilege  "See here for more details." link showing a page not found exception.

**Comment by leastprivilege** [comment]
sorry! 

See [here](https://identityserver4.readthedocs.io/en/lastest/intro/support.html) for more details.

**Comment by AkhilRajMR** [comment]
Thanks, @leastprivilege ,  I have partially completed an Authorisation Code flow. I have achieved the login scenario. After clicking 'Yes, Allow' debugger hit the 'IsActiveAsync()' in Profile service with proper claims. But  the app still creates an error in postman like :

     'Could not complete OAuth 2.0 login. Check Postman Console for more details.'

Postman Console shows an Access denied message.

I have spent a lot of effort on that but I can't fix it. Please suggest an idea to overcome that.

Note: I am using my own DB for store user data.
