### ISSUE TITLE
Minor incorrect statement in hybrid flow quickstart docs

### ISSUE THREAD

**Issue by mstancombe** [IdentityServer/IdentityServer4#2953]
on the page
https://github.com/IdentityServer/IdentityServer4/blob/master/docs/quickstarts/5_hybrid_and_api_access.rst

there is a line
"When you run the MVC client, there will be no big differences, besides that the consent screen now asks you for the additional API and offline access scope."

This is not accurate, as now that the id and access token are requested, none of the claims apart from sub will show.

the ID Server shows the reason:
"In addition to an id_token, an access_token was requested. No claims other than sub are included in the id_token. To obtain more user claims, either use the user info endpoint or set AlwaysIncludeUserClaimsInIdToken on the client configuration."

I think the quickstart should set the AlwaysIncludeUserClaimsInIdToken as one of the changes, and possibly discuss why it does this.  I don't have enough background in ID server to do this PR myself, I'm just doing the quickstart so thought I'd log this here, hope that's ok :) 

(btw.. brilliant docs so far :+1: :+1: )

**Comment by leastprivilege** [comment]
@LindaLawton could you have a look
