### ISSUE TITLE
Cookie: idsrv & idsrv.external - Possibility for changing name

### ISSUE THREAD

**Issue by sekoch** [IdentityServer/IdentityServer4#2956]
Hi,

I didn't find it in the documentation or anywhere else.

If you build a multi tenancy identityserver4 setup, where the tenants are resolved by path (not domain, that wouldn't be a problem), is it possible to change the names of the cookies at runtime (after retrieving the http context for resolving the tenant)? I don't find any solution yet or which changes I should make via DI.

Maybe you can give me some advice or point me to the correct solution.

**Comment by 40345839668** [comment]
After the control panel, try the user's Hesps you can also find them using the PC in the notifications or messages panel on the bottom right corner of your monitor or the search Toolbar on your monitor.
Control Panel  All Control Panel items

**Comment by leastprivilege** [comment]
The names cannot be changed right now.

**Comment by sekoch** [comment]
@leastprivilege: Thank you for the answer! 

I know that ASP.NET Core or IdentityServer itself does not support multi tenancy, but multi tenancy can be simple implemented with a middleware (for checking the path or domain). So no multi tenant feature for the identity server or .net core is needed, but maybe some additional customizing functions I and some others (I think) would appreciate for enabling multi tenancy for their needs.

I saw that the domain and path attributes for the cookies should be customizable?! in a next release (tagged with 2.4). Maybe the tenant route path (like XY.com/tenantZ) can be set there ?!

Or do you have any other ideas that a multi tenancy identity server based on the path and not domain does not share the same cookie? Currently a user log in and is logged in in every tenant due the same cookie. 

- Overwrite the cookieauthoptions via services? (remove it from the service collection and implement an own?)
- encapulates the identity server to be set up in a separate pipeline (But I think it isn't a good solution). For instance: app.UsePerTenant((ctx, builder) => { builder.UseIdentityServer(), ... }. I saw this in another multi tenancy project on github (saaskit).
- Does the cookie path based on the tenant route would fit?

Thank you in advance!

**Comment by brockallen** [comment]
This isn't something we're in a position to design and support in the core implementation at this time. If you can get it working, then great, but we can't support that now. Thanks.
