### ISSUE TITLE
issue with GetDiscoveryDocumentAsync(IDPBaseURL)

### ISSUE THREAD

**Issue by fawadali123** [IdentityServer/IdentityServer4#2964]
I am trying to deploy IDS4 on server. everything works fine both on http and https.  but when i try to access  client.GetDiscoveryDocumentAsync(IDPBaseURL). it returns error. if it is on http is says https required. if on https it gives error "The remote certificate is invalid according to the validation procedure". 
I know its not an issue in IDS but unable to get any solution from SO and gitter so posting it here. 

Thanks,

**Comment by leastprivilege** [comment]
Wrong repo. Please move to: https://github.com/IdentityModel/IdentityModel2
