### ISSUE TITLE
connect/userinfo returns 403 forbidden

### ISSUE THREAD

**Issue by barron9** [IdentityServer/IdentityServer4#2965]
i can get token from server and i am trying to auth the token validity and get the userinfo with this api.but it returns 403

http://docs.identityserver.io/en/latest/endpoints/userinfo.html

`{"issuer":"http://localhost:5000","jwks_uri":"http://localhost:5000/.well-known/openid-configuration/jwks","authorization_endpoint":"http://localhost:5000/connect/authorize","token_endpoint":"http://localhost:5000/connect/token","userinfo_endpoint":"http://localhost:5000/connect/userinfo","end_session_endpoint":"http://localhost:5000/connect/endsession","check_session_iframe":"http://localhost:5000/connect/checksession","revocation_endpoint":"http://localhost:5000/connect/revocation","introspection_endpoint":"http://localhost:5000/connect/introspect","device_authorization_endpoint":"http://localhost:5000/connect/deviceauthorization","frontchannel_logout_supported":true,"frontchannel_logout_session_supported":true,"backchannel_logout_supported":true,"backchannel_logout_session_supported":true,"scopes_supported":["api1","offline_access"],"claims_supported":[],"grant_types_supported":["authorization_code","client_credentials","refresh_token","implicit","urn:ietf:params:oauth:grant-type:device_code"],"response_types_supported":["code","token","id_token","id_token token","code id_token","code token","code id_token token"],"response_modes_supported":["form_post","query","fragment"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"subject_types_supported":["public"],"id_token_signing_alg_values_supported":["RS256"],"code_challenge_methods_supported":["plain","S256"]}`

full dummy project is here
https://github.com/barron9/identityserver4

**Comment by brockallen** [comment]
Check your IS logs.

**Comment by barron9** [comment]
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:5003/connect/introspect application/x-www-form-urlencoded 644
IdentityServer4.Hosting.EndpointRouter:Debug: Request path /connect/introspect matched to endpoint type Introspection
IdentityServer4.Hosting.EndpointRouter:Debug: Endpoint enabled: Introspection, successfully created handler: IdentityServer4.Endpoints.IntrospectionEndpoint
IdentityServer4.Hosting.IdentityServerMiddleware:Information: Invoking IdentityServer endpoint: IdentityServer4.Endpoints.IntrospectionEndpoint for /connect/introspect
IdentityServer4.Endpoints.IntrospectionEndpoint:Debug: Starting introspection request.
IdentityServer4.Validation.BasicAuthenticationSecretParser:Debug: Start parsing Basic Authentication secret
IdentityServer4.Validation.SecretParser:Debug: Parser found secret: BasicAuthenticationSecretParser
IdentityServer4.Validation.SecretParser:Debug: Secret id found: client
IdentityServer4.Validation.ApiSecretValidator:Error: No API resource with that name found. aborting
IdentityServer4.Endpoints.IntrospectionEndpoint:Error: API unauthorized to call introspection endpoint. aborting.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 14.353ms 401 
Microsoft.AspNetCore.Server.Kestrel:Information: Connection id "0HLJVO3RHTUPP", Request id "0HLJVO3RHTUPP:00000002": the application completed without reading the entire request body.
The thread 0x3928 has exited with code 0 (0x0).
The thread 0x4f94 has exited with code 0 (0x0).

**Comment by barron9** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/SampleAspNetWebApi/Startup.cs#L17-L25
