### ISSUE TITLE
when use AddAspNetIdentity, the external providers can't redirect

### ISSUE THREAD

**Issue by deeyi2000** [IdentityServer/IdentityServer4#2966]
### Issue / Steps to reproduce the problem
when I use use AddAspNetIdentity, the external providers can't redirect to client 
var builder = services.AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;
            })
                .AddAspNetIdentity<IdentityExpressUser>()
                // this adds the config data from DB (clients, resources, CORS)
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = db =>
                        db.UseSqlite(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = db =>
                        db.UseSqlite(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    // options.TokenCleanupInterval = 15; // interval in seconds. 15 seconds useful for debugging
                });

### Relevant parts of the log file

```
[21:22:07 Debug] IdentityServer4.EntityFramework.Stores.ResourceStore
Found ["api1"] API scopes in database

[21:22:07 Debug] IdentityServer4.EntityFramework.Stores.ResourceStore
Found ["openid", "profile"] identity scopes in database

[21:22:07 Debug] IdentityServer4.EntityFramework.Stores.ResourceStore
Found ["api1"] API scopes in database

[21:22:07 Debug] IdentityServer4.Validation.AuthorizeRequestValidator
Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator

[21:22:07 Information] IdentityServer4.Endpoints.AuthorizeCallbackEndpoint
ValidatedAuthorizeRequest
{"ClientId": "client", "ClientName": "CAS Test", "RedirectUri": "https://localhost:9443/simple-web-app/openid_connect_login", "AllowedRedirectUris": ["https://localhost:9443/simple-web-app/openid_connect_login"], "SubjectId": "d5255077-c587-4c6c-addf-2fe1fc4a9fb3", "ResponseType": "code", "ResponseMode": "query", "GrantType": "authorization_code", "RequestedScopes": "openid profile api1", "State": "14dab2b9d5358", "UiLocales": null, "Nonce": "8eea809debb0", "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": null, "MaxAge": null, "LoginHint": null, "SessionId": "2a6dcfc56a26bba55c1cbb24cad907ad", "Raw": {"response_type": "code", "client_id": "client", "scope": "openid profile api1", "redirect_uri": "https://localhost:9443/simple-web-app/openid_connect_login", "nonce": "8eea809debb0", "state": "14dab2b9d5358"}, "$type": "AuthorizeRequestValidationLog"}

[21:22:07 Warning] IdentityServer4.AspNetIdentity.ProfileService
 **No user found matching subject Id: d5255077-c587-4c6c-addf-2fe1fc4a9fb3**

[21:22:07 Information] IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator
Showing login: User is not active

[21:22:07 Debug] IdentityServer4.Validation.AuthorizeRequestValidator
Start authorize request protocol validation
```

**Comment by brockallen** [comment]
You're going to have to investigate further to understand and explain if and what the bug is in IdentityServer. The external provider coordination is your code, not IdentityServer.

**Comment by brockallen** [comment]
Any update?

**Comment by deeyi2000** [comment]
yes,I create a project with is4admin template, it has same problem,and I find out _userManager.CreateAsync  can run succed,but it can't write to database.so, when redirect to Authorize/Callback endpoint, it can't find user in database,then redirect to login.
ps: all of motheds in _userManager perfrom write database can't really write!

**Comment by brockallen** [comment]
Ah you're using the is4admin template? They set the auto save changes to false. You can set it to true.

// @scottbrady91

**Comment by brockallen** [comment]
Ah you're using the is4admin template? They set the auto save changes to false. You can set it to true.

https://github.com/aspnet/AspNetIdentity/blob/a24b776676f12cf7f0e13944783cf8e379b3ef70/src/Microsoft.AspNet.Identity.EntityFramework/UserStore.cs#L111

// @scottbrady91
