### ISSUE TITLE
Error: Invalid response Content-Type: text/html

### ISSUE THREAD

**Issue by baronnt** [IdentityServer/IdentityServer4#2967]
Hi,

I have implemented the Identityserver4 which is being consumed by an Angular 7 client. When running the IdentityServer4 in localhost, everything work fine.
But after deploying it in Dev environment, it throws the following error in the client while trying to authenticate:

ERROR Error: Uncaught (in promise): Error: Invalid response Content-Type: text/html, from URL: identityServer_url/.well-known/openid-configuration

![image](https://user-images.githubusercontent.com/43637534/51478379-f3408280-1d93-11e9-93a2-f2d1083432fe.png)

**Comment by brockallen** [comment]
I suspect there's an html error paging being rendered from that endpoint, which indicates something is broken/misconfigured in your IS. Check your logs.

**Comment by brockallen** [comment]
Any update?

**Comment by baronnt** [comment]
Yes, it turns out that IIS was not rendering html properly. Now its working. Thanks.
