### ISSUE TITLE
How to use client oidc serve to the identityserver protected api

### ISSUE THREAD

**Issue by jingliancui** [IdentityServer/IdentityServer4#2969]
I have config the oidc client(WPF) and the IdentityServer with oidc and aspnetidentity.
Then after i use wpf oidc login succeed. I use wpf's httpclient with token to serve to the identityserver's protected api which use [Authorize] attribute .
Result is the httpclient's result is html that redirect me to to login page content.
Then i add the the code to the identityserver's service method 
```
            services
                .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    // base-address of your identityserver
                    options.Authority = "https://localhost:44336/";

                    // name of the API resource
                    options.Audience = "api1";

                    options.RequireHttpsMetadata = false;

                });
```
And add `app.UseAuthentication();` to the configure method .

Reuslt still redirect wpf's httpclient to the login page html content.

So ,Is it I should use a api project to manage the oidc's aspnetidentity account by opera the database?
Or is there some way to let the identityserver as the same as the api project?

**Comment by jingliancui** [comment]
for example:
after add [Authorize] to the action in the Identityserver(not the api project,It's the identityserver's controller),
the wpf(use oidc token) still can not serve the action which is added [Authorize] .
But if I use webbrowser(Microsoft Edge) to login .After this , I can serve the action.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by jingliancui** [comment]
Ok,after bing searched.
Solution is in identity server 's
Startup Service configure:
```
            services
                .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    // base-address of your identityserver
                    options.Authority = "https://localhost:44336/";

                    // name of the API resource
                    options.Audience = "api1";

                    options.RequireHttpsMetadata = false;

                });
```

Then in identityserver's controller add this:
`AuthenticationSchemes="Bearer"`
for example:
        [Authorize(AuthenticationSchemes="Bearer",Roles = "Administrator")]
        public IActionResult AdminCheck()
        {
            return Content("OK");
        }

**Comment by jingliancui** [comment]
https://github.com/brockallen/IdentityServerAndApi/blob/master/IdentityServerHost/TestController.cs
