### ISSUE TITLE
String  vs string typo in IdentityServer4.AspNetIdentity

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#2971]
### Issue / Steps to reproduce the problem

I just ran across a typo while digging in the code we have a small issue with 

>String.IsNullOrWhiteSpace(phoneNumber)  Vs  string.IsNullOrWhiteSpace(phoneNumber)

[UserClaimsFactory.cs#L53](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/826829a65402a1943c1cc6d65476ca536a7cb7b4/src/UserClaimsFactory.cs#L53)

[UserClaimsFactory.cs#L67](https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/826829a65402a1943c1cc6d65476ca536a7cb7b4/src/UserClaimsFactory.cs#L67)

Also IIR you guys normally have this nice extension method you use for IsNullOrWhiteSpace.

Note: Happy to fix this myself.  I would just have to go find out if the IsNullOrWhiteSpace extension method is usable in the IdentityServer4.AspNetIdentity project or not.

**Comment by LindaLawton** [comment]
String  <-- capital letter `S`

[What is the difference between String and string in C#?](https://stackoverflow.com/q/7074/1841839)

**Comment by brockallen** [comment]
IMO, since these are static methods I prefer the class name.
