### ISSUE TITLE
TokenRequestValidator.ValidateAuthorizationCodeRequestAsync: Bad logging for invalid redirect_uri 

### ISSUE THREAD

**Issue by enikitin** [IdentityServer/IdentityServer4#2972]
### Issue / Steps to reproduce the problem

Obtain an authorization code with a PascalCase _redirect_uri_ (**http://localhost:46688/AuthCodeClient.html** in my case), then try to obtain an access token with a lowercase _redirect_uri_ (**http://localhost:46688/authcodeclient.html**). 
Response:
{
  "status": 400,
  "statusText": "Bad Request",
  "response": "{\"error\":\"unauthorized_client\"}"
}

The problem is insufficient/wrong log records. 
https://github.com/IdentityServer/IdentityServer4/blob/master/src/Validation/Default/TokenRequestValidator.cs : 264

LogError("Invalid redirect_uri: _{redirectUri}_, expected _{exceptRedirectUri}_", redirectUri, _validatedRequest.AuthorizationCode.RedirectUri);
 
_{redirectUri}_ and _{exceptRedirectUri}_ don't get resolved.

Also, would you consider case-insensitive comparison?

https://github.com/IdentityServer/IdentityServer4/blob/master/src/Validation/Default/TokenRequestValidator.cs : 262
if (redirectUri.Equals(_validatedRequest.AuthorizationCode.RedirectUri, **StringComparison.Ordinal**) == false) ...

### Relevant parts of the log file

[15:06:05.05 Debug] IdentityServer4.Validation.TokenRequestValidator
Start token request validation

[15:06:05.05 Debug] IdentityServer4.Validation.TokenRequestValidator
Start validation of authorization code token request

[15:06:05.05 Error] IdentityServer4.Validation.TokenRequestValidator
Error logging Index was outside the bounds of the array., request details: {"ClientId": "test.client", "ClientName": "Test Client", "GrantType": "authorization_code", "Scopes": null, "AuthorizationCode": "48eb80af6665b723d254c0f41965a8cce805d24021193f2dd07114e38ebd8814", "RefreshToken": null, "UserName": null, "AuthenticationContextReferenceClasses": null, "Tenant": null, "IdP": null, "Raw": {"grant_type": "authorization_code", "code": "48eb80af6665b723d254c0f41965a8cce805d24021193f2dd07114e38ebd8814", "redirect_uri": **"http://localhost:46688/authcodeclient.html"**, "scope": "offline_access openid"}, "$type": "TokenRequestValidationLog"}

**Comment by leastprivilege** [comment]
Will look into it. thanks!

**Comment by brockallen** [comment]
I've been trying to repro this in our unit tests, but I can't seem to. I suspect the exception is thrown from a specific logger. What types do you have configured in your app?

**Comment by enikitin** [comment]
1. I suggest that URL comparison should be consistent - either case-sensitive everywhere or case-insensitive everywhere.

Case-insensitive comparison:
https://github.com/IdentityServer/IdentityServer4/blob/master/src/Validation/Default/StrictRedirectUriValidator.cs: 30
```
return uris.Contains(requestedUri, StringComparer.OrdinalIgnoreCase);
```
This test passes:
```
[Fact]
public async Task Uri_Comparison_Case_Insensitive()
{
	var client = new Client { RedirectUris = new[] { "https://server/cb" } }; // Lowercase
	var requestedUri = "HTTPS://SERVER/CB"; // Uppercase
	var strictRedirectUriValidator = new StrictRedirectUriValidator();
	var result = await strictRedirectUriValidator.IsRedirectUriValidAsync(requestedUri, client);
	result.Should().BeTrue(); // Passes in spite of different case
}
```
Case-sensitive comparison:
https://github.com/IdentityServer/IdentityServer4/blob/master/src/Validation/Default/TokenRequestValidator.cs: 262
```
if (redirectUri.Equals(_validatedRequest.AuthorizationCode.RedirectUri, StringComparison.Ordinal) == false)
```

This test fails:
```
[Fact]
[Trait("Category", Category)]
public async Task Valid_Code_Request()
{
	var client = await _clients.FindEnabledClientByIdAsync("codeclient");
	var grants = Factory.CreateAuthorizationCodeStore();

	var code = new AuthorizationCode
	{
		CreationTime = DateTime.UtcNow,
		Subject = new IdentityServerUser("123").CreatePrincipal(),
		ClientId = client.ClientId,
		Lifetime = client.AuthorizationCodeLifetime,
		RedirectUri = "HTTPS://SERVER/CB", // Uppercase
		RequestedScopes = new List<string>
		{
			"openid"
		}
	};

	var handle = await grants.StoreAuthorizationCodeAsync(code);

	var validator = Factory.CreateTokenRequestValidator(
		authorizationCodeStore: grants);

	var parameters = new NameValueCollection();
	parameters.Add(OidcConstants.TokenRequest.GrantType, OidcConstants.GrantTypes.AuthorizationCode);
	parameters.Add(OidcConstants.TokenRequest.Code, handle);
	parameters.Add(OidcConstants.TokenRequest.RedirectUri, "https://server/cb"); // Lowercase

	var result = await validator.ValidateRequestAsync(parameters, client.ToValidationResult());

	// Will fail because of different case
	result.IsError.Should().BeFalse();
}
```
2. Your unit tests don't catch errors in TokenRequestValidator.LogError().
These lines will not work as expected:

TokenRequestValidator.cs
(102,17) LogError("Client {clientId} has invalid protocol type for token endpoint: expected {expectedProtocolType} but found {protocolType}", ↵ _validatedRequest.Client.ClientId, ↵ IdentityServerConstants.Prot…
(163,21) LogError("Custom token request validator error {error}", customValidationContext.Result.Error);
(212,17) LogError("Invalid authorization code: {code}", code);
(220,17) LogError("Authorization code expired: {code}", code);
(237,17) LogError("Client {0} is trying to use a code from client {1}", _validatedRequest.Client.ClientId, authZcode.ClientId);
(264,17) LogError("Invalid redirect_uri: {redirectUri}, expected {exceptRedirectUri}", ↵ redirectUri, _validatedRequest.AuthorizationCode.RedirectUri)
(299,21) LogError("Unexpected code_verifier: {codeVerifier}. This happens when the client is trying to use PKCE, but it is not enabled. Set RequirePkce to true.", codeVerifier);
(312,17) LogError("User has been disabled: {subjectId}", _validatedRequest.AuthorizationCode.Subject.GetSubjectId());
(330,17) LogError("{clientId} not authorized for client credentials flow, check the AllowedGrantTypes of the client", _validatedRequest.Client.ClientId);
(344,17) LogError("{clientId} cannot request OpenID scopes in client credentials flow", _validatedRequest.Client.ClientId);
(350,17) LogError("{clientId} cannot request a refresh token in client credentials flow", _validatedRequest.Client.ClientId);
(367,17) LogError("{clientId} not authorized for resource owner flow, check the AllowedGrantTypes of client", _validatedRequest.Client.ClientId);
(452,17) LogError("User has been disabled: {subjectId}", resourceOwnerContext.Result.Subject.GetSubjectId());
(550,17) LogError("{clientId} does not have the custom grant type in the allowed list, therefore requested grant is not allowed", _validatedRequest.Client.ClientId);
(559,17) LogError("No validator is registered for the grant type: {grantType}", _validatedRequest.GrantType);
(586,21) LogError("Invalid extension grant: {error}", result.Error);
(612,21) LogError("User has been disabled: {subjectId}", result.Subject.GetSubjectId());
(653,21) LogError("No allowed scopes configured for {clientId}", _validatedRequest.Client.ClientId);
(693,17) LogError("{clientId} is missing code challenge or code challenge method", _validatedRequest.Client.ClientId);
(712,17) LogError("Unsupported code challenge method: {codeChallengeMethod}", authZcode.CodeChallengeMethod);
(760, 21)_logger.LogError("Error logging {exception}, request details: {@details}", ex.Message, details);

**Comment by leastprivilege** [comment]
This issue deals with logging - please open a separate one for case sensitivity.

**Comment by enikitin** [comment]
Issue opened https://github.com/IdentityServer/IdentityServer4/issues/3011

Error with stack trace:
```
Index was outside the bounds of the array.

   at Microsoft.Extensions.Logging.Internal.LogValuesFormatter.GetValue(Object[] values, Int32 index)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.get_Item(Int32 index)
   at Microsoft.Extensions.Logging.Internal.FormattedLogValues.GetEnumerator()+MoveNext()
   at Serilog.Extensions.Logging.SerilogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at IdentityServer4.Validation.TokenRequestValidator.LogError(String message, Object[] values) in C:\local\identity\server4\IdentityServer4\src\Validation\Default\TokenRequestValidator.cs:line 756
```

**Comment by leastprivilege** [comment]
OK - check the latest commit 

https://github.com/IdentityServer/IdentityServer4/commit/1278ae692caf7a2d9dd6196875ffb4e873de00a8

I converted everything to structured data.

**Comment by enikitin** [comment]
Good, thanks
