### ISSUE TITLE
tutorial links are dead

### ISSUE THREAD

**Issue by andrewryan-andie** [IdentityServer/IdentityServer4#2973]
1. Go to any Quickstart samples [link here](https://github.com/IdentityServer/IdentityServer4.Samples/tree/master/Quickstarts)

2. Go to any sample, say client credentials [link here](https://github.com/IdentityServer/IdentityServer4.Samples/tree/master/Quickstarts/1_ClientCredentials)

3. Go to readme.md and click on tutorial link, which is [this link](http://docs.identityserver.io/en/release/quickstarts/1_client_credentials.html).

4. It returns 404 / Maze found, which a very beautiful (!) ASCII message

This page does not exist yet.

**Comment by leastprivilege** [comment]
fixed. thanks.
