### ISSUE TITLE
Authorization Code Flow Without using MVC

### ISSUE THREAD

**Issue by granthoff1107** [IdentityServer/IdentityServer4#2974]
I'm using angular and to Obtain my Authorization Code.  I'm trying to figure out how to obtain my tokens through Identity Server 4.

When I do this using MVC I can resolve my request (using as stated in the examples)

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Action(nameof(ExternalLoginCallback), "Account", new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties, provider);
        }

In the examples I don't see a callback which obtains the Authorization code and converts them into Access Tokens.   Considering this handles the Authorization Code Flow fine, I feel like there is a way to do so I'm just not sure how?

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
