### ISSUE TITLE
In Hybrid flow, refresh access_token doesn't use refersh_token. After I clean all the data in IPersistedGrantStore, the access_token always can refresh

### ISSUE THREAD

**Issue by woailibain** [IdentityServer/IdentityServer4#2977]
I use the sample from https://github.com/IdentityServer/IdentityServer4.Samples/tree/master/Quickstarts/5_HybridFlowAuthenticationWithApiAccess 
I modify the client's AccessTokenLifetime to 600 in QuickStartIdentityServer. I make sure the grant type is HybridAndClientCredentials
I run the mvcClient,IdentityServer and login success. after 20 mins, I clean all the data in IPersistedGrantStore.  than I refresh the mvcClient page, the page redirect to IdentityServe, regenerate access_token and refresh_token ,and redirect to mvcClient page!

the question is ,why the access_token can refresh without a validate refresh_token. I was delete all the token by IPersistedGrantStore.RemoveAllAsync("subjectId"). Is it correct? ?

I know the cookies already exist in IdentityServer domain. I know the mvcClient was logged in before.
although the cookies exist, it just contain an expired access_toke, just contain an invalidate refresh_token which I deleted in IPersistedGrantStore before .

I find some help from others, but no one can explain. As I know, refresh_token is the requirement for refresh the access_token.

**Comment by brockallen** [comment]
I think in QS5 we are still using the in-memory grant store. So what data are you clearing and how?

**Comment by woailibain** [comment]
here is the constructor in AccountController in IdentityServer 

```
IPersistedGrantStore _persistedGrantStore;


        public AccountController(
            IIdentityServerInteractionService interaction,
            IClientStore clientStore,
            IHttpContextAccessor httpContextAccessor,
            IAuthenticationSchemeProvider schemeProvider,
            IEventService events,
            IPersistedGrantStore persistedGrantStore,
            TestUserStore users = null)
        {
            // if the TestUserStore is not in DI, then we'll just use the global users collection
            _users = users ?? new TestUserStore(TestUsers.Users);
            _interaction = interaction;
            _events = events;
            _account = new AccountService(interaction, httpContextAccessor, schemeProvider, clientStore);
            _persistedGrantStore = persistedGrantStore;
        }
```

**Comment by woailibain** [comment]
@brockallen , no matter what the GrantStore is, I can add or delete the persistedGrants by using IPersistedGrantStore, isn't it？

**Comment by woailibain** [comment]
Is it a bug ? If no, please help

**Comment by scottbrady91** [comment]
Both the in-memory and EF implementations of `IPersistedGrantStore` are working correctly. Both add and delete functionality are working as expected.

It might be worth looking into what implementation of `IPersistedGrantStore` you are using, and if that implementation is behaving as you expect.

**Comment by woailibain** [comment]
@scottbrady91 , I used Quick Start 5 sample which use the in-memory implementation, it can add and delete the data. 
But my trouble is the access_token can always be refresh with the invalidate refresh_token which I had deleted in HybridAndClientCredentials flow.

In Authorize Endpoint , is it any refresh_token checking when the access_token refresh in HybridAndClientCredentials flow?

**Comment by brockallen** [comment]
Any update?

**Comment by woailibain** [comment]
The problem still not solve.!!!

**Comment by brockallen** [comment]
> The problem still not solve 

Please investigate further and produce a concrete repro for the issue. That was we can repo it and if it's a bug we can fix it.
