### ISSUE TITLE
Add Client.Id and or Client.Name to UserLoginSuccessEvent and UserLoginFailureEvent

### ISSUE THREAD

**Issue by faithword** [IdentityServer/IdentityServer4#2978]
We use the `UserLoginSuccessEvent` and `UserLoginFailureEvent` raised during user authentication/token validation to record user login attempts using a custom `IEventSink` implementation.
However, it is not straightforward to determining which Client the user is login in from. 

We currently determine which client the login attempt is coming from through other means but it will be nice and easier to add these fields (Client.Id and Client.Name) to these events when the events are raised.

Both `TokenIssuedSuccessEvent` and `TokenIssuedFailureEvent` events contains these fields and are populated when these events are raised and understandably so. Could the same be done for the User Login events?

**Comment by KEPochka** [comment]
Look forward to the realization of this beautiful feature :)

**Comment by jjavierdguezas** [comment]
+1 to this feature... any updates?

**Comment by jjavierdguezas** [comment]
@faithword do you have any workaround for this while this feature is included (if it happens) ?
I need to known the `ClientId` in the `EventIds.UserLoginSuccess` and `EventIds.UserLogoutSuccess`

**Comment by brockallen** [comment]
PR submitted. Please look and see if that does what you're asking for.

**Comment by brockallen** [comment]
merged.
