### ISSUE TITLE
[Question] unexpected id_token from refresh token response

### ISSUE THREAD

**Issue by StevenLiekens** [IdentityServer/IdentityServer4#2979]
As stated in #89, an id_token can only be requested using a flow specified in OpenID Connect. I was surprised to learn that refresh_token flow **does** produce id_token responses when the refresh token was obtained from a custom grant_type.

**Comment by StevenLiekens** [comment]
So the question is: shouldn't the grant store remember which grant was used to obtain a refresh token? And then decide whether the refresh_token can be used to obtain an id_token.

**Comment by brockallen** [comment]
Yea, we do currently if the original request contains identity scopes.

**Comment by StevenLiekens** [comment]
So this works as intended, but then what's the point in issuing id_tokens for OIDC-grants only if all grant types can be used to obtain a refresh token? Maybe identity scopes should not be allowed for non-OIDC grant types?

**Comment by brockallen** [comment]
Is this somehow adversely affecting you in some way?

**Comment by StevenLiekens** [comment]
Not at all, just thought it was weird.
