### ISSUE TITLE
Sorry, there was an error : unauthorized_client

### ISSUE THREAD

**Issue by baronnt** [IdentityServer/IdentityServer4#2981]
Hi,
I have implemented an angular 7 client which consumes the Identity Server 4. When running the client in localhost, its working fine. But when I deploy it in Dev environment, its giving me a "unauthorized_client" error.

Here is the client configuration in Identity Server 4:

 new Client
            {
                ClientId = "client_angular",
                ClientName = "UserApp",
                AllowedGrantTypes = IdentityServer4.Models.GrantTypes.Implicit,

                AllowedScopes =
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    IdentityServerConstants.StandardScopes.Email,
                    "helpdesk_service_api.read",
                    "helpdesk_service_api.write"
                },

                RedirectUris = {"http://client-url/auth-callback"}, 
                PostLogoutRedirectUris = {"http://client-url"}, 
                AllowedCorsOrigins = {"http://client-url"}, 

                AllowAccessTokensViaBrowser = true,
                AccessTokenLifetime= 3600,
                 RequireClientSecret = false,

            }

And on the angular client side, this is how its configured:

export function getClientSettings(): UserManagerSettings {
  return {
      authority: 'http://identity-server-url', 
      client_id: 'client_angular',
      redirect_uri: 'http://client-url/auth-callback', 
      post_logout_redirect_uri: 'http://client-url', 
      response_type:"id_token token",
      scope:"openid profile email helpdesk_service_api.read helpdesk_service_api.write",
      filterProtocolClaims: true,
      loadUserInfo: true,
      automaticSilentRenew: true,
      silent_redirect_uri: 'http://client-url/silent-refresh.html', 
  };
}

Is there anything missing?

**Comment by brockallen** [comment]
> Is there anything missing?

check the logs

**Comment by baronnt** [comment]
The logs didnt output any error.
