### ISSUE TITLE
Duplicate email_verified claim in id token when AlwaysIncludeUserClaimsInIdToken = true

### ISSUE THREAD

**Issue by roh85** [IdentityServer/IdentityServer4#2982]
When requesting an id token from a client configured with the AlwaysIncludeUserClaimsInIdToken set to true, I receive an id token with the email_verified claim being added twice. Both claims have the same value but written in different casing (lowercase vs proper case).

**Id token contents**
```
sid: 8984357d3f22589e80f40ca274eaba3a
sub: 66fc136f-1fe3-4197-93b1-c4e4f3f9aa61
idp: local
email: bob@localhost
email_verified: true
amr: pwd
email_verified: True
refresh token: 599b38d1c159610465e1d472a805a36e49fe3b20f1b9b320f12d5cdd7dba244f
```
For testing purposes I also excluded my custom ProfileService and ClaimsPrincipalFactory from the DI container so that only the framework variants are used.

I have been debugging this for a while, can't seem to figure out which class is adding the second email_verified claim to the token.

The one from IdentityServer4.AspnetIdentity.UserClaimsFactory adds the email_verified but all in lowercase to the claims collection.

```
            if (_userManager.SupportsUserEmail)
            {
                var email = await _userManager.GetEmailAsync(user);
                if (!String.IsNullOrWhiteSpace(email))
                {
                    identity.AddClaims(new[]
                    {
                        new Claim(JwtClaimTypes.Email, email),
                        new Claim(JwtClaimTypes.EmailVerified,
                            await _userManager.IsEmailConfirmedAsync(user) ? "true" : "false", ClaimValueTypes.Boolean)
                    });
                }
            }
```

### Issue / Steps to reproduce the problem

1. Setup IdentityServer (2.2.0) with AspnetIdentity (2.3.0) and entityframework
2. Add below configuration for client, apiresource and identityresource
3. Login using Hybrid flow with local user
4. Check identity token

Client requested scopes:
`openid email identityserver.api offline_access`

**Client configuration**
```
                new Client
                {
                    ClientId = "native.hybrid",
                    ClientName = "Native Client (Hybrid with PKCE)",

                    RedirectUris = {"https://notused"},
                    PostLogoutRedirectUris = {"https://notused"},

                    RequireClientSecret = false,

                    AllowedGrantTypes = GrantTypes.Hybrid,
                    RequirePkce = true,
                    AllowedScopes = {"openid", "profile", "email", "identityserver.api"},

                    AllowOfflineAccess = true,
                    RefreshTokenUsage = TokenUsage.ReUse,
                    AlwaysIncludeUserClaimsInIdToken = true
                },
```
**ApiResource configuration**
```
public static IEnumerable<ApiResource> GetApiResources()
{
	return new List<ApiResource>
	{
		new ApiResource("fiver_auth_api", "Fiver.Security.AuthServer.Api"),
		new ApiResource("identityserver.api")
		{
			ApiSecrets =
			{
				new Secret("secret".Sha256())
			}
			,
			UserClaims = new List<string>()
			{
				"tenant_id"
			}
		}
	};
}
```
**IdentityResource configuration**
```
public static IEnumerable<IdentityResource> GetIdentityResources()
{
	return new List<IdentityResource>
	{
		new IdentityResources.OpenId(),
		new IdentityResources.Profile(),
		new IdentityResources.Email(),
	};
}
```

**Comment by brockallen** [comment]
Are you certain it's in the id_token twice?

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by roh85** [comment]
Sorry for the late response. I haven't had much time to deep dive into the issue. The claims I am referring too are the claims received on the client, the claims contain the user information (identity resources).
The access token only contains the tenant_id and sub from the user.

I have tried to reproduce this issue with a clean identity server project. I used your Combined_AspId_and_EFStorage from the IdentityServer4.Samples repository. I did not receive the duplicate email_verified claim when using your solution. So it seems there is something wrong with my own identityserver project. I need to plan some time to deep dive this issue further.

**Comment by wardboumans** [comment]
We had another look at this issue and found the cause. 

The tokens are fine. It goes wrong in the IdentityModel component:
- Login > OK (email_verified: true)
- The ```OidcClientOptions.LoadProfile``` option = true so the client retrieves the userinfo 
- ```UserInfoResponse``` object is created and the claims in the json are parsed resulting in the uppercase 'True'.
- The UserInfo claims and the User claims are merged, where the ClaimComparer sees True/true as unique values.

**.ToClaims method, original json**
![image](https://user-images.githubusercontent.com/9028898/60796288-60db4200-a16d-11e9-9daa-21e4a188a250.png)

**.ToClaims method, result**
![image](https://user-images.githubusercontent.com/9028898/60796320-6df83100-a16d-11e9-8494-67c75d076bc8.png)

**Merged claims**
![image](https://user-images.githubusercontent.com/9028898/60796441-a730a100-a16d-11e9-9499-959a72108a3d.png)
