### ISSUE TITLE
Convert External Idp Login to Local Login

### ISSUE THREAD

**Issue by alain27espina** [IdentityServer/IdentityServer4#2985]
Is there an equivalent method for IdentityServer3's **CreateSignInRequest** in IdentityServer4? Basically what I want to achieve is when a certain client passed an external idp and tenant to IdentityServer4 authorization endpoint. On OnRedirectToIdentityProvider event,  i have to check additional rules for that tenant based on our records. If it doesn't passes the rules then I would like to restart the authentication process but this time it should be local. Or is there a better way of doing it?

**Comment by brockallen** [comment]
Your client can send prompt=login on the authorize request. Check the params: http://docs.identityserver.io/en/latest/endpoints/authorize.html

**Comment by alain27espina** [comment]
The OnRedirectToIdentityProvider event that I'm talking about is on the IdentityServer host for the addwsfederation middleware that redirects to another provider if the tenant acr value that was passed in passed the rules.

**Comment by brockallen** [comment]
I guess I don't follow. Your UI has all the logic about triggering upstream auth.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
