### ISSUE TITLE
Moving from Development to Production. Unsure about HTTPS errors

### ISSUE THREAD

**Issue by senorpinatta** [IdentityServer/IdentityServer4#2987]
### **0.**

Hello

Mvc project successfully communicated with IdentityServer (IDS) when both were in development environment (localhost).

### **1.**
When IDS is deployed to production environment (https://identity.placeholder.url), Mvc app can no longer successfully communicate with it and the error is produced:

    Issuer name does not match authority: http://identity.placeholder.url

This seems strange to me since I specify in Mvc's startup.cs

    services.AddAuthentication(options =>
                {
                    options.DefaultScheme = "Cookies";
                    options.DefaultChallengeScheme = "oidc";                    
                })
                .AddCookie("Cookies")
                .AddOpenIdConnect("oidc", options =>
                {
                    options.Authority = "https://identity.placeholder.url";
    //                    options.Authority = "http://localhost:5000";
                    options.RequireHttpsMetadata = false;
                    options.ClientId = "client";
                    options.SaveTokens = true;
                    options.ClientSecret = "placeholder";
                    options.ResponseType = "code id_token";
                });

And later on have the call:

            var client = new HttpClient();
        
            var disco = await client.GetDiscoveryDocumentAsync(new DiscoveryDocumentRequest
            {
                Address = "https://identity.placeholder.url",
    //                Address = "http://localhost:5000",
    //                Policy =
    //                {
    //                    ValidateIssuerName = false,
    //                    RequireHttps = false
    //                }
            });

In both areas I specify "http**s**".

### **2.**
I decided to change both instances to "http", and got the **HTTPS Required** error:

    Error connecting to http://identity.placeholder.url/.well-known/openid-configuration: HTTPS required

### **3.**
So I set the **RequireHttps** flag to false. Which gets me through! Until I try to request a token from IDS:

    var tokenResponse = await client.RequestClientCredentialsTokenAsync(new 
    ClientCredentialsTokenRequest
                {
                    Address = disco.TokenEndpoint,
                    ClientId = "client",
                    ClientSecret = "placeholder"
            });

At which point I'm getting an `invalid_request` error message, which I understand means 
`The request is missing a required parameter, includes an unsupported parameter value (other than grant type), repeats a parameter, or is otherwise malformed.`

Going into my debugger I noticed that in this situation, the request header appears to be empty.
________________________________________________________________________________

My research into this suggests that this might have something to do with the fact that I'm using an HTTP connection instead of HTTPS which brings me back to Stage 1.

This might also have something to do with developer credentials (IDS is still using DeveloperSigninCredentials ) but figuring out how to setup certificates and credentials right now seems like a large endeavor that I want to make sure is necessary before I start.

Appreciate your guys' work,
Happy to clear up terminology I got wrong,
Hoping for some guidance

**Comment by leastprivilege** [comment]
Check the deployment docs - sounds like a "running behind reverse proxy" problem.

**Comment by senorpinatta** [comment]
Thanks for pointing me in the right direction.
