### ISSUE TITLE
Documentation lacks mobile-app scenario information & https considerations

### ISSUE THREAD

**Issue by ckpearson** [IdentityServer/IdentityServer4#2990]
I'm currently working on a project utilising IdentityServer4, with which there will be a native mobile app (iOS).

I'm not 100% certain on whether this belongs here, so feel free to close / discuss.

Essentially I ran headlong into .net core's dev-certs not being supported by iOS due to the certs being self-issued rather than having a CA that iOS can trust.

The documentation for IDS4 is lacking around mobile-app client types as it stands (no real mention of hybrid, pkce, avoiding usage of client secrets, utilisation of redirect urls etc), and there's no information on the utilisation of https in this scenario for dev purposes.

The templates are big on supporting https and getting that right for mvc clients and IDS itself, but there's a real wall you run into when using these certs in a mobile sim.

You can see [this issue](https://github.com/aspnet/AspNetCore/issues/3957) for more information, as well as this [gist](https://gist.github.com/ckpearson/f96074697c583de0d2599c6009191824) for the workaround I eventually had to implement.

Was just wondering if this is something that it's worth calling attention to in the docs?

As I've been banging my head against this for hours, and honestly, it's this sort of friction around security that leads to holes and half-assed implementations.

**Comment by brockallen** [comment]
If we had anything, it's just be on the flows to use and how to get the browser launched and the results back. We'd not be covering anything about HTTPS in dev or prod -- that's outside the scope of what our QS should cover. The main problem with docs on mobile is that there are 4+ platforms to describe and each one is different. Perhaps we just have a general doc and people would need to do their own leg work to research the platform they want to support.

**Comment by LindaLawton** [comment]
I am all for some generalized documentation for mobile developers.   I have personally never done any mobil development so can't create.

I think we will need to lean on the community to help out with this.

**Comment by leastprivilege** [comment]
Agreed - nothing we can do right now inside our core repo. We did some talks around the topic recently - but nowhere as detailed as you probably want it to be.

https://www.youtube.com/watch?v=YF8coyfQb0Y&t=3156s

**Comment by LindaLawton** [comment]
Toss a link to this up on gitter see if anyone wants to do it.
