### ISSUE TITLE
Different scopes per grant type

### ISSUE THREAD

**Issue by bkooistra** [IdentityServer/IdentityServer4#2991]
Hi everyone,

I have the following usecase I wanted your ideas about:

I have an identityserver up and running, multiple applications and API's.

One application needs to be able to send requests to an API. It's a server application, request to this API will not be made on behalf of the user, but rather on behalf of the application, so I thought client credentials would make the most sense in regard of obtaining the access token for this API. However, within the same application, other requests to other API's will have to be made and they will be made on behalf of the user, so for this scenario I would go for authorization code.

Now I have two API's and one application with two allowed grant types. Depending on which grant type was used to obtain the access token, either access to API-1 or access to API-2 is allowed as scope. Now it would be nice if a request for a token is made with the wrong scope using the wrong grant type, this request will be handled appropriately.

What is the best way forward in your opinions? Is this configurable and am I missing that part? Should I override a piece of the default functionality of identityserver? Or maybe should I configure two clients for this one client application? Any alternative solutions to this problem are also welcome.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
