### ISSUE TITLE
Remove default ports from issuer url

### ISSUE THREAD

**Issue by SebastianStehle** [IdentityServer/IdentityServer4#2995]
I use IdentityServer4 with an ASP.NET Core API, both hosted in the same API and IdentityServer4.AccessTokenValidation as and authentication scheme.

It works great so far but an user of mine uses an external tool to request tokens and has not full control over each http request.

This tool request the token from https://domain:443/identity-server/... but all other clients do not include the default port.

I inspected the JWT token and it includes the url with port as an issuer.

The request fails then with: Bearer was not authenticated. Failure message: IDX10205: Issuer validation failed.

I checked the code and the issuer is created from the http context. But the host contain the port: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest.host?view=aspnetcore-2.2

I think it would be great to remove the default ports (80, 443) from the host when creating the issuer url.

I can probably write a middleware for that as an alternative.

**Comment by scottbrady91** [comment]
I'd prefer they change the request on their side and IdentityServer infer issuer based on the HTTP request.

If they can't change anything on their side, you could always manually set the [IssuerUri](http://docs.identityserver.io/en/dev/reference/options.html#identityserver-options) in your IdentityServerOptions.

**Comment by SebastianStehle** [comment]
I told them the same but it was not possible for my customers.

I have solved it with a middleware: https://github.com/Squidex/squidex/blob/master/src/Squidex/Pipeline/CleanupHostMiddleware.cs

But I think it should be the default behavior.

**Comment by brockallen** [comment]
I don't see us doing this, but since you have a workaround I'll close this.
