### ISSUE TITLE
Question using AddIdentityServerQuickstart, AddIdentityServer extension methods

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#300]
With the rc1 version, I have new extension methods possibilities  for IdentityServer4. 

When should I use AddIdentityServerQuickstart or AddIdentityServer?

Is the following setup ok for production?

``` 
services.AddIdentityServerQuickstart()
                .SetSigningCredential(cert)
                .AddInMemoryScopes(Config.GetScopes())
                .AddInMemoryClients(Config.GetClients())
                .AddAspNetIdentity<ApplicationUser>()
.AddProfileService<IdentityWithAdditionalClaimsProfileService>();
```

Greetings Damien

**Comment by leastprivilege** [comment]
Yea - we gonna change the design again.

Remove the Quickstart - and add `AddInMemoryStores` - that's the cleanest right now

**Comment by damienbod** [comment]
Ok, thanks
