### ISSUE TITLE
How I can validate JWT token offline in IdentityServer4?

### ISSUE THREAD

**Issue by KarenTazayan** [IdentityServer/IdentityServer4#3000]
Is there any quick example of how to validate JWT token offline (without introspection endpoint)? Should I go and start to investigate sources?

**Comment by brmatola** [comment]
Microsoft has a library hosted here (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) that provides support for validating JWTs among other things. You can use it to consume your OIDC server and run validations locally

**Comment by KarenTazayan** [comment]
@brmatola thank you, I'll investigate this library.
