### ISSUE TITLE
I'm missing a refresh token 

### ISSUE THREAD

**Issue by Brijak0** [IdentityServer/IdentityServer4#3001]
Hi,

I have defined the following client in an implementation of an openid connect authentication server using the Indentityserver 4. The grant type is set to hybrid and from the client definition I would have expected to receive a refresh token. 
new Client
                {
                    ClientId = "xxxx.app",
                    ClientName = "xxxxx app",
                    RequireClientSecret = false,

                    AllowedGrantTypes = GrantTypes.Hybrid,
                    AccessTokenLifetime = 75,
                    RequirePkce = true,
                    RedirectUris = { "http://127.0.0.1:7890/", "https://oidcdebugger.com/debug" },
                    PostLogoutRedirectUris = { "https://notused" },
                    AllowOfflineAccess = true,
                    AllowAccessTokensViaBrowser = true,
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        "api.full_access"
                    },
                    SlidingRefreshTokenLifetime = 12960,
                    RefreshTokenUsage = TokenUsage.OneTimeOnly,
                    RefreshTokenExpiration = TokenExpiration.Sliding,
                   
                },
but I'm getting the following from the authentication server

Claims:
sid: 4acaba7433226f97ce7947fec435f3b0
sub: 818727
idp: local
amr: pwd
name: Alice Smith
given_name: Alice
family_name: Smith
website: http://alice.com

identity token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjUxNDBlNGE4MjM3ODM2ZjNhZGIxMDgxODk1ZjA5ZGIwIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NDkyNzI4NDAsImV4cCI6MTU0OTI3MzE0MCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMzQiLCJhdWQiOiJ4eHh4LmFwcCIsIm5vbmNlIjoiYzk5ZmU4MmZjMWUyNTkyNTIxZWM1ZmI4MDhkZTdjZTIiLCJpYXQiOjE1NDkyNzI4NDAsImF0X2hhc2giOiJBclFSVS1zU1hQX19ncVpkQUNNSmRRIiwic2lkIjoiNGFjYWJhNzQzMzIyNmY5N2NlNzk0N2ZlYzQzNWYzYjAiLCJzdWIiOiI4MTg3MjciLCJhdXRoX3RpbWUiOjE1NDkyNzE4MDUsImlkcCI6ImxvY2FsIiwiYW1yIjpbInB3ZCJdfQ.hCbXKQTYYcx2jpF-uua3FIbi73jpNi0E1nB5S7XgXrgtiwqWSCToVNSG0x6Lu1tTwa8K8UFtEL9lLJlhaztsqBEdEkPKIqgPbv-BFOxWypfRrhCiMm3L74zD4kH6eZIRN4rkvb4uDfEN7tDBK96J4fRLJ3xSLMr-x0kCu0xf1Fpm9HkjJqkTtfnE6gpzKt4_RgGY-fhBZI-70mRVgyqVWhck7rjcMkdcXKsi_G6GZU-aovvbQ311_XpL5oGlTau4LaXgNRBwc0xS6IxGlRUxPGVj100-abBjZ14fUPt57dhaA_B6lMSGbdQy1ZrarfHgOEnKND-ovDKrYvNBvYtq1w
access token:   eyJhbGciOiJSUzI1NiIsImtpZCI6IjUxNDBlNGE4MjM3ODM2ZjNhZGIxMDgxODk1ZjA5ZGIwIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NDkyNzI4NDAsImV4cCI6MTU0OTI3MjkxNSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMzQiLCJhdWQiOlsiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzMzQvcmVzb3VyY2VzIiwiaHlwb3NhZmV3ZWJhcGkiXSwiY2xpZW50X2lkIjoieHh4eC5hcHAiLCJzdWIiOiI4MTg3MjciLCJhdXRoX3RpbWUiOjE1NDkyNzE4MDUsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImh5cG9zYWZld2ViYXBpLmZ1bGxfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.PS0I13MfXCrbpkBwn6hLxk8vE1npBElNlf8XpGw4lLYpAs79eNjKNlO1BmdkXUAAnTFdgIrVkO9QVTSCc5HzTBvUqtrN7GT7DNjRuQfPVJQjLkdA12V05czTqGK7tp24dLl4FdfEWdAXTiK1kI-t6CsIsGEq9WVbPMfcMryGXUTiwHEOk4D8ABfoW9eepVG4-vqgb3kS6vArl-vbigQQ_o54r_O-Q4mt3q1DdJV9fmChamb8Q8giix9PAAHI7a0wJPkmiIwnZRkiIjG0eU5HJ8-meYx_2Mk-Vq78IJgbjYXu61D4wtMFLCmz9_bCQuc4HRXq4JbsdbhR8sW1ywygRg
refresh token:  none

That is no refresh token? Have I missed a setting of somehow? 

br
Jakob

**Comment by brockallen** [comment]
The client must request offline_access as a scope.

**Comment by Brijak0** [comment]
Yes, thanks for the reply, I just worked it myself. :)
