### ISSUE TITLE
Custom IClientStore implementation and DI configuration

### ISSUE THREAD

**Issue by StanoMartin** [IdentityServer/IdentityServer4#3004]
Hi Guys,

I have problem to register my custom IClientStore implementation in Startup.cs within the ConfigureServices method.

My IClientStore implementation looks like:

`public class ClientRepository : IClientStore
    {
        private List<Client> _clients = new List<Client>
            {
                // OpenID Connect hybrid flow client (MVC)
                new Client
                {
                    ClientId = "ApplicationTest",
                    ClientName = "Auris.oAuth2.MvcClient.Test",
                    AllowedGrantTypes = GrantTypes.Hybrid,

                    ClientSecrets =
                    {
                        new Secret("secret".Sha512())
                    },

                    RedirectUris           = { "http://localhost:5112/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:5112/signout-callback-oidc" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "Auris.OAuth2.Api"
                    },

                    AllowOfflineAccess = true
                },

                new Client
                {
                    ClientId = "ApplicationTestWebClient",
                    ClientName = "Auris.oAuth2.WebClient.Test",
                    AllowedGrantTypes = GrantTypes.Hybrid,

                    ClientSecrets =
                    {
                        new Secret("websecret".Sha512())
                    },

                    RedirectUris           = { "http://localhost:5113/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:5113/signout-callback-oidc" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "Auris.OAuth2.Api"
                    },

                    AllowOfflineAccess = true
                }
            };

        public Task<Client> FindClientByIdAsync(string clientId)
        {
            var result = _clients.FirstOrDefault(tt => tt.ClientId.Equals(clientId, StringComparison.InvariantCultureIgnoreCase));
            return new Task<Client>(()=> result);
        }
    }`

I created the extension method like this:
`public static IIdentityServerBuilder AddCustomClientStore(this IIdentityServerBuilder builder)
        {
            builder.Services.AddSingleton<IClientStore, ClientRepository>();
            //builder.AddClientStore<ClientRepository>();
            builder.Services.AddSingleton<ICorsPolicyService>(
                new DefaultCorsPolicyService(null)
                {
                    AllowedOrigins = { "http://localhost", "http://localhost:5113", "http://localhost:5112" },
                    AllowAll = true
                });
            return builder;
        }`

And configuration section looks like:
`public void ConfigureServices(IServiceCollection services)
        {            
            services.AddMvc().SetCompatibilityVersion(Microsoft.AspNetCore.Mvc.CompatibilityVersion.Version_2_1);

            var builder = services.AddIdentityServer()
                .AddCustomUserStore()
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApis())                
                .AddCustomClientStore();

            if (Environment.IsDevelopment())
            {
                builder.AddDeveloperSigningCredential();
            }
            else
            {
                throw new Exception("need to configure key material");
            }
            
            services.AddAuthentication()                
                .AddOpenIdConnect("oidc", "OpenID Connect", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                    options.SaveTokens = true;

                    options.Authority = "https://demo.identityserver.io/";
                    options.ClientId = "implicit";

                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role"
                    };
                });
        }`

When I run my client I`m possible only hit the FindClientByIdAsync method in my ClientRepository class and then I`m getting some kind of timeout or not responding state.
In case I used in the configuration the `AddInMemoryClients(Config.GetClients())` it is working correctly.
Do you have an idea what`s going on?
I think I`m missing something in the configuration or I`m missing some another interface implementation.

**Comment by AutismPatient** [comment]
**Is your target identity server already running**

**Comment by StanoMartin** [comment]
@AutismPatient I`m not sure what you mean, but my problem still persists. I can start my IdentityServer without any problem just when I trying to redirect to it from my web test client nothing happens and I stay on the web test client page.

**Comment by brockallen** [comment]
You will need to do some more digging on your own for us to do anything about this issue. Look at our implementations if that helps.

**Comment by StanoMartin** [comment]
@brockallen: What you mean exactly? Do you need more code or some additional information? I think the question is pretty clear and straightforward. I`m trying to implement my own ClientStore named "ClientRepository". I use extension method to configure and add this "ClientRepository" usind DI in Startup.cs. The problem is that it is not working ... I`m not getting any exception or error, just the chrome displays the loading page indicator on the page tab.
From my point of view I guess I`m missing something in my extension method to support the configuration of my own ClientStore implementation. I cannot find anywhere some example of custom ClientStore which is not using the EntityFramework. I wnat to use just plain ADO.DNET approach, so afterwards I can implement in ClientRepository my own methods to get/set clients via ADO.NET.
If you have somewhere an example hot to do this it will help me a lot.

**Comment by StanoMartin** [comment]
Hi Guys, I have managed my issue ;-)
The problem was in the return value of method "FindClientByIdAsync", it should be Task.FromResult(result) instead of new Task<Client>(()=> result);
So the problem was not in the configuration itself but in the incorrect return value.
