### ISSUE TITLE
IdentityServer Only for JWT Functionality

### ISSUE THREAD

**Issue by granthoff1107** [IdentityServer/IdentityServer4#3005]
I noticed IdentityServer has alot of functionality baked into it.  Such as handling JWT's.
I would like to use Identity Server but only for it's JWT Implementation.  e.g I have a startup class like so:

    services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
        .AddJwtBearer(cfg =>
        {
            cfg.RequireHttpsMetadata = false;
            cfg.SaveToken = true;

            cfg.TokenValidationParameters = tokenValidationParameters;
        })
        .AddCoinbase(options => {
            options.SendLimitCurrency = "USD";
            options.ClientId = Configuration["Coinbase:ClientId"];
            options.ClientSecret = Configuration["Coinbase:ClientSecret"];
            COINBASE_SCOPES.ForEach(scope => options.Scope.Add(scope));
            options.SaveTokens = true;
            options.ClaimActions.MapJsonKey("urn:coinbase:avatar", "avatar_url");
        });

And I have my External Logins setup to Generate tokens manually 

    [HttpGet("ExternalLoginCallback")]
    [AllowAnonymous]
    public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
    {
        var info = await _signInManager.GetExternalLoginInfoAsync();
        var result = await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor: true);

        var user = await (result.Succeeded ?
             _userManager.FindByLoginAsync(info.LoginProvider, info.ProviderKey)
            : this.CreateIdentityUser(info));

        var jwt = await Tokens.GenerateJwt(_jwtFactory.GenerateClaimsIdentity(user.UserName, user.Id),
            _jwtFactory, _jwtOptions);
        //...

    }

Is there a simple way I can use IdentityServer4 Only for its token Generation? (e.g I would perfer not to have to register clients etc or have an additional DBSetup for configuration.)

**Comment by leastprivilege** [comment]
If all you want is JWTs - I recommend you use the Microsoft JWT handler directly.

**Comment by granthoff1107** [comment]
Thanks, I to see if you exposed the token generation and refresh generation
logic,  I just didn't want to have to write additional code that's already
supported by a well known existing framework, is that logic hidden?
