### ISSUE TITLE
On DI, UserManager is not releasing resources after login

### ISSUE THREAD

**Issue by briankitt** [IdentityServer/IdentityServer4#3008]
I had a very similar ticket open, but I got pulled off on other tasks, and was not able to respond in a timely manner, so that ticket was closed.  I apologize, I don't set my priorities, and this problem was shuffled down lower.  

The 30 second version:  I am using .NET Core 2.0, with Identity 4, and the Dapper ORM provider.  SQL threads are not getting released, after about 4 or 5 logins, the system locks up for too many open SQL threads.  In my project, I have full (unmodified) source for Identity 4, and full source for the Dapper Identity connector, so that way I can trouble shoot.

The problem is very simple.  UserManager that comes in through DI to my login controller is never getting disposed.  If I can get that disposed, I am confident that will fix my problem. It just appears that .NET Core builds a new instance on every logon, and never releases the instances that are finished.  That lends me to think it's a setup issue.

An example pinch points is GetRolesByUserId.  The Dapper Identity connector opens a DBConnection here, but doesn't dispose of it until the UserManager is disposed.  Which never happens.  In debug mode, I set a breakpoint at the 'open connection' and the 'dispose'.  The dispose does not get called, therefore, the connection never gets closed.  If I manually do a 'dispose' on usermanager, then it does, however, I know I should not dispose of an object given to me by DI.

Maybe more specifically, I should say that DapperUserStore is never getting released, which is getting allocated by UserManager.

My startup.cs, abbreviated to show only relevant hooks.

        public void ConfigureServices(IServiceCollection services)
        {
services.ConfigureDapperConnectionProvider<SqlServerConnectionProvider>_configuration.GetSection("DapperIdentity"))
.ConfigureDapperIdentityCryptography(_configuration.GetSection("DapperIdentityCryptography"))
.ConfigureDapperIdentityOptions(new DapperIdentityOptions { UseTransactionalBehavior = false }); //Change to True to use Transactions in all operations
            services.AddIdentity<Model_CustomUser, Model_CustomRole>(x =>
            {
                x.Password.RequireDigit = false;
                x.Password.RequiredLength = 4;
                x.Password.RequireLowercase = false;
                x.Password.RequireNonAlphanumeric = false;
                x.Password.RequireUppercase = false;
                x.User.RequireUniqueEmail = false;
                x.User.AllowedUserNameCharacters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 #`~!%^*()+-={}|[]:;<>?s,.'_@&";
            })
            .AddDapperIdentityFor<SqlServerConfiguration>()
            .AddDefaultTokenProviders();
            services.AddMvc()
                .AddJsonOptions(options => 
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            );
            var builder = services.AddIdentityServer(options =>
                {
                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;
                })
            .AddInMemoryIdentityResources(Config.GetIdentityResources())
            .AddInMemoryApiResources(Config.GetApiResources())
            .AddInMemoryClients(Config.GetClients())
            .AddAspNetIdentity<Model_CustomUser>()
            .AddProfileService<CustomProfileService>();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env) {
            app.UseIdentityServer();
            app.UseMvc();
}

            `

Here is the constructor for the controller for my login:

        private readonly UserManager<Model_CustomUser> _userManager;
        private readonly SignInManager<Model_CustomUser> _signInManager;
        private readonly IIdentityServerInteractionService _interaction;
        private readonly IClientStore _clientStore;
        private readonly IAuthenticationSchemeProvider _schemeProvider;
        private readonly IEventService _events;
        public AccountController(
            UserManager<Model_CustomUser> userManager,
            SignInManager<Model_CustomUser> signInManager,
            IIdentityServerInteractionService interaction,
            IClientStore clientStore,
            IAuthenticationSchemeProvider schemeProvider,
            IEventService events,
        {
            this._userManager = userManager;     //******* this is never getting disposed of, new instance every login
            this._signInManager = signInManager;
            this._interaction = interaction;
            this._clientStore = clientStore;
            this._schemeProvider = schemeProvider;
            this._events = events;
        }
    }

And finally, my login method

        public async Task<IActionResult> Login(Model_LoginInput thisModel, string button)
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(thisModel.userName, thisModel.password, thisModel.rememberLogin, lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    var user = await _userManager.FindByNameAsync(thisModel.userName);
                    await _events.RaiseAsync(new UserLoginSuccessEvent(user.UserName, user.Id.ToString(), user.UserName));

                    if (_interaction.IsValidReturnUrl(thisModel.returnUrl) || Url.IsLocalUrl(thisModel.returnUrl))
                    {
                        return Redirect(thisModel.returnUrl);
                    }
                    return Redirect("~/");
                }

                await _events.RaiseAsync(new UserLoginFailureEvent(thisModel.userName, "invalid credentials"));

                ModelState.AddModelError("", AccountOptions.InvalidCredentialsErrorMessage);
            }
            var vm = await BuildLoginViewModelAsync(thisModel);
            return View(vm);
        }

**Comment by AutismPatient** [comment]
**Is it logged in successfully**

**Comment by briankitt** [comment]
It logs in perfectly fine, up until the point that I run out of SQL
threads, then logins no longer work.

**Comment by leastprivilege** [comment]
Well, you should tell Microsoft.

**Comment by briankitt** [comment]
So as a test, I swapped out the Dapper framework with EF.  The problem went
away.

So this is clearly an issue with out Dapper is implemented to work with the
Identity 4 package.  That makes it their issue, not yours.

Thanks for your time, it's greatly appreciated, hopefully this ticket can
help someone else.
