### ISSUE TITLE
OnRedirectToLogin event not firing

### ISSUE THREAD

**Issue by hnviradiya** [IdentityServer/IdentityServer4#3010]
Whenever unauthorized. it returns 302 redirects perfectly. But .net core OnRedirectToLogin event is not firing (I want to change response status). 

Is any other setup required? I have posted question on stackoverflow as well. Not sure if .net core has issue or identity server or my code.

https://stackoverflow.com/questions/54560707/net-core-2-2-not-updating-status-code-for-302-to-401-onredirecttologin-event-n

My startup file is similar to below sample repo file. In addition to below, I have added global authorize filter and vueclimiddleware and 302 to 401 ajax status convert. other than that it is same as below.

https://github.com/IdentityServer/IdentityServer4.Samples/blob/master/Clients/src/MvcHybridAutomaticRefresh/Startup.cs

**Comment by brockallen** [comment]
`OnRedirectToLogin` where? in the client app?

**Comment by hnviradiya** [comment]
Yes. In client app. I am authorizing controllers in ajax call. So want to respond 401 instead of 302 because client side 302 response cannot be handled by us in ajax call. Status comes as undefined in ajax call.

**Comment by brockallen** [comment]
Then your issue is unrelated to IdentityServer.

**Comment by hnviradiya** [comment]
Ok.
