### ISSUE TITLE
Case-insensitive comparison for redirect_uri

### ISSUE THREAD

**Issue by enikitin** [IdentityServer/IdentityServer4#3011]
I suggest that URL comparison should be consistent - either case-sensitive everywhere or case-insensitive everywhere.

Case-insensitive comparison:
https://github.com/IdentityServer/IdentityServer4/blob/master/src/Validation/Default/StrictRedirectUriValidator.cs: 30
```
return uris.Contains(requestedUri, StringComparer.OrdinalIgnoreCase);
```
This test passes:
```
[Fact]
public async Task Uri_Comparison_Case_Insensitive()
{
	var client = new Client { RedirectUris = new[] { "https://server/cb" } }; // Lowercase
	var requestedUri = "HTTPS://SERVER/CB"; // Uppercase
	var strictRedirectUriValidator = new StrictRedirectUriValidator();
	var result = await strictRedirectUriValidator.IsRedirectUriValidAsync(requestedUri, client);
	result.Should().BeTrue(); // Passes in spite of different case
}
```
Case-sensitive comparison:
https://github.com/IdentityServer/IdentityServer4/blob/master/src/Validation/Default/TokenRequestValidator.cs: 262
```
if (redirectUri.Equals(_validatedRequest.AuthorizationCode.RedirectUri, StringComparison.Ordinal) == false)
```

This test fails:
```
[Fact]
[Trait("Category", Category)]
public async Task Valid_Code_Request()
{
	var client = await _clients.FindEnabledClientByIdAsync("codeclient");
	var grants = Factory.CreateAuthorizationCodeStore();

	var code = new AuthorizationCode
	{
		CreationTime = DateTime.UtcNow,
		Subject = new IdentityServerUser("123").CreatePrincipal(),
		ClientId = client.ClientId,
		Lifetime = client.AuthorizationCodeLifetime,
		RedirectUri = "HTTPS://SERVER/CB", // Uppercase
		RequestedScopes = new List<string>
		{
			"openid"
		}
	};

	var handle = await grants.StoreAuthorizationCodeAsync(code);

	var validator = Factory.CreateTokenRequestValidator(
		authorizationCodeStore: grants);

	var parameters = new NameValueCollection();
	parameters.Add(OidcConstants.TokenRequest.GrantType, OidcConstants.GrantTypes.AuthorizationCode);
	parameters.Add(OidcConstants.TokenRequest.Code, handle);
	parameters.Add(OidcConstants.TokenRequest.RedirectUri, "https://server/cb"); // Lowercase

	var result = await validator.ValidateRequestAsync(parameters, client.ToValidationResult());

	// Will fail because of different case
	result.IsError.Should().BeFalse();
}
```

**Comment by brockallen** [comment]
Two reasons we've never done that to date:

1: URLs are case sensitive: https://tools.ietf.org/html/rfc3986#section-6.2.2.1
2: OAuth specs suggest doing exact matching: https://tools.ietf.org/html/draft-ietf-oauth-security-topics-11#section-2.1

**Comment by enikitin** [comment]
OK, thanks. I just thought that URL matching should be the same in StrictRedirectUriValidator and TokenRequestValidator.

**Comment by brockallen** [comment]
Sorry -- my comment was about why we should be doing case sensitive. If we're not consistent, then we shoul[d fix.

**Comment by enikitin** [comment]
According to the RFC, case-sensitive is not exactly correct. System.Uri.Equals() does the matching correctly:

new Uri("http://ab.cd/de") == new Uri("HTTP://AB.CD/de"))
new Uri("http://ab.cd/de") != new Uri("http://ab.cd/DE"))

**Comment by brockallen** [comment]
If we change this to be more strict, then we suspect it will break people. We'll push this to a breaking change release.

**Comment by brockallen** [comment]
Need to test: does asp.net core's OIDC handler take the current URL and use that to craft the redirect_uri. If so, then the end user can enter different casing causing the comparison to break.
