### ISSUE TITLE
IdentityServer4.Models.ApiResourceExtensions.CloneWithScopes does not clone properties

### ISSUE THREAD

**Issue by MarkClouden** [IdentityServer/IdentityServer4#3013]
Similar to an earlier (2441) issue with DisplayName, Properties of an api resource are not cloned by the method. This is impactful to a custom profile service where resource properties may be useful to determine access for the user (ClaimsProviderAccessToken caller). Workaround is for our resource store to use the resource name as the key - but preference would be to have the primary key int as a property on the api resource returned by the store.

**Comment by brockallen** [comment]
fixed, thanks for letting us know.
