### ISSUE TITLE
AddInMemoryPersistedGrants() does not save the refresh token?

### ISSUE THREAD

**Issue by frostless** [IdentityServer/IdentityServer4#3017]
I know I need to implement `IPersistedGrantStore` to achieve persistent token storage. But right now I am totally fine with in-memory storage.  With the AddInMemoryPersistedGrants()  in use I expect the token will be saved in memory during the period from the sever starts to the server shuts down/restart. However, it does not look like to be the case:

Current Behavior: (code authorization flow)
  
1. I request a access token(default expiration time 60 mins) along with the refresh token.
2. From the following 60 mins onward, I can refresh the token using the refresh token
3. After 60 mins, if I try refreshing the token I will get this `refresh_token grant with value: {refresh_token} not found in store`

But should not the refresh token be saved in the in-memory store? If there was not an in-memory store, the first 60 minutes I should not be able to refresh the token(the validation should fail). But if there was an in-memory store, then the refresh token should out-live 60 minutes. Currently it seems like the refresh_token is being deleted from the store once the access token is expired.

Expected behavior:

With AddInMemoryPersistedGrants()  in use I should be able to refresh the token even after the access token is expired(60 mins by default) until the memory is cleaned(server shuts down/restarts)
I will use a table to implement `IPersistedGrantStore`  later, but right now I just want to use in-memory. I think it should be possible. So am I missing something here?

My startup:
`   services.AddIdentityServer()
   //.AddDeveloperSigningCredential()
 .AddSigningCredential(Certificate.GetCertificate())
	.AddInMemoryIdentityResources(Config.GetIdentityResources())
.AddInMemoryApiResources(Config.GetApiResources())
.AddInMemoryPersistedGrants()
.AddInMemoryClients(Config.GetClients())
.AddTestUsers(Config.GetUsers());`

Client:
`		  AllowedGrantTypes = GrantTypes.Code,
				  RefreshTokenExpiration = TokenExpiration.Sliding,
				  AbsoluteRefreshTokenLifetime = 0,
				  SlidingRefreshTokenLifetime = 1296000,
				  //RequirePkce = true,
				  AllowedScopes = {
						IdentityServerConstants.StandardScopes.OpenId,
						IdentityServerConstants.StandardScopes.Profile,
						IdentityServerConstants.StandardScopes.OfflineAccess
					},
				  AllowOfflineAccess = true`

**Comment by brockallen** [comment]
This is news to us, as we never observed this behavior.

**Comment by frostless** [comment]
It seems only happen in production instead of development.

**Comment by brockallen** [comment]
I can't seem to repro this. Do you have any updates on this issue?

**Comment by frostless** [comment]
No update yet. It only happens in production. The only difference I can think of is the certificate's access level. In my dev machine I did not need to worry about the certificate, but in production I needed to give IISUER the "read" access to the certificate. Maybe that is the problem. For now I just give a very long expiry time to the access token...

**Comment by brockallen** [comment]
I don't think the cert would any anything to do with that. I'm going to close for now since neither of us can provide a repro for it. If you can or find out more, please let us know on this thread. Thanks.
