### ISSUE TITLE
Blazor Example

### ISSUE THREAD

**Issue by MovGP0** [IdentityServer/IdentityServer4#3019]
**Is your feature request related to a problem? Please describe.**

There should be an example how to authenticate an user and properly store user credentials with Blazor in the [IdentityServer4.Samples](https://github.com/IdentityServer/IdentityServer4.Samples) project. 

**Describe the solution you'd like**

- a minimal IdentityServer OAuth server (single hardcoded user)
- a Blazor client application (using Implicit Grant)
- a example hello-world API (using Client Credentials)

Those three could be implemented as a single application using different routes. 

**Describe alternatives you've considered**

- none

**Additional context**

* [Blazor Homepage](https://blazor.net)

**Comment by leastprivilege** [comment]
Good idea. Please go ahead and create that sample.

**Comment by leastprivilege** [comment]
That being said - implicit is deprecated. Client creds don't make sense to me.

**Comment by fuzzzerd** [comment]
Would authorization code with PKCE be more appropriate if Implicit is not recommended?

**Comment by brockallen** [comment]
https://brockallen.com/2019/01/11/using-oauth-and-oidc-with-blazor/

**Comment by MovGP0** [comment]
when I have my next project that uses OAuth, I intend to do so. However, currently I am working at a couple of other projects, so I don't have the time right now. 😓

**Comment by leastprivilege** [comment]
Understood. But please don’t hesitate in the future to tell us what we should do..

**Comment by stermic2** [comment]
I've put in a pull request with a Sample for this feature request. Note that the logout redirect will not function until a modification is made to the demo server.

**Comment by MV10** [comment]
@stermic2 I have logout working fine against the demo server, [repo here](https://github.com/MV10/BlazorOIDC).

I was thinking about offering it as a PR sample until I saw the Feb 12 comment.
