### ISSUE TITLE
JWT max size limit(2kb)

### ISSUE THREAD

**Issue by balaji-rajan** [IdentityServer/IdentityServer4#3025]
We ran into an issue where IdentityServer returning invalid_scope when JWT hit max size limit of 2kb? is this an in-built validation in IDS which does this? and can we control/override this behavior?

**Comment by brockallen** [comment]
When? What endpoint? What workflow?

**Comment by balaji-rajan** [comment]
Grant: client_credentials
Endpoint:connect/token

Throwed when requesting more scopes in JWT

Sorry, thought it's generic that's why didn't add more context

**Comment by brockallen** [comment]
> Throwed when requesting more scopes in JWT

What do you mean here?

**Comment by primalfear** [comment]
Hi @balaji-rajan 
What is the exact error / exception you're getting?
Are you experiencing this issue in web browsers? (An if so which)

When i first start using identity server, i was basically using claims for permissions and things (which claims are not actually we suited to) and was hitting querystring parameter length issues on certain browsers.
https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string

This is also an article i found rather useful in terms of how to think about things to reduce the what you put in claims:
https://leastprivilege.com/2016/12/16/identity-vs-permissions

hope this helps....

**Comment by balaji-rajan** [comment]
@brockallen sorry about missing more context. 

would like to know whats the thought/influence factor to restrict input length to 300?
Is it overcome restriction on browsers like IE(2kb) ?
yes, its configurable but what would be the ideal length?

and why IDS is returning a very generic message as **'scope_invalid'** instead of being specific message like **exceeds the maximum scope length**
```
namespace IdentityServer4.Configuration
{
    public class InputLengthRestrictions
    {
        /// <summary>
        /// Max length for scope
        /// </summary>
        public int Scope { get; set; } = 300

........
```

**Comment by brockallen** [comment]
We limit (by default) the length of the scopes request parameter to 300 characters.

**Comment by balaji-rajan** [comment]
@brockallen yes agree its default, but i'm curious to know the reason behind 300? also why IDS is just responding as `scope_invalid`?

**Comment by brockallen** [comment]
We do simple input length restrictions for security, overflow concerns. You can always change it.

**Comment by balaji-rajan** [comment]
yes error log is perfect IdentityServer4.Validation.TokenRequestValidator: `Error: Scope parameter exceeds max allowed length`.  but token endpoint returns `Bad Request` with message `scope_invalid`

![image](https://user-images.githubusercontent.com/11008306/52743281-aef57a80-2fff-11e9-8f33-416a742af357.png)

Could you also suggest what could be the ideal length for scope?

**Comment by brockallen** [comment]
So all of those messages explain what's happening perfectly, yes. Why is your incoming scope larger than 300 characters?

**Comment by balaji-rajan** [comment]
we've a long list of scopes to support to growing microservices/ apis /microfrontends

**Comment by brockallen** [comment]
It's simple -- change that config value to accommodate your long list of scopes.
