### ISSUE TITLE
Custom DI Container

### ISSUE THREAD

**Issue by iamgurdip** [IdentityServer/IdentityServer4#303]
Does or will identityserver 4 support custom DI container such as SimpleInjector?

**Comment by brockallen** [comment]
We use the ASP.NET host's DI, so whatever ASP.NET Core supports we will use.

**Comment by iamgurdip** [comment]
ASP.NET also supports plugging your own DI framework, which is what i do, b/c the ASP.NET default DI does not support advanced things like Decorators. So do you support plugging 3rd party DI framework like ASP.NET does?

**Comment by brockallen** [comment]
This is not something we control. Your host controls it. I guess I'm confused...

**Comment by iamgurdip** [comment]
thank you for the light bulb moment. My issue was that i did not replace the build in DI framework. BTW love what you are doing with idsvr4. 
- thanx
