### ISSUE TITLE
[Feature] Make all extensions method and Default-classes public by default

### ISSUE THREAD

**Issue by Angelinsky7** [IdentityServer/IdentityServer4#3032]
**Feature**
Is there a reason why DateTimeExtensions class, for example, is internal ? Can't we use it and have public like _all_ the others extensions methods ?

**Describe the solution you'd like**
Make all extensions methods and Default-classes public and easily reusable.

**Describe alternatives you've considered**
Could you maybe explain why this is not already the case. There is a lot of request about this kind of issue and there is maybe a reason why all extensions methods and also all *Default*-classes are not public by default. It seems to me that id4 should be easily extensible, no ?
For example : https://github.com/IdentityServer/IdentityServer4/issues/615 from 2016, marked as _enhancement_ but closed..

**Additional context**
IdentityServer4, Version=2.3.2.0

**Comment by brockallen** [comment]
> Could you maybe explain why this is not already the case

Probably because some things we don't want to be beholden to backwards compatibility.
