### ISSUE TITLE
code grant, checksession and "invalid grant type for client"

### ISSUE THREAD

**Issue by karpikpl** [IdentityServer/IdentityServer4#3033]
### Issue / Steps to reproduce the problem
Identity server configured with code grant 
OpenIdClient javascript client with code grant
Refreshing the app with F5 seems to be causing this issue.

### Relevant parts of the log file
```
connect/authorize?client_id=XXXApp&redirect_uri=https%3A%2F%2FXXX%2Fsilent.html&response_type=id_token&scope=openid&state=1dcff6cee2a644e2866598b8fa6decaa&nonce=8ac65d2e9f0844ddac84ffd8d11a3460&prompt=none

Response 302
Location: error?errorId=abc
```
Error abc says:
```
error=unauthorized_client&error_description=Invalid%20grant%20type%20for%20client&state=1dafd9aee8e54ae394e2e4d33c62beb9",
```

I'm wondering if that's correct. 
From what I've learned - **id_token** request is sent when **checksession** detects a change in session.
But at the same time server is not configured to support **id_token** grant.

Would that be a identityServer bug? oidc-client? or just invalid configuration on my end?

**Comment by brockallen** [comment]
Sounds like invalid config. You need to look more at your IdentityServer log file.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
