### ISSUE TITLE
[question] Resource usage

### ISSUE THREAD

**Issue by amccool** [IdentityServer/IdentityServer4#3035]
IdentityServer4 2.3.2 using IdentityServer4.Entityframework 2.3.2 backed by WsFederation

we have a light usage scenario, but idsrv4 using between 531 and 750 megs, over 2000 handles and ~145 threads.  Our other dotnetcore webapps dont even approach these numbers.

I see between 110-100 network connections to the sql server.

performance is fine about 60% of the time.  But when its bad, its bad, like 25-45 seconds of delay

sure looks like the DB connections arent getting released.   What should I be looking for?

**Comment by brockallen** [comment]
Have you enabled caching for config data?

**Comment by amccool** [comment]
ok we added caching.    The initial startup performance is still the same.   However `hours` later the number of sql connections does finally drop to 1 (which is probably the token cleanup connection).

but why is the connection count still really high after the app has started up and no longer needs the db connections ~ 15 minutes later?

**Comment by amccool** [comment]
so after my startup, after a good 15 minutes of activity I still have 101 connections to my sql server in State: ESTABLISHED.
during this time, I get spotty performance, some requests are fast, some requests are slow (in seconds, rather than ms)

so - then I used tcpview and forcibly terminated `many` of the sql connections from my process, and the result was better performance overall.   E.g. far less `long` requests.

**Comment by amccool** [comment]
Turned the issue was related to a Database logger leaving connections open.
