### ISSUE TITLE
Question: How to use RedirectUri

### ISSUE THREAD

**Issue by KazysNoobiys** [IdentityServer/IdentityServer4#3037]
Hi! I do not understand why in the samples RedirectUris use a different port than IdentityServer. For example: Server "http://localhost:5000",  and Client RedirectUrI  "http://localhost:5002/signin-oidc". Why? So it should be, or need to do other servers whith port 5002? Or do I just have to change the port to 5000?
And another question. What is `signin-oidc` and `signout-callback-oidc`? Are these some pre-defined endpoints? Why are they present in all the samples and projects templates?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!

**Comment by rohankleem** [comment]
> Hi! I do not understand why in the samples RedirectUris use a different port than IdentityServer. For example: Server "http://localhost:5000", and Client RedirectUrI "http://localhost:5002/signin-oidc". Why? So it should be, or need to do other servers whith port 5002? Or do I just have to change the port to 5000?
> And another question. What is `signin-oidc` and `signout-callback-oidc`? Are these some pre-defined endpoints? Why are they present in all the samples and projects templates?

Yes, I think it could be beneficial to have some higher level overviews of the flows between some of these. Currently I am having issues specifying the correct Redirect URI to facebook, but am also a bit confused how one of my clients could handle URLs like /signin-oidc when they don't even have that directory in them. Which makes me thing that it's meant to be the identity server that should be the redirect URL. Anyway, will keep hacking away at it but lots of unnecessary time trying to test and validate key concepts, and lots of trawling and revisiting docs. If I find answer I will post back here.
