### ISSUE TITLE
[question] Access to IdentityServer4 service with token for API

### ISSUE THREAD

**Issue by Szaharov** [IdentityServer/IdentityServer4#3038]
Hi all, 
  in our case we use IdentityServer4 in our IdentityService to provide a token that our SPA can access API in other micro-services. In the same time IdentityService  provide some API (like register new user or update user parameters) which should be called by another services. 
  So the question is - how IdentityService could be configured that it will be and IdentityServer and API resource in the same time? Now when we call API from identity service with token we get 401 (Unauthorized). 
Many thanks in advance!

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
