### ISSUE TITLE
Not able to successfully authenticate my Razor Pages app with Identity Server 4.

### ISSUE THREAD

**Issue by wiseguytamo** [IdentityServer/IdentityServer4#3041]
I am having an issue of not being able to have my Razor Page application be successfully authenticated via Identity Server.

After applying the [Authorize] annotation to my startup page and running the application I am prompted to log in. After logging in and accepting the consent screen I am not redirected to the page I initially wanted to access. Why is this ?

I tried authenticating sample MVC app via Identity Server and it worked fine.

Please also note that there are no controllers in my application, only pages.

Please could someone enlighten me as to what could be the issue.

Please see sample code below and attached screenshot of error:

 [Authorize]
    public class Dashboard1Model : PageModel
    {
        public void OnGet()
        {
             //WriteOutIdentityInformation();
        }

        public async Task WriteOutIdentityInformation()
        {
            //gets the saved identity token
            var identityToken = await HttpContext
                .GetTokenAsync(OpenIdConnectParameterNames.IdToken);

            //write it out
            Debug.WriteLine($"Identity token: {identityToken}");

            //write out other user claims.
            foreach (var claim in User.Claims)
            {
                Debug.WriteLine($"Claim type: {claim.Type} - Claim value: {claim.Value}");
            }
        }
    }

******************************************************
Startup.cs of the Razor Pages application
******************************************************

public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;

            //clears the DefaultInboundClaimTypeMap to ensure our claims remain the same way we defined them instead of mapping them to different claim types.
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddMvc().AddRazorPagesOptions(options =>
                        {
                            options.Conventions.AddPageRoute("/Dashboards/Dashboard1", "");
                        })
                        .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

            // register an IHttpContextAccessor so we can access the current
            // HttpContext in services by injecting it
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            //Register HTTP Client here.
            //--------------

            //Configuring the authentication middleware to log into IdentityServer
            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "msc_cookies"; //scheme-names must be different for each app hosted on the same server.
                options.DefaultChallengeScheme = "oidc";
            }).AddCookie("msc_cookies",
               (options) =>
               {
                   options.AccessDeniedPath = "/Authorization/AccessDenied";
               })
              .AddOpenIdConnect("oidc", options =>
              {
                  options.SignInScheme = "msc_cookies";
                  options.Authority = "https://localhost:44370";
                  options.ClientId = "smc_client";
                  options.ResponseType = "code id_token";
                  //options.CallbackPath = new PathString("...");
                  //options.SignedOutCallbackPath = new PathString("...");

                  options.Scope.Add("openid");
                  options.Scope.Add("profile");

                  options.Scope.Add("address");
                  options.Scope.Add("email");
                  options.Scope.Add("roles");
                  options.Scope.Add("subscriptionlevel");
                  options.Scope.Add("country");
                  options.Scope.Add("imagegalleryapi");
                  options.Scope.Add("offline_access");

                  options.SaveTokens = true;
                  options.ClientSecret = "secret";

                  options.GetClaimsFromUserInfoEndpoint = true;
                  options.ClaimActions.Remove("amr"); //this ensures that the amr claim is not filtered out.
                  options.ClaimActions.DeleteClaim("sid");
                  options.ClaimActions.DeleteClaim("idp");
                  ////options.ClaimActions.DeleteClaim("address");
                  options.ClaimActions.MapUniqueJsonKey("role", "role"); //Added mappings to the role claim.
                  //options.ClaimActions.MapUniqueJsonKey("subscriptionlevel", "subscriptionlevel");
                  //options.ClaimActions.MapUniqueJsonKey("country", "country");

                  //options.TokenValidationParameters = new TokenValidationParameters
                  //{
                  //    NameClaimType = JwtClaimTypes.GivenName,
                  //    RoleClaimType = JwtClaimTypes.Role,
                  //};

              });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseMvc();
        }
    }

![login_error](https://user-images.githubusercontent.com/11686469/52892198-525ca180-315e-11e9-97c3-8484f0fdce15.PNG)

**Comment by brockallen** [comment]
`app.UseAuthentication()` is missing

**Comment by wiseguytamo** [comment]
Thank you very much @brockallen
