### ISSUE TITLE
Always force user to login when hitting the [Authorize] attribute (grants/consent)

### ISSUE THREAD

**Issue by PresidentCamacho** [IdentityServer/IdentityServer4#3044]
Hi, I'm using the quickstart template for IdentityServer and was wondering if theres a way to force the user thats entering the [Authorize] controllers (grants/consent) to always need to login again?

I've been looking on some attributes in `AddIdentityServer() ` in the startup pipline but couldn't find anything relevent. 

Or is this more of an asp.net mvc issue?

**Comment by brockallen** [comment]
I don't follow. `[Authorize]` doesn't mean always login -- it means the user must be authenticated.

**Comment by PresidentCamacho** [comment]
> I don't follow. `[Authorize]` doesn't mean always login -- it means the user must be authenticated.

I know, but even if there's an user thats authenticated to my IdentityServer. Is there a way to force the user to reauthenticate?

I would like to use something like `SignOutAsync `at the start of each requests. But that will only give me a  loop to the sign in screen.

**Comment by Ruard** [comment]
@PresidentCamacho Why do you want this? What are you trying to accomplish? Is it because you want to refresh the claims on each call?

**Comment by brockallen** [comment]
> I know, but even if there's an user thats authenticated to my IdentityServer. Is there a way to force the user to reauthenticate?

Look into the authorize endpoint params: http://docs.identityserver.io/en/latest/endpoints/authorize.html
