### ISSUE TITLE
[MTLS] Change endpoint format

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3045]
right now we use

`/connect/token/mtls`

given that this will affect multiple endpoints, we should do

`/connect/mtls/[token|introspection|revocation]`

a) easier for our middleware
b) allows for a single HTTPS setting in IIS for `/connect/mtls/*`

**Comment by leastprivilege** [comment]
How about we just re-write `/connect/mtls/*` to `/connect/*` and apply the challenge for x509. This way anybody can add new MTLS secured endpoints.

**Comment by brockallen** [comment]
done
