### ISSUE TITLE
Customize the Well-Known Url Response

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3049]
Hi, 
Currently Well-Known Url for my Authorisation Server will shown following list in "response_types_supported" Parameter

code
token
id_token
id_token token
code id_token
code token
code id_token token

I wanted just show the "code id_token" in "response_types_supported".

Please guide us, how customize the well-known url

**Comment by leastprivilege** [comment]
These are the response types supported by IdentityServer. We don't have a way to customize that.

**Comment by leastprivilege** [comment]
It might work to set this to false

https://github.com/IdentityServer/IdentityServer4/blob/master/src/Configuration/DependencyInjection/Options/DiscoveryOptions.cs#L42

and add the element manually

https://github.com/IdentityServer/IdentityServer4/blob/master/src/Configuration/DependencyInjection/Options/DiscoveryOptions.cs#L80

**Comment by Sathiyanathan-Macro** [comment]
Thanks for the quick replay. I'll try your suggestion and revert back if need any further details on this
