### ISSUE TITLE
multiple query string after redirect from sign-google 

### ISSUE THREAD

**Issue by RajanJS** [IdentityServer/IdentityServer4#3050]
I'm not sure what's going wrong here and don't know if it's the right place to post this. Didn't get response about it in StackOverflow. So, posting here if I can get some help from here.
https://stackoverflow.com/questions/54747090/identityserver4-multiple-query-string-parametrs

I’m getting an invalid redirect from sign-google with double “?” Which leads to 404 for the requested action.

`http://[hostname]/Account/ExternalLoginCallback?returnUrl=%2Fconnect%2Fauthorize%2Fcallback?nonce=lsWtLSRMgOeocUptXZj3E24uVwKrtsTRCHkKse08Xyg&response_type=code&code_challenge_method=S256&scope=openid%20profile%20offline_access%20opus.scheduling%20opus.location%20opus.users&code_challenge=HNm-xYnKgPUSj3IH379RrdhPPXcHtPfUiEQxse8ndoo&redirect_uri=com.opus%3A%2F%2Fsignin-oidc&client_id=opus.scheduling.app&state=1yUDkZo90noExsWzx5o9hkDqZzMvdmTe6ggGUy7oGDo`

Thanks,

**Comment by joel100** [comment]
To add more detail around this. 

The project is running 
- IdentityServer4 - 2.3.0
- IdentityServer4.EntityFramework - 2.3.0
- IdentityServer4.AspnetIdentity - 2.3.0
- AspnetCore.All - 2.1.4

The environment in AWS and has NGINX and an application loadbalancer (to make service discovery easier) in front of the container hosting the identity process. Nginx does SSL termination and forwards on in http.

The logs appear to correlate with the same requests, so it doesn't appear that they have anything to do with this. We seem to get two slightly different behaviors. The above and a URL that is fully encoded with no ? Both lead to 404.
```http://[hostname]/Account/ExternalLoginCallback%3FreturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fnonce%3DXpu8UxyRPK8794_fgclsUCHTgckuCFDFDzz4kqr_sS4%26response_type%3Dcode%26code_challenge_method%3DS256%26scope%3Dopenid%2520profile%2520offline_access%2520opus.scheduling%2520opus.location%2520opus.users%26code_challenge%3DPJlZzcFjSN1FTA13hde8yB0lR8gUdrs23rgCN0QpUHA%26redirect_uri%3Dcom.opus%253A%252F%252Fsignin-oidc%26client_id%3Dopus.scheduling.app%26state%3DyVfCJx9HSimb_BItRYM7SaG-q8Sg3G0E2Jc7bGD3gJg```

The working theory is something is something is occurring in how the state is is being roundtrips to Google or inside the Signin-Google method. 

```http://[hostname]/signin-google?state=CfDJ8FsRN3iZTfJDuzniBaeFvFLoPG8NRi3xFinQun1quAtKa6Jj680Ujv00KH9o-fGYY0agSdxVOhv5S9vYbQ4qSMC1OzEPfIQzjP1nE-_EOZhp-yNFXIWBoQXNgoF9ZZ6bLSN4aGk08Px7EYv85ekq4J4rw3IZ17FHsTWlVV2s464MSWUevgHhoMDKAbRvNeRN2_dpQrphraM_uYzLEHZHbv-2savZBfkMe_Gke2QM_9zZ_1R8qw1JBTur4ypAXCKOQxSGJZKKXPV192Ttm0jb1bdmRLhDubx_Hmjk1aFKwV-J1RWoY7TYfXlbtaFaS_CoHw5mBv07kCYcKAavm-e2oWXDGZj_QovdxNIEFrHotPZOTzb-Q9p8NMN-lCZyDrdjA56VnQ4ifmxiQAABvK05bzhJmT1IxvWq9EKYQHiDVNTJEqU_YBmfY5w2cnvwfOq6GXYK2MsGenzLZ_DJWk88fty_HZkHlq7XAe6Ioy2fu2Q2a03ck8-eVB1SwXYiZsqVRlHNA7bi6388jlyhuNnAYPiv5zbiWuGdCsauOlU317uyC5s_RY9iNXIiCXdMpQiv7QVQKz333zYw8glxtVx_8TwJ2BspLy3aZM0Qzo6tS795gwoyaj8J7mA3u7zi39qK2RJhNVTdYb2vVAu8yawZu34rc8Jh95UVJL171RnDLvU2VrZtFlwbO1l4v6FQB1JbBSsZe_QLPj-NVHFd_kqLjgKBgwZzu4Ff4nJeGfXNXQ6JiHKx2nYXvdOd4wY8P8S6ySd_Aba-Kg_XQwa-jM51k-kX3_0Mt1XqymXuelo9A4ri2UfqocC-pK4WV8_etVXKfc9xV3KEeNi26YhrDPO1udJ-uJgGRHLOPJ5oQtFwwYu0br9kRi_00LdZttWFqHFKUuM88TBQIgGwF2ehfZ1sLiMjpvPuZFKlfGHzFKmqe2Ua&code=4/-AAFAYIg-IgjhwgHQM1tfxT2axtBnIV-00BDHMWmQTiruqUKPHNvhRnFJI5ZeFKi0Vcd4ioD58_cFFg-YGCdsG4&scope=openid+email+profile+https://www.googleapis.com/auth/calendar+https://www.googleapis.com/auth/userinfo.email+https://www.googleapis.com/auth/userinfo.profile&authuser=0&session_state=0606a5a5e995d8dcd2f42a13e26362ab59499ea4..b228&prompt=none```

We've been looking at this for a while so any guidance would be helpful.
