### ISSUE TITLE
List of samples on Quickstarts readme.md does not match actual source code order

### ISSUE THREAD

**Issue by joaopgrassi** [IdentityServer/IdentityServer4#3052]
### Issue / Steps to reproduce the problem
Open the `Quickstarts` folder under the `Samples` repo:
https://github.com/IdentityServer/IdentityServer4.Samples/tree/master/Quickstarts

The actual folders have the following names: (and these match with the order in the docs: http://docs.identityserver.io/en/latest/)

```
1_ClientCredentials
2_ResourceOwnerPasswords
3_ImplicitFlowAuthentication
4_ImplicitFlowAuthenticationWithExternal
5_HybridFlowAuthenticationWithApiAccess
6_JavaScriptClient
7_EntityFrameworkStorage
8_AspNetIdentity
Combined_AspId_and_EFStorage
```

But the `readme.md` is different from Quickstart 6 onwards:

```
6 - IdentityServer and ASP.NET Identity
7 - JavaScript clients
8 EntityFramework configuration
```

I would be glad to adjust it. Just opening the bug first, as stated in the coding guidelines.

**Comment by leastprivilege** [comment]
yes please go for it!

**Comment by joaopgrassi** [comment]
@leastprivilege PR is there. Should be good to go.

**Comment by brockallen** [comment]
In your PR you moved around our docs to match the QS samples? Or did you update the readme in the same to match the folders?

**Comment by joaopgrassi** [comment]
Hi @brockallen

I changed the `readme.md` in `IdentityServer4.Samples/Quickstarts/` so it matches the QS folder themselves. The folders themselves are already on par with the docs (http://docs.identityserver.io/en/latest/). The issue was only in the `readme.md` where the order of some samples were inverted.

**Comment by brockallen** [comment]
Ah ok, I see now -- I think I was looking at the core repo, not samples and got confused. Thanks.

**Comment by brockallen** [comment]
Merged, thanks!
