### ISSUE TITLE
Configurable token lifetime per client/grant type

### ISSUE THREAD

**Issue by Ruard** [IdentityServer/IdentityServer4#3054]
**Is your feature request related to a problem?**
I would like to _configure_ the lifetime of the _extensions grant type_, but there is no option to do so. By default the _access token lifetime_ is used for the created token, but having both an access token and an extension grant token, I need two different lifetime values.

Consider the following extension grant validator that is used for [delegation](http://docs.identityserver.io/en/latest/topics/extension_grants.html#example-simple-delegation-using-an-extension-grant):

```
public class AuthorizationGrantValidator : IExtensionGrantValidator
{
    private readonly IClientSecretValidator _clientValidator;
    private readonly IHttpContextAccessor _httpContextAccessor;

    public AuthorizationGrantValidator(IClientSecretValidator clientValidator, IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
        _clientValidator = clientValidator;
    }

    public string GrantType => "authorization";

    public async Task ValidateAsync(ExtensionGrantValidationContext context)
    {
        // validate client
        var clientResult = await _clientValidator.ValidateAsync(_httpContextAccessor.HttpContext);
        if (clientResult.Client == null)
        {
            context.Result = new GrantValidationResult(TokenRequestErrors.InvalidClient);
            return;
        }
            
        // get user's identity
        var sub = context.Request.Raw.Get("sub");

        // work-around: replace the access token lifetime with the alternative lifetime.
        context.Request.AccessTokenLifetime = 60;

        context.Result = new GrantValidationResult(sub, GrantType);
    }
}

```

**Describe alternatives you've considered**
Currently the lifetime of various tokens are configured in the clients table:

 - AbsoluteRefreshTokenLifetime
 - AccessTokenLifetime
 - IdentityTokenLifetime
 - DeviceCodeLifetime

I can add a field in the clients table to store the value for the extension grant type, but in that case I would end up adding fields for every extension grant type I add. _And I need to set the value myself as done in the above example._

The alternative is to add a field to the ClientGrantTypes table, as described in the solution. But I still need to replace `context.Request.AccessTokenLifetime` with the configured value, which seems more a hack than a solution.

**Describe the solution you'd like**
I think that there is a distinction between the refresh token, identity token and access token. But not between access token, DeviceCode and extension grant types.

So it seems logical to me to add a lifetime field to the ClientGrantTypes, instead of configuring this in the clients table. That way you can specify the token lifetime (regardless the type of token) that can be used to set the extension grant lifetime. `context.Request.AccessTokenLifetime` could then become `context.Request.TokenLifetime`, containing the value as configured in the ClientGrantTypes table, e.g.:
```
Id     ClientId	GrantType           TokenLifetime
1      1	client_credentials  600
2      1	hybrid              3600
3      1	authorization       60
```
Being configured, there is no need to add the additional line as work-around. And since it's not limited to extension grant types, it allows more flexibility in configuration.

**Additional context**
I've seen [Feature Request: Allow changing AbsoluteRefreshTokenLifetime for Extension Grants #2305](https://github.com/IdentityServer/IdentityServer4/issues/2305) which also involves the extension grant type. But that feature request is about the refresh token lifetime, which is not the scope of this feature.

Actually, I'm not sure if and how a refresh token should be implemented for extension grant types that are used for delegation.

**Comment by brockallen** [comment]
I guess I don't 100% follow. The custom grant is an input, whereas the access token is an output. And in theory there are an infinite number of possible extension grant types.

I can see possibly wanting to change the lifetime depending on the incoming grant, so being able to set the AccessTokenLifetime in code is already the workaround.

**Comment by Ruard** [comment]
Yes, each succesful grant request produces an access token, where the lifetime can depend on the client. But using the same access token lifetime (from the clients table) for each token, despite being constructed with different grant types, would not be accurate. Depending on who uses the token, one could decide to alter the lifetime. As configured in the sample table in my previous comment.

So that's the first part of this feature request. A central place to store the information in order to make this easy to configure. And this is not limited to extension grants. This should be possible for all grant types. The ClientGrantTypes table would be a good candidate to store the AccessTokenLifetime, because of the link between grants and clients.

The effect is that the AccessTokenLifetime from the clients table can be removed. Though I would rather leave it, as it can be used as a default value when the ClientGrantType.AccessTokenLifetime is omitted, something like:

`context.Request.AccessTokenLifetime = Clients.AccessTokenLifetime ?? ClientGrantType.AccessTokenLifetime;`

Yes, it is possible to use the workaround, but then the existing grant validators would not honor the lifetime value for each grant when set. Which means that I would have to override all grant validators that are available, in order to simulate the same behaviour for all grant types.

So the second part of the feature request is to change the source of the AccessTokenLifetime in all existing grant validations.

---

Adding the possibility to set a lifetime per client/grant type allows a more accurate configuration.

There is no distinction between existing grant types and extension grant types. Once implemented, this works for all grant types, without having to add / change code. As it's all configuration then.

However, the workaround is fine with me. To be honest, I am not using that many grant types. But as a generic solution it would seem more logical (to me at least) to be able to set the AccessTokenLifetime at another level. Currently AccessTokenLifetime seems not in the right place.

**Comment by leastprivilege** [comment]
This can be achieved by a custom token request validator. No plan to built that in.
