### ISSUE TITLE
TokenRequestValidationLog disclosing reused refresh tokens to log output

### ISSUE THREAD

**Issue by msitms** [IdentityServer/IdentityServer4#3055]
There is already builtin support to redact sensitive information from log output, also in `IdentityServer4.Logging.Models.TokenRequestValidationLog`. (Which is very nice to see as it proves once again that you really try hard to apply security best practices and ship with secure default behavior -- thank you very much!) 

However, this seems to redacts only the refresh token from the `raw` part:

```
IdentityServer4.Validation.TokenRequestValidator:Information: Token request validation success
{
  "ClientId": "my-client-id",
  "ClientName": "my-client",
  "GrantType": "refresh_token",
  "RefreshToken": "***NOT REDACTED!!!***",
  "Raw": {
    "grant_type": "refresh_token",
    "refresh_token": "***REDACTED***",
    "client_id": "my-client-id"
  }
}
```

The problem seems to be that the refresh token is added _after_ `.ToScrubbedDictionary` is called on the raw request.

This is probably not intended, and could even be considered a security problem if more people have access to the logs than to the database, right?

**Comment by leastprivilege** [comment]
Tracking here

https://github.com/IdentityServer/IdentityServer4/issues/3518
