### ISSUE TITLE
How to Clear the SignIn Cookies (idsrv) in OIDC Flow

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3056]
Hi,
We have Implemented the OIDC Flow in our Authorization Server as like below
 services.AddIdentityServer(op =>
            {
                op.UserInteraction.LoginUrl = MacSets.routeURL+"/Account/OidcLogin/";
                op.UserInteraction.ErrorUrl = MacSets.routeURL + "/Error/Error/";
           });

My Question:
* User successfully logged in to the Login Screen then cookies (idsrv) is created automatically.
* After Which, Identityserver4 redirect to Redirect Url with Authorization Code when i called Redirect() function with valid return Url.
* What is the procedure to clear the idsrv cookies when above process is done. (Because the Identityserver4 not generating Auth. Code when clear the cookies before redirect)

I hope you understand what is my question and provide answer for that.

Detail Diagram was attached below for more clarification.

[AuthServer_Cookies_Issue_Details.docx](https://github.com/IdentityServer/IdentityServer4/files/2899536/AuthServer_Cookies_Issue_Details.docx)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
