### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by ghavipanjeh** [IdentityServer/IdentityServer4#3058]
Clone https://github.com/IdentityServer/IdentityServer4.AspNetIdentity

I am Getting an error like below ,when run project.

![capture](https://user-images.githubusercontent.com/38580625/53345485-44f7a200-392a-11e9-90a5-91b2960edad4.PNG)

@scottbrady91
@leastprivilege

**Comment by brockallen** [comment]
Bizarre -- I don't see that behavior on the dev branch.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
