### ISSUE TITLE
IPersistedGrantStore.StoreAsync is called twice to store the Authorization Code

### ISSUE THREAD

**Issue by kevinlo** [IdentityServer/IdentityServer4#3060]
Occasionally , I can see from my logging that the IPersistedGrantStore.StoreAsync is called twice within less than 200ms for the same logon.  

The second one will be removed by the IdentityServer, but the first one will be stored in my DB as orphan.

I don't know how to reproduce it and it occurs intermittently. 

Any clue what can cause it?   I see the first call is finished in 50ms, so I don't think the second one is a retry.

**Comment by brockallen** [comment]
Not sure. It's possible a client is making parallel requests.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by span** [comment]
Did you locate your issue @kevinlo ? We are seeing the same kind of behaviour.

**Comment by kevinlo** [comment]
@span No, I did not spend time to locate it.   I think I just put a time to live to the document and it will be removed automatically.
