### ISSUE TITLE
Company firewall is blocking the discovery document endpoint bc it contains "/."  (".well-known/openid-configuration")

### ISSUE THREAD

**Issue by exp-geometrics** [IdentityServer/IdentityServer4#3062]
**Is your feature request related to a problem? Please describe.**
Company firewall is blocking the discovery document endpoint bc it contains "/."  (".well-known/openid-configuration").  The firewall is blocking uri's with period following forward slash.

**Describe the solution you'd like**
Is there an api available for overriding the discovery endpoint?

**Describe alternatives you've considered**
Would have to request exception to the firewall rule at company.

**Additional context**
Error:
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://xxx.xxx.com/identityserver/.well-known/openid-configuration

![1](https://user-images.githubusercontent.com/44303485/53445982-6e223c00-39d7-11e9-9334-88e8b9d9edc5.png)

**Comment by brockallen** [comment]
>  Is there an api available for overriding the discovery endpoint?

You could build middleware to rewrite the path.

**Comment by exp-geometrics** [comment]
Is there an example of a middleware?

Also I tried downloading the sample and modifying the discovery endpoint directly first to test the effect of removing the period after the slash.  It led to couple of the tests failing.  Is the period required for a reason..?

**Comment by exp-geometrics** [comment]
Was able to get corporate to add an exception to the barracuda firewall rule.
