### ISSUE TITLE
Event to capture access token request using refresh token

### ISSUE THREAD

**Issue by mahapatraprabhanjan** [IdentityServer/IdentityServer4#3064]
Hello All,

I have a question related to events. 
When an user requests for a new access token using the refresh token which event has to be captured.

i.e., User have access token and refresh token. 
Client application finds the access token expired and requests a new access token using refresh token.
In the identity server I wanted to capture which event has been fired and all steps are performed before giving the access and refresh token back to client.

Thanks

**Comment by giorgos07** [comment]
Hello @mahapatraprabhanjan 

Please take a look at [this](http://docs.identityserver.io/en/latest/topics/events.html) section of the official documentation to understand about Identity Server events. Although events are mostly used logging oriented purposes you could use something like the following to achieve what you describe.

``` csharp
public class TokenIssuanceEventSink : IEventSink
{
   public Task PersistAsync(Event @event) {
      if (@event.Id.Equals(EventIds.TokenIssuedSuccess)) {
         // Do stuff here...
      }

      return Task.CompletedTask;
   }
}
```

Also in the Identity Server configuration you need, among others, to register the custom event sink

``` csharp
services.AddIdentityServer().AddEventSink<TokenIssuanceEventSink>();
```
Hope this helps.

**Comment by mahapatraprabhanjan** [comment]
@giorgos07 Thanks for the reply let me try this solution. Will get back to you with an update.

**Comment by mahapatraprabhanjan** [comment]
@giorgos07 I am still not sure how to track for which user the token has been issued. Is there any way we can get the sub or name or email in the PersistAsync?

**Comment by giorgos07** [comment]
@mahapatraprabhanjan you can inject the [IHttpContextAccessor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.ihttpcontextaccessor?view=aspnetcore-2.2) interface if you want to get access to the logged in user and its claims. You can enhance the above class to achieve it, like this:

``` csharp
using System;
using System.Threading.Tasks;
using IdentityModel;
using IdentityServer4.Events;
using IdentityServer4.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace Avgoulea.Identity.Security
{
    public class TokenIssuanceEventSink : IEventSink
    {
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ILogger<TokenIssuanceEventSink> _logger;

        public TokenIssuanceEventSink(IHttpContextAccessor httpContextAccessor, ILogger<TokenIssuanceEventSink> logger) {
            _httpContextAccessor = httpContextAccessor ?? throw new ArgumentNullException(nameof(httpContextAccessor));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public Task PersistAsync(Event @event) {
            if (@event.Id.Equals(EventIds.TokenIssuedSuccess)) {
                var user = _httpContextAccessor.HttpContext.User;
                var userId = user.FindFirst(JwtClaimTypes.Subject);
                var userEmail = user.FindFirst(JwtClaimTypes.Email);
                _logger.LogInformation($"User with Id: '{userId}' and email '{userEmail}' was issued a token.");
            }

            return Task.CompletedTask;
        }
    }
}

```
Do not forget to add the following 2 lines in your `ConfigureServices` method in order for this to work:

``` csharp
services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
services.AddLogging();
```

**Comment by mahapatraprabhanjan** [comment]
Oh that worked... thanks for such a wonderful explanation.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
