### ISSUE TITLE
Revoke a non exist token return 200

### ISSUE THREAD

**Issue by jasonycw** [IdentityServer/IdentityServer4#3068]
It seems like IdentityServer doesn't not return any error message or 400 when the request is asking for a non existing token to revoke

From what I have saw from IdentityServer4 repo (`origin/master 6d831016c0a9fa9147080b8ce3d0d5f0544dc94e`)

It seems that it is because this function only return `false` but no Error
https://github.com/IdentityServer/IdentityServer4/blob/63a50d7838af25896fbf836ea4e4f37b5e179cd8/src/ResponseHandling/Default/TokenRevocationResponseGenerator.cs#L127
``` C#
        protected virtual async Task<bool> RevokeRefreshTokenAsync(TokenRevocationRequestValidationResult validationResult)
        {
            var token = await RefreshTokenStore.GetRefreshTokenAsync(validationResult.Token);

            if (token != null) // token == null
            {
                if (token.ClientId == validationResult.Client.ClientId)
                {
                    Logger.LogDebug("Refresh token revoked");
                    await RefreshTokenStore.RemoveRefreshTokenAsync(validationResult.Token);
                    await ReferenceTokenStore.RemoveReferenceTokensAsync(token.SubjectId, token.ClientId);
                }
                else
                {
                    Logger.LogWarning("Client {clientId} tried to revoke a refresh token belonging to a different client: {clientId}", validationResult.Client.ClientId, token.ClientId);
                }

                return true;
            }

            return false;
        }
```
This will then only set the `response.Success` to `false` but nothing is set for `response.Error`
https://github.com/IdentityServer/IdentityServer4/blob/63a50d7838af25896fbf836ea4e4f37b5e179cd8/src/ResponseHandling/Default/TokenRevocationResponseGenerator.cs#L77
``` C#
            else if (validationResult.TokenTypeHint == Constants.TokenTypeHints.RefreshToken)
            {
                Logger.LogTrace("Hint was for refresh token");
                response.Success = await RevokeRefreshTokenAsync(validationResult);
                // Where is response.Error = ???
            }

```
Thus this will not throw an error 
https://github.com/IdentityServer/IdentityServer4/blob/63a50d7838af25896fbf836ea4e4f37b5e179cd8/src/Endpoints/TokenRevocationEndpoint.cs#L118
``` C#
            var response = await _responseGenerator.ProcessAsync(requestValidationResult);

            if (response.Success)
            {
                _logger.LogInformation("Token successfully revoked");
                await _events.RaiseAsync(new TokenRevokedSuccessEvent(requestValidationResult, requestValidationResult.Client));
            }
            else
            {
                _logger.LogInformation("No matching token found");
            }
            // No response.Error is here
            if (response.Error.IsPresent()) return new TokenRevocationErrorResult(response.Error);

            return new StatusCodeResult(HttpStatusCode.OK);
```
And then it will `return new StatusCodeResult(HttpStatusCode.OK);`

### Issue / Steps to reproduce the problem
1. Call the revoke endpoint<br>
```
POST /connect/revocation HTTP/1.1
Host: localhost:51000
Content-Type: application/x-www-form-urlencoded
cache-control: no-cache
Postman-Token: 
client_id=client_idclient_secret=super_secrettoken=123
```
2. Token `123` is not in our RevokeTokenStore
4. Our `CustomRefreshTokenStore.GetRefreshTokenAsync` will return `null`
3. Endpoint returns `200 OK`

### Relevant parts of the log file

```
2019-02-28 17:44:33.2341|INFO|IdentityServer4.Hosting.IdentityServerMiddleware|Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenRevocationEndpoint for /connect/revocation
2019-02-28 17:44:38.9781|INFO|IdentityServer4.Endpoints.TokenRevocationEndpoint|No matching token found
```

**Comment by brockallen** [comment]
That behavior is per spec

**Comment by jasonycw** [comment]
@brockallen why is it not letting the client know the revoke token is not found?
I understand maybe it is for security issue, but why no option for the client to handle the refresh token error?

Any documentation related to this behavior?

**Comment by brockallen** [comment]
Because: https://tools.ietf.org/html/rfc7009#section-2.2
