### ISSUE TITLE
Remove Access Token based on subject and Client id 

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3069]
Hi,
I wanted to Remove Access Token from Authorisation Server based on Subject Id and Client Id. 

Please provide if you have any code sample for this.

Your quick response is highly appreciated,

**Comment by brockallen** [comment]
Are you aware of the docs? 

http://docs.identityserver.io/en/latest/reference/interactionservice.html

**Comment by Sathiyanathan-Macro** [comment]
Hi Brockallen,

Thanks for your response.

IIdentityServerInteractionService, it's only for User interface module based on the document details. 

My question is, We got access token for the Authorization code. After some part of time, I wanted to remove the access tokens related to the subject id and client id.

some of them using ReferenceTokenStore classes, But they haven't provided any code samples.

So, Can you please help us to provide some code samples to remove the access tokens for the specific subject id and client id.

I hope you understand my requirement.

**Comment by brockallen** [comment]
In that case, connect to the store and delete the rows that match your criteria.

**Comment by Sathiyanathan-Macro** [comment]
Thanks Brockallen,

I'll try your suggestion and revert back if required any.
