### ISSUE TITLE
Define Access Token Life Time dynamically.

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3070]
Hi,

How can set Access Token Life Time dynamically instead of referring client table?

**Comment by leastprivilege** [comment]
You can do that in a custom token request validator.

**Comment by Sathiyanathan-Macro** [comment]
Hi,

I need to set access token life time during issuing stage.

**Comment by leastprivilege** [comment]
Yes - implement a custom token request validator - you can set the token lifetime there.

https://github.com/IdentityServer/IdentityServer4/blob/master/src/Validation/ICustomTokenRequestValidator.cs

**Comment by Sathiyanathan-Macro** [comment]
Thanks Least,

I'll try it out.

**Comment by Sathiyanathan-Macro** [comment]
Thanks Least, 

It's working perfect.
