### ISSUE TITLE
Feature Request: Support OIDC Request Object in Authorize

### ISSUE THREAD

**Issue by acarlonvsn** [IdentityServer/IdentityServer4#3071]
Since I never got an answer on [SO](https://stackoverflow.com/q/54964822/746754) I guess that the Request JWT is not supported. 

The OIDC specification includes Request Object JWT parameter that can be passed to the authorize request, see [here](http://docs.identityserver.io/en/latest/endpoints/authorize.html).

It would be great if IdentityServer could be extended to support this parameter to authorize. I would be happy to take a stab at implementing support for it, but wonder where the best place would be. 

Without going into much detail it seems that a starting point would be:
* Extend AuthorizeRequestValidator to validate Request JWT (needs to do this using public key).
* Extend DefaultClaimsService.cs to add custom claims from Request JWT.

**Comment by brockallen** [comment]
dup: #594
