### ISSUE TITLE
AspNetIdentity AuthenticationMethod is wrong

### ISSUE THREAD

**Issue by webbes** [IdentityServer/IdentityServer4#3076]
When using AspNetIdentity eventhough we use Multi Factor Authentication the resulting token always contains an "amr" claim with a value of "pwd" only. This should be at least "mfa" but in most cases it should be ["pwd", "otp", "mfa"].

**Comment by brockallen** [comment]
When you issue the claims at login you can add amr claims that will add to that collection. Our AspId code doesnt' do this today, but you could extend it to do so. If you come up with a nice solution, then we coul[d consider a PR into our AspId code as well.

**Comment by webbes** [comment]
Thx for your fast response,

I'm certainly willing to adjust the code but where? I've looked everywhere. But can not find where the "amr" claim is set to "pwd". I even started searching for the string "pwd" :-(

I also noticed that I can try to tell IdentityServer I want to use MFA by setting the parameter "amr_values" on the protocol message to "mfa", but this is completely ignored is it?

Another thing I noticed is that even though I set the "amr" claim to "mfa" (in a custom ProfileService for example) this is being overridden and set to "pwd" again? Where?

Security is not my specialty and simply configuring MFA using the AspIdentityProvider is proven to be very difficult. Mfa is required everywhere nowadays so this kind of got me by surprise. I hoped there was a working AspNetIdentity integration available.

That being said... If you tell me where to start looking, I'm sure willing to fix it and create a pull request.

Kind regards,
Webbes

**Comment by brockallen** [comment]
> I'm certainly willing to adjust the code but where? I've looked everywhere. But can not find where the "amr" claim is set to "pwd". I even started searching for the string "pwd" :-(

Unfortunately, if you're using AspId to log a user in (or do MFA) they don't make it easy to add custom claims at login time. You would mostly have to tinker with the internals of the SignInManager and/or UserManager from AspId. This is all outside IdentityServer. 

> I also noticed that I can try to tell IdentityServer I want to use MFA by setting the parameter "amr_values" on the protocol message to "mfa", but this is completely ignored is it?

This would all have to be custom code you write.

> Security is not my specialty and simply configuring MFA using the AspIdentityProvider is proven to be very difficult. Mfa is required everywhere nowadays so this kind of got me by surprise. I hoped there was a working AspNetIdentity integration available.

This is unrelated to IdentityServer. This is a function of the login workflow which IdentityServer expects you to build. Of course we have our AspId quickstart, but it's just a starting point and doesn't implement every requirement that anyone would ever want/need. In short, this would be your code, but it should be possible to do.

**Comment by dealproc** [comment]
As part of the Login workflow, can the Identity User's hash set be altered?

https://github.com/IdentityServer/IdentityServer4/blob/63a50d7838af25896fbf836ea4e4f37b5e179cd8/src/IdentityServerUser.cs#L37

If so, this may offer a solution.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
