### ISSUE TITLE
Cross Identity Server Resource communication

### ISSUE THREAD

**Issue by lucho6d2-reply** [IdentityServer/IdentityServer4#3077]
Hi, we are building a multi client platform (on-premise) and we have the follow scenario:

![image](https://user-images.githubusercontent.com/37108401/53879438-43df0880-3fed-11e9-8752-b974acf7ddd7.png)

We have the Master company (the owner of the platform) and then different clients, what we are trying to figure out if there is a way to do the company-clients resources (APIs) communication, with authentication,  in a way that a client resource talks with client identity server and get a token, and then with that token it can request company resources.

It is a kind of external provider but without login.

Is it possible?

Thanks in advance, and suggestions are really appreciate!

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
