### ISSUE TITLE
Host value is not propagated to authorize callback URL

### ISSUE THREAD

**Issue by Sebosek** [IdentityServer/IdentityServer4#3078]
Hi,

the configuration of `Request.Host` is not propagated to created Return URL after a call to `authorize` endpoint.

### Steps to reproduce the problem
Create IdS with the following configuration:
```
app.Map(
        "/identity", 
        map => map.Use(async (ctx, next) =>
            {
                ctx.Request.Host = new HostString($"{ctx.Request.Host.Value.TrimEnd('/')}/services/identitymanagement");
                await next();
            }).UseIdentityServer());
```

URLs in discovery endpoints are correct:
```
...
  "jwks_uri": "https://10.10.29.22/services/identitymanagement/identity/.well-known/openid-configuration/jwks",
  "authorization_endpoint": "https://10.10.29.22/services/identitymanagement/identity/connect/authorize",
  "token_endpoint": "https://10.10.29.22/services/identitymanagement/identity/connect/token",
  "userinfo_endpoint": "https://10.10.29.22/services/identitymanagement/identity/connect/userinfo",
  "end_session_endpoint": "https://10.10.29.22/services/identitymanagement/identity/connect/endsession",
  "check_session_iframe": "https://10.10.29.22/services/identitymanagement/identity/connect/checksession",
  "revocation_endpoint": "https://10.10.29.22/services/identitymanagement/identity/connect/revocation",
  "introspection_endpoint": "https://10.10.29.22/services/identitymanagement/identity/connect/introspect",
  "device_authorization_endpoint": "https://10.10.29.22/services/identitymanagement/identity/connect/deviceauthorization",
...
```

But after redirect to Login URL defined by `options.UserInteraction.LoginUrl = "/single-sign-on"` URL contains http://10.10.29.22/single-sign-on?ReturnUrl=%2Fidentity%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dwphapp%26scope%3Dwph_identity%2520profile%2520email%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%253A5001%252Fapp-signin%26state%3DCfDJ8Ncai4ZNyK9Bno-T0jQD3hVL0SnO-Ucd5E1Gd9qdbywcV8uV-lnZemS1YLpNtkS_l5r9IxmaD8j9TKJpDkVYjZebK9ans_EIujvARCWTUSFWdCCroOdkhQ0APtmN6PEjsUt30XJlfO2BfEDcl1wEMk3yMnUtkKW4L3Of2Lkx3GeTS1eIR3ujdimDbIA4c3l71eiKv6CP_9jF3AEY5Ttsjvb7YFZVSTrM1aQB6MNzVF8Icd5LEYvN0fMJL_CLMFaCYA. The ReturnUrl parametr should start with `%2Fservices%2Fidentitymanagement%2Fidentity%2Fconnect%2Fauthorize%2Fcallback` (/services/identitymanagement/identity/connect/authorize/callback).

**Comment by brockallen** [comment]
are you running the login page on a different host/server than IS itself?

**Comment by Sebosek** [comment]
Yes, I do.

**Comment by brockallen** [comment]
In that case, you will have to come up with your own design to make that work. I know some customers have done this, but it's all custom.
