### ISSUE TITLE
Return refresh token's expire time

### ISSUE THREAD

**Issue by jasonycw** [IdentityServer/IdentityServer4#3079]
**Is your feature request related to a problem? Please describe.**
We are now creating a separate Identity Server and API project from single API project that handle authentication and business logic. 
One of our authenticate result is the expire time for the refresh token, but from the return result of Identity Server's token endpoint, only access token's expire time is returned.

```
{
    "access_token": "some_jwt_token",
    "expires_in": 1800,
    "token_type": "Bearer",
    "refresh_token": "some_refresh_token"
}
```

**Describe the solution you'd like**
It would be great if there is a config for IdentityServer to return the refresh token's expire time and `TokenResponse` can contain the `ExpiresIn` for the `RefreshToken`

**Additional context**
Related class
https://github.com/IdentityModel/IdentityModel2/blob/97d134bcdfd967f0ee702ee6aca1be09d6a356f3/src/Client/Messages/TokenResponse.cs

**Comment by brockallen** [comment]
Can you explain why or how you'd use it?

**Comment by jasonycw** [comment]
Currently, our web client only communicate with our API and not to Identity Server, so our API provides the authentication endpoints to client and we do the authorization with Identity Server in the backend only.

Our web client need to save the token and refresh token with their expire time on their end, so our API will return something like this to them
```
[
    {
        "type": "Jwt",
        "token": "some_jwt_token",
        "expiryDateUtc": "2019-03-07T08:00:35"
    },
    {
        "type": "RefreshToken",
        "token": "some_refresh_token",
        "expiryDateUtc": "2019-06-15T07:30:35"
    }
]
```
Since we control both the API and the Identity Server, sure we can just hardcode the time span for the refresh token in both projects so the API don't need to get the refresh token's expire_in from Identity Server.

But, we are trying to find a way to not coding any authen related config in our API and depend everything from Identity Server return results. 
So, if the refresh token's expires_in can also be returned, we can just use it to `DateTime.UtcNow.AddSeconds(auth.Value.RefreshToken.ExpiresIn)`

**Comment by leastprivilege** [comment]
The spec does not define such a parameter. But you can add custom response parameters using a custom token request validator.

**Comment by jasonycw** [comment]
@leastprivilege but we only want to get the refresh token's expire time in the response, custom token request validator will need to implement all kinds of request.

And also, even if I customized the Identity Server's token endpoint's response with the refresh token's expire time, the `TokenResponse` from `IdentityModel2` will still not have custom attributes handling?

**Comment by leastprivilege** [comment]
Yes true - you need an if statement to check for the request type and then add it. IdentityModel has ways to query for non-standard responses.

As I said - it's not part of the spec - so not part of our default implementation.

**Comment by leastprivilege** [comment]
Also - I don't believe the client needs to know the expiration of the refresh token. It is not a client concern. It can also change at any point in time when the refresh token gets revoked.

You should code your clients in a way that they can deal with both access and refresh token invalidation.

**Comment by Jehoel** [comment]
Right now IS4 only returns a generic `invalid_grant` error without giving a reason. It would be helpful if it could indicate if the reason was because of revokation vs. expiration so the client app can display a an appropriate message to the user to explain why they're having to login again. Being forced to login without warning is an unpleasant UX. I'd like to be able to display "Your access has been revoked. Go away." vs "Your session (refresh_token) has expired. Please login again.", for example.
