### ISSUE TITLE
Azure - CryptographicException: Keyset does not exist

### ISSUE THREAD

**Issue by tamkam** [IdentityServer/IdentityServer4#308]
I have a Identity Server web app hosted on Azure. It has a .pfx file in it's root directory for signing. The problem is that when newly published it works perfectly fine but after some time it starts throwing CryptographicException: Keyset does not exist.

Based on  [CryptographicException KeySet does not exists](http://stackoverflow.com/questions/25666483/cryptographicexception-keyset-does-not-exists) I would assume that it is a file access issue, but why out of the sudden azure is messing up with file access.

**Comment by brockallen** [comment]
In azure you should be using this: https://azure.microsoft.com/en-us/blog/using-certificates-in-azure-websites-applications/

**Comment by tamkam** [comment]
Thanks @brockallen. What if I will store the certificate as base64 in application config and load it from there ?

**Comment by brockallen** [comment]
Well, apparently this:

>  after some time it starts throwing CryptographicException: Keyset does not exist.

**Comment by tamkam** [comment]
Thank you. I'll try this approach.
