### ISSUE TITLE
IConfigureOptions<IdentityServerAuthenticationOptions>.Configure() isn't automatically called.

### ISSUE THREAD

**Issue by Poltergeisen** [IdentityServer/IdentityServer4#3081]
### Issue / Steps to reproduce the problem
Create a class that implements `IConfigureOptions<IdentityServerAuthenticationOptions>`

Add to dependency injection:
`services.AddSingleton<IConfigureOptions<IdentityServerAuthenticationOptions>, ConfigureIdentityServerAuthenticationOptionss>();`

The Configure method is never called when using `services.AddAuthentication().AddIdentityServerAuthentication()`

**Comment by leastprivilege** [comment]
We are not using IOptions internally. What's your use case?

**Comment by adam-geisen** [comment]
I needed to access my configuration variables from a settings class. We do encryption on our variables and I didn't want to take a hard dependency on our encryption library in the startup.cs file. 

I'll include an example below

If at some point you could support IOptions to follow the pattern that Microsoft is pushing with .net core that would be awesome.

Example (pseudo code):

Settings.cs

```
public class Settings{
  private readonly ICryptographer cryptographer;
  public Settings(ICryptographer cryptographer){
     this.cryptographer = cryptographer;
  }

  public string ClientSecretEncrypted => {get; set;}
  public string ClientSecretDecrypted => cryptographer.decrypt(ClientSecretEncrypted);
}
```
I'd populate the ClientSecretEncrypted property in the Startup.cs class.
```
services.Configure<Settings>(options => options.ClientSecretEncrypted = Configuration["ClientSecret"]);
```

Then if that all worked correctly I'd make a configuration class for Identity server that implements IConfigureOptions that could automatically configure what I want:

```
    public class
        ConfigureIdentityServerAuthenticationOptions :
            IConfigureOptions<IdentityServerAuthenticationOptions>
    {
        private readonly IOptions<Settings> options;

        public ConfigureIdentityServerAuthenticationOptions(
            IOptions<Settings> options)
        {
            this.options = options;
        }

        public void Configure(IdentityServerAuthenticationOptions identityServerAuthenticationOptions)
        {
            identityServerAuthenticationOptions.RequireHttpsMetadata = !options.Value.IsLocal;
            identityServerAuthenticationOptions.ApiName = "name";
            identityServerAuthenticationOptions.ApiSecret = options.value.ClientSecretDecrypted;
            identityServerAuthenticationOptions.Authority = options.Value.IdentityServerAuthority;
        }
    }
```

Hopefully that makes sense for what I'm trying to do. Honestly I'm pretty new but this options pattern really helps to clean up the code and allows me to use constructor injection to set up options which seems like a really handy feature.

**Comment by adam-geisen** [comment]
Here's an example that I found on the aspnet/Security repo of someone requesting the same functionality for AddJwtBearer

https://github.com/aspnet/Security/issues/1709

**Comment by Poltergeisen** [comment]
So I think that I might've messed up. This is the IdentityServer4 repo and not the AccessTokenValidation repo. I will close this ticket and reopen on the other repo.

Sorry about the confusion.
