### ISSUE TITLE
MVC Client Conflict IdentityServer4 with ASP.NET Identity

### ISSUE THREAD

**Issue by devlnull** [IdentityServer/IdentityServer4#3082]
Hi, I have an IdentityServer4(version 2.3.2.0) and a MVC client application to manage users and some other things.
My MVC Client : 
```
                new Client()
                {
                    ClientId = MyClient.Id,
                    ClientName = MyClient.Name,
                    AllowedGrantTypes = GrantTypes.Hybrid,
                    RedirectUris = { $"{managementUrl}/signin-oidc" },
                    PostLogoutRedirectUris = { $"{managementUrl}/signout-callback-oidc" },
                    AllowedCorsOrigins = new [] { managementUrl },


                    ClientSecrets =
                    {
                        new Secret(MySecret.Sha256())
                    },

                    AllowedScopes = {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        IdentityServerConstants.StandardScopes.Phone,
                        IdentityServerConstants.StandardScopes.Address,
                        IdentityServerConstants.StandardScopes.OfflineAccess,
                        MyApi.ApiName,
                        JwtClaimTypes.Role
                    },

                    AllowOfflineAccess = true,
                }
```

In my MVC Client application I've added Authentication this way :

```
           JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
            .AddCookie("Cookies")
            .AddOpenIdConnect("oidc", options =>
            {
                options.SignInScheme = "Cookies";

                options.Authority = authUrl;
                options.RequireHttpsMetadata = false;

                options.ClientId = MyClient.Id;
                options.ClientSecret = MyClient.Secret;
                options.ResponseType = "code id_token";

                options.SaveTokens = true;
                options.GetClaimsFromUserInfoEndpoint = true;

                options.Scope.Add("openid");
                options.Scope.Add(MyApi.Api);
                options.Scope.Add("offline_access");
                options.Scope.Add("profile");
                options.Scope.Add("email");
                options.Scope.Add("phone");
                options.Scope.Add("role");
                options.ClaimActions.MapUniqueJsonKey("role", "role");
                options.ClaimActions.MapUniqueJsonKey("email", "email");
                options.ClaimActions.MapUniqueJsonKey("picture", "picture");
                options.ClaimActions.MapUniqueJsonKey("phone_number", "phone_number");
            });
```

When I use ASP.NET Identity Configuration in my MVC Client application :
```
            services.AddIdentity<AppUser, AppRole>()
            .AddEntityFrameworkStores<AppDbContext>()
            .AddUserManager<AppUserManager<AppUser>>();
```
after login on IdentityServer login page I get Consent page and I click yes, confirm all of them and then instead of redirecting to MVC Client, I get the Consent page again!

IdentityServer4 log says :

> [01:34:22 Information] IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator
> Showing consent: User has not yet consented

Interesting thing is that when I comment my Identity configuration it works well!
More info : I use IdentityServer configuration (AddAuthentication) after Identity configuration(AddIdentity), otherwise ASP.NET Identity override the auth and redirect me to Account/Login page!

**Comment by brockallen** [comment]
It's hard to say. You will have to debug into the response from consent back into the IS endpoint to figure out why the response is being lost. I'd suggest comparing our working samples to your workflows to see the delta.

**Comment by devlnull** [comment]
I already did!
I used the Sample projects and got the configuration you used for MVC clients, I tried to use the Samples MVC clients to check if Identity works for them, but got the same result!
After manipulating configuration I found out the  problem is Authentication Schemes!
Currently configuration in MVC clients is :
```
            services.AddAuthentication(options =>
                {
                    options.DefaultScheme = "Cookies";
                    options.DefaultChallengeScheme = "oidc";
                })
                .AddCookie("Cookies")
                .AddOpenIdConnect("oidc", options =>
                {
                    options.SignInScheme = "Cookies";

                    options.Authority = "http://localhost:5000";
                    options.RequireHttpsMetadata = false;

                    options.ClientId = "mvc";
                    options.ClientSecret = "secret";
                    options.ResponseType = "code id_token";

                    options.SaveTokens = true;
                    options.GetClaimsFromUserInfoEndpoint = true;

                    options.Scope.Add("api1");
                    options.Scope.Add("offline_access");

                    options.ClaimActions.MapJsonKey("website", "website");
                });
}
```
Which it misses an important part, unfortunately we don't get an understandable error from it.
finally with adding the below line in [startup.cs](https://github.com/devlnull/IdentityServer4.Samples/blob/master/Quickstarts/9_MvcClientWithIdentity/src/MvcClient/Startup.cs) everything worked.
[` options.DefaultAuthenticateScheme = "Cookies";`](https://github.com/devlnull/IdentityServer4.Samples/blob/master/Quickstarts/9_MvcClientWithIdentity/src/MvcClient/Startup.cs#L45)

[MVC client with using IdentityServer is in this repo](https://github.com/devlnull/IdentityServer4.Samples)

**Comment by brockallen** [comment]
If you'd like us to debug your code, then you will need to get commercial support. If not, then I'll close for now and if you find a bug or an issue in IdentityServer related to this, feel free to reopen this issue.
