### ISSUE TITLE
Cannot log in via Chrome: net::ERR_INVALID_HTTP_RESPONSE

### ISSUE THREAD

**Issue by MattiasHammarhorn** [IdentityServer/IdentityServer4#3084]
Hello, I am not sure if this is the appropriate place to ask for help but I have gotten no answers on any other sites.
I am using ASP.NET 4.6.1 with an ASP.NET MVC-project while authenticating to Identity Server in Service Fabric. On the client side of the MVC-project I am using oidc-client.min.js and redirecting to a different page. Authentication and redirection works fine when the project is hosted on Azure or when I try different browsers but when I try to log in using localhost on Google Chrome I get redirected to callback.html, and receive these two errors in the console:
```
Failed to load resource: net::ERR_INVALID_HTTP_RESPONSE :5000/connect/userinfo:1
Error: Network Error at XMLHttpRequest.s.onerror (oidc-client.min.js:1) callback.html:13
```
The url of the callback.html-redirect contains a token though and if I use it in a post to localhost:5000/connect/userinfo in Postman, then I will get back the user info. I have not found any answer on if this is related to Google Chrome or Visual Studio and I have reinstalled Chrome and tried it on other browsers were it works. In output it says:
`Failed to load resource: net::ERR_INVALID_HTTP_RESPONSE [http://localhost:5000/connect/userinfo]`

Does anyone have any idea of what could be causing this?

**Comment by brockallen** [comment]
No, sorry.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by MateuszKikmunter** [comment]
Maybe this will help, it looks similar.

https://stackoverflow.com/questions/53906866/neterr-invalid-http-response-error-after-post-request-with-angular-7/53965732#53965732
