### ISSUE TITLE
Do I need an extra database for my Identity server 4 project?(persistent storage implementation)

### ISSUE THREAD

**Issue by frostless** [IdentityServer/IdentityServer4#3085]
Sorry if this questions has been raised..
So I have three projects in my solution;
1: My Web API (authority is Identity Server4)
2: Identity Server 4
3:API consumer client

I have a database associated with my Web API already. And now with Identity Server I am going to replace the in-memory storage with persistent storage (https://docs.identityserver.io/en/latest/quickstarts/7_entity_framework.html?highlight=storage)
Seems like I need an extra database.

The question is, what is considered a good practice, create a brand new database only for Identity server 4? Or I can consider just adding some tables for the existing database used by the Web API?

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/latest/topics/deployment.html
