### ISSUE TITLE
Install build fails

### ISSUE THREAD

**Issue by zakwillis** [IdentityServer/IdentityServer4#3086]
Hi, I am using Visual Studio 2017,  have .net core sdk 2.2 etc installed, although I believe you do an install of .net core sdk as part of the powershell build. 

I have followed the simple instructions, so why does it not build? Do I need to clone the git repository as opposed to downloading the zip?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to locate repository containing directory 'C:\InfoRhino\is4mstr\src'.	IdentityServer4	C:\Users\zak_w\.nuget\packages\microsoft.build.tasks.git\1.0.0-beta-63127-02\build\Microsoft.Build.Tasks.Git.targets	20	
Error	CS0006	Metadata file 'C:\InfoRhino\is4mstr\src\bin\Debug\netstandard2.0\IdentityServer4.dll' could not be found	IdentityServer.UnitTests(netcoreapp2.1)	C:\InfoRhino\is4mstr\test\IdentityServer.UnitTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\InfoRhino\is4mstr\src\bin\Debug\netstandard2.0\IdentityServer4.dll' could not be found	IdentityServer.IntegrationTests(netcoreapp2.1)	**C:\InfoRhino\is4mstr\test\IdentityServer.IntegrationTests\CSC	1	Active
Error	CS0006	Metadata file 'C:\InfoRhino\is4mstr\src\bin\Debug\netstandard2.0\IdentityServer4.dll' could not be found	Host	C:\InfoRhino\is4mstr\host\CSC	1	Active**

**Comment by brockallen** [comment]
Sounds like your zip or clone has files missing?

**Comment by leastprivilege** [comment]
Try cloning it.

**Comment by zakwillis** [comment]
Hi there. Was going to try cloning it later. Many thanks, Zak

**Comment by zakwillis** [comment]
Hi there. Cloning works. Builds. Many thanks, Zak
