### ISSUE TITLE
IdentityServer4.Endpoints.Results.TokenResult throws exception (for some users only)

### ISSUE THREAD

**Issue by duhtmep** [IdentityServer/IdentityServer4#3089]
Hello 

May I ask for a short look and a hint what is going wrong here?
Many thanks in advance!

Get this exception for some users in our database:
2019-03-11 12:30:32.5384 [75] **FATAL IdentityServer4.Hosting.IdentityServerMiddleware - Unhandled exception**: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. System.### NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei IdentityServer4.Extensions.DictionaryExtensions.AddDictionary(JObject jobject, Dictionary`2 dictionary)
   bei IdentityServer4.Endpoints.Results.TokenResult.<ExecuteAsync>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()|

![image](https://user-images.githubusercontent.com/31841540/54142946-0e8d4d00-4429-11e9-9aa3-19a94432093c.png)

Exception origin is somewhere here i think.

Related to Response.Custom field?? When do we expect this field to be set??

Many thanks for any hint!

**Comment by leastprivilege** [comment]
`Response.Custom` is not set by us anywhere. You must use some extensibility point somewhere and set it?!

**Comment by duhtmep** [comment]
Found the issue:

In our LoginValidator we add some custom data to the dictionary, like:
customResponse.Add("CultureInfoCode", user.CultureInfoCode);

When user.CultureInfoCode is NULL in this case the exception is thrown during the AddDictionary call 

Maybe there should be a possibility to have null values here??

Only a hint. Not important for me now!

Many thanks!

**Comment by leastprivilege** [comment]
How about you check for null? ;)
