### ISSUE TITLE
Logout: Need to further reduce the State parameter to a GUID after applying services.AddOidcStateDataFormatterCache

### ISSUE THREAD

**Issue by tiwari-abhishek** [IdentityServer/IdentityServer4#3090]
**Issue / Steps to reproduce the problem**
I have 2 IdentityServers. The first one is an IdentityServer4 which is setup as an Relying Party to an upstream IdentityServer3. I don't control the upstream IdP.

Since the .NET Core based middleware was generating a huge **"state"** parameter, I used `services.AddOidcStateDataFormatterCache("ids3")` as advised in another thread, in my IdentityServer4 to reduce the size of the state parameter. The size came down a bit, but its not good enough in my case. The state parameter length is still 184 characters long.  So I still get the error:
`"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable"`

When I delete/reduce the state parameter size, the redirects back to my IdentityServer4 start working, but obviously the subsequent redirect from IdentityServer4 to the client application fail because the state is lost or altered.

**Question**
Is there a away to swap out this already reduced state parameter with a GUID or something and restore the original state parameter, using this GUID later, once I get the signout callback, so as to complete the end to end signout?

Can someone provide a code sample or pointers?

**Comment by tiwari-abhishek** [comment]
The post [#407](https://github.com/IdentityServer/IdentityServer4/issues/407) was helpful. But I skipped the encryption/decryption part since it was still 180 chars long after encryption. The state id is just a guid now and the logout works using that.

Is skipping the data protector encryption for state property a security risk?

**Comment by brockallen** [comment]
A guid is high enough entropy, so that would address the concern of an attacker guessing.

**Comment by tiwari-abhishek** [comment]
ok, thanks Brock. I guess I would go with the GUID then. Do you think its a good idea to add the GUID option to the AddOidcStateDataFormatterCache extension method you have?

**Comment by brockallen** [comment]
I think that should be left up to the consumer of the feature. If you want it a guid, then I'd suggest doing your own implementation at that point (since you can just copy the same code from our AddOidcStateDataFormatterCache).

**Comment by tiwari-abhishek** [comment]
thanks, that makes sense. I did that, skipping the encryption.
