### ISSUE TITLE
Even after logout access token remains active(Implicit flow)

### ISSUE THREAD

**Issue by ravi22saini** [IdentityServer/IdentityServer4#3092]
Hi,

I am facing one issue, i have implemented implicit flow and the thing happening is when I duplicate a tab and logout from the first tab, I am still able to access my API without getting 401. Ideally if i do a logout then my access token should be become invalidate.

Startup of my api project which contains below

  services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
               .AddIdentityServerAuthentication(options => {
                   
                   options.Authority = "http://localhost:50000/";
                   options.RequireHttpsMetadata = false;
                   options.ApiName = "***";                   
               });
and i have Authorize attribute implemented.

  this.oidcConfigService.onConfigurationLoaded.subscribe(() => {
      const openIDImplicitFlowConfiguration = new OpenIDImplicitFlowConfiguration();      
      openIDImplicitFlowConfiguration.stsServer = '****';
      openIDImplicitFlowConfiguration.redirect_url = '****';       
      openIDImplicitFlowConfiguration.client_id = 'UiProject'; 
      openIDImplicitFlowConfiguration.response_type = 'id_token token';
      openIDImplicitFlowConfiguration.scope = 'openid profile ***';
      openIDImplicitFlowConfiguration.post_logout_redirect_uri = '****';
      openIDImplicitFlowConfiguration.start_checksession = false;
      openIDImplicitFlowConfiguration.silent_renew = true;
      openIDImplicitFlowConfiguration.silent_renew_url = '****';
      openIDImplicitFlowConfiguration.post_login_route = '/';
      // HTTP 403
      openIDImplicitFlowConfiguration.forbidden_route = '/Forbidden';
      // HTTP 401.
      openIDImplicitFlowConfiguration.unauthorized_route = '/Unauthorized';
      openIDImplicitFlowConfiguration.log_console_warning_active = true; 
      openIDImplicitFlowConfiguration.log_console_debug_active = true; 
       
      openIDImplicitFlowConfiguration.max_id_token_iat_offset_allowed_in_seconds = 60;
      
      const authWellKnownEndpoints = new AuthWellKnownEndpoints();
      authWellKnownEndpoints.setWellKnownEndpoints(this.oidcConfigService.wellKnownEndpoints);

      this.oidcSecurityService.setupModule(
        openIDImplicitFlowConfiguration,
        authWellKnownEndpoints
      );
    });
    console.log('APP STARTING');

Identity server config.cs

  new Client
                {
                    ClientId = "UiProject",
                    ClientName = "Angular Client",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AccessTokenType = AccessTokenType.Jwt,
                    // Default 300 seconds
                    IdentityTokenLifetime = 300,                    
                    // Default 300 seconds
                    AuthorizationCodeLifetime = 50,
                    // Default is 1 hour or 3600 seconds
                    AccessTokenLifetime = 120,
                    // Default is 30 days
                    AbsoluteRefreshTokenLifetime = 259200,
                    RefreshTokenExpiration = TokenExpiration.Sliding,
                    SlidingRefreshTokenLifetime = 1296000,
                    AllowAccessTokensViaBrowser = true,
                    UpdateAccessTokenClaimsOnRefresh = true,
                    AlwaysIncludeUserClaimsInIdToken = true,
                    AllowRememberConsent = false,
                    RequireConsent = false,
                    AllowedCorsOrigins = new List<string>
                    {
                        ***
                    },
                    RedirectUris =           { 
                     ***
                    },
                    PostLogoutRedirectUris = { ****},  
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "***"
                    }                    
                }

Please let me know am I missing something or doing something wrong.

I do have one more question don't know if it is a issue or a feature requirement. the problem is, if i have 2 clients and open them together in one browser then i am able to login to one client with out any issue but for second client when i provide the credential to the login screen i get back 400 status code.
This issue is related to Hybrid flow.

If possible please help me with these 2 issues Thank you in advance...:-)

Thanks
Ravi

**Comment by brockallen** [comment]
If the other tab has an in-memory copy of the access token, and the token is a JWT, then it would explain what you're seeing. JWTs aren't revocable. Reference tokens are, though.

Also, the other tab should listen for the `UserSignedOut` event to know when this has happened and handle it however you want to.

**Comment by ravi22saini** [comment]
Hi brockallen,

Could you please provide me the link to the documentation where i can see how to use UserSignedOut event and if it is possible could you please help me with my second issue.

This issue is related to Hybrid flow. If i have 2 clients and open them together in one browser (different tabs) redirecting to same IDP, then i am able to login to one client with out any issue but for second client when i provide the credential and try to do login then i am getting back 400 status code from login screen, i am able to see the debug logs of IDP and able to figure out that my Antiforgerytoken validaton failed but i have no idea how to handle this. Could you please help me with this

Thank you
Ravi :-)

**Comment by brockallen** [comment]
I was confused on your question (and thus my reply). I updated above.
