### ISSUE TITLE
Call FlushAsync anywhere we use WriteAsync

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#3096]
IOW, flush the http response buffer when we know we're done, otherwise `Dispose` will call `Flush` synchronously and apparently that's bad.

**Comment by brockallen** [comment]
https://github.com/aspnet/Announcements/issues/342

**Comment by joaopgrassi** [comment]
Hey @brockallen  I could help out with this. I would probably need some guidance as I never contributed to Identity Server before though.. so might be a little tricky for me to know where exactly "we are done".

If I got it right, we would need to call `FlushAsync()`, after writing to the response body:

**UserInfoResult**
```
public async Task ExecuteAsync(HttpContext context)
{
	context.Response.SetNoCache();
	await context.Response.WriteJsonAsync(Claims);

	// flushing the response stream
	await context.Response.Body.FlushAsync();
}
```
Let me know your thoughts.

**Comment by brockallen** [comment]
yep, i think that's about it.

**Comment by joaopgrassi** [comment]
Cool. I'll try to work on this then :).

**Comment by brockallen** [comment]
merged. thanks!
