### ISSUE TITLE
How would I go about 'auto login'

### ISSUE THREAD

**Issue by briankitt** [IdentityServer/IdentityServer4#3099]
I have a front end Angular application, backed by Identity4 Server.  Everything works fine.

I have a need to send the users a link, in email, where they can log directly into the Angular app.  What I am doing, is grabbing the link, and using an API call to the Identity 4 server.  But really unsure of how to get them logged in from a known link.

I keep getting CORS errors trying to do this, which is odd, considering I have CORS working perfectly for the system already.

I have a routine that populates 'model' object with the retrieved username/password based on the link.  But on the 'Redirect', it just keeps blowing up on CORS errors, and I can't get past it.   It doesn't really make sense, because the 'returnURL' at this point, is identical to the 'returnURL' from my login controller.  I can't see any difference, but my login works correctly, this does not.

                    await _signInManager.PasswordSignInAsync(model.userName, model.password, false, lockoutOnFailure: true);
                    var user = await _userManager.FindByNameAsync(model.userName);
                    await this._eventService.RaiseAsync(new UserLoginSuccessEvent(user.UserName, user.Id.ToString(), user.UserName));
                    return Redirect(returnUrl);

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!

**Comment by briankitt** [comment]
I don't get it.  A big part of my problem is that I can't find any
documentation on your product.  If you had documentation, I can figure this
out myself.  How is this a 'commercial support option'?

If you please provide a link to documentation, I can do this myself.

**Comment by brockallen** [comment]
> A big part of my problem is that I can't find any documentation on your product.

This is a free OSS framework and not a product your company paid for.

We do offer commercial support options -- please see this section: https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support
