### ISSUE TITLE
Logout and using old access_token in API not invalid

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#310]
I have a solution with an SPA, IdentityServer4 and an API. 

1) I login correctly using the OpenID Connect Implicit Flow and have access to my data in the API.
2) I logout from the IdentityServer4 not the SPA. I expect that the previously issued access_token and id_token are now invalid.
3) I continue to used my SPA (using old tokens) and still have full access to my server data.

How do I prevent the SPA from accessing this data as the tokens should now be invalid. (server logout)

Resource API startup:
```
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

IdentityServerAuthenticationOptions identityServerValidationOptions = new IdentityServerAuthenticationOptions
{
	Authority = "https://localhost:44318/",
	ScopeName = "dataEventRecords",
	ScopeSecret = "dataEventRecordsSecret",

	AutomaticAuthenticate = true,
	// required if you want to return a 403 and not a 401 for forbidden responses

	AutomaticChallenge = true
};

app.UseIdentityServerAuthentication(identityServerValidationOptions);

```

Or full example:
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow

Greetings Damien

**Comment by brockallen** [comment]
This is also how it worked in IdSvr3, BTW. If you want access tokens to be invalidatable, then either keep short access token times and make the client frequently get new tokens, or use reference tokens and invalidate them at logout time.

**Comment by damienbod** [comment]
So a server logout is useless when using access tokens. If someone gets my access tokens, they have access to my protected data even though I have logged out. (Until the access_token have timed out) Doesn't sound like access tokens are safe to use at all.

**Comment by brockallen** [comment]
Access tokens represent consent for a client to use a resource on behalf of the user, which is different then the user logging out. If you want to tie the two together, then you'll have to take extra steps as I mentioned above.

**Comment by damienbod** [comment]
Thanks for your answer, makes sense, but for me, but if I logout of an application, (and most other users), believe that the protected resources cannot be used without logging in again.  This feel like a serious security risk. 

"use reference tokens and invalidate them at logout time" seems like the only valid solution. Have to figure out how to use this, I was using an Implicit Flow as I though this was the best practice for javascript clients. (Unless of course, logging out from the server is not a requirement)

Do you not believe that a login must be required once the user has logged out (server)?

Greetings Damien

**Comment by brockallen** [comment]
Thanks for your answer, makes sense, but for me, but if I logout of an application, (and most other users), believe that the protected resources cannot be used without logging in again. This feel like a serious security risk. 

Are the apps 1st party or 3rd party to IdentityServer and the user database? If they're 1st party, then they are all in the same realm of trust, so it's not a real concern. If they're 3rd party, that's what consent is all about. Think about when you use some app and you give it access to your google calendar. If you logout of google, should the app stop being able to use your calendar? Or think about when you use an app on your phone to access your facebook. When you logout in the browser, should that affect the app?

All I'm trying to do is point out that it's tricky. Fortunately IdentityServer allows you the flexibility to design it to work the way you want :)

**Comment by damienbod** [comment]
true, thanks, I was just considering server logouts, not client logouts. Thanks for your answers, helped me a lot.

Greetings Damien

**Comment by damienbod** [comment]
Another question, 

I'm using a reference token for the access token. How do I invalidate this when logging out and how should the resource server validate this reference token?

Greetings Damien

**Comment by damienbod** [comment]
I'll create a new issue for this

**Comment by damienbod** [comment]
ref:
https://github.com/IdentityServer/IdentityServer4/issues/313

**Comment by vanthome** [comment]
@damienbod 
have you also tried a front channel token invalidation (like from an SPA). Theoretically it should work with such a request:

```
curl -v -k -X DELETE -H 'Authorization: Bearer XXX' http://localhost:4400/connect/token
```

but for me it fails.

**Comment by leastprivilege** [comment]
Why would that work? In which spec is this defined?

**Comment by vanthome** [comment]
yea, maybe this is not in the spec (as you keep on mentioning it's also not an OAuth concern) but in reality I saw some OAuth 2 token endoints which allowed just this because it's handy in a Resource Owner Credentials scenario. Also I interpreted the property `frontchannel_logout_supported: true,` to enable this.
So what options do I have for log-out from an SPA then?

**Comment by leastprivilege** [comment]
Use the revocation endpoint?

**Comment by leastprivilege** [comment]
Also - front channel refers to this spec:

https://openid.net/specs/openid-connect-frontchannel-1_0.html
