### ISSUE TITLE
User info endpoint it's letting expired tokens pass through

### ISSUE THREAD

**Issue by Dongata** [IdentityServer/IdentityServer4#3100]
### Issue / Steps to reproduce the problem

1. Have an established IS4 server
2. Configure 30 seconds of expiration on an access token
3. Request an access token
4. Check decoded time to check the expired time
5. Hit /connect/userinfo endpoint when the  token is recently expired

#### Expected result
401

#### Result 
User info normal scoped response.

### Take into account
We're using 30 second expiration time for refresh token testing on a invisible log in for a mobile application using RO flow
We removed Skew time on api

**Comment by brockallen** [comment]
>  We removed Skew time on api

But I bet you're getting the skew time in IdentityServer's JWT validation. Try it after 5 minutes and see if it's still allowing the tokens in.

**Comment by Dongata** [comment]
Yeah, i mean after 5 minutes the validator takes it as expired, but i didn't find a configuration in Identity server api to change it on the idp itself for the built in endpoints. ¿It has one? ¿should have one?

**Comment by brockallen** [comment]
I don't know if we expose it... @leastprivilege?

**Comment by leastprivilege** [comment]
We don't...

**Comment by leastprivilege** [comment]
If we should please open a new issue with a feature request.
