### ISSUE TITLE
Can IdentityServer4 in one instance reference Microsoft Identity in a separate service instance

### ISSUE THREAD

**Issue by jcoxprog** [IdentityServer/IdentityServer4#3103]
Sorry if this is obvious, I am going in circles

I would like to use IdentityServer4 Login and Logout screens running in its own service but configure it to use Microsoft Identity in a separate service. I don't want any of the Identity Razor pages I just want the "back end" logic. Basically I think I want the SignInManager and UserManager in the IdentityServer instance to be pointing to the Microsoft Identity instance, if this makes sense.

Thanks

**Comment by brockallen** [comment]
You would need to invent a way to coordinate across the two. I know others have done it, but I don't have any suggestions.
