### ISSUE TITLE
How does MvcHybridAutomaticRefresh refresh the token? Is it on an interval?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#3106]
https://github.com/IdentityServer/IdentityServer4.Samples/tree/master/Clients/src/MvcHybridAutomaticRefresh

I am really confused how this works, and there is not many comments or other info to go off of. 

It looks to me like the meat of the logic is here in [AutomaticTokenManagementCookieEvents.cs#L36](https://github.com/IdentityServer/IdentityServer4.Samples/blob/master/Clients/src/MvcHybridAutomaticRefresh/AutomaticTokenManagement/AutomaticTokenManagementCookieEvents.cs#L36) but I do not understand when `ValidatePrincipal` gets invoked.

To me this sort of looks like it runs every single time the user makes a request to the app, and then the token is refreshed if its expired before the users is authenticated.

**Comment by KevinCathcart** [comment]
You are absolutely correct. This is checked on each incoming request. This pattern mirrors the behavior of the sliding expiration mode of cookie authentication, but is updating the tokens. (If it is successful it will re-issue the cookie, effectively providing sliding expiration for the cookie as well).

Note that the sample application there is expecting a relatively short lifespan of the refresh token. It would ideally have a lifespan of no more than twice the cookie expiration time-span set in the client. (On the order of hours, as opposed to days, which is somewhat more common of a refresh token lifespan).
