### ISSUE TITLE
EntityFramework query optimization

### ISSUE THREAD

**Issue by MichelZ** [IdentityServer/IdentityServer4#3107]
### Issue / Steps to reproduce the problem
- Use EntityFramework as Client Store
- Record SQL queries with something like Application Insights

### Problem
Lots of SQL queries get executed.
The tables are queried one by one for a Client, going through all tables like AllowedGrantTypes, RedirectUrls. 
It looks like it's not joining the tables together, despite using the ".Include()" syntax.

![image](https://user-images.githubusercontent.com/1040252/54541439-37b65c00-499a-11e9-9826-a4a1c4a3fe6d.png)

Is there anything that can be done to optimize this behavior?
EF should certainly be capable of properly joining these tables together, and only issue a single query to retrieve all necessary information from the Tables for a single Client?

**Comment by huysentruitw** [comment]
Probably related to the way EF Core 2.x handles includes, should get fixed in EF Core 3. Related issue: https://github.com/aspnet/EntityFrameworkCore/issues/12098

**Comment by brockallen** [comment]
Have you had a chance to re-evaluate these queries under EF Core 3.x? There was some rework to update to that, so I'm curious if you had a look.

**Comment by brockallen** [comment]
Ping?

**Comment by MichelZ** [comment]
Unfortunately I'm not involved anymore in the identity part in my organization, so I don't have visibility into this anymore, I'm sorry.

**Comment by brockallen** [comment]
Ok, thanks for the update.
