### ISSUE TITLE
Logging IdServ4 Events with Serilog and Seq?

### ISSUE THREAD

**Issue by mcquiggd** [IdentityServer/IdentityServer4#311]
Hopefully a quick question:

Previously with IdServ3, @leastprivilege had posted a handy blog entry to add a SeqEventService, which was registered as via a Factory method as an EventService:

https://leastprivilege.com/2015/10/22/identityserver3-logging-monitoring-using-serilog-and-seq/

The Factory approach, and indeed the Event Service seems to be no longer with us in IdServ4. 

Is such Event logging available by some other approach with IdServ4?

**Comment by brockallen** [comment]
We will still have the event service. If you write a custom one, then put it into DI.

**Comment by mcquiggd** [comment]
@brockallen 

Thanks Brock, 

Just to be clear, the EventService will be added later, or is already in place...? I have looked through the source and was unable to find this, or an extension point where one could be added... 

Probably a case of me just needing to be patient while the core stuff is finalised...?

**Comment by mcquiggd** [comment]
Ok, forget that... all is working:

A) Take the `SeqEventService` class mentioned in the blog post at:

https://leastprivilege.com/2015/10/22/identityserver3-logging-monitoring-using-serilog-and-seq/

B) Instead of registering it with the Factory as described, use the following in your `ConfigureServices` method:

`services.AddTransient(typeof(IEventService), typeof(SeqEventService));`

C) Ensure that the relevant Eventoptions are set, for example, in your `ConfigureServices` :


```
            var identityBuilder = services.AddIdentityServer(options =>
                     options.EventsOptions = new EventsOptions
                     {
                         RaiseErrorEvents = true,
                         RaiseFailureEvents = true,
                         RaiseInformationEvents = true,
                         RaiseSuccessEvents = true
                     });
```

**Comment by danjohnso** [comment]
For anyone else that comes across this, the DefaultEventService will write the event out to the logger registered with the DI system (Serilog/Seq if you have it configured so).
