### ISSUE TITLE
IdentityServer4.EntityFramework.Entities update

### ISSUE THREAD

**Issue by wilson0007** [IdentityServer/IdentityServer4#3110]
Not so much an issue as a wtf.   See the migration code below.  And yes I am being nitpicky

`  migrationBuilder.AlterColumn<string>(
                name: "Value",
                table: "ClientSecrets",
                maxLength: 4000,
                nullable: false,
                oldClrType: typeof(string),
                oldMaxLength: 2000);`

So 2000 characters was not long enough for a secret hash?  You felt the need to boost it up to 4000?  Good thing too because my job just implemented a no less that 2001 character secret hash policy.  Seriously why is even done?  Who is this effecting?  Why stop at 4000?  Why not just varchar(max)?  Shit let's make all fields varchar(max).  Data is cheap right?  How about you put your efforts toward real issues, instead of unnecessarily increasing the size of my database.

**Comment by brockallen** [comment]
> So 2000 characters was not long enough for a secret hash

The value holds secrets, not just a sha256 of a symmetric secret.

**Comment by wilson0007** [comment]
4000characters... 
 dalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdssdalhfheruherjknbj,mbvnjsdhfukdeshrdjsnvcdjskhfuerhjjdfnbcvjskhfwkuehnjndvcjsdhfdekjfdss

**Comment by wilson0007** [comment]
curious as to why none of that is mentioned here

http://docs.identityserver.io/en/latest/topics/secrets.html

Can you point me to an example of what you are taking about or cite a situation where this is needed?  Thanks
