### ISSUE TITLE
Merge two accounts using IdentityServer4

### ISSUE THREAD

**Issue by mushthaque-pk** [IdentityServer/IdentityServer4#3111]
We built OAuth identity server using .net core identity server 4 third party library. The identity server support both direct login and facebook login. We are now thinking to merge direct login user and facebook user if both have same email ID. So can you please suggest how to integrate this feature in our identity server. Is there any built in support or best practice to implement this? 

Any suggestion or ideas greatly appreciated.

Thanks!

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
