### ISSUE TITLE
IdentityServer doesn't preserve subpath for discovery document

### ISSUE THREAD

**Issue by BoasE** [IdentityServer/IdentityServer4#3112]
Hi

I'm not quite sure if it is a bug if not please let me know.

We hosted identity server on  and everything worked fine.

Now we moved it to ```https://mySecondDomain.com/auth``` but as a result the discoverydocument doesn't preserve the ```auth``` subpath. 

When I look at public origin it says "the origen is inferred from the request" so my expectation was that identityserver should be aware of it.

When I set the PublicOrigin manually it works fine.

So is it expected or a bug?

**Comment by brockallen** [comment]
How are you configuring the subpath? In your web server, or in the aspnet core pipeline somehow?

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
