### ISSUE TITLE
Front Channel and Back Channel Logout Sample Code request

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3119]
Hi,

Do you have any sample code which exhibits Front Channel and Back Channel Logout scenario in Aspnetcore MVC application?

You quick response is highly appropriated.

**Comment by brockallen** [comment]
Did you check our samples?

**Comment by Sathiyanathan-Macro** [comment]
I have seen it. But not saw specific sample codes for Front Channel and Back Channel Logout.

Can you please share the exact sample path for this?

**Comment by leastprivilege** [comment]
See

https://github.com/IdentityServer/IdentityServer4.Samples/blob/master/Clients/src/MvcHybridBackChannel/Startup.cs
and
https://github.com/IdentityServer/IdentityServer4.Samples/blob/master/Clients/src/MvcManual/Controllers/HomeController.cs#L42

**Comment by Sathiyanathan-Macro** [comment]
Hi,

When I call
HttpContext.Signout() function then cookies has been set like below.

{idsrv=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; httponly,idsrv.external=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; httponly}

**Comment by brockallen** [comment]
I don't follow what you're trying to explain./

**Comment by Sathiyanathan-Macro** [comment]
Sorry Brockallen,

I followed least suggestion, now we can able sign out without any issue using Back Channel Logout Uri.
