### ISSUE TITLE
Post login screens (like Ts&Cs or 2FA) before Consent

### ISSUE THREAD

**Issue by sai-nagarjuna-t** [IdentityServer/IdentityServer4#3122]
This is more of a query. 
After logging in with username and password, I wanted to support any number of arbitrary extra screens like Terms & conditions or 2FA screens before the 'Consent' screen.

And at the same time I need to make sure that these extra screen are protected from unauthorized access. (i.e., to stop people navigating directly to the T&C screen )

I have tried adding a temporary AuthenticationScheme cookie after login to protect the extra screens.
The another approach I have in my hand is to post back the forms to the same route, so that there will only one URL and that way we don't need to worry about 'protecting' access to each individual step.

can u please suggest if there is a better way that IDS 4 supports to handle these post login screens

Thanks

**Comment by brockallen** [comment]
Yes, a temp cookie would be the way to go, but having said that: 

This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
