### ISSUE TITLE
Enhance quickstart CSS to be mobile friendly

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#3126]
So the login page (etc.) looks decent on iOS/Android.

**Comment by joaopgrassi** [comment]
Hey @brockallen, I could take a look at this. Not a UI expert, but if only what's needed is to make it responsive, then I might be able to do it. Quick questions though:

- Do you have something concrete in mind already (design-wise)?
- I guess we want to stick with Bootstrap? What about moving to Boostrap 4?
- This is the `css` we're talking about, right? `https://sourcegraph.com/github.com/IdentityServer/IdentityServer4.Quickstart.UI/-/blob/wwwroot/css/site.less`

**Comment by brockallen** [comment]
Sure, help would be great. We have an open PR for bootstrap 4 -- so we want that done first.

**Comment by leastprivilege** [comment]
Is this done with the move to bootstrap 4? @brockallen

**Comment by brockallen** [comment]
No.
