### ISSUE TITLE
Identity server returns same token for different client credential requests if it was executed in the same time (second) 

### ISSUE THREAD

**Issue by andreypr17** [IdentityServer/IdentityServer4#3129]
Identity server returns same token for different client credential requests if it was executed in the same time (second)

### Issue / Steps to reproduce the problem

Request a new token using client credentials grand type in the same second from the same machine to the identity server site, the results was the same token for all request in the same second, if a request enters in a different second, a different token is returned

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Can you send a PR with a new unit test or integration test that reproduces this? Without a concrete repro, it's hard to know what's the cause.

**Comment by andreypr17** [comment]
Client:

`using IdentityModel.Client;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Http;
using System.Threading.Tasks;

namespace Client
{
    public class Program
    {
        private static async Task Main()
        {
            // discover endpoints from metadata
            var client = new HttpClient();          

           var disco = await client.GetDiscoveryDocumentAsync("http://localhost:5000");
            if (disco.IsError)
            {
                Debug.WriteLine(disco.Error);
                return;
            }
            Dictionary<String, String> miDiccionario;
            int i = 0;

            for(i = 0; i < 10; i++)
            {


                var tokenResponse = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
                {
                    Address = disco.TokenEndpoint,
                    ClientId = "haroldCliente",
                    ClientSecret = "!234s678",


                    //  GrantType = "hybrid",
                    Scope = "haroldAPI"

                });





                if (tokenResponse.IsError)
                {
                    Console.WriteLine(tokenResponse.Error);
                    return;
                }
                Debug.WriteLine(i.ToString());

                Debug.WriteLine(tokenResponse.AccessToken);

                Debug.WriteLine("\n");

                //System.Threading.Thread.Sleep(1000);
            }


        }
    }
}`

Identity Server Client

              `  new Client
                {
                    ClientId="haroldCliente",
                   AllowedGrantTypes=GrantTypes.ResourceOwnerPasswordAndClientCredentials,
                    ClientSecrets = {
                        new Secret("!234s678".Sha256())
                    },
                    AllowedScopes={"haroldAPI"}
                }`

Log for execution with duplicate tokens
0
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


1
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


2
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


3
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


4
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


5
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


6
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


7
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


8
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


9
3/27/2019 6:02:02 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQxMjIsImV4cCI6MTU1MzcyNzcyMiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.R2pQQ4WNs-JhTymo3M8oroBkKAjxqjbpJkoyHQptEaZLXBOEx3VWNH-sVE4ibrmnr0ouN3Hmp2Wx6a6326nj7MAA1he2aJDf1YKCUR2xNPi2q2eWxbVMCiCHZl7eFAYxK3nGwkZ3Za9DSicHsju3whhrCGpHZyvbJRPXihHk2jv0erWB7M3WBBEBcAkkp7kAtaCVGm2-qmZMnFNVfH1Df8jQ_n1iPR_qfp4I0fGDYCEmaLxtsplU6mUSdr2BQcnjhmBUm2Qv2cvEH7-hPrM3pq9qHZ34ar0m5MpCMmWjz_GlIGu_uwvkV2hENimKv31M4EeRCbsi3Yt6QJZH4TH62w


Adding System.Threading.Thread.Sleep(1000) -- No duplicate Tokens

0
3/27/2019 6:06:19 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzNzksImV4cCI6MTU1MzcyNzk3OSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.gouoO7oxbm5UXzeIQNiLEHpXOIl75ffjuevaIcboJvA1ET36rE2ROSRICGUFYAlzzEkcsJeXmsVRCKkAZWWjGn33ptx3xVK3vEpXUnxozuCICdQDyzWyzDMJFT50n8OI-3W0J_GLLFivjAzHjj6M1eaZfRf_LJPjoxYbzDEokmgzydoXCQ5o4Bt9UiALLrN5BWbnPG6ACBfD_iv3dc5MjmDYppbVbDmUV4qtp7tD6c6uD7LC_No7FBckYEOxxYXHEvalcJEd0z-UNtbzLHbwrHw7eK4OxsD8DSObnS0awSdVITZAnNlXDKll5JRxH79wZDg6lv_JuhFQDQdcB4uNjw


1
3/27/2019 6:06:20 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzODAsImV4cCI6MTU1MzcyNzk4MCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.DFapeQs1TQI75TU5jUCrLjnF-Yf_lsFl7D1i-uy0I6vJOCWysina97mTm2O_-_81E3dkOUH-Mp0KI2v1d4dJ68jI_EhCSbML0dmq63DucUS37pkXJwMqchkyiBHBfyFY9ehLGEcE0KD95iWU8_l7eLdyuURXRa-5msK-DbTezXKSUW0CrFiaTchc5y02HZER_IVqjP-_AQnnNnmOAVYGsLnI4n7EEDP8gtcC4WU_yhI21AQcn6qd-6oC3FPMrT4nge5P68eMWyBw1I0DduUyaLze0QJ4Xw6lBOHlpRfUfY8b3E0dRwDcIgER3zIi22_fMFP0PE43mCObEPci8KcHsg


2
3/27/2019 6:06:21 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzODEsImV4cCI6MTU1MzcyNzk4MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.fqhRjYYllDx_tpdo11ZMvDr0ogTyvkvbEYPn_U6ROr_FOhzbIVsiFcJ2GPI0EMR5fK7YVryjoi5yQ8lTV7kv3USE7DPioO3QkURRBWjdVVvir0j9Ituza-2xRsCZAUyqjQKaL61iUX8F6RsT4XBVW0JJ59IIm05uf6RdOJDcc_ufeIEQjz4qB_JrPE-fse_v5MdKbp3zMkXJJ2hdiencxTuF7hHix1cc33vRoB0ZyyMMmoALOS6V1ayDPglVQYZ4poFtOlQRw0wvQw3hIJKGiE3Xj2E8AaupXxl9FFTksJuQTkFLRKPO2D7rzRhyCCDNSMi1-9EsaRNa7VmdW-E_mg


3
3/27/2019 6:06:22 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzODIsImV4cCI6MTU1MzcyNzk4MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.ZUaNah7tORHohf6kfCngKwruD6bchtVeB0IfkBkh5Ztx6Y1r_JKNVbIgLrXCN4_wLimYg37Aa72kLNxq_DmmbjzsoGOpomthbCIKL81w-yuPVHKCtLTycdBGYDmlJzehF-xjLXE8MfosGaxLAsY-DdVKNsfc3mN9Z0f8VPQx3NP0PAKrHmmE6gpWYimcGMrO1NDXBRUxKWFIkiz12WyguYWC_vJuq4UiIkjs0P2p41LlwRAwMnJIACRMBVyggfO7iB37h6MDFpb8V9LILPitO6qZaD8oqwpmOKApfLiCROKxkYGUMNeyKLOYRUEa5n_MFFL-q4hHTx0h1xyDyAPsoA


4
3/27/2019 6:06:24 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzODQsImV4cCI6MTU1MzcyNzk4NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.Id13aTn9Ya7DE4Sv7f9Wfioqr3fuLAIKLTfmaZpw94LPV5qzBgB46mouYSUi21nfyasSw6ImMbZgJHeo0o4FXi9J5O4Zf2HrgzgjNNyCtVz4sr0nvy4aHYiuC2HS5Hqf4e37ovbSh8vo6S4Bx35uiMNAuTvrNTznSYAnLm08QzF3OhnwY35inQGdLGr2Ts2w6VrC0PJsB_Gs9-W0m0JG0vc4Aa7UTI2J0HmX0wFFnxXXrAcY_NiGxboGTZjYVTu8Cwl9rE076faHvpjF-RVNXAenSfWg2LMLGusoomdeCE5m1G39VZx-fQSb9GTZ0S1et5UygsrakflVHkIth9u5kw


5
3/27/2019 6:06:25 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzODUsImV4cCI6MTU1MzcyNzk4NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.Lw9NOBva1_ehCSF2GYPvFsMRhvzAqUOVxnVHzRHn4m2P87m20TwUKlyvfFDe8L9ruv7ZYhCzOUId60rYKOXwLSVFXoOsChI9xP4UFVpn7xMCTAGRTSORIleICzjkJHnq5hmWFiLBpfovlvUUQL-6u2MDoJoWuEHcacllNTtsAYJX-fg2ZIyLNhEBd6hquHPAHtqiZGENPXP8Tts7ZJqb6DQhv9ecKiMeQGS2Kky6jtMYPn9PDV97b2ucqdJtaehYWqivlyneKJzjbQy-WrLJ8Gy2Yu24oHrBfq2Eq5aiLX1t0mwMI_u_SjjA7jwN6_V-zZN6fi0p5yh_HB6RxpZOMA


6
3/27/2019 6:06:26 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzODYsImV4cCI6MTU1MzcyNzk4NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.BHrIdDCPLrBMdk3RhaSf-PM0W_lBF-4juoi9-NxHjRjaOVgn7Pn04TCVNVlOc54vZF9CTwxeu9NwrYI_NKVbi1-N2L7CL8-Va6Awkov8uKDikhPRYdXGrRC5osmOeE1YcZloEmj50YEis0hPRHWwRpvzcblVSPC5zqiTBx7EiKwnPvSgtS744N99BfmUn9dwnl6Jcf5TakIwUONi0O6CWU9Jnu-rMNZGryEC5_FD36aclUkOhzF8Frx5GYJ3j-oN5-mjDQDHmuczkhwcMTy5s6KqoorD7gnszzE-SPE_Dq-VRQGaw7PhYIELeUZbxE6dWefrs4GAfwLYlGxqCU5Orw


7
3/27/2019 6:06:27 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzODcsImV4cCI6MTU1MzcyNzk4NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.cqo6J3-Rgg6iVJcvmeT5Bta_7wnYCnczKPuVvnBA0Bj5IrvzfuYleBf4LW60FtH82uwj-MfijXWBAC2UZ_YyUQK3aGs3Q9OSsIWu1DKbA4sgrHY_4eQ9mqS8I_kN7MSYrAFz3QPxoHMDbC00hkeagceXQdrydIlSt0FVKgmQJMs_LZnXAMUMjl2ohbSo0sI97IdZzpuzyOYii7Fr95_wV9XgYFk_wMoY3uylnLLeY9mxU7svXpXSZLoac9Ul-ljmIzKJ8qYBllAV5yGNaoDQ3obWdc4eqIijOzZQKHAsrPOUlmEEOi7hi31JAviFhbxQ_1CWVIMgjy6t8E7NmYbFyQ


8
3/27/2019 6:06:28 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzODgsImV4cCI6MTU1MzcyNzk4OCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.ZfqhzAedwGisw2n86OZ9PT8DuvXkAV0fXpqT-TP3hnj6-b0qgEH9boNz5CyKoFwV-N_WL7MOhSS-BMvztQ69CZkq0NWXUNaDBcC4GMxd4yiF51RRLltZDr8i9wd3uRypf3MSZJNN69p33NU1dXJZG9hz15HML2gkM0H8tJYWqXZz-on__r_3NieyW5U3vj9J1E2cZnPpWvDz2sn76ekVJBmMvW7QuHxbTJS7vloFIGTOfWHj26Q8n8QtWt05sbFjwzdRTci8Ins6e-4cSz2TPAyCn009YNna1pp_FLSpSbd1VZ0zyp2vhd1t8nvQTEgJMh4qZaRh6jrzE8Ff5zKDkA


9
3/27/2019 6:06:29 PM -04:00
eyJhbGciOiJSUzI1NiIsImtpZCI6IjI1YTg3YmE3ODQxZTVkMDk0Zjk4YmQxNmU4MDIwZjhkIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTM3MjQzODksImV4cCI6MTU1MzcyNzk4OSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJoYXJvbGRBUEkiXSwiY2xpZW50X2lkIjoiaGFyb2xkQ2xpZW50ZSIsInNjb3BlIjpbImhhcm9sZEFQSSJdfQ.hGJsONsoIt9W6I6T7LJV-R69eUGQE1eifRalKbU4Uf2oVDIeXQkZPWWLJgpOJzmVyBhKpUojvvWSyBFXkXzkblp9gi28Bqojcgl2_Mqm1YEy4GHN4xqX0NVm-SxfbbQXjN4EX48KxPS-pnXr2RFtSPxl5emBjRlKqxkzH2meu3HCUr4NAi2ILDD96qDsOJwK0_i4QfnhREoI26xDZ4I1Tng-4F0j7sEwakrn6ZXKOGp4mmEK9xbFBF-kz-EGIS4YkrWzZ7Q0WfHtjF6JfBJI1Y1qaWE-6qLcr4VDUbXdL8Qkc_w71ix1WSA2HMooS_WGmAQufASXp16jA0-86NwnNw

**Comment by huysentruitw** [comment]
Isn't that normal? As tokens are JWTs (post them on https://jwt.io to see its content) and the content only changes each second (nbf and exp field). And the signature follows the content, so...

**Comment by bobekhj** [comment]
@huysentruitw Doesn't the token also encode subject information? If the credentials are different, even if the token was created at the same time it would have different claims, wouldn't it?

**Comment by andreypr17** [comment]
We are using a Middleware to send the same credentials for all requests to the Identity server

**Comment by leastprivilege** [comment]
So what's the issue then?

**Comment by huysentruitw** [comment]
@bobekhj the sample code uses the same credentials in all requests

**Comment by brockallen** [comment]
All set on this issue -- can we close?
