### ISSUE TITLE
Validate reference token on resource server and delete reference token with IdentityServer4 user logout

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#313]
I'm using a reference token for the access token in an OpenID Connect Implicit Flow. 

1) How do I invalidate the reference token when logging out on IdentityServer4?

2) How should the resource server validate this reference token? (Using IdentityServer4.AccessTokenValidation or any other way) Can't get the Introspection options to work.

Greetings Damien

**Comment by leastprivilege** [comment]
You can use the persisted grant store to delete tokens at the logout endpoint.

Reference tokens are validated using the introspection middleware (or the is4.accesstokenvalidation)

**Comment by brockallen** [comment]
Even better -- the `IPersistedGrantService`. It has higher level API specific to reference tokens, refresh tokens, etc.

**Comment by damienbod** [comment]
@brockallen @leastprivilege, the IPersistedGrantService works perfect! 
IdentityServer4 is pretty awesome, very flexible.

thanks

**Comment by Jonatthu** [comment]
Where is the documentation of this?
Can  I use this without asp.net core  Identity 3?

**Comment by brockallen** [comment]
No docs yet for this. It's a work in progress. And no, you don't have to use AspId3.

**Comment by Jonatthu** [comment]
So for do a Reference Token and for an emergency revoke a token, Is it not include right now, right?
Just to be sure

**Comment by brockallen** [comment]
reference tokens are implemented, yes

**Comment by Jonatthu** [comment]
Is there any documentation? 
If not maybe I would like to help with the docs if there's something that I can do.

**Comment by damienbod** [comment]
@Jonatthu  here's an example:

https://damienbod.com/2016/09/16/full-server-logout-with-identityserver4-and-openid-connect-implicit-flow/

Greetings Damien

**Comment by Jonatthu** [comment]
@damienbod  thanks I will try it without identity and from scratch, and publish my results following your tutorial, any advice?
