### ISSUE TITLE
Document LocalApi

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3131]

**Comment by LindaLawton** [comment]
Want to come with a description for those of us who dont mind writing docs?

**Comment by leastprivilege** [comment]
It's a new feature we added in 2.4 - it needs documentation. I am probably the only person right now that is qualified for that (unless you want to follow the commits)...

**Comment by LindaLawton** [comment]
(unless you want to follow the commits)...  thats always fun.

**Comment by leastprivilege** [comment]
It's in our host...

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/host/Startup.cs#L62

**Comment by leastprivilege** [comment]
here's the client

https://github.com/IdentityServer/IdentityServer4.Samples/blob/master/Clients/src/ConsoleClientCredentialsFlowCallingIdentityServerApi/Program.cs#L36

**Comment by brockallen** [comment]
This commit shows what I had to do to update local API validation to use this new feature:

https://github.com/brockallen/IdentityServerAndApi/commit/6164235caa13c13e453b605418bc1eeccebeb6d3

**Comment by leastprivilege** [comment]
done
