### ISSUE TITLE
IdentityServer4: Quickstart UI improvements

### ISSUE THREAD

**Issue by Jurabek** [IdentityServer/IdentityServer4#3134]
Currently, Quickstart UI API controllers bit harder to modify, test and extend

We can move all `helper API` methods to testable separate classes for each `ViewModels` applying Builder pattern and write UnitTests and inject those interfaces to controllers

**Comment by leastprivilege** [comment]
Since this is really only meant as a sample to get you started - I prefer the "simplicity" of having the code in one place.
