### ISSUE TITLE
Back-Channel Logout Token: Allow configuring additional claims

### ISSUE THREAD

**Issue by john--** [IdentityServer/IdentityServer4#3139]
This is regarding the logout token passed to the endpoint upon a back channel logout.

I noticed that it only includes pretty typical claims in the JWT such as subject, session ID, and that sort of thing. We have a Relying Party that is asking us to include a more specific claim, such as email. The OIDC spec seems to indicate this this is valid, but Identity Server 4 doesn't seem to allow this functionality at the moment.

Is this something viable to add to Identity Server?

**Comment by brockallen** [comment]
That's not in the back channel spec. Does it allow for custom values as well?

**Comment by john--** [comment]
Hi @brockallen. Thanks for the reply. Also sorry for the slow response. Maybe I misunderstood the spec but it mentions:

> Logout Tokens MAY contain other Claims. Any Claims used that are not understood MUST be ignored.

It sounds like basically anything but "nonce" can be allowed, which I intrepret as including custom claims, but I could be wrong.

**Comment by brockallen** [comment]
So you want claims about the user sent... the class that does this might be in DI, so you might be able to replace/override it. If not, then we should make this more extensible.

**Comment by brockallen** [comment]
I started working on this on a branch. Have a look and see if you think this will help.

**Comment by john--** [comment]
Thanks Brock I'll check it out!

Sorry for the lack of replies, I've been a little busy.

**Comment by john--** [comment]
@brockallen ,

So I could implement the IBackChannelSignoutService interface, register that through DI, and add my desired claim logic to CreateClaimsForTokenAsync()? i like this. It makes sense to me.

**Comment by brockallen** [comment]
Even better -- derive from the DefaultBackChannelSignoutService and override GetClaimsForToken, call the base, and add your additional claims.

**Comment by john--** [comment]
Ah that's public. Nice! Excellent job. Much appreciated.
