### ISSUE TITLE
Single Logout with a client having multiple domains

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4#3142]
We have a working IdServer4 that has been running for a while and has several clients. For whatever reasons we had not implemented single log out but now we need to.

I think front channel would be the easiest for us to implement but the problem I see is that there is only 1 entry for logout URI per client. We have a couple of clients which have 2 top level domains.

Does anyone know how this could be implemented? All I can think of off the top of my head is for the logout end point itself redirecting to a 2nd logout URI

**Comment by brockallen** [comment]
Use backchannel then.

**Comment by daver77** [comment]
Thanks. Front channel just delete cookies, so eawsy to understand, I can't seem to get my head around how back channel actually works. I've had a look at your sample code and it just seems to read data
https://github.com/IdentityServer/IdentityServer4.Samples/blob/master/Clients/src/MvcManual/Controllers/HomeController.cs#L58

Do you have any links to help me understand it better?

**Comment by brockallen** [comment]
Just our samples and the spec

**Comment by daver77** [comment]
Yeah i've read both but i'm confused as to how the logout actually happens, specifically
https://openid.net/specs/openid-connect-backchannel-1_0.html (2.6) "If any of the validation steps fails, reject ....... Otherwise, proceed to perform the logout actions."
Can you point me to the line in the samples that does that please

**Comment by brockallen** [comment]
That logout action is up to your client design. With out of the box session mgmt from ASP.NET Core, the back channel can't delete the cookie, so you need to figure something out.

**Comment by daver77** [comment]
Thanks.
Useful link for anyone else finding this post
https://blog.tretainfotech.com/posts/2018/august/single-sign-out-in-identityserver4-with-back-channel-logout/

**Comment by brockallen** [comment]
Nice find -- I'll add that to our community blog posts
