### ISSUE TITLE
Signout Server Itself - OIDC Flow

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3145]
Hi,

Is it possible to logout/Signout the Logged in User by server itself in Oidc flow instead of client using Front/ Back Channel logout process?

As per the Open Banking UK Standard, Server itself has to logged out and then redirect to client (TPP) with auth. code and id token.

Can please assist us on this?

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!

**Comment by YaremaVuyiv** [comment]
> Hi,
> 
> Is it possible to logout/Signout the Logged in User by server itself in Oidc flow instead of client using Front/ Back Channel logout process?
> 
> As per the Open Banking UK Standard, Server itself has to logged out and then redirect to client (TPP) with auth. code and id token.
> 
> Can please assist us on this?

Hello. I have the same issue. If you found out the solution for this, could you please share it?

**Comment by Sathiyanathan-Macro** [comment]
> > Hi,
> > Is it possible to logout/Signout the Logged in User by server itself in Oidc flow instead of client using Front/ Back Channel logout process?
> > As per the Open Banking UK Standard, Server itself has to logged out and then redirect to client (TPP) with auth. code and id token.
> > Can please assist us on this?
> 
> Hello. I have the same issue. If you found out the solution for this, could you please share it?

For intrim solution, we have add cookies expiration time is very less.
