### ISSUE TITLE
Any example for Google authentication for web api asp.net core ?

### ISSUE THREAD

**Issue by redplane** [IdentityServer/IdentityServer4#3147]
Hi,

I'm using `IdentityServer4` for my `Web API` written in ASP.Net Core.
I have been searching for tutorials about applying `ASP.Net Core Web API` and `IdentityServer4`, but every example is about `MVC Website`.

Any example for this ?

Thank you,

**Comment by brockallen** [comment]
Our samples have an API: https://github.com/IdentityServer/IdentityServer4.Samples/tree/master/Clients/src/SampleApi and most of the other clients in those samples call that API.

**Comment by redplane** [comment]
In [IdentityServer4 documentation](http://docs.identityserver.io/en/latest/quickstarts/4_external_authentication.html). 

After successfully added `Google Authentication` that mentioned in the topic, I couldn't find anything related to how to test that implemention using `Postman` or `Web API`.

I already understood how `Google OAuth` work and successfully implemented that flow manually, however, when I get started with `IdentityServer4`, I dont know why when I used [http://localhost:56219/connect/authorize?client_id=mvc&scope api1&client_secret=secret&redirect_uri=http://localhost:56219/api/user/login&response_type=code id_token token](http://localhost:56219/connect/authorize?client_id=mvc&scope api1&client_secret=secret&redirect_uri=http://localhost:56219/api/user/login&response_type=code id_token token) , if I input my username & password (using `hybrid` flow), I can get `access_token`. With the same link, when I click on `Google` button, I received nothing.

Its very hard to a beginner like me.

**Comment by eflorespalma** [comment]
> Our samples have an API: https://github.com/IdentityServer/IdentityServer4.Samples/tree/master/Clients/src/SampleApi and most of the other clients in those samples call that API.

Why this repo doesnt exist any more?

**Comment by brockallen** [comment]
moved to this repo for consolidation: https://github.com/IdentityServer/IdentityServer4/tree/master/samples
