### ISSUE TITLE
How to pass Passing acr_values for Authorization Code flow (IdentityServer3 Openid connect)

### ISSUE THREAD

**Issue by jishnus** [IdentityServer/IdentityServer4#3150]
If you are using SSO and your account is linked to the same account you are using on Salesforce you would not need to show the login page.

The identity server is supported for passing additional authentication related information to the user service.

acr_values - there are also values with special meaning: idp:name_of_idp bypasses the login/home realm screen and forwards the user directly to the selected identity provider (if allowed per client configuration)

So we can set up the params like acrValues: "idp:SalesForce"

But It's getting an error screen not redirect to our callback URL.

ERROR IdentityServer3.Core.Endpoints.AuthenticationController - IdP requested was: SalesForce, but the user service issued signin for IdP: idsrv

How to resolve this issue?

**Comment by leastprivilege** [comment]
This is the issue tracker of IdentityServer4 - IdentityServer3 has no free support anymore. If you need commercial support, let us know.
