### ISSUE TITLE
IDS4 can't be added to DotNet Framework API 4.7.2 OWIN

### ISSUE THREAD

**Issue by Genata** [IdentityServer/IdentityServer4#3151]
I'm trying to setup Identity Server 4 Auth server in ASP.NET Framework 4.7.2 WEB API, but I can't get it working. I'm not able to add appBuilder.UseIdentityServer() in the Startup class. 

Is it possible to use IdentityServer4 like that? 
What am I doing wrong here?

This is my startup class:

`
        public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            var builder = services.AddIdentityServerBuilder()
                .AddInMemoryIdentityResources(IdentityServerConfig.GetIdentityResources())
                .AddInMemoryApiResources(IdentityServerConfig.GetApis())
                .AddInMemoryClients(IdentityServerConfig.GetClients());            
        }

        public void Configuration(IAppBuilder appBuilder)
        {
            HttpConfiguration httpConfiguration = new HttpConfiguration();
            WebApiConfig.Register(httpConfiguration);
            appBuilder.UseWebApi(httpConfiguration);
        }

    }
`

Here is a [link](https://github.com/Genata/TestIds4Api472/tree/master/TestApi3) to my project: 

I've been looking for solution for couple of days, but I can't find anytning helpful. Excuse me if I've missed something. 

Thanks.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
