### ISSUE TITLE
Seesion expired

### ISSUE THREAD

**Issue by sanathkumarshetty** [IdentityServer/IdentityServer4#3152]
Session Expired

HttpContext.SignOutAsync("oidc") its redirects to login page.

is there any way I can clear identity server cookie without redirecting to login page

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
