### ISSUE TITLE
Redirect url with ephemeral port?

### ISSUE THREAD

**Issue by iconics-milan** [IdentityServer/IdentityServer4#3154]
Does the IdentityServer accept a random port in the Redirect URI when the client uses the loopback interface, as described in RFC8252 here?

https://tools.ietf.org/html/rfc8252#section-7.3

Alternatively, is it OK if I fill the Client.RedirectUris collection with 65535 entries?

**Comment by LindaLawton** [comment]
_Note: I haven't tried this but Identity server 4 is extremely configurable_ 

You should be able to make your own custom validator [AuthorizeRequestValidator.cs#L128](https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/IdentityServer4/src/Validation/Default/AuthorizeRequestValidator.cs#L128)  Then you can just have it validate how ever you wish.   


>is it OK if I fill the Client.RedirectUris collection with 65535 entries?

I am not sure where you are storing these but if its in the database i dont think there would be any max number of entries if thats what you are asking. 

However if you are asking my opinion if this is security wise a good idea the answer would be no.  In my experience Rediret uris should always match **Exactly** where you are sending to including port even overloading the validator is not something i would do lightly.  IDs4 is extremely configurable and lets you do what you think is right for your application so in the end the decision is yours.

I am wondering why you have an application thats running on random ports cant you just set that up to run on a static port?  Security wise it would probably be the safer option.

**Comment by iconics-milan** [comment]
Thanks for the link @LindaLawton. It informed me about the existence of an IRedirectUriValidator, which will be perfect for this task. IDs4 is indeed flexible.

As for the reasons: we have a WPF application that we want to integrate with OIDC, and it will open a temporary local http server on a random port to receive the OIDC server response, exactly as described in the RFC section. Especially this sentence there:
`The authorization server MUST allow any port to be specified at the time of the request for loopback IP redirect URIs`

**Comment by iconics-milan** [comment]
Even better, this is already supported (and documented): AddAppAuthRedirectUriValidator

**Comment by LindaLawton** [comment]
I already printed your RFC i havent used this auth method before.   Good luck with your project.
