### ISSUE TITLE
Allow logging unhandled exception to be configurable

### ISSUE THREAD

**Issue by iwomm** [IdentityServer/IdentityServer4#3155]
First of all, thank you for an awesome project!

I use IdSrv4 to build my token service. I have my own exception handling middleware sitting in front of IdSrv4 to catch exceptions. This middleware maps a known exception to proper HTTP response, and the middleware also logs the exception. The known exceptions are from a custom exception set that I built. For example, my implementation of IResourceOwnerPasswordValidator may throw custom validation exceptions, which will be caught by my exception handling middleware, and this exception is mapped to 400 Bad Request response,  and the exception is logged by my middleware at the Warning level (since it's not a critical issue for the server).

The issue is the method IdentityServerMiddleware.Invoke() always logs exceptions that it caught as unknown exceptions at the Critical level. This creates false alarms in my server's logs.

A possible solution is having a default event handler for UnhandledExceptionEvent, where the exception is logged at the Critical level, and allow users to replace the event handler with their own implementation.

**Comment by leastprivilege** [comment]
tracked here

https://github.com/IdentityServer/IdentityServer4/issues/3518
