### ISSUE TITLE
Consent prompt always when including offline_access

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#3157]
### Issue / Steps to reproduce the problem

I am seeing something in my identity server and i am not sure if this is working as intended or if i have a setup issue in my identity server / client.    When using a hybrid client sending offline_access scope.   The user is presented with the consent screen every time they login not just the first time.  If i remove the offline_access  they are not presented with the consent screen.

My experience with other identity servers (Google) a user will only be presented with this consent screen once and then never again unless they remove consent.   

I have checked the documentation and can find no information on how you have implemented offline_access.     

Should the identity server be prompting for user consent to the application every time you send offline_access?

If "yes" is this something that can be configured with the exception of turning off consent competently on the client.

If "no" I am going to assume there is something wrong with my implementation of the identity server and start digging in the code.

### code

    /**
     * getAuthenticationUrl  builds url to authenticate to identity server 4
     *
     * @param string $nonce nonce
     * @return string URL used for authentication
     */
    public function getAuthenticationUrl($nonce = 'stuff')
    {
        $parameters = array(
            'response_type' => 'code id_token',
            'client_id'     => $this->client_id,
            'redirect_uri'  => $this->redirectUri,
            'nonce' => $nonce,                                                                 			
            'response_mode' => 'form_post',
            'scope' => $this->prepareScopes()   
        );
        return $this->authenticationEndpoint . '?' . http_build_query($parameters, null, '&');
    }

**Comment by brockallen** [comment]
The spec says to: https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

**Comment by LindaLawton** [comment]
Yes i saw that.    So i guess the reason would be that every time you request a refresh token you must consent to that every time.

Rather then just assuming because the user consented to these scopes for that application once six months ago they must remember that and there for not requesting access again.

Thank for the clarification.
