### ISSUE TITLE
Restrict API based on Grant Types

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3159]
Hi,

I have two controller. I wanted to restrict the access to API based on Grant Types.

1. Controller one can be accessed using access token which requested using Client Credential Grant.
2. Controller one can be accessed using access token which requested using Client Authorization Code Grant.

Can you please assist us, how can we achieved the above scenario in identityserver4?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
