### ISSUE TITLE
Katana/AspNetCore integration tests

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#316]
AspNetCore IdSrv to Katana Web API
Katana IdSrv to AspNetCore Web API

**Comment by leastprivilege** [comment]
IS4 emits a x5t in addition to kid for backwards compat with Wilson v4
and
e.g. https://github.com/IdentityServer/IdentityServer3/issues/3040

**Comment by leastprivilege** [comment]
Maybe we need to do that as a new repo that has both is3/4 with Katana/Core APIs and exercise a couple of combinations.

**Comment by brockallen** [comment]
done in new repo
