### ISSUE TITLE
PersistedGrants missing index on Expiration column

### ISSUE THREAD

**Issue by chrklin** [IdentityServer/IdentityServer4#3160]
### Issue / Steps to reproduce the problem
According to [DOC](http://docs.identityserver.io/en/latest/reference/ef.html#operationalstoreoptions) you can enable periodically cleanup of PersistedGrants.

But when looking at the class `TokenCleanup` we can see that it has a where clause on `Expiration` which does not have an index and the result will be a full table scan
[Source Code Link](https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/EntityFramework.Storage/src/TokenCleanup/TokenCleanup.cs#L136)

**Comment by brockallen** [comment]
Would changing this:

```
grant.HasIndex(x => new { x.SubjectId, x.ClientId, x.Type });
```

to this:

```
grant.HasIndex(x => new { x.SubjectId, x.ClientId, x.Type, x.Expiration });
```

be sufficient? In the past I've been told that adding a new index isn't that worthwhile, so just adding tot he existing one is sufficient.

**Comment by brockallen** [comment]
Also, this leads me to think we need this on the device table as well, and should add the device codes to the token cleanup too. // @scottbrady91

**Comment by scottbrady91** [comment]
Check out PR #3200 for cleanup. Agreed on the expiration

**Comment by brockallen** [comment]
Ok, i just went and tested with that index change and it seems like it's will use the index:

![image](https://user-images.githubusercontent.com/649492/56967604-888ba980-6b2f-11e9-9093-059aa3878945.png)

So I'll make those changes.

**Comment by brockallen** [comment]
Done.

**Comment by chrklin** [comment]
Hi @brockallen sorry i didn't follow. I am testing it now. And I can see that you added the index last into an existing index, this will not have the desired effect. 
As shown in your screen shot, it is in fact not using the index, it is doing a full table scan or full Clustered index scan on the primary key.
It is not using the index created with the Expiration Column.

**Comment by brockallen** [comment]
I added this in our 3.0 release.

**Comment by voroninp** [comment]
Is there any special purpose of selecting all the expired rows instead of just emitting raw sql to delete expired entries thus bypassing all EF's pipeline?

**Comment by brockallen** [comment]
Because we don't know what DB provider you're using. EF helps abstract that.

**Comment by voroninp** [comment]
Ok, then this feature should be requested on their side.

**Comment by brockallen** [comment]
Looks like this has been fixed already. Closing.
