### ISSUE TITLE
Multiple front-channel logout URI's per client (feature request)

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4#3166]
It would be great if IdServer could handle multiple front-channel logout URI's, it already handles multiple ClientRedirectUris/ClientPostLogoutRedirectUris so it would make sense to allow multiple logout URI's. 

I appreciate back-channel can be a solution to this but it is a lot of extra effort to implement.

**Comment by leastprivilege** [comment]
Unfortunately the spec isn't written that way.

https://openid.net/specs/openid-connect-frontchannel-1_0.html
