### ISSUE TITLE
Left out the markdown for code in documentation.

### ISSUE THREAD

**Issue by kevingates** [IdentityServer/IdentityServer4#3170]
### Issue / Steps to reproduce the problem
1. Go to this page and section: https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html#creating-the-client
2. You will see this sentence:
>Then as before, add it to your solution using:
>     cd .. dotnet sln add .srcClientClient.csproj

Instead, it should be the following with the proper markup for displaying:
```
cd ..
dotnet sln add .\src\Client\Client.csproj
```

**Comment by LindaLawton** [comment]
Glad to see i am not the only one that reads the documentation.  Well spotted

**Comment by brockallen** [comment]
merged, thanks for spotting that
