### ISSUE TITLE
JWT access token - iss claim with port

### ISSUE THREAD

**Issue by piotrekbigu** [IdentityServer/IdentityServer4#3171]
Hi,
During my current project I have to setup identity server in the cloud in docker based manner.
My use case looks like below:
- Mobile client calls API Gateway under url https://my.cloud.idp (default port 443 is used)
- API Gateway forwards request to Load Balancer at https://my.cloud.docker.idp:15001 address
- Load Balancer Forwards request to chosen container (many instances are involved)

With this scenario I faced two problems:
- discovery endpoint is built in incorrect way as the request host details are built using load balancer uri. I managed to fix in by intercepting some default and custom headers and building custom DiscoveryEndpoint implementation using it
- iss clam in JWT access token is built using url without port (GetIdentityServerHost extension method) so the default port assumed from schema is used instead of 15001. Due to this fact using iss claim inside the Virtual Private Cloud leads to nowhere

For the second issue the only option which I found is to set it at configuration options level but I would like to avoid such thing in favour of http context based url building.

So finally my question is why the framework ommits the port? Is there an option to do it using current implementation or add such logic?

**Comment by scottbrady91** [comment]
Sounds like you are after the `IssuerUri` or `PublicOrigin` setting http://docs.identityserver.io/en/latest/reference/options.html#identityserver-options

**Comment by piotrekbigu** [comment]
> 
> 
> Sounds like you are after the `IssuerUri` or `PublicOrigin` setting http://docs.identityserver.io/en/latest/reference/options.html#identityserver-options

@scottbrady91 
Yeah, I found it but as I said I am searching for solution which does not involve configuration settings.

**Comment by brockallen** [comment]
The issuer value is derived from the incoming HTTP request, and without configuration we don't know anything about your load balancer.

**Comment by piotrekbigu** [comment]
@brockallen 
Yeas I know - I have studied source code very deeply.

My problem results from fact that method **GetIdentityServerHost** intercepts only sheme and host without the port. Usually it is not a problem because API is served at default ports.

In case of custom ports, which in case of NLB are very common scenario, additional headers are added to request:
- X-Forwarded-Proto
- X-Forwarded-Port

What do you think about conditional intercepting of this information based on these headers presence?
If it is acceptable approach I can submit PR.

**Comment by brockallen** [comment]
Check the archives -- I think this sort of thing has already been well hashed out previously.

Also, you can always set the `PublicOrigin` on our options:

![image](https://user-images.githubusercontent.com/649492/56867573-a4b70b80-69b4-11e9-96b9-7c7e8bc73d1d.png)

and it works:

![image](https://user-images.githubusercontent.com/649492/56867575-ad0f4680-69b4-11e9-943f-373476468d70.png)

**Comment by scottbrady91** [comment]
Those headers are also supported by ASP.NET Core: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2#forwarded-headers

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
