### ISSUE TITLE
Microsoft.IdentityModel.Tokens 5.4.0 changes kid value when using X509SecurityKey

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4#3172]
`Microsoft.IdentityModel.Tokens` version 5.4.0 adds support for `x5t` to JWTs when using an `X509SecurityKey`. However, this also changes the `kid` value in generated tokens and the `kid` value in IdentityServer's discovery document.

See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1084

### Issue / Steps to reproduce the problem
1. Use x509 signing cert
2. Check `kid` value in discovery document
3. Update `Microsoft.IdentityModel.Tokens` to 5.4.0
4. Check `kid` value in discovery document

**Comment by leastprivilege** [comment]
nice...

**Comment by scottbrady91** [comment]
Just spotted: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1108

**Comment by brockallen** [comment]
So this is a breaking change if there's a version mismatch for them? Is there an action item for us?

**Comment by leastprivilege** [comment]
it's a shit show as usual ;)
