### ISSUE TITLE
Add option AllowCredentials in CorsPolicyProvider

### ISSUE THREAD

**Issue by Koenyn** [IdentityServer/IdentityServer4#3174]
I'm using isomorphic-fetch from a react app to hit the userinfo endpoint.

When making a GET request to the userinfo endpoint I am receiving the following message:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://MyIdentityServer.com/connect/userinfo. (Reason: expected ‘true’ in CORS header ‘Access-Control-Allow-Credentials’)

This can be fixed in the CorsPolicyProvider.Allow() by adding AllowCredentials() option.

This would makes sense as the request to the userinfo endpoint does have an authorization header.

**Comment by brockallen** [comment]
The allow credentials flag in CORS is for the browser sent credentials such as a cookie or a kerberos ticket, not an access token sent via the authorization header. So I don't see how this request applies for the userinfo endpoint.

**Comment by Koenyn** [comment]
If you look at the [Mozilla documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials) you will see that Access-Control-Allow-Credentials is used for **cookies, authorization headers or TLS client certificates.**

**Comment by brockallen** [comment]
Yes, and all of those are credentials that browser has collected. Passing a bearer token via the authorize header does not require ACAC, just the ACAH for Authorize on the preflight response.
