### ISSUE TITLE
Get reference token from the Identity API

### ISSUE THREAD

**Issue by gabrielrenom** [IdentityServer/IdentityServer4#3175]
Hi ,

We are trying to **automatise** tests with Soap UI or Postman for a **REST Api**. We are looking the way to get the **reference token** from the Identity API and use it in an API. Is there any way or **feature** that can provide this functionality by using clients such us Fiddler, SoapUI or Postman?

Cheers

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
