### ISSUE TITLE
Make StringsExtensions.cs public

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#3177]
**Is your feature request related to a problem? Please describe.**

I am trying to add some tests for my consent screen basically I have something on my consent screen that I need to test for that wouldn't be on your standard consent screen.  I thought to make my life easier i would just clone your consent tests 

[ConsentTests.cs](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/test/IdentityServer.IntegrationTests/Endpoints/Authorize/ConsentTests.cs)  So far so good.  However when i go to copy your IdentityServerPipeline.cs i run into an issue on  [#L155](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/test/IdentityServer.IntegrationTests/Common/IdentityServerPipeline.cs#L155)

     Constants.UIConstants.DefaultRoutePaths.Error.EnsureLeadingSlash()

A bit of digging and it turns out this extension class is internal  [StringsExtensions.cs](https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/IdentityServer4/src/Extensions/StringsExtensions.cs#L17)

I guess the same goes for [Constants.cs#L12](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Constants.cs#L12)

Which means i am not going to be able to access it in my test project.

**Describe the solution you'd like**

- Could these be set to public?  
- Is it worth setting them public? 
- Would there be any issues in setting them public?

**Describe alternatives you've considered**

I am just going to copy the extension class and constants put it in my unit test project.

**Additional context**

Thanks for having awesome tests that i can copy as a starting point.

**Comment by leastprivilege** [comment]
These are internal helpers that we use - we want to be able to change/refactor them anytime we want. Making the public makes that harder.
