### ISSUE TITLE
How to remove Reference Tokens from IDP?

### ISSUE THREAD

**Issue by OmidRafiee** [IdentityServer/IdentityServer4#3180]
I have  used   TokenRevocationClient for removing  but unfortunately, it fails to complete successfully
for example
I implemented the revokeTokens method, but after logging on its different in both browsers, still after leaving ،one of the browsers has  the valid entree‌
Both RevokeAccessTokenAsync and RevokeRefreshTokenAsync methods have been successfully implemented.
![Untitled](https://user-images.githubusercontent.com/25098596/55779296-4df79980-5aba-11e9-8e07-28f179a3fbd8.png)

**Client Config:**
"clientType": 0,
"absoluteRefreshTokenLifetime": 2592000,
"accessTokenLifetime": 3600,
"consentLifetime": null,
"accessTokenType":Refrence,
"allowAccessTokensViaBrowser": false,
"allowOfflineAccess": true,
"allowPlainTextPkce": false,
"allowRememberConsent": true,
"alwaysIncludeUserClaimsInIdToken": true,
"alwaysSendClientClaims": false,
"authorizationCodeLifetime": 300,
"frontChannelLogoutUri": null,
"frontChannelLogoutSessionRequired": true,
"backChannelLogoutUri": null,
"backChannelLogoutSessionRequired": true,
"clientId": "mvc",
"clientName":"Test",
"clientUri": null,
"description": null,
"enabled": true,
"enableLocalLogin": true,
"id": 3,
"identityTokenLifetime": 300,
"includeJwtId": false,
"logoUri": null,
"clientClaimsPrefix": "client_",
"pairWiseSubjectSalt": null,
"protocolType": "oidc",
"refreshTokenExpiration": 1,
"refreshTokenUsage": OneTimeOnly ,
"slidingRefreshTokenLifetime": 1296000,
"requireClientSecret": true,
"requireConsent": false,
"requirePkce": false,
"updateAccessTokenClaimsOnRefresh": true,
"postLogoutRedirectUris": [
"http://localhost:5002/",
"http://localhost:5002/signout-callback-oidc"
],
"postLogoutRedirectUrisItems": null,
"identityProviderRestrictions": [

],
"identityProviderRestrictionsItems": null,
"redirectUris": [
"http://localhost:5002/signin-oidc",
"http://localhost:37295/signin-oidc",
"http://localhost:5002",
"http://localhost:37295/"
],
"redirectUrisItems": null,
"allowedCorsOrigins": [

],
"allowedCorsOriginsItems": null,
"allowedGrantTypes": [
"hybrid"
],
"allowedGrantTypesItems": null,
"allowedScopes": [
"account",
"offline_access",
"profile",
"openid"
]

**Comment by brockallen** [comment]
Your client can either use the revocation endpoint to remove them on behalf of the user. But if you want an admin style mechanism, then you'd need to connect to your database (or where ever you're storing them) and delete them.

**Comment by OmidRafiee** [comment]
Yes, I want to implement the admin removal mechanism.
After logout the system, I call the revokeTokens method and delete the IDP list.
 (I store the client information in the SQL database)
However, if the user login at the same time on the two clients, after exiting, it is expected that the client will be invalid and will be redirected to the login screen. 
That‌‌‌ does not happen

**Comment by brockallen** [comment]
> However, if the user login at the same time on the two clients, after exiting, it is expected that the client will be invalid and will be redirected to the login screen.
> That‌‌‌ does not happen

I'm sorry, I'm not following.
