### ISSUE TITLE
Do I have to host a login UI within my identity server?

### ISSUE THREAD

**Issue by julipur** [IdentityServer/IdentityServer4#3181]
Hi, 

I have a SPA scenario. I want my login UI to live within my SPA which will be hosted somewhere other than Identity Server. All I want on the Identity Server side is an API end point that takes the username/password. The SPA UI will take the username/password and send it to that end point. I want to be able to pass back auth token to the SPA application from identity server. 

I am not finding clear cut instructions to do this anywhere in the docs. I think the recommended approach is PKCE with Authorization code flow. However how can I achieve that without UI/cookies on the identity server?

Am I way off in trying to implement this like so?

**Comment by leastprivilege** [comment]
You can't. You are looking for resource owner flow

https://github.com/IdentityServer/IdentityServer4.Samples/blob/master/Clients/src/ConsoleResourceOwnerFlow/Program.cs

**Comment by julipur** [comment]
Thanks Dominick.

**Comment by julipur** [comment]
For those who are tempted to go with this flow, seems like this is not the right approach. 

https://www.scottbrady91.com/OAuth/Why-the-Resource-Owner-Password-Credentials-Grant-Type-is-not-Authentication-nor-Suitable-for-Modern-Applications

Especially, this sentence got stuck with me 

"No. It is not okay to use this grant type because you want to keep the login screen in your application so that you can style it. There are valid “security reasons” against using this grant type, don’t let anyone convince you to do otherwise for the sake of UX"

**Comment by leastprivilege** [comment]
Well- if you want to keep your login UI inside you application, this is the only option you have. That's what you asked for.

**Comment by julipur** [comment]
Yes, I did. :)

What I have understood though is, that designing like that is not the right (or recommended approach). It seems to me like a "just cause I can do it, doesn't mean I should".
