### ISSUE TITLE
Use non-case sensitive string for any keys in persisted grants

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#3184]
If key is stored in non-case sensitive DB then might be collisions.

**Comment by brockallen** [comment]
From what I can tell, this is already being done since we use `CryptoRandom.CreateUniqueId` which in turns uses `ByteArrayToString` which emits the hex encoded values of the bytes (which of course is not case sensitive).

**Comment by brockallen** [comment]
Ok, I was wrong... `CryptoRandom.CreateUniqueId` defaults to base64url encoding. We need to change it everywhere to pass `CryptoRandom.CreateUniqueId(format: CryptoRandom.OutputFormat.Hex)`.

**Comment by leastprivilege** [comment]
Yes - we also should make sure we use the handle generation service everywhere?
