### ISSUE TITLE
Achieving SaaS Multitenancy with controlled/governed SSO

### ISSUE THREAD

**Issue by tiwari-abhishek** [IdentityServer/IdentityServer4#3185]
I need feedback/comments/suggestions on the possibility of building a Multitenant SaaS solution using IdentityServer4, which would consist of the following:

- A single Identity Server as central token service
- Multiple Tenants
- Multiple applications per tenant
- Prevent SSO between Tenants
- Control SSO within a Tenant. I would like to have control over when and which apps within a tenant can have SSO. E.g. prevent SSO between a User app and its corresponding Admin app, but probably allow SSO with other user apps in that tenant, since the upstream IdP would be same for that Tenant.

The last 2 points are my concern. 

**Questions:**
1. Would it be enough to run tenants under different domains in order to prevent SSO across tenants (I guess browser and cookies would take care of this)?
2. Within a Tenant, is it possible to have a SSO policy that can be validated against to see if SSO should be allowed?

Any thoughts? Has anyone done this before?

**Comment by leastprivilege** [comment]
Yes - this is possible. You can attach tenant information to the client config and use the extensibility points around the authorize endpoint to prevent accidental SSO. You can also use multiple domains and use cookies as and additional mechanism.
