### ISSUE TITLE
AWS Lambda deployment - query parameter issue

### ISSUE THREAD

**Issue by MauricioArroyo** [IdentityServer/IdentityServer4#3186]
Hi,

I have a question related to IdSrv4 running on AWS lambda. The issue happens only on AWS, locally it works fine so it doesn't seem to be a IdSrv4 issue, but maybe someone has an idea on what to check.
 
When our MVC app tries to authenticate with the IdSrv, we can see the Login page and the Url with a query string ReturnUrl with a value (including the nonce) encoded (for instance & are %26), but once the IdSrv Login action is called, the ReturnUrl parameter only has the first part of the query string. The AWS seems to be decoding the query string, and so, only part of it is getting to the action...

If we add a new parameter (let's say nonce) to the Login action, then we get the nonce, so the parameters are there, split, not as part of the returnurl param.

We get an error, but the authentication works, if we just refresh, the cookie was created and we are able to login in our app.

In some AWS forums they recommend to encode the url data in base64, but we don't want to mess with IdSrv coding unless it's absolutely necessary to have a custom build.

Has somebody seen this behavior before? Any help will be really appreciated!

**Comment by brockallen** [comment]
Any update?

**Comment by leastprivilege** [comment]
i have never used Lambda. Maybe @damianh can help?

**Comment by MauricioArroyo** [comment]
We created an action filter and get the raw returnUrl as a workaround. We were not able to make it work "out of the box". 
Thanks as always for your help!

**Comment by fredmararac** [comment]
Hi @MauricioArroyo, 

Have you successfully deploy an IdSvr in AWS Lambda? Did you use aspnet core? Do you have public repo? I am interested in deploying the same architecture.

Thanks!

**Comment by MauricioArroyo** [comment]
Hey @fredmararac,
Yes, we did. The only issue we had was with the return Url and we created a custom filter to access it and put it back. Maybe the new versions work out of the box, I haven' tried. But if they don't let me know and I can share our fix with you.

Regards,
