### ISSUE TITLE
Windows AD authentication and login screen

### ISSUE THREAD

**Issue by sowsan** [IdentityServer/IdentityServer4#3194]
Configured the IdentityServer as per the documentation here , http://docs.identityserver.io/en/latest/topics/windows.html

Trying with asp.net mvc web client. Not seeing any button for windows authentication? Am I expected to see a button in the external authentication in http://localhost:5000/Account/Login?

**Comment by leastprivilege** [comment]
Yes it should appear automatically if you are using our sample UI - 

> Also the virtual directory in IIS (or IIS Express) must have Windows and anonymous authentication enabled.

**Comment by BBanoth** [comment]
@sowsan : If you are using .Net Core 2.2, the default Kestrel server is replaced with IISHttpServer. Use the following code and run your project with IISExpress

services.Configure<**IISServerOptions**>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });
