### ISSUE TITLE
TokenIssuedSuccessEvent should contain Claims to be present in logs

### ISSUE THREAD

**Issue by cerginio** [IdentityServer/IdentityServer4#3199]
**Is your feature request related to a problem? Please describe.**

Production support for cases with external provider authentication require logs drill down using search authentication tokens by claims - including technical oidc jwt claims. 
We are using Splunk and Azure AppInsights.
Token payload (claims) in logs for "2001 token issued" events helps us a lot with customer incidents troubleshooting in production. 

**Describe the solution you'd like**

I suggest to include Claims property into TokenIssuedSuccessEvent and put token payload there.
**Claims = token.Claims.ToClaimsDictionary()**

Token payload logging was gracefully implemented for IdentityServer3:
[https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/IEventServiceExtensions.cs](url)
```evt.DetailsFunc = () => new AccessTokenIssuedDetails
            {
                SubjectId = token.SubjectId ?? "no subject id",
                ClientId = token.ClientId,
                TokenType = token.Client.AccessTokenType,
                Lifetime = token.Lifetime,
                Scopes = token.Scopes,
                Claims = token.Claims.ToClaimsDictionary(),
                ReferenceTokenHandle = referenceTokenHandle
            };
```

**Describe alternatives you've considered**
Alternative semi-solution we found, but unfortunately, this approach missing technical jwt claims: f.e nonce, jti, at_hash.

```
IEventSynk.PersistAsync(Event evt) =>
if (evt is TokenIssuedSuccessEvent)
            {
                var claims = _accessor.HttpContext.User?.Claims.ToClaimsDictionary();

                _logger.LogInformation
                ("{EventId},{EventName},{EventCategory},{EventType},{@Claims},{@Details}",
                    evt.Id,
                    evt.Name,
                    evt.Category,
                    evt.EventType,
                    claims,
                    evt);

                return Task.CompletedTask;
            }
```

**Additional context**
Wondering what was the reason to remove such functionality from Ids4.
If there were some security wise reasons, I would point to a more insecure place where the attacker could decrease logging level to Trace and get valid signed tokens from logs.

[https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Endpoints/AuthorizeEndpointBase.cs](url)

```
private void LogTokens(AuthorizeResponse response)
        {
            var clientId = $"{response.Request.ClientId} ({response.Request.Client.ClientName ?? "no name set"})";
            var subjectId = response.Request.Subject.GetSubjectId();

            if (response.IdentityToken != null)
            {
                Logger.LogTrace("Identity token issued for {clientId} / {subjectId}: {token}", clientId, subjectId, response.IdentityToken);
            }
            if (response.Code != null)
            {
                Logger.LogTrace("Code issued for {clientId} / {subjectId}: {token}", clientId, subjectId, response.Code);
            }
            if (response.AccessToken != null)
            {
                Logger.LogTrace("Access token issued for {clientId} / {subjectId}: {token}", clientId, subjectId, response.AccessToken);
            }
        }
```

**Comment by brockallen** [comment]
Would there be PII issues in doing this? I think I have several customers that would only want this opt-in.

**Comment by TomCJones** [comment]
There certainly are PII issues, but i always assumed that that logging was turned off in production. Do some of you leave it on? If so we might need more logging categories. Specifically PII data contained.

**Comment by leastprivilege** [comment]
Tracked here

https://github.com/IdentityServer/IdentityServer4/issues/3518
