### ISSUE TITLE
Videos are missing.

### ISSUE THREAD

**Issue by kevingates** [IdentityServer/IdentityServer4#3203]
### Issue / Steps to reproduce the problem
1. Go to this page: https://identityserver4.readthedocs.io/en/latest/misc/videos.html
2. Under 2019 section, both videos have been removed:
January [NDC] – Securing Web Applications and APIs with ASP.NET Core 2.2 and 3.0
January [NDC] – Building Clients for OpenID Connect/OAuth 2-based Systems

##### Option 1 (Preferred)
Re-upload videos and update links as needed.

##### Option 2
Delete 2019 section until videos are available.

**Comment by leastprivilege** [comment]
thanks
