### ISSUE TITLE
Small dependency issue in 3.0.0-preview3.4 IdentityServer4.Storage NuGet package

### ISSUE THREAD

**Issue by D3MaxT** [IdentityServer/IdentityServer4#3204]
### Issue / Steps to reproduce the problem
Update the IS4 NuGet packages to 3.0.0-preview3.4 versions.

### Result
A warning shows up in VS2019 (mostly cosmetic, everything still works though):
IDentityServer4.EntityFramework.Storage 3.0.0-preview3.4 depends on IdentityServer4.Storage(>=3.0.0-preview3.2) but IdentityServer4.Storage-preview3.2 was not found. An approximate best match of IdentityServer4.Storage-preview3.4 was resolved.

Cosmetic mostly, since the right version is still selected in the end, but I have OCD. :p

Thank you.
![IS4warning](https://user-images.githubusercontent.com/24484920/56398316-78a9c680-620d-11e9-8a9c-8b9248bb0722.jpg)

**Comment by leastprivilege** [comment]
OK - thanks. Will need to investigate why this happened.
