### ISSUE TITLE
How to custom client Identity server4

### ISSUE THREAD

**Issue by nguyenthequyen** [IdentityServer/IdentityServer4#3206]
How to custom "Client" Identity server4, add properties EnablePasswordles?

**Comment by danlavrushko** [comment]
@nguyenthequyen check out `Client.RequireClientSecret` property https://identityserver4.readthedocs.io/en/latest/reference/client.html.

btw this type of questions are better to ask at Stask Overflow with tag [identityserver4](https://stackoverflow.com/questions/tagged/identityserver4)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
