### ISSUE TITLE
Single Signin between MVC & SPA

### ISSUE THREAD

**Issue by maganuk** [IdentityServer/IdentityServer4#3207]
I have a functional Identity Server, a MVC app using Hybrid Flow and a React SPA using Authorization Code Flow (using oidc-client). 

Both the apps are work fine with Identity Server, however when a user logs into the SPA and after being authorized visits the MVC app, the user still shows as being not logged in. He needs to click on the Login button upon which he is redirected to the IDS and then redirected back to the MVC app (not asked for credentials - which is fine). 

Is it expected behavior for the MVC app to not know that the user has already logged into the Identity Server? If not, what could I be doing wrong?

If it is expected behavior, does Identity Server support back channel login which I can use to check if the user is logged in and generate a claims principal?

I've already implemented a back channel logout which seems to be working fine.

Thanks
Vishal

**Comment by maganuk** [comment]
I did some more reading and it seems this is normal behaviour since the client itself needs to be authenticated. Which brings me to the second point. How does something like you tube know when you've logged into Gmail that the user is logged in.

Will opening up a check session iframe help to determine if that the OP has a valid login?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
