### ISSUE TITLE
Moving grant logging to Debug

### ISSUE THREAD

**Issue by jrutley** [IdentityServer/IdentityServer4#3208]
Can we bump the line 
`_logger.LogInformation("Removing {grantCount} grants", found);` in TokenCleanup.cs down to Debug?

Our log is full of these, and we don't want to turn off Info

**Comment by LindaLawton** [comment]
@brockallen Happy to do it if you approve it.

**Comment by brockallen** [comment]
Yes, that looks like it. I don't know if there's other related log messages that also are related that could use review.

**Comment by LindaLawton** [comment]
In my experience the term `"use review"` is a loaded statement that results in a lot of time and effort.

**Comment by brockallen** [comment]
Sure :) Just while you're in there, look for any others that might also make sense to move to debug level.

**Comment by LindaLawton** [comment]
What your going to let me use my judgment!

**Comment by LindaLawton** [comment]
[TokenCleanup.cs#L161](https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/EntityFramework.Storage/src/TokenCleanup/TokenCleanup.cs#L161) should maybe be error?

**Comment by brockallen** [comment]
> TokenCleanup.cs#L161 should maybe be error?

I think this happens often if they have multiple instances running at same time. So i think of it more as debug/info. If it's an error, it will show up often.

**Comment by LindaLawton** [comment]
Ping to close this as it has been merged
