### ISSUE TITLE
Multitenancy, Identity tables per tenant

### ISSUE THREAD

**Issue by Oxoproline** [IdentityServer/IdentityServer4#3209]
### Question / Steps to reproduce the problem
Hi, we are currently building multitenant app. We want to have one app with general configDB and multiple Tenant DBs. We are getting tenant info based on http context, so we write our own connection string provider.

We would like to have Identity tables per tenant. But we struggle with setting Identity server correctly.

we used this previously when we didn't need multitenancy and we had only one DB per APP
```
.AddConfigurationStore(options =>
                {
                    options.DefaultSchema = Schemas.Identity;
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionStringProvider.DbConnectionString,
                            sqlOptions => sqlOptions.MigrationsAssembly(migrationsAssembly));
                })
                .AddOperationalStore(options =>
                {
                    options.DefaultSchema = Schemas.Identity;
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(connectionStringProvider.DbConnectionString,
                            sqlOptions => sqlOptions.MigrationsAssembly(migrationsAssembly));
                });
```
to setup Identity server. Now It works only if we use our common ConfigDB. But we would like to have users stored in tenant DBs.

So now after call to:
```
app.UseIdentityServer()
```
there is call to options.ConfigureDbContext which tries to set Db context, but at this point we don't have http context info thus we can't provide correct tenant connection string. 

So Question basically is: How to setup multiple Configuration and Operational stores one per each tenant and how to do initial setup with identity server ?

Any hint will be highly appreciated :)

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
