### ISSUE TITLE
Windows Authentication and Local Login hybrid flow

### ISSUE THREAD

**Issue by rodmanb2** [IdentityServer/IdentityServer4#3210]
Hi,
I'm trying to implement a hybrid flow where I verify a piece of information prior to Windows Authentication (SSO), and if the verification fails the browser is redirected back to the login screen for a Local Login flow. I'm building this on top of the [IdentityServer4.Quickstart.UI](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI) sample with a client that's initiazlied with `EnableLocalLogin = true`. 

I have the initial flow working but after being redirected to the login screen with the user/password form, the POST action eventually leads me to being redirected back to the initial Login route.

Can you think of anything I could be missing?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!

**Comment by rodmanb2** [comment]
Since there was a 'Question' option I assumed it was fine too.

Found the problem eventually, in my case my own code had a client with `EnableLocalLogin = false` and it caused IdentityServer4 to redirect me back, I wasn't expecting that behavior.
