### ISSUE TITLE
Consider adding support for CIBA

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3216]
"Client initiated Backchannel Authentication"

https://medium.com/@darutk/ciba-a-new-authentication-authorization-technology-in-2019-explained-by-an-implementer-d1e0ac1311b4

https://openid.net/specs/openid-connect-modrna-client-initiated-backchannel-authentication-1_0.html

**Comment by leastprivilege** [comment]
Looking for a sponsor. If your company needs that feature, let us know.

**Comment by jbfreymann** [comment]
working in healthcare in France. my company is interested in CIBA support for identity server 4. use cases are involving patient in order to grant access for practitionner.

**Comment by leastprivilege** [comment]
we will not add CIBA to IdentityServer4 - it's a pretty big feature.

We are open to discuss this in the context of our new sustainable version of IdentityServer. Feel free to contact us!
https://duendesoftware.com/contact
