### ISSUE TITLE
Authorization taking above 1000 ms to validate access token IdentityServer4

### ISSUE THREAD

**Issue by UMANGAWASTHY** [IdentityServer/IdentityServer4#3217]
I am using IdentityServer4 with web app dotnet4.6.1 framework. I am using Authorize Attribute for user Authetication to access web api. This Authorization process taking above 1000ms.
With Authorize Attribute API call execution Time : 1200ms.
WithOut Authorize Attribute API call execution Time : 150ms.

Here My IdentityConfig code...

 public class Config
    {
        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            var customProfile = new IdentityResource(
              name: "custom.profile",
              displayName: "Custom profile",
              claimTypes: new[] { "role", "appId", "companyId", "partnerId"});

            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Email(),
                customProfile
            };
        }

        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource("appId", "My API"),
                new ApiResource("role", "My role"),
                new ApiResource("companyId", "My companyid"),
                new ApiResource("partnerId", "My partnerid"),
           };
        }
        public static IEnumerable<Client> GetClients()
        {
            return new List<Client>
            {
                new Client
                {
                      ClientId = "MyClient",
                      ClientName = "MyClient"
                      AllowedGrantTypes = GrantTypes.ImplicitAndClientCredentials,
                      RequireConsent = false,
                      ClientSecrets =
                      {
                       new Secret("secret".Sha256())
                      },
                      RedirectUris = {
                        "http://localhost:37048/callback.html",
                        "http://192.168.0.104/admin.microdev/callback.html"
                        "https://192.168.0.104/admin.microdev/callback.html"
                    },
                      PostLogoutRedirectUris = {
                        "http://localhost:37047/callback.html",
                        "http://192.168.0.104/admin.microdev/callback.html", 
                        "https://192.168.0.104/admin.microdev/callback.html",                         
                      },

                      AllowedScopes =
                      {
                       IdentityServerConstants.StandardScopes.OpenId,
                       IdentityServerConstants.StandardScopes.Profile,
                       "role",
                       "appId",
                       "companyId",
                       "partnerId",
                       "custom.profile",
                       IdentityServerConstants.StandardScopes.Address,
                       IdentityServerConstants.StandardScopes.Email,
                      },
                      AllowedCorsOrigins={
                        "http://localhost:37047",
                        "http://192.168.0.104/admin.microdev",
                        "https://192.168.0.104/admin.microdev",
                        "http://localhost:37047/callback.html",
                        "http://192.168.0.104/admin.microdev/callback.html",
                        "https://192.168.0.104/admin.microdev/callback.html",
                      },
                      AllowAccessTokensViaBrowser=true,
                      AllowRememberConsent = true,
                      Enabled = true,
                      EnableLocalLogin = true,
                      AbsoluteRefreshTokenLifetime = 600,
                      AccessTokenLifetime = 3600,
                      AlwaysSendClientClaims = true,
                      AuthorizationCodeLifetime = 600,
                      IdentityTokenLifetime = 600,
                      RefreshTokenExpiration = 0,
                      RefreshTokenUsage = 0,
                      AccessTokenType = 0,
                }
            };
        }
    }

here my startup.cs code

  services.AddIdentity<ApplicationUser, IdentityRole>(options =>
  {             
                options.Tokens.ChangePhoneNumberTokenProvider = "Phone";
		options.Password.RequiredLength = 8;
		options.Password.RequiredUniqueChars = 0;
		options.Password.RequireDigit = false;
		options.Password.RequireLowercase = false;
		options.Password.RequireUppercase = false;
		options.Password.RequireNonAlphanumeric = false;
                })
		.AddEntityFrameworkStores<ApplicationDbContext>()
		.AddDefaultTokenProviders();
              var cert = new X509Certificate2(System.IO.File.ReadAllBytes("idsrv3test.pfx")
                                   , "idsrv3test"
                                   , X509KeyStorageFlags.MachineKeySet |
                                     X509KeyStorageFlags.PersistKeySet |
                                     X509KeyStorageFlags.Exportable);

                services.AddIdentityServer()
                .AddSigningCredential(cert)
				.AddInMemoryPersistedGrants()
				.AddInMemoryIdentityResources(Config.GetIdentityResources())
				.AddInMemoryApiResources(Config.GetApiResources())
				.AddInMemoryClients(Config.GetClients())
				.AddAspNetIdentity<ApplicationUser>();

        Here My Startup.cs code in WebAPP
        public void ConfigureAuth(IAppBuilder app)
        {
            var config = new HttpConfiguration();
            config.MapHttpAttributeRoutes();
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority= "http://localhost:5000",
                RequiredScopes = new[] { "role" },
                //DelayLoadMetadata = true,
            });
        }

To Authenticate Cross Version i am using below nuget dll's

IdentityServer3.AccessTokenValidation 2.14.0 
IdentityModel 1.13.1
Microsoft.Owin.Security 3.0.1
Microsoft.Owin.Security.OAuth 3.0.1
System.IdentityModel.Tokens.Jwt 4.0.2.206221351
Microsoft.IdentityModel.Protocol.Extensions 1.0.2.206221351 
Microsoft.Owin.Security.Jwt 3.0.1
Microsoft.AspNet.WebApi.Owin 5.2.3
Microsoft.Owin.Diagnostics 3.1.0
Microsoft.Owin.Host.SystemWeb 3.0.0

**Comment by leastprivilege** [comment]
Hard to say - IdentityServer is not involved in validating access tokens in the API...

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
