### ISSUE TITLE
RefreshToken is invalid in multiple instances

### ISSUE THREAD

**Issue by zhangzhanhong2** [IdentityServer/IdentityServer4#3218]
I have 3 ids4 instances, the instanceA can't authorize accesstoken when request with the refreshtoken from instanceB.
How can I solve this problem?
May I to persistence the reflesh token from every instance?

**Comment by LindaLawton** [comment]
In my experience it was an issue with the sessions on multiple instances.  assuming you are using the same certificate on all the insurances I can't see why the refresh tokens would be different.

you might want to consult [data protection](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.2)

**Comment by leastprivilege** [comment]
Have you set up a data store for your refresh tokens?

https://identityserver4.readthedocs.io/en/latest/topics/deployment.html

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
