### ISSUE TITLE
Booleans in MySQL and the OnModelCreating (ConfigurationDbContext)

### ISSUE THREAD

**Issue by gph2000** [IdentityServer/IdentityServer4#3223]
I am running IdentityServer4 in an authorization server by adding its Nuget Packages, but I am targetting MySql. 
I get coercison exceptions (Int16 vs Boolean) because MySql represents booleans as integers.

From what I gather, I need to add something like 
 ````
modelBuilder
                .Entity<Client>()
                .Property(c => c.AllowAccessTokensViaBrowser).HasConversion<Int16>()
            ;
````
to the  OnModelCreating but I don't know how to do it in such a way that the the Nuget packages will see it.

The Authorization Server I have created is a copy of its Identity Server counterpart in the Combined Example in the Identity Server documentation.

Other research has suggested using Pomelo as the MySql ORM but further enquiries indicate that it will have issues with Async Methods.

How should I resolve this?

**Comment by brockallen** [comment]
Try to derive from `ConfigurationDbContext` and override `OnModelCreating` to do your extra config. You'd need to then register your in DI rather than ours.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
