### ISSUE TITLE
Recompilation required for EF.Storage with latest AutoMapper 8.1.0 due to signature change

### ISSUE THREAD

**Issue by GeorgDangl** [IdentityServer/IdentityServer4#3227]
The call to `ConstructUsing` ([example usage in IdentityResourceMapperProfile](https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Mappers/IdentityResourceMapperProfile.cs#L25)) had it's signature changed between AutoMapper 8.0.0 to 8.1.0.

Signature in 8.0.0:

```csharp
public interface IMappingExpression<TSource, TDestination>
{
    IMappingExpression<TSource, TDestination> ConstructUsing(Expression<Func<TSource, TDestination>> ctor);
}
```

Signature in 8.1.0:

```csharp
public interface IMappingExpressionBase<TSource, TDestination, out TMappingExpression> where TMappingExpression : IMappingExpressionBase<TSource, TDestination, TMappingExpression>
{
    TMappingExpression ConstructUsing(Func<TSource, ResolutionContext, TDestination> ctor);
}
```

This is related to #2852. As far as I see, all that is required by IdentityServer4 is to recompile with AutoMapper 8.1.0.

I don't think this is critical right now, but I encountered the issue and wanted to log it.

**Comment by brockallen** [comment]
FML // @jbogard

**Comment by jbogard** [comment]
What I do

**Comment by brockallen** [comment]
> What I do

you breaky my codez

**Comment by jbogard** [comment]
Ohhhhh we consolidated to a base interface for that one. It still exists, it's just:

```c#
public interface IMappingExpressionBase {
    void ConstructUsing(Expression<Func<TSource, TDestination>> ctor);
}

public interface IMappingExpression<TSource, TDestination> : IMappingExpressionBase<TSource, TDestination, IMappingExpression<TSource, TDestination>>
```

**Comment by jbogard** [comment]
But yes....it seems it needs a re-compile. Just NuGet update and go

sorreeeeeeeee

**Comment by brockallen** [comment]
BREAKING CHANGE! FOR THE LOVE OF HUMANITY!

**Comment by brockallen** [comment]
done

**Comment by gingters** [comment]
Just ran into that issue too. Any idea when 2.5 will ship?
It's not urgent, just to have a rough guesstimate when we would need a bit of extra time to update packages (and double check for further breaking changes from AutoMapper… 😔).

**Comment by brockallen** [comment]
July :)
