### ISSUE TITLE
Xamarin.Forms app keep getting unauthorized 401 error message

### ISSUE THREAD

**Issue by hmheng** [IdentityServer/IdentityServer4#323]
Im trying to use httpclient accessing WebApi's secured API, it prompts me unauthorized 401. But for unsecured (without [Authorize] attribute in API controller class), it works perfectly fine.

I try using ASP.NET MVC client to access secured api, it seems fine.
Any idea to solve this?

**Comment by leastprivilege** [comment]
Check the logs? I guess this is not really an IdentityServer issue, right?
