### ISSUE TITLE
CORS issue when using trying to redirect to redirect_uri

### ISSUE THREAD

**Issue by DanielJamesSharp** [IdentityServer/IdentityServer4#3231]
Hello, i'm pretty new to IdentityServer and am trying to modify the quickstart code to use angular as the UI. I have managed to get it to work however it is blocking the redirection back to my frontend (Also in angular). I am using oidc-client on the frontend using a routeguard to trigger the login process. Once I login successfully, everything seems to work if I go back and trigger the auth guard again. Just the redirect seems to be not working, 
Thanks in advance for any help you may be able to provide.

IdentityServer4.Test.TestUserProfileService:Debug: IsActive called from: AuthorizeEndpoint
IdentityServer4.Services.DefaultConsentService:Debug: Client is configured to not require consent, no consent is required
IdentityServer4.ResponseHandling.AuthorizeResponseGenerator:Debug: Creating Implicit Flow response.
IdentityServer4.Services.DefaultClaimsService:Debug: Getting claims for access token for client: angular
IdentityServer4.Services.DefaultClaimsService:Debug: Getting claims for access token for subject: d860efca-22d9-47fd-8249-791ba61b07c7
IdentityServer4.Test.TestUserProfileService:Debug: Get profile called for subject d860efca-22d9-47fd-8249-791ba61b07c7 from client Image Gallery with claim types  via ClaimsProviderAccessToken
IdentityServer4.Test.TestUserProfileService:Debug: Issued claims: 
'dotnet.exe' (CoreCLR: clrhost): Loaded '.nuget\packages\system.identitymodel.tokens.jwt\5.2.4\lib\netstandard1.4\System.IdentityModel.Tokens.Jwt.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '.nuget\packages\microsoft.identitymodel.jsonwebtokens\5.2.4\lib\netstandard1.4\Microsoft.IdentityModel.JsonWebTokens.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.9\System.Text.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
IdentityServer4.Services.DefaultClaimsService:Debug: Getting claims for identity token for subject: d860efca-22d9-47fd-8249-791ba61b07c7 and client: angular
IdentityServer4.Services.DefaultClaimsService:Debug: In addition to an id_token, an access_token was requested. No claims other than sub are included in the id_token. To obtain more user claims, either use the user info endpoint or set AlwaysIncludeUserClaimsInIdToken on the client configuration.
IdentityServer4.Endpoints.AuthorizeCallbackEndpoint:Information: Authorize endpoint response
{
  "SubjectId": "d860efca-22d9-47fd-8249-791ba61b07c7",
  "ClientId": "angular",
  "RedirectUri": "http://localhost:4200/auth-callback",
  "State": "a817721e22584c9e803fa24d6653dbf1",
  "Scope": "openid profile"
}
IdentityServer4.Hosting.IdentityServerAuthenticationService:Debug: Augmenting SignInContext
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler:Information: AuthenticationScheme: Cookies signed in.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 233.6341ms 302 

Access to XMLHttpRequest at 'http://localhost:4200/auth-callback#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjBmOTUzNjJjZTI2MTA0OTRhZGZkMGRlYWM0MjQyYWNjIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTY0ODYyMDgsImV4cCI6MTU1NjQ4NjUwOCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzOTkiLCJhdWQiOiJhbmd1bGFyIiwibm9uY2UiOiI3YWE0OTE4ZWUwZmQ0OGEyOTRhYjRlMGE3Y2MwOTBlMSIsImlhdCI6MTU1NjQ4NjIwOCwiYXRfaGFzaCI6Ind2WGh3ZjRGbU9CampybGwwQXVoQmciLCJzaWQiOiI3MGRhY2JlMGE5OWI0YmUxMDlkMDAxNGZiNzU5ZTAyMSIsInN1YiI6ImQ4NjBlZmNhLTIyZDktNDdmZC04MjQ5LTc5MWJhNjFiMDdjNyIsImF1dGhfdGltZSI6MTU1NjQ4NjIwOCwiaWRwIjoibG9jYWwiLCJhbXIiOlsicHdkIl19.x_S7nfj02SNEkr7ajmnEv6tFS6G7UWtXqpXqeN9FszX2lsrmsmfXFlgThxA4xyGJe5uVzHqNBzqn12JdItEhjo1i4IZtmQDniqJMVWHD8YPeOdpKNDCtD4MfoYwtfZ9ZCDeNDK_SIBknF9g9FaeKNJwQFaTP0lpNezYHXkFyUmwLdACe9BrV0Z_98EcZV4Bx7f6MwMCeyi-nRVvKbvj5vvoR1RlRzk1-RB3QWuuCRLLt7nOtUPvO-dRHCRlumG6Lptd_tm9QelHYRj_yJibWnTrT-427C4df2q22_Rlo5I-mi-kj0SRLGs2yE97DErPmQU8AABZADt8YN77Uqn7HIA&access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjBmOTUzNjJjZTI2MTA0OTRhZGZkMGRlYWM0MjQyYWNjIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTY0ODYyMDgsImV4cCI6MTU1NjQ4OTgwOCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzOTkiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0NDM5OS9yZXNvdXJjZXMiLCJjbGllbnRfaWQiOiJhbmd1bGFyIiwic3ViIjoiZDg2MGVmY2EtMjJkOS00N2ZkLTgyNDktNzkxYmE2MWIwN2M3IiwiYXV0aF90aW1lIjoxNTU2NDg2MjA4LCJpZHAiOiJsb2NhbCIsInNjb3BlIjpbIm9wZW5pZCIsInByb2ZpbGUiXSwiYW1yIjpbInB3ZCJdfQ.d2eDf6BovSRKowVH3dKZgst4B1_yRnHFerZ7umaM56oXkDbicKePC6DRNOsjVEkZ5ZNUSoBqJsKLUIlVJqiyLSvgeMWiic_pWNusyXXblrHCIccChRExkvweJZGf98YQzU12FWnp58UaWiDyBaFB2giFTEo2ZNckvXrC8h7U5F5c_dcWsUX2FQ_ogcB9wM_FDb3diLreFvGBXbS2cMI8VnXIjSxBdIGPnclBdM_E8r5gLBqri21s-QViOZi2sa3vZHkojEFVSCE93EnlBXYq2xrjeEt8RnqMCIAAw3C4jmkFSsfBjB-kZ6uDV9z2I_lrhudoer-D2f4nKeV_pNdHeA&token_type=Bearer&expires_in=3600&scope=openid%20profile&state=a817721e22584c9e803fa24d6653dbf1&session_state=JJ7qvmOrWGPQUKo6BzEtEqJxwD2JquCWyzNi2yGRCIk.78549d75c766b6a3e5d0d5180c9b7f0c' (redirected from 'https://localhost:44399/account/login') from origin 'https://localhost:44399' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.
core.js:1448 ERROR HttpErrorResponse {headers: HttpHeaders, status: 0, statusText: "Unknown Error", url: null, ok: false, …}

**Comment by xyzblocks** [comment]
@DanielJamesSharp Hello,

In my case this issue was caused by the missing CORS headers on the request for the discovery document. To solve this, you can change the configuration of the OIDC Client or add the relevant CORS headers to ID Server.

**Comment by DanielJamesSharp** [comment]
Thanks for the reply,
I have CORS enabled within the ID Server. This CORS Issue only seems to arise with a SPA as the UI, when I connect to the quickstart, and then auth, it redirects perfectly back to the RedirectURI

**Comment by DanielJamesSharp** [comment]
Seems if I also copy the connect/authorize/callback and paste it in the url it actually does redirect correctly (http://localhost:57749/connect/authorize/callback?client_id=angular&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fauth-callback&response_type=id_token%20token&scope=openid%20profile%20api1&state=a45e34be04a54ce9abc8f5eea2eeec76&nonce=f5b85804ed67468d922c25c547b2da5a).

However, when using return Redirect(model.returnUrl) < contains the same link as above starting from /connect, it throws the CORS error as mentioned.
Any help would be greatly appreciated, thanks in advance.

**Comment by xyzblocks** [comment]
If possible, could you share a snippet or the entire project especially the code around the OIDC Client?

**Comment by DanielJamesSharp** [comment]
Yes of course. Heres the oidc-client code.
import { Injectable } from '@angular/core';
import { UserManager, UserManagerSettings, User } from 'oidc-client';

@Injectable({
  providedIn: 'root'
})
export class AuthService {
  private manager = new UserManager(getClientSettings());
  private user: User = null;

  constructor() {
    this.manager.getUser().then(user => {
      this.user = user;
    });
   }

   isLoggedIn(): boolean {
     return this.user != null && !this.user.expired;
   }

   getClaims(): any {
     return this.user.profile;
   }

   getAuthorizationHeaderValue(): string {
     return `${this.user.token_type} ${this.user.access_token}`;
   }

   startAuthentication(): Promise<void> {
     return this.manager.signinRedirect();
   }

   completeAuthentication(): Promise<void> {
     return this.manager.signinRedirectCallback().then(user => {
       this.user = user;
     });
   }
}

export function getClientSettings(): UserManagerSettings {
  return {
    authority: 'https://localhost:5001',
    client_id: 'angular',
    redirect_uri: 'http://localhost:4200/auth-callback',
    response_type: 'id_token token',
    scope: 'openid profile',
    filterProtocolClaims: true,
    loadUserInfo: true
  };
}

Followed by the auth-callback class
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../services/auth.service';

@Component({
  selector: 'app-auth-callback',
  templateUrl: './auth-callback.component.html',
  styleUrls: ['./auth-callback.component.css']
})
export class AuthCallbackComponent implements OnInit {

  constructor(private authService: AuthService) { }

  ngOnInit() {
    this.authService.completeAuthentication();
  }

}

and a simple authGuard
import { Injectable } from '@angular/core';
import { CanActivate } from '@angular/router';
import { AuthService } from './auth.service';

@Injectable()

export class AuthGuardService implements CanActivate {

  constructor(private authService: AuthService) { }

  canActivate(): boolean {
    if (this.authService.isLoggedIn()) {
      return true;
    }

    this.authService.startAuthentication();
    return false;
  }
}

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by xyzblocks** [comment]
@DanielJamesSharp Take a look at this project and see how I use OIDC-Client.

https://github.com/xyzblocks/feature-toggle-ui

**Comment by DanielJamesSharp** [comment]
@xyzblocks I've had a look and it looks very similar to what I have. My issues has something to do with using angular as the UI for the loginscreen. Using the quickstart MVC app everything works completely perfectly. Only when you substitute for an Angular frontend, I get this CORS issue when the call-back is called.

**Comment by xyzblocks** [comment]
In that case, I'm pretty sure the problem is with the OpenID provider. If I had to guess, you are using Identity Server C#?

**Comment by brockallen** [comment]
Perhaps the docs would help? http://docs.identityserver.io/en/latest/topics/cors.html

**Comment by DanielJamesSharp** [comment]
@xyzblocks yes, I am using IdentityServer C#. 
I've read them docs before posting this and tried to allow CORS origin.

Sorry for the late replies, I've been on other projects recently. Appreciate the help and will be moving back to the project shortly.

**Comment by brockallen** [comment]
Ok, I'll close for now then. If you still have issues, feel free to reopen.

**Comment by eddie-jb** [comment]
@DanielJamesSharp were you able to figure this out?
