### ISSUE TITLE
Quickstart: Client Credentials - How to get the output?

### ISSUE THREAD

**Issue by kevingates** [IdentityServer/IdentityServer4#3233]
### Question / Steps to reproduce the problem
In this section: https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html#calling-the-api

The second paragraph says,

> The output should look like this:
![1_client_screenshot](https://identityserver4.readthedocs.io/en/latest/_images/1_client_screenshot.png)

### Possible Solution
Add another line that clarifies *how* we are to get that output would be helpful.
**EXAMPLE**
> Run ______, then put _____ in the URL bar. You will see ______ in the console window.

**Comment by leastprivilege** [comment]
@LindaLawton

**Comment by leastprivilege** [comment]
Did you notice the "Edit on Github" link at the top of the page? You can make those changes yourself.

**Comment by kevingates** [comment]
For me, I’m not sure how that output got produced, which is why I made this issue.

**Comment by LindaLawton** [comment]
I am in the process of rewriting the quick starts you are right we should have a picture showing the proper results for users who may not be aware of what the standard response should be

**Comment by LindaLawton** [comment]
Acutally i think it should be something like 

Run all three projects.  You will see the following in the console window.
