### ISSUE TITLE
Code/Credentials Combined GrantType fails when no Scopes requested

### ISSUE THREAD

**Issue by HoboRobo123** [IdentityServer/IdentityServer4#3236]
### Issue / Steps to reproduce the problem
1. Configure a client to allow both client_credentials and authorization_code grant types
2. Request a token using either grant type with no scopes specified. 
3. The OP server returns "invalid_request" error "invalid scope". 

Normally IdentityServer4 will include all allowed scopes when none are asked for.

**Comment by leastprivilege** [comment]
Confirmed. Will fix.

**Comment by leastprivilege** [comment]
Actually. No - can't repro.

Couple of things to narrow your problem down:

* make sure you have a redirect URI configured when you enable the code grant type
* omitting scopes is only allowed for certain requests at the token endoint - e.g. client credentials. For code flow you need to do an authorize request first, this always requires the scope parameter.

Besides that it works fine for me.

**Comment by HoboRobo123** [comment]
The client has the following Config:
``` c#
new Client
{
    ClientId = "postman",
    ClientName = "Postman",
    ClientUri = "https://www.getpostman.com/docs/v6/postman/sending_api_requests/authorization",

    ClientSecrets =
    {
        new Secret("secret".Sha256())
    },

    AllowedGrantTypes =
    {
        GrantType.ClientCredentials,
        GrantType.AuthorizationCode,
        ExtensionGrantType.DelegationGrant
    },
    AllowAccessTokensViaBrowser = true,

    RedirectUris = { "https://app.getpostman.com/oauth2/callback" },

    AllowOfflineAccess = true,

    AllowedScopes =
    {
        IdentityServerConstants.StandardScopes.OpenId,
        IdentityServerConstants.StandardScopes.Profile,
        IdentityServerConstants.StandardScopes.Email,
        IdentityServerConstants.StandardScopes.OfflineAccess,
        "api.products",
        "api.partners",
        "api.productinstances",
        "api.users"
    }
}
```

But IdentityServer4 logs the following when I omit scopes for the client credentials request.
``` json
{"Name":"Token Issued Failure","Category":"Token","EventType":"Failure","Id":2001,"ClientId":"postman","ClientName":"Postman","Endpoint":"Token","GrantType":"client_credentials","Error":"invalid_scope","ActivityId":"0HLMF5440Q7E5:00000001","TimeStamp":"2019-05-03T18:51:24Z","ProcessId":1,"LocalIpAddress":"****","RemoteIpAddress":"****"}
```

I have an extension grant validator registered similar to http://docs.identityserver.io/en/latest/topics/extension_grants.html
I also override the DefaultClaimsService but my implementation inherits from DefaultClaimService and only overrides the `GetIdentityTokenClaimsAsync()` method so that shouldn't impact the client credentials flow.

I'll try to repro locally with logging turned up to see if I can get some more info to help troubleshoot.

Thanks

**Comment by HoboRobo123** [comment]
I'm also on 2.3.2. Maybe it's something that got fixed in the update to 2.4.0. I'll see if I can repro on the latest version too.

**Comment by HoboRobo123** [comment]
It looks like the issue occurs if the client is configured with the offline access scope. Leaving scopes blank on the client credentials request tries to pull all the allowed scopes and the TokenRequestValidator step fails.

I'm unsure whether this should be considered a "bug" or intended behavior. It might be nice from a usability point of view to exclude the offline_access scope in this scenario but the reason for the failure makes sense.

[logs.txt](https://github.com/IdentityServer/IdentityServer4/files/3143294/logs.txt)

**Comment by leastprivilege** [comment]
`IdentityServerConstants.StandardScopes.OfflineAccess,` needs to be removed. Use `AllowOfflineAccess` instead.

**Comment by HoboRobo123** [comment]
@leastprivilege thank you!
