### ISSUE TITLE
Revoke access for specific device

### ISSUE THREAD

**Issue by Sascha-Gschwind** [IdentityServer/IdentityServer4#3237]
#### Situation
* Web Client that can be run on multiple devices
* Code Flow with Refresh Tokens
* Our IdentityServer implementation is based on the AspNetIdentity quickstart

#### Problem
We want to be able to revoke access for a specific device. Per default, when you navigate to /grants only one grant will be shown. If you click on Revoke Access all grants from all devices will be removed.
E.g. I have a Windows Client where I open the homepage in a browser. I also have an Android Phone where I do the same through a browser. Each of these will have their own set of Access and Refresh Tokens which is good and works fine. Now I want to revoke access to the Android Phone but not the Windows Client. I know that I could just Logout from the Android Phone but I want to be able to do this in the IdentityServer UI as well but I can only revoke all tokens simultaneously (at least in the quickstart that is).

#### What we have done to do this so far
When I inspected the code from the InMemoryPersistedGrantStore I saw that it has a RemoveAsync(string key) method. So I thought I should be able to do this.

I created an Interface which adds the needed method to the IIdentityServerInteractionService as well as the IPersistedGrantService.
```
public interface IHsrPersistedGrantService : IPersistedGrantService
{
    Task RemoveGrantAsync(string key);
}

public interface IHsrInteractionService : IIdentityServerInteractionService
{
    Task RevokeSpecificUserConsentAsync(string key);
}
```

The next step was to show all the grants in the /grants page instead of merging them together into one. So I implemented the newly created Interface IPersistedGrantService based on the DefaultPersistedGrantService. The following changes have been made to the default implementation:

```
// Insead of Join we use Merge now in GetAllGrantsAsync
private IEnumerable<Consent> Merge(IEnumerable<Consent> first, IEnumerable<Consent> second)
{
    var list = first.ToList();
    list.AddRange(second.ToList());
    return list;
}

public Task RemoveGrantAsync(string key)
{
    return this.store.RemoveAsync(key);
}
```

This worked fine, we were able to see all the grants now (e.g. I have 2 devices with tokens -> I would see 2 grants in the /grants page).

I then added the key property to the GrantViewModel and made sure the key was stored.

I edited the GrantsController to have a Revoke and a RevokeAll method which should execute the newly added code:

```
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Revoke(string clientId, string key)
{
    await this.interaction.RevokeSpecificUserConsentAsync(key);
    await this.events.RaiseAsync(new GrantsRevokedEvent(this.User.GetSubjectId(), clientId));

    return this.RedirectToAction("Index");
}

[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> RevokeAll(string clientId)
{
    await this.interaction.RevokeUserConsentAsync(clientId);
    await this.events.RaiseAsync(new GrantsRevokedEvent(this.User.GetSubjectId(), clientId));

    return this.RedirectToAction("Index");
}
```

Now all was set up I thought. I was able to see all the grants for this user from all devices, the Revoke button executed the Revoke method from the GrantsController which also received the correct key of the grant.

#### Question
And here's the actual problem I have. The grant did not get removed. I tried a lot of things by now, did a lot of debugging but the grant just doesn't want to get removed. The RemoveAsync(string key) method of the IPersistedGrantStore gets called but nothing happens. I even tried implementing the IPersistedGrantStore myself which lead to further problems (now I couldn't get tokens anymore because the Authorization_Code didn't get stored, even though I just copied the InMemoryPersistedGrantStore from this library.

Is there any way or example that helps me achieve my goal to revoke tokens from specific devices?

#### Log
```
CORS request made for path: /grants/Revoke from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
```
Note: CORS is set to AllowAll for testing purposes

**Comment by Sascha-Gschwind** [comment]
I added the following line into the Startup.cs AddIdentityServer

`options.Cors.CorsPaths.Add("/grants/Revoke");`

Now my log looks like this:
`2019-05-01 12:51:11.857 +02:00 [DBG] CORS request made for path: /grants/Revoke from origin: null
2019-05-01 12:51:11.857 +02:00 [DBG] Client list checked and origin: null is not allowed
2019-05-01 12:51:11.857 +02:00 [WRN] CorsPolicyService did not allow origin: null`

I don't understand why it is null. The origin is the identityserver itself because I'm in the /grants page and clicking on the Revoke Access button.

**Comment by brockallen** [comment]
I don't fully understand your design (and I'm not looking for all the innards), but normally you create different clients for different apps. For wep apps, it's easy. For native apps, it's harder since 2 instances of an android app on 2 devices is harder, so in that case you need some sort of dynamic client registration or some mechanism to allow a user to identify one vs. the other. Having said all of that, we don't have anything for either in the current implementation.

**Comment by Sascha-Gschwind** [comment]
Thanks for the feedback then!
