### ISSUE TITLE
Checksession JS causes 100% CPU consumption in Chrome

### ISSUE THREAD

**Issue by u-abramchuk** [IdentityServer/IdentityServer4#3238]
Hi,

we've faced an issue with JS code returned from Checksession endpoint. Together with some extensions it causes Chrome tab to utilize 100% CPU. The reason is in the way these extensions use messaging via `window.addEventListener('message', ...)` and `window.postMessage`. 

### Pre-setup:
1. IdentityServer4 on server
2. Oidc-client-js on client
3. [MetaMask](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en) or [CryptoPro Extension for CAdES](https://chrome.google.com/webstore/detail/cryptopro-extension-for-c/iifchhfnnmpdbibifmljnfjhpififfog) or some other Chrome extension installed.

### Issue / Steps to reproduce the problem

1. Extension subscribes to all `window` objects it can find, including IdentityServer's `iframe`.
2. Extension publishes event via `window.postMessage`
3. [Checksession event handler](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Endpoints/Results/CheckSessionResult.cs#L343) is called.
4. `e.source` for such event is equal to `window`. Thus call to `e.source.postMessage` leads to invocation of that same handler again, which results in infinite recursion and 100% CPU consumption.

### Possible solution
Sure, turning off such extensions helps. But it's not an option for us as our application is used by many people and we cannot tell them to turn off all Chrome extensions.

Another solution may be some event validation. It looks like checking for event source to be different from window fixes the issue:
```js
if (window === e.source) {
    return;
}
```

**Comment by brockallen** [comment]
Sounds like the extension is hammering the postMessage. Perhaps also ask them why?

**Comment by u-abramchuk** [comment]
I'll link this issue to them.

**Comment by brockallen** [comment]
Hey -- any update on this? I spent some time and I'm not sure how we can prevent a plug in from making spurious requests. We don't/can't know the containing origin and validate it, other than what the spec has us do via the computeSessionStateHash.

**Comment by u-abramchuk** [comment]
No updates so far. I've applied the fix I'd mentioned and it solved the issues for me. 
Speaking about the origin of the event, couldn't you add all the necessary information to the event payload? You just have to discriminate events produces by IdentityServer4 scripts against all the others. Or am I missing something?

**Comment by brockallen** [comment]
> couldn't you add all the necessary information to the event payload

the spec mandates that payload.

**Comment by bioharz** [comment]
Thank you @u-abramchuk for providing us with a quick fix. I'm not sure why the fix doesn't make it to the identity server. And Disadvantages? The issue existswithin other chrome and safari extensions too...

**Comment by brockallen** [comment]
I'll open this back up and test this suggestion (I think I missed it when I originally read this):

> Another solution may be some event validation. It looks like checking for event source to be different from window fixes the issue:

**Comment by armitagemderivitec** [comment]
Hi @brockallen, we have just come across this ourselves and suspect it's caused by our ad-blocker. Were you able to successfully test the suggestion above? If so, will you patch the identity server? Many thanks as always!

**Comment by brockallen** [comment]
I did look into it, and the problem is that if there's something malformed about the data passed in, you're supposed to reply with error, as per-spec.

**Comment by armitagemderivitec** [comment]
OK we'll approach the extension maker. Thanks

**Comment by brockallen** [comment]
Your question got me re-evaluating and I did try to put in @u-abramchuk's fix and it seems to work. I can put this out and if we don't get any complaints we can keep it in and hope it's a long term fix.

**Comment by brockallen** [comment]
Will track and fix here: #3881

**Comment by armitagemderivitec** [comment]
Very much appreciated @brockallen
