### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by joshmouch** [IdentityServer/IdentityServer4#3240]
First, thanks for the great product.
However, I continually find myself scratching my head as to why some certain configuration isn't working as expected, and all the client gets back is something like an "invalid_scope" response.  I'm to the point where I have to fork the entire project and add it to my solution that way so that I can step through the code when I need to to figure out why something worked the way it did.

Some additional logging would go a very long way.  For example, if you are returning an "invalid_scope", throw in a Debug level message explaining why.

That's an issue I'm facing right now.  The AcceptedScopes are set up, but I have no idea why they are being ignored.

**Comment by leastprivilege** [comment]
We have *very* detailed logging. What are you missing?

**Comment by joshmouch** [comment]
In this case, I had scopes defined, but they weren't added to the ApiResources, so line #230 of ScopeValidator.cs returned invalid scope.

**Comment by joshmouch** [comment]
And you *do* have very detailed logging.  I've been going through the source.
