### ISSUE TITLE
Consider global switch to disable request_uri feature

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3242]
To disable outbound calls.

**Comment by brockallen** [comment]
the other idea could be a per-client list of allowed domains for request_uri (sort of like the allowed cors origins).

**Comment by leastprivilege** [comment]
Global switch is implemented - and defaults to "disabled". In addition we pass the client object to the back channel handler so any custom processing could be implemented there.

We will wait how this feature pans out before we add more formal config support.
