### ISSUE TITLE
Consider to respect scope parameter of Refresh Request to obtain access tokens with narrower scope

### ISSUE THREAD

**Issue by AndreiGorlov** [IdentityServer/IdentityServer4#3245]
For example if we have original access_token with resource owner authorized scopes `["api1", "api2", "offline_access","openid"]` we can request refresh with `api1` scope only and use obtained token for access `api1` resource only.

Also id_token may be omitted in response if scope parameter provided and not contains `openid`/other identity resource scopes.

**Comment by leastprivilege** [comment]
Tracked 

https://github.com/IdentityServer/IdentityServer4/issues/3519
https://github.com/IdentityServer/IdentityServer4/issues/3520
