### ISSUE TITLE
SSO between a trusted web app and web app protected by Identity Server

### ISSUE THREAD

**Issue by ShruthiMuddada** [IdentityServer/IdentityServer4#3247]
We are trying to implement SSO between a trusted internal web application that is not using Identity server 4 (App A) and our web application (App B) using hybrid flow, protected by Identity Server 4. (Note: App B is hosted in IIS)

App A will provide the Username in its Token.

What is the best approach in Identity Server 4 to achieve this and are there any examples of doing this?

Below is the approach we tried:
One approach we tried was to create an Extension Grant Type which validates a user by using username and client Id. We get the Access and Id Tokens, create a cookie manually and then redirect to App B. But Identity Server is not recognizing that user is already logged in and is displaying the Login Page.

**Comment by brockallen** [comment]
Have you looked at this: http://docs.identityserver.io/en/latest/topics/federation_gateway.html

Having said that, this seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
