### ISSUE TITLE
Support alternate signing algorithms like PS256 and ES256

### ISSUE THREAD

**Issue by chandrasoma** [IdentityServer/IdentityServer4#3250]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chandrasoma** [comment]
I am very sorry about the description. Yes, does the identityserver4 now support the alternate signing algorithms like PS256 and ES256?

**Comment by chandrasoma** [comment]
Please let me know when do you expect to implement supporting alternate signing algorithms.

**Comment by leastprivilege** [comment]
PS256 is not supported by Microsoft right now. ES256 will come once we are on .NET Core 3

**Comment by chandrasoma** [comment]
Thank you.

**Comment by leastprivilege** [comment]
Will be supported in 3.0
