### ISSUE TITLE
Suggestion: Rename `ApiResource.UserClaims` to `AccessTokenClaims` and `IdentityResource.UserClaims` to `IdentityTokenClaims`.

### ISSUE THREAD

**Issue by Jehoel** [IdentityServer/IdentityServer4#3251]
**Is your feature request related to a problem? Please describe.**

My feature request is related to a developer-usability problem.

The `Resource` class' property `UserClaims`, at first glance, implies they're `id_token` claims because it's "User"-specific (or at least, shared between `id_token` and `access_token`). Whereas in reality the subclass `ApiResource.UserClaims` is _only_ used by `access_token` and `IdentityResource.UserClaims` is _only_ used by `id_token`.

**Describe the solution you'd like**

While `UserClaims` can be retained, I think it should be changed to be a hidden (`protected internal`) member and instead it should be exposed in the `ApiResource` and `IdentityResource` subclasses as `AccessTokenClaims` and `IdentityUserOrEndPointTokenClaims` respectively to prevent any confusion by developers using the IdentityServer4 system.

I also think `IProfileService`'s `GetProfileDataAsync` method should be replaced with three separate methods for `id_token`, `access_token`, and user-profile claims respectively instead of differentiating sources through the `ProfileDataRequestContext.Caller` property (which is a `String` and not an `enum` valued property too). If extensibility is a concern, consider adding a fourth method, for example (as below). This can be further simplified by exposing a simpler interface (`ISimpleProfileService`) assuming that `id_token` and user-profile endpoint claims are identical:

    public interface IProfileService
    {
        Task<IEnumerable<Claim>> GetAccessTokenClaims( ProfileDataRequestContext )
        Task<IEnumerable<Claim>> GeIdentityTokenClaims( ProfileDataRequestContext )
        Task<IEnumerable<Claim>> GetUserProfileEndPointClaims( ProfileDataRequestContext )
        Task<IEnumerable<Claim>> GetOtherClaims( ProfileDataRequestContext, String caller )
    }

    public interface ISimpleProfileService
    {
        Task<IEnumerable<Claim>> GetAccessTokenClaims( ProfileDataRequestContext )
        Task<IEnumerable<Claim>> GeIdentityTokenClaims( ProfileDataRequestContext )
    }

    public class DefaultProfileService : IProfileService
    {
        private readonly ISimpleProfileService inner;
        
        public DefaultProfileService( ISimpleProfileService inner )
        {
            this.inner = inner ?? throw new ArgumentNullException(nameof(inner));
        }

        Task<IEnumerable<Claim>> GetAccessTokenClaims( ProfileDataRequestContext context ) => this.inner.GetAccessTokenClaims( context );
        Task<IEnumerable<Claim>> GeIdentityTokenClaims( ProfileDataRequestContext context ) => this.inner.GeIdentityTokenClaims( context );
        Task<IEnumerable<Claim>> GetUserProfileEndPointClaims( ProfileDataRequestContext context ) => this.inner.GeIdentityTokenClaims( context );
        Task<IEnumerable<Claim>> GetOtherClaims( ProfileDataRequestContext, String caller ) => throw new NotSupportedException();
    }
    

**Describe alternatives you've considered**
* None.

**Additional context**

This came to mind because I was investigating a bug caused by an IS4-consuming web-application API expecting Claims added to the `access_token` when they were only added to `id_token`. After spending a couple of hours stepping-through the IS4 source-code I realised how Claims were distributed (i.e. to `access_token`, `id_token`, or user-profile endpoint based on the parent `Resource` subclass type). This is not exactly intuitive to people who are facing OAuth/OIDC with a more _facile_ mentality towards authentication infrastructure than those who have read all of the RFCs inside-out.

While the IS4 documentation does explain this - the API itself is not exactly self-documenting. I feel explicitly naming the collections as `AccessTokenClaims` and `IdentityTokenClaims` (and/or `UserProfileClaims`) would reduce the learning curve and reduce future bugs.

**Comment by leastprivilege** [comment]
It's is called user claims - because there is also the concept of client claims.

I do like the idea of having multiple methods in the profile service though. The interface won't change, but we could provide a base class that does the switching based on the caller.

**Comment by TomCJones** [comment]
not sure I understand that - all claims are claims about the user.
The client may request some claims, but these are not client claims.
Some claims are provide by the AS, some by the identity token, perhaps some by the user himself. That is the most mysterious.
