### ISSUE TITLE
External IdP unavailable, Password GrantType fallback

### ISSUE THREAD

**Issue by zapap** [IdentityServer/IdentityServer4#3255]
Using IdentityServer as a gateway to an external IdP. 

Assuming user's email (from external IdP) is stored in IdentityServer, if the external IdP goes offline, can users can still authenticate by going through a registration process in which an email is sent to set a local password and complete sign-up. This can be handy as a fallback solution in case of external IdP outage.

Thought?

**Comment by brockallen** [comment]
This would be up to your customization of IdentityServer, and nothing in IdentityServer itself.

**Comment by zapap** [comment]
Thanks for the feedback.
