### ISSUE TITLE
Docs: Multiple bad links on quickstarts/samples page

### ISSUE THREAD

**Issue by ascott18** [IdentityServer/IdentityServer4#3256]
On http://docs.identityserver.io/en/latest/quickstarts/community.html:

- "Razor Pages based QuickStart sample" links to a nearly-empty repo (just a readme and gitignore)
- "This sample combines the EF and ASP.NET Identity quickstarts" is a 404.

**Comment by LindaLawton** [comment]
Looks like there is stuff in the dev branch just not master

https://github.com/IdentityServer4Contrib/IdentityServer4.Contrib.Templates.RazorPages/tree/develop

However it hasnt been touched in two years.

**Comment by gohf** [comment]
The dev branch just has a folder structure and unfortunately there is no code within.
