### ISSUE TITLE
Make EntityFramework.Stores\*Store.cs private fields accessible for derived Classes

### ISSUE THREAD

**Issue by BloodyMettle** [IdentityServer/IdentityServer4#3257]
**Problem description**
I'm running an EntityFrameworkCore based IdentityServer4 and use the provided package IdentityServer4.EntityFramework.Stores. As always, there are very useful base implementations for the [`IClientStore`](https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Stores/ClientStore.cs), and the other Stores (`IResourceStore`, `IDeviceFlowStore`, `PersistedGrantStore`).
I wanted to add a method (only to the `ClientStore` so far, but it might come up for all of them) and since the base functionality is already there, I decided to inherit from the provided implementation instead of copying the wheel: 

```
public interface IClientStoreExtended : IClientStore 
{
    Task<ICollection<Client>> ExtendedMethod();
}
```
```
public class ClientStoreExtended : ClientStore, IClientStoreExtended
{
    public ClientStoreAp(IConfigurationDbContext context, ILogger<ClientStore> logger) : base(context, logger) {}
    public Task<ICollection<Client>> ExtendedMethod()
    {
         //_context.DoSomething...
    }
}
```

Obviously I needed the `IConfigurationDbContext` and `ILogger` in my method as well. But since it's private to the base class, i can't use it. 
Currently I only see three options:
1. Implementing the `IClientStore` myself and have the context injected into the new implementation. This would result in a copy-paste of the already implemented function from `ClientStore`, since I'm totally fine with that version.
2. Save the `IConfigurationDbContext` and `ILogger` in a new field in the subclass and have a class that has two private members doubled. Even if it's only a reference type and they reference the same injected object, i think it's not really good style to do so. 
3. Do method injection in the new class or in extension methods for the IClientStore, which would result in a dependency on the context and the logger for all calling classes.

There might be other options that I don't recognize at the moment though. 

**Suggestion**
Make the `DbContext` and `Logger` available for subclasses of the *Store.

I'm not sure if it was an intended design decision to keep these fields private, if so, it would be nice to have some context about the thought behind it. 

PS:
Thanks for the great work done with these frameworks.

**Comment by brockallen** [comment]
Done. Have a look please.

**Comment by BloodyMettle** [comment]
Looks good to me, thank you!
