### ISSUE TITLE
.Net MVC Policy Authorization Redirect Loop

### ISSUE THREAD

**Issue by ericgreenmix** [IdentityServer/IdentityServer4#326]
In idsvr 3, we were able to do the following, (per the idsvr 3 documenation), to avoid the infinite redirect loop on an authenticated but not authorized request. Is there a good way to do this in idsvr 4 with .Net Core MVC ?
```
public class AuthAttribute : AuthorizeAttribute
{
    protected override void HandleUnauthorizedRequest(AuthorizationContext filterContext)
    {
        if (filterContext.HttpContext.User.Identity.IsAuthenticated)
        {
            // 403 we know who you are, but you haven't been granted access
            filterContext.Result = new HttpStatusCodeResult(System.Net.HttpStatusCode.Forbidden);
        }
        else
        {
            // 401 who are you? go login and then try again
            filterContext.Result = new HttpUnauthorizedResult();
        }
    }
}
```

**Comment by brockallen** [comment]
UI style MVC?

**Comment by ericgreenmix** [comment]
What do you mean by UI style MVC?

To give a bit more detail, on my Controller, I have something like `[HttpPost, Authorize("mypolicy")]`. If Authorization fails, it is emitting the 401, even if the user is Authenticated and there is no override for `HandleUnauthorizedRequest` in the new .Net Core AuthorizationAttribute, like there was before.

**Comment by brockallen** [comment]
> What do you mean by UI style MVC?

As opposed to just an API.

**Comment by ericgreenmix** [comment]
Ah, yes

**Comment by brockallen** [comment]
I had something similar in a project, but I can't repro it now. IIRC what I did was to set AutomaticChallenge on the OIDC MW to false. This fell thru to the cookie MW's 401 vs. 403 behavior.

**Comment by ericgreenmix** [comment]
Was able to get it working by letting it fall through like that. Thanks!
