### ISSUE TITLE
Unable to install version 3.0.0-preview3.4 NuGet package

### ISSUE THREAD

**Issue by myalexbennett** [IdentityServer/IdentityServer4#3262]
Trying to install 3.0.0-preview3.4 in Visual Studio 2019 .NET Core 3.0 via NuGet package manager gives the following failed response:

PM> Install-Package IdentityServer4 -Version 3.0.0-preview3.4
Restoring packages for C:\Users\myale\Source\Repos\WebApplication13\WebApplication13\WebApplication13.csproj...
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='IdentityServer4.Storage'&semVerLevel=2.0.0
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.AspNetCore.Authentication.OpenIdConnect'&semVerLevel=2.0.0
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='System.IdentityModel.Tokens.Jwt'&semVerLevel=2.0.0
  GET https://api.nuget.org/v3-flatcontainer/identityserver4.storage/index.json
  OK https://api.nuget.org/v3-flatcontainer/identityserver4.storage/index.json 124ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/identityserver4.storage/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/identityserver4.storage/index.json 78ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/identityserver4.storage/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/identityserver4.storage/index.json 79ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/identityserver4.storage/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/identityserver4.storage/index.json 77ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/identityserver4.storage/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/identityserver4.storage/index.json 79ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/identityserver4.storage/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/identityserver4.storage/index.json 78ms
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/identityserver4.storage/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.identitymodel.tokens.jwt/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.identitymodel.tokens.jwt/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.identitymodel.tokens.jwt/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.identitymodel.tokens.jwt/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.identitymodel.tokens.jwt/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.identitymodel.tokens.jwt/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.identitymodel.tokens.jwt/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json 76ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/identityserver4.storage/index.json 77ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json 78ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json 79ms
  OK https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json 88ms
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/3.0.0-preview3-19153-02/microsoft.aspnetcore.authentication.openidconnect.3.0.0-preview3-19153-02.nupkg
  OK https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json 103ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json 108ms
  OK https://api.nuget.org/v3-flatcontainer/system.identitymodel.tokens.jwt/index.json 96ms
  GET https://api.nuget.org/v3-flatcontainer/system.identitymodel.tokens.jwt/5.4.0/system.identitymodel.tokens.jwt.5.4.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.identitymodel.tokens.jwt/5.4.0/system.identitymodel.tokens.jwt.5.4.0.nupkg 20ms
  OK https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/3.0.0-preview3-19153-02/microsoft.aspnetcore.authentication.openidconnect.3.0.0-preview3-19153-02.nupkg 91ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.JsonWebTokens'&semVerLevel=2.0.0
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.tokens/index.json
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Tokens'&semVerLevel=2.0.0
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.identitymodel.tokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.identitymodel.tokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.identitymodel.tokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.identitymodel.tokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.identitymodel.tokens/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.identitymodel.tokens/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.tokens/index.json 43ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.tokens/5.4.0/microsoft.identitymodel.tokens.5.4.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.tokens/5.4.0/microsoft.identitymodel.tokens.5.4.0.nupkg 20ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json 77ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json 79ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json 77ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json 79ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json 84ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/system.identitymodel.tokens.jwt/index.json 323ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.aspnetcore.authentication.openidconnect/index.json 323ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/system.identitymodel.tokens.jwt/index.json 323ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/system.identitymodel.tokens.jwt/index.json 323ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/system.identitymodel.tokens.jwt/index.json 324ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/system.identitymodel.tokens.jwt/index.json 324ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json 108ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.jsonwebtokens/5.4.0/microsoft.identitymodel.jsonwebtokens.5.4.0.nupkg
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.identitymodel.tokens/index.json 119ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.jsonwebtokens/5.4.0/microsoft.identitymodel.jsonwebtokens.5.4.0.nupkg 18ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.identitymodel.tokens/index.json 153ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.logging/index.json
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Logging'&semVerLevel=2.0.0
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.identitymodel.logging/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.identitymodel.logging/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.identitymodel.logging/index.json
  GET https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.identitymodel.logging/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.identitymodel.logging/index.json
  GET https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.identitymodel.logging/index.json
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.identitymodel.tokens/index.json 173ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.identitymodel.tokens/index.json 172ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.identitymodel.jsonwebtokens/index.json 179ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.identitymodel.tokens/index.json 170ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/system.identitymodel.tokens.jwt/index.json 402ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.identitymodel.tokens/index.json 173ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.logging/index.json 45ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.logging/5.4.0/microsoft.identitymodel.logging.5.4.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.identitymodel.logging/5.4.0/microsoft.identitymodel.logging.5.4.0.nupkg 18ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore-tooling/flatcontainer/microsoft.identitymodel.logging/index.json 78ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-entityframeworkcore/flatcontainer/microsoft.identitymodel.logging/index.json 77ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-core/flatcontainer/microsoft.identitymodel.logging/index.json 77ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-extensions/flatcontainer/microsoft.identitymodel.logging/index.json 77ms
  NotFound https://dotnetfeed.blob.core.windows.net/aspnet-aspnetcore/flatcontainer/microsoft.identitymodel.logging/index.json 79ms
  NotFound https://dotnetfeed.blob.core.windows.net/dotnet-windowsdesktop/flatcontainer/microsoft.identitymodel.logging/index.json 77ms
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.AspNetCore.Authentication.OpenIdConnect'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.AspNetCore.Authentication.OpenIdConnect'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='IdentityServer4.Storage'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.JsonWebTokens'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='IdentityServer4.Storage'&semVerLevel=2.0.0
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.JsonWebTokens'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Logging'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Logging'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Tokens'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Tokens'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='System.IdentityModel.Tokens.Jwt'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='System.IdentityModel.Tokens.Jwt'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.AspNetCore.Authentication.OpenIdConnect'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.AspNetCore.Authentication.OpenIdConnect'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='IdentityServer4.Storage'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='IdentityServer4.Storage'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.JsonWebTokens'&semVerLevel=2.0.0'.
The HTTP request to 'GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.JsonWebTokens'&semVerLevel=2.0.0' has timed out after 100000ms.
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.JsonWebTokens'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Tokens'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Tokens'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Logging'&semVerLevel=2.0.0'.
An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='Microsoft.IdentityModel.Logging'&semVerLevel=2.0.0
Retrying 'FindPackagesByIdAsyncCore' for source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='System.IdentityModel.Tokens.Jwt'&semVerLevel=2.0.0'.
The HTTP request to 'GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='System.IdentityModel.Tokens.Jwt'&semVerLevel=2.0.0' has timed out after 100000ms.
  GET http://nuget.agorapic.com/nuget/FindPackagesById()?id='System.IdentityModel.Tokens.Jwt'&semVerLevel=2.0.0
Install-Package : Failed to retrieve information about 'IdentityServer4.Storage' from remote source 'http://nuget.agorapic.com/nuget/FindPackagesById()?id='IdentityServer4.Storage'&semVerLevel=2.0.0'.
  An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.167.200.58:80
At line:1 char:1
+ Install-Package IdentityServer4 -Version 3.0.0-preview3.4
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by brockallen** [comment]
Uhh, can you help dig a bit more into your problem?

**Comment by myalexbennett** [comment]
Absolutely, what would you like me to try? It's a new install of VS 2019.

**Comment by leastprivilege** [comment]
Can't repro

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IdentityServer4" Version="3.0.0-preview3.4" />
  </ItemGroup>

</Project>
```

**Comment by myalexbennett** [comment]
It looks like it was a corrupt NuGet config on my end. I deleted nuget.config and that fixed the issue.
