### ISSUE TITLE
IdentityServer login with external provider access token

### ISSUE THREAD

**Issue by OneCyrus** [IdentityServer/IdentityServer4#3264]
Currently we use IdentityServer 4 with Azure AD as our external login provider. Our APIs are protected by the tokens of the IdentityServer. This works fine. 

Now we would like to use our APIs in products where we already have a valid Azure AD access token. e.g. Office 365/Teams addins. As the user is already logged into those applications he has already a valid Azure AD token to which our addin has access. 

Is there a way to get a valid token from our IdentityServer with the users' Azure AD access token so that the user doesn't need to login into IdentitySever again?

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/latest/topics/extension_grants.html

**Comment by OneCyrus** [comment]
that looks very interesting! will give this a try. thank you!
