### ISSUE TITLE
Issue with winforms webbrowser control

### ISSUE THREAD

**Issue by wzoet** [IdentityServer/IdentityServer4#3265]
Hi,

We just updated to the 2.4.0 release of identity server using Nuget.
Unfortunately, we are having an issue with our legacy clients using winforms webbrowsercontrol when logging in.

An error occurs when trying to send the access token to the client on the /connect/authorize/callback url saying addEventListener is not found. referring to the window.addEventListener script in this page.

### Issue / Steps to reproduce the problem

Login in the normal way. The issue appears after logging in, or right after giving consent.

### code where the issue occurs

Our previous version had this code:
```
<script>(function(){document.forms[0].submit();})();</script>
```
the 2.4.0 version uses this code:
```
<script>window.addEventListener('load', function(){document.forms[0].submit();});</script>
```
### possible solution

As the webbrowsercontrol behaves like IE8, this should use window.attachEvent. Therefore the script should check which of both methods should be used.
Based on https://stackoverflow.com/questions/12216301/object-doesnt-support-property-or-method-webbrowser-control the script could also add a meta tag in the page header just like issue #633. 
```
<meta http-equiv="X-UA-Compatible" content="IE=edge">
```

Thanks for addressing this. We love your product! Keep up the good work.

**Comment by brockallen** [comment]
dup:  #3128
