### ISSUE TITLE
PrincipalExtensions.cs subject problems

### ISSUE THREAD

**Issue by compunited** [IdentityServer/IdentityServer4#3266]
should be changed to
 public static string GetSubjectId(this IIdentity identity)
        {
            var id = identity as ClaimsIdentity;
            var claim = id.FindFirst(JwtClaimTypes.Subject);
            if (claim == null)
                claim = id.FindFirst(ClaimTypes.NameIdentifier);
            if (claim == null) throw new InvalidOperationException("sub claim is missing");
            return claim.Value;
        }

otherwise  the following error is going to happen

An unhandled exception was thrown by the application.
System.InvalidOperationException: sub claim is missing
   at IdentityServer4.Extensions.PrincipalExtensions.GetSubjectId(IIdentity identity)

**Comment by brockallen** [comment]
Can you elaborate when/why this happens for you? Our requirement in IS is that when you issue the cookie, you must provide a `sub` claim type.

**Comment by compunited** [comment]
switch to dotnet 2.2 and you'll see that it doesn't work. Instead the name identifyer is working.
