### ISSUE TITLE
Client Specific Roles With IDS4

### ISSUE THREAD

**Issue by CShelton11** [IdentityServer/IdentityServer4#3269]
How might one go about having only client specific roles passed to a client in the token.  Def not my preference, but it has been requested of me.  Effectively they are looking to use ids4 to manage access in each application so they can simply use the claims principal to determine privilege within each client.  Hoping that you'll have a simple solution or recommendation....

**Comment by leastprivilege** [comment]
When you implement `IProfileService` you have all the information you need to emit whatever claims to whatever client.

https://identityserver4.readthedocs.io/en/latest/reference/profileservice.html

**Comment by CShelton11** [comment]
Worked Perfectly.  Really appreciate it.
