### ISSUE TITLE
DistributedCacheStateDataFormatter caches the data forever with no opts

### ISSUE THREAD

**Issue by dfrunet** [IdentityServer/IdentityServer4#3270]
In production scenario we use several instances of Identityserver with DistributedRedisCache in between. After a while we see millions keys in Redis, most of them look like: ```DistributedCacheStateDataFormatter--2a2bdc38-c81c-41d7-9210-e5aa22152400; 
sldexp:-1
absexp:-1
data:{"Items":{".redirect":"/account/ExternalLoginCallback?returnUrl=https%3A%2F%2Fdomain.com%2FMenu%2F","scheme":"ExternalIdp",".xsrf":"qhYOnBBcklKhdUSDPyIMkp-Cw7XnXUVmWuBM0HX6PY4","OpenIdConnect.Code.RedirectUri":"https://login.domain.com/signin-oidc"},"Parameters":{},"RedirectUri":"/account/ExternalLoginCallback?returnUrl=https%3A%2F%2Fdomain.com%2FMenu%2F"}```

Short research shown that these records were produced during external authentication by the [DistributedCacheStateDataFormatter](https://github.com/IdentityServer/IdentityServer4/blob/75b1a660c3cab2580112e6e0288f3f6bed8189f9/src/Infrastructure/DistributedCacheStateDataFormatter.cs#L62). It caches the items permanently with no opts. Looks like a bug, isn't? 

A solution could be to use (when presented) the expiration from ```AuthenticationProperties``` object to be cached, and some reasonable or configurable value when omitted.

**Comment by leastprivilege** [comment]
PR?

**Comment by dfrunet** [comment]
Ok. Will first try it internally and then commit.

**Comment by dfrunet** [comment]
@leastprivilege any milestone for this?

**Comment by javaadpatel** [comment]
@leastprivilege is there anything more that needs to be done for this to be approved? Also experiencing the same issue with the cache filling up with keys that never expire.

**Comment by brockallen** [comment]
We will look at this fro our next release the next time we're doing reviews. It will be in July.

**Comment by javaadpatel** [comment]
amazing, thanks @leastprivilege

**Comment by brockallen** [comment]
This PR was merged, so closing this.
