### ISSUE TITLE
Access Token Grant Types

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3272]
Hi,

Grant types for the generated access token is not available in persisted grant store.

Can you please advise, How to get the grant type for the access token from identity server

**Comment by brockallen** [comment]
Not all access token types get written to the grant store.

**Comment by Sathiyanathan-Macro** [comment]
What about CCG and authorisation code?

1. I want to provide access to some of the endpoints using access token which was generated using CCG grant type
2. I want to provide access to some of the endpoints using access token which was generated using authotisation_code grant type.

How can I achieve above cases in identityserver4?

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/latest/reference/ef.html#operational-store-support-for-authorization-grants-consents-and-tokens-refresh-and-reference
