### ISSUE TITLE
context.GetIdentityServerBasePath() returns null, which then throws an exception

### ISSUE THREAD

**Issue by JoshYaxley** [IdentityServer/IdentityServer4#3274]
### Issue

Took me a little while to drill down into this one. I think I know the solution, but not the *exact* cause of the issue.

I'm running IdentityServer4 in an AWS Lambda behind an AWS ELB Application Load Balancer (currently just for development, maybe too for production as a cheap hosting option). Also using a custom Lambda runtime to run it as a netcoreapp2.2 application (Lambda only supports 2.1 otherwise).

In this situation, it seems that `HttpContext.Request.PathBase.Value` returns `null`, so, when `BaseUrlMiddleware.Invoke` calls `context.SetIdentityServerBasePath(request.PathBase.Value.RemoveTrailingSlash())`, it sets the base path to `null` (note that `RemoveTrailingSlash()` returns `null` if the input is `null`).

Then, when `LoginPageResult.ExecuteAsync` is called, it tries to retrieve this base path using `context.GetIdentityServerBasePath().EnsureTrailingSlash()`.

However, `EnsureTrailingSlash()` throws an exception if the input is `null`, which crashes the application.

### Relevant parts of the log file

```
An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
at IdentityServer4.Extensions.StringExtensions.EnsureTrailingSlash(String url)
at IdentityServer4.Endpoints.Results.LoginPageResult.ExecuteAsync(HttpContext context)
at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
```

### Suggested solution

While I'm not sure why `HttpContext.Request.PathBase.Value` returns `null` in this particular hosting case (it works perfectly fine running locally or running in a Docker container on AWS ECS), if it's a use case that wants to be supported, then the solution is probably a simple null guard that defaults to either `/` or a configurable base path.

I'd be happy to take some time to do a pull request if you confirm this is the right way to go!

**Comment by scottbrady91** [comment]
Just an FYI, but this would be a breaking change. I have some customers that expect the null and returning `/` instead would break their implementation.

Having a null check in the `EnsureTrailingSlash` method would not be a breaking change though.

**Comment by scottbrady91** [comment]
I went ahead and added null checks to `EnsureLeadingSlash` and `EnsureTrailingSlash` either way so that they are consistent with their remove counterparts. See PR #3277

**Comment by brockallen** [comment]
pr merged, so closing this.
