### ISSUE TITLE
Resolve/Modify scope

### ISSUE THREAD

**Issue by joshmouch** [IdentityServer/IdentityServer4#3278]
I'd like to set up IdentityServer4 to allow "*" to be passed in as the scope during an authentication request, and then the server will figure out which scopes the client has access to and grant them (and return them in the JWT token). Is there an IdentityServer4 class I can override/implement that can "resolve/modify" the scopes that are sent in

**Comment by leastprivilege** [comment]
OpenID Connect requires the scopes to be sent explicitly (e.g. `openid`). OAuth leaves that decision up to the implementer.

Right now we don't have good extensibility to make that decision yourself - we have a bigger work item to track this for future releases:

https://github.com/IdentityServer/IdentityServer4/issues/1640
