### ISSUE TITLE
405 - connect/authorize Ajax call CORS error

### ISSUE THREAD

**Issue by andresgbertola** [IdentityServer/IdentityServer4#3281]
Hi, I´m using IdentityServer4 for oidc authentication in my ASP .NET Core MVC Client with refresh tokens.

But I´m having trouble with token renewal when expiration ocurrs.

The web app performs ajax calls. Then lets put this situation: The user leaves the browser idle and the token expires. Then he clicks a button, the browser performs the ajax call to the web app. Due to the expiration of the token, the user get the following error (blocked by CORS policy):

> Failed to load resource: the server responded with a status of 405 (Method Not Allowed)customers:1 
> auth-test.mydomain.com/connect/authorize?client_id=openID.myappClient.client&redirect_uri=https%3A%2F%2Fmyapp.mydomain.com%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile%20api.mydomain.com%20offline_access&response_mode=form_post&nonce=636940350363269435.NDQ0NTU1MjQtMGI0Ni00MWU1LTg4NGItYzQ5NzQ1ZDMzZjNiN2VlOTM3MGMtM2EyNi00MzlkLThiODMtOWRlN2Y2MmIyOWRl&state=CfDJ8G5_9qjj_BRInewMRqLDlrLZ2cKkku2SwjqPcivQrPWgUb4FL-EBXPZO5ORBhJcStmHi5WtEkGWsq8OqSTZV-xflxirFQ92r8MTIE75sZlKH8jrfRDGl_vGNV0WG8UxIcoszhkqkPl3GENQDLF_gBwYWiOpcdXnfgpaeILpeY04ywOw0TRDDEvXLzVUs0cY_YpfAHqmtrvJNEuH3q-WzekLP0HeU6h-G3GlyHvu3h24Rc8-H8X1MXf22dQc5vuQFgmMY7PD-dJOAUW-yTw65xkDzjPfaMS1rW7b7b_b_rQ2A9kSRMo_O7-f4vFD2q58pi-YFb7br_YbNPrg4JevIO-xNUkVfqe-3V4UFUM-8M-2NhjfAm8MtuayBHXsHonG_XXYUE2SQJAO4M8y3dQSi1x-2_27NRBrl8lXcoDOolNE5cFqKXf_ohpBHs2wqjdmdFA&x-client-SKU=ID_NETSTANDARD1_4&x-client-ver=5.2.0.0:1 
> 
> Access to XMLHttpRequest at 'https://auth-test.mydomain.com/connect/authorize?client_id=openID.myappClient.client&redirect_uri=https%3A%2F%2Fmyapp.mydomain.com%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile%20api.mydomain.com%20offline_access&response_mode=form_post&nonce=636940350363269435.NDQ0NTU1MjQtMGI0Ni00MWU1LTg4NGItYzQ5NzQ1ZDMzZjNiN2VlOTM3MGMtM2EyNi00MzlkLThiODMtOWRlN2Y2MmIyOWRl&state=CfDJ8G5_9qjj_BRInewMRqLDlrLZ2cKkku2SwjqPcivQrPWgUb4FL-EBXPZO5ORBhJcStmHi5WtEkGWsq8OqSTZV-xflxirFQ92r8MTIE75sZlKH8jrfRDGl_vGNV0WG8UxIcoszhkqkPl3GENQDLF_gBwYWiOpcdXnfgpaeILpeY04ywOw0TRDDEvXLzVUs0cY_YpfAHqmtrvJNEuH3q-WzekLP0HeU6h-G3GlyHvu3h24Rc8-H8X1MXf22dQc5vuQFgmMY7PD-dJOAUW-yTw65xkDzjPfaMS1rW7b7b_b_rQ2A9kSRMo_O7-f4vFD2q58pi-YFb7br_YbNPrg4JevIO-xNUkVfqe-3V4UFUM-8M-2NhjfAm8MtuayBHXsHonG_XXYUE2SQJAO4M8y3dQSi1x-2_27NRBrl8lXcoDOolNE5cFqKXf_ohpBHs2wqjdmdFA&x-client-SKU=ID_NETSTANDARD1_4&x-client-ver=5.2.0.0' (redirected from 'https://myapp.mydomain.com/api/customers/1') from origin 'https://myapp.mydomain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 

I tried enabling CORS in Identity Server 4 for https://*.mydomain.com. But I still have the same error. Which is the proper way to handle token expiration?  

My web app startup.cs:

```
                services.AddAuthentication(options =>
                {
                    options.DefaultScheme = "Cookies.Mvc";
                    options.DefaultChallengeScheme = "oidc";
                })
                .AddCookie("Cookies.Mvc")
                .AddOpenIdConnect("oidc", options =>
                {
                    options.SignInScheme = "Cookies.Mvc";
                    options.Authority = "xxx";
                    options.RequireHttpsMetadata = true;
                    options.ClientId = "xxx";
                    options.ClientSecret = "xxx",
                    options.SaveTokens = true;
                    options.GetClaimsFromUserInfoEndpoint = true;
                    options.ResponseType = "code id_token";
                    options.Scope.Add("api.com");
                    options.Scope.Add("offline_access");
                    options.UseTokenLifetime = false;
                });
```
Thank you!

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
