### ISSUE TITLE
IdentityServer redirect to Angular6 application

### ISSUE THREAD

**Issue by kewinbrand** [IdentityServer/IdentityServer4#3284]
We have an  Angular App as an Login UI (rendered in Backend (aspnetcore)). When we try to login it goes to login method and validate the username/password. Our doubt is about what we should do to IndentityServer goes to redirectUrl (client to be logged) with cookies ** return Redirect(model.ReturnUrl);** only return status 405 to login application.

![Screenshot_1](https://user-images.githubusercontent.com/33696153/58205757-97d8bf80-7cb5-11e9-9c30-942cf84eba5a.png)

![2](https://user-images.githubusercontent.com/33696153/58205843-d5d5e380-7cb5-11e9-9f1c-599ba68aca2d.png)

I used the AspNetCore template to render the angular login page.

AspNetCore Version 2.2

Thank you so far.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!

**Comment by kewinbrand** [comment]
Hi,

Sorry but I don't get it. Why is it a general question? I implemented the whole thing. 
It looks like some problem with routes/cors but I can't figure it out.

**Comment by brockallen** [comment]
It's better suited for SO since it's not a bug you are reporting in IS.

**Comment by kewinbrand** [comment]
Ok. I created in SO. Link:

https://stackoverflow.com/questions/56299519/405-method-not-allowed-cors-origin-problem-when-redirecting-to-angular-applicati

Thank's for your time
