### ISSUE TITLE
Is there any authorization code flow demo with identityserver4 ? thx

### ISSUE THREAD

**Issue by djl394922860** [IdentityServer/IdentityServer4#3285]
i just look for it from identityserver.sample source code , but not found

**Comment by brockallen** [comment]
All of our client sample are here: https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Clients/src

**Comment by djl394922860** [comment]
> All of our client sample are here: https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Clients/src

thx , i got it
