### ISSUE TITLE
OpenID Connect - Identity Server 4 - Logout

### ISSUE THREAD

**Issue by NarayanRG** [IdentityServer/IdentityServer4#3287]
I have a Angular Application, integrated with Identity Server 4. I am not able to implement Logout. I am calling signout() {

     this.manager.signoutRedirect();
I notice that connect/endSession with id_token_hint and postlogoutredirecturi is being called.
In debug mode, Logout function in AccountController is called but User is not Authenticated.
If i use the same endSession resquest and run it or invoke it from browser it works, and cookies are getting removed

My server configuration 

public void ConfigureServices(IServiceCollection services)
        {

            var builder = services.AddIdentityServer()
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApis())
                .AddInMemoryClients(Config.GetClients())
              
                .AddProfileService<UserProfileService>();

               services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
             .AddCookie("Cookies");

                 .AddOpenIdConnect("oidc", "OpenID Connect", options =>
                {
                   options.SignInScheme = IdentityServerConstants.DefaultCookieAuthenticationScheme;
                    options.SignOutScheme = IdentityServerConstants.SignoutScheme;

                    options.SaveTokens = true;

                     options.GetClaimsFromUserInfoEndpoint = true;

                    options.Authority = "https://demo.identityserver.io/";
                    //options.Authority = "https://localhost:5000/";
                    options.ClientId = "mvc";

                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role"
                    };
                });

           

            //Allow CORS
            services.AddCors();
            
            // Register the Swagger generator, defining 1 or more Swagger documents
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info {
                    Title = "RegalPay IDP Service",
                    Version = "v1",
                    Description = "A RegalPay IDP service web API",
                    TermsOfService = "None",
                    Contact = new Contact
                    {
                        Name = "Regal Software",
                        Email = string.Empty,
                        Url = "https://regal-software.com/"
                    },
                });

                // Set the comments path for the Swagger JSON and UI.
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                c.IncludeXmlComments(xmlPath);

                c.OperationFilter<AddAuthorizationHeader>();

            });

        }

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseCors(builder =>
                   builder.AllowAnyOrigin()
                          .AllowAnyHeader()
                          .AllowAnyMethod()
                          
            );

            app.UseCors("AllowAll");

            app.UseHttpsRedirection();

            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();

            // Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.), 
            // specifying the Swagger JSON endpoint.
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "RegalPay IDP Service");
            });

            app.ConfigureCustomExceptionMiddleware();

            app.UseStaticFiles();

            app.UseIdentityServer();

            app.UseMvc();

            app.UseMvcWithDefaultRoute();
        }

public static IEnumerable<Client> GetClients()
        {
            return new List<Client>
            {
                new Client
                {
                    ClientId = "client",

                    // no interactive user, use the clientid/secret for authentication
                    AllowedGrantTypes = GrantTypes.ClientCredentials,

                    // secret for authentication
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },

                    // scopes that client has access to
                    AllowedScopes = { "api1" }
                },
                // resource owner password grant client
                new Client
                {
                    ClientId = "ro.client",
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,

                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowedScopes = { "api1" }
                },
                // OpenID Connect hybrid flow client (MVC)
                new Client
                {
                    ClientId = "mvc",
                    ClientName = "MVC Client",
                 //   AllowedGrantTypes = GrantTypes.Hybrid,
                 //Changed for Angular
                 AllowedGrantTypes = GrantTypes.Implicit,
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },

                 //   RedirectUris           = { "http://localhost:5002/signin-oidc" },
                RedirectUris           = {  "http://localhost:4200/auth-callback" },
                 //   PostLogoutRedirectUris = { "http://localhost:5002/signout-callback-oidc" },
              // PostLogoutRedirectUris = {"http://localhost:4200/home/"},

                PostLogoutRedirectUris = {"https://demo.identityserver.io/Account/Logout"},

               

               // PostLogoutRedirectUris = {"http://localhost:4200/auth-callback"},

                  AllowedCorsOrigins = {"http://localhost:4200"},

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "api1"
                    },

                    //Changed for Angular
                 //   AllowOfflineAccess = true,
                    IdentityTokenLifetime = 60,
                    AccessTokenLifetime = 60,
                    AuthorizationCodeLifetime = 60,

                     AllowAccessTokensViaBrowser = true, //Changed for Angular

                    //Changed for Angular
                  //  UpdateAccessTokenClaimsOnRefresh = true
                }
            };
        }

and my client configuration is 

export function getClientSettings(): UserManagerSettings {
  return {
      authority: 'http://localhost:50000',
     // client_id: 'angular_spa',
    client_id: 'mvc',
   // client_secret: 'secret',
     
    redirect_uri: 'http://localhost:4200/auth-callback',
   // post_logout_redirect_uri: 'http://localhost:4200/auth-callback',

    
    //post_logout_redirect_uri: 'http://localhost:4200/home/',
    post_logout_redirect_uri: 'https://demo.identityserver.io/Account/Logout',
    //AllowedCorsOrigins = 'http://localhost:4200',

      response_type:"id_token token",

   // response_type: "token id_token",
      scope:"openid profile  api1",
      filterProtocolClaims: true,
      loadUserInfo: true //,
     // automaticSilentRenew: true,
//silent_redirect_uri: 'http://localhost:4200/silent-refresh.html'
  };
}

Can someone please help me on this

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
