### ISSUE TITLE
Extracting details from AspNetUsers

### ISSUE THREAD

**Issue by gph2000** [IdentityServer/IdentityServer4#3288]
How do I extract more columns from AspNetUsers? I am using the MVC client from the combined quickstart but I have extended the AspNetUsers table to match my application? I can see the ID and Username in the User.Claims on the secure page but nothing else.

One possibility is to replicate the data in AspNetUserClaims but I would prefer not to have to go down that route.

**Comment by brockallen** [comment]
> How do I extract more columns from AspNetUsers

Using the standard ASP.NET Identity approach: implement a custom UserClaimsPrincipalFactory.

**Comment by gph2000** [comment]
Cheers Brock!
