### ISSUE TITLE
How can I customize the generation of authorization code in the authorization code flow ? thx

### ISSUE THREAD

**Issue by djl394922860** [IdentityServer/IdentityServer4#3289]
is there some interface for that ?? i can implement it

**Comment by djl394922860** [comment]
i found IHandleGenerationService interface , this can create the authorization code (64bit) , can i use addsingleton to replace it ?

**Comment by leastprivilege** [comment]
Yea you can.

but why?

**Comment by djl394922860** [comment]
> Yea you can.
> 
> but why?

first thank your reply , i am just curious for that , then i will use identityserver4 with custom store , so i ask this question , thx again !!
