### ISSUE TITLE
How to implement custom user store in rc version?

### ISSUE THREAD

**Issue by khuramshahzad** [IdentityServer/IdentityServer4#329]

**Comment by brockallen** [comment]
The user store is your responsibility. You only need to implement `IProfileService` in IdentityServer to allow us to query claims for the user.

**Comment by khuramshahzad** [comment]
I have implemented the IProfileService for that i have also implement IResourceOwnerPasswordValidator and ICustomGrantValidator.

When i upgrade from beta version to RC - Update 2 it gives an error in password validation CustomGrantValidationResult is not found.

Can you please let me know that what is update for this  CustomGrantValidationResult.

**Comment by brockallen** [comment]
Perhaps the class name changed to GrantValidationResult.

**Comment by leastprivilege** [comment]
http://docs.identityserver.io/en/dev/topics/extension_grants.html
