### ISSUE TITLE
Please update documentation as per current release of .NET Core and Identity server

### ISSUE THREAD

**Issue by Dheerajmentor** [IdentityServer/IdentityServer4#3290]
Hello Team , 

thanks a lot for creating such a great tool/library for us and helping us implementing security for .net core application in micro-services environment. 

This is to request you guys to please update the document as following it does not allow me to creating a working demo app as command and options mentioned here are not working as of now. 
this makes learner loose confidence if he/she is going on with correct path or not. 

thank you 
Dheeraj Kumar

**Comment by brockallen** [comment]
> This is to request you guys to please update the document as following it does not allow me to creating a working demo app as command and options mentioned here are not working as of now.

Can you be more specific?

**Comment by Dheerajmentor** [comment]
for example in overview of under Preparation you have command 
**dotnet new -i IdentityServer4.Templates** 
this does not run

**Comment by LindaLawton** [comment]
I just ran the following five minutes ago it ran fine.

>dotnet new -i IdentityServer4.Templates

What error did you get exactly?

**Comment by brockallen** [comment]
Any update?

**Comment by LindaLawton** [comment]
Works for me :)

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
