### ISSUE TITLE
AddIdentityServerAuthentication how to set option like GetClaimsFromUserInfoEndpoint?

### ISSUE THREAD

**Issue by m-demydiuk** [IdentityServer/IdentityServer4#3293]
Hello!

We have custom user claims stored in the UserClaim table in the db.

Our client app retrieves access_token from the identity server and then we manually call UserInfo endpoint to get custom user claims. Then we manually validate if user has specific claims.

Is it possible to add some configuration int the `AddIdentityServerAuthentication` so it will go to UserInfo endpoint, request user claims and put it into the user Identity.

So we need something like

```c#
services.AddAuthentication(options =>
{
	options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
	options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddIdentityServerAuthentication(options =>
{
	options.Authority = settings.Authority;
	options.RequireHttpsMetadata = settings.RequireHttpsMetadata;
	options.ApiName = settings.ApiName;

        options.GetClaimsFromUserInfoEndpoint = true;//We need this option

});
```

```
services.AddAuthorization(options =>
{
	options.AddPolicy("CustomPolicy", policy => policy.RequireClaim("CustomClaimType", "CustomClaimValue"));
});
```
And then on the action level use
```
[Authorize("CustomPolicy")]
...
```

Thanks in advance!!!

**Comment by leastprivilege** [comment]
UserInfo is an OpenID Connect feature.

In your scenario you are simply consuming a JWT - either configure the access token to directly contain the claims you need, or write some code to retrieve additional claims.

https://brockallen.com/2017/11/07/the-userinfo-endpoint-is-not-designed-for-apis/
