### ISSUE TITLE
Invalid redirect_uri even though they are exactly the same

### ISSUE THREAD

**Issue by stilren** [IdentityServer/IdentityServer4#3296]
When trying to login to identityserver (using .net core 3 preview) I get Invalid redirect_uri error even though the request uri and the allowed one are identical.

What else could I be doing wrong?

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:6969/connect/authorize?client_id=myapp&redirect_uri=http%3A%2F%2Flocalhost%3A1337%2Fauthentication%2Flogin-callback&response_type=id_token%20token&scope=webAPI%20openid%20profile&state=0caf674ca128402f97e3a3a3034f68fd&nonce=323936c0b5b541d68c34f798f8f6cdb9
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /connect/authorize matched to endpoint type Authorize
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Endpoint enabled: Authorize, successfully created handler: IdentityServer4.Endpoints.AuthorizeEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
dbug: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
      Start authorize request
dbug: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
      No user present in authorize request
dbug: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Start authorize request protocol validation
dbug: IdentityServer4.Stores.ValidatingClientStore[0]
      client configuration validation for client arkelconfigurator succeeded.
fail: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Invalid redirect_uri: http://localhost:1337/authentication/login-callback
{
        "ClientId": "myapp",
        "ClientName": "myapp",
        "AllowedRedirectUris": [
          "http://localhost:1337/authentication/login-callback"
        ],
        "SubjectId": "anonymous",
        "RequestedScopes": "",
        "Raw": {
          "client_id": "myapp",
          "redirect_uri": "http://localhost:1337/authentication/login-callback",
          "response_type": "id_token token",
          "scope": "webAPI openid profile",
          "state": "0caf674ca128402f97e3a3a3034f68fd",
          "nonce": "323936c0b5b541d68c34f798f8f6cdb9"
        }
      }
fail: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
      Request validation failed
```

**Comment by stilren** [comment]
I was using the wrong profile in the new identity server features in core 3. Was using "IdentitySpa" - should have been "SPA"

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0#other-configuration-options

**Comment by eheinz57** [comment]
Hello stilren, 

I am having the same issue, but I can't find where profile is even configured.  I followed the link you posted, but it talks about AddApiAuthorization which doesn't appear to be found in my referenced packages.  I'm using .NET Core 3.1 and IdentityServer4 v3.0.2 with EF/SQL backing the data.  The logs show the "invalid" redirect URI and it matches exactly with the AllowedRedirectUris.
I dug into the code and it appears to be failing at line 285:

`if (await _uriValidator.IsRedirectUriValidAsync(redirectUri, request.Client) == false)`

That code just basically takes the redirect URI from the request and compares it to the client.RedirectUris.  I can see that they match in the logs.

To compound the confusion, this works locally, but not in our deployed solution in azure.  
AND it works for the original request to authenticate, but not the silent renewal.

Any ideas on what to look for?
