### ISSUE TITLE
Performance improvement on TokeCleanup's RemoveGrants method

### ISSUE THREAD

**Issue by RichardSilveira** [IdentityServer/IdentityServer4#3299]
Does RemoveGrants method **really** needs to use `OrderBy`operator while retrieving expiredGrants items?
```
var expiredGrants = context.PersistedGrants
                    .Where(x => x.Expiration < DateTime.UtcNow)
                    .OrderBy(x => x.Key)
                    .Take(_options.TokenCleanupBatchSize)
                    .ToArray()
```

I think that moving away this method will considerally improve the query performance. I'm proposing the same that was already made for `RemoveDeviceCodes` method, for `expiredCodes` collection as follow:

```
var expiredCodes = context.DeviceFlowCodes
                    .Where(x => x.Expiration < DateTime.UtcNow)
                    .Take(_options.TokenCleanupBatchSize)
                    .ToArray();
```

**Comment by LindaLawton** [comment]
Well Take is going to tell it to grab X number of rows.  By adding the order by ensure that it would take the top ones first.   That being said i would think it would make more sense to do 

```
var expiredGrants = context.PersistedGrants
                    .Where(x => x.Expiration < DateTime.UtcNow)
                    .OrderBy(x => x.Expiration)
                    .Take(_options.TokenCleanupBatchSize)
                    .ToArray()
```

Ensuring that the oldest ones are removed first. (Assuming i have my ascending descending correct) 

These days an order by doesn't really do that much to performance as key is more than likely indexed (I don't have the power to check that right now).  If its a performance concern that is causing you to question the order by.

**Comment by scottbrady91** [comment]
A bit of history on this one: https://github.com/IdentityServer/IdentityServer4.EntityFramework/commit/1d7a862903b82c08f28d0787b1dafe1590e2f526#diff-a05e3c090c8013bb1f51e30de5eea6a2
