### ISSUE TITLE
Why does ITokenMetadata not have a key?

### ISSUE THREAD

**Issue by null-d3v** [IdentityServer/IdentityServer4#33]
There are many stores where ITokenMetadata objects are cached based on a key generated by `CryptoRandom.CreateUniqueId()`. However, given an ITokenMetadata, it is not possible to know its key.

Is this intentional? If so, why? It introduces difficulties in implementing distributed storage for IAuthorizationCodeStore, IRefreshTokenStore, and IAuthorizationCodeStore for a load-balanced environment. Mostly with distributed caching and not a relational database store. Or is it only intended that these stores be written to an RDB for a load-balanced setup?

**Comment by leastprivilege** [comment]
These are long lived state artifacts. A cache does not seem ideal.
