### ISSUE TITLE
Sample project dev or production

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#3301]
Should sample projects and documentation show how to run things in only dev mode or how to properly set things up for production as well?

Currently they appear to be designed with dev in mind and throw exceptions when run not in dev.

sample project shows throw exception when not run in dev mode. [#L37](https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Quickstarts/1_ClientCredentials/src/IdentityServer/Startup.cs#L37)

    else
            {
                throw new Exception("need to configure key material");
            }

It will be hard to design samples and docs that show exactly how things should be set up in a production environment as every environment is different. 

I would like some opinions on this because i am leaning towards dev only and removing that else.

**Comment by leastprivilege** [comment]
dev only
