### ISSUE TITLE
Dynamic Scopes (Prefix, Wildcard or Regex pattern)

### ISSUE THREAD

**Issue by cleftheris** [IdentityServer/IdentityServer4#3302]
This feature is related but not limited to Financial APIs (FAPIs) and the functionality around registering a dynamic scope that serves a specific purpose which is determined at run-time of an application that a user must consent upon. A somewhat related issue is #2737 where people request the ability to override the built in `ScopeValidator` in order to achieve this.

What I am proposing is an added value solution that does not break any of the current stuff and I have proven to work in production. I just feel like it may be good enough to share so that It can be better integrated into the project as IdentityServer evolves. The current solution is structured to work around the limitations of the current `Scope` class and `ScopeValidator` as well as the Scope validation extension methods, so it can be surely evolved if it gets integrated. That said the solution consists mainly of 3 decorators. 
1. One around the `IClientStore` 
2. The other around the `IResourceStore`
3. and the third one wraps the `IntrospectionResponseGenerator`

If this is something that fits the product roadmap I am more that willing to make a pull request. I have the code already in a public repo that [you can inspect](https://github.com/indice-co/Indice.AspNet/tree/master/src/Indice.AspNetCore.Identity/Scopes) but I got a hard time creating unit tests around IdentityServer and may need some help.

Thanks

**Comment by leastprivilege** [comment]
Hey, 

thanks!

We will have a look. The plan is to make the built-in scope handling much more flexible.

For now I would rather appreciate if you would document/blog about your approach.

**Comment by cleftheris** [comment]
Hi,

I too believe that if the you make some changes to the Scope and ScopeValidator classes these stuff will be even easyer to implement. 

For now I will try to make a blog post and come back with a link.

Thanks

**Comment by brockallen** [comment]
I'll close this since we have plans to rework in the future. Thanks.

**Comment by cleftheris** [comment]
Hi sorry did not find the time to blog about this. If I do I will post back. If there is something I can do  to help ping me.

Thanks.
