### ISSUE TITLE
Client Credentials Configured with No Scopes

### ISSUE THREAD

**Issue by HoboRobo123** [IdentityServer/IdentityServer4#3306]
Repro:
1. Register a client credentials client with no allowed scopes
2. Request a token
3. Client Authentication is Successful but a "Token Issued Failure" event is generated with an "invalid_scope" error

Should client credential clients be allowed to get access tokens if they do not have any allowed scopes?
I have some APIs that just need a valid access token and don't care about the aud or scope claims. It's easy enough to work around by creating and assigning a dummy scope to the client for these scenarios.

**Comment by leastprivilege** [comment]
A scope is mandatory in our implementation.
