### ISSUE TITLE
Make discovery configuration more flexible

### ISSUE THREAD

**Issue by xmichaelx** [IdentityServer/IdentityServer4#3307]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have two docker containers - one with IS4 and other one with MVC hybrid client and I want them to work together in development environment without modifying `/etc/hosts` file.

This is the docker scenario (bridge network driver)

- IS4 with port 5000 mapped to localhost:5000 (hostname: is4)
- MVC App with Hybrid client mapped to localhost:5001  (hostname: mvc)

I have to set Authority on `mvc` to `http://is4:5000` but this affects discovery document so it has every endpoint prepended with is4 and so hybrid client redirects me for login to `http://is4:5000/connect/authorize` and would later redirect for logout to `http://is4:5000/connect/endsession`.

**Describe the solution you'd like**

Ability to set base uri selectively for authorize and endsession endpoint in `IdentityServerOptions` or shere it with `IssuerUri` if it is provided instead of base url [here](https://github.com/IdentityServer/IdentityServer4/blob/86faf2a7e495c3a5029312bbe5edfae6ecb5215a/src/IdentityServer4/src/ResponseHandling/Default/DiscoveryResponseGenerator.cs#L116)

**Describe alternatives you've considered**

**Alternative 1** for development scenario is:

1. Extending DiscoveryResponseGenerator and manually changing `end_session` and `authorize` endpoints to use `issuerUri` instead of baseUri and use issuerUri 

2. Replacing it in DI container

**Alternative 2** is modifying /etc/hosts and simulating deployment in production scenario under a fake url like `is4.example.com`.

Using `PublicOrigin` is not viable in this context because it uniformly replaces baseurl for all endpoints and here I need it to be done selectively for `issuerUri`, `authorize` and `end_session`.

**Additional context**

The discovery document I'd like to get when I `curl is4:5000/.well-known/openid-configuration` from `mvc` container:

```
{
  "issuer": "http://localhost:5000",
  "jwks_uri": "http://is4:5000/.well-known/openid-configuration/jwks",
  "authorization_endpoint": "http://localhost:5000/connect/authorize",
  "token_endpoint": "http://is4:5000/connect/token",
  "userinfo_endpoint": "http://is4:5000/connect/userinfo",
  "end_session_endpoint": "http://localhost:5000/connect/endsession",
  "check_session_iframe": "http://is4:5000/connect/checksession",
  "revocation_endpoint": "http://is4:5000/connect/revocation",
  "introspection_endpoint": "http://is4:5000/connect/introspect",
  // ... the rest
}
```

**Comment by xmichaelx** [comment]
From the high-level perspective I need the ability to have two "domains" in discovery document - one for the client that lives inside docker container in docker network and other one for all interactions done by user from outside docker network by user.

**Comment by leastprivilege** [comment]
Reading this makes my head hurt ;)

> From the high-level perspective I need the ability to have two "domains" in discovery document - one for the client that lives inside docker container in docker network and other one for all interactions done by user from outside docker network by user.

I think that's a common misconception with the "docker people". In OpenID Connect, the host name is the identity of the token service. If clients use different host names, they logically address different token services.

I think the right answer is: configure your DNS correctly.

**Comment by xmichaelx** [comment]
Of course for production scenario it makes sense, because likely you will have the IS under a publicly recognizable name anyway.

But would you still recommend it for local, automated integration tests? In this scenario you don't always get to change the  /etc/hosts or modify DNSes.
