### ISSUE TITLE
IdentityServer 4 behind Reverse Proxy: Redirect URL is changed

### ISSUE THREAD

**Issue by marcBalta** [IdentityServer/IdentityServer4#3309]
I deployed an IdentityServer4 behind an IIS Reverse Proxy so it is now reachable via
https://domain/IdentityServer/

And I have a angular SPA application which is currently in the state of ongoing development. It is also deployed to the same server and reachable by https://domain/AngularApp/. When it is deployed everything works: After the authentication ( I use the external authentication mechanism) the browser is redirected to https://domain/AngularApp/callback.html.

So far so good. When I, however, debug the application in Visual Studio, the SPA application is running with the following url: http://localhost:56119. The authentication flow is working correctly but the redirect url is changed from  http://localhost:56119/callback.html to https://domain/callback.html which is not existing. 

This problem started with using a reverse proxy, which is however necessary. My assumption is:
* all accesses to the identityserver4 are done by the reverse proxy which has the client address 127.0.0.1.
* maybe the identity server considers this as local access and hence as a relative address and handles the redirect as such.

Relevant parts of the identityserver4 logs:
```
dbuginfo: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 6.0136ms 302 
: IdentityServer4.Services.DefaultClaimsService[0]
      Getting claims for access token for subject: a168b4d518649ab25b3dc8878e02a35e13a9f42d8c227a4ab6435aebc96ec4a9
dbug: IdentityServer4.Test.TestUserProfileService[0]
      Get profile called for subject a168b4d518649ab25b3dc8878e02a35e13a9f42d8c227a4ab6435aebc96ec4a9 from client lobsterwebapi_implicit with claim types email, name via ClaimsProviderAccessToken
dbug: IdentityServer4.Test.TestUserProfileService[0]
      Issued claims: name
dbug: IdentityServer4.Services.DefaultClaimsService[0]
      Getting claims for identity token for subject: a168b4d518649ab25b3dc8878e02a35e13a9f42d8c227a4ab6435aebc96ec4a9 and client: lobsterwebapi_implicit
dbug: IdentityServer4.Services.DefaultClaimsService[0]
      In addition to an id_token, an access_token was requested. No claims other than sub are included in the id_token. To obtain more user claims, either use the user info endpoint or set AlwaysIncludeUserClaimsInIdToken on the client configuration.
info: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint[0]
      Authorize endpoint response
      {
        "SubjectId": "a168b4d518649ab25b3dc8878e02a35e13a9f42d8c227a4ab6435aebc96ec4a9",
        "ClientId": "lobsterwebapi_implicit",
        "RedirectUri": "http://localhost:56119/callback.html",
        "State": "15595491470380.185571376957492260.8366116270391999",
        "Scope": "openid profile lobster"
      }
dbug: IdentityServer4.Hosting.IdentityServerAuthenticationService[0]
      Augmenting SignInContext
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[10]
      AuthenticationScheme: idsrv signed in.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 6.0136ms 302 
```

I've also already examined this in the chrome developer tools with the same observations.
This is the request url send by chrome to the identityserver:
```
https://domain/identityserver/connect/authorize/callback?client_id=lobsterwebapi_implicit&redirect_uri=http%3A%2F%2Flocalhost%3A56119%2Fcallback.html&response_type=id_token%20token&scope=openid%20profile%20tool&nonce=N0.140025512576284821559569766619&state=15595696747620.97191242700320910.8232684904817373
```
The response to this request is a 302 (redirection) with the access token but the Location field of the redirection is not what it should be, is it now the domain instead of localhost as specified in the request url:
```
https://domain/callback.html#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImI4YmNkOGUyODgwZmNiYzQwOTc0ZmYwYTBjNDEyNWEwIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTk1Njk4NDUsImV4cCI6MTU1OTU3MDE0NSwiaXNzIjoiaHR0cHM6Ly9nZS1hcHBzLWRldi5pbnRyYW5ldC5tY2tpbnNleS5jb20vL2lkZW50aXR5c2VydmVyIiwiYXVkIjoibG9ic3RlcndlYmFwaV9pbXBsaWNpdCIsIm5vbmNlIjoiTjAuMTQwMDI1NTEyNTc2Mjg0ODIxNTU5NTY5NzY2NjE5IiwiaWF0IjoxNTU5NTY5ODQ1LCJhdF9oYXNoIjoiSHdlcl9yQ05wOHpJY2V4X0VRN0xDZyIsInNpZCI6IjU1MjNlNWZjMzFkYjlmMmMxYjNiMWE4N2UyNzZmOTUzIiwic3ViIjoiYjk0OTEMGIwMDkxOGI3NTY2NjQ0ZTk1MWJmOTRkMTBhYzM4NTJmZTNhZDllZjRiNGI3NGJhMmZmM2JmZjA0
```

**Comment by leastprivilege** [comment]
We are doing redirect to the **exact** URL configured in the redirect URI configuration of the client. I assume it is your reverse proxy changing the URLs somehow.

**Comment by marcBalta** [comment]
But that would be strange. In IIS you would have to set so called outbound rewrite rules to such kind of changes, There are, however, none defined.

**Comment by grebenval** [comment]
I have the same problem. If I set the options property.PublicOrigin = @"http://mydomen"; And correct work if you leave the default, i.e. not set.

**Comment by marcBalta** [comment]
Exactly. I also had to set it. There is no other way if you let run it behind a reverse proxy. Right?

In ConfigureServices I use:
```
services.AddIdentityServer(o => o.PublicOrigin = "https://domain/")
                .AddDeveloperSigningCredential(false)
                .AddTestUsers(InMemoryConfiguration.Users().ToList())
                .AddInMemoryClients(InMemoryConfiguration.Clients())
                .AddInMemoryIdentityResources(InMemoryConfiguration.IdentityResources())
                .AddInMemoryApiResources(InMemoryConfiguration.ApiResources());
```

**Comment by grebenval** [comment]
public void Configure(IApplicationBuilder app)
{
	if (Environment.IsDevelopment())
	{
		app.UseDeveloperExceptionPage();
		app.UseDatabaseErrorPage();
	}
	else
	{
		app.UseExceptionHandler("/Home/Error");
	}


	var fordwardedHeaderOptions = new ForwardedHeadersOptions
	{
		ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
	};
	fordwardedHeaderOptions.KnownNetworks.Clear();
	fordwardedHeaderOptions.KnownProxies.Clear();

	app.UseForwardedHeaders(fordwardedHeaderOptions);


	app.UseCors("CorsPolicy");


	app.Map("/IdentityServer4", builder =>
	{
		builder.UseCors("CorsPolicy");
		builder.UseForwardedHeaders(fordwardedHeaderOptions);
		builder.UseStaticFiles();
		builder.UseIdentityServer();
		builder.UseMvcWithDefaultRoute();
		builder.UseMvc(routes =>
		{
			routes.MapRoute(
		  name: "default",
		  template: "connect/{action=Index}/{id?}",
		  defaults: new { Controller = "Connect" });
		});
	});
}

**Comment by marcBalta** [comment]
@grebenval  Did that work at your site ? So if you acess 
https://domain/identityserver4/.well-known/openid-configuration
are the endpoints set to the correct domain? For me it didnt.

**Comment by marcBalta** [comment]
I modified a piece of your code in that way: 
```
            var fordwardedHeaderOptions = new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedHost
            };
            fordwardedHeaderOptions.KnownNetworks.Clear();
            fordwardedHeaderOptions.KnownProxies.Clear();

            app.UseForwardedHeaders(fordwardedHeaderOptions);
```
I includes now also the ForwardedHeaders.XForwardedHost header. This made the endpoint configuration to work correctly. I then dont have to use the property PublicOrigin. Unfortunatley then I got the same initial problem: the redirect url is changed in  the same way.

**Comment by grebenval** [comment]
{"issuer":"http://win2016/identityserver4","jwks_uri":"http://win2016/IdentityServer4/.well-known/openid-configuration/jwks","authorization_endpoint":"http://win2016/IdentityServer4/connect/authorize","token_endpoint":"http://win2016/IdentityServer4/connect/token","userinfo_endpoint":"http://win2016/IdentityServer4/connect/userinfo","end_session_endpoint":"http://win2016/IdentityServer4/connect/endsession","check_session_iframe":"http://win2016/IdentityServer4/connect/checksession","revocation_endpoint":"http://win2016/IdentityServer4/connect/revocation","introspection_endpoint":"http://win2016/IdentityServer4/connect/introspect","device_authorization_endpoint":"http://win2016/IdentityServer4/connect/deviceauthorization","frontchannel_logout_supported":true,"frontchannel_logout_session_supported":true,"backchannel_logout_supported":true,"backchannel_logout_session_supported":true,"scopes_supported":["openid","profile","api1","offline_access"],"claims_supported":["sub","name","family_name","given_name","middle_name","nickname","preferred_username","profile","picture","website","gender","birthdate","zoneinfo","locale","updated_at","email","id","jti","role","sid"],"grant_types_supported":["authorization_code","client_credentials","refresh_token","implicit","password","urn:ietf:params:oauth:grant-type:device_code"],"response_types_supported":["code","token","id_token","id_token token","code id_token","code token","code id_token token"],"response_modes_supported":["form_post","query","fragment"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"subject_types_supported":["public"],"id_token_signing_alg_values_supported":["RS256"],"code_challenge_methods_supported":["plain","S256"]}

**Comment by grebenval** [comment]
мой identityserver во внутренней сети http://win2016:5000/IdentityServer4

**Comment by marcBalta** [comment]
But do you still have problems with the redirect url?

**Comment by LindaLawton** [comment]
I suspect your issue is with the downgrade from https to http

**Comment by marcBalta** [comment]
@LindaLawton not unfortunatley not. I changed just now my project to https but no change. I still get redirected to the wrong url.

**Comment by grebenval** [comment]
I use IIS Application Request Routing.
This is not an identityserver4 problem, this is a problem asp.net core 2.2
I made a project, with a test of the context.Response.Redirect (this method is used in Middleware), and got the same error.
	
```
public class Program
{
public static void Main(string[] args)
{
  CreateWebHostBuilder(args).Build().Run();
}
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
.UseStartup<Startup>();
}

public class RedirectHandlingMiddleware
{
 private RequestDelegate _next;
 public RedirectHandlingMiddleware(RequestDelegate next)
 {
  _next = next;
 }
 public async Task Invoke(HttpContext context)
 {
  await _next.Invoke(context);
 string path = context.Request.Path.Value;
 if (path.Contains(@"uritest"))
  {
   context.Response.Redirect(@"http://localhost:5003");
 }
 }
}

public class Startup
	{
		public Startup(IConfiguration configuration)
		{
			Configuration = configuration;
		}

		public IConfiguration Configuration { get; }

		// This method gets called by the runtime. Use this method to add services to the container.
		public void ConfigureServices(IServiceCollection services)
		{
			services.Configure<CookiePolicyOptions>(options =>
			{
				// This lambda determines whether user consent for non-essential cookies is needed for a given request.
				options.CheckConsentNeeded = context => true;
				options.MinimumSameSitePolicy = SameSiteMode.None;
			});


			services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);

			services.Configure<ForwardedHeadersOptions>(options =>
			{
				//options.ForwardLimit = 4;
				//options.KnownProxies.Add(IPAddress.Parse("127.0.10.1"));
				//options.ForwardedForHeaderName = "X-Forwarded-For-My-Custom-Header-Name";
				options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedHost;
			});
		}

		// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
		public void Configure(IApplicationBuilder app, IHostingEnvironment env)
		{
			app.UseForwardedHeaders();
			app.UseMiddleware<RedirectHandlingMiddleware>();
			if (env.IsDevelopment())
			{
				app.UseDeveloperExceptionPage();
			}
			else
			{
				app.UseExceptionHandler("/Error");
				// The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
				app.UseHsts();
			}

			//app.UseHttpsRedirection();
			//app.UseStaticFiles();
			//app.UseCookiePolicy();

			//app.UseMvc();

			app.Map("/testurl", builder =>
			{
				app.UseForwardedHeaders();
				//app.UseMiddleware<IdentityServerUrlMiddleware>(@"http://win2016/IdentityServer4", @"/IdentityServer4");
				//app.UseMiddleware<IdentityServerUrlMiddleware>(@"http://win2016", string.Empty);
				//builder.UseCors("CorsPolicy");
				//builder.UseForwardedHeaders(fordwardedHeaderOptions);
				builder.UseStaticFiles();
				builder.UseMvcWithDefaultRoute();
				builder.UseMvc(routes =>
				{
					routes.MapRoute(
				  name: "default",
				  template: "connect/{action=Index}/{id?}",
				  defaults: new { Controller = "Connect" });
				});
			});
		}
	}

```
Redirect rule
`<rule name="Redirect test" enabled="true" stopProcessing="true">
<match url="^testurl/(.*)" />
<conditions logicalGrouping="MatchAll" trackAllCaptures="false" />
<action type="Rewrite" url="http://win2016:5300/{R:0}" logRewrittenUrl="true" />
</rule>`
![chrome](https://user-images.githubusercontent.com/51368706/58960491-f7ec5d00-87af-11e9-96db-b38cebaf48d2.jpg)
[TestRedirect.zip](https://github.com/IdentityServer/IdentityServer4/files/3257424/TestRedirect.zip)

**Comment by marcBalta** [comment]
I fixed the problem now. Actually it is not a problem of IdenityServer, nor a problem of asp.net core.

I used a packet sniffer and noticed that indeed the identiyserver doesnt modify the redirect url: The response packet which is a http redirect (http 302 code) was emitted with the correct redirect url to the reverse proxy. When it was however forwarded to the client (the browser) the redirect url was changed.

To fix this problem you have to uncheck the "Reverse rewritehost in response headers" option in the Server Proxy Settings inside the module. When it is checked the domain of the url inside the Location Header of a redirect http packet will be exchanged with the domain of the reverse proxy.
