### ISSUE TITLE
How to issue multiple role claims?

### ISSUE THREAD

**Issue by ksj2209** [IdentityServer/IdentityServer4#331]
I have configured an IdentityServer with a custom IProfileService which issues a number of role claims.

These claims are constructed using the microsoft claim type for roles, which should allow me to use User.IsInRole() to check for membership of roles.

The problem is that IdentityServer issues the role claims as follows:

ht<span>tp://</span>schema.microsoft.com/ws/2008/06/identity/claims/role: ["Role1", "Role2", "Role3"]

This representation does not seem to work with the ClaimsPrincipal in System.Security.Claims which returns false on IsInRole when checking for a specific role.

Is there a workaround to either create separate entries for each role, or to make the array representation work with ClaimsPrincipal?

**Comment by brockallen** [comment]
It's a Microsoft bug in the OIDC middleware: https://github.com/aspnet/Security/issues/976

**Comment by leastprivilege** [comment]
They fixed it by now - either use their nightlies - or wait for the next release. closing.
