### ISSUE TITLE
Communicating with IdentityServer4 with Owin Startup class in Asp.Net WebForms

### ISSUE THREAD

**Issue by cybercop** [IdentityServer/IdentityServer4#3310]
I am trying to get currently logged in User in IdentityServer4 from my Asp.Net webforms application.

Since there is no example for WebForms project, I am using example from IdentityServer3 provided in [GitHub repo of IdentityServer][1]

Here is the `client config in IdentityServer4` project

            new Client
            {
                ClientId = "Foo",
                ClientName = "Foo",
                ClientSecrets =
                {
                    new Secret("Secret".Sha256())
                },
                AllowedGrantTypes = GrantTypes.Implicit,
                AllowOfflineAccess = true,
                RequirePkce = false,
                RequireClientSecret = false,
                RequireConsent = false,
                RedirectUris = redirectUris,
                PostLogoutRedirectUris = postLogoutRedirectUris,
                BackChannelLogoutUri = "https://localhost/LogOff",
                AllowedCorsOrigins = allowedCorsOrigins,
                AlwaysIncludeUserClaimsInIdToken = true,
                AllowedScopes =
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    IdentityServerConstants.StandardScopes.OfflineAccess,
                    "firstName",
                    "lastName",
                    "emailId",
                    "api1"
                }
            }

Here is the startup class in Asp.Net webForms project

```
using System;
using System.Threading.Tasks;
using Microsoft.Owin;
using Microsoft.Owin.Extensions;
using Owin;
using System.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.OpenIdConnect;
using System.Linq;
using System.Security.Claims;
using IdentityModel.Client;
using Microsoft.IdentityModel.Protocols;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;

[assembly: OwinStartup(typeof(Client.Startup))]

namespace Client
{
    public class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            app.UseCookieAuthentication(new CookieAuthenticationOptions()
            {
                AuthenticationType = "Cookies",
                ExpireTimeSpan = TimeSpan.FromMinutes(10),
                SlidingExpiration = true
            });

            var tokenHandler = new JwtSecurityTokenHandler();
            tokenHandler.InboundClaimFilter.Clear();

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                AuthenticationType = "oidc",
                SignInAsAuthenticationType = "Cookies",
                Authority = "https://localhost:44367",
                ClientId = EP_Configuration.epIdpClientId,
                RedirectUri = "https://localhost/callback",
                PostLogoutRedirectUri = "https://localhost/LogOff",
                ResponseType = "id_token token",
                Scope = "openid profile emailId",
                UseTokenLifetime = false,
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = async n =>
                    {
                        var claims_to_exclude = new[]
                        {
                            "aud", "iss", "nbf", "exp", "nonce", "iat", "at_hash"
                        };

                        var claims_to_keep =
                            n.AuthenticationTicket.Identity.Claims.Where(x => false == claims_to_exclude.Contains(x.Type)).ToList();
                        claims_to_keep.Add(new Claim("id_token", n.ProtocolMessage.IdToken));
                        if (n.ProtocolMessage.AccessToken != null)
                        {
                            claims_to_keep.Add(new Claim("access_token", n.ProtocolMessage.AccessToken));

                            var userInfoClient = new UserInfoClient(EP_Configuration.epIdpUserInfoAccessPoint);
                            var userInfoResponse = await userInfoClient.GetAsync(n.ProtocolMessage.AccessToken);
                            var userInfoClaims = userInfoResponse.Claims; // filter sub since we're already getting it from id_token
                            claims_to_keep.AddRange(userInfoClaims);
                        }

                        var ci = new ClaimsIdentity(
                            n.AuthenticationTicket.Identity.AuthenticationType, "name","role");
                        ci.AddClaims(claims_to_keep);
                        n.AuthenticationTicket = new Microsoft.Owin.Security.AuthenticationTicket(
                            ci, n.AuthenticationTicket.Properties
                        );
                    },
                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)
                        {
                            var id_token = n.OwinContext.Authentication.User.FindFirst("id_token")?.Value;
                            n.ProtocolMessage.IdTokenHint = id_token;
                        }

                        return Task.FromResult(0);
                    }
                }
            });
            app.UseStageMarker(PipelineStage.Authenticate);
        }
    }
}
```

A user is loggedIn, in IdentityServer as shown in image below,

[![1][2]][2]

But Currentuser does not seem to be getting any claims and IsAuthenticated is false

        void Application_PostAcquireRequestState(object sender, EventArgs e)
        {
            // now you can fix up you session object from
            // if you use session state (which makes me sad if you do)
            var cp = (ClaimsPrincipal)HttpContext.Current.User;
        }

[![enter image description here][3]][3]

Any idea how I can make my startup to work and, get currently logged in User in IdentityServer in Asp.Net webforms project from server side.

PS: Looks like WebForm client is not calling IdentityServer at all. Log file of identity server does not contain any update when I run the client application

Here is the log file of IdentityServer

    2019-06-03 16:36:05.074 +02:00 [INF] Starting IdentityServer4 version 2.3.2.0
    2019-06-03 16:36:05.119 +02:00 [INF] You are using the in-memory version of the persisted grant store. This will store consent decisions, authorization codes, refresh and reference tokens in memory only. If you are using any of those features in production, you want to switch to a different store implementation.
    2019-06-03 16:36:05.126 +02:00 [INF] Using the default authentication scheme idsrv for IdentityServer
    2019-06-03 16:36:05.126 +02:00 [DBG] Using idsrv as default ASP.NET Core scheme for authentication
    2019-06-03 16:36:05.126 +02:00 [DBG] Using idsrv as default ASP.NET Core scheme for sign-in
    2019-06-03 16:36:05.126 +02:00 [DBG] Using idsrv as default ASP.NET Core scheme for sign-out
    2019-06-03 16:36:05.126 +02:00 [DBG] Using idsrv as default ASP.NET Core scheme for challenge
    2019-06-03 16:36:05.126 +02:00 [DBG] Using idsrv as default ASP.NET Core scheme for forbid
    2019-06-03 16:36:05.437 +02:00 [DBG] Login Url: /Account/Login
    2019-06-03 16:36:05.438 +02:00 [DBG] Login Return Url Parameter: ReturnUrl
    2019-06-03 16:36:05.439 +02:00 [DBG] Logout Url: /Account/Logout
    2019-06-03 16:36:05.439 +02:00 [DBG] ConsentUrl Url: /consent
    2019-06-03 16:36:05.439 +02:00 [DBG] Consent Return Url Parameter: returnUrl
    2019-06-03 16:36:05.439 +02:00 [DBG] Error Url: /home/error
    2019-06-03 16:36:05.439 +02:00 [DBG] Error Id Parameter: errorId

  [1]: https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/WebFormsClient/Startup.cs
  [2]: https://i.stack.imgur.com/f8rjO.jpg
  [3]: https://i.stack.imgur.com/US6H1.jpg

**Comment by Texbase** [comment]
What version of .NET are you running for WebForms application? Are you using OWIN? We have it working in our legacy WebForms application running .NET 4.x with OWIN.

Make sure you're allowing anonymous access to the WebForms application. 

i.e.
<system.web>
         <authorization>
            <allow users="?"/>
         </authorization>
</system.web>

**Comment by cybercop** [comment]
@Texbase I am using .NET 4.7.1
I made sure I am allowing anonymous access to WebForm app 

Here are the packages version I am using 
` <package id="IdentityModel" version="3.10.10" targetFramework="net471" />
  <package id="Microsoft.AspNet.FriendlyUrls" version="1.0.2" targetFramework="net471" />
  <package id="Microsoft.AspNet.FriendlyUrls.Core" version="1.0.2" targetFramework="net471" />
  <package id="Microsoft.AspNet.FriendlyUrls.Core.de" version="1.0.2" targetFramework="net471" />
  <package id="Microsoft.AspNet.ScriptManager.MSAjax" version="5.0.0" targetFramework="net471" />
  <package id="Microsoft.AspNet.ScriptManager.WebForms" version="5.0.0" targetFramework="net471" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net471" />
  <package id="Microsoft.AspNet.Web.Optimization.de" version="1.1.3" targetFramework="net471" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="2.0.0" targetFramework="net471" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="5.3.0" targetFramework="net471" />
  <package id="Microsoft.IdentityModel.Logging" version="5.3.0" targetFramework="net471" />
  <package id="Microsoft.IdentityModel.Protocols" version="5.3.0" targetFramework="net471" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.3.0" targetFramework="net471" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.3.0" targetFramework="net471" />
  <package id="Microsoft.Owin" version="4.0.1" targetFramework="net471" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.0.1" targetFramework="net471" />
  <package id="Microsoft.Owin.Security" version="4.0.1" targetFramework="net471" />
  <package id="Microsoft.Owin.Security.Cookies" version="3.0.1" targetFramework="net471" />
  <package id="Microsoft.Owin.Security.OpenIdConnect" version="4.0.1" targetFramework="net471" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net471" />
  <package id="Owin" version="1.0" targetFramework="net471" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.3.0" targetFramework="net471" />`

Still I am getting IsAuthenticated false

**Comment by Texbase** [comment]
I'd move this to https://stackoverflow.com/ since it is more of a configuration issue vs. an issue w/IdServer.

Some additional thoughts...

1. Do you have these web.config AppSettings:
`    <add key="owin:AutomaticAppStartup" value="true"/>`
`    <add key="owin:AppStartup" value="{yourNamespace}.Startup"/>`
2. Do you have your StartUp.cs Namespace decorated with this:
`<Assembly: OwinStartup(GetType({yourNamespace}.Startup))>`

**Comment by cybercop** [comment]
@Texbase I already did ask there

https://stackoverflow.com/questions/56426073/communicating-with-identityserver4-with-owin-startup-class-in-asp-net-webforms

**Comment by Texbase** [comment]
Sounds to me like you need some consultation via a screen share to speed this up and avoid the back and forth.

**Comment by cybercop** [comment]
@Texbase Ok who can help me and when?

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/latest/intro/support.html#commercial-support
