### ISSUE TITLE
Support for Apple Sign In

### ISSUE THREAD

**Issue by ghuntley** [IdentityServer/IdentityServer4#3312]
Opening up an epic for discussion. Technical details are vauge at this time.

**Describe alternatives you've considered**

Sign In with Apple will be available for beta testing this summer. *It will be required as an option* for users in apps that support third-party sign-in when it is commercially available later this year.

**Additional context**

- https://t.co/qen34RLGOW?amp=1
- https://twitter.com/GeoffreyHuntley/status/1135722231919628288

**Comment by brockallen** [comment]
i hope you're trolling :)

**Comment by ghuntley** [comment]
Kinda, sorta. It was only a matter of time before someone opened up this topic of discussion so why not a friendly face? :-)

**Comment by ryanmendoza** [comment]
> _It will be required as an option_ for users in apps that support third-party sign-in when it is commercially available later this year.

Sounds like you better hurry up and configure your external provider 😁

**Comment by leastprivilege** [comment]
**Almost** spec compliant - looks like code flow without PKCE to me.


* https://developer.apple.com/sign-in-with-apple/get-started/
* https://github.com/aaronpk/sign-in-with-apple-example/blob/master/index.php

**Comment by leastprivilege** [comment]
That's a job for @pinpointtownes

**Comment by PinpointTownes** [comment]
> That's a job for @PinpointTownes

Feel free to open a ticket, or better, directly send a PR 😄 

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers

**Comment by leastprivilege** [comment]
done ;)
