### ISSUE TITLE
How to Register gRPC endpoint as client app?

### ISSUE THREAD

**Issue by maulik-modi** [IdentityServer/IdentityServer4#3314]
Hi team,

I would like to know what it would take to register gRPC Server endpoint as client app in IdentityServer.
https://docs.microsoft.com/en-us/aspnet/core/tutorials/grpc/grpc-start?view=aspnetcore-3.0&tabs=visual-studio

Thanks,
Maulik.

**Comment by leastprivilege** [comment]
Does this help: https://damienbod.com/2019/03/06/security-experiments-with-grpc-and-asp-net-core-3-0/ ?

**Comment by brockallen** [comment]
Any update?
