### ISSUE TITLE
build.ps1 is not digitally signed.

### ISSUE THREAD

**Issue by LindaLawton** [IdentityServer/IdentityServer4#3315]
### Issue / Steps to reproduce the problem

I just tried to run the .\build.ps1 It pops up with this message.

![image](https://user-images.githubusercontent.com/6592543/58887611-33baf000-86e6-11e9-8788-9d6afd77ca8f.png)

### Solution

Googled my way to a solution. 
[Fix for PowerShell Script Not Digitally Signed](http://tritoneco.com/2014/02/21/fix-for-powershell-script-not-digitally-signed/)

>Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

Do we want to sign this. I am happy to do it but I suspect the signing certificate would have to be add to the build process and saved by you guys some place.

I almost think it would be easier to just add a note in the readme for now and how to deal with the error.

**Comment by leastprivilege** [comment]
It is pretty much standard procedure to turn off the signature check (e.g. when you put your Windows machine in "developer mode"). I think the policy you want is called "RemoteSigned" IIRC.

**Comment by LindaLawton** [comment]
close this then if you don't want to do anything about it.

I will just go figure out how to turn it off

**Comment by leastprivilege** [comment]
Maybe you find a good link somewhere to include...

I typically do it via 

<img width="1194" alt="Screenshot 2019-06-05 13 02 43" src="https://user-images.githubusercontent.com/1454075/58951784-4e4aa300-8792-11e9-8d49-d1d03b497f97.png">

**Comment by brockallen** [comment]
Any update?
