### ISSUE TITLE
Is possible to show a loading progress after the login screen?

### ISSUE THREAD

**Issue by filipefelice** [IdentityServer/IdentityServer4#3316]
Hi, my users are seeing a blank page after login, it takes almost 1 second in connect/authorize page before redirect to client authorized uri. 

I think it occurs because i have some **customs functionalities** in **GetProfileData** and **Validate** functions that takes some time. 

Is there a way how I could show a **loading page** during this step? 

Thanks!

**Comment by brockallen** [comment]
We tried to in the QS UI on these lines of code: https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/host/Quickstart/Account/AccountController.cs#L138

If you have a better idea on how to improve it please let us know.

**Comment by brockallen** [comment]
For now, you will have to add your own custom code in the UI to address. In the future, we will do something better: #3407.

**Comment by filipefelice** [comment]
Ok Brock, Thank you!
