### ISSUE TITLE
Device Auth Tokens Expired b/c of Timezone Issue

### ISSUE THREAD

**Issue by enzian** [IdentityServer/IdentityServer4#3319]
When a device code is requested, it is marked with the creation time (`DeviceAuthorizationResponseGenerator.cs`). This is a `DateTime` and the issue is, when we compare a `DateTime` with a `DateTimeOffset` in `DeviceCodeValidator.cs` like this:
```
            // validate lifetime
            if (deviceCode.CreationTime.AddSeconds(deviceCode.Lifetime) < _systemClock.UtcNow)
            {
                _logger.LogError("Expired device code");
                context.Result = new TokenRequestValidationResult(context.Request, OidcConstants.TokenErrors.ExpiredToken);
                return;
            }
```
This means that the left side of the comparison will be implicitly cast to a `DateTimeOffset` and if that happens to occur on a system in another timezone the comparison will be offset by the difference in time zones to GMT an thus potentially (almost certainly) fail!

Solution: The `TimeSpan` on the left side is created in UTC so we could compare the Ticks with the `DateTimeOffset` from the system clock!

**Comment by scottbrady91** [comment]
I'm struggling to replicate this. Have you seen this in production? And to confirm, you are definitely storing CreationTime in UTC?

Do you have something to reproduce the error?

Note also that the same style time comparison check is used throughout IdentityServer4.

**Comment by enzian** [comment]
switch your cultures time zone settings to CEST, create a device flow client with a device core lifetime of 300 and create the token, do the challenge and try to get the token and you'll get:

```json
{
    "error": "expired_token"
}
```

**Comment by scottbrady91** [comment]
Still no luck. I've set my machines timezone to CEST (and confirmed by checking `DateTime.Now`), but I cannot replicate your issue. This is using the test host found in the core IdentityServer4 repo.

What store are you using for device codes? Does the same time comparison issue happen for authorization codes? Do you have anything else that could help me replicate your issue?

**Comment by enzian** [comment]
@scottbrady91: sorry for sending you on that wild goose chase :-( It turns out, the persistence layer messed this up - as you suggested: It stored time in Ticks and restored them through the constructor `DateTime(long ticks)` and that messed up the timing. 

Storing the time using `DateTime.ToFileTimeUtc()` and restoring it using `DateTime.FromFileTimeUtc()` solved the issue! Thanks for the hint!
