### ISSUE TITLE
How to return custom http status code while using IResourceOwnerPasswordValidator

### ISSUE THREAD

**Issue by avoxm** [IdentityServer/IdentityServer4#332]
I have implemented `IResourceOwnerPasswordValidator` for user credentials validation.

In `ValidateAsync` I check whether user with the provided username exists and if yes I validate the password. I need to show a user 2 different messages when user does not exist and when it exists but the password is incorrect, so I am thinking to return 2 different status codes (or any other indicator that does not rely on response message) for each case. Please see the sample code below.

```
public Task<CustomGrantValidationResult> ValidateAsync(string userName, string password, ValidatedTokenRequest request)
{
    var user = _repository.FindByUsername(userName);

    if (user == null)
    {
        //return 404
        return Task.FromResult(new CustomGrantValidationResult("Invalid username"));
    }

    if (IsValidPassword(password))
    {
        var result = new CustomGrantValidationResult(user.Id.ToString(), "password", user.Claims, "idsrv");
        return Task.FromResult(result);
    }

    // return 401
    return Task.FromResult(new CustomGrantValidationResult("Invalid password"));
}
```

**Comment by brockallen** [comment]
The spec is clear about what status codes are expected for what conditions: https://tools.ietf.org/html/rfc6749#section-4.3.3

**Comment by avoxm** [comment]
Thanks for your feedback @brockallen. What about setting http status code. Is there a way to do it. As per spec authorization server must be able to set other code than 400. How can I do it in ValidateAsync ?

**Comment by brockallen** [comment]
We don't give you a way. You return the grant validation result and we set the appropriate status code. You can set the description on it and we will pass that back to the client.

**Comment by avoxm** [comment]
I guess that leaves me with only error description. Thanks

**Comment by loukaspd** [comment]
@brockallen
> The spec is clear about what status codes are expected for what conditions: https://tools.ietf.org/html/rfc6749#section-4.3.3
> 
> IIRC we added support for returning an error description... i'd have to double check.

I tried sending Basic Authorization header with wrong value and got 400 instead of 401 as mentioned in 
https://tools.ietf.org/html/rfc6749#section-5.2 : 
If client attempted to authenticate via the "Authorization" request header field, the authorization server MUST respond with an HTTP 401 (Unauthorized) status code and include the "WWW-Authenticate" response header field matching the authentication scheme used by the client.

**Comment by brockallen** [comment]
@loukaspd if you have uncovered a new problem/bug, then please open a new issue
