### ISSUE TITLE
Include identity resource properties in GetAllResourcesAsync

### ISSUE THREAD

**Issue by Brice-xCIT** [IdentityServer/IdentityServer4#3320]
**Is your feature request related to a problem? Please describe.**
It's impossible to retrieve all properties for all identity resources (ResourceStore.GetAllResourcesAsync includes properties for api resources but not for identity resources: https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Stores/ResourceStore.cs#L136)

**Describe the solution you'd like**
It would be more consistent and easier to have ResourceStore.GetAllResourcesAsync include the properties for identity resources, just like it does for api resources. 

**Describe alternatives you've considered**
There is no alternative for this specific use case besides querying the underlying stores directly.

**Comment by brockallen** [comment]
Done. Thanks for letting us know.
