### ISSUE TITLE
Make Client.*Lifetime properties TimeSpans and allow sub-second times

### ISSUE THREAD

**Issue by loop-evgeny** [IdentityServer/IdentityServer4#3321]
**Is your feature request related to a problem? Please describe.**
`Client.AccessTokenLifetime` cannot be set to less than one second. A sub-second lifetime might seem silly at first, but it's useful for unit tests.

**Describe the solution you'd like**
Make all `Client.*Lifetime` properties TimeSpans instead of ints.

**Additional context**
In addition to allowing sub-second time, a TimeSpan is a clearer way of representing time - there is less chance of a developer confusing the units (e.g. thinking it's in milliseconds) or writing the wrong number of zeros.

This would, of course, be a breaking change (though easy to fix).

**Comment by leastprivilege** [comment]
This would be a breaking change. We will consider it for the next major version

**Comment by leastprivilege** [comment]
We should check all lifetimes and make them consistently a TimeSpan

**Comment by leastprivilege** [comment]
This is too much of a breaking change.

**Comment by loop-evgeny** [comment]
Really, even for a major version? Seems pretty easy to update the calling code.
