### ISSUE TITLE
www-authenticate Header set error segment to ExpiredToken

### ISSUE THREAD

**Issue by ste2425** [IdentityServer/IdentityServer4#3322]
**Is your feature request related to a problem? Please describe.**
Within the browser i make API calls to a server. Should my token expire the JS makes a request to refresh the token.

In order to decide if requesting a refresh is required the JS parses the `www-authenticate` header.

Looking at the source code here: https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/IdentityServer4/src/Endpoints/Results/ProtectedResourceErrorResult.cs#L36

ID Server explicitly changes the error type to a more generic `invalid-token` if the error is `token-expired`. This means the JS has to instead check the more brittle error description to see if the token has expired.

**Describe the solution you'd like**
Leave the error type to be expired token in the situation where the token has expired.

**Additional context**
I guess i have a lack of understanding as to why the decision was made to bundle expired tokens under the same type as other generic token errors. 

However to me as a consumer it seems less than ideal to have to check the error description against a specific string to know the token has expired when internal to ID server there is a specific error type to handle this. That error type should be exposed for public consumption.

**Comment by ste2425** [comment]
Always the way that literally as i press `submit` i have somewhat of a light-bulb moment. Anyway technically you could argue when ever you have any issue with a token you need to request a new one. 

As only `401` appears to be returned should there be any issue with the token then that is the only thing that needs to be checked in this scenario. 

I will leave the issue open for now as I'm curious as to why the decision was still made regarding the error type.

**Comment by TomCJones** [comment]
As a general rule it is a bad idea to give an attacker any information that will help them to improve their attack.

**Comment by leastprivilege** [comment]
Yes we are deliberately generic here - as Tom already said.
