### ISSUE TITLE
Not able to access added API endpoint from client application.

### ISSUE THREAD

**Issue by jwize** [IdentityServer/IdentityServer4#3323]
Forgive me for being new. I have been able to setup the server and do basic operations such as logging in and consenting applications. I have also been able to logout using IdentityModel library. 

Following along with the documentation on "Adding more API Endpoints" I have added a controller called LocalApiController. Now, I want to call this and return some data from the running identity server. When, I am not using an authorize attribute the call is simply http://localhost:5000/localapi my IActionResult returns "Hello World" as expected. 

Calling the logout was a challenge since everything was new but eventually I came across IdentityModel helper library and used the following code.

`    
    public ActionResult LogOff(String redirectUri)
    {
        var identity = (User?.Identity as ClaimsIdentity);
        var idTokenHint = identity.FindFirst("id_token").Value;
        var url = new 
             RequestUrl("http://localhost:5000/connect/endsession")
            .CreateEndSessionUrl(idTokenHint,  redirectUri);
        return Redirect(url);
    }
`
The url looks something like http://localhost:5000/connect/endsession?id_token_hint=<token>.

As soon as I add the `[Authorize(IdentityServerConstants.LocalApi.PolicyName)]` attribute to the LocalApiController I start getting a 401 when I send requests. 

How can I authorized the LocalApiRequest from my client applciations. I tried sending a request with the token hint(http://localhost:5000/localapi?id_token_hint=<token>) but obviously it was a naive attempt to get authorization to work properly.

Any help would be great!

**Comment by leastprivilege** [comment]
You would send your access token via the authorization header.

https://tools.ietf.org/html/rfc6750
