### ISSUE TITLE
one claim has the same value within my access_token 

### ISSUE THREAD

**Issue by zpc870921** [IdentityServer/IdentityServer4#3324]
below is my access_token

eyJhbGciOiJSUzI1NiIsImtpZCI6ImFkOTA5NWE4N2Q0ZDFkNDY3ODJjZTFmZDMzMjVmMjUxIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1NTk5OTgxNjQsImV4cCI6MTU2MDAwMTc2NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJzb2NpYWxuZXR3b3JrIl0sImNsaWVudF9pZCI6Im12Y19jb2RlIiwiZ2VuZGVyIjoibWFsZSIsInN1YiI6IjI2OTY5OTA2LWVjYWItNDU2NS1hZWY2LTBlNjQ0ZTVlMTljZCIsImF1dGhfdGltZSI6MTU1OTk5ODE1OCwiaWRwIjoibG9jYWwiLCJlbWFpbCI6WyI0NDI4MSIsIjQ0MjgxIl0sInJvbGUiOlsidXNlciIsInVzZXIiXSwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIiwicm9sZXMiLCJzb2NpYWxuZXR3b3JrIiwiYXBpLnJlYWQiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsicHdkIl19.Waba4BNiUUYDWFUBtrx2KfpC69UVmKoLw5qjz4TLFxCUOOVWNC3xfuyMGLbuwjcjSKknfY6mxjY-DpceJkCc3aLraHB5j7-4-5Ja6DiDyXRQ8dpN8fGjcX5PFGIwzYWMQ1qkC5GxX3WxTtonV_RZtPDiRaLofUcFjrdQr6je0zgF7lKgv-zMZwWTz9d188Z-q__28lKFkXyjz1O7vGCgN_9fHiu9VrD5OG0mANkmzErKWXyA5QJzAg-HIfKnIDAUWWMf3WXhZNqljthywuV5ZccPuAf7ndHZu76r2kbaHx_2qB5cakBso148pt-kGP0Y-vJtNpIWgjRPz50cWZr4pA

please tell me is this a bug? thanks

**Comment by brockallen** [comment]
Depends how you've written your profile service.

**Comment by zpc870921** [comment]
@brockallen 
i use the identityserver4 + asp.net core identity ,  below is adduser method , i guess the problem is here


`  var result= await _userManager.CreateAsync(user, login.Password);
                var claims = new[]
                {
                    new Claim(JwtClaimTypes.Name,user.UserName),
                    new Claim(JwtClaimTypes.GivenName, user.UserName),
                    new Claim(JwtClaimTypes.FamilyName, user.UserName),
                    new Claim(JwtClaimTypes.Email,user.Email),
                   /new Claim(JwtClaimTypes.Role,login.UserName=="443813032@qq.com"?"admin":"user")
                };
                result= await _userManager.AddClaimsAsync(user, claims);
                result= await _userManager.AddToRoleAsync(user, login.UserName == "443813032@qq.com"? "admin" : "user");
                await _signInManager.PasswordSignInAsync(user, login.Password, false, false);`
