### ISSUE TITLE
Microsoft login Correlation Failed error

### ISSUE THREAD

**Issue by paulguz** [IdentityServer/IdentityServer4#3326]
This is an easily reproducible error using the vanilla IdentityServer demo projects.

During the Microsoft external login process, if already authenticated, there is a pause before the redirect back to the return url.  

During that pause, the user is free to click on their username.  Doing so appears to upset the flow and causes a Correlation Failed error.  

Our users are repeatedly falling in to this trap.

Now, I know this is a problem caused by something in the Microsoft flow (and I have already raised it with them the best I can), but is there anything than can be done to _prevent_ this in IdentityServer? I am already handling the error via OnRemoteFailure, but I'd rather stop at happening.

**Comment by leastprivilege** [comment]
We rely on the Microsoft handler - did you get any response?

**Comment by paulguz** [comment]
Sadly no.

**Comment by hugoqribeiro** [comment]
This is something that was changed recently by MS.

One way to fix it is to add the following when redirecting to the authorization endpoint:

`&prompt=select_account`

**Comment by paulguz** [comment]
Thanks @hugoqribeiro, that works.

I found the [documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code) on the MS authorization endpoint, where that parameter is documented: 

> select_account: The user is prompted to select an account, interrupting single sign on. The user may select an existing signed-in account, enter their credentials for a remembered account, or choose to use a different account altogether.

I was able to add the parameter in the `OnRedirectToAuthorizationEndpoint` handler amongst the MicrosoftAccountOptions like so:

```
var existingOnRedirectToAuthorizationEndpoint = options.Events.OnRedirectToAuthorizationEndpoint;
options.Events.OnRedirectToAuthorizationEndpoint = opts =>
{
   opts.RedirectUri += "&prompt=select_account"; 

   return existingOnRedirectToAuthorizationEndpoint(opts);
};
```

(I'd love it if there were a prompt option to show no prompt at all if the user is already authenticated, but this will do!)
