### ISSUE TITLE
idsrv.session cookie : secure security control attribute in the set-cookie header

### ISSUE THREAD

**Issue by fcavaco** [IdentityServer/IdentityServer4#3327]
hello, 

Tried to browse through documentation and got nowhere...
I've currently a pentest report were am asked to present on my idsrv reponse a set-cookie header passing "secure" as true for the idsrv.session cookie. 
but... have been unable to find how to do so? is this only achieved through configuration out of the code somewhere?

my dev env:
asp.net core 2.2 (asp.net identity)
IdentityServer4
F#

been able to set cookie options easily for the asp.net core identity cookie, so was expecting, probably wrongly, to find something similar for this cookie ..?!

```
 builder.Services.Configure<CookieAuthenticationOptions>(IdentityConstants.ApplicationScheme,fun (cookie:CookieAuthenticationOptions) ->
                                                                        cookie.Cookie.SameSite <- Microsoft.AspNetCore.Http.SameSiteMode.None 
                                                                        cookie.Cookie.HttpOnly <- true
                                                                        cookie.Cookie.SecurePolicy <- Microsoft.AspNetCore.Http.CookieSecurePolicy.Always

```

**Comment by brockallen** [comment]
That cookie is issued as `secure` if the request is over https.
