### ISSUE TITLE
IdentityToken not generated in Hybrid type

### ISSUE THREAD

**Issue by Ram-97** [IdentityServer/IdentityServer4#3328]
with reference- http://docs.identityserver.io/en/latest/topics/grant_types.html
Hybrid Grant type is a combination of  implicit and authorization code. Implict grant type generates a id token with customized user claims then why hybrid doesn't adds the claims to id token.

ProfileService.cs

        public virtual Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            context.LogProfileRequest(Logger);
            var user = Users.FindBySubjectId(context.Subject.GetSubjectId());
            if (user != null)
            {
                var claims = Users.GetUserClaims(context.Subject.GetSubjectId());
                context.IssuedClaims.AddRange(claims);
            }
            context.LogIssuedClaims(Logger);
            return Task.CompletedTask;
        }

UserStore.cs

        public User FindBySubjectId(string subjectId)
        {
             return _context.Users.FirstOrDefault(x => x.SubjectId == subjectId);
        }

        public List<Claim> GetUserClaims(string subjectId)
        {
            var user= FindBySubjectId(subjectId);
            List<Claim> claims = new List<Claim>() {
                new Claim(JwtClaimTypes.Email,user.Email),
                new Claim(JwtClaimTypes.PhoneNumber,user.Phoneno),
                new Claim(JwtClaimTypes.Name,user.Firstname),
                new Claim(JwtClaimTypes.MiddleName,user.Lastname)
                };
            return claims;
        }

`

**Comment by amccool** [comment]
of course it would be good to post your setup(startup) code to see what your configuration is.

https://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken2

appears that the spec allows for not explicitly sending all the claims in the id_token.

```
All Claims about the Authentication event present in either SHOULD be present in both. If either ID Token contains Claims about the End-User, any that are present in both SHOULD have the same values in both.

Note that the OP MAY choose to return fewer Claims about the End-User from the Authorization Endpoint, for instance, for privacy reasons. 
```

I believe you want to add `AlwaysIncludeUserClaimsInIdToken` property to the Client configuration in IdSvr4

```
            new Client
            {
                ClientId = "myspecialclient",
                ClientName = "RE RE client",
                AllowedGrantTypes = GrantTypes.Hybrid,
                AlwaysIncludeUserClaimsInIdToken = true,
```

http://docs.identityserver.io/en/latest/reference/client.html

**Comment by Ram-97** [comment]
Thanks for your response..
but sorry i still don't get your point. I'm a beginner.
Here's the code you asked.
Client Configuration:

         public static IEnumerable<Client> GetClients()
        {
            return new List<Client>
                {
                new Client
                {
                    ClientId = "mvc",
                    ClientName = "MVC Client",
                    ClientSecrets={ new Secret("secret".Sha256())},
                    AllowedGrantTypes = GrantTypes.Hybrid,
                    RequireConsent=false,
                    RedirectUris = { "http://localhost:5001/signin-oidc"
                },
                PostLogoutRedirectUris = { "http://localhost:5001/signout-callback-oidc" },
                AllowedScopes = new List<string>
                {
                    IdentityServerConstants.StandardScopes.OpenId,
                    IdentityServerConstants.StandardScopes.Profile,
                    "api1"
                },
                AllowOfflineAccess = true
                }
            };
        }

**Comment by leastprivilege** [comment]
Does this help

https://leastprivilege.com/2016/12/14/optimizing-identity-tokens-for-size/

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by Ram-97** [comment]
It works.Thank you all
