### ISSUE TITLE
[Device Flow] Token response does not contain "scope" property

### ISSUE THREAD

**Issue by dudedev** [IdentityServer/IdentityServer4#3329]
We are using IdentityServer4 library v2.4.0 to build our Authorization Server. We implemented/enabled the device code flow. We noticed that the token response does not contain "scope" property if user has not consented to all requested scopes. However, according to the [RFC6749 section 5.1](https://tools.ietf.org/html/rfc6749#section-5.1), the "scope" property is "required" if consented scopes are different than requested scopes.

We also verified this against the demo server provided by you.

Do you plan to implement this feature soon?

**Comment by brockallen** [comment]
Please have a look @scottbrady91.

**Comment by scottbrady91** [comment]
@brockallen Device flow sets the authorized scopes, but I'm not seeing scope returned from the token endpoint at all: https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Endpoints/Results/TokenResult.cs#L52

**Comment by scottbrady91** [comment]
So, scope is defined as a parameter on the token endpoint in the original OAuth spec. Would that ever be necessary outside of device flow?

**Comment by scottbrady91** [comment]
@brockallen ping?

**Comment by brockallen** [comment]
Dp we have a unit test that shows the expected result, but should be failing if the report is correct? That's the best way to go about repo'ing and then fixing.

**Comment by brockallen** [comment]
merged.
