### ISSUE TITLE
Am getting the following error in the latest version of IdentityServer4 in ASP Core, "Constants variable cannot be accessed due to its protection level" at Constants.BuiltInIdentityProvider. I get the error while using the latest package of IdentityServer4 but not getting it in "IdentityServer4": "1.0.0-beta4-update2" package? Has the functionality of accessing the identity provider of a claim type changed? Sorry for the poor formatting.

### ISSUE THREAD

**Issue by mykeadam** [IdentityServer/IdentityServer4#333]
public override async Task SignInAsync(TUser user, AuthenticationProperties authenticationProperties, string authenticationMethod = null)
        {
            var userPrincipal = await CreateUserPrincipalAsync(user);

            userPrincipal.Identities.First().AddClaims(new  []
            {
                new Claim(JwtClaimTypes.IdentityProvider, authenticationMethod ?? **Constants.BuiltInIdentityProvider**), 
                new Claim(JwtClaimTypes.AuthenticationTime, DateTime.UtcNow.ToEpochTime().ToString())
            });

            await Context.Authentication.SignInAsync(options.Cookies.ApplicationCookieAuthenticationScheme,
                userPrincipal,
                authenticationProperties ?? new AuthenticationProperties());
        }

**Comment by brockallen** [comment]
`IdentityServerConstants`
