### ISSUE TITLE
Specify HTTP status code for extension grant errors

### ISSUE THREAD

**Issue by PrihodkoVladimir** [IdentityServer/IdentityServer4#3334]
I have read a similar issue: #2894.

In my case I'm implementing (UMA) 2.0 Grant for OAuth 2.0 (https://datatracker.ietf.org/doc/draft-maler-oauth-umagrant/?include_text=1) as an extension grant to IdentityServer4.
The issue is that UMA 2.0 spec requires returning HTTP 400 or 403 depending on error (section 3.3.6), but option to specify HTTP code is not available, it always returns 400 for errors.

Is there a better way than described by andrx in #2894? That approach certainly works, but I'd like to avoid copy-pasting of IdentityServer code.

**Comment by leastprivilege** [comment]
When we designed this, we used the OAuth spec which only uses 400 to convey errors. We would need to look at this for a future version.
