### ISSUE TITLE
Edge Not Saving Cookies From Signin-Oidc

### ISSUE THREAD

**Issue by dresdor** [IdentityServer/IdentityServer4#3337]
### Issue / Steps to reproduce the problem
We have an Identity Server 4 implementation and our front end application on different subdomains of the same domain (e.g. identity.somedomain.com and sales.somedomain.com).

In Chrome and Firefox, we are able to login just fine without issues.  The Authorize middleware redirects us to identity when we first reach the site, it allows us to login, redirects us back to sales, and then it succesfully authorizes and loads the page that is behind the authorize tag.

In Edge and IE11, however, it will get in a redirect loop which Edge/IE11 detects and kills.  After login, it will navigate to sales, then authorize fails and it tries to renavigate to identity, which would see it's already authorized and redirect back to sales.

I pulled the network traffic, particularly focusing on the cookies because that's a likely suspect, and found that when the redirect reaches sales/signin-oidc:

IE:

* Posts to sales/signin-oidc which responds with the authorize cookies I expect.
* Gets to sales/signin-oidc with no cookies which returns a 500 (not sure why it does this)
* Gets to sales, with no cookies, responds with a redirect to identity

Chrome:

* Posts to sales/signin-oidc which responds with the authorize cookies I expect
* Gets to sales, with the cookies, responds with the site

Edge noticeably does two things: does not set the cookies that the signin-oidc responded with, and makes an additional get call to signin-oidc.

The only major difference I see is that the chrome cookies have a samesite=lax; on them that the edge log does not have.  

What I think is happening is something is preventing edge from saving the cookies.  However, I'm at a loss for what to even look for.

Logs attached.  Please let me know what other information would be useful.  This cannot be replicated locally, only on our servers (seems like edge "trusts" the cookies if they both come from localhost)

Versions:
.Net Core 2.1
IdentityServer4.AspNetIdentity 2.3.0
IdentityServer4.EntityFramework 2.3.2
Microsoft.AspNetCore.App 2.1.8

### Relevant parts of the log file

Attached (looks like the upload ate the formatting, sorry :( )
[chrome.txt](https://github.com/IdentityServer/IdentityServer4/files/3290828/chrome.txt)
[edge.txt](https://github.com/IdentityServer/IdentityServer4/files/3290831/edge.txt)

**Comment by brockallen** [comment]
Perhaps relevant: https://brockallen.com/2019/01/11/same-site-cookies-asp-net-core-and-external-authentication-providers/
