### ISSUE TITLE
Running 2 client together from sample app. First client works fine but second client gives 400 error

### ISSUE THREAD

**Issue by ravi22saini** [IdentityServer/IdentityServer4#3338]
Running 2 client together from sample app. First client works fine but second client gives 400 error.

Steps to reproduce 
Run both app and open up login screen together try to login in both of them one by one.
First client will be logged in perfectly but second client returns 400(Screenshot attached).
![image](https://user-images.githubusercontent.com/31721143/59517617-90d25500-8ee1-11e9-9ca3-6206585f8a91.png)

**Comment by bobekhj** [comment]
Your second client is most likely miss-configured. Try adding logging to the application. Identity Server will write the error to your log file.

**Comment by ravi22saini** [comment]
Thanks @bobekhj for replying.
Firstly i am using sample code of identity server and i haven't made any change in the code.
Secondly if i try to run the second client first then it works but the first client will give me error...:-(

**Comment by leastprivilege** [comment]
dup of https://github.com/IdentityServer/IdentityServer4/issues/3339
