### ISSUE TITLE
Correlation failed :: Cookie not found

### ISSUE THREAD

**Issue by ravi22saini** [IdentityServer/IdentityServer4#3339]
if i try to open a client(for example MVCHybridBackChannel) and open up multiple tab and try to login in both tab. The first tab works fine but in case of second tab i get the following error.
![image](https://user-images.githubusercontent.com/31721143/59520940-b878eb80-8ee8-11e9-9cb1-18fa8726dd0f.png)
![image](https://user-images.githubusercontent.com/31721143/59520965-c62e7100-8ee8-11e9-9a90-ab44a57abac5.png)
Please Note:: i haven't made any change in the sample app, if you want to replicate this issue u can use the same code.
Please let me know what is the best approach in fixing this thing.

**Comment by dfrunet** [comment]
@ravi22saini, what do you mean by "try to login"? wait until it redirects to login in each tab and only after that log in each? so what you see is the normal behavior of oidc handler in asp.net. nothing specific for identity server. if that matter, it must be easy to handle in `OnAuthenticationFailed` client side.

**Comment by ravi22saini** [comment]
@dfrunet I mean when you try to access the url of client(for example MVCHybridBackChannel), you will be redirected to login page of IDP (Till this point everything works and this i know is normal behaviour) but when i provide my credentials in first tab it works fine and i am redirected by to the main page of the client. but in second tab i get this error.
to easily replicate this scenario you can try the sample code of identity server and run any client from code, once running open the login page and duplicate the tab(you will have 2 login tabs).
Now when you try to login in first it will work and you will be redirected back normally but in second tab you will get this error.

**Comment by leastprivilege** [comment]
This is the expected behavior with the Microsoft OIDC client library.

**Comment by ravi22saini** [comment]
Thank you for the revert @leastprivilege. But i want to how can we avoid this behavior, we can have multiple clients(eg MVCHybridBackChannel , MvcHybridAutomaticRefresh and so on) which might be pointing to same IDP and our user can try to access all these clients together, then they will see this error which is not what anyone would expected.
Please let me know how can we handle?

**Comment by leastprivilege** [comment]
It is by design - it's a security feature.

**Comment by ravi22saini** [comment]
Is there a way we can solve it or override it??

**Comment by leastprivilege** [comment]
Ask Microsoft what they would suggest. It is their librariy.
