### ISSUE TITLE
Detecting a prexisting authentication

### ISSUE THREAD

**Issue by gph2000** [IdentityServer/IdentityServer4#3340]
When my .NET Core site authenticates using the hybrid model, the token continues to be valid for a period.

If I shut down the site and relaunch it, how do I detect that the authentication is still valid?

I can still access the authorized areas but I would like to be able to display a logout button once authentication is detected (or indeed after it completes first time!)

**Comment by bobekhj** [comment]
The JWT access token will be valid until it expires. If you want to expire the token on demand, do not use JWT - use reference token instead: http://docs.identityserver.io/en/latest/topics/reference_tokens.html

**Comment by bobekhj** [comment]
On your View you can use `User.IsAuthenticated` check and show/hide the Logout button appropriately.

**Comment by gph2000** [comment]
Perfect, well almost. Problem solved in _Layout.cshtml using
`
        @if (User.Identity.IsAuthenticated)
        {
            <a asp-controller="Access" asp-action="Logout"
               class="btn btn-danger">Logout</a>
        }
        else
        {
            <a asp-controller="Access" asp-action="Login"
               class="btn btn-info">Login</a>

        }
`
