### ISSUE TITLE
External Authentication Azure and Windows

### ISSUE THREAD

**Issue by BBanoth** [IdentityServer/IdentityServer4#3342]
I am using Windows and Azure AD login in my IdentityServer4 application.

I am also using these logins for native mobile app which requires offline_access, 
If the access token & refresh tokens are once compromised, that person will have access to all the token eligible resources even if the actual user changes his password. This would be major security problem for this kind of Application Design.

So when the password changes in the above external login provides, I want to block subsequent requests to resources / refresh token / etc ...

Is there any possibility ?.

**Comment by BBanoth** [comment]
Sorry, Accidentally clicked close issue

**Comment by leastprivilege** [comment]
Not built-in. IdentityServer cannot know if the password has changed.

The profile service has the `IsActiveAsync` method - if there is a programmatic way for you to find out if the password has changed, you can block the token request.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
