### ISSUE TITLE
If you have a private NuGet feed which requires credentials, then build.sh and build.ps1 fail

### ISSUE THREAD

**Issue by SpiegelSoft** [IdentityServer/IdentityServer4#3343]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](http://docs.identityserver.io/en/latest/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem
Add a private NuGet feed (requiring credentials) to Visual Studio 2019.
Go to the root of the repository
Run build.sh or build.ps1
The build fails with the message:

nuget response status code does not indicate success

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
Makes sense. Merged.
