### ISSUE TITLE
IS4 adds base path to cookie login URL

### ISSUE THREAD

**Issue by mohammada-myplanet** [IdentityServer/IdentityServer4#3348]
We have a situation where we are using IS4 within an application that has a PathBase. The challenge is in the cookie options we set the login/logout URLs to include that path (i.e. /admin), but when IS4 picks it up, it adds the PathBase to it before redirecting, thus resulting in an incorrect URL.

I was about to submit this as a bug, but not sure. We can override IS4 login URLs, but it seems weird that it will add the PathBase to the login URL. I think it should assume that the URL already has the PathBase in it, because in reality, without the PathBase, that login URL won't work inside the app anyways (outside of IS4).

What do you think?

**Comment by brockallen** [comment]
I can't seem to repro what you're suggesting. I did this in `ConfigureServices`

```
            var builder = services.AddIdentityServer(options =>
                {
                    options.Authentication.CookieAuthenticationScheme = "foo";
                })
                .AddInMemoryClients(Clients.Get())
                .AddInMemoryIdentityResources(Resources.GetIdentityResources())
                .AddInMemoryApiResources(Resources.GetApiResources())
                .AddDeveloperSigningCredential();

            services.AddAuthentication("foo")
                .AddCookie("foo", options=>
                {
                    options.LoginPath = "/auth/login";
                });

```

And this in `Configure`:

```
 app.Map("/foo", app2 =>
            {
                app2.UseMiddleware<Logging.RequestLoggerMiddleware>();
                app2.UseDeveloperExceptionPage();

                app2.UseIdentityServer();

                app2.UseStaticFiles();
                app2.UseMvcWithDefaultRoute();
            });
```

This is how I'd expect to configure a base path in the app. It's working for me. How are you doing it differently?

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
