### ISSUE TITLE
Strange problem with nginx reverse proxy in Linux 

### ISSUE THREAD

**Issue by findmoon** [IdentityServer/IdentityServer4#3349]
I'm not sure whetherit is a setup issue or some bug。I deployed the idsrunder linux with nginx reverse proxy。Occasionally the following problems occur when requesting authorization。The space sometimes disappear。Using the clientid `spa client` will also become `spaclient`, so I changed to `spa_client`。but response_type cannot be changed。so i want  to know how to deal with this problem. It doesn't appear every time and I did not find this problem under the window.

![image](https://user-images.githubusercontent.com/18387852/59730375-bad69f00-9274-11e9-981c-214ea379f0a0.png)

**Comment by leastprivilege** [comment]
Client IDs don't allow spaces.

For response_type, I have never seen that before.

**Comment by brockallen** [comment]
Any update?

**Comment by manigandham** [comment]
What's the URL of that request to IdentityServer with all those query params? You might have a different character in there.
