### ISSUE TITLE
Internet Explorer does not redirect on connect/authorize/callback

### ISSUE THREAD

**Issue by mtren** [IdentityServer/IdentityServer4#3350]
Internet Explorer Version:
Internet Explorer 11
Version 11.557.17763.0

During login the Internet Explorer shows a white page on ``` https://{identityServer Uri}/connect/authorize/callback?client_id=mvc&redirect_uri={client uri}%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile&response_mode=form_post&nonce={...}&state={...}&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.4.0.0 ``` and does not redirect to the client.

In the Development Tools of Internet Explorer I can the see the Error: 
```
SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "addEventListener" nicht
callback (6,71)
```

I could not reproduce this on my localhost or any other browser, but on my test environment.

Windows Server 2016 
Version 1607 (Build 14393.2848)
Internet Information Services (Version 10.0.14393.0)

**Comment by brockallen** [comment]
possibly related: https://github.com/IdentityServer/IdentityServer4/issues/3128

can you try the preview of IS 2.5.0?

**Comment by mtren** [comment]
I tried, the new version has not the problem.
