### ISSUE TITLE
AddPolicyScheme breaks ID4

### ISSUE THREAD

**Issue by DalSoft** [IdentityServer/IdentityServer4#3351]
As soon as I add use AddPolicyScheme to select a DefaultAuthenticationScheme, ID4 starts to get exceptions. It starts with not setting the UserInteractionOptions i.e. LogoutUrl etc... Then it doesn't add the default claims.

My user case is I need to support Multiple Authentication Schemes based on the header.

I found this issue [4648](https://github.com/aspnet/AspNetCore/issues/4648), but is there a workaround or will you never support AddPolicyScheme? Currently my workaround is Authenticating with middleware instead.

**Comment by brockallen** [comment]
You can work around this, IIRC, by setting the `CookieAuthenticationScheme`

http://docs.identityserver.io/en/latest/reference/options.html#authentication

**Comment by DalSoft** [comment]
Thanks that was exactly what I was looking for.
