### ISSUE TITLE
Login page is loaded if cookies is expired.

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3355]
Hi, 
When we trigger connect/autorize/callback? for access token in "authorization code" grant type. If cookies is expired then this endpoint is redirect the user to the Login screen again for authentication.

is there any way around to call particular page if cookies is expired when trigger the connect/authorize/callback endpoint 

Please advice.

**Comment by leastprivilege** [comment]
An expired cookie looks exactly the same as an anonymous request. So I guess the answer is no.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
