### ISSUE TITLE
DefaultTokenService - access token claims without distinct

### ISSUE THREAD

**Issue by PrzemyslawMucha** [IdentityServer/IdentityServer4#3358]
DefaultTokenService has two different approaches to claims in identity/access token. 

Identity token - https://github.com/IdentityServer/IdentityServer4/blob/45ac86e90ddbf38ace3f7ba8d8b0ef738527a18a/src/IdentityServer4/src/Services/Default/DefaultTokenService.cs#L138

Access token - https://github.com/IdentityServer/IdentityServer4/blob/45ac86e90ddbf38ace3f7ba8d8b0ef738527a18a/src/IdentityServer4/src/Services/Default/DefaultTokenService.cs#L176

It's a bug or it's based on some standards ?

**Comment by brockallen** [comment]
I think the difference is just an oversight. Adding the distinct might make sense.

**Comment by brockallen** [comment]
@leastprivilege -- this is an easy filter to add. any objections?

**Comment by leastprivilege** [comment]
OK

**Comment by brockallen** [comment]
Ok, I made the change.
