### ISSUE TITLE
Identity Server EF Core DB Configuration with Azure MSI

### ISSUE THREAD

**Issue by manu4rhyme** [IdentityServer/IdentityServer4#3359]
**Is your feature request related to a problem? Please describe.**
We are required to ensure that we do not store database credentials anywhere (not even in Azure KeyVault), as part of our security compliance workitem. For our services to access the database, we are required to setup and use MSI based authentication only

**Describe the solution you'd like**
MSDN has a nice documentation for enabling and using MSI based authentication, and we have successfully enabled the same for a lot of our services, including SQL databases 
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi
However, we are unable to configure the same for the database used by Identity Server 4.
Is there a known workaround for this? Also, when can we expect a release that supports this or atleast allows a known workaround to work?

**Describe alternatives you've considered**
 ```
                 // this adds the config data from DB (clients, resources)
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(
                            KeyVaultData.DatabaseConnectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })

                // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(
                            KeyVaultData.DatabaseConnectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    // This enables automatic token cleanup.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 3600;
                });
```
This is our current implementation. We tried using a custom DbConnection (SqlConnection object with token added as explained in the documentation), but that did not work,

**Additional context**
We are on dot net core 2.2, and are using identity server 4 (2.2). With managed identity we can assign an identity to a web application, and enable database access to this identity during deployment itself, thus eliminating the need to store credentials

**Comment by leastprivilege** [comment]
I haven't used MSI for EF yet, but

* since we are using standard EF, it should work just like any other DB connection
* please upgrade to the latest IdentityServer version - we don't support older versions (for free).

**Comment by manu4rhyme** [comment]
> I haven't used MSI for EF yet, but
> 
> * since we are using standard EF, it should work just like any other DB connection
But it requires modifications in the database context which i believe are managed internally by IDS4?
> * please upgrade to the latest IdentityServer version - we don't support older versions (for free).
Okay, but i believe it requires migrating the Database schema to a newer version, which is why we are reluctant on doing so. Could you please point us to the exact documentation that is supposed to be followed for upgrading the same?

**Comment by leastprivilege** [comment]
As I said - I haven't tried it yet. You need to figure out the technical details yourself. Then let us know and we can decide how we can help you.

**Comment by manu4rhyme** [comment]
Hi,

I was able to make it work by changing the above code to the following 

                ```
                // .AddDeveloperSigningCredential()              
                // this adds the config data from DB (clients, resources)
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                    {
                        SqlConnection sqlConnection = new SqlConnection(KeyVaultData.DatabaseConnectionString)
                        {
                            AccessToken = (new AzureServiceTokenProvider()).GetAccessTokenAsync(Constants.SqlServerTokenResourceEndpoint).Result
                        };

                        builder.UseSqlServer(
                            sqlConnection,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                    };
                })

                // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                    {
                        SqlConnection sqlConnection = new SqlConnection(KeyVaultData.DatabaseConnectionString)
                        {
                            AccessToken = (new AzureServiceTokenProvider()).GetAccessTokenAsync(Constants.SqlServerTokenResourceEndpoint).Result
                        };

                        builder.UseSqlServer(
                            sqlConnection,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                    };

                    // This enables automatic token cleanup.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 3600;
                });
```

Its working correctly as far as I've tested.
@leastprivilege  Could you please comment on whether this approach seems okay?

**Comment by leastprivilege** [comment]
IOW - no code changes are required to IdentityServer. Right?

**Comment by manu4rhyme** [comment]
Yup, it seems to be working correctly so far

**Comment by leastprivilege** [comment]
OK. Great!
