### ISSUE TITLE
Asp.Net Core Identity user claims

### ISSUE THREAD

**Issue by raigol** [IdentityServer/IdentityServer4#336]
How to read Asp.Net Core Identity user claims when using IdentityServer4? 
I have successfully set up IdentityServer to use Asp.Net Core Identity for user database. But can't get the user claims from database. 
I understand that for retrieval of claims must use IProfileService. But how exactly is it done?

**Comment by damienbod** [comment]
@raigol Here's 2 examples:

http://dkbe.ch/post/include-user-properties-in-identityserver4-with-asp-net-core-identity

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/IdentityServerWithIdentitySQLite/IdentityWithAdditionalClaimsProfileService.cs

**Comment by kdaveid** [comment]
@raigol I have changed my domain for the blog:

https://blog.dkbe.ch/2016/09/13/include-user-properties-in-identityserver4-with-asp-net-identity/

Let me know if you need further assistance.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by JimBobSquarePants** [comment]
Both links 404.
