### ISSUE TITLE
Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

### ISSUE THREAD

**Issue by pppangilinan** [IdentityServer/IdentityServer4#3363]
Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

Not Updated on version 2.4.0 showing this console error.

Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

Maybe it's better if automatically configure on SecurityHeaderAttribute.cs instead setting it up manually.

**Comment by brockallen** [comment]
I don't understand your question. I don't see any error like that in my error console. Can you elaborate?
