### ISSUE TITLE
Not able to find Core Enums in IdentityServer4

### ISSUE THREAD

**Issue by telugulover2009** [IdentityServer/IdentityServer4#3364]
HI,
I'm trying to figure out where are the Core Model Enums in IdentityServer4. For Eg, openid connect flows enum. Do I need to create my own core models or is there one dll available?

Thanks,
Navya.

**Comment by leastprivilege** [comment]
There is the `IdentityServerConstants` class - all other constants are coming from IdentityModel. What exactly are you looking for?

**Comment by telugulover2009** [comment]
Hi,
Thanks, I'm looking for below enum (and few other) in IdentityServer4.

I could find it in IdentityServer3 but not in 4

namespace IdentityServer3.Core.Models

/// <summary>
    /// OpenID Connect flows.
    /// </summary>
    public enum Flows
    {
        /// <summary>
        /// authorization code flow
        /// </summary>
        AuthorizationCode = 0,

        /// <summary>
        /// implicit flow
        /// </summary>
        Implicit = 1,

        /// <summary>
        /// hybrid flow
        /// </summary>
        Hybrid = 2,

        /// <summary>
        /// client credentials flow
        /// </summary>
        ClientCredentials = 3,

        /// <summary>
        /// resource owner password credential flow
        /// </summary>
        ResourceOwner = 4,

        /// <summary>
        /// custom grant
        /// </summary>
        Custom = 5,

        /// <summary>
        /// authorization code with proof key flow
        /// </summary>
        AuthorizationCodeWithProofKey = 6,

        /// <summary>
        /// hybrid flow with proof key
        /// </summary>
        HybridWithProofKey = 7
    }

**Comment by telugulover2009** [comment]
Hello, Can anyone answer this for me? If a dll is available in Identity4.

**Comment by leastprivilege** [comment]
We don't have something like this. Just copy the code.
