### ISSUE TITLE
jti claim type missing in the ID_token 

### ISSUE THREAD

**Issue by mmbeyrem** [IdentityServer/IdentityServer4#3366]
**Is your feature request related to a problem? Please describe.**
I need to share an identity token with some clients and they expect "jti" claim type in the token

**Describe the solution you'd like**
```
if (request.ValidatedRequest.Client.IncludeJwtId)
            {
                claims.Add(new Claim(JwtClaimTypes.JwtId, CryptoRandom.CreateUniqueId(16)));
            }
```
should copied  tin  CreateIdentityTokenAsync
I didn't found in the openId specification  a restriction about it

**Comment by leastprivilege** [comment]
OIDC does not use jti. Nonce would be the equivalent.

**Comment by leastprivilege** [comment]
No-one stops you from issung a jti claim yourself, of course.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
