### ISSUE TITLE
Small typo under 'Protecting an API using Client Credentials' heading

### ISSUE THREAD

**Issue by zakaria-dz** [IdentityServer/IdentityServer4#3367]
In https://github.com/IdentityServer/IdentityServer4/blob/master/docs/quickstarts/1_client_credentials.rst
Under "Protecting an API using Client Credentials" heading, there's a small typo in the last sentence of the first paragraph.

"To see the full list of please go to IdentityServer4 Quickstarts Overview"  should be either 

"To see the full list, please go to IdentityServer4 Quickstarts Overview" or

"To see the full list of scenarios, please go to IdentityServer4 Quickstarts Overview"

**Comment by LindaLawton** [comment]
PR submitted thanks for this.

**Comment by brockallen** [comment]
merged, thanks both!
