### ISSUE TITLE
Problem with renew token, when poor internet connection

### ISSUE THREAD

**Issue by finchatticus** [IdentityServer/IdentityServer4#3368]
When access_token expire I create refresh request with 30 seconds read timeout.
In some cases when internet connection poor server receive request, but I don't receive response, and server delete this token.

After i make 2nd request with old refresh_token, I don't get new credentials, instead I receive response: {"error":"invalid_grant"}, because this token was used in 1st request.

How can I solve this problem?

IdentityServer client config:
```
new Client {
         ClientId = "example-android",
         ClientName = "Example Android",
         AllowedGrantTypes = GrantTypes.Code,
         RequirePkce = true,
         RequireClientSecret = false,
         RequireConsent = false,

         RedirectUris = {"example callback"},

         AllowedScopes = {
           IdentityServerConstants.StandardScopes.OpenId,
           IdentityServerConstants.StandardScopes.Profile,
           IdentityServerConstants.StandardScopes.Email,
           IdentityServerConstants.StandardScopes.OfflineAccess,
           "example-web-api",
           "example-api"
         },
         PostLogoutRedirectUris = {"example"},
         AllowOfflineAccess = true
}
```

**Comment by leastprivilege** [comment]
You can set the refresh token usage to `re-use`. This way you can use the refresh token more than once.

**Comment by finchatticus** [comment]
@leastprivilege thx, for answer, but I think this solution is not secure. Is any still solutions available?

**Comment by leastprivilege** [comment]
no, sorry.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
