### ISSUE TITLE
When Core 3 is released, use the new HostMatcherPolicy/HostAttribute in the diagnostic controllers for the quickstarts/samples.

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#3372]
This is a placeholder issue for September-ish when Core 3 is released.

In Core 3 we are getting some new features that let us lock down our routes to only specific hosts, or ports https://github.com/aspnet/AspNetCore/pull/6214

This will be a perfect replacement for this code https://github.com/IdentityServer/IdentityServer4/blob/master/samples/Quickstarts/3_ImplicitFlowAuthentication/src/IdentityServer/Quickstart/Diagnostics/DiagnosticsController.cs#L19

**Comment by VictorioBerra** [comment]
@leastprivilege example:

## Old

```csharp
    [SecurityHeaders]
    [Authorize]
    public class DiagnosticsController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var localAddresses = new string[] { "127.0.0.1", "::1", HttpContext.Connection.LocalIpAddress.ToString() };
            if (!localAddresses.Contains(HttpContext.Connection.RemoteIpAddress.ToString()))
            {
                return NotFound();
            }

            var model = new DiagnosticsViewModel(await HttpContext.AuthenticateAsync());
            return View(model);
        }
    }
```

## New

```csharp
    [SecurityHeaders]
    [Authorize]
    [Host("127.0.0.1", "::1")]
    public class DiagnosticsController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var model = new DiagnosticsViewModel(await HttpContext.AuthenticateAsync());
            return View(model);
        }
    }
```

Might want to triple check that `"::1"` is needed.

**Comment by leastprivilege** [comment]
PR?

**Comment by jcschmittmouts** [comment]
Can someone tell why only localAdresses can access diagnostics page?

**Comment by VictorioBerra** [comment]
@jcschmittmouts because its full of a lot of sensitive information that you may not want to make available to a user or to an attacker.
