### ISSUE TITLE
Convert Asp.net 4.5 MVC5 SimpleMembership Authentication to IdentityServer4

### ISSUE THREAD

**Issue by PivotDataTao** [IdentityServer/IdentityServer4#3374]
I have an Asp.net 4.5 MVC5 app using SimpleMembership for Authentication and Authorization with role in App. Now I need to integrate to use external IdentityServer4 for Authentication. Is this possible? Is there an sample I can follow?

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
