### ISSUE TITLE
Multiple ADFS server with Identity server 4 in .Net core

### ISSUE THREAD

**Issue by NeelBhatt** [IdentityServer/IdentityServer4#3375]
Hello guys,

I have asked a question related to multiple ADFS server on stackoverflow but have not got any response yet so thought to try my luck here.

Can anyone help me for this? https://stackoverflow.com/questions/56778643/multiple-adfs-server-with-identity-server-4-in-net-core

Thanks in advance.

**Comment by vkctata** [comment]
Hi NeelBhatt, 

You need to register each tenant like below in startup.

services.AddAuthentication()
                .AddSaml2p(TenantConstants.USWM_TENANT_NAME_INTERNAL, options => 
                {
                    var tenantName = TenantConstants.USWM_TENANT_NAME_INTERNAL;
                    options.CallbackPath = "/s/sso";
                    options.AllowIdpInitiatedSso = true;

                    options.IdPInitiatedSsoCompletionPath = "/sam";
                    options.Licensee = Configuration["SamlPlugin:Licensee"];
                    options.LicenseKey = Configuration["SamlPlugin:LicenseKey"];

                    var thisCertificate = LoadCertificate(tenantName);

                    options.IdentityProviderOptions =
                        Config.GetSamlIdpOptions(Configuration, tenantName);
                    if (options.IdentityProviderOptions != null)
                        options.IdentityProviderOptions.SigningCertificate = thisCertificate;

                    options.ServiceProviderOptions = Config.GetSamlSpOptions(Configuration, tenantName);
                    if (options.ServiceProviderOptions != null)
                        options.ServiceProviderOptions.SigningCertificate = thisCertificate;

                    //This whole section needs a rethink...
                    options.NameIdClaimType = Configuration[$"SamlIdpConfig_{tenantName.ToLower()}:NameIdClaimType"];
                    options.CallbackPath = Configuration[$"SamlIdpConfig_{tenantName.ToLower()}:CallbackUrl"];
                    options.SignInScheme = Configuration[$"SamlIdpConfig_{tenantName.ToLower()}:SignInScheme"];
                    options.SaveTokens = Config.GetResultAsBool(Configuration, $"SamlIdpConfig_{tenantName.ToLower()}:SaveTokens", true);
                })
                .AddSaml2p(TenantConstants.UKRB_TENANT_NAME_INTERNAL, options => 
                {
                    var tenantName = TenantConstants.UKRB_TENANT_NAME_INTERNAL;
                    options.CallbackPath = "/s/sso";
                    options.AllowIdpInitiatedSso = true;

                    options.IdPInitiatedSsoCompletionPath = "/sam";
                    options.Licensee = Configuration["SamlPlugin:Licensee"];
                    options.LicenseKey = Configuration["SamlPlugin:LicenseKey"];

                    var thisCertificate = LoadCertificate(tenantName);

                    options.IdentityProviderOptions =
                        Config.GetSamlIdpOptions(Configuration, tenantName);
                    if (options.IdentityProviderOptions != null)
                        options.IdentityProviderOptions.SigningCertificate = thisCertificate;

                    options.ServiceProviderOptions = Config.GetSamlSpOptions(Configuration, tenantName);
                    if (options.ServiceProviderOptions != null)
                        options.ServiceProviderOptions.SigningCertificate = thisCertificate;

                    //This whole section needs a rethink...
                    options.NameIdClaimType = Configuration[$"SamlIdpConfig_{tenantName.ToLower()}:NameIdClaimType"];
                    options.CallbackPath = Configuration[$"SamlIdpConfig_{tenantName.ToLower()}:CallbackUrl"];
                    options.SignInScheme = Configuration[$"SamlIdpConfig_{tenantName.ToLower()}:SignInScheme"];
                    options.SaveTokens = Config.GetResultAsBool(Configuration, $"SamlIdpConfig_{tenantName.ToLower()}:SaveTokens", true);
                });

**Comment by NeelBhatt** [comment]
@vkctata - Hey thanks a lot for the reply :)

I am just wondering is there any way we can automate this, like getting data from web api table and have kind of a loop for above logic instead of adding hardcoded data?

Because if new ADFS tenant is added, it will take whole cycle to add this tenant as it will require code change everytime right?

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question.
