### ISSUE TITLE
Custom claim-based authorization in multi-tenant api

### ISSUE THREAD

**Issue by eparizzi** [IdentityServer/IdentityServer4#3376]
I have an ASP.NET Core Web API that's currently behind an IdentityServer 4 with ASP.NET Identity. Authentication and authorization works great.

I know need to support multiple tenants (one database per tenant in my API). The API endpoints will receive a tenantId parameter to know which database should be used.
I need to define custom claims to give certain users permission to certain tenants.

Ideally, on my API I'd like to apply some kind of Authorize filter that can specify a role and IdentityServer should only allow users that have a claim matching that tenant-role relationship based on the tenantId parameter received by the endpoint.

Is this scenario possible? Any guidelines on how to achieve this?

Thanks

**Comment by leastprivilege** [comment]
IdentityServer establishes an identity - authorization is done in the API.

That said

This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
