### ISSUE TITLE
PersistedGrantStore (Entity Framework) not honoring expiration

### ISSUE THREAD

**Issue by davemateer** [IdentityServer/IdentityServer4#3378]
Based on the source code for the PersistedGrantStore, it looks like expired keys will be returned.

Example:

    public Task<PersistedGrant> GetAsync(string key)
    {
        var persistedGrant = _context.PersistedGrants.AsNoTracking().FirstOrDefault(x => x.Key == key);
        var model = persistedGrant?.ToModel();
    
        _logger.LogDebug("{persistedGrantKey} found in database: {persistedGrantKeyFound}", key, model != null);
    
        return Task.FromResult(model);
    }
	
Is this by design, or a bug? I'm creating my own implementation of IPersistedGrantStore for a different storage strategy, but was using this to get expectations on how the interface is supposed to be implemented. This seemed off to me, but maybe expired grants are handled correctly downstream?

**Comment by brockallen** [comment]
The higher order code checks the expirations.

**Comment by davemateer** [comment]
Thank you for the clarification.
