### ISSUE TITLE
What data should be persistent when IdentityServer4's App Pool is recycled?

### ISSUE THREAD

**Issue by rodmanb2** [IdentityServer/IdentityServer4#3379]
I have the IS4 hosted in IIS. The app pool is recycled every 24 hours and if a client logged in then it loses its ability to refresh its token.
I'm guessing that data is lost which should be persistent but I can't quite understand what.

**Comment by brockallen** [comment]
Docs: http://docs.identityserver.io/en/latest/topics/deployment.html
