### ISSUE TITLE
additional AddValidationKeys signatures to reflect AddValidationKey

### ISSUE THREAD

**Issue by StephanKuehn** [IdentityServer/IdentityServer4#3383]
I would like to add ValidationKeys (probably the past Token Signing Key, he current Token Signing Key, and the upcoming, future Token Signing Key) in order to support key roll-over.

While I can add a single Validation Key from a X509Certificate2, the method AddValidationsKeys currently support only AsymmetricSecurityKey[].

I would propose to make the API methods
AddSigningCredential
AddValidationKey
AddValidationKeys
symmetric, so they are easier to use.

Please find the list of missing signatures below:
`public static IIdentityServerBuilder AddValidationKeys(this IIdentityServerBuilder builder, params SigningCredentials[] credentials)
public static IIdentityServerBuilder AddValidationKeys(this IIdentityServerBuilder builder, params X509Certificate2[] certificates)
public static IIdentityServerBuilder AddValidationKeys(this IIdentityServerBuilder builder, params CertificateSearchOption[] searchOptions) with
public class CertificateSearchOption 
{
   public string Name { get; set; } 
   public StoreLocation Location { get; set; ] = StoreLocation.LocalMachine;
   public NameType NameType { get; set; } = NameType.SubjectDistinguishedName
}
public static IIdentityServerBuilder AddValidationKeys(this IIdentityServerBuilder builder, params RsaSecurityKey[] rsaKeys)

public static IIdentityServerBuilder AddValidationKey(this IIdentityServerBuilder builder, SigningCredentials credential)
public static IIdentityServerBuilder AddValidationKey(this IIdentityServerBuilder builder, RsaSecurityKey rsaKey)
public static IIdentityServerBuilder AddValidationKey(this IIdentityServerBuilder builder, AsymmetricSecurityKey key)`

**Comment by leastprivilege** [comment]
you know that you can simply create an X509SecurityKey by passing in the cert?

**Comment by StephanKuehn** [comment]
Sorry, I just read up the AddValidationKey methods in the code, and of course, I can return AsymmetricSecurityKey[] from my IEnumerable<X509Certificate2> by creating a X509SecurityKey for each certificate and casting this to AsymmetricSecurityKey.

In my opinion, public static IIdentityServerBuilder AddValidationKeys(this IIdentityServerBuilder builder, params X509Certificate2[] certificates) would still have made my life easier.

**Comment by leastprivilege** [comment]
Feel free to do a PR to get signatue parity between the two..

**Comment by StephanKuehn** [comment]
Would love to do so, but can't push my local branch to your repository. Any guides for this?

**Comment by brockallen** [comment]
If you're willing to submit a PR before Friday June 12 2019, then we can get this into our next release.

**Comment by StephanKuehn** [comment]
I've send you a patch file as I am not able to create a PR for this. 
Hope this is sufficient.

Kind Regards
Stephan

**Comment by brockallen** [comment]
In the UI here in github, for each file in the source there's an edit button on the top right. You can use that to submit a PR.
