### ISSUE TITLE
signout without session cookies (e.g. from multiple distinct devices)

### ISSUE THREAD

**Issue by fcavaco** [IdentityServer/IdentityServer4#3385]
Hello,

oidc
have a requirement to allow signout even though there is no session cookie associated to the request sent to /endsession (say they have been forcefully removed), 

Our plan currently is to redirect to the login page (to avoid open redirect attacks) and then postback into client sign-out endpoint... 

Does this make sense? how can I at logout obtain the client context required for the login page redirect?

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
