### ISSUE TITLE
Setup ADFS (>=3.0) as a external identity provider in Identity Server using OAuth 2.0

### ISSUE THREAD

**Issue by Goppey** [IdentityServer/IdentityServer4#3386]
We are trying to add ADFS (right now 4.0 but we also need to implement for 3.0 ) as external login provider. we are on track right now but we are not getting claims into access token, neither any user details. I am posting the screenshot of decoded access token:

![Screenshot (102)](https://user-images.githubusercontent.com/13184438/60507042-e0d45880-9ce4-11e9-856a-d8572b9d67c5.png)

Can anyone please guide me what am I doing wrong ?

**Comment by vkctata** [comment]
Are you requesting them from the client in the first place?

**Comment by Goppey** [comment]
Sorry, as I am newbie I am not able understand your question, we have identity server for authentication, I am adding **service.AddAuthentication.AddOAuth("","", OAuthOptions)** method into startup class with all configurations.

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
