### ISSUE TITLE
AspNetClaimTypes not available

### ISSUE THREAD

**Issue by ErnestHodge** [IdentityServer/IdentityServer4#3387]
I noticed that the AspNetClaimTypes table is not available when trying to list all available.  

Note that when setting up the IdentityServer4 with entity the follow will work with Identity, Operations and Persistants.  

```
var builder = services.AddIdentityServer(options =>
                {
                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;

                    options.UserInteraction = new UserInteractionOptions
                    {
                        LogoutUrl = "/Account/Logout",
                        LoginUrl = "/Account/Login",
                        LoginReturnUrlParameter = "returnUrl"
                    };
                })
                .AddAspNetIdentity<ApplicationUser>()
                 // this adds the config data from DB (clients, resources, CORS)
                 .AddConfigurationStore(options =>
                 {
                     options.ConfigureDbContext = b =>
                         b.UseSqlServer(connectionString,
                             sql => sql.MigrationsAssembly(migrationsAssembly));
                 })
                            // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = b =>
                        b.UseSqlServer(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;


                });
```

However, when dealing with getting access to all available ClaimsTypes within the database there is no real way to get what is currently added.  What are ways to access the currently added claims available for administrative purposes?

Or how does Identity Server maintain the list of Available Claims?

**Comment by brockallen** [comment]
> I noticed that the AspNetClaimTypes table is not available when trying to list all available.

I'm not sure what you mean. Which `AspNetClaimTypes` table are you referring to? I don't see one in the ASP.NET Identity code:

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/EntityFrameworkCore/src/IdentityDbContext.cs

or 

https://github.com/aspnet/AspNetCore/blob/master/src/Identity/EntityFrameworkCore/src/IdentityUserContext.cs

**Comment by ErnestHodge** [comment]
I was following the IdentityServer.Templates is4admin.  I am trying to mimic the functionality of the AdminUI and noticed that the list of ClaimsTypes actually refers to a table AspNetClaimTypes of the AspIDUser.db which is not in the DataMigration.  

![image](https://user-images.githubusercontent.com/49884788/60594678-19b71080-9d6b-11e9-9bca-b8e5bd20e26d.png)

I'm unable to find the way IdentityServer gets the list of the ClaimTypes available for Scopes/Identity Resources.

**Comment by brockallen** [comment]
That table is from the AdminUI product, not ASP.NET Identity. // @scottbrady91

**Comment by ErnestHodge** [comment]
Therefore,  I will create a table called "ClaimTypes" and change the IdentityClaims.Type to have a foreign key against the ClaimTypes.Name column.  Since, IdentityClaims only lists "IdentityResources"s available claims. 

Thanks

**Comment by scottbrady91** [comment]
AdminUI community edition only supports SQLite. If you want to use a different database we can set you up with a demo: <sales@identityserver.com>
