### ISSUE TITLE
Can IdentityServer4 be configured as an external IdP?

### ISSUE THREAD

**Issue by chazt3n** [IdentityServer/IdentityServer4#3390]
Can IdentityServer4 be configured as an external IdP?

![image](https://user-images.githubusercontent.com/3843179/60617318-1b97c880-9d99-11e9-90ec-70ab73a59430.png)

**Comment by TomCJones** [comment]
if your interested i have these two sites configured that way.
https://idesg2rp.azurewebsites.net/Account/Login
https://idesg-idp.azurewebsites.net/

Peace ..tom
________________________________

**Comment by chazt3n** [comment]
@TomCJones Thank you!!

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by chazt3n** [comment]
Yes sir - I'm sorry for the late response @brockallen - did not see the notification
