### ISSUE TITLE
Improve query on cors origins.

### ISSUE THREAD

**Issue by Jonatthu** [IdentityServer/IdentityServer4#3395]
https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/EntityFramework.Storage/src/Services/CorsPolicyService.cs#L48

Why are we bringing all the client cors origins into memory?

Would not be better just to search if the origin is registered on the AllowedCorsOrigins Table?
I am doing currently an implementation of this cors service and I would like to understand why this is like this.

**Comment by brockallen** [comment]
It's so we can run this line:

```
https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/EntityFramework.Storage/src/Services/CorsPolicyService.cs#L52
```

since we don't know how the DB does it

**Comment by Jonatthu** [comment]
Would not be better to say something like:
Assuming the origins are normalized on the cors table...
```
dbContext.AllowedCorsOrigins.Any(x => x.Origin == origin.ToNormalizedOrigin()));
```
So you do not bring all the cors origins to memory

@brockallen

**Comment by brockallen** [comment]
Perhaps, but it wasn't originally designed that way.

**Comment by Jonatthu** [comment]
@brockallen I am implementing Identity Server for DotNet Graphql usage there is a lot of benefits and I am normalizing the current database implementation repo, I'd like to see a way to show you the benefits without publishing this to public until is ready. Maybe we can make it part of IdentityServer Organization .

**Comment by brockallen** [comment]
Sure, we're open to suggestions/ideas. My concern is that normalizing an origin is harder than we might thing.

**Comment by brockallen** [comment]
Any update?

**Comment by Jonatthu** [comment]
@brockallen is there any way to contact you to share screens and show you the project in action?

**Comment by brockallen** [comment]
You can paste screen shots here.

**Comment by brockallen** [comment]
Any update?

**Comment by Jonatthu** [comment]
![image](https://user-images.githubusercontent.com/3742176/62016216-a46e0e00-b165-11e9-8cda-22bcb0909c3f.png)
![image](https://user-images.githubusercontent.com/3742176/62016246-e5feb900-b165-11e9-9295-cc319ed2096e.png)
![image](https://user-images.githubusercontent.com/3742176/62016261-f6169880-b165-11e9-8506-70c5b1173dd6.png)
![image](https://user-images.githubusercontent.com/3742176/62016276-06c70e80-b166-11e9-9f19-861340071e8f.png)

Except for the UI Playground everything else was generated and enhancing the strong type of Identity server and docs for a API server, allowing to have a nice UI Admin Panel to manage all the resources and clients.

The tool that I am using to generate services, interfaces and repositories and dbcontext is something that I have been working on for almost 3 years, it is like prisma but for dotnet core generating the whole graphql schema and possibilities to query against the db. Allowing to configure what's public or private.

I am still thinking on what to do with this project, but I would like to open source the Identity Serv er Graphql API and join it as part of Identity server org

**Comment by Jonatthu** [comment]
@brockallen would be nice to have a chat if you are interested on the details of this

**Comment by Jonatthu** [comment]
The cool part of this project is that developers can override and extend the project, since all the interfaces to do this got generated, so basically allows to override the db context, services and repositories. This supports batching add, edit and delete out of the box

**Comment by Jonatthu** [comment]
Only from a class library and using POCO classes can generate the whole api
![image](https://user-images.githubusercontent.com/3742176/62016451-1dba3080-b167-11e9-9bd6-f561d2e18a13.png)

and extend the generated api by custom fields that the generator does not support
![image](https://user-images.githubusercontent.com/3742176/62016477-3e828600-b167-11e9-9f7e-e3fdc95878db.png)

**Comment by Jonatthu** [comment]
@brockallen this is my update :)

**Comment by Jonatthu** [comment]
@brockallen  Any feedback?

**Comment by brockallen** [comment]
I've been traveling for the past 10 days. I'll have to look at it late next week.

**Comment by Jonatthu** [comment]
@brockallen well 14 days have passed, do you need something else to understand the full concept from me? Or any questions?

**Comment by brockallen** [comment]
So yes, I see the point about querying all rows. This can be improved, but given the EF changes in ASP.NET Core 3 we can't fix this without a breaking change. I will leave this open to address in our 4.0 version. Thanks.

**Comment by brockallen** [comment]
This will require adding a `DbSet<ClientCorsOrigin>` on the `IConfigurationDbContext`.

**Comment by brockallen** [comment]
PR submitted. Please have a look.

**Comment by brockallen** [comment]
Any feedback on the PR?

**Comment by brockallen** [comment]
PR merged
