### ISSUE TITLE
What does IS4 provide that I cannot get with Azure Active Directory alone?

### ISSUE THREAD

**Issue by cdecinkoKnight** [IdentityServer/IdentityServer4#3396]
We currently have Azure Active Directory with several thousand users in Active Directory. What does IS4 provide that I cannot get with connecting my .NET and/or Java apps to AAD alone?

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!

**Comment by cdecinkoKnight** [comment]
Thanks, however looking at the posts on StackOverflow shows that very few of the postings receive any up votes much less a response.


Connie DeCinko | Software Developer | MIS

Knight Transportation, Inc. | Phoenix, AZ
Connie.DeCinko@knighttrans.com<mailto:Connie.DeCinko@knighttrans.com>

[cid:image001.png@01D53338.54683BC0]
