### ISSUE TITLE
Multiple requests to discovery endpoint 

### ISSUE THREAD

**Issue by vdecristofaro** [IdentityServer/IdentityServer4#3397]
I am experiencing a very strange problem which is only happening when the software runs on azure. Either on a Macos development machine as well as on an internal Windows Server it is working good. 

The problem does not avoid the authentication and the authorization to work. That is, my implementation is working very good. 

Almost every 10 seconds I get a discovery request. I am sure none of my rp is doing noise. Do you have any suggestion to investigate? 

Thanks
 
### Relevant parts of the log file

<img width="952" alt="immagine" src="https://user-images.githubusercontent.com/18700475/60755941-3d8e8680-9ff7-11e9-89fc-e33285237fe6.png">

**Comment by leastprivilege** [comment]
no idea. sorry.

**Comment by brockallen** [comment]
Any update?
