### ISSUE TITLE
Prevent a client to access multiple resources using a single access-token

### ISSUE THREAD

**Issue by Rzassar** [IdentityServer/IdentityServer4#3398]
There are a bunch of question like "IdentityServer4 Multiple API access, single token #1943". 
Consider this scenario:

> a person (Developer1) developed ResourceApi1 and another person (Developer2) developed ResourceApi2. and a client wants to access both of them using a single access-token. Then ResourceApi1 has the same access-token that is acceptable and functional in ResourceApi2

question is: 
  1- Can ResourceApi1 call ResourceApi2 end-points without asking additional permission and without anyone aware of that?
  2- If it can, Is this dangerous or a normal thing in aspect of OAuth2 specs?
  3- In my old-school knowledge, the only way to prevent this is that: client use separate access-token for each resource. but i think more proper way is to (some how) prevent it from IDP at first place. So is that a way to prevent it in IDP instead of client?
many many thanks.

**Comment by leastprivilege** [comment]
You are right - and yes, this is considered "normal" in OAuth 2 as long as you use bearer tokens. I think the threat model talks about it somewhere

https://tools.ietf.org/html/rfc6819
