### ISSUE TITLE
always getting invalid_client

### ISSUE THREAD

**Issue by mayankgaur** [IdentityServer/IdentityServer4#3399]
Whenever I am trying to login, I am always getting invalid_client, Please find my details below. I have posted related code and details. Kindly help, I am stuck now:-
Client Details:-
Client
                {
                    ClientId = "ro.client",
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,

                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowedScopes = { "PublicApi", "ProtectedApi" }
                },
Postman query
![image](https://user-images.githubusercontent.com/5146368/60786683-07771100-a175-11e9-8218-0e59e49071e0.png)
Database data
![image](https://user-images.githubusercontent.com/5146368/60786776-6046a980-a175-11e9-88a2-0774f3e8eee3.png)
![image](https://user-images.githubusercontent.com/5146368/60786809-77859700-a175-11e9-846a-50cf6df4c753.png)
![image](https://user-images.githubusercontent.com/5146368/60786822-80766880-a175-11e9-9cdc-b1a292ec3d8b.png)
![image](https://user-images.githubusercontent.com/5146368/60786841-89673a00-a175-11e9-98b0-9ebf4682d1e5.png)
![image](https://user-images.githubusercontent.com/5146368/60786861-971cbf80-a175-11e9-8655-706b6c5321b4.png)
Token Controller
 [HttpPost]
        [AllowAnonymous]

        public async Task<IActionResult> LoginClient(ClientLoginModel model)
        {

            // discover endpoints from metadata
            var discoveryClient = new DiscoveryClient(_configuration["IdentityURL"]);
            discoveryClient.Policy.ValidateIssuerName = false;
            var disco = await discoveryClient.GetAsync();
            if (disco.IsError)
            {
                return Json(disco.IsError + disco.Error);
            }

            // request token
            var tokenClient = new TokenClient(disco.TokenEndpoint, model.ClientId, model.ClientSecrets);
            var tokenResponse = await tokenClient.RequestClientCredentialsAsync(model.Scope);

            if (tokenResponse.IsError)
            {
                return Json(tokenResponse.Error);
            }

            return Json(tokenResponse.Json);

        }

**Comment by leastprivilege** [comment]
Check the logs.

**Comment by SureshAmudalapalli** [comment]
@mayankgaur The allowedGrantType is different from the request type to TokenClient. You have to use `RequestResourceOwnerPasswordAsync` instead of `RequestClientCredentialsAsync`

**Comment by mayankgaur** [comment]
@SureshAmudalapalli I have tried according to your suggestion I am still having same issue
![image](https://user-images.githubusercontent.com/5146368/60796449-0224c100-a18b-11e9-8de8-e5a0bb6abdf8.png)
     public async Task<IActionResult> LoginUser(UserLoginModel model)
        {
            //var disco = await DiscoveryClient.GetAsync(_configuration["IdentityURL"]);
            var discoveryClient = new DiscoveryClient(_configuration["IdentityURL"]);
            discoveryClient.Policy.ValidateIssuerName = false;
            var disco = await discoveryClient.GetAsync();
            if (disco.IsError)
            {
                return Json(disco.Error);
            }

            // request token
            var tokenClient = new TokenClient(disco.TokenEndpoint, model.ClientId, model.ClientSecrets);
            var tokenResponse = await tokenClient.RequestResourceOwnerPasswordAsync(model.UserName, model.Password);

            if (tokenResponse.IsError)
            {
                return Json(tokenResponse.Error);
            }

            return Json(tokenResponse.Json);
        }
Db Details
![image](https://user-images.githubusercontent.com/5146368/60796703-88410780-a18b-11e9-829e-ce9d70ce2d93.png)

Client Details:-
   new Client
                {
                    ClientId = "ro.client",
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,

                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowedScopes = { "PublicApi", "ProtectedApi" }
                }

**Comment by SureshAmudalapalli** [comment]
@mayankgaur I think adding scope to the token request resolve the issue.

**Comment by mayankgaur** [comment]
@SureshAmudalapalli yes it has been resolved thanks
