### ISSUE TITLE
SampleApi project is not able to run

### ISSUE THREAD

**Issue by venkatrv** [IdentityServer/IdentityServer4#34]
I am getting the following message (I tried the SampleApi project)

The selected debug option is IIS Express but this project is not a web project. To use IIS Express you need to add the wwwroot attribute to project.json
So is there a problem with project.json file deployed with samples? Please let me know.

Yes, I am using 1.0.0-RC1-update1

**Comment by leastprivilege** [comment]
All I can is - it works for me. It has a wwwroot folder as you can see.

Maybe try without the debugger.

**Comment by venkatrv** [comment]
Thanks, it is working finally. The issue is with "1.0.0-RC1-update1", I got it updated and able to run sampleapi project
