### ISSUE TITLE
Add option to allow open redirects (standard OIDC behaviour)

### ISSUE THREAD

**Issue by AdamWillden** [IdentityServer/IdentityServer4#3400]
**Is your feature request related to a problem? Please describe.**
See background dicussion https://github.com/IdentityServer/IdentityServer4/pull/3381 (now closed)

We'd like the ability to return errors to the client (relying party) during auth. At the moment this is not possible due to [IdentityServer forcing a specific mitigation of a vulnerability](https://github.com/IdentityServer/IdentityServer4/pull/3381#issuecomment-507310799).

**Describe the solution you'd like**
Add a new `IdentityServerOptions` parameter (likely within `AuthenticationOptions`) that permits open redirects. Consider cases where the identity server implementation (like ours) has provided an alternative mitigation of the open redirect vulnerability.

**Describe alternatives you've considered**
Replacing the entire auth endpoint with a custom implementation... which is not easy due to large number of 'internal' classes.

**Comment by brockallen** [comment]
I worry about maintaining the complexity of two different redirect styles. We'd need all new unit/integration tests that do things both ways. If your company really wants this change, then contact us to discuss it as a sponsored feature.

**Comment by leastprivilege** [comment]
Any update?

**Comment by AdamWillden** [comment]
Sorry imminent on a release right now. 

I did mention to my boss but we didn't really discuss it in detail. For now given time constraints this is something we'll simply try to work around (i.e. returning `AccessDenied` for all errors and rely on the error description).

Whilst unit/integration tests may a little time the run-time logic required is rather simple, so I had hoped it'd be a minor thing to address.

I won't be coming back to this before 19th August.
