### ISSUE TITLE
Rework callback to allow for intermediate loading page

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#3407]
Instead of the authorize endpoint doing a direct redirect back to client, allow for a per-client setting to instead redirect to a endpoint in the UI so it can control the redirect (e.g. to show a loading UI, or allow for meta redirects like we have for the pkce client).

**Comment by thomaslevesque** [comment]
This intermediate redirect would happen even if the user was already logged in, right? Unlike what is done in 5777bc12e67fd45bf3fb7ffad43d3d4017657c30?

**Comment by thomaslevesque** [comment]
Still interested in this

**Comment by brockallen** [comment]
Idea: config path in our options. when re detect native client we re-execute request in pipeline for this path getting it to emit the html which does the redirect.

**Comment by brockallen** [comment]
Oh I guess I had this idea already: #2215
