### ISSUE TITLE
Remove option to configure issuer?

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#341]
https://tools.ietf.org/html/draft-ietf-oauth-discovery-04#section-3.3

**Comment by leastprivilege** [comment]
I think that's limiting. 

I know the spec says MUST - but I had some weird scenarios in the past where there were 2 installations of identityserver that had to act a one logical one.

Which requires to configure the issuer manually.

**Comment by brockallen** [comment]
Fair enough.
