### ISSUE TITLE
What does the introspect endpoint actually do when we call it?

### ISSUE THREAD

**Issue by Danni-Ke** [IdentityServer/IdentityServer4#3412]
### Question / Steps to reproduce the problem
I am new to the IdentityServer4, and I am really confused about this endpoint right now. I searched so many different answers, someone said we need to send the client secret and client id, and someone said that they should be api secret and api name. And also there is no clear description in the document. I hope I can get more useful information from here. I want to make sure that the idea, introspect endpoint is for a reference token, not a jwt token, is right or not.

Also, I am trying to use this endpoint to validate my token and always got a 401 Unauthorized. Have no idea what is happening. Since I don't use hardcoded way to set up the config of my IdentityServer4, it doesn't have pictures about my config.cs.
Below are snapshots my postman windows, I am not sure I send the request in right way.
![image](https://user-images.githubusercontent.com/46721114/60967643-c2f29d80-a34d-11e9-9d67-3191f08d9eb6.png)
![image](https://user-images.githubusercontent.com/46721114/60967654-c8e87e80-a34d-11e9-87ea-b6a63528eecb.png)

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. But also you should read the specs, as they have all the details: http://docs.identityserver.io/en/latest/intro/specs.html

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
