### ISSUE TITLE
Do not take a dependency on Newtonsoft's Json.NET for ASP.NET Core 3

### ISSUE THREAD

**Issue by SidShetye** [IdentityServer/IdentityServer4#3414]
Identityserver4 `3.0.0-preview3.4`, [AddDeveloperSigningCredential()](https://github.com/IdentityServer/IdentityServer4/blob/f0d57a3c0fd231b1a5e270783536a8e15d05c4d8/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs#L118) takes a hard dependency on Json.NET which is no longer part of ASP.NET Core 3's standard stack ([news](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#fast-built-in-json-support)).

Please remove this dependency to be consistent with the asp.net core 3 default stack. As it stands, the transitive dependency on json.net is broken so you get

`
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.`

**Comment by leastprivilege** [comment]
This will not happen for the 3.0 release - but we will use the same Json.Net version that Microsoft's integration will use.

https://github.com/IdentityServer/IdentityServer4/issues/3415
