### ISSUE TITLE
Use same JSON.NET version as Microsoft's integration package

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3415]
..since JSON.NET is removed from core ASP.NET Core..

**Comment by douglasg14b** [comment]
Wait, why was #3414 closed and #3415 opened? That's a bit odd

**Comment by leastprivilege** [comment]
We are not removing JSON.NET in 3.0 - but to make it easier we will use the same version as Microsoft's integration package.

We will consider removing JSON.NET in future versions...

**Comment by leastprivilege** [comment]
OK - Microsoft's integration package 

https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.NewtonsoftJson/3.0.0-preview7.19365.7

uses 12.0.1

So that's what we are now explicitly referencing from IdentityServer4.
