### ISSUE TITLE
how to generate personal access token in a self serving manner

### ISSUE THREAD

**Issue by balaji-rajan** [IdentityServer/IdentityServer4#3416]
Is there a provision/custom extension to generate access token with scopes & sub (user Identity) with customisable expiration depends upon logged in user's permission.

**IdentityServerTools** could help to some extend but it works well for server to server communication in the lines of **client_credential** flow

**Comment by leastprivilege** [comment]
You can put whatever claims you want into the token with the tools class. So it can look like a user token if you want to.

**Comment by balaji-rajan** [comment]
@leastprivilege thanks, that's my last option to add `sub` as a claim.

**Comment by brockallen** [comment]
All set on this issue -- can we close?
