### ISSUE TITLE
Can you disable iss and sid query parameters?

### ISSUE THREAD

**Issue by lyubomirr** [IdentityServer/IdentityServer4#3417]
Is it possible not to append the sid and iss query parameters to the FrontChannelLogoutUri when issuing single sign out as they are optional as it is stated in the OpenIdConnect specification?

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/master/src/Storage/src/Models/Client.cs#L134

**Comment by lyubomirr** [comment]
Oh thanks for the quick answer, haven't noticed that.
