### ISSUE TITLE
ClientConfigurationDbContext unavailable in Identity Server 4

### ISSUE THREAD

**Issue by telugulover2009** [IdentityServer/IdentityServer4#3418]
Hi,
I'm looking for ClientConfigurationDbContext and ScopeConfigurationDbContext in Identity Server 4. Are they available? 

On similar note, I've a database with Entity Framework and Asp.Net Identity server 3. Can I use the same database for Identity Server 4? Do you have any samples for the same?

**Comment by leastprivilege** [comment]
No, no and no. sorry ;)

**Comment by telugulover2009** [comment]
I understand, It would be of great help if anyone can provide a sample for migration in future.

**Comment by brockallen** [comment]
Have a look here: https://github.com/RockSolidKnowledge/IdentityServer.Migration
