### ISSUE TITLE
IdSrv4 and ADFS 2016 Open ID connect

### ISSUE THREAD

**Issue by osca2000** [IdentityServer/IdentityServer4#342]
Has anyone made the two implemented together?
I understand that WsFederation, etc. are not supported in .core and IdSrv4. But OpenID Connect is a different monster from ADFS legacy functions? I mean can I assume if Google OpenID connect is supported, ADFS OpenID connect will as well?

Thanks

**Comment by leastprivilege** [comment]
The standard OIDC middleware should just work fine with ADFS 4

**Comment by muena** [comment]
Did you manage to get it working?
I get a "The authorization server does not support the response type 'token' for confidential clients" error.
