### ISSUE TITLE
Unable to run 9_Combined_AspId_and_EFStorage

### ISSUE THREAD

**Issue by valentinacupac** [IdentityServer/IdentityServer4#3420]
### Question / Steps to reproduce the problem

1. I opened up the solution IdentityServer4\samples\Quickstarts\9_Combined_AspId_and_EFStorage\Combined.sln
2. I built the solution, build works.
3. On the project IdentityServer, I clicked on Debug > Start new instance
4. It started but then resulted in HTTP Error 502.5 - Process Failure.
5. I'm not sure if I missed something, but are there any other necessary startup instructions aside from Debug > Start new instance....
6. After that didn't work, I also tried

```
{code}
PM> Update-Database -Context ApplicationDbContext
Done.
PM> Update-Database -Context PersistedGrantDbContext
Done.
PM> Update-Database -Context ConfigurationDbContext
Done.
PM> 
{code}
```

Then I tried to run the solution after that too, but it still didn't work (i.e. the IdentityServer starts and then it terminates).

**Comment by iguanaware** [comment]
The project has debug args with "/seed" and the Program.cs exits after seeding instead of running the host (WWW).

Change the project setting to not seed after running once or remove line 30  from Program.cs

launchSettings.json

`{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:5000",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "commandLineArgs": "/seed",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "SelfHost": {
      "commandName": "Project",
      "commandLineArgs": "/seed",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:5000"
    }
  }
}`

**Comment by valentinacupac** [comment]
Thanks a lot, it works now.
