### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by PHONGLEX** [IdentityServer/IdentityServer4#3423]
I've encountered the error as follows:
![error](https://user-images.githubusercontent.com/9126175/61123336-52bf5580-a4ce-11e9-94b9-78c69022ae05.PNG)

And here is my config in Startup.cs file of client app:

![config](https://user-images.githubusercontent.com/9126175/61123300-3ae7d180-a4ce-11e9-91cf-5bd988a1d91c.PNG)

The client has been stored in the database as well:
![db](https://user-images.githubusercontent.com/9126175/61123302-3ae7d180-a4ce-11e9-8eec-7fd731b41515.PNG)

The order when running project as follows:
![running](https://user-images.githubusercontent.com/9126175/61124537-53a5b680-a4d1-11e9-88f9-deb6d67f31ac.PNG)

Could you please support me on this?

Regards,
Phong

**Comment by leastprivilege** [comment]
Don't set `options.Configuration`.

**Comment by leastprivilege** [comment]
Also - this error is not IdentityServer related. Closing.
