### ISSUE TITLE
IdentityServer MVC Token Expiration

### ISSUE THREAD

**Issue by LiamSmithEngland** [IdentityServer/IdentityServer4#343]
Cross Post from Stackoverflow http://stackoverflow.com/questions/39673231/identityserver-mvc-token-expiration

I am new to Identity server and a key concept is missing from my understanding.
I am using the code from the [MVC tutorial][1].

If I decorate my Home controller with the attribute `[Authorize]` and visit my website I get redirect to the IdentityServer. I then log in using my username and password. I then use some custom code and authenticate. I get back an AccessToken and I can then access the Home controller.

My client settings is as follows:

      new Client
                {
                    ClientId = "mvc",
                    ClientName = "MVC Client",
                    AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,
                    ClientSecrets = new List<Secret>{new Secret("secret".Sha256())},
                    RequireConsent = false,
                    AccessTokenLifetime = 1,

                    // where to redirect to after login
                    RedirectUris = new List<string>{"http://localhost:5002/signin-oidc"},

                    // where to redirect to after logout
                    PostLogoutRedirectUris = new List<string>{"http://localhost:5002"},

                    AllowedScopes = new List<string>
                    {
                        StandardScopes.OpenId.Name,
                        StandardScopes.Profile.Name,
                        StandardScopes.OfflineAccess.Name,
                    }
                }

My access token is

    {
      "nbf": 1474697839,
      "exp": 1474697840,
      "iss": "http://localhost:5000",
      "aud": "http://localhost:5000/resources",
      "client_id": "mvc",
      "scope": [
        "openid",
        "profile"
      ],
      "sub": "26296",
      "auth_time": 1474697838,
      "idp": "local",
      "amr": [
        "pwd"
      ]
    }

As I set my `AccessTokenLifetime` to 1 my token when sent to call an API etc will be invalided. I still however will be able to access the website.

What is the best way to get the MVC website to confirm that my token has not expired? This may be where the refresh tokens come in to play.

**Note**
The `AccessTokenLifetime` set to 1 is for testing only so I can test things quickly.

  [1]: https://identityserver4.readthedocs.io/en/dev/quickstarts/3_interactive_login.html#creating-an-mvc-client

**Comment by brockallen** [comment]
>  I get back an AccessToken

No, authentication is via the id_token. An access token is used for when you invoke a web api.

**Comment by LiamSmithEngland** [comment]
OK so I can access the id_tokenby using

`HttpContext.Authentication.GetTokenAsync("id_token")`

This contains both a `exp` time stamp. I can then compare that to the current UTC date time. 
The `exp` on the id_token is controlled by the client setting IdentityTokenLifetime.

Just need to work out how to log someone out now...

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
