### ISSUE TITLE
Upgrade from IdentityServer4 2.4 to IdentityServer4 2.5

### ISSUE THREAD

**Issue by renato-sucoski** [IdentityServer/IdentityServer4#3430]
Update to 2.5 to make IdentityServer4 my accesses from users with offline_access scope have stopped working. Get Invalid Scope.
Returning to version 2.4, the system returned to normal operation.
.Net Core 2.2 - WebApi

**Comment by brockallen** [comment]
Can you provide more info -- perhaps the pertinent log entry, the client settings, and how the client makes the authorize request.

**Comment by renato-sucoski** [comment]
Sure :)

**Log:**
`IdentityServer4.Endpoints.TokenEndpoint:Debug: Start token request.
IdentityServer4.Validation.ClientSecretValidator:Debug: Start client validation
IdentityServer4.Validation.BasicAuthenticationSecretParser:Debug: Start parsing Basic Authentication secret
IdentityServer4.Validation.PostBodySecretParser:Debug: Start parsing for secret in post body
IdentityServer4.Validation.SecretParser:Debug: Parser found secret: PostBodySecretParser
IdentityServer4.Validation.SecretParser:Debug: Secret id found: ClientTesteApp
Microsoft.EntityFrameworkCore.Infrastructure:Information: Entity Framework Core 2.2.6-servicing-10079 initialized 'ConfigurationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MigrationsAssembly=Omnion.IdentityServer 
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (3ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [x].[Id], [x].[AbsoluteRefreshTokenLifetime], [x].[AccessTokenLifetime], [x].[AccessTokenType], [x].[AllowAccessTokensViaBrowser], [x].[AllowOfflineAccess], [x].[AllowPlainTextPkce], [x].[AllowRememberConsent], [x].[AlwaysIncludeUserClaimsInIdToken], [x].[AlwaysSendClientClaims], [x].[AuthorizationCodeLifetime], [x].[BackChannelLogoutSessionRequired], [x].[BackChannelLogoutUri], [x].[ClientClaimsPrefix], [x].[ClientId], [x].[ClientName], [x].[ClientUri], [x].[ConsentLifetime], [x].[Created], [x].[Description], [x].[DeviceCodeLifetime], [x].[EnableLocalLogin], [x].[Enabled], [x].[FrontChannelLogoutSessionRequired], [x].[FrontChannelLogoutUri], [x].[IdentityTokenLifetime], [x].[IncludeJwtId], [x].[LastAccessed], [x].[LogoUri], [x].[NonEditable], [x].[PairWiseSubjectSalt], [x].[ProtocolType], [x].[RefreshTokenExpiration], [x].[RefreshTokenUsage], [x].[RequireClientSecret], [x].[RequireConsent], [x].[RequirePkce], [x].[SlidingRefreshTokenLifetime], [x].[UpdateAccessTokenClaimsOnRefresh], [x].[Updated], [x].[UserCodeType], [x].[UserSsoLifetime]
FROM [Clients] AS [x]
WHERE [x].[ClientId] = @__clientId_0
ORDER BY [x].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (2ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [x.AllowedGrantTypes].[Id], [x.AllowedGrantTypes].[ClientId], [x.AllowedGrantTypes].[GrantType]
FROM [ClientGrantTypes] AS [x.AllowedGrantTypes]
INNER JOIN (
    SELECT TOP(1) [x0].[Id]
    FROM [Clients] AS [x0]
    WHERE [x0].[ClientId] = @__clientId_0
    ORDER BY [x0].[Id]
) AS [t] ON [x.AllowedGrantTypes].[ClientId] = [t].[Id]
ORDER BY [t].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (3ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [x.RedirectUris].[Id], [x.RedirectUris].[ClientId], [x.RedirectUris].[RedirectUri]
FROM [ClientRedirectUris] AS [x.RedirectUris]
INNER JOIN (
    SELECT TOP(1) [x1].[Id]
    FROM [Clients] AS [x1]
    WHERE [x1].[ClientId] = @__clientId_0
    ORDER BY [x1].[Id]
) AS [t0] ON [x.RedirectUris].[ClientId] = [t0].[Id]
ORDER BY [t0].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (2ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [x.PostLogoutRedirectUris].[Id], [x.PostLogoutRedirectUris].[ClientId], [x.PostLogoutRedirectUris].[PostLogoutRedirectUri]
FROM [ClientPostLogoutRedirectUris] AS [x.PostLogoutRedirectUris]
INNER JOIN (
    SELECT TOP(1) [x2].[Id]
    FROM [Clients] AS [x2]
    WHERE [x2].[ClientId] = @__clientId_0
    ORDER BY [x2].[Id]
) AS [t1] ON [x.PostLogoutRedirectUris].[ClientId] = [t1].[Id]
ORDER BY [t1].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (2ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [x.AllowedScopes].[Id], [x.AllowedScopes].[ClientId], [x.AllowedScopes].[Scope]
FROM [ClientScopes] AS [x.AllowedScopes]
INNER JOIN (
    SELECT TOP(1) [x3].[Id]
    FROM [Clients] AS [x3]
    WHERE [x3].[ClientId] = @__clientId_0
    ORDER BY [x3].[Id]
) AS [t2] ON [x.AllowedScopes].[ClientId] = [t2].[Id]
ORDER BY [t2].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (2ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [x.ClientSecrets].[Id], [x.ClientSecrets].[ClientId], [x.ClientSecrets].[Created], [x.ClientSecrets].[Description], [x.ClientSecrets].[Expiration], [x.ClientSecrets].[Type], [x.ClientSecrets].[Value]
FROM [ClientSecrets] AS [x.ClientSecrets]
INNER JOIN (
    SELECT TOP(1) [x4].[Id]
    FROM [Clients] AS [x4]
    WHERE [x4].[ClientId] = @__clientId_0
    ORDER BY [x4].[Id]
) AS [t3] ON [x.ClientSecrets].[ClientId] = [t3].[Id]
ORDER BY [t3].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (2ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [x.Claims].[Id], [x.Claims].[ClientId], [x.Claims].[Type], [x.Claims].[Value]
FROM [ClientClaims] AS [x.Claims]
INNER JOIN (
    SELECT TOP(1) [x5].[Id]
    FROM [Clients] AS [x5]
    WHERE [x5].[ClientId] = @__clientId_0
    ORDER BY [x5].[Id]
) AS [t4] ON [x.Claims].[ClientId] = [t4].[Id]
ORDER BY [t4].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (2ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [x.IdentityProviderRestrictions].[Id], [x.IdentityProviderRestrictions].[ClientId], [x.IdentityProviderRestrictions].[Provider]
FROM [ClientIdPRestrictions] AS [x.IdentityProviderRestrictions]
INNER JOIN (
    SELECT TOP(1) [x6].[Id]
    FROM [Clients] AS [x6]
    WHERE [x6].[ClientId] = @__clientId_0
    ORDER BY [x6].[Id]
) AS [t5] ON [x.IdentityProviderRestrictions].[ClientId] = [t5].[Id]
ORDER BY [t5].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (2ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [x.AllowedCorsOrigins].[Id], [x.AllowedCorsOrigins].[ClientId], [x.AllowedCorsOrigins].[Origin]
FROM [ClientCorsOrigins] AS [x.AllowedCorsOrigins]
INNER JOIN (
    SELECT TOP(1) [x7].[Id]
    FROM [Clients] AS [x7]
    WHERE [x7].[ClientId] = @__clientId_0
    ORDER BY [x7].[Id]
) AS [t6] ON [x.AllowedCorsOrigins].[ClientId] = [t6].[Id]
ORDER BY [t6].[Id]
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (2ms) [Parameters=[@__clientId_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
SELECT [x.Properties].[Id], [x.Properties].[ClientId], [x.Properties].[Key], [x.Properties].[Value]
FROM [ClientProperties] AS [x.Properties]
INNER JOIN (
    SELECT TOP(1) [x8].[Id]
    FROM [Clients] AS [x8]
    WHERE [x8].[ClientId] = @__clientId_0
    ORDER BY [x8].[Id]
) AS [t7] ON [x.Properties].[ClientId] = [t7].[Id]
ORDER BY [t7].[Id]
IdentityServer4.EntityFramework.Stores.ClientStore:Debug: ClientTesteApp found in database: True
IdentityServer4.Stores.ValidatingClientStore:Debug: client configuration validation for client ClientTesteApp succeeded.
IdentityServer4.Validation.SecretValidator:Debug: Secret validator success: HashedSharedSecretValidator
IdentityServer4.Validation.ClientSecretValidator:Debug: Client validation success
IdentityServer4.Validation.TokenRequestValidator:Debug: Start token request validation
IdentityServer4.Validation.TokenRequestValidator:Debug: Start resource owner password token request validation
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [identityResource].[Id], [identityResource].[Created], [identityResource].[Description], [identityResource].[DisplayName], [identityResource].[Emphasize], [identityResource].[Enabled], [identityResource].[Name], [identityResource].[NonEditable], [identityResource].[Required], [identityResource].[ShowInDiscoveryDocument], [identityResource].[Updated]
FROM [IdentityResources] AS [identityResource]
WHERE 0 = 1
ORDER BY [identityResource].[Id]
IdentityServer4.EntityFramework.Stores.ResourceStore:Debug: Found  identity scopes in database
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT [api].[Id], [api].[Created], [api].[Description], [api].[DisplayName], [api].[Enabled], [api].[LastAccessed], [api].[Name], [api].[NonEditable], [api].[Updated]
FROM [ApiResources] AS [api]
WHERE EXISTS (
    SELECT 1
    FROM [ApiScopes] AS [x]
    WHERE 0 = 1)
ORDER BY [api].[Id]
IdentityServer4.EntityFramework.Stores.ResourceStore:Debug: Found  API scopes in database
IdentityServer4.Validation.ScopeValidator:Error: No identity or API scopes requested
IdentityServer4.Validation.TokenRequestValidator:Error: {
  "ClientId": "ClientTesteApp",
  "ClientName": "Cliente para teste das Apps",
  "GrantType": "password",
  "Raw": {
    "grant_type": "password",
    "username": "61944831134",
    "password": "***REDACTED***",
    "scope": "offline_access",
    "client_id": "ClientTesteApp",
    "client_secret": "***REDACTED***"
  }
}
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 140.0104ms 400 application/json; charset=UTF-8
Microsoft.EntityFrameworkCore.Infrastructure:Information: Entity Framework Core 2.2.6-servicing-10079 initialized 'PersistedGrantDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: MigrationsAssembly=Omnion.IdentityServer 
Microsoft.EntityFrameworkCore.Database.Command:Information: Executed DbCommand (0ms) [Parameters=[@__p_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT TOP(@__p_0) [x].[Key], [x].[ClientId], [x].[CreationTime], [x].[Data], [x].[Expiration], [x].[SubjectId], [x].[Type]
FROM [PersistedGrants] AS [x]
WHERE [x].[Expiration] < GETUTCDATE()
ORDER BY [x].[Key]
`
**StartUp server Class**
`    public class Startup
    {
        private IHostingEnvironment _environment;
        public Startup(IConfiguration configuration, IHostingEnvironment environment)
        {
            Configuration = configuration;
            _environment = environment;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddOptions();
            string connectionString = Configuration.GetConnectionString("Auth");
            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddDbContext<ApplicationDbContext>(builder => builder.UseSqlServer(connectionString));
            var lockoutOptions = new LockoutOptions()
            {
                AllowedForNewUsers = true,
                DefaultLockoutTimeSpan = TimeSpan.FromMinutes(10),
                MaxFailedAccessAttempts = 3
            };

            services.AddIdentity<ApplicationUser, UserRoles>(option =>
            {

                option.Lockout = lockoutOptions;
                option.User = new UserOptions { RequireUniqueEmail = false };
                option.Password.RequireDigit = true;
                option.Password.RequiredLength = 8;
                option.Password.RequiredUniqueChars = 0;
                option.Password.RequireLowercase = true;
                option.Password.RequireNonAlphanumeric = false;
                option.Password.RequireUppercase = true;

            })
            .AddEntityFrameworkStores<ApplicationDbContext>()
            .AddDefaultTokenProviders();
            var cert = new X509Certificate2( Path.Combine(_environment.ContentRootPath, "Cert.pfx"), "OmnionIdentity");
            services.AddIdentityServer()
               .AddSigningCredential(cert)
               .AddConfigurationStore(options =>
               {
                   options.ConfigureDbContext = builder =>
                       builder.UseSqlServer(connectionString,
                           sql => sql.MigrationsAssembly(migrationsAssembly));
               })
               .AddOperationalStore(options =>
               {
                   options.ConfigureDbContext = builder =>
                       builder.UseSqlServer(connectionString,
                           sql => sql.MigrationsAssembly(migrationsAssembly));
                   options.EnableTokenCleanup = true;
                   options.TokenCleanupInterval = 30;
               })
               .AddAspNetIdentity<ApplicationUser>()
               .AddProfileService<ProfileService>();
        }
        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseIdentityServer();
            app.UseAuthentication();
            app.UseCors(x => x
              .AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader());
            app.UseMvc();
        }
    }
}
`
**EndPoint Api Logon**
`
        [HttpPost("UserLogon")]
        public async Task<ActionResult> UserLogon(inUserLogon inUserLogon)
        {
            var client = new HttpClient();
            var discoveryClient = await client.GetDiscoveryDocumentAsync(_server.HostIdentityServer);
            if (discoveryClient.IsError)
            {
                Console.WriteLine(discoveryClient.Error);
                return BadRequest();
            }
            var response = await client.RequestPasswordTokenAsync(new PasswordTokenRequest
            {
                Address = discoveryClient.TokenEndpoint,
                ClientId = inUserLogon.clientId,
                ClientSecret = inUserLogon.clientSecret,
                Scope = inUserLogon.scope,
                UserName = inUserLogon.userId,
                Password = inUserLogon.userPassword

            });
            if (response.IsError)
            {
                return BadRequest(response.Json);
            }
            return Ok(response.Json);

        }
`
**Call from Postman**
![image](https://user-images.githubusercontent.com/52841882/61165169-2bc74a80-a4f3-11e9-926c-278630f3a971.png)

**Clients Table**
![image](https://user-images.githubusercontent.com/52841882/61165227-1acb0900-a4f4-11e9-9f2e-398ba7b2d246.png)

**clientScopes Table**
![image](https://user-images.githubusercontent.com/52841882/61165237-4f3ec500-a4f4-11e9-951a-e02b5018777a.png)

**AspNetUsers Table**
![image](https://user-images.githubusercontent.com/52841882/61165274-acd31180-a4f4-11e9-8ade-1a9b129f8845.png)

**when roll back to 2.4**
![image](https://user-images.githubusercontent.com/52841882/61165316-31259480-a4f5-11e9-94e0-01dfff3ed5b4.png)

Thank You very much

**Comment by brockallen** [comment]
Looks like this is the error:

`IdentityServer4.Validation.ScopeValidator:Error: No identity or API scopes requested `

And this:

` "scope": "offline_access"`

offline access is the only scope requested. 

This change is the reason: https://github.com/IdentityServer/IdentityServer4/pull/3391

So why were you only ever requesting `offline_access`? That's counter to the `ApiResource` scope design in IdentityServer (and also pretty much OAuth2).

**Comment by renato-sucoski** [comment]
I understand, thank you for your time. I use offline_access because it is the only scope that brings me the refresh token, because it is not possible to revoke a jwt tokens in production are 5 minutes and need refresh

**Comment by brockallen** [comment]
My point is that you have no other scopes in the access token, which is counter to our design.

**Comment by renato-sucoski** [comment]
I understand your point and I agree, really the way I did is not correct.
Just to clarify, I did it this way because I am migrating from another authentication service and used only the Client, User and Roles for authentication and authorization, so when changing first I tried to put the resources that already existed to later deepen and improve solutions .
Thank you very much for your commitment and I will study the architecture better to create my application correctly.

**Comment by brockallen** [comment]
all you would need to do is add a new scope that models your api.

**Comment by renato-sucoski** [comment]
Perfect, it worked.
Thank you very much for your work and for your commitment.

![image](https://user-images.githubusercontent.com/52841882/61176084-0ab53700-a591-11e9-9687-da805a503889.png)
