### ISSUE TITLE
Identityserver unauthorized_client error in implicit flow

### ISSUE THREAD

**Issue by SaMirzaei** [IdentityServer/IdentityServer4#3433]
My Identity Server works well in some weeks after that I have gotten an unauthorized_client error, I don't know why.

I have an error in Implicit flow, I describe it in StackOverflow as following the [Identityserver unauthorized_client error in implicit flow](https://stackoverflow.com/questions/57034138/identityserver-unauthorized-client-error-in-implicit-flow)

Have you ever been this error?
Thanks

**Comment by leastprivilege** [comment]
You need to check your logs.

**Comment by SaMirzaei** [comment]
Actually, I found the problem, The IdentityServer4 package in Identity service updated from version 2.4.0 to 2.5.0 but I can't resolve this problem.

Eventually, I'm forced to be down-grade to 2.4.0 version and my problem solved.

Any Idea to solve this problem in IdentityServer4 version 2.5.0?

**Comment by leastprivilege** [comment]
You need to check your logs.

**Comment by cportillosv** [comment]
> Actually, I found the problem, The IdentityServer4 package in Identity service updated from version 2.4.0 to 2.5.0 but I can't resolve this problem.
> 
> Eventually, I'm forced to be down-grade to 2.4.0 version and my problem solved.
> 
> Any Idea to solve this problem in IdentityServer4 version 2.5.0?

You save my day, the same problem here

**Comment by LubosVoska** [comment]
I have the same problem with update from 2.4.0 to 2.5.0

**Comment by leastprivilege** [comment]
Even when I am repeating myself - you will need to check your logs.

I would be interested too what causes the problem. But only the logs will tell you.

**Comment by LubosVoska** [comment]
Error from console:

**2.4.0** - working fine
**2.5.0** - Error


`
fail: IdentityServer4.Stores.ValidatingClientStore[0]
      Invalid client configuration for client MyClientId: AllowedCorsOrigins contains invalid origin: http://192.168.0.14:9000/
info: IdentityServer4.Events.DefaultEventService[0]
      {
        "Name": "Invalid Client Configuration",
        "Category": "Error",
        "EventType": "Error",
        "Id": 3001,
        "ClientId": "MyClientId",
        "ClientName": "MyClientId",
        "Message": "AllowedCorsOrigins contains invalid origin: http://192.168.0.14:9000/",
        "ActivityId": "0HLOG3E62DJQH:00000001",
        "TimeStamp": "2019-07-24T09:44:43Z",
        "ProcessId": 2004,
        "LocalIpAddress": "127.0.0.1:50000",
        "RemoteIpAddress": "192.168.0.14"
      }
fail: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Unknown client or not enabled: MyClientId
{
        "SubjectId": "anonymous",
        "RequestedScopes": "",
        "Raw": {
          "client_id": "MyClientId",
          "redirect_uri": "http://localhost:9000/signin-oidc",
          "response_type": "id_token",
          "scope": "openid profile email roles",
          "response_mode": "form_post",
          "nonce": "636995582834333117.OTU3NGIzNGQtY2MzZC00MTYxLTk2MTgtNThhOTdjZGIxYjAyMzdkOGYxYWEtMzM4ZS00Yjk4LTliZDEtMWE0YTJhMjYxYmZk",
          "state": "CfDJ8Jm77mZgTuJDn2F1xELxH9CRDibh5myzcHfyrszPbuW2zjnP9Uk1538-zcov1PsKmeFsBJJyeGyvHsqUYNPScjvdOXbGzWMKrIjLffZasdcpyIBvu8ZyEnOJOzhKEUgXRJvzNPpX8NEXJHGKIxY_OVOJpU91llwilr8vAByVKO6asYXJDHays2YUVvCJIcRZiESFy6OJ1DGVS_JtwHMC16Ff8lBDLNA8b2wW4aBkRwXUOJcoY7BFOrI9fmcu2vLLPazwjGSGWYksARA7FB5Ky4lfBVbFU1eske6EIukygKyB_hzc3vF8PYxrWt1-x-pGYQ",
          "x-client-SKU": "ID_NETSTANDARD2_0",
          "x-client-ver": "5.3.0.0"
        }
      }
fail: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
      Request validation failed
info: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
      {
        "SubjectId": "anonymous",
        "RequestedScopes": "",
        "Raw": {
          "client_id": "MyClientId",
          "redirect_uri": "http://localhost:9000/signin-oidc",
          "response_type": "id_token",
          "scope": "openid profile email roles",
          "response_mode": "form_post",
          "nonce": "636995582834333117.OTU3NGIzNGQtY2MzZC00MTYxLTk2MTgtNThhOTdjZGIxYjAyMzdkOGYxYWEtMzM4ZS00Yjk4LTliZDEtMWE0YTJhMjYxYmZk",
          "state": "CfDJ8Jm77mZgTuJDn2F1xELxH9CRDibh5myzcHfyrszPbuW2zjnP9Uk1538-zcov1PsKmeFsBJJyeGyvHsqUYNPScjvdOXbGzWMKrIjLffZasdcpyIBvu8ZyEnOJOzhKEUgXRJvzNPpX8NEXJHGKIxY_OVOJpU91llwilr8vAByVKO6asYXJDHays2YUVvCJIcRZiESFy6OJ1DGVS_JtwHMC16Ff8lBDLNA8b2wW4aBkRwXUOJcoY7BFOrI9fmcu2vLLPazwjGSGWYksARA7FB5Ky4lfBVbFU1eske6EIukygKyB_hzc3vF8PYxrWt1-x-pGYQ",
          "x-client-SKU": "ID_NETSTANDARD2_0",
          "x-client-ver": "5.3.0.0"
        }
      }
`

**Comment by brockallen** [comment]
Seems like the logs have it:
```
AllowedCorsOrigins contains invalid origin: http://192.168.0.14:9000/
```

`http://192.168.0.14:9000/` is not an origin. `http://192.168.0.14:9000` is.

https://tools.ietf.org/html/rfc6454#section-7

**Comment by LubosVoska** [comment]
> Seems like the logs have it:
> 
> ```
> AllowedCorsOrigins contains invalid origin: http://192.168.0.14:9000/
> ```
> 
> `http://192.168.0.14:9000/` is not an origin. `http://192.168.0.14:9000` is.
> 
> https://tools.ietf.org/html/rfc6454#section-7

Yes Cors is the problem thank you.
