### ISSUE TITLE
Make it easier to change the IsActiveAsync bahavior 

### ISSUE THREAD

**Issue by ulrichb** [IdentityServer/IdentityServer4#3434]
**Is your feature request related to a problem? Please describe.**

The current `ProfileService.IsActiveAsync()` API:

https://github.com/IdentityServer/IdentityServer4/blob/4b84868587e8b7ab20483940d08d1b6ee6a94642/src/AspNetIdentity/src/ProfileService.cs#L95-L107

To extend checks on the user-object one must _either_ override the complete method including the null-checking and logging code _or_ call the base method and load the user again (calling `UserManager.FindByIdAsync` which hits the database).

**Describe the solution you'd like**

Please separate the data loading / logging code from the check-predicate. 

For example: Extract the `context.IsActive = user != null` line (106) into a protected virtual member which can be overridden in a derived class. (+ allow it to be "async")

Maybe better extract a boolean-returing predicate (only the `user != null` part, not the `context.IsActive = ...` part).

**Comment by ulrichb** [comment]
Btw, my use case would be:

```C#
Task<bool> async CustomIsActivePredicate(user: ApplicationUser) => 
    user != null && !await UserManager.IsLockedOutAsync(user)
```

**Comment by ulrichb** [comment]
Just have the same problem when overriding `ProfileService.GetProfileDataAsync()`. I have to do a second silly `UserManager.FindByIdAsync` access :/

**Comment by brockallen** [comment]
How about something like this:

https://github.com/IdentityServer/IdentityServer4/commit/afb90cba94a18a1d469cfa55f827ea5776efff86

**Comment by brockallen** [comment]
PR submitted. please have a look.

**Comment by brockallen** [comment]
merged? yay!

**Comment by ulrichb** [comment]
@brockallen Finally found time to upgrade to IS4 4.0 and it works great. Many thanks!
