### ISSUE TITLE
JwtRequestValidator ctor causes SimpleInjector validation error

### ISSUE THREAD

**Issue by protonyx** [IdentityServer/IdentityServer4#3436]
We use SimpleInjector in tandem with the built-in Microsoft DI (https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html) to provide more advanced (and opinionated) DI scenarios. During our startup flow, we call a `Verify `method on the SimpleInjector container which walks through the dependency tree and ensures that all dependencies are constructable.

When SimpleInjector gets to JwtRequestValidator, an exception is thrown because `contextAccessor.HttpContext` is null, which is expected behavior when you are calling this method outside the scope of a request. 

This issue is not seen when using the default Microsoft DI container, because it does not try to construct all classes known to the container. This capability of SimpleInjector allows us to fail fast and detect DI configuration-related issues on startup. 

This is not a high priority issue, since it has limited impact to an optional feature of a non-standard DI container.

**Comment by leastprivilege** [comment]
Is SimpleInjector clever enough to deal with ArgumentNullExceptions?

**Comment by protonyx** [comment]
I did some testing, and it looks like it is not. SimpleInjector assumes that all registered classes are constructable. `HttpContextAccessor` is constructable without providing an `HttpContext` (https://github.com/aspnet/HttpAbstractions/blob/master/src/Microsoft.AspNetCore.Http/HttpContextAccessor.cs), so a call to `HttpContextAccessor.HttpContext` without setting the context will return null.

**Comment by brockallen** [comment]
So where are we on this issue?

**Comment by armitagemderivitec** [comment]
I'm using Autofac in tandem with Microsoft DI and I'm getting the same error in my integration tests for controller instantiation. Each of my controllers that inject IIdentityServerInteractionService cannot now be tested. Any ideas?

**Comment by ChristianKuhre** [comment]
I am experiencing the same issue when using Simple Injector and updating to 2.5.0, so it is kinda keeping us from updating from 2.4.0. Maybe the HttpContext access could be moved away from the constructor?

**Comment by leastprivilege** [comment]
Will be fixed here

https://github.com/IdentityServer/IdentityServer4/pull/3517

**Comment by protonyx** [comment]
Thank you, that change fixes our issue.
