### ISSUE TITLE
RefreshToken validation for multiple client

### ISSUE THREAD

**Issue by jasonycw** [IdentityServer/IdentityServer4#3438]
**Is your feature request related to a problem? Please describe.**
I am trying to make 2 clients to share both Jwt and RefreshToken usage.

For Jwt token, by changing the `Client.AllowedScopes`, I can create token from client A and use it in client B, that's ok

But for RefreshToke, if I create it from client A and try to refresh it through client B, `TokenValidator.ValidateRefreshTokenAsync` will say it is invalid

https://github.com/IdentityServer/IdentityServer4/blob/4b84868587e8b7ab20483940d08d1b6ee6a94642/src/IdentityServer4/src/Validation/Default/TokenValidator.cs#L397-L407

**Describe the solution you'd like**
If there is some default option to set the client to accept refresh token from another client.

OR if there is some option to set the client to issue a refresh token for another client

**Describe alternatives you've considered**
I tried to make a `CustomizeTokenValidator` by implementing `ITokenValidator` to customize `ValidateRefreshTokenAsync` 
https://github.com/IdentityServer/IdentityServer4/blob/4b84868587e8b7ab20483940d08d1b6ee6a94642/src/IdentityServer4/src/Validation/ITokenValidator.cs#L13

But it will also require me to implement `ValidateAccessTokenAsync` and `ValidateIdentityTokenAsync`, I don't really want to change the default behavior, if there will be difference interface for each implementation so I can customize it in detail?

e.g. `ITokenValidator` change to  `IAccessTokenValidator` + `IRefreshTokenValidator` + `IIdentityTokenValidator`

Not sure if this related to https://github.com/IdentityServer/IdentityServer4/issues/1847

**Additional context**
The [old issue](https://github.com/IdentityServer/IdentityServer4/issues/3425) detailing more about the background, and I don't think there is a current solution

**Comment by leastprivilege** [comment]
Right now refresh tokens can only be refresh by the client that requested the token in the first place. We have no plans to change this in the near future.

**Comment by leastprivilege** [comment]
We are tracking this here 

https://github.com/IdentityServer/IdentityServer4/issues/3446
