### ISSUE TITLE
Access the client is inside IScopeStore

### ISSUE THREAD

**Issue by BehnamAbdy** [IdentityServer/IdentityServer4#344]
I'm reading the Scopes from db so I use my own custom implementation of iscopestore.then in my case I need the clientid inside the IScopeStore.FindScopesAsync to filter the Scopes(I have a very specific case),I tried injecting interaction into the constructor but thing crash.
Any idea?

**Comment by leastprivilege** [comment]
The scope store has no knowledge about the current client.
