### ISSUE TITLE
Refresh token lifetime

### ISSUE THREAD

**Issue by tiljanssen** [IdentityServer/IdentityServer4#3440]
Question 1: 
If I have a one-time refresh token policy, I assumed that the absolute token lifetime is restarted each time the token is refreshed, since a new token is generated. 
Is the assumption true?

A remark:
The documentation mentions "OneTime" as the value for RefreshTokenUsage, while the code uses "OneTimeOnly".

**Comment by leastprivilege** [comment]
No - it is the **absolute** lifetime. And might span different refresh token values.
