### ISSUE TITLE
Undocumented behavior - Authorization Code requires Client Secret

### ISSUE THREAD

**Issue by Compufreak345** [IdentityServer/IdentityServer4#3443]
### Issue / Steps to reproduce the problem
When setting up a client for the Code-Flow without providing a client secret I get the error
`Client secret is required for authorization_code, but no client secret is configured`.

This behaviour is documented [in an issue for IdentityServer3](https://github.com/IdentityServer/IdentityServer3/issues/2688) 
but not in the [current documentation for the token endpoint](http://docs.identityserver.io/en/latest/endpoints/token.html) or the [current documentation for the Authorization Code flow](http://docs.identityserver.io/en/latest/topics/grant_types.html?highlight=code%20flow#authorization-code).

The behavior kind of contradicts the purpose of [the PKCE-Flow for Authcodes](https://auth0.com/docs/flows/concepts/auth-code-pkce) as described by [different sources](https://developers.onelogin.com/openid-connect/guides/auth-flow-pkce) as this is explicitly made for untrusted clients. We are trying to work around this , but I ask you to please
(a) Reconsider this decision when PKCE is enabled as libraries like [this one](https://github.com/damienbod/angular-auth-oidc-client) do not send the secret on such a request and require workarounds. 
(b) If you come to a negative conclusion please at least update the documentation to reflect this requirement.

I also filed [an issue](https://github.com/damienbod/angular-auth-oidc-client/issues/472) on the library I linked to provide the client_secret with this request as this probably also is not a perfect behavior - but also was not implemented on a previous issue.

### Relevant parts of the log file

```
[16:11:13 VRB] Calling into client configuration validator: IdentityServer4.Validation.DefaultClientConfigurationValidator
[16:11:13 ERR] Invalid client configuration for client codeflow: Client secret is required for authorization_code, but no client secret is configured.
```

Thanks & best regards,
Christoph Sonntag

**Comment by brockallen** [comment]
Why not set `RequireClientSecret` to `false`?

http://docs.identityserver.io/en/latest/reference/client.html

**Comment by Compufreak345** [comment]
Because I did not read the documentation thoroughly enough 🙀. Thanks for your help :)
