### ISSUE TITLE
Consider specifying in the docs the need to use AddIdentity before AddIdentityServer when integrating with AspNet Identity

### ISSUE THREAD

**Issue by patrickhacens** [IdentityServer/IdentityServer4#3448]
This [doc](http://docs.identityserver.io/en/latest/quickstarts/8_aspnet_identity.html) is missing an important information about the configuration of services: the fact that `AddIdentityServer` must occur **after** `AddIdentity` or the following exception is thrown:
```
System.InvalidOperationException: 'Service type: IUserClaimsPrincipalFactory`1 not registered.'
```

I believe either it should be made clear at the docs or it should not be a requirement

**Comment by brockallen** [comment]
Feel free to PR the doc where you'd like it mentioned.

**Comment by brockallen** [comment]
merged, thanks
