### ISSUE TITLE
IdentityServer4 manual is unclear on sending password

### ISSUE THREAD

**Issue by vporton** [IdentityServer/IdentityServer4#3449]
http://docs.identityserver.io/en/latest/quickstarts/2_resource_owner_passwords.html is unclear on *why* to send password when requesting a token:

```csharp
var tokenResponse = await client.RequestPasswordTokenAsync(new PasswordTokenRequest
{
    Address = disco.TokenEndpoint,
    ClientId = "ro.client",
    ClientSecret = "secret",

    UserName = "alice",
    Password = "password",
    Scope = "api1"
});
```

It is not understandable *why* to send both ClientId/ClientSecret and UserName/Password. It looks like that they request to "identify the user two times": both by ClientSecret and by Password.

Change the manual to explain why it is done.

**Comment by leastprivilege** [comment]
Please read the OAuth spec first. If you still think we are doing it wrong, feel free to re-open the issue.

**Comment by vporton** [comment]
Read the OAuth spec. Reading it did not change my opinion: You have at least your documentation too unclear: You do a weird thing in your code example and do not explain why. It is a bug in the documentation.

I see no Reopen button. Please help to reopen the issue.

**Comment by leastprivilege** [comment]
Then check the spec about the difference between a client and a user.

It's not weird nor a bug - and our documentation's job is not to teach you how the protocols work.

**Comment by vporton** [comment]
I know the difference:
* client is software that uses access tokens
* user is a human that uses a password

The weird thing is that it delivers authentication data for both a client and an user in a single request.

The bug is that it is not explained in the documentation why the code example does this weird thing.

If a reader of your docs says your docs are weird, they are likely to be such, because the docs are written for a reader. Moreover, if it is required to read a whole formal specification to understand why your example code is so weird, and moreover if reading it does not lead to understanding this, then it is a documentation bug.

**Comment by leastprivilege** [comment]
OK - feel free to open a PR to improve our documentation.
