### ISSUE TITLE
Is Idsvr4 production ready?

### ISSUE THREAD

**Issue by khelben** [IdentityServer/IdentityServer4#345]
We have a current implementation using idsrv3, but we'd like to move on to idsrv4.  

So I would like to know how far this version is from production ready? (from what I've read in the past, it was always the intention to make this RTM as soon as DotNetCore was RTM'ed)

TIA

Christiaan

**Comment by leastprivilege** [comment]
That's our current thinking:

https://github.com/IdentityServer/IdentityServer4/milestones

**Comment by khelben** [comment]
Thx!

Anything I could help with fixing issues, would love to try to help.

**Comment by leastprivilege** [comment]
nothing particular right now.

It would me most helpful to just use it for real scenarios and see if you find any issues.
