### ISSUE TITLE
How can I change the namespace of IdentityServer4.Quickstart.UI?

### ISSUE THREAD

**Issue by ranzeplay** [IdentityServer/IdentityServer4#3451]
How can I change the namespace of IdentityServer4.Quickstart.UI? I want it as same as my project.
But when I tried to do it. VisualStudio tells me "you can't rename elements that are defined from metadata"

**Comment by brockallen** [comment]
Not sure what the issue is. Why can you just rename the text in the .cs files?

**Comment by ranzeplay** [comment]
I mean, I want to rename the namespace "IdentityServer4.Quickstart.UI" to my project's namespace, like MyApp.IdentityServer

**Comment by Jehoel** [comment]
> "you can't rename elements that are defined from metadata"

That means you're using the Quickstart.UI by referencing the assembly rather than copying the Quickstart source files into your project.

Remove your project references to the quickstart assemblies and copy the source files into your project, then you can rename the namespaces.

**Comment by leastprivilege** [comment]
The quickstart UI is only available as source...

**Comment by ranzeplay** [comment]
Okay, thanks
