### ISSUE TITLE
Pass parameters and receive them from IS4

### ISSUE THREAD

**Issue by NihadOb** [IdentityServer/IdentityServer4#3454]
Is there a way to pass parameter (referrer url) from client to Identity Server 4 and after login to receive that parameter in form of query parameter?
I have situation where users are redirected from client url (not static) to IS (in this step I have custom parameter as part of return url). After login user is redirected to connect/authorize/callback (again parameter is part of the url). 
Next step is return to client to return url from configuration, but in this step I am losing custom parameter. Only code, scope, state, session_state are part of response.
I am doing all this so I can return user to correct client url (referrer url) and not to return url from identity server configuration.
Is this possible?

**Comment by leastprivilege** [comment]
state is the dedicated parameter that should be used if you want to round-trip data.
