### ISSUE TITLE
Going forward with Core 3, will the recommended way to configure IS4 server be to use Microsoft.ApiAuthorization.IdentityServer

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#3455]
I have been going through all this to try and prepare myself for Core 3 https://github.com/aspnet/AspNetCore/tree/master/src/Identity/ApiAuthorization.IdentityServer

I noticed, out of the box it comes with its own way to configure an identity server, or protect an API.

So my question is, going forward, will people who create Identity Servers or create a Protected Resource use Microsoft.ApiAuthorization.IdentityServer? Or should we use all the stuff in IS4/src/Configuration/DependencyInjection/?

**Comment by leastprivilege** [comment]
Microsoft created a simplified abstraction over our configuration system. If that works for you, feel free to use it.

We will continue to use our own config system.
