### ISSUE TITLE
GetUserInfoAsync returns only sub without other claims

### ISSUE THREAD

**Issue by aleksanderwercis** [IdentityServer/IdentityServer4#3465]
Why does GetUserInfoAsync return only sub without other claims?

```
var discoveryResponse = client.GetDiscoveryDocumentAsync("some Authorization Url").Result;
var userInfoResponse = client.GetUserInfoAsync(new UserInfoRequest
{
    Address = discoveryResponse.UserInfoEndpoint,
    Token = token // access_token
}).Result;
```
After signed in I have in the response 'email' but when I call GetUserInfoAsync I don't have it. I pass to GetUserInfoAsync access_token maybe that? Because claims are in id_token but how I can return claims from GetUserInfoAsync in that case?

My code:

I have on the list of the IdentityResource 'email':

```
public static IEnumerable<IdentityResource> GetIdentityResources()
{
    return new List<IdentityResource>
    {
        new IdentityResources.OpenId(),
        new IdentityResources.Email()
    };
}
```
In the client I have 'email' and 'AlwaysIncludeUserClaimsInIdToken':

```
return new Client
{
    ClientId = clientId,
    AllowedGrantTypes = GrantTypes.Implicit,
    AllowAccessTokensViaBrowser = true,
    RedirectUris = { "some url" },
    PostLogoutRedirectUris = { "some url" },
    AlwaysIncludeUserClaimsInIdToken = true,
    AllowedScopes = new List<string>
    {
        IdentityServerConstants.StandardScopes.OpenId,
        "email"
    }
};
```
I pass scopes in the SignInAsync method:

`await _accessor.HttpContext.SignInAsync(subject, new Claim(ClaimNames.Email, email));`
In the requested scopes I have:

`scope: 'openid email'`

**Comment by leastprivilege** [comment]
check the logs and see if that reveals more information.

**Comment by brockallen** [comment]
Any update?
