### ISSUE TITLE
iOS 12.4 Breaking Changes

### ISSUE THREAD

**Issue by adamtarmstrong** [IdentityServer/IdentityServer4#3466]
I am not exactly sure what the issue is, yet.  But here's what I am experiencing.

Yesterday iOS 12.4 came out and since then my refresh tokens appear to no longer work.  Every single time the users are forced to re-enter their username and password.

Last year there was a similar issue when 12.1 came out - but I think that issue was around Apple locking down "LAX" Mode.  This new issue seems to be slightly different but yet very familiar.

Is anyone else seeing this new issue on 12.4?

Adam.

**Comment by Jehoel** [comment]
- What kind of client application is this? Just in iOS Safari or is it affecting mobile device apps? Are those apps native Swift/ObjC/Xamarin or WebView-based apps? What OIDC flows are you using?
- Where are the `refresh_token` values being stored?
- The "lax" isse refers to the handling of `SameSite=Lax` cookies in Safari. Those cookies are not _necessarily_ issued by IdentityServer4.
    * IS4 only issues cookies for the authentication website, and they don't generally contain any tokens. And websites are able to override this with their own cookies.
    *  So as you're talking about the use of `refresh_token` I assume you're referring to a relying-party web-application instead of the IS4-powered web-application - in which case it probably isn't anything to do with IS4 but instead with the relying-party web-app.

**Comment by brockallen** [comment]
Any update?
