### ISSUE TITLE
Pull-request-request: Expose TokenValidator and add "reason" messages to Store operations.

### ISSUE THREAD

**Issue by Jehoel** [IdentityServer/IdentityServer4#3469]
(My code for this functionality is already written, but I'd like to know if you would be receptive to me submitting a PR for this - no point me wasting time otherwise, y'see!)

A comparison of my fork's branch with the main repo is available here: https://github.com/IdentityServer/IdentityServer4/compare/3f98f07e3fbb922090c089b68812eb4739506fac...Jehoel:demo/3469 

**Is your feature request related to a problem? Please describe.** + **Describe the solution you'd like**

I've extended my IS4 service to add a "refresh_token introspection" endpoint that lets authenticated clients get information about the lifetime and history of a `refresh_token`. (This functionality is needed in my application because of UX and usability concerns about users suddenly finding their sessions invalidated without warning). This PR is not about refresh_token introspection (but if you'd like a PR for that for an "IdentityServer4.Extensions" project then I'd be happy to submit that too).

My current solution for implementing refresh_token introspection is an ugly hack involving reimplementing `IPersistedGrantStore`, `IRefreshTokenStore` and `IRefreshTokenService` and abusing DI to inject my functionality into IS4 while using stock, unmodified IS4 NuGet packages.

I can greatly simplify my implementation if IS4 made the following changes:

* Expose `TokenValidator` as a `public class` instead of `internal class` so I can subclass it.
    * Right now only `ITokenValidator` is available to implement and inject into DI. Because (to my knowledge) I cannot have multiple simultaneous registrations of `ITokenValidator` I cannot simply wrap the existing `TokenValidator`.
* Extend `IRefreshTokenStore`'s method parameters to add a `string reason` parameter which stores can use.
    * For example:
        * When `TokenValidator.ValidateRefreshTokenAsync` sees a refresh_token has expired then it currently calls `await _refreshTokenStore.RemoveRefreshTokenAsync(tokenHandle);`.
            * I'd change that to `await _refreshTokenStore.RemoveRefreshTokenAsync(tokenHandle, reason: "refresh_token_lifetime_expired");`
        * Similarly `DefaultRefreshTokenService.UpdateRefreshTokenAsync` calls `await RefreshTokenStore.RemoveRefreshTokenAsync(handle);` to expire a one-time-use refresh_token. I would change that to `await RefreshTokenStore.RemoveRefreshTokenAsync(handle, reason: "one_time_token_used");`.
        * Each call-site would have its own appropriate "reason" string. I did think about proposing these use an `enum` (e.g. `enum RefreshTokenRemovalReason { LifetimeExpired, OneTimeUse, SingleSignOut, ExplicitRevoked, User }`) but I understand that would cause maintenance issues and block new call-sites of `RemoveRefreshTokenAsync`.
    * I'd like to add the `reason` parameter to other "`FooStore`" interfaces too so other stores can appropriately handle different cases of token or data removal appropriately (e.g. logging to an audit table, etc).

**Describe alternatives you've considered**

Right now, just an ugly hack of DI and reflection which I'd really rather not have in my codebase.

**Additional context**

As I said, I've got these changes made to my local fork of IS4 if you would like to merge them - I can't use them from my own projects because I need to use the official NuGet versions of IS4.

My code is in my fork's branch here: https://github.com/Jehoel/IdentityServer4/tree/demo/3469

**Comment by brockallen** [comment]
So in short, you're looking for an endpoint to determine a refresh token's expiration?

**Comment by Jehoel** [comment]
@brockallen No, I've already got that working using IS4's custom endpoint functionality - I just want to make my internal code easier by not having to use reflection and DI tricks. In short: please make the `TokenValidator` class public. I can make do without `reason` information for now.

**Comment by brockallen** [comment]
I think we have plans to rework this: https://github.com/IdentityServer/IdentityServer4/issues/1847

**Comment by Jehoel** [comment]
@brockallen Sure, if that means that `TokenValidator` will be public then that's fine.
