### ISSUE TITLE
The Error like this? 

### ISSUE THREAD

**Issue by woshilangdanger** [IdentityServer/IdentityServer4#3472]
![1](https://user-images.githubusercontent.com/35796921/61786676-c94e4280-ae40-11e9-966b-d1fb4226e75a.png)

**Comment by brockallen** [comment]
please provide more context.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by woshilangdanger** [comment]
> Closing. If you still have issues, feel free to reopen.

i have complete this problem.thanks!
