### ISSUE TITLE
Does GitVersion update your assembly/csproj automatically via the GitReleaseManager.yaml?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#3474]
If so, where is that done? I do not see the GitVersion MSBuild NuGet, or the GitVersion.exe command anywhere in the project.

How is the package version incremented? What am I missing?

**Comment by VictorioBerra** [comment]
I notice we are using this: https://github.com/adamralph/minver

And I notice theres a build task here https://github.com/IdentityServer/IdentityServer4/blob/master/src/Directory.Build.targets#L46

But im not sure how this eventually makes it way into the final nuget package.

**Comment by leastprivilege** [comment]
MinVer is doing all the magic. Check their docs.

GitReleaseManager is unrelated (it's for release notes).
