### ISSUE TITLE
Quickstart.UI signout-redirect.js does not need load event

### ISSUE THREAD

**Issue by ArturDorochowicz** [IdentityServer/IdentityServer4#3475]
Recent change in `signout-redirect.js` file in Quickstart.UI replaces `window.addEventListener()` with `$()` [1]. I think none is necessary actually.

As far as I see, in all scenarios the script is included after the relevant anchor element in the DOM. Therefore it's safe to just query for the element. In fact this is pretty much exactly what is done in the sibling file `signin-redirect.js` [2].

[1] https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/commit/bedfed33462f4223bee4a0519c361c59aa8d3753
[2] https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/bedfed33462f4223bee4a0519c361c59aa8d3753/wwwroot/js/signin-redirect.js

**Comment by brockallen** [comment]
It needs to run after all the iframes are done running. That's wh originally it was running in the load event, but IE that runs before iframes are done, so jQuery's document ready event normalizes it across browsers and runs after the iframes are done.

**Comment by ArturDorochowicz** [comment]
I see. I did not realize this was about iframes. 

However, if that's the case then jQuery document ready handler is not appropriate, because it runs when "DOM is ready" which is earlier than "window is loaded". jQuery documentation hints at the difference (https://api.jquery.com/ready/):
> Browsers also provide the load event on the window object. When this event fires it indicates that all assets on the page have loaded, including images. 

and also (https://learn.jquery.com/using-jquery-core/document-ready/)

> Code included inside $( document ).ready() will only run once the page Document Object Model (DOM) is ready for JavaScript code to execute. Code included inside $( window ).on( "load", function() { ... }) will run once the entire page (images or iframes), not just the DOM, is ready.

If the change was due to IE7 not supporting `addEventListener` then maybe the old `attachEvent` will work instead? https://stackoverflow.com/a/6927800

**Comment by brockallen** [comment]
Yep, absolutely right. This is a bug.

**Comment by brockallen** [comment]
This change seems to correct the problem:
```
$("iframe.signout").load(function () {
    var a = document.querySelector("a.PostLogoutRedirectUri");
    if (a) {
        window.location = a.href;
    }
});

```

thoughts?

**Comment by ArturDorochowicz** [comment]
I was kind of hoping that you'd drop jQuery from here, because that is the only place it is used in the project and that would open the possibility of dropping it from the project altogether (I know that bootstrap.js depends on jQuery, but as far as I see it isn't used either).

When it comes to the code, I'd change `load(handler)` to `on('load', handler)`. The former doesn't exist in jQuery 3+.

Also , I'd say that if you use jQuery then let's use it, so:
1. the whole thing should probably be in a `ready` handler (I realize I said it wasn't needed, but if jQuery remains, then it's the appropriate solution)
2. replace `document.querySelector` with `$()`, for consistency

Feel free to close the issue.

**Comment by brockallen** [comment]
Well, as you saw it used to be the window.load event, but I changed it since I had customers saying load doesn't work properly in IE 11 (We don't care about older IE). I (incorrectly) assumed jQuery's ready event was better. So what native even works, do you suggest?

**Comment by ArturDorochowicz** [comment]
I don't know why I thought the change was triggered by having to work in IE7. My earlier mention of `attachEvent` is irrelevant then, I think. Sorry for the confusion. 

I just realized that the code above might not be correct. Looking at the code of `LoggedOut` view, the iframe and the link are both optional and independent of each other. So the redirect can't depend only on the iframe load, because that iframe might not be present on the page at all.

**Comment by brockallen** [comment]
Ok, so seems the load event is the right one (https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event), and was what I originally had. Le sigh. So whatever -- screw IE11 then.

**Comment by brockallen** [comment]
PR merged, thanks for the report on this.
