### ISSUE TITLE
AlwaysSendClientClaims vs ProfileService

### ISSUE THREAD

**Issue by cmerighi** [IdentityServer/IdentityServer4#3477]
Setting `AlwaysSendClientClaims` to `true` allows the *access_token* to be enriched with the claims of the requesting clients.  
During an introspection flow (WebAPI consumption) it turns out to be very convenient in order to make assumptions about the features of the requesting client alongside with the ones of the requesting user. Fine.  

From the **`ProfileService` perspective** the client_claims inclusion mechanism is:
- "transparent" when the system is building up the _access_token_ and the `IClaimsService` is in charge (that is when the context.Caller equals "ClaimsProviderAccessToken").
- "opaque" when the client is requesting for UserInfo (context.Caller equal to "UserInfoEndpoint"). I should then add the necessary logic to handle `AlwaysSendClientClaims` and eventually `ClientClaimsPrefix` :
```c#
public async Task GetProfileDataAsync(ProfileDataRequestContext context)
{
    var requestedClaimTypes = context.RequestedClaimTypes;
    var subjectId = context.Subject.GetSubjectId();
    User user = await _users.FindBySubjectIdAsync(subjectId);
    var issuedClaims = user.Claims.Where(c => requestedClaimTypes.Contains(c.Type)).ToList();
            
    // here's the custom logic needed to handle AlwaysSendClientClaims...
    if (context.Caller == "UserInfoEndpoint" && context.Client.AlwaysSendClientClaims && context.Client.Claims?.Count >0)
    {
        // ...together with the ClientClaimsPrefix manipulation.
        string prefix = context.Client.ClientClaimsPrefix ?? string.Empty;
        foreach (var clientClaim in context.Client.Claims)
        {
            string claimType = string.Concat(prefix, clientClaim.Type);
            issuedClaims.Add(new Claim(claimType, clientClaim.Value, clientClaim.ValueType, clientClaim.Issuer));
        }
    }
            
    context.IssuedClaims = issuedClaims;
}
``` 

Is there a way to (kind-of) synchronize the utilization of the `AlwaysSendClientClaims` flag among different contexts?

**Comment by leastprivilege** [comment]
You are confusing client and user claims.

The profile service is for user claims. Client claims were originally meant to be static - but you can dynamically set them using a custom token request validator.

**Comment by cmerighi** [comment]
I was mainly searching for the perfect place to include the client_claims in a response from the _UserInfo_ endpoint.
Tweaking the `UserInfoResponseGenerator` (by handling the client's `AlwaysSendClientClaims` in the `ProcessAsync` method) might be the case...
This way I'll let the ProfileService only manage the very user claims.

(The use case is a multi-tenant app with a CMS that filters content based on the ClaimsIdentity.)

**Comment by leastprivilege** [comment]
Not seeing the point - userinfo endpoint is for user claims (it is part of OIDC) - the client claims are just part of the access token.

**Comment by cmerighi** [comment]
I was comparing `/connect/introspect` and `/connect/userinfo` expecting a similar/coherent behavior.  
I [can see](https://tools.ietf.org/html/rfc7662#section-1) that the introspection is meant to ...introspect the access token slavishly, thus providing client_claims (if any); while the [userinfo endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo) just "returns Claims about the authenticated End-User" (given scope, etc...). It seems that my expectations weren't justified, even if the both responses still feed the claims of the authenticated user (in WebApi and ClientApp respectively).

Now I need to figure out how a good oidc citizen would include client_claims among the `ClaimsIdentity` ones, in the client app:  
- Parallel ClientCredentials flow while fetching the UserInfoEndpoint?  
- Introspection request directly from the Client?
...
