### ISSUE TITLE
Cannot redirect after allow permission

### ISSUE THREAD

**Issue by qianthinkover** [IdentityServer/IdentityServer4#3479]
Hi, I create IdentityServer and Client two projects when the web MVC project sign in by IdentityServer Project and allow the permission of this app. the identity server cannot redirect link to my web MVC client. there is one error 'Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.'.

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
