### ISSUE TITLE
identityserver4.readthedocs.io

### ISSUE THREAD

**Issue by LiamSmithEngland** [IdentityServer/IdentityServer4#348]
Would it be possible to add a link to https://vimeo.com/113604459 to the documents. Watching it gave me a far better understanding of the material. I know the examples re with IdentityServer3 however the concept are the same. Maybe a list of further reading/watching would be great.

**Comment by leastprivilege** [comment]
Will add a video section.

**Comment by leastprivilege** [comment]
done
