### ISSUE TITLE
Extension Grant with Authorization Code 

### ISSUE THREAD

**Issue by NarayanRG** [IdentityServer/IdentityServer4#3480]
I have implemented IExtensionGrantValidator, set up the Custom grant Type for the Client, registered in StartUp, I have 2 grant Types for the Client. 1) Authorization Code 2) Custom

Request is from my Angular App, I am using OIDC client libray

ValidateAsync method is not hit, am i missing anything

**Comment by brockallen** [comment]
Check your logs

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
