### ISSUE TITLE
Override sub claim value

### ISSUE THREAD

**Issue by Mich-b** [IdentityServer/IdentityServer4#3483]
**update: this question is only for the access token.** 

Is it possible to override the sub claim value with another value in the access token, or to remove it from the access token entirely?

For some API's, I'd like to use an identifier which is completely different from the primary key of the user for privacy reasons. It seems the sub claim is by default added to the id token (following the spec) but also to the access token (not sure why), and cannot be overridden easily. 

I'd love for the sub claim to follow the same logic as other claims before it's being added to the access token, meaning using the ApiClaims or ApiScopeClaims table, so that I can control myself whether or not the sub claim goes into the access token. Is this possible?

**Comment by leastprivilege** [comment]
The sub claim is special - we don't give you an easy way to change the behavior - because we think it is the right behavior ;)

If you absolutely want to change claims etc - IClaimsService or deriving from our DefaultClaimsService will give you that control.
