### ISSUE TITLE
upgrating to 2.5.0 from 2.3.2 - Unknown client or not enabled

### ISSUE THREAD

**Issue by parmarnishant** [IdentityServer/IdentityServer4#3484]
Here are my logs after i upgrade to 2.5.0

Unknown client or not enabled

[19:41:51 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
[19:41:51 ERR] Invalid client configuration for client js_oidc_mobile: AllowedCorsOrigins contains invalid origin: https://devsites.z6.web.core.windows.net/
[19:41:51 ERR] Unknown client or not enabled: js_oidc_mobile
{"ClientId":null,"ClientName":null,"RedirectUri":null,"AllowedRedirectUris":null,"SubjectId":"anonymous","ResponseType":null,"ResponseMode":null,"GrantType":null,"RequestedScopes":"","State":null,"UiLocales":null,"Nonce":null,"AuthenticationContextReferenceClasses":null,"DisplayMode":null,"PromptMode":null,"MaxAge":null,"LoginHint":null,"SessionId":null,"Raw":{"client_id":"js_oidc_mobile","redirect_uri":"https://localhost:44343/callback.html","response_type":"id_token token","scope":"openid profile email api1 api2.read_only","state":"6891afb4cbac471c8890f64752c06887","nonce":"a0d1f99aa31a412aa3d9c40c55cc8aeb"},"$type":"AuthorizeRequestValidationLog"}

**Comment by parmarnishant** [comment]
I am using InMemoryClients.
It is working in 2.3.2

Thanks,
Nishant

**Comment by brockallen** [comment]
Did you not notice your error?

>  [19:41:51 ERR] Invalid client configuration for client js_oidc_mobile: AllowedCorsOrigins contains invalid origin: https://devsites.z6.web.core.windows.net/

**Comment by parmarnishant** [comment]
Thanks @brockallen.
The same url was working in older version. 
Hence i ignored that error.
The issue is fixed now.
