### ISSUE TITLE
How should i license my authentication plugin?

### ISSUE THREAD

**Issue by codetrove-development** [IdentityServer/IdentityServer4#3487]
Hi,

I am currently developing an application which will provide an optional authentication layer plug-in using identity server. Clients may write their own authentication if they prefer and simply drop in the required dlls/js files. My product is licensed under a commercial license.

I have a few questions:
- Is it OK to ship this plug-in with the main product even though it is nearly all identity server 4 & the oidc javascript client code with wrappers while licensing my main product as a commercial product or should it be a separate download? 
- What license am I obliged to ship this plug-in with?
- Are there any other licensing requirements I should be aware of?

My product is quite a few months away from completion, however the auth is coming along and close to being finished. I am happy to privately provide you with the code when it's properly extracted (bit of tight coupling at the moment).

Thank you for your time.

**Comment by leastprivilege** [comment]
IS is Apache 2 licensed . you can do whatever you want with that. But you need to attribute the original authors.

**Comment by codetrove-development** [comment]
That's fine - do you have guidelines somewhere? Or is a license.txt dropped in the base file and mentions there adequate?

**Comment by leastprivilege** [comment]
Something like this

https://help.dropbox.com/accounts-billing/security/open-source-software
