### ISSUE TITLE
token issuer and token validator in one Asp.net core app?

### ISSUE THREAD

**Issue by Avareto** [IdentityServer/IdentityServer4#349]
I am very interested to use IdentityServer4’s token based authentication in combination with ASPIdentity (user store in Asp.net core) as a mobile backend solution project. The only drawback I see in most of the described samples and scenarios is that IdentityServer is always hosted as a separate server instance. Previous Aps.net solution offered token base authentication (JWT bearer token) in a “one” server instance (as an issuer and validator). Is there any reference or sample project available in Asp.net core and ASPIdentity that host both roles in one deployable sever instance? Or can I just merge the configuration stuff of both roles in one StartUp class? Does this make sense at all?

**Comment by brockallen** [comment]
You can host them together. It's just that as soon as you have more than one app or API, this hosting doesn't make sense anymore. Most real world scenarios host it separate.

**Comment by Avareto** [comment]
It depends. I assume that most of the projects that start from scratch want to start with one small and dedicated project host. I think, starting a project with three separate hosted apps (client, resource server and identity server) already in the beginning is way too complicated, difficult to debug and hard to maintain. I think you are right in the long term when everything has stabilized and as second app project is required that fulfills exactly the same security requirements. But this may take years. It would be really great if you could add as sample to your Identity4.Samples repro that host everything I one ASP.NET/ ASPIndentity core with host.

**Comment by leastprivilege** [comment]
Why do you need a sample for this?

You can simply merge everything to single project if you like.

**Comment by Avareto** [comment]
Sorry, but I don't think it's simple. I got lost when I was looking at all the different options and implementations. I would appreciate if you would post the Startup.cs as a starting point.

**Comment by leastprivilege** [comment]
So you are looking for a sample that uses IS4, ASP.NET Identity and web APIs in a single project?

**Comment by damienbod** [comment]
Here's an example:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/singleAppWithIdentityResourceClient/src/ResourceWithIdentityServerWithClient

I'll create a blog for this and merge it then.

Greetings Damien

**Comment by damienbod** [comment]
Blogged:
https://damienbod.com/2016/10/01/identityserver4-webapi-and-angular2-in-a-single-asp-net-core-project/
