### ISSUE TITLE
IdentityServer3/IdentifyServer4

### ISSUE THREAD

**Issue by rpetrusha** [IdentityServer/IdentityServer4#3492]
### Replace or add link to IdentifyServer4?

In <https://github.com/microsoft/dotnet/blob/master/dotnet-developer-projects.md>, IdentityServer3 is listed in the **Security/Identity Management** section. Do you want to replace the entry with IdentityServer4, or keep IdentityServer3 and add IdentifyServer4? In addition, there's currently no description.

If you'd like to update your information, we'd welcome a pull request.

**Comment by brockallen** [comment]
PR submitted. Thanks
