### ISSUE TITLE
How to get token of logged in user in login API

### ISSUE THREAD

**Issue by mayankgaur** [IdentityServer/IdentityServer4#3495]
We have added two Protected pages - "Customer Management" and "User Management" in MVC based solution of Identity server and related API in Identity server. Once user is logged into Identity server, we want to obtain access token in order to grant permission to Customer Management and User Management pages.

So, our question is how do we retrieve Access token in Identity Server?

**Comment by leastprivilege** [comment]
Like this?

https://identityserver4.readthedocs.io/en/latest/topics/tools.html

**Comment by mayankgaur** [comment]
Firstly thanks for your reply,Yes but I want to get same access token as what my spa is getting

**Comment by mayankgaur** [comment]
done i have resolved this by 
 var token = await _identityServerTools.IssueJwtAsync(500,
         new Claim[] { new Claim(JwtClaimTypes.Audience, "authorization"),

         new Claim(JwtClaimTypes.ClientId,"ecp_spa"),
         new Claim(JwtClaimTypes.Subject,user.SubjectId),
          new Claim(JwtClaimTypes.PreferredUserName,user.UserName),
          new Claim(JwtClaimTypes.Email,user.Email),
          new Claim(JwtClaimTypes.Id,user.Id)               

                });
