### ISSUE TITLE
Custom claims not present in API in hybrid asp.net identtiy client

### ISSUE THREAD

**Issue by anilchaulagain25** [IdentityServer/IdentityServer4#3496]
I am trying to implement identity server in Hybrid mode using AspNetIdentity with some custom claim using own custom profile service (implementing IProfileService) and UserClaimsPrincipalFactory to include the user input value into token. But I have faced a problem in two different scenarios.
Those added claims are not present in API but available in hybrid MVC application
They are:
When I register first services.AddScoped<IProfileService,MyProfileService>() then service.UseIdentityServer(..).AddProfileService<AppUser>() then, those claims key are present in API but not value(as it not hits the breakpoint in profile service).
In other case: I register service.UseIdentityServer(..).AddProfileService<AppUser>() then services.AddScoped<IProfileService,MyProfileService>() then, the breakpoints in profile service get hit and claim key value both not present in API.
I haved included those additional claims in userclaims of apiresources.

**Comment by anilchaulagain25** [comment]
In summary, how to add identity server claim (not static value, which is stored during the login by user input) value to access token in hybrid mode. In access token request we are unable to find the user context.

**Comment by anilchaulagain25** [comment]
@leastprivilege , isn't there any solution for custom user input claim into token in hybrid mode with asp.net identity implementation.

**Comment by leastprivilege** [comment]
The `IProfileService` is the place where claims get into tokens. That's where I would put my breakpoint to understand what's going on.

**Comment by anilchaulagain25** [comment]
Thanks @leastprivilege . But in our case, during the token request (ProfileDataRequestContext.caller=AccessTokenRequest).. we dont have have state of user. Becuase application server post the auth_code, client id and client secret. That's why we are unable to access the previous claim we issued to the client by user input.
What might be the solution?

**Comment by leastprivilege** [comment]
IIRC they should be on the Subject of the profile context.

**Comment by anilchaulagain25** [comment]
Thank you @leastprivilege . It worked.
