### ISSUE TITLE
No DefaultAuthenticateScheme found when using AddIdentityCore

### ISSUE THREAD

**Issue by mdmoura** [IdentityServer/IdentityServer4#3497]
### Issue / Steps to reproduce the problem

Create an application with Identity Server 4 and Asp.Net Core Identity simply using:

    dotnet new is4aspid

Then on Startup replace the code line:

    services.AddIdentity<ApplicationUser, IdentityRole>()

By:

    services.AddIdentityCore<ApplicationUser>()

Which is the Asp.Net Core option to use only User / Claims without Role.

### Exception

When I run the application I get the Exception: 

```
InvalidOperationException: No DefaultAuthenticateScheme found.
IdentityServer4.Services.DefaultUserSession.GetCookieSchemeAsync() in C:\local\identity\server4\IdentityServer4\src\IdentityServer4\src\Services\Default\DefaultUserSession.cs, line 114
```

I suppose this is a bug? 

Is there a way to solve this?

**Comment by brockallen** [comment]
Set the IdentityServer options' CookieAuthenticationScheme: http://docs.identityserver.io/en/latest/reference/options.html#authentication

**Comment by mdmoura** [comment]
@brockallen Do you have any example / template using AddIdentityCore instead of AddIdentity?

I am asking this because your answer helped me solving the problem but now a new one shows up:

    InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.SignInManager`1[Entities.User]' 
    while attempting to activate 'IdentityServer4.AspNetIdentity.ResourceOwnerPasswordValidator`

And I think more issues will come up as IdentityCore leaves some configuration out which is needed by IdentityServer.

**Comment by mdmoura** [comment]
I found a better way by using:

      .AddDefaultIdentity<User>()

Which allows to use User without Role and does not seem to miss any configuration needed by Identity Server.
