### ISSUE TITLE
Session Expiary

### ISSUE THREAD

**Issue by LiamSmithEngland** [IdentityServer/IdentityServer4#350]
Hopefully I am beginning to understand how things are working. When using an Implicit flow with my MVC website I want a short lifetime for my cookies. I want my users to have to sign in daily.

I can set the cookie lifetime of the MVC site by doing. (I have set the time span to be 1 minute for testing only)

```
 app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = "Cookies",
                ExpireTimeSpan = TimeSpan.FromMinutes(60)
});
```

When I examine  my cookie for the page I can see that my cookie expiration is set to be the next minute. When I check 5 minutes later the cookie has been renewed and set to expire in the next minute. 

So I am being signed in again. Where can I set the IdentityServer session lifespan?

I tried 

```
  app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
                AutomaticAuthenticate = false,
                AutomaticChallenge = false,
                ExpireTimeSpan = TimeSpan.FromMinutes(1)
            }); 
```

Sadly no joy.

**Comment by KeithBarrows** [comment]
Look for the sliding expiration.  I don't have the code up infront of me
but what you are seeing is a sliding renewal of the token.  I believe the
default is set to 30 days.  That is the property you need to set to 1 day,
set your expiration to 5 or 10 minutes.



[image: --]
Keith Barrows
[image: https://]about.me/kbarrows
<https://about.me/kbarrows?promo=email_sig>


On Tue, Sep 27, 2016 at 10:53 AM, LiamSmithEngland <notifications@github.com

**Comment by leastprivilege** [comment]
That's an ASP.NET Core question - not an issue with identityserver. Please use SO.
