### ISSUE TITLE
Remove Custom Grant from Discovery Document

### ISSUE THREAD

**Issue by bugnuker** [IdentityServer/IdentityServer4#3500]
Hello,

I have created a custom grant using IExtensionGrantValidator.

Is there a way to hide this custom grant or prevent this grant from showing up in the discovery document? 

Thanks!

**Comment by leastprivilege** [comment]
There's a config option to hide all extension grants. If you need more granularity you can derive from the standard DiscoveryResponseGenerator.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by bugnuker** [comment]
I'm having a hard time finding the documentation for that config option. Can you link me?

**Comment by leastprivilege** [comment]
it's on `IdentityServerOptions.DiscoveryOptions`
