### ISSUE TITLE
Change jwks_uri endpoint value 

### ISSUE THREAD

**Issue by chandrasoma-senani123** [IdentityServer/IdentityServer4#3501]
Hi
I am using a version of Identityserver4 for implementing Authorisation Server for Open Banking. To pass the OpenId Security Conformance test I need to change the base url of the "jwls_uri" endpoint to be something like "https://keystore.openbanking.org.uk/....". What's the best way to go about it without breaking existing client token validation please please?

**Comment by leastprivilege** [comment]
You can override/derive from our DiscoveryResponseGenerator.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by chandrasoma-senani123** [comment]
Hi, thanks for the reply and sorry for not getting back to you sooner as I was on holiday.
Unfortunately, I got an error when I overrode the  "jwks_uri" endpoint with a different url in the discovery document. This error occurs when calls an endpoint of a resource api (which is protected by IdentityServer 4). Probably when trying to validate an access token. I don't have the full error description on me at the moment but it's something to do with '[PII is hidden]'. I will post the full error message when I try again. Once again, thanks for your help.
