### ISSUE TITLE
Identity Server 4 is generating long values for"nonce" + "state" parameter 

### ISSUE THREAD

**Issue by clfilipe** [IdentityServer/IdentityServer4#3502]
I work for the Azure Identity Support Team and I am currently working with a customer where we are encountering the following issue:

Customer registered a custom application under his Azure AD.  When users access their application, using the app URL, it opens the Microsoft log-in screen, as expected. If one user tries to authenticate with wrong password it gives the option to reset the password, which is expected as well. When the user hits 'reset it now' button, he gets a Page not found error message. This password reset action generates a long URL that exceeds the minimum length of characters, reason why the page cannot be found. 

On the other hand, if a user does not use the application URL to reset his password, but for example azure.portal.com, he hits the 'reset it now' button and it works as expected. He is redirected to the SSPR page with no errors being prompt. 

For the non-working scenario, what we understood so far was that this is due to the maximum URL length limit that is being reached. The CTX parameter from https://login.microsoftonline.com/ is longer than expected. Also, this happens since the affected App is sending a "nonce" parameter + "state" parameter with too long values. This can be seen when capturing a Fiddler Trace. 

That being said, our suggestion was for the customer to reduce the size of the values (nonce and state) that are being emitted by the app: https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-openid-connect-code 
Nevertheless, customer informed me that they are using the open source Identity Server 4, which is generating those 2 parameters. 

Our question now is: I there any way to reduce the size of ‘nonce’ and ‘state’ parameter?
![SSPRNotFound](https://user-images.githubusercontent.com/44497350/62237241-8eac5300-b3c8-11e9-985f-d0ea1ead4c1a.PNG)

**Comment by brockallen** [comment]
> Our question now is: I there any way to reduce the size of ‘nonce’ and ‘state’ parameter?

This is not an IdentityServer issue. It's a problem with state management in how ASP.NET Core's OIDC plumbing works combined with a client application that needs to use upstream token servers with URL limits (most commonly with multiple federation hops). We do have a solution, though. From the docs: http://docs.identityserver.io/en/latest/topics/signin_external_providers.html#state-url-length-and-isecuredataformat

My question now is: AAD increased its URL limit. Why can't live?

**Comment by leastprivilege** [comment]
Any update?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
