### ISSUE TITLE
Logging IPAddress (and other data) for each app login

### ISSUE THREAD

**Issue by luis-cortina** [IdentityServer/IdentityServer4#3504]
Hi:

I have a requirement to log the IPAddress of the logged in user along with the clientId of the app it was logged into. The out of the box events give us everyting except the client.  Where would be the best place (or extensibility point) to place some code to save that into a DB?

Luis

**Comment by leastprivilege** [comment]
Check the docs on how to create a custom event

**Comment by luis-cortina** [comment]
The how is clear in the docs, the where is what was puzzling me. Imagine that IdSrv is protecting multiple apps, user logs into app 1 and sees the login page, if he goes to app 2 it wont show the login page as the user is already signed in, so raising that event in the login page wouldn't capture all scenarios.
Looking through the issues in the repo I found `IAuthorizeInteractionResponseGenerator` so I extend it this way:
```
public override async Task<InteractionResponse> ProcessInteractionAsync(ValidatedAuthorizeRequest request, 
            ConsentResponse consent = null)
        {
            var interactionResult = await base.ProcessInteractionAsync(request, consent);

            if (!interactionResult.IsError 
                && !interactionResult.IsLogin 
                && !interactionResult.IsRedirect)
            {
                await _dataStoreRepository.SaveLoginInformation(
                    request.Subject.FindFirst("sub").Value,
                    request.ClientId);
            }

            return interactionResult;
        }

```

It works for my use case that it will capture all the authorize requests wheter user is signed in or not.
I'm not completely sure about the if criteria but seems to work. Anything wrong with this approach?

**Comment by leastprivilege** [comment]
Yep. thats OK.

Technically it is not a login. But an authorize request.
