### ISSUE TITLE
Session_state is not received in implicit flow

### ISSUE THREAD

**Issue by GabrielMancik** [IdentityServer/IdentityServer4#3505]
I am using implicit flow to retrieve access token only. I want to implement single sign out but I do not receive session_state in authorization response. Does Identity Server require some configuration to manage sessions?

In this issue: #2287 session management extension is mentioned but I was unable to find out what that even is. 

Thanks.

**Comment by leastprivilege** [comment]
access tokens only is not OIDC - thus no authentication session. 

You need to ask for an id_token and the openid scope.

**Comment by mackie1001** [comment]
Also worth noting that client initiated single sign-out really needs the `id_token_hint` to be passed to get the desired UX anyway.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
