### ISSUE TITLE
Change EF stores to use SaveChangesAsync

### ISSUE THREAD

**Issue by mackie1001** [IdentityServer/IdentityServer4#3507]
Something tells me this has come up in conversation before but a search of the issues didn't reveal anything.

I'd like to politely request that the default shipping EF stores (e.g. https://github.com/IdentityServer/IdentityServer4/blob/2.4.0/src/EntityFramework.Storage/src/Stores/PersistedGrantStore.cs) use `SaveChangesAsync` instead of the synchronous `SaveChanges` method and also `ToListAsync` instead of `ToList` for queries.

I'm trying to ensure that our heavily trafficked application has as little blocking IO as possible and noticed this on my travels.

**Comment by brockallen** [comment]
dup: #2067

**Comment by mackie1001** [comment]
Thanks, I knew I'd seen it discussed.
