### ISSUE TITLE
IdentityServer4 Bearer token authentication does not work with .net 4.5.2 Web Api 

### ISSUE THREAD

**Issue by EvTestUser** [IdentityServer/IdentityServer4#351]
I am trying to use Identity Server 4 for Securing Web Api written in .Net 4.5.2, currently I am using the following code:

 ` public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
             app.UseIdentityServerBearerTokenAuthentication(new      IdentityServerBearerTokenAuthenticationOptions
              {
                  Authority = "http://localhost:5000"
              }); 
`
Once I try to call the Web Api with the valid Authorization header like:

Authorization: bearer xxx

Where xxx is the access token retrievd from IdSvr4. I get the following exception in the Api code:

Exception thrown: 'System.InvalidOperationException' in System.Core.dll

Can anyone please check on this issue.

**Comment by leastprivilege** [comment]
You probably already know that InvalidOperationException as the only info - is not enough.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by callranjithkani** [comment]
am also facing this issue , my sso proxy application developed by identityserver 4 with asp.net core, my few client applications are developed by core it's working fine, i try to include framework 4.5.2 developed client it throws error "Sorry, there was an error : invalid_request"

My client Code is app.UseCookieAuthentication(new CookieAuthenticationOptions
{
AuthenticationType = "Cookies",

        });
     

        app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
        {

            AuthenticationType = "oidc",
            SignInAsAuthenticationType = "Cookies",
            Authority = "http://localhost:4000", //ID Server SSO Server
            ClientId = "Reportaldev",
            ClientSecret = "secret",
            ResponseType = "code id_token",
            RedirectUri = "http://localhost:4002/signin-oidc", //URL of Client website
            Scope = "apiportal",
            AuthenticationMode= Microsoft.Owin.Security.AuthenticationMode.Active ,
          
        });
