### ISSUE TITLE
id_token_hint not being sent from IDS4 as an RP to my own OIDC Implementation

### ISSUE THREAD

**Issue by leninator** [IdentityServer/IdentityServer4#3510]
Hello I'm not sure if this is a bug or just me not understanding what I need to set up.

I have registered my own IDP against the quickstart as a third party provider using the following.

            services.AddAuthentication()
                .AddOpenIdConnect(ExternalAuthSchemes.MyIdp, "Test Idp", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.SignOutScheme = IdentityServerConstants.SignoutScheme;

                    options.Authority = myidpSettings.Authority;
                    options.ClientId = myidpSettings.ClientId;

                    options.CallbackPath = "/signin-myidp";

                    options.ResponseType = "id_token";

                    options.Scope.Clear();
                    options.Scope.Add("openid");
                });

This correctly allows me to connect to my idp, and sign-in via myidp as a third party. I'm using an RP to IDS4 that a user is then successfully authenticated against.

When I logout of my RP I see the following call, in Account/Logout

            return new SignOutResult(new List<string> { AuthorizationConsts.SignInScheme, AuthorizationConsts.OidcAuthenticationScheme },
                new AuthenticationProperties { RedirectUri = "/" });

This makes the following call correctly to the IDS4 endpoint.

> http://localhost:53142/connect/endsession?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fsignout-callback-oidc&id_token_hint=*original_id_Token*&state=CfDJ8MlKAZVqhlFGm_CZZYeHAZYkwbzkMnsREq4u4QeMZzglIRpjKB0I1XtgJWYx2LWNBGQeLFKRRfoWyXqysCNYFCfAs5DKWRN2rnkbGTyS7ktSFqdQ4w9xuhvnIRRF-Rom_F3zpFXPPExJQYs_W1JR4BA&x-client-SKU=ID_NETSTANDARD1_4&x-client-ver=5.2.0.0

My IDS4 quickstart then successfully recognizes it itself is an RP of 'myidp' and runs the below.

            if (vm.TriggerExternalSignout)
            {
                // build a return URL so the upstream provider will redirect back
                // to us after the user has logged out. this allows us to then
                // complete our single sign-out processing.
                string url = Url.Action("Logout", new { logoutId = vm.LogoutId });

                // this triggers a redirect to the external provider for sign-out
                return new SignOutResult(new List<string> { vm.ExternalAuthenticationScheme },
                    new AuthenticationProperties { RedirectUri = url });
            }

Which in turn sends a request to my end session endpoint which looks like this.

> https://localhost:44331/v1/account/logout?post_logout_redirect_uri=http%3A%2F%2Flocalhost%3A53142%2Fsignout-callback-oidc&state=CfDJ8MlKAZVqhlFGm_CZZYeHAZYa3IvPKIOMLauSUZ80C0eV3LM_ms7qeQxz55-eTNO5gEtGV0drAWU8HshaIAdAdSEN8U2SJrbDmT8kU-5m6seuyuMZel7xXKo2LqPzTlw1j-daGK0InXnWqSoVJLSclmljB5_W6jHOaDkZuI96esmrU8VI4dEjLui429yMZhI0OjpTrEWtTv02xjTTx4yhrsudFgNjlMijNoODMIMI6a5LeHIl-64MWNZMSVzyDMG211a8efh3YRR2xKUjvZlD3ArC1aNiVwOP7cLAC2J9vxS7IqRqy6_WXXhJFE7mEaBRInbGIICHmroxHTTcIBXpEJPLyaj2BTMEEqalMxQB0ZOuWzQZBqiejFAr1F0TaWHZ26Q1SkuNJ6nil5_baorT_VBMvKFfeY1ifLmQYxSa5M7CdG-xb2q-O1l3kvmrPXOMnpHxeSqt7wEQF5g20_pYB4--WL6xBbAf20wtj5PeA5S0m61lfwY_BFI5It5gCsEJ0m4bEa9UUCQp5AjPEo_UREfpFGtB-Ws3Mfe0rRAHCqsSexBe72eSj1NeFYLyvGOmSDKQVb8k3ceFCtmgXpG_hVxJy-AC6zZKogVZM4ntIBX2Lk7KhoYRW2NjQR_M6ASsmC7X1SqcFUSIfhTqRsork4CqIwyS9WTezF8HF15Smu4eYhjWEAOJb30tQjIcUOWS043EcBVHEA5sD3dmRl51ghndFL8VMAJ7xr7bGwLMfSg56TmaOhtTVhWRCZMozAUmGFRD7z6_ICro1sFdazusM_2IZmpSdZUTiY-C5Am4ip0rnn8eUXU2YRbuxw30p2OAfytj7SXrlC4Ij1N29yGmZ_E5iSmWn09e7STeKq1Zwv8Z3n7tTwqKkeSpVmgxbOxYHo09yCl29YlI9Go2SDaH64B4dMKgvgPg6IuC4aSjiyznLpUD8D6aEzn4R4I5D92C5r7mWgoTIe2CQJpogut411D0JTsI6HSpCMrw_wpmpnqDw3PXqtnEXx7ssF_L_rlEfm96jYuo8KghSEMKUZbuvUvdV8NGnl6xMoUmi6a4NkOm_xtXOc5T4eOnhPSpEmKtW-DzYvvyUmli2FcyioLBtqXbXXUS90o0yvqlHH6XokBJEZne273UdE7liKpNSUKoXFhA15q3-4H8f2HyzOoFchospXu_M3eQ9-JF0aPi-cK95Rl8ur5E5WHklG8j6OA_aiqeUmgpEer7wDtvUWIOSb20yr9w9_as894JLfynEonSrNXSTrEJ2B5UMtqXpkRp8kA2yze3MRsam82fWGo7RzAFT_IfOG_tvvUp1gmMXyOamawTkk4EkSnptAnfOBz0Dw&x-client-SKU=ID_NETSTANDARD1_4&x-client-ver=5.2.0.0 HTTP/1.1

For some reason the "id_token_hint" parameter isn't being sent, so I can't authenticate the post_logout_redirect_uri is allowed. Also the state parameter is huge compared to the previous call. Do you have any ideas what could be causing this? I'm assuming i've misconfigured something, although it could be a bug.

**Comment by leastprivilege** [comment]
Did you save the original id_token? Otherwise it cannot be sent back as the hint.

**Comment by leninator** [comment]
Hello Least Priveledge,

Thank you for your response. Initially I did not, however I added it and it still was no happening automatically. I added the following code and it is now working.

                    //Original code above here
                    options.SaveTokens = true;

                    options.Events = new OpenIdConnectEvents
                    {
                        OnRedirectToIdentityProviderForSignOut = OnRedirectToIdentityProviderForSignOut,
                    };
                });

And the method implementation...

        private async Task OnRedirectToIdentityProviderForSignOut(RedirectContext context)
        {
            context.ProtocolMessage.IdTokenHint = await context.HttpContext.GetTokenAsync("id_token");
        }

This works now, i'm still curious why it seemingly does this automatically from my RP to IDS4 without the need for the `OnRedirectToIdentityProviderForSignOut`. But does not seem to work from my IDS4 to my third party OP.

**Comment by leastprivilege** [comment]
Don't know. Should work automatically.
