### ISSUE TITLE
re-authenticate and post redirect back to app fails OpenId Connect & IdentityServer4

### ISSUE THREAD

**Issue by leealexander** [IdentityServer/IdentityServer4#3515]
If a user is doing a post operation and the the OpenId middleware decides to redirect for authentication (access token might have expired); IdentityServer after this re-authentication redirects to the original post URL but without the original FormData causing my app to error. What is the recommended solution to this?

**Comment by brockallen** [comment]
This is not the responsibility of IdentityServer. That would be state your application needs to maintain across the OIDC protocol request.

**Comment by leealexander** [comment]
OK I figured as much... Just wanted to be sure!
