### ISSUE TITLE
Epic: New logging/auditing/events

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3518]
Current plan is:

* printf style logging must be trace/debug
* everything else will be fully structured data with typed classes using DiagnosticSource
* replace existing auditing plumbing

This will address the most common problems

* split low level logging from events/auditing
* filtering
* redacting certain values
* modifying log levels
* extensibility

Also look at new `EventCounter` API.

related:

https://github.com/IdentityServer/IdentityServer4/issues/2488
https://github.com/IdentityServer/IdentityServer4/issues/2714
https://github.com/IdentityServer/IdentityServer4/issues/3055
https://github.com/IdentityServer/IdentityServer4/issues/3155
https://github.com/IdentityServer/IdentityServer4/issues/3199

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/3771

**Comment by voroninp** [comment]
I work in a company which has eHealth products. Healthcare industry is strictly regulated, plus GDPR does not make our life easier. User may require to be completely forgotten by the system. (We had a couple of them already)
It means we need to delete or anonymise all the data containing any information which allows to identify the user. There are also restrictions on physical location of the storage with user data. If logs contain bits of personal data, they fall under this restriction.

Identity Server 4 logs user name without masking it, thus log entry contains both `subject id` and `user name`. This is invaluable for debugging and testing, but goes against the policy for production environment logs. I hope you agree that cleaning logs from user data is quite a challenging task.

Therefore in issue #3841  I request a feature which gives framework users possibility to preprocess logged entry and mask confidential data.
