### ISSUE TITLE
Epic: Re-design refresh token handling

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3519]
ideas

* keep history of refresh tokens to enable revocation in case the same token gets refreshed twice
* bind refresh token to session cookie for SPA scenarios (maybe less and less feasible with ongoing browser cookie hardening)

related

https://github.com/IdentityServer/IdentityServer4/issues/2610
https://github.com/IdentityServer/IdentityServer4/issues/3245

**Comment by brockallen** [comment]
* soft delete, and future RT usage has better logging

**Comment by leastprivilege** [comment]
Consider supporting scope parameter on RT requests

https://github.com/IdentityServer/IdentityServer4/issues/3644

**Comment by brockallen** [comment]
Related: #3354

**Comment by brockallen** [comment]
Related: #1056

**Comment by brockallen** [comment]
Related: #2976

**Comment by leastprivilege** [comment]
If the original token request was made using e.g. MTLS - we could bind the refresh token to the confirmation method - 

IOW - the client would need to use the same client certificate for refreshing the token as it used to request the initial token. Might be useful for public native clients where no client secret is used.

**Comment by brockallen** [comment]
related #1655

**Comment by brockallen** [comment]
#4206

**Comment by brockallen** [comment]
In a sense, the deleted (or enabled) flag from the grants table and the rework of the RT plumbing is related. I also think it means updating more store than just the RT store (maybe the authZ code store due to similar concerns?) to have not Get and Delete APIs, but more like GetAndDelete (as mentioned here  #1655 and related to #4213 and perhaps #3354).

**Comment by rob3c** [comment]
Is this a good place to ask about support for the two options in section 6 "Refreshing An Access Token" of the upcoming [OAuth 2.1 spec](https://tools.ietf.org/html/draft-parecki-oauth-v2-1-01#section-6)?

```
Authorization server MUST utilize one of these
methods to detect refresh token replay by
malicious actors for public clients:

   *  _Sender-constrained refresh tokens:_ the authorization server cryptographically binds the refresh token to a certain client instance by utilizing [I-D.ietf-oauth-token-binding] or [RFC8705].

   *  _Refresh token rotation:_ the authorization server issues a new refresh token with every access token refresh response.  The previous refresh token is invalidated but information about the relationship is retained by the authorization server.  If a refresh token is compromised and subsequently used by both the attacker and the legitimate client, one of them will present an invalidated refresh token, which will inform the authorization server of the breach.  The authorization server cannot determine which party submitted the invalid refresh token, but it will revoke the active refresh token.  This stops the attack at the cost of forcing the legitimate client to obtain a fresh authorization grant.
```

I'm not sure about "sender-constrained refresh tokens", but is "refresh token rotation" already covered by the`TokenUsage.OneTimeOnly` setting?

(In any case, those keywords should probably be in the docs/repo somewhere for searchers like me.)

**Comment by brockallen** [comment]
We added `ConsumedTime` and use that instead of deleting refresh tokens when consumed. They will only be deleted via `TokenCleanupService` after the expiration.

**Comment by rob3c** [comment]
@brockallen I've looked through commit #4428 and see `ConsumedTime` added to the model, but I don't see anywhere that it's assigned a meaningful non-null value or is used somehow to implement the refresh token rotation strategy required in the OAuth 2.1 draft spec as quoted above.

Can you help clarify for me how it's intended to solve that?

Or were you just making an unrelated announcement about the refresh token re-design progress to update everyone in the thread, and I misinterpreted it following my question as a direct reply? Thanks in advance.

**Comment by brockallen** [comment]
There's an open PR with it.
