### ISSUE TITLE
Authorization Policy with JWT Token and Identity Server 4

### ISSUE THREAD

**Issue by abdelkaderbenabdi** [IdentityServer/IdentityServer4#352]
I'm using Identity Server 4 for authenticating users from Angular 2 App and asp.net core. I'm declaring an authorization Policy on the asp.net core application so only some roles can access some api.

services.AddAuthorization(options =>
            {
                options.AddPolicy("AdminOnly", policyAdmin =>
                {
                    policyAdmin.RequireClaim("role", "Admin");
                });
            });

and adding the Jwt bearer authentication like this on the asp.net core app :
app.UseJwtBearerAuthentication(options);

So after authenticating with identity server 4, I receive an access token. this access token is used in angular 2 http header. but the asp.net core app never authorize the user for admin role even if I have the role claim in the access token.

Is there any configuration to add to the asp.net core app?

**Comment by damienbod** [comment]
Hi @abdelkaderbenabdi 
Have you added your policy to the authorize attribute in the controller?

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/blob/master/src/ResourceServer/Controllers/DataEventRecordController.cs

**Comment by abdelkaderbenabdi** [comment]
Hi @damienbod,

Yes I added the authorize attribute on the controller:
[Authorize("AdminOnly")]

I followed your article and the only difference is that I'm using Asp.net Core identity with mongodb as user store.

**Comment by leastprivilege** [comment]
Why is that an issue with IdentityServer? Wouldn't SO be the better place to discuss general ASP.NET Core questions?

**Comment by abdelkaderbenabdi** [comment]
You're right, it was a bad configuration of the asp.net core application authentication middleware.

**Comment by elfarouqy** [comment]
Hello,
Some body help me i can't get name after authentication
.net Core Server and Mvc 5 Net Client thanks to answer me
