### ISSUE TITLE
Epic: Re-write scope handling

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3520]
More flexible scope validation

* dynamic scopes?
* structured scopes?
* claims parameter in request object
* ignore unknown scopes?
* consider default resource scopes also for authorize endpoint (similar to token endpoint)

Evaluate resource indicator spec

* could work with current resource/scope model

related

https://github.com/IdentityServer/IdentityServer4/issues/2737
https://github.com/IdentityServer/IdentityServer4/issues/2763
https://github.com/IdentityServer/IdentityServer4/issues/3245

**Comment by leastprivilege** [comment]
Also: related to resource indicators 

https://tools.ietf.org/html/draft-ietf-oauth-resource-indicators-08

which is now in the queue to become an RFC

**Comment by leastprivilege** [comment]
Plan is to allow duplicate scope names - because there are scenarios where this makes sense.

But for most scenarios this is just a config bug. We need to add a config switch to validate that.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/3958

**Comment by brockallen** [comment]
PR submitted.
