### ISSUE TITLE
Add range AllowedCorsOrigin ?

### ISSUE THREAD

**Issue by darkurse** [IdentityServer/IdentityServer4#3522]
### Question / Steps to reproduce the problem
From last release we cannot specify wildcards for `AllowedCorsOrigin` ... justly so. However our identityserver4 instance is called behind a load balancer which works from a range of IPs.

**ie.** https:// 11.22.33.0 **/23** . So basically in a spirit of sparing anyone from doing the math:

- Start IP: 11.22.3**2.0** 
- End IP: 11.22.3**3.255**

And this is just for one client.  

Is there a concise way to specify this range other than adding 500 lines ?

**Comment by brockallen** [comment]
You could implement this yourselves by replacing the cors service in DI.
