### ISSUE TITLE
Dynamic Google's scope for each clients

### ISSUE THREAD

**Issue by PahmCougn** [IdentityServer/IdentityServer4#3528]
### Question / Steps to reproduce the problem

I 'm build SSO system allow user sign in by Google to access all my site.
Specially, I have three clients site (Client A,Client B,Client C) and Identity Server (IDServer)
+ Client A: allow user sign in by Google, access to Google Drive and get email, accessToken, Google's access_token, Google refresh_token from IDServer
```
// Google Scope
scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive openid"
```
+ Client B: allow user sign in by Google, access to Google Calendar and get email, accessToken, Google's access_token, Google refresh_token from IDServer
```
// Google Scope
scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/calendar openid"
```
+ Client C: allow user sign in by Google, only get email, accessToken from IDServer.
```
// Google Scope
scope: "https://www.googleapis.com/auth/userinfo.email openid"
```
+ IDServer: I config authentication by Google at `StartUp.cs`
```
services.AddAuthentication()
                .AddGoogle(options =>
                {
                    // register your IdentityServer with Google at https://console.developers.google.com
                    // enable the Google+ API
                    // set the redirect URI to http://localhost:5000/signin-google
                    options.ClientId = "<my-google-client-id>";
                    options.ClientSecret = "<my-google-client-secret>";
                    options.AccessType = "offline";
                    options.SaveTokens = true;
                });
```
**Issue**
Because each client need to access Google's resource different (Google Drive for Client A, Google Calendar for Client B), so after user login user show confirm permission access to them. I can add all Google's scope to `StartUp.cs` but if user access Client C, user also confirm permission access to Google resource (Google's resource difference (Google Drive for Client A, Google Calendar for Client B), it is incorrect.

**My question**:
+ How can I get Google's access_token, Google's refresh token on clients (Client A,Client B) from IDServer.
+ How can I dynamic add Google's scope for each request authentication from client (Client A,Client B or Client C).

Thanks

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
