### ISSUE TITLE
Should IClientStore return disabled clients?

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4#353]
Should implementations of [IClientStore](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Stores/IClientStore.cs) return clients that have been disabled (enabled == false)?

Currently the [InMemoryClientStore](https://github.com/IdentityServer/IdentityServer4/blob/ccb9cfc407aea220f7d654bec100a1bde41a640b/src/IdentityServer4/Stores/InMemory/InMemoryClientStore.cs) does this check, whilst the [EntityFramework](https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Stores/ClientStore.cs) and [Cached](https://github.com/IdentityServer/IdentityServer4/blob/ced9f22cc4bd64402605f3ee7265cfc95cfa68ee/src/IdentityServer4/Stores/Caching/CachingClientStore.cs) implementations do not.

Some classes that use IClientStore already perform this check alongside the usual null check (e.g. [DefaultCustomTokenValidator](https://github.com/IdentityServer/IdentityServer4/blob/ced9f22cc4bd64402605f3ee7265cfc95cfa68ee/src/IdentityServer4/Validation/DefaultCustomTokenValidator.cs)), whilst others do not (e.g. [ClientSecretValidator](https://github.com/IdentityServer/IdentityServer4/blob/ced9f22cc4bd64402605f3ee7265cfc95cfa68ee/src/IdentityServer4/Validation/ClientSecretValidator.cs)).

The same will apply for the IScopeStore.

**Comment by leastprivilege** [comment]
I think we need to check all usages of scopes and clients and do the checks in core - and not rely on store implementation. Opinions?

**Comment by scottbrady91** [comment]
Agreed, it's a simple enough check and the IClientStore is a popular extensibility point. There's no guarantee that only enabled clients will be returned and the method name of `FindClientById` does not suggest that it should to implementers.

**Comment by leastprivilege** [comment]
done on dev
