### ISSUE TITLE
IS4 + Katana

### ISSUE THREAD

**Issue by borisgr04** [IdentityServer/IdentityServer4#3530]
IdentityServer3 .AccessTokenValidation 2.14.0 and Katana/Owin is compatible con IdentityServer4. ?

It does not work for me.

in the examples you have use IdentityServer3.AccessToken 2.15.1.

**Comment by leastprivilege** [comment]
This repo is about IdentityServer4.

Check this test project
https://github.com/IdentityServer/CrossVersionIntegrationTests
