### ISSUE TITLE
Consider breaking change for validation key registration

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4#3532]
The JWKS endpoint currently returns the same `alg` value for all keys. This means that IdentityServer doesn't currently support multiple validation keys with different signing algorithms.

Validation keys are currently loaded without knowledge of their signing algorithm.

## Required breaking changes
- Update validation key registrations to include signing algorithm
- Update validation key store to remember signing algorithm

## Failing unit test
For `DiscoveryEndpointTests.cs`:
```
[Fact]
public async Task Jwks_with_two_key_using_different_algs_expect_different_alg_values()
{
    var ecdsaKey = CryptoHelper.CreateECDsaSecurityKey();
    var rsaKey = CryptoHelper.CreateRsaSecurityKey();

    IdentityServerPipeline pipeline = new IdentityServerPipeline();
    pipeline.OnPostConfigureServices += services =>
    {
        services.AddIdentityServerBuilder()
            .AddSigningCredential(ecdsaKey, "ES256")
            .AddValidationKeys(rsaKey);
    };
    pipeline.Initialize("/ROOT");

    var result = await pipeline.BackChannelClient.GetAsync("https://server/root/.well-known/openid-configuration/jwks");

    var json = await result.Content.ReadAsStringAsync();
    var jwks = new JsonWebKeySet(json);

    jwks.Keys.Should().Contain(x => x.KeyId == ecdsaKey.KeyId && x.Alg == "ES256");
    jwks.Keys.Should().Contain(x => x.KeyId == rsaKey.KeyId && x.Alg == "RS256");
}
```

**Comment by scottbrady91** [comment]
@leastprivilege This one's for v3. It blocks the migration path from RS256 to other signing algorithms

**Comment by leastprivilege** [comment]
Yep - will look into it next week.

**Comment by leastprivilege** [comment]
Do we really need the `alg` on the key? spec says it is optional...

**Comment by scottbrady91** [comment]
ASP.NET works fine without it. It's not required in COSE either, but scoping a key to an `alg` seems to be a norm across the industry.

**Comment by leastprivilege** [comment]
Done. Could you add above test?
