### ISSUE TITLE
Consider breaking change for supporting multiple signing keys

### ISSUE THREAD

**Issue by scottbrady91** [IdentityServer/IdentityServer4#3533]
Currently, only a single signing key can be registered, and therefore only a single signing algorithm supported.

To improve compatibility, we could allow multiple signing keys & algorithms to be registered. A default algorithm could be set and then overridden on a per client basis.

**Comment by scottbrady91** [comment]
(one for v4)

**Comment by brockallen** [comment]
Merged.
