### ISSUE TITLE
Identity Server not working with base path

### ISSUE THREAD

**Issue by Prince269090** [IdentityServer/IdentityServer4#3536]
Hi,

I am trying to run identity server with base path, behind the nginx ingress controller. I am using below code to set the base path. But still i am not able to access the identity server with base path. Example [here](http://edf.eastus.cloudapp.azure.com/identity)
```

public class PublicFacingUrlMiddleware
    {
        private readonly RequestDelegate _next;
        private readonly string _publicFacingUri;

        public PublicFacingUrlMiddleware(RequestDelegate next, string publicFacingUri)
        {
            _publicFacingUri = publicFacingUri;
            _next = next;
        }

        public async Task Invoke(HttpContext context)
        {
            var request = context.Request;

            context.SetIdentityServerOrigin(_publicFacingUri);
            context.SetIdentityServerBasePath(request.PathBase.Value.TrimEnd('/'));

            await _next(context);
        }
    }
```

I am getting wrong mime type while accessing the resources. Below is the startup.cs file registered middleware.

          `  app.UseMiddleware<PublicFacingUrlMiddleware>("http://edf.eastus.cloudapp.azure.com/identity");
`

**Comment by brockallen** [comment]
Check the archives, please. This has come up before.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
