### ISSUE TITLE
IdentitServer4 error MSB3073 during build

### ISSUE THREAD

**Issue by kitingChris** [IdentityServer/IdentityServer4#3537]
Hi, I am trying to get the IdentitServer4 setup in a docker container. But running builds exits with an error
```
/opt/IdentityServer4 # ./build.sh 

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

Configuring...
--------------
A command is running to populate your local package cache to improve restore speed and enable offline access. This command takes up to one minute to complete and only runs once.
Decompressing 100% 7279 ms
Expanding 100% 10921 ms

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
/root/.nuget/packages/minver/1.1.0/build/MinVer.targets(38,5): error MSB3073: The command "dotnet "/root/.nuget/packages/minver/1.1.0/build/../minver/MinVer.dll" --auto-increment "" --build-metadata "" --minimum-major-minor "" --repo "/opt/IdentityServer4/src/Storage/build" --tag-prefix "" --verbosity "" --version-override """ exited with code 134. [/opt/IdentityServer4/src/Storage/build/build.csproj]

The build failed. Please fix the build errors and run again.
An error occured.
```
```
/opt/IdentityServer4 # dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.107
 Commit:    2212cac826

Runtime Environment:
 OS Name:     alpine
 OS Version:  3.9
 OS Platform: Linux
 RID:         alpine.3.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.107/

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.107 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by brockallen** [comment]
Can you get a non-IdentityServer project building in a docker conatiner?

**Comment by ClientIco** [comment]
Hi I got this after I deleted the Global.json file, but before this I had the thing complaining about not being able to find 

{   "sdk": {     "version": "2.2.107"   } } 

A compatible SDK version for global.json version: [2.2.107] from [] could not be found. 

So I found that if I run Build.sh on my machine it builds. But within docker image microsoft/dotnet:2.2-sdk it give the above error.

**Comment by brockallen** [comment]
> A compatible SDK version for global.json version: [2.2.107] from [] could not be found.

You need that exact SDK to build it then.

**Comment by ClientIco** [comment]
It has to do with minver ?
So I made a docker image with the correct SDK, but I keep on getting :

`$ echo $PWD
/builds/Clientico/IdentityServer4
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.107
 Commit:    2212cac826

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.107/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.2.107 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
$ ./build.sh
/root/.nuget/packages/minver/1.1.0/build/MinVer.targets(38,5): error MSB3073: The command "dotnet "/root/.nuget/packages/minver/1.1.0/build/../minver/MinVer.dll" --auto-increment "" --build-metadata "" --minimum-major-minor "" --repo "/builds/Clientico/IdentityServer4/src/Storage/build" --tag-prefix "" --verbosity "" --version-override """ exited with code 134. [/builds/Clientico/IdentityServer4/src/Storage/build/build.csproj]

The build failed. Please fix the build errors and run again.
An error occured.`


Here is the docker file I used to have an image in which I can build-->


`FROM buildpack-deps:stretch-scm

# Install .NET CLI dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libc6 \
        libgcc1 \
        libgssapi-krb5-2 \
        libicu57 \
        liblttng-ust0 \
        libssl1.0.2 \
        libstdc++6 \
        zlib1g \
    && rm -rf /var/lib/apt/lists/*

# Install .NET Core SDK
ENV DOTNET_SDK_VERSION 2.2.107

RUN curl -SL --output dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-x64.tar.gz \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

# Configure web servers to bind to port 80 when present
ENV ASPNETCORE_URLS=http://+:80 \
    # Enable detection of running in a container
    DOTNET_RUNNING_IN_CONTAINER=true \
    # Enable correct mode for dotnet watch (only mode supported in a container)
    DOTNET_USE_POLLING_FILE_WATCHER=true \
    # Skip extraction of XML docs - generally not useful within an image/container - helps performance
    NUGET_XMLDOC_MODE=skip

# Trigger first run experience by running arbitrary cmd to populate local package cache
RUN dotnet help`

**Comment by leastprivilege** [comment]
@adamralph

**Comment by adamralph** [comment]
@kitingChris @ClientIco I'm not much of a Docker expert, but I just tried the build on a pristine Linux Mint 19.2 machine with only .NET SDK 2.2.107 and it worked perfectly. I suspect that something isn't quite right with the Docker container.

If it helps, https://github.com/SQLStreamStore/SQLStreamStore are running their CI in a Docker container, and they are using MinVer. Perhaps you can look there for some pointers?

Also, would you be able to connect to the Docker container interactively and running the following, and see if you get the same error? It may gives us more information.

```
dotnet tool install -g minver-cli
minver
```

**Comment by leastprivilege** [comment]
Thanks @adamralph

**Comment by ClientIco** [comment]
@adamralph Thanks for the additional assistance. I just ran it and received this. I am still looking into it. Maybe this additional info will be insightful ->

> PS C:\Users\Jacobus Roos> docker  run -it registry.gitlab.com/clientico/identityserver4:buildimage-netcore-sdk-2.2.107-stretch-slim                                                                                                             root@a373deb7ab3d:/# dotnet tool install -g minver-cli                                                                  Tools directory '/root/.dotnet/tools' is not currently on the PATH environment variable.
If you are using bash, you can add it to your profile by running the following command:

cat << \EOF >> ~/.bash_profile
# Add .NET Core SDK tools
export PATH="$PATH:/root/.dotnet/tools"
EOF

You can add it to the current session by running the following command:

export PATH="$PATH:/root/.dotnet/tools"

You can invoke the tool using the following command: minver
Tool 'minver-cli' (version '1.2.0') was successfully installed.

**Comment by leastprivilege** [comment]
any update?

**Comment by ClientIco** [comment]
On local machine when running docker as mentioned above it works 100%. On Gitlab devops there seems to be some substitution happening on special characters. As soon as I get it to build in gitlab I will give feedback. If any other Team have successfully used Gitlab devops for building IdentityServer, please let me know as well! Thanks! I am almost sure it is something small :)

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by kitingChris** [comment]
Sorry for answering so late. With deleting global.json the built succeeded...
If you want to try yourself just create a Dockerfile in the project root (besides build.sh) with the following content:

```
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app
COPY . .
RUN rm global.json && ./build.sh
```

and run `docker build .`

This container just builds the nupkg. Runtime would be a separate step...
