### ISSUE TITLE
Token Error Response Status Code Change

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3541]
Hi,

I wanted to change the Status Code of the Token Response.

Eg : if the Token endpoint is called with incorrect client id then i expected to return status code 401 instead of 400

I wanted to change MTLS error response  as well.

Can you please help us how can we achieve this in identityserver4?

**Comment by brockallen** [comment]
> I wanted to change the Status Code of the Token Response.

That would be counter-spec, so we don't provide a way to change it.

**Comment by Sathiyanathan-Macro** [comment]
is it possible to change the MTLS error response status code?

**Comment by Sathiyanathan-Macro** [comment]
Thanks Brockallen,

We have modified the status code at our end.
