### ISSUE TITLE
Identity server 4 windows authentication using extension Grant not working

### ISSUE THREAD

**Issue by janardhanbikka** [IdentityServer/IdentityServer4#3543]
I have set-up Identity server 4 for client credentials and Implicit flows and all are working fine.Now I have written an extension grant to support windows authentication but it always return false from AuthenticateAsync in the ValidateAsync method.

My problem is same as the one mentioned in this post IdentityServer4 Resource owner password and Win auth: unauthorized

but none answered that post

public class WinAuthGrantValidator : IExtensionGrantValidator
    {
        private readonly HttpContext _httpContext;
        private readonly IClientSecretValidator _clientValidator;

        public string GrantType => "CustomWindowsAuth";

        public WinAuthGrantValidator(IClientSecretValidator clientValidator,IHttpContextAccessor httpContextAccessor)
        {
            _httpContext = httpContextAccessor.HttpContext;
            _clientValidator = clientValidator;
        }

        public async Task ValidateAsync(ExtensionGrantValidationContext context)
        {
            // validate client
            var clientResult = await _clientValidator.ValidateAsync(_httpContext);
            if (clientResult.Client == null)
            {
               // _httpContext.Response.StatusCode = 401;
                context.Result = new GrantValidationResult(TokenRequestErrors.InvalidClient);
                return;
            }

            var result = await _httpContext.AuthenticateAsync(AccountOptions.WindowsAuthenticationSchemeName);
            if (result?.Principal is WindowsPrincipal wp)
            {
                var roles = wp.Claims.ToList();

                var id = new ClaimsIdentity(AccountOptions.WindowsAuthenticationSchemeName);
                id.AddClaim(new Claim(JwtClaimTypes.Subject, wp.Identity.Name));
                id.AddClaim(new Claim(JwtClaimTypes.Name, wp.Identity.Name));
                if (AccountOptions.IncludeWindowsGroups)
                {
                    var wi = wp.Identity as WindowsIdentity;
                    var groups = wi?.Groups?.Translate(typeof(NTAccount),false);
                    if (groups != null)
                    {
                        roles = groups.Select(x => new Claim(JwtClaimTypes.Role, x.Value)).ToList();
                        id.AddClaims(roles);
                    }
                }
                context.Result = new GrantValidationResult(wp.Identity.Name, GrantType, roles);

            }
            else
            {

                await _httpContext.ChallengeAsync(AccountOptions.WindowsAuthenticationSchemeName);
                context.Result = new GrantValidationResult(TokenRequestErrors.UnauthorizedClient, "Invalid credential");
            }
        }
    }
Here is the identity server registration for the above

services.Configure<IISOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });

  var builder = services.AddIdentityServer(options =>
                {

                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;
                })
                .AddSigningCredential(Certificate.Certificate.LoadCertificateFromStore(thumbPrint, logger))
                .AddAspNetIdentity<TUserIdentity>()
                .AddIdentityServerStoresWithDbContexts<TConfigurationDbContext, TPersistedGrantDbContext>(configuration)
                 .AddExtensionGrantValidator<WinAuthGrantValidator>()
                .AddProfileService<CustomProfileService>();

this is the code from client

var client = new HttpClient(new HttpClientHandler
    {
        UseDefaultCredentials = true
    });

    var disco = await client.GetDiscoveryDocumentAsync(new DiscoveryDocumentRequest
    {
        Address = "http://marsdevhv020.identity.marsdev.co.nz",
        Policy =
        {
            RequireHttps = false
        }
    });

    var tokenResponse = await client.RequestTokenAsync(new TokenRequest
    {
        Address = disco.TokenEndpoint,
        GrantType = "CustomWindowsAuth",
        ClientId = "WindowsClient",
        ClientSecret = "WindowsClientSecret",
        Parameters =
        {
            { "scope", "TestApi.Read" }
        }
    });

    if (tokenResponse.IsError)
    {
        Console.WriteLine(tokenResponse.Error);
        Console.WriteLine("Press any key to exit!");
        Console.Read();
    }

    Console.WriteLine(tokenResponse.AccessToken);

It always return error as always result?.Principal is null

**Comment by janardhanbikka** [comment]
I have tested this further more and it is working only if the IdentityServer in IIS has windows authentication is enabled and anonymous authentication is disabled.

But we need to enable anonymous authentication as well as this is consumed by different people.
 Is this bug with Identity server 4?

**Comment by brockallen** [comment]
No it's not a bug. If you force authentication at your reverse proxy using its own scheme, then IdentityServer can't use its own cookie scheme. You need anon and windows auth in IIS, and you should trigger windows auth earlier in the pipeline -- the extension grant is too late.

But having said that, StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
