### ISSUE TITLE
Claims are empty in LocalApiAuthentication

### ISSUE THREAD

**Issue by Nastya-Scherbakova** [IdentityServer/IdentityServer4#3544]
I have an IS4 project with api. I tried to use `AddLocalApiAuthentication`, but it doesn't see the claims anyway. Then I tried to add it like I do on API's that are separated from IS4:
```
 services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;

            }).AddJwtBearer(options =>
            {
                options.Authority = Configuration["Auth"];
                options.RequireHttpsMetadata = false;
                options.Audience = "auth";
            });
```
But still claims are empty. Can you help me, please, to understand why it happens?

**Comment by git-net** [comment]
3.0 preview8?

**Comment by Nastya-Scherbakova** [comment]
> try change app.usexxx order
> app.UseRouting();
> app.UseAuthentication();
> app.UseAuthorization();

I tried to change it in a different orders but still claims are empty.

**Comment by Nastya-Scherbakova** [comment]
also tried to configure like this:
```
 services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
       .AddIdentityServerAuthentication(options =>
       {
           options.Authority = Configuration["Auth"];

           options.ApiName = "auth";
       });
```
Nothing changed

**Comment by brockallen** [comment]
Here's a sample that uses it: https://github.com/brockallen/IdentityServerAndApi/tree/master/IdentityServerHost

**Comment by leastprivilege** [comment]
any update?
