### ISSUE TITLE
Passing additional data with reference tokens

### ISSUE THREAD

**Issue by TrevorHerr** [IdentityServer/IdentityServer4#3548]
Is it possible to pass additional data with a reference token? So my token result looks something like this:

```
{
    "access_token": "...",
    "expires_in": 3600,
    "token_type": "Bearer",
    "scope": "api1",
    "custom_property": "custom value"
}
```
Thanks!

**Comment by brockallen** [comment]
Yes, no differently than with JWTs. Having said that, StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
