### ISSUE TITLE
AccessTokenType.Jwt AccessTokenLifetime not respected?

### ISSUE THREAD

**Issue by benhysell** [IdentityServer/IdentityServer4#355]
Example code - https://github.com/benhysell/QuickStartIdentityServer/tree/master/src

Not sure if I'm doing something incorrect, or there is an actual bug.

Take Quickstart 1, in ```config.cs``` for the IdenityServer and change ```AccessTokenLifetime = 6``` 
https://github.com/benhysell/QuickStartIdentityServer/blob/master/src/QuickStartIdentityServer/config.cs#L50

In our client add a loop around calling our WebAPI end point.
https://github.com/benhysell/QuickStartIdentityServer/blob/master/src/ClientApp/Program.cs#L36

Run the application and one will not see an Unauthorized response for about 5 minutes.

Change the ```AccessTokenType``` to ```AccessTokenType.Reference``` and run the same test.  One is able to access the WebAPI for about six seconds before receiving an Unauthorized, as expected.

Feels like they should both return an Unauthorized in about 6 seconds, unless I am missing something fundamental.

**Comment by leastprivilege** [comment]
The MS JWT handler has a default clock skew of 5 minutes.
