### ISSUE TITLE
3.0 Preview versions use .NETCoreApp 3.0 instead of netstandard2.1

### ISSUE THREAD

**Issue by kooshanabedian** [IdentityServer/IdentityServer4#3550]
Hi,
Just switched to netcore 3.0 preview to give it a try and found out that my class libraries referencing

- IdentityServer4.EntityFramework
- IdentityServer4.EntityFramework.Storage

do not compile. I noticed this [issue](https://github.com/IdentityServer/IdentityServer4/issues/1410) from version 2.0 with similar problem. Is this targeting intended to stick from now on? and if it is not, is that going to fix/last until 3.0 stable release?

**Comment by kooshanabedian** [comment]
Does this decision has anything to do with [this](https://github.com/aspnet/AspNetCore/issues/3754)?

**Comment by brockallen** [comment]
Yes, @leastprivilege knows more of the details, but yes I think so.

**Comment by leastprivilege** [comment]
ASP.NET Core 3 targets netcore3 only. Not sure where EF will land in the end. It seems they are targeting netstandard2.1 right now. If that's the case for RTM, we can do this as well.
