### ISSUE TITLE
Is it possible to use the accessToken or refreshToken to authenticate with identity server ?

### ISSUE THREAD

**Issue by harimtejada** [IdentityServer/IdentityServer4#3551]
I am developing a React Native App, that connects to a remote web api and also needs to show a secure web view.

Connecting to the remote api is working perfectly I can get and refresh the token.

My problem is that I want to use the same Identity to open/show a web view within the app.

What's the best approach to accomplish this ?

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
