### ISSUE TITLE
No default instance for IdentityServer4.Stores.IAuthorizationParametersMessageStore

### ISSUE THREAD

**Issue by bzamora** [IdentityServer/IdentityServer4#3552]
IdentityServer 2.5.2

When using StructureMap as DI (v1.4.0), receive an error for missing default instance of IdentityServer4.Stores.IAuthorizationParametersMessageStore

Can work around by creating a dummy implementation or downgrading to IdentityServer 2.4.0

### Issue / Steps to reproduce the problem

Using StructureMap as DI

### Relevant parts of the log file

```
-----------------------------------------------------------------------------------------------------
Build Error on Instance 'IdentityServer4.Services.ReturnUrlParser' 
    for PluginType IdentityServer4.Services.ReturnUrlParser
 - and Instance 'IdentityServer4.Services.DefaultIdentityServerInteractionService' for PluginType IdentityServer4.Services.IIdentityServerInteractionService

No default Instance is registered and cannot be automatically determined for type 'IdentityServer4.Stores.IAuthorizationParametersMessageStore'
There is no configuration specified for IdentityServer4.Stores.IAuthorizationParametersMessageStore


-----------------------------------------------------------------------------------------------------
Build Error on Instance 'IdentityServer4.Endpoints.AuthorizeCallbackEndpoint' 
    for PluginType IdentityServer4.Endpoints.AuthorizeCallbackEndpoint

No default Instance is registered and cannot be automatically determined for type 'IdentityServer4.Stores.IAuthorizationParametersMessageStore'
There is no configuration specified for IdentityServer4.Stores.IAuthorizationParametersMessageStore
```

**Comment by brockallen** [comment]
If you've not configured this feature, then there's no code path that triggers the use of this service. I guess in Automapper it's mandatory, whereas in ASP.NET Core DI that is not.

**Comment by brockallen** [comment]
We'll add a default.

**Comment by evereq** [comment]
Resolved it in my project using (in Startup.cs / ConfigureServices method)
```
 services.AddAuthorizationParametersMessageStore<DistributedCacheAuthorizationParametersMessageStore>()
```
(see https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Stores/Default/DistributedCacheAuthorizationParametersMessageStore.cs)

Think dummy implementation can be easy created from https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Stores/Default/QueryStringAuthorizationParametersMessageStore.cs

**Comment by brockallen** [comment]
Looking at this again, we're taking advantage of the support in ASP.NET Core DI for optional ctor params and the behavior is different based on the preseance/absence of the service in DI.

**Comment by brockallen** [comment]
PR added, but I'm not happy with it.

**Comment by leastprivilege** [comment]
Since a workaround exists, not sure we need to do anything for 3.1 - and re-visit for 4.0
