### ISSUE TITLE
.Net Identity Single Sign-out

### ISSUE THREAD

**Issue by Asherslab** [IdentityServer/IdentityServer4#3554]
Hi, i've been working on an implementation of IdentityServer4 (Major difference being that i'm using Razor) with .NET Core Identity, i have a webapp/client authing user via the implicit flow. 
My IS4 implementation is based off of the `IdentityServer4AspNetIdentity` template

Currently when i logout via the client, i am redirected to IS4, where the appropriate logout stuff happens, then i am redirected back to the client, properly logged out (this works fine).
However, if i go directly to the IS4 instance and hit logout and then navigate to the Client/webapp, i am still logged in, this is obviously incorrect.

I Have scoured the internet for the past two days, have found information on Federated sign-out, `FrontChannelLogoutUri` and `BackChannelLogoutUri`, iframes, and all sorts of other things, i have tried all of them, and yet this issue remains. So, i turn here, can you please help me understand what i'm missing in my code?

This is the client logout page:
https://github.com/ldtteam/ChatChain/blob/feature/seperate-accounts-from-webapp/WebApp/Pages/Account/Logout.cshtml.cs

This is the IS4 logout page:
https://github.com/ldtteam/ChatChain/blob/feature/seperate-accounts-from-webapp/IdentityServer/Pages/Account/Logout.cshtml.cs

Obviously the code changed tonnes of times while i was testing all the different possible solutions, this code is my original attempt, as the code only got more and more unreadable as i attempted further solutions.

I can answer any questions you may have, and provide any code you may need.
I apologise if i missed something extremely obvious, i did my best to read all the documentation and information on this topic.

**Comment by brockallen** [comment]
YOu need to render the iframe on the logged out view.

**Comment by Asherslab** [comment]
Thank you so much for that help.
I had done that several times, however i tried it again just now, and i realised that the iframe variable only gets set if you have logged in through the client (oidc), if you don't the iframe is null!
So, i've got this working. thanks so much, that was a stupid issue lol. hope that helps someone in the future though.

One quick question, if i have two clients authenticated (both going through the proper OIDC stuff) does two iframes get rendered? because i would assume not, given that the variable is a single url. not multiple. So, if not, which client would be logged out the first to go through OIDC, or the second? And is there a simple way to make sure both get logged out?

Thanks!

**Comment by brockallen** [comment]
No and yes :)

The one iframe will then contain the two iframes.

**Comment by Asherslab** [comment]
Oh, That's interesting and cool. Thanks for your help!
