### ISSUE TITLE
Mutual TLS Request Docs Clarification on Enabling MTLS for Certain Paths in .well-known List

### ISSUE THREAD

**Issue by jrovny** [IdentityServer/IdentityServer4#3557]
Regarding MTLS, the Identity Server [documentation]() says
>In IdentityServer, the mutual TLS endpoints are expected to be located beneath the path ~/connect/mtls. This means your web server can be configured to require mutual TLS for all requests at and below that path.

However, the [readme](https://github.com/blowdart/idunno.Authentication/tree/master/src/idunno.Authentication.Certificate) for the idunno.Authentication package referenced in the documentation says

>**Can I configure my application to require a certificate only on certain paths?**
>Not possible, remember the certificate exchange is done that the start of the HTTPS conversation, it's done by the host, not the application. Kestrel, IIS, Azure Web Apps don't have any configuration for this sort of thing.

I initially asked in other places but then I came across the quote from the idunno.Authentication readme and thought I'd ask here to get some clarification on the documents.

**Comment by brockallen** [comment]
> This means your web server can be configured to require mutual TLS for all requests at and below that path.

The above comment means something like this:

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/host/web.config#L14-L20

So we're only asking IIS at that path to force MTLS (since it's the one handling the TLS connection). I'm not sure if that's inconsistent with @blowdart's statement.

**Comment by jrovny** [comment]
Very interesting, that definitely clarifies things for me. Much appreciated. Given mutual TLS at specific endpoints is possible in IIS, as you've shown, I'm curious about blowdart's statement.

**Comment by brockallen** [comment]
Not sure if there's anything else we can do on this issue.
