### ISSUE TITLE
Generating Access Tokens (& refresh tokens) manually

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer4#356]
I am wondering if IS4 allows you to generate tokens manually, which I would like to use in my own custom scenario for authenticating with external providers. 
Let's assume we obtain an access token from google, and we want to validate and then generate an access token for our own app to the client. After the validation of google's token, how can we generate access & refresh tokens manually to the user?

**Comment by leastprivilege** [comment]
Using an extension grant. Check the docs.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by khushalpatel1981** [comment]
I am wondering, if implemented with asp.net identity core, how user would be registered, or where and how to call extension grant endpoint. should be from Account Controller?

**Comment by behrooz66** [comment]
@khushalpatel1981  have a look at this, not exactly what you are looking for but can be of your interest:
[here!](https://www.linkedin.com/pulse/securing-net-core-web-api-identityserver4-resource-owner-dalvandi?trk=mp-reader-card)

**Comment by bongia** [comment]
@leastprivilege can you provide an example?

**Comment by rwhertenstein2** [comment]
I just saw that there is an IRefreshTokenService that I will work on implementing next

**Comment by jongear** [comment]
@rwhertenstein2 were you able to get refresh tokens to work for you?

**Comment by Kaidanov** [comment]
Did anyone created refresh tokens manually at the end? Any examples ?

**Comment by redplane** [comment]
Same question. I wonder how to create `reference token` manually or not.

**Comment by renaudLVLP** [comment]
Same for me : how to generate a refresh token by code ;(

**Comment by behrooz66** [comment]
Hey guys, I am the one who created this thread. May I ask why do you guys need to generate the refresh token manually? Because I ended up not even needing it for my purpose!

**Comment by renaudLVLP** [comment]
Hi @behrooz66

My specific scénario is a native mobile app using Facebook login through native app. So I send the Facebook token to identity server to exchange for an access token ... and a refresh token.

I use the same kind of code than rwhertenstein2 ... just need to return both tokens as I don't use connect/token api.

**Comment by behrooz66** [comment]
Hey @renaudLVLP , Can you have a look at [this four piece article](https://www.linkedin.com/pulse/securing-net-core-web-api-identityserver4-using-owner-dalvandi-1/?trk=mp-author-card)? The part 3 includes adding external authentication through Google and the result does include RefreshToken delivering to the end user. 
However you better start reading it from the first part so you follow the logic. I wrote it years ago, which means it is using an older version of everything and you may need to do adjustment but the idea should be the same.

**Comment by renaudLVLP** [comment]
@behrooz66 I followed your article, part 3, works like a charm, I get my refresh token via connect/token for facebook auth ! Thanks a lot !!!

**Comment by behrooz66** [comment]
@renaudLVLP I am glad it came to use for someone!
