### ISSUE TITLE
Response headers on the callback

### ISSUE THREAD

**Issue by ventil8** [IdentityServer/IdentityServer4#3560]
I've noticed that during the callback part of the process (https://localhost:44353/connect/authorize/callback?) to get logged in the **Response Headers** and **CSP** changes. I need these to be consistent throughout the process but I cannot see where I can control this.

It doesn't seem to hit the SecurityHeadersAttribute code on the callback at all...

**Comment by leastprivilege** [comment]
`SecurityHeadersAttribute` is for UI parts only (when HTML gets rendered).

If you want to attach response headers - write a middleware to do it.
