### ISSUE TITLE
Logout not working in hrbrid client in production mode

### ISSUE THREAD

**Issue by anilchaulagain25** [IdentityServer/IdentityServer4#3564]
We are trying to implement identity server with hybrid client. In which the logout is working in local environment but not working in production mode. that is logout id is not present in production, hence we are unable to redirect to client.

**Comment by leastprivilege** [comment]
a) not enough information
b) this does not seem to be an issue with identity server since it is environmental.

Check 
https://identityserver4.readthedocs.io/en/latest/intro/support.html
for more support/consulting options
