### ISSUE TITLE
OptionsValidationException: The 'Instance' option must be provided. - AzureAD and IS4

### ISSUE THREAD

**Issue by GeordieStew** [IdentityServer/IdentityServer4#3567]
This fails with **OptionsValidationException: The 'Instance' option must be provided.**

I would like to use IS4 server and also have a web front end that uses AzureAD to authenticate to allow users to manage clients/resources etc

The site works without IS4. It works without AzureAD. But together it errors.

[https://github.com/GeordieStew/TestIS4Azure](url)

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!

**Comment by GeordieStew** [comment]
Maybe I didn't include enough information. It seems to be a bug as everything else works? Is it something that SHOULD work?

**Comment by leastprivilege** [comment]
I don't know exactly what you are trying to achieve.
