### ISSUE TITLE
PromptMode login not passed to login page

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#3571]
Since we strip login when redirecting to login, we lose the original prompt value. Find a way to pass the original value along.

**Comment by DLMRP** [comment]
Hi!
So...prompt=login parameter is not working now ? Is it right ?
I'm adding this parameter, but I cannot see it in the login url..

Thanks,

**Comment by leastprivilege** [comment]
It is working as described in the protocol - it re-triggers the authentication workflow.

**Comment by DLMRP** [comment]
You are right. It re-triggers the authentication workflow..

But I'd need to know if prompt=login was included by client...Is there any way to know that ?

Thanks!

**Comment by brockallen** [comment]
That's the purpose of this issue/enhancement.

**Comment by DLMRP** [comment]
Ok. It's clear!

Thanks.

**Comment by brockallen** [comment]
Do you have a use case you can describe why your login page need/wants this? I'm curious.
