### ISSUE TITLE
Identity server 4 not working signin?ReturnUrl=/connect after update IdentityServer4 package from 2.2.0  to 2.4.0

### ISSUE THREAD

**Issue by nikolay-dimitrov** [IdentityServer/IdentityServer4#3573]
Yesterday i have updated Identity server 4 to version 2.4.0 - the package also include one migration that has to be executed and applied to Indentity database (it added some columns to Client table and e.t). After the update of the version and deployment of to our dev server when request is perform durring the redirection to signin?ReturnUrl=/connect Identity server return 404. Front end is using oidc-client to comunicated with Indentity server. I want to point that before upgrading to 2.4.0 everything work as expected. If i nagivate manually to login page of Indentity server im able to load it correctly

I cannot find what goes wrong after the update of this package and i start to get feeling that is related to this migration that i executed its added default values to newly added columns and maybe some of them are not included to oidc-client

Please help me this drive me crazy

oidc-client settings

  const settings: UserManagerSettings = {
  authority: 'https://login.' + appConfig.config.mainDomain + '/',
  client_id: environment.clientId,
  client_secret: environment.clientSecret,
  redirect_uri: window.location.origin + '/auth-callback',
  post_logout_redirect_uri: window.location.origin + '/',

  // these two will be done dynamically from the buttons clicked, but are
  // needed if you want to use the silent_renew
  response_type: 'id_token token',
  scope: 'openid profile address test',

  // this will toggle if profile endpoint is used
  loadUserInfo: true,
  // silent renew will get a new access_token via an iframe
  // just prior to the old access_token expiring (60 seconds prior)
  silent_redirect_uri: window.location.origin + '/assets/silent.html',
  automaticSilentRenew: true,
  // will revoke (reference) access tokens at logout time
  revokeAccessTokenOnSignout: true,
  // this will allow all the OIDC protocol claims to be visible in the window. normally a client app
  // wouldn't care about them or want them taking up space
  filterProtocolClaims: false
};

Logs 
2019-08-29 10:44:27.890 +03:00 [DBG] Start authorize request protocol validation
2019-08-29 10:44:28.224 +03:00 [DBG] JSDevClient found in database: true
2019-08-29 10:44:28.232 +03:00 [DBG] client configuration validation for client JSDevClient succeeded.
2019-08-29 10:44:28.300 +03:00 [DBG] Found openid, profile, address identity scopes in database
2019-08-29 10:44:28.353 +03:00 [DBG] Found test API scopes in database
2019-08-29 10:44:28.366 +03:00 [DBG] Found openid, profile, address identity scopes in database
2019-08-29 10:44:28.370 +03:00 [DBG] Found metaformsmanagerapi API scopes in database
2019-08-29 10:44:28.380 +03:00 [DBG] Calling into custom validator: IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator
2019-08-29 10:44:28.432 +03:00 [INF] ValidatedAuthorizeRequest
{
"ClientId": "JSDevClient",
"ClientName": "JS dev client",
"RedirectUri": "https://test.test.app/auth-callback",
"AllowedRedirectUris": ["https://*.test.app/assets/silent.html", "http://mfm.localhost/callback.html", "http://mfm.localhost/auth-callback", "https://mfm.localhost/auth-callback", "https://test.test.app/assets/silent.html", "http://test.test.app/assets/silent.html", "https://test.test.app/auth-callback", "http://test.test.app/auth-callback", "https://*.test.app/auth-callback", "http://localhost:4200/auth-callback", "https://localhost:4200/auth-callback", "http://localhost:4200/assets/silent.html", "https://localhost:4200/assets/silent.html"],
"SubjectId": "anonymous",
"ResponseType": "id_token token",
"ResponseMode": "fragment",
"GrantType": "implicit",
"RequestedScopes": "openid profile address testapi",
"State": "dffeb4fca72e43afaecb5fb5daff2348",
"UiLocales": null,
"Nonce": "8dad56338d7f40b595a9f2d91aba18d0",
"AuthenticationContextReferenceClasses": null,
"DisplayMode": null,
"PromptMode": null,
"MaxAge": null,
"LoginHint": null,
"SessionId": null,
"Raw": {
    "client_id": "JSDevClient",
    "redirect_uri": "https://test.test.app/auth-callback",
    "response_type": "id_token token",
    "scope": "openid profile address testapi",
    "state": "dffeb4fca72e43afaecb5fb5daff2348",
    "nonce": "8dad56338d7f40b595a9f2d91aba18d0"
},
"$type": "AuthorizeRequestValidationLog"
}
 2019-08-29 10:44:28.497 +03:00 [INF] Showing login: User is not authenticated
2019-08-29 10:44:28.499+03:00 [INF] Cookies was not authenticated. Failure message: Unprotect ticket failed
2019-08-29 10:44:28.499 +03:00 [INF] Cookies was not authenticated. Failure message: Unprotect ticket failed
2019-08-29 10:44:28.499 +03:00 [INF] Cookies was not authenticated. Failure message: Unprotect ticket failed

**Comment by nikolay-dimitrov** [comment]
I just made some test with my local repo and local database - I have revert IdentityServer4 to 2.2.0 redirect work correctly then update to 2.3.0 with IdentityServer4.EntityFramework package also (this was required by not working AddConfigurationStore() and AddOperationalStore() was not found  https://github.com/IdentityServer/IdentityServer4/issues/3014). There are not changes over the code before update to 2.3.0 just executing the migration with changes that was included into 2.3.0. After migration was applyed over my local database - redirect to identity server to signin?ReturnUrl=/connect from oidc-client stop work. I can confrim that this migration cause the problem with 404 from oidc-client. Can someone please tell me what i should update over my Client columns in order to work as before please?

**Comment by nikolay-dimitrov** [comment]
I found what cause the problem but i dont know why 
    services.AddAuthentication(options => { options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme; })
                    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
                    {
                        //options.LoginPath = new PathString(Constants.SignIn);
                        //options.LogoutPath = new PathString(Constants.SignOut);
                        options.Cookie.SameSite = Microsoft.AspNetCore.Http.SameSiteMode.None;
                    });
Those 2 rows that are comment LoginPath(/signin) and LogoutPath(/signout) after i comment them everything work as expected.
Can some please give more information why i experience such behavior

**Comment by brockallen** [comment]
There's an old issue that describes the changes related to those settings. Have a look, as it describes how/what/why the changes were made.
