### ISSUE TITLE
Authority string validation

### ISSUE THREAD

**Issue by aTable** [IdentityServer/IdentityServer4#3575]
Hi, I recently spent several days (fml) debugging an issue where my API protected by identity server kept returning 
```
Bearer error=“invalid_token”, error_description=“The signature key was not found
```
errors in production. Naturally, there are many possibilities as to what this could be and it turned out my protected api had an issue in applying my production setting overrides causing it to be configured to an identity server authority at `""` empty string.

### Question / Steps to reproduce the problem
```
 services.AddAuthentication("Bearer")
                    .AddIdentityServerAuthentication(options =>
                    {
...
                        options.Authority = "";
                        options.ApiName = "api1";
...
                    });
```

Is there intended behaviour behind supporting null or empty strings for identity server authorities? A simple `string.IsNullOrWhitespace` would have saved many headaches.

**Comment by leastprivilege** [comment]
I am simply passing this on the Microsoft's JWT handler...

But if you feel that this would improve the library, please send a PR.

**Comment by leastprivilege** [comment]
Closing because wrong repo. Right repo is: 

https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation
