### ISSUE TITLE
Rename ApiResource constructor parameter claimTypes -> requiredClaimTypes

### ISSUE THREAD

**Issue by voroninp** [IdentityServer/IdentityServer4#3577]
**Is your feature request related to a problem? Please describe.**
It took me a while to understand what is the purpose of the `claimTypes` parameter of `ApiResource` constructor
I had to look into source code eventually where I saw items being added to `UserClaims` collection. The comment to `UserClaims` property is more insightful: 
> List of associated user claims that should be included when this resource is requested.

**Describe the solution you'd like**
So I suggest to rename `claimTypes` to `requiredClaimTypes` to convey the purpose more accurately, and maybe slightly improve documentation.

**Comment by leastprivilege** [comment]
That would be a breaking change. Feel free to add a comment to the docs via a PR.

**Comment by brockallen** [comment]
The comments added aren't quite right. We'll add them. Thanks.
