### ISSUE TITLE
Different initialization of the AccessTokenLifetime property in response generators

### ISSUE THREAD

**Issue by holydk** [IdentityServer/IdentityServer4#3578]
I need to configure token lifetime in TokenService in some situations. Token has the correct lifetime, but the "expires_in" property in response is different because of the different initialization.

1) good [AuthorizeResponseGenerator](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/ResponseHandling/Default/AuthorizeResponseGenerator.cs#L158)
2) not desirable [TokenResponseGenerator](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/ResponseHandling/Default/TokenResponseGenerator.cs#L139)

**Comment by leastprivilege** [comment]
for the token code path - the lifetime can be changed dynamically in a custom validator. That's why it is read from the request.

The fact that this is inconsistent with the authorize path is something we have to look into in the future.

**Comment by holydk** [comment]
@leastprivilege thank you for useful information.
