### ISSUE TITLE
IdentityServer4.Storage Dependency on Microsoft.AspNetCore.Authentication.Abstractions

### ISSUE THREAD

**Issue by CrossBound** [IdentityServer/IdentityServer4#3580]
### Question
I'm implementing custom storage using SQL Server (without EF) and I notice that the IdentityServer4.Storage nuget package is carrying a dependency on Microsoft.AspNetCore.Authentication.Abstractions. Because of the dependency it makes any of my libraries that deal with the storage interfaces have to also reference a bunch of ASP.NET Core libraries that are completely unnecessary. I looked through the code and could not find where this package is being referenced. 

Is there any reason this dependency can not be removed from the IdentityServer4.Storage library?

**Comment by leastprivilege** [comment]
I think that's an oversight - feel free to remove it in a PR.
