### ISSUE TITLE
ExternalController.callback for the Integrated Windows Authentication 

### ISSUE THREAD

**Issue by kevinlo** [IdentityServer/IdentityServer4#3581]
I am following the QuickStart codes to see how to implement Integrated Windows Authentication.

The ExternalController.Callback function is calling the FindUserFromExternalProvider to find the user from TestUserStore.

For the Windows Authentication case, does it need a user store?  Can it just get the ClaimsPrincipal from the AuthenticateAsync returned result to SiginAsync like below?  It seems works.

```
            var result = await HttpContext.AuthenticateAsync(IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme);

            var user = result.Principal;
            await HttpContext.SignInAsync(user);
```

**Comment by leastprivilege** [comment]
This logic is up to you - we are only providing a sample.

**Comment by kevinlo** [comment]
Ok.  I am looking for sample about Windows Authentication and it refers to use the ExternalController.  But the ExternalController is handling external authentication provider in general.  Just want to confirm if there is any special reason why Windows Authentication requires using user stores.  I'll close it.
