### ISSUE TITLE
how to close activated sessions and force user to re-enter his credentials?

### ISSUE THREAD

**Issue by elyasnew** [IdentityServer/IdentityServer4#3583]
One user can log in through multiple systems with various IP addresses, so is there any way to deactivate one of his sessions? (or all other sessions except the current logged in one) if yes, how?
The thing I want to do is exactly like Telegram which you are able to close any of your activated sessions.

**Comment by elyasnew** [comment]
any solution?

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!

**Comment by elyasnew** [comment]
You are saying that you, as the writer of this library, have no answer for this question??? And maybe someone in a stackoverflow knows??

**Comment by brockallen** [comment]
I'm saying that the issue tracker is mainly for bug reports and feature requests. There are other places to get help with with designing your application.

**Comment by elyasnew** [comment]
so the `question` label is useless then
