### ISSUE TITLE
DateTime Claims cannot be parsed directly

### ISSUE THREAD

**Issue by KunLee** [IdentityServer/IdentityServer4#3589]
Hi guys,

Trying to parse some datetime claims back to datetime type.
Adding the claim by
`claims.Add(new Claim(CustomClaimTypes.DateTimeValue, user.DateTimeValue.ToString("o")));`
Looks all good and checked from Client Side without any issue, the round-trip datetime string was correct.
But when I do authorization on operations and try to get the claims from AuthorizationHandlerContext by `_httpContextAccessor.HttpContext?.User.Claims`

I can see the Datetime string like this "\"2019-08-20T11:09:57.703\""
Does someone know why is like this? How shall I fix it?

Thanks

**Comment by KunLee** [comment]
Currently, I have to do this` dateTimeValue.Value.Replace("\"", "");`

**Comment by leastprivilege** [comment]
See if this changes anything:

``claims.Add(new Claim(CustomClaimTypes.DateTimeValue, user.DateTimeValue.ToString("o"), ClaimValueTypes.DateTime));``

**Comment by KunLee** [comment]
@leastprivilege  Tried that one, did not work. From client end, it was correct string. Just when trying to fetch claims from token in operation Authorizing, it cannot be transferred back as a normal string.

**Comment by leastprivilege** [comment]
Well - so this is not really an IdentityServer issue. Our responsibility ends when the token gets sent back to the client.

With the above change, I believe our serializer does the right thing. What you are seeing most probably happens during de-serialization on the client. You can have a look at the raw data with a tool like https://jwt.ms

**Comment by KunLee** [comment]
Yes, I assume this is a deserialisation issue of token to http context user claims. The token has no problem being tested by the online tool.
