### ISSUE TITLE
Token validation for local APIs services.AddLocalApiAuthentication()

### ISSUE THREAD

**Issue by nikolay-dimitrov** [IdentityServer/IdentityServer4#3590]
i have follow and implemented successfully generating local tokens that are used for local end points into Identity server itself http://docs.identityserver.io/en/latest/topics/add_apis.html

So far so good, is there any mechanism to detect durring the request made to those protected end points that token is expired. I have implemented this in my protected APIs with help from JwtBearerEvents which is triggered on OnAuthenticationFailed and im able to detect and redirect the user to given static page that his token is expired e.t.

Is there anyway to achive the same behaviour for those "local" tokens inside the Identity server ?
This is the code from my protected API that detect that token is expired.

    service.AddAuthentication(IdentityServerAuthenticationDefaults.Authentication 
    Scheme).AddIdentityServerAuthentication(options =>
          {
          // base-address of your identityserver
           options.Authority = currentAuthority;
           options.RequireHttpsMetadata = true;
          // name of the API resource
           options.ApiName = clientId;
           options.ApiSecret = clientSecret;
            options.JwtBearerEvents.OnAuthenticationFailed += async 
       (context) => {
                await OnAuthenticationFailed(context);
                return;
            };
        });

    public async Task OnAuthenticationFailed(AuthenticationFailedContext context)
    {
        if (context.Exception is SecurityTokenExpiredException expiredException)
        {
            context.Response.Headers.Add("Token-Expired", "true");
        }
    }

**Comment by leastprivilege** [comment]
Not right now.

Returning a 401 is typically enough to signal the client that a new token is needed.

**Comment by nikolay-dimitrov** [comment]
@leastprivilege tnx for the response. Is there any recommendation according this subject because according the article it is not good idea to use IdentityServerAuthentication handler or Microsoft’s JwtBearer

**Comment by leastprivilege** [comment]
As I already said - returning a 401 signals to the client that the credential it sent, is not valid - e.g. expired. I have never used a header to indicate that.

Currently there is no way to achieve what you are asking with the LocalApi feature. We can consider it for a future version.
