### ISSUE TITLE
.OrderBy in TokeCleanup's RemoveDeviceCodes method is missing

### ISSUE THREAD

**Issue by ducalai** [IdentityServer/IdentityServer4#3592]
An exception is fired when RemoveDeviceCodes method is called:
`Exception removing expired grants: Error generated for warning 'Microsoft.EntityFrameworkCore.Query.RowLimitingOperationWithoutOrderByWarning: Query: '(from DeviceFlowCodes x in DbSet<DeviceFlowCodes> where [x].Expiration < (Nullable<DateTime>)DateTim...' uses a row limiting operation (Skip/Take) without OrderBy which may lead to unpredictable results.'. This exception can be suppressed or logged by passing event ID 'CoreEventId.RowLimitingOperationWithoutOrderByWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.`

Can you please add an .OrderBy(...) before .Take(...), as you did it in RemoveGrants method ?

**Comment by brockallen** [comment]
Is there an exception? In the past I've always just seen this as a warning in the logs.

**Comment by ducalai** [comment]
Displayed in red in my logs. RemoveExpiredGrantsAsync() catches an exception and logs it as an error

**Comment by Krupasekhar** [comment]
Unable to run IS4 with this

**Comment by brockallen** [comment]
I can't repo this error. And as far as I can tell, it's in there already:

https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/TokenCleanup/TokenCleanupService.cs#L120

Any thoughts?

**Comment by ducalai** [comment]
At the time of my original post, we were running ASP.NET Core 2.2 and identityServer v2.5.2. TokenCleanup.cs class was missing line added in v3.0 https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/TokenCleanup/TokenCleanupService.cs#L120. 
Should be fixed now. I haven't check because I haven't switch to v3.0.* yet

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
