### ISSUE TITLE
Client stays logged in after calling end session endpoint

### ISSUE THREAD

**Issue by nkaenzig** [IdentityServer/IdentityServer4#3593]
My client calls the Identity Server end session endpoint using the signoutRedirect() of oicd-client-js method to log out. Looking at the sent request I see the id_token passed with the id_token_hint parameter and post_logout_redirect_uri hold the client uri to which IdentityServer redirects after logging out. 

This basically works, it logs the user out and redirects me to the specified URI, but I'm having the issue that the endpoint doesn't clear the cookie used to authenticate my client. So when I hit login after that, it will automatically log in the user that was logged in before without directing me to the log in page. 

On [https://github.com/IdentityModel/oidc-client-js/issues/507](url) basically the same issue is described, one user reports that he resolved it by making the following call on the server (in Account/Logout):
`await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);`

However, in my case I don't have this option, as the endpoint redirects me directly back to the client, without hitting the Account/Logout route in the backend. The Account/Logout route seems to be bypassed when the client sends the id_token with the request - **however I think in this case it would make sense for the endpoint to automatically clear the cookie**?

I tried to force IdentityServer to direct me to Account/Logout instead, where I could call SignOutAsync() manually before redirecting to the client. I tried to make a request without passing a post_logout_redirect_uri and setting AutomaticRedirectAfterSignOut=false & ShowLogoutPrompt=true in my AccountOptions. However, I couldn't prevent the bypassing of Account/Logout. In any case It seems to me that clearing the cookie automatically when bypassing Account/Logout is a missing feature/bug?

**Comment by brockallen** [comment]
You will have to look into how the OIDC spec allows for clients to receive notifications of sign out.

**Comment by nkaenzig** [comment]
> You will have to look into how the OIDC spec allows for clients to receive notifications of sign out.

My client gets a http-only cookie from IdentityServer - which by definition cannot be altered/deleted by javascript. So I feel it is the responsibility of IdentityServer to revoke the cookie, when a client calls its End Session endpoint - or am I getting something wrong here?

**Comment by brockallen** [comment]
Your logout page in IdentityServer is responsible for managing that. Have you seen how it works in our samples and quickstarts?

**Comment by nkaenzig** [comment]
The issue is that I don't have a logout page. Identity server redirects me directly back to the client. As I described above, I tried to make IdentityServer direct me first to a "logout"-route on the backend ("Account/Logout"), as it does when I log in (without having the cookie yet), but I couldn't achieve that. Is it documented somewhere how to do this?

I looked at all Quickstart packes an example codes. The quickstart that matches my usecase the most is the following:
http://docs.identityserver.io/en/latest/quickstarts/6_javascript_client.html

In this example after calling signoutRedirect on the client, IdentityServer displays a Logout page. I imagine, when the user clicks on the link to get back to the client, the method SignOutAsync() is called to revoke the cookie. 
However, I don't know how to tell IdentityServer to show me this Logout page instead of redirecting me directly to the client. As mentioned in the first post, changing AutomaticRedirectAfterSignOut=false & ShowLogoutPrompt=true in my AccountOptions doesn't work out. Also I'm not sure where to specify the route of my Logout page - I imagine it's hardcoded somewhere in the IdentityServer source code ("Account/Logout").

In any case, it would be a nice feature, if IdentityServer called SignOutAsync() by default when the End Session endpoint is called - in case that you want to bypass the Logout page and go directly back to the client page (which is a much nicer user experience...).

**Comment by brockallen** [comment]
> The issue is that I don't have a logout page. Identity server redirects me directly back to the client. 

That sounds like your problem. Why is there not logout page? As you should see in our quickstarts/samples, there is a logout page and it performs what you need.

**Comment by brockallen** [comment]
> In any case, it would be a nice feature, if IdentityServer called SignOutAsync() by default when the End Session endpoint is called - in case that you want to bypass the Logout page and go directly back to the client page (which is a much nicer user experience...).

This misses the bigger picture of single signout. It's more complicated.

**Comment by nkaenzig** [comment]
> > The issue is that I don't have a logout page. Identity server redirects me directly back to the client.
> 
> That sounds like your problem. Why is there not logout page? As you see in our quickstarts/samples, there is a logout page and it performs what you need. The page to redirect to is an option in our settings/config object model.

To me it seems unnecessary to have a log out page, and I see many pages on the web that direct you directly back to the /index page after hitting the "logout" button.
Even so I tried to set up a logout page, but I couldn't make IdentityServer make me redirect to this page after calling the End Session endpoint. - Is it documented somewhere how to do that, i.e. what exactly one has to configure?

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/latest/topics/signout.html

**Comment by nkaenzig** [comment]
> http://docs.identityserver.io/en/latest/topics/signout.html

Yes, this is exactly what i was trying to do:
Call SignOutAsync() to revoke the cookie before redirecting to the client. But I can't call this function because after calling the End Session edpoint, IdentityServer redirects me directly back to the client.

**Comment by brockallen** [comment]
>  Calling SignOutAsync() to revoke the cookie before redirecting to the client. But I can't call this function because after calling the End Session endpoint, IdentityServer redirects me directly back to the client.

That's just not how it's supposed to work. Are there logs indicating any more info? Or can you look at the http trace?

**Comment by nkaenzig** [comment]
> > Calling SignOutAsync() to revoke the cookie before redirecting to the client. But I can't call this function because after calling the End Session endpoint, IdentityServer redirects me directly back to the client.
> 
> That's just not how it's supposed to work. Are there logs indicating any more info? Or can you look at the http trace?

How is it supposed to work? The cookie has to be revoked at some point by IdentityServer. The client has no possibility to revoke it, as it's a http-only cookie.

I somehow managed to make it work now. It is crucial, that a Logout() method in the AccountController.cs exists. If no such method exists, IdentityServer wont redirect you to Account/Logout after the End Session endpoint was called. Within the Logout() method I called SignOutAsync() which as expected revoked the cookie, and then I just redirect back to the client.
On https://github.com/mmacneil/AngularASPNETCoreOAuth/issues/2 I described the solution with a bit more details.

In any case, if you see a better solution, I would be very interested.

**Comment by brockallen** [comment]
> I somehow managed to make it work now.

What's unclear to me is how you managed to get it to redirect to your client without IdentityServer's end session endpoint first redirecting to a logout page in your IdentityServer host.

**Comment by nkaenzig** [comment]
> > I somehow managed to make it work now.
> 
> What's unclear to me is how you managed to get it to redirect to your client without IdentityServer's end session endpoint first redirecting to a logout page in your IdentityServer host.

I did not manage to do that. What I'm doing is letting IdentityServer's Session Endpoint redirect my to Account/Logout in my AccountController.cs, but instead of showing a Logout view there, I call Redirect(context.PostLogoutRedirectUri) which redirects me to my client application. So for the user it feels like he's being redirected directly back to the client.

**Comment by brockallen** [comment]
Ok, this line:

> This basically works, it logs the user out and redirects me to the specified URI,

Is what I misunderstood then. I thought it meant you were successfully being redirected to the post_logout_uri after hitting the end session endpoint.

So starting over, please have a look at how the samples/quickstarts do it. You need a logout page in the hosted app, which the end session endpoint will redirect to. This is needed for the reasons mentioned in our docs.
