### ISSUE TITLE
Change Operational Store tables names and integrate with EF migrations command

### ISSUE THREAD

**Issue by mdmoura** [IdentityServer/IdentityServer4#3596]
I have an Entity Framework Core 2.2 DbContext as follows:

    public class MyContext : IdentityUserContext<User, Int32, UserClaim, UserLogin, UserToken> {
    }

And, using Identity Server 4, I would like to use OperationalStore so I added to my Auth project startup:

          services
            .AddIdentityServer()
            .AddSigningCredential(certificate)
            .AddInMemoryIdentityResources(Config.GetIdentityResources())
            .AddInMemoryApiResources(Config.GetApiResources())
            .AddInMemoryClients(Config.GetClients())
            .AddAspNetIdentity<User>()
            .AddOperationalStore(x => {
               x.ConfigureDbContext = y => y.UseSqlServer(connectionString);
               x.EnableTokenCleanup = true;
               x.TokenCleanupInterval = 30;
            });

What entities and configuration should I add to MyContext to support OperationalStore?

And can I change the names of the tables that support Operational Store? How?

Thank You

**Comment by brockallen** [comment]
> What entities and configuration should I add to MyContext to support OperationalStore?

This is already encapsulated in the call to `AddOperationalStore`.

**Comment by mdmoura** [comment]
> This is already encapsulated in the call to `AddOperationalStore`.

@brockallen Not sure I got it. I have `MyContext` in a class library ...

To create the migrations and the database I use the commands on the database:

    dotnet ef migrations add "FirstMigration"
    dotnet ef database update

How to ensure the SQL tables used by Identity Server are included in the migration and in the database update?

And is it possible to change the name of one of the SQL tables used by Identity Server?

**Comment by mdmoura** [comment]
In case I use only OperationalStore, and not configuration, wouldn't dbo.PersistedGrants be the only table / entity needed?
