### ISSUE TITLE
Admin UI -- free version for claims, tenants, roles, users

### ISSUE THREAD

**Issue by papyr** [IdentityServer/IdentityServer4#3597]
Hello, the lack of a proper UI is limiting much use of this. Skorba has a nice UI, but for simpler turnkey solutions thats not practical, ```
any chance this will get a full turn key UI with

claims, tenants, roles, users
```

**Comment by leastprivilege** [comment]
No. This is not on our roadmap. 

But you can get a full featured admin ui at

Https://IdentityServer.com
