### ISSUE TITLE
How much backward breaking/incompatible changes will there be in 3.0?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#3598]
I read on https://leastprivilege.com that we should "Stay on [IdentityModel] v3.x if you are using: IdentityServer4 v2.x"

This worries me because we have a ton of different apps using different flows, most use IdentityModel 3 and friends. I was hoping we could update IS4 to 3.0 when Core 3.0 released and nothing would break. 

Or maybe only specific things would break. So im hoping for some detailed clarification on what backwards incompatible changes will come with IS4 3.0. Sorry if I missed it, but I noticed you guys had a helpful issue a couple years ago for 2.0 https://github.com/IdentityServer/IdentityServer4/issues/1057

**Comment by leastprivilege** [comment]
We will add release notes that indicate breaking changes.
