### ISSUE TITLE
delegated access API

### ISSUE THREAD

**Issue by venkatrv** [IdentityServer/IdentityServer4#36]
Do you have a sample which can demonstrate the delegated access? meaning, user access token/credentials/claims should flow down to server 
say for example: from user to server1 to server2

And server2 in the above example can take decision whether to authorize particular user or not.

I am looking for 2 scenarios here: 
1) all server and user is in the same windows domain
2) all are in different windows domains

Thanks.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Multi%20Hop%20Delegation%20(ActAsCustomGrant)

**Comment by venkatrv** [comment]
Thanks. Is this sample is available for IdentityServer4?

**Comment by brockallen** [comment]
It's a sample in IdSvr3, but the mechanics are all roughly the same.

**Comment by venkatrv** [comment]
Ok, thanks. I have downloaded the ActAsCustomGrant sample. It has 4 projects: ConsoleClient, IdentityServer, WebApi1, WebApi2, WpfClient
all are using same port numbers: 44333.
I am wondering why IdentityServer project is here in the samples. So with this samples download, I don't need download and run the IdentityServer3? I am bit confused.. I wish there can be diagram which explains how this works.

**Comment by leastprivilege** [comment]
sorry - that's all we have right now.
