### ISSUE TITLE
best practices for one front end client and many micro services.

### ISSUE THREAD

**Issue by zuizuihao** [IdentityServer/IdentityServer4#3601]
We have one web and two back end service, user access web, request to the back end of web, some request is also depend on the data service.  now there are two option。
data_service -> web_back_end -> web

option 1: 
data_service and web_back_end  use the “Client credentials” grant type to authenticate and the client id is WebCalcDataApi

web and web_back_end  use the use  the "Authorization code" grant type to authenticate and the client id is WebCalcUI

option 2:
data_service, web_back_end and web  use the “Hybrid” grant type to authenticate and these three client use the same client WebCalc.

if there are best practices for this situation, especially when we apply microservices.

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
