### ISSUE TITLE
How to properly configure upstream identity providers for Federation Gateway architecture

### ISSUE THREAD

**Issue by EnricoMassoneDeltatre** [IdentityServer/IdentityServer4#3604]
Hi, 

we are writing an ASP.NET core 2.2 web application which is basically an identity provider implemented by using identity server 4. So, **this question is related to the identity provider application itself, not to the client application using the identity provider to sign in and access an API**. We are developing against identity server 4 version `2.5.3` (the latest stable version available).

We have used the [identity server 4 quickstart UI](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI) in order to provide a user interface.

The architecture we are implementing is the [federation gateway](http://docs.identityserver.io/en/latest/topics/federation_gateway.html), so we don't need to handle local users: the only way for a user to authenticate is using one of the configured upstream identity providers. 

Each deploy of this application will be able to configure the upstream identity providers dynamically; the idea is being compatible with any identity provider compliant with the open id connect protocol.

The high level plan is writing what follows inside the `Startup.ConfigureServices` method: 

```
var builder = services.AddAuthentication();

foreach (var provider in configuredProviders)
{
	builder.AddOpenIdConnect(provider.Key, provider.Name, options =>
	  {
		options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
		options.SignOutScheme = IdentityServerConstants.SignoutScheme;
		options.SaveTokens = true;

		options.ClientId = provider.ClientId;
		options.Authority = provider.Authority;
		options.ClientSecret = provider.ClientSecret;
		options.MetadataAddress = provider.MetadataAddress;

		options.CallbackPath = $"/signin-oidc-{provider.Key}";
		options.SignedOutCallbackPath = $"/signout-callback-oidc-{provider.Key}";

		options.Scope.Add("openid");
		options.Scope.Add("profile");
		options.Scope.Add("email");

		options.TokenValidationParameters = new TokenValidationParameters
		{
		  NameClaimType = "name",
		  RoleClaimType = "role"
		};
	  });
}
``` 

We want to keep this code **the bare minimum** needed to configure the external providers for identity server 4. We have started from [this sample](http://docs.identityserver.io/en/latest/quickstarts/4_external_authentication.html) and added the different options incrementally. 

We have the following questions: 

- is it really needed to specify **both** the `Authority` and the `MetadataAddress` ? Can we avoid specifying the `Authority` and leave the `MetadataAddress` only ? 
- we have found out that the different providers must have different values for the properties `CallbackPath` and  `SignedOutCallbackPath` (otherwise it doesn't work). Is it fine to set these properties the way we did ? Can we set them to whatever unique value ? Is there any validation rule applied to them (apart from being valid URL path) ?
 - how can we configure the provider so that after logging out from it the user agent is redirected to the home page of our identity provider application ? We have tried to set `options.PostLogoutRedirectUri = "/"`, but it seems to be ignored. After logging out from the external provider we are redirected to a page asking us if we are sure to logging out from identity server. We are not able to be redirected to the home page. 

Thanks for helping

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
