### ISSUE TITLE
.Net Core 3 with Docker

### ISSUE THREAD

**Issue by maganuk** [IdentityServer/IdentityServer4#3607]
I have a few applications which I have ported to asp.net core 3 preview 9. These are all dockerized and running on a kubernetes cluster. All other apps seem fine but for some reason the Identity Server App is running fine locally but fails to start in Kubernetes. Was working fine in 2.2. The logs don't show much, just says that the Application is shutting down...

I'm using IdentityServer.EntityFramework with token cleanup enabled. Hope this has nothing to do with the service. I've tried disabling token cleanup to no avail.

[Update]
I did some more testing and now if I change the docker runtime image from debian (buster - which is default) to ubuntu (disco) it seems to be running fine. Don't know if it is an issue with the images or IDS.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by maganuk** [comment]
Ok. Will give it a shot with the new RC1 images and see if it works with ubuntu.
