### ISSUE TITLE
Access Tokens/Claims from one site/domain to another site/domain in ASP.NET

### ISSUE THREAD

**Issue by raiajithkumarr** [IdentityServer/IdentityServer4#361]
We are implementing the OpenIDConnect for multiple projects/sites and those are hosted at different IIS Servers.
Now we want to cache tokens for reusing authentication it means.
For example we have 3 site/application hosted in 3 different servers when enduser login into the any one of the application he can able to access other 2 applications.

We already spent so much of time on this ,please suggest me answer or provide me piece of code that will help me.

**Comment by brockallen** [comment]
identityserver.io/ is an FOSS project written in .NET for SSO using OIDC

**Comment by brockallen** [comment]
So just have all 3 apps trust the one IdentityServer -- that's how you achieve SSO.

**Comment by raiajithkumarr** [comment]
yes.
But how to implement IdentityServer can share sample with me.
so that it will helpus.

**Comment by leastprivilege** [comment]
Check the docs and the samples repo - especially the sample called "Clients".

To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

**Comment by raiajithkumarr** [comment]
Can any body provide me sample application with identity server,ASP.NET and ASP.NET MVC.
Means ASP.NET/MVC Communicate identity server from that tokens passed to applicaiton(asp.net and asp.net MVC) later anyone can access from respective browser. 
we were strucked.
help on this.
