### ISSUE TITLE
Update QuickStarts to ASP.NET Core 3

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3611]
* [ ] update to 3.0 RTM
* [ ] add/re-work content as needed (@LindaLawton)
* [ ] remove hybrid and replace with code + pkce

**Comment by LindaLawton** [comment]
Do we have a branch with the 3.0 changes in it?

**Comment by daver77** [comment]
Will there any guides on what we need to do to update to 3.0?

**Comment by LindaLawton** [comment]
@daver77 Thats the plan with this issue.   Updating the samples, and tutorials.  I will probably put out something related to how to upgrade as well.

**Comment by brockallen** [comment]
> Do we have a branch with the 3.0 changes in it?

It's now all on master.

**Comment by murbanowicz** [comment]
@brockallen it is but only for clients. I am struggling with setting up the client on 3.0 which will not require the PKCE.
When adding `AddInMemoryClient` it does not use those clients, adding `RequirePkce: false` to `appsettings.json` does not make any difference and it is still throwing error on code challange.
Any help please?
I posted question on SO: https://stackoverflow.com/questions/57857813/identity-server-4-unauthorized-client?noredirect=1#comment102144354_57857813

**Comment by sevenmay** [comment]
> remove hybrid and replace with code + pkce

So with a server side MVC app (and API calls) should we use code+pkce instead of hybrid?
Have you some resource on why this is the better approach?
Thanks!

**Comment by leastprivilege** [comment]
That's our guidance

https://identityserver4.readthedocs.io/en/latest/topics/grant_types.html
