### ISSUE TITLE
Issues passing scope to Identity server in Python

### ISSUE THREAD

**Issue by mmotahar-ia** [IdentityServer/IdentityServer4#3613]
Hello,

    We know that "IdentityServer4 itself must run in an ASP.NET Core v2 application (either on 
    .NET Core or .NET Framework). and the client can run on any platform." 

However, I have difficulties writing a python client application to call oauth 2.0. Is there any samples I can use ? 

I am using this python library and the legacy application workflow. 
https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#legacy-application-flow

Thanks,

`
import requests
import requests_oauthlib
from requests_oauthlib import OAuth2Session

client_id = 'my_id'
client_secret = 'my_secret'

username = "my_username"
password = "Mypassword"

base_url = "https://our_indetity_server.com"
token_url = base_url + "/identity/connect/token"
my_scope = ['openid','IdentityAPI']
oauth = OAuth2Session(client=LegacyApplicationClient(client_id=client_id),scope=my_scope)
token = oauth.fetch_token(token_url=token_url,username=username, password=password, client_id=client_id, client_secret=client_secret)

>>>   oauthlib.oauth2.rfc6749.errors.InvalidScopeError: (invalid_scope)
`

**Comment by brockallen** [comment]
Don't know really. Maybe this: https://github.com/rohe/pyoidc. It's listed from: https://openid.net/developers/certified/
