### ISSUE TITLE
Whether its possible to seperate the flow of identity server 4 based on each clients grant types

### ISSUE THREAD

**Issue by 29parthi** [IdentityServer/IdentityServer4#3618]
Our existing application (its an internal application which allows users of a particular AD)

Web client 1
Web api
Identity server 4 (which usings Ldap to to fetch the current AD user and assign respective roles based on the AD permission level which is set in the DB )

Problem :

Web client 2
Web api
Identity server 4 (authenticate user by using resource owner password grant )

What we are trying to achieve is to extend our web api to an external website , whose login(username and password) are available in our database. So we tried using the resource owner password grant by using resourceownervalidator and profile service. it worked , but its breaking the existing flow(the flow which was setup for web client 1).

**Comment by leastprivilege** [comment]
I think you have access to the client ID in the validator. So you can branch your logic based on that.
