### ISSUE TITLE
Can clients specify which external provider to use?

### ISSUE THREAD

**Issue by aweFalafelApps** [IdentityServer/IdentityServer4#3619]
I know that clients can be configured to only allow certain providers during IS4 startup, but is there a way to allow clients, during an authentication request, to specify which of it's allowed providers to use? Use case: I'd like to show the ui that lists the available providers in a native mobile app instead of using the IS4 ui.

**Comment by leastprivilege** [comment]
Yes - you can set that as a request parameter - use

`acr_values=idp:name_of_idp`

**Comment by aweFalafelApps** [comment]
Thanks, sorry I missed it!
