### ISSUE TITLE
Prevent MVC client (other browser tab) to automatically login with External provider

### ISSUE THREAD

**Issue by 1Jesper1** [IdentityServer/IdentityServer4#3620]
Use case:
1. Multiple tabs of MVC client open and logged in.
2. Logout of MVC client tab 1.
3. Logout  MVC client tab 1 redirects to logout page (custom, prevent to go automatically to external login provider).
4. Cookies are cleared.
5. When clicking in the other MVC client tab 2 on an action. MVC client tab 2 redirects to external login provider page, because "User is not authenticated. Redirecting to login".

How can we accomplish that the MVC client tab 2 does not automatically go to the external login provider page, but also goes to the custom logout page?
We want to prevent logging in automatically in the external login provider.

For the JS clients we check for SignOutUser event and then do an signoutRedirect call.

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!

**Comment by 1Jesper1** [comment]
Posted the question on Stackoverflow: [https://stackoverflow.com/questions/57901729/identityserver-prevent-mvc-client-other-browser-tab-to-automatically-login-w](https://stackoverflow.com/questions/57901729/identityserver-prevent-mvc-client-other-browser-tab-to-automatically-login-w)
