### ISSUE TITLE
Remove "plain" from code_challenge_methods_supported in Discovery

### ISSUE THREAD

**Issue by gthvidsten** [IdentityServer/IdentityServer4#3621]
How can we define which values are displayed for `code_challenge_methods_supported` in the Discovery endpoint?

By default it lists `plain` and `S256`, but I don't want to support plain and want to remove it from the Discovery endpoint, but can't find any options to do this.

**Comment by leastprivilege** [comment]
This might no be easily possible right now without replacing the whole response generator.

**Comment by brockallen** [comment]
Also, isn't it actually a per-client setting to allow plain?

**Comment by gthvidsten** [comment]
Yes, it is a per-client setting, but I don't want to publish that I support plain when I personally won't allow any clients to use it.

**Comment by brockallen** [comment]
You could maybe achieve the same thing by adjusting the discovery document response generator?
