### ISSUE TITLE
Why would you recommend hybrid than authorization_code flow?

### ISSUE THREAD

**Issue by janmchan** [IdentityServer/IdentityServer4#3623]
I've set up our own IDS4 and a lot of examples are using hybrid "code id_token". I also tried Admin UI and for a web app, it specifically uses "hybrid" for the web app and actually disallows to select authorization_code. 

From what I understand the response type determines what is included during redirect. But, id_token is created is still returned in the backend response. So I was wondering why return id_token in the first place on the redirect, especially for MVC web apps which doesn't really access id_token in the front end.

So here are the main concepts I can't seem to clearly understand.
- What is the main use case where you would need id_token in the initial response for MVC Web App? You can't really access the id_token using pure javascript.
- Is there a benefit for doing hybrid for security?

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
