### ISSUE TITLE
Reasoning why only certain grant types go thru ValidateRequestedScopesAsync ? (TokenValidation)

### ISSUE THREAD

**Issue by MarkClouden** [IdentityServer/IdentityServer4#3625]
I not that this (and by it, the ValidatedScopes on the context) is only occurring during clientcredentials, extension, ROP, and one other, but not in auth code validation.

I ask because I currently apply claims based on policies at the resource scope (and other factors such as client) and in a mobile hybrid flow on token endpoint validation the ValidatedScopes is not presented during either ICustomTokenRequestValidator.ValidateAsync (via CustomTokenRequestValidationContext), nor in IProfileService.GetProfileDataAsync (via ProfileDataRequestContext).

I can certainly perform that filtering of client-configured scopes vs those requested myself, but i got to wondering if there was a fine reason why this was not occurring already?

**Comment by leastprivilege** [comment]
Sorry - this fell through the cracks. Still an issue?

**Comment by MarkClouden** [comment]
No worries. 'Still an issue' depends on how you would classify it. My initial question was just that, a question; was there an intentional reason why the ValidatedScopes was not populated in that code path? If there was a good reason for it then it is 'by design', and I have a work-around. If it was not intentional I am more than happy to submit a patch for your review.

**Comment by leastprivilege** [comment]
Don't worry. Re-writing the scope handling is a top priority for vNext. It's indeed a bit messy.

**Comment by leastprivilege** [comment]
Glad you have a workaround.
