### ISSUE TITLE
How to cache token get by "RequestClientCredentialsTokenAsync" and reuse again that token and avoid api call redundantly with example

### ISSUE THREAD

**Issue by RenishDadhaniya06** [IdentityServer/IdentityServer4#3626]
Please Provide Any Example here or link of example

**Comment by damienbod** [comment]
Here's an example:

https://damienbod.com/2019/05/10/handling-access-tokens-for-private-apis-in-asp-net-core/

**Comment by RenishDadhaniya06** [comment]
may I have an example for .net MVC

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
