### ISSUE TITLE
Migration from Identity Server 3 to Identity Server 4

### ISSUE THREAD

**Issue by imolinaDev** [IdentityServer/IdentityServer4#3627]
I am working in a project to migrate Identity Server 3 to Identity Server 4 and I am facing some problems migrating the old Tokens table into the new PersistedGrants table.

The structure of PersistedGrants has changed comparing with the old Tokens table. For instance, **TokenType (smallint)** is now **Type(nvarchar(50))**, **JsonCode** has disappeared and a new column **Data** has been added. 

Any advice?

Thank you very much in advance.

**Comment by leastprivilege** [comment]
@scottbrady91 don't you have some tool for that?

**Comment by scottbrady91** [comment]
We have a console tool for config and tokens: https://github.com/RockSolidKnowledge/IdentityServer.Migration

However, you will need to extend the various token stores to support these older token types.

**Comment by imolinaDev** [comment]
Thank you very much guys. Very useful
