### ISSUE TITLE
.NET Core 2.2 IdentityServer 4 v2.5 IdentityModel v4.0

### ISSUE THREAD

**Issue by sv-xzc5lnp** [IdentityServer/IdentityServer4#3634]
I am getting this error

> Token request validation success, 
> 2019-09-15 16:15:41.952 -04:00 [FTL] Unhandled exception: Method not found: 'System.String IdentityModel.CryptoRandom.CreateUniqueId(Int32)'.

This is with the sample application instructed here
http://docs.identityserver.io/en/latest/quickstarts/1_client_credentials.html

I am using 

> Vs2017 Pro
> <TargetFramework>netcoreapp2.2</TargetFramework>

**Identity Server Project with the below references**
- IdentityModel 4.0
-IdentityServer 2.5.0

**CLient Project**
- IdentityModel 4.0

**Comment by leastprivilege** [comment]
IdentityModel 4 is a breaking change

https://github.com/IdentityModel/IdentityModel/releases/tag/4.0.0

<img width="864" alt="Screenshot 2019-09-16 07 52 09" src="https://user-images.githubusercontent.com/1454075/64936559-e60e6180-d856-11e9-8c8f-32acfb2b500b.png">
