### ISSUE TITLE
QuickStart UI is broken for ASP Core 2.2

### ISSUE THREAD

**Issue by 18549** [IdentityServer/IdentityServer4#3636]
The latest commit to https://github.com/IdentityServer/IdentityServer4.Quickstart.UI which is https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/commit/39a249881be4081520336af5e4d57272a5d6ef8c

breaks the UI for ASP Core 2.2 by replacing IHostingEnvironment with IWebHostEnvironment, but the Readme.md states that this is still the codebase for ASP.NET Core / MVC 2.

### Issue / Steps to reproduce the problem

1. Copy the QuickStart UI into an ASP.NET Core / MVC 2 webservice project.
2. Try to build.

Expected Result

It should build.

Actual Result:

It does not build.
Error "The type or namespace 'IWebHostEnvironment' could not be found"

**Comment by fuzzzerd** [comment]
The latest commit message on that repo states its being prepped for .NET Core v3.

**Comment by leastprivilege** [comment]
master is on 3.0 now. yes. sorry for the confusion.

You can use this list to download older versions
https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/releases

**Comment by 18549** [comment]
Bit premature isn't it? Dotnet Core 3 isn't even live yet is it?
