### ISSUE TITLE
Cannot disable endpoint deviceauthorization

### ISSUE THREAD

**Issue by jaanclaeys** [IdentityServer/IdentityServer4#3638]
I was hardening the identityServer4 and closing some endpoints.
Is there a reason that in EndpointOptionsExtensions.cs that devicecodeauthorization endpoint is not mentioned, I suspect this is a bug.

### Issue / Steps to reproduce the problem
1. In AddIdentityServer disable the deviceauthorizationendpoint at start-up:
```
var builder = services.AddIdentityServer(o =>
{
  // Remove endpoints not in use                
  o.Endpoints.EnableDeviceAuthorizationEndpoint = false;
}
```

2. Check if the endpoint /connect/deviceauthorization gives 404 after disabling the endpoint in the IdentityServerOptions (Personal hardening unit test)

  ```
  // Act
  var response = await client.GetAsync("http://localhost/connect/deviceauthorization");

  // Assert
  Assert.IsFalse(response.IsSuccessStatusCode);
  Assert.IsTrue(response.StatusCode == System.Net.HttpStatusCode.NotFound);
```

However it gives a 400 as a response. Indicating it is still open.

**Comment by brockallen** [comment]
> I suspect this is a bug.

Perhaps more of an omission, than a bug.

**Comment by jaanclaeys** [comment]
True. As a workaround I manually put the handler out of the servicecollection for the moment so my test passes.

**Comment by carl-hartshorn** [comment]
Hi @jaanclaeys @brockallen 👋 

Please find above a PR to resolve this issue!
