### ISSUE TITLE
If we update to IS4 3 when Core 3 releases, will that be backwards compatible with the old IdentityModel/AccessTokenValidation?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#3639]
In [the release notes for v3](https://github.com/IdentityServer/IdentityServer4/releases/tag/3.0.0) you say:

> We removed the old legacy ~/resources audience from access tokens and use a typ header instead. This might cause problems with some legacy JWT validation libraries and needs some testing.

But no where is there any explicit mention of backwards incompatibility, or any text urging people up update the libraries mentioned below.

Does any of the following libraries and their versions rely on the ~/resources audience?

- IdentityServer4 v2.x
- IdentityServer4.AccessTokenValidation v2.x
- IdentityModel.AspNetCore.OAuth2Introspection v3.x
- IdentityModel.OidcClient v2.x

This is kind of a callback to [my other issue](https://github.com/IdentityServer/IdentityServer4/issues/3598). The blog states IM 4 is not compatible with IS4-2 but it never says anything about IS4 3 not being compatible with IM 3.

**Comment by leastprivilege** [comment]
AccessTokenValidation is really the important one. I don't think this will be an issue for the ASP.NET Core version of it.

How about you give it a try and let us know?

**Comment by VictorioBerra** [comment]
@leastprivilege 

I got it to work, It looks like `AccessTokenValidation` 2.7 will indeed work with IS4-3.

**Comment by leastprivilege** [comment]
great!
