### ISSUE TITLE
Calling introspect with Bearer token

### ISSUE THREAD

**Issue by dhjf** [IdentityServer/IdentityServer4#364]
Hi

Is it correct that IdentityServer4 does not support calling the introspect endpoint using a Bearer token?
According to the RFC, this should be possible - please correct me if I am wrong :-)

/Christian

**Comment by leastprivilege** [comment]
not out of the box. What would be the scenario? And what exactly does the spec say?

**Comment by dhjf** [comment]
The scenario is that we currently call the introspect endpoint using a scope/secret, and we might not know or want to know the scope secret at this point. 

From the spec:
 To prevent token scanning attacks, the endpoint MUST also require
 some form of authorization to access this endpoint, such as client
 authentication as described in OAuth 2.0 [RFC6749] or a separate
 OAuth 2.0 access token such as the bearer token described in OAuth
 2.0 Bearer Token Usage [RFC6750]. 

Examples can be found in the spec and here: http://connect2id.com/products/server/docs/api/token-introspection

**Comment by leastprivilege** [comment]
For your API to get a token to call introspection, it would need a client secret. What's the advantage here?

**Comment by dhjf** [comment]
I might be mixing topics now, but currently you do a check to see if the scope used to call the introspect endpoint is part of the input token. Is this a requirement from the spec?

**Comment by leastprivilege** [comment]
yes

**Comment by madsj** [comment]
Hi, sorry for interrupting this thread. But is it possible to point to the part of the spec where 

> but currently you do a check to see if the scope used to call the introspect endpoint is part of the input token. Is this a requirement from the spec?

is described?

**Comment by leastprivilege** [comment]
in 2.2 it says

> The authorization server MAY respond differently to different
   protected resources making the same request.  For instance, an
   authorization server MAY limit which scopes from a given token are
   returned for each protected resource to prevent a protected resource
   from learning more about the larger network than is necessary for its
   operation.

**Comment by brockallen** [comment]
@dhjf all set on this issue -- can we close?

**Comment by dhjf** [comment]
Yeah, you can close it. Thanks.
