### ISSUE TITLE
Multiple redirect uris

### ISSUE THREAD

**Issue by Coldplayer1995** [IdentityServer/IdentityServer4#3640]
Hello, I have the following problem: 
I am implementing IdentityServer4 in a microservice architecture. Currently, we have our landing page with the login button. Trying to log in by IdentityServer4 then retrieving access_token and we want to move into the totally different angular app but at the same time to be already authenticated. The redirect_uri does not really do the job, as the returning url is depended on the user role. The question is if registering every single client in IdentityServer will help us to achieve a multi-application login state.

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
