### ISSUE TITLE
ClaimTypes.NameIdentifier is not mapped to claim of type sub

### ISSUE THREAD

**Issue by mdmoura** [IdentityServer/IdentityServer4#3642]
Using ASP.NET Core 2.2 and Identity Server 4 I have the following API Configuration:

    services
      .AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
      .AddIdentityServerAuthentication(x => {
        x.ApiName = "api";
        x.Authority = Configuration.Get<Settings>().AuthorityUri;
        x.RequireHttpsMetadata = true;
      });

    services.AddAuthorization();

    services
      .AddIdentityCore<User>()
      .AddEntityFrameworkStores<Context>()
      .AddDefaultTokenProviders();

Then on an API Controller I have the following:

```
[HttpGet("posts"), Authorize]
public async Task<IActionResult> GetPosts() {
  var authenticated = this.User.Identity.IsAuthenticated;
  var claims = this.User.Identities.FirstOrDefault().Claims;
  var id = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
}
```

In claims I have one of type 'sub' but 'id' is null ...

It seems `ClaimTypes.NameIdentifier` is not mapped to claim of type `sub`.

**Comment by leastprivilege** [comment]
You need to turn off the global mapping in the JWT handler - something like

`JwtSecurityTokenHandler.DefaultMapInboundClaimTypes = true;`
