### ISSUE TITLE
Global sign-out

### ISSUE THREAD

**Issue by m4szl4g** [IdentityServer/IdentityServer4#3643]
Hi,

We would like to logout all of our clients by using **FrontChannelLogoutUri** property. However, we saw it only works if the applications (with different client ids) are opened in the same browser on different tabs. Is that possible to logout all the clients from different browsers / mobile devices? All of the documents are read but we couldn't figure out whether it is possible.

The same Identity Server (v4.2.3) is used by the clients. For testing we used two different MVC clients with different clientids with the same user. It work well with one browser but if the apps run in different browsers, the **SignOutIframeUrl** property contains only one **FrontChannelLogoutUri** for the given client which triggered the logout process.

Can you confirm whether it is a valid logout workflow?

Regards,
Csaba

**Comment by leastprivilege** [comment]
Front-channel only works for client in the same browser.

For other environments you can use the back-channel signout.

**Comment by m4szl4g** [comment]
Hi Dominick,

We've tried the back-channel signout as you suggested but it doesn't work as we expected. As an experiment we used your Identity Server host (IdentityServer4\src\IdentityServer4\host\) and your backchannel client app from github samples (IdentityServer4\samples\Clients\src\MvcHybridBackChannel).

We duplicated the MvcHybridBackChannel (used with clientId  "mvc.hybrid.backchannel") appplication (MvcHybridBackChannel2 with "mvc.hybrid.backchannel2") and use the same setup with different clientids (and of course with different port settings: 21403 vs 21404 ).

After that we started the Host application and logged in with the 2 mvc client app (MvcHybridBackChannel and MvcHybridBackChannel2) with the same username/password (= bob/bob) with different browser instance. After sign-out with MvcHybridBackChannel app we would expect the MvcHybridBackChannel2 logout uri will be fired/invoked as well but nothing happened.

We can see no error messages and everything seems correct.

What do you think? Should this workflow work? (BackChannel with different ClientIds with different browser instance with the same user.)


Here are the clients setup we used:

var client1 = new Client
{
               ClientId = "mvc.hybrid.backchannel",
               ClientName = "MVC Hybrid (with BackChannel logout)",
               ClientUri = "http://identityserver.io",

               ClientSecrets =
               {
                              new Secret("secret".Sha256())
               },

               AllowedGrantTypes = GrantTypes.Hybrid,
               AllowAccessTokensViaBrowser = false,

               RedirectUris = { "http://localhost:21403/signin-oidc" },
               BackChannelLogoutUri = "http://localhost:21403/logout",
               PostLogoutRedirectUris = { "http://localhost:21403/signout-callback-oidc" },

               AllowOfflineAccess = true,

               AllowedScopes =
               {
                              IdentityServerConstants.StandardScopes.OpenId,
                              IdentityServerConstants.StandardScopes.Profile,
                              IdentityServerConstants.StandardScopes.Email,
                              "api1", "api2.read_only"
               }
},



var client2 = new Client
{
               ClientId = "mvc.hybrid.backchannel2",
               ClientName = "MVC Hybrid (with BackChannel logout)",
               ClientUri = "http://identityserver.io",

               ClientSecrets =
               {
                              new Secret("secret".Sha256())
               },

               AllowedGrantTypes = GrantTypes.Hybrid,
               AllowAccessTokensViaBrowser = false,

               RedirectUris = { "http://localhost:21404/signin-oidc" },
               BackChannelLogoutUri = "http://localhost:21404/logout",
               PostLogoutRedirectUris = { "http://localhost:21404/signout-callback-oidc" },

               AllowOfflineAccess = true,

               AllowedScopes =
               {
                              IdentityServerConstants.StandardScopes.OpenId,
                              IdentityServerConstants.StandardScopes.Profile,
                              IdentityServerConstants.StandardScopes.Email,
                              "api1", "api2.read_only"
               }
},

**Comment by leastprivilege** [comment]
Ah - two completely different browsers. Well - no in this case we have nothing built-in to help you.

You could do your own book keeping of using signing in and out - and send the back-channel calls yourself.

**Comment by m4szl4g** [comment]
Ok, thanks for the quick reply
