### ISSUE TITLE
does serilog have legs

### ISSUE THREAD

**Issue by TomCJones** [IdentityServer/IdentityServer4#3646]
I still see this in the code
We personally like `Serilog <https://serilog.net/>`_ a lot. Give it a **try.**
Is this likely to continue for the foreseeable future, or is there any other direction planned?

**Comment by leastprivilege** [comment]
I don't follow. What's the question?

**Comment by VictorioBerra** [comment]
It sounds like hes asking if you plan to leave Serilog and use something else? Not sure.

**Comment by brockallen** [comment]
Serilog is quite solid and is being used in many production apps.

**Comment by TomCJones** [comment]
thank you for that answer
