### ISSUE TITLE
asp.net core 3.0 not support identityserver4 with mvc client http mode

### ISSUE THREAD

**Issue by zdp120** [IdentityServer/IdentityServer4#3649]
When I use Indentityserver4 mvc app with asp.net core 2.2 http method, it can be work. But I update asp.net core 3.0, mvc app with http method, it cann't work. Why? The mvc app client must support https. This is a bug or not.

**Comment by leastprivilege** [comment]
I do not think this is the case. Check our repo - our host runs on netcore3 and http only.

**Comment by zdp120** [comment]
Can you tell me how to modify the source code? I don't know which part to change, thank you.

**Comment by taadis** [comment]
i only use `IdentityServerTools`, So just `services.AddIdentityServer().AddSigningCredential(xxx)`, this work in .NET Core 2.x App, can't work in .NET Core 3.x App.

![图片](https://user-images.githubusercontent.com/16029681/65483191-e7cacb80-decd-11e9-83e5-5b1bf5131cf4.png)

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
