### ISSUE TITLE
When upgrading from 1.5.x to 2.5.x public framework URLs change and cause problems if users bookmark the login page

### ISSUE THREAD

**Issue by mackie1001** [IdentityServer/IdentityServer4#3651]
Users do strange things and something we see a LOT is them bookmarking the login page in our identity server. We've worked around this in client apps (as state and nonce etc will be invalid) but it also means that their bookmark will contain `/connect/authorize/login` or `/connect/authorize/consent` in the returnUrl.

These 2 URLs have now been combined into `/connect/authorize/callback` but there's no backwards compatibility so anyone using a bookmark like this will receive a 404.

I have worked around it using the ASP.Net rewrite middleware but I figured it might be nice to maintain backwards compatibility for people upgrading from an earlier version of the framework.

Otherwise the upgrade was relatively painless :)

**Comment by leastprivilege** [comment]
I can see the issue - but we didn't plan for that.

**Comment by mackie1001** [comment]
FYI this is the workaround we ended up with. We didn't clock the issue until it hit production either.

    var options = new RewriteOptions();
    options.AddRewrite(@"^connect/authorize/login(.*)$", "connect/authorize/callback$1", true);
    options.AddRewrite(@"^connect/authorize/consent(.*)$", "connect/authorize/callback$1", true);
    app.UseRewriter(options);

**Comment by brockallen** [comment]
Glad you have a workaround. We're not planning on doing anything more around this.
