### ISSUE TITLE
Is it possible to explicitly set KeyId for signing material?

### ISSUE THREAD

**Issue by voroninp** [IdentityServer/IdentityServer4#3653]
### Question
We are migrating from IS3 and we have a strict requirement to avoid user logout because of that.

I managed to override the method which generates token hash to restore IS3 hashing behaviour. This is fine.

But KeyId is set differently for IS3 and IS4, and our services use old `kid` value for local signature validation, so they cannot match the key and reject the tokens.

Hence we need to set KeyId explicitly, is it possible?

**Comment by leastprivilege** [comment]
You could derive from our `DiscoveryResponseGenerator` and overwrite the method that creates the key set. Then fix-up the key id.
