### ISSUE TITLE
Enable reuse of TokenCleanupHost by injecting a custom TokenCleanupService

### ISSUE THREAD

**Issue by springcomp** [IdentityServer/IdentityServer4#3655]
When implementing a custom operational store, it would be great to be able to reuse the token cleanup logic embedded in the `TokenCleanupHost` hosted service and the `TokenCleanupService` public interface.

By making `TokenCleanupService` an interface implementation, one would be able to inject their own custom implemation.

**Comment by leastprivilege** [comment]
I think @brockallen did something like this for the 3.0 release...
