### ISSUE TITLE
integrate DotNetNuke_9_3_2_24 with Identity Server 4.0

### ISSUE THREAD

**Issue by lucky85008** [IdentityServer/IdentityServer4#3656]
Hi

We are trying to integrate DotNetNuke_9_3_2_24 with Identity Server 4.0 , http://docs.identityserver.io/en/latest/#

How to set up integrate DotNetNuke_9_3_2_24 with Identity Server 4.0 ?

What configuration is needed?

DNN has default extensions for Facebook, Google, Twiter, Windows Live.

Please advice
Thanks.

Lucky

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!

**Comment by lucky85008** [comment]
Actually I am requesting a feature to Create DNN extension for Identity Server 4.0. So many people are looking this integration 

Similar to DNN Extension for FACEBook, Google, Twitter.
There can be IDS 4 extension for DNN
like Windows Live
https://github.com/dnnsoftware/Dnn.Platform/tree/release/9.3.2/DNN%20Platform/Providers/AuthenticationProviders

Yes, we already have commercial Support for Identity Server 4 (With Andy) But so far we trying to make it work.
Thanks.
