### ISSUE TITLE
Hashtag in login url gets urlencoded

### ISSUE THREAD

**Issue by mortenn** [IdentityServer/IdentityServer4#3658]
### Issue / Steps to reproduce the problem

- Set login url to /index.html#!/login
- Navigate to a page that sends you to the login page
- See url get broken by # becoming %23

**Comment by brockallen** [comment]
Not sure we can/want support that, as we need to add query string params to the path.

**Comment by brockallen** [comment]
@leastprivilege any input if we should support SPA style login page URLs? Also, @mortenn, do those work on the normal CookieOptions' LoingPath when you call Challenge?

**Comment by leastprivilege** [comment]
IMHO - for "normal" redirects to a login page we want to rely in Challenge only in the future - support for other scenarios like e.g. (external) SPAs needs design. So 4.x rather.

**Comment by brockallen** [comment]
So mark this as a 4.0 to consider/discuss?

**Comment by dbpieter** [comment]
Any updates on this ?

**Comment by brockallen** [comment]
This has a milestone for 4.0.

**Comment by brockallen** [comment]
We'd like to allow the login UI to formally live "elsewhere", but it needs to be designed as a proper feature and not just work "by accident" (as Dom says).

**Comment by mortenn** [comment]
Regarding your question adressed at me, @brockallen, I am not at all sure what you mean regarding Challenge. My only task in our project was to set up the login spa, and that is used by external and internal applications that support openid connect/oauth2

I have worked around the issue by having a simple jump page that redirects the client for now.
