### ISSUE TITLE
Id is assigned as subjectId; want to change value of SubjectId to Something else

### ISSUE THREAD

**Issue by carlospence** [IdentityServer/IdentityServer4#3659]
I implemented a CustomUserStore with Id as key field, I also have another field called userguid.

The Id is automatically assigned as the SubjectId and I want to change it to the userguid.

I used a custom resource owner password validator to change SubjectId to the value I wanted but this is works if the granttype is "password". I noticed that this custom resource owner password validator is not called for other granttypes.

if I use "implicit" GrantType the IdentityServer4.Validation.DefaultCustomAuthorizeRequestValidator is called, thus using the default SubjectId. I want the SubjectId to be the UserGuid instead of the UserId but it is using the UserId by default.

**Comment by brockallen** [comment]
Change your code in the login page to use your other value for the subject id.

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/host/Quickstart/Account/AccountController.cs#L130
