### ISSUE TITLE
Custom URL Schemes iOS

### ISSUE THREAD

**Issue by adozenlines** [IdentityServer/IdentityServer4#3660]
Mobile Applications that perform OAuth have the ability to register custom URL schemes. When such a scheme is specified in the call back URL of the request, the identity server doesn't redirect to the custom scheme and as a result, the mobile application never receives the access token.

**Comment by leastprivilege** [comment]
Works for me. Do you have more details?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
