### ISSUE TITLE
System.TypeLoadException: Method 'get_Info' 

### ISSUE THREAD

**Issue by linfx** [IdentityServer/IdentityServer4#3662]
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](http://docs.identityserver.io/en/latest/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

update ef 3.0 than have a bug,,  bug ef 2.2 is fine

  <ItemGroup>
    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="3.0.1" />
    <PackageReference Include="IdentityServer4.EntityFramework" Version="3.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.2.7" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
  </ItemGroup>

### Relevant parts of the log file

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.TypeLoadException: Method 'get_Info' in type 'Pomelo.EntityFrameworkCore.MySql.Infrastructure.Internal.MySqlOptionsExtension' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by leastprivilege** [comment]
> Pomelo.EntityFrameworkCore.MySql, Version=2.2.0.0

Looks like you need to update this to 3.0

**Comment by zhanghaiboshiwo** [comment]
The problem is you don't will drive Pomelo. EntityFrameworkCore. MySql update to version 3.0
