### ISSUE TITLE
MissingMethodException: Method not found: 'System.String IdentityModel.CryptoRandom.CreateUniqueId(Int32)'.

### ISSUE THREAD

**Issue by UltaChain** [IdentityServer/IdentityServer4#3663]
When I try to create access_token using this code
`var tokenResponse = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest
            {
                Address = disco.TokenEndpoint,
                ClientId = "angularClient",
                ClientSecret = "angular",
                Scope = "userapi"
            });`
I got Internal Server Error for tokenResponse.
And It says Method not found: 'System.String IdentityModel.CryptoRandom.CreateUniqueId(Int32)'.
I checked this function if it exists or not and verified that it exists.
Please help.

**Comment by UltaChain** [comment]
Any help please?

**Comment by leastprivilege** [comment]
Sounds like you updated IdentityModel to v4 on the server. Don't.
