### ISSUE TITLE
Will demo.identityserver.io be updated to 3.x?

### ISSUE THREAD

**Issue by VictorioBerra** [IdentityServer/IdentityServer4#3664]
Or perhaps we can have a demo3.identityserver.io?

**Comment by leastprivilege** [comment]
Why?

**Comment by leastprivilege** [comment]
...and yes it will - once App Services has v3 support.

**Comment by VictorioBerra** [comment]
Its very handy to prototype against. Especially when verifying compatibility with client libs and IS4.
