### ISSUE TITLE
No .Net Standard package available

### ISSUE THREAD

**Issue by joshmouch** [IdentityServer/IdentityServer4#3665]
I'm trying to upgrade to the latest IdentityServer4, and I found that there are no .Net Standard packages anymore (only .Net Core 3.0).

This creates problems when creating custom classes based on IdentityServer4 classes.  For example, overriding ISecretValidator or IClientConfigurationValidator.

I'm now forced to make my library a .Net Core 3.0 library instead of a .Net Standard library.  And this trickles its way all the way up the solution.  ... since this library is now .Net Core, anything referencing it needs to be .Net Core.

Can you create a Abstraction package that pulls all of the interfaces and non-MVC default implementations into a .Net Standard package?

**Comment by leastprivilege** [comment]
We can have a look. But I think we tried that before - and it is not so trivial.

**Comment by mgernand** [comment]
@leastprivilege 
I need to port my application to .NET Core 3 and am having the same issue. I could take a look into that.

**Comment by leastprivilege** [comment]
You can have a look - but we don't have any immediate plans to rip apart our code - we tried it before, and the result was our Storage package - which is netstandard2.0.

Anything else is very closely related to IdentityServer which is an extension to ASP.NET Core 3 - which is not netstandard anymore.

I guess it takes some time getting used to it, but netstandard is not very useful anymore in this world ;)

**Comment by brockallen** [comment]
Don't see to have any more thoughts? Closing. If you still have issues, feel free to reopen.
