### ISSUE TITLE
IntrospectionBackChannelHandler and InstrospectionDiscoveryHandler

### ISSUE THREAD

**Issue by joshmouch** [IdentityServer/IdentityServer4#3666]
After upgrading to latest IdentityServer4, the following properties are missing:

```
var options = new IdentityServerAuthenticationOptions();
options.IntrospectionBackChannelHandler = identityServerHttpMessageHandler;
options.IntrospectionDiscoveryHandler = identityServerHttpMessageHandler;
```

Were these moved, or are they no longer available?  I use them for unit testing.

**Comment by leastprivilege** [comment]
Yes they are gone. Check this repo how to use it - including tests.

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection

**Comment by ramanathants** [comment]
I am having the similar issue.  I was using IntrospectionBackChannelHandler & InstrospectionDiscoveryHandler  in the similar way Josh mentioned for my integration tests.  The above link doesn't provide me a clear example on how to use it in a new way?  Would you be able to provide an concrete example on how to fix this?  Thanks

**Comment by joshmouch** [comment]
@ramanathants I had to dig through the code a bit, but the new way to do it is to inject an HttpClient into your DI container with a name like so:

```
						// Specify the HTTP client to use when IdentityModel is performing authentication.
						services.AddHttpClient(OAuth2IntrospectionDefaults.BackChannelHttpClientName)
							.AddHttpMessageHandler(() => TestMessageHandler);

```

**Comment by leastprivilege** [comment]
Yes - that's right.

**Comment by ramanathants** [comment]
Thank you @joshmouch !
