### ISSUE TITLE
infinite loop after consent

### ISSUE THREAD

**Issue by mobius127** [IdentityServer/IdentityServer4#3669]
Hi there,
I'm starting to learn Identity server and I have a problem with this.

I'm trying to secure MVC app with identity server, my repo is this https://github.com/mobius127/IdentityServerTests

After consent page, mvc applications takes a redirect loop

Solution is in .net core 3.0 with the latest version of Identity Server

Thanks in advance

**Comment by leastprivilege** [comment]
Try to repro with our host and client samples, please.

**Comment by mobius127** [comment]
Hi there,

I've downloaded your entire repo of Identity server.
I tried this example IdentityServer4\samples\Quickstarts\3_ImplicitFlowAuthentication
It happens the same problem, I didn't update any dependency.
If you look my repo, it is in .netcore3.0

IdentityServer.csproj

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="IdentityServer4" Version="2.3.0" />

    <PackageReference Include="Serilog" Version="2.7.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.0.0" />
  </ItemGroup>
</Project>

MvcClient.csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
</Project>

Thanks for your time

**Comment by mobius127** [comment]
Hi again,
I have deleted the cookies and now your example not shows consent page.

:/

**Comment by leastprivilege** [comment]
With samples I mean any of the clients in this folder

https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Clients

Can you repro this behavior with one of the MVC clients in there?

**Comment by vladimir-efimenko** [comment]
I experience the very same problem after update from 3.0.0-preview7.19365.7

**Comment by mobius127** [comment]
Hi there

I tried your examples and not compiling in vs2019:

Error occurred while restoring NuGet packages: The local source 'C:\_PROYECTOS\DotNetCore\IdentityServer4\nuget' doesn't exist.
This is the error.

Can you please check my repo and tell me what is wrong?

Thanks

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
