### ISSUE TITLE
How to connect Local DB with already existing users to IS4 

### ISSUE THREAD

**Issue by shankar369** [IdentityServer/IdentityServer4#3670]
- I have users table with some users in local DB (id, firstname, lastname, password, email as fields)
- Using entity framework (database first approach) how can we add the already existing users to IS4  for token generation without using asp.net identity ?
-Thanks in advance :)

**Comment by mahitosh** [comment]
Hi Shankar,
May be this will help
https://mcguirev10.com/2018/01/02/identityserver4-without-entity-framework.html

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
