### ISSUE TITLE
SSO between Windows Application and Angular App

### ISSUE THREAD

**Issue by mahitosh** [IdentityServer/IdentityServer4#3671]
Hi,
First I would like to thanks the team to create such a good framework for SSO.
I am using this framework for first time.
I have a scenario where I will be hosting an Angular application in ViewBrowser control of windows application.
So ideally user will first launch the windows application and authenticate using the SSO server. I got this working by using the sample from [here](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/WinFormsWebView)

Now, after successful authentication a page will open up which will host an Angular page inside the windows form.
I am not able to do the handshake between Windows Application and Angular application.
Please help.
Thanks,

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
