### ISSUE TITLE
Create DNN extension for Identity Server 4.0

### ISSUE THREAD

**Issue by lucky85008** [IdentityServer/IdentityServer4#3673]
Hi 
I am requesting a feature to Create DNN extension for Identity Server 4.0. So many people are looking this integration.
Similar to DNN Extension for FACEBook, Google, Twitter.
There can be IDS 4 extension for DNN
like Windows Live
https://github.com/dnnsoftware/Dnn.Platform/tree/release/9.3.2/DNN%20Platform/Providers/AuthenticationProviders
Microsoft announced their support with Identity Server 4.0 , We need to more tools to consume Identity Server 4.0 from different CMS, especially from CMS which are based on Microsoft platform.
Thanks.

**Comment by leastprivilege** [comment]
IdentityServer uses standard protocols. Let the DNN people know that they need to support industry standards - in our case OpenID Connect.

**Comment by lucky85008** [comment]
DNN already supporting OpenID Connect, New version of DNN work with Facebook, Google , LiveConnect , Twitter. Here is code https://github.com/dnnsoftware/Dnn.Platform/tree/release/9.3.2/DNN%20Platform/Providers/AuthenticationProviders 

I am requesting a feature to Create DNN extension for Identity Server 4.0

**Comment by brockallen** [comment]
If DNN already supports OIDC, then why do you need an IdentityServer specific extension?

**Comment by lucky85008** [comment]
DNN is black box. Communication can be done by a connector/ extension. Like it was done for Windows Live
Like this :
TokenMethod = HttpMethod.POST;
TokenEndpoint = new Uri("**https://login.live.com/oauth20_token.srf**");
AuthorizationEndpoint = new Uri("**https://login.live.com/oauth20_authorize.srf**");
Here is Code:
https://github.com/dnnsoftware/Dnn.Platform/blob/release/9.3.2/DNN%20Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect/Components/LiveClient.cs 

Main URL :
https://github.com/dnnsoftware/Dnn.Platform/tree/release/9.3.2/DNN%20Platform/Providers/AuthenticationProviders/DotNetNuke.Authentication.LiveConnect

Facebook, Google, Twitter, Windows Live have “a” Public url to call. 
Identity Server does not have “a” generic/Public url to call. All the Identity server implementations are private.

Yes, DNN already supports OIDC and to communicate with DNN , Identity Server connector/extension need be created.
https://www.dnnsoftware.com/docs/developers/creating-modules/index.html

**Comment by leastprivilege** [comment]
OK. Cool.
