### ISSUE TITLE
AddValidationKeys missing

### ISSUE THREAD

**Issue by AerisG222** [IdentityServer/IdentityServer4#3676]
Hello,

It looks like this method might be missing in the latest release (3.0.1).  This is within the following file for v2.5.3:
IdentityServer4/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs

Is this intentional?

Thanks

**Comment by leastprivilege** [comment]
Yep - I think I removed it when we added support for multiple signing algorithms.

You can call AddValidationKey multiple times instead I think.

**Comment by AerisG222** [comment]
Thank you for the quick response, and this great project!
