### ISSUE TITLE
Using User claim to redirect to different URL than RedirectURL

### ISSUE THREAD

**Issue by scriptmonkey69** [IdentityServer/IdentityServer4#3678]
I have successfully implemented IdentityServer as my Identity Source for my SAAS multitenant application. 

But I would like to redirect to the tenant url I have added as a claim to the user identity, so that the user cannot login in against another tenant application.

**Comment by leastprivilege** [comment]
That's not how it works. Your client app needs to check the claim and make sure the user is in the right place.

**Comment by scriptmonkey69** [comment]
Cool, i will do that change.
