### ISSUE TITLE
Documentation adjustment needed for dotnet core 3

### ISSUE THREAD

**Issue by kdgdev** [IdentityServer/IdentityServer4#3679]
docs/quickstarts/1_client_credentials.rst

The first example is currently not executable in dotnet core 3.0. The problem lies in the configuration part where the .AddJsonFormatters(); and .AddJwtBearer() is used. These functions are no longer available in Microsoft.AspNetCore.Authentication

Related stackoverflow from a few months ago. 
https://stackoverflow.com/questions/56365319/how-to-add-json-formatters-to-mvccore

### Issue / Steps to reproduce the problem
Follow the coding instructions. 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.jwtbearer?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-3.0

https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.mvcjsonmvccorebuilderextensions.addjsonformatters?view=aspnetcore-2.2&viewFallbackFrom=aspnetcore-3.0
![2019-09-26 16_15_44-Quickstart - Microsoft Visual Studio](https://user-images.githubusercontent.com/3345270/65696135-0620fa80-e079-11e9-9e74-31cc528c9c96.png)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
Yes. The docs will be updated soon.

**Comment by shyamal890** [comment]
How to solve this though?
