### ISSUE TITLE
The naming of AddInMemoryStores

### ISSUE THREAD

**Issue by Lutando** [IdentityServer/IdentityServer4#368]
I feel like the naming of `AddInMemoryStores` is kind of misleading or confusing. To me at first glance it sounds like an extension method that adds all the InMemory implementations of the store interfaces into the services collection. Where in fact it is only adding the InMemory implementation of the `IPersistedGrantStore`.

Would it not make more sense to just call this extension method `AddInMemoryPersistedGrantStore` ?

**Comment by brockallen** [comment]
That name came from a time when we had 4 in-memory stores. We've recently consolidated them into the one, so you have a good point.

**Comment by leastprivilege** [comment]
We gonna remove this method altogether.

**Comment by leastprivilege** [comment]
done
