### ISSUE TITLE
Suggestion to target .NET Standard 2.1

### ISSUE THREAD

**Issue by snickler** [IdentityServer/IdentityServer4#3680]
In the 2.x versions of IdentityServer4 and the corresponding libraries, .NET Standard 2.0 was a target. This allowed for me to include pieces of the library in .NET Standard 2.0 projects instead of making them all target .NET Core 2.x. 

Now with 3.x, the libraries are solely targeting .NET Core 3, which would mean that I have to completely retarget my class libraries to .NET Core 3. Is this something that's willing to be considered or will this be the guideline moving forward?

**Comment by leastprivilege** [comment]
We are dependent on ASP.NET Core 3 - which is a netcoreapp3.0 framework. That's why we need to target this as well.

**Comment by snickler** [comment]
Understood, I was  wondering if .netstandard 2.1 could be added as an extra target for the particular libraries that solely targeted .netstandard 2.0 in the 2.x versions. For instance, IdenttiyServer4.AccessTokenValidation works fine for the class library I'm using it in, since it still targets .netstandard.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by leastprivilege** [comment]
We already target the lowest possible. Everything would mean major refactoring and probably breaking changes.

**Comment by snickler** [comment]
Ah, gotcha. Thanks for the clarification!
