### ISSUE TITLE
SourceLink

### ISSUE THREAD

**Issue by joshmouch** [IdentityServer/IdentityServer4#3681]
Is there anything special that needs to be done to get SourceLink debugging working with IdentityServer4?  Every other nuget package I have is working except for this one.

**Comment by leastprivilege** [comment]
I've seen this working on other people's computers - nothing special IIRC.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by fangqifan** [comment]
I had the same problem.
