### ISSUE TITLE
Name claim value is UserName instead of Full Name

### ISSUE THREAD

**Issue by ruben0909** [IdentityServer/IdentityServer4#3682]
Hi,

### Issue / Steps to reproduce the problem
This line set UserName as "name" Claim
https://github.com/IdentityServer/IdentityServer4/blob/015e79d80a99f2b78239c92bf4236c6f7a6b5098/src/AspNetIdentity/src/UserClaimsFactory.cs#L47
But in OpenID Spec
https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

name is 

> End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences.

¿Is it right?

Thank you

**Comment by ruben0909** [comment]
In https://github.com/IdentityServer/IdentityServer4/blob/015e79d80a99f2b78239c92bf4236c6f7a6b5098/src/AspNetIdentity/src/IdentityServerBuilderExtensions.cs#L38
would be ?
opts.ClaimsIdentity.UserNameClaimType = JwtClaimTypes.PreferredUserName

**Comment by leastprivilege** [comment]
Our sample UI treats the username as the display name. Feel free to handle that in any way you want in your own implementation.

**Comment by brockallen** [comment]
Once the user is logged in, why do you care about the username? The user's name is what should be displayed to them. Those are two different claim types (and semantics).

**Comment by ruben0909** [comment]
Hi,

Thank you for your quick reply,
I don`t care about username, maybe I don' need the user's name neither. Could be enough with "sub" claim.
The trouble is here
https://github.com/IdentityServer/IdentityServer4/blob/015e79d80a99f2b78239c92bf4236c6f7a6b5098/src/AspNetIdentity/src/UserClaimsFactory.cs#L47

The code is assigning UserName -> To -> User's name claim.

I think this line could be removed, because now you get username when you want user's name.

MORE INFO
The same value is assigned here too.
https://github.com/IdentityServer/IdentityServer4/blob/015e79d80a99f2b78239c92bf4236c6f7a6b5098/src/AspNetIdentity/src/UserClaimsFactory.cs#L42


But maybe I wrong, @brockallen you are the expert :smiley: 
In that case close the issue, 
Thank you

**Comment by leastprivilege** [comment]
Ultimately you can implement it the way YOU want. I wouldn't read to much into the fact we chose this approach.
