### ISSUE TITLE
redirection after login to client application -vue.js with implicit mode.

### ISSUE THREAD

**Issue by santosh2812** [IdentityServer/IdentityServer4#3685]
https://stackoverflow.com/questions/58153118/redirection-not-happening-from-identityserver4-after-login-to-client-vuejs-appli

please have a look , had added all the reuview

**Comment by santosh2812** [comment]
Hi the problem is the application stuck on below point 
redirecting to /connect/authorize/callback?client_id=Vuejs&redirect_uri=http%3A%2F%2Flocalhost%3A8484%2Flogin&response_type=id_token%20token&scope=openid%20profile%20courses%20roles%20country%20GPSSchoolAPI&state=5b7f679b185642db87a745f649dab48f&nonce=9f222f460a974434a6d0a7179d79765a.
and in
1. Chrome it gives the message - big header 
2. In IE it stuck and on console of Identity Server4 it say that kesteral server header issue for this Have increased the header size in program.cs 
3. in Mozila it stuck -no message is displayed. 
I am not sure what is the issue, have cleared the browser cookies, and also change the port number. 
please suggest.

**Comment by leastprivilege** [comment]
The only place I typically see this error message is when cookies become too big.

This is something you could investigate.

**Comment by santosh2812** [comment]
Hi Sir, for that I have cleared the cookies and also changed the port number so that if any previous cookies is left will not be in any use. 
please suggest.

**Comment by leastprivilege** [comment]
Sorry - don't know.

**Comment by santosh2812** [comment]
HI @brockallen, Can you p[lease help on this. please.

**Comment by farhadbheekoo** [comment]
Hi Santaosh

Your actual cookie size should be no more than 4KB in size. If it is larger than 4KB you will get this issue. If your client app is an MVC one, the cookie authentication middleware has an extensibility point where you can say where you want to store cookie data. So all that will be saved and stored in your cookie is a reference to that data thereby decreasing the size of your cookie.

Hope this helps or at least gives you some insight.

Regards
Farhad

**Comment by santosh2812** [comment]
Hi Farhad,
just I have seen that It is creating lots of cookies, but unable to understand from where it is being created, for reference below is the image.
![image](https://user-images.githubusercontent.com/28972208/66709756-4d510000-ed88-11e9-9a7b-f94d8bd50666.png)

**Comment by farhadbheekoo** [comment]
Hi Santosh

Yes, this is internal to ASP.Core authentication doing it. If your cookie data/info is more than 4KB it will create chunks of cookies to hold the data hence the reason you have 'CXXXX' at the end of every cookie. The reason why one would have so many cookie chunks would be because of the amount of data e.g. many claims, you are putting into it.
A suggestion would be reducing the amount of data you adding to the cookie if possible? Maybe look into the concept I mentioned above if storing references in the cookie to data stored somewhere else.

Hope this helps!

Regards
Farhad

**Comment by santosh2812** [comment]
Thanks, Actually it was cookies issue. I have removed some Claims and now its running fine.
