### ISSUE TITLE
Wrong namespace in ExternalController

### ISSUE THREAD

**Issue by boskjoett** [IdentityServer/IdentityServer4#3686]
### Issue / Steps to reproduce the problem

The sample file 

> IdentityServer4/samples/Quickstarts/5_HybridFlowAuthenticationWithApiAccess/src/IdentityServer/Quickstart/Account/ExternalController.cs

has a wrong namespace.
It is currently **Host.Quickstart.Account** but should be I**dentityServer**.

Using the namespace name **Host.Quickstart.Account** causes problems when converting the project to ASP.NET Core 3.0.

Please fix the namespace name.

**Comment by leastprivilege** [comment]
We will update the docs/quickstarts soon.
