### ISSUE TITLE
Add custom Razor Pages in IdentityServer4

### ISSUE THREAD

**Issue by salem84** [IdentityServer/IdentityServer4#3687]
Hi, 
I read about _AddLocalApi_ methods in order to extend IdentityServer and add custom endpoints.
Do you think a similar feature for adding custom authenticated pages (such as Razor Pages or MVC controllers/view) will be supported?

Thanks

**Comment by brockallen** [comment]
there's nothing special for that -- you'd protect them with the main cookie you're using on your login page

**Comment by salem84** [comment]
thank you Brock, do you think it works also with External Authentication? 
I have configured IdSrv only with Windows Authentication, handled as External Auth as in samples.
Do you think there is a way to obtain a ClaimsPrincipal with all claims (and not only WindowsPrincipal) in order to configure a policy ?

**Comment by leastprivilege** [comment]
Whatever claims you issue at SignIn time can be used by authZ policy.

IdentityServer does not change that in any way - it's pure ASP.NET Core behavior.

**Comment by salem84** [comment]
Yes, I agree with you that IdentityServer doesn't change claims, but I haven't claims issued in a custom ProfileService; is there any way to obtain that (e.g. calling ProfileService or so on)?
