### ISSUE TITLE
Windows Authentication misbehaving

### ISSUE THREAD

**Issue by alexkolt** [IdentityServer/IdentityServer4#369]
I had issues with integrated authentication on local environment and saw issue logged as problem with Kestrel. Thus I build the project (no changes from the repo) and deployed to IIS. Enabled Anonymous and Windows authentications.  Symptom of the issue:
1. Go to the website: url:portName.
2. Change url to url:portName/account/login.
3. Choose Windows as authentication mechanism.
4. Expect to be redirected to home page. But screen is stuck at url:portName/account/External?provider=Negotiate.
5. Navigate to url:portName. Observe the user is logged in.

Secondary issue:
1. Attempt to Logout.
2. Get a prompt to confirm logout operation. Accept.
3. Get redirected to url:portName/Account/Logout to confirm success.
4. Navigate to url:portName.
5. Expected that user is no longer logged in. Actual result the user is still logged in.

**Comment by leastprivilege** [comment]
tracked here #570
