### ISSUE TITLE
netcoreapp3.0 based templates and/or quickstart samples

### ISSUE THREAD

**Issue by garyevari** [IdentityServer/IdentityServer4#3691]
I noticed that none of the templates and/or quickstart samples have been upgraded to run against netcoreapp3.0 and was wondering if that was simply a matter of time constraints or if there was an actual issue that was preventing this, and therefore should be of concern to me for upgrading my implementation from 2.1 -> 3.0?

Thank you, keep up the awesome work.

--edit--

I can see now that https://github.com/IdentityServer/IdentityServer4.Templates has had some templates updated, but just not published to nuget yet - all good

**Comment by leastprivilege** [comment]
working on it.
