### ISSUE TITLE
AuthorizationCode validation failure on ASP .NET Core 3.0 

### ISSUE THREAD

**Issue by pkali18** [IdentityServer/IdentityServer4#3694]
I have been using the React template included with .NET Core 3.0 preview 7, including the default Identity Server setup for individual accounts.
As of upgrading to the current release version of .NET Core, we have encountered this issue regarding the PersistentGrants store. Up untill now, I did not use database storage for the grants.

This is the configuration that I tried using now : 
 
services.AddIdentityServer()
                .AddOperationalStore(options =>
                {
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 600;
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
                }
               )
               .AddApiAuthorization<ApplicationUser, ApplicationDbContext>()              
               .AddProfileService<SisypheanProfileService>();

Nothing has ever been stored in the PersistedGrants table, so I am assuming that it was all done in-memory.

This is the log I'm getting :

 IdentityServer4.Events.DefaultEventService[0]
      {
        "Name": "Client Authentication Success",
        "Category": "Authentication",
        "EventType": "Success",
        "Id": 1010,
        "ClientId": "Sisyphean",
        "AuthenticationMethod": "NoSecret",
        "ActivityId": "0HLQ75HB85RB2:0000009B",
        "TimeStamp": "2019-10-02T11:34:01Z",
        "ProcessId": 12260,
        "LocalIpAddress": "::1:5001",
        "RemoteIpAddress": "::1"
      }
dbug: IdentityServer4.Validation.TokenRequestValidator[0]
      Start token request validation
dbug: IdentityServer4.Validation.TokenRequestValidator[0]
      Start validation of authorization code token request
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__key_0='?' (Size = 200)], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [p].[Key], [p].[ClientId], [p].[CreationTime], [p].[Data], [p].[Expiration], [p].[SubjectId], [p].[Type]
      FROM [PersistedGrants] AS [p]
      WHERE ([p].[Key] = @__key_0) AND @__key_0 IS NOT NULL
dbug: IdentityServer4.EntityFramework.Stores.PersistedGrantStore[0]
      OYhxLqU3lWEfZA8KB0ey7lbsmzaNE/MHiGd88344okc= found in database: False
dbug: IdentityServer4.Stores.DefaultAuthorizationCodeStore[0]
      authorization_code grant with value: J_zYh5HcZTh1mjx7sCa7LT8K-2dmjm-wWA8XWqb1f54 not found in store.
fail: IdentityServer4.Validation.TokenRequestValidator[0]
      Invalid authorization code{ code = J_zYh5HcZTh1mjx7sCa7LT8K-2dmjm-wWA8XWqb1f54 }, details: {
        "ClientId": "Sisyphean",
        "ClientName": "Sisyphean",
        "GrantType": "authorization_code",
        "AuthorizationCode": "J_zYh5HcZTh1mjx7sCa7LT8K-2dmjm-wWA8XWqb1f54",
        "Raw": {
          "client_id": "Sisyphean",
          "code": "J_zYh5HcZTh1mjx7sCa7LT8K-2dmjm-wWA8XWqb1f54",
          "redirect_uri": "https://localhost:5001/authentication/login-callback",
          "code_verifier": "c61f3e4fe2b043658293fdfae017191bb028c0998f0e4da79bce6ab5edc554badbc42de12f9b4260bdcbf9e885dbea0b",
          "grant_type": "authorization_code"
        }
      }
info: IdentityServer4.Events.DefaultEventService[0]
      {
        "Name": "Token Issued Failure",
        "Category": "Token",
        "EventType": "Failure",
        "Id": 2001,
        "ClientId": "Sisyphean",
        "ClientName": "Sisyphean",
        "Endpoint": "Token",
        "GrantType": "authorization_code",
        "Error": "invalid_grant",
        "ActivityId": "0HLQ75HB85RB2:0000009B",
        "TimeStamp": "2019-10-02T11:34:01Z",
        "ProcessId": 12260,
        "LocalIpAddress": "::1:5001",
        "RemoteIpAddress": "::1"
      }

**Comment by BjornEngelen** [comment]
I have the exact same issue

**Comment by leastprivilege** [comment]
Please upgrade to the the latest bits. Otherwise we can't help you.

**Comment by Iymcjames** [comment]
I am having this same issue as well. Any help?

**Comment by matthieume** [comment]
I had the same with a project using Angular.
I successfully fixed it by updating the oidc-client dependency in package.json to 1.9.0 
Then generate a new project from scratch and copying the generated Typescript files linked to authentication (/api-authorization/) to my project.

**Comment by leastprivilege** [comment]
Yep - as I said. Please either start from scratch with the RTM template or use the above technique.
