### ISSUE TITLE
Should I use hybrid flow or authorization code + PKCE

### ISSUE THREAD

**Issue by baskooistra** [IdentityServer/IdentityServer4#3695]
Hi,

I have read the docs clearly stating that for server applications hybrid flow should be the grant type to go for. However, I have also read somewhere else that the authorization code flow + PKCE (without a need for client secret) should be considered as the new standard to replace all the other flows, in all situations.

Can anyone elaborate on this?

Kind regards,

Bas

**Comment by leastprivilege** [comment]
I updated our official guidance 

https://identityserver4.readthedocs.io/en/latest/topics/grant_types.html

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
