### ISSUE TITLE
Windows Authentication Provider DisplayName is null in Core 3.0

### ISSUE THREAD

**Issue by ThisNoName** [IdentityServer/IdentityServer4#3696]
Have been using Windows authentication for ages, google is just added here for comparison

```
services.Configure<IISOptions>(iis =>   {
	iis.AuthenticationDisplayName = "Windows";
	iis.AutomaticAuthentication = true;
});

services.AddAuthentication()
	.AddGoogle("Google", options =>   {
	options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
		... ... 
	});
```

### Issue / Steps to reproduce the problem

In .NET Core 2.1, everything works.  After upgrading to Core 3.0, Google still works, but Windows authentication provider DisplayName is always null.  So LoginViewModel.VisibleExternalProviders no longer returns Windows.

```
AuthenticationScheme	"Google"
DisplayName             "Google"

AuthenticationScheme	"Windows"
DisplayName              null
```

Tried all combination of program/startup settings mentioned in Microsoft and IdentityServer documentation, same result.  Not a deal breaker in my simple setup, but wondering if this is intended behavior.

Thanks.

**Comment by leastprivilege** [comment]
Thanks for reporting. We'll have a look.
