### ISSUE TITLE
Pushed Authorization Requests and Rich Authorization Requests

### ISSUE THREAD

**Issue by veikkoeeva** [IdentityServer/IdentityServer4#3697]
The purpose of this is to request a potential future feature. The problem statemets are copied as indicated by links augmented with more IdentityServer related information.

### Rich Authorization Requests
- Expressiveness of scopes is not sufficient for emerging OAuth scenarios, e.g. open banking.
- Allocation of requested permissions to resource server specific access token is hard (despite resource indicators).

Source: [Rich Authorization Requests (SlideShare)](https://www.slideshare.net/TorstenLodderstedt/rich-authorization-requests) by **Torsten Lodderstedt**. 

### Pushed Authorization Requests 

- OAuth authorization code flow sends parameters as URI query parameters via redirection in the user agent.
- Challenges:
 - There is no cryptographical integrity and authenticity protetion.
 - There is no mechanism to ensure confidentiality of request parameters.
 - Authorization request URLs can become quite large, especially in scenarios requiring fine-grained authorization data.

Source: [Pushed Authorization Requests (SlideShare)](https://www.slideshare.net/TorstenLodderstedt/pushed-authorization-requests) by **Torsten Lodderstedt**. 

**Additional context**
[Rich OAuth 2.0 Authorization Requests (Medium)](https://medium.com/oauth-2/rich-oauth-2-0-authorization-requests-87870e263ecb) by **Torsten Lodderstedt**.

[Transaction Authorization or why we need to re-think OAuth scopes (Medium)](https://medium.com/oauth-2/transaction-authorization-or-why-we-need-to-re-think-oauth-scopes-2326e2038948) by **Torsten Lodderstedt**.

[Comments back to “Transaction Authorization or why we need to re-think OAuth scopes”](https://nat.sakimura.org/2019/05/12/comments-back-to-transaction-authorization-or-why-we-need-to-re-think-oauth-scopes-by-torsten/) by **Nat Sakimura**.

[IdentityServer for ASP.NET Core 3](https://leastprivilege.com/2019/09/08/identityserver-for-asp-net-core-3/) by **Dominick Baier** due to mention of FAPI and its financial use these other APIs closely related, also [banking issues](https://github.com/IdentityServer/IdentityServer4/search?q=banking&type=Issues) and also [CIBA](https://github.com/IdentityServer/IdentityServer4/issues/3216) that seem to be related to FAPI.

**Comment by leastprivilege** [comment]
Thanks - 

yes there are a couple of things we want to re-work. 

This is tracked here

https://github.com/IdentityServer/IdentityServer4/issues/3520

Feel free to continue the conversation on this thread.
