### ISSUE TITLE
Migration guide to 3.0.1

### ISSUE THREAD

**Issue by TulyOpt** [IdentityServer/IdentityServer4#3698]
Hi,

is there a migration guide to the 3.0.1 version ? Thanks !

**Comment by leastprivilege** [comment]
No. But it should be very straightforward. Did you run into any problems?

**Comment by TulyOpt** [comment]
I had this error : 
`Startup.cs(51,18): error CS1061: 'AuthenticationBuilder' does not contain a definition for 'AddGoogle' and no accessible extension method 'AddGoogle' accepting a first argument of type 'AuthenticationBuilder' could be found (are you missing a using directive or an assembly reference?)`

I solved my problem using [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#addauthorization-moved-to-a-different-assembly) ( Section [Add package references for removed assemblies](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#add-package-references-for-removed-assemblies) )
So I had to add this line to my vsproj : 
`<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="3.0.0" />`
