### ISSUE TITLE
Make these extension methods internal 

### ISSUE THREAD

**Issue by davidfowl** [IdentityServer/IdentityServer4#3699]
https://github.com/IdentityServer/IdentityServer4/blob/5a1c1f619fff365067bea16e56af729a2db2e507/src/IdentityServer4/src/Extensions/HttpResponseExtensions.cs#L17

Or maybe change the namespace? We’re working on adding some of these methods like WriteJsonAsync and they’ll likely clash (when we do).

Also IdentityServer is so commonly used it’s a less than ideal situation that these names get squatted on.

**Comment by leastprivilege** [comment]
I agree - they should be in our namespace.

**Comment by leastprivilege** [comment]
When do you want to add these methods? @davidfowl ?

**Comment by davidfowl** [comment]
They'll be part of 5.0 (WriteJsonAsync..), not sure about the HTML one.

**Comment by aboondeviant** [comment]
What about IEnumerableExtensions? These are internal in the Storage project but public in the IdentityServer4 project

https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/IdentityServer4/src/Extensions/IEnumerableExtensions.cs#L14

**Comment by brockallen** [comment]
all done
