### ISSUE TITLE
Question: how to hook up custom stores

### ISSUE THREAD

**Issue by ronaldkuijpers** [IdentityServer/IdentityServer4#37]
Hi all,

Current IdSrv4 samples all use InMemory Clients, Scopes and Users stores. In IdSrv3, a custom store could be hooked up using IdentityServerServiceFactory (see sample IdentityServer3.Samples/source/CustomUserService/CustomUserService/). However, in IdSrv4 I can't find the IdentityServerServiceFactory nor how to attach a custom store.
Is there a sample available using a custom (user) store? Or what is the extension point I should use?

Kind regards,
Ronald

**Comment by brockallen** [comment]
You put those implementations into the ASP.NET Core DI system.

**Comment by ronaldkuijpers** [comment]
Thanks!

**Comment by ninety7** [comment]
@ronaldkuijpers I still can't figure out how to tie IdServer custom stores to the DI system. Do you have an example of how to accomplish that?

**Comment by joaomello** [comment]
@ninety7 https://github.com/IdentityServer/IdentityServer4/issues/45

**Comment by ninety7** [comment]
Thanks!
