### ISSUE TITLE
After logging in-[Error] User is not authenticated

### ISSUE THREAD

**Issue by talal3000** [IdentityServer/IdentityServer4#370]
I have attempted merging AspNetIdentity and SqlServer integration examples.
I tried recreating the example twice. both same results.

Any thought would be a great help.

Thank you

[Startup.txt](https://github.com/IdentityServer/IdentityServer4/files/508171/Startup.txt)
[project.txt](https://github.com/IdentityServer/IdentityServer4/files/508172/project.txt)

[TeePro4.Auth.txt](https://github.com/IdentityServer/IdentityServer4/files/508161/TeePro4.Auth.txt)
[TeePro4.Web.txt](https://github.com/IdentityServer/IdentityServer4/files/508162/TeePro4.Web.txt)
[TeePro4.WebAPI.txt](https://github.com/IdentityServer/IdentityServer4/files/508163/TeePro4.WebAPI.txt)

**Comment by brockallen** [comment]
Can you ask a more specific question or identify a more specific issue?

**Comment by talal3000** [comment]
Apologies; I may not be good in putting things in clear question.. I will try:

I narrowed it down to this:
When i use the following lines the application works as expected:

            _services.AddDeveloperIdentityServer()
                .AddInMemoryScopes(SampleData.GetScopes())
                .AddInMemoryClients(SampleData.GetClients())
                .AddAspNetIdentity<IdentityUserExtended>();_

 When however i use the below code instead the application errors AFTER log in is successful. 
"http://my Identity server path/home/error?errorId=605b418d8064b450418543520a715c82"
The error msg when i check the logs is: User not authenticated .. when its trying to open authorize end point.

            _var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            var cert = new X509Certificate2(Path.Combine(_env.ContentRootPath, "my pfx path"), "my pass");
            var builder =
                services.AddIdentityServer() 
                .SetSigningCredential(cert)
                .AddConfigurationStore(o =>
            o.UseSqlServer(connectionString, oo =>
                oo.MigrationsAssembly(migrationsAssembly)))
        .AddOperationalStore(o =>
            o.UseSqlServer(connectionString, oo =>
                oo.MigrationsAssembly(migrationsAssembly)));

            builder.Services.AddTransient<IResourceOwnerPasswordValidator,    ResourceOwnerPasswordValidator<IdentityUserExtended>>();_

SO my question is:
- Could you kindly let me know what COULD be the problem? 
- What does AddDeveloperIdentityServer in technical terms differ from AddIdentityServer? (all the samples i saw were using the Developer function.
- What exactly does AddConfigurationStore do?
- What exactly does AddOperationalStore do?
- both the above 2 functions take MigrationsAssembly. What if my migration project is separate (I have a separate project actually that handles EF migration).

Sorry many questions but i am really trying to get this to work and i am unable to find the answers in the documentation or even Google.

**Comment by talal3000** [comment]
apologies; this turned out to be an issue with the settings that were retrieved from the database for CLIENT .. i can't believe it took me this long to figure it out.. Things are working now. 

Thank you for your time

**Comment by Valeriy1991** [comment]
Hi everyone!

I've got the same problem when I learned the [Quickstart 8](http://docs.identityserver.io/en/stable/quickstarts/8_entity_framework.html). 

As it turned out, the problem was that I registered the new user in ASP.NET Identity storage, but I'm not linked IdentityServer4 with ASP.NET Identity. To do this, you just need to add 1 line of code:
```
            var connectionString = @"Host=localhost;Port=5432;Database=IdentityServer4.Quickstart.8;Username=postgres;Password=postgres";

            // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                //options.UseNpgsql(Configuration.GetConnectionString("DefaultConnection")));
                options.UseNpgsql(connectionString));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();


            services.AddMvc();

            // Add application services.
            services.AddTransient<IEmailSender, AuthMessageSender>();
            services.AddTransient<ISmsSender, AuthMessageSender>();

            
            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            // configure identity server with in-memory users, but EF stores for clients and resources
            services.AddIdentityServer()
                .AddTemporarySigningCredential()
                .AddTestUsers(Config.GetUsers())
                .AddConfigurationStore(builder =>
                    builder.UseNpgsql(connectionString, options =>
                        options.MigrationsAssembly(migrationsAssembly)))
                .AddOperationalStore(builder =>
                    builder.UseNpgsql(connectionString, options =>
                        options.MigrationsAssembly(migrationsAssembly)))
                        .AddAspNetIdentity<ApplicationUser>(); // <-- This is the same line that I did not guess at first
```

I think, that this line must be include in Quickstart 8 tutorial page... At least as a "Note".
