### ISSUE TITLE
What's the proper way to maintain identity server 4 logged in  users' sessions when a breaking change applied 

### ISSUE THREAD

**Issue by max-market-engine** [IdentityServer/IdentityServer4#3700]
I searched on the Google with no luck about this. Most of the suggestions from the internet suggest that we can do something on the client side, but this doesn't suit my needs. 
I wonder is there possible to force the user to re-issue the token or log-out from the Identity Server 4 instead of the client side. If has, what's the proper way to do this?
For instance, when adding some additionally claims to the token, I would like to force all the clients to re-issue the token.  Otherwise the clients may occur errors.

**Comment by leastprivilege** [comment]
I don't think I follow.

What's the question?

**Comment by max-market-engine** [comment]
> I don't think I follow.
> 
> What's the question?

When updating the identity server logic, e.g. adding additional claims in the token, how to let all the clients get the latest token instead of using the old one? Is there a way to make a change on Identity Server side, which can force all the existing tokens becoming invalid immediately? So all the clients will re-issue a new token which includes additional claims.

**Comment by leastprivilege** [comment]
Tokens are typically short lived. So the next time the client gets a new token (or refreshes one) - you new logic will be executed.
