### ISSUE TITLE
IdentityServer .Net Core 3.0 & Owin/Katana Token validation

### ISSUE THREAD

**Issue by kkozlowski89** [IdentityServer/IdentityServer4#3705]
### Issue / Steps to reproduce the problem

Hello,

I started own project with IdentityServer4 and .Net Core 3.0. Everything works good. I'm able to generate token and consume via other .Net Core Api.
 The problem occured when I trying to "consume" token via .Net Framework Api (OWIN/Katana).

I always had: { "message": "Authorization has been denied for this request." }

I enabled system.diagnostics in my Owin/Katana project and I found interesting thing:

`Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Error: 0 : Authentication failed
System.ArgumentException: IDX10703: Unable to decode the 'header': ...  as Base64url encoded string. jwtEncodedString: .... ---> System.IdentityModel.Tokens.SecurityTokenException: IDX10702: Jwt header type specified, must be 'JWT' or 'http://openid.net/specs/jwt/1.0'.  Type received: 'at+jwt'.
   at System.IdentityModel.Tokens.JwtSecurityToken.Decode(String jwtEncodedString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityToken.cs:line 387
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.JwtSecurityToken.Decode(String jwtEncodedString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityToken.cs:line 376
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ReadToken(String tokenString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 627
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
    ProcessId=20692
    DateTime=2019-10-07T11:26:01.1811172Z `

So I tried to decode my token. I used jwt.io and it is the result:

![image](https://user-images.githubusercontent.com/10422142/66321460-e44d3080-e920-11e9-8f7f-bc90746b3e1a.png)

The type is: 'at+jwt' <----- so it's why my Owin project didnt understand it.

The problem is in Owin and System.IdentityModel.Tokens.Jwt

I cannot use version 5+ of System.IdentityModel.Tokens.Jwt because of Owin (Owin doesnt support it) so my token cannot be parsed through api. Only this version is able to read token with type: 'at + jwt'.

I created test project (simple .NET Framework library + xunit). I added System.IdentityModel.Tokens.Jwt 5.5.0 and eveyrhing was read correctly!

So now it is not possible to use IdentityServer4 in .Net Core 3 and consume through Owin/Kata Api but..... I repeated eveyrhing with .Net Core 2.2 -> I used IdentityServer4 with .Net core 2.2. I generated token and I checked again on jwt.io and here is the result:

![image](https://user-images.githubusercontent.com/10422142/66321273-9b957780-e920-11e9-8a8c-1b7d443bc960.png)

Now type is 'JWT' and my Owin/Katana Api authenticated correctly so the summary is:

When I generate token with IdentityServer4 and .Net Core 3.0 it doesn't work
When I generate token with IdentityServer4 and .Net core 2.2 it works

**Comment by leastprivilege** [comment]
Explicit typing of JWTs is recommended these days, that's why we made that change:

https://leastprivilege.com/2019/09/13/use-explicit-typing-for-your-jwts/

You can revert back to the old behavior by setting `IdentityServerOptions.AccessTokenJwtType` to empty string or `JWT`.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/3706

**Comment by kriwec** [comment]
Dominik - thanks. But it not resolve my problem.
- in old version - "aud" has additional  URL,
- "jti" - it looks like it use another algorithm for hash
![3637 - token](https://user-images.githubusercontent.com/26826426/66387072-802f7880-e9c3-11e9-8d8c-280052235fad.png)

**Comment by leastprivilege** [comment]
Yes - the`/resources` aud has been removed in favour of a typed JWT. If that causes problems you can add it back manually.

**Comment by kriwec** [comment]
Hi - I do not know - I need to check
Also JTI looks different - in old it looks like guid, in new it is some hash.

I think problem could be in IdentityModel - so .net 4.6 can convert IdentityModel 4.0 to IdentityModel 3.10.6.
in 3.0.0-preview3.4 - IdentityModel (>= 3.10.6), in newer one IdentityModel (>= 4.0.0-preview.3).

**Comment by xrkolovos** [comment]
> /resources



> Yes - the`/resources` aud has been removed in favour of a typed JWT. If that causes problems you can add it back manually.

how you can add it back?

thank you

**Comment by leastprivilege** [comment]
https://identityserver4.readthedocs.io/en/latest/search.html?q=EmitLegacyResourceAudienceClaim&check_keywords=yes&area=default
