### ISSUE TITLE
Marketing material for executive pitch

### ISSUE THREAD

**Issue by luis-cortina** [IdentityServer/IdentityServer4#3707]
Hi:

We are trying to create a sales pitch for our executives to implement identity server in our org. Everything I've seen from you guys is directed to devs. Do you have anything that could get us started but the target audience is less technical.

**Comment by leastprivilege** [comment]
No. sorry. 

I guess it would be your job to create technical facts into the things that your management likes to hear ;)

**Comment by luis-cortina** [comment]
@leastprivilege that's fair(though it doesn't hurt to ask)
