### ISSUE TITLE
'UserLoginSuccessEvent' does not contain a constructor that takes 6 arguments

### ISSUE THREAD

**Issue by haugan** [IdentityServer/IdentityServer4#3709]
Following the steps from https://identityserver4.readthedocs.io/en/latest/quickstarts/3_interactive_login.html it seems that something is broken. Might be me though, but just in case I'm reporting this anyway. Here's the signatures of the UserLoginSuccessEvent constructors:

UserLoginSuccessEvent(string provider, string providerUserId, string subjectId, string name)
UserLoginSuccessEvent(string username, string subjectId, string name, bool interactive = true)

Here's how it's being called e.g. in AccountController:115
new UserLoginSuccessEvent(user.Username, user.SubjectId, user.Username, clientId: context?.ClientId)

Visual Studio is complaining that the ClientId property doesn't fit.

**Comment by leastprivilege** [comment]
OK - the event has been changed at some point. We are in the process of re-writing the docs. So this will be fixed at some point.
