### ISSUE TITLE
How to connect login page on the angular and identity server 4?

### ISSUE THREAD

**Issue by Abdigapar** [IdentityServer/IdentityServer4#3710]
Good afternoon. I am new to identity server. I have a login page on the angular, I do not want to use the standard quick tart ui. I registered the login page as a new client. Which grand should I use: implicit or ResourceOwnerPassword? How to transfer the username and password of the user through the / connect / authorize angular? How is this implemented correctly?

**Comment by leastprivilege** [comment]
You can configure the location of the login page on the IdentityServerOptions. Registering it as a client is not the right way to do it.

I recommend you familiarize yourself first with the "standard" UI approach - and once you got that working - think about replacing the logon workflow.

I will close this - feel free to open more focused issues/questions
