### ISSUE TITLE
Quickstarts for v3 Release

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3711]
We have to many quickstarts - and updating them for each release is just too much work. Relying on external help has not proven to be feasible.

I'd like to simplify them - along the lines or our new grant types guidance

**core**

* Machine to Machine communication (aka client credentials)
* ASP.NET Core authentication only (using code flow) + external authentication
* ASP.NET Core authentication + API access (using code flow + PKCE)

**additional**

* JS client
* EF config
* ASP.NET Identity for authentication
* Device flow

@scottbrady91 Interested in EF and device flow?
@LindaLawton can you review them? But only say yes if you really have the cycles. Saying no is fine too.

I will work on core.

**Comment by scottbrady91** [comment]
Yeah, sure. As long as you give me a bit of notice each time :)

**Comment by LindaLawton** [comment]
Unfortunately starting this new job has been a bit more stressful than I anticipated.   I'm on vacation next week for ten days.   So that is a no from me.

Even my own blog is suffering 😣

**Comment by leastprivilege** [comment]
OK - I updated QS1-3 and remove the others from the index.

@scottbrady91 You can do a continuation from QS3 that shows moving the config and state to EF. Thanks!

**Comment by leastprivilege** [comment]
@scottbrady91 ?

**Comment by scottbrady91** [comment]
I'll submit a PR tonight

**Comment by scottbrady91** [comment]
See PR #3809

**Comment by brockallen** [comment]
I've added back in the QS for JS and AspId.
