### ISSUE TITLE
Duplicate sub claim

### ISSUE THREAD

**Issue by bdaniel7** [IdentityServer/IdentityServer4#3714]
I'm using ASP.NET Core 2.2 and IS4, v2.5.2 with a custom ProfileService:

```
public class IdentityWithAdditionalClaimsProfileService : IProfileService
{
  readonly IUserClaimsPrincipalFactory<ApplicationUser> claimsFactory;
  readonly UserManager<ApplicationUser> userManager;
  readonly DbContext dbContext;

  public IdentityWithAdditionalClaimsProfileService(UserManager<ApplicationUser> userManager, DbContext dbContext, IUserClaimsPrincipalFactory<ApplicationUser> claimsFactory)
  {
    this.userManager = userManager;
	this.dbContext = dbContext;
	this.claimsFactory = claimsFactory;
  }

public async Task GetProfileDataAsync(ProfileDataRequestContext context)
  {
    var sub = context.Subject.GetSubjectId();
	var user = await userManager.FindByIdAsync(sub);
	var systemRoles = await userManager.GetRolesAsync(user);
	var principal = await claimsFactory.CreateAsync(user);
	var claims = principal.Claims.ToList();

	var businessRoles = await getDistinctBusinessRolesForUser(sub);
	claims.AddRange(systemRoles.Select(role => new Claim(JwtClaimTypes.Role, role)));
	claims.AddRange(businessRoles.Select(role => new Claim(JwtClaimTypes.Role, role)));
	context.IssuedClaims = claims;
  }
```
The ```claimsFactory``` is the "default" one, and it creates a collection of claims where sub appears twice.

![bug](https://user-images.githubusercontent.com/215914/66487674-6ff7c600-eab5-11e9-812a-8e244805703e.png)

Which causes a **Sequence contains more than one matching element** exception in ```UserInfoResponseGenerator.ProcessAsync```.

Method ```IdentityWithAdditionalClaimsProfileService.GetProfileDataAsync``` is called twice, once from ```DefaultClaimsService```, once from ```UserInfoResponseGenerator.ProcessAsync```.

Is this a bug? How should I configure IS4 to avoid this?

**Comment by leastprivilege** [comment]
You don't need to set a sub claim at all in the profile service. Give that a try.

**Comment by bdaniel7** [comment]
Well, I'm not setting any **sub** claim.
When the call ```var principal = await claimsFactory.CreateAsync(user);``` returns, ```principal.Claims``` already has two **sub** claims.

**Comment by klioqc** [comment]
Probably you have it in the asp. Net table with custom user claims?

**Comment by bdaniel7** [comment]
Well, yes. Shouldn't they be there? I have the following: sub, email_verified, email, family_name, given_name, userName.
These claims things confuse me very much...

**Comment by klioqc** [comment]
No, those predefined claims are added automatically

**Comment by bdaniel7** [comment]
Right. Then I will close this.
