### ISSUE TITLE
IDP does not redirect to post_logout_redirect_uri due to id_token_hint values not as expected

### ISSUE THREAD

**Issue by timg83** [IdentityServer/IdentityServer4#3716]
Hi

I have a client (not under my direct control) that does a logout on the connect/endsession endpoint
supplying an id_token_hint, post_logout_redirect_uri

The URL looks like:
https://account-test.muppet.nu/connect/endsession?id_token_hint=<tokenhint>&state=ok&post_logout_redirect_uri=https%3A%2F%2Fplan.muppet.nu%2Fopenid%2Fmuppets%2Fpost-logout

The user gets logged out of the IDP but the redirect to the post logout redirect URI isn't happening. I have configured the redirect URI to be allowed.

The (anonimized) token looks like this:

```
{
  "nbf": 1568880050,
  "exp": 1568883650,
  "iss": "https://account-test.muppet.nu",
  "aud": [
    "https://account-test.muppet.nu/resources",
    "muppets-api"
  ],
  "client_id": "plan-test",
  "sub": "0657988e-fdec-41c6-868c-bad6334e6f54",
  "auth_time": 1568880049,
  "idp": "local",
  "AspNet.Identity.SecurityStamp": "7WTFC3HBMLURCKW6UEY4RIMJUCZ7AK26",
  "preferred_username": "kevin@muppet.nu",
  "name": "kevin@ymuppet.nu",
  "email": "kevin@muppet.nu",
  "email_verified": true,
  "muppet_id": "2964",
  "muppet_is_member": "false",
  "scope": [
    "openid",
    "profile",
    "email",
    "muppet_company",
    "muppets-api"
  ],
  "amr": [
    "pwd"
  ]
}
```

In the logging I see that IdentityServer tries to validate the client using the aud element from the token:

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Validation/Default/TokenValidator.cs#L496

Which gives: https://account-test.muppet.nu/resources ...which is not a valid client id for our IDP.

1. Now where does the https://account-test.muppet.nu/resources aud comes from? Our IDP has nothing like that.
2. Why does IdentityServer uses the aud element instead of the client_id (which is a valid client on our IDP)?
3. Is it possible that my client has been changing/tampering the token_hint?

Thank you identity gods 🙂

**Comment by leastprivilege** [comment]
Because the client sends the access token and not the identity token.

**Comment by timg83** [comment]
Thanks for the information Dominick! That makes sense... But how can I see the difference between an access token and an identity token?

**Comment by leastprivilege** [comment]
Not sure I understand - they come back as different tokens from the token request...

**Comment by timg83** [comment]
Sorry, let me explain.

Currently we are flying blind. The client connects to us and the only thing I can rely on is the IdentityServer logging and the network traffic I capture through developer tools in the browser. So I can see the URL with the tokenhint and I can decrypt it using jwt.io. But is it visible in the decrypted token that the client is sending an acces token and not an id token? So, how can I see the difference between an access token and an identity token (keep in mind we have no control over how the client uses our IDP endpoints. Framework, self rolled, ...?)

I hope I made my self a bit more clear 🙂

**Comment by leastprivilege** [comment]
The id_token aud claim must be the client ID of the client.

**Comment by timg83** [comment]
Ok thx for clearing up. I give it back to the developers of the client application.
