### ISSUE TITLE
Content Security Policy error and redirect loop 

### ISSUE THREAD

**Issue by bdaniel7** [IdentityServer/IdentityServer4#3717]
All of a sudden I'm getting CSP errors and a redirect loop after the user is authenticated:

The redirect occurs when the request is made from http://localhost:5200/connect/authorize?client_id=mvc&redirect_uri=http%3A%2F%2Flocalhost%3A5400%2Fsignin-oidc

Even though I have set in the SecurityHeaders attribute the following:

```
var csp = "default-src 'self' http://localhost:5200; img-src 'self' data: http://localhost:5200 ;"
```

where http://localhost:5200 is the IS4 instance.

"Refused to load the image 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWx...' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback."

And this error happens for 5 data:image requests.

When I inspect the response headers for the request, I see 
```Content-Security-Policy: default-src 'none'; script-src 'sha256-orD0...'```

**Comment by brockallen** [comment]
This happens from a top level window or from an iframe scenario?

**Comment by brockallen** [comment]
Closing due to lack of response.
