### ISSUE TITLE
EF Core 3.0 multiple Include performance on FindByClientIdAsync making Identity Server 4 3.0.1 unusable

### ISSUE THREAD

**Issue by ericgreenmix** [IdentityServer/IdentityServer4#3718]
The following client query executes EXTREMELY slowly on IS4 3.0.1.

https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Stores/ClientStore.cs#L52

This looks to be caused by the following EF Core 3.0 issue.

https://github.com/aspnet/EntityFrameworkCore/issues/18022

I have verified that in IS4 2.* (using EF Core 2.2) it breaks the Includes out into separate DB queries, making the `FindByClientIdAsync` method execute quickly.

However in IS4 3.0.1 (using EF Core 3.0.1) it uses the following huge query which is extremely slow.

```
SELECT t.id, t.absolute_refresh_token_lifetime, t.access_token_lifetime, t.access_token_type, t.allow_access_tokens_via_browser, t.allow_offline_access, t.allow_plain_text_pkce, t.allow_remember_consent, t.always_include_user_claims_in_id_token, t.always_send_client_claims, t.authorization_code_lifetime, t.back_channel_logout_session_required, t.back_channel_logout_uri, t.client_claims_prefix, t.client_id, t.client_name, t.client_uri, t.consent_lifetime, t.created, t.description, t.device_code_lifetime, t.enable_local_login, t.enabled, t.front_channel_logout_session_required, t.front_channel_logout_uri, t.identity_token_lifetime, t.include_jwt_id, t.last_accessed, t.logo_uri, t.non_editable, t.pair_wise_subject_salt, t.protocol_type, t.refresh_token_expiration, t.refresh_token_usage, t.require_client_secret, t.require_consent, t.require_pkce, t.sliding_refresh_token_lifetime, t.update_access_token_claims_on_refresh, t.updated, t.user_code_type, t.user_sso_lifetime, c0.id, c0.client_id, c0.grant_type, c1.id, c1.client_id, c1.redirect_uri, c2.id, c2.client_id, c2.post_logout_redirect_uri, c3.id, c3.client_id, c3.scope, c4.id, c4.client_id, c4.created, c4.description, c4.expiration, c4.type, c4.value, c5.id, c5.client_id, c5.type, c5.value, c6.id, c6.client_id, c6.provider, c7.id, c7.client_id, c7.origin, c8.id, c8.client_id, c8.key, c8.value
FROM (
    SELECT c.id, c.absolute_refresh_token_lifetime, c.access_token_lifetime, c.access_token_type, c.allow_access_tokens_via_browser, c.allow_offline_access, c.allow_plain_text_pkce, c.allow_remember_consent, c.always_include_user_claims_in_id_token, c.always_send_client_claims, c.authorization_code_lifetime, c.back_channel_logout_session_required, c.back_channel_logout_uri, c.client_claims_prefix, c.client_id, c.client_name, c.client_uri, c.consent_lifetime, c.created, c.description, c.device_code_lifetime, c.enable_local_login, c.enabled, c.front_channel_logout_session_required, c.front_channel_logout_uri, c.identity_token_lifetime, c.include_jwt_id, c.last_accessed, c.logo_uri, c.non_editable, c.pair_wise_subject_salt, c.protocol_type, c.refresh_token_expiration, c.refresh_token_usage, c.require_client_secret, c.require_consent, c.require_pkce, c.sliding_refresh_token_lifetime, c.update_access_token_claims_on_refresh, c.updated, c.user_code_type, c.user_sso_lifetime
    FROM clients AS c
    WHERE (
        c.client_id = @__clientId_0)
        AND (@__clientId_0 IS NOT NULL)
        LIMIT 1 ) AS t
LEFT JOIN client_grant_types AS c0 ON t.id = c0.client_id
LEFT JOIN client_redirect_uris AS c1 ON t.id = c1.client_id
LEFT JOIN client_post_logout_redirect_uris AS c2 ON t.id = c2.client_id
LEFT JOIN client_scopes AS c3 ON t.id = c3.client_id
LEFT JOIN client_secrets AS c4 ON t.id = c4.client_id
LEFT JOIN client_claims AS c5 ON t.id = c5.client_id
LEFT JOIN client_id_p_restrictions AS c6 ON t.id = c6.client_id
LEFT JOIN client_cors_origins AS c7 ON t.id = c7.client_id
LEFT JOIN client_properties AS c8 ON t.id = c8.client_id
ORDER BY t.id, c0.id, c1.id, c2.id, c3.id, c4.id, c5.id, c6.id, c7.id, c8.id
```

This renders IS4 v3 unusable for us. As calling the `authorize` endpoint hits this query, causing it to take over a minute to return because of this query.

**Comment by leastprivilege** [comment]
@scottbrady91 can you have a look?

**Comment by scottbrady91** [comment]
I've had a quick look using the EF template. I'm seeing the same query as you but it's still sub-second even when I throw in a couple thousand client applications.

Can I get a bit more information so that I can try and get a feel for when it gets slow? How many client applications do you have? I assume this is SQL Server?

**Comment by ericgreenmix** [comment]
@scottbrady91 We are using Postgres. We have 8 clients in our system. So you have to have enough data in the client tables to have a bigger cartesian product. In our case, we have around 10 redirect URI's and 5 post logout redirect URI's. This is the main cause of the cartesian product being so large. It puts the query returning ~140k rows.

**Comment by scottbrady91** [comment]
Okay, I'm seeing it now. My test data wasn't good enough :)

@leastprivilege This is something we'll need to address. I'm happy to pick this one up

**Comment by leastprivilege** [comment]
go for it!

**Comment by scottbrady91** [comment]
I've sent a PR. I checked the performance on the includes in the resources store too but I couldn't get anything slower than a few hundred milliseconds. If anyone experiences anything different, let me know.

**Comment by huan086** [comment]
@scottbrady91 any idea why the original code wasn't using LoadAsync? I see that you changed the code to something like @ericgreenmix's code, but it's using Load instead of LoadAsync

**Comment by scottbrady91** [comment]
@huan086 check out the long running discussion here: https://github.com/IdentityServer/IdentityServer4/issues/2067

**Comment by huan086** [comment]
I see that the conclusion is that it'll be async in the next version of identity server.

**Comment by leastprivilege** [comment]
Async will not speed up queries.

@scottbrady91 changed the query. It is faster now.
