### ISSUE TITLE
Override/Customize the generated ClaimsPrincipal

### ISSUE THREAD

**Issue by slogmaverick** [IdentityServer/IdentityServer4#372]
I have implemented IdentityServer4 in a new .NET Core API project.  The project does NOT use AspNetIdentity or Entity Framework.
I like that IdentityServer sets up the ClaimsPrincipal so that it's easy to access it via this.User in my controller.
The issue I'm having is that there are claims that I want to be part of the ClaimsPrincipal but not part of the JWT.  
Here's what I've tried so far, none has accomplished what I want.
- Excluding claims in the ProfileService.
- Excluding claims in the ClaimsService.
- Adding a custom ClaimsIdentity to the context.Subject in the ProfileService.
- Implement an IUserClaimsPrincipalFactory.... CreateAsync never got called.

Is there a service in IdentityServer that I can implement to allow override/customization of the ClaimsPrincipal that is generated?

**Comment by leastprivilege** [comment]
The profile service collects all the claims for the various tokens - but whatever you return there, goes into the token.

**Comment by slogmaverick** [comment]
Is there any way to get access to the ClaimsPrincipal before IdentityServer sets it as the User context of my app so that I can add claims or add a custom ClaimsIdentity?

**Comment by leastprivilege** [comment]
You set the ClaimsPrincipal yourself - it's the cookie you issue on the login pahe.

**Comment by slogmaverick** [comment]
I should have been more specific.  I am using IdentityServer with an API, we don't have any kind of front end connecting to it, only a console app right now using Resource Owner flow.

After successfully authenticating the credentials IdentityServer is automatically setting the User in the HttpContext.  That's what I'm hoping to be able to get a hook into so that we can extend the properties of that ClaimsPrincipal User.  I can't see where Context.Authentication.SignInAsync is exposed where I can do that.

**Comment by brockallen** [comment]
> After successfully authenticating the credentials IdentityServer is automatically setting the User in the HttpContext

Where is this happening?

**Comment by slogmaverick** [comment]
Upon further investigation it looks as though AspNetCore is creating the ClaimsPrincipal from the JWT token being used.  
It looks as though I'm able to hook into the JwtBearerEvents middleware using IdentityServerAuthenticationOptions in order to get access/transform the ClaimsPrincipal and ClaimsIdentity.

**Comment by icistrate** [comment]
@slogmaverick I am interested to know if your approach transforming claims hooking into JwtBearerEvents worked ok for you. I also want to have my own ClaimsPrincipal created, but only when user is authorized (because I have to call database for retrieving some extra permissions)

**Comment by wilson0007** [comment]
You can replace the NoopClaimsTransformation service that gets added as a singleton when adding the authentication service.  NoopClaimsTransformation implements the IClaimsTransformation interface.

IClaimsTransformation interface contains one Method called "TransformAsync()" that takes in the claims principle. This method used by Authentication and get's called immediately after the claim principle is built. It appears to me that the NoopClaimsTransformation class being used by default is meant to be replaced as a means of doing exactly what you are describing. It's TransformAsync() does nothing but returns (Hence Noop).  

All you have to do it create a class that implements IClaimsTranformation, update your claims principle in the TransFormAsync() method, and add it as a singleton to the services (you may have to remove the NoopClaimsTransformation also).  I know I am responding to an old post, but I hope this helps anyone in the future.
