### ISSUE TITLE
Local SignalR Implementation

### ISSUE THREAD

**Issue by sebasunlam** [IdentityServer/IdentityServer4#3720]
I was wondering if is any implementation to autheticate a local signalR with identity server 4.
According to [this](https://docs.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-3.0) documentation, signlaR only receive a token in a querystring, But [this](http://docs.identityserver.io/en/latest/topics/add_apis.html) implementation only retrieve from Header so, any orientation about how can i authenticate a local hub that lives in the same project as identity server 4? I found this #2349 but this is not my scenario because identity server is in the same project

**Comment by leastprivilege** [comment]
You could wire up an additional JWT handler for your signalr hub.

**Comment by sebasunlam** [comment]
Sorry for the delay, so the idea would be to implement JWT like microsoft recomends, and validete the token with the introspection endpoint? or i should validate with my key material localy?

**Comment by leastprivilege** [comment]
All I am saying is you can add any authentication handler you like - e.g. exactly like MS describes it.

**Comment by leastprivilege** [comment]
another option would be to add a feature to the local API plumbing to read tokens from alternative locations...

**Comment by sebasunlam** [comment]
Ok, thanks dominick for the reply, closing the question, and when i solve it i will post the solution for future related questions.
