### ISSUE TITLE
Guidance on using "post_logout_redirect_uri", but with dynamic/custom urls?

### ISSUE THREAD

**Issue by pauldotknopf** [IdentityServer/IdentityServer4#3721]
In my client app, I have a ```/logout``` that redirects to IdentityServer's end-session endpoint.

My problem is that I would like to redirect the user to the current page that they were on before signing out. I can't use ```post_logout_redirect_uri``` with random locations, since this path must be white-listed.

One approach is this:
* On client, navigate to ```/logout?returnUrl=/mycurrent-page```.
* Store ```returnUrl``` in memory, creating a ```state``` key to lookup later.
* Send ```state``` to the end session endpoint.
* When identity server redirects back to my ```post_logout_redirect_uri``` with the ```state```, I will look up the ```returnUrl``` and issue a redirect.

Is there another approach? Is this what you'd recommend?

PS: Thanks for the great product!

**Comment by leastprivilege** [comment]
The state approach is exactly how it's meant to be.
