### ISSUE TITLE
How to Get Subject.Identity.Name via ExtensionGrant and ProfileService

### ISSUE THREAD

**Issue by bugnuker** [IdentityServer/IdentityServer4#3722]
Hello,

I am trying to write my own ExtensionGrant using the IExtensionGrantValidator.

Here is some code to look at:

```
        public async Task ValidateAsync(ExtensionGrantValidationContext context)
        {
            
            var myClaims = new List<System.Security.Claims.Claim>
            {
                new System.Security.Claims.Claim("name", "testuser2"),
                new System.Security.Claims.Claim("sub", "testuser2")
            };

            context.Result = new GrantValidationResult("testuser2", GrantType, myClaims);
            return;
        }
```

After this returns, the ProfileService is triggered and the IsActiveAsync method is executed.

However, once in this method, the IsActiveContext does not have the Subject.Identity.Name populated. It does have the claims, and it does say validated = true. 

I'm currently using Subject.Identity.Name to get the username and make database calls, therefore my IsActiveAsync call is failing because this value is null. I'm looking for guidance on how to proceed. Should I be looking at another value instead of Subject.Identity.Name?
 
If not, how do I get this property populated with the subject name for ExtensionGrants?

Thanks in advance!

**Comment by brockallen** [comment]
The first param to `GrantValidationResult` is the `sub` claim type. Use that in your profile service.

**Comment by bugnuker** [comment]
Thanks for your reply. I will make that change in my ProfileService.
