### ISSUE TITLE
Manually creating access_tokens and refresh_tokens without ExtensionGrant

### ISSUE THREAD

**Issue by bugnuker** [IdentityServer/IdentityServer4#3723]
Hello,

I am trying to create a refresh_token and an access_token manually. I found this link:

https://github.com/IdentityServer/IdentityServer4/issues/356

This link recommends a CustomExtensionGrant. I have fully implemented this and it works as expected. However, this is now exposed to the public domain via an HTTP call. Anyone who happens to stumble across it might be able to access this function. I am sure I could secure it with extra credentials or something along those lines. 

However, instead of going down that path of securing the endpoint I am trying to find if there is a way to generate these tokens without making an HTTP call and using internal code libraries only. 

Is there any recommendation you can offer for creating access_token and refresh_token without making it exposed to the public domain?

Thanks in advance!

**Comment by brockallen** [comment]
If your extension grant does not authenticate the caller in any way, then you're not quite doing it right. Having said that, StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
