### ISSUE TITLE
When using ASP.NET Identity, the application cookie doesn't use the "login" urls.

### ISSUE THREAD

**Issue by pauldotknopf** [IdentityServer/IdentityServer4#3726]
I am using ASP.NET Identity with Identity Server.

```csharp
services.AddIdentity<User, Role>()
    .AddDefaultTokenProviders();

services.AddIdentityServer(options =>
{
    options.UserInteraction.LogoutUrl = "/logout";
    options.UserInteraction.LoginUrl = "/login";
});
```

However, when requests are redirected to the login page, the are sent to "/Account/Login".

It looks like Identity server tries to keep the default cookie up to date [here](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Configuration/DependencyInjection/ConfigureInternalCookieOptions.cs#L28), but IdentityServer doesn't realize that ASP.NET Identity configures the default cookie to be ```IdentityConstants.ApplicationScheme```. I can update the cookie manually using this:

```c#
services.Configure<CookieAuthenticationOptions>(
    IdentityConstants.ApplicationScheme,
    options => { options.LoginPath = "/login"; });
```

But what about the other cookies/settings that are changed?

```
if (name == IdentityServerConstants.DefaultCookieAuthenticationScheme)
{
    options.SlidingExpiration = _idsrv.Authentication.CookieSlidingExpiration;
    options.ExpireTimeSpan = _idsrv.Authentication.CookieLifetime;
    options.Cookie.Name = IdentityServerConstants.DefaultCookieAuthenticationScheme;
    options.Cookie.IsEssential = true;
    options.Cookie.SameSite = SameSiteMode.None;

    options.LoginPath = ExtractLocalUrl(_idsrv.UserInteraction.LoginUrl);
    options.LogoutPath = ExtractLocalUrl(_idsrv.UserInteraction.LogoutUrl);
    if (_idsrv.UserInteraction.LoginReturnUrlParameter != null)
    {
        options.ReturnUrlParameter = _idsrv.UserInteraction.LoginReturnUrlParameter;
    }
}

if (name == IdentityServerConstants.ExternalCookieAuthenticationScheme)
{
    options.Cookie.Name = IdentityServerConstants.ExternalCookieAuthenticationScheme;
    options.Cookie.IsEssential = true;
    // https://github.com/IdentityServer/IdentityServer4/issues/2595
    // need to set None because iOS 12 safari considers the POST back to the client from the 
    // IdP as not safe, so cookies issued from response (with lax) then should not be honored.
    // so we need to make those cookies issued without same-site, thus the browser will
    // hold onto them and send on the next redirect to the callback page.
    options.Cookie.SameSite = SameSiteMode.None;
}
```

Should I manually set cookie configuration with the settings above? I feel like IdentityServer should realize that we are using ASP.NET Identity, and use the correct cookie name.

Is there another place in code where cookies are incorrectly expected to be ```IdentityServerConstants.DefaultCookieAuthenticationScheme```? Should we review the code base and ensure that not other bugs/issue surface because of this?

**Comment by leastprivilege** [comment]
I would recommend you do all cookie related config on the cookie handler - and not IdentityServer. We will pick up the default handler per your asp.net authN config.

**Comment by pauldotknopf** [comment]
Understood.

You aren't concerned that this cookie settings be set in IdentityServer aren't being reflected when using ASP.NET Identity? I'd think that IdentityServer set them for good reason.

**Comment by leastprivilege** [comment]
No that's fine. We only added that for simple scenarios and that cookies work out of the box.

For most real world scenarios you want to wire up your own cookie handler to control all the settings.
