### ISSUE TITLE
Consider setting RequireConsent = false as a default

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3729]

**Comment by scottbrady91** [comment]
I get that a lot of people turn this off by default, but consent is a big feature of OAuth and I would expect to see it present by default.

I'm also concerned that this will cause more people to be confused on first use of IdentityServer, when they haven't learnt about OAuth and OpenID Connect yet. I've found that the consent screen helps people realize that OAuth is about delegation, that the end-user is the resource owner, and that this isn't about user authorization.

**Comment by leastprivilege** [comment]
I get all this - but 99% of the time, it's not used. And for the scenarios that we mostly use IS (business applications), it's not needed for most parts.

**Comment by brockallen** [comment]
merged
