### ISSUE TITLE
Expiry of AccessToken after its configured life time

### ISSUE THREAD

**Issue by rameshnlg** [IdentityServer/IdentityServer4#373]
Hi,
For automation simulation purpose, We are using a low value of AccessTokenLifetime(5 seconds) instead of the default value. I understood for previous post on idSvr3 is that there is an extra clock skew time of 5 minutes which we need to wait for the token to be not useful.

May i know where can we either disable/configure a low value for MaxClockSkewTime. As I realized there is no more configuration on the IdentityServer to set the ValidationMode

Thanks,
Ram

**Comment by leastprivilege** [comment]
That's a feature of the MS JWT token handler.
