### ISSUE TITLE
Remove unused SaveChanges APIs in EF DbContext Interfaces

### ISSUE THREAD

**Issue by beforan** [IdentityServer/IdentityServer4#3732]
Quick note first: I've tried to look around at existing questions related to this area (#3507 #2067) and frankly that makes this more confusing.

### Question

`IConfigurationDbContext` and `IPersistedGrantDbContext` both expect implementors to provide the following method in addition to the expected `DbSet`s:

`Task<int> SaveChangesAsync();`

However, EF Core's `DbContext` provides [an implementation that takes 1 optional parameter](https://github.com/aspnet/EntityFrameworkCore/blob/45a5ccd05dbc0ec30efb199ae98b8ae9a7ddbeae/src/EFCore/DbContext.cs#L528), which should presumably suffice for any call sites working with these interfaces.

Furthermore, as per the issues linked above, I see that IdentityServer4's EF Stores don't actually call `SaveChangesAsync()` (this is a work in progress as per #3674), which suggests to me the interfaces don't need the method implementing as it will never be called anyway.

Really I'm just making sure I don't need to do something important when implementing these interfaces, and if I have noticed this unnecessary requirement, maybe the interfaces can be updated to reflect that.

**Comment by scottbrady91** [comment]
I don't remember *exactly* why. I think it dates back to Entity Framework Core 1.x method signatures. It's something that can be updated, but unfortunately, it's a breaking change.

You're not missing anything. The default implementation just calls base: https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/DbContexts/ConfigurationDbContext.cs#L82

**Comment by brockallen** [comment]
Yep. I think in a 4.0 we can revisit it.

**Comment by brockallen** [comment]
Yea, there are 2 Save APIs -- any objections to removing both?

**Comment by brockallen** [comment]
Done
