### ISSUE TITLE
issue with identity Server3

### ISSUE THREAD

**Issue by shaikVali786** [IdentityServer/IdentityServer4#3733]
1.There is an error determining which application you are signing into. Return to the application and try again
2.    authority: <<Authority>>,
    client_id: <<Client ID>>,
    redirect_uri: window.location.protocol + "//" + window.location.host + "/login.html",
    post_logout_redirect_uri: window.location.protocol + "//" + window.location.host + "/index.html",

    // these two will be done dynamically from the buttons clicked, but are
    // needed if you want to use the silent_renew
    response_type: "id_token token",
    scope: "openid api",

    // silent renew will get a new access_token via an iframe 
    // just prior to the old access_token expiring (60 seconds prior)
    silent_redirect_uri: window.location.protocol + "//" + window.location.host + "/silent-renew.html",
    automaticSilentRenew: true,

    // will raise events for when user has performed a logout at IdentityServer
    monitorSession: true,

    // this will allow all the OIDC protocol claims to vbe visible in the window. normally a client app 
    // wouldn't care about them or want them taking up space
    filterProtocolClaims: true,

    // this will use the user info endpoint if it's an OIDC request and there's an access_token
    loadUserInfo: false,

    // Set OIDC Configuration for CORS issue 
    metadata: {
        issuer: <<Identity Server URL>>,
        authorization_endpoint: <<Identity Server URL>> + '/connect/authorize',
        userinfo_endpoint: <<Identity Server URL>> + '/connect/userinfo',
        end_session_endpoint: <<Identity Server URL>> + '/connect/endsession',
        jwks_uri: <<Identity Server URL>> + '/.well-known/jwks',
        token_endpoint: <<Identity Server URL>> + '/connect/token',
        check_session_iframe: <<Identity Server URL>> + '/connect/checksession',
        revocation_endpoint: <<Identity Server URL>> + '/connect/revocation',
        introspection_endpoint: <<Identity Server URL>> + '/connect/introspect'
    },

    signingKeys: [
        {
            kty: 'RSA',
            use: 'sig',
            kid: 'hg5ICghxImSPINSCHjbH4qErPq0',
            x5t: 'hg5ICghxImSPINSCHjbH4qErPq0',
            e: 'AQAB',
            n: 'xuyMn-rdHmhrJRjNHsWpbKAR0uv_qIk5oEquKFToDm5ia5vcJqitkofLedZ9Key1Om8O6cJV7U0v7OQwoo6xkL3O8fOBbkVoMTTfzBq13gGN_R5Ktx8tpdzl4SFGSuUaB51Zu75nJy6UWjIjJlWDi-_Wk3x7MljndJJD-a1D3kP6JNHJzWI3sGZUDGudJOIkEIOsxwjpHpUdadD0MexxiLbj0q50yWS_K_OmC1q0DD1lhlKoS5KoAeR9oHPzuZPP1NmEGc3QhJsMTEX6bEIbb6irC4mBq3VkN-BmxJL0O5TPNJKWw761W-Hxfx_a2wyBJaEuGGaSO-xnpfpstWvCWQ',
            x5c: ['MIIDKzCCAhOgAwIBAgIJAJfoWRoRIKzfMA0GCSqGSIb3DQEBBQUAMCwxKjAoBgNVBAMMIXFhbmNtaWRlbnRpdHlzZXJ2ZXIubnVjb21wYXNzLmNvbTAeFw0xNjA2MTUyMTM5MzdaFw0yNjA2MTMyMTM5MzdaMCwxKjAoBgNVBAMMIXFhbmNtaWRlbnRpdHlzZXJ2ZXIubnVjb21wYXNzLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbsjJ/q3R5oayUYzR7FqWygEdLr/6iJOaBKrihU6A5uYmub3CaorZKHy3nWfSnstTpvDunCVe1NL+zkMKKOsZC9zvHzgW5FaDE038watd4Bjf0eSrcfLaXc5eEhRkrlGgedWbu+ZyculFoyIyZVg4vv1pN8ezJY53SSQ/mtQ95D+iTRyc1iN7BmVAxrnSTiJBCDrMcI6R6VHWnQ9DHscYi249KudMlkvyvzpgtatAw9ZYZSqEuSqAHkfaBz87mTz9TZhBnN0ISbDExF+mxCG2+oqwuJgat1ZDfgZsSS9DuUzzSSlsO+tVvh8X8f2tsMgSWhLhhmkjvsZ6X6bLVrwlkCAwEAAaNQME4wHQYDVR0OBBYEFO8zJsvO9n+KPCoQY7LVk1/MTTBBMB8GA1UdIwQYMBaAFO8zJsvO9n+KPCoQY7LVk1/MTTBBMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAIcjBNrTTLhSvU7WcGnGPE3mqcwXQhdETt8aVm0HlqoruGhQorD+hETeNNiC3Ww9ZwMNhPh7am6cHpTCgCtV+d4l9IE5YSiwP6/muv8S+Bm0BgTQ0cWQl3QRk8S27SJfIdlcoDj89ULCoUSFwq4ueA0BjdiLNauBRx/c2hfJZZjV1IwKQXI9vnd4LWz6oBW6CdD8RYXX222jhryiOI1WBmZVdMnppLgaYqGP1XyMYgechJMzQKruuyvllgskKH+uNG7uVEpJIRp4rewlEeAdkCljC5nPpxQreDlPI0CYaGUtMhloUf45KjNUKFS8F+anfXMYihM0s3hXk+XYE4rT9zU='],
        }
    ]
 if i upgrading into identity Server 4 it will be Resolved or Not

**Comment by brockallen** [comment]
IdentityServer3 is no longer in support. IdentityServer4 has a different architecture here, but the fundamental issue is the same -- users that bookmark a login page in the middle of the OpenID Connect protocol will have possible issues because of the protocol (and not because of IdentityServer). In IdentityServer4 it's easier for you to write logic to deal with this.
