### ISSUE TITLE
IdentityServer4 负载

### ISSUE THREAD

**Issue by messcf** [IdentityServer/IdentityServer4#3734]
网关 我们部署了两套 是统一认证  轮询分发  IdentityServer认证服务也是两套  登录完之后  拿着token 在请求其他接口的时候  返回401 在网关分发的时候分发到不同的认证服务 然后就返回401。
需要怎么配置才能避免这种问题！ 谢谢

**Comment by leastprivilege** [comment]
sorry - don't understand a word besides token and 401 ;)

**Comment by messcf** [comment]
Thank you!
