### ISSUE TITLE
Passing 'prompt=login' to an idp defined by Acr value.

### ISSUE THREAD

**Issue by leninator** [IdentityServer/IdentityServer4#3736]
Hello Hopefully this falls into the remit of a simple problem!

I'm forcing a redirect to a specific third party provider using the acr value "idp:myprovider". This works flawlessly.

I would like my user to be forced to re-authenticate, so I also pass "prompt=login". Unfortunately prompt login is only passed as far as the initial authorize endpoint. It is not passed down the chain to my provider defined in the acr value.

1. Is it supposed to?
2. If it isn't then is there a simple way to make it do so?
3. Would if be bad practice for me to pass this down to my third party IDP?

Many Thanks,

**Comment by leastprivilege** [comment]
This wouldn't happen automatically. Also we "strip" the prompt parameter before we hit the login URL. So you could use a custom parameter and pass that through to the authN handler you want to challenge.
