### ISSUE TITLE
Where are endpoints in IdentityServer4 is4aspid template

### ISSUE THREAD

**Issue by Simplejash** [IdentityServer/IdentityServer4#3739]
I want to edit token parameters when token response, but I can't find token endpoint in IdentityServer4 is4aspid template.

Where can I find endpoints in IdentityServer4 is4aspid template? such as connect/token, connect/userinfo, connect/authorize. 

I cant's find those endpoints in Controllers, please help, thanks.

**Comment by leastprivilege** [comment]
Which sample code?

**Comment by brockallen** [comment]
> I tried to find the "connect/token" method in Quickstart Controllers, 

our middleware handles those endpoints:

http://docs.identityserver.io/en/latest/topics/signin.html#login-workflow
