### ISSUE TITLE
asp net identity UI error 

### ISSUE THREAD

**Issue by amSaighi** [IdentityServer/IdentityServer4#3740]
I found issue with the new samples example exactly in Quickstarts\1_ClientCredentials 

> Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
> [11:15:54 Debug] IdentityServer4.Startup
Login Url: /Account/Login

> [11:15:54 Debug] IdentityServer4.Startup
Login Return Url Parameter: ReturnUrl

> [11:15:54 Debug] IdentityServer4.Startup
Logout Url: /Account/Logout

> [11:15:54 Debug] IdentityServer4.Startup
ConsentUrl Url: /consent

> [11:15:54 Debug] IdentityServer4.Startup
Consent Return Url Parameter: returnUrl

> [11:15:54 Debug] IdentityServer4.Startup
Error Url: /home/error

> [11:15:54 Debug] IdentityServer4.Startup
Error Id Parameter: errorId

I didn't found the file appsettings.json in IdentityServer for configuration, 
I installed asp net identitu UI from nugetpackage the same problem

how we can resolve it 

thank you

**Comment by leastprivilege** [comment]
What exactly is the problem?

**Comment by amSaighi** [comment]
I wann use Asp Identity UI with this example Quickstarts\1_ClientCredentials

**Comment by leastprivilege** [comment]
a) this does not make sense because QS1 is about machine to machine and not end-user authentication
b) even then - what's the problem?

**Comment by amSaighi** [comment]
Thank you for the answer.
