### ISSUE TITLE
Get token from Azure AD using an httpClient

### ISSUE THREAD

**Issue by chuckgmthompson** [IdentityServer/IdentityServer4#3742]
Looking for a simple example on how to configure IdentityServer to allow a console client (httpClient) or even postman to get an access token using their Azure Active Directory username/password

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
