### ISSUE TITLE
How to run client application without IS for developing purpose?

### ISSUE THREAD

**Issue by dario-l** [IdentityServer/IdentityServer4#3743]
Is there any guideline which shows me how to setup client application for developing purpose?

Running IS for every time when I want to run/debug/test during development time will be hard.

**Comment by leastprivilege** [comment]
You can mock IS by setting HttpContext.User yourself - e.g. in a middleware.

**Comment by dario-l** [comment]
That's easy. I thought that IS has some implemented solution for that. :)

**Comment by leastprivilege** [comment]
No - too easy ;)
