### ISSUE TITLE
refresh_token grant with value:  refresh_token  not found in store.

### ISSUE THREAD

**Issue by messcf** [IdentityServer/IdentityServer4#3749]
I don't know why refresh_token grant with value: 6b6503a16e20e5eaabf5c1b96877256b810a23c67210741b24ec4bef05bab12c not found in store. Then return "error": "invalid_grant" .

But when I repeat the request, I can refresh the token normally. That is to say, I need to repeat the request twice before I can refresh the token normally.

Thank you for helping me out。

My configuration：
new Client
                {
                    ClientId = "yysy.wallet.com",
                    ClientName = "yysysystem",
                    ClientSecrets = new [] { new Secret("websecret".Sha256()) },
                    AccessTokenLifetime = AppSettings.TokenLifetime,
                    RefreshTokenExpiration = TokenExpiration.Sliding,
                    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
                    RefreshTokenUsage = TokenUsage.OneTimeOnly,
                    AllowOfflineAccess = true,
                    AllowedScopes = new [] {
                        "YYSYWalletService",
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile }
                }

**Comment by leastprivilege** [comment]
I don't know either.
