### ISSUE TITLE
Error after moving to EntityFramework Core for configuration data

### ISSUE THREAD

**Issue by noufionline** [IdentityServer/IdentityServer4#375]
Hi There,
Just trying to setup EntityFramework Core to save the configuration data. after updating hybrid sample example is giving the following error.

An unhandled exception occurred while processing the request.

InvalidOperationException: No signing credential is configured. Can't create JWT token

From this code
```
services.AddDeveloperIdentityServer()
                .AddInMemoryScopes(Config.GetScopes())
                .AddInMemoryClients(Config.GetClients())
                .AddAspNetIdentity<ApplicationUser>();

```
changed to 

```
 var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
            string connectionString = Configuration.GetConnectionString("IdentityServer");

            services.AddIdentityServer()
                .AddConfigurationStore(
                    builder => builder.UseSqlServer(connectionString,
                    options => options.MigrationsAssembly(migrationsAssembly)))
                .AddOperationalStore(
                    builder => builder.UseSqlServer(connectionString,
                    options => options.MigrationsAssembly(migrationsAssembly)))
                .AddAspNetIdentity<ApplicationUser>();
```
Did I miss anything?

**Comment by diogodamiani** [comment]
You should set the signing credential. You could call the SetTemporarySigningCredential() extension method or one of SetSigningCredential overloads.

**Comment by noufionline** [comment]
Thanks a lot!!!
@diogodamiani Do we have any examples of doing this in the quickstart already?

**Comment by diogodamiani** [comment]
That's because before you were calling AddDeveloperIdentityServer and now AddIdentityServer. The AddDeveloperIdentityServer already set the temporary signing credential.

Have a look here how can you set the temporary: https://github.com/diogodamiani/IdentityServer4.MongoDB/blob/dev/src/Host/Startup.cs

And here how can you set a X509 certificate: https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Docker/src/IdentityServer/Startup.cs

**Comment by noufionline** [comment]
@diogodamiani now I understand. But when I am publishing identityserver to IIS how I have to load the certificate? 

Is the certificate (.pfx) needs to be published along with the app or will it take from iis certificate store?

**Comment by diogodamiani** [comment]
I think you can use both strategies. Publish with the app or get it from a certificate store.

**Comment by noufionline** [comment]
@diogodamoani I still need your help to figure out how to do it. how can I extract it from the certificate store?

**Comment by brockallen** [comment]
Look at the IdentityModel `X509` class.

**Comment by noufionline** [comment]
@brockallen and @diogodamiani
Thanks a ton👍

Managed to host in IIS successful 

Once again thanks for you Great help and fantastic support .
