### ISSUE TITLE
Consider removing PKCE plain method

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3750]
It's insecure and I am failing to see a legitimate use case.

Either remove altogether - or introduce global flag.

**Comment by scottbrady91** [comment]
A global flag to allow plain across all clients? That sounds worse than the client property.

**Comment by leastprivilege** [comment]
No - disable globally. Default to true. Or just remove it.

**Comment by kabua** [comment]
The problem I see with removing it is:

1. Plan is part of the spec. 
2. It is helpful when trying to debug why things aren't working.

If you can control it on a per client bases than adding a global flag would be disastrous.
