### ISSUE TITLE
Understanding Identityserver4 with Identity (cookies/tokens, server architecture)

### ISSUE THREAD

**Issue by NAasen** [IdentityServer/IdentityServer4#3752]
I also asked this question on SO, but not much response. I have some problems seeing the big picture when it comes to understanding how it all fits togheter. It's a big topic for a beginner.

What is the point of Identity's cookies and all its default templates/pages when combined with IdentityServer, when it issues tokens?

And why are these pages included in all the examples even when using SPA clients? Isn't the whole point to be able to authorize/authenticate/register via an API?

I see many suggest that one should have IdentityServer in it's own project, and then the user database on a local network separately, how is that possible? I have not found one sample of this.

Why is there any need to separate the userdatabase from the resource API, and isn't the combined IdentityServer4 and Identity its own API?

I appreciate your time and help.

**Comment by brockallen** [comment]
> I also asked this question on SO, but not much response. I have some problems seeing the big picture when it comes to understanding how it all fits togheter. It's a big topic for a beginner.

We have docs: http://docs.identityserver.io/en/latest/intro/big_picture.html

Beyond that, I'd suggest our training: https://identityserver.io/training/ or consulting: http://docs.identityserver.io/en/latest/intro/support.html

**Comment by NAasen** [comment]
Are you sure my questions are answered there? I don't think so. Because I have read everything.

**Comment by leastprivilege** [comment]
This issue tracker is about big reports and feature requests.

Please understand that we cannot provide free training of fundamentals or consulting here.
