### ISSUE TITLE
Please add full project or Startup.cs at Quickstart.UI

### ISSUE THREAD

**Issue by reyou** [IdentityServer/IdentityServer4#3753]
Title: | IdentityServer/IdentityServer4.Quickstart.UI: Starter UI for in-memory IdentityServer4
-- | --
Url: | https://github.com/IdentityServer/IdentityServer4.Quickstart.UI

Please turn this into a full project, or add Startup.cs for Service and Middle-ware registrations.
Without those registrations, copied code does not work in a brand new .net core project.

**Comment by leastprivilege** [comment]
You can use our templates for this purpose. They contain both UI and host.
