### ISSUE TITLE
Auth0 with IdentityServer4 multi-application SSO not working

### ISSUE THREAD

**Issue by sw-ms-pradipbaria** [IdentityServer/IdentityServer4#3758]
I have followed below article and configured Auth0 as external IDP. http://docs.identityserver.io/en/latest/topics/signin_external_providers.html

All working fine for single application login, and when i open second application in same browser it get session for second application's login (as auht0 cookie for user extists), but issue is i get logout from first application.

SessionId getting changed for both application for same user.

I need a same sessionId between application, is it possible with external IDP?

https://i.stack.imgur.com/pj15g.png
https://i.stack.imgur.com/KIvC3.png

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!

**Comment by sw-ms-pradipbaria** [comment]
@brockallen Thanks for reply, I have already asked over there. But not get any response so asking over here. With IDS clients it works fine but with external provider it is considering as 2 different idp. 

And get 2 different session for 2 external client.
Please help me out on this.

**Comment by brockallen** [comment]
Ok, then the issue is the session id in IdentityServer is changing? Can you elaborate?

**Comment by sw-ms-pradipbaria** [comment]
Thanks for reply, 
I am configuring all Auht0 applications as OpenIdConnect Client's in Identityserver.

So each auth0 application get treated as IDS client. Login is working file but SSO not working between 2 Auth0 applications (which is IDS client ideally).

Let me know if it is not clear and understandable.

![image](https://user-images.githubusercontent.com/31621470/67366361-f8d03080-f590-11e9-98af-8bf0223d01de.png)

**Comment by brockallen** [comment]
I'm confused:

> So each auth0 application get treated as IDS client

The code you show seems like it's adding those as IdPs, not as clients. And at the same time you're looping thru the client store? None of that makes sense.

**Comment by sw-ms-pradipbaria** [comment]
Hi, 

> The code you show seems like it's adding those as IdPs, not as clients.

Yes, you are right i am adding it as IDPs, I am not sure how to add them as client.
Can you share any details for same?


> And at the same time you're looping thru the client store? None of that makes sense.

I am looping through clients which are exists in Auth0. Is it needed?
Or I just have to register 1 IDP and then regeister it's client somewhere else?

**Comment by brockallen** [comment]
Ok, so it seems the issue is not a bug with how IdentityServer works. Check our docs and quickstarts for getting started with how to use IdentityServer. The issue tracker is not for training on how to use IdentityServer or architect your solution.

**Comment by sw-ms-pradipbaria** [comment]
You are right, but I am not able to make it work can you suggest/advice me any way to do it. It would be Great help for me.
