### ISSUE TITLE
RsaSha256Signature not supported?

### ISSUE THREAD

**Issue by span** [IdentityServer/IdentityServer4#3762]
### Issue / Steps to reproduce the problem
Add `RsaSha256Signature` as a signing algorithm to signing credentials.

### Relevant parts of the log file

```
Unhandled exception. System.InvalidOperationException: 
    Signing algorithm http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 is not supported.
    at
 Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCrypto.AddSigningCredential
    (IIdentityServerBuilder builder, SigningCredentials credential)

```

### Source

There is a check for valid signing algoritms in `Crypto.AddSigningCredential` that verifies the configured algoritm against the `IdentityServerConstants.SupportedSigningAlgorithms` constant. The constant do not contain any of the `*Signature` algoritms from `Microsoft.IdentityModel.Tokens.SecurityAlgorithms`.

Is this a feature or a bug? I am upgrading legacy code that is using the algorithm.

### Version
IdentityServer 3.0.1

**Comment by leastprivilege** [comment]
In the OIDC world - this algorithm is called `RS256`.

**Comment by span** [comment]
I see. So many options in `Microsoft.IdentityModel.Tokens.SecurityAlgorithms` my head is spinning. You rock.
