### ISSUE TITLE
Wildcard patterns / Globbing for Allowed CORS origins

### ISSUE THREAD

**Issue by enzian** [IdentityServer/IdentityServer4#3765]
I was wondering if there is a reason why it would not be possible to have a clients `AllowedCorsOrigins` support globb patterns like for example `https://*.contoso.org/`?

I would like to contribute this if it's something considered worth upstreaming...

**Comment by leastprivilege** [comment]
Wildcards in URLs are always dangerous from a security point of view.

If you need that particular feature and think you can implement it securely for your environment, please use our extensibility points to do it yourself. That's why they exist.

**Comment by enzian** [comment]
Thanks!
