### ISSUE TITLE
Asp.net core 3.0 Angular how to customize the identity server and config the events

### ISSUE THREAD

**Issue by collina2019** [IdentityServer/IdentityServer4#3766]
Do we have any Asp.net core 3.0 Angular identity server guide docs ? It is very simple :

`    services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();`

And for validating token :
`services.AddAuthentication()
              .AddIdentityServerJwt();`

But i don't know how to customize IDS4 , for example , how to extend the `ProfileService` to add claims .  In `AddIdentityServerJwt` , how to add jwt events like `OnTokenValidated` ?

Thanks

**Comment by leastprivilege** [comment]
This would be Microsoft's job to document their "DSL" on top of our config system.

To tap into the full power of IdentityServer and ASP.NET Core - you can just drop their convenience methods and go to the raw config system. You will find information in our docs about, e.g. the profile service.

**Comment by collina2019** [comment]
Thanks for the information .
