### ISSUE TITLE
[Question] CSP Scanner: Wildcard Directive alert for check session  endpoint 

### ISSUE THREAD

**Issue by yukund** [IdentityServer/IdentityServer4#3768]
Question:
We used ZAP 2.8 to scan our angular web application implemented with IdentityServer4 (implicit flow). It generated a Wildcard Directive alert (show in below), I am not sure it is a security issue or not.

If it is a security issue, what should we do? The OpenID Connect checksession endpoint is provided by IdentityServer4. We have implemented SecurityHeadersAttribute in order to set frameAncestors values, but it does not apply to the checksession endpoting.  Any suggestions? thanks

```
public class SecurityHeadersAttribute : ActionFilterAttribute {
    public override void OnResultExecuting(ResultExecutingContext context)
        {
. . .
                var frameAncestors = _configuration.GetSection("Uris:AllowedCorsOrigins").Get<string[]>().Join(" ");

                // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
                var csp = $"default-src 'self'; object-src 'none'; sandbox allow-forms allow-same-origin allow-scripts; base-uri 'self'; frame-ancestors {frameAncestors};";
```

Medium (Medium) | CSP Scanner: Wildcard Directive
-- | --
Description | The following directives either allow wildcard sources (or ancestors), are not defined, or are overly broadly defined:frame-ancestor
 
URL | https://cnwchcs103.cnw.co.nz:51723/jadethirdeye.services.identity/connect/checksession
Method | GET
Parameter | Content-Security-Policy
Evidence | default-src 'none'; script-src 'sha256-ZT3q7lL9GXNGhPTB1Vvrvds2xw/kOV0zoeok2tiV23I='
Instances | 1
Solution | Ensure that your web server, application server, load balancer, etc. is properly configured to set the Content-Security-Policy header.

**Comment by leastprivilege** [comment]
Ah - the beauty of security scanners ;)

The check session endpoint is supposed to be loaded inside an iframe. So not sure what the issue is...

**Comment by yukund** [comment]
Hi @leastprivilege 
I asked ZAP team as well for this alert.  They explained that " frame-ancestors does not fall back to the default sources when the directive is not defined. That is, policy that defines default-src 'none' but not frame-ancestors will still allow the resource to be framed from anywhere."

Does IdentityServer want session management script to be able to be used anywhere?  or any recommend configurations for `frame-ancestors?

Thanks

**Comment by leastprivilege** [comment]
Well - I don't see an issue here since this is not security sensitive.

But you could always add a middleware to the pipeline that adds the relevant headers.

@brockallen is this something we should add?

**Comment by brockallen** [comment]
I think we do, since we don't know which client is making the request for it. Plus, the session mgmt spec has mitigations against attackers trying to glean info about the session.

**Comment by leastprivilege** [comment]
> I think we do

What does that mean. Do we need to something - or do we close the issue?

**Comment by brockallen** [comment]
We can't set a CSP header with an ancestor since we don't know which requesting app/SPA is including the check_session endpoint.
