### ISSUE TITLE
Validate previously authenticated user based on the Tenant passed by the Client

### ISSUE THREAD

**Issue by RickBlouch** [IdentityServer/IdentityServer4#377]
Hi,

I am using MVC Hybrid flow based on the samples in your repository.  I have the login flow working successfully where authentication is utilizing a tenant specific user store to validate the username / password.  The trouble I'm having is that I need a way within my IdentityServer to restrict an already authenticated user's access to tenant sites for which he should not have access.

**Scenario**

1. User navigates to https://**tenant1.website.com**/someprotectedresource
2. User is redirected to IdentityServer to authenticate.  Client forwards **TenantId (1)** in AcrValues
3. User sees Client & Tenant specific login page
4. User enters credentials and we authenticate them against the proper user store (DB per tenant)
5. User is redirected back to https://**tenant1.website.com**/someprotectedresource
6. User is issued an auth cookie for tenant1.website.com

So far so good.  However if the same user who is authenticated with IdentityServer now does the following:

1. User navigates to https://**tenant2.website.com**/someprotectedresource
2. User is redirected to IdentityServer to authenticate.  Client forwards **TenantId (2)** in AcrValues
3. User is already authenticated with IdentityServer
4. User is redirected back to https://**tenant2.website.com**/someprotectedresource
5. User is issued an auth cookie for tenant2.website.com

This user should not have access to the tenant2 site but he does.  

**What I have tried**

Override IsActiveAsync on IProfileService.  The problem is I can't figure out how retrieve the Tenant being forwarded to IdentityServer from the client.  Is there any way to access the Tenant within a custom IProfileService?  I'm not sure how I could implement either of these methods without knowing the Tenant.  When I attempting hardcoded returning IsActive = false for the second half of the flow above, I got the desired result of sending the user to the login page for tenant2.

Override ValidateAsync on ICustomAuthorizeRequestValidator.  I have all the information I need here to perform the validation.  I set IsError = true, and Error = "unauthorized".  This sends the user to Home/Error page which might work, however I don't see a way to get the Tenant.  I call the IdentityServerInteractionService with an errorId which gives me some details about the error.  Is there a way to use the RequestId to get the original request AuthorizationContext?  I searched the repo but didn't see anything already using it in that way.  Alternatively I could pass TenantId through the Error property but that seems like a hack and I would question if a future IdentityServer change would break that functionality.  I'm also not sure how I could send the user to the login page from the error page without having a valid returnUrl.

What is the recommended way using IdentityServer hooks to handle this scenario?

Thanks,
Rick

**Comment by brockallen** [comment]
> This user should not have access to the tenant2 site but he does. 

Fundamentally the app should be enforcing this. IIRC we pass along a tenant param as a claim? Maybe that was in IdSvr3... but you could add this claim in the profile service or at login time.

Now, could IdentityServer do something more to help... we'd need to check the tenant param and compare to the current logged in user's tenant and then force re-authentication. 

I'll leave this open so we can think more about it.

**Comment by RickBlouch** [comment]
Thanks for the quick reply.  I have spent some time working through your first comment which I agree with.

> Fundamentally the app should be enforcing this. 

So then with this in mind, would your opinion be to do the site / tenant authorization in the OnTicketReceived event in my Client?  If it's determined that they should not have access, call SignOutAsync('oidc') which will then redirect back to and sign out from IdentityServer.

The only hitch with the above that I've seen so far is I will have to manually retrieve and attach the IdTokenHint so the call to the EndSession endpoint will work as expected.

Then I will need to figure out whether to show an unauthorized error message, or just send them to a login screen.

**Comment by RickBlouch** [comment]
> Now, could IdentityServer do something more to help... we'd need to check the tenant param and compare to the current logged in user's tenant and then force re-authentication.

I also wanted to comment on this.  Instead of having anything built into IdentityServer to handle tenant authentication, I think it would be better to just have an extensibility point and let the implementing system write the authentication logic.

I have some scenarios where a user could have access to 2 or 3 tenant sites, but not all of them which what you described above would not accommodate.

Based on my testing, it would seem like the IsActive hook in the ProfileService would be a fair enough place to implement this logic if it provided me the request context so I could get Tenant.  I can't speak to how big of an effort that would be though as I don't know the internals of IdentityServer very well.

Thanks for your efforts!

**Comment by brockallen** [comment]
> So then with this in mind, would your opinion be to do the site / tenant authorization in the OnTicketReceived event in my Client? If it's determined that they should not have access, call SignOutAsync('oidc') which will then redirect back to and sign out from IdentityServer.

Sure -- really anywhere in your app when the authenticated user arrives you need to ensure they meet any requirements. This is just normal authorization that apps should do.

> I also wanted to comment on this. Instead of having anything built into IdentityServer to handle tenant authentication, I think it would be better to just have an extensibility point and let the implementing system write the authentication logic.

I have a feeling this will allow for your requirement: https://github.com/IdentityServer/IdentityServer4/issues/166#issuecomment-252442506. If so, then perhaps we can close this issue?

**Comment by RickBlouch** [comment]
> I have a feeling this will allow for your requirement: #166 (comment). If so, then perhaps we can close this issue?

I think you may be right.  I briefly reviewed the `AuthorizeInteractionResponseGenerator` and I think if I could override the `ProcessLoginAsync` method that would work.  I would still want to run the base logic, only applying my logic if the base logic was successful.

I would like to note that the `IsActiveAsync `hook on `ProfileService `would still be unusable for me and many multi-tenant scenarios I would imagine, but I could ignore it and add that logic to my custom `AuthorizeInteractionResponseGenerator` instead.

I will close this issue and follow the other.  Thanks again!
