### ISSUE TITLE
PK_PersistedGrants should be nonclustered by default

### ISSUE THREAD

**Issue by enikitin** [IdentityServer/IdentityServer4#3770]
The key value is effectively a random string.

https://github.com/IdentityServer/IdentityServer4/blob/f2cca2a73a886ebb7d9d6cdbf85deb0df08ca75c/src/IdentityServer4/src/Stores/Default/DefaultGrantStore.cs#L154

By default PK_PersistedGrants is created as a clustered index.

https://github.com/IdentityServer/IdentityServer4/blob/f2cca2a73a886ebb7d9d6cdbf85deb0df08ca75c/src/EntityFramework.Storage/migrations/SqlServer/Migrations/PersistedGrantDb.sql#L33

Clustered indexes on random values cause performance issues. I suggest that PK_PersistedGrants be created as nonclustered by default:

`CONSTRAINT [PK_PersistedGrants] PRIMARY KEY NONCLUSTERED ([Key])`

**Comment by scottbrady91** [comment]
We're not doing anything specific for this dbcontext other than setting the key, an index on subject + client ID + type, and an index on expiration: https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Extensions/ModelBuilderExtensions.cs#L143

I'd be happy to take a look into any recommendations as long as they:
-  work across all EF Core supported relational databases (mainly SQL Server, MySQL, and PostgreSQL)
- doesn't introduce a breaking change

Any ideas?

**Comment by enikitin** [comment]
- PersistedGrantDb.sql is specific for Microsoft SQL Server and will not work with MySQL or PostgreSQL in any case.
- Changing a table index from clustered to non-clustered doesn't affect .NET clients . I made this change in our database and this did not cause any issues with IdentityServer4.

**Comment by scottbrady91** [comment]
Those SQL scripts are just example EF migrations (Brock uses them for testing), as opposed to something we support or maintain.

If there is a way to handle this at the DbContext level, I would be interested in supporting it.

**Comment by brockallen** [comment]
This is a provider specific setting. ForSqlServer you'd have to try something like this (EF Core 3.1 syntax):

```
    public class MyDbContext : PersistedGrantDbContext
    {
        public MyDbContext(DbContextOptions<PersistedGrantDbContext> options, OperationalStoreOptions storeOptions) : base(options, storeOptions)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<PersistedGrant>(b =>
            {
                var pk = b.Metadata.FindPrimaryKey();
                pk.SetIsClustered(false);
            });
        }
    }
```

and then:

```
.AddOperationalStore<MyDbContext>(options =>
{
    options.ConfigureDbContext = builder => builder.UseSqlServer(connectionString);
});
```

In pre-3.0 it's like this:

```
            modelBuilder.Entity<PersistedGrant>(b =>
            {
                var pk = b.Metadata.FindPrimaryKey();
                pk.SqlServer().IsClustered = false;
            });
```

This is the best work around we're aware of for you as of now.

**Comment by brockallen** [comment]
Did you try what I suggested? Someone else used it for a different PostGres feature and it worked for them, so I'll close for now.
