### ISSUE TITLE
Multiple eventSink support

### ISSUE THREAD

**Issue by jmolla31** [IdentityServer/IdentityServer4#3771]
**Is your feature request related to a problem? Please describe.**
At the moment, the default IEventService implementation provided by IdentityServer loads one IEventSink from the services collection. If you need to send an event to multiple sinks a main "distributor" sink or a custom IEventService are needed.

**Describe the solution you'd like**
Update the default IEventService implementation (or provide a secondary default implementation with multiple sink support) that raises the event for every implementation of IEventSink registered in the DI services collection.

**Comment by leastprivilege** [comment]
We are planning to re-write events for v4. No changes planned for the current implementation.

Please use that workaround for now

> If you need to send an event to multiple sinks a main "distributor" sink or a custom IEventService are needed.

**Comment by leastprivilege** [comment]
tracked here

https://github.com/IdentityServer/IdentityServer4/issues/3518
