### ISSUE TITLE
netcoreapp3.0 app got "Correlation failed" on iOS device.

### ISSUE THREAD

**Issue by Lukiya** [IdentityServer/IdentityServer4#3772]
### Describe the bug
On iOS device, "signin-oidc" encpoint seems cannot append correlationid cookie to iOS browsers.
**Desktop browser doesn't this issue!**

### To Reproduce
1. Build IdentityServer4 environment.
2. Use iPhone6/7/8 to access pages that need login.
2. After login, there will be a post request send to xxxxxxxxx.com/signin-oidc
3. Got errors:
- '".AspNetCore.Correlation.OpenIdConnect.xxxxxxxxxx"' cookie not found.
- System.Exception: Correlation failed.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Expected behavior
Should login success just like desktop browser.

### Screenshots
![image](https://user-images.githubusercontent.com/2961561/67601333-ef79cc00-f728-11e9-8d4d-0b34cdbec954.png)

### Additional context
WebServer: nginx
netcoreapp3.0
IdentityServer4 3.0.2
ForwardedHeaders_Enabled: true

**Comment by leastprivilege** [comment]
This error happens on the client, not IdentityServer. Check the Microsoft docs or issue tracker for this error.
