### ISSUE TITLE
Identity Server 4 runs as sub IIS application

### ISSUE THREAD

**Issue by GOVYANSONG** [IdentityServer/IdentityServer4#3773]
The solution worked great when deployed directly under IIS site root. Once it was converted to a sub application, it stopped working. From Windows Auth example, whenever Callback action of External controller is invoked, method HttpContext.AuthenticateAsync always returns result.Succeeded = False. This may not be identity server related. My current hunch is that HttpContext.SignInAsync with IdentityServer4.IdentityServerConstants.ExternalCookieAuthenticationScheme did not work properly for IIS sub application. My environment is: Asp.net core 2.0.9.

More info:
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint for /connect/authorize/callback
dbug: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint[0]
      Start authorize callback request
dbug: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[9]
      AuthenticationScheme: idsrv was not authenticated.
dbug: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint[0]
      No user present in authorize request
dbug: IdentityServer4.Validation.AuthorizeRequestValidator[0]
      Start authorize request protocol validation

info: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint[0]
      ValidatedAuthorizeRequest
      {
        "ClientId": "spa_fop_logistics",
        "ClientName": "FOP Logistics SPA",
        "RedirectUri": "https://xxxxxx/account/signinCallback",
        "AllowedRedirectUris": [
          "https://xxxxxx/account/signinCallback",
          "https://xxxxxx/account/silent-renew.html"
        ],
        "SubjectId": "anonymous",
        "ResponseType": "id_token token",
        "ResponseMode": "fragment",
        "GrantType": "implicit",
        "RequestedScopes": "openid profile api.access report.access",
        "State": "3c048241fac149649b2c806281078fa5",
        "Nonce": "0a1581966638469c9c858d1c4e5f8a14",
        "Raw": {
          "client_id": "spa_fop_logistics",
          "redirect_uri": "https://xxxxxx/account/signinCallback",
          "response_type": "id_token token",
          "scope": "openid profile api.access report.access",
          "state": "3c048241fac149649b2c806281078fa5",
          "nonce": "0a1581966638469c9c858d1c4e5f8a14"
        }
      }
trce: IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator[0]
      ProcessInteractionAsync
info: IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator[0]
      Showing login: User is not authenticated
trce: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint[0]
      End Authorize Request. Result type: IdentityServer4.Endpoints.Results.LoginPageResult
trce: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking result: IdentityServer4.Endpoints.Results.LoginPageResult
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HLQPI4SSKF2P" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]

Issuer: https://xxxxxx/idsrv4/auth
Public origin: https://xxxxxx/idsrv4. Path ‘auth’ is converted to IIS application and used to form proto endpoint urls in the discovery document.

The authentication flow stuck with endless loop of login, challenge, callback and Account/Login. I can confirm that Windows Auth succeeded for the Challenge in the log. The Windows Auth provider is NTLM as configured in IIS sub application. Is it because necessary cookie is not written correctly in this scenario e.g httpcookie.path and data protection with DPAPI and UserSession.GetUserAsync failed to find authenticated user? Or HttpContext.User is not set? Or peculiarity for NTLM? Or claim transformation is not activated automatically?
Any idea?

**Comment by leastprivilege** [comment]
Did you ever resolve that?

**Comment by GOVYANSONG** [comment]
Thanks for following up with this issue. Unfortunately, I got side tracked recently and did not get time to debug through the source code.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
