### ISSUE TITLE
IdentityServerTools IssueClientJwtAsync Audiences

### ISSUE THREAD

**Issue by erjicles** [IdentityServer/IdentityServer4#3774]
Context: Our IdentityServer instance makes server-to-server requests to other APIs that are also protected by IdentityServer. We use IdentityServerTools.IssueClientJwtAsync (http://docs.identityserver.io/en/latest/topics/tools.html) to create the access tokens used for these calls.

Question: When calling this function, we found that specifying the scopes doesn't automatically populate the audiences associated with those scopes - we need to pass them in manually. Is that intentional?

Also, we noticed that the IdentityServerTools.IssueClientJwtAsync function always adds the IdentityServer issuer uri as an audience to the token, no matter what:

https://github.com/IdentityServer/IdentityServer4/blob/f2cca2a73a886ebb7d9d6cdbf85deb0df08ca75c/src/IdentityServer4/src/Extensions/IdentityServerToolsExtensions.cs#L55

Why does it always add that audience? In all of our use cases, these access tokens are for audiences other than IdentityServer.

**Comment by leastprivilege** [comment]
> When calling this function, we found that specifying the scopes doesn't automatically populate the audiences associated with those scopes - we need to pass them in manually. Is that intentional?

Yes this is intentional. We let you issue whatever claims you like and don't even use the config system.

> we noticed that the IdentityServerTools.IssueClientJwtAsync function always adds the IdentityServer issuer uri as an audience to the token

That's actually a bug. Thanks for reporting.

**Comment by leastprivilege** [comment]
fixed.
