### ISSUE TITLE
/resources claim still present in IdentityServerTools

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3775]
Needs updating

https://github.com/IdentityServer/IdentityServer4/issues/3774

**Comment by rafanoronha** [comment]
seems like a pretty straight-forward fix, can I open a PR to address this?
no prior background with this ISTools class tough.
@leastprivilege do you want to drop the claim or maybe  emit it based on that recent flag? not sure if the flag/options do make sense there

**Comment by leastprivilege** [comment]
Oh - didn't see this. I already fixed it.

Thanks!
