### ISSUE TITLE
Does Identity server support multiple login in same session 

### ISSUE THREAD

**Issue by rambabukarnati** [IdentityServer/IdentityServer4#3776]
Hi,
We have a scenario where Identity server should authenticate the user in couple of other places even it verified at the time of my application login. 
workflow 
1. User access my application and it will redirect to Identity server to authenticate user. User will authenticate with Identity server and return to my home page 

2. We have a module to change logical control of my application, When a user trying to modify them our application should required to authenticate the user again. In other word user has to enter username and password one more time to perform this action 

Can someone help me to understand how we can implement my 2nd scenario ?

**Comment by leastprivilege** [comment]
You can pass a `prompt=login` parameter to re-trigger authentication. The `auth_time` claim tells you how "old" the session is.
