### ISSUE TITLE
idsvrtest.pfx  Certificate is about to expire （Expiry date: January 21, 2020）

### ISSUE THREAD

**Issue by dengyangxi** [IdentityServer/IdentityServer4#3777]
Does the default certificate of identityserver4 have any exception after expiration ? 
How should I sign my own certificate? To adapt to identity server 4 ？ 
idsvrtest.pfx （Expiry date: January 21, 2020）

**Comment by dengyangxi** [comment]
@leastprivilege   @brockallen      Please help me out, thank you ！~

**Comment by brockallen** [comment]
The expiration of the signing certificate for IS does not matter. Also, you should not be using the signing certificate that comes with our samples.

**Comment by dengyangxi** [comment]
https://www.identityserver.com/documentation/keymanagement/ 

 thank you !~
