### ISSUE TITLE
IdentityServer demo site as external authentication provider.

### ISSUE THREAD

**Issue by libypur2k19** [IdentityServer/IdentityServer4#3778]
Hi.

I've followed the steps to add identityserver demo site  as an external authentication provider as decribed in: https://identityserver4.readthedocs.io/en/latest/quickstarts/2_interactive_aspnetcore.html

If I run the mvc client, "Demo IdentityServer" appears as an additional external provider on the login page, that's ok, but clicking on it, the button's text switchs to "Sign-in with Azure AD" and, again, if i click this, it redirects me to:

https://login.microsoftonline.com/common/oauth2/authorize?client_id=https%3A%2F%2Fleastprivilegelabs.onmicrosoft.com%2F38196330-e766-4051-ad10-14596c7e97d3&redirect_uri=https%3A%2F%2Fdemo.identityserver.io%2Fsignin-aad&response_type=id_token&scope=openid%20profile&response_mode=form_post&nonce=637080306861607418.NGQ4YTlhYzEtZmU1Ni00ZmQ0LTlkYTktNGQ4YWJlMzU5YzAyYWNhYjJjMDAtMTcwMC00NzdmLTkzOGEtYjM4NWM5OTdlMmFj&state=CfDJ8M89_M2FPhRKoQ5g2ZUV45_Ys8qb_3Qi6ww_p36_TFXLSOYytbkmmeCq13hBbPAy2KQdBh46QI288KmPj-dZZjDaKjuWT6hoPT7Gl2ra6BQuc-4iY08H8E47ORdvG7-ocZiah40K4UysLqX242ptT-Any0sLe0UK9Fj1wGt2EVJg&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0

to enter an email address and a password, but I don't know what to enter.

I've going through
https://github.com/IdentityServer/IdentityServer4.DemoSite/blob/master/src/IdentityServer4Demo/Config.cs
to see the available identityserver demo site client's list, and tried with others rather than "native.code", as stated in the quickstart code:

                .AddOpenIdConnect("oidc", "Demo IdentityServer", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                    options.SaveTokens = true;

                    options.Authority = "https://demo.identityserver.io/";
                    options.ClientId = "native.code";
                    options.ClientSecret = "secret";
                    options.ResponseType = "code";

                    options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role"
                    };
                });

, but none of them works. 

So, please, What do I need to do in order to authenticate successfully against IdentityServer demo site?

Thank you!

**Comment by leastprivilege** [comment]
You can't do that because you don't have an AAD account in our system. You can use Google instead.

**Comment by libypur2k19** [comment]
Can you add a test AAD account on your system, so people like me, following quickstart #2 can test your identityserver demo site as an external authentication provider?

Than you!

**Comment by leastprivilege** [comment]
An AAD account is not needed to finish the quickstarts. But it's a good idea. Will add that when I find time.
