### ISSUE TITLE
Should the LoggedOutViewModel be updated?

### ISSUE THREAD

**Issue by Simply-Awesome** [IdentityServer/IdentityServer4#378]
The IdentityServer4.Quickstart.UI.Models.LoggedOutViewModel class is used in IdentityServer4.Quickstart.UI.Controllers.AccountController.

It has a property called ClientName and the only time this property is used is when a ClientId is assigned to it when a User logs out.

Would it be possible for the class to have BOTH a ClientName and a ClientId property? 

I ask because I prefer returning the ClientName (of the Client Class) in the view instead of the ClientId.

**Comment by brockallen** [comment]
This is what `LoggedOutViewModel` has: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/Host/Models/LoggedOutViewModel.cs

**Comment by Simply-Awesome** [comment]
Indeed.

If possible, I think it would be better if `LoggedOutViewModel` also has the property:
      
      public string ClientId { get; set; }

And in the POST Logout method of the Account Controller, you have:

     var logout = await _interaction.GetLogoutContextAsync(model.LogoutId);
     var vm = new LoggedOutViewModel
     {
        PostLogoutRedirectUri = logout?.PostLogoutRedirectUri,
        ClientName = logout?.ClientName,
        ClientId = logout?.ClientId,
        SignOutIframeUrl = logout?.SignOutIFrameUrl
     };
     return View("LoggedOut", vm);

Instead of:

     var logout = await _interaction.GetLogoutContextAsync(model.LogoutId);
     var vm = new LoggedOutViewModel
     {
        PostLogoutRedirectUri = logout?.PostLogoutRedirectUri,
        ClientName = logout?.ClientId,          
        SignOutIframeUrl = logout?.SignOutIFrameUrl
     };
     return View("LoggedOut", vm);


Where ClientId is referred to as ClientName (somewhat incorrectly).

**Comment by brockallen** [comment]
If you want the client name, use the client store to look it up. This is just the sample UI code.

**Comment by Simply-Awesome** [comment]
okie dokie,  ty
