### ISSUE TITLE
Quickstart #6 - JavaScript Client

### ISSUE THREAD

**Issue by libypur2k19** [IdentityServer/IdentityServer4#3781]
Hi!

I've followed steps on quickstart #6 to add a JavaScript client.

I run the JavaScript client app. I click on Login button and it redirects me to IdentityServer UI login page. I try login as user:alice, password:alice, but in return I get the following exception:

**InvalidOperationException: Endpoint IdentityServer.ConsentController.Index (IdentityServer) contains authorization metadata, but a middleware was not found that supports authorization. Configure your application startup by adding app.UseAuthorization() inside the call to Configure(..) in the application startup code.**

Here you have the resulting log file:
[identityserver4_log.txt](https://github.com/IdentityServer/IdentityServer4/files/3794155/identityserver4_log.txt)

NOTE: All projects on the solution target .NET Core 3.0

Please, help!
Thank you!

**Comment by tai-yi** [comment]
@libypur2k19 
Add middleware `app.UseAuthorization();` in `Startup` method `public void Configure(IApplicationBuilder app)`.

**Comment by leastprivilege** [comment]
Thanks - not all quickstarts have been updated to ASP.NET Core  3 yet. We will work on it ASAP.
