### ISSUE TITLE
Controlling session cookie lifetime at runtime

### ISSUE THREAD

**Issue by snothub** [IdentityServer/IdentityServer4#3782]
Is it possible to have a more dynamic session cookie lifetime? We have different user groups all using IdSrv to log into various applications (clients) and would like to have different session lifetime per user group. So, to be clear, not per client id, but another, custom logical entity in our application ecosystem.

**Comment by leastprivilege** [comment]
You are in control of the cookie lifetime on the login page.

**Comment by snothub** [comment]
> You are in control of the cookie lifetime on the login page.

Meaning I can set it at login by implementing own cookie handler? Cause v3 would only allow to set it at startup, thats why I'm asking.

**Comment by leastprivilege** [comment]
You can set it when calling `SignInAsync` - we are using the standard ASP.NET Core APIs.
