### ISSUE TITLE
Suggestion: Utilize ReadTheDocs SSL Cert

### ISSUE THREAD

**Issue by SeanKilleen** [IdentityServer/IdentityServer4#3783]
I came across this idea while updating some `http` --> `https` links in the `dotnet/docs` repo.

I noticed that the `https` version of the docs appeared to have a cert error.

I believe ReadTheDocs allows for a custom SSL cert courtesy of CloudFlare that you can configure: https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-ssl

Wanted to leave this here in case you find it useful; feel free to close if you have no plans to utilize it. 👍

**Comment by leastprivilege** [comment]
Yes - it's on my todo list...thanks!
