### ISSUE TITLE
Why ApiScope's name field is unique?

### ISSUE THREAD

**Issue by fabercs** [IdentityServer/IdentityServer4#3785]
Well for my authorization server I have started building a simple admin backend , while inserting ApiResource's scopes, I saw that name field of ApiScope table is unique. Shouldn't it be unique with `ApiResourceId ` together (a composite)? Becasue another `ApiResource `might have exactly the same scope name.

**Comment by leastprivilege** [comment]
Scope names must be unique. We didn't want to enforce any composite naming format, so you need to do that yourself, e.g.

`resourceName.ScopeName`
