### ISSUE TITLE
No id_token returned by token endpoint for custom grant.

### ISSUE THREAD

**Issue by voroninp** [IdentityServer/IdentityServer4#3788]
# Issue / Steps to reproduce the problem
I was trying to reproduce the problem discussed in this [PR](https://github.com/IdentityServer/IdentityServer4/pull/3713), but got another issue.
When I make a request to token endpoint with `my` grant and `openid offline_access` scope I do not get `id_token`. However on refreshing access token id_token is returned. Why?

Here is the repo, reproducing the issue:

https://github.com/voroninp/Is4NoIdTokenOnFirstRequest

**Comment by leastprivilege** [comment]
Extension grants are an OAuth concept. So no id_token. You can ask for identity scopes (like openid) and then use the userinfo endpoint to get the claims.

The fact that the id_token gets returned from a refresh token - is a bug IIRC.

**Comment by voroninp** [comment]
But how then do I issue only an id_token without access token as a result of custom flow?

**Comment by leastprivilege** [comment]
You don't. As I said extension grants are an OAuth feature. OAuth does not have id_tokens.

**Comment by voroninp** [comment]
So when some API needs to authenticate user with id_token, then application first should exchange access token containing `openid` scope for id_token and then pass it to API, right?

**Comment by leastprivilege** [comment]
An API does not authenticate users with id_tokens - an API consumes access tokens.

**Comment by voroninp** [comment]
Then which entity uses id_token?

**Comment by leastprivilege** [comment]
The id_token is for the client.

You need to (re-)read the specs or do some training on how the protocols work. It'll all make sense then.

Here is the wrong place for that.

**Comment by voroninp** [comment]
arghhh... terms. Exactly how you described it.

So we have an SPA which has access to its back-end. Back-end is the client of internal APIs.
SPA -> id_token -> back-end
back_end -> access token -> api

**Comment by leastprivilege** [comment]
OK - I will close this issue.
