### ISSUE TITLE
Consider "ConsentCookie" ?

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#379]
In the default UI - similar to 2FA "Trust this browser"

**Comment by brockallen** [comment]
I think the best/easiest place to implement this would be as a custom `IPersistedGrantService` with `StoreUserConsentAsync` and `GetUserConsentAsync` checking the DB as well as a cookie.

**Comment by brockallen** [comment]
Yes, it's now possible.
