### ISSUE TITLE
Quickstart instructions for ASP.NET Core 2.x needs to reference "v2" templates

### ISSUE THREAD

**Issue by jeremy-jameson** [IdentityServer/IdentityServer4#3795]
### Issue / Steps to reproduce the problem

Attempting to follow the current quickstart documentation for **ASP.NET Core 2** results in numerous problems due to the upgrade of IdentityServer to ASP.NET Core 3.0. The documentation should be updated to instruct the reader to install the current "v2" version of the IdentityServer templates (i.e. 2.6.1).

### Relevant parts of the log file

N/A

**Comment by leastprivilege** [comment]
merged.
