### ISSUE TITLE
CORS issue when authenicating user 

### ISSUE THREAD

**Issue by scossgrove** [IdentityServer/IdentityServer4#3797]
I have implement the Identity Service with the "Quick Start". I can start the service up fine and navigate to the Login page. I can enter username and password and it will authenticate but after the process redirects it comes back to the login screen.

I think it has something to do with the CORS but cannot get it to pass no matter what I have done.

I've tried
app.UseCors(builder =>
           {
               builder.AllowAnyOrigin()
                       .AllowAnyMethod()
                       .AllowAnyHeader();
           });

but nothing seems to work.

Can you help?

[identityserver4_log.txt](https://github.com/IdentityServer/IdentityServer4/files/3812011/identityserver4_log.txt)

**Comment by leastprivilege** [comment]
We only support the latest version of IdentityServer - either upgrade to the highest 2 or 3 version.

If you are doing your login interactively then CORS is not involved. The log entry is a red herring.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
