### ISSUE TITLE
Please add JavaScript client sample in QuickStart

### ISSUE THREAD

**Issue by khrezaei** [IdentityServer/IdentityServer4#3799]

**Comment by Luis-Palacios** [comment]
It seems they are working hard on updating the quickstarts guides to support Dotnet Core 3.0 see #3781 so we should have it soon.

My question would be: Are we just missing and updated sample for a javascript client? or right now there is no way to create a javascript client?

**Comment by Luis-Palacios** [comment]
It looks like we can, I have used the is4aspid template and it already has a configuration for a SPA Client, I'm also looking at the client samples here: https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Clients/src but I'm seeing two for javascript `JsOAuth2` and `JsOidc` I'm wondering if I can use any or just one with the is4aspid  template

**Comment by khrezaei** [comment]
I used is4aspid, It has SPA client. but the problem is that it wont authenticate the user and also wont redirect to the client.

**Comment by leastprivilege** [comment]
Nothing has changed functionality-wise from 2 to 3. It all works - and you can go back to the 2.x branch if you want to have a look at the older quickstarts.

Besides that, this is issue is already tracked as mentioned above - so I will close this one.

**Comment by wswind** [comment]
JsOidc uses oidc-client.js. You can use it to login with redirect like the old  JavaScript client sample. If you don't use the redirect way. Just request token like the JsOAuth2 sample.

> It looks like we can, I have used the is4aspid template and it already has a configuration for a SPA Client, I'm also looking at the client samples here: https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Clients/src but I'm seeing two for javascript `JsOAuth2` and `JsOidc` I'm wondering if I can use any or just one with the is4aspid template

**Comment by khrezaei** [comment]
Hi,
thanks a lot.
