### ISSUE TITLE
Intrspection - Secret validation is failing 

### ISSUE THREAD

**Issue by cqxiaoxie** [IdentityServer/IdentityServer4#3801]
version:IdentityServer4 2.4  IdentityModel 3.10.7 IdentityServer4.AccessTokenValidation 2.7.0
error:IsActive = 'response.IsActive' threw an exception of type 'System.InvalidOperationException'
(https://user-images.githubusercontent.com/13866292/68379571-156f8980-0189-11ea-8069-838098866150.png)

(https://user-images.githubusercontent.com/13866292/68379396-bad62d80-0188-11ea-9240-43054c5e0f67.png)

**Comment by leastprivilege** [comment]
Not enough information.

Read the docs about introspection/reference tokens first.

**Comment by cqxiaoxie** [comment]
> Not enough information.
> 
> Read the docs about introspection/reference tokens first.
I don't know what went wrong?
(https://user-images.githubusercontent.com/13866292/68455313-072b7700-0236-11ea-8dae-915b78d98364.png)

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
