### ISSUE TITLE
Previous version quickstart docs now out of date

### ISSUE THREAD

**Issue by codemonkey33** [IdentityServer/IdentityServer4#3802]
Hi. I've spent a couple of days getting to grips with Identity Server 4 and firstly, thanks.

Anyway......
I unfortunately am not in a position to use Dotnet Core 3 and am stuck with 2.2 (Jenkins, Openshift updates etc)

on this page (and the one after) http://docs.identityserver.io/en/aspnetcore2/quickstarts/0_overview.html

it tells you nicely how to get the templates installed, however this command will always install the latest version from Nuget no matter what SDK you are using.

dotnet new -i IdentityServer4.Templates

So I wasted (learning opportunity for me) a few hours fighting the new version, reverting things to work in core 2.2 before I worked out the error of my ways

if you are stuck in an older version (and I'm reading the docs for that version) then you need to control the template version you use:

dotnet new -i IdentityServer4.Templates::2.7.0

hope that helps somebody

**Comment by leastprivilege** [comment]
Docs have been updated. Thanks.
