### ISSUE TITLE
6_JavaScriptClient has been moved to deprecated folder. My code is not working. Need help.

### ISSUE THREAD

**Issue by ajitanil** [IdentityServer/IdentityServer4#3803]
I am trying to use JS client along with Identiyserve4.
I was trying to find out a sample code for this approach.
But found out the folder in the 'Deprecated' folder.
Still I used it and was getting error on the 'Callback.html' - Error - OidcClient.processSigninResponse: No matching state found in storage.
Tried checking on stackoverflow, but did not get any resolution.

Need a working sample code for reference to test the javascript client. Can you please help.

**Comment by leastprivilege** [comment]
Opening an issue in the JS lib would be more suitable.

https://github.com/IdentityModel/oidc-client-js
