### ISSUE TITLE
IdentityServer4.AccessTokenValidation for .netstandard?

### ISSUE THREAD

**Issue by leo9223** [IdentityServer/IdentityServer4#3804]
I was using IdentityServer4.AccessTokenValidation in .net standard 2.0

Then I just wanted to update my project .net standard 2.0 to 3.0 and the new version (IdentityServer4.AccessTokenValidation - 3.0.1) is no more targeting .net standard :(

What to do now?

**Comment by leastprivilege** [comment]
I don't follow - there is no netstandard 3.0.

The latest version of the access token handler targets ASP.NET Core 3 - which is netcore3 only.

If you need to support older versions - then use an older version of the access token handler.
