### ISSUE TITLE
Purpose of the "Enabled" property on the Client, Resource objects

### ISSUE THREAD

**Issue by nholik** [IdentityServer/IdentityServer4#3806]
I've noticed that several object have an "Enabled" property, for example the client and was wondering what the purpose or convention is surrounding it.  My assumption would be anything with a false enabled property should be ignored. [see here](https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/Storage/src/Models/Client.cs#L29) and [here](https://github.com/IdentityServer/IdentityServer4/blob/19264a3847e8547371d1f4b9909d9be8892bf969/src/EntityFramework.Storage/src/Entities/Client.cs#L16)

However, the EF store does not filter these out if this is the intended behaviour - [see](https://github.com/IdentityServer/IdentityServer4/blob/19264a3847e8547371d1f4b9909d9be8892bf969/src/EntityFramework.Storage/src/Stores/ClientStore.cs#L54)

Would it make sense to filter out based on enabled being false, or is there perhaps a different rationale behind this?

**Comment by leastprivilege** [comment]
We check the flag internally before we use the client/resource.

If we filter out a) we couldn't log the fact that someone is trying to use a disabled resource (don't know if we are doing that) - or use the EF store to show disabled clients (in some sort of admin/diag UI)

**Comment by nholik** [comment]
Got it makes perfect sense, and it does look like you are in fact logging
