### ISSUE TITLE
not find tempkey.rsa 

### ISSUE THREAD

**Issue by tttttvf** [IdentityServer/IdentityServer4#3810]
In asp.net core 3.0, the launch application did not generate the temp.rsa file, resulting in the jwt token not being generated properly. The document does not describe whether additional configuration is required.

**Comment by tttttvf** [comment]
The program prompts me: No signing credential is configured. Can't create JWT token

**Comment by leastprivilege** [comment]
Check out our templates or other samples. They show you how it works.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
