### ISSUE TITLE
Using  IdentityServer4.EntityFramework in netcore3

### ISSUE THREAD

**Issue by wayne-o** [IdentityServer/IdentityServer4#3813]
**We can only help you if you are on the latest version. Either use the latest 2.x or 3.x**

I am using latest 3.x

### Issue / Steps to reproduce the problem

I am trying to build my Ids inside a docker container :

FROM microsoft/dotnet:3.0-aspnetcore-runtime AS base
FROM microsoft/dotnet:3.0-sdk AS build

This seems to work when i run dotnet build on the host machine

The outout of the docker build is:

```error NU1202: Package IdentityServer4.EntityFramework.Storage 3.0.2 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package IdentityServer4.EntityFramework.Storage 3.0.2 supports: netstandard2.1 (.NETStandard,Version=v2.1)```

**Comment by leastprivilege** [comment]
That's a weird error, because netcore3 is compatible with netstandard. That's a question for Microsoft.

https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by wayne-o** [comment]
I was not using the correct paths for the base images - i.e. mcr.microsoft.com/dotnet/core/runtime:3.0

fixed :)
