### ISSUE TITLE
Unable to use Windows Auth on a Single Page App due to Antiforgery token being incorrect

### ISSUE THREAD

**Issue by jocco** [IdentityServer/IdentityServer4#3815]
### Issue 
I am trying to use the `Microsoft.AspNetCore.ApiAuthorization.IdentityServer` sample of creating a SPA together with IdentityServer, running against a oidc source works great but when attempting to use Windows Auth I get a 400 error, which turns out to be because a `AntiforgeryValidationException` is thrown with the error message `The provided antiforgery token was meant for a different claims-based user than the current user.`

I have been trying to find a way to disable the antiforgery validation to see if this would work in that case but have been unable to find a way around it (and I assume that should really be enabled).
I am running IIS Express as my own user so it should have access to verify my login.

I hope that I correctly identified this as an issue with IdentityServer (as the login page is just the quickstart ui pages running) and not a issue that belong with `ApiAuthorization`, if I was wrong I apologize.

### Repro
* Use `dotnet new react -o <output_directory_name> -au Individual` to create a react SPA application. See https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.0
* Enable Windows Auth
```            
services.Configure<IISServerOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });```
```
* Enable windows auth in IIS Express
* Debug site,  stopping on all exceptions. try to login using windows auth. Note the exception.
 
### Relevant parts of the log file

```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 POST https://localhost:44385/Identity/Account/ExternalLogin?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DHimalia2%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%253A44385%252Fauthentication%252Flogin-callback%26response_type%3Dcode%26scope%3DHimalia2API%2520openid%2520profile%26state%3D2e07cf0192664d70b1a915e7d1881484%26code_challenge%3DFG2cbwTwPd3vDZV_nPxjSiMUe26-dcSQV4wZRtW2Yu4%26code_challenge_method%3DS256%26response_mode%3Dquery application/x-www-form-urlencoded 199
Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware: Information: No CORS policy found for the specified request.
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint '/Account/ExternalLogin'
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Route matched with {page = "/Account/ExternalLogin", area = "Identity", action = "", controller = ""}. Executing page /Account/ExternalLogin
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executing handler method Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal.ExternalLoginModel.OnPost - ModelState is Invalid
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executed handler method OnPost, returned result Microsoft.AspNetCore.Mvc.ChallengeResult.
Microsoft.AspNetCore.Mvc.ChallengeResult: Information: Executing ChallengeResult with authentication schemes (Windows).
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executed page /Account/ExternalLogin in 69.03540000000001ms
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/Account/ExternalLogin'
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request finished in 129.8761ms 401 
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/1.1 POST https://localhost:44385/Identity/Account/ExternalLogin?returnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DHimalia2%26redirect_uri%3Dhttps%253A%252F%252Flocalhost%253A44385%252Fauthentication%252Flogin-callback%26response_type%3Dcode%26scope%3DHimalia2API%2520openid%2520profile%26state%3D2e07cf0192664d70b1a915e7d1881484%26code_challenge%3DFG2cbwTwPd3vDZV_nPxjSiMUe26-dcSQV4wZRtW2Yu4%26code_challenge_method%3DS256%26response_mode%3Dquery application/x-www-form-urlencoded 199
Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware: Information: No CORS policy found for the specified request.
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint '/Account/ExternalLogin'
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Route matched with {page = "/Account/ExternalLogin", area = "Identity", action = "", controller = ""}. Executing page /Account/ExternalLogin
Exception thrown: 'Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException' in Microsoft.AspNetCore.Antiforgery.dll
The provided antiforgery token was meant for a different claims-based user than the current user.

```

**Comment by leastprivilege** [comment]
That's a question for Microsoft. @javiercn

**Comment by blowdart** [comment]
And best asked on the [aspnetcore repo](https://github.com/aspnet/AspNetCore/issues).

Basically Windows Auth is special, annoyingly so. Trying to treat it like any other auth type doesn't work. Adding in a SPA app to this makes it worse. If you want Windows Auth in a SPA then don't use the Identity Server templates, the SPA needs to be dedicated to just Windows auth.

**Comment by leastprivilege** [comment]
This is only partially true - our default UI for IdentityServer has some additional code to make Windows authN behave like any other external authN mechanism

https://github.com/IdentityServer/IdentityServer4/issues/3819

and

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/host/Quickstart/Account/ExternalController.cs#L148-L193

Maybe thr ASP.NET Identity UI needs something comparable.

**Comment by leastprivilege** [comment]
Closing because this is about the MS integration. Use our raw APIs to get the full feature set.
