### ISSUE TITLE
Create corresponding interfaces for SecretParser and SecretValidator classes to make them easier to re-implement

### ISSUE THREAD

**Issue by ntavendale** [IdentityServer/IdentityServer4#3818]
**Is your feature request related to a problem? Please describe.**
I needed to re-implement the SecretParser class to account for the possibility of two distinct secrets being presented. The browser will send the bearer auth and also the basic auth creds if it still has them cached. The OAuth Spec does not explicitly proscribe this situation.

To do this I needed to roll my own secret parser class, MyCustomSecretParser, as the SecretParser class in IdentityServer4 is not implementing an interface, it is simply a class (same with the SecretValidator class).

Once  I rolled my own class however the I could no longer use the ClientSecretValidator class as the constructor parameters were classes, not interfaces. So I then had to roll my own version of that as well.

**Describe the solution you'd like**
I would like SecretParser & SecretValidator classes to be implementations of interfaces, and change the constructor of the ClientSecretValidator class to reflect this. That way I can still use the original ClientSecretValidator class and the re-implementation of the SecretParser class is greatly simplified.

**Describe alternatives you've considered**
Rolling my own set of classes, bu this means that any changes in IdentityServer4 may break the code that uses it.

**Additional context**
I have actually done this work in a fork and tested it out. My solution works with my project and all the unit tests work as well.  I can put up a Pull Request if anyone waishes.

**Comment by leastprivilege** [comment]
yes - please send a PR so we have some code to look at. thanks!

**Comment by ntavendale** [comment]
Have created pull request:
https://github.com/IdentityServer/IdentityServer4/pull/3824

I won't claim it's an elegant, or even very good, piece of code but it illustrates what I am getting at with this feature request.

**Comment by brockallen** [comment]
The spec does say: "The client MUST NOT use more than one authentication method in each request."

https://tools.ietf.org/html/rfc6749#section-2.3

**Comment by brockallen** [comment]
> The browser will send the bearer auth and also the basic auth creds if it still has them cached.

Does this mean you've changed the CORS processing for the token endpoint to allow credentials?
