### ISSUE TITLE
Can the length of token be set a little shorter?

### ISSUE THREAD

**Issue by cqpaul** [IdentityServer/IdentityServer4#3820]
Can see the token's length is too long, I need to use it in the URL, to reuse the token in the other site.
![image](https://user-images.githubusercontent.com/1913951/68755063-e8b4e980-0642-11ea-8a8a-5982e2cfc4b5.png)

**Comment by leastprivilege** [comment]
Use a tool like https://jwt.ms to see what's inside.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
