### ISSUE TITLE
Consider adding more context to outgoing HTTP calls

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3825]
As part of 

https://github.com/IdentityServer/IdentityServer4/issues/3518

https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/

```csharp
private async Task<string> GetWeatherForecast()
{
    var activity = new Activity("CallToBackend")
        .AddBaggage("appVersion", "v1.0")
        .Start();

    try
    {
        return await _httpClient.GetStringAsync(
                                         "http://localhost:5000/weatherforecastproxy");
    }
    finally
    {
        activity.Stop();
    }
}
```

**Comment by veikkoeeva** [comment]
Maybe of interest also, [HTTP Server-Timing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server-Timing) (also via [Mozilla DevTools Twitter](https://twitter.com/FirefoxDevTools/status/1201914691863244800)).
