### ISSUE TITLE
Samples not working

### ISSUE THREAD

**Issue by Alik2015** [IdentityServer/IdentityServer4#3827]
I must be missing something very simple but I pulled the project fresh from git and opened in vs 2019.  I set up startup to run Identityserver project followed by api fullowed by mvc project without changing any other settings.

It seems to get stuck here:
http://localhost:5000/connect/authorize?client_id=mvc&redirect_uri=http%3A%2F%2Flocalhost%3A5002%2Fsignin-oidc&response_type=code&scope=openid%20profile%20api1%20offline_access&code_challenge=K0iGfhQJOd_wWeUz79Brf4AYW9_r8cpiF6dqcc7q3eQ&code_challenge_method=S256&response_mode=form_post&nonce=637096827373579828.ZTBhMzNjOWUtNTFhMC00NTE2LTk2OTItODA1NWFlOGI3YTA3YWJhZWM1YWUtYjMzNi00ZGYyLWJmN2EtODAyYjVhNzhjYzA3&state=CfDJ8F8F_CrHwnFOkz4ygPVptdBV5EB7t1l27pbUsMjYfGSsZ6C7PY4cTKvxs13JHe2dV2-IkjLlwUCvRpuBJteCcdhX-3YU0rRoYDNAlj7JKqkIOeb7RSSdhXX5p7RxqnwGgLJV4bzwHCdj-9-jpPV7v3eI5Eefrkc7n3Lk0iUvqJIYYTRCia6BClUsQ2wkGWtNj1FFBIOjExOWS9GQ5rvVoKy2pj73QRE3c79Fwsy-RSSXeU5_CBCvV1x6s6ISXpJYyivn6DrCx3p81C26Mch-AbuQhaZcjPBtTL31I2B4JYDCPHPZf_j7MnaBt6vBEF7mo2cM7lwzB8orivzWb_9zDG58fQpHv-D8PzChR5BdPD4RXhVn4pg6EwzONcCOXPp3Iw&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0
Without any errors in the logging.

FYI the console client project works fine.

**Comment by leastprivilege** [comment]
Make sure everything is on the right port.

**Comment by Alik2015** [comment]
Definitely on the right ports like I said client app is working.  Just MVC client is failing.  Using the sample project no changes.
