### ISSUE TITLE
Invalid grant type for client implicit issue - Identity Server 4

### ISSUE THREAD

**Issue by Venkatroyal** [IdentityServer/IdentityServer4#3828]
I am getting an error during refresh token process (while invoking /connect/authorize endpoint) in identity server. Find below the error message from identity server log.
**"Invalid grant type for client : implicit"**
This happens after 8 to 9 hours of successful running. Following are the configuration details at client & server side.
Client side : oidc-client is being used.

automaticSilentRenew - true
response_type         - code id_token token
scope                - openid email profile role offline_access 

Server Side :  

AllowedGrantTypes      - Hybrid
AllowedScopes        - OpenId,Email,Profile,Role
AllowOfflineAccess   - true
AccessTokenType      - AccessTokenType.Jwt

Please provide your suggestions/feedback to resolve this issue.

**Comment by brockallen** [comment]
> This happens after 8 to 9 hours of successful running.

Do you mean you get this error during a silent renew?

**Comment by Venkatroyal** [comment]
Yes. It refreshes the token every 1 hour(which is accesstokenlifetime i had set) properly for 8 to 9 hours and then this exception is thrown in identity server logs. Let me know if you need any other configuration details to track the issue.

**Comment by brockallen** [comment]
Is it possible that you're getting an error because the cookie at IS has expired?

**Comment by Venkatroyal** [comment]
Yes. I did some research,found that Cookie/Authentication Ticket expiry will be the issue and added the following code.

            .AddAuthentication(opts =>
            {
                opts.DefaultAuthenticateScheme = "Cookies";
            })
            .AddSaml(Configuration, externalProviders.UseSaml)
            .AddCookie("Cookies",options =>
            {
                options.SlidingExpiration = true;
                options.ExpireTimeSpan = System.TimeSpan.FromDays(30);
            });
			
Now that the error is not being thrown but the following activities are happening.

1) Some of the API's(under same client in identity server) are throwing the 401 Unauthorized error (token expired) while few of them are working
2) connect/authorize endpoint invoked twice 
3) While analysing the 401 Unauthorized error, in some requests the tokens are valid (meaning that good valid expiration time) but still the 401 Unauthorized error is thrown.

Please let me know your suggestions/feedback in this regard.

**Comment by brockallen** [comment]
I think you will need more logging to help you understand what's happening.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
