### ISSUE TITLE
Is there any way to customize the Windows Authentication UI?

### ISSUE THREAD

**Issue by EdLichtman** [IdentityServer/IdentityServer4#3829]
There is a Windows Authentication Dialog controlled by the browser (i.e. IE, Chrome, Firefox, etc) when you disallow Automatic Authentication. I understand if for security purposes Windows Auth is handled separately so we as developers cannot hijack the request and store users Usernames and Passwords, but from a purely aesthetic point, we really don't like the looks of the Windows Auth prompt since it doesn't really match our "brand". 

Someone alluded to the same question in another question that was asked: https://github.com/IdentityServer/IdentityServer4/issues/1374. Not sure if what they were looking for is what I was looking for since they didn't really specify any further, but the guy at the end asked exactly the question I'm looking for: 

We would like to:  is possible to do the following:

1) Create custom html form page with a username field and password field.
2) User keys in his/her windows domain account and password into those field and click submit button.
3) In the backend, somehow use those inputs from user and do windows authentication to verify the login.
4) Return access token if successfully authenticated.

That way we don't have to rely on the following UI in order to Authenticate UI and we don't have to allow "Automatic Authentication":
![image](https://user-images.githubusercontent.com/13857969/69067771-4ce00080-09e9-11ea-9bd4-b1315c63d7ef.png)

p.s. I included the issue number because it looks like the guy never got his answer. I'm a bit new to using github actively, but if we could link him to this answer, I figured that would be nice.

**Comment by leastprivilege** [comment]
You can't modify this UI. Also - this UI only shows up as a fallback if integrated Windows authentication is not working properly in your domain. Maybe that's what you would need to investigate.
