### ISSUE TITLE
Auto-Login after Registration

### ISSUE THREAD

**Issue by rsnj** [IdentityServer/IdentityServer4#383]
Is there a programmatic way for my API to get a login token on behalf of a user?

**My use case is this:**
My registration is an Angular2 SPA application that calls an API
After the user completes the registration I want to sign them in automatically
My application requires Two-Factor Authentication, but this would be bypassed after registration

Since my API has the user's information, is there anyway I can retrieve a token and pass it with the registration response?

Looking at issue #51 I considered using the Resource Owner Flow to have my Angular2 SPA request a token that way. But this would violate my Two-Factor Authentication requirement. Is there a way to support MFA with the Resource Owner Flow?

**Comment by brockallen** [comment]
Sounds like you need a token to submit to the UI of IdentityServer to accept the user as being logged in. You can always pass a custom `acr_values` or any custom QS params and IdentityServer will pass those to the login page in the `returnUrl`. You'd then just trust that param instead on the login page and not prompt the user.
