### ISSUE TITLE
Build Process - Test Result output

### ISSUE THREAD

**Issue by enterprisebug** [IdentityServer/IdentityServer4#3831]
How do you collect Test results in your azure-pipelines.yml?

https://github.com/IdentityServer/IdentityServer4/blob/767438b7a4caf84bf97c5e6a9ed13a6da4cba90a/azure-pipelines.yml#L34

When the build is running it does some tests, but no test result is written that can be picked up for evaluation.

https://github.com/IdentityServer/IdentityServer4/blob/767438b7a4caf84bf97c5e6a9ed13a6da4cba90a/src/Storage/build/Program.cs#L49

Just curious: Are you not interested in the test result output?

i was expecting something like `dotnet test --logger ...`

**Comment by leastprivilege** [comment]
I see the error output - that's all I care about..

**Comment by enterprisebug** [comment]
Got it. Thx.
