### ISSUE TITLE
Question about Identity Server + API Management + Service Fabric

### ISSUE THREAD

**Issue by alancorreas** [IdentityServer/IdentityServer4#3832]
Hi,

I'm not sure about what would be the best approach for my problem.

I have 3 applications:
- An Identity Server 4 instance
- An API protected by bearer tokens issued by my IS4
- A worker that uses IS4 to generate a token and then consumes the API (first bullet)

All 3 applications are hosted on containers inside a Service Fabric Cluster distributed in various nodes accessed through a load balancer.

The Identity Server application and the resource API are exposed to the world through a API Management Gateway (in this case Sensedia).

(Internet -> APIM -> Load Balancer -> Nodes)

The thing is that I don't want my worker going through API Management to get to IS4 and to the resource API. Also, I don't want the resource API passing through APIM to validate the token on IS4.

So basically I want all the internal calls happening inside the cluster.

But, I need both, the IS4 and Resource API to be exposed through APIM, because the resource API can be used by other applications than the worker.

Here my problem starts:
- When I use the discovery endpoint without any configuration it returns the addresses of the nodes inside of the cluster (it screws up the calls of applications that aren't inside of the cluster)
- Ok, then let's change issuer and Public Origin to use APIM external address (it screws up the calls of applications inside of the cluster, like the worker, because now I have to go out the cluster and then come back, but that's not the only problem, I'll need a subscription (to pass through APIM barrier).

brockallen suggested [here](https://github.com/IdentityServer/IdentityServer4/issues/3558#issuecomment-524097950) that what could be done is to set the public origin per request. But also pointed out the problems that it can generate. And as stated by leastprivilege [here](https://github.com/IdentityServer/IdentityServer4/issues/3558#issuecomment-524185229) PublicOrigin should not be used as it's there just to allow a hack to fix a problem that's in another place (misconfigured reverse proxies).

The perfect scenario for me would be to have IS4 returning APIM addresses on discovery endpoint in case of a request that comes from APIM and returning internal cluster addresses when the call is internal.

So, what would be the best/most elegant approach to this problem? Should I set the hostname based on what comes from APIM? What about the load balancer on Service Fabric? Will I need to forward the address again?

I'm not very sure if this is the best place to make this question because it involves programming, infrastructure, and design, but I couldn't find a better place to expose the problem. But if it's not the right place, please point me in the right direction.

Thank you and advance.

**Comment by leastprivilege** [comment]
This has been discussed in many variations already.

All parties must use the same DNS name to access IdentityServer - that's how discovery and OIDC works.

**Comment by TomCJones** [comment]
While @leastprivilege is completely correct, that limitation is failing all around the world and so will cause a change in the specs sooner rather than later.

**Comment by leastprivilege** [comment]
> will cause a change in the specs sooner rather than later

any official reference for that?

**Comment by alancorreas** [comment]
In the end I just used the approach of leaving the container cluster and then coming back through APIM, which is far from ideal for me. But it was the way I found to keep specification compliant.

I hope that in the future the spec take this scenario into account.
