### ISSUE TITLE
EF Core produces a RowLimitingOperationWithoutOrderByWarning

### ISSUE THREAD

**Issue by cuzzlor** [IdentityServer/IdentityServer4#3833]
### Issue / Steps to reproduce the problem

- Follow the EF Core guide to generate and run migrations for a new IdentityServer 4 instance.
- See a `Microsoft.EntityFrameworkCore.Query.RowLimitingOperationWithoutOrderByWarning` warning produced during password auth.
- `Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor` produces a `Microsoft.EntityFrameworkCore.Query.RowLimitingOperationWithoutOrderByWarning` 

### Relevant parts of the log file

```
Query: '(from DeviceFlowCodes x in DbSet<DeviceFlowCodes> where [x].Expiration < (Nullable<DateTime>)DateTim...' uses a row limiting operation (Skip/Take) without OrderBy which may lead to unpredictable results.
```

**Comment by scottbrady91** [comment]
Is this from the latest version?

Do you know if the warning happens with the persisted grants table too?

**Comment by ArturDorochowicz** [comment]
> Query: '(from DeviceFlowCodes x in DbSet<DeviceFlowCodes> where [x].Expiration < (Nullable<DateTime>)DateTim...' uses a row limiting operation (Skip/Take) without OrderBy which may lead to unpredictable results.

FYI, I'm seeing this message in 2.5.3.

**Comment by scottbrady91** [comment]
I can't replicate this using the EF quickstart: https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Quickstarts/4_EntityFramework/src/IdentityServer

Can someone give me some repro steps using that repository?

**Comment by cuzzlor** [comment]
Apologies for missing the messages and the late reply. We were running .NET Core 2.1 targetting net461 and (therefore) using v2.5.3.

**Comment by brockallen** [comment]
I don't see the error/warning either.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
