### ISSUE TITLE
Error when initialize database InitializeDatabase(IApplicationBuilder app)  Cannot insert the value NULL into column 'NonEditable'

### ISSUE THREAD

**Issue by vlapenkov** [IdentityServer/IdentityServer4#3836]
Hi.
I'm trying to Using EntityFramework Core for configuration and operational data. According to your article https://github.com/IdentityServer/IdentityServer4/blob/master/docs/quickstarts/4_entityframework.rst i successfully performed
```
dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb
dotnet ef migrations add InitialIdentityServerConfigurationDbMigration -c ConfigurationDbContext -o Data/Migrations/IdentityServer/ConfigurationDb
```
But when i call `private void InitializeDatabase(IApplicationBuilder app)` it fails with following exception
SqlException: Cannot insert the value NULL into column 'NonEditable', table 'aspnet-AspNetCoreIdentityServer2.dbo.Clients'; column does not allow nulls. INSERT fails.
The statement has been terminated.
Code is following:
```
public static IEnumerable<Client> Clients =>
    new List<Client>
    {
        // machine to machine client (from quickstart 1)
        new Client
        {
            ClientId = "client",
            ClientSecrets = { new Secret("secret".Sha256()) },

            AllowedGrantTypes = GrantTypes.ClientCredentials,
            // scopes that client has access to
            AllowedScopes = { "api1" }
        },
        // interactive ASP.NET Core MVC client
        new Client
        {
            ClientId = "mvc",
            ClientSecrets = { new Secret("secret".Sha256()) },

            AllowedGrantTypes = GrantTypes.Code,
            RequireConsent = false,
            RequirePkce = true,

            // where to redirect to after login
            RedirectUris = { "http://localhost:5002/signin-oidc" },

            // where to redirect to after logout
            PostLogoutRedirectUris = { "http://localhost:5002/signout-callback-oidc" },

            AllowedScopes = new List<string>
            {
                IdentityServerConstants.StandardScopes.OpenId,
                IdentityServerConstants.StandardScopes.Profile
            }
        }
    };
```

Project file is following:
```
<PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <UserSecretsId>aspnet-AspNetCoreIdentityServer-AFD4C82E-A3A7-4B45-BDA5-4EF3A9BE1DF0</UserSecretsId>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="IdentityServer4.EntityFramework" Version="2.1.0" />
    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="2.1.0" />  
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.1.4" PrivateAssets="all">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.4" PrivateAssets="All" />
  </ItemGroup>
```
If i set this field to nullable explicitely, the same bug occurs with IdentityResources.NonEditable , Created and etc ...
How to fix this?
Thanks in advance!

**Comment by scottbrady91** [comment]
These properties should have default values set if you are using the `ToEntity` mappers found in the IdentityServer4 EF library.

That being said, you are using quite an old version of IdentityServer4 and I can't remember exactly when those were added.

**Comment by vlapenkov** [comment]
As i assume you call my nugets too old and you suggest to move to identity server 3.0.x.
Please tell 

- if this server has support for Windows authorization i if there are any samples on github.

- What benefits Using EntityFramework Core for configuration and operational data gives me if i choose to move to IS 3.0.x

**Comment by scottbrady91** [comment]
You could try the patches for 2.1 or even upgrade to 2.5

**Comment by vlapenkov** [comment]
Thank you, i upgraded to  `<PackageReference Include="IdentityServer4.EntityFramework" Version="2.4.0" />    `, InitializeDatabase works
