### ISSUE TITLE
too many .AspNetCore.OpenIdConnect.Nonce cause Nginx Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by wulaiwei** [IdentityServer/IdentityServer4#3837]
Steps to reproduce:

1.)
Go to some page that has authorization required (get redirected to IdenityServer login screen)
Notice that an OpenId.nonce cookie ending with some random suffix is created in browser (so far so good)

2.) Use the browser button to go back

3.) Click again on a link that requires authorization (get redirected to login screen again)
Now an additional OpenId.nonce cookie is being created with different random suffix

4.) Do that 20-30 times until there are too many cookies for the domain and the request is being rejected with "Bad Request - Request Too Long"

By viewing issue, I found some solutions eg:OpenIdConnectAuthenticationHandler ,But it doesn't apply to me.
My project environment version is：
**.net core 2.2  identityserver4**  
I tried the sample project and the problem can be reproduced.
Is there any solution to deal with this problem?
![image](https://user-images.githubusercontent.com/16910820/69127028-6f0a7900-0ae4-11ea-9d92-9b01fb9f4592.png)

**Comment by leastprivilege** [comment]
That's a question for Microsoft @blowdart

**Comment by blowdart** [comment]
Please log a bug in the asp.net repo core about this.

**Comment by wulaiwei** [comment]
> 请将此问题记录在asp.net存储库核心中。

Thank you very much! I have created a bug in the asp.net repo core about this. https://github.com/aspnet/AspNetCore/issues/17247#issue-525355104
