### ISSUE TITLE
authorize/callback endpoint implicit flow CORS issue

### ISSUE THREAD

**Issue by micglo** [IdentityServer/IdentityServer4#3838]
Hello,

In my scenario i have 2 web application. First is .net core mvc app with IdentityServer4 version 3.0.2 installed and second one is angular app for login purpose. IdentityServer is configured with client resource for JS application with AllowedCorsOrigins = { "http://localhost:4200" } and AllowedGrantTypes = GrantTypes.Implicit.

My login in flow is like this:
1. Angular app sets window.location.href to http://localhost:5000/connect/authorize with proper parameters
2. Authorize endpoint redirects to http://localhost:4200/sign-in
3. SignInComponent issues login proces and calls http://localhost:5000/api/auth/login with username, password and returnUrl
4. api/auth/login endpoint verifies user credentials and redirects to given returnUrl which contains url http://localhost:5000/connect/authorize/callback with parameters
5. authorize/callback endpoint should redirect to http://localhost:4200/sign-in-callback with id token and access token but the result is CORS error with message "Access to XMLHttpRequest at 'http://localhost:4200/sign-in?ReturnUrl=http%3A%2F%2Flocalhost%3A5000%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Djs%26scope%3Dopenid%2520profile%2520api1%26response_type%3Did_token%2520token%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A4200%252Fsign-in-callback%26state%3Dabc%26nonce%3Dxyz' (redirected from 'http://localhost:5000/api/auth/login') from origin 'null' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response."

In addition .net core app has set up CORS service to allow any origin, any header and any method.

**Comment by brockallen** [comment]
It doesn't sound like your scenario is following the proper OIDC login workflow. Having said that, StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
