### ISSUE TITLE
Issue a warning or throw an exception for not completely configured ResourceOwnePassword flow.

### ISSUE THREAD

**Issue by voroninp** [IdentityServer/IdentityServer4#3839]
**Is your feature request related to a problem? Please describe.**
It's easy to forget to register custom implementation of `IResourceOwnerPasswordValidator` when client is allowed to use resource owner credentials flow.

**Describe the solution you'd like**
I would like to see at least a warning, which says that clients A,B and D can use the flow, but it is not completely configured. Throwing an exception is definitely a breaking change, but failing at startup is much better than just log message `flow is not supported`.

**Comment by voroninp** [comment]
Though it is weird because commit e504a423 contains line

```CSharp
_logger.LogInformation("Resource owner password credential type not supported. Configure an IResourceOwnerPasswordValidator.");
```

However I never saw the part about `IResourceOwnerPasswordValidator`

**Comment by voroninp** [comment]
Ah, I got it. We log only errors, so this is not shown in log, but failed grant validation is logged as error, however, it contains string which is coming from `ConvertTokenErrorEnumToString(error);` So information is partially lost. Error description is returned as part of the response, yet it is not logged.

Ugly solution is to add another enum value `TokenRequestErrors.ResourceOwnerPasswordValidatorNotImplemented` and create correct string from it.

**Comment by leastprivilege** [comment]
As I said before - extending the client config validator is the right way to do that.
