### ISSUE TITLE
Option for masking user name.

### ISSUE THREAD

**Issue by voroninp** [IdentityServer/IdentityServer4#3841]
**Is your feature request related to a problem? Please describe.**
GDPR and other rules related to personal information may be quite strict and require that user name is not logged as a plain text.

```
"Raw": { "username": "USERNAME", "scope": "openid offline_access", "client_id": "otp_client", "client_secret": "***REDACTED***", "grant_type": "one_time_password", "password": "***REDACTED***" }
```

**Describe the solution you'd like**
I'd like to have an option for `IS4` when required to treat `username` as sensitive data and mask it.

**Comment by leastprivilege** [comment]
..and how useful is that log entry then?

related to and tracked here:
https://github.com/IdentityServer/IdentityServer4/issues/3518

**Comment by voroninp** [comment]
@leastprivilege  Well, usually user name consists of more than 4 characters, so in our system we just use first N and last characters: voro...@...com
Having timestamp on log entry helps to correlate it with the actions., if you know who made an attempt to sign in.

You could just define some transformer which does nothing by default, by framework users then could provide their own implementation. For example for us it perfectly fine to replace user email with internal user id.

**Comment by leastprivilege** [comment]
> You could just define..

please comment on https://github.com/IdentityServer/IdentityServer4/issues/3518

this is where such changes are compiled, because this is a bigger effort than changing individual log entries...

**Comment by leastprivilege** [comment]
> GDPR and other rules related to personal information may be quite strict and require that user name is not logged as a plain text.

* Is this a real issue for you - or just a potential one?
* is it only in one place in the code base?

**Comment by voroninp** [comment]
Ok, sorry, I'll add comments there.

**Comment by leastprivilege** [comment]
I would be interested in the answers to that 2 questions above

**Comment by voroninp** [comment]
Done.

**Comment by leastprivilege** [comment]
We won't add a general purpose log pre-processing feature now. But if you do some research and have a look where exactly we log the username - we could probably add redaction more short term.

**Comment by voroninp** [comment]
Ok, I kinda fixed it myself:

```CSharp
var userName = context.Request.Raw["username"];
var password = context.Request.Raw["password"];

if (userName.IsNullOrEmpty())
{
    context.Result = new GrantValidationResult
    {
        IsError = true,
        Error = "'username' field is not set."
    };
    return;
}

Email userEmail;
try
{
    userEmail = (Email)userName;
    // DECISION: Identity Server logs raw requests, so we need to mask user name to comply with GDPR
    context.Request.Raw["username"] = userEmail.MaskedValue;
}
catch
{
    Logger.LogDebug("User name '{username}' is not a valid email address.", userName);
    context.Result = new GrantValidationResult
    {
        IsError = true,
        Error = "Wrong user name."
    };
    return;
}
```
You log raw request, I just masked the value.

P.S.
I was surprised to discover that `UserName` property does not propagate value back to the request, my expectation was that it is just a convenient proxy for `Request.Raw["username"]`.

**Comment by leastprivilege** [comment]
yea - re-writing logging is one my to do list ... glad it works for you.
