### ISSUE TITLE
Can Data protection be used to sign tokens

### ISSUE THREAD

**Issue by Alik2015** [IdentityServer/IdentityServer4#3843]
Just wondering if we have to use certificate to sign tokens or if Data Protection was added could that be used instead of having a certificate?

**Comment by leastprivilege** [comment]
Data protection is a mechanism based on symmetric keys - this is not recommended.

You don't need to use a certificate - any RSA or ECDSA based asymmetric key would work.

**Comment by Alik2015** [comment]
Is there any good examples that will allow me to create RSA and store it where ever I want e.g filesystem/database etc.  The idea is the cloud app can access this no matter where it is.  Other alternative I guess is to generate self signed cert and just use that.  Which is good for cloud app running on multiple instances for the Id Server?

**Comment by leastprivilege** [comment]
Have a look at the source code of the `AddDeveloperSigningCredential` extension method...
