### ISSUE TITLE
Regarding the "Allow access token in browser" setting.

### ISSUE THREAD

**Issue by haugan** [IdentityServer/IdentityServer4#3844]
Even if I set AllowAccessTokensViaBrowser = false in my Client configuration, I'm still able to find the token in my Firefox console by looking at the request headers. I think I'm misunderstanding how this is supposed to work, so could you please enlighten a (poor) noob? I wasn't able to find properly dumbed down examples of this elsewhere! :)

Example code using PKCE flow:
`
new Client 
{ 
    // .. 
    AllowedGrantTypes = GrantTypes.Code, 
    AllowAccessTokensViaBrowser = false, 
    RequirePkce = true 
    // .. 
} 
`

**Comment by brockallen** [comment]
the flag `AllowAccessTokensViaBrowser` really controls if we allow an access token to be returned to the client in the URL from the authorize endpoint (as opposed to the normal mechanism of the token endpoint).

**Comment by haugan** [comment]
Oh, ok. I guess I got some reading to do. Thanks for your swift answer Brock! :)
