### ISSUE TITLE
Extend Client class - add permissions

### ISSUE THREAD

**Issue by JeremiJutand** [IdentityServer/IdentityServer4#3847]
I use Identity Server 4 for managing authentication in my different clients.
I'd like include permissions for managing authorization ; to do this, I want to add them on each client and API like suggest [(https://leastprivilege.com/2016/12/16/identity-vs-permissions/)].

I'd like to extend the Client class or ConfigurationDbContext to add roles and permissions but I don't know all steps to do this (what classes I've to extend, how to migrate to EF, what configuration, ... and firstly if it is possible ?)

Thanks

**Comment by cowlinb6** [comment]
This is good starting point

https://github.com/PolicyServer/PolicyServer.Local

**Comment by JeremiJutand** [comment]
Thanks for your answer !
I've already read this article and it could be perfect for what I'm doing... but I want to manage and centralize this mechanism in database in my Identity Server app.

Have you any idea ?

**Comment by cowlinb6** [comment]
We did the same thing. You can just build upon the sample to add a database store behind this - which can be the same as IdentityServer db.
