### ISSUE TITLE
HTTP link in HTTPS host

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#385]
When I start IdentityServer4 using HTTPS, I receive to following exception in the browser:

SEC7111: HTTPS security is compromised by http://localhost:28168/2d581390896c4191bba0e7f6b9141a8b/browserLink

Code:
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/master/src/IdentityServerWithIdentitySQLite

Greetings Damien

**Comment by brockallen** [comment]
So disable browser link?

**Comment by damienbod** [comment]
@brockallen could do that, but I cannot change the browser link because it is defined no where from me. Where is this browser link defined and why is it called. IdentityServer is running on HTTPS and not HTTP and also using a different port. This URL is not defined or configured any where in my application.

Greetings Damien

**Comment by damienbod** [comment]
This has nothing to do with IdentityServer4, but more the UseBrowserLink extension does not work with HTTPS. I'll close this and open the issue where it belongs.

Sorry and thanks Damien

**Comment by brockallen** [comment]
> Where is this browser link defined and why is it called.

In ASP.NET Core, it's a middleware that the templates add IIRC.
