### ISSUE TITLE
How do I interrogate Login on the Account Controller in the Combined Quickstart?

### ISSUE THREAD

**Issue by gph2000** [IdentityServer/IdentityServer4#3851]
How do I interrogate the call to the Login action on the Account Controller in the Combined Quickstart? 

I believe that if I can either redirect to a different action or pass additional parameters to the Login Action then I can build out the remainder of what is needed to implement a reset password / confirm registration feature based on an emailed link with a unique token.

**Comment by gph2000** [comment]
Since my rest token is Microsoft Identity generated, I'm thinking what if I verify it in my MVC client applicaiton and where valid use machine-to-machine between the client and identityserver to authorize the session. Am I going in the right direction?

**Comment by leastprivilege** [comment]
I honestly don't know what you are talking about.

**Comment by gph2000** [comment]
Hi Dominick, apologies for the confusion. Let me try clear it up.

**My Objective**
Consume a reset password / confirm account link from my MVC client that will also authenticate the user via IdentityServer without forcing them to enter credentials.

**Initial thoughts**
Following the combined quick start as a template, where an MVCclient with the Authorize attribute on an action redirects to the login action on the identity server account controller, I wanted to either pass additional parameters to that action or redirect to a new one entirely when consuming a reset link. I cannot figure out how to make that cut.

**Further thoughts**
My initial thoughts may not be possible and even if they are a simpler solution may be available. Let's say the MVC client validates the token from the link itself and upon finding it to be valid then uses a shared secrect (machine-to-machine) method of communication as per the console client example in the combined quickstart to authenticate the session with Identity Server. It will be Monday before I have the opportunity to experiment with this some more.

**Comment by gph2000** [comment]
I'm going to close this for now, Machine-to-Machine looks like it will suffice as a workaround. I will pose a fresh question on how to pass the login credentials rather than pull them from a form when I get back to this.
