### ISSUE TITLE
IdentityServer4.Storage with version (>= 3.0.3)

### ISSUE THREAD

**Issue by SDmorgan** [IdentityServer/IdentityServer4#3852]
Downloaded the latest version. Getting error message when building 

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	NU1102	Unable to find package IdentityServer4.Storage with version (>= 3.0.3)
  - Found 20 version(s) in NuGet [ Nearest version: 3.0.2 ]
 

Went to Nuget repository and could only find IdentityServer4.Storage version 3.0.2. 

Where is 3.0.3?

### Issue / Steps to reproduce the problem

Download and build solution.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
> Downloaded the latest version. Getting error message when building

You mean the source code?

you need to run `build.ps1` first - as stated in the readme.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
