### ISSUE TITLE
GetProfileDataAsync called multiple times, results in multiple database entries.

### ISSUE THREAD

**Issue by babloo-singh** [IdentityServer/IdentityServer4#3856]
I have a rather different use case where I have to track the login history, and to track them I'm creating a new GUID in the IProfileService and adding it in the claims and also to the DB , to continue front end task.
The issue is I get multiple DB entry for a single login click, which starts displaying two records per login.
The GUID is used to track the current login session.(We have concurrent login scenario)
Question 1 - Is the GUID creation within this function the right thing, if not where to do it?
Question 2 - Does IDSvr provide a Unique Id for each login, so that i can just use it in the claims.
Question 3-  How I stop/minimize the other DB calls made because of multiple calls.

 ```
public async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var user = DataBaseUserRetrive();
            var claims = new List<Claim>
            {
                         //All Claims from user
            };
                string deviceIdGuid = Guid.NewGuid().ToString();
                Claim deviceId = new Claim("device_id", deviceIdGuid ,ClaimValueTypes.String);
                claims.Add(deviceId);
                await databaseCall(user,deviceIdGuid );
           context.IssuedClaims = claims;
        }
```

**Comment by brockallen** [comment]
The profile service is the wrong place for that.

**Comment by babloo-singh** [comment]
Yes, I figured that out. For a quick fix I put my logging logic within the claimsTranformer class, and added the ID in the principalclaims with some "does exists" check. But is there a better place where I can probably do this kind of stuff?

**Comment by brockallen** [comment]
Why not put your logic in the login page? Isn't that when the user logs in? In any event, I can't really answer your question, as it's your requirements and solution.
