### ISSUE TITLE
MissingFieldException: Field not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueExceptionMethod'.

### ISSUE THREAD

**Issue by salaritangianbonfire** [IdentityServer/IdentityServer4#3862]
MissingFieldException: Field not found: 'Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueExceptionMethod'.

Hi, I'm currently using EF Core , MySQL and Xamarin Form for my development.

I've encountered this error when I'm trying to SaveChanges() my insert statement without identity(id[pm key]) in the object which is auto incremented and also my primary key. BUT ITS WORKING IF I WILL INCLUDE MY column "Id" in making statement.

This is my Category class on Model part:
    public class Category
    { 
        public long Id { get; set; }
        public string Name { get; set; }
        public int Active { get; set; }
        public string Image { get; set; }
        public DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    }

This is my class for Category's Model Builder:
        public void Configure(EntityTypeBuilder<User> builder)
        {
            builder.ToTable("category");
            builder.Property(a => a.Id).HasColumnName("id");
            builder.Property(a => a.Name).HasColumnName("name");
            builder.Property(a => a.Active).HasColumnName("active");
            builder.Property(a => a.Image).HasColumnName("image");
            builder.Property(a => a.LastModifiedDate).HasColumnName("last_modified_date");
            builder.Property(a => a.LastModifiedBy).HasColumnName("last_modified_by");
        }

And this is my simple insert statement method which I will call every time I run the software:
        public static void InsertCategory()
        {
            var category = new Category
            {
                Active = 1,
                Image = "c:",
                LastModifiedBy = "gian",
                LastModifiedDate = DateTime.Now,
                Name = "category"
            };
            using (var databaseContext = new DatabaseContext())
            {
                databaseContext.Category.Add(category);
                databaseContext.SaveChanges();
            }
        }

![Capture](https://user-images.githubusercontent.com/55374833/69770905-b7512780-11c5-11ea-9e89-52ceba07b1e0.PNG)

**Comment by scottbrady91** [comment]
Is this anything to do with IdentityServer4? It looks like this is a general EF question.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by salaritangianbonfire** [comment]
The main issue was ef core was installed only in the PCL project thats why
I've encountered this issue on different platform. The solution basically
is to install the ef core in all your project platform (android, ios, uwp).
Good to close this issue
