### ISSUE TITLE
Can we change base path for particular endpoint like Token endpoint?

### ISSUE THREAD

**Issue by mgupta0710** [IdentityServer/IdentityServer4#3865]
Is there any way to change base path for particular endpoint like Token endpoint in discovery document?
Example : https://localhost:5001/.well-known/openid-configuration

Response: ....
`"token_endpoint": "https://api.com/connect/token",`

**Comment by leastprivilege** [comment]
no. sorry.

**Comment by mgupta0710** [comment]
I got this by extending DiscoveryResponseGenerator class and overriding CreateDiscoveryDocumentAsync method as below:

```
        public override async Task<Dictionary<string, object>> CreateDiscoveryDocumentAsync(string baseUrl, string issuerUri)
        {
            var entries = await base.CreateDiscoveryDocumentAsync(baseUrl, issuerUri);

            if (Options.Endpoints.EnableTokenEndpoint && Environment.IsStaging())
            {
                entries["token_endpoint"] = "https://api.com/connect/token";
            }
            return entries;
        }
```

**Comment by leastprivilege** [comment]
Ah - yes of course. You can do that. But that does not move the actual endpoint...

**Comment by mgupta0710** [comment]
Yes. I agree. We have API routing layer for that. Thanks for your response.
