### ISSUE TITLE
When using more than one IDP, have problem with logout, cause session in idsrv.session cookie is being overwritten.

### ISSUE THREAD

**Issue by moskam** [IdentityServer/IdentityServer4#3868]
We are struggling recently with some uncommon issue in our implementation of Identity Server 4. I've prepared Demo of the issue inside this [repository](https://github.com/moskam/idserver4-multiple-idp-issue) with steps to reproduce it.

I think the problem is with identity server session id stored in 'idsrv.session' cookie which is overwritten when you log in using different IDP in the other tab, that way on logout wrong session is being used so user is not correctly logged out. Is there any other way to store session id, not in cookie which can be shared? Or maybe there is a way of using cooking from IDP instead of Identity Server host.

**Comment by brockallen** [comment]
If you establish a new identity, that's a new session. It's quite involved to design your identity system to support multiple simultaneous sessions. Google does it, but I've not really seen any others that do.

**Comment by moskam** [comment]
> If you establish a new identity, that's a new session. It's quite involved to design your identity system to support multiple simultaneous sessions. Google does it, but I've not really seen any others that do.

Does anyone have a code sample of simultaneous sessions?

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
