### ISSUE TITLE
What are the scalability targets of IS4?

### ISSUE THREAD

**Issue by mxa0079** [IdentityServer/IdentityServer4#3869]
Hello,

I've looked without succes for information about the scability targets of Identity Server 4. We are considering using it for an app with 1 million monthly active users. Are there any case studies or references that I could use?

I understand that we will be responsible for the authentication code of the serverm but what about the other standard endpoints?

Thanks,

Mau

**Comment by brockallen** [comment]
It's just another web app, so you scale it like anything else you build. We mention deployment considerations here: http://docs.identityserver.io/en/latest/topics/deployment.html

**Comment by mxa0079** [comment]
Hello @brockallen - we really appreciate your reply.

If it is true and we understand that this is just another web app, it is also true that the code can be optimized to make efficiente use of the resources where it is hosted or it can have performance deficiencies.  We are not concerned about the asp.net core part of the solution, we know its performance is top notch. We are concerned about the code written on top of it (authorization, token, and the other endpoints). Hence our question stands.

Are there use cases of relevant traffic using identity server? Has anyone performance load or performance tests on the server? 

Thanks,

Mau

**Comment by brockallen** [comment]
We don't have anything like that, as we're a framework and every app using IdentityServer is custom and is possibly done differently with different workflows and thus would have perf characteristics.

**Comment by mxa0079** [comment]
But the authorization and token endpoints will always be the same. I think it would be very valuable to have performance and scalability metrics for thos endpoints.

Given our volume, we will have to do this before going to production.  If anyone in the core team is interested in participating so the community can benefit from this effort we will be happy to collaborate.

**Comment by brockallen** [comment]
> But the authorization and token endpoints will always be the same.

Not necessarily. Many people use in-mem config, others don't. Some people build custom profile services, some don't. Some have thousands of users, some have millions. We have many extensibility points, so I'm not sure what you'd settle on for a "standard test".

Anyway, as I said, we don't have this in the OSS.

**Comment by leastprivilege** [comment]
Feel free to do some perf measurements using typical setups (db, in-mem, cached etc.) - we are happy to link to them from our docs.
