### ISSUE TITLE
Logging levels for events

### ISSUE THREAD

**Issue by beakersoft** [IdentityServer/IdentityServer4#3872]
Is there any way to change the logging levels of the messages that come out of Identity server. For example in our prod enviroment we have a dashboard view of critical/error/warning messages, and get a lot of messages logged from idsv such as 

_Invalid password for user 'xxxxxx'_

As the level of this is a warning we see it in the logging dashboard, but never act on it (we cant really do anything about it) so we class it as log spam. 

We use Serilog and could set that to just log messages error and above from the classes causing the log spam, but ideally it would be good to carry on logging these messages as Information instead of warning in case we do ever need to go back to them.

Cheers

**Comment by leastprivilege** [comment]
Nothing "built-in" right now. On the to-do list.

Tracked here: https://github.com/IdentityServer/IdentityServer4/issues/3518
