### ISSUE TITLE
Set idsvr.session cookie httponly is true

### ISSUE THREAD

**Issue by Thomas5588** [IdentityServer/IdentityServer4#3873]
How to set httponly flag is true for idsvr.session ?

**Comment by leastprivilege** [comment]
why?

**Comment by Thomas5588** [comment]
to stops javascript from being able to read the cookiw value.

**Comment by leastprivilege** [comment]
That's the whole purpose of it.

https://openid.net/specs/openid-connect-session-1_0.html
