### ISSUE TITLE
Azure Windows Authentication

### ISSUE THREAD

**Issue by HariSirigouniTest** [IdentityServer/IdentityServer4#3874]
Hi,

We are using Identity Server 4 framework to build Token App(.Net Core web app). We need to support both Forms & Windows(LDAP and Azure AD) authentications. Windows authentication works fine when application is running on locally or VMs but not in azure (app service), as there is no direct support in azure to enable windows authentication. Can some one help me how this can be achieved?

Thanks,
Hari.

**Comment by brockallen** [comment]
How a user logs in is up to your hosting logic: http://docs.identityserver.io/en/latest/intro/big_picture.html#how-identityserver4-can-help
