### ISSUE TITLE
Introspection Call With Client Cert

### ISSUE THREAD

**Issue by jgill248** [IdentityServer/IdentityServer4#3876]
I have a self-hosted instance of IdentityServer 4 in an ASP Core 2.2 application.  Everything works well until we turn on IIS > SSL > Require Certificate.  Then I am getting an error:

 Exception message: Discovery endpoint https://localhost/.well-known/openid-configuration is unavailable: Error connecting to https://localhost/.well-known/openid-configuration: Forbidden
Stack trace:    at IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions.GetIntrospectionEndpointFromDiscoveryDocument(OAuth2IntrospectionOptions Options) in ....

It seems like I need to add a client certificate on the call to the Discovery Document and the Introspection endpoints.  I cannot figure out out how to do this.  I am I way off here or just missing something obvious.

**Comment by klioqc** [comment]
That IIS setting indeed requires client cert for all calls.
What are you trying to achieve? If just to enable https then it is not the right place to do.

**Comment by jgill248** [comment]
@klioqc unfortunately, we are in a hosting environment that we do not control.  The security requirements levied on IIS by the company in charge of the hosting environment state that Require must be selected.

**Comment by leastprivilege** [comment]
Then they are doing it wrong.

**Comment by jgill248** [comment]
They could be doing it wrong, but I don't really have an option.  https://vaulted.io/library/disa-stigs-srgs/iis_85_site_security_technical_implementation_guide/V-76779?version=v1r1

**Comment by leastprivilege** [comment]
Above you say "require client cert" - which is different to requiring HTTPS.

I agree that HTTPs is required - client certs are not.

**Comment by jgill248** [comment]
Sorry, I had the wrong STIG:  https://www.stigviewer.com/stig/iis_8.5_site/2019-01-08/finding/V-76809.  

"Follow the procedures below for each site hosted on the IIS 8.5 web server:

Open the IIS 8.5 Manager.

Double-click the "SSL Settings" icon.

Verify the "Clients Certificate Required" check box is selected.

If the "Clients Certificate Required" check box is not selected, this is a finding."

**Comment by leastprivilege** [comment]
> Exception message: Discovery endpoint https://localhost/.well-known/openid-configuration is unavailable: Error connecting to https://localhost/.well-known/openid-configuration: Forbidden
Stack trace: at IdentityModel.AspNetCore.OAuth2Introspection.PostConfigureOAuth2IntrospectionOptions.GetIntrospectionEndpointFromDiscoveryDocument(OAuth2IntrospectionOptions Options) in ....

Well - then this error message indicates that you client is not presenting a client certificate that is accepted by your IIS.

**Comment by jgill248** [comment]
That is correct, but I don't know how to tell our API to use a client cert to make the call to .well-known.  I have tried to use JwtBackChannelHandler, and create a custom SendAsync method, adding a client cert to that call.  But I get an error about the request being sent multiple times.

**Comment by leastprivilege** [comment]
Yea - you can't do that ;)

Try this one
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-3.0&viewFallbackFrom=netframework-4.8

and set the client cert there.

**Comment by jgill248** [comment]
I'll give that a try, but I do need to do that with the IntrospectionBackChannelHandler and IntrospectionDiscoveryHandler properties I am trying to put this behavior into, yea?

**Comment by leastprivilege** [comment]
Well - you might be on an old version. The latest version does not do that distinction anymore and uses the HTTP client factory instead.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.

**Comment by jgill248** [comment]
@leastprivilege , thank you for the help.  I can't tell you how long I was banging my head against the wall trying to figure this out!
