### ISSUE TITLE
Feature 'recursive patterns' is not available in C# 7.3. Please use language version 8.0 or greater.

### ISSUE THREAD

**Issue by SDmorgan** [IdentityServer/IdentityServer4#3877]
### Issue / Steps to reproduce the problem
Using VS2019 latest build. Core 3.1 installed
Run build.ps1

### Relevant parts of the log file
I get 5 errors.

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS8370	Feature 'recursive patterns' is not available in C# 7.3. Please use language version 8.0 or greater.	IdentityServer4	C:\Users\smorgan\Source\repos\IdentityServer4-master\src\IdentityServer4\src\Configuration\CryptoHelper.cs	90		Active

Error reoccurs four more times in same file at line 104, 118, 143, 158.

When looking at the project file, I cannot choose the version of C# as it states it is tied to the version of .Net you are using. I checked and I am using 3.1 Core which should be c#8.0

Any suggestions would be appreciated.

```
<log goes here>
```

**Comment by leastprivilege** [comment]
Sorry - no idea. Can't repro.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
