### ISSUE TITLE
checksession endpoint clears all related cookies occasionally during silent response

### ISSUE THREAD

**Issue by svechin** [IdentityServer/IdentityServer4#3878]
Hi, 

Keep struggling with the issue when silent call to checksession endpoint clears all auth cookies in response by resetting its values and expiration which causes user to be unauthorized on the next call or page refresh. It happens occasionally and I can't bind any configured time spans with the period when this happens. It happens earlier than cookie might have expired even thought i have sliding expiration. So instead of rendering checksession html response i see empty body and headers in chrome which reset xxxx.identity, xxxx.session cookies. If I compare two requests to checksession endpoing: one which works correctly and weird one - they are identical - similar identity cookie is attached in both cases.

Just for clarification. User can successfully login, get token, code etc keep working, refresh pages or navigate, do ajax calls and in 15min or 45min or another time period he is being redirected to the login page. Studying network activity I see that some of previous checksession calls cleared all cookies. 
Nothings in logs preceding weird checksession call which may clarify why user is decided to be unauthenticated.

IdentityServer4 (2.4.0), netcore 2.2. Configuration is quite common for spa client.  
  
So the question is has anybody ever met such behavior and may share direction where to look at.

**Comment by leastprivilege** [comment]
We can only help you (for free) if you update to the latest version - in your case 2.5.3.
