### ISSUE TITLE
About idsvr.session cookie

### ISSUE THREAD

**Issue by Thomas5588** [IdentityServer/IdentityServer4#3882]
Hi,
I am new to identity server so any one can share about the below

What is the main job of 'idsvr.session' cookie and what are the information it has.

Thanks
Thomas

**Comment by brockallen** [comment]
It's used for this spec: https://openid.net/specs/openid-connect-session-1_0.html

**Comment by Thomas5588** [comment]
It’s says, cannot set http only flag for this cookie, then how we can secure it
Could you please share your thoughts

**Comment by leastprivilege** [comment]
This is cookie is made for JavaScript to consume it.
