### ISSUE TITLE
Network calls /.well-known/openid-configuration/ and /.well-known/openid-configuration/jwks

### ISSUE THREAD

**Issue by vlapenkov** [IdentityServer/IdentityServer4#3883]
Hello! 
I have :
1. Identity server 4, 
2. Mvc app  with OpenId Connect and Hybrid flow 
3. Webapi app.

Assume user already got cookies with id_token and access token.
Then he calls an action from mvc app:

 ```
var accessToken = await HttpContext.GetTokenAsync("access_token");
  var client = new HttpClient();
  client.SetBearerToken(accessToken);
 // call webapi
  var content = await client.GetStringAsync("http://localhost:5001/api/resource-with-policy");
```

In fiddler i see two calls:
GET <is4-url>/.well-known/openid-configuration/
GET <is4-url>/.well-known/openid-configuration/jwks 

As i assume WebApi sees [Authorize] attribute on action and make these calls. 
What's purpose of these calls?

**Comment by leastprivilege** [comment]
https://openid.net/specs/openid-connect-discovery-1_0.html

**Comment by vlapenkov** [comment]
I read this document but information about GET /.well-known/openid-configuration/jwks is missed there.

**Comment by leastprivilege** [comment]
Thats the `jwks_uri`.

**Comment by TomCJones** [comment]
well, there is a longer answer that might help vlapenkov
https://stackoverflow.com/questions/59245281/network-calls-well-known-openid-configuration-and-well-known-openid-configu
