### ISSUE TITLE
405 Method not allowed on requests to API

### ISSUE THREAD

**Issue by SpiritBob** [IdentityServer/IdentityServer4#3884]
I have a configured Identity Server (latest version), using the quickstart files, except slightly modified to use database/external storage.

I have a mockup web-client that authenticates the user through the identity server (hybrid flow), which in turn return an access token granting me access to the protected resources to my API (So we have 3 projects, a web client, the identity server, and the API client - all of which are using their latest versions/NET Core 3.0)

Everything was working correctly prior to updating my whole solution (from 2.2 core to 3.0), except that now, for some mind-boggling reason, when I do a GET request from `HttpClient`, or use `SendAsync` with a corresponding GET `HttpRequestMessage` to the specific resource, I get a 405 method not allowed, whereas the same request, with the same headers (only access key, nothing else fancy, no body, etc) from Postman, returns the expected result.

This is killing me. Can you please help me out here? All 3 projects are hosted on my localhost. The endpoint I'm trying to hit is something like this "https://localhost:39491/api/somecontroller/someaction?id=7

I tried setting `BaseAddress` to `https://localhost:39491/api` and then passing in the rest of the url like this `/somecontroller/someaction?id=7`, and I also tried without setting that property, and just altogether do the get request on the full uri string.

Neither of those approaches worked, nor did using `HttpRequestMessage` with `SendAsync` yield any results.

Please, help me out here!

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
