### ISSUE TITLE
Username with empty password - TokenRequestValidator

### ISSUE THREAD

**Issue by jded76** [IdentityServer/IdentityServer4#3885]
I'm trying to implement a new Web API (.net Core) with IdentityServer 4 as the authentication framework to replace my old one (.net framework). The whole project is going very well (I have almost finished) but now I faced an unexpected problem.

I saw [here](https://github.com/IdentityServer/IdentityServer4/blob/1a7fb8e045dcf53cfe93ac2c68fc084c6dc44f78/src/IdentityServer4/src/Validation/Default/TokenRequestValidator.cs#L389) that password must be non empty to continue and call my custom ResourceOwnerPasswordValidator.

We have many test environments with users with empty password. In some rare occasions we have users with empty password in production too because the application is for internal use (private network) and the users are not so experienced, so I cannot escape from that.

I know that the empty password is not a wise choice but it's not up to me to argue with the users of our product. After all it's their data, their risk...

Is there any way to allow empty passwords?

Thank you for your time and your excellent framework by the way.

John Dendrinos

**Comment by jded76** [comment]
Hi @leastprivilege,

Is there anything I can do to help with this?

**Comment by brockallen** [comment]
Should username also be optional? :P

**Comment by LindaLawton** [comment]
>I know that the empty password is not a wise choice but it's not up to me to argue with the users of our product. After all it's their data, their risk...

I would just like to point out that if there is a data breach who do you think they are going to come after because of an insecure system?   IMO its every developers job to ensure that the users are secure they dont know enough to know the dangers its up to us to show them the way.

Not sure how much my opinion counts for but opposed to nullable password.    Let them set it to PassW0rd123 if they want :)

**Comment by jded76** [comment]
There are applications of high risk, low risk and there are with no risk. 
So the responsibility of the password should be in UserProvider, not in every library that has to do with password. There you can have options about password complexity, strength, length or whatever you need and you validate the password before write it.

Either way, I'm not here to argue about the necessity of the password but only because I think this validation is out of scope of IdentityServer (especially if you rely on other user providers).
For example, as the code is right now, it will not work if you have spaces for password (because of string.IsNullOrWhiteSpace [here](https://github.com/IdentityServer/IdentityServer4/blob/1a7fb8e045dcf53cfe93ac2c68fc084c6dc44f78/src/IdentityServer4/src/Extensions/StringsExtensions.cs#L66)).

**Comment by leastprivilege** [comment]
> So the responsibility of the password should be in UserProvider, not in every library that has to do with password. There you can have options about password complexity, strength, length or whatever you need and you validate the password before write it.

agreed.

**Comment by leastprivilege** [comment]
ok. done for 3.1
