### ISSUE TITLE
Using Postman to test OAuth Authentication Code Flow

### ISSUE THREAD

**Issue by cowlinb6** [IdentityServer/IdentityServer4#3889]
I'm trying to use Postman to test the Authentication Code Flow - but it doesn't seem to work correctly. I'm not sure if this is IS4 or a Postman issue.

Using the demo instance (https://demo.identityserver.io/) and the SPA client below

```
new Client
{
    ClientId = "spa",
    ClientName = "SPA (Code + PKCE)",

    RequireClientSecret = false,
    RequireConsent = false,

    RedirectUris = { "https://notused" },
    PostLogoutRedirectUris = { "https://notused" },

    AllowedGrantTypes = GrantTypes.Code,
    AllowedScopes = { "openid", "profile", "email", "api" },

    AllowOfflineAccess = true,
    RefreshTokenUsage = TokenUsage.ReUse
},
```

When I try and request the token:

![image](https://user-images.githubusercontent.com/12410874/70529354-40fae080-1b48-11ea-8b9c-40f2826b687f.png)

I then login with either bob/bob or alice/alice and when I click the Login button it justs redirects back to the login screen.

I was expecting the access token to be retrieved.

![image](https://user-images.githubusercontent.com/12410874/70529557-b5ce1a80-1b48-11ea-88a6-f93fb5e48214.png)

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!

**Comment by cowlinb6** [comment]
Moved this over to StackOverflow

https://stackoverflow.com/questions/59286904/using-postman-to-test-oauth-authentication-code-flow
