### ISSUE TITLE
is4ui and  is4inmem error in documentation. Couldn't find an installed template that matches the input, searching online for one that does.

### ISSUE THREAD

**Issue by KamranShahid** [IdentityServer/IdentityServer4#3890]
I am following tutorial on http://docs.identityserver.io/en/latest/quickstart with ,y .net core 3.0 solution
Were able to complete first section
Then in second part when trying 
https://github.com/IdentityServer/IdentityServer4/blob/master/docs/quickstarts/2_interactive_aspnetcore.rst

dotnet new is4inmem
getting error 
**Couldn't find an installed template that matches the input, searching online for one that does...**

dotnet new is4ui
**Couldn't find an installed template that matches the input, searching online for one that does...**

Please let me know what wrong i am doing

**Comment by brockallen** [comment]
Did you install the template?

**Comment by KamranShahid** [comment]
I thought i have installed it prior. but let me try do it again and check

**Comment by leastprivilege** [comment]
Templates are per SDK - if you updated the SDK, you need to re-install the templates as well.
