### ISSUE TITLE
Minor Quickstart Docs Typo

### ISSUE THREAD

**Issue by bryanllewis** [IdentityServer/IdentityServer4#3896]
On the Protecting an API using Client Credentials quickstart page, the code in the "Calling the API" section has a small error.  The code block starts with 

```
// call api
var client = new HttpClient();
```

When, in order to match the actual sample file in the repo, should be:
```
// call api
var apiClient = new HttpClient();
```

In addition to just being consistent, if you follow along the tutorial and create the file yourself, instead of just copying the "full file" from the repo, then the "client" var will conflict with the one of the same name in the "discover endpoints from metadata" section.

**Comment by leastprivilege** [comment]
OK - thanks. PR?
