### ISSUE TITLE
Case convention for PostgreSQL

### ISSUE THREAD

**Issue by aspramsh** [IdentityServer/IdentityServer4#3897]
Hi all,

I am using Identity Server with PostgreSQL. I would like to know if there is a way to change naming convention from Pascal case to snake case?

**Comment by brockallen** [comment]
It's EF Core under the covers -- so the question is can you make that do what you want?

**Comment by aspramsh** [comment]
I use this blog post for overriding NpgSQL naming conventions. So can I override ConfigurationDbContext's and PersistedGrantDbContext's OnModelCreating method?

**Comment by brockallen** [comment]
I just provided a somewhat simiar example for clustering. You can see if it works for your NpgSQL config:

https://github.com/IdentityServer/IdentityServer4/issues/3770#issuecomment-564327555

**Comment by aspramsh** [comment]
When I do that I get the following error:
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.DbContextOptions`1[IdentityServer4.EntityFramework.DbContexts.PersistedGrantDbContext]' while attempting to activate 'MyContext'.

**Comment by brockallen** [comment]
Ah yea, I see. Can you try:

`public MyDbContext(DbContextOptions<MyDbContext> options, OperationalStoreOptions storeOptions) : base(options, storeOptions)`

instead?

**Comment by aspramsh** [comment]
I have generated migrations successfully, thanks a lot.
