### ISSUE TITLE
Native UI: Using discovery document with a native ios/android ui

### ISSUE THREAD

**Issue by Jonatthu** [IdentityServer/IdentityServer4#3898]
So I am currently working on a native ui on ios, I am aware that if I use authorize endpoint to start a code flow I need to have a session cookie on Identity server.

https://github.com/karpikpl/identity-server4-with-SPA-UI 
I was able to implement this with an angular application serving as an UI for identity server.

I want to do the same but for ios, but my restriction is the cookie, Is there anyway to request a token to IDS from the native UI and then consume the authorize endpoint with this token and request a code for another client? Or if this breaks the spec how can I authenticate my native UI in order to consume authorize endpoints and make all the code PCKE flow?

I just wanna be able to open an authenticator app that will act as the website that give us back an authorization code. I have been researching so much for the web app and have success, but I have not been able to find anything related to a native ui

Closest related question would be https://github.com/IdentityServer/IdentityServer4/issues/1777

I wanna be able to provide an IDS UI for the web and a native UI so instead opening a web browser I open the native app if installed.

**Comment by TomCJones** [comment]
it's not clear what your question is. There are ways to consume a url in an app in both ios & android. Or you can check this for an example native app https://github.com/openid/AppAuth-iOS

**Comment by Jonatthu** [comment]
@TomCJones  Thanks I will take a look!

**Comment by Jonatthu** [comment]
@TomCJones So after reviewing this library, I will rephrase my question or my problem...

What I want is to replace QuickStart UI for a Native iOS QuickStart UI, so native clients instead opening a web browser can open the Native QuickStart UI

**Comment by TomCJones** [comment]
still not sure what you want.
Is it that the browser on the phone goes to the client and the client opens an app on the phone?
This is possible with uri capture, but then it is the app that controls the session,
ie. there is no going back to the same browser session on the phone.
That is the way phones work.
If you want the phone app to control the connex from the start, then you can open a web window on the phone and then the app on the phone controls the entire session.
if it is a different flow you need to explain more than you have.

**Comment by leastprivilege** [comment]
> so native clients instead opening a web browser can open the Native QuickStart UI

That's an anti-pattern, read [this](https://tools.ietf.org/html/rfc8252) first.

**Comment by Jonatthu** [comment]
@leastprivilege I have noticed that facebook opens a web browser but allows you to open their native facebook app to authorize other ios apps. 

I would like to replicate this behavior and if is possible to skip the web browser if I detect the authority app is installed.

**Comment by Jonatthu** [comment]
it would be 7.1.  Private-Use URI Scheme Redirection

**Comment by leastprivilege** [comment]
Closing as this question is not related to IdentityServer.
