### ISSUE TITLE
Host Identity server in the same application with a client

### ISSUE THREAD

**Issue by xabikos** [IdentityServer/IdentityServer4#39]
In Identity server 3 there is an option to host the server on the same application with a client. According to the official example which is [here](https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html) we can add a piece of code that looks like this 

```
app.Map("/identity", idsrvApp => 
    {
        idsrvApp.UseIdentityServer(new IdentityServerOptions
            {
                SiteName = "Embedded IdentityServer",
                SigningCertificate = LoadCertificate(),
                Factory = new IdentityServerServiceFactory()
                    .UseInMemoryUsers(Users.Get())
                    .UseInMemoryClients(Clients.Get())
                    .UseInMemoryScopes(StandardScopes.All)
        });
    });
```

And then when we navigate to the _http://myapplication.com/identity_ we could see some info about the Identity server. 

Is there something similar in Identity Server 4? I guess that this must be a configuration in IdentityServerOptions class as now we just have to do 
```
app.UseIdentityServer()
```
inside Configure method.

**Comment by brockallen** [comment]
I'm not sure I follow -- are you just asking about the "welcome" page?

**Comment by xabikos** [comment]
The scenario I am interesting in is to host the server and the client under the same application and not have the server in a separate one. In that case I am not sure how the configuration in the server should look like. In case of Identity server 3 the code on the first comment does the trick. 

Is it a bit more clear now?

**Comment by brockallen** [comment]
So this is technically possible -- i've never tried it. But you won't see anything by default in IdSvr4 if you navigate to the base path where you have IdSvr. You could inspect ~/.well-known/openid-configuration to see if the metadata is there.

**Comment by xabikos** [comment]
Yes that makes the trick. I am getting back a json response that looks like 
```
{
  "issuer":"http://localhost:5000",
  "jwks_uri":"http://localhost:5000/.well-known/openid-configuration/jwks",
  "authorization_endpoint":"http://localhost:5000/connect/authorize",
  "token_endpoint":"http://localhost:5000/connect/token",
  "userinfo_endpoint":"http://localhost:5000/connect/userinfo"
 ...
}
```
So I guess everything is in place. Thanks a lot

**Comment by brockallen** [comment]
np

**Comment by davidfaynzilberg** [comment]
How did you solved this issue?

**Comment by davidfaynzilberg** [comment]
Where did you specify "/identity"?
