### ISSUE TITLE
Login failed and can't redirect in older chrome

### ISSUE THREAD

**Issue by archeraya** [IdentityServer/IdentityServer4#3902]
Using chrome (ver63) try to login https://demo.identityserver.io failed. But it can login on the local IIS.

**Comment by brockallen** [comment]
Not enough info.

**Comment by archeraya** [comment]
Visit the site on chrome which version is 63 can see reproduce the error, It can't redirect to the logged page, like refresh the page, can't find any error in console.

**Comment by brockallen** [comment]
version 63 is quite old, no?

**Comment by archeraya** [comment]
> version 63 is quite old, no?

But some newer custom explorer using this chrome version, and it can't login in newest wechat app on some phone. It's browser kernel named x5. This project should works well in 2017 when chrome 63 published. Why it can't work now

**Comment by archeraya** [comment]
Now It works. I've done like this 
https://docs.microsoft.com/zh-cn/dotnet/core/compatibility/3.0-3.1#support-older-browsers
