### ISSUE TITLE
Azure App Service update on Sunday breaks auth on iOS12+more

### ISSUE THREAD

**Issue by rushfrisby** [IdentityServer/IdentityServer4#3904]
This is more of an announcement to those looking into the issue, as I was...

Microsoft rolled out ASP.NET Core 2.2.8 / 3.1 to Azure App Services on Sunday which breaks SameSite compatibility with iOS 12 and some other browsers. This isn't an issue with IdentityServer but IdentityServer projects hosted in Azure App Services are likely to experience the issue as a result.

The workaround can be found here - https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

Hope this helps someone save time investigating!

**Comment by leastprivilege** [comment]
thanks

@brockallen We need to put that sample cookie policy into our host - and on the demo server ASAP

**Comment by devployment** [comment]
Does the Opt-out switches work as a workaround for Azure App Services as well?

https://github.com/aspnet/Announcements/issues/390

**Comment by rushfrisby** [comment]
> 
> 
> Does the Opt-out switches work as a workaround for Azure App Services as well?
> 
> [aspnet/Announcements#390](https://github.com/aspnet/Announcements/issues/390)

I did not test this. If it works it will buy you time (~2mo) until all latest browsers roll out the new samesite spec.

**Comment by philippklautke** [comment]
Hi, 
i tested the proposed workaround and it works on Azure Web Apps

**Comment by leastprivilege** [comment]
>  If it works it will buy you time (~2mo) 

agreed.
