### ISSUE TITLE
How to pass server's authenticationTicket ExpiresUtc value as claim in accesstoken

### ISSUE THREAD

**Issue by neu-anthony** [IdentityServer/IdentityServer4#3905]
### Question / Steps to reproduce the problem
working on a project with 
an Angular2.0 UI, 
an AspNetCore3.0 WebApi 
protected by an AspNetCore3.0 IdentityServer4.

Have found that the user's session on the server will expire while they are inactive (as expected) and that the token's expiry time is not related to the server's cookie (explained elsewhere, and as expected)

I'd like to pass the server's AuthenticationTicket.Properties.ExpiresUtc value as a claim in the access_token, so the UI can read it and popup a modal dialog that asks the user if they want to extend their session when the session is a few minutes from expiry.

### Minimal working example
the below method is in a CustomTokenService which inherits from Identityerver4.Services.DefaultTokenService
```
public override async Task<Token> CreateAccessTokenAsync(TokenCreationRequest request)
{
	request.Validate();

	var authenticated = request.Subject.Identity.IsAuthenticated;  // <-- always true, as it should be

	var result = await _httpContextAccessor.HttpContext.AuthenticateAsync();

	if (result.Succeeded)  // <-- always returns false...
	{
		var expiryTime = result.Properties.ExpiresUtc?.ToLocalTime();
		request.Subject.Claims.Append(new Claim("TicketExpiry", expiryTime == null ? "" : expiryTime.Value.LocalDateTime.ToString("G")));
	}

	var accessToken = await base.CreateAccessTokenAsync(request);

	return accessToken;
}
```

Any ideas how I can get this expiry time into the token?

I have also posted on StackOverflow, but thought that you folks here might know how to easily manage this, or where I can find the properties from the AuthenticationTicket..

Thanks in advance.

**Comment by leastprivilege** [comment]
a) probably rather use the claims service, than the token service
b) check the name of your cookie handler, you need to pass that into the AuthenticateAsync method. Default names are being logged at startup

**Comment by neu-anthony** [comment]
Thanks Dominic, where do I find the name of the cookie handler?  Is it in the services.AddAuthentication().AddCookie()?  we are using services.AddIdentityServer()...etc to add the authentication to our "QuickStart" implementation.  Should we change it to AddAuthentication().AddCookie?

**Comment by neu-anthony** [comment]
@leastprivilege 
Hey Dominick,

I created a CustomClaimsService which inherits from DefaultClaimsService and overrode the GetAccessTokenClaimsAsync as you suggested, but when I call the AuthenticateAsync method my VisualStudio process just freezes on that line of code and I get nothing....
```
        public override async Task<IEnumerable<Claim>> GetAccessTokenClaimsAsync(ClaimsPrincipal subject,
            Resources resources, ValidatedRequest request)
        {
            var outputClaims = new List<Claim>();

            // first we create the claims list that would normally be generated by IdentityServer4
            outputClaims = (await base.GetAccessTokenClaimsAsync(subject, resources, request)).ToList();

            // now we add our custom claims to the list of claims

            var result = await _httpContextAccessor.HttpContext.AuthenticateAsync(IdentityServerConstants
                .DefaultCookieAuthenticationScheme);  // <-- this never returns

            if (result.Succeeded)
            {
                outputClaims.Add(new Claim("TicketExpiry", result.Properties.ExpiresUtc.Value.LocalDateTime.ToString("G")));
            }

            // finally we return our full list of claims to the calling process
            return outputClaims;
        }
```

**Comment by leastprivilege** [comment]
Re-reading this

> I'd like to pass the server's AuthenticationTicket.Properties.ExpiresUtc value as a claim in the access_token, so the UI can read it and popup a modal dialog that asks the user if they want to extend their session when the session is a few minutes from expiry.

This does not make sense. If you want to convey information to the UI - the access token is def. the wrong approach. An access token might get created when the cookie is not available (e.g. using a call to the token endoint).

You could put the session expiration into the id_token - simply add it as a claim at sign-in time and pick it up in the profile service call for id tokens.

**Comment by neu-anthony** [comment]
@leastprivilege 
Hi Dominick,
I started with the thought of using the id_token to pass the value, but then found that the id_token is not refreshed or re-sent when the js_oidc client silently refreshes, only the access token is.  Which is why we thought of using the access_token to hold this value.  
But we then found, as you stated above, that the access_token can still be requested when the cookie is not available (like on first login), which is why the AuthenticateAsync was freezing the VisualStudio debugging flow, an exception was being thrown of "Object not set to an instance of an object" which I found after adding a try/catch around the call to AuthenticateAsync.  
I haven't found a way to refresh the id_token from the js_oidc client, without forcing the user to re-enter their credentials.  Is there one?
Our design calls for this value to be refreshed every time the session on the server's expiry time slides, which isn't totally clear to me, actually, since the signinSilent in the js_oidc library uses the same id_token that was issued on login to refresh the access_token, we have found that this id_token can be expired, but still effectively be used to get a new access_token.  Does this call to signinSilent slide the server's session expiry?  
I can't be sure because the calls to the webapi seem to cause the server's session expiry to slide, but the signinSilent doesn't.  Our solution runs on three separate servers (IdSrv, WebApi, Client), and the calls to the webapi seem to call to identityserver for token validation, I think to get the signing key of the token, but the calls to the signinSilent in the js_oidc library still allow the session to timeout, if the user stops using the client/webapi.  I haven't wiresharked it to be sure, nor searched logs, as they are extensive, but since the access_token expires before the session, and the signinSilent is still fired off on a timer when the user isn't using the client site, it seems to me that the signinSilent does not slide the expiry time of the session, since it times out when the user stops using the client break over their "lunch break" or a similar amount of time. 
  
Maybe we can implement a full refresh of both tokens and extend the UserManager in the oidc_client library to provide the value of this item to the client...

**Comment by neu-anthony** [comment]
@leastprivilege 
I think we've decided that this is too complex to implement on the IdentityServer side.  I couldn't find a way to access the AuthenticationTicket for either token type and the id_token does not refresh when the js_oidc client performs a SignInSilent.

Can you let me know what type of request to IdentityServer "does/does not" cause the expiration of the AuthenticationTicket to slide?  We'll get the client to fire of a request that does when we want to force the slide, and handle the rest on the client side.

Thanks in advance.
