### ISSUE TITLE
VS2019V16.4.1  EntityFramework项目360浏览器不兼容

### ISSUE THREAD

**Issue by YeChangZhong** [IdentityServer/IdentityServer4#3906]
我把VS2019升级到 16.4.1版本后  4_EntityFramework项目用360浏览器打开后。登陆成功后不跳转！

**Comment by archeraya** [comment]
现象是360极速浏览器正常，360安全浏览器v10版不行，这个浏览器是chrome63的内核，去官网下载v11版本就可以了，那个内核是69的没这个问题，同样在手机qq浏览器和部分微信里也是一样的问题，然后尝试了多个identityserver版本，直接用63内核的浏览器登陆官网的demo也不行，我用翻译软件提了类似的issue。
This is similar to #3902

**Comment by archeraya** [comment]
Have a try 
https://docs.microsoft.com/zh-cn/dotnet/core/compatibility/3.0-3.1#support-older-browsers

**Comment by brockallen** [comment]
I'm guessing this is similar to the other issue, so I'll close for now. If it's not, then feel free to reopen, and ask the question again in English (since we can't read what's above). Thanks,
