### ISSUE TITLE
IdentityServr4(3.02)

### ISSUE THREAD

**Issue by zhanghaiboshiwo** [IdentityServer/IdentityServer4#3907]
I use IdentityServr4(3.02) to prompt the following utterance when using oidc authorization

The specified RSA parameters are not valid; both Exponent and Modulus are required fields.

That's where it went wrong
![image](https://user-images.githubusercontent.com/43592384/70770971-7c94e500-1daa-11ea-85ef-9829431f8fa3.png)

**Comment by zhanghaiboshiwo** [comment]
What is the reason

**Comment by leastprivilege** [comment]
Not enough info.

**Comment by zhanghaiboshiwo** [comment]
@leastprivilege  This is my translation of the json data 
  
  
 {"nbf":1576216462,"exp":1576216762,"iss":"http://localhost:5000","aud":"mvc","nonce":"637118129446237778.M2MxNGQ0Y2ItYjg3Yy00YjJjLTkyMjUtYTNiNGJlM2YxNWU3YTdkMjdhYTYtZWEyYi00MmVkLTlhMDgtODEyMzg3MzA0YmM5","iat":1576216266,"c_hash":"EGOx8WiK_NbJSqZUL1Kn0A","s_hash":"2ybXt4P5c2VxecKb8vTgIw","sid":"30tTyfrK-7pamP5eJ_Y9WA","sub":"1","auth_time":1576202876,"idp":"local","amr":["pwd"]}

**Comment by zhanghaiboshiwo** [comment]
Thank you. I've solved it  @leastprivilege
