### ISSUE TITLE
Ability to change token issuer on client basis

### ISSUE THREAD

**Issue by giammin** [IdentityServer/IdentityServer4#3908]
**Is your feature request related to a problem? Please describe.**
i need to generate tokens for firebase and among others things it need a custom issuer like: 
firebase-adminsdk-XXXX@XXXXXX.iam.gserviceaccount.com

and i need it without disrupting the other services that are using my authentication service so setting the [IssuerUri ](http://docs.identityserver.io/en/latest/reference/options.html) is not an option

**Describe the solution you'd like**
maybe a parameter in `UserLoginSuccessEvent`

**Describe alternatives you've considered**
creating a parallel identityserver site

**Additional context**
firebase token requirement: https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_a_third-party_jwt_library

**Comment by giammin** [comment]
at the moment I found a solution but dont know if is a good one:


```
    public class CustomTokenRequestValidator : ICustomTokenRequestValidator
    {
        public Task ValidateAsync(CustomTokenRequestValidationContext context)
        {
            context.Result.ValidatedRequest.Options.IssuerUri = "mycustomissuer";
            return Task.CompletedTask;
        }
    }
```

**Comment by brockallen** [comment]
> at the moment I found a solution but dont know if is a good one:

That doesn't look thread safe.

Why does FireBase tell you what the issuer must be? Sounds like a design flaw on their side.

**Comment by giammin** [comment]
> Why does FireBase tell you what the issuer must be? Sounds like a design flaw on their side.

I totally agree with you

**Comment by giammin** [comment]
> That doesn't look thread safe.
@brockallen isn't it instantiated for request? did not find anything in the documentation about thread safety

**Comment by klioqc** [comment]
Options is  shared between all calls

**Comment by giammin** [comment]
I thought it was just for the current call.
then it is definitely not what i need

**Comment by klioqc** [comment]
I the similar case but for multi tenancy I had to make Options transient.

**Comment by giammin** [comment]
could you tell me how you did it. just in case...

**Comment by giammin** [comment]
at least is it possible to intercept the token creation? or swap the token before sending it to the client?

**Comment by giammin** [comment]
any suggestion?
