### ISSUE TITLE
A connection attempt failed because connected host has failed to respond 

### ISSUE THREAD

**Issue by lochan717** [IdentityServer/IdentityServer4#3911]
i am getting this error after hosting the application.
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 164.XXX.XXX.XX:443. This is when client application tries to login via SSO. Can anybody help please?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
