### ISSUE TITLE
Why is acr_values not passed to POST /connect/token

### ISSUE THREAD

**Issue by natelaff** [IdentityServer/IdentityServer4#3913]
Tried to ask this on SO but figured I need to go right to this source as maybe this is an enhancement request? Or maybe there is a better way to handle this than what I'm trying.

I have a multi-tenant app (DB per tenant) with a single IS4 instance using ASP.NET Core Identity and use IPersistedGrantDbContext to push persisted grants to each database.

When I attempt to authorize I pass acr_values tenant:tenantname and determine which database to connect to-- I inspect the HttpRequest and parse this out. This all works great... up until POST /connect/token (where presumably it is also reading/writing to PersistedGrants entity). Once this post happens, I lose track of my tenant name and everything fails. It's not included in the form data that's being posted.

I don't have an authorized user at this point so I don't have the tenant claim yet.

Is there a way to push acr_values to this final post? Is there a more obvious way to do this? Thanks!

**Comment by brockallen** [comment]
It's from the OIDC spec and it's a flag parm to give hints on how to authenticate the user (e.f. MFA).

**Comment by natelaff** [comment]
Hmm so is there a better way to pass information all the way from the start to finish? This the last call that I’m struggling with getting the necessary information of which db I’m trying to authenticate against in this multi tenant environment.

**Comment by natelaff** [comment]
Ok, so setting a cookie doesn't work because of #3914 but I was able to get around the invalid grant error by using a separate db for grants. However, I still have the same issue essentially because /connect/token seems to be when ProfileService is invoked, so I still don't have the right database.

Any suggestions here? Surely I'm not the only person to have ever tried a user store in a database per tenant model. Can you pass the original request in the header or connect/token or something just so we can get to it for this purpose?

**Comment by natelaff** [comment]
For the record I ended up going a completely different route and implementing IEndpointRouter to add a path segment. i.e. https://localhost:5000/tenantname which seems to work well. It requires a separate authority for each tenant, which is proving difficult to deal with in ASP.NET Core web app (can't set Authority dynamically based on context.) but so far this has proved to be the only solution where I can consistently get the token all the way through the flow.

Any other official thoughts on this would be helpful. In general some kind of multi-tenancy guidance would be good. I still don't understand why I couldn't get to that arc_values in the final /connect/token call. One small thing would have made this much easier.

**Comment by brockallen** [comment]
acr_values is not a param from the spec for the token endpoint.

**Comment by natelaff** [comment]
So in your personal opinion what's the best way to deal with this if you don't mind the question.

It's an ASP.NET Core Identity based app, with database per tenant. Tenant is identified by subdomain. IEndpointRouter works, but then complicates the authority.

**Comment by brockallen** [comment]
It's hard to say and that's usually a consulting type of discussion because it might require some involved architecture. But one idea is to issue the tenant in a claim on the authorize endpoint so it's available in the token endpoint. YMMV :)

**Comment by natelaff** [comment]
Well that's what I was trying to do with acr_values ;) But because by the time I get to the token issuing I lose track of the tenant. At which point there was no way to connect to the proper database.

**Comment by thePmr** [comment]
> acr_values is not a param from the spec for the token endpoint, only the authorize endpoint.
But your [docs](http://docs.identityserver.io/en/latest/endpoints/token.html) say that token endpoint can accept `acr_values`?

**Comment by brockallen** [comment]
> But your docs say that token endpoint can accept acr_values?

So they do, which is a surprise to me, TBH. @leastprivilege might have added it at some point, specifically for the `password` grant type (which is also what the docs indicate)?
