### ISSUE TITLE
I am getting error 401 when I have client machine with don`t combine serverdate 

### ISSUE THREAD

**Issue by marcusmleite** [IdentityServer/IdentityServer4#3916]
I am getting error 401 when I have client machine with wrong date compared to server date. After I correct the date on the client machine I have authorized the token. Is there any configuration in identity server that I can eliminate this delay

**Comment by leastprivilege** [comment]
No. Your clocks needs to be reasonably in sync.

If you are using the Microsoft libraries on the client, you get an allowed clock skew of 5 minutes by default. This value is configurable.
