### ISSUE TITLE
deploy identity server on Google Cloud

### ISSUE THREAD

**Issue by henryyue2010** [IdentityServer/IdentityServer4#3917]
### Question / Steps to reproduce the problem

During development, I use http://localhost:5000 as discovery endpoint, everything works fine. But after deploying the application on Google Cloud, the identity server doesn't work very well. 

The application on the google cloud uses https, but the urls in /.well-known/openid-configuration are all http. 

```
 "issuer":"http://optimum-octane-xxxxxx.appspot.com",
"jwks_uri":"http://optimum-octane-xxxxxx.appspot.com/.well-known/openid-configuration/jwks",
"authorization_endpoint":"http://optimum-octane-xxxxxx.appspot.com/connect/authorize",
"token_endpoint":"http://optimum-octane-xxxxxx.appspot.com/connect/token"
......
```

I tried http://optimum-octane-xxxxxx.appspot.com and https://optimum-octane-xxxxxx.appspot.com as the discovery endpoint in my code, but both don't seem to work. Does anyone know how to make the identity server work on Google Cloud?

Thank you very much in advance for your help.

**Comment by sbebrys** [comment]
GCP use loadbalacer before Your app (as I think it is deployed on AppEngine) and cover your http server https reverse proxy. So this proxy pass to Your server orgin address and scheme in headers: https://cloud.google.com/appengine/docs/flexible/dotnet/reference/request-headers.

Your app doesn't consume `X-Forwarded-Proto` header, in .net core is MS package to do that: [Microsoft.AspNetCore.HttpOverrides](https://www.nuget.org/packages/Microsoft.AspNetCore.HttpOverrides/)

Up to .Net Core 2.2 You must attach this middleware or filter by hand, from .Net Core 3.0 it is used by default: https://github.com/aspnet/AspNetCore/blob/1480b998660d2f77d0605376eefab6a83474ce07/src/DefaultBuilder/src/WebHost.cs#L240
