### ISSUE TITLE
Password Policy not applying on user update

### ISSUE THREAD

**Issue by mayankgaur** [IdentityServer/IdentityServer4#3919]
I have a case I creating a user with default password and then giving an activation link to user for Updating Password. For Updating Password I am just Updating user by UserManager 
my code is below 
`  applicationUser.PasswordHash = password;
                _userManager.UpdateAsync(applicationUser);`

and I have setup Password policy in StartUp.cs class like below
` services.AddIdentity<ApplicationUser, IdentityRole>(options =>
            {
                options.User.RequireUniqueEmail = true;
                options.Password.RequiredLength = 8;
                options.Password.RequiredUniqueChars = 3;
                options.Password.RequireDigit = true;
                options.Password.RequireLowercase = true;
                options.Password.RequireUppercase = true;
            })`

but user is creating without using any password policy. 
Please let me know if am doing anything wrong.

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
