### ISSUE TITLE
Public app should not require a 'client_secret' on token request.

### ISSUE THREAD

**Issue by cboyce428** [IdentityServer/IdentityServer4#3920]
I am creating a “public” app (android app in play store), whereby the client_secret could be discovered by someone determined.

Currently a 'client_secret' is required to get a token even when the redirect_uri is not a web URL e.g.  'myappname://callback' which would be linked to an event listener within android.

Can I suggest you change this behaviour, other OAuth servers return an error such as, to prevent accidental leakage if the redirect_url does not start with "http://" or "https://" 

{"error":"invalid_request","error_description":"Public clients can't send a client secret.","correlation_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}

**Comment by brockallen** [comment]
That's why there's a config setting called `RequireClientSecret`, which you can find in our docs: http://docs.identityserver.io/en/latest/reference/client.html

**Comment by cboyce428** [comment]
Thanks for the link much appreciated. Was confused by the error as it said just "invalid client_id" & the client_id was valid.

Now works great.
