### ISSUE TITLE
Reference to non existent source code

### ISSUE THREAD

**Issue by gph2000** [IdentityServer/IdentityServer4#3921]
I had an exception where some careless cut and paste led me to attempt getting a machine-to-machine token in a situation where it made no sense.
This was part of the exception:
INFO  17-12-2019 18:20:28 Executing action method CentralMessageDistributionService_CoreAPI.Controllers.DistributeController.UpdateRegistration (CMDS) - Validation state: Valid
INFO  17-12-2019 18:23:00 Exception: Object reference not set to an instance of an object. has occurred generating Machine-to-machine token
ERROR 17-12-2019 18:23:00    at IdentityModel.Client.HttpClientDiscoveryExtensions.GetDiscoveryDocumentAsync(HttpClient client, DiscoveryDocumentRequest request, CancellationToken cancellationToken) in **C:\local\identity\model\IdentityModel2\src\Client\New\HttpClientDiscoveryExtensions.cs**:line 48
   at IdentityModel.Client.HttpClientDiscoveryExtensions.GetDiscoveryDocumentAsync(HttpClient client, String address, CancellationToken cancellationToken) in **C:\local\identity\model\IdentityModel2\src\Client\New\HttpClientDiscoveryExtensions.cs:**line 27
   at CentralMessageDistributionService_CoreAPI.Controllers.DistributeController.GetToken(String localMessageHandlerName) in C:\OneDrive\SBSB\projects\CentralMessageDistributionService_CoreAPI\CentralMessageDistributionService_CoreAPI\Controllers\DistributeController.cs:line 272

There are no source files in my system for the path beginning "C:\local\IdentityModel2"

Note, this is not blocking me so if it is a not a valid issue it may be closed.

**Comment by cboyce428** [comment]
Just a FYI this seems to be a dependency project of https://github.com/IdentityModel/IdentityModel

**Comment by gph2000** [comment]
True, I've raised it because the authors may not be aware that line numbers from it are appearing in exceptions where it is deployed as a nuget package.

**Comment by leastprivilege** [comment]
Isn't that normal when you provide symbols?

**Comment by gph2000** [comment]
No, I would mask details like this behind a generic error message for artifacts packaged as nuget and for that matter in any production code. Are you or Dominic concerned by the occurrence of this particular null reference exception, and the resultant output from the IdentityModel nuget package? If not, then we should close this ticket.
