### ISSUE TITLE
DeviceController Error reference 

### ISSUE THREAD

**Issue by juank52009** [IdentityServer/IdentityServer4#3922]
Severity	Code	Description	Project	File	Line	Suppression State

Error	CS0246	The type or namespace name 'IDeviceFlowInteractionService' could not be found (are you missing a using directive or an assembly reference?)	Marvin.IDP	

C:\securing-aspdotnet-core2-oauth2-openid-connect\02\demos\start-end\ImageGallery\src\Marvin.IDP\Quickstart\Device\DeviceController.cs

![Error_1](https://user-images.githubusercontent.com/18407942/71035297-2648de80-20e9-11ea-9c6f-6fb2ced54125.png)

**Comment by scottbrady91** [comment]
IDeviceFlowInteractionService is in the IdentityServer4.Services namespace from v2.3 onwards
