### ISSUE TITLE
Wrong parameter name for user code in quickstart DeviceController

### ISSUE THREAD

**Issue by thomaslevesque** [IdentityServer/IdentityServer4#3923]
### Issue / Steps to reproduce the problem

- Make a device authorization request
- Open the `verification_uri_complete` in the browser
- The page ignores the user code in the query string and prompts the user to enter it

The problem is that the controller expects the parameter name to be named `user_code`, but it's actually named `userCode` in `verification_uri_complete`.

I realize that it's configurable, but the quickstart controller should match the default name, or use the name from the options. Maybe something like this:

```diff
         [HttpGet]
-        public async Task<IActionResult> Index([FromQuery(Name = "user_code")] string userCode)
+        public async Task<IActionResult> Index([FromServices] IOptions<IdentityServerOptions> options)
         {
+            string userCodeParamName = options.Value.UserInteraction.DeviceVerificationUserCodeParameter;
+            string userCode = Request.Query[userCodeParamName];
             if (string.IsNullOrWhiteSpace(userCode)) return View("UserCodeCapture");

             var vm = await BuildViewModelAsync(userCode);
```

### Relevant parts of the log file

N/A

**Comment by leastprivilege** [comment]
thanks! PR?
