### ISSUE TITLE
Set Access Token Life as openended

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3924]
Hi,

I wanted to set the access token lifetime as open-ended for the specific request in CustomAuthorizeRequestValidator middle ware.

Currently we can able set the access token life time as any integer value but not able set null value in it. 

Please kindly provide the solution for this issue.

**Comment by leastprivilege** [comment]
The expiration value is a mandatory field in the generated token (JWT).

**Comment by Sathiyanathan-Macro** [comment]
I'm using reference token not the JWT token.

**Comment by leastprivilege** [comment]
int.MaxValue would not work?

**Comment by Sathiyanathan-Macro** [comment]
Thanks least, 

it's working
