### ISSUE TITLE
IdentityServer4.AspNetIdentity dependency from Microsoft.AspNetCore.Identity

### ISSUE THREAD

**Issue by CesarD** [IdentityServer/IdentityServer4#3927]
I'm updating a project that used IdentityServer4.AspNetIdentity 2.4.0 and now when jumping to latest version, I notice the nuget doesn't have the Microsoft.AspNetCore.Identity dependency anymore.

I would like confirmation about this and, should I add the MS nuget separately? Is there some "breaking changes" changelog regarding any other changes between versions of these libraries?

Thanks!

**Comment by leastprivilege** [comment]
IIRC it is included now by default.

**Comment by CesarD** [comment]
I had to add it separetely with the latest version of the nuget.

And apparently the code doesn't show it referenced:

https://github.com/IdentityServer/IdentityServer4/blob/9048ac2684ace1f95c76f132681243d1588ebfc2/src/AspNetIdentity/src/IdentityServer4.AspNetIdentity.csproj#L36

**Comment by leastprivilege** [comment]
As I said - i think it is reference by this 

https://github.com/IdentityServer/IdentityServer4/blob/9048ac2684ace1f95c76f132681243d1588ebfc2/src/AspNetIdentity/src/IdentityServer4.AspNetIdentity.csproj#L31-L33
