### ISSUE TITLE
How to authorize SignalR websocket transport when using AddLocalApiAuthentication

### ISSUE THREAD

**Issue by vunguyen-dmt** [IdentityServer/IdentityServer4#3929]
I've seen the CustomTokenRetriever token way. But I don't know how to config it with AddLocalApiAuthentication.

In my startup I used: services.AddLocalApiAuthentication().

I am trying to use the method mentioned in this issue: https://github.com/IdentityServer/IdentityServer4/issues/2349

**Comment by leastprivilege** [comment]
We don't have a customizable way to retrieve tokens right now.
