### ISSUE TITLE
Don't want password users to have to grant access

### ISSUE THREAD

**Issue by futzy314** [IdentityServer/IdentityServer4#393]
First off, I'm still pretty new to this, so I'm sorry if it's a dumb question, but I couldn't figure it out.  I have a set up working where users can either choose to create a local account with an email and password, or they can use their Google identity.  Now I understand why if they use a Google identity they need the screen that says, "Yes, I allow this site to access this, this, and this from my Google profile."  But for users that create a local account, it currently pops up the same thing in the flow, and it just seems silly that a user just created a new account for our site and immediately we have to ask them to grant us access to that profile.  Is there a way to automate that step just for password users but not for external IdP users?

**Comment by leastprivilege** [comment]
RequireConsent on the Client class controls this. 

Get Outlook for iOS




On Sun, Oct 9, 2016 at 9:26 PM +0200, "futzy314" <notifications@github.com> wrote:












First off, I'm still pretty new to this, so I'm sorry if it's a dumb question, but I couldn't figure it out.  I have a set up working where users can either choose to create a local account with an email and password, or they can use their Google identity.  Now I understand why if they use a Google identity they need the screen that says, "Yes, I allow this site to access this, this, and this from my Google profile."  But for users that create a local account, it currently pops up the same thing in the flow, and it just seems silly that a user just created a new account for our site and immediately we have to ask them to grant us access to that profile.  Is there a way to automate that step just for password users but not for external IdP users?
