### ISSUE TITLE
Consider ignoring an explicit offline_access scope in client credentials flow

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3930]
Right now we are rejecting the request - maybe ignoring it is good enough.

**Comment by scottbrady91** [comment]
I prefer rejecting. This is not allowed at the spec level and it stops people getting frustrated when they don't receive the refresh token they asked for. After all, who checks the logs.

**Comment by leastprivilege** [comment]
Well - strictly speaking client creds is an OAuth concept - and OAuth has no notion of an offline_access scope...

But yes - this is open for discussion ;)

**Comment by brockallen** [comment]
For consistency, it seems that we want all invalid, non existent, or not allowed scopes requested to have the same behavior. Lazy clients should be less lazy :P
