### ISSUE TITLE
How to protect APIs of external PHP web application with IdentityServer?

### ISSUE THREAD

**Issue by biapar** [IdentityServer/IdentityServer4#3933]
I've a PHP application. I wish to centralize AA on IdentityServer. How to protect APIs of external PHP web application?

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!

**Comment by biapar** [comment]
Done. https://stackoverflow.com/questions/59451402/how-to-protect-apis-of-external-php-web-application-with-identityserver
