### ISSUE TITLE
Silent renew and refresh tokens

### ISSUE THREAD

**Issue by mbachaalani** [IdentityServer/IdentityServer4#3934]
Hello,

The concept of silent renew and refresh tokens gets me a bit confused.
First for the access token if it is stolen and have an expiry date. From the time it is sent from another browser (the ones of the person who stole it) what is the difference between the user who authenticated first and the other one who is sending request from another browser, if the request is sent with the token that did not expire yet, is there other information that are sent to the server that identify the authenticated user. Also how the silent renew and refresh token makes it more secure in case of stealing?

Thank you.

**Comment by manfredsteyer** [comment]
You are right. Per se, it's not much safer than the access token. Hence, originally it was forbidden in the browser. The [current best practices document](https://oauth.net/2/oauth-best-practice/) tells us, we might use it in the browser under specific circumstances. One thing the demand us to do is making the refresh token a one time token. If it is used more than once, all users who used it have to be logged out. Also, you have to take care about XSS (they demand it indirectly). Another interesting aspect is, that it is not send on a regular basis via the network like the access_token.

The safest way to store an refresh_token is IMHO still a HTTP-only cookie. However, this leads quite often to iframe tricks which are not nice to debug.
