### ISSUE TITLE
Missing Claims ;(

### ISSUE THREAD

**Issue by patsadow2** [IdentityServer/IdentityServer4#3936]
Frontend ask IdentityServer and then Frontend ask WebApi

I get only that claims in JWT but i want more for example email and customIdentityScope claims

email: Bob,
customIdentityScope: RandomKey

![image](https://user-images.githubusercontent.com/19226186/71326274-e757c600-24f8-11ea-9e52-6e77a48d38b8.png)

What is wrong that this is missing should i ask somehow WebApi to IdentityServer for additional claims with value {email: Bob} etc ???

Please help ;(

**Comment by brockallen** [comment]
I'm not sure what the real question is, but maybe this will help: https://brockallen.com/2019/02/25/scope-and-claims-design-in-identityserver/.
