### ISSUE TITLE
IntrospectionResponseGenerator ProcessAsync method returns scopes which are specified in calling ApiResource (but must return all scopes that token contains)

### ISSUE THREAD

**Issue by hovhanneskarapetyan** [IdentityServer/IdentityServer4#3946]
why this line is added in PocessAsync method 

```
 var allowedScopes = validationResult.Api.Scopes.Select(x => x.Name);
            var scopes = validationResult.Claims.Where(c => c.Type == JwtClaimTypes.Scope).Select(x => x.Value);
            scopes = scopes.Where(x => allowedScopes.Contains(x));
            response.Add("scope", scopes.ToSpaceSeparatedString());
```

scopes = scopes.Where(x => allowedScopes.Contains(x)); this line must be **removed**

**Comment by leastprivilege** [comment]
why?

**Comment by hovhanneskarapetyan** [comment]
if client who knows ApiSecret and wants to know in which scope token is genereted, how can he do that ?

**Comment by leastprivilege** [comment]
A resource should only see the scope it belongs to. That according to the spec iirc. 

If you don’t like this behavior, feel free to replace the response generator.

**Comment by hovhanneskarapetyan** [comment]
according to spec
https://tools.ietf.org/html/rfc7662

Introspection response section 2.2


   scope
      OPTIONAL.  A JSON string containing a space-separated list of
      scopes associated with this token, in the format described in
      Section 3.3 of OAuth 2.0 [RFC6749].

**Comment by hovhanneskarapetyan** [comment]
there is also 
“ The authorization server MAY respond differently to different
   protected resources making the same request.  For instance, an
   authorization server MAY limit which scopes from a given token are
   returned for each protected resource to prevent a protected resource
   from learning more about the larger network than is necessary for its
   operation.”

you mean this ?

**Comment by leastprivilege** [comment]
yes
