### ISSUE TITLE
Why does IdentityServer4 use cookies?

### ISSUE THREAD

**Issue by connelhooley** [IdentityServer/IdentityServer4#3949]
### Question / Steps to reproduce the problem
I noticed in the example apps/templates that the `AccountController` and `ExternalController` both store a cookie to track signed in users. I thought one of the main differences of OIDC/OAuth (compared to traditional sign ins) was to use JTWs in request headers instead of cookies. Is that assumption wrong? Are cookies still used with OIDC/OAuth?

I notice with other auth providers like Auth0, they use the header approach:

https://auth0.com/docs/quickstart/spa/react/02-calling-an-api#call-the-api

Also GitHub:

https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#response

What I really want is an OAuth API that hosts the login page `auth.example.com/login`, this will return a JWT that can be used to make requests to `api.example.com/orders`. Internally `auth.example.com/login` will call `api.example.com/auth/login`. I just really want the complex OAuth stuff split out, I don't want any presentation logic in `api.example.com` and I only want one API to access the underlying database.

I can use cookies that work on sub domains but I'm not sure what the security ramifications may be with that. I was just why the recommended/default practice is to use cookies?

### Minimal working example

Taken from `AccountController` in `is4ui` template:

``` c#
// issue authentication cookie with subject ID and username
await HttpContext.SignInAsync(user.SubjectId, user.Username, props);
```

**Comment by connelhooley** [comment]
Looks like there's extra config to use JWTs instead of cookies:

http://docs.identityserver.io/en/latest/topics/apis.html

Would be great if there was a template for this too.

**Comment by hsb0307** [comment]
I have the same enquiries too

**Comment by leastprivilege** [comment]
> IdentityServer4 gives the client a cookiewhen they sign in. This cookie is then swapped for a JWT token using OIDC or OAuth2. So the cookie will be for auth.example.com and that is fine as the client will use that URL to get a token that works wherever I configure it to.

Exactly. Please read the OIDC spec for more details.
