### ISSUE TITLE
Best practice for multiple apps with same users

### ISSUE THREAD

**Issue by malballah** [IdentityServer/IdentityServer4#3950]
I am asking about the best practice when I have a single application but can be deployed to different domains with different features and different databases and a single user may have an account on both domains so the user information will be repeated, so is it a best practice to create one database with asp.net identity tables and the identity server connect to this database and authenticate all users from this database? 
The question again is it good to put the asp.net identity tables at the identity server or at the client apps?

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
