### ISSUE TITLE
ApptoApp Authentication

### ISSUE THREAD

**Issue by Sathiyanathan-Macro** [IdentityServer/IdentityServer4#3954]
Hi,

Currently, We have developed the OAuth Server using identityserver4 and it support browser based authentication.

Do you have any code sample for ApptoApp Authentication?

I need to implement the below process.

1. Third Party App Calls the Authorize endpoint with signed jwt request.
2. I have configured my Android application to open the app when the user calls the authorize endpoint (using Deeplink configuration).
3. I have to validate the jwt request if it valid then consent journey is takes place within the app.
4. If the customer agrees the consent, then we should call some API which was configured in the OAuth Server and get authorisation result and redirect back to Third Party App.

Kindly assist me to implement the ApptoApp Redirection in Our OAuth Server.

**Comment by leastprivilege** [comment]
This seems to be a general question - not a bug report or a feature request. 

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html) for more details.

Thanks!
