### ISSUE TITLE
Implement resource indicator spec

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#3958]
https://tools.ietf.org/html/draft-ietf-oauth-resource-indicators-08

this is our interpretation of how it works in IdentityServer

**a) no resource parameter, scope parameter**
* all resources requiring indicator are excluded
* AllowedScopes works as today
* same behavior as today + if scope is defined in multiple resources, then you'll get multiple audiences

**b) resource parameter, scope parameter**
* all resources that match the resource parameter(s) are used
* must use new AllowedResources config setting
* get one access token per resource with downscoped behavior
    * if a requested scope is not present in any resource -> invalid_target
    * if a requested scope is not present in one or more resource
        * if resource has no scopes defined -> access token without scopes
        * if resource has scopes defined -> invalid_target

**c) resource parameter, no scope**
* all resources that match the resource parameter(s) are used
* must use new AllowedResources config setting
* get one access token per resource with no scopes if resource has no scopes defined

**Comment by brockallen** [comment]
New config idea:
* Scopes top level
* ApiResource contains list of scope names (reference model, not ownership model)

Config: no resources, only scopes
Request: no resource, scope
* Aud is scope
* No introspection possible

Config: resources and scopes
Request: no resource, scope
* Aud is matching ApiResources
* Introspection based on ApiResource secret

Config: resources and scopes
Request: resource, no scope
* Aud is matching ApiResources
* Introspection based on ApiResource secret

Config: resources and scopes
Request: resource and scope
* Aud is matching ApiResources
* Introspection based on ApiResource secret

**Comment by BoggsSystems** [comment]
Need any assistance implementing this?  Very interested
