### ISSUE TITLE
/connect/endsession from SPA client - missing logoutId

### ISSUE THREAD

**Issue by pedershk** [IdentityServer/IdentityServer4#396]
I've been following 
https://damienbod.com/2016/03/02/angular2-openid-connect-implicit-flow-with-identityserver4/

to implement IdentityServer4 for a SPA application. We also have several resource backends, but those are not relevant here, I believe.

Everything seems to work fine, except for one thing - I cannot for the life of me get logout to work.

Here's the code that's run from securityService.ts as per the blog post above:

(never mind the additional TS services and variables - the url is correctly formed)

```
public logoff() {
        // /connect/endsession?id_token_hint=...&post_logout_redirect_uri=https://myapp.com
        console.log("BEGIN Logoff, no auth data");

        const idTokenHint = this._storageService.retrieve("authorizationDataIdToken");

        this._resourceService.getService(ResourceService.authorizationUrl)
            .subscribe((authorizationUrl: string) => {
                this._resourceService.getService(ResourceService.fagsystem)
                    .subscribe((fagsystem: string) => {
                        const url = authorizationUrl + "/connect/endsession" + "?" +
                            "id_token_hint=" + encodeURI(idTokenHint) + "&" +
                            "post_logout_redirect_uri=" + encodeURI(fagsystem + "/");

                        this.resetAuthorizationData();
                        window.location.href = url;
                    });
            });
    }
```

The /connect/endsession call redirects (302) to /account/logout - a GET method in the AccountController. I've implemented this from the sample repos. The Get method should call the POST method, which it doesn't - it redirects to the Logout.cshtml view because no logonId is set.

```
/// <summary>
        /// Show logout page
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Logout(string logoutId)
        {
            var context = await _interaction.GetLogoutContextAsync(logoutId);
            if (context?.ClientId != null)
            {
                // if the logout request is authenticated, it's safe to automatically sign-out
                return await Logout(new LogoutViewModel { LogoutId = logoutId });
            }

            var vm = new LogoutViewModel
            {
                LogoutId = logoutId
            };

            return View(vm);
        }

        /// <summary>
        /// Handle logout page postback
        /// </summary>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(LogoutViewModel model)
        {
            // delete authentication cookies
            await _signInManager.SignOutAsync();

            // set this so UI rendering sees an anonymous user
            HttpContext.User = new ClaimsPrincipal(new ClaimsIdentity());

            // get context information (client name, post logout redirect URI and iframe for federated signout)
            var logout = await _interaction.GetLogoutContextAsync(model.LogoutId);

            var vm = new LoggedOutViewModel
            {
                PostLogoutRedirectUri = logout?.PostLogoutRedirectUri,
                ClientName = logout?.ClientId,
                SignOutIframeUrl = logout?.SignOutIFrameUrl
            };

            return Redirect(vm.PostLogoutRedirectUri);
            //return View("LoggedOut", vm);
        }
```

Question - why isn't the logout ID passed along to the Logout method from /connect/endsession?

Am I missing something on the /connect/endsession call?

**Comment by brockallen** [comment]
check the logs

**Comment by pedershk** [comment]
Sorry. I'll go hide now. I'd overlooked the blatant error of forgetting to add a "/" to the post_logout_redirect_urls.

**Comment by farshid3003** [comment]
I upgrade my client from 1.0.0 to 1.1.0 and now logoutId  is null in the server

**Comment by DermotAtPimss** [comment]
That's happened to me also, after an upgrade logoutId is null.

It's easy to reproduce... Upgrade the Quickstart6_AspNetIdentity MvcClient to 1.1.0:

"Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },

Now use NuGet to update packages ...

**Comment by brockallen** [comment]
I just tried to repro on the quickstart as you suggested, and it's working for me. Did you remember to update the `PostLogoutRedirectUris` to now have `/signout-callback-oidc` as the suffix? That's a change from 1.0 to 1.1 from Microsoft: 

```
PostLogoutRedirectUris = { "http://localhost:5002/signout-callback-oidc" }
```

**Comment by DermotAtPimss** [comment]
Thank you Brock Allen!!!

You are right.

**Comment by pmaheshgupta** [comment]
hi can any one let me know what is the fix for the mentioned issue -- logoutid not available for implicit flow?? I am also facing the same issue ? how is the logoff happening even though there is no logoutid?

**Comment by ttajic** [comment]
Hello!

I am also having implicit flow (asp.net mvc) client with Cookies SignInScheme and IdentityServer 1.5.1 with custom local identity provider.

No logoutid is passed from client to server Logout action and therefore no client context is retrieved where PostLogouRedirectUris and other data is defined.

I am apparently misunderstanding the concept, because I doubt this is a bug. I do not know how the client would know what the logoutId is anyway. I can see in sample IdSrv host app, that it creates logoutId but only for external providers, with extra roundtrip. Should this be done for local providers also.

please point me to the right direction as I am kind of lost.

My Client config:

            app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",
                PostLogoutRedirectUri = string.Format("{0}/signout-callback-oidc", Constants.ClientUrl),
                //DEVELOPMENT Authority
                Authority = "https://localhost:44345",
                RequireHttpsMetadata = false,                              
                ClientId = Constants.ClientId,
                ResponseType = "id_token",
                Scope = { "openid", "profile", "email", "contact" },
                SaveTokens = true,

                TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    RoleClaimType = "role",
                },
...

I've got http://localhost:44077/signout-callback-oidc defined as PostLogouRedirectUris, but like I've said the problem is actually not reading the client data from Context....

Regards,
Tom

**Comment by brockallen** [comment]
`PostLogoutRedirectUri ` is set for you automatically in the MW, so no need to set it explicitly.

**Comment by cosmoKenney** [comment]
@brockallen what does this mean?:
> PostLogoutRedirectUri is set for you automatically in the MW, so no need to set it explicitly.
If you look at the configurations in the docs [here](http://docs.identityserver.io/en/release/quickstarts/7_javascript_client.html#add-your-html-and-javascript-files), and [here](http://docs.identityserver.io/en/release/quickstarts/7_javascript_client.html#add-a-client-registration-to-identityserver-for-the-javascript-client)
They show the js client redirect as index.html:
`PostLogoutRedirectUris = { "http://localhost:5003/index.html" },`

**Comment by brockallen** [comment]
I was referring to the ASP.NET OIDC security handler -- IOW, the client side component, not IdentityServer's config.
