### ISSUE TITLE
SecurityTokenInvalidSignatureException encountered when using "AddDeveloperSigningCredential"

### ISSUE THREAD

**Issue by TheMagnificent11** [IdentityServer/IdentityServer4#3963]
### Question / Steps to reproduce the problem

I created an IdentitySever4 ASP.Net Core 3.1 website using the EF template (http://docs.identityserver.io/en/latest/quickstarts/5_entityframework.html) and modifying it (template created using .Net Core 3, but I upgrade it to 3.1 and upgraded all the NuGet packages as well).  It seeds a API Resource and Client with a secret for client-credentials acccess on startup.

I the identity configuration is signed using the `AddDeveloperSigningCredential` extension method (this is currently only local development).

I create an API project (the one linked to the API Resource that is seeded at startup) and configured it as mentioned in the quick start guide (http://docs.identityserver.io/en/latest/quickstarts/1_client_credentials.html).

I request the token from the Identity Server using client credentials and then try to do a post to the API, but it encounters a `SecurityTokenInvalidSignatureException`.

### Working example

The full code is available at the tag: https://github.com/TheMagnificent11/identity-server-admin/tree/Github-SecurityTokenInvalidSignatureException-Issue

### Relevant parts of the log file

```
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
Exceptions caught:
 '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
token: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
```

**Comment by leastprivilege** [comment]
did you follow https://aka.ms/IdentityModel/PII ?

**Comment by TheMagnificent11** [comment]
I turned it on and it showed up some strange claims in the token.

Turns out the issue was my Postman collection.  I was saving the token in an environment variable and the same variable was set as global variable in another collection.

Thanks.
