### ISSUE TITLE
Please support Windows authentication with the Microsoft.AspNetCore.Authentication.Negotiate  package

### ISSUE THREAD

**Issue by RaulRG** [IdentityServer/IdentityServer4#3964]
It would be great if we could use Windows Authentication with Kestrel (and without IIS). We've got a very big application as a Windows service that will use ASP.NET Core 3 for providing a web API. 
It should support Windows Authentication, but for this we have currently 2 options:
- Kestrel behind IIS
- HTTP.sys
The first one does not work for us, and we would love to use Kestrel for it. 

**Describe the solution you'd like**
Support for Microsoft.AspNetCore.Authentication.Negotiate package. Currently at version 3.1.0 and supporting Windows, Linux and MacOS.
This would allow us to even use a docker image with our software and Windows Authentication.

**Comment by leastprivilege** [comment]
There is nothing IdentityServer needs to do to support this. It's a matter of configuration of the hosting application - just like any other authentication method.

**Comment by RaulRG** [comment]
Thank you for the clarification, Dominick. The documentation for IdentityServer states that for Windows Authentication you could use the both methods I wrote above. I (wrongly) assumed that this eliminated any other possibility.

**Comment by leastprivilege** [comment]
Oh yes - the docs are pre-Negotiate handler. Feel free to add a comment.
