### ISSUE TITLE
Do not Sha256() they GrantType in DefaultGrantStore

### ISSUE THREAD

**Issue by clearwaterstream** [IdentityServer/IdentityServer4#3967]
**Is your feature request related to a problem? Please describe.**
I need to store my transient or short lived tokens in Redis, and my long lived refresh tokens in a DB. My refresh tokens may live for 180 days (I know it's too long, but there it is). I've created my own implementation of `IPersistedGrantStore`. Problem is, in the `GetAsync()` method I am only given the key, and I do not know if I'm pulling a refresh token, an access token, or what have you. The interesting part is the type of token IS embedded in the key, it's just the key is hashed and therefore I cannot extract that info. If I have this info, I can go to Db for refresh_tokens and to Redis for everything else. There is a way to accomplish this today, but it involves a bit of code. Not much, but I think this could be simply be achieved by allowing the keys not to be hashed. Also, I am not sure why GrantType needs to be hashed anyway (nothing sensitive there).

**Describe the solution you'd like**
```csharp
// https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Stores/Default/DefaultGrantStore.cs
protected virtual string GetHashedKey(string value)
{
	// return (value + KeySeparator + GrantType).Sha256(); // current impl

       return value.Sha256() + KeySeparator + GrantType;
}
```

**Describe alternatives you've considered**
I could derive from `DefaultGrantStore` and overload the virtual `GetHashedKey()` method where I would skip the Sha256().  I would then have to create and register `class MyRefreshTokenStore : MyGrantStore<RefreshToken>, IRefreshTokenStore`. Doable, but I would like to avoid this work if possible.

Thank you!!!

**Comment by brockallen** [comment]
You can always implement the more specific stores like the IRefreshTokenStore.

**Comment by clearwaterstream** [comment]
> 
> 
> You can always implement the more specific stores like the IRefreshTokenStore.

Looking at [DefaultRefreshTokenStore](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Stores/Default/DefaultRefreshTokenStore.cs) I don't think I need to change anything. What I do need, is an ability to somehow hint to the `DefaultRefreshTokenStore` that I need to use a very specific `IPersistedGrantStore` implementation. An implementation that may differ than the one used in `DefaultAuthorizationCodeStore` for example.

Right now, I can supply my own implementation of `IPersistedGrantStore` via

```csharp
var persistedGrantStoreDesc = new ServiceDescriptor(typeof(IPersistedGrantStore), typeof(MyPersistedGrantStore), ServiceLifetime.Singleton);

services.Replace(persistedGrantStoreDesc);
```
I guess one way I can achieve this is to derive from DefaultRefreshTokenStore and pass the whatever implementation of `IPersistedGrantStore` to the base constructor. That will work -- but I will be hardcoding the dependency, and not using the "DI way". Anyhow, Sha256() no longer seems like a good option anyhow, so I will close this.

Thank you for the help!
