### ISSUE TITLE
Single-item-claim-array when using ClaimValueTypes.Json still changing schema

### ISSUE THREAD

**Issue by azydevelopment** [IdentityServer/IdentityServer4#3968]
### Issue / Steps to reproduce the problem

Related to issue #2468.

Using an ASP.NET + React based project with Individual Account user authentication/authorization.

Here's my IProfileService::GetProfileDataAsync implementation which does let me add claims to the final issued JWT:

```csharp
public Task GetProfileDataAsync(ProfileDataRequestContext context)
{
    // Get all the roles associated with this subject
    IEnumerable<Claim> roleClaims = context.Subject.FindAll(JwtClaimTypes.Role);

    // Put those roles into a list so we can serialize them after
    IList<string> roles = new List<string>();
    foreach (Claim roleClaim in roleClaims)
    {
        Debug.Assert(roleClaim.Type == JwtClaimTypes.Role);

        roles.Add(roleClaim.Value);
    }

    // Serialize the roles into JSON
    string rolesJson = JsonSerializer.Serialize(roles);

    // Put the roles JSON into an actual Claim object
    Claim claim = new Claim(JwtClaimTypes.Role, rolesJson, IdentityServerConstants.ClaimValueTypes.Json);

    // Add the claim to the IssuedClaims which will eventually end up in the issued JWT
    context.IssuedClaims.Add(claim);

    return Task.CompletedTask;
}
```

When I add single 'role' claim, it adds it as a string type in the JWT. If I add multiple 'role' claims, it adds it as an array. All exactly as the above issue describes.

The suggested solution was to use the ClaimTypeValue.Json. As it turns out, if I put in a JSON array with a single value, it still pops out the other end as a string and not a JSON array.

With multiple role claims, everything works great.

Replacing `rolesJson` with `"[\"role1\"]"` will incorrectly produce a string in the JWT claim.
Replacing it with `"[\"role1\", \"role2\"]"` will correctly produce an array in the JWT claim.

I marked this as a bug since the recommended workaround doesn't seem to work.

**Comment by leastprivilege** [comment]
I just tried your code...

I get back

eyJhbGciOiJSUzI1NiIsImtpZCI6Ik9mTW12dHFjeVVoOU1RZkprbmxQMnciLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE1Nzg0MDcyODcsImV4cCI6MTU3ODQwNzU4NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoibXZjLmNvZGUiLCJub25jZSI6IjYzNzE0MDA0MDcwNzg0Mjg1MC5NRFZsTjJJd01qZ3RaR0U0WkMwME1HSXlMVGc1TkRndE9XSXlZekZoWlRneE9XUTJaak5sWTJVMU1tTXRNVE5sT0MwME9EazNMV0ptTUdJdFpXWmpOekppWmpnNFpqazEiLCJpYXQiOjE1Nzg0MDcyODQsImF0X2hhc2giOiJoNFlHbFpXdFNQaFJiRWs3OE1BbDFnIiwic19oYXNoIjoiRzRDVU1aclAwUFQ2dVdKMGsyZmdJdyIsInNpZCI6IlpnMnNFeDNtM2htLTNMRUJjbDFfcmciLCJzdWIiOiI4ODQyMTExMyIsImF1dGhfdGltZSI6MTU3ODQwNzI3MywiaWRwIjoibG9jYWwiLCJuYW1lIjoiYm9iIiwiYW1yIjpbInB3ZCJdLCJyb2xlIjpbInJvbGUxIl19.qRaO_q0EAW8FQVDgKGuc7SY0feY7y07kcmobgI2NEed3HEdgaBrlAdOVIS-MWWXrLlHtG1C4E_bmTR_A0Pu0d3enGC2oMfF8SYMMPyHM0DYqcMr6A9bJWD1UIPnxwbtMYPfTFWg7DGP9WlDeFvGlCtdFX_Z7sFfkK4e1HSSwwf9LbcnK47v7lbJpn05Qkf6dSCOFOex7leqXzfMyrhlk1WamF-NbqokkC4WKaNmTmFno58lxfMeAMELIEzFZTvXZTcaNRhMFy7eQAEeLqhz2MoBw1zjSK8D8dBUuZ3_6SRtsFsDT3tyb4QNJ-xvMZCzeBx-KntXqvrAeCFfkzdU7pg

and

eyJhbGciOiJSUzI1NiIsImtpZCI6Ik9mTW12dHFjeVVoOU1RZkprbmxQMnciLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1Nzg0MDcyODQsImV4cCI6MTU3ODQxMDg4NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiYXBpMSIsImNsaWVudF9pZCI6Im12Yy5jb2RlIiwic3ViIjoiODg0MjExMTMiLCJhdXRoX3RpbWUiOjE1Nzg0MDcyNzMsImlkcCI6ImxvY2FsIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIiwiYXBpMSIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJwd2QiXSwicm9sZSI6WyJyb2xlMSJdfQ.lMkAr8lsu_NiW8up0MUD9RSftTINUPuEVFEIY1Ps7wCEKh8W79aikm7gwTxbEZGqK3V4fqQh91pDloAD77nrtaIfHX3mjuMmp07TmNZYnNcvQs-sxMa0Foc4Lcx6lDKvji7956oWB4XJCURncVZZ9BX04JfsXMYPgeZgbwEvM01cYIUMK0fqjKUNIH_paclYqElYfZOrM0hq0TsqNd-rhPVn9ZthFJ-ADUPzW4DvxBcZl_OIGKBQbeLovwFmKfev3XggQINb_uPJhTns-tbBeUFHDLo1tuX-p1ijcj6OR6_jxvb4i50J88AroiP6E4OwmOwkZfiyManpdn2v1kzp_A

In both cases role is a single valued JSON array. Am I missing something?

**Comment by azydevelopment** [comment]
Weird. Sounds more like I'm missing something. Let me give it more tries tonight.

**Comment by azydevelopment** [comment]
Okay I've got it. The JWT itself does seem to have a single value array but the client side library I think brings it down to just a string:

From AuthorizeServices.js checking out user.profile where the claims end up on the client side:

![image](https://user-images.githubusercontent.com/29720335/71915345-64f21780-3130-11ea-8da7-d5f81690138e.png)


![image](https://user-images.githubusercontent.com/29720335/71915338-602d6380-3130-11ea-86db-07bb40245a17.png)

Looks like this might not be an IdentityServer thing. Should this issue go into the AspNetCore repo?

**Comment by leastprivilege** [comment]
yes please.
