### ISSUE TITLE
Leeway in the "nbf" claim

### ISSUE THREAD

**Issue by cleverswine** [IdentityServer/IdentityServer4#397]
According to rfc7519, when setting the "nbf" (Not Before) Claim:
"Implementers MAY provide for some small leeway, usually no more than a few minutes, to account for clock skew."
https://tools.ietf.org/html/rfc7519#section-4.1.5

I looks like there is no flexibility in IdentityServer4 for setting that leeway. I'm looking in Services/Default/DefaultTokenCreationService.cs

This could (and has for me) cause an issue if the Token validator's clock is behind the issuer's clock.

**Comment by leastprivilege** [comment]
The clock skew is typically done at the receiving end - e.g. the MS JWT handler has a 5 min clock skew built-in.

**Comment by cleverswine** [comment]
That makes sense. I'm using a golang library for token validation (https://github.com/dgrijalva/jwt-go), so I'll see about implementing it there. Meanwhile I have an override on the Token Creation that subtracts 5 minutes from the nbf claim (not ideal, but it works).
