### ISSUE TITLE
Token endpoint returns invalid_client after upgrading to .NET Core 3.1, with certain ClientCorsOrigins entries

### ISSUE THREAD

**Issue by ppi-gzhou** [IdentityServer/IdentityServer4#3970]
### Issue / Steps to reproduce the problem
After upgrading my IdentityServer implementation to use .NET Core 3.1, I am always getting an `invalid_client` error when calling `RequestPasswordTokenAsync` from my client. This only appears to be an issue on our staging server, not on localhost.

I have confirmed this is not a configuration db issue, because the token endpoint returns the access token just fine when using .NET Core 2.1 implementation.

**TokenResponse from Core 3.1:**
```
{
  "accessToken": null,
  "identityToken": null,
  "tokenType": null,
  "refreshToken": null,
  "errorDescription": null,
  "expiresIn": 0,
  "httpResponse": {
    "version": "1.1",
    "content": {
      "headers": [
        {
          "key": "Content-Type",
          "value": [
            "application/json; charset=UTF-8"
          ]
        }
      ]
    },
    "statusCode": 400,
    "reasonPhrase": "Bad Request",
    "headers": [
      {
        "key": "Cache-Control",
        "value": [
          "no-store, no-cache, max-age=0"
        ]
      },
      {
        "key": "Pragma",
        "value": [
          "no-cache"
        ]
      },
      {
        "key": "Transfer-Encoding",
        "value": [
          "chunked"
        ]
      },
      {
        "key": "Server",
        "value": [
          "Microsoft-IIS/7.5"
        ]
      },
      {
        "key": "Strict-Transport-Security",
        "value": [
          "max-age=31536000; includeSubDomains"
        ]
      },
      {
        "key": "X-Content-Type-Options",
        "value": [
          "nosniff"
        ]
      },
      {
        "key": "Referrer-Policy",
        "value": [
          "no-referrer"
        ]
      },
      {
        "key": "X-XSS-Protection",
        "value": [
          "1; mode=block"
        ]
      },
      {
        "key": "X-Frame-Options",
        "value": [
          "Deny"
        ]
      },
      {
        "key": "Content-Security-Policy",
        "value": [
          "script-src 'self';style-src 'self' 'unsafe-inline';img-src 'self';font-src 'self';form-action 'self';frame-ancestors 'self';block-all-mixed-content"
        ]
      },
      {
        "key": "X-Powered-By",
        "value": [
          "ASP.NET"
        ]
      },
      {
        "key": "Date",
        "value": [
          "Tue, 07 Jan 2020 16:40:18 GMT"
        ]
      }
    ],
    "trailingHeaders": [],
    "requestMessage": {
      "address": "https://XXXXXXXX/connect/token",
      "clientId": "XXXXXXXX",
      "clientSecret": null,
      "clientAssertion": {
        "type": null,
        "value": null
      },
      "clientCredentialStyle": 1,
      "authorizationHeaderStyle": 0,
      "parameters": {
        "grant_type": "password",
        "username": "XXXXXXXX",
        "password": "XXXXXXXX",
        "scope": "openid offline_access XXXXXXXX",
        "client_id": "XXXXXXXX"
      },
      "version": "1.1",
      "content": {
        "headers": [
          {
            "key": "Content-Type",
            "value": [
              "application/x-www-form-urlencoded"
            ]
          },
          {
            "key": "Content-Length",
            "value": [
              "247"
            ]
          }
        ]
      },
      "method": {
        "method": "POST"
      },
      "requestUri": "https://XXXXXXXX/connect/token",
      "headers": [
        {
          "key": "Accept",
          "value": [
            "application/json"
          ]
        },
        {
          "key": "Request-Id",
          "value": [
            "|e78a2272-42ddc78843b2e687.3."
          ]
        }
      ],
      "properties": {}
    },
    "isSuccessStatusCode": false
  },
  "raw": "{\"error\":\"invalid_client\"}",
  "json": {
    "error": "invalid_client"
  },
  "exception": null,
  "isError": true,
  "errorType": 1,
  "httpStatusCode": 400,
  "httpErrorReason": "Bad Request",
  "error": "invalid_client"
}
```

**TokenResponse from Core 2.1:**
```
{
  "accessToken": (valid access token),
  "identityToken": null,
  "tokenType": "Bearer",
  "refreshToken": (valid refresh token),
  "errorDescription": null,
  "expiresIn": 3600,
  "httpResponse": {
    "version": "1.1",
    "content": {
      "headers": [
        {
          "key": "Content-Type",
          "value": [
            "application/json; charset=UTF-8"
          ]
        }
      ]
    },
    "statusCode": 200,
    "reasonPhrase": "OK",
    "headers": [
      {
        "key": "Cache-Control",
        "value": [
          "no-store, no-cache, max-age=0"
        ]
      },
      {
        "key": "Pragma",
        "value": [
          "no-cache"
        ]
      },
      {
        "key": "Transfer-Encoding",
        "value": [
          "chunked"
        ]
      },
      {
        "key": "Server",
        "value": [
          "Kestrel"
        ]
      },
      {
        "key": "Strict-Transport-Security",
        "value": [
          "max-age=31536000; includeSubDomains"
        ]
      },
      {
        "key": "X-Content-Type-Options",
        "value": [
          "nosniff"
        ]
      },
      {
        "key": "X-XSS-Protection",
        "value": [
          "1; mode=block"
        ]
      },
      {
        "key": "Content-Security-Policy",
        "value": [
          "frame-ancestors https:;block-all-mixed-content"
        ]
      },
      {
        "key": "X-Powered-By",
        "value": [
          "ASP.NET"
        ]
      },
      {
        "key": "Date",
        "value": [
          "Tue, 07 Jan 2020 16:44:18 GMT"
        ]
      }
    ],
    "trailingHeaders": [],
    "requestMessage": {
      "address": "https://XXXXXXXX/connect/token",
      "clientId": "XXXXXXXX",
      "clientSecret": null,
      "clientAssertion": {
        "type": null,
        "value": null
      },
      "clientCredentialStyle": 1,
      "authorizationHeaderStyle": 0,
      "parameters": {
        "grant_type": "password",
        "username": "XXXXXXXX",
        "password": "XXXXXXXX",
        "scope": "openid offline_access XXXXXXXX",
        "client_id": "XXXXXXXX"
      },
      "version": "1.1",
      "content": {
        "headers": [
          {
            "key": "Content-Type",
            "value": [
              "application/x-www-form-urlencoded"
            ]
          },
          {
            "key": "Content-Length",
            "value": [
              "247"
            ]
          }
        ]
      },
      "method": {
        "method": "POST"
      },
      "requestUri": "https://XXXXXXXX/connect/token",
      "headers": [
        {
          "key": "Accept",
          "value": [
            "application/json"
          ]
        },
        {
          "key": "Request-Id",
          "value": [
            "|e78a2273-42ddc78843b2e687.3."
          ]
        }
      ],
      "properties": {}
    },
    "isSuccessStatusCode": true
  },
  "raw": "{\"access_token\":\(valid access token),\"expires_in\":3600,\"token_type\":\"Bearer\",\"refresh_token\":\(valid refresh token)}",
  "json": {
    "access_token": (valid access token),
    "expires_in": 3600,
    "token_type": "Bearer",
    "refresh_token": (valid refresh token)
  },
  "exception": null,
  "isError": false,
  "errorType": 0,
  "httpStatusCode": 200,
  "httpErrorReason": "OK",
  "error": null
}
```

**Comment by leastprivilege** [comment]
as always - check your server logs first.

**Comment by ppi-gzhou** [comment]
Using SeriLog, I set the minimum log level to Debug (it's normally at Warning), but the server did not generate an event log for the bad request after I called `RequestPasswordTokenAsync`.

That is the frustrating thing, if I had logs to work with I could probably get somewhere on my own. Any suggestions as to either improving my logging or getting some other indication as to what is going on?

**Comment by ppi-gzhou** [comment]
Finally got some logs to show.

```
fail: IdentityServer4.Stores.ValidatingClientStore[0]
    Invalid client configuration for client XXXXXXXX: AllowedCorsOrigins contains invalid origin
```

Did something change as far as CORS origins entries?

**Comment by leastprivilege** [comment]
what are your entries?

**Comment by ppi-gzhou** [comment]
I had one for `https://localhost:4200` and one for `https://www.XXXXXXXX.com/portal`.

I ended up just removing all of the entries from the ClientCorsOrigins table and it resolved the issue. This works for us because we switched to use password grant type, but this issue could possibly affect others as well

**Comment by nmocruz** [comment]
I'm getting this to.
I'm trying to use pkce no secret on the phone. 
Sending POST /token/connect tries to validate the secrect with basic authotication validation parser

**Comment by brockallen** [comment]
>  I'm trying to use pkce no secret on the phone.
>  Sending POST /token/connect tries to validate the secrect with basic authotication validation parser.

Did you set `RequireClientSecret` to `false`?

http://docs.identityserver.io/en/latest/reference/client.html

**Comment by nmocruz** [comment]
> > I'm trying to use pkce no secret on the phone.
> > Sending POST /token/connect tries to validate the secrect with basic authotication validation parser.
> 
> Did you set `RequireClientSecret` to `false`?
> 
> http://docs.identityserver.io/en/latest/reference/client.html

Yes I'm, I gonna doble check deleting the DB and reconfigure it again.
there's also a strange log information, saying that there's no POST endpoint to /token/connect and I was wondering if this is not failing back to other endpoint.

**Comment by nmocruz** [comment]
[09:45:31 INF] Request starting HTTP/2 POST https://server1:5003/connect/token application/x-www-form-urlencoded; charset=utf-8 2
[09:45:31 DBG] POST requests are not supported
[09:45:31 DBG] No candidates found for the request path '/connect/token'
[09:45:31 DBG] Request did not match any endpoints
[09:45:31 DBG] AuthenticationScheme: idsrv was not authenticated.
[09:45:31 DBG] AuthenticationScheme: idsrv was not authenticated.
[09:45:31 DBG] Request path /connect/token matched to endpoint type Token
[09:45:31 DBG] Endpoint enabled: Token, successfully created handler: IdentityServer4.Endpoints.TokenEndpoint
[09:45:31 INF] Invoking IdentityServer endpoint: IdentityServer4.Endpoints.TokenEndpoint for /connect/token
[09:45:31 DBG] Start token request.
[09:45:31 DBG] Start client validation
[09:45:31 DBG] Start parsing Basic Authentication secret
[09:45:31 DBG] Start parsing for secret in post body
[09:45:31 DBG] Connection id "0HLSOQNMQHF16", Request id "0HLSOQNMQHF16:00000007": started reading request body.
[09:45:31 DBG] Connection id "0HLSOQNMQHF16", Request id "0HLSOQNMQHF16:00000007": done reading request body.
[09:45:31 DBG] No secret in post body found
[09:45:31 DBG] Parser found no secret
[09:45:31 ERR] No client identifier found

**Comment by paaland** [comment]
Had similar issues after the update. Seems the new packages does not allow paths, So ```https://www.somedomain.com/path/``` does not work, even ```https://www.somedomain.com/``` fails. But ```https://www.somedomain.com``` works.

**Comment by nmocruz** [comment]
in my case I'm using nativescrip with appauth-js and the origin is file://* the uri seems to convert to file:/// and so I'm keeping a extended implementation to accept file://* 

Is client configuration validation went well, for some reason is failing into a BasicAthenticationParser and trie to get missing information from headers,

**Comment by brockallen** [comment]
> Had similar issues after the update. Seems the new packages does not allow paths, So https://www.somedomain.com/path/ does not work, even https://www.somedomain.com/ fails. But https://www.somedomain.com works as AllowedCorsOrigins URLs.

That's because those aren't origins. The additional validation is an attempt to ensure the correct values are used.
