### ISSUE TITLE
Silent Renew on our IS4 Server and External OIDC Provider

### ISSUE THREAD

**Issue by bryanllewis** [IdentityServer/IdentityServer4#3976]
I am asking this question here because my SO question has no responses after 3 weeks and I am hoping for some insight.

I have an Asp.Net Core IdentityServer4 instance securing an API that is fronted by a Vue.js SPA (using oidc-client). Our IS4 server is setup to manage accounts for my company's users, but we also have an external OIDC provider setup for a trusted partner that allows their users to access our app using their single sign-on server (OIDC). The partner's portal has a link to our app, so if they are already authenticated by their own OIDC server, then no additional login prompt is displayed.

Overall, this process works. I can login "locally" (our identity server), or use the external OIDC provider that authenticates the user and goes through the auto-provisioning on our IS4 server. The Vue app has its tokens and silent refresh is enabled, which keeps the user's credentials updated against our IS4 server.

However, if a user from our partner comes to our app, spends some time there, and then returns to their own portal via a link on our site, it's likely that their access will have timed out and they see their own SSO login again. This is because the silent refresh on our site is only refreshing our local IS4 token.

Is it possible to somehow maintain BOTH sessions while the partner user is on our site? Silently refreshing both our IS4 token and their OIDC SSO credentials so that when they return to their own site they will not have to login again against their SSO?

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
