### ISSUE TITLE
Error with IdentityServer4 and Swagger on same server

### ISSUE THREAD

**Issue by vblahov** [IdentityServer/IdentityServer4#3977]
Hello! I have a problem with Implicit OAuth using Web Api and IdentityServer4 in same project. 
All client credentials are valid. After clicking on the button "Login", i can see next error:

"An unhandled exception occurred while processing the request.
InvalidOperationException: The authentication handler registered for scheme 'Bearer' is 'IdentityServerAuthenticationHandler' which cannot be used for SignInAsync. The registered sign-in schemes are: idsrv, idsrv.external."

Code:
```
 services.AddIdentityServer(options => options.UserInteraction = new UserInteractionOptions()
            {
                LogoutUrl = "/account/logout",
                LoginUrl = "/account/login",
                LoginReturnUrlParameter = "returnUrl"
            }).AddTestUsers(TestUsers.Users)
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApis())
                .AddInMemoryClients(Config.GetClients());

            services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
            .AddIdentityServerAuthentication(options =>
            {
                options.ApiName = "demo_api"; // required audience of access tokens
                options.RequireHttpsMetadata = false; // dev only!
            });

            services.AddAuthorization();

            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new Info { Title = "Protected API", Version = "v1" });

                options.AddSecurityDefinition("oauth2", new OAuth2Scheme
                {
                    Flow = "implicit",
                    TokenUrl = "/connect/token",
                    AuthorizationUrl = "/connect/authorize",
                    Scopes = new Dictionary<string, string> { { "demo_api", "Demo API - full access" } }
                });

                options.OperationFilter<AuthorizeCheckOperationFilter>(); // Required to use access token
            });
```

**Comment by qumeta** [comment]
change this line
services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
-->
services.AddAuthentication()

**Comment by vblahov** [comment]
> change this line
> services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
> -->
> services.AddAuthentication()

Thanks, that helped, but now i have not redirect back to main page

**Comment by vblahov** [comment]
> change this line
> services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
> -->
> services.AddAuthentication()

In this case, my controllers will be not secured
 public class AuthorizeCheckOperationFilter : IOperationFilter
        {
            public void Apply(Operation operation, OperationFilterContext context)
            {
                var authAttributes = context.MethodInfo.DeclaringType.GetCustomAttributes(true)
                .Union(context.MethodInfo.GetCustomAttributes(true))
                .OfType<AuthorizeAttribute>();

                if (authAttributes.Any())
                {
                    operation.Responses.Add("401", new Response { Description = "Unauthorized" });

                    operation.Security = new List<IDictionary<string, IEnumerable<string>>>
                {
                    new Dictionary<string, IEnumerable<string>> {{"oauth2", new[] {"demo_api"}}}
                };
                }
            }
        }

**Comment by vblahov** [comment]
> change this line
> services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
> -->
> services.AddAuthentication()

```
 public class AuthorizeCheckOperationFilter : IOperationFilter
        {
            public void Apply(Operation operation, OperationFilterContext context)
            {
                var authAttributes = context.MethodInfo.DeclaringType.GetCustomAttributes(true)
                .Union(context.MethodInfo.GetCustomAttributes(true))
                .OfType<AuthorizeAttribute>();

                if (authAttributes.Any())
                {
                    operation.Responses.Add("401", new Response { Description = "Unauthorized" });

                    operation.Security = new List<IDictionary<string, IEnumerable<string>>>
                {
                    new Dictionary<string, IEnumerable<string>> {{"oauth2", new[] {"demo_api"}}}
                };
                }
            }
        }
```
In this case my controllers will not secured

**Comment by vblahov** [comment]
Solve this with 
change this line
```
services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
-->
services.AddAuthentication()
```
 and change [Authorize] to [Authorize(AuthenticationSchemes = "Bearer")] on controllers
