### ISSUE TITLE
How to redirect back to the application after password change?

### ISSUE THREAD

**Issue by noufionline** [IdentityServer/IdentityServer4#398]
Hi,
In a Hybrid Flow scenario where user navigates to manage user profile and changes password, how can a user be redirected back to the application from Identity Server?

**Comment by brockallen** [comment]
I don't understand the question. Change password is not covered in OIDC anywhere.

**Comment by noufionline** [comment]
May be might question doesn't make sense in the context but if I wanted to give user an option to manage users / change the password option in my mvc client I need to navigate to identity server to do the job. 
According to QuickStart hybrid flow example aspnet identity is bundled with identity server. Once the user navigates to identity server uri to change the password need to provide a link back to the mvc client. In essence I wanted to know where the redirect uri is created so that I can do the same to solve my problem

Get Outlook for iOS




On Tue, Oct 11, 2016 at 5:14 PM +0400, "Brock Allen" <notifications@github.com> wrote:












I don't understand the question. Change password is not covered in OIDC anywhere.

**Comment by brockallen** [comment]
Pass some id param of the client app so your change password can redirect back once done. That's just normal web development at that point.
