### ISSUE TITLE
Identity Server 4 Equivalents of Identity Server 3 IUserService's AuthenticateExternalAsync and AuthenticateLocalAsync methods 

### ISSUE THREAD

**Issue by ehelin** [IdentityServer/IdentityServer4#3983]
I am working on finding the equivalents of Identity Server 3 IUserService functionality in Identity Server 4. The recommended path seems to be to use 'IProfileService' and 'IResourceOwnerPasswordValidator'.  However, 'IResourceOwnerPasswordValidator' does not appear to work for Implicit and other standard work flows.  Is there an alternative?

I have been reading the documents and so far, I have not come up with the Identity Server 4 equivalent of IUserService's AuthenticateExternalAsync and AuthenticateLocalAsync methods.

**Comment by brockallen** [comment]
In IS4 the UI layer and thus getting the user authenticated is entirely the responsibility of your UI/hosting later. See the docs for more info:

http://docs.identityserver.io/en/latest/topics/signin.html

**Comment by ehelin** [comment]
OK.  Thank you.

**Comment by ehelin** [comment]
Another question if I may :)  My plan is to roll our own IUserService equivalent (see below).  Reviewing the sample projects (thank you for those, very helpful!! :)), I can inject this interface's implementation into our account controller via the constructor and call each method from is appropriate action.  Specifically:

-AuthenticateLocalAsync(args) from '[HttpPost] -> Task<IActionResult> Login(LoginInputModel model)'
-SignOutAsync(<new parameter(s) here!>) from '[HttpPost] -> Task<IActionResult> Logout(LogoutInputModel model)'

What is eluding me is the equivalent of 'AuthenticateExternalAsync'.  Will all login calls come through  '[HttpPost] -> Task<IActionResult> Login(LoginInputModel model)'?  Reading through the external authentication documentation, I

public interface INewUserService
{
	Task AuthenticateExternalAsync(<new parameter(s) here!>);
	Task AuthenticateLocalAsync(<new parameter(s) here!>);
	Task SignOutAsync(<new parameter(s) here!>);
}
