### ISSUE TITLE
Extend PersistedGrants with UserAgent

### ISSUE THREAD

**Issue by reaction1989** [IdentityServer/IdentityServer4#3985]
We want to give the ability to an User to revoke the refresh_token/login for a specific device/app. So it would be nice to have the user_agent of that to device to be able to determine the used device.

**Describe the solution you'd like**
Add a new Column Useragent to the PersistedGrants table and fill it when a new token gets saved into it

Is this something that is interesting to implement it here, or should it be better done by the consumer of identityserver?

**Comment by brockallen** [comment]
You mean like this: 

https://github.com/IdentityServer/IdentityServer4/issues/2976
or
https://github.com/IdentityServer/IdentityServer4/issues/2621

**Comment by reaction1989** [comment]
Yeah a description would be neat and the ability to save the user-agent from which the request came. 

--> That would make it possible to display the following two things:
1. A Friendly name given by the User
2. The Device of the user (User-Agent Sniffing)
