### ISSUE TITLE
System.TypeLoadException: Could not load type 'IdentityModel.Client.DiscoveryResponse' from assembly 'IdentityModel, Version=4.1.1.0, Culture=neutral, PublicKeyToken=e7877f4675df049f'

### ISSUE THREAD

**Issue by hubaozhang2017** [IdentityServer/IdentityServer4#3986]
I have an exception error after converted from IdentityServer4 2.2 to 3.1. Here is the code
     public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        if (_environment.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
            app.UseDatabaseErrorPage();
        }
        try
        {
            using (var serviceScope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                SeedData.EnsureSeedData(serviceScope, Configuration);
            }
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex.Message);
        }

        //app.UseIdentityServer();
        //app.UseCors(builder => builder.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod().AllowCredentials());
        //app.UseStaticFiles();
        //app.UseMvcWithDefaultRoute();

        app.UseStaticFiles();

        app.UseRouting();
        app.UseCors();
        app.UseIdentityServer();
        // app.UseAuthorization();
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapDefaultControllerRoute();
        });
    }
The error occurred on app.UseEndpoints.

**Comment by leastprivilege** [comment]
Make sure all code you are using is compiling against the latest version of Identitymodel

**Comment by hubaozhang2017** [comment]
Thank you. The problem was resolved.
