### ISSUE TITLE
Get token without an HTTP call.

### ISSUE THREAD

**Issue by aspramsh** [IdentityServer/IdentityServer4#3987]
Hi there,

Is there a way to get an access token programmatically in my identity server API?

**Comment by scottbrady91** [comment]
http://docs.identityserver.io/en/latest/topics/tools.html

**Comment by aspramsh** [comment]
Thanks. And also are there any such methods for getting refresh tokens and revoking them?

**Comment by leastprivilege** [comment]
no.

**Comment by aspramsh** [comment]
Thanks.
