### ISSUE TITLE
Auto login(skip login page) for ADFS and identity server 4

### ISSUE THREAD

**Issue by NeelBhatt** [IdentityServer/IdentityServer4#3988]
Hello Guys,

Just wondering if anyone can help me with this question on StackOverflow: https://stackoverflow.com/questions/59731578/auto-loginskip-login-page-for-adfs-and-identity-server-4

Thanks in advance

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
