### ISSUE TITLE
The signature key was not found

### ISSUE THREAD

**Issue by mbeckenbach** [IdentityServer/IdentityServer4#399]
Whenever I change something at server side which causes a restart or recompile I only get 401s containing this header:

WWW-Authenticate:Bearer error="invalid_token", error_description="The signature key was not found"

I have identity server and my api in the same project. In identity server 3 we had to configure a signing certificate. I did not see that in your examples, which felt quite strange. 

What am I doing wrong? Or do i have to add the certificate? How?

**Comment by leastprivilege** [comment]
you are probably using the `AddDeveloperIdentityServer` extension method.

This will set a temp. signing key which will recycle with every start. You can use the `SetSigningCredential` method to set an explicit one.

**Comment by mbeckenbach** [comment]
@leastprivilege Thank you. 

As i dont need in memory stores anymore, I replaced AddDeveloperIdentityServer with AddIdentityServer and added a certificate. Works fine like this now:

````
var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

/*
* Use powershell as administrator to create a new dev certificate:
* New-SelfSignedCertificate -certstorelocation cert:\localmachine\my -dnsname some.testingdomain.internal
* Then export using mmc (include private key)
*/

var contentRootPath = _environment.ContentRootPath;
var cert = new X509Certificate2(Path.Combine(contentRootPath, "devcert.pfx"), "password");

services.AddIdentityServer()
.SetSigningCredential(cert)
.AddConfigurationStore(builder => builder.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationsAssembly)))
.AddOperationalStore(builder => builder.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationsAssembly)))
.AddAspNetIdentity<User>()
.AddProfileService<ProfileService>();
```

**Comment by FrankV01** [comment]
Is `AddSigningCredential` the new name for `SetSigningCredential` or are these different?
