### ISSUE TITLE
Context.User.Identity.isAuthenticated is false after successfully login.

### ISSUE THREAD

**Issue by raban33** [IdentityServer/IdentityServer4#3992]
Hello, I have implemented a simple identity server in asp.net core 2.1 application. after local login, the page keeps redirecting to login page instead of ~/grants page. I know its a simple things which I am missing but can't figure out. I do see the idsrv and idsrv.session cookies. here is the configuration

Startup.cs
=======================================================
public IServiceProvider ConfigureServices(IServiceCollection services)
        {
 services.AddMvc();
   services.Configure<IISOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });

services.AddExternalIdentityProviders(Configuration);

            services.AddMvc(options => options.MaxModelValidationErrors = 5);

            return services.BuildServiceProvider(validateScopes: false);
}
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
                app.UseDatabaseErrorPage();
            }
            else
            {
                loggerFactory.AddLambdaLogger(Configuration.GetLambdaLoggerOptions());
                app.UseExceptionHandler("/Home/Error");
            }
            
            app.UseIdentityServer();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");

            });

        }

 public static class ServiceExtensions
    {
        public static IServiceCollection AddExternalIdentityProviders(this IServiceCollection services, IConfiguration configuration)
        {
            // configures the OpenIdConnect handlers to persist the state parameter into the server-side IDistributedCache.
            services.AddOidcStateDataFormatterCache("aad", "demoidsrv");
            services.AddAuthentication()
                .AddGoogle("Google", options =>
                {
                    options.SignInScheme = IdentityConstants.ExternalScheme;
                    options.ClientId = configuration["ExternalIdentityProviders:Google:AppKey"];
                    options.ClientSecret = configuration["ExternalIdentityProviders:Google:AppSecret"];
                }).AddFacebook("Facebook", options =>
                {
                    options.SignInScheme = IdentityConstants.ExternalScheme;
                    options.ClientId = configuration["ExternalIdentityProviders:Facebook:AppKey"];
                    options.ClientSecret = configuration["ExternalIdentityProviders:Facebook:AppSecret"];
                    options.Scope.Add("user_birthday");
                    options.Scope.Add("user_friends");
                    //options.Scope.Add("read_custom_friendlists");
                    options.SaveTokens = true;
                })
                .AddOpenIdConnect("aad", "WPSPublish User?", options =>
                {
                    options.SignInScheme = IdentityConstants.ExternalScheme;
                    options.SignOutScheme = IdentityConstants.ExternalScheme;

                    options.Authority = "https://login.windows.net/3695bb70-607a-4c0e-87bd-d5c77fa38413";
                    options.ClientId = "13fbd759-8d23-463c-8958-270f700de183";
                    options.ResponseType = "id_token";
                    options.CallbackPath = "/signin-aad";
                    options.SignedOutCallbackPath = "/signout-callback-aad";
                    options.RemoteSignOutPath = "/signout-aad";
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role"
                    };
                });

            return services;
        }
    }

AccountController
============================================================

I am rendering cookies by using 

                    AuthenticationProperties props = null;
                    if (AccountOptions.AllowRememberLogin && model.RememberLogin)
                    {
                        props = new AuthenticationProperties
                        {
                            IsPersistent = true,
                            ExpiresUtc = DateTimeOffset.UtcNow.Add(AccountOptions.RememberMeLoginDuration)
                        };
                    };
                    // issue authentication cookie with subject ID and username
                    await HttpContext.SignInAsync(SubjectId, Email, props, Claims.ToArray());

**Comment by brockallen** [comment]
>  services.AddAuthentication("SeeticketsAuth")

This is why. You're making that scheme the default scheme. Is that what's getting issued on the login page?

**Comment by raban33** [comment]
sorry, it was a commented section, I have removed it for brevity... Despite that its still an issue

**Comment by brockallen** [comment]
Then it's hard to tell, sorry.

**Comment by raban33** [comment]
would you be able to help if we seek commercial support?

**Comment by brockallen** [comment]
Yes, commercial support would involve one-on-one screen sharing sessions where we could look at and debug your code.

**Comment by raban33** [comment]
@brockallen I will be sending you an email with my name Rajiv Bannur. Please note it

**Comment by raban33** [comment]
@brockallen Seems like I figured out an issue. may be you can throw some light on it. I had these two registrations in configure services in reverse order

 app.UseMvcWithDefaultRoute();
 app.UseIdentityServer();

I guess IdentityServer needs to be registered prior to UseMvcWithDefaultRoute 

The moment I got it in right order, the user sign-in cookies were properly decrypted and claimsprinicpal was deserialized correctly.

**Comment by leastprivilege** [comment]
yes - IdentityServer must be in the pipeline before MVC.

**Comment by raban33** [comment]
Very interesting, but thanks for clarification. I am closing this now
