### ISSUE TITLE
Please fix the is4ef template.

### ISSUE THREAD

**Issue by cpm205** [IdentityServer/IdentityServer4#3994]
Hi,
Can you please fix the is4ef template? it uses EFCore.sqlite not EFCore.SQL.

Thanks,
Derek Hu

**Comment by maxswann** [comment]
Hi Derek,

With efcore the templates should be db provider agnostic, you should be able to just change the db provider within startup and then use your chosen db provider.

**Comment by cpm205** [comment]
Thanks @maxswann.
I guess that Migrations folder needs to be deleted as well since everything in that folder is to create sqlite database, and I have to run below command to generate new migrations for sql server, right?
dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb
dotnet ef migrations add InitialIdentityServerConfigurationDbMigration -c ConfigurationDbContext -o Data/Migrations/IdentityServer/ConfigurationDb

**Comment by brockallen** [comment]
> I guess that Migrations folder needs to be deleted as well since everything in that folder is to create sqlite database, and I have to run below command to generate new migrations for sql server, right?

Yes, EF migrations have always been provider specific. If you change providers you will need to take those steps.
