### ISSUE TITLE
Improve redirect treatment for clients in Quickstart.UI

### ISSUE THREAD

**Issue by ArturDorochowicz** [IdentityServer/IdentityServer4#3997]
_I suppose the idea here is covered by #3407, but this is more focused and constrained to just the Quickstart UI._

I'm wondering about the special treatment of PKCE clients in the QuickStart UI with regard to redirecting back to the client (e.g. [1]). This special redirection treatment assumes that every PKCE client is a native client. But I think this assumption is becoming less and less true. In newer AspNet Core versions, using PKCE is a matter of setting a couple of configuration properties and adding it to older AspNet Core is not much work either [2]. It's also possible with Katana 4.1 [3]. Also, we apparently need just two grants and one of them includes PKCE and covers all kinds of apps [4] ;)

So, I wonder if there is a better differentiator than whether RequirePkce is true. Would it make sense to base the decision on what the redirect uri is? If the scheme of the redirect uri is http or https, we do a regular http redirect. Otherwise, we show the intermediate screen. The assumption then is that a native client uses _Private-use URI Scheme Redirection_ [5].

[1] https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/6f187aa50f31690e44c838885b8f816c96fc417f/Quickstart/Account/AccountController.cs#L93
[2] https://www.scottbrady91.com/OpenID-Connect/ASPNET-Core-using-Proof-Key-for-Code-Exchange-PKCE
[3] https://www.scottbrady91.com/ASPNET/Refreshing-your-Legacy-ASPNET-IdentityServer-Client-Applications
[4] https://leastprivilege.com/2019/09/09/two-is-the-magic-number/
[5] https://tools.ietf.org/id/draft-ietf-oauth-native-apps-12.html#rfc.section.7.1

**Comment by leastprivilege** [comment]
Thanks - -we are aware of all of that. It was meant to be a sample - but we want to have a more flexible approach in the future.

**Comment by leastprivilege** [comment]
> The assumption then is that a native client uses Private-use URI Scheme Redirection [5].

I like this idea - if you could PR an extension method that tries to infer that based on a Client - that would be interesting.

**Comment by ArturDorochowicz** [comment]
#4015 implements what I had in mind. Note that it will change the behavior for some (most?) of your sample console clients.

**Comment by brockallen** [comment]
We improved this, so closing.
