### ISSUE TITLE
Auth Cookie SPA

### ISSUE THREAD

**Issue by patsadow2** [IdentityServer/IdentityServer4#3999]
Simple, is there any good tutorial how to correctly implement auth cookie spa in identity server 4 ???

**Comment by brockallen** [comment]
http://docs.identityserver.io/en/latest/quickstarts/4_javascript_client.html

**Comment by patsadow2** [comment]
I see it's example without cookie implementation

**Comment by brockallen** [comment]
> I see it's example without cookie implementation, i 've SPA implementation with localstorage but i would like to convert it to cookie, but i am not sure what steps should i do to do that ;/

Then you'd drive the protocol from the server, and use a different library.
