### ISSUE TITLE
Combine AspNetIdentity with IdentityServer4

### ISSUE THREAD

**Issue by cpm205** [IdentityServer/IdentityServer4#4001]
Hi guys,

Do you have any sample that combines both aspnetidentity and is4 into one SQLServer database with EFCore?

Regards,

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/tree/master/samples/Quickstarts/deprecated/9_Combined_AspId_and_EFStorage

But it hasn't been updated to 3.x - feel free to do that and PR once you got it working.

**Comment by cpm205** [comment]
Thanks @leastprivilege
