### ISSUE TITLE
Extension Grants Documentation out of date

### ISSUE THREAD

**Issue by sethb75** [IdentityServer/IdentityServer4#4007]
The TokenClient class signature has changed. Instead of 3 strings, now it requires HttpMessageInvoker and an options class. It is also missing the RequestCustomGrantAsync method.
The current documentation does not reflect this.

### Issue / Steps to reproduce the problem:
Go to the end of: IdentityServer4/docs/topics/extension_grants.rst

The following code sample is out of date:
`public async Task<TokenResponse> DelegateAsync(string userToken)
{
    var payload = new
    {
        token = userToken
    };

    // create token client
    var client = new TokenClient(disco.TokenEndpoint, "api1.client", "secret");

    // send custom grant to token endpoint, return response
    return await client.RequestCustomGrantAsync("delegation", "api2", payload);
}`

- TokenClient constructor signature change.
- RequestCustomGrantAsync method not available.

**Comment by leastprivilege** [comment]
Thanks. Will have a look

**Comment by leastprivilege** [comment]
merged
