### ISSUE TITLE
Client secret not validating

### ISSUE THREAD

**Issue by MadEddieFFS** [IdentityServer/IdentityServer4#4008]
I previously had IS4 setup and running in a **.net core 3 ASP.NET** host but recently moved databases. I currently use a **SQL database** for all IS4 configuration. Within the **ClientSecrets** table I have a single row for the client which is of type **"SharedSecret**".

I have an Angular client connecting with **PCKE + Code (using angular-oauth2-oidc)** where I have used the secret from the table as the **"dummyClientSecret"** within the angular-oauth2-oidc setup.

Previously this worked but I now receive the following

> [21:07:07 DBG] Start parsing Basic Authentication secret 
> 
> [21:07:07 DBG] Start parsing for secret in post body 
> 
> [21:07:07 DBG] Parser found secret: PostBodySecretParser 
> 
> [21:07:07 DBG] Secret id found: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
> 
> [21:07:07 DBG] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx found in database: True 
> 
> [21:07:07 DBG] client configuration validation for client xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx succeeded. 
> 
> [21:07:07 DBG] No matching hashed secret found. 
> 
> [21:07:07 DBG] Secret validators could not validate secret 
> 
> [21:07:07 INF] {"ClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "Category": "Authentication", "Name": "Client Authentication Failure", "EventType": "Failure", "Id": 1011, "Message": "Invalid client secret", "ActivityId": "8000001e-0001-f900-b63f-84710c7967bb", "TimeStamp": "2020-01-22T21:07:07.0000000Z", "ProcessId": 6888, "LocalIpAddress": "xx.xx.xx.xx", "RemoteIpAddress": "xx.xx.xx.xx", "$type": "ClientAuthenticationFailureEvent"} 
> 
> [21:07:07 ERR] Client secret validation failed for client: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx. 
> 

Could someone help tell me what is wrong with the secret and/or why this validation step is failing.

**Comment by leastprivilege** [comment]
Don't know - but why are you using a secret at all?

**Comment by MadEddieFFS** [comment]
Have since stopped using it as I slightly mis-understood the PKCE flow - however I suppose the issue remains

**Comment by morrisond91** [comment]
I found a similar issue with the secrets, if they are added as headers then a secret that contains special characters like + and % are deemed not valid. You can work around this with either

1. Url encoding the secret
1. Generate a new secret that doesnt have special chars.

hope this helps
