### ISSUE TITLE
Signing Certificate Rollover

### ISSUE THREAD

**Issue by Lutando** [IdentityServer/IdentityServer4#401]
I am aware that this is available in the IDS3. Is this available in IDS4? I dug into the source code of IDS4 and haven't found anything.

**Comment by brockallen** [comment]
We have a collection of validation keys now -- you can use `AddValidationKeys`.

**Comment by Lutando** [comment]
OK so the basic roll over procedure would be (if I understand this correctly), Given signing cert `A` and `B`, where A is due to be removed.

`A` would be the SigningCredential added via `SetSigningCredential` and `B` would be added via `AddValidationKeys`. This would add two keys to your jwks_uri.

Then to do the rollover we swap A and B and then remove `A` after some time. Is this correct?

**Comment by brockallen** [comment]
yep
