### ISSUE TITLE
.NET Core 3.0

### ISSUE THREAD

**Issue by FlorenciaNodar** [IdentityServer/IdentityServer4#4010]
I'm using .NET Core 3.0. 
When I want to initialize in the startup the contexts to save the clients in the database I get the following error.
![image](https://user-images.githubusercontent.com/17852643/73007562-80754780-3deb-11ea-84d5-8746539dfb95.png)

**Comment by icnocop** [comment]
See https://github.com/IdentityServer/IdentityServer4/issues/3014

> AddConfigurationStore and AddOperationalStore are extensions in the Microsoft.Extensions.DependencyInjection namespace, but located in the IdentityServer4.EntityFramework assembly.
> 
> You'll have to add the IdentityServer4.EntityFramework NuGet package to your project.

Did you add `using Microsoft.Extensions.DependencyInjection;` to the top of your file?
