### ISSUE TITLE
How is the NameClaimType and RoleClaimType specified when using LocalApi?

### ISSUE THREAD

**Issue by fuzzzerd** [IdentityServer/IdentityServer4#4011]
### Question

How can one specify the NameClaimType and/or RoleClaimType when using `.AddLocalApi()`? 

Reading the [documentation here](http://docs.identityserver.io/en/latest/topics/add_apis.html#adding-more-api-endpoints), and [this blog post about Authorize Attribute not working](https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/) I can't figure out if this is possible.

### Minimal working example

```csharp
services.AddAuthentication("Bearer")
.AddLocalApi("Bearer", o => {/* how can I specify NameClaimType here?*/});
```
Everything works fine, but User.Identity.Name is always null. If I manually force a claim (via my custom ProfileService) that matches the DefaultNameClaimType it does work, but was hoping to avoid adding extra claims.

**Comment by leastprivilege** [comment]
It uses name and role.

https://github.com/IdentityServer/IdentityServer4/blob/5f9c637a8ff2eaf715efb2629ac8c4b08b063b2a/src/IdentityServer4/src/Hosting/LocalApiAuthentication/LocalApiAuthenticationHandler.cs#L83

**Comment by fuzzzerd** [comment]
Would making NameClaimType and RoleClaimType for LocalApi be configurable be a matter of adding two parameters to the LocalApiAuthenticationOptions class and using those if not null, otherwise defaulting to the existing ones? 

Would you be inclined to accept a PR with that addition?

With respect to the transformation afterwards, is something like this what you mean?

```csharp
services.AddLocalApiAuthentication(principal =>
{
    principal.Identities.First().AddClaim(new Claim(JwtClaimTypes.Name, principal.Identities.First().FindFirst("custom_name_claim").Value));

    return Task.FromResult(principal);
});
```

**Comment by fuzzzerd** [comment]
For anyone that finds this down the road, and to avoid a [denvercoder9](https://xkcd.com/979/) situation, this is what ultimately worked using IdentityServer4 v3.1.0 (potential future PRs not withstanding):

```csharp
.AddLocalApi("Bearer", o =>
{
    o.Events = new IdentityServer4.Hosting.LocalApiAuthentication.LocalApiAuthenticationEvents
    {
          OnClaimsTransformation = (c) =>
          {
               var identity = c.Principal.Identities.First();
               identity.AddClaim(new Claim(JwtClaimTypes.Name, identity.FindFirst("custom_name_claim").Value));
               identity.AddClaim(new Claim(JwtClaimTypes.Role, identity.FindFirst("custom_role_claim").Value));
               return Task.CompletedTask;
           }
      };
});
```

**Comment by leastprivilege** [comment]
> Would making NameClaimType and RoleClaimType for LocalApi be configurable be a matter of adding two parameters to the LocalApiAuthenticationOptions

Don't use `.Name` anymore - it is deprecated.
