### ISSUE TITLE
Will IdentityServer4 will work out of the box for PostGreSQL

### ISSUE THREAD

**Issue by TameezM** [IdentityServer/IdentityServer4#4014]
It just a clarification question not a bug instead.  Will  IdentityServer4 will work out of the box for PostGreSQL  For our project, we want to use PostGreSQL rather than MSSQL as it involves license cost.

**Comment by UmutComlekci** [comment]
Off-course, It is possible to use PostgreSQL database for IdentityServer4. You only need to write your own storage classes or use some nuget packages. I'm not sure they are working but you can read [Identity Server With PostgreSQL](https://medium.com/@aspram.shadyan.dev/identityserver4-with-postgresql-as-a-persistence-store-9941060d047f) or you can try [IdentityServer4 Postgresql](https://github.com/sphiecoh/IdentityServer4.Postgresql) nuget package.
