### ISSUE TITLE
Where is AddIdentityServerUserClaimsPrincipalFactory ?

### ISSUE THREAD

**Issue by Pilchard123** [IdentityServer/IdentityServer4#4016]
As mentioned in #1285, #1498, #2682 and [others](https://github.com/IdentityServer/IdentityServer4/issues?q=is%3Aissue+AddIdentityServerUserClaimsPrincipalFactory+is%3Aclosed), `AddIdentityServerUserClaimsPrincipalFactory` should be used to add username, email and phone number to the token. It's apparently found in the IdentityServer4.AspNetIdentity package, but I've installed that, and it doesn't seem to exist. Is that still the right place to look for it? Or should I be using a different function entirely?

**Comment by brockallen** [comment]
When you call `AddAspNetIdentity` it's added:

https://github.com/IdentityServer/IdentityServer4/blob/master/src/AspNetIdentity/src/IdentityServerBuilderExtensions.cs#L33
