### ISSUE TITLE
How invalidate token in hybric flow

### ISSUE THREAD

**Issue by noufionline** [IdentityServer/IdentityServer4#402]
Hi @leastprivilege , @brockallen 

If I block a user in my database I want my mvc application to be logged out when user tries to navigate to any link. In an asp.net identity application I achieved this by implementing a custom SecurityStampValidato like this.

```
  public virtual async Task ValidateAsync(CookieValidatePrincipalContext context)
        {

            var user = await _signInManager.ValidateSecurityStampAsync(context.Principal);
            if (user == null || user.IsBlocked)
            {
                context.RejectPrincipal();
                await _signInManager.SignOutAsync();
            }
            else
            {
                var currentUtc = DateTimeOffset.UtcNow;
                if (context.Options != null && context.Options.SystemClock != null)
                {
                    currentUtc = context.Options.SystemClock.UtcNow;
                }
                var issuedUtc = context.Properties.IssuedUtc;

                // Only validate if enough time has elapsed
                var validate = (issuedUtc == null);
                if (issuedUtc != null)
                {
                    var timeElapsed = currentUtc.Subtract(issuedUtc.Value);
                    validate = timeElapsed > _options.SecurityStampValidationInterval;
                }

                if (validate)
                {  
                    // REVIEW: note we lost login authenticaiton method
                    context.ReplacePrincipal(await _signInManager.CreateUserPrincipalAsync(user));
                    context.ShouldRenew = true;
                }
            }
        }
``` 
but the mvc application doesn't have any reference to Identity as Identity management is implemented in Identity Server as per the quick start [https://identityserver4.readthedocs.io/en/dev/quickstarts/6_aspnet_identity.html](https://identityserver4.readthedocs.io/en/dev/quickstarts/6_aspnet_identity.html)

In this scenario do we have an extension point where we can invalidate the token if the user is blocked ?

while reading the document found out that the identity is saved as a token (identity_token).

on each request from where this token is assigned to the current user. is it possible to access that point?

**Comment by brockallen** [comment]
You would need to implement something to check your user database. Nothing in OIDC or IdentityServer has that built-in.

**Comment by noufionline** [comment]
@brockallen ok thanks.
Can you please tell me how claimsprincipal is created on the mvc client side using identity_token?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

**Comment by noufionline** [comment]
@brockallen Ok. Thanks I will do that.
