### ISSUE TITLE
end session endpoint: Is it realy secure to provide the id_token_hint ?

### ISSUE THREAD

**Issue by bpt-dev** [IdentityServer/IdentityServer4#4020]
Hi

According to this documentation http://docs.identityserver.io/en/latest/endpoints/endsession.html when calling the end session endpoint you can provide the id_token_hint to avoid being prompted for sign-out confirmation.
Some clients reported this as a security defect during security audit and raised some alert like the following:
> This application contains a session token in the query parameters. A session token is sensitive information and should not be stored in the URL. URLs could be logged or leaked via the Referer header.

Are we really wright to claim this is not a security issue at all? Any advice are welcome about how we should argue in this case.

Regards

**Comment by leastprivilege** [comment]
That's how the spec is written - and that's how it is implemented - yes.

Depending on the definition of "sensitive" - there could be sensitive data inside the token (if you put that in there). But this token cannot be used to login or anything like that.

**Comment by bpt-dev** [comment]
Thank you for your quick help.

Regards.
