### ISSUE TITLE
Missing properties in ModelBuilderExtensions

### ISSUE THREAD

**Issue by hugoqribeiro** [IdentityServer/IdentityServer4#4025]
### Issue / Steps to reproduce the problem

The following properties have been added to the ConfigurationDbContext entities:

[ApiResource](https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Entities/ApiResource.cs):

```
public DateTime Created { get; set; } = DateTime.UtcNow;
public DateTime? Updated { get; set; }
public DateTime? LastAccessed { get; set; }
public bool NonEditable { get; set; }
```

[IdentityResource](https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Entities/IdentityResource.cs):

```
public DateTime Created { get; set; } = DateTime.UtcNow;
public DateTime? Updated { get; set; }
public bool NonEditable { get; set; }
```

[Client](https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Entities/Client.cs):

```
public DateTime Created { get; set; } = DateTime.UtcNow;
public DateTime? Updated { get; set; }
public DateTime? LastAccessed { get; set; }
public bool NonEditable { get; set; }
```

The problem is that [ModelBuilderExtensions](https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Extensions/ModelBuilderExtensions.cs) was not updated accordingly in the following methods:

```
public static void ConfigureClientContext(this ModelBuilder modelBuilder, ConfigurationStoreOptions storeOptions);
public static void ConfigureResourcesContext(this ModelBuilder modelBuilder, ConfigurationStoreOptions storeOptions);
```

This causes EF to ignore any change to this properties on updates.
I don't see any to way to work around this to populate these properties from my admin UI.

**Comment by scottbrady91** [comment]
Nope, not in v3 anyway

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
