### ISSUE TITLE
Swagger UI Branch Approval

### ISSUE THREAD

**Issue by amadard** [IdentityServer/IdentityServer4#4027]
@leastprivilege or @brockallen Will you take a look at the [branch](https://github.com/amadard/IdentityServer4/tree/features/swagger) I started for adding Swagger json generation support, and let me know if what I have added thus far is acceptable?  This is coming from the #2286 discussion.

I want to make sure my decisions are acceptable before I get to a PR.

**Comment by leastprivilege** [comment]
I personally are not interested in having Swagger support for protocol endpoints. I also don't want to maintain that code.

**Comment by amadard** [comment]
Understood, would you be against a separate project?

**Comment by leastprivilege** [comment]
No . not at all. Feel free to that in your own repo.
