### ISSUE TITLE
User.IsInRole() issue

### ISSUE THREAD

**Issue by DaveThorson** [IdentityServer/IdentityServer4#403]
I’m seeing some conflicting/confusing behavior when evaluating User.IsInRole().

I'm using example code (Identity Server & MVC Client).  I have database storage for both Identity Server and Asp.Net Identity.

In the Asp.Net Identity database I have a Role, using the tables appropriate for roles, we’ll call it “AdminRole”, I’ve also created a claim in the claims table, ClaimType “Role”, value “UserRole”.  This is not how I would actually implement roles, but this will illustrate the issue I’m seeing.

In both the MVC Client and the Identity Server ‘client’, I have code that evaluates the user roles:  User.IsInRole().

Give the following scenarios this is the behavior I’m seeing:

AspNetRoles table: “AdminRole”
AspNetUserClaims: ClaimType: “role”; ClaimValue: “UserRole”

MVC Client: User.IsInRole(“AdminRole”) returns false
MVC Client: User.IsInRole(“UserRole”) returns false

Identity Server: User.IsInRole(“AdminRole”) returns true
Identity Server: User.IsInRole(“UserRole”) returns true

If I change the Claim type in AspNetUserClaims to:

AspNetUserClaims: ClaimType: “**http://schemas.microsoft.com/ws/2008/06/identity/claims/role**”; ClaimValue: “UserRole”

MVC Client: User.IsInRole(“AdminRole”) returns false
**MVC Client: User.IsInRole(“UserRole”) returns true**

Identity Server: User.IsInRole(“AdminRole”) returns true
**Identity Server: User.IsInRole(“UserRole”) returns false**

The claims output for both clients is identical in regards to the role claims.  

Additionally, I have the scope type set to ScopeType.Identity (I wasn't seeing the roles in the MVC Client otherwise), and the IncludeAllClaimsForUser = true.

**Comment by leastprivilege** [comment]
See here

https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
