### ISSUE TITLE
Howto deploy IdentityServer in Azure with MTLS enabled?

### ISSUE THREAD

**Issue by HansKindberg** [IdentityServer/IdentityServer4#4035]
I would like to deploy IdentityServer4 to Azure. I understand your demo-site, https://demo.identityserver.io, is deployed in Azure. I have read this:

- https://github.com/IdentityServer/IdentityServer4/issues/577

But as I can see, mutual TLS, is not configured for your demo-site. If I want to configure mutual TLS, http://docs.identityserver.io/en/latest/topics/mtls.html. **Do you know what Azure component I would need for that?**

You can configure TLS mutual authentication for Azure App Service, https://docs.microsoft.com/en-us/azure/app-service/app-service-web-configure-tls-mutual-auth. But not for a specific endpoint, /connect/mtls. And I cant see how you would set up a certificate trust list for it.

What I have found is that you may fix it with an "API Management service" and maybe with an "Application Gateway". What I want to accomplish is instead of this:

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/host/web.config#L15

I know you can accomplish it by setting up virtual machines with IIS. But I would like to use App Services.

I know this is not really an IdentityServer question but you maybe just can point me in the right direction.

Regards Hans

**Comment by leastprivilege** [comment]
Yea . I don't know. I have found that IIS is mostly in the way when it comes to MTLS. And the way I understand it is that you cannot setup paths for MTLS in Azure.

FWIW - my test setup is using nginx

**Comment by HansKindberg** [comment]
Thank you, I will have a look at that.
