### ISSUE TITLE
Upcoming Browser Behaviour Changes that may need IdSrv changes

### ISSUE THREAD

**Issue by marzoukali** [IdentityServer/IdentityServer4#4039]
Hello Guys,

There are upcoming browser changes that may affect the work of identity providers with browsers and cookie-based authentications and i think you guys aware of this. 

It's described below: 
https://auth0.com/blog/browser-behavior-changes-what-developers-need-to-know/

My questions here, are there any changes or awareness for us as IdSrv users to take care of or to implement to be up to date with those changes?

**Comment by leastprivilege** [comment]
Yes, make sure you are on the latest versions of ASP.NET Core and IdentityServer and implement the browser sniffing logic that Microsoft published.
