### ISSUE TITLE
Detect "DB Down" and return an error in ".well-known/openid-configuration"

### ISSUE THREAD

**Issue by arogges** [IdentityServer/IdentityServer4#4040]
### Question

Dears,
in my installation of IdS4 I use mySql (with Entity Framework) for User Store and json files for clients configuration: I realized that when the mySql service is stopped, the .well-known/openid-configuration api responds correctly however.

My question is: in your opinion, what's the best method to propagate the connection error towards the .well-known/openid-configuration api response?

**Comment by leastprivilege** [comment]
I would rather implement a health check endpoint.

**Comment by brunohbrito** [comment]
@arogges `.well-know/openid-configuration` endpoint is OpenId compliant and have different pourposes. So for this case isn't the best option. 

Could you try [AspNetCore.Diagnostics.HealthChecks](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks). It publish a healthcheck endpoint, which is one of the best alternative for your needs.
