### ISSUE TITLE
limit ApiResource to certain clients

### ISSUE THREAD

**Issue by OneCyrus** [IdentityServer/IdentityServer4#4045]
currently we are able to limit the access to certain resources by specifying `AllowedScopes` in the client. this allows us to set some constraints on the client. there are also some certain scenarios where we need to limit clients from using specific ApiResources.

Now i'm wondering if there is also something like 'AllowedClients' for ApiResources. I couldn't find a settings which would allow this. So I assume this isn't possible right now. sure i could code this on top of identityserver or limit on the API itself. but i think this would be a very nice way to set some additional constraints directly on the IdP.

**Comment by leastprivilege** [comment]
No . it's the other way round, you grant access to scopes via the client settings.

**Comment by OneCyrus** [comment]
that's very unfortunate from a security point of view.

**Comment by leastprivilege** [comment]
why?
