### ISSUE TITLE
Make `UserInfoEndpoint` extendable

### ISSUE THREAD

**Issue by asleire** [IdentityServer/IdentityServer4#4046]
**Is your feature request related to a problem? Please describe.**
The OpenID Connect Core specification indicates that the UserInfo endpoint may return a signed and/or encrypted JWT instead of JSON.

The current `UserInfoEndpoint` implementation only supports the JSON format. 

**Describe the solution you'd like**
The optimal solution would for IdentityServer4 to support signed and/or encrypted UserInfo responses, but the easier solution is to make it easier to customize `UserInfoEndpoint`. 

-  `UserInfoEndpoint` would need to be `public`
- `BearerTokenUsageValidator` would need to be `public` OR modified to implement a public interface
- `UserInfoEndpoint.Error` would need to be `protected`
- `UserInfoEndpoint.ProcessAsync` and `UserInfoEndpoint.ProcessUserInfoRequestAsync` should be made virtual

**Describe alternatives you've considered**
Currently creating a custom UserInfo endpoint can be accomplished by copying the source code of `UserInfoEndpoint`, `BearerTokenUsageValidator` and `ProtectedResourceErrorResult` and modify `UserInfoEndpoint` to suit our needs.

I can make a PR with proposed changes if interested

**Comment by leastprivilege** [comment]
Wouldn't it be sufficient to override the UserInfoResponseGenerator?

**Comment by asleire** [comment]
> Wouldn't it be sufficient to override the UserInfoResponseGenerator?

`IUserInfoResponseGenerator` creates a dictionary containing the JSON properties to return. One cannot override it to return a JWT

**Comment by leastprivilege** [comment]
OK thanks - we will discuss this. Might not be immediate.

**Comment by leastprivilege** [comment]
We don't have any immediate plans to do this. We will re-visit this for the next version.
