### ISSUE TITLE
Improve support for overriding Endpoints

### ISSUE THREAD

**Issue by asleire** [IdentityServer/IdentityServer4#4047]
**Is your feature request related to a problem? Please describe.**
There is currently no neat way of overriding an existing endopint.

**Describe the solution you'd like**
A neat way of overriding an endpoint that doesn't require copying source code from IdentityServer4.

A simple solution is to make `EndpointRouter` public, which would allow developers to make a simple class like below in order to use the latest-registered endpoints.
```
internal class ReversedEndpointRouter : EndpointRouter {
    public ReversedEndpointRouter(IEnumerable<Endpoint> endpoints, IdentityServerOptions  options, ILogger<EndpointRouter> logger) : base(endpoints.Reverse(), options, logger)
    {
    }
}
```

**Describe alternatives you've considered**
The alternatives I've found are 
1) the workaround in #2273 which involves copying the source code of `.AddEndpoint()`
2) creating a custom implementation of `IEndpointRouter` which is most easily done by copying the source code of `EndpointRouter` and modify it slightly

**Comment by leastprivilege** [comment]
The current plan is to switch to the new endpoint routing in ASP.NET Core 3.x
