### ISSUE TITLE
Add "switch user account" method to IIdentityServerInteractionService for Consent Page

### ISSUE THREAD

**Issue by ryanelian** [IdentityServer/IdentityServer4#4049]
**Is your feature request related to a problem? Please describe.**

Currently there are two options when dealing with consent:
- Grant the consent
- Deny the consent somehow

I would love to have a third option, which is to allow switching user account for the ongoing authorization flow.

**THIS IS NOT A REQUEST FOR HANDLING MULTIPLE ACCOUNT LOGIN (https://github.com/IdentityServer/IdentityServer4/issues/717)**

![image](https://user-images.githubusercontent.com/8892187/73779406-47f84500-47bf-11ea-9f1c-a099b126da42.png)

**Describe the solution you'd like**
There should be a method in `IIdentityServerInteractionService` to sign-out the currently signed-in user, then redirect the user to the sign-in page again, restarting the authorization flow.

Something like:

```cs
await HttpContext.SignOutAsync();
var loginPageUrlWithReturnUrlQuery = await IIdentityServerInteractionService.RedirectToLoginPage(returnUrl);
return Redirect(loginPageUrlWithReturnUrlQuery);
```

**Describe alternatives you've considered**
~~I have managed to implement this feature by using dirty hacks via Referer header (sign out manually then redirect the user back to the RP so that the user gets redirected back to the IDP).~~

~~But this is grossly inefficient and might fail if the RP `Referrer-Policy` HTTP header is set to no referrer (unreliable)...~~

**Additional context**
IdentityServer should be able to reconstruct the authorization flow redirect URL for the login page from the consent page, but I don't have the expertise to do this.

**Comment by brockallen** [comment]
Can't a custom redirect solve the problem?

**Comment by ryanelian** [comment]
I am at loss as to how to reconstruct the returnUrl query parameter for the login page for IdentityServer4 to digest.

As far to my understanding, that returnUrl format is something only IdentityServer4 understand.

If there are existing method to generate the returnUrl for the login page, please enlighten me.

**Comment by brockallen** [comment]
When you set a custom redirect, the returnUrl is automatically passed to that page (like it is for the login page).
