### ISSUE TITLE
Combined AspId and EFStorage -- deprecated

### ISSUE THREAD

**Issue by ClientIco** [IdentityServer/IdentityServer4#4054]
Hi 

What was the reason for deprecating these ?

**Comment by leastprivilege** [comment]
maintenance cost

**Comment by GFoley83** [comment]
The IdS 4 + ASP.NET Identity + EF Core combo is still going to be the stack of choice for a lot of enterprise projects moving forward; will there be any guidance on this at all? E.g. documentation. 
Or is it a case of, if you're using that particular stack, you're on your own.

**Comment by leastprivilege** [comment]
I agree. But we only so many hours a week to work on free stuff.

EF nor ASP.NET Identity is not really IdentityServer related. But we do consulting if "enterprises" need help.
