### ISSUE TITLE
Make Scope property on AuthorizeResponse settable

### ISSUE THREAD

**Issue by user1336** [IdentityServer/IdentityServer4#4055]
In the OAuth2 authorization_code flow (no OIDC) the `Scope` property is always included in the AuthorizeResponse. We would like to exclude it on this response so we can create the following response:
HTTP/1.1 302 Found
Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
(without including the granted scopes).
This would conform the following section:
http://tools.ietf.org/html/rfc6749#section-4.1.2

It's readonly and [defaults](https://github.com/IdentityServer/IdentityServer4/blob/44651bea9b02c992902639b21205f433aad47d03/src/IdentityServer4/src/ResponseHandling/Models/AuthorizeResponse.cs#L18) to: `Request?.ValidatedScopes?.GrantedResources?.ToScopeNames()?.ToSpaceSeparatedString();`

Would it be possible to create a (private) set so we can override it and construct a response on the Authorize endpoint? We could probably change this in de override of the `CreateCodeAsync` in the `AuthorizeResponseGenerator`.

**Comment by leastprivilege** [comment]
why?

**Comment by user1336** [comment]
Data minimalization, the (external) client breaks because there is more information in the response. I realize that they don't comply the spec (don't ask..).
On the other hand, I think it should nice to construct a response that matches the spec exactly without additional parameters. 

I can probably do a PR if you're open to it.

**Comment by leastprivilege** [comment]
We need to discuss this first.

**Comment by user1336** [comment]
Sure -- keep me posted about the progress.

**Comment by user1336** [comment]
Have you got a chance to look at this? Is there anything I can do to help?

**Comment by brockallen** [comment]
Sorry, we don't plan on doing this. Sorry.
