### ISSUE TITLE
Bearer token stops working

### ISSUE THREAD

**Issue by dribeiroo** [IdentityServer/IdentityServer4#4058]
Hi all,

I have identity server 4 with .Net Core 3.1 installed as Azure App Service. I also have a couple of APIs that checks tokens on identity server. The solution has build and release on TFS. During release, the app aervice os stopped and then started again.

If I call identity server to generate a token, by using user credentials and cliente secret, a token is issues correctly. The client os configured with a huge token expiration.

Then I start using the token like a charm, but if I Run a new build and a new release then the token stops working and I must get a new One.

My question is if this is a normal behavior. My understanding is that the token should work regardless of a release ir a stop/start. So my guess is that this is nota normal. Do you know of anything that could cause this?

A couple of things:
On the release definition, there was a setting during deploy that was deleting files before release. Que unchecked this today.
Data seed is off, so this is not running
No Database Change was made
No configuration Change was made
The only thing we added was showpii setting to true
It seems to not be related with .net Core 3.1, since it happened on 3.0 as well.

Hope I provided every detail, any help would be great. Thanks

**Comment by leastprivilege** [comment]
Where do you store the key material for signing the tokens?

**Comment by dribeiroo** [comment]
Hi, thank you for your reply. I'm sorry but I don't understand what you are refering to, where can I check that?

**Comment by leastprivilege** [comment]
Something must happen when you re-cycle the server that makes the token invalid. One could be that the key material becomes invalid.

**Comment by dribeiroo** [comment]
Yes that's what we also suspect but we don't know what.
What do you refer to when you mention the key material? What's that? The place were data is stored, the solution files..? Can you detail a little bit more what is that? Probably is something quite simple, but we are new at Identity server. Thanks.

**Comment by Kibsgaard** [comment]
You probably lack an implementation of the operational database store (e.g. where refresh tokens are stored, so they persist between restarts and multiple instances).
There is a quick start on implementing it with EntityFramework:
http://docs.identityserver.io/en/latest/quickstarts/5_entityframework.html

If you want to roll your own, take a look at:
https://www.scottbrady91.com/Identity-Server/Creating-Your-Own-IdentityServer4-Storage-Library

There are also storage solutions to different platforms (cosmosDB, mongoDB, etc.) on github, but I don't know how up-to-date they are.

**Comment by dribeiroo** [comment]
You mentioned refresh tokens that rings a bell here.

What I'm doing is issuing a new token by calling /connect/token API which gives me a token, that has a huge expiration date.
Then I use that token on my APIS without any problem.
But I don't perform any refresh or any further operation, I mean I use the token resulted from connect/token API and that's it.

Am I doing it wrong? After issuing a new token using /connect/token should I do anything else?

**Comment by brunohbrito** [comment]
Even if you implement the operational databases will not resolve the problem of key material.
Maybe your problem is that your JWK is recycling when you redeploy your server. 

You can make a test by looking at `/.well-known/openid-configuration/jwks` before. Then look again after your deploy.

If it changes it's the root of why the tokens became invalid.
