### ISSUE TITLE
end session on closing browser 

### ISSUE THREAD

**Issue by GopalZadafiya** [IdentityServer/IdentityServer4#4060]
I want to end session when user closes the browser or tab. user should be asked for login again while opening the page again in new tab or new window. 

So basically I want to implement non-persistent cookies.

I tried setting **isPersistent** value to **false** for signIn methods for local and external users as below but still It is not asking for credentials again.
            
`await _signInManager.SignInAsync(user, isPersistent: false);`

`await _signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey, isPersistent: false, bypassTwoFactor: true);`

Is there any configuration in Identity Server that can help me to achieve this ?

**Comment by leastprivilege** [comment]
Use the browser tools to check if the cookie is a session cookie or not.

**Comment by GopalZadafiya** [comment]
It looks something liek this :

![image](https://user-images.githubusercontent.com/13184438/73918492-bb957180-48e7-11ea-9b69-6636b45394cf.png)

**Comment by leastprivilege** [comment]
These are all session cookies. So closing the browser should delete them. Unless you have some weird settings enabled...

**Comment by GopalZadafiya** [comment]
What could be those settings possibly ? 

I am using angular-oauth-oidc library to use these authentication on Angular SPA. but I think that couldn't be the issue as it only deals with sessionStorage and localStorage.
