### ISSUE TITLE
Aquire access_token using mobile phone number

### ISSUE THREAD

**Issue by marzoukali** [IdentityServer/IdentityServer4#4062]
Hello Guys,

I am looking for a sample or a guideline on how to authenticate people using mobile phone number or passwordless flow. I've checked the demos and the samples here but can't find any. I just want to make sure if it's easy to achive and some guidelines to how to do that, which flow is the best for it and which handlers should i override and if it's possible to integrate that as part of AspCore Identity?

**Comment by amadard** [comment]
I cant speak to the security of it, or the guidelines, but this could be achievable using an [extension grant](http://docs.identityserver.io/en/latest/topics/extension_grants.html).  You could have the phone number as a request parameter, then look up the sub using the phone number.

Client credentials would be my greatest concern, the secret needs to be kept secure.

**Comment by marzoukali** [comment]
I've seen this implementation: https://github.com/Jurabek/IdentityServer4.PhoneNumberAuth .. I think it's the clearest sample out there.
