### ISSUE TITLE
Access Client Claim in Api Resource

### ISSUE THREAD

**Issue by VincentNeutsDel** [IdentityServer/IdentityServer4#4063]
### Scenario
We have an API that handles all the audits of multiple applications, we want to protect this API by using identity server.  

There are 2 type of clients that want to connect to it:
-  with full access, a "trusted client"
-  one with only read access, "a SPA"

Both clients should only be able to access the audit for their application. 

For this I should get 2 claims from the client, for example:
- AuditAccessLevel = "read/write" OR "read"
- AuditAppName = "Library" (Can be whatever) => used to determine which audits is had access to. 

### Possible Solution
An option would be to include all the client claims in the access token, but that would mean that it would be send in each request and that seems unnecessary because only one API resource would make use of it. 

### Questions
- **Is it possible for an API resource to request client claims to the IDP?**
- **What are client properties and can they be used for this?**  

Maybe I'm seeing this all wrong, any suggestion on how I should handle this is more than welcome! 

Cheers,

**Comment by brockallen** [comment]
Why not scope?

**Comment by amadard** [comment]
If you are mapping specific auditappnames to specific audits for access, the resource server can extract the clientid from the access token and the the resource server uses that for the lookup, inside the resource server.

Read and write can be scope, or if they are client specific, you can map the access based on client id in the resource server.

**Comment by VincentNeutsDel** [comment]
> the resource server can extract the clientid from the access token and the the resource server uses that for the lookup, inside the resource server

Which endpoint should I use to request the information about a client? 
   I probably can't use the userinfo endpoint because that is meant for: "to retrieve identity information about a user" and I need information about a client.

**Comment by VincentNeutsDel** [comment]
> Why not scope?

Scope is indeed a good idea for the access, and that is what I did as shown in[ this example](http://docs.identityserver.io/en/latest/topics/resources.html#defining-api-resources)

But adding a different scope for each different appname that uses the application looks a but cumbersome.

**Comment by leastprivilege** [comment]
This sounds like application logic to me. Why is IdentityServer involved here?

IS sends a client identity to your audit API. Have records at the API that determine the access level.
