### ISSUE TITLE
Remove use of "so called" in the docs

### ISSUE THREAD

**Issue by ngbrown** [IdentityServer/IdentityServer4#4064]
While working through the quickstart sections, I've seen the phrase "so called" several times.

For [example](http://docs.identityserver.io/en/latest/quickstarts/2_interactive_aspnetcore.html#creating-an-mvc-client):
> We use the **so called** `authorization code` flow with PKCE to connect to the OpenID Connect provider. See here for more information on protocol flows.

A common definition is "falsely or improperly so named" (example "deceived by a so-called friend").  So it's a little jarring to read.

The extra words aren't needed, so just removing entirely is sufficient.

There are 6 instances that need replaced:
https://github.com/IdentityServer/IdentityServer4/search?q=%22so+called%22&unscoped_q=%22so+called%22

**Comment by leastprivilege** [comment]
Thanks. Did you see the "edit" link on the docs pages?

**Comment by leastprivilege** [comment]
@ngbrown Are you sending a pull request?
