### ISSUE TITLE
C# IdentityServer SSO Password Expiry Notification

### ISSUE THREAD

**Issue by bharathkumarreddyng** [IdentityServer/IdentityServer4#4074]
I am using IdentityServer and Single Sign On.My requirement is when User logins and if User is going to expire I have to show a pop up(Information with OK button) saying User is going to expire soon and when User clicks on OK he should be redirected to redirectUri.

I am new to IdentityServer so can you give me some suggestions or links to see how this can be implemented.I have done some googling and see that if I use PostAuthenticateAsync or DefaultViewServiceOptions I may solve this problems(But I am not sure).

enter image description here

**Comment by brockallen** [comment]
The UI is entirely customizable, so do that where you need/want in the login workflow.
