### ISSUE TITLE
http://docs.identityserver.io/ doesn't have valid SSL certificate

### ISSUE THREAD

**Issue by drk-mtr** [IdentityServer/IdentityServer4#4076]
I'm enjoying the irony, but it would probably give a better impression if it can be updated...

**Comment by leastprivilege** [comment]
Interesting - readthedocs does an automatic redirect. That's new.

Which irony exactly are you enjoying?

**Comment by drk-mtr** [comment]
Irony because a guide about security doesn't have a working security cert :) 

It's not concerning since it's a very read only site so I wasn't sure whether to raise as a bug.

**Comment by leastprivilege** [comment]
OK. thanks.
