### ISSUE TITLE
ResourceOwnerPasswordValidator can only find by username

### ISSUE THREAD

**Issue by TrabacchinLuigi** [IdentityServer/IdentityServer4#4079]
https://github.com/IdentityServer/IdentityServer4/blob/94ee1947c721723e8aa8272c35335f4819546ea1/src/AspNetIdentity/src/ResourceOwnerPasswordValidator.cs#L56

Usually Username and Email coincide, but in our case they don't.
But we'd like to let our customers log in using username or email.
We could rewrite that class and substitute it in the services for now, but i think it would be way better if the one shipped by default would search first by username and if it doesn't find anything then search by email

```
var user = await _userManager.FindByNameAsync(context.UserName);
if (user == null)
{
    user = await _userManager.FindByEmailAsync(context.UserName);
}
if (user != null)
{
...
```

**Comment by brockallen** [comment]
So then write your own by implementing the extensibility point.

**Comment by TrabacchinLuigi** [comment]
I already did that, that is kinda overkill for just two more lines of code, also this code have to be mantained, and I think everyone would benefit from that. So why not merging this instead?

**Comment by brockallen** [comment]
Because I don't agree that all systems want the email as the username. Also, you could have set email to not unique in AspId. There are too many "what ifs", we have a fairly clear default implementation, and if you need something else it is extensible.

**Comment by TrabacchinLuigi** [comment]
Thanks for your time, make perfectly sense, also reminded me that i have to filter users that haven't confirmed the mail!
