### ISSUE TITLE
Broken dependencies using IdentityServer4 and EntityFramework Storage from classlib/netstandard project.

### ISSUE THREAD

**Issue by ghorsey** [IdentityServer/IdentityServer4#4080]
So for our application, we are building custom endpoints around the IdentityServer4 entity models with custom querying, etc.  We have all data access code in Repository classes behind repository interfaces.

Previously we could reference both IdentityServer4, and IdentityServer4.EntityFramework dependencies from our netstandard class lib.

### Issue / Steps to reproduce the problem
1. Create a class lib project, for say a Repository (netstandard2.1)
2. Attempt to add a reference to IdentityServer4 or IdentityServer4.EntityFramework

#### Expected Result
1. Nuget installs dependencies

#### Actual Result
1. Nuget fails to install package because netcoreapp3.1 dependency for both.

I believe netstandard2.1 cover both dotnet core 3.0 and 3.1. This breaking change definitely limits usability of these class libraries.

**Comment by ghorsey** [comment]
If I understand things correctly,  netcoreapp is supposed to be used for applications (like aspnet apps/console apps) whereas netstandard should be used for libraries.  

I believe that identityserver4  is a great library (netstandard lacking `public static main`) that adds OpenId/OAuth/Security to an aspnet apps (netcoreapp with a `public static main`).

Maybe I'm off base on this, or there is a security concern that I am just do not know about.

**Comment by leastprivilege** [comment]
IdentityServer references ASP.NET Core - which is netcoreapp3.1.

**Comment by ghorsey** [comment]
@leastprivilege I was hoping to have a little more of a conversation.  

To have that dependency ripple through your framework even into your entity framework packages feels like a breaking change and would warrant a major version upgrade.

Architecturally there has to be a better way to isolate the netcoreapp3.1 dependency from the rest of the library/framework.

Your tool is amazing, I was very bummed to see this change because it broke much of my code.  Not everyone would have all their application code in a aspnet web project, especially if working on a more advance architecture (like microservices based).

I'll try to take a fork of the app and isolate the dependency and send you a pull request.

**Comment by brockallen** [comment]
> To have that dependency ripple through your framework even into your entity framework packages feels like a breaking change and would warrant a major version upgrade.

I think we changed the version from 2.x to 3.x, no?

Anyway, as Dominick said it's not something we had much of a choice over.

**Comment by ghorsey** [comment]
@brockallen my bad. Maybe I didn't notice the version bump. 

I think architecturally/structurally where the prob is, is that the identityserver4.csproj is too big. (That's not a criticism on what you guys built, it is a feat and I'm thankful for your work.) 

I'm about 50% through the refectoring now. It might not be the direction you guys want to go, but I'm trying to be least impactful with it. I'm basically splitting out a identityserver4.common assembly and keeping the namespaces to isolate the netcoreapp framework dep to the identityserver4 root csproj. 

You can check my progress here to see if it Sparks any ideas... https://github.com/ghorsey/IdentityServer4/tree/feature/isolate-netcoreapp3.1

**Comment by ghorsey** [comment]
So, I was wondering on my drive in to the office if the issue was because of adding a dependency to the aspnet core rollup package vs individual assemblies... 

I gave that a try this morning, wishing I thought about it last night... 

Turns out that there are only 2 classes with a hard dependency to Microsoft.AspNetCore.Authentication.OpenIdConnect which has the hard dependency on netcoreapp3.1.

I wish I did this yesterday....  Basically, I think I can move everything into a common netstandard2.1 assembly with the exception of: 

- /Configuration/IdentityServerServiceCollectionExtensions.cs
- /Configuration/ConfigureOpenIdConnectOptions.cs

which would need to remain in the root IdentityServer4.csproj file.

The common assembly can target netstandard2.1 and the root project can target netcoreapp3.1.

This experiment is at https://github.com/ghorsey/IdentityServer4/tree/feature/isolate-netcoreapp3.1v2.  Open the IdentityServer4.Local.sln to see the changes.

**Comment by ghorsey** [comment]
So @leastprivilege & @brockallen  I split the identityserver4 into 3 project:
- IdentityServer4.Common
  - netstandard2.1
- IdentityServer4.Configuration.Oidc 
  - netcoreapp3.1
  - has a reference to IdentityServer4.Common
- IdentityServer4 
  - netcoreapp3.1
  - meta package
  - has reference to IdentityServer4.Common
  - has reference to IdentityServer4.Configuration.Oidc
- IdentityServer4.EntityFramework
  - netstandard2.1
  - has a reference to IdentityServer4.Common

Going w/ the IdentityServer4 as a meta package approach should still give the same developer experience of just adding 1 package to a aspnet project, whereas for people doing other more advanced things can pull in the IdentityServer4.Common package to peel back the onion so to speak.

I can send a pull request, or you can just review my changes and incorporate them as you see fit.  

I still think the IdentityServer4.Common project is still too big and should be decomposed into separate packages.

Smaller packages that can be composed together may provide better flexibility for the framework you've all created!

See https://github.com/ghorsey/IdentityServer4/tree/feature/isolate-netcoreapp3.1v3 for my code.

I'd open the IdentityServer4.Ef solution to see how the things come together and build. 

Let me know if you'd like a PR!

**Comment by ghorsey** [comment]
Actually, I could have simplified the refactoring by merging the IdentityServer4.Configuration.Oidc classes into the IdentityServer4 assembly...  which may be better...

**Comment by leastprivilege** [comment]
thanks for spending the time! We will have a look at your repo ASAP.

**Comment by ghorsey** [comment]
No worries and glad to do the experiments! 

Thank you for an awesome framework!

**Comment by leastprivilege** [comment]
Is this the right branch?

https://github.com/ghorsey/IdentityServer4/blob/feature%2Fisolate-netcoreapp3.1v3/src/IdentityServer4%20.Common/src/IdentityServer4.Common.csproj

This is referencing netcoreapp3.1 and you are using ASP.NET Core 2.x dependencies. This doesn't make sense...

**Comment by ghorsey** [comment]
I didn't update every csproj file... I might have started in that file, but I mostly worked on the local variants.

The correct csproj file is the local https://github.com/ghorsey/IdentityServer4/blob/feature/isolate-netcoreapp3.1v3/src/IdentityServer4%20.Common/src/IdentityServer4.Common.Local.csproj

That said, I still do have several 2.2 dependencies in the common.csproj file that I didn't catch (late night coding after work) and am a little thrown by that.

In nuget the latest `Microsoft.AspNetCore.App` is 2.2.8.  I would have expected to see version 3.1. 

That being said, those classes that have the dependencies on the four 2.2 assemblies:
* Microsoft.AspNetCore.Authentication
* Microsoft.AspNetCore.Authentication.Cookies
* Microsoft.AspNetCore.Authorization.Policy
* Microsoft.AspNetCore.Cors

I should be pull them back up into the IdentityServer4.csproj file.  

It's strange that MS has not published the related 3.1 assembly variants including Microsoft.AspNetCore.App and dependencies to nuget. (Maybe I missed a blog somewhere).

I can clean up those 2.2 dependency oversights this evening after work to give a clear example.

However, I am just drawing lines around dependencies, but there may be more logical grouping around the items in IdentityServer4 (or my IdentityServer4.Common) to split into the separate assemblies that will have the most utility.  Maybe it makes more sense to only pull out Models into a separate assembly.

**Comment by leastprivilege** [comment]
Yeah - those packages don't exist anymore. They are part of what they called the "shared framework" and you need to be on 3.1 to reference them.

> However, I am just drawing lines around dependencies

Understood - but the devil is in the details. Let me know once you think you finished and polished everything.

**Comment by ghorsey** [comment]
Okay.  Just finished revising experiment 3 for ya.

https://github.com/ghorsey/IdentityServer4/raw/feature/isolate-netcoreapp3.1v3/src/IdentityServer4.Ef.sln

This is split apart just following dependencies.  So there is definitely a more logical separation possible here.

netstandard2.1:
* IdentityServer4.Common.Local
* IdentityServer4.EntityFramework.Local
* IdentityServer4.EntityFramework.Storage
* IdentityServer4.Storage.csproj

netcoreapp3.1
* IdentityServer4.Local.csproj

This can be more of a conversation starter and to show it's possible.

I think the root issue is that the IdentityServer4 project contains what should be several assemblies.

I'll start on a experiment 4 to improve the structure of the project, so that dependencies flow toward abstractions.  It's natural for dependencies to get loose/tangled when everything is in a single assembly.

**Comment by leastprivilege** [comment]
Don't put too much work into this. I am not sure we will be able to do that for the next release.

**Comment by leastprivilege** [comment]
...also ignore the Local projects.

**Comment by ghorsey** [comment]
Well, checkout what I did in that ef4 solution... if it make sense to you and looks good, I can update the non local csproj files.

Then I can attempt a Pull Request, if you'd like.

The experiment #4 about breaking out abstract assemblies is just to see if I can do it :)

I'm tired and got to get up early tomorrow for some meetings...

**Comment by ItsKaleb** [comment]
Has there been any further progress around this thread?
I would be keen to hear if there is an upgrade path to version 3.x that is compatible with netstandard libraries, as I believe I am in a similar position to the original author.

**Comment by leastprivilege** [comment]
We will not do this re-factoring for the next version - but will re-visit this in the .NET 5 timeframe (and if this is still needed then).

**Comment by ghorsey** [comment]
@leastprivilege Sounds great.  Thanks for the update and great library!
