### ISSUE TITLE
Secret Hashing Algorithm

### ISSUE THREAD

**Issue by danutzplusplus** [IdentityServer/IdentityServer4#4082]
Hello,

I’ve read through this previously open/now closed issue on the way client secrets are currently stored: https://github.com/IdentityServer/IdentityServer4/issues/284

And I’ve no issue with the lack of a salt, since as was said, secrets are not human created. 

But I believe one point was missed, which was actually asked by someone in the thread, but maybe got lost in the commotion. 

And namely why use only a single round of a SHA, when nowadays it’s very usual, when storing passwords, to use a workload algorithm with a big nr of iterations of hashing. Like for ex: PBKDF2 with 10k iterations to make bruteforcing impossible, even with rainbow tables. And they use this workload/interations regardless if I store a simple password or a 60 char random one.

I’m not an expert in security, so that’s why I’m curious to find out if/where I’m wrong in my assesment. 

Thanks

**Comment by leastprivilege** [comment]
The input to the hash should be a high entropy value, e.g. a GUID. So no need to do any kind of key stretching...

**Comment by danutzplusplus** [comment]
Ok, so SHA256/512 are technically impossible to bruteforce (at least for the foreseeable future) via a rainbow table as long as the secrets you’re hashing are random enough and occupy a large enough space, like guids do. 

I guess I was worried about how long or short it would take to generate a sha256 rainbow table of all guids. But then I realized we’re talking about ALL GUIDS. Which is a whole lot. 

Thanks for the explanation.

**Comment by leastprivilege** [comment]
;)

https://www.youtube.com/watch?v=S9JGmA5_unY
