### ISSUE TITLE
RequireRequestObject column missing from EF Migration SQL Script?

### ISSUE THREAD

**Issue by aaronhoffman** [IdentityServer/IdentityServer4#4083]
### Question

I am new to EF Migrations, so this is likely something simple I am just missing.

I am trying to configure IdentityServer from SQL/EF and following this quickstart: http://docs.identityserver.io/en/latest/quickstarts/5_entityframework.html

I am required to produce a SQL Script to modify the database, I am not able to allow EF to perform the migration on app startup, etc.

Using the master branch @3ebc137, the output of this command produces a set of three files:
`dotnet ef migrations add InitialIdentityServerConfigurationDbMigration -c ConfigurationDbContext -o Data/Migrations/IdentityServer/ConfigurationDb`

Files here: https://gist.github.com/aaronhoffman/d4ac6312e09b6d2140137aaca1a67653

And if I execute `dotnet ef migrations script --context ConfigurationDbContext -o config.sql` that will produce this sql script: https://gist.github.com/aaronhoffman/d4ac6312e09b6d2140137aaca1a67653#file-config-sql-L1

My question is: Why is the `RequireRequestObject` property not being included in the SQL Script?

I see it referenced in the  20200213083642_InitialIdentityServerConfigurationDbMigration.cs file, and the property was added to the class recently: https://github.com/IdentityServer/IdentityServer4/pull/4019/files

### Minimal working example

 above

### Relevant parts of the log file

 n/a

**Comment by brockallen** [comment]
I think we only added `RequireRequestObject` in our latest prerelease, thus the quickstart wouldn't yet have it.

**Comment by aaronhoffman** [comment]
I linked to the EF Quickstart for background more than anything. It may still reference an older version of the IdentityServer4.EntityFramework.Sorage package that would not have the new property, but I am not attempting to generate the SQL scripts based on the package reference within that quickstart, but by opening the IdentityServer4.EntityFramework.Sorage project itself at the @3ebc137 commit. (and running the EF migration CLI from that project/directory)

I am not familiar with EF Migrations, so I am not sure how they decide what the "starting point" of the migration is. I don't understand why that property/column (and only that property/column) is included in the "migration" Up() and Down() methods, and why it would not be included in the output config.sql.

**Comment by brockallen** [comment]
I think this commit is what you wanted? https://github.com/IdentityServer/IdentityServer4/commit/0bade7c2e3e25548960ebc5b639e68cc055b224e

also, as for the DB and migrations: https://identityserver4.readthedocs.io/en/latest/reference/ef.html
