### ISSUE TITLE
validation for required response_type OAuth 2.0 parameter is missing

### ISSUE THREAD

**Issue by zsalkus** [IdentityServer/IdentityServer4#4084]
https://openid.net/specs/openid-connect-core-1_0.html#JWTRequests specification states that:

> So that the request is a valid OAuth 2.0 Authorization Request, values for the response_type and client_id parameters MUST be included using the OAuth 2.0 request syntax, since they are REQUIRED by OAuth 2.0. The values for these parameters MUST match those in the Request Object, if present. 

However, if we don't include `response_type` into OAuth 2.0 request syntax, but include it into JWT Request parameter validation passes, because jwt payload values are merged into original request parameters in `AuthorizeRequestValidator.ReadJwtRequestAsync(...)` method.

The same bug doesn't exist for `client_id` because in `AuthorizeRequestValidator.ValidateAsync(...)` method code loads client before reads the JWT request parameter.

**Comment by leastprivilege** [comment]
That's what the OIDC spec says - yes. And their intention was not to break OAuth.

Now the OAuth JAR spec intentionally breaks OAuth by saying all parameters *can* be inside the JWT. So both is acceptable now.

**Comment by zsalkus** [comment]
If _all parameters can be inside the JWT_, then why client_id cannot be inside JWT in IdentityServer4?

_If both is acceptable_, then why there is no flexibility provided to have custom OAuth request params validator? There is an interface exposed for custom authorize request validation which is invoked at the end of the method, however, there is no use of it since JWT parameters are merged into OAuth request parameters already.

**Comment by leastprivilege** [comment]
> then why client_id cannot be inside JWT in IdentityServer4?

it can. The latest version on master allows this.

For the other question - I don't follow. What do you want to achieve?

**Comment by zsalkus** [comment]
I couldn't find the final specification of OAuth JAR. My organization prefers to follow OIDC specification which currently doesn't mention a possibility to omit required params. From my understanding there's no possibility to follow OIDC spec if we're using .NET Core 3.x.

Perhaps I missed some specs, or maybe I don't understand something, but how can draft specification override final OIDC specification?

**Comment by leastprivilege** [comment]
both styles are supported. OIDC style in the current released version. JAR and OIDC in the next version (v4).

**Comment by zsalkus** [comment]
I am currently using 3.1.1 version of IdentityServer4. If I pass `response_type` as an OAuth and as a JWT request param, then it works. If I pass it only as a JWT request param, but not as an OAuth param (not according to OIDC spec.) it also works. 

If the current released version supports OIDC style (I hope that by saying style you meant spec), then second request shouldn't pass because required parameter `response_type` is missing. How OIDC style is supported if JWT request values are merged into raw values and only params are validated?

**Comment by leastprivilege** [comment]
True. I remember that we did not enforce that. Why is this a problem?

**Comment by zsalkus** [comment]
The problem is that my organization wants to follow OIDC specification. We used this library from the beginning and now we're a bit stuck. We can't use all params in JWT request token due to client_id validation (since we're using latest stable release) and at the same time we can't use params according to OIDC specification because validation for them is missing.

**Comment by leastprivilege** [comment]
I don't understand.

What exactly is not working for you?

**Comment by zsalkus** [comment]
If we want to work according to the spec, we must send such request:
```
{
  "response_type": "string",
  "client_id": "string",
  "scope": "string",
  "request": "very secret info that also contains the properties which were mentioned above"
}
```
According to the spec `response_type` and `client_id` values MUST match those in the Request Object, if present. `scope` MUST contain `openid` value. IdentityServer4 **merges** JWT Request values into raw payload, so **validation doesn't happen**.

But alright, let's assume it's not a big deal because OAuth JAR (which is currently in draft and its usage is not mentioned in OIDC spec) allows to send everything in `request` param, so other 3 params can be omitted. We send such request:
```
{
  "request": "very secret info"
}
```
IdentityServer4 treats this as bad request because `client_id` is missing. 

Sending such request:
```
{
  "client_id" "string",
  "request": "very secret info"
}
```
Would be too random, because it's not a standard way?

So to conclude the answer to your question what exactly is not working for me, I'd say that requests according to the specified standard are not working for me.

**Comment by leastprivilege** [comment]
OK - well then you have to live with that until v4. sorry.
