### ISSUE TITLE
Allow non-cookie authentication

### ISSUE THREAD

**Issue by jez9999** [IdentityServer/IdentityServer4#4086]
Right now, IdentityServer is pretty locked in to cookie authentication when it comes to the user logging in to the actual auth server app, as it internally calls `AddCookie`.  However, I'd like to implement an authentication method that doesn't use cookies at all on the UA side; maybe just POSTing a form to the authentication endpoint with a session ID, or including one in the query string, because I want to implement an auth server that never persists user authentication (even for a session).  If the user logs in and then re-visits the authentication URL in their browser, it should again prompt them to login.

Right now, I don't think there's a way for me to do this because IdentityServer really wants to use cookie auth.  Or is there a way?  If not, could IdentityServer's authentication be made more flexible to allow it?

**Comment by leastprivilege** [comment]
We are using whatever is configured as the default scheme in ASP.NET Core. If you want to "invent" your own session mechanism - then you would an authentication handler for that.

**Comment by jez9999** [comment]
But the docs say IdentityServer internally calls .AddCookie():

https://identityserver4.readthedocs.io/en/latest/topics/signin.html

I don't want cookie auth; how can I undo that?

**Comment by leastprivilege** [comment]
Exactly what I said before. You wire up a handler and set it as the default - we will use it.

**Comment by leastprivilege** [comment]
the docs say

> We only expose basic settings for these cookies (expiration and sliding), and you can register your own cookie handlers if you need more control.

So replace cookie with signin in the above sentence
