### ISSUE TITLE
Default support for roles

### ISSUE THREAD

**Issue by brunohbrito** [IdentityServer/IdentityServer4#4087]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Load roles from ASP.NET Identity as `JwtClaimTypes.Role` by default in `IdentityServer4.AspNetIdentity`

**Describe alternatives you've considered**
We need to provide a custom ClaimsFactory to accomplish that.

**Additional context**
Actually [UserClaimsFactory.cs](https://github.com/IdentityServer/IdentityServer4/blob/master/src/AspNetIdentity/src/UserClaimsFactory.cs) do some checks, e.g:
``` c#
 // ...
if (_userManager.SupportsUserEmail)
{
    // Load E-mail claims ...
}
if (_userManager.SupportsUserPhoneNumber)
{ 
     // Load phone number claims
}
```
Why not do the same with Roles? 

It's very common to dev's from ASP.NET Identity works with roles. There is a `JWTClaimTypes.Roles` and at `IdentityServer4.AspNetIdentity.IdentityServerBuilderExtensions.cs`  has a override of default claims name of ASP.NET Identity:
``` c#
            builder.Services.Configure<IdentityOptions>(options =>
            {
                options.ClaimsIdentity.UserIdClaimType = JwtClaimTypes.Subject;
                options.ClaimsIdentity.UserNameClaimType = JwtClaimTypes.Name;
                options.ClaimsIdentity.RoleClaimType = JwtClaimTypes.Role; // <-- here
            });
```

But the roles aren't loaded as Claims. So, whats is your opinion about this feature?

If ok, I change and make a PR.

**Comment by TheMisir** [comment]
Could you please share your code how you added role claim to access token. 

Mine looks like that.

```cs
identity.AddClaims(new[]
{
    new Claim(JwtClaimTypes.Name, user.FullName),
    new Claim(JwtClaimTypes.Role, string.Join(' ', roles)),
});
```

The `role` claim is added to `/userinfo` endpoint but not added to access token. So I could not use role based authorization of `AspNetCore.Identity`.

**Comment by TheMisir** [comment]
I solved by adding `JwtClaimTypes.Role` to my ApiResource.

```cs
new ApiResource(LocalApi.ScopeName, "Local Api", new[] { JwtClaimTypes.Role }),`
```

https://stackoverflow.com/a/44932837/7616528

**Comment by brunohbrito** [comment]
Hi @TheMisir,

I don't have my "code". Your example is very good use case. You are loading by your code the roles. You MUST do it if you want the roles at JWT.

Now lets take a look closer to IdentityServer4.AspNetIdentity component.

Open IdentityServer4 default implementation of Claims at [UserClaimsFactory.cs](https://github.com/IdentityServer/IdentityServer4/blob/master/src/AspNetIdentity/src/UserClaimsFactory.cs) and go to line 50 and 64 as well. 

Could you see that the default Implementation make a check about Support Email and Support Telephone at UserManager from ASP.NET Identity?

In this way it's possible to made another check, if it supports Roles:

``` c#
            if (_userManager.SupportsUserRole)
            {
                var roles = await _userManager.GetRolesAsync(user);
                identity.AddRange(roles.Select(s => new Claim(JwtClaimTypes.Role, s)));
            }
```

So, if IdentityServer4 provide such kind of feature I don't have to extend IProfileService or UserClaimsPrincipalFactory.

**Comment by brunohbrito** [comment]
This Stackoverflow linke is a good example that we need to extend IdentityServer4 to provide Roles.

Now let's take a look closer to `IdentityServer4.AspNetIdentity` component.

Open [ApplicationClaimsIdentityFactory.cs)(https://github.com/brunohbrito/JPProject.IdentityServer4.SSO/blob/master/src/Frontend/Jp.UI.SSO/Configuration/ApplicationClaimsIdentityFactory.cs) and go to line 50 and 64 as well.

It checks if UserManager from ASP.NET Identity has support for Email and Telephone. And if it has, load that data  into claims.

Why not do the same with Roles? e.g:

``` c#
if (_userManager.SupportsUserRole)
{
    var roles = await _userManager.GetRolesAsync(user);
    claims.AddRange(roles.Select(s => new Claim(JwtClaimTypes.Role, s)));
}
```

In this way we don't have to extend IdentityServer4 for the basics use case, and afterall it make senses, since it already do some checks at UserManager.

**Comment by TheMisir** [comment]
I write how I implemented role support for IS4 here: https://themisir.com/adding-role-claim-to-identity-server-4/
