### ISSUE TITLE
TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.HttpResponseExtensions'

### ISSUE THREAD

**Issue by dv7865** [IdentityServer/IdentityServer4#4091]
I am upgrading from Asp.net Core 2.2 to Core 3.0.102 and IdentityServer4 3.0.2.

When trying to signin the following exception is thrown:

System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.HttpResponseExtensions' from assembly 'IdentityServer4, Version=3.0.2.0, Culture=neutral, PublicKeyToken=f294d0afe402bb2b'.

The full call stack is:

**System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.HttpResponseExtensions' from assembly 'IdentityServer4, Version=3.0.2.0, Culture=neutral, PublicKeyToken=f294d0afe402bb2b'.**
   at Rsk.AspNetCore.Authentication.Saml2p.Saml2pAuthenticationHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Rsk.AspNetCore.Authentication.Saml2p.Saml2pAuthenticationHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope 
   
My previous runtime environment was Core 2.2 and IdentityServer4 2.3.3 and worked ok.

Has anyone seen this error before, or can help with this issue?

My project references the following packages:

  <ItemGroup>
    <PackageReference Include="Autofac" Version="5.1.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="Autofac.Extras.NLog" Version="2.0.0-rc" />
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.18" />
    <PackageReference Include="IdentityServer4" Version="3.0.2" />
    <PackageReference Include="IdentityServer4.EntityFramework" Version="3.0.2" />
    <PackageReference Include="IdentityServer4.Storage" Version="3.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="3.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens.Saml" Version="5.6.0" />
    <PackageReference Include="Microsoft.IdentityModel.Xml" Version="5.6.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="3.1.0" />
    <PackageReference Include="NLog" Version="4.6.8" />
    <PackageReference Include="Rsk.IdentityServer4.Saml" Version="2.4.6" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="4.7.0" />
  </ItemGroup>

**Comment by scottbrady91** [comment]
Only v2.5 of our SAML component supports .NET Core 3.x: https://www.nuget.org/packages/Rsk.IdentityServer4.Saml/2.5.0-preview4

For support for IdentityServer4 commercial components, please email support@identityserver.com

**Comment by dv7865** [comment]
Thanks for the info
