### ISSUE TITLE
Interactive Login (Code) -- ASP.NET Core Identity, Claims not Returning

### ISSUE THREAD

**Issue by joepietrzak** [IdentityServer/IdentityServer4#4096]
**Scenario**
Architecturally, we have a simple setup.
There is a website (interactive application) [we will call it Frontend] set to use Open ID Connect auth, with the authority being the Identity Server.
The Identity Server is using ASP.NET Core Identity.
I simply want to be able to pull out ASP.NET Core Identity Roles and pass them as ClaimsPrincipal Claims within the Cookie, so that Frontend can read these.

Here is a snippet of my Startup.cs for IdentityServer

             JwtSecurityTokenHandler.DefaultMapInboundClaims = false;
             var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
             const string connectionString = @"Data Source=cribuatlan\uattest;database=IdentityServer4;trusted_connection=yes;";

            services.AddScoped<IPasswordHasher<ApplicationUser>, SaltedPasswordHasher<ApplicationUser>>();
            services.AddDbContext<ApplicationDbContext>(options => options.UseSqlServer(Configuration.GetConnectionString("CSECNewContext")));
            services.AddIdentity<ApplicationUser, IdentityRole<int>>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddClaimsPrincipalFactory<CentralSecurityClaimsPrincipalFactory>()
                .AddDefaultTokenProviders();

            var builder = services.AddIdentityServer(options =>
            {
                options.Events.RaiseErrorEvents = true;
                options.Events.RaiseInformationEvents = true;
                options.Events.RaiseFailureEvents = true;
                options.Events.RaiseSuccessEvents = true;
            })
            .AddConfigurationStore(options =>
            {
                options.ConfigureDbContext = b => b.UseSqlServer(connectionString,
                    sql => sql.MigrationsAssembly(migrationsAssembly));
            })
            .AddOperationalStore(options =>
            {
                options.ConfigureDbContext = b => b.UseSqlServer(connectionString,
                    sql => sql.MigrationsAssembly(migrationsAssembly));
            })
            .AddProfileService<DefaultProfileService>()
            .AddAspNetIdentity<ApplicationUser>();

A snippet of the custom ClaimsPrincipalFactory I'm using to generate the claims:

        protected override async Task<ClaimsIdentity> GenerateClaimsAsync(ApplicationUser user)
        {
            var identity = await base.GenerateClaimsAsync(user);
            var roles = await _UserManager.GetRolesAsync(user);

            identity.AddClaims(roles.Select(role => new Claim(JwtClaimTypes.Role, role)));
            // Add Basic Info
            identity.AddClaim(new Claim(ClaimTypes.Email, user.Email));
            identity.AddClaim(new Claim("phone_number", user.PhoneNumber ?? "XXX-XXX-XXXX"));
            identity.AddClaim(new Claim("gender", "mans"));
            //// Serialize Carriers
            //var carrStr = string.Join(";", user.Carriers.Select(c => c.CarrierCode));
            //identity.AddClaim(new Claim("Carrier", carrStr));
            // Return
            return identity;
        }

A snippet of my Config.cs for IdentityServer:

        public static IEnumerable<IdentityResource> Ids =>
            new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Phone(),
                new IdentityResource
                {
                    Name = "roles",
                    DisplayName = "Roles",
                    UserClaims = { JwtClaimTypes.Role }
                }
            };

        public static IEnumerable<Client> Clients =>
            new List<Client>
            {
                new Client
                {
                    ClientId = "client",

                    // no interactive user, use the clientid/secret for authentication
                    AllowedGrantTypes = GrantTypes.ClientCredentials,

                    // secret for authentication
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },

                    // scopes that client has access to
                    AllowedScopes = { "api1" }
                },
                // interactive ASP.NET Core MVC client
                new Client
                {
                    ClientId = "mvc",
                    ClientSecrets = { new Secret("secret".Sha256()) },

                    AllowedGrantTypes = GrantTypes.Code,
                    RequireConsent = false,
                    RequirePkce = true,

            // where to redirect to after login
            RedirectUris = { "https://localhost:44305/signin-oidc" },

            // where to redirect to after logout
            PostLogoutRedirectUris = { "https://localhost:44305/signout-callback-oidc" },

                    AllowedScopes = new List<string>
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Phone,
                        "roles",
                        "api1"
                    },

    AllowOfflineAccess = true
                }
            };

A snippet of the Startup.cs for Frontend:

            JwtSecurityTokenHandler.DefaultMapInboundClaims = false;

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
                .AddCookie("Cookies")
                .AddOpenIdConnect("oidc", options =>
                {
                    options.Authority = "http://localhost:5000";
                    options.RequireHttpsMetadata = false;
                    options.SignedOutRedirectUri = "http://localhost:5002/signout-callback-oidc";
                    options.ClientId = "mvc";
                    options.ClientSecret = "secret";
                    options.ResponseType = "code";
                    options.GetClaimsFromUserInfoEndpoint = true;
                    options.SaveTokens = true;
                    options.Scope.Add("api1");
                    options.Scope.Add("roles");
                    options.Scope.Add("offline_access");
                });

As you can see I override my ClaimsPrincipalFactory. I can sit and there and verify a Claim is being generated for a Role called 'Admin'.
However, when Frontend gets the cookie, the 'Admin' Claim is not present.

**Questions**
I have not deviated far from the Quickstart guides within IdentityServer documentation, and I do not believe what I am attempting to do to be complicated.
Can anyone point me to where I may be going wrong? I will be happy to provide additional information if someone can tell me what is relevant.

Cheers,

**Comment by joepietrzak** [comment]
Update:

In the course of troubleshooting this I spun my own implementation of IProfileService and am now able to debug and am noticing this same behavior as reported in https://github.com/IdentityServer/IdentityServer4/issues/1067 which was auto-closed by the bot.
I am running into the same issue. Note that this **does not** occur when using the AddTestUsers

**Comment by joepietrzak** [comment]
I figured out how to map in the claims.
See the bottom of this article
https://leastprivilege.com/2017/11/15/missing-claims-in-the-asp-net-core-2-openid-connect-handler/

With respect to AddTestUsers, from what I have gathered, it seems the claims are stuffed right in the ID token, hence you do not run into this issue.

**Comment by natelaff** [comment]
@joepietrzak I've been struggling with the same. I have ASP.NET Core Identity backed IdentityServer and just want Roles/RoleClaims/UsersClaims to come across.

You mentioned the bottom of that article? Which part? The options.GetClaimsFromUserInfoEndpoint = true ? That seems to be on the client end, but in my case I'm not using ASP.NET Core front end...

Do you just have to manually add user/role claims in ProfileService? Is that the way to handle these?

**Comment by joepietrzak** [comment]
@natelaff 
I did two things after which point it worked for me. I'm not sure if #1 is strictly necessary but I know #2 is.

1) I implemented IProfileService. Within the GetProfileDataAsync method, I added some logic to resolve the ASP.NET Core IdentityUser represented by the access token, when calling the UserInfo endpoint. This was the only way I could get the proper claims to be added to the response, but again not sure if it was misconfiguration or if that is always needed
2) I used MapJsonKey on the client side in Startup.cs. This is necessary in core 2.0+, which is pointed out by the article and is what I was referring to above.

With both of those pieces in place I get back my claims as expected.

**Comment by natelaff** [comment]
@joepietrzak thanks. I actually literally just got this working about two seconds before you replied in the ProfileService.

`
		public async Task GetProfileDataAsync(ProfileDataRequestContext context)
		{


			var user = await _userManager.GetUserAsync(context.Subject);
			if (user != null)
			{
				// If we're dealing with the access token, add the permissions/roles
				if (context.Caller == IdentityServerConstants.ProfileDataCallers.ClaimsProviderAccessToken)
				{
					List<string> permissions = new List<string>();
					var userClaims = await _userManager.GetClaimsAsync(user);
					permissions.AddRange(userClaims.Select(c => c.Value));

					if (_userManager.SupportsUserRole)
					{
						var roles = await _userManager.GetRolesAsync(user);
						context.IssuedClaims.AddRange(roles.Select(role => new Claim(JwtClaimTypes.Role, role)));

						foreach (var roleName in roles)
						{
							var role = await _roleManager.FindByNameAsync(roleName);
							if (role != null)
							{
								var claims = await _roleManager.GetClaimsAsync(role);
								//permissions.AddRange(claims.Select(c => c.Value));
								context.IssuedClaims.AddRange(claims);
							}
						}
					}
				}

...
}
`

So I just shove user and role claims right into the access token this way. It's the only way I could figure out how to do it. So... whether it's correct or not, I have no idea, but it seems to work.
