### ISSUE TITLE
What will be returned if grant_type=client_credentials sent as query parameter?

### ISSUE THREAD

**Issue by xperiandri** [IdentityServer/IdentityServer4#410]
We have a [discussion](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/347#issuecomment-253825958) about __Client credentials grant__ request.
A tried to send a request in form of query parameters instead of `x-www-form-urlencoded`  and got a message that `grant_type` us not specified. So I couldn't find what is wrong for a long time.
Do you think it reasonable to check for this case and return an appropriate error message?

**Comment by leastprivilege** [comment]
the grant type goes into the post body. We don't check the query string parameters.
