### ISSUE TITLE
Dead link to "sample SQL scripts"

### ISSUE THREAD

**Issue by slimbofat** [IdentityServer/IdentityServer4#4101]
according to the docs for EF integration found here...
http://docs.identityserver.io/en/stable/reference/ef.html

sample sql scripts should be available here...
https://github.com/IdentityServer/IdentityServer4.EntityFramework/tree/release/src/Host/Migrations/IdentityServer

but github is returning a 404

**Comment by brockallen** [comment]
Fixed, thanks.
