### ISSUE TITLE
Client and ClientCorsOrigin interaction

### ISSUE THREAD

**Issue by bri2** [IdentityServer/IdentityServer4#4103]
In the IdentityServer4.Entityframework package, Client is linked with ClientCorsOrigin. My understanding of this relation is that a client can only call IdentityServer from an origin (in a browser) that is linked with the client itself through the list of its 'ClientCorsOrigins.
However, looking at [CorsPolicyService in the IdentityServer4.Entityframework repo](https://github.com/IdentityServer/IdentityServer4/blob/a4f21c5b320dbf449af1a021b149f95a81f2b8b3/src/EntityFramework/src/Services/CorsPolicyService.cs#L50) it looks like once an origin has been added in the database, the origin is valid for all clients.

Is this as intended?
Is the link between Client and ClientCorsOrigin just to indicate from what origins (in browsers) requests are expected?

**Comment by brockallen** [comment]
You're correct. Many endpoints are not authenticated or don't even have a client id passed them yet cors needs to be enabled.
