### ISSUE TITLE
id_token_hint not being sent to OIDC provider

### ISSUE THREAD

**Issue by Ceteareth** [IdentityServer/IdentityServer4#4104]
### Question
Hello. I'm experiencing pretty much the same issue as in #3510, but I've tried the solution mentioned there, and I can't seem to get it to work.

### Minimal working example

```csharp
authenticationBuilder.AddOpenIdConnect(OpenIdConnectAuthenticationSchemes.Scheme, "OIDC", options =>
{
        options.Authority = authority;
        options.ClientId = externalProviderConfiguration.ClientId;
        options.ClientSecret = externalProviderConfiguration.ClientSecret;
        options.ResponseType = "code";
        options.CallbackPath = $"/signin-{OpenIdConnectAuthenticationSchemes.Scheme}";

        options.SaveTokens = true;
        options.RemoteSignOutPath = $"/endsession";

        options.Events.OnRedirectToIdentityProviderForSignOut = async n =>
        {
                n.ProtocolMessage.IdTokenHint = await n.HttpContext.GetTokenAsync("id_token");
        }
}
```
In OnRedirectToIdentityProviderForSignOut , the id token is always null. I've tried with different schemes, but no luck so far.

In the ExternalLoginCallback method on the AccountController, I've verified that the access and id tokens are available.
Any chance you could give me some pointers as to where things might be going wrong?

**Comment by leastprivilege** [comment]
you don't need to handle `OnRedirectToIdentityProviderForSignOut` - if `SaveTokens` is set, then that's typically done automatically for you. 

Either way - that is Microsoft code - not ours.
