### ISSUE TITLE
Saml2p: AuthenticationProperties are null for RemoteAuthentication failures

### ISSUE THREAD

**Issue by joaco-espinosa** [IdentityServer/IdentityServer4#4108]
Our IdentityProvider is a client of a SAML External Provider. During the authentication mechanism, our IdentityProvider delegates the authentication to said provider:

```C#
var props = new AuthenticationProperties
{
    RedirectUri = Url.Action("callback", new { Provider = scheme.Name }),
    Items =
    {
        { "returnUrl", model.ReturnUrl },
        { "scheme", scheme.Name }
    }
};

return Challenge(props, scheme.Name);
```

If, for example, the remote authentication takes too long, then the RemoteAuthenticationFailure handler kicks in. When that happens, we don't have any info in the Properties field of the `RemoteFailureContext` object:

![image](https://user-images.githubusercontent.com/28567872/75067717-8588ed80-54a2-11ea-8fd3-7004dfa2048d.png)

This works correctly when the external authentication process is successful. It also works well for other protocols such as OIDC and OAuth2.0. In other words, the properties field is **not** null when an external authentication error occurs for an OIDC/OAuth2.0 external provider.

**Comment by leastprivilege** [comment]
@scottbrady91

**Comment by scottbrady91** [comment]
Hi! For component support, please could you send your support request to support@identityserver.com.

Once you open a ticket there, I can get a developer working on a fix.

**Comment by joaco-espinosa** [comment]
Thanks. E-mail has been sent
