### ISSUE TITLE
Saml2p: CorrelationCookie.Expiration not taking effect

### ISSUE THREAD

**Issue by joaco-espinosa** [IdentityServer/IdentityServer4#4109]
This is the current config for our `Saml2pAuthenticationOptions`:

```C#
samlOptions.CallbackPath = $"/external/{provider.Name}";
samlOptions.CorrelationCookie.Expiration = TimeSpan.FromSeconds(300);
samlOptions.Events = new RemoteAuthenticationEvents
{
    OnRemoteFailure = context => context.HandleRemoteFailure()
};
```

Unfortunately, the expiration of the `Saml2pCorrelation` cookie is always 15 minutes (900 seconds) despite the fact that we are manually changing it to 300 seconds.

Can you tell me if this cookie is being overwritten somehow? The `CorrelationCookie.Expiration` specification works perfectly for `OAuthOptions` and `OpenIdConnectOptions`

**Comment by brockallen** [comment]
What assembly/package is `Saml2pAuthenticationOptions` from?

**Comment by leastprivilege** [comment]
See the other issue. Please send an email to the SAML product support.
