### ISSUE TITLE
Asp.net web api 4.5.2 can not understand the token from identityserver4

### ISSUE THREAD

**Issue by tlp0308** [IdentityServer/IdentityServer4#411]
Hi all,
I set up identityserver4 successfully. I have UI application with Asp.net core, which authenticates successfully. But when i use the access_token to call the Web API (4.5.2). Unauthorized request will be thrown. The configuration of my web client:

> app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
>             {
>                 Authority = "http://localhost:5000", //ID Server
>                 ClientId = "demo",
>                 SignInAsAuthenticationType = "Cookies",
>                 RedirectUri = "http://localhost:24082/signin-oidc", //URL of website
>                 Scope = "openid",
>                 AuthenticationType = "oidc"

```
        });
```

I also can not see any logging there

**Comment by brockallen** [comment]
I see no config in your `UseOpenIdConnectAuthentication` where access tokens are being requested.

**Comment by leastprivilege** [comment]
update?
