### ISSUE TITLE
Add additional parameters when redirecting to /connect/endsession through SignOutResult

### ISSUE THREAD

**Issue by pulkitkalra** [IdentityServer/IdentityServer4#4111]
Hi, I'm currently implementing logout through the Microsoft.AspNetCore.Mvc.SignOutResult as shown below:

### Sign Out

```csharp
SignOutResult result = new SignOutResult(new[] { "oidc", "Cookies" });
```
This redirects to the /connect/endsession endpoint as expected. This is how I handle the logoutId after the redirect happens in a logout method:

### Account Controller (Redirect from /connect/endsession)

```csharp
var context = await _interaction.GetLogoutContextAsync(logoutId);
{...}
```
### Question
I'd like to be able to add extra paramaters on the SignOutResult Action Result like this:
```csharp
var props = new AuthenticationProperties();
props.SetParameter("switch", true);
return new SignOutResult(new[] { "oidc", "Cookies" }, props);
```
However, I can't seem to understand how I can access this data in my controller, since `GetLogoutContextAsync` doesn't appear to populate this. Any ideas on how I can achieve this? TIA.

**Comment by brockallen** [comment]
Did you look at the quickstart samples?

**Comment by pulkitkalra** [comment]
@brockallen Yes I have gone through those, can you point me to an example where this is achieved in the samples? Thanks.

**Comment by brockallen** [comment]
I guess I don't follow. This code:

```
var props = new AuthenticationProperties();
props.SetParameter("switch", true);
return new SignOutResult(new[] { "oidc", "Cookies" }, props);
```

Is in your client, not in IdentityServer. You want to pass the "switch" to the IdentityServer logout page?

**Comment by brockallen** [comment]
There's a `Parameters` on the `LogoutRequest`, but that pulls from query params. Try adding your switch there instead.
