### ISSUE TITLE
Customize default endpoint urls

### ISSUE THREAD

**Issue by adimkov** [IdentityServer/IdentityServer4#4112]
### Question
Hey guys,

In our scenario we need to customize default endpoint urls (connect/token, connect/authorize, etc.). Basically we need to add url prefix 'oauth' like: 'https://app.com/oauth/.well-known/openid-configuration'
We tried to add default endpoints with required path, but default implementation is internal and we can not use it. 

Can we customize endpoint url without changing endpoint itself? How?

### Minimal working example

```csharp
   AddEndpoint<DiscoveryEndpoint>(EndpointNames.Discovery, "/oauth/.well-known/openid-configuration");
```

### Relevant parts of the log file

```
   no logs
```

**Comment by brockallen** [comment]
Did you try Map in the pipeline?

**Comment by adimkov** [comment]
Hi @brockallen, thank you for response.
Unfortunately I do not get the idea how [Map](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1) can help me? The problem is -  DiscoveryEndpoint is internal and we can not "re-add" it with required route. Besides that, discovery document should return endpoints with respecting of custom routes:
``` json
 {
    "jwks_uri": "https://customapp.com/oauth/openid-configuration/jwks",
    "authorization_endpoint": "https://customapp.com/oauth/connect/authorize",
    "token_endpoint": "https://customapp.com/oauth/connect/token",
    "userinfo_endpoint": "https://customapp.com/oauth/connect/userinfo
}
```

ideal I would like to do something like this: 
```csharp
services.AddEndpoint<DiscoveryEndpoint>(EndpointNames.Discovery, "/oauth/.well-known/openid-configuration");
```

**Comment by brockallen** [comment]
Map would only give you a custom path at the beginning of our hard coded paths. As of now we have no option to change our internal paths.
