### ISSUE TITLE
Windows Authentication Logout

### ISSUE THREAD

**Issue by beawolf** [IdentityServer/IdentityServer4#4113]
I have a problem with Windows Authentication. The problem is, when I login with Windows Authentication, I cannot properly logout.

My application is hosted in IIS. Both Anonymous Authentication and Windows Authentication are enabled. I use Quickstart UI.

Here are the full steps without (correct behaviour) and with Windows Authentication (incorrect behaviour):

**Without Windows Authentication**
1. I click _grants_ link on main page to access stored grants. It redirects me to login page.
2. I enter username and password on _Local Login_ section to login.
3. I log in successfully and view stored grants.
4. I click my name on header, and then _Logout_ link. It shows _Logout_ page with "Would you like to logout of IdentityServer?".
5. I click Yes. I now see _Logout_ page with "You are now logged out". Also, my name on header disappears.
6. I click IdentityServer4 link on top left corner. I do not see my name in header anymore as I am successfully logged out.

**With Windows Authentication**
1. I click _grants_ link on main page to access stored grants. It redirects me to login page.
2. I click _Windows_ button on _External Login_ section to login.
3. I log in successfully and view stored grants.
4. I click my name on header, and then _Logout_ link. It shows _Logout_ page with "Would you like to logout of IdentityServer?".
5. I click Yes. I now see _Logout_ page with "You are now logged out". Also, my name on header disappears.
6. I click IdentityServer4 link on top left corner. I still see my name in header even if I am logged out.
7. When I debug it, I see that `User.Identity.IsAuthenticated` property is still `true`.

What may I be missing?

Here is my full Logout method:

```csharp
/// <summary>
/// Handle logout page postback
/// </summary>
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Logout(LogoutInputModel model)
{
  // build a model so the logged out page knows what to display
  var vm = await BuildLoggedOutViewModelAsync(model.LogoutId);

  if (User?.Identity.IsAuthenticated == true)
  {
    // delete local authentication cookie
    await HttpContext.SignOutAsync();
    await HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);

    // raise the logout event
    await _events.RaiseAsync(new UserLogoutSuccessEvent(User.GetSubjectId(), User.GetDisplayName()));
  }

  // check if we need to trigger sign-out at an upstream identity provider
  if (vm.TriggerExternalSignout)
  {
    // build a return URL so the upstream provider will redirect back
    // to us after the user has logged out. this allows us to then
    // complete our single sign-out processing.
   string url = Url.Action("Logout", new { logoutId = vm.LogoutId });

    // this triggers a redirect to the external provider for sign-out
    return SignOut(new AuthenticationProperties { RedirectUri = url }, vm.ExternalAuthenticationScheme);
  }

  return View("LoggedOut", vm);
}
```

**Comment by brockallen** [comment]
> I have a problem with Windows Authentication. The problem is, when I login with Windows Authentication, I cannot properly logout.

Are you using integrated windows authentication?

**Comment by beawolf** [comment]
How can I determine if I am using it exactly? I don't have a `<authentication mode="Windows" />` line in my web.config file as suggested [here](https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/integrated-windows-authentication).

In Debug section of my project properties, both _Enable Anonymous Authentication_ and _Enable Windows Authentication_ checkboxes are checked. On Authentication settings window in IIS, both Anonymous Authentication and Windows Authentication are enabled. On Advanced Settings, enabled providers are Negotiate and NTLM.

Also, when I click _Windows_ button on the External Login section of login page and debug it, I can see that it goes through Challenge, Callback, ProcessWindowsLoginAsync, etc. methods of ExternalController (part of Quickstart UI).

As a side note I would like to add that when I debug before the first login, I can still see my Windows Identity in `User` object, however, `User.Identity.IsAuthenticated`property is set to false. I tried to set it to `false` on logout method, but it is read-only.

**Comment by beawolf** [comment]
@brockallen, are these enough or should I provide more details?

**Comment by logcorner** [comment]
@brockallen +1

**Comment by brockallen** [comment]
> Also, when I click Windows button on the External Login section of login page and debug it, I can see that it goes through Challenge, Callback, ProcessWindowsLoginAsync, etc. methods of ExternalController (part of Quickstart UI).

The challenge of windows, does emit a cookie. So you can "logout" by deleting the cookie. But if you trigger windows again, it will just automatically get logged in again. 

So think about it now... you were able to be logged into the web app without entering new credentials, right? So what provided this? The initial login to your windows computer. So to truly be logged out you need to logout of the windows computer.

**Comment by erikvg111** [comment]
I have the same problem as beawolf and his description on Feb24 is completely applicable for my situation.
- without Windows Authentication : logout working correctly
- with Windows Authentication : when I click IdentityServer4 link on top left corner. I still see my name in the header even if I am logged out.

In my case this is introduced after an upgrade. So in our older version, this does work correctly.
- old version: IdentityServer4 v2.2.0 and netcore2.0 application
- upgrade to IdentityServer4 v4.1.1 and netcore3.1 application

Logout code:
```
 [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(LogoutInputModel model)
        {
            // build a model so the logged out page knows what to display
            LoggedOutViewModel vm = await BuildLoggedOutViewModelAsync(model.LogoutId);

            if (User?.Identity.IsAuthenticated == true)
            {
                // delete local authentication cookie
                await HttpContext.SignOutAsync();
                await _signInManager.SignOutAsync();

                // raise the logout event
                await _events.RaiseAsync(new UserLogoutSuccessEvent(User.GetSubjectId(), User.GetDisplayName()));
            }

            // check if we need to trigger sign-out at an upstream identity provider
            if (vm.TriggerExternalSignout)
            {
                // build a return URL so the upstream provider will redirect back
                // to us after the user has logged out. this allows us to then
                // complete our single sign-out processing.
                string url = Url.Action("Logout", new { logoutId = vm.LogoutId });

                // this triggers a redirect to the external provider for sign-out
                return SignOut(new AuthenticationProperties { RedirectUri = url }, vm.ExternalAuthenticationScheme);
            }

            return View("LoggedOut", vm);
        }
```
