### ISSUE TITLE
Where should Login page in MVC context

### ISSUE THREAD

**Issue by virshu** [IdentityServer/IdentityServer4#412]
I am following the quickstarts on [interactive login](http://docs.identityserver.io/en/dev/quickstarts/3_interactive_login.html) and I think I got confused... It says "You need to provide the necessary UI parts for login". Sure - but to _which_ project? Sample project in GitHub shows account controller and view in MVC project; however, IdentityServer redirects me to http://localhost:**5000**/account/login?returnUrl... which is the port of IdentityServer itself that returns 404 for /account.

There is another item that makes me think that I confused... Docs say "add a new client to IdentityServer" to Implicit flow. Specifically,
` // where to redirect to after login
  RedirectUris = { "http://localhost:5002/signin-oidc" },
`
But I would expect that IdentityServer is oblivious to the address/port of the client that comes to authenticate. So localhost:5002 looks very strange here. Am I missing something obvious?

Thank you

**Comment by leastprivilege** [comment]
The login UI goes to IdentityServer of course - that's where users login.

And yes - IdentityServer needs to know the physical location of the client application. It needs to send the token to this location.

**Comment by virshu** [comment]
Makes sense. Thank you.
