### ISSUE TITLE
is it possible to customize jwks_uri?

### ISSUE THREAD

**Issue by amihalj** [IdentityServer/IdentityServer4#4123]
by default servers /.well-known/openid-configuration **jwks_uri** 

returns
/.well-known/openid-configuration/jwks

but some authorizers expect that endpoint to be

/.well-known/jwks.json and therefor signature verification fails.

I am talking about AWS Gateway in this case and I don't know how to make it work together.

Is there any way Identity server can return keys on that endpoint?

thank you
/Ante

**Comment by brockallen** [comment]
> but some authorizers expect that endpoint to be

why? there's nothing in the spec that mandates that. That's the whole reason the discovery document contains the jwks_uri -- so the server can tell the client the URL.
