### ISSUE TITLE
Having trouble using ICustomTokenRequestValidator

### ISSUE THREAD

**Issue by thecristidima** [IdentityServer/IdentityServer4#4127]
### Question
I am trying to add a custom error message (or at least a description) using a `CustomTokenRequestValidator`. The problem is that the custom validator doesn't seem to be used.

### Minimal working example

Client-side I do this:
```csharp
var token = await client.RequestClientCredentialsTokenAsync(new ClientCredentialsTokenRequest {...});
```

Then I do the following:
```csharp

// Startup
var builder = services
    .AddIdentityServer(options => {...})
    ...
    .AddCustomTokenRequestValidator<TestValidator>();

// Validator
public class AnotherTestThingie : ICustomTokenRequestValidator
{
    public Task ValidateAsync(CustomTokenRequestValidationContext context)
    {
        var validationResult = context.Result; // <--- BREAKPOINT

        validationResult.ErrorDescription = ":D";

        return Task.CompletedTask;
    }
}
```

The breakpoint is never triggered and, client-side, I don't see any error description added to the messages. 

Edit: after further investigation it seems that the breakpoint is triggered only when the client and secret are actually validated, but that's exactly the opposite of what I was looking to do. Is something like this doable in IdentityServer 4?

**Comment by brockallen** [comment]
If you don't want client authentication, then disable it for that client.

**Comment by thecristidima** [comment]
> 
> 
> If you don't want client authentication, then disable it for that client.

I want to send a custom error message when clients enter invalid credentials (e.g. "Dummy, try filling in both fields"). After digging around a bit more it seems this can't actually be done. Could you confirm this, or did I miss something?

**Comment by leastprivilege** [comment]
The OAuth way of saying that is called `invalid_client` ;)

**Comment by thecristidima** [comment]
Thanks a lot, I've been trying to explain this to people for a while, but you're a more reliable source than I am 😁
