### ISSUE TITLE
IDX10108 - https address not recognized as https

### ISSUE THREAD

**Issue by Petteroe** [IdentityServer/IdentityServer4#413]
I am running IDSVR4, and I am using IdentityServer4.AccessTokenValidation version 1.0.1-rc1

I am getting this error on my api (not the ID service). I have tried to open the url directly in Postman, and I am getting the configuration just fine.

I deployed my 
Stack trace:
`fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKVMI2FMHI2O": An unhandled exception was thrown by the ap
plication.
System.InvalidOperationException: IDX10803: Unable to obtain configuration from:
 'https://testid.******.***/.well-known/openid-configuration'. ---> System.
ArgumentException: IDX10108: The address specified is not valid as per HTTPS sch
eme. Please specify an https address for security reasons. If you want to test w
ith http address, set the RequireHttps property  on IDocumentRetriever to false.

   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>
d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration
Retriever.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfiguration
Async>d__24.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfiguration
Async>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuth
enticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuth
enticateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<InitializeAsy
nc>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__
18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationMiddlewa
re.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<
Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessi
ngAsync>d__2.MoveNext()`

**Comment by leastprivilege** [comment]
That's happening in Microsoft's code - maybe open an issue on their repo.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by clevelandbuckeye** [comment]
Integrated with Auth0, getting this error when making calls to Authorized methods.
