### ISSUE TITLE
No claims set when using client credentials

### ISSUE THREAD

**Issue by drowhunter** [IdentityServer/IdentityServer4#4130]
### Question
I have an net core(2.2) webapi **(idapi)** which is accessed by multiple client credential clients.  This **idapi** is hosted on the same server that idserver is running.(not sure if this is relevant)

These client credential clients all have **idapi** scopes and i can see it in the jwt token.
#### Jwt Token
```
{
  "nbf": 1582991741,
  "exp": 1582995341,
  "iss": "https://localhost:44300",
  "aud": [
    "https://localhost:44300/resources",
    "idapi"
  ],
  "client_id": "client1",
  "role": "Admin",  
  "scope": [
    "idapi"
  ]
}
```
#### Example client
```
new Client() // note i can set different claims per client
{
	  ClientId = "client1",
          AllowedGrantTypes = GrantTypes.ClientCredentials,
	  ClientSecrets = {new Secret("somesecret".Sha256())},
	  AllowedScopes = new List<string>(){ "idapi'},
	   ClientClaimsPrefix = string.Empty,
           Claims = new[]
           {
                 new Claim(JwtClaimTypes.ClientId,"client1"),
                 new Claim(JwtClaimTypes.Role,BLRRole.Admin), 
           }
},
```
I would like to gate access to certain controller methods to specific clients , and roles. 
So i have followed the example in the docs [here](http://docs.identityserver.io/en/stable/topics/apis.html#validating-scopes)

#### Custom AuthorizationHandler used by custom policy

```
protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, ClientCredentialRequirement requirement)
{
			
	if (requirement.AllowedClients != null && requirement.AllowedClients.Any())
	{
		// ensure that there is no sub to restrict it to client credentials
		if (!context.User.TryGetClaim(out var subClaim, JwtClaimTypes.Subject))
		{
                        if (context.User.TryGetClaim(out var clientid, JwtClaimTypes.ClientId))
			{
				var hasClient = requirement.AllowedClients.Any(r => r == clientid.Value);
				if (hasClient)
				{
					context.Succeed(requirement);
					return Task.CompletedTask;
				}
			}					
		}				
	}

	context.Fail();
	return Task.CompletedTask;
}
```
### The problem 
The issue is that i receive no claims whatsoever .  even the built in `.RequireScope()` doesn't work because it internally just sets `JwtClaimType.Scope`

Is this a bug? shouldn't the validated token request allow me to access the claims which i set on the apiResource? or at the very least allow me access to the properties set on the jwt token

**Comment by mkrtich-m** [comment]
@drowhunter Have your tried to set `AlwaysSendClientClaims` to `true` on client object?

**Comment by leastprivilege** [comment]
First thing I would do is - inspect Controller.User/Requirement in you API and see what claims you actually get.

**Comment by drowhunter** [comment]
you're right. I figured out the answer to my problem here.
https://stackoverflow.com/questions/60462057/using-client-credentials-flow-on-identityserver4-and-custom-authorizationhandler
