### ISSUE TITLE
Question: AntiForgery validation in Login page

### ISSUE THREAD

**Issue by joaco-espinosa** [IdentityServer/IdentityServer4#4131]
Some of your quickstart demos have the `[ValidateAntiForgeryToken]` decoration on the Login controller actions. Therefore, when we load the IdentityServer login page, there's an AntiForgery cookie on the browser, which needs to be sent back to the server upon form submission.

**My question is: is this really necessary, given that, since there is no user authenticated, there's no identity that could be forged?**

I found a Microsoft blog that mentions the possibility of removing this check for public pages: https://techcommunity.microsoft.com/t5/iis-support-blog/anti-forgery-token-and-anti-forgery-cookie-related-issues/ba-p/984870

Even though this might depend on different aspects related to a particular solution, I wanted to ask your opinion regarding this approach (i.e. removing the AntiForgery check for public pages but, in particular, removing it for the Login page).

Thanks in advance.

**Comment by leastprivilege** [comment]
The account controller should be absolutely protected against anti-forgery. Actually anything that might change system state and is protected by a cookie.

**Comment by joaco-espinosa** [comment]
Just to remove the possibility of confusion: I'm not talking about removing the AntiForgery validation from the **entire** Account controller but specifically referring to removing it from **one controller action** in which there's no authenticated user.
_That_ action doesn't change system state if I understand things correctly.

**Comment by leastprivilege** [comment]
It would help so much if you tell me which action you are talking about?

**Comment by joaco-espinosa** [comment]
Sure, sorry about that:

```C#
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Login(LoginInputModel model)
{
    ...
}
```

**Comment by leastprivilege** [comment]
Yes - it's a post and it potentially logs in a user (or changes the logon session of an existing one) hence anti-forgery protection.

**Comment by joaco-espinosa** [comment]
Thanks for your answers.
