### ISSUE TITLE
TypeLoadException: Could not load type 'IdentityServer4.Extensions.IReadableStringCollectionExtensions'

### ISSUE THREAD

**Issue by pengweiqhca** [IdentityServer/IdentityServer4#4134]
TypeLoadException: Could not load type 'IdentityServer4.Extensions.IReadableStringCollectionExtensions' from assembly 'IdentityServer4, Version=3.1.2.0, Culture=neutral, PublicKeyToken=f294d0afe402bb2b'.
IdentityServer4.Saml.Endpoints.Saml2SingleSignOnEndpoint.ProcessSingleSignOn(HttpContext context)
IdentityServer4.Saml.Endpoints.Saml2SingleSignOnEndpoint.ProcessSingleSignOn(HttpContext context)
IdentityServer4.Saml.Endpoints.Saml2SingleSignOnEndpoint.ProcessAsync(HttpContext context) in Saml2SingleSignOnEndpoint.cs

**Comment by pengweiqhca** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/4100

**Comment by leastprivilege** [comment]
yes. that's fixed in 3.1.2

**Comment by pengweiqhca** [comment]
> yes. that's fixed in 3.1.2

No! Occur at 3.1.2, because you changed the class `IdentityServer4.Extensions.IReadableStringCollectionExtensions` to `Microsoft.AspNetCore.Http.IReadableStringCollectionExtensions`

**Comment by leastprivilege** [comment]
Oh - I see. That's a different problem then.

@scottbrady91 could you release an update that fixes the namespace. I had to revert back to the old namespace because I broke the MS templates...

**Comment by leastprivilege** [comment]
@pengweiqhca Downgrade to 3.1.1 - that namespace change is the only change...

**Comment by pengweiqhca** [comment]
I has downgrade to 3.1.1, I waiting for the new version.

**Comment by scottbrady91** [comment]
Version 2.6 of our SAML component now supports IdentityServer4 3.1.2: https://www.identityserver.com/downloads/saml2p

A side effect is that the component had to drop support for IdentityServer4 3.1.0 and 3.1.1.

**Comment by pengweiqhca** [comment]
And `Rsk.IdentityServer4.WsFederation` need upgrade

**Comment by scottbrady91** [comment]
https://www.identityserver.com/downloads/ws-federation
