### ISSUE TITLE
SSO implemented using identiyitserver4 doesn't work with asp.net core mvc client when deployed to IIS,But Locally works great

### ISSUE THREAD

**Issue by mwaleedr** [IdentityServer/IdentityServer4#4137]
I am trying to achieve single sign_on functionality in .net core, i have an identityserver4 app running on http://identity.colaraz.net/ and two .net core clients app running locally http://localhost:5001 and http://localhost:5003. If i tries to go on any client first user is redirect to identityserver4 login page and after successful login user is redirected back to client,now suppose i am loged into localhost:5001 and tries to go to http://localhost:5003 on same browser window then i should be able to go on http://localhost:5003 because i have already logged in on identityserver4 from http://localhost:5001 but i can't do that. But all this works if identityserver4 app is running locally.

asp.net

**Comment by maxswann** [comment]
Hi,

Is it giving you any errors?

**Comment by mwaleedr** [comment]
thanks maxswann ,  it does not gives any error , but as i have mentioned above when i am already loged in on one application and tries to go to other it should allow me to go to other , but it does not allow rather it redirects me to login page again

**Comment by mwaleedr** [comment]
if i run identityserver4 app on localhost then it gives desired result

**Comment by maxtsw** [comment]
Just to check as to make sure I understand the issue.

When you login to the first app you are successfully logged in, but when you go the second app you are ask to sign in again. 

Would you be able to check if the user is authenticated still, on the second attempt? this sounds like either a cookie issue but could be an authentication issue.

**Comment by mwaleedr** [comment]
yes you  understood my issue, but what do you mean by second attempt

**Comment by mwaleedr** [comment]
after the second attempt the user is still authenticated in firstapp

**Comment by maxtsw** [comment]
I mean do they get asked to give there username and password on the second attempt and if so Are they logged in? or does this just automatically redirect?

**Comment by mwaleedr** [comment]
on the first app if i refresh the page the user is still logged in , but on second app if i refresh i am redirected to login

**Comment by mwaleedr** [comment]
look maxtsw, consider i am logged in in app1 now i tries to go to app2 on same browser's second window and i am redirected to login page and asked to give credentials  if i fills in and after logging in successfully i am redireted to app2, but logged out from app1

**Comment by maxtsw** [comment]
Hi mwaleedr, I am asking on identity server itself are you still logged in?

**Comment by mwaleedr** [comment]
no on identiy server no

**Comment by mwaleedr** [comment]
http://identity.colaraz.net/Account/Login

**Comment by mwaleedr** [comment]
user name: hr@insigniabiz.com    password: LG8P2n5v

**Comment by maxtsw** [comment]
When I goto coloraz.net and click sign in this redirects me to http://www.colaraz.net/Home/Login.aspx could this me why?

**Comment by mwaleedr** [comment]
sorry there is no client app deployed except identity server, and the above url is of identityserver

**Comment by mwaleedr** [comment]
you can go to this page http://identity.colaraz.net/Grants and  try to log in

**Comment by maxtsw** [comment]
This works and I can login, could i ask is there another app i can access, using this identity server?

**Comment by mwaleedr** [comment]
there is no other app deployed
but i can send you code of those apps

**Comment by mwaleedr** [comment]
i mean i have two local client apps that i can send you

**Comment by mwaleedr** [comment]
by the way maxstw i am wondering that if i logs in from app1 and goes to identityserver app to insure that i am logged in there or not, then i see i am not logged in there

**Comment by maxtsw** [comment]
That would help yes

**Comment by mwaleedr** [comment]
maxstw you can download project zip files from here https://github.com/mwaleedr/IdnetityClientApps

**Comment by mwaleedr** [comment]
would be thankful to you if you can help me

**Comment by maxtsw** [comment]
I feel as though there is something on your identity server that is not properly authenticating the user, It may be as though they are not being saved properly. It may have worked locally as localhost may have been sharing the same claims

**Comment by mwaleedr** [comment]
if the user is not authenticated then how it is redirected or successfully logging into any of the client app. i thing the issue is due to cookies but not sure what is the real issue

**Comment by mwaleedr** [comment]
did  you run those apps?

**Comment by maxtsw** [comment]
I did yes, have you change how your cookies work anywhere in your app this is usually done within startup.cs?

**Comment by mwaleedr** [comment]
no i have not changed cookies, i see when identity server is running on localhost then identity server share these two cookies  ("idsrv", "idsrv.session") with the client apps, but on deployment it does not share these cookies. Can you suggest me how two share these cookies when client apps and identity server are running on different domains

**Comment by mwaleedr** [comment]
this is startup of my identity server



using System.Reflection;
using Autofac;
using Autofac.Extensions.DependencyInjection;
using Identity.API.Infrastructure.Extensions;
using Identity.API.Infrastructure.Services;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Identity.API
{
    public class Startup
    {
        public Startup(IWebHostEnvironment environment, IConfiguration configuration)
        {
            Environment = environment;
            Configuration = configuration;
        }

        public IWebHostEnvironment Environment { get; }
        public IConfiguration Configuration { get; }


        public ILifetimeScope AutofacContainer { get; private set; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();

            // configures IIS out-of-proc settings (see https://github.com/aspnet/AspNetCore/issues/14882)
            services.Configure<IISOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });

            // configures IIS in-proc settings
            services.Configure<IISServerOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });

            services.AddCustomOptions(Configuration);

            var connectionString = Configuration.GetConnectionString("DefaultConnection");
            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            var builder = services.AddIdentityServer(options =>
                {
                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;
                })
                .AddRedirectUriValidator<RedirectUriValidator>()
                .AddCorsPolicyService<ColarazCorsPolicy>()
                .AddSigningCertificate(Configuration, Environment)
                .AddIdentityUserStore(Configuration)
                // this adds the config data from DB (clients, resources, CORS)
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = dbContextOptionsBuilder =>
                        dbContextOptionsBuilder.UseSqlite(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = dbContextOptionsBuilder =>
                        dbContextOptionsBuilder.UseSqlite(connectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                });
            services.AddLocalApiAuthentication();


        }

        public void ConfigureContainer(ContainerBuilder builder)
        {
            // Register your own things directly with Autofac, like:
            //builder.RegisterModule(new MyApplicationModule());
        }

        public void Configure(IApplicationBuilder app)
        {
            AutofacContainer = app.ApplicationServices.GetAutofacRoot();

            if (Environment.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }

            app.UseStaticFiles();

            app.UseRouting();
            app.UseIdentityServer();
            app.UseAuthorization();
            app.UseEndpoints(endpoints => { endpoints.MapDefaultControllerRoute(); });
        }
    }
}

**Comment by mwaleedr** [comment]
hey max there is a good news and also some wonder i was using code flow before this,now  i used  implicit flow and try to do what i was doing already and get the desired result , mean logging in from one app also getting me logs into the second app but still i am not able to get those two cookies in my client apps.

**Comment by maxtsw** [comment]
Hi,

I am glad this was sorted, I was going to say that as a next step as everything else did appear in order. I am glad its working now.

I presume this can now be closed?
