### ISSUE TITLE
Validate a token issued from identity server 4 using identity server 3 token validation library

### ISSUE THREAD

**Issue by diyathn** [IdentityServer/IdentityServer4#4139]
### Question
I have an identity server that was developed using Identity Server 4 (v3.1.2) and a web API which was developed using ASP .NET Framework 4.6.1. In the web API, I am using Identity Server 3 AccessTokenValidation library (v2.14.0) to validate the incoming tokens generated from ID server. Following is the codebase which I am using in the Startup.cs of my web API.

### Minimal working example

```csharp
          public void Configuration(IAppBuilder app)
        {

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "http://localhost:9080/IdentityServer"
            });

            var config = new HttpConfiguration();
            config.MapHttpAttributeRoutes();

            app.UseWebApi(config);
        }
```
What happens is, once a request comes to the web API, ID server 3 AccessTokenValidation library, gets the issuer of my token and uses it as the audience appending the "/resources". Since the actual audience (AppointmentAPI) of my token is different from this I get unauthorized (status 401). 

 Following is the log that I get in Owin when unauthorized.

### Relevant parts of the log file

```
  Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Error: 0 : Authentication failed
System.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'AppointmentAPI'. Did not match:  validationParameters.ValidAudience: '<token_issuer>/resources' or validationParameters.ValidAudiences: 'null'
   at System.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\Validators.cs:line 92
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 1179
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(String securityToken, TokenValidationParameters validationParameters, SecurityToken& validatedToken) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 702
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()
    ProcessId=31064
    DateTime=2020-03-03T09:43:05.1841359Z
```
**Questions:**
1. Is there a way for me to set the audience explicitly rather than letting it to set by the library? or at least skip audience validation.
2. Can I use Identity server 4 AccessTokenValidation library which was built to use in .net standard (v2.7.0 or before) within my web API project (.NET framework 4.6.1)?
     If so is there any working sample related to this?

Your help is appreciated. Thanks!

**Comment by leastprivilege** [comment]
You can add the /resources audience in IS4 - there's a config switch

`EmitLegacyResourceAudienceClaim`

https://identityserver4.readthedocs.io/en/latest/reference/options.html

**Comment by diyathn** [comment]
Thanks, Dominick for the reply. Even though I enable the `EmitLegacyResourceAudienceClaim` switch, the AccessTokenValidation library will still check the audience as "<issuer>/resources" right? 
The audience attribute in the token I get from the identity server 4 doesn't contain the issuer or "resources" part. it has simply an API resource name (AppointmentAPI) which will be set by the identity server. In that case, still, my token will be unauthorized.

Can I please know the reason for setting the audience name like this (<issuer>/resuorces) within the library itself rather than letting it set by the library user?
