### ISSUE TITLE
PersistedGrants / Operational Store

### ISSUE THREAD

**Issue by pedershk** [IdentityServer/IdentityServer4#414]
Hi.

I've set up the .AddOperationalStore and added migrations and run them for the Context PersistedGrantDbContext.

Also tried explicitly pointing IPersistedGrantStore to the PersistedGrantStore implementation in Identityserver4.EntityFramework.

However - no grants/tokens are actually stored in the PersistedGrants table in the database.

Am I missing something?

**Comment by pedershk** [comment]
Btw - the Operational store lives in its own database, if that matters.

**Comment by Lutando** [comment]
If you look at the PersistedGrant, it only stores AuthorizationCodes, RefreshTokens, ReferenceTokens and UserConsent. Access tokens wont appear there.

**Comment by pedershk** [comment]
Then color me confused. If we have an IdentityServer that's load balanced to run on two instances - how do we keep the user logged in across instances? Is the cookie itself good enough? 

In Identityserver3 it was easy to store this stuff in Sql Server, and a built in process could be configured to clear out expired tokens.

Nothing appears in PersistedGrants at all.

**Comment by leastprivilege** [comment]
The cookie is enough - same as in IdentityServer3

**Comment by pedershk** [comment]
Thx.

**Comment by obosha** [comment]
Am I correct that this means Access Tokens cannot be "revoked" or invalidated prior to expiration then?

**Comment by leastprivilege** [comment]
That's true for JWTs - but you can revoke reference tokens

**Comment by shawndewet** [comment]
Nuts, so I've changed my client's AccessTokenType to Reference.  And after login, there is still nothing written to the PersistedGrants table. 
In my Client startup.cs I have
 ```
services.AddAuthentication(options => {
...
options.SaveTokens = true;
...
})
```
In my IdentityServer startup.cs I have:
```
services.AddIdentityServer()
                ....
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"),
                            sql => sql.MigrationsAssembly(migrationsAssembly));                                        
                });
```

What else could I be missing?

**Comment by shawndewet** [comment]
mmm, seems I had to setup my client to require Consent.  AND, on the consent page, I had check the "Remember" option.  Only then did a "user_consent" record get written to the PersistedGrants table.

**Comment by shawndewet** [comment]
Well it still leaves the question "How do I get a ReferenceToken to be stored in that table?"
