### ISSUE TITLE
IS4 CORS blocking preflight requests

### ISSUE THREAD

**Issue by arcsoft-ro** [IdentityServer/IdentityServer4#4141]
### Steps to reproduce
 1. Added EF client config with PKCE flow and ClientCorsOrigins set to https://mvc.mydomain.com
 2. Protected an API endpoint on the IS4 app (id.mydomain.com) and an MVC (mvc.mydomain.com) with this client
 3. Authenticated the user on https://mvc.mydomain.com/testpage and triggered an xhr via jQuery from the MVC client towards https://id.mydomain.com/admin/test

The xhr is set-up like this:
```
xhrFields: {
    withCredentials: true
},
crossDomain: true,
```

When calling the protected endpoint via CORS from JS the IS4 responds with a method not allowed, so it looks like IS4 is not allowing the OPTIONS request method.

If I configure ASP Net Core CORS Middleware with AllowAnyMethod and set-up the https://mvc.mydomain.com as allowed origins in the startup config, it works, but I am willing to use the OOB configuration feature of IS4 and set-up the allowed origins in the ClientCorsOrigins table.

### Relevant parts of the log file

```
Microsoft.AspNetCore.Hosting.Diagnostics: Information: Request starting HTTP/2.0 OPTIONS https://id.mydomain.com/admin/test  
IdentityServer4.Hosting.CorsPolicyProvider: Debug: CORS request made for path: /admin/test from origin: https://mvc.mydomain.com but was ignored because path was not for an allowed IdentityServer CORS endpoint
Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware: Information: No CORS policy found for the specified request.
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint '405 HTTP Method Not Supported'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '405 HTTP Method Not Supported'
```

**Comment by brockallen** [comment]
Our CORS config only applies to IdentityServer endpoints. It won't affect any other endpoints in the host (e.g. "/admin/test").

**Comment by arcsoft-ro** [comment]
Thank you for the reply, Allen. 
I am investigating a better approach for protecting API's and indeed I need to change the current client's configuration.
