### ISSUE TITLE
ValidatingClientStore to throw on error

### ISSUE THREAD

**Issue by katlimruiz** [IdentityServer/IdentityServer4#4142]
**Is your feature request related to a problem? Please describe.**
I was getting a null client, even though the client id was registered in the client store.
The problem was that the client did not have a secret.
I found it only by looking closely in the Output logs.

**Describe the solution you'd like**
Configure to throw error exception when any error like that happens.

**Describe alternatives you've considered**
Documentation

**Comment by katlimruiz** [comment]
The error in the log was: `IdentityServer4.Stores.ValidatingClientStore: Error: Invalid client configuration for client xxx: Client secret is required for client_credentials, but no client secret is configured.`

**Comment by leastprivilege** [comment]
That works exactly as designed.

**Comment by katlimruiz** [comment]
Yup, that is why this is a feature request.
