### ISSUE TITLE
New token format introduced in IdentityServer4 v3.0

### ISSUE THREAD

**Issue by martinmine** [IdentityServer/IdentityServer4#4143]
### Question
In version `2.5.3` of IdentityServer4, access tokens would be formated like this:
`d5df5bea02a743883bbfc2967b104ee42a2521eaa5bdf0e4814e251933373e4e`
In version 3.0 of IdentityServer4, access tokens started appearing in this format:
`tJWQ9zTiUwiAc3MSnVqlOEp-sPXSHtMlW3TA7zP_F1E`

What is the reason for this change, and is there any way I can get the old behavior in 3.x of IdentityServer4? 

### Minimal working example

Send a POST to /connect/token to generate a new token with grant_type `client_credentials`.

**Comment by leastprivilege** [comment]
What’s the problem?

**Comment by martinmine** [comment]
The problem is that the formats are different. The second format has a mix of lower/upper-case characters with - and _ symbols. I am wondering what is the reason for this change and is there a way I can get the old behavior.

**Comment by leastprivilege** [comment]
Both are random strings. I think we changed the encoding at some point. It shouldn't matter.

**Comment by martinmine** [comment]
Yes, they are both random strings, but the random strings use different characters. For my use-case this is causing some systems to break since they do not expect - or _. This has introduced a significant cost in order to fix this. While this is being fixed, I am eager to know why this change is taking place or if we can get the old behavior back due to the risk involved in switching to newer version of IdentityServer4. I am aware that the ideal solution would be to make the systems compatible with the new token format, but in context of a risk assessment I would nevertheless like to know a bit more context regarding this change.

**Comment by leastprivilege** [comment]
I can't remember tbh. The behavior is not configurable. A reference token should be treated as opaque data.

**Comment by martinmine** [comment]
I've done some digging and found out that the change was introduced as part of 41f83cd7bf22c87fd4be98df9b8eaefafd80dbc2. The change in this commit leading to the new token format is the switch from IdentityModel `3.10.10` to `4.x`. IdentityServer4 uses the call IdentityModel.CryptoRandom.CreateRandomKey(length) in [DefaultHandleGenerationService ](https://github.com/IdentityServer/IdentityServer4/blob/3.0.0/src/IdentityServer4/src/Services/Default/DefaultHandleGenerationService.cs#L23)to generate these access tokens.
The new behavior in CreateRandomKey was changed in https://github.com/IdentityModel/IdentityModel/commit/d95fd0713b4d2d93ee3a81c78ac970a76421294b#diff-81ea87ed84ec475bb74866784c8b12e3. The reason this is now different is that CreateRandomKey use `Base64Url.Encode` to encode the random bytes that represents the key, opposed to the previous behavior which use a `StringBuilder` and use composite string formatting to represent the random generated bytes. From the commit itself I cannot understand why this change was made since the commit is titled "manual merge of v4" and has 2,903 additions and 4,727 deletions. Does this provide you a bit more context to remember why this change was made?

**Comment by leastprivilege** [comment]
No. But as you already found out - you can generate your own handles by overriding the

https://github.com/IdentityServer/IdentityServer4/blob/3.0.0/src/IdentityServer4/src/Services/Default/DefaultHandleGenerationService.cs#L23

**Comment by martinmine** [comment]
Cool, thanks, I'll go ahead and close this issue then :)
