### ISSUE TITLE
 Error Response with invalid redirection URI on authorize endpoint

### ISSUE THREAD

**Issue by user1336** [IdentityServer/IdentityServer4#4145]
Same as #4075 but on the Authorize endpoint:

In the OAuth authorization_code flow, when validating the redirect_uri on the authorize endpoint, why do we return an `unauthorized_client` when the redirect_uri is invalid.

Shouldn't [this ](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Validation/Default/AuthorizeRequestValidator.cs#L325  ) be an `invalid_request` according to the spec:

> invalid_request
>         The request is missing a required parameter, includes an
>         invalid parameter value, includes a parameter more than
>         once, or is otherwise malformed.
> https://tools.ietf.org/html/rfc6749#section-4.1.2.1 

Parameter is invalid, unauthorized_client says something about the method the client uses to request an authorization_code.

If you agree I can do the work on this.

**Comment by brockallen** [comment]
We didn't see a PR for the authorize EP as well, so we just made the fix. Thanks.

**Comment by user1336** [comment]
If you'd agreed, I would have made one.

Thanks anyway, this helps a lot!

**Comment by brockallen** [comment]
No worries. Thanks
