### ISSUE TITLE
Sign in with possibility to change AbsoluteRefreshTokenLifetime on fly

### ISSUE THREAD

**Issue by sudden-alex** [IdentityServer/IdentityServer4#4147]
Hi community!
I'm trying to implement logic around 'keep me logged in'
I'm using /connect/token endpoint for getting tokens and my task is changing 'AbsoluteRefreshTokenLifetime' value depending on the some parameter who is responsible for  'keep me logged in'

Maybe there is some solution to change refresh token lifetime?
I have some solution for access token lifetime:
I'm using ICustomTokenRequestValidator:

```csharp
    public class CustomTokenRequestValidator : ICustomTokenRequestValidator
    {
        public Task ValidateAsync(CustomTokenRequestValidationContext context)
        {
            context.Result.ValidatedRequest.AccessTokenLifetime = 6000;
            return Task.CompletedTask;
        }
    }
```

**Comment by Kibsgaard** [comment]
@sudden-alex Did you find a solution for this?

I've found that you can modify the client config in ValidateAsync, but that will stick around for the next requests and I'm not sure how thread/task-safe it is with many incoming request.
