### ISSUE TITLE
Issue a notice when IdSrv uses a expired certificate for token signing

### ISSUE THREAD

**Issue by ManuelRauber** [IdentityServer/IdentityServer4#415]
For development time we use a self-signed certificate to sign our tokens. This works well on our development machine but startet to crash after deploying on Azure.

Together with .NET Core team we noticed, that the certificate was expired (https://github.com/dotnet/corefx/issues/12704) which lead to the crash in Azure. 

Wouldn't it be nice if IdSrv 4 issues a warning, that it uses an expired certificate for signing? :)

**Comment by leastprivilege** [comment]
When?

At startup time? during signing?

**Comment by ManuelRauber** [comment]
During signing would may be the best, since the certificate can expire while IdSrv is running.

**Comment by leastprivilege** [comment]
Sure - open a PR please.

**Comment by leastprivilege** [comment]
yes? ;)

**Comment by ManuelRauber** [comment]
@leastprivilege Sorry! I thought you do it yourself because you assigned yourself to the ticket. :D 

I'll take a look at it :)

**Comment by ManuelRauber** [comment]
@leastprivilege I started digging into this. So far, I recognized, that I need to start somewhere at `Crypto.js` and the `DefaultSigningCredentialsStore`. But: As far as I can see, the `SigningCredentials` used by .NET do not allow adding more information like an expiration date. 

So, the easy solution would be to check for the expiration during startup, since `AddSigningCredentials` in `Crypto.js` is used there - but the message would only be visible, when the application starts. 

"My" preferred solution, to issue a message every time an expired certificate is used, would need to either wrap `SigningCredentials` into another class or to create an subclass of it to support more information about the signing credentials used. (For certs checking the `NotBefore` could also be a scenario, maybe). 

Both ways change a bit in the internals of IdSrv, which prevents me from starting an implementation without discussing it with you. 

Therefore: Are my ideas above correct? If yes, would the "preferred" solution something, you want to see in the code base or do you have another idea (since I'm not used to the internal code base of IdSrv yet)

**Comment by leastprivilege** [comment]
good enough?

https://github.com/IdentityServer/IdentityServer4/commit/7389065bf9f615ff3583fb5b50a34e90d363aa94

**Comment by ManuelRauber** [comment]
Ah dang! That's the missing link for doing the preferred solution easily! Looks good. Thanks! :)
