### ISSUE TITLE
About Claims

### ISSUE THREAD

**Issue by lfppfaria** [IdentityServer/IdentityServer4#4150]
Hello, it's not clear for me when I am suposed to use each type of claim, as I have read, we have ApiResource claims, IdentityResource claims and Scope Claims. Actually, my doubt is more about how to use them, not when. Can someone help me to understand this? Thanks in advance.

**Comment by brockallen** [comment]
https://brockallen.com/2019/02/25/scope-and-claims-design-in-identityserver/

**Comment by lfppfaria** [comment]
Thanks, it helped but I still have some doubts. Scope Claims, for example, can I use them both for clients and users? This kind of definition is not very clear.
