### ISSUE TITLE
checksession endpoint?

### ISSUE THREAD

**Issue by lawrenceong001** [IdentityServer/IdentityServer4#4155]
Hello,

the configuration endpoint identifies a checksession endpoint, but I couldn't seem to find documentation regarding this. can you tell me if this indeed exists, and if so, how I can use it? 

thanks

**Comment by brockallen** [comment]
https://openid.net/specs/openid-connect-session-1_0.html

**Comment by lawrenceong001** [comment]
Hi @brockallen , 

yes I did look into that prior to this note -- what I was interested in was the documentation from IdentityServer's point of view, since we have the list of endpoints in the docs, but this one wasn't there. 

![image](https://user-images.githubusercontent.com/8312221/76337221-6f19c900-62cd-11ea-96e8-61db00bc55f9.png)

tks
Lawrence

**Comment by brockallen** [comment]
Well, it's not something you typically interact with or invoke, thus that's probably why we neglected to list it. But, we do list that we support session management in our specs list: https://identityserver4.readthedocs.io/en/latest/intro/specs.html

**Comment by lawrenceong001** [comment]
hi @brockallen , yes it is in the specs. 

I was interested in understanding what the request and response content looks like, as we are embarking on a project where we intend to wrap functionality around this framework (tks by the way). 

interesting that you mentioned this is not typical. just out of curiosity then, how would an app check for a session's validity? perhaps it's my understanding of the functionality that should be adjusted.

tks
Lawrence

**Comment by brockallen** [comment]
Normally you use oidc-client-js and it does it for you. As for the details, I refer you to the spec.

**Comment by lawrenceong001** [comment]
thanks @brockallen -- with the virus thing going on I had been pulled off this temporarily. will touch base with you again when we're on track.

tks
lawrence
