### ISSUE TITLE
IdSrv4 ApiAuthorizationDbContext with Identity doesn't support custom ApplicationUser primary key

### ISSUE THREAD

**Issue by seanronan** [IdentityServer/IdentityServer4#4159]
When starting with `dotnet new react -o <output_directory_name> -au Individual` from https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity-api-authorization?view=aspnetcore-3.1 
`ApplicationDbContext` inherits `ApiAuthorizationDbContext<ApplicationUser>` instead of the `IdentityDbContext<ApplicationUser>` for a 'standard' net core app that uses Identity.

Previously, to alter the type of the primary key of the Application user I would amend ApplicationDbContext to inherit from `IdentityDbContext<CustomUser, CustomRole, int>`

Question: why can't I do the same when using IdentityServer4, as `ApiAuthorizationDbContext` only accepts a single `TUser` parameter? Am I missing something?

Previous issue https://github.com/IdentityServer/IdentityServer4/issues/2389 from 2018 shows solution not using `ApiAuthorizationDbContext`. Why shouldn't I revert to the 2018 approach?

**Comment by brockallen** [comment]
That's a Microsoft template, so you should open an issue with them.

**Comment by seanronan** [comment]
Thanks  - but they [said](https://github.com/dotnet/AspNetCore.Docs/issues/17267) to raise it here
It's less about the template, more about the `ApiAuthorizationDbContext` class which sits in the 
`Microsoft.AspNetCore.ApiAuthorization.IdentityServer` namespace. Isn't it appropriate to raise IdentityServer issues here?

**Comment by zhanghm1** [comment]
I removed Microsoft.AspNetCore.Identity.UI in the project；

`public class ApplicationUser : IdentityUser<int>{}
public class ApplicationRole : IdentityRole<int>{}`

` public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, int>{}`

`services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();`
is OK.

**Comment by brockallen** [comment]
`ApiAuthorizationDbContext` is from Microsoft, not IdentityServer. And IdentityServer does not mandate anything about your identity db context.

**Comment by seanronan** [comment]
Thanks Brock, I followed https://stackoverflow.com/questions/58208894/aspnet-core-identity-custom-apiauthorizationdbcontext to create a class that did allow the params
