### ISSUE TITLE
Compiling Problem - WindowsPrincipals

### ISSUE THREAD

**Issue by amerlin** [IdentityServer/IdentityServer4#4160]
### Question
Hello, 
I have created a is4inmem project, with dotnet core cli. 
I'm trying to compile with dotnet core 3.1.102. 
I'm receiving this error: 
'WindowsPrincipal' is not found, in Quickstart\Account\ExternalController.cs(151,38)

What's about this problem? 
Thanks

### Minimal working example

```csharp
   // <code goes here>
```

**Comment by leastprivilege** [comment]
is that on Windows?

**Comment by amerlin** [comment]
Windows 10 
Dotnet Core  3.1.102

Thansk

**Comment by leastprivilege** [comment]
Yea - i just ran into that myself. If you carefully read the exception message, it says you need to pull in

https://www.nuget.org/packages/System.Security.Principal.Windows/

Will need to update the templates
