### ISSUE TITLE
Is there a way to generate refresh token using a CustomGrantValidator?

### ISSUE THREAD

**Issue by AmadorSV** [IdentityServer/IdentityServer4#4162]
I'm developing a web app that generate Access tokens using an ExtensionGrantValidator but i cant find a way to generate the refreshtoken. I tried with AllowOfflineAccess = true but its not working.

**Comment by leastprivilege** [comment]
Does the client send the offline_access scope?

**Comment by AmadorSV** [comment]
Haven't tried that, now its working, thanks
