### ISSUE TITLE
Authorization endpoint with error redirects to error display page that doesn't exist

### ISSUE THREAD

**Issue by PeterDavidCarter** [IdentityServer/IdentityServer4#4164]
### Issue / Steps to reproduce the problem

Attempt to connect to the authorization endpoint with an error condition.

Identity Server tries to resolve to an internal error page, presumably with details of the problem for debugging:

![image](https://user-images.githubusercontent.com/23146481/76605119-d28f3b00-6507-11ea-9ecd-eec09c58c00c.png)

This page always resolves to a 404.

![image](https://user-images.githubusercontent.com/23146481/76605172-eaff5580-6507-11ea-8aa4-e8c61b0eb257.png)

Expected behaviour is that this page actually resolves with details of error, allowing for debugging.

**Comment by brockallen** [comment]
You need an error page, much like the one from our quickstart: https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/master/Quickstart/Home/HomeController.cs#L45. Now it still won't show you all the details, as that's an end-user page. If you want the details, check your IS logs.

**Comment by PeterDavidCarter** [comment]
Excellent. Thanks for the info: very helpful.
