### ISSUE TITLE
Logs show client_id missing or too long, but is neither missing or long

### ISSUE THREAD

**Issue by PeterDavidCarter** [IdentityServer/IdentityServer4#4166]
### Issue / Steps to reproduce the problem

This request:

![image](https://user-images.githubusercontent.com/23146481/76629492-421c1f00-6536-11ea-9e0c-082e0ac3b8a5.png)

Is logging: 

### Relevant parts of the log file

```
client_id is missing or too long
```

But the client_id is set in the body in what seems to be the appropriate format.

(Sorry to be a pain, I know this is my second bug/question today :/).

**Comment by leastprivilege** [comment]
The authorize endpoint uses a GET with query string params - not a form encoded POST. Check the specs if you really want to use a tool like Postman.

**Comment by PeterDavidCarter** [comment]
Still seems like it shouldn't be logging

**Comment by PeterDavidCarter** [comment]
On further consideration, surely the above is a 405? Not certain if it's appropriate to check the response body when you're not expecting one, though given the difference from the client credentials flow and the relatively sparse description in the docs (which does resolve when you grock it I must admit...) I'm wondering if error handling to return a 415 in that scenario would be good. I know it's returning a 404 because it's considering as if it's attached to a UI, but perhaps an inner exception would be appropriate? Just some ideas I had.

Also, I cloned the repo and the nuget resolve path was borked and there's some issues with .pdb files that meant I had to resolve a bunch of symbols manually to get debugging support...

**Comment by leastprivilege** [comment]
Well - I had a 2nd look - the logic looks pretty solid to me.

https://github.com/IdentityServer/IdentityServer4/blob/bddaa2311e7dfc5780e8455682a61a35530ca2e7/src/IdentityServer4/src/Endpoints/AuthorizeEndpoint.cs#L37-L53

The problem with Postman is, it's a pretty low level tool. You need to know what you are doing. At this level the specification is the best documentation.

> nuget resolve path was borked

what does that mean? Have you run the build script as described in the readme.

> there's some issues with .pdb files

and what does that mean?
