### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by GioviQ** [IdentityServer/IdentityServer4#4167]
After reading this https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/ 
It would be interesting to mention somewhere blazor IdentyServer integration.

**Comment by brockallen** [comment]
https://brockallen.com/2019/01/11/using-oauth-and-oidc-with-blazor/

**Comment by GioviQ** [comment]
Thanks
