### ISSUE TITLE
Add --nuget-source param in quickstart

### ISSUE THREAD

**Issue by Domitnator** [IdentityServer/IdentityServer4#4168]
Hi Guys,

I was walking trough the walktrough and i stumbled into an issue when I tried to install the templates.

The quickstart provides the following command to install the templates:

`dotnet new -i IdentityServer4.Templates`

When running this command I got an error because i am using private nuget sources and dotnet is using my private nuget source instead of the public (default) one. So i changed the command to:

`dotnet new -i IdentityServer4.Templates --nuget-source https://api.nuget.org/v3/index.json`

And then it works perfectly. I took me like 5 minutes to figure this out but a junior colleague struggled one hour with this issue. So in my opinion i would be better to add the --nuget-source parameter by default. Do you agree?

I already forked the repo and made the change. Let me know if you want me to push the pull request.

**Comment by leastprivilege** [comment]
thanks! you can add a note to the quickstart if you think this will help other people.
