### ISSUE TITLE
After restarting server a valid refresh token is not getting the new token

### ISSUE THREAD

**Issue by leo9223** [IdentityServer/IdentityServer4#417]
I am facing the problem after restarting server a valid refresh token is not getting the new token. I have published both api and server on IIS10.

**Comment by xyting** [comment]
@leo9223 

You had DI `IPersistedGrantStore` ?

**Comment by leastprivilege** [comment]
how are you storing your refresh tokens?

**Comment by leo9223** [comment]
@xyting no I didn't DI IPersistedGrantStore

@leastprivilege storing in local SharedPrefrences in android it stores like KeyValuePair.

by the way after restarting the server just refresh token not works if its valid. But if access token is valid it works.

**Comment by leastprivilege** [comment]
I meant how do you store them in IdentityServer? They will not be automagically persisted - you need to do some work for that.

**Comment by leo9223** [comment]
Sorry Sir,
I literally don't know about storing tokens in IdentityServer? 
I didn't do anything for storing them explicitly.
I just followed your samples.

Please guide me. Thank you

**Comment by scottbrady91** [comment]
If you still using the In-Memory stores (e.g. `AddInMemoryScopes` or `AddDeveloperIdentityServer`) then all tokens that are stored by IdentityServer will be lost upon application restart. Tokens that are stored like this are: refresh tokens, reference tokens, consent and authorization codes.

If you want these tokens to persist across deployments then you need to use the EntityFramework implementation or something similar (see: http://docs.identityserver.io/en/dev/quickstarts/8_entity_framework.html).

**Comment by leo9223** [comment]
@scottbrady91 
My ConfigureServices method is here.

I have implemented IClientStore, IScopeStore, IResourceOwnerPasswordValidator and IProfileService to have my clients, users and scopes from database. I am using EF Core.

1. are you talking about this -> var builder = services.AddIdentityServer().SetSigningCredential(cert); ? should I do something else here?

2. My clients, users and scopes are stored in database, should I also need to store the tokens in database?


`        public void ConfigureServices(IServiceCollection services)
        {
            var cert = new X509Certificate2(Path.Combine(_environment.ContentRootPath, "Cert", "IdentityServer4cert.pfx"), "IdentityServer4cert");

            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            var builder = services.AddIdentityServer().SetSigningCredential(cert);

            string DbConnString = Configuration["DatabaseConnection:ConnectionString"];

            // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(DbConnString));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            builder.Services.AddSingleton<IClientStore>(new ClientStore(DbConnString));
            builder.Services.AddSingleton<IScopeStore>(new ScopeStore(DbConnString));
            builder.Services.AddScoped<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();
            builder.Services.AddSingleton<IProfileService>(new ProfileService(DbConnString));

            services.AddMvc();
        }`

**Comment by scottbrady91** [comment]
Yes, you need `AddOperationalStore` for storing tokens that should be persisted.

Otherwise you need to register implementations for `IPersistedGrantStore` and `IPersistedGrantDbContext`.

**Comment by leo9223** [comment]
@scottbrady91 Sir is there any docs for how to Implement these interfaces?

**Comment by scottbrady91** [comment]
They are interfaces, you can implement them how you want as long as you fulfill the contract.

See IdentityServer4.EntityFramework for existing implementation: https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/release/src/IdentityServer4.EntityFramework/Stores/PersistedGrantStore.cs

**Comment by leo9223** [comment]
@scottbrady91 Sir thank you so much. It's really helpful.

Sir but I am not getting what is key, type and subjectId in PersistedGrant class?

**Comment by scottbrady91** [comment]
That's not for the store to understand, only persist. If you want to see how these are used search the core repository for usages of the interfaces.

**Comment by leo9223** [comment]
@scottbrady91 Sir can you guide me how to DI both these `IPersistedGrantDbContext, IPersistedGrantStore`

I am doing this way
`builder.Services.AddScoped<IPersistedGrantDbContext, ApplicationDbContext>();
builder.Services.AddScoped<IPersistedGrantStore, PersistedGrantStore>();`

and I guess I am doing it wrong

because constructor needs two arguments 
`public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options, OperationalStoreOptions storeOptions) : base(options)
        {
            if (storeOptions == null)
                throw new ArgumentNullException(nameof(storeOptions));

            this.storeOptions = storeOptions;
        }`

**Comment by scottbrady91** [comment]
Okay, I think we've cleared up this issue. For implementation specific questions like this I would recommend StackOverflow.

**Comment by leo9223** [comment]
Alright Sir.

**Comment by leo9223** [comment]
I have done it, I have my own Configuration schema in DB for holding configuration data(clients, scopes and users) and only one table of PersistedGrants to hold persisted grants.

I am here for help if anyone other wants. skype: leo_9223

**Comment by capiono** [comment]
leo, how did you solve this issue? do you have a sample code?

**Comment by DoubleExposure** [comment]
Leo can you share your solution?

**Comment by kalebasiyakup** [comment]
leo, how did you solve this issue? do you have a sample code?
