### ISSUE TITLE
Multiple Identity Provider support

### ISSUE THREAD

**Issue by vermapraveen** [IdentityServer/IdentityServer4#4171]
### Question
Is it possible to configure multiple Identity Provider for app and use specific IdProvider base on some input in request, for example request header value has x_new_identityprovider_key from client of app. This is to support both OLD and NEW version of identity Provider until all client migrate to new. This authentication is from server(api) to server(api), no UI login.

### Currently In pipeline I do

```csharp
public virtual void ConfigureServices(IServiceCollection services)
{
  ...
  services
  .AddAuthentication("Bearer")
  .AddIdentityServerAuthentication(options =>
  {
	options.Authority =
		"https://identity_OLD.mycompany.com/"; // Set the Identity Server Authority
	options.RoleClaimType = "scope";
  });
}
```

### IS something like this possible ?

```csharp
public virtual void ConfigureServices(IServiceCollection services)
{
  ...
  services
  .AddAuthentication("Bearer")
  .AddIdentityServerAuthentication(options =>
  {
	options.Authority =
		"https://identity_OLD.mycompany.com/"; // Set the Identity Server Authority
	options.RoleClaimType = "scope";
  })
  .AddIdentityServerAuthentication(options =>
  {
	options.Authority =
		"https://identity_NEW.mycompany.com/"; // Set the Identity Server Authority
	options.RoleClaimType = "scope";
  });
}
```

**Comment by leastprivilege** [comment]
Not out of the box.

You would need to give them different scheme names and then invoke imperatively. Give that a try.

**Comment by vermapraveen** [comment]
trying to understand on scheme names from documentation and looks like it’s valid for cookie scenario; does scheme valid in api to api scenarios also?

**Comment by leastprivilege** [comment]
yes.

**Comment by vermapraveen** [comment]
so, this new IdentityProvider in above example (https://identity_NEW.mycompany.com) doesn't use IdentityServer4 and exposed single method service.AddCustomAuthorization() and app.UseCustomAuthorization(). So i think this question may not belong here, can you suggest right forum?

**Comment by leastprivilege** [comment]
sorry - I am not following.
