### ISSUE TITLE
TokenRequestValidator raises UserLoginFailureEvent with interactive=true

### ISSUE THREAD

**Issue by ArturDorochowicz** [IdentityServer/IdentityServer4#4172]
Using IdentityServer 4 3.1.2

`TokenRequestValidator.ValidateResourceOwnerCredentialRequestAsync` raises `UserLoginFailureEvent` via `RaiseFailedResourceOwnerAuthenticationEventAsync` with interactive=true. It should be interactive=false.

See: 
https://github.com/IdentityServer/IdentityServer4/blob/3.1.2/src/IdentityServer4/src/Validation/Default/TokenRequestValidator.cs#L817

**Comment by brockallen** [comment]
merged. thx
