### ISSUE TITLE
How to prevent logging for EnableTokenCleanup

### ISSUE THREAD

**Issue by akiander** [IdentityServer/IdentityServer4#4174]
### Question

Has anyone run into an issue where TokenCleanupHost.StartInternalAsync causes thread starvation? 

### Minimal working example

I have a token server running the latest version of IdentityServer4 on .net core 3.1 and using EntityFramework for the operational store only (codes, tokens, consents). 

The configuration for that looks like this: 

```csharp
                   .AddOperationalStore(options => {
                    options.ConfigureDbContext = builder =>
                        builder.UseSqlServer(ssoConnection,
                            sqlOptions => {
                                sqlOptions.MigrationsAssembly(migrationsAssembly);
                                sqlOptions.EnableRetryOnFailure();
                            });
                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                    options.TokenCleanupInterval = 30;
                })
```

### Relevant debugging information

Over time, we can watch the thread count to rise until the application crashes due to thread starvation. 

When we take a memory dump from the thread-starved process, we see hundreds of instances of threads waiting on Application Insights logging. We *think* they are rooted by the calls to TokenCleanupHost.StartInternalAsync although truthfully I am not enough of an expert to say for sure. 

here's the tasks view of the memory dump

![image](https://user-images.githubusercontent.com/1742168/76900796-69455a00-6870-11ea-81f6-0ed98464aa8c.png)

and here's the threading view showing the App Insights logging threads apparently waiting

![image](https://user-images.githubusercontent.com/1742168/76902075-8f1f2e80-6871-11ea-9d5e-df76db90f1a8.png)

My guess is that we have App Insights logging configured incorrectly but even stripping it down to what I think matches [guidance](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core), I still see the thread starvation issue. 

Wondering if anyone else has run into this or has advice.

**Comment by brockallen** [comment]
Bizarre. I'd almost ask them (meaning AppInsights or MSFT) what's going on? The background cleanup is only working on a single (logical) thread, so I don't why app insights is doing their own? I'd suggest removing app insights to see if the problem persists (since you can repo it). That'd narrow down whose issue it is :)

**Comment by akiander** [comment]
I removed Application Insights so I'll keep an eye on it for the next few days.

**Comment by akiander** [comment]
I received some help from Microsoft and it sounds like the real issue here is multiple calls to BuildServiceProvider in startup and some need for better object disposal. I will close this out once I confirm.

**Comment by akiander** [comment]
`TokenCleanupHost.StartInternalAsync` was not the cause for this issue. It was just a casualty. This was corrected by eliminating the per-request calls to `BuildServiceProvider()` in the `Startup.cs`. Apologies for the distraction.
