### ISSUE TITLE
Chrome redirect stopped working on localhost (Cookie SameSite=none) 

### ISSUE THREAD

**Issue by mikkovor** [IdentityServer/IdentityServer4#4177]
I changed nothing from 2 days ago and today redirect (localhost) from login stopped working on Chrome but still worked fine on Firefox and Edge. Googled around and apparently SameSite=none is the reason why. I disabled the SameSite flags on chrome and it started working again. But i would like to know how to fix this without changing the flags?

**Comment by mikkovor** [comment]
Adding  ```new CookiePolicyOptions { MinimumSameSitePolicy = SameSiteMode.Lax };``` seemed to do the trick

**Comment by balkarov** [comment]
@mikkovor hello. I tried to add CookiePolicyOptions  to Startup IdentityServer and WebApp, 
```
var cookiePolicyOptions = new CookiePolicyOptions { MinimumSameSitePolicy = SameSiteMode.Lax };
app.UseCookiePolicy(cookiePolicyOptions);
```

But localhost does not stop redirecting to Login page. 
IdentityServer 2.5.4, asp net core 2.2. Maybe I made some mistake?
