### ISSUE TITLE
MutualTLS options source does not match documentation, which does not match NuGet

### ISSUE THREAD

**Issue by kkohler2** [IdentityServer/IdentityServer4#4178]
From http://docs.identityserver.io/en/latest/topics/mtls.html:

    var builder = services.AddIdentityServer(options =>
    {
        options.MutualTls.Enabled = true;
        options.MutualTls.ClientCertificateAuthenticationScheme = "Certificate";

        // uses sub-domain hosting
        options.DomainName = "mtls";
    });

options is of type IdentityServerOptions and MutualTls is of type MutualTlsOptions.

Source for IdentityServerOptions does NOT contain DomainName (https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Configuration/DependencyInjection/Options/IdentityServerOptions.cs), however source for MutualTls does contain DomainName (https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Configuration/DependencyInjection/Options/MtlsOptions.cs).

Most important, with IdentityServer4 latest Nuget (3.1.2), Neither IdentityServerOption or MutualTls contain DomainName.

Using the latest Nuget, how can I get Mutual TLS working?

**Comment by brockallen** [comment]
Looks like a docs typo. The DomainName is on the mTlsOptions: https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Configuration/DependencyInjection/Options/MtlsOptions.cs#L27

**Comment by kkohler2** [comment]
I can accept that the doc is a little off, but the latest Nuget should match the git repository source code and it does not.

**Comment by leastprivilege** [comment]
The source code for the latest 3.x nuget is on the 3.x branch.

Master has code that is not released yet - but closest would be the 4.x previews.
