### ISSUE TITLE
IdentityServer does not redirect to Application

### ISSUE THREAD

**Issue by nyihtway** [IdentityServer/IdentityServer4#4179]
(disclaimer: this problem only exists in Chrome. I didn't encounter it in Firefox)

Hi All, 

I'm new to IdentityServer4, I was trying to follow the QuickStart tutorial "Interactive Applications With AspNet Core", when I run the applications, the MVC application will redirect me to IdentityServer4 login page.  But when i login, it will briefly show me the PKCE page and then redirect me back to login page. 

When i pull the project files from Github and tried, it works. I was redirected back to my MVC application. 

When i compare my tutorial project to the Github sample files, I found out that my tutorial is using Asp.Net Core 3.1 and IdentityServer4 version 3.1.0.  and the Github sample is using Asp.Net Core 3.0 and IdentityServer4 3.0.1. 

When I tried to change the Github sample to Asp.Net Core 3.1 and IdentityServer4 version 3.1.0, I faced the exact same problem again. I guess things works differently on 3.1 

As Asp.Net Core 3.1 is a must for my current project, I need to make this work. Is there any workaround or any article that I missed obviously? I had been trying to Google for past few days but the closest thing I could come up with is this issue (https://github.com/IdentityServer/IdentityServer4/issues/3296) but that also closed without any solution. 

any help would be much appreciated. 

Regards, 

Nyi

**Comment by brockallen** [comment]
More details needed. Perhaps relevant: #4170.

**Comment by nyihtway** [comment]
Hi @brockallen , awesome. Yes looks like it is. Let me go through it and try out first before closing this thread.

**Comment by gbjbaanb** [comment]
I added stpes to https-ify your project that should fix this for you.
https://github.com/IdentityServer/IdentityServer4/issues/4170#issuecomment-609075309
