### ISSUE TITLE
Can i provide also the KeyId ?

### ISSUE THREAD

**Issue by TrabacchinLuigi** [IdentityServer/IdentityServer4#4181]
# Question
Is there a simple way to provide to ids4 also the key id instead of just the RsaKey ?
I'd like to use the same certificate to sign some other stuff, and since i'm already storing the public keys with their ids in the client i'd like to expose the public key with it's id also in the other service that do that (it is not sure that the key will be changed simultaneusly, it might take some time to get all the other services updated so i want to them to have their copy of the private key, and key id) ...

Or

Is there a way to generate the same key id (kid) that can be seen in the jwks starting from the certificate ?

**Comment by leastprivilege** [comment]
We allow you setting a SecurityKey IIRC - this has a `KeyId` property.

**Comment by TrabacchinLuigi** [comment]
Amazing! and shame on me for not realizing that!
