### ISSUE TITLE
I cant connect to the Api from the Client.

### ISSUE THREAD

**Issue by dangelogonzalez** [IdentityServer/IdentityServer4#4183]
Hi everyone!
I am doing the tutorial from IdentityServer4 documentation. It is the first one, called "Protecting an API using Client Credentials". I get an Exception when calling the Api from the client, that says that a connection cannot be established as the destination computer expressly denied that connection.

This is the script from Client/Program.cs, that is the same as the tutorial:

// call api
var apiClient = new HttpClient();
apiClient.SetBearerToken(tokenResponse.AccessToken);

**var response = await apiClient.GetAsync("http://localhost:5001/identity");** 
if (!response.IsSuccessStatusCode)
{
   Console.WriteLine(response.StatusCode);
}
else
{
   var content = await response.Content.ReadAsStringAsync();
   Console.WriteLine(JArray.Parse(content));
}

![Cant connect](https://user-images.githubusercontent.com/46447149/77191038-f02c4980-6a9f-11ea-9c0e-5c61c91410d5.PNG)

**Comment by brockallen** [comment]
All hosts must be running.

**Comment by dangelogonzalez** [comment]
> All hosts must be running.

Thanks for your time.
I used “Multiple startup projects”, from Solution Property Pages. All appear to be running.
