### ISSUE TITLE
A "real world" example of IdentityServer + SPA

### ISSUE THREAD

**Issue by aTable** [IdentityServer/IdentityServer4#4186]
**Is your feature request related to a problem? Please describe.**
I found some aspects of IdentityServer a breeze but others were rough and want to help others on the learning curve. As security is critical in the modern web, I think it would be great if there was a more opinionated "production-y" example of IdentityServer than the isolated examples and needing to piece things together.

**Describe the solution you'd like**
An additional example of using IdentityServer4 showing what a best practice set up is for SaaS applications.

**Additional context**
I've had [my version](https://github.com/aTable/im-lazy) of this on the back burner for a while and have built quite a few apps with it as a starting point. I'm polishing the rough edges on it i.e converting from implicit grant to PCKE, more configuration but it's getting to a state where it could benefit others.

Do you see this (or similar) being added to the official samples?

**Comment by leastprivilege** [comment]
We don't have the resources to create or maintain additional samples right now. We are busy with feature work and feeding our families.

Hopefully this will get better in the future.

**Comment by aTable** [comment]
Totally understandable and I'll check in again later. I fully intend to keep updating my linked boilerplate and would be more than happy to share it.
