### ISSUE TITLE
Replace Newtonsoft.Json with System.Text.Json

### ISSUE THREAD

**Issue by reaction1989** [IdentityServer/IdentityServer4#4187]
This is probably harder that the change in IdentityModel.

I see following areas which are harder to tackle:

- Usage of ContractResolver (RsaKeyContractResolver --> perhaps can be replaced with JsonConverter<TemporaryRsaKey>)
- Usage of JsonProperty Order  (used in Events.cs) --> If this is critical a JsonConverter<Event> should be added which can handle the Order

The rest should be straight forward.

**Comment by leastprivilege** [comment]
OK - I think both can be dealt with.

**Comment by leastprivilege** [comment]
We made some progress on that. I think we cannot remove it completely right now.
