### ISSUE TITLE
How to configure web API in .net framework with identity server 4

### ISSUE THREAD

**Issue by moahemdsobhy** [IdentityServer/IdentityServer4#4188]
I already have an identity server 4 and it's working with .net core projects, Now I want to configure web API using .Net Framework 4.7.2.

I tried to use IdentityServer4.AccessTokenValidation but didn't know how to implement it.

I found implementation using IdentityServer3.AccessTokenValidation and tried it with client credentials grant type(the simplest one) but didn't work

app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "http://localhost:5000",
                RequiredScopes = new[] { "scope1" },
                ClientId = "client",
                ClientSecret = "secret",

            });

Please help cause it's urgent.

**Comment by Imanol91** [comment]
I have the same problem, I think that "UseIdentityServerBearerTokenAuthentication" of " IdentityServer3.AccessTokenValidation" is incompatible with the token from identityserver4.

https://github.com/IdentityServer/IdentityServer4/issues/1908
That post, the project of joaocolombo no works (project net 4.6.1 no works, the project net core work fine)

**Comment by leastprivilege** [comment]
They are compatible. Maybe the exact error message would help...

**Comment by moahemdsobhy** [comment]
First, Thank you for your reply.

It returns with unauthorized, the code as I mentioned before.

I made a custom authentication attribute to check the header in the request and it's correct and i
base.isauthorized return false.

What should I do?

**Comment by theonesuperdave** [comment]
I am experiencing the same issue, getting the following response from the .net FW 4.7.2 WebAPI:

> Unauthorized
> {"Message":"Authorization has been denied for this request."}

.net Core secured API, Azure AD, and MVC auth all work flawlessly. It is only a problem with .net FW WebAPI. Having read the docs, it reads like we are following the proper instructions. Using `IdentityServer3.AccessTokenValidation` nuget package for validation.

Please advise at your earliest convenience.

#### Startup.cs
```
public void Configuration(IAppBuilder app)
{
    app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
    {
        Authority = "http://localhost:5000",
        AuthenticationType = "Bearer",
        RequiredScopes = new[] { "blah" },
    });

    var config = new HttpConfiguration();
    config.MapHttpAttributeRoutes();

    app.UseWebApi(config);
}
```

#### packages.config
```
<packages>
  <package id="IdentityModel" version="1.9.2" targetFramework="net472" />
  <package id="IdentityServer3.AccessTokenValidation" version="2.14.0" targetFramework="net472" />
  <package id="Microsoft.AspNet.Cors" version="5.0.0" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.OwinSelfHost" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.7" targetFramework="net472" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="2.0.1" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.2.206221351" targetFramework="net472" />
  <package id="Microsoft.Owin" version="4.1.0" targetFramework="net472" />
  <package id="Microsoft.Owin.Cors" version="4.1.0" targetFramework="net472" />
  <package id="Microsoft.Owin.Host.HttpListener" version="2.0.2" targetFramework="net472" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="4.1.0" targetFramework="net472" />
  <package id="Microsoft.Owin.Hosting" version="2.0.2" targetFramework="net472" />
  <package id="Microsoft.Owin.Security" version="4.1.0" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.Cookies" version="4.1.0" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.Jwt" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.OAuth" version="3.0.1" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net472" />
  <package id="Owin" version="1.0" targetFramework="net472" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.2.206221351" targetFramework="net472" />
</packages>
```

#### Client
```
             var apiClient = new HttpClient();
            apiClient.SetBearerToken(tokenResponse.AccessToken);
            var response = await apiClient.GetAsync("http://localhost:5002/identity");
```

**Comment by theonesuperdave** [comment]
Was able to pull this from the .net FW WebAPI output. Looks like a spec change not supported by older versions of `System.IdentityModel.Tokens.Jwt`?

> Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware Error: 0 : Authentication failed
System.ArgumentException: IDX10703: Unable to decode the 'header': 'eyJhbGciOiJSUzI1NiIsImtpZCI6IlR1aW5xMFYyd2RZZmo2am50aDdXMFEiLCJ0eXAiOiJhdCtqd3QifQ' as Base64url encoded string. jwtEncodedString: 'eyJhbGciOiJSUzI1NiIsImtpZCI6IlR1aW5xMFYyd2RZZmo2am50aDdXMFEiLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1ODU5MzI3MzgsImV4cCI6MTU4NTkzNjMzOCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoiQ0ZJLkFkbWluIiwiY2xpZW50X2lkIjoiY2xpZW50Iiwic2NvcGUiOlsiQ0ZJLkFkbWluIl19.S4OWlw-FbCKFsKEgTs8hSbYxHIw-Dc9b75BoT6x2sqpuuXbRSvTw-oKCAlA-v_aflgMcLI33k9Z55J7mkeOoYOVGAdtXCELDohJiSrpIam0abiry-gRimIuUHKXGtNoK3_4bCm8hja1E_szvb7sRdGld4PBLso7tQ2nVAxozdIgvOHIhnUU3nAWGyiJRAAkTyTxHuERicr__pc93FnIHeIjkUDJurZS758TAg_9P3JUol7qrRyv9o4Tu4nHYGvnLrTCsoZJxQtkYYZyv2sBWIVWcF8AATBsLg9LtN9RHEZob-x7IHmYV4c7CT0E2OQX-L75VAGmaEMbnZcYfkl0aow'. ---> System.IdentityModel.Tokens.SecurityTokenException: IDX10702: Jwt header type specified, must be 'JWT' or 'http://openid.net/specs/jwt/1.0'.  Type received: 'at+jwt'.
   at System.IdentityModel.Tokens.JwtSecurityToken.Decode(String jwtEncodedString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityToken.cs:line 392
   --- End of inner exception stack trace ---
   at System.IdentityModel.Tokens.JwtSecurityToken.Decode(String jwtEncodedString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityToken.cs:line 403
   at System.IdentityModel.Tokens.JwtSecurityToken..ctor(String jwtEncodedString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityToken.cs:line 71
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ReadToken(String tokenString) in c:\workspace\WilsonForDotNet45Release\src\System.IdentityModel.Tokens.Jwt\JwtSecurityTokenHandler.cs:line 627
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext()

**Comment by theonesuperdave** [comment]
Got it working thanks to PR [#3760](https://github.com/IdentityServer/IdentityServer4/pull/3760) which allows us to add the required claim for legacy token validators.

@leastprivilege - I think this one is ready to be closed.

**Comment by shyamal890** [comment]
So the only change needed is to add `EmitLegacyResourceAudienceClaim` in the IdentityServer's options right?

```
services.AddIdentityServer(options =>
            {
                options.EmitLegacyResourceAudienceClaim = true;
            })
```

And then in **Startup.cs** of Asp.net WebApi as the code below.

```
public void Configuration(IAppBuilder app)
{
    app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
    {
        Authority = "http://localhost:5000",
        AuthenticationType = "Bearer",
        RequiredScopes = new[] { "blah" },
    });

    var config = new HttpConfiguration();
    config.MapHttpAttributeRoutes();

    app.UseWebApi(config);
}
```
