### ISSUE TITLE
Suggestion for code improvement

### ISSUE THREAD

**Issue by tndata** [IdentityServer/IdentityServer4#4191]
**Is your feature request related to a problem? Please describe.**

As a user of IdentityServer, when defining new Identity or API resources, the naming is a bit confusing, when it is named **ClaimTypes** in the constructor but **UserClaims** as property. 

```
var customProfile = new IdentityResource(
                            name: "Resource",
                            displayName: "Resource",
                            claimTypes: new[] { "claim1", "claim2" });

var claims = customProfile.UserClaims;
```

**Describe the solution you'd like**

Use one term for the claims inside the resource objects would make the code less confusing instead of two as it is today. Perhaps something for the next major version of IdentityServer?

**Comment by leastprivilege** [comment]
Thanks. Yes we know, but that would unfortunately be a breaking change.
