### ISSUE TITLE
None persistent DeveloperSigningCredential

### ISSUE THREAD

**Issue by gterdem** [IdentityServer/IdentityServer4#4192]
### Question
What is the impact of **not** creating a temp.rsa file for development environment?
It's persistent as default. Couldn't find much info about it.
```csharp
  AddDeveloperSigningCredential(false)
```
Can any performance-wise or anything else happen if I use it like this when debugging bunch of microservices hooked up to IdentityServer?

**Comment by brockallen** [comment]
Clients cache, so each time you restarted you'd get diff keys and the clients might not be able to validate the tokens.

**Comment by gterdem** [comment]
@brockallen Thank you,
Simply all the clients must re-signin when the identityserver is restarted if persistence is set to false. 
I would like to suggest to add this tiny piece of this information to be added under `Key Material` -> `AddDeveloperSigningCredential` at [docs](https://github.com/IdentityServer/IdentityServer4/blob/3.1.0/docs/topics/startup.rst).

Issue can be closed, thank you very much.
