### ISSUE TITLE
SourceLink does not work

### ISSUE THREAD

**Issue by hermanho** [IdentityServer/IdentityServer4#4193]
### Issue / Steps to reproduce the problem
SourceLink cannot be loaded in vs2019

### Relevant parts of the log file

Here is the sourcelink test in the following pdb:
%userprofile%\.nuget\packages\identityserver4\3.1.2\lib\netcoreapp3.1\IdentityServer4.pdb

Command:
```
>sourcelink test IdentityServer4.dll
```
Result:
```
1 Documents with errors:
fbcb5dddb109a7a0ec1695c07690b932b9abe38b6b7dbc56ee75b3c78b582f03 sha256 csharp /Users/dominick/Documents/Repos/IdentityServer/IdentityServer4/src/IdentityServer4/src/obj/Release/netcoreapp3.1/IdentityServer4.AssemblyInfo.cs
https://raw.githubusercontent.com/IdentityServer/IdentityServer4/3efcef29c14d0d8756fd8af63a0474091e8fac51/src/IdentityServer4/src/obj/Release/netcoreapp3.1/IdentityServer4.AssemblyInfo.cs
error: url failed NotFound: Not Found
sourcelink test failed
```

Fiddler log when loading symbol from nuget in vs2019
![image](https://user-images.githubusercontent.com/2337380/77364898-15ff6a00-6d90-11ea-8507-cc13451973f0.png)

**Comment by leastprivilege** [comment]
<img width="371" alt="Screenshot 2020-06-18 10 57 48" src="https://user-images.githubusercontent.com/1454075/85000633-fb504d80-b152-11ea-97bd-e5582ddd0f43.png">

**Comment by leastprivilege** [comment]
Seems all good to me.
