### ISSUE TITLE
IdentityServer4 nginx

### ISSUE THREAD

**Issue by wjkhappy14** [IdentityServer/IdentityServer4#4194]
### Question

how  to use nginx for loadbalance？
can you give a demo？
### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by leastprivilege** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1
