### ISSUE TITLE
Many methods of password-like validation?

### ISSUE THREAD

**Issue by dario-l** [IdentityServer/IdentityServer4#4198]
I'm looking for advice. I have application with API exposed to android devices and IS4 as a separated service.

I need to create authentication within android application but based on internal type it can be done by:
- password
- pin
- card id

**Questions**
1. Will **Resource Owner Password Validation** be suitable for that? If not how should I do this?
2. Where and how I can set expiration time for the token based on some business requirements during issuing **tokens**?
3. Can I disable **refresh token** based on some business requirements during issuing **tokens** (for eg. for _password_ I want to issue **refresh token** but for _pin_ and _card id_ do not)?

**Comment by leastprivilege** [comment]
Password grant is only for passwords. I guess you could re-purpose the password field somehow - but I would rather create extension grant types for the other credential types.

Ideally you would do that via a web interface and not via a grant type.

refresh tokens are a per client setting, but I guess you could strip the offline_access scope when needed - but I can't remember if it tried that before.

**Comment by dario-l** [comment]
Thanks. I'll try custom grand types.
App is specialized for people who doesn't understands why app executes something in browser.
