### ISSUE TITLE
OpenId Connect Hybrid flow + SPA + Backend  (+mobile app) 

### ISSUE THREAD

**Issue by kapoc** [IdentityServer/IdentityServer4#42]
I have SPA (angular.js) that is communicating with backend API. What I want to implement is OpenId Connect's Hybrid flow. 

I was doing this based on this sample - https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Mvc/src/IdSvrHost

It all works well if I put [Authorize] attribute on some controller & try to access it - I'm being redirected to login screen and can sign in. I'm using AspNet OpenId Connect middleware for logging user in and accessing his claims. 

The problem is that I want to have a simple login screen with no redirects after being unauthorized user (i.e. first time user enters the application and clicks 'Log in' button). 

What I can't wrap my head around is this (from the sample mentioned above, LoginController.cs): 

```
        [HttpGet(Constants.RoutePaths.Login, Name = "Login")]
        public async Task<IActionResult> Index(string id)
        {
            var vm = new LoginViewModel();

            if (id != null)
            {
                var request = await _signInInteraction.GetRequestAsync(id);
                if (request != null)
                {
                    vm.Username = request.LoginHint;
                    vm.SignInId = id;
                }
            }

            return View(vm);
        }
```
Login screen gets this SignInId cookie & id (during the unauthorized redirect) that is being later used during the actual logging in (for SignInResult).

1) Is Hybrid flow best suited for having SPA that is used together with Backend API? Both the client & identity server here are ours so they're trusted. 
2) If SignInId is not necessary, then what could be the approach to implemented hybrid flow with blank login form? 
3) If SignInId is necessary, then what could be the workflow for having blank log in screen & using this approach? Redirecting with [Authorize] is, sadly, the only option that I see right now
4) Can this approach (OpenId Connect's hybrid flow) work well with mobile apps? (having in mind cookies, storage, etc) 
5) Currently Identity Server is inside another project (next to my API) - would anything change if both API & Identity Server would be inside the same project (self hosted) or this doesn't affect anything?

**Comment by xabikos** [comment]
I am also having the same questions and I am interested to hear some answers. I am developing a Reactjs application and would like to fully customize the log in screens and remove the redirects if possible.

**Comment by leastprivilege** [comment]
You can't remove redirects - they are part of the protocol.

As for the login UI - simply customize the views and controllers.

**Comment by xabikos** [comment]
So I guess there is no way to implement a full Ajax login workflow even if we remove the consent part.

**Comment by leastprivilege** [comment]
No - and that is by design.

**Comment by leastprivilege** [comment]
if you want to skip the server side UI altogether you can always use resource owner flow instead - but this is generally not recommended since you are losing SSO and federation this way (amongst other things).

**Comment by xabikos** [comment]
Thanks for the answer. It's more clear for me now.
