### ISSUE TITLE
Refresh Tokens documentation is misleading

### ISSUE THREAD

**Issue by joaco-espinosa** [IdentityServer/IdentityServer4#4206]
Reference: https://identityserver4.readthedocs.io/en/latest/topics/refresh_tokens.html

Excerpt:
> `RefreshTokenExpiration`
> 
> `Absolute` the refresh token will expire on a fixed point in time (specified by the _AbsoluteRefreshTokenLifetime_)
> 
> `Sliding` when refreshing the token, the lifetime of the refresh token will be renewed (by the amount specified in SlidingRefreshTokenLifetime). The lifetime will not exceed _AbsoluteRefreshTokenLifetime_.

The documentation _suggests_ that Absolute=0 and Sliding=1 but values are reversed.

I confirmed this by inspecting the values for:
* `IdentityServer4.Models.TokenExpiration.Absolute` (=1)
* `IdentityServer4.Models.TokenExpiration.Sliding` (=0)

Can you please correct this inconsistency? The `RefreshTokenUsage` values order is correct.

**Comment by brockallen** [comment]
@leastprivilege also, maybe we can revisit this for 4.0?

**Comment by brockallen** [comment]
Sorry, we checked -- we don't agree. The default is absolute, in case that helps?
