### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by JonLam925** [IdentityServer/IdentityServer4#4209]
this error appears when using "app.UseIdentityServer()" in the startup.cs file in my MvcApp. Any ideas?

System.InvalidOperationException: 'No storage mechanism for grants specified. Use the 'AddInMemoryPersistedGrants' extension method to register [a](url) development version.'

**Comment by leastprivilege** [comment]
Please check the quickstarts for getting started. 

https://identityserver4.readthedocs.io/en/latest/quickstarts/0_overview.html
