### ISSUE TITLE
Add option to force discovery doc returns https endpoints

### ISSUE THREAD

**Issue by ericvan76** [IdentityServer/IdentityServer4#421]
I'm running IdentityServer (in http) behind [https-portal](https://github.com/SteveLTN/https-portal), which results discovery doc returns all endpoints starts with http, not https.

Is there any way to let discovery doc force returns https when it's running in http?

**Comment by leastprivilege** [comment]
You would use middleware to dynamically change the scheme (and other parts of the URL).

This is built-in for IIS, and there is more general purpose middleware for that using the X-override headers like `app.UseHttpMethodOverride`.

**Comment by ericvan76** [comment]
Thanks
