### ISSUE TITLE
Support tracking consumed refresh tokens (for replay detection)

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#4213]
e.g. for refresh tokens

**Comment by brockallen** [comment]
Add ConsumedDateTime column which implied the grant was consumed. Logic in the RT service determines how to use this value (including a possible threshold/window for double RT requests).

The token cleanup service would then cleanup based on very old consumed values (configurable?) something like 24 hours.

**Comment by brockallen** [comment]
PR submitted
