### ISSUE TITLE
Best way to add sub claim for client credential tokens

### ISSUE THREAD

**Issue by Jacobski-fr** [IdentityServer/IdentityServer4#4214]
Hello,
  I need to integrate Identity Server 4 with WSO2 API Manager. WSO2 currently requires that all JWT access tokens emitted by IS4 contain a "sub" claim even those emitted by client credentials flow.
  The answer for the issue #3628 was to use some extension points in order to add sub claim in client credentials flow. I would like some guidance to do so.
  First I thought of implementing ICustomTokenRequestValidator but, as I understand it : 
- Setting `ValidatedRequest.Subject` will lead to adding other claims like IdentityProvider which have no meaning
- Adding to ClientClaims but it would require to set ClientClaimsPrefix to an empty string and I am not fond of it
  So, for now, I was going to extend the DefaultTokenService with the following code :
``` csharp
public override async Task<Token> CreateAccessTokenAsync(TokenCreationRequest request)
{
     var result = await base.CreateAccessTokenAsync(request);

     if (result != null && result.SubjectId == null)
     {
         result.Claims.Add(new Claim(JwtClaimTypes.Subject, request.ValidatedRequest?.ClientId));
     }

     return result;
}
```

It is safe (regarding to impacts and maintainability) to do it that way or is there a better option?

Thanks in advance,

**Comment by leastprivilege** [comment]
that's fine.

**Comment by Jacobski-fr** [comment]
Thanks
