### ISSUE TITLE
Enable to customize ScopeValidator

### ISSUE THREAD

**Issue by vstribrny** [IdentityServer/IdentityServer4#4215]
Hi, I need to customize the `IdentityServer4.Validation.ScopeValidator` being use in default implementations of `IAuthorizeRequestValidator`, `ITokenRequestValidator`and `IDeviceAuthorizationRequestValidator`.

Suggested solution:
* Introduce new interface - IScopeValidator.
* Make public methods of ScopeValidator virtual to be able to override standard implementation.

In fact, even today I could register my class derived from `ScopeValidator` into the DI container. The problem is that public methods in ScopeValidator are not virtual so the implementation from the base class gets called anyway.

Thanks!

**Comment by leastprivilege** [comment]
We just re-worked that for v4. We don't plan to make any changes to v3.

**Comment by vstribrny** [comment]
In the sources of v4, I do not see any changes in regards to customize `ScopeValidator` (looking into 4.0.0-preview.2 tag), or am I just missing something?

**Comment by leastprivilege** [comment]
there is no preview yet. We merged just a couple of days ago. Will publish a preview soon.

**Comment by leastprivilege** [comment]
The preview is up on nuget now. No docs - but our sample host has some code showing how it works.
