### ISSUE TITLE
.AspNetCore.Antiforgery.* Secure is false over https

### ISSUE THREAD

**Issue by jaydgus** [IdentityServer/IdentityServer4#4219]
I recently updated to Core 3.1.2 and IS4 3.1.2.

I noticed that the .AspNetCore.Antiforgery.* cookie is set to Secure = false over https.  Is this expected behavior?  

This is on Chrome 80 and FF 74.

Thanks,
Jay

**Comment by leastprivilege** [comment]
Please ask Microsoft about this.
