### ISSUE TITLE
releases/3.1.x won't build

### ISSUE THREAD

**Issue by serefarikan** [IdentityServer/IdentityServer4#4221]
Hi, I wanted to build the current release (3.1.2) from sources but failed. 

### Issue / Steps to reproduce the problem
Clone IdentityServer4 repository. Checkout `releases/3.1.x` branch. run `.\clean.ps1` followed by `.\build.ps1` as per instructions.
Build fails due to Host project under the following solutions not having references to `System.Security.Principal.Windows` nuget packages.
Adding this nuget package to IdentityServer4/host, AspNetIdentity/host and EntityFramework/host projects fixes the problem. 

This is Windows 10 Professional with .NET Core 3.1 SDK installed.

Should I be looking elsewhere for a working build that is the origin of the current nuget packages?

**Comment by leastprivilege** [comment]
that's a breaking change in .NET Core. Could you please create a PR with the changes you did?

**Comment by serefarikan** [comment]
thanks, of course, I'd be delighted to. Thanks for the great work you've done btw.

**Comment by serefarikan** [comment]
Closing since fixed and merged:
https://github.com/IdentityServer/IdentityServer4/commit/7292ac9da3021d4f7dac58c449e5b78d7fef072c
