### ISSUE TITLE
Is there way to use IdServer4 also be a client for itself ? 

### ISSUE THREAD

**Issue by mfarkan** [IdentityServer/IdentityServer4#4229]
### Question

I'm new at IdServer 4 and i also achived using IdServer with SPA or any other applications but im wondering am i able to use IdServer itself as a web application ? I mean I've a admin account (it has godMode claim) and i want to login with this account (without other clients redirect to IdServer) IdServer for Admin pages but i couldnt make it.

I create for another login page to login but its not authenticated. What do you think about my silly idea ? Which advice do you give me ?

**Comment by leastprivilege** [comment]
It's just a "normal" ASP.NET application. You can do whatever you want to it ;)

**Comment by mfarkan** [comment]
Yea it is but i'm confuse about **ConfigureApplicationCookie** and **AddAuthentication.AddCookie.** IdServer use **ConfigureApplicationCookie** , i  **AddAuthentication.AddCookie.** add for new login path for (/admin/login) but signInManager not logged me in :) so i need to some research about it thank you :) @leastprivilege
