### ISSUE TITLE
AdditionalClaims parameter to SignInAsync not working

### ISSUE THREAD

**Issue by Lalithkx** [IdentityServer/IdentityServer4#423]
The additionalClaims parameter that we pass to "await HttpContext.Authentication.SignInAsync(....) does not get reflected in the token to the angularClient2. Looks like it is a bug as the additionalClaims parameter has no effect on the final token. Could this be a bug? I was trying to add a couple of role claims.

**Comment by leastprivilege** [comment]
Passing additional claims into the cookie does not mean that they are included in the token automatically. That's the job of the profile service to decide which claims go into which token.

**Comment by Lalithkx** [comment]
How do we do that for InMemoryProfileService? Do we derive from it and override GetProfileAsync?

**Comment by leastprivilege** [comment]
InMem is only designed for testing - why do you want to use that?

Create your own profile service, that's what you have to do anyways.
