### ISSUE TITLE
Is Sign In with Apple supported for native iOS Apps?

### ISSUE THREAD

**Issue by minichma** [IdentityServer/IdentityServer4#4232]
We're using IdentityServer 4 with [AspNet.Security.OAuth.Apple](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.Apple) to implement a (browser-based) authorization grant flow. This works great for browsers and also for Android Apps (using [AppAuth-Android](https://github.com/openid/AppAuth-Android)). However, the flow in native iOS apps is somewhat different. I.e. an authentication code and ID token are received within the iOS app and forwarded to the server, where they are validated and used for establishing an authenticated user session. To my understanding, this kind of flow is not supported using the `AspNet.Security.OAuth.Apple` component. I've opened a [separate ticket](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/issues/399), requesting corresponding support.

**Our setting**
* We have mobile apps (iOS and Android) and a browser-based SPA.
* We have an IdentityServer, used for authentication
* We have a resource server hosting the actual APIs.
* The apps usually authenticate against IdentityServer using an Authorizatoin Grant flow and receive a refresh token and an access token from there.
* The apps use the access token to access the resource server.

This flow doesn't work for _Sign in with Apple_ in native iOS apps, because the authorization grant flow doesn't seem to be supported there.

**Intended solution**
To work around this limitation, we intend to implement the following solution:
* Implement the login procedure inside the iOS App as outlined in [Apple's documentation](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple) and receive an access code within the app.
* Forward the access code to IdentityServer, probably to a custom extension of the `token` endpoint.

On IdentityServer
* Exchange the `code` for a `refresh_token` and an `access_token` as outlined [in Apple's docs](https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple).
* Create `access_token` and `refresh_token` on IdentityServer, that wrap the tokens returned by the Apple APIs and return the newly created tokens to the calling app.
* Let the app use the `access_token` to access the resource server. After expiration, let the app use the `refresh_token` to refresh the `access_token` via IdentityServer.
* Let IdentityServer accept the `refresh_token` via the regular `token` endpoint using the `refresh_token` grant type. Let IdentityServer wrap Apple's `refresh_token` and use it to validate the validity of the token using [Apple's token endpoint](https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens).
* On success return a new `access_token`.

**Questions**

* Does the approach as outlined make sense?
* Is this kind of flow supported by IdentityServer?
* Do examples exist of how to implement this kind of flow?
* Which are the basic building blocks for implementing this kind of flow?

Thanks for any assistance!

**Comment by brockallen** [comment]
Is this what you're looking for?

https://identityserver4.readthedocs.io/en/latest/topics/extension_grants.html

**Comment by minichma** [comment]
@brockallen Basically yes. My hope was, that there are some more specific building blocks that help in implementing this flow. In the end I'd expect many developers to have the sime kind of challenge and implementing the flow from scratch is not exactly trivial. Especially dealing with the refresh tokens causes me headaches.

I'm actually trying to implement a custom `IExtensionGrantValidator`. Some of the challenges are
* Can I reuse existing functionality for doing a code exchange? Doesn't seem so, so I'm doing it on my own on top of `HttpClient` (will reuse [AppleClientSecretGenerator](https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.Apple/AppleClientSecretGenerator.cs) though).
* How would I deal with the `refresh_token` returned by Apple? I'd like to wrap it into a custom refresh token, unwrap it on token refresh and use it to validate against Apple. But how would I implement this? I found https://github.com/IdentityServer/IdentityServer4/issues/449. Is this the way to go?
