### ISSUE TITLE
invalid_request code challenge required. What is code challenge? How to get one?

### ISSUE THREAD

**Issue by wzup** [IdentityServer/IdentityServer4#4238]
### Question

What is code challenge? How do I get it?

I'm trying to test my JS React SPA against IdentityServer4 DEMO server https://demo.identityserver.io/. 
I do not set up local ASP .NET server, I'm not familiar with the technology. So I want to test against IdentityServer4 DEMO server https://demo.identityserver.io/.well-known/openid-configuration.

But demo server returns me 
> Sorry, there was an error : invalid_request
code challenge required

Documentation doesn't answer, it has only this which doesn't help much

![screenshot-identityserver4 readthedocs io-2020 03 31-14_47_08](https://user-images.githubusercontent.com/3880497/78009531-ce17ae80-735e-11ea-98b9-5ad7917029d5.png)

### Minimal working example

My JS code
```javascript
const config = {
  authority: "https://demo.identityserver.io",
  client_id: "interactive.confidential",
  redirect_uri: "http://localhost:3000/callback",
  response_type: "code",
  scope:"openid profile email api offline_access",
  post_logout_redirect_uri : "http://localhost:3000/post_logout",
};

const url = `https://demo.identityserver.io/connect/authorize?
client_id=${config.client_id}&
redirect_uri=${config.redirect_uri}&
response_type=${config.response_type}&
scope=${config.scope}`;

  const onFormSubmit = async (ev: React.FormEvent) => {
    window.location.replace(url);
  };
```

### Response
![screenshot-demo identityserver io-2020 03 31-14_43_26](https://user-images.githubusercontent.com/3880497/78009141-35812e80-735e-11ea-87e7-9f82d511cc2c.png)

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by brockallen** [comment]
> Documentation doesn't answer, it has only this which doesn't help much

The docs are not intended to teach you the protocols. You need to learn those yourself, and here's the link to the spec in question: https://tools.ietf.org/html/rfc7636

**Comment by emnu1971** [comment]
Hi All,
Had this error to, but IHMO it's a typical error that is thrown when you have a server / client configuration mismatched. For example you enable PKCE on the server (for a specific client id) but on the respective client you disable PKCE protection in the OIDC configuration setup, then this kind of error (code challenge required) will be thrown. So check your configs first :).
Kr,
Emmanuel.
