### ISSUE TITLE
When signin directly on IDS4 login page the ProfileService is not called

### ISSUE THREAD

**Issue by joovnaz** [IdentityServer/IdentityServer4#4239]
## Issue / Steps to reproduce the problem
When signin directly on IDS4 login page the `ProfileService` is not called.

If I use a client everything goes fine and the profile service is triggered.

Is there any way to trigger it even for local signin?

**Comment by brockallen** [comment]
The profile service is used when tokens need to be created. That's why just logging in does not call it.

**Comment by joovnaz** [comment]
Thanks a lot for your prompt reply.

Please consider a scenario where a given claim, currently injected by protocol, should show up even after local authentication, 
For now, to do so I have customized `UserClaimsPrincipalFactory' but does not look a very elegant solution (DRY...).
Given the logic is basically replicated both in `ProfileService` and `UserClaimsPrincipalFactory` customized classes, i.e.
[1] create principal
[2] add extra claims 
[3] return new principal

maybe might get (optionally) married somehow,
Best

**Comment by brockallen** [comment]
You can add any claims you want at login, and those are carried over to profile service via the `Subject`.

**Comment by joovnaz** [comment]
Many thanks.
