### ISSUE TITLE
Auto login with Windows Auth for already authenticated user

### ISSUE THREAD

**Issue by DenisIvanovIvanov** [IdentityServer/IdentityServer4#4242]
Is there a workaround to skip providing credentials for Windows Auth if the user is already authenticated against the AD (by login in the Win itself)? Currently it always prompts me for credentials if the session is not expired? I want when there is login request to automatically login with windows (which I've done it) and if unauthorized to go to manually providing credentials for user created in our DB. Which will be easy to do (I guess) when there is no prompt for windows credentials.

**Comment by brockallen** [comment]
This is a more general purpose question and not really specific to IdentityServer.
