### ISSUE TITLE
Identity server 4 loclaAPi Frequently giving Error: Response status code does not indicate success: 503 (Server has been shutdown).

### ISSUE THREAD

**Issue by mwaleedr** [IdentityServer/IdentityServer4#4247]
I am using identity server 4 for token base authentication i have a asp.net mvc core application which is using code flow to get access token and i id token. I am using identity model client to get code and then access token and idtoken from identity server 4. Now when i get access token and i tries to hit localapi which is in identity server 4, first time it gives me this error   "Response status code does not indicate success: 503 (Server has been shutdown)". And when i hit second time and hits again and again it does not give that error anymore.

**Comment by brockallen** [comment]
No idea; you've not provided nearly enough info.

**Comment by mwaleedr** [comment]
what kind of enough information you needed

**Comment by mwaleedr** [comment]
public async Task<IActionResult> Index()
        {
            var accessToken = Request.Cookies.Where(c => c.Key == "accessToken").FirstOrDefault().Value;
            if (!string.IsNullOrEmpty(accessToken))
            {
                return RedirectToAction("Callback");
            }
            var client = new HttpClient();
            var disco = await client.GetDiscoveryDocumentAsync(new DiscoveryDocumentRequest
            {
                Address = authorityBaseUrl,
                Policy =
                {
                    RequireHttps = false
                }
            });
                    var authorizeUrl = new RequestUrl(disco.AuthorizeEndpoint).CreateAuthorizeUrl(
            clientId: "colaraz.web.edly",
            responseType: "code",
            scope: "openid profile IdentityServerApi",
            redirectUri: "http://localhost:5001/LogIn/Callback",
            state: "random_state",
            nonce: "random_nonce"
            );
            //var url = $"{authorityBaseUrl}/connect/authorize?client_id=colaraz.web.edly&scope=openid profile IdentityServerApi&response_type=code&redirect_uri=http://localhost:5001/LogIn/Callback";
            return Redirect(authorizeUrl);
        }
        public async Task<IActionResult> Callback()
        {
            var accessToken = Request.Cookies.Where(c => c.Key == "accessToken").FirstOrDefault().Value;

            string id_token = "";
            var client = new HttpClient();
            if (string.IsNullOrEmpty(accessToken))
            {
                var query = Request.Query;

                var code = query["code"].ToString();

                var tokenResponse = await client.RequestAuthorizationCodeTokenAsync(new AuthorizationCodeTokenRequest
                {
                    Address = $"{authorityBaseUrl}/connect/token",

                    ClientId = "colaraz.web.edly",
                    ClientSecret = "20cbbd2f-b22e-40b0-81b3-6450eaae2ecf",

                    Code = code,
                    RedirectUri = "http://localhost:5001/LogIn/Callback",

                });
                if (tokenResponse.IsError)
                {
                    ViewBag.Error = tokenResponse.Error;
                    return View();
                }
                accessToken = tokenResponse.AccessToken;
                id_token = tokenResponse.IdentityToken;

                Response.Cookies.Append("id_token", id_token);
                Response.Cookies.Append("accessToken", accessToken);
            }
            if (!string.IsNullOrEmpty(accessToken))
            {
                var jsonString = "";
                try
                {
                    HttpClient Apiclient = new HttpClient();
                    string url = $"{authorityBaseUrl}/UserInformationApi";
                    Apiclient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                    jsonString = await Apiclient.GetStringAsync(url);
                    //jsonString = await response.Content.ReadAsStringAsync();
                    LoggedInUser LoggedInUser = JsonConvert.DeserializeObject<LoggedInUser>(jsonString);

                    ViewBag.UserInformation = LoggedInUser;


                }
                catch (Exception ex)
                {
                    ViewBag.Error = ex.Message.ToString();
                    Response.Cookies.Append("JsonResponse", jsonString);
                    return View();
                }

            }

            return View();
        }

**Comment by mwaleedr** [comment]
the above method is used to createAuthorize url and redirect to identity and the below one is used as a callback function

**Comment by mwaleedr** [comment]
now when call back got hit and i receive access token which i use to hit localapi which is in identityserver4 , now first time this api gives error in respone  "Response status code does not indicate success: 503 (Server has been shutdown)" but when i hit it again it gives me data

**Comment by brockallen** [comment]
What I'm looking for is something that you can find to pinpoint that there's an issue/bug in the IdentityServer component itself. If there's a bug in our code, we will address it. Logs would be a good place to start. 

We're not going to debug and diagnose all of your code on top, though. Sorry.
