### ISSUE TITLE
Client properties or claims best practices recommendations and questions

### ISSUE THREAD

**Issue by pacojones** [IdentityServer/IdentityServer4#4248]
Hi all,
I have a question about client properties or claims, I'm not sure which is the best approach so I need some help on the right path if you guys can help me out.

First of all, I'm using Identity Server to issue tokens so my APIs use them. I request a new token through the /connect/token endpoint then I use them on my APIs.

Basically, I want to store some sort of custom properties per client so I can (a) pass them with the token to the APIs or (b) make another call inside the APIs to Identity server in order to get those properties.

Those properties may be simple data such as a basic key-value pair set, or could be more complex data, but the main thing is that the set of data (set of key-values) may be different from client to client.

So my questions are:
1. Where should I put this in terms of client? is this custom properties or claims?
2. Should I (or shouldn't) include this on my token? Apart from customization required on ProfileService, I'm not sure if it is the right path since tokens will become huge and those properties may be quite sensitive
3. If I want to get this information later inside my API, is there any endpoint I can call to get this? I only found out UserInfo endpoint but it is related to the user only, is there anything related to client?

Thanks a lot.

**Comment by leastprivilege** [comment]
1) Properties are to extend the internal configuration system. Claims will get emitted to tokens.

2) tokens should only contain the bare minimum

3) no - but you could provide such an endpoint yourself.
