### ISSUE TITLE
Does Front-channel logout only work on the same domain?

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4#4249]
Hi, we have our IdServer4 on a single domain name but have several relying parties, each on 2 domain names (different TLD's)

eg 
IdServer4
id.domain1.com

RP1
rp1.domain1.com
rp1.domain2.com

RP2
rp2.domain1.com
rp2.domain2.com

So in the above example we have 4 Clients. We're using front channel logout but it only seems to work on domain1.com, when we try on domain2.com the endpoint is hit but IsAuthenticated is always false. Is this expected or can I do something to fix it?

![image](https://user-images.githubusercontent.com/2369739/78349969-4e772300-759c-11ea-8792-8dd409c3f0c8.png)

**Comment by brockallen** [comment]
Front channel is not designed for a client running on several different domains (as cookies are scoped to domain). Consider configuring 2 clients for the 2 domains, as that better aligns to how cookies work.

**Comment by daver77** [comment]
Yeah I have 2 clients for each relying party so for RP1 I have 2 clients with the following FrontChannelLogoutUris

rp1.domain1.com/fcl
rp1.domain2.com/fcl

When logging out the rp1.domain2.com/fcl is hit from id.domain1.com correctly passing the sid but fails on the IsAuthenticated. Should that work?

**Comment by daver77** [comment]
> Consider configuring 2 clients for the 2 domains, as that better aligns to how cookies work.

I do have 2 clients for the 2 domains, do you think that should work?

**Comment by leastprivilege** [comment]
This will soon not work reliably anymore. We recommend switching to back-channel notifications for cross-site scenarios.

https://leastprivilege.com/2020/03/31/spas-are-dead/

**Comment by enikitin** [comment]
Could you point to a good sample of back-channel logout? 
I need to logout from the IdP UI and make all the web clients abandon their sessions.
