### ISSUE TITLE
When does RemoveAllAsync(+1 overload) get invoked? (PersistedGrantStore)

### ISSUE THREAD

**Issue by SpiritBob** [IdentityServer/IdentityServer4#4250]
When does **IdentityServer4** invoke the methods with the following signature: `RemoveAllAsync(string, string)`, as well as `RemoveAllAsync(string, string, string)`?

I'm aware that it calls `RemoveAsync(string key)` when someone revokes a given token, but what about the other ones?

Thank you.

**Comment by brockallen** [comment]
It's there if you wanted to build a UI to allow an end user to revoke.

**Comment by SpiritBob** [comment]
> It's there if you wanted to build a UI to allow an end user to revoke.

Thanks! Every other method apart from those 2 has its usage otherwise, correct?
