### ISSUE TITLE
CheckSession Iframe - AvastPasswords causing error due to DOMChanged event

### ISSUE THREAD

**Issue by SFBBI** [IdentityServer/IdentityServer4#4252]
### Issue / Steps to reproduce the problem

Hi,

We are using identity server in a production environment where a user is using [Avast Passwords](https://www.avast.com/en-gb/passwords#pc) in Firefox.

This cause a lot of `error` message to be posted by the `checksession` iframe to the parent window.
After some search  and debugging of the `checksession` source code, it seem's that [this line is causing the issue](https://github.com/IdentityServer/IdentityServer4/blob/f756a0fb653bc152039ca18921ed0ad38812e315/src/IdentityServer4/src/Endpoints/Results/CheckSessionResult.cs#L321):
```javascript
var idx = message.lastIndexOf(' ');
```

The [Avast Passwords](https://www.avast.com/en-gb/passwords#pc) browser extension seem's to raise some `DOMChanged` event periodically, which cause a `TypeError: message.lastIndexOf is not a function`.

**Comment by brockallen** [comment]
Why is Avast Passwords sending messages to an iframe windows that it knows nothing about?

**Comment by SFBBI** [comment]
I don't know ...
But the problem only appears when this extension is enabled.
When we are disabling it in the browser, the problem disappear.

I don't know how I can prove you this issue...
It's really annoying because we notifying the user when a session error appear, and it's happening every second.

In the debugger we can see that the `checksession` code is catching an exception:
![image](https://user-images.githubusercontent.com/49191468/78535846-203c5200-77ed-11ea-8710-c589987227b8.png)

And here is a screenshot of the raised event that causes the error:
![image](https://user-images.githubusercontent.com/49191468/78536740-9d1bfb80-77ee-11ea-8806-57f3231aa653.png)

The error appears because `data` is an object and not a string.

**Comment by brockallen** [comment]
> But the problem only appears when this extension is enabled.
> When we are disabling it in the browser, the problem disappear.

Kind of makes you think they're doing something wrong, no?

In any event, the code in the check session is following the spec from here: 

https://openid.net/specs/openid-connect-session-1_0.html#OPiframe

And I don't see anything to change which would not produce your error from a rogue caller into the iframe.
