### ISSUE TITLE
Scope mandatory for authorization code flow ?

### ISSUE THREAD

**Issue by nileshnikalje** [IdentityServer/IdentityServer4#4254]
Hi, 

 We are using IdentityServer. The client is using authorization code without a scope. The IdentityServer throws "Scope is missing". As per the RFC (https://tools.ietf.org/html/rfc6749#section-4.1.1) the scope is optional for authorization code flow. Any plans for fix this in future release?

**Comment by leastprivilege** [comment]
We made the decision to require the scope parameter on the authorize request. No plans to change that.
