### ISSUE TITLE
How can I implement my own ClientStore with custom ReturnType in IdentityServer4?

### ISSUE THREAD

**Issue by mgh9** [IdentityServer/IdentityServer4#4255]
I wanna add some extra columns (e.g. ClientCustomProperty) to the Client entity in IdentityServer4, and deal with them in my business layer so I'm creating my custom Store:
```
public class MyClientStore : IClientStore
{
    public Task<IdentityServer4.Models.Client> FindClientByIdAsync(string clientId)
    {
         // ...
    }
}
```
 but the IClientStore.FindClientByIdeAsync signature :
`Task<IdentityServer4.Models.Client> FindClientByIdAsync(string clientId);`
doesn't fulfill my problem. I don't want to return `IdentityServer4.Models.Client` type.

I'm looking for something like this (Generic ReturnType):
```
Task<TModel> FindClientByIdAsync<TModel>(string clientId)
    where TModel: class, IClientModel /* IClientModel is in IS4 */
```

How can I do that?

**Comment by brockallen** [comment]
If you need your concrete type, then build your own APi for obtaining that. Don't try to add your type semantics onto ours -- we've just not designed for that.

**Comment by mgh9** [comment]
OK, thank you anyway
