### ISSUE TITLE
Update to EF Core 5.0

### ISSUE THREAD

**Issue by AndriySvyryd** [IdentityServer/IdentityServer4#4259]
The next EF Core 5.0 preview will contain a binary breaking change that affects new apps that use IdentityServer4 with EF Core 5, like the ones created with the ASP.NET Core templates.

**Comment by shanselman** [comment]
?

**Comment by leastprivilege** [comment]
We will not update to EF Core 5 any time soon.

If that means that the old templates are broken - that's unfortunate. They are not designed for 5.0.

**Comment by AndriySvyryd** [comment]
We've reverted the change, so this is no longer urgent. But please do let us know if you are willing to coordinate a major release in the future.
