### ISSUE TITLE
Identity server 4 does not hit front channel logout url every time when client log out.

### ISSUE THREAD

**Issue by mwaleedr** [IdentityServer/IdentityServer4#4260]
I have deployed an identity server 4 app on IIS which is running on this url http://identity.colaraz.net and i am running a .net mvc core app on localhost using code flow. I have registered a frontchannel logout url for this mvc client. Now when i logout from my mvc client app, front channel logout got hit some time and some time not. This only happens when i deploy identity server 4 on server but when i run both identity server 4 and mvc client app on localhost then this works ok. I am unable to understand why this is happening please help

**Comment by brockallen** [comment]
> I have registered a frontchannel logout url for this mvc client.

One guess -- your IdentityServer is https, and the local app on localhost is http. Check your browser console window for errors.

**Comment by mwaleedr** [comment]
both identity server and localhost are http.

**Comment by leastprivilege** [comment]
Maybe it is a "third party cookie in iframe" problem.

IOW - browsers are making it harder to use front-channel logout these days. I don't know if your problem is related to that - but my advice would be to switch to back-channel logout anyways.

**Comment by mwaleedr** [comment]
hey @leastprivilege  thanks for your response i will test backchannel , let suppose that it is due to browser but i hvae implemented DefaultUserSession, IUserSession interface to check logged in clients and before logging out i get the logged in clients and then print it on the loggedOut view to check the clients which were logged in but this also some time give me logged in clients and some time not why this happens on server and on localhost it works fine.

**Comment by leastprivilege** [comment]
Yes that’s absolutely possible.

**Comment by mwaleedr** [comment]
but i am also having problem in single sing on, it works some time and some time not why the
 behavior is uncertain
