### ISSUE TITLE
Improve AllowedGrantTypes error messages and documentation

### ISSUE THREAD

**Issue by guillaumeTactics** [IdentityServer/IdentityServer4#4265]
I use IdentityServer (v2.5.3) and recently went from code-defined clients to appSettings-defined (see http://docs.identityserver.io/en/3.1.0/topics/clients.html)

In the process I made the mistake of translating `AllowedGrantTypes = GrantTypes.ClientCredentials` into `"AllowedGrantTypes": [ "ClientCredentials" ]` when the correct value is `"client_credentials"`.

I noticed that:
 - The error message I get when trying to authenticate with a client defined as `"ClientCredentials"` is 
`Client not authorized for client credentials flow, check the AllowedGrantTypes setting`
(not accurate and can be misleading)
 - The error message I get when trying to authenticate with a client defined as any other invalid type is
`Invalid client configuration for client X : no allowed grant type specified`
(better but still ambiguous)

Could these messages be harmonized, and maybe the help page listed above mention the different format in json mode?

**Comment by leastprivilege** [comment]
Thanks for reporting. The 2.x version does not get feature updates anymore.

But maybe something to consider for 4.x

**Comment by leastprivilege** [comment]
I guess the issue is that we don't easily know if the grant type is invalid, since you can define your own...

I guess our client configuration validator plumbing could query all grant types and see if the one used is valid or not. If you want to give this a try - that'll be nice.
