### ISSUE TITLE
How do you decide which user claims are returned?

### ISSUE THREAD

**Issue by tolemac** [IdentityServer/IdentityServer4#4266]
### Question

How do you decide which user claims are included on token?
I have build my IdentityServer from `is4aspid` template and I am getting only the follow claims:
```
s_hash=tFpbakJatWNQIjaChraJAw
sid=Sj6JGUgztjOIK1Cq8E-HoA
sub=a070c8cc-d962-440c-a796-e0c169e87578
auth_time=1586427090
idp=local
amr=pwd
```

I have wrote a [question on stackoverflow](https://stackoverflow.com/questions/61119142/identityserver4-return-unknown-claims-using-openid) (before to know you accepts questions here).

Searching for a reason for this result I have clone and build this repo, I have run `6_AspNetIdentity` Quickstart sample and the result is similar:

![image](https://user-images.githubusercontent.com/247167/78968663-79fe8e00-7b05-11ea-99b8-d38becfe02e0.png)

However [the doc shows](https://identityserver4.readthedocs.io/en/latest/quickstarts/6_aspnet_identity.html) this:

![image](https://user-images.githubusercontent.com/247167/78968815-c8ac2800-7b05-11ea-9e29-e32867a1b662.png)

Why the results are different? how to decide what claims are include in the token?

**Comment by brockallen** [comment]
https://brockallen.com/2019/02/25/scope-and-claims-design-in-identityserver/

**Comment by tolemac** [comment]
Yes, very enlightening article strongly recomended.

In addition, the answer on [my stackoverflow question](https://stackoverflow.com/questions/61119142/identityserver4-return-unknown-claims-using-openid) make me debug `ProfileService` and `DefaultClaimsService` where I have understood the same that the article tells.

Thanks!!
