### ISSUE TITLE
Getting Error in latest source of Quick start project with ASP.NET Core 3.1 

### ISSUE THREAD

**Issue by gowthamece** [IdentityServer/IdentityServer4#4271]
I'm getting error from latest source code, the assembly IdentityServer4.Validation is not loading from the source code after integrating with my project using powershell script

**Comment by brockallen** [comment]
Not enough into.

**Comment by KostetskyiYaroslav** [comment]
Hey @brockallen ,

I think @gowthamece says that the latest commit for Quickstart repo makes ~25 compilation errors.

For instance, the VS 2019 says it can't find `ParsedScopeValue` and `ApiScope` classes in `DeviceController.cs`.

Also, there it can't access to `ValidatedResources` property of request ( `DeviceFlowAuthorizationRequest` type ) that is received from here -> https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/master/Quickstart/Device/DeviceController.cs#L148

![image](https://user-images.githubusercontent.com/13874357/79078383-a3d7d080-7d10-11ea-8d1c-79a2d7bdf542.png)

Thanks!

**Comment by KostetskyiYaroslav** [comment]
Hey @gowthamece,

I did manage to avoid the above errors by checkouting at Dec 20 date for Quickstart project.
PS: Exactly this commit - https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/tree/0ae3fa9f5f5bf5cd1223b3f27882b431adc4b1d9

![image](https://user-images.githubusercontent.com/13874357/79078794-7e989180-7d13-11ea-9991-d5c9152af957.png)

cc: @brockallen

**Comment by gowthamece** [comment]
Hi @KostetskyiYaroslav , 

  Exactly this is what the issue I'm facing with VS 2019, let me try https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/tree/0ae3fa9f5f5bf5cd1223b3f27882b431adc4b1d9

**Comment by sberube** [comment]
@KostetskyiYaroslav @gowthamece did you manage to solve the issue? Thanks!

**Comment by gowthamece** [comment]
> @KostetskyiYaroslav @gowthamece did you manage to solve the issue? Thanks!

Yes, thanks for the support 👍
