### ISSUE TITLE
Support application/json content-type on IdentityServer endpoints

### ISSUE THREAD

**Issue by kristijan-ujevic** [IdentityServer/IdentityServer4#4273]
Hello,

I'm sure this is not the first time someone is requesting this, but this is something that should be configurable and/or supported.

`application/x-www-form-urlencoded` is the only `content-type` that is supported at the moment, `application-json` should also be supported.

Is there a specific reason this is not supported yet?

Thanks

**Comment by leastprivilege** [comment]
For which endpoints? - and could you attach a link to the relevant part of the relevant spec where it says that this is a specified content type?

**Comment by kristijan-ujevic** [comment]
All of the endpoints, here is an example for token endpoint:

https://identityserver4.readthedocs.io/en/latest/endpoints/token.html#example

**Comment by leastprivilege** [comment]
I see what you are saying, but IdentityServer is an implementation of a specification.  The spec says, e.g.

> 4.4.2.  Access Token Request

   The client makes a request to the token endpoint by adding the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body.

https://tools.ietf.org/html/rfc6749#section-4.4.1

**Comment by kristijan-ujevic** [comment]
That's what I figured, however would it be possible for something like:

```
services.AddIdentityServer(options =>
{
    options.Endpoints.UseApplicationJsonContentType = true;
    // or
    options.Endpoints.ContentType = MediaTypeNames.Application.Json;
}
```

Then it's just a matter of adding a new set of controllers to support it, and inject them according to these options.

**Comment by leastprivilege** [comment]
Everything is possible. But we only implement specifications.
