### ISSUE TITLE
SignInAsync no longer sets time

### ISSUE THREAD

**Issue by jez9999** [IdentityServer/IdentityServer4#4274]
The resolution to #2650 removed a number of extension methods for `SignInAsync`, many of which set `AuthenticationTime` with:

```
var clock = context.GetClock();
[...]
AuthenticationTime = clock.UtcNow.UtcDateTime
```

The suggested replacement quickstart code doesn't set the time:

```
var isuser = new IdentityServerUser(user.SubjectId)
{
    DisplayName = user.Username
};

await HttpContext.SignInAsync(isuser, props);
```

Might this not be an issue worth fixing?

**Comment by leastprivilege** [comment]
IIRC if the time is missing it is filled in by the authentication service - and that becomes the `auth_time` claim. 

Is there a problem?
