### ISSUE TITLE
Deploy IdentityServer4 on ubuntu Nginx

### ISSUE THREAD

**Issue by dicksonkimeu** [IdentityServer/IdentityServer4#4282]
Any guidance on this ?

**Comment by leastprivilege** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1

**Comment by dicksonkimeu** [comment]
My API works on Nginx and kestrel too, however, the get token url works on kestrel only. If i switch to Nginx the request doesn't even reach my identity server.

If i use Kestrel i works, if i use nginx it brings (BAD REQUEST).

Below is my Nginx settings.

NGINX ASP.NET CORE CONFIG

server {
    listen 80;

    server_name saleslife.cloud;
    large_client_header_buffers 8 16k;
    client_header_buffer_size 64k;
    http2_max_field_size 16k;
    http2_max_header_size 128k;

    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;


        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
     }
}
