### ISSUE TITLE
PKCE Verification doesn't appear to be implemented correctly.

### ISSUE THREAD

**Issue by kabua** [IdentityServer/IdentityServer4#4284]
In review the [RFC 7636](https://tools.ietf.org/html/rfc7636#page-8) today, I noticed the following paragraph:

``` 
If the "code_challenge_method" from Section 4.3 was "S256", the
   received "code_verifier" is hashed by SHA-256, base64url-encoded, and
   then compared to the "code_challenge", i.e.:

   BASE64URL-ENCODE(SHA256(ASCII(code_verifier))) == code_challenge

   If the "code_challenge_method" from Section 4.3 was "plain", they are
   compared directly, i.e.:

   code_verifier == code_challenge.
```

And the verification code:

        private bool ValidateCodeVerifierAgainstCodeChallenge(string codeVerifier, string codeChallenge, string codeChallengeMethod)
        {
            if (codeChallengeMethod == OidcConstants.CodeChallengeMethods.Plain)
            {
                return TimeConstantComparer.IsEqual(codeVerifier.Sha256(), codeChallenge);
            }

            var codeVerifierBytes = Encoding.ASCII.GetBytes(codeVerifier);
            var hashedBytes = codeVerifierBytes.Sha256();
            var transformedCodeVerifier = Base64Url.Encode(hashedBytes);

            return TimeConstantComparer.IsEqual(transformedCodeVerifier.Sha256(), codeChallenge);
        }

I may not be reading the spec right, but it appears to me that the code is Sha256() the codeVerifier one too many times. E.g. The possible problem lies with:

                return TimeConstantComparer.IsEqual(codeVerifier.Sha256(), codeChallenge);

and with:

            return TimeConstantComparer.IsEqual(transformedCodeVerifier.Sha256(), codeChallenge);

I think these two lines should read as:

                return TimeConstantComparer.IsEqual(codeVerifier, codeChallenge);

and

            return TimeConstantComparer.IsEqual(transformedCodeVerifier, codeChallenge);

**Comment by pieterphilippaerts** [comment]
PKCE is implemented correctly.

I'm not familiar with the source code of IdentityServer, but I can only assume that they store all secrets (client secrets, codes, etc.) as hashes in the database. This is the safest thing to do (you don't actually need the original secrets, so why risk getting them stolen) and explains why you're seeing these 'extra' calls to Sha256.

**Comment by leastprivilege** [comment]
@pieterphilippaerts That's correct.

**Comment by kabua** [comment]
Oh good, that makes a lot of sense. Thanks for taking the time to explain it.
