### ISSUE TITLE
cnf claim doesn't seem to work for mTLS

### ISSUE THREAD

**Issue by pieterphilippaerts** [IdentityServer/IdentityServer4#4285]
I'm testing mTLS with the latest version of IdentityServer4 (straight from the repository). I've configured a client on the test site to use/require mTLS and this works perfectly. (I've verified that I cannot get a token without the client certificate I've configured.)

However, when I look at the JWT token that the server returns, there seems to be a problem with the cnf claim. According to the mTLS specification (RFC8705), the cnf claim should have a property "x5t#S256" that holds the hash of the certificate that was used when the token was requested. However, this is the (unpacked) token I got from IdentityServer4:

```
{
  "alg": "RS256",
  "kid": "BD55BCDFD7DC43A6BACD426E6EC1E18AEC3CE375RS256",
  "typ": "at+jwt",
  "x5t": "vVW839fcQ6a6zUJubsHhiuw843U"
}
{
  "nbf": 1586950818,
  "exp": 1586951418,
  "iss": "https://localhost:44365",
  "client_id": "secure_client",
  "sub": "88421113",
  "auth_time": 1586947791,
  "idp": "local",
  "jti": "7CC98784B028BC9B707F5359CB21353B",
  "sid": "3CD31E0C8B6054ED80EAC2095EBB1335",
  "scope": [
    "IdentityServerApi",
    "offline_access"
  ],
  "amr": [
    "pwd"
  ],
  "cnf": {
    "x5t#S256": []
  }
}
```

The cnf claim is present and it contains a property "x5t#S256", but the value of that property is an empty array. This confuses me a bit as (1) it's not supposed to be an array according to the specification, but a string, and (2) it's not supposed to be empty.

Can you verify whether this is a bug in IdentityServer4?

**Comment by leastprivilege** [comment]
hm. Can't repro

![image](https://user-images.githubusercontent.com/1454075/79345460-6ef69400-7f31-11ea-982e-6de231997107.png)

**Comment by leastprivilege** [comment]
![image](https://user-images.githubusercontent.com/1454075/79345596-9a797e80-7f31-11ea-8d2e-f00fc54445bd.png)

**Comment by leastprivilege** [comment]
Do you have more info - and maybe some relevant log entries?

**Comment by pieterphilippaerts** [comment]
Hi Dominick,

After some debugging, I was able to pinpoint the source of the bug. It turns out that something changed in the JwtPayload class (in System.IdentityModel.Tokens.Jwt) in version 6.5.0 that introduces this bug. If I downgrade the System.IdentityModel.Tokens.Jwt package to version 5.6.0, everything works correctly.

At some point during the creation of the access token, the CreateJwtPayload method (in the IdentityServer4.Extensions.TokenExtensions class) gets called. The JwtPayload result of method seems to be correct at first sight. All the claims are there, and the cnf claim is still correct.

![payload_raw](https://user-images.githubusercontent.com/16557893/79353442-5a1efe00-7f3b-11ea-818b-6a8365e854cb.png)

However, if we look at the Claims property of the token, this is what we get:

![payload_claims](https://user-images.githubusercontent.com/16557893/79353458-5d19ee80-7f3b-11ea-91c7-1a682ee24b12.png)

Notice that the cnf claim now isn't correct anymore. It returns the array that I'm seeing on the client side when I unpack the access token.

I don't know whether this is a bug in the JwtPayload class, or whether it's a bug in IdentityServer4 (maybe you're not supposed to add JToken instances anymore?). In any case, I'll leave it to you to figure it out :-)

**Comment by leastprivilege** [comment]
The 6.x version of the JWT handler has breaking changes and is not supported by us.

**Comment by pieterphilippaerts** [comment]
OK 🙂
