### ISSUE TITLE
Cnf claim is calculated incorrectly

### ISSUE THREAD

**Issue by pieterphilippaerts** [IdentityServer/IdentityServer4#4286]
When using mTLS, IdentityServer4 has to add the "x5t#S256" claim to the token. However, it seems that the calculation of the value of this property is wrong.  The CreateThumbprintCnf method that calculates the value incorrectly uses the Thumbprint property of the certificate as its hash. This is problematic, because
 (1) the thumbprint is a SHA-1 hash, whereas the "x5t#S256" property expects a SHA-256 hash.
 (2) Thumbprint returns a hexadecimal string, whereas the string in "x5t#S256" should be Base64Url encoded

I believe the code should be changed to first call the certificate.GetCertHash(HashAlgorithmName.SHA256) method, and then convert the result to a string by using the Base64Url encoding.

**Comment by leastprivilege** [comment]
This sounds reasonable. I will have a look.

**Comment by leastprivilege** [comment]
Created a PR.
