### ISSUE TITLE
MapUniqueJsonKey Function is not available in new release.

### ISSUE THREAD

**Issue by nikhilhece2011** [IdentityServer/IdentityServer4#4287]
![image](https://user-images.githubusercontent.com/3807094/79363356-cc7ce780-7f15-11ea-969a-c083e26c42a8.png)

@leastprivilege @brockallen  I am trying to get the claim type "role" at client side, I am getting this claim at IDP side. 
However somehow I am not able to get this function which will map the new claim type for my client. Please check the screenshot.

Although I have seen this link [https://github.com/IdentityServer/IdentityServer4/issues/1786].
But Do you seriously think that this is the last approach only to get this.

**Comment by brockallen** [comment]
That's an ASP.NET Core feature, not an IdentityServer feature.

**Comment by nikhilhece2011** [comment]
I resolved it.
