### ISSUE TITLE
Quickstart.UI translation to pt-BR

### ISSUE THREAD

**Issue by fauresco** [IdentityServer/IdentityServer4#4288]
Please, let me know if you would like me to submit a PR to Quickstart.UI with translation to pt-BR.

In my project, I have created resource files for each folder inside Views and then modified each view. I.e.:

Resources/Account.resx
Resources/Account.pt-BR.resx

Resources/Consent.resx
Resources/Consent.pt-BR.resx

You get the idea.

**Comment by brockallen** [comment]
Thanks for the offer. I think the focus is on the security mechanics, and the more features we add I think the more complicated the quickstarts become (also to maintain).

**Comment by fauresco** [comment]
Yes, makes sense!
