### ISSUE TITLE
Best way to migrate schema to SqlServer

### ISSUE THREAD

**Issue by not-good-with-usernames** [IdentityServer/IdentityServer4#4289]
### Question

Hi, I've used the Quickstart solution to generate my Sql Server schema. Now using the IdentityServer4 server doesn't work with that schema because there is a mismatch between the models the schema was based on, and the models in the IdSrv4 project.

When I looked deeper into this, I noticed the Quickstart solution referenced IdSrv v3.1.2 assemblies. The IdSrv4 project references v4-preview assemblies. This would explain why there is a mismatch, but now I'm at a loss on how to move forward.

Is there (or will there be) an up-to-date Quickstart? 
Should I even be using Quickstart to generate the schema? 
Is there a better way to do it?
Is there a baseline IdentityServer4 implementation that I should use that does not use preview assemblies?

Thanks,

Dave

**Comment by brockallen** [comment]
No, we don't provide a comprehensive schema migration plan, as that would be a tremendous amount of work for all the different DB providers and versions to do properly. Here's where we document that fact:

https://identityserver4.readthedocs.io/en/latest/reference/ef.html#database-creation-and-schema-changes-across-different-versions-of-identityserver
