### ISSUE TITLE
Exp is in the past

### ISSUE THREAD

**Issue by jeanpoelie** [IdentityServer/IdentityServer4#4291]
### Issue / Steps to reproduce the problem
Some of our users are experiencing problems with logging in, the logging reports that:
**Error: exp is in the past: [time]**

We have been able to reproduce this fully.
A user who has a different timezone (read, Amsterdam, London, Sydney etc.) will not have this error occuring because the time is converted to UTC.
A user who lives in The Netherlands currently has a time of 13:15.
They change their time manually (ignore the phone setting for network timezone) will set a time by hand, but they actually do not change the time, keep it at 13:15.
The time on the server is in UTC, and is current 11:15.
Normally this would match because Timezone Europe/Amsterdam is +2 in UTC at this moment.
But because the user turned of network syncing it seems to think that 13:15 is the UTC time, therefore the user will have a exp in the past.
This also works for aic is in the future (same steps).

We reproduce this 100% of the time, now this either seems to be a bug for the phones, which would make it irrelevant here, or, it is a bug that the library does not keep in mind that a user can remove syncing.

I feel like this should be investigated a bit to see if we can get a users timezone even though they turned of their time syncing.

**Comment by leastprivilege** [comment]
I am confused. Why would this  be a bug in the library that creates the JWT?

We set the exp according to the spec in epoch time UTC.

**Comment by jeanpoelie** [comment]
I agree that the error that is thrown is correct when it is in the past.
But in our use case the user turned their automatic timezone off, kept their timezone in Amsterdam Europe (GMT+2) and than moved their time by 40 minutes.
I am wondering if this handling should be done differently in the library where you just check the timezone of a user, than get the 'now' time from that timezone and convert it to utc rather than using the users clock time and taking away the GMT+2

**Comment by leastprivilege** [comment]
>  in the library

Which library are you talking about?

**Comment by jeanpoelie** [comment]
the OIDC javascript version of this library: https://github.com/IdentityModel/oidc-client-js
I am assuming the handling of timezones is done in the backend (Identity Server)

**Comment by leastprivilege** [comment]
There are no timezones. All times are UTC. Interpreting that is the job of the client. Not the (Identity) Server. Makes sense?

**Comment by jeanpoelie** [comment]
Allright, I was under the impression the client sends client time and the server converts it, I will move the ticket to oidc-client-js
