### ISSUE TITLE
DefaultClientConfigurationValidator bug

### ISSUE THREAD

**Issue by naretto** [IdentityServer/IdentityServer4#4295]
Just upgraded my package from 2.2.0 to latest 3.1.2 and found this bug.

### Issue / Steps to reproduce the problem

Path: https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Validation/Default/DefaultClientConfigurationValidator.cs
File: DefaultClientConfigurationValidator.cs
Method: ValidateUriSchemesAsync

Repro:
Validation for "RedirectUris" checks if "uri" is null using "?": 
if (_options.Validation.InvalidRedirectUriPrefixes.Any(scheme => uri?.StartsWith(scheme, StringComparison.OrdinalIgnoreCase) == true))
Line 188

Validation for "PostLogoutRedirectUris" doesn't check for null and raises "Object reference not set to an instance of an object" if uri is null:
if (_options.Validation.InvalidRedirectUriPrefixes.Any(scheme => uri.StartsWith(scheme, StringComparison.OrdinalIgnoreCase)))
Line 200

The work around is to set a blank value for "logoutRedirectUri" so it is never null.

JSON config example:
"logoutRedirectUri": ""

**Comment by brockallen** [comment]
Fixed, thanks.
