### ISSUE TITLE
Why can't I log in with the test user credentials?

### ISSUE THREAD

**Issue by kfrajtak** [IdentityServer/IdentityServer4#4296]
I have cloned the repository and used the IdentityServer with UI from `2_InteractiveAspNetCore`. But I can't sign in with any test user. I am using Microsoft Edge (the new one built on Chromium).

I guess I am authenticated, in the output I can see 
```
[10:30:42 Debug] IdentityServer4.Hosting.IdentityServerAuthenticationService
Adding idp claim with value: local
[10:30:42 Debug] IdentityServer4.Hosting.IdentityServerAuthenticationService
Adding amr claim with value: pwd
[10:30:42 Information] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: idsrv signed in.
[10:30:42 Information] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler
AuthenticationScheme: idsrv was challenged.
```

But redirect to `grants` do not work and I see the form to enter username and password instead.

In the logs there is also this:
```
[10:30:42 Debug] IdentityServer4.Hosting.CorsPolicyProvider
CORS request made for path: /Account/Login from origin: null but was ignored because path was not for an allowed IdentityServer CORS endpoint
```

In the dev tools new cookies appear after "signing in": `idsrv.session` and `idsrv`.

**Comment by kfrajtak** [comment]
Does not work on my PC in Edge, works in Chrome. 
Works perfectly on my notebook in Chrome, FF, IE and Edge.

**Comment by priyank89patel** [comment]
@kfrajtak Can you show us how your `IdentityServer `is configured?

`IdentityServer4`needs to be configured to make it work with test users. Something like this

```
var builder = services.AddIdentityServer()
                .AddInMemoryIdentityResources(Config.Ids)
                .AddInMemoryApiResources(Config.Apis)
                .AddInMemoryClients(Config.Clients)
                .AddTestUsers(TestUsers.Users);
```

**Comment by kfrajtak** [comment]
That's what I did. Please note that it only does not work on one machine in Edge.
