### ISSUE TITLE
Pairwise subject identifier support

### ISSUE THREAD

**Issue by asleire** [IdentityServer/IdentityServer4#4298]
This is a feature request for pairwise subject identifier support according to the OpenID Connect specification. 

I couldn't find an issue, but I think there should be one.

I'm wondering what the current status is. The `PairWiseSubjectSalt` has been present on the `Client` model for a while, and there's a PR https://github.com/IdentityServer/IdentityServer4/pull/1578 with some discussion that was eventually closed as "postponed".

**Comment by leastprivilege** [comment]
it's in the backlog. It's a bigger change than we thought.
