### ISSUE TITLE
Enable extensibility or replacement for endpoint handlers

### ISSUE THREAD

**Issue by tillig** [IdentityServer/IdentityServer4#43]
I would like to be able to dynamically change the contents of the discovery document based on the URL currently being accessed. For example, the "name" of the Identity Server instance should change based on the URL.

The problem I'm trying to solve is to enable a multitenancy in IdentityServer4. While I recognize this may not be an explicit goal for the project, allowing extension points at certain places where I can plug in will allow me to customize the experience.

In [`IdentityServerServiceCollectionExtensions`](https://github.com/IdentityServer/IdentityServer4/blob/d86dfb59eee571990dbff30e4620401c6f32779d/src/IdentityServer4/Configuration/IdentityServerServiceCollectionExtensions.cs#L84) the set of `IEndpoint` instances associated with different well-known endpoints is added to the service collection as part of an `EndpointRouter`. There's really no way to modify the `IEndpoint` associated with a request or to affect the `IEndpointResult` generated by a request.

One way to get around this would be to introduce a new `IEndpointMapping` interface, like this:

```csharp
public interface IEndpointMapping
{
  public string Endpoint { get; }
  public Type Handler { get; }
}
```

Instead of using a `Dictionary<string, Type>` right in the `AddEndpoints` routing registration extension, you could change to do stuff like:

```csharp
if (endpoints.EnableTokenEndpoint)
{
  var mapping = new EndpointMapping
  {
    Endpoint = Constants.RoutePaths.Oidc.Token,
    Handler = typeof(TokenEndpoint)
  };
  services.AddInstance(typeof(IEndpointMapping), mapping);
  services.AddTransient(mapping.Handler)
}
```

[`EndpointRouter`](https://github.com/IdentityServer/IdentityServer4/blob/1836d57440c0b3fd4ec856e815d22a10873e5606/src/IdentityServer4/Hosting/EndpointRouter.cs) could be changed to take `IEnumerable<IEndpointMapping>` instead of `Dictionary<string, Type>`. It can read the `IEndpointMapping` instances and only add the first of a given name that's encountered - so if two endpoints are registered with the same endpoint name, the first one in wins (silently - no error).

You could then just register it as a singleton during `AddEndpoints` instead of registering  a specific instance:

```csharp
services.AddSingleton(typeof(IEndpointRouter), typeof(EndpointRouter));
```

If I need to override an endpoint, I can just register my overrides after your defaults:

```csharp
var mapping = new EndpointMapping
{
  Endpoint = Constants.RoutePaths.Oidc.Token,
  Handler = typeof(MyCustomTokenEndpoint)
};
services.AddInstance(typeof(IEndpointMapping), mapping);
services.AddTransient(mapping.Handler)
```

When the singleton for the `IEndpointRouter` gets resolved from DI, it will see my endpoint mapping for the endpoint first and use that instead of the default.

My `IEndpoint` implementation can derive from the default, call base at the right time, and do customization as needed. It can use any dependency registered, so it's pretty open to do whatever it needs.

I can PR something like that if it sounds interesting.

**Comment by leastprivilege** [comment]
fwiw - According to the spec, the issuer name is the base URL of the instance. So if it is only about that value, that would be taken care of automatically. For true multi-tenancy you'd need per tenant scope, client, user stores etc. IdentityServer (nor asp.net core itself) is designed for that.

wrt your proposal - we will discuss this. thanks

**Comment by tillig** [comment]
Ah, good point about the spec. Thanks for the tip. But, yeah, if you are interested in this, I'd still be interested in seeing it added.

**Comment by brockallen** [comment]
we added this today. more cleanup to be done, but it's a start.

**Comment by tillig** [comment]
Just took a peek. Looks really nice!

**Comment by brockallen** [comment]
I think we're done on this one.
