### ISSUE TITLE
Custom user service GetProfileDataAsync not getting called

### ISSUE THREAD

**Issue by Lalithkx** [IdentityServer/IdentityServer4#430]
Implemented a custom service class derived from IProfileService. The custom impl of GetProfileDataAsync is not getting called. Can somebody tell me what is being done wrong or what needs to be done?

I have the following in startup

`.AddProfileService<IdentityWithAdditionalClaimsProfileService>()
            .SetSigningCredential(cert)
            .AddOperationalStore(builders => builders.UseSqlServer(connectionString, 
                                    options => options.MigrationsAssembly(migrationsAssembly)))
            .AddConfigurationStore(builders => builders.UseSqlServer(connectionString, 
                                    options => options.MigrationsAssembly(migrationsAssembly)))
            .AddAspNetIdentity<ApplicationUser>();`

Thanks

**Comment by Lalithkx** [comment]
On further investigation looks like the constructor of the custom service is not getting called. I am also adding a TransientService for the custom user service.

`services.AddTransient<IProfileService, IdentityWithAdditionalClaimsProfileService>();`

**Comment by leastprivilege** [comment]
inspect the IServiceCollection at the the end of ConfigureServices to make sure your implementation is in the container.

**Comment by nhdmalik** [comment]
@leastprivilege why my profile service not added in container by services.AddProfileService call?

**Comment by StanislavChankov** [comment]
In my case switching the places of `.AddProfileService<TService>()` and `.AddAspNetIdentity<TUser>()` solved the problem.
So instead of:
`.AddProfileService<IdentityProfileService>();`
`.AddAspNetIdentity<ApplicationUser>();`
Declare
`.AddAspNetIdentity<ApplicationUser>();`
`.AddProfileService<IdentityProfileService>();`

**Comment by GWJYonder** [comment]
> In my case switching the places of `.AddProfileService<TService>()` and `.AddAspNetIdentity<TUser>()` solved the problem.

I don't know how you stumbled into figuring that out but bless you for it, you just stopped my bleeding at two hours of wasted time.
