### ISSUE TITLE
Broken Quickstart Guide - Adding the UI

### ISSUE THREAD

**Issue by MatthewJones517** [IdentityServer/IdentityServer4#4300]
### Issue / Steps to reproduce the problem

The Quickstart guide appears to be broken. Specifically, everything breaks that the point you try to add the UI files. 

1.) Complete the first Quickstart guide [Protecting an API using Client Credentials](https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html)

2.) Continue to the second Quickstart guide [Interactive Applications with ASP.NET Core](https://identityserver4.readthedocs.io/en/latest/quickstarts/2_interactive_aspnetcore.html)

3.) Attempt to add the UI in any of the following ways:
- Type `dotnet new is4ui` in ./src/IdentityServer
- Run the following bash command in ./src/IdentityServer: `curl -L https://raw.githubusercontent.com/IdentityServer/IdentityServer4.Quickstart.UI/master/getmaster.sh | bash`
- Clone the Quickstart UI repo and manually copy in the files.

Upon building the IdentityServer Project you are presented with 18 errors. I have attached them to this report. 

[ErrorLog.txt](https://github.com/IdentityServer/IdentityServer4/files/4494369/ErrorLog.txt)

Initially many of these appeared to just be missing namespaces, but as I dug deeper the errors got more gnarly. I really would like to learn IdentityServer, but this issue with the documentation has had me stumped for the past three days. 

I should point out that the "finished" project in the Samples folder of the main repo does not have this problem, which tells me there's a step or two missing somewhere in the Quickstart guide. 

Finally, I'm not sure if it's relevant but I'm using Visual Studio for Mac.

Any help you can offer would be greatly appreciated.

**Comment by leastprivilege** [comment]
> Type dotnet new is4ui in ./src/IdentityServer

this should work?!

**Comment by MatthewJones517** [comment]
> > Type dotnet new is4ui in ./src/IdentityServer
> 
> this should work?!

I promise you it doesn't. I tried that multiple times before trying the other options. 

If you take the time to go through the steps I outlined, following the tutorial EXACTLY (not adding any info you know outside if it) the errors I posted result. 

Would it help if I recorded my screen of me doing this step by step?

If I knew enough about Identity Server I'd just update the docs and do a pull request. Unfortunately I don't.

**Comment by MatthewJones517** [comment]
Here's video of me following the quick-start guide step by step.
https://youtu.be/Yx5jdVmgj-s

**Comment by leastprivilege** [comment]
Hey, 

thanks for taking the time to record this - yes, so this is a breaking change in ASP.NET Core itself after the quickstart was released.

Microsoft moved the type and you need to add an additional nuget package

```
<PackageReference Include="System.Security.Principal.Windows" Version="4.7.0" />
```

**Comment by MatthewJones517** [comment]
Awesome. Thanks for looking into this for me. I appreciate it.
