### ISSUE TITLE
Missing CVE info

### ISSUE THREAD

**Issue by 1Jesper1** [IdentityServer/IdentityServer4#4302]
Hello, why is this security issue still reserved? https://cve.mitre.org/cgi-bin/cvename.cgi?name=2018-14766 Version 2.6.2: https://github.com/IdentityServer/IdentityServer3/releases/tag/2.6.2

**Comment by 1Jesper1** [comment]
@leastprivilege is it possible to provide info?

**Comment by leastprivilege** [comment]
No. I don't know what this is. Anybody can open CVEs.

That being said - IdentityServer3 has some security updates. We distribute them via the security maintenance program.

https://leastprivilege.com/2020/01/05/identityserver3-and-upcoming-samesite-cookie-changes-in-browsers/

**Comment by 1Jesper1** [comment]
Thanks for the reply!
