### ISSUE TITLE
Question about login and authentication flow

### ISSUE THREAD

**Issue by webczat** [IdentityServer/IdentityServer4#4304]
Hi, I actually have two questions:
1. I was just curious why identity server has it's own logic to redirect to a login page instead of using things like ChallengeAsync? How does that work if I have a normal mvc webapp with login flow that also serves as oidc provider, similar to, say, github?
2. Why UseIdentityServer calls UseAuthentication internally? Is that done for any specific reasons? I see that the only real thing before it is cors configuration.

**Comment by brockallen** [comment]
1: because we need more redirect semantics beyond challenge -- we have consent, error, logout, etc. so mainly for consistency.

2: we need to order the middleware in a particular way.

**Comment by webczat** [comment]
What are the order requirements? Because from what I know identity server does not influence the AuthenticateAsync and that is what authentication middleware calls... Just curious.

**Comment by brockallen** [comment]
The code's there -- go have a look.

**Comment by webczat** [comment]
well that's generally what I figured from code. I may be looking again in a while. Thanks.
