### ISSUE TITLE
Support for hybrid flow when using custom user store

### ISSUE THREAD

**Issue by No1e** [IdentityServer/IdentityServer4#4305]
Hello, I hope you are well and healthy,

I am not sure if this is actually feature request or question related to my lack of knowledge.

Is it possible to use hybrid flow when using custom user store? As far as understood, using custom user store makes only OAuth 2.0 resource flow available, which lacks of some security features available in OpenID Connect hybrid flow. 

Or we are forced to used ASP.Net Core Identity if we want to use OpenID Connect flows?

Thank you and best regards,
Nole

**Comment by No1e** [comment]
Would it be correct to simply implement communication with custom user store in the Account controller?

Best regards,
Nole

**Comment by Dheerajmentor** [comment]
i also have this question
