### ISSUE TITLE
Why user interaction local url must be under the same path of IdSrv ?

### ISSUE THREAD

**Issue by alaincroisetiere** [IdentityServer/IdentityServer4#4306]
Redirection to user interaction use the extension method below and force local url to be under the same path of IdSrv because of GetIdentityServerBaseUrl :
```csharp
public static void RedirectToAbsoluteUrl(this HttpResponse response, string url)
{
    if (url.IsLocalUrl())
    {
        if (url.StartsWith("~/")) url = url.Substring(1);
        url = response.HttpContext.GetIdentityServerBaseUrl().EnsureTrailingSlash() + url.RemoveLeadingSlash();
    }
    response.Redirect(url);
}
```
User is redirect to /auth/identity/acount/login instead of /identity/account/login with this configuration :
```csharp
public void ConfigureServices(IServiceCollection services)
{
    [...]
    var builder = services.AddIdentityServer(options =>
        {
            options.UserInteraction.LoginUrl = "/identity/account/login";
            [...]
        });
    [...]
}

public void Configure(IApplicationBuilder app)
{
    [...]
    app.Map("/auth", idApp => idApp.UseIdentityServer());
    [...]
}
```

Modify the the extension as below should solve the issue :
```csharp
public static void RedirectToAbsoluteUrl(this HttpResponse response, string url)
{
    if (url.IsLocalUrl())
    {
        if (url.StartsWith("~/")) url = url.Substring(1);
        url = response.HttpContext.GetIdentityServerHost().EnsureTrailingSlash() + url.RemoveLeadingSlash();
    }
    response.Redirect(url);
}
```

**Comment by alaincroisetiere** [comment]
Possible fix : https://github.com/alaincroisetiere/IdentityServer4/tree/features/userinteraction-redirect

**Comment by alaincroisetiere** [comment]
Temporary fixed with url rewriter but not ideal.
```csharp
app.UseRewriter(new RewriteOptions().AddRedirect(@"^(.[^/]{1,36})/(?i:account|consent|device|home)($|[/\?#].*)$", "/$2$3"));
```

**Comment by AndersAbel** [comment]
I've seen the same error when deploying IdentityServer under /identity (to keep endpoints backwards compatible with an old IdSrv3 instance). Redirects to the Account controller and /Home/Error incorrectly gets an `/identity` prefix.

I'm not sure how easy it is to fix this in a generic way though. Just skipping PathBase would fix it if the rest of the application runs in the root. But that would break the current behaviour for anyone running IdSrv+MVC UI under a path prefix.

**Comment by brockallen** [comment]
From our discussions, I think this is a hard problem to solve internally in IdentityServer. So the hosting layer needs to handle this in whatever way makes sense. Closing unless there's something more specific you think we need to do.

**Comment by AndersAbel** [comment]
I agree to closing it since there's really nothing that can be done due to how the pipeline/APIs work. And to run IdentityServer under a mapped path different to the MVC controllers is a bad idea. Don't go that way.

**Comment by alaincroisetiere** [comment]
Could that be an option of UserInteraction to give more control of LoginUrl, LogoutUrl, ConsentUrl, ErrorUrl, DeviceVerificationUrl ?
