### ISSUE TITLE
Simple OAuth Wrapper for Windows Authentication - ASP.net Core 3.0

### ISSUE THREAD

**Issue by martinkoslof** [IdentityServer/IdentityServer4#4309]
Hello, I am currently trying to do something I believe is simple in ASP.net Core 3.0/3.1 but I'm having a different time pulling things apart. High level, in summary, I need to wrap Windows/Kerberos authentication within a simple oauth IDP or provider. While IdentityServer4 looks great, I don't need ASP.net Identity, I don't need SqlLite or a sql database. I was hoping to implement something similar to what I see here:

https://github.com/IdentityServer/WindowsAuthentication

But unfortunately it didn't seem to port over to ASP.net core 3.0.  How can I do something similar? I just need to provide an oauth compatible end point, which will use integrated security, populate a claim and provide back the proper oauth flow and token.

Looking at the quick starts I see how it is doing windows authentication, but it seems too complex and feature rich (again, I don't need any sort of persistence, external vs internal ways to login and such) for me to wrap my head around.

Thanks in advance

**Comment by leastprivilege** [comment]
Both our docs and the quickstart UI have the bits and pieces for Windows authentication

**Comment by martinkoslof** [comment]
This really doesn't answer my question sadly.  I have no external providers of login (just windows), I have no need for ASP.net Identity hooking into EntityFramework, I have no need for MVC pages for consents and checking "my grants", I was hoping, as noted, the simple example provided could be done in a similar fashion in ASP.net 3.1. I fail to see how that sample is even 5% of the bloat and unnecessary parts the quick start UI provide for IdentityServer4.

Thanks, I'll move on and consider this not a viable option.

**Comment by leastprivilege** [comment]
Well - all the bits and pieces are there - and you can absolutely achieve what you are asking for. I am sorry we don't have a sample for your exact use case.

If you don't want to spend some time with it, I guess, it is indeed not a viable option. Sadly.
