### ISSUE TITLE
Getting clients and scopes from db 

### ISSUE THREAD

**Issue by nburak** [IdentityServer/IdentityServer4#431]
Hello, I want to ask a question for Identity Server v4. 

Is there a way for getting client and scope information from our db in Identity Server 4?

Thanks.

**Comment by leastprivilege** [comment]
Of course. Either implement the corresponding interfaces or have a look at our EF repo.

**Comment by greenskin86** [comment]
No offence, but this answer is informative as hell. On SO it would be hammered. Lacks info about interfaces or even link to a proper place in documentation.

**Comment by brockallen** [comment]
> No offence, but this answer is informative as hell. On SO it would be hammered. Lacks info about interfaces or even link to a proper place in documentation.

That's why this is no SO. The issue tracker is for bug reports, feature requests, etc. not general help.

**Comment by eluchsinger** [comment]
@brockallen Still, a lot of people (like me) find this question on google. I would expect at least a link to the interfaces. Even then, you could take this question as a bug report for your documentation. Apparently it isn't clear enough.
