### ISSUE TITLE
Models.Client.ToEntity() method always returns a Client with Id = 0

### ISSUE THREAD

**Issue by dotcom9** [IdentityServer/IdentityServer4#4314]
The class `IdentityServer4.Models.Client` has no property corresponding to the Id column of the underlying database table. When the `.ToEntity()` method is called to map it back to the table data structure, the Id column is always 0.

Expected behaviour
`IdentityServer4.Models.Client.ToEntity()` should return an object with all properties populated per the underlying data record, particularly the record key.

Actual behaviour
The Id property always has a value of zero.

Steps to reproduce
```     var clientId = "myClient";
        var client = await ClientStore.FindClientByIdAsync(clientId);
        var entity = client.ToEntity();
        Assert.NotEqual(0, entity.Id);
```

**Comment by brockallen** [comment]
Yes, the code would need to fix that up when doing the EF work. Not all storage systems have the same key mechanisms.

**Comment by dotcom9** [comment]
@brockallen which code do you mean? Client application code or IdentityServer4.EntityFramework code? The property does happen to represent the key, but in this context, that's not really important: just that it gets populated.

**Comment by dotcom9** [comment]
In the end, I bypassed this problem by dealing with ConfigurationDbContext directly, but I would have preferred to use your store repository class.

**Comment by brockallen** [comment]
> In the end, I bypassed this problem by dealing with ConfigurationDbContext directly, but I would have preferred to use your store repository class.

Our store is not designed for general DB access. It's meant for use within IdentityServer and its use case. If you want to access the DB for other semantics, then what you've done is the right approach.
