### ISSUE TITLE
How to prevent AuthorizeAttribute from redirecting to login url when using LocalApi?

### ISSUE THREAD

**Issue by ryancole** [IdentityServer/IdentityServer4#4315]
### Question

I'm learning how to use IdentityServer4 and am trying to put both the IdentityServer and the protected API in the same ASP.NET Core project. I see in the documentation [an area that explains how to do this](http://docs.identityserver.io/en/latest/topics/add_apis.html) via the `services.AddLocalApiAuthentication` method. When using this, requests to the protected API controller, which is marked with an `AuthorizeAttribute`, redirect me to a login URL if I fail to provide the required headers.

It's my understanding that `AddLocalApiAuthentication` is a helper and does a few things under the hood, which is where I figure the redirect may be coming from. I tried following the [advanced section](http://docs.identityserver.io/en/latest/topics/add_apis.html#advanced), and used the `services.AddAuthentication().AddLocalApi(...)` method instead of the helper method, but it still causes a redirect.

How can I make it so that those unauthorized requests are just responded to with an 401 Unauthorized response, instead of a redirect?

This is purely an API / IdentityServer web application and therefore has no interactive login URL to redirect to.

### Minimal working example

Below is my `Startup` class. All of the contents here are things I've learned while reading the IdentityServer4 docs - namely the `AllLocalApi`, `AddIdentityServer`, etc.

```csharp
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddControllers();

        services
            .AddAuthentication()
            .AddLocalApi();

        services
            .AddIdentityServer()
            .AddInMemoryApiResources(IdentityServerConfig.Apis)
            .AddInMemoryClients(IdentityServerConfig.Clients)
            .AddDeveloperSigningCredential();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
        app.UseDeveloperExceptionPage();

        app.UseRouting();

        app.UseIdentityServer();

        app.UseAuthorization();

        app.UseEndpoints(ConfigureEndpoints);
    }

    private void ConfigureEndpoints(IEndpointRouteBuilder endpoints)
    {
        endpoints.MapControllers();
    }
}
```

**Comment by leastprivilege** [comment]
Can't repro if I follow the instructions in the docs. 

You can alternatively use our test host and the corresponding client in the samples folder to see if you can repro.

**Comment by ryancole** [comment]
@leastprivilege My code is a progressive accumulation of the docs' overview section and then the adding more API endpoints section (that's where I found the LocalApi related topics). So I don't necessarily have code the reflects 1 exact example from the docs, as the LocalApi docs explain how to configure an existing example, which is what I've tried to do. Unfortunately I don't have a corresponding doc instructions to point you to because of that, but I did upload my super minimal ASP.NET Core project if you have the time to check that for my reproducible example. It's literally just the empty ASP.NET Core VS template project with the bits I added from my readings through the IdentityServer4 docs.

https://github.com/ryancole/identity-server-4-repro

Is that an acceptable reproduction sample? Should just be able to clone it and run, I think. It doesn't have any anything beyond the IdentityServer settings.

**Comment by leastprivilege** [comment]
please use our test host and the corresponding client in the samples folder to see if you can repro.

**Comment by ryancole** [comment]
@leastprivilege Your test host's api server responds with 401 unauthorized as I want. I'm unsure of how your test host api is implemented, but I'm personally trying to host IdentityServer4 and my API in the same ASP.NET Core project, using the `AddLocalApiAuthentication` helper method from IdentityServer4.

I've created a pull request on my repo that I linked above that shows how I can reproduce and demonstrate that adding IdentityServer4 to my ASP.NET Core project causes my unauthorized requests to no longer respond with 401, but instead attempt to redirect to a login url.

My goal is to not have it redirect, but continue to return 401 like your test host api.

Here is a link to the pull request's diff. This diff shows that when I remove IdentityServer4 and just use built in `AddJwtBearer`, I get the 401 responses. With the IdentityServer4 left in place, I get a redirect.

https://github.com/ryancole/identity-server-4-repro/pull/1/files

Any thoughts? Thanks.

**Comment by leastprivilege** [comment]
> If there is a sample showing this use-case then that would likely help me, but I have not been able to find one.

That is exactly the test host I pointed you to.

**Comment by ryancole** [comment]
> > If there is a sample showing this use-case then that would likely help me, but I have not been able to find one.
> 
> 
> 
> That is exactly the test host I pointed you to.

I’ve seen the host api website. Which sample were you pointing me to that shows the local api usage? I looked through the sample projects but guess I’m missing which one has the identity server and api hosted in the same aspnet project? That sample should help me out.

**Comment by ryancole** [comment]
Oh, I see now. The demo website itself hosts all the examples and uses the local api! I understand what you were saying now. I see the usage here: https://github.com/IdentityServer/IdentityServer4.Demo/blob/master/src/IdentityServer4Demo/Startup.cs

Thank you. I will close this.
