### ISSUE TITLE
What does ASP.NET Core Identity provide that I cannot do with bare IdentityServer4?

### ISSUE THREAD

**Issue by ryancole** [IdentityServer/IdentityServer4#4319]
### Question

I'm looking into removing Azure B2C from a project of mine but want to keep my auth work flows the same. Currently, we use B2C to secure our REST API server. We have a mobile app and a React SPA that redirects to B2C for tokens that we then use to access our REST API. I would be needing to implement a self-hosted replacement for B2C, basically.

I see that my options appear to include ASP.NET Core Identity and IdentityServer4. So, I started looking at ASP.NET Core Identity. The documentation for Identity lead me to IdentityServer4, so I have spent the past two days going through the IdentityServer4 overview templates trying to gain an understanding of the moving parts (I'm not an OpenID / OAuth expert).

I'm a bit confused as to what each of these projects provide, though. It seems to me that they have a ton of overlap. For example, the official ASP.NET Core Identity documentation says to use IdentityServer4 if you're trying to secure a REST API. I even see that the official Visual Studio project templates use IdentityServer4 if you choose a Web Api project template and choose to enable single account authentication. But then on the IdentityServer4 documentation, at the end of the overview sections, I see a section explaining how to then integrate IdentityServer4 back into ASP.NET Core Identity. This circular dependency / integration has me a bit confused as to what's doing what with those two projects being used.

So I come here for help with clarifying this ...

If I'm using IdentityServer4, why would I maybe want to use ASP.NET Core Identity? What does Identity provide on top of IdentityServer4?

As a beginner, my mind is just running in circles trying to understand what role each of these projects play and how or why I might use one or both.

Thank you so much for taking a moment to help me out.

**Comment by leastprivilege** [comment]
ASP.NET Identity is an API for database-backed user management - things like create a user, set a password, validate a password etc.

**Comment by ryancole** [comment]
Ah, OK. I see. And IdentityServer4 is strictly for the authentication / authorization portions. This is why the overview docs for IdentityServer4 use those pre-scaffolded user accounts.
