### ISSUE TITLE
Logging in on Chrome 55 when hosting in docker returns to login page

### ISSUE THREAD

**Issue by jeanpoelie** [IdentityServer/IdentityServer4#4320]
We have been using IdentityServer 4 for quite some time.
We are getting several reports from users that try to login but after pressing 'login' the credentials get removed and nothing happens.
I reproduced this issue by opening a chrome 55 (or earlier) browser and trying to login.
What we noticed it that the redirect to the redirect_uri is being ignored and a user will be send the login page instead.

### Issue / Steps to reproduce the problem

Deploy a blank IdentityServer4 to a docker enviroment
Open Chrome 55
Try to login to the identity server, you will be redirected to the login page

**Comment by brockallen** [comment]
Sounds like a samesite cookie to me.
