### ISSUE TITLE
Performance issues with ~650.000 users, crippling at 100% CPU usage.

### ISSUE THREAD

**Issue by MrAdam** [IdentityServer/IdentityServer4#4321]
### Issue / Steps to reproduce the problem

We are trying to use IdentityServer as the authentication provider for our Sitecore-instances.
So far, every time we try to enable authentication through IdentityServer in production, the CPU and memory usage starts climbing after some minutes, and continues until it freezes completely at 100% CPU, while eating a lot of RAM.

We have around 650.000 users in the system, and are using Entity Framework Core for storage.
Looking into the system with a profiler, we see that the slowdown happens inside `EntityFrameworkCore.ChangeTracking`. Then, looking into the SQL Server, we see what I have included in the logs, as the main culprit of the slowdown, a query trying to find all AspNetUserRoles for a specific RoleName - we haven't been able to figure out why this query is being made, and also why it is not AsNonTracking.

We assume that this is something coming from IdentityServer internally, as none of our custom API endpoints in IdentityServer queries for users in specific roles.

### Screenshot of the runtime profiler

![MicrosoftTeams-image](https://user-images.githubusercontent.com/297282/80215273-79edaa80-863c-11ea-9e44-c36194d9359a.png)

### Relevant parts of the log file

```
(@__normalizedRoleName_0 nvarchar(256))SELECT [t].[Id], [t].[ConcurrencyStamp], [t].[Description], [t].[Name], [t].[NormalizedName], [t].[Reserved], [a0].[UserId], [a0].[RoleId]
FROM (
    SELECT TOP(1) [a].[Id], [a].[ConcurrencyStamp], [a].[Description], [a].[Name], [a].[NormalizedName], [a].[Reserved]
    FROM [AspNetRoles] AS [a]
    WHERE [a].[NormalizedName] = @__normalizedRoleName_0
) AS [t]
LEFT JOIN [AspNetUserRoles] AS [a0] ON [t].[Id] = [a0].[RoleId]
ORDER BY [t].[Id], [a0].[UserId], [a0].[RoleId]
```

**Comment by brockallen** [comment]
Can you track down the call stack where this query is being executed?

**Comment by MrAdam** [comment]
Sorry for the slow response, but we believe that the issue is in the library `IdentityExpress.Identity`.

We are using the `IdentityExpressUser` and `IdentityExpressDbContext` from this library, as we are using AdminUI for managing our users. The problem is - we believe - that the `IdentityExpressUser` has the following property: 
```
public ICollection<IdentityExpressUserRole> Roles { get; } = (ICollection<IdentityExpressUserRole>) new List<IdentityExpressUserRole>();
```
This is likely the cause of a stream of "started tracking" statements in the logs, indicating the issue:
```
[DBG] Context '"IdentityExpressDbContext"' started tracking '"IdentityExpressUserRole"' entity.
```
On a test-server where we set up 250.000 users, all with roles, the call to `/connect/token` took 2+ min.

**Comment by rsegecin** [comment]
@MrAdam did you find out what was causing those Role queries?

**Comment by MrAdam** [comment]
Hi @rsegecin. I contacted Rock Solid Knowledge, the developers of AdminUI, as it turned out to be a problem in the IdentityExpress.Identity NuGet package which we used in out IdentityServer setup to make it work with AdminUI.
They promptly solved it, and released [version 3.1.1](https://www.nuget.org/packages/IdentityExpress.Identity/3.1.1) of the package, which solved our problem.

**Comment by rsegecin** [comment]
@MrAdam can you tell how long does it take to call /connect/token now? and in your opinion how does IdentityServer4 performs in your App?

**Comment by MrAdam** [comment]
We haven't gone into production with it yet due to some other stuff taking up our time, so I can't really give any numbers on performance since we updated the package.

**Comment by rsegecin** [comment]
> We haven't gone into production with it yet due to some other stuff taking up our time, so I can't really give any numbers on performance since we updated the package.

Please tell us when you do. Thank you.
