### ISSUE TITLE
Identity4  /Connect/token request is slow.

### ISSUE THREAD

**Issue by mukeshr-sdd** [IdentityServer/IdentityServer4#4327]
I have setup Identity Server 4 with Entity Framework.
 Identity4 Server for method (/connect/token) taking around 12 seconds to load for the first time and then taking around 4-5 seconds after that.

Please suggest on this.

**Comment by brockallen** [comment]
Sorry, it's hard to tell. You will have to do some profiling of your solution.

**Comment by mukeshr-sdd** [comment]
I have tried to a disable the AllowOfflineAccess as it will not generate the refresh token thus reducing  the response time, but it hasn't reduced the time significantly it just made a time difference of 3 seconds.

Please let me know if there is any way to reduce the time significantly.
