### ISSUE TITLE
AddInMemoryApiResources Using IConfiguration

### ISSUE THREAD

**Issue by lopezbertoni** [IdentityServer/IdentityServer4#4328]
Trying to add an in memory api resource using values from the config file. 
Looks like this is always binding to an empty list and not the actual configuration value. 

I followed the sample code in:
https://identityserver4.readthedocs.io/en/latest/reference/api_resource.html#defining-api-resources-in-appsettings-json

The same seems to happen with AddInMemoryApiScopes but I haven't tried it. 

```
        public static IIdentityServerBuilder AddInMemoryApiResources(this IIdentityServerBuilder builder, IConfigurationSection section)
        {
            var resources = new List<ApiResource>();
            section.Bind(resources);

            return builder.AddInMemoryApiResources(resources);
        }
```

I'll be more than glad to help fixing this (if that's the case) or else please point me in the right direction on how to make this work.

Thanks,

https://github.com/IdentityServer/IdentityServer4/blob/bef52b1505f2ca42160a4743cc2e8bf48528f8d1/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/InMemory.cs#L82

**Comment by brockallen** [comment]
Any update before I go look into this?

**Comment by lopezbertoni** [comment]
Hey, thanks for asking. I didn't do anything regarding this since. 
My understanding is that the problem does happen in the code I posted. 
Last time I tried ~1 month ago I didn't get this to work so I posted this.

**Comment by lopezbertoni** [comment]
Haven't tested this since the comments. 
When I did, the configurations where not working when passed from IConfigurationSection.

The code at the time was:

```chsarp
public static IIdentityServerBuilder AddInMemoryApiResources(this IIdentityServerBuilder builder, IConfigurationSection section)
{
    var resources = new List<ApiResource>();
    section.Bind(resources);

    return builder.AddInMemoryApiResources(resources);
}
```
which was setting the Resources to an empty list. Basically the `section` variable was not used.
