### ISSUE TITLE
Exception reading protected message from logoutId and errorId

### ISSUE THREAD

**Issue by RubMertens** [IdentityServer/IdentityServer4#4329]
Hi,
We've recently upgraded IdentityServer from .net core 1 to 2 (IdentityServer 1.0.2 to 2.5.4). Since going to production we've occasionally seen following exception in the logs.

```
Exception reading protected message
```
```
System.Security.Cryptography.CryptographicException: The provided payload cannot be decrypted because it was not protected with this protection provider.    
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)    
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)    
at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)    at IdentityServer4.Stores.ProtectedDataMessageStore`1.ReadAsync(String value)
```

It happens on calls to logout when the logoutId is a simple Guid instead of the expected encrypted token and on call to our /Error endpoint where the errorId is a Guid.

An example of the type of Url that fails: 
```
/gatekeeper/logout?logoutId=477c1810636ca6aecb4c17e013f9889a
```
I would expect this to be some encrypted token starting with `CfD` which is the Magic header if understand correctly. We do see some of those logs (for requests that succeed), for example:

 ```
/gatekeeper/logout?logoutId=CfDJ8FLySel0lLBElhKpk7TfsVfCIUe3LTYv2T1r8f5IDGc3bVyEPnOby67kVt7E7s87tLohX4CN6LSSrWMVWtTSQ-fN7iDB6srgMfsp28BAs_EdYvpuGefmmB_2h0h27gKRVXPcdkIEwXPLFbHGUwjXvK9efkvlp12e2H-pGaWkUWgRA_xisu0vnhi_JyS3XWrI1tPzy5gsECWQCmG8bfqCbeCuHW4gNP9BU9Me9soWo45FhhvfKuZ9fkAFAM-hWOdULBk4l4rkpXZzsxsrdZpE0IKW4FgJskIGLbonMP3vyPIAJU6QWsHJcKutwOY5lzVSmeA0-konspBzf9jN1OsQrkizwQ0EKO41sMtK-H5srdQssBQ4EttWw-gj7K5z7Z542s4mZggGR4oU_yv5MqTtrFzSq--olGocGwAeJ1Jpr331VweTdnjuGx4fcYSpc9JkI8twS1qlebHLYh7qbMXlAMPufOk1s_GBS66YotIt7mpZuz.........
```

One more thing to note. For the request that fail (with the Guid logoutId) we find no endsession call in the logs. We would have expected this to be there but don't fully understand why there is anything in the logoutId at all if it wasn't redirected from the endsession endpoint.
For the logout calls with a proper logoutId, we do see a call to endsession. We can't explain why the endsession call is missing in the failing logout calls.

#### Where could this Guid come from or what place(s) should we be looking into?

We've investigated #1946 . This does not seem to be the cause since we have the correct version of DataProtection persisted in the database.

### Reproduction
Sadly we have not been able to reproduce this locally and don't have a clue where to start looking. We simply see error logs and are trying to find a cause. The code that triggers the exception is:

```csharp
var context = await _interaction.GetLogoutContextAsync(logoutId);
//or
var message = await _interaction.GetErrorContextAsync(errorId);
```

**Comment by brockallen** [comment]
Sounds like a data protection problem in ASP.NET Core.

**Comment by tuananh-le** [comment]
@RubMertens : I'm experiencing the same problem too. Have you found out the root cause of this issue?

**Comment by tuanle07** [comment]
@RubMertens : I'm experiencing the same error as well. Have you found out the root cause of the issue and how to solve it? Thanks.

**Comment by RubMertens** [comment]
Hello @tuanle07 

We have not been able to track down the cause of this exception. 
We've looked further into data protection as brockallen suggested but have only found evidence that when Identityserver's endsession endpoint gets called everything works as expected. The correct data proctection provider is used and we see a correctly formed token in the logoutId.

We're currently working to switch our logging stack to Application Insights to get User Session tracing and hope we find the origin of the faulty logout request that way. 

I hope you have more luck figuring out what the issue is!
