### ISSUE TITLE
What is a proper place for a new persistence implementation?

### ISSUE THREAD

**Issue by DejanMilicic** [IdentityServer/IdentityServer4#4330]
I would like to implement RavenDB persistence for IdentityServer4.  
What would be a proper place and approach to doing it:

1. Fork this repo, working on a feature branch, then create PR
2. Go with "contrib" approach like this one https://github.com/diogodamiani/IdentityServer4.Contrib.MongoDB

**Comment by leastprivilege** [comment]
2. it is.

thanks!
