### ISSUE TITLE
Can we configure IdentityServer 4 in sub application?

### ISSUE THREAD

**Issue by karthickramasamy08** [IdentityServer/IdentityServer4#4331]
I have implemented the Identity server 4 in our application and ensured the working process in localhost. After that, we merged and checking it in our development. It is not working.

We hosted our project as sub-application. So, can you please confirm, is identityServer 4 working in Sub application?

**Comment by dealproc** [comment]
I was able to do so by adding the following line into Startup.cs in the Configure(..) method:

`app.Map("/auth", x => x.UseIdentityServer());`

You'll also need to add the configuration into the services object within ConfigureServices(...):

```CSharp

            services.AddIdentityServer(options => {
                    options.Discovery.ShowIdentityScopes = false;
                    options.Discovery.ShowApiScopes = false;
                    options.Discovery.ShowClaims = false;
                    options.Discovery.ShowExtensionGrantTypes = false;
                })
                .AddDeveloperSigningCredential()
                .AddInMemoryApiResources(Apis);
```
