### ISSUE TITLE
Invalid AllowedCorsOrigins on Clients after upgrade from Identity Server 2.4.0 to 3.1.2

### ISSUE THREAD

**Issue by charlesgardiner** [IdentityServer/IdentityServer4#4332]
### Question

I upgraded from IdentityServer4 2.4.0 to Identity 3.1.2.  One of the clients has an AllowedCorsOrigins value of 
```json
"allowedCorsOrigins": [
        "*"
    ],
```
This client is now invalid.

The intent of this value was to allow all origins.  I think this value was set in error, and did not have the behavior intended.  ( I deduced this from looking at the code. )  I need to work with this team to determine their intended use of this client.

My question is, Is there a way to allow all CorsOrigins through configuration on the client? or would I need to write a custom Cors Policiy?

Thanks for your shared knowledge

**Comment by brockallen** [comment]
"*" was never supported in our default implementation, so I'm not sure why it worked before and why it doesn't work now. sorry.

**Comment by charlesgardiner** [comment]
I appreciate the quick response.  Yes, "*" was an incorrect value.

My question is still, Is there a way to allow all CorsOrigins through configuration on the client? or would I need to write a custom Cors Policiy?

**Comment by brockallen** [comment]
I'm not clear on what's no longer working, meaning the specifics. You mean CORS is not working, or there's some other error? The AllowedCorsOrigins should allow JS clients to use the APIs they need in the IdentityServer endpoints, and it's working (I was just using it yesterday). So I think I need some more info/details.

**Comment by charlesgardiner** [comment]
Perhaps, I've worded the questions poorly.  I appreciate your time.  Thanks.
