### ISSUE TITLE
IS4 under loadbalancer haproxy

### ISSUE THREAD

**Issue by SpeakOutLoud** [IdentityServer/IdentityServer4#4345]
### Question
I am using IS4 under loadbalancer haproxy, while the LB is issuing the ssl to the product and using port 80 to connect to IIS.

Question is, how to read the pfx file from identity server?

**Comment by brockallen** [comment]
> Question is, how to read the pfx file from identity server?

What pfx?

**Comment by maulik-modi** [comment]
@SpeakOutLoud , PFX file contains Private key hence you need to set it in ConfigureServices method of IdentityServer setup.

`var cert = new X509Certificate2(fileName, "Your_PassPhrase" );
        services.AddIdentityServer().AddSigningCredential(cert)`

Once you have done this, you can browse to Discovery Endpoint of IdentityServer that publishes Public Key of the certificate you setup above.

Typical URL of Discovery endpoint looks like this-
https://[Hostname]/.well-known/openid-configuration

All other APIs protected with identityServer will use JWKS setting from Discovery endpoint to validate the token.
