### ISSUE TITLE
Source Link not working

### ISSUE THREAD

**Issue by jmevel** [IdentityServer/IdentityServer4#4346]
Nuget package IdentityServer4 version 3.1.3

I'm migrating a project from .NET Core 2.1 to 3.1 so I performed a database migration (cf: [issue 2845](https://github.com/IdentityServer/IdentityServer4/issues/2845)). However now when I execute this line 

```csharp
return await _identityServerInteractionService.GetAuthorizationContextAsync(returnUrl);
```
I get the following error:

> SqlException: Invalid object name 'IdentityProperties'.
Microsoft.Data.SqlClient.SqlCommand+<>c.<ExecuteDbDataReaderAsync>b__164_0(Task<SqlDataReader> result)

I checked the Identity Server source code and saw in the `.csproj` that the `.PDB` file is included in the Nuget package and the repository URL is included as well. 

I checked the package in my cache under `C:\Users\username\.nuget\packages\identityserver4\3.1.3` just to be sure I see the `.PDB` file and the repository's URL in the `.nuspec` file.

I set the proper options in Visual Studio 2019 (v16.5.4) [as described here](https://stackoverflow.com/a/54980908/1203116) however when I try to step into the `GetAuthorizationContextAsync` method it just doesn't work. 
Visual Studio doesn't ask me if I want to download the source code.

Have you tested this feature already? I'm wondering if I forgot something or if this is just not working anymore.
I've a bit of experience with Source Link and I'm wondering if this is because the `IdentityServer4.dll` inside the Nuget package might be compiled in Release mode?

In my experience, Source Link would work only with Debug compiled DLLs.

Could someone confirm the `IdentityServer4.dll` is a Debug one? Or did I miss something?

I created [another ticket](https://github.com/IdentityServer/IdentityServer4/issues/4347) (Question) for my `IdentityProperties` issue. I'd be really glad if you could answer me about this problem as well.

Thanks for your answers

**Comment by jmevel** [comment]
Could you at least give me an explanation instead of just closing this ticket please?

Thanks

**Comment by leastprivilege** [comment]
Not sure what to say.

**Comment by jmevel** [comment]
Ok thanks for your answer.
So f it works in Rider there's no reason it couldn't work with Visual Studio.

Just out of curiosity, do you compile the DLL in Debug or Release mode?
I've [this stackoverflow question](https://stackoverflow.com/q/55899023/1203116) open, I'm wondering if this is even possible with a Release DLL...

**Comment by leastprivilege** [comment]
you can compile in release mode and produce PDBs.

**Comment by jmevel** [comment]
My PDBs were stored on the Azure DevOps's Symbol Server. 
Maybe Source Link with a release DLL simply doesn't work yet with Visual Studio.
I wouldn't be surprised if Rider was ahead of VS with this technology.

Ok then closing this issue.
Thanks for your answers
