### ISSUE TITLE
Identity server logs out at every 30 min, not able to set idsrv.session cookie lifetime expiration time

### ISSUE THREAD

**Issue by mayankgaur** [IdentityServer/IdentityServer4#4353]
Here is my cookie details, not able to find expiry time of idsrv.session. I have tried to google it but could not be able to find solution. I am using IdentityServer4 and Asp.net core. Here is my package reference
`  <PackageReference Include="IdentityServer4.AspNetIdentity" Version="3.1.0" />
 <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.0" />`

![image](https://user-images.githubusercontent.com/5146368/80810329-39b09e00-8be1-11ea-84c0-aa21e5a126c4.png)

**Comment by mayankgaur** [comment]
I have downloaded the IdentityServer4 from Github Repository and login through the credential:-
Username:bob
Password:bob
but I am always logout from the server every 30 min. May I know where can I exceed the time and reason why it has been logout at particular interval

**Comment by maulik-modi** [comment]
@mayankgaur , Quickstart has [Diagnostics controller ](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/master/Quickstart/Diagnostics/DiagnosticsController.cs), It does show Cookie Expiration time.

See this screenshot:
![image](https://user-images.githubusercontent.com/34910430/81033992-36eccc00-8eb3-11ea-8499-4bddcaf7ef94.png)

@brockallen or @leastprivilege , Please suggest if there is any other way of seeing Cookie expiration time?

**Comment by mayankgaur** [comment]
@maulik-modi as per your observation it says it will expires in 10 hours?

**Comment by maulik-modi** [comment]
@mayankgaur , Cookie expiration time can be easily set with this one liner after adding IdentityServer in ConfigureServices
`services.AddAuthentication("MyCookie")
                .AddCookie("MyCookie", options =>
                {
                    options.ExpireTimeSpan = TimeSpan.FromSeconds(30);                     
                });`

Refer this screenshot showing Expiration time correctly set to **30 Seconds** and **Ticket Expired message** logged in Console logger when I tried to access diagnostics page after 2 minutes of **MyCookie Signed In message**
![5  AuthCookieVerification](https://user-images.githubusercontent.com/34910430/81036437-bcc14500-8ebc-11ea-9fa5-16a6ec7fd127.PNG)

**Comment by mayankgaur** [comment]
> @mayankgaur , Cookie expiration time can be easily set with this one liner after adding IdentityServer in ConfigureServices
> `services.AddAuthentication("MyCookie") .AddCookie("MyCookie", options => { options.ExpireTimeSpan = TimeSpan.FromSeconds(30); });`
> 
> Refer this screenshot showing Expiration time correctly set to **30 Seconds** and **Ticket Expired message** logged in Console logger when I tried to access diagnostics page after 2 minutes of **MyCookie Signed In message**
> ![5 AuthCookieVerification](https://user-images.githubusercontent.com/34910430/81036437-bcc14500-8ebc-11ea-9fa5-16a6ec7fd127.PNG)
> 
> **Packages**
> 
> ```
> <PackageReference Include="IdentityServer4" Version="3.1.3" />
> <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
> ```
> 
> **Project Template**
> `dotnet new is4ui -n IdentityServer`

@maulik-modi its not working
![image](https://user-images.githubusercontent.com/5146368/81037528-addc9180-8ec0-11ea-9b8b-acc5415a36a2.png)
We have already done that
