### ISSUE TITLE
Create NuGet package for Events

### ISSUE THREAD

**Issue by eloekset** [IdentityServer/IdentityServer4#4359]
**Is your feature request related to a problem? Please describe.**
I'm using IdentityServer for a real project and now I'm migrating to .NET Core 3.1 LTS, however as #2189 and #3680 says, it's not possible to use the 3.1.X versions in a class library, since they no longer target .NET Standard 2.X.

**Describe the solution you'd like**
Split the library in several NuGet packages. The one I need is Event, so you'll need at least Model and Event to support my usage.

**Describe alternatives you've considered**
Well, I haven't even considered it, but using IdentityServer, I'll have to stop creating reusable class libraries supporting .NET Standard, which I guess is a showstopper for all real applications.

**Additional context**
![image](https://user-images.githubusercontent.com/791721/80924240-16742300-8d88-11ea-8294-08fbb9ea745a.png)

**Comment by eloekset** [comment]
I just spent one hour doing a quick and dirty refactor without using `git mv` to keep file history. I'm able to build a new IdentityServer4.Core project, which contains the **Models** and **Events** stuff that I need in a .NET Standard 2.1 NuGet package.

I had to move quite a lot more to be able to build. But obviously it *is* possible to do this. If you want me to send a pull request, I can do a better job by using `git mv` instead of just copy and delete files.

I pushed it to a new feature branch on my fork here: https://github.com/eloekset/IdentityServer4/tree/feature/RefactorForNetStandard21NuGetPackage

It is based on your **releases/3.1.x** branch.

![image](https://user-images.githubusercontent.com/791721/80925827-4c6ad480-8d93-11ea-88d3-5c4b1ee0ab11.png)

**IdentityServer4.Core** will have to contain parts of both **IdentityServer4** and **IdentityServer4.Storage**. But I haven't put any thoughts into what to include in the new **IdentityServer4.Core** project besides making it build successfully and include **Models** and **Events**. And I didn't change any of the namespaces, which I guess would just make a lot of unnecessary noise.

**Comment by leastprivilege** [comment]
Hi, 

thanks for doing this research. We are pretty close to releasing v4 and we are not planning to do such fundamental changes for this release.

We will consider this for the release coming after the next. Will leave this issue open to remind us.
