### ISSUE TITLE
Quickstart UI using ASP.NET Core Identity not compliant with IdentityServer4 3.1.3

### ISSUE THREAD

**Issue by sberube** [IdentityServer/IdentityServer4#4362]
When trying to compile Quickstart UI for ASP.NET Core Identity I get compilation errors about `ParsedScopeValue `and `ApiScope `classes doesn't exists in `DeviceController.cs` and `ConsentController.cs`.

Maybe this is related to #4271 

Did anyone found a fix for those errors? Thanks!

**Comment by sberube** [comment]
It seems to work by using the files available in the templates : https://github.com/IdentityServer/IdentityServer4.Templates/tree/master/src/IdentityServer4AspNetIdentity

Maybe the repository [IdentityServer4.Quickstart.UI.AspNetIdentity](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI.AspNetIdentity) need to be removed?

**Comment by leastprivilege** [comment]
The QS repo targets the upcoming v4. This was done by mistake. Using the templates instead works. sorry.
