### ISSUE TITLE
I am setting up Identity Server 4 with MVC client but getting this issue while running in containers. Locally everything is fine.

### ISSUE THREAD

**Issue by nikhilhece2011** [IdentityServer/IdentityServer4#4364]
![image](https://user-images.githubusercontent.com/3807094/81116322-28260980-8ef3-11ea-8ea6-f7a1aa7f2053.png)

I have used IP for http://10.0.75.1 to connect with Identity server 4. Got this IP from eShopOnContainers. Please help.

My docker compose is:- 

![image](https://user-images.githubusercontent.com/3807094/81116700-d5991d00-8ef3-11ea-8d8e-cf24b6ecdd82.png)

Client configuration:- 

![image](https://user-images.githubusercontent.com/3807094/81116798-ff524400-8ef3-11ea-88f1-7fbcdc190b89.png)

**Comment by nikhilhece2011** [comment]
@brockallen  @leastprivilege Any idea, what am I doing wrong here ?

**Comment by 1Jesper1** [comment]
@nikhilhece2011 try adding a slash at the end of authority.
