### ISSUE TITLE
Refresh tokens and auth codes as self-encoded tokens

### ISSUE THREAD

**Issue by jez9999** [IdentityServer/IdentityServer4#4366]
At the moment, IdentityServer requires a persistence store for the operational data of authorization codes and refresh tokens.  However, why can't these be self-encoded / self-contained tokens, similar to signed JWT access tokens?  That way, the server could use the key material used for access tokens to sign them & verify their signature when presented, and the data associated with them (such as expiry date for a refresh token) could be embedded in the token itself, meaning no persistence store is needed.  If this could be done it would be great for removing the overhead of a persistence store.

**Comment by leastprivilege** [comment]
And how would you revoke the refresh token?

**Comment by jez9999** [comment]
This would be for applications where you didn't need to.
