### ISSUE TITLE
How to add a custom implementation (e.g. WsFederation) of IReturnUrlParser if everything is internal set in AuthorizationRequest class in next v4.x ?

### ISSUE THREAD

**Issue by alaincroisetiere** [IdentityServer/IdentityServer4#4368]
### Question
How to add a custom implementation (e.g. WsFederation) of [IReturnUrlParser](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Services/IReturnUrlParser.cs) if everything is internal set in [AuthorizationRequest ](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Models/Messages/AuthorizationRequest.cs) class in next v4.x ?

### Minimal working example
[IdentityServer4.WsFederation/src/IdentityServer4.WsFederation/WsFederation/WsFederationReturnUrlParser.cs](https://github.com/IdentityServer/IdentityServer4.WsFederation/blob/2769d2f9d48cb7fb6f91b67ed3d8a379b28cca97/src/IdentityServer4.WsFederation/WsFederation/WsFederationReturnUrlParser.cs#L48-L73)

```csharp
        public async Task<AuthorizationRequest> ParseAsync(string returnUrl)
        {
            var user = _contextAccessor.HttpContext.User;

            var signInMessage = GetSignInRequestMessage(returnUrl);
            if (signInMessage == null) return null;

            // call validator
            var result = await _signinValidator.ValidateAsync(signInMessage, user);
            if (result.IsError) return null;

            // populate request
            var request = new AuthorizationRequest()
            {
                ClientId = result.Client.ClientId,
                IdP = result.SignInRequestMessage.HomeRealm,
                RedirectUri = result.SignInRequestMessage.Reply
            };

            foreach (var item in result.SignInRequestMessage.Parameters)
            {
                request.Parameters.Add(item.Key, item.Value);
            }

            return request;
        }
```

**Comment by brockallen** [comment]
So yea, looks like we changes them to internal? That was just an oversight. I can make the public again.

**Comment by alaincroisetiere** [comment]
Bug planned into 4.0 milestone.

**Comment by brockallen** [comment]
Fixed. Thx for the heads up!
