### ISSUE TITLE
Not able to run in multiple EC2 instances

### ISSUE THREAD

**Issue by sarkarstanmoy** [IdentityServer/IdentityServer4#4369]
Hi Team,

I am trying to run identity server in AWS EC2 having 2 instances pointing to the same identityserver configuration to db. However, when I am running two instances one is running fine and able to view the login screen but other instances is showing error like "No storage mechanism for grants specified. Use the 'AddInMemoryStores' extension method to register a development version". When I am moving to single instances it is working fine. Any  thoughts?  

private void ConfigureIdentityServer(IServiceCollection services)
        {
            var identityconnectionString = GetParameterStoreValueAsync(ParameterStoreKeyNameForIdentityDb).Result;
       

            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
            var idsrvBuilder = services.AddIdentityServer(options => { options.PublicOrigin = _config["PublicOrigin"]; })
                .AddRedirectUriValidator<RedirectUriValidator>()
                .AddSigningCredential(new X509Certificate2(Path.Combine(".", "certs", "******.pfx"), "****"))
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseMySql(identityconnectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = builder =>
                        builder.UseMySql(identityconnectionString,
                            sql => sql.MigrationsAssembly(migrationsAssembly));
                });
            idsrvBuilder.AddResourceOwnerValidator<ResourceOwnerPasswordValidator>();
            idsrvBuilder.AddProfileService<ProfileService>();
            idsrvBuilder.AddExtensionGrantValidator<LoginAsAdminGrantValidator>();
        }

**Comment by brockallen** [comment]
https://identityserver4.readthedocs.io/en/latest/topics/deployment.html
