### ISSUE TITLE
response_mode type query fails unexpectedly

### ISSUE THREAD

**Issue by sarora2073** [IdentityServer/IdentityServer4#437]
Hi,

I've been experimenting with IdentityServer4 1.0.0-rc2.  Due to conflicts between an existing Angular project that relies on hash tag for routing and the hash fragment response in IdentityServer (#id_token in the url), i've been trying to find a way to make calls to connect/authorize endpoint using response_mode set to 'form_post' or 'query' instead. 

'form_post' implementation gives the expected response, but unfortunately i can't work with the id_token returned as a POST, since this is client side code, which means i'm left only with the 'query' response mode as solution path for this particular angular project, which doesn't work. Debug info follows:

1. Within the /.well-known/openid-configuration, response_mode query is shown as follows:
"response_modes_supported" : ["form_post", "query", "fragment"],

2. Here's a sample failed http request:
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:44342/connect/authorize?response_type=id_token%20token&client_id=singleapp&response_mode=query&scope=dataEventRecords%20openid&nonce=N0.317960979640421471477262357139&state=14772623571390.46208932621804366&redirect_uri=https://localhost:44342/  

3. And here's the debug info showing the failure to authenticate. For some odd reason the logs show '"ResponseMode": "fragment". I'm not setting that anywhere in the server side code, and don't know how to override it. AFAIK from reading the code / docs, i shouldn't have to override it, which is why i'm concerned this is a bug. Help appreciated!

IdentityServer4.Validation.AuthorizeRequestValidator:Error: Invalid response_mode for flow: query
{
  "ClientId": "singleapp",
  "ClientName": "singleapp",
  "RedirectUri": "https://localhost:44342/",
  "AllowedRedirectUris": [
    "https://localhost:44342",
    "https://localhost:44342/",
    "https://localhost:44342/#",
    "https://localhost:44342/#/",
    "https://localhost:44342/#/home"
  ],
  "SubjectId": "1c301a83-c251-431a-add6-1f06422ed9e8",
  "ResponseType": "id_token token",
  **"ResponseMode": "fragment",**
  "GrantType": "implicit",
  "RequestedScopes": "",
  "State": "14772623571390.46208932621804366",
  "Raw": {
    "response_type": "id_token token",
    "client_id": "singleapp",
    **"response_mode": "query",**
    "scope": "dataEventRecords openid",
    "nonce": "N0.317960979640421471477262357139",
    "state": "14772623571390.46208932621804366",
    "redirect_uri": "https://localhost:44342/"
  }
}

**Comment by brockallen** [comment]
tokens are not allowed in query response modes. you must use fragment for client-side JS

**Comment by sarora2073** [comment]
I see. Thanks for the feedback. Given the restrictions of this particular angular 2 project I ended up creating a custom route to handle the inadvertent '#id_token' callback to my angular 2 app and grabbed the token that way...a bit of hack admittedly. 

Point of feedback..hashes have a special place in the web insofar as they uniquely allow for http requests that don't force a browser page reload. I gather that's why a lot of angular projects rely on them (and other SPA apps perhaps?) for routing approach. Accordingly, it may improve adoption if IdentityServer would allow for a callback without a hash symbol for client-side JS. Just a thought.

Again, thanks so much for your help.

**Comment by paulschalkwijk** [comment]
Hi sarora, I have the same problem as you describe in this ticket. Could you please inform me how you solved it? I'm already working on this for hours and this would help me a lot!

**Comment by sarora2073** [comment]
Hi, Sorry this isn't code that I use any more and don't recall anything beyond the general approach of intercepting the request.

**Comment by paulschalkwijk** [comment]
Thanks for you response!


Met vriendelijke groet


Paul Schalkwijk

T +31 348 460096<tel:+31%2088%202384522>　

T +31 6 15097509<tel:+31297745547>

E paul@digiframebv.nl

W www.digiframebv.nl<http://www.digiframebv.nl>


[1506868616686_digiframelogo.png]

Digiframe BV I Maltakade 4 I 3446 BC  Woerden



________________________________
Van: sarora2073 <notifications@github.com>
Verzonden: vrijdag 9 maart 2018 17:06:15
Aan: IdentityServer/IdentityServer4
CC: paul@digiframebv.nl; Comment
Onderwerp: Re: [IdentityServer/IdentityServer4] response_mode type query fails unexpectedly (#437)


Hi, Sorry this isn't code that I use any more and don't recall anything beyond the general approach of intercepting the request.
