### ISSUE TITLE
Extend deployment documentation regarding distributed cache

### ISSUE THREAD

**Issue by M-Wildgruber** [IdentityServer/IdentityServer4#4371]
**Is your feature request related to a problem? Please describe.**
For a considerable amount of time we were trying to scale IdentityServer in a Kubernetes deployment beyond one instance.  
Even though DataProtection API was configured correctly, we were not able to log in using Azure AD B2C. In this case, the message "Unable to unprotect message.State" was written to the log.  So at first we suspected that there still was an error in the configuration of DataProtection API.  
At the end, it turned out that a call to `services.AddOidcStateDataFormatterCache();` was responsible because it registered components that rely on IDistributedCache which used the InMemory implementation. 

**Describe the solution you'd like**
Please add a section to the deployment documentation that states that there are some dependencies on IDistributedCache and list the components that rely on these. 

**Describe alternatives you've considered**
I can provide a pull request for the documentation that you could extend.

**Comment by leastprivilege** [comment]
Yes - feel free to send a PR. Thanks!

**Comment by brockallen** [comment]
merged
