### ISSUE TITLE
Stuck in identity/connect/authorize loop when using IdentityServer4 in subpath with MVC client

### ISSUE THREAD

**Issue by 1Jesper1** [IdentityServer/IdentityServer4#4372]
Hello, I'm hosting IdentityServer4 in subpath "/identity" in the same .NET Core 3.0 project as my client MVC application.
When I login I get stuck in a "identity/connect/authorize" loop. The redirect url is "http://localhost:44300/signin-oidc".

We would like to host IdentityServer4 and the client app in the same application. I got it working by not hosting IdentityServer4 in a subpath. We would like to host IdentityServer4 in subpath, like we did with IdentityServer3.

**Comment by leastprivilege** [comment]
tbh - this is not a scenario we recommend or did test (or even tried out).

**Comment by 1Jesper1** [comment]
@leastprivilege I undestand, we are migration IdentityServer3 to IdentityServer4. We used to work with IdentityServer3 like this: https://identityserver.github.io/Documentation/docsv2/overview/mvcGettingStarted.html

Do you have any suggestions what could cause the problem described above?

**Comment by leastprivilege** [comment]
No. sorry. As I said we never tried that.

**Comment by 1Jesper1** [comment]
It seems to happen when the default route is secured by [Authorize].

Steps:
1. Go to http://localhost:5000/ (Protected Home Index)
2. Navigated to Request URL: http://localhost:5000/identity/connect/authorize?client_id=mvc&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fsignin-oidc 
3. Redirected to http://localhost:5000/signin-oidc
4. http://localhost:5000/
5. Navigated to Request URL: http://localhost:5000/identity/connect/authorize?client_id=mvc&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fsignin-oidc

When we run IdentityServer also on the root, this problem does not seems to happen.
Could ik be a cookie issue?
Is there an action I could execute to debug this problem?

**Comment by lyubomirr** [comment]
@1Jesper1 Did you check if the authentication cookie for your MVC application is set when you execute /signin-oidc? Maybe you need to change the Identity Server cookies path to "/identity" if they are with root path. This may cause some problems.

**Comment by 1Jesper1** [comment]
Hello @lyubomirr You mean like this?
 ``.AddCookie("Cookies", options =>
                {
                    options.Cookie.Path = "/identity";
                })``

**Comment by lyubomirr** [comment]
Is this the MVC authentication cookie? If thats the case it should have "/" path. Identity Server 4 by default adds a default cookie scheme with name "idsrv": 

```
builder.Services.AddAuthentication(IdentityServerConstants.DefaultCookieAuthenticationScheme)
                .AddCookie(IdentityServerConstants.DefaultCookieAuthenticationScheme)
```
So I am thinking that when you go to "/" the default cookie authentication scheme handler is called which is the "idsrv" one and not the "Cookies" one, and if the path of the "idsrv" cookie is set to "/identity" then it is not found and your are redirected to authorize again. If your "idsrv" cookie is set to "/identity" I suggest you to authorize with specific scheme on the root path:
`[Authorize(AuthenticationSchemes = "Cookies")]` .

I may be totally wrong but its worth a check.

**Comment by 1Jesper1** [comment]
@lyubomirr I'm using:
```
var builder = services.AddIdentityServer(options =>
                {
                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;
                    options.UserInteraction.LoginUrl = "/../Account/Login";
                    options.UserInteraction.LogoutUrl = "/../Account/Logout";
                    options.UserInteraction.LogoutUrl = "/../Home/Error";
                })
                .AddInMemoryIdentityResources(Config.Ids)
                .AddInMemoryApiResources(Config.Apis)
                .AddInMemoryClients(Config.Clients)
                .AddAspNetIdentity<ApplicationUser>();

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
    .AddCookie("Cookies")
    .AddOpenIdConnect("oidc", options =>
    {
        options.Authority = "http://localhost:5000" + "/identity";
        options.RequireHttpsMetadata = false;

        options.ClientId = "mvc";
        options.ClientSecret = "secret";
        options.ResponseType = "code";

        options.SaveTokens = true;

        options.Scope.Add("api1");
        options.Scope.Add("offline_access");
    });
```

With: 

```
public void Configure(IApplicationBuilder app)
        {
            if (Environment.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }

            app.UseStaticFiles();

            app.UseRouting();
            app.Map("/identity", app1 =>
            {
                app1.UseIdentityServer();
            });
                app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
            });
        }

```

**Comment by lyubomirr** [comment]
I can't really understand the problem from the configuration. My suggestion is that there is a problem with cookies/authentication schemes so you can check that out.

**Comment by 1Jesper1** [comment]
@lyubomirr Thanks, I will look into this further. Your suggestion to add [Authorize(AuthenticationSchemes = "Cookies")] to the root action adds "/" to the returnUrl at the loginpage.
