### ISSUE TITLE
Override Claims in access token for every silent renew

### ISSUE THREAD

**Issue by muralisambu** [IdentityServer/IdentityServer4#4374]
I'm adding claims from external service when trying to logging to present in access token. I would like to update the claim value for every silent renew. Is overriding the DefaultTokenService is the correct way or do we have any specific class to override? 

Thanks in advance

**Comment by crazyfx1** [comment]
You should implement your own `IProfileService` 

```C#
public async Task GetProfileDataAsync(ProfileDataRequestContext context)
{
    // check for access token
    if (context.Caller == IdentityServerConstants.ProfileDataCallers.ClaimsProviderAccessToken)
    {
        // add custom claims
        context.IssuedClaims.Add(new Claim("mycustomclaim", "newvalue"));
    }
}
```
