### ISSUE TITLE
Client Certificate Authentication

### ISSUE THREAD

**Issue by FDonald** [IdentityServer/IdentityServer4#4375]
### Question
Hi, I am using IdentityServer4 in my organization, and a business requirement is client  certificate  authentication. It seem that with  HTTP/2 protect some path of an application is prohibited.
So, how could I integrate a service certifiacte authentication in IdentityServer4?
This is a discussion link with aspnetcore team [Optional client certificates
 #21193](https://github.com/dotnet/aspnetcore/issues/21193) but i can't figure how to integrate it.

### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by leastprivilege** [comment]
Authenticate users or clients?

**Comment by FDonald** [comment]
@leastprivilege 
Sorry if I explained it wrong, it`s a user certificate authentication for an  IdentityServer4 client.
User certificate authentication is one of our identity providers.
