### ISSUE TITLE
[Feature Request]: Email not confirmed error in Resource Owner grant flow

### ISSUE THREAD

**Issue by shyamal890** [IdentityServer/IdentityServer4#4377]
**Is your feature request related to a problem? Please describe.**

- When utilizing Resource Owner grant credential if the setting in Asp.Net Identity is set to not allow a user without email confirmation, one gets an `invalid_grant` error. The error description says `Invalid username or password`. 

- Now this doesn't give the client enough information if a `Resend Email Verification` prompt should be displayed.  

**Describe the solution you'd like**

- IdentityServer should return a distinguishable error, so that the client can display `Resend Email Verification` prompt. 

**Describe alternatives you've considered**

- I am now aware of any alternatives to this problem.

**Comment by YZahringer** [comment]
You can define your own `ResourceOwnerPasswordValidator` or override the default:
````cs
internal class CustomResourceOwnerPasswordValidator : ResourceOwnerPasswordValidator<User>
{
    private UserManager<User> UserManager { get; }

    public CustomResourceOwnerPasswordValidator(UserManager<User> userManager, SignInManager<User> signInManager,
        ILogger<ResourceOwnerPasswordValidator<User>> logger) : base(userManager, signInManager, logger)
    {
        UserManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
    }

    public override async Task ValidateAsync(ResourceOwnerPasswordValidationContext context)
    {
        await base.ValidateAsync(context);

        if (context.Result.IsError && context.Result.Error == OidcConstants.TokenErrors.InvalidGrant)
        {
            var user = await UserManager.FindByEmailAsync(context.UserName);
            if (user?.EmailConfirmed == false)
            {
                context.Result.CustomResponse ??= new Dictionary<string, object>();
                context.Result.CustomResponse.Add("error_detail", "email_not_confirmed");
            }
        }
    }
}
````
