### ISSUE TITLE
Return back to Identity Server if ADFS User Login fails

### ISSUE THREAD

**Issue by vkalpana09** [IdentityServer/IdentityServer4#4378]
I have the IdentityServer4 connected to ADFS and im able to login with right user credentials. I have enabled IWA and i have a secanrio like if the User clicks cancel it should return back to Identity Server application. As of now if i click cancel it just shows me 401 error page with ADFS URL. 

![image](https://user-images.githubusercontent.com/60258761/81474532-aea85700-9223-11ea-98ea-cee762f5f31b.png)

```csharp

 services.AddAuthentication().AddOpenIdConnect("adfs", "ADFS Authentication", options =>
 {
      options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
      options.SignOutScheme = IdentityServerConstants.SignoutScheme;
      options.Authority = "ADFS URL";
      ptions.ClientId = "Client  Id";
      options.ResponseType = "code";
      options.CallbackPath = "/signin-adfs";
      options.SignedOutCallbackPath = "/signout-callback-adfs";
      options.RemoteSignOutPath = "/signout-adfs";
      options.RequireHttpsMetadata = true;
      options.BackchannelHttpHandler = GetHandler();      
       options.ClientSecret = "Client Secret";
       options.SaveTokens = true;
       options.TokenValidationParameters = new TokenValidationParameters
       {
             NameClaimType = "name",
             RoleClaimType = "role"
         };
         options.GetClaimsFromUserInfoEndpoint = true;
 });

**Comment by vkalpana09** [comment]
I am still waiting for inputs. Please suggest.

**Comment by lazycoder07** [comment]
I had similar problem with Azure using openId. We handled it using events,

` options.Events = new OpenIdConnectEvents
                            {
                                OnRemoteFailure = ctx =>
                                {
                                    switch (ctx.Failure.Message)
                                    {
                                        case string error when error.Contains("Error message which is received"):
                                            ctx.HandleResponse();
                                            ctx.Response.Redirect("your page")
                                   }
                              }
                        };`

**Comment by vkalpana09** [comment]
Thanks for the reply. I will check this. So this u have written in startup class.
