### ISSUE TITLE
RequireSignOutPrompt on Client is Missing

### ISSUE THREAD

**Issue by DerAlbertCom** [IdentityServer/IdentityServer4#438]
Hi,

the documentation document a RequireSignOutPrompt on the ClientModel https://identityserver4.readthedocs.io/en/dev/reference/client.html

But this does not exists

https://github.com/IdentityServer/IdentityServer4/search?utf8=%E2%9C%93&q=RequireSignOutPrompt

**Comment by leastprivilege** [comment]
fixed in docs
