### ISSUE TITLE
Missing scope

### ISSUE THREAD

**Issue by GioviQ** [IdentityServer/IdentityServer4#4383]
Maybe I am missing something, I have just cloned the repository to debug and after sending this PR for the doc https://github.com/IdentityServer/IdentityServer4/pull/4382
I cannot make working my IdentityServer setup.
In https://github.com/IdentityServer/IdentityServer4/blob/master/src/EntityFramework.Storage/src/Stores/ResourceStore.cs#L146
no scope is found.
I have ApiScopes table empty. Only ApiResourcesScopes has one row.

In samples / demo projects I don't remember to see manually init ApiScopes.

My config before adding scopes inside ApiResource https://github.com/enkodellc/blazorboilerplate/blob/development/src/Server/BlazorBoilerplate.Storage/IdentityServerConfig.cs

**Comment by leastprivilege** [comment]
Thanks. see my other reply.
