### ISSUE TITLE
Should DefaultSignOutScheme be set?

### ISSUE THREAD

**Issue by AndersAbel** [IdentityServer/IdentityServer4#4384]
The quickstart UI contains this line in the logout method:

````
// delete local authentication cookie
await HttpContext.SignOutAsync();
````

It looks like the intention is to terminate the local session ("Identity.Application" scheme when using Asp.Net Identity). But what it does is to first look at `DefaultSignOutScheme` which is null. It then fall backs to the `DefaultSignInScheme` which is the external authentication cookie. Is this really the intention? Or should the `DefaultSignOutScheme` be set to the same value as `DefaultAuthenticateScheme` so that the session is terminated?

Now, the logout typically works anyway. I think that it is due to the end session endpoint that is invoked in the iframe on the logged out page.

**Comment by Angelinsky7** [comment]
As version 4.0.4 this way of loging out (from id4 himself without any client) doesn't work for me (using the sample quickstart ui).
The cookie is still valid and if you refresh the id4 login page, you're still logged in as the user.

**Comment by brockallen** [comment]
For ASP.NET Identity, wouldn't you use the SignInManager's SignOut instead?

**Comment by AndersAbel** [comment]
@brockallen Yes, that would make more sense for Asp.Net Identity. So this is probably not relevant then. I think I ended up in this situation when I added Asp.Net Identity to a project after I already had started with a non Asp.NetIdentity quickstart-UI.

**Comment by brockallen** [comment]
Yea, I think that'd be the recommended approach. Thx :)
