### ISSUE TITLE
Securing anonymous calls from SPA ?

### ISSUE THREAD

**Issue by GreyKarnival** [IdentityServer/IdentityServer4#4388]
Hello, 

I'm in a case where I want to make sure the calls made to my API comes from my SPA, even in cases where the user is not authenticated.
The idea being that even if the pages are available to everybody I don't want to have the Web Api completely open bar, and I thought that maybe the identityserver would be a good fit to do that.
However as I was looking it seems nobody has done it yet, do you guys have any article on the subject of securing an SPA this way ? Any alternative ? Or some lead on how to go at it with the identityserver4 ?
I was thinking of something along the lines of authorization code flow that would generate an token without any username//password, but still enforce that the token is passed through a redirect only to the allowed url.

Thanks in advance,
Karny

**Comment by an2ny** [comment]
@GreyKarnival i think this is client credentials. look at the this page -> https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html

btw, we are both planning to do the same thing. i have an app that i wanted to make sure is the only one communicating to my api even though users are not logged in and then some parts of the api are only accessible to logged in users. been having hard time integrating spa + asp identity + identity server (persisted grants) smoothly and i'm going back and forth as errors shows up everywhere and so little references (not beginner friendly imo) 😄 

this is a work in progress for me though. will try to post here what i did for the sake of giving info if needed.

**Comment by GreyKarnival** [comment]
@an2ny From what I get Client Credentials is more for securing APIs for back-end calls, so for example a classic .net core MVC calling a Web Api, in which case the ClientId and the ClientSecret would not be completely exposed to the outside world as it would in the case of an SPA where, with more or less effort depending on how hard you try to hide it, everything is visible to the outside world. 

I feel like what we are trying to do cannot be that rare and yet I don't really find much on the subject, if anything at all. So maybe I'm looking at it wrong, hence my post here.

Hang in there, security is worth spending time learning :)

**Comment by an2ny** [comment]
@GreyKarnival you are right. but client_credentials is the only choice for now or at least what i thought is the choice 😄 so i need to skip this for now as it is taking me a bit longer without even progressing at other parts of the project. but hey, look at this [youtube video](https://www.youtube.com/watch?v=eF2myGRT8bo). it might us (will watch the video later). you are right security is worth spending time but sometimes boring/ignored, that's why most apps are not even secure 😄
