### ISSUE TITLE
GetOrigin() string extension

### ISSUE THREAD

**Issue by code-bio** [IdentityServer/IdentityServer4#439]
Hi,

I'm playing around with the InMemory Setup for IS4 and using the Postman ChromeApp to evaluate the different scenarios. Unfortuantely Postman seems to be restricted to the CORS Policy of Chrome and the IS4 gets "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop" as the origin header. I added the "fhbjgbiflinjbdggehcddcbncdddomop" string as allowed origin in the InMemoryClient Settings, but the CorsPolicy implementation of the InMemoryClient is using the string extension GetOrigin() to check the allowed cors origins and only accepts http or https protocols. Doesn't it make sense to ignore the protocol in this scenario at all?

Many thanks for your work. IS4 is really a great product!

**Comment by brockallen** [comment]
Does Postman really honor the same origin policy? Isn't it really just a native app? I guess I'm confused since it's all about making HTTP requests in the browser to arbitrary web sites...

**Comment by code-bio** [comment]
I just checked it again. It seems that the version of postman (chrome app), which I am using, is going to retire. You are right! There is a new standalone app of postman without this origin issue. That solves my problem. Thank you for your support!

In spite of this, shouldn't the GetOrigin() extension ignore the protocol? Maybe the old Postman chrome app is not the only affected client.

**Comment by brockallen** [comment]
> In spite of this, shouldn't the GetOrigin() extension ignore the protocol

Not so sure -- the only context in which same-origin policy & CORS makes sense is a browser and Ajax calls, which should all be under http/s.
