### ISSUE TITLE
connect/endsession 404

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#44]
I want to implement the logout and a post_logout_redirect_uri for an angular client, Implicit Flow. 

I'm following the docs here:
https://identityserver.github.io/Documentation/docs/endpoints/endSession.html

I keep getting a 404, Is it possible that this does not work yet in IdentityServer4?

Greetings Damien

**Comment by leastprivilege** [comment]
yes - this is not done yet.

**Comment by damienbod** [comment]
OK thanks, and will it work with the jti property from the token?

**Comment by leastprivilege** [comment]
?

**Comment by damienbod** [comment]
Client Config on server:
 IncludeJwtId= true,
 
 I use response_type = "token".
 
 Then I would like to logout like this:
 ```
 // /connect/endsession?id_token_hint={jti property from token}&post_logout_redirect_uri=https://localhost:44347/unauthorized.html
        var Logoff = function () {
            var token = localStorageService.get("authorizationData");
            var data = getDataFromToken(token);

            var authorizationUrl = 'https://localhost:44345/connect/endsession';
            var id_token_hint = data.jti;
            var post_logout_redirect_uri = 'https://localhost:44347/unauthorized.html';
            var state = Date.now() + "" + Math.random();

            var url =
                authorizationUrl + "?" +
                "id_token_hint=" + id_token_hint + "&" +
                "post_logout_redirect_uri=" + encodeURI(post_logout_redirect_uri) + "&" +
                "state=" + encodeURI(state);

            ResetAuthorizationData();
            $window.location = url;
        }
 ```
 
 Possible?
 
 Thanks Damien

**Comment by leastprivilege** [comment]
it is not implemented yet - don't try to work around that ;)

Jti is not meant for logout.

**Comment by leastprivilege** [comment]
We'll have an update to idsrv4 once rc2 is released.

**Comment by damienbod** [comment]
When it is implemented, sometime after RC2 release, how will logout be supported when using response_type="token" then?

Greetings Damien

**Comment by leastprivilege** [comment]
since token on its own would be OAuth 2.0 and not OpenID Connect - there is no logout.

**Comment by damienbod** [comment]
Why do you support response_type="token"  if you cannot logout then?

**Comment by leastprivilege** [comment]
logout is part of the openid connect spec. OAuth 2.0 on its own is not an authentication protocol (hence no logout).

You can still logout of identityserver of course.

I can see that this is confusing ;)

**Comment by damienbod** [comment]
Well you always said we should use OpenId connect. Have to re-implement now... It's not so easy to implement "id_token token" in javascript.

Thanks Damien

**Comment by brockallen** [comment]
JS is not that bad -- you can look into the oidc-client/oidc-token-manager, or just use the idtoken validation endpoint:

https://identityserver.github.io/Documentation/docsv2/endpoints/identityTokenValidation.html

**Comment by brockallen** [comment]
Also, here's a link to a relevant video: https://vimeo.com/131636653

**Comment by damienbod** [comment]
Thanks, got it working, was missing the openId scope in the request. Thanks for the link, I look forward to watching it.

Greetings Damien

**Comment by theDiverDK** [comment]
Hi there

Any idea about the ETA of RC2?

Looking forward to be able to use the Session logout feature.

**Comment by leastprivilege** [comment]
No 

https://github.com/aspnet/Home/wiki/Roadmap

**Comment by ericgreenmix** [comment]
Any work happening on this guys?

**Comment by nielslbeck** [comment]
Looking forward to a solution on this one :-)
