### ISSUE TITLE
DefaultClaimsService Filters out protocol claims like exp, amr, nonce...

### ISSUE THREAD

**Issue by Rinsen** [IdentityServer/IdentityServer4#4417]
### Question
What is the reasoning behind filtering out Protocol claims in the DefaultClaimsService?
https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Services/Default/DefaultClaimsService.cs

"Filters out protocol claims like amr, nonce etc.."

If I need to have access to for example expiration claim in a client application do I need to add this into my own claim type instead of using the stadard "exp" claim in the identity token? This feels strange when I read the OpenId documentation below on what thet call "Reserved Claim Names".

"None of the claims defined in the table below are intended to be mandatory, but rather, provide a starting point for a set of useful, interoperable claims."
https://openid.net/specs/draft-jones-json-web-token-07.html

But I'm quite new to OpenId and cant find any documentation around this.

**Comment by brockallen** [comment]
We filter those returned from a custom profile service so erroneous claims don't conflict with those maintained/issued/controlled by IdentityServer and would incorrectly influence the resultant tokens.
