### ISSUE TITLE
Cookies idsrv.session in different domain

### ISSUE THREAD

**Issue by IwanSumpena** [IdentityServer/IdentityServer4#4418]
I run the identity server with the client. Login is successful as usual and every tab has the same cookies with the same value (idsrv.session).

When the identity server and client are running from 2 different machines and different domains idsrv.session cookies are not formed in the client tab. Is it really like that?

**Comment by maulik-modi** [comment]
@IwanSumpena , Yes, By default browser shows cookie of current domain.
myclientapp.com -> shows cookie issued form myclientapp.com
identity.com -> shows cookie issued form identity.com

**Comment by IwanSumpena** [comment]
@maulik-modi  Tanks
