### ISSUE TITLE
Redirect back to reditect_uri provided by client on Authorize error instead of error page

### ISSUE THREAD

**Issue by nzhuravel** [IdentityServer/IdentityServer4#4420]
**Is your feature request related to a problem? Please describe.**

We use Identity server to do authorization for SPA.
If you provide a clientID which is invalid, you are redirected to an error page which is part of Identity Server app (in our case it's Home/AuthError).
(host)/connect/authorize?client_id=**our_client_id**&redirect_uri=our_redirect_uri&response_type=code&scope=openid%20profile%20user_api.full_access&state=our_state&code_challenge=our_code_challenge&code_challenge_method=S256&response_mode=query

We have a requirement to redirect back to redirect_uri with whatever error code we get and let SPA app decide what is wrong and what to do next per OpenID spec
https://openid.net/specs/openid-connect-core-1_0.html#AuthError

Per source code of Identity Server 4, I see that some errors are considered safe, some are not
https://github.com/IdentityServer/IdentityServer4/blob/e40e566f1b546925175fa7f955de7752a44f9497/src/IdentityServer4/src/Endpoints/Results/AuthorizeResult.cs#L72

Is it possible somehow to override safe/unsafe error cases processing and be able to redirect back to client as OpenID spec states? Were there any reasons it was not made customizable? 

**Describe the solution you'd like**
Make Authorize endpoint error processing customizable

**Describe alternatives you've considered**
Currently we've added a hack by replacing IAuthorizeRequestValidator with our own version, which decorates this one
https://github.com/IdentityServer/IdentityServer4/blob/e40e566f1b546925175fa7f955de7752a44f9497/src/IdentityServer4/src/Validation/Default/AuthorizeRequestValidator.cs
and sets AuthorizeRequestValidationResult.ValidatedAuthorizeRequest.ResponseMode to the one from Authorize request query string. This way internally AuthorizeResult class is able to build correct Redirect_uri with proper error code (https://github.com/IdentityServer/IdentityServer4/blob/e40e566f1b546925175fa7f955de7752a44f9497/src/IdentityServer4/src/Endpoints/Results/AuthorizeResult.cs#L107). 
And we are redirected to error Page (Home/AuthError) from where we redirect to Redirect_uri provided by client SPA
```
public async Task<IActionResult> AuthError(string errorId)
        {
            // retrieve error details from identityserver
            ErrorMessage message = await _interaction.GetErrorContextAsync(errorId);
            if (message != null && message.RedirectUri != null)
            {
                return Redirect(message.RedirectUri);
            }
            else
            {
                return View("Error", new ErrorViewModel() { Error = message });
            }
        }
```
This hack looks ugly because most of functionality in IdentityServer4 has internal modificators (for example 
https://github.com/IdentityServer/IdentityServer4/blob/e40e566f1b546925175fa7f955de7752a44f9497/src/IdentityServer4/src/Constants.cs)
So to properly map ResponseMode from query string ResponseType I had to copy some constants into our code base which leads to random results when we update version of IdentityServer in the future.

**Additional context**

**Comment by brockallen** [comment]
> We have a requirement to redirect back to redirect_uri with whatever error code we get and let SPA app decide what is wrong and what to do next per OpenID spec

Sure, but there's an attack so out implementation follows the guidance from here:

https://tools.ietf.org/html/draft-bradley-oauth-open-redirector-00

**Comment by nzhuravel** [comment]
Thanks for the spec ref. 
According to it redirecting back to SPA can be vulnerable if attacker can register his own client dynamically. If he can't then all described cases are not the case, am I right? 

I made that conclusion because you already add "#_=_" fragment to redirect uri and thus there will be no data leak from previous uri params, and in case of error you provide only errorId+errorDesc+state. Is 'state' considered as sensitive info?

**Comment by poveilleux** [comment]
I'd like to follow up on that. For requests made to the authorize endpoint with an invalid `redirect_uri`, I agree this should not work. On the other hand, if the `redirect_uri` is allowed by the client and the Authorization Server does not have public client registrations possible, I think it should be possible to change the way errors are handled to return them to the client application.
