### ISSUE TITLE
AuthenticationOptions.EnableLocalLogin alternatives for IdentityServer4

### ISSUE THREAD

**Issue by osagga** [IdentityServer/IdentityServer4#4422]
### Question
Hello, not sure if this is the right place for this, but I was wondering about any alternatives for the [`AuthenticationOptions.EnableLocalLogin`](https://identityserver.github.io/Documentation/docsv2/configuration/authenticationOptions.html) option (from `IdentityServer3`) in `IdentityServer4`? 

I basically want my register/login page to only show the external providers option, and disable the local login (email/password based). Is that possible anymore?

Related issue https://github.com/IdentityServer/IdentityServer4/issues/227 (@leastprivilege is there any documentation as to how to still acheive the same behaviour in `IdentityServer4`?)

Related StackOverFlow question: https://stackoverflow.com/questions/46387172/external-login-only-no-local-users-is-this-a-supported-option-in-identityserv

I've noticed that in the code, its possible to hide the the local login, like here:
https://github.com/IdentityServer/IdentityServer4/blob/42a6907d0d3ffb3862ec2e3a942595cd0d9d2f7d/src/IdentityServer4/host/Views/Account/Login.cshtml#L12

But its not really clear on how can I control that value from the server side, specially if I don't have access to the default controller that handles the `Identity/Account/Register` endpoint on the server side.

**Comment by brockallen** [comment]
Have you seen this setting?

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/host/Quickstart/Account/AccountOptions.cs#L11

**Comment by osagga** [comment]
@brockallen that worked, thanks!
