### ISSUE TITLE
Changing AccessTokenJwtType

### ISSUE THREAD

**Issue by MrSmoke** [IdentityServer/IdentityServer4#4424]
### Question
After upgrading to the latest identityserver, I set the `AccessTokenJwtType` setting back to `JWT` as to not break some older clients as be more of a drop in replacement. I now plan on changing the type back to `jwt+at`, however the introspection endpoint does not accept `JWT` token types when I change `AccessTokenJwtType` back to `jwt+at`.

What would be a migration plan to cut over to the new token type? I assumed there would be something similar to `UnprotectKeysWithAnyCertificate`/`ProtectKeysWithCertificate` but it doesn't seem so.

Thanks

**Comment by leastprivilege** [comment]
That sounds like a bug. I will have a look.

**Comment by MrSmoke** [comment]
Ah ok. I wasn't sure if it was me doing something wrong or if it was by design since it looks like the source is just doing a plain equality check. This is where its failing for me

https://github.com/IdentityServer/IdentityServer4/blob/5a50edfb0e96472922fc6a2ce57d8bd89533553e/src/IdentityServer4/src/Validation/Default/TokenValidator.cs#L280

**Comment by leastprivilege** [comment]
Ah OK - oh well - I guess we did not build any "rollout" features into the code.

It's a hard switch. sorry.
