### ISSUE TITLE
[Question] Refresh tokens for a JS client

### ISSUE THREAD

**Issue by plioi** [IdentityServer/IdentityServer4#443]
I have a JS Client successfully interacting with Identity Server 4 for logging in and out, and this is based on the [Adding a JavaScript client](https://identityserver4.readthedocs.io/en/dev/quickstarts/7_javascript_client.html) quickstart.

I'm using the suggested oidc-client javascript library.

My JS Client, naturally, needs to make API calls against a second Client (a typical web API project). Beyond what the quickstart suggests, what does it take to ensure that a user's interactions with the site will properly take part in refresh tokens?

**Comment by leastprivilege** [comment]
Refresh tokens are not supported for implicit clients. check the spec.

**Comment by plioi** [comment]
Oh, so are all javascript clients inherently using the implicit flow?  Are refresh tokens only applicable then, for other long-connected clients like phone apps?

**Comment by leastprivilege** [comment]
yes
