### ISSUE TITLE
Custom Check Session Endpoint

### ISSUE THREAD

**Issue by lazycoder07** [IdentityServer/IdentityServer4#4433]
Hello,
Is there possibility to extend check session endpoint?
I want to return additional tokens along with existing ones from check session endpoint.

**Comment by Roach6996** [comment]
I am also looking for possibility to extend check session endpoint. If it's not available can it be added as new feature in next release?

**Comment by lyubomirr** [comment]
You can implement your own `IEndpointHandler ` add register it in the IdentityServiceBuilder with the `AddEndpoint ` method with the correct path to the check session endpoint like done [here](https://github.com/IdentityServer/IdentityServer4/blob/8d8cce5c1963bc5ed4deac7fed9ecfe04808897b/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Core.cs#L81). 

Unfortunately, the endpoint implementations are internal and you cannot extend them directly.
