### ISSUE TITLE
Where is the refresh_token grant type defined? I'm trying to give a client access to it.

### ISSUE THREAD

**Issue by ryancole** [IdentityServer/IdentityServer4#4440]
I'm trying to allow a client access to refresh tokens. I've given the client the "allow offline access" scope, and I can see a refresh token being provided. I'm now trying to use the refresh token, but am getting an invalid grant type error.

Looking through the docs, I see the refrest_token grant mentioned in various places, such as [here](https://identityserver4.readthedocs.io/en/latest/topics/extension_grants.html#extension-grants), but I don't see that token available in the code under the [GrantType](https://github.com/IdentityServer/IdentityServer4/blob/master/src/Storage/src/Models/GrantType.cs) class.

Would I just need to manually specify that grant, like below ...

```
Client.AllowedGrantTypes =
{
    GrantType.Code,
    GrantType.ClientCredentials,
    "refresh_token"
};
```

Or is there some other way that I am supposed to add this grant? Thanks!

**Comment by GWJYonder** [comment]
Make sure your Client is set to AllowOfflineAccess, and then when you request your tokens add "offline_access" as a scope.

**Comment by ryancole** [comment]
Oh, ok, I see. So you don't have to explicitly enable the grant type - it comes with that flag. Thanks,
