### ISSUE TITLE
After upgrading to latest pre-release am getting invalid_scope

### ISSUE THREAD

**Issue by klanglie** [IdentityServer/IdentityServer4#4441]
After upgrading to latest pre-release I am getting an invalid_scope error. Any ideas. I am referencing the source code directly.

It looks like it has something to do with ResourceValidator. The scopes passed along from my UI were not found in either FindIdentityResourcesByScope or FindApiScope. Why is it not also searching ApiResources?

Something feels a little disconnected. Perhaps I am seeding the tables wrong? I am using same seed data as before. I am not sure what the difference between IdentityResources / ApiScopes and ApiResources are. Ideally this solution would lso be multi-tenant.

Another thing I came across is duplicate lines of code. SEE: ApiResourceMapperProfile Lns 27 + 29.

**Comment by leastprivilege** [comment]
We changed the config model slightly. Docs are not written yet.

Check our test host to see how it works.

**Comment by GioviQ** [comment]
@leastprivilege Is it https://github.com/IdentityServer/IdentityServer4/tree/master/src/IdentityServer4/host ?

**Comment by leastprivilege** [comment]
Yes

https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/host/Configuration/Resources.cs

**Comment by klanglie** [comment]
Ok, looks like I need to modify my config by adding ApiScopes. I am guessing the reason for that reading the comments is to better implement the OAuth spec. I don't like duplication and lack of constraints so much. But if my UI deletes a token from ApiScopes I can find the same ones that are in any of the ApiResources.Scopes and delete them. Conversely, if I add a scope in my UI to ApiResources and it doesn't already exist in ApiScopes, I can add it there too.

OLD Way

            new ApiResource("myAPI", "Scope for My API")
                {
                    ApiSecrets =
                    {
                        new Secret("GUID".Sha256())
                    },
                    Scopes = 
                    { 
                        "myAPI",
                        "myAPI.user",
                        "myAPI.admin"
                    }
                },

**Comment by vietlp** [comment]
[https://github.com/IdentityServer/IdentityServer4/issues/4549#issuecomment-647676504](url)
