### ISSUE TITLE
IdentityServer & third-party cookie blockers

### ISSUE THREAD

**Issue by danielbecroft** [IdentityServer/IdentityServer4#4447]
We're having some issues using IdentityServer when the browser is blocking third-party cookies.

Our setup is as follows:
- IdentityServer4 running in a .NET Core app (auth.domain.com)
- Our app is an SPA Angular app, running in (app-ui.domain.com), fronting an API (running app-api.domain.com)

All sites are running under HTTPS.

We've recently switched from using OAuth2+refresh_token to the Implicit flow for authentication in our Angular code. This is using the `silent_renew.html` approach as outlined here[1].

In browsers where third-party cookies are allowed by default, everything is working fine. When we have third-party cookies blocked in the browser (which is by default in the Brave browser), the silent-renew.html is failing. The silent renew process works by running inside an `<iframe/>`.

On a working request, I can see that there are two cookies being sent during the `/connect/authorize` call: `idsrv.session` and `.AspNetCore.Identity.Application`, and these are the cookies that are getting blocked as "third-party" cookies.

These cookies are coming through as SameSite=None, and I've tried setting these as SameSite=Lax, based on the issues[2,3], but it still doesn't work.

Short of not blocking third-party cookies (which Google et al are going to start enforcing soon), how do we get the IdentityServer cookies being sent in a silent renew operation?

[1] - https://lalitacode.com/implement-openid-connect-code-flow-with-pkce-in-angular/
[2] - https://stackoverflow.com/questions/60611137/net-core-2-2-with-identity-server-4-samesite-cookie-changes-issue
[3] - https://github.com/IdentityServer/IdentityServer4/issues/4110

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2020/03/31/spas-are-dead/

**Comment by danielbecroft** [comment]
Thanks @leastprivilege . That article is very interesting, and also very scary.

From what I can see, the Angular app will need to be structured completely differently, as it will need a runnable backend, not just a static file server. (Our plan was to eventually host the static Angular files from a CDN, but if we need a back-end for this on the same domain, that could be a problem).

I think we have two options:

1. Combine the Angular and API applications to a single .NET Core project, using something like the .NET Core Angular SPA template. Kestrel serves both the API and the static files, and the routes all work on the same domain. We would need to handle both cookie and JWT based authentication schemes (as the API is available externally from the app); or

1. Do (1), but instead of the API as the backend, add a new .NET Core application. This app is purely responsible for authentication against the identity server, and proxying through to the API. THe downside is we now need to handle a scalable and secure method of storing the `access_token` values received from the IdentityServer. These should live in the session state, so we would need to bring a distributed store like Redis or similar.

I had a look at the example BFF on your repo, @leastprivilege, referenced from your [blog article](https://leastprivilege.com/2019/01/18/an-alternative-way-to-secure-spas-with-asp-net-core-openid-connect-oauth-2-0-and-proxykit/), which indicates a solution like (2), and I can start to see how this would work.

I can see that the practice of serving authenticated SPAs on static storage (S3, Azure BLOB, CDNs, etc) will start to become obselete as apps get rearchitected.

**Comment by leastprivilege** [comment]
It's a combination of 1) and 2)

Use 1) for all the front-end exclusive APIs. Use anti-forgery protected cookies to secure front/backend communication (e.g. using same-site).

2) Put the shared APIs in a separate API project and secure with JWTs.

**Comment by danielbecroft** [comment]
Great, thanks for your assistance @leastprivilege .
