### ISSUE TITLE
Access token validation endpoint

### ISSUE THREAD

**Issue by juanan** [IdentityServer/IdentityServer4#4449]
### Question
I have a web application (.Net Framework 4.7.2) where I want to validate the JWT access token got from my identity server 4.

My question is if there is any endpoint like in the past with IS3 (connect/accesstokenvalidation) or any other of your libraries (i.e. IdentityModel) to do that.

Introspection is not the desired way since the SPA should know the api secret due to the instrospection endpoint needs it for Basic authorization.

I'm not using Owin so startup class is not a solution, just some endpoint or something like that to call in my SPA flow.

Many thanks.

**Comment by leastprivilege** [comment]
Access tokens are validated at APIs - not clients. I don't follow.

**Comment by juanan** [comment]
I just wanted to validate an access token in the client trying to avoid set in the client info like apiSecret.

I was asking if you have any library for that and I found that IdentityModel has GetDiscoveryDocumentAsync so with that I can validate the token.

Thanks.
