### ISSUE TITLE
Needs a proper Error Codes returned by the discovery client in case of any Error occurred in the identity server.

### ISSUE THREAD

**Issue by humzatufail47** [IdentityServer/IdentityServer4#4450]
**Is your feature request related to a problem? Please describe.**
yes, sometimes we need to modify the error messages returned by the Discover client, and at that time in identityServer4. we don't have any way to check that what kind of error is returned by the IdentityServer and how we can modify this error message. Identity server returns invalid_grantType in case of even wrong email/password and invalid_username_and_password, we don't have any way to modify this.

**Describe the solution you'd like**
I think the identity server should return the "ErrorCodes" in the cause of the error that occurred on the side of indetityServer. like 1004 describe the "invalid email",4005 describe the "This error occurs when invalid credentials are provided". on the API side then we can customize our end-user error messages based on these error codes.

**Describe alternatives you've considered**
what did I do? simply throw the exception with "Invalid email or password". this is not the proper way to return the hard code error message.

**Comment by adeen-waheed-confiz** [comment]
Yes, that a nice feature request. Developers should be able to customize error messages in identity servers as per the project requirements.

**Comment by leastprivilege** [comment]
Detailed error message are a security concern. IdentityServer implements the error codes as specified in the OAuth 2.0 / OpenID Connect family of specifications.
