### ISSUE TITLE
unsupported_grant_type when using password grant?

### ISSUE THREAD

**Issue by ketchums** [IdentityServer/IdentityServer4#4455]
So I'm trying to implement bearer tokens to my API, when going to the connect/token endpoint I am greeted with unsupported_grant_type

Checked database, client is set to use 'password' grant type but it says unsupported?

Tried with a different grant type, worked flawlessly, so why does it error when using password?

Version 3.1.3

**Comment by leastprivilege** [comment]
do you have a validator for the password?

**Comment by maulik-modi** [comment]
`services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>()
	.AddTransient<IProfileService, ProfileService>()`

https://www.linkedin.com/pulse/securing-net-core-web-api-identityserver4-using-owner-dalvandi-2/
