### ISSUE TITLE
Refused to frame 'http://localhost:5000/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'"

### ISSUE THREAD

**Issue by zqyo2000z** [IdentityServer/IdentityServer4#4457]
### Question
Refused to frame 'http://localhost:5000/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'"

### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by brockallen** [comment]
Not enough context.

**Comment by maulik-modi** [comment]
@zqyo2000z , Please provide identityserver verbose logs and Browser > Console logs
