### ISSUE TITLE
HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by patricioortiz** [IdentityServer/IdentityServer4#4458]
**We can only help you if you are on the latest version. Either use the latest 2.x or 3.x**

Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](http://docs.identityserver.io/en/latest/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem
I have an application running ok in a azure app service, it is a asp.net core 3.1, with angular 9 and IndentityServer 4, I use the AspNetCore.Identity and everything works fine with the *.azurewebsites.net domain, but when I use the custom domain (I tried with different options, I have bought from MSFT a certificate, I have used the free managed certificate from MSFT and created one with openssl) the app can login but when I use http requests, in the azurewebsites.net domain works fine but with my custom domain I got 401's... The user IS logged in.
I have used the default template from VS with the angular oidc client.

startup.cs
  public void ConfigureServices(IServiceCollection services)
        {
            X509Certificate2 cert = null;
            using (X509Store certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
            {
                certStore.Open(OpenFlags.ReadOnly);
                X509Certificate2Collection certCollection = certStore.Certificates.Find(
                    X509FindType.FindByThumbprint,
                    "900F9CF0E0E4E5E7597EDE30311162B5D034SD5A"
                    false);
                if (certCollection.Count > 0)
                {
                    cert = certCollection[0];
                    Log.Logger.Debug($"**********Successfully loaded cert from registry: {cert.Thumbprint}");
                }
            }

            // Fallback to local file for development
            if (cert == null)
            {
                cert = new X509Certificate2(Path.Combine(Environment.ContentRootPath, "appvMarket.pfx"), "xxxxxxxx");
                Log.Logger.Debug($"***********Falling back to cert from file. Successfully loaded: {cert.Thumbprint}");
            }
            ////////////

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection")));

            services.AddCors();

            services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddEntityFrameworkStores<ApplicationDbContext>();

            services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>().AddSigningCredential(cert);
#######appsettings.json
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=xxxxxx.database.windows.net;Initial Catalog=MyDatabase;User ID=mysuer;Password=mypass;integrated security=false;"
  },
  "Logging": {
      "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
      }
    },
  "IdentityServer": {
    "Clients": {
      "Daltum.Rest.Web": {
        "Profile": "IdentityServerSPA"
      }
    },
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "CurrentUser",
      "Name": "CN=app.customdomain.com"
    }
  },
"AllowedHosts": "*"
}

### Relevant parts of the log file

This only happens with a custom domain

Failed to load resource: the server responded with a status of 401 (Unauthorized)

**Comment by maulik-modi** [comment]
@patricioortiz , Could you please confirm if this line ever gets printed in case of custom domain?
`Log.Logger.Debug($"**********Successfully loaded cert from registry: {cert.Thumbprint}");
`

**Comment by patricioortiz** [comment]
Hello, I got the problem solved! It was the issuerUri...

Thank you!

**Comment by maulik-modi** [comment]
yes, @patricioortiz , Every time you use a  host URL different than the one Kestrel is listening e.g. 
behind reverse proxy, DNS domain, you must set Authority or IssuerUri explicitly.

**Comment by maulik-modi** [comment]
@patricioortiz , Please close this issue

**Comment by patricioortiz** [comment]
Problem solved
