### ISSUE TITLE
Fields get missing after the CreateAsync call

### ISSUE THREAD

**Issue by makemefeelgr8** [IdentityServer/IdentityServer4#4459]
### Issue / Steps to reproduce the problem
1. Use the latest version of identity service in .NET Core 3.1 project.
2. Create DB context, add a custom ApplicationUser class like this:
```
public class ApplicationUser : IdentityUser
{
    public string ExtendedJobName { get; set; }
}
```
3. Inject a user manager like you normally would:
```
UserManager<ApplicationUser> userManager 
```
4. Create a variable of ApplicationUser type, fill it with your data.
```
ApplicationUser newUser = new ApplicationUser();
newUser.ExtendedJobName = "Test Name";
...
```
5. Create a user like this:
```
await userManager.CreateAsync(newUser, "strong-password");
```
As you can see, the `ExtendedJobName` property is missing from a created user.
In case you use the following function, it works fine:
```
await userManager.CreateAsync(newUser);
await userManager.AddPasswordAsync(newUser, "strong-password");
```

There is nothing to log here, just INSERT INTO sql queries with custom property missing in the 1st case and present in the 2nd case.

**Comment by brockallen** [comment]
Your question is about ASP.NET Identity, not IdentityServer. This repo is for IdentityServer, not ASP.NET Identity.
