### ISSUE TITLE
Can IS4 and API be within the same project?

### ISSUE THREAD

**Issue by WayneWinter** [IdentityServer/IdentityServer4#4463]
After following this https://github.com/cradle77/BlazorSecurityDemo, which has
a separate API to the server project I wish to have the API within the server (IdentityProvider)
so in effect in this example I am calling Weatherforecast controller in the IdentityProvider project.
 I have hit the CORS problem and have tried all sorts of variations in setting up
CORS allowed origin for Https://localhost:5001 to no avail,
I am beginning to wonder, is it even possible?

**Comment by leastprivilege** [comment]
Have a look at the Blazor or Angular/React templates in Visual Studio. That's what they do. We don't recomend it, but it works.
