### ISSUE TITLE
Missing OpenIdConnect.nonce Cookie after upgrade from .NET Core 1.0 to .Net Core 3.1

### ISSUE THREAD

**Issue by rfennell** [IdentityServer/IdentityServer4#4464]
### Question
I have recently been upgraded an Identity Server 4 previously hosted on .NET Core 1.0 (IdentityServer4 Version 1.5.2) directly to .NET Core 3.1 (IdentityServer4 Version 3.12)

I  have only made changes required due to changed API methods, there should  be no logical changes to the logical flow for what was a previously working Identity Server instance.

Now, upon successful authentication, when a call is made to my `https://mysite.com/signin-oidc` endpoint, a .NET Framework 4.7.2 MVC web sites, it is failing with an error 

> IDX10311: RequireNonce is 'true' (default) but validationContext.Nonce is null. A nonce cannot be validated. If you don't need to check the nonce, set OpenIdConnectProtocolValidator.RequireNonce to 'false'.

On checking with Fiddler I can see that the OpenIdConnect.nonce Cookie is indeed missing in the post request to the signin-oidc.

If I revert my Identity Server back to the .NET Core 1.0 version and re-run my test then the cookie re-appears. So it does appear the issue is to do with the upgrade.

So my questions are
- Is there a step I need to do to make sure nonce is generated that differs between .NET Core 1.0 and 3.1?
- Any suggest on how best to debug this issue

**Comment by leastprivilege** [comment]
Sounds like a SameSite issue.

**Comment by rfennell** [comment]
Futher analysis shows the problem can  be initialy seen when going from .net core 1.0 to 2.0, after supposedly making all the changes the release notes recommend when moving through .net core versions. I would not have expected samesite changes to have impacted at this point if the upgrade steps to 3.1

Having spent a good deal of time trying to work out where the upgraded version is going wrong, i am thinking it might it might be easier to start the the current .net core 3.1 quickstart sample and bring over the custom logics from the older implementation.

**Comment by rfennell** [comment]
We found our issue, it was not the upgrade from .NET Core 1.0 to 3.1, but in the system that calls the Identity Server passing a corrupted URL that our own custom code was erroring on and discarding the the nonce cookies
