### ISSUE TITLE
Identity Sever connect/token method taking time to return the token

### ISSUE THREAD

**Issue by sahil-sdm** [IdentityServer/IdentityServer4#4465]
I have setup Identity Server 4 with Entity Framework in .net core web api.
Identity Server for the method (/connect/token) taking around 12 seconds to return the token

Please suggest on this.

**Comment by leastprivilege** [comment]
I suggest you do some profiling.

**Comment by sahil-sdm** [comment]
> I suggest you do some profiling.

Can you please suggest some articles to do the same
