### ISSUE TITLE
How to add custom claims during client credentials flow - can we use IProfileService or equivalent?

### ISSUE THREAD

**Issue by mmvohra-code** [IdentityServer/IdentityServer4#4469]
Problem:- We have client credentials flow and we want to add some claims to it

We have implemented Customprofileserives

Purpose for this is :-To add custom claim such as TokenId similar to jti, we need event handler that gets called before issuing token

1.  Profile service does not get called for Client credentials flow

```
public class CustomProfileServices : IProfileService
 {  
var claims = new List<Claim>
                     {

                            new Claim("username", user?.UserName),
                            new Claim("email", user?.Email),
                   
                     };

                        context.IssuedClaims.AddRange(claims);
}
```

**Comment by leastprivilege** [comment]
Profile service only gets called when a user is present - so not in client credential flow.

If you want to add client claims you need to use a `ICustomTokenRequestValidator`.
