### ISSUE TITLE
I am getting access token, even posting false secret

### ISSUE THREAD

**Issue by nburak** [IdentityServer/IdentityServer4#447]
Hello,
in Identity Server 4 , I post a true client_id with an invalid client_secret to the identity server. In spite of this. I am getting Access Token. 

For example. My client name is wlclient and secret is topsecret. But i post wlclient as client_id and topsecret2 as client_secret. In spite of this. I got Access token. How can i solve this problem?

Thank you

**Comment by leastprivilege** [comment]
I don't think that this is the case - have you set `RequireClientSecret` to false by chance?

Try our sample clients - or check our integration tests - they prove that this cannot be the case.

**Comment by nburak** [comment]
When i added a new client from an external app to database, i set RequireClientSecret column as false. 
But when i update it to true, I am getting invalid_client error, even i post correct client_id and secret.

**Comment by leastprivilege** [comment]
You need to put client secrets as SHA256 into your database.

**Comment by nburak** [comment]
Sorry but. In spite of me to use Sha256() function and have a hashed secret, I am getting invalid_client error.  This is what i have in the ClientSecrets table. Thank you very much for all of your helps.
![finaldb](https://cloud.githubusercontent.com/assets/7663595/19932241/080fe5fc-a118-11e6-8b53-7fd8acf0a9f4.png)
