### ISSUE TITLE
ProfileService not being executed nor breakpoint hit

### ISSUE THREAD

**Issue by Khalid-Mekdad** [IdentityServer/IdentityServer4#4473]
I know this question was asked many times before , but I can't get the profile service being called, I also added breakpoint inside GetProfileDataAsync function but nothing hits .. 

As I read before in other [question](https://github.com/IdentityServer/IdentityServer4/issues/2155#issuecomment-374159366) related , it is being automatically when I need extra claims

my goal is I have a claim called **subsetId** which is supposed to be filled inside the profile service

I checked my container to make sure that the IprofileService is being injected and it's injected.

Here is the code inside the **Startup.cs** inside the identityServer 

```

var builder = services.AddIdentityServer(options =>
                {
                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;
                })
                .AddInMemoryIdentityResources(Config.Ids)
                .AddInMemoryApiResources(Config.Apis)
                .AddInMemoryClients(Config.Clients);
          
            services.AddScoped(typeof(IProfileService), typeof(ProfileService));
            
            builder.AddAspNetIdentity<ApplicationUser>();
```

also here's the code of  IdentityResource and Clients inside the **Config.cs** file

```
new IdentityResource[]
           {    new IdentityResource("subsetId", new List<string>{"subsetId"}),
                new IdentityResources.OpenId(),
                new IdentityResources.Profile()
           };
      new Client
                {
                    ClientId = "js",
                    ClientName = "JavaScript Client",
                    AllowedGrantTypes = GrantTypes.Code,
                    RequirePkce = true,
                    RequireClientSecret = false,

                    RedirectUris =           { "http://localhost:4200/assets/callback.html" },
                    PostLogoutRedirectUris = { "http://localhost:4200" },
                    AllowedCorsOrigins =     { "http://localhost:4200" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "subsetId",
                        "api1",
                    },
                    AlwaysSendClientClaims = true,
                    AlwaysIncludeUserClaimsInIdToken = true
                }
```

here is the code GetProfileDataAsync inside ProfileService which implements IProfileService 

 ```
 public async Task GetProfileDataAsync(ProfileDataRequestContext context)
     {
             var sub = context.Subject.GetSubjectId();
            var user = await _userManager.FindByIdAsync(sub);
            var principal = await _claimsFactory.CreateAsync(user);

            var claims = principal.Claims.ToList();
             claims.Add(new Claim("subsetId", user.UserType.ToString() ?? string.Empty));
            context.IssuedClaims = claims;
        }
```

and finally here is the configuration of the my Js client

```
  oidcConfig: {
        authority: "https://localhost:5000/",
        client_id: "js",
        redirect_uri: "http://localhost:4200/assets/callback.html",
        response_type: "code",
        scope: "openid profile subsetId api1",
        post_logout_redirect_uri: "http://localhost:4200/",
        loadUserInfo: true,
        extraQueryParams: {
         "provider":'asp'
        },

```

I am not sure what is wrong in my code ,, I have been searching for the problem for many hours and I still can't figure out where is the problem , or am I understand it wrongly , your help is much appreciated

**Comment by Khalid-Mekdad** [comment]
I think I figured out what is the problem in my code ..

inside function IsActiveAsync inside the profile service I had the following

```
     public async Task IsActiveAsync(IsActiveContext context)
        {
            var sub = context.Subject.GetSubjectId();
            var user = await _userManager.FindByIdAsync(sub);

            if (user == null)
                context.IsActive = false;

            context.IsActive = !user.LockoutEnabled ? true : false;

        }
```

the user which I used to login has **LockoutEnabled** = **true** which sets **context.IsActive  = false** that's why the GetProfileDataAsync didn't get called
once I set the **LockoutEnabled** = **false**  context.IsActive became true and the GetProfileDataAsync got called

 
but now I have another question .. I noticed that the **GetProfileDataAsync**  and **IsActiveAsync**  got called 3 times ... is that because my client has 3 allowed scopes?

 "I removed subsetId scope from IdentityResources and allowed scopes in my client and now client have only **openId,Profile,api1**" scopes ??

**Comment by HunteRoi** [comment]
From my understanding and use of the library at the moment, I suspect the IProfileService implementation to be called for each request made to the identity server.

In my usecase, a client requests the identity server once but it creates 3 underlying requests:
- /connect/authorize
- /connect/token
- /connect/userinfo

I came to this conclusion after checking the value of `context.Caller` in each method of the custom IProfileService class.
