### ISSUE TITLE
.Net Core Identity Server 4 + .Net core 3.1

### ISSUE THREAD

**Issue by ddgajjar** [IdentityServer/IdentityServer4#4475]
We are building micro-services architecture application, we created 4 services and authorize API endpoint using identity server in .Net Core 3.1.

We have different clients which will access our API, we will give them client ID and client secret to authorize our API Endpoint, Now clients will be dynamic so we want to implement Admin page where i can manage clients(Add, Update, Delete), client table is from ConfigurationDbContext.

So what is the best way to do CRUD operation on client table? (We are using code first)

**Comment by HunteRoi** [comment]
If you have news on that, I'd like to hear it ! It's something that will be asked for a future release on my project. 
If I can get feedbacks from someone who's implementing it at the moment, I'd be really happy.

**Comment by leastprivilege** [comment]
There is nothing built-in in IdentityServer for that. IS only has read access to the configuration data. So build it in any way you like.

**Comment by amadard** [comment]
@HunteRoi It ends up being another entire API to manage this data.  You can buy [AdminUI](https://www.identityserver.com/products/adminui) from the IdentityServer guys, or build it yourself.  I built it myself before I looked around enough to find AdminUI, and it ends up being a decent sized API.  In my build APIResources has 17 endpoints, Clients has 31, then add IdentityResouces, Roles, Users, and optional endpoints like Provisioning users and getting the available options for Scopes, Grant Types etc.  I used EF Core to manage the DB, and you end up needing full CRUD for each "model" in the DB Contexts.

**Comment by HunteRoi** [comment]
A completely new app so. Alright, thanks for the feedback !

I hope there's somebody available to close this issue if there's nothing to add on it.
