### ISSUE TITLE
LogoutContext.ClientId is null

### ISSUE THREAD

**Issue by katlimruiz** [IdentityServer/IdentityServer4#4476]
V3.1.1

LogoutContext.ClientId is null, however LogoutContext.Clients.First() does give you a record.

It is just a minor problem, or perhaps somewhere needs to explain what is the difference.

**Comment by katlimruiz** [comment]
OK, so let me explain better.

This is my code in my LogoutController.

```
[Route("account/logout")]
[HttpGet]
public async Task<IActionResult> Index(string logoutId)
{
    if (string.IsNullOrEmpty(logoutId))
    {
        throw new ArgumentNullException("logoutId");
    }

    var logoutCtx = await _identityServerInteractionService.GetLogoutContextAsync(logoutId);
    if (logoutCtx != null)
    {
        var subid = GetSubjectId(logoutCtx, User, "<unknown>");
        var subname = GetSubjectName(User, "<unknown>");

        **string clientId = logoutCtx.ClientId ?? logoutCtx.ClientIds.FirstOrDefault();**
        if (string.IsNullOrEmpty(clientId))
        {
            logger.Error("ClientId not available");
            throw new ArgumentNullException("client", "ClientId not available");
        }
    }
    else
    {
        throw new ArgumentNullException("LogoutCtx is null although logoutId is present");
    }            
}
```
(this is just an excerpt).

The problem is in this line:
`logoutCtx.ClientId ?? logoutCtx.ClientIds.FirstOrDefault();`

I would've thought that `logoutCtx.ClientId == logoutCtx.ClientIds.FirstOrDefault()`. However, it is not.

The left side is null, and the right side does have a value.

Indeed the code already goes around the problem, yet I think this is a bug worth fixing. Therefore, this issue being created.

**Comment by brockallen** [comment]
They mean two different things. The client ids are use for SLO notification. The ClientId is the client that request logout. 

It's also unclear what you're using it for, so I can't say what you're doing is right or wrong.

**Comment by katlimruiz** [comment]
I'm trying to obtain the clientId that is requesting logout. Yet it is null. I had to get it from the array of clients.

**Comment by brockallen** [comment]
> I'm trying to obtain the clientId that is requesting logout. Yet it is null.

That means something about the signout request validation failed.
