### ISSUE TITLE
Sample projects don't open in Visual Studio

### ISSUE THREAD

**Issue by garethrbrown** [IdentityServer/IdentityServer4#4478]
The initial issue is that opening from the solution file results in Visual Studio opening with the projects unloaded.

This is fixed by adding a global.json file directing to the .NET Core version installed.

For example - the sample under: 3_AspNetCoreAndApis

Having resolved this, the solution can then not be built reporting project.assets.json not found for each project.

The samples should open and at least build without having to work through these steps.

**Comment by terribletim** [comment]
There is global.json in the root folder of the repo. Edit `"version": "3.1.200" to match the highest version number installed on your computer (for VS users, PM Console `dotnet --list-sdks` to see versions).

The nuget.config in root folder can also cause grief for VS. Uncheck "IdentityServer Local" in NuGet Package Manager / Package Sources.
