### ISSUE TITLE
Hybrid Flow sample did not work for me

### ISSUE THREAD

**Issue by persiandeveloper** [IdentityServer/IdentityServer4#448]
Hi

I just followed the doc step by step and when reached "Switching to Hybrid Flow and adding API Access back" (http://docs.identityserver.io/en/dev/quickstarts/5_hybrid_and_api_access.html?highlight=refresh%20token), when the mvc client cannot access the identityserver and I get the following error : 

![image](https://cloud.githubusercontent.com/assets/8937406/19786584/8af175ec-9cab-11e6-9438-463cb6c977b2.png)

Here is my configuration in mvc client : 

`app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",

                Authority = "http://localhost:5000",
                RequireHttpsMetadata = false,

                ClientId = "mvc",
                ClientSecret = "secret",

                ResponseType = "code id_token",
                Scope = { "api1", "offline_access" },
                GetClaimsFromUserInfoEndpoint = true,
                SaveTokens = true
                

              

            });`

And Startup file also the config in Identityserver app:

`public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit http://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
                 //.AddJsonFormatters()
                //.AddAuthorization();

            services.AddDeveloperIdentityServer()
            .AddInMemoryScopes(Config.GetScopes())
            .AddInMemoryUsers(Config.GetUsers())
            .AddInMemoryClients(Config.GetClients());
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            //app.UseDeveloperExceptionPage();

            app.UseIdentityServer();

          

            app.UseStaticFiles();
            app.UseMvcWithDefaultRoute();
        }
    }`

`new Client
                    {
                        ClientId = "mvc",
                        ClientName = "MVC Client",
                        AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,

                        RequireConsent = true,

                        ClientSecrets =
                        {
                            new Secret("secret".Sha256())
                        },

                        RedirectUris           = { "http://localhost:5002/signin-oidc" },
                        PostLogoutRedirectUris = { "http://localhost:5002" },

                        AllowedScopes =
                        {
                            StandardScopes.OpenId.Name,
                            StandardScopes.Profile.Name,
                            StandardScopes.OfflineAccess.Name,
                            "api"
                        }
                    }
...

return new List<Scope>
                {
                    
                    StandardScopes.OpenId,
                    StandardScopes.Profile,
                    StandardScopes.OfflineAccess,

                    new Scope
                    {
                        Name = "api1",
                        Description = "My API"
                    },

                };
`

**Comment by brockallen** [comment]
Not enough info in this short log snippet.

**Comment by persiandeveloper** [comment]
@brockallen I followed the mentioned sample and all the codes are same. When I run the MVC client it redirects to Identityserver (in this case localhost:5000), and the error appears in console, "Bearer was not authenticated"
If I switch back the client configuration to what described here "http://docs.identityserver.io/en/dev/quickstarts/3_interactive_login.html" it again works.

**Comment by leastprivilege** [comment]
Did you try the working sample from the samples repo?

https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/5_HybridFlowAuthenticationWithApiAccess

**Comment by persiandeveloper** [comment]
@leastprivilege yes it did work with original sample. Now I have problem using postman calling the token endpoint, cause it throws the following error : 

....
 CorsPolicyService did not allow origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop
....

I tried this in my config : 

```
services.AddCors(options =>
            {
                options.AddPolicy("AllowOrigins", policyBuilder =>
                {
                    policyBuilder
                    .AllowAnyMethod()
                    .AllowAnyOrigin()
                    .AllowAnyHeader();
                });
            });
```


...


```
 app.UseIdentityServer();
 app.UseCors("AllowOrigins");
```

But still get same error.

**Comment by leastprivilege** [comment]
That's a postman issue I guess - but definitely a new issue. closing this one.

**Comment by leastprivilege** [comment]
The Postman issue seems to be the same as https://github.com/IdentityServer/IdentityServer4/issues/439
