### ISSUE TITLE
Merging an API project with IDP

### ISSUE THREAD

**Issue by kentcb** [IdentityServer/IdentityServer4#4483]
### Question

I have an API project and IDP project implemented separately and working (at least, well enough for development purposes). I am considering merging the two projects, since that would make deployment and dependency management easier. However, I cannot find any real guidance on this.

I tried simply copying files and code from the IDP project into the API project and got it building and running. I could hit the `openid-configuration` endpoint, as well as an unauthorized API. However, when hitting an authorized API I got through the login process but then hit a server error (I stupidly didn't record the error and have reverted the code, but I believe it was to do with the JWT token handler).

What I'm wondering is whether there is any guidance on combining an ADP server project into an existing ASP.NET API project?

**Comment by leastprivilege** [comment]
Well. there are some subtleties - mainly involving ASP.NET Core authentication configuration and the fact that you now want multiple default authentication methods (cookies for UI, JWT for API).

It is doable, but we don't recommend doing that, and we don't have guidance for it.
