### ISSUE TITLE
An error occurred while opening two tabs at the same time

### ISSUE THREAD

**Issue by myesn** [IdentityServer/IdentityServer4#4486]
Scenario: Using the chrome browser, create two new tabs and navigate to the login page. When one of the tabs is logged in, the other tab will log in again and you will get an error. How can I solve this?

The experience of github is like this. After one of the tabs is logged in, the other tab prompts that you are logged in, and the login button will not send a request to the background, but I don’t know how he implemented it?

Can someone help me? Thank you!

**Comment by brockallen** [comment]
> When one of the tabs is logged in, the other tab will log in again and you will get an erro

This is likely an anti-forgery issue, not an IdentityServer issue. Check with Microsoft.
