### ISSUE TITLE
User previous consent when user is logging again to a client app

### ISSUE THREAD

**Issue by HunteRoi** [IdentityServer/IdentityServer4#4487]
### Question
As explained in [an older issue](https://github.com/IdentityServer/IdentityServer4/issues/928), the consent is always asked again to the user which seems weird.

The links provided by @brockallen are not accessible anymore. What is the way to go with IdentityServer4 to only allow the consent once for a client app?

**Comment by brockallen** [comment]
If subsequent requests ask for offline_access, the spec says you should re-prompt for consent. That's why we do it that way.
