### ISSUE TITLE
AuthorizeErrors.UnsupportedResponseType when "Invalid response_mode for flow"?

### ISSUE THREAD

**Issue by tiagofe** [IdentityServer/IdentityServer4#4491]
### Question
When we request an authorization for **Hybrid flow** (response_type=code id_token) and try to use **response_mode=query** which obviously is not supported by Hybrid flow. We are receiving the message:
```
error code=unsupported_response_type
Error Description=Invalid response_mode
```

In our opinion, this message is not clear to understand the problem. In this case, the real problem is query response_mode is not supported for Hybrid flow.

Instead of "unsupported_response_type" for the error code, should be "invalid_request" (based on [OAuth2 Authorization error response spec](https://tools.ietf.org/html/rfc6749#section-4.1.2.1))?
Is it possible to have a better error description message? Example: "**Invalid response_mode for flow**" or better "**Invalid response_mode (query) for Hybrid flow**"?

It seems the return statement for error message it's a copy-paste situation.
### Minimal working example

The code bellow is found on [AuthorizeRequestValidator.cs](https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/Validation/Default/AuthorizeRequestValidator.cs) (**line 437**) 
```csharp
    // check if response_mode parameter is present and valid
            var responseMode = request.Raw.Get(OidcConstants.AuthorizeRequest.ResponseMode);
            if (responseMode.IsPresent())
            {
                if (Constants.SupportedResponseModes.Contains(responseMode))
                {
                    if (Constants.AllowedResponseModesForGrantType[request.GrantType].Contains(responseMode))
                    {
                        request.ResponseMode = responseMode;
                    }
                    else
                    {
                        LogError("Invalid response_mode for flow", responseMode, request);
                        return Invalid(request, OidcConstants.AuthorizeErrors.UnsupportedResponseType, description: "Invalid response_mode");
                    }
                }
                else
                {
                    LogError("Unsupported response_mode", responseMode, request);
                    return Invalid(request, OidcConstants.AuthorizeErrors.UnsupportedResponseType, description: "Invalid response_mode");
                }
            }

```

**Comment by leastprivilege** [comment]
Thanks. 

We are discussing this here: https://github.com/IdentityServer/IdentityServer4/pull/4504
