### ISSUE TITLE
InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.

### ISSUE THREAD

**Issue by kodlar** [IdentityServer/IdentityServer4#4497]
Hello helper person,
 I need help, I got error as in the title
 I'm using ubuntu 18.04 and on ubuntu, IdentityServer4
 builder.AddDeveloperSigningCredential(); certification does not wok

What do you offer to me?
Thanks

**Comment by JoseOchoaITH** [comment]
There is no enough information about the question but I had the exact same issue last week trying to make a request to an IS4 app hosted on a Linux container.
The issue was related to trusting the certificate of the application.
Hope it helps

**Comment by lyubomirr** [comment]
You can get the hidden part if you set IdentityModelEventSource.ShowPII to true. That way you can debug easier. This error generally says that your client application cannot get the configuration from ./well-known/openid-configuration .
