### ISSUE TITLE
Entity Framework

### ISSUE THREAD

**Issue by jerry2007** [IdentityServer/IdentityServer4#45]
Hello,
I would like to ask you, if you plan some project with Entity Frameowork which will implement IClienStore etc.

Like IdentityServer3.EntityFramework.

And if you have plant his, could you tell me some release date please?

**Comment by leastprivilege** [comment]
yes - and no.

It is not even clear when EF and ASP.NET Core will be released.

**Comment by joaomello** [comment]
Hi! I'm very noob yet at IdentityServer4. I'm trying to use at my new project, and I created "something" to connect with database based on the existing IdentityServer3, ultil rc2 comes out https://github.com/joaomello/playgrond/tree/master/IdentityServer4/EntityFramework

And call this at startup https://github.com/joaomello/playgrond/blob/master/IdentityServer4/EntityFramework/Extensions/IdentityEntiyFrameworkServerBuilderExtensions.cs#L8

It's not the best option, and don't have the token stores, but in my case is good enough.

Just trying to help (=

**Comment by jerry2007** [comment]
@joaomello thank you very much, I will try it...

**Comment by joaomello** [comment]
This is how I did the config, just add the code to the project.

```
public class UpdateContext : IScopeConfigurationDbContext, IClientConfigurationDbContext
    {
        public DbSet<EntityFramework.Entities.Client> Clients { get; set; }
        public DbSet<EntityFramework.Entities.Scope> Scopes { get; set; }
    }

```
```
services.AddIdentityServer(options =>
            {
                options.RequireSsl = false;
                options.SigningCertificate = cert;
            })
                .AddInIdentityEntity<UpdateContext, UpdateContext>()
```

**Comment by jerry2007** [comment]
Only for information...
I found this projet:
TwentyTwenty.IdentityServer4.EntityFramework7

It's implementation of clients and scopes for IdSrv4 and work very well

`services.AddIdentityServer(options =>
            {
                options.SigningCertificate = cert;
            }).AddInMemoryUsers(new List<InMemoryUser>())
                .ConfigureEntityFramework()
                .RegisterOperationalStores()
                .RegisterClientStore<Guid, ClientConfigurationContext>()
                .RegisterScopeStore<Guid, ScopeConfigurationContext>();`
