### ISSUE TITLE
How can I implement a custom TokenCleanupService class

### ISSUE THREAD

**Issue by tedzhao** [IdentityServer/IdentityServer4#4500]
The identityserver provides a way that clean grants, consents, and tokens, see the link: [http://docs.identityserver.io/en/latest/reference/ef.html]

`public IServiceProvider ConfigureServices(IServiceCollection services)
{
    const string connectionString = @"Data Source=(LocalDb)\MSSQLLocalDB;database=IdentityServer4.EntityFramework-2.0.0;trusted_connection=yes;";
    var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

    services.AddIdentityServer()
        // this adds the operational data from DB (codes, tokens, consents)
        .AddOperationalStore(options =>
        {
            options.ConfigureDbContext = builder =>
                builder.UseSqlServer(connectionString,
                    sql => sql.MigrationsAssembly(migrationsAssembly));

            // this enables automatic token cleanup. this is optional.
            options.EnableTokenCleanup = true;
            options.TokenCleanupInterval = 3600; // interval in seconds (default is 3600)
        });
}`
 
I saw when enable token clean up, the identityserver will call TokenCleanupService[https://github.com/IdentityServer/IdentityServer4/blob/1d58568f8ac718cc622e98ce1a5fce1c7c9e27db/src/EntityFramework.Storage/src/TokenCleanup/TokenCleanupService.cs].

Can I implement a custom TokenCleanupService class?

Regards

**Comment by wterpstra** [comment]
The TokenCleanupService is being called from the TokenCleanup host, which is a ASP.NET hosted service. It is not being resolved through an interface, so no you can't implement your own. However, the TokenCleanupService will call the PersistedGrantsRemovedAsync(IEnumerable<PersistedGrant> persistedGrants) method  on the IOperationalStoreNotification interface after removing the persisted grants. Maybe you can implement your own IOperationalStoreNotification and run your logic after removal.
