### ISSUE TITLE
Build question

### ISSUE THREAD

**Issue by olegbaev** [IdentityServer/IdentityServer4#4503]
**Can someone explain what is the aim of having here IdentityServer4.Local.csproj ?**
https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/src/IdentityServer4.Local.csproj

The reason I am asking - I upgraded VS.NET (using the latest 2019 VS.NET upgrade) and .NET FWK to 3.1.200 on Windows and started having build issues using this solution - https://github.com/IdentityServer/IdentityServer4/blob/master/src/IdentityServer4/IdentityServer4.sln.

Pretty sure before the upgrade the build on my local Windows was OK. 

For some reason VS.NET was keeping downgrading the IdentityServer  Nuget due to IdentityServer4.Storage Referenced there (was keeping reverting to using the preview of IdentityServer4.Storage).

I finally did fix my issue as was done in IdentityServer4.Local.csproj ie referencing the project directly as was done in IdentityServer4.Local.csproj 
 <ProjectReference Include="..\..\Storage\src\IdentityServer4.Storage.csproj" />

Very puzzled with the aim of this .Local. file...

Please advise.

**Comment by leastprivilege** [comment]
Feel free to ignore it. It's an artifact on an experiment I did a while ago - and forgot to delete it.

**Comment by olegbaev** [comment]
Thanks, Dominick
