### ISSUE TITLE
Winforms example?

### ISSUE THREAD

**Issue by madmunsterdaddy** [IdentityServer/IdentityServer4#451]
Sorry if I'm missing it but do you have a logon example using Winforms? For example, Skype (desktop) when you sign into your MSA it brings up what I assume is a browser window (maybe its just a very stylized form?).

I need to make calls into my API from a Winforms app and need them to authenticate first, then ideally store that token and keep using it.

Thanks!

**Comment by brockallen** [comment]
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples
