### ISSUE TITLE
Question about quickstart documentation: `AddJwtBearer` vs `AddIdentityServerAuthentication`

### ISSUE THREAD

**Issue by sam-wheat** [IdentityServer/IdentityServer4#4512]
Hello I am going through the quickstarts one by one and I ran into an issue:

In [this part](https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html) of the quickstart it says the api controller should look like this:

		public void ConfigureServices(IServiceCollection services)
		{
			services.AddControllers();

			services.AddAuthentication("Bearer")
				.AddJwtBearer("Bearer", options =>
				{
					options.Authority = "https://localhost:5001";
					options.RequireHttpsMetadata = false;

					options.Audience = "api1";
				});
		}
			
			
However in the [section for adding a JavaScript client](https://identityserver4.readthedocs.io/en/latest/quickstarts/4_javascript_client.html) the code for api Startup.cs looks like this:

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddControllers();

		services.AddAuthentication("Bearer")
			.AddIdentityServerAuthentication(options =>
			{
				options.Authority = "http://localhost:5000";
				options.RequireHttpsMetadata = false;

				options.ApiName = "api1";
			});

	}
	
	
	
Which one is correct?

Also the quickstart appears to be missing this requirement in Startup.cs in IdentityServer project:

         options.UserInteraction = new UserInteractionOptions()
			{
				LogoutUrl = "/account/logout",
				LoginUrl = "/account/login",
				LoginReturnUrlParameter = "returnUrl"
			};

I found a Stackoverflow question that got me past it but I thought I would mention it.

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation#identityserver4accesstokenvalidation
