### ISSUE TITLE
Minimal example of signing with DataProtection

### ISSUE THREAD

**Issue by arisliang** [IdentityServer/IdentityServer4#4519]
The documentation barely mentioned it's possible to configure token Signing and validation with DataProtection api at http://docs.identityserver.io/en/latest/topics/crypto.html#data-protection.

However, the documentation doesn't have any example, even a minimal one.

In DataProtection api, `PersistKeysToFileSystem` is probably easiest to use, as it only needs to specify a directory. Is it possible to add a minimal example of how to use `PersistKeysToFileSystem` in DataProtection, to sign for IdentityServer?

Thanks.

**Comment by btshft** [comment]
Hi!

It seems to me that there is a slight misunderstanding in in the purpose of DataProtection API.

The main purpose of the [Data Protection API](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/using-data-protection?view=aspnetcore-3.1) is to protect and encrypt data. It based on [symmetric cryptography](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/implementation/context-headers?view=aspnetcore-3.1) that is not very suitable for signing and validating tokens at pointed in #3843. The main reason why it is not recommended to use symmetric algorithms for digital signature is their lack of [non-repudiation](https://en.wikipedia.org/wiki/Non-repudiation) property i.e. the receiver of a message can't prove that he didn't create the message themselves. This makes the system **potentially insecure**.

I managed to find that IdentityServer4 using DataProtection API to 
* Persisting protected state in a [distributed cache](https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/src/Configuration/DependencyInjection/IdentityServerServiceCollectionExtensions.cs#L84) (via [formatter](https://github.com/IdentityServer/IdentityServer4/search?q=IDataProtector&unscoped_q=IDataProtector))
* Protecting cookies ([here](https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/src/Infrastructure/MessageCookie.cs))
* Protecting [consent result](https://identityserver4.readthedocs.io/en/latest/topics/consent.html#informing-identityserver-of-the-consent-result) (via [custom message store](https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/src/Stores/Default/ProtectedDataMessageStore.cs))

It seems to me that from your link to the documentation, it's about protecting cookies, but not for signing tokens.

**Comment by arisliang** [comment]
My main purpose is to use DataProtection API's key rollover feature to provide signing keys for IdentityServer, so I could avoid using Develop signing key in production environment. Guess it's the same as #3843, and therefore not recommended.
