### ISSUE TITLE
Authenticating and Authorization with Multiple ActiveDirectory

### ISSUE THREAD

**Issue by mominmaaz** [IdentityServer/IdentityServer4#4523]
### Question
My requirement is using IdentityServer for Multiple domain(having seperate Active Directory). So if a user with abc@company1.com tries to login I would like to check credentials in company1 database, similarly if abc@xyz.com tries to login, I would like to check crecentials in xyz database. Also the auth policies will be mapped from their database to general auth policy defined in our system. Can we achieve this by using IdentitySever4. An example or a doc/link pointing in this direction would help a lot.

**Comment by amadard** [comment]
How do you know which company the user belongs to before you send them to Active Directory to log in?

**Comment by mominmaaz** [comment]
> How do you know which company the user belongs to before you send them to Active Directory to log in?

By the domain of the email I'd.

**Comment by leastprivilege** [comment]
Windows integrated authentication only allows authentication with the domain the machine is joined to - or a trusted one.

**Comment by mominmaaz** [comment]
> Windows integrated authentication only allows authentication with the domain the machine is joined to - or a trusted one.

Well noted but more importantly can we achieve this for Authenticate and Authorization with Multiple domain?

**Comment by cdecinkoKnight** [comment]
What if you used a "gateway" app? Users go to the app where it examines which company and then redirects to an instance of IDS4 for each company?

**Comment by mominmaaz** [comment]
> What if you used a "gateway" app? Users go to the app where it examines which company and then redirects to an instance of IDS4 for each company?

Yes that would be another option but I was hoping for a solution directly provided by IDS4.

**Comment by mominmaaz** [comment]
One of the way that I found was by using a ef template of identity and then in AccountController we can find out domain of the user, map the domain with provider and then Challenge.

**Comment by mominmaaz** [comment]
For authorization one can use [PolicyServer](https://github.com/PolicyServer/PolicyServer.Local) or [OpenPolicyAgent ](https://www.openpolicyagent.org/docs/latest/)
