### ISSUE TITLE
Using docs SigninManager.GetExternalLoginInfoAsync() returns null with external

### ISSUE THREAD

**Issue by madmunsterdaddy** [IdentityServer/IdentityServer4#453]
Hi there,

Was following along with the docs. I am using the ASP.net Core Individual Auth template and I added my external providers, however I'm having issues on the login screen using them when they're configured the way the docs show.

https://identityserver4.readthedocs.io/en/dev/quickstarts/4_external_authentication.html

In those docs it says to configure the provider like so:

```
app.UseGoogleAuthentication(new GoogleOptions
{
    AuthenticationScheme = "Google",
    DisplayName = "Google",
    SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,

    ClientId = "<Secret>",
    ClientSecret = "<Secret>"
});
```

However, when I do this, when attempting to click the button on the login screen, it calls into ExternalLoginCallback and makes this call:

var info = await _signInManager.GetExternalLoginInfoAsync();

GetExternalLoginInfoAsync() returns null here.

Knowing that this worked fine in a project I had done I compared and saw the SignInScheme was not defined in my project so I commented it out. Sure enough it works.

So if I leave out SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme, then everything works as expected.

I defined the Cookie per the docs as 

```
            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
                AutomaticAuthenticate = false,
                AutomaticChallenge = false                
            });
```

Am I missing something? Are the docs wrong? Or some other issue?

Thanks!

**Comment by brockallen** [comment]
The ASP.NET Identity library also needs to know that scheme. Configure it on the AddIdentity helper.

**Comment by madmunsterdaddy** [comment]
Thanks, can you show maybe what that would look like? I'm not seeing any setter in there for scheme. Anything I'm finding is read only?

**Comment by brockallen** [comment]
something like:
```
services.AddIdentity(options=>{
   options.Cookies.ExternalCookie.AuthenticationScheme = "SomeName";
});
```

**Comment by madmunsterdaddy** [comment]
Dang it! I did that I thought, but it said it was read only :-| Thank you.

You should add that to the docs in that section because as they stand now it doesn't work. Though technically you could remove overwriting the scheme, right? It worked because I just had it as default which appears to be "Identity.External"

**Comment by brockallen** [comment]
In our AspId3 sample we allow the AspId3 framework to register the external cookie middleware.

**Comment by brockallen** [comment]
As for the docs, we do accept PRs so if you find a good place for this info, please add it.

**Comment by kleancph-vladica** [comment]
Removing this line from the client MVC  app  solved the problem with the GetExternalLoginInfoAsync returning null. 

JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
