### ISSUE TITLE
Where is PublicOrigin option now?

### ISSUE THREAD

**Issue by ArtemAvramenko** [IdentityServer/IdentityServer4#4535]
### Question
After upgrade to 4.0.0, the following option is gone. Where is it now?

### Minimal working example

```csharp
    services.AddIdentityServer(options =>
    {
        options.PublicOrigin = "https://my.id.server";
    });
```

**Comment by leastprivilege** [comment]
It's gone. It was a hack - please use the forwarded headers approach in ASP.NET Core from now on.

**Comment by kostebudinoski** [comment]
hack that worked.  forwarded headers approach never worked for me on ngix.... facing same issue again

**Comment by leastprivilege** [comment]
All it did was setting the host and scheme to a hard-coded value.

You can easily replace it with

```csharp
app.Use(async (ctx, next) =>
{
    ctx.SetIdentityServerOrigin("https://foo.com");
    await next();
});
```
