### ISSUE TITLE
401 Invalid_token The issuer is invalid - Asp.Net Core 3.1, Angular, Identity Server 4, Azure App Service, Linux

### ISSUE THREAD

**Issue by richmhouse** [IdentityServer/IdentityServer4#4538]
### Question
I have created a web app https://www.alpacabiriba.com using the Visual Studio 2019 Template (Create New Project | Asp.Net Core Web Application | Angular + Inidividual User Accounts). I published this to an Azure Linux App Service using the VS2019 wizzards.

It works fine in Azure except when I click on Fetch Data when I get WWW-Authenticate: Bearer error="invalid_token", error_description="The issuer 'https://www.alpacabiriba.com' is invalid"

Please could some kind person help?

### Minimal working example
I changed as little as I could to try & get it working before I went on to change it to do Biriba things ...

1) I changed it to load the p12 SSL certificate from /var/ssl/private the Azure App Service put it in. This included my attempt to inline the AddApiAuthorization extension method to get round it insisting on accessing the certificate key from the appsettings.json rather than /var/ssl/private.

 2) I added some code to void Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) to apply database migrations when run in Azure.

```csharp
var identityServicesServicesColection = services.AddIdentityServer();
identityServicesServicesColection
  .AddAspNetIdentity < ApplicationUser > ()
  .AddOperationalStore < ApplicationDbContext > ()
  //.ConfigureReplacedServices()
  .AddIdentityResources()
  .AddApiResources()
  .AddClients();
var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT");
if (environment == Environments.Development)
{
  identityServicesServicesColection.AddSigningCredentials();
}
else
{
  var p12 = LoadP12Certificate();
  identityServicesServicesColection.AddSigningCredential(p12);
}
```

### Relevant parts of the log file

```
WWW-Authenticate: Bearer error="invalid_token", error_description="The issuer 'https://www.alpacabiriba.com' is invalid"
```

**Comment by leastprivilege** [comment]
The template comes from Microsoft. Please ask them over in the ASP.NET Core repo.

**Comment by richmhouse** [comment]
> 
> 
> The template comes from Microsoft. Please ask them over in the ASP.NET Core repo.

Thanks @leastprivilege (Dominick). Do you know of  another template that works when deployed to a production environment?

**Comment by imt-s1897** [comment]
I'm not 100% sure but I think I had the exact same problem deploying on a Linux Azure Webapp. The solution was setting the PublicOrigin-property with the correct domain origin. But if you are using the latest version (IdentityServer4 4.0+) that property has now been removed. I haven't yet tried to upgrade to the latest version (still using 3.1.3) and tried it out yet, but I suspect this will be a breaking change for my environment.

**Comment by richmhouse** [comment]
Thanks Mohammad (@imt-s1897). I set the PublicOrigin as follows bit sadly with no luck. If you could share your StartUp class of one that works when deployed to Azure I'd be immensley grateful.
`
            services.AddIdentityServer(options =>
                    options.PublicOrigin = "https://alpacabiriba.com";
            })
`

**Comment by imt-s1897** [comment]
> https://alpacabiriba.com

It that the place where IdentityServer4 is deployed? When one tries to access the domain you provided you get the welcome screen for Azure deployment. It's not under a subdomain? In my startup the PublicOrigin-property is for example set to https://login.my-domain.com.

Have you tried the templates provided by IdentityServer4? Just to see if you can get it running. You can always add a Frontend-project later on.

https://github.com/IdentityServer/IdentityServer4.Templates

**Comment by richmhouse** [comment]
Apologies Mohammad . A temporary unrelated deployment problem. It's back up again now. Yes it's deployed to https://alpacabiriba.com. 

Is the "login" subdomain something that is needed by Identity Server 4 or something you've decided to use in your specific application?

I also tried https://www.alpacabiriba.com without luck. The razor pages work fine (login, register, amend user details) - it's the angular component calling the weather forecast web-api that doesn't work. 

Thanks for the suggestion about using the templates provided by IdentityServer4 - I'll give them a go.

**Comment by imt-s1897** [comment]
> Is the "login" subdomain something that is needed by Identity Server 4 or something you've decided to use in your specific application?

No, not needed.

> I also tried https://www.alpacabiriba.com without luck. The razor pages work fine (login, register, amend user details) - it's the angular component calling the weather forecast web-api that doesn't work.

So maybe it's not a PublicOrigin-issue in Azure Linux webb app environments, and instead something specific to the template used. You could head over to the ASP.NET Core repo as suggested by Dominick.

**Comment by richmhouse** [comment]
I've got it working. I found an info message in the logs saying "Failed to determine the https port for redirect."
and set ASPNETCORE_HTTPS_PORT to 5001 in the App Service configuration. Thanks for your help Mohammad.

**Comment by imt-s1897** [comment]
> Failed to determine the https port for redirect."
> and set ASPNETCORE_HTTPS_PORT to 500

Could you please try it without the PublicOrigin-property being set and see if that in fact made a difference?

**Comment by drma-dev** [comment]
Hi, I've been experiencing this problem for a long time. But I'm using blazor, in this case.

I tried this configuration: ASPNETCORE_HTTPS_PORT: 5001, but there was no effect (which I think is strange, because there is no port configured in azure).
