### ISSUE TITLE
Upgrade to version 4 stable release breaks build

### ISSUE THREAD

**Issue by EggheadPrez** [IdentityServer/IdentityServer4#4539]
### Question
Using visual studio 2019, upgrade identityServer4 to 4.0 stable release through package manager.   Now have 11 build errors

### Minimal working example

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'AuthorizationRequest' does not contain a definition for 'ClientId' and no accessible extension method 'ClientId' accepting a first argument of type 'AuthorizationRequest' could be found (are you missing a using directive or an assembly reference?)	IdentityServer	\Account\ExternalController.cs	141	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'ConsentResponse' does not contain a definition for 'Denied'	IdentityServer	Account\AccountController.cs	91	Active

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by brockallen** [comment]
Yes, a major version update can contain breaking changes. Here's a list of the updates:

https://github.com/IdentityServer/IdentityServer4/releases/tag/4.0.0

and here's some info about the resource changes:

https://identityserver4.readthedocs.io/en/latest/topics/resources.html#migration-steps-to-v4

**Comment by EggheadPrez** [comment]
thanks brockallen!

**Comment by EggheadPrez** [comment]
@brockallen will there be updates to the documentation soon?  Just wondering if I should go ahead and work my way through the changes from v3 to v4, or just wait for updated documentation and start from scratch.
