### ISSUE TITLE
Authorize with roles and claims.

### ISSUE THREAD

**Issue by pfonyad** [IdentityServer/IdentityServer4#4544]
Hi,

I'm stuck with authorization in API. I want to use [Authorize(Roles = "some_role")] attribute in my API. I succesfully configured the IdentityServer4 to use PostgreSql via EntityFramework and use AddAspNetIdentity with my custom user which inherit from IdentityUser and use Postgres also. Quickstart 5 and 6 were very successful. The problem is the Identity server never send user's roles or claims. I tried a lot of configurations. I did not find any description about this.

Can you help where can i find some description or samle about this.

Thanks,
Peter

**Comment by brockallen** [comment]
Perhaps this? https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by pfonyad** [comment]
I've tried, but not working. The IdentityServer4 don't send any roles. Moreover it send an http page response.

**Comment by rustybox** [comment]
Some links that may help you

https://github.com/IdentityServer/IdentityServer4/issues/4087
https://themisir.com/adding-role-claim-to-identity-server-4/

The blog post is a tad confusing as author suggests he subclasses IdentityServer4.AspNetIdentity.UserClaimsFactory which is unlikely as it is internal so i'm asuming really he is subclassing Microsoft.AspNetCore.Identity.UserClaimsPrincipalFactory

You can also see https://github.com/IdentityServer/IdentityServer4/issues/1786 where there are a couple of other options including implementing your own IProfileService (seems over the top as that just calls into UserClaimsPrincipalFactory)
