### ISSUE TITLE
_clientStore.IsPkceClientAsync

### ISSUE THREAD

**Issue by ahedreville** [IdentityServer/IdentityServer4#4545]
### Question
_clientStore.IsPkceClientAsync is not longer avaliable on Quickstart.UI?
Should I replace it with context.IsNativeClient())

### i.e.

```csharp
   if (await _clientStore.IsPkceClientAsync(context.Client.ClientId))
vs
   if (context.IsNativeClient())
```

**Comment by leastprivilege** [comment]
If you need that functionality - yes, this is the replacement.

**Comment by tmaxcoded** [comment]
i solved it by using this 

                    if(context.Client.RequirePkce)
                    {
                        return Redirect("https://localhost:44778/Home/Index");
                    }
