### ISSUE TITLE
Support for ECDsa

### ISSUE THREAD

**Issue by bergben** [IdentityServer/IdentityServer4#4550]
### Question
I am currently running into the exact scenario described here by Dominick: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1291#issue-516246389 

I think a fix is available, Brent recently modified the Milestone in the issue linked to 6.6.0 which has already been released. Does this mean that the next release of IdentityServer4 will include this fix? Or is it already included with 4.0? 

Not sure if [this line is the right place to look](https://github.com/IdentityServer/IdentityServer4/blob/main/src/Directory.Build.targets#L44), but if so then I think it is not updated to 6.6.0 yet, probably because it includes some breaking changes?

A short info on the subject would be great, thank you!

**Comment by leastprivilege** [comment]
6.x has a couple of breaking changes and we didn't update to it. The next release will probably use it..
