### ISSUE TITLE
If we have a custom PersistedGrantStore implementation (non-EF based), how can we leverage TokenCleanupService?

### ISSUE THREAD

**Issue by SpiritBob** [IdentityServer/IdentityServer4#4551]
We've got a lot of stale entries in the database. It'd be great if we could somehow use an interface for a `TokenCleanupService` which IdentityServer4 can use.

**Comment by Peperud** [comment]
You'll have to do it yourself. 
Token cleanup doesn't seem to be a first class service. The built-in one is rather an implementation detail of the EF storage.
https://github.com/IdentityServer/IdentityServer4/issues/3116#issuecomment-481830039

**Comment by SpiritBob** [comment]
That's what I'd love to do!

The question is - is it currently possible to do so? If we've got no interface to inject our own TokenCleanupService, what is the solution?

Is it to create our own `IOperationalStoreNotification` interface? Does the builder support injecting a custom `IOperationalStoreNotification`?
