### ISSUE TITLE
Confusing API/property PersistedGrant.ConsumedTime

### ISSUE THREAD

**Issue by BorisWilhelms** [IdentityServer/IdentityServer4#4553]
### Question
The `PersistedGrant` type contains the property `ConsumedTime` which looks like a general purpose property for persisted grants. But the property is actually a write-only property and only set for RefreshTokens. But in order to invalidate/mark refresh tokens as consumed the actual data in the `data` property must be changed. The `ConsumedTime` property on `PersistedGrant` is ignored on reads.

Since the property is never used, I am wondering what the purpose of the `ConsumedTime` property on `PersistedGrant` is and if its actually needed/used. If not used/needed please consider removing the property to make the API more clear.

**Comment by brockallen** [comment]
Strictly speaking most (if not all) of thew columns are that way, no?

**Comment by BorisWilhelms** [comment]
Not sure if this question is addressed to me, but I don't know if this affects also other columns.

**Comment by brockallen** [comment]
What I was getting at is that all the columns except for the key act in the same way. They are all read only copies of the payload in the JSON data column.
