### ISSUE TITLE
Authentication fails when running IdentityServer on a non-https address

### ISSUE THREAD

**Issue by JohanPetersson** [IdentityServer/IdentityServer4#4555]
### Issue / Steps to reproduce the problem

* Install in-memory template and run the project on a non-https address
* Log in just locally,
* or set up an external client and challenge an authentication

#### Expected

User is logged in and cookies are set and user is redirected back to the client (if applicable).

#### Actual

Login view is just loaded again without any error message or cookies set (except for antiforgery).

When running the project on https everything seems to work. Everything seems fine in the AccountController but when user gets redirected to `/connect/authorize/callback` after successful login nothing happens.

### Relevant parts of the log file

```
info: IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator[0]
      Showing login: User is not authenticated
info: IdentityServer4.Events.DefaultEventService[0]
      {
        "Name": "User Login Success",
        "Category": "Authentication",
        "EventType": "Success",
        "Id": 1000,
        "Username": "bob",
        "SubjectId": "88421113",
        "DisplayName": "bob",
        "Endpoint": "UI",
        "ClientId": "xxx",
        "ActivityId": "0HM0MPUOL1H5S:00000002",
        "TimeStamp": "2020-06-22T17:30:29Z",
        "ProcessId": 40484,
        "LocalIpAddress": "::1:44360",
        "RemoteIpAddress": "::1"
      }
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeCallbackEndpoint for /connect/authorize/callback
info: IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator[0]
      Showing login: User is not authenticated
```

**Comment by leastprivilege** [comment]
That's probably because the browser does not accept SameSite=none cookies without the secure flag.

**Comment by JohanPetersson** [comment]
Thank you for pointing me in the right direction. IdentityServer seems to explicitly set the cookie options when appending cookies? I tried to disable SameSite=none but that didn't work:

```
services.Configure<CookiePolicyOptions>(options =>
{
    options.MinimumSameSitePolicy = SameSiteMode.Unspecified;
    options.OnAppendCookie = ctx =>
    {
        ctx.CookieOptions.SameSite = SameSiteMode.Unspecified;
    };
});
```
```
app.UseCookiePolicy();
app.UseAuthentication();
app.UseAuthorization();
```

SameSite is still set on the cookie. I will obviously not do this in production, but for various reasons I need to run this on http locally.

**Comment by JohanPetersson** [comment]
Above solution actually worked. Not sure why it didn't first time I tested.

Thank you again!
