### ISSUE TITLE
Allow authorization code flow without passing scopes 

### ISSUE THREAD

**Issue by jceresini** [IdentityServer/IdentityServer4#4556]
I saw from looking at closed issues that this is by design: https://github.com/IdentityServer/IdentityServer4/issues/4254#issuecomment-609029124

I just wanted to bring another use case to see if you're willing to reconsider your stance.

I'm interested in using IS4 to authenticate an internal private terraform module directory. The "terraform login protocol" doesn't send a scope. Even if we ask them to update their application to include `scope`, and even if they accept it and release it, we wont be able to provide terraform modules until everyone updates their terraform client.

Some details terraform login:
* https://www.terraform.io/docs/internals/login-protocol.html
* https://www.terraform.io/docs/commands/login.html#protocol-v1

If we could allow authorization code flow without a scope, we could build a service that works with `terraform login <our_service_hostname>`, and all of our customers could use our modules using our existing authentication platform.

I'm sure its already been mentioned, but what im asking for is valid for Oauth2:
* https://tools.ietf.org/html/rfc6749#section-4.1.1
* https://tools.ietf.org/html/rfc6749#section-3.3

>   If the client omits the scope parameter when requesting
>   authorization, the authorization server MUST either process the
>   request using a pre-defined default value or fail the request
>   indicating an invalid scope.  The authorization server SHOULD
>   document its scope requirements and default value (if defined).

**Comment by leastprivilege** [comment]
We know that omitting scopes in OAuth is valid - but not in OIDC. That's why we decided to always require a scope parameter at the authorize endpoint.

We can take this into future consideration.

**Comment by brockallen** [comment]
We don't plan on implementing this. It's not trivial. Sorry.

**Comment by jceresini** [comment]
For our use case, terraform accepted our PR to supply scopes. Thanks for reconsidering it though
