### ISSUE TITLE
Support of CancellationToken

### ISSUE THREAD

**Issue by ylabade** [IdentityServer/IdentityServer4#4557]
This is a feature request to add the support of CancellationToken.

**Comment by leastprivilege** [comment]
Can you name some scenarios where you would need/benefit from the cancellation token?

**Comment by ylabade** [comment]
I'm having trouble understanding your question. In many cases it is important to take into account the cancellation of requests.

In my case for example, my user repository is completely externalized and accessible via HTTP. In this case, it's preferable that the profile service allows to receive a cancellation token to allow the cancellation of HTTP calls in case the client cancels the request (HttpClient supports cancellation). The same is true for database queries (Entity Framework also supports cancellation).

https://stackoverflow.com/a/54199137

**Comment by leastprivilege** [comment]
..and what would be the cancellation source?

**Comment by ylabade** [comment]
All the logic is already present with ASP.NET Core. There is a property accessible directly on the HttpContext: https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httpcontext.requestaborted?view=aspnetcore-3.1

or via the feature IHttpRequestLifetimeFeature : 

```cs
var cancellationToken = context.Features.Get<IHttpRequestLifetimeFeature>()?.RequestAborted ?? default;
```

**Comment by leastprivilege** [comment]
Yes  I am aware of all that. Just curious about your use case.

Since this is a massive breaking change, we cannot do it right now. But we will consider it for the future.

**Comment by leastprivilege** [comment]
..or IOW - to "unblock" you, you can retrieve the cancellation token directly from the context before you make your outbound HTTP calls. No need to for us to propagate it.

**Comment by ylabade** [comment]
Is there any chance to re-open this issue and pin it? Thank you

**Comment by thomasfrisko** [comment]
We would also appreciate support for CancellationToken. Especially in the interfaces interacting with EntityFramework since it is currently not possible to cancel database operations.
