### ISSUE TITLE
Abstraction of user storage

### ISSUE THREAD

**Issue by wijnsema** [IdentityServer/IdentityServer4#456]
AFAIK the two starting options for having a user interface with login/external login/logoff in Identity Server 4 are 

1. start from scratch (and maybe start with IdentityServer4.Quickstart.UI)
2. start with the ASP.NET Identity template in Visual Studio

Option 2, using the Identity template might be a possible choice for a greenfield project, but still you pull in a lot of code of which you only use parts. More importantly, Microsoft has refactored this template many times the last couple of years, leaving many developers (including me) with incompatible user databases. Maybe things have settled down a bit but I'm reluctant to step on this bandwagon again.

Back to option 2 then, starting from scratch. With all the functionality Identity Server has, this still leaves me with a lot of work. I have to implement

- `IResourceOwnerPasswordValidator`
- `IProfileService`

which is not to hard. But for the user interface I will also need some `CustomUserLoginService` which interacts with the AccountController, and my AccountController is now different from the template, making future updates more difficult.

Things would be far more easy if the user store would be abstracted behind a suitable interface. At the moment the user store is implemented as

```
List<InMemoryUser>
 
public class InMemoryUser
{
	public bool Enabled { get; set; } = true;
	public string Subject { get; set; }
	public string Username { get; set; }
	public string Password { get; set; }
	public string Provider { get; set; }
	public string ProviderId { get; set; }
	public ICollection<Claim> Claims { get; set; } = new HashSet<Claim>(new ClaimComparer());
}
```
My suggestion is to create an interface for the persistence of the users like this:
```
interface IUser
{
	string Subject { get; set; }
	string Username { get; set; }
	string Provider { get; set; }
	string ProviderId { get; set; }
	ICollection<Claim> Claims { get; set; }
}

interface IUserStore
{
	IUser FindByUsername(string username);
	IUser FindByExternalProvider(string provider, string userId);
	bool ValidateCredentials(string username, string password);
	bool IsActive(IUser user);
	void AddUser(IUser user);
}
```
The implementation within Identity Server is really easy, only `InMemoryUserProfileService`, `InMemoryUserResourceOwnerPasswordValidator` and `InMemoryUserLoginService` need a slighty other (easier?) implementation, and a better name, given the more abstract nature.

Implementation of the iUserStore for us developers/implementators is easy too, just hook in your database (or whatever storage you have) and write a couple of methods. No need to implement `IResourceOwnerPasswordValidator' and `IProfileService', no need to write you custom login service and tweak the AccountController.

I think this might be a big win for the ease of implementation of Identity Server, and at the same is a good step in abstracting the UI, or facilitate multi-tenant implementations.

Warning: The mentioned interfaces are not tested and might be incomplete and are for demonstration purposes only.

Disclaimer: I'm new to Identity Server so I might have overlooked information.

Kinds Regards and thanks for this nice piece of software,

Ronald Wijnsema

**Comment by brockallen** [comment]
> But for the user interface I will also need some CustomUserLoginService which interacts with the AccountController, and my AccountController is now different from the template, making future updates more difficult.

This class is more for the quickstart templates backed by the in-mem users. For your scenario you'd just take over 100% control of the UI and how it contacts your custom database for the users to login. At least that's how we were planning on people being able to do what you want.

**Comment by wijnsema** [comment]
The underlying problem which I tried to solve with the IUserStore is precisely that I do not want 100% control of the UI! It's a waste of time to write a UI for login if this exactly the same for 90% of other implementations. If the UI was part of the Identity Server framework it would be easier to implement, and implementations would be more robust.

For this the UI should be abstracted in some way. This might be beyond the scope of Identity Server.

A quick fix could be a 'defacto' UI, covering commonly used parts, approved by the Identity Server team? For this, the IUserStore would help.

Another possibility is an AccountController as part of Identity Server. Developers could override or extend this. The Views could be under 100% controls of the developers.

**Comment by brockallen** [comment]
Fair point. We moved away from the built-in UI we had in IdentityServer3 since most of the time people needed to customize it. But I also see your side... I think we considered having a pre-built UI layer (much like IdentityServer3) to put on top of the IdentityServer4 model... but we just haven't gotten there yet. The quiskstart UI was short-term solution.

**Comment by wijnsema** [comment]
What would be ideal is some kind of default UI where you could replace parts of the layout or behavior. Unfortunately, the way the MVC framework works with Controllers and View makes this very difficult. One thing that could help is break it up into smaller parts. I have some ideas for this, maybe I'll open a new case for this later. In the mean time I'll leave you to it.

Back to the iUserStore. I couldn't resist to experiment a little more with this. I implemented the `IResourceOwnerPasswordValidator`, the `IProfileService` and `QuickstartUiAccountControllerUserLoginService`. This was very easy and it feels very 'natural' to work with a IUserStore. 

I realize that the QuickstartUi is precisely a quickstart, but the less the complexity and the more  interchangeability, the better. Also, IUserStore helps with `IResourceOwnerPasswordValidator` and  `IProfileService` too.

```c#
public interface IUser
{
	string Subject { get; set; }
	string Username { get; set; }
	string Provider { get; set; }
	string ProviderId { get; set; }
	bool Enabled { get; set; }
	ICollection<Claim> Claims { get; set; }
}
public interface IUserStore
{
	IUser FindByUsername(string username);
	IUser FindBySubject(string subject);
	IUser FindByExternalProvider(string provider, string userId);
	bool ValidateCredentials(string username, string password);
	bool IsActive(IUser user);
	IUser AddUser(string username, string provider, string providerId, ICollection<Claim> claims);
}

public class ResourceOwnerPasswordValidator : IResourceOwnerPasswordValidator
{
	private readonly IUserStore userstore;

	public ResourceOwnerPasswordValidator(IUserStore userstore)
	{
		this.userstore = userstore;
	}

	public Task ValidateAsync(ResourceOwnerPasswordValidationContext context)
	{
		if (userstore.ValidateCredentials(context.UserName, context.Password))
			context.Result = new GrantValidationResult(userstore.FindByUsername(context.UserName).Subject, "password");
		else
			context.Result = new GrantValidationResult(TokenRequestErrors.InvalidGrant, "invalid username/password");
		return Task.FromResult(0);
	}
}

public class ProfileService : IProfileService
{
	private readonly IUserStore userstore;

	public ProfileService(IUserStore userstore)
	{
		this.userstore = userstore;
	}

	public Task GetProfileDataAsync(ProfileDataRequestContext context)
	{
		var user = userstore.FindBySubject(context.Subject.GetSubjectId());
		context.IssuedClaims.Add(new Claim(JwtClaimTypes.Subject, user.Subject));
		context.AddFilteredClaims(user.Claims);
		return Task.FromResult(0);
	}

	public Task IsActiveAsync(IsActiveContext context)
	{
		if (context.Subject == null)
			throw new ArgumentNullException("subject");
		return Task.FromResult(0);
	}
}

public class QuickstartUiAccountControllerUserLoginService
{
	private readonly IUserStore userstore;

	public QuickstartUiAccountControllerUserLoginService(IUserStore userstore)
	{
		this.userstore = userstore;
	}

	public bool ValidateCredentials(string username, string password)
	{
		return userstore.ValidateCredentials(username, password);
	}

	public IUser FindByUsername(string username)
	{
		return userstore.FindByUsername(username);
	}

	public IUser FindByExternalProvider(string provider, string userId)
	{
		return userstore.FindByExternalProvider(provider, userId);
	}

	public IUser AutoProvisionUser(string provider, string userId, List<Claim> claims)
	{
		var filtered = NormalizeClaimsFromExternalProvider(claims);
		var name = filtered.FirstOrDefault(c => c.Type == JwtClaimTypes.Name)?.Value;
		return userstore.AddUser(name, provider, userId, filtered);
	}

	ICollection<Claim> NormalizeClaimsFromExternalProvider(ICollection<Claim> claims)
	{
		// create a list of claims that we want to transfer into our store
		var filtered = new List<Claim>();

		foreach (var claim in claims)
		{
			// if the external system sends a display name - translate that to the standard OIDC name claim
			if (claim.Type == ClaimTypes.Name)
			{
				filtered.Add(new Claim(JwtClaimTypes.Name, claim.Value));
			}
			// if the JWT handler has an outbound mapping to an OIDC claim use that
			else if (JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap.ContainsKey(claim.Type))
			{
				filtered.Add(new Claim(JwtSecurityTokenHandler.DefaultOutboundClaimTypeMap[claim.Type], claim.Value));
			}
			// copy the claim as-is
			else
			{
				filtered.Add(claim);
			}
		}

		// if no display name was provided, try to construct by first and/or last name
		if (!filtered.Any(x => x.Type == JwtClaimTypes.Name))
		{
			var first = filtered.FirstOrDefault(x => x.Type == JwtClaimTypes.GivenName)?.Value;
			var last = filtered.FirstOrDefault(x => x.Type == JwtClaimTypes.FamilyName)?.Value;
			if (first != null && last != null)
			{
				filtered.Add(new Claim(JwtClaimTypes.Name, first + " " + last));
			}
			else if (first != null)
			{
				filtered.Add(new Claim(JwtClaimTypes.Name, first));
			}
			else if (last != null)
			{
				filtered.Add(new Claim(JwtClaimTypes.Name, last));
			}
		}

		return filtered;
	}
}
```

While we're at it, let's implement the IUserStore for a SimpleMembership (Microsoft user acounts in the default Web Application template, back in 2012) SQL Server database:

```c#
public class User : IUser
{
	public string Subject { get; set; }
	public string Username { get; set; }
	public string Provider { get; set; }
	public string ProviderId { get; set; }
	public bool Enabled { get; set; } = false;
	public ICollection<Claim> Claims { get; set; }
}

public class UserStore : IUserStore
{
	private readonly SomeSimpleMembershipContext db;

	public UserStore(SomeSimpleMembershipContext db)
	{
		this.db = db;
	}

	public IUser FindByUsername(string username)
	{
		var persoon = db.Persoon.FirstOrDefault(p => p.Email.ToLower() == username);
		if (persoon == null)
			return null;
		var user = db.WebpagesMembership.FirstOrDefault(u => u.UserId == persoon.Id);
		return new User
		{
			Subject = user.UserId.ToString(),
			Username = persoon.Email
		};
	}

	public IUser FindByExternalProvider(string provider, string userId)
	{
		var t = db.WebpagesOauthMembership.FirstOrDefault(x => x.Provider == provider && x.Provider == userId);
		if (t == null)
			return null;
		var persoon = db.Persoon.Find(t.UserId);
		return new User
		{
			Subject = t.UserId.ToString(),
			Provider = provider,
			ProviderId = t.ProviderUserId,
			Username = persoon.Email
		};
	}

	public IUser FindBySubject(string subject)
	{
		var persoon = db.Persoon.Find(int.Parse(subject));
		if (persoon == null)
			return null;
		return new User
		{
			Subject = persoon.Id.ToString(),
			Username = persoon.Email
		};
	}

	public bool IsActive(IUser user)
	{
		return true;
	}

	public bool ValidateCredentials(string username, string password)
	{
		var user = FindByUsername(username);
		var wpm = db.WebpagesMembership.Find(int.Parse(user.Subject));
		if (wpm == null)
			return false;
		return SimpleMembershipPasswordHasher.VerifyHashedPassword(wpm.Password, password);
	}

	public IUser AddUser(string username, string provider, string providerId, ICollection<Claim> claims)
	{
		var person = new Persoon { Email = username };
		db.Persoon.Add(new Persoon { Email = username });
		if (provider != null)
			db.WebpagesOauthMembership.Add(new WebpagesOauthMembership { UserId = person.Id,  Provider = provider, ProviderUserId = providerId });
		db.SaveChanges();
		return new User
		{
			Subject = person.Id.ToString(),
			Username = person.Email,
			Provider = provider,
			ProviderId = providerId,
			Claims = claims
		};
	}
}
```
If you're still with me, change the services part of `startup.cs` to 
```c#
services.AddMvc();

services.AddDbContext<SomeSimpleMembershipContext >();

var builder = services.AddDeveloperIdentityServer();
builder.AddInMemoryClients(Config.GetClients());
builder.AddInMemoryScopes(Config.GetScopes());

builder.Services.AddTransient<IUserStore, UserStore>();
builder.Services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();
builder.Services.AddTransient<IProfileService, ProfileService>();
builder.Services.AddTransient<QuickstartUiAccountControllerUserLoginService>();
```
One final change to AcountController is to replace the line

`private readonly InMemoryUserLoginService _loginService;`
with
`private readonly QuickstartUiAccountControllerUserLoginService _loginService;`

Done! I did a few tests and this seems to work well. 

If IUserStore, or a similar abstraction, was part of Identity Server 4, it would be even more easy to plug in your user database. InMemoryUsers are still possible if you implement `IUserStore` based on `List<InMemoryUser>`, which is a trivial.

A few things to note:
- The subject is left out of the AddUser method, This is done on purpose: Generation of the key is left to the IUserStore. The subject is returned, so the subject is known to the caller of AddUser.
- Nothing has been done with the additional Claims for now.

**Comment by brockallen** [comment]
Changing the label, but no guarantees. We envision adding a UI library at some point -- perhaps this could be rolled into that./

**Comment by leastprivilege** [comment]
No plans for 1.0

Feel free to open a new issue based on 1.0 desifgn
