### ISSUE TITLE
Need a way to change base path for openid-configuration

### ISSUE THREAD

**Issue by TFisherInComm** [IdentityServer/IdentityServer4#4563]
We are using a proxy setup that uses consul dns to look up services based on a tag name to tell the proxy where to route the call. Our IdentityService is setup at {baseuri}/identity. Hence all of our endpoint paths need to have the same construction so that the proxy knows where to route them. The proxy in question strips the service discovery key (in this case "/identity") out of the path before forwarding the request. This used to be possible with the PublicOrigin setting, but with it's removal, that is no longer possible. We have already solved the other problems that the PublicOrigin used to be used as a workaround for using the forward headers that our proxy is properly applying, but this issue does not have as simple an answer.

It would be nice if there were an property on the IdentityServerOptions object to add to the basepath used in the construction of the endpoint urls to help with issues like this one. 

I've  gone down several paths of trying to force in new path information and to have the proxy not strip out the service key. The former are less maintainable and viable, the later are a serious change to our proxy config that would impact all services.

I'm more than willing to submit a PR on this myself if there is no major concern with idea.

quick edit-

It looks like our proxy server IS adding an x-forwarded-pathbase  that could also be used to fill in the above information, but there is not suport for that header built in to dotnet core and it would require a little work, again, I'd be willing to do the work on this.

**Comment by TFisherInComm** [comment]
Just closing this as I have worked out something else, and would probably be told to do that anyway, thanks!

**Comment by leastprivilege** [comment]
Have you tried `app.UseBasePath`  ?
