### ISSUE TITLE
v4 API Scopes, API Resources and Introspection

### ISSUE THREAD

**Issue by Peperud** [IdentityServer/IdentityServer4#4565]
v4 introduces the concept of "free" scopes and scopes, that belong to API resources.
The [documentation](https://identityserver4.readthedocs.io/en/latest/topics/resources.html) presents the API resources as a way to deal with growing number of api scopes by organizing them together in a logical/functional way. Great.

However, it seems that with reference tokens, one still cannot use the simpler, "free scopes" way. Even if having to deal only with a handful of scopes. The reference token would need to be validated server side and secrets are at "resource" level.

Am I correct?  

Makes me wonder what need did this breaking change satisfy?

**Comment by leastprivilege** [comment]
Yes - for introspection you need an ApiSecret - and that is part of a resource definition.
