### ISSUE TITLE
Quickstart sample cannot build

### ISSUE THREAD

**Issue by boskjoett** [IdentityServer/IdentityServer4#4567]
**We can only help you if you are on the latest version. Either use the latest 2.x or 3.x**

Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](http://docs.identityserver.io/en/latest/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

I cloned the IdentityServer4 repo to my local PC and load this solution into Visual Studio 2019 Enterprise Edition:
IdentityServer4\samples\Quickstarts\3_AspNetCoreAndApis\Quickstart.sln

When I do a "Rebuild All" in Visual Studio I get this error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'c:\Temp\Zylinc\IdentityServer4\samples\Quickstarts\3_AspNetCoreAndApis\src\IdentityServer\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	IdentityServer	C:\Program Files\dotnet\sdk\3.1.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
```

It would be nice if the QuickStart solution would just compile in VS2019 without any additional steps.

I haven't yet found out how to do a NuGet restore to fix the issue, so I have to quit spending more time on IdentityServer4.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
@leastprivilege told ya

**Comment by leastprivilege** [comment]
Sorry - I can't repro that.

Do you have the right SDK installed per global.json?

**Comment by boskjoett** [comment]
I can build everything if I run build.ps1 or build.sh in the root folder.
But if I do a clean git clone of the repo and opens 
IdentityServer4\samples\Quickstarts\3_AspNetCoreAndApis\Quickstart.sln
in Visual Studio the solution will not build.
It is a minor issue, but still a bit confusing.

**Comment by leastprivilege** [comment]
The quickstarts are unrelated to the build. I still can't repro it.

**Comment by boskjoett** [comment]
Feel free to close this issue then.
