### ISSUE TITLE
IPersistedGrantStore vs individual stores

### ISSUE THREAD

**Issue by rajeshaz09** [IdentityServer/IdentityServer4#4570]
### Question
Operational data can be stored in DB implementing either **IPersistedGrantStore** or individual stores (IAuthorizationCodeStore, IRefreshTokenStore, IReferenceTokenStore, IUserConsentStore ). As of now we are using IPersistedGrantStore and storing in documentDB. But V4.0 introduced **PersistedGrantFilter** which is very difficult to query with document database. 

We are planning to use individual stores (IAuthorizationCodeStore, IRefreshTokenStore, IReferenceTokenStore, IUserConsentStore ).
Do you have plans to **deprecate** individual stores in near future? What is the recommended approach?

**Comment by brockallen** [comment]
> Do you have plans to deprecate individual stores in near future? 

No, but the default implementation of them rely upon the IPersistedGrantStore. So you if implement them manually, then you lose the benefit of any other services that depend on the IPersistedGrantStore (which seems to only be the default implementation of the IPersistedGrantService).
