### ISSUE TITLE
Unannounced change in signing key kid in 4.0.0

### ISSUE THREAD

**Issue by ArturDorochowicz** [IdentityServer/IdentityServer4#4571]
If someone is migrating from 3.x to 4.0 they should be aware that they need to essentially do a key rollover. That's because the same key is presented at jwks endpoint differently in 3.x and 4.0 (e.g. `"kid": "AB...12"` in 3.x and `"kid": "AB...12RS256"` in 4.0).

I think it'd be better if changes like this were clearly spelled out. Maybe a migration doc?

Sorry, if I have missed an announcement or documentation on this, but I think I have not. (I'm aware of the announcement about supporting multiple signing keys and that the issue here is a result of that, but still, it does not warn about this).

I think I wouldn't check for this if not for a similar issue when I had migrated from IdentityServer3 to IdentityServer4 (back then it was Microsoft who changed the format). I suppose other people might not catch this before deploying. Just wanted to let the problem be known. Feel free to close this.

**Comment by leastprivilege** [comment]
Thanks for pointing this out - that is indeed a breaking change that we probably haven't specifically documented. 

That being said, you are in full control of your keys, by using this overload:

https://github.com/IdentityServer/IdentityServer4/blob/3420873926a94670d8e002efb861f30cb0f74aa3/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs#L30-L65

**Comment by ArturDorochowicz** [comment]
Sure, it's absolutely something that can be done in a straightforward way. You just need to do it "on both sides" of the migration, as far as I understand. 

I should have mentioned that the kid format change happens when using AddSigningCredential with X509Certificate (line 87), not sure about other overloads:
https://github.com/IdentityServer/IdentityServer4/blob/3420873926a94670d8e002efb861f30cb0f74aa3/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs#L76-L91

**Comment by slaneyrw** [comment]
This will also affect key rollover... the AddValidationKey method does not add the algorithm to the KeyId so the KID will change when you move a cert from the primary signing crediential to a validationkey.

https://github.com/IdentityServer/IdentityServer4/blob/3420873926a94670d8e002efb861f30cb0f74aa3/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs#L258-L272

**Comment by leastprivilege** [comment]
Good catch - thanks!

https://github.com/IdentityServer/IdentityServer4/commit/f6f892b7b0f8378566caa773b77d5204c32f97a3
