### ISSUE TITLE
TokenUsage.OneTimeOnly refesh_token with grace

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#4574]
**Is your feature request related to a problem? Please describe.**

There are clients(many) that exist with very fragile internet connections.  The number of times the connection gets dropped before a new refresh_token is delivered has become too high to ignore.  The backend has already committed the new refresh_token but the refresh_token never reaches the client.  Going through a new Authentication/Authorization flow is not a 
business acceptable option.

When the clients make a refresh_token request and it fails they will attempt to do it again.   The only thing they have in their possession is that old refresh_token and it needs to work (within reason).

**Describe the solution you'd like**
```
client_configuration
    SingleUseRefreshToken = true 
    SingleUseRefreshTokenGraceEnable = true
    SingleUseRefreshTokenGraceTTL=3600
    SingleUseRefreshTokenGraceAttempts=10
```

When a new child_refresh_token is created, its parent_refresh_token remains and has knowledge of its child_refresh_token.  
The child_refresh_token also has knowledge of its parent_refresh_token.  

**If a parent_refresh_token comes in, it is gated by the following rules;**
1. Can only be used {SingleUseRefreshTokenGraceAttempts} times, i.e. 10 times before it is trashed.
2. A parent_refresh_token has a {SingleUseRefreshTokenGraceTTL}, i.e. 1 hour.  If a parent_refresh_token comes in past its TTL it is trashed.
3. If a parent_refresh_token comes in, a new child_refresh_token is created and if possible the old_child_refresh_token is trashed.

When a Child_refresh_token comes in, we know that someone got the response so the parent_refresh_token gets trashed.   This child_refresh_token becomes the new parent_refresh_token.  There's a lot of clever ways to do this one like setting the child_refresh_token as a parent and no parent can have an association to another parent.  In this case if the old parent_refresh_token comes in it is trashed because it is pointing to another parent_refresh_token.

**Describe alternatives you've considered**
For security reasons a multi-use refresh_token is not desired.

I can replace the DefaultRefreshTokenService but before I do this I would like to see of this feature would be something IDS would take up.

**Additional context**

**Comment by leastprivilege** [comment]
We made changes to the default RT service to be able to implement this easier. We are not planning to add more features soon - so please go ahead and give it a try yourself. 

I will leave this issue open for future discussion.

**Comment by ghstahl** [comment]
@leastprivilege Thanks.  I will document what I did to get this in.

**Comment by ghstahl** [comment]
I have a [demo IdentityServer4-v4-refresh-token-with-grace](https://github.com/fluffy-bunny/IdentityServer4-v4-refresh-token-with-grace)  with documentation on what I did to implement this.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
