### ISSUE TITLE
Can't get loopback for native app on random port working

### ISSUE THREAD

**Issue by bencyoung** [IdentityServer/IdentityServer4#4580]
### Question

I'm using AddAppAuthRedirectUriValidator to try and get the IdentityModel.OidcClient.Samples\NetCoreConsoleClient working with a random port. However the code at https://github.com/IdentityServer/IdentityServer4/blob/4624ed0aed7f3f3ce9fb2f15147fdf95338e8802/src/IdentityServer4/src/Validation/Default/TokenRequestValidator.cs#L288 is still rejecting the redirect_uri with the below log

Am I doing something obviously wrong? Should I be using a different flow?

### Relevant parts of the log file

10:06:25.410 ERROR ASP.NET Invalid redirect_uri: http://127.0.0.1:53525/
{"ClientId":"native.hybrid", "AllowedRedirectUris":["http:\/\/127.0.0.1\/"], "SubjectId":"anonymous", "RequestedScopes":"", "Raw":{"response_type":"code","nonce":"777719952...","state":"","code_challenge":"JS8jdHpO2ARSL5PJfScW...ob2FKHbA","code_challenge_method":"S256","client_id":"native.hybrid","scope":"openid profile api","redirect_uri":"http:\/\/127.0.0.1:53525\/","response_mode":"form_post"}}
10:06:25.420 ERROR ASP.NET Request validation failed

**Comment by leastprivilege** [comment]
I can't repro. Could you try this sample and see if it works for you

https://github.com/IdentityServer/IdentityServer4/blob/ae7a1c146964b7e41025962f1d42a26ed5421a99/samples/Clients/src/ConsoleCode/Program.cs

**Comment by bencyoung** [comment]
Thanks for taking a look. I think the issue is with our IdentityServer based "federation gateway microservice" but I can't see what else I need to configure. The service registration looks like:

```csharp
            services.AddIdentityServer(opts =>
                {
                    var baseUrl = this.configuration.BaseOrigin;
                    if (baseUrl is object)
                    {
                        opts.PublicOrigin = baseUrl.Scheme + Uri.SchemeDelimiter + baseUrl.Authority;
                    }

                    opts.UserInteraction.ErrorUrl = "/account/error";
                    opts.UserInteraction.LoginUrl = "/account/login";
                    opts.UserInteraction.LogoutUrl = "/account/logout";
                    opts.Discovery.ResponseCacheInterval = 900;

                    // Fix for safari browsers ( below 9 ).
                    opts.Csp.Level = CspLevel.One;

                    // Expiration time is greater than 0 it set with custom time span or set with default value 10hrs.
                    if (this.configuration.CookieExpiry > TimeSpan.Zero)
                    {
                        opts.Authentication.CookieSlidingExpiration = true;
                        opts.Authentication.CookieLifetime = this.configuration.CookieExpiry;
                    }
                })
                .AddAppAuthRedirectUriValidator()
                .AddSigningCredential(this.configuration.SigningCertificate)
                .AddInMemoryIdentityResources(Defaults.GetIdentityResources(this.configuration.ExtraClaims))
                .AddInMemoryApiResources(Defaults.GetApiResources(this.configuration.CustomApiResources, this.configuration.ExtraClaims))
                .AddInMemoryClients(this.configuration.Clients);
```

The clients come from static config. In this case it's:

```json
{
  "Enabled": true,
  "ClientId": "console.pkce",
  "ProtocolType": "oidc",
  "ClientSecrets": [
    {
      "Description": null,
      "Value": "K7gNU3sdo+OL0wNhqo...",
      "Expiration": null,
      "Type": "SharedSecret"
    }
  ],
  "RequireClientSecret": true,
  "ClientName": null,
  "Description": null,
  "ClientUri": null,
  "LogoUri": null,
  "RequireConsent": false,
  "AllowRememberConsent": true,
  "AllowedGrantTypes": [
    "authorization_code"
  ],
  "RequirePkce": false,
  "AllowPlainTextPkce": false,
  "AllowAccessTokensViaBrowser": false,
  "RedirectUris": [
    "http://127.0.0.1/"
  ],
  "PostLogoutRedirectUris": [
    ""
  ],
  "FrontChannelLogoutUri": null,
  "FrontChannelLogoutSessionRequired": true,
  "BackChannelLogoutUri": null,
  "BackChannelLogoutSessionRequired": true,
  "AllowOfflineAccess": true,
  "AllowedScopes": [
    "openid",
    "profile",
    "email",
    "api"
  ],
  "AlwaysIncludeUserClaimsInIdToken": true,
  "IdentityTokenLifetime": 300,
  "AccessTokenLifetime": 3600,
  "AuthorizationCodeLifetime": 300,
  "AbsoluteRefreshTokenLifetime": 2592000,
  "SlidingRefreshTokenLifetime": 1296000,
  "ConsentLifetime": null,
  "RefreshTokenUsage": 1,
  "UpdateAccessTokenClaimsOnRefresh": false,
  "RefreshTokenExpiration": 1,
  "AccessTokenType": 0,
  "EnableLocalLogin": true,
  "IdentityProviderRestrictions": [],
  "IncludeJwtId": false,
  "Claims": [],
  "AlwaysSendClientClaims": true,
  "ClientClaimsPrefix": "",
  "PairWiseSubjectSalt": null,
  "UserSsoLifetime": null,
  "UserCodeType": null,
  "DeviceCodeLifetime": 300,
  "AllowedCorsOrigins": [],
  "Properties": {}
}
```

**Comment by bencyoung** [comment]
Is there something different the example id server does to allow generated ports?

**Comment by leastprivilege** [comment]
I don't know. That's why you should try it.

**Comment by bencyoung** [comment]
By running https://github.com/IdentityServer/IdentityServer4.Demo locally?

**Comment by bencyoung** [comment]
Ah: https://github.com/IdentityServer/IdentityServer4.Demo/blob/main/src/IdentityServer4Demo/DemoRedirectValidator.cs

**Comment by bencyoung** [comment]
Ah but I'm saying that interface isn't the issue as it's the token request validator. Let me see

**Comment by bencyoung** [comment]
I can't get the demo up and running for now (can't access vault from my corp network). I'll try and have a dig and see if I can understand it.

**Comment by leastprivilege** [comment]
No - not the demo.

The host in this repo + the clients in the samples folder.

**Comment by bencyoung** [comment]
I got this working. For future reference:

1) I needed AddAppAuthRedirectUriValidator
2) UsePkce is required
3) The redirect uris have to 127.0.0.1, not localhost and can't end in slashes...

Thanks for the poke in the right direction
