### ISSUE TITLE
Add the ability to delay the receipt of a certificate in the extension method IdentityServerBuilderExtensionsCrypto.AddSigningCredential

### ISSUE THREAD

**Issue by Shazhko-Artem** [IdentityServer/IdentityServer4#4582]
This is a suggestion for a new feature.

### Problem

In my current project, we have several certificate providers, so we use the certificate factory. The problem is that `IdentityServerBuilderExtensionsCrypto.AddSigningCredential` requires a certificate directly, for which we need a certificate factory, but for getting a factory, we need an `IServiceProvider`.

### Solution
We need to add a method overload with the following parameters.
``` C# 
 public static IIdentityServerBuilder AddSigningCredential(this IIdentityServerBuilder builder, Func<IServiceProvider, X509Certificate2> factory, string signingAlgorithm = SecurityAlgorithms.RsaSha256)
```

### Similar existing solutions

A similar solution already exists for `DataProtectionBuilderExtensions.AddKeyEscrowSink` in the `Microsoft.AspNetCore.DataProtection` project.
``` C#
public static IDataProtectionBuilder AddKeyEscrowSink(this IDataProtectionBuilder builder, Func<IServiceProvider, IKeyEscrowSink> factory){...}
```

**Comment by leastprivilege** [comment]
You want to implement the `ISigningCredentialStore` or `IKeyMaterialService` - depending on the level of control you need.

**Comment by Shazhko-Artem** [comment]
So, should I implement the `ISigningCredentialStore` and register it instead of calling the extension `AddSigningCredential`? Now we use the workaround and created our extension method `AddSigningCredential` in which we did the following:
``` C#
builder.Services.AddSingleton<ISigningCredentialStore>(provider =>
{
    var credential = factory(provider);
    return new DefaultSigningCredentialsStore(credential);
});
```
It would be cool if the IdentityServer4 package initially provided something like that.
