### ISSUE TITLE
How to authenticate against multiple Azure ADs silently

### ISSUE THREAD

**Issue by cdecinkoKnight** [IdentityServer/IdentityServer4#4585]
We have multiple Azure Active Directories for various business units in our company. We would like to standardize on a single sign on, single login environment such as using IDS4. How could we connect each of those, I'm assuming, external directories, such that the user does not have to click the appropriate one on the login page?  Would like the login to check each one silently until it finds the user with no user interaction OR best would be to check the username/email domain of the user and use the AAD associated with that domain or subdomain.

**Comment by leastprivilege** [comment]
If with "silent" you mean Windows integrated authentication - this is not possible, because a Windows Server can only be joined to a single domain.

**Comment by cdecinkoKnight** [comment]
By silent, I mean, kind of a daisy chain of ADs. I enter my username/password and rather than click the appropriate AD to authenticate against, the login just checks each one until it finds me. Or based on my email address, it knows which AD to use.
