### ISSUE TITLE
Docs - Initializing database example improvement

### ISSUE THREAD

**Issue by cirojr** [IdentityServer/IdentityServer4#4586]
I think the "Initialize the database" docs section lacks the code to add ApiScopes.

I'm new to the library, so I followed the docs, configured first time with "in memory" methods and all worked great.

When I did the changes to use entity framework, the result was the "Scope x not found in store" error, like in this issue: https://github.com/IdentityServer/IdentityServer4/issues/4549.

So, I though it will be great to add it in the docs section.

It can save the time to deal with more issues like this one.

If it's really a good idea, I can make a pull request.

**Comment by brockallen** [comment]
You mean this section? https://identityserver4.readthedocs.io/en/latest/quickstarts/5_entityframework.html#initializing-the-database

**Comment by cirojr** [comment]
Yes. Sorry, I should have let it explicit.
