### ISSUE TITLE
Separate IdentityServer4.Models from the main IdentityServer4 project

### ISSUE THREAD

**Issue by StanislavChankov** [IdentityServer/IdentityServer4#4587]
**Is your feature request related to a problem? Please describe.**
I can't use `IdentityServer4.Models` library in a `netstandard2.1` project. I am forced to install the whole nuget to `netcoreapp3.1` project.

**Describe the solution you'd like**
As a developer I want `IdentityServer4.Models` in a separate nuget package built with `netstandard2.1`.
Pros:
1. I will be able to install the nuget package to my project, which depends only on `netstandard2.1` references, instead of having to install it on my startup project, which is `netcoreapp3.1`.
2. The project architecture will have better separation of concerns.
Cons:
1. One more nuget package.

**Additional context**
![image](https://user-images.githubusercontent.com/35253870/85926704-d920a300-b8a9-11ea-866d-d51fc0647dfe.png)

**Comment by leastprivilege** [comment]
I am not following. The is no Model project. But Storage - and that is netstandard2.0

https://github.com/IdentityServer/IdentityServer4/blob/e0bc6889182bc27331a79f259d71ddf487a970ce/src/Storage/src/IdentityServer4.Storage.csproj#L4

**Comment by StanislavChankov** [comment]
Sure, but that's the domain models. I am talking about the entities. Do you think that they does not depend on anything to `netcoreapp`? So they could be separated into different project, which depend only on `netstandard` and therefore could be installed into non-runnable project.

**Comment by leastprivilege** [comment]
You mean the Entity Framework entities?

https://github.com/IdentityServer/IdentityServer4/blob/main/src/EntityFramework.Storage/src/IdentityServer4.EntityFramework.Storage.csproj#L5

**Comment by StanislavChankov** [comment]
That's right. I am sorry I have missed to mention `EntityFramework` entities.
Yes, that's the nuget package i've been looking for - https://www.nuget.org/packages/IdentityServer4.EntityFramework.Storage/
Thank you very much @leastprivilege .
I haven't use the `EntityFramewor`k projects of `IdentityServer4` before, but I am finding the very useful and easy to setup.

I want to thank you about developing this such a useful framework, one of the best assets of ASP.NET Core. Surely It is making the .NET platform one step before other frameworks in OAuth aspect.
Keep going the good work! `IdentityServer4` 🔝

**Comment by StanislavChankov** [comment]
@leastprivilege , I had in mind models like `GrantTypes` and `StandardScopes` from `IdentityServer4.IdentityServerConstants`, which are in https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/src/IdentityServer4.csproj#L5
