### ISSUE TITLE
MTLS AND PKCE can exists at the same time in idsrv4?

### ISSUE THREAD

**Issue by Demon520-coder** [IdentityServer/IdentityServer4#4588]
In our project, there are WPF clients, mobile clients and micro services,the project manager hopes that the WPF side can continue to log in with PKCE, and the microservice side canuse MTLS to achieve two-way authentication.
### Question
1. If identityserver4 uses HTTPS, pkce will not be able to establish a connection with identityserver4. 
2. Can pkce and MTLs exist at the same time?
I‘m looking forward to your answers,thank you very much.

**Comment by leastprivilege** [comment]
I am not following. 

PKCE and MTLS are completely unrelated and both are supported.

**Comment by Demon520-coder** [comment]
Sorry,I have resolved this problem.
