### ISSUE TITLE
Use Bearer token with AddLocalApi

### ISSUE THREAD

**Issue by zyofeng** [IdentityServer/IdentityServer4#4591]
IS there any example on how to use bearer token authentication with addlocal api?

Im switching from 

            services.AddAuthentication(IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationDefaults.AuthenticationScheme)
              .AddIdentityServerAuthentication(options =>
              {
                  options.Authority = Configuration["ServerUrl"];
                  options.RequireHttpsMetadata = true;
                  options.ApiName = "my.api";
                  options.ApiSecret = Configuration["AuthSettings:Secret"];
                  options.EnableCaching = true;
              });

to

            services.AddAuthentication(IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationDefaults.AuthenticationScheme)
              .AddLocalApi(options =>
              {
                  options.ExpectedScope = "my.api";
              });

So the api doesn't have to call itself to validate the token (auth on the same server) but im getting 
System.InvalidOperationException: No DefaultAuthenticateScheme found.

**Comment by leastprivilege** [comment]
Have you read this

https://identityserver4.readthedocs.io/en/latest/topics/add_apis.html

**Comment by zyofeng** [comment]
Yes I have.
In fact my original Bearer token validation was setup this way and working.
Anyway I managed to get it working by looking at the source code


services.AddAuthentication(IdentityServerConstants.LocalApi.AuthenticationScheme).AddLocalApi(options => options.ExpectedScope = "my.api");
