### ISSUE TITLE
Migration from v3 to V4

### ISSUE THREAD

**Issue by jt-pt-dev** [IdentityServer/IdentityServer4#4592]
### Question

I am struggling a little with the migration from v3 to v4. I understand consulting is a paid for option and that is fair, but will a migration doc be released at some point?

My solution followed the Quickstart docs pretty closely for v3. Now with v4 I have changed ApiResources to ApiScopes (as I was getting an 'invalid_scope' error) but now I get 'Audience validation error' when the MVC app calls the Api. Database migrations were run based on  RockSolidKnowledge/IdentityServer4.Migration.Scripts but only needed the new columns in DeviceCodes and PersistedGrants as Api, Clients and Identity resources are run in memory.

**Comment by StefanKoenigMUC** [comment]
would also be interested for a migration guide.

**Comment by brockallen** [comment]
> but now I get 'Audience validation error'

https://identityserver4.readthedocs.io/en/latest/topics/resources.html#apis

**Comment by leastprivilege** [comment]
OK - I pinned this issue.

Please report all migration issues you run into. This can be then used to create a guide at some point. This is a community effort.

**Comment by jt-pt-dev** [comment]
Thank you Brock and Dominick for your replies. I have my solution working now. I will try and summarise my experience in case it helps others or in case I am "doing it wrong" and others can learn.

My system has multiple clients (currently ASP.NET Core web applications and in the future mobile apps). They are related apps in a safety management system for mining/construction/engineering scenarios. Each client basically has its own API. They are relatively simple and small in size. IdentityServer is used for authentication for each app and API and I am using ASPNET Identity. It very similar to the Quickstart examples.

I keep Identity resources, API resources and Clients in `Config.cs` and keep the Operational store in SQL Server. I do this as the resources and clients will change very infrequently and all apps and APIs and IdentityServer will live on the one server.

The relevant part of my v3 `Config.cs` was like the docs:
```
public IEnumerable<ApiResource> Apis =>
	new ApiResource[]
	{
		new ApiResource(configuration["ApiNames:MyActionsApi"], "MyActions API")
	};
```

The relevant part of my v3 `Startup.cs` was:
```
var builder = services.AddIdentityServer()
			.AddInMemoryIdentityResources(config.Ids)
			.AddInMemoryApiResources(config.Apis)
			.AddInMemoryClients(config.Clients)
			.AddOperationalStore(options =>
			{
				options.ConfigureDbContext = b => b.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
				options.EnableTokenCleanup = true;
			})
			.AddAspNetIdentity<ApplicationUser>();
```

I upgraded the Nuget packages to v4 and ran the appropriate migrations scripts from https://github.com/RockSolidKnowledge/IdentityServer4.Migration.Scripts/tree/CreateScripts for my database.

The first problem I had was IdentityServer returned an 'invalid_scope' error. After reading the docs I changed my `Config.cs` Apis from `ApiResource` to `ApiScope`. This solved the 'invalid_scope' error but authentication at the API was failing with 'Audience validation error'. This occurs because "When using the scope-only model, no aud (audience) claim will be added to the token". (https://identityserver4.readthedocs.io/en/latest/topics/resources.html#apis)

I then changed to include BOTH `ApiScope` and `ApiResource` and this solved the problem. I used the same value for Scope name and Resource name. I don't know if this is the "right" solution but it works so far for my simple project.

The relevant part of my v4 `Config.cs`:
```
public IEnumerable<ApiScope> ApiScopes =>
	new ApiScope[]
	{
		new ApiScope(configuration["ApiNames:MyActionsApi"], "MyActions API")
	};

public IEnumerable<ApiResource> ApiResources =>
	new ApiResource[]
	{
		new ApiResource(configuration["ApiNames:MyActionsApi"], "MyActions API")
		{
			Scopes = { configuration["ApiNames:MyActionsApi"] }
		}
	};
```

The relevant part of my v4 `Startup.cs`:
```
var builder = services.AddIdentityServer()
			.AddInMemoryIdentityResources(config.Ids)
			.AddInMemoryApiScopes(config.ApiScopes)
			.AddInMemoryApiResources(config.ApiResources)
			.AddInMemoryClients(config.Clients)
			.AddOperationalStore(options =>
			{
				options.ConfigureDbContext = b => b.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
				options.EnableTokenCleanup = true;
			})
			.AddAspNetIdentity<ApplicationUser>();
```

Hope that helps and I am not leading people in the wrong direction.

**Comment by bryantlikes** [comment]
I have a fairly simple API so I just switched out the ApiResource for ApiScope and it worked fine. The [update blurb](https://identityserver4.readthedocs.io/en/latest/topics/resources.html?highlight=v4#migration-steps-to-v4) was helpful but it would be nice if it was more visible instead of hidden at the bottom of that page. 

I also ran into an issue where the ClientId property was removed from the AuthorizationRequest model and replaced with Client (which has the missing ClientId property) so that was a fairly easy fix. I create a PR for the documentation which still has ClientId in it even though it isn't there. 

Everything else seems to be working fine.

**Comment by zyofeng** [comment]
One of the issue I am encountering, is that version 4.0 is checking Content-Type header for "application/x-www-form-urlencoded"

I'm calling token endpoint from Axios in React Native 0.62 and there are some compatiblity issues with Flipper causing Content-Type header to be stripped out. I understand it's probably not specifically an issue caused by IdentityServer4 but it would be nice if there is a way to disable HasApplicationFormContentType checking.

**Comment by hallidev** [comment]
Few issues I've run into that I'm unsure how to handle:

1:

Current broken code:

```
await _interaction.GrantConsentAsync(context, ConsentResponse.Denied);
```

```ConsentResponse.Denied``` no longer exists, but I'm unsure how to construct a ConsentResponse that means ```Denied```. The old implementation of ```Denied``` looked like this:

```public static ConsentResponse Denied = new ConsentResponse();```

Is an empty ```ConsentResponse``` still the equivalent of ```Denied```?

2: 

Current broken code:

```
await HttpContext.SignInAsync(user.Id, user.UserName, props);
```

I notice that there is now an overload that takes ```IdentityServerUser```, but I'm unfamiliar with this class and how to get an instance of it. I see that there's a constructor that takes ```sub```. Is it enough to just do ```var user = new IdentityServerUser(user.Id)``` and pass that to ```SignInAsync```?

3:

Current broken code:

```
await _events.RaiseAsync(new ConsentGrantedEvent(User.GetSubjectId(), request.Client.ClientId, request.ScopesRequested, grantedConsent.ScopesValuesConsented, grantedConsent.RememberConsent));
```

There used to be a ```ScopesRequested``` property on ```AuthorizationRequest```. I'm not sure what the intended replacement is.

4: Above, @jt-pt-dev links to some SQL scripts for updating the database, but are there Entity Framework migration files available? If so, how do we use them?

**Comment by brockallen** [comment]
> ConsentResponse.Denied no longer exists, but I'm unsure how to construct a ConsentResponse that means Denied.

There's a new DenyConsent API.

**Comment by hallidev** [comment]
@brockallen Gotcha - I will take a look at that. Are there simple answers for my other questions? Was just hoping to get some guidance on the breaking changes.

**Comment by srinijss** [comment]
I am getting the error "Unable to resolve service for type - 'IdentityServer4.Services.IReplayCache' when i run my IdentityServer project after upgrading IdentityServer4 nuget package from 3.1.0 to 4.0.1. Please let me know if you need more details on this. Appreciate any help on this. Would also be interested for a migration guide. Thanks.

**Comment by mikegoatly** [comment]
@hallidev I can help with this question:

> 2:
> 
> Current broken code:
> 
> ```
> await HttpContext.SignInAsync(user.Id, user.UserName, props);
> ```
> 
> I notice that there is now an overload that takes `IdentityServerUser`, but I'm unfamiliar with this class and how to get an instance of it. I see that there's a constructor that takes `sub`. Is it enough to just do `var user = new IdentityServerUser(user.Id)` and pass that to `SignInAsync`?

If you look at the updated quickstart sample you can see an example of how to construct `IdentityServerUser` [here](https://github.com/IdentityServer/IdentityServer4.Quickstart.UI/blob/11e17428a84c08e1cb0f8eb1dd71edaf40925ffd/Quickstart/Account/AccountController.cs#L131).

I suspect you'll be able to answer some of your other questions by looking through the updated quickstart code as well, but I've not had to cross those particular bridges 😄

**Comment by Omotayad** [comment]
Hi, 
I am currently facing this issue after migration, whenever I call the token endpoint. Am i missing a library or configuration? 

An exception was thrown while activating IdentityServer4.Endpoints.TokenEndpoint -> IdentityServer4.Validation.ClientSecretValidator -> IdentityServer4.Validation.SecretValidator -> λ:IdentityServer4.Validation.ISecretValidator[] -> IdentityServer4.Validation.PrivateKeyJwtSecretValidator."

**Comment by leastprivilege** [comment]
https://www.identityserver.com/articles/migrating-your-identityserver4-v3-database-to-identityserver4-v4

**Comment by jinweijie** [comment]
Finished deploying the migration to production yesterday.

The overall migration experience was smooth, thanks to the migration script: https://github.com/RockSolidKnowledge/IdentityServer4.Migration.Scripts

One gotcha was the `PublicOrigin` property was removed in v4, so we didn't find the issue util we deployed to dev environment. Just follow this instruction to replace the `PublicOrigin` with `SetIdentityServerOrigin` method in `Configure` method of `Startup.cs`: https://github.com/IdentityServer/IdentityServer4/issues/4535  (Please be aware that place `SetIdentityServerOrigin` above `UseIdentityServer` method)

Thanks for all the resources and hope this also helps a bit.

**Comment by jinweijie** [comment]
> Few issues I've run into that I'm unsure how to handle:
> 
> 1:
> 
> Current broken code:
> 
> ```
> await _interaction.GrantConsentAsync(context, ConsentResponse.Denied);
> ```
> 
> `ConsentResponse.Denied` no longer exists, but I'm unsure how to construct a ConsentResponse that means `Denied`. The old implementation of `Denied` looked like this:
> 
> `public static ConsentResponse Denied = new ConsentResponse();`
> 
> Is an empty `ConsentResponse` still the equivalent of `Denied`?
> 
> 2:
> 
> Current broken code:
> 
> ```
> await HttpContext.SignInAsync(user.Id, user.UserName, props);
> ```
> 
> I notice that there is now an overload that takes `IdentityServerUser`, but I'm unfamiliar with this class and how to get an instance of it. I see that there's a constructor that takes `sub`. Is it enough to just do `var user = new IdentityServerUser(user.Id)` and pass that to `SignInAsync`?
> 
> 3:
> 
> Current broken code:
> 
> ```
> await _events.RaiseAsync(new ConsentGrantedEvent(User.GetSubjectId(), request.Client.ClientId, request.ScopesRequested, grantedConsent.ScopesValuesConsented, grantedConsent.RememberConsent));
> ```
> 
> There used to be a `ScopesRequested` property on `AuthorizationRequest`. I'm not sure what the intended replacement is.
> 
> 4: Above, @jt-pt-dev links to some SQL scripts for updating the database, but are there Entity Framework migration files available? If so, how do we use them?

for #1
maybe:
```
grantedConsent = new ConsentResponse { Error = AuthorizationError.AccessDenied };
```

for #3: 
maybe:
```
await _events.RaiseAsync(new ConsentDeniedEvent(User.GetSubjectId(), request.Client.ClientId, request.ValidatedResources.RawScopeValues));
```

**Comment by MCFHTAGENTS** [comment]
Hi, I am using the 
`PublicOrigin `option in my call to `AddIdentityServer`. Can someone tell me where that has gone in version 4?

Thank you

**Comment by hiwjcn** [comment]
@MCFHTAGENTS 

two ways to fix it

https://github.com/IdentityServer/IdentityServer4/issues/4631

``` c#
app.Use(async (context, next) =>
            {
                //升级到v4后这publicorigin选项不见了，改为在中间件中设置publicorigin
                var config = context.RequestServices.ResolveConfig_();
                var publicOrigin = config["public_origin"];
                if (publicOrigin?.Length > 0)
                {
                    context.SetIdentityServerOrigin(publicOrigin);
                    context.SetIdentityServerBasePath(context.Request.PathBase.Value.TrimEnd('/'));
                }
                await next.Invoke();
            });
```

**Comment by MCFHTAGENTS** [comment]
Thank you - has anyone any idea on my other point above?

**Comment by MCFHTAGENTS** [comment]
OK - one update on the error above - I needed to set `Enabled` to true in the ApiScope definition

**Comment by ishchatul** [comment]
For anyone that has implemented their own ISecretListValidator the params the Validate async method receives have been switched:
now - Task<SecretValidationResult> ValidateAsync(IEnumerable<Secret> secrets, ParsedSecret parsedSecret); 
used to be - Task<SecretValidationResult> ValidateAsync(ParsedSecret parsedSecret, IEnumerable<Secret> secrets);

**Comment by SpiritBob** [comment]
#4742

**Comment by seven1986** [comment]
I have add 
ApiResources 'books' and ApiResourceScopes 'books.read' and
ApiScope 'books.read'

![image](https://user-images.githubusercontent.com/20808494/90106445-0225c600-dd7a-11ea-8231-0b75228081c9.png)

**Comment by HuntJason** [comment]
I just came across the article [Learn how to migrate from your IdentityServer4 v3 database to IdentityServer4 v4 through manual migrations and EntityFramework Migrations](https://www.identityserver.com/articles/migrating-your-identityserver4-v3-database-to-identityserver4-v4). Hope someone finds this helpful.

**Comment by snothub** [comment]
One of my migration woes is that we have one legacy .net framework app that gets the id_token using form_post mechanism and then validates that id_token and nonce within using /identitytokenvalidation endpoint. That endpoint is no more in v4, so I'm left wondering what I should be doing instead. Any suggestions @leastprivilege ?

**Comment by leastprivilege** [comment]
This is not exactly a v3 to v4 issue, right? This endpoint is gone since a couple of years now.

Either way - introspection is the replacement for it.

**Comment by snothub** [comment]
> Either way - introspection is the replacement for it.

What credentials should be used for validating id_token? This is all identity resources and those have no secrets.

**Comment by leastprivilege** [comment]
I see. Well you need a JWT library in your clients s then.

**Comment by w0rt4** [comment]
@srinijss you need to add extra line to your Identity Server configuration. As showed in this [link](https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Additional.cs) you need to execute extention (AddJwtBearerClientAuthentication()) method on your identityserverbuilder object to register default implementation of IReplayCache
> 
> 
> I am getting the error "Unable to resolve service for type - 'IdentityServer4.Services.IReplayCache' when i run my IdentityServer project after upgrading IdentityServer4 nuget package from 3.1.0 to 4.0.1. Please let me know if you need more details on this. Appreciate any help on this. Would also be interested for a migration guide. Thanks.

**Comment by leastprivilege** [comment]
Since the workaround for the removed PublicOrigin seems to come up again and again - here's the solution

https://github.com/IdentityServer/IdentityServer4/issues/4857#issuecomment-689719505

**Comment by IndexOverflow** [comment]
I'm having some issues in my ProfileService after updating to v4. When the `ProfileDataRequestContext.Caller `is for an access_token `ResourceValidationResult` contains the expected `ApiResources`. However, when the caller is for an identity_token the validation result is empty; no resources and the parsed scopes list is also empty. As far as I can tell the refactor regarding ApiResource and ApiScopes shouldn't affect `IdentityResources` (which again, works as expected after a minor refactor).

**Comment by sevenam** [comment]
After adding migrations and updating the database schema we ended up with an `invalid_scope` error. This turned out to be due to a new field in the `ApiScope` table called `Enabled` which was set to 0 as default.

Changed the `defaultvalue` for this to `true` in the migration:

`     migrationBuilder.AddColumn<bool>(
                name: "Enabled",
                table: "ApiScopes",
                nullable: false,
                defaultValue: true);
`

**Comment by sevenam** [comment]
Also had to change the `AddAuthentication` method in `Startup.cs` due to deprecated package: `IdentityServer4.AccessValidation`. Using the package `Microsoft.AspNetCore.Authentication.JwtBearer` instead.
`
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                // base-address of your identityserver
                options.Authority = "https://demo.identityserver.io";

                // if you are using API resources, you can specify the name here
                options.Audience = "resource1";

                // IdentityServer emits a typ header by default, recommended extra check
                options.TokenValidationParameters.ValidTypes = new[] { "at+jwt" };
            });
    }
}
`

See:[https://identityserver4.readthedocs.io/en/latest/topics/apis.html]( https://identityserver4.readthedocs.io/en/latest/topics/apis.html)

**Comment by joch0a** [comment]
Is there any particular reason why the ApiSecrets table is being dropped and created again instead of being just renamed just like other tables?

```C#
migrationBuilder.DropTable(
               name: "ApiSecrets",
               schema: "dbo");

migrationBuilder.CreateTable(
                name: "ApiResourceSecrets",
                schema: "dbo",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Description = table.Column<string>(maxLength: 1000, nullable: true),
                    Value = table.Column<string>(maxLength: 4000, nullable: false),
                    Expiration = table.Column<DateTime>(nullable: true),
                    Type = table.Column<string>(maxLength: 250, nullable: false),
                    Created = table.Column<DateTime>(nullable: false),
                    ApiResourceId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ApiResourceSecrets", x => x.Id);
                    table.ForeignKey(
                        name: "FK_ApiResourceSecrets_ApiResources_ApiResourceId",
                        column: x => x.ApiResourceId,
                        principalSchema: "dbo",
                        principalTable: "ApiResources",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });
```
```C#
migrationBuilder.RenameTable(
          name: "IdentityProperties",
          schema: "dbo",
          newName: "IdentityResourceProperties",
          newSchema: "dbo");
```

Is there any risk if I manually modify that code to instead of dropping out the table I just rename it like this? 
So, if I need to revert the migration I don't lose the data inside the tables

```
migrationBuilder.RenameTable(
                name: "ApiSecrets",
                schema: "dbo",
                newName: "ApiResourceSecrets",
                newSchema: "dbo");
```

Thanks!

**Comment by daver77** [comment]
Hi, i'm just having an issue around API's when updating from v3 > v4

I have migrated my db to v4, my API was [setup using AddIdentityServerAuthentication](https://docs.identityserver.io/en/3.1.0/topics/apis.html#the-identityserver-authentication-handler)   (is this still supported?)

(I have no ApiResourceClaims(ApiClaims)/ApiResourceProperties(ApiProperties)/ApiResourceSecrets(ApiSecrets) records)

```
services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication("SsoApiAuth", options =>
                {
                    options.Authority = Configuration.GetValue<string>("IdentityServer:Authority");
                    options.ApiName = Configuration.GetValue<string>("IdentityServer:ApiName");
                });
```

Now, testing with Postman, I can get the token fine but a 401 accessing the API. Is there anything new that I need to add or anything I need to change in order for this to work?

**Comment by daver77** [comment]
Ah, I have found the issue, I need to populate ApiResourceScopes from ApiScopes

https://github.com/RockSolidKnowledge/IdentityServer4.Migration.Scripts/blob/master/MSSQL/ConfigurationDbContext.sql#L211

Does that mean ApiScopes is deprecated?

**Comment by joch0a** [comment]
> Ah, I have found the issue, I need to populate ApiResourceScopes from ApiScopes
> 
> https://github.com/RockSolidKnowledge/IdentityServer4.Migration.Scripts/blob/master/MSSQL/ConfigurationDbContext.sql#L211
> 
> Does that mean ApiScopes is deprecated?

ApiScopes is not deprecated, the relationship between the ApiResource was moved to another table.

To populate the table I added this line on the Up() method of the migration.

`migrationBuilder.Sql("INSERT INTO dbo.\"ApiResourceScopes\"(\"Scope\", \"ApiResourceId\") SELECT \"Name\", \"ApiResourceId\" FROM dbo.\"ApiScopes\"; ");
`
This works fine with postgres.

**Comment by daver77** [comment]
Thanks, there seems to be duplication in the db. I have my ApiScopes data, my ApiResources data, surely ApiResourceScopes should be a link table eg Id, ApiScopeId (instead of Scope), ApiResourceId, rather than duplicating the Scope name in ApiResourceScopes.

Or am I misunderstanding it :)

**Comment by joch0a** [comment]
Yes, you are right, idk why the ApiResourceScopes table doesn't use the ApiScopeId instead of the Name. The same happens on the ClientScopes table IIRC

**Comment by sevenam** [comment]
We're also getting a js script error: `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

This points to the `<script>` tag in line 76 in `Checksessionresult.cs`. 

Anyone else seen that?

**Comment by mantasaudickas** [comment]
Is there any option to do db migration in backwards compatible way?
Once scripts are applied - instances goes down as unable to generate new tokens (because of changes in database schema)..
If something fails - there is no way back anymore and it means whole authentication starts failing.. any thoughts? :)

**Comment by jivpif** [comment]
Hi,

After migrating, we have the following issue related with JWKS:
The "kid" value is changed (found in /.well-known/openid-configuration/jwks). It has the "RS256" string appended to it.

Previous version: '"kid": "01D94A4A417A86B10366467C70980FCC9442E6D3"'
New version: '"kid": "01D94A4A417A86B10366467C70980FCC9442E6D3RS256"'

We will appreciate any guidance how to set it to it's previous value. 
And do you think it's related to the IdentityServer upgrade?

Thanks

**Comment by leastprivilege** [comment]
I think `AddSigningCredential` always allows you to pass a raw `SigningCredential` that in turn allows you to control the kid yourself.

What kind of problem causes this?

**Comment by jivpif** [comment]
Seems some of the clients using our service keep this value hardcoded on their side. They are using it to validate the JWTs that we send to them and they fail as the "kid" in the JWT is not the same anymore.

I think I found something that might be causing this:
https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs#L87

We are calling the AddSigningCredential(X509Certificate2) whithout passing a signingAlgorithm. Its deafult value is "RS256" and it's appended to the key id as the code shows.
Will try passing an empty string instead and see how it goes.

Thanks for the quick reply it was a hint

**Comment by leastprivilege** [comment]
> keep this value hardcoded on their side

well - this is wrong. The kid can change at any point in time.

**Comment by lucent-sea** [comment]
Maybe I missed this somewhere in the conversation, but...  Why was `PublicOrigin` removed?  Will it be added back?

**Comment by lucent-sea** [comment]
Nevermind.  Saw the comments in the linked issues.  Worked for me.

**Comment by viveknaragude** [comment]
> Yes, you are right, idk why the ApiResourceScopes table doesn't use the ApiScopeId instead of the Name. The same happens on the ClientScopes table IIRC

Any Update

**Comment by viveknaragude** [comment]
> Thanks, there seems to be duplication in the db. I have my ApiScopes data, my ApiResources data, surely ApiResourceScopes should be a link table between those 2 eg Id, ApiScopeId (instead of Scope), ApiResourceId, rather than duplicating the Scope name in ApiResourceScopes.
> 
> Or am I misunderstanding it

Any Update

**Comment by sevenam** [comment]
@viveknaragude Due to the missing relation between ApiResourceScopes and ApiScopes, we ended up duplicating the scopes data into both of these tables after upgrading to v4 unfortunately...

**Comment by viveknaragude** [comment]
> @viveknaragude Due to the missing relation between ApiResourceScopes and ApiScopes, we ended up duplicating the scopes data into both of these tables after upgrading to v4 unfortunately...

Thank you.

**Comment by MikaelElkiaer** [comment]
I had issues with claim mappings and audience, but none of the previous comments quite got me there.
I too swapped out `IdentityServer4.AccessTokenValidation` for `IdentityModel.AspNetCore.AccessTokenValidation`, but found myself digging into the deprecated package to find stuff I still needed.
I ended up with a configuration like this in order to support the correct sub and role claims, as well as ignoring audience:
```csharp
services.AddAuthentication("token")
                .AddJwtBearer("token", o =>
                {
                    o.Authority = BoundConfiguration.AuthConfig.AuthBaseUrl;
                    o.Audience = "manager";

                    o.TokenValidationParameters.ValidateAudience = false;
                    o.TokenValidationParameters.ValidTypes = new[] { "at+jwt" };
                    o.SecurityTokenValidators.Clear();
                    o.SecurityTokenValidators.Add(new JwtSecurityTokenHandler { MapInboundClaims = false });
                    o.TokenValidationParameters.NameClaimType = ClaimConstants.NameIdentifier; // "sub"
                    o.TokenValidationParameters.RoleClaimType = ClaimConstants.Role; // "role"
                });
```

**Comment by kvijayasingh** [comment]
> .



> Thank you Brock and Dominick for your replies. I have my solution working now. I will try and summarise my experience in case it helps others or in case I am "doing it wrong" and others can learn.
> 
> My system has multiple clients (currently ASP.NET Core web applications and in the future mobile apps). They are related apps in a safety management system for mining/construction/engineering scenarios. Each client basically has its own API. They are relatively simple and small in size. IdentityServer is used for authentication for each app and API and I am using ASPNET Identity. It very similar to the Quickstart examples.
> 
> I keep Identity resources, API resources and Clients in `Config.cs` and keep the Operational store in SQL Server. I do this as the resources and clients will change very infrequently and all apps and APIs and IdentityServer will live on the one server.
> 
> The relevant part of my v3 `Config.cs` was like the docs:
> 
> ```
> public IEnumerable<ApiResource> Apis =>
> 	new ApiResource[]
> 	{
> 		new ApiResource(configuration["ApiNames:MyActionsApi"], "MyActions API")
> 	};
> ```
> 
> The relevant part of my v3 `Startup.cs` was:
> 
> ```
> var builder = services.AddIdentityServer()
> 			.AddInMemoryIdentityResources(config.Ids)
> 			.AddInMemoryApiResources(config.Apis)
> 			.AddInMemoryClients(config.Clients)
> 			.AddOperationalStore(options =>
> 			{
> 				options.ConfigureDbContext = b => b.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
> 				options.EnableTokenCleanup = true;
> 			})
> 			.AddAspNetIdentity<ApplicationUser>();
> ```
> 
> I upgraded the Nuget packages to v4 and ran the appropriate migrations scripts from https://github.com/RockSolidKnowledge/IdentityServer4.Migration.Scripts/tree/CreateScripts for my database.
> 
> The first problem I had was IdentityServer returned an 'invalid_scope' error. After reading the docs I changed my `Config.cs` Apis from `ApiResource` to `ApiScope`. This solved the 'invalid_scope' error but authentication at the API was failing with 'Audience validation error'. This occurs because "When using the scope-only model, no aud (audience) claim will be added to the token". (https://identityserver4.readthedocs.io/en/latest/topics/resources.html#apis)
> 
> I then changed to include BOTH `ApiScope` and `ApiResource` and this solved the problem. I used the same value for Scope name and Resource name. I don't know if this is the "right" solution but it works so far for my simple project.
> 
> The relevant part of my v4 `Config.cs`:
> 
> ```
> public IEnumerable<ApiScope> ApiScopes =>
> 	new ApiScope[]
> 	{
> 		new ApiScope(configuration["ApiNames:MyActionsApi"], "MyActions API")
> 	};
> 
> public IEnumerable<ApiResource> ApiResources =>
> 	new ApiResource[]
> 	{
> 		new ApiResource(configuration["ApiNames:MyActionsApi"], "MyActions API")
> 		{
> 			Scopes = { configuration["ApiNames:MyActionsApi"] }
> 		}
> 	};
> ```
> 
> The relevant part of my v4 `Startup.cs`:
> 
> ```
> var builder = services.AddIdentityServer()
> 			.AddInMemoryIdentityResources(config.Ids)
> 			.AddInMemoryApiScopes(config.ApiScopes)
> 			.AddInMemoryApiResources(config.ApiResources)
> 			.AddInMemoryClients(config.Clients)
> 			.AddOperationalStore(options =>
> 			{
> 				options.ConfigureDbContext = b => b.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"));
> 				options.EnableTokenCleanup = true;
> 			})
> 			.AddAspNetIdentity<ApplicationUser>();
> ```
> 
> Hope that helps and I am not leading people in the wrong direction.

i tried  the above steps , it worked on the identity server, but test application is using the pipelinefactory , modified the add scopes and resource but still failing on all the controller test here is pipeline factory code
![PipelineFactory](https://user-images.githubusercontent.com/95244667/147595168-69428fde-a033-4be1-bad1-60075beaa80e.PNG)

public static TestServer CreateServer(Action<OAuth2IntrospectionOptions> options,
            DelegatingHandler backChannelHandler, bool addCaching = false)
        {
            return new TestServer(new WebHostBuilder().UseUrls("http://localhost:5000")
                .ConfigureServices(services =>
                {
                    if (addCaching) services.AddDistributedMemoryCache();

                    // Start Custom Code

                    services.AddTransient<IClientsRepository, ClientsRepository>();
                    services.AddTransient<IApiResourceRepository, ApiResourceRepository>();

                    // Add AspNet Identity Database context
                    services.AddDbContext<ApplicationDbContext>(dbContextOptionsBuilder =>
                        dbContextOptionsBuilder.UseInMemoryDatabase("xxxx"));

                    // Add AspNet Identity provider to Identity Server
                    services.AddIdentity<ApplicationUser, IdentityRole>()
                        .AddEntityFrameworkStores<ApplicationDbContext>()
                        .AddDefaultTokenProviders();

                    // Add InMemory Identity Server configuration
                    services.AddIdentityServer()
                        .AddDeveloperSigningCredential()
                        .AddConfigurationStore(configurationStoreOptions =>
                        {
                            configurationStoreOptions.ConfigureDbContext = builder =>
                                builder.UseInMemoryDatabase("xxxx");
                        })
                        .AddOperationalStore(operationalStoreOptions =>
                        {
                            operationalStoreOptions.ConfigureDbContext = builder =>
                                builder.UseInMemoryDatabase("xxxx");
                        })
                        .AddInMemoryApiScopes(GetApiScopes())
                        .AddInMemoryApiResources(GetApiResource());

please suggest do i miss anything

**Comment by kvijayasingh** [comment]
i tried the above steps , it worked on the identity server, but test application is using the pipelinefactory , modified the add scopes and resource but still failing on all the controller test here is pipeline factory code
PipelineFactory

public static TestServer CreateServer(Action options,
DelegatingHandler backChannelHandler, bool addCaching = false)
{
return new TestServer(new WebHostBuilder().UseUrls("http://localhost:5000")
.ConfigureServices(services =>
{
if (addCaching) services.AddDistributedMemoryCache();

                // Start Custom Code

                services.AddTransient<IClientsRepository, ClientsRepository>();
                services.AddTransient<IApiResourceRepository, ApiResourceRepository>();

                // Add AspNet Identity Database context
                services.AddDbContext<ApplicationDbContext>(dbContextOptionsBuilder =>
                    dbContextOptionsBuilder.UseInMemoryDatabase("xxxx"));

                // Add AspNet Identity provider to Identity Server
                services.AddIdentity<ApplicationUser, IdentityRole>()
                    .AddEntityFrameworkStores<ApplicationDbContext>()
                    .AddDefaultTokenProviders();

                // Add InMemory Identity Server configuration
                services.AddIdentityServer()
                    .AddDeveloperSigningCredential()
                    .AddConfigurationStore(configurationStoreOptions =>
                    {
                        configurationStoreOptions.ConfigureDbContext = builder =>
                            builder.UseInMemoryDatabase("xxxx");
                    })
                    .AddOperationalStore(operationalStoreOptions =>
                    {
                        operationalStoreOptions.ConfigureDbContext = builder =>
                            builder.UseInMemoryDatabase("xxxx");
                    })
                    .AddInMemoryApiScopes(GetApiScopes())
                    .AddInMemoryApiResources(GetApiResource());
please suggest do i miss anything
