### ISSUE TITLE
Add Client to TokenValidationResult in the ValidateRefreshTokenAsync

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#4593]
4.x Code Base
Reference: [DefaultRefreshTokenService.cs](https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Services/Default/DefaultRefreshTokenService.cs) 

I don't know if this is an issue of not, but can we change the following;  
```
public virtual async Task<TokenValidationResult> ValidateRefreshTokenAsync(string tokenHandle, Client client)
{
    ...
    return new TokenValidationResult { IsError = false, RefreshToken = refreshToken };
}
```
to
```
public virtual async Task<TokenValidationResult> ValidateRefreshTokenAsync(string tokenHandle, Client client)
{
    ...
    eturn new TokenValidationResult { IsError = false, RefreshToken = refreshToken ,Client = client};
}
```
Since its there, shouldn't any returned ```TokenValidationResult``` be populated with a ```Client``` in ```all cases```.

**Comment by leastprivilege** [comment]
Sure can do.
