### ISSUE TITLE
Cannot implicitly convert type 'ICollection<IdentityServer4.Models.ClientClaim>

### ISSUE THREAD

**Issue by aborderon** [IdentityServer/IdentityServer4#4594]
### Question

Hello,

I just updated my Idsr4 to version 4.0.0 and I have a type conversion problem in my **ClientRequestValidator**.

I want to recover the claims of a client with the **FindClientByIdAsync** method but since the update the type has changed.

```
private async Task<IEnumerable<Claim>> GetClaimsFromClient(string clientId)
        {
            var client = await _clientStore.FindClientByIdAsync(clientId);

            if (client is null)
            {
                throw new Exception();
            }
            
            return client.Claims;
        }
```

Here is the error:

![image](https://user-images.githubusercontent.com/6728728/86016134-b796f700-ba22-11ea-8fe7-17ffe2ef9a3b.png)

Do you have the solution to this problem?

Thank you

**Comment by ylabade** [comment]
In this case, it's true that it's not practical that the types are different.

As an acceptable workaround you can :

```cs
return client.Claims.Select(c => new Claim(c.Type, c.Value, c.ValueType));
```

**Comment by aborderon** [comment]
Perfect, thank you, I had found another solution but this one suits me better.

I close my issue ;)
