### ISSUE TITLE
Full logout from mobile application

### ISSUE THREAD

**Issue by vdecristofaro** [IdentityServer/IdentityServer4#4595]
### Question

I have a mobile application which uses an Authorization Code + PKCE flow against an identity server implementation. Everyhting works good either for login as well as for logout. My  client uses reference token configuration.

After logging out however there is still some time (few minutes) while the token remain valid.

My application has been assessed by a QSA which says that this practice does not adhere to OWASP recommendations

>   The user's session should be terminated after clicking the logout button. Please follow the session management recommendations from OWASP: https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html 

Is there anything I can do  to mitigate this behaviour?

**Comment by jt-pt-dev** [comment]
This may be related to the clock skew with JWT tokens:

https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/issues/90

**Comment by leastprivilege** [comment]
In case of JWT there is indeed a clock skew - 5 mins by default.

Reference tokens should be immediate - unless the API does some caching of the validation result.

**Comment by vdecristofaro** [comment]
Thanks a lot for very quick answer. 
I am getting a little bit confused. Should I call the revocation endpoint before logging out to invalidate the access and refresh token? 
I have read about signout procedure in documentation however, as my application is a native mobile app developed with xamarin, I do not really understand if it fall under Front/Back channel or Session Management.

Could anyone give a bit of guidance on  the right process to follow?

**Comment by leastprivilege** [comment]
Revoking tokens is a good idea during logout. This is unrelated to session management.

**Comment by vdecristofaro** [comment]
Many thanks!
I  have been able to solve the issue by invoking the revocation endpoint through IdentityModel. Here is a sample code:

```
var logoutUri = await _oidcClient.PrepareLogoutAsync( request );
using (var client = new HttpClient()) {
     var endSessionResponse = await client.GetAsync( logoutUri ).ConfigureAwait( false );
     var disco = await client.GetDiscoveryDocumentAsync( AuthConstants.AuthorityUri );
     var accessTokenRevocationRequest = new TokenRevocationRequest() {
         RequestUri = new Uri( disco.RevocationEndpoint ),
         ClientId = AuthConstants.ClientId,
         Token = accessToken,
         TokenTypeHint = AuthConstants.ACCESS_TOKEN_NAME
     };
     var accessTokenResponse = await client.RevokeTokenAsync( accessTokenRevocationRequest );
     var refreshTokenRevocationRequest = new TokenRevocationRequest() {
         RequestUri = new Uri( disco.RevocationEndpoint ),
         ClientId = AuthConstants.ClientId,
         Token = refreshToken,
         TokenTypeHint = AuthConstants.REFRESH_TOKEN_NAME
     };
     var refreshTokenResponse = await client.RevokeTokenAsync( refreshTokenRevocationRequest );
} 
```

Also noted that when revoking the refresh token first also the access token is revoked.
