### ISSUE TITLE
Docs advide poor npm practice

### ISSUE THREAD

**Issue by IronSean** [IdentityServer/IdentityServer4#4598]
### Issue

This isn't really a question, but not a bug with the software itself. It's feedback on the documentation advising really strange npm usage.

[From here](https://github.com/IdentityServer/IdentityServer4/blob/main/docs/quickstarts/4_javascript_client.rst) The following content is included:

>**NPM**
>
>If you want to use NPM to download `oidc-client`, then run these commands from your `JavaScriptClient` project directory::
>
>    npm i oidc-client
>    copy node_modules\oidc-client\dist\* wwwroot
>
>This downloads the latest `oidc-client` package locally, and then copies the relevant JavaScript files into `~/wwwroot` so they >can be served up by your application.

This is strange advice because if you're just going to copy the content from the node modules folder you should just download it manually and not pretend those files are controlled or versioned by npm. Copying the content out defeats any benefits of using npm. Better advice would be that if you're using npm you should install the package then include it in your build and bundling configuration.

**Comment by brockallen** [comment]
It's a sample and wasn't intended to tackle the larger issues around versioning and package management. If you want to add a note to the docs/QS, feel free to propose a PR.
