### ISSUE TITLE
Clarify in the documentation the purpose of the new Description input field on the consent screen

### ISSUE THREAD

**Issue by tndata** [IdentityServer/IdentityServer4#4600]
**We can only help you if you are on the latest version. Either use the latest 2.x or 3.x**

Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](http://docs.identityserver.io/en/latest/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

On the consent screen in version 4.01 (quicktemplates) we now have a new Description input field. 

I think the user-interface in the template needs some help icon describing what the user is supposed to enter here. Also clarify in the documentation what the purpose of this field is and where the input data is stored. what is the description used for?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Docs updated.
