### ISSUE TITLE
Why not delete Consumed PersistedGrant's?

### ISSUE THREAD

**Issue by MrGroovy** [IdentityServer/IdentityServer4#4608]
### Question
Hi. We are upgrading to 4.0.1. We have custom implementations of `IPersistedGrantStore` with NHibernate. When a client uses it's refresh token the `StoreAsync` method is called twice. Once to update the original, and once te create the new persisted grant. The update will have the `ConsumedTime` set.

Why would we keep the consumed grants in the database? Why not delete them? (See code below).

```csharp
        public async Task StoreAsync(PersistedGrant grant)
        {
            NhPersistedGrant nhGrant = new NhPersistedGrant();
            nhGrant.Key = grant.Key;
            nhGrant.ClientId = grant.ClientId;
            nhGrant.SubjectId = grant.SubjectId;
            nhGrant.Type = grant.Type;
            nhGrant.CreationTime = grant.CreationTime;
            nhGrant.ExpirationTime = grant.Expiration;
            nhGrant.Data = grant.Data;

            if (grant.ConsumedTime is { })
            {
                await nhGrantRepository.Remove(nhGrant.Key);
            }
            else
            {
                await nhGrantRepository.Add(nhGrant);
            }
        }
```

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2020/06/29/refresh-tokens-in-identityserver4-v4/
