### ISSUE TITLE
Question about the error code to return

### ISSUE THREAD

**Issue by juanan** [IdentityServer/IdentityServer4#4610]
If a made a request to get an access token where the username/password is ok, the scope is ok for the client id but that scope is not valid for that username/password, which error code should I return: invalid_username_password or invalid_scope?

Maybe the OAuth standard says something about that, I didn't found so I wanted to follow your basic guidelines.

Many thanks.

**Comment by leastprivilege** [comment]
> but that scope is not valid for that username/password

scopes are never related to users, only client. So I don't follow.

**Comment by juanan** [comment]
This was what I mean

https://oauth.net/2/scope/

Scope is a mechanism in OAuth 2.0 to limit an application's access to a user's account. An application can request one or more scopes, this information is then presented to the user in the consent screen, and the access token issued to the application will be limited to the scopes granted.

Many thanks @leastprivilege
