### ISSUE TITLE
Docs - Incorrect instructions in quickstarts

### ISSUE THREAD

**Issue by granttw** [IdentityServer/IdentityServer4#4613]
Referring to the documentation on quickstarts/1_client_credentials.html.

In the section titled "Authorization at the API", I read the following instructions:

"Add the following to the Configure method in Startup"

I think this is suppose to be:

"Add the following to the ConfigureServices method in Startup"

I am using ASP.NET Core 3.1.301.

**Comment by brockallen** [comment]
Please send a PR.

**Comment by leastprivilege** [comment]
merged
