### ISSUE TITLE
Docs - Incorrect instructions on adding an api

### ISSUE THREAD

**Issue by granttw** [IdentityServer/IdentityServer4#4614]
Referring to documentation on quickstarts/1_client_credentials.html.

In the section titled "Adding an API", I am instructed to run the following command:

`dotnet new web -n API`

I think this is suppose to be:

`dotnet new webapi -n API`

I am using ASP.NET Core version 3.1.301.

**Comment by brockallen** [comment]
Send a PR please.

**Comment by brockallen** [comment]
merged, thanks
