### ISSUE TITLE
AddLocalApi queries the identity database with every API request

### ISSUE THREAD

**Issue by ahmadakra** [IdentityServer/IdentityServer4#4622]
### Question (Performance related)
When I protect an API with an external IdentityServer authority, the access token is authenticated 100% in memory.
But when I protect an API with a **local** IdentityServer, it queries the identity database **with every web request**.

This is the SQL query that is executed with every web request.
```sql
SELECT TOP(1) [a].[Id], [a].[AccessFailedCount], [a].[ConcurrencyStamp], [a].[Email], [a].[EmailConfirmed], [a].[LockoutEnabled], [a].[LockoutEnd], [a].[NormalizedEmail], [a].[NormalizedUserName], [a].[PasswordHash], [a].[PhoneNumber], [a].[PhoneNumberConfirmed], [a].[SecurityStamp], [a].[TwoFactorEnabled], [a].[UserName]
FROM [AspNetUsers] AS [a]
WHERE [a].[Id] = @__p_0
```

Is this behavior expected?

### Minimal working example

This configuration results in performant in-memory token authentication:
```csharp
services.AddAuthentication().AddIdentityServerAuthentication(JwtBearerDefaults.AuthenticationScheme, opt =>
                {
                    opt.Authority = authorityUri;
                    opt.ApiName = Constants.ApiResourceName;
                });
```

This, on the other hand, results in an SQL query to the identity database with every single API request:
```csharp
services.AddAuthentication().AddLocalApi(JwtBearerDefaults.AuthenticationScheme, opt => { });
```

### Additional info

IdentityServer v3.1.3
IdentityServer4.AccessTokenValidation v3.0.1
.NET Core 3.1

I configured IdentityServer to use ASP.NET Identity like this:

```csharp
services.AddIdentityServer(opt =>
            {
                   // ...
            })
            // ...
            .AddAspNetIdentity<EmbeddedIdentityServerUser>();
```

**Comment by leastprivilege** [comment]
Yes - that is right. We are using our internal token validation logic - which is also checking if the user represented by the access token is still valid.

**Comment by ahmadakra** [comment]
Thank you for the info.
