### ISSUE TITLE
EntityFramework Quickstart - Account Controller v4 refactor

### ISSUE THREAD

**Issue by abritabroad** [IdentityServer/IdentityServer4#4623]
### Question

Is a Quickstart refactor on the roadmap so that the account controller uses the UserManager for authentication?

### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by brockallen** [comment]
Have you seen this:

https://github.com/IdentityServer/IdentityServer4.Quickstart.UI.AspNetIdentity

**Comment by abritabroad** [comment]
No! I guess I was looking in the wrong place.... sorry...

and thanks!
