### ISSUE TITLE
Bug in the Description handling?

### ISSUE THREAD

**Issue by tndata** [IdentityServer/IdentityServer4#4627]
**We can only help you if you are on the latest version. Either use the latest 2.x or 3.x**

Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](http://docs.identityserver.io/en/latest/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem

1. When I login as a user (IdentityServer 4.0.2) and give a consent and enter a **Description** then the following happens:
 
-   1. PersistedGrantStore.StoreAsync is called with a **PersistedGrantType=user_consent** and Description = **null**
-   2. PersistedGrantStore.StoreAsync is called with a **PersistedGrantType=authorization_code** and Description = **MyDescription**

2. Later when the client uses the authorization code, the authorization_code entry in my PersistedGrantStore is removed.

Fine.

3. When I later go to the **/grants** page to view my grants, the description is never shown, because the description is always null. 

So, what I think is a bug is that the description property of the  **PersistedGrantType=user_consent** is always null when IdentityServer calls PersistedGrantStore.

Otherwise,what's the point to save the description for the short-lived authorization_code grant?

I also verified this against https://demo.identityserver.io/ when I logged in as Bob, give consent, enter a description and then go to https://demo.identityserver.io/grants

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
I just ran our EF samples and I am seeing the description in the Client Application Permissions page. The refresh token in the DB has the description, but I do see what you mean in that the consent entry does not.

**Comment by tndata** [comment]
I was using the InMemory database and I didn't try it against the database. 

I also think it would be helpful to the general user of IdentityServer if there were a small "(I) info" icon/tooltip describing what the end-user is expected to enter there.. Just saying description is a bit unclear.

**Comment by brockallen** [comment]
Looks like this is already documented here: https://identityserver4.readthedocs.io/en/latest/reference/interactionservice.html#consentresponse
