### ISSUE TITLE
Method not found: 'Void IdentityServer4.Models.ProfileDataRequestContext.set_IssuedClaims

### ISSUE THREAD

**Issue by ayberkcanturk** [IdentityServer/IdentityServer4#463]
I am using the same architecture of following sample (https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Docker) with MongoDB Storage (IdentityServer4.MongoDB) and AspNetCore Identity (Microsoft.AspNetCore.Identity.MongoDB) with following Identity Server configuration;

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .RegisterMongoStores<ApplicationUser, IdentityRole>(_configuration.GetConnectionString("DefaultConnection"))
                .AddDefaultTokenProviders();

            // Add application services.
            services.AddTransient<IEmailSender, AuthMessageSender>();
            services.AddTransient<ISmsSender, AuthMessageSender>();

            services.AddIdentityServer()
               .SetTemporarySigningCredential()
               .AddInMemoryUsers(Users.Get())
               .AddAspNetIdentity<ApplicationUser>()
               .AddConfigurationStore(_configuration.GetSection("MongoDB"))
               .AddOperationalStore(_configuration.GetSection("MongoDB"));

            services.AddMvc();

When I try to access secure area with [Authorize] filter I am having following error;
Method not found: 'Void IdentityServer4.Models.ProfileDataRequestContext.set_IssuedClaims

I have attached the raw exception details.

[MethodNotFound.txt](https://github.com/IdentityServer/IdentityServer4/files/571778/MethodNotFound.txt)

PS: After I close the browser window, retry to access the secure area again (a method with [Authorize] filter) I am having following error;

InvalidOperationException: idp claim is missing

Thank for your help.
Regards,
Ayberk

**Comment by brockallen** [comment]
sounds like a version mismtach

**Comment by ayberkcanturk** [comment]
@brockallen, Thank you for your reply. I've written the dependencies of the project;

 "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "IdentityServer4": "1.0.0-rc2",
    "IdentityServer4.MongoDB": "1.0.0-rc2",
    "Microsoft.AspNetCore.Identity": "1.0.0",
    "Microsoft.AspNetCore.Identity.MongoDB": "1.0.2",
    "IdentityServer4.AspNetIdentity": "1.0.0-rc1",
    "Microsoft.AspNetCore.Authentication.Google": "1.0.0"
}

**Comment by brockallen** [comment]
"IdentityServer4": "1.0.0-rc2",
"IdentityServer4.AspNetIdentity": "1.0.0-rc1",

here's your mismatch

**Comment by ayberkcanturk** [comment]
It works like a charm! Thank you @brockallen
