### ISSUE TITLE
How to configure IdentityServer with MySQL database?

### ISSUE THREAD

**Issue by ViacheslavUKR** [IdentityServer/IdentityServer4#4630]
### Question

Hello, gays. Main SQL server of NET Core is MySQL. This is fact, because Net Core is an exactly Linux platform. There are nothing another goal to use Net Core environment rather than in Linux, because Net Framework working perfectly in Windows environment. But I don't see any example about configuration MySQL database with IdentityServer, only stubs and demo with MSSQL on Windows platform. How to force working IdentityServer  with MySQL DB? It seems to me AddConfigurationStore and AddOperationalStore is missing for MySQL. What methods need to use for replacement to connect MySQL DB? Or IdentityServer is not possible to implement in real Net Core environment because this is Net Framework program only?

**Comment by leastprivilege** [comment]
Our library targets EF. If you favourite database has an EF provider, you can use it.

**Comment by damianh** [comment]
FYI MSSQL run on linux https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-overview?view=sql-server-ver15

**Comment by ViacheslavUKR** [comment]
> 
> 
> FYI MSSQL run on linux https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-overview?view=sql-server-ver15

and what? my question about configure IdentityServer for main main Net Core environment - for MySQL, if it is impossible, IdentityServer is only stupid scam, because without IdentityServer we can configure Net Core + JWT + MySQL perfectly - https://github.com/ViacheslavUKR/CallMicroservicesFromBlazorWithJwtProtection

**Comment by ViacheslavUKR** [comment]
> 
> 
> Our library targets EF. If you favourite database has an EF provider, you can use it.


and what? my question about configure IdentityServer for main main Net Core environment - for MySQL, if it is impossible, IdentityServer is only stupid scam, because without IdentityServer we can configure Net Core + JWT + MySQL perfectly - https://github.com/ViacheslavUKR/CallMicroservicesFromBlazorWithJwtProtection

**Comment by leastprivilege** [comment]
I assume the fact that you sound rude and aggressive is a language/translation problem.

To reiterate: Our library targets EF. If you favourite database has an EF provider, you can use it. If not, implement the `IClientStore` and `IResourceStore` interfaces using your favourite data access API. That's all we have.

**Comment by damianh** [comment]
In case anyone sees this and thinks it's not possible... I use IdentityServer on linux (lambda) with MySQL (AWS RDS Aurora).

**Comment by eloekset** [comment]
We used IdentityServer with Azure Table Storage at my previous job. That's a much bigger difference than another SQL DB. (In case someone is interested - no I don't have the source code, and it was never open sourced unfortunately.)
