### ISSUE TITLE
public origin is not found in options in v4.x

### ISSUE THREAD

**Issue by hiwjcn** [IdentityServer/IdentityServer4#4631]
```
var identityBuilder = collection.AddIdentityServer(option =>
            {
                //option.UserInteraction.ErrorUrl = "";
                var publicOrigin = config["public_origin"];
                if (publicOrigin?.Length > 0)
                {
                    option.PublicOrigin= publicOrigin;//complie error
                }
            });
```

**Comment by leastprivilege** [comment]
We removed it. Use the forwarded headers instead.

**Comment by gegaryfa** [comment]
@hiwjcn To use forwarded headers:
In the `Startup.ConfigureServices` :
```
services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders =
        ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto | ForwardedHeaders.XForwardedHost;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});
```
In the `Startup.Configure` :
```
app.UseForwardedHeaders();
```

Then you can pass the headers `X-Forwarded-Proto=<https or http>` and `X-Forwarded-host=<you_host>` in the  request.

**Comment by hiwjcn** [comment]
thanks, and pls update to the docs in the break change section :)

**Comment by TheMisir** [comment]
> We removed it. Use the forwarded headers instead.

@leastprivilege,

Why did you removed it? Is there another way to modify origin? It did currently break our server. So I had to downgrade it to build project. I know I can use forwarded headers. But it doesn't works. The only way to fix that issue is using PublicOrigin :(

**Comment by unionthugface** [comment]
Just FYI this solves [Issue 46](https://github.com/IdentityModel/IdentityModel.OidcClient/issues/46) and [Issue 324](https://github.com/IdentityServer/IdentityServer4/issues/324) as well for anyone who winds up on one of those pages first.

**Comment by g3v** [comment]
Does the fix with forwarded headers also corrects the endpoints in the Discovery Endpoint output document, so that they are relative to custom path?

**Comment by TheMisir** [comment]
Is there any update about that?

**Comment by TheMisir** [comment]
Here's temporary fix 😅

Just add a middleware before identity server to modify host and protocol properties of `HttpContext.Request`. It worked for me =)

**Comment by CesarD** [comment]
I configured in `Startup.ConfigureServices`:

```
services.Configure<ForwardedHeadersOptions>(options =>
                                                        {
                                                            options.ForwardedHeaders = ForwardedHeaders.XForwardedFor |
                                                                                       ForwardedHeaders.XForwardedProto |
                                                                                       ForwardedHeaders.XForwardedHost;
                                                            options.KnownNetworks.Clear();
                                                            options.KnownProxies.Clear();
                                                        });
```

and in `Startup.Configure`:

```
app.UseForwardedHeaders()
               .UseHttpsRedirection()
               .UseCors()
               .UseStaticFiles()
               .UseRouting()
               .UseIdentityServer();
```

Still getting HTTP URLs in Discovery Document instead of HTTPS as expected.
I'd prefer to get back Public Origin setting. This is very annoying to solve when before we could solve it on our own without so much dependency from the network team.

What other alternative do I have right now if this Startup configurations don't work?

**Comment by M0ns1gn0r** [comment]
@CesarD This is how I solved that:

```c#
app.Use((context, next) =>
{
	context.Request.Protocol = "https";
	context.Request.Host = new HostString("my-domain.com:12345");
	//  Only if you need it.
	context.Request.PathBase = new PathString("/api/auth");

	return next();
});
```

**Comment by CesarD** [comment]
Thanks a lot @M0ns1gn0r !! :)

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/4857#issuecomment-689719505
