### ISSUE TITLE
IdentityServer configuration with IIS CORS module

### ISSUE THREAD

**Issue by jovball** [IdentityServer/IdentityServer4#4634]
We have been using the IIS CORS module along with a wild-card rule for any subdomain belonging to us. That has worked well until we attempted to add IdentityServer4 on the server.

If we have the IIS CORS module enabled, any attempt to login with IdentityServer will result in a 403 error (on posting the login data). I have tried to configure a CORS policy in IdentityServer with no success. 

Here is the IIS CORS module section from applicationHost.config with the domain wildcard rule.
```
 <cors enabled="true" failUnlistedOrigins="true">
            <add origin="*" allowed="false" />
			
            <add origin="https://*.mydomain.com" allowCredentials="true">
                <allowHeaders allowAllRequestedHeaders="true">
                    <add header="Content-Type" />
                </allowHeaders>
                <allowMethods>
                    <add method="PUT" />
                    <add method="POST" />
                    <add method="DELETE" />
                    <add method="PATCH" />
                </allowMethods>
            </add>							
        </cors>
```

This is the CORS Policy code. I've tried with wildcards and without wildcards
```csharp
  public virtual void ConfigureCors(IServiceCollection services)
{
	services.AddCors(options =>
	{
		options.AddPolicy(name: AllowedSpecificOrigins,
			builder =>
			{
				builder.WithOrigins("https://mysite.mydomain.com",
									"https://*.mydomain.com")
				.SetIsOriginAllowedToAllowWildcardSubdomains()
				.AllowAnyHeader()
				.AllowAnyMethod();
			});
	});
}
	
```

If I add a CORS configuration section directly into the IdentityServer application, I can log into the application directly but any attempt to log in from another application will result in the same 403 error.
```
 <cors enabled="true" failUnlistedOrigins="true">
            <clear />			
            <add origin="https://IdentityServer.mydomain.com" allowCredentials="true">
                <allowHeaders allowAllRequestedHeaders="true">
                    <add header="Content-Type" />
                </allowHeaders>
                <allowMethods>
                    <add method="PUT" />
                    <add method="POST" />
                    <add method="DELETE" />
                    <add method="PATCH" />
                </allowMethods>
            </add>							
        </cors>
```

### Relevant parts of the log file
The log file does not have any entries for these actions.

How can I configure IdentityServer to work with the IIS CORS module?

**Comment by brockallen** [comment]
I don't know, sorry. Never tried to use the IIS CORS module.

**Comment by jovball** [comment]
Here is more information that might help. Upon login, the authorize/callback action sends a post to our client. For some reason the origin header of the post request is being sent as null so this fails our CORS origin check. When we allow the origin 'null' in the IIS CORS configuration, we no longer have the 403 error.

I should have also said in the first post that we are using IdentityServer4 3.13.

![idsrv4-cors-origin](https://user-images.githubusercontent.com/7237539/86962812-7c3aad80-c131-11ea-8415-08bddc269aee.png)

**Comment by brockallen** [comment]
Sometimes browsers send the origin header (on POST) even though the request is not a real Ajax/cross-origin call. Not sure if that helps your investigation.
