### ISSUE TITLE
Claim isnt being returned to mvc client

### ISSUE THREAD

**Issue by ebarbuti** [IdentityServer/IdentityServer4#464]
In ResourceOwnerPasswordvalidator I create a GrantValidationResult with a claim...

GrantValidationResult grGood = new GrantValidationResult(context.UserName, context.Password, new[] { new Claim("profile", res) });

When its returned from await _validator.ValidateAsync(ctx); I can see its there...

When i put a break in GetProfileDataAsync in my ProfileService i can see its there...

        public Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var claims = context.Subject.Claims.Select(claim => new Claim(claim.Type, claim.Value, claim.ValueType, claim.Issuer, claim.OriginalIssuer, claim.Subject)).ToList();
            context.IssuedClaims = claims;
            return Task.FromResult(0);            
        }

When I redirect to my client and loop thru the User.Claims... its not there...

Can you give me any clue as to what may be happening here?
Thanks!

**Comment by leastprivilege** [comment]
> When I redirect to my client and loop thru the User.Claims... its not there...

What you mean with redirect in resource owner flow?

**Comment by ebarbuti** [comment]
Sorry for any confusion... the redirect is in the account controller login method after the user is logged in successfully.

if (_interaction.IsValidReturnUrl(model.ReturnUrl))
{
    return Redirect(model.ReturnUrl);
}

I am using the sample MVC client app and looping thru User.Claims and the claim I added is not there even though I can see it in the context in the server.

**Comment by leastprivilege** [comment]
I still don't follow.

Resource owner flow is unrelated to all of that. It is a web api call that returns an access token...

Am I missing something?

**Comment by ebarbuti** [comment]
I'm the one that is probably missing something I'm sure!
MVC Client calls IdentityServer API for validation and receives the token fine.. that all works.  Now I want to add a claim for the given user.  My assumption is that if I create the GrantValidationResult with a claim as part of the constructor it should be in the context.Result and it is... then in my ProfileService class I add ALL claims to context.IssuedClaims like this...

            var claims = context.Subject.Claims.Select(claim => new Claim(claim.Type, claim.Value, claim.ValueType, claim.Issuer, claim.OriginalIssuer, claim.Subject)).ToList();
            context.IssuedClaims = claims;

When I loop thru all claims using User.Claims in the client, its not there...

Sorry for any confusion.. this is all new to me! :) but I really appreciate the help!

**Comment by leastprivilege** [comment]
you can use https://jwt.io/ to inspect your tokens.

That's what I would do.

**Comment by ebarbuti** [comment]
Thank you! I ended up setting the value for the sub claim to the profile id of the user I was after and that will do it for me! I really appreciate you taking the time to help out!
