### ISSUE TITLE
Configed with IdentityServer, but can't load and redirect on IOS.

### ISSUE THREAD

**Issue by xaqfan** [IdentityServer/IdentityServer4#4642]
I have configed with IdentityServer on IOS,

static NSString *const kIssuer = @"https://demo.identityserver.io";
static NSString *const kRedirectURI = @"io.identityserver.demo:/oauthredirect";

And SFSafariViewcontroller had loaded html and to login,then there is no someing in html.
It can't  redirect .

How can i config it ?

**Comment by MaikuB** [comment]
Did you add the following to your app's Info.plist file?

```
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>io.identityserver.demo</string>
        </array>
    </dict>
</array>
```

**Comment by xaqfan** [comment]
Hi, 
I just have conifged it  in AppAuth-iOS example.
Loading nothing ,and no redirect!
