### ISSUE TITLE
See  EnsureSeedData

### ISSUE THREAD

**Issue by douglassimaodev** [IdentityServer/IdentityServer4#4643]
Hi

I am using template version 4.0.2 and when I create a new project dotnet new is4ef -o ProjectName

see file seedData

in  private static void EnsureSeedData there is this validation at line 71

if (!context.ApiResources.Any())
            {
                Log.Debug("ApiScopes being populated");
                foreach (var resource in Config.ApiScopes.ToList())
                {
                    context.ApiScopes.Add(resource.ToEntity());
                }
                context.SaveChanges();
            }
            else
            {
                Log.Debug("ApiScopes already populated");
            }

note that it checks context.ApiResources.Any()   however it is adding into context.ApiScopes.Add(resource.ToEntity());

meaning if you run it for the second time it will try to run it again, shouldn't it be checking against ApiScopes instead of ApiResources?

**Comment by brockallen** [comment]
Fixed, thanks.
