### ISSUE TITLE
Ability to run IdentityServer4 as IDP and SP in same instance

### ISSUE THREAD

**Issue by jongallant** [IdentityServer/IdentityServer4#4646]
### Question
Is it possible to run IdentityServer4, as both an Identity Provider, and Service Provider, in the same instance?
I would just like confirmation, as based on all the examples I have seen, this does not seem to be possible.

Can someone elaborate on this ?

**Comment by leastprivilege** [comment]
ServiceProvider is a SAML term - so it is unclear to me what the real question is.

**Comment by jongallant** [comment]
Yes exactly, using a SAML plugin, such as SAML2P.  I am under the impression you would require to run two separate instances of IdentityServer4 in order to provide this functionality.

**Comment by leastprivilege** [comment]
No - you can use this plugin:

https://www.identityserver.com/products/saml2p
