### ISSUE TITLE
Consent is not remembered if one of the requested scopes is deselected

### ISSUE THREAD

**Issue by darena-mhaque** [IdentityServer/IdentityServer4#4647]
I have a question on this and not sure if this is a bug or if it is intentional. In the typical consent screen, you should be able to select/deselect which scopes you want to give to the requesting client. Suppose a client is requesting the following scopes:

- openid
- profile
- my-custom

In the consent screen, the user may choose to provide the openid and profile scopes, but not the my-custom scope. The user then chooses to "remember" this so that they are not prompted again later.

The issue occurs as follows. In the persisted grant store, the scopes openid and profile will be saved. When time comes for the user to login again, the validation is performed. The particular check of interest is in the `DefaultConsentService.RequiresConsentAsync` method. In the very last check, an intersect is being performed:

```csharp
if (consent.Scopes != null)
{
	var intersect = scopes.Intersect(consent.Scopes);
	var different = scopes.Count() != intersect.Count();

	if (different)
	{
		Logger.LogDebug("Consent found in consent store is different than current request, consent is required");
	}
	else
	{
		Logger.LogDebug("Consent found in consent store is same as current request, consent is not required");
	}

	return different;
}
```

In this particular line: `var intersect = scopes.Intersect(consent.Scopes);` the requested scopes (which are all three from the client) is intersected with the consented scope from the previous login (which is only 2, the other one was not granted). This will result in `different` always being `true`, which means that the consent screen will be displayed again, and thus not being remembered.

Instead of:
```csharp
var intersect = scopes.Intersect(consent.Scopes);
var different = scopes.Count() != intersect.Count();
```

shouldn't it be:
```csharp
var intersect = consent.Scopes.Intersect(scopes);
var different = consent.Scopes.Count() != intersect.Count();
```

Again, this logic seems to work only if all scopes requested by the client are selected. In that situation, consent screen is not displayed again. However, if one of the scopes are not selected by the user, but others are, then consent screen will be displayed again even if "remember my decision" was selected.

**Comment by brockallen** [comment]
If the client keeps asking for more scopes, we will re-prompt. That's how it's always been implemented.

**Comment by darena-mhaque** [comment]
What if the client asks for the _same_ scopes though, not more. For example if the client asks for scope1 and scope2, but the user only granted scope1 and wanted to remember this decision, the next time the user logs in, the consent screen is still shown again (even though the client has asked for the same exact scopes, scope1 and scope2). This occurs because of the `intersect` logic I highlighted above.

Unless you mean to say that the client should keep a record of what scopes were granted per user so that the client does not request scopes any more than what was granted in a previous login. Of course, this won't work because the client doesn't know the user before login, so it can't possibly know how to filter scopes being requested.

**Comment by brockallen** [comment]
We'd need to persist the scopes the user omitted in addition to the ones they consented to. We don't do that currently.

**Comment by darena-mhaque** [comment]
Can this issue be made into a feature request with that? I think this change should be done because otherwise "remember my decision" doesn't really have meaning if the decision isn't actually remembered and the consent screen is always displayed again if only a subset of the requested scopes were granted.

I myself have created my own consent service to workaround this. I have also added logic into the application where if any part of the client changes (scopes, name, TOS, etc.), then I delete the persisted grant which means the consent screen is displayed to the user again.

**Comment by brockallen** [comment]
I wonder if the new incremental authorization spec is better suited for this? If/when it becomes a real spec, we can implement it in Duende IdentityServer.
