### ISSUE TITLE
CORS setup doesn't seem to work

### ISSUE THREAD

**Issue by nklap** [IdentityServer/IdentityServer4#465]
I'm trying to test the Client Credentials flow with Postman. Unfortunately I'm receiving the following warning:

CorsPolicyService did not allow origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop

**Here is my setup**

```
services.AddDeveloperIdentityServer()
                .AddInMemoryClients(IdentityConfig.GetClients())
                .AddInMemoryScopes(IdentityConfig.GetScopes())
                .AddInMemoryUsers(IdentityConfig.GetUsers());
```

```
public static List<Client> GetClients()
{
    return new List<Client> 
    {
        new Client 
        {
            ClientId = "f9907d84-d4ca-49f0-ac9e-795c838006a6",
            AllowedGrantTypes = GrantTypes.ClientCredentials,
            ClientSecrets = new List<Secret> 
            {
                new Secret("fff40907faa4428eb9c2bf3b3d55b95c".Sha256())
            },
            AllowedScopes = new List<string> 
            {
                "test"
            },
            AllowedCorsOrigins = new List<string> 
            {
                "chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop"
            }
        }
    };
}
```

```
public void ConfigureDevelopment(IApplicationBuilder app, ILoggerFactory logger)
{
    logger.AddConsole();
    app.UseDeveloperExceptionPage();
    app.UseDatabaseErrorPage();
    app.UseCors(options =>
    {
        options.AllowAnyHeader();
        options.AllowAnyMethod();
        options.AllowAnyOrigin();
        options.AllowCredentials();
    });
    app.UseIdentity();
    app.UseIdentityServer();
    app.UseStaticFiles();
    app.UseMvcWithDefaultRoute();
}
```

**The request:**

http://localhost:5000/connect/token?grant_type=client_credentials&scope=test&client_id=f9907d84-d4ca-49f0-ac9e-795c838006a6&client_secret=fff40907faa4428eb9c2bf3b3d55b95c

**The log:**

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://localhost:5000/connect/token?grant_type=client_credentials&scope=test&client_id=f9907d84-d4ca-49f0-ac9e-795c838006a6&client_secret=fff40907faa4428eb9c2bf3b3d55b95c  0
warn: IdentityServer4.CorsPolicyProvider[0]
      CorsPolicyService did not allow origin: chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop

I am not sure if there's anything missing as I couldn't find more Info on CORS in the docs.

**Comment by code-bio** [comment]
It seems you are using the browser extension. Use the new standalone version of Postman instead:
https://www.getpostman.com/apps

**Comment by nklap** [comment]
I didn't know they have a standalone version for Windows. Thank you for the hint, I'll try it out.
