### ISSUE TITLE
LogoutRequest.Parameters always empty

### ISSUE THREAD

**Issue by imcc** [IdentityServer/IdentityServer4#4655]
`LogoutMessage.Parameters` is type of NameValueCollection, so `EndSessionResult` -> `ExecuteAsync()` -> `_logoutMessageStore.WriteAsync(msg)` -> ` ObjectSerializer.ToString(message)`  will lose the NameValueCollection\`s Value, causing loss of data. For example, {"Parameters":["name" : "test"]} will be serialized to {"Parameters":["name"]}.

At the same time, `LogoutMessage.Parameters` is read-only, so it will be ignored when deserializing in `DefaultIdentityServerInteractionService.GetLogoutContextAsync()`. This causes the `LogoutRequest.Parameters` to always be empty.

``` cs
public class EndSessionResult : IEndpointResult
{
    ...
    public async Task ExecuteAsync(HttpContext context)
    {
        ...
        id = await _logoutMessageStore.WriteAsync(msg);
    }
}

public class ProtectedDataMessageStore<TModel> : IMessageStore<TModel>
{
    ...
    public virtual Task<string> ReadAsync(Message<TModel> message)
    {
        ...
        // 
        var json = Encoding.UTF8.GetString(bytes);

        // LogoutMessage.Parameters is read-only, so it will be ignored.
        result = ObjectSerializer.FromString<Message<TModel>>(json);
        ...
    }

     public virtual Task<string> WriteAsync(Message<TModel> message)
     {

        // lost NameValueCollection data 
        var json = ObjectSerializer.ToString(message);
        ...
     }
}
```

**Comment by brockallen** [comment]
Confirmed and PR submitted. Thanks!
