### ISSUE TITLE
How to mock the DbSet of the ConfigurationDbContext class

### ISSUE THREAD

**Issue by diegodalben** [IdentityServer/IdentityServer4#4656]
Hello!

I'm using the ConfigurationDbContext class in my repository. 
It's now necessary to create the unit tests for this repository. However, it's not possible to mock the DbSet's because they are not virtual members.
Is there any behavior not recommended in injecting the IConfigurationDbContext interface instead of the concrete class (ConfigurationDbContext)? Or is a change necessary to allow the DbSet to be overridable in the ConfigurationDbContext class, allowing its mock?

Note: It's not possible to inform the CancellationToken object to the SaveChangesAsync method when using the IConfiguration DbContext interface. The ConfigurationDbContext class allows you to inform.

**Comment by bryantlikes** [comment]
Have you looked at the existing tests in the source code? 

https://github.com/IdentityServer/IdentityServer4/tree/main/src/EntityFramework.Storage/test

**Comment by diegodalben** [comment]
> Have you looked at the existing tests in the source code?
> 
> https://github.com/IdentityServer/IdentityServer4/tree/main/src/EntityFramework.Storage/test

**Comment by diegodalben** [comment]
Yeah! ConfigurationDbContext is being used in integration tests, with a database in memory. I need to perform the mock for unit tests.

**Comment by brockallen** [comment]
Personally I've just always configured the in-memory EF DB for testing. Would that work for you?

**Comment by diegodalben** [comment]
I use in-memory EF Db for integration tests, for unit tests I believe it isn't the best way. I like to work with mock the repositories, defining fake collections to setup the DbSets.

**Comment by diegodalben** [comment]
Hi,

Is it possible to inject IConfigurationDbContext and the ConfigurationStore work perfectly with the ConfigurationDbContex implementation?
That way, I can run the mock without problems.

Tks

**Comment by brockallen** [comment]
Did you try? I think this is what some of our tests use?

**Comment by diegodalben** [comment]
I tried to perform the test but I couldn't because the IConfigurationDbContext interface no longer has the signature for SaveChanges(), which was removed according to https://github.com/IdentityServer/IdentityServer4/issues/3732
