### ISSUE TITLE
AddSigningCredential using x509 cert from Azure KeyVault

### ISSUE THREAD

**Issue by theonesuperdave** [IdentityServer/IdentityServer4#4658]
### Question
I have been loosely following @damienbod 's example [here](https://damienbod.com/2020/04/09/using-certificates-from-azure-key-vault-in-asp-net-core/) to fetch an X509 cert from `Azure KeyVault` to use for signing credentials in my app service. I am able to access the key vault and fetch the cert just fine from Azure. However, after adding it as a signing credential for Identity Server 4, no signing keys are available at the `jwks` endpoint (`.well-known/openid-configuration/jwks`), and I get the following error when attempting to generate tokens: `No signing credential is configured. Can't create JWT token`.

- everything works fine using `AddDeveloperSigningCredential()`
- everything works fine using a different cert from local disk (see reference sample below)
- no errors from `AddSigningCredential(...)`
- same behavior locally and also in Azure App Service using a system-assigned MI
- cert in `Azure KeyVault` was generated using `Azure Key Vault` 
- tried generating a cert from local PKI server and uploading it to `Axure KeyVault`; same issue

I have compared the cert that works versus the one that does not, and do not see any real differences. Both are `RSA`, and I verified the private keys in each. It seems like the cert generated from and hosted in `Azure KeyVault` is either missing some information or not being fetched properly. Any ideas on what to try next?

### Minimal working example
It works for a "local" cert, but no keys are recognized when a different cert is fetched from `Azure KeyVault` and no errors from `AddSigningCredential` in `Startup.cs`.

#### Works using file from disk
```csharp
       var certFileName = Configuration.GetSection("TokenSigning").GetValue<string>("fileName");
       var certKey = Configuration.GetSection("TokenSigning").GetValue<string>("key");
       var cert = new X509Certificate2(certFileName, certKey);
       builder.AddSigningCredential(cert);
```

#### Does NOT work using cert fetched from `Azure KeyVault`
```csharp
            string KEY_VAULT_IDENTIFIER = Configuration.GetValue<string>("KeyVault:identifier");
            string CERTIFICATE_NAME = Configuration.GetValue<string>("KeyVault:certificateName");
 
            var azureServiceTokenProvider = new AzureServiceTokenProvider();
            string accessToken = await azureServiceTokenProvider.GetAccessTokenAsync("https://vault.azure.net");
            var kvClient = new KeyVaultClient((authority, resource, scope) => azureServiceTokenProvider.KeyVaultTokenCallback(authority, resource, scope));
            var cert = await kvClient.GetCertificateAsync(KEY_VAULT_IDENTIFIER, CERTIFICATE_NAME);
            var certificateSecret = await kvClient.GetSecretAsync(cert.SecretIdentifier.Identifier);
            var privateKeyBytes = Convert.FromBase64String(certificateSecret.Value);

            X509Certificate2 certificate = new X509Certificate2(privateKeyBytes,
                (string)null,
                X509KeyStorageFlags.MachineKeySet);
            builder.AddSigningCredential(certificate);
```

### Relevant parts of the log file
The error below is seen when attempting to generate JWT tokens from the TokenEndpoint.
```
System.InvalidOperationException: No signing credential is configured. Can't create JWT token
   at IdentityServer4.Services.DefaultTokenCreationService.CreateHeaderAsync(Token token)
   at IdentityServer4.Services.DefaultTokenCreationService.CreateTokenAsync(Token token)
   at IdentityServer4.Services.DefaultTokenService.CreateSecurityTokenAsync(Token token)
```

**Comment by bryantlikes** [comment]
I'm using a certificate stored in Azure KeyVault. Here is how I've set it up.

1) Make sure you have the [KeyValue Nuget Package](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureKeyVault/3.1.5?_src=template). 

2) Add the KeyVault name to your appsettings.json. 

3) Setup the KeyVault client in the Program.cs/CreateHostBuilder. 

``` c#
      .ConfigureAppConfiguration((context, config) =>
                {
                    if (context.HostingEnvironment.IsProduction())
                    {
                        var builtConfig = config.Build();

                        var azureServiceTokenProvider = new AzureServiceTokenProvider();
                        var keyVaultClient = new KeyVaultClient(
                            new KeyVaultClient.AuthenticationCallback(
                                azureServiceTokenProvider.KeyVaultTokenCallback));

                        config.AddAzureKeyVault(
                            $"https://{builtConfig["KeyVaultName"]}.vault.azure.net/",
                            keyVaultClient,
                            new DefaultKeyVaultSecretManager());
                    }
                })
```

4) Use the cert in the statup. 

``` C#
            if (Environment.IsDevelopment())
            {
                builder.AddDeveloperSigningCredential();
            }
            else
            {
                var key = Configuration["YOUR-KEY-NAME"];
                var pfxBytes = Convert.FromBase64String(key);
                var cert = new X509Certificate2(pfxBytes, (string)null, X509KeyStorageFlags.MachineKeySet);
                builder.AddSigningCredential(cert);
            }
```

You'll also need to make sure you've setup the correct access to read the key from the key vault.

**Comment by theonesuperdave** [comment]
Man, I don't know what the fundamental difference is in our two approaches, but that works. Thanks, @bryantlikes! Must be some plumbing between fetching it "manually" versus the KeyVault Config provider. I don't see a difference in the cert once it is loaded into memory, but ID4 adds the signing credentials just fine for two different certs hosted in KeyVault now. Hopefully, this helps someone else if they encounter the issue.

**Comment by theonesuperdave** [comment]
Putting this here in case someone else runs into it. It would seem there is a bug somewhere in the MS Azure KeyVault plumbing. Forcing the below async function to run synchronously allows for the signing keys to be set in ID4; both ways return what looks like a perfectly fine X509 cert from Az KeyVault.

`var certificateSecret = await kvClient.GetSecretAsync(KEY_VAULT_IDENTIFIER, CERTIFICATE_NAME);`

##### This Code Works Just Fine
Startup.cs (`ConfigureServices`)
 ```csharp
var azureServiceTokenProvider = new AzureServiceTokenProvider();
var kvClient = new KeyVaultClient((authority, resource, scope) => azureServiceTokenProvider.KeyVaultTokenCallback(authority, resource, scope));
var certificateSecret = kvClient.GetSecretAsync(KEY_VAULT_IDENTIFIER, CERTIFICATE_NAME).Result;
var privateKeyBytes = Convert.FromBase64String(certificateSecret.Value);

X509Certificate2 Certificate = new X509Certificate2(privateKeyBytes,
  new SecureString(),
  X509KeyStorageFlags.MachineKeySet |
  X509KeyStorageFlags.PersistKeySet |
  X509KeyStorageFlags.Exportable);
builder.AddSigningCredential(Certificate);
```
