### ISSUE TITLE
IdentityServer4.EntityFramework.Storage has dependency on AutoMapper version lower than 10

### ISSUE THREAD

**Issue by GeraldLx** [IdentityServer/IdentityServer4#4663]
We upgradet lately our source base to the latest version of AutoMapper (10) and now I have a problem in my Identity Server project cause there is a constraint in the NuGet package dependencies:
AutoMapper (>= 9.0.0 && < 10.0.0)

Is there any reasoning behind this? If not can we have an updated version?

**Comment by nimrod46** [comment]
Probably related #4662 #4611

**Comment by GeraldLx** [comment]
Damn, I explicitly searched for AutoMapper before posting, but search did not find anything (cause I searched in open issues not pull requests).

#4662 is about someone trying to use AutoMapper 8. Personally I find this behavior ok. The IdentityServer library requires version 9 or higher. Almost every NuGet package demands a minimum version of some other library.

My ticket is a copy of #4611, cause limiting the dependency is a rare thing. While it may be a safe approach saying I only testet this version, I basically block anyone else from upgrading.

So in a way most libraries lie by saying I will work with any future version ;)

**Comment by nimrod46** [comment]
> #4662 is about someone trying to use AutoMapper 8. Personally I find this behavior ok. The IdentityServer library requires version 9 or higher. Almost every NuGet package demands a minimum version of some other library.

I think version 8 of `AutoMapper.Extensions.Microsoft.DependencyInjection` is equivalent to `AutoMapper` version 10 the issue is true for both of them
