### ISSUE TITLE
How to prevent re-attempt of token generation of external token based authentication scheme

### ISSUE THREAD

**Issue by githugt** [IdentityServer/IdentityServer4#4664]
Let's say I as a user requested to login to my website via google login. This is achieved by passing the token generated by Google. And then validating that. Presumably, this was done at a shady cafe that logged my request and response. Therefore, the cafe now has access to the google token that was passed. And so could ask to fetch a new token by simply requesting the same request again, as long as the google token is valid. 

Therefore, assuming the google token and my own website token is valid for 60 minutes, the cafe owner could then make a request at the 59-minute mark and generate a fresh new website token which is valid for another 60 minutes. 

Is this a problem that has been solved here?

**Comment by githugt** [comment]
Are we allowed to bump topics? (I am not sure. Feel free to delete the thread if in case that isn't allowed).
Also, why did the bot add the **wontfix** tag?

**Comment by brockallen** [comment]
Use HTTPS; that's a requirement.

**Comment by githugt** [comment]
Since this is a case where the machine itself is compromised, how does HTTPS here help? Because whatever private key was generated during the HTTPS handshake would be known. no?

**Comment by brockallen** [comment]
Oh that's what you meant by shady cafe? I thought you meant their wifi was being monitored. 

Yea, for a compromised machine I can't help you, nor can the protocols. If the machine's compromised, then it key logged the user's uid/pwd anyway. Don't enter credentials into untrusted machines.

**Comment by githugt** [comment]
>Oh that's what you meant by shady cafe?

Yup. Sorry I wasn't clear in my initial post.
Thank you for your help. 👍
