### ISSUE TITLE
Using IdentityServer without EntityFramework

### ISSUE THREAD

**Issue by a-a-k** [IdentityServer/IdentityServer4#4667]
Hi folks!
I'm trying to practice with _Asp.Net Core 3.1 SPA Template with individual authentication_. It creates a project with all auth stuff already implemented on backend and frontend. There in `Startup.cs --> ConfigureServices` exists this line
` services.AddIdentityServer().AddApiAuthorization<ApplicationUser, ApplicationDbContext>();`. Since I don't want use EF I'm wondering how to pass there my implementation of `ApplicationDbContext` which doesn't inherit EF `DbContext`.
This is only one issue I've faced with, may be there much more and I would like hear all the opinions you have.
Thanks!

**Comment by leastprivilege** [comment]
This seems to be related to Microsoft's IdentityServer integration. Please open an issue on their issuer tracker instead. @javiercn @blowdart

https://github.com/aspnet/aspnetcore/issues

**Comment by blowdart** [comment]
Kind of. It's Identity as a whole, which is very focused on EF. This, frankly is by design, and so we currently require EF. This won't change for the foreseeable future.
