### ISSUE TITLE
what to set in  "OpenIdConnectOptions.Authority" while running in docker container ? 

### ISSUE THREAD

**Issue by Dheerajmentor** [IdentityServer/IdentityServer4#4668]
Hello All , 

I am having problem in implementing authentication for client app(Web APP asp.net core 3.1) with identity server 4. 
Details 
I have developed a solution with 

1. Gateway- Ocelot(latest)
2. Sample API - Asp.net core 3.1
3. Identity service - Identity server 4 (latest) 
4. Web App -Asp.net core 3.1

all above projects are running under docker with docker compose. 

i am using granttype as Hybrid and trying to make authenticate work.  

Web App Startup 

```
 public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            services.AddAuthentication(options =>
            {
                Microsoft.IdentityModel.Logging.IdentityModelEventSource.ShowPII = true;
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            }).AddCookie("Cookies")
               .AddOpenIdConnect("oidc", options =>
                {
                    options.SignInScheme = "Cookies";

                    options.Authority = "http://identityserver";
                    options.RequireHttpsMetadata = false;

                    options.ClientId = "MS.UI";
                    options.ClientSecret = "z71C0PyDjR";
                    options.ResponseType = "code id_token";

                    options.SaveTokens = true;
                    options.GetClaimsFromUserInfoEndpoint = true;

                    options.Scope.Add("sampleapi.read");
                    options.Scope.Add("offline_access");
                    
                });
           
        }
 public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            //app.UseHttpsRedirection();
            app.UseAuthentication();

            app.UseStaticFiles();

            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }

```
Web App registration in Identity server 

```
public static IEnumerable<Client> Clients =>
            new Client[] 
            {
                new Client(){ 
                    ClientId = "MS.UI",
                    AllowedGrantTypes = GrantTypes.Hybrid,
                    AllowOfflineAccess = true,
                    ClientSecrets = { new Secret("z71C0PyDjR".Sha256()) },
                    RedirectUris ={"http://localhost:5003/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:5003"},
                    FrontChannelLogoutUri = "http://localhost:5003/signout-oidc",
                    AllowedScopes = {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        "sampleapi.read"
                    },
                },
            
            };
```

i have added [Authorize] attribute on an action method as below  
```
        [Authorize]
        public IActionResult Privacy()
        {
            return View();
        }
```
### Question
when i run all the containers and click on privacy link on web page i get redirected to below url , 

`http://identityserver/connect/authorize?client_id=MS.UI&redirect_uri=http%3A%2F%2Flocalhost%3A5003%2Fsignin-oidc&response_type=code%20id_token&scope=openid%20profile%20sampleapi.read%20offline_access&response_mode=form_post&nonce=637307704380796477.Y2I3ZWU2ZGYtM2JmZC00YzM5LTkzNTYtZjViODdiYTgyMjcwMTY4NmFjYzUtODRkYi00YzBhLTk2ZmItMzZjY2U4YmQ4MTM5&state=CfDJ8DijVzAh2XJHu0bjE4_F-h91Q8_54uzjK5mvWqhDPtbVKIPdFE20-vLUVWjIflj1q4FkY6uQkA27ifjGWpGdjawgpY1pyM8XpeDW-QriKnrJwjtCTihnu7Xqw7FU_FsjnY2zTDxd3f0b_OgALMFzqpC8BDb44kn8vqqf-Kmaj4AhTi2fhhZ_Qkb5cc1SEkdLUjvnFhRZtBnM6W6_zUiju_YeKf_2eZxpdDVlMCGOL4Gjup7VJ_3f5D3OIWYi0UjTs7fvpBCAjwRQsylDIuxwE8Kvu48cnH1357mAjxw-Mumw6Jre_eYdT9iKIfdr1PwKJQ&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0`

in above url please observe that host is 
`"http://identityserver"`
 which is what i set in
 `options.Authority = "http://identityserver";`

i have to set this to `"http://identityserver"` as this the name of container. if i set it to `"http://localhost:5002"` then it give me below error 
```
OException: IDX20804: Unable to retrieve document from: 'http://localhost:5002/.well-known/openid-configuration'.
```
which i believe make send because webapp container is pointing to locahost to self not to indentity server.

Please help me solve this . 
I have also created a public repo of same code at 
`https://github.com/Dheerajmentor/Microservice.git` , 

I really need to solve this issue asap. please help.

thank you 
Dheeraj Kumar

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by GasyTek** [comment]
Hi ,

The workaround is to set the "IssueUrl" property to a fixed value as explained here : https://stackoverflow.com/questions/43911536/how-can-i-use-identityserver4-from-inside-and-outside-a-docker-machine

This has drawbacks and doesn't work for instance if you want to use Swagger + OpenId with your api.

I'm also looking for a cleaner solution without success until now ..

Riana
