### ISSUE TITLE
#449 Continued: Automatic token refresh dosn't update external tokens

### ISSUE THREAD

**Issue by NickyM** [IdentityServer/IdentityServer4#467]
Since I don't know if you read the updates in the questions marked as "Closed", I'll write copy my latest response from [#449](https://github.com/IdentityServer/IdentityServer4/issues/449) to here:

Just delete this, and remove the closed-tag from the other, if that is better.

---------

Hehe, I'm not even close to having what I need..

Maybe my last posts was hard to understand, my brain maybe went full ADHD mode. 

As I said, I have managed to get IndentityServer to get UserInfo by on token token refreshes by storing the external accesstoken in a custom claim, and accessing it in a CustomTokenRequestValidator using UserInfoClient from IndentityModel. 

That part works like a charm. Unless, my accesstoken has expired. then I need to refresh that access token, by telling the client, that it has to do a full token refresh roundtrip. I have thought of some possible ways to do this, but I'm not sure if it can be done, or how?

- From the CustomTokenRequestValidator: How do I logout an user?
- From the CustomTokenRequestValidator: How do I tell, that the token could not be refreshed?
- From the CustomTokenRequestValidator: How do I perform a redirect?
- How to I tell IdSrv4 to invalidate all refreshtokens and accesstokens from a specific user?

If sets - CustomTokenRequestValidationContext.Result.IsError to true, when it just results in an exception in the IdentityServer.

_What I really hope to do, is to update userinfo from the IDP every 15 minutes. If accesstoken or refresh token i still valid, then it should be OK. If access token has expired, and refresh token is expired/invalidated, then the user should be forced to login again._

Please ask me to refraise, if it still doesn't make any sense. I have faceslammed my keyboard enough these last days :)

**Comment by brockallen** [comment]
i'll close since i added to the other issue
