### ISSUE TITLE
Autofac v10 not working properly with IdentityServer4

### ISSUE THREAD

**Issue by marzoukali** [IdentityServer/IdentityServer4#4673]
### Issue / Steps to reproduce the problem

Autofac v10.0 not working properly with IdentityServer 4.0.3. I ended up downgraded Autofac to v9.0 and it works fine.

Below is a record from my logging system contains the detailed exception:

> {"Timestamp":"2020-07-22T05:25:28.5128967+02:00","Level":"Error","MessageTemplate":"API!!! Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'. -- {ErrorId}.","Exception":"System.MissingMethodException: Method not found: '!!0 AutoMapper.IMapper.Map(System.Object)'.\r\n at IdentityServer4.EntityFramework.Mappers.ClientMappers.ToModel(Client entity)\r\n at IdentityServer4.EntityFramework.Stores.ClientStore.FindClientByIdAsync(String clientId)\r\n at IdentityServer4.Stores.ValidatingClientStore`1.FindClientByIdAsync(String clientId)\r\n at IdentityServer4.Stores.IClientStoreExtensions.FindEnabledClientByIdAsync(IClientStore store, String clientId)\r\n at IdentityServer4.Validation.ClientSecretValidator.ValidateAsync(HttpContext context)\r\n at IdentityServer4.Endpoints.TokenEndpoint.ProcessTokenRequestAsync(HttpContext context)\r\n at IdentityServer4.Endpoints.TokenEndpoint.ProcessAsync(HttpContext context)\r\n at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)\r\n at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)\r\n at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)\r\n at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)\r\n at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\r\n at Mda.Infrastructure.Middleware.ExceptionMiddleware.ExceptionMiddleware.Invoke(HttpContext context) in C:\Users\10\Desktop\stormra\mda\code\Mda.Auth\src\Infrastructure\Mda.Infrastructure\Middleware\ExceptionMiddleware\ExceptionMiddleware.cs:line 29","Properties":{"ErrorId":"66167054-4a56-4d56-9941-4680d27e2828","SourceContext":"Mda.Infrastructure.Middleware.ExceptionMiddleware.ExceptionMiddleware","RequestId":"0HM1DTRDIGR9K:00000007","RequestPath":"/connect/token","SpanId":"|9bebd43c-46e12d1acc9c01eb.","TraceId":"9bebd43c-46e12d1acc9c01eb","ParentId":"","ConnectionId":"0HM1DTRDIGR9K"}}

You can see the discussion here in the PR of `Allow Automapper` which had the same issue and it fixed in 4.0.3: https://github.com/IdentityServer/IdentityServer4/pull/4611

**Comment by brockallen** [comment]
PR submitted https://github.com/IdentityServer/IdentityServer4/pull/4677
