### ISSUE TITLE
Allowlist for Authorize Request Objects 

### ISSUE THREAD

**Issue by user1336** [IdentityServer/IdentityServer4#4675]
We would like to implement an allowlist for Authorize Request Objects so we can prevent requests to untrusted sources.

The spec says:
>  To prevent such attack to succeed, the server should (a) check that
 >  the value of "request_uri" parameter does not point to an unexpected
>   location."

https://tools.ietf.org/html/draft-ietf-oauth-jwsreq-23#section-10.4 

I'm aware we can implement our own `IJwtRequestUriHttpClient` and implement the behaviour described in 10.4.* and create a list with allowed endpoints that we can request.

We can also set a property on the `Client` with an allowlist so we can prevent requests to unexpected locations.
How do you feel about this?

**Comment by leastprivilege** [comment]
We won't add this to the core - but added all the necessary extensibility points we think.

The long term solution to this will be PAR (https://tools.ietf.org/wg/oauth/draft-ietf-oauth-par/) IMO.

**Comment by user1336** [comment]
Out of curiousity: why don't you consider this as a core feature?
I can confirm that the extensibility points are in place so it's quite easy to prevent requests to untrusted sources.

PAR makes sense to me, this helps mitigate possible SSRF issues.

**Comment by leastprivilege** [comment]
because

https://tools.ietf.org/html/draft-ietf-oauth-jwsreq-25#section-10.4

And as stated above - the real solution IMO is to provide a "drop location" for jws requests. And that's called PAR. We will add PAR once it is stable.
