### ISSUE TITLE
IDServer oauth MTLS Client

### ISSUE THREAD

**Issue by sbodese** [IdentityServer/IdentityServer4#4678]
Hi,
thanks for this great work and project!

Well, my question is: Is it possible to include the ca-chain also for the mtls *client* like curl with the option ;
--cacert /ca-chain.cert.pem?
I'm missing the client cert-handler as the second -mutual - cert check option for the client.
So, at least: Which mtls standard is supported by this idserver mtls client?

Thanks!
Greeting 
Steffen

**Comment by leastprivilege** [comment]
> idserver mtls client

What do you mean with that?

Have you read our docs?
https://identityserver4.readthedocs.io/en/latest/topics/mtls.html

**Comment by sbodese** [comment]
yes, i read these helpfully docs, but i only see a client cert handler, not a handler for the ca-chain to validate -mutual- the server response at the client side

**Comment by leastprivilege** [comment]
not sure I follow.

In .NET HttpClient is the default client API. Check their docs.
