### ISSUE TITLE
maximum length of state value in authorization request parameters

### ISSUE THREAD

**Issue by 12dinesh12** [IdentityServer/IdentityServer4#4679]
### Question
I need a clarification around the restriction on maximum length for state value in authorisation request.
Currently identity server library only supports configuration for nonce value which can be enforced using InputLengthRestrictions.nonce value in IdentityServerOptions, but i do not see a support to setup the maximum length for state parameter. Can someone explain if it is purposely missing or is there a plan to add that support in future?

```csharp
            //////////////////////////////////////////////////////////
            // check state
            //////////////////////////////////////////////////////////
            var state = request.Raw.Get(OidcConstants.AuthorizeRequest.State);
            if (state.IsPresent())
            {
                request.State = state;
            }
-------------
               //////////////////////////////////////////////////////////
            // check nonce
            //////////////////////////////////////////////////////////
            var nonce = request.Raw.Get(OidcConstants.AuthorizeRequest.Nonce);
            if (nonce.IsPresent())
            {
                if (nonce.Length > _options.InputLengthRestrictions.Nonce)
                {
                    LogError("Nonce too long", request);
                    return Invalid(request, description: "Invalid nonce");
                }

                request.Nonce = nonce;
            }
```

**Comment by leastprivilege** [comment]
I can't remember.

State is used in many different ways, maybe that's why we haven't put a length restriction on it. Maybe we forgot.

**Comment by 12dinesh12** [comment]
@leastprivilege : is there a plan to add support for that? It would definitely be useful to stop bloating the query parameters.

**Comment by leastprivilege** [comment]
> bloating

Which scenario do you have in mind?

**Comment by 12dinesh12** [comment]
When state value is passed as part of query parameters in auth request, the server cannot handle it and returns 405. there should be a way to override the behaviour and returns invalid_request error. Identity provider should have more control on the error message and should not rely on the default error messages.

**Comment by leastprivilege** [comment]
Well - if the query string length exceeds the allowed limit for the web server, it will generate an error. That is beyond our control.
