### ISSUE TITLE
How can I login from the login page?

### ISSUE THREAD

**Issue by ramihamati** [IdentityServer/IdentityServer4#4680]
I  have IdentityServer 4 setup with SignInManager and UserManager and a custom store in mongo.

I my AccountController.cs I have
```
   if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberLogin, lockoutOnFailure: true);
                if (result.Succeeded)
                {
                    var user = await _userManager.FindByNameAsync(model.Username);
```
I want to be able to simply go to the loginpage (serverhost/account/login) and type the username and password and login. I am getting the error "sub claims is missing".

I added the ProfileService but this does not get called (from what I see it's being called by the DefaultTokenService.CreateIdentityTokenAsync ).

**Comment by brockallen** [comment]
Have you done this: https://identityserver4.readthedocs.io/en/latest/reference/aspnet_identity.html

**Comment by ramihamati** [comment]
> Have you done this: https://identityserver4.readthedocs.io/en/latest/reference/aspnet_identity.html

Right. I missed adding AddAspNetIdentity<>(). 

That was missing. Thanks!
