### ISSUE TITLE
Token/Introspect is not working

### ISSUE THREAD

**Issue by Mtank21** [IdentityServer/IdentityServer4#4682]
I have project using Identity server 4, I am using connect/token to generate token, password grant, I am not using Client Secret when calling connect/token.
I have a different client api from which I need to validate token (thru connect/introspect). I am not sure how to use basic auth without Client Secret will work, it always gives me 401 unauthorized error.
Also, another issue I observed, I am using certificate for IdServer (not developer's credentials), but when I generate token from server and try to use locally it always fails. Not sure if I am doing anything wrong.
Any help will be appreciated.

**Comment by brockallen** [comment]
Set an ApiSecret: https://identityserver4.readthedocs.io/en/latest/reference/api_resource.html

and see this: https://identityserver4.readthedocs.io/en/latest/topics/resources.html#api-resources

**Comment by Mtank21** [comment]
Can connect/introspect work without Client Id and Client secret? I am able to generate token without client secret. I am stuck at verifying the token. For now I am just using postman to verify the api calls. The document link did not help much.

**Comment by leastprivilege** [comment]
the introspection endpoint requires authentication.
