### ISSUE TITLE
Identity Server 4 - Password Policy

### ISSUE THREAD

**Issue by Mtank21** [IdentityServer/IdentityServer4#4683]
I want to implement use password functionality where user should not be able to use last 5 used password. I am try to customize and store hash password in DB. PasswordHasher.HashPassword returns hash password. But when I run PasswordHasher.VerifyHashedPassword it fails. Present hash password and hash password stored in DB are different values. They never match. I am definitely missing something but not sure how to fix it.

**Comment by brockallen** [comment]
StackOverflow is a more appropriate place for your question. 

If you or your company need commercial support, please see [here](https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support) for more information.

Thanks!
