### ISSUE TITLE
JwtClaimType.IdentityProvider claim issue

### ISSUE THREAD

**Issue by jigneshpanchal22** [IdentityServer/IdentityServer4#4686]
### Question
I'm always getting IdentityProvider claims  values as "local" even I set it as provider in external authentication flow.

### This is how I set claim

```
idsrvUser.AdditionalClaims.Add(new Claim(JwtClaimTypes.IdentityProvider, provider));

await HttpContext.SignInAsync(user: idsrvUser,
                properties: authProperties);
```

while logout getting claim like this
```
var idp = user.FindFirst(JwtClaimTypes.IdentityProvider)?.Value;
````

where I always get value as "local"

**Comment by leastprivilege** [comment]
Works in our test host:

![image](https://user-images.githubusercontent.com/1454075/92450753-195ea480-f1bc-11ea-9ce4-b16ef5a32089.png)

Maybe use that and see what's different in your code.
