### ISSUE TITLE
A small document carry over from older version

### ISSUE THREAD

**Issue by BenHayat** [IdentityServer/IdentityServer4#4689]
In Defining an API Scope & Defining the client section of documentation, It should be an array and not list, according to the new 4.x code.

**Comment by brockallen** [comment]
Are you talking about the docs or the quickstarts?

**Comment by brockallen** [comment]
Do you have a link, or you can send a PR please.

**Comment by brockallen** [comment]
I can't tell where exactly you mean @BenHayat, so I'm going to close for now. If you still have issues, feel free to reopen.
