### ISSUE TITLE
Wellknown config with subpath Question

### ISSUE THREAD

**Issue by stephenlautier** [IdentityServer/IdentityServer4#4700]
### Question

We have our identityserver4 hosted with a subpath e.g. http://xyz.com/v1 - the subpath `/v1` coming from nginx.

The problem within the `/.well-known/openid-configuration` endpoint, the endpoints are omitting the `/v1` as follows:

```json
"issuer": "https://heimdall.nk.dev",
"jwks_uri": "https://heimdall.nk.dev/.well-known/openid-configuration/jwks",
"authorization_endpoint": "https://heimdall.nk.dev/connect/authorize",
"token_endpoint": "https://heimdall.nk.dev/connect/token",
"userinfo_endpoint": "https://heimdall.nk.dev/connect/userinfo",
"end_session_endpoint": "https://heimdall.nk.dev/connect/endsession",
"check_session_iframe": "https://heimdall.nk.dev/connect/checksession",
"revocation_endpoint": "https://heimdall.nk.dev/connect/revocation",
"introspection_endpoint": "https://heimdall.nk.dev/connect/introspect",
"device_authorization_endpoint": "https://heimdall.nk.dev/connect/deviceauthorization",
```
Is there a way to specify the subpath? or at least configure them? As i cannot find a way of doing this.

In another issue I saw someone mentioned changing the `Issuer` (and `PublicOrigin`?), however no luck yet.

Any help would be appreciated, thanks.

**Comment by brockallen** [comment]
This is not an IdentityServer issue. When you do hosting tricks like that you're expected to have your ASP.NET Core app aware of that. I think there's a call to `app.UsePathBase("/v1");` or some such that you're missing.

**Comment by stephenlautier** [comment]
Sorry i thought its somewhat related to the identity server config. Make sense to be in .netcore, never seen it to be honest.

Thanks for pointing me to the direction I will have a look.

**Comment by M0ns1gn0r** [comment]
@stephenlautier How did you solve your problem in the end?
