### ISSUE TITLE
Storing Tokens in Client Strategy

### ISSUE THREAD

**Issue by Jonatthu** [IdentityServer/IdentityServer4#4707]
After many implementations and research

The overall "accepted way" to store a JWT token and a Refresh token would the next:

JWT should be store in memory of the application.
Refresh tokens should be set in a cookie by IdentityServer4 with HttpOnly  in order to protect the refresh token.

There is a huge debate about LocalStorage is vulnerable to XSS Attacks and that's why we "would like not to use this method" so I have been looking how identity server is setting a cookie in the moment I get an access token.

I look in DefaultRefreshTokenService implementation class and I do not see any cookie manipulation or DefaultTokenService.

What identity server 4 as organization recommends to secure our tokens?

Reference:
https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/#refresh_token_persistance
https://github.com/apollographql/apollo-feature-requests/issues/149
https://reactnative.dev/docs/security#async-storage

**Comment by ngbrown** [comment]
I think the answer is to work on preventing your site from being susceptible to XSS. If an attacker can run arbitrary JavaScript code in the context of your site, they can abuse HttpOnly cookies too.

Reference: https://pragmaticwebsecurity.com/articles/oauthoidc/localstorage-xss.html
