### ISSUE TITLE
IPersistedGrantStore Kind of ConsumedTime is Unspecified. Intentional or not?

### ISSUE THREAD

**Issue by MrGroovy** [IdentityServer/IdentityServer4#4708]
Hi, the method `StoreAsync` in implementation of `IPersistedGrantStore` is called with a `PersistedGrant` instance. When the `ConsumedTime` is given it's Kind is `Unspecified`, why? `CreationTime` and `Expiration` have `Utc`.

```csharp
public async Task StoreAsync(PersistedGrant grant) {     
    // This is what i now do
    DateTime databaseValueToStore = grant.ConsumedTime is { }
        ? DateTime.SpecifyKind(grant.ConsumedTime.Value, DateTimeKind.Utc)
        : (DateTime?)null;
}
```

**Comment by brockallen** [comment]
Huh odd -- the call to `Clock.UtcNow` which is the system clock from ASP.NET returns that. I'll have to adjust their value.

**Comment by brockallen** [comment]
Ahh, it's a DateTimeOffset -- that's why. I will fix.

**Comment by brockallen** [comment]
PR submitted. thx!
