### ISSUE TITLE
SignOutAsync() - SignInManager or HttpRequest?

### ISSUE THREAD

**Issue by gatecrasher63** [IdentityServer/IdentityServer4#4709]
In the original Quickstart on which I based my code you would find

_signInManager.SignOutAsync()

but in the latest code it's

HttpContext.SignOutAsync()

Having read this article I'm a bit confused as to what I should be doing in Logout()

https://mcguirev10.com/2018/01/26/signoutasync-and-identity-server-cookies.html

It's being called from an Angular App if that's relevant

Any thoughts?

thanks

**Comment by brockallen** [comment]
> I'm a bit confused as to what I should be doing in Logout()

It depends on what you use to build your identity system and how you log the user in. So neither one is right or wrong.
