### ISSUE TITLE
OIDC available in external authentication providers

### ISSUE THREAD

**Issue by vdecristofaro** [IdentityServer/IdentityServer4#471]
I have a single deployment of a Multitenant IDS4.
On this deployment I added the chance to login locally to access management features (users, clients, etc.). This has been done by adding code like this at startup:

```
app.UseOpenIdConnectAuthentication( new OpenIdConnectOptions() {
    AuthenticationScheme = "oidc",
    SignInScheme = "Cookies",
    Authority = Configuration["Issuer:IssuerUri"],
    RequireHttpsMetadata = false,
    ClientId = "adminClient",
    SaveTokens = true
} );
```

However when I go to the login page I see that this provider is available in the list of external providers like Google

![image](https://cloud.githubusercontent.com/assets/18700475/20062260/5e0f3392-a503-11e6-8ea2-9ad64e3a2b65.png)

Is there any way to hide this?

~~Another question: is there any way to configure different External authentications for every tenant?~~

**Comment by leastprivilege** [comment]
Different questions - different issues.

You can hide by setting the `DisplayName` to empty string.

**Comment by vdecristofaro** [comment]
Actually if I set `DisplayName = string.Empty` in `OpenIdConnectOptions` the button is still created.
I have modified the view `Login.cshtml` however. Thanks.
