### ISSUE TITLE
IdentityServer4 4.0.4 doesn't work with IdentityServer4.Contrib.MongoDB 2.3.4

### ISSUE THREAD

**Issue by VladislavMorozov** [IdentityServer/IdentityServer4#4710]
**We can only help you if you are on the latest version. Either use the latest 3.x or 4.x**

I use .net core 3.1, IdentityServer4 4.0.4 with mongodb IdentityServer4.Contrib.MongoDB 2.3.4.

### Issue / Steps to reproduce the problem

configure identity server with mongo and start.

### Relevant parts of the log file

```
<log goes here>
```
![image](https://user-images.githubusercontent.com/31768904/89304018-9f477700-d675-11ea-8a35-65939d41d239.png)

**Comment by brockallen** [comment]
You'd have to contact the developers that run that project.
