### ISSUE TITLE
Method get_ClientCorsOrigin is not implemented in ApiAuthorizationDbContext

### ISSUE THREAD

**Issue by yakeer** [IdentityServer/IdentityServer4#4715]
Updated from 3.1.4 to 4.0.4,
All dependencies are in latest version.

When I run my project, I get a System.TypeLoadException: Method get_ClientCorsOrigin is not implemented in ApiAuthorizationDbContext

Not sure if it's IdentityServer4 issue, or ApiAuthrozationDbContext...
But anyone else is facing this issue?

**Comment by brockallen** [comment]
3.x to 4.x will have breaking changes. Looks like something custom you implemented no longer conforms to the interface it was implementing.

**Comment by yakeer** [comment]
I also asked in Microsoft.ASPNetCore repository, they mentioned that the latest 3.1.6 of APIAuthorization does not support IS4 yet. 
It will be supported only on v5 release.

**Comment by brockallen** [comment]
Ah so that's Microsoft's extension? Yea, then that's something you will have to sort out with them.
