### ISSUE TITLE
Can I force all the URIs in the discovery doc to be SSL when I start identityserver on http?

### ISSUE THREAD

**Issue by mahoekst** [IdentityServer/IdentityServer4#4716]
### Question
I run the service on my dev machine **http**://localhost:5001 and can access it through ngrok so I have a public SSL tunnel my test mobile can access. But when I access the discovery doc through ssl . https://004023d82ebf.ngrok.io/ .well-known/openid-configuration all the URIs in that doc are http not https. I guess since the service starts with http that’s the default. Is this something I can force to SSL?

### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by brockallen** [comment]
You need to enable the forwarded headers middleware, as you would with any reverse proxy:

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

:)
