### ISSUE TITLE
why it shows valid_scope

### ISSUE THREAD

**Issue by quliting** [IdentityServer/IdentityServer4#4724]
**We can only help you if you are on the latest version. Either use the latest 3.x or 4.x**
404
Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](http://docs.identityserver.io/en/latest/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.
![QQ截图20200809224709](https://user-images.githubusercontent.com/14035957/89735055-6272ea00-da92-11ea-958a-62e819af3523.png)

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem
i make the same scope in the code.
![2](https://user-images.githubusercontent.com/14035957/89735053-60a92680-da92-11ea-96c6-bf9abead09cf.png)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by quliting** [comment]
![2](https://user-images.githubusercontent.com/14035957/89735087-87fff380-da92-11ea-8cfa-235fd79a7a70.png)
![Uploading QQ截图20200809224709.png…]()

**Comment by brockallen** [comment]
Did you define the `ApiScope`? Also, you might want to see our migration issue: https://github.com/IdentityServer/IdentityServer4/issues/4592

**Comment by quliting** [comment]
i change the apiresource into apiscope .the error disappear,but your webbsite is apiresource and client .
http://docs.identityserver.io/en/release/quickstarts/1_client_credentials.html#defining-the-api
what should i reference.

**Comment by leastprivilege** [comment]
Not sure where the above doc link comes from - but the correct one is this:

https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html

**Comment by quliting** [comment]
thanks

**Comment by quliting** [comment]
ok ,now i do it right.thanks.
