### ISSUE TITLE
Unable to change nonce expiration time

### ISSUE THREAD

**Issue by hashmed** [IdentityServer/IdentityServer4#4728]
Hi all. I have created new sample IdentityServer4 (with UI) and consuming MVC Client app, hosting them both locally.
If I try to login with sample user within 15 minutes of opening login page, everything works fine.

However, I am unable to allow users to log in if the login page has become stale (opened for more than default 15 minutes).

I have modified OpenIdConnect configuration in the consuming MVC app by adding these to lines in order to increase remote authentication timeout (correlation cookie) and nonce expiration:
![image](https://user-images.githubusercontent.com/11403710/89789977-9a753e00-db21-11ea-888f-6d921f8624ff.png)

Inspecting the response in chrome after navigating to login page, the cookie values are correct (24h in future, minus 2h of time zone difference)
![image](https://user-images.githubusercontent.com/11403710/89789872-7a457f00-db21-11ea-9af8-2d8d24dfe8f7.png)

But if I leave the page opened for more than 15 minutes and try to log in, I get the following error:
![image](https://user-images.githubusercontent.com/11403710/89790320-0bb4f100-db22-11ea-9381-073c4e3bc560.png)

As if the change was not applied - it is reporting that nonce had expired and showing default lifetime of 15 minutes.

What am I missing here? Where is the mismatch coming from?
I've tried clearing cookies, using incognito, both Chrome and Edge - the result is always the same.

**Comment by brockallen** [comment]
That's a question for Microsoft, as that's their component.
