### ISSUE TITLE
Custom claims (.NET Identity)

### ISSUE THREAD

**Issue by FelschR** [IdentityServer/IdentityServer4#473]
Hi,

I have a microservice architecture where I created one authentication service that is using IdentityServer4 with .NET Identity to issue tokens. All the other microservices implement IdentityServer4.AccessTokenValidation for token validation.

In the other microservices I want to access claims of the authenticated users but I'm not sure how to implement it properly. In .NET Identity I add claims as usually but those don't seem to be included when a new token is generated; they are not included in User.Claims on the client.
Is there some sort of setting that I'm missing?
FYI the token currently includes the standard claims including the id of the .NET Identity user in "sub".

I hope you can help me.
Thanks!

**Comment by leastprivilege** [comment]
Claims are emitted on the IProfileService - that's where I would put my breakpoint.

**Comment by FelschR** [comment]
Thanks! This information helped me a lot.
While I was trying to implement a custom IProfileService I noticed that in my Scope configuration I only set one ScopeClaim to be transmitted. I removed the ScopeClaim and added `IncludeAllClaimsForUser = true` to the configuration and now it even works properly without a custom IProfileService.
