### ISSUE TITLE
EF PersistedGrantStore.RemoveAllAsync not removing multiple Persisted Grants

### ISSUE THREAD

**Issue by DaleyKD** [IdentityServer/IdentityServer4#4730]
Currently using version 4.0.4

### Issue / Steps to reproduce the problem
If a user logs out of any of our apps or out of IS, we figure that we might as well kill the persisted grants (refresh_tokens) for the current subject + session.

Trying to use `IIdentityServerInteractionService.RevokeTokensForCurrentSessionAsync()` in the `[HttpPost] Logout` of the `AccountController`.
``` csharp
[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> Logout(LogoutViewModel model)
{
    // build a model so the logged out page knows what to display
    var vm = await BuildLoggedOutViewModelAsync(model.LogoutId);

    if (User?.Identity.IsAuthenticated == true)
    {
        // delete local authentication cookie
        await _signInManager.SignOutAsync();

        // raise the logout event
        await _events.RaiseAsync(new UserLogoutSuccessEvent(User.GetSubjectId(), User.GetDisplayName()));
    }

    // check if we need to trigger sign-out at an upstream identity provider
    if (vm.TriggerExternalSignout)
    {
        // build a return URL so the upstream provider will redirect back
        // to us after the user has logged out. this allows us to then
        // complete our single sign-out processing.
        string url = Url.Action("Logout", new { logoutId = vm.LogoutId });

        // this triggers a redirect to the external provider for sign-out
        return SignOut(new AuthenticationProperties { RedirectUri = url }, vm.ExternalAuthenticationScheme);
    }

    await _interaction.RevokeTokensForCurrentSessionAsync(); // ??? this isn't killing all the session tokens in the PersistedGrants table?

    if (vm.PostLogoutRedirectUri != null)
    {
        // If it's null, an exception is thrown
        return Redirect(vm.PostLogoutRedirectUri);
    }

    return View("LoggedOut", vm);
}
```
https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/src/Services/Default/DefaultIdentityServerInteractionService.cs#L185-L194
 ... eventually calls ...
https://github.com/IdentityServer/IdentityServer4/blob/9558fac524057f42ac7a35eabe72f880df2468a7/src/EntityFramework.Storage/src/Stores/PersistedGrantStore.cs#L129-L148

But only a single persisted grant is deleted.  The rest of the session tokens are still there.

I understand I may be doing/understanding this wrong. But I'm not sure why calling that function would NOT do as it says: `RemoveAll`.

**Comment by brockallen** [comment]
Have you traced the SQL to the DB to see if the filter is correct?

**Comment by DaleyKD** [comment]
I haven't watched the actual SQL being generated because the LogDebug shows that it's removing 0 grants.  I'll try to pull the code in the next couple days and step thru.
```
trce: IdentityServer4.Endpoints.TokenRevocationEndpoint[0]
      Calling into token revocation request validator: IdentityServer4.Validation.TokenRevocationRequestValidator
trce: IdentityServer4.Validation.TokenRevocationRequestValidator[0]
      ValidateRequestAsync called
dbug: IdentityServer4.Validation.TokenRevocationRequestValidator[0]
      Token type hint found in request: refresh_token
dbug: IdentityServer4.Validation.TokenRevocationRequestValidator[0]
      ValidateRequestAsync result: IdentityServer4.Validation.TokenRevocationRequestValidationResult
trce: IdentityServer4.Endpoints.TokenRevocationEndpoint[0]
      Calling into token revocation response generator: IdentityServer4.ResponseHandling.TokenRevocationResponseGenerator
trce: IdentityServer4.ResponseHandling.TokenRevocationResponseGenerator[0]
      Hint was for refresh token
dbug: IdentityServer4.EntityFramework.Stores.PersistedGrantStore[0]
      roJWoApfn7gFYD8kB5GP3Y9+IxxemmgbgMpWUYHXynQ= found in database: True
dbug: IdentityServer4.ResponseHandling.TokenRevocationResponseGenerator[0]
      Refresh token revoked
dbug: IdentityServer4.EntityFramework.Stores.PersistedGrantStore[0]
      removing roJWoApfn7gFYD8kB5GP3Y9+IxxemmgbgMpWUYHXynQ= persisted grant from database
dbug: IdentityServer4.EntityFramework.Stores.PersistedGrantStore[0]
      removing 0 persisted grants from database for IdentityServer4.Stores.PersistedGrantFilter
```

**Comment by brockallen** [comment]
Yea, I'm curious what's happening around the filter logic.

**Comment by DaleyKD** [comment]
Goodness, I think I'm a moron.

I put the `await _interaction.RevokeTokensForCurrentSessionAsync();` after I've come back from logging out of Azure Active Directory... at which point, I'm signed out.  Which means, that `var user = await _userSession.GetUserAsync();` should indeed be coming back `null`.

I've been staring at this stuff for too long, my head is spinning.

Now, the question is, do I really want to revoke everything before I've redirected to Azure AD to sign out of them?

**Comment by DaleyKD** [comment]
I know you guys are swamped.  I'll go ahead and close this out since it's not a bug.

If you ever get a wild hair and want to answer the "second question," it'd be appreciated.

Thank you SO much for all the hard work you and leastprivilege do.

**Comment by brockallen** [comment]
> Second question: Is it not common place to want to revoke all the tokens of the session when logging out of IS?

Depends :) 

And it's tricky. For example: what if the RT you issued really is meant to be long-lived?
