### ISSUE TITLE
Minimum Oracle version support for IdentityServer4

### ISSUE THREAD

**Issue by manish13oct** [IdentityServer/IdentityServer4#4734]
Some of the table in IdentityServer4 has column names exceeding 30 characters which is causing issue with my currently working version of Oracle 11g.

Is there any workaround to get it working with Oracle 11g? If not, can you provide any documentation which clearly mentions the minimum supported Oracle version to work with IdentityServer4.

**Comment by brockallen** [comment]
IdentityServer supports EF Core, and not Oracle directly. As long as you have an Oracle provider for EF Core it should work.

As for the column names, IIRC, we allow you to override those: https://github.com/IdentityServer/IdentityServer4/blob/main/src/EntityFramework.Storage/src/Options/ConfigurationStoreOptions.cs#L45

**Comment by manish13oct** [comment]
Thanks for the reply.

Let me know if I am understanding you correctly -

In IdentityServer, there is a table called "Clients" having column "AlwaysIncludeUserClaimsInIdToken". If I want to override this column so that it doesn't exceed 30 character limit, I should use something like below in my application code:

ConfigurationStoreOptions.Client  = new TableConfiguration("CustomClients");

Where "CustomClients" is the new table with column "AlwaysIncludeUserClaimsInIdToken" renamed to "NewColumnName" and keeping everything else same. Is that correct?

**Comment by brockallen** [comment]
Oh it's the column... hmm, yea, our table options won't help with that. Sorry.
