### ISSUE TITLE
Identity server 4 - error The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors

### ISSUE THREAD

**Issue by meirib** [IdentityServer/IdentityServer4#4735]
V4.0.2

We're receiving **spontaneous** peaks of errors, that are only shown in application insights, such as:

`Microsoft.Data.SqlClient.SqlException (0x80131904): The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors.`

For the following query:

`SELECT [p].[Key], [p].[ClientId], [p].[ConsumedTime], [p].[CreationTime], [p].[Data], [p].[Description], [p].[Expiration], [p].[SessionId], [p].[SubjectId], [p].[Type] FROM [PersistedGrants] AS [p] WHERE [p].[Key] = @__key_0`

Connection string contains:
;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

Any suggestions?

**Comment by brockallen** [comment]
No idea, sorry.

**Comment by meirib** [comment]
@brockallen 
FYI

[https://github.com/dotnet/SqlClient/issues/687](https://github.com/dotnet/SqlClient/issues/687)
Any use of SqlDataReader or SqlBulkCopy on your side?

**Comment by brockallen** [comment]
Well, we use the EF abstraction layer -- not SqlClient directly.
