### ISSUE TITLE
JavaScript Quickstart Client does not log.

### ISSUE THREAD

**Issue by robotron2084** [IdentityServer/IdentityServer4#4738]
When attempting to log information within the JavaScript client in the quickstart, the logged information is logged to the `innerHtml` member of the `results` element instead of the `innerText` element. Because of this, no logs display.

### Issue / Steps to reproduce the problem
1. Follow the quickstart tutorial up to the JavaScript client portion.
1. Open the javascript client.
1. Attempt to log in.
1. Observe that no logging information appears.

### Expected Behaviour
When the user logs into the app, it  should show logs of the actions taken like so

![](https://identityserver4.readthedocs.io/en/latest/_images/jsclient_not_logged_in.png)

The reason for this seems to be that `innerHtml` is used instead of `innerText`. I have a [fork ready for a PR here](https://github.com/robotron2084/IdentityServer4/tree/patch-3).

**Comment by brockallen** [comment]
We don't have that client sample anymore.

**Comment by robotron2084** [comment]
I’m not sure what you mean. I just followed your quickstart, posted the above PR based off `master`. Are you saying you’ve removed it from the development branch?

**Comment by robotron2084** [comment]
To be clear, this is the sample I am talking about: https://github.com/robotron2084/IdentityServer4/tree/patch-3/samples/Quickstarts/4_JavaScriptClient/src/JavaScriptClient

**Comment by brockallen** [comment]
Oh I'm sorry -- you did say "quickstart", and in my mind I was thinking "sample". I'll have another look.

**Comment by brockallen** [comment]
Fixed on docs PR. Thanks.
