### ISSUE TITLE
Why I can't install IdentityServer4.Templates using dotnet CLI?

### ISSUE THREAD

**Issue by nhonoskywalker** [IdentityServer/IdentityServer4#4741]
### Question
When I run the dotnet new -i IdentityServer4.Templates command in command line it does not install the template. No error nor messages. It will just show the installed templates. Why?

This works on my team's machine but why not in my machine? Are there any specific requirements?
I've run the cmd as administrator and turned off my anti-virus.

### Minimal working example
dotnet new -i IdentityServer4.Templates
dotnet new -i IdentityServer4.Templates --nuget-source https://api.nuget.org/v3/index.json

### Relevant parts of the log file
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.400 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by brockallen** [comment]
Not sure -- it just worked for me.

**Comment by nhonoskywalker** [comment]
I wonder if the Nuget config file in my Windows user is the problem. 
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
	<clear/>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="IdentityServer Local" value="./nuget" />
  </packageSources>
</configuration>`

I found a workaround by downloading the template nugetpackage file and install it using `dotnet new -i <path>identityserver4.templates.4.0.1.nupkg`
