### ISSUE TITLE
Adding custom CorsPolicyService doesn't work with IdentityServer4.EntityFramework

### ISSUE THREAD

**Issue by Andree643** [IdentityServer/IdentityServer4#4743]
### Issue / Steps to reproduce the problem
I try to add my custom `CorsPolicyService` called `MyCorsPolicyService` in `Startup.ConfigureServices()`. Basicaly all attempt to add work fine until I try to get the `ICorsPolicyService` in `Startup.Configure()` to check the registration. Instead I get `IdentityServer4.Stores.CachingCorsPolicyService<IdentityServer4.EntityFramework.Services.CorsPolicyService>`.
I've tried to use `builder.AddCorsPolicyService<MyCorsPolicyService>()` or `builder.AddCorsPolicyCache<MyCorsPolicyService>()` call right after `services.AddIdentityServer()` or register it to container manually under the `ICorsPolicyService` interface. None of that worked. The only thing that helped was replacing extension methods `AddConfigurationStore<TContext>()` and `AddConfigurationStoreCache()` and remove calls to add CorsPolicyService.

```
public static IIdentityServerBuilder AddConfigurationStoreCache(
	this IIdentityServerBuilder builder)
{
	builder.AddInMemoryCaching();

	// add the caching decorators
	builder.AddClientStoreCache<ClientStore>();
	builder.AddResourceStoreCache<ResourceStore>();
	//builder.AddCorsPolicyCache<CorsPolicyService>(); // <== this overwrites the service

	return builder;
}

public static IIdentityServerBuilder AddConfigurationStore<TContext>(
	this IIdentityServerBuilder builder,
	Action<ConfigurationStoreOptions> storeOptionsAction = null)
	where TContext : DbContext, IConfigurationDbContext
{
	builder.Services.AddConfigurationDbContext<TContext>(storeOptionsAction);

	builder.AddClientStore<ClientStore>();
	builder.AddResourceStore<ResourceStore>();
	//builder.AddCorsPolicyService<CorsPolicyService>(); // <== same here

	return builder;
}
```
My registration:

```
builder.AddCorsPolicyCache<MyCorsPolicyService>();
```
Where CorsPolicyService implements ICorsPolicyService.

**Comment by brockallen** [comment]
Yes, that's why we offer those finer-grained APIs to register like `AddCorsPolicyCache<T>` if you don't want our wrapped up implementation via `AddConfigurationStoreCache`. 

So in short, it sounds like you have the config APIs you need, it's just that `AddConfigurationStoreCache` is not the right API for you when you want your own `ICorsPolicyService`?

**Comment by Andree643** [comment]
It just seems strange to me that when I want to register my own CORS policy service it's never used since these services are resolved prior to my custom one.

**Comment by brockallen** [comment]
The call to `AddCorsPolicyCache` adds a decorator on whatever service was registered in DI. I guess the real question is if it gets your custom implementation for the inner instance?
