### ISSUE TITLE
Provide a default grant description

### ISSUE THREAD

**Issue by natelaff** [IdentityServer/IdentityServer4#4746]
In #2967 is was suggested for providing a default description. It doesn't look like this was implemented. I think there is a lot of value in doing this. First of all, end users (well, anyone really) is lazy and don't want to type things. Second, providing a default descriptive name is obviously useful.

Is there a way to do this without a lot of heavy lifting currently? And for the future, providing an easier mechanism for this that would also inject the context to get things like client description as well as the user context would be super helpful.

**Comment by brockallen** [comment]
I don't follow what a default description would be. A description is not required.

**Comment by natelaff** [comment]
Imagine a scenario where we provide a UI to revoke a login.

I have a client specifically for Zapier connections to my API. So when creating that connection and consenting, I could provide a default description like "Zapier (brockallen)" that would already be filled out which results in a clean user experience on both ends.

I hope that clarifies a little bit.

**Comment by brockallen** [comment]
Ok, sure... then your UI for the consent page can do that. That's why the quickstart UI is provided -- for you to make any of those kinds of modifications/customizations. Our quickstart UI is not sacrosanct.

**Comment by natelaff** [comment]
Sure I know I can rip that apart and that's all fine. Was looking for feedback I suppose on if you thought this was a good idea or worth exploring. Other instances include non visual instances where grabbing the user agent would be nice, etc... I think a service to inject that can supply this would be useful but maybe I'm over complicating it :)

**Comment by brockallen** [comment]
Yea, we're a framework and provide building blocks to do with as you see fit. I don't see many people actually using description, to be honest, but it's something that might be useful for some scenarios.

**Comment by natelaff** [comment]
Maybe I'll try a PR on it. I think you're underestimating its value though ;) Maybe I'm wrong.
