### ISSUE TITLE
Should AuthorizeInteractionResponseGenerator trigger on a "local" login without a client?

### ISSUE THREAD

**Issue by jenspettersson** [IdentityServer/IdentityServer4#4747]
### Question
When I login using a client (a simple MVC web) my simple custom `AuthorizeInteractionResponseGenerator` that triggers just fine and I can do the things I want.

However, if I login in directly in Identity Server (via the `/Account/Login`) URL in the Quick Start, i.e. not being redirected from a client, the `AuthorizeInteractionResponseGenerator` does not trigger.

### Minimal working example

```csharp
.AddIdentityServer(...)
 ...
    .AddAuthorizeInteractionResponseGenerator<TestResponseGenerator>();
```
```csharp
public class TestResponseGenerator : AuthorizeInteractionResponseGenerator
{
    public TestResponseGenerator(ISystemClock clock, ILogger<AuthorizeInteractionResponseGenerator> logger, IConsentService consent, IProfileService profile) : base(clock, logger, consent, profile)
    {
    }

    protected override Task<InteractionResponse> ProcessLoginAsync(ValidatedAuthorizeRequest request)
    {
        // Does nothing for now, just want to see if it triggers when debugging...
        Console.WriteLine("Triggered!");
        return base.ProcessLoginAsync(request);
    }
}
```

Is this by design?

We have a scenario where we might want to let user register/signup (and later login) without coming from the context of a client, and we want to do some processing of the login regardless.

**Comment by brockallen** [comment]
> However, if I login in directly in Identity Server (via the /Account/Login) URL in the Quick Start, i.e. not being redirected from a client, the AuthorizeInteractionResponseGenerator does not trigger.

Yes, because you're not making an authorization request.

**Comment by jenspettersson** [comment]
> Yes, because you're not making an authorization request.

Ah I see, so this is authorizing a client making a request (on behalf of a "user"/identity)? I mixed it up with a user just authenticating itself.

If I want to take an action every time a user logs in (for example, check if the email is verified and things like that), is it outside the scope of Identity Server and perhaps something done in the asp net core identity side of things?
