### ISSUE TITLE
IdentityServer4.Extensions.NameValueCollectionExtensions.ToScrubbedDictionary is case-sensitive, which should not be

### ISSUE THREAD

**Issue by cchongchong** [IdentityServer/IdentityServer4#4749]
Here is the link to source code:
https://github.com/IdentityServer/IdentityServer4/blob/94a311564c72faf666172a33e8a41cc2ab8bf83c/src/IdentityServer4/src/Extensions/NameValueCollectionExtensions.cs#L100

Ideally, we'd better ignore cases when filtering out URL parameters. The worse case is: IdentityServer4.Logging.Models.TokenRequestValidationLog is calling this method to generate raw content of token endpoint request, **that would expose sensitive data like secret or password, if the consumer side is passing upper-case parameter name.**

**Comment by leastprivilege** [comment]
This has been changed already...

https://github.com/IdentityServer/IdentityServer4/blob/b406b60e66d97bced4e9870691f013c48dfa4df0/src/IdentityServer4/src/Extensions/NameValueCollectionExtensions.cs#L120
