### ISSUE TITLE
MissingMethodException: get_Scopes()

### ISSUE THREAD

**Issue by RwnRchrds** [IdentityServer/IdentityServer4#4752]
When calling `app.UseIdentityServer();` during startup of an ASP.NET Core application, the following exception is thrown:

**System.MissingMethodException: 'Method not found: 'System.Collections.Generic.ICollection`1<IdentityServer4.Models.Scope> IdentityServer4.Models.ApiResource.get_Scopes()'.'**

**Comment by brockallen** [comment]
Did you register any scopes in your Startup?

**Comment by Rafal38** [comment]
same issue with version v4.0.4

**Comment by brockallen** [comment]
The current Microsoft templates are not compatible with the v4.x version. You will have to wait for Microsoft to fix them.
