### ISSUE TITLE
Re-validating a user (authenticated using IResourceOwnerPasswordValidator) on token refresh

### ISSUE THREAD

**Issue by TomerAdmon** [IdentityServer/IdentityServer4#4753]
### Question
Is there an option to re-validate a user that was initially validated using IResourceOwnerPasswordValidator when he uses a refresh-token? 
The use-case is for when using a 3rd party service in which the user might get updated or deleted since the initial access token grant. The 3rd party application has its own users datastore and authentication API.

Flow:
The user uses username&password to log in --> gets an access token --> some time pass --> user uses refresh token (at this point i would like to revalidate his data and update the claims accordingly)

I've tried to use the 'ICustomTokenRequestValidator' implementation for that, to have both validators share the same logic, but since the user and password are needed it seems like it's a dead-end.

Does the 'UpdateAccessTokenClaimsOnRefresh' should help in such a scenario? tried that but I'm probably misunderstanding it's purpose.

Thanks!

**Comment by brockallen** [comment]
IProfileService.IsActiveAsync is what you're looking for.

**Comment by TomerAdmon** [comment]
@brockallen - So, something like looking for "RefreshTokenValidation" context.Caller and revalidating the user with the 3rd party and updating the Claims?
Can I get the user password from somewhere to do that?

**Comment by leastprivilege** [comment]
> Can I get the user password from somewhere to do that?

no
