### ISSUE TITLE
How to get ScopesRequested

### ISSUE THREAD

**Issue by Joshlo** [IdentityServer/IdentityServer4#4757]
According to the documentation http://docs.identityserver.io/en/latest/reference/interactionservice.html#authorizationrequest AuthorizationRequest should have ScopesRequested, but after upgrading from 3.x to 4.0.4 it is gone.

Is the docs wrong and if yes, can you guide me in a direction to where I get them.

Thanks in advance
Kenneth

**Comment by brockallen** [comment]
Requested Scopes: https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Validation/Models/ValidatedAuthorizeRequest.cs#L55

Validated Resources: https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Validation/Models/ValidatedRequest.cs#L93

**Comment by brockallen** [comment]
Added docs label as reminder to go check/fix docs.

**Comment by brockallen** [comment]
Updated in the docs PR. Thanks.
