### ISSUE TITLE
MongoDB - Fail On IProfileService.GetProfileDataAsync

### ISSUE THREAD

**Issue by saridakis** [IdentityServer/IdentityServer4#476]
I am trying to create a MongoDb Solution using this approach http://blog.stoverud.no/posts/identity-server-with-mongodb/ with .net framework. Everythink is working fine until the moment the code gets in GetProfileDataAsync function:

public Task GetProfileDataAsync(ProfileDataRequestContext context) {
            var userId = context.Subject.GetSubjectId();
            var user = _repository.GetUserById(userId);
            if (context.AllClaimsRequested == false) {
                var claims = new List<Claim>
                   {    
                        new Claim(JwtClaimTypes.Name, "Alice Smith"),
                        new Claim(JwtClaimTypes.GivenName, "Alice"),
                        new Claim(JwtClaimTypes.FamilyName, "Smith"),
                        new Claim(JwtClaimTypes.Email, user.Email),                        
                        new Claim(JwtClaimTypes.EmailVerified, "true", ClaimValueTypes.Boolean),
                        new Claim(JwtClaimTypes.Role, "Admin"),
                        new Claim(JwtClaimTypes.Role, "Geek"),
                        new Claim(JwtClaimTypes.WebSite, "http://alice.com"),
                    };
                context.IssuedClaims = claims;
            }
            return Task.FromResult(0);
        }

The function assignes the claims into IssuedClaims property and seems to returns with no error but at the client side the result of this call 'http://localhost:65191/connect/token' with : 
client_id:myapi
client_secret:secret
grant_type:password
scope:api1
username:alice
password:alice

returns 500 Inernal Server Error with no any other error info or trace info. I have use try catch but no error rises at framework.

Do you have any idea why is this happening?

**Comment by saridakis** [comment]
The missing part was the app.UseDeveloperExceptionPage() call that gave me the following exception 'No signing credential is configured. Can't create JWT token', but I can not find any way to assign my certificate:

var cert = new X509Certificate2(Path.Combine(_environment.ApplicationBasePath, "idsrv4test.pfx"), "idsrv3test");

            var builder = services.AddIdentityServer(options =>
            {
                options.SigningCertificate = cert;
});

How can i do that?

**Comment by leastprivilege** [comment]
http://docs.identityserver.io/en/release/topics/crypto.html
