### ISSUE TITLE
Is it a security risk if clients are aware of refresh token lifetime?

### ISSUE THREAD

**Issue by ahofman** [IdentityServer/IdentityServer4#4761]
### Question

Hi,
I'm using IdentityServer4 to secure an HTTP API that is consumed by a SPA web application, using the authorization code grant flow with a refresh token stored in the browsers local storage. 

The issue is that when the refresh token expires, the user is suddenly kicked out to a login screen with no warning, interrupting their workflow.

We would like to implement an experience where a warning popup appears to the user to advise them that their session is about to expire in x minutes, and to provide them a link to log in to do so when they are ready.

There doesn't seem to be any built in way for clients to know the absolute expiry time of a refresh token. I am curious if this was a deliberate design decision? **Is the refresh token expiry time hidden from clients deliberately, for security reasons?**

If not, I am considering implementing a solution outlined here: https://stackoverflow.com/questions/59313874/identityserver4-refresh-token-how-to-determine-expiration-time

Thankyou :)

**Comment by leastprivilege** [comment]
I don't see a security risk, but since the OAuth spec did not include this - we didn't either.

**Comment by ahofman** [comment]
That's fair enough, thankyou!
