### ISSUE TITLE
Can I use the same external provider but with different settings for different clients?

### ISSUE THREAD

**Issue by B45man** [IdentityServer/IdentityServer4#4765]
### Question
I have multiple Clients with ApiScopes in an 1-1 relationship in my IDS4 project. So Client1 has ApiScope1, Client2 has ApiScope2, etc. 

These clients each can have different ways to log in. For example, Client1 can use Google and Facebook, and Client 2 can use Google and Active Directory.

My question: if Client1 and Client2 both use Google as an external provider, but both with their own ClientId and ClientSecret, is it possible to set up Google for both of these clients seperately? In the documentation I see the following method being called: 

```
services.AddAuthentication()
    .AddGoogle("Google", options => ......)
```
Ideally I would like to call this method for each client I have, with different settings (ClientId and ClientSecret) and then use some kind of filter (like **Client.IdentityProviderRestrictions**) to select which Client can use which external providers.

**Comment by brockallen** [comment]
Did you try calling `AddGoogle` more than once?

**Comment by B45man** [comment]
Nope, due to tunnel vision, and not having two google accounts to try it with, I assumed that wouldn’t work. Judging by your comment it should work. I’ll try calling it multiple times with names like “google-client1”, “google-client2” etc, then adding those names to IdentityProviderRestrictions. Thanks!

**Comment by brockallen** [comment]
Yep, you should be able to add several in the same way you can add several OIDC handlers.
