### ISSUE TITLE
How to i retrieve token from identity server and send to api with user roles/claims etc?

### ISSUE THREAD

**Issue by smooney123** [IdentityServer/IdentityServer4#4768]
### Question
I want to use identity server but i want to know how to store the token sent back to the client by identity server and send that to the api with the user details like roles/claims etc?

### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by smallprogram** [comment]
When you pass the IDP authentication and return to the Client, you can obtain the access_token in the following way:
```c#
var accessToken = await HttpContext.GetTokenAsync("access_token");
```
Later you can save this token to the place you want to save.

When you want to include the claim in the access_token and return it from the idp to the client. You need to set api resource or api scope in idp:
```c#
public static IEnumerable<ApiResource> GetApis()
        {
            return new List<ApiResource>
            {
                // Aud
                new ApiResource(name:"ApiOne",displayName:"ApiOneResource",userClaims:new string[]{ "role.apione" })
                {
                    Scopes ={ "ApiOne.read" }
                },
                new ApiResource(name:"ApiTwo")
                {
                  Scopes = { "ApiTwo.read" }
                },
            };
        }
```
When your client contains the scope of ApiOne.read, idp will return accsss_token with the claim of role.apione.
Later, when you use this access_token to access the ApiOne api, you will find the role.apione claim in the httpcontext.User.Claims of the api, and then you can do what you want. Such as authorization, etc.

**Comment by smooney123** [comment]
OK thanks. 

When i try this 

` var accessToken = await HttpContext.GetTokenAsync("access_token");` i get null returned. 

How would that work then if a user is in multiple roles? so for example if user A has one role and user B has a different role then would only that users role be sent across?

**Comment by smooney123** [comment]
OK thanks. 

When i try this 

` var accessToken = await HttpContext.GetTokenAsync("access_token");` i get null returned. This is how you get the token from the client?

I should say i am using identity server and identity. I am not using Jwt but identity servers version of it. 

How would that work then if a user is in multiple roles? so for example if user A has one role and user B has a different role then would only that users role be sent across?

Here is the code i am using as a sample atm to try and get the token and hit the api.

`  string url = "https://localhost:44314/weatherforecast";

                var token = await HttpContext.GetTokenAsync("access_token");

                HttpClientHandler httpClientHandler = new HttpClientHandler();
                httpClientHandler.UseDefaultCredentials = true;
                using (HttpClient c = new HttpClient(httpClientHandler))
                {
                    c.SetBearerToken(token);

                    using (HttpResponseMessage response = await c.GetAsync(url))
                    using (HttpContent content = response.Content)
                    {
                        // ... Read the string.
                        string result = await content.ReadAsStringAsync();

                        // ... Display the result.
                        if (result != null &&
                            result.Length >= 50)
                        {
                            Console.WriteLine(result.Substring(0, 50) + "...");
                        }
                    }
                }`



Here is my startup.cs for mvc client

     `public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            services.AddAuthentication(options =>
            {
                options.DefaultScheme = "Cookies";
                options.DefaultChallengeScheme = "oidc";
            })
            .AddCookie("Cookies")
            .AddOpenIdConnect("oidc", options =>
            {
                options.SignInScheme = "Cookies";
                options.Authority = "https://localhost:44302/";
                options.RequireHttpsMetadata = false;
                options.ClientId = "mvc";
                options.GetClaimsFromUserInfoEndpoint = true;
                options.ClientSecret = "secret".ToSha256();
                options.SaveTokens = true;
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateAudience = false,
                    NameClaimType = "name",
                    RoleClaimType = "role"
                };
            });

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {

            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }
            app.UseDeveloperExceptionPage();

            app.UseHttpsRedirection();

            app.UseStaticFiles();

            app.UseRouting();


            app.UseAuthentication();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }`

Here is my startup.cs for identity server

    `public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(option => option.EnableEndpointRouting = false);

            var connectionString = Configuration.GetSection("ConnectionStrings:Database").Value;
            var migrationAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;

            services.AddDbContext<ApplicationDbContext>(builder =>
             builder.UseSqlServer(connectionString, sqlOptions => sqlOptions.MigrationsAssembly(migrationAssembly)));
            services.AddIdentity<IdentityUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseSqlServer(connectionString, sql => sql.MigrationsAssembly(migrationAssembly));
                })
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseSqlServer(connectionString, sql => sql.MigrationsAssembly(migrationAssembly));
                })
                .AddAspNetIdentity<IdentityUser>()
             .AddProfileService<IdentityProfileService>();

            services.AddCors();
            services.AddLogging();
            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            InitialISDatabase(app);

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();
            app.UseIdentityServer();
            app.UseAuthorization();
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy(new CookiePolicyOptions { MinimumSameSitePolicy = SameSiteMode.Lax });
            app.UseCors();
            app.UseMvcWithDefaultRoute();
        }

        private void InitialISDatabase(IApplicationBuilder app)
        {
            using (var serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
            {
                serviceScope.ServiceProvider.GetRequiredService<PersistedGrantDbContext>().Database.Migrate();
                serviceScope.ServiceProvider.GetRequiredService<ConfigurationDbContext>().Database.Migrate();
                serviceScope.ServiceProvider.GetRequiredService<ApplicationDbContext>().Database.Migrate();

                var context = serviceScope.ServiceProvider.GetRequiredService<ConfigurationDbContext>();
                var u = serviceScope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

                if (!context.Clients.Any())
                {
                    foreach (var client in Config.GetClients())
                    {
                        context.Clients.Add(client.ToEntity());
                    }

                    context.SaveChanges();
                }


                if (!context.IdentityResources.Any())
                {
                    foreach (var resource in Config.GetIdentityResources())
                    {
                        context.IdentityResources.Add(resource.ToEntity());
                    }

                    context.SaveChanges();
                }

                if (!context.ApiScopes.Any())
                {
                    foreach (var scope in Config.GetApiScopes())
                    {
                        context.ApiScopes.Add(scope.ToEntity());
                    }
                    context.SaveChanges();
                }

                if (!context.ApiResources.Any())
                {
                    foreach (var api in Config.GetAllApiResources())
                    {
                        context.ApiResources.Add(api.ToEntity());
                    }

                    context.SaveChanges();
                }


                if (!u.Users.Any())
                {

                    var identityUser = new IdentityUser();
                    identityUser.UserName = "admin";
                    PasswordHasher<IdentityUser> hasher = new PasswordHasher<IdentityUser>();
                    identityUser.PasswordHash = hasher.HashPassword(identityUser, "123qwe");
                    identityUser.Email = "admin@crm.com";
                    identityUser.NormalizedEmail = "admin@crm.com".ToUpper();
                    identityUser.NormalizedUserName = "admin".ToUpper();
                    identityUser.SecurityStamp = Guid.NewGuid().ToString();

                    u.Users.Add(identityUser);

                    u.SaveChanges();


                }

            }
        }
    }`

Here is my config

    `  public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                 new IdentityResources.Email(),
                new IdentityResource
                {
                    Name = "role",
                    UserClaims = new List<string> {"role"}
                }
            };
        }

        public static IEnumerable<ApiResource> GetAllApiResources()
        {
            return new List<ApiResource>
            {
               new ApiResource
                {
                    Name = "crmApi",
                    DisplayName = "API #1",
                    Description = "Allow the application to access API #1 on your behalf",
                    Scopes = new List<string> {"crmApi"},
                    ApiSecrets = new List<Secret> {new Secret("secret".Sha256())}, // change me!
                    UserClaims = new List<string> {"role"}

                }
            };
        }

        public static IEnumerable<ApiScope> GetApiScopes()
        {
            return new[]
            {
                new ApiScope("crmApi", "Access to API #1"),
            };
        }

        public static IEnumerable<Client> GetClients()
        {
            return new List<Client>
            {
                new Client
                {
                    ClientId = "client",
                    AllowedGrantTypes = GrantTypes.ClientCredentials,
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                    AllowedScopes = { "crmApi" }
                },

                  new Client
                {
                      ClientId = "mvc",
                      ClientName = "MVC Client",
                      AllowedGrantTypes = GrantTypes.ImplicitAndClientCredentials,
                      RedirectUris = {"https://localhost:44315/signin-oidc"},
                      PostLogoutRedirectUris = {"https://localhost:44315/signout-callback-oidc"},
                      RequireConsent = false,
                        AllowOfflineAccess = true,
            AlwaysSendClientClaims = false,
            
            AlwaysIncludeUserClaimsInIdToken = true,
            ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },
                      AllowedScopes =new List<string>
                      {
                          IdentityServerConstants.StandardScopes.OpenId,
                          IdentityServerConstants.StandardScopes.Profile,
                          IdentityServerConstants.StandardScopes.Email,
                          "role",
                          "crmApi"
                }
            },
        };


        }`

and here is my api startup.cs

    `  public class Startup
    {
        public Startup(IConfiguration configuration)
        {

            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme)
                .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = "https://localhost:44302/";
                    options.ApiName = "crmApi";
                    options.RequireHttpsMetadata = false;
                   
                });

            services.AddAuthorization();
            services.AddControllers();

          
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseAuthentication();

            app.UseAuthorization();
            app.UseHttpsRedirection();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }`

**Comment by smallprogram** [comment]
I read your code, I want to say a few points:
1. Implicit Flow is actually suitable for Javascript clients. ClientCredentials is suitable for machine-to-machine authentication. For MVC clients, it is better to use Authorization code flow or Hybrid Flow to be more secure.
2. You want to use the Token with Claims to request a protected API. This Token must be AccessToken, not IdentityToken.
3. If you want to have Claims in AccessToken, you need to start with ApiResouce and ApiScope in IdentityServer, not IdentityResouce

After that, I will show you a simple example that can achieve your needs. This example is an MVC client, a protected API, and an IdentityServer4, implemented using Authentication Code Flow:

### 1. Identity Server 4 runs at https://localhost:7001 
**startup.cs**
```c#
public class Startup
    {
        private readonly IConfiguration _configuration;

        public Startup(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddDbContext<AppDbContext>(config =>
            {
                config.UseInMemoryDatabase("MemoryDb");
            });


            // asp.net identity config
            services.AddIdentity<IdentityUser, IdentityRole>(config =>
            {
                config.Password.RequireDigit = false;
                config.Password.RequiredLength = 4;
                config.Password.RequireNonAlphanumeric = false;
                config.Password.RequireUppercase = false;
                config.SignIn.RequireConfirmedEmail = false;
            })
                .AddEntityFrameworkStores<AppDbContext>()
                .AddDefaultTokenProviders();

            services.ConfigureApplicationCookie(config =>
            {
                config.Cookie.Name = "IdentityServer.Cookie";
                config.LoginPath = "/Auth/Login";
            });

            services.AddIdentityServer()
                .AddAspNetIdentity<IdentityUser>()
                .AddInMemoryApiResources(Configuration.GetApis())
                .AddInMemoryApiScopes(Configuration.GetApiScopes())
                .AddInMemoryClients(Configuration.GetClients())
                .AddInMemoryIdentityResources(Configuration.GetIdentityResources())
                .AddDeveloperSigningCredential(); //RSA developer Credential

            services.AddControllersWithViews();
        }


        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseIdentityServer();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
            });
        }
    }
```

**Configuration.cs**
```c#
public static class Configuration
    {
        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
            };
        }
        public static IEnumerable<ApiScope> GetApiScopes()
        {
            // Scope
            return new List<ApiScope>
            {
                new ApiScope(name: "ApiOne.read",   displayName: "Read your data.",userClaims:new string[]{"scope.claim" }),
                new ApiScope(name: "ApiOne.write",   displayName: "write your data."),
                new ApiScope(name: "ApiOne.all",   displayName: "management apione"),
                new ApiScope(name: "ApiTwo.read",   displayName: "Read your data."),
            };
        }
        public static IEnumerable<ApiResource> GetApis()
        {
            // Aud
            return new List<ApiResource>
            {
                // Aud
                new ApiResource(name:"ApiOne",displayName:"ApiOneResource",userClaims:new string[]{ "role.apione" })
                {
                    Scopes ={ "ApiOne.read" }
                },
                new ApiResource(name:"ApiTwo")
                {
                  Scopes = { "ApiTwo.read" }
                },
            };
        }
        public static IEnumerable<Client> GetClients()
        {
                // Authorization code Client
                new Client
                {
                    ClientId = "client_id_mvc",
                    ClientSecrets = {new Secret("client_secret_mvc".ToSha256())},

                    AllowedGrantTypes = GrantTypes.Code,

                    RedirectUris ={"https://localhost:7004/signin-oidc" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "ApiOne.read",
                        "ApiTwo.read",
                        IdentityServerConstants.StandardScopes.OfflineAccess,
                    },
                    RequireConsent = false, 
                    AllowOfflineAccess = true, 
                }
            };
        }
    }
```
**Initialize some claims for the user in Program.cs**
```c#
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build();

            using (var scope = host.Services.CreateScope())
            {
                var userManager = scope.ServiceProvider.GetRequiredService<UserManager<IdentityUser>>();

                var user = new IdentityUser("zhusir");
                userManager.CreateAsync(user, "zhusir").GetAwaiter();
                userManager.AddClaimAsync(user, new Claim("role.apione", "apioneadmin")).GetAwaiter();
                userManager.AddClaimAsync(user, new Claim("scope.claim", "apionecliam")).GetAwaiter();
            }

            host.Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
```

### 2. MvcClient runs at https://localhost:7004
**startup.cs**
```c#
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication(config =>
            {
                config.DefaultScheme = "MvcClientCookie";
                config.DefaultChallengeScheme = "oidc";
                
            })
                .AddCookie("MvcClientCookie")
                .AddOpenIdConnect("oidc", config =>
                {
                    config.Authority = "https://localhost:7001";
                    config.ClientId = "client_id_mvc";
                    config.ClientSecret = "client_secret_mvc";
                    config.SaveTokens = true;
                    config.ResponseType = "code"; 
                    config.GetClaimsFromUserInfoEndpoint = true;
                    config.Scope.Clear();
                    config.Scope.Add("openid");
                    config.Scope.Add("profile");
                    config.Scope.Add("offline_access"); 
                    config.Scope.Add("ApiOne.read");
                    config.Scope.Add("ApiTwo.read");
                    });

            services.AddHttpClient();

            services.AddControllersWithViews();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
            });
        }
    }
```
**Method in controller**
```c#
        [Authorize]
        public async Task<IActionResult> Secret()
        {
            var accessToken = await HttpContext.GetTokenAsync("access_token");
            var idToken = await HttpContext.GetTokenAsync("id_token");
            var refreshToken = await HttpContext.GetTokenAsync("refresh_token");

            var claims = User.Claims.ToList();

            var _accessToken = new JwtSecurityTokenHandler().ReadJwtToken(accessToken);
            var _idToken = new JwtSecurityTokenHandler().ReadJwtToken(idToken);

            var result = await GetSecret(accessToken);
            return View();
        }
       
        /// <summary>
        /// use accesstoken request API
        /// </summary>
        /// <param name="accessToken"></param>
        /// <returns>secret content</returns>
        public async Task<string> GetSecret(string accessToken)
        {
            var apiClient = _httpClientFactory.CreateClient();
            apiClient.SetBearerToken(accessToken);
            var response = await apiClient.GetAsync("https://localhost:7002/api/secret");
            var content = await response.Content.ReadAsStringAsync();
            return content;
        }
```
When the MVC Client requests the Secret, it will jump to the IdentityServer for authentication. After the authentication is passed, it will return a response with accessToken identityToken refreshToken. You can set breakpoints to look at the contents of Claims in the accessToken and the contents of User.Claims.

Of course, this method will also call the method GetSecret to access the API.

### 3. ApiResource runs at https://localhost:7002
**startup.cs**
```c#
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication("Bearer")
                .AddJwtBearer("Bearer", config =>
                {
                    config.Authority = "https://localhost:7001";
                    config.Audience = "ApiOne";
                });
            services.AddControllers();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
```
**Method in controller**
```c#
        [Route("api/secret")]
        [Authorize]
        public string Index()
        {
            var claims = User.Claims.ToList();
            return "secret message from apione";
        }
```
When MVC Client uses AccessToken to access this method. You can set a breakpoint and look at the content in Claims.You will find that the Claims in the API have the Claims in AccesToken.
Finally, it should be noted that it is very insecure to put some sensitive claims in the token. Once the Token is leaked, it will cause disaster for the entire system. So don't put some sensitive claims in the token.

If this answer helped you, that would be great
