### ISSUE TITLE
Moving Models to a separated project help loosely-coupled. 

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4#477]
When we want to an implement  on `IClientStore` ,`IScopeStore`  we need to reference to `IdentityServer4` project with have many Hosting environment and MVC related packages. So having  separated project that contains interfaces and domain models help to have a more loosely-coupled  solution.

**Comment by brockallen** [comment]
I don't see this happening, as we want the number of IdentityServer assemblies to be as few as possible.

**Comment by mikeandersun** [comment]
Maybe this is my sensitivity that wouldn't like to add an assembly that brings MVC requirement (assemblies ) to a project (Store or CQRS  implementation) that doesn't needs MVC assemblies.

**Comment by xyting** [comment]
Hmm, I'm happy to see this changing

**Comment by brockallen** [comment]
@leastprivilege to discuss

**Comment by leastprivilege** [comment]
this adds complexity - and adds little value IMHO
