### ISSUE TITLE
Set expiration date to "idsrv.session" cookie 

### ISSUE THREAD

**Issue by lexon0011** [IdentityServer/IdentityServer4#4773]
I get problems with the silent-refresh mechanism of my angular app, because the cookie expiration will not set correctly by the identity server.

After a successful login, the following cookies will be set for the domain of the identity server:
![2020-08-20 12_53_39-ORF Zuul - Microsoft Visual Studio](https://user-images.githubusercontent.com/16290662/90761846-4ff37e80-e2e4-11ea-9919-21ffdb363692.png)

As you can see on the picture, the "idsrv.session" cookie has the expiration "session". In my old IdentityServer3 this cookie has a correct expiration date and all works fine.

Could anyone help me, to solve this problem. I need a way to set a expiration-date for the "idsrv.session" cookie.

#### Here are the current configuration/statements, which I added to achieve my goal:

```csharp
// Startup.cs - ConfigureServices()
services
   .AddIdentityServer(options =>
   {
      options.EmitStaticAudienceClaim = true;
      options.AccessTokenJwtType = "JWT";
      options.Authentication.CookieLifetime = TimeSpan.FromDays(30);
   })
services
   .AddAuthentication("Cookies")
   .AddCookie("Cookies", options =>
   {
      options.ExpireTimeSpan = TimeSpan.FromDays(30);
   })
```

```csharp
// AccountController.cs - Login()
await HttpContext.SignInAsync(isuser, new AuthenticationProperties
   {
       IsPersistent = true,
       ExpiresUtc = DateTimeOffset.UtcNow.Add(TimeSpan.FromDays(30))
    });
```

But this settings has no effekt on the "idsrv.session" cookie. 

I use .net core 3.1 and IdentityServer4 4.0.4. 

Thanks!!

**Comment by brockallen** [comment]
We had problems in the past with setting an expiration, so in IS4 we changed this to a session cookie. This cookie is emitted derived on the incoming main authentication cookie thus always keeping it in sync with the current user.

**Comment by lexon0011** [comment]
Thank you very much for fast reply! The problem is, that after approximately 30 minutes the cookies (idsrv.session, .AspNetCore.Identity.Application) disappears from the Chrome Developer Console. After loosing the cookie, the user must be logged on again, because silent-refresh doesn't work (error: "login_required"). In my setup a user should be logged out automatically after 30 days. The tokens will be refreshed every hour by a silent-refresh mechanism (IdentityTokenLifetime and AccessTokenLifetime are set to 3600).

All this thinks works fine on the previous version (IdentityServer3), but I am not able the get it work with the new version.

In the logging I only get the following message:
```
[21:18:38 INF] Showing login: User is not authenticated
[21:18:38 INF] Changing response to LoginRequired: prompt=none was requested
```

Have you any idea how I can solve my problem?

**Comment by brockallen** [comment]
Not sure -- perhaps for some reason your cookie settings are wrong? Or something is causing the cookie to be removed.

**Comment by lexon0011** [comment]
In my case the following statement helps me, that a user will not logout after 30 minutes. The expiration "idsrv.session" cookie is although still set to session, but it will not removed after 30 minutes.

```csharp
services.Configure<SecurityStampValidatorOptions>(o => o.ValidationInterval = TimeSpan.FromDays(30));
```
