### ISSUE TITLE
how to make Reference Token like Access Token to contain User Claims ? 

### ISSUE THREAD

**Issue by masoud-shayan** [IdentityServer/IdentityServer4#4774]
I customized access token to contains user claims and roles in it by IProfileService , but at some point I found that we need a token to can invalidate/revoke to Sign Out the user 
Many parts of the Client API that I have, Use Claims and Roles in Tokens 
Now I want to use Refrence Token how can I do to have the same roles and claims in Refrence Token instead of Access Token and how I can read these data from the Client API side ?

**Comment by brockallen** [comment]
> Now I want to use Refrence Token how can I do to have the same roles and claims in Refrence Token instead of Access Token and how I can read these data from the Client API side

Introspection: https://identityserver4.readthedocs.io/en/latest/topics/reference_tokens.html
