### ISSUE TITLE
Chrome not executing 302 redirect after OpenId login

### ISSUE THREAD

**Issue by dotnet555** [IdentityServer/IdentityServer4#4786]
Hi, I'm facing a problem that's probably not caused by Identity Server 4, but maybe someone can point me out something obvious that I'm missing... or at least point me out to who I should ask.

The problem regards Google Chrome (v. 84) being stuck in a "Processing request" / "Pending" state after the first login on a IS4 login interface (from Quickstart, with minimal variations, so I'm using "AddOpenIdConnect").
It's not, apparently, a redirect loop, and it never goes in timeout or throws any error: it just remains pending in the network tab of the browser's F12, with the "Processing request..." notification text in the bottom-left of the browser's window.
The response from the form POST is actually received by the browser, with status (302), with the target address and with all the headers, including set-cookies: I can verify this in the browser's F12, and also because if I hit F5 while the browser is in this endless pending status, it reloads the login page and I'm already logged in (so, the cookie are correctly set and ok).

Also, this behaviors occurs always the first-time I try to do a login after starting the application, while subsequent logins proceeds without any issue (so, for example: login -> stuck in pending -> F5 -> logged in -> logout -> login -> successful redirect to the returnUrl).
This remains consistent also if I delete all cookies between the first and second login: the first stucks in endless pending, the second goes.
(Although, rarely it does not apply 302 not just for the first login, but also for the first N logins, and that's completely random.)

The only cookie I have apart from the two login cookies that are created by the login POST (".AspNetCore.Identity.Application" and "idsrv.session") is the ".AspNetCore.Antiforgery" cookie.

This problem happens identically both on IdentityServer4 V3 and V4, on different projects (all using slightly different variations of the Quickstart) and using different machines.
On other browsers (Edge, Firefox) the problem never happens.
There is no output in browser's console (Preserve Log is ticked).
I compared the the request and response with Fiddler and I confirm that there is no evident difference between a successfully 302 redirect and a infinitely-pending 302 redirect (the only difference is the content of the login cookies).

The trace logs for both IdentityServer and NetCore gives the same outputs in both cases (302 applied or not): "[INF] AuthenticationScheme: Identity.Application signed in." and the rest of claims info for the IdentityServer tracing, and "[INF] Request finished in..." for the NetCore tracing.

Some things I tried to resolve the problem:
- No differences in using HTTP or HTTPS
- Setting all the cookies to SameSite = Lax and Essential, so no warning from the browser is raised about blocked cookies.
- Disabling the Antiforgery check and Antiforgery cookie generation.
- ...some other random changing and hacking when I became desperate. :)

So, there is a difference in the behavior, but with contexts that appears to be absolutely identical, the only discriminating parameter being the "first login from this particular client since the webapp started".

The only similar resolved problems I found on this issue tracker are relevant only to nginx, which I'm not using, so they are not relevant to me.

What I'm missing?

If someone can help, it'll be very appreciated.

Thanks.

**Comment by brockallen** [comment]
I don't know, but I'd be curious if you find something.

**Comment by dotnet555** [comment]
Ok, to keep you updated: this morning I got Chrome updated from version 84 to version 85 (released officially on 2020-08-25), and suddenly all seems to work ok: I got redirected without problem, even on first login, and the error is no more reproducible.

That's freaking scary, I tell ya.

Either there was a bug in version 84, or the update to 85 caused the reset of some local Chrome setting that where preventing the redirect (if something like this even exists): in both cases, it's a scary scenario.

**Comment by dotnet555** [comment]
Correction, it still happens, but it's not deterministic anymore: now is wildly random.

**Comment by brockallen** [comment]
Odd question: you're doing local testing with dummy accounts, right? Do you use the same password for your test users?

**Comment by dotnet555** [comment]
No, I'm using different passwords for different accounts.
The accounts are stored in a ASP.NET Identity DB, but I'd say that's probably not relevant, as the cookies are created correctly, or so it appears.

If it may be relevant, I'm using the HttpContext.SignInAsync(IdentityServerUser, AuthenticationProperties) overload.

The IdentityServerUser is created by passing he string (guid) Id in the constructor, and setting the AdditionalClaims manually (List<Claim>), and setting the IdentityProvider to IdentityServerConstants.LocalIdentityProvider (this last one is not set for a concrete reason: just a residual of the various random attempts I made to make this work).

**Comment by brockallen** [comment]
The reason I asked is that I'm seeing the same behavior, but only when I use a particular password. I know it sounds crazy, but I started changing the password I use for these test users, and the problem stopped happening. But the instant I try to use the particular password, it causes the problem in Chrome.

**Comment by dotnet555** [comment]
Ok, there MAY be something weird about the passwords, but, as I said, since this morning this problem has become more random, so no clear-cut way to tell.

By the way, because I suppose there is no hardcoded "bad password" in the OpenId framework (or at leas I hope so :) ), I thought it may be something weird about password complexity, so I turned down all the requirements (digits, lowercase, ecc...), but nothing changed.

So, I tried to change the password and, as you said, I was able to login without problems.
Then, I changed the password again, setting the old "problematic" one, and again I was able to login without problems.

The only difference between the first password setup and the second, today, is the version of Identity Server 4 (V4 instead of V3), but that's theoretically not relevant, as the PasswordManager is a custom class, in my case.

By the way, I'll do some more tests tomorrow (here is 8 PM now), also with other users and clients, and I'll let you know if the "double password change" is a consistent way to resolve the problem.

Thanks.

**Comment by dotnet555** [comment]
I confirm the change password it's not a consistent solution: the login immediately following the password-change seems to always successfully redirect (although it may be by chance), but subsequent logins with the same password will still occasionally fail.

I specify I launch a new debugging session of the identity server nearly every time I try, so apparently can't be a caching problem related to the identity server itself: it appears, so, to be something related to chrome's redirect cache or something like that but, again, I'm wild guessing.

**Comment by brockallen** [comment]
I have run fiddler traces to show that the browser gets the full response, so it shouldn't be anything server side. But, as I said, I found it odd that the use of that one password causes Chrome to not follow the redirect. And yes, it's only on the redirect where it's failing. Normal page re-renders are successful.

**Comment by brockallen** [comment]
I'm going to go ahead and close... if you ever find anything else out, feel free to add to this thread. Thanks.

**Comment by dotnet555** [comment]
Dunno if can be useful, but here I found a similar issue on Google Support:
https://support.google.com/chrome/thread/37163649?hl=en

So, someone else experienced the same problem in versions from 80 to 84 of Chrome, and found the issue is resolved in version 85 (although, for me, the problem is still there, except for now it's just happening random, instead of being consistently reproducible).

So, for reference, a way to mitigate this problem is to assure the version of Chrome is < 80 or >= 85.

I'll let you know if I'll find a more definitive solution.

**Comment by 839928622** [comment]
> Dunno if can be useful, but here I found a similar issue on Google Support:
> https://support.google.com/chrome/thread/37163649?hl=en
> 
> So, someone else experienced the same problem in versions from 80 to 84 of Chrome, and found the issue is resolved in version 85 (although, for me, the problem is still there, except for now it's just happening random, instead of being consistently reproducible).
> 
> So, for reference, a way to mitigate this problem is to assure the version of Chrome is < 80 or >= 85.
> 
> I'll let you know if I'll find a more definitive solution.

I experienced the same problem in vsersions 85.0.4183.121 of Chrome, but it works fine on  Microsoft Edge (version:85.0.564.63) also I noticed that two wanning on console :

```
Cookies marked with SameSite=None must also be marked with Secure to allow setting them in a cross-site context. This behavior protects user data from being sent over an insecure connection.

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site request

Name | Domain & Path
-- | --
idsrv.session | localhost/
.AspNetCore.Identity.Application | localhost/
```

dont know if this problem is related to the wanning above?  anyway,did you find any solution about it ?

**Comment by dotnet555** [comment]
No, the problem is not related to the SameSite policy because, after I set correctly my Cookie Policies, the cookie is indeed created after the post, and the browser does not give any warning regarding the cookies (either in the console or in the response's Set-Cookie details).
If you have this error, you have to adjust your Cookie Policies on the server side (Startup.cs, assuming you're using NetCore), according to witch protocol you're using (http or https).

And, no, I didn't find any definitive solution yet: as today, Chrome still sometimes doesn't execute the 302 command.

**Comment by 839928622** [comment]
so this  looks like a brower related issue . anyway, thanks for sharing .
