### ISSUE TITLE
Reconsider adding support for RP-initiated logout ui_locales parameter

### ISSUE THREAD

**Issue by jonekdahl** [IdentityServer/IdentityServer4#4789]
This is basically a request to revisit #2045 (I would have commented there, but that issue is locked). It seems that the OIDC committee recently has decided to include ui_locales in the [RP-initiated logout specification](https://openid.net/specs/openid-connect-rpinitiated-1_0.html), and @brockallen stated that:

> If the spec gets clarified on these points, then I'm fine with adding it.

If the maintainers agree, perhaps #2045 can be reopened?

**Comment by leastprivilege** [comment]
https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout
