### ISSUE TITLE
Token Endpoint client_id (required) should be optional?

### ISSUE THREAD

**Issue by acarlonvs** [IdentityServer/IdentityServer4#4790]
### Question

The token endpoint lists client_id as a required parameter: 

client_id
   client identifier (required)

Source: https://identityserver4.readthedocs.io/en/latest/endpoints/token.html

According to the oauth spec, client_id can be ommitted for the client_credentials grant, and indeed it seems to work that way - I can omit the client_id when calling IdentityServer4 /token endpoint with client_credentials grant. 

Isn't it only the grant_type that is required?

**Comment by leastprivilege** [comment]
Client ID is always required.

**Comment by acarlonvs** [comment]
@leastprivilege:

Here is a curl request calling the `/connect/token` endpoint that successfully retrieves an access token. Note there is no client_id.

    curl -X POST \
      https://demo.identityserver.io/connect/token \
      -H 'Authorization: Basic bTJtOnNlY3JldA==' \
      -H 'Content-Type: application/x-www-form-urlencoded' \
      -H 'Postman-Token: 4f3e8ad7-cb2e-4843-80f0-a666c871bcc9' \
      -H 'cache-control: no-cache' \
      -d 'grant_type=client_credentials'

My understanding is that only the grant_type is mandatory for all /token request types. Note in the [spec](https://tools.ietf.org/html/rfc6749#section-4.4.2) there is no client_id. 

Client Id is mandatory for the authorization code grant along with redirect uri and code, but not for client_credentials grant.

The client comes from the header Base64(clientid:secret). Not a major thing at all, it just mislead some of the pre-validation done at the perimiter which caused a client library to fail (as it expected to omit the client_id and the perimeter enforced it). Easily resolved.

Unless I am not understanding something.

**Comment by leastprivilege** [comment]
Oh I see - yes the client_id must either come from the post body or the authorization header.

The docs don't state that. Feel free to propose some language.

**Comment by acarlonvs** [comment]
>> Feel free to propose some language.
Sure, in this question or somewhere else?

**Comment by leastprivilege** [comment]
as a PR would be easiest.

**Comment by acarlonvs** [comment]
ok, will get to it in a couple of days.
