### ISSUE TITLE
IdentityServer 4 same site none cookie

### ISSUE THREAD

**Issue by attrib75** [IdentityServer/IdentityServer4#4795]
### Question

I'm using IdentityServer4 with .Net Core 2.0 (Not possible to upgrade at the moment). I'm trying set the Identity Server cookies to same site none using the following methods, but in Chrome, it is always displayed as empty (not assigned).

in startup.cs - ConfigureServices method (some of it seems redundant but trying everything)

```csharp
    services.AddAuthentication(options =>
        {
            options.DefaultScheme = "Cookies";
            options.DefaultChallengeScheme = "oidc";
        })

        .AddCookie("Cookies", options =>
        {
            options.Cookie.SameSite = SameSiteMode.None;
            options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
        });

        services.Configure<CookieAuthenticationOptions>(

        IdentityServerConstants.DefaultCookieAuthenticationScheme,
        options =>
        {
            options.Cookie.SameSite = SameSiteMode.None;
            options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
            // options.Cookie.IsEssential = true;
        });


        
```

also tried

         services.ConfigureApplicationCookie(options =>
            {
                options.Cookie.SameSite = SameSiteMode.None;
                options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
            });

 in startup.cs - Configure method (tried with and without this)

```csharp
     app.UseCookiePolicy(new CookiePolicyOptions
        {
            MinimumSameSitePolicy = SameSiteMode.None,
            Secure = CookieSecurePolicy.Always
        });

        // This will write cookies, so make sure it's after the cookie policy
        app.UseAuthentication();
```

Since this is reposted from StackOverflow, someone suggested I try

       var builder = services.AddIdentityServer(options =>
        {
            options.Authentication.CookieSameSiteMode = SameSiteMode.None;
        })

 but CookieSameSiteMode is not recognized.  I would appreciate any help.  Thank you

**Comment by mirusky** [comment]
I had the same issue with IdentityServer4 since Google Chrome [deny](https://www.thinktecture.com/en/identity/samesite/prepare-your-identityserver/) some cookies. My solution is setup `services.AddIdentityServer()` to use a diferent cookie police.

Somethink like:
```C#
var builder = services.AddIdentityServer()
                    .AddDeveloperSigningCredential()
                    .AddClientStore<ClientAppService>()
                    // TODO: Validate CORS with AspNet Middleware or CorsPolicyService or both?
                    // .AddCorsPolicyService<CorsPolicyAppService>()
                    .AddResourceStore<ResourcesAppService>()
                    .AddPersistedGrantStore<PersistedGrantAppService>()
                    .AddDeviceFlowStore<DeviceFlowAppService>()
                    .AddAbpIdentityServer<User>();

                builder.Services.ConfigureExternalCookie(options =>
                {
                    options.Cookie.IsEssential = true;
                    options.Cookie.SameSite = (SameSiteMode)(-1); //SameSiteMode.Unspecified in .NET Core 3.1
                });

                builder.Services.ConfigureApplicationCookie(options =>
                {
                    options.Cookie.IsEssential = true;
                    options.Cookie.SameSite = (SameSiteMode)(-1); //SameSiteMode.Unspecified in .NET Core 3.1
                });
```

**Comment by gutzi** [comment]
This could help you:

A cookie associated with a resource at was set with SameSite=None but without Secure. It has been blocked, as Chrome now only delivers cookies marked SameSite=None if they are also marked Secure.

https://stackoverflow.com/questions/60757016/identity-server-4-post-login-redirect-not-working-in-chrome-only
