### ISSUE TITLE
TokenRequest from Angular/Ionic App: No Client Identifier Found

### ISSUE THREAD

**Issue by ShreyanshDaga** [IdentityServer/IdentityServer4#4797]
### Question
I setup a simple IdentityServer using the sample code provided in documentation and I can make token requests from POST Man and simple C# client (also from sample code) However when I try to do the same from an Angular/Ionic app in TypeScript I keep getting  400 InvalidClient

### Minimal working example
![image](https://user-images.githubusercontent.com/6823110/91626341-2c26dd00-e963-11ea-8ca5-031683963b66.png)
Client configuration on my IdentityServer

![image](https://user-images.githubusercontent.com/6823110/91626362-524c7d00-e963-11ea-80a4-4cfa5218cc3d.png)
C# simple client where I can get the access_token and refresh token

![image](https://user-images.githubusercontent.com/6823110/91626371-68f2d400-e963-11ea-8b7e-692079b4fe62.png)
POSTMAN sample where I am getting the same response succesfully

Here is my Angular/Ionic side TypeScript code:
![image](https://user-images.githubusercontent.com/6823110/91626385-81fb8500-e963-11ea-93bc-59630994a7e0.png)
I am setting up the parameters i setup in body similar to POSTMAN and then finally make the http request as follows:
![image](https://user-images.githubusercontent.com/6823110/91626405-a192ad80-e963-11ea-8bce-5beeea6a4f98.png)

But this is what I see in the IdentityServer console:
![image](https://user-images.githubusercontent.com/6823110/91626409-b40ce700-e963-11ea-8ff8-c260573d5368.png)

The top response in the log is for my POSTMAN client, bottom ones are my attempt from Angular/Ionic, 

Am I missing something? I am not able to understand what is wrong

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by ShreyanshDaga** [comment]
Appreciate any help, I am not sure if this is an issue or not so added as a question!

**Comment by psyfakerr** [comment]
@ShreyanshDaga 

Hello, sending the request body as FormData instead of regular JSON fixed my problem.
