### ISSUE TITLE
trying to run identityserver and mvc authentication in same application

### ISSUE THREAD

**Issue by gthelp** [IdentityServer/IdentityServer4#48]
if there a sample to run the identity server 4 on a asp.net core mvc web application? I am trying to have 1 project that has it all and allows cookies on mvc side.
I created a persisted cookie (idsrv) when I SignInAsync on that authentication type and pass isPersistent, but all the CookieAuthenticationOptions such as timeout and name and such are ignored. Can't you use IdentityServer as a local authentication piece for cookies and auto route to login page if not authenticated?

Am I missing tsomething – it seems to be ignoring the cookie options I am setting

My startup in configservices
//setup for IdentityServer Service Component Middleware
//setup signing cert
var cert = new X509Certificate2(Path.Combine(_appEnv.ApplicationBasePath + @”\Infrastructure\IdentityServer\Cert”, “idsrv4test.pfx”), “idsrv3test”);

var cookieopt = new CookieAuthenticationOptions
{
AutomaticAuthenticate = true,
AutomaticChallenge = true,
AuthenticationScheme = IdentityServer4.Core.Constants.PrimaryAuthenticationType,
CookieDomain = “/”,
CookieHttpOnly = true,
CookieName = “TestCookie”,
LoginPath = “/Account/Login”,
LogoutPath = “/Account/Logout”,
SlidingExpiration = true,
ExpireTimeSpan = TimeSpan.FromMinutes(4)

};
var builder = services.AddIdentityServer(options =>
{
options.SigningCertificate = cert;
options.SiteName = “Test Site”;
options.AuthenticationOptions.CookieAuthenticationOptions = cookieopt;
});
builder.AddInMemoryClients(Clients.Get());
builder.AddInMemoryScopes(Scopes.Get());
builder.AddInMemoryUsers(Users.Get());

In Configure
app.UseIdentityServer();

**Comment by leastprivilege** [comment]
why are you doing that at all?

**Comment by gthelp** [comment]
just having 1 application to maintain for authentication at this time was ideal. All I had to do was UseIdentityServer and create claims login for it, and I was in business for my local application and was next testing my api controllers. It created a session only login, so I wanted to a cookie authentication with a sliding scale and absolute expiration, but can not get that to work using the AuthenticationOptions.CookieAuthenticationOptions. Just seeing if I am using a wrong method.

**Comment by pauldotknopf** [comment]
I think using IdentityServer4 with existing authentication (ASP.NET Identity EntityFramework) should be supported.

For what it is worth, I managed to get this working with the default ASP.NET template with account management.

```
var builder = services.AddIdentityServer(options =>
{
    options.SigningCertificate = cert;
    // important, tells IdentityServer to use authentication from ASP.NET Identity
    options.AuthenticationOptions.PrimaryAuthenticationScheme = new IdentityOptions().Cookies.ApplicationCookie.AuthenticationScheme;
});
```

Then, use ASP.NET Identity look you would in the default template, except we need to add a custom ```IUserClaimsPrincipalFactory<TUser>```.

```
services.AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>, UserClaimsPrincipalFactory>();
services.AddIdentity<ApplicationUser, IdentityRole>()
    .AddEntityFrameworkStores<ApplicationDbContext>()
    .AddDefaultTokenProviders();
```

This claims provider adds some claims required by IdentityServer.

```
public class UserClaimsPrincipalFactory : IUserClaimsPrincipalFactory<ApplicationUser>
{
    private IdentityOptions _options;

    public UserClaimsPrincipalFactory(IOptions<IdentityOptions> optionsAccessor)
    {
        _options = optionsAccessor.Value;
    }

    public Task<ClaimsPrincipal> CreateAsync(ApplicationUser user)
    {
        var id = new ClaimsIdentity(_options.Cookies.ApplicationCookieAuthenticationScheme,
            _options.ClaimsIdentity.UserNameClaimType,
            _options.ClaimsIdentity.RoleClaimType);
        id.AddClaim(new Claim(_options.ClaimsIdentity.UserIdClaimType, user.Id));
        id.AddClaim(new Claim(_options.ClaimsIdentity.UserNameClaimType, user.UserName));

        // required by IdentityServer
        id.AddClaim(new Claim(JwtClaimTypes.Name, user.UserName));
        id.AddClaim(new Claim(JwtClaimTypes.Subject, user.Id));
        id.AddClaim(new Claim(JwtClaimTypes.IdentityProvider, _options.Cookies.ApplicationCookieAuthenticationScheme));
        id.AddClaim(new Claim(JwtClaimTypes.AuthenticationTime, DateTimeOffset.UtcNow.ToEpochTime().ToString(), ClaimValueTypes.Integer));

        return Task.FromResult(new ClaimsPrincipal(id));
    }
}
```

That is it. Of course, you will now have to write the ASP.NET Endpoints that handle the authorization, etc. You will also have to write a ```IProfileService``` that will query the ```ApplicationUser``` from EntityFramework.

**Comment by leastprivilege** [comment]
I don't understand this

> you will now have to write the ASP.NET Endpoints that handle the authorization

why? that's done by identityserver

**Comment by pauldotknopf** [comment]
> why? that's done by identityserver

True, but the default asp.net project template has a lot more functionality, such as two-factor authentication, external sign in, locking out users, auto-locking account after X number of attempts, etc.

**Comment by leastprivilege** [comment]
Exactly - and they are supposed to be composable. IdentityServer is doing all the protocol work - you implement **your** login workflow.

This will become more seamless once we get closer to release. But that's the idea.

**Comment by gthelp** [comment]
pauldotknopf - Thank you for the suggestions. I will plan to revisit using identity server with our project. Looking forward to this Great product coming out of Beta.
