### ISSUE TITLE
UserInfo endpoint returns only "sub" claim

### ISSUE THREAD

**Issue by wojciechrak** [IdentityServer/IdentityServer4#480]
## Short story:
I want to get user email address in my react-redux js app. I am using [redux-oidc](https://github.com/maxmantz/redux-oidc) which utilizes [oidc-client-js](https://github.com/IdentityModel/oidc-client-js). But `/connect/userinfo` endpoint returns only `sub` claim.

````
GET /connect/userinfo HTTP/1.1
Host: localhost:44356
Authorization: Bearer ...
````
````
{
  "sub": "4"
}
````

## Long story:
My access token has some additional claimes, namely `role` and `email` (from `JwtClaimTypes`)

````
{
  "nbf": 1479243468,
  "exp": 1479244068,
  "iss": "https://localhost:44356",
  "aud": "https://localhost:44356/resources",
  "client_id": "eks_client",
  "sub": "4",
  "auth_time": 1479238034,
  "idp": "local",
  "role": "customer",
  "email": "test@user.com",
  "scope": [
    "openid",
    "profile"
  ],
  "amr": [
    "pwd"
  ]
}
````

I am using custom `IProfileService` in which I map my claims (I assume it works OK, since claims are present in access token).
Also there is custom  `ScopeStore` where I have standard scopes: OpenId, Profile, and "my_scope| with `IncludeAllClaimsForUser = true`.
And a custom `ClientStore` with `AllowAccessToAllScopes = true`.

And in client-side app I request following scopes: 
````
response_type: "id_token token",
scope: "openid profile my_scope",
````

I also have role-based authorization in my API and it works correctly ie. `[Authorize(Roles = "customer")]`

So what am I missing?

**Comment by brockallen** [comment]
For the user info endpoint to return claims, you must have requested scopes that model identity data. IOW, you need to ask for more identity scopes (such as email or a custom identity scope where you've configured the claims you want the client app to get back). Claims in the access token are unrelated.

**Comment by wojciechrak** [comment]
I've added additional scopes to `UserManagerSettings`, so now my scopes section looks like this:
````
scope: "openid profile my_scope email roles",
````

I've also added these to IdentityServer Scopes:
````
StandardScopes.Email,
StandardScopes.RolesAlwaysInclude,
````

Now user info endpoint return `email` and `role` claims. Both are also available in access_token, and `role` is present in id_token.

**Comment by nhdmalik** [comment]
@wojciechrak I am struggling the same issue, by applying your suggestions it give invalid_scope error. I am using identityserver4. Can you give the complete example with code? thanks.
