### ISSUE TITLE
Remember consent: where it is stored and how it works

### ISSUE THREAD

**Issue by nzhuravel** [IdentityServer/IdentityServer4#4801]
After upgrade to IdentityServer4 v 4.0.4 we noticed that checkbox "Remember my choice" on consent screen actually does not affect anything, consent screen is shown upon first login and then it's not showing up. It can be an issue on our side but everything regarding consent is happening internally in IdentityServer4 code (we use IdentityServer4.EntityFramework package for storage of client configs, users and persistent grants)
Here are properties regarding Client config: 
```
RequireConsent=true,
ConsentLifetime=null,
AllowRememberConsent=true.
```
So wondering if I could find out whether 'remember consent' flag is stored successfully in DB. I started investigating and looks like persistent grant context is responsible for storing this flag, but it is rather hard to figure out at which point this flag is saved and when it's being retrieved since everything is hashed in persistent grant context tables. 
So if someone could point me to places in source code where I can see where that flag is checked and then debug why consent screen is not shown on login.

**Comment by brockallen** [comment]
https://identityserver4.readthedocs.io/en/latest/topics/deployment.html#operational-data

**Comment by nzhuravel** [comment]
How this links helps me to find out whether Remember my choice value is stored correctly? I've already mentioned that we use PersistedGrantDbContext from IdentityServer4.EntityFramework.Storage without any customization. My question was can you point me to part of codebase where 'Remeber my choice' flag is used to verify whether to show Consent screen or not? I could not find it by myself. Thanks.

**Comment by nzhuravel** [comment]
ok, I debugged the way consent is stored. Flag RememberConsent now does not affect anything except scopes are logged (code taken from https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs):
```
if (request.Client.AllowRememberConsent)
{
            // remember consent
            var scopes = Enumerable.Empty<string>();
            if (consent.RememberConsent)
            {
                 // remember what user actually selected
                 scopes = request.ValidatedResources.RawScopeValues;
                 Logger.LogDebug("User indicated to remember consent for scopes: {scopes}", scopes);
              }

             await Consent.UpdateConsentAsync(request.Subject, request.Client, request.ValidatedResources.ParsedScopes);
}
```
Does not matter if I leave that checkbox checked/unchecked consent in db is stored like this:
{"SubjectId":"sensored","ClientId":"sensored","Scopes":["openid","profile","sensored"],"CreationTime":"2020-09-01T12:48:24Z","Expiration":null}

@brockallen , can you please confirm that Consent screen is shown to user if client.AllowRememberConsent =true and consent is expired (if consent lifetime is set) or if AllowRememberConsent flag for client is set to false. In other cases consent screen in not shown upon login.

Also why that RememberConsent flag is needed if it does not affect anything or am I missing something?
