### ISSUE TITLE
Quickstart says use port 5002, but IIS Express doesn't allow that

### ISSUE THREAD

**Issue by korggy** [IdentityServer/IdentityServer4#4803]
Hello, the quickstart [Interactive Applications with ASP.NET Core](https://identityserver4.readthedocs.io/en/latest/quickstarts/2_interactive_aspnetcore.html#creating-an-mvc-client) says 

> Once you've created the project, configure the application to run on port 5002.

However, the mvc demo template is configured to use IIS Express, and IIS Express only allows SSL on ports 44300 through 44399 (see [Handling URL Binding Failures in IIS Express](https://docs.microsoft.com/en-us/iis/extensions/using-iis-express/handling-url-binding-failures-in-iis-express)). I spent an hour or so trying to get the mvc app to run on 5002 but eventually gave up and used 44327 which worked fine.

Also, the instructions in the quickstart don't specify whether to configure the app to run http or https on port 5002. Based on the rest of the quickstart I'm assuming it means https.

Recommend changing the quickstart template to use Kestrel or change the documentation to suggest https and a port in the 44300-44399 range.

**Comment by leastprivilege** [comment]
Thanks. I added a note to the docs.

**Comment by MarvinZ** [comment]
Same here.. lost a good amount of time because of this error.

I used another port and ran it in another VS instance.
