### ISSUE TITLE
Quickstart says to use AllowOfflineAccess but the accompanying code sample doesn't include it

### ISSUE THREAD

**Issue by korggy** [IdentityServer/IdentityServer4#4804]
The quickstart at [ASP.NET Core and API access](https://identityserver4.readthedocs.io/en/latest/quickstarts/3_aspnetcore_and_apis.html#modifying-the-client-configuration) says

> Updating the client configuration in IdentityServer is straightforward - we simply need to add the api1 resource to the allowed scopes list. In addition we enable support for refresh tokens via the AllowOfflineAccess property

but the code sample doesn't include the AllowOfflineAttribute property:

```
new Client
  {
    ClientId = "mvc",
    ClientSecrets = { new Secret("secret".Sha256()) },

    AllowedGrantTypes = GrantTypes.Code,

    // where to redirect to after login
    RedirectUris = { "https://localhost:5002/signin-oidc" },

    // where to redirect to after logout
    PostLogoutRedirectUris = { "https://localhost:5002/signout-callback-oidc" },

    AllowedScopes = new List<string>
    {
        IdentityServerConstants.StandardScopes.OpenId,
        IdentityServerConstants.StandardScopes.Profile,
        "api1"
    }
  }
```

**Comment by leastprivilege** [comment]
thanks. Added.
