### ISSUE TITLE
Quickstart should mention AlwaysIncludeUserClaimsInIdToken

### ISSUE THREAD

**Issue by korggy** [IdentityServer/IdentityServer4#4805]
The quickstart [Interactive Applications with ASP.NET Core](https://identityserver4.readthedocs.io/en/latest/quickstarts/2_interactive_aspnetcore.html#further-experiments) challenges the user to

> Feel free to add more claims to the test users - and also more identity resources.

However, the quickstart doesn't mention the AlwaysIncludeUserClaimsInIdToken property in IdentityServer4's client configuration, without which no additional user claims will be returned. This could be very frustrating for someone just learning how to use IS4 from scratch (it was for me anyway).

**Comment by leastprivilege** [comment]
You mean the claims are not in the id_token returned from the front channel? But ultimately asp.net core will collect them via userinfo. 

So what did exactly fail for you?

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
