### ISSUE TITLE
IdentityServer4 without using oidc-client

### ISSUE THREAD

**Issue by alishahzadone** [IdentityServer/IdentityServer4#4806]
For some reason, I don't want to use/introduce the oidc-client library in front-end apps either its Angular SPA, native Android or iOS. Is it possible to call the endpoints one by one manually like first calling `/connect/authorize` and then `/connect/token` in authorization code flow? When I try calling the `/connect/authorize` endpoint, it gives me an error "code challenge required". Please advise any solution where I can test calling the APIs manually one after the other in postman and then in all apps without using the oidc-client.

**Comment by brockallen** [comment]
Yes you can, but you need to follow the protocols. Check the specs for those details.

**Comment by alishahzadone** [comment]
> Yes you can, but you need to follow the protocols. Check the specs for those detail

@brockallen I have prepared the GET request with all possible parameters for `/connect/authorize` endpoint but in the ends it asks for a code challenge. What value should I provide to code challenge?

**Comment by brockallen** [comment]
> Check the specs for those details.

Or we can provide consulting to help you understand the protocols and how they work.

**Comment by alishahzadone** [comment]
> Or we can provide consulting to help you understand the protocols and how they work.

How can you do? I would be interested to understand this without using oidc-client.

**Comment by brockallen** [comment]
https://identityserver4.readthedocs.io/en/latest/intro/support.html
