### ISSUE TITLE
Allow for use of application identity in Azure

### ISSUE THREAD

**Issue by wzoet** [IdentityServer/IdentityServer4#4809]
**Is your feature request related to a problem? Please describe.**
We use IDS4 in Azure and we would like to remove the userid and password from our sql server connection string. This can be accomplished using Application identities

**Describe the solution you'd like**
According to MS documentation, this requires some extra code within the constructor of the datacontexts. We would like a configuration flag to activate this feature

**Describe alternatives you've considered**
A simple solution could be to make the current datacontexts partial classes. This way we could extend the constructor ourselves. However, making datacontexts partial could result in potential issues when not used correctly.

**Comment by bryantlikes** [comment]
This isn't really an Identity Server issue, just standard Entity Framework. You can specify the connection string in your startup. Something like:

``` c#
public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(o => o.UseSqlServer(Configuration.GetConnectionString("DefaultConnection")));
```

You can store the connection string in your config file (not secure) or in Azure you can set it in the Application Settings (more secure). I use the Azure Key Vault to store my connection strings since that lets me share them across multiple Azure web applications.

**Comment by wzoet** [comment]
Yes, I know what you mean. We started off from the EF QuickStart setup, so we have this set up currently and our connection strings are in keyvault as well which is accessed using application identity.
However we would like to remove the userid and password from the connection string altogether and use application identity as documented in https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi
This solves continuously replacing passwords (which expire on a regular interval as per company security policy).

For the applicationdbcontext we can already do this, but the configurationdbcontext and persistedgrantsdbcontext are embedded in the IDS4 library. Or could we subclass them somehow?

**Comment by wzoet** [comment]
This can indeed be accomplished by inheriting from the ConfigurationDbContext and PersistedGrantDbContext. We missed that the methods AddConfigurationStore and AddOperationalStore can be called using generics which allows for using custom datacontexts. 

Thanks for making this great product!
