### ISSUE TITLE
Identity Server and single file published apps

### ISSUE THREAD

**Issue by javiercn** [IdentityServer/IdentityServer4#4810]
Hi @leastprivilege and @brockallen.

We've recently updated the integration in ASP.NET Core to use Identity Server 4.0.4. It was very smooth! so great job there ❤️ 

That said, we found a bug though our manual validation process that relates to publishing single file applications. I found the root cause to be the access to the assembly location here which does not exist for single file published apps https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Configuration/IdentityServerApplicationBuilderExtensions.cs#L57

The impact is that this blocks ASP.NET Core apps that use the latest identity server from being published as a single file.

I'm not sure how problematic this is to fix, could an alternative be to stamp the version you are looking for in an assembly attribute and use that instead to retrieve the value? Would it be ok to omit the version if the app is single file publish?

Thanks in advance, and If there's anything we can do to help let us know

**Comment by leastprivilege** [comment]
Hey, 

do you know a way to retrieve that value using a compatible API? If not possible, the short term solution would be to disable the version logging for those incompatible scenarios.

Either way - please create a PR.

thanks!

**Comment by leastprivilege** [comment]
@javiercn any update?

**Comment by javiercn** [comment]
@leastprivilege thanks for the response.

I'm wrapping up some other tasks, but I'll hope to get to this later this week. I'll have to look a bit more in depth to understand what the value is and what is used for. Your solution of disabling the version login in this case sounds good to me.

**Comment by leastprivilege** [comment]
Well - if there is a way to get the same value from your new fancy single file scenario - that would be ideal ;)

**Comment by leastprivilege** [comment]
merged
