### ISSUE TITLE
How to set Tenant during auth request

### ISSUE THREAD

**Issue by winromulus** [IdentityServer/IdentityServer4#4822]
### Question
How does the "Tenant" parameter work? In the logs we see `"Tenant": null`
Where does the Tenant value come from and how are we supposed to set it?

### Relevant parts of the log file

```
   ` "Scopes": null, "AuthorizationCode": null, "RefreshToken": null, "UserName": null, "AuthenticationContextReferenceClasses": null, "Tenant": null, "IdP": null`
```

**Comment by brockallen** [comment]
It's passed via acr_values: https://identityserver4.readthedocs.io/en/latest/endpoints/authorize.html

**Comment by winromulus** [comment]
@brockallen it doesn't seem to work on the latest version. Is this for specific flows/grant types?

**Comment by brockallen** [comment]
It's working for me in my projects.

**Comment by winromulus** [comment]
@brockallen can you provide an example? Also, again, is this limited to specific flows/grant types?

**Comment by brockallen** [comment]
Any of our existing samples should work -- just update them to pass the acr_values.
