### ISSUE TITLE
.NET 5 Beta 8 - AddDeveloperSigningCredential persisted or not throws Json Error that is translated to Assert causing tests to fail

### ISSUE THREAD

**Issue by JohnGalt1717** [IdentityServer/IdentityServer4#4823]
### Issue / Steps to reproduce the problem
1. Use the sample, update to .NET 5 Beta 8 with latest VS.NET 2019.
2. Make sure it's using AddDeveloperSigningCredential (doesn't matter if you choose to persist or not)
3. Run a unit tests that causes AddDeveloperSigningCredential to be hit.

```
System.ArgumentException: 'IDX10805: Error deserializing json: 'System.String' into 'System.RuntimeType'.'

DebugAssertException: Method Debug.Assert failed with '
', and was translated to Microsoft.VisualStudio.TestPlatform.TestHost.DebugAssertException to avoid terminating the process hosting the test.

```

This also throws when debugging but doesn't terminate the TestHost.

One presumes it's using System.Text.Json and something has changed, but that is just a guess.

**Comment by leastprivilege** [comment]
@javiercn does this affect you? @blowdart

**Comment by jhancock4d** [comment]
Any chance of a work around? When is 5.0 beta scheduled? This specifically blocks tests from running right now and .net 5 RC is go live.

**Comment by leastprivilege** [comment]
can't repro with RC2
