### ISSUE TITLE
Can I use as an MVC client an application on .net framework 4.5.1 with identityserver4 v4.0.4

### ISSUE THREAD

**Issue by DobrovAlexey** [IdentityServer/IdentityServer4#4828]
Hi, can you please tell me Can I use as an MVC client an application on .net framework 4.5.1 with identityserver4 v4.0.4.
Client support on .net framework 4.5.1, is it only through Ws federation or are there any other options?
I want to build identityserver4 server on .net core 3.1
Will I have to revert to old versions of identityserver4 in this case? to connect client applications written in .net framework 4.5.1

Thanks!

**Comment by leastprivilege** [comment]
WS-Federation would be one options - or using OWIN + OIDC.

**Comment by mirusky** [comment]
@leastprivilege could you provide any examples or sample repo with it working?

**Comment by leastprivilege** [comment]
@mirusky Well - you could browse the old IdentityServer3 samples....there's an archived repo in this org.

**Comment by mirusky** [comment]
I've tried some sample and they work, but when I need to run IdentityServer client with your own user ( because some layout colors, custom buttons etc ... ) I can't make this work, I didn't see any client sample with Owin + Database / AspNet Identity
