### ISSUE TITLE
Where can I find the repo of demo.identityserver.io?

### ISSUE THREAD

**Issue by nhonoskywalker** [IdentityServer/IdentityServer4#4829]
### Question
Where can I find the repo of demo.identityserver.io?
I need an example like MVC to demo.identityserver4.io to google but with azureAD. I tried adding AzureAD with the quickstart but it does not work like google. 
After a week of playing with it seemed like AzureAD is not supported in MVC and IS4 quickstart sample?

### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer4.Demo
