### ISSUE TITLE
Persist access_token across deploys / build

### ISSUE THREAD

**Issue by alesten** [IdentityServer/IdentityServer4#483]
Hey

I've followed this: http://docs.identityserver.io/en/dev/quickstarts/8_entity_framework.html#using-entityframework-core-for-configuration-data
I have the data base up and runnig, I can log in with a user, get a token and then call my api with that token to get some info that I want.
If I then go ahead and rebuild my project I get a 401 on my api and have to login again.

How do I persist my access token so I can use it when I want and I can desice for myself when I want to revoke it?

**Comment by Lutando** [comment]
You must be using `SetTemporarySigningCredential` when configuring your identity server. basically everytime you deploy/run, your identityserver generates new random signing credentials. You can use an `X509Certificate` as a "persisted signing credential". Check the API [here](https://github.com/IdentityServer/IdentityServer4/blob/f964184bbe7ea45d4cc2369516b14a509a3531a5/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/Crypto.cs#L47)


And also see - http://docs.identityserver.io/en/dev/topics/crypto.html

**Comment by brockallen** [comment]
Yep, @Lutando's right.

**Comment by alesten** [comment]
So how would you go and do this in development where I don't have a certificate?

**Comment by brockallen** [comment]
You make one: https://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/
