### ISSUE TITLE
Support for .Net 5 / EF Core 5

### ISSUE THREAD

**Issue by No1e** [IdentityServer/IdentityServer4#4831]
### Question
Dear Dominick & Allen,

Could you tell me what is the plan for supporting .Net 5 / EF Core 5? I know that those are still in Preview, but they are about to be released soon.

Thank you and best regards,
Nole

**Comment by No1e** [comment]
Please ignore my question. I have found the answer in your Milestones page.

**Comment by joaoantunes** [comment]
Where can I see the Milestones showing the support for .Net 5? The only thing that I can find is that IS is going to be paid, not sure even how much.

**Comment by leastprivilege** [comment]
IdentityServer4 works fine on .NET 5.

**Comment by joaoantunes** [comment]
I can host and identityserver4 using. Net core 5? I was trying to update the project from 3.1 to 5 and was unable to do it. Which version supports. NET5?

**Comment by leastprivilege** [comment]
v4.x works fine on .NET 5 - Microsoft ships it with its templates.
