### ISSUE TITLE
Consent is saved regardless of RememberConsent checkbox value

### ISSUE THREAD

**Issue by nzhuravel** [IdentityServer/IdentityServer4#4833]
Version: 4.0.4

### Issue / Steps to reproduce the problem
Enable Consent for client by setting
client.RequireConsent=true,
client.AllowRememberConsent=true
Login, leave RememberConsent checkbox unchecked.
Log out. Login again.

Actual result: consent screen is not shown upon login
Expected result: since user did not hit RememberConsent it should be shown after each login until user agrees to save it.

Editional:
By looking into source code looks like RememberConsent  does not play any role during consent save. Consent is saved regardless of RememberConsent checkbox value
https://github.com/IdentityServer/IdentityServer4/blob/88ad5ee315de7234da47753d13bad06fba47a13b/src/IdentityServer4/src/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs#L312

**Comment by brockallen** [comment]
Confirmed.

**Comment by brockallen** [comment]
PR submitted
