### ISSUE TITLE
Hook into IdentityServer4 session cookie sliding expiration

### ISSUE THREAD

**Issue by slask** [IdentityServer/IdentityServer4#4837]
I need to run some custom code (manage another custom cookie), at the moment when IdentityServer performs the sliding of the expiration time on the session cookie (```idsrv```).

How or where can I hook into the IdentityServer pipeline to accomplish this? Is there something I can override or is there an event I can subscribe to?

I am currently using IdentityServer4 3.x in an asp.net core 3.1 app.

**Comment by leastprivilege** [comment]
If you need more control, add your own cookie authentication handler and set it as the default scheme.
