### ISSUE TITLE
injecting ctor of IScopeStore implementation causes circular reference error

### ISSUE THREAD

**Issue by brentblunden** [IdentityServer/IdentityServer4#484]
Hi,

I have a db repository that is registered in the startup with AddSingleton.  I want to use this db repository for accessing persisted scope configurations and implementing IScopeStore.  When I try to inject it in the ctor of my IScopeStore implementation I get a circular reference error at runtime.  How can I get hold of the registered db repository in the IScopeStore?  Is there a particular pattern that needs to be followed?

Best Regards,
Brent

**Comment by Lutando** [comment]
There is no particular pattern, but the norm is to inject the `DbContext` or a wrapped `DbContext` into `IScopeStore`. Unfortunately the information that you've given us isn't enough to deduce the problem. Perhaps a start would be to show us how you're adding your services to the DI and also the code snippets of each the ctors of each of those services.

**Comment by brentblunden** [comment]
Thank you for your response.  While putting together the code bits you requested I found a different injection into the db repository class ctor that was causing the problem.  This is no longer a concern.  
Best Regards, 
Brent
