### ISSUE TITLE
Support policy (security fixes) for aspnetcore2 branch

### ISSUE THREAD

**Issue by ma499** [IdentityServer/IdentityServer4#4843]
### Question

What is the support / security patching policy in relation to the aspnetcore2 branch?

Can I assume security patches will be provided until [end of LTS for .NET Core 2.1](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) (August 2021) or will the project stop providing security patches beforehand?

It would be helpful to have this policy for all branches documented in the root Readme.md.

**Comment by leastprivilege** [comment]
You can assume security patches 'til ASP.NET Core 2.1/3.1 EOL.
