### ISSUE TITLE
how to change BaseUrl of the Identityserver

### ISSUE THREAD

**Issue by saisworld** [IdentityServer/IdentityServer4#4857]
### Question
I m currently working on setting up Identityserver for my organisation, I have hosted it on AKS cluster with multiple replicas. I have set it up in such a way that when a request comes from internet with url "identity.abc.com" then it gets terminated at the gateway and from there it uses identity.internal.abc.com, I have deployed the TLS  certificates into each pod with identity.internal.abc.com. This is creating problem as the discover url is generating all the Urls using the "internal" urls. Is there a way to change the base url in code so that it picks up the external url (identity.abc.com)?

### Minimal working example
Previously, there was an option available to change the base Url using the below code -
```csharp
   // <code goes here>
   services.AddIdentityServer(options =>
{
   options.PublicOrigin = "https://identityserver.io";
});
```
But looks like this has been removed in newer versions. Could you please advise if there is an option available to change the base url?

**Comment by brockallen** [comment]
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

**Comment by saisworld** [comment]
> https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-3.1

This only forwards the request headers, hosts etc to the end application. However, my issue is different, the discoveryendpoint displays all the Urls with the internal domain name (identity.internal.abc.com) instead of "identity.abc.com".

**Comment by brockallen** [comment]
We use the incoming host header, and if you configure the reverse proxy correctly then it works properly. There's another issue that already explains this in detail (I can't find it at the moment).

**Comment by brockallen** [comment]
Here's the other issue: https://github.com/IdentityServer/IdentityServer4/issues/4631

**Comment by CesarD** [comment]
> We use the incoming host header, and if you configure the reverse proxy correctly then it works properly. There's another issue that already explains this in detail (I can't find it at the moment).

Generically speaking, what should we need to explain to the corresponding team in a company where we are trying to setup IdentityServer4 behind a reverse proxy? What specific stuff is IdS4 expecting to receive?

**Comment by leastprivilege** [comment]
All the public origin really did, was to call this extension method - so if you really want to hard code this - here's the code:

https://github.com/IdentityServer/IdentityServer4/blob/c5b8280a82e9077024180e61db6a265a0dd62f5e/src/IdentityServer4/src/Extensions/HttpContextExtensions.cs#L29-L39
