### ISSUE TITLE
More flexible redirect uri validation options for signed requests

### ISSUE THREAD

**Issue by bigheadedmonster** [IdentityServer/IdentityServer4#4865]
**Redirect Uri validation based on validated request / authorization context**
We would like to have better options, when making custom implementations of ex. IRedirectUriValidator.

A specific case is allowing any redirect_uri from withint a whitelisted domain for a client, when the authorization request is signed using the OIDC RequestObject.

**Possible solutions**
We have a specific problem of writing custom redirect_uri validation based on signed authorization requests (i.e. a signed and valid RequestObject is present in the request).
A general solution would be to make the validated request and/or the authorization context available or more easily accessable in ex the IRedirectUriValidator by additional parameters or some DI available interface (the obvious ones results in circular dependencies like IIdentityServerInteractionService).

We would also be able to solve our specific case, if we had some easy way to know if the request has a valid RequestObject parameter in our IRedirectUriValidator implementation.

**Alternatives**
As of now, we a looking at the request using the IHttpContextAccessor and looks for the "request" parameter and does some custom logic and uses a distributed  cache to keep state for the entire flow.

**Comment by bigheadedmonster** [comment]
The wish is partly a pre-burner to support the Pushed Authorization Request (PAR) draft: https://tools.ietf.org/html/draft-ietf-oauth-par-03 - (which would be another awesome feature for IDSrv :)

If you read the introduction in the PAR draft, they comment on this subject and argues that when you can authorize the clients up-front, one of the benefits is that you can be more dynamic in your redirect URI validation.

**Comment by bigheadedmonster** [comment]
We have a wide range of different customers with different clients and environments (dev, test etc.). It is a frequent job to change client redirect_uris for different clients and often registering multiple redirect_uris for the same clients. 
Often, redirect_uris also changes to something else, and again triggers manual configuration and validation.

If you allow automatic client configuration of redirect_uris by some authorized process, this would be equivalent to allowing it dynamically in authorized requests.

**Comment by leastprivilege** [comment]
OK - I added it to the 5.0 milestone for consideration.
