### ISSUE TITLE
StateHash requires signing credentials

### ISSUE THREAD

**Issue by jonbergholmas** [IdentityServer/IdentityServer4#4867]
Hi,

I´m updating from version 2.5.3 to 3.1.3.
I have a mobile application which authorize users using `GrantType.AuthorizationCode` and receiving an `AccessTokenType.Reference`.

I now recieve the exception:
```
[IdentityServer4.Hosting.IdentityServerMiddleware] Unhandled exception: No signing credential is configured.
System.InvalidOperationException: No signing credential is configured.
   at IdentityServer4.ResponseHandling.AuthorizeResponseGenerator.CreateCodeAsync(ValidatedAuthorizeRequest request)
```

It seems that the `AuthorizationCode` created in `src/ResponseHandling/Default/AuthorizeResponseGenerator.cs` now have a `StateHash` which requires signing credentials to be configured. See:

https://github.com/IdentityServer/IdentityServer4/blame/41f83cd7bf22c87fd4be98df9b8eaefafd80dbc2/src/IdentityServer4/src/ResponseHandling/Default/AuthorizeResponseGenerator.cs#L228

The state hash seem to relate to the Financial grade API.
https://openid.net/specs/openid-financial-api-part-2-ID2.html#introduction

How is the state hash realated to the switch to Asp.Net Core 3?

RFC6749 specifies that the state should be returned as-is so why is it required to specify an algorithm for hashing it?
```
state
     REQUIRED if the "state" parameter was present in the client
     authorization request.  The exact value received from the client. 
```

Whats my best route to move forward, is it to implement my own `IAuthorizeResponseGenerator.cs`?

**Comment by leastprivilege** [comment]
Well - it's probably easier to introduce a signing credential.

I guess it is a bit of an edge case to do reference tokens only (and no id_token or JWTs in general). Maybe we can introduce a setting to disable state_hash.

> RFC6749 specifies that the state should be returned as-is so why is it required to specify an algorithm for hashing it?

the hashing algorithm use for hashing the state must have the same length as the signing algorithm - hence the hard dependency on a signing credential.
