### ISSUE TITLE
That's not really recommended - an API should only trust one authority.

### ISSUE THREAD

**Issue by AgSync-Aaron** [IdentityServer/IdentityServer4#4872]
> That's not really recommended - an API should only trust one authority. 
That said - you can add one authentication handler for each authority.

_Originally posted by @leastprivilege in https://github.com/IdentityServer/IdentityServer4/issues/2256#issuecomment-383382200_

In my org there are multiple environments (development, staging, and production) for our main applications. Currently each environment (auth server) uses the same issuer and signing certificate. Meaning development tokens are valid in production! I am looking to secure this by having separate issuers and signing certs. 

However, we have some independent micro-services (think image resizing, or PDF manipulation) that don't rely on any outside services at all, but they need to be secured to valid users only. I don't want to have a separate environment for each one of these services (single authority each). For these micro-services I would like to just have one environment that accept tokens from development, staging, or production. 

If trusting multiple authorities is not recommended, can you tell me what would be recommended in this situation? Or can you point me to some good reading on this specific topic?

Thanks!

**Comment by mirusky** [comment]
It's just a suggestion not effective answer but what you think about using resource based api? 

Like IdentityServer APIs [example](https://github.com/IdentityServer/IdentityServer4/blob/main/samples/Clients/src/APIs/ResourceBasedApi/Startup.cs#L24-L45), so you could set up each microservice to accept just a specific audience then yours PROD Env could use `prod-microservice1" and your Dev could use `dev-microservice1` this way when a dev token goes into production the resource will automatically deny that token since the audience is not as expected I think.

**Comment by AgSync-Aaron** [comment]
Thanks @mirusky there is some useful info in there. I thought about using the audience (like the first example you provided) to separate the different environments. The Development auth server could give an audience of `http://dev.site.com`, stage could give `http://stage.site.com` and prod auth could give `http://site.com` for it's `aud` claim. The micro-services could ignore the audience check and allow any valid token while the main applications could check the audience. I think that would work great to keep the environments segregated.

Unfortunately, the auth servers (one in each environment) would be back to sharing the same signing key so validation on the micro-services works across environments, and that doesn't solve my main goal; keeping the production signing cert secure (no devs, not even me can have it).

I'll probably just make the microservices public (no auth) or add a simple static key to the request for auth, like what azure functions does.
