### ISSUE TITLE
Fail the "Authorization Code Grant" from "user interaction"?

### ISSUE THREAD

**Issue by tiesmaster** [IdentityServer/IdentityServer4#4877]
### Question
We'd like to instruct IdentityServer somehow to return to the authorization callback, and indicate failure in a scenario where that fails for us during the user interaction (see below for some additional context). We're not sure if this is allowed by the spec, but it does look like [OAuth2](https://tools.ietf.org/html/rfc6749#section-4.1.2.1), and [OIDC](https://openid.net/specs/openid-connect-core-1_0.html#AuthError) supports returning an error response. We also noticed IdentityServer also uses that in certain scenarios (such as when validation fails of the client, for example).

However, we didn't find any support in IdentityServer to instruct it as such. Before overriding some of the injected types into IS4, I first want to validate that we're not overlooking support that's already present. I know there is the `IIdentityServerInteractionService`, but that doesn't allow for this, AFAICT. A different way might be to use the callback URL when the user interaction starts to indicate failure. I didn't find any documentation about this, and checked the source, and looks like this is unsupported, atm.

### Context
We're building an app that requires authorization. It connects to our authentication API, that's built on top of IdentityServer. This delegates the actual logging in to a small set of 3rd party identity providers. We have some specific scenarios when the account cannot be used, and we need to fail the auth flow. In that case, we don't want to show a failure page, but return the auth flow back to the app, and show an error message there, and allow the user to fix it according to our instructions.

Maybe, we're abusing IdentityServer, and this really shouldn't be the way that you do a scenario like this. Please let me know if that's the case.

**Comment by brockallen** [comment]
DenyAuthorizationAsync: https://identityserver4.readthedocs.io/en/latest/reference/interactionservice.html#iidentityserverinteractionservice-apis

**Comment by tiesmaster** [comment]
Very nice! Thank you for the swift reply. I know I didn't see that when investigating that a few weeks ago, and [I see](https://github.com/IdentityServer/IdentityServer4/issues/4592#issuecomment-652513498) now that it was just added in v4. We're still on v3, so makes sense then :)

We'll upgrade to v4, and post any lessons learned in the pinned issue #4592. Thanks for that!
