### ISSUE TITLE
Retrieve the Client for a connected user

### ISSUE THREAD

**Issue by YZahringer** [IdentityServer/IdentityServer4#488]
I use the Hybrid flow to connect to my Identity Server. In this server I also have WebAPI methods.

Is it possible to retrieve the client used by the logged user? For example, I would like to add the name of the client in the logs for each request to my API.

I have to store it in user claims? Or is there a method to recover the client from HttpContext.User?

**Comment by Lutando** [comment]
You answered the question yourself. It is stored in user claims. You can get the HttpContext elsewhere in your code (ie not in the Controller context) by injecting the `IHttpContextAccessor` into your logger or whatever. HTH

**Comment by YZahringer** [comment]
Thank you for the answer. The Policy work with a single scope, not with several.

There is a different behavior if there are one or more claim scopes. With a single scope, the value of the claim is the name of scope, but with several scopes, the value is stored as JSON Array. The problem is that policy does not work with JSON Array in value claim:
```cs
services.AddAuthorization(options =>
{
    options.AddPolicy("RequireMyScopeName", builder => builder.RequireClaim("scope", "myScopeName"));
});
```

The problem does not occur if I store the scopes in claims with a name other than "scope".

**Comment by leastprivilege** [comment]
There's a bug in the OIDC middleware 1.0, where claims with the same type get de-serialized as a comma separared list. I think that's what you are hitting.

This should be fixed in 1.1

**Comment by YZahringer** [comment]
Thanks, compatibility with version 1.1 is planned for RC4?

**Comment by leastprivilege** [comment]
This is happening in your client application - not in identity server. So this is unrelated to us

**Comment by leastprivilege** [comment]
IdentityServer itself will not move to 1.1 soon.
