### ISSUE TITLE
Samples rely on an uncompatible package Serilog.AspNetCore

### ISSUE THREAD

**Issue by Banyc** [IdentityServer/IdentityServer4#4884]
**We can only help you if you are on the latest version. Either use the latest 2.x or 3.x**

### Issue / Steps to reproduce the problem

Run:

```
dotnet add package Serilog.AspNetCore
```

... on a .NET Core 3.1 project

### Relevant parts of the log file

```
error: Package Microsoft.Extensions.Options.ConfigurationExtensions 2.0.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.Extensions.Options.ConfigurationExtensions 2.0.0 does not support any target frameworks.   
error: Package 'Serilog.AspNetCore' is incompatible with 'all' frameworks in project ...
```

**Comment by leastprivilege** [comment]
can't repro. This is working for us (and many others) for a long time...

**Comment by Banyc** [comment]
> can't repro. This is working for us (and many others) for a long time...

https://github.com/serilog/serilog-sinks-seq/issues/129#issuecomment-567246105

**Comment by Banyc** [comment]
What if I have only one computer. Is that means I am disqualified from the use of IdentityServer4?

**Comment by leastprivilege** [comment]
Well - the package is not mandatory. Feel free to remove it and use the plain ASP.NET Core logging.

**Comment by Banyc** [comment]
> Well - the package is not mandatory. Feel free to remove it and use the plain ASP.NET Core logging.

It might be better to have a parallel version of samples/templates that include as little third-party packages as possible.
