### ISSUE TITLE
IOptionsMonitorCache<IdentityServerAuthenticationOptions> clear function does not update IdentityServerAuthenticationOptions

### ISSUE THREAD

**Issue by rwalusb3** [IdentityServer/IdentityServer4#4885]
Trying to update IdentityServerAuthenticationOptions, particularly the Authority URL in an api.

Solution, is to use the IOptionsMonitorCache<IdentityServerAuthenticationOptions> to clear the cache, and retrigger the .AddIdentityServerAuthentication extension method in ConfigureServices in Startup.cs in the API project. This method works and retriggers the call to the .AddIdentityServerAuthentication extension; however, a change is not reflected in the UI browser. 

1. Create a Test API, UI and IdentityServer
2. In Test API Startup.cs use .AddIdentityServerAuthentication with Authority using configuration (such as from appsettings.json)
ex: .AddIdentityServerAuthentication(options =>
                {
                    options.Authority = Configuration.GetSection("IdentityServer:Authority").Value;
                    ...
                }
3. Add a change token to the Configure method in the Test API startup.cs 
ChangeToken.OnChange(
                () => Configuration.GetReloadToken(),
                (state) => InvokeChanged(state), optionsMonitorCache);
Where InvokeChanged method is defined as:
        private void InvokeChanged(IOptionsMonitorCache<IdentityServerAuthenticationOptions> optionsMonitorCache)
        {
            optionsMonitorCache.Clear();
        }
4. Start the UI and connect to the identity server
5. Update the Authority value in appsettings.json file (or whatever used for configuration)
6. If breakpoints set, you can see the .AddIdentityServerAuthentication is re-triggered after optionsMonitorCache.Clear() is called.
 
Seems that this behavior is likely happening because the IdentityServerAuthenticationOptions are being directly added to ConfigureInternalOptions instead of using the IOptionsMonitor.

**Comment by leastprivilege** [comment]
> Seems that this behavior is likely happening because the IdentityServerAuthenticationOptions are being directly added to ConfigureInternalOptions instead of using the IOptionsMonitor.

That is correct. We currently don't have plans to change this.

**Comment by leastprivilege** [comment]
> Trying to update IdentityServerAuthenticationOptions, particularly the Authority URL in an api.

Could you explain what you are trying to achieve?

**Comment by rwalusb3** [comment]
I want to be able to update the Authority URL within the IdentityServerAuthenticationOptions in my API at runtime. My Security Service can change, so trying to be able to update my API to use my new Security Service (and update the IdentityServerAuthenticationOptions to reflect the new Security) without having to restart the API.

**Comment by rwalusb3** [comment]
> > Trying to update IdentityServerAuthenticationOptions, particularly the Authority URL in an api.
> 
> Could you explain what you are trying to achieve?

I want to be able to update the Authority URL within the IdentityServerAuthenticationOptions in my API at runtime. My Security Service can change, so trying to be able to update my API to use my new Security Service (and update the IdentityServerAuthenticationOptions to reflect the new Security) without having to restart the API.

**Comment by leastprivilege** [comment]
Oh now I see - you are talking about the authentication handler? That's strictly speaking the wrong repo.

Also we discontinued that handler in favour of a more flexible approach (that probably also does what you want):
https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/

That being said - changing the authority at runtime sounds troublesome.
