### ISSUE TITLE
How to set my own expiration

### ISSUE THREAD

**Issue by brianpooe** [IdentityServer/IdentityServer4#4887]
I have been googling for 2days now and all answers never seem to work, is there any straight forward way to set my own expiration session or token, all I want to do is redirect the user to log in again on Identity Server after a specific time for instance maybe after 20minutes.

A number of ways I have tried googling around:

1.
```c#
 app.UseCookieAuthentication(new CookieAuthenticationOptions
        {
            AuthenticationScheme = "Cookies",
            SlidingExpiration = true,
            ExpireTimeSpan = System.TimeSpan.FromSeconds(1.0)
        });
```

2.
```c#
.AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
{
  // ..
  options.Events.OnTicketReceived = async (context) =>
  {
    context.Properties.ExpiresUtc = DateTime.UtcNow.AddHours(1);
  };
  // ..
}
```

3.
```c#
services
   .AddIdentityServer(options =>
   {
      options.Authentication.CookieLifetime = TimeSpan.FromDays(30);
   })
```

4.
```c#
// AccountController.cs - Login()
await HttpContext.SignInAsync(isuser, new AuthenticationProperties
   {
       IsPersistent = true,
       ExpiresUtc = DateTimeOffset.UtcNow.Add(TimeSpan.FromDays(30))
    });
```

But none of the above work. Could someone please point me in the right direction and I have seen a lot of people struggle with this so perhaps this needs to be documented. Thanks in advance.

**Comment by alexcmoss** [comment]
I've just run into this problem. I believe it used to work as our solution was teste din the past with a custom sliding expiry.

**Comment by brianpooe** [comment]
There are so many issues related to this on github that has been closed with no solution.

**Comment by alexcmoss** [comment]
Given your examples above, this may not be helpful, but I've got things working by combining 3 and 4. The documentation is unclear:

"[This is separate from the value of , which specifies how long the browser will keep the cookie.](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.cookieauthenticationoptions.expiretimespan?view=aspnetcore-3.1#Microsoft_AspNetCore_Authentication_Cookies_CookieAuthenticationOptions_ExpireTimeSpan)"

" , "!

**Comment by mirnoca** [comment]
Take a look in your client configuration in IS4. There is a field where you can setup the lifetime of your AccessToken. The field is called AccessTokenLifetime. When you don't use the refresh token mechanism, your access token will live (per default) 1 hour. What kind of client are you using? Is it a javascript or net app? Depending on that you need to make some adjustments. See http://docs.identityserver.io/en/dev/topics/signout.html

**Comment by alexcmoss** [comment]
It seems I misunderstood the original question. My answers refer to setting the expiration of the Identity Server authentication session i.e. how long idsvr cookie and auth ticket last.

@mirnoca is correct. For the client session this depends on what sort of grant type you're using.

**Comment by brianpooe** [comment]
@mirnoca not sure I follow what adjustments you referring to. The link you sent is about signing out.

I'm using the .net core MVC app. With grant type code.

@alexcmoss the combination you mentioned is what most blogs and StackOverflow answers suggest but with no luck, it has never worked for me. Even though the cookie seems expired if I do a refresh I am still not redirected to login.

**Comment by mirnoca** [comment]
@alexcmoss  I misunderstood the problem. I tried picture 4 and set ExpiresUtc  = 5 minutes. I see in the developer tools that the cookie "idsrv"  expires in 5 minutes. But the other cookies don't have any expire time.

**Comment by mirnoca** [comment]
This combination works for me. I used the "samples\Quickstarts\5_EntityFramework" project in IdentityServer repository.
Startup.cs  Client
![2020-09-23_01h14_10](https://user-images.githubusercontent.com/41487395/93946761-686b1480-fd3a-11ea-9825-a66b8a69c35d.png)

Startup.cs  IdentityServer
![2020-09-23_01h14_59](https://user-images.githubusercontent.com/41487395/93946801-86387980-fd3a-11ea-9f46-fe65513cbefe.png)

**Comment by brianpooe** [comment]
@mirnoca i will try your combo and get back to you. Thanks.
