### ISSUE TITLE
JWT access token is too large.

### ISSUE THREAD

**Issue by zivfuture** [IdentityServer/IdentityServer4#4888]
Too many scopes in access token .  so it has a large size.   how to avoid this?  

Anathor question is how to remove some values from header or payload?:
```
{
 alg: "RS256",
 kid: "AB91EBBDAEA44D424B7B28ACFF8696B9454788E0RS256",    //how to remove this from access token?
 typ: "jwt",
 x5t: "q5Hrva6kTUJLeyis_4aWuUVHiOA"       //how to remove this from access token?
}.
{
 nbf: 1600255927,  //how to remove this from access token?
 exp: 1600259527,
 iss: "http://localhost:5000",
 sub: "1",
 auth_time: 1600255920,  //how to remove this from access token?
 idp: "local",
 jti: "90D973B10217E797E49317D7F4D6AEB3",  //how to remove this from access token?
 iat: 1600255927,   //how to remove this from access token?
 scope: [
  "Member",
  "Configuration",
  "openid",
  "offline_access"
 ],
 amr: [
  "password"
 ]
}.
[signature]
```

**Comment by mirnoca** [comment]
Why is the size of the JWT for you a problem? You should better read what a jwt is -> https://medium.com/@sureshdsk/how-json-web-token-jwt-authentication-works-585c4f076033 
The anwer should solve itself.

**Comment by zivfuture** [comment]
@mirnoca   thanks for reply,   Something wrong with the url?  I can't  access it.

**Comment by zivfuture** [comment]
@mirnoca   thanks for reply .
I had read this.   I just want to remove unimportant stuff from the header( "kid", "x5t" .. ) or payload ("nbf","jti" ....).  I don't need these items.

**Comment by mirnoca** [comment]
It is not possible to customize a JWT in IS4 and except scopes and claims.

**Comment by zivfuture** [comment]
@mirnoca   got it.  thanks!

**Comment by leastprivilege** [comment]
This is not correct. You have full control over the JWT in the token creation service. But most of them claims you find "unimportant" are relevant to the protocol and validation procedures.
