### ISSUE TITLE
Get claims in WebApi using HybridAndClientCredentials

### ISSUE THREAD

**Issue by mitchellmaler** [IdentityServer/IdentityServer4#489]
Hello, 

I have gone through all the quick starts and have started building out an application with a WebApi backend and IdentityServer4 separate servers. The authentication is working as expected but in the claims on the WebApi side I only am getting the sub. I have added ScopeClaims to my WebApi scope and now at a loss to how I request those on the WebApi side. This would help me know more information about the user without having to do extra db lookups. I am using UseIdentityServerAuthentication in my WebApi. 

Thanks,
Mitchell Maler

**Comment by leastprivilege** [comment]
Claims for tokens are returned from your profile service. That's where I would put a breakpoint to check what is actually returned.

**Comment by JonasAxelsson** [comment]
I don't know but are you sure that your web api client is required to use the HybridAndClientCredentials flow in order to fetch extra claims via the concrete class implementing IProfileService?

**Comment by leastprivilege** [comment]
I don't follow.

The OP indicates he is missing claims - claims are compiled at token creation time by the profile service. To know what's going on - that's the code to inspect.

**Comment by mitchellmaler** [comment]
Thanks for that tip. I should have time this week to step through that code.

**Comment by mitchellmaler** [comment]
Hey guys. I was able to implement IProfileService and use it to add my custom claims to the access token. Thanks for pointing me that direction.
