### ISSUE TITLE
How to use login page hosted in .Net framework 4.6 application to authenticate for IdentityServer4 application on .Net Core 3.1?

### ISSUE THREAD

**Issue by EugeneMetlitski** [IdentityServer/IdentityServer4#4891]
We have a current login page on a .Net framework 4.6 application.
We are building a new .Net Core 3.1 IdentityServer4 application primarily for issuing tokens, but during the code authentication flow we want to redirect to a login page which is hosted in our current .Net framework 4.6 application.

The redirect for login page from IDServer app to .Net framework 4.6 app works fine, but after the .Net framework 4.6 app creates and sets the cookie, IdentityServer4 doesn't seem to be responding to this cookie.

Does anyone know how to achieve logging-in in the .Net framework 4.6 application and then redirecting back to IdentityServer and handling the tokens after the login?

In IdentityServer, the following code makes it possible to redirect to .Net framework 4.6 application:
```C#
services.AddIdentityServer(options =>
                {
                    options.UserInteraction.LoginUrl = "https://localhost:44352/login/";
                    options.UserInteraction.LoginReturnUrlParameter = "returnUrl";
                })
```

But after the app running on "https://localhost:44352/login/" sets the identity cookie and redirects back to IdentityServer4 with the provided returnUrl, the IdentityServer4 is not reading that cookie.
We've even tried to create the Identity cookie using another .Net Core 3.1 application using Microsoft's Identity package, which works when doing it in IdentityServer4, but it doesn't work when creating this cookie in another application and passing it to IdentityServer4.

**Comment by mirnoca** [comment]
What is IS4 saying in the log after the .Net framework 4.6 app creates and sets the cookie?

**Comment by EugeneMetlitski** [comment]
> What is IS4 saying in the log after the .Net framework 4.6 app creates and sets the cookie?

I created an auth cookie in another .NetCore 3.1 application using Microsoft's Identity library using this function:
```c#
await HttpContext.SignInAsync(isuser, props);
```
When creating cookie inside IDS4 application then the code flow works and user is logged in, but when creating the cookie in another application, then IDS4 thinks that user did not log in, and it takes user to the login page.
It looks like the same cookie is created with the same name, but for some reason IDS4 doesn't accept this cookie if it wasn't created from within IDS4 app.
I was wondering how to make IDS4 accept the cookie?
