### ISSUE TITLE
PublicOrigin

### ISSUE THREAD

**Issue by radek673** [IdentityServer/IdentityServer4#4894]
To be honest, removing PublicOrigin was a mistake. Its not only host, but also protocol. When you are using IdentityServer behind proxy with https=>http, tokens stop working because http(s) difference.
You are not even using x-forwarded-proto, just request.Scheme+request.Host...
What should we do in our case as consequence of this removal ?

**Comment by brockallen** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/4857#issuecomment-689719505
