### ISSUE TITLE
"client_credentials" add single custom claim without prefix

### ISSUE THREAD

**Issue by pfaustinopt** [IdentityServer/IdentityServer4#4895]
Hello,

I'm trying to achieve the following: 

- I want to add a custom claim to identify the device that is asking for the token (I pass this information on the body of the request that is sent to /connect/token), which will be accessed later on my web API for logging purposes

I've already implemented the following:

- My own implementation of IResourceOwnerPasswordValidator that reads the device id from the request raw and adds it as a claim
- My own implementation of IExtensionGrantValidator to support delegation, in which I add the claims that are associated with the token that I pass

Both these implementations create a claim with the name "device_id".

I've attempted to implement my own I ICustomTokenRequestValidator in order to add this claim when using  "client_credentials" but I've noticed that the claim gets the name "client_device_id". Since I want to access this claim on the web API for logging purpose, I want its name to always be "device_id". I understand that I can set the client prefix to empty, but is there any way to keep the rest of the client claims with this prefix while adding this claim at runtime without it? This claim, in particular, is not associated with any specific client, it is supposed to be something similar to the JWT registered names. 

Best regards

**Comment by leastprivilege** [comment]
There's a prefix setting on the client registration. Make it an empty string.

**Comment by pfaustinopt** [comment]
I've ended up removing the client prefix.
