### ISSUE TITLE
How to configure WS-Fed IdentityProviders in IS4

### ISSUE THREAD

**Issue by charettedavid** [IdentityServer/IdentityServer4#49]
Hi, i'm trying to configure V4 based on my V3 configuration, first thing i get my hands on is the "ConfigureIdentityProviders" trying to add my ADFS via UseWsFederationAuthentication.

Is this implemeted yet? Is there a sample or doc i can refer to?

Thank you

**Comment by leastprivilege** [comment]
ASP.NET Core has no support for WS-Fed.
