### ISSUE TITLE
c_hash and at_hash for hybrid flow

### ISSUE THREAD

**Issue by Lutando** [IdentityServer/IdentityServer4#490]
I am under the impression that when you use AuthorizationCode/Hybrid flow that the token response for the id_token would include at_hash and the c_hash if the response_type [is code and id_token (or code, id_token and token)](http://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken)

my request url looks something like this (url decoded for readability)

Request starting HTTP/1.1 GET http://myidentity.com/login?returnUrl=/connect/authorize/login?client_id=myhybridappi&redirect_uri=app%3A%2F%2Fmyhybridapp%2Fend&response_type=code%20id_token&scope=openid%20profile%20offline_access%20collector%3Atracks%3Awrite&state=example2096806332&nonce=3348204092021932443&access_type=offline

does anything pop out as glaringly wrong here? The  id_tokens returned do not include either of these

**Comment by leastprivilege** [comment]
Are you talking about the id_token being returned from the authorize endpoint? It should contain the hashes.

**Comment by Lutando** [comment]
Yes sorry I was misunderstanding the use of c_hash and at_hash initially. 

As I understand it if you call the authorize endpoint with a `code` then you will get a `c_hash`, similarly calling the authorize endpoint with an `access_token` will give you an `at_hash`, in both cases allowing you to verify the linking between the `code` <-> `c_hash` (within the id_token) or `access_token` <-> `at_hash` (again within the id_token)

Does this sound about right?

**Comment by leastprivilege** [comment]
Yes






On Wed, Nov 23, 2016 at 9:30 AM +0100, "Lutando Ngqakaza" <notifications@github.com> wrote:












Yes sorry I was misunderstanding the use of c_hash and at_hash initially.


As I understand it if you call the authorize endpoint with a code then you will get a c_hash, similarly calling the authorize endpoint with an access_token will give you an at_hash, in both cases allowing you to verify the linking between the code <-> c_hash (within the id_token) or access_token <-> at_hash (again within the id_token)


Does this sound about right?

**Comment by Lutando** [comment]
Thanks
