### ISSUE TITLE
ASP.NET Identity implementation of IResourceOwnerPasswordValidator not returning error description

### ISSUE THREAD

**Issue by ajphall** [IdentityServer/IdentityServer4#4906]
We are using Identity Server 4.1 with ASP.NET Core Identity.  For one of our applications we are using the ResourceOwnerPasswordAndClientCredentials.  We have noticed that if a login fails, Identity Server is always returning "invalid_username_or_password", even if there is another reason for the failure (e.g. the user is locked out)

Looking in the code, it seems this is the default response from the `IdentityServer4.Validation.TokenRequestValidator` if the provided implementation of `IResourceOwnerPasswordValidator.ValidateAsync` does not provide a description in the `ValidationResult`.

Looking in the `IdentityServer4.AspNetIdentity.ResourceOwnerPasswordValidator` if the user authentication fails no extra information (i.e. a description) is added to the `GrantValidationResult`, even though the reason for the failure is logged.

I have listed this as a bug, but it could be that this is intentional to not provide additional information to a client?  If this is not intentional would you be willing to accept a PR where we add a description to the returned `GrantValidationResult` in the event user authentication failed that matches what is logged (e.g. "locked out", "now allowed" or "invalid credentials")?

Thanks.

**Comment by leastprivilege** [comment]
That's intentional to not leak information to potential attackers.

**Comment by ajphall** [comment]
Makes sense.  Thanks.
