### ISSUE TITLE
AddIdentityServerBuilder() Does not resolve dependencies correctly on a Mac

### ISSUE THREAD

**Issue by Eebo78** [IdentityServer/IdentityServer4#4907]
**We can only help you if you are on the latest version. Either use the latest 3.x or 4.x**

Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](http://docs.identityserver.io/en/latest/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem
Use the services.AddIdentityServerBuilder() in startup and run command: dotnet run and you get a exception.

Works fine on windows and using the .AddIdentityServer() instead solves the issue
### Relevant parts of the log file

```
Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: IdentityServer4.Stores.IDeviceFlowStore Lifetime: Transient ImplementationType: IdentityServer4.EntityFramework.Stores.DeviceFlowStore': Unable to resolve service for type 'IdentityServer4.Stores.Serialization.IPersistentGrantSerializer' while attempting to activate 'IdentityServer4.EntityFramework.Stores.DeviceFlowStore'.) (Error while validating the service descriptor 'ServiceType: IdentityServer4.Stores.IClientStore Lifetime: Transient ImplementationType: IdentityServer4.Stores.ValidatingClientStore`1[IdentityServer4.EntityFramework.Stores.ClientStore]': Unable to resolve service for type 'IdentityServer4.Validation.IClientConfigurationValidator' while attempting to activate 'IdentityServer4.Stores.ValidatingClientStore`1[IdentityServer4.EntityFramework.Stores.ClientStore]'.)
```

**Comment by leastprivilege** [comment]
Please use `.AddIdentityServer` to get a default set of services.

**Comment by Eebo78** [comment]
@leastprivilege That's how we solved it. Wouldn't you say that since it works on Windows environment and not Mac that this is a bug? Or is the `.AddIndentityServerBuilder()` method obsolete?

**Comment by leastprivilege** [comment]
They behave the same on both operating systems.

**Comment by Eebo78** [comment]
Strange that we see different behaviour then. I were able to run the server on windows using `.AddIdentityServerBuilder()` without getting the exception, but as soon as our developer running on a Mac he got the exception mention above? I would expect same error on both environment?
