### ISSUE TITLE
431- Request Header Fields Too Large  - External CallBack from Azure AD

### ISSUE THREAD

**Issue by himalpatel81** [IdentityServer/IdentityServer4#4908]
### Question
We've configured Azure AD authentication with Identity Server and it works fine for all user except one user. For one user, the call back request is failiing with the error 431-Request Header Fields Too Large. We chekced the cookie and the cookie is idserver.external. 

Based on the documentation Identity Server is using this cookie as temporary cookie to store the User claims received from external provider. Azure AD in this ase. 

So the question is

1. Is there any way to handle this situation in Identity Server ?
2. What should we check on the Azure Ad side for this user ?

Thanks!

**Comment by brockallen** [comment]
This is not an IdentityServer issue -- it sounds more like a general issue with ASP.NET Core and handling responses from AAD. To get it working, I'd suggest setting up a stand alone app to integrate w/ AAD and get that working first. Then apply that to your IdentityServer project.

**Comment by himalpatel81** [comment]
If there is any issue with the integration then it won't work for other users in AD. This is happending only with a specific user in Azure AD. All other users are working just fine. 

It is the issue with the way Identity Server uses cookie to temporarily store the claims from external provider. Got the below article and the solution provided there may fix the issue. 

https://www.daimto.com/headersize-issue-with-identityserver4/

Will close the ticket once I verify the work around given in above link.

**Comment by himalpatel81** [comment]
Solution provided in the link above worked. Closing the ticket.
