### ISSUE TITLE
redirect_uri is missing or too long

### ISSUE THREAD

**Issue by TechLiam** [IdentityServer/IdentityServer4#4909]
### Issue / Steps to reproduce the problem
So the issue I'm having is that the redirect_uri is not being parsed from the query string or atleast that what it looks like from our logs.
The incoming request looks like this:
```
Request starting HTTP/1.1 GET 
http://login.{idpHost}.com/te/{tenant}.{applicationHost}.com/Account/Login?ReturnUrl=/te/{tenant}.{applicationHost}.com/connect/authorize/callback?client_id={clientId}&response_type=code%20id_token&scope=openid%20profile%20email%20offline_access%20{applicationApiScope}&state=OpenIdConnect.AuthenticationProperties=T75kZZojYYxsSrh860xctPAfezsgYMKIhxetDwtVTP7x4flcE0I4ozViZDIqGtVNfTPXX4qf9Nj-tPu0_K9YadWOfZwgJCNX41xYmprc87-v19VDsVxtgr19j_rKe1DdhiSeAqMWC5NoLc6TEmM8cOzIRsI&response_mode=form_post&nonce=637364662424541053.NWQyNzM1ODYtMzA0OS00YTdmLWIwYWItYTViZmJjMjMxNjExNmM5NDM0OTYtOTEyYy00MGE3LThiYTUtOWM3MzIxYmY2Yzg4&redirect_uri=https://{tenant}.{applicationHost}.com/{path}/signin-oidc&post_logout_redirect_uri=https://{tenant}.{applicationHost}.com/{path}/Admin/Index&acr_values=%20use_local_login:true&x-client-SKU=ID_NET461&x-client-ver=5.6.0.0
```

But when it gets to the validation part of the process we get the log:
"redirect_uri is missing or too long"
The request object that is logged with this looks like this:
``` json
{
    "ClientId": "{clientId}", 
    "ClientName": "{ClientName}", 
    "RedirectUri": null, 
    "AllowedRedirectUris": [
    "http://{tenant}.{applicationHost}.com/{path}/signin-oidc", 
    "https://{tenant}.{applicationHost}.com/{path}/signin-oidc"], 
    "SubjectId": "anonymous", 
    "ResponseType": null, 
    "ResponseMode": null, 
    "GrantType": null, 
    "RequestedScopes": "", 
    "State": null, 
    "UiLocales": null, 
    "Nonce": null, 
    "AuthenticationContextReferenceClasses": null, 
    "DisplayMode": null, 
    "PromptMode": null, 
    "MaxAge": null, 
    "LoginHint": null, 
    "SessionId": null, 
    "Raw": {
        "client_id": "{clientId}"
    }, 
    "_typeTag": "AuthorizeRequestValidationLog"
}
```

As can be seen here the redirect URI has not been mapped over from the request query string.
I have no idea why this might be please help?

**Comment by leastprivilege** [comment]
You can set the max length for URIs on the options.

**Comment by TechLiam** [comment]
Is the max length default small?
I will try this?

**Comment by leastprivilege** [comment]
Don't know. Never seen that before.

**Comment by TechLiam** [comment]
Closing this as the fix suggested worked really well thank you for the as always wonderful help.
For anyone else reading this that may have the same issue I set the option to be 5000 a nice big number.

**Comment by TechLiam** [comment]
I'm having to reopen this as the issue has persisted it seams to be speradic now in nature but the same logs as before apply. There doesn't seam to be any specific correlation with the falure and anything in the request.
Please let me know if you need any more detail from me for this is becoming a critical issue for my team and I.
Any assistance would be grate like i noted in my previouse closing comment I have applyed the option and set the value to a 5000.

**Comment by leastprivilege** [comment]
If you need someone to look into it, consider getting commercial support:
https://identityserver4.readthedocs.io/en/latest/intro/support.html#commercial-support
