### ISSUE TITLE
Remove InMemory cache

### ISSUE THREAD

**Issue by mbauerdick** [IdentityServer/IdentityServer4#491]
Hi,

is it possible to remove the line:

[IdentityServerServiceCollectionExtensions.cs](https://github.com/IdentityServer/IdentityServer4/blob/f964184bbe7ea45d4cc2369516b14a509a3531a5/src/IdentityServer4/Configuration/DependencyInjection/IdentityServerServiceCollectionExtensions.cs)
`// provide default in-memory implementation, not suitable for most production scenarios
            builder.AddInMemoryPersistedGrants();`

from your DI extension? One have to re-write the extension if you do not want to use the in memory service of it.

**Comment by leastprivilege** [comment]
Why?

You can simply overwrite with your own implementation. Last one wins in ASP.NET Core DI.

**Comment by mbauerdick** [comment]
Hi, 

i know you can just overwrite the default implementation.
I just don't get why you implemented the grant store only. 
I can remember when you had an extensions like "AddDeveloperIdentityServer" with all in-memory stores already set up while the default "AddIdentityServer" was just a basic configuring.

Anyway, i go with IdentityServerBuilder for full flexibility.

Thanks
Martin

**Comment by leastprivilege** [comment]
And why do you need that flexibility?

What's wrong with overwriting the default implementation?

**Comment by mbauerdick** [comment]
Hi,

there is absolutly nothing wrong with the default implementation.
I just wonder why you inserted the in-memory grant store in your default AddIdentityServer extension in exception of the other in-memory stores (rc-3).

Long story short: you admit to overwrite the IPersistendGrantStore or the ICache in general.
For my project i had to do both because we're in a clustered environment with RedisCache and ServiceRelays.

**Comment by leastprivilege** [comment]
Because the in-mem one is useful for dev and testing - and there are even some situations where you don't need a grant store at all.
