### ISSUE TITLE
What are ApiScopeProperty used for ?

### ISSUE THREAD

**Issue by Vandersteen** [IdentityServer/IdentityServer4#4911]
Hello all,

I've been looking around and I can't find any information around [ApiScopeProperty](https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/EntityFramework.Storage/src/Entities/ApiScope.cs#L21)'
These can be found in EntityFrameWork entities and they are mapped to a [KeyValuePair](https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/EntityFramework.Storage/src/Mappers/ScopeMapperProfile.cs#L21)

What are these used for ?
These properties also appear to be used on ApiResource, Client, IdentityResource.

Is there any information available around these ?

**Comment by brockallen** [comment]
It allows you to put any extra data you need for the resource.

**Comment by vivekgowdatv111** [comment]
> It allows you to put any extra data you need for the resource.

What is use of being use of adding extra data to resource , Please explain in details
