### ISSUE TITLE
Refresh token: expire after a certain interval?

### ISSUE THREAD

**Issue by jez9999** [IdentityServer/IdentityServer4#4913]
We're currently using refresh tokens with the following setup:

```
    // Allow use of sliding refresh token, which changes handle every refresh request
    AllowOfflineAccess = true, // Client requests scope 'offline_access' to be issued a refresh token
    AccessTokenLifetime = 3600, // 1 hour
    AbsoluteRefreshTokenLifetime = 0,
    SlidingRefreshTokenLifetime = 1296000, // 15 days
    RefreshTokenExpiration = TokenExpiration.Sliding,
    RefreshTokenUsage = TokenUsage.OneTimeOnly,
    UpdateAccessTokenClaimsOnRefresh = true
```

We want to keep using the sliding token expiration, but we want to allow for the client making several quick requests in succession with the same refresh token by having it expire after, say, 1 hour instead of immediately.  My understanding is that if we change `RefreshTokenUsage` to `TokenUsage.ReUse`, the refresh token won't expire at all, but `OneTimeOnly` makes it expire immediately.  Is there a way we can achieve this "expire after x interval" behaviour?

**Comment by brockallen** [comment]
https://leastprivilege.com/2020/06/29/refresh-tokens-in-identityserver4-v4/

**Comment by jez9999** [comment]
@brockallen Was the "mark a refresh token as consumed rather than delete it from the DB" behaviour implemented in version 4.0.1 or something?  On the version 3.x we're using, it actually is deleting it.

**Comment by leastprivilege** [comment]
yes. Starting with v4

**Comment by jez9999** [comment]
@leastprivilege Is there any guide for migrating from identityserver 3.x to 4.x?

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/4592
