### ISSUE TITLE
Audience validation failed: 'empty' after 4.x upgrade

### ISSUE THREAD

**Issue by i8beef** [IdentityServer/IdentityServer4#4914]
I am attempting to upgrade to 4.x and I appear to be unable to convert to the "simple" Scope-only setup. My token audience appears to be "[]", but its failing on usage with the following:

```
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'empty'. Did not match: validationParameters.ValidAudience: 'REDACTED' or validationParameters.ValidAudiences: 'null'.
```

I changed the config to remove the AddInMemoryApiResources as specified in your migration documentation and gone to a simplified scopes setup.

```
            var identityServerBuilder = services
                .AddIdentityServer(options =>
                {
                    options.IssuerUri = authority;
                })
                .AddInMemoryClients(Clients.Get(Configuration))
                .AddInMemoryIdentityResources(Resources.GetIdentityResources())
                .AddInMemoryApiScopes(Resources.GetApiScopes())
                .AddTestUsers(Users.Get(Configuration));
```

I also changed the setup for the following for the ApiName to match my api's scope name.

```
                services.AddIdentityServerAuthentication(IdentityServerAuthenticationDefaults.AuthenticationScheme, options =>
                {
                    options.Authority = authority;
                    options.ApiName = "myScope";
                });
```

What am I missing? Does the simplified path have issues, and I should just add the wrapping Resources back?

**Comment by i8beef** [comment]
Note, I found a blog entry (https://nahidfa.com/posts/migrating-identityserver4-to-v4/) that mentions in passing at the end:

> Option 2 is the only solution if you are using IdentityServer authentication handler on API. On authentication handler, the ApiName property checks if the token has a matching audience. Read more here

As I AM using that here, I assume that means I have no choice but to use the Resource wrapping still?

**Comment by i8beef** [comment]
For anyone that finds this later, I did indeed have to go back to full Resource definitions. It appears that the simple approach to scope definitions needs some work / other areas such as the IdentityServer authentication handler needs to made a ware of the approach.

**Comment by leastprivilege** [comment]
Here are the docs for resources - that should contain all information
https://identityserver4.readthedocs.io/en/latest/topics/resources.html

...and the authN handler is deprecated
https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/

**Comment by i8beef** [comment]
Ok, so after several hours perusing your documentation, examples, blog posts, etc., I am still not clear on what the replacement for AddIdentityServerAuthentication is exactly...

If I don't want to have to use Resources anymore I think I need to use this, but do I need to set any of the other TokenValidationParameters?

```
            services.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
                {
                    options.RequireHttpsMetadata = true;
                    options.Authority = "https://myauthority";
 
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateAudience = false
                    };
                });
```

**Comment by leastprivilege** [comment]
Exactly - you don't validate the audience at all - instead you write an authorization policy to check for the existence of the scope - e.g.

```
services.AddAuthorization(options => options.AddPolicy("myscope", policy => policy.RequireClaim("scope", "foo")));
```

and attach that policy either globally or to a controller. Check the asp.net core docs.
