### ISSUE TITLE
how can I config authority with subdomains

### ISSUE THREAD

**Issue by seven1986** [IdentityServer/IdentityServer4#4915]
My IdentityServer and ApiResource  in the same project, and develop in sub domain like
- a.myids.com
- b.myids.com
- c.myids.com
- d.myids.com

I  have reference this code, but only can config one IdentityServer address, how can I change the Authority property dynamic, follow current requestContext Uri? 

``` csharp
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                // base-address of your identityserver
                options.Authority = "https://demo.identityserver.io";

                // if you are using API resources, you can specify the name here
                options.Audience = "resource1";

                // IdentityServer emits a typ header by default, recommended extra check
                options.TokenValidationParameters.ValidTypes = new[] { "at+jwt" };
            });
    }
}
```

**Comment by lyubomirr** [comment]
These options must have a TokenValidationParameters property of type TokenValidationParameters which has a property named IssuerValidator where you can put your own validation delegate. Also there is ValidIssuers property where you can a list of all valid issuers.
