### ISSUE TITLE
SecurityTokenSignatureKeyNotFoundException after rollover of signingcredential

### ISSUE THREAD

**Issue by santo2** [IdentityServer/IdentityServer4#4918]
Hi all, 

We just rolled over our signing credential, we accidentally skipped one part of rolling over. This is what we did.

We moved from this code:
```
identityServerBuilder.AddSigningCredential(certificate1);
```

to this code, without first making certificate 2 a validation key.
```
identityServerBuilder.AddSigningCredential(certificate2);
identityServerBuilder.AddValidationKey(certificate1);
```

Now we see that logging out with an old token (from before the code deploy) provided via external identity integration with Google, provides us issues. 
we see that the IdentityServerInteractionService, when requestiong the GetLogoutContext, is not providing us with the details that we expected, and therefore we can get the callback URL for our app back. 

Now we see the exception "SecurityTokenSignatureKeyNotFoundException" (IDX10501: Signature validation failed. Unable to match keys: kid: '[PII is hidden]', token: '[PII is hidden]'.)
.in our app insights logging popping up. shouldn't adding the old certificate as validation key prevent this exception? 

We've read up on the article of Brock Allen on the credential rollover, and we expected that the exceptions would stop after that 5 days passed, since he states that external identity providers possibly have 2-5 days of caching. 
those days passed, but we still are unable to log out properly using the logout flow for our mobile app.
Is this normal? Just because we forgot one step in the flow?

Extra context: 
our mobile app is using OIDCClient, which provides a logoutId on logging out. it redirects us to the browser on our mobile phone, and redirects us via the redirect URL that should come back via the interaction context. this is missing, therefore the flow of logging out on our app is broken for old tokens

**Comment by santo2** [comment]
Hi, you mean like I mentioned that we did? :) we added the first (old) certificate as a validation key.

**Comment by brockallen** [comment]
> Now we see that logging out with an old token (from before the code deploy) provided via external identity integration with Google, provides us issues.

Are you sending the google token to IdentityServer?

**Comment by santo2** [comment]
I'm asking the team that implemented it to give an answer to this question, so that I'm not giving any bad answers. Coming back to your question ASAP
