### ISSUE TITLE
Where is the latest source code for IdentityServer4.AccessTokenValidation?

### ISSUE THREAD

**Issue by DureSameen** [IdentityServer/IdentityServer4#4921]
I am upgrading the Identityserver to the latest version, my source code depend upon source code of IdentityServer4.AccessTokenValidation(3.0.1). Where can I find it?

**Comment by brockallen** [comment]
Here: https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation

But read: https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/
