### ISSUE TITLE
AuthorizationContext - context.IsNativeClient() does not exist

### ISSUE THREAD

**Issue by DanielTrefzer** [IdentityServer/IdentityServer4#4923]
Hi, 
regarding this example: 
https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/host/Quickstart/Account/ExternalController.cs

there should be a method for context.IsNativeClient()

Maybe a using is missing?

Regards

Daniel

**Comment by crazyfx1** [comment]
It's a custom method implemented in the sample:
https://github.com/IdentityServer/IdentityServer4/blob/c281dfcf6a9307ad1c0d3dd18562c4beabd8c46c/src/IdentityServer4/host/Quickstart/Extensions.cs#L13

**Comment by DanielTrefzer** [comment]
Thank you very much... I did not see this.
