### ISSUE TITLE
Claims not recognized in IdentityServer but in calling API

### ISSUE THREAD

**Issue by DanielTrefzer** [IdentityServer/IdentityServer4#4924]
Hi, 
we have the following setting:

- Authentication via Windows SSO
- Call from an external API works well and user and claims are correctly
- Open the MVC Page of IdentityServer does not work --> Claims are not loaded correctly 

Only difference in Debugging is in External Controller: 
(Example : https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/host/Quickstart/Account/ExternalController.cs) 

 // check if external login is in the context of an OIDC request
  var context = await _interaction.GetAuthorizationContextAsync(returnUrl);

The context ist null if I use the MVC Page directly and if the call is coming from an external party its not null.

Any ideas are welcome

Regards
Daniel

**Comment by DanielTrefzer** [comment]
Any ideas here?

**Comment by leastprivilege** [comment]
> The context ist null if I use the MVC Page directly and if the call is coming from an external party its not null.

All that `GetAuthorizationContextAsync` does it to parse the return URL you are passing in. Something must be different between the two situations.

**Comment by DanielTrefzer** [comment]
Ok, thanks for this clarification. 
This was the only difference that we were able to find. 

The only difference is the calling party --> An external API via OIDC where it works and the MVC Quickstart application where it does not work. 
It seams as if the MVC does not forget the Windows User / does not correctly load the user/claims despite the fact calling 


    await HttpContext.SignInAsync(isuser, localSignInProps);
      // delete temporary cookie used during external authentication
   await HttpContext.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
