### ISSUE TITLE
CSP violation

### ISSUE THREAD

**Issue by juanan** [IdentityServer/IdentityServer4#4925]
I have an SPA using oidc-client to connect to my Identity Server and when I'm redirected from the login page to the SPA I get this error

![image](https://user-images.githubusercontent.com/17723190/94551595-e2792d00-0255-11eb-885f-62ab5d7e8f9b.png)

What the checksession does?How can I avoid it so that my CSP is not violated?

Many thanks.

**Comment by juanan** [comment]
As I saw, the checksession endpoint returns an html with inline script code

![image](https://user-images.githubusercontent.com/17723190/94654684-b31dfb00-02fd-11eb-87c0-7ccf1e55b9cf.png)

Any ideas @brockallen ?

Many thanks.

**Comment by brockallen** [comment]
Yes, this did change in a recent release, but as you can see it's working for me:

![image](https://user-images.githubusercontent.com/649492/94960228-85cd7a80-04c0-11eb-951b-90f6ddddfed0.png)


I wonder if something is changing the payload, perhaps a load balancers?

**Comment by juanan** [comment]
Its working fine for you because you don't have any other CSP overriding yours, what is was my case. Seen that Identity Server has itw own CSP, I have only added my CSP in custom endpoints and everything ok.

Thanks a lot @brockallen .
