### ISSUE TITLE
Blazor To API not authenticating properly

### ISSUE THREAD

**Issue by chassq** [IdentityServer/IdentityServer4#4927]
We have attached a sample zip with our source to try and setup a very basic Blazor (wasm) Client -> API using Identity Server 4 v4. The logins seem to work fine. However when we attempt to make a call from the Blazor client to the API the authorization fails. If we remove the [authorize] attribute from the weather forecast controller the request goes through just fine so we think it has to do with the API request not receiving something it needs to authenticate the request? Nothing seems to show up in our logs.

Using:
IdentityServer4 v4.1.0
Dotnet Core 3.1.8
Serilog 3.4.0

[src.zip](https://github.com/IdentityServer/IdentityServer4/files/5299201/src.zip)

Any input is welcome.

Thanks!

**Comment by brockallen** [comment]
If you created that from the Microsoft template, then I'd suggest you contact them for support.
