### ISSUE TITLE
Razor Pages based Quickstart

### ISSUE THREAD

**Issue by AmarjeetBanwait** [IdentityServer/IdentityServer4#4928]
Add RazorPages based Quickstart

[RazorPages template by Martin Fletcher](https://github.com/IdentityServer4Contrib/IdentityServer4.Contrib.Templates.RazorPages) doesn't exist.

**Comment by leastprivilege** [comment]
We don't have plans to do this. Maybe someone in the community has done that - but I am not aware of it.

**Comment by AmarjeetBanwait** [comment]
I checked already, Only sample by Martin Fletcher is no longer existed. 
In Quickstart sample lots of other areas left in favor of Microsoft authentication eg change password, forgot password etc, It is also mentioned in Identityserver docs. But as now Microsoft moved to Razorpages and IdentityUI, I think IdentityServer should move to razorpages and make separate Ui library like IdentityUi eg IdentityServerUI.
