### ISSUE TITLE
Typo in DefaultClaimsService.cs

### ISSUE THREAD

**Issue by tndata** [IdentityServer/IdentityServer4#4929]
In the file 

IdentityServer4/src/IdentityServer4/src/Services/Default/DefaultClaimsService.cs

The XML documentation for the GetAccessTokenClaimsAsync method is wrong. Replace **Identity** with **access**.

        /// <summary>
        /// Returns claims for an **identity** token.
        /// </summary>
        /// <param name="subject">The subject.</param>
        /// <param name="resourceResult">The validated resource result</param>
        /// <param name="request">The raw request.</param>
        /// <returns>
        /// Claims for the access token
        /// </returns>
        public virtual async Task<IEnumerable<Claim>> GetAccessTokenClaimsAsync(ClaimsPrincipal subject, ResourceValidationResult resourceResult, ValidatedRequest request)
        {

**Comment by brockallen** [comment]
Fixed. I meant to do a PR, but I accidentally just did it directly on main.
