### ISSUE TITLE
Client session cookies are never cleared/removed

### ISSUE THREAD

**Issue by 1awst** [IdentityServer/IdentityServer4#493]
I've been encountering an issue with the size of requests to identity server which appear to be caused by the cookie created by the the client session service. Each time a users signs out of the application they're redirected to the end session endpoint (/connect/endsession) along with the 'post_logout_redirect_uri', 'id_token_hint' and 'state' query parameter values. At this point identity server creates a cookie (Client.Sessions.xxxxx=xxxx) with the 'sid' from the 'id_token_hint'. The cookies keep building up each time the user logs out but are never cleared/removed so the request size keeps growing over time.

Is this expected behaviour and/or is there something I can configure to clear them so the request size doesn't keep growing?

Thanks

**Comment by brockallen** [comment]
>  The cookies keep building up each time the user logs out but are never cleared/removed so the request size keeps growing over time.

These should be cleared when the iframe completes the request to the end session callback endpoint.

**Comment by JonasAxelsson** [comment]
For me SLO started working with RC3 of IDSvr4. Can you provide kestrel webserver logs from your clients and idsvr?

**Comment by brockallen** [comment]
Yes, there was a bug and some things just not implemented relating to SLO in the prior RCs.

**Comment by 1awst** [comment]
I was using RC3 when the problem occurred, however its magically started working without changing anything. I remember from looking at the traffic in fiddler it was redirecting back to the application immediately after hitting the end session endpoint. Now its going to the logged out page which has an iframe that invokes the end session callback and this removes the cookie.

Sorry I've no idea why it didn't work previously but its all ok now. Thanks for all the responses.
