### ISSUE TITLE
Authorization error response mismatch with OAuth specification?

### ISSUE THREAD

**Issue by JosephWoodward** [IdentityServer/IdentityServer4#4930]
Whilst building on top of IdentityServer 4 we noticed what we believe to be a mismatch between what IdentityServer 4 does and the OAuth specification, specifically around error responses and the recommended redirect URI on the authorization endpoint.

According to the [OAuth specification](https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-4.1.2.1) (in this case the new draft proposal, but it's the same in the older version) it says the following:

>If the resource owner denies the access request or **if the request
   fails for reasons other than a missing or invalid redirect URI, the
   authorization server informs the client by adding the following
   parameters to the query component of the redirect URI using the
   "application/x-www-form-urlencoded" format**, per Appendix B:

However it appears that IdentityServer 4 redirects ([see source here](https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/src/Endpoints/Results/AuthorizeResult.cs#L76-L81)) the client to IdentityServer's error page as opposed to the client's redirect URI.

Is this intentional or am I misunderstood/missing something?

**Comment by brockallen** [comment]
We implement these mitigations:
https://tools.ietf.org/html/draft-bradley-oauth-open-redirector

**Comment by JosephWoodward** [comment]
Great, thanks @brockallen, I had a suspicion I was missing something.
