### ISSUE TITLE
Load balancer environment - Idsrv.session cookie properties are changed to HTTPOnly.

### ISSUE THREAD

**Issue by ramkrivas** [IdentityServer/IdentityServer4#4933]
**We can only help you if you are on the latest version. Either use the latest 3.x or 4.x**

Please only use the issue tracker for bug reports and/or feature requests. For general security questions, or free or commercial support options do __not__ use the issue tracker and instead see [here](http://docs.identityserver.io/en/latest/intro/support.html) for more details.

For bug reports,  include the relevant log files related to your issue. See here how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html). Delete this line once you have.

Finally, please keep the issue concise and to the point. If you paste in more code than the text for the issue you are reporting then we will most likely not read it. 

### Issue / Steps to reproduce the problem
1. Provide Hostname of the webserver as the baseUrl to identity server => idsrv.session cookie is getting created as" **Non HTTPOnly**" cookie.

2. Provide a load balancer path instead of hostname for the webserver as baseUrl to identity server = > idsrv.session cookie getting created as "**HTTPOnly** " cookie.

Issue
We are using implicit/authorization code grant workflow. Hence our client JS would expect idsrv.session cookie to be readable through JavaScript to monitor session.  but in a load balancer environment the idsrv.session cookie is being returned as HTTPOnly cookie, hence our client codes could not read it and fails.

### Relevant parts of the log file

```
screenshot : **idsrv.session cookie property in Loadbalancer environment** 
![image](https://user-images.githubusercontent.com/71707/94781979-3a479d80-03e8-11eb-80fb-1414e8f2b2f1.png)

screenshot : *idsrv.session cookie property in normal environment** 
![image](https://user-images.githubusercontent.com/71707/94782971-a676d100-03e9-11eb-8ce7-3c2c04cbdafb.png)

<log goes here>
```

**Comment by leastprivilege** [comment]
I guess this is more of a question to whoever takes care of the load balancer. IdentityServer is always emitting this cookie as non http-only.

**Comment by brockallen** [comment]
> IdentityServer is always emitting this cookie as non http-only.

BTW, that's essential for its function.
