### ISSUE TITLE
Windows authentication loop

### ISSUE THREAD

**Issue by jpboudreauforces** [IdentityServer/IdentityServer4#4937]
The windows authentication does not seems to be working on last 4.x version. It was working before on 3.x.

### Issue / Steps to reproduce the problem
Create a new Identity Server with the quickstart UI
`
dotnet new is4empty -n IdentityServer
cd IdentityServer
dotnet new is4ui
`

In the ConfigureService function of startup.cs add
`services.Configure<IISServerOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
            });`

Publish on IIS (in-process, with anonymous, windows auth enabled, default app pool) and go to a client app or on the quickstart UI to manage grant and log in with Windows as External Provider.
The Authentication window popup and keep popping up in an infinite loop.

### Relevant parts of the log file
Nothing is shown in the log.

**Comment by leastprivilege** [comment]
Windows authentication is not a feature of IdentityServer, but of ASP.NET Core.

Did you follow the docs?
https://identityserver4.readthedocs.io/en/latest/topics/windows.html
