### ISSUE TITLE
Access Token validation in .net framework mvc app

### ISSUE THREAD

**Issue by mahyarnet** [IdentityServer/IdentityServer4#494]
I used Identity Server 4 to implement sso, some applications have  implemented by mvc 4  and full .net frame work and are using IdentityServer3 token validation, but when I connected them to my new Identity server they couldnt validate access token.
Is there any specific configuration?

**Comment by leastprivilege** [comment]
We need more information.

**Comment by mahyarnet** [comment]
First of all thank you for your attention,
In my identityserver app that use idsv4 and run on port "7000" have a client
`new Client
                {
                    ClientId = "client",

                    // no interactive user, use the clientid/secret for authentication
                    AllowedGrantTypes = GrantTypes.ClientCredentials,

                    // secret for authentication
                    ClientSecrets =
                    {
                        new Secret("secret".Sha256())
                    },

                    // scopes that client has access to
                    AllowedScopes = { "api1" }
                }`
and in my .Net Framework Api's startup class that use port no "7001" :
`app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "http://localhost:7000",
                ValidationMode = ValidationMode.ValidationEndpoint,
                
                RequiredScopes = new[] { "api1" }
            });`

and finally in my client catch token successfully:
`static TokenResponse GetClientToken()
        {
            var client = new TokenClient(
                "http://localhost:5000/connect/token",
                "client",
                "secret");

            return client.RequestClientCredentialsAsync("api1").Result;
        }`
but when i use this token to call api: 
`static void CallApi(TokenResponse response)
        {
            var client = new HttpClient();
            client.SetBearerToken(response.AccessToken);

            Console.WriteLine(client.GetStringAsync("http://localhost:7001/api/identity/get").Result);
        }`
client throw an exception: 

> Response status code does not indicate success: 401 (Unauthorized).

I have done all of them in core api and every things are ok!!

**Comment by mahyarnet** [comment]
> https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/issues/124

Thank you

**Comment by Sivasekare** [comment]
Still I'm the facing though I sign the tokens using X509 certificates and using IS4 latest version.  Appreciate your help
