### ISSUE TITLE
Logout when multiple tabs

### ISSUE THREAD

**Issue by juanan** [IdentityServer/IdentityServer4#4944]
I have noticed that when I have 2 tabs opened and try to logout, this is what happens:

Tab 1:

Request starting HTTP/2.0 GET https://xxx/auth/connect/endsession?id_token_hint=zzz&post_logout_redirect_uri=yyy
Request starting HTTP/2.0 GET https://xxx/auth/Account/Logout?logoutId=zzz

Tab 2 (since I was already authorized in tab1, the login form was not shown and the user was redirected automatically to the SPA) :

Request starting HTTP/2.0 GET https://xxx/auth/connect/endsession?post_logout_redirect_uri=yyy
Request starting HTTP/2.0 GET https://xxx/auth/Account/Logout

In tab 2 I don't have id_token_hint nor logoutId so my Logout endpoint fails because no PostLogoutRedirectUri to redirect.

How can to deal with that?

![image](https://user-images.githubusercontent.com/17723190/95172716-05f12a00-07b8-11eb-9fc2-9d39ca1e1d46.png)

Many thanks.

**Comment by brockallen** [comment]
That implementation of `Logout` looks nothing like the one we provide: https://github.com/IdentityServer/IdentityServer4.Templates/blob/main/src/IdentityServer4InMem/Quickstart/Account/AccountController.cs#L181

**Comment by juanan** [comment]
This is your implementation

![image](https://user-images.githubusercontent.com/17723190/95205091-34392e80-07e5-11eb-8a55-7ba5725783b2.png)

In my case is the same but instead of redirecting to the Logout form I directy redirect to the PostLogoutRedirectUri.
The thing works great until you open a second tab where the id_token_hint  and logoutId is null.

**Comment by brockallen** [comment]
> In my case is the same but instead of redirecting to the Logout form I directly redirect to the PostLogoutRedirectUri.

And that's wrong. You need to render the logged out page to allow SLO to complete.

**Comment by juanan** [comment]
Ok I am trying to render now the logged out page but the error is the same, in the second tab the logoutId comes null.

I can not debug that part since its part of the Identity Server Core so my question is: can I force anyway to always log in if the user opens a new tab?Right now the user enters directly in all new tabs since he is already logged.
