### ISSUE TITLE
Why it the return url works when logging-in using IS4 TestUsers but the return url does not work with ASP.NET Identity login?

### ISSUE THREAD

**Issue by nhonoskywalker** [IdentityServer/IdentityServer4#4945]
### Question
Why it the return url works when logging-in using IS4 TestUsers but the return url does not work with ASP.NET Identity login?
In my scenario, I'm using a client with authorization_code grant because I'm also using OIDC AAD. Then I have tested the TestUser login in IS4 and works as expected but when I tried the ASP.NET Identity login it does not return me to the MVC client. What's the reason?

### Minimal working example
```
  if (context != null)
     {
         // we can trust model.ReturnUrl since GetAuthorizationContextAsync returned non-null
          return Redirect(model.ReturnUrl);
      }
```
The model.ReturnUrl format seems the same with Identity login when using TestUsers login.

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by brockallen** [comment]
Have you tried the ASP.NET Identity quick start?
https://identityserver4.readthedocs.io/en/latest/quickstarts/6_aspnet_identity.html
