### ISSUE TITLE
Unable to find package IdentityServer4.Storage with version (>= 4.1.1)

### ISSUE THREAD

**Issue by BrianARice** [IdentityServer/IdentityServer4#4946]
### Question
I am getting the error below when I try to build the latest version of IdentityServer4.
When I look at NuGet packages the one that is installed is 4.1.1-0

### Minimal working example
None

### Relevant parts of the log file
Error NU1102 Unable to find package IdentityServer4.Storage with version (>= 4.1.1)  - Found 43 version(s) in NuGet [ Nearest version: 4.1.0 ]  - Found 1 version(s) in IdentityServer Local [ Nearest version: 0.0.0-alpha.0 ]
IdentityServer4

**Comment by leastprivilege** [comment]
did you read me?

![image](https://user-images.githubusercontent.com/1454075/95293471-c38d2300-0873-11eb-8ded-31d906ee7e62.png)

**Comment by Funnybanny** [comment]
> did you read me?
> 
> ![image](https://user-images.githubusercontent.com/1454075/95293471-c38d2300-0873-11eb-8ded-31d906ee7e62.png)

I read it and done it. 
![image](https://user-images.githubusercontent.com/14212919/95576678-24158f00-0a31-11eb-837b-576e9f239985.png)
![image](https://user-images.githubusercontent.com/14212919/95576691-2aa40680-0a31-11eb-83a2-3c622ba5d6b6.png)
When I ran the powershell it gave the same errors. When I ran the script it was successful but Visual Studio gave the same error.

So What to do? Before trying both I deleted the previous and extracted from the zip again.

**Comment by leastprivilege** [comment]
I don't know. sorry.

What's the output of the build script?

**Comment by Funnybanny** [comment]
[output.txt](https://github.com/IdentityServer/IdentityServer4/files/5363188/output.txt)


> I don't know. sorry.
> 
> What's the output of the build script?

**Comment by leastprivilege** [comment]
> MinVer : warning MINVER1001: 'D:\develop\IdentityServer4\IdentityServer4-main\src\Storage\build' is not a valid working directory. Using default version 0.0.0-alpha.0.

That's the problem.

Have you installed git?

**Comment by leastprivilege** [comment]
..or have you removed the ".git" directory in the root?

**Comment by Funnybanny** [comment]
there is no .git directory in the zip file

**Comment by Funnybanny** [comment]
@leastprivilege  Could you update the how to build that simply unzipping the project doesnt work?

**Comment by leastprivilege** [comment]
I see...we need the git folder for versioning.

You need to clone it. I updated the build instructions.

**Comment by leastprivilege** [comment]
Thanks for bringing this to my attention. I never use the zip download, so I didn't consider this path...

**Comment by Funnybanny** [comment]
Thank you for the quick responses
