### ISSUE TITLE
Too many scopes of api caused an error.

### ISSUE THREAD

**Issue by zivfuture** [IdentityServer/IdentityServer4#4950]
### Question
I have lot of apis and scopes. 
When the client try to get an access token from identityserver4.x.  
I get an error:```Scope parameter exceeds max allowed length...```

If the apis and scopes is too much. how should i do?  
Can i hide the scopes in access token and reload scopes when validate the access token in introspection?

**Comment by leastprivilege** [comment]
You can set the maximum length of the scope parameter on the options.

**Comment by pablopioli** [comment]
@zivfuture 
The default max length is 300 characters
https://github.com/IdentityServer/IdentityServer4/blob/18897890ce2cb020a71b836db030f3ed1ae57882/src/IdentityServer4/src/Configuration/DependencyInjection/Options/InputLengthRestrictions.cs

You can change it with

```
services.AddIdentityServer(x =>
            {
                x.InputLengthRestrictions.Scope = 1000;
            })
```

**Comment by zivfuture** [comment]
@leastprivilege  @pablopioli    Thanks for reply ,    But i dont think this is a good idea.

If i have 1000 Apis. 3 scopes per api.     there will be more then 3000 scopes in system.  I can't put then all in access token. Its not a good idea. and the size of access token will become too large.

**Comment by leastprivilege** [comment]
> But i dont think this is a good idea

I agree with you

**Comment by zivfuture** [comment]
@leastprivilege   so ,  how should i do?

**Comment by zivfuture** [comment]
@leastprivilege   Can you help me ?

**Comment by leastprivilege** [comment]
> Then reload scopes from db and Validate it in introspection. But i dont find any example like this.

You can switch to reference tokens, no extra coding/work necessary.

**Comment by zivfuture** [comment]
@leastprivilege   I cant switch to reference tokens,    because i have android and ios client. they cant work with  reference tokens.

**Comment by leastprivilege** [comment]
why?
