### ISSUE TITLE
Not possible to disable caching for discovery document

### ISSUE THREAD

**Issue by spanevin** [IdentityServer/IdentityServer4#4955]
https://github.com/IdentityServer/IdentityServer4/issues/1602

Exactly the same problem appeared in 4.1, no Vary header in metadata response

**Comment by brockallen** [comment]
The code from that PR is still in. So you're saying when there's an age set in config, you're not getting the `Vary` by origin response header?

**Comment by spanevin** [comment]
What age? I can't google anything related to cache control for metadata endpoint. Could you please give me a link to docs about it?

**Comment by spanevin** [comment]
options.Discovery.ResponseCacheInterval

This setting?

Default is null which doesn't set any of cache control headers, which breaks IE as there is no Vary: Origin header as well. Incorrect Cors-Allowed-Origins value is taken from cached response.
It breaks apps in iframes which have other apps in iframes.
There is no option to set just Vary header but don't set Cache-Control header, for me it's still a bug.

**Comment by spanevin** [comment]
Up

**Comment by brockallen** [comment]
Is this what you'd expect to see?

![image](https://user-images.githubusercontent.com/649492/101260060-fed49280-36fa-11eb-882c-2cd5e460d317.png)

**Comment by spanevin** [comment]
Yes

**Comment by brockallen** [comment]
Ok, so then that's how it already works if you are to set something like this:

```
services.AddIdentityServer(options =>
{
    options.Discovery.ResponseCacheInterval = 600;
});
```

**Comment by spanevin** [comment]
Have you read my previous comments at all?

I DON'T WANT to set any specific cache interval. Default behavior is good for me. The ONLY problem is that IE doesn't vary the cache by Origin without this header. And there is NO WAY to set JUST vary: Origin header with NO OTHER cache-related headers!

**Comment by brockallen** [comment]
So your request put more simply is: "Please always emit Vary: Origin on the discovery document"?

**Comment by spanevin** [comment]
The main problem is that DEFAULT middleware behavior DOES NOT WORK with IE caching properly.

**Comment by brockallen** [comment]
I"M SORRY CAPS DON"T HELP ME UNDERSTAND YOU ANY BETTER

**Comment by spanevin** [comment]
> 
> 
> So your request put more simply is: "Please always emit Vary: Origin on the discovery document"?

Maybe. I don't know the source of the middleware. Maybe it does something specific for CORS requests, maybe not. Only CORS requests are affected.

**Comment by spanevin** [comment]
> 
> 
> I"M SORRY CAPS DON"T HELP ME UNDERSTAND YOU ANY BETTER

It's the easiest way to highlight the most important parts. **I don't think this way is any better**

**Comment by brockallen** [comment]
It's Saturday. I'm trying to take time out of my weekend to work on an issue that's affecting you. I'm trying to understand your problem, and I guess you are not 100% clear on the issue yourself. Only providing a link to an old issue wasn't sufficient for helping me hone in on what your issue is. 

Your last comment is the first one to mention Ajax and CORS. This gives me more into go investigate. And there was no need to berate me.

**Comment by spanevin** [comment]
>Incorrect Cors-Allowed-Origins value is taken from cached response.

Doesn't it say clearly about CORS request issue?

I'm OK if there is any option to set vary: Origin or don't set it, but only this header, not in combination with other cache-control related headers. Maybe there are cases where this header is not needed at all, which I don't know about as I'm not an expert in CORS probably... But I'd like to see the default value/behavior work properly in all browsers.

**Comment by spanevin** [comment]
>It's Saturday.

I know. But the issue was created 2 months ago, and #1602 was created 3 years ago. And you want Duende IdentityServer to be paid...

**Comment by brockallen** [comment]
> Doesn't it say clearly about CORS request issue?

CORS was mentioned, but wasn't the main point of the issue. The ask was adding Vary when setting a cache value. The fact that it was during an Ajax call was ancillary.

Also given that the OP did not re-open the issue or mention that the PR did not fix their issue, I assumed the fix was correct and solved the issue. Your issue was not clear how it was different or new, so I was trying to determine what was different in your scenario. You didn't really help in that given that you didn't explain what was different.

Also, disabling caching (by setting `ResponseCacheInterval` to zero) would be a valid fix, as it would prevent caching. But if you enable caching, the Vary header is set. So I'm not clear why one of those two are not valid solutions for you. 

>> It's Saturday.
> I know. But the issue was created 2 months ago, and #1602 was created 3 years ago. And you want Duende IdentityServer to be paid...

This repo is IdentityServer4 -- the free version. If you'd like, I can move this issue to the Duende repo and have it fixed there instead.

**Comment by spanevin** [comment]
I want to appologize if I didn't explain the issue clearly from the scratch. Now when I read your explanation I see it was my fault.

I thought the #1602 fixed all affected cases so I was surprised than when I upgraded IdentityServer4 from 2.0 to 2.5 and removed a custom middleware which set this header explicitly, I found the issue was still reproducible.

I never used options.Discovery.ResponseCacheInterval so I didn't know this setting was related at all. And when this issue was created, nobody mentioned the name of this setting. I had to go through source code to find out what does the "an age set in config" mentioned in the first comments mean. Unfortunately the IdentityServer4 doc search is not great.

After that I did some experiments with this setting and found that there is no way to keep default browser caching interval settings but just set the vary: Origin header to fix the bug. And reported it here.

>So I'm not clear why one of those two are not valid solutions for you.

I'm OK with default browser caching behavior. With the exception of the bug with IE and CORS. I want to have an option to use browser's default caching (which I assume is achievable using the default null value of the ResponseCacheInteval option) but with no CORS-related bug in IE. In other words, I don't want to set any particular cache interval. Browser's default interval is OK for me.

>This repo is IdentityServer4 -- the free version.
I understand. But people can judge the new company by previous versions of the products and their support.

**Comment by brockallen** [comment]
> I found the issue was still reproducible.

So we think the problem is an odd bug in IE. If you set the cache interval to zero, does it fix your problem?

> But people can judge the new company by previous versions of the products and their support.

Yes, and we've done a hell of a good job for the past 10 years considering it's been free. Just imagine how much better it will be when it's paid.

**Comment by spanevin** [comment]
JFYI unrelated, but even upgrading from 2.0 to 2.5 was painful as redis implementation used for shared things was switched from StackExchange.Redis.StrongName 1.x lib to StackExchange.Redis 2.x lib but IdentityServer4 and the AspNetCore framework itself were not the only things which used redis in my app... You know, it's hardly possible to use 2 different libs which share the same namespaces and classes...

**Comment by spanevin** [comment]
>If you set the cache interval to zero, does it fix your problem? I'm pretty sure if you set the cache interval to be a non-zero value it will also fix your problem.

As I said before, I don't want to set any cache interval explicitly, including 0.
Yes if I set the setting to 0 it solves IE behavior but disables caching which introduces another issue, no cache.
If I set the setting to any other int value, it also solves IE behavior, but as I said before, I don't want to set the interval explicitly, I want ability to use browser's default. But more than that I want the default middleware behavior to work properly in all browswers. I don't want to care about setting this value explicitly... If you think there is another good default value, not the null, you can just change the default probably... It's up to you.

None of the quick start guides set this setting or say "do this but remember, it doesn't work properly in IE"

**Comment by brockallen** [comment]
> As I said before, I don't want to set any cache interval explicitly, including 0.

There's history here that might help you understand -- 

Our code originally had no code on setting cache values for the discovery endpoint. The setting was added as a new feature to fix the issue you originally linked and was added in a non-breaking way to not change prior behavior. Thus to have the feature (cache or no-cache) you needed to set something.

**Comment by spanevin** [comment]
>The setting was added as a new feature to fix the issue you originally linked

#1602 the first post says the setting did exist already, didn't it? Am I reading it incorrectly?
As I understand from #1602 description, the the setting was added before but it didn't specify the vary header as well.

Now I think I found some more misunderstanding in the threads. I found #1602 when I investigated the IE issue I mentioned. But as I didn't used the interval setting, I thought it was a common issue and people understood that and fixed it by adding the vary header with no relation to the interval setting. It's why I was surprised that the issue was not fixed for me after upgrading to 4.1 and I thought it didn't go to 4.x at all by some reason (as I wrote in the first post of this issue).

It looks like you and I had different understanding of the same issue...

**Comment by spanevin** [comment]
> So your request put more simply is: "Please always emit Vary: Origin on the discovery document"?

Looks like it's the simplest answer for both threads, and probably the only good solution...

**Comment by spanevin** [comment]
I love github :(
