### ISSUE TITLE
IdentityServerConstants.LocalApi.AuthenticationScheme's authentication handler parses booleans inconsistently with other alternatives

### ISSUE THREAD

**Issue by SpiritBob** [IdentityServer/IdentityServer4#4956]
When you create a `PolicyScheme` that adds the above authentication scheme (`AuthorizationPolicyBuilder.AddAuthenticationSchemes`), and you add a claim requirement to the policy, which checks if a given claim's value is `true` or `false, you will be surprised to see that when you pass `"true"` to the `allowedValues` parameter of `AuthorizationPolicyBuilder.RequireClaim`, it'll fail (succeeds if using JwtBearer/Introspection endpoint logic), because the internal Identity Server authentication handler for some reason parses those values by capitalizing the first letter.

That is,  `true` is parsed as `"True"`, `false` is parsed as `"False"`.

This is not the case when you use Microsoft's JwtBearer token handler, or the OAuthIntrospection handler you guys created.

**Comment by leastprivilege** [comment]
hm - can't repro. I get lowercase everywhere (i tried both ClaimValuesTypes.String as well as ClaimValueTypes.Boolean).

![image](https://user-images.githubusercontent.com/1454075/95554632-ca04d180-0a10-11eb-892f-30726d02661c.png)

**Comment by SpiritBob** [comment]
That's weird. I'll upload a repo later today. I'll keep you posted.

**Comment by leastprivilege** [comment]
I won't have time to look at your repro right now - just debug it yourself and let me know.

**Comment by SpiritBob** [comment]
You are right, it was an error on my part.
