### ISSUE TITLE
JWKS endpoint support for client secret

### ISSUE THREAD

**Issue by cortex93** [IdentityServer/IdentityServer4#4961]
### Question
Currently, it is possible to use jwks as client secrets but they seems to be hard defined in the client secret collection.
Would it be possible to configure a secret as a jwks endpoint like "https://a.client/.well-known/jwks.json" and have identity server grabing the keys ?

I guess i need a new secret type and a ISecretValidator implementation that would build a collection of JsonWebKey secret and delegate the validation to the PrivateKeyJwtSecretValidator. Does it make sense ?

**Comment by leastprivilege** [comment]
All the plumbing is in place to build this yourself.
