### ISSUE TITLE
One user with multiple identities

### ISSUE THREAD

**Issue by ju57u5** [IdentityServer/IdentityServer4#4962]
### Question

Hey,

first of all thanks for all the great work you did with Identity Server 4 and good luck on your future endeavors.

I've got a question: We have users that will be able to select an identity they want to login as, after typing in their credentials. These identities should (in our best case implementation) look totally different to the client, meaning that the client will receive a different "sub" claim if the user logs in as a different identity.

We investigated this issue a bit and came to the conclusion that it is very important that the session you have with Identity Server 4 is containing the correct sub claim in the default identity of the ClaimsPrincipal located at `ClaimsPrincipal.Identity`.

Changing the subject id in that identity would be generally possible, but would prevent the user from logging into two different clients with different identities at the same time. (Because IdentityServer only checks the default identity regardless of client).

So I just wanted to ask if our analysis is correct, meaning that we currently can't implement something like this, without heavily modifying the code or if there is a reasonable way to do this and what that could look like.

Thanks for your help!

**Comment by leastprivilege** [comment]
Basically you are asking about multiple concurrent sessions.

This is nothing we have designed for - and yes you are right - this would mean to make some major changes to our code.

**Comment by ju57u5** [comment]
Hey thanks for your answer.

Just out of interest: If I were to implement multiple concurrent session for IdentityServer is that something that would have a chance to get upstream (for Duende)? Or is this out of scope for IdentityServer or are the architectural changes so major that it does make little sense if you don't do it yourselves?

**Comment by leastprivilege** [comment]
I really don't know. It would be a major change, and we haven't looked into all the implications yet.
