### ISSUE TITLE
Multiple valid issuers

### ISSUE THREAD

**Issue by pecanw** [IdentityServer/IdentityServer4#4965]
### Question
Is it possible to set multiple valid issuers for Identity Server 4 JWT token validation?

### Details
We need to support multiple valid issuers for two scenarios:
1. Multiple geographical locations for identity server instances (each using it's own DNS and having it's own issuer; in future might will be replaced by a traffic manager and one common DNS, however we cannot do the change now)
2. Seamless upgrade of an old system (based on Identity server 3) - we need temporarily accept tokens from the old identity with different issuer.

**Comment by pecanw** [comment]
I have created a proposed solution. See the pull request #4967.

**Comment by alexgalie** [comment]
Maybe this will help: https://blog.novacare.no/identity-multiple-valid-issuers-jwt/
