### ISSUE TITLE
Open ID Configuration JSON returns a mix of public URL and localhost

### ISSUE THREAD

**Issue by jonasarcangel** [IdentityServer/IdentityServer4#4966]
Open ID Configuration JSON returned is a mix of my public URL and localhost. It shouldn't have localhost.

http://167.172.118.170/.well-known/openid-configuration

Identity Server configuration:

            services.AddIdentityServer(options =>
            {
                options.IssuerUri = "https://167.172.118.170/";

            })
                .AddApiAuthorization<ApplicationUser,
                ApplicationIdentityDbContext>(); 

Repository: https://github.com/jonasarcangel/BlazorLoginNetworkErrorIssue/blob/master/src/MyProject.Data.Identity/Extensions.cs

Host is configured as follows in Startup.cs:

            app.Use(async (ctx, next) =>
            {
                ctx.Request.Scheme = "http";
                ctx.Request.Host = new HostString("167.172.118.170");
                await next();
            });

Repository:
https://github.com/jonasarcangel/BlazorLoginNetworkErrorIssue/blob/master/src/MyProject.Web.Server/Startup.cs

Authentication.razor does not provide any option on how to provide server URL.

Repository:
https://github.com/jonasarcangel/BlazorLoginNetworkErrorIssue/blob/master/src/MyProject.Web.Client.Shell/Pages/Authentication.razor

**Comment by leastprivilege** [comment]
Sorry -  I don't follow. Is this still an issue, and do you have more information?
