### ISSUE TITLE
Prompt=login in request object => loop

### ISSUE THREAD

**Issue by bigheadedmonster** [IdentityServer/IdentityServer4#4971]
### Issue / Steps to reproduce the problem
Set the prompt=login in a signed request object.

This creates en eternal loop, as the prompt is removed from the raw request, but not from the request object (obviously). Then re-processing of the request in AuthorizeInteractionResponseGenerator re-finds the prompt=login and starts login again.

I have noted this in version 3.X, but as far as I can see, the problem should be the same in the newest version? (Have looked at the source-code a bit, but not thoroughly).

**Comment by leastprivilege** [comment]
Thanks! We will look into it.

**Comment by bigheadedmonster** [comment]
Any status on this? 
Alternatively, do you have any suggestions for at quick-fix, until idsrv fixes the issue?
We have to mitigate this problem somehow and it seems like we have to re-implement one of the core interfaces in idsrv in order to achieve this?

**Comment by leastprivilege** [comment]
I will try to look into it beginning next week. OK?

**Comment by bigheadedmonster** [comment]
Perfect, thank you! 👍

**Comment by leastprivilege** [comment]
OK - I can confirm the bug.

Not sure there is an easy fix right now. Would passing the prompt outside the request object work as a workaround for the time being?

**Comment by bigheadedmonster** [comment]
Hi. Thanks for verifying.
We are currently using exactly this approach, and then additionally recommending using auth_time.
But, I think we will have to re-implement the class/interface where you remove prompt from the request and set "IsLogin=true" to include some internal state-keeping that temporarily fixes this issue for us, until a proper fix is introduced from Identity Server.

**Comment by leastprivilege** [comment]
If you have a fix, feel free to propose a PR.

**Comment by brockallen** [comment]
Related: https://github.com/IdentityServer/IdentityServer4/issues/3571

We will look into both
