### ISSUE TITLE
update supported specifications in docs

### ISSUE THREAD

**Issue by JuliusPC** [IdentityServer/IdentityServer4#4975]
On [this page](https://identityserver4.readthedocs.io/en/latest/intro/specs.html) the spec (<https://openid.net/specs/openid-connect-rpinitiated-1_0.html>) is missing, [although IS4 supports it](https://identityserver4.readthedocs.io/en/latest/endpoints/endsession.html). RP-initiated logout was part of the session management spec, but was moved to a separate spec. Although you mention the old version of the session management spec, you link to the current one, which may be confusing.

proposal: Check if implementation matches "OpenID Connect Session Management 1.0 - draft **30**" instead of draft 28 and update the version number. Add [OpenID Connect RP-Initiated Logout 1.0 - draft 01](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) as supported spec on this page.

**Comment by leastprivilege** [comment]
done. thanks!
