### ISSUE TITLE
connect/token： Stress test 50 people concurrent program 500 abnormal

### ISSUE THREAD

**Issue by murongqingsi** [IdentityServer/IdentityServer4#4976]
When using the ABP framework https://github.com/abpframework/abp , get token interface through stress test: connect / token, and there are 500 exceptions in the visits of 50 people. What is the cause?

In addition, the source code can not be found. Can you tell the location of the interface code for easy reference.

**Comment by leastprivilege** [comment]
You will need to contact ABP.
