### ISSUE TITLE
Modifying Quickstart 6 to use self-signed cert 

### ISSUE THREAD

**Issue by MylesRip** [IdentityServer/IdentityServer4#4977]
After getting Quickstart 6 to work on my dev computer, I tried loading and using a self-signed cert from a .pfx file. The only changes were... 

In IdentityServerAspNetIdentity.Startup.ConfigureServices: 

**Added:** 
var certificate = new X509Certificate2("localhostFromMyCAwithRootCA.pfx", "mypassword");

**Replaced:** 
//builder.AddDeveloperSigningCredential();
builder.AddSigningCredential(certificate);

Note that I added the pfx file as an Embedded Resource. 
Also, the pfx file itself appears to be valid when examined using certutil. 
Am I missing a step? 

**Here is the log:** 

[09:32:25 Debug] IdentityServer4.Hosting.EndpointRouter
Request path /.well-known/openid-configuration matched to endpoint type Discovery
 
[09:32:25 Debug] IdentityServer4.Hosting.EndpointRouter
Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryEndpoint
 
[09:32:25 Information] IdentityServer4.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
 
[09:32:25 Debug] IdentityServer4.Endpoints.DiscoveryEndpoint
Start discovery request
 
[09:32:25 Debug] IdentityServer4.Hosting.EndpointRouter
Request path /.well-known/openid-configuration/jwks matched to endpoint type Discovery
 
[09:32:25 Debug] IdentityServer4.Hosting.EndpointRouter
Endpoint enabled: Discovery, successfully created handler: IdentityServer4.Endpoints.DiscoveryKeyEndpoint
 
[09:32:25 Information] IdentityServer4.Hosting.IdentityServerMiddleware
Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryKeyEndpoint for /.well-known/openid-configuration/jwks
 
[09:32:25 Debug] IdentityServer4.Endpoints.DiscoveryKeyEndpoint
Start key discovery request
 
[09:32:26 Information] IdentityServer4.Events.DefaultEventService
{"Details": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at System.Object.GetType()\r\n   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.CreateJwkDocumentAsync()\r\n   at IdentityServer4.Endpoints.DiscoveryKeyEndpoint.ProcessAsync(HttpContext context)\r\n   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)", "Category": "Error", "Name": "Unhandled Exception", "EventType": "Error", "Id": 3000, "Message": "Object reference not set to an instance of an object.", "ActivityId": "0HM3H3P3D065B:00000002", "TimeStamp": "2020-10-15T15:32:26.0000000Z", "ProcessId": 23388, "LocalIpAddress": "::1:5001", "RemoteIpAddress": "::1", "$type": "UnhandledExceptionEvent"}
 
[09:32:26 Fatal] IdentityServer4.Hosting.IdentityServerMiddleware
Unhandled exception: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.CreateJwkDocumentAsync()
   at IdentityServer4.Endpoints.DiscoveryKeyEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
 
[09:32:26 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Object.GetType()
   at IdentityServer4.ResponseHandling.DiscoveryResponseGenerator.CreateJwkDocumentAsync()
   at IdentityServer4.Endpoints.DiscoveryKeyEndpoint.ProcessAsync(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by leastprivilege** [comment]
This works for us
https://github.com/IdentityServer/IdentityServer4/blob/9fa8eafdeaca8dc60953cebb5a215a86701828b0/src/IdentityServer4/host/Startup.cs#L140

So maybe something is wrong with your cert?

**Comment by MylesRip** [comment]
Thanks for your reply! 

If that's the case, I'd like to be able to verify it. Maybe you could share how you went about creating your cert(s). 

Here's what I did: 

Based on information from [here](https://docs.microsoft.com/en-us/azure/application-gateway/self-signed-certificates) and other places, I used openssl to create a custom, self-signed CA certificate and installed it in the certificate store in the following locations: 

Local Computer / Trusted Root Certification Store
Current User / Trusted Root Certification Store

Then I created a dependent cert that was chained from that one and issued to localhost. This cert was installed to: 

Local Computer / Personal
Current User / Personal

The certs appear to be correct as far as I was able to tell by inspecting and verifying them. 

Next I combined the .crt and .key files into a .pfx file that included both the CA cert and the one that was chained from it. 

Finally, I moved the pfx file to the appropriate folder in my project, included it as on Embedded Resource, and made the code changes described in my original post. 

If it would be helpful, I could provide the specific commands I used for all of the above steps.

**Comment by leastprivilege** [comment]
how about you first try using the certs that are included in our repo...just to see if that makes a difference?

**Comment by MylesRip** [comment]
Thanks for the tip. I found the "identityserver_testing" in a different part of the repo (not in the quickstart) and installed the .cer file in Current User / Trusted Root Certification Authorities and loaded the corresponding .pfx file in the Startup file instead of my cert. It worked! I'll work back from that to try to figure out why my cert doesn't work. I'll let you know how it goes. Thanks again.

**Comment by leastprivilege** [comment]
> installed the .cer file in Current User / Trusted Root Certification Authorities

That's not necessary. The code snippet I sent you above works solely on a file being loaded on the fly.

**Comment by MylesRip** [comment]
Thanks again for your advice. You are correct (of course). I removed the cert from the store and it still worked, so the problem at this point definitely appears to be my certificate. (Maybe at some point in the future the IS4 code could test for this situation and provide messaging that gives more specific feedback on what it's expecting that it's not finding.) I still haven't gotten my certs to work, but I'm comparing my two certs with the one included in the repo to figure out why mine doesn't work. 

My certs: 
1. custom self-signed CA for "all issuance policies" and "all application policies" 
2. cert chained from the CA and issued to localhost for "all application policies"

Repo cert:
1. self-signed cert for "all issuance policies", "proves your identity to a remote computer, and "ensures the identity of a remote computer". 

Wouldn't the last two purposes for the repo cert be included in "all issuance policies" or "all application policies"? Hmmm... 

To put my experiment in context, this is one step along the way to my eventual goal, which is to set up an application (using microservices and a Blazor server frontend) running in Docker Linux containers with IS4 running as a service in its own, separate container. As an extra layer of security behind the reverse proxy, the backend services would use https among each other. I want the application environment on my development machine (Windows 10 Professional with Visual Studio 2019 and Docker for Windows with WSL 2 enabled) to be as close to a production environment as possible, meaning that it would use certs using the same mechanisms as they would in production and Docker containers that could be used in production. I wasn't able to get that working so I went back to square one and started with Quickstart 6 with the idea of refactoring it until I eventually get a production-like configuration.

**Comment by MylesRip** [comment]
Update... I was able to create a self-signed root certificate that works for SSL (at least when running under Windows) and even chained a certificate from that one and got it to work (again, when running directly in Windows). Apparently when the Windows certificate viewer says "all issuance policies" and "all application policies", it doesn't really mean it. It's necessary to specifically set it up so that it says "ensures the identity of a remote computer", a.k.a. Enhanced Key Usage = Server Authentication (1.3.6.1.5.5.7.3.1).  

When I try to run it in Docker Linux containers, it doesn't work, but I suppose that's a different scenario so I think I should close this one. Thanks for the help!
