### ISSUE TITLE
Disadvantages of using AddDeveloperSigningCredential() for API protection?

### ISSUE THREAD

**Issue by improwise** [IdentityServer/IdentityServer4#4979]
If our only consumers of access_tokens are machines calling a protected API, and the access_tokens only have a TTL of 3600, what actual disadvantages are there of using AddDeveloperSigningCredential() instead of "real" keys? Single server only.

Have looked in the documentation but have not found any obvious disadvantages for our scenario by using AddDeveloperSigningCredential() but the method name is kind of scary.

**Comment by leastprivilege** [comment]
The main drawback of this method is the key storage location - and that it never gets rotated.

From a crypto point of view, the key is totally fine.

**Comment by improwise** [comment]
Thanks. Since the TTL is only 3600 I guess that key rotation perhaps isn't as important as in other more typical scenarios with more long lived tokens.
