### ISSUE TITLE
Malformed redirect_uri when login

### ISSUE THREAD

**Issue by crkjl** [IdentityServer/IdentityServer4#4983]
Hi,

I'm not sure where is my error, but I've tried and reviewed all in my code without success.

When my client app (Angular 10.1, oidc client: angular-auth-oidc-client) do a request to login, the redirectUrl is sent, and IS4 responds with a "malformed redirect_uri" error.

**Request:**
https://epmid.xxxxxxx.com/connect/authorize?client_id=e3m&redirect_uri=https%253A%252F%252Fe3m.xxxxxx.com&response_type=code&scope=openid%2520profile%2520roles%2520offline_access%2520E3MApi&nonce=cff811f389293bc3bd905bfdc6c8614a02za6ShIX&state=a72e68d561a3777c10db97fc7898f754acYqmZJK1&code_challenge=qaXRF4swipqQn5ED7uJKAK_I0ErTOkx0Na7hvLaeFRY&code_challenge_method=S256

```
Oct 17 10:59:31 ubuntu epmid[26172]: [10:59:31 Debug] IdentityServer4.Stores.ValidatingClientStore
Oct 17 10:59:31 ubuntu epmid[26172]: client configuration validation for client e3m succeeded.
Oct 17 10:59:31 ubuntu epmid[26172]: [10:59:31 Error] IdentityServer4.Validation.AuthorizeRequestValidator
Oct 17 10:59:31 ubuntu epmid[26172]: malformed redirect_uri: https%3A%2F%2Fe3m.xxxxxx.com
Oct 17 10:59:31 ubuntu epmid[26172]: {"ClientId": "e3m", "ClientName": "E3M", "RedirectUri": null, "AllowedRedirectUris": ["https://e3m.xxxxxx.com"], "SubjectId": "anonymous", "ResponseType": null, "ResponseMode": null, "GrantType": null, "RequestedScopes": "", "State": null, "UiLocales": null, "Nonce": null, "AuthenticationContextReferenceClasses": null, "DisplayMode": null, "PromptMode": "", "MaxAge": null, "LoginHint": null, "SessionId": null, "Raw": {"client_id": "e3m", "redirect_uri": "https%3A%2F%2Fe3m.xxxxxx.com", "response_type": "code", "scope": "openid%20profile%20roles%20offline_access%20E3MApi", "nonce": "56a6008d45c57a6818334f9678ba8db204Ob6afcx", "state": "05d129a49ea250ae8c6fd9b2567b799466OyABOmO", "code_challenge": "5r2xWAuPu9hG-TcuTsK0C2tXgfpxeWGS9cym2VzqGIY", "code_challenge_method": "S256"}, "$type": "AuthorizeRequestValidationLog"}
Oct 17 10:59:31 ubuntu epmid[26172]: [10:59:31 Error] IdentityServer4.Endpoints.AuthorizeEndpoint
Oct 17 10:59:31 ubuntu epmid[26172]: Request validation failed
```

Any idea about what could be happening?

Thank you very much for your help
Jose

**Comment by brockallen** [comment]
Yea, that's odd. It looks double encoded?

**Comment by crkjl** [comment]
Sorry @brockallen , it's no double encoded. Has been an error copying request:

This is the request producing the error:

http://epmid.epmtic.com/connect/authorize?client_id=e3m&redirect_uri=https%3A%2F%2Fe3m.epmtic.com&response_type=code&scope=openid%20profile%20roles%20offline_access%20E3MApi&nonce=a133e27e21c80123aaf441eb2663c2d11fVaVXwMw&state=3f6e2fbb6295baf0e620077e737cc753ef6QUQcEN&code_challenge=da_lJf-_umtaPK_vZTkoMXWjrpU2IdcXel8hYg-KBBU&code_challenge_method=S256

Regards

**Comment by brockallen** [comment]
The key in the log is "malformed" -- it's unclear why IS thinks that.

**Comment by crkjl** [comment]
Hi @brockallen , do you have any idea where to investigate the problem?

**Comment by brockallen** [comment]
I don't, sorry. But this is the line from the log to focus on:

```
Oct 17 10:59:31 ubuntu epmid[26172]: malformed redirect_uri: https%3A%2F%2Fe3m.xxxxxx.com
```

**Comment by crkjl** [comment]
Hi @brockallen , I've solved the problem changing to nginx without any change to the code.
It looks like apache2 doesn't handle fine urls and headers.
Regards
