### ISSUE TITLE
Custom endpoint with a reference token

### ISSUE THREAD

**Issue by vocko** [IdentityServer/IdentityServer4#4984]
### Question
I'm trying to implement a custom endpoint on the IS according to the instructions here: https://docs.identityserver.io/en/latest/topics/add_apis.html

The problem I have is that my client is using reference tokens and always gets the 401 response when calls the endpoint with a valid reference token. Is this scenario supported or any easy way how to make an internal introspection working?

I could get it working by setting up no required scope:
```
services.AddAuthentication().AddLocalApi(options => 
{
    // options.ExpectedScope = IdentityServerConstants.LocalApi.ScopeName;
});

services.AddAuthorization(options =>
{
    options.AddPolicy(IdentityServerConstants.LocalApi.PolicyName, policy =>
    {
        policy.AddAuthenticationSchemes(IdentityServerConstants.LocalApi.AuthenticationScheme);
        policy.RequireAuthenticatedUser();
    });
});
```
but when I uncomment the ExpectedScope, it starts returning 401.

**Comment by leastprivilege** [comment]
Reference tokens should work. Let me investigate..

**Comment by vocko** [comment]
It's all good, I've forgotten to request the claim in client, it all works now.
