### ISSUE TITLE
client_id from jwt

### ISSUE THREAD

**Issue by becio** [IdentityServer/IdentityServer4#4989]
### Steps to reproduce the problem

To invoke EndSessionEndpoint passing a valid _id_token_hint_

### Issue

TokenValidator can't extract the clientId from the token because it takes the first audience as clientId rather than searching for it in the claims.

**Please see the GetClientIdFromJwt(string token) method of the TokenValidator class.**

**Comment by leastprivilege** [comment]
Not sure I understand - in an id_token there is no client ID. The value of the audience claim is the client ID.

**Comment by becio** [comment]
my fault, I was providing an accessToken rather than the id_token.

thank you for the hint
