### ISSUE TITLE
Stewardship going forward

### ISSUE THREAD

**Issue by Blackclaws** [IdentityServer/IdentityServer4#4990]
### Question

Seeing as how official development of identity server will be moved to a different org (I've read the discussion why and wish you all the best). I was wondering how the stewardship of this project is going to work going forward. Will you for example accept pull requests that add new features nevertheless? Will there be a handover to the community at large (a council of the top contributors or something similar) so that the general interest in the completely open version has a home?

I'm wondering about this specifically due to the impeding arrival of .NET 5 and whether the community will be allowed to update Identity Server to that version and perform future bugfixing beyond the .NET 3 era.

**Comment by leastprivilege** [comment]
Thanks! These are all valid and good questions.

> how the stewardship of this project is going to work going forward

We will actively maintain this repo for at least another 2 years. This will include bug fixes, security updates and **minor** enhancements. We think this library is pretty much feature complete according to our roadmap.

All **big** new features (like e.g. the automatic key management) is happening in the new repo that has a sustainability model (https://github.com/DuendeSoftware/IdentityServer). It is also completely open source and has a free license as well.

> Will you for example accept pull requests that add new features nevertheless?

Depends. It’s always been a challenge to accept substantial PRs given the complexity and nuance of both the code base and the subject matter. If we think the feature makes sense and fits into our roadmap, we will consider it.

> Will there be a handover to a council of the top contributors or something similar?

You can have a look at the top contributors here: https://github.com/IdentityServer/IdentityServer4/graphs/contributors

As you can see, there are no other “top contributors”. We had good results governing this repo the way we did for the last 6 years. For now it will stay that way.

> due to the impeding arrival of .NET 5

Microsoft ships IdentityServer4 with their .NET 5 templates. It works fine. We are working with Microsoft on a solution for .NET 6 and beyond. There will be an official announcement at some point.

**Comment by chungonion** [comment]
> All **big** new features (like e.g. the automatic key management) is happening in the new repo that has a sustainability model (https://github.com/DuendeSoftware/IdentityServer). It is also completely open source and has a **free** license as well.

I am a bit concerned on this. As the current IdentityServer4 is licensed on Apache License, the word "free" is sort of equivalent to "freedom" but it seems that on the new repo, the "free" is just equivalent as "free beer" --  not all kinds of development are permitted with the "free beer" license option. (Say for my use case, I am using that on commercial projects which it seems violates the license term if I try to use the new Identity Server)

Am I right on this matter? If yes then how would you let the community decide how this project will be moving forward in the future?

Thank you!
