### ISSUE TITLE
How can I pass additional information to identity server while login and based on it return information on token or claims?

### ISSUE THREAD

**Issue by Ishaqkhan2020** [IdentityServer/IdentityServer4#4991]
I am using GrantTypes.Code example and i will have multiple clients using the identity server,
during login where I can provide additional information from my client to Identity server, and based on that additional information I need to return its result.

Steps
1- user press login in client app, it redirects to the identity server login page  
2- when user provider username and password, I need to provid additional information "dynamically" to Get additional information i saved in identity server db, 
example: I need to profileType=basic [which means get only age, country and city information in the token or claim] so that client app can access it and display result.

profileType values will vary [basic, detail etc]

**Comment by leastprivilege** [comment]
Have a look at the profile service

https://identityserver4.readthedocs.io/en/latest/reference/profileservice.html

This is how you add claims to tokens.

**Comment by Ishaqkhan2020** [comment]
Thank you so much for the reply, but how can I pass additional information to identity server while login? 
so that i will add token?

**Comment by Ishaqkhan2020** [comment]
Is there any practical example in the form of code?
also please guide me to from where i can pass additional information to identity server during login so that particular claim or token will be generated.

**Comment by leastprivilege** [comment]
You can pass arbitrary query string parameters on the authorize request - they will be available to you on the login page.

**Comment by Ishaqkhan2020** [comment]
Ok but authorize request url below is created automatically, how can i add additional query string?
connect/authorize?client_id=mvc&redirect_uri=https%3A%2F%2Fclientone.com%3A5002%2Fsignin-oidc& etc

**Comment by leastprivilege** [comment]
That depends on your client side framework/library.

**Comment by Ishaqkhan2020** [comment]
ok i will check, thank you soo much for your support.
