### ISSUE TITLE
Invalid authorization code loop and error 500

### ISSUE THREAD

**Issue by Jumpy555** [IdentityServer/IdentityServer4#4993]
Hi,
I have an **Identity Server 4 application** with Asp.net Core Identity to manage accounts.
It is hosted on Azure as an app service, it runs on https and it's distributed on **two instances**.
I implemented a **self-signed certificate** for AddSigningCredential and I implemented **persisted grants in a database**.

I also have an **Asp.Net MVC 5 application**, hosted on another server on one instance.
It is configured to connect through **Owin** and the grant type is **code** with pkce.

The problem is that, sometimes, once authenticated, the client receives an "**Invalid authorization code**" message and it starts a loop that ends with "HTTP Error 400. The size of the request headers is too long" and many nonce cookies stored on the client.
This could be related to the Identity Server two instances because, before persisting grants in database, it happened more frequently.

Do I need anything else to make Identity Server work on more than one instance, a part from persisting grants in database?

The other problem is that, once it gives those errors, the identity server won't responde anymore.
The page hangs until it gives "**500 - The request timed out**" and the only way to unlock the situation is to delete all cookies.

Do you know what it could be related to?

Thank you

**Comment by brockallen** [comment]
>  It is configured to connect through Owin and the grant type is code with pkce.

I wasn't aware the OWIN/Katana OIDC middleware implementing PKCE? I'd try hybrid flow instead.

**Comment by Jumpy555** [comment]
Thank you for your answer, I found this article saying it would have been safer with pkce so I implemented it in my configuration:

https://www.scottbrady91.com/ASPNET/Refreshing-your-Legacy-ASPNET-IdentityServer-Client-Applications

I will give hybrid flow a try.

To avoid problems with Identity Server running on multiple instances, is it enough to persist grants in the database?

**Comment by brockallen** [comment]
Hybrid solves the same problems as PKCE, so either is acceptable. Hybrid is the older solution, PKCE is the newer solution.
