### ISSUE TITLE
[Authorize] always redirects to "/account/login" on authorization failure

### ISSUE THREAD

**Issue by SpiritBob** [IdentityServer/IdentityServer4#4994]
I've modified `IdentityServerOptions.UserInteraction.LoginUrl` to a complete different url, but this does not seem to affect the redirect from failing to authorize.

**Comment by brockallen** [comment]
Use the `LoginPath` on the `CookieAuthenticationOptions` instead:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.cookieauthenticationoptions.loginpath?view=aspnetcore-1.1

**Comment by SpiritBob** [comment]
> Use the `LoginPath` on the `CookieAuthenticationOptions` instead:
> 
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.cookieauthenticationoptions.loginpath?view=aspnetcore-1.1

Thank you!
