### ISSUE TITLE
Hybrid client refresh tokens

### ISSUE THREAD

**Issue by strung250** [IdentityServer/IdentityServer4#50]
Hey everyone, I am new to Openid Connect and Identity Server. However, I did manage to download the sample and get things working but I am having an issue getting a refresh token. I created my client as follows:

new Client
                {
                    ClientId = "hybridClient",
                    Flow = Flows.Hybrid,
                    RequireConsent = false,//setting this to true made no difference    
                    ClientName = "Hybrid client",                
                    RedirectUris = new List<string>
                    {
                        "http://localhost:23114/signin-oidc"
                    },
                    AllowedScopes = new List<string>
                    {
                        StandardScopes.OpenId.Name,
                        StandardScopes.OfflineAccess.Name,
                        StandardScopes.Profile.Name,
                        StandardScopes.Email.Name,
                        StandardScopes.Roles.Name,
                        "api1"
                    },
                },

my MVC project startup contains:

 app.UseCookieAuthentication(options =>
            {
                options.AuthenticationScheme = "cookies";
                options.AutomaticAuthenticate = true;
            });

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            app.UseOpenIdConnectAuthentication(options =>
            {
                options.AuthenticationScheme = "oidc";
                options.SignInScheme = "cookies";
                options.AutomaticChallenge = true;
   
                options.Authority = "https://localhost:44326/";
                options.RequireHttpsMetadata = false;

                options.ClientId = "hybridClient";
                options.ResponseType = "code id_token token";

                options.Scope.Add("offline_access");
                options.Scope.Add("profile");
                options.Scope.Add("email");
                options.Scope.Add("roles");
                options.Scope.Add("openid");
                options.Scope.Add("api1");
                
                options.TokenValidationParameters.NameClaimType = "name";
                options.TokenValidationParameters.RoleClaimType = "role";

            });

After I authenticate with the 'bob' user, my claims contain access token and id_token but no refresh token. What am I missing?

As a separate question, where would I be able to look up the access code the authorization endpoint gives me? I was going to try and hit the token endpoint before my API call to see if it would give me a refresh token but it needs an access code. I see plenty of ID Server 3 examples on how to use OpenIdConnectAuthenticationNotifications  to set claims for this type of thing but I haven't been able to figure it out for ID Server 4. Any help would be appreciated.

**Comment by leastprivilege** [comment]
logs please.

**Comment by strung250** [comment]
Here are the logs:

3/7/2016 11:03:19 AM Info User profile is available. Using 'C:\Users\xxxxx\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
3/7/2016 11:03:19 AM Debug Hosting starting
3/7/2016 11:03:19 AM Debug Hosting started
3/7/2016 11:03:19 AM Info Request starting HTTP/1.1 DEBUG http://localhost:44388/ text/html 
3/7/2016 11:03:19 AM Debug DEBUG requests are not supported
3/7/2016 11:03:20 AM Debug Request successfully matched the route with name '' and template ''.
3/7/2016 11:03:20 AM Debug Executing action Plan.IdentityServer.UI.Home.HomeController.Index
3/7/2016 11:03:20 AM Info Executing action method Plan.IdentityServer.UI.Home.HomeController.Index with arguments () - ModelState is Valid'
3/7/2016 11:03:20 AM Debug Executed action method Plan.IdentityServer.UI.Home.HomeController.Index, returned result Microsoft.AspNet.Mvc.ViewResult.'
3/7/2016 11:03:21 AM Debug The view 'Index' was found.
3/7/2016 11:03:21 AM Info Executing ViewResult, running view at path /UI/Home/Views/Index.cshtml.
3/7/2016 11:03:21 AM Info Executed action Plan.IdentityServer.UI.Home.HomeController.Index in 0.1514ms
3/7/2016 11:03:21 AM Info Request finished in 0.1965ms 200 text/html; charset=utf-8
3/7/2016 11:03:31 AM Info Request starting HTTP/1.1 GET https://localhost:44388/.well-known/openid-configuration  
3/7/2016 11:03:31 AM Debug Start discovery request
3/7/2016 11:03:31 AM Info Request finished in 0.0125ms 200 application/json
3/7/2016 11:03:31 AM Info Request starting HTTP/1.1 GET https://localhost:44388/.well-known/openid-configuration/jwks  
3/7/2016 11:03:31 AM Debug Start key discovery request
3/7/2016 11:03:31 AM Info Request finished in 0.0047ms 200 application/json
3/7/2016 11:03:31 AM Info Request starting HTTP/1.1 GET https://localhost:44388/connect/authorize?client_id=hybridClient&redirect_uri=http%3A%2F%2Flocalhost%3A4679%2Fsignin-oidc&response_type=code%20id_token%20token&scope=openid%20profile%20offline_access%20profile%20email%20roles%20openid%20api1&response_mode=form_post&nonce=635929706118258386.NDliNWVmY2UtYTc5Ny00ZTJiLTkyNDQtYjQyNTMwYzRhZDMxN2RkMDQzMzQtM2FiMy00ZWU1LWFlMTgtY2M1NTU0ODE3ZmU5&state=CfDJ8LRsqLZ5qrtBuiVe_n7JGZQjwAWxWyvWKp8R9dPJWbqDsW387ICAVvuiDSJlXMKrjr1zHR-ito4-PBFinKWssIp928g0O3oS1V5acdm882hRs7mcf5ZwBqzrH7TTgrmWRk-ELFgqzyG8IiYIpQ3Sg3QJI6NBWflZtBYDIJ8gkG6_t7cwKTxEJtRSGO0Uti4euSXTdrzQFRaLYs7j76fYMU8ndPwdPwEFcRqfDzj24LpetLvGXyS04WlxL5RpP1AszCoqssXQ9cas9xYkoRRKG5eaLhOquw4-QFWPC5graOFYhfK4iTT0XHBtZdoFEUee8iGruUyhDDk9O7-riA8Anos3oZMno5SHrQzwLg2BtPi_  
3/7/2016 11:03:31 AM Info Start Authorize Request
3/7/2016 11:03:31 AM Debug No user present in authorize request
3/7/2016 11:03:31 AM Info Start authorize request protocol validation
3/7/2016 11:03:31 AM Info Authorize request validation success
 {
  "ClientId": "hybridClient",
  "ClientName": "Hybrid Client",
  "RedirectUri": "http://localhost:4679/signin-oidc",
  "AllowedRedirectUris": [
    "http://localhost:4679/signin-oidc"
  ],
  "SubjectId": "unknown",
  "ResponseType": "code id_token token",
  "ResponseMode": "form_post",
  "Flow": "Hybrid",
  "RequestedScopes": "openid profile offline_access email roles api1",
  "State": "CfDJ8LRsqLZ5qrtBuiVe_n7JGZQjwAWxWyvWKp8R9dPJWbqDsW387ICAVvuiDSJlXMKrjr1zHR-ito4-PBFinKWssIp928g0O3oS1V5acdm882hRs7mcf5ZwBqzrH7TTgrmWRk-ELFgqzyG8IiYIpQ3Sg3QJI6NBWflZtBYDIJ8gkG6_t7cwKTxEJtRSGO0Uti4euSXTdrzQFRaLYs7j76fYMU8ndPwdPwEFcRqfDzj24LpetLvGXyS04WlxL5RpP1AszCoqssXQ9cas9xYkoRRKG5eaLhOquw4-QFWPC5graOFYhfK4iTT0XHBtZdoFEUee8iGruUyhDDk9O7-riA8Anos3oZMno5SHrQzwLg2BtPi_",
  "Nonce": "635929706118258386.NDliNWVmY2UtYTc5Ny00ZTJiLTkyNDQtYjQyNTMwYzRhZDMxN2RkMDQzMzQtM2FiMy00ZWU1LWFlMTgtY2M1NTU0ODE3ZmU5",
  "Raw": {
    "client_id": "hybridClient",
    "redirect_uri": "http://localhost:4679/signin-oidc",
    "response_type": "code id_token token",
    "scope": "openid profile offline_access profile email roles openid api1",
    "response_mode": "form_post",
    "nonce": "635929706118258386.NDliNWVmY2UtYTc5Ny00ZTJiLTkyNDQtYjQyNTMwYzRhZDMxN2RkMDQzMzQtM2FiMy00ZWU1LWFlMTgtY2M1NTU0ODE3ZmU5",
    "state": "CfDJ8LRsqLZ5qrtBuiVe_n7JGZQjwAWxWyvWKp8R9dPJWbqDsW387ICAVvuiDSJlXMKrjr1zHR-ito4-PBFinKWssIp928g0O3oS1V5acdm882hRs7mcf5ZwBqzrH7TTgrmWRk-ELFgqzyG8IiYIpQ3Sg3QJI6NBWflZtBYDIJ8gkG6_t7cwKTxEJtRSGO0Uti4euSXTdrzQFRaLYs7j76fYMU8ndPwdPwEFcRqfDzj24LpetLvGXyS04WlxL5RpP1AszCoqssXQ9cas9xYkoRRKG5eaLhOquw4-QFWPC5graOFYhfK4iTT0XHBtZdoFEUee8iGruUyhDDk9O7-riA8Anos3oZMno5SHrQzwLg2BtPi_"
  }
}
3/7/2016 11:03:31 AM Info User is not authenticated.
3/7/2016 11:03:31 AM Info Showing login page
3/7/2016 11:03:32 AM Debug Reading data from file 'C:\Users\xxxxx\AppData\Local\ASP.NET\DataProtection-Keys\key-b6a86cb4-aa79-41bb-ba25-5efe7ec91994.xml'.
3/7/2016 11:03:32 AM Debug Found key {b6a86cb4-aa79-41bb-ba25-5efe7ec91994}.
3/7/2016 11:03:32 AM Debug Considering key {b6a86cb4-aa79-41bb-ba25-5efe7ec91994} with expiration date 2016-05-17 21:35:54Z as default key.
3/7/2016 11:03:32 AM Debug Decrypting secret element using Windows DPAPI.
3/7/2016 11:03:32 AM Debug Opening CNG algorithm 'AES' from provider '' with chaining mode CBC.
3/7/2016 11:03:32 AM Debug Opening CNG algorithm 'SHA256' from provider '' with HMAC.
3/7/2016 11:03:32 AM Debug Using key {b6a86cb4-aa79-41bb-ba25-5efe7ec91994} as the default key.
3/7/2016 11:03:32 AM Info End Authorize Request. Result type: IdentityServer4.Core.Endpoints.Results.LoginPageResult
3/7/2016 11:03:32 AM Info Request finished in 0.014ms 302 
3/7/2016 11:03:32 AM Info Request starting HTTP/1.1 GET https://localhost:44388/ui/login?id=950e91369dda513d52f5e53dfa76dbd0  
3/7/2016 11:03:32 AM Debug The request path /ui/login does not match a supported file type
3/7/2016 11:03:32 AM Debug Request successfully matched the route with name 'Login' and template 'ui/login'.
3/7/2016 11:03:32 AM Debug Action 'Plan.IdentityServer.UI.Login.LoginController.Index' with id '66807072-d7ef-45aa-884e-11882f73f176' did not match the constraint 'Microsoft.AspNet.Mvc.ActionConstraints.HttpMethodConstraint'
3/7/2016 11:03:32 AM Debug Executing action Plan.IdentityServer.UI.Login.LoginController.Index
3/7/2016 11:03:32 AM Info Executing action method Plan.IdentityServer.UI.Login.LoginController.Index with arguments (950e91369dda513d52f5e53dfa76dbd0) - ModelState is Valid'
3/7/2016 11:03:32 AM Debug Executed action method Plan.IdentityServer.UI.Login.LoginController.Index, returned result Microsoft.AspNet.Mvc.ViewResult.'
3/7/2016 11:03:32 AM Debug The view 'Index' was found.
3/7/2016 11:03:32 AM Info Executing ViewResult, running view at path /UI/Login/Views/Index.cshtml.
3/7/2016 11:03:32 AM Info Executed action Plan.IdentityServer.UI.Login.LoginController.Index in 0.0327ms
3/7/2016 11:03:32 AM Info Request finished in 0.0359ms 200 text/html; charset=utf-8
3/7/2016 11:03:35 AM Info Request starting HTTP/1.1 POST https://localhost:44388/ui/login?id=950e91369dda513d52f5e53dfa76dbd0 application/x-www-form-urlencoded 270
3/7/2016 11:03:35 AM Debug POST requests are not supported
3/7/2016 11:03:35 AM Debug Request successfully matched the route with name 'Login' and template 'ui/login'.
3/7/2016 11:03:35 AM Debug Action 'Plan.IdentityServer.UI.Login.LoginController.Index' with id '9371dd17-e30b-413a-a350-56a537528bb4' did not match the constraint 'Microsoft.AspNet.Mvc.ActionConstraints.HttpMethodConstraint'
3/7/2016 11:03:35 AM Debug Executing action Plan.IdentityServer.UI.Login.LoginController.Index
3/7/2016 11:03:35 AM Info Executing action method Plan.IdentityServer.UI.Login.LoginController.Index with arguments (Plan.IdentityServer.UI.Login.LoginInputModel) - ModelState is Valid'
3/7/2016 11:03:35 AM Info AuthenticationScheme: idsrv signed in.
3/7/2016 11:03:35 AM Debug Executed action method Plan.IdentityServer.UI.Login.LoginController.Index, returned result Plan.IdentityServer.UI.Login.SignInResult.'
3/7/2016 11:03:35 AM Info Executed action Plan.IdentityServer.UI.Login.LoginController.Index in 0.0093ms
3/7/2016 11:03:35 AM Info Request finished in 0.0093ms 302 
3/7/2016 11:03:35 AM Info Request starting HTTP/1.1 GET https://localhost:44388/connect/authorize/login?id=fcab3c0b2aab1798e116041914072cc0  
3/7/2016 11:03:35 AM Info HttContext.User merged via AutomaticAuthentication from authenticationScheme: idsrv.
3/7/2016 11:03:35 AM Info Start Authorize Request (after login)
3/7/2016 11:03:35 AM Info AuthenticationScheme: idsrv was successfully authenticated.
3/7/2016 11:03:35 AM Debug User in authorize request: name:Bob Smith, sub:88421113
3/7/2016 11:03:35 AM Info Start authorize request protocol validation
3/7/2016 11:03:35 AM Info Authorize request validation success
 {
  "ClientId": "hybridClient",
  "ClientName": "Hybrid Client",
  "RedirectUri": "http://localhost:4679/signin-oidc",
  "AllowedRedirectUris": [
    "http://localhost:4679/signin-oidc"
  ],
  "SubjectId": "88421113",
  "ResponseType": "code id_token token",
  "ResponseMode": "form_post",
  "Flow": "Hybrid",
  "RequestedScopes": "openid profile offline_access email roles api1",
  "State": "CfDJ8LRsqLZ5qrtBuiVe_n7JGZQjwAWxWyvWKp8R9dPJWbqDsW387ICAVvuiDSJlXMKrjr1zHR-ito4-PBFinKWssIp928g0O3oS1V5acdm882hRs7mcf5ZwBqzrH7TTgrmWRk-ELFgqzyG8IiYIpQ3Sg3QJI6NBWflZtBYDIJ8gkG6_t7cwKTxEJtRSGO0Uti4euSXTdrzQFRaLYs7j76fYMU8ndPwdPwEFcRqfDzj24LpetLvGXyS04WlxL5RpP1AszCoqssXQ9cas9xYkoRRKG5eaLhOquw4-QFWPC5graOFYhfK4iTT0XHBtZdoFEUee8iGruUyhDDk9O7-riA8Anos3oZMno5SHrQzwLg2BtPi_",
  "Nonce": "635929706118258386.NDliNWVmY2UtYTc5Ny00ZTJiLTkyNDQtYjQyNTMwYzRhZDMxN2RkMDQzMzQtM2FiMy00ZWU1LWFlMTgtY2M1NTU0ODE3ZmU5",
  "SessionId": "2db8d4373bdef4f05b976edff3f29d00",
  "Raw": {
    "client_id": "hybridClient",
    "redirect_uri": "http://localhost:4679/signin-oidc",
    "response_type": "code id_token token",
    "scope": "openid profile offline_access profile email roles openid api1",
    "response_mode": "form_post",
    "nonce": "635929706118258386.NDliNWVmY2UtYTc5Ny00ZTJiLTkyNDQtYjQyNTMwYzRhZDMxN2RkMDQzMzQtM2FiMy00ZWU1LWFlMTgtY2M1NTU0ODE3ZmU5",
    "state": "CfDJ8LRsqLZ5qrtBuiVe_n7JGZQjwAWxWyvWKp8R9dPJWbqDsW387ICAVvuiDSJlXMKrjr1zHR-ito4-PBFinKWssIp928g0O3oS1V5acdm882hRs7mcf5ZwBqzrH7TTgrmWRk-ELFgqzyG8IiYIpQ3Sg3QJI6NBWflZtBYDIJ8gkG6_t7cwKTxEJtRSGO0Uti4euSXTdrzQFRaLYs7j76fYMU8ndPwdPwEFcRqfDzj24LpetLvGXyS04WlxL5RpP1AszCoqssXQ9cas9xYkoRRKG5eaLhOquw4-QFWPC5graOFYhfK4iTT0XHBtZdoFEUee8iGruUyhDDk9O7-riA8Anos3oZMno5SHrQzwLg2BtPi_"
  }
}
3/7/2016 11:03:35 AM Info Issuing successful authorization response
3/7/2016 11:03:35 AM Info Creating Hybrid Flow response.
3/7/2016 11:03:35 AM Info {
  "Category": "TokenService",
  "Name": "Authorization code issued",
  "EventType": "Information",
  "Id": 2010
}
3/7/2016 11:03:35 AM Info Creating Implicit Flow response.
3/7/2016 11:03:35 AM Debug Creating access token
3/7/2016 11:03:35 AM Debug Creating JWT access token
3/7/2016 11:03:35 AM Info {
  "Category": "TokenService",
  "Name": "Access token issued",
  "EventType": "Information",
  "Id": 2000
}
3/7/2016 11:03:35 AM Debug Creating identity token
3/7/2016 11:03:35 AM Info Getting claims for identity token for subject: 88421113
3/7/2016 11:03:35 AM Debug Creating JWT identity token
3/7/2016 11:03:35 AM Info {
  "Category": "TokenService",
  "Name": "Identity token issued",
  "EventType": "Information",
  "Id": 2001
}
3/7/2016 11:03:35 AM Info {
  "Category": "Endpoints",
  "Name": "Endpoint success",
  "EventType": "Success",
  "Id": 3000,
  "Details": {
    "EndpointName": "authorize"
  }
}
3/7/2016 11:03:35 AM Info End Authorize Request. Result type: IdentityServer4.Core.Endpoints.Results.AuthorizeFormPostResult
3/7/2016 11:03:35 AM Info Request finished in 0.0187ms 200 text/html; charset=UTF-8

**Comment by leastprivilege** [comment]
hm - need to try to repro. TBH we won't put much work into this before RC2. I will leave this open and see what I can do.

**Comment by leastprivilege** [comment]
all set?

**Comment by Shadowman4205** [comment]
@leastprivilege  Hello, i am using same HybridAndClientCredentials as granttype but still i  do not get 
refresh_token.

```
   new Client
                {
                    ClientId = "test",
                    ClientName = "Test client",
                    AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,

                    RequireConsent = false,
                    AlwaysSendClientClaims = true,
                    AllowAccessTokensViaBrowser = true,
                    AllowOfflineAccess = true
                    ClientSecrets =
                    {
                        new Secret("test".....)
                    },
                    RedirectUris = new List<string>
                    {
                       'http://localhost:3000/test/calback
                    },
                    AllowedScopes =
                    {
                        StandardScopes.OpenId,
                        StandardScopes.Profile,
                        StandardScopes.Email,
                        StandardScopes.OfflineAccess,
                        "role",
                        "api1",
                    },
                }
```
some logs
```
IdentityServer4.Endpoints.AuthorizeEndpoint:Information: ValidatedAuthorizeRequest
{
  "ClientId": "test",
  "ClientName": "Test client",
  "RedirectUri": "http://localhost:3000/test/calback",
  "AllowedRedirectUris": [
    "http://localhost:3000/test/calback"
  ],
  "SubjectId": "788897b1-9fef-4bb9-9e66-28e714eae785",
  "ResponseType": "code id_token token",
  "ResponseMode": "form_post",
  "GrantType": "hybrid",
  "RequestedScopes": "openid profile offline_access",
  "State": "ODIxMjYwNjI1NDk4NzcwNA==",
  "Nonce": "NjUyODg5NTYyMTM0ODYxNw==",
  "SessionId": "5c72fead00daf3f77aa06bc5146c6fb5",
  "Raw": {
    "state": "ODIxMjYwNjI1NDk4NzcwNA==",
    "nonce": "NjUyODg5NTYyMTM0ODYxNw==",
    "client_id": "reactjs",
    "redirect_uri": "http://localhost:3000/test/calback",
    "response_type": "code id_token token",
    "scope": "openid profile offline_access",
    "response_mode": "form_post"
  }
}

IdentityServer4.Endpoints.AuthorizeEndpoint:Information: Authorize endpoint response
{
  "SubjectId": "788897b1-9fef-4bb9-9e66-28e714eae785",
  "ClientId": "test",
  "RedirectUri": "http://localhost:3000/test/calback,
  "State": "ODIxMjYwNjI1NDk4NzcwNA==",
  "Scope": "openid profile offline_access"
}

```
and post to callbackurl has got this data 
code,id_token,acccess_token,token__type,expires_in,state,session_state (and 

> scope:''openid profile offline_access')

What am i missing?
