### ISSUE TITLE
Include error_description in response

### ISSUE THREAD

**Issue by improwise** [IdentityServer/IdentityServer4#5000]
I have not been able to find any information of error_description and if it is possible to enable some setting and similar and get additional info in responses besides something like:

{
    "error": "invalid_client"
}

Is this something we are supposed to implement our selves? 

(Reason for asking is that we have a client requirement to include not only the error but a short description in response)

**Comment by leastprivilege** [comment]
I can't remember the details - but we decided against this for security reasons. The error codes are standardized. Everything beyond that might leak data to potential attackers...

**Comment by improwise** [comment]
OK, thanks.
