### ISSUE TITLE
MSSQL deployments

### ISSUE THREAD

**Issue by greengumby** [IdentityServer/IdentityServer4#5001]
Hi,

Scenario: Utilising IdentityServer4 within the same database as the bespoke product. (This is forced by the client who do not want to maintain two separate databases.) 

Problem: For the product we use dacpac's to deploy updates however as the schema for IdentityServer is not in the dacpac it attempts to drop it.

I guess when ID4 starts it will auto create the database but then what happens if the data within it had been changed.

Any thoughts on how to handle this situation?  

Thanks
Jeremy

**Comment by brockallen** [comment]
> I guess when ID4 starts it will auto create the database but then what happens if the data within it had been changed.

What makes you think that? Strictly speaking IdentityServer is abstracted away from any stores. We provide an EF implementation of the stores and you must create and maintain that database anyway you see fit.

https://identityserver4.readthedocs.io/en/latest/quickstarts/5_entityframework.html#database-schema-changes-and-using-ef-migrations

https://identityserver4.readthedocs.io/en/latest/reference/ef.html
