### ISSUE TITLE
PromptModes empty on Login

### ISSUE THREAD

**Issue by jamesikanos** [IdentityServer/IdentityServer4#5002]
### Issue / Steps to reproduce the problem

My users are saving the login page into their browser bookmarks including the Authorize Return Url. Because the "Prompt Mode" is stripped out when getting an AuthorizationContext on the Login page I'd like to automatically redirect if the user is already logged in. But, because the prompt modes are not available, I don't know if this is a legacy request (where a login is not required) or a "prompt=login" request.

To reproduce:
1. Login via Authorize Route using prompt=login
1. On Login page, use "IIdentityServerInteractionService.GetAuthorizationContextAsync"
1. Save page to bookmarks
1. Observe that PromptModes is empty
1. Login user

Ideally, I would like PromptModes to be available so I can make a decision myself as to how to handle the request.

https://github.com/IdentityServer/IdentityServer4/blob/3a2d3d373281c38b780b8d51210f0fe9abf8797b/src/IdentityServer4/src/ResponseHandling/Default/AuthorizeInteractionResponseGenerator.cs#L130

**Comment by leastprivilege** [comment]
This has been asked before - but essentially we have to remove the prompt parameter because we would otherwise run into an endless loop. You could save the parameter in a separate parameter I guess.

**Comment by jamesikanos** [comment]
Understood.

Upon further reading, I managed to fix the issue simply by implementing an IAuthorizationParametersMessageStore.

In my login controller I'm validating the ReturnUrl using `GetAuthorizationContextAsync`. If the same login URL is recycled then I redirect the user out to my default client for re-auth.

```csharp
if (!_identityServerInteractionService.IsValidReturnUrl(returnUrl))
{
    return Redirect(_defaultRedirectUrl);
}

var context = await _identityServerInteractionService.GetAuthorizationContextAsync(returnUrl);

if (context == null)
{
    return Redirect(_defaultRedirectUrl);
}
```

Many thanks,
James
