### ISSUE TITLE
Invalid RedirectUri for External Logout when UsePathBase in quickstarts

### ISSUE THREAD

**Issue by gekiss** [IdentityServer/IdentityServer4#5004]
When in middleware replaces context.Request.PathBase, for example UsePathBase(), 

```C#
public void Configure(IApplicationBuilder app)
{
    app.UsePathBase("/first");
}
```
External logout address duplicates PathBase part. https://externalhost/signout?wreply=http://localhost/first/first/Logut...

Solution line
https://github.com/IdentityServer/IdentityServer4.Templates/blob/ecb2f5d5af77b7a64d25881ef1a759b9aa6361e6/src/IdentityServer4Admin/Quickstart/Account/AccountController.cs#L195
replace with:
```C#
string url = Url.ActionLink(action: "Logout", values: new { logoutId = vm.LogoutId });
```

**Comment by brockallen** [comment]
Hmm, I'm not seeing the same thing you are. `Url.Action` in my tests don't add the double "/first/first" to the URLs generated.
