### ISSUE TITLE
How to get IdentityServer4.Storage 4.1.2-0

### ISSUE THREAD

**Issue by yeritsyan** [IdentityServer/IdentityServer4#5008]
### Question
Hi everybody,

I cloned the current repo and wanted to run the Project /src/Host. But I can't install IdentityServer4.Storage 4.1.2-0, because its "Not available in this source". Furthermore, it's not possible to downgrade to Version 4.1.1 (after the installation, 4.1.2-0 is shown instead, but does not work).

Any idea how to fix this? 

Thanks!

**Comment by leastprivilege** [comment]
Check the readme

**Comment by yeritsyan** [comment]
... problem solved (I just wanted to run it in the debugger, didn't expect that I need to run the build-script first)
Thanks!
