### ISSUE TITLE
Is it possible to use Identity Server as a IDP Proxy

### ISSUE THREAD

**Issue by cwoolum** [IdentityServer/IdentityServer4#5012]
### Question
This is a conceptual question and might not be the best approach. I'm currently running into an issue where we have some client side React apps that authenticate with our IDP using implicit flow. We are trying to make the auth flow more secure but the problem is that our IDP doesn't support Code Flow w/PKCE. I would like to keep the flow triggered via the client side for a better user experience (refresh session without redirect). My thought was that I could use Identity server as a proxy to execute a code flow with a `client_secret`. 

From my research, IdentityServer always creates its own tokens and you have the ability to manipulate them with information from the external provider. My question is, is it possible to use the `id_token` and `access_token` from the external provider as the one used by IdentityServer so that they would be returned back to the client app? All of the services we call use these tokens and it would be nice to not have to make any changes to them to improve security of our client side apps.

**Comment by brockallen** [comment]
Yep, a very common pattern: https://identityserver4.readthedocs.io/en/latest/topics/federation_gateway.html

**Comment by cwoolum** [comment]
Aaah, thanks for the follow up! I had read through that before I posted this question but it seemed like IdentityServer would create it's own `id_token` and `access_token` for this scenario. My intent is to return the tokens from my external provider after the server side code flow is complete.

**Comment by brockallen** [comment]
> My intent is to return the tokens from my external provider after the server side code flow is complete.

Why is that necessary? That defeats the purpose of the federation gateway to abstract away the external providers.

**Comment by cwoolum** [comment]
The point of my question wasn't to use a federation gateway; it was to create a proxy that could support a code flow w/ secret since our IDP only supports implicit and not code flow w/PKCE. My hope was to just do this to our client applications so that we don't need a major change for all of our API's.
