### ISSUE TITLE
Token introspection Basic authorization breaks when RFC 8707 resource names are used

### ISSUE THREAD

**Issue by gergelyGcsikvari** [IdentityServer/IdentityServer4#5013]
### Issue / Steps to reproduce the problem

1. Resource definition:
`new ApiResource
            {
                Name = "https://foo.bar/MyResource",` _//see https://tools.ietf.org/html/rfc8707, section 2_
`               Scopes = new List<string>() {"MyResource.read", "MyResource.write"},` _//as we do not have separate resource indicator in place_
`                ApiSecrets = new List<Secret>() { new Secret("secret".Sha256()) },
            };`
2. Request Access token scope is specified as "MyResource.read"
3. call /connect/introspect
`Authorization Basic aHR0cHM6Ly9mb28uYmFyL015UmVzb3VyY2U6c2VjcmV0` _//decoded base64: "https://foo.bar/MyResource:secret"_

Result: 401 authorization fails

Reason I found is that the incoming string is split at the first colon which results "https" which is obviously not matching to the stored resource names.
https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Validation/Default/BasicAuthenticationSecretParser.cs, line 87

Is my finding valid or am I missing some concept?

**Comment by leastprivilege** [comment]
OAuth is not using "standard" basic authentication encoding.

https://github.com/IdentityModel/IdentityModel/blob/5ca6e0983a/src/Client/BasicAuthenticationOAuthHeaderValue.cs#L31-L40

**Comment by gergelyGcsikvari** [comment]
Oh, I get your point. I should have (also) spotted this at https://github.com/IdentityServer/IdentityServer4/blob/33b879ffb3f08e18aa7929d610bfa101d51dad10/src/IdentityServer4/src/Validation/Default/BasicAuthenticationSecretParser.cs#L115

**For the readers only:** before making the concatenation of the resource name with the secret escaping to be done on both values.
`Uri.EscapeDataString(value).Replace("%20", "+");`
