### ISSUE TITLE
The SSL connection could not be established, see inner exception

### ISSUE THREAD

**Issue by Allaev1** [IdentityServer/IdentityServer4#5014]
Hey guys. 

Exception message - System.Net.Http.HttpRequestException: 'The SSL connection could not be established, see inner exception.'
Inner exception 
IOException: The handshake failed due to an unexpected packet format.

This exception was originally thrown at this call stack:
    System.Net.Security.SslStream.StartReadFrame(byte[], int, System.Net.AsyncProtocolRequest)
    System.Net.Security.SslStream.PartialFrameCallback(System.Net.AsyncProtocolRequest)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Net.Security.SslStream.ThrowIfExceptional()
    System.Net.Security.SslStream.InternalEndProcessAuthentication(System.Net.LazyAsyncResult)
    System.Net.Security.SslStream.EndProcessAuthentication(System.IAsyncResult)
    System.Net.Security.SslStream.EndAuthenticateAsClient(System.IAsyncResult)
    System.Net.Security.SslStream.AuthenticateAsClientAsync.AnonymousMethod__65_1(System.IAsyncResult)
    System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(System.IAsyncResult, System.Func<System.IAsyncResult, TResult>, System.Action<System.IAsyncResult>, System.Threading.Tasks.Task<TResult>, bool)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

This exception was thrown when I was working with Quickstart1: Protecting an API using Client Credentials. When client do request to API such exception is thrown. If I do HTTP exception is not thrown. SSL is not enabled on my API. URL address of my API - https://localhost:6001. API runs on IIS Express.

**Comment by leastprivilege** [comment]
You cannot run HTTPS on this port in IIS Express. You would need to use something like > 44300.

**Comment by Allaev1** [comment]
Oh got it. So the only way to run HTTPS on IIS is Enable IIS and access API through SSL port am I wright?
