### ISSUE TITLE
root build folder program.partial   prefix  const string  missing 

### ISSUE THREAD

**Issue by soheilbj** [IdentityServer/IdentityServer4#5015]
in Program.Partial.cs for build project get an error missing "Prefix"  ive add this line of code from another directory

**Comment by leastprivilege** [comment]
What exactly is the issue?

**Comment by soheilbj** [comment]
hi
on build on pure project from github get error from your build project , in
partial program file not passed parameter to program main files to build

**Comment by leastprivilege** [comment]
check the usage in our build script - that's how it is supposed to work...
