### ISSUE TITLE
Cannot see custom claim in accessToken

### ISSUE THREAD

**Issue by h33t92** [IdentityServer/IdentityServer4#5021]
Hey, Identity noob here..
I am trying to get a custom claim in the access_token but not getting it..

In the authorization server :
1. for one of my ApiResources I have defined a test claim called "test.claim" by using 
new ApiResource("ApiTest", new string[] { "test.claim" })

2. Configured a new client with AllowedScopes { "ApiTest" }

3. Seeded a user in Program.cs
userManager.AddClaimAsync(user, new Claim("test.claim", "big.claim"))
                    .GetAwaiter().GetResult();

In the Client:
1. in the oidc configuration in Startup.. I do

         services.AddAuthentication(config =>
                {
                    config.DefaultScheme = "Cookie";
                    config.DefaultChallengeScheme = "oidc";
                })
                .AddCookie("Cookie")
                .AddOpenIdConnect("oidc", config =>
                {
                    config.Authority = "https://localhost:5001/";
                    
                    config.ClientId = "client_id";
                    config.ClientSecret = "client_secret";
                    
                    config.SaveTokens = true; 

                    config.ResponseType = "code";
                    
                    config.ClaimActions.MapUniqueJsonKey("Mani.I", "man.i");
                 
                    config.ClaimActions.DeleteClaim("amr");
                    config.ClaimActions.DeleteClaim("s_hash");
                    config.GetClaimsFromUserInfoEndpoint = true;
                    config.Scope.Clear(); 
                    config.Scope.Add("openid");
                    config.Scope.Add("rc.scope");
                    config.Scope.Add("ApiTest");                  
                });

But im still not getting the "test.claim" in the access Token.. but i do see "ApiTest" as a scope..
Am i missing something here?
Thanks

**Comment by gabrielbarceloscn** [comment]
I guess you should map this custom claim too:  

```
config.ClaimActions.MapUniqueJsonKey("test.claim.mapped", "test.claim");
```
