### ISSUE TITLE
Add usercode and url to DeviceAuthorizationSuccessEvent

### ISSUE THREAD

**Issue by Brunni** [IdentityServer/IdentityServer4#5022]
I want to show a notification on my main application, when a new device registers via the device workflow.

In this notification, I want to allow the user to directly open the browser to access the IdS-Page to allow this device.

For this, I implemented a custom event sink (IEventSink) and wait for the DeviceAuthorizationSuccessEvent to be fired.
When it is fired, I can create the notification.

But: I cannot include the URL because I would need the URL or at least the usercode to send the user to the correct page.

My suggestion:
Adding the user code, VerificationUri and VerificationUriComplete would allow this use case.

**Comment by leastprivilege** [comment]
why is this a bug?

**Comment by Brunni** [comment]
I gutess it is not a bug. Does this mean, that PR won't get merged because of the current situation, right?

**Comment by leastprivilege** [comment]
We need to discuss this internally. I just wondered why you filed a bug...
