### ISSUE TITLE
Setting JWT Typ at a client level - is it possible?

### ISSUE THREAD

**Issue by parkinsona** [IdentityServer/IdentityServer4#5025]
### Question
We've been using IdentityServer4 for some time and recently updated to version 4.1
We ran into the issue with legacy webapis not being able to decode the header because the type had changed from JWT to at+jwt.
One solution for us is to set IdentityServerOptions like:
"AccessTokenJwtType": "JWT",
"EmitStaticAudienceClaim": true

While this is ok for now, going forward I'm not sure this is ideal. There is only one of our webapis that has this issue because it is older. I'd like to have identity server default to at+jwt, but have the type to be set at a client level?

Is there a way to achieve this?

Another solution would be to update the webapi to allow it to set the jwt direcly, but I think it'd be nice if Idsvr gave you that flexibility.

### Minimal working example

The current webapi config looks like this:
```csharp
app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = Properties.Settings.Default.AuthBaseAddress,
                ValidationMode = ValidationMode.Local,
                RequiredScopes = new[] { "xxxx", "yyy" },
                 
            });
```

**Comment by leastprivilege** [comment]
Only by implementing your own token creation service - e.g. by deriving from `DefaultTokenCreationService`.

**Comment by TravisTX** [comment]
I faced the exact same issue today.  Thanks @leastprivilege for the information!

@parkinsona Here is my solution:

```
    public class JwtTokenCreationService : DefaultTokenCreationService
    {
        public JwtTokenCreationService(
            ISystemClock clock,
            IKeyMaterialService keys,
            IdentityServerOptions options,
            ILogger<JwtTokenCreationService> logger)
            : base(clock, keys, options, logger)
        {
        }

        public override async Task<string> CreateTokenAsync(Token token)
        {
            if (token.Type == IdentityServerConstants.TokenTypes.AccessToken &&
                token.ClientId == "TrinityClientImplicit")
            {
                token.Type = "JWT";
            }

            return await base.CreateTokenAsync(token);
        }
    }
```

and then in your dependency injection:
```
services.AddTransient<ITokenCreationService, JwtTokenCreationService>();
```

**Comment by parkinsona** [comment]
Thanks @leastprivilege and @TravisTX .. This was exactly what I was after. I extended mine  a little further to also inject a list of client Ids so it was a little more flexible for my needs. Ideally, I would have liked to extend the Client to include a new option, but this was all I had time for today.
