### ISSUE TITLE
React Server-Side Rendered App as Login UI for IdS

### ISSUE THREAD

**Issue by mdrgeniebelt** [IdentityServer/IdentityServer4#5026]
So my question is more about your people opinion about the following solution:

ASP .NET Core app with Identity Server with login/logout etc UI with server-side rendered React. I know that most of people will ask 'why do you want to complicate your life like that, just use MVC and Razor pages'...I don't want to, but I have very persistent people in my company that would like everything to be in React so that we can easily share react components.

Looking for solutions I've found this issue: https://github.com/IdentityServer/IdentityServer4/issues/3181 and for obvious reason we don't want to use Resource Owner Password Credentials Grant Type. 

Do you think it is possible without exposing ourselves to issues with security of such solution? Would SSR react be as secure as Razor pages? Any issues that you can think of?

Would appreciate a bit of your insight.

**Comment by brockallen** [comment]
Make your UI anything you want, as long as it triggers the right ASP.NET Core cookie authentication handler to emit the cookie so that IdentityServer can authenticate requests.
