### ISSUE TITLE
Client cannot request OpenID scopes in client credentials flow

### ISSUE THREAD

**Issue by JulienM28** [IdentityServer/IdentityServer4#5027]
I'm trying to get an access toekn from Postman.

```csharp
 new Client
            {
                Enabled=true,
                ClientId="58522CA1C8124117BB5F90016DDE8ED0",
                ClientName="Postman Test client",
                ClientSecrets={
                    new Secret("17E6382F847E47839EC3FE9ACE59271FC3B6B16F84FB41C5B34C56B20389A02E".Sha256())
                },
                AllowedGrantTypes=GrantTypes.ClientCredentials,
                AllowOfflineAccess=true,
                AllowedScopes={"toto_client"},
                RequireClientSecret=true,
                RequireConsent=false,
                AllowAccessTokensViaBrowser=true,
                EnableLocalLogin=true,

            }
```
Postman is set like this:
![image](https://user-images.githubusercontent.com/23618436/98579232-9db5cc80-22be-11eb-9e67-15f773f83d7b.png)

And I get this error:
[Error] IdentityServer4.Validation.TokenRequestValidator
Client cannot request OpenID scopes in client credentials flow{"clientId": "58522CA1C8124117BB5F90016DDE8ED0"}, details: {"ClientId": "58522CA1C8124117BB5F90016DDE8ED0", "ClientName": "Postman Test client", "GrantType": "client_credentials", "Scopes": "toto_client", "AuthorizationCode": "********", "RefreshToken": "********", "UserName": null, "AuthenticationContextReferenceClasses": null, "Tenant": null, "IdP": null, "Raw": {"grant_type": "client_credentials", "scope": "toto_client"}, "$type": "TokenRequestValidationLog"}

I don't understand why, cause I assume "toto_client" isn't an openid scope.

Thanks

**Comment by leastprivilege** [comment]
Please show us your scope definition.

**Comment by JulienM28** [comment]
new IdentityResource("toto_client", new List<string>{
                    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress",
                    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname",
                    "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
                 })

**Comment by JulienM28** [comment]
I also tried with this:

```csharp
new IdentityResource("toto_client", new List<string>{
                    "toto_client_nom",
                 })
```

But no way.

**Comment by JulienM28** [comment]
Ok I messed something yesterday after doing tons of tests.

I didn't tried Client with ApiScope I think, I assume I just tried ApiRessource with ApiScope.

Whatever it works 

```csharp
new ApiScope{
Name="toto_api",
DisplayName="Api of Toto",
UserClaims ={ JwtClaimTypes.Email },
} 
```

My apologies.

Thanks for your time.
