### ISSUE TITLE
Microsoft ships IdentityServer4 with their .NET 5 templates? Where?

### ISSUE THREAD

**Issue by JoeMarkov** [IdentityServer/IdentityServer4#5031]
### Question
I see in it being mentioned in many places that Microsoft will ship IdentityServer4 with their .NET 5 templates. Cool, but where and how and what templates? 

I updated to latest Visual Studio 2019 (16.8.0, freshly updated after the .NET 5 release) and tried to do **File->New Project** to see where IdentityServer would show up, but I didn't find any places.

After some googling I also found this namespace and NuGet package **Microsoft.AspNetCore.ApiAuthorization.IdentityServer**

Can anyone please help me understand:
* Where are these template?
* When should I use them? 
* Where can I read more about them?
* Why should I use the Microsoft.AspNetCore.ApiAuthorization.IdentityServer packages instead of IdentityServers own packages?

**Comment by leastprivilege** [comment]
This issue would be better in a Microsoft repo. But my understanding is this

* just like before IdentityServer is part of the Angular/React templates when you choose the "Individual" option for authentication
* it is included in the Blazor WASM template. Probably also when authentication is enabled (never tried it).

**Comment by JoeMarkov** [comment]
Thanks for the clarification!
