### ISSUE TITLE
How to allow cookieless authentication

### ISSUE THREAD

**Issue by diogonborges** [IdentityServer/IdentityServer4#5032]
### Question
Is it possible to allow cookieless authentication? If so, how? 
Context: IdentityServer won't allow login to proceed with on a mobile app on a phone which has the cookies disabled.
Upon investigation I've noticed the Asp Net is responsible for some cookies: AntiForgery and Session.
In theory the OIDC wouldn't actually require a cookie to be set, right? Would this be completely focused on the Asp Net side?

Is it possible to override 

There is _some_ info here but without closure: https://github.com/IdentityServer/IdentityServer4/issues/4277

This is a silly quest, i know, but we're trying to get a spike to see how would this be done and at what cost. In parallel we're doing customer education, of course.

**Comment by dIeGoLi** [comment]
How could a client prove that he is authenticated without having a authentication cookie? 
OIDC does not require a cookie to serve tokens on token endpoint. But how to do a user authentication and save that state without a cookie?

**Comment by diogonborges** [comment]
That, even being overkill would have to be handled with other means, like storage, and it might mean that we would have to go down the route of only supporting SPAs...

**Comment by brockallen** [comment]
Cookieless schemes have been implemented by frameworks in the past (including ASP.NET) and it turns out they're less secure than allowing cookies. From a consumer perspective I can sort of understand the desire to block cookies, but it turns out the cookieless is less secure, because they typically put the session id in the URL and that's fraught with a whole lot of other secure issues.

**Comment by leastprivilege** [comment]
To add to this:

In IdentityServer we do not rely on the authentication **cookie** - we rely on the asp.net core authentication session. This is implemented by ASP.NET in using cookies by default. You could replace the cookie handler with your own implementation.

But as Brock said - it is very hard to implement this securely without cookies.

**Comment by diogonborges** [comment]
Thank you both for your answers! Made us reflect and it's re-assuring to know we're not going down a rabbit hole!

Cheers

**Comment by vai** [comment]
To aid 'searchability', this was a question we were investigating with a view to supporting mobile applications using our IdentityServer, particularly iOS with cookies disabled entirely.
