### ISSUE TITLE
Switch user without re-authenticating?

### ISSUE THREAD

**Issue by RedaAouad** [IdentityServer/IdentityServer4#5034]
Hi,

Is there a way to have 2 users authenticated at the same time in one (angular) client app? The idea is to enable the client app to switch between the 2 (previously-authenticated) users without logout/login.

Thanks
Reda

**Comment by leastprivilege** [comment]
That's a client app concern.

IdentityServer does not support multiple concurrent sessions.

**Comment by dIeGoLi** [comment]
You could store the tokens of each users in your app. But how can it be safe to switch between two users without login logout in the same app?
