### ISSUE TITLE
Endpoint validation - why hostname validation is needed and how to cope with changes in endpoints hosts?

### ISSUE THREAD

**Issue by shaisherman** [IdentityServer/IdentityServer4#5036]
Hi,

In the DiscoveryDocumentResponse->ValidateEndpoints, what is the purpose of the hostname validation for all endpoints? 

In several cases, the endpoints hosts are different from the discovery URL host. In these cases, the discovery will not pass the endpoint validation. If the "allowed hosts" will be configured on the DiscoveryPolicy, it still could fail in case that the identity provider will add a new endpoint. 

For example, in google, the discovery URL is "https://accounts.google.com/.well-known/openid-configuration" but a lot of the endpoints configured with different hosts like for example:
 "token_endpoint": "https://oauth2.googleapis.com/token" and  "userinfo_endpoint" : "https://openidconnect.googleapis.com/v1/userinfo". 

In this example, Google may also add new additional endpoints with different hostnames and cause the discovery endpoint validation to fail.

_My questions are_:
1. What are the best ways to cope with that issue without damaging security? 
2. What is the reason for using it?  Why the AuthorityValidationStrategy is not enough? 

Thanks for your support,
Shai

**Comment by leastprivilege** [comment]
wrong repo. Please use IdentityModel.
