### ISSUE TITLE
Logging in on existing session causes 400 error

### ISSUE THREAD

**Issue by joshbinney** [IdentityServer/IdentityServer4#5037]
My apologies if this has already been covered.

It seems if you log in over the top of an existing session then the identity server middleware throws a 400 error. 
The scenario to cause this would be a user with several IS tabs open has their session expire, and so has the login screen on several tabs. If you log into one, it will work as usual, but when going to another tab and clicking login the server throws a 400 back. You can demo this behavior here:

https://demo.identityserver.io/grants

Before logging in, open two tabs of this link so you have two login pages. Login to one with username bob and pw bob, and after successful login do the same on tab 2. 

This case is admittedly rare but I have had it happen to me and others here without looking for it, particularly when a session has expired and the browser is reopened, causing it to auto load several tabs which will load login screens.

Hope you can help!

**Comment by leastprivilege** [comment]
Sounds like antiforgery - you probably can repro this exact behavior on a plain asp.net core app with a login screen.

**Comment by joshbinney** [comment]
Thanks, if this is an asp.net issue, do you know where I can contact MS for support on this? Surprised this hasn't been addressed before.

**Comment by leastprivilege** [comment]
@blowdart

**Comment by blowdart** [comment]
It has been addressed, just not in a way you would like. We specifically don't support you switching from anonymous to logged in in multiple tabs. This is a design decision, to link CSRF tokens to a logged in user, and not one that will change. I'd say exactly the same thing if you opened this in the [asp.net repo](https://github.com/dotnet/aspnetcore/issues/)

Dom you can close this.

**Comment by joshbinney** [comment]
@blowdart fair enough. Is there a way to override or intercept the 400 so that we are not left with a plain error page?

**Comment by brockallen** [comment]
> @blowdart fair enough. Is there a way to override or intercept the 400 so that we are not left with a plain error page?

In the past I've written app-side exception handing code to detect this scenario and show something more user friendly.
