### ISSUE TITLE
The AuthorizeInteractionResponseGenerator.ProcessConsentAsync method fails because it is using the Scope DisplayName for comparison 

### ISSUE THREAD

**Issue by alanhoman** [IdentityServer/IdentityServer4#5038]
When using the Quickstart and Require Consent is true, the processing of user consent fails on scopes such as openid and offline_access because their DisplayName is different than the Value.  The issue is on line 295 of ResponseHandling -> Default -> AuthorizeInteractionResponseGenerator ->ProcessConsentAsync where the requiredScopes uses scope.Value and consent.ScopesValuesConsented uses scope.DisplayName.  Here is the line:
295: var valid = requiredScopes.All(x => consent.ScopesValuesConsented.Contains(x));

This is when using the QuickStart ConsentController and the user is prompted to consent.  One the web page, it displays **Your user identifier** for openid and **Offline Access** for offline_access.  These display names are passed into consent.ScopesValuesConsented and fail because requiredScopes contains the value, not the DisplayName

**Comment by brockallen** [comment]
>  The issue is on line 295 of ResponseHandling -> Default -> AuthorizeInteractionResponseGenerator ->ProcessConsentAsync where the requiredScopes uses scope.Value and consent.ScopesValuesConsented uses scope.DisplayName.

Can you provide a link to the line in the repo where DisplayName is used, not Name?

**Comment by alanhoman** [comment]
After debugging further I discovered that I had an old _ScopeListItem.cshtml in the Consent folder which was overriding the correct one in the Shared directory.  There is no issue, so I am closing this.  Sorry if I wasted any of your time on this.
