### ISSUE TITLE
SHA256-Sum of Certificate Thumbprints

### ISSUE THREAD

**Issue by JulianHBuecher** [IdentityServer/IdentityServer4#5045]
Good evening all together,

during the last weeks and months I was looking at the Mutual TLS topic, did all your tutorials and establish a working test example with deployment in AKS Kubernetes.

After migration to .NET 5 a problem regarding to cnf-Claim Validation occurred... 

Short example:
The Thumbprint of my certificate is:
49BA0325A9FD2BFD1AD578709F200C0FB1F43C59
... and the according SHA256 sum:
d12c93767abd47ffa30cf0406b29115e53aba80e84d447441e5a55b7deac5de3

By sending these to my IdentityServer, it gives me the following token:
```json
{
   "alg":"RS256",
   "kid":"4DE77A63702D067E9C8BC9FA0B355F47",
   "typ":"at+jwt"
}{
   "nbf":1606150901,
   "exp":1606154501,
   "iss":"https://identityserver",
   "client_id":"mtls",
   "jti":"C4B5AFE23B96D9CE2C48502691933D21",
   "iat":1606150901,
   "scope":"api1",
   "cnf":{
      "x5t#S256":"n1_m0cxjG1GJkdgJwug4YASdct_-mKBUT5G4vebWwaY"
   }
}
```
I never saw a value like this in the cnf-Claim... and since the upgrade, my server cannot validate the tokens anymore...

Do you know something about this behaviour? Hopefully you could help me here 👍 

Best regards
Julian

**Comment by leastprivilege** [comment]
Interesting. Maybe it would be worth debugging the code on both 3.1 and 5.0 to find out what the difference is.

Also you can give the v5 preview a try
https://www.nuget.org/packages/Duende.IdentityServer/5.0.0-preview.1.6

**Comment by JulianHBuecher** [comment]
Hello @leastprivilege,
thank you for your fast response.
I'll try to figure it out and give you feedback if something pops up 👍 
Have a nice day

**Comment by JulianHBuecher** [comment]
...Got my mistake...
Certificate Authentication / Mutual TLS works fine with .NET 5. Made a proper mistake according to the Forwarded-Header-Policy in my Startup.cs. After adding TLS Termination in my ingress the correct http scheme wasn't used from my backend.

Adding this...
```
services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardLimit = 20;
                options.KnownProxies.Clear();
                options.KnownNetworks.Clear();
                options.ForwardedHeaders = ForwardedHeaders.All;
            });
```
solves the problem.

Now everythings works fine.
Thank you again for your help 👍
