### ISSUE TITLE
I am implementing a custom grant type implementing IExtensionGrantValidator, where can I find an implementation reference? :)

### ISSUE THREAD

**Issue by joslat** [IdentityServer/IdentityServer4#5046]
### Question
I want to implement a custom validation for a user/password request token endpoint.
It should be like the Grant Type "Resource Owner Password", but adding some custom additional checks on some information I store about the user.
I read about it here: http://docs.identityserver.io/en/release/topics/grant_types.html, then I have also read about Extension Grants here http://docs.identityserver.io/en/release/topics/extension_grants.html and implemented it with a class that extends IExtensionGrantValidator.
I figured out that if I was using the default TokenRequest for Password, PasswordTokenRequest and called it with RequestPasswordTokenAsync, no matter the GrantType I set up, this function was setting the grant type to Password ( to OidcConstants.GrantTypes.Password to be exact).

So, I implemented my custom CustomPasswordTokenRequest and RequestCustomPasswordTokenAsync. 

**_I am a bit lost in implementing the IExtensionGrantValidator...  Where  could I find some examples, and more concretely the implementation for the PasswordGrantValidator?_** 

Any help or guidance would be very welcome :) - also feel free to tell me if I did something very stupid... I am like 2 weeks into IdentityServer4 and my previous authentication experience was "old school" cookie based ASP.NET except for two projects with Azure AD...  so learning now thanks to some cool videos from Channel 9, NDC (mostly from the authors themselves) and some courses from Pluralsight and LinkedIn learning)

**Comment by brockallen** [comment]
Here's an example of the mechanics: https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/host/Extensions/ExtensionGrantValidator.cs

**Comment by joslat** [comment]
I got it working, hitting the breakpoints so configuration is good, thanks. :)
Any hint on where can I find the IdentityServer4 code managing the RequestPasswordTokenAsync with its PasswordTokenRequest?
Essentially I am looking for what is managing the "password" grant type token request.

**Comment by leastprivilege** [comment]
Do you mean

http://docs.identityserver.io/en/release/topics/resource_owner.html

?

**Comment by joslat** [comment]
Hi, no, I was wrong. I just needed the Secret, so the documentation was enough. 
Authentication really does require proper understanding or you end up doing the wrong thing over and over... 
Thanks for the help, kindly appreciated!!
