### ISSUE TITLE
A proper way of adding `azp` claim to the id_token

### ISSUE THREAD

**Issue by WinniX** [IdentityServer/IdentityServer4#5048]
### Question
When using a openid connect client library, for example `node-openid-client`, the `id_token` validation is failing, due to a missing `azp` claim. The claim is required in our case, since we have multiple audiences. What is the proper way to include `azp` claim into an `id_token`?

Appreciate any help.

-- Eugene

**Comment by leastprivilege** [comment]
I think you can emit it using your profile services. Multiple audiences in id_token is unusual...

**Comment by WinniX** [comment]
thank you for the quick answer! We will need to override the default claims service, because `FilterProtocolClaims()` is called after `GetProfileDataAsync()`. As a result `azp` claim is filtered out. At least we have a way to go now. 
Will address the multiple audiences question as well.
Thanks again!
