### ISSUE TITLE
Get JwtSecurityHandler from DI?

### ISSUE THREAD

**Issue by bigheadedmonster** [IdentityServer/IdentityServer4#5050]
The use of JwtSecurityHandler seems to diverge from the general use of DI in both Identity Server code and basically everywhere else.

A common thing is to see "var handler = new JwtSecurityHandler()". This should in a setup like Identity Server perhaps be via a DI injected service instead?

**Comment by leastprivilege** [comment]
..and what would be the advantage of that?

**Comment by bigheadedmonster** [comment]
Solving a problem like setting MaximumTokenSizeInBytes as a general configuration in startup.cs via DI .)

(https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenhandler.maximumtokensizeinbytes?view=azure-dotnet)
