### ISSUE TITLE
Error Redirect Callback

### ISSUE THREAD

**Issue by borisgr04** [IdentityServer/IdentityServer4#5052]
I have a client in angular on port 8050 set to connect to the identityserver server on port 8070.
Angular client correctly redirected to IS4 server on 8070 correctly. I log in with a valid username and the IS4 redirects to a wrong URL.
So:

**1. FrontEnd Redirect Correct: http: // localhost: 8050/Archivo/login**

Right.

**2. Login in IS 4 Correct**

http: // localhost: 8070 / identity / Account / Login? ReturnUrl =% 2Fidentity% 2Fconnect% 2Fauthorize% 2Fcallback% 3Fclient_id% 3DFileInventoryFrontTest% 26redirect_uri% 3Dhttp% 253A% 252F% 252Flocalhost% 253A80h50% 252Flocalhost% 253A80h50% 252Flocalhost callback% 253A80h50% 252responive callback % 2520token% 26scope% 3Dopenid% 2520profile% 2520email% 2520FileInventory% 26state% 3D956d8cc74ae64346945da6bd86ee5a95% 26nonce% 3D46f7b13bb9d94456b77acd0e85185481

**3. IS4 wrongly redirects to**
http://localhost:8070/Archivo/auth-callback#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkNGOUM0N0E2NTM2MDFEMkYxRDlGNTREM0IxQkE4NTYyNkU5RkM3RDkiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJ6NXhIcGxOZ0hTOGRuMVRUc2JxRlltNmZ4OWsifQ.eyJuYmYiOjE2MDY2MDcwODUsImV4cCI6MTYwNjYwNzM4NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDcwL2lkZW50aXR5IiwiYXVkIjoiYXJjaGl2b0ludmVudGFyaW9Gcm9udFRlc3QiLCJub25jZSI6IjQ2ZjdiMTNiYjlkOTQ0NTZiNzdhY2QwZTg1MTg1NDgxIiwiaWF0IjoxNjA2NjA3MDg1LCJhdF9oYXNoIjoiZWdNWm83TW5LUm5vZDZXbFExWHRWQSIsInNfaGFzaCI6IlQ5TGo5aFdxZGEtVlhwWTkweDF3dEEiLCJzaWQiOiJYQUNtbXJrOU9MOUhkN2RPaU05NHVnIiwic3ViIjoiMTEyNmU1ZTItOTYzZi00ZjA4LWFhY2ItY2I3MTRiODdlODA1IiwiYXV0aF90aW1lIjoxNjA2NjA3MDg1LCJpZHAiOiJsb2NhbCIsImFtciI6WyJwd2QiXX0.jQUV9KnzC0eqXr37DyXLuXOlsk-eA4_-N_29x-sJMdxUOcxjSJkcwZSzNLxJBO44SPSVH7usZJ3VO2Su-UGeOH_8As-8yvo85XyKdzmOAggeLjpA-P7J96TpnO2asyolw51ChXLYBAoRp_1vYCc90rMT1a1q0yTvkILeeA8hFTvGjV4aTUNhxypNqgE7WUov_ib4HnUmPsncugxN7l8yTFDNoAL4Y4sDLvsG8X4-rt8rTeW0B9GiLG8AJC1doO-q4oUl-Wo_BNXPIpYVYpaA2dWqcLolbhFRkuCtObKcT2hNOut_NQ4Pf1pW-d2aw5-D-CPFtV-ZRN2nZ9A7VwVl9dXqWnSgsBpBtYKa55X6jEiq22EfvoQS1gzCqc26ogLG9xlGXIgugN3a-0cVQP9HaDDUW8ZLsp1Wc1zy-6sGVFUjXERIHExAeVfAUEq-G9_Fv9ooCo7EsGJcfKuqqEc41gxEqqBMXwwhG30slYtO9RLgQDQma0Kaaw6DIf29Vwr2WmoTy0zga9nfgfy_ytZ49sep_N2f73c34eEHzdNhdzR8wVFw02TeZEe2oTwiWy4FhF1XbCBMJmgbgEXy4ovifPvoqrkiSQQyZHHBmWcyYgEwvdphSvezPXw6R651c2IoaRtzGwGJd5gPZzy_tV7QDDLwWIEZ7nEN9Vzg4UJ92hE&access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IkNGOUM0N0E2NTM2MDFEMkYxRDlGNTREM0IxQkE4NTYyNkU5RkM3RDkiLCJ0eXAiOiJhdCtqd3QiLCJ4NXQiOiJ6NXhIcGxOZ0hTOGRuMVRUc2JxRlltNmZ4OWsifQ.eyJuYmYiOjE2MDY2MDcwODUsImV4cCI6MTYwNjY5MzQ4NSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDcwL2lkZW50aXR5IiwiYXVkIjoiQXJjaGl2b0ludmVudGFyaW9BcGkiLCJjbGllbnRfaWQiOiJhcmNoaXZvSW52ZW50YXJpb0Zyb250VGVzdCIsInN1YiI6IjExMjZlNWUyLTk2M2YtNGYwOC1hYWNiLWNiNzE0Yjg3ZTgwNSIsImF1dGhfdGltZSI6MTYwNjYwNzA4NSwiaWRwIjoibG9jYWwiLCJBc3BOZXQuSWRlbnRpdHkuU2VjdXJpdHlTdGFtcCI6IkdBVFhSS1FBV1A3SlRMMlJESVNBMk9KUjQyNlRORkpGIiwicm9sZSI6WyJQcmVzdXB1ZXN0b0FwaV9BcHJvcGlhY2lvbk1vZGlmaWNhY2lvblRyYXNsYWRvIiwiUHJlc3VwdWVzdG9BcGlfR2FzdG9zQXByb2JhY2lvblNvbGljaXR1ZENkcCIsIkNvbnRyYXRhY2lvbkFwaV9Db250cmF0aXN0YSIsIkNvbnRyYXRhY2lvbkFwaV9Db250YWJpbGlkYWRBY2VwdGFySW5mb3JtZXNTdXBlcnZpc2lvbiIsIklkZW50aXR5QXBpX1NlZ3VyaWRhZCIsIkNvbnRyYXRhY2lvbkFwaV9Db250YWJpbGlkYWRJbmZvcm1lc1N1cGVydmlzaW9uQXByb2JhZG9zIiwiUHJlc3VwdWVzdG9BcGlfQXByb3BpYWNpb25Nb2RpZmljYWNpb25BZGljaW9uIiwiQ29udHJhdGFjaW9uQXBpX0NvbnRhYmlsaWRhZFJlZ2lzdHJhclJwIiwiQ29udHJhdGFjaW9uQXBpX1VuaWRhZENvbnRyYXRhY2lvbkdlc3Rpb25Db250cmF0b3MiLCJDb250YWJpbGlkYWRBcGlfUmVhbGl6YXJPcmRlbmVzUGFnbyIsIlByZXN1cHVlc3RvQXBpX0dlc3Rpb25WaWdlbmNpYUZpc2NhbCIsIlByZXN1cHVlc3RvQXBpX0dhc3Rvc0VsYWJvcmFjaW9uUnAiLCJDb250cmF0YWNpb25BcGlfRWRpdGFyUHJvY2Vzb3NDb250cmF0YWNpb24iLCJQcmVzdXB1ZXN0b0FwaV9HYXN0b3NTb2xpY2l0dWRDZHAiLCJQcmVzdXB1ZXN0b0FwaV9BcHJvcGlhY2lvbkluaWNpYWxJbmdyZXNvcyIsIkNvbnRyYXRhY2lvbkFwaV9HZXN0aW9uVGVyY2VybyIsIkNvbnRyYXRhY2lvbkFwaV9Fc3R1ZGlvUHJldmlvQ29uc3VsdGFQb3JOdW1lcm9Qcm9jZXNvIiwiQ29udHJhdGFjaW9uQXBpX0Zpcm1hckNvbnRyYXRvcyIsIlByZXN1cHVlc3RvQXBpX0VqZWN1Y2lvbiIsIkNvbnRhYmlsaWRhZEFwaV9HZXN0aW9uT3JkZW5lc1BhZ28iLCJDb250cmF0YWNpb25BcGlfU29saWNpdHVkQ29udHJhdG8iLCJQYXNpdm9zRXhpZ2libGVzQXBpX0FyY2hpdm8iLCJQcmVzdXB1ZXN0b0FwaV9SZXZpc2FyQXByb3BpYWNpb25Nb2RpZmljYWNpb25BZGljaW9uIiwiQXV0b3JpemFjaW9uUGFnb0FwaV9SZXZpc2FyQXV0b3JpemFjaW9uZXNQYWdvIiwiUGFzaXZvc0V4aWdpYmxlc0FwaV9HZXN0aW9uUGFzaXZvcyIsIkNvbnRyYXRhY2lvbkFwaV9FZGl0YXJDb250cmF0byIsIkNvbnRyYXRhY2lvbkFwaV9TdXBlcnZpc29yIiwiQ29udHJhdGFjaW9uQXBpX1VuaWRhZENvbnRyYXRhY2lvbkdlc3Rpb25Tb2xpY2l0dWRlcyIsIkNvbnRyYXRhY2lvbkFwaV9Db250cmF0b3NQb3JKZWZlVW5pZGFkQ29udHJhdGFjaW9uIiwiQ29udGFiaWxpZGFkQXBpX0dlc3Rpb25BdXRvcml6YWNpb25lc1BhZ28iLCJDb250cmF0YWNpb25BcGlfQ29udGFiaWxpZGFkQXNvY2lhY2lvbkVncmVzb3MiLCJDb250cmF0YWNpb25BcGlfUmVwb3J0ZXNEZUNvbnRyYXRvcyIsIlByZXN1cHVlc3RvQXBpX0VqZWN1Y2lvbkluZm9ybWVHYXN0b3MiLCJQcmVzdXB1ZXN0b0FwaV9HZXN0aW9uVW5pZGFkRWplY3V0b3JhIiwiQ29udHJhdGFjaW9uQXBpX0Fwcm9iYXJEb2N1bWVudG9zIiwiQ29udHJhdGFjaW9uQXBpX1JlY3Vyc29zSHVtYW5vc19BcHJvYmFyRG9jdW1lbnRvcyIsIkNvbnRyYXRhY2lvbkFwaV9VbmlkYWRDb250cmF0YWNpb25Fc3RydWN0dXJhZG9yRGVDb250cmF0b3MiLCJQcmVzdXB1ZXN0b0FwaV9HZXN0aW9uRnVlbnRlc0ZpbmFuY2lhY2lvblN1YkZ1ZW50ZSIsIlByZXN1cHVlc3RvQXBpX0Fwcm9waWFjaW9uIiwiQ29udHJhdGFjaW9uQXBpX0NvbnRhYmlsaWRhZEFzb2NpYWNpb25QYWdvcyIsIlByZXN1cHVlc3RvQXBpX0dhc3Rvc0Fwcm9iYWNpb25Tb2xpY2l0dWRScCIsIkNvbnRyYXRhY2lvbkFwaV9SZXBvcnRlTWVuc3VhbERlQ29udHJhdG9zIiwiQ29udHJhdGFjaW9uQXBpX0RhdG9zQmFzaWNvcyIsIkNvbnRyYXRhY2lvbkFwaV9MZWdhbGl6YWRvckNvbnRyYXRvcyIsIkNvbnRyYXRhY2lvbkFwaV9SZXBvcnRlQ29udHJhdGlzdGFzIiwiQXV0b3JpemFjaW9uUGFnb0FwaV9SZWFsaXphckF1dG9yaXphY2lvbmVzUGFnbyIsIlByZXN1cHVlc3RvQXBpX0RhdG9zQmFzaWNvcyIsIkNvbnRyYXRhY2lvbkFwaV9DcmVhckNvbnRyYXRvcyIsIlBhc2l2b3NFeGlnaWJsZXNBcGlfRGF0b3NCYXNpY29zIiwiUHJlc3VwdWVzdG9BcGlfQXByb3BpYWNpb25Nb2RpZmljYWNpb25SZWR1Y2Npb24iLCJDb250YWJpbGlkYWRBcGlfQ2F1c2FyT3JkZW5lc1BhZ28iLCJQcmVzdXB1ZXN0b0FwaV9HZXN0aW9uSW5ncmVzb3MiLCJ0ZXNvcmVyaWFBcGlfUmVhbGl6YXJFZ3Jlc29zIiwiQ29udHJhdGFjaW9uQXBpX0NvbnRhYmlsaWRhZEFzb2NpYWNpb25PcmRlbmVzUGFnbyIsIkNvbnRyYXRhY2lvbkFwaV9Db250YWJpbGlkYWREZXZvbHZlckluZm9ybWVzU3VwZXJ2aXNpb25BY2VwdGFkb3MiLCJQcmVzdXB1ZXN0b0FwaV9HYXN0b3MiLCJDb250cmF0YWNpb25BcGlfRmlybWFzVW5pZGFkQ29udHJhdGFjaW9uIiwiQ29udHJhdGFjaW9uQXBpX1JlY3Vyc29zSHVtYW5vc1NvbGljaXR1ZGVzIiwiUHJlc3VwdWVzdG9BcGlfR2VzdGlvblRlcmNlcm8iLCJQcmVzdXB1ZXN0b0FwaV9HZXN0aW9uRnVlbnRlc0ZpbmFuY2lhY2lvbiIsIkNvbnRyYXRhY2lvbkFwaV9SZXZpc29yRG9jdW1lbnRvcyIsIlByZXN1cHVlc3RvQXBpX0dlc3Rpb25GdWVudGVzRmluYW5jaWFjaW9uT3JpZ2VuIiwiUHJlc3VwdWVzdG9BcGlfUmV2aXNhckFwcm9waWFjaW9uTW9kaWZpY2FjaW9uVHJhc2xhZG8iLCJDb250cmF0YWNpb25BcGlfQW51bGFyQ29udHJhdG9zIiwiUHJlc3VwdWVzdG9BcGlfRWplY3VjaW9uSW5mb3JtZUluZ3Jlc29zIiwiQ29udHJhdGFjaW9uQXBpX0F1eGlsaWFyQWRtaW5pc3RyYXRpdm8iLCJQcmVzdXB1ZXN0b0FwaV9HYXN0b3NFbGFib3JhY2lvbkNkcCIsIkNvbnRyYXRhY2lvbkFwaV9Db25zdWx0YUNvbnRyYXRvUG9yTnVtZXJvIiwiQ29udHJhdGFjaW9uQXBpX0F1dG9yaXphckVzdHVkaW9zUHJldmlvcyIsIlByZXN1cHVlc3RvQXBpX0dlc3Rpb25HYXN0b3MiLCJQcmVzdXB1ZXN0b0FwaV9BcHJvcGlhY2lvbkluaWNpYWxHYXN0b3MiLCJQcmVzdXB1ZXN0b0FwaV9HYXN0b3NBcHJvYmFjaW9uQ2RwIiwiQ29udHJhdGFjaW9uQXBpX0ludGVydmVudG9yIiwiQ29udHJhdGFjaW9uQXBpX0plZmVEZXBlbmRlbmNpYSIsIkNvbnRyYXRhY2lvbkFwaV9DZXJ0aWZpY2FjaW9uZXNDb250cmF0byIsIkFyY2hpdm9JbnZlbnRhcmlvQXBpX0FyY2hpdm8iLCJQcmVzdXB1ZXN0b0FwaV9SZXZpc2FyQXByb3BpYWNpb25Nb2RpZmljYWNpb25SZWR1Y2Npb24iLCJDb250cmF0YWNpb25BcGlfUmVwb3J0ZUJhc2ljb0RlQ29udHJhdG9zIiwiUHJlc3VwdWVzdG9BcGlfR2FzdG9zQXByb2JhY2lvblJwIiwiQ29udHJhdGFjaW9uQXBpX1JlYWxpemFyTW9kaWZpY2F0b3Jpb3MiLCJBcmNoaXZvSW52ZW50YXJpb0FwaV9EYXRvc0Jhc2ljb3MiLCJQcmVzdXB1ZXN0b0FwaV9HYXN0b3NTb2xpY2l0dWRScCIsIkNvbnRyYXRhY2lvbkFwaV9HZXN0aW9uQ29udHJhdG9zUG9ySmVmZURlcGVuZGVuY2lhIl0sInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIiwibmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBieWFzeXN0ZW1zLmNvbS5jbyIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaG9uZV9udW1iZXIiOiItIiwicGhvbmVfbnVtYmVyX3ZlcmlmaWVkIjpmYWxzZSwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFkbWluIiwiZ2l2ZW5fbmFtZSI6IkFkbWluIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIiwiQXJjaGl2b0ludmVudGFyaW8iXSwiYW1yIjpbInB3ZCJdfQ.H-0Y-V4yfaXEfaX3Ma7KjxEbK6IpL4_5lZedvAriDlB89sk25WLWE_t8ZPHDq07GRc1QRVSfGgNkwMyjex5rsCcUC1-_DJbwCIh4ePZqinfl4q9IEF-eZui5gS6Nl1NGyD2AX5yHmJwGqWwNOAM36kWSSWpRAsp-MO6jqfwqjByz9RXw2k0wxH-xoViWdjzdTS3ynxEdn6pG4krwTXWlJ9N-wtGu8J6zdcP2mxKDd_uP3Y5UrwH1spM9_BZdBpfIYSMXFeQGkUeJeeQQwCebeURoQeNnVZFiiD81XlwxWXUigoK3MS0eTvmsPQYxM7ikN6M_v1430R6GR1gO3-E3n9VBiJtGlg19mgriijqrf7Y70eaws14xpwm1k-PcCpanCWEI3sPnBSA2u1yMv5AckqYAwstO7RMLdZCFb0M464cJYOVTEmcs-0MsfIIiQL3rrRLnWG3S7UEPahgLaQmIYAQSO5uYlIeWEEcaX7YvMeHLldkIva8N5ySEROpA3ofQstJncRX4_nX_PDV8KX3QMe8QfoXjPFH1qj5fUGAqCNigvMOxRVOqbL_5tEgyjS8uE0DO8MFgQ2vAVQeXu0c0eF_Ef0xVZId7CILyeI9avc_rDvJuSkLYRpMuEtRndSO-tcrsBmabS4On5ZJganm3JXbHg7O4NcdnrbX9RMx8lVA&token_type=Bearer&expires_in=86400&scope=openid%20profile%20email%20ArchivoInventario&state=956d8cc74ae64346945da6bd86ee5a95&session_state=D7nBs6C8zB04gKZpde0DxVaPNAri-NU9HcI2CN809_4.qDkDxFwJQKkpyyJqwAaksA

**Comment by mcrio** [comment]
You probably have something misconfigured but it's hard to tell based on the provided data. Also, I'd keep an eye on the size of the access token, it looks very big.
