### ISSUE TITLE
Redirecting to different URL dynamically

### ISSUE THREAD

**Issue by joshbinney** [IdentityServer/IdentityServer4#5053]
Hi there,

I have an authorization_code based OWIN client connecting to my identity server 4 app. I have a requirement that I need multiple host addresses. I've set my OWIN client configuration to the usual host uri, and within the redirect to IS notification dynamically changed the redirect uri to another (that is listed in the clientredirecturis table), but I'm getting an error that the redirect uri is incorrect.

I know that the uri is correct because if I set the OWIN config to use this second uri and dont change the return uri dynamically it works like a treat, redirecting to a different host. 

I guess the OWIN client sends its config to IS at some point, which IS uses as the golden ticket of whats allowed. So how can I change this so that I can dynamically set return uris at runtime and have IS just check if it is a valid redirecturi specified in the DB.

Thanks in advance!

P.S. no one seems to ever say it on these forums, so I will - thanks for your FREE software and active support for it!

**Comment by leastprivilege** [comment]
Thanks ;)

When we receive a redirect URI that we think is invalid - there is a log message showing the received URI and the allowed one. Have a look at that. Maybe there is a typo somewhere.

**Comment by joshbinney** [comment]
Heres the error:

```
[10:45:12 Error] IdentityServer4.Validation.TokenRequestValidator
Invalid redirect_uri{"redirectUri": "https://localhost:55555/", "expectedRedirectUri": "https://localhost:44304/"}, details: ......
```

And in my startup on my OWIN client:

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                Authority = "https://localhost:55555/",
                RedirectUri = "https://avayaidentityserverdev.virsae.com/",
            ...............

RedirectToIdentityProvider = context =>
                    {
                        context.ProtocolMessage.RedirectUri = "https://localhost:44304/";
                    ......................
```

It seems if I switch the ports around, so start with 44304 and change to 55555 it works.

**Comment by mcrio** [comment]
@joshbinney  If you need custom logic for validating the redirect URI, you can always write your own validator. See `IRedirectUriValidator`.

**Comment by joshbinney** [comment]
@mcrio, I've seen that and I'm sure it'll do the trick, I just thought this behavior was supported by default and I don't want to go overriding something when I may have just messed up some config :P

**Comment by DickvdBrink** [comment]
But what are the redirect in you client definitions? 
You should have something similar to this:
https://github.com/IdentityServer/IdentityServer4/blob/07898a61dc22ce9a95e5fc5611fa674feac4230e/samples/Quickstarts/3_AspNetCoreAndApis/src/IdentityServer/Config.cs#L50

Did you list all the valid redirect uri's there?

**Comment by joshbinney** [comment]
Yeah I have them listed in my database. The logs show that its getting the correct redirect uris and there's no silly typos. It just seems to be an issue when I dynamically change the redirect uri in OWIN as described above :(
