### ISSUE TITLE
The certificate data cannot be read with the provided password, the password may be incorrect with .NET 5.0

### ISSUE THREAD

**Issue by odinnou** [IdentityServer/IdentityServer4#5057]
### Question
Hello, I am trying to migrate my application with IdsSrv4 from .NET Core 3.1 to .NET 5.0 and I'm in front of a big problem, the exactly same line crash in .NET 5.0, the "opening" of a certificate.pfx (properties **Build action** : Embedded resource & **Copy to output** : copy always)

### Minimal working example. 

```csharp
.AddSigningCredential(new X509Certificate2(appSettings.CertificateFile, appSettings.CertificatePassword))
```

Obviously, I tried with hard coded values to check it was not a settings issue

### Relevant parts of the log file

```
System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
 ---> System.Security.Cryptography.CryptographicException: A certificate referenced a private key which was already referenced, or could not be loaded.
```

Does anyone have this problem?
It's not a IdsSrv4 bug, because its the "new X509Certificate2(...)" statement which cause this crash

Thanks in advance
Kind regards, Rémi

**Comment by leastprivilege** [comment]
@blowdart

**Comment by blowdart** [comment]
I'm on vacation till January so I suggest raising an issue in the .net repo

**Comment by odinnou** [comment]
hello, here the solution : https://github.com/dotnet/runtime/issues/44535 thanks @blowdart
