### ISSUE TITLE
ids4 was not authenticated. Failure message: IDX10222: Lifetime validation failed. The token is not yet valid. ValidFrom: 'System.DateTime', Current time: 'System.DateTime'.

### ISSUE THREAD

**Issue by zqlovejyc** [IdentityServer/IdentityServer4#5058]
Linux reports the following exceptions: Microsoft.AspNetCore.Authentication .AuthenticationHandler`1.AuthenticateAsync : ids4 was not authenticated. Failure message: IDX10222: Lifetime validation failed. The token is not yet valid. ValidFrom: ' System.DateTime ', Current time: ' System.DateTime '.
But windows is normal.

IdentityServer4.AccessTokenValidation -Version 3.0.1
net5.0

**Comment by leastprivilege** [comment]
That typically points to the fact that the system date/time is wrong

**Comment by zqlovejyc** [comment]
> That typically points to the fact that the system date/time is wrong

I checked the system time, which is basically consistent. My token expiration time is set to 3600s. According to the reason, it should not be expired?

**Comment by zqlovejyc** [comment]
> That typically points to the fact that the system date/time is wrong

Synchronization server time problem solved, thank you
