### ISSUE TITLE
How to add AddNegotiate?

### ISSUE THREAD

**Issue by balkarov** [IdentityServer/IdentityServer4#5060]
### Question
Hello.
I am trying implement WindowsAuthentication with IdentityServer4.

I took IdentityServer host project.
I added handler AddNegotaite to Startup:
```c#
services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
                .AddNegotiate();
```

And created WindowsController with `[Authorize]` attribute:
```c#
[Authorize]
public class WindowsController: Controller
{
    [HttpGet]
    public async Task<IActionResult> Challenge(string returnUrl)
    {
        return await ChallengeWindowsAsync(returnUrl);
    }

    private async Task<IActionResult> ChallengeWindowsAsync(string returnUrl)
    {
        var wp = HttpContext.User;
        var props = new AuthenticationProperties
        {
            RedirectUri = Url.Action("Callback", "External"),
            Items =
            {
                { "returnUrl", returnUrl },
                { "scheme", "Negotiate" }
            }
        };

        var id = new ClaimsIdentity("Negotiate");

        // the sid is a good sub value
        id.AddClaim(new Claim(JwtClaimTypes.Subject, wp.FindFirst(ClaimTypes.PrimarySid).Value));

        // the account name is the closest we have to a display name
        id.AddClaim(new Claim(JwtClaimTypes.Name, wp.Identity.Name));

        // add the groups as claims -- be careful if the number of groups is too large
        var wi = wp.Identity as WindowsIdentity;

        // translate group SIDs to display names
        var groups = wi.Groups.Translate(typeof(NTAccount));
        var roles = groups.Select(x => new Claim(JwtClaimTypes.Role, x.Value));
        id.AddClaims(roles);

        await HttpContext.SignInAsync(
            IdentityServerConstants.ExternalCookieAuthenticationScheme,
            new ClaimsPrincipal(id),
            props);
        return Redirect(props.RedirectUri);
    }

}
```

After Windows sign in page redirect to External/Callback.
And authentication crash in Callback method on this line:
```c#
await HttpContext.SignInAsync(isuser, localSignInProps);
```
with error: 

> InvalidOperationException: sub claim is missing
> IdentityServer4.Extensions.PrincipalExtensions.GetSubjectId(IIdentity identity) in PrincipalExtensions.cs, line 81

It crashes because IdentityServer tries create session and crash when it tries get `sub` claim from WindowsIdentity. But WindowsIdentity has not this claim.

How to fix it? I did not find any solution IdentityServer4 + AddNegotiate.

My sample project:
[WinAuth.zip](https://github.com/IdentityServer/IdentityServer4/files/5629560/WinAuth.zip)
Need to go: http://localhost:5002/External/Callback

**Comment by leastprivilege** [comment]
I never tried the Negotiate handler. We only have docs for using IIS - but I guess you would follow the same pattern - e.g. not use the authorize attribute and use ChallengeAsync instead

https://identityserver4.readthedocs.io/en/latest/topics/windows.html

**Comment by balkarov** [comment]
@leastprivilege I need AddNegotiate and Authorize attribute because my project works on Linux (Kerberos protocol). 
Without Authorize attribute AddNegotiate does not work. 
Your example works only on Windows machine.

**Comment by leastprivilege** [comment]
You need to use a cookie handler to create the session - so this must be the default scheme.

Still you can trigger any other handler (e.g. negotiate) via setting the authN scheme on the Authorize attribute or calling ChallengeAsync.

As I said - it is the same pattern as in our docs, just with a different handler.

**Comment by balkarov** [comment]
@leastprivilege 
I'm not sure if I understood you correctly. 
Do you mean that I do not need use AddNegotiate?
Do you have any example?
Because I tried your example `ChallengeWindowsAsync` and it does not work on Ubuntu with kerberos.

**Comment by balkarov** [comment]
@leastprivilege I think you help me!)
I try this:

In startup:
```c#
services.AddAuthentication()
                .AddNegotiate();
```

And I change Authorize attribute to
```c#
[Authorize(AuthenticationSchemes = NegotiateDefaults.AuthenticationScheme)]
```

Please do not close this issue. I need check all and I will answer here again and close issue if all will be ok.

**Comment by balkarov** [comment]
@leastprivilege thank you very much for your help!
