### ISSUE TITLE
Error in identityserver demo - automatic redirect to external provider

### ISSUE THREAD

**Issue by sabbadino** [IdentityServer/IdentityServer4#5062]
https://github.com/IdentityServer/IdentityServer4.Demo/blob/main/src/IdentityServer4Demo/Quickstart/Account/AccountController.cs

provider should be changed to scheme

[HttpGet]
        public async Task<IActionResult> Login(string returnUrl)
        {
            // build a model so we know what to show on the login page
            var vm = await BuildLoginViewModelAsync(returnUrl);

            if (vm.IsExternalLoginOnly)
            {
                // we only have one option for logging in and it's an external provider
                return RedirectToAction("Challenge", "External", new { **provider** = vm.ExternalLoginScheme, returnUrl });
            }

            return View(vm);
        }

should be 

[HttpGet]
        public async Task<IActionResult> Login(string returnUrl)
        {
            // build a model so we know what to show on the login page
            var vm = await BuildLoginViewModelAsync(returnUrl);

            if (vm.IsExternalLoginOnly)
            {
                // we only have one option for logging in and it's an external provider
                return RedirectToAction("Challenge", "External", new { **scheme**= vm.ExternalLoginScheme, returnUrl });
            }

            return View(vm);
        }

**Comment by brockallen** [comment]
fixed, thx
