### ISSUE TITLE
Shouldn't PersistedGrantStore store its data encrypted?

### ISSUE THREAD

**Issue by merijndejonge** [IdentityServer/IdentityServer4#5066]
I noticed that the Data property of PersistedGrant contains all claims and everything as a json object which is stored unencrypted. I was wondering what the security considerations are here to _not_ store this data in encrypted form.

Some of the claims I'm using contain sensitive data and are derived from information the user provides when singing in. I didn't expect to find these unencrypted in my persisted grant database.

Apart from these special claims that I'm using, a hacker who gets access to the persisted grant database finds quite some relevant data, right?

Can you explain this design decision?

**Comment by leastprivilege** [comment]
Doing protection of data by default would have required quite some additional infrastructure - creating keys, storing them securely etc. That's why we decided against it back then.

But I totally agree that this is something additional you might want to do. I would recommend to just use the decorator pattern to layer encryption on top of the existing store to add that feature yourself.

**Comment by merijndejonge** [comment]
Thanks for your answer.

I understand your reasoning. However, shouldn't the documentation more explicitly mention this? I mean, I was just adding the PersistedGrant store stuff by reading the docs without noticing that this stuff gets stored without encryption. I also took as well to realize the potential impact. I think that, like me, many others will just assume that using the provided PersistedGrant EntityFramework stuff is safe. However, I don't think it is as safe as the rest of the system. It feels like a security flaw now. Therefore, adding a warning might not be a bad thing to do.

Then, w.r.t. the implementation. Is it much harder than the stuff for AddSingingCredential? Because, there you seem to already have implemented encryption stuff, which is optional. Couldn't this be done for PersistedGrants as well? By making it optional, the user can opt not to use it. This would have the same effect as it is right now. But if he enables it, by providing a key, the system will encrypt the data?

I'm willing to offer my help to develop this and make it part of IdentityServer. Is that an idea, to co-develop in a way?

**Comment by leastprivilege** [comment]
It is a bit more complicated than that. Simply turning on encryption on that data will break backwards compatibility.

I agree that the docs should mention it - and a sample would be great as well. It could be e.g. done a a grant store that used ASP.NET data protection.

**Comment by merijndejonge** [comment]
Using ASP.NET data protection sounds like a great idea.
Do you have a suggestion about how to use the decorator pattern here, because the default DI of AspNet Core doesn't provide build-in decorator functionality, and the idsrv4 extension method AddOperationalStore doesn't allow for providing a custom IPersistedGrantStore, if I'm not mistaken?

**Comment by brockallen** [comment]
You can copy ours:

https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Configuration/DependencyInjection/BuilderExtensions/Core.cs#L263

**Comment by merijndejonge** [comment]
Then this is a possible implementation. What do you think?

```csharp
    public class ProtectedPersistedGrantStore : IPersistedGrantStore
    {
        private readonly IPersistedGrantStore _persistedGrantStore;
        private readonly IDataProtector _protector;

        public ProtectedPersistedGrantStore(Decorator<IPersistedGrantStore> persistedGrantStore,
            IDataProtectionProvider dataProtectionProvider)
        {
            _persistedGrantStore = persistedGrantStore.Instance;
            _protector = dataProtectionProvider.CreateProtector(typeof(ProtectedPersistedGrantStore).FullName);
        }

        public Task StoreAsync(PersistedGrant grant) => _persistedGrantStore.StoreAsync(grant.Protect(_protector));

        public async Task<PersistedGrant> GetAsync(string key)
        {
            var grant = await _persistedGrantStore.GetAsync(key);
            return grant?.Unprotect(_protector);
        }

        public async Task<IEnumerable<PersistedGrant>> GetAllAsync(PersistedGrantFilter filter)
        {
            var grants = await _persistedGrantStore.GetAllAsync(filter);
            return grants?.Select(x => x.Unprotect(_protector));
        }

        public Task RemoveAsync(string key) => _persistedGrantStore.RemoveAsync(key);
        public Task RemoveAllAsync(PersistedGrantFilter filter) => _persistedGrantStore.RemoveAllAsync(filter);
    }

    internal static class PersistedGrantExtensions
    {
        internal static PersistedGrant Protect(this PersistedGrant grant, IDataProtector protector) =>
            grant.MakeCopy(x => x.Data = protector.Protect(grant.Data));

        internal static PersistedGrant Unprotect(this PersistedGrant grant, IDataProtector protector) =>
            grant.MakeCopy(x => x.Data = protector.Unprotect(grant.Data));

        private static IEnumerable<PropertyInfo> GetProperties(this object obj) => obj.GetType().GetProperties();

        private static T MakeCopy<T>(this T sourceObj, params Action<T>[] initializers) where T : new()
        {
            var targetObj = new T();

            foreach (var property in sourceObj.GetProperties())
            {
                property.SetValue(targetObj, property.GetValue(sourceObj));
            }

            foreach (var initializer in initializers)
            {
                initializer(targetObj);
            }

            return targetObj;
        }
    }
```

**Comment by merijndejonge** [comment]
We can even make use of `ITimeLimitedDataProtector` to limit the lifetime of the encrypted data according to the Expiration property in the grant. 

The protect method then becomes:
```csharp
internal static PersistedGrant Protect(this PersistedGrant grant, ITimeLimitedDataProtector protector) =>
            grant.MakeCopy(x => x.Data = protector.Protect(grant.Data, grant.Expiration ?? DateTimeOffset.MaxValue));
```

Did you have a chance to look at the code already?

**Comment by merijndejonge** [comment]
Would be nice if you could give your opinion about this proposed implementation for more secure storage of grants, such that the issue can be closed with (some sort of a) "confirmed" state.
