### ISSUE TITLE
Order of services.AddIdentityServer() calls stops cookies from being set for none-SSL

### ISSUE THREAD

**Issue by yetanotherchris** [IdentityServer/IdentityServer4#5067]
I've been trying to get the quickstart into a Docker container, alongside a small number of test users. As it's only a test container I don't want the overhead of SSL certificates in the container, so I'm using none-SSL for now.

Something that took me quite a while to figure out is the `/account/login` page would not set the cookies unless SSL was enabled in .NET Core. I thought this may have been a ASP.NET Core restriction, but testing with its starter project this wasn't the case.

It seems to be that the order of my `services.AddIdentityServer()` and `services.AddCookie()` calls, but only if none-SSL is enabled. Have I missed something obvious? Here's my configure method, which works for non-ssl:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews();

    var builder = services.AddIdentityServer(options =>
    {
        options.Authentication.CookieAuthenticationScheme =
            CookieAuthenticationDefaults.AuthenticationScheme;
        options.Authentication.CheckSessionCookieName = "chris_auth";
        options.Events.RaiseErrorEvents = true;
        options.Events.RaiseInformationEvents = true;
        options.Events.RaiseFailureEvents = true;
        options.Events.RaiseSuccessEvents = true;
        options.EmitStaticAudienceClaim = true;
    }).AddTestUsers(JsonConfigReader.Users);

    // in-memory, code config
    var clientsConfig = Configuration.GetSection("clients");
    builder.AddInMemoryIdentityResources(new IdentityResource[]
    {
        new IdentityResources.OpenId(),
        new IdentityResources.Profile(),
    });
    builder.AddInMemoryApiScopes(JsonConfigReader.ApiScopes);
    builder.AddInMemoryClients(clientsConfig);

    var signing = CredentialsHelper.GetSigningCredentials();
    builder.AddSigningCredential(signing);
    
    services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
        .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme,
            options =>
            {
                options.Cookie.Name = "chris";
                options.Cookie.HttpOnly = true;
                options.Cookie.SecurePolicy = CookieSecurePolicy.None;
                options.ExpireTimeSpan = TimeSpan.FromDays(30);
            });
}
```

**Comment by leastprivilege** [comment]
I think this is a SameSite issue. SameSite value of None is not allowed anymore on non-HTTPS.

**Comment by leastprivilege** [comment]
But generally speaking - don't be surprised about ordering problems in ASP.NET Core DI registrations. That's just how it works.

**Comment by yetanotherchris** [comment]
Sorry for the slow response - yes the "None" requiring SSL is the answer. I did a little test and setting the secure policy to "None" is actually ignored by Chrome, it sets it to Lax which I'd assume is fine for almost all authorization setups.

Thanks for the help
