### ISSUE TITLE
How to configure Key on Linux and aspnet core

### ISSUE THREAD

**Issue by maxima120** [IdentityServer/IdentityServer4#5069]
### Question

How do I configure Key on Linux?

The following config works fine on Windows. How do I do the same on Linux (CentOS)?
There is no `certificate store` is there?

### Minimal working example

```json
  "IdentityServer": {
    "Clients": {
      "HelloLinuxAuth": {
        "Profile": "IdentityServerSPA"
      }
    },
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "LocalMachine",
      "Name": "CN=my-demo"
    }
  },
```

**Comment by leastprivilege** [comment]
This seems to be related to Microsoft's IdentityServer integration. Please open an issue on their issuer tracker instead. @javiercn @blowdart

https://github.com/aspnet/aspnetcore/issues

**Comment by maxima120** [comment]
they bounce me to stackoverflow where bunch of random people downvote and close my questions (because they dont understand them/dislike anything microsoft)..
