### ISSUE TITLE
Redesign introspection response generator

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#507]
especially the response...

**Comment by cbeall** [comment]
I'd like to see an enhancement where an equivalent JWT was optionally added to the response. If not that functionality directly, at least the ability to extend the existing functionality without having to replace the entire IntrospectionResponseGenerator.

I made a case for this functionality in #807 with API Gateways. Beyond that, I think it would benefit any situation where reference tokens are being combined with a poor man's delegation scenario. An example of this would be a public facing API that relies on a internal API for authorization. Sending the reference token to the internal API requires an additional introspection step. It would be great to be able to forward a JWT (which could be returned from the original introspection step) from the public API to that internal API.

**Comment by leastprivilege** [comment]
* follow same pattern as the other endpoints
* move all response generation into response generator (including error responses)
* make `IntrospectionResponse` smarter (e.g. aware of JObject etc)

will be a breaking change.

**Comment by leastprivilege** [comment]
see #1001

**Comment by leastprivilege** [comment]
PR done
