### ISSUE TITLE
EmitStaticAudience not found?

### ISSUE THREAD

**Issue by JoeMarkov** [IdentityServer/IdentityServer4#5073]
In the documentation it says here https://github.com/IdentityServer/IdentityServer4/blob/main/docs/topics/resources.rst

`_When using the scope-only model, no aud (audience) claim will be added to the token, since this concept does not apply. If you need an aud claim, you can enable the EmitStaticAudience setting on the options. This will emit an aud claim in the issuer_name/resources format. If you need more control of the aud claim, use API resources._
`

But when I search the source code for **EmitStaticAudience**,  I can't find it.  I guess you mean the EmitStaticAudienceClaim option? 

A suggestion is also to improve the documentation about this more generic audience value, why we have it at all.

"aud" : "[
  "invoiceapi",
  **"https://localhost:6001/resources"**
]",

Also, I would suggest the text also mentions on what options object this property is defined (IdentityServerOptions), I was searching around the client and all the resource objects to try to find it. The page is about resources, so its a bit unclear here.

**Comment by leastprivilege** [comment]
Good ideas! Feel free to send a PR for the docs.
