### ISSUE TITLE
How to configure key material on Linux

### ISSUE THREAD

**Issue by maxima120** [IdentityServer/IdentityServer4#5074]
*Please dont close this outright. I already asked it on aspnet core and they said they simply transfer config to identity server without any mapping.. So **you** should know how to do it*

### Question

How do I configure Key material on Linux?

The following config works fine on Windows. How do I do the same on Linux (CentOS)?
There is no `certificate store` is there?

### Minimal working example

```json
  "IdentityServer": {
    "Clients": {
      "HelloLinuxAuth": {
        "Profile": "IdentityServerSPA"
      }
    },
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "LocalMachine",
      "Name": "CN=my-demo"
    }
  },
```

**Comment by brockallen** [comment]
Do you have the link for the original issue?

**Comment by maxima120** [comment]
no. looks like its been deleted already..
but it must be simple - how do you expect a material key to be configured when you have no `certificate store` ? any example you can give me?

**Comment by leastprivilege** [comment]
I think there is a comparable concept on Linux - but StoreLocation must be User or LocalUser (or whatever they call it). I never used it though.

I typically load my keys from some sort of vault (like KeyVault or HashiCorp Vault).

But since this is Microsoft's abstraction I am surprised, they sent you to us. @blowdart

**Comment by blowdart** [comment]
Again I'm in vacation till January.

**Comment by leastprivilege** [comment]
For that you are pretty quick to respond to mentions on Github :p

**Comment by maxima120** [comment]
his vacation is in the datacentre, next to github racks perhaps? ;)

**Comment by maxima120** [comment]
Ping
