### ISSUE TITLE
Stop certain characters being used in key field for persistent grants in EF Core

### ISSUE THREAD

**Issue by James-Whitfield** [IdentityServer/IdentityServer4#5077]
### Question

I am trying to use EF Core and Cosmos Db with identity server. My persistent grants are failing to be stored to the db due to the key field containing invalid characters. Below is the error. 

```
Unhandled exception: Response status code does not indicate success: 404 Substatus: 0 Reason: (The value 'dbs/inspection-platform/colls/ApplicationDbContext/docs/PersistedGrant%7CoQoCRzsJm/GAhaeAqJQ8X/pOv+ZJqVyFK4oXO5T9SFU=' specified  for query '$resolveFor' is invalid.ActivityId: 6579e6b3-553c-486a-8363-bb8e26f74ad7, Windows/10.0.19041 cosmos-netstandard-sdk/3.3.0).
```
The model which is failing to update.
https://github.com/IdentityServer/IdentityServer4/blob/07898a61dc22ce9a95e5fc5611fa674feac4230e/src/EntityFramework.Storage/src/Entities/PersistedGrant.cs#L13
the key field appears to contain '\\' values which are not support by cosmosdb. [Link to docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.resource.id?view=azure-dotnet).

I dug into your code and it appears that the field is not generated by the server. https://github.com/IdentityServer/IdentityServer4/blob/07898a61dc22ce9a95e5fc5611fa674feac4230e/src/EntityFramework.Storage/src/Extensions/ModelBuilderExtensions.cs#L135

Is it possible to provide a key value generation method or some other way of stopping certain characters from being used as the key field value? Snooping though the code I have not found where the key field is generated/assigned yet so any help would be appreciated.

**Comment by brockallen** [comment]
Off the top of my head, I'd think you could override the storage implementation and convert the key to some other format.
