### ISSUE TITLE
On mutual tls enabled, accessing mtls token endpoint returns ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by muqadar-ali** [IdentityServer/IdentityServer4#5078]
On mutual tls enabled, accessing mtls token endpoint returns ERR_NAME_NOT_RESOLVED in browser. If I try to access it using RequestTokenAsync (sample provided at [https://identityserver4.readthedocs.io/en/latest/topics/mtls.html#refmutualtls](https://identityserver4.readthedocs.io/en/latest/topics/mtls.html#refmutualtls) returns **no host found**).

sample urls (certificate is issued to *.def.com.pk)
-------------
Issuer Uri:  https://abc.def.com.pk/ids
mtls token endpoint: https://mtls.abc.def.com.pk/ids

Please guide me.

**Comment by brockallen** [comment]
Sounds like a DNS issue?

**Comment by muqadar-ali** [comment]
But if I set empty value of options.Mtls.DomainName then url becomes:
https://abc.def.com.pk/ids/connect/mtls/token
And the error i get is 404 not found.
Please guide me how to set up mutual tls and achieve proof of possession tokens using ids4

**Comment by brockallen** [comment]
This is what we have: https://identityserver4.readthedocs.io/en/latest/topics/mtls.html

**Comment by muqadar-ali** [comment]
Thanks but this doesn't help much..
Seems like I have to apply url rewrite from mtls/token to  connect/token.

**Comment by muqadar-ali** [comment]
Rewrite did not work, it starts giving ssl connection error.

**Comment by leastprivilege** [comment]
There are indeed a lot of moving - only a small portion of it is actually IdentityServer related - hosting, routing, X509 etc...

Here's a video - maybe that helps
https://youtu.be/LdY_HPPpxVo?t=2285

**Comment by leastprivilege** [comment]
There are indeed a lot of moving - only a small portion of it is actually IdentityServer related - hosting, routing, X509 etc...

Here's a video - maybe that helps
https://youtu.be/LdY_HPPpxVo?t=2285

**Comment by muqadar-ali** [comment]
I got past the url issue with following settings:
1. Turns out IIS does not have sub domain based settings so I used path based mtls.
2. Path based mtls does not work alone, we need to add following piece of code in startup as well (Events are optional)
Note: ToByteArray is extension method to convert hex string to bytes
`


                 services.AddAuthentication(AuthenticationScheme)
                 .AddCertificate(AuthenticationScheme, options =>
                 {
                     options.AllowedCertificateTypes = CertificateTypes.All;
                     options.RevocationMode = System.Security.Cryptography.X509Certificates.X509RevocationMode.NoCheck;

                     options.Events = new CertificateAuthenticationEvents
                     {
                         OnCertificateValidated = context =>
                         {
                             CustomLogger.Trace("CertificateAuthenticationEvents.OnCertificateValidated", context.HttpContext.TraceIdentifier, "certificate validated, adding claims from certificate");

                             context.Principal = Principal.CreateFromCertificate(context.ClientCertificate, includeAllClaims: true);
                             context.Success();

                             return Task.CompletedTask;
                         },
                         OnAuthenticationFailed = context =>
                         {
                             CustomLogger.Trace("CertificateAuthenticationEvents.OnAuthenticationFailed", context.HttpContext.TraceIdentifier, "Certificate not valid.");
                             context.Fail("Certificate not valid.");
                             return Task.CompletedTask;

                         }

                     };
                 });


`

`


             
               services.AddCertificateForwarding(options =>
            {

                options.CertificateHeader = "X-SSL-CERT";

                options.HeaderConverter = (headerValue) =>
                {
                    CustomLogger.Trace("AddCertificateForwarding", "", $"Header Converter called, isHeaderValueNull=[{string.IsNullOrWhiteSpace(headerValue)}]");

                    X509Certificate2 clientCertificate = null;

                    if (!string.IsNullOrWhiteSpace(headerValue))
                    {
                        
                        var bytes = Uri.UnescapeDataString(headerValue)?.ToByteArray();
                        CustomLogger.Trace("AddCertificateForwarding", "", $"bytes: [{bytes?.Length}]");
                        clientCertificate = new X509Certificate2(bytes);

                    }

                    return clientCertificate;
                };
            });

`

**Comment by muqadar-ali** [comment]
Now I am facing another issue, I cannot seem to generate token without adding entire certificate as hex string in X-SSL-Cert header.
 I tried using this request token method but it does not work.
https://identityserver4.readthedocs.io/en/latest/topics/mtls.html#using-a-client-certificate-to-authenticate-to-identityserver

The only way to get token is to add below given line of code.
`               client.DefaultRequestHeaders.Add("X-SSL-CERT", cert.GetRawCertDataString());
`
Can you please guide me what am I doing wrong? 
@leastprivilege @brockallen

**Comment by leastprivilege** [comment]
The `X-SSL-CERT` is specific to nginx. If you are using IIS, this should not be needed. Haven't done any IIS work in a long time, so don't know from the top of my head, sorry.
