### ISSUE TITLE
How to issue tokens with typ: jwt instead of at+jwt in Identity Server 4?

### ISSUE THREAD

**Issue by Duke4848** [IdentityServer/IdentityServer4#5081]
### Question

Identity Server 4 in contrary to Identity Server 3 issues tokens with default value `"typ": "at+jwt"`, however for some time I still need to issue older version of token, meaning `"typ": "jwt"`.

Is there any way to overwrite default configuration of IS4 and issue JWT token of `"typ": "jwt"`?

**Comment by leastprivilege** [comment]
There a setting on the options.
