### ISSUE TITLE
Simple Example on authorize page not working with the demo ?

### ISSUE THREAD

**Issue by bart3r** [IdentityServer/IdentityServer4#5082]
### Question
Why does the simple example for authorization ([bottom of page](https://identityserver4.readthedocs.io/en/latest/endpoints/authorize.html)) not work with the demo client credentials?

If I use the demo details listed [here](https://demo.identityserver.io/), should the following link just work in the browser:

https://demo.identityserver.io/connect/authorize?scope=api&client_id=m2m&redirect_uri=http%3A%2F%2Fwww.google.com&response_type=token+id_token&nonce=abcdefghid&state=abc

When I click on that link, I see the error message:
"Sorry, there was an error : unauthorized_client. Invalid grant type for client"

Obviously, I am missing something, but will need your help.
Thank you.

**Comment by leastprivilege** [comment]
the `m2m` client is registered for client credentials flow. Use e.g. the `interactive.public` client with response type of `code`. Also - you would be missing the PKCE parameters (`code_challenge`).

**Comment by leastprivilege** [comment]
Try

`https://demo.identityserver.io/connect/authorize?client_id=interactive.public&state=1599045135410-jFe&scope=openid%20profile%20api&response_type=code&code_challenge=AnzQ4E1rK_TVDbOd3DUPmX8-UBB5KtACmz4v2g7PaAs&code_challenge_method=S256&redirect_uri=https://oauth.tools/callback/code`

**Comment by bart3r** [comment]
Thanks @leastprivilege This helped me progress.

I receive a verifier code and then use that to try to obtain an access token, but I get the following error:

**Authentication failure! invalid_credentials: OAuth2::Error, invalid_grant:
{"error":"invalid_grant"}**

My redirect uri is set to my local development environment. Does the demo IdentityServer allow any redirect uri, or has it whitelisted certain domains? Is that likely the cause of my problem?

**Comment by leastprivilege** [comment]
The demo instance allows any redirect URI. 

Well - handcrafting those requests is not trivial. That's why client libraries exist. 

It might be easier to self-host IdentityServer (or even the demo instance) so you have access to log files.
