### ISSUE TITLE
when authentication of .NET 4+ application is done from identity server core 4, Response header location turns HTTP from HTTPS in chrome.

### ISSUE THREAD

**Issue by nityanandomalo18** [IdentityServer/IdentityServer4#5083]
After chrome update 87.0.4280.88 Release. In chrome browser, my application started showing 
Error "**The information you’re about to submit is not secure**". But all the contents in it are secure. After investigating it was found that after successful authentication using SSO Identity Server Core 4. the response header Location Attribute is changing HTTP from HTTPS and status in network shows block(other). All other browsers are working fine. I tried to forcefully add HTTPS in the location section in the response header, but it still not working
![image](https://user-images.githubusercontent.com/75992269/102092616-3f908200-3e46-11eb-8e2d-c189247f2da6.png)

**Comment by itorian** [comment]
Same issue when i'm using identityserver4 to authenticate asp.net full framework app and chrome version 87.0.4280.88. identityserver4 to authenticate asp.net core app works well.

**Comment by brockallen** [comment]
I don't follow, and so I think we need more information. The big thing here is that I think you're describing the login page, which is not from the IdentityServer middlware, and so this means this is more of your issue to sort out in your host and your UI.

**Comment by andrewisaburden** [comment]
@nityanandomalo18 @itorian does this solve it for you? https://stackoverflow.com/questions/57934185/asp-net-core-3-0-security-issue-with-http2-on-chrome-and-firefox
