### ISSUE TITLE
Redirect after authentication to .Net full framework 4.7.2 application is not working

### ISSUE THREAD

**Issue by koyal123** [IdentityServer/IdentityServer4#5084]
For authentication I am using openid connect authentication(identity server 4). I am redirecting to SSO app that is built on .Net Core framework. After successful authentication it returns the call back url to my client web app that is built on .net full framework 4.7.2. It was working fine before. But due to the latest update of chrome version 87.0.4280.88. It is not working on chrome now. It is saying that website is not secured. And location of response header is set as http even when callback url is https. Please refer the below images. I have forcefully over write the http header to https in location in startup class as well.
![image](https://user-images.githubusercontent.com/75992020/102092422-13750100-3e46-11eb-88b8-2fb83e08a9c2.png)

![image](https://user-images.githubusercontent.com/75992020/102092511-28519480-3e46-11eb-9700-f9a7a4927cbc.png)

![image](https://user-images.githubusercontent.com/75992020/102092612-3ef7eb80-3e46-11eb-9172-5c519a9011d5.png)
 
I have put this code in startup of my SSO app(on .net core framework) as well

![image](https://user-images.githubusercontent.com/75992020/102092746-62229b00-3e46-11eb-9046-b14362cd15bd.png)
 
This in startup of client web app (.net full framework)
![image](https://user-images.githubusercontent.com/75992020/102092870-83838700-3e46-11eb-8a6b-3458131c65b3.png)

### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by itorian** [comment]
Same issue when i'm using identityserver4 to authenticate asp.net full framework app and chrome version 87.0.4280.88. identityserver4 to authenticate asp.net core app works well.
