### ISSUE TITLE
Is it necessary/possible to validate logoutId?

### ISSUE THREAD

**Issue by Perustaja** [IdentityServer/IdentityServer4#5085]
### Question
When logoutId is passed in as a hidden field in the logout form, is it necessary to validate it?
I get that this may be more of an issue suited for IdentityServer4.Quickstart

I understand the logoutId does not come from an external source and the end-session endpoint should be used, but I am still a bit confused on the possibility of, if a logout prompt is required, someone changing the hidden form field. 

I guess the worst possible scenario is they are redirected to bogus providers/not fully signed out? I'm not sure if it would actually cause harm to anyone but the user but I'm still unsure. Appreciate any feedback.

### Specific code in question
IdentityServer4.Quickstart.UI.Quickstart.Account.AccountController.cs
```
        public async Task<IActionResult> Logout(string logoutId)
        {
            // build a model so the logout page knows what to display
            var vm = await BuildLogoutViewModelAsync(logoutId);

            if (vm.ShowLogoutPrompt == false)
            {
                // if the request for logout was properly authenticated from IdentityServer, then
                // we don't need to show the prompt and can just log the user out directly.
                return await Logout(vm);
            }

            return View(vm);
        }
```
Then, the actual view associated with the action.
IdentityServer4.Quickstart.UI.Quickstart.Views.Logout.cshtml
```
@model LogoutViewModel

<div class="logout-page">
    <div class="lead">
        <h1>Logout</h1>
        <p>Would you like to logut of IdentityServer?</p>
    </div>

    <form asp-action="Logout">
        <input type="hidden" name="logoutId" value="@Model.LogoutId"  />
        <div class="form-group">
            <button class="btn btn-primary">Yes</button>
        </div>
    </form>
</div>

```

**Comment by brockallen** [comment]
The logout id contains context needed for OIDC SLO, which needs to be processed properly on the logged out page processing.

**Comment by Perustaja** [comment]
Thanks for the reply. Is it necessary to validate it based on the user? For instance in the quickstart UI it could potentially be modified as it is sent in through a hidden form field. I suppose the worst case scenario is they mess up their own logout?

**Comment by brockallen** [comment]
Doesn't anti forgery protect the hidden field? And as for modification of the logout id payload itself, it's data protected.

**Comment by Perustaja** [comment]
That's very true, I read up and it does indeed do that. Thanks, sorry for the time taken.
