### ISSUE TITLE
Since v4.0, generated reference token is very long

### ISSUE THREAD

**Issue by bgarel** [IdentityServer/IdentityServer4#5090]
### Question
Since v4.0, generated reference token is very long and much longer than in v3.0. 

Ex: 93E7DB422497D00029ECA44016E09821D9F15333684C5947B0ED69C545A5BD67

I see in the source history that it is because of the PR #4234. 
It uses the CryptoRandom.CreateUniqueId() method with the CryptoRandom.OutputFormat.Hex format, which make the token much longer.
Is there a way to generate the reference token with the older format ?

Thank you for your reply.

Benjamin

**Comment by brockallen** [comment]
You can replace the token handle service in DI.

**Comment by bgarel** [comment]
Thank you for your quick reply.
I will create a custom HandleGenerationService.

Regards,
