### ISSUE TITLE
Quickstart Protecting an API using Client Credentials

### ISSUE THREAD

**Issue by Robotuner** [IdentityServer/IdentityServer4#5099]
I am following the Quickstart Protecting an API using Client Credentials.
https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html

Have set up the IdentityServer and API project in visual studio 2019.  The version of IdentityServer4 that is installed is 4.0.0
I have modified IdentityServer and API projects to not use https, so the endpoints are localhost:5001 and localhost:6001

From the webpage, I am able to retrieve the disco info using the url:
http://localhost:5001/.well-known/openid-configuration

My problem is the console app.

when I attempt to execute:
var client = new HttpClient();
var disco = await client.GetDiscoveryDocumentAsync("http://localhost:5001");
if (disco.IsError) { }

**the call to GetDiscoveryDocumentAsync never returns**.  No Exception is thrown. disco.isError is never hit.

I can use postman with the Get 
http://localhost:5001/.well-known/openid-configuration and it returns with the disco data.

adding;
services.AddCors(o =>
{
	o.AddDefaultPolicy(d => d.AllowAnyOrigin());
});
to the IdentityServer website does not make a difference.

If I replace 
var disco = await client.GetDiscoveryDocumentAsync("http://localhost:5001");
with 
HttpResponseMessage response = await client.GetAsync("http://localhost:5001/.well-known/openid-configuration");
the call never returns.

What am I doing wrong?
Thanks for any insights.

**Comment by brockallen** [comment]
Did you ever make any progress on your issue?

**Comment by Robotuner** [comment]
Since there hasn't been any comments, I have set this aside and will revisit at a later date.
