### ISSUE TITLE
Types missing from Latest Release branch / Nuget

### ISSUE THREAD

**Issue by alikor** [IdentityServer/IdentityServer4#510]
I am unable to compile my application because the following interfaces/types are missing from the Release branch but they still exists in the Dev branch 

IResourceStore
IdentityServerConstants.StandardScopes

There might be more missing types

How/Why was these two types not in the latest release?

**Comment by leastprivilege** [comment]
They are not yet in the release. They will soon in RC4.

**Comment by alikor** [comment]
but the quick start documentation points to them for current release https://identityserver4.readthedocs.io/en/release/quickstarts/3_interactive_login.html

**Comment by leastprivilege** [comment]
No it doesn't.

Not here:
https://identityserver4.readthedocs.io/en/release/quickstarts/3_interactive_login.html

but here:
https://identityserver4.readthedocs.io/en/dev/quickstarts/3_interactive_login.html

**Comment by alikor** [comment]
I am referring to the IdentityServer4.Quickstart.UI repo when introducing breaking changes a release tag? should be added

**Comment by brockallen** [comment]
Ah, we don't have a release branch on that repo -- just a dev branch. @alikor for now, you can use the files from the release branch of this repo in the host folder.
