### ISSUE TITLE
Why is this an invalid redirect_uri?

### ISSUE THREAD

**Issue by Jonatthu** [IdentityServer/IdentityServer4#5105]
When I configure my client with allowed cors origins with:

```
fail: IdentityServer4.Stores.ValidatingClientStore[0]
      Invalid client configuration for client DatterApp: AllowedCorsOrigins contains invalid origin: https://auth.expo.io/@jonatthu/Datther
```
Also this url fails: https://auth.expo.io/@jonatthu/Datther

If I do not make it part of my configuration, the client will work just fine.

This part of the code is making it invalid:
https://github.com/IdentityServer/IdentityServer4/blob/45f8cb5d2215263528b6481ad9571729d7090c96/src/IdentityServer4/src/Validation/Default/DefaultClientConfigurationValidator.cs#L152

This url is given by expo client using ios.

I am using Identity server 4 version 3.1.0

**Comment by leastprivilege** [comment]
That's an origin `https://auth.expo.io` - you configure a URL.
