### ISSUE TITLE
Need help on implementing IRefreshTokenService interface

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer4#511]
I just need a quick help to understand how can I properly implement the interface "IRefreshTokenService" in case I want to do some manipulation.
This is the signature of the method:
 public Task<string> CreateRefreshTokenAsync(ClaimsPrincipal subject, Token accessToken, Client client)

Can you please give me some simple sample on how to generate a valid refresh token in there?

Cheers,
Behrooz

**Comment by leastprivilege** [comment]
check the default implementation.

**Comment by behrooz66** [comment]
Well, I looked at the default implementation. The part that I don't get is:
await _events.RaiseRefreshTokenIssuedEventAsync(handle, token);
As the IEventService does not include that method. And in Visual Studio it leads to the following error: "IEventServiceExtension.RaiseRefreshTokenIssuedEventAsync... is inaccessible due to its protection level".

Can you give me quick guide?

**Comment by behrooz66** [comment]
I read through the default implementation and there is a tiny piece I cannot decipher, probably due to a missing piece in my programming knowledge. I wonder if you can give me a quick tip.

The _event is from the type IEventService which only contains one method called RaiseAsync.
However, in refresh token service implementation, there is the following line:

_event.RaiseSuccessfulRefreshTokenRefreshEventAsync(....)

This "RaiseSuccessfulRefreshTokenRefreshEventAsync" is a method of another class called "IEventServiceExtensions" that does not event implement that "IEventService" interface! How does the _event then invoke a method in that class?
I'm very confused and any help is appreciated.

**Comment by brockallen** [comment]
it's an extension method
