### ISSUE TITLE
It is possible to customize default endpoints Urls?

### ISSUE THREAD

**Issue by patelbinal** [IdentityServer/IdentityServer4#5112]
Hi,

Can we customize the default internal endpoint URL? I did not find the option to use it in 
` var builder = services.AddIdentityServer(options => {
                        options.UserInteraction.LoginUrl= "/Email/EmailLogin";
                        options.UserInteraction.LogoutUrl = "/Logout/Logout";
                
                    }) //use custom login page for OTP login
                    .AddInMemoryIdentityResources(Config.IdentityResources)
                    .AddInMemoryApiResources(Config.GetApiResource())
                    .AddInMemoryApiScopes(Config.ApiScopes)
                    .AddInMemoryClients(Config.Clients)
                ;`

Also, I tried with builder.AddEndpoint<DiscoveryEndpoint>(EndpointNames.Discovery, ""); but this shows error mentioning "The type 'IdentityModel.Client.DiscoveryEndpoint' cannot be used as type parameter 'T' in the generic type or method 'IdentityServerBuilderExtensionsCore.AddEndpoint<T>(IIdentityServerBuilder, string, PathString)'. There is no implicit reference conversion from 'IdentityModel.Client.DiscoveryEndpoint' to 'IdentityServer4.Hosting.IEndpointHandler'".

**Comment by leastprivilege** [comment]
No this is not possible with the current design.

**Comment by patelbinal** [comment]
I mean to say the default endpoints means authorization_endpoint, token_endpoint etc.
