### ISSUE TITLE
It is possible to customize default internal endpoints Urls?

### ISSUE THREAD

**Issue by patelbinal** [IdentityServer/IdentityServer4#5115]
Hi guys,

I was working around IdentityServer 4 
By default, the endpoint for discovery endpoint is: 'https://localhost:44301/.well-known/openid-configuration'.

How can I change the default endpoints in IdentityServer's discovery endpoint so that it would be like https://localhost:44301/authentication/.well-known/openid-configuration.

In the same way I want to apply the "authentication" prefix in another internal endpoint like authorization_endpoint, token_endpoint, userinfo_endpoint, etc.

I am not seeing any option in adding the Identity server another custom URLs like login and logout URLs.
` var builder = services.AddIdentityServer(options => {
                        options.UserInteraction.LoginUrl= "/Email/EmailLogin";
                        options.UserInteraction.LogoutUrl = "/Logout/Logout";
                    })`

**Comment by leastprivilege** [comment]
You cannot change the paths to the endpoint. They are always relative to you base-address.

**Comment by patelbinal** [comment]
ok, one more thing I need to ask.

**Comment by patelbinal** [comment]
Suppose my identity server is hosted on www.abc.com/ which is a private address so, all the internal endpoints of the identity server would start with www.abc.com/. Is there any way, I could replace this base address of these URLs, so all the endpoints covered in the discovery document should start with another public URL which I could configure let say www.xys.com instead of www.abc.com ? www.xys.com is a public address

**Comment by patelbinal** [comment]
Thanks @leastprivilege for te reply
