### ISSUE TITLE
Is it possible to use WebAPI to replace the original logic？

### ISSUE THREAD

**Issue by smallprogram** [IdentityServer/IdentityServer4#5118]
### Question
I have an idea. The original template is basically designed using ASP.NET MVC architecture. Is it possible to use Asp.Net Core WebAPI to replace the back-end logic, and then use the SPA front-end architecture for UI display? Is this feasible? Will it bring insecurity?

**Comment by brockallen** [comment]
It's possible, yes.

**Comment by smallprogram** [comment]
> It's possible, yes.

I will try Thank You~
