### ISSUE TITLE
The default for RefreshTokenExpiration is missing in the documentation

### ISSUE THREAD

**Issue by tiesmaster** [IdentityServer/IdentityServer4#5120]
We're working on changing the `RefreshTokenExpiration` from `Absolute` to `Sliding`, and noticed that the default is not specified in either of the 2 places that this is documented (the [Refresh Tokens](https://identityserver4.readthedocs.io/en/latest/topics/refresh_tokens.html#additional-client-settings), and [Client](https://identityserver4.readthedocs.io/en/latest/reference/client.html?highlight=RefreshTokenExpiration#token)), where most other settings have a default.

Is there a reason that this is left out, or can I put in a PR to add it?

**Comment by leastprivilege** [comment]
Thanks - yes, please. Submit a PR.
