### ISSUE TITLE
How to Configure Identity Server behind an Application Gateway on Azure

### ISSUE THREAD

**Issue by laz360play** [IdentityServer/IdentityServer4#5124]
I have a simple web client running on an azure app service and an identity server  4 project running on an azure app service as well. Both are running behind an application gateway. I have updated the discovery document to using the public origin which belongs to the Application Gateways DNS. However when the web client tries to authorize itself with the identity server, the identity server uses the app services host name to create the redirect uri instead of the app gateway dns. 

How do I make sure Identity server creates the correct redirect uri of the web client? I am getting a 403 forbidden error because of this

**Comment by Chris3773** [comment]
The host header that the Application Gateway sends to the App Service needs to be updated. You can install the extension "Application Gateway Host Rewrite" on the App Service and IdentityServer4 will pick up the correct host from the Application Gateway.

**Comment by laz360play** [comment]
> The host header that the Application Gateway sends to the App Service needs to be updated. You can install the extension "Application Gateway Host Rewrite" on the App Service and IdentityServer4 will pick up the correct host from the Application Gateway.
> 
> The same thing should also be possible to do with a rewrite rule in the web.config.

Thank you so much

**Comment by tiwari-abhishek** [comment]
@laz360play Or you can specify the hostname you want to use in the web.config file for your specific environment, and assign it during startup. Then you can be sure that even on non-azure deployments the hostname would remain consistent for specific domain (D/Q/P).
