### ISSUE TITLE
My web app needs the external provider's access tokens obtained via IdentityServer4, what is the best practice?

### ISSUE THREAD

**Issue by felinepc** [IdentityServer/IdentityServer4#5125]
### Question

My project has a main web app (the relying party client), which relies on a standalone instance of IdentityServer4 for user authentication/authorization.

The IdentityServer is integrated with external identity providers (Microsoft, Google etc). 

Normally, the IdentityServer would only use the external provider for authentication, then discard their tokens and ultimately issues its own tokens to the relying party.

But in my case, my web app actually needs these external provider's access and refresh tokens in order to periodically access these social providers on behalf of the user, without the user's presence. 

So my question is: 

1. Where should these tokens be stored? In IdentityServer's own database, or at the client?

If they're stored with IdentityServer, how should the web app client access them? Give the client direct access to IdentityServer's underlying database if their connection can be secured?

If they should be stored in the client's own database, what's the best way to deliver these tokens to the client during the initial authorization flow?

2. If the answer to #1 is that IdentityServer stores these tokens, then who should be responsible for refreshing them periodically so that my web app never loses access to those external providers? 

Your advice will be greatly appreciated!

**Comment by leastprivilege** [comment]
If the web app needs those tokens, I would transfer them back. From that point on it is the web apps responsibility to manage them.
