### ISSUE TITLE
How to authenticate AAD user in Identity Server 4?

### ISSUE THREAD

**Issue by rairafaqatali** [IdentityServer/IdentityServer4#5127]
I have integrated the Azure Active Directory in Identity Server 4 as an external provider.

I want to authenticate Azure Active Directory users from Identity Server 4 by using the APIs.

Here is the code:

```
  var disco = await client.GetDiscoveryDocumentAsync("https://localhost:5001");

if (disco.IsError)
{
    Console.WriteLine(disco.Error);
    return;
}

// request token
var tokenResponse = await client.RequestPasswordTokenAsync(new PasswordTokenRequest
        {
            Address = disco.TokenEndpoint,
            ClientId = "client",
            ClientSecret = "secret",

            Scope = "api1",
            UserName = "ad user name",
            Password = "add user password"
        });
```
When I execute this piece of code, I got an invalid username or password error.

Note: the provided credentials are valid.

**Comment by brockallen** [comment]
https://identityserver4.readthedocs.io/en/latest/topics/resource_owner.html

**Comment by rairafaqatali** [comment]
Do we have to explicitly implement IResourceOwnerPasswordValidator for external providers?

**Comment by brockallen** [comment]
You either use the interactive workflow where the browser redirects, or the client collects credentials and you use IResourceOwnerPasswordValidator to validate those credentials. The browser redirect is the recommended approach.
