### ISSUE TITLE
What are the rules of a 'DisplayName' in an IdentityServerUser object?

### ISSUE THREAD

**Issue by Walkerguy** [IdentityServer/IdentityServer4#5137]
### Question
I'm using the **IdentityServerUser** object and wanted to change the DisplayName from the email to my user's username (since the claim is called 'name').

However, if I modify the display name to anything other than the user's email, I'm unable to log in and I get redirected to the logged-out screen.

### Changing from this
```csharp
var AuthedUser = new IdentityServerUser(user.Guid)
{
    DisplayName = user.Email,
    IdentityProvider = provider
};

AuthedUser.AdditionalClaims.Add(new Claim("username", user.Username ?? string.Empty));
AuthedUser.AdditionalClaims.Add(new Claim("firstname", user.FirstName ?? string.Empty));
AuthedUser.AdditionalClaims.Add(new Claim("lastname", user.LastName ?? string.Empty));
AuthedUser.AdditionalClaims.Add(new Claim("image", user.Image ?? string.Empty));
```

### To this
```csharp
var AuthedUser = new IdentityServerUser(user.Guid)
{
    DisplayName = user.Username, <----
    IdentityProvider = provider
};

AuthedUser.AdditionalClaims.Add(new Claim("email", user.Email?? string.Empty)); <----
AuthedUser.AdditionalClaims.Add(new Claim("firstname", user.FirstName ?? string.Empty));
AuthedUser.AdditionalClaims.Add(new Claim("lastname", user.LastName ?? string.Empty));
AuthedUser.AdditionalClaims.Add(new Claim("image", user.Image ?? string.Empty));
```
will cause this, I'm guessing there's some process that validates a user's email to be the displayname that I'm not aware of?
Thanks in advance!

**Comment by leastprivilege** [comment]
We don't use the display name anywhere besides for showing it in our default UI...

**Comment by Walkerguy** [comment]
Hahah alright, that's what I thought. Then I truly don't know why this is happening. Thanks for the quick response.
