### ISSUE TITLE
Does the password grant type implementation in IdentityServer4 require client secret?

### ISSUE THREAD

**Issue by johnxjcheng** [IdentityServer/IdentityServer4#5146]
When using the password grant type for a console or service app, it works fine when I POST username/password and client_id/secret. However, we are questioning whether it's necessary to include the client's secret. So, I tested it by not send the secret. I get error code 400 and message 'invalid_client'. I saw a column on the client registration table called: RequireClientSecret. When setting to 0, I get 'invalid_grant'. I don't know if the secret is mandatory from the OAuth's standard. I did some search and did not find the answer. But I saw a comment on the Azure AD's implementation. It says: client_secret is 'Sometimes required'. See this link:

[https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth-ropc#:~:text=You%20should%20only%20use%20this,flows%20can't%20be%20used.&text=The%20Microsoft%20identity%20platform%20only,AD%20tenants%2C%20not%20personal%20accounts.&text=Personal%20accounts%20that%20are%20invited,t%20sign%20in%20through%20ROPC.](url)

So, I am wondering if you can provide an answer or explanation? 

Thanks!

**Comment by leastprivilege** [comment]
If you set `RequireClientSecret` to false, then then client secret is not required.

**Comment by johnxjcheng** [comment]
@leastprivilege, I tried that and got 'invalid_grant'. Seems like 'RequireClientSecret = false' is not compatible with password grant.

**Comment by leastprivilege** [comment]
I don't think so. As always - check the logs to find the real reason of an error.

**Comment by johnxjcheng** [comment]
@leastprivilege, after a more careful test, I confirm you are right. By setting RequireClientSecret to false, the client secret is not needed for password grant. Thanks!
