### ISSUE TITLE
Using IdentityServer4 with Asp.net core3.1 behind a Nginx Reverse Proxy Server

### ISSUE THREAD

**Issue by sadaqatbukhari** [IdentityServer/IdentityServer4#5152]
### Question
Is this solution is outdated or still valid?
https://github.com/IdentityServer/IdentityServer4/issues/1623

We are facing same issue but not able to resolve using above solution.

We are using IdentityServer4 and asp.net core 3.1 and our clients are in angular. Public domain(mydomain.com) is configured by NGINX reverse proxy server and applications are deployed on IIS. If the Authority is set to the internal URL http://192.168.0.13:8001, identity server redirects to internal instead of external. But if Authority is set to external URL then services cannot resolve the DiscoveryURIs.

How to access DiscoveryURIs and http://192.168.0.13:8088/.well-known/openid-configuration behind the reverse proxy with NGINX. Because public domain(mydomain.com) is not accessible from local environment.

### Minimal working example

```csharp
 .AddJwtBearer(options =>
        {
            options.Authority = _identityServerURL;

            options.Audience = _identityServerURL+"resources";
           
            options.RequireHttpsMetadata = false;
        });
```

**Comment by leastprivilege** [comment]
Well this is really a DNS problem. You network admins need to fix that.
