### ISSUE TITLE
Cannot set SameSite property of ApplicationCookie

### ISSUE THREAD

**Issue by fanruinet** [IdentityServer/IdentityServer4#5159]
### Issue / Steps to reproduce the problem
I have the following code in ConfigureServices(...), in Startup.cs, in a .NET 5.0 MVC application:
services.ConfigureApplicationCookie(options =>
{
    options.Cookie.IsEssential = true;
    options.Cookie.SameSite = SameSiteMode.Strict;
});

But after login, the server issued a cookie with SameSite=None. I see the SameSite property is overridden here:
https://github.com/IdentityServer/IdentityServer4/blob/07574678bed9e499b190d0b000b182323eb89566/src/AspNetIdentity/src/IdentityServerBuilderExtensions.cs#L51
and related to issue #2595 External authentication failing on iOS 12 

### Actual behavior:
The change restricted the SameSite to None so I can never set it to Strict or Lax.

### Expected behavior:
It should be possible to set SameSite to Strict or Lax.

**Comment by brockallen** [comment]
Have you read this on how to control the cookie settings?

https://identityserver4.readthedocs.io/en/latest/topics/signin.html#overriding-cookie-handler-configuration

**Comment by fanruinet** [comment]
Thanks for pointing to the documents. I'm able to change SameSite after I moved the code below services.AddIdentityServer(...).
