### ISSUE TITLE
how to do authentication with JWT token in Java spring with identityServer4. Also how to get the claim from IdentityServer4

### ISSUE THREAD

**Issue by jinyanghuang** [IdentityServer/IdentityServer4#5160]
I am using IdentityServer4 to do the authentication and authorization. The frontend will receive the access token after signin. And will establish a websocket(Stomp) connection. I want to do the authentication at backend before the connection. How do I do it? I dont find any example explain how the identityServer4 interact with java spring.

**Comment by jinyanghuang** [comment]
This is a question. I dont know how to add the label tho

**Comment by langhaoabcd** [comment]
example   https://github.com/Rainy99/springboot-ids4

**Comment by langhaoabcd** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/2890

**Comment by jinyanghuang** [comment]
@langhaoabcd Thanks, that is the right way to do it
