### ISSUE TITLE
Sign out with HTTP POST seem not working

### ISSUE THREAD

**Issue by thanhdn1989** [IdentityServer/IdentityServer4#5161]
### Issue / Steps to reproduce the problem
When performing a sign-out request as HTTP POST from my client (Xamarin Mobile app), there are 2 case:
1. Without POST_LOG_OUT_URI, I receive the response with status 200
2. With POST_LOG_OUT_URI, I receive the response with status 302

Both case has the same result: I didn't get logged out

So it seem that this is the expected behavior or am I missing something ?

**Comment by brockallen** [comment]
Did you use it in the expected way (via the browser)?
https://identityserver4.readthedocs.io/en/latest/endpoints/endsession.html

**Comment by thanhdn1989** [comment]
> Did you use it in the expected way (via the browser)?
> https://identityserver4.readthedocs.io/en/latest/endpoints/endsession.html

No I purely use the POST request without Browser interaction. So for IdentityServer we can't use POST request for endsession ?

**Comment by brockallen** [comment]
> No I purely use the POST request without Browser interaction. So for IdentityServer we can't use POST request for endsession ?

OIDC logout doesn't work that way. It expects the browser to make the request.
