### ISSUE TITLE
Setting IS4 cookie expiration

### ISSUE THREAD

**Issue by joshbinney** [IdentityServer/IdentityServer4#5165]
Hey,

I can't for the life of me figure out how to change the cookie lifetime so my logged in session is more than 2 weeks? I finally managed to get it off session by realizing that the remember me button does this, so now its 2 weeks.

I'm using .net core identity 3.1. It was my understanding that IS4 would set the cookies settings for this with this code:

`var builder = services.AddIdentityServer(options =>
                    {
                        ...
                        options.Authentication = new AuthenticationOptions()
                        {
                            CookieLifetime = TimeSpan.FromMinutes(1), 
                            CookieSlidingExpiration = false
                        };
...`

But with this the browser tells me AspNetCore.Identity.Application cookie is still 2 weeks

Thanks!

**Comment by brockallen** [comment]
https://identityserver4.readthedocs.io/en/latest/topics/signin.html#overriding-cookie-handler-configuration
