### ISSUE TITLE
How to add encryption key in JWKS url?

### ISSUE THREAD

**Issue by nhontran** [IdentityServer/IdentityServer4#5166]
### Question
I have a requirement to add the encryption key in JWKS url like the below:

{
    "kty": "EC",
    "use": "enc",
    "kid": "enc-2021-01-15T12:09:06Z",
    "crv": "P-256",
    "x": "xom6kD54yfXRPvMFVYFlVjUKzmNhz7wf0DP_2h9kXtY",
    "y": "lrh8C9c8-SBJTm1FcfqLkj2AnHtaxpnB1qsN6PiFFJE",
    "alg": "ECDH-ES+A128KW"
}

Does IS4 support it? I have searched for a while but could not find the way to add it.

Any help would be much appreciated.

**Comment by leastprivilege** [comment]
We don't support this natively. You would need to override the response generator to get those extra values in.

We are not adding any new features to IdentityServer4 - if you want to request that feature in our new version. Please open a feature request in the new repo:

https://github.com/DuendeSoftware/IdentityServer/discussions/categories/feature-request

**Comment by nhontran** [comment]
Hi @leastprivilege , thanks for your response. 

I will override the discovery response generator then.
