### ISSUE TITLE
ClientId - ":" character creates error

### ISSUE THREAD

**Issue by CTBT** [IdentityServer/IdentityServer4#5167]
I couldn´t find any information about this in the oauth specs so i have to ask here. Is it not allowed to use the ":" character as part of an oauth client identifier ? 

I´m trying to get an access token with postman, using the authorization tab and when i use a client identifier like "urn:appname" identity server returns an error.
`No client with id 'urn' found. aborting`

This only happens when i choose the option "Send as basic auth header". If i send the client credentials in the message body, the token is returned without errors.

![image](https://user-images.githubusercontent.com/22419230/109025402-fd45b580-76be-11eb-9b0d-72e623615a76.png)

![image](https://user-images.githubusercontent.com/22419230/109025722-45fd6e80-76bf-11eb-9c33-18f12eea6a08.png)

**Comment by leastprivilege** [comment]
Postman is doing the wrong encoding of the authorization header. Try sending the client id and secret in the post body. It will work.

**Comment by CTBT** [comment]
Thanks. It would definitely help if identity server could validate the authorization header for this kind of wron encoding because one of our customers client applications creates the same error for the token request at our identity server so it looks like it´s a common problem and it had cost me a lot of time.

**Comment by leastprivilege** [comment]
IdentityServer implements the OAuth specification. I think that's all we can do.

Maybe rather tell that the companies that do it wrong ;)
