### ISSUE TITLE
Is there a way to get the state & nonce generated by Challenge method without redirection?

### ISSUE THREAD

**Issue by nhontran** [IdentityServer/IdentityServer4#5169]
### Question
Hi, I have a requirement to integrate with an external authentication provider which they require us to generate the state & nonce and using these parameters as an input for the embedded JS to generate the QR code, this QR code is put in our page, it will be scanned by mobile app for authentication, there is no redirection to external login page.

https://stg-id.singpass.gov.sg/docs/embedded-auth/js (Section 4.2 Input parameters)

for the standard login with external authentication provider, we call the Challenge() method to redirect to the login page, and the redirect url contains the state & nonce itself, is there a way to generate/get them without redirection?

If I generate random nonce & state at frontend side then scanning the QR code and completed the authentication in mobile, it returned the authentication code and threw "**unable to unprotect the message.State.**" exception at the IS4, I tried to disable the state validation but it does not work.

```                    
configureOptions.ProtocolValidator = new OpenIdConnectProtocolValidator()
{
    RequireState = false,
    RequireStateValidation = false,
};
```

Any help would be much appreciated.

**Comment by nhontran** [comment]
Update on my question: I managed to generate the state & nonce by using the below method:

```
           private readonly IOptionsMonitor<OpenIdConnectOptions> _openIdOptions;
            ...
            private string GenerateNonce()
            {
                return Convert.ToBase64String(Encoding.UTF8.GetBytes(Guid.NewGuid().ToString()));
            }
            
            public string GetState()
           {
                var state = GenerateNonce();
                AuthenticationProperties authProperties = new AuthenticationProperties
                (
                  new Dictionary<string, string>
                  {
                    { OpenIdConnectDefaults.UserstatePropertiesKey, state },
                  }
                );

                //This StateDataFormat does not use the correct DataProtectionProvider
                return _openIdOptions.Get("oidc").CurrentValue.StateDataFormat.Protect(authProperties);
            }
```

However, I got another error in RemoteAuthenticationHandler "**.aspnetcore.correlation. state property not found**", as this correlation is generated when redirecting to the authentication login page which does not happen in my case. I am thinking to override the ValidateCorrelationId(), Is it correct doing this way?

**Comment by leastprivilege** [comment]
To be honest - this is really a question for Microsoft, since it is their code.

But I think the authentication handler was not designed with this use case in mind.

**Comment by nhontran** [comment]
Hi @leastprivilege , thanks for your reply.

Yah, this is really a question for Microsoft, anw, I have overridden the ValidateCorrelationId() method, I will close this question then.
