### ISSUE TITLE
Is IdentityServer4 GDPR compliant? 

### ISSUE THREAD

**Issue by sagarkul** [IdentityServer/IdentityServer4#5175]
### Question
I don't see an official document for GDPR compliance. Is IdentityServer4 is GDPR compliant?
Is there any guidelines for the GDPR in IdentityServer4?

**Comment by leastprivilege** [comment]
I think you are misunderstanding the purpose of IdentityServer. It's an OAuth/OIDC protocol implementation. All the user data handling is done by whoever implements the hosts.
