### ISSUE TITLE
Is it possible host Quickstart UI in a separate client project outside IdentityServer4 project?

### ISSUE THREAD

**Issue by rajivverma** [IdentityServer/IdentityServer4#5178]
I am following co-hosting example from [quickstart example](http://docs.identityserver.io/en/latest/quickstarts/community.html#co-hosting-identityserver4-and-a-web-api).
Let's say this application is hosted at `https://localhost:5001`.

I want to use Quickstart UI to implement login page and related functionality. But I want host these MVC pages in a separate ASP.NET MVC client project, which uses this identity server for authentication.
Let's say this application is hosted at `https://localhost:4001`.

Based on [this reference](https://docs.identityserver.io/en/latest/topics/signin.html#login-workflow), it seems I can specify login URL as `https://localhost:4001/account/login`. However, how am I supposed to implement/change the actual login logic in `AccountController.cs` and `ExternalController.cs` ? I don't have access to the database or entity framework database contexts `ConfigurationDbContext` and `PersistedGrantDbContext` in this project.

**Comment by brockallen** [comment]
All of our quickstarts host the client, the API, and IdentityServer in separate hosts:

https://github.com/IdentityServer/IdentityServer4/tree/main/samples/Quickstarts/3_AspNetCoreAndApis/src

**Comment by rajivverma** [comment]
@brockallen Thanks for your quick response. I believe I was not clear in asking the question.
In the example you shared, Quickstart MVC pages are still inside the IdentityServer project [here](https://github.com/IdentityServer/IdentityServer4/tree/main/samples/Quickstarts/3_AspNetCoreAndApis/src/IdentityServer/Quickstart).
I want to host these MVC page inside the MVC client project [here](https://github.com/IdentityServer/IdentityServer4/tree/main/samples/Quickstarts/3_AspNetCoreAndApis/src/MvcClient).

**Comment by brockallen** [comment]
Oh, you meant the quickstart UI for like login, logout, etc. that we bundle in the host w/ IdentityServer? Doing that is an anti-pattern, as you'd lose SSO.

**Comment by rajivverma** [comment]
Idea was to separate the UI interaction code in a separate project and keep the SSO with ID server project. I believed it would have been possible if somehow UserManager and SignInManager could use REST APIs instead of EF context to access configuration and persistent grant data directly?

**Comment by brockallen** [comment]
If you can get the SPA to issue the cookie in IS, then sure, that sounds like it would work.
