### ISSUE TITLE
demo.identityserver.io support for authorization code flow without PKCE

### ISSUE THREAD

**Issue by texnokot** [IdentityServer/IdentityServer4#5181]
### Question

demo.identityserver.io is not supporting authorization code flow without PKCE anymore. Or at least there is no client id provided for it. Can you please add support for it as well? 

The need is for demo-ing Identity Server as OpenId provider for other IdP. The problem is that now I can't add demo.identityserver.io in my IdP as an alternative IdP as it was before. 

Thank you!

**Comment by jafin** [comment]
Perhaps they are aligning it to OAuth 2.1 spec where `PKCE is required for all OAuth clients using the authorization code flow`   (https://oauth.net/2.1/)

**Comment by leastprivilege** [comment]
Code flow without PKCE is vulnerable to code injection attacks. That's why we do not expose it.

**Comment by texnokot** [comment]
I know about vulnerabilities related to authz code flow. What I'm trying to do is to use demo environment for connecting it to B2C. Like this example: https://medium.com/the-new-control-plane/connecting-azure-ad-b2c-to-identityserver4-via-the-b2c-custom-identity-provider-fd5ec0fbba0f
B2C is supporting PKCE but for their apps. So in this case which client should I use, if I want to utilize demo for federating with another IdP?

**Comment by leastprivilege** [comment]
client id: interactive.confidential
grant type: authorization code with PKCE and client credentials
client secret: secret
access token lifetime: 60 minutues
allowed scopes: openid profile email api offline_access

**Comment by texnokot** [comment]
Thanks! Yes, I tried this one before writing this question. In this configuration with B2C  I get:
Sorry, there was an error : invalid_request
code challenge required

It seems it still goes thru PKCE path and that's not the way to work for IS4<->B2C

**Comment by leastprivilege** [comment]
That means that B2C is not sending the code challenge - IOW - no PKCE. I cannot believe that B2C doesn't support PKCE.

**Comment by texnokot** [comment]
B2C is supporting PKCE for clients registered in it, but not then you federate it with another IdP.
So before the changes on demo environment, this scenario worked: https://medium.com/the-new-control-plane/connecting-azure-ad-b2c-to-identityserver4-via-the-b2c-custom-identity-provider-fd5ec0fbba0f 

Now with "client id: interactive.confidential" is not working by failing with provided message above.

**Comment by leastprivilege** [comment]
Does B2C support hybrid flow instead?

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4.Demo/actions/runs/638872074

I believe you know how to get all the info you need from this link ;)

**Comment by texnokot** [comment]
Thanks, Dominick! Works like a charm. Will close this thread.

Thanks again for the support. And have a good one! :)
