### ISSUE TITLE
Possible mismatch between authentication/cookie prefixes

### ISSUE THREAD

**Issue by antonfelich** [IdentityServer/IdentityServer4#519]
Not sure if this is by design or not, but there appears to be two different prefixes for cookies. One is IDSRV and the other IDSVR (note the V and R swapped around). 

**IdentityServerConstants.cs**
public const string DefaultCookieAuthenticationScheme = "idsrv";

**DefaultSessionIdService.cs**
public string GetCookieName()
{
	// TODO: fix from config?
        return "idsvr.session";
}

**Comment by brockallen** [comment]
That's the US vs. European spelling. (that was a joke)

In any event, this is moot as that code changed in RC4 to use the configured cookie scheme dynamically. 

Thanks though!
