### ISSUE TITLE
Manual token creation

### ISSUE THREAD

**Issue by sshumakov** [IdentityServer/IdentityServer4#52]
Hello, I've integrated usage of identity server to my project according to samples. Everything works like a charm :). Then, I faced with next challenge - I have tests which call API in self-hosted server. Once I add authentication to protect resources, I need to pass the token in header for each test.

Is there any way in which I can generate access token without going through full authentication flow (I want to do this only when IsDevelopment() == true, for testing purposes only) with some basic claims like id/name?

**Comment by leastprivilege** [comment]
you can create the tokens yourself (using the MS JWT lib) - or in-memory host idsrv. Check our integration tests for an example.
