### ISSUE TITLE
AWS enviroment Discovery URLs are not HTTPs

### ISSUE THREAD

**Issue by xiesamgh** [IdentityServer/IdentityServer4#5203]
I'm developing a SSO server which deployed to AWS. The nginx load balancer redirect all https request to http. It causes the failure of the login. 

I spent few days on this issue and tried all the solution such as setting options.ForwardedHeaders to XForwardedProto etc, no luck with all of them. And I also checked the nginx server setting, the X-Forwarded-Proto is enable. 

Did anyone get it work in AWS enviroment? Any commercial plugin I can pay to get it work?

**Comment by joeangry** [comment]
Commercial plugins shouldn't be need. Are you sure your nginx configuration is correct? Could you show us your nginx configuration for the site?

**Comment by xiesamgh** [comment]
My SSO service is using Asp.net Identity as user store. If I use test users store, the service is working well in AWS enviroment. So the nginx configuration should be ok. 
If I run the SSO service in my local, it also work well. 

So the situation is like this:
'asp.net identity + local enviroment'          **works well**
'test user store + local enviroment'            **works well**
'asp.net identity + aws enviroment'           **doesn't work**
'test user store + awsenviroment'              **works well**

Then I checked network details from Chrome, I found only the 'asp.net identity + aws enviroment' got different response header:

Set-Cookie: .AspNetCore.Identity.Application=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=none; httponly
Set-Cookie: Identity.External=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=none; httponly
Set-Cookie: Identity.TwoFactorUserId=; expires=Thu, 01 Jan 1970 00:00:00 GMT; path=/; samesite=lax; httponly
Set-Cookie: idsrv.session=98D41AE9F6A3FF372F0AB0FE16354D1E; path=/; samesite=none
Set-Cookie: .AspNetCore.Identity.Application=CfDJ8CJnUguhU2RKk_NuBOVj3zxbOV3GctAIc3be75rZJi-O5GNI9lgue6uKNq9EAJD-dZLrjnGVBUH_TKNA0wSefWz4Qdex4KrpPZ4PA4-

What reason causes the first three lines of the 'Set-Cookie'? The other 3 scenarios only got the last two 'Set-Cookie'.


my startup file code:

`
            services.AddDbContext<UserDbContext>(options => options.UseMySQL(connectionString));
            services.AddDatabaseDeveloperPageExceptionFilter();

            services.AddIdentity<IdentityUser, IdentityRole>()
                .AddEntityFrameworkStores<UserDbContext>()
                .AddDefaultTokenProviders();

            var builder = services.AddIdentityServer(options =>
                {
                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;

                    // see https://identityserver4.readthedocs.io/en/latest/topics/resources.html
                    options.EmitStaticAudienceClaim = true;
                })
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseMySQL(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseMySQL(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                .AddAspNetIdentity<IdentityUser>();
                //.AddTestUsers(TestUsers.Users);
`

my Configure of the startup:

`            
            var forwardOptions = new ForwardedHeadersOptions
            {
                ForwardedHeaders =
                Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedFor |
                Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedProto,
                RequireHeaderSymmetry = false
            };

            forwardOptions.KnownNetworks.Clear();
            forwardOptions.KnownProxies.Clear();

            // ref: https://github.com/aspnet/Docs/issues/2384
            app.UseForwardedHeaders(forwardOptions);

`

**Comment by xiesamgh** [comment]
here is the screenshot of the nginx setting:

![nginx setting](https://user-images.githubusercontent.com/7857781/113642088-26e8f800-96d3-11eb-8520-1b5db8b6582b.PNG)

After being redirected to the login page, I have to modify the url to change the http to https to make the login work. It looks like the AWS load balancer always changes https to http no matter what’s the configuration.

**Comment by xiesamgh** [comment]
here is my whole Startup.cs:

`

public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
            var connectionString = Configuration.GetConnectionString("DefaultConnection");

            services.AddCors(o => o.AddPolicy("AllowAll", builder =>
            {
                builder.AllowAnyOrigin()
                       .AllowAnyMethod()
                       .AllowAnyHeader();
            }));

            services.AddControllersWithViews();
            // Set up health checks
            services.AddHealthChecks();

            services.AddDbContext<UserDbContext>(options => options.UseMySQL(connectionString));
            services.AddDatabaseDeveloperPageExceptionFilter();

            services.AddIdentity<IdentityUser, IdentityRole>(options => {
                //options.Cookies.ApplicationCookie.ExpireTimeSpan = TimeSpan.FromHours(1);
            })
                .AddEntityFrameworkStores<UserDbContext>()
                .AddDefaultTokenProviders();

            var builder = services.AddIdentityServer(options =>
                {
                    options.Events.RaiseErrorEvents = true;
                    options.Events.RaiseInformationEvents = true;
                    options.Events.RaiseFailureEvents = true;
                    options.Events.RaiseSuccessEvents = true;

                    // see https://identityserver4.readthedocs.io/en/latest/topics/resources.html
                    options.EmitStaticAudienceClaim = true;
                })
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseMySQL(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseMySQL(connectionString,
                        sql => sql.MigrationsAssembly(migrationsAssembly));
                })
                .AddAspNetIdentity<IdentityUser>();
                //.AddTestUsers(TestUsers.Users);

            // not recommended for production - you need to store your key material somewhere secure
            builder.AddDeveloperSigningCredential();

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseCors("AllowAll");

            var forwardOptions = new ForwardedHeadersOptions
            {
                ForwardedHeaders =
                Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedFor |
                Microsoft.AspNetCore.HttpOverrides.ForwardedHeaders.XForwardedProto,
                RequireHeaderSymmetry = false
            };

            forwardOptions.KnownNetworks.Clear();
            forwardOptions.KnownProxies.Clear();

            // ref: https://github.com/aspnet/Docs/issues/2384
            app.UseForwardedHeaders(forwardOptions);


            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseMigrationsEndPoint();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseIdentityServer();

            app.UseCookiePolicy(new CookiePolicyOptions
            {
                MinimumSameSitePolicy = SameSiteMode.Lax,
                Secure = CookieSecurePolicy.Always,
            });

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHealthChecks("/healthcheck");
                endpoints.MapDefaultControllerRoute();
            });
        }
    }

`

**Comment by xiesamgh** [comment]
can we have PublicOrigin back for this situation? 

services.AddIdentityServer(options => {
options.PublicOrigin = "YOUR IDENTITY/AUTHORITY URL";
})

Then I can set the url to https.

**Comment by joeangry** [comment]
Your nginx configuration points to a http address, I'm pretty sure it should point to https to get what you want.
https://docs.nginx.com/nginx/admin-guide/security-controls/securing-http-traffic-upstream/
