### ISSUE TITLE
Hey @fredmararac,

### ISSUE THREAD

**Issue by mpospisil** [IdentityServer/IdentityServer4#5205]
Mauricio,

I have the same problem as you had. Could you add more details how to fix it. I don't know how and where to create a custom filter.

Regards,
Martin

Hey @fredmararac,
Yes, we did. The only issue we had was with the return Url and we created a custom filter to access it and put it back. Maybe the new versions work out of the box, I haven' tried. But if they don't let me know and I can share our fix with you.

Regards,

_Originally posted by @MauricioArroyo in https://github.com/IdentityServer/IdentityServer4/issues/3186#issuecomment-544155208_

**Comment by preqproaws** [comment]
Hey @mpospisil  that was sometime ago but I can share with you what we did, it's quite simple.
We created an ActionFilterAttribute where we ensure the right returnUrl.
Something in the lines of
```
            if (context.ActionArguments.ContainsKey("ReturnUrl"))
            {
                context.ActionArguments["ReturnUrl"] =
                    context.HttpContext.Request.QueryString.ToString().Replace("?ReturnUrl=", "");
            }
```

and then on the account controller methods, such as login, we setup this filter
```
 [HttpGet]
 [AllowAnonymous]
 [ServiceFilter(typeof(AwsUrlFilterAttribute))]
 public async Task<IActionResult> Login(string returnUrl)
```

I hope that helps, that was our workaround to make it work.

**Comment by mpospisil** [comment]
Hey @preqproaws . I have solved the issue. In the latest IdentityServer4 doesn't require any special filters but problem was in my configuration.
