### ISSUE TITLE
Revoke all reference tokens for a client, except the current one

### ISSUE THREAD

**Issue by kwerty** [IdentityServer/IdentityServer4#5207]
Disclaimer: I know Github Issue tracker isn't StackOverflow, and I know I'm not entitled to customer support from the devs, but I have a problem which I've been unable to find a solution to, and I'm at my wits end trying to figure out how to do it. I did post the question to Stackoverflow a week ago, but no responses :(

https://stackoverflow.com/questions/66912300/identityserver4-revoke-all-reference-tokens-for-a-client-except-the-current-one

If someone can answer, I'll be sure to update the Stackoverflow so others can find the answer. I'm certain I can't be the only person wanting to do something like this.

Anyway so here's the question -

I have a single page application which is protected by IdentityServer4 reference tokens.

I expect users to login to from multiple computers/devices.

In the settings area of the app, the user can change their password. To do so, they must enter their current password, as well as the new password.

I also wish to give the user the option to "Logout all other devices and computers".

If the user ticks this option, I want to invalidate any other reference tokens that exist for this client and this user, but I do NOT want to invalidate the reference token the user is currently using.

I only want it to logout other devices and computers. The user should stay logged in on the computer they are using.

For the life of me, I cannot see a way to do this with IdentityServer4. I was thinking I could simply run a delete on the PersistedGrants table, however I have no way of knowing which of the persisted grants in this table is the one the user is currently using.

Please help!

**Comment by kwerty** [comment]
Soon after this I realised I was using an older version of IdentityServer4. After updating there is a session_id in the PersistedGrants table. Taking the sid from the access/reference token, I am able to revoke all other reference tokens for the user.

I thought I'd finally solved it, but then I realised that IdentityServer stores the user's consent in a cookie, so after logging out a user on a different computer, the web app redirects them to the authorize endpoint, which promptly creates a new token for them and redirects them back the site.

So I'm back to where I started 👎 

Is there a way to tell Identity Server to invalidate the user's consent?

**Comment by brockallen** [comment]
Yes, that's why we added sid to the grants table. You'd also need to design your cookies to be stored server side and revoke those by sid. And then you'd need to trigger SLO to client apps to have their sessions revoked (also as server side cookies). So all possible but it requires your architecture to be designed to support that requirement. And IdenittyServer is only a piece of that.

**Comment by kwerty** [comment]
Is there a way to intercept token issuance by the authorization endpoint so that I can simply check the user's security stamp?

I would've thought I could check the security stamp in the OnGet method, before calling `idSrvInteractionService.GetAuthorizationContextAsync(returnUrl);`, however it would seem that IdentityServer handles the request all on its own without involving my LoginModel page.


        public async Task<IActionResult> OnGet(string returnUrl)
        {

            //<-------------- here is where I thought I could check the security stamp

            var authContext = await idSrvInteractionService.GetAuthorizationContextAsync(returnUrl);

            ClientName = authContext.Client.ClientName;

            return Page();

        }

Regarding what you said about having to trigger SLO client apps, etc. I'm not concerned about this, since I'm using reference tokens. If a user changes their password, all reference tokens are revoked, disabling access by anybody other than this client.

^ That is, assuming the authorize endpoint doesn't just hand out brand new tokens! :)

**Comment by brockallen** [comment]
https://identityserver4.readthedocs.io/en/latest/topics/custom_token_request_validation.html

**Comment by kwerty** [comment]
Thanks for your help. I have arrived at a solution.

When user changes password:

            if (model.EndSessions)
            {

                var currentSessionId = User.FindFirst(JwtClaimTypes.SessionId).Value;

                foreach (var grant in db.PersistedGrants.Where(pg => pg.ClientId == "the-client-name" && pg.SubjectId == user.Id.ToString() && pg.SessionId != currentSessionId).ToList())
                {
                    db.PersistedGrants.Remove(grant);
                }

                db.SaveChanges();

                await userManager.UpdateSecurityStampAsync(user);

            }

Then inside custom profile service:

        public override async Task IsActiveAsync(IsActiveContext context)
        {

            //only run check for cookie authentication
            if (context.Subject.Identity.AuthenticationType == IdentityConstants.ApplicationScheme)
            {

                var validationResponse = await signInManager.ValidateSecurityStampAsync(context.Subject);

                if (validationResponse == null)
                {
                    context.IsActive = false;
                    return;
                }

                var user = await userManager.GetUserAsync(context.Subject);

                context.IsActive = user.IsActive;

            }


        }
