### ISSUE TITLE
"error": "invalid_client"

### ISSUE THREAD

**Issue by liaoyuanchu666** [IdentityServer/IdentityServer4#5210]
thanks for your time
when i make a post request to http://localhost:5000/connect/token,return "error": "invalid_client"
below are my code 
startup.cs
services.AddIdentityServer()
                .AddDeveloperSigningCredential()        //This is for dev only scenarios when you don’t have a certificate to use.
                .AddInMemoryClients(Config.Clients)
                .AddInMemoryIdentityResources(Config.Ids)
                .AddInMemoryApiResources(Config.Apis)
                .AddApiAuthorization<ApplicationUser, PeonyDataContext>()
                .AddResourceOwnerValidator<ResourceOwnerPasswordValidator>();

config.cs
public static class Config
    {
        public static IEnumerable<IdentityResource> Ids =>
            new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
            };

        public static IEnumerable<ApiResource> Apis =>
            new List<ApiResource>
            {
                new ApiResource("api1", "api1", new[]{"role"}),
                //new ApiResource("sso", "SSO Service", new[]{ "role"}),
            };

        public static IEnumerable<Client> Clients =>
            new List<Client>
            {
            new Client
            {
                ClientId = "webClient",
                //ClientName = "Client",
                ClientSecrets = { new Secret("MainsiteSecret".Sha256()) },
                AllowOfflineAccess= true,
                AllowedGrantTypes = GrantTypes.ResourceOwnerPassword ,  
                
                AllowedScopes = { "api1" }
            }
            };
    }
![image](https://user-images.githubusercontent.com/66347658/114264236-532aae80-9a1c-11eb-98eb-a3b24f4c7d04.png)
below is the log info
![image](https://user-images.githubusercontent.com/66347658/114264263-72294080-9a1c-11eb-9451-3f54c9202c81.png)
thx again

**Comment by CTBT** [comment]
have you tryed it with a lower case id ?
