### ISSUE TITLE
InvalidOperationException: sub claim is missing When using ASP.NET Core Identity

### ISSUE THREAD

**Issue by Alik2015** [IdentityServer/IdentityServer4#5215]
This error comes from 

  var result = await _signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberLogin, lockoutOnFailure: false);

We have a custom user store which is implemented as follows:

```
    public class ApplicationUserStore:IUserStore<ApplicationUser>, 
        IUserPasswordStore<ApplicationUser>
    {...}
```
Core Identity Config

```
        public static IServiceCollection AddAppIdentityDB(this IServiceCollection services,IConfiguration configuration)
        {
            string connStr = configuration.GetConnectionString("IDTestDB");
            services.AddDbContext<IdentityContext>(options=> {
            options.UseMySql(connStr,ServerVersion.AutoDetect(connStr));
        });
            services.AddIdentity<ApplicationUser,ApplicationRole>()
                .AddEntityFrameworkStores<IdentityContext>()
                .AddUserManager<ApplicationUserManager>()
                .AddUserStore<ApplicationUserStore>()
                .AddDefaultTokenProviders();
            return services;
        }

```

And IdentityServer Config

```
            services.AddCustomIdentity(Configuration);

            var builder = services.AddIdentityServer()
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseMySql(idServerDBConn,ServerVersion.AutoDetect(idServerDBConn));
                })
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseMySql(idServerDBConn, ServerVersion.AutoDetect(idServerDBConn));
                }).
                AddDeveloperSigningCredential()
                .AddProfileService<AppProfileService>();
```

This was received using the link on identity server default test page that redirects to accountcontroller.

Although the error is from identityserver and it sais there is a missing claim I am not sure where this claim should have been added and whether there is something missing in identity server that would add the claim as default.

**Comment by brockallen** [comment]
Use `AddAspNetIdentity` instead for our ASP.NET Identity integration support:

https://docs.duendesoftware.com/identityserver/v5/aspnet_identity/

**Comment by Alik2015** [comment]
I am using idsrv4 and I just wish to clairify is duendesoftware the same company who makes this product.also added the package above but extension AddAspNetIdentity<ApplicationUser> not found.

**Comment by brockallen** [comment]
Yes, the people behind Duende Software created IdentityServer4, but IdentityServer4 is essentially in maintenance mode. That means we will not support it anymore, nor do we provide feature updates or bug fixes. We will only provide critical security updates (if feasible) - this will stop altogether in November 2022 (at the same time when .NET Core 3.1 goes out of support).

Duende IdentityServer v5 is the successor which offers a commercial license to guarantee sustainability, updates, support and a security notification service.
