### ISSUE TITLE
IdentityModel 4.5.0 fixes some CVEs in References

### ISSUE THREAD

**Issue by SymbioticKilla** [IdentityServer/IdentityServer4#5216]
### Question
https://github.com/IdentityModel/IdentityModel/releases/tag/4.5.0
Is any new release expected soon with IdentityModel 4.5.0?
Thanks!

**Comment by leastprivilege** [comment]
Can't you simply upgrade System.Text.Encodings.Web in the host?

**Comment by SymbioticKilla** [comment]
Thanks for the answer. It would be a workaround since it is not best practice to add and maintain nugets that not used directly.
