### ISSUE TITLE
IdentityServerTools without HttpContext

### ISSUE THREAD

**Issue by vocko** [IdentityServer/IdentityServer4#5217]
### Question
In relation to this original question https://github.com/IdentityServer/IdentityServer4/issues/3826.

Is there a way to use IdentityServerTools without HttpContext or would it be too hard to add this option in?

I'm doing some api calls from IS in background processing and need a token for this. I can issue it myself using the token service as hinted in the question below, just would prefer some cleaner, more standard way.

**Comment by leastprivilege** [comment]
It's not designed for this. and since we are not adding features anymore. Please use the workaround you mentioned.

**Comment by vocko** [comment]
Ok, I've done that. Thanks for the answer.
