### ISSUE TITLE
How to create or generate JWKS key (use for encryption - enc) in identityserver4

### ISSUE THREAD

**Issue by iamchamith** [IdentityServer/IdentityServer4#5220]
### Question
I want to implement jwks key with Identityserver4 for jwks endpoint, I've already checked alot of articles but no one can solve my requirement Here's is my requirement

https://stg-id.singpass.gov.sg/docs/authorization/api#_jwk_for_encryption
{
    "kty": "EC",
    "use": "enc",
    "kid": "enc-2021-01-15T12:09:06Z",
    "crv": "P-256",
    "x": "xom6kD54yfXRPvMFVYFlVjUKzmNhz7wf0DP_2h9kXtY",
    "y": "lrh8C9c8-SBJTm1FcfqLkj2AnHtaxpnB1qsN6PiFFJE",
    "alg": "ECDH-ES+A128KW"
}
following is the my code. it always assign use as sin
```csharp
 .AddValidationKey(((Func<ECDsaSecurityKey>)(() =>
             {
                 var pemBytes = Convert.FromBase64String(Configuration["IdentityServer:SigningCredential:PrivateKey"]);
                 var ecdsa = ECDsa.Create();
                 ecdsa.ImportECPrivateKey(pemBytes, out _);
                 return new ECDsaSecurityKey(ecdsa) { KeyId = Configuration["IdentityServer:SigningCredential:KeyId"] };

             }))(), IdentityServerConstants.ECDsaSigningAlgorithm.ES256);
 
```
Did I missed something ?

**Comment by nhontran** [comment]
Hi @iamchamith, you need to override the CreateJwkDocumentAsync() method in DiscoveryResponseGenerator to add your own encryption key.

**Comment by iamchamith** [comment]
@nhontran ,
Thank you for your replay, As you said I override the CreateJwkDocumentAsync()  as following, 
```
 private SecurityKey GetSecurityKey()
        {
            var pemBytes = Convert.FromBase64String(Configuration["IdentityServer:SigningCredential:PrivateKey"]);
            var ecdsa = ECDsa.Create();
            ecdsa.ImportECPrivateKey(pemBytes, out _);
            var ecdsaKey = new ECDsaSecurityKey(ecdsa) { KeyId = Configuration["IdentityServer:SigningCredential:KeyId"] };
            var parameters = ecdsaKey.ECDsa.ExportParameters(false);
            var x = Base64Url.Encode(parameters.Q.X);
            var y = Base64Url.Encode(parameters.Q.Y);
            var ecdsaJsonWebKey = new JsonWebKey
            {
                Kty = "EC",
                Use = "enc",
                Kid = ecdsaKey.KeyId,
                X = x,
                Y = y,
                Crv = "P-256",
                Alg = "ES256"
            };
            return ecdsaJsonWebKey;
        }
        
         services.AddIdentityServer() .AddValidationKey(new IdentityServer4.Models.SecurityKeyInfo { Key = GetSecurityKey(), SigningAlgorithm = "ES256" });
```
seems it is working.

**Comment by iamchamith** [comment]
@nhontran , One last question, 
My objective is create jwk using https://stg-id.singpass.gov.sg/docs/authorization/api#_jwk_for_encryption specification .
how can I able to add alg as **ECDH-ES+A128KW** ?
seems I can only add algorithms what in  **IdentityServerConstants.ECDsaSigningAlgorithm**
