### ISSUE TITLE
Why is the introspection endpoint limited to APIs

### ISSUE THREAD

**Issue by ilmora** [IdentityServer/IdentityServer4#5223]
### Question

I just read on the documentation [here](https://identityserver4.readthedocs.io/en/latest/endpoints/introspection.html) that the introspection endpoint is limitied to apis. So, you have to register an api in IdentityServer in order to use the introspection endpoint.
I have a simple scenario where the client (a ASP.Net Core 3.1 web application) receives encrypted tokens (id and access) stored in the cookies. Why can't the client validate those incomming tokens against the introspection endpoint ?

Best regards
Tristan

**Comment by JuliusPC** [comment]
I think the reason for this is the separation of a client requesting authorization from an API introspecting the access token. In your case the client is also the consumer of access token.
