### ISSUE TITLE
Resource

### ISSUE THREAD

**Issue by dbman86** [IdentityServer/IdentityServer4#5225]
Hi, I am using Resource Owner type, I can authenticate but I it's not returning all the user claims for 

### Minimal working example
Created client like this:

            var resourceOwnerClient = new Client
            {
                ClientId = "ro.client",
                AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,

                ClientSecrets =
                {
                    new Secret { Value = "SuperSecretPassword".Sha256()}
                },
                AllowedScopes = { "weatherapi.read", "openid", "profile" }
            };

Startup.cs:
```            services.AddIdentityServer()
                .AddAspNetIdentity<IdentityUser>()
                .AddConfigurationStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseSqlServer(Configuration.GetConnectionString("IdentityServerConfiguration")
                        //,sql => sql.MigrationsAssembly(migrationsAssembly)
                        );
                })
                // this adds the operational data from DB (codes, tokens, consents)
                .AddOperationalStore(options =>
                {
                    options.ConfigureDbContext = b => b.UseSqlServer(Configuration.GetConnectionString("IdentityServerPersistedGrant")
                        //,sql => sql.MigrationsAssembly(migrationsAssembly)
                    );

                    // this enables automatic token cleanup. this is optional.
                    options.EnableTokenCleanup = true;
                })
                .AddResourceOwnerValidator<ResourceOwnerPasswordValidator<IdentityUser>>()
                .AddDeveloperSigningCredential();
```

How come it is not returning all the claims associate with profile Identity Resource?

![image](https://user-images.githubusercontent.com/629163/116016356-4055d380-a5f1-11eb-9e5b-494c19aa96c8.png)

User definitely has values for some of them:

![image](https://user-images.githubusercontent.com/629163/116016408-5bc0de80-a5f1-11eb-9a2e-a36d4bc38ab0.png)

I access it with postman with these parameters:
![image](https://user-images.githubusercontent.com/629163/116016166-ab52da80-a5f0-11eb-9d55-0ce2c9184e43.png)

This is the decoded JWT:
![image](https://user-images.githubusercontent.com/629163/116016120-7b0b3c00-a5f0-11eb-953f-7c4223bec9c6.png)
![image](https://user-images.githubusercontent.com/629163/116016177-b6a60600-a5f0-11eb-84c4-412caa8806cf.png)

thank you!

**Comment by leastprivilege** [comment]
It's the job of your profile service to collect and return the claims. typically based on the requested scopes. Did you implement that?

**Comment by dbman86** [comment]
Thank you for the reply.  Yes I implemented a profile service but I pretty much used same implementation as one that comes with IS4.  Anyway, I added then to the ApiResourceClaims table and it is sending it back now...
