### ISSUE TITLE
/connect/endsession? endpoint exposing JWT token

### ISSUE THREAD

**Issue by Sandeep321** [IdentityServer/IdentityServer4#5226]
### Question
The below endpoints are GET methods and they do pass some info in the query string.
/login/callback?; 
/connect/authorize/callback?; 
/connect/endsession?

Specifically "/connect/endsession" passes the JWT token as id_token_hint in the query string (seems o be an issue) and after the logout is performed, the token is still valid(until it expires of course). This seems to be a security-related issue. To get around this issue, we could do the below, please let me know which one is possible with Identity server 4 and how.

1. If we could change these API's to POST and pass the info in the body. Please let me know if this is possible and how if yes.
2. If we can invalidate(expire) the token after the logout happens via "/connect/endsession" api. Please let me know how this can be achieved using IS4.

**Comment by leastprivilege** [comment]
a) this is according to spec
b) id_tokens contain a nonce - they are only accepted once for authentication purposes

**Comment by Sandeep321** [comment]
a) Point taken
b) it remains a valid token even after logout is done. User can still access data using the same token by a API client although user is signed out of IS.

**Comment by leastprivilege** [comment]
an id_token is not used to access APIs

**Comment by Sandeep321** [comment]
If I access an API using this token (after user logout), it still works. Are we doing something wrong?

**Comment by leastprivilege** [comment]
If you can access an API **at all** with an id_token - yes, you are doing something wrong. Access tokens are for accessing APIs - not id_tokens.

https://leastprivilege.com/2020/06/17/i-dont-like-identity-tokens/

**Comment by Sandeep321** [comment]
access_token is not a JWT token and can't be used as a bearer token to authorize an API. We use this token for authorizing the API's and then passing it in "/connect/endsession" as id_token_hint.

Can you please explain a bit on what token should be passed onto "/connect/endsession"?

**Comment by leastprivilege** [comment]
This is not really the right place to explain how protocols work, sorry. But the id_token is not for APIs - that's what access tokens are for.

You are right in sending the id_token to end session though.

Check the spec
https://openid.net/specs/openid-connect-core-1_0.html#IDToken

**Comment by Sandeep321** [comment]
@leastprivilege 
Do we have **POST** /connect/endsession instead of **GET** /connect/endsession wherein I can send **id_token_hint** in **POST** body?

**Comment by leastprivilege** [comment]
IIRC yes.

**Comment by Sandeep321** [comment]
@leastprivilege Any idea on how do I change this GET to POST?

**Comment by leastprivilege** [comment]
As you can see - the end session endpoint accepts both GET and POST

https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Endpoints/EndSessionEndpoint.cs#L38-L50

How YOU do those requests is up to you.

**Comment by Sandeep321** [comment]
@leastprivilege 
Is there any sample or link you can refer to?
