### ISSUE TITLE
RequestedClaimTypes  in IProfileService.GetProfileDataAsync not including IdentityResourceClaims

### ISSUE THREAD

**Issue by dbman86** [IdentityServer/IdentityServer4#5230]
I have created my own ProfileService concrete, based on the built in one.

context.RequestedClaimTypes does not include any related claims from IdentityResourceClaims table, but it does have the IdentityResource from the specified scopes in context.RequestedResources.ParsedScopes.  I would think it should be included in RequestedClaimTypes, otherwise is there any way to get these from the context? Or would I need to do my own db query?

Is this example - "app_perms" is the scope (identity resource) and "app" is the claim (in the IdentityResourceClaims table)
```
        protected virtual async Task GetProfileDataAsync(ProfileDataRequestContext context, IdentityUser user)
        {
            if (context.RequestedResources.ParsedScopes.Any(x => x.ParsedName == "app_perms") || context.RequestedClaimTypes.Contains("app"))
            {
                // add some test app claims 
                context.IssuedClaims.Add(new Claim("app", "App1"));
                context.IssuedClaims.Add(new Claim("app", "App2"));
            }
        }
```
thanks

**Comment by IndexOverflow** [comment]
It's been a while, but I'm fairly sure you can see which scopes are associated to which claims directly under resources. RequestedClaimTypes are likely just that, see 5.5 here https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter

**Comment by dbman86** [comment]
thank you - yes actually I can find it here:
context.RequestedResources.Resources.IdentityResources.Any(x => x.UserClaims.ContainsIgnoreCaseTrim("role"))
