### ISSUE TITLE
Potential mistake in the documentation

### ISSUE THREAD

**Issue by JuliusPC** [IdentityServer/IdentityServer4#5236]
In [the docs the client_id is marked as required](https://identityserver4.readthedocs.io/en/latest/endpoints/token.html). Which is definetly not the case (see below). It also would not compliant with the OAuth spec.

The same applies to the [docs of Duende IdentityServer](https://docs.duendesoftware.com/identityserver/v5/reference/endpoints/token/), but I didn’t test it against it.

Test: Call Token Endpoint without client_id in the body, client is confidential and needs to provide credentials (and does in HTTP header), PKCE is used.

**Comment by leastprivilege** [comment]
I am not following - client_id is always required. Either in the body or as part of the authorization header.

**Comment by JuliusPC** [comment]
> client_id is always required.

Sure, but I read the docs as if it is required to be *in the* body.

How about changing the docs from this:

> `client_id`  
> client identifier (required)

to

> `client_id`  
> client identifier (required – Either in the body or as part of the authorization header.)

**Comment by leastprivilege** [comment]
No objections - feel free to send a PR.
