### ISSUE TITLE
Confirmation claim is not being set

### ISSUE THREAD

**Issue by kenoby-dev** [IdentityServer/IdentityServer4#5238]
### Issue / Steps to reproduce the problem

We are using Identity Server 4 v4.1.2 which includes a reference to Microsoft.IdentityModel.Protocols.OpenIdConnect (>=5.6.0) which includes a reference to System.IdentityModel.Tokens.Jwt (>=5.6.0).

We are setting a value for the cnf claim and this is working correctly when the System.IdentityModel.Tokens.Jwt version remains at 5.6.0.

e.g.:

"cnf": {
    "x5t#S256": "58D76F7....."
  }

However, if a later version of the System.IdentityModel.Tokens.Jwt package is referenced (e.g. 6.11.0) either directly or indirectly via another project reference then the cnf claim becomes empty within the access token.

e.g.

"cnf": {
    "x5t#S256": ""
  }

Removing any references to ensure the System.IdentityModel.Tokens.Jwt package reverts back to v5.6.0 fixes the issue.

Nothing different appears in the log file for either cases.  There are no errors or warnings, just an access token that is missing the cnf claim.

**Comment by leastprivilege** [comment]
IdentityServer4 is not compatible with the Jwt 6.x package. You need to stay on 5.x
