### ISSUE TITLE
Licensing issue - Code from Stackeroverflow with CC-BY-SA license

### ISSUE THREAD

**Issue by bjoernbusch** [IdentityServer/IdentityServer4#5241]
### Question

The file https://github.com/IdentityServer/IdentityServer4/blob/main/src/IdentityServer4/src/Validation/Default/ResponseTypeEqualityComparer.cs contains a codesnippet from Stackoverflow, which is attributed with the CC-BY-SA license. This license, when I understand it correctly says that IdentityServer would also have to be distributed under that license now, since you build open the material:

https://creativecommons.org/licenses/by-sa/4.0/

_If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original._

What is your opinion on that?

**Comment by leastprivilege** [comment]
You mean change the license of IdentityServer because of 3 lines of code?

I don't think so.

**Comment by bjoernbusch** [comment]
I agree that this software copyright / licensing stuff is weird, but I just always hear as an example the fight between Oracle and Google over a small number of lines of code from test or something. And I was wondering, since the code is properly attributed with the link and the license, why is that part done, but not the other part of the license?

If I were the owner of the repo, I would probably respond the same way, but isn't it equal to saying: I don't care about that license? Why mention it then?

**Comment by leastprivilege** [comment]
When Microsoft started using IdentityServer in their templates, they scanned the code. We actually added the comment based on the feedback from their legal department. So I assumed this is OK.
