### ISSUE TITLE
Require authentication to get client credentials access token

### ISSUE THREAD

**Issue by natelaff** [IdentityServer/IdentityServer4#5245]
This is conceptual, because I'm thinking there may be a better way to do this flow. I couldn't tell if extension grants were the way to go, or client credentials. And since stackoverflow doesn't like conceptual, I'm posting here.

I have a public native mobile app that has users with their own permission sets. The device can be put into a "public" mode, where a an anonymous person is handed the device and needs to fill out data. To do this, they may need additional permissions that the original authenticated user does not have.

My first attempt at this was client credentials, which is great. I can add any permissions I need that client to have, and can set the name of the client for auditing to know the object was created in this mode. However, it's obviously not very secure.

So, I started thinking "maybe I just make an API that an authenticated user can call which will return an access token for that client". This way it's somewhat protected, but I'm wondering what the "right" way to do this would be.

Extension grants seem interesting and maybe the way to go? But any documentation on it didn't seem to match my use case where I want to basically change the identity to this public client.

Thanks for any input!

**Comment by amadard** [comment]
Extension grants can do this.  Pass in the token from the authenticated user, which you can then validate, and if valid generate a new token as you want.

This isnt too different from delegation, so look at that write up:  https://github.com/IdentityServer/IdentityServer4/issues/3945

Not saying this is the right way to do it, but just that grants can do what you are thinking of.

**Comment by amadard** [comment]
Getting the previously logged in user a new access token is based on session lifetime.  If the session is still alive, get a new access token, otherwise re-authenticate the user and get a new access token.

"Access tokens don't reflect the user's "logged-in-ness""
