### ISSUE TITLE
A Refresh_token request issued with different scopes is ignored when issued 

### ISSUE THREAD

**Issue by whatisthejava** [IdentityServer/IdentityServer4#5256]
I want to use the refresh flow to extend my scopes.  (First question is this allowed) 

I created this request 
````
 new RefreshTokenRequest
                {
                    Address = disco.TokenEndpoint,
                    GrantType = "refresh_token",
                    ClientId = "mvc",
                    ClientSecret = "secret",
                    RefreshToken = refreshToken,,
                    Scope = "newscope"
````
The IdentityServer client is Allowing it 
````
              new Client
               {
                     AllowedScopes = new List<string>
                     {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        "newscope"
                    }
````
The client is expecting it 
````
 .AddOpenIdConnect("oidc", options =>
            {
                options.ClaimActions.MapUniqueJsonKey("a", "a");
                options.Scope.Add("newscope");
````
After creating and issueing the request, I can see the request is received by the identity server 

````

[15:58:58 Information] IdentityServer4.Validation.TokenRequestValidator
Token request validation success, {"refresh_token": "***REDACTED***", **"scope": "newscope"**, "}, "$type": "TokenRequestValidationLog"}
````
 In the IdentityServer class IdentityServer4.ResponseHandling.TokenResponseGenerator the following method is called 

````
 protected virtual async Task<TokenResponse> ProcessRefreshTokenRequestAsync(TokenRequestValidationResult request)
        {
        // removed for clarity 
            if (request.ValidatedRequest.Client.UpdateAccessTokenClaimsOnRefresh)
            {
                var parsedScopesResult = ScopeParser.ParseScopeValues(**oldAccessToken.Scopes**);

        // removed for clarity 
````

As you can see the scopes from the request are ignored and the claims are just re-added from the old token.

I would suggest there are two solutions. 
Remove scopes/set to obsoloete from the RefreshTokenRequest.class 
or 
Populate the new scopes from the RefreshTokenRequest and not the old Access token,#

Im happy to submit a PR to fix this, but want to make sure that I implement the correct behaviour 
### Issue / Steps to reproduce the problem
Create a RefreshTokenRequest populating the scopes parameter with different claims 
Issue the RefreshTokenRequest  as expected

**Comment by brockallen** [comment]
> I want to use the refresh flow to extend my scopes. (First question is this allowed)

No: https://datatracker.ietf.org/doc/html/rfc6749#section-6

**Comment by whatisthejava** [comment]
Thanks for the response

Is there a flow which combines the functionality of the extension grant, but instead of creating two distinct access tokens 
(the first and the extension) 
will combine them into a single access token ?

**Comment by whatisthejava** [comment]
Im going to raise a PR, to update the documentation to inform people that extending scope is not available with the refresh token flow
