### ISSUE TITLE
Downstream sign out from remote IdP does not sign out clients on my idsrv4

### ISSUE THREAD

**Issue by nativenolde** [IdentityServer/IdentityServer4#5263]
hey folks,

i'm running an identity server 4.1.1 almost like the demo system, with some clients and microsoft azure as remote IdP.

when initiating the sign out remotely at microsoft azure, clients connected to my idsrv4 remain signed in, even though the federated sign out request is been handled.

```
[09:46:08 INF] Request starting HTTP/2 GET https://localhost:44315/signout-azure?sid=6e6cecbb-946f-4e5e-80d4-29740c197aba  
[09:46:08 DBG] The request path /signout-azure does not match a supported file type
[09:46:08 DBG] No candidates found for the request path '/signout-azure'
[09:46:08 DBG] Request did not match any endpoints
[09:46:08 DBG] AuthenticationScheme: idsrv was not authenticated.
[09:46:08 INF] Remote signout request processed.
[09:46:08 INF] AuthenticationScheme: idsrv signed out.
[09:46:12 DBG] AuthenticationScheme: idsrv was not authenticated.
[09:46:13 DBG] Processing federated signout
[09:46:13 DBG] AuthenticationScheme: idsrv was not authenticated.
[09:46:13 DBG] No signout callback iframe to render
[09:46:13 INF] Request finished in 5093.0408ms 200 
```

i noticed inside `FederatedSignOut.AuthenticationRequestHandlerWrapper` that `GetIdentityServerSignoutFrameCallbackUrlAsync` did not return a iframe url, which happens because there was no authenticated user session anymore... therefore the EndSessionCallback does not happen.

https://github.com/IdentityServer/IdentityServer4/blob/4c998dea822779d6a288fe56d81bb85fddcf9cc0/src/IdentityServer4/src/Hosting/FederatedSignOut/AuthenticationRequestHandlerWrapper.cs#L69-L83

https://github.com/IdentityServer/IdentityServer4/blob/4c998dea822779d6a288fe56d81bb85fddcf9cc0/src/IdentityServer4/src/Extensions/HttpContextExtensions.cs#L183-L196

if the user initiates the signs out locally at one of my clients, the federated sign out round trip via azure works perfectly fine and all clients are being signed out afterwards.

is anyone of you folks also facing this issue?

**Comment by brockallen** [comment]
Have you configured a FrontChannelLogoutUri or BackChannelLogotUri for your clients?

**Comment by nativenolde** [comment]
The clients are using Front Channel Logout Url

**Comment by brockallen** [comment]
You should debug the iframes and why they are not working.

**Comment by nativenolde** [comment]
The federated sign out call from azure arrives at the IdentityServer `FederatedSignOut.AuthenticationRequestHandlerWrapper` that calls the `HttpContextExtensions.GetIdentityServerSignoutFrameCallbackUrlAsync` which does not return a signout iframe url because the user is already signed out... So the end session endpoint is not called, and therefore my clients stay signed in.

I am trying to figure out, why there is no user when the federated sign out is processed.

https://user-images.githubusercontent.com/45496636/121029836-39ea7800-c7a9-11eb-8f9d-b759ada880db.mp4

**Comment by nativenolde** [comment]
I've got that part working now, at least local. The authentication cookie was not loaded into the remote sign out request iframe incoming from azure. That seemed to be caused by `Lax` same-site mode used by the authentication cookie, changing to `None` (default anyway) fixes that.

On the server, the iframe still does not load the authentication cookie.

Still investigating...

**Comment by nativenolde** [comment]
To add a context, we use an explicit identity server origin to make reverse proxy scenarios a bit easier for our on-premise customers... 

just wild guessing, but could the application path or auth cookie issuer conflict with that explicit identity server origin, so that the iframe wont load the auth cookie?
