### ISSUE TITLE
Logout from all clients is not working

### ISSUE THREAD

**Issue by ebinroy** [IdentityServer/IdentityServer4#5265]
Hi All, I am using identity server Version="4.0.0" I would like to implement sign-out from all clients when a client logout. I am trying backoutchannel logout.

**For example : -** I have below applications URL connected to the IS. When Client MVC1 logout from the URL https://localhost:5002/ other client also should be logout. I go through the IS documentation they are saying to add the backoutchannelURL

https://localhost:5002/ (Client: MVC1, BackChannelLogoutUri: https://localhost:5002/home/logout)
https://localhost:5003/ (Client: MVC2, BackChannelLogoutUri: https://localhost:5003/home/logout)
https://localhost:5004/ (Client: MVC3, BackChannelLogoutUri: https://localhost:5004/home/logout)

**IS--> accountController**
```
[HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Logout(LogoutInputModel model)
    {
        // build a model so the logged out page knows what to display
        var vm = await BuildLoggedOutViewModelAsync(model.LogoutId);

        if (User?.Identity.IsAuthenticated == true)
        {
            // delete local authentication cookie
            await HttpContext.SignOutAsync();

            // raise the logout event
            await _events.RaiseAsync(new UserLogoutSuccessEvent(User.GetSubjectId(), User.GetDisplayName()));
        }

        // check if we need to trigger sign-out at an upstream identity provider
        if (vm.TriggerExternalSignout)
        {
            // build a return URL so the upstream provider will redirect back
            // to us after the user has logged out. this allows us to then
            // complete our single sign-out processing.
            string url = Url.Action("Logout", new { logoutId = vm.LogoutId });

            // this triggers a redirect to the external provider for sign-out
            return SignOut(new AuthenticationProperties { RedirectUri = url }, vm.ExternalAuthenticationScheme);
        }

        return View("LoggedOut", vm);
    }
```

**MVC application --> Home/Logout**
The logout method is not being called.
```
       [HttpPost("Logout")]
        [AllowAnonymous]
        public IActionResult BackchannelLogout()
        {
            return SignOut("Cookies", "oidc");
        }       
```

Any idea about why it is not working? Anything wrong in my approach? Please help

**Comment by brockallen** [comment]
Did the user actually log into those 3 clients?

**Comment by ebinroy** [comment]
Yes all clients are login. I am going through your example Hybrid backlogout.  Making some changes on client side MVC app. Will update the result
