### ISSUE TITLE
[Question] Regarding license model

### ISSUE THREAD

**Issue by anktsrkr** [IdentityServer/IdentityServer4#5272]
### Question
I have some applications integrated with well established token provider. However, as per organization policy I'm not supposed to do performance test using that provider. As a alternate I was thinking to use ID4 as stubbed token provider in Pre-Prod env using in-memory data store. 

As per this scenario, All of my application willl use well established token provider for dev,uat and production. Only in Pre-Prod we want to use ID4 as stubbed token provider. 

As per new license model, testing is always free. But in my scenario is it still under FOSS?

**Comment by leastprivilege** [comment]
IdentityServer4 is under the Apache license (IOW free) and will stay like that.

You can also use 

https://duendesoftware.com/products/identityserver

for the above scenario, this is also free to non-production scenarios.

**Comment by anktsrkr** [comment]
Thanks for the clarification!
