### ISSUE TITLE
Confusing defaults for `RequireConsent`

### ISSUE THREAD

**Issue by Ghostbird** [IdentityServer/IdentityServer4#5276]
https://github.com/IdentityServer/IdentityServer4/blob/3ff3b46698f48f164ab1b54d124125d63439f9d0/src/IdentityServer4/src/Services/Default/DefaultConsentService.cs#L98-L104

This threw me for a loop, because when I added `offline_access` to a client (it already had in it allowed scopes for a while on the identity server), suddenly the consent screen started popping up. I couldn't find this in the documentation.

Is there a reason why this mechanism was chosen? Maybe an RFC recommendation or something like that?

**Comment by leastprivilege** [comment]
I think it was based on 

https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

Especially:

> The OP MUST always obtain consent to returning a Refresh Token that enables offline access to the requested resources

**Comment by Ghostbird** [comment]
Thanks for that answer, that explains a lot. Except that I can _still_ disable it explicitly, even though I'm not allowed to.
