### ISSUE TITLE
Login not working in multiple tabs

### ISSUE THREAD

**Issue by binshidhak** [IdentityServer/IdentityServer4#5282]
I opened login page of my application in two different tabs of the same browser
1 - Entered the credentials and clicked Login- Application is working as expected
2 - Then I came to second tab and entered  the credentials and clicked login - it is showing error 400.
I didn't get what exactly happened.  The hit is not happening in the OnPostAsync of login page in the second case to find out the exact issue.

Thankyou

**Comment by thohng** [comment]
Hi, this is a feature of ASP.NETCore https://docs.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-5.0
Or you can ask question on this repos https://github.com/dotnet/aspnetcore for further help.
