### ISSUE TITLE
Scope can be assigned even if it is not existing

### ISSUE THREAD

**Issue by bertschronja** [IdentityServer/IdentityServer4#5283]
### Issue
ClientScopes (ApiScopes and IdentityResources) can be assigned to clients even if the scopes do not exist.
Same applies for ApiResourceScopes that are not created in table ApiScopes.

### Steps to reproduce
Assign an ApiScope to a client (do NOT create it in ApiScopes)

**Comment by leastprivilege** [comment]
For context: you mean in the EF entity model.
