### ISSUE TITLE
Identity server 4 - GetToken slowness intermittently

### ISSUE THREAD

**Issue by vinayrkmr** [IdentityServer/IdentityServer4#5289]
### Question

We have implemented Identity server 4 for our API suite and we have a SLA of 10 secs for the clients that consume our service.

What we have observed is first request of the day to generate the token for all the clients takes around 6-7 seconds, subsequent request takes 100-200ms. 

We are unable to pinpoint the setting that is contributing to this, as we do not reset AppPool/IIS.

Any help here would be appreciated.
### Minimal working example

```csharp
   // <code goes here>
```

### Relevant parts of the log file

```
   <log goes here>
```

**Comment by ebinroy** [comment]
This would be an iis issue , you can reset this to change the app pool idle timeout to zero or 1 days
