### ISSUE TITLE
Test for ASP.NET Core 1.1

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#529]
Current builds, but update core references to 1,1

**Comment by brockallen** [comment]
Tested IdentityServer4 build rc4-update1 with our sample host updated to .NET Core 1.1 and ASP.NET Core 1.1 (all NuGets updated), and it worked fine with all of our samples. There was only one minor configuration addition needed for the external authentication middleware -- OIDC needed to add the `SignedOutCallbackPath` (for post logout redirect uri) to disambiguate the 2 OIDC middlewares (same as setting `CallbackPath`).

**Comment by brockallen** [comment]
The ASP.NET Identity quickstart worked with no problems with our IdentityServer4.AspNetIdentity rc4-update1.

**Comment by brockallen** [comment]
EF did not go as well as the others. EF 1.1 seems to have a breaking change: https://github.com/aspnet/EntityFramework/issues/7116#issuecomment-264664641.

**Comment by brockallen** [comment]
I was able to update IdentityServer4 core project to 1.1 and update and compile both of the unit test projects to 1.1. the unit tests ran fine, but many of the integration tests did not. Working on that next.

**Comment by brockallen** [comment]
Ok, the integration tests failing was due to a superfluous call we were making into the web host builder. i fixed it in dev (and in my AspNetCore11 testing) and now all the integration tests pass fine.

**Comment by brockallen** [comment]
So it seems that xunit is working with 1.1 -- what were the complains/issues with it?

**Comment by pjjwpc** [comment]
crit: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Unhandled exception: System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,!!2> Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ThenInclude(Microsoft.EntityFrameworkCore.Query.IIncludableQueryable`2<!!0,System.Collections.Generic.IColl
ection`1<!!1>>, System.Linq.Expressions.Expression`1<System.Func`2<!!1,!!2>>)'.
         at IdentityServer4.EntityFramework.Stores.ResourceStore.GetAllResources()
         at IdentityServer4.Stores.IResourceStoreExtensions.<GetAllEnabledResourcesAsync>d__2.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityServer4.Endpoints.DiscoveryEndpoint.<ExecuteDiscoDocAsync>d__9.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()
aspcore 1.1 efcore 1.1

**Comment by brockallen** [comment]
@pjjwpc yes, that's the EF issue I mentioned above. We're working on it.

**Comment by brockallen** [comment]
They seem to have acknowledged that there was a known breaking change in 1.1 (https://github.com/aspnet/EntityFramework/issues/7116#issuecomment-264919565). Makes me wonder why they released it...

**Comment by brockallen** [comment]
Ok, we're moving to only supporting 1.1.
