### ISSUE TITLE
Signing Key Management - Customize table name?

### ISSUE THREAD

**Issue by john--** [IdentityServer/IdentityServer4#5292]
Hi, 
We are trying out the automatic signing key functionality and we're evaluating things to see if it will fit our needs.
I understand you guys likely won't want to offer support until we buy our Duende license, however, I was hoping you could answer this question:

Is there a way to change the default table name from "SigningKeys" to something else? With the PersistedStoreExtension this was possible, but I'm not seeing the option for SigningKeyManagement.

current startup code looks like this

```
            service.AddSigningKeyManagement(
                    options =>
                    {
                        options.Licensee = "<...>";
                        options.License = "<...>";
                    })
                    .PersistKeysToDatabase(new DatabaseKeyManagementOptions
                    {
                        ConfigureDbContext = b => b.UseSqlServer(connectionString),
                    })
                    .ProtectKeysWithDataProtection();
```

**Comment by leastprivilege** [comment]
Hey, 

since key management was never part of IdentityServer4 - but is now part of our v5, could you ask the question on our now support forum instead?

https://github.com/DuendeSoftware/IdentityServer/discussions

**Comment by john--** [comment]
Sounds good, thanks
