### ISSUE TITLE
Inconsistent JWT token header "Typ" value

### ISSUE THREAD

**Issue by pnwright84** [IdentityServer/IdentityServer4#5294]
We are currently migrating from version 2.3.0 to 4.1.2 and have come across an inconsistency where IdentityServer4 has specified a default value for the AccessTokenJwtType 

https://github.com/IdentityServer/IdentityServer4/blob/fc9953a5c322396fdf9bc51167dcd3d7f869d277/src/IdentityServer4/src/Configuration/DependencyInjection/Options/IdentityServerOptions.cs#L32

compared to the actual value that's generated by the Token 

https://github.com/IdentityServer/IdentityServer4/blob/fc9953a5c322396fdf9bc51167dcd3d7f869d277/src/IdentityServer4/src/Services/Default/DefaultTokenCreationService.cs#L93

when converting from the AccessTokenType enum to a string (it uses a constant [defined here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/6f6b935c55ceff4b133a0bb2236fee1daa001c90/src/System.IdentityModel.Tokens.Jwt/JwtConstants.cs#L38)).

So when the following if statement runs the default value provided by IdentityServerOptions doesn't match what has been provided by the Token.
https://github.com/IdentityServer/IdentityServer4/blob/fc9953a5c322396fdf9bc51167dcd3d7f869d277/src/IdentityServer4/src/Validation/Default/TokenValidator.cs#L278

We only found this from stepping through the debugger to find out why our api controller kept getting a 401 when trying to access the userinfo endpoint.

https://github.com/IdentityServer/IdentityServer4/blob/fc9953a5c322396fdf9bc51167dcd3d7f869d277/src/IdentityServer4/src/Endpoints/UserInfoEndpoint.cs#L79

**Comment by leastprivilege** [comment]
I am not quite sure I understand - 

the typ value is set here

https://github.com/IdentityServer/IdentityServer4/blob/fc9953a5c322396fdf9bc51167dcd3d7f869d277/src/IdentityServer4/src/Services/Default/DefaultTokenCreationService.cs#L107-L113

This only happens if the typ is set on the options.
