### ISSUE TITLE
Setting ClientId dynamically at runtime

### ISSUE THREAD

**Issue by mashinchi** [IdentityServer/IdentityServer4#5296]
Hi All,

Is there any way to dynamically set the ClientId at runtime for openId connect? 
The reason for this is to support different client ids for each tenant in my app but using the same instance and single db for all the tenants. I tried to change the clientId in the event handlers like: OnRedirectToIdentityProvider but it doesn't work as the token validation process seems to take the clientId from the options at the initial config always.

I also tried to use OpenIdConnectPostConfigureOptions, but again didn't work.

Thanks for your support.

**Comment by RakshithVP** [comment]
I'm developing a Spring boot application where the authentication server is IdentityServer4. I have cloned this code and ran the identity server in my Linux. I tried to get access token via client credentials grant type and for the sample client id like "m2m" or "client" it always throws invalid client. As I'm very new to Dot net framework couldn't find out how to load sample clients and users for setting up a development environment. If you could share some info, it would be of great help.

Thanks in advance
