### ISSUE TITLE
Can I set `idsrv.session` cookie to `SameSite=Strict`?

### ISSUE THREAD

**Issue by mgh9** [IdentityServer/IdentityServer4#5297]

**Comment by mkeskes** [comment]
Check this [PR](https://github.com/IdentityServer/IdentityServer4/pull/4711)
`var identityServerBuilder = services.AddIdentityServer(options =>
 {
         options.Authentication.CheckSessionCookieSameSiteMode = SameSiteMode.Strict; 
 })
`

**Comment by joshua5822** [comment]
Is there any solution if you are still on asp.net core 2.x? The latest package points to asp.net core 3.x, so the property for setting this doesn't exist.

**Comment by joshua5822** [comment]
Never mind. I realized I could extend the DefaultUserSession and override the CreateSessionIdCookieOptions method to setup my own value for samesite. Then just needed to set DI for the IUserSession to my new implementation.
