### ISSUE TITLE
UserServiceBase missing from latest version ?

### ISSUE THREAD

**Issue by oferAshkenazy** [IdentityServer/IdentityServer4#53]
Hi
Using IdentityServer4 1.0.0-beta1-update1 version 
i am trying to use DB users for authentication
but i can't find UserServiceBase class ?

Thanks

**Comment by leastprivilege** [comment]
It's gone - check the archives or samples.

**Comment by oferAshkenazy** [comment]
I have done a search for a replacement class but no avail..
Hints please ?

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/IdentityServerBuilderExtensions.cs#L14
