### ISSUE TITLE
IdentityServer4 with Asp.Net Identity and External Authentication fails to sign out

### ISSUE THREAD

**Issue by girishnuli** [IdentityServer/IdentityServer4#530]
Steps to reproduce:

1. Download the asp.net identity quickstart:
https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/6_AspNetIdentity

2. Add google authentication nuget package

3. Configure Google Authentication:
3a. In Startup.cs, ConfigureServices method:

services.AddIdentity<ApplicationUser, IdentityRole>(x=> { x.Cookies.ExternalCookie.AuthenticationScheme = "Google"; })

3b. In Startup.cs, Configure method:

           app.UseIdentity();
           app.UseIdentityServer();

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
                AutomaticAuthenticate = false,
                AutomaticChallenge = false
            });

            app.UseGoogleAuthentication(new GoogleOptions
            {
                AuthenticationScheme = "Google",
                SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
                ClientId = "your client id",
                ClientSecret = "your client secret"
            });

Launch identity server and the mvc client. You should be able to login with google and register. Click the Logout button and you get the below error:

Specified method is not supported.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleSignOutAsync(SignOutContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<SignOutAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<SignOutAsync>d__14.MoveNext()

**Comment by brockallen** [comment]
I just added google to the ASP.NET Identity quickstart and it works fine. Can you check with the latest on the release branch?

**Comment by girishnuli** [comment]
@brockallen The new sample is working fine. Was there a change in rc4-update1 that solved the problem? Thanks.

**Comment by brockallen** [comment]
Possibly... maybe check the commit history for anything that sticks out. Anyway, I'll close this since it's working for you.
