### ISSUE TITLE
Multiple simultaneous sessions in a client

### ISSUE THREAD

**Issue by Merijn040** [IdentityServer/IdentityServer4#5303]
Hello,

We want to be able that a user can switch in the client between multiple identities without first signing out and then signing in again. I think this is called multi-session.

I've seen a couple of questions about this but they have been closed E.g. #717 and #4962. 

Everything seems to work just fine, except signout. In our call to end_session always the most recent session is ended no matter what id_token_hint we provide.

Is multi-session simply not supported? Or are we doing something wrong? If it is not supported, what would be the best approach to implement it myself?

Any help is greatly appreciated!

**Comment by leastprivilege** [comment]
Multi-session is not supported and would require changing the internal of IdentityServer.

**Comment by Merijn040** [comment]
That is a short and clear answer :-)

As far as I understand, this is to a large extent because the authentication/session cookie contains a single session. Is that right?

But what if 1) the cookie holds some sort of a client identifier and not the session itself; 2) the server keeps track of a collection of sessions per client identifier, and 3) the requests to idsrv4 contain an optional id_token_hint to index a particular session. Then, with the cookie, the server can retrieve all sessions and with the id_token_hint can find the requested sessions and authenticate the user accordingly. If no hint is available, the most recent session is used. 

I'm probably missing a couple of things and/or you might have considered this already, but since this is an urgent thing for us, I would like to understand it and, if possible, help to get it in. Is it on the roadmap already?

**Comment by leastprivilege** [comment]
You probably know that we stopped adding new features to this code-base.

All new development is happening here:
https://github.com/DuendeSoftware/IdentityServer

there's even an open issue
https://github.com/DuendeSoftware/IdentityServer/issues/34

but that has not been prioritized yet

**Comment by Merijn040** [comment]
I'll put my further questions, suggestions, and remarks on DuendeSoftware then.

Still one more question though. We noticed that the authentication cookie is shared between different applications (with different client-ids) which are controlled by a single identity server instance. This means that the identities of these distinct applications can (and will) interfere if they're used in the same browser. That is, if I first sign in as John on application A and then as user Nigel on application B, John gets an error message when signing out because the authentication cookie holds information about Nigel. 

Is this expected behavior or a bug? What is the proposed way to deal with this?

**Comment by merijndejonge** [comment]
@leastprivilege do you have an answer to my question about interference between different client applications in the same browser?

**Comment by leastprivilege** [comment]
yes. this is expected

https://github.com/IdentityServer/IdentityServer4/issues/5303#issuecomment-877160942
