### ISSUE TITLE
Tokens are not cleared from cache when they are revoked using RemoveAllGrantsAsync()

### ISSUE THREAD

**Issue by eddex** [IdentityServer/IdentityServer4#5304]
### Issue / Steps to reproduce the problem

I want to revoke a session without knowing the refresh or access token. I use the `IPersistedGrantService` to do this:
```c#
persistedGrantService.RemoveAllGrantsAsync(userId, sessionId: session);
```

I also use caching which is set up as follows (using `IdentityServer4.AccessTokenValidation` 3.0.1):
```c#
services.AddIdentityServerAuthentication("Bearer", options =>
{
    ...
    options.EnableCaching = true;
    options.CacheKeyPrefix = "my-cache-prefix";
    options.CacheDuration = TimeSpan.FromMinutes(cacheDuration);
    options.SupportedTokens = SupportedTokens.Reference;
   ...
});
```

When the `RemoveAllGrantsAsync()`-method is called, the refresh- and access-tokens are deleted from the database. However, the cached data is not removed from the cache and since the cookies are not cleared on the client side, they can still be used until the cache is invalidated.

As far as I could see in the IdentityServer code, the `RemoveAllGrantsAsync()`-method doesn't consider the cache at all. Is there another way to do this that clears the cache?

**Comment by leastprivilege** [comment]
The introspection client-side cache cannot know that you deleted the entry from the database. You should keep that cache very short-lived. e.g. 10 seconds or so.

**Comment by eddex** [comment]
I'm using the cache to improve performance. I have set the `cacheDuration` to the expiration time of the access-token to avoid calling the database over and over again. Should I not be doing this?

And is there a way to figure out which key in the cache belongs to a token?

**Comment by leastprivilege** [comment]
By doing that you are defeating the main purpose of reference tokens - which is revocability.

There is no connection between the API side cache and the IS side stored grants - classical stale cache entry problem.

**Comment by eddex** [comment]
Alright, got it. Thanks for taking the time to answer Dominick!
