### ISSUE TITLE
Should access level criteria be returned from the userinfo endpoint?

### ISSUE THREAD

**Issue by David-Jacobsen** [IdentityServer/IdentityServer4#5305]
### Question
Should access level criteria be returned from the userinfo endpoint?

We are using windows security groups to control whether a user has access to an API or not. Because of this, we have added the windows groups into a role claim within the access_token, and they are not included in the id_token nor the userinfo endpoint.

However, the [sample for the userinfo](https://docs.identityserver.io/en/latest/endpoints/userinfo.html) endpoint is showing roles being returned, which I assume would be used by the API to dictate access to specific endpoints/functionality.

Is it following standard usage to include roles in the userinfo endpoint (and I assume to also be in the id_token optionally returned with the access_token)?

**Comment by leastprivilege** [comment]
The userinfo endpoint is just an alternative way to return claims to the client - as opposed to the id_token. 

IOW - this is not an access token concept, nor should an API query userinfo.

**Comment by David-Jacobsen** [comment]
Thank you, however I think I wasn't clear and worded the question poorly.

The example for userinfo shows the userinfo endpoint returning the role claim, with sample values of user and admin. As these roles would typically be used to control access to resources, shouldn't they be in the access_token and not included in the userinfo endpoint?

Every example from the [spec](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse) are claims that contain PII information about the end-user. 

Perhaps a more succinct question is, We are including windows security groups in the 'role' claim in our access_tokens in order for resources to identify what access to permit. Is there anything wrong with including those roles in the userinfo response as well?

**Comment by brockallen** [comment]
> Is there anything wrong with including those roles in the userinfo response as well?

No, as long as the client needs them (unrelated to the API).

https://brockallen.com/2017/11/07/the-userinfo-endpoint-is-not-designed-for-apis/

**Comment by David-Jacobsen** [comment]
Ok. Thank you.

Sent from my iPhone

On Jul 15, 2021, at 9:47 AM, Brock Allen ***@***.***> wrote:

﻿

Is there anything wrong with including those roles in the userinfo response as well?

No, as long as the client needs them (unrelated to the API).

https://brockallen.com/2017/11/07/the-userinfo-endpoint-is-not-designed-for-apis/
