### ISSUE TITLE
Should ClientStoreCache & ConfigurationStoreCache be "thread safe"?

### ISSUE THREAD

**Issue by nzandy** [IdentityServer/IdentityServer4#5313]
Hi all.

We are in the process of "turning on" our new Identity Service (built using IdentityServer4) in production for a large, relatively high traffic web application.

The first few times after switching on we faced quite a few performance issues, which eventually ground our web app to a halt.

The original issue we found was that every time a user navigated to identity server, we were performing ~12 queries to our database to fetch the client & general configuration. After some quick googling we found that we should add caching as follows:
```
		.AddInMemoryCaching()
                .AddClientStoreCache<IdentityServer4.EntityFramework.Stores.ClientStore>()
                .AddConfigurationStoreCache()
                .AddResourceStoreCache<IdentityServer4.EntityFramework.Stores.ResourceStore>()
```

This has worked great. However we are now facing a new potential issue.

In the recent scenario, the cache expired whilst we had roughly ~220 requests in progress (our max number of threads available on web app currently). What I would have expected to happen would be that the first request would update the cache whilst the following requests waited until the cache was updated.

Instead, the behaviour that we saw was that all 220 requests attempted to update the cache by performing those large number (~12) of queries for each request. We believe that this eventually led to long blocking whilst waiting for DB connections to free to perform these queries.

The way we verified this behavior was looking at individual requests leading up to the cache expiry - all requests before the cache expiry made no calls to the DB to fetch configuration (because they were retrieving from cache) However as soon as the 30 minute cache period expired, we noticed that a large number of requests were all of a sudden performing the 12 queries.

This eventually led to our app becoming unresponsive, and we are not sure exactly how to proceed at this stage. (The first thing we will do it try to replicate this behaviour locally with some load testing and simulating cache expiry, but will be non trivial).

In the meantime I thought I would post here just incase anyone had any suggestions, or had experienced the same issues that we have?

If any further information would be helpful then don't hesitate to ask.

**Comment by amadard** [comment]
Not all of IMemoryCache is thread safe, I have built workarounds for MemoryCache.GetOrCreateAsync dbecause it does not appear to be thread safe:

https://github.com/aspnet/Caching/blob/56447f941b39337947273476b2c366b3dffde565/src/Microsoft.Extensions.Caching.Abstractions/MemoryCacheExtensions.cs#L92-L106

If you are having threading issues, I recommend moving away from IMemoryCache and a building your own implementations of the caches.
