### ISSUE TITLE
Identity JWT token not a strict base64 string

### ISSUE THREAD

**Issue by rajagemini** [IdentityServer/IdentityServer4#5318]
Hi,

 We have upgraded to idserv4 recently and the access token issued with jwt is not a strict base64 string, means we have to append padding to get string from base64 string for access token payload. I would like to know is there anything we are missing in upgrade which prompt jwt payload(header and signature looks fine) to not returning the character divisible by 4. Since we haven't faced this before(using quite a long time) want to know if we can solve this from server side before going to change the client with adding padding character to get the expected string.

**Comment by brockallen** [comment]
JWTs are base64Url encoded, not base64 encoded. 

https://datatracker.ietf.org/doc/html/rfc7519#section-3
