### ISSUE TITLE
Login redirect not working for ImplicitFlow with client and server using same HostURL , rc4 update

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#532]
When using the Implicit Flow with the SPA and the IdentityServer4 hosted in the same application, after a successful login, the user is redirected back to the IdentityServer4 login page and not the SPA application or the consent page if activated.

**Comment by damienbod** [comment]
Code:
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/updateIdentityServerRc4/src/ResourceWithIdentityServerWithClient

**Comment by brockallen** [comment]
Can you show a fiddler trace please.

**Comment by damienbod** [comment]
Problem is on the server from the loin redirect to the following consent page per default, not client

**Comment by brockallen** [comment]
I don't understand.

**Comment by damienbod** [comment]
This was a routing problem which I caused by updating incorrectly. sorry

Greetings Damien
