### ISSUE TITLE
Can't reach identityserver 4 controller

### ISSUE THREAD

**Issue by Kirill-basic** [IdentityServer/IdentityServer4#5325]
Hi, i have a very simple question but i couldn't find any answers on the interner :(. I have 1 client app, 1 api and identityserver. Identity server only have a couple of controllers and one of them has method of changing password protected with authorize attribute.

When accessing this method from identityserver everything works great, i can easily access this method. But when trying to request this method from client i am being redirected to the login page, though the access token is valid and not expired (i simply get 200 ok and being redirected to login page). But with the same token i can easily access my protected api.

What am i doing wrong and how can i access identityserver protected controller from external client?

**Comment by BloodyMettle** [comment]
Your access token will contain an API for which it is valid. The Identity Server controllers are not part of this API (different uri). 
I assume you'd have to register the identity server endpoints as an API Resource in your configuration and allow your client to access the API. Also you need to add BearerTokenAuthentication to these endpoints in some way, if it's not already added by IdentityServer itself.

**Comment by Kirill-basic** [comment]
> Your access token will contain an API for which it is valid. The Identity Server controllers are not part of this API (different uri).
> I assume you'd have to register the identity server endpoints as an API Resource in your configuration and allow your client to access the API. Also you need to add BearerTokenAuthentication to these endpoints in some way, if it's not already added by IdentityServer itself.

Yes. You are right. There is actually a default solution which i've tried before and it wasn't working. I've tried to realise it again and suprisingly it works. It might have been my mistake somewhere.

https://docs.identityserver.io/en/latest/topics/add_apis.html
