### ISSUE TITLE
Problems with running more than 1 instance of IdentityServer4 in Azure Kubernetes behind NGINX

### ISSUE THREAD

**Issue by micoskibojan** [IdentityServer/IdentityServer4#5328]
Hi, first time asking here so I apologize for not following guides or rules.
 
I am using version v3.1.4 of IdentityServer4 as an ASP .NET Core 3.1 application as a service on a linux docker image and deployed to an Azure Kubernetes cluster behind NGINX reverse proxy. The question I want to ask is, whether anyone has encountered a problem with "Unable to unprotect the message.State." when using IdentityServer 4 v3.1.4 with the setup I am describing bellow?

**My setup:**
I am using version IdentityServer4 v3.1.4 that uses Azure Active Directory as an external Identity Provider.
The application is running in ASP .NET Core 3.1 and is deployed on a docker linux pod and pushed to an Azure Kubernetes cluster, and is behind an NGINX. For data protection I am using Redis DB. 
I am using Azure SQL DB for the operational and configurational stores.

**More in detail about the problem**
We have noticed that whenever we scale to multiple pods per cluster of IdentityServer4 after the authentication is done from the clients side and the callback begins, it fails when it lands back in IdentityServer4 as if the DataProtection keys are not being shared properly and we get this error: 
"Unable to unprotect the message.State.','Data':null,'InnerException':null,'HelpURL':null,'StackTraceString':null,'RemoteStackTraceString':null,'RemoteStackIndex':0,'ExceptionMethod':null,'HResult':-2146233088,'Source':null,'WatsonBuckets':null},'HelpURL':null,'StackTraceString':'   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()\n   at IdentityServer4.Hosting.FederatedSignOut.AuthenticationRequestHandlerWrapper.HandleRequestAsync() ..."

**What have I tried:**
To make it a bit more clear I have tried distributed sharing the DataProtection keys in Redis DB also in the same Azure Kubernetes cluster and in a shared Azure SQL DB. 
I have tried overwriting the default protector when the protecting and unprotecting is being done and just modify it so it has to pass.
I have also tried a variety of NGINX configurations but nothing has worked to eliminate this issue. Also I do not have a sticky session enabled in NGINX.

Everything points to the keys are not properly shared but Just wondered if someone else encountered this as well?

**Comment by brockallen** [comment]
> The question I want to ask is, whether anyone has encountered a problem with "Unable to unprotect the message.State."

Sounds like a data protection problem:

https://identityserver4.readthedocs.io/en/latest/topics/deployment.html#asp-net-core-data-protection

**Comment by micoskibojan** [comment]
Thank you very much for the super fast answer I will redirect my question there, since I thought as much, but was not entirely sure.

**Comment by brockallen** [comment]
Well, I think if you read their docs, you should have the answer in there.

**Comment by micoskibojan** [comment]
Just a feedback, did the necessary changes added the state cache and it works now!
I found out where I got things wrong and saw that I had misunderstood the distributed state cache in the beginning, so I never looked back to check :) 

Thank you very much!
