### ISSUE TITLE
identityserver4 and asp net core spa

### ISSUE THREAD

**Issue by sna-king** [IdentityServer/IdentityServer4#5330]
I have created a project template by 

> dotnet new react -o project_name -au individual

So after scaffolding a react app with authentication and identity server, the following content was added to startup.cs file

    public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlite(
                    Configuration.GetConnectionString("DefaultConnection")));

            services.AddDatabaseDeveloperPageExceptionFilter();

            services.AddDefaultIdentity<ApplicationUser>(options =>
              {options.SignIn.RequireConfirmedAccount = true ; } )
                .AddEntityFrameworkStores<ApplicationDbContext>();

            services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

            services.AddAuthentication()
                .AddIdentityServerJwt();

            services.AddControllersWithViews();
            services.AddRazorPages();

            // In production, the React files will be served from this directory
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp/build";
            });
        }

as I read the Microsoft documentation, the `services.AddAuthentication().AddIdentityServerJwt();` is responsible for all request in /identity area path.
and also we have these identityserver configurations at the appsettings.json
```
"IdentityServer": {
    "Clients": {
      "project_name": {
        "Profile": "IdentityServerSPA"
      }
    }
  }
```
 the classic architecture recording to identityserver4 docs is that we have a client who is talking to identity server and make sure that everything about users are ok and retrieves their information and log then in... and in this case a token for an API. if you notice API is not a client is some sort of object and service(resources as they say). that means, the implementation of IDS(identityserver) is best for those who have a client which could be MVC app, and they might use some API and that they wanna protect so the MVC app call IDS to get a bearer token and it will use it in front page to request backend API in some pages.
till now everything is a nightmare for me who want to build a SPA and I don't want to make a mvc app just for requesting tokens (or yes that would be possible to make mvc app as a client and then create API controller but still I need to configure a separate IDS).
it seems Microsoft doesn't provide support asp .net core identity (alone) for web API and spa apps so we should use the identity server. 
but after I scaffold a react app as I said, it seems they try to reduce the pain combining the API app and identity server(i think I am wrong a bit because they may run on different servers host scope). but pretty sure the source code contains only one project in the solution, after this combination, my question is :

**1.what would be the architecture of the default generated SPA code**
I mean who is the client of the identity server? in the appsettings the project_name is set as the client and I think the created app SPA is both the client and API controller?
and one more important thing is the identity which has integration with IDS and they both use one database context

**2.where are these combined stuff?** 
the /identity area is actually the IDS so how can i customize the login page,registration page, user role and claims... they are not visible in the app source files and looks like the /identity area and its sub-controllers are pre built DLL files.
**what will happen if I just use the .net core identity** (the database API for creating user and middleware and annotations for authorization) and then create an identity controller for creating users, log them in by userManager... and is it even possible? because i just seeing the identity context and i never try to do that in action.

**Comment by brockallen** [comment]
For SPAs, the BFF pattern is the more secure and reliable approach:

https://blog.duendesoftware.com/posts/20210326_bff/

https://docs.duendesoftware.com/identityserver/v5/bff/

**Comment by sna-king** [comment]
> For SPAs, the BFF pattern is the more secure and reliable approach:
> 
> https://blog.duendesoftware.com/posts/20210326_bff/
> 
> https://docs.duendesoftware.com/identityserver/v5/bff/

in my opinion, the whole IdentityServer is not suitable for SPAs
managing and Authorizing user seems to be a huge deal as there is not any possibility to Authorize user by they roles because of token authentication.

**Comment by brockallen** [comment]
> in my opinion, the whole IdentityServer is not suitable for SPAs

Perhaps not in the way that the visual studio templates has arranged things. But perhaps you're missing the forest from the trees. Do you need token based security is the first question (which is a question independent of IdentityServer). Once you've decided you do, then you can consider which token server works best for you (that's where IdentityServer comes in).

> managing and Authorizing user seems to be a huge deal as there is not any possibility to Authorize user by they roles because of token authentication.

I think you're confused about something. Tokens are simply an abstraction for proof of identity and they can model anything you want. That's not incompatible with authorizing users.

**Comment by sna-king** [comment]
For some reason, Microsoft like to actually push people to use identity server when they are trying to build SPA and web API
[according to Microsoft docs](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-5.0&tabs=visual-studio):
""ASP.NET Core Identity adds user interface (UI) login functionality to ASP.NET Core web apps. To secure web APIs and SPAs, use one of the following:
- Azure Active Directory
- Azure Active Directory B2C (Azure AD B2C)
- IdentityServer4
""
of course, I  think it is possible to create an MVC client (which also is responsible for my front react app ) and then configure a separate Identity server and ... but that would be a little expensive and time-consuming design.
>Perhaps not in the way that the visual studio templates has arranged things

the reason that I am trying to get along and learn this template is that they come with this built-in identity server and .net core identity support which I like.
>But perhaps you're missing the forest from the trees.

federating authentication, OAuth2, OpenID connect and all of these things are good but I just wanna use an authentication system and design for a single SPA app and I want to do it efficiently but yeah I am basically new to idntityserver .
>I think you're confused about something. Tokens are simply an abstraction for proof of identity and they can model anything you want. That's not incompatible with authorizing users.
I agree with you but my problem here is about modeling them. 
I tried to follow [this post] (https://themisir.com/adding-role-claim-to-identity-server-4/) to get claims but it was hard to convert that implementation to my setups with dotnet template:
```C#
services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options =>
                {
                    options.IdentityResources.Add(
                        new IdentityResource("roles","roles", userClaims: new List<string> { "role" })
                    );
                    options.ApiScopes.Add(new ApiScope("roles"));

                   /* options.Clients.AddIdentityServerSPA(
                        "newreact", spa =>
                            spa.WithScopes("openid profile roles"));*/

                });
```

and I do some part of configs in `appsetting.json` because if I fully configure identity server in code I get some error in my react app failing to get configuration for authService .
`appsetings.json`
```JSON
  "IdentityServer": {
    
    "Clients": {
      "newreact": {
        "Profile": "IdentityServerSPA",
        "Scopes":"openid token profile roles"
        
      }
    }
  }
```
for test i create this method:
```C#
[HttpGet("getUser")]
         public Array getUser()
        {
         return ControllerContext.HttpContext.User.Claims.Select(c => new { c.Type , c.Value ,c.Properties}).ToArray() ;  
        }
```
(above codes are in a controller class with [Authorize] annotation )
the result I get:
```JSON
[
    {
        "type": "nbf",
        "value": "1629493529",
        "properties": {}
    },
    {
        "type": "exp",
        "value": "1629497129",
        "properties": {}
    },
    {
        "type": "iss",
        "value": "https://localhost:5001",
        "properties": {}
    },
    {
        "type": "aud",
        "value": "newreactAPI",
        "properties": {}
    },
    {
        "type": "client_id",
        "value": "newreact",
        "properties": {}
    },
    {
        "type": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier",
        "value": "30e9858a-d26e-4e3b-b648-8ea8f14ba90d",
        "properties": {
            "http://schemas.xmlsoap.org/ws/2005/05/identity/claimproperties/ShortTypeName": "sub"
        }
    },
    {
        "type": "auth_time",
        "value": "1629493523",
        "properties": {}
    },
    {
        "type": "http://schemas.microsoft.com/identity/claims/identityprovider",
        "value": "local",
        "properties": {
            "http://schemas.xmlsoap.org/ws/2005/05/identity/claimproperties/ShortTypeName": "idp"
        }
    },
    {
        "type": "jti",
        "value": "ADB90C6EC970202B758DDF2C732F297B",
        "properties": {}
    },
    {
        "type": "sid",
        "value": "B1909B0E58B22A15EFF89D990E535079",
        "properties": {}
    },
    {
        "type": "iat",
        "value": "1629493529",
        "properties": {}
    },
    {
        "type": "scope",
        "value": "newreactAPI",
        "properties": {}
    },
    {
        "type": "scope",
        "value": "openid",
        "properties": {}
    },
    {
        "type": "scope",
        "value": "profile",
        "properties": {}
    },
    {
        "type": "http://schemas.microsoft.com/claims/authnmethodsreferences",
        "value": "pwd",
        "properties": {
            "http://schemas.xmlsoap.org/ws/2005/05/identity/claimproperties/ShortTypeName": "amr"
        }
    }
]
```
