### ISSUE TITLE
prevent  repeat login

### ISSUE THREAD

**Issue by xiaohanlaila** [IdentityServer/IdentityServer4#5337]
### Question
Hi , dear senior,  the situation is  same account is logged in on different devices at the same time，how  can i prevent the first logged operation  or let him logout...And i don't kown how start

**Comment by xiaohanlaila** [comment]
Can  i  override some  filter?

**Comment by brockallen** [comment]
This would be a function of your login page logic.

**Comment by xiaohanlaila** [comment]
> This would be a function of your login page logic.

Ok, I know that , but  i just want to know if there were  integration some funcs...

**Comment by xiaohanlaila** [comment]
> This would be a function of your login page logic.

Anyway，thank you very much

**Comment by xiaohanlaila** [comment]
i know that
