### ISSUE TITLE
Any guidance for DB script of mysql with identity server 4

### ISSUE THREAD

**Issue by KamranShahid** [IdentityServer/IdentityServer4#5341]
I am trying to setup identity server with mysql but not able to find a single article regarding it.
Even tried https://identityserver4.readthedocs.io/en/latest/quickstarts/5_entityframework.html for sql server as test migration but getting error

dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb

PS D:\NewWorkingFolder\test\IdentityServerPractices\ClientCredntials\quickstart\src\IdentityServer> dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.7' was not found.
  - The following frameworks were found:
      3.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Can anyone atleast shared DB script of mysql against which i can try to run identity server 4

**Comment by brockallen** [comment]
It's just normal EF. Here's a sample we use to create the SqlServer scripts:

https://github.com/IdentityServer/IdentityServer4/tree/main/src/EntityFramework.Storage/migrations/SqlServer

So you could take this and rework for MySql.

**Comment by KamranShahid** [comment]
> It's just normal EF. Here's a sample we use to create the SqlServer scripts:
> 
> https://github.com/IdentityServer/IdentityServer4/tree/main/src/EntityFramework.Storage/migrations/SqlServer
> 
> So you could take this and rework for MySql.

I doesn;t have .net core 2.0 installed on my system. when i were trying i was getting following error
dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb

PS D:\NewWorkingFolder\test\IdentityServerPractices\ClientCredntials\quickstart\src\IdentityServer> dotnet ef migrations add InitialIdentityServerPersistedGrantDbMigration -c PersistedGrantDbContext -o Data/Migrations/IdentityServer/PersistedGrantDb
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.0.7' was not found.
  - The following frameworks were found:
      3.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      3.1.18 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

So simply looking for mysql schema instead of doing whole these migrations
