### ISSUE TITLE
How should I access SignOutPropertiesEntry of AuthenticationManager which I added at the time of logoff

### ISSUE THREAD

**Issue by hashimabbaz** [IdentityServer/IdentityServer4#5351]
### Question
Is there any way I could access SignOutPropertiesEntry of AuthenticationManager which I added at the time of log off?

Scenario:
1) When a user is forced to log out, then the client application can at the time of logout add in the property that the user is forced to log out. Now on RedirectToIdentityProvider when we check that the user is logged out and the user is redirected to identityware, we can get our property value on RedirectToIdentityProvider from SignOutPropertiesEntry of AuthenticationManager. This information can be sent to identityware by state 

2) When a user has manually logged out, then the client application can at the time of logout add in the property that the user has manually logged out.  Now on RedirectToIdentityProvider when we check that the user is logged out and the user is redirected to identityware, we can get our property value on  RedirectToIdentityProvider from SignOutPropertiesEntry of AuthenticationManager
This information can be sent to identityware by state 
### Minimal working example

```csharp

AccountController.cs
   public async Task<ActionResult> LogOutUser(string logouttype, string logoutstate)
        {
            var properties = new AuthenticationProperties();
            properties.Dictionary.Add("type", "automatic");
            properties.Dictionary.Add("state", "forced");

            SignInManager.AuthenticationManager.SignOut(properties, OpenIdConnectAuthenticationDefaults.AuthenticationType, CookieAuthenticationDefaults.AuthenticationType);
        }
startup.cs
private Task RedirectToIdentityProvider(RedirectToIdentityProviderNotification<OpenIdConnectMessage, OpenIdConnectAuthenticationOptions> context)
        {
            if (context.ProtocolMessage.RequestType == OpenIdConnectRequestType.Logout)
            {
                var signoutproperty = ((Microsoft.Owin.Security.AuthenticationManager)((Microsoft.Owin.OwinContext)context.OwinContext).Authentication).SignOutPropertiesEntry;
            }
        }
```

### Relevant parts of the log file

```
  error CS1061: 'IAuthenticationManager' does not contain a definition for 'SignOutPropertiesEntry' and no accessible extension method 'SignOutPropertiesEntry' accepting a first argument of type 'IAuthenticationManager' could be found (are you missing a using directive or an assembly reference?)
```

**Comment by hashimabbaz** [comment]
@brockallen can you please reply to my question

**Comment by brockallen** [comment]
Isn't it on the context somewhere? I forget exactly where.

**Comment by hashimabbaz** [comment]
@brockallen Can you please let me know where? I can only access this property through the quick watch feature of the visual studio by using be code:
((Microsoft.Owin.Security.AuthenticationManager)((Microsoft.Owin.OwinContext)context.OwinContext).Authentication).SignOutPropertiesEntry;

I want to access the properties on RedirectToIdentityProvider if it is possible to set the state property accordingly.
