### ISSUE TITLE
.NET 6 Support

### ISSUE THREAD

**Issue by vasicvuk** [IdentityServer/IdentityServer4#5354]
### Question

I wanted to know will you accept a Pull Request for supporting .NET 6 when it is released ? I see that the repo will be maintained until 2022 but I am not sure if this include switching to .NET 6 since it would be released this year and it is new LTS.

**Comment by leastprivilege** [comment]
Thanks! We are not doing any updates anymore to this code-base.

We just released a .NET 6 compatible update over here:
https://github.com/DuendeSoftware/IdentityServer

**Comment by vasicvuk** [comment]
@leastprivilege So you will not accept is even if someone else does it?
