### ISSUE TITLE
Response of "connect/authorize/callback" sends ConsentResponse cookie

### ISSUE THREAD

**Issue by msschl** [IdentityServer/IdentityServer4#5377]
Although consent is not required (set by the client settings), the "connect/authorize/callback" endpoints sends a cookie named "ConsentResponse.{Id}"=. 
```
Set-Cookie: ConsentResponse.Mpe9ObwEdnlkUYGDrt6DzwVcKpt--sfnaYI2te6clq0=.; expires=Fri, 31 Dec 1999 23:00:00 GMT; path=/; secure; httponly
```

I traced this down to the [MessageCookie.ClearByCookieName](https://github.com/DuendeSoftware/IdentityServer/blob/main/src/IdentityServer/Infrastructure/MessageCookie.cs#L136) function which always sets the content of the cookie to `.`, regardless of whether the cookie even exists in the first place or not.

My observations:
In the final block of the `ProcessAuthorizeRequestAsync` method in the `AuthorizeEndpointBase.cs` class a call to the consent response store delete async method is made. This method calls the Clear method on the `MessageCookie<ConsentResponse>` class, which finally calls the `Clear` method on the `MessageCookie` class.

Suggestion:
Add a check whether the cookie is event present on the request before trying to clear the cookie.

**Comment by msschl** [comment]
Is this fixed?

**Comment by leastprivilege** [comment]
If this was acknowledged as a bug, it has been fixed in the new repo:

https://github.com/DuendeSoftware/IdentityServer
