### ISSUE TITLE
Use of Refresh Token in Native and SPA app

### ISSUE THREAD

**Issue by pampua84** [IdentityServer/IdentityServer4#5386]
Hi,
I have a question to which unfortunately I cannot find an answer.
Native or SPA apps in which a **secret is not associated** use the **AuthorizationCode Flow + PKCE** to get the various tokens, but how can they use the RefreshToken to get a new AccessToken and IDToken, since the endpoint /connect/token also wants the client_secret among the parameters, like this:

```
POST /connect/token

    client_id=client&
    client_secret=secret&
    grant_type=refresh_token&
    refresh_token=hdh922
```

 Unfortunately, I have not found any useful info on the doc on the internet. 
Can you please help me understand how to do this?
Thanks.

**Comment by brockallen** [comment]
The `Client` config has a `RequireClientSecret` that you can set to `false`:

https://docs.duendesoftware.com/identityserver/v5/reference/models/client/#basics

We don't recommend refresh tokens in SPAs though:

https://blog.duendesoftware.com/posts/20210326_bff/

**Comment by pampua84** [comment]
Thanks, @brockallen for the reply. I have read the posts linked by you and they are very useful. Does the same thing also apply to native mobile apps?

**Comment by brockallen** [comment]
Native mobile is fine with refresh token and no client secret.
