### ISSUE TITLE
Clarification on what happens with IS4 after 2022

### ISSUE THREAD

**Issue by adminnz** [IdentityServer/IdentityServer4#5389]
> ...but to answer the question in the title of the issue.
> 
> "we" are still free. Nothing will change here 'til end of 2022. The new Duende IdentityServer will also stay open source - and also completely free for dev/testing as well as non-commercial open source projects.
> 
> _Originally posted by @leastprivilege in https://github.com/IdentityServer/IdentityServer4/issues/4953#issuecomment-706497581_
> 

After 2022 is IdentityServer4 still under Apache 2.0 and just that no development will be done on it?

**Comment by Blackclaws** [comment]
Since IdentityServer4 has been released under Apache 2.0 it will stay under that, or at the very least you can just fork it in its current state.

**Comment by leastprivilege** [comment]
We will archive the repo in Nov 2022. You can still use it of course.
