### ISSUE TITLE
how to create pfx file for prod servers

### ISSUE THREAD

**Issue by oferAshkenazy** [IdentityServer/IdentityServer4#539]
Hi
I would like to know which steps required for creating PFX file

Thanks

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
