### ISSUE TITLE
Can I see somewhere configuration of the public Demo Server

### ISSUE THREAD

**Issue by vzdesic** [IdentityServer/IdentityServer4#5397]
Can I see somewhere source code, or at least setup inside the Startup.cs file, of the https://demo.identityserver.io/ Identity Server? 

Maybe on Github?

Thanks,
Vedran

**Comment by brockallen** [comment]
Maybe :)

https://github.com/IdentityServer/IdentityServer4.Demo

**Comment by vzdesic** [comment]
Ah yes, this is it, of course! Thanks and sorry for me being in a hurry  :) ​
