### ISSUE TITLE
Finish off eventing programming model

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#540]

**Comment by brockallen** [comment]
Related: https://github.com/IdentityServer/IdentityServer4/issues/63

**Comment by mackie1001** [comment]
I don't suppose you have a link to anything that details what this feature entails/will entail do you?

**Comment by leastprivilege** [comment]
It's a port of this

https://github.com/IdentityServer/IdentityServer3/tree/master/source/Core/Events

But we wanted to get more reviews / discussions before we put into the current release.

**Comment by brockallen** [comment]
Still todo:
* TokenFailure events

**Comment by brockallen** [comment]
We now have 4 categories:
* User AuthN
* Client AuthN
* API AuthN
* Tokens

Can we just make it two?
* Authentication
* Tokens

**Comment by brockallen** [comment]
For now, it's baked
