### ISSUE TITLE
Multi-Tenant

### ISSUE THREAD

**Issue by learntecno** [IdentityServer/IdentityServer4#541]
I am using Identity Server4 , I want to save the IdentityResources and APIResource  I am using  IdentityServer4.EntityFrameworkCore and I want to save this by Tenant and I am using SASSKit for multi tenant , So I have create custom PersistedGrantDbContext as shown below.

    public class SqlServerPersistedGrantDbContext : DbContext, IPersistedGrantDbContext
{
public SqlServerPersistedGrantDbContext(DbContextOptions<SqlServerPersistedGrantDbContext> options, AppTenant tenant) : base(options)
        {           
            this.tenant = tenant;          
        }
       protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(tenant.ConnectionString);
            base.OnConfiguring(optionsBuilder);
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            //builder.ConfigurePersistedGrantContext(storeOptions);
            base.OnModelCreating(builder);
        }
} 

and In the Start up I have added as below , but the issue is calling UseIdentityServer middleware is called first  , then UseMultitenancy is called second , so because of this I could not able to get the Tenant object in the above class SqlServerPersistedGrantDbContext .  Please let me know how to solve this issue. or how to store IdentityResources and APIResource  in multi tenant environment.

            app.UseMultitenancy<AppTenant>();
            app.UsePerTenant<AppTenant>((ctx, builder) =>
            {

                builder.UseCookieAuthentication(new CookieAuthenticationOptions()
                {
                    AuthenticationScheme = $"{ctx.Tenant.Id}Cookies",
                    //LoginPath = new PathString("/account/login"),
                    //AccessDeniedPath = new PathString("/account/forbidden"),
                    AutomaticAuthenticate = false,
                    AutomaticChallenge = false,
                    CookieName = $"{ctx.Tenant.Id}.AspNet.Cookies"
                });
                builder.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
                {
                    Authority = ctx.Tenant.Authority,
                    AllowedScopes = { "api1" },
                    RequireHttpsMetadata = false
                });

            });
            app.UseIdentity();
            app.UseIdentityServer();

**Comment by brockallen** [comment]
How do you identity the tenant? DNS/host? QS param? Or acr_values tenant param? Also, does tenant mean to you customer isolated version of IdentityServer, or does tenant mean a way to distinguish different groups of users for authentication?

**Comment by brockallen** [comment]
I'm going to close this one as a dup of #593. Feel free to get involved over there. Thanks.
