### ISSUE TITLE
Automapper conflicts, update package.

### ISSUE THREAD

**Issue by isnakolah** [IdentityServer/IdentityServer4#5412]
Updating AutoMapper package in project throws version conflict error since the Duende.IdentityServer.EntityFramework.Storage 5.2.0 has a AutoMapper package requirement of (<=10.0.0 && < 11.0.0).

### Reproducing the issue
```
To reproduce, update an AutoMapper package to 11.0.0 in a project with IdentityServer4;
```

### Relevant parts of the log file

```

Version conflict detected for AutoMapper. Install/reference AutoMapper 11.0.0 directly to project RESTApi.Tests.Intergration to resolve this issue.  RESTApi.Tests.Intergration -> RESTApi -> Application -> AutoMapper.Extensions.Microsoft.DependencyInjection 11.0.0 -> AutoMapper (>= 11.0.0) 
 RESTApi.Tests.Intergration -> RESTApi -> Infrastructure -> Microsoft.AspNetCore.ApiAuthorization.IdentityServer 6.0.1 -> Duende.IdentityServer.EntityFramework.Storage 5.2.0 -> AutoMapper (>= 10.0.0 && < 11.0.0).	EPharmacy.RESTApi.Tests.Intergration	C:\Users\nakol\dev\work\e-pharmacy\server\tests\RESTApi.Tests.Intergration\RESTApi.Tests.Intergration.csproj	1	
```

**Comment by leastprivilege** [comment]
IdentityServer4 is "done" and there will be no more updates. You have to use the package it references.

All new development is happening here: https://github.com/DuendeSoftware/IdentityServer

**Comment by mamaly12** [comment]
Without any explanation, you will suddenly encounter an error when updating the package, and then you will see that this package is no longer supported, which is very professional behavior.

**Comment by mamaly12** [comment]
It was not professional behavior, @isnakolah use Microsoft Identity and write your own authentication mechanism for your project:

https://docs.microsoft.com/en-us/azure/active-directory/develop/
