### ISSUE TITLE
Allow multipart/form-data requests on token endpoints

### ISSUE THREAD

**Issue by lvandyk** [IdentityServer/IdentityServer4#5414]
We updating to the latest version of IdentityServer4 but we have one breaking change that removes the ability to use multipart-form-data on the token endpoint: https://github.com/IdentityServer/IdentityServer4/issues/4340

We currently have clients and apps configured to use multipart-form-data. We are making the fix to use form-url-encoded but what about the existing installations?

Is there a way to disable this check or to somehow create a middleware that will convert the request to form-url-encoded just before hitting the token endpoint logic?

Thanks!

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
