### ISSUE TITLE
AAD bypass login screen

### ISSUE THREAD

**Issue by greengumby** [IdentityServer/IdentityServer4#5415]
### Question

We are use Azure Active Directory to authenticate via ExternalProviders and this all sits behind an Azure Application proxy.  The proxy enforces authentication and currently redirects to the login screen of the website.  Once the user clicks on the sign in button it will re-authenticate and allow them into the site.

My question is as they are already authenticated to the proxy can I bypass clicking on the button in the login screen?

Thanks

**Comment by gterdem** [comment]
As a workaround, you can write javascript to trigger button (external login) click when it is loaded or in a time out.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
