### ISSUE TITLE
How to handle multiple cookie Authentication schemes?

### ISSUE THREAD

**Issue by mcrio** [IdentityServer/IdentityServer4#5416]
Hi, I have different cookie auth schemes to login `application users` vs `customers` who use 2 different SPA applications and oAuth clients. I keep them also separate having 2 different asp identity stores and services.

IdentityServer by default uses the default cookie scheme or the one set in the options.
Is there a way to use multiple schemes and so we can support issuing tokens for both the `application users` and the `customers` ?

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
