### ISSUE TITLE
How to return errors from IProfileService?

### ISSUE THREAD

**Issue by kwaazaar** [IdentityServer/IdentityServer4#5419]
### Question
My ProfileService implementation is pretty complicated and depends on external systems.
If exceptions occur during that communication, should I just throw an exception?
Exceptions result in a HTTP 500 response. I think I prefer another kind of error, similar to an invalid_grant, etc.

So are exceptions the way to go or is there another way?

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
