### ISSUE TITLE
Refresh UserClaims in Identity Server 4

### ISSUE THREAD

**Issue by ahmedtahami** [IdentityServer/IdentityServer4#5420]
### Problem:

I want to refresh user claims in identity server 4. I have made an API endpoint in identity server project. This API endpoint is given below. After that I call the UserInfoEndpoint and RefreshTokenEndpoint from my Angular Client using oidc-client.js library. I get the refreshtoken and new accesstoken but the claims in the response are old. I have to relogin in my client and identity server to reload the updated claims.

### API Code

```csharp
   if (ModelState.IsValid && model.IsSelected && User.Identity.IsAuthenticated)
                {
                    var user = _userRepository.GetUserByAppId(model.UserId);
                    user.AccessCode = model.Code; // A simple 3 digit code
                    var updatedUser = _userRepository.UpdateUser(user); //updating it in the dB
                    var claimsResult = _userRepository.GetUserClaims(updatedUser);
                    if (!claimsResult.IsSuccess)
                    {
                        return BadRequest(new { Status = false, Message = "Failed To Change" });
                    }
                    var identity = User.Identity as ClaimsIdentity;
                    string[] claimsTobeUpdated = { "AccessCode" };
                    foreach (var item in identity.Claims.ToList())
                    {
                        if (claimsTobeUpdated.Contains(item.Type))
                        {
                            identity.RemoveClaim(item);
                            var claim = claimsResult.Claims.Where(p => p.Type == item.Type).FirstOrDefault();
                            identity.AddClaim(claim);
                        }
                    } // I was updating more than one claims thats why I'm iterating
                    AuthenticationProperties props = new AuthenticationProperties()
                    {
                        IsPersistent = true,
                        ExpiresUtc = DateTimeOffset.UtcNow.Add(AccountOptions.RememberMeLoginDuration),
                    };

                    // issue authentication cookie with subject ID and username
                    var isuser = new IdentityServerUser(user.Id.ToString())
                    {
                        DisplayName = user.Name,
                        AdditionalClaims = claimsResult.Claims.ToList(),
                    };
                    await HttpContext.SignInAsync(isuser, props);


                    var claims = User.Identity as ClaimsIdentity; // here I've checked that the claims updated or not and these are updated.

                    return Ok(new { Status = true, Message = "Changed Successfully" });
                }
```

### Desired Output:

I want to have same claims in my identity server session as well as the Ng session. if you can help me it would be highly appreciated.

**Comment by ahmedtahami** [comment]
@brockallen Could you please help me?

**Comment by gterdem** [comment]
This is not directly related with identityserver. Maybe you want to check [this blog post about claim-based authentication](https://andrewlock.net/introduction-to-authentication-with-asp-net-core/#claims-based-authentication).

Basically, [UserClaimsFactory](https://github.com/IdentityServer/IdentityServer4/blob/ff6041bfa4e0d9930ded7602405b20bd0ccd2a34/src/AspNetIdentity/src/UserClaimsFactory.cs#L26) creates a claims principal using _user manager_. And this happens **during the sign in process**. You can only add custom claims **during** the sign in process with using claims factory.

Changing the logged in user **after** a user is signed in, is the concept of **impersonation**.
