### ISSUE TITLE
Monitoring of expiring credentials in ClientCredentials flow

### ISSUE THREAD

**Issue by ivannedyalkov** [IdentityServer/IdentityServer4#5422]
### Question

Hello folks,

We have created API with which the clients of our SSO can route their credentials (client_id, client_secret) with a mandatory expiration date. Now we need to start watching when they expire and if they have a few days left to let them know.

We have to somehow hook up to the authorization flow and intercept. To take a client and a secret and do some business logic. But we can't find a suitable place for that.

We also need access to ClientStore cache so that we do not make unnecessary SQL request.

----------------
- Middleware
- Override of one of the classes
- Event
- --------------

Some tips :)

Thanks

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
