### ISSUE TITLE
IdentityServer4 and CSP problem

### ISSUE THREAD

**Issue by pampua84** [IdentityServer/IdentityServer4#5424]
Hi everyone,
I have a problem with an application integrating with my IdentityServer4 based IdP. The problem is that when the user logs in to my IdP everything works, but then if I try the flow again and the user is already logged in and therefore the redirect on the application should take place directly without entering the email and password, the application crashes on the endpoint / authorize and in the browser I see this error: 
 
![image](https://user-images.githubusercontent.com/17255890/151453821-edf4cdc0-6ec0-4e36-b4af-51828ae56f20.png)

On the old version of IdetityServer 3 there was this functionality:

[https://identityserver.github.io/Documentation/docsv2/endpoints/csp.html](url)

 and then through the log I could have understood the problem, in version 4 how can I get the same result? 
Please can you help me? Hope i was clear.
Thank you,

**Comment by nileshmohite-code** [comment]
Same for me.

Error:
aspnetcore-browser-refresh.js:234 Refused to connect to 'ws://localhost:60519/identityserver/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
