### ISSUE TITLE
How to upgrade from Identity Server 4 v3.1.4 to v4.0.0 to not lose data?

### ISSUE THREAD

**Issue by Duke4848** [IdentityServer/IdentityServer4#5428]
I need to upgrade from IdS 4 to 4.0.0, a lots of tables change between 3.1.4 and 4.0.0 but I can't find any migration tool or process. I can upgrade my nuget packate to 4.0.0 and generate migration but it will drop and recreate the tables, what about data inside?

**Comment by brockallen** [comment]
Here are some upgrade guides to the latest: https://docs.duendesoftware.com/identityserver/v6/upgrades/

**Comment by Duke4848** [comment]
> Here are some upgrade guides to the latest: https://docs.duendesoftware.com/identityserver/v6/upgrades/

Thanks, that will do. Is there any official upgrade from IdS3 to IdS4 ? I got this covered by custom migration tool, but if there is a official way...
