### ISSUE TITLE
User gets access to a wrong account

### ISSUE THREAD

**Issue by diogonborges** [IdentityServer/IdentityServer4#5429]
Can anyone clarify how was this solved?

https://github.com/IdentityServer/IdentityServer4/issues/4466

It says it was solved but I would like know what is the release or pull request that solved it

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
