### ISSUE TITLE
Can I use Identity server 4 with asp.net web API 4.x and WPF , on-premises AD ? 

### ISSUE THREAD

**Issue by esraa2** [IdentityServer/IdentityServer4#5432]
Can I use Identity server 4 with asp.net web API 4.x and WPF , on-premises AD ?

**Comment by brockallen** [comment]
Sure: https://docs.duendesoftware.com/identityserver/v6/ui/login/windows/

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
