### ISSUE TITLE
Email claim is missing in AccountController.Callback

### ISSUE THREAD

**Issue by Duke4848** [IdentityServer/IdentityServer4#5433]
Basing on IdS4 samples I am reading external identity from temporary cookie when using external IdentityServer instance to obtain a token and then issue my own token. The external token contains email claim, but when I 
do this in the AccountController.Callback. Instead I get some kind of ADFS claims.

```
           // read external identity from the temporary cookie
            var result = await HttpContext.AuthenticateAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
```
the `result.Principal` already lacks the email claim that was present in the token issued by external identity provider. Why is it removed and instead I got these adfs claims.

Screenshot: https://i.stack.imgur.com/WAqKE.png

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
