### ISSUE TITLE
Identity Server Add Client with type interactive 

### ISSUE THREAD

**Issue by MonaElHaj** [IdentityServer/IdentityServer4#5434]
Hi Team,
I'm using asp.net core for my application 
and add identity server 
my problem is when I added interactive client as documentation 
this error  "Unknown client or client not enabled" appear
what's maybe wrong? 

![Screenshot 2022-03-10 143304](https://user-images.githubusercontent.com/101334610/157662643-bb08625f-1aa1-4e18-8e8b-b44ac645eb62.png)

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
