### ISSUE TITLE
I am trying to override, ValidateAllowedCorsOriginsAsync, to handle iOS origin, but not sure how to hook the derived class to IdentityServer4 to use it. Is there an example or can you provide a link for instruction

### ISSUE THREAD

**Issue by hubaozhang2017** [IdentityServer/IdentityServer4#5438]

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.

**Comment by hubaozhang2017** [comment]
I figured out the problem. Here are steps: 
(1) Create a class, 
`	public class CustomClientConfigurationValidator : DefaultClientConfigurationValidator
	{
        readonly IConfiguration _configuration;
        public CustomClientConfigurationValidator(IConfiguration configuration)
            :base()
        {
            _configuration = configuration;
        }
        protected override Task ValidateAllowedCorsOriginsAsync(ClientConfigurationValidationContext context)
		{}
        }`
        
(2) Add AddClientConfigurationValidator<CustomClientConfigurationValidator> to services
`		var identityServerBuilder = services.AddIdentityServer()
				.AddSigningCredential(new X509Certificate2(certPath, "", X509KeyStorageFlags.MachineKeySet))
				.AddClientConfigurationValidator<CustomClientConfigurationValidator>()
				;`
