### ISSUE TITLE
ServerTooBusyException while accessing services through identity server 4

### ISSUE THREAD

**Issue by ShreyaSingh098** [IdentityServer/IdentityServer4#5440]
We are using identity server 4 in our application. 
There are 2 servies which are used by identity server for user authentication.Identity server 4 hosts these App services through WCF. 
sometimes, during login, these services are not resolves and an exception is thrown at identity server with below details:

exception type: System.ServiceModel.ServerTooBusyException

Message: One or more errors occurred. (The HTTP service located at <Service Path> is unavailable.  This could be because the service is too busy or because no endpoint was found listening at the specified address. Please ensure that the address is correct and try accessing the service again later.) The HTTP service located at <Service path> is unavailable.  This could be because the service is too busy or because no endpoint was found listening at the specified address. Please ensure that the address is correct and try accessing the service again later.

This error occurs intermittently on identity service, CAUSING SOME USERS TO LOGOUT OF APPLICATION. Most of the time it works fine but sometimes, this error is thrown. We could not identify any particular pattern or cause for this.
We also suspected that this might be an issue with App service, so we raised a ticket for that as well, but it seems that app service works fine in this case. We are not able to identify what might be issue with identity server in this case.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
