### ISSUE TITLE
How to handle multiple client

### ISSUE THREAD

**Issue by gundogduhasan** [IdentityServer/IdentityServer4#5441]
Hello,

First of all thanks for this great project. I hope my question is not unreasonable.
I have two javascript(angular) client almost same config. Only difference between clients, names, redirect urls, api scopes etc. I am using third party js library on front-end. Anyway, my first client works fine. But my second client return an error during silent-renew. I just can't figure out, this issue related with ID4 or front-end library. By the way i am using .net 6 with ID4. Could it be related with .net version?

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.

**Comment by gundogduhasan** [comment]
Any idea about this issue?
