### ISSUE TITLE
Invalid redirect_uri:

### ISSUE THREAD

**Issue by xewn** [IdentityServer/IdentityServer4#5445]
这个错误，为什么不能直接将URI哪里有错返回呢？
SELECT TOP (1000) [ClientId]
      ,[RedirectUri]
  FROM [IdentityServerClientRedirectUris]      
这个表的数据，结尾也不能有/    
类似这样才是正确的http://192.168.25.204/system
为什么不直接返回错误，URL的结尾不允许带有/

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
