### ISSUE TITLE
AllowedCorsOrigins contains invalid origin:

### ISSUE THREAD

**Issue by xewn** [IdentityServer/IdentityServer4#5446]
SELECT TOP (1000) [ClientId]
      ,[Origin]
  FROM[IdentityServerClientCorsOrigins]   
这个表的数据，结尾不能有/   也不能有子路径，类似/system/
正确的应该是http://192.168.25.204
这个错误为什么不能直接将URL的准确错误信息返回。

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
