### ISSUE TITLE
Login looping issue

### ISSUE THREAD

**Issue by sergeyDyadenchuk** [IdentityServer/IdentityServer4#545]
Hey guys!
I have strange issue in my project. I use Identity Server 4 with the asp.net mvc 5 app and it's working fine. When I deploy it, it also works fine but after some time when user wants to login it's looped. After login using google user sees log in page again in mvc app. When user goes to Identity Server page, user is authenticated but in the mvc app still is not. I've investigated it and realized that after some time mvc app stopped getting user claims from Identity Server in 'SecurityTokenValidated' in Startup class (e.g. username which is needed). Could you please consult me about it. Thanks

**Comment by brockallen** [comment]
Not sure. Sounds like a cookie is not getting properly set.

**Comment by sergeyDyadenchuk** [comment]
Could it be due to the fact that I use IdentityServer with InMemory configurations? Only users is stored in database but 'scopes', 'clients' and the signing key material are kept in-memory only.
Also after testing I mentioned that if I restart IdentityServer - it'll work fine for one user. But once some another user login - it's broken and nobody can login. Added the new logs I can see in 'SecurityTokenValidated' that IdentityServer actually forwards user claims and id_token but after transformation claims and adding them to 'ClaimsIdentity' in mvc controller they are empty. Could it be due to the fact that id_token is not validated in 'SecurityTokenValidated' and because of that all claims in mvc controller are empty?
My Startup configuration of asp.net mvc 5 app:
app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = ConfigurationManager.AppSettings["AuthenticationClientId"],
                Authority = ConfigurationManager.AppSettings["AuthorityUrl"],
                RedirectUri = ConfigurationManager.AppSettings["RedirectAuthenticationUrl"],
                ResponseType = "id_token",
                Scope = "openid profile email",
                SignInAsAuthenticationType = "Cookies",
                AuthenticationType = "oidc",
                AuthenticationMode = AuthenticationMode.Passive,
                UseTokenLifetime = false,

                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = n =>
                    {
                        var id = n.AuthenticationTicket.Identity;
                        var name = id.FindAll("name");
                        _log.Write(LogLevel.INFO, "Claims: " + id.Claims.Count());
                        // create new identity and set name and role claim type
                        var nid = new ClaimsIdentity(
                            id.AuthenticationType,
                            ClaimTypes.GivenName,
                            ClaimTypes.Role);

                        nid.AddClaims(name);
                        nid.AddClaim(new Claim("id_token", n.ProtocolMessage.IdToken));
                        
                        n.AuthenticationTicket = new AuthenticationTicket(
                            nid,
                            n.AuthenticationTicket.Properties);

                        return Task.FromResult(0);
                    },

                    RedirectToIdentityProvider = n =>
                    {
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
                            _log.Write(LogLevel.INFO, "LogoutRequest token: " + idTokenHint);
                            if (idTokenHint != null)
                            {
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                            }
                        }

                        return Task.FromResult(0);
                    }
                }
            });
And mvc account controller action where user claims disappears some times:
[AllowAnonymous]
        public ActionResult ExternalLoginCallback(string returnUrl)
        {
            var username = (User.Identity as ClaimsIdentity)?.Claims.FirstOrDefault(x => x.Type == "name")?.Value;
            var token = (User.Identity as ClaimsIdentity)?.Claims.FirstOrDefault(x => x.Type == "id_token")?.Value;
            _log.Write(LogLevel.INFO, "Username: " + username);
            _log.Write(LogLevel.INFO, "Token: " + token);
            if (string.IsNullOrEmpty(username))
            {
                _log.Write(LogLevel.ERROR, "Username: " + username);
                return RedirectToLocal(returnUrl);
            }

            var user = UserManager.Users.FirstOrDefault(x => x.Email.Equals(username, StringComparison.OrdinalIgnoreCase));

            if (user != null)
            {
                user.Claims.Add(new IdentityUserClaim()
                {
                    ClaimType = "id_token",
                    ClaimValue = token
                });

                SignInManager.SignIn(user, false, false);              
            }

            return RedirectToLocal(returnUrl);
        }

Could you please look at this and explain what I'm doing wrong? Thanks

**Comment by leastprivilege** [comment]
Any update?

**Comment by sergeyDyadenchuk** [comment]
I'm working on persistent storage now for configurations, like client, scopes etc. Also setting physical signing certificate. I'll let you know how it goes.

**Comment by brockallen** [comment]
We'll close this for now. If you feel there's still a bug/issue with IdentityServer, then please reopen.
