### ISSUE TITLE
Chrome tab not closing after Authorisation on Android app

### ISSUE THREAD

**Issue by calebmakore** [IdentityServer/IdentityServer4#5456]
I am using app auth to do authorization via Identiyserver4.  I can sign in but the Chrome tab is not closing and redirecting back to the app. 

{
  "client_id": "my Client id",
  "redirect_uri": "net.openid.appauthdemo://oauth2redirect",
  "end_session_redirect_uri": "net.openid.appauthdemo://oauth2redirect",
  "authorization_scope": "openid profile",
  "discovery_uri": "https://Myidentitytest/.well-known/openid-configuration",
  "authorization_endpoint_uri": "",
  "token_endpoint_uri": "",
  "registration_endpoint_uri": "",
  "user_info_endpoint_uri": "",
  "https_required": true
}

 manifestPlaceholders = [
                'appAuthRedirectScheme': 'net.openid.appauthdemo'
        ]

I am following this example https://github.com/openid/AppAuth-Android. 

Thanks for the help.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
