### ISSUE TITLE
ProfileDataRequestContext not setup with IdentityResource claims types!

### ISSUE THREAD

**Issue by the-black-wolf** [IdentityServer/IdentityServer4#5457]
I wanted to add a custom identity resource instead of a really large profile one and with the claim I need:

``` csharp
        public class BillingAccountResource : IdentityResource
        {
            public BillingAccountResource()
            {
                Name = "billing";
                DisplayName = "Billing system information";
                UserClaims.Add("billing_account_number");
                UserClaims.Add(JwtClaimTypes.Name);
            }
        }
```

I added it to resources and to the applicable client:

``` csharp

    public static IEnumerable<IdentityResource> IdentityResources => new IdentityResource[]
        {
            new IdentityResources.OpenId(),
            new BillingAccountResource()
        };
...
        // inside client setup
        AllowedScopes = { IdentityServerConstants.StandardScopes.OpenId, "billing" },
```

I've setup my `IProfileService` implementation, however, when the token is requested and the code enters `GetProfileDataAsync`, the `context.RequestedClaimsType` is empty.  Enduser logged in with requested `billing` scope and the database entry in grant storage reflects this. 

I've debug this a little and found this code here:

https://github.com/IdentityServer/IdentityServer4/blob/3ff3b46698f48f164ab1b54d124125d63439f9d0/src/IdentityServer4/src/Services/Default/DefaultClaimsService.cs#L113-L217

Apparently, the `additionalClaimTypes`, which is later filtered before passing to `GetProfileDataAsync`, is only constructed from ApiResources and ApiScopes. Identity resources are completely ignored. 

Is this a bug or a desired functionality (why skip custom identity claims?), and if so how do I dynamically adjust profile service to detect if I should set 'name' and `billing_account_number` claims. I see the `billing` scope name listed in `context.RequestedResources`, but its just there by name, I fear the future moment where this might change and cause a disconnect between client setup and a profile service, I would much rather like to dynamically respond to requested claims rather than assume things. In the samples on the internet, people mostly just have one client and an always-requested scope so they just blindly force claims into result. We will only need `billing` for clients which deal with user's billing.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
