### ISSUE TITLE
client_id is not included in returned token unless explicitly included in request body

### ISSUE THREAD

**Issue by pdf** [IdentityServer/IdentityServer4#5463]
The documentation says that the client_id must be included in a request to the token endpoint, either in the request body or the authorization header.

However, if client_id is only included in the authorization header it is not populated in the returned token, which breaks further workflows (e.g. UserInfo) that expect to find the client_id in the token.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
