### ISSUE TITLE
Login with only phone number

### ISSUE THREAD

**Issue by scaki** [IdentityServer/IdentityServer4#5464]
Hello,
We are using identity server 4 in our project. Identity server allows login with username and password by default. What I want is to only get a phone number while logging in, and in the second step, send the otp code and make sure that the user logs in if the code is correct. How can I do that?

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
