### ISSUE TITLE
Issue with User login between two different providers in Identity server4

### ISSUE THREAD

**Issue by tejaswigattu** [IdentityServer/IdentityServer4#5466]
We are using  Identity Server4 has two external login schemes(Azure Ad B2C and Azure AD).

App1 -- has access to login with B2C
App2 -- has access to login with Azure AD

If the user is login to App1. when he tries to open the App2 it is directly opening the application without asking for Azure AD login. Ideally this should not happen.

I guess this is due to user is able to login to Azure AD with the same cookie of B2C.

We want to restrict this since few users of B2C not access to Azure AD tenant.
Please provide suggestion.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
