### ISSUE TITLE
Redirect to moder.url breaking when is4 call's protected api

### ISSUE THREAD

**Issue by uyau** [IdentityServer/IdentityServer4#5467]
I have some additional behavior, so I need to call protected api inside is4 when I try to authenticate with interactive user.
So I'm using IdentityServerTools to issue access tooken for is4.

```
var token = await tools.IssueClientJwtAsync("is4", 100, new[] { "manage_role" });
httpClient.SetBearerToken(token);
```
then I call protected API, getting 200 status code. Everything is going fine. I authenticate user `await HttpContext.SignInAsync(iduser, props); 
` and it doesn't redirect me to the callback page of my React app. But if I don't use `builder.Services.AddAuthentication().AddJwtBearer...` Everything is working fine. And redirect is working. Even with IdentityServerTools, so problem is somewhere in the point, where API is cheking my token. Do someone have any idea why?

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
