### ISSUE TITLE
Force user sign out from server without user interaction?

### ISSUE THREAD

**Issue by remus-corneliu** [IdentityServer/IdentityServer4#5468]
I have a requirment in which I have to sign out some user to which a jwt was emitted, but without the user having to know about this (so somehow to invalidate a token or to force the user to login again)

Following is the scenario. Say I am assigned some roles and I sign in into the system and the system generates a jwt for me to which it attaches my roles, but does not keep any reference to it anywhere or any other mechanism to identify it. The token is dealt and that is it. Now a 2nd user that has admin rights can go ahead and remove some of the roles that I have, but since I already have a valid token I can still use it till it expires and still can get accees according to old roles list to parts of the system that I shouldn't have rights to access.

This is my issue, the requirment is to not keep any reference to identify a token in the system, so I have no idea how can I overcome this issue.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
