### ISSUE TITLE
Identity server 4 - AuthorizeInteractionResponseGenerator not getting called for saml sso

### ISSUE THREAD

**Issue by Jaydeep28** [IdentityServer/IdentityServer4#5469]
Hi Team,

I am using Identity server 4 with Auth0 IDP and I have integrated SAML SSO with third part service provider.

I have some customization implemented in extended function of '[AuthorizeInteractionResponseGenerator](https://docs.duendesoftware.com/identityserver/v5/reference/response_handling/authorize_interaction_response_generator/)' but somehow after authentication this function not getting called.

It works fine for normal login flow, issue is with only saml sso.

any thought?

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.

**Comment by Jaydeep28** [comment]
Hi, Thanks for the information. We are planning to move to paid service once we get an necessary approval.

However, at this moment can you pls help us to resolve this issue i.e. why [AuthorizeInteractionResponseGenerator] dose not work with saml workflow?

Thanks,
Jaydeep s
