### ISSUE TITLE
Manually Extending Existing Refresh Token Expirations

### ISSUE THREAD

**Issue by lvandyk** [IdentityServer/IdentityServer4#5470]
Does anyone know how to extend the expiration of a refresh token that has already been created and exists in the PersistedGrants table? I know the "Expiration" column is simply for informational purposes. 

Could I perhaps edit the "CreationTime" or "Lifetime" values inside the "Data" column?

We have an issue where users got an access/refresh token long ago and now only want to use it a year later, we don't want them to logout.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
