### ISSUE TITLE
Adding Custom values in Identity Server 4 Connect/token endpoint

### ISSUE THREAD

**Issue by shoaibismailAppify** [IdentityServer/IdentityServer4#5471]
i have implemented the Identity server 4 .. one thing on which i am stuck is currently connect/token endpoint provides the following fields

{ "id_token": "id toekn value", "access_token": "access token value", "token_type": "Bearer", "refresh_token": "a refresh token", "scope": "some scopes" }

however i want to add some more fields in this like

{ "id_token": "id toekn value", "access_token": "access token value", "token_type": "Bearer", "refresh_token": "a refresh token", "scope": "some scopes", "id":"any id", "url":"any url" }

any way to intercept this call and add custom fileds???

**Comment by shoaibismailAppify** [comment]
@leastprivilege  any help on this???

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
