### ISSUE TITLE
FingerPrint Login

### ISSUE THREAD

**Issue by mahdikazemi96** [IdentityServer/IdentityServer4#5472]
Hi
in my project i need to have both username/password login and Fingerprint Login and I do not know how to implement both authentication type in IdentityServer. can you help me?

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.

**Comment by mmk90** [comment]
Thank You
