### ISSUE TITLE
Custom token validation token

### ISSUE THREAD

**Issue by pdania** [IdentityServer/IdentityServer4#5478]
Hi! I am currently working on the logic of custom token validation. I need to deactivate the token when the user's password is changed (_change-password_ endpoint is public).
I have implemented the `ICustomTokenRequestValidator` interface and resolved my class via DI
`.AddCustomTokenRequestValidator<TokenHashValidatorService>();`
However, I see the following problem, my implementation of ICustomTokenRequestValidator only works when I generate a token and during only the first request to my API.
In logs I see the following information:
![image](https://user-images.githubusercontent.com/13735587/191924190-f8974e67-49e5-4d91-bf2f-6bbcb307902d.png)
During first request to API request to `/.well-known/openid-configuration` and `/.well-known/openid-configuration/jwks` is sent. But when I send a second, third, etc. requests my breakpoint in TokenHashValidatorService is skipped.

Is there any way I can forcefully initiate second `/.well-known/openid-configuration` and `/.well-known/openid-configuration/jwks` requests? 
Or maybe I can somehow mark that "token validation needed" during the _change-password_ flow?

I'm really stuck and out of options, I've read all the articles out there, any ideas?

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
