### ISSUE TITLE
Customizing IdentityServer to support multi-tenancy

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4#548]
Hi ,

I am working with IdentityServer4 and I have implemented all the flows and played with them for a while. I have cloned the IdentityServer4 repo and now I am looking for a way to customize it so that I could make it support multi-tenancy as well. 

what I am looking for is to change the generated token so that it contains the application name as well. I will then use the token to know to which application it belongs and do things accordingly. Is there any sample available to achieve that?

Is it a good practice to implement IEndPoint Interface and introduce a flow of my own?

**Comment by brockallen** [comment]
The id token does have the app name -- that's the `aud` claim.
