### ISSUE TITLE
Displayed logged-in devices？

### ISSUE THREAD

**Issue by qq1176914912** [IdentityServer/IdentityServer4#5481]
Can ids4 display all the devices logged in by an account? Similar to git, as shown in the figure
![image](https://user-images.githubusercontent.com/79817742/195264437-6eeb3fde-3771-4149-bc07-be645b7de98f.png)

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
