### ISSUE TITLE
Different domain silent renew issue

### ISSUE THREAD

**Issue by gundogduhasan** [IdentityServer/IdentityServer4#5484]
Hi,

I have two different clients with diffrent domains. And i have identity server hosting different domains. Like this;

client1.com, client2.com (client domains) , auth.client1.com (identity server domain).

Silent renew works on client1.com. But on client2.com when try to silent renew it's gives an error and whole page become empty
error is "Error: AuthCallback AuthResult came with error: login_required".

Do i missing something?

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.

**Comment by gundogduhasan** [comment]
Okay. I will ask the similar question on Duende.
