### ISSUE TITLE
Could not load file or assembly Microsoft.IdentityModel.Tokens

### ISSUE THREAD

**Issue by pappasa** [IdentityServer/IdentityServer4#5485]
I created an IdentityServer as described in https://identityserver4.readthedocs.io/en/latest/quickstarts/1_client_credentials.html with .NET Core 3.1 on Windows 10. We use it in development, to mock some services. On most machines, it runs ok, but on two machines we get the error:

Could not load file or assembly Microsoft.IdentityModel.Tokens

I see, that Microsoft.IdentityModel.Tokens is referenced by Microsoft.IdentityModel.Protocols, which is referenced by Microsoft.IdentityModel.Protocols.OpenIdConnect, which is referenced by IdentityServer4.

We uninstalled Nuget package IdentityServer4 and reinstalled it. That worked for about 10 minutes, but then the same problem occurred.

I found in Stackoverflow the similar issue [Could not load file or assembly Microsoft.IdentityModel.Tokens problem](https://stackoverflow.com/questions/66399294/could-not-load-file-or-assembly-microsoft-identitymodel-tokens-problem), but it is in Azure Functions, whereas we have it on our Windows 10 development machines with Visual Studio 2019 installed.

**Comment by leastprivilege** [comment]
# Important update
This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new [Duende Software](https://github.com/duendesoftware) organization. 

The new [Duende IdentityServer](https://duendesoftware.com/products/identityserver) comes with a commercial license but is [free](https://blog.duendesoftware.com/posts/20220111_fair_trade/) for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please [get in touch with us](https://duendesoftware.com/contact) if you have any question.
