### ISSUE TITLE
/connect/introspect return 405 on server to server

### ISSUE THREAD

**Issue by alesten** [IdentityServer/IdentityServer4#550]
Hey

I'm trying to validate a token given to my api with my identityserver and I'm using the /connect/introspect to do so.

I've tried calling /connect/introspect with postman and it works as a charm. But when I try to call it from my code I get a 405, Method Not Allowed back from my identityserver?
Why do I get 2 different responses from the same request?

Code I'm using to call introspect
```
var client = new HttpClient();
var request  = new HttpRequestMessage(HttpMethod.Get, "https://identityserver/connect/introspect");

request.Headers.Authorization = new AuthenticationHeaderValue("Basic", "id:secret");
var content = new List<KeyValuePair<string, string>> {new KeyValuePair<string, string>("token", token)};
Request.Content = new FormUrlEncodedContent(content);
var response = client.SendAsync(request).Result;
```

I haven't done anything on my identityserver regarding introspect beside from what it comes with.
On my scope I have `AllowUnrestrictedIntrospection = true`

**Comment by leastprivilege** [comment]
HttpMethod.Get ?

**Comment by alesten** [comment]
That's my mistake! Was doing POST in postman but Get in code. Changed to HttpMethod.Post and now it works like a charm! Thanks @leastprivilege
