### ISSUE TITLE
Migration instruction RC3 --> RC4

### ISSUE THREAD

**Issue by ales004** [IdentityServer/IdentityServer4#553]
Could you write some migration instruction from RC3 to RC4?

I found 3 incompatibility with RC3:
1) IdentityServerAuthenticationOptions : ScopeName --> AllowedScopes
2) AddInMemoryScopes does not exist
3) StandardScopes.All and StandardScopes.OfflineAccess do not exist anymore

Point 1) seems simple to solve while 2) and 3) I don't know how to solve.

By the way, when searching fro AddInMemoryScopes I discovered that in [this page](http://docs.identityserver.io/en/release/quickstarts/8_entity_framework.html) the AddInMemoryScopes is still referenced.

Thank you for your help
Alessandro

**Comment by leastprivilege** [comment]
Check our samples repo

**Comment by brockallen** [comment]
i just fixed the quickstart docs. thanks

**Comment by ales004** [comment]
@leastprivilege thanks, [this commit](https://github.com/IdentityServer/IdentityServer4.Samples/commit/55e08d1dfbf36f7e6bbf2f3eedd2bb2ffac3118e) got me on the right track.
