### ISSUE TITLE
Getting signed JWT from reference token

### ISSUE THREAD

**Issue by joelsand** [IdentityServer/IdentityServer4#554]
Hey there,

Is there a way to get a signed JWT by providing a reference token that was created using client_credentials?   The introspection endpoint is close, but the response isn't a signed JWT. 

The scenario: We're building out a microservices-type system where we'd like to allow an external client to acquire a reference access token using client_credentials, then we want to use a reverse proxy to translate those reference tokens to JWT's to be validated internally in the other services.  Similar to what's described [here](http://nordicapis.com/how-to-control-user-identity-within-microservices/).

Thanks!

**Comment by leastprivilege** [comment]
No - not right now.

And why don't you just stick with the reference token?

**Comment by joelsand** [comment]
Ok, thanks.  

We could.  The idea is that the other internal services would receive a JWT and they don't need to worry about looking up the scopes, etc for that token. All they'd need to do is validate it.
