### ISSUE TITLE
Change Task.Result to await Task on demo code

### ISSUE THREAD

**Issue by ncarandini** [IdentityServer/IdentityServer4#555]
When I run the example described on [IdentityServer4/docs/quickstarts/1_client_credentials.rst](https://github.com/IdentityServer/IdentityServer4/blob/release/docs/quickstarts/1_client_credentials.rst#protecting-an-api-using-client-credentials), I randomly get an error on this code:
```
var content = response.Content.ReadAsStringAsync().Result;
Console.WriteLine(JArray.Parse(content));
```
Based on comment of Stephen Cleary in this [StackOverflow page](http://stackoverflow.com/questions/24623120/await-on-a-completed-task-same-as-task-result), shouldn't we change it to:
```
var content = await response.Content.ReadAsStringAsync();
Console.WriteLine(JArray.Parse(content));
```
With this change, that error never happens.

**Comment by brockallen** [comment]
Feel free to submit a PR.

**Comment by brockallen** [comment]
Done
