### ISSUE TITLE
Showing login: User is not authenticated" for javascript Client

### ISSUE THREAD

**Issue by masaab** [IdentityServer/IdentityServer4#557]
I am using Identity Server 4. I am getting " Showing login: User is not authenticated" I am trying to access my api using Javascript Client. If I understand correctly, I dont need a login to get token for my JavaScript Client application. I am following the exact steps in th documentation example
What am I missing.

**Comment by mikeandersun** [comment]
> If I understand correctly, I dont need a login to get token for my JavaScript Client application. 

You need to login first.
What is the example that you follow?
Do you use a js library(e.g oidc-client-js, angular-jwt ,...)?
Please give more details and some code snippet of what you did?

**Comment by masaab** [comment]
I am following the Javascript Client [sample ](http://identityserver4.readthedocs.io/en/release/quickstarts/7_javascript_client.html)application   and I could find anywhere a username and password being used. Where do I need to enter my username and password.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
