### ISSUE TITLE
JavaScript client is not redirected after logout to post_logout_redirect_uri

### ISSUE THREAD

**Issue by raigol** [IdentityServer/IdentityServer4#558]
Javascript client app.js in config is defined 
post_logout_redirect_uri : "http://localhost:5003/index.html" 

Also in IdentityServerHost project for JS client is defined 
PostLogoutRedirectUris = { "http://localhost:5003/index.html" } 

However when clicking Logout user remains on page 
http://localhost:5000/account/logout?logoutId=xyz
"Logout You are now logged out" 

and is not redirected to post_logout_redirect_uri. 
what else is required to do the redirect?

this problem is also in also in Quickstarts 7_Javascript client sample.

**Comment by brockallen** [comment]
> what else is required to do the redirect

the id_token as the id_token_hint param. check the logs and see if it says why the signout validation failed.

**Comment by raigol** [comment]
thank you.

**Comment by jbanken** [comment]
@raigol Where do you end up on your findings? I am running into something similar.
