### ISSUE TITLE
Set relative base URL for host?

### ISSUE THREAD

**Issue by obosha** [IdentityServer/IdentityServer4#559]
Is it possible to set a relative base URL for the IdentityServer4 host?

For example, if you wanted to run IdentityServer4 at a relative url of:    /identityserver

**Comment by brockallen** [comment]
Use `Map` in the ASP.NET pipeline

**Comment by obosha** [comment]
To be more clear, I have IdentityServer4 added to an existing WebApi, and I'd like to keep them running under separate base relative URL's.

For example, run my existing API under /api and IdentityServer endpoints under /identityserver.

I don't think I can use Map to target IdentityServer endpoints themselves without affecting my others, can I?

**Comment by brockallen** [comment]
Map forks the pipeline based on path -- isn't that what you're asking?

**Comment by obosha** [comment]
I just want all IdentityServer4 endpoints to be accessed from the base URL of /identityserver as opposed to from the root of the application like it works out of the box.

I thought in previous versions of IdentityServer, you could set all of IdentityServer to run under a relative URL like "/core" for example.

The one caveat though is that whatever method I use, I don't want it to affect my existing Contollers in my WebApi project.  I just want to target IdentityServer endpoints, and have them all be accessible from under /identityserver.

Does this make sense.  I just want all of IdentityServer to run under relative URL, without affecting my own custom Controllers that exist apart from IdentityServer.

**Comment by brockallen** [comment]
> I just want all IdentityServer4 endpoints to be accessed from the base URL of /identityserver as opposed to from the root of the application like it works out of the box.

Yep, add a Map then.

> I thought in previous versions of IdentityServer, you could set all of IdentityServer to run under a relative URL like "/core" for example.

That was done with Map.

**Comment by obosha** [comment]
:)  ok you must enter referring to something different than MapHttpRoute
which is what I thought you were referring to...

I'll dig into the old code if need be...

Thanks Brock.

**Comment by brockallen** [comment]
Yes, it's an API on the IApplicationBuilder

**Comment by obosha** [comment]
Ok...  will look into it.  Thanks.
