### ISSUE TITLE
Exception when calling connect/token from angular 2 

### ISSUE THREAD

**Issue by oferAshkenazy** [IdentityServer/IdentityServer4#56]
Hi
using version beta 1 update 1 resource owner flow
I get the following error
"InvalidOperationException: Unable to resolve service for type 'IdentityServer4.Core.Validation.IResourceOwnerPasswordValidator' while attempting to activate 'IdentityServer4.Core.Validation.TokenRequestValidator'."

Thanks

**Comment by ircnelson** [comment]
@oferAshkenazy put this in your Startup.cs and try again: 
`builder.Services.AddTransient<IResourceOwnerPasswordValidator, DefaultResouceOwnerPasswordValidator>();`

**Comment by ircnelson** [comment]
Look how this works behind the scenes...

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/IdentityServerBuilderExtensions.cs#L14

**Comment by oferAshkenazy** [comment]
thanks it helped a lot!!!
