### ISSUE TITLE
Build on full framework

### ISSUE THREAD

**Issue by jinweijie** [IdentityServer/IdentityServer4#560]
With the announcement of .net standard (https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/), i think the correct direction to implement the server part of identity server is to use the full framework (.Net Framework). Instead of struggling dealing with the breaking changes of the .net core.

What do you think?

Thanks.

**Comment by brockallen** [comment]
We're supporting both.
