### ISSUE TITLE
Expose and implement an IHandleGenerator interface

### ISSUE THREAD

**Issue by strtdusty** [IdentityServer/IdentityServer4#564]
We are using the DefaultRefreshTokenService.  We have implemented our own RefreshTokenStore to provide storage for the refresh tokens.  We map the handle to our primary key.  The DefaultRefreshTokenService uses CryptoRandom.CreateUniqueId() to generate a 32 character random string.  Since we use SQL Server to back our storage any index on that column is going to get fragmented very quickly.  It would be nice if you used DI to obtain a IHandleGenerator so that I could create sequential GUID's or something that would play nicer in the database.  I realize I can create my own RefreshTokenService and that will work for us.  It just seems like a shame to create our own service just for that.  If you think this is a good idea I could try to provide a PR.

**Comment by leastprivilege** [comment]
But the handle must be truly random - otherwise it can be guessed.

**Comment by strtdusty** [comment]
Good point.
