### ISSUE TITLE
How to maintain access token and refresh token in database instead memory?

### ISSUE THREAD

**Issue by atpyk** [IdentityServer/IdentityServer4#566]
I can obtain an access token, but it will lose all data if the identity server crash or meltdown, so that cannot to do token validation.
Is there any way to store token in database, not in memory? and how?
Thanks for your help:)

**Comment by leastprivilege** [comment]
By implementing `IPersistedGrantStore` - check our EF Core implementation.

**Comment by atpyk** [comment]
@leastprivilege Many thanks, buddy
