### ISSUE TITLE
Is this really usable for only .NET?

### ISSUE THREAD

**Issue by sivabudh** [IdentityServer/IdentityServer4#567]
Hello,

Is this only usable from .NET projects? Can it be used to provide authentication for python, Java, JavaScript, etc.?

**Comment by leastprivilege** [comment]
Of course. It is a protocol implementation. 

---
Dominick Baier




On Sat, Dec 10, 2016 at 10:40 AM +0100, "Sivabudh Umpudh" <notifications@github.com> wrote:












Hello,


Is this only usable from .NET projects? Can it be used to provide authentication for python, Java, JavaScript, etc.?

**Comment by sivabudh** [comment]
Sorry @leastprivilege. You mean of course as in it can be used from other languages such as Python, Java, or Javascript, right?

**Comment by leastprivilege** [comment]
Yes of course

---
cheers
Dominick Baier




On Sun, Dec 11, 2016 at 1:24 PM +0100, "Sivabudh Umpudh" <notifications@github.com> wrote:












Sorry @leastprivilege. You mean of course as in it can be used from other languages such as Python, Java, or Javascript, right?

**Comment by solenovex** [comment]
There is a working sample using python (hug) api and identity server 4: 
[Identity Server 4 samples: Call Python Hug Api](https://github.com/solenovex/Identity-Server-4-Python-Hug-Api-Jwks)

**Comment by solenovex** [comment]
There is working sample using python (hug) api and identity server 4:   
<a href="https://github.com/solenovex/Identity-Server-4-Python-Hug-Api-Jwks" target="_blank">Identity Server 4 samples: Clients Call Python Hug Api</a>
