### ISSUE TITLE
Defining Api Resource

### ISSUE THREAD

**Issue by maganuk** [IdentityServer/IdentityServer4#568]
Hi,

Upgrading a host from IDS4 RC2 to RC4, when defining an api resource if I do:

    new ApiResource("testapi", "testapidescription")

it seems to work. However when I do:

    new ApiResource{Name = "testapi", DisplayName = "testapidescription"} 

I get an invalid scope.

May be a bug.

Thanks

**Comment by Sebosek** [comment]
It's not a bug. When you're creating Api Resource with empty constructor, then you have to define Scope as well. First variant creates Scope with name at background.

**Comment by brockallen** [comment]
When you don't use the convenience constructor, then you must define and populate the `Scopes` collection.

**Comment by maganuk** [comment]
Thanks @brockallen . closing

**Comment by ChrisSimmons** [comment]
Naive question posed from a position where I can't easily navigate the project code right now: would it be bad to simply remove the default constructor for `ApiResource`?  Granted you can always actively remove all the scopes from the `ApiResource` and break it, but at least that would require a concerted effort.

**Comment by brockallen** [comment]
> would it be bad to simply remove the default constructor for ApiResource

then if you needed to define multiple scopes i think it would look strange -- one via ctor, and another via collection.
