### ISSUE TITLE
Provide easy way to create an access token

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#571]
Scenario:
Calling an API from within an IS extensibility point (e.g. profile service).

**Comment by brockallen** [comment]
We should look at all of the OWIN extensions from IdentityServer3 and see what would make sense to offer here.

**Comment by leastprivilege** [comment]
maybe introduce an injectable interface for "tools". e.g. `IIdentityServerTools`

**Comment by leastprivilege** [comment]
`IdentityServerTools` it is.

Can be injected and mocked.

**Comment by bison92** [comment]
Can you please provide an example of how to use this? there is no documentation. @brockallen 
Also, answering "just inject it on your class" is not what I'm asking for. In case you fell tempted  @leastprivilege

**Comment by bison92** [comment]
Thank you @leastprivilege I did found how to use it but it is nice to have a piece of doc for the users to come. 

The link to the documentation is [here](http://docs.identityserver.io/en/dev/topics/tools.html)

BTW, It will be great if you include an example of how to consume this token on the API side. Thank you again.
