### ISSUE TITLE
Setting to set maximum number of reference tokens created?

### ISSUE THREAD

**Issue by vvdimov** [IdentityServer/IdentityServer4#573]
Trying to find a way to limit the number of active reference tokens per user.

**Comment by leastprivilege** [comment]
Can you explain a little more?

**Comment by vvdimov** [comment]
For a particular user I am trying to have not more than X active reference tokens issued. If a user request a new token, one of the existing tokens is disabled/expired/deleted. The attempt is to limit the devices which can have simultaneous access. Thanks!

**Comment by leastprivilege** [comment]
We'll look into it. thanks!

**Comment by brockallen** [comment]
I'd suggest this be done in a custom persisted grant store.
