### ISSUE TITLE
Tutorial for deployment IdentityServer4 to Azure

### ISSUE THREAD

**Issue by MartinBodocky** [IdentityServer/IdentityServer4#577]
Hi everybody,

I know this is so stupid question, but I'm trying to deploy Identity Server4 as .net core app to azure web site but it's constantly failing. Do you have any experience ? Do you have sample which is working nicely for you.

Thanks,

Martin

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4.DemoSite

**Comment by balivo** [comment]
This sample is the "server" side of IdentityServer4 for Azure deploy?

**Comment by leastprivilege** [comment]
That's the repo I point Azure at. It deploys from there.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by docseuss** [comment]
leastprivilege I am having difficulties deploying to Azure as well. I have created a new project using the dotnet new is4ef template and have the solution up and running on my local machine. However when I publish to Azure the site never comes up. 
Link to published server is http://gambitcreationspawsidentityserver.azurewebsites.net/

Are there any special steps needed to get this up and running in Azure?

Thanks,
Garry
