### ISSUE TITLE
Can I use ID server with PHP or does it need to be JS call???

### ISSUE THREAD

**Issue by furrybaer** [IdentityServer/IdentityServer4#58]
Trying to see if I can have our PHP/Wordpress guy use ID server(4) to call my ASP.NET Web API services.  Will try to use this under the new ASP.NET 5 Core...Do you think that is possible?  Hints on how to get there?

**Comment by brockallen** [comment]
Yes, it should be possible since it's all about the OIDC protocol.

**Comment by furrybaer** [comment]
But in all the samples I see, the ASP.NET MVC app needs a reference to the ID Server library/package...PHP couldn't do that...Not sure what the "Client" would be when I configure the ID Server...Sorry/thanks...

**Comment by brockallen** [comment]
If you're not a .NET developer, then there are many other platforms that have OIDC support: https://openid.net/developers/libraries/

**Comment by furrybaer** [comment]
I see the PHP example...Looks like it takes "ClientId" and "ClientSecret"...So the OpenIdConnectClient("IDSERVERURLGOESHERE???").  That is my guess...Will try to get the ID Server running and have my PHP Developer try it out...Thanks...

**Comment by brockallen** [comment]
np
