### ISSUE TITLE
Redirect issue in case of expired or no token

### ISSUE THREAD

**Issue by ehsaanwelcome** [IdentityServer/IdentityServer4#582]
flow => resource owner password / web api
i called localhost:5000/identity endpoint without setting authorization header or set temepred token

1. if i use in memory users and do not set **addidentity** or **useidentity** then i get 401 http status code which is correct (used exactly this configuration https://identityserver4.readthedocs.io/en/release/quickstarts/2_resource_owner_passwords.html)

2. as i configure **useidentity** and **addidentity**, i start getting http status 200 with /account/login redirection

this redirection happens because addidentity by default redirect to login path in case of unauthorized access
services.AddIdentity<ApplicationUser, IdentityRole>(options =>
                {
                    //this is default path
                    //options.Cookies.ApplicationCookie.LoginPath= "/Account/Login";
                })

how can i stop this redirection anf get just 401 or 403 status?

**Comment by leastprivilege** [comment]
I don't follow - where exactly are you getting a 401 or a 200 ?

The token endpoint in identityserver either sends 200 (success) or 400 (failure).

**Comment by ehsaanwelcome** [comment]
working example from available samples
configure service
services.AddIdentityServer()
.AddTemporarySigningCredential()
.AddInMemoryApiResources(Config.GetApiResources()).AddInMemoryClients(Config.GetClients()) .AddInMemoryUsers(Config.GetUsers());

and 

app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:5000",
                RequireHttpsMetadata = false,
                
                ApiName = "api1"
            });
everything works, if i call /identity endpoint without token, i do get 401 http response

Now add this
services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

and 

app.UseIdentity()

everything is working after above changes except when i call /identity without token (from Postman, IdentityModel or through SPA app), i get redirection page to /Account/Login while i just expect 401 http status code.

**Comment by leastprivilege** [comment]
app.UseIdentityServer()
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions

Why is the API running in the same app as identity server?

**Comment by ehsaanwelcome** [comment]
You are right, I was trying both identity server and api in same project, now it is working.

I tested JS client with resourceOwnerPassword and can successfully refresh token but unable to make it work with hybrid flow.

my app(SPA) scenario is to redirect user to identity server login page and get back both access token and refresh token

i tried oidc-client.js lib where they first call createSigninRequest and then processSigninResponse to get back access and refresh token but doesn't work for me, can you please provide a JavaScriptClient with hybrid flow.

Thanks.

**Comment by MarioRosas89** [comment]
****
