### ISSUE TITLE
Get empty page when access the MVCClient that deployed in IIS

### ISSUE THREAD

**Issue by atpyk** [IdentityServer/IdentityServer4#584]
I used Kestrel to launch my MVCClient to test the OpenId authentication before, They worked fine.
But when I deploy MVCClient in IIS and got an empty page when I call the default action that has been marked "Authorize" attribute.
I found it cannot jump to the Login page automatically.
How to solve this issue? Please help, thanks a lot.

**Comment by atpyk** [comment]
Is there any update for this issue?
Besides that I found using IISExpress to launch the MVCClient, it also couldn't work.

**Comment by leastprivilege** [comment]
This happens in your client app - so this is not an issue with identity server I assume.

Check the MVC logs.

**Comment by atpyk** [comment]
I've found the root cause. The version of "Microsoft.AspNetCore.Authentication.Cookies" and "Microsoft.AspNetCore.Authentication.OpenIdConnect" should be 1.0.0, not be 1.1.0.
There is no error and prompt message in IDE and Runtime, It's a tricky issue.
