### ISSUE TITLE
Where is IUserService?

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4#59]
I am trying use `Microsoft.AspNet.Identity` for user store. In Identityserver3 we have an `IUserService`. Where is it in Identityserver4? Is it `IprofileService`?

**Comment by brockallen** [comment]
Check the archives

**Comment by Edu115** [comment]
@mikeandersun I also struggled a bit to understand how to do this.

 I think the current approach is to use IProfileService for implementing the profile specific logic, and the login/logout logic, which previously was "baked in" and tightly coupled to IdentityServer's UI implementation, is now completely up to you to implement. I guess if you look at the current Host example, it would be implemented in the LoginService and LogoutService, which are in the UI folder.
If you want to use the Resource Owner Password flow, then you also need to implement your own validator that inherits from IResourceOwnerPasswordValidator.

I assume later this will probably be changed and improved. Please correct me if I'm wrong @brockallen :)

**Comment by brockallen** [comment]
@Edu115 yes, for the most part. But this is all still a work in progress. Again, some of this has already been discussed in prior issues opened (and since closed).

**Comment by krishanthaI** [comment]
HI, 
can any one direct me to find some resource to implement AspNetIdentity in IdentityServer4
Regards
_xx

**Comment by mikeandersun** [comment]
@krishanthaI here is for bug report and feature request. Please add you questions on others sites (stackoverflow ,..). I have some experiences on what you want.
