### ISSUE TITLE
userinfo throwing InvalidOperationException when integrated with ASP.NET Core Identity

### ISSUE THREAD

**Issue by dlacaille-baytech** [IdentityServer/IdentityServer4#591]
Hi,
We used your ASP.Net Identity integration sample and extended it for custom props at the user level. Everything works like a charm except for the following:

When testing a JavaScript client (another of your samples) and a direct call (using Postman) to the userinfo endpoint we get the following error (see below) with a very vague stacktrace. But, when using the access token and querying one of our secured APIs, all the scopes data is available. Are we missing something?

``An unhandled exception occurred while processing the request. 
InvalidOperationException: Sequence contains more than one matching element
``

P.S. We are using IdSrv4 ver. **1.0.0-rc3**

**Comment by leastprivilege** [comment]
upgrade to RC5 and see if this error still exists.

**Comment by dlacaille-baytech** [comment]
Resolved. Thank you sir!
