### ISSUE TITLE
Managing client registrations

### ISSUE THREAD

**Issue by obosha** [IdentityServer/IdentityServer4#592]
I was under the impression that with the EF integration package, that I'd have a fully functional client registration repository capable of registering/unregistering clients, etc.

But after attempting to implement this, it appears that the current code only lets you query for _existing_ clients that are registered, and there is no endpoint _or_ mechanism that exists to actually register a client (other than manually adding to the database).

Is this correct?

**Comment by leastprivilege** [comment]
this is correct.

**Comment by obosha** [comment]
Thanks for the feedback Dominick.

**Comment by antonfelich** [comment]
@obosha what was your solution to this? We are experiencing the exact same issue at the moment.

**Comment by obosha** [comment]
Ended up implementing endpoints outside of Identity Server that used the
same DbContext as IdentityServer to perform updates.

We didn't want to modify IS itself.  This worked fairly well and more
easily isolated the authorization concerns too.
