### ISSUE TITLE
Authorization Code with MVC 5 Application

### ISSUE THREAD

**Issue by akamud** [IdentityServer/IdentityServer4#596]
I'm trying to configure IS4 to allow Authorization Code for my client (`GrantTypes.CodeAndClientCredentials`), 

I'm configuring my MVC 5 client using `UseOpenIdConnectAuthentication` and setting the `response_type` to `code` only.

```C#
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",

                Authority = Clients.Constants.BaseAddress,
                RequireHttpsMetadata = false,

                ClientId = "mvc.code",
                ClientSecret = "mySecret",

                ResponseType = "code",
                Scope = { "openid", "profile", "email", "offline_access" },
                GetClaimsFromUserInfoEndpoint = true,

                SaveTokens = true
            });
```

But everytime I make a request to my IS4 server, I get a response saying 
```
Invalid grant type for client: authorization_code
```

I see all the samples from the IS4 sample repo are now using *Hybrid Flow*, does IS4 still support *Authorization Code*?

**Comment by leastprivilege** [comment]
logs or it never happened.

**Comment by akamud** [comment]
After reviewing all my applications I noticed there was a problem in my IS configuration.

Can we build a sample using Authorization Code to `IdentityServer4.Samples`?

**Comment by leastprivilege** [comment]
Why would you use code over hybrid?

**Comment by akamud** [comment]
In our scenario some of our clients are applications that can't be customized and have only code flow implemented.

**Comment by leastprivilege** [comment]
OK I understand - when we have time, we'll add a code flow example.
