### ISSUE TITLE
How would I go about updating user data from the API?

### ISSUE THREAD

**Issue by Biarity** [IdentityServer/IdentityServer4#597]
I have an IdentityServer4+ASP.NET Identity Auth Server working with a JS client & an ASP.NET Core API. The JS client is able to use the Auth Server to register/login/logout and get the access token that would allow access to the API; a very similar setup to the 'Using ASP.NET Identity' quickstart in the docs.

Now, how would I allow the API to edit user data (eg. update profile image, 'favorites', prefs, etc.)? Currently the API can only access the user data through the token and doesn't communicate with the Auth Server (which is the only server that has access to my users database). Is there some built-in mechanic for this that I'm missing or do I have to grant my API write access to my users database?

I apologize for posting a question in the issues section but this is the only active place I could think of.

**Comment by leastprivilege** [comment]
You need to provide your own API to write to your user database.

**Comment by prisar** [comment]
I want to edit a user details. how should i create a edit action in Account controller?
