### ISSUE TITLE
Large amount of data in user claims

### ISSUE THREAD

**Issue by JerVoe** [IdentityServer/IdentityServer4#60]
Hi, 

I've been playing with IS4 and have a question about claims - when I dump a large amount of data in a user's claim (I'm serializing a large object as a claim containing a large amount of data about the user) I get "400 - Bad Request" errors - am I working with this the wrong way? If I have a large amount of authorization data about the user I need to return, should that be sent to the clients somewhere else?

Thank you.

**Comment by brockallen** [comment]
Claims are about identity data, not permissions.

**Comment by JerVoe** [comment]
OK, thanks.
