### ISSUE TITLE
Everything is working, but still confuse in different flow!

### ISSUE THREAD

**Issue by ehsaanwelcome** [IdentityServer/IdentityServer4#601]
**Authorization Code Flow in SPA**
1. i made a request with response type **code** 
2. got **code** in redirect_uri 
3. then made back channel post call to get access and refresh token with grant_type=authorization_code 
4. access token works

**Hybrid Flow in SPA**
1. i made a request with response type **code id_token** 
2. got **code** and **id_token** in redirect_uri 
3. then made back channel post call to get access and refresh token with grant_type=authorization_code 
4. access token works

**confusion/issue:**
1. when i made request in hybrid flow with "code id_token **token**", i get invalid request error
2. all steps in both flows are same other than **response type in step 1**

I followed steps from [http://openid.net/specs/openid-connect-core-1_0.html#HybridFlowSteps](url) but unable to locate differences in both flows other than theory or might be not getting it properly.

really appreciate your work.
Thanks.

**Comment by brockallen** [comment]
There's a setting on the Client to allow access tokens to be sent via the browser front-channel.

**Comment by leastprivilege** [comment]
...and as always, reading no the logs would help.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
