### ISSUE TITLE
Storage of access tokens in javascript clients

### ISSUE THREAD

**Issue by martintro** [IdentityServer/IdentityServer4#608]
In most examples of oauth 2 with javascript clients I've seen the access tokens is stored in local storage or session storage. I have also read posts where they think that's a bad idea, for example https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage and http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/.

What do you think about that? Is there any way to use cookies for the APIs, like the posts mention, with IdentityServer?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by martintro** [comment]
Alright, thanks. I posted the question on StackOverflow as well now: http://stackoverflow.com/questions/41260971/storage-of-oauth-access-tokens-in-javascript-clients-e-g-angular
