### ISSUE TITLE
Consider all specialized Store*Async methods to create new handles by themselves

### ISSUE THREAD

**Issue by pavolpr** [IdentityServer/IdentityServer4#609]
I am using IdentityServer in multi-node scenario and I want to ensure availability of generated **authorization codes**, **refresh** and **reference tokens** immediately after their creation from each node. We use modified event-sourcing with lastPublishedEventId-s as a means for synchronizing published events. For that reason I need to encode the lastPublishedEventId into the produced handles. It is now possible but with a lot of code copying (e.g., replacing the whole IAuthorizeResponseGenerator) ...
TL DR

**I would suggest that all specialized methods for storing of Authorization Codes, Refresh and Reference Tokens should create and return handles instead getting them from their callers.** 
Then, the respective signatures

```C#
Task IAuthorizationCodeStore.StoreAuthorizationCodeAsync(string handle, AuthorizationCode code);
Task IRefreshTokenStore.StoreRefreshTokenAsync(string handle, RefreshToken refreshToken);
Task IReferenceTokenStore.StoreReferenceTokenAsync(string handle, Token token);
```
would become

```C#
Task<string> IAuthorizationCodeStore.StoreAuthorizationCodeAsync(AuthorizationCode code);
Task<string> IRefreshTokenStore.StoreRefreshTokenAsync(RefreshToken refreshToken);
Task<string> IReferenceTokenStore.StoreReferenceTokenAsync(Token token);
```

This way, it would be a much better separation from the calling code and I would be happy :)
Either way, IdentityServer is a beautiful piece of work, 
thank you for that,
keep going!

**Comment by pavolpr** [comment]
Well, there is another catch, the IAuthorizeResponseGenerator is **not** marked as **public** . so effectively I am forced to replace the whole

**Comment by brockallen** [comment]
What about multiple use refresh tokens where we need to slide the value (IOW, update what's in the DB). Does an Update API work on your multi-node scenario?

**Comment by pavolpr** [comment]
Well, yet another catch, to replace AuthorizeEndpoint, besides the IAuthorizeResponseGenerator, also IAuthorizeRequestValidator is **internal**. Maybe, I'll go for a custom build with some patches for now, this would become a lot of copied code ...
I'll wait for your advise, what to do. If my suggestion in this issue is the way to go, I'll have all problems solved. If you would approve the change, I can create a PR.

**Comment by brockallen** [comment]
> IAuthorizeRequestValidator is internal

Open a new issue for that one, please, so we don't mix up this issue.

**Comment by pavolpr** [comment]
@brockallen , we are using AuthorizeEndpoint with authorization_code grant with PKCE.
The returned authorization code can be asked for redemption on another node, so the other node needs to wait for the published event with the code to get the code's data (they flow with a broadcasted event which then creates the code in DB on all the nodes to be accessible).

The problem I have here is how to customize the code "structure" in the most extensible way. 
Now, the code is generated as 32 random bytes hex encoded string, while we need something like "encodedlastPublishEventId+random 16 bytes" structured code.
Similar requirement applies to refresh tokens, but that is not such a problem, because refresh tokens are not expected to be used for some time, so the nodes are synchronized "with time".
But, if we want to use reference tokens for our access tokens, the same applies, we need a little structure in the token handles, too.

**Comment by leastprivilege** [comment]
we changed the stores to generate the handle - see if that works for you.

**Comment by pavolpr** [comment]
Yes! 👍 
The changes you made are exactly what I need. I'll give it a try, but it seems very good fit for me at first glance.
Thank you, I have Christmas :)

(I've opened/commented another issue with the AuthorizeResponse not being public, so it breaks the build, but that is a minor.)

**Comment by brockallen** [comment]
Enjoy
