### ISSUE TITLE
IAuthorizeResponseGenerator and IAuthorizeRequestValidator are internal

### ISSUE THREAD

**Issue by pavolpr** [IdentityServer/IdentityServer4#616]
These two interfaces are internal which makes extensibility less flexible.
For example, if one needs to change/replace AuthorizeEndpoint, these two interface implementations cannot be reused.

**Comment by pavolpr** [comment]
IAuthorizeResponseGenerator is now public,
but AuthorizeResponse is not -> cannot build the solution with error
error CS0050: Inconsistent accessibility: return type 'Task<AuthorizeResponse>' is less accessible than method 'IAuthorizeResponseGenerator.CreateResponseAsync(ValidatedAuthorizeRequest)'

**Comment by brockallen** [comment]
fixed
