### ISSUE TITLE
Consider DateTimeHelper to be public as well as its UtcNowFunc

### ISSUE THREAD

**Issue by pavolpr** [IdentityServer/IdentityServer4#619]
We are using IdentityServer in a time synchronized environment with a single IClock interface.
We would like to replace IdentityServer's clock source with ours, but DateTimeHelper.UtcNowFunc is not visible from our code (maybe a reflection hack woud do it, but that is not nice).

**Comment by brockallen** [comment]
maybe we can get this in for rtm

**Comment by pavolpr** [comment]
Also, I believe having available the DateTimeHelper in the user code is beneficial, because the user extensions would use the same time source as the core implementation. Not to mention testing ...

Anyway, I'd be satisfied with just turning the keywords from internal to public. No need for a service oriented or DI way of doing that, which could pretty complicate the refactor of all the time using code ... 
IMHO, the singleton solution is the way to go here, maybe with some rename only, st. like IdentityServerDateTime.UtcNow and .SetUtcNowFunc() or similar to suite your taste.

Thank you for your development and evolution!
I am learning from reading your code a lot.

**Comment by brockallen** [comment]
I made them public.

**Comment by pavolpr** [comment]
Thank you!

Congrats to the fresh OIDC Certification! 🥇 
Crossing fingers for the RTM on Friday 
and Best Wishes for the New Year :)
