### ISSUE TITLE
IdentityServer4 Database Schema

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#62]
Can we have a full json schema example of what a database might look like for folks backing this with the DB of their choosing. I have been going through the entity framework code by 2020IP to do a one-to-one comparison to what I am trying to model in both JSON and in Cassandra.

`https://github.com/2020IP/TwentyTwenty.IdentityServer4.EntityFramework7/tree/master/src/TwentyTwenty.IdentityServer4.EntityFramework7/Entities`

Where did the 2020IP authors get their schemas from?    
I am guessing looking here.  
`https://github.com/IdentityServer/IdentityServer3.EntityFramework`

What would ultimately be nice is an example of a Cassandra CQL which produces all UserDefinedTypes and Tables, as well as one for MongoDB, etc.

Perhaps a place in your area where people can contribute their versions of database creation scripts.

**Comment by leastprivilege** [comment]
Feel free to start a contrib project for that.
