### ISSUE TITLE
Call to connect/token generated DB exception

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4#620]
I am using IdentityServer as my authentication server, I have connected it to a mysql database using 'Sapient.Guardian.Mysql' package,

I have got clients, users and scopes in the datatbase and everything was working fine , I was able to generate tokens etc.

But now when I request a token I get the following exception,

>InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTimeOffset'.
GetFieldValue

While the Logs show the following

>Microsoft.EntityFrameworkCore.Query.RelationalQueryCompilationContextFactory:Error: An exception occurred in the database while iterating the results of a query.
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTimeOffset'.

**Comment by brockallen** [comment]
dup: https://github.com/IdentityServer/IdentityServer4.EntityFramework/issues/48
