### ISSUE TITLE
Client ID per instance or application

### ISSUE THREAD

**Issue by PaulRReynolds** [IdentityServer/IdentityServer4#621]
Apologies if this question has been raised before, I've read some topics here on multi-tenancy with Identity Server but not one that covers this particular question. 

We're in the process of using IdentityServer 4 to develop a SSO solution to provide centralised authentication for several .Net apps including a mix of MVC web apps and native mobile. The web apps are deployed in a mixture of single and multi-tenant instances, however I'm not sure whether each instance should have a unique Client ID + Secret or whether it's appropriate for multiple instances of the same application to share the same Client ID + Secret? 

I can see that it might be useful in order to identify the instance making server-server API calls using the ClientID but also increases the amount of secrets to manage securely.

**Comment by brockallen** [comment]
Depends. If you need each instance of the client to have different settings (such as redirect uris) then perhaps.

**Comment by PaulRReynolds** [comment]
Yes, each instance would have its own redirect uris, e.g.

- https://uk.domain.com/InstanceA/signin-oidc
- https://us.domain.com/Shared/signin-oidc

I'm aware that multiple uris could be configured for a single client, but maybe this would be a little messy. I already have an entity to persist Instances (to allow for portal functionality) so I'll add fields for ID and Secret there and keep them unique.

Thanks for your help, much appreciated

**Comment by brockallen** [comment]
Well, if all that's different is a locale, then maybe it's not worth multiple clients. I thought maybe your multi-tenancy was customer name based, i.e.: pepsi.yourapp.com vs. coke.yourapp.com,  and perhaps based on that you'd need different settings (secrets or token lifetimes). But if you're hosting the app and it's really the same app, then maybe it's just one client.

**Comment by PaulRReynolds** [comment]
Yes, we will host the apps ourselves, so there's no need to share secrets with third parties. Settings and lifetimes should be identical for all instances of the same application.

**Comment by brockallen** [comment]
Sounds like a single client then.

**Comment by PaulRReynolds** [comment]
Great, thanks Brock
