### ISSUE TITLE
Consider expose PersistentGrantSerializer as interface

### ISSUE THREAD

**Issue by sbebrys** [IdentityServer/IdentityServer4#624]
Consider expose PersistentGrantSerializer as interface to make own implementation without extend this class. It would be easier to use own internal serializer instead JsonConvert.

**Comment by brockallen** [comment]
I'm curious what you need/want to do differently for your serialization?

**Comment by brockallen** [comment]
look ok? https://github.com/IdentityServer/IdentityServer4/commit/df62c4a893545553539db0b9d2061384bda91df4

**Comment by brockallen** [comment]
@leastprivilege any objections?

**Comment by brockallen** [comment]
merged.

**Comment by sbebrys** [comment]
JsonConvert it isn't the fastest way to serialize these objects - profiler showed big hot path in this place - so now I could make something more optimal :)
