### ISSUE TITLE
Client Credentials flow without secret working

### ISSUE THREAD

**Issue by muena** [IdentityServer/IdentityServer4#626]
Hello,

Yesterday I found out that it is possible to use the client credentials flow without a secret (by setting "Require Client Secret" to false).

RFC6749 says:
"The authorization server issues the registered client a client identifier -- a unique string representing the registration information provided by the client.  The client identifier is not a secret; it is exposed to the resource owner and MUST NOT be used alone for client authentication.  The client identifier is unique to the authorization server."

So I think IdentityServer should not issue access tokens for the client credentials flow when "Require Client Secret" is set to false.

**Comment by leastprivilege** [comment]
RFC6749 also says

>OAuth defines two client types, based on their ability to
   authenticate securely with the authorization server (i.e., ability to
   maintain the confidentiality of their client credentials):

   confidential
      Clients capable of maintaining the confidentiality of their
      credentials (e.g., client implemented on a secure server with
      restricted access to the client credentials), or capable of secure
      client authentication using other means.

   public
      Clients incapable of maintaining the confidentiality of their
      credentials (e.g., clients executing on the device used by the
      resource owner, such as an installed native application or a web
      browser-based application), and incapable of secure client
      authentication via any other means.


and

> If the client type is confidential, the client and authorization
   server establish a client authentication method suitable for the
   security requirements of the authorization server.  The authorization
   server MAY accept any form of client authentication meeting its
   security requirements.

> The authorization server MAY establish a client authentication method
   with public clients.  However, the authorization server MUST NOT rely
   on public client authentication for the purpose of identifying the
   client.

**Comment by leastprivilege** [comment]
I mean I see your point that it does not seem very useful to treat a client credentials client as public - yet some people do that and we don't want to stand in their way.

That's why we made it an explicit flag.

**Comment by muena** [comment]
OK, thanks for the clarification!
