### ISSUE TITLE
PostLogoutRedirectUri not work [Reopened]

### ISSUE THREAD

**Issue by atpyk** [IdentityServer/IdentityServer4#627]
I've set the PostLogoutRedirectUris in Client, and it cannot redirect to specific Url when logout.
I debug my code and got the value of PostLogoutRedirectUri from  _interaction.GetLogoutContextAsync(model.LogoutId), but it's null.

How to fix this issue?

**Comment by elciopa** [comment]
I have the same issue. What kind of flow do you use? The implict flow?

**Comment by atpyk** [comment]
I used implicit and hybrid, both not work

**Comment by brockallen** [comment]
Did you look at our samples to compare?

**Comment by atpyk** [comment]
Yes, of cause.

**Comment by atpyk** [comment]
Ha Ha! I think I have found the root cause. 
If set multiple Urls, like below:
RedirectUris = { "http://localhost:5002/signin-oidc", "http://localhost:5003/signin-oidc"  },
PostLogoutRedirectUris = { "http://localhost:5002", "http://localhost:5003" },
It would not work. Once I removed either, it worked. 
I was finding this issue when I did the testing of SSO (Single Sign On), Because I need multiple Urls to respond to different requests that are from different web portals. 

You could reproduce this issue by this way.

**Comment by brockallen** [comment]
It looks like you've resolved you issue, I think. I'll close. If you feel there's still a bug/issue with IdentityServer then please reopen.

**Comment by atpyk** [comment]
What's your recommend for the SSO? Specify multiple clients correspond to different web request?
If you allow to input multiple redirects, you should coordinate the inter-logic and make it on the correct way that expect. Otherwise, I think it should be "Redirect", not "Redirects", it just be allowed to receive only one value, not an array. Does it make sense?

**Comment by atpyk** [comment]
I've no permission to reopen it, please allow me to mark it reopened.

**Comment by testaco23** [comment]
I have the same issue as OP, but in my case it doesn't always happen. For example I might log in and log out correctly, but if I log in again right away and try to log out, the `model.LogoutId` value is null. 
I don't have multiple PostLogoutRedirectUris specified, it's just one.

Also sometimes during login, the url stays stuck at website/signin-oidc and doesn't redirect back. Both of the issues happen randomly though and there's no way I can reproduce them with 100% certainty to track down the problem.

**Comment by ravetroll** [comment]
I was getting null in my logoutId string but I noticed in the log

`IdentityServer4.Validation.EndSessionRequestValidator:Information: End session request validation failure: Invalid post logout URI`

below I saw 
`"post_logout_redirect_uri": "http://localhost:3308/signout-callback-oidc"`

I knew that my Post Logout Redirect Uri was set to http://localhost:3308/ which worked in older version of IdentityServer4.  I changed my Post Logout Redirect Uri to "http://localhost:3308/signout-callback-oidc" and I suddenly had a value in my logoutId and my post logout redirection was working.  It seems putting that signout-callback-oidc on the end of the base url fixed it for me.

**Comment by brockallen** [comment]
> I knew that my Post Logout Redirect Uri was set to http://localhost:3308/ which worked in older version of IdentityServer4.

You mean older versions of the ASP.NET Core OpenID Connect middleware.

**Comment by ravetroll** [comment]
Was my fix the correct approach or is it a fudge and I am missing a more correct approach.

**Comment by brockallen** [comment]
Are we all set on this issue? Can we close?

**Comment by AamirTamtec** [comment]
PostLogoutRedirectUris not redirecting to specific Url when logout

**Comment by dayan2** [comment]
you can find the solution in this link:[SO]( https://stackoverflow.com/questions/49117283/identityserver4-postlogoutredirecturi)
