### ISSUE TITLE
External Login Sample causing Access Denied redirect if initial external login fails

### ISSUE THREAD

**Issue by jinder** [IdentityServer/IdentityServer4#628]
I've been using the Quick Start sample for an Implicit Flow with External Login.  I've used the ExternalLogin and ExternalLoginCallback methods as shown in the [AccountController](https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/4_ImplicitFlowAuthenticationWithExternal/src/QuickstartIdentityServer/Controllers/AccountController.cs).

However, I've found that if the ExternalLoginCallback fails prior to signing out the External Cookie, the user can't do another login with that provider, until they clear their cookies.  If they do, they're repeatedly redirected to the Access Denied page.  Is this expected behaviour or am I missing something?  Should the ExternalLoginCallback method wrap everything in a finally block to ensure that the external cookie is signed out?

**Comment by brockallen** [comment]
Yep, this is a MSFT bug.

**Comment by jinder** [comment]
Ah thanks.  Do you have a link to that issue?  Would the recommended workaround be a SignOut call in the finally block?

**Comment by brockallen** [comment]
Not off hand... somewhere in here: https://github.com/aspnet/security/issues

**Comment by jinder** [comment]
Ah okay, I think it's this:  https://github.com/aspnet/Security/issues/1067

**Comment by brockallen** [comment]
Closing since it's a Microsoft issue.
