### ISSUE TITLE
Open Id with a client with client credentials flow

### ISSUE THREAD

**Issue by Gekctek** [IdentityServer/IdentityServer4#632]
I have clients set up so that they have both client credentials and resource owner flows. There is a problem with this in the latest iterations with the AllowedScopes property. It seems that AllowedScopes is required to be set and if I specify OpenId (for resource owner password flow) it wont let me use the client credentials flow because openid is not allowed for that flow. On the other hand if I dont have it then I get a 'Requested scope not allowed: openid' because it is not in the AllowedScopes. It doesnt seem that AllowedScopes is optional, I set it to an empty list and everything fails. Also if I set it to null I get a null ref.

**Comment by waqaskhan540** [comment]
I am facing the same issue right now

**Comment by leastprivilege** [comment]
Are you saying you are requesting the openid scope in the client credentials case - or openid only on the list of allowed scopes?

**Comment by Gekctek** [comment]
I dont want openid with client credentials but I can't not specify it because it is needed for the resource flow, so I have to specify it. But if I specify it then it will give the error that client credentials cant use it. 

I wont specify the openid when I make the request to client credentials but I need the client to have both flows

**Comment by Gekctek** [comment]
Also applies to a client with AllowOfflineAccess = true. I need it for other flows but it blows up for client credentials. It worked in the earlier RC's

**Comment by Gekctek** [comment]
This is not a solution, but to clarify, I pulled down the source code, removed the 2 checks for openid and refresh token scopes for client credentials flow, and it worked as I wanted. 

If there was a way to optionally loosen these restrictions, that would be optimal.

**Comment by Gekctek** [comment]
I dont know if we can make this a priority or not. If this isnt done soon I will have to try an make my own changes because it is a blocking issue for me. If not any advice would be great.

**Comment by leastprivilege** [comment]
I will look into it tomorrow.

**Comment by leastprivilege** [comment]
sorry - can't reproduce your problem. Maybe I am misunderstanding it.

I added some tests:

https://github.com/IdentityServer/IdentityServer4/blob/dev/test/IdentityServer.IntegrationTests/Clients/ClientCredentialsAndResourceOwnerClient.cs

feel free to add a test that shows the bug.

**Comment by Gekctek** [comment]
I found the issue which was my fault it seems. I am not requesting with any scopes for the client credentials so it defaults the request to have all the scopes that client has as 'allowed'. I dont know if that is intended or not and if it was supposed to change but it is not an issue that affects me. Thanks, appreciate you looking into this for me
