### ISSUE TITLE
Question on MVC client configuration.

### ISSUE THREAD

**Issue by hvanbakel** [IdentityServer/IdentityServer4#636]
In this part of the documentation:
[Configuring clients](https://github.com/IdentityServer/IdentityServer4/blob/dev/docs/configuration/clients.rst) 

Why is the suggestion to use hybrid over regular code flow? What is the benefit of getting the id_token posted back on the initial authorize as opposed to getting it when exchanging the authorization code?

**Comment by brockallen** [comment]
By getting back an id_token you have a signed protocol response. Code by itself suffers from various attacks. The spec mailing lists discuss these.

**Comment by hvanbakel** [comment]
Thanks for the explanation, does that mean that the code only flow should be considered less secure?

**Comment by brockallen** [comment]
Yes.

**Comment by hvanbakel** [comment]
To add to this, I've done some more research here and I think this article describes the attack vectors for anyone interested:
http://openid.net/2016/07/16/preventing-mix-up-attacks-with-openid-connect/
