### ISSUE TITLE
Claim information security

### ISSUE THREAD

**Issue by marcosribj** [IdentityServer/IdentityServer4#637]
I have a multi tenant application where users share the same database, separating information only with a TenantId type column

```
public class SampleEntity
{
   public int Id {get;set;}
   public string Name {get;set;}

   public int TenantId {get;set;}
}

```
Currently I use asp.net identity in an mvc application

I store the TenantId of the user logged in to Claim, and every request and access to the database I use TenantContext.TenantId where it returns the tenantId that is in the Claim

  ```
public static int? TenantId
        {
            get
            {
                var claimsPrincipal = Thread.CurrentPrincipal as ClaimsPrincipal;
                var tenant = claimsPrincipal.Claims.FirstOrDefault(c => c.Type == AppClaimTypes.TenantId);
                int tenantId;
                if (!int.TryParse(tenant.Value, out tenantId))
                {
                    return null;
                }
                return tenantId;
            }
        }
```

In asp.net Identity, by default the cookie is encrypted and I do not worry about leaving the TenantId in Claim

In IdentityServer, my Claims is encrypted? Should I encrypt the token? Currently I use integer as primary key, 
How it is information that has great importance, should I use it as guid?

What would be the best way to store tenantId?

Which way should I go? I am a layman in identityserver and I do not want to expose this fault

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
