### ISSUE TITLE
Idsvr will generate lots of temporary cookies for each call by OpenId

### ISSUE THREAD

**Issue by atpyk** [IdentityServer/IdentityServer4#638]
I did a testing for OpenId in Chrome:
I have the IdSvr(localhost:5000), and I give two tabs in browser, one is MVCClient(localhost:5002), other is whatever(like google.com), first I type into the Url localhost:5002 in a tab and not enter, and then I switch to the other tab, then I switch these two tabs frequently, the temporary cookies(oidc & Nonce) will be generated for each switch.

Eventually it will form a huge cookie list, so that the client-side will bring a very long head that cannot be transferred. 

Even these temporary cookies cannot be removed when login successfully. 

NOTE: **Chrome provided a mechanism to pre-request before enter Url.**

**Comment by atpyk** [comment]
[](http://pan.baidu.com/s/1kUNCirX)

**Comment by atpyk** [comment]
![](https://raw.githubusercontent.com/atpyk/LinksOutside/master/longcookies.png)

**Comment by brockallen** [comment]
If you don't complete the authentication protocol handshake then these cookies will be orphaned, as you have seen.

**Comment by atpyk** [comment]
Please reproduce by my steps(Use Chrome). You will find the root cause. So far maybe we cannot fix this issue.

**Comment by brockallen** [comment]
This sounds like an issue in Chrome and the Microsoft OIDC middleware and has nothing to do with IdentityServer.
