### ISSUE TITLE
Update token when a new role is added to the user

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4#639]
I have implemented the IdentityServer4 with ResourceOwner flow and everything is working fine, but I have a doubt that what if I add a new role to the user , keep in mind that I am using AspIdentity for managing users and entityframework for configuration stores, The solution might be is to get a new token so that it includes the latest claims. But I was wondering if there is a much nicer solution to this problem.? kindly share with me..

**Comment by brockallen** [comment]
You need a new token from IdentityServer if you want updated claims in it.

**Comment by brockallen** [comment]
Correct.

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2016/12/16/identity-vs-permissions/
