### ISSUE TITLE
Applying Cors Policy

### ISSUE THREAD

**Issue by nklap** [IdentityServer/IdentityServer4#64]
Hey,

how to add cors policy correctly?

```
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddCors(options => {
        options.AddPolicy("GlobalCorsPolicy", policy =>
        {
            policy.AllowAnyOrigin();
            policy.AllowAnyHeader();
            policy.AllowAnyMethod();
        });
    });
    ...
```
```
app.UseCors("GlobalCorsPolicy");
app.UseCors(policy =>
{
    policy.AllowAnyOrigin();
    policy.AllowAnyMethod();
    policy.AllowAnyHeader();
});
```

I tried it like this but this has no effect.

Thanks in advance

**Comment by brockallen** [comment]
That is Microsoft's middleware -- why are you asking here about it?

**Comment by nklap** [comment]
I was asking this:

"how to add cors policy correctly?"

using **AllowedCorsOrigins** for InMemoryClients doesn't have any effect:

I always get
**Information: Client list checked and origin: xxxxxxx is not allowed**

**Comment by xyting** [comment]
@nklap You can view my project [RigoFunc.IdentityServer](https://github.com/xyting/RigoFunc.IdentityServer) and view file [IIdentityServerBuilderExtensions.cs](https://github.com/xyting/RigoFunc.IdentityServer/blob/develop/src/RigoFunc.IdentityServer/IIdentityServerBuilderExtensions.cs)
