### ISSUE TITLE
Plans for EntityFramework management UI for data

### ISSUE THREAD

**Issue by dodegaard** [IdentityServer/IdentityServer4#640]
Guys.....before I launch into designing my own UI to manage the EF-based database fueling the IdSvr instance are there immediate plans to create a UI similar to what you did with ASP.NET Identity management in the past?  If so would that be solely on the commercial side of the shop via Rock Solid (I believe I saw an Admin UI noted)?  I'm doing some deliverable planning with a client and thought I'd ask about it as I decide how to manage that data. Happy to contribute if I come up with something but working through understanding the schema at the moment. Thanks for the work you have done getting it as data-driven! Cheers!

**Comment by brockallen** [comment]
>  If so would that be solely on the commercial side of the shop via Rock Solid (I believe I saw an Admin UI noted)

As of now we don't have plans for a FOSS admin UI. Not sure about a user management UI.
