### ISSUE TITLE
Minor Client Credentials Quickstart Documentation issue

### ISSUE THREAD

**Issue by steelerc** [IdentityServer/IdentityServer4#641]
Under defining the client:

The line
                // no interactive user, use the clientid/secret for authentication
                AllowedGrantTypes = GrantTypes.ClientCredentials,

Should probably be something like:
                // no interactive user, use the clientid/secret for authentication
                AllowedGrantTypes = new[] { GrantTypes.ClientCredentials },

**Comment by brockallen** [comment]
Why? I don't follow. Also, this:

>  AllowedGrantTypes = new[] { GrantTypes.ClientCredentials },

I don't think that will compile.

**Comment by steelerc** [comment]
Sorry for the confusion, found my problem when doing the next lesson.  I had new[] { GrantType.xxxx } NOT GrantTypes.  I have corrected my problem.  Sorry for the confusion.
