### ISSUE TITLE
Exception while requesting token using refresh token

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4#642]
While requesting an access token using the refresh token I get the following exception, 

>An unhandled exception occurred while processing the request.
>JsonReaderException: Unterminated string. Expected delimiter: ". Path 'AccessToken.Type', line 1, position >255.
>ReadStringIntoBuffer

my request params are

>client_id : myclient
>client_secret : secret
>grant_type: refresh_token
>scope: offline_access
>refresh_token: my_refresh_token

while on logs I can see the following exception

> >IdentityServer4.Hosting.IdentityServerMiddleware:Critical: Unhandled exception: Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'AccessToken.Type', line 1, position 255.
>    at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
>    at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
>    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
>    at Newtonsoft.Json.JsonTextReader.ReadAsString()
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at IdentityServer4.Stores.DefaultGrantStore`1.<GetItemAsync>d__8.MoveNext()

**Comment by brockallen** [comment]
Can you paste in your JSON here from that record?

**Comment by waqaskhan540** [comment]
i dont recieve any JSON, instead i receive this exception.

**Comment by brockallen** [comment]
I think we need more info. Regardless, this does mean we should have better exception handling around this.

**Comment by waqaskhan540** [comment]
![capture](https://cloud.githubusercontent.com/assets/15784870/21560232/a133de72-ce7d-11e6-841c-17564e9d97ed.PNG)

this is the response I get on 'PostMan', and the only detail I can give you is the exception itself pasted above.

**my project.json** is below so you can have an idea that which versions I am using..

` "dependencies": {
    "IdentityServer4.AspNetIdentity": "1.0.0",
    "IdentityServer4.EntityFramework": "1.0.0-rc5",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.EntityFrameworkCore.Design": "1.1.0",
    "Microsoft.EntityFrameworkCore.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "type": "build",
      "version": "1.0.0-preview2-final"
    },
    "SapientGuardian.EntityFrameworkCore.MySql": "7.1.15",
    "SapientGuardian.MySql.Data": "6.9.813"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "imports": [
        "portable-net45+win8"
      ]
    },
    "Microsoft.EntityFrameworkCore.Tools.DotNet": "1.1.0-preview4-final"
  },`

**Comment by waqaskhan540** [comment]
Ok, I changed the configuration stores from entity framework to In-Memory Stores and then was able to generate access_token through the refresh token, seems like the problem is with the IdentityServer.EntityFramework package but not sure,,  because I recently updated the package from "1.0.0-rc-5" to "1.0.0" but things started creating issues specially with the migrations,  so I downgraded the package again.

**Comment by waqaskhan540** [comment]
**Application Insights Telemetry (unconfigured):** 

> {"name":"Microsoft.ApplicationInsights.Dev.Exception","time":"2016-12-30T07:31:11.7163196Z","tags":{"ai.operation.name":"POST /connect/token","ai.user.userAgent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36","ai.operation.id":"xHwNj+55hQk=","ai.internal.sdkVersion":"aspnet5c:1.0.0","ai.device.roleInstance":"waqas"},"data":{"baseType":"ExceptionData","baseData":{"ver":2,"handledAt":"Platform","properties":{"DeveloperMode":"true"},"exceptions":[{"id":8133706,"typeName":"Newtonsoft.Json.JsonReaderException","message":"Unterminated string. Expected delimiter: \". Path 'AccessToken.Type', line 1, position 255.","hasFullStack":true,"stack":"   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)\r\n   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)\r\n   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)\r\n   at Newtonsoft.Json.JsonTextReader.ReadAsString()\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at IdentityServer4.Stores.DefaultGrantStore`1.<GetItemAsync>d__8.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Validation.TokenRequestValidator.<ValidateRefreshTokenRequestAsync>d__17.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Validation.TokenRequestValidator.<RunValidationAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Validation.TokenRequestValidator.<ValidateRequestAsync>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Endpoints.TokenEndpoint.<ProcessTokenRequestAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Endpoints.TokenEndpoint.<ProcessAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Hosting.IdentityServerMiddleware.<Invoke>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Hosting.FederatedSignOutMiddleware.<Invoke>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Hosting.AuthenticationMiddleware.<Invoke>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at IdentityServer4.Hosting.BaseUrlMiddleware.<Invoke>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()"}]}}}
> Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:Error: An unhandled exception has occurred while executing the request

**Comment by waqaskhan540** [comment]
I have pushed my identity server on github, kindly have a look and let me know if there is a fix for this. thanks.

[Identity Server ](https://github.com/waqaskhan540/IdentityServerDemo)

**Comment by waqaskhan540** [comment]
I have figured out the issue, the problem is with the identityserver.Entityframework package , somewhere it is not getting the valid json token, the string is invalid so it can't parse it.. I will post the code once I go deep into the issue..

**Comment by brockallen** [comment]
Yes, that's where that error comes from. If you have the JSON record, please post it here so we can see what's inside it.

**Comment by waqaskhan540** [comment]
When I make a request for refresh_token, then on the PersistedGrantStore.cs class GetAsync is called,
the model contains the following Data in JSON which is an invalid JSON.

>{"CreationTime":"2017-01-04T07:57:06.6020074Z","Lifetime":2592000,"AccessToken":{"Audiences":["http://localhost:5000/resources","Core.WebApi"],"Issuer":"http://localhost:5000","CreationTime":"2017-01-04T07:57:06.6010052Z","Lifetime":86400,"Type":"access_t

![capture](https://cloud.githubusercontent.com/assets/15784870/21635174/fa2a5372-d27d-11e6-8f47-d5459ce20c55.PNG)

**Comment by brockallen** [comment]
Can you post the entire json? That seems to be cut off.

**Comment by waqaskhan540** [comment]
this is the exact JSON which I get in the Data property of model, it is cut_off that's why the exception is being generated.

**Comment by brockallen** [comment]
Oh, that's very strange... well, that means there was an error producing the JSON, or persisting the JSON. You're using the EF stores for the persisted grants?

**Comment by waqaskhan540** [comment]
Its varchar 255 which you can also see below
![capture](https://cloud.githubusercontent.com/assets/15784870/21643721/c1bebbee-d2ab-11e6-9729-dc7a3d936c14.PNG)

**Comment by brockallen** [comment]
Ah, Data is 255 -- that explains it. Make it the max length you can for that DB.

**Comment by waqaskhan540** [comment]
Will you update the migrations as well?

**Comment by brockallen** [comment]
> Will you update the migrations as well?

What do you mean?

**Comment by waqaskhan540** [comment]
Sorry , I thought its from the migrations. but there is no max length property specified there..

**Comment by brockallen** [comment]
FYI: https://github.com/IdentityServer/IdentityServer4/issues/660

**Comment by brockallen** [comment]
Did you sort this out?

**Comment by waqaskhan540** [comment]
yup.. its solved..

**Comment by Blastnsmash** [comment]
I am doing a fresh install and I am having this issue as well. 

The ef migrations created varchar 255 for the column data type - But even when changing the data type in the DB the Data content is always 255 bytes (and hence gets truncated)
