### ISSUE TITLE
Secure IdentityServer Host

### ISSUE THREAD

**Issue by Gentlehag** [IdentityServer/IdentityServer4#643]
This question is related to some best practice experience and not to code so i think i post better here than on SO.

Are there any provider specialised to security which are hosting identity server / where I can publish my identity server to and having persistane and so on?

One solution can be on premise but in one project we have no sensitive data at all . so it would be nice to have this securly outsourced. any experiences with this?

Or would you just publish it to your onpremise servers / azure-

**Comment by ravetroll** [comment]
You could host it on Azure.  Thats what I do. It works well.

**Comment by leastprivilege** [comment]
Any cloud provider (Azure, Amazon, Google..) would work.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
