### ISSUE TITLE
Post-login redirect not working correctly

### ISSUE THREAD

**Issue by testaco23** [IdentityServer/IdentityServer4#644]
I set up an MVC client using Implicit flow, and everything seems to be working fine when the user is already authenticated. If I clear my cookies and go to an [Authorize] page, I am redirected to the IdentityServer login page as expected. However I am not redirected back after successful login, and instead I see IdentityServer's page indicating my login was successful (and stay there).

I checked the requests made, and it seems that I am redirected to the /account/login page with the parameters from the /authorize page. Any idea what I could be doing wrong?

The requests from the network tab: http://i.imgur.com/TTfFtwX.png

**Comment by brockallen** [comment]
Any update? Not much info for us to go on here. You might need to do some more debugging.

**Comment by ambarish68** [comment]
Hi, I am facing the same issue.
What is the set of debug info that I could add which will help with diagnosing this?
