### ISSUE TITLE
AddInMemoryUsers?

### ISSUE THREAD

**Issue by eshorgan** [IdentityServer/IdentityServer4#649]
What happened to the "AddInMemoryUsers" extension?  The documentation still references it like it exists, but it appears to be gone. 

It was very useful when testing, I could set up temporary users just like temporary clients.

**Comment by naeemsarfraz** [comment]
@eshorgan, I see you closed your issue . What was the answer? I'm looking for this helper.

**Comment by leastprivilege** [comment]
it is called TestUser now.
