### ISSUE TITLE
Reopen #38 Support for windows authnetication 

### ISSUE THREAD

**Issue by LiveLikeLastDay** [IdentityServer/IdentityServer4#650]
Hi,

IdentityServer4 released verion 1.0.

Can someone reopen [#38 support for windows authnetication](https://github.com/IdentityServer/IdentityServer4/issues/38)? 

Thanks.

**Comment by rposener** [comment]
+1 for that

It works great running behind IIS Express, but as soon as I try to publish to IIS, everything breaks.  Just ends up with a 500 error on /Account/ExternalLogin?provider=Negotiate URL.

**Comment by rposener** [comment]
Looks like you need to configure WebListener.  This means not using Kestrel and not using IIS.  WebListener is it's own web server.  Here are some critical details that seem to be working for me: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/weblistener .

**Comment by leastprivilege** [comment]
both WebListener and Kestrel + IIS Integration works.

**Comment by rposener** [comment]
Any chance some direction on getting this working with Kestrel + IIS Integration would be helpful.  As noted, it seems to work fine under IIS Express, but will not work when deployed to IIS.  Even just a pointer to some MS article or source that might be useful would be helpful.

When run under Kestrel + IIS Express and it does work it still presents a 500 Error Page momentarily then seems to refresh and the credential is set.  Quite odd behavior - I've never seen a 500 error refresh itself.

**Comment by brockallen** [comment]
> Any chance some direction on getting this working with Kestrel + IIS Integration would be helpful.

IIRC our samples/quickstarts were even updated to show how to do this. Do those not work for you?

**Comment by brockallen** [comment]
huh, ok. we'll double check it tomorrow.

**Comment by rposener** [comment]
Didn't mention it in my last post, just for clarity the unmodified Hosts project running this in VS under IIS Express works perfectly when I click the Windows button.  Here is my IIS setup:
![image](https://cloud.githubusercontent.com/assets/1682573/21704178/aa522120-d374-11e6-95fd-acdb7c92135e.png)
![image](https://cloud.githubusercontent.com/assets/1682573/21704182/b8ef98f2-d374-11e6-8dac-fe18e9ee7f95.png)

and I'm just doing a dotnet publish from command line to get it to the directory.  Thanks for the help.

**Comment by brockallen** [comment]
I was able to repro. It's a app identity permissions issue as far as I can tell. I opened an issue here: https://github.com/aspnet/KestrelHttpServer/issues/1288. If I can find a workaround here in IdentityServer, but fundamentally that call should work in ASP.NET Core.

**Comment by brockallen** [comment]
Looks like this was already reported: https://github.com/aspnet/IISIntegration/issues/231

**Comment by brockallen** [comment]
As for a workaround, we could use "Windows" as the provider name -- this is really just used to lookup the user's IdP in the identity management system, and it prolly doesn't care if NTLM or Negotiate is used. Really it just cares that the user is a windows user.

**Comment by brockallen** [comment]
done on dev

**Comment by rposener** [comment]
Excellent!  Thanks for getting to the bottom of it quickly.
