### ISSUE TITLE
Code not working on VS2017 RC 2

### ISSUE THREAD

**Issue by makgul1** [IdentityServer/IdentityServer4#652]
Thank you very much for the tutorials but unfortunately your code is not working on VS2017 RC 2. First of all there is no project.json file in  VS2017 RC 2. When I managed that, new errors came shortly: namely AddIdentityServer(), since the service thus not have that method. 

I could not event run the application! (Running http://localhost:5000/.well-known/openid-configuration step in https://identityserver4.readthedocs.io/en/dev/quickstarts/1_client_credentials.html)

You know identityserver better than me but I believe that you have to design the document step-by-step without ignoring any tiny detail and jumping from one place to another.(eg, adding identity models before adding ApiResource). I also believe, the document should reflect latest implementation in visual studio also.

Can you please update the documentation please?

Thank you very much.

**Comment by brockallen** [comment]
> Thank you very much for the tutorials but unfortunately your code is not working on VS2017 RC 2

Given how unstable the Microsoft tooling has been for the past year (or more), we didn't see the value in trying to support VS 2017 at this time. Once they RTM we will support it.
