### ISSUE TITLE
Relax form-action CSP on authorize response

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#659]
Given the external IdP double-posting issues we found in Chrome, perhaps we should relax the form-action CSP setting.

**Comment by brockallen** [comment]
Related: https://github.com/IdentityServer/IdentityServer4/issues/475

**Comment by BobBoba** [comment]
Fantastic! 1.0.1-build00660 works fine now, many thanks @brockallen for great job!

**Comment by xmichaelx** [comment]
I'm adding my SO question to illustrate how issue may look like: http://stackoverflow.com/questions/41854600/identityserver-used-as-external-identity-provider-for-another-identityserver-fai/41862927

Update from 1.0.0 to 1.0.2 solved the problem for me. Thank you!
