### ISSUE TITLE
Consider custom response params on authorize endpoint

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#661]
Much like token endpoint

**Comment by R74NN** [comment]
Hello,
do I understand it correctly, that this feature should allow me to pass "original url" from client as a parameter during user login?

Currently I need my JS client to know what was the original page requested by the user before redirecting to auth server login page. The "redirect_uri" parameter in client setup is not enough to restore originally requested page on the client.

Or is there another way how to accomplish this now?

Thanks.

**Comment by leastprivilege** [comment]
You would use the `state` parameter for that.

**Comment by R74NN** [comment]
I'm a bit lost here. state parameter seems to be used by JS Oidc-client library, so I can't alter it?

**Comment by brockallen** [comment]
You can pass some state, as shown here: https://github.com/IdentityModel/oidc-client-js/blob/dev/sample/public/user-manager-sample.js#L103

and then on the callback get it back out on the `user.state` property: https://github.com/IdentityModel/oidc-client-js/blob/dev/sample/public/user-manager-sample.js#L112

**Comment by R74NN** [comment]
Works perfectly! Thank you.
