### ISSUE TITLE
how to set cookie expiration in IdentityServer4?

### ISSUE THREAD

**Issue by murraywsmith** [IdentityServer/IdentityServer4#662]
I've implemented a server using IdentityServer4. After logging in, if the user does nothing for some period of time, say 15 minutes, I would like the cookie with their identity token to become invalid so they will need to log in again. I have tried setting the SlidingExpiration and ExpireTimeSpan values in the CookieAuthentitcationOptions in the Configure() method in Startup.cs in my identity server. However, when I look at the generated cookies in Chrome using it's developer tools, the idsrv and idsrv.session cookies both have their expiration set to "Session".

This is my Configure() method from Startup.cs. The ExpireTimeSpan is being set to 1 second for test puposes.

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            Func<string, LogLevel, bool> filter = (scope, level) =>
                scope.StartsWith("IdentityServer") ||
                scope.StartsWith("IdentityModel") ||
                level == LogLevel.Error ||
                level == LogLevel.Critical;

            loggerFactory.AddConsole(filter);
            loggerFactory.AddDebug(filter);

            app.UseDeveloperExceptionPage();

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = "Cookies",

                AutomaticAuthenticate = false,
                AutomaticChallenge = false,
                SlidingExpiration = true,
                ExpireTimeSpan = System.TimeSpan.FromSeconds(1.0)
            });

            app.UseIdentityServer();

            app.UseStaticFiles();

            app.UseMvcWithDefaultRoute();
        }

Any suggestions are welcome.

**Comment by leastprivilege** [comment]
You need to tell identityserver which cookie middleware to use (in your case the one with the scheme "Cookies") - that is configured in the options in ConfigureServices.

**Comment by murraywsmith** [comment]
Thanks for the quick reply. I'm new to this and am not sure exactly how to tell identityserver which cookie middleware to use. This is what I have in my ConfigureServices method in Startup.cs.

public void ConfigureServices(IServiceCollection services)
        {
            var cert = getX509Certificate();

            IIdentityServerBuilder builder = services.AddIdentityServer();
            builder.AddInMemoryClients(Config.GetClients());
            builder.AddInMemoryIdentityResources(Config.GetIdentityResources());
            builder.AddInMemoryApiResources(Config.GetApiResources());
            builder.AddSigningCredential(cert);
            builder.Services.AddTransient<IProfileService, ProfileService>();

            // Add framework services.
            services.AddMvc();
        }

**Comment by leastprivilege** [comment]
AddIdentityServer takes an options class - there are authentication related settings - and there you can set the scheme.

**Comment by brockallen** [comment]
There's an open issue to document this: #656

**Comment by brockallen** [comment]
The short answer as Dom said is to setup your own cookie middleware and let us know about it via this property: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/Options/AuthenticationOptions.cs#L21

I'll close this for now and we can track docs progress on #656.
