### ISSUE TITLE
The specified CGI application encountered an error and the server terminated the process.

### ISSUE THREAD

**Issue by ravetroll** [IdentityServer/IdentityServer4#664]
I have recently updated my IdentityServer4 Host to Net Core 1.1.  It works perfectly authorising my client when I run them both in VS2015 in debug mode.  No errors, all perfect.  I have a CI setup where my checkins to VSTS are built and deployed to Azure.  This all worked fine on my old Net Core 1.0 and the whole deployment part I have updated and the application does run and access the database on the new Net Core 1.1 build.  The problem comes when I try to hit an endpoint with [Authorise] that should be redirecting off to the login screen.  In that case I get the message that is the subject of this thread.  I set up logging and there are no Exceptions thrown except for the https://github.com/aspnet/IISIntegration/issues/239 one which is apparently harmless.  Has anyone else had any luck getting a Host up and running with Net Core 1.1 using VSTS CI build and deploy to Azure Web App?

**Comment by brockallen** [comment]
Yes, we have IS4 running in Azure.

**Comment by ravetroll** [comment]
Ok, I have created something similair to my setup based on Quickstart5 with the same CI setup I use on my main project and it works.  Now I need to try and find out why my main project is failing on Azure and running perfectly in Dev.  Based on my experience I would say its the configuration thats wrong but I have gone over it in detail already.  My beta5 IS4 on Net Core 1.0 ran perfectly in Azure so I need to try and isolate what aspect of the upgraded project is triggering the error.

**Comment by brockallen** [comment]
The only azure oddity that we've heard of was this: https://github.com/IdentityServer/IdentityServer4/pull/645

We'll release a patch next week.

**Comment by ravetroll** [comment]
I have located the problem.  It relates to services.AddIdentityServer.AddSigningCredential(cert)

In my previous version of IS4 I used a certificate for signing so I decided to continue doing so.  

I get my certificate using

`X509Certificate2 cert = GetCertificate(Configuration["AppSettings:Certificates:SigningCredentialsThumbprint"]);`

I think I was failing to retrieve a certificate and this was causing a sudden stop when it was required.  There would simply be nothing in the log after the following events:

```
dbug: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[9]
      AuthenticationScheme: idsrv was not authenticated.
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /.well-known/openid-configuration/jwks matched to endpoint type Discovery
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Mapping found for endpoint: Discovery, creating handler: IdentityServer4.Endpoints.DiscoveryEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration/jwks
trce: IdentityServer4.Endpoints.DiscoveryEndpoint[0]
      Processing discovery request.
dbug: IdentityServer4.Endpoints.DiscoveryEndpoint[0]
      Start key discovery request
trce: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking result: IdentityServer4.Endpoints.Results.JsonWebKeysResult
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL1N76IS27JH" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 83.9096ms 200 application/json

```

I am not sure if it is possible to put some code in IS4 to make it give a warning if the certificate is not there.  Could save some people some time in future.

**Comment by brockallen** [comment]
Glad you sorted it out. As for logging, good idea: #665.
