### ISSUE TITLE
Use identityserver4 handling roles,claims,user, etc by EF

### ISSUE THREAD

**Issue by massimopasquali** [IdentityServer/IdentityServer4#668]
I guys, I have to use identityserver4 and EF for authorize a web application. I would like to do that checking scope, roles, claim and users that will be memorize in a SQL Server DB.
I can't find an example, I have read the doc online, where explaining like to implement EF, but it doesn't explain like to use the roles memorize in the store.
So can you help me!? Can you explain me like to receive the roles from DB to ability the property Authorize in c# language ?

**Comment by brockallen** [comment]
Scopes, and Clients can be configured like this: https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html

User identity is your responsibility. ASP.NET Identity can be used like this: https://identityserver4.readthedocs.io/en/release/quickstarts/6_aspnet_identity.html

Further questions like this should be asked on StackOverflow. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by andy194** [comment]
None of these links resolve correctly?
