### ISSUE TITLE
Standard UI

### ISSUE THREAD

**Issue by nicolasr75** [IdentityServer/IdentityServer4#67]
The MVC sample shows how to implement my own UI for login. That's great but in many cases I want to keep it as simple as possible because I need the UI only for testing the API with browsers. Therefore a standard UI would be great.

In the announcements a standard UI is mentioned. Is this already available?

**Comment by henningst** [comment]
A simple standard UI based on Bootstrap is already included in the IdentityServer package. You can see the source code here: https://github.com/IdentityServer/IdentityServer4/tree/dev/src/Host/UI

**Comment by nicolasr75** [comment]
Thanks, wasn't aware of that.
