### ISSUE TITLE
how to "IncludeAllClaimsForUser = true" in the new version

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer4#670]
Up to the RC3 version where there was still the notion of "Scopes" we could create a scope and set the "IncludeAllClaimsForUser" property on it to through, and then by implementing the IProfileService interface we could add exactly each claim that we wanted to the access token.

Now that the ApiResource has replaced the "Scope", I cannot find that setting anymore. And therefore when I send an authentication request using Postman my implementation of the IProfileService doesn't event get hit (resource owner password grant).

Is there an equivalent to that "IncludeAllClaimsForUser" property somewhere in the new version?

**Comment by brockallen** [comment]
Add the claims you need/want to the UserClaims or write a custom profile service to emit all the claims.
