### ISSUE TITLE
AddSigningCredential does not seem to pick up certificate from Azure Web App

### ISSUE THREAD

**Issue by ravetroll** [IdentityServer/IdentityServer4#671]
I can get AddSigningCredential to work with a file in my app directory which is bad practice for production.

I can load a certificate into the SSL Blade in Azure Web App service and then I can access that certificate using 

```
public static X509Certificate2 FindCertificateByThumbprint(string findValue)
        {
            X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
            
            try
            {
                store.Open(OpenFlags.ReadOnly);
                X509Certificate2Collection col = store.Certificates.Find(X509FindType.FindByThumbprint,
                    findValue, false); // Don't validate certs, since the test root isn't installed.
                if (col == null || col.Count == 0)
                    return null;
                return col[0];
            }
            finally
            {
                
                store = null;
            }
        }
```

I have made a test page to verify that I am actually getting a certificate and I definitely am as I can read its properties after returning it from the above function.  When I pass in that certificate to AddSigningCredential and then try to access a secured page I get the error I described in https://github.com/IdentityServer/IdentityServer4/issues/664 .  I am using a self signed certificate which should be fine for this purpose.  If I access the certificate as a pfx file out of my app directory it works.  If I upload the pfx into Azure Web App on the SSL blade and reference it by its thumbprint I get the error when I try to use it.  No error is logged as described in https://github.com/IdentityServer/IdentityServer4/issues/664

**Comment by leastprivilege** [comment]
I can't repro that - this works fine for us in Azure:

https://github.com/IdentityServer/IdentityServer4.Demo/blob/master/src/IdentityServer4Demo/Startup.cs#L44

**Comment by ravetroll** [comment]
I have tried using that same line, with my own thumbprint of course and I get the 'The specified CGI application encountered an error and the server terminated the process.'  . My certificate test page confirms Azure is reading my certificate and I have tried uploading other certificates and using those too with the same result.  When I refer to the pfx file in my app directory and get my cert using  `return new X509Certificate2(Path.Combine(_environment.ContentRootPath, "idserver.pfx"), "Password");` it works perfectly.  Its the same certificate I uploaded into Azure

**Comment by leastprivilege** [comment]
Then I don't know. 

I would try streaming logs or Kudu to get to the FREBs or the event log to find out what unhandled exception is thrown.

**Comment by ravetroll** [comment]
I have created a new App Plan (S1) and a new web app in it.  I have compiled your IdentityServer4Demo and published to Azure.  The only thing I changed was uploading a different certificate to the SSL Blade with its thumbprint configured for AddSigningCredential.  I get a 500 Internal Server Error on startup with that but all goes well if I use  `builder.AddTemporarySigningCredential();`  I am thinknig maybe my certificate is wrong or is the wrong type or not compatible.  Could you attach a valid cert I could try with or show me the commands to make a compatible cert.  I used something like this but with different names and a valid date range to make my cert:

```
makecert -sv mykey.pvk -n "cn=KVWebApp" KVWebApp.cer -b 07/31/2015 -e 07/31/2016 -r
pvk2pfx -pvk mykey.pvk -spc KVWebApp.cer -pfx KVWebApp.pfx -po test123 
```

**Comment by ravetroll** [comment]
I have managed to make this work by using the test certificate used by the IS4 team idsrv3test.pfx  My own self signed certificate didn't work when referenced out of the Azure App certificate store but did work when  I created a reference to it as a pfx file as in ` return new X509Certificate2(Path.Combine(_environment.ContentRootPath, "idserver.pfx"), "Password");`

So something is different about the certificate I was using so I compared its properties to the ones in idsrv3test.pfx .  There is an additional property called 'Enhanced Key Usage' with a value of Server Authentication (1.3.6.1.5.5.7.3.1) in idsrv3test.pfx that my certificate did not have which might be the reason.  Could the IS4 team provide a powershell command to create the 'right' type of certificate as i see makecert is deprecated https://msdn.microsoft.com/en-us/library/windows/desktop/aa386968(v=vs.85).aspx

**Comment by leastprivilege** [comment]
I am using makecert.

see https://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/

**Comment by ravetroll** [comment]
I think I may have been on the wrong trail with that certificate problem.  After restarting the app and playing with some settings I was back to the original error even with the idsrv3test.pfx loaded into the store.  I did manage to coax a new error out of my dev environment 

`An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Security.Cryptography.X509Certificates.dll`

I was also then able to get this error showing on startup in the Azure web App.  (I think I had AlwaysOn set which was tracking it through the startup before I could get back to the LogStream from the App restart button and there was never anything about this in the logs).

This led me to this issue with net core 1.1 https://github.com/dotnet/coreclr/issues/8148

I was able to resolve the problem by putting this as an environment variable in my dev environment and as an application setting in azure:

Key: COMPlus_ReadyToRunExcludeList
Value:  System.Security.Cryptography.X509Certificates

It seems like this is a known problem with net core 1.1 and while the IdentityServer4 demo doesn't seem to trigger it my application did.  Anyhow glad to say I am back in business!  Thanks for your patience and help.

**Comment by leastprivilege** [comment]
fun..

thanks for investigating this.

**Comment by eloekset** [comment]
@ravetroll, did you get a running version in Azure using the SSL storage of App Service for the certificate? I'm having trouble on startup now, and I've added the config key/value of your latest comment to the Application Settings, but no luck so far.

The sample code that @leastprivilege linked to in an earlier comment in this issue was changed 4th April, so it seems like they've got an issue in the sample as well. The current sample code has commented out the line that should use real SigningCredential and use AddTemporarySigningCredential() for both dev and prod environments.

**Comment by eloekset** [comment]
This did the trick for me: https://azure.microsoft.com/en-us/blog/using-certificates-in-azure-websites-applications/

> Adding an app setting named WEBSITE_LOAD_CERTIFICATES with its value set to the thumbprint of the certificate will make it accessible to your web application. You can have multiple comma-separated thumbprint values or can set this value to “ * “ (without quotes) in which case all your certificates will be loaded to your web applications personal certificate store. To add this configuration for your website, go to the configure option for your website in the management portal, scroll down to the app settings section and add the setting as shown below with the thumbprint of the certificate you uploaded in the previous step.
