### ISSUE TITLE
"No Client Identifier Found"

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer4#672]
I have setup IdentityServer4 and it works fine as long as I use Postman to obtain access tokens (using resource owner grant), however, when I send the exact same request within a javascript application, I get a 400 bad request on the browser console and the following error in the IdentityServer console:

![image](https://cloud.githubusercontent.com/assets/297620/21782850/c98545b6-d669-11e6-84df-cb3ea0d4306d.png)

"No client identifier found". Here is the request sent in Typescript, using exact same parameters and values as I use in my Postman:

`let head = new Headers({
          'content-type': 'application/x-www-form-urlencoded'
      });
      let options = new RequestOptions({
          headers: head
      });
      let body = JSON.stringify({
          "grant_type":"password",
          "username": "behrooz66",
          "client_id": "resourceOwner",
          "client_secret": "secret",
          "password": "bbcliqa",
          "scope": "api offline_access"
      });

      let x = this._http.post("http://localhost:5000/connect/token", body, options)
            .map(res => res.json());
      return(x);`

Any ideas?

**Comment by brockallen** [comment]
hmm, 5m from open to close. so what was it?

**Comment by behrooz66** [comment]
Sorry, I realized the format of the body is not right. My bad :(

**Comment by mo-norant** [comment]
why dont you say your fix then

**Comment by alokbaburdc** [comment]
https://stackoverflow.com/questions/43912622/identity-server-4-getting-invaid-client-error
