### ISSUE TITLE
Difference between Client Scopes and Client Claims

### ISSUE THREAD

**Issue by eventgenius** [IdentityServer/IdentityServer4#674]
- [ ] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem

I am trying to setup a configuration interface for our Identity Server 4 implementation. During client configuration, there's a `Claims` property of type `ClientClaims`, and also an `AllowedScopes` property of type `ClientScopes`. What is the difference between client claims and client scopes?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
Think of client claims as static claims associated with a client - mostly useful for server to server style scenarios.

**Comment by eventgenius** [comment]
Thanks @leastprivilege
