### ISSUE TITLE
Cluster environment

### ISSUE THREAD

**Issue by biasmey** [IdentityServer/IdentityServer4#677]
If I running identityserver4 on amazon ECS and running more than one task ,not working fine  to redirect after login . Can Identityserver4 working on cluster environment.

**Comment by biasmey** [comment]
Thanks , I needed put  Sticky Sessions enabled on the load balancer, is working now.

**Comment by brockallen** [comment]
> Thanks , I needed put Sticky Sessions enabled on the load balancer, is working now.

This is not an IdentityServer requirement, so it must be something required from your custom code.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by biasmey** [comment]
I was checking my custom implementation for user and grants and I not used memory , but if I remove the  Stickiness  in my load balancer the login paga not working never redirect to client  , I checked the logs and I found "AuthenticationScheme: idsrv was not authenticated." , Could you help me 

``` [14:21:12 INF] Microsoft.AspNetCore.Hosting.Internal.WebHost
14:21:12
Mapping found for endpoint: Authorize, creating handler: IdentityServer4.Endpoints.AuthorizeEndpoint
[14:21:12 DBG] IdentityServer4.Hosting.EndpointRouter
[14:21:12 DBG] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware
[14:21:12 DBG] IdentityServer4.Hosting.EndpointRouter
14:21:12
Request path /connect/authorize matched to endpoint type Authorize
14:21:12
AuthenticationScheme: idsrv was not authenticated.
[14:21:12 INF] IdentityServer4.Hosting.IdentityServerMiddleware
14:21:12
Invoking IdentityServer endpoint: IdentityServer4.Endpoints.AuthorizeEndpoint for /connect/authorize
[14:21:12 DBG] IdentityServer4.Endpoints.AuthorizeEndpoint
14:21:12
Start authorize request
[14:21:12 DBG] Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware
14:21:12
AuthenticationScheme: idsrv was not authenticated.
[14:21:12 DBG] IdentityServer4.Endpoints.AuthorizeEndpoint
14:21:12
No user present in authorize request```

**Comment by leastprivilege** [comment]
Have you setup the shared data protection key container?

**Comment by biasmey** [comment]
Thanks for your quick reply , No, I do not have

**Comment by biasmey** [comment]
My client configuration is 
``` app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = "Cookies",
                AutomaticAuthenticate = true,
                ExpireTimeSpan = TimeSpan.FromMinutes(60)
            });

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

            app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",

                Authority = Clients.Constants.BaseAddress,
                RequireHttpsMetadata = false,

                ClientId = "myclient",
                ClientSecret = "secret",

                ResponseType = "code id_token",
          
                GetClaimsFromUserInfoEndpoint = true,
                SaveTokens = true,
                
                TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
                {
                    NameClaimType = JwtClaimTypes.Name,
                    RoleClaimType = JwtClaimTypes.Role,
                }
            });```

**Comment by leastprivilege** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/introduction

**Comment by biasmey** [comment]
Thanks you so much, That was my problem. I stored the data protection in SqlServer  and is working perfect  👍

**Comment by Mardoxx** [comment]
Is this needed as well as having each instance use `AddSigningCredential()`s? Or is just using one, or the other, sufficient?

**Comment by leastprivilege** [comment]
Each instance needs access to the signing credential

https://identityserver4.readthedocs.io/en/release/topics/deployment.html

**Comment by Mardoxx** [comment]
Does each instance need to set up data protection API too? Or is that handled by setting the signing credential?

**Comment by leastprivilege** [comment]
Data protection and signing certs are unrelated. Are the docs not clear - should we change something or add more info?

**Comment by Mardoxx** [comment]
Confusion on my part most likely.

So signing certs are used to sign and validate generated tokens. What data is protected using the data protection API? 

http://docs.identityserver.io/en/release/topics/crypto.html#data-protection

**Comment by leastprivilege** [comment]
Cookies and Anti-Forgery e.g.

**Comment by Mardoxx** [comment]
Not sure what I'm trying to as here, but how are cookies used in IdentityServer? Or rather ,what are they used for? Is it just for local account sign in and remember-me settings?
