### ISSUE TITLE
IdentityServer4 - What happened to IUserService.AuthenticateExternalAsync?

### ISSUE THREAD

**Issue by smuthiya** [IdentityServer/IdentityServer4#680]
In IdentityServer3 - I have implemented IUserService with specific implementation for "AuthenticateExternalAsync" and "GetProfileDataAsync" 

Now when I migrated to IdentityServer4 - I have implemented the IProfileService which lets me implement my "GetProfileDataAsync" however I am not able to map where the existing "AuthenticateExternalAsync" implementation will move?

**Comment by smuthiya** [comment]
Is it now under AccountController.ExternalLoginCallback method?

**Comment by leastprivilege** [comment]
yes

**Comment by shaikatz** [comment]
@leastprivilege I'm facing the same issue and I can't find ExternalLoginCallback can you share more details?

**Comment by smuthiya** [comment]
@shaikatz - AuthenticateExternalAsync is no more part of IUserService in IdentityServer4 implementation. For authenticating user external you need to implement a logic. You can start with Quickstart UI provided at following location 
**https://github.com/IdentityServer/IdentityServer4.Quickstart.UI**
