### ISSUE TITLE
Always invoke profile service in DefaultClaimsService 

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#683]

**Comment by akamud** [comment]
I'm working on this.

Do you think this should happen to `access_token` only or for both the `access_token` and `id_token`?

**Comment by brockallen** [comment]
both

**Comment by akamud** [comment]
Where could we put this in the documentation?

The closest mention to adding Claims to tokens is in this [page](http://docs.identityserver.io/en/release/configuration/resources.html), but I'm not sure if it makes sense.

**Comment by leastprivilege** [comment]
done

**Comment by akamud** [comment]
Where can I put this in the docs? There is way other than looking at the code to know how to do this.
