### ISSUE TITLE
using an object initializer on ApiResource

### ISSUE THREAD

**Issue by aaronralls** [IdentityServer/IdentityServer4#687]
When using the object initializer on ApiResource and not setting the required Scope explicitly thus the default Scope of the ApiResource.Name is never added.

                new ApiResource
                {
                            
                    Name = "APItest"
                 }

work around:

                new ApiResource
                {
                            
                    Name = "APItest",
                    
                    Scopes = new[]
                    {
                        new Scope("APItest", "api default scope")
                    }

                }

work around #2 use non default constructor.
               new ApiResource("APItest")

**Comment by brockallen** [comment]
The ctor that accepts scope name and description is designed as the convenience mechanism if you don't want to set the properties/collections correctly.
