### ISSUE TITLE
Build in the "openid" scope

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#689]
Doesn't need to be configured as an identity resource anymore.

Handle the fact that it might be explicitly registered in a resource service.

**Comment by brockallen** [comment]
I was thinking about this, and the UI will have to handle the absence/presence of this in consent (as it does now for offline).

**Comment by leastprivilege** [comment]
How about we register an additional "BuiltInResourcesStore" that always has openid and offline_access (if not provided by explicitly registered store) ?

**Comment by railarmenien** [comment]
Totally agree with this feature, migrating from a Katana based OAuth2 server to IS4, we had to register an AuthorizeRequestShimMiddleware before IS4 to handle adding those scopes to the authorize request. That way migration was as transparent as it could be for clients.
