### ISSUE TITLE
IdentityTokenValidationEndpoint missing

### ISSUE THREAD

**Issue by ash23** [IdentityServer/IdentityServer4#69]
Am I correct in assuming that IdentityTokenValidationEndpoint has not yet been implemented in IdentityServer4? 

It exists as an option in EndpointOptions however the actual endpoint class does not seem to exist.
I am writing a Angular SPA application using the Implicit flow and would like to validate the identity token from the client. If this endpoint has indeed not yet been implemented is there a recommended work around to use? 

Also when is it planned to be implemented?

Thanks for a brilliant product, you guys rock.

**Comment by leastprivilege** [comment]
Yep - this endpoint is not implemented yet. No high prio plans to bring it back right now.

Use a JS lib that does local validation e.g. Brock's oidc-token-manager in the IdentityModel org.

**Comment by ash23** [comment]
OK thanks for the clarification and for the quick response!
