### ISSUE TITLE
Always invoke profile service even if no claims requested

### ISSUE THREAD

**Issue by brockallen** [IdentityServer/IdentityServer4#691]

**Comment by brockallen** [comment]
done

**Comment by mikebridge** [comment]
@brockallen [The documentation doesn't give a full description of IProfileService](http://docs.identityserver.io/en/release/search.html?q=IProfileService&check_keywords=yes&area=default), but am I correct in assuming that with this modification, the claims added by `IProfileService.GetProfileDataAsync` will be added to both Identity Token and the Access Token, but before 1.0.2 they were only added to the Identity Token?  This seems to be the behaviour I'm seeing when upgrading from QuickStart 7's version 1.0.0 to 1.1.1.

**Comment by mikebridge** [comment]
It looks like the commit is [this one](https://github.com/IdentityServer/IdentityServer4/commit/f5b5d2e28e1251cea51183bacb23e54102c50dd4), and it's getting called for the Identity Token [here](https://github.com/IdentityServer/IdentityServer4/blob/f5b5d2e28e1251cea51183bacb23e54102c50dd4/src/IdentityServer4/Services/DefaultClaimsService.cs#L83) and again for the Access Token in this method [here](https://github.com/IdentityServer/IdentityServer4/blob/f5b5d2e28e1251cea51183bacb23e54102c50dd4/src/IdentityServer4/Services/DefaultClaimsService.cs#L192).  So I guess the answer is that IProfileService will normally be queried for both tokens.
