### ISSUE TITLE
Connect Identity Server 4 with Asp.net MVC5 ,WebForms and Web Api

### ISSUE THREAD

**Issue by anirudh89haridas** [IdentityServer/IdentityServer4#693]
Currently I am working a project that needs to integrate SSO. They are having multiple clients with different frameworks.It would be very helpful if you can share some samples for the same.

**Comment by brockallen** [comment]
we have several: https://identityserver4.readthedocs.io/en/release/quickstarts/0_overview.html

**Comment by anirudh89haridas** [comment]
Thanks for the quick response.

I am planning to run identity server 4 Authentication.So is it possible to use the same client code in identity server 3 example?(Please look it this link https://github.com/IdentityServer/IdentityServer3.Samples/blob/master/source/Clients/WebFormsClient/Startup.cs)

Also in future is there is any plan to add client which is written in java or php?

**Comment by brockallen** [comment]
It's all protocol, so you can use the katana client stack to connect to IdentityServer4.

As for java or php -- see the OIDC home page for links to those other stacks.
