### ISSUE TITLE
IProfileService does not execute GetProfileDataAsync to issue custom claims

### ISSUE THREAD

**Issue by iberodev** [IdentityServer/IdentityServer4#698]
### Issue / Steps to reproduce the problem
After migrating to IdentityServer 1.0.0 from the last RC I have found a few issues.

I had a custom service `AspNetIdentityProfileService : IProfileService` registered in the DI container:
`builder.Services.AddScoped<IProfileService, AspNetIdentityProfileService>();`
to issue custom claims in the token.

Now I can see this class is being instantiated but its methods `GetProfileDataAsync` or `IsActiveAsync` are never executed and I don't know why (so my token is missing some claims).

Has it changed the way to issue/overwrite custom claims or am I missing something to have this working as before?

Thanks

### Relevant parts of the log file

```
IdentityServer4.Endpoints.AuthorizeEndpoint:Information: ValidatedAuthorizeRequest
{
  "ClientId": "speedi_cargo_client",
  "ClientName": "SpeEDI Cargo",
  "RedirectUri": "http://localhost:8080/callback",
  "AllowedRedirectUris": [
    "http://localhost:60499/silent_renew.html",
    "http://localhost:60499/callback",
    "http://localhost:8080/callback",
    "http://localhost:8080/silent_renew.html"
  ],
  "SubjectId": "318f51f6-ac04-42b6-bae3-fe544587970a",
  "ResponseType": "id_token token",
  "ResponseMode": "fragment",
  "GrantType": "implicit",
  "RequestedScopes": "openid profile email roles speedi.cargo",
  "State": "748bdee5850d4207ac517e3d20b8a487",
  "Nonce": "f2e85b7c05624b82acde88fe25fe1484",
  "SessionId": "34f4a1c47fb74a301f86f6da0dfedd6b",
  "Raw": {
    "client_id": "speedi_cargo_client",
    "redirect_uri": "http://localhost:8080/callback",
    "response_type": "id_token token",
    "scope": "openid profile email roles speedi.cargo",
    "state": "748bdee5850d4207ac517e3d20b8a487",
    "nonce": "f2e85b7c05624b82acde88fe25fe1484"
  }
}
//...
IdentityServer4.Endpoints.AuthorizeEndpoint:Information: Authorize endpoint response
{
  "SubjectId": "318f51f6-ac04-42b6-bae3-fe544587970a",
  "ClientId": "speedi_cargo_client",
  "RedirectUri": "http://localhost:8080/callback",
  "State": "748bdee5850d4207ac517e3d20b8a487",
  "Scope": "openid profile email roles speedi.cargo"
}
```

There is an old similar issue but the link to documentation is broken https://github.com/IdentityServer/IdentityServer4/issues/458
and [this other link](http://docs.identityserver.io/en/release/quickstarts/3_interactive_login.html?highlight=IProfileService) does not clarify much.

**Comment by iberodev** [comment]
Found that the solution was to AlwaysIncludeClaimsInIdToken at the Client's configuration.

**Comment by michael-freidgeim-webjet** [comment]
Correct name of property is **_AlwaysIncludeUserClaimsInIdToken_**
