### ISSUE TITLE
How can I implement PersistedGrantStore on my mongodb database

### ISSUE THREAD

**Issue by mohamed-elsabagh** [IdentityServer/IdentityServer4#699]
I am trying to implement PersistedGrantStore on mongodb, I have managed successfully to use mongodb to store users and client and now I am trying to store grants instead of using in memory grant stores I created a class which inherits from IPersistedGrantStore

`

    public class PersistedGrantStore : IPersistedGrantStore
    {
        public async Task<IEnumerable<PersistedGrant>> GetAllAsync(string subjectId)
        {
            PersistedGrantService persistedGrantService = new PersistedGrantService();
            return await persistedGrantService.GetAllPersistedGrant(subjectId);
        }

        public async Task<PersistedGrant> GetAsync(string key)
        {
            PersistedGrantService persistedGrantService = new PersistedGrantService();
            return await persistedGrantService.GetPersistedGrantByKey(key);
        }

        public async Task RemoveAllAsync(string subjectId, string clientId)
        {
            PersistedGrantService persistedGrantService = new PersistedGrantService();
             await persistedGrantService.RemoveAllBySubjectIdAndClientId(subjectId, clientId);
        }

        public async Task RemoveAllAsync(string subjectId, string clientId, string type)
        {
            PersistedGrantService persistedGrantService = new PersistedGrantService();
            await persistedGrantService.RemoveAllBySubjectIdAndClientIdAndType(subjectId, clientId, type);
        }

        public async Task RemoveAsync(string key)
        {
            PersistedGrantService persistedGrantService = new PersistedGrantService();
            await persistedGrantService.RemoveAllByKey(key);
        }

        public async Task StoreAsync(PersistedGrant grant)
        {
            PersistedGrantService persistedGrantService = new PersistedGrantService();
            await persistedGrantService.InsertPersistedGrant(grant);
        }
    }
`

And in startup.cs

```
    public void ConfigureServices(IServiceCollection services)
    {
        var builder = services.AddIdentityServer()
            .AddSigningCredential(cert)
            .AddInMemoryIdentityResources(IdentityConfiguration.GetIdentityResources())
            .AddInMemoryApiResources(ApiResourceConfiguration.GetApiResources());

        builder.Services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();
        builder.Services.AddTransient<IProfileService, ProfileService>();
        builder.Services.AddTransient<IClientStore, ClientStore>();
        builder.Services.AddTransient<IPersistedGrantStore, PersistedGrantStore>();
    }
```

It seems whatever I do none of the functions in PersistedGrantStore is called, I am not sure what I a missing here, still I can ping the server and get access token so I am assuming inmemory storage is still being used.

**Comment by brockallen** [comment]
If you're not using the flows that require persistence, then you might not see any called.  You should see calls if you're using code/hybrid flow, reference tokens, or prompting for consent.

**Comment by mohamed-elsabagh** [comment]
Thanks so much, I added AllowOfflineAccess = true to client and now I can see the application is creating the new collection on the DB
