### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by mbeckenbach** [IdentityServer/IdentityServer4#7]
Hi, 

I'm developing an app on asp.net 5 at the moment and would like to give identity server a try. The docs on identity server 3 look like it can save lots of headache. :-)

I've seen there are already many examples for this new version. Is it worth playing arround with it or should I wait? 

Are there important features, that are currently missing? Do you expect bigger breaking changes as far as you can say now?

I'm not planning to go live soon and I know things can change during development. 

As I don't care about .net core at the moment, some missing support for that would not be a show stopper for me.

Thanks for any input on this

Max

**Comment by brockallen** [comment]
Most of the core from IdentityServer3 is the same in IdentityServer4. The main things that will be changing relate to the user service and how your UI pages are invoked from IdentityServer (login page, error page, etc). Unfortunately these are the places you spend the most of your time coding for IdentityServer. So I'm not sure what to tell you. In a month's time these aspects will be much more stable, but at the same time if you start to try them out now you are in a perfect position to provide feedback on what works and what doesn't work.

What do you think?

**Comment by mbeckenbach** [comment]
Sounds good and I would be happy to provide feedback.

Any tip where i should have a look in the examples for getting an idea of the new ui invoking and user service? I think there is nothing like a documentation yet, correct?

**Comment by brockallen** [comment]
The MVC sample 

-Brock

**Comment by mbeckenbach** [comment]
OK. If that's all to look at, let's go. :)

**Comment by mbeckenbach** [comment]
First positive feedback, after playing arround for some time:

I really like the usage of ViewLocationExpanders. This helps much to keep the project directories clean and gives the feeling of component driven development while still using mvc. 

But the naming of the UI folder in the example feels somehow wrong. Don't know why.
