### ISSUE TITLE
usage with mongodb and aspnet identityserver 3

### ISSUE THREAD

**Issue by parmarnishant** [IdentityServer/IdentityServer4#70]
Is there any reference for using this with mongodb and isentity server 3 ?

**Comment by henningst** [comment]
I'm not sure if I understand your question. This is the repository for IdentityServer 4. If you want to use Identity Server 3, you'll use that version. IdentityServer 4 is implemented on ASP.NET Core.

If you want to use IdentityServer 3 with MongoDB, you could have a look at this:
https://github.com/jageall/IdentityServer.v3.MongoDb

I have written a sample for IdentityServer 4 using MongoDB here:
https://github.com/henningst/IdentityServer4-MongoDB-Sample/
