### ISSUE TITLE
How to update claims on refresh tokens refresh?

### ISSUE THREAD

**Issue by sriram5052** [IdentityServer/IdentityServer4#705]
it's not an issue, its a question.
Setup
Identity server- HybridAndClientCredentials
scope - IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Email,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.OfflineAccess,
                       "api","offline_access" 
UpdateAccessTokenClaimsOnRefresh=true,
 AllowOfflineAccess = true,

I was trying to update the custom claims on the client, but couldn't update the claim to the identity server.
It would be great if you could point me at right direction for updating the claim.
whether the way i am trying to update the claim by refreshing token is right or not?

**Comment by sriram5052** [comment]
i have claim named facility_id, which has to be changed when the user change the default facility.
i have updated the facility_id in the client.but how to update it to the database through identity server.

**Comment by leastprivilege** [comment]
Data management is not our problem - go to your database and update it yourself ;)

Also - if the data frequently changes - it is probably not a good candidate for a claim in a token.

**Comment by sriram5052** [comment]
Thanks for the answer, i thought identity will take care of updating claim to database. Now it's clear.
