### ISSUE TITLE
Upgrading to IdentityServer4 1.0.2 raises errors

### ISSUE THREAD

**Issue by ahodroj74** [IdentityServer/IdentityServer4#716]
Hello,

I have IdentityServer4 (1.0.1) running fine as an MVC application.
In order to resolve the issue: (GetProfileDataAsync not being invoked)
I migrated to 1.0.2 which is supposed to fix this issue according to the new release details:
#691 Always invoke profile service even if no claims requested.
Yes, my IProfileService is added to the pipeline.

Now, I can't run my APP. It compiles fine however it raises an error on:
app.Map("/api", apiApp =>
            {
                apiApp.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
                {
                    Authority = "https://localhost:5000",
                    ApiName = "api"
                });
                apiApp.UseMvc();
            });

{"Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
 The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":
"Microsoft.IdentityModel.Tokens, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}

and If I go back to version 1.0.1 everything works well but GetProfileDataAsync does not get called

Any idea how I can resolve the issue with the new version 1.0.2? 
I have tried adding the latest version of Microsoft.IdentityModel.Tokens (5.1.2) but it didn't work.

My IdentityServer4.AccessTokenValidation version is 1.0.2

Thank you in advance
Alec

**Comment by leastprivilege** [comment]
i had that problem before as well - try cleaning your bin, obj, .vs and nuget cache.

or `git clean -xdf`

**Comment by ahodroj74** [comment]
That worked. Thank you
