### ISSUE TITLE
Ability to handle multiple accounts at once without user signing out and signing back in again

### ISSUE THREAD

**Issue by Krishna-teja** [IdentityServer/IdentityServer4#717]
We have successfully implemented idsvr4 and it's awesome. Thanks for all the hard work!. 

The users of our system could have multiple accounts and right now the only way for them to switch accounts is to logout and re-login. Is there any way that idsvr can handle multiple login sessions so that users can seamlessly switch between different accounts?

Thanks!

**Comment by leastprivilege** [comment]
"multiple logon sessions" is tricky. You can append `prompt=login` to re-show the login page instead.

**Comment by martintro** [comment]
I thought of this as well and also your solution for it @leastprivilege. But will the silent renewal of access tokens in JS clients still work then? In client nr1 after the second login.

**Comment by brockallen** [comment]
If you login to a second client app with a different identity at IdentityServer, then it's a new session and a user subject id, so the silent renew will no longer work at the first client app.

**Comment by martintro** [comment]
Yeah. What is the solution for that? Multiple sessions?

**Comment by brockallen** [comment]
We only support a single authentication cookie as of now in IdentityServer.

**Comment by martintro** [comment]
Alright, and because of that there is no possibility to have multiple "sessions" right now?

**Comment by leastprivilege** [comment]
As for now - yes.

**Comment by dmossberg** [comment]
> As for now - yes.

Has this situation changed by now, or are is it in the roadmap to support this scenario? My customer is using IdSvr4 as the corporate OIDC Authority for internal (employee) and customer facing apps,  which normally rely on different IdPs. For employees, it is problematic that they need to sign-in/sign-out with the coorporate (ADFS) credentials and the local IdP credentials when switching apps.

**Comment by leastprivilege** [comment]
no update. sorry.
