### ISSUE TITLE
Settings it up with Asp.Net Forms (question)

### ISSUE THREAD

**Issue by abomadi** [IdentityServer/IdentityServer4#718]
Hi,

i have a question that i couldn't find a direct answer for it.

i have a asp.net site with asp.net 4.5 membership provider (site1)
also IDS4 is setup (auth provider)

i want to keep the existing login on site1 as it's but also i want to make IDS to authenticate site1 users by reading and validating users directly from the DB store.

I know that i have to create my own classes on IDS to ready asp.net membership users, however if i can see an example on how to start it would be great, and one more thing how to handle the encrypted password from previous site ! taking in consideration we have the encryption method for site1

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
