### ISSUE TITLE
External Login for native mobile apps through IdentityServer4

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4#719]
I have IdentityServer4 configured for my JS clients , and I am using ResourceOwner flow for getting access_token and authenticate the user. This flow can work for both JS clients and mobile apps.

Now I want to authenticate my native mobile app clients with external providers like Facebook, Twitter etc using my IdentityServer4.

I have run the samples for IdentityServer4 using External Providers but I want to authenticate my mobile app users from native apps (android , ios) , please give me suggestion that how can I achieve that? I know that it is not possible without redirects , this is OK.

**Comment by brockallen** [comment]
You need to use a browser to redirect to IdentityServer for that.  It's just how it works.
