### ISSUE TITLE
Where is bower.json in Host project?

### ISSUE THREAD

**Issue by ateregulov** [IdentityServer/IdentityServer4#722]
My gitignore contains "/wwwroot/lib" path.

**Comment by totht91** [comment]
Yes it's missing. The /wwwroot/lib gitignore is a common usa-case.

**Comment by ateregulov** [comment]
I created pull request #723

**Comment by brockallen** [comment]
We don't have one, as our gitignore does not filter that path. If you want to use bower, then add it in your project.
