### ISSUE TITLE
Is it possible to use Identity server 4 to secure nodejs web api?

### ISSUE THREAD

**Issue by mohamed-elsabagh** [IdentityServer/IdentityServer4#724]
I am running identity server app and another web api app using dotnet core and I am securing the api using identity server and everything is perfect, I would like to use Identity server 4 to secure nodejs web api is that possible?
and if yes is there any example or library that I can use?
Thanks in advance

**Comment by brockallen** [comment]
Yes. For node.js samples, check the OpenID Connect working group's list of libraries: https://openid.net/developers/libraries/

**Comment by cosmoKenney** [comment]
I am in the same boat here. I have a production IDS4 and Web Application with dotnet core Web API running. But we have an outside developer who wants to build an Node.js api for a mobile app. I followed the link that @brockallen provided and only found node idp provider implementations.  
@mohamed-elsabagh have you found a way to secure your node api?

**Comment by mohamed-elsabagh** [comment]
Well I am not sure if this is the best answer but what you can do is build your own authentication module it should be very simple. You can get jwt decoder library and extract the bearer token from the header of the requests and then authenticate this token with the identity server application and once you find it's an authenticated token then decode it using the jwt decoder to get required info I am not on my PC but once I am back I could point some useful libraries for you. It's also worth to have look at passport node library.

**Comment by tlejmi** [comment]
yes, you can by using passport-openidconnect .  

```
    "openid": {
    "module" : "passport-openidconnect",
    "porvider" : "openid",
    "issuer" : "https://ip",
    "authorizationURL": "https://ip/connect/authorize",
    "tokenURL": "https://ip/connect/token",
    "userInfoURL": "https://ip/connect/userinfo",
    "clientID": "clientid",
    "clientSecret": "clientsecret",
    "callbackURL": "/auth/openid/callback", 
    "authPath": "/auth/openid",
    "successRedirect": "/",
    "failureRedirect": "/",
    "session": "true",
    "scope":"openid profile email"
    }
```
