### ISSUE TITLE
Problem with Microsoft.AspNetCore.Authentication.* v 1.1.0

### ISSUE THREAD

**Issue by jaider** [IdentityServer/IdentityServer4#728]
I spent all day trying to make the demo of Identity Server 4 to work, and neither HybridAndClientCredentials nor HybridAndClientCredentials was working for me and all I got was 401 response. And I finally discovered the problem. It was the latest versions (v 1.1.0) of packages in the MVC Client. Once I **downgraded the version to v1.0.0**, it works! These are the packages.  
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
I would like to know what are those breaking changes and how we can fix it. It will be great to **add this as important note in the documentation.**

Note the IdentityServer4 works fine in the v1.0.2.

**Comment by brockallen** [comment]
We don't support Microsoft's client-side libraries. If you feel the docs can be improved, we accept PRs.
