### ISSUE TITLE
EndSessionEndPoint missing

### ISSUE THREAD

**Issue by ash23** [IdentityServer/IdentityServer4#73]
Is there any plans to implement EndSessionEndpoint? It is available in EndpointOptions but the actual endpoint class does not seem to exist.

What I would like to do is simply sign out the user from the OP without needing any further confirmation from the user. The user has already clicked a "Logout" button in my Angular app which I would like to trigger an automated logout from the OP (my app still has the id token available at this point so it's not a problem including it in the request, i.e, as id_token_hint parameter).

If this endpoint has not yet been implemented is there any workaround to achieve this?

Also from http://openid.net/specs/openid-connect-session-1_0.html#RPLogout:
"At the logout endpoint, the OP SHOULD ask the End-User whether he wants to log out of the OP as well. If the End-User says "yes", then the OP MUST log out the End-User."

Would it be possible to skip this extra confirmation from the user (since the spec sais "SHOULD")?
It would be frustrating for the user to have to again confirm that he wants to logout (since he has already clicked "Logout" in my app).

**Comment by brockallen** [comment]
Yes, but not much is happening here until ASP.NET Core RC2 is out.

**Comment by totht91** [comment]
Why is the RC2 release the turning point? You can actively develop with the nightly builds, it's paintful sometimes but you can.

**Comment by brockallen** [comment]
Because we don't have infinite time or resources. If your company would like to sponsor this OSS effort, then email us.

**Comment by totht91** [comment]
understood

**Comment by Junicus** [comment]
now that rc2 has been release, any word about this endpoint?

**Comment by damienbod** [comment]
@brockallen  @leastprivilege 

Hi, just wondering if you have any plans to implement this now that RC2 has been released.

Would be great.

Greetings Damien

**Comment by brockallen** [comment]
Yes, soon.

**Comment by leastprivilege** [comment]
End session is there now. Federated signout not yet.
