### ISSUE TITLE
Using IdentityServer 

### ISSUE THREAD

**Issue by capiono** [IdentityServer/IdentityServer4#735]
I want to use IdentityServer to create an authentication services to a MVC web application and Web API. 

I want the Web API to implement the `IdentityDbContext` and IdentityServer to pulling users and identity information from the Web API. 

I have look through all your samples, still struggling on how to set this up. 

Any suggestions?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
