### ISSUE TITLE
Log the tokens generated for debugging purposes

### ISSUE THREAD

**Issue by akamud** [IdentityServer/IdentityServer4#738]
I would like to see the `access_token` generated by IS4 for debugging purposes when I activate verbose logs.

I see it never gets logged [here](https://github.com/IdentityServer/IdentityServer4/blob/e46dde73e3a47976ee40f8a9912cdbf705e50067/src/IdentityServer4/Services/DefaultTokenService.cs#L149), but sometimes it might be useful to make sure everything is working as expected.

Is there a motivation for this? Security? Tokens can be too long? Would it be ok to log them when Trace level is configured?

**Comment by leastprivilege** [comment]
@brockallen opinion?

**Comment by brockallen** [comment]
Do you have a list of the places where you'd like to see this added?

**Comment by akamud** [comment]
Would it be too bad to log it every time we enter the `CreateAccessTokenAsync` and `CreateIdentityTokenAsync`? Like in [here]?(https://github.com/IdentityServer/IdentityServer4/blob/e46dde73e3a47976ee40f8a9912cdbf705e50067/src/IdentityServer4/Services/DefaultTokenService.cs#L183)

**Comment by leastprivilege** [comment]
done on dev
