### ISSUE TITLE
ScopeClaim in v4?

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4#739]
I've just been reading

https://github.com/IdentityServer/IdentityServer3.Samples/issues/5

Is there an equivalent in v4 to include certain scopes in the id_token?

**Comment by brockallen** [comment]
https://identityserver4.readthedocs.io/en/release/reference/identity_resource.html

**Comment by daver77** [comment]
Thanks. I'm using db storage. So I have custom.profile in [IdentityResources] which has my [IdentityClaims] and I add custom.profile to [ClientScopes].

Is that right? They're not being returned

**Comment by daver77** [comment]
Ah, found [AlwaysIncludeUserClaimsInIdToken] in [Clients], setting that to true works

**Comment by ImaginaryDevelopment** [comment]
> https://identityserver4.readthedocs.io/en/release/reference/identity_resource.html

Page not found, Is it IdentityResource or ClientScope?
