### ISSUE TITLE
Implicit flow with EntityFramework core Error

### ISSUE THREAD

**Issue by AllenMaz** [IdentityServer/IdentityServer4#74]
I want to implement Scopes and Clients from EF core,but when i test implicit flow ,i got an error:

An unhandled exception occurred while processing the request.
SqlException: Invalid object name 'Consents'.

The following is my logging:

2016-04-14 11:12:51.489 +08:00 [Information] Start Authorize Request

2016-04-14 11:12:51.506 +08:00 [Information] AuthenticationScheme: "idsrv" was successfully authenticated.

2016-04-14 11:12:51.515 +08:00 [Debug] User in authorize request: name:"Admin", sub:"5d8db2b4-bd97-47d1-ba97-d9ae354ca88a"

2016-04-14 11:12:51.518 +08:00 [Information] Start authorize request protocol validation

2016-04-14 11:12:51.997 +08:00 [Information] "Authorize request validation success"
 "{
  \"ClientId\": \"padmate_mvcimplicit\",
  \"ClientName\": \"MVC Implicit\",
  \"RedirectUri\": \"http://localhost:15142/Home/CallBack\",
  \"AllowedRedirectUris\": [
    \"http://localhost:15142/Home/CallBack\"
  ],
  \"SubjectId\": \"5d8db2b4-bd97-47d1-ba97-d9ae354ca88a\",
  \"ResponseType\": \"id_token token\",
  \"ResponseMode\": \"form_post\",
  \"Flow\": \"Implicit\",
  \"RequestedScopes\": \"openid profile email roles dpcontrolapiscope\",
  \"State\": \"CfDJ8K1drB7YBJZDj0rLODLm_ulRINSOpO-Ajek9KJ78eUlK8iVZ5DnMXcr8nNbCrHdZJwyGJGHG3aZw-1tHpDhMGPNtLm_M_wW1QEnNKzJEh4bbSJR9K8ET-0nE_ABk0GyjETbewsQzS1X6d64T0OvzoSlAUx6WMbFTxRsi52bJw223jXR3Rubcu-4CRAqeaeKZ3pjG2BYFdotO0coulc9cepuhSlf_jw-HuLK7PcxIRm9YsREGHggJ7v6mu1LqL7c9A0SiZIk_x2gHddg-CPp7JJTqzsaWFCYNfTefTizenXABK-FzI1SzhY7TzfvB_-P90cJx2TJHsjJnT2s1II5UcZw4JDHf3qQvcOgeH9HVVERYj5OvKFF2m-ApgZNgeChBzg\",
  \"Nonce\": \"635962003712692754.ZGY2NDI0ZTgtMzBmYi00NmU3LTgxZWMtYTlmNGIyYzBjYzcyNzNjMWUwYTAtNDIyYi00ZTMxLTljYWEtMjYyM2NiYzUyZWM0\",
  \"SessionId\": \"76e382e86594bf87e2e35fe31ef7da3b\",
  \"Raw\": {
    \"client_id\": \"padmate_mvcimplicit\",
    \"redirect_uri\": \"http://localhost:15142/Home/CallBack\",
    \"response_type\": \"id_token token\",
    \"scope\": \"openid profile profile email roles dpcontrolapiscope\",
    \"response_mode\": \"form_post\",
    \"nonce\": \"635962003712692754.ZGY2NDI0ZTgtMzBmYi00NmU3LTgxZWMtYTlmNGIyYzBjYzcyNzNjMWUwYTAtNDIyYi00ZTMxLTljYWEtMjYyM2NiYzUyZWM0\",
    \"state\": \"CfDJ8K1drB7YBJZDj0rLODLm_ulRINSOpO-Ajek9KJ78eUlK8iVZ5DnMXcr8nNbCrHdZJwyGJGHG3aZw-1tHpDhMGPNtLm_M_wW1QEnNKzJEh4bbSJR9K8ET-0nE_ABk0GyjETbewsQzS1X6d64T0OvzoSlAUx6WMbFTxRsi52bJw223jXR3Rubcu-4CRAqeaeKZ3pjG2BYFdotO0coulc9cepuhSlf_jw-HuLK7PcxIRm9YsREGHggJ7v6mu1LqL7c9A0SiZIk_x2gHddg-CPp7JJTqzsaWFCYNfTefTizenXABK-FzI1SzhY7TzfvB_-P90cJx2TJHsjJnT2s1II5UcZw4JDHf3qQvcOgeH9HVVERYj5OvKFF2m-ApgZNgeChBzg\"
  }
}"

2016-04-14 11:12:52.057 +08:00 [Error] An unhandled exception has occurred while executing the request
System.AggregateException: 发生一个或多个错误。 ---> System.AggregateException: 发生一个或多个错误。 ---> System.AggregateException: 发生一个或多个错误。 ---> System.AggregateException: 发生一个或多个错误。 ---> System.Data.SqlClient.SqlException: Invalid object name 'Consents'.
   在 System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__167_0(Task`1 result)
   在 System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
;;;;;;;;;;;;;;
ClientConnectionId:6d373b20-ac77-4ca0-afd6-e1eba39f66f5
Error Number:208,State:1,Class:16<---
<---
<---
<---

2016-04-14 11:12:52.093 +08:00 [Information] Request finished in 0.0703ms 500 text/html; charset=utf-8

**Comment by AllenMaz** [comment]
When i use InMemoryClients ,if i set RequireConsent = true,Consent Screen will show,if i set RequireConsent = false,then no Consent Screen ,it works fine.

But when i use EF Core, if i set the RequireConsent column to true,then i get an error: "Invalid object name 'Consents'",but when i set the  RequireConsent column to false, it works fine and i get a Consent Screen from Implicit flow. Is that a bug in TwentyTwenty.IdentityServer4.EntityFramework7 ?

**Comment by leastprivilege** [comment]
We currently don't provide any EF support - please open those issues in the right repo.
