### ISSUE TITLE
Claim authorization logic

### ISSUE THREAD

**Issue by neridonk** [IdentityServer/IdentityServer4#740]
Hey this is only a little question.

So fat IdentityServer4 works fine and I really like it, but I have a lack in the logic.

My implementation is following 

1. A user logs in
2. API redicts to token endpoint
3. The ResourceOwnerPasswordValidator creates the access_token with many claims which we get from a database 

```
//like 1000 claims because every Controller Methode in my API has a auth. filter attribute
var listRoles = managerContext.Roles.Where(i=>i.username == context.UserName && active == 1 )

```
4. I get a huge access_token with over 1000 claims

**So every request to the api the Authorization hedaer holds this big access_token**

**Is this a problem or does the size of the token not matter?**

My solution against this would be an middleware in my API which does the step in 3,

**Comment by brockallen** [comment]
> I get a huge access_token with over 1000 claims

https://leastprivilege.com/2016/12/16/identity-vs-permissions/

**Comment by neridonk** [comment]
thanks I wasn't sure no iam
