### ISSUE TITLE
'System.ExecutionEngineException' when providing auth over an API within the IdentityServer4 application with a non-temporary signing credential

### ISSUE THREAD

**Issue by bendetat** [IdentityServer/IdentityServer4#741]
- [-] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem
I'm trying to require authorisation on an API controller that will live within the identity server application. Eg.

```
namespace My.Auth.Controllers
{
    [Route("api/v1/ping")]
    [Authorize]
    public class PingController : Controller
    {
        [HttpGet]
        public IActionResult Get()
        {
            return Ok("ack");
        }
    }
```

I've already set up the identity server with EF stores, ASP.NET Identity and a self-signed cert as the signing credential. I'm following http://docs.identityserver.io/en/release/quickstarts/1_client_credentials.html to add the middleware to the application, viz within `Startup.Configure()`:

```
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
{
	Authority = "http://localhost:8130",
	RequireHttpsMetadata = false
});
```

where `http://localhost:8130` is the internal address the application is running on - I imagine this causes a loopback request to the IdentityServer part of the application to authenticate the user.

When I request the API with a valid bearer token in the `authorization` header, it results in this exception (not shown in the log): `An unhandled exception of type 'System.ExecutionEngineException' occurred in System.Security.Cryptography.X509Certificates.dll`.

However if I change the signing credential from `.AddSigningCredential("CN=My-Auth")` to `.AddTemporarySigningCredential()` (as used in the quickstart documentation and other examples of this I've found) the request succeeds (and correctly fails with a 404 if the token is invalid).

### Relevant parts of the log file

```
...
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3511.5988ms 200 application/json
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:8130/.well-known/openid-configuration/jwks
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Request path /.well-known/openid-configuration/jwks matched to endpoint type Discovery
dbug: IdentityServer4.Hosting.EndpointRouter[0]
      Mapping found for endpoint: Discovery, creating handler: IdentityServer4.Endpoints.DiscoveryEndpoint
info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
      Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration/jwks
dbug: IdentityServer4.Endpoints.DiscoveryEndpoint[0]
      Start key discovery request
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 590.0719ms 200 application/json

(exception thrown at this point)
```

**Comment by leastprivilege** [comment]
It's a bug in .NET Core 1.1

https://github.com/dotnet/coreclr/issues/8148

**Comment by bendetat** [comment]
:-O Thank you very much 👍
