### ISSUE TITLE
redirect_uri # or ?

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4#742]
Hi,
We have an IdentityServer4 install with .NET Identity setup to handle the future SSO requirements of our customer websites. I've setup test API's and relying parties using WebForms, MVC5 and MVC6 and they all work fine. 

One of our development partners is developing a website using OutSystems (Java) and they have come across an issue after the Identity Provider has taken username/password and sent them back to the redirect_uri.

http://localhost:8081/CustomSSO/index.xhtml#code=c38b40ae2db5e84e1d6............

The URL is returned with a # which means they can't get the querystring values easily, is there an option anywhere to change this to ?

**Comment by brockallen** [comment]
Values after the hash are only visible to client-side JS, so it's strange that they're sending back a code there (since code is designed for server-side scenarios, but can also be used by mobile/native apps). Anyway, sounds like a tech support question for them.

**Comment by daver77** [comment]
I found this post which has a similar issue, I think they just need to change to `response_mode=form_post`
https://github.com/IdentityServer/IdentityServer3/issues/2710
