### ISSUE TITLE
 .AddSigningCredential(certificate) is not working 

### ISSUE THREAD

**Issue by Waqaar-Rasool** [IdentityServer/IdentityServer4#743]
When I was using ID Server 4 RC 3,  .AddSigningCredential(certificate) code was working fine on Windows Server 2012 R2 but after upgrade to ID Server 4 and .NET Core 1.0 to .NET Core 1.1, the .AddSigningCredential(certificate) is not working anymore.
But this code  .AddTemporarySigningCredential() is working fine in every condition. 

But when I use this .AddSigningCredential(certificate), I start getting Bad Gateway issue for new controller which I have written. On class level I used [Authorize(Policy = "CRUD")].

Any help/pointers will be appreciated.

**Comment by brockallen** [comment]
In what way is it not working?

**Comment by Waqaar-Rasool** [comment]
I created one controller with two action methods. The controller is decorated with authorize attribute. From fiddler i invoke one of the method with bearer token. But it says bad gateway. Getting token works fine from id server.

**Comment by leastprivilege** [comment]
maybe you are running into this:

https://github.com/dotnet/coreclr/issues/8148

**Comment by Waqaar-Rasool** [comment]
I don't think so, because I am not getting any kind of exception in log and plus tried with below code.

            var fail = true;
            X509Certificate2 cert;
            if (!fail)
            {
                cert = new X509Certificate2(@".\demo-svc.pfx", "demo-svc");
                cert = new X509Certificate2(cert.RawData);
                Console.WriteLine(cert.Thumbprint);
            }

            cert = FindInStore("demo-svc");
            Console.WriteLine(cert.Thumbprint);

            **var credential = new SigningCredentials(new X509SecurityKey(cert), "RS256");**       

The last line is copied from ID Server code and it is not throwing any kind of exception. So I think problem is somewhere else.

**Comment by leastprivilege** [comment]
I had the above mentioned problem - the exception was happening *at some point* and since the whole CLR broke down, there were also no logs.

Closing for now - feel free to re-open if it needs further discussion.

**Comment by Waqaar-Rasool** [comment]
Yes, during setup, the code don't break (X509Certificate2). But once it receive request, it started giving the Bad Gateway issue. To overcome this we have to create a object of X509Certificate2 as mentioned in your pointers. You can also mentioned this in some documentation imho.
