### ISSUE TITLE
Authorization code cannot be found in the store

### ISSUE THREAD

**Issue by kglessner** [IdentityServer/IdentityServer4#744]
We currently have Identity Server and an MVC application hosted in Azure using the HybridClientCredentials flow. We are occasionally getting a 500 response from the POST to signin-oidc after logging in.  Looking at the logs it seems that when the MVC app is trying to swap the authorization code for the access token, the request to the token endpoint is returning a 400 Bad Request.  What is strange is that this seems to be random.  Sometimes it works, sometimes we get this error.

It sounds similar to this issue because we are using InMemory storage, but we are only running one instance of Identity Server
https://github.com/IdentityServer/IdentityServer4/issues/340

Also this seems to work 100% of the time running on a local environment. It's only occurring once we deploy to Azure.  Do you have any ideas that might point us in the right direction?

**The error logged by our MVC app.**

2017-01-24 18:03:51.875 +00:00 [Debug] Updating configuration
2017-01-24 18:03:51.891 +00:00 [Debug] Received 'id_token'
2017-01-24 18:03:52.266 +00:00 [Debug] Redeeming code for tokens.
2017-01-24 18:03:52.562 +00:00 [Error] Exception occurred while processing message.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<RedeemAuthorizationCodeAsync>d__21.MoveNext()   
   
**The error logged by Identity Server.**

2017-01-24 18:07:39.808 +00:00 [Debug] Start token request validation
2017-01-24 18:07:39.838 +00:00 [Debug] Start validation of authorization code token request
2017-01-24 18:07:39.851 +00:00 [Error] Authorization code cannot be found in the store: "4a201bc574d46cd1ad4a45beb643be5b152a6529d16769b96d042cda726a9939"
2017-01-24 18:07:39.868 +00:00 [Error] "{
  \"ClientId\": \"ContentSiteAdminMvc\",
  \"GrantType\": \"authorization_code\",
  \"AuthorizationCode\": \"4a201bc574d46cd1ad4a45beb643be5b152a6529d16769b96d042cda726a9939\",
  \"Raw\": {
    \"client_id\": \"ContentSiteAdminMvc\",
    \"client_secret\": \"SomeSecretString\",
    \"code\": \"4a201bc574d46cd1ad4a45beb643be5b152a6529d16769b96d042cda726a9939\",
    \"grant_type\": \"authorization_code\",
    \"redirect_uri\": \"https://somewebsite/signin-oidc\"
  }
}"

**Comment by leastprivilege** [comment]
any more infos?

**Comment by Jenan** [comment]
Same error message: `Authorization code cannot be found in the store`

IdServer settings:
```
services.AddIdentityServer()
                .AddTemporarySigningCredential()
                .AddInMemoryIdentityResources(Config.GetIdentityResources())
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddInMemoryClients(Config.GetClients())
		.AddInMemoryCaching()
		.AddInMemoryPersistedGrants()
                .AddTestUsers(Config.GetUsers());
```
I've add the following code:

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
			{
				AuthenticationScheme = "oidc",
				SignInScheme = "Cookies",

				Authority = "http://localhost:5000",
				RequireHttpsMetadata = false,

				ClientId = "mvc",
				ClientSecret = "secret",

				ResponseType = "code id_token",
				Scope = { "api1", "offline_access" },

				GetClaimsFromUserInfoEndpoint = false,
				SaveTokens = true,

				Events = new OpenIdConnectEvents()
				{
					OnAuthorizationCodeReceived = async n => await OnAuthorizationCodeReceivedSettings(n)
				}

			});
```

Especially this part:
```
private async Task OnAuthorizationCodeReceivedSettings(AuthorizationCodeReceivedContext n)
		{
			var disco = await DiscoveryClient.GetAsync("http://localhost:5000");
			if (disco.IsError) throw new Exception(disco.Error);

			var tokenClient = new TokenClient(disco.TokenEndpoint, "mvc", "secret");
			var refreshResponse =
				await tokenClient.RequestAuthorizationCodeAsync(n.ProtocolMessage.Code, "http://localhost:5002/signin-oidc");

			var expiresIn = refreshResponse.ExpiresIn;

			n.Properties.ExpiresUtc = DateTime.UtcNow.AddSeconds(expiresIn);
			n.Properties.IsPersistent = true;
			n.Properties.AllowRefresh = false;
			n.Properties.IssuedUtc = DateTimeOffset.UtcNow;
		}
```

**Comment by Jenan** [comment]
Same error with EntityFramework - database store:

```
[09:37:39 ERR] IdentityServer4.Validation.TokenRequestValidator
Authorization code cannot be found in the store: 573e1b3e7afb554a91ae7e0991577ed
c1fd0c8dda601f0b14a0c380ba1c09906

[09:37:39 ERR] IdentityServer4.Validation.TokenRequestValidator
{
  "ClientId": "mvc",
  "ClientName": "MVC Hybrid",
  "GrantType": "authorization_code",
  "AuthorizationCode": "573e1b3e7afb554a91ae7e0991577edc1fd0c8dda601f0b14a0c380b
a1c09906",
  "Raw": {
    "client_id": "mvc",
    "client_secret": "secret",
    "code": "573e1b3e7afb554a91ae7e0991577edc1fd0c8dda601f0b14a0c380ba1c09906",
    "grant_type": "authorization_code",
    "redirect_uri": "http://localhost:5002/signin-oidc"
  }
}

[09:37:39 VRB] IdentityServer4.Hosting.IdentityServerMiddleware
Invoking result: IdentityServer4.Endpoints.Results.TokenErrorResult
```

**Comment by kglessner** [comment]
In my case, we had more than one instance of our MVC app running in Azure.  Switching this to a single instance seemed to resolve the issue for now.

**Comment by Jenan** [comment]
I have only one instance of MVC app.

**Comment by brockallen** [comment]
> services.AddIdentityServer()
>                .AddTemporarySigningCredential()
>                .AddInMemoryIdentityResources(Config.GetIdentityResources())
>                .AddInMemoryApiResources(Config.GetApiResources())
>                .AddInMemoryClients(Config.GetClients())
>                .AddTestUsers(Config.GetUsers());

You need to configure something for the persisted grants store: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Stores/IPersistedGrantStore.cs

This is one implementation: https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Stores/PersistedGrantStore.cs

**Comment by Jenan** [comment]
Yes, I have tried the InMemory and EntityFramework version of storing the persistant grants and I get the some error both.

**Comment by Jenan** [comment]
I have tried debug more and I've discovered that here:

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
			{
				.......
				Events = new OpenIdConnectEvents()
				{
					OnAuthorizationCodeReceived = async n => await OnAuthorizationCodeReceivedSettings(n)
				}
			});

private async Task OnAuthorizationCodeReceivedSettings(AuthorizationCodeReceivedContext n)
		{
			var disco = await DiscoveryClient.GetAsync("http://localhost:5000");
			if (disco.IsError) throw new Exception(disco.Error);

			var tokenClient = new TokenClient(disco.TokenEndpoint, "mvc", "secret");
			var refreshResponse = await tokenClient.RequestAuthorizationCodeAsync(n.ProtocolMessage.Code, "http://localhost:5002/signin-oidc");
			var expiresIn = refreshResponse.ExpiresIn;
			n.Properties.ExpiresUtc = DateTime.UtcNow.AddSeconds(expiresIn);
			n.Properties.IsPersistent = true;
			n.Properties.AllowRefresh = false;
			n.Properties.IssuedUtc = DateTimeOffset.UtcNow;
		}
```

If I create the request using the code `tokenClient.RequestAuthorizationCodeAsync(n.ProtocolMessage.Code, "..")`; the `authorization_code` is removed from database at this time.

How can I modify that? :)

**Comment by leastprivilege** [comment]
This is by design - authorization codes are one time only tokens.

You don't need to do that manually in asp.net core - it is done already by the middleware.

**Comment by Jenan** [comment]
You are right. I've tried this because I want to set the cookie expiration time according the access token expiration time not according the id_token.

Any idea for doing that? :)

**Comment by Jenan** [comment]
I solved this issue like this:

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
			{
				....
				GetClaimsFromUserInfoEndpoint = false,
				SaveTokens = true,
				UseTokenLifetime = false,

				Events = new OpenIdConnectEvents()
				{
					OnAuthorizationCodeReceived = async n => await OnAuthorizationCodeReceivedSettings(n),
					OnTicketReceived = n => OnTicketReceived(n)
				}

			});

private Task OnTicketReceived(TicketReceivedContext n)
		{
			var accessTokenExpiresAt = n.Properties.Items[".Token.expires_at"];
			n.Properties.ExpiresUtc = DateTimeOffset.Parse(accessTokenExpiresAt);

			return Task.FromResult(0);
		}
```

Thank you for your help. :)
