### ISSUE TITLE
Update logout implementations

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#746]
http://self-issued.info/?p=1633

**Comment by leastprivilege** [comment]
Wait til specs are final

**Comment by leastprivilege** [comment]
they are final now
http://self-issued.info/?p=1668

**Comment by leastprivilege** [comment]
* update front channel
* implement back channel

**Comment by brockallen** [comment]
No changes needed for the session management spec

**Comment by brockallen** [comment]
Renamed LogoutUri (et al) to FrontChannelLogoutUri

**Comment by brockallen** [comment]
I might like the idea of reworking the session id and client list interfaces as part of this: https://github.com/IdentityServer/IdentityServer4/issues/846

**Comment by brockallen** [comment]
Hmm... some issues with back-channel. The spec says that the sub is optional, and the place where we do the end session callback we no longer have the sub. I'm thinking this might mean we want some rework, as I hinted at above. We should discuss.
