### ISSUE TITLE
IdentityServer 4 in ASP.Net Web Application (.Net Framework 4.6.2)?

### ISSUE THREAD

**Issue by boopathyThangamani** [IdentityServer/IdentityServer4#750]
Is it possible to do the following

1. Use IdentityServer 4 in Asp.Net Web Application(.Net Framework 4.6.2) instead of (.NET Core)
2. Im using Owin  and found that  there is no extension method for IAppBuilder.UseIdentityServer

**Comment by leastprivilege** [comment]
https://leastprivilege.com/2017/01/15/platforms-where-you-can-run-identityserver4/

**Comment by seattleravin** [comment]
IdentityServer4 is an OpenID Connect and OAuth 2.0 framework for ASP.NET Core 2. It only works with Asp.Net core 2.0. It doesNOT work with old ASP.net like Owin/KATANA.

**Comment by brockallen** [comment]
IdentityServer3 was designed to use in a OWIN/Katana host.
