### ISSUE TITLE
Generating and Validating token in a Azure Web Farm scenario

### ISSUE THREAD

**Issue by vinaykumar0787** [IdentityServer/IdentityServer4#751]
I am new to Security and IdentityServer aspects, though I have built applications using Angular/ASP.NET and Azure. 
In IdentityServer4 how would the generated token for a Angular2 app client gets validated from different servers where the IdentityServer is deployed(say in Azure). 
Does the pfx file takes care of it? Or is there anything that I need to take care of?
@brockallen

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
