### ISSUE TITLE
Username or password too long?

### ISSUE THREAD

**Issue by snowjim** [IdentityServer/IdentityServer4#752]
Hi,

I have a working IdentityServer with a IResourceOwnerPasswordValidator that grant username & password.

A external login provides me with a UserId(mapped in database) and a token, this token needs to be validated on the service.

To make a easy solution I thought to use the same class as for username & password and then have it switched on logintyp(userpassword/external).

So the username is id and the password is the token. The problem is that when sending this to the IdentityServer I get the following : 

```
fail: IdentityServer4.Validation.TokenRequestValidator[0]
      Username or password too long
fail: IdentityServer4.Validation.TokenRequestValidator[0]
      {
        "ClientId": "ro.My",
        "ClientName": "Resource owner My client",
        "GrantType": "password",
        "Scopes": "offline_access My.wcf",
        "Raw": {
          "grant_type": "password",
          "username": "4JFM",
          "password": "***REDACTED***"
        }
      }
```
Is there any way to change the length or should I implement this an other way? I have looked at the IExtensionGrantValidator but its not clear how to provide the id and token to the ValidateAsync method?

BestRegards

**Comment by snowjim** [comment]
This is solved by using the IExtensionGrantValidator. Its explained here : http://docs.identityserver.io/en/release/topics/extension_grants.html

**Comment by shaikatz** [comment]
I had the same issue, you can do that:
```
            var builder = services.AddIdentityServer(options =>
            {
                options.InputLengthRestrictions.Password = int.MaxValue;
                options.InputLengthRestrictions.UserName = int.MaxValue;
            });
```
