### ISSUE TITLE
Deploying particular auth scenario

### ISSUE THREAD

**Issue by FacundoGFlores** [IdentityServer/IdentityServer4#755]
I have an SPA registered in my azure. Users can login via ADAL usign adal.js. Now I need to integrate my application with others. So, for example app external B wants to fill a form from my app A. The thing is, app A is using microsoft accounts for login, while app B is using its own accounts stored in its DB. The process would be something like:

1. user X from B clicks on "fill form"
2. new navigation window is opened with app A
3. app A authorize user X to use "fill form" (wihout any login, just using the user X or any other info such as a token)
4. app A gets user X info from app B (from an API)
5. app A shows the "fill form" to user X
6. user X fills the form and submit it
7. "fill form" is saved on app A DB.

Has anyone lead with this kind of scenario? 
Would implementing Identity Server intead of adal.js help me?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
