### ISSUE TITLE
Authentication support for prompt=none and id_token_hint

### ISSUE THREAD

**Issue by joshpearce** [IdentityServer/IdentityServer4#757]
- [x] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem
Here is our situation: 

- We have a desktop application which can render a login form in a web browser control. 
- After the user logs in to the STS, they are redirected to a page that loads the access and identity tokens into JavaScript variables. 
- The desktop application can then read these tokens and make requests to services.
- Later, the user wants to open a Web UI in a full browser.
- We would like to pass the identity token in the URL, and bypass the login screen

Now, I realize there are several missing pieces that are not part of Identity Server:
- The web UI's OpenID Connect middleware would likely not (out of the box) take the ID Token and then change the STS authentication URL to include prompt=none and id_token_hint. We could work around that.
- The Identity Server, by default, I believe just stores logged-in users in cookies, so it would have no idea this user had recently logged in, and have no knowledge of it's identity token. Perhaps there is a Identity Server provider we can write to store session in a DB to solve this.

Perhaps there is another way to handle this flow...

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
You should read the "native apps" spec - and use the system browser for both login and other web UI.

https://tools.ietf.org/wg/oauth/draft-ietf-oauth-native-apps/

this library can help you with that:
https://github.com/IdentityModel/IdentityModel.OidcClient2

**Comment by joshpearce** [comment]
@leastprivilege, Thank you for that suggestion. From my research, I can expect us to encounter many difficulties (sharing cookies) with that approach when using IE, and it is likely impossible with Chrome.

Does the OpenID Connect spec intend for prompt=none combined with id_token_hint to be a method for continuing a current identity session? It's unclear to me whether that is the case.

**Comment by joshpearce** [comment]
One strategy I had not considered, and that I believe is used by password managers, is the loopback interface redirect mentioned in the spec you referenced.

https://tools.ietf.org/html/draft-ietf-oauth-native-apps-07#appendix-B.3

**Comment by leastprivilege** [comment]
yep - which is a possible approach with OidcClient - check the "ConsoleWithBrowser" sample in the repo.

**Comment by joshpearce** [comment]
Thanks, but I can't find anything by the name, ConsoleWithBrowser.

**Comment by leastprivilege** [comment]
lmgtfy ;)

https://github.com/IdentityModel/IdentityModel.OidcClient2/tree/dev/clients/ConsoleClientWithBrowser
