### ISSUE TITLE
Extend LocalAuthenticationContext

### ISSUE THREAD

**Issue by avoxm** [IdentityServer/IdentityServer4#76]
To login a user aside from username and password I need additional parameter like company id.
So I have decided to make a custom login service and implement AuthenticateLocalAsync. However the problem is that LocalAuthenticationContext does not allow to pass custom parameters. 
So is there a way to pass additional data to AuthenticateLocalAsync ?

**Comment by leastprivilege** [comment]
There is no AuthenticateLocalAsync anymore. Do whatever you need to authenticate a user - but you do it yourself.

**Comment by avoxm** [comment]
Interesting. Could you please point me to the direction where to look for this. What should be used instead of AuthenticateLocalAsync now ?

**Comment by leastprivilege** [comment]
Just have a look at the host project and follow the code path on the login page.

**Comment by totht91** [comment]
Am I right that in IdentityServer4 the UI is completely decoupled from the library, and we always need copy-paste from the sample project?

**Comment by leastprivilege** [comment]
You are right about the decoupling - but our plan is to provide the standard UI as a nuget package.

**Comment by avoxm** [comment]
Thanks @leastprivilege it looks like this approach simplifies the integration a lot. Am I right to conclude that IdentityServer4 doesn't really care about how you validate the credentials and what is the database structure. As long as you populate claims and pass it in ClaimsPrincipal it will know all it needs to know.

**Comment by leastprivilege** [comment]
Yes you are right.

**Comment by Haleni888** [comment]
Could you please elaborate on how the custom parameter (e.g.: company-id) is propagated from the client to the login page?
