### ISSUE TITLE
Allow wildcarding on Client AllowCorsOrigins

### ISSUE THREAD

**Issue by francisspor** [IdentityServer/IdentityServer4#760]
- [X] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem
We have a javascript OIDC client potentially running on each of our subdomains (site1.test.com, site2.test.com, etc), and our identity service is at identity.test.com. We do not control our subdomain names, since they are customer generated, and would like to match a pattern (*.test.com) so that we can restrict that Client to that TLD.

It looks like all that would be required is changing in InMemoryCorsPolicyService:
`        public Task<bool> IsOriginAllowedAsync(string origin)
        {
            var query =
                from client in _clients
                from url in client.AllowedCorsOrigins
                select url.GetOrigin();

            var result = query.Contains(origin, StringComparer.OrdinalIgnoreCase);

            if (result)
            {
                _logger.LogDebug("Client list checked and origin: {0} is allowed", origin);
            }
            else
            {
                _logger.LogDebug("Client list checked and origin: {0} is not allowed", origin);
            }
            
            return Task.FromResult(result);
        }`
to use a regex match, instead of a Contains.  This would allow wider hosting, be closer to the wild carded standards, and

**Comment by brockallen** [comment]
You can always implement the cors policy service to override this behavior.

**Comment by francisspor** [comment]
That's a great idea.  I'll take a swing at that.  Thanks.
