### ISSUE TITLE
ClientSessions cookie deleteon

### ISSUE THREAD

**Issue by sergik** [IdentityServer/IdentityServer4#764]
- [x] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)
 

### Issue / Steps to reproduce the problem
We are using Identity Server v4 and faced some issue with ClientSessions cookie. In our case they didn't clear on logout so many times login/logout cause cookie to long problem. I looked into the code of Identity Server and some samples and looks like this cookies stores client ids of the application user used. And in samples everything works correct because logout view renders IFrame with SignOutIFrameUrl refers to the connect/endsession/callback which finally clear this cookies. In our scenario we did not want show some pages on Identity Server side after logout we want to navigate back to application automatically. 

- Could you please explain what for this cookies used? 
- Why logged out goes in 2 steps?
- Can I just clear this cookies manually during the logout calling IClientSessionService.RemoveCookie and then redirect back to application?

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
> In our scenario we did not want show some pages on Identity Server side after logout we want to navigate back to application automatically.

Well, then you're skipping the step that cleans up at signout.
