### ISSUE TITLE
IdentityServer4 and ADFS 4.0

### ISSUE THREAD

**Issue by windischb** [IdentityServer/IdentityServer4#765]
Hi!

I have configured my IdentityServer to use ADFS from Windows Server 2016 with "app.UseOpenIdConnectAuthentication" 

After entering my credentials on the ADFS Site i'll be always redirected to "/account/login".
I can't figure out if this is a Setting on Identityserver or on ADFS Site.

Any Ideas?
Br
Bernhard

**Comment by leastprivilege** [comment]
I just added my ADFS to the IS4 host - check the latest on dev.

All I needed to do was to add an "app group" and point it to the "signin-adfs" callback address.

**Comment by leastprivilege** [comment]
closing for now - feel free to re-open if it needs further discussion.

**Comment by gcardozoj** [comment]
Hi! where can I found an example of that configuration: use ADFS as an External Identity provider for IdSrv4? In another post I read this: "You have to setup IdSrv in ADFS as a relying party, and ADFS in IdSrv as an identity provider" but I dont know how can I do that.

In documentation I saw it may be done using Oidc: ".AddOpenIdConnect("adfs", "ADFS", options =>{...});"

but what is the configuration I need to do? Is the same for connecting to Azure AD, only changing the authority? I made the next configuration for Azure AD:
.AddOpenIdConnect("AAD", "Employees", options =>
                {
                    options.SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme;
                    options.SignOutScheme = IdentityServerConstants.SignoutScheme;
                    options.Authority = "https://login.microsoftonline.com/common";
                    options.ClientId = "<GUID for configured app in azure ad - apps>";
                    options.Scope.Add("openid");
                    options.Scope.Add("profile");
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateIssuer = false
                    };
                    options.GetClaimsFromUserInfoEndpoint = true;
                });

Thanks in advance.
