### ISSUE TITLE
Error: SqlException: Invalid object name 'Clients' in Identity Server 4 Project

### ISSUE THREAD

**Issue by gauravawr** [IdentityServer/IdentityServer4#767]
I would like to connect Identity Server to the Sql Server in my Asp.net core AuthServer project. But I am getting the error in the InitlizeDatabase(app) step as shown in the image below.

![identityserver-error](https://cloud.githubusercontent.com/assets/17614830/22527311/f9965598-e8ce-11e6-9409-eb86b02585f2.png)

**Comment by brockallen** [comment]
Does Migrate not create the DB for you?

**Comment by EdwardBlair** [comment]
Did you [create the initial migrations](https://github.com/IdentityServer/IdentityServer4/blob/dev/docs/quickstarts/8_entity_framework.rst#adding-migrations)?

**Comment by gauravawr** [comment]
When I do "Add-Migration first" then comes the "Build Failed" Error. But I can run the project, if the comment out the  InitializeDatabase(app) line, without error. 

As the migration command is failing, so the migrations did not occur therefor the migrations folder is not created.

I have attached the config file as below:

![identityserver-error-config](https://cloud.githubusercontent.com/assets/17614830/22564231/0ffcf688-e984-11e6-9134-ad1651c9d214.png)

**Comment by gauravawr** [comment]
It was the EF version issue.

When I used the ef and the ef tool version as given in the documentation and it worked :)

 So my code works with the version below:
"Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
