### ISSUE TITLE
Using AddValidationKeys

### ISSUE THREAD

**Issue by muffadal53** [IdentityServer/IdentityServer4#770]
Hi,

Along with AddSigningCredential if I use AddValidationKeys to add additional validation keys to validate access token then, will it clear the security key added by AddSigningCredential as calling AddValidationKeys method creates new singleton instance of DefaultValidationKeysStore with validation keys.

Thanks.

**Comment by leastprivilege** [comment]
No it won't. Did you run into a problem here?

**Comment by muffadal53** [comment]
Actually, I haven't used it yet but I got this query while looking at IdentityServer code on how singleton of DefaultValidationKeysStore works.

**Comment by leastprivilege** [comment]
The DI system allows to register multiple instances of the same type.

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultKeyMaterialService.cs

**Comment by muffadal53** [comment]
Thanks for the clarification. Can I use AddValidationKeys method to add KeyId, which I have got from wellknown endpoint of other IdentityServer using DiscoveryClient.

**Comment by leastprivilege** [comment]
you can add a key - yes.

**Comment by muffadal53** [comment]
ok. So I can create instance of RsaSecurityKey and assign KeyId and pass this security key to AddValidationKeys method.

**Comment by leastprivilege** [comment]
yes - that works.

**Comment by muffadal53** [comment]
Hi,

If order to call "AddValidationKeys" method to add keyId issued by other Identity sever, If I create DiscoveryClient object by passing authority value as url of other identity server e.g. "https://Identitysvr2:44333/IdentityServer4"
and call GetAsync() method to get JsonWebKey I get following error. Any idea regarding below error.

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()

Thanks.
