### ISSUE TITLE
Expiring token with JS Client

### ISSUE THREAD

**Issue by apacherose** [IdentityServer/IdentityServer4#771]
Hello,
I am trying to setup js client to the identity server. 
I've read the docs, downloaded and successfully run one of the sample quickstart projects: 7_JavaScriptClient.

One thing I am confused about: how should I correctly handle the token expiration?
From the "Grant Types" docs I understand the "Implicit" grant type is suitable for such JS Clients, **but** refresh tokens are not supported.
Should I create a handler for **accessTokenExpiring** event and manually handler token re-creation?
Or
I should create my UserManager instance in js with settings object that is configured with silent_redirect_uri and automaticSilentRenew props (although refresh tokens are not supported in implicit flow)?

Thanks in advance!

**Comment by brockallen** [comment]
The oidc-client library already has some support for handling expiring access tokens. Check the wiki/docs and samples in that repo, and there's also a sample in our repos here too.

**Comment by apacherose** [comment]
Thank you, Brock.
Yeah, I've followed wiki and docs of the oidc-client repo, and what I've found to be the missing config was that I had to add additional string for the "silent" url in the RedirectUris prop in the config of my js client on the Identity Server. Otherwise, I always get **unauthorized_client** while rendering the iframe.

```
// code missed for brevity
// ...
    RedirectUris = { "http://localhost:5003/callback.html", "http://localhost:5003/silent.html" },
// ..
```
Please, confirm that this is the correct way, before I close the thread.

**Comment by brockallen** [comment]
Sorry, I missed the question. Yes, you need to have all redirect URIs configured in IdentityServer, as you have done.

**Comment by apacherose** [comment]
Thank you, Brock.
