### ISSUE TITLE
Invalidate Token problem

### ISSUE THREAD

**Issue by ahodroj74** [IdentityServer/IdentityServer4#773]
I am using Identity Server 4 1.1.0
I am trying to invalidate a Token so it can no longer access my API resource.

My client config is set to use Reference tokens. 
So calling the revocation endpoint using Postman keeps returning 200 whether 
I use a valid reference token or NOT... 

According to the docs i got:

In headers:
Content-Type    application/x-www-form-urlencoded
Authorization    Basic c3ZhcHAxMDAxOnNlY3JldA==     (my client id and client secret)

In body:
token                      'my reference token'
token_type_hint      access_token

My question is: 
How do I invalidate an access token so It can no longer access my API resource?
and can I invalidate a JWT access token instead of a Reference token type?

I would like to do that using a simple POST request using Postman.

Thank you in advance
Regards,

**Comment by brockallen** [comment]
Check the logs

**Comment by leastprivilege** [comment]
You cannot invalidate JWTs - only reference/refresh tokens

**Comment by ahodroj74** [comment]
As mentioned, I am using Reference token..
Why do I keep getting 200 even when an invalid token is passed to the revocation end point??

**Comment by brockallen** [comment]
IIRC because the spec says to
