### ISSUE TITLE
Using Structuremap throws Unknown client or not enabled

### ISSUE THREAD

**Issue by beersky** [IdentityServer/IdentityServer4#776]
Hi,
Any pointers or suggestions are most welcome. Thanks!

### Issue / Steps to reproduce the problem
I'm trying to use Structuremap as the DI container with ID4 and the Implicit flow. I'm trying this as simple as I can but I can't seem to get it to work. As soon as I add the following code it stops to work. If I skip the structuremap everything works fine.

```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
            services.AddMvc();
            services.AddIdentityServer()
                .AddTemporarySigningCredential()
                .AddInMemoryClients(TestData.TestClients.GetAll())
                .AddInMemoryIdentityResources(TestData.TestIdentityResources.GetAll())
                .AddTestUsers(TestData.TestUsers.GetAll());
            
            var container = new Container();
            container.Populate(services);
            return container.GetInstance<IServiceProvider>();
}
```

### Relevant parts of the log file
```
fail: IdentityServer4.Validation.AuthorizeRequestValidator[0]
     Unknown client or not enabled: partner
```

**Comment by leastprivilege** [comment]
Then you should probably take this to the StructureMap repo. We are using the ASP.NET Core ID abstraction only.

**Comment by beersky** [comment]
Well the Structuremap things work just fine also if I don't want to use the implicit flow with ID4 also. So there seems to be something that goes wrong with AddInMemoryClients and Structuremap.

I was of the understanding that it shouldn't matter what DI I use because you are using the ASP.NET Core ID abstraction.

Well thanks anyway. Have a great day.

**Comment by leastprivilege** [comment]
Well - check our source code. We are just calling the ASP.NET Core primitives. 

Maybe StructureMap is not 100% compatible.

**Comment by nukec** [comment]
same problem here @beersky did you resolve this issue with structuremap?
