### ISSUE TITLE
Extended Asp.Net Identity

### ISSUE THREAD

**Issue by dpedrelli** [IdentityServer/IdentityServer4#779]
- [ X] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem
I extended several of the Asp.Net Core Identity classes:  IdentityUser, IdentityRole, SignInManager, UserManager, and UserStore.  Not only do I have custom properties on user and role, but I support password expiration and maintain previous passwords and I have custom sign-in methods.

.AddAspNetIdentity<ApplicationUser>() seems to register my ApplicationUser class.  I added .AddAspNetIdentity<ApplicationSignInManager>().  My ApplicationSignInManager class is instantiated; however, IdentityServer4 does not call my overridden PasswordSignInAsync() method.

I would like to be able to register all of my custom, Identity classes and utilize their overridden methods, rather than the base methods.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
> IdentityServer4 does not call my overridden PasswordSignInAsync() method

In what scenario are you expecting it to be called? From the login page? Or another workflow?

**Comment by dpedrelli** [comment]
Yes, as part of the default login process, from Account.Login().

In my standard, MVC app, I am able to register my classes and override the default ones.  When a user logs in, I check for an expired password, and redirect the user to change the password.  There are some other properties that I check to see if the user may access the system.  I have custom columns in the dbo.AspNetUsers table that are stored as claims and return as custom properties in the ApplicationUser class.  As part of the password expiration, I stored old passwords, to ensure that they are not reused.  I even extended IdentityRole to ApplicationRole, with custom properties.

            services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();
            // Add custom properties as claims and return the claims as class properties.
            services.AddScoped<IUserClaimsPrincipalFactory<ApplicationUser>, ApplicationClaimsPrincipalFactory>();
            // Add custom SignInManager to check for expired passwords and limit IP addresses.
            services.AddScoped<SignInManager<ApplicationUser>, ApplicationSignInManager>();
            // Add custom UserManager to override PasswordChange() & PasswordReset().
            services.AddScoped<UserManager<ApplicationUser>, ApplicationUserManager>();
            // Add custom UserStore to store user previous passwords.
            services.AddScoped<IUserStore<ApplicationUser>, ApplicationUserStore>();

**Comment by brockallen** [comment]
> Yes, as part of the default login process, from Account.Login().

So then debug on your login page why your APIs aren't being called. The UI is complete under your control.

**Comment by dpedrelli** [comment]
Just to confirm, are you saying that I should be able to register my own Identity classes, in the IdentityServer startup.cs, with services.AddIdentityServer()?

Let me clarify, I have not changed the default code.  I am trying to migrate an MVC app from using Identity to IdentityServer4.  In my existing, MVC app, I am registering the above classes in DI, and they work fine.

In IdentityServer startup.cs, I added
            services.AddIdentityServer()
                .AddTemporarySigningCredential()
                .AddInMemoryIdentityResources(Resources.GetIdentityResources())
                .AddInMemoryApiResources(Resources.GetApiResources())
                .AddInMemoryClients(Clients.Get())
                .AddAspNetIdentity<ApplicationUser>()
                .AddAspNetIdentity<ApplicationRole>()
                .AddAspNetIdentity<ApplicationUserManager>()
                .AddAspNetIdentity<ApplicationUserStore>()
                .AddAspNetIdentity<ApplicationSignInManager>();

When I tried this before, I traced the code and IdentityServer used the default SigninManager, rather than my registered class.  

I just tried it again and if I registers any of the Identity classes with IdentityServer4, other than ApplicationUser, I get an error:
Unhandled exception: System.InvalidOperationException: Unable to resovle server for type 'Microsoft.AspNetCore.Identity.UserManager`1[ResolveROI.Identity.Models.ApplicationUserStore]' while attempting to activate IdentityServer4.AspnetIdentity.ResourceOwnerPasswordValidator`1[ResolveROI.IdentityModels.ApplicationUserStore]'.

I have been making changes trying to figure-out what I am doing.  I may have changed a setting that is leading to this error.

**Comment by dpedrelli** [comment]
Okay that was largely my stupidity.  Instead of making the separate services.AddScoped registrations, I was including all of my Identity classes in the services.AddIdentityServer() call.  I traced the code and it does instantiate my own ApplicationSignInManager.  However, it does not call my overridden PasswordSignInAsync() method.  Is IdentityServer forcing it to call the base method?

**Comment by brockallen** [comment]
Did you follow the quickstart for ASP.NET Identity 3? https://identityserver4.readthedocs.io/en/release/quickstarts/6_aspnet_identity.html

**Comment by dpedrelli** [comment]
For testing purposes, I downloaded the IdentityServer4.Samples, from this site, and I am running the Quickstarts\6_AspNetIdentity\src\IdentityServerWithAspNetIdentity project.  Rather than create a new project, I copied the sample project to a new solution and added a project for the WinForms client.

I think I found why base.PasswordSignInAsync() is being called rather than my classes PasswordSignInAsync() method.  I overloaded the method and I am injecting an HttpContext.

public async virtual Task<ApplicationSignInResult> PasswordSignInAsync(string userName, string password, bool isPersistent, bool lockoutOnFailure, HttpContext httpContext)

In my existing MVC app, this works fine.  

I tried this with the Quick Start Identity project.

If I subclass SignInManager and override PasswordSignInAsync

        public override async Task<SignInResult> PasswordSignInAsync(string userName, string password, bool isPersistent, bool lockoutOnFailure)
        {
            return await base.PasswordSignInAsync(userName, password, isPersistent, lockoutOnFailure);
        }

I can place a break within the method and execution breaks when it hits that line.

If, instead of overriding, I overload the method

public async Task<SignInResult> PasswordSignInAsync(string userName, string password, bool isPersistent, bool lockoutOnFailure, HttpContext httpContext)
        {
            return await base.PasswordSignInAsync(userName, password, isPersistent, lockoutOnFailure);
        }

If I place a break, it never hits the break.  Again, within the standard MVC app, this works.  Within the IdentityServer Quick Start project, it does not.  Is there some reason that a project running IdentityServer4 may not inject the HttpContext?

Thanks.

**Comment by brockallen** [comment]
> I think I found why base.PasswordSignInAsync() is being called rather than my classes PasswordSignInAsync() method. I overloaded the method and I am injecting an HttpContext.

So that's a custom/new method. How would our code have known about it? Anyway, like I said -- you have total control over the UI code, so change it to do whatever you need it to.

**Comment by dpedrelli** [comment]
Your comment made it click.  I was so focused on what I don't know about IdentityServer, I forgot what I do know about Identity.  I forgot to modify the AccountController.Login() method.  I still had to add the HttpContext parameter to the PasswordSignInAsync() call, in my IdentityServer project.  I just kept thinking I was doing something wrong with the IdentityServer4 configs.

Thanks.
