### ISSUE TITLE
Porting IdSrv3 to IdSrv4

### ISSUE THREAD

**Issue by rh78** [IdentityServer/IdentityServer4#780]
We are in front of releasing a new product (clean ID database) and I have to decide regarding Upgrade ro Idsrv3 to idsrv4. Actually our Idsrv3 implementation runs fine but if we start now with idsrv3 of course our DB will fill with Idsrv3 data. Will it then be possible to upgrade later without losing any data / Tokens invalid etc? We are using idsrv3 on .net Core 1.1 together with EF Core + Idsrv EF Integration (user data in DB), Client and scope data in memory. Thanks for any hints.

**Comment by leastprivilege** [comment]
I don't think you are running IS3 with .NET Core - they are not compatible...anyways.

There is no easy data migration path from 3 to 4.

If IS3 works for you - then by any means - use it. Maybe it is worth spending a day or so migrating to 4 to find out how much work it would be. IS4 is definitely the version where we'll spend our time and effort in the future.

**Comment by leastprivilege** [comment]
closing for now - feel free to re-open if it needs further discussion.

**Comment by rh78** [comment]
Hi of course one can run it there is the OWIN bridge you guys provided an integration for that. Ok its asp.net Core on full .net framework :) thanks for the information its good to know we will probably Port it then before releasing.
