### ISSUE TITLE
Is it possible to use IdentityServer to protect Java based Web API?

### ISSUE THREAD

**Issue by alvachien** [IdentityServer/IdentityServer4#783]
In my case, there are several legacy Java-based APIs just want to enable the protection. 

Let say, is it possible to provide a Java based AccessTokenValidation?

Thanks and regards,
Alva

**Comment by leastprivilege** [comment]
ask your Java ;)

Tokens emitted by IdentityServer are standard JWTs. Here's a good list of JWT libraries: https://jwt.io/

**Comment by alvachien** [comment]
@leastprivilege 
Thank you so much for your quick reply. 
I still think provides the AccessTokenValidation on other platform can enlarge the usage of the IdentityServer.

**Comment by lousaibiao** [comment]
I created a [repository](https://github.com/lousaibiao/IdentityServer4ProtectSpringbootApi/) and it just a demo about how to config SpringBoot Api when it protected by IdServer. Wish it helps.
