### ISSUE TITLE
Returning JSON from IExtensionGrantValidation 

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4#785]
I have created a custom grant named as "external" where I want to send my facebook access token and validate it ,,, if the email is recieved then create a new user and generate access token,,but if the email is not recieved I want to send  a JSON result with all the user information so that the registeration can be done manually.. how can I send plan JSON from IExtensionGrantValidation..??

**Comment by leastprivilege** [comment]
you can return a JObject via the custom response parameter.

**Comment by leastprivilege** [comment]
But if your question is how you can take over complete control of the response - the answer is, you can't. It is a protocol endpoint with spec defined message formats.

If you need something custom, add a custom endpoint.

**Comment by waqaskhan540** [comment]
Yeah that's what I am doing now.. thanks..
