### ISSUE TITLE
Impersonation

### ISSUE THREAD

**Issue by u-abramchuk** [IdentityServer/IdentityServer4#786]
Hi,

I want to implement impersonation in IdentityServer4-based application. I've found [tutorial for Identity Server3](http://djsharepoint.com/blog/2016/03/impersonation-in-identity-server-3/) and tried to do something similar (using 'acr_values' etc.), but with no success.

How do I implement impersonation in IdentityServer4?

I'm using IdentityServer4 RC2.

Thank you in advance.

**Comment by leastprivilege** [comment]
first of all, you would need to upgrade to the latest version..then

This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io

**Comment by odysseus1973** [comment]
Hi! Thanks for idSrv

Please consider create an example for user impersonation on idSrv4. I find examples how to impersonate  user on idSrv3 (using arc_values and PreAuthenticateAsync) , but can't find examples for idSrv4.

Thanks
