### ISSUE TITLE
Question on Audience in IDS4

### ISSUE THREAD

**Issue by akshetty9** [IdentityServer/IdentityServer4#787]
Is there a reason to include api resources in Audience? IDS3 audience value of "IdsServer/resources" meant that token is intended for all resources protected by IDS server instance. Does that change here? What changes should be done while validating token to validate audience?

**Comment by leastprivilege** [comment]
We added the additional audience if you want to do more specific checks. You can also still validate on scope if you prefer that.

**Comment by Lutando** [comment]
@leastprivilege could you elaborate on what scenario would be beneficial for checking these additional audience values?

**Comment by leastprivilege** [comment]
It's all about granularity.

* /resources check: API belongs to this IS
* api name check: check for API resource
* scope check: check for a (sub) scope of an API

**Comment by Lutando** [comment]
Thanks, makes sense.
