### ISSUE TITLE
Question:  Any way to get client_id based on logoutId ?

### ISSUE THREAD

**Issue by Exocomp** [IdentityServer/IdentityServer4#788]
I'm setting up themes based on the client_id passed to IdentityServer4, I'm able to do this fine for the login since it has the client_id but the logout endpoint looks like this:

http://localhost:5000/account/logout?logoutId=4774996132a7a0d35950f1f41732acad

Is there a way to get the client_id based on the logoutId?

Thanks,
E

**Comment by brockallen** [comment]
This has client id: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Models/Messages/LogoutRequest.cs#L57

From this API: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultIdentityServerInteractionService.cs#L71

**Comment by asharda1** [comment]
all links returns 404
