### ISSUE TITLE
BasicAuthenticationSecretParser doesn't allow for public clients

### ISSUE THREAD

**Issue by andrew-laughlin** [IdentityServer/IdentityServer4#789]
- [x] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem
Setup a public client (e.g. `RequireClientSecret = false`)
Using HTTP Basic AuthN, attempt to login with the client
Result is `invalid_client / no description`

It looks like the client id and secret are evaluated together, rather than separately like in the other parsers.

**Comment by leastprivilege** [comment]
Why do you want to use basic authN with no password? Simply post the client_id in the body.

**Comment by andrew-laughlin** [comment]
We'll use a post, thanks.
