### ISSUE TITLE
Question: token persistence for a SPA client

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#79]
Hi

For an OpenID Implicit Flow SPA client, what's the best or recommended way of storing the token on the client, cookie, local storage, session etc.

Any opinion on this?

Greetings Damien

**Comment by brockallen** [comment]
Any storage is essentially accessible by any code running on the website's origin. So if your website is XSS compromised then any storage is accessible. Also, though, if your website is XSS compromised then most anything that the user could do the attacker can do. 

Having said all of that, it still all depends on your token expiration and where it's needed.

**Comment by damienbod** [comment]
Thanks
