### ISSUE TITLE
PostLogoutRedirectURI only respected if idTokenHint is present

### ISSUE THREAD

**Issue by CrustyJew** [IdentityServer/IdentityServer4#795]
### Issue / Steps to reproduce the problem

Trigger an OIDC logout with a redirect URI (valid or invalid) on the MVC Client without logging in first.
No validation of the PostLogoutRedirectURI will occur, and it will not be populated on LogoutViewModel.

https://github.com/IdentityServer/IdentityServer4/blob/e46dde73e3a47976ee40f8a9912cdbf705e50067/src/IdentityServer4/Validation/EndSessionRequestValidator.cs#L70

I would expect the redirect uri to still work / trigger even if it's not officially logging out a user. As it stands, it just displays the LoggedOut view if there is no idTokenHint

**Comment by brockallen** [comment]
This is by design, as to avoid an open redirect attack. Search the archives on this -- it's been asked a few times before. In essence the id_token_hint is authenticating which client made the signout request, so the post logout redirect uri can be verified against the list in the client configuration.

**Comment by CrustyJew** [comment]
Sorry I hadn't seen that, mustn't have been using the best search terms earlier.. I did find this discussion

https://github.com/IdentityServer/IdentityServer4/issues/544

Although what you just mentioned about verifying against the client configuration makes sense, but it seems like there should be a better way of doing that or the ability to add in a "default" redirect uri that's allowed for any client at the IdentityServerOptions level.

Would passing the ClientID and Secret be a bad idea to identify the Client in case the id_token_hint isn't present?

**Comment by brockallen** [comment]
> Would passing the ClientID and Secret be a bad idea to identify the Client in case the id_token_hint isn't present?

That's not in the spec :)

**Comment by CrustyJew** [comment]
True,

But according to the spec the id_token_hint isn't required and the redirect uri should be honored if it's provided. But it does state that it should be registered so arguably I do get it. Thanks!

**Comment by brockallen** [comment]
Yep, we're erring on the side of caution with our level of strictness. Thanks.
