### ISSUE TITLE
invalid_token using a proxy

### ISSUE THREAD

**Issue by Exocomp** [IdentityServer/IdentityServer4#796]
I'm setting up identityserver4 for the first time and I'm running into an issue when deploying it to production where IdentityServer4 is behind a proxy.  

User -> Proxy -> IdentityServer4

The issue is at this step after the user logs in and then is redirected to the callback:

`GET /identity/connect/userinfo HTTP/1.1
Host: host is here
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer token info here
Referer: call back here
Cookie: .AspNetCore.Antiforgery.rest of cookie here
Connection: keep-alive

HTTP/1.1 302 Found
Cache-Control: no-store, no-cache, max-age=0
Pragma: no-cache
Location: location url here
Server: Kestrel
WwwAuthentication: Bearer
WwwAuthentication: error="invalid_token"
Date: Wed, 08 Feb 2017 03:35:02 GMT
Content-Length: 0
`

Any idea what could be causing the problem that could be specific to the proxy setup.  Looking at the requests for a few hours all the necessary requests and headers look like they are getting to Identity Server just fine.  I'm wondering if there is something specific I'm not aware of that you might know with the proxy setup that could be causing it ?

**Comment by brockallen** [comment]
Visit the discovery endpoint and look at the issuer -- does it look right?

**Comment by Exocomp** [comment]
Yep the discovery endpoint is fine and a token is generated and sent back to the client using oidc_client.  oidc_client then makes a userinfo call with the token and that is when there is a reply of invalid_token which I believe is breaking the oidc_client parser also since it is expecting json back but gets html back (since there is 302 redirect to login since token was invalid).

I was looking at the proxy log for the userinfo call and it does receive the token and it shows it sends the token to identityserver, however something doesn't make sense here.  At this point I don't trust the proxy logs, I need to check what is going across the wire or update the logging on identity server to see if it is receiving the token.  So looks like more troubleshooting for me today.

**Comment by Exocomp** [comment]
Found the problem, the authorization header is not making it to identity server.  So proxy logs were wrong all along, somehow it is dropping it.  I would close this but in going through this issue I think there is a bug between IdentityServer4 and the oidc_client in the following scenario.  I will describe it here and leave it up to you on how you want to proceed (it will not affect me once I fix the proxy issue so would be low priority).

Issue:  oidc_client parser breaks when IdentityServer returns a "invalid_token" on the getuser call.  Reason why is oidc_client is expecting json back but IdentityServer4 returns html (login page) since the token was invalid.

To Reproduce: Get IdentityServer4 to return "invalid_token" on getuser call, see example below:

Example:

GET /identity/connect/userinfo HTTP/1.1
Host: host is here
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Accept: /
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Authorization: Bearer token info here
Referer: call back here
Cookie: .AspNetCore.Antiforgery.rest of cookie here
Connection: keep-alive

HTTP/1.1 302 Found
Cache-Control: no-store, no-cache, max-age=0
Pragma: no-cache
Location: location url here
Server: Kestrel
WwwAuthentication: Bearer
WwwAuthentication: error="invalid_token"
Date: Wed, 08 Feb 2017 03:35:02 GMT
Content-Length: 0

**Comment by brockallen** [comment]
> Location: location url here

And the 302 redirects to the login page?

**Comment by Exocomp** [comment]
Yep:

Location: https://<domain>/identity/Account/Login?ReturnUrl=%2Fidentity%2Fconnect%2Fuserinfo

**Comment by brockallen** [comment]
Ok, we shouldn't let that redirect.

**Comment by Exocomp** [comment]
Sounds good.  And for the sake of completeness, turns out the firewall was dropping the authorization header (not the proxy fault).  My issue is resolved.  :)

**Comment by yakeer** [comment]
@Exocomp  Could you please share how did you solve it?
I'm having the same issue and it drives me nuts.
