### ISSUE TITLE
Generate access token with ResourceOwner using only the username

### ISSUE THREAD

**Issue by waqaskhan540** [IdentityServer/IdentityServer4#797]
I am using ResourceOwner flow, so is it possible to generate access token from the identityserver using only the email/username while leaving the password blank?

The reason why I need to do this is that I have users registered/login through external providers, like facebook ,google. Conventionally asp.net identity creates a user in aspnet users table without password (for external users) ..but I am not using that flow.. I just get fb access token and get the information from facebook including emails,gender,id and creating user manually.

**Comment by brockallen** [comment]
This is a design question -- not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by quanterion** [comment]
https://stackoverflow.com/questions/44172221/generate-access-token-with-identityserver4-without-password
