### ISSUE TITLE
Should the "temp" cookie middleware be included in IdSrv by default?

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#798]

**Comment by brockallen** [comment]
We could do something similar to how we do the primary cookie.

**Comment by leastprivilege** [comment]
like #802 ?

**Comment by brockallen** [comment]
Almost. I was thinking they could still setup the MW themselves and thus they'd set a new property on options for the name of the external MW. If they've set it, we don't register the cookie MW.
