### ISSUE TITLE
/UI in host

### ISSUE THREAD

**Issue by ispbox** [IdentityServer/IdentityServer4#80]
In v.3 of IdentityServer there was a sample host application with few files for users, scopes and clients. But in v.4 there is also UI folder with all the UI. Should I just copy-paste all that folder to my own project, or maybe there is some better way?

In other words, is there any way to show default UI as it was in v.3 without all that stuff in the UI folder?

**Comment by mackvatoloco** [comment]
V3 had the UI embedded. In V4 you have full control over the UI. You can either create your own UI in any technology you prefer, copy-paste the UI provided in the example or wait for the nuget package with default UI/Templates they will eventually provide. 

So, if you want default UI and are in a hurry, copy-paste (either in the same project or in another), if not in a hurry, wait for the separate nugget package. 

For more: https://leastprivilege.com/2016/01/11/announcing-identityserver-for-asp-net-5-and-net-core/

Hope this helps.

**Comment by ispbox** [comment]
mackvatoloco, thanks a lot for a detailed description! I will copy-paste existing UI from IdentityServer4/Host application.
