### ISSUE TITLE
DI and Logging

### ISSUE THREAD

**Issue by dpedrelli** [IdentityServer/IdentityServer4#801]
- [X ] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem
I want to log failed login attempts, but I want to include the ClientId and the calling client's URL host name.  Is there a class that I can inject that will give me the ClientId and the URL of the calling client?  Request.QueryString.Value contains the ReturnUrl, but it does not contain the ClientId.

Thanks.

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
You can parse the return Url with the IIdenttyServerInteractionService. The connected IP is via HttpContext.Connection.

**Comment by dpedrelli** [comment]
I had the client IP address.  I parsed httpContext.Request.QueryString.Value, to get the client_id and redirect_uri.  It ended-up being a cleaner option than having to inject more classes.
Thanks.
