### ISSUE TITLE
"Sharing" authentication between ASP.NET Core MVC server application and JavaScript client

### ISSUE THREAD

**Issue by R74NN** [IdentityServer/IdentityServer4#803]
Hello,

I have an ASP.NET Core MVC server application hosting a JavaScript client application. The JS application currently uses Oidc auth with implicit flow. The MVC server application provides file download functionality and needs to authenticate the user too.

Is there a way or an example how to configure both applications to support scenario, when user logs in the JS client and clicks download link referencing to MVC server backend and the server should accept the already authenticated user. 

Also if the user is not authenticated yet and navigates in the browser to the download URL, the MVC backend should redirect him to identity server login page before proceeding with the download.

I have tried several configurations, but both clients behave independently and after first login the MVC server doesn't reflect JS client user switch inside one browser session.

Thanks.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
