### ISSUE TITLE
UserInfo from external OpenIdConnect Provider

### ISSUE THREAD

**Issue by windischb** [IdentityServer/IdentityServer4#804]
Hi!

I have an ADFS 4.0 Server successfully connected to my Identityserver4 as OpenIdConnect Provider.
How can i get the UserInfo from this OpenIdConnect Provider?
I need to get the Roles and a few other things from there to grant Access to an API based on this Claims.
If i "ask" the UserInfo Endpoint from Identityserver, will Identityserver forward my request to the external Provider?
Or do i have to ask for this Infos on Login and save as claims on the User in my Database?

Br
Bernhard

**Comment by brockallen** [comment]
>  How can i get the UserInfo from this OpenIdConnect Provider?

That's up to you when connecting to it. If you're doing this in an IS4 host, then you are probabaly using the OIDC middleware from Microsoft which automatically consumed the user into endpoint. I recently heard that ADFS' OIDC support is... limited: https://twitter.com/glatzert/status/827959547478364160

So you'd really have to ask Microsoft for support on how to use ADFS's OIDC support.

**Comment by windischb** [comment]
Ah ok! Thanks!
