### ISSUE TITLE
Duplicated Roles

### ISSUE THREAD

**Issue by dpedrelli** [IdentityServer/IdentityServer4#805]
- [X ] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem
One of the things that I am doing with IdentityServer is to implement SSO across multiple MVC applications.  I followed a StackOverflow article that injects a custom IProfileService, to add Asp.Net Identity roles as claims.  With this code, the roles are added and the Controller Action, which is protected by [Authorize(roles = "")] fires properly.  Without it, I get Access Denied.

The key is that with the code that adds the roles, I can set a break in the controller and see that the roles are all duplicated.  Further, if I said a break inside of the IProfileService implementation of GetProfileDataAsync(), whether I explicitly add the roles or not, they only exist in the context once each.

I have three screen captures.  The first one shows a break in which the code to add the roles as claims has been commented out.  The roles are still added.  However, I get an Access Denied on my controller action.

![claims1](https://cloud.githubusercontent.com/assets/17931111/22795640/698c6c10-eec5-11e6-95a0-5b4133f5e95c.png)

The second capture shows the code to add the roles is executed.  Yet there are the same number of 17 claims and none of them are duplicated.  In this case, the controller action succeeds.

![claims2](https://cloud.githubusercontent.com/assets/17931111/22795688/8e01020e-eec5-11e6-9571-3a859e71d7b1.png)

The last image shows the controller action and the roles are duplicated.

![claims3](https://cloud.githubusercontent.com/assets/17931111/22795759/ccf01932-eec5-11e6-8d3f-80bf9d7f713d.png)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
did you ever resolve that problem?

**Comment by dpedrelli** [comment]
No.  At this point, I just left it.  The duplicated roles work.  However, I would prefer to remove them and make my cookie smaller.

**Comment by brockallen** [comment]
It wouldn't surprise me that if the same claims came in both the id_token and the user info endpoint that the OIDC middleware would add them all.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
