### ISSUE TITLE
Question: Security Of Refresh tokens In Resource Owner Flow

### ISSUE THREAD

**Issue by storment** [IdentityServer/IdentityServer4#81]
I have a public application that uses long standing Refresh Tokens to access an API (Both read and write).  I was wondering about the security of using access tokens in this scenario, specifically mitigating against the risk of brute forcing a token.
Is a brute force not a worry due to the number of combinations?
Is it ok to have the same ClientID and Secret for every install of the application (Where the ease to extract it presumably renders them useless). and if not....
Should I have a different ClientID and Secret for every installation of the application in the wild or is there a better way such as passing through a user ID as well and linking that to the refresh token?
Thanks in advance for any pointers.

**Comment by mackvatoloco** [comment]
> Is a brute force not a worry due to the number of combinations?
An access token is a JWT, which means it is signed (assures the JWT has not been tampered with) and encoded. So I don't think brute forcing a token is a concern. Of course there are other concerns with the use of access tokens like XSRF (if you are using cookies), man in the middle attacks, poorly validated tokens, etc. But most of this have a known solutions.

> Is it ok to have the same ClientId and Secret for every install of the application
Yes. Just remember that ClientId and Secret are the application's credentials, so they have to be safeguarded.

> Should I have a different ClientId and Secret for every installation of the application in the wild
It depends on your business rules. But just consider that there is a trust relation between the authorization server and the client. The authorization server must know of the client. So in this scenario, for every installation of the application you would have to "inform" the authorization server that there is a new client(for example having the user "manually" request a ClientId and secret from the authorization server).

> or is there a better way such as passing through a user ID as well and linking that to the refresh token?
You should use the SubjectId standard claim for this (sub). So yes, you could "link it" I guess along with any other claims you deem necessary. But if you are worried about the fact that access tokens and refresh tokens are self contained tokens (they have the information required to be granted authorization and don't need to be checked by the authorization server once granted), consider using reference tokens instead (which use the introspection end point) to have more control over their lifetime. For more on reference tokens and introspection: https://leastprivilege.com/2015/11/25/reference-tokens-and-introspection/

Hope this helps.

**Comment by storment** [comment]
Thanks for the reply,
I may be wrong but I was under the impression that IdentityServer's refresh tokens are simply a random id with no data such as Sub and no signature.  A brute force would just fire random ID's at the Token Endpoint and hope for a match.
My worry was the more users you have the more active refresh id's there are to match against but I've been thinking about it and even if you have a refresh token for every human on the plant, the chance of matching one would still be almost 0. I think the combinations are so big I just can't visualize it.
Identity Server seems to use 128bit ID's for the Reference Token Handle which I've increased to 256bit to satisfy my own Anxiety.
I could lock it down even further by requiring the refresh token in the form UserID.RefreshTokenHandle when sent to the endpoint but I think this is probably overkill?

**Comment by mackvatoloco** [comment]
Yes my bad, reference tokens are opaque tokens. 

I don't think is a good idea to resend the UserId outside the access token.
I believe it is overkill.

**Comment by storment** [comment]
Thanks, I'll leave it as I currently have it then.
