### ISSUE TITLE
Consider ability to define cache-control header for discovery endpoint

### ISSUE THREAD

**Issue by jjafuller** [IdentityServer/IdentityServer4#810]
It would be nice if there was a supported way to define cache headers for the discovery endpoint. Right now, our resource servers assume that the jwk immediately expires if there is no cache header set. 

For now we are using middleware to add the cache headers on for discovery requests. While this works it would be nice to get an integrated solution. We would be happy to submit a pull request to add the functionality if you let us know how you would like it integrated.

**Comment by leastprivilege** [comment]
> Right now, our resource servers assume that the token immediately expires if there is no cache header set.

I don't follow - explain.

**Comment by jjafuller** [comment]
I edited my commend for clarity I was referring to the jwk, not the access token. I also found an example in another client that does something similar to what we are doing, except we default the TTL to 0, rather than 24 hours.

https://github.com/coreos/go-oidc/blob/fe7346e2e6855bda769d5b3db7d917f159c5613c/oidc/key.go#L28

**Comment by leastprivilege** [comment]
so IOW - you are saying that it would be nice we would support a configurabel cache control header on the discovery docs so a client library could use that value as a hint for how often the document should be refreshed?

This is not mentioned in the spec - so I think it is wrong if client impls make an assumption - but I like the idea... @brockallen ??

**Comment by brockallen** [comment]
Yea, not a bad idea. You can do this now by putting middleware in front of IdentityServer and emit those headers on the way out for those endpoints.

**Comment by jjafuller** [comment]
Yup. That is what we are doing now.

**Comment by leastprivilege** [comment]
Can you give me an example how that header should look like - we will add this.

**Comment by jjafuller** [comment]
The header just needs to look like this: `Cache-Control: max-age=3600` this is the basic middleware we're using now:

https://gist.github.com/jjafuller/0bd6631235eaf93928487e6288e092d1

**Comment by leastprivilege** [comment]
Happy? https://github.com/IdentityServer/IdentityServer4/commit/58e6c3ab42a3071f9db3fe2ec66a09737a09838a

**Comment by brockallen** [comment]
Yes, happy.
