### ISSUE TITLE
The access token in the request doesn't have required audience

### ISSUE THREAD

**Issue by windischb** [IdentityServer/IdentityServer4#812]
- [x] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

I still have Problems with ADFS 4.0 as external Provider.
Maybe it's not related with Identityserver, but maybe anyone have a hint or recommendation...

I open the login Page on Identityserver -> http://localhost:5000/account/login
Click on the Button for the external OpenIdConnect Provider and will be forwarded to the ADFS login Page.
Provide Credentials and can login. But if i try to send a request to the UserInfo Endpoint i'll get an HTTP 401 Unauthorized Error.

Afterwards i can find following Errors in the Logfiles from ADFS Server:

1. UserInfoListener.ValidateAccessToken: The access token in the request doesn't have required audience 'urn:microsoft:userinfo'. Actual audience 'microsoft:identityserver:60b3d106-d155-4f9f-ba75-84b8078829fa'

2. UserInfoListener.WriteErrorResponse: The UserInfo endpoint meets error when process the requset. Writing error response.

3. Sending response at time: '2017-02-12 18:02:50' with StatusCode: '401' and StatusDescription: 'Unauthorized'.
Response headers set: {"WWW-Authenticate":"Bearer error=\"invalid_token\", error_description=\"MSIS9921: Received invalid UserInfo request. Audience \u0027microsoft:identityserver:60b3d106-d155-4f9f-ba75-84b8078829fa\u0027 in the access token is not same as the identifier of the UserInfo relying party trust \u0027urn:microsoft:userinfo\u0027.\"","Content-Type":"text/html; charset=utf-8"} 

It looks like ADFS expect the Audience 'urn:microsoft:userinfo', But receives 'microsoft:identityserver:60b3d106-d155-4f9f-ba75-84b8078829fa'.

The Payload from my token:
{
  "aud": "microsoft:identityserver:60b3d106-d155-4f9f-ba75-84b8078829fa",
  "iss": "http://SRV2016DC01.test.local/adfs/services/trust",
  "iat": 1486923455,
  "exp": 1486927055,
  "apptype": "Confidential",
  "appid": "60b3d106-d155-4f9f-ba75-84b8078829fa",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "auth_time": "2017-02-12T18:02:49.653Z",
  "ver": "1.0",
  "scp": "profile openid"
}

I don't know what's the "normal" or "right" Value for the Audience Property when sending a request to the Userinfo Endpoint...
Anyone who can tell me if this is a failure from the OpenIdConnectMiddleware in my Identyserver or from ADFS?

**Comment by leastprivilege** [comment]
This is indeed completely unrelated to identityserver - but it looks like you try to send the identity token and not the access token to the userinfo endpoint.

**Comment by windischb** [comment]
ADFS is really strange.......
Thats the only "access_token" i get back.

In the ExternalLoginCallback i get following from _signInManager.GetExternalLoginInfoAsync():

```
[
  {
    "Name": "access_token",
    "Value": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImplZVFqTFVhbV81akpncVcxalZMZVlsOEdpayJ9.eyJhdWQiOiJtaWNyb3NvZnQ6aWRlbnRpdHlzZXJ2ZXI6NjBiM2QxMDYtZDE1NS00ZjlmLWJhNzUtODRiODA3ODgyOWZhIiwiaXNzIjoiaHR0cDovL1NSVjIwMTZEQzAxLnRlc3QubG9jYWwvYWRmcy9zZXJ2aWNlcy90cnVzdCIsImlhdCI6MTQ4Njk3NDQ2NywiZXhwIjoxNDg2OTc4MDY3LCJlbWFpbCI6ImFkbWluQHRlc3QubG9jIiwiYXBwdHlwZSI6IkNvbmZpZGVudGlhbCIsImFwcGlkIjoiNjBiM2QxMDYtZDE1NS00ZjlmLWJhNzUtODRiODA3ODgyOWZhIiwiYXV0aG1ldGhvZCI6InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0IiwiYXV0aF90aW1lIjoiMjAxNy0wMi0xM1QwODoyNzo0Ni45MThaIiwidmVyIjoiMS4wIiwic2NwIjoicHJvZmlsZSBvcGVuaWQifQ.VVXBxh2HXX4B3Afh_sQuVdcAPETGVwVGhGSHGRumejunwJ5xisrFqgM9cFgfQYDNaeWl1-vPBkQfzkFDgBfDALnohxfE50YU2Tdu-rO7oRDGXwXmVCwDJPOjBVVbnVfigQW_Z8AI3RcCztvfxbpCz6Pt0reUeTK1pBSx6aTClsy9ezsyDA7A6NQ1iR3-fLX2Slg_AJOcq4ElqX937ARGriCPBswNLGF7JNxj8x3NYmyAQ_mGrtKekWpZ5B3uLP5DDZZfmj8ab9-fTibEDNLaD5FkFGVOoTFHLlq7VkiEr7yTsMsgZBHFHJlEuWxXx_j8skdDblKMn0EeLsINeLxZZA"
  },
  {
    "Name": "id_token",
    "Value": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImplZVFqTFVhbV81akpncVcxalZMZVlsOEdpayIsImtpZCI6ImplZVFqTFVhbV81akpncVcxalZMZVlsOEdpayJ9.eyJhdWQiOiI2MGIzZDEwNi1kMTU1LTRmOWYtYmE3NS04NGI4MDc4ODI5ZmEiLCJpc3MiOiJodHRwczovL1NSVjIwMTZEQzAxLnRlc3QubG9jYWwvYWRmcyIsImlhdCI6MTQ4Njk3NDQ2NywiZXhwIjoxNDg2OTc4MDY3LCJhdXRoX3RpbWUiOjE0ODY5NzQ0NjYsIm5vbmNlIjoiNjM2MjI1NzEyNTk1NjczOTk1Lk5UbGxNRFF3Wm1RdFltTXpOeTAwWVdZNExUaGxaV1V0TkRKaE5XWXdabVJqWkRBeU56YzVPVEpoT0RJdE9USmlOeTAwWm1VekxXSTBaV1F0T1dFd01ERTVNR0UxWldJeCIsInN1YiI6InV0NWxmbEFGZVhzMTlhbWZlaFVzcnpadStVWW1vQXZOVFVoaU93U2Y5KzA9IiwidXBuIjoiYWRtaW5pc3RyYXRvckB0ZXN0LmxvY2FsIiwidW5pcXVlX25hbWUiOiJURVNUXFxBZG1pbmlzdHJhdG9yIn0.hsApHR4eG6w6gR1qU6kvG_6B16zG8qR_JcdAztdKEyOpvCt6zbTpkoKFL7KozKkzahj9Sd7e7Mf9FLNMKZRvuhTnrwmxIE69ng1vs2gl3puMdM2sKf_yZsSUgxKaaSI6UBf4WY7MUbTJCW-Y7J8AeGh4fMfGUsKyiLwFtXU5ppRGygaL4TvpL8NcFAm2qYYMz8N7g52qbcimQZAx22WbCr9PPq3uUIU-fM4sJE_9U0OL2O0wufBXJ_18W6MCAGN5pyvMSBvCsB2P-Lx5RCLiM6nVkGxPrBATAxsr8-rpuGFOf5Ilwb-UN5eBGAi6klt3cuLWT4iAAeR1jM39nCocRA"
  },
  {
    "Name": "refresh_token",
    "Value": "9C6xx5ev54b8MPCUnwwEKKaJNBnMdghax0GmWpD-FRkAAQAAkEpw-4vByr1n_eD1O4lT7Fgl03-j3fhCifwilgVcy4IXB-6Q--LuQqtW2VIBabJSEYuv2Kt1ymDMIHQirRFKyX2VrJ-oFrhY90WFzbYcGgT3FYl5g0rl13TM-aZ6yPDO67uYeFMwiWBGoedC5-ehe9DfM90QRskinnr2jR03GwfBYVxTewoTbABAPDeNnNfu2KXNbbBbbX49g-MF4aoL7K45Z1Is0lw_-6Pj683UOJLFoCNA1JHVe-SwUw-sybjolYAa3H3E3uLgVUhGTewB4iZaCTVLwghpLydj0Ye82MgTtG0Ju7w-jtVxrOzXSD-vhbIp66cRFNkKf7kB0OS-s3AFAAAabB8f7bi1LuzVmNSApygRF3PaR3ol_ns-UM-oanvOryUx07ZoA6BzOZtoKGji1mI-Acf6hEZy-x6Kai-LlX2GNrzZwCmRfCieioE7D2LA-z-DRXH4kXmKRG-fzQoxfJ_bjtWXvpOSP56bV3XF96maRpeuTv3-zjMf_5SrgrEDjt7CA6pczaS9E9iI-zKQapeXOmVFsuHOBFw9OuXeTAmH3vUsYXJ2StV8pK7103qgXtNWpGT4xmbMPSpNNwHVzxX04I4D50mfImF69wlaw1jLVzNqGKiMVJlhJm46AA8tIN62sz5wA3J-KxwvqKFh4Uitzy0NK2CcHtRJ95aviqYOFTEz9wYugaySjISOM5sVM59VB9gU50-rqN_YMUmNBGKO0SuAteWGxC0_YF3xCQPIium0SDu-Lk-kDjxwqTaImIsslmnWYuMKyo5fhu7JEOGNXkEw3zdLknbq2f5u6zRSt9UhdvHhSOg_fLeAYkPlVxPN-ZdkGLHSyG4ATVFhd6aZBpTozPkXxC7NHCM54HGCfAbEw3qColzvk17uzXfWcL0cqSHZFVLNO-TjtvJT6OiGfMwJyZAOR8fLmhpjgxx0Sxw-l-BekGLYcLarAVMc84qKA5TuB2flHuk7IXGKrCUZE4FoFK2UZFNuXJw7X6i8f0aMDTu27nv5bjRK9JR1neIZJIViMXpoA8YPt-dU5esLzMERWLGoyceOzqxPdUEL3FQoZzOhf1WDonBOpp4Vi2cryXFiGL5RV6gRyiBWLmg3xjrWzUGGxMddU1idcKY5_DFdcKEyjhHikiJYGQrIUz3ChOxiyWM3n9reeHGqPXkBHeX9z2_xRX0QFtk2ITXRKeb4ziRvYQ49xwQtGFMgZLfwJl-2LiaVLkvbmElitI2HJmWuR75sHUFErlfjHEpSFaTNUb-EH6nATik0has65RaaS_JTqLZMzpvn3ITiNgDDDfcFy6eyp_yeJRVBsWe4T7zv3IkVQFNdJgQpTqXszy7-TyVmt3aj-JIZRBUvIliU7rvYX3YdaJnmH0NFvcmFf3FglmrGmYHFEuB7KNFvzeQ3OuIclf1lbfqPjO410TEYSMRFuiVrYC9oAZbcvKD3rQMrW-lZFZywZDf0emEmBE5XMCb4jkhkWGPYD7w0uLdzbMbOs4usWWg8gO9loqMu4ctnSfPaX4vS0x3fN5YeH1y4YiFx0yCPRYEcRKzTLVOj-wE6Ir7wrhW3gYroTnH0O9u3ncds9mSaR8lHWqCSgWEqu19-JE0O1ItjR7TrltPSc6EK2xVzwqTynCCBVlKNguMb0q133uzWFrGF7ZJnfkNJvBpVdo2CGDjF1PhXKsOn8_udDyI7ZtS-PxYMv8Y0C1Y0V4ma7CIfOJgNBgZamVjSMgt9Ky43GJsNd1ucMpyCU63JrWEz62Ecf5nW8qlh0TV0ieVatOj2Srduw4GS2KLQ9FvRTT1suJ64Zroqdeg2ziCIlq4I4niEIkQneIORfWwtAdzTOMjpK34Mz09GahLkoMJEnCqsm2f8muX4YajNIhClojUzK7S1DqhTsxIe9zodss5NJlKJqUp4Ic92aXhvWrW0jvz2ZNSHXdsSSW0EHvhRIwA5wj94j0AGT053cUbxweIbvbp9Mrjq38yFgPeOxAxqx5yzcRi7v4FVHBN8W6aHCEs9DIHc4xuRd7fI3YhTteDUA3OY3hkvMN1EHoMShZC6ybvtxnxpNqb6G15vPTp2j1UvF0lDhS7K3AgUOjffv7B3A66lLI8wp4poK6Tn0LB8Z0eGku7xiJcbwr1420EpeOVxpTj4f1LlJuvwQrAFxihf51BTn4qchioUjeoX98cGYwBkLhHHIYhCqnQ.WduPafn5m6duRZPRlxPg2c6oocSaud-YSZsLRrqbDgdvE2xZTmWOoOLaCK7pZQOBtE430NsFxwMyVF1-d96Z75iUeD8ybj_sFlbBJd8C2OsSSaGwQ4bztT34_vvz7h6R2A-03UX6Nd0ZobqJgQFuIiu6ra56pYJ9Oh4HTajFZwWPzMig98Tod1w-p0Smf_a9sIE8SE367LcTdkOYb5kiaCRaJ1zo8vRGNq04UuBA55guphdonSkG2AoXPks3Ic3ZG42smBX-6MgfD4frTZitkxVcqEvG1oMbyY9pHk_fapoJNE8Q53FlOiPNt2U5MFE6vdyXtJ0M__uh2VGJxdilPw"
  },
  {
    "Name": "token_type",
    "Value": "bearer"
  },
  {
    "Name": "expires_at",
    "Value": "2017-02-13T09:27:49.0006923+00:00"
  }
]
```

Decoded access_token: 
```
{
  "aud": "microsoft:identityserver:60b3d106-d155-4f9f-ba75-84b8078829fa",
  "iss": "http://SRV2016DC01.test.local/adfs/services/trust",
  "iat": 1486974467,
  "exp": 1486978067,
  "email": "admin@test.loc",
  "apptype": "Confidential",
  "appid": "60b3d106-d155-4f9f-ba75-84b8078829fa",
  "authmethod": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
  "auth_time": "2017-02-13T08:27:46.918Z",
  "ver": "1.0",
  "scp": "profile openid"
}
```

Decoded id_token:
```
{
  "aud": "60b3d106-d155-4f9f-ba75-84b8078829fa",
  "iss": "https://SRV2016DC01.test.local/adfs",
  "iat": 1486974467,
  "exp": 1486978067,
  "auth_time": 1486974466,
  "nonce": "636225712595673995.NTllMDQwZmQtYmMzNy00YWY4LThlZWUtNDJhNWYwZmRjZDAyNzc5OTJhODItOTJiNy00ZmUzLWI0ZWQtOWEwMDE5MGE1ZWIx",
  "sub": "ut5lflAFeXs19amfehUsrzZu+UYmoAvNTUhiOwSf9+0=",
  "upn": "administrator@test.local",
  "unique_name": "TEST\\Administrator"
}
```

**Comment by leastprivilege** [comment]
OK - Well I haven't tried ADFS4 in-depth yet. This is something you should take to Microsoft.

**Comment by windischb** [comment]
I think i'm little bit closer to the solution for my Problem!

Now i can see the Claims inside of the info object in the ExternalLoginCallback Method!

But afterwards these claims are not in User.Identity.Claims...
![image](https://cloud.githubusercontent.com/assets/6182311/22896571/fc711112-f220-11e6-90fc-f64a3e48b31e.png)

Whats the best way to copy those claims to the User?
Save it directly on the IdentityUser Entity in the Database?

If its useful i can create an example if everthing works!
Maybe other people have the same struggle with ADFS...

**Comment by windischb** [comment]
I just read a similar question and answer from in an other Issue......
Thanks!

**Comment by nafiux** [comment]
Hi wind, Did you solve the problem?

**Comment by premiumwd** [comment]
@windischb having same issue, can you link example where you found solution?

**Comment by windischb** [comment]
As far as i rember, the Problem was on ADFS Server side.
Currently i don't use ADFS anymore, but i have Screenshots from the ADFS Server configuration.
Maybe they are helpfull...
 
![image](https://user-images.githubusercontent.com/6182311/29742925-0c7d747e-8a88-11e7-8135-7e58cae5b440.png)

![image](https://user-images.githubusercontent.com/6182311/29742935-2ca38270-8a88-11e7-9d7a-fdd5d4ae1937.png)

![image](https://user-images.githubusercontent.com/6182311/29742940-4251d784-8a88-11e7-90dd-b18f082151a7.png)

**Comment by m-mccool** [comment]
Hi 
Just hit this problem myself and I got it working using the the code below.

A few things to note

1. I had to set the `Policy` on the `OidcClientOptions` to get rid of a at_hash error
2. I had to set `LoadProfile` property on the `OidcClientOptions` to avoid an error where it complains about not being authorized to use the userInfo endpoint
3. ADFS requires a (non-standard?) parameter called `resource` which should contain the relying party identifier of the Web API configured in your applications group. I achieved this by adding it via the `FrontChannelExtraParameters` property of the `LoginRequest` object passed to the `LoginAsync `method

```
var authority = "https://<AdfsServerFullyQualifiedDomainName>/adfs";
var options = new OidcClientOptions
                {
                    Authority = authority,
                    ClientId = "<YourClientId>",
                    Scope = "openid profile api",
                    RedirectUri = "my.domain.name://callback",
                    ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect,
                    Browser = new ChromeCustomTabsBrowser(this),
                    Policy = new Policy()
                    {
                        RequireAccessTokenHash = false
                    },
                    LoadProfile = false
                    
                };

var oidcClient = new OidcClient(options);
                _result = await oidcClient.LoginAsync(new LoginRequest()
                {
                    FrontChannelExtraParameters = new Dictionary<string, string>()
                    {
                        { "resource", "<your web api relying party url configured in ADFS>" }
                    }
                });
```
