### ISSUE TITLE
How to use same hashing mechanisim on client manager side as IdentityServer4 does?

### ISSUE THREAD

**Issue by demiremre** [IdentityServer/IdentityServer4#813]
When I create my clients , I am supposed to enter the client secret. I know that IdentityServer4 uses SHA256() for hashing secrets. But I m concerned that there may be some difference between algorithms. So, what is the best way to hash client secret for no problem with IdentityServer during client validation?

**Comment by leastprivilege** [comment]
You don't need the hashing algorithm on the client - you send the secret in clear text (over a secured transport). IdentityServer uses the hash to store the secret.

**Comment by demiremre** [comment]
I am using entity framework for CRUD clients on a different UI. So , my goal is creating a new client with a secret. To insert the client with hashed secret into database, what should I do? My client manager for creating, deleting is separated from IdentityServer, the database is just common.

**Comment by demiremre** [comment]
Hello again,

I guess it is okay to use the class pointed by the link below while creating and inserting new client into database in order to hash client secret. I had a look at database and saw there is no problem. I created an secret ("secret") and saw that it is the same hash  with IdentityServer created  with same secret. Am I right?

https://github.com/IdentityServer/IdentityServer3/blob/master/source/Core/Extensions/HashExtensions.cs

**Comment by leastprivilege** [comment]
Why IdentityServer3?

**Comment by demiremre** [comment]
I couldnt find pure class which is responsible with hashing of IdentityServer4. I assumed IdentityServer3 and IdentityServer4 use the same algorithm to hash client secret. When I checked it out, they both created same secret hash for same key.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Extensions/HashExtensions.cs

**Comment by demiremre** [comment]
Thank you for your help and IdentityServer :)
