### ISSUE TITLE
IResourceStore methods to get open ended data is a little dangerous

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#814]
Can we turn this into a pager instead.

The Cassandra C# driver
https://github.com/datastax/csharp-driver

has a really good IPage implementation that I have adopted for all my stores.

The IResourceStore should allow paging for data.
```
   
    public interface IResourceStore
    {
        ....
         Task<IPage<ApiResource>> PageAsync(int pageSize,
            byte[] pagingState,IEnumerable<string> scopeNames = null);

        Task<IPage<Resources>> PageAsync(int pageSize,
            byte[] pagingState);
    }
```

here is a production example of one of my stores.

````
 public interface IDocumentByOwnerStore
    {
        #region Document

        /// <summary>
        /// Creates a new dodument
        /// </summary>
        /// <param name="document"></param>
        /// <returns></returns>
        Task InsertDocumentAsync(Document document);

        /// <summary>
        /// Delete the document
        /// </summary>
        /// <param name="document"></param>
        /// <returns></returns>
        Task DeleteDocumentAsync(Document document);

        /// <summary>
        /// Finds the document 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Task<Document> FetchDocumentByIdAsync(Guid id);

        /// <summary>
        /// Pages all documents 
        /// </summary>
        /// <param name="pageSize"></param>
        /// <param name="pagingState"></param>
        /// <param name="owner"></param>
        /// <param name="category"></param>
        /// <param name="version"></param>
        /// <returns></returns>
        Task<Models.IPage<Document>> PageDocumentsAsync(int pageSize,
            byte[] pagingState,
            string owner = null, string category = null, string version = null);

        #endregion
    }
````

**Comment by brockallen** [comment]
In what scenario do you expect paging to be necessary? Are you building an admin UI?

**Comment by ghstahl** [comment]
You tell me.  What is the expected number of ApiResource and IdentityResource records that I might have?  is it 10, 100, ..., 1 million.

I am looking at IdentityServer4 as a self help portal for developers to register their own clients, scopes, etc.  It will be there as an open ended access_token manager for any api scope set we can come up with.  

I may not have a problem with this particular store (IResourceStore), however....

As-A-Rule when I see an api like the following;
```
Task<IEnumerable<ApiResource>> FindApiResourcesByScopeAsync(IEnumerable<string> scopeNames);
```
I write a defect and ask for it to be changed to something like this;
```
 Task<IPage<ApiResource>> PageAsync(int pageSize,
            byte[] pagingState,IEnumerable<string> scopeNames = null);
```

```
 public interface IResourceStore
    {
        Task<ApiResource> FindApiResourceAsync(string name);
        
        Task<IEnumerable<ApiResource>> FindApiResourcesByScopeAsync(IEnumerable<string> scopeNames);
        Task<IEnumerable<IdentityResource>> FindIdentityResourcesByScopeAsync(IEnumerable<string> scopeNames);
        Task<Resources> GetAllResources();
    }
```

**Comment by brockallen** [comment]
In many systems it's less than 10. Some larger scenarios I'd say less than 50. But my original comment's point was that if you build an admin UI then you'd use a different abstraction to get at the data. Based on IdentityServer's needs, the API is designed appropriately (meaning there's a scenario where all the scopes are needed in one query).

**Comment by leastprivilege** [comment]
As Brock said - whenever we call the resource store, we actually need to retrieve all resources in question.
