### ISSUE TITLE
Assert Required Claims Flexibility

### ISSUE THREAD

**Issue by Lutando** [IdentityServer/IdentityServer4#820]
Some context of my issue over [here](https://github.com/aspnet/Security/issues/1126). The short of it, is that it seems I cannot `SignIn()` a user if the principal does not contain the name claim even if the principal has been specified to use a different claim type as the name claim.

In my case I would like to use the "preferred_username" as the principals name. I am pretty sure that the claims principal has the claim type of where the name came from as well, so this wouldn't be too much of  a fuss to do. Could something like checking for the name claim type rather than just doing a blanket check on the claim type "name" like it is now? The LOC in question is [here](https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/IdentityServerPrincipal.cs#L81) 

Thanks.

**Comment by leastprivilege** [comment]
We simply use a claim called name for the UI. Simply create a name claim with whatever content you want.

**Comment by Lutando** [comment]
OK. I guess all is good then. Thanks a lot.
