### ISSUE TITLE
"Unauthorized" while calling Web API (middle written in IdentityServer3.AccessTokenValidation

### ISSUE THREAD

**Issue by TarunVarian** [IdentityServer/IdentityServer4#821]
Hi Team,

We have migrated from IdentityServer3 to IdentityServer4. I wrote web api sample (which is getting called after fetching access token from IdentityServer) whose middleware is written in IdentityServer3.AccessTokenValidation in StartUp.cs as shown below:

 public void Configuration(IAppBuilder app)
        {
            var httpConfiguration = new HttpConfiguration();
            // This is where it "should" be
            GlobalConfiguration.Configure(WebApiConfig.Register);
            httpConfiguration.Formatters.Clear();
            httpConfiguration.Formatters.Add(new JsonMediaTypeFormatter());
            httpConfiguration.MapHttpAttributeRoutes();

            JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();
            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = ConfigurationItems.EndPointConfiguration.BaseAddress,
                RequiredScopes = new[] { "read", "write" },
                ValidationMode = ValidationMode.Both,
                //RequireHttpsMetadata = false,
                AuthenticationMode = AuthenticationMode.Active,
                AuthenticationType = "Bearer",
                PreserveAccessToken = true,
                DelayLoadMetadata = true,
                EnableValidationResultCache = true,
            });

            app.UseWebApi(WebApiConfig.Register());
            app.UseWebApi(httpConfiguration);
        }

We have now migrated to IdentityServer4 and when I pass IdentityServer4 access token to the Web API Layer and call an API (let's say identity Api ) as shown below, then I get UnAuthorized.

Web API:
[Authorize]
        [HttpGet]
        public dynamic Get()
        {
            var principal = User as ClaimsPrincipal;

            return from c in principal.Identities.First().Claims
                   select new
                   {
                       c.Type,
                       c.Value
                   };
        }

Sample calling above Web API by setting token to access token:

scription: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).

Source Error: 

Line 51: 
Line 52:             var response = client.GetAsync("identity").Result;
Line 53:             response.EnsureSuccessStatusCode();
Line 54: 
Line 55:             var claims = response.Content.ReadAsAsync<IEnumerable<Models.ViewClaim>>().Result;

Could you please let me know what could be the reason?

**Comment by leastprivilege** [comment]
You need to enable Katana logging in the API to see what's going on.

**Comment by TarunVarian** [comment]
Console Logging is added here. When I run the IdentityServer4 solution in console mode, see all the logs while calling IdentityServer and fetching access token. But when I call Web API, I simply gets UnAuthorized without anything in the console logging.

Is there any other logging which I need to enable?

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole();
            if (env.IsDevelopment())
                app.UseDeveloperExceptionPage();
            else
                app.UseExceptionHandler();

            app.InitialiseDatabase()
               .UseIdentityServer()
                // cookie middleware for temporarily storing the outcome of the external authentication
                .UseCookieAuthentication(new CookieAuthenticationOptions
                {
                    AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,
                    AutomaticAuthenticate = false,
                    AutomaticChallenge = false
                })
                .UseStaticFiles()
                .UseMvcWithDefaultRoute();

            app.UseJwtBearerAuthentication();
        }

**Comment by leastprivilege** [comment]
You need logging in the API - not IdentityServer.

**Comment by TarunVarian** [comment]
I looked into the internet and found somewhere that this issue is resolved by pointing to latest binary IdentityServer3.AccessTokenValidation version -  2.14.0. So I upgraded by binaries and its working fine now. Closing the issue

**Comment by samanevrc** [comment]
hi can you help me to solve my problem that is like you?
my web api sample that configed by IdentityServer3.AccessTokenValidation in StartUp.cs 
doest not even redirect to IdentityServer4 api

in my api i wrote this:

 var config = new HttpConfiguration();
            config.MapHttpAttributeRoutes();

            app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
            {
                Authority = "http://localhost:6001",
                RequiredScopes = new[] { "api" },

                DelayLoadMetadata = true
            });

            app.UseWebApi(config);

and i configed my identityserver4 to port 6001, 
but when i start both of them, my api/test does not redirect to identityserver4 for authenticate
please help me
