### ISSUE TITLE
Redirect to MVC client using Google Authenticaiton not working

### ISSUE THREAD

**Issue by gauravawr** [IdentityServer/IdentityServer4#822]
I am using Identity server 4 for authentication. When I use my IS4 login then after authentication of the user, user get redirected to the MVC client. But when  the user uses Google Authentication for the same MVC client. Then after google authentication user don't get redirected to the MVC client, the user stays on the authentication server's login page?

![google-redir-not-work](https://cloud.githubusercontent.com/assets/17614830/22995432/34398a92-f3cb-11e6-84e0-fb5aa4cfe63e.png)

**Comment by brockallen** [comment]
Did you debug into your code that triggers google logins?

**Comment by gauravawr** [comment]
Yes, after authentication from google, google redirected me back to the url I registered(localhost:myport, this is my local identity server). But then identity server does not redirect back to the mvc client.

**Comment by gauravawr** [comment]
When I looked info ExternalLoginCallback method in the account controller. The calls comes to this piece of code, where info is null, that's why I guess, it returns back to the login page again.

            var info = await _signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {
                return RedirectToAction(nameof(Login));
            }

Any suggestions why info can be null?

**Comment by brockallen** [comment]
Are you registering a temp cookie middleware for the external authentication? Is that scheme the same one the quickstarts uses?

**Comment by gauravawr** [comment]
Yes I did same as the quickstart does (https://identityserver4.readthedocs.io/en/release/topics/signin_external_providers.html, now its TBD).

Here the code from starup.cs and assemblies from my Identity server:

![google-redir-not-work-2](https://cloud.githubusercontent.com/assets/17614830/23092963/72d681a8-f5d6-11e6-9355-c53fac289611.png)

**Comment by gauravawr** [comment]
Another thing is that if I use var info = await HttpContext.Authentication.GetAuthenticateInfoAsync(Identity‌​ServerConstants.Exte‌​rnalCookieAuthentica‌​tionScheme); to get the info, then it works.

![google-redir-not-work-3](https://cloud.githubusercontent.com/assets/17614830/23093405/84db8234-f5e2-11e6-8759-defeb8644585.png)


1.From image avove image, this is the flow is given in the MS default mvc core template for /Account/ExternalLoginCallback, are we suppose to use it still or it has been changed?
2. And also the await _signInManager.GetExternalLoginInfoAsync(); is given in the MS default template. Does it not work anymore?

**Comment by zahik** [comment]
I had the same problem (waste on it 3 days)
and for me the solution was :
var CookieScheme = app.ApplicationServices.GetRequiredService<IOptions<IdentityOptions>>().Value.Cookies.ExternalCookieAuthenticationScheme;

and change :
SignInScheme = CookieScheme,
like here:
https://github.com/IdentityServer/IdentityServer4.Samples/issues/122
and here
http://stackoverflow.com/questions/42176017/using-iprofileservice-when-sign-in-by-google-oauth

@bobsum , you should update the samples NOT to use:
"SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme" - NOT GOOD.

**Comment by brockallen** [comment]
> and change : SignInScheme = CookieScheme,

Perhaps I'm missing what you mean here, but if this is setting the social middleware, then this is wrong. You don't want the social middleware to go directly to the main login cookie. That's why we use a 2nd middleware for external logins. 

> @brockallen , you should update the samples NOT to use: 
> "SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme" - NOT GOOD.

So I still don't follow.

**Comment by brockallen** [comment]
> And also the await _signInManager.GetExternalLoginInfoAsync(); is given in the MS default template. Does it not work anymore?

This is a feature of ASP.NET Identity, not the authentication system. Microsoft conflates the two without explaining how each layer works. Complain to them, as they need to be told to stop doing that.

**Comment by kuncevic** [comment]
Getting an error `No authentication handler is configured to authenticate for the scheme: idsrv.external` whatever I am using `var CookieScheme = app.ApplicationServices.GetRequiredService<IOptions<IdentityOptions>>().Value.Cookies.ExternalCookieAuthenticationScheme;` or just `IdentityServerConstants.DefaultCookieAuthenticationScheme`:

```
public void ConfigureServices(IServiceCollection services)
        {
            var connectionString = Configuration.GetConnectionString("DefaultConnection");
            var migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name;
            // Add framework services.
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(connectionString));

            services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

            services.AddMvc();

            // Add application services.
            services.AddTransient<IEmailSender, AuthMessageSender>();
            services.AddTransient<ISmsSender, AuthMessageSender>();

            services.AddIdentityServer()
                .AddTemporarySigningCredential()
                .AddConfigurationStore(builder =>
                    builder.UseSqlServer(connectionString, options =>
                        options.MigrationsAssembly(migrationsAssembly)))
                .AddOperationalStore(builder =>
                    builder.UseSqlServer(connectionString, options =>
                        options.MigrationsAssembly(migrationsAssembly)))
                .AddAspNetIdentity<ApplicationUser>();
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            var ientityServerUrl = Configuration.GetConnectionString("DefaultConnection");
            // this will do the initial DB population
            InitializeDatabase(app);

            app.UseCors("default");

            loggerFactory.AddConsole(LogLevel.Debug);
            app.UseDeveloperExceptionPage();

            app.UseIdentity();
            app.UseIdentityServer();

            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            app.UseJwtBearerAuthentication(new JwtBearerOptions()
            {
                Authority = ientityServerUrl,
                Audience = ientityServerUrl,

                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
                RequireHttpsMetadata = false,

                TokenValidationParameters = new TokenValidationParameters()
                {
                    ClockSkew = TimeSpan.Zero,
                    NameClaimType = ClaimTypes.Name,
                    RoleClaimType = ClaimTypes.Role
                },
            });

            app.UseGoogleAuthentication(new GoogleOptions
            {
                AuthenticationScheme = "Google",
                DisplayName = "Google",
                SignInScheme = IdentityServerConstants.DefaultCookieAuthenticationScheme,

                ClientId = "434483408261-55tc8n0cs4ff1fe21ea8df2o443v2iuc.apps.googleusercontent.com",
                ClientSecret = "3gcoTrEDPPJ0ukn_aYYT6PWo"
            });

            app.UseStaticFiles();
            app.UseMvcWithDefaultRoute();
        }
```

**Comment by dazinator** [comment]
I just hit this, when creating a vanilla `asp.net core` project that uses `individual user accounts`, with the `scaffolded` identity razor pages UI. The project worked out of the box, and it also worked when I added bitbucket external authentication, however when trying to bring `identity server 4` into the mix, after looking at the samples and docs, I was unable to get it to work.

Note the samples provided for using `identity server` with `asp.net core identity` don't appear to use the standard scaffolded UI's, instead the samples have custom UI and controller implementations - so this left me thinking perhaps this scenario still needs to be worked through / ironed out.
