### ISSUE TITLE
IdentityServer4 hang-up 

### ISSUE THREAD

**Issue by tedzhao** [IdentityServer/IdentityServer4#824]
Hi IdentityServer4er,

I created an IdentityServer4 demo with MS Dotnet core 1.1 and deploy to ubuntu 16.04. This demo uses memory users and works well in my local windows machine. 

After deploying to ubuntu, when try to login with some user, IdentityServer4 will hang-up. I checked the log:

> info: Microsoft.AspNetCore.Server.Kestrel[14]
> Connection id "0HL2M89T5U0QT" communication error.
> 
> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -32 EPIPE broken pipe

I have build nginx service behind Kestrel. 

The attached file is login form and click the Login, the request will be timeout(504)
![screen shot 2017-02-16 at 6 09 38 pm](https://cloud.githubusercontent.com/assets/6092595/23016896/269018c2-f473-11e6-96e3-b27b9722c992.png)

Looking forward to your reply!

**Comment by leastprivilege** [comment]
you probably need to take this problem to the Microsoft's Kestrel repo on github.
