### ISSUE TITLE
Configurable http scheme for identity server

### ISSUE THREAD

**Issue by sergik** [IdentityServer/IdentityServer4#826]
- [x] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem

We are using Identity Server and host it under the API gateway(KONG). Externally it published over https but under the gateway it is published over http. So applications refer Identity Server over https but requests to Identity Server comes as http requests. So we have an issue with metadata endpoint which was rendered with http based urls. To fix it I had to rewrite BaseUrlMidleware to provide correct scheme for identity server. But to reregister it I had to rewrite all the UseIdentityServer extension as well which is quite tricky to support during IdentityServer updates. 
Could this be fixed in other ways? Maybe in future releases BaseUrlMidleware could be written in more configurable way to not only use http request but use some scheme provider for example?  If it acceptable I can provide a pull request for it. Mb you have some better ideas how this situation could be fixed in better way?

**Comment by leastprivilege** [comment]
This is a standard ASP.NET Core concern - see here:

https://github.com/aspnet/Docs/issues/2384

**Comment by sergik** [comment]
Thanks a lot for your reply! ForwardedHeaders midleware fixed our issue.
