### ISSUE TITLE
Design Question: IdentityResources and ApiResources

### ISSUE THREAD

**Issue by aggieben** [IdentityServer/IdentityServer4#829]
@leastprivilege from the blog:

Why don’t `ApiResource` and `IdentityResource` share a common abstract class or interface? I’m finding in my implementation that having them not be covariant means I have to write a bit of code twice where it seems like once would suffice. Obviously one can avoid the issue by using `dynamic`, but that’s undesirable.

For example:
```C#
ViewBag.Resources = resources.IdentityResources
    .Select(s => new SelectListItem { Value = s.Name, Text = s.DisplayName })
    .Union(resources.ApiResources
        .Select(s => new SelectListItem { Value = s.Name, Text = s.DisplayName }));
```

instead of just:
```C#
ViewBag.Resources = resources
    .Select(s => new SelectListItem { Value = s.Name, Text = s.DisplayName });
```

**Comment by brockallen** [comment]
> Why don’t ApiResource and IdentityResource share a common abstract class or interface

Yea, @leastprivilege, why don't they? :P

**Comment by leastprivilege** [comment]
Maybe because this was never discussed? ;p  Scope is def. not the right base class from a domain modeling point of view...

**Comment by brockallen** [comment]
> Maybe because this was never discussed? ;p

haha, i was calling you out because we specifically did discuss it, and your argument against was the same one you said above. I still feel a base makes more sense, but i'm easy like sunday morning.

**Comment by leastprivilege** [comment]
So shall we have a common base class for resources - maybe with name, display name, description..more?

**Comment by aggieben** [comment]
That's kind of what I was thinking.

Also, one other thing that also struck me was the way that scopes in `IdentityResource`s and `ApiResource`s are treated differently - in the former, they're treated as though they automatically get one default scope with the same name as the resource, but with the latter, they're treated as though they have no scopes by default (which seems more intuitive to me).  Was that behavior by design, or just something that evolved when you were working on these changes?

**Comment by brockallen** [comment]
We did identify the overlapping/shared members during the design and development (thus my joking comments above), but we never took the time to factor them out.

**Comment by grahamehorner** [comment]
I was just asking myself this question 😜

**Comment by brockallen** [comment]
Added on dev.
