### ISSUE TITLE
IdentityServer4 add custom endpoint type

### ISSUE THREAD

**Issue by BlackMoon** [IdentityServer/IdentityServer4#83]
Hi all!

Is it possible to extend default endpoints' list with custom endpoint behaviour?

I would like to have another url for change password action, something like 

> connect/change

Thanks.

**Comment by leastprivilege** [comment]
sure - just add a route and controller - that's just normal MVC at this point.

**Comment by BlackMoon** [comment]
Not exactly.

I also want to see endpoint url in
1. .well-known/openid-configuration
2. use by different clients (console, web, api, etc.)

**Comment by leastprivilege** [comment]
Discovery is extensible. Check the discovery options.

**Comment by BlackMoon** [comment]
> Discovery is extensible. Check the discovery options.

You mean that I can inject custom behaviour in 
`DiscoveryEndpoint.ProcessAsync(IdentityServerContext context)`

like `if (context.HttpContext.Request.Path.Value.EndsWith("/jwks"))
            {
                return ExecuteJwksAsync(context.HttpContext);
            }
            else
            {
                return ExecuteDiscoDocAsync(context.HttpContext);
}`
