### ISSUE TITLE
[Question] Correct behavior after logout from another JS client

### ISSUE THREAD

**Issue by apacherose** [IdentityServer/IdentityServer4#834]
Hello,
my setup is quite the following:
- Identity Server as open-id provider
- two JS clients - js01 and js02 working with the same API resource;
- one api resource
- authentication using the implicit flow;

Each client has custom token expiration and AllowOfflineAccess is enabled, so tokens are renewed.
However, when a user logouts from one of the JS client application, the token renewal in the other JS client comes to an end, which I suppose is the correct behavior.

My problem is that even the user logouts from the first js client, he is still able to do calls to the api resource from the second js client (until the access token really expires, of course). Is it OK by protocol and specifications?

My question: How should I react on this use-case if I want to prevent users in second client app from doing any more calls to the api resource?
I know there is event - Oidc.UserManager.events.addAccessTokenExpired(callback), but it is fired after the access token issued for that client really expires. Should I use this event?

Thank you in advance.

**Comment by brockallen** [comment]
> Each client has custom token expiration and AllowOfflineAccess is enabled

That's incompatible with implicit flow. If you're requesting offline_access and it's somehow working for you, then it's a bug.

> My problem is that even the user logouts from the first js client, he is still able to do calls to the api resource from the second js client (until the access token really expires, of course). Is it OK by protocol and specifications?

A user's session is unrelated to the access token's lifetime.

**Comment by apacherose** [comment]
Yes, I understand that refresh_tokens are not supported in that kind of flow.
By saying token renewal I meant that I've enabled automaticSilentRenew in the js clients - so periodically a call to the Identity Server is made. As a result the tokens in clients are changed - I can see the net calls and the change of the tokens in the session storage of the browser. That's why I've falsely understood it as a token refresh :)

Anyway, as far as I understand, each client should handle token expiration by its own, regardless of whether  the user has a session in another client or not.

**Comment by brockallen** [comment]
> Anyway, as far as I understand, each client should handle token expiration by its own, regardless of whether the user has a session in another client or not.

Yep.
