### ISSUE TITLE
Calling connect/identitytokenvalidation for Identityserver4

### ISSUE THREAD

**Issue by TarunVarian** [IdentityServer/IdentityServer4#838]
Hi Team,

Earlier we were using IdentityServer3 and I created verification sample for identitytokenvalidation by calling identityserver3/varian/sts/connect/identitytokenvalidation  endpoint as shown in below code:

var client = new HttpClient();
var response = client.GetAsync(ConfigurationItems.EndPointConfiguration.IdentityTokenValidationEndpoint
                                           + "?token=" + token +
                                           "&client_id=" + 		ConfigurationItems.ClientConfiguration.ImplicitFlow_ClientId)
                .Result;
where token  is the token returned from IdentityServer3. We are now moving to IdentityServer4 and when pointing my IdentityTokenValidationEndpoint to our IdentityServer4/connect/identitytokenvalidation, I am getting 404 in the response. 

Can you please let me know if connect/identitytokenvalidation  endpoint exist in IdentityServer4?

**Comment by leastprivilege** [comment]
No - it does not exist anymore. What's the use case?

**Comment by TarunVarian** [comment]
Thanks Dominic for the update.
