### ISSUE TITLE
"Step by Step" IdentityServer4 install tutorial

### ISSUE THREAD

**Issue by balivo** [IdentityServer/IdentityServer4#84]
Hi!

There's any tutorial explaining the steps to use IdentityServer4?

**Comment by alexsandro-xpt** [comment]
+1

**Comment by leastprivilege** [comment]
No. But its just a normal Web App. We'll have more docs when we get closer to the release.

**Comment by balivo** [comment]
It's "stable" for production use? Angular cliente, web api...

**Comment by leastprivilege** [comment]
It is as stable as the platform it runs on - do you get that hint? ;)

**Comment by balivo** [comment]
Tks for answer @leastprivilege... Now I'm looking at samples for configuration process...
