### ISSUE TITLE
Revoke/disable user for specific client(s)

### ISSUE THREAD

**Issue by Blastnsmash** [IdentityServer/IdentityServer4#841]
By default, it looks like all users can use all clients. What is the correct way to exclude certain users from using certain clients or even reducing claims based on the client the user is logging in through. 

If I had to guess, IsActiveAsync implementation from IProfileService looks like a good place. Appropriate?

For example, 

```
 public Task IsActiveAsync(IsActiveContext context)
        {
            if(context.Client.ClientName == "roclient")
            {
                context.IsActive = false;
            }
            else
            {
                context.IsActive = true;
            }          

            return Task.FromResult(0);
        }
```

Is there a more correct way to do this?

**Comment by brockallen** [comment]
Do an authorization check in the client.

**Comment by Blastnsmash** [comment]
Could you or someone else expand on that and give an example?  I'm not entirely sure what an authorization check means on the client side.

**Comment by brockallen** [comment]
IdentityServer is not designed to do authorization around which user is allowed in which application or API. You might be able to bend it to your will, but, as I said, that's not what it's designed for.

**Comment by KeithBarrows** [comment]
Try using a resource scope with appropriate claims that identifies which
app the user has permissions for?
https://github.com/IdentityServer/IdentityServer3/issues/1784 might help
point out a solution.

As far as an auth check on the client side:  Build an auth attribute
handler and decorate your controller or actions with it or use a Mediator
pattern pipeline with pre-processing in each of your actions.  Inside the
handler (or pre-processor) you should be able to determine if the user has
access to the resource.  I am thinking of a SaaS solution with multiple
modules the client buys separately.



[image: --]
Keith Barrows
[image: https://]about.me/kbarrows
<https://about.me/kbarrows?promo=email_sig>
*The truly free individual is free only to the extent of his own
self-mastery. While those who will not govern themselves are condemned to
find masters to govern over them.*  -- Socrates

**Comment by Blastnsmash** [comment]
Thank you both very much for the response. 
There seems to be several ways to bend the product to my will so to speak. I mainly wanted feedback to see if I wasn't overlooking something obvious.

**Comment by leastprivilege** [comment]
Scopes are unrelated to user authorization.


-------
Dominick Baier
