### ISSUE TITLE
IdentityServer4 and API in same Project

### ISSUE THREAD

**Issue by windischb** [IdentityServer/IdentityServer4#842]
I try to create an Admin UI for managing Users, Clients, Resources,...
My Idea was to use a Angular SPA -> http://localhost:5000/admin

I use the oidc-client to handle the login for the SPA.
There are a few Api Controllers for CRUD Operations.

How can i "limit" the Api Controllers to only use the token for authentication and not the Cookie which i get from Identityserver??
Or is this at all a bad decision to put these two things together in one Project?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by Jenan** [comment]
Hello @windischb, I have wondered about creating the admin ui for IdSrv too, do you want to cooperate with me?
