### ISSUE TITLE
 HttpContext.Authentication.GetTokenAsync("access_token") return null

### ISSUE THREAD

**Issue by stanleychen** [IdentityServer/IdentityServer4#843]
Get Access_Token from the identity server itself return null after login successfully. Are there anyway to make it work?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by michael-freidgeim-webjet** [comment]
> StackOverflow  questions and answers can be easily found by search engines

Actually Google now often returns Github issues before Stackoverflow (but I agree with your recommendation in general)

**Comment by DoubleExposure** [comment]
Michael, did you resolve this? My login is successful but 
await ViewContext.HttpContext.Authentication.GetTokenAsync("access_token")
returns null

**Comment by michael-freidgeim-webjet** [comment]
@DoubleExposure , sorry, it was many similar issues, I don't remember how particular one was resolved.
Sometimes clearing browser cookies helps.

**Comment by kazantsev-nikita** [comment]
@DoubleExposure I have the same problem. Have you solved this?

**Comment by DoubleExposure** [comment]
I do not remember this issue but I would think that you should make sure that you are running in Hybrid flow  (code id_token) so that an access_token is created.    You can be an authenticated user and not have an access token so make sure you are running Hybrid and not Implicit flow
