### ISSUE TITLE
supported .net core version

### ISSUE THREAD

**Issue by paulvanbladel** [IdentityServer/IdentityServer4#845]
The readme says:
IdentityServer is built against ASP.NET Core 1.1.0 using the 1.0.0-preview2-003131 SDK.

Please consult this page:
https://github.com/dotnet/core/blob/master/release-notes/download-archive.md
I believe 1.0.0-preview2-003131 SDK is .net core 1.0.1 and not 1.1
Did I miss something?

**Comment by leastprivilege** [comment]
This is the combination of frameworks and tooling we use.

As soon as VS 2017 is released, we will update to the RTM tooling.
