### ISSUE TITLE
Required Scopes and Consent

### ISSUE THREAD

**Issue by pierslawson** [IdentityServer/IdentityServer4#854]
I have a question about scopes and consent. 

I can see how a scope can be marked as required within IdentityServer, which means if that scope is requested by any client it will be shown as required on the Consent screen. 

Is it possible to have a scope that is required by one client but for it to be optional for a different client? Is that even a sensible requirement?

For example, one client may absolutely need "email" in order to function but a different client will use it if available, but can get by without. My current understanding is that I would have to mark this as not required within IdentityServer, then have the client that needs "email" check for it within the OnTicketReceived event (probably displaying an error message to the user). It would be better if the client could specify the scope was required as the OIDC process started or I could configure the scopes differently for each client in IdentityServer.

**Comment by brockallen** [comment]
I think the internal complexity would be very high, so the easy workaround would be to create different scopes.

**Comment by pierslawson** [comment]
OK, so no easy solution. For some scopes it would look a bit clumsy having two (e.g. email and perhaps email_required). 

I suppose one option is to code it myself within the consent controller for particular clients.

Thanks
