### ISSUE TITLE
Let the issued access token(JWT) invalid instantly

### ISSUE THREAD

**Issue by atpyk** [IdentityServer/IdentityServer4#856]
Idsrv4 will issue an access token(JWT) when login success; the issued token's expired time is 15 days and will be kept on client side.
In this time, if disable this account, I prefer to let the issued token invalid instantly. 

Could you have any suggestion for it? Thanks.

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io

**Comment by atpyk** [comment]
Thanks for your help!
