### ISSUE TITLE
jwks endpoint doesn't return public key exponent or modulus - breaks PKCE

### ISSUE THREAD

**Issue by channeladam** [IdentityServer/IdentityServer4#86]
In DiscoveryEndpoint.cs, there is a todo (due to the port to core) to return the public key exponent and modulus.

Without this, IdentityServer.OidcClient throws a null ref exception as it is required for validation.

I have a fix that uses Portable.BouncyCastle if you would like it.

**Comment by leastprivilege** [comment]
We will fix that once we start the RC2 work - probably next week.

**Comment by leastprivilege** [comment]
I did a quick fix in `beta2-update2` - give it a try.
