### ISSUE TITLE
feature(baseUrl): Allow to set a baseurl before UseIdentityServer()

### ISSUE THREAD

**Issue by rmja** [IdentityServer/IdentityServer4#860]
Currently, the `BaseUrlMiddleware` is always run when using UseIdentityServer() [here](https://github.com/IdentityServer/IdentityServer4/blob/ab09cda7d636cf154986b1cc08e702d45ffae478/src/IdentityServer4/Configuration/IdentityServerApplicationBuilderExtensions.cs#L19)

However, when IdentyServer is run behind a reverse proxy which handles https->http translation, then the baseUrl (used in the discovery document) is incorrectly set with http url's instead of https urls. It would be neat if the `BaseUrlMiddleware` only called `SetIdentityServerOrigin()` if it was not already set. In that way it would be possible to insert a middleware before UseIdentityServer() which could set the correct base url (with https) to use for identity server.

**Comment by leastprivilege** [comment]
You need middleware in front of identity server that sets the right hostname/protocol etc...

https://identityserver4.readthedocs.io/en/release/topics/deployment.html

**Comment by rmja** [comment]
Ahh yes, I missed that. Thanks.

**Comment by JanBN** [comment]
@rmja How did you solve this ? What middleware. Don't get the link provided by @leastprivilege 
Thank you

**Comment by rmja** [comment]
I basically have the following before `UseIdentityServer()`:
```
app.UseForwardedHeaders(new ForwardedHeadersOptions()
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedHost | ForwardedHeaders.XForwardedProto
            });
```
