### ISSUE TITLE
Use case: Multiple applications per single Identity Server

### ISSUE THREAD

**Issue by carol-braileanu** [IdentityServer/IdentityServer4#862]
Hello,

We have a scenario in which we want to use Identity Server to give access to multiple applications to a set of APIs. Each Application has one or more clients, and its own roles and claims (ex: a user can be administrator for one of the applications and regular customer for others). 

The login flow would be as follows:
* User requests login for client X
* IdentityServer proceses the login and checks the user's roles for the application to which Client X belongs. It then adds to the generated token only those claims that the user has according to the roles for Client X's parent aplication.

I tried to figure out a way in which I could achieve this using the built-in functionality, but I could not find anything. If there is something that I am missing please let me know, but it seems that multiple parent applications are not supported. After some research I came to the conclusion that the following changes are needed:

* Create an `Application` class
* Create a custom `IdentityUserRole` class that also contains the application ID
* Create a custom `Client` class that also references the application to which it belongs
* Create a custom `IProfileService' class that will only return the claims for user's roles in the application to which the current Client belongs

All of these are doable, but the problems come when I am trying to extend the `Client` class, and add an extra column. There is no way to specify my custom implementation of the class in the configuration of IdentityServer. Besides that, because `Client` is part of the `ConfigurationDbContext`, and the derived class is part of my own DB Context, the migrations are not generated properly.

It would be nice to have something like `ConfigurationDbContext<TClient>` and to be able to specify the custom `ConfigurationDbContext` when configuring IdentityServer like so: `AddConfigurationStore<ConfigurationDbContext<TClient>>(connStr, options)`

**Comment by leastprivilege** [comment]
In short: you don't.

IdentityServer emits identity - no permission. Check the permission in the app/api

https://leastprivilege.com/2016/12/16/identity-vs-permissions/

**Comment by carol-braileanu** [comment]
Hi, and thanks for your response. I understand the idea that Identity Server is just a token provider service. However, I wasn't talking about setting permissions, but rather to be able to host multiple applications on a single IdentityServer. We would be able to define roles on a "per-application" basis, and when a token is generated to only contain the claims for the app for which it is requested.
Example: 
* I have 2 services, IdentityServer and TranslationServer and 2 apps running on them: 
     * App1 for which I have roles: Administrator (claims "edit-translation") and Customer. App 1 has 2 clients:
             * Web App 1
             * Mobile App 1
     * App2 for which I am only a customer, and only has a "Web app 2" client

When I request a login from Web App 1 or Mobile App 1 I want to have returned a token that contains the "edit-translation" claim. When I request a login from Web App 2 I want to have a token that doesn't contain "edit-translation".

With the current situation, I can only be an Administrator for both apps, or a customer for both apps.

**Comment by leastprivilege** [comment]
No - what I said is that IdentityServer emits identity information - not permissions. Your applications check the permissions based on the identity.

That said - you have the client id in the profile service - so you can emit whatever claim you want.

**Comment by thijscrombeen** [comment]
I have a question on what you said:
"IdentityServer emits identity - no permission. Check the permission in the app/api"

Do you have an example of how to extend the User.Identity to add permissions specific for this API? 
Do we extend the authorize attribute to get the permissions for the user / client from our API DB or is there some other hook to use?

**Comment by carol-braileanu** [comment]
Try to use something like in the following example:
https://youtu.be/5OUQZAvxZuA?t=30m40s

**Comment by brockallen** [comment]
> Do you have an example of how to extend the User.Identity to add permissions specific for this API?

I think you're missing the point. User.Identity models the identity of the user, which should be different than the user's permissions. As for how you check authorization, that's up to your app.

**Comment by brockallen** [comment]
Are we good to close this, or do we have something pending for this issue?

**Comment by carol-braileanu** [comment]
Hello,

Yes, it's ok to close. I read your article on Identity vs Permissions and i understood your point.

Thank you

**Comment by erickvierag** [comment]
j
