### ISSUE TITLE
Access Token & Refresh Token storage best practice

### ISSUE THREAD

**Issue by pierslawson** [IdentityServer/IdentityServer4#863]
I have a couple of questions after working through the "Switching to Hybrid Flow and adding API Access back" quick start.

I thought one of the benefits of Hybrid Flow was that it avoided the Access Token and Refresh Tokens from being passed to the client via the browser channel. However ,the quickstart appears to show those tokens being saved to a cookie by setting SaveToken = true and then using HttpContext.Authentication.GetTokenAsync to retrieve the tokens when needed. 

Is this considered best practice or just a shortcut in order to demonstrate the flow? 

If I wanted to capture the tokens and hold them server side only I presume I could set SaveToken to false. If I did this, which event on OpenIdConnectOptions should be handled in order to retrieve the tokens? Would I have to hit the TokenEndpoint myself?

Thank you

**Comment by leastprivilege** [comment]
It is definitely not a "bad practice" from a security point of view at least. The cookie is signed and encrypted.

The downside is that the cookie gets bigger.

I can't remember which events you need to use to take over storage yourself - you need to poke around yourself.

**Comment by pierslawson** [comment]
Thanks for the information.

Changing to SaveToken = false prevents the tokens being saved to the cookie, but the downside is that the identity token is also dropped, which makes the Logout flow more difficult to implement.

I should have played around sooner. Handling `OnTokenResponseReceived` looks like the event I need. I will investigate further to see if I can keep Savetoken = true but use this event to both extract the Access and Refresh tokens and prevent them from being put into the cookie.

Thanks again!

**Comment by pierslawson** [comment]
So handling OnTokenResponseReceived does allow me to read and store away the Access Token and Refresh Token. I can also set the RefreshToken property of TokenEndpointResponse to null which prevents it from being stored in the cookie. However, setting the AccessToken to null causes an error (which can be caught using the OnAuthenticationFailed handler):

> IDX10336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.

This error is raised by the ValidateTokenResponse extension method in OpenIdConnectProtocolValidator. It is called as part of the HandleRemoteAuthenticateAsync in the OpenIdConnectHandler class whilst dealing with Authorization Codes. Unfortunately there is no where to hook into the process between the validation call and the SaveTokens call.  SaveTokens will blindly save all tokens it can find (AccessToken, IdToken and RefreshToken). The only workaround would be to hande the Authentication Code myself as the existing code does not revalidate the tokens if a HandledCodeRedemption is returned from the OnAuthorizationCodeReceived event handler.

So, as it stands, the Access Token will always get saved into the cookie unless you use a brittle workaround. I think I'll just live with the Access Token being saved!

BTW This has been raised as an issue already

https://github.com/aspnet/Security/issues/1101

**Comment by leastprivilege** [comment]
I would like to see a special event that just deals with token storage. And not trial & erroring through the other events to find the right place in time to manipulate their context.

Maybe you should open a new issue for that.
