### ISSUE TITLE
Redirect After ExternalLoginCallback not behaving as expected

### ISSUE THREAD

**Issue by lenniebriscoe** [IdentityServer/IdentityServer4#865]
I have merged two of the Quickstarts (6&8) together to allow me to use the EF database for Asp.net Identity and also the IdentityServer Configuration database. I have a single client using asp.net mvc client (Microsoft.Owin.Security.Cookies and Microsoft.Owin.Security.OpenIdConnect) using UseOpenIdConnectAuthentication and Windows Authentication as an external provider i.e. the application allows internal Windows Authenticated users and external users via an mvc IdentityServer login page.

The identity server is running under IISExpress with both Windows and Forms Authentication enabled.

If I connect my client straight to the Quickstart8 Identity Server I can login via windows and externally successfully.

If I connect my client to my merged IdentityServer project the Redirect at the end of the ExternalLoginCallback seems to fail and the Login Action on the Account Controller gets called again. I have checked the code and database configuration and all seems the same as the Quickstart. I'm struggling to debug why the redirect back to the login page is happening after a successful ChallengeResult + SignInAsync in the ExternalLogin Action and then successful SignInAsync + SignOut in the ExternalLoginCallback function. The redirect Url looks the same as the working IdentityServer version. The only difference I can see is that I'm not using the userStore to find a user or auto provision. 

Would you be able to shed any light please? 

**Update 2**
After enabling logging I noticed the following in the output:

SELECT TOP(1) [e].[Id], [e].[AccessFailedCount], [e].[ConcurrencyStamp], [e].[Email], [e].[EmailConfirmed], [e].[LockoutEnabled], [e].[LockoutEnd], [e].[NormalizedEmail], [e].[NormalizedUserName], [e].[PasswordHash], [e].[PhoneNumber], [e].[PhoneNumberConfirmed], [e].[SecurityStamp], [e].[TwoFactorEnabled], [e].[UserName]
FROM [AspNetUsers] AS [e]
WHERE [e].[Id] = @__get_Item_0
**IdentityServer4.ResponseHandling.AuthorizeInteractionResponseGenerator:Information: Showing login: User is not active**
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 920.2148ms 302 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:5000/account/login?returnUrl=%2Fconnect%2Fauthorize%2Flogin%3Fclient_id%3Dhca.web.milestonesandoutputs%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A60590%252Fsignin-oidc%26response_mode%3Dform_post%26response_type%3Did_token%26scope%3Dopenid%2520profile%26state%3DOpenIdConnect.AuthenticationProperties%253DH2XA-wvFfOWI157BmSkS6HHqqJA4EwrhstVwnXC0nuliNpqCGzwSgZPCSLoLCbQF0nWIL2Ay5P-FJuv4lRqmZZMYVWBN-gR8WmUw1SO7WOIB8PH4QrNPdZeSaFbDo5Dfe3M5bLOPOShakQkqxM_TqUATsgf54rsYLl7DSy6zuvBQ0Sjsoad2_ZbH1INAwQF5mcCaN75LQf_w0C-kLHIjHg%26nonce%3D636244136043515720.MWUwNGZmZmEtNzljYi00OWY5LTllNmQtZDEwYjk0ZTczN2ZjY2FlOWZlMzAtYTJiZi00Y2RhLTgzNTQtZGNjMDYwYzliM2Jj  
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware:Information: HttpContext.User merged via AutomaticAuthentication from authenticationScheme: Identity.Application.
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware:Information: AuthenticationScheme: Identity.Application was successfully authenticated.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method HCAConnect.Source.Controllers.AccountController.Login (HCA.Connect.Web) with arguments (/connect/authorize/login?client_id=hca.web.milestonesandoutputs&redirect_uri=http%3A%2F%2Flocalhost%3A60590%2Fsignin-oidc&response_mode=form_post&response_type=id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3DH2XA-wvFfOWI157BmSkS6HHqqJA4EwrhstVwnXC0nuliNpqCGzwSgZPCSLoLCbQF0nWIL2Ay5P-FJuv4lRqmZZMYVWBN-gR8WmUw1SO7WOIB8PH4QrNPdZeSaFbDo5Dfe3M5bLOPOShakQkqxM_TqUATsgf54rsYLl7DSy6zuvBQ0Sjsoad2_ZbH1INAwQF5mcCaN75LQf_w0C-kLHIjHg&nonce=636244136043515720.MWUwNGZmZmEtNzljYi00OWY5LTllNmQtZDEwYjk0ZTczN2ZjY2FlOWZlMzAtYTJiZi00Y2RhLTgzNTQtZGNjMDYwYzliM2Jj) - ModelState is Valid

So, it seems to be looking for the user in the Asp.net Identity database, but since it's an external user it wont be in there. Its therefore redirecting to the Login page. I've clearly missed some configuration somewhere....

**Update 1: Cookie differences After 302 from ExternalLoginCallback**

**Working Response 200 -** http://localhost:5000/connect/authorize/login?
idsrv.session=bf7512bea9d3954657e97a1caa113dcc
idsrv=CfDJ8P_ixu_H3w1NjY2-qnTCzCVUQUnFvtUYMRfL-........
OpenIdConnect.nonce.fqL4Bll1ZCiR1Qik0JF9ekXXEUQ5.....

**Not Working Response 302 -** http://localhost:5000/connect/authorize/login?
.AspNetCore.Identity.Application=CfDJ8P_ixu_H3w1NjY2....
Identity.Application.session=738a49b8e9a868a9520b427aadf8a830
OpenIdConnect.nonce.fqL4Bll1ZCiR1Qik0JF9ekXXEUQ5.....

Have I lost some IdentityServer Cookies ?

**Client Configuration**
```
public void Configuration(IAppBuilder app) {
              JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

			app.UseCookieAuthentication(new CookieAuthenticationOptions {
				AuthenticationType = "Cookies"
			});

			app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions {
				ClientId = "hca.web.milestonesandoutputs",
				Authority = "http://localhost:5000/",
				RedirectUri = "http://localhost:60590/signin-oidc",
				ResponseType = "id_token",
				Scope = "openid,
				UseTokenLifetime = false,
				SignInAsAuthenticationType = "Cookies",
			});
		}

```
**Server Configuration**
```
public void ConfigureServices(IServiceCollection services) {
			var identityConnectionString = Configuration.GetConnectionString("HCAConnectIdentity");
			var configurationConnectionString = Configuration.GetConnectionString("HCAConnectConfiguration");

			services.AddDbContext<IdentityDbContext>(options => options.UseSqlServer(identityConnectionString));

			services.AddIdentity<ApplicationUser, IdentityRole>()
				.AddEntityFrameworkStores<IdentityDbContext>()
				.AddDefaultTokenProviders();

			services.AddMvc();

			services.AddTransient<IEmailSender, AuthMessageSender>();
			services.AddTransient<ISmsSender, AuthMessageSender>();
			services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
			services.AddSingleton<IExternalUserStore, ExternalUserStore>();


			var migrationsAssembly = typeof(IdentityDbContext).GetTypeInfo().Assembly.GetName().Name;

			services.AddIdentityServer()
				//TODO: Generate Public\Private Keys for signing JWTs. This is for development only.
				.AddTemporarySigningCredential()

				//.AddTestUsers(Config.GetUsers())
				.AddConfigurationStore(builder =>
					builder.UseSqlServer(configurationConnectionString, options =>
						options.MigrationsAssembly(migrationsAssembly)))
				.AddOperationalStore(builder =>
					builder.UseSqlServer(configurationConnectionString, options =>
						options.MigrationsAssembly(migrationsAssembly)))
				.AddAspNetIdentity<ApplicationUser>();
		}

		public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) {
			loggerFactory.AddConsole(LogLevel.Debug);
			app.UseDeveloperExceptionPage();

			app.UseIdentity();
			app.UseIdentityServer();

			app.UseCookieAuthentication(new CookieAuthenticationOptions {
				AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,

				AutomaticAuthenticate = false,
				AutomaticChallenge = false
			});


			app.UseStaticFiles();
			app.UseMvcWithDefaultRoute();

			app.UseForwardedHeaders(new ForwardedHeadersOptions {
				ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
			});

		}

```
**Server ExternalLogin Handling**
```
[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> ExternalLogin(string provider, string returnUrl = null) {
			// Request a redirect to the external login provider.
			var redirectUrl = Url.Action("ExternalLoginCallback", new { ReturnUrl = returnUrl });
			// windows authentication is modeled as external in the asp.net core authentication manager, so we need special handling
			if (AccountOptions.WindowsAuthenticationSchemes.Contains(provider)) {
				// but they don't support the redirect uri, so this URL is re-triggered when we call challenge
				if (HttpContext.User is WindowsPrincipal) {
					var props = new AuthenticationProperties();
					props.Items.Add("scheme", HttpContext.User.Identity.AuthenticationType);

					var id = new ClaimsIdentity(provider);
					id.AddClaim(new Claim(ClaimTypes.NameIdentifier, HttpContext.User.Identity.Name));
					id.AddClaim(new Claim(ClaimTypes.Name, HttpContext.User.Identity.Name));

					await HttpContext.Authentication.SignInAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme, new ClaimsPrincipal(id), props);

					return Redirect(redirectUrl);
				} else {
					// this triggers all of the windows auth schemes we're supporting so the browser can use what it supports
					return new ChallengeResult(AccountOptions.WindowsAuthenticationSchemes);
				}
			} else {
				// start challenge and roundtrip the return URL
				var props = new AuthenticationProperties {
					RedirectUri = returnUrl,
					Items = { { "scheme", provider } }
				};
				return new ChallengeResult(provider, props);
			}

		}

		//
		// GET: /Account/ExternalLoginCallback
		[HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> ExternalLoginCallback(string returnUrl = null, string remoteError = null)
        {
			// read external identity from the temporary cookie
			var info = await HttpContext.Authentication.GetAuthenticateInfoAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);
			var tempUser = info?.Principal;
			if (tempUser == null) {
				throw new Exception("External authentication error");
			}

			// retrieve claims of the external user
			var claims = tempUser.Claims.ToList();

			// try to determine the unique id of the external user - the most common claim type for that are the sub claim and the NameIdentifier
			// depending on the external provider, some other claim type might be used
			var userIdClaim = claims.FirstOrDefault(x => x.Type == JwtClaimTypes.Subject);
			if (userIdClaim == null) {
				userIdClaim = claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
			}
			if (userIdClaim == null) {
				throw new Exception("Unknown userid");
			}

			// remove the user id claim from the claims collection and move to the userId property
			// also set the name of the external authentication provider
			claims.Remove(userIdClaim);
			var provider = info.Properties.Items["scheme"];
			var userId = userIdClaim.Value;

			var additionalClaims = new List<Claim>();

			// if the external system sent a session id claim, copy it over
			var sid = claims.FirstOrDefault(x => x.Type == JwtClaimTypes.SessionId);
			if (sid != null) {
				additionalClaims.Add(new Claim(JwtClaimTypes.SessionId, sid.Value));
			}

			// if the external provider issued an id_token, we'll keep it for signout
			AuthenticationProperties props = null;
			var id_token = info.Properties.GetTokenValue("id_token");
			if (id_token != null) {
				props = new AuthenticationProperties();
				props.StoreTokens(new[] { new AuthenticationToken { Name = "id_token", Value = id_token } });
			}

			// issue authentication cookie for user
			await HttpContext.Authentication.SignInAsync(CryptoRandom.CreateUniqueId(), userId, provider, props, additionalClaims.ToArray());

			// delete temporary cookie used during external authentication
			await HttpContext.Authentication.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);

			// validate return URL and redirect back to authorization endpoint
			if (_interaction.IsValidReturnUrl(returnUrl)) {
				return Redirect(returnUrl);
			}

			return Redirect("~/");
		}
```

**Comment by brockallen** [comment]
I have a customer who needs this exact same setup -- when I am working on their code, I'll confirm this combination works, and report back. It will be next week sometime.

**Comment by lenniebriscoe** [comment]
See update (2) above. After enabling Trace logging it seems to be looking for the user in the Asp.net Identity database, but since it's an external user it wont be in there. Its therefore redirecting to the Login page. I've clearly missed some configuration somewhere....

**Comment by brockallen** [comment]
Ah yes, that makes sense -- the user is not in the DB. Normally the expectation is that, even for external users, you have some record of them in your user DB. Sounds like you either need to provision the users in the DB, or alter the IProfileService to better suit your scenario.

**Comment by lenniebriscoe** [comment]
Thanks. Amusingly the auto-provisioning code I removed caused the problem. So I've added it back in with some LDAP handling to get more information about the subject before I persist it to the IdentityDB. Apparently System.DirectoryServices hasn't been written yet so I had to use a 3rd party .net core package ("Novell.Directory.Ldap.NETStandard"):
```
			// check if the external user is already provisioned
	        var user = await _userManager.FindByLoginAsync(provider, userId);
			if (user == null) {
				// this simply auto-provisions a new external user. Another common approach is to start a registration workflow first
				var externalUser = await _externalUserStore.FindByExternalProviderAsync(provider, userId);
				user = new ApplicationUser(externalUser);
				await _userManager.CreateAsync(user);
			}
```

The critical bit was using the correct Id for the subject when Signing them in as the EntityFramework query looking at the AspNetUsers table is looking for the Primary key ID value. 

```
// issue authentication cookie for real user
await HttpContext.Authentication.SignInAsync(user.Id, userId, provider, props, additionalClaims.ToArray());
```

Cheers

**Comment by brockallen** [comment]
All set then -- we can close?

**Comment by lenniebriscoe** [comment]
Yes yes. Many thanks

**Comment by vijay2358** [comment]
Hello lenniebriscoe,

what was the final fix? - is that working windows/external login from EF-AspNetIdentity  DB

**Comment by exlnt** [comment]
@lenniebriscoe Can you please share your code for adding the external user into the local Asp.Net Identity store? I am in the exact same scenario. After Google & MS logins, my app keeps redirecting user to the Identity server login page and not back to the original client app.

**Comment by lenniebriscoe** [comment]
@vijay2358 and @exlnt it did indeed work as per my comments above. I needed to provision the users in the DB. You may want to alter the IProfileService to better suit your scenario. I have moved on from that role, so no code available i'm afraid.

**Comment by sniperwolfpk5** [comment]
@lenniebriscoe I have exact same scenario but I will deny user if it is not exists in local DB. I would like to give a message to user that you are not allowed contact administrator. How can I give error message to user rather than throw an exception

**Comment by sniperwolfpk5** [comment]
Why we need provision of user in local DB?

**Comment by lenniebriscoe** [comment]
@sniperwolfpk5 if your workflow is to deny users who do not exist in the local DB then you can create your own implementation of the IProfileService which returns IsActive = False if they don't exist in the database:
[http://docs.identityserver.io/en/latest/reference/profileservice.html](ProfileService). If they do exist they this profile service will return their appropriate details.
