### ISSUE TITLE
CustomEntries vs DiscoveryDocumentResult

### ISSUE THREAD

**Issue by beauceant** [IdentityServer/IdentityServer4#866]
#Hi all,
I aim to expose a custom endpoint in the discovery document, but I can't figure out how to prepend the ***IdentityServer BaseUrl*** to the route I configured and obtain its absolute url fashion. As far as I can grasp, the default endpoints get "enriched" with ***that*** piece of information on a per-request basis, every time the discovery endpoint gets hit:

```c#
// /IdentityServer4/Endpoints/DiscoveryEndpoint.cs#Ln78
var baseUrl = context.GetIdentityServerBaseUrl().EnsureTrailingSlash();
// [..]
// /IdentityServer4/Endpoints/DiscoveryEndpoint.cs#Ln177
document.authorization_endpoint = baseUrl + Constants.ProtocolRoutePaths.Authorize;
```
On the other end (the "end" relevant to `CustomEntries`), the same treatment isn't applied:

```c#
// /IdentityServer4/Endpoints/Results/DiscoveryDocumentResult.cs#Ln33
jobject.AddDictionary(CustomEntries);
// my custom entries look like: [{"key": "expulsion_endpoint", "value": "/connect/expulsion"}]
```
Since `DiscoveryClient` fails in processing a document with an `*_endpoint` whose url isn't absolute (error message `Malformed endpoint: /connect/expulsion`) and since the context is there (`DiscoveryDocumentResult.ExecuteAsync`) to be used, would it be feasible to prepend the IdentityServer baseurl for each endpoint entry in the `CustomEntries`  dictionary while rendering?

```c#
// so that my custom entries might then be rendered like:
// [{"key": "expulsion_endpoint", "value": "http://localhost:56000/connect/expulsion"}]
```
If not, are there workarounds you may suggest?

Many thanks in advance,
Cristian.

**Comment by leastprivilege** [comment]
I can see the problem.

I don't have a workaround right now. I think you have to set the absolute path manually for the time being.

What would be the preferred "feature" to deal with that?

**Comment by beauceant** [comment]
Something coherent to how `IdentityModel.Client.DiscoveryResponse` behaves, could be just fine.
Since there is this statement:
```c#
// /IdentityModel/Client/DiscoveryResponse.cs#Ln138
if (element.Key.EndsWith("endpoint", StringComparison.OrdinalIgnoreCase) || //[...]
```
I'd like to see `IdentityServer4.Endpoints.DiscoveryEndpoint` dealing with it, like (pseudo-code):
```c#
// /IdentityServer4/Endpoints/DiscoveryEndpoint.cs#Ln172 and following
var endpointEntries = _options.Discovery.CustomEntries.Where(e => e.Key.EndsWith("endpoint", StringComparison.OrdinalIgnoreCase));
var clonedEntries = _options.Discovery.CustomEntries.Except(endpointEntries).ToDictionary(i => i.Key, i => i.Value); // in order to not interfere with the original entries' values
if (_options.Discovery.ShowEndpoints)
{
    // [...]
    foreach (var entry in endpointEntries)
    {
    	var endpoint0 = entry.Value.ToString(); // original
	var endpoint1 = string.Concat(baseurl, endpoint0.RemoveLeadingSlash()); // dynamically "absolutized"
	Uri uri;
	var isValidUri = Uri.TryCreate(endpoint0, UriKind.Absolute, out uri)
	    || Uri.TryCreate(endpoint1, UriKind.Absolute, out uri);
	if (!isValidUri)
	    _logger.LogWarning($"Malformed omitted endpoint: {endpoint0}");
	else
	    clonedEntries.Add(entry.Key, uri);
    }
}
// [...]
return new DiscoveryDocumentResult(document, clonedEntries);
```

**Comment by leastprivilege** [comment]
OK - hardcode it for now. I will probably add an "AdditionalEndpoints" feature in the next version.

https://github.com/IdentityServer/IdentityServer4/issues/878

**Comment by leastprivilege** [comment]
I added the feature on dev - docs are here:

http://docs.identityserver.io/en/dev/topics/discovery.html

**Comment by beauceant** [comment]
The _custom_ endpoints don't behave like the _standard_ ones (e.g. they don't obey the `.ShowEndpoints` flag).

I would suggest a `.CustomEndpoints` property alongside `.CustomEntries` in the `DiscoveryOptions` class, with some sort of semantic validation on the keys if you will (e.g. custom endpoint keys must have an `"_endpoint"` suffix while custom entries shouldn't). 
Don't know if it sounds like overengineering to you, it's just my 2 cents put on the table...

(`.CustomEndpoints` could even be constrained to have `Uri` as entry value type: in case of _relative_ ones, these could be made _absolute_ at rendering time... 2 more - 2much!? - cents)

**Comment by leastprivilege** [comment]
nope - not going to happen. You have all the primitives you need. sorry.
