### ISSUE TITLE
[Question] Authenticate user using API keys

### ISSUE THREAD

**Issue by 206mph** [IdentityServer/IdentityServer4#869]
I have implicit flow configured and working for a AngularJS application that uses a separate identity server website and separate API website. Now, I'm trying to figure out how I allow users that build their own APIs to access my API directly with no interactive user. Several other APIs I use employ API Keys. Is this still the preferred approach? If so, how can I implement that using IdentityServer4?

I need to know the user and the user's claims so I don't think using client ID and secrets will work since that appears to only identify the client API itself and not the user. I want to still use client IDs and secrets but also control user authorization within my API.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
