### ISSUE TITLE
What's the equivalent of IdentityServer3 IAuthenticationSessionStoreProvider in IdentityServer4?

### ISSUE THREAD

**Issue by FranciscoJCLus** [IdentityServer/IdentityServer4#87]
I'm trying to store sessions in a database using IdentityServer4. I found this issue related to IdentityServer3 (https://github.com/IdentityServer/IdentityServer3/issues/2527) that relates to my need, but I can't seem to find the equivalent in IdentityServer4. Is there been any renaming, is it a missing feature or am I totally missing the extensibility point? Thanks in advance.

**Comment by brockallen** [comment]
We just haven't gotten to that feature yet. It also depends on how we eventually design the cookie management.

**Comment by FranciscoJCLus** [comment]
Thanks for your quick answer. Is this something that can be done indirectly through the .net core session/cookie or any other mechanism? I'm trying to stick to IdentityServer4 and .net core, but if I cannot make this somehow work, I may have to go back to IdentityServer3, which is less than desirable.

**Comment by brockallen** [comment]
IdentityServer3 is much more mature and has many more customers using it. IdentityServer4 is still in development (mainly because ASP.NET Core is still thrashing so much).

**Comment by FranciscoJCLus** [comment]
I see. So the way it works today is storing all the information of the session in the cookie itself? So if the user hits a second instance of identity server (with the same data protection settings), this second instance just checks that the expire date is in the future to consider a session valid, for example?

**Comment by brockallen** [comment]
"all the information" meaning all the info about a user's current login session, yes

**Comment by FranciscoJCLus** [comment]
Our requirement is to be able to list the open sessions for a given user, and have the possibility to terminate any of them, forcing the user to re-login the next time he/she tries to use an application with terminated session. Would it be possible to achieve that combining identityserver and the native asp.net core session/cookie approach?

**Comment by brockallen** [comment]
Eventually, yes. But as mentioned elsewhere we're not really starting back up with significant work here until RC2 is out. This feature would be lower on the priority list, to be honest (just so many more fundamental things to get ported over from IdSvr3).
