### ISSUE TITLE
New Feature: Allow the ability to validate a refresh_token

### ISSUE THREAD

**Issue by ghstahl** [IdentityServer/IdentityServer4#870]
### Issue / Steps to reproduce the problem

I have the need to validate a refresh_token in the context of a IExtensionGrantValidator implementation.
The validation should take into account the following inputs;
1. The refresh_token
2. The client that created it
3. Lifetime check flag

A suggestion would be to have had it in ITokenValidator 
```
public interface ITokenValidator
{
    Task<TokenValidationResult> ValidateAccessTokenAsync(string token, string expectedScope = null);
    Task<TokenValidationResult> ValidateIdentityTokenAsync(string token, string clientId = null, bool validateLifetime = true);
    Task<TokenValidationResult> ValidateRefreshTokenAsync(string token, string clientId = null,bool validateLifetime = true);
}
```
most of the code already exits in TokenRequestValidator 
```
public class TokenRequestValidator : ITokenRequestValidator
{
    private async Task<TokenRequestValidationResult> ValidateRefreshTokenRequestAsync(NameValueCollection parameters);
}
```

**Comment by leastprivilege** [comment]
@brockallen needs discussing for v2

**Comment by brockallen** [comment]
Is there a related issue with more context?

**Comment by ghstahl** [comment]
@brockallen 
This is the original thread that prompted this.
https://github.com/IdentityServer/IdentityServer4/issues/847

**Comment by leastprivilege** [comment]
I prototyped this: https://github.com/IdentityServer/IdentityServer4/pull/1487

Would that work for you?

**Comment by ghstahl** [comment]
From the code it looks like this will work for me.  Its been awhile since I have been in my stuff that uses it, and I believe  the only issue I had was this feature existed by was not public.  I need to find some time quickly to swap out my stuff with this to verify it completely.

**Comment by leastprivilege** [comment]
well - I merged it.

**Comment by ghstahl** [comment]
Dependency Injection just makes me happy :)  I injected ITokenValidator into my custom ExtensionGrantValidator, and verified that I could validate the refresh token.
Thanks.
