### ISSUE TITLE
IdentityServer4 with Javascript Client not working in Edge browser

### ISSUE THREAD

**Issue by vmalhar** [IdentityServer/IdentityServer4#871]
Javascript client (provided in the documentation) doesnt work in edge.
I works as per expected in other browser.
I get the following error message when i try to log in or make an api call to the IdentityServer4 controller action from a javascript client application in Edge browser.

### Issue / Steps to reproduce the problem
1) Download and setup the javascript client specified in the indentityServer4 documentation.
http://docs.identityserver.io/en/release/quickstarts/7_javascript_client.html

2) Open the javascript client in Edge. When you try to login you get the following error which can be seen in Edge Developer Console.

SCRIPT7002 : XMLHttpRequest: Network Error 0x2efd, Could not complete the operation due to error 00002efd.

And 

Unhandled promise rejection Error: network error.

**Comment by brockallen** [comment]
I just tested it with: Microsoft Edge 38.14393.0.0 and it's working for me.

**Comment by Tochikoma** [comment]
Working fine for me too, on the "slightly older" Microsoft Edge 25.10586.672.0.
