### ISSUE TITLE
Question on extension grants

### ISSUE THREAD

**Issue by noufionline** [IdentityServer/IdentityServer4#872]
Hi @leastprivilege / @brockallen 

My application connects to different databases based on the choice of the user at login. I asked a similar question before but this one is about extension grants.

At the time of login user is asked for the division and I found the way to include that division id in the token.
Now if the user changes the division I want to replace the division id in token to the new division without asking the user their credentials again. Its just a change of one claim in the token. 

Is this possible using extension grants? If not then what is the recommended solution?

Thanks in advance.

Noufal

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
