### ISSUE TITLE
Question:  Access to ClientId

### ISSUE THREAD

**Issue by wattam** [IdentityServer/IdentityServer4#873]
Hi Team,

I am looking to add theming.

What is the best way of getting access to the ClientId in _layout.cshtml?

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
