### ISSUE TITLE
Windows Authentication Display a Temporary 500 Error Page

### ISSUE THREAD

**Issue by vmalhar** [IdentityServer/IdentityServer4#879]
### Issue / Steps to reproduce the problem
1) Enable Windows AUthentication using this link using IIS integration and Krestrel.
http://docs.identityserver.io/en/dev/topics/windows.html

2) When logging in, using Windows Authentication, a temporary 500 error page is displayed which then automatically gets refreshed and then logs the user in.
this issue is also mentioned in the following ticket logged by another user.
https://github.com/IdentityServer/IdentityServer4/issues/650

**Comment by brockallen** [comment]
Can you share a screen shot of the error page?

**Comment by vmalhar** [comment]
[cid:image001.jpg@01D29672.48EC0070]

**Comment by vmalhar** [comment]
![windows error](https://cloud.githubusercontent.com/assets/23177316/23620794/346ef21e-0266-11e7-9bf8-dceedd7d4fb0.png)

**Comment by vmalhar** [comment]
![windows error](https://cloud.githubusercontent.com/assets/23177316/23620891/9ed6af5c-0266-11e7-8c9d-8a60a935276f.png)

**Comment by brockallen** [comment]
Yes, I've seen this same issue. If you notice other browsers don't show this, so I feel like it's more of a chrome problem.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by brockallen** [comment]
This was recently re-tested on the Chrome v59 and was no longer the behavior.
