### ISSUE TITLE
Login from RP spends much time at connect/authorize endpoint (submit this form)

### ISSUE THREAD

**Issue by ajtowf** [IdentityServer/IdentityServer4#88]
If identityserver (read web app) is activated from idle state the first login request takes unreasonable amount of time at the connect/authorize endpoint.

Flow:
- RP redirects to Identityserver
- If you're not logged in, sign in (doesn't matter)
- Get redirected to connect/authorize endpoint, you can see (submit this form title in browser tab)
- After quite some time you get redirected back to the RP

Repeating the steps again after this is super fast.

**Comment by leastprivilege** [comment]
so what? ;)

Tell MS to boot up faster or keep the app running..that has always been an issue in .net

**Comment by ajtowf** [comment]
A bit quick to judge don't you think? The latency is definitely in the identityserver middlewear. You're referring to the long load time from cold start with the non core version but I'm running on core. Also as I described the app is already warm since I've loaded the login page and posted my credentials, it's not the first load, just the first redirect to connect/authorize.

Just now I had one tab that was waiting on connect/authorize with the title "submit this form", while that tab was busy I opened up a new tab and browsed to the identityserver where I was already logged in (due to the RP redirect->login), and I could perform several operations like updating my email adress and whatever until the first tab finally finished and redirected to RP.

Definitely not a MS problem.

**Comment by leastprivilege** [comment]
You said "idle" state. Why would "core" change that?

Anyways - feel free to do some more investigation and profiling to find out where the time gets spend. Looking forward to the findings!

**Comment by leastprivilege** [comment]
what did you profiling bring up?

**Comment by ajtowf** [comment]
I haven't had the time to come around and do it, been kind of swamped with work, also seems like it's faster, I've scaled the webapp to the premium tier. Closing this.

**Comment by ZOXEXIVO** [comment]
We have same problem. 
After cold start client project, when first request to identity is not quick - client freeze and only press F5 helps us.
