### ISSUE TITLE
IdentityServer4 AzureAD OpenIdConnect callbak state is missing

### ISSUE THREAD

**Issue by puddlewitt** [IdentityServer/IdentityServer4#883]
I have a stand-alone authserver using IdentityServer4. The server has an internal user/password mechanism for login and an AzureAd idp for login. Both using OpenIdConnect. Login for both works perfectly. Logout for the internal user/password works perfectly.

The AzureAD logout, however, seems to never send back the state to my authserver after I request a logout.

![image](https://cloud.githubusercontent.com/assets/2998294/23630411/e64125ce-02b2-11e7-807c-b780ef0696eb.png)

http://localhost:5000 = My AuthServer

I'm expecting the redirect from Microsoft to look more like

`http://localhost:5000/signout-callback-add?state=XXXXXX`

Any ideas?

**Comment by leastprivilege** [comment]
Ask Microsoft maybe?

**Comment by puddlewitt** [comment]
1. Ask MS
2. I could write some middleware to intercept a callback without state and display some page
3. I could store the state on my end at some point during the flow?

**Comment by brockallen** [comment]
All set on this issue? Can we close?
