### ISSUE TITLE
Make scope validator to case insensitive.

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4#884]
I add `openId ` inested of `openid `to identity resources, and got and `invalid_scope` error. 
It is possible to make scope validator to case insensitive?

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Validation/ScopeValidator.cs
```
trce: IdentityServer4.MessageCookie[0]
      Protecting message: {"Id":"be850e0e11325772953ec797e90b3b2d","Created":636244740037893075,"Data":{"Error":"invalid_scope","RequestId":"0HL356QOM6GV4"}}


```

**Comment by leastprivilege** [comment]
No. scope names are an exact match.

**Comment by mikeandersun** [comment]
Thanks to quick reply.
