### ISSUE TITLE
Implicit Flow - Javascript Client without User

### ISSUE THREAD

**Issue by demiremre** [IdentityServer/IdentityServer4#885]
Hello, 

I am implementing implicit flow for my javascript client. The only purpose of client is accessing API which is protected by IdentityServer4. I just see examples of implicit flow including user interaction. But in this case, there is no user but the client is javascript . So, can I use implicit flow like this or must I implement client credentials flow?

**Comment by leastprivilege** [comment]
In this case you would use client credentials flow.

But that means that you either need to hard code the client secret in the JS code, or use no secret at all.

**Comment by demiremre** [comment]
Okay thank you.
