### ISSUE TITLE
'IIdentityServerBuilder' does not contain a definition for 'AddAspNetIdentity'

### ISSUE THREAD

**Issue by Drumev** [IdentityServer/IdentityServer4#888]
When adding this configuration to Startup.cs ConfigureServices method:

services.AddIdentityServer()
            .AddTemporarySigningCredential()
            .AddInMemoryIdentityResources(Config.GetIdentityResources())
            .AddInMemoryApiResources(Config.GetApiResources())
            .AddInMemoryClients(Config.GetClients())
            .AddAspNetIdentity<ApplicationUser>();

the last bit isn't getting resolved by the compiler (.AddAspNetIdentity<ApplicationUser>();).

**Comment by dahumadaatgmail** [comment]
You have to add a reference to IdentityServer4.AspNetIdentity:

Install-Package IdentityServer4.AspNetIdentity

**Comment by prisar** [comment]
Installing `IdentityServer4.AspNetIdentity` worked for me

**Comment by mungiu** [comment]
Installing IdentityServer4.AspNetIdentity worked for me +1

**Comment by 95domin95** [comment]
Installing `IdentityServer4.EntityFramework` helps me

**Comment by thakurutkarsh22** [comment]
Installing IdentityServer4.EntityFramework Worked for me
