### ISSUE TITLE
Is requesting an id_token from ResourceOwnerPassword or Custom Grant supported?

### ISSUE THREAD

**Issue by jkavanaghrdm** [IdentityServer/IdentityServer4#89]

**Comment by jkavanaghrdm** [comment]
I've read that id_token values can be returned from grants other than the Implicit and Code flows. I'd like to try that but can't figure out if it's possible, and if it is, what the configuration is. Is it supported? Also, is there a relevant sample?

**Comment by leastprivilege** [comment]
id_tokens can be only requested using flows specified in OpenID Connect - hybrid, implicit and code.
