### ISSUE TITLE
Xamarin Android client oidc

### ISSUE THREAD

**Issue by mmothupally** [IdentityServer/IdentityServer4#890]
Hi, My apologies if this is a naive question. Below are my client and server configurations. Receiving unauthorized client error. Wondering where is its going wrong. Would highly appreciate your replies. Thanks!

**Android Client Login code:**

           var authority = "http://insightsidentityprovider.azurewebsites.net";
            var options = new OidcClientOptions(
                authority,
                "InsightsLocate",
                 "secret",
                 "openid profile api",
                 "http://com.insights.locate://callback", 
                  new ChromeCustomTabsWebView(this));
            _oidcClient = new OidcClient(options);
            var result = await _oidcClient.LoginAsync();

**OAuth Server client config:**

               ///////////////////////////////////////////
                // Android Hybrid with PKCE Sample
                //////////////////////////////////////////
                new Client
                {
                    ClientId = "InsightsLocate",
                    ClientName = "Console Hybrid with PKCE Sample",
                    ClientSecrets = new List<Secret>()
                    {
                        new Secret()
                        {
                           Value = "secret"//.Sha256()
                        }
                    },
                    RequireClientSecret = true,

                    AllowedGrantTypes = GrantTypes.Code,
                    RequirePkce = true,

                    RedirectUris = { "http://com.insights.locate://callback" },

                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        "api1", "api2.read_only",
                    },
                }

**OAuth Startup code:**

       public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            
            services.AddIdentityServer()
            .AddInMemoryClients(Clients.Get())
            .AddInMemoryIdentityResources(Resources.GetIdentityResources())
            .AddInMemoryApiResources(Resources.GetApiResources())
            .AddTemporarySigningCredential()
            .AddExtensionGrantValidator<Extensions.ExtensionGrantValidator>()
            .AddExtensionGrantValidator<Extensions.NoSubjectExtensionGrantValidator>()
            .AddSecretParser<ClientAssertionSecretParser>()
            .AddSecretValidator<PrivateKeyJwtSecretValidator>()
            .AddTestUsers(TestUsers.Users);

            services.AddMvc();

            // only use for development until this bug is fixed
            // https://github.com/aspnet/DependencyInjection/pull/470
            return services.BuildServiceProvider(validateScopes: true);
        }

**Comment by leastprivilege** [comment]
Logging or it never happened.

**Comment by mmothupally** [comment]
Thanks for your super fast response. 

Unfortunately this is happening on an Azure App instance and I have no access to logs. Are there any misconfigurations that could potentially cause it?

**Comment by brockallen** [comment]
I suggest you figure out how to get logging to work on azure.

**Comment by mmothupally** [comment]
Here is the log from Azure

2017-03-07 16:52:43.282 +00:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.AuthorizeEndpoint" for "/connect/authorize"
2017-03-07 16:52:43.298 +00:00 [Debug] Start authorize request
2017-03-07 16:52:43.345 +00:00 [Debug] No user present in authorize request
2017-03-07 16:52:43.360 +00:00 [Debug] Start authorize request protocol validation
2017-03-07 16:52:43.408 +00:00 [Error] Invalid redirect_uri: com.insights.locate://callback
"{
  \"ClientId\": \"InsightsLocate\",
  \"ClientName\": \"Console Hybrid with PKCE Sample\",
  \"RedirectUri\": \"com.insights.locate://callback\",
  \"AllowedRedirectUris\": [
    \"http://com.insights.locate://callback\"
  ],
  \"SubjectId\": \"anonymous\",
  \"RequestedScopes\": \"\",
  \"Raw\": {
    \"client_id\": \"InsightsLocate\",
    \"response_type\": \"code id_token\",
    \"scope\": \"openid profile api\",
    \"redirect_uri\": \"com.insights.locate://callback\",
    \"nonce\": \"350620ed73266717cb65deed749e2482f2798617d67a1a61f7d7d915f052bba0bd497adbc50f1e86fd8da12a16c8c71d1c2701c51c9b0806758fac2ee7111780\",
    \"code_challenge\": \"90STNTd2hwdrfWOtvhyO5y_8hkPsFiW3PEmWbLGwGeo\",
    \"code_challenge_method\": \"S256\"
  }
}"
2017-03-07 16:52:43.408 +00:00 [Error] Request validation failed
2017-03-07 16:52:43.423 +00:00 [Information] "{
  \"ClientId\": \"InsightsLocate\",
  \"ClientName\": \"Console Hybrid with PKCE Sample\",
  \"RedirectUri\": \"com.insights.locate://callback\",
  \"AllowedRedirectUris\": [
    \"http://com.insights.locate://callback\"
  ],
  \"SubjectId\": \"anonymous\",
  \"RequestedScopes\": \"\",
  \"Raw\": {
    \"client_id\": \"InsightsLocate\",
    \"response_type\": \"code id_token\",
    \"scope\": \"openid profile api\",
    \"redirect_uri\": \"com.insights.locate://callback\",
    \"nonce\": \"350620ed73266717cb65deed749e2482f2798617d67a1a61f7d7d915f052bba0bd497adbc50f1e86fd8da12a16c8c71d1c2701c51c9b0806758fac2ee7111780\",
    \"code_challenge\": \"90STNTd2hwdrfWOtvhyO5y_8hkPsFiW3PEmWbLGwGeo\",
    \"code_challenge_method\": \"S256\"
  }
}"

**Comment by mmothupally** [comment]
Thank You, was able to get the logs and observed the issue was with the GrantType being mentioned as **Code** for the client. Modified it to **GrantTypes.Hybrid** and I was able to get to the login screen and authenticate. However, receiving below error on the redirect.

![screenshot_20170307-123710](https://cloud.githubusercontent.com/assets/24532271/23677086/a2ccfdf0-0333-11e7-8974-b37d2d4f980b.png)

Below are the configurations on server and client for quick reference

**Server:**

                    new Client
                    {
                        ClientId = "InsightsLocate",
                        ClientName = "Console Hybrid with PKCE Sample",
                        ClientSecrets = new List<Secret>()
                        {
                           new Secret()
                           {
                              Value = "secret"//.Sha256()
                           }
                    },
                    RequireClientSecret = true,
                    AllowedGrantTypes = GrantTypes.Hybrid,
                    RequirePkce = true,
                    RedirectUris = { "com.insights.locate://callback" },
                    AllowedScopes =
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        "api1", "api2.read_only",
                    },
                }

**Android Client:**

            var authority = "http://insightsidentityprovider.azurewebsites.net";
            var options = new OidcClientOptions(
                authority,
                "InsightsLocate",
                 "secret",
                "openid profile api1",
                "com.insights.locate://callback", 
                new ChromeCustomTabsWebView(this));

            _oidcClient = new OidcClient(options);
            var result = await _oidcClient.LoginAsync();

**Comment by brockallen** [comment]
And you registered that custom scheme with the OS on the native device? That's really not an IdentityServer issue then.

**Comment by mmothupally** [comment]
Thank You, I was missing it. It now works with single Android App. I'm testing the SSO scenario and will have to see how it works with another app and same idp. 

Thanks again for all prompt responses!
