### ISSUE TITLE
Getting UnAuthorized while calling TokenEndPoint for IdentityServer4

### ISSUE THREAD

**Issue by TarunVarian** [IdentityServer/IdentityServer4#891]
Hello Team,

We are using IdentityServer4 which is hosted on IIS with Authentication mechanism as Windows Authentication to the Site. While I am trying to hit the token end point(with below code), I am getting unauthorized in TokenResponse.

When I enable Anonymous Authentication at Site level for IdentityServer4, it gives me the token. I need to know, is it mandatory to have Anonymous Authentication enabled in IIS for getting the token? 
While I run my IdentityServer4 code in IIS express and hit the corresponding end-point, it works fine. Could you please let me know what could be the reason?

var client = new TokenClient(
                ConfigurationItems.EndPointConfiguration.TokenEndpoint,
                clientId,
                clientSecret,
                authenticationStyle);
var TokenResponse = client.RequestClientCredentialsAsync(scope).Result;

Thanks,
Tarun Babbar
Varian Medical Systems, Pune

**Comment by leastprivilege** [comment]
You need to allow anonymous access.
