### ISSUE TITLE
Difference between ClientPostLogoutUri and LogoutUri? 

### ISSUE THREAD

**Issue by demiremre** [IdentityServer/IdentityServer4#899]
Hello,

What is the difference? Although Logout uri can be only one uri, post logout uri is a list. What is the exact purpose of each?

**Comment by brockallen** [comment]
I updated the docs to help clarify. https://identityserver4.readthedocs.io/en/release/reference/client.html#authentication-logout

**Comment by alexsandro-xpt** [comment]
@brockallen why all of thoses links is broken?

**Comment by brockallen** [comment]
Because the branch names changes. Go to our docs (http://docs.identityserver.io/en/latest/) and then change the url to match the one above but replace the branch names.
