### ISSUE TITLE
LoginService dependency

### ISSUE THREAD

**Issue by sebitsi** [IdentityServer/IdentityServer4#9]
Login controller depends on LoginService that depends on "fixed" InMemory user list:

```
public LoginService(List<InMemoryUser> users)
```
Everything work fine if we use InMemoryUsers
```
builder.AddInMemoryUsers(Users.Get());
```
If we change this to
```
builder.Services.AddTransient<IUserService, CustomUserService>();
```
what is proper way to inject custom service to login service ?
Just inject IUserService ?

It seems that CustomUserService and LoginService are not compatible.

Regards

Edvin

**Comment by ircnelson** [comment]
@sebitsi In my case, I removed the "LoginService" dependency and I put the IUserService calling the "AuthenticateLocalAsync" method passing an instance of "LocalAuthenticationContext" with username and password...

after passing in the "AuthenticateLocalAsync" method, you can see the property "AuthenticateResult" in the same instance of "LocalAuthenticationContext"

example:

```
 var localAuthContext = new LocalAuthenticationContext() 
 {
    UserName = model.Username,
    Password = model.Password
 };

// use the instance of IUserService injected
await _userService.AuthenticateLocalAsync(localAuthContext);

if (string.IsNullOrWhiteSpace(localAuthContext.AuthenticateResult.ErrorMessage))
{
   // everthing ok...
}
```

I used my class like this

**Comment by sebitsi** [comment]
Hi Nelson.
Thanks for your suggestion.
I made exactly same solution.

But. Point of my question is: 
What code should be part of IdentityServer implementation  and what is my code.

For example: Should be LoginController implemented as part of IdS4 or in my custom LoginController ?
With DI we can inject in custom controller everything we need and implement anything we need.
But is this right approach ?

I think logging process should be isolated in Ids4 with (for example) extension points for adding
custom claims or something else.

Or..

In IdS4 code there could be some bulletproff default controller we can inherit.

Or...

I missed something.. :)

Edvin

**Comment by leastprivilege** [comment]
It is the very first beta version. Some things are not done yet.

**Comment by sebitsi** [comment]
@leastprivilege 
Yes, I know that. 
Your work is awsome.

For now - it is enought for me that you are aare of that problem and you have plans to solve it.

Thanks for advance.

Edvin
