### ISSUE TITLE
ASP.NET Core RC2 ERROR

### ISSUE THREAD

**Issue by oferAshkenazy** [IdentityServer/IdentityServer4#90]
I tried using identity server 4 but i get the following error
"IdentityServer4.AccessTokenValidation 1.0.0-beta3 does not support framework .NETFramework,Version=v4.6.1"

**Comment by leastprivilege** [comment]
RC2 was released yesterday, I am still in the process of updating the code.

**Comment by PivotalAnimal** [comment]
Let me know if I can help out. Experienced at .NET. New to Core.

**Comment by ajtowf** [comment]
Let me know if you need help mate, just upgraded to RC2, shawn has written an excellent guide, helped med a lot, https://wildermuth.com/2016/05/17/Converting-an-ASP-NET-Core-RC1-Project-to-RC2 
Cheers!

**Comment by markgarcia** [comment]
I tried to port IdentityServer4 myself to RC2 and found some references, namely Json.Net and IdentityModel2 still doesn't support dotnet core / cli. Aside from that, it's *mostly* simple renaming references.

**Comment by markgarcia** [comment]
I tried to port IdentityServer4 myself to RC2 and found some references, namely Json.Net and IdentityModel2 still doesn't support dotnet core / cli. Aside from that, it's *mostly* simple renaming references.

**Comment by leastprivilege** [comment]
I will push the source code and nuget later today.

**Comment by oferAshkenazy** [comment]
My problem seems to be adding IdentityServer4 from nuget to work with my assembles (net 4.6.1)
I need Identity Server 4 version project for .Net Framework and not .Net core ?

**Comment by oferAshkenazy** [comment]
My problem seems to be adding IdentityServer4 from nuget to work with my assembles (net 4.6.1)
I need Identity Server 4 version project for .Net Framework and not .Net core ?
