### ISSUE TITLE
Docs: Setup and overview doc is missing instructions

### ISSUE THREAD

**Issue by tugberkugurlu** [IdentityServer/IdentityServer4#900]
## Problem

When you follow the setup instructions here, you get the following error first:

> 2017-03-09 21:18:43 [Fatal] No storage mechanism for clients specified. Use the 'AddInMemoryClients' extension method to register a development version.

Error message is really clean which made me happy. After following that suggestion (smilar to how it's done [here](https://github.com/IdentityServer/IdentityServer4/blob/b06c5b9aedb4826c59e1ec959d82f5f3934483fc/test/IdentityServer.IntegrationTests/Endpoints/Introspection/Setup/Startup.cs)), you get the below:

> 2017-03-09 21:30:43 [Fatal] No storage mechanism for resources specified. Use the 'AddInMemoryResources' extension method to register a development version.

I was able to get the server up and running after configuring completing this step, too.

## Suggestion

It would be nice to make this apparent at the docs. I am sure it would make the getting started experience better.

The following statement is there:

> AddIdentityServer registers the IdentityServer services in DI. It also registers an in-memory store for runtime state. This is useful for development scenarios. 

However, it's outdated I believe.

**Comment by cemana** [comment]
tugberkugurlu, I have the same problem with VS 2017. Can you show the correct lines for Startup.cs?
Thanks

**Comment by leastprivilege** [comment]
I will update the docs for 2017 this week.

**Comment by leastprivilege** [comment]
but it does say:

> IdentityServer is not yet ready to be launched. In fact, when you try it, you should see an exception at startup time stating that services are missing. We will add those services in the following quickstarts.

Did you miss that - or is it not clear enough?

**Comment by cemana** [comment]
I am sorry. I missed that.

**Comment by gshock** [comment]
Hi, I ran into the same issue... you must continue on to the next section "Protecting an API using Client Credentials"
