### ISSUE TITLE
IdentityServer4 within single app architecture

### ISSUE THREAD

**Issue by obosha** [IdentityServer/IdentityServer4#904]
QUESTION:

I currently have the ability to host _one_ and only one site (that's what I'm paying for).  I will have a SPA front-end, Web Api resource, and then IdentityServer4 for security (utilizing AspNetCore Identity for users).

Something feels "wrong" with this approach to a single hosted site architecture.  AspNet Identity I believe uses auth cookies, and then IdentityServer would be serving up JWT tokens for my SPA to call my API.

Is this a misguided approach when I don't deploy these pieces independently?  The thing that seems off is that I believe my API calls will _also_ have the auth cookie attached along with the JWT token because the API call will be from same domain as the auth cookie was generated.  And so it seems I'm using two forms of authentication at once unnecessarily...   thoughts?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io

**Comment by obosha** [comment]
Makes sense, will do.

**Comment by stt106** [comment]
Did you get any answer on SO? If so please can you post the SO link?
