### ISSUE TITLE
IDX10501: Signature validation failed. Key tried: 'System.IdentityModel.Tokens.RsaSecurityKey'.

### ISSUE THREAD

**Issue by lemieuxs** [IdentityServer/IdentityServer4#905]
Every time I deploy my identityServer project (the app pool is recycle) and that a client tries to identity itself I get this error on the client.

```
IDX10501: Signature validation failed. Key tried: 'System.IdentityModel.Tokens.RsaSecurityKey'.
token: '{"alg":"RS256","kid":"abdcefghijklmnopqrstuvwxyz","typ":"JWT"}.{"nbf":1489172589,"exp":1489172889,"iss":"https://id.xxxxx.spk.rocks","aud":"xxxxx-formation","nonce":"636247693843365788.N2Y1N2QxMDMtY2Q1My00NDI1LTk0NDMtNTBmYTQwZmIyNDQzMDQ5ZDA2ODEtMDAwNS00MTI2LTlhY2MtMWQ4OGQ2OWNmM2Fi","iat":1489172589,"c_hash":"YRHgKlOKFtNzJISJtFFmaQ","sid":"7be8f781503ad9bd81c0097d3c1e6edb","sub":"A186C135-0D2E-4BE6-A116-8E397B339C6D","auth_time":1489172567,"idp":"local","email":"geeks@spektrummedia.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name":"geeks@spektrummedia.com","http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier":"A186C135-0D2E-4BE6-A116-8E397B339C6D","role":["ADMIN FORMATION","SUPER ADMIN"],"http://schemas.microsoft.com/ws/2008/06/identity/claims/role":["ADMIN FORMATION","SUPER ADMIN"],"amr":["pwd"]}'
```

Here is how I setup my signing credentials on the identity server:

```
private IIdentityServerBuilder AddSigningCredentials(IIdentityServerBuilder builder)
        {
            RSA rsa = RSA.Create();
            if (rsa.KeySize < 2048)
            {
                rsa.Dispose();
                rsa = (RSA)new RSACryptoServiceProvider(2048);
            }
            RsaSecurityKey rsaSecurityKey = (RsaSecurityKey)null;
            if (rsa is RSACryptoServiceProvider)
            {
                rsaSecurityKey = new RsaSecurityKey(rsa.ExportParameters(true));
                rsa.Dispose();
            }
            if (rsaSecurityKey == null)
                rsaSecurityKey = new RsaSecurityKey(rsa);
            rsaSecurityKey.KeyId = Configuration.GetValue<string>("TokenKey");
            SigningCredentials credential = new SigningCredentials((SecurityKey)rsaSecurityKey, "RS256");
            return builder.AddSigningCredential(credential);
        }
```

In order to get my app back to work I need to recycle the app pool or to restart the client website.

Do I have to implement anything to handle the decryption of the token client side ?

Do you have any ideas what is happening ? I can't seem to get my head around it.

Thanks.

**Comment by leastprivilege** [comment]
You are basically using the "temporary signing credential" approach. This is only for dev time and obviously not for production.

You need a stable RSA key pair or an x509 cert for production.

**Comment by lemieuxs** [comment]
What part in the above code is not stable ? When I first looked at the "temporary signing credential approach I thought that the only thing that wasn't stable was the KeyId. It seems I was wrong. What else is ?

Is there any documentation or complete tutorial that are setting a stable RSA key pair or an x509 cert that you could point me to. 

Thanks

**Comment by leastprivilege** [comment]
The key.

I am using this approach e.g:

https://github.com/IdentityServer/IdentityServer4.Demo/blob/master/src/IdentityServer4Demo/Startup.cs#L38-L45

**Comment by geasi** [comment]
Hi!

Do you have a RSA key pair working sample?
I see that the link you provided is getting a certificate in CertificateStore.

I'm trying to make it work without success.

Part of my Startup.ConfigureServices(IServiceCollection services):

`            var rsa = RSA.Create();
            var key = new RsaSecurityKey(rsa)
            {
                KeyId = "c38b4f9a81500dc44bf1f6c84a9bfb2b"
            };

            var credentials = new SigningCredentials(key, SecurityAlgorithms.RsaSha256);

            services.AddIdentityServer()
                .AddSigningCredential(credentials)
                (...)`

**Comment by Mardoxx** [comment]
`KeyId` is the id of the key, not the key itself.

Export a key as XML with all props (`RSA.Create().ToXmlString(true)`). Save this somewhere safe.

Modify your startup to do this:

```
var signingKeyXml = "<RSAKeyValue>...</RSAKeyValue>";
var rsa = new RSACryptoServiceProvider(2048);
rsa.FromXmlStringEx(signingCredKeyXml);
var signingKey = new RsaSecurityKey(rsa.ExportParameters(true));

services.AddIdentityServer()
    .AddSigningCredential(credentials);
```

If using netcore, you'll have to implement `fromXMLString(string xml)` yourself: `https://github.com/dotnet/core/issues/874#issuecomment-323894072`
