### ISSUE TITLE
Impicit Flow -  Api project not validating tokens whe using .NetFramework4.6.2 - Internal Server error

### ISSUE THREAD

**Issue by anupavanm** [IdentityServer/IdentityServer4#906]
### Issue / Steps to reproduce the problem

Impicit Flow -  Api project not validating tokens when  running on .NetFramework4.6.2.
It works perfectly when i switch the project to .Net core.
I'm not using SSL or any certificate.
I've enabled CORS.
I'm using   "IdentityServer4.AccessTokenValidation": "1.0.5",

Network tab log:
http://localhost:5001/api/Employees/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
employees:1 XMLHttpRequest cannot load http://localhost:5001/api/Employees/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5003' is therefore not allowed access. The response had HTTP status code 500.
(BUT THE PREFLIGHT REQUEST RESPONSE HAS THE CORS HEADER)

### Relevant parts of the log file
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HL37UJTR1OSQ": An unhandled exception was thrown by the application.

System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://localhost:5000/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'http://localhost:5000/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 127.0.0.1:5000
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

**Comment by leastprivilege** [comment]
Try updating `System.Net.Http` to 4.3.1 - this seems to fix these kinds of problems.

**Comment by leastprivilege** [comment]
Also let us know if that helped.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
