### ISSUE TITLE
Registration part 

### ISSUE THREAD

**Issue by alvachien** [IdentityServer/IdentityServer4#91]
It's great project which make our development more easier on Login part.
However, is it possible to handle the registration part as well? For instance, click on the Register link on the Login page will open the Register page, and will redirect to the app with token assigned if the register was successful.

A default implementation, let says, based on ASP.NET Identity should be fantastic.

**Comment by leastprivilege** [comment]
It is just controllers and views - feel free to add it yourself.

A "default" registration does not exist - everybody does it differently. Maybe this is more for a sample.
