### ISSUE TITLE
Issue with windows authentication

### ISSUE THREAD

**Issue by prydzewski** [IdentityServer/IdentityServer4#910]
Hi,
When I run your Quickstart(6_AspNetIdentity) sample and try to login with external provider Negotiate or NTLM, I get a empty site with status code some times is 403 or 400(/Account/ExternalLogin). It's look like challenge is not working like I think it should. When I go to main page I see that User is logged in but flow of log in with windows authentication is broken. Maybe someone can tell me how should work external login with Negotiate or NTML. I tried run IdentityServer with IIS and WebListener and result is the same. It's possible that it is problem with system? In my system windows authentication will be the main login provider.

**Comment by leastprivilege** [comment]
the UI needs to be prepared for that since the windows middleware is behaving a bit different than the other middlewares. Check our Quickstart UI - especially the ExternalCallback code.

**Comment by prydzewski** [comment]
Problem is that I don't even reach ExternalLoginCallback action. It looks like a challenge method in ExteernalLogin action is behaving strange.

**Comment by leastprivilege** [comment]
exactly. Check our UI.

**Comment by prydzewski** [comment]
With UI sample i have the same result like before. After external login by Windows, browser stays on account/ExternalLogin?provider=Negotiate site and in logs I have request with 401 status code.
Now i'm trying this on WindowsServer2016.
