### ISSUE TITLE
Returning false in IProfileService.IsActiveAsync

### ISSUE THREAD

**Issue by Mardoxx** [IdentityServer/IdentityServer4#911]
What is meant to happen when you return false in `IsActiveAsync`?

I created a basic profile service to test:

    public class ProfileService : IProfileService
    {
        public ProfileService()
        {
        }

        public Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            return Task.FromResult(0);
        }

        public Task IsActiveAsync(IsActiveContext context)
        {
            context.IsActive = false;
            return Task.FromResult(0);
        }
    }

And I have added it to `IdentityServerBuilder` with `.AddProfileService<ProfileService>();`

I see in `AuthorizeInteractionResponseGenerator.cs` it does `if (!isActive) { _logger.LogInformation("Showing login: User is not active"); }` but there doesn't seem to be a way to catch this?

All that happens for me is that the user gets redirected back to the login page. Ideally I'd want to send them to a page that says they're locked out?

**Comment by brockallen** [comment]
> What is meant to happen when you return false in IsActiveAsync?

Do the docs not help? https://identityserver.github.io/Documentation/docsv2/advanced/userService.html

> All that happens for me is that the user gets redirected back to the login page. Ideally I'd want to send them to a page that says they're locked out?

If you know they're locked out, then your login page should inform them.

**Comment by Mardoxx** [comment]
Hi,

No worries!

So if I follow, IsActive is to restrict already authenticated users being issued new tokens -- e.g. lock out when they are already logged in. So I should be doing a similar logical checks when the user logs in, for example, [here](https://github.com/IdentityServer/IdentityServer4.Samples/blob/1.0.1/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/Quickstart/Account/AccountController.cs#L73) and [here](https://github.com/IdentityServer/IdentityServer4.Samples/blob/1.0.1/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/Quickstart/Account/AccountController.cs#L234) ?

**Comment by brockallen** [comment]
Yes, at login time if you don't want them to "get in" you should block them. Also, IsActive will prevent new tokens (such as those being obtained from refresh tokens).

**Comment by Mardoxx** [comment]
Brilliant, thank you 😄

**Comment by collinbarrett** [comment]
Just to confirm this is still the case:

If we determine if a user is active by calling an external API, we need to call this API twice? Once [here](https://github.com/IdentityServer/IdentityServer4.Samples/blob/a189aa74c243582a86a85320fd5be320dde624a9/Quickstarts/7_JavaScriptClient/src/QuickstartIdentityServer/Quickstart/Account/AccountController.cs#L75)-ish and then again in `ProfileService.IsActiveAsync()`?

Thanks.

**Comment by brockallen** [comment]
Yes, it might be called several times. You can always cache your results.
