### ISSUE TITLE
Authorize/login - Internal Server Error (500) Error: null

### ISSUE THREAD

**Issue by lemieuxs** [IdentityServer/IdentityServer4#912]
**In my staging environment**, every time a user attempt to authenticate himself, when Identity is about to redirect to my client app it seems to fail with a **Internal Server Error (500)**, but no details are bubling up the stack to the view as you can see.

![error null](https://cloud.githubusercontent.com/assets/10490601/23872377/75cb74e6-0804-11e7-8480-c9b352231a4f.png)

**This does not happen in development.** All I can see that is different is the fact of using a certificat to sign the tokens instead of using the "Temporary signing credentials" method.

Here is how I do:
`
 if (Environment.IsDevelopment())
 {
      identityServer.AddTemporarySigningCredential();
  }
  else
  {
       identityServer.AddSigningCredential("04f3ce640b0453f2ba1c655cdaaf47a91fab1287", storeLocation.LocalMachine, nameType: NameType.Thumbprint);
  }
`

We can cleary see that the login was successfull. It is really the **authorize/login** that seems to fail somewhere.

I am not able to get any logs or more defails out of this error.
BTW There ain't no documentation about how to setup the logging in IndentityServer4... :(

I know I ain't got much, but any help would be greatly appreciated.

Thanks.

**Comment by Mardoxx** [comment]
Might want to check that the thumbprint doesn't have some hidden unicode characters before it if you copied it from certmgr! https://support.microsoft.com/en-us/help/2023835/certificate-thumbprint-displayed-in-mmc-certificate-snap-in-has-extra-invisible-unicode-character

Logging can be setup thusly:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging

**Comment by lemieuxs** [comment]
It's not any hidden unicode characters. I had this error this morning.

I'll check out the logging. thx

Any other thoughts ?

**Comment by Mardoxx** [comment]
Have you tried it in a new session, e.g  private browsing?

**Comment by leastprivilege** [comment]
Logging will have more details - make sure you know how to enable it in staging/production.

Also make sure you update everything to dotnet/aspnetcore 1.1.1 - there was a x509 related bug in 1.1.

**Comment by lemieuxs** [comment]
1. Private browsing get's the same result...
2. I updated everything to dotnet/aspnetcore 1.1.1 

I read the documentation for IdentityServer 3 about enabling the EventOptions for more logging. But I'm not quite sure how to implement it in IdentityServer4 since the doc page isn't done yet...

**Comment by leastprivilege** [comment]
Logs are good enough. Use the trace log level.


-------
Dominick Baier

**Comment by lemieuxs** [comment]
Thx for your help. With the logging I found out that the IIS_IUSRS did not have access to my certificat
This link helped me fix my error: http://stackoverflow.com/a/3176253/5153162
