### ISSUE TITLE
[Question]How can I filter Roles/RoleClaims/UserClaims

### ISSUE THREAD

**Issue by JamieZMZhang** [IdentityServer/IdentityServer4#913]
Hi!
I'm trying to make IDSvr work with multi-tenants website that allows a user to have different roles/userclaims when they login with diff tenants.
So now I'm trying to filter the roles and claims with value suffix. But I couldn't find the Interface or Class that I can override the behavior before they output.
Is there a way to do this? 
Thanks for your time and fine work.

**Comment by leastprivilege** [comment]
Implement the IProfileService.

**Comment by JamieZMZhang** [comment]
It's working now.
Actually I implemented that interface already. But I only resign in on IDSvr so it didn't work. 
Thx!
