### ISSUE TITLE
[Question]CorsPolicyServer is warning when IS is siting behind ELB.

### ISSUE THREAD

**Issue by gaupoit** [IdentityServer/IdentityServer4#914]
Hi guys, I just deployed the Identity Server to my ELB with two instances in load balancer, namely A and B instance. The A instance works well, however the B instance show the message that Warning] CorsPolicyService did not allow origin: "http://myclientdomain.com". Please give me some advice to figure out them problem? Thanks.

**Comment by brockallen** [comment]
> Please give me some advice to figure out them problem? Thanks.

Check the logs?
