### ISSUE TITLE
Port Quickstarts and QS docs to VS 2017

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#916]

**Comment by leastprivilege** [comment]
Following steps are necessary:

* migrate to VS 2017
* set target to aspnetcore 1.1
* edit csproj <RuntimeFrameworkVersion>1.1.1</RuntimeFrameworkVersion>
* update packages

**Comment by leastprivilege** [comment]
@brockallen 6-8 are for you.

**Comment by jeremycook** [comment]
@leastprivilege @brockallen Would you guys like any help updating the QS docs? I am going through the Quick Starts now with VS 2017, and would be happy to change project.json mentions to .csproj and so on.

**Comment by leastprivilege** [comment]
Thanks. We want to take that opportunity to make slow slight updates. But
if you could review the result, that would be useful.


-------
Dominick Baier

**Comment by jeremycook** [comment]
OK. Tell me where to look or when it's ready, and I will.

**Comment by brockallen** [comment]
Yea, I'll be getting to these soon. Thanks for the feedback.

**Comment by brockallen** [comment]
6-8 done.

**Comment by brockallen** [comment]
All quickstarts docs updated for vs2017 changes. @leastprivilege  have a look -- i added several nuget screenshots where we used to instruct editing project.json

**Comment by leastprivilege** [comment]
looks good!

**Comment by jeremycook** [comment]
Thanks for updating for the new tooling. The docs have been great for transitioning my Identity Server 3 knowledge to version 4, and for learning ASP.NET Core (not that that is a goal).
