### ISSUE TITLE
Can we use Identity Server 4 to Secure API Created using .Net Framework 4.x

### ISSUE THREAD

**Issue by ShashikantMaurya** [IdentityServer/IdentityServer4#918]
- [ ] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by ShashikantMaurya** [comment]
Please let me know if it is possible using .net framework 4.x

**Comment by leastprivilege** [comment]
>= 4.5 yes.
