### ISSUE TITLE
Interaction Generator Error

### ISSUE THREAD

**Issue by rh78** [IdentityServer/IdentityServer4#919]
Hi, in my logs (Application Insights, running on Azure, ASP.NET Core on full .NET 4.6.2 Framework) I sometimes get "Interaction Generator Error" (no exception, no stack trace, just a log entry with severity level "Error"). Category Name "IdentityServer4.Endpoints.AuthorizeEndpoint" on "GET /connect/authorize"

Reporting because maybe it is an issue, but in any case it would be good to know possible causes of this issue.

**Comment by brockallen** [comment]
Would this be the same issue? https://github.com/IdentityServer/IdentityServer4/issues/815

**Comment by rh78** [comment]
Not sure but could be according to the description.

**Comment by brockallen** [comment]
We did a new release with this change -- can you upgrade and try it?

**Comment by brockallen** [comment]
Any update?

**Comment by brockallen** [comment]
Also, if you can't confirm on the recent release can you at least provide me the message with the error log entry? I can't tell which one it is,

**Comment by rh78** [comment]
Sorry for the long waiting time. We did a release yesterday using latest version of IdSrv4 lets see if the errors stop spawning. Will keep you posted.

**Comment by rh78** [comment]
Looks very good! You can close the issue IMHO.

**Comment by leastprivilege** [comment]
cool
