### ISSUE TITLE
Full framework support

### ISSUE THREAD

**Issue by rmja** [IdentityServer/IdentityServer4#92]
Would it be possible to have full framework support instead of _only_ `netstandard1.5`. Maybe `net451` or `net46`?

**Comment by totht91** [comment]
`netstandard1.5` is compatible with the full framework, specifically with the 4.6.2. 

https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by rmja** [comment]
Ahh, I didn't know that. Thanks!

**Comment by rmja** [comment]
Reopening. I seems that I really need net451, as I need to deploy to a Service Fabric cluster.

**Comment by rmja** [comment]
Created https://github.com/IdentityModel/IdentityModelv2/pull/2 for `net451` support in IdentityModel.

**Comment by totht91** [comment]
You can use the IdentityServer3 with asp.net core on the full framework, Or @brockallen, do you want to support anything else beside netstandard?

**Comment by bburman** [comment]
I would also like support for net451. .NET 4.6.2 still appears to be in preview.

**Comment by YannisMarios** [comment]
@totht91 I might be mistaken but neither IdentityServer3 nor IdentityServer4 work with net451, net462

I have a solution that must include .net 4.5.1 class libraries and an ASP.NET Core (.NET framework) web app. Changing target framework to my class libraries to 4.6.2 worked and I can Include them in my ASP.NET Core web app. The thing is that IdentityServer has problems with .net 4.6.2

Any suggestions?

**Comment by leastprivilege** [comment]
i updated all the packages - give it a go and see if that works better for you (and open a new issue if you encounter problems)

**Comment by YannisMarios** [comment]
Thank you Dominic. I will try it and let you know
