### ISSUE TITLE
UseAllClaims in IdentityServer4

### ISSUE THREAD

**Issue by siberianguy** [IdentityServer/IdentityServer4#920]
There used to be a property (don't recall exact name) in IdentityServer3 to put all the claims to a token. I can't find a similar one in IdentityServer4. Is there any reason for that? Is it considered a bad practice?

**Comment by leastprivilege** [comment]
We removed it in 4 because generally speaking this is dangerous. Token sizes might get out of control with this setting on. 

If you need the behavior, write an IProfileService that implements that.

**Comment by siberianguy** [comment]
But it looks like it's not enough to add a custom ProfileService. I still have to add fake UserClaim (as ProfileService is not called if UserClaims list is empty):

```
        public static IEnumerable<ApiResource> Get()
        {
            return new List<ApiResource>
            {
                new ApiResource("api_access", "access the api")
                {
                    UserClaims = new List<string>()
                    {
                        "custom"
                    }
                }
            };
        }
```

**Comment by leastprivilege** [comment]
Are you on the latest version? This behavior has changed at some point.


-------
Dominick Baier

**Comment by siberianguy** [comment]
@leastprivilege, you're right. I had just IdentityServer4.IdentityServer 1.0.0 in project.json and it implicitly referenced IdentityServer4 of the same version (1.0.0). I had explicitly specified version 1.2.0 (there was an error for 1.3.0, so had to downgrade) and now it works without UserClaims specified. Thanks!
