### ISSUE TITLE
Build not loading in Visual Studio 2017 Community Edition

### ISSUE THREAD

**Issue by sreejithneologix** [IdentityServer/IdentityServer4#922]
I'm trying to open the solution using VS 2017 CE, but the projects are not loading. When I open the solution, it shows the project needs migration. On proceeding with that, one of the projects is not loaded correctly. Please help me in fixing this scenario.

**Comment by leastprivilege** [comment]
Are you on the latest version of the code? We already migrated to VS2017 and it works fine.

**Comment by leastprivilege** [comment]
any update?
