### ISSUE TITLE
How to Secure Web WEB API Created Using 4.x Framework as we can not use IApplicationBuilder

### ISSUE THREAD

**Issue by ShashikantMaurya** [IdentityServer/IdentityServer4#923]
- [ ] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Relevant parts of the log file

```
<log goes here>
```

**Comment by ShashikantMaurya** [comment]
Hi,

We can use below code to secure api created using .net core ,but how to do same if using .net framework 4.5. Please help

app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:5000",
                RequireHttpsMetadata = false,

                ApiName = "api1"
            });

**Comment by leastprivilege** [comment]
using 

https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation

**Comment by ShashikantMaurya** [comment]
Hi,

I am using Identity Server 4,you have given link of Identity Server 3,so please let me know how to secure API created using .net framework not .Net Core.

**Comment by leastprivilege** [comment]
I have given you the correct information. Now go research.

**Comment by kotikavoori** [comment]
@ShashikantMaurya  @leastprivilege  Any update on this ? is it okay to use IS-4 with .net f/w 4.5.1 ?
