### ISSUE TITLE
Any other way to remove idsrv.ClientSession cookie when single signout?

### ISSUE THREAD

**Issue by atpyk** [IdentityServer/IdentityServer4#924]
Regarding your example, it has a LoggedOut page that include an iframe will call endsession endpoint to clean client cookies. I don't think it's the ideal solution. Is there any other way to implement it without iframe?

I try to use HttpClient to call endsession endpoint in Logout action, it got 200 but the ClientSession cookie couldn't be removed. Could you have any suggestion for this, thanks.
   

var client = new HttpClient();
    var result = client.GetAsync(vm.SignOutIframeUrl).Result;

            if (model.LogoutId == null || string.IsNullOrWhiteSpace(vm.PostLogoutRedirectUri))
            {
                return Redirect("/Account/Login");
            }

            return Redirect(vm.PostLogoutRedirectUri);

**Comment by leastprivilege** [comment]
You have to call end session in the context of a browser. Read the specs.
