### ISSUE TITLE
How to return email claim from IExtensionGrantValidator in GrantValidationResult

### ISSUE THREAD

**Issue by yolofy** [IdentityServer/IdentityServer4#927]
I'm using the following code in my IExtensionGrantValidator
```
 public async Task ValidateAsync(ExtensionGrantValidationContext context)
        {
            var idToken = context.Request.Raw["access_token"];

            var result = this.handlerDispatcher.Handle(new TokenExchangeCommand
            {
                IdToken = idToken
            });

            var claims = new List<Claim>
            {
                new Claim("email", result.Email),
            };

            context.Result = new GrantValidationResult(result.UserId.ToString(), "access_token", claims);
        }
```

In my client configuration I have set AlwaysSendClientClaims to true. After this there are 2 additional claims available in my JWT:

{
  "nbf": 1489590551,
  "exp": 1489594151,
  "iss": "http://localhost:5000",
  "aud": "http://localhost:5000/resources",
  **"client_id": "client1",
  "client_email": "test_test_test@hotmail.com",**
  "sub": "66b8645f-44af-e065-8595-68afc8dcafc9",
  "auth_time": 1489590551,
  "idp": "local",
  "scope": [
    "email"
  ],
  "amr": [
    "access_token"
  ]
}

But I want the claim to be called '**email**' not '**client_email**', how can I do this?

**Comment by leastprivilege** [comment]
You are confusing user and client claims. What do you want to achieve?

**Comment by yolofy** [comment]
I was looking for the IProfileService, thanks.
