### ISSUE TITLE
Considering user's previous consent while logging-in again to a client asking for a Refresh Token

### ISSUE THREAD

**Issue by urielb92** [IdentityServer/IdentityServer4#928]
It occurred to us that whenever a user logs in again to a client that he has already consented to give access to his resources (and specifically to offline_access - meaning the client will get a refresh token), he has to consent again.
Our app contains sensitive data, once a user logs in he has access to financial operations. We must re-authenticate the identity of the user at least once a day. Making the user consent on every log in can get tedious.

I just think of real life applications - you don't consent every time you login again to an app using FB / Google account.

**Comment by leastprivilege** [comment]
I can see that being not so nice. Let's see what we can do about it @brockallen

**Comment by twenzel** [comment]
Got a hint from Johnny to set the `RequireConsent` flag to false in the Client registration.

http://stackoverflow.com/questions/42834138/permission-grant-page-will-always-be-shown-when-using-identityserver4/42837395#42837395

**Comment by urielb92** [comment]
@twenzel But I want to show a consent. I just don't want to show it every single time the user logs in.

**Comment by twenzel** [comment]
@urielb92 you're right. Let's see what leastprivilege or brockallen says.

**Comment by TomCJones** [comment]
If you were interested in the rights of the user to their own data you should allow the user to decide if the consent is durable.

thx ..tom

**Comment by leastprivilege** [comment]
We had a look - in https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

it says:

> The OP MUST always obtain consent to returning a Refresh Token that enables offline access to the requested resources.

We are looking into a way on how to modify this behavior - but not sure yet if this will be possible without a breaking change.

**Comment by urielb92** [comment]
Okay, thanks a lot for the update!

We turned consent off for now, and thinking of alternatives, maybe a one-time consent in the registration page. 
Not ideal, but we need the login experience to be as smooth and easy as possible, we can't compromise about the in this area.

We'll keep track of this issue, hoping it will be possible to implement without breaking the current implementation.
Again, thanks for the awesome job 👍

**Comment by brockallen** [comment]
Your easiest approach for this now is to replace (or derive from) our default consent service: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultConsentService.cs

and then copy the code from `RequiresConsent`: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultConsentService.cs#L50

but leave out the check for offline access: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultConsentService.cs#L72

**Comment by brockallen** [comment]
I think you have a sufficient workaround, so I'll close this now.
