### ISSUE TITLE
.Net core 1.1 problem

### ISSUE THREAD

**Issue by sonphnt** [IdentityServer/IdentityServer4#929]
Hi Everyone,

I have updated to .Net core 1.1. I would like to use IdentityServer4. So which version of it is working fine with .net core 1,1 and EF core 1.1.1. 
It looks like there are some differences between EF core 1.1.0 and 1.1.1

I am having a problem with nuget confliction

Thanks

**Comment by leastprivilege** [comment]
use the latest of all ;)

**Comment by mkeymolen** [comment]
seems to be working fine..
