### ISSUE TITLE
Plug into VS generated project

### ISSUE THREAD

**Issue by cuiliang** [IdentityServer/IdentityServer4#93]
I want to make minimal change on visualstudio generated web project and plug idsvr only for providing tokens.
I want: 
     1) use asp.net identity  
     2) use original controller's and views for Login/Register/External Login
Is there some guidelines to do this?
Thanks very much~

**Comment by brockallen** [comment]
Sure... with time we might have something like this. But we don't have it now as we're in beta.

**Comment by leastprivilege** [comment]
That's one way to do it

https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/SpaWithAspId3AndIdSvr4
