### ISSUE TITLE
Options When You Own All Sites

### ISSUE THREAD

**Issue by joshpearce** [IdentityServer/IdentityServer4#930]
We're using Identity Server to authenticate web apps and api across a few domains, but we own all of them, and they all have access to a common datastore.

The nice thing about Identity Server is, for .NET web apps, we can plug in the middleware and it just works. I'm finding it's not quite as easy to secure a Node/Express web api with OAuth2. That's a little disappointing.

But, JWTs have some features that we just don't need: PKI and statelessness.

So my questions is, would it make sense to modify Identity Server to do the following:

- Validate JWTs (or an alternative token format) with a shared, non-public signing cert
- Make JWTs lighter by removing the header, issuer and audience values
- Do active token validation agains the DB, thereby greatly simplifying the logout story, and gaining token invalidation.

I'm not asking these questions lightly, like "Hey, can I author invalid JWTs and then complain that JWT parsing libs can't read them." Rather, I'd like to know if the Identity Server project/code has enough value for my scenario, or it's better to look elsewhere.

**Comment by leastprivilege** [comment]
Have you looked into reference tokens?

**Comment by joshpearce** [comment]
Thanks. I found some blog posts and issues on Reference Tokens. The docs are empty. Am I correct that access token validation works out of the box with the Thinktecture Middleware, app.UseIdentityServerAuthentication, by contacting an HTTPS token validation endpoint? If so, that seems to conflict with the idea of a common data store. There is a way to add a custom token validator when using app.UseIdentityServerAuthentication right?

**Comment by TomCJones** [comment]
Kerberos is designed to do this. Why don’t you just use Kerberos?

thx ..tom
