### ISSUE TITLE
How and where can i consume the "extra" object passed to RequestClientCredentialsAsync method

### ISSUE THREAD

**Issue by murtaza13** [IdentityServer/IdentityServer4#936]
I am trying to pass an extra parameter which i want to consume and write logic about,

var tokenResponse = await tokenClient.RequestClientCredentialsAsync("api1", new { a = "Hello World", b ="bye World" }); 

Now, I need to know where and how can i access the OBJECT which i have passed apart from my "api1" parameter?

**Comment by leastprivilege** [comment]
What do you want to achieve?

**Comment by murtaza13** [comment]
What I want to achieve here is pass on some extra information whilst requesting the token, and then use the extra information to do some custom validation at server side

**Comment by leastprivilege** [comment]
OK - then try implementing the `ICustomTokenRequestValidator` - there you have access to the request.

**Comment by leastprivilege** [comment]
does that work for you?

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
