### ISSUE TITLE
SSO with WinForms and Windows Authentication

### ISSUE THREAD

**Issue by twenzel** [IdentityServer/IdentityServer4#937]
I've a working WinForms sample application using IdentityModel.OidcClient2 login into IS4. It shows a browser window where I can choose "Windows" as external Provider.

How can I achive a login using the current logged in Windows User without showing any UI?

**Comment by leastprivilege** [comment]
By sending an idp hint via an acr_value, e.g.

append `acr_values=idp:Negotiate` to the authentication request

**Comment by twenzel** [comment]
Is this correct?
```
var result = await _oidcClient.LoginAsync(IdentityModel.OidcClient.Browser.DisplayMode.Hidden, extraParameters: new { acr_values = "idp:Negotiate" });
```
Then I recieve a "HttpError". And the browser window will still be shown.

**Comment by leastprivilege** [comment]
Couple of orthogonal issues:


* passing in the acr_values is correct - I verified that
* your windows provider might not be called negotiate - you need to go through the code where the view model for your login page gets created to see the internal name (depends a bit on host configuration)
* hiding the browser is not implemented in the sample - you would need to add that yourself.

**Comment by twenzel** [comment]
Maybe I found the error.
When I add the  `acr_values` value the request fail because of to much redirects. It ends in a loop in AccountController from Login/ExternalLogin -> ChallengeResult to Login/ExternalLogin again..

I have "fixed" this issue by removing the `acr_values` from value from the return url in AccountController.       ExternalLoginCallback().

```
...
// delete temporary cookie used during external authentication
await HttpContext.Authentication.SignOutAsync(IdentityServerConstants.ExternalCookieAuthenticationScheme);

// remove the acr_values in order to get redirected correctly
if (returnUrl.Contains("&acr_values"))
	returnUrl = returnUrl.Substring(0, returnUrl.IndexOf("&acr_values"));

// validate return URL and redirect back to authorization endpoint
if (_interaction.IsValidReturnUrl(returnUrl))
{
	return Redirect(returnUrl);
}
...
```
Now it work's fine.

Is this a bug or "by design"?

**Comment by leastprivilege** [comment]
Do you set the idp claim to the right name (the same value used on the acr_values) at signin time?

**Comment by twenzel** [comment]
No I never set an idp claim. Should I? Where?

**Comment by leastprivilege** [comment]
When the client request a certain idp - the server must set the idp claim - you can do that when calling `SignInAsync` in your external callback.

**Comment by twenzel** [comment]
I've added following code right before SignInAsync

```
// very rough code -> ONLY for testing
if (returnUrl.Contains("&acr_values="))
{
	var pairs = returnUrl.Substring(returnUrl.IndexOf("&acr_values=") + 12).Split(';');

	foreach(var pair in pairs)
	{
		var values = System.Net.WebUtility.UrlDecode(pair).Split(':');					
		additionalClaims.Add(new Claim(values[0], values[1]));					
	}
}
```
This adds a new "idp" claim with "Negotiate". But it does not help. I've to remove the  `acr_values` from the return url in order to get this working.

**Comment by leastprivilege** [comment]
The SignInAsync method has an identity provider parameter - try setting that to Negotiate.

Also check the logs. I think we would emit an error if the claim has not the right value.

**Comment by twenzel** [comment]
That worked. Setting the provider name to "Negotiate" (instead of "Windows") prior calling SignInAsync works, no error message.

```
if (returnUrl.Contains("&acr_values="))
{
	var pairs = returnUrl.Substring(returnUrl.IndexOf("&acr_values=") + 12).Split(';');

	foreach (var pair in pairs)
	{
		var values = System.Net.WebUtility.UrlDecode(pair).Split(':');					
		
		if (values[0] == JwtClaimTypes.IdentityProvider)
			provider = values[1];
	}
}

// issue authentication cookie for user
await HttpContext.Authentication.SignInAsync(user.SubjectId, user.Username, provider, props, additionalClaims.ToArray());
```

**Comment by leastprivilege** [comment]
Your parsing looks wrong to me ;)

Use the IIdentityServerInteractionService for turning the returnUrl into a object model
