### ISSUE TITLE
Sharing the results of some experiments.

### ISSUE THREAD

**Issue by rmbrunet** [IdentityServer/IdentityServer4#94]
Recently, I was installing IdentityServer 2.5 to make some tests and decided to experiment a little bit with some ideas which I am sharing here in case it might be useful (or totally wrong).
### Introspection Endpoint Security

The concept of an Scope secret seems a little bit odd to me and only allows for Basic Auth. It would be easier, I think, to create a Client with client_id = scope, Client Credentials Flow and AllowedScopes = "introspection" (new Standard Scope). Then, the endpoint could validate the credentials as is doing today (Basic) or the Resource Server could just ask for an access token to use in the endpoint with Bearer. All the functionality is already there.
### Scopes and Audiences in Jwt

I still think that Identity Server embraces Jwt but does not follow RFC 7519 with respect to the audience. A long time ago @leastprivilege suggested a possible alternative by including all resource scopes in the audience. I do like that idea very much. But I found myself in the situation that I need quite granular scopes often having several scopes per Resource Server; and does not make a lot of sense to have all these scopes in the aud claim. Then, it occurred to me to create the resource scopes using the convention resource_server.scope and to include in the audience claim only the resource_server part. With this approach the aud claim can be used to verify the token and the scopes to enforce the authorization to each particular action.
### Token encrypting

It would be nice to include the possibility of encrypted tokens even if not supported initially. This Jwt library is a very robust alternative to Microsoft's: https://github.com/dvsekhvalnov/jose-jwt

 Best Regards

**Comment by brockallen** [comment]
> Introspection Endpoint Security

We allow other credential types for authentication now.

> Scopes and Audiences in Jwt

Been discussed many times. This is by design.

> Token encrypting

It's coming in the Microsoft JWT library. Once they have it, we'll consider it.

**Comment by bashiransari** [comment]
Microsoft JWT library added Token encryption support still it's not supported in Identityserver also I cannot find any integration point in TokenValidator class to implement JWE support.
I have to copy TokenValidator code into my project change it and use it. 
Can you please at least provide an integration point for just token validation, you can make TokenValidator public and ValidateJwtAsync method protected virtual .

**Comment by leastprivilege** [comment]
Which token do you want to encrypt? identity or access token?

**Comment by leastprivilege** [comment]
Actually move that discussion to: #1847
