### ISSUE TITLE
[Question] [Best Practice] Relationship between user identity 'sub' with the domain identity

### ISSUE THREAD

**Issue by MahmoudElShazly** [IdentityServer/IdentityServer4#941]
Hi,

My question is regarding the best practice followed in relating the user 'sub' in IdSrv and the user id used in the application domain model.

Example, if in my domain I have a customer with a GUID as its customer id, and there is also an id (sub) stored in the identity db used with identity server, my strategy that I thought of is that when the customer registers to the identity server, I use its generated 'sub' and create a customer entity with the value of 'sub' as its id.

is that the right way to do things like this? my intention is to store every detail about the customer in the application domain model, and use only the IdSrv db for authentication and authorization process.

does that make sense, or that is not recommended and there is a better way?

Thanks

**Comment by brockallen** [comment]
> My question is regarding the best practice followed in relating the user 'sub' in IdSrv and the user id used in the application domain model.

They should be the same when you're designing around a SSO/centralized identity solution.

**Comment by MahmoudElShazly** [comment]
Thanks for your reply,

Sorry if this sounds a repetition,
I also believe those should be the same, but my question is, is the strategy I mentioned above the right/best way of doing that? is there any other best practice?

Thanks

**Comment by brockallen** [comment]
I don't understand... I think you just have a data problem, not a security problem.
