### ISSUE TITLE
Publishing Identity4 to IIS 8.5 unable to read openid-configuration

### ISSUE THREAD

**Issue by mjnorman** [IdentityServer/IdentityServer4#942]
- [X ] I read and understood how to enable [logging](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging)

### Issue / Steps to reproduce the problem
Walked through the example for creating identityserver 4 to issue tokens and an app to consume and authenticate users based on tokens.  Works fine on local dev machine.  Deploy both IdentityServer4 and API application to my QA box (Server 2012 IIS 8.5).

Tokens issued at localhost:5000/connect/token (works without issue, tokens issued correctly)
API hosted at localhost:5001/api/XXXX

### Relevant parts of the log file

```
Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerMiddleware
Exception occurred while processing message.

System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://localhost:5000/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'http://localhost:5000/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).

```
Followed by 
```
Microsoft.AspNetCore.Server.Kestrel
Connection id "0HL3E7DTFGQ0R": An unhandled exception was thrown by the application.

System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://localhost:5000/.well-known/openid-configuration'. ---> System.IO.IOException: IDX10804: Unable to retrieve document from: 'http://localhost:5000/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).

```

After doing some research I added the following headers to the web.config that ships when you publish .net core app, but to no avail.

```
<httpProtocol>
     <customHeaders>
       <add name="Access-Control-Allow-Origin" value="*" />
     </customHeaders>
   </httpProtocol>
```

Thanks for any advice you can give.

**Comment by mjnorman** [comment]
Forgot to mention the config file is able to be viewed remotely without issue (replaced hostname with MYSERVER obviously)--

```
{"issuer":"http://MYSERVER:5000","jwks_uri":"http://MYSERVER:5000/.well-known/openid-configuration/jwks","authorization_endpoint":"http://MYSERVER:5000/connect/authorize","token_endpoint":"http://MYSERVER:5000/connect/token","userinfo_endpoint":"http://MYSERVER:5000/connect/userinfo","end_session_endpoint":"http://MYSERVER:5000/connect/endsession","check_session_iframe":"http://MYSERVER:5000/connect/checksession","revocation_endpoint":"http://MYSERVER:5000/connect/revocation","introspection_endpoint":"http://MYSERVER:5000/connect/introspect","frontchannel_logout_supported":true,"frontchannel_logout_session_supported":true,"scopes_supported":["Callbacks","offline_access"],"claims_supported":[],"grant_types_supported":["authorization_code","client_credentials","refresh_token","implicit"],"response_types_supported":["code","token","id_token","id_token token","code id_token","code token","code id_token token"],"response_modes_supported":["form_post","query","fragment"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"subject_types_supported":["public"],"id_token_signing_alg_values_supported":["RS256"],"code_challenge_methods_supported":["plain","S256"]}
```

**Comment by brockallen** [comment]
As always, check your logs in IdentityServer

**Comment by mjnorman** [comment]
Thanks for the reply @brockallen.  I can't manage to get the logging to work with using IIS (probably something with the confounded App Identity Pools), but I ran it in console and I see the below--

```
2017-03-18 18:16:23.576 -04:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/.well-known/openid-configuration  
2017-03-18 18:16:23.654 -04:00 [Debug] AuthenticationScheme: "idsrv" was not authenticated.
2017-03-18 18:16:23.669 -04:00 [Debug] Request path "/.well-known/openid-configuration" matched to endpoint type Discovery
2017-03-18 18:16:23.669 -04:00 [Debug] Mapping found for endpoint: Discovery, creating handler: "IdentityServer4.Endpoints.DiscoveryEndpoint"
2017-03-18 18:16:23.669 -04:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.DiscoveryEndpoint" for "/.well-known/openid-configuration"
2017-03-18 18:16:23.669 -04:00 [Debug] Start discovery request
2017-03-18 18:16:23.935 -04:00 [Debug] Connection id ""0HL3E9HKQ73PD"" completed keep alive response.
2017-03-18 18:16:23.951 -04:00 [Information] Request finished in 383.8397ms 200 application/json
2017-03-18 18:16:24.044 -04:00 [Information] Request starting HTTP/1.1 GET http://localhost:5000/.well-known/openid-configuration/jwks  
2017-03-18 18:16:24.044 -04:00 [Debug] AuthenticationScheme: "idsrv" was not authenticated.
2017-03-18 18:16:24.044 -04:00 [Debug] Request path "/.well-known/openid-configuration/jwks" matched to endpoint type Discovery
2017-03-18 18:16:24.044 -04:00 [Debug] Mapping found for endpoint: Discovery, creating handler: "IdentityServer4.Endpoints.DiscoveryEndpoint"
2017-03-18 18:16:24.044 -04:00 [Information] Invoking IdentityServer endpoint: "IdentityServer4.Endpoints.DiscoveryEndpoint" for "/.well-known/openid-configuration/jwks"
2017-03-18 18:16:24.044 -04:00 [Debug] Start key discovery request
2017-03-18 18:16:24.247 -04:00 [Debug] Connection id ""0HL3E9HKQ73PD"" completed keep alive response.
2017-03-18 18:16:24.263 -04:00 [Information] Request finished in 213.0071ms 200 application/json
2017-03-18 18:18:04.265 -04:00 [Debug] Connection id ""0HL3E9HKQ73PD"" received FIN.
2017-03-18 18:18:04.265 -04:00 [Debug] Connection id ""0HL3E9HKQ73PD"" disconnecting.
2017-03-18 18:18:04.265 -04:00 [Debug] Connection id ""0HL3E9HKQ73PD"" sending FIN.
2017-03-18 18:18:04.265 -04:00 [Debug] Connection id ""0HL3E9HKQ73PD"" sent FIN with status "0".
2017-03-18 18:18:04.265 -04:00 [Debug] Connection id ""0HL3E9HKQ73PD"" stopped.
```

**Comment by mjnorman** [comment]
Until I have a good AD account to run the app pools under I just have both applications running under my NT login context so I can get logging working.

What I observe is that the token is issued without problem.  Then in the protected API application, it makes the request to `http://localhost:5000/.well-known/openid-configuration` which is where the IO exception occurs (same as what was visible in the eventlog from original post.)

```
2017-03-18 18:39:25.784 -04:00 [Error] Exception occurred while processing message.
System.InvalidOperationException: IDX10803: Unable to obtain configuration from: 'http://localhost:5000/.well-known/openid-configuration'
```

In the Identity server application log, it never receives that message.  It is being blocked somehow by IIS.  which is odd because I can browse to it from a remote computer without issue.

**Comment by brockallen** [comment]
I don't see anything that's erroring in the IdentityServer log. I'm guessing something is failing from IIS to Kestrel.

**Comment by mjnorman** [comment]
I agree. Any ideas on why I can't browse to that config file from the server itself, but can from remote server?

**Comment by brockallen** [comment]
No, sorry. It sounds environmental, as IIS works on my machine :)

**Comment by mjnorman** [comment]
Thanks for the additional info.  You mention it works in IIS on your machine.  Can you elaborate? Can you please provide the IIS settings you are using, the server and API web.configs, CORS etc?  I'm attempting the very basic client_credentials and also attempted the EF quickstart.  There is still something awry in the configurations here at least with IIS 8.5.  I noticed while perusing the Quickstart samples, that quickstart 8 the EF sample, in the API startup.cs, it is specifically enabling CORS--

```
services.AddCors(options=>
            {
                // this defines a CORS policy called "default"
                options.AddPolicy("default", policy =>
                {
                    policy.WithOrigins("http://localhost:5003")
                        .AllowAnyHeader()
                        .AllowAnyMethod();
                });
            });
```
Yet this is not in the regular client_credentials samples.  Why?  What does this do?  Is it required for Identity Server to work, and in what configuration scenario?  There isn't any mention of it being a requirement in any of the documentation which leads me to believe that you can just publish the quickstart samples and they will "just work," they don't.  Just not sure where to go from here?  Any advice?

**Comment by brockallen** [comment]
> Thanks for the additional info. You mention it works in IIS on your machine. Can you elaborate? Can you please provide the IIS settings you are using, the server and API web.configs, CORS etc?

I just run a `dotnet publish`  and then point an IIS app at the public directory and it works.

**Comment by mjnorman** [comment]
I just figured it out not 10 seconds after posting my last.  For some reason I was not able to get to "localhost:5000" on my prod/qa boxes.  However if I put the fully qualified name with port 5000 it works like a charm.  So for anyone else coming across this comment, if you run into trouble, do not use localhost (which might be the case for anyone running APIs and IdentityServer on the same boxes as in my case).  Could be something with IPv6, not sure.
