### ISSUE TITLE
Custom implementation of ICorsPolicyService

### ISSUE THREAD

**Issue by alaa9jo** [IdentityServer/IdentityServer4#943]
I've looked into the following documentations about custom implementation of `ICorsPolicyService` :
https://github.com/IdentityServer/IdentityServer4/blob/release/docs/topics/cors.rst
https://identityserver4.readthedocs.io/en/release/reference/options.html#cors

I created a custom class that implements `ICorsPolicyService` , but I don't know to register it in identityserver , and the documentation doesn't provide any samples on how exactly can I register custom `ICorsPolicyService`, it should be registered somehow before setting `CorsPolicyName` in IdentityServerOptions, right?

**Comment by teom10** [comment]
and the solution?
