### ISSUE TITLE
IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier

### ISSUE THREAD

**Issue by anirudhharidas** [IdentityServer/IdentityServer4#945]
I am getting a error like below.Can you please help me to fix this issue.

IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
   (
   IsReadOnly = False,
   Count = 1,
   Clause[0] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause
   )
', 
token: '{"alg":"RS256","kid":"dd7c611e160e00098b3d5507e49195a7","typ":"JWT"}.{"nbf":1488801076,"exp":1488802876,"iss":"http://ssostaging.test.com","aud":"ssgp.web","nonce":"636243978589730721.ZTkyNWM0OGEtMDc2Yy00NTY4LWE0YzAtOTgzZDYzYTY5YWE3NjZhZGMzZWMtODU2OS00YjExLTk4ZDQtZThjYTA2OWRlYjYz","iat":1488801075,"c_hash":"sdTV6pjqxIhkEvEqjT7ogA","sid":"9a7a3bab09a596b8fb9f8fe6aaa2a98c","sub":"1","auth_time":1488801075,"idp":"local","amr":["pwd"]}
RawData: eyJhbGciOiJSUzI1NiIsImtpZCI6ImRkN2M2MTFlMTYwZTAwMDk4YjNkNTUwN2U0OTE5NWE3IiwidHlwIjoiSldUIn0.eyJuYmYiOjE0ODg4MDEwNzYsImV4cCI6MTQ4ODgwMjg3NiwiaXNzIjoiaHR0cDovL3Nzb3N0YWdpbmcuc2hhcmphaC5hZSIsImF1ZCI6InNzZ3Aud2ViIiwibm9uY2UiOiI2MzYyNDM5Nzg1ODk3MzA3MjEuWlRreU5XTTBPR0V0TURjMll5MDBOVFk0TFdFMFl6QXRPVGd6WkRZellUWTVZV0UzTmpaaFpHTXpaV010T0RVMk9TMDBZakV4TFRrNFpEUXRaVGhqWVRBMk9XUmxZall6IiwiaWF0IjoxNDg4ODAxMDc1LCJjX2hhc2giOiJzZFRWNnBqcXhJaGtFdkVxalQ3b2dBIiwic2lkIjoiOWE3YTNiYWIwOWE1OTZiOGZiOWY4ZmU2YWFhMmE5OGMiLCJzdWIiOiIxIiwiYXV0aF90aW1lIjoxNDg4ODAxMDc1LCJpZHAiOiJsb2NhbCIsImFtciI6WyJwd2QiXX0.Sg1FDl8gOBrt0rv-wAPxImP02jM6FGbfBesJtpsHmN-y2Qj-4sL-XRTX4XpczFbuVuXlAqi90YNZDJwYEY4tLw_vfUzymYqEaIb0udnf4nMN6rRhtbCpy8BmmcTm84fkMGL-kE_m5ybhrK2dhEJUyoeFjkTrtHIy5yEndrrga4bgciPlk7U9au0KGjiQbni1wHZB4ihcebdhpB25_s3BCHvQUCzKRs7Pd5WCbrL4tq2J0Aq7tW20-72u6m0BjjTSNrfwdG9tRySNU7JbWPs_aMYbeyC1oA09VSUEm-_LeTTJXyh-ter7Ktfv3gBAolsJBJuwinCOEQsokeMQFs9CIA'.

And the discovery looks like below

http://localhost:5000/.well-known/openid-configuration/jwks

{"keys":[{"kty":"RSA","use":"sig","kid":"598503d025b8c875f16ee7b15802b668","e":"AQAB","n":"3nkLIGW_lhnmVcqet2L8jYHrbaFpvVsKajMTkUT9JKA9x3d_iLsI-T7McR-aFBDZiV3HiBZ90eAN7ocP3FNiFGACO2ued34UajJ1s2WND3qx_TOnByJ1Tlnt-P-E87RwsCzNgHHkbMqzHTls1g-NqBFcLJqZs6TomCgQB4beCwM7G5QWywMWVaVlgvF3zs2S7LdtX2VM41mnxg07hOZEz6P80ej1ckwHZrwuDERX65tFls2bdkPGziiMxGMGziVFs_lc5CV3rWjpG9Xs1_cIlf3dZln4BZie1Fo9VrRUcB9H7j_0sc42zGbj4wn_4fUNRgvKcFngnUF1JwPa-BmmjQ"}]}

**Comment by leastprivilege** [comment]
How do you setup the key in IS?

**Comment by anirudhharidas** [comment]
This is my  ConfigureServices Code

    public void ConfigureServices(IServiceCollection services)
        {
            var builder = services.AddIdentityServer(options =>
               {
                   options.Authentication.FederatedSignOutPaths.Add("/signout-callback-aad");
                   options.Authentication.FederatedSignOutPaths.Add("/signout-callback-idsrv3");
                   options.Authentication.FederatedSignOutPaths.Add("/signout-callback-adfs");
               });
               builder.AddInMemoryClients(Clients.Get());
            builder.AddInMemoryIdentityResources(Resources.GetIdentityResources());
            builder.AddInMemoryApiResources(Resources.GetApiResources());
            builder.AddTemporarySigningCredential();
            builder.AddExtensionGrantValidator<Extensions.ExtensionGrantValidator>();
            builder.AddSecretParser<ClientAssertionSecretParser>();
            builder.AddSecretValidator<PrivateKeyJwtSecretValidator>();
            builder.Services.AddTransient<IProfileService, ProfileService>(); 

            services.AddMvc();
        }

Please let me know if you are taking about the above code or else can you please guide me to fix it.

**Comment by leastprivilege** [comment]
`builder.AddTemporarySigningCredential();`

Do you know what you are doing here?

**Comment by anirudhharidas** [comment]
Yes i know this for the development purpose.Is that the cause for the issue?If  yes how can i set it for the production environment.

**Comment by leastprivilege** [comment]
this means that every time you start up you get a new key pair - and you api's cached config gets out of sync.

Set a static credential like an x509 cert to get around that.

**Comment by anirudhharidas** [comment]
can you please give me some reference link to create a stable RSA key pair method or Set a static credential like an x509 cert .It would very helpfull

**Comment by leastprivilege** [comment]
https://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/
