### ISSUE TITLE
Which version applies to.Net core 1.0?

### ISSUE THREAD

**Issue by yhdkzy** [IdentityServer/IdentityServer4#946]
Which version applies to.Net core 1.0? thanks

**Comment by leastprivilege** [comment]
We require ASP.NET Core 1.1 - and I think this also means you want to combine that with .NET Core 1.1 (or the full .NET Framework).

**Comment by yhdkzy** [comment]
Can I use vs2015 Update3 and identityserver4 for development? thanks

**Comment by leastprivilege** [comment]
I probably works - but it's not supported anymore (nor by us or Microsoft). 

I recommend using VS2017 (community edition).
