### ISSUE TITLE
The client and server cannot communicate, because they do not possess a common algorithm

### ISSUE THREAD

**Issue by anirudhharidas** [IdentityServer/IdentityServer4#947]
I am getting one error when the identity server host is SSL attached domin.My Client is a web api project .
 I know this issue is not related to your identity server.But it would be very helpful if you have any solution
issue:

The client and server cannot communicate, because they do not possess a common algorithm

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ComponentModel.Win32Exception: The client and server cannot communicate, because they do not possess a common algorithm

Source Error: 

Line 20:         {
Line 21:             JwtSecurityTokenHandler.InboundClaimTypeMap.Clear();
Line 22:             app.UseIdentityServerBearerTokenAuthentication(new IdentityServerBearerTokenAuthenticationOptions
Line 23:             {
Line 24:                 Authority = ConfigurationManager.AppSettings["SSOBaseAddress"].ToString(),

![error](https://cloud.githubusercontent.com/assets/19528279/24092462/6f4538f8-0d74-11e7-8f80-681fe5d7653f.png)

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
