### ISSUE TITLE
Cookie validation for apis

### ISSUE THREAD

**Issue by jimmystridh** [IdentityServer/IdentityServer4#948]
Hi,

I have a javascript SPA as well as a native app I want to do authentication&authorization for.

The apis are multiple services (separate .NET core apps) behind an application proxy (Traefik), basically like this:

```
api.example.com/
  /api1
  /api2
  /identityserver
```

For the native app, all the examples of tokens issuing & token validation incl refres tokens work perfectly.

For the javascript app I want it to handle it's own login dialog, to provide a better user experience than redirecting the user around, since I control the app. That would work fine if use Resource Owner Password Validation and store the token in LocalStorage on the client. However since local storage is discouraged for storing secrets, and the recommended method i Secure, HttpOnly cookies, that's what I would like to do.

Is this a scheme that could be supported ? Looking at IdentityServer4.AccessTokenValidation there doesn't seem to be any cookie handling but it seems like I could have my own middleware before that one to extract the cookie and place it in `idsrv4:tokenvalidation:token` perhaps. It feels somewhat hacky though.

What are your thoughts ?
Thanks

**Comment by leastprivilege** [comment]
We don't recommend it nor support it. Local storage is not an issue for storing secrets as long as you use CSP (which you should anyways).

**Comment by jimmystridh** [comment]
Thanks for the response Dominick, I'll re-evaluate using local storage + CSP (which I don't have ATM).

Out curiosity and wanting to understand; any references or comments on why you don't recommend cookie based token auth ?

**Comment by leastprivilege** [comment]
Because of CSRF - and cookies are a browser-only mechanism.

**Comment by jimmystridh** [comment]
Reasonable view. Reading up on CSP, thanks for the input & hard work on idsrv! Going to help out some with the improving the docs when I'm more familiar with the lots.
