### ISSUE TITLE
FileNotFoundException When Targeting Framework net462

### ISSUE THREAD

**Issue by bburman** [IdentityServer/IdentityServer4#95]
I'm new to both IdentityServer4 and ASP .NET Core, but this reared its head after upgrading to RC2 yesterday. It's quite possible that I'm doing something wrong.

Since IdentityServer4 is now specifying netstandard1.5 for the framework, I am targeting net462 in my project.json file. All NuGet packages restore successfully. There are no errors or warnings in the build process.

I can launch the app, but when the Build() method of the WebHostBuilder is invoked, I receive an exception stating that version 4.1.0.0 of the System.Runtime assembly could not be loaded. I have to manually copy the following assemblies into the bin/Debug/net462/win7-x64 directory in order to run the application:

- System.Runtime 4.1.0-rc2-24027
- System.Runtime.Extensions 4.1.0-rc2-24027
- System.Linq 4.1.0-rc2-24027

NuGet seems to think that, even though IdentityServer is targeting netstandard1.5, the above assemblies should be 4.0.20.

**Comment by rmja** [comment]
Try and add the assemblies like this in the `frameworks` section in project.json:

```
"frameworks": {
    "net46": {
      "frameworkAssemblies": {
        "System.Runtime": "4.0.20.0"
      }
    }
  }
```

I have not tried it with `net462` though.

**Comment by bburman** [comment]
Unfortunately this won't work, as the latest version of IdentityServer4 requires .NET 4.6.2 or above (because it targets netstandard1.5). If I augment your suggestion above, target net462, and add the missing assemblies to the frameworkAssemblies section, they are still not copied to the bin folder.

This may be, more or less, more of a problem with the .NET 4.6.2 installer. It appears that all of the .NET assemblies are installed in the Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2 directory:

![image](https://cloud.githubusercontent.com/assets/19496701/15472853/b289aefe-20c2-11e6-9c5a-d427bf1007f1.png)

These three files are missing from this directory. When I add them to the frameworkAssemblies section and then view the Add Reference dialog from within Visual Studio, it looks like this:

![image](https://cloud.githubusercontent.com/assets/19496701/15472907/fa965cc4-20c2-11e6-9965-e12dcb10bf10.png)

Notice the version number picked up by Visual Studio is 1.0.0.0, signifying that it can't find those assemblies...

**Comment by leastprivilege** [comment]
i updated all the packages - give it a go and see if that works better for you (and open a new issue if you encounter problems)

**Comment by bburman** [comment]
Works like a champ! Thanks, @leastprivilege!
