### ISSUE TITLE
An unhandled exception occurred while processing the request.  CryptographicException: OpenCSP failed

### ISSUE THREAD

**Issue by anirudhharidas** [IdentityServer/IdentityServer4#950]
I am Getting a error like below after changing temporary
![error-1](https://cloud.githubusercontent.com/assets/19528279/24104745/f97a9e6c-0da8-11e7-91af-c9885ad5dc4c.png)
 signing to builder.AddSigningCredential("CN=ssgpcn");
I followed https://brockallen.com/2015/06/01/makecert-and-creating-ssl-or-signing-certificates/ lin to create certificate

An unhandled exception occurred while processing the request.

CryptographicException: OpenCSP failed with error code 2148073494.
Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, bool randomKeyContainer)

**Comment by brockallen** [comment]
Sorry, not sure. Searching came up with this: https://stackoverflow.com/questions/42102401/opencsp-failed-with-error-code-2148073494

**Comment by leastprivilege** [comment]
make sure the process account has read access to the private key.

**Comment by anirudhharidas** [comment]
I have changed the signing method .And the above issue is not showing

**Comment by leastprivilege** [comment]
which doesn't help me at all..

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
