### ISSUE TITLE
UI Front end for Entity Framework persistence

### ISSUE THREAD

**Issue by mjnorman** [IdentityServer/IdentityServer4#952]
Question only -- Is there a front end available for administration of the persistent store in SQL?

**Comment by leastprivilege** [comment]
yes - soon.

https://www.identityserver.com/upcoming-products/

**Comment by ima-tech** [comment]
Any news on the Q1 Release?

**Comment by leastprivilege** [comment]
You can beta test - did you leave your email on their site so they know about you?

**Comment by ima-tech** [comment]
Yes I did, but no news.

**Comment by vdecristofaro** [comment]
I did it to. No news also

**Comment by alexsandro-xpt** [comment]
Waiting for....
