### ISSUE TITLE
OpenID Connect id_hash validation incorrect value

### ISSUE THREAD

**Issue by damienbod** [IdentityServer/IdentityServer4#954]
I'm using the OpenID Connect Implicit Flow (id_token token). When I successfully login, IdentityServer4 returns an id_token and an access_token as per spec. When I validate the id_token.at_hash value, it does not match the access_token per spec.

Note, I assume this is because my access token is a reference token. Should this not validate anyway? 

at_hash
    REQUIRED. Access Token hash value. If the ID Token is issued with an access_token in an Implicit Flow, this is REQUIRED, which is the case for this subset of OpenID Connect. Its value is the base64url encoding of the left-most half of the hash of the octets of the ASCII representation of the access_token value, where the hash algorithm used is the hash algorithm used in the alg Header Parameter of the ID Token's JOSE Header. For instance, if the alg is RS256, hash the access_token value with SHA-256, then take the left-most 128 bits and base64url-encode them. The at_hash value is a case-sensitive string. 

{
  "alg": "RS256",
  "kid": "06D3E46E91073C5D4BC2C9983BE9FF448CF640D4",
  "typ": "JWT",
  "x5t": "BtPkbpEHPF1LwsmYO-n_RIz2QNQ"
}

{
  "nbf": 1489916740,
  "exp": 1489917040,
  "iss": "https://localhost:44363",
  "aud": "singleapp",
  "nonce": "N0.308197602232886061489916736051",
  "iat": 1489916740,
  "at_hash": "fe4IzKhg7e-Pqm83tn91Mg",
  "sid": "dca13d5850169e8f87da723d97d07911",
  "sub": "ace69c61-3493-4f5d-8359-927e0d537889",
  "auth_time": 1489916516,
  "idp": "local",
  "amr": [
    "pwd"
  ]
}

access_token:
"e944994b6672db5a4a8ec2f46432facdf0b032fdf0fff0aa7a3aa437871166c1"

id_token:
"eyJhbGciOiJSUzI1NiIsImtpZCI6IjA2RDNFNDZFOTEwNzNDNUQ0QkMyQzk5ODNCRTlGRjQ0OENGNjQwRDQiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJCdFBrYnBFSFBGMUx3c21ZTy1uX1JJejJRTlEifQ.eyJuYmYiOjE0ODk5MTY1MTYsImV4cCI6MTQ4OTkxNjgxNiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNjMiLCJhdWQiOiJzaW5nbGVhcHAiLCJub25jZSI6Ik4wLjY2MzE3NjA0MTE5MDM1OTExNDg5OTE2NDk2NTU2IiwiaWF0IjoxNDg5OTE2NTE2LCJhdF9oYXNoIjoiVG81SWlwLXp4bXpaZWh5U2Q2aVcxQSIsInNpZCI6ImRjYTEzZDU4NTAxNjllOGY4N2RhNzIzZDk3ZDA3OTExIiwic3ViIjoiYWNlNjljNjEtMzQ5My00ZjVkLTgzNTktOTI3ZTBkNTM3ODg5IiwiYXV0aF90aW1lIjoxNDg5OTE2NTE2LCJpZHAiOiJsb2NhbCIsImFtciI6WyJwd2QiXX0.m_PzEczhIhVppYyLgexHtpTvUah_cH0hthrYNYSH1YRkKWgf7aOW-QuYZcAxxDNcHfZ7GWXKSuOnRjJw05HLj9vvwcvJuGWkuokyTMPlz9PGA-Ar2afFlSJuH2rKYpvlTOG_cSfsEX-tCNSqhQwsLl6GwdSsaUXO2Fiz-Je6HhQhO3fieUbCsywSKDAl17PLipXc1JkOtj8FoCG7m_Ttfib_we3Y89mPv2z5lddGFw-MzZg3sGW5TQjQTibHZz-41fRFizkJ_tbjtiwSry6zPxTKNI2dsd2EYkxCQqXzyua3KoBOp0VsyWz6_J7OmCF8D790cIwaPC3wwcSfRJDbaA

**Comment by leastprivilege** [comment]
This should work with reference tokens as well. Try Brock's library - it has a JS implementation.

**Comment by damienbod** [comment]
sorry, tested with the wrong access_token
