### ISSUE TITLE
Bring id_token validation endpoint back?

### ISSUE THREAD

**Issue by leastprivilege** [IdentityServer/IdentityServer4#958]

**Comment by brockallen** [comment]
![1e6](https://cloud.githubusercontent.com/assets/649492/24166198/e4d52f0e-0e48-11e7-83da-d58f090ad378.jpeg)

**Comment by leastprivilege** [comment]
as an alternative to JS client side validation?

**Comment by brockallen** [comment]
yea, seems fine to me

**Comment by Mardoxx** [comment]
I assume this is for validating `id_token`s provided from a different STS?

**Comment by brockallen** [comment]
No, it's for providing a way for a client to validate a id_token if they don't have a proper JWT/OIDC validation library.

**Comment by Mardoxx** [comment]
Surely if you can't (don't) trust that your received id_token is valid, the response from sending it off to get validated can't be trusted either? So it's a little unnecessary?

As I understand it, the idea of validating id_token client side is so you can be sure it wasn't tampered with before being received? So if you don't trust your sts then sending it back to get validated just seems silly?

Or have I completely missed the point?

**Comment by brockallen** [comment]
> Surely if you can't (don't) trust that your received id_token is valid, the response from sending it off to get validated can't be trusted either?

Trust is established via TLS.

**Comment by damienbod** [comment]
@leastprivilege @brockallen I don't see the point of this, how does this improve the security or trust of the id_token? The client must validate the id_token and also the access_token if used.

**Comment by leastprivilege** [comment]
It's for clients that can't or want to do their own crypto to validate the tokens themselves (which all in all is pretty involved).

Some people e.g. complain that the JS library is too big because it has all the crypto stuff built-in. Some people complain that JS crypto does not use "approved" OS crypto - etc

In these situations a server side id token validator helps.

**Comment by Mardoxx** [comment]
So it's okay that the op validates the token, not the actual client?

**Comment by leastprivilege** [comment]
Well - someone you trust. You could build such an endpoint also yourself.

This is not my first choice - but for certain situations this certainly better than not validating the token at all.

**Comment by leastprivilege** [comment]
no.
