### ISSUE TITLE
How to implement google and facebbok external providers in xamarin.android application using idsrv4

### ISSUE THREAD

**Issue by amruta455** [IdentityServer/IdentityServer4#959]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I am trying to implement external authentication in xamarin.android application using idsrv4, for that I have enabled google authentication in idsrv using this code - 
app.UseGoogleAuthentication(new GoogleOptions
            {
                AuthenticationScheme = "Google",
                SignInScheme = "Identity.External",
                ClientId = xxx.apps.googleusercontent.com",
                ClientSecret = "xxx"
            });
But when I am trying to authorize using google It is giving me disallowed_useragent error.So how to cretae client id ,client secret for the android paltform in the google develper console and what is redirect url for android application.
I went through this link - https://github.com/IdentityModel/IdentityModel.OidcClient.Samples    
but I am not getting how to set up that client.
### Relevant parts of the log file

```
<log goes here>
```

**Comment by leastprivilege** [comment]
Are you using an Android WebView to show the google login page? This might not be allowed anymore.

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

and 

https://stackoverflow.com/questions/41801836/how-can-google-detect-a-request-is-from-a-webview

**Comment by sailikudalakar** [comment]
Thanks for the quick reply.
Is it possible to authenticate xamarin.android application using idsrv4 with google/facebook external login providers.
If there is any other way to do external authentication from xamarin.android using idsrv4 please suggest me.

**Comment by leastprivilege** [comment]
You can't use a webview - use the system browser instead (Chrome custom tab).

**Comment by sailikudalakar** [comment]
Now I am using Chrome custom tab for log in using google.In that I am giving my machine IP address in the authority URL to connect my xamarin.android application to the idsrv4 project.
So my authority url is  - http://xxx.xxx.xx.xx:portnumber//
but when trying to open sign in page of the google it is giving me error -  Invalid_request
Invalid parameter value for redirect_uri:Raw Ip addresses not allowed:http://xxx.xxx.xx.xx:portnum/Signin-google.
My facebook login is working with web view If we have to use chrome custom tab for google authentication is it necessary to use same custom view for the facebook also ?

**Comment by leastprivilege** [comment]
yes - read this spec please. This is not an IdentityServer issue:

https://tools.ietf.org/html/draft-ietf-oauth-native-apps-09
