### ISSUE TITLE
Fork of IS3 EF, TwentyTwenty for Data Persistence

### ISSUE THREAD

**Issue by PivotalAnimal** [IdentityServer/IdentityServer4#96]
I created a repo based on IS3 EF, 'TwentyTwenty' and RigoFunc (among others) Contributions welcome. SEE:
[BlueConcord.IdentityServer.EntityFrameworkCore](https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore)
[https://github.com/IdentityServer/IdentityServer3.EntityFramework](https://github.com/IdentityServer/IdentityServer3.EntityFramework)
[TwentyTwenty](https://github.com/2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore)
[https://github.com/xyting/RigoFunc.IdentityServer](https://github.com/xyting/RigoFunc.IdentityServer)
[https://github.com/aspnet/Identity](https://github.com/aspnet/Identity)

**Comment by brockallen** [comment]
Are you planning on doing a full EF implementation for client, cors, scope, and operational stores?

**Comment by ericgreenmix** [comment]
Just FYI, our https://github.com/2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore has been ported to RC2 IS4 beta 2. Will be published to nuget tomorrow. Not sure what the purpose of his fork was here...

**Comment by PivotalAnimal** [comment]
I'm still figuring this out as I go. The project currently stores maps between its own POCO classes and IS4 POCO classes. They are: Scope, ScopeClaim, ScopeSecret, ClientSecret and Client. I have read through some of the RFCs: 7523 / 6750. I have also watched the excellent video 'Intro to OpenID Connect' and have taken note of the resources it mentions. My primary goal of the fork is as a learning experience and to demo the usage of IS4 using entity framework. Out of the box IS4 only uses an in memory data store so I need data persistence. Along with my primary goal of using this as a place to learn, I am going to create a website that makes use of this functionality to try and help other developers along. I aim to use the JavaScript examples in the demo apps as a foundation for an Angular2 approach. The reason I did this at all is because I am new to contributing to github and did not realize there was a new branch available from TwentyTwenty that was being worked on for RC2. it appeared to me at the time that it was a stagnant project. Now I know.

**Comment by jarroda** [comment]
We have pushed a nuget package with EF Core support. https://www.nuget.org/packages/TwentyTwenty.IdentityServer4.EntityFrameworkCore/

**Comment by totht91** [comment]
@jarroda Do you plan to create an ASP.NET Identity Core support package for IdSvr4?

**Comment by ericgreenmix** [comment]
@totht91 I have an implementation of Identity Core working with IS4. I am going to compile gists of it's basic usage and publish those later this week. I don't think there is a way to abstract out all the user stuff to it's own nuget, as it is very custom.

**Comment by PivotalAnimal** [comment]
I updated the BlueConcord Fork. The Host project should be working soon I hope. I think it will be extremely helpful to other developers to have a full on working EF example. I am still getting familiar with IS4 code and what not. Contributions welcome.

**Comment by Codelnw** [comment]
@ericgreenmix Where would be the place to keep an eye on for the compilation of those gists ?

**Comment by PivotalAnimal** [comment]
I was thinking of maybe trying to update IdentityServer3.EntityFramework to a pure IS4 / RC2 solution. Besides referencing different libraries and dealing with the new nuances of EF Core and namespace changes, has much changed between IS3 and IS4? Would you view this as a worthy pursuit?

**Comment by PivotalAnimal** [comment]
I added EF Migrations to my code. You can clone the repo then run 'Update-Database.' See readme. Now I need to seed the data. There are a lot of columns in the Clients table. This mirrors the Client class in the IS4 project. Does anyone know what the default values should be? I could toy with the EF attributes so that it will be easier to add new clients. I would imagine that changing some of the fields to nullable is undesirable.

**Comment by TheRubble** [comment]
@ericgreenmix Are those gists available?

**Comment by Codelnw** [comment]
@TheRubble You should take a look at this repo:
https://github.com/tibold/IdentityServer4.Contrib.AspNetIdentity

**Comment by PivotalAnimal** [comment]
I am trying to create a hybrid of that and 20|20 for scope, claim and user stores. Still a work in progress. Contributions / suggestions welcome. See: https://github.com/PivotalAnimal/BlueConcord.IdentityServer.EntityFrameworkCore

**Comment by Codelnw** [comment]
@PivotalAnimal 
You might want to cosider contributing to this repo instead:
https://github.com/2020IP/TwentyTwenty.IdentityServer4.EntityFrameworkCore

**Comment by PivotalAnimal** [comment]
@Codelnw I might. Right now I am trying to get an example working. Anyone serious about OAuth should read rfc6749 / 6750, visit @leastprivilege website opened.net, pluralsight, etc. There is a ton of great info out there and I am just trying to get up to speed.

**Comment by PivotalAnimal** [comment]
As a followup, my project is more complete now yet still a work in progress. If interested, get latest, restore nuget packages, then run prerequisite requirements outlined in read me for project. After you have seeded the database, you will be able to run the IS4 'MVC and API' example against it. You will have to change the Authority parameter, but that should be about it. I have tried to make the example as painless as possible.

**Comment by brockallen** [comment]
Marking with docs so we can add links to these projects.

**Comment by leastprivilege** [comment]
We started our own EF repo - please join us there and contribute to improve the library.
