### ISSUE TITLE
How to maps users from Javascript Client to IdentityServer4

### ISSUE THREAD

**Issue by GrantHoffman** [IdentityServer/IdentityServer4#960]
### Issue / Steps to reproduce the problem

I'm trying to Map users from the Javascript client to the Web-api and Pass the profile token so I have the claims data the first time a user logs in.

normally we send the access token like so:

    `var xhr = new XMLHttpRequest();
        xhr.open("GET", url);
        xhr.onload = function () {
             log(xhr.status, JSON.parse(xhr.responseText));
        }
        xhr.setRequestHeader("Authorization", "Bearer " + user.access_token);
        xhr.send();`

On my WebApi I'm using the JwtBearerEvents to intercept 

`app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
{
    Authority = "http://localhost:5000",
    RequireHttpsMetadata = false,

    ApiName = "api1",

    Events = new CustomBearerEvents() 
    {
        OnTokenValidated = async context =>
        {
            //Grab out claims data etc.
        }
     }
});`

When I go to grab out the claims data the profile claims are not there. How can I append the claim data to the initial request I want to do something like this but i do not know the proper header

    xhr.setRequestHeader("Authorization-Profile", "Bearer " + user.profile);

Alternatively I Could call a method from the call back with the claims data pre-populated, to update the user information, but I'm really just trying to understand the proper flow of linking the users from IdentityServer to an external db which is consumed by web api

**Comment by granthoff1107** [comment]
This should be relatively simple I'm just looking for the proper way to map my users from Web-Api to IdentityServer4

**Comment by GrantHoffman** [comment]
I know everyone is busy but, can someone please field issue to have the label question so I know it's been looked at

**Comment by brockallen** [comment]
The access token contains a `sub` claims -- that's the user identifier.

**Comment by GrantHoffman** [comment]
Thank you for responding:

I'm using Custom bearer events to authenticate when I try to request the Sub Claim i am returned null

app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
{
    Authority = "http://localhost:5000",
    RequireHttpsMetadata = false,

    ApiName = "api1",

    Events = new JWTCustomBearerEvents() 
    {
        OnTokenValidated = async context =>
        {
              //Pseudo
             var claimsIdentity = context as ClaimsIdentity.
             
              var subject = claimsIdentity.claims.ToList().Where(x => x.Type == 'sub)'.First()
               
        }
     }
});

I'm using this to obtain the subject but the claim is null? Am I doing something wrong here

**Comment by brockallen** [comment]
What claims are in there?

**Comment by GrantHoffman** [comment]
There is 13 of them but off the top of my head, Role, Admin, OpenId, Something called PWD,  I can post everything when I get home tonight. 

Just wondering the way i'm trying grabbing the subject looks correct right is that the proper flow

**Comment by brockallen** [comment]
I don't know from the little I can see -- it seems ok, but you'll have to do some debugging I guess.

**Comment by GrantHoffman** [comment]
is there an easy way I can just send the Id_Token with the Access token in the Authorization Request so all of the claims are included?

**Comment by brockallen** [comment]
It doesn't work that way. id_token is for the client. access_token is meant for the API. How are you getting the access_token -- what flow? Client credentials or via some other flow from the app?

**Comment by GrantHoffman** [comment]
I'm using the Identity-Server to Javascript client to web-api.  In my client I get the Access_Token and Id_Token fine, I can see the claims in the Id token using the sample you've provided.  

I know I can use a web-api endpoint to update the user information,  but I need to assure that the subject Id has not been modified, so the only way to do that would be through the access token unless there was a way to valid the id_token, but I know the Id_Token Validation end point has been removed

**Comment by brockallen** [comment]
As I said, id_tokens are not designed to be sent to the API for authentication/validation. Perhaps Microsoft's code is converting the claim types -- do you see a "NameIdentifier" claim in there instead? If so, then you need to add JwtSecurityTokenHandler.InBoundClaimTypeMap.Clear() or JwtSecurityTokenHandler.DefaultInBoundClaimTypeMap.Clear() (depending on the API version you're using).

**Comment by GrantHoffman** [comment]
I know I have that in one of my projects but I'm not sure which whether I just put that in the IdentityServer Project instead of the Web-Api,  I'll investigate this when I get home Thanks for your time!

**Comment by granthoff1107** [comment]
It seems, I was requesting SubjectId just using the wrong Identifier :/. Thank you for your help!
