### ISSUE TITLE
duplicate key value violates unique constraint "IX_ApiScopes_Name"

### ISSUE THREAD

**Issue by dudedev** [IdentityServer/IdentityServer4#964]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
I have implemented an API to manage API Resources of IdentityServer (IdentityServer4). 
If I try to update an API Resource, I get this database error. **"duplicate key value violates unique constraint "IX_ApiScopes_Name".**

Code to update database:
```
        public void Update(IdentityServer4.Models.ApiResource apiResource)
        {
            _context.ApiResources.Update(apiResource.ToEntity());
            _context.SaveChanges();
        }
```
To test the update method, I get the ApiResource using get method and just change the description/displayName of the received model, and send it back to update endpoint.
```
{
  "enabled": true,
  "name": "api1",
  "displayName": "Updated display name",
  "description": null,
  "apiSecrets": [],
  "userClaims": [],
  "scopes": [
    {
      "name": "api1",
      "displayName": "My API",
      "description": null,
      "required": false,
      "emphasize": false,
      "showInDiscoveryDocument": true,
      "userClaims": []
    }
  ]
}
```
If I remove the scopes part and just change the displayName, then I get following error: 
```
Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

### Relevant parts of the log file

```
<log goes here>
```

**Comment by brockallen** [comment]
Wrong repo -- this should be in the EF repo.
