### ISSUE TITLE
AuthorizeResult and ErrorMessage discard the ErrorDescription in AuthorizeResponse

### ISSUE THREAD

**Issue by mackie1001** [IdentityServer/IdentityServer4#965]
I have a requirement to perform additional validation on authorize endpoint requests to enforce a policy around 2FA use. As part of this I need to present a friendly message to the end user. _ICustomAuthorizeRequestValidator_ is great and allows me to do exactly what I want, including specifying an _ErrorDescription_ in the returned result. However when this reaches _AuthorizeResult.RedirectToErrorPageAsync()_ it does not pass/persist the _ErrorDescription_ property. 
Could I possibly request that you add support for this to _IdentityServer4.Models.ErrorMessage_ and _IdentityServer4.Endpoints.Results.AuthorizeResult_ please?

**Comment by brockallen** [comment]
Ok, done.

**Comment by mackie1001** [comment]
This appears to still be an issue. If I set  AuthorizeRequestValidationResult.ErrorDescription in my ICustomAuthorizeRequestValidator even the TokenIssuedFailureEvent raised immediately after the call to ValidateAsync() does not include the description. It does not get picked up when I call IIdentityServerInteractionService.GetErrorContextAsync() either. 

It looks like this is the culprit:
```
            if (customResult.IsError)
            {
                LogError("Error in custom validation: " + customResult.Error, request);
                return Invalid(request, customResult.Error);
            }
```
The call to Invalid() is not passing the ErrorDescription from customResult.
