### ISSUE TITLE
builder.Services.TryAddTransient<IEventService, DefaultEventService>() repeats twice

### ISSUE THREAD

**Issue by mikeandersun** [IdentityServer/IdentityServer4#969]
` builder.Services.TryAddTransient<IEventService, DefaultEventService>();` repeats twice in 
` public static IIdentityServerBuilder AddPluggableServices(this IIdentityServerBuilder builder)` method of `https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/BuilderExtensions/Core.cs`
It have technical reason?

**Comment by leastprivilege** [comment]
thanks for reporting. fxed.
