### ISSUE TITLE
Lose logoutId when single-signout.

### ISSUE THREAD

**Issue by atpyk** [IdentityServer/IdentityServer4#970]
The reproduce steps:
1. Login MVCClient by user "Ray".
2. Disable the user "Ray", (Customize the IProfileService to judge the user status)
3. Logout on MVCClient by current user "Ray".

Expect: I can get the LogoutId when it call the "Logout(string LogoutId)" action in Idsvr4.

Actual: the LogoutId is null, I cannot redirect back to MVCClient.

**Comment by brockallen** [comment]
That's because part of the validation of the id_token checks the profile service to see if the user is still active or not. // @leastprivilege

**Comment by leastprivilege** [comment]
I see the problem - needs discussion.

**Comment by brockallen** [comment]
In your IsActive you can check the `IsActiveContext`'s `Caller` for the constant `"IdentityTokenValidation"` to know if it's this scenario.
