### ISSUE TITLE
How to configure OpenIdClient Created using Framework 4.5 for Identity Server 4 

### ISSUE THREAD

**Issue by ShashikantMaurya** [IdentityServer/IdentityServer4#971]
Hi,

I have used Identity Server 4,and I want to configure OpenIdClient for it,

Please help..

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
