### ISSUE TITLE
IdSvr4 implementation with multiple API's and clients that dont share SSO?

### ISSUE THREAD

**Issue by garymacpherson** [IdentityServer/IdentityServer4#974]
I have an IdSvr4 tech demo set up to try and address some issues we have with our existing IdSvr3 implementation.

The one and only problem we have left prior to making the switch and rewriting is to ensure that IdSvr4 has an in-spec solution to having a single API registered across multiple instances of identity server.

Our use case essentially boils down to this:
We have multiple client applications, all with different styled login pages, different login forms, different user stores and most importantly, we cannot have single sign-on between them, it is logically senseless to have SSO between almost all the clients. This has lead us down the path of wanting multiple instances of IdSvr4, one for each logical separation of what should and should not be sharing SSO.

We now have a few API's that we want to protect with IdSvr, most of which are only accessed by 1 client with 1 IdSvr authority, however there are a few API's that will be used by all of our clients, and therefor need to be able to have all of our instances of IdSvr as potential authorities.

So, I was thinking the solution to that is to have a single instance of IdSvr that acts as the authority for all clients and API's, but then just acts as a gateway to route the requests to the appropriate clients authority (the other instances)? If so, what is the correct approach in IdSvr4, as I have found very little documentation compared to 3?

Or am I wrong from the get-go and it is entirely appropriate to have clients that do not share SSO on the same instance of IdSvr? If so, how do you selectively prevent SSO?

Thanks very much for any comments!

**Comment by leastprivilege** [comment]
How about you issue an "app group" claim when the uses signs in (both cookie and tokens).

This way you can check whenever he comes back if he is in the right "SSO group" or not - and show the login page - or not.

**Comment by garymacpherson** [comment]
> How about you issue an "app group" claim when the uses signs in (both cookie and tokens).

And that would still allow a user to be signed into client X with one set of credentials at the same time as client Y with another in the same browser?

I will incorporate that into my demo and comment if I find something interesting or blocking.

**Comment by leastprivilege** [comment]
Yes.

The most seamless way to do that is to derive from our AuthorizationInteractionGenerator - call the base class first - then check the claims of the user and the client he wants to sign in to.

If all is good do nothing - otherwise set IsLogin to true.

(I haven't checked the exact names - but something along those lines).

**Comment by garymacpherson** [comment]
So I tested the following

    public class MyCustomAuthIntResGen : AuthorizeInteractionResponseGenerator
    {
        public MyCustomAuthIntResGen(ILogger<AuthorizeInteractionResponseGenerator> logger, IdentityServerOptions options, IConsentService consent, IProfileService profile) : base(logger, options, consent, profile)
        {
        }

        public override async Task<InteractionResponse> ProcessInteractionAsync(ValidatedAuthorizeRequest request, ConsentResponse consent = null)
        {
            var result = await base.ProcessInteractionAsync(request, consent);

            var client = request.ClientId;
            var clientGroup = getClientGroup(client);
            var user = ??????????????;
            if (user.IsAuthenticated() && !result.IsConsent && !user.Claims.Any(x => x.Type == "client_group" && x.Value == clientGroup))
            {
                result.IsLogin = true;
            }

            return result;
        }

        private string getClientGroup(string client)
        {
            switch (client)
            {
                case "mvc2":
                    return "Group1";
                case "mvc3":
                    return "Group2";
                default:
                    throw new NotImplementedException();
            }
        }
    }

But now I am lost where to get the users claims from? 

I tried added the claim on the `AccountController.cs` HttpPost Login function, but when I try and pick up the claims in `ProcessInteractionAsync it only has the claims sub, name, idp, auth_time and amr on the request.Subject object... not any of the actual users claims.

**Comment by leastprivilege** [comment]
Rather override ProcessLogin - the request has a Subject property (which might be null for anon users).

**Comment by garymacpherson** [comment]
the `ValidatedAuthorizeReqest request`?

Same problem, always only got the claims sub, name, idp, auth_time and amr

**Comment by leastprivilege** [comment]
and did you set the app group on signin?

**Comment by garymacpherson** [comment]
I believe so, with the following in `AccountController.cs` based on the Quickstart.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginInputModel model)
        {
            if (ModelState.IsValid)
            {
                // validate username/password against in-memory store
                if (_users.ValidateCredentials(model.ApplicationId, model.Email, DateTime.Parse(model.DateOfBirth).ToString("dd/MM/yyyy", CultureInfo.InvariantCulture)))
                {
                    AuthenticationProperties props = null;
                    // only set explicit expiration here if persistent. 
                    // otherwise we reply upon expiration configured in cookie middleware.
                    if (AccountOptions.AllowRememberLogin && model.RememberLogin)
                    {
                        props = new AuthenticationProperties
                        {
                            IsPersistent = true,
                            ExpiresUtc = DateTimeOffset.UtcNow.Add(AccountOptions.RememberMeLoginDuration)
                        };
                    };

                    // issue authentication cookie with subject ID and username
                    var user = _users.FindByAppId(model.ApplicationId);
                    await HttpContext.Authentication.SignInAsync(user.SubjectId, user.ApplicationId, props);

                    var context = await _interaction.GetAuthorizationContextAsync(model.ReturnUrl);
                    switch (context.ClientId)
                    {
                        case "mvc2":
                            user.Claims.Add(new Claim("client_group", "Group1"));
                            break;
                        case "mvc3":
                            user.Claims.Add(new Claim("client_group", "Group2"));
                            break;
                        default:
                            break;
                    }

                    // make sure the returnUrl is still valid, and if yes - redirect back to authorize endpoint
                    if (_interaction.IsValidReturnUrl(model.ReturnUrl))
                    {
                        return Redirect(model.ReturnUrl);
                    }

                    return Redirect("~/");
                }

                ModelState.AddModelError("", AccountOptions.InvalidCredentialsErrorMessage);
            }

            // something went wrong, show form with error
            var vm = await _account.BuildLoginViewModelAsync(model);
            return View(vm);
        }

And I can see that the claim does exist on the object by the end of this function.

**Comment by garymacpherson** [comment]
So I implemented my own `IProfileService` and resolved my issue where I wasn't getting any claims at all when using the TestUserStore, however my problem still stands that there is no claims on the request object in my `AuthorizeInteractionResponseGenerator` because the profile service isn't called until after `AuthorizeInteractionResponseGenerator.ProcessLoginAsync()`

**Comment by leastprivilege** [comment]
Well - of course - 

if the user is anonymous there will be no claims. But for a returning user, there will be claims. And that's exactly what you need to read the appgroup claim.

Or am I missing something?

**Comment by garymacpherson** [comment]
On the returning user it is still empty. I'll run through everything again to see if I missed a silly mistake and see what happens.

**Comment by garymacpherson** [comment]
Same problem - 

- 2 MVC clients on 2 ports
- Same IdSvr4 instance as their authority
- Hit a page that requires sign in on the first MVC client
- IdSvr AuthorizeInteractionResponseGenerator gets hit
- within ProcessInteractionAsync and ProcessLoginAsync request.Subject.Claims just has {http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name: } which is expected
- call base class and move on
- login page gets rendered
- enter valid credentials
- AccountController.Login gets hit, and I throw in my client_group claim depending on the ClientId
- AuthorizeInteractionResponseGenerator gets hit again
- within ProcessInteractionAsync and ProcessLoginAsync request.Subject.Claims now has sub, name, idp, auth_time and amr claims as expected
- call base class and move on
- consent page rendered - accept all
- AuthorizeInteractionResponseGenerator gets hit again still with request.Subject.Claims having sub, name, idp, auth_time and amr claims as expected
- call base class and move on
- ProfileService.GetProfileDataAsync gets hit
- context.IssuedClaims gets populated with name, address, website, client_group, etc. all the claims that I would need
- Hit a page that requires sign in on the **second** MVC client
- AuthorizeInteractionResponseGenerator gets hit
- Within ProcessInteractionAsync and ProcessLoginAsync request.Subject.Claims still just has sub, name, idp, auth_time and amr claims.
- Without the the address, website, client_group etc. all of the claims that got thrown in by the ProfileService how am I supposed to know whether to throw them the login screen or not?

What am I doing wrong?

**Comment by leastprivilege** [comment]
When you call SignInAsync - do you add the app group claim?

**Comment by garymacpherson** [comment]
I believe so... within `AccountController`

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginInputModel model)
        {
            // the rest of the function
    
            var user = _users.FindByAppId(model.ApplicationId);

            var context = await _interaction.GetAuthorizationContextAsync(model.ReturnUrl);
            switch (context.ClientId)
            {
                case "mvc2":
                    user.Claims.Add(new Claim("client_group", "Group1"));
                    break;
                case "mvc3":
                    user.Claims.Add(new Claim("client_group", "Group2"));
                    break;
                default:
                     break;
                }

            await HttpContext.Authentication.SignInAsync(user.SubjectId, user.ApplicationId, props);

            // the rest of the function
        }

**Comment by leastprivilege** [comment]
I don't see it.


-------
Dominick Baier

**Comment by leastprivilege** [comment]
SignInAsync has an overload to pass in additional claims - right now you are only setting subject id and application id.

**Comment by garymacpherson** [comment]
... wow. Can't see the wood for the trees.

Thank you so much.

Invaluable assistance again as always.

**Comment by garymacpherson** [comment]
@leastprivilege apologies for all the questions, just wondering if I could get closure on my above comment.

What is the current best way to handle staying signed into multiple clients concurrently? Is it the Identities concept that currently exists in the codebase but hasn't been implemented? Is there something else that can be done now? Do you have plans for implementing that feature on your roadmap?

**Comment by leastprivilege** [comment]
We don't have multiple identities on the roadmap.

Do you know a social/commercial provider that implements that?

**Comment by garymacpherson** [comment]
No I don't, I even can't think of a generic scenario where it would really make sense so I understand it isn't a priority, just one of the nice-to-haves for our specific internal/corporate needs.

Thanks for the information.

**Comment by leastprivilege** [comment]
and it is also really hard to get right ;)
