### ISSUE TITLE
Shared Key vs Redirect uri

### ISSUE THREAD

**Issue by Skoucail** [IdentityServer/IdentityServer4#975]
We are creating some mobile apps (android and IOS) that should access our API.
For user authorization we are using identityserver4.

During my research i fond out that using the Resource Owner Password Credentials flow is not good because an mobile app (public client) can not keep the Shared Key secret. And i fully agree with that.
As the alternative they say to use the Hybrid flow. This flow does not a shared key but an redirect uri to check if the client is allowed to request tokens. As i understand it correct the redirect uri is also not a protected against disassembly etc. 

So my questing, what is the added security with the Hybrid flow?
Unless i'm missing something both systems do not protect against someone else duplicating my app to get access to the tokens.

**Comment by leastprivilege** [comment]
Nothing protects you from that. 

But there still needs to be a valid user to use that "duplicated" app - which is an explicit trust decision.

Also read this:
https://tools.ietf.org/html/draft-ietf-oauth-native-apps-09

**Comment by Skoucail** [comment]
Thanks for the link!
I still have to read in in depth but during my quick read i still havent found an answer about what makes the autorizationcode flow better then the resource owner password credential flow. (Given the app is from the same company as the api and identityserver). But all oauth documentation says that the resource owner password credential flow is bad practise (only use in legacy applications), but no explaination why.

**Comment by brockallen** [comment]
You don't get SSO and the client app must handle the credentials.
