### ISSUE TITLE
Is it Possible to store Persisted Grants in the DB while leaving Resources/Clients in Memory?

### ISSUE THREAD

**Issue by ttugates** [IdentityServer/IdentityServer4#978]
- [ ] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
        services.AddIdentityServer((options) =>
        {
            options.UserInteraction = new UserInteractionOptions
            {
                LoginUrl = "/login",
                LogoutUrl = "/api/Account/Logout",
                ErrorUrl = "/error"
            };
        })
        .AddSigningCredential(X509CertificateHelper.getCert(_env))           
        .AddOperationalStore(builder => builder.UseSqlServer(connectionString,
            options => options.MigrationsAssembly(migrationsAssembly)))
        .AddInMemoryIdentityResources(Config.GetIdentityResources())
        .AddInMemoryApiResources(Config.GetApiResources())
        .AddInMemoryClients(Config.GetClients(AppSettingsHelper.GetIdSrvrSettings()))
        // .AddConfigurationStore(builder => builder.UseSqlServer(connectionString,
        // options => options.MigrationsAssembly(migrationsAssembly))) 
        .AddAspNetIdentity<ApplicationUser>();

### Relevant parts of the log file
When running `dotnet ef database update -c PersistedGrantDbContext`
```
An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Cannot perform runtime binding on a null reference
```

**Comment by brockallen** [comment]
> Is it Possible to store Persisted Grants in the DB while leaving Resources/Clients in Memory

Yes. Those are all different extensibility points.

**Comment by ttugates** [comment]
To be able to run `dotnet ef database update -c PersistedGrantDbContext` and seed the PersistedGrants table, I have to comment out:
```
   // .AddInMemoryIdentityResources(Config.GetIdentityResources())
   // .AddInMemoryApiResources(Config.GetApiResources())
   // .AddInMemoryClients(Config.GetClients(AppSettingsHelper.GetIdSrvrSettings()))
```
and uncomment:
```
    .AddConfigurationStore(builder => builder.UseSqlServer(connectionString,
    options => options.MigrationsAssembly(migrationsAssembly))) 
```
After running database update on the PersistedGrantDbContext successfully, I can then comment out the  
`.AddConfigurationStore..`  and uncomment the  `.AddInMemoryIdentityResources/ApiResources/Clients`  and everything works seemingly as desired.

.NET Core, DI and the Factory Pattern are new for me.  Assuming the above does not stand out as `.AddConfigurationStore` and `.AddOperationalStore` are dependent on each other, at the least for seeding the Db; I will focus on learning how to use IDbContextFactory  and how EF7 MigrationsAssembly work.

Thanks..

**Comment by ttugates** [comment]
For anyone else with same road block,
I ultimately solved this by implementing IPersistedGrantStore with help [from the following](http://stackoverflow.com/questions/43002160/its-is-possible-to-use-addoperationalstore-for-persistedgrants-with-inmemoryre/43040727#43040727) like so:

```
            services.AddIdentityServer((options) =>
            {
                options.UserInteraction = new UserInteractionOptions
                {
                    LoginUrl = "/login",
                    LogoutUrl = "/api/Account/Logout",
                    ErrorUrl = "/error"
                };
            })
           .AddSigningCredential(X509CertificateHelper.getCert(_env))            
           .AddOperationalStore(builder => builder.UseSqlServer(connectionString,
            options => options.MigrationsAssembly(migrationsAssembly)))
           .AddInMemoryIdentityResources(Config.GetIdentityResources())
           .AddInMemoryApiResources(Config.GetApiResources())
           .AddInMemoryClients(Config.GetClients(AppSettingsHelper.GetIdSrvrSettings()))
           .AddAspNetIdentity<ApplicationUser>();

            services.AddTransient<IPersistedGrantStore, PersistedGrantStore>();
```

And wiring up a PersistedGrantStore : IPersistedGrantStore

**Comment by mithun-daa** [comment]
I am trying something similar but my code never gets to my persisted store class at all.

**Comment by brockallen** [comment]
>  but my code never gets to my persisted store class at all

depends on the use cases if the store gets hit

**Comment by ttugates** [comment]
Without more details, its hard to know how to help.  

The following is what I learned that helped me today and quite possibly is no help to you.  All the same.
-  When you run `dotnet ef ...` the entry point of the program is not Program.Main.  I was reading my config file in Main, and only got the above mentioned error when running `dotnet ef` commands.  

To diagnose `dotnet ef` commands, append --verbose to them.

I learned this from [here](http://stackoverflow.com/questions/39574124/consider-using-idbcontextfactory-to-override-the-initialization-of-the-dbcontext/40121503#40121503).

**Comment by mithun-daa** [comment]
I was trying something similar to @ttugates where I was using in-memory clients and api resources. Once I deployed it to a load balanced environment to test I was getting errors. Those were, I am assuming, because of the `jwki` uri keys. So after reading up a little more I realized I had to have a persisted grant stored. I am wrong to think that the persisted grant store will solve my issue?
So, I tried to implement the interface and store stuff in Redis instead of SQL Server but I could never hit the any breakpoints in my code.

**Comment by brockallen** [comment]
> Once I deployed it to a load balanced environment to test I was getting errors

In a load balanced environment you will need to set a signing credential and use the same one across the 2 machines. Also, depending on the client flows, you will need to set a persisted grant store.

**Comment by mithun-daa** [comment]
> you will need to set a signing credential and use the same one across the 2 machines

You mean, set up a cert using `AddSigningCredential` right? Ran into a weird error when I tried this yesterday. It was not able to find the cert even when I could see it in the certificate manager.

>Also, depending on the client flows, you will need to set a persisted grant store. 

We are using only the implicit flow as of now.

**Comment by brockallen** [comment]
> We are using only the implicit flow as of now - used entirely to authenticate human users and to support SSO.

So no need for persistent grants, unless you are enabling consent.

**Comment by mithun-daa** [comment]
Awesome! One last Q. Can I pass any cert (under Personnal) on a machine to `AddSigningCredential`? Is there any restriction if that cert needs to be a special kind? When I tried locally on my machine with a self signed cert from IIS it worked fine but in our testing environments I am trying to use domain issued certs which it does not seem to like.

**Comment by brockallen** [comment]
If you can load it yourself, you can pass the x509 cert object. You might have DACL issues. That's been covered a ton elsewhere.

**Comment by mithun-daa** [comment]
Good pointers for me to look into. Thank you!

**Comment by mithun-daa** [comment]
@brockallen Noob question: Do you know if I can add a cert using a friendly name instead of a CN.

```
.AddSigningCredential("CN=MyCert")
```

**Comment by osudude** [comment]
@brockallen Which flows in a load balanced environment need a custom / persistent implementation of IPersistedGrantStore?

**Comment by brockallen** [comment]
read the docs: https://identityserver4.readthedocs.io/en/release/topics/deployment.html

**Comment by osudude** [comment]
@brockallen Sorry, guess I missed that in the docs.  Was just asking based upon your previous comment re: load balance environment.
