### ISSUE TITLE
CORS problem when calling from angular 2 application

### ISSUE THREAD

**Issue by mohamed-elsabagh** [IdentityServer/IdentityServer4#979]
I am trying to get access token from my remote identity server using http request, I already can do this using android client and postman but can't do this from my chrome running my angular app.

I am getting the following error 
``` 
XMLHttpRequest cannot load http://myidentityserverip.com:5000/connect/token. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 400.
```

I checked the CORS page in documentation but it's still empty, is there any good example of how I can do this and should I do it on both my API (.Net core guarded by identity server), and my IDS as well?

**Comment by brockallen** [comment]
Enable AllowedCorsOrigins on the client config.

**Comment by mohamed-elsabagh** [comment]
I already did but I am getting the same error, what are the origins I should give to AllowedCorsOrigins since I am not sure about the client IP address which will generate the request

**Comment by brockallen** [comment]
If you are using AddInMemoryClients, then it should work. If not, and you're using EF then it should also work. If not, then you need to implement your own CorsPolicyService. Origin is the combination of protocol, host, and port (not the URL).

**Comment by mohamed-elsabagh** [comment]
Here is my implementation of the IS which is working fine as I mentioned using clients like postman
```
// Feed the name of the certificate file and the password when the file was created
            var cert = new X509Certificate2(Path.Combine(_environment.ContentRootPath, "mycert.pfx"), "mycert_0");

            var builder = services.AddIdentityServer()
                .AddSigningCredential(cert)
                .AddInMemoryIdentityResources(IdentityConfiguration.GetIdentityResources())
                .AddInMemoryApiResources(ApiResourceConfiguration.GetApiResources());

            builder.Services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();
            builder.Services.AddTransient<IProfileService, ProfileService>();
            builder.Services.AddTransient<IClientStore, ClientStore>();
            builder.Services.AddTransient<IPersistedGrantStore, PersistedGrantStore>();
```

Here is my Client 
```
var client = new ClientModel
            {
                Enabled = true,
                ClientName = Constants.DEFAULT_CLIENT_NAME,
                ClientId = Constants.DEFAULT_CLIENT_ID,
                AllowOfflineAccess = true,
                AllowedCorsOrigins = { Constants.AUTHENTICATION_SERVER },
                AllowedGrantTypes = GrantTypes.List(
                        GrantType.ResourceOwnerPassword,
                        GrantType.ClientCredentials
                        ),
                ClientSecrets =
                    {
                        new Secret(Constants.DEFAULT_CLIENT_SECRET.Sha256())
                    },
                AllowedScopes = new List<string>
                    {
                        Constants.API_SCOPE_NAME_CORE
                    }
            };
```
I am not using AddInMemoryClients however I am reading them externally from database, I am not sure what does EF means.
can you please guide me how can implement my own CorsPolicyService?

**Comment by brockallen** [comment]
>  I am reading them externally from database, 

So then you also need to implement the ICorsPolicyService: https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/Interfaces/ICorsPolicyService.cs

**Comment by mohamed-elsabagh** [comment]
@brockallen you are amazing as always, thanks so much

**Comment by AliShd** [comment]
@mohamed-elsabagh, @brockallen I am having the exact same issue. Can you please share how can I implement ICorsPolicyService?

**Comment by chrisdrobison** [comment]
They have a sample implementation in the quick start examples.

**Comment by AliShd** [comment]
@chrisdrobison Can you please share the link?

**Comment by chrisdrobison** [comment]
Here is the link to the default implementation:
https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Services/DefaultCorsPolicyService.cs

**Comment by chrisdrobison** [comment]
Here is a link to the entity framework implementation:
https://github.com/IdentityServer/IdentityServer4.EntityFramework/blob/dev/src/IdentityServer4.EntityFramework/Services/CorsPolicyService.cs

**Comment by AliShd** [comment]
Thank you @chrisdrobison. I did the same implementation but still no success. Don't know what I am missing:

```
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    // This method gets called by the runtime. Use this method to add services to the container.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddCors(options =>
        {
            options.AddPolicy("AllowSpecificOrigin",
                builder => builder
                    .WithOrigins("http://localhost:4200")
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials()
                );
        });

        services.AddIdentityServer()
            .AddDeveloperSigningCredential()
            .AddInMemoryApiResources(Config.GetApiResources())
            .AddInMemoryClients(Config.GetClients());

        services.AddMvcCore()
            .AddApiExplorer()
            .AddAuthorization()
            .AddJsonFormatters();

        services.AddAuthentication("Bearer")
            .AddIdentityServerAuthentication(options =>
            {
                options.Authority = "http://localhost:5000";
                options.RequireHttpsMetadata = false;
                options.ApiName = "userInfo";
            });

        services.AddSingleton<IConfiguration>(Configuration);

        // Register application services.
        services.AddTransient<IResourceOwnerPasswordValidator, ResourceOwnerPasswordValidator>();
        services.AddTransient<IUserRepository, UserRepository>();
        services.AddTransient<ICorsPolicyService, DemoCorsPolicy>();
        ...
    }

    // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
    {
        if (env.IsDevelopment())
        {
            loggerFactory.AddConsole();
            app.UseDeveloperExceptionPage();
        }

        app.UseCors("AllowSpecificOrigin");

        app.UseIdentityServer();

        app.UseAuthentication();

        app.UseMvc();
    }
}

// Allows arbitrary CORS origins - only for demo purposes
public class DemoCorsPolicy : ICorsPolicyService
{
    public Task<bool> IsOriginAllowedAsync(string origin)
    {
        return Task.FromResult(true);
    }
}
```

**Comment by brockallen** [comment]
If you need CORS for the IdentityServer endpoints, then you don't need to add CORS yourself via ASP.NET COre with the call to UseCors. All you'd need to do is either configure the client with AllowedCorsOrigins and use our ICorsPolicyService, or you implement your own ICorsPolicyService and do whatever you need/want. Only use UseCors if you have your own endpoints beyond those of IdentityServer you need CORS support for. 

If our docs don't make this clear, then please submit a PR to improve them.

**Comment by AliShd** [comment]
@brockallen I have my own endpoints as well other than the IdentityServer's. I first enabled CORS using the UseCors method and everything was working fine thru my Angular app (on different domain). But after adding IdentityServer CORS just stopped working and for which I also tried implementing the ICorsPolicyService as you can see in the above code. Here you can check the Client configuration as well:

```
new Client
{
    ClientId = "client",
    ClientName = "Angular app",
    AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
    AllowAccessTokensViaBrowser = true,
    RequireClientSecret = false,
    AllowedScopes = new List<string> { "openid", "profile", "userInfo" },
    RedirectUris = new List<string> {"http://localhost:4200/auth-callback", "http://localhost:4200/silent-refresh.html"},
    PostLogoutRedirectUris = new List<string> {"http://localhost:4200/"},
    AllowedCorsOrigins = new List<string> {"http://localhost:4200"},
}
```

**Comment by brockallen** [comment]
Have you read the CORS docs? http://docs.identityserver.io/en/release/topics/cors.html

> just stopped working

This is not helpful. You need to trace the HTTP calls to find out where it's not working and why. Inspecting the HTTP request and response will lead you there.

**Comment by AliShd** [comment]
Getting this error on log:

![image](https://user-images.githubusercontent.com/10972060/32736170-97f248c2-c8b8-11e7-8320-8835e68c2f2a.png)

**Comment by brockallen** [comment]
So there's your answer!

**Comment by AliShd** [comment]
@brockallen Thanks a lot man. Adding `options.ApiSecret` to `AddIdentityServerAuthentication` has solved the issue. 👍
