### ISSUE TITLE
MVC and API sample solution not opening in VS2015 Community edition

### ISSUE THREAD

**Issue by akajains** [IdentityServer/IdentityServer4#98]
When I try to open the sample solution in Visual studio 2015, there is an error during the project load. (please look at the screenshot)

![23-05-2016 11-35-48 am](https://cloud.githubusercontent.com/assets/7066357/15458234/93b012f8-20da-11e6-88da-5ae1dad41d5f.jpg)

I found a related issue - https://github.com/NuGet/Home/issues/2616

But this doesn't help. Did anyone faced it or resolved it successfully?

**Comment by brockallen** [comment]
Delete the ".vs? folder if you see one and try again, please. Not sure if this is the issue, but we've had lots of VS tooling problems when moving projects from machine to machibne.

**Comment by Silwood** [comment]
Try to upgrade  Microsoft .NET Core Tools (Preview 1) to RC2. It worked for me. It didn't work in In RC1 but works OK after update to RC2.

**Comment by akajains** [comment]
I will try these suggested solutions and post my findings.

**Comment by leastprivilege** [comment]
You need update 2 and the RC2 tooling.
