### ISSUE TITLE
Invalid scope when API resource constructor is not parameterized  

### ISSUE THREAD

**Issue by defyjoy** [IdentityServer/IdentityServer4#980]
I tried with two things . ..... 

**One which works --** 
 ```
new ApiResource("mvc", "Storyboard Mvc App"){
                    UserClaims= { "name" , "email"},
                    ApiSecrets = { new Secret("secret".Sha256())},
  },
```

But when I Do this -- 

 ```
               new ApiResource
                {
                    Name="mvc",
                    DisplayName="Storyboard Mvc App",
                    UserClaims = {"name","email"},
                    ApiSecrets = { new Secret("secret".Sha256())},
                },
```

It doesnt work at all. All it gives is invalid scope . WHY !! :( 

![capture](https://cloud.githubusercontent.com/assets/1047068/24324469/b26cd99c-11ac-11e7-8c81-ee79409ba1e1.JPG)

And here is my OpenId configuration for Mvc app --

![image](https://cloud.githubusercontent.com/assets/1047068/24324477/f26a9034-11ac-11e7-9a11-546b2d5d499f.png)

**Comment by leastprivilege** [comment]
The ctor is a convenience for setting name and scope in one go. If you don't use it you need to create the scope yourself.
