### ISSUE TITLE
Getting Error "https://localhost:44358/home/error?errorId=08e36a48955f31ea67525c7d3b0a1792"

### ISSUE THREAD

**Issue by ShashikantMaurya** [IdentityServer/IdentityServer4#984]
Hi,

I have used below Configuration in identity server 4

 public class Config
    {
        // scopes define the resources in your system
        public static IEnumerable<IdentityResource> GetIdentityResources()
        {
            return new List<IdentityResource>
            {
                new IdentityResources.OpenId(),
                new IdentityResources.Profile(),
                new IdentityResources.Email(),
                new IdentityResource
                {
                    Name = "role",
                    UserClaims = new List<string> {"role"}
                }
            };
        }

        public static IEnumerable<ApiResource> GetApiResources()
        {
            return new List<ApiResource>
            {
                new ApiResource
                {
                    Name = "customAPI",
                    DisplayName = "Custom API",
                    Description = "Custom API Access",
                    UserClaims = new List<string> {"role"},
                    ApiSecrets = new List<Secret> {new Secret("scopeSecret".Sha256())},
                    Scopes = new List<Scope>
                    {
                        new Scope("customAPI.read"),
                        new Scope("customAPI.write")
                    }
                }
            };
        }

        // clients want to access resources (aka scopes)
        public static IEnumerable<Client> GetClients()
        {
            // client credentials client

            return new List<Client>
            {
                new Client
                {
                    ClientId = "oauthClient",
                    ClientName = "Example Client Credentials Client Application",
                    AllowedGrantTypes = GrantTypes.ClientCredentials,
                    ClientSecrets = new List<Secret>
                    {
                        new Secret("superSecretPassword".Sha256())
                    },
                    AllowedScopes = new List<string> {"customAPI.read"}
                },
                new Client
                {
                    ClientId = "openIdConnectClient",
                    ClientName = "Example Implicit Client Application",
                    AllowedGrantTypes = GrantTypes.Implicit,
                    AllowedScopes = new List<string>
                    {
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.Email,
                        "role",
                        "customAPI"
                    },
                    RedirectUris = new List<string> {"https://localhost:44330/signin-oidc"},
                    PostLogoutRedirectUris = new List<string> { "https://localhost:44330" }
                }
            };
        }
    }

and i am using below code for MVC Client

 app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies"
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "openIdConnectClient",
                Authority = "https://localhost:44358",                              
                SignInAsAuthenticationType = "Cookies",
                ResponseType = "id_token",
                Scope = "openid profile",                               
            });

Please help me

```
<log goes here>
```

**Comment by leastprivilege** [comment]
check the logs.

**Comment by ShashikantMaurya** [comment]
Where to find logs

**Comment by leastprivilege** [comment]
read the docs ;)

**Comment by dave-hillier** [comment]
This page is top hit from google. "Read the docs ;)" and "check the logs" are useless responses for others trying to diagnose the same issue. In future, can you please post links to relevant pages of the docs.

**Comment by Vuurwarm** [comment]
So I don't have an answer but I got some insight on the problem:

to see what the error code means I Injected the `IIdentityServerInteractionService` into my controllers constructor.

Added an extra function that accepts the errorId
`public async Task<IActionResult> error(string errorId)
        {
            var errormessage = await identity.GetErrorContextAsync(errorId);
        }`

After I inspected the errorMessage object the message read
`Invalid redirect_uri`
and it seems my `RedirectUri` property is null

hope this helps someone. 

but yes still don't have a proper solution
[http://docs.identityserver.io/en/release/reference/interactionservice.html?highlight=GetErrorContextAsync](url)

**Comment by SIkebe** [comment]
@Vuurwarm Wrong URL 😉 
http://docs.identityserver.io/en/release/reference/interactionservice.html?highlight=GetErrorContextAsync

**Comment by Vuurwarm** [comment]
@SIkebe ah, woops. Removed it. Was more in line of "read further" type thought. 

But yes, was able to get what my problem was. So the redirect URl that it used was /signin-oidc which i believe clashed with the fact the user is already logged in. We just opted to showing the user a page saying Email has been confirmed.

**Comment by Quentinb** [comment]
Pretty poor response from @leastprivilege. Would have expected better considering they build it. If I find useful info, I'll post it here to help others. Facing the same issue. Off to "Read the docs"...

**Comment by Michaelwan777** [comment]
> Pretty poor response from @leastprivilege. Would have expected better considering they build it. If I find useful info, I'll post it here to help others. Facing the same issue. Off to "Read the docs"...
> 
> For starters: http://docs.identityserver.io/en/latest/reference/options.html?highlight=errorId
> Using Serilog is also useful: http://docs.identityserver.io/en/latest/topics/logging.html
> 
> In my case, my client configuration is invalid
> 
> [12:06:25 DBG] js found in database: True
> [12:06:25 ERR] Invalid client configuration for client js: No redirect URI configured.
> [12:06:25 ERR] Unknown client or not enabled: js
> 
> I've not found a way to user the errorId yet, but will update the comment if I find something.
> 
> Update:
> Found some useful info here:
> 
> #1002
> 
> and here:
> 
> https://github.com/IdentityServer/IdentityServer4/blob/db1affb8a6574b90881c9a3da7a5ad1ec2e996b7/src/Host/Quickstart/Home/HomeController.cs#L29

@Quentinb  Thanks for reference! It seems the actual View page for Error is missing in that repo.
