### ISSUE TITLE
Question: Storing the ReturnUrl 

### ISSUE THREAD

**Issue by ksond** [IdentityServer/IdentityServer4#986]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

Hi..when user hits the MVC client it gets redirected to IdSrv4 and has the returnUrl, but when user clicks any other link on the top of the page (links in partial layout view - Register and Login) it loses the returnUrl. How can i save the returnUrl...??

Also, when user resets the password and hit the login link, how to get it redirected to the client as it doesnt have the return url at this point (unless its hard coded)

Thanks for your help!

**Comment by brockallen** [comment]
>  How can i save the returnUrl...??

That's up to you -- you'd need to code the UI to not lose it.

> Also, when user resets the password and hit the login link, how to get it redirected to the client as it doesnt have the return url at this point (unless its hard coded)

Again, the UI in the application that hosts IdentityServer is entirely up to you. IdentityServer is just handling the OIDC protocol endpoints, and it periodically passes some context to your UI, which you then need to manage if you have complex UI workflows.

**Comment by ksond** [comment]
Thanks for replying. I am using a static string to store the url now, just wanted to confirm we don't have something in build already! :)

**Comment by brockallen** [comment]
> I am using a static string to store the url now

Doesn't sound like that would handle multiple concurrent users.

So can we close this issue then?

**Comment by ksond** [comment]
So what do you prefer then...?

**Comment by brockallen** [comment]
If your problem is solved, then I'd prefer to close this issue.

**Comment by ksond** [comment]
Well still looking for the best solution but you can go ahead and close the issue. Thanks!
