### ISSUE TITLE
How can I test if api is contacting identity server?

### ISSUE THREAD

**Issue by nukec** [IdentityServer/IdentityServer4#991]
I wrote an endpoint in web api and put [Authorize] attribute on endpoint. In my api settings there is identityserver settings added:

     JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
                IdentityServerAuthenticationOptions identityServerValidationOptions = new IdentityServerAuthenticationOptions
                {
                    Authority = "https://localhost:5001/",
                    AllowedScopes = new List<string> { "api" },
                    ApiSecret = "apiSecret",
                    ApiName = "api",
                    AutomaticAuthenticate = true,
                    SupportedTokens = SupportedTokens.Both,
                    // TokenRetriever = _tokenRetriever,
                    // required if you want to return a 403 and not a 401 for forbidden responses
                    AutomaticChallenge = true,
                };
    
                app.UseIdentityServerAuthentication(identityServerValidationOptions);

In identtiyserver I added apiResource:

    public static IEnumerable<ApiResource> GetApiResources()
    {
        return new List<ApiResource>
        {
            new ApiResource("api", "PI")
        };
    }

When I use postman to access API, there are no logs in identityServer that api was trying to access identityServer to validate authorization. If i access identityserver direct via postman, logs are working. So logs are working, is there anything else I should check?

**Comment by leastprivilege** [comment]
In the case of JWTs - there is no back-channel communication between API and IdentityServer (besides the initial download of the discovery document).
