### ISSUE TITLE
Reference token is not updating with client claims on introspection call

### ISSUE THREAD

**Issue by Anp-tomsk** [IdentityServer/IdentityServer4#996]
Hello guys,

I'm using reference toke and client credentials for flow for authentication. And face a problem that reference token payload is not updated in case when i add claims to client. So i checked your sources and find out that it send to Resource only those client claims that was used during token generation. M.b. i miss something and it is designed to work like that (in this case is there any way to generate persistent token with long lifetime period that would provide updated client claims?)

Snippest from [TokenValidator](https://github.com/IdentityServer/IdentityServer4/blob/ec17672d27f9bed42f9110d73755170ee9265116/src/IdentityServer4/Validation/TokenValidator.cs)
```
        private IEnumerable<Claim> ReferenceTokenToClaims(Token token)
        {
            var claims = new List<Claim>
            {
                new Claim(JwtClaimTypes.Issuer, token.Issuer),
                new Claim(JwtClaimTypes.NotBefore, token.CreationTime.ToEpochTime().ToString(), ClaimValueTypes.Integer),
                new Claim(JwtClaimTypes.Expiration, token.CreationTime.AddSeconds(token.Lifetime).ToEpochTime().ToString(), ClaimValueTypes.Integer)
            };

            foreach (var aud in token.Audiences)
            {
                claims.Add(new Claim(JwtClaimTypes.Audience, aud));
            }

            claims.AddRange(token.Claims);
            return claims;
        }
```

As i'm using EF.core IdentityServer4 aswell i can update Data Row in PersistedGrants table with regenerated token, but i honestly don't think that it is the right way to do this. 
Would it make sens if token would be regenerated based on client claims in each introspection call?

**Comment by leastprivilege** [comment]
Claims for reference tokens are not getting updated.

Why reference tokens - this is an unusual combination for client cred flow. Why not have shorter lived JWTs?

**Comment by Anp-tomsk** [comment]
In my case i have to provide long term token to access API resources for client, with possibility to revoke token by admin and adjustable list of resources that client have access to. I thought that reference token would feet perfectly as it provide possibility for revocation and is not self contained so i thought that during introspection call it can provide updated information about client claims and allowed scopes.

**Comment by leastprivilege** [comment]
Not right now. We are re-working the introspection endpoint right now to allow such a feature.

**Comment by leastprivilege** [comment]
That said - you can also today implement your own `IIntrospectionResponseValidator` and change the returned claims on the fly. It is not as clean as we want it, but it would work.

**Comment by Anp-tomsk** [comment]
Thanks it sounds feasible for me.

**Comment by tiaroque** [comment]
Is this working now, I am using reference token and client credentials and I dont get the Claims in the User principal in the .net core

**Comment by RomainWilbert** [comment]
I don't understand the current behavior. I get that JWT token can't be updated, but for reference token claims should not be stored with the grant, but read again on introspection. Where are we concerning introspection re-work ? Will this featured be supported by next version ?
