### ISSUE TITLE
HTTP issuer being published instead of HTTPS in .well-known/openid-configuration

### ISSUE THREAD

**Issue by mithun-daa** [IdentityServer/IdentityServer4#998]
- [x] I read and understood how to enable [logging](https://identityserver4.readthedocs.io/en/release/topics/logging.html)

### Issue / Steps to reproduce the problem
N/A

Hello there, 
I have IdSrv set up and I have only a HTTPS binding on it in IIS. However, when I browse to .well-known/openid-configuration I see that all the urls are HTTP instead of HTTPS. 
```
{"issuer":"http://xxx.com","jwks_uri":"http://xxx.com/.well-known/openid-configuration/jwks","authorization_endpoint":"http://xxx.com/connect/authorize","token_endpoint"....
```
The exact same code works just fine in my testing environments and the discovery endpoint correct exposes the issuer. What could I be doing wrong?

**Comment by leastprivilege** [comment]
You probably need to setup the forwarded header config / IIS integration

https://github.com/aspnet/Docs/issues/2384
