### ISSUE TITLE
IS4 Possibilities

### ISSUE THREAD

**Issue by juancash** [IdentityServer/IdentityServer4#999]
Hi, 
I have the following scenario:

ApiIdentity -> it´s my IdentityServer (developed with .Net Core and IS4 packages)
Api1 -> it´s an simple api developed with .Net Core and IdentityServer4 token validation packages. I have this code in the class Startup.cs:

```
app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
{
    Authority = "http://localhost:5000",
    RequireHttpsMetadata = false,
    ApiName = "api1",               
});
```

All works fine.

Now, I need develop a new api without net core (with .net framework). It´s possible use IS4 token validation with this api? How I can configure the API to UseIdentityServerAuthentication? because in a web api (without net core) the Startup.cs class is not available.

Thanks.

**Comment by brockallen** [comment]
Yes, we have OWIN middleware for this. Check here: https://github.com/IdentityServer/IdentityServer3.AccessTokenValidation/

**Comment by juancash** [comment]
@brockallen 

But the package IdentityServer3.AccessTokenValidation validates tokens issued by an IdentityServer4? because my IdentityServer was developed with version 4.

Thanks.

**Comment by brockallen** [comment]
Yes, they're compatible; see https://github.com/IdentityServer/CrossVersionIntegrationTests
